### ISSUE TITLE
Migration repo requires https address

### ISSUE THREAD

**Issue by joedborg** [gogits/gogs#1000]
```
 is not a valid URL.
```
Is the error received whenever the URL begins with http://.  Unfortunately, we can't all have access to https repositories.

**Comment by Unknwon** [comment]
Thanks your report!

We've found this problem ourselves, so it should be fixed in `dev` branch. You should be able to test on https://try.gogs.io/repo/migrate

**Comment by linquize** [comment]
By v0.6.1, it can migrate from `http://`, `https://` and `git://` protocols.

**Comment by Unknwon** [comment]
Close as implemented, feel free to continue discussion! :smile:
