### ISSUE TITLE
Emails are missing the Date header

### ISSUE THREAD

**Issue by srvg** [gogits/gogs#1002]
Bug report gogs 5.11

I noticed the Message struct is missing a date field, and in composing the message, no Date: header is created.

This Date header is a required header. I had user complained not receiving the password reset mail, as filters where refusing to accespt it based on this.

See also http://www.ietf.org/rfc/rfc2822.txt section 3.6

> The only required header fields are the origination date field and...

part of the relevant bounce notification is:

```
The message WAS NOT relayed to:
  <A@Borg>:
   554 5.6.0 Bounce, id=03337-17 - BAD HEADER

This nondelivery report was generated by the program amavisd-new at host
node-0001.somehost.tld. Our internal reference code for your message is
03337-17/P_LobZe0COHo

INVALID HEADER

  Missing required header field: "Date"
```

**Comment by Unknwon** [comment]
Thanks for your report!

**Comment by Unknwon** [comment]
Hi @srvg !

New implementation of mailer module in Gogs has been pushed to `develop`, please help test and see if problem has been solved. Thanks!

**Comment by Unknwon** [comment]
Close as fixed.
