### ISSUE TITLE
error 502 after secret_key change

### ISSUE THREAD

**Issue by b4dtR1p** [gogits/gogs#1003]
I change secret_key with a random base64 one, and after restart gogs stop working!

Error 502 BadGateway

Help me please!

**Comment by Unknwon** [comment]
Hi there, thanks for your feedback, but `Error 502 BadGateway` sounds like you don't even start Gogs yet...

**Comment by b4dtR1p** [comment]
Tnks for your reply, but service tell me that is running

**Comment by Unknwon** [comment]
Are you running Nginx for reverse proxy? Nginx never lies... :smiley:

**Comment by b4dtR1p** [comment]
Yep,It worked until I changed that fucking key

**Comment by Unknwon** [comment]
Maybe you should be able to dump something in case key makes Gogs crash.

**Comment by b4dtR1p** [comment]
OK i send you some news asap

Tnks, bit if don't work, can I remove and reinstall Gog's from zero?

How to make fresh install?

**Comment by Unknwon** [comment]
> Tnks, bit if don't work, can I remove and reinstall Gog's from zero?

Yes, removes the directory where you set to store all repositories and gogs directory. (SSH key file as well if you added SSH key through Gogs)

Then download new one, which becomes a fresh install.

**Comment by b4dtR1p** [comment]
OK, come back home now tnks

**Comment by Unknwon** [comment]
No problem, so how's reinstall process going?

**Comment by b4dtR1p** [comment]
i'm arrived now, just do it now!

**Comment by Unknwon** [comment]
I'm heading to my class, leave your comments I'll reply ASAP. :blush:

**Comment by b4dtR1p** [comment]
ok, the problem is service, becouse after after removal keeps telling me that it is active...

**Comment by Unknwon** [comment]
Cool! So I guess Gogs wasn't running when you get `502` :eyes:

**Comment by b4dtR1p** [comment]
yep but how to remove this fucking gogs service from ubuntu?

i'm try to delete /etc/init.d/gogs but don't work....oh fuck!

**Comment by Unknwon** [comment]
Not familiar with init.d thing, but I guess you should execute some commands to let daemon remove it.

**Comment by b4dtR1p** [comment]
look at web log after fresh install 

[publickey.go:77 init·3()] [E] fail to create '/home/gogs/.ssh': mkdir /home/gogs: permission denied

gogs user already exist

**Comment by Unknwon** [comment]
I think it really means no permission to create .ssh directory

**Comment by b4dtR1p** [comment]
i know, i fix it create manually every dir, now open installer page but when finish to compile it...
Error 502 BadGateway

log error
[repo.go:113 NewRepoContext()] [E] Fail to set git user.name(exit status 255): error: could not lock config file /home/gogs/.gitconfig: Permission denied

**Comment by b4dtR1p** [comment]
i try to fix permission manually, but isn't normal

**Comment by b4dtR1p** [comment]
now work...tnks mate for you time

i hope for snipets or gist news lol

**Comment by b4dtR1p** [comment]
now i've the old repo(that don't exist jet) and recive error 500, and i'm unable to delete it....

**Comment by b4dtR1p** [comment]
ok delete manually from db old repo!
