### ISSUE TITLE
 Cannot SSH clone with non-default port

### ISSUE THREAD

**Issue by litgh** [gogits/gogs#1004]
```
git remote -v
origin  ssh://git@192.168.0.101:8126:user/repo.git (fetch)
origin  ssh://git@192.168.0.101:8126:user/repo.git (push)

git pull origin master
ssh: connect to host 192.168.0.101:8126:user port 22: Bad file number
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by matt-h** [comment]
Did gogs give you that format or was that just how you setup the remotes?

The correct format for non standard ports should be:
origin  ssh://git@192.168.0.101:8126/user/repo.git (fetch)
origin  ssh://git@192.168.0.101:8126/user/repo.git (push)

**Comment by mbirth** [comment]
Can we add an option like ROOT_SSH to the app.ini to set a non-standard SSH port to be shown in the cloning options popup, too? Like:

    [server]
    ROOT_SSH = ssh://git@192.168.0.101:8126/

So that the popup shows:

    ssh://git@192.168.0.101:8126/user/repo.git

instead of currently

    git@192.168.0.101:user/repo.git

**Comment by Unknwon** [comment]
@mbirth there is already one: https://github.com/gogits/gogs/blob/master/conf/app.ini#L23

**Comment by mbirth** [comment]
@Unknwon But isn't that the port where SSH is set to listen on? I.e. the complement of HTTP_PORT?

I want something like:

    SSH_PORT = 22
    ROOT_SSH = ssh://git@192.168.0.101:8126/

Because I'm running Gogs in a Docker image on my Synology and port 22 of the Docker image is mapped to port 3000 on the "outside". So I want Gogs to display a ssh-URL with port 3000 although it's still using port 22 internally.

Much like HTTP_PORT (port to actually use) and ROOT_URL (URL to display).

**Comment by Unknwon** [comment]
@mbirth Gogs does not start SSH server itself, this port is the port where outside world can connect to your SSH server.

**Comment by mbirth** [comment]
@Unknwon Wow, okay, then that's exactly what I wanted. Just tried it: Works great! Thanks!

**Comment by Unknwon** [comment]
@mbirth no problem!

**Comment by Unknwon** [comment]
Close for now and open for continuing discussion.

**Comment by lk0606** [comment]
@unknwon 
docker gogs 10022:22

SSH_PORT = 10022

how do i display as ssh-gogs.git.com?
