### ISSUE TITLE
Can not delete repository using gogs

### ISSUE THREAD

**Issue by turboscholz** [gogits/gogs#1006]
Installed Gogs-Version: 0.5.13.0214 Beta

I have created a private test repository on my gogs-Server, named "us-git". As I don't need it anymore, I want to delete it now. Here are the steps I did:

1. Clicked on "Delete repository" in the repository options
2. Typed the name of the repository and my password in the pop-up dialogue
3. Click the delete button
4. All I get is "Please make sure the password is correct." (See screenshot, it is in German)

I checked my password several times now, I'm sure that I have no typo here. The online-log
of Gogs shows no error when clicking the delete button, also in 'log/xorm.log' I can not find any hint to this problem. I want to say that I am logged in to my gogs-Server via LDAP, but this workes without a problem. 

If I can give you any more info, please give me an advise.

Thanks,
Uwe

![fehler-gogs](https://cloud.githubusercontent.com/assets/5513310/6505382/f9385bb4-c341-11e4-9bf2-4f510917d2e2.png)

PS: Is it possible to "hard-delete" a repository physically from "git/gogs-repositories"? Or will this make trouble?

**Comment by Unknwon** [comment]
Hi @turboscholz , thanks for the feedback!

I've pushed code on `master` branch so that you can help us test again!

**Comment by turboscholz** [comment]
Hi @Unknwon

Great, now I can delete my test-repository. Perfect! Thanks allot!!! :)

**Comment by Unknwon** [comment]
@turboscholz very well! Thanks your feedback again!
