### ISSUE TITLE
How do I run gogs dump?

### ISSUE THREAD

**Issue by debunge** [gogits/gogs#1008]
When i try on my ubuntu 14.10 
sudo gogs run dump
sh: 1: exec: dump: not found

or sudo gogs dump
Usage:
  gogs run COMMAND [options]
  gogs scale TYPE=NUM
  gogs logs [--tail|-n NUMBER]
  gogs config:get VAR
  gogs config:set VAR=VALUE
  gogs configure
  gogs reconfigure

I've installed gogs from debian package from here https://packager.io/gh/pkgr/gogs

**Comment by Unknwon** [comment]
Gogs currently does not provide recovery from it, but if you want to use it, do `./gogs dump`.

Not sure how https://packager.io/gh/pkgr/gogs wrapper it, I cannot tell, maybe it's hidden by packager.

**Comment by debunge** [comment]
If it is hidden by packager, then how do I find it?

**Comment by Unknwon** [comment]
> If it is hidden by packager, then how do I find it?

Don't install by packager.

**Comment by debunge** [comment]
oh, crap. I have the whole system is up and running for quite a time. Migration is going to be painful... 

Is there any easy ways, like comiling dump.go separately?

**Comment by Unknwon** [comment]
@debunge just curious why you want to use `dump`?

**Comment by debunge** [comment]
I want to use it for backups.

**Comment by Unknwon** [comment]
I see, I guess you can file an issue say that `where is the gogs binary?` to packager. 

BTW, packager version of Gogs is really old now...

**Comment by debunge** [comment]
I see, the problem is with packaging. Thank you very much for your time. btw, gogs is awesome!

**Comment by Unknwon** [comment]
@debunge we are glad you like Gogs!
