### ISSUE TITLE
FreeSSHD on Windows

### ISSUE THREAD

**Issue by losper** [gogits/gogs#1010]
我是gogs新手，在32位win7系统下使用gogs，
1、按照安装页面的方法构建 SQLite3/Redis/Memcache 集成版
2、gogs web运行并install页面安装
3、加入ssh key并创建一个test仓库
然后在git clone这个仓库时，提示如下
mark@MARK-PC /e/home/tmp
$ git clone mark@192.168.3.80:root/test.git
Cloning into 'test'...
ssh: connect to host 192.168.3.80 port 22: Bad file number
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

我的custom/conf/app.ini内容如下：
RUN_USER = mark
RUN_MODE = prod

[database]
DB_TYPE = sqlite3
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = 
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = e:\home\web

[server]
DOMAIN = 192.168.3.80
HTTP_PORT = 3000
ROOT_URL = http://192.168.3.80:3000/

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info

[security]
INSTALL_LOCK = true
SECRET_KEY = JyGsEqvZZ1CNc7R

**Comment by losper** [comment]
有任何可以解决的办法么？

**Comment by Unknwon** [comment]
> ssh: connect to host 192.168.3.80 port 22: Bad file number

This is an error responded by SSH server, your request doesn't even get pass to Gogs.

For error like this, I think:

- Your SSH config isn't right, port is not 22
- Your firewall restricts connection for port 22

**Comment by losper** [comment]
unknwon，你好，谢谢回复。
1、请问如何查看gogs的ssh配置，并将gogs的ssh端口配置为22？在app.ini里修改？
2、我已将防火墙关闭，估计不会是防火墙的问题。
ps.之后运行了gitbucket，通过ssh的clone是正常的。

**Comment by Unknwon** [comment]
Gogs has no SSH server in current version, so you are dealing with your server's SSH, not Gogs's SSH.

Also, the default port Gogs uses is `22`.

- How did you add your SSH key? 
- What is your full command clone?

**Comment by Unknwon** [comment]
Would you mind dump your `/home/mark/.ssh/authorized_keys` content?

**Comment by losper** [comment]
~/.ssh/authorized_keys里内容如下，不知道有什么不对的地方？
command="E:/home/dev/gogs/gogs.exe serv key-2 --config='E:/home/dev/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEZI9zX0fq5fh0YFf5TJmRsFWKzPsUICGa8/4dsLclxMyC1uQqGIVVOt+ch5ovxhxUGKDxTZqwOjMC2Fs9nWGrKX/608MllH22kzC0FCz+JQcNjfhYRP7ms3NrOpR1oyQ4LrtPqitIlHlo+aMKh0hvQal7fI2cg+1y13D2fdc+kZ47HXsi12U1L7oSX3fNx0PVNLPRT5ToU/YMca0szqFHls80lCHpToE6dwm0e2xkM+nTZsGTjr1bV106tcctEjE1TE0/AtvxcSqC4Tbf8Q3T5PwmuvxN+zD8JH80/Gim4MS5IiTJxOcXbHs8buQivMqBT/4IIzKz445VUS5QcDnP liuwenjun@hangsheng.com.cn
command="d:/dev/go/src/src/github.com/gogits/gogs/gogs.exe serv key-1 --config='d:/dev/go/src/src/github.com/gogits/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEZI9zX0fq5fh0YFf5TJmRsFWKzPsUICGa8/4dsLclxMyC1uQqGIVVOt+ch5ovxhxUGKDxTZqwOjMC2Fs9nWGrKX/608MllH22kzC0FCz+JQcNjfhYRP7ms3NrOpR1oyQ4LrtPqitIlHlo+aMKh0hvQal7fI2cg+1y13D2fdc+kZ47HXsi12U1L7oSX3fNx0PVNLPRT5ToU/YMca0szqFHls80lCHpToE6dwm0e2xkM+nTZsGTjr1bV106tcctEjE1TE0/AtvxcSqC4Tbf8Q3T5PwmuvxN+zD8JH80/Gim4MS5IiTJxOcXbHs8buQivMqBT/4IIzKz445VUS5QcDnP liuwenjun@hangsheng.com.cn

**Comment by Unknwon** [comment]
What will happen when you execute `d:/dev/go/src/src/github.com/gogits/gogs/gogs.exe serv`?

My guess is in Windows, those `/` should be `\`.

**Comment by losper** [comment]
1、已经有在gogs中增加自己的ssh key
2、完整的clone指令是：git clone mark@192.168.3.80:root/test.git
3、msysgit是否已经有ssh？
4、在windows下/与\都可以识别，应当没有关系。

**Comment by losper** [comment]
按照你的意思，是否我需要在windows下为gogs安装一个freeSSHd或者类似ssh服务以便gogs使用?

**Comment by Unknwon** [comment]
> 3、msysgit是否已经有ssh？

No, it does not.

> ps.之后运行了gitbucket，通过ssh的clone是正常的。

GitBucket maybe has a built in SSH server, but currently version of Gogs does not.

So do you actually have installed a SSH server on your windows?

**Comment by Unknwon** [comment]
> 按照你的意思，是否我需要在windows下为gogs安装一个freeSSHd或者类似ssh服务以便gogs使用?

Yes.

**Comment by losper** [comment]
我知道了，我会安装一个试试，多谢解疑！
期待你们的Builtin SSH&PR！：）

**Comment by Unknwon** [comment]
@losper no problem, my pleasure!

**Comment by losper** [comment]
嗨，Unknown，我按照你的建议，下载了一个freeSSHd，并且安装成功。但是我该如何设置让gogs使用freeSSHd提供的SSH服务？
现在我加入了msysgit提供的ssh key，但是提示：
$ git clone mark@192.168.3.80:root/test.git
Cloning into 'test'...
mark@192.168.3.80's password:
Permission denied, please try again.
mark@192.168.3.80's password:

**Comment by Unknwon** [comment]
Let freeSSHd use `~/.ssh/authorized_keys` file for authorization.

**Comment by losper** [comment]
@Unknwon 我对SSH服务器配置不熟悉，请问对freesshd熟悉么，我在Authentication标签中找到设置public key的目录，但是没有直接设置authorized_keys。

**Comment by Unknwon** [comment]
Hasn't tried freesshd, I'll keep this issue open and try it see if Gogs can nicely work with it.

**Comment by losper** [comment]
@Unknwon 请问以前有在windows上验证过gogs么，使用的是哪款SSH软件？

**Comment by Unknwon** [comment]
All tests on Windows is using HTTP/HTTPS.

**Comment by victorsegall** [comment]
#1030 also referenced freeSSHd in its first version. I looked, and the project looks unmaintained. A lot has happened in SSL/TLS since the last release.

In both cases, I'm suggesting to move to [Cygwin OpenSSH](http://docs.oracle.com/cd/E24628_01/install.121/e22624/preinstall_req_cygwin_ssh.htm), and that will be one of the docs I follow when I test it.

**Comment by Unknwon** [comment]
@victorsegall looks good! Thanks, I'll try Cygwin OpenSSH first.
