### ISSUE TITLE
Navigating Issues Through Labels Is Awkward

### ISSUE THREAD

**Issue by victorsegall** [gogits/gogs#1011]
* gogs_v0.5.13_windows_amd64
* Windows 7 Pro 64bit
* msysgit Git 1.9.5.0

No error to log, just awkward behavior in the web UI.

Began with a first-run repo, and made one issue and one label, then navigated to: http://localhost:3000/victor/DVS/issues

The label gets hyperlink href: http://localhost:3000/victor/DVS/issues?type=all&state=&labels=1

Clicking that acts as a filter toggle. That's working. However, with the label toggled ON, the "Closed" and "Open" hyperlinks are not including that filter.

Closed href, when a label is toggled on: http://localhost:3000/victor/DVS/issues?type=all&state=closed

After the behavior is learned by the user, it still requires navigating to Open or Closed before selecting labels. It also prevents swapping between Open and Closed while keeping the selected label filter.

I would make a feature request to have label selection persist through the Open/Closed URL params, and also add a "clear selected" hyperlink to the Labels sidepanel; moving that label-clearing behavior there, and making it intentional. "Clear selected" would be a URL that still includes the "state" parameter.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by victorsegall** [comment]
Thank you.

My mistake in calling it a feature request; it is really an enhancement. I'm not sure if that affects priority.

**Comment by Unknwon** [comment]
@victorsegall Hmm, they're basically the same, just a clarification thing. I would say it's a bug as well :stuck_out_tongue_closed_eyes:

**Comment by victorsegall** [comment]
Then we agree that user experience is a feature. :smiley:

**Comment by victorsegall** [comment]
The behavior is solidly a bug when navigating issues by Milestone. Selecting a label filter will remove the milestone filter.

**Comment by Unknwon** [comment]
Should work well now! https://try.gogs.io/unknwon/gogs/issues
