### ISSUE TITLE
Allow to disable Markdown hard line breaks

### ISSUE THREAD

**Issue by valeriangalliat** [gogits/gogs#1012]
Hello there, and thank you for making this awesome software!

I see that [hard line breaks](https://github.com/gogits/gogs/blob/5cd887dba5dea90470435bfa338b70c5c036019e/modules/base/markdown.go#L211) are forced for Markdown parsing.

I found this quite surprising, since it's not the usual behavior for Markdown parsers, and more specifically readme renderers on GitHub-like sites. It makes wrapped readmes look really bad (and I believe it's common practice to wrap Markdown files to ~80 characters, at least when not created from a web interface like GitHub).

Typically, for [Blackfriday](https://github.com/gogits/gfm):

**Gogs default:**

![Wrap](http://image.noelshack.com/fichiers/2015/10/1425745277-wrap.png)

**No hard line breaks:**

![No wrap](http://image.noelshack.com/fichiers/2015/10/1425745281-nowrap.png)

---

I removed this flag from my personnal installation, but do you think it's worth adding a configuration option for this?

**Comment by Unknwon** [comment]
Thanks your feedback, but it's duplicated to https://github.com/gogits/gogs/issues/1009

**Comment by valeriangalliat** [comment]
Oh thank you, I feel dumb for not noticing the already existing issue from just two days ago!

**Comment by Unknwon** [comment]
@valeriangalliat no worries, too many issues here, I often get lost, too :stuck_out_tongue_closed_eyes:
