### ISSUE TITLE
Review Slack WebHooks support

### ISSUE THREAD

**Issue by aPeer** [gogits/gogs#1013]
I've just noticed that Gogs supports and suggest using two different kind of WebHooks. One is *Gogs*, which is basically a POST request. The other one is *Slack*, that's an integration with "slack.com" service.
It looks like "slack.com" is a **non-free** team communication tool. [Wikipedia](https://en.wikipedia.org/wiki/Slack_%28software%29) lists it as *Freeware*. I've never heard of that website before, so I might be wrong. However, I urge you to check this issue and confirm whether Slack is indeed free or not. *If it's not, please remove it from Gogs as soon as possible*.
Thanks

**Comment by Unknwon** [comment]
Slack has free plan.

>  If it's not, please remove it from Gogs as soon as possible

Why should Gogs?

**Comment by matt-h** [comment]
@aPeer You are correct that slack is non-free software, however the WebHook is just integration with their API so there is no reason for that not to be in Gogs. If you don't want to setup that WebHook you don't have to.

Gogs should have as many WebHook options as possible to integrate with as many services as possible (both free and non-free) so it can integrate into the user's workflow no matter what systems they choose to use.

**Comment by aPeer** [comment]
@matt-h I'm really sorry, but that's not a valid argument. I don't want to opt-out of private software. It just doesn't have to be there. If you or anybody else want to use non-free software, then just fork Gogs and add your stuff there. But please don't pollute an otherwise free project. Gogs can support as many services as it wants to, as long as they are free. Currently it's suggesting to use a non-free service.. Again, if you want to use a non-free option in your workflow, that's your own business. So, please take care of maintaining a separte fork for yourself, and don't put the burden on other people.

@Unknwon I'm not talking about their "free plan". *Free plan* just means *gratis*; that is you don't have to pay in order to use it. I'm talking about freedom, [*free software*](https://en.wikipedia.org/wiki/Free_software). I'm asking you to take a strong position here: if Gogs *is* free software, then please remove Slack integration, otherwise you should write clearly on your README that Gogs is integrated with *non-free* software. Thank you.

**Comment by Unknwon** [comment]
@aPeer Gogs doesn't force you use Slack integration, your freedom to choose not use it, or fork Gogs to delete it. Thank you.

**Comment by hickscorp** [comment]
As @Unknwon said, you're free to do whatever you want with free software, including using it with non-free software. Do you consider Adium or Pidgin to *not* be free software? Once compiled, gogs also interfaces (Statically!) with the Win32 API, which is not free, and by analogy it would be a shame to drop support for such operating system, on the sole basis that it is not free.

You said that "Gogs is integrated with non-free software", IMO it's quite the opposite. Gogs integrates / will integrate implementations of connectors to *various* third party software. It doesn't make it in any way a subsidiary of those third party services.

I agree on the fact that all the connectors / third party providers supported by Gogs should be in the Readme, because it will make people aware of their options.

**Comment by hpvb** [comment]
For now we have removed support for slack in the fork we run at notabug.org. Would you be open to a patch that added configuration option to gogs.ini along the lines of 'disable proprietary third party extensions' or something? I'd like to keep the nab fork of gogs as close to main upstream as I can but we seem to have slightly different goals. :)

**Comment by rubenwardy** [comment]
I think it is fine if free projects support non-free webhooks, as long as you have to enable it or sign up. Providing that the code you're using to integrate is free, ie: just sending POST calls after being enabled rather than including code from them.

**Comment by Unknwon** [comment]
@hpvb 

> Would you be open to a patch that added configuration option to gogs.ini along the lines of 'disable proprietary third party extensions' or something?

Mostly like not.

**Comment by hpvb** [comment]
@Unknwon OK. Sorry to bother you with this then :) it'll make it a little harder for us to directly send you pull requests from our fork but I'm sure we can figure it out.

**Comment by Unknwon** [comment]
@hpvb no problem! But don't send new feature pull request without discussing wits us on https://gitter.im/gogits/gogs :)

**Comment by hpvb** [comment]
@Unknwon It's why I'm in there! :D

**Comment by Unknwon** [comment]
Thanks for all participants!

Few words before closing this issue:

Gogs core team's standpoint is very clear, we will not remove Slack webhook options(or any other future hook integrations) as HTTP POST actions. When HTTP POST is no longer free, that would be a good time to remove it.

:eyes::eyes::eyes:

**Comment by toogy** [comment]
I wanted to add that Mattermost exist and is an open source slack alternative written in Go and it rocks. It supports Slack webhooks so supporting Slack webhooks is supporting Mattermost web hooks!

I think it's fine!
