### ISSUE TITLE
New Milestone Data Stuck in Session Storage

### ISSUE THREAD

**Issue by victorsegall** [gogits/gogs#1015]
Probably a bug:

When creating a new Milestone through _http://localhost:3000/victor/DVS/issues/milestones/new_, two possibly undesirable things happen.

One is that client JS stores the incoming text in session storage under key _"issue-victor-DVS-new"_, which is the same key used while drafting a new issue. This leads to the second problem.

On successfully posting the new milestone, that session storage value is not cleared. The stored text will be emitted on _http://localhost:3000/victor/DVS/issues/new_ the next time that page loads.

**Comment by Unknwon** [comment]
Thanks your feedback!

But Gogs JS doesn't do anything about or even close to "session storage", not sure if it's your browser's hidden feature? Also, not quite understand what is the problem exactly... :mask:

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
