### ISSUE TITLE
Hide email address option in account settings

### ISSUE THREAD

**Issue by ghost** [gogits/gogs#1017]
Would it be possible to add an option to hide emails address?

**Comment by Unknwon** [comment]
No, but it's hidden when visitor is not logged in,

**Comment by raichu** [comment]
No?
So it is not possible to add an option to hide email addresses? Why not?

**Comment by Unknwon** [comment]
@aPeer @raichu My apologize, I thought @aPeer was referring to add an option in global level(config file), then I realize was in account settings page. :stuck_out_tongue_closed_eyes:

**Comment by raichu** [comment]
Oh, I see.
Well, github does have such an option in the account settings, so I just thought it is reasonable.

**Comment by Unknwon** [comment]
Close as user is deleted...

**Comment by herby** [comment]
Would it be possible to reopen it (and add possibility to user to hide the email)? Thanks.

**Comment by Unknwon** [comment]
@herby please open a new one.
