### ISSUE TITLE
Forked repo unavailable after deleting original repo

### ISSUE THREAD

**Issue by srvg** [gogits/gogs#1021]
A user created a personal repository. That repository was forked to an organisation.
Then the user deleted his personal repo.

After this, the repo in the organisation is not accessible any more. The web interface returns a 500 error. The error logged is

```
[Macaron] Started GET /Nasibel/jetfire for 127.0.0.1
[Macaron] Completed /Nasibel/jetfire 500 Internal Server Error in 15.333483ms
2015/03/09 22:12:37 [repo.go:379 func·008()] [E] GetForkRepo: Repository does not exist
```

Within `data/repositories` there is no git data anymore under the user personal name - as expected.
But the data at `data/repositories/nasibel/jetfire.git` still exists, and the bare repository seems complete.

As the repo home page is not available from the webinterface, it seems also impossible to edit the settings or e.g. delete it, so it can be re-created.

Gogits `Version: 0.5.13.0212 Beta`

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
Hi, now fork repo with deleted original repo will become independent.

But for private original repo, from now on, delete it will delete all forks.

**Comment by Unknwon** [comment]
Closed as implemented. :tada:
