### ISSUE TITLE
OFFLINE_MODE Still Uses Gravatar

### ISSUE THREAD

**Issue by victorsegall** [gogits/gogs#1024]
When setting gogs/custom/conf/app.ini:

```
[server]
OFFLINE_MODE = true
```

The page templates still call out to gravitar.com.

**Comment by Unknwon** [comment]
Thanks for the report! We'll get on this ASAP!

**Comment by victorsegall** [comment]
It's just not conditional in the templates. Here's an example:

![](https://i.imgur.com/Dumj27K.png)

**Comment by Unknwon** [comment]
Hi @victorsegall , I've pushed fix to `master`, please help test again, thanks!

**Comment by victorsegall** [comment]
@Unknwon , will do. Keeping it on reminder, though. I'm not yet set up to do my own compiles.

**Comment by Unknwon** [comment]
@victorsegall sure, take your time!

PS: plan to do a release on next Tue, EST, will be very helpful if you can test before that day. :blush:

**Comment by victorsegall** [comment]
@Unknwon will give it a shot this weekend.

The [from source](http://gogs.io/docs/installation/install_from_source.html) doc isn't mentioning GCC, so it's correct that you aren't calling C libs, and I won't need [MinGW gcc](https://golang.org/doc/install)?

**Comment by Unknwon** [comment]
@victorsegall Yes, as long as you don't use `sqlite`.

**Comment by victorsegall** [comment]
@Unknwon I use sqlite, and would want a complete build for testing. :laughing:

**Comment by victorsegall** [comment]
@Unknwon I see the tagging at the bottom of the doc now. :)

**Comment by Unknwon** [comment]
Recommend http://tdm-gcc.tdragon.net/ to install GCC on windows.

**Comment by victorsegall** [comment]
@Unknwon Thanks, installing now to test a bit later.

Just to confirm: I'm working in 64bit, so both Go and TDM 64bit binary packs are the way to go, and I won't be needing the 32bit tools. Yes?

**Comment by Unknwon** [comment]
@victorsegall yes.

**Comment by victorsegall** [comment]
Normally 64bit accounts for both; just making sure. Thanks :smile:

**Comment by Unknwon** [comment]
No problem.

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Comment by hazrd** [comment]
I know this is closed, but it isn't resolved and there is no related merge/pullrequest... Here is how to reproduce error:

I just installed Gogs (works great) and seen the offline option, I chose it. I disabled gravatar. Awesome.

I log in and see a gravatar avatar! Then I mouseover it and it says *something like* "go to gravatar.com to change this photo" and I am like.. "what?"

I ended up finding the profile edit area and uploaded my own (and checked the box about ignoring gravatar requests)

On 64 bit debian with sqlite db

**Comment by Unknwon** [comment]
How did you change your config?

**Comment by hazrd** [comment]
In the profile editor, at the bottom of the page it says upload avatar 

![Screenshot](https://linx.li/selif/d09gaypy.png)

**Comment by Unknwon** [comment]
OK... It's nothing to do with offline mode.

Did you uploaded new one?

**Comment by hazrd** [comment]
Before I uploaded my own avatar, it showed a gravatar one.

I didn't catch if it was remotely grabbing it, or if it was just a gravatar lookalike.

Thanks, have a great day
