### ISSUE TITLE
[SECURITY] Debian init script runs daemon as root

### ISSUE THREAD

**Issue by FiloSottile** [gogits/gogs#1025]
https://github.com/gogits/gogs/blob/5e763baa12e346f8eb577073399068802fa5d67a/scripts/init/debian/gogs#L51-L53

The gogs binary itself is usually owned by a regular user - as encouraged, but the debian init script will run it as root with `--test`, allowing privilege escalation.

All the scripts must take great care to only run the daemon under the target user.

The project might consider getting a CVE ID for this.

**Comment by Unknwon** [comment]
Thanks for the report!

All scripts are from 3rd-party, we personally don't use init.d, so don't know how to correct it.

Would you like you to make a PR on this? :blush:

**Comment by FiloSottile** [comment]
I guess it's the least I can do, considering how I like the project :)

But with my security hat on I'll have to stress the importance of making sure "blessed" system scripts that will run as root are secure. I can take of the Debian one.

Please don't sacrifice users security to convenience.

**Comment by Unknwon** [comment]
I should definitely learn init.d when I got time(famous false statement)!

Would you mind or possible change the script to run under user `git`? That is the recommend user to run Gogs.

**Comment by FiloSottile** [comment]
Yeah, I'm making that change soon and reviewing the init script. It does run under `git` except on one call, but that's enough to become root on a system.

What I'm saying is that stuff that runs as root is delicate, and should not be shipped/blessed unless fully understood.

**Comment by Unknwon** [comment]
> What I'm saying is that stuff that runs as root is delicate, and should not be shipped/blessed unless fully understood.

True.

**Comment by hickscorp** [comment]
I have my own script that runs as root but starts the daemon as another user. Give me a moment and I will post it.

Pierre.

**Comment by Unknwon** [comment]
> I have my own script that runs as root but starts the daemon as another user. Give me a moment and I will post it.

cc @FiloSottile

**Comment by hickscorp** [comment]
Hello again,

```shell
#! /bin/sh
### BEGIN INIT INFO
# Provides:          gogs
# Required-Start:    $syslog $network
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A self-hosted Git service written in Go.
# Description:       A self-hosted Git service written in Go.
### END INIT INFO
# Author: Danny Boisvert

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Go Git Service"
NAME=gogs
SERVICEVERBOSE=yes
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
WORKINGDIR=/home/system/git/gogs
DAEMON=$WORKINGDIR/$NAME
DAEMON_ARGS="web"
USER=git

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0
# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh
# Define LSB log_* functions. Depend on lsb-base (>= 3.2-14) to ensure that this file is present and status_of_proc is working.
. /lib/lsb/init-functions

# Function that starts the daemon/service
do_start() {
  sh -c "start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile  --exec $DAEMON -- $DAEMON_ARGS --test > /dev/null || return 1"
  sh -c "start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec /bin/su -- - $USER -c \"cd \\\"$WORKINGDIR\\\" && $DAEMON -- $DAEMON_ARGS\" || return 2"
}

# Function that stops the daemon/service
do_stop() {
  start-stop-daemon --stop --quiet --retry=TERM/1/KILL/5 --pidfile $PIDFILE --name $NAME
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2
  start-stop-daemon --stop --quiet --oknodo --retry=0/1/KILL/5 --exec $DAEMON
  [ "$?" = 2 ] && return 2
  # Many daemons don't delete their pidfiles when they exit.
  rm -f $PIDFILE
  return "$RETVAL"
}

case "$1" in
  start)
  [ "$SERVICEVERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
  do_start
  case "$?" in
    0|1) [ "$SERVICEVERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$SERVICEVERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  stop)
  [ "$SERVICEVERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1) [ "$SERVICEVERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$SERVICEVERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  status)
  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  restart|force-reload)
  log_daemon_msg "Restarting $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1)
    do_start
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_end_msg 1 ;;
      *) log_end_msg 1 ;;
    esac
    ;;
    *)
    # Failed to stop
    log_end_msg 1
    ;;
    esac
  ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
    exit 3
    ;;
esac
:
```

As you can see, the master init process is root, and switches to git once started:
```shell
ps aux | grep gogs
root       368  0.0  0.0  64488    64 ?        S    Feb20   0:00 /bin/su - git -c cd "/home/system/git/gogs" && /home/system/git/gogs/gogs -- web
git        372  0.0  0.0  24796   196 ?        Ss   Feb20   0:00 -su -c cd "/home/system/git/gogs" && /home/system/git/gogs/gogs -- web
git        440  0.0  0.6 160288 12844 ?        Sl   Feb20   4:47 /home/system/git/gogs/gogs -- web
```

**Comment by Unknwon** [comment]
@hickscorp many thanks!

**Comment by hickscorp** [comment]
@Unknwon Don't mention it. As a side note: i have not heavily tested the various signals that are supposed to work with init (restart / reload). I only use this script for startup and manual restart.

**Comment by FiloSottile** [comment]
I'm afraid this has the same vulnerability. As I said the main process runs under the target user, but this line here

```
sh -c "start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile  --exec $DAEMON -- $DAEMON_ARGS --test > /dev/null || return 1"
```

runs `--test` as root. Since the user has ownership of the binary, they can get any command executed by root the first time gogs is restarted.

**Comment by hickscorp** [comment]
@FiloSottile Very good pointer indeed, will change my script accordingly.

**Comment by hickscorp** [comment]
@FiloSottile I have edited my initial post with an alternative way for the init script to check wether the service is already running or not. Could you give me some feedback about it? Thanks a bunch!

**Comment by sammcj** [comment]
Also note that Debian 8 uses systemd (the same as RHEL/Arch etc...) - while it can run legacy unit scripts, it's preferred to have a systemd unit instead which might negate this issue.
