### ISSUE TITLE
log.go:294 on Windows Expects UNIX Directory Separator

### ISSUE THREAD

**Issue by victorsegall** [gogits/gogs#1028]
In `gogs\custom\conf\app.ini`

```
[log]
ROOT_PATH = C:\gogs\log
```

Will cause:

```
timestamp [T] Custom path: C:/gogs/custom
timestamp [T] Log path: C:\gogs\log
timestamp [I] Gogs: Go Git Service 0.5.13.0212 Beta
timestamp [log.go:294 Error()] [E] Fail to set logger(file): invalid character 'g' in string escape code
```

It expects:

```
ROOT_PATH = C:/gogs/log
```

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by hickscorp** [comment]
This should not change! Pretty much all serious cross-platform framework unify (Make abstraction) of the paths. They usually decide of an arbitrary separator (In our case the "/" character) for paths, because the "\" character is a pretty much universal way to say "escape the next character".

Sources: Cygwin, Qt, MSYS, etc.

**Comment by Unknwon** [comment]
@victorsegall are you using standard Windows command line prompt?

**Comment by hickscorp** [comment]
Let me develop on my initial comment.

Let's say that i'm running Gogs on a windows computer. I will craft some configuration files, containing relative paths to various locations. If i decide to switch to Linux, those configuration files should not have to be refactored (Portability is better). Hence, using the "/" character for paths specification is IMO the best option, since "\" would probably be misleading for people as the "escape" character.

What do you guys think?

**Comment by Unknwon** [comment]
@hickscorp true point.

@victorsegall Have you ever tried use git-bash to start Gogs? (since Git is required to install)

**Comment by hickscorp** [comment]
@victorsegall If my assumptions are correct, replacing:
```ini
C:\gogs\log
```
With:
```
C:\\gogs\\log
```

The later will escape a slash, while your version escapes a "g" and a "l".

**Comment by victorsegall** [comment]
@Unknwon Yes, standard CMD, as I've already hit similar separator+context confusion in using gpg4win through msysgit bash.exe (it's basically the inverse of this ticket).

@hickscorp `C:\\gogs\\log` is exactly how I read the error, too. However, since the confusion is rooted in UNIX vs. MSDOS conventions, and Windows is already allowing the form of `C:/gogs/logs` in the same way it is case insensitive, I went with forward slash in the docs. The platform lets the prettier syntax work, and we'll likely never try `C:/` anything in *nix.

The real confusion for the user who needs any explanation to this point, I believe, will be in the fact that the Gogs ini reader correctly handles this:

```
[repository]
ROOT = C:\path\to\repositories
```

But not this:

```
[log]
ROOT_PATH = C:\gogs\log
```

In that sense it is "one more thing" to remember; reasons not withstanding. Whatever is being done to `ROOT` should be done to `ROOT_PATH`, or the inverse.

**Comment by victorsegall** [comment]
Also note that backslash `\` is the current output from Gogs first run installer, for the `[repository]` `ROOT` value in `gogs/custom/conf/app.ini`.

**Comment by hickscorp** [comment]
@victorsegall Your last point is very important. Shouldn't the paths be correctly "unified" by the first-run installer?

**Comment by victorsegall** [comment]
@hickscorp I would agree. Consistency.

**Comment by Unknwon** [comment]
@victorsegall is now the problem becomes:

You want to do the configuration in the following way:

```ini
[log]
ROOT_PATH = C:\gogs\log
```

But you want Gogs to see it as if it's:

```ini
[log]
ROOT_PATH = C:/gogs/log
```

**Comment by victorsegall** [comment]
@Unknwon only if:

```
[repository]
ROOT = C:\path\to\repositories
```

Is to remain as that. As I see it, either that has some code behind it (when gogs.exe reads it) to make it work, or it is working only because it is evaluated in a Win32 context, and not a POSIX context.

```
[repository]
ROOT = C:/path/to/repositories
```
```
[repository]
ROOT = C:\\path\\to\\repositories
```

Both of those will work in either Win32 or POSIX context, in the sense that `\` is an escape character in POSIX and is not one in Win32.

It is not an issue of preference or wanting the Windows way, but is one of consistency and placing the admin's mind into UNIX expectations when configuring. I agree with @hickscorp that `C:\\gogs\\log` is both a correct and a wrong thing for the admin to do.

That is to say, it is correct that the app.ini parser should always require `C:\\` when `C:\` is intended, because the app.ini parser should expect that it is sending those lines to a POSIX-type shell, where `\` is an escape character in those strings.

I think that `C:\gogs\` with unescaped `\` as separator should never be seen, and shouldn't work. Perhaps it gets caught as an exception in gogs.exe at the app.ini reading phase, and emitted to console or log.

In most areas of working with Gogs, Git Bash, and Cygwin, the form of `C:/gogs/` is being used, and I think that's the standard we should promote.

**Comment by Unknwon** [comment]
Hmm, so you suggest that Gogs has a `\` detector when read config?

**Comment by victorsegall** [comment]
Yes, to make sure admin uses `/` and to let coders not worry about ever needing to be "clever" about how to handle `\` across platforms.

**Comment by Unknwon** [comment]
Hi @victorsegall , I've pushed a fix on `develop` branch to ensure that no `\` or `\\` is allowed in config paths, and prompt to say `please use /`.

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Comment by linquize** [comment]
So, starting from v0.6, please also use `/` for paths on Windows.
