### ISSUE TITLE
sending an Accept header when using the REST API fails with a 406

### ISSUE THREAD

**Issue by jstrachan** [gogits/gogs#1029]
It seems the REST API fails if an Accept header is passed. 

e.g. this works fine:
```
curl -vk -u myuser:mypwd http://localhost:3000/api/v1/user/repos
```
however this fails with a 406
```
curl -vk -H "Accept: application/json" -u myuser:mypwd http://localhost:3000/api/v1/user/repos
...
< HTTP/1.1 406 Not Acceptable
```
it'd be nice to be able to pass an Accept header along too (so its easier to invoke the REST API via a browser in AngularJS ;)

**Comment by Unknwon** [comment]
Thanks for the report! I'm not quite sure what's going on with `"Accept: application/json"`, but will take a look.

**Comment by jstrachan** [comment]
Many thanks! I've been trying to figure out how to use $http in angularjs and not send any Accept header at all and so far no luck :)

**Comment by Unknwon** [comment]
Hmm... it's strange, based on current `master` version `0.6.1.0714`, 

> curl -vk -H "Accept: application/json" -u myuser:mypwd http://localhost:3000/api/v1/user/repos

returns correct JSON results.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
