### ISSUE TITLE
How can I config SSH on windows

### ISSUE THREAD

**Issue by ElvizLai** [gogits/gogs#1030]
Our server is Windows 2008.
when i use ssh -v with public key,it shows:
Hi shlyz ! You've successfully authenticated, but Gogs does not provide shell access.

but when I request a clone using ssh, it told me:
Gogs: internal error: exec: "git-upload-pack": executable file not found in %PATH%
but I add this binary to PATH

**Comment by victorsegall** [comment]
It needs to be on the path in the CMD environment while gogs.exe runs. It's possible for you to have it in your own %PATH% (when doing `echo %PATH%`), and for it to not be in the environment when gogs.exe runs.

Check that the directory for `git-upload-pack` is permanently added to the %PATH% of the user that gogs.exe runs as during your test.

**Comment by victorsegall** [comment]
You can also test it with:

```
C:\gogs\>PATH=%PATH%;C:\Program Files (x86)\Git\libexec\git-core
C:\gogs\>gogs web
```

Set `RUN_USER` in `gogs\custom\conf\app.ini` to your own username. That will run gogs as yourself, with `git-upload-pack` guaranteed to be on the path if you installed msysgit in the default location.

**Comment by ElvizLai** [comment]
LOL, we finally solved this problem:
1、Using Git Bash to start gogs service. NOT the window cmd.
2、Using COPSSH instead of FreeSSHD.

**Comment by Unknwon** [comment]
@ElvizLai very well! Can issue be closed?

**Comment by ElvizLai** [comment]
Thanks for all of the tips.

**Comment by victorsegall** [comment]
Then the issue was that `C:\Program Files (x86)\Git\libexec\git-core` was not actually on gogs.exe environment path, and the above solution worked because that environment will be enforced by executing gogs.exe within Git Bash's sh.exe.

**Comment by Unknwon** [comment]
@victorsegall looks like so.
