### ISSUE TITLE
Unhandled situation in migration

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1032]
Hi!

I just have upgraded to the latest develop version, and Gogs is unable to start:
```
2015/03/10 17:24:20 [T] Custom path: /home/system/git/gogs/custom
2015/03/10 17:24:20 [T] Log path: /home/system/git/gogs/log
2015/03/10 17:24:20 [I] XXX Git Hosting 0.5.16.0301 Beta
2015/03/10 17:24:20 [I] Log Mode: Console(Info)
2015/03/10 17:24:20 [I] Log Mode: File(Info)
2015/03/10 17:24:20 [I] Redis Enabled
2015/03/10 17:24:20 [I] Cache Service Enabled
2015/03/10 17:24:20 [I] Session Service Enabled
2015/03/10 17:24:20 [I] Mail Service Enabled
2015/03/10 17:24:20 [I] Register Mail Service Enabled
2015/03/10 17:24:20 [I] Oauth Service Enabled [GitHub Google]
2015/03/10 17:24:20 [I] Migration: generate team-repo from team
2015/03/10 17:24:20 [install.go:65 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: insert team-repos: Error 1062: Duplicate entry '1-19' for key 'UQE_team_repo_S'
```

Is there any chance that i could start Gogs again without loosing my DB?

**Comment by hickscorp** [comment]
FYI, solved by hand. Here is a hint for your migration scripts:

In my actual Gogs version, from the team table, the repo_ids column was listing many repos. Some of them were here multiple times. You should sanitize this before migrating, and remove any duplicate.

Eg: if team > repo_ids read like this:
`$1|$3|$1|$32|$12|`
Change it to a sanitized version like so:
`$1|$3|$12|$32|`

Restart gogs.

**Comment by Unknwon** [comment]
@hickscorp thanks for the report, sorry about any trouble!

**Comment by Unknwon** [comment]
Hi @hickscorp , I've pushed code to `master` fix this issue.

**Comment by hickscorp** [comment]
@Unknwon unfortunatelly, as i have migrated non-unique entries by hand, i won't be able to give you much feedback about this issue. I'm closing it.

**Comment by Unknwon** [comment]
@hickscorp true, but thanks anyway!
