### ISSUE TITLE
Is this a gogs bug?

### ISSUE THREAD

**Issue by ElvizLai** [gogits/gogs#1034]
So sorry for the misspell, not dogs, it is gogs, sorry.

Some of my team member meets this bug in windows. Is this a gogs bug?

![qq20150311-2 2x](https://cloud.githubusercontent.com/assets/501861/6590249/9a6d05e8-c7e8-11e4-8af2-b18a6caf6e73.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

To test if it's a fundamental function bug or Git GUI compatible bug, try clone in terminal.

**Comment by ElvizLai** [comment]
The same error in terminal.
![qq20150312-1](https://cloud.githubusercontent.com/assets/501861/6610693/e89f6958-c89d-11e4-90d8-2eed37e1ebd9.png)

**Comment by Unknwon** [comment]
What is your Gogs version? And how was the repository created?

**Comment by ElvizLai** [comment]
@Unknwon We solved this issue. It is not a git or gogs bug. Just because a software from HUAWEI caused this issue. Uninstall it, git works well.

**Comment by Unknwon** [comment]
@ElvizLai .....THIS IS AMAZING...unexpected :eyes::eyes::eyes:

**Comment by Unknwon** [comment]
@ElvizLai can you give me the specific name of this HUAWEI software so that I can add to troubleshooting

**Comment by ElvizLai** [comment]
@Unknwon The name of the software is "TopEng Intelligent Call Center", it's a Call Center System Dev Kit. Usually people may not install this software.

**Comment by Unknwon** [comment]
Fine..haha. 

Can this issue be closed?
