### ISSUE TITLE
Perhaps make APIs compatible with Gitlab

### ISSUE THREAD

**Issue by nashtsai** [gogits/gogs#1035]
Perhaps make APIs compatible with GitLab, so reviewboard can just work by choosing Gitlab as review repo.

FYR: https://github.com/gitlabhq/gitlabhq/tree/master/doc/api

**Comment by lunny** [comment]
It sounds good.

**Comment by Unknwon** [comment]
Sounds a good idea!

Not sure how it's compatible with GitHub API.

**Comment by Unknwon** [comment]
Close by https://github.com/gogits/go-gogs-client/wiki

**Comment by nashtsai** [comment]
great job
