### ISSUE TITLE
Debian 8.0 jessie apt source

### ISSUE THREAD

**Issue by zoujiaqing** [gogits/gogs#1036]
Debian 8.0 is very stable, need add jessie package source, thank you.

**Comment by Unknwon** [comment]
Hmm..sorry, not very familiar with Debian packaging, is it something like allow `apt get gogs`?

**Comment by zoujiaqing** [comment]
Yes, Ubuntu is debian based, use debian's apt toolkit.

**Comment by Unknwon** [comment]
Do you have introduction or tutorials on how to write a jessie package source?

**Comment by zoujiaqing** [comment]
Debian wiki:
https://wiki.debian.org/HowToPackageForDebian

**Comment by Unknwon** [comment]
Cool, thanks, I'll keep this in mind.

**Comment by liotier** [comment]
@Unknwon On top of the generic Debian packaging guidelines linked above by @zoujiaqing , you absolutely need to read the specifics of Debian Go Packaging: http://pkg-go.alioth.debian.org/packaging.html

If you need more guidance, get in touch with pkg-go-maintainers - the Debian golang packages maintainers: https://lists.alioth.debian.org/mailman/listinfo/pkg-go-maintainers

**Comment by Unknwon** [comment]
@liotier very helpful! Many thanks.

**Comment by sammcj** [comment]
+1 for a Debian package repo - I personally use packagecloud.io and have had a really good experience with it.

**Comment by Unknwon** [comment]
@sammcj thanks for the suggestion!

**Comment by crohr** [comment]
FYI debian-8 packages are available from https://packager.io/gh/pkgr/gogs

**Comment by Unknwon** [comment]
Thanks @crohr

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
