### ISSUE TITLE
Hoverover dropdown "owner" disappears on mouse move

### ISSUE THREAD

**Issue by ElessarWebb** [gogits/gogs#1039]
I cannot select the owner I want to, because the dropdown with organisations in the *owner* field of the *create repository* form disappears when I try to move my mouse to it.

I'm at *0.5.13*, fresh installation from aur, Arch Linux.

**Comment by Unknwon** [comment]
Thanks for the report!

But I think it's duplicated to https://github.com/gogits/gogs/issues/882 .

**Comment by ElessarWebb** [comment]
You're right, I missed that one while searching.

**Comment by Unknwon** [comment]
@ElessarWebb no worries, this happens often :stuck_out_tongue_closed_eyes:
