### ISSUE TITLE
Support GitHub-style checklists/tasklists

### ISSUE THREAD

**Issue by ndarilek** [gogits/gogs#1048]
https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments

I use a feature similar to this for larger issues when I don't want to file 20 smaller issues for various tasks. Would be nice to see something like it in Gogs for quickly specing out lots of work.

Thanks.

**Comment by Moter8** [comment]
:+1: Very interesting feature IMO.

**Comment by MichielDeMey** [comment]
I agree. This is a nice feature to have.

**Comment by alampros** [comment]
:+1: This was one of the first things I tried after installation.

**Comment by mgracer48** [comment]
+ 1

**Comment by sailsup** [comment]
+1

**Comment by bkcsoft** [comment]
I'll have a look at it after the weekend. The hard part is adding the checklist-feature to the markdown-parser, the easy part is making them interactive ^.^

**Comment by Unknwon** [comment]
@bkcsoft maybe you can look at [CustomRender](CustomRender) and use interface feature to implement the method [ListItem](https://gowalker.org/github.com/russross/blackfriday#Html_ListItem) or [List](https://gowalker.org/github.com/russross/blackfriday#Html_List). Then check if the item content has `[ ]` or [x]` prefix?

**Comment by bkcsoft** [comment]
working on it :)

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging #2396

**Comment by Unknwon** [comment]
See in action: https://try.gogs.io/gogs/gogs/issues/3

**Comment by bkcsoft** [comment]
I'd prefer to have this open still, since I wanna give interactive checkboxes a try. Though I need to fix an API-endpoint first IIRC :)

**Comment by Unknwon** [comment]
@bkcsoft I think that could be put into another issue, since you can always edit the comment/issue content to change the checklist. It's not a must-thing to have.

**Comment by Unknwon** [comment]
Close as implemented. 

If someone thinks `interactive checkboxes` is necessary, please open up a new issue. :trollface:

**Comment by bkcsoft** [comment]
@Unknwon nah, I'll just open a PR when Icve implemented it :trollface:

**Comment by Choko256** [comment]
Very old topic but...
Is this present in 0.11.12.0529 ?
I tried to add the `[ ]` in my issue and they are not transformed :(

There is no documentation on how to do that in issue markdown editor.

**Comment by Fastidious** [comment]
@Choko256 see https://try.gogs.io/Fastidious/Ideas/src/master/README.md (bottom). Simply use:

```
- [ ] One.
- [ ] Two.
- [x] Three.
```

**Comment by Choko256** [comment]
@Fastidious han yeah it works ! Sorry I forgot the bullets. Thank you very very very much ! :)
