### ISSUE TITLE
Bad permissions on authorized_keys after rewrite.

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1050]
When you're an admin of your Gogs instance, there is a procedure called "Rewrite '.ssh/autorized_key' file (caution: non-Gogs keys will be lost)".

If you run this, then the authorized_keys file will become chmod 660 (Instead of 600), therefore denying all connections from GIT SSH.

**Comment by Unknwon** [comment]
Hi @hickscorp , thanks your feedback!

I've pushed fix to `master`, please help test!

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
