### ISSUE TITLE
"New issue" multiple requests

### ISSUE THREAD

**Issue by aPeer** [gogits/gogs#1051]
When submitting a new issue, every time a user clicks the "Submit/Submitting..." button a new request is sent and the same issue get inserted multiple times. The "Submit" button should be disabled while submitting.

**Comment by bastiao** [comment]
Could #1073 related with this one?

**Comment by aPeer** [comment]
Likely

**Comment by Unknwon** [comment]
Right now in `develop` branch should fix this problem.

You can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Closed as implemented. :star:
