### ISSUE TITLE
Clone private organization repo without credentials

### ISSUE THREAD

**Issue by GithSystems** [gogits/gogs#1056]
When a project is marked "Private", it still can be cloned without credentials by anyone:

Let's say my project is "FooProject" owned by organization "company", it can be cloned using http://10.0.1.1:3000/company/fooproject.git

If I mark it "Private", it is hidden to "non-allowed" users on the web interface but still can be cloned using http://10.0.1.1:3000/company/fooproject.git (no credentials required)

**Comment by Unknwon** [comment]
Thanks your report! 

What is your Gogs version and database?

**Comment by GithSystems** [comment]
Bug appears in version Version: 0.5.13.0212 Beta and I'm using sqlite db

**Comment by Unknwon** [comment]
@GithSystems thanks for the info!

**Comment by Unknwon** [comment]
Oops..

**Comment by srvg** [comment]
Hm, can't seem to be able to reproduce that. I do get a password prompt, both using git and https
also, not via the public url (nginx+ssl), and not via the localhost:3000 url

0.5.13.0212 Beta + mysql

**Comment by Unknwon** [comment]
@srvg thanks for the tip!

**Comment by GithSystems** [comment]
Ok, I'll check this again and tell you if I can confirm that issue !

**Comment by Unknwon** [comment]
@GithSystems no problem, I'll test locally as well.

**Comment by GithSystems** [comment]
Ok, my fault, sorry !
I seems that my credentials were stored on a git cache somewhere … I've tried to clone with a totally distinct linux account and credentials have been properly required.

Sorry for that !

  Benoit

**Comment by srvg** [comment]
Better this than a real security issue :)

**Comment by Unknwon** [comment]
@GithSystems LOL.

@srvg thanks for following up!
