### ISSUE TITLE
Non-HTTPS option for URL when creating a new migration repo.

### ISSUE THREAD

**Issue by mattarnster** [gogits/gogs#1057]
I have a Git server which isn't running over HTTPS, and would like to migrate my repos across to Gogs, but when creating a new Migration, it forces me to use an HTTPS url and returns a 500 if it cannot connect.

Is there anything stopping using just plain HTTP instead of HTTPS when creating a new Migration repo?

**Comment by mattarnster** [comment]
Just noticed this was a dupe. Sorry!

**Comment by Unknwon** [comment]
No worries, and this issue is solved in the `master` branch code!
