### ISSUE TITLE
Mongodb

### ISSUE THREAD

**Issue by tiaguinho** [gogits/gogs#1058]
What you guys think about add mongodb support?

**Comment by Unknwon** [comment]
Do you refer to a backend database or a cache/session backend?

**Comment by tiaguinho** [comment]
Backend database.
We can use Redis to cache/session.

What you think?

I can work in both if you guys like the idea..

**Comment by Unknwon** [comment]
Hi @tiaguinho , if I remember correctly, MongoDB is a NoSQL type database? 

All we use now are SQL database, MySQL, PostgreSQL and SQLite.

I don't think MongoDB would fit in at this situation, do you?

**Comment by tiaguinho** [comment]
Yes, MongoDB is a NoSQL database.

I think you are right.
We can use MongoDB to cache objects (query results) and improve even more the speed of the pages.

What do you think?

**Comment by Unknwon** [comment]
It sounds like completely rewrite models layer to me :flushed:

**Comment by tiaguinho** [comment]
Just add a package I will create do handle the cache.

I don't think will be so much work. I can make this feature...

One question, do you use Beego as a framework in this project?

**Comment by Unknwon** [comment]
If you're saying the cache layer of entire app, hmm, Gogs hasn't start on that part yet, but when we do, it it very good to add MongoDB support.

> One question, do you use Beego as a framework in this project?

No, we use a variant of [Martini](https://github.com/go-martini/martini), [Macaron](https://github.com/Unknwon/macaron).

**Comment by tiaguinho** [comment]
Ok, nice.

I'll find another feature to do for now.

Thank you!

**Comment by Unknwon** [comment]
No problem.
