### ISSUE TITLE
create new repo 'stars' => Repository name contains illegal characters.

### ISSUE THREAD

**Issue by karmakaze** [gogits/gogs#1063]
I was able to create many other repositories on my installation with the same/more/less characters. Don't see what's special here.

**Comment by Unknwon** [comment]
Thanks your feedback, but we have docs for this: http://gogs.io/docs/intro/troubleshooting.html#form-validation

**Comment by Unknwon** [comment]
Gogs now has better error message about why it contains illegal characters.
