### ISSUE TITLE
X-Gogs-Event header is empty

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1064]
Looking at the code it should send event type correctly, but it actually sends an empty string.

```
    [HTTP_X_GOGS_DELIVERY] => f6f4b954-fe9d-41e1-a759-ebf3f3175cab
    [HTTP_X_GOGS_EVENT] =>
```

**Comment by Unknwon** [comment]
Hi @xPaw , I've pushed fix on `develop` branch, you can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
