### ISSUE TITLE
Deleting users should remove them from collaborator lists

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1067]
Deleting a collaborator user does not remove it from the collaborators list of the projects. I end up getting this error:

2015/03/17 04:59:32 [setting.go:209 SettingsCollaboration()] [E] GetCollaborators: User does not exist

**Comment by raichu** [comment]
This happens when I go to the project's collabolators page BTW (after deleting the collaborating user).

**Comment by Unknwon** [comment]
Hi @raichu , I've pushed fix on `develop` branch, you can also test on https://try.gogs.io .

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
