### ISSUE TITLE
Can't change the Application URL

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1068]
I need to change the port part of the URL. This apparently can't be changed from conf/app.ini, nor from the UI /admin/config.

**Comment by Unknwon** [comment]
Hmm.. I think because you didn't read the docs: http://gogs.io/docs/installation/configuration_and_run.html

**Comment by raichu** [comment]
Uh-oh, thanks.

**Comment by Unknwon** [comment]
@raichu no problem!
