### ISSUE TITLE
Copyright violations

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1069]
/user/settings/ssh page says
Need help? Check out our guide to generating SSH keys or troubleshoot common SSH Problems.

Where "our guide" is GitHub's guide. And this text, along with the links, is directly taken from github. This is beyond re-creation of GitHub's look and feel, this is a direct violation of copyrights. I have seen other instances of this.

UI needs a clean up.

**Comment by Unknwon** [comment]
Good catch! We shall change to `...GitHub's guide...`

**Comment by raichu** [comment]
Also, on the create new issue page, Content with Markdown link sends to github's markdown page, which is not exactly compatible with gogs.

**Comment by Unknwon** [comment]
@raichu true.

**Comment by raichu** [comment]
I've seen a few others, but I can't remember exactly where.
Well I should just post others when I come across them.

**Comment by Unknwon** [comment]
@raichu haha, no worries.

**Comment by Unknwon** [comment]
> Need help? Check out our guide to generating SSH keys or troubleshoot common SSH Problems.

Fix in `develop` branch, test on https://try.gogs.io/user/settings/ssh

**Comment by raichu** [comment]
See my post above

> Also, on the create new issue page, Content with Markdown link sends to github's markdown page, which is not exactly compatible with gogs.

**Comment by raichu** [comment]
GitHub: "Great repository names are short and memorable."
Gogs: "Great repository names are short and unique."

OMG these are just endless I give up.
Hell, did you just copy-pasted everything from GitHub including HTML and CSS?
I know that it is kind of Chinese culture to rip off things, but you have to remember that this is *illegal* in US.

**Comment by Unknwon** [comment]
We have consider your comments, and have contacted to GitHub and waiting for the response.

**Comment by hickscorp** [comment]
@raichu, the last part of your comment is unacceptable on a github issue, given the policy and agreement you had in hand when subscribing to github. I urge you to edit it and let the "Chinese culture" out of the discussion.

**Comment by linquize** [comment]
Any concrete suggestions to solve the crisis?

**Comment by hickscorp** [comment]
Sure @linquize, but i don't think there any kind of crisis :)

I will be glad to help translate / correct Gogs. I'm a native french speaker, and i'm not that bad at English.

I strongly disagree on @raichu comment regarding that "Usually it's either crappy English", i find myself very pleased with Gogs user experience, but I will be very happy to help re-formulate sentences in a Gogs-owned terminology.

Anyone to point me to a list of translation files so i can reformulate and then duplicate + translate to french?

**Comment by Unknwon** [comment]
@hickscorp Thanks, Gogs has been 100% translated to French according to https://crowdin.com/project/gogs , and are you on https://gitter.im/gogits/gogs ? That's an easier place to discuss sort of things.

**Comment by hickscorp** [comment]
@Unknwon I am. But we're always out of sync :)

**Comment by raichu** [comment]
@hickscorp Care to mention which term are you talking about exactly?
And in case you don't know, in US, there is freedom of speech. Speaking up [public truth](https://en.wikipedia.org/wiki/Shanzhai#Shanzhai_culture) is not against any law.
The laws in US protects freedom of speech, and laws trump and terms of service.

**Comment by raichu** [comment]
@hickscorp Care to mention which term are you talking about exactly?
And in case you don't know, there is freedom of speech in US. Speaking up [public truth](https://en.wikipedia.org/wiki/Shanzhai#Shanzhai_culture) is not against any law.
The laws in the US protects freedom of speech, and laws trump any terms of service.

**Comment by Calinou** [comment]
@raichu, please read this c omic:

![Free Speech](http://imgs.xkcd.com/comics/free_speech.png)

**Comment by raichu** [comment]
@Calinou, please read this article, it must be even funnier for you:
https://en.wikipedia.org/wiki/Copyright_law_of_the_United_States

**Comment by hickscorp** [comment]
@raichu if you don't really know how to read (And even if you're pointing me to a Wikipedia article... Well. Really? Wikipedia?!), and if you're confused between the Shanzhai phenomenon and the actual Chinese culture, then i will just say that i'm not really interested in talking to people of *your kind*.

Us law protects freedom of speech, and if you're proud to be claiming that Chinese culture is about rip off and scam, i'm very happy that you're surrounded by people of *your kind* as well, so you can have this kind of discussion freely.

However, when you sign up on github, there is a chart that you agree on reading and fully understanding. More generally, it's about the "netiquette".

It might be very hard for you to make the difference between those two, as for instance you seem to think that i'm not familiar with US law... In fact i might have lived on the US soil for quite a longer time span that you did. You just don't know, as you probably don't know what Chinese culture is all about. As long as you refer to your ideas with terms that are not confusing a majority to be defined by within the an isolated definition of a minority, i'm fine with you-being-free-to-say whatever idiotic things pleases you. Your original post wasn't like that, and the difference is a whole world to a lot of people.

[edit]Thanks for your edit on your original post. You are now referring to a term that doesn't confuses a majority to be within a minority.[/edit]

**Comment by raichu** [comment]
@hickscorp You hear what you want to hear.
And that's fine.
You're just nitpicking, and it's not without a purpose. And that's also fine.

It is a culture, and it is in China. I didn't know the term "Shanzhai culture" (thank God I learnt another useless term today). Anyone who's not nitpicking would have understood what I'm referring to.

And that's not the *kind* of person that I am though. In fact, after your personal "assault" on me, one can very well question your "netiquette".

Yep, I don't know if you're Count Chocula or ghost of Lincoln. I have no idea who you are. And same goes for you. You don't know who I am.

But what I know for certain is, what's going on here. It is not fair or legal to damage GitHub by ripping off from it. There shouldn't be a "Shanzhai GitHub", especially not here at GitHub.

**Comment by raichu** [comment]
> Any concrete suggestions to solve the crisis?

@linquize 
How about this for a start?
Get rid of everything you ripped off, do your own thing and work honest abiding laws.

**Comment by hickscorp** [comment]
@raichu Duly noted.

>  [...] In fact, after your personal "assault" on me [...]
I'm sorry if it looked personal. The way you initially formulated your sentence was really no way to discuss a copyright thing.

> [...] one can very well question your "netiquette" [...]
And i encourage you to do so if you think it's important.

> [...] You don't know who I am.
Let's keep it this way then :)

> But what I know for certain is, what's going on here. It is not fair or legal to damage GitHub by ripping off from it. There shouldn't be a "Shanzhai GitHub", especially not here at GitHub.
As you seem to think that my objective on this "personnal assaut" was to raise a "smoke screen", then i'd be very happy to begin a fresh discussion about this very last claim.

IMO, there is no plagia here on this project. I checked the JS / CSS files from Gogs, and didn't notice any obvious copy-paste as you see, to mention. Also, it's obvious to me (And i've been following this project for quite a while now) that the team behind it is responsive and is solving the bugs as they appear. Also, the very core of Gogs is written in Go, and that's really not the way Github works internally (Correct me if i'm wrong, Github used to be RoR, and moved to Erlang + some NodeJS).

Visually, Gog's web UI is lightyears behind github's one (@Gogs maintainers: really not trying to disgrace Gogs here, just merely an attempt of proving that the magnitudes of both projects are quite different). There is no realtime event propagation, and it really looks completely different to me. It vaguely resembles Gitbucket, Gitlab etc. They all do, because their scope is very similar with each other. But there is no copyright on this.

**Comment by raichu** [comment]
> IMO, there is no plagia here on this project. 

You are proven wrong by the *literal* rip offs (including the href part) I pointed out in my earlier posts.

I don't know about the total extent of this, whether it includes JS/CSS/etc , which is why I stated it as a question.

**Comment by hickscorp** [comment]
> You are proven wrong by the literal rip offs (including the href part) I pointed out in my earlier posts.

IMO it's quite the opposite. They kept the HREF as a reference to an external source of information, while really "ripping it off" would have been to take the target page "as is" and include it into Gogs source code.

Your thoughts?

**Comment by raichu** [comment]
Are you intentionally being thick?

https://github.com/settings/ssh:
> Need help? Check out our guide to generating SSH keys or troubleshoot common SSH Problems

/user/settings/ssh page says
> Need help? Check out our guide to generating SSH keys or troubleshoot common SSH Problems.

**Comment by hickscorp** [comment]
> Are you intentionally being thick?

No, i really didn't see this. The idea would be to reformulate all the sentences present in Gogs, because making it appear like a mere copy pasting of another project would not be cool.

I actually endorsed this task, which will be my first contribution to the project.

**Comment by raichu** [comment]
Great, because things are quite uncool right now.
Assuming that this is done until the next release, you may also want to cease the distribution of earlier versions, because they *are* violating copyright laws.

You may or may not need to clean to the git history from these tainted bits, you should better consult with github on this. Hopefully, they'll be lenient with the devs of this project and not press charges.

**Comment by hickscorp** [comment]
@raichu Good pointers, thanks.

**Comment by Unknwon** [comment]
As GitHub hasn't responded or has ignored my e-mail for 5 months, I consider this issue should be closed now and keep an eye on this in the future.

**Comment by manfer** [comment]
A link to Github saying it is a link to Github as it is coded now is not a copyright infringement as far as I know. Even when it said `our guide` when it were a link to Github (not a rip off of github's content served from your own server) I doubt it were a copyright infringement but just a mistake.

And if gogs has some sentences that looks just the same than in github when talking about same topic is not a copyright infringement either. Well I suppose github has not copyright on english language, does they? It is pretty normal two people finish using even the same exact sentence to word same idea.

Don't know what this person thinks is copyright law but the following example is absurd.

> GitHub: "Great repository names are short and memorable."
> Gogs: "Great repository names are short and unique."
> Wow, that makes everything's OK then.

Yes, that's totally OK.

And even if it were the same sentence as far as it is not the whole UI (or a large portion) with just the same look&feel and with the same sentences it should not be a problem.

About the other things talked about make no sense. That patriotism feelings are out of place in my opinion.

I'm sure github people are common sense people and if they have any problem with this project they will contact.

**Comment by Unknwon** [comment]
@manfer thanks for the comments.

**Comment by raichu** [comment]
@manfer

Some strings *are* literally copied (in more than one instance). The one I mentioned in the first post is just one example of those.

> About the other things talked about make no sense. That patriotism feelings are out of place in my opinion.

Have fun explaining this at the court.

In case you're not aware, yes, even a single sentence can and is protected by US copyright law. Your definition of "making sense" or "should not be a problem" is irrelevant. You're confusing the court with philosophy club. See that tiny "© 2015 GitHub, Inc." below? *That's* what matters.

**Comment by Unknwon** [comment]
https://help.github.com/articles/github-terms-of-service/  F4 is what we should look at
