### ISSUE TITLE
Create an issue with returns Error 1062: Duplicate entry 'X' for key 'PRIMARY'

### ISSUE THREAD

**Issue by bastiao** [gogits/gogs#1073]
I'm in 'developer' branch.

- I tried create projects with same name in different organizations. 
- Tried to create teams.
- When I create an issue it give that error:

```
Error 1062: Duplicate entry '9' for key 'PRIMARY'
```

I did not did any hack by SQL or something. All things by user interface and I think they make sense. So I strongly believe that it is a bug.

**Comment by Unknwon** [comment]
Hi @bastiao , I cannot reproduce this issue based on the information you provide. 

> When I create an issue

Create issue for which repository?

> Error 1062: Duplicate entry '9' for key 'PRIMARY'

Can you dump the full line of log, not just error part?

Thanks.

**Comment by bastiao** [comment]
@Unknwon it appears in UI, ok? I just copied from UI.

Now from gogs.log:
```
2015/03/17 12:07:45 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '3' for key 'PRIMARY'
2015/03/17 12:07:48 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '4' for key 'PRIMARY'
2015/03/17 12:07:49 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '5' for key 'PRIMARY'
2015/03/17 12:07:51 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '6' for key 'PRIMARY'
2015/03/17 12:07:51 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '7' for key 'PRIMARY'
2015/03/17 12:07:55 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '8' for key 'PRIMARY'
2015/03/17 12:08:13 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '9' for key 'PRIMARY'
2015/03/17 12:12:31 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '10' for key 'PRIMARY'
2015/03/17 12:12:34 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): Error 1062: Duplicate entry '11' for key 'PRIMARY'
```

**Comment by Unknwon** [comment]
Thanks for the log, what is your database type?

**Comment by bastiao** [comment]
MySQL

**Comment by Unknwon** [comment]
So it's the same env as https://try.gogs.io , if you can reproduce on the demo site, it would be easier for us to debug and fix.

**Comment by bastiao** [comment]
I tried, without success. sorry.

**Comment by Unknwon** [comment]
Hmm... maybe it's a very edge case, we'll see, if somehow I can reproduce it. Thanks for following up!

**Comment by Unknwon** [comment]
Hi @bastiao , I've pushed a fix to develop. Please help test, thanks again!

**Comment by bastiao** [comment]
Sure, in the next few days I'll give an update and report you feedback.

**Comment by bastiao** [comment]
@Unknwon seems fixed now, thanks.
