### ISSUE TITLE
Hardcoded user in ssh server?

### ISSUE THREAD

**Issue by bashrc** [gogits/gogs#1074]
Not sure what this is about in ssh.go:

    privateBytes, err := ioutil.ReadFile("/Users/jiahuachen/.ssh/id_rsa")

**Comment by d-kr** [comment]
I think this is similar to / in the same file as #1060 .

**Comment by Unknwon** [comment]
Hi @bashrc , thanks for the feedback but details are explained in #1060 .

@d-kr thanks for your quick answer.
