### ISSUE TITLE
Repository inside another one (submodule)

### ISSUE THREAD

**Issue by bastiao** [gogits/gogs#1075]
The sub-repository will be recognised as submodule, but it is not able to visualize it.

```
2015/03/17 14:33:42 [view.go:141 Home()] [E] GetSubModule: GetTreeEntryByPath: error not exist
```

Example to reproduce: 
1. Create an empty repository.
2. Go for: 
```
$ mkdir myRepo
$ touch README.md
$ git add README.md && git commit && git push 
$ git clone https://github.com/angular/quickstart.git
$ git add quickstart & git commit & git push 
```

Try to visualize. it returns 500.

**Comment by Unknwon** [comment]
Thanks for your feedback, what is your Gogs version and system?

**Comment by bastiao** [comment]
© 2015 Gogs · Version: 0.5.16.0317 Beta · Page: 2ms · Template: 1ms

Installed from source code :)

**Comment by Unknwon** [comment]
@bastiao thanks for  the info!

**Comment by linquize** [comment]
@bastiao  You did not add `.gitmodules`, so gogs does not know the URL of `quickstart`

**Comment by bastiao** [comment]
it is true. maybe we can close and it is not considered as a bug?

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/1061 for any possible updates. :beer:
