### ISSUE TITLE
Detect file renames/moves in diffs

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1078]
Right now it just shows as deleted in old path, and added in new path.

**Comment by xPaw** [comment]
Would be nice to have this implemented.

Gitea did this: https://github.com/go-gitea/gitea/issues/72

**Comment by Unknwon** [comment]
Thanks your info!

**Comment by Unknwon** [comment]
Please try it on `develop` branch or https://try.gogs.io

**Comment by xPaw** [comment]
Yeah, it works!

It might be better not to render images if they're unchanged though (simply renamed). If you rename a huge folder with images, they'll all render without a reason.

**Comment by Unknwon** [comment]
> It might be better not to render images if they're unchanged though (simply renamed). If you rename a huge folder with images, they'll all render without a reason.

Good point, let me work on it.

**Comment by Unknwon** [comment]
OK, pushed to `develop` and updated https://try.gogs.io

**Comment by xPaw** [comment]
I've deleted my test account, so can't test again.

**Comment by Unknwon** [comment]
Anyway, the main problem is resolved :smile:
