### ISSUE TITLE
Custom robots.txt should be send with plaintext content-type

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1079]
Currently it's sent as this:
```
Content-Transfer-Encoding:binary
Content-Type:application/octet-stream
```

**Comment by Unknwon** [comment]
Hi @xPaw , thanks your feedback! I've pushed fix on `develop` branch, you can also test on https://try.gogs.io/robots.txt

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
