### ISSUE TITLE
Remove ads/branding from default template

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1080]
Could you please remove the ads/branding from the default template? (The ones at the bottom of the page, gogschina etc.)
I don't understand even a single glyph of Chinese, so they're not even remotely useful to me (and all other people who are not Chinese).

Also, the link "Website" could be more descriptive (likes Gogs website).

Preferably, it would be best if the default template has no visible branding at all though (an HTML comment would just work).
However, I think most people are just OK with a single link to *either* gogs.io or the github page, which is either a text along the lines of "powered by gogs" or an icon-link.

After all, we're talking about a gogs installation for "private" use, not gogs.io homepage. It'd be best to keep these two things separate.

**Comment by Unknwon** [comment]
> Could you please remove the ads/branding from the default template? (The ones at the bottom of the page, gogschina etc.)
> I don't understand even a single glyph of Chinese, so they're not even remotely useful to me (and all other people who are not Chinese).

Somehow relates to customizable template, will do when that comes. 

> Also, the link "Website" could be more descriptive (likes Gogs website).

`Gogs website` isn't looks as nice as `Website`, noisy me a while to pick a single good word. Can you come up something?

> After all, we're talking about a gogs installation for "private" use, not gogs.io homepage. It'd be best to keep these two things separate.

This is already available for config options `LANGING_PAGE`(https://github.com/gogits/gogs/blob/master/conf/app.ini#L43) to redirect users when they visit homepage, eg redirect to explore page.

**Comment by raichu** [comment]
> Gogs website isn't looks as nice as Website, noisy me a while to pick a single good word. Can you come up something?

Yes. Nothing. Just remove it.
Because as I mentioned, what is noise is having your branding in my personal installation.

Put whatever ads with whatever wording you prefer on your personal website, just don't force those onto people.

> This is already available for config options
I'm not talking about the landing page. I'm talking about the ads you inject at the bottom of **every single page**.

**Comment by Unknwon** [comment]
@raichu thanks your advice, we will consider!

**Comment by Unknwon** [comment]
Close by https://github.com/gogits/gogs/commit/2bb982dada0012d59ead783aaf90e730351171cc
