### ISSUE TITLE
A missing link in the output of "Need help?" string on the repository page

### ISSUE THREAD

**Issue by asahnoln** [gogits/gogs#1082]
As far as I know, there is only one string in the localization pack which says "Need help cloning? Visit Help!".

It looks like this on a page of a pushed repository:
![screenshot 2015-03-18 14 47 48](https://cloud.githubusercontent.com/assets/2792908/6705335/04061c3e-cd7e-11e4-9afc-6f0caf6de7a6.png)

And it looks like this on a page of a new empty repository page:
![screenshot 2015-03-18 14 46 40](https://cloud.githubusercontent.com/assets/2792908/6705328/f1e90c14-cd7d-11e4-9d51-331451a38b71.png)

The link "Help" is missing.

**Comment by Unknwon** [comment]
Good catch!

**Comment by Unknwon** [comment]
Pushed fix to `develop` branch, you can test on https://try.gogs.io/unknwon/bare

**Comment by asahnoln** [comment]
@Unknwon thank you, works properly. 

By the way, there is a problem in Russian, but, I think, it should be mentioned in another issue. The button "Copy" falls to the next line because of the string length:
![screenshot 2015-03-18 15 15 28](https://cloud.githubusercontent.com/assets/2792908/6705698/aa26e2bc-cd81-11e4-898a-4aadca326535.png)

**Comment by Unknwon** [comment]
Yes, sure, please open another issue!
