### ISSUE TITLE
Localized UI: Button "Copy" falls to the next line on a page of an empty repository.

### ISSUE THREAD

**Issue by asahnoln** [gogits/gogs#1083]
In Russian UI, button "Copy" which is on a page of an empty repository falls to the next line because of the string length.
![screenshot 2015-03-18 15 15 28](https://cloud.githubusercontent.com/assets/2792908/6705830/a8f24cdc-cd82-11e4-8aeb-06a2a6095ef9.png)

**Comment by linquize** [comment]
Actually this is a css problem. If you decrease the width of your browser window, the problem may occur.

**Comment by Unknwon** [comment]
This should be fixed already.
