### ISSUE TITLE
Automated install

### ISSUE THREAD

**Issue by jimmidyson** [gogits/gogs#1084]
Is there a way to automate the install step of Gogs? My use case is for a Docker container where the admin password could be passed in at container creation time.

**Comment by srvg** [comment]
Automating the installation of gogs is pretty easy.

Create a dedicated user, install some dependencies, 
Download and unzip gogs
Provision the configuration file and an init script

How to do it depends on the technology you want to use.
If you're interestec in ansible, there's a nice role over here:

https://github.com/michaelrigart/ansible-role-gogs

**Comment by jimmidyson** [comment]
I actually meant the `'/install` step where you have to specify the admin user & password in the web UI. I can't see how that is done through that Ansible playbook?

**Comment by srvg** [comment]
​/install is just an interactive way to fill in parts of the config file.
If you provide a complete config file, you won't need to do that any more.

**Comment by jimmidyson** [comment]
AFAIK you can't specify the admin username or password in the config file & without that you can't actually use gogs?

**Comment by srvg** [comment]
Yes that's true. That's one step I didn't care to automate. Perhaps you can do that via some sql insert statement.

**Comment by Unknwon** [comment]
Change `[secutiry] INSTALL_LOCL = false` in custom config file does the magic.

**Comment by jimmidyson** [comment]
So a SQL insert & setting INSTALL_LOCK should do the job?

Any chance of adding this as a command line switch? Something like `./gogs install [ALL CONFIGURATION` to simplify this command line setup?

**Comment by Unknwon** [comment]
> So a SQL insert

I don't think there is any SQL insertion for installation step(but you can do it when you have special cases to init database)

> & setting INSTALL_LOCK should do the job?

Should be.

> Any chance of adding this as a command line switch? Something like ./gogs install [ALL CONFIGURATION to simplify this command line setup?

This gets things complicated. All `/install` do is just a GUI for setup your custom config file, so if you can fake one, it's easy.

**Comment by jimmidyson** [comment]
So you don't need an admin user to be set up?

**Comment by Unknwon** [comment]
@jimmidyson everyone can visit `/install` page. Whoever's `ID=1` becomes admin automatically.

**Comment by jimmidyson** [comment]
OK thanks for the info!

**Comment by Unknwon** [comment]
No problem, many people do this way when they make Dockerfiles and package builder.

**Comment by willzhang** [comment]
if install in docker how do that?

**Comment by unknwon** [comment]
@willzhang You mounted the pre-configured `app.ini` directly, it is basically the same thing as if you would do an image upgrade for Docker.
