### ISSUE TITLE
UI: Mouse over the hint of the "Copy" button

### ISSUE THREAD

**Issue by asahnoln** [gogits/gogs#1085]
Mouse over the hint of the "Copy" button causes the popup block to close on a page of a pushed repository.
![screenshot 2015-03-18 15 44 21](https://cloud.githubusercontent.com/assets/2792908/6706211/b3d75e1e-cd85-11e4-911d-955bd6ea3c82.png)
![screenshot 2015-03-18 15 44 35](https://cloud.githubusercontent.com/assets/2792908/6706212/b3d7e0fa-cd85-11e4-80c0-191746931d36.png)

**Comment by Unknwon** [comment]
This is fixed with new UI.
