### ISSUE TITLE
%!s(MISSING) in dashboard feed page

### ISSUE THREAD

**Issue by Mte90** [gogits/gogs#1087]
I get this after the upgrade with packagr of gogs.

There is no wiki about the upgrade so i don't know if i have left out some commands.
Also the link on %!s(MISSING) are wrong https://domain/mte90/blablabla/master/src/mte90/blablabla i get a 404 when i click on it.

![rattic4](https://cloud.githubusercontent.com/assets/403283/6710332/24114466-cd80-11e4-81c0-760f1c32c465.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

Looks like you didn't update locales files (`conf/locale`)

**Comment by Mte90** [comment]
uhm from the file data i see that was changed with the upgrade.
i've updated manually the en file from this repo, restarted gogs but the problem persist.

**Comment by Unknwon** [comment]
Why don't you just `git pull`?

**Comment by Mte90** [comment]
uhm i've updated from apt using the packagr package, can create some problem do this?

**Comment by Unknwon** [comment]
Hmm... very hard to say, locale files and templates files should be exact match, otherwise...

If you're using Ubuntu, this is a good start: https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04

**Comment by Mte90** [comment]
uhm but this require to compile gogs, for this reason i've choose the binary package for simplify the update.

**Comment by Unknwon** [comment]
Binary is easy too, much easier.

**Comment by Mte90** [comment]
so the package for the distros are unuseful if for fix is required to move to the other upgrade system :-/

**Comment by Unknwon** [comment]
Hmm... I'm not quite understand what you mean...

**Comment by Mte90** [comment]
For fix this problem i need to compile myself gogs, so the distros package are useless for update gogs

**Comment by Unknwon** [comment]
No, your problem is files' version are not match, maybe because you update somehow incorrectly.

**Comment by Mte90** [comment]
Uhm i've re-loaded the template files in the static folder that i use, reloaded gogs but nothing.

**Comment by Unknwon** [comment]
What is your Gogs version?

**Comment by Mte90** [comment]
0.6.0.0318 Beta

**Comment by Unknwon** [comment]
Hmm... at this point, you did remove old `templates` directory and download the latest template files and put them to the old location, right?

**Comment by Mte90** [comment]
do it but the problem persist :-/

**Comment by Unknwon** [comment]
How's going on this issue?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
