### ISSUE TITLE
Diff changeset view 

### ISSUE THREAD

**Issue by wqweto** [gogits/gogs#1088]
In .git/config I'm using i18n for non-unicode source code files to use cyrillic code page

    [i18n]
        commitencoding = cp1251

and in gogs source file view everything is ok. HTML page view source shows `content="text/html; charset=UTF-8"` and cp1251 to utf-8 is done server-side just fine.

Browsing commit diff view seems to always be using cp1252/Latin code page and my cyrillic texts go berserk. Gogs is setup on CentOS 6.6 behind nginx.

What tool do you use for diff or is it built-in? Is there something OS level I can tweak?

**Comment by Unknwon** [comment]
Thanks your feedback!

Currently we use git-shell to generate diff and parse, then show on the web UI. 

BTW, what is your Gogs version?

**Comment by wqweto** [comment]
I'm using Version: 0.5.16.0316 Beta

**Comment by Unknwon** [comment]
OK, the way it works is when parse the diff, Gogs will auto-detect encoding and try to convert to UTF8. Haven't tried when set i18n in git/config.

**Comment by wqweto** [comment]
I searched for "encoding" setting in `app.ini` with no luck. Have no idea idea how i18n is supposed to work in git-scm in first place.

SourceTree and GfW seem to understand `commitencoding` just fine. Will test github.com behavior and post here.

**Comment by Unknwon** [comment]
Sure!

Actually I'm not if `.git/config` is actually for server side, maybe it's just for client side.

**Comment by ZafiRUS** [comment]
Actually, diff view encoding breaks even if I use utf-8. File view is fine.
I have no encoding settings in git, I just use utf8 everywhere.

**Comment by Unknwon** [comment]
Close by https://github.com/gogits/gogs/pull/1399

**Comment by wqweto** [comment]
@ZafiRUS: After this patch putting `ANSI_CHARSET = Windows-1251` under `[repository]` section showed cyrillic letters in view and diff of ANSI files just fine here.
