### ISSUE TITLE
Ask for setting git user info when it's not available

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1089]
I just pushed a commit (in a repo that has absolutely nothing to do with gogs) from the machine I just installed gogs, and the commiter is, for some reason:
Gogs <gogitservice@gmail.com>

Is gogs fiddling around my git settings and populating them with email address I don't have access to? And is this documented?
And why is it an e-mail address **you** are controlling?
This is quite a trojan-horse-like behavior, and I find this quite outrageous.

**Comment by raichu** [comment]
This is the culprit
`// Check if server has user.email and user.name set correctly and set if they're not.
	for configKey, defaultValue := range map[string]string{"user.name": "Gogs", "user.email": "gogitservice@gmail.com"} {`

https://github.com/gogits/gogs/blob/master/models/repo.go#L107

*That* is not setting user.email and user.name "correctly". If these are required, these *should* be asked during the installation.
gogs should never populate .gitconfig with some email address only you have access to.

**Comment by Unknwon** [comment]
> If these are required, these should be asked during the installation.

Good point.

**Comment by Unknwon** [comment]
Close by https://github.com/gogits/gogs/commit/9c67a193321a766097e6494484df5370010b512c

**Comment by ePirat** [comment]
Why is it needed that it modifies the `.gitconfig` on the server it is installed on?

**Comment by Unknwon** [comment]
Hi @ePirat , 

For current implementation, Gogs uses git command to commit changes to initial commit, and git requires you set a fake user.name and user.email no matter you use it or not. (Gogs commit is based on your account info, you can say this is a way to bypass git check)
