### ISSUE TITLE
gogs should use CWD

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1090]
gogs is institing that the templates should be in the directory where the binaries are.
That is not how common Unix installations works. You need to make the data directory should be separate for Linux packages, and either let users pass the template etc dir, or just use the current working directory. But never insist on the binary dir (which is typically /usr/bin, and that is **not** where things like templates go)

**Comment by Unknwon** [comment]
We have config options for define where you locate your template and static files: http://gogs.io/docs/advanced/configuration_cheat_sheet.html#server

**Comment by linquize** [comment]
About the default location:
What happen if I relocate the binary together with the template?
Should I recompile gogs?

**Comment by Unknwon** [comment]
> What happen if I relocate the binary together with the template?
> Should I recompile gogs?

Move files around don't need to recompile anything.

**Comment by Unknwon** [comment]
@linquize

**Comment by Unknwon** [comment]
Close for now, feel free to reopen if you want to continue discussing. :wink:
