### ISSUE TITLE
Language fixes

### ISSUE THREAD

**Issue by raichu** [gogits/gogs#1093]
Here's my top list so far:

(commit log for initial commit) "Init commit" -> "initial commit."
(create new project page) "Google Go" is not a language name. "Go" is. Just like we simply say "C" rather than "Bell Labs C"

**Comment by Unknwon** [comment]
Thanks for the advice!

**Comment by tkisme** [comment]
http://git.XXX.com/issues
左侧栏汉化不完全

**Comment by Unknwon** [comment]
@tkisme I have no idea what are you talking about

**Comment by tkisme** [comment]
if repo title is long
<img width="436" alt="2015-08-28 9 49 22" src="https://cloud.githubusercontent.com/assets/5886048/9537408/442f230c-4d6a-11e5-8268-f35aa36de0b7.png">

**Comment by Unknwon** [comment]
@tkisme your version is too old, `master` branch has fixed this problem.

Also, don't comment on issue that is not relevant to your problem. It is very confusing.

**Comment by vijairaj** [comment]
The following text in the **issues** page:
commented ~~at~~ 6 days ago
closed ~~at~~ 6 days ago
reopened ~~at~~ 6 days ago

**Comment by Unknwon** [comment]
@vijairaj thanks

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/commit/d07033a0f0c4bc1a151eceb7179d227d81e528db
