### ISSUE TITLE
add_email_success_confirmation_email_sent and other missing i8n stuff

### ISSUE THREAD

**Issue by iSDP** [gogits/gogs#1094]
**How to reproduce:**

- Go to Email Settings (/user/settings/email)
- Add new email address

Messages don't show the proper content, but rather the placeholder like add_email_success_confirmation_email_sent.....

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version and can you reproduce on https://try.gogs.io ?

**Comment by iSDP** [comment]
http://i.gyazo.com/bffd5e46fbe08583d37c33da6860717f.png

Yes i can :)

And version:

VERSION:
   0.5.13.0212 Beta

**Comment by Unknwon** [comment]
Oh, thanks a lot!

**Comment by iSDP** [comment]
It's not in the Locale files, and the nl-NL locale is way off, like it has been automatically translated...

**Comment by Unknwon** [comment]
@iSDP yeah, translate key is used when translation are not available.

**Comment by iSDP** [comment]
@Unknwon i hope you can get it fixed before the next minor release :) 

I've introduced your project to my co-workers, they're impressed, but the bugs need fixin' :P

**Comment by Unknwon** [comment]
Thanks! Will fix it with 0.6 release :)

**Comment by iSDP** [comment]
Awesome! I'll work on improving the dutch translation if you want :)

Also, how long until 0.6 comes out? :D

**Comment by Unknwon** [comment]
Planned today EST, few tests to run.

**Comment by Unknwon** [comment]
Hi, I've pushed fix on `master` branch, you can also test on https://try.gogs.io/ .

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
