### ISSUE TITLE
Public repositories are not visible on org pages

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1096]
This happens when a user is not in a team that has access to repositories. This seems weird because repositories are public and are visible on explore page.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version and can you reproduce on https://try.gogs.io ?

**Comment by xPaw** [comment]
Version: 0.5.13.0212 Beta

Reproduction steps would be:
- Create an organization
- Create a public repository in that organization
- View organization page in incognito or as another user

**Comment by Unknwon** [comment]
I can count this bug in your version. But I think it's been fixed at some point after that, if you can reproduce on https://try.gogs.io  would be very helpful for us to debug!

**Comment by xPaw** [comment]
I`ll close this issue then, and if it comes up in next release, I`ll reopen it.

**Comment by Unknwon** [comment]
@xPaw no problem, thanks for following up :)

**Comment by xPaw** [comment]
Now there's a different bug, anyone can see organisation pages even without
logging in (sign in required in conf).
