### ISSUE TITLE
Hide gravatar email field if gravatar is disabled (or offline mode)

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1098]
On user settings page.

**Comment by tsumaru720** [comment]
Might also be worth changing the wording on the config cheat sheet :) It isnt clear that enabling OFFLINE_MODE will stop Gravatar working

**Comment by Unknwon** [comment]
@tsumaru720 good point, thanks for pointing out!

**Comment by Unknwon** [comment]
@xPaw pushed fix on `develop`, @tsumaru720 added to docs.

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
