### ISSUE TITLE
Ability to upload avatars for organizations

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1099]
Users can upload avatars if gravatar is disabled, but organizations can't.

**Comment by Unknwon** [comment]
Thanks for your feedback!

Need page to edit organization settings, along with avatar settings.

**Comment by xPaw** [comment]
There is already a page to edit organization settings? You just need to add an avatar field on it.

**Comment by Unknwon** [comment]
@xPaw Oh, you're right :wink:

**Comment by Unknwon** [comment]
It has been implemented.
