### ISSUE TITLE
Suburl is missing after changing language

### ISSUE THREAD

**Issue by aksh3ll** [gogits/gogs#1102]
i've configured gogs with an apache2 proxy, it works fine, but in a folder:
> https://domain:443/git/

and when i change the language to Français
it goes to:
> https://domain/git/?lang=fr-CA

(it should be fr-FR and not fr-CA by the way)
and then to:
> https://domain/

the response header is:
> Location: /

but it should be: /git/ or ./ to redirect to the original page or path

**Comment by Unknwon** [comment]
What is your version of Gogs?

**Comment by Unknwon** [comment]
> (it should be fr-FR and not fr-CA by the way)

Thanks, I've fixed this locally, will push soon.

**Comment by aksh3ll** [comment]
sorry, i should have precised the version,
I've installed the ubuntu 14.04 package from packager.io :
> Version: 0.6.0.0318 Beta
Go Version: Go1.4.1

**Comment by Unknwon** [comment]
No worries, what is your setting for your `Application URL` when you are in `/git/install` page?

**Comment by aksh3ll** [comment]
in https://domain/git/admin/config
> Application URL: https://domain/git/

if i change the language from this url, it redirects to:
> https://domain/admin/config

**Comment by aksh3ll** [comment]
I've installed it from the local machine using the localhost:6000/install and set it to https://domain/git/ validate and then done the redirection in apache2

**Comment by Unknwon** [comment]
Your setting looks right, let me test locally with Nginx see if I can reproduce it. Thanks for the quick response!

**Comment by Unknwon** [comment]
Hi @aksh3ll , I've did some tests.

My `ROOT_URL` is `http://mydomain.com/git/`
My Nginx config:

```nginx
     server {
         listen 8080;
         server_name mydomain.com;

         location /git/ {
             proxy_pass http://localhost:3000/;
         }
     }
```

And change language works properly. 

Not sure how to translate to Apache2 format, but should be pretty same on the values.

**Comment by Unknwon** [comment]
@aksh3ll any updates on this?

**Comment by aksh3ll** [comment]
yes: but on the locale name. sorry :-)
version: 0.6.0-1427291357.c5c5aac.trusty
in web-1.log:
>2015/03/25 20:34:49 [T] Custom path: /opt/gogs/custom
2015/03/25 20:34:49 [T] Log path: /opt/gogs/log
2015/03/25 20:34:49 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/03/25 20:34:49 [I] Log Mode: File(Info)
2015/03/25 20:34:49 [I] Cache Service Enabled
2015/03/25 20:34:49 [I] Session Service Enabled
2015/03/25 20:34:49 [I] Mail Service Enabled
2015/03/25 20:34:49 [I] Register Mail Service Enabled
2015/03/25 20:34:49 [I] Notify Mail Service Enabled
2015/03/25 20:34:50 [I] Run Mode: Production
panic: fail to set message file(fr-CA): open conf/locale/locale_fr-CA.ini: no such file or directory

i've copied /opt/gogs/conf/locale/locale_fr-FR.ini to locale_fr-CA.ini as a temporary fix and it works.
and now i can change the local and keep my relative path, thank you :-)

maybe i should open a new bug for the locale ?

and for apache2 conf mine is:
<VirtualHost *:443>
		...

        <Proxy *>
                 Order allow,deny
                 Allow from all
        </Proxy>

        ProxyPass /git http://127.0.0.1:6000
        ProxyPassReverse /git http://127.0.0.1:6000
</VirtualHost>

i'm not sure if the ProxyPassReverse is needed, but it works with, so...

**Comment by Unknwon** [comment]
> panic: fail to set message file(fr-CA): open conf/locale/locale_fr-CA.ini: no such file or directory

You should update all dependencies, all locale files put into binary since 0.6.0.

**Comment by aksh3ll** [comment]
i'm using the package from packager.io, it's probably missing from it, but since you change fr-CA to fr-FR, why it is still required ?

**Comment by Unknwon** [comment]
Maybe your `custom/conf/app.ini` has `[i18n]` section which still uses old name `fr-CA`.

**Comment by aksh3ll** [comment]
right !
so everything fixed, thanks a lot.
