### ISSUE TITLE
Github oauth is broken.

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1103]
I previously had everything working on my Gogs instance. At some point (And i'm not sure what version exactly), it got broken.

Right now, i'm able to use Google's oauth, but using Github's oauth gives me the following behavior:
- From my instance, being logged out, click on the Github's oauth button.
- Redirects me to Github credentials page, i login successfully.
- Redirects me to my instance, but Gogs isn't catching the token, and i'm left on the Gogs login page with no further informations.

Gogs gives the following log (Any occurrence to `[CUT]` is postprocessing as i don't want to expose some of the information):

```
[CUT]
[Macaron] Completed /user/login/oauth2/github?next=/user/info/github 302 Found in 19.96593ms
[CUT]
[Macaron] Started GET /user/info/github for 46.189.244.59
2015/03/20 12:09:46 [I] social.SocialSignIn(social login): &{0  }
2015/03/20 12:09:46 [T] social.SocialSignIn(oa): &{0 -1 <nil> 1 0 {"access_token":"[CUT]","token_type":"Bearer","expiry":"2015-03-20T13:05:47.799168968+01:00","Raw":{"access_token":"[CUT]","expires_in":3600,"id_token":"[CUT]","token_type":"Bearer"}} 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC false}
2015/03/20 12:09:46 [T] social.SocialSignIn(social ID): 2
[Macaron] Completed /user/info/github 302 Found in 500.029787ms
[CUT]
```

Have a look at the timestamps `0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC`, they don't look too good to me. Any clue please?

_edit for clarity's sake_: It gets weirder. After trying again, i successfully got the Gogs social account binding page. After doing so, i had a very weird result. So i truncated the oauth table and restarted Gogs, to make sure it was reproducible. The result is the same, now it sometimes binds with my Github account, but after the process shows me this:

![weird binding](https://cloud.githubusercontent.com/assets/822933/6750509/c06358a4-cef2-11e4-98c1-f0c9a1dfae4d.jpg)

In fact, the database looks like so:
```
# id, uid, type, identity, token, created, updated
'1', '1', '1', '0', '{\"access_token\":\"[CUT]\",\"token_type\":\"Bearer\",\"expiry\":\"2015-03-20T13:05:47.799168968+01:00\",\"Raw\":{\"access_token\":\"[CUT]\",\"expires_in\":3600,\"id_token\":\"[CUT]\",\"token_type\":\"Bearer\"}}', '2015-03-20 12:15:31', '2015-03-20 12:15:31'
```

Note that the `identity` column is zero'ed. Any idea? oO

**Comment by hickscorp** [comment]
It gets weirder. After trying again, i successfully got the Gogs social account binding page. After doing so, i had a very weird result. So i truncated the oauth table and restarted Gogs, to make sure it was reproducible. The result is the same, now it sometimes binds with my Github account, but after the process shows me this:

![weird binding](https://cloud.githubusercontent.com/assets/822933/6750509/c06358a4-cef2-11e4-98c1-f0c9a1dfae4d.jpg)

In fact, the database looks like so:
```
# id, uid, type, identity, token, created, updated
'1', '1', '1', '0', '{\"access_token\":\"[CUT]\",\"token_type\":\"Bearer\",\"expiry\":\"2015-03-20T13:05:47.799168968+01:00\",\"Raw\":{\"access_token\":\"[CUT]\",\"expires_in\":3600,\"id_token\":\"[CUT]\",\"token_type\":\"Bearer\"}}', '2015-03-20 12:15:31', '2015-03-20 12:15:31'
```

Note that the `identity` column is zero'ed. Any idea? oO

**Comment by hickscorp** [comment]
Sounds like a critical bug to me. As the identity is zero, let's say that multiple users use oauth and get these zero'ed identities, what would happend?... Wouldn't Gogs be confused and then let users use someone else's Gogs account because the identity would be the same? oO

**Comment by Unknwon** [comment]
I've noticed this myself, which is why I disabled demo site for all OAuth2 login, but it takes long time to debug.

**Comment by Unknwon** [comment]
Close now OAuth support in Gogs right now...
