### ISSUE TITLE
Creating repo for Organizations is broken

### ISSUE THREAD

**Issue by onuraslan** [gogits/gogs#1104]
After the latest update (0.6.0.0319) creating repo for organization is not working. Gogs stops completing any request if I try to create a repo for organization.

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

I think this is same to https://github.com/gogits/gogs/issues/1100 .

And what is your system and database?

**Comment by Unknwon** [comment]
When you have time, please comment on https://github.com/gogits/gogs/issues/1100 , thanks!
