### ISSUE TITLE
Uploaded avatar is not visible in dashboard commits

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1106]
It looks like it doesn't check if a locally uploaded avatar exists. I'm using offline mode.

Screenshot:
![2015-03-20-20238eb57](https://cloud.githubusercontent.com/assets/613331/6758091/5e8351c4-cf3e-11e4-9338-6d972eab31da.png)

**Comment by matt-h** [comment]
To add to this, it seems the commit avatar always uses the gravatar of the email address of the commit even if it matches a user.

It tested commits with different emails and they both showed their own gravatar and never my user gravitar or user uploaded avatar.

**Comment by Unknwon** [comment]
We are aware of this actually, but it hurts performance since Gogs hasn't had a app level cache layer.

**Comment by Unknwon** [comment]
This is fixed in the `develop` branch.
