### ISSUE TITLE
"Change your avatar" tooltip/link on any user page

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1107]
Visiting any user profile and hovering on any profile will show a tooltip to change avatar on gravatar.com.

![2015-03-20-2048ljl05](https://cloud.githubusercontent.com/assets/613331/6758143/c95d11a6-cf3e-11e4-8537-0af2a4b7149e.png)

---

On an unrelated note, it would be a good idea to add width/height attributes to avatar so that content doesn't jump while image is being loaded. It also seems that gogs resizes images to 200px, but user profile displays avatar in 234px.

**Comment by Unknwon** [comment]
> It also seems that gogs resizes images to 200px, but user profile displays avatar in 234px.

Good catch, thanks!

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/pull/1464
