### ISSUE TITLE
bad encoding on commit page 

### ISSUE THREAD

**Issue by mr-tron** [gogits/gogs#1108]
https://subgroup.org/git/mr_tron/karl/commit/c027a7267e3191b7775e9f0b3d34ac4833ac346c
file webui/triggers.py line 6
But in https://subgroup.org/git/mr_tron/karl/src/c027a7267e3191b7775e9f0b3d34ac4833ac346c/webui/triggers.py - encoding os ok

Looks like utf-8 text showed as cp-1252.

**Comment by mr-tron** [comment]
I don`t know that have been changed, but now it work ok.

**Comment by Unknwon** [comment]
Good to know! Thanks your confirmation
