### ISSUE TITLE
Run user isn't the current user

### ISSUE THREAD

**Issue by JesusIslam** [gogits/gogs#1109]
On installing gogs, I get `Run user isn't the current user: git -> ` error.

I use docker-compose and run gogs in a container.

I've tried changing the Run user into `root` but it says the same error `Run user isn't the current user: root -> `

How to fix this?

**Comment by Unknwon** [comment]
Hi @JesusIslam , Gogs reads `USER` and `USERNAME` to determine which user it is running under, you may want to assign one of those env vars in the Docker compose file.

**Comment by JesusIslam** [comment]
Thanks, it works now.
