### ISSUE TITLE
"View comparison for these 2 commits"

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1110]
Dashboard feed always says "2 commits" regardless of many actual commits there are when you push.

There might be 1 commit, there might be 6, it will still say "2 commits".

![2015-03-21-1353q5dqy](https://cloud.githubusercontent.com/assets/613331/6764970/9b99426e-cfd2-11e4-941a-9b4b31b9696b.png)

**Comment by Unknwon** [comment]
Thanks for the report!

Would change sentence to `View comparison for commits` be better? Because the actual link is comparing the **last commit before push** and the **last commit after push**.

**Comment by xPaw** [comment]
Sure, if it's hard to count how many actual commits there are. And perhaps hide that link if there is only one commit?

GitHub does it like this:
1 commit: no link
2 commits: `View comparison for these 2 commits »`
3 or more comments: `1 more commit »`

**Comment by Unknwon** [comment]
By merging https://github.com/gogits/gogs/pull/2125 , this should be fixed.
