### ISSUE TITLE
Private repositories issues included in 'Public Activity'

### ISSUE THREAD

**Issue by raunsbaekdk** [gogits/gogs#1112]
Steps

1) Create private repository
2) Create issue
3) Check public activity - it's hidden
4) Close issue
5) Check public activity - the title of the issue are now visible

Example: https://try.gogs.io/raunsbaekdk?tab=activity

**Comment by xPaw** [comment]
It's also worth noting that closing an issue shows up as "commented on issue" in activity.

**Comment by Unknwon** [comment]
Thanks for the report!

**Comment by atomi** [comment]
On ```Version: 0.6.1.0325 Beta ``` even creating and commenting on issues in a private repo shows up in "public activity".

**Comment by Unknwon** [comment]
@raunsbaekdk Hi, fix has been pushed to `develop` branch, please help test! Thanks for your patient! :beer:
