### ISSUE TITLE
'New Release' always visible

### ISSUE THREAD

**Issue by raunsbaekdk** [gogits/gogs#1114]
The 'New Release' button are always visible - always when you're not the owner of the repository.

Example: https://try.gogs.io/jonshape/derp/releases

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
Hi @raunsbaekdk , pushed fix to `master`

**Comment by raunsbaekdk** [comment]
@Unknwon Doesn't work. Still visible in my example link: https://try.gogs.io/jonshape/derp/releases

**Comment by Unknwon** [comment]
Oops, forgot to push. Please try again now. :)

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
