### ISSUE TITLE
'allow_git_hook' flag ignored when 'is_admin' flag is true

### ISSUE THREAD

**Issue by raunsbaekdk** [gogits/gogs#1115]
When 'is_admin' are set to true, the 'allow_git_hook' flag are ignored.

It seems like if you're admin, you're allowed to create Git hooks.

**Comment by Unknwon** [comment]
> It seems like if you're admin, you're allowed to create Git hooks.

Yes, why not? Even it's false, you're admin, you can change it to `enabled` anyway.

**Comment by raunsbaekdk** [comment]
Didn't thought of that, but you're right. Is there some way, we can make it possible to assign someone the admin role, without giving them the ability to check 'allow_git_hook'. So there would be a "superadmin" and there will be admins.

**Comment by Unknwon** [comment]
@raunsbaekdk that's reasonable but far beyond the current admin mechanism... not possible in near future I think. But you can turn in this issue into a feature request if you wish.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
