### ISSUE TITLE
0.6.0.0319 Issues can not assigned

### ISSUE THREAD

**Issue by ElvizLai** [gogits/gogs#1116]
As the pic shows, new issues can not assigned to team members.
In last release, this feature works well.
![qq20150322-1 2x](https://cloud.githubusercontent.com/assets/501861/6767954/8e70c360-d08a-11e4-8bca-1c66d1b16e84.png)

**Comment by bastiao** [comment]
It is related with re-open of this issue #747 -  I guess.

**Comment by Unknwon** [comment]
@bastiao right, related.

**Comment by aseidlitz** [comment]
Confirmed in Version: 0.6.1.0325 Beta

**Comment by f0086** [comment]
This bug is still open and very anoying. The whole issue tracker is not very usable without this feature :(

**Comment by da-kid** [comment]
+1

**Comment by Unknwon** [comment]
It is now possible to assignee anyone who has write access to the repository when create issue, try on https://try.gogs.io

**Comment by Unknwon** [comment]
Close as implemented. :tada:
