### ISSUE TITLE
Feature: Clean up views

### ISSUE THREAD

**Issue by sedrubal** [gogits/gogs#1118]
I think the views are quite messed up. There are, for example, different config and sign out buttons, completely different layouts and so on.

Expecially the issue view is completely different to all other views especially to the views listet in the tabs above (`Source`, `Commits`, `Issues`, `Releases`). So If someone clicks on a other tab and wants return to the issue view, he can't simply click on the other tab and the on the issue tab, but he has to search for the issues again or push the back button of the browser which is quite.

**Comment by Unknwon** [comment]
Thanks your feedback!

I think this is kind of same to https://github.com/gogits/gogs/issues/650 .

> So If someone clicks on a other tab and wants return to the issue view, he can't simply click on the other tab and the on the issue tab, but he has to search for the issues again or push the back button of the browser which is quite.

I don't understand this part very well.

**Comment by sedrubal** [comment]
oh sorry, yes, it might concern the same.

I tried to say that the tab-buttons are linking to other sites with other layouts and not to real tabs although they look like tab-buttons.

**Comment by Unknwon** [comment]
I see. No problem, I'll close this and please follow on that one!
