### ISSUE TITLE
diff page Chinese garbled, some files

### ISSUE THREAD

**Issue by mukaiu** [gogits/gogs#1119]
diff page Chinese garbled, some files
File encoding utf8
![qq 20150323003158](https://cloud.githubusercontent.com/assets/7746790/6770196/21a73dd0-d0f4-11e4-8436-fef2e2e9eb55.jpg)
![image](https://cloud.githubusercontent.com/assets/7746790/6770214/755e326c-d0f4-11e4-9ff8-03161a3d34e9.png)

**Comment by Unknwon** [comment]
Is file source code page showing those characters OK?

**Comment by mukaiu** [comment]
Source code page to normal

**Comment by Unknwon** [comment]
This should have been somewhat fixed along with another issue.
