### ISSUE TITLE
Can't exe new ownership update option when mirror repository transferred ownership 

### ISSUE THREAD

**Issue by melote** [gogits/gogs#1120]
Now my gogs user is 'melo' , I got this message if we transferred ownership  to the new user such as 'mirror-user', and 'mirror-user' can't update the mirror repository as well.
```
Fail to update mirror repository(/home/geil/gogs-server/repository/melo/xxx.git): chdir /home/geil/gogs-server/repository/melo/xxx.git: no such file or directory
```
The new version may exist this legacy issue, could be helpful to post it.
gogs version: Version: 0.5.13.0212 Beta

**Comment by Unknwon** [comment]
> The new version may exist this legacy issue, could be helpful to post it.

Yes, I remember someone posted already, just cannot find now. But I'll keep this open until I found the previous one.

Thanks!

**Comment by zenzire** [comment]
@Unknwon When do you plan to release binary package with fix? Unfortunately I am not able to create any new organization repositories and it is critical.

**Comment by Unknwon** [comment]
Hi @zenzire , hmm...

> Unfortunately I am not able to create any new organization repositories and it is critical.

Can you give more details on this?

**Comment by zenzire** [comment]
I use version 0.6.0 with SQLite and when I tried to create a new repository in organization, I got timeout error.

In database log there is something like this:

```
[xorm] [info]  2015/03/24 10:47:21.394460 [sql] UPDATE `repository` SET num_watches = num_watches + 1 WHERE id = ? [args] [35]
[xorm] [debug] 2015/03/24 10:47:21.395062 [time] UPDATE `repository` SET num_watches = num_watches + 1 WHERE id = ? - args [35] - execution took: 488569ns
[xorm] [info]  2015/03/24 10:47:21.395281 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [7 35]
[xorm] [info]  2015/03/24 10:48:18.087771 [sql] SELECT `id`, `uuid`, `type`, `url`, `payload_content`, `content_type`, `event_type`, `is_ssl`, `is_delivered`, `is_succeed` FROM `hook_task` WHERE is_delivered=? [args] [[false]]
[xorm] [info]  2015/03/24 10:48:21.787161 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [1]
```

**Comment by zenzire** [comment]
@Unknwon I see that there is already created issue about problems with creating new repositories #1100.

**Comment by Unknwon** [comment]
@zenzire that one has been fixed with newly uploaded binary.

**Comment by zenzire** [comment]
@Unknwon I downloaded and installed binary from https://github.com/gogits/gogs/releases and http://gogs.io/docs/installation/install_from_binary.html. And still creating a new repository for organization doesn't work.

Please let me know, where can I download the updated binaries for Linux?

**Comment by Unknwon** [comment]
@zenzire both places you go are having updated binaries for Linux, make sure you did not execute the old one again.

**Comment by Unknwon** [comment]
Also we should move discussion to  more relevant  issue #1100 :eyes:

**Comment by Unknwon** [comment]
Hi @melote , I've pushed fix to `master`, please help test again!

**Comment by melote** [comment]
would be my pleasure.

**Comment by melote** [comment]
Test OK, the admin panel's monitoring shows below:
```
Update mirrors	@every 1h	2015-03-26 17:21:00 +0800 CST	2015-03-26 16:21:00 +0800 CST	6
```
and the System Notices includes no more error infos.

**Comment by Unknwon** [comment]
@melote looks good! Thanks for confirmation!

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
