### ISSUE TITLE
Upgrade to 0.6 failed!

### ISSUE THREAD

**Issue by decker502** [gogits/gogs#1121]
Log show : 

````
2015/03/23 15:09:08 [I] Gogs: Go Git Service 0.6.0.0319 Beta
2015/03/23 15:09:08 [I] Log Mode: File(Trace)
2015/03/23 15:09:08 [I] Redis Enabled
2015/03/23 15:09:08 [I] Memcache Enabled
2015/03/23 15:09:08 [I] Cache Service Enabled
2015/03/23 15:09:08 [I] Session Service Enabled
2015/03/23 15:09:08 [I] Migration: refactor access table to use id's
2015/03/23 15:09:08 [install.go:65 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: drop access table: Error 1051: Unknown table 'access'
````
Shoud I add 'access' table first?

**Comment by Unknwon** [comment]
Hi, how old was your previous version?

**Comment by decker502** [comment]
It's 0.5.5.1010 Beta

**Comment by Unknwon** [comment]
Do these error occur when you first time run 0.6.0? Or you already ran multiple times to then still see this error?

**Comment by decker502** [comment]
Already ran multiple times!
And collaborators data was lost after degrade to 0.5.

**Comment by Unknwon** [comment]
collaborators now uses `collaborator` table, see if this table exists?

**Comment by decker502** [comment]
It's not exists, I only see `collaboration` table.

**Comment by Unknwon** [comment]
Oops, sorry for my typo. So is `collaboration` table empty?

**Comment by decker502** [comment]
It's not empty. And I see `access` table . Why log show that it's not exists?

**Comment by Unknwon** [comment]
Is `access` table empty?

**Comment by decker502** [comment]
Yes. I am sure that the table was not exists after I ran and failed.

**Comment by Unknwon** [comment]
Can you dump `log/gogs.log` file here? There may be other error messages could be helpful.

**Comment by decker502** [comment]
Sorry, I had dumped . No more data .

**Comment by Unknwon** [comment]
OK, please backup your database now, and re-run Gogs(create `access` table if it does not exist).

BTW, what is your database?

**Comment by decker502** [comment]
Amazing, I success. 
I use MYSQL.

**Comment by Unknwon** [comment]
@decker502 cool, please check if your organization, collaboration relations are still correct?

**Comment by decker502** [comment]
@Unknwon Yes, all is correct.
Thank u very much!

**Comment by Unknwon** [comment]
@decker502 no problem!

I haven't found out why MySQL fails because we mostly work on MySQL. But in your case all `access` data were already regenerable from `collaboration`.

**Comment by decker502** [comment]
This is  really  a problem.

Another problem always perplex me. I as admin can't access and manage other private repos. 
It should be to my understanding.

**Comment by Unknwon** [comment]
> Another problem always perplex me. I as admin can't access and manage other private repos. 
It should be to my understanding.

Right, someone posted issue about this.

**Comment by decker502** [comment]
OK.
