### ISSUE TITLE
All users email are public

### ISSUE THREAD

**Issue by blemasle** [gogits/gogs#1127]
Email for all users can be found using the api with in the worst case with around 30 calls.
* /api/v1/users/search?q=a
* repeat the operation for each letter
* query /api/v1/users/:username with the result form the api

Those api should not be usable without an authentication token, or at least email should not be displayed when not logged in.

**Comment by raunsbaekdk** [comment]
@Unknwon Are there an ETA on this one?

**Comment by Unknwon** [comment]
@raunsbaekdk I've put into release 0.6.2.

**Comment by Unknwon** [comment]
Hi @blemasle , @raunsbaekdk , fix has been pushed `develop` branch and can be tested here: https://try.gogs.io/api/v1/users/unknwon

**Comment by Unknwon** [comment]
Close as implemented, feel free to continue discussion! :smile:

**Comment by blemasle** [comment]
Great, thanks @Unknwon !

**Comment by Unknwon** [comment]
No problem!
