### ISSUE TITLE
API calls are not hidden behind sign in

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1128]
If sign in is required in config, you can still use API to get any info, for example `/api/v1/users/search?q=a`

**Comment by raunsbaekdk** [comment]
@Unknwon Is there an ETA on this one?

**Comment by Unknwon** [comment]
@raunsbaekdk I've put into release 0.6.2.

**Comment by Unknwon** [comment]
Fix has been pushed to `develop` branch. :dizzy:

**Comment by Unknwon** [comment]
Close as implemented, feel free to continue discussion! :smile:
