### ISSUE TITLE
Can't send mails

### ISSUE THREAD

**Issue by solusipse** [gogits/gogs#1129]
I got this strange error no matter how I configure mailer section in `app.ini` (even if host isn't localhost i get same message):
```
[asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: xxxxxx@xxxx.xx, info: UID: 1, send reset password email err: missing port in address localhost
```

Smtp server is configured to use 587 port, it's running on localhost. I tried to put these in mailer section but no luck:
`HOST = mail.mydomain.com:587`
`HOST = mail.mydomain.net`
`HOST = localhost`
`HOST = localhost:587`

I recently updated to newest version without merging `app.ini`, maybe it's the reason?

**Comment by Unknwon** [comment]
Which `app.ini` are you modifying?

**Comment by solusipse** [comment]
Damn, I forgot about `custom/conf/app.ini` and edited `conf/app.ini`. Sorry!

**Comment by Unknwon** [comment]
@solusipse hmm... no problem! Is it working now?

**Comment by solusipse** [comment]
Flawless, thank you!

**Comment by Unknwon** [comment]
Great!
