### ISSUE TITLE
Installation doesn't check if the port specified is in use

### ISSUE THREAD

**Issue by steelbrain** [gogits/gogs#1131]
Took me quite some time to figure out that the port I had specified (9000) was being used by an fcgi server.
It would be nice to have gogs try and see if the port is available and cry if it's not.

**Comment by Unknwon** [comment]
Thanks your feedback!

Gogs does print an error message if it fails to listen on given address and port. I think you just ignored the logs.

**Comment by steelbrain** [comment]
Yes, it does. But at boot time only, not when we have started it and are going through initial installation.

**Comment by Unknwon** [comment]
I see, I got your point now!

**Comment by Unknwon** [comment]
Hmm... I'm losing idea how to fix this. Any thoughts?

**Comment by steelbrain** [comment]
@Unknwon When we specify a port during installation, it should try to listen on that port, if it can't it should not let the user proceed

**Comment by Unknwon** [comment]
:D Glad you're still here.

Please see https://github.com/gogits/gogs/blob/master/cmd/web.go#L59

At some point I've implemented this.

**Comment by steelbrain** [comment]
That's awesome! Thanks!

**Comment by Unknwon** [comment]
:tada:
