### ISSUE TITLE
Mirrored repository isn't updated

### ISSUE THREAD

**Issue by romanoff** [gogits/gogs#1132]
Hello,
  I have started gogits on a server. I have cloned a repository and made it a mirror (+ -> New migration, set checkbox for "This repository will be a mirror"). I also had to specify authorization credentials for  the mirror and changed repository name. Everything was cloned successfully. I also updated mirror interval and set it to 1 hour.

I waited for "update mirrors cron task" to be executed watching `/admin/monitor`. After this happened, my repository was still not updated. Going manually to gogits-repositories/<username>/<reponame>.git and doing `git fetch origin` fixed the issue.

Possible the reason is that I renamed repository. Here is error I found in `gogs/log/gogs.log`:

```
2015/03/23 16:11:07 [session.go:933 Iterate()] [E] Fail to update mirror repository(/home/git/gogs-repositories/<username>/<renamed repository name>.git): chdir /home/git/gogs-repositories/<username>/<renamed repository name>.git: no such file or directory
```

**Comment by Unknwon** [comment]
Hi @romanoff , I've pushed fix to `master`, please help test again!

Also, this is duplicated to https://github.com/gogits/gogs/issues/1120 so I'm going to close this one and please follow on that one. Thanks!
