### ISSUE TITLE
SSH Key Enforcement Limitation

### ISSUE THREAD

**Issue by zacheryph** [gogits/gogs#1133]
I do understand the reasoning for having required minimums for ssh keys.  But enforcing this and not allowing it to be modified is very restricting.  Maybe I am the only one with this problem but I use Cloud66 to manage my production environments and it creates 1024 bit keys.  Yes i have requested they make this changeable or default to 2048.

If this is something thats going to be enforced the way it is, there should either A: be the option to enable/disable it, or B: modify the minimum requirements.  Or make these limitations widely known.

Yes, I do understand its for security but at what cost?  So now Im stuck:

* waiting for cloud66 to update (not possible, i need to get code out there)
* going back to another solution (gitlab, possible but id rather not)
* depend on external public hosting sites (then whats the point of self hosting)

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

What version of Gogs and system you are using?

**Comment by zacheryph** [comment]
Ubuntu 14.04, Gogs 0.6.0.0319

0.6.0-1427038154.529b6f0.trusty - installed via packager.io

**Comment by Unknwon** [comment]
Thanks your info!

Let me see if this is possible to make easy change to allow 1024 key and prompt a warning message. Does this sound good to you?

**Comment by zacheryph** [comment]
that sounds excellent.  If you want I could probably look at getting this in place as well.  I wanted to make sure to get a ticket in at least first

**Comment by Unknwon** [comment]
Sure, I think this is the place: https://github.com/gogits/gogs/blob/master/models/publickey.go#L104-L114

Is your key is RSA 1024?

**Comment by zacheryph** [comment]
Yes it is RSA 1024.

**Comment by Unknwon** [comment]
@zacheryph thanks for classifying!

**Comment by Unknwon** [comment]
Hi @zacheryph , pushed fix to `master`, now you're able to use `[service] DISABLE_MINIMUM_KEY_SIZE_CHECK = true` to disable minimum check.

**Comment by zacheryph** [comment]
Ahh nice.  I was attempting to do a warning but couldn't get it.  This works also.  Awesome, thank you.

**Comment by Unknwon** [comment]
No problem!

**Comment by Unknwon** [comment]
How's going on this one?

**Comment by zacheryph** [comment]
This is working as expected.  Love it.  Thank you.  Can be closed :D

**Comment by Unknwon** [comment]
Great, thanks for confirmation!

**Comment by zacheryph** [comment]
Hehe.  I did have an issue with the Locale file yesterday.  I renamed it locally and everything came up just fine

**Comment by Unknwon** [comment]
Cool, actually I added a auto-fix for that locale thing last night.
