### ISSUE TITLE
supervisord script does not work

### ISSUE THREAD

**Issue by martinellison** [gogits/gogs#1134]
When I try to run the supervisord script I get (on Fedora):

[root@di1 gogs]# ./scripts/gogs_supervisord.sh start
/var/local/gogs/scripts
ln: failed to create symbolic link ‘/usr/bin/gogs_start’: File exists
starting
./scripts/gogs_supervisord.sh: line 29: supervisord: command not found
started

**Comment by Unknwon** [comment]
This is a snapshot of supervisor under Ubuntu, not sure but should be pretty same:

```
[program:gogs]
directory=/home/git/go/src/github.com/gogits/gogs/
command=/home/git/go/src/github.com/gogits/gogs/gogs web
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/gogs/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/gogs/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
environment = HOME="/home/git", USER="git"
```

From tutorial https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04

**Comment by martinellison** [comment]
OK, but I am running on Fedora, so did not see that FAQ. 

I have installed supervisord and added your configuration section, with relevant changes, and it seems to be working now. 多謝！

**Comment by Unknwon** [comment]
@martinellison no problem, my pleasure!
