### ISSUE TITLE
0.6 has no app.ini

### ISSUE THREAD

**Issue by martinellison** [gogits/gogs#1135]
According to the documentation, as I read it, we are supposed to copy over app.ini to custom/app.ini and make some changes. However, there is no app.ini file to copy. This is in the current version 0.6.

**Comment by Unknwon** [comment]
Hi, docs also says `Since v0.6.0, this file is embeded into binary.`, see http://gogs.io/docs/advanced/configuration_cheat_sheet.html for help.

**Comment by Unknwon** [comment]
Close for now, feel free to reopen if you want to continue discussing. :wink:
