### ISSUE TITLE
0.6 not reading custom/app.ini

### ISSUE THREAD

**Issue by martinellison** [gogits/gogs#1136]
when I try running a new install using ./gogs web, it is trying to read from 0.0.0.0 and not from the correct IP address. This seems to be because it is not reading custom/app.ini (hard to tell for sure).

**Comment by martinellison** [comment]
Sorry, the error message was in yellow and hard to read on a white background; you might want to make it a better colour.

**Comment by Unknwon** [comment]
> Sorry, the error message was in yellow and hard to read on a white background; you might want to make it a better colour.

Hmm, which error message? Give a screenshot would be cool.
