### ISSUE TITLE
MySQL root password exposure

### ISSUE THREAD

**Issue by tsumaru720** [gogits/gogs#1140]
Once Gogs is installed, if you re-enable the install page via INSTALL_LOCK=false, the MySQL root password is visible in the HTML source.

As Gogs clearly already knows about config values, maybe just fill out the SQL password with Asterisks or keep it empty with some text advising that it will change if updated.

Gogs Version: 0.6.0.0319 Beta

**Comment by Unknwon** [comment]
Hi @tsumaru720 , pushed fix on `master`.

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
