### ISSUE TITLE
Crash when pushing a tag

### ISSUE THREAD

**Issue by GithSystems** [gogits/gogs#1142]
Hi,

When pushing  a local tag on the server, "gogs web" halts suddently.

Client side :
    git push --tags
    error: RPC failed; result=52, HTTP code = 0
    fatal: The remote end hung up unexpectedly
    fatal: The remote end hung up unexpectedly

On the server side, gogs web is stopped and http logfile shows :
     "2015/03/24 15:04:36 [http.go:339 serviceRpc()] [F] runUpdate.GetTag: strconv.ParseInt: parsing "Tue": invalid syntax"

After restart, when trying to display release page the following error is shown :
    [Macaron] Started GET /Tanker/GithClient/releases for 10.1.31.2
    2015/03/24 15:04:58 [release.go:84 Releases()] [E] GetCommitOfTag2: strconv.ParseInt: parsing "Tue": invalid syntax
    [Macaron] Completed /Tanker/GithClient/releases 500 Internal Server Error in 47.792739ms

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version?

**Comment by GithSystems** [comment]
(oops sorry !) 
My version is : Gogs version 0.5.13.0212 Beta

**Comment by Unknwon** [comment]
Cool, would you like try to push on https://try.gogs.io/ see if anything goes wrong? If that's OK to your code, you can create a private repo to test as well.

**Comment by GithSystems** [comment]
Ok, the same repo crashes my own server but not yours (https://try.gogs.io/benoit/TestDeps/releases) when pushing the same tag.
Strange !

**Comment by Unknwon** [comment]
Found it! https://github.com/gogits/gogs/issues/663

Same issue, fixed `18 days ago` means after `v0.5.13` release, so the latest release `v0.6.0` should no longer has this issue.

**Comment by GithSystems** [comment]
Great !
I'll update and confirm, thanks !

**Comment by Unknwon** [comment]
However there is a chance the bug still exists because I really don't how to change my Git commit date format to the one you have.

**Comment by GithSystems** [comment]
I just updated to 0.6.0 and everything seems to be fine, all my tags are there!
Thanks again,

  Benoit

**Comment by Unknwon** [comment]
@GithSystems thanks for quick feedback!
