### ISSUE TITLE
Team member access lost when adding repository collaborator

### ISSUE THREAD

**Issue by jcracknell** [gogits/gogs#1143]
Issue seems to be in `models/access.go`, `recalculateTeamAccesses` and `recalculateAccesses` seem as though they would wipe each other's entries.

**Comment by phsmit** [comment]
Yes, it seems @Unknwon has tried to made some speed improvements that make it incorrect (https://github.com/gogits/gogs/commit/473e265727c1e47dd83e3f66a5cc92d2f027d951)

@Unknwon The method was quite efficient already, and it was combined for the exact reason that it is hard to delete the right old entries from the table (a form of the cache invalidation problem). I suggest you revert it to the earlier method, and if you want speed improvement it could be replaced with the "insert into select" paradigm (but that would require a lot of testing on all three db platforms).

**Comment by Unknwon** [comment]
@phsmit I didn't do speed improvements at all except leave a comment says we might do at some point. I think this issue is about when add a collaborator to repo, should check if this repo belongs to individuals or organization. Then call the properly recalculate method.

**Comment by phsmit** [comment]
But wasn't there only one recalculate method, which recalculates for the whole repository?

**Comment by jcracknell** [comment]
...which is how I would have expected it to be implemented. Multiple methods is asking for trouble, particularly for an operation that happens infrequently, and therefore can be slow.

**Comment by Unknwon** [comment]
@phsmit based on the type, both of them recalculate for whole repository. There is a special case(I think it's remove a repo from team) need to pass a ignore team ID.

**Comment by phsmit** [comment]
Ok. I can have a small look tomorrow afternoon and see if I can find the problem

**Comment by Unknwon** [comment]
I think the solution is to add a check here: https://github.com/gogits/gogs/blob/master/models/repo.go#L1118

**Comment by Unknwon** [comment]
@phsmit @jcfrank pushed fix to `master` along with another critical bug, you can test on https://try.gogs.io as well.

**Comment by jcracknell** [comment]
I'll try and find time to test this tomorrow.

**Comment by jcracknell** [comment]
@Unknwon Seems to work.

**Comment by Unknwon** [comment]
@jcracknell thanks for confirmation!
