### ISSUE TITLE
TLS and BindDN

### ISSUE THREAD

**Issue by ArKam** [gogits/gogs#1145]
As discussed earlier on the LDAP documentation page of the project, it would be really cool to improve some functionalities on Gogs regarding the way it talk to LDAP Authentication Endpoint.

**1. Support of the BindDN property to allow more complex filters and LDAP requests against some secured LDAPs.**

**2. It seems that GO-LDAP support TLS Transport channel, both, ActiveDirectory AND OpenLDAP support LDAP over TLS which is the successor of Older SSL transport.**

As I pointed it out on the documentation page, when people talk about SSL support they mostly talk about TLS support now a day.

As I said, those two options are very important one when a SysAdmin benchmark future solutions for enterprise grade services (among many others).

**Comment by flotho** [comment]
could it be a duplicate of #472 for the first point?

**Comment by ArKam** [comment]
Absolutly, I was in direct talk with the author regarding this issue entry and so made it on github as requested without checking previous entry but from the screens and discussion on your link (I'm sorry I can't read Mandarin), the first is a duplicate request.

Gogist creator asked me to create this entry as I explained him clearly why and how works this request.

**Comment by flotho** [comment]
Hy @ArKam 

Great thanks for your answer

**Comment by ArKam** [comment]
You're welcome ;-)

**Comment by smarmit** [comment]
+1 I believe we would be using gogs in our enterprise if we had the authenticated (bind) support for LDAP. Thx.

**Comment by Unknwon** [comment]
Hi there, by mering PR #1476 into develop, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by ArKam** [comment]
Hi @unknown, I can confirm that you can close this issue as the proposed merge is everything we needed ! The merger made a tremendous job on its patch and refactor of the ldap code, good job and I'm happy to hear back on this topic!

**Comment by Unknwon** [comment]
@ArKam Thanks your confirmation!
