### ISSUE TITLE
Access rights for collaborators

### ISSUE THREAD

**Issue by cybrwushl93** [gogits/gogs#1146]
It would be nice to specify access rights for collaborators. I think of three levels:
- admin: deleting repo, ...
- write: make changes
- read: readonly

**Comment by jcracknell** [comment]
This would be a good feature, I have always thought GitHub should have a "friends" feature in the [C++ sense](http://www.cplusplus.com/doc/tutorial/inheritance/) where "friends can touch each others' private parts". :wink:

**Comment by burzum** [comment]
+1 this would be really useful.

I've installed gogs because I wanted to give read only access on some private repos and now I figured out I can't... :(

**Comment by Unknwon** [comment]
@burzum yes, the foundation is there, this issue is waiting in line to be implemented :D

**Comment by burzum** [comment]
@Unknwon I'm not a Go developer but what exactly is still missing from finishing this feature?

I might look at it and try to complete it.

**Comment by Unknwon** [comment]
@burzum different people have different interests, I can't make everyone happy :sweat:

**Comment by TilmannBach** [comment]
i think organization collaborators should be able to close issues, even if they are not the owner of them

**Comment by Unknwon** [comment]
@TilmannBach I think they should at least have `write` permission.

**Comment by fnkr** [comment]
I would suggest the following permission scheme:

Action | Read | Write | Admin
--- | --- | --- | ---
browse & clone code/wiki | yes | yes | yes
create issues | yes | yes | yes
push & add/edit releases | no | yes | yes
edit issue labels/milestone/assignee | no | yes | yes
write & push wiki | no | yes | yes
everything in the `Settings` tab | no | no | yes

**Comment by Unknwon** [comment]
@fnkr :+1:

**Comment by TilmannBach** [comment]
* CLOSE issues - no - yes -yes

**Comment by fnkr** [comment]
@TilmannBach Good catch! Updated my comment.

**Comment by rajder** [comment]
Awesome project! Good feature request, I might dig into this project and try to contribute... just not right now :)

**Comment by tebanep** [comment]
+1

**Comment by rajder** [comment]
My use case would be to give specific users read access to some private repos and require pull requests for collaboration.

**Comment by Unknwon** [comment]
> require pull requests for collaboration.

@rajder that would be part of branch protect feature

**Comment by fnkr** [comment]
@Unknwon I updated [my comment above](#issuecomment-180988947) and added permissions for pull requests.

create pull request - yes - yes - yes
merge/close pull request - no - yes - yes

People with read only permissions should be able to create pull requests.

Do you agree?

**Comment by Unknwon** [comment]
@fnkr LGTM, thanks!

**Comment by hhenkel** [comment]
Is this not also related to #776 ?

**Comment by Unknwon** [comment]
@hhenkel why?

**Comment by fnkr** [comment]
Maybe he means something like:

- Admins should be able to push directly to master
- Admins should be able to merge a merge request with less then two up votes

Could be a good idea. Maybe. Who knows?

**Comment by Unknwon** [comment]
@fnkr thanks! But this issue is about collaborators, not admins...

**Comment by hhenkel** [comment]
@Unknwon from my understanding this issue (as described in @fnkr table) should enable us to restrict access to certain functions of a repository. Especially for this case

merge/close pull requests | no | yes | yes 

the implemented behavior will have an impact on the implementation of #776?

**Comment by Unknwon** [comment]
@hhenkel OK... in the case of protected branch:

1. should add just only allow admin level access to merge 
2. or users can choose what's minimal level of access level can merge?

**Comment by hhenkel** [comment]
@Unknwon imho the second option is what one would want. However it seems like the implementation of protected branches would require more work/thinking on a more sophisticated privilege concept.

**Comment by Unknwon** [comment]
@hhenkel yes, when it comes to protected branch, the access level could be ignored/overwrite, but that's should be discussed under that thread.

**Comment by Unknwon** [comment]
Whoever watches on this thread, you can now follow [this guide](https://discuss.gogs.io/t/how-to-manage-collaborators/87) to test on `develop` branch or demo site.

**Comment by moltam** [comment]
@Unknwon It seems to working. I tested all use cases in the table with an reader/writer/admin collaborator. I didn't find any problems. Although others should test it too, I may have missed something...

Thank you!

**Comment by Unknwon** [comment]
@moltam thanks for the testing!

**Comment by Unknwon** [comment]
Close as implemented.

**Comment by miqmago** [comment]
I'm not really sure if this is the expected behavior: I have an organization where I've added a user in `myorganization/members` as member and also in `myorganization/teams` as admin

I create a private repo on the organization but this member cannot access to the repo until I add him into `settings/collaboration`.

This is quite confusing and just wanted to check if this is an issue or as expected.

**Comment by Unknwon** [comment]
@miqmago a member can access a private repository in an organization if:

1. His team has access to the repository
2. He is a collaborator of the repository
