### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by Aidoboy** [gogits/gogs#1148]
I'm trying to update to v0.6.0 and I get this when I try to build:
```
git@gitpi ~/go/src/github.com/gogits/gogs $ go build
# github.com/gogits/gogs/cmd
cmd/web.go:138: unknown "github.com/macaron-contrib/i18n".Options field 'Files' in struct literal
cmd/web.go:470: ctx.ServeFileContent undefined (type *middleware.Context has no field or method ServeFileContent)
```

**Comment by Aidoboy** [comment]
I get the same error when I run go get ./...

**Comment by Unknwon** [comment]
@Aidoboy you need to run `go get -u ./...` in order to fetch updates.

**Comment by Aidoboy** [comment]
Woops, I forgot to post here after I solved it. I had to re-run `go get -u github.com/gogits/gogs` to update the dependencies.

**Comment by Unknwon** [comment]
@Aidoboy cool, so everything is working now?

**Comment by Aidoboy** [comment]
Yeah, everything's fine.

**Comment by Unknwon** [comment]
Good, so I'm closing it now. :wink:
