### ISSUE TITLE
Explore page should indicate author names

### ISSUE THREAD

**Issue by Calinou** [gogits/gogs#1150]
Currently, it looks like this:

![Image](https://lut.im/c0gPAgzz/ZUyMwXS6)

What about adding the author's name in a smaller font, before the repository name?

**Comment by Unknwon** [comment]
Good point!

**Comment by nounoursheureux** [comment]
It is fixed.

**Comment by Unknwon** [comment]
See examples here: https://try.gogs.io/explore
