### ISSUE TITLE
gogs web hangs in starting loop Ubuntu 14.04

### ISSUE THREAD

**Issue by evook** [gogits/gogs#1151]
Hi, since updating from the package repo today gogs web won't start propaly. This log entry repeats over thousands of lines. 

2015/03/26 00:02:51 [T] Custom path: /opt/gogs/custom
2015/03/26 00:02:51 [T] Log path: /opt/gogs/log
2015/03/26 00:02:51 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/03/26 00:02:51 [I] Log Mode: File(Info)
2015/03/26 00:02:51 [I] Cache Service Enabled
2015/03/26 00:02:51 [I] Session Service Enabled
2015/03/26 00:02:51 [I] Run Mode: Production
panic: fail to set message file(fr-CA): open conf/locale/locale_fr-CA.ini: no such file or                         directory

goroutine 1 [running]:
github.com/macaron-contrib/i18n.initLocales(0xc208114023, 0x0, 0xcdb2f0, 0xb, 0xc2085589f0,                         0xc20800bf40, 0x1c, 0xc208064160, 0xb, 0xb, ...)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/macaron-contrib/i18n/i1                        8n.go:54 +0x7ce
github.com/macaron-contrib/i18n.I18n(0xc2084310a0, 0x1, 0x1, 0x0, 0x0)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/macaron-contrib/i18n/i1                        8n.go:151 +0xe0
github.com/gogits/gogs/cmd.newMacaron(0xc20815e2a0)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/cmd/web.go:                        143 +0xb98
github.com/gogits/gogs/cmd.runWeb(0xc20815e2a0)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/cmd/web.go:                        185 +0xbe
github.com/codegangsta/cli.Command.Run(0xcaff30, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd0f2d0, 0x                        15, 0xde3db0, ...)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/codegangsta/cli/command                        .go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc20816a000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/codegangsta/cli/app.go:                        177 +0xdf6
main.main()
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/main/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20806f5c0)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log                        /log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log                        /log.go:161 +0x13a

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/mai                        ler/mailer.go:53 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/mai                        ler/mailer.go:47 +0xea

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208118a40)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log                        /log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log                        /log.go:161 +0x13a

goroutine 36 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc20816f440)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/cro                        n/cron.go:162 +0xa65
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/cro                        n/cron.go:137 +0x3d

goroutine 24 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20824e640)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 37 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20823e300)
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log                        /log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /tmp/d20150325-14-13gn9vh/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log                        /log.go:161 +0x13a

**Comment by Unknwon** [comment]
Hi, delete `[i18n]` section in file `custom/conf/app.ini` file should fix it.

**Comment by evook** [comment]
Fixed, thank you!

**Comment by Unknwon** [comment]
@evook no problem!
