### ISSUE TITLE
View branch of the commit in commits list

### ISSUE THREAD

**Issue by davmrtl** [gogits/gogs#1153]
Like on Bitbucket, it should be nice to display the branch of the commit in the commits list.

![2015-03-25 22_34_09-davmrtl _ littledebt _ commits bitbucket](https://cloud.githubusercontent.com/assets/233767/6839486/6f75c20a-d33f-11e4-8fd9-1a9240ac45d1.png)

**Comment by davmrtl** [comment]
I just saw that in Gogs, you can only see the commits of one branch at the time since in Bitbucket, there's an option "Show all" to list all commits of all branches.

**Comment by karasz** [comment]
+1

**Comment by Unknwon** [comment]
I think in Gogs, https://github.com/gogits/gogs/issues/1846 is good enough.
