### ISSUE TITLE
Autostart on Centos 6

### ISSUE THREAD

**Issue by depl0y** [gogits/gogs#1154]
I installed Gogs on my Centos 6 machine using the "binary" guide.

I created a `git` user and did all the steps. I also added the `gogs` startup script (from https://github.com/gogits/gogs/blob/master/scripts/init/centos/gogs) to my /etc/init.d folder and added the startup script to my startup sequence using `chkconfig --add gogs`. The script is listed as `S85gogs` in:

- `/etc/rc2.d`
- `/etc/rc3.d`
- `/etc/rc4.d`
- `/etc/rc5.d`

I tested my configuration using `sudo service gogs start`, which starts the gogs service properly and it is reachable through my proxy in apache (yay!).

After that I rebooted my machine to see if it started automatically, but it is not auto starting. The `boot.log` shows that gogs starts correctly:

`Starting Gogs Go Git Service: ^[[60G[^[[0;32m  OK  ^[[0;39m]`

But the gogs service is still unavailable. Also a `sudo service gogs status` shows that my gogs service is stopped.

I have the feeling this is a permissions problem, but I can't seem to find out why. My gogs permissions are `-rwxr-xr-x.  1 root root  1774 Mar 26 11:33 gogs`. These are the same as the other services running at my system.

One minor detail, when my `git` user tries to start the service, I get the following message, not sure this is related to the problem or just because the user isn't tied to any group.

```
$ service gogs start
Starting Gogs Go Git Service: runuser: cannot set groups: Operation not permitted
                                                           [FAILED]
```

**Comment by Unknwon** [comment]
Hi, I'm not sure this is the reason Gogs fails to start :+1: 

> Starting Gogs Go Git Service: runuser: cannot set groups: Operation not permitted

Maybe you need to use `sudo service gogs start` for this.

For reboot, do you have any log from `log/gogs.log`? There should be some error message if Gogs itself refuse to start.

**Comment by Unknwon** [comment]
Also from some search, it might be a SELinux issue: http://unix.stackexchange.com/questions/80066/postgresql-service-start-issues

**Comment by depl0y** [comment]
Yup, `sudo service gogs start` does work. I mentioned this in my original post. 

The logs in the `/log` folder do show an error indeed. It seems that my MySQL server isn't started before my gogs service is started. There is a `mysqld` script in `init.d`, but it doesn't have an `on` in my `chkconfig --list`. Maybe this is because it is started by Plesk (which is installed on my server too).

Damn, I wish I knew more about this on Centos.

**Comment by Unknwon** [comment]
Right, does `init` has something like require a service to start before this one? Like systemd.

**Comment by Unknwon** [comment]
BTW, I'm using CentOS 7 with systemd and it works well for weeks so far.

**Comment by depl0y** [comment]
Upgrading is something I had in mind for a couple of weeks now, but I am hosting a couple of sites and I do need Plesk to keep everything organized. Not sure an upgrade will go so well. 

In other news, the gogs init.d script does have this:

```
### BEGIN INIT INFO
# Provides:          gogs
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start gogs at boot time.
# Description:       Control gogs.
### END INIT INFO
```
I wonder if I can do something with the "Required-Start" from this.

**Comment by Unknwon** [comment]
`Required-Start` looks the right way to try.

PS: my point isn't CenOS 7, but systemd, if you would consider to switch to it. I'm not pro on this kind of thing but at least I got working solution :eyes:

**Comment by depl0y** [comment]
Ah yes, well I will try to fiddle with the Required-Start.

As I read it, `systemd` is only for Centos 7?

**Comment by Unknwon** [comment]
Oops, my bad... that's so sad!

**Comment by depl0y** [comment]
No problem, it seems solved now. I downgraded the priority from 85 to 99 and that fixed it. My Plesk control panel also had the priority 85 and that is now started before gogs.

Awesome! Thanks for the pointers!

**Comment by Unknwon** [comment]
No problem, my pleasure!
