### ISSUE TITLE
Change repo name and then get 404

### ISSUE THREAD

**Issue by zijing07** [gogits/gogs#1155]
- Bug Description: After I change the repo name in the setting page, `gogs` will redirect to the setting page of the repo with the old name, since I have change the repo name, a 404 error will be raised. It goes well with the new repo name.
- Gogs Version: 0.6.1
- Gis Version: 1.9.1
- System Type: CentOS 7

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

But I cannot reproduce it on https://try.gogs.io which has exactly same env as yours.

**Comment by zijing07** [comment]
I see, I will try it tomorrow to see whether if I can reproduce it. Thanks for your amazingly rapid response.

**Comment by Unknwon** [comment]
@zijing07 haha, no problem, I'm just releasing 0.6.1, so... :stuck_out_tongue_closed_eyes:

**Comment by zijing07** [comment]
Sorry I checked my server today, the gogs version was 0.6.0 Beta. There is no problem now.
