### ISSUE TITLE
Avatar-related settings feedback

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1157]
1. This checkbox should probably be hidden if gravatar is disabled.
> Enable Custom Avatar   Enable this to disable fetch from Gravatar
2. Add a button to delete current uploaded avatar
3. Display current custom avatar

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by xor-gate** [comment]
It should be noted that the user profile also still has the gravar tooltip and hyperlink when gravatars are disabled.

![gogs_user_profile_gravar_tooltip](https://cloud.githubusercontent.com/assets/1050166/11715619/a06a176e-9f43-11e5-91e0-b5f4fed83afd.png)

**Comment by Unknwon** [comment]
Be sure you read the tooltip by each world.

**Comment by Unknwon** [comment]
Adjust some changes about avatar, and you can delete current avatar now.
