### ISSUE TITLE
Ability to view repository size

### ISSUE THREAD

**Issue by boarpig** [gogits/gogs#1158]
I think it would be useful to be able to see the repository size when viewing either the repository main window or in the settings windows.

It would also be useful to be able to see repository size for each repo in Admin panel's repository list.

**Comment by jacobhands** [comment]
I'm going to take a shot at this.

**Comment by drsect0r** [comment]
+1 @jacksonpan how is it going? If you're currently not working on this; I'm going to take a shot this weekend.

**Comment by jacobhands** [comment]
Hey yeah, life happened etc and I haven't had time. Go for it.

**Comment by DblK** [comment]
Should be linked to #1294 for the way to compute size.

@drsect0r are you still working on this one?

**Comment by drsect0r** [comment]
@DblK It is still on my todo list. Feel free if you want to have a go at it.

**Comment by DblK** [comment]
I modified in the admin section to see the size:
![image](https://cloud.githubusercontent.com/assets/832617/18352934/a18ed5a2-75e0-11e6-993e-6c1fcfd62317.png)

Need to finish implementation of triggering repo size before PR.
For now it's only a fake data in the database but will be soon operational once the triggering will be done.
I will add in another PR after this one will be merged, the user display size and repo.

**Comment by DblK** [comment]
Now it's working !
![image](https://cloud.githubusercontent.com/assets/832617/18387049/8f7a4fa8-769a-11e6-9069-f4065c786295.png)

To keep the PR small, I did not implemented the user menu to display repository including the size.
Once the first PR will be merge, I will make the GUI change for user settings.

**Comment by DblK** [comment]
Once the PR #3631, I already have the next PR for closing this issue.
Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/832617/18469769/ae4d23a8-79a9-11e6-8382-0123eb28e37c.png)

I will continue to tweak the display. Maybe a table for another display same as GitHub.
Here is in GitHub:
![image](https://cloud.githubusercontent.com/assets/832617/18469818/f2cba86a-79a9-11e6-90be-8b924fe896be.png)

Any thought?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch. Currently only admin can view size in admin panel. For user to view own repo sizes, please follow https://github.com/gogits/gogs/issues/4277.

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/23829814/ca81e8dc-06d1-11e7-9921-62aeda396d07.png)

Depends on how many repositories you have, migration could take from few seconds to few minutes. In the case of demo site, 6.5k took about 3 mins.
