### ISSUE TITLE
Files created by Gogs are owned by root

### ISSUE THREAD

**Issue by drew-y** [gogits/gogs#1160]
Whenever I attempt to push to a repository i get the following error:
```bash
Andrews-iMac:second-test-repo andrewyoungwerth$ git push origin master
Counting objects: 5, done.
Writing objects: 100% (3/3), 280 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: error: insufficient permission for adding an object to repository database ./objects
remote: fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To git@drew.club:drew/second-test-repo.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'git@drew.club:drew/second-test-repo.git'
```
When I examine the file permissions it appears that new repos are owned by root:
```bash
drwxr-xr-x 7 git  root 4096 Mar 27 02:05 my-test-repo.git
drwxr-xr-x 7 root root 4096 Mar 27 02:52 second-test-repo.git
```
(I ran a chown on my-test-repo.git)

`chown -R gogs-repositiories` alleviates the issue for existing repos but it doesn't solve for any new ones that are created. I had the same file ownership issue with `.ssh/authorised_keys`.

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

I think it is depends on which user you run Gogs.

**Comment by drew-y** [comment]
I run Gogs using the standard git user on a digitalocean ubuntu 14.04 image. I actually followed this tutorial to get everything setup: https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04

I created the git user from root with ```adduser git``` and gave it sudo privileges with ```adduser git sudo```

**Comment by drew-y** [comment]
Probably should have checked this first thing but apparently gogs is being run by root
```bash
git@git:~$ ps aux | grep gogs
root      3566  0.0  1.7 213292 18296 ?        Sl   12:51   0:03 /home/git/go/src/github.com/gogits/gogs/gogs web
git       4167  0.0  0.0  11744   916 pts/3    S+   15:44   0:00 grep --color=auto gogs
```
The run user is set to git. Shouldn't I have gotten an error?

I'm not certain how this happened. It could have something to do with supervisor.

**Comment by drew-y** [comment]
Ok I figured it out. All I had to do was add the line `user = git` to the supervisor program config.

```bash
[program:gogs]
directory=/home/git/go/src/github.com/gogits/gogs/
command=/home/git/go/src/github.com/gogits/gogs/gogs web
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/gogs/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/gogs/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
user = git
environment = HOME="/home/git", USER="git"
```

**Comment by merqurio** [comment]
Thanks @drew-y, that worked for me too

**Comment by lunny** [comment]
OK.

**Comment by 284247028** [comment]
mark
