### ISSUE TITLE
Fail send activation mail for a new mail adress

### ISSUE THREAD

**Issue by gregaou** [gogits/gogs#1161]
Hi, when i try to add an email for an user,

Gogs says "A new confirmation e-mail has been sent to *****@gmail.com, please check your inbox within the next 3 hours to complete the confirmation process."

But in logs i saw this message :
 `2015/03/27 10:02:32 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: ********@gmail.com, info: UID: 1, send activate email to *********@gmail.com err: mail: missing phrase`

**Comment by Unknwon** [comment]
Hi, thanks your feedback. 

Did you set up your own sender e-mail?

**Comment by gregaou** [comment]
Yes, i use another server for this and i have configure the config file for this. I have previously fix some errors like :

`2015/03/26 16:53:03 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: ********@gmail.com, info: UID: 3, send register mail err: missing port in address ********.com`

`2015/03/27 09:04:48 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: **********@gmail.com, info: UID: 1, send activate email to ***********@gmail.com err: 454 4.7.0 TLS not available due to local problem`

`2015/03/27 09:56:09 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: ************@gmail.com, info: UID: 1, send activate email to *********@gmail.com err: x509: certificate signed by unknown authority`

**Comment by Unknwon** [comment]
> i use another server for this

What so you mean by another server? What is your `[mailer]` section in `custom/conf/app.ini`?

**Comment by gregaou** [comment]
`[mailer]
ENABLED = true
HOST = smtp-server-addr.tld:25
USER = user
PASSWD = password
SKIP_VERIFY = true
`

On server smtp-server-addr.tld, i have configured a postfix server.

**Comment by Unknwon** [comment]
Thanks, did you edit your config in `custom/conf/app.ini` file?

**Comment by gregaou** [comment]
yes

**Comment by Unknwon** [comment]
OK, can you go to `/admin/config` and go down to **Mailer Configuration** see if Gogs reads your config correctly.

**Comment by gregaou** [comment]
All is correct, but i just don't get the password, and i get that :

`Name         Gogs: Go Git Service`

Enabled is check and host and user are the same as config file.

**Comment by Unknwon** [comment]
Hmm... does your password contains special characters like `@#`?

**Comment by gregaou** [comment]
No, but if i try to setup postfix, on gogs server : 
`echo "something" | mailx -s "subject" **********@gmail.com`
is working, so i set this config
```
[mailer]
ENABLED = true
HOST = localhost:25
USER =
PASSWD =
SKIP_VERIFY = true
```

And i got another error : 
` 2015/03/27 11:55:00 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: *********@gmail.com, info: UID: 1, send activate email to *********@gmail.com err: mail: no address `

**Comment by gregaou** [comment]
i have try on another server with fresh install from packager.io and i get the same result as last comment

**Comment by gregaou** [comment]
Same result if i test with smtp.gmail.com:587 and my gmail acount USER PASSWORD

**Comment by Unknwon** [comment]
What do you mean by `Same result`?

**Comment by gregaou** [comment]
`2015/03/27 15:06:32 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: ********@gmail.com, info: UID: 1, send activate email to ***********@gmail.com err: mail: no address`

**Comment by gregaou** [comment]
my error come from package : `net/smtp.go` https://golang.org/src/net/mail/message.go

```
229	func (p *addrParser) parseAddress() (addr *Address, err error) {
230		debug.Printf("parseAddress: %q", *p)
231		p.skipSpace()
232		if p.empty() {
233			return nil, errors.New("mail: no address")
234		}
```

**Comment by gregaou** [comment]
Problem solved, `[mailer]` section just need a FROM= configuration, my bad sorry i didn't saw this

**Comment by gregaou** [comment]
Maybe add this in the QS (http://gogs.io/docs/advanced/configuration_cheat_sheet.html)

**Comment by Unknwon** [comment]
Oops, that's really.... my bad...

**Comment by gregaou** [comment]
Lot of investigations =) But no problems :p

**Comment by lifehome** [comment]
Can you please kindly freaking **bold** that "if not exist that create one custom/conf/app.ini" sentence? I mislooked that like billion times and still I can't understand why we can't use conf/app.ini to modify or edit to use...
