### ISSUE TITLE
500 Internal Error on subrepo

### ISSUE THREAD

**Issue by dvwallin** [gogits/gogs#1164]
If I add a folder to my project which happens to be a git repo of its own and I then commit that gogs will give me a 500 error when trying to reach the repo. I can clone it alright with the ssh -addr but I cannot surf to it with the gogs interface.

**Comment by Unknwon** [comment]
Thanks your feedback, I think this is same to https://github.com/gogits/gogs/issues/1061

**Comment by dvwallin** [comment]
I agree, could well be the same issue.
