### ISSUE TITLE
Mouseover clone url glitch on Gogs version 0.6.0.0319 Beta

### ISSUE THREAD

**Issue by klauern** [gogits/gogs#1168]
I don't know if this is happening to anyone else, but I had this weird mouseover glitch that made it hard to click the "Help" link

[![mouseover UI glitch for clone url](http://img.youtube.com/vi/cZVJYtYGbAM/0.jpg)](http://www.youtube.com/watch?v=cZVJYtYGbAM)

This is on Gogs version 0.6.0.0319 Beta

**Comment by MeltedLux** [comment]
:+1: just tested this.

**Comment by vantt** [comment]
the same to me

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/gogs/gogs

**Comment by Unknwon** [comment]
Close as fixed.
