### ISSUE TITLE
When creating an empty repo, if you don't own it, Quick Start is still visible

### ISSUE THREAD

**Issue by dentmaged** [gogits/gogs#1170]
I'm not too sure if this is intentional but anyway here is an example: https://try.gogs.io/unknwon/bare
Screenshot:

![image](https://cloud.githubusercontent.com/assets/9807038/6883089/071e8a1c-d596-11e4-8218-16579c050a72.png)

**Comment by dentmaged** [comment]
@Unknwon ?

**Comment by dentmaged** [comment]
@Unknwon ?

**Comment by Unknwon** [comment]
Thanks your feedback! It has been added to todo list. :smile:

**Comment by Unknwon** [comment]
Please on https://try.gogs.io/unknwon/bare again!

**Comment by dentmaged** [comment]
@Unknwon Fixed, thanks! Nice seeing you back as well!

**Comment by Unknwon** [comment]
:wink:
