### ISSUE TITLE
function "DisableGravatar" not defined

### ISSUE THREAD

**Issue by pztrn** [gogits/gogs#1172]
After upgrading from 0.5.11 to latest git source I got this error:

https://gist.github.com/pztrn/eaa3a0a4fcc96b12e74f

I'm on fully updated Debian Jessie with go 1.3.3.

**Comment by pztrn** [comment]
I am very sorry, forgot to update dependencies. After `go get -u github.com/gogits/gogs` everything is okay.

**Comment by Unknwon** [comment]
:wink: no problem!
