### ISSUE TITLE
Changing colour of an issue label sets repo_id and num_issues to 0

### ISSUE THREAD

**Issue by misje** [gogits/gogs#1173]
Changing the colour of an issue label makes the label disappear from the label list. Issues with that label will still have a reference to the label (and show the new colour), but it looks like several columns in the *label* database table are incorrectly changed to 0.

gogs version: 0.6.1
git version: 2.1.4 (built from source using golang go1.3.3 linux/386)
database: postgresql 9.3
Debian GNU/Linux 8.0 (jessie) 3.16.0-4-686-pae

**Comment by misje** [comment]
Changing a label's name also seems to cause similar results.

**Comment by fake-name** [comment]
Can confirm this issue, I have some dangling labels now.

**Comment by Unknwon** [comment]
I think this is fixed in the `v0.6.3` release, you can also try on https://try.gogs.io

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
