### ISSUE TITLE
split modules from main project into own project repo

### ISSUE THREAD

**Issue by thoroc** [gogits/gogs#1174]
Hi,

Could the modules be splitted out of the project and into separate repository? I was looking at pocking around with some code located in modules, but it feels a bit tedious getting the whole repo Gogs just for this. And keeping this project more modular could me more support for the modules from outsite the core team.

Regards,

thoroc

**Comment by Unknwon** [comment]
Hi, which module do you indicate specifically?

Actually when a module feels good/stable enough we would make it to another repository, and as you can see all the modules should be able to build without dependency of Gogs, which was the original design of modules.

**Comment by thoroc** [comment]
At that point I was looking at the ldap/social/auth ones. 

I guess I need to read the code a bit more. Sorry for the bother.

**Comment by Unknwon** [comment]
No problem!
