### ISSUE TITLE
register mail err: mail: missing phrase

### ISSUE THREAD

**Issue by m42e** [gogits/gogs#1175]
Hi,

I can't get gogs to send mails. I'm using it on my server and created a new user which works perfectly for sending mail. But goes always logs me the following error message and doesn't send a mail:
```
[asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: user@i*****.com, info: UID: 10, send register mail err: mail: missing phrase
```

**Comment by m42e** [comment]
Ok, I got it I missed the FROM in the Mailer configuration.

**Comment by Unknwon** [comment]
Good to hear it! Sorry about confusion, docs is corrected now.
