### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by wernight** [gogits/gogs#1176]
(may be not best place for this suggestion but didn't find better)

I see Gogs main point vs GitLab (as per your blog) is it's easy install, and lightweight. Those are good points, but along with that there is another that could really well come up as a selling point, that is security. How easy is it to have good security settings, how stable, and how granular.

I'd suggest considering putting those points as focus points as they'd be selling points to me.

**Comment by Unknwon** [comment]
Hi, thanks your suggestion!

But I think right now is not a good time to that because we aren't any form of company yet, and don't have a well trained security team. So we cannot promise on things we cannot do.

Hope you understand!

**Comment by linquize** [comment]
I like a single binary (gogs) and good support for Windows (go).
GitLab requires additional ruby runtime and Ruby libraries may or may not support Windows.

**Comment by wernight** [comment]
@linquize Nowadays I would just run the GitLab Docker which is really simple. However not working on Windows, which is true. And on Mac with manual install or Docker VM.

@Unknwon I understand. Thanks for your consideration.
