### ISSUE TITLE
javascript as the repository language

### ISSUE THREAD

**Issue by zoozalp** [gogits/gogs#1178]
While creating a new repository, gogs asks for the language to setup the gitignore file. However, javascript is not among them.
![screen shot 2015-04-02 at 11 04 14 am](https://cloud.githubusercontent.com/assets/2495246/6960103/0f2b950c-d928-11e4-9316-327fc1d26113.png)

**Comment by iSDP** [comment]
Also missing HTML, CSS, JS, jQuery, MySQL, Perl, Bash, etc

**Comment by dentmaged** [comment]
Objective-C++ anyone?

**Comment by xPaw** [comment]
https://github.com/github/gitignore
This is basically what you want.

**Comment by Aidoboy** [comment]
I just use http://gitignore.io/

**Comment by Nedlinin** [comment]
@zoozalp : if you create a folder at the path gogs\custom\conf\gitignore, you can drop gitignore files within it (simply name them the language.  IE for Java, the file would simply be named Java.  

Restart the gogs binary and you'll find them in the dropdown list.

**Comment by Unknwon** [comment]
Added a big list to Gogs on `master` branch. :tada:
