### ISSUE TITLE
Mouseover new migration owner glitch

### ISSUE THREAD

**Issue by melote** [gogits/gogs#1180]
Can't choose other owner item most of the time when Hover the mouse over the default owner.I don't know if this is happening to anyone else.

Gogs Version: 0.6.1.0325 Beta Go1.4.2

**Comment by melote** [comment]
I am so glad that the issue got response finally :)

**Comment by Unknwon** [comment]
Hmm, hmm, :stuck_out_tongue_closed_eyes: thanks for your patient, now it's on the v0.6.7 todo list.

**Comment by Unknwon** [comment]
Things are better now: https://try.gogs.io/repo/migrate

**Comment by melote** [comment]
OK, the css looks better as well :)

**Comment by Unknwon** [comment]
Close as implemented. :blush:
