### ISSUE TITLE
Error 500 if adding an SSH key with the same name

### ISSUE THREAD

**Issue by JensErat** [gogits/gogs#1188]
When adding an SSH key with the same name as another already existing, a 500 error is displayed and a database error logged:

> [setting.go:353 SettingsSSHKeysPost()] [E] ssh.AddPublicKey: pq: duplicate key value violates unique constraint "UQE_public_key_S"

Expected output: A reasonable error message.

**Comment by Unknwon** [comment]
Not sure what version of Gogs you're using, but the current version does have a user-friendly message.

![image](https://cloud.githubusercontent.com/assets/2946214/8893838/d2183542-33d3-11e5-90ae-51cf81d6ce35.png)

**Comment by Unknwon** [comment]
Closed as implemented. :octocat:
