### ISSUE TITLE
Slack hook is raised if the update hook returns an error

### ISSUE THREAD

**Issue by stumpyfr** [gogits/gogs#1189]
Hi,

I have a custom version of the update hook in my repositories, the goal is to check is the commits are signed with the gpg key of my dev (security, audit, ...).

In the case of the signature is missing or wrong, the hook return an error:

```
echo "*** Missing or bad signature on commit $commit" >&2
exit 1
```

and at the end of the update hook, I still have the original call:

`"/home/digint/gogs/gogs" update $1 $2 $3 --config='/home/digint/gogs/custom/conf/app.ini'`

Did I miss something? I guess the slack hook is raised by the gogs binary with the call at the end of update hook, no? but so why the slack notif is still pushed on the slack server is the update script exited before.

Missed something or I need to make a workaround?

**Comment by stumpyfr** [comment]
And without any update hook, the notifications is still raised to Slack, so not related to the update hook.

But the questions is now, how to block the slack hook if the push/commit if refused?

**Comment by Unknwon** [comment]
> how to block the slack hook if the push/commit if refused

Once the update hook is being called, the hook is been added to the waiting list, so your check process is after the commit action, which may rejected the update of Git repository, but not Gogs database.

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
