### ISSUE TITLE
Organizations can only get Avatars from Gravatar

### ISSUE THREAD

**Issue by Aidoboy** [gogits/gogs#1191]
This means that when Gravatar is disabled, organizations can't have avatars.

**Comment by Sqozz** [comment]
I whould love, if that issue gets fixed as soon as possible :+1:

**Comment by Sqozz** [comment]
I've found a little dirty workaround:
* Login into your server over SSH 
* Goto your gogs installation path
* Goto data/avatars
* Rename the avatar for YOUR useraccount to preserve a backup (the file should be named like your gogs user id)
* Upload the organization image into YOUR useraccount over the gogs web interface
* Rename the new file (with your user id) into the user id of your organization
* Rename the backup back to your userid to get back your personal image
* Set the "use_custom_avatar" value in the table "user" in the gogs database from 0 to 1
* Enjoy your new gravatar-free organization image :+1:

**Comment by nvx** [comment]
+1

**Comment by Unknwon** [comment]
OK, now on `develop` and https://try.gogs.io , you can upload avatar for organizations.

**Comment by Unknwon** [comment]
Close as implemented.
