### ISSUE TITLE
Markdown for headers does nothing

### ISSUE THREAD

**Issue by Aidoboy** [gogits/gogs#1192]
It just shows the hashes instead of making it a header.

**Comment by linquize** [comment]
What is your filename entension? Is it `.md` ?

**Comment by Aidoboy** [comment]
Yes, it was the readme.md file.

**Comment by linquize** [comment]
Could you post the markdown source?

**Comment by Aidoboy** [comment]
It was just `#header`, which should look like this:
#header

**Comment by Aidoboy** [comment]
This issue can be closed.

**Comment by linquize** [comment]
You can close the issue yourself by clicking `Comment and Close`.
