### ISSUE TITLE
Make organization emails non-mandatory

### ISSUE THREAD

**Issue by zekesonxx** [gogits/gogs#1193]
I like making puppet organizations for organizing my repos into projects, and putting in fake emails is annoying and might mess something up down the line.

**Comment by y-ponomarev** [comment]
+1

**Comment by dentmaged** [comment]
+1

**Comment by srvg** [comment]
+1

**Comment by tszym** [comment]
+1

**Comment by Sqozz** [comment]
+1

**Comment by Daraku** [comment]
+1

**Comment by Techcable** [comment]
+1

**Comment by Mr-Berna** [comment]
Or maybe just allow organization emails to be duplicate emails. Let me put in my developer email address for more than one organization.

**Comment by Techcable** [comment]
@Mr-Berna 
That would be fine too,.

**Comment by linquize** [comment]
In current DB schema, `user.email` column is mandatory (not null).

**Comment by Unknwon** [comment]
@Mr-Berna it is possible in current version(and some versions early)

**Comment by de-live-gdev** [comment]
@Unknwon Are you sure that its possible in the current version? I am currently on beta/(dev branch) and it's not possible there

**Comment by Unknwon** [comment]
@de-live-gdev oh yes, you're right, I forgot it's possible to same email for 1 user and 1 org.

**Comment by Unknwon** [comment]
Now on `develop` and https://try.gogs.io , `e-mail` for organization is no longer needed.

**Comment by Unknwon** [comment]
Close as implemented.
