### ISSUE TITLE
Add centos 7 build to packager.io

### ISSUE THREAD

**Issue by mr-tron** [gogits/gogs#1196]
subj

**Comment by flotho** [comment]
yes good idea.
Additionnally I used the centos6 packages and it runs perfectly on centos7

**Comment by crohr** [comment]
@mr-tron centos7 and debian8 are coming this week on [Packager.io](https://packager.io)

**Comment by brandonsturgeon** [comment]
@crohr Any update on the Centos7? Only seeing Centos6 releases on Packager.io , gunna give one of them a try.

**Comment by Unknwon** [comment]
Looks like packager.io has Centos 7 now: https://packager.io/gh/pkgr/gogs
