### ISSUE TITLE
API docs and migration script 

### ISSUE THREAD

**Issue by hardikdangar** [gogits/gogs#1197]
Hey,

I wanted to say really awesome work on this project to entire team of gogs. really love the simplicity and lean binary of gogs :+1: 

One glitch though I couldn't find any information about API's available and how to call them except migration API. After diggin around i was able to find searching user API.

Now what i want to do is create a migration script for users who are coming from gitlab and for that i have already created hefty little script in php which uses API calls to create new repos.

What i essentially want is feature in API to create users. That would make any migration scenario simple. So my question is, is there an easy way to enhance API code to create new user in the system? I would love to write code about this. any pointers on where should i focus my lens? Is there any system code already available that i can write an API function and call ?

If i can't add a code to API is there a way i could add this code to scripts folder or some kind of module or something so people can just download my code and migrate there projects easily?

I would also love to write some sort of API docs for the project. but not sure where should i look to add help docs.

**Comment by Unknwon** [comment]
Hi @hardikdangar , 

it's been a while and not sure if you're still interested in doing this.

If you're, I think the keep those scripts in a repository and we can add a link to your repository in the README/Gogs docs should be the best way to do it.

Best regards,

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
