### ISSUE TITLE
start.sh script missing

### ISSUE THREAD

**Issue by vaz-ar** [gogits/gogs#1198]
release 0.6.1

the scripts/start.sh script is missing in the 0.6.1 version, causing gogs_supervisord.sh to be unable to start gogs.

It was removed via the commit 6c84223f4305784fd0d13708f623c785d48221e5

**Comment by hardikdangar** [comment]
I think you are confused about how you can start gogs. I believe you have downloaded gogs binary. you can start gogs server by going to your installation directory and running 
$ ./gogs web

Let me know if that works.

**Comment by vaz-ar** [comment]
Thank you for you response.

I already knew that It can be started like that, and it works, but in order to use gogs_supervisord.sh to start/stop/restart gogs (as detailled on this page http://gogs.io/docs/installation/configuration_and_run.md), you need the start.sh script.

use case: starting gogs at reboot from the crontab

**Comment by hardikdangar** [comment]
oh man sorry for that.

I would suggest install supervisor as init.d somehow doesn't worked for me. to do that,

sudo apt-get -y install supervisor

and edit its file via

sudo nano /etc/supervisor/supervisord.conf


[program:gogs]
directory=/home/git/go/src/github.com/gogits/gogs/
command=/home/git/go/src/github.com/gogits/gogs/gogs web
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/gogs/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/gogs/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
environment = HOME="/home/git", USER="git"

change directory's to match your installation and user to your git user. and restart the supervisor via,
sudo service supervisor restart

that's all you need to make gogs start automatically on boot.

**Comment by vaz-ar** [comment]
Yes I did something like that to make it work, thanks.

I was mainly reporting the issue because the documentation suggest to use this method to control the process. Maybe the documentation should be updated to reflect the changes ?

**Comment by hardikdangar** [comment]
Yeah. I see issues like that with documentation. lot of outdated documentation. infect i have asked for help on this as i wanted to improve it.

**Comment by faddei** [comment]
``program:gogs]
directory=/home/git/go/src/github.com/gogits/gogs/
command=/home/git/go/src/github.com/gogits/gogs/gogs web
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/gogs/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/gogs/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
environment = HOME="/home/git", USER="git",**PATH="/usr/local/git/bin"**
