### ISSUE TITLE
Starting the debian gogs package produces a panic

### ISSUE THREAD

**Issue by Sqozz** [gogits/gogs#1200]
Hi all!

I've tried to install gogs on a debian 7 system.
Adding the packager.io repos and installing gogs was fine.
But when i want to start gogs, it produces a panic (plain configuration):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x637f0d]

goroutine 1 [running]:
gopkg.in/ini%2ev1.(*Key).String(0xc20815be80, 0x0, 0x0)
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/gopkg.in/ini.v1/ini.go:142 +0x27d
gopkg.in/ini%2ev1.(*Key).MustString(0xc20815be80, 0xd2ca10, 0x16, 0x0, 0x0)
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/gopkg.in/ini.v1/ini.go:194 +0x3a
github.com/gogits/gogs/modules/setting.NewConfigContext()
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/setting/setting.go:211 +0x995
github.com/gogits/gogs/routers.GlobalInit()
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/gogits/gogs/routers/install.go:53 +0x27
github.com/gogits/gogs/cmd.runWeb(0xc2081542a0)
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/gogits/gogs/cmd/web.go:182 +0xb4
github.com/codegangsta/cli.Command.Run(0xcafeb0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd0f310, 0x15, 0xde3a70, ...)
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208162000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/main/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2080415c0)
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /tmp/d20150331-14-q6acap/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 6 [runnable]:
text/template/parse.lexText(0xc20805cf00, 0xe46558)
        /usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20805cf00)
        /usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:191 +0x1ac
```

hope you can help

**Comment by hardikdangar** [comment]
Would you provide with more information like,

what is your installation directory?
what user have you used ?
how you are trying to start gogs?

**Comment by Sqozz** [comment]
hi,
sorry i was a little bit in hurry..
the installation folder is /opt/gogs (the default after an apt-get install gogs)
i used root to start it with "/etc/init.d/gogs start"

**Comment by Sqozz** [comment]
Okay. First issue was a wrong "ROOT_URL".
I wrote "ROOT_URL = https://%(domain)s"
instead of "ROOT_URL = https://%(DOMAIN)s".
Now gogs complains, that he doesn't know "mysql" as provider:

My config:
```
[database]
; Either "mysql", "postgres" or "sqlite3", it's your choice
DB_TYPE = mysql
```


 The output:
panic: session: unknown provider 'mysql'(forgotten import?)

**Comment by hardikdangar** [comment]
not sure what's the issue with mysql but just to confirm have you install mysql-server? 

I would prefer using latest binary version. as it's just download binary zip and unzip and run "gogs web" which works on most debian flavours without any issues.

**Comment by Sqozz** [comment]
I've figured out, that the unknown provider error comes from the PROVIDER option in the [sessions]-section.
Since gogs is now running, i'll close this issue. But it whould be nice, if these errors get caught somewhere, so that the admin knows whats wrong with his config file.

**Comment by Unknwon** [comment]
Hi @Sqozz , would you mind to post the wrong config about 

> PROVIDER option in the [sessions]-section.

So that I can test on and maybe there is a way to add more user-friendly message?

Best regards,
