### ISSUE TITLE
 only Quick Guide is shown, instead of source files

### ISSUE THREAD

**Issue by GaryHost** [gogits/gogs#1201]
The #418 is closed, but not solved. You create a repository, commits code, it works fine, but when you try to visualize the sources, it shows only the Quick Guide.

**Comment by Unknwon** [comment]
Thanks your feedback, what is version of Gogs?

**Comment by GaryHost** [comment]
Hi,

Sorry for the delay.

I'm using V0.6.1.0325 Beta.

Thanks,

**Comment by Unknwon** [comment]
@GaryHost your problem was caused by unsuccessful push operation, you can change database table field `is_bare` to `0` and Gogs will show you repo files.

**Comment by GaryHost** [comment]
Allright, It works now. So an unsuccessful push operation caused that ? Does it mean that each time that an unsuccessfull push will happen, i will have to change the mysql column by hand ?

Thanks very much for your help.

**Comment by Unknwon** [comment]
> Does it mean that each time that an unsuccessfull push will happen, i will have to change the mysql column by hand ?

`unsuccessfull` already indicates that operation is failed, so I think this is reasonable. And only if your repo was created as `bare` repo, repo created with initial commit or has been pushed some commits will not meet this issue.

**Comment by COLABORATI** [comment]
I have got the same issue, what kind of feedback can help? I see nothing of relevance in the logs. 
I can push to the repos (without errors) and clone from the repos, files are there. 
#1762 applies here too, maybe there is some connection to this error.

**Comment by Unknwon** [comment]
@COLABORATI What is the command and SSH URL you use for pushing?

I think you made something fundamentally wrong.

**Comment by COLABORATI** [comment]
I now understood this issue - if there was just a *little* but more documentation it would be much easier. 
Please add to the 'new repo' page some description about what actually happens: that if no template files are generated then a BARE repo is created - this bare repo will never show files, even if pushed to the repo. There is so much space on that html page - and one sentence about this can really help not to waste endless hours. 

Now only that annoying #1762 keeps me from being happy...

**Comment by Unknwon** [comment]
> I now understood this issue - if there was just a little but more documentation it would be much easier. 
Please add to the 'new repo' page some description about what actually happens: that if no template files are generated then a BARE repo is created - this bare repo will never show files, even if pushed to the repo. There is so much space on that html page - and one sentence about this can really help not to waste endless hours.

Because it is simply not true.

**Comment by Unknwon** [comment]
If you successfully triggered commit event of Gogs, it will create an action about push: `xx pushed xx to xxx` on dashboard. And it set `is_bare` field to `false` in database.

**Comment by COLABORATI** [comment]
Hmm, then it must be a bug. I successfully pushed (and can clone from that repo with all files), but the is_bare field is not changed. However, it works with the little workaround to populate the initial repo with some files, then there are no problems.

**Comment by Unknwon** [comment]
Yeah, but you're still not answering my question which blocks me from helping you:

> What is the command and SSH URL you use for pushing?

**Comment by RichieB2B** [comment]
I just ran into the same issue using Gogs 0.9.99.0903 (on CentOS 6, installed using RPM). After creating a bare repo and a successful push Gogs is still showing the Quick Guide. Commands used were:
```
git remote add origin gogs@myserver:user/TEST.git
git push -u origin master
```
