### ISSUE TITLE
bundle jquery with gogs

### ISSUE THREAD

**Issue by robinpaulson** [gogits/gogs#1203]
fetching it from jquery is slow, and unnecessary, the file is only a few kilobytes. it also alerts jquery to me using the file, which is again not necessary

**Comment by linquize** [comment]
gogs ships the javascript libraries, but by default, it links to CDN servers.
To link to offline javascript files, set `custom/conf/app.ini`

    [server]
      OFFLINE_MODE = true

`OFFLINE_MODE` default value is `false`

**Comment by Nedlinin** [comment]
What all does OFFLINE_MODE do?  Perhaps it'd be smart to simply rename the config options to "USE_OFFLINE_SCRIPTS" or similar.  When I see OFFLINE_MODE I think "localhost only" or similar.

**Comment by Unknwon** [comment]
@Nedlinin http://gogs.io/docs/advanced/configuration_cheat_sheet#server has things explained, but good suggestion, thanks!

**Comment by FSMaxB** [comment]
OFFLINE_MODE doesn't really solve this because it also turns of Gravatar which requires accessing third party servers. So there's no way to disable loading jquery from external servers and still have Gravatar enabled.

**Comment by linquize** [comment]
See https://github.com/go-gitea/gitea/issues/20

**Comment by robinpaulson** [comment]
Honestly, I'm as keen to disable remote Gravatar as I am remote jquery - their tracking and data mining stinks and is completely unnecessary. But, perhaps we could have them in different config options, so they can be set independently?

**Comment by Unknwon** [comment]
@robinpaulson yeah, that's some users want and how gitea implemented.

**Comment by Unknwon** [comment]
To make things simple, starting now on `develop`, no more CDN requests from Gogs, all scripts are served locally. 

You can check this behavior also on https://try.gogs.io/

**Comment by Unknwon** [comment]
Closed as implemented. :tada:
