### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by sh4nks** [gogits/gogs#1205]
Hey! 
First of all, great work! 

Is it possible to change the landing page? So, when a user is not logged in he sees the page with all this information (which is great) but it would be also cool to just have the login or registration formular there instead. As far as I can see it is not possible via settings to change it - do you have any plans on making this customizeable (if possible)?

Cheers!

**Comment by matt-h** [comment]
If you set REQUIRE_SIGNIN_VIEW to true in the ini, users only get the login page before they login.

**Comment by sh4nks** [comment]
But does this mean they are no longer able to see "Explore" if they are not logged in? I would like to route them to "/explore". I actually tried it with nginx but then the Dashboard for logged in users is no longer available (because they always get redirected to /explore).

**Comment by matt-h** [comment]
Ahh, yes it does. I thought that is what you meant.
You could check for the login cookie in nginx and redirect if not set.

**Comment by sh4nks** [comment]
How do you that? I just found the cookies if the "Remember Me" thing is ticked. The other cookies are always present (``_csrf``, ``i_like_gogits`` and ``lang``) even when I am logged out. If "Remember Me" is checked I have "gogs_awesome" and "gogs_incredible".

**Comment by matt-h** [comment]
Looks like that won't work. I thought `gogs_awesome` was available when you were logged in, but it looks like it is only when Remember Me is checked.

**Comment by sh4nks** [comment]
Anyway, thanks for your help! I am leaving this open in case someone has a solution to this.

**Comment by klingtnet** [comment]
@sh4nks 
You don't need to configure nginx to show the **explore** as landing page. Instead you can use the `LANDING_PAGE` setting in the `[Server]` of your `app.ini`:

```ini
[Server]
LANDING_PAGE = explore
...
```

**Comment by sh4nks** [comment]
Thanks!
okay, now I am feeling a bit stupid that I haven't seen it..
