### ISSUE TITLE
Forking an empty repo results in 500 error

### ISSUE THREAD

**Issue by StrangeWill** [gogits/gogs#1206]
Gogs:  0.6.1.0325 Beta

Steps to reproduce:

* Create new repo in an organization
* Fork said empty repo
* Bam, 500 error.

Error in gog.log:

2015/04/15 01:14:14 [repo.go:330 funcÂ·008()] [E] GetBranches:

Was preparing a repo, wanted to push my code to my fork then pull request into the org. Not sure if this workflow makes sense, but either way should be handled better than a 500 error. I can see the empty repo fine on the organization though.

**Comment by coffin5257** [comment]
I have the issue too.

**Comment by LeDistordu** [comment]
+1

**Comment by LeDistordu** [comment]
how i delete my forked repo with this error 500 ?

**Comment by DmitrySkripunov** [comment]
+1. I have same question!

**Comment by Unknwon** [comment]
Hmm... hi @StrangeWill by 

> Create new repo in an organization

Is this repository is empty when creation?

Because bare seems no button/UI lets you fork on it?

**Comment by StrangeWill** [comment]
@Unknwon Click on "settings", the UI element to fork will be rendered and you can fork from there.

**Comment by Unknwon** [comment]
@StrangeWill this helps, thanks!

**Comment by Unknwon** [comment]
Right now Gogs disallow you fork a bare repo. You can test on https://try.gogs.io

**Comment by StrangeWill** [comment]
Attempted to hard-fork by going to https://try.gogs.io/repo/fork/[Repo ID] and I get a 404, awesome.

**Comment by Unknwon** [comment]
Thanks your confirmation!
