### ISSUE TITLE
Bad LDAP Filter Breaks Gogs

### ISSUE THREAD

**Issue by StrangeWill** [gogits/gogs#1207]
An LDAP filter doing something dumb like including all objects (oops), results in creating users with blank user names. You'll get authed as this blank user account, and can create repos and wreck all sorts of havock.

This pretty much breaks everything in Gogs, in a really bad way, you can't delete these repos from the UI (404 errors trying to access them) due to the invalid path that is given due to the lack of a user name, I didn't notice any issues on the filesystem caused by this but it makes me paranoid.

Mainly under no condition should Gogs ever accept a blank user name, including over LDAP.

**Comment by Unknwon** [comment]
Closed by #1218
