### ISSUE TITLE
Gogs creates "LICENSE" and ".gitignore" with the executable permission

### ISSUE THREAD

**Issue by xaionaro** [gogits/gogs#1208]
If I choose and LICENSE and .gitignore while creating a repository, Gogs creates this:

    drwxr-xr-x 512 xaionaro xaionaro 108K Apr 15 12:40 ..
    -rwxr-xr-x   1 xaionaro xaionaro 1.5K Apr 15 12:40 LICENSE
    -rwxr-xr-x   1 xaionaro xaionaro  143 Apr 15 12:40 .gitignore
    drwxr-xr-x   3 xaionaro xaionaro 4.0K Apr 15 12:40 .
    drwxr-xr-x   8 xaionaro xaionaro 4.0K Apr 15 12:40 .git

LICENSE and .gitignore should _not_ be executable.

**Comment by xaionaro** [comment]
Seems to be a problem in this code:

https://github.com/gogits/gogs/blob/639e34e362c3e4cea2532de4b811dc8bb916f9f3/models/repo.go#L483

**Comment by linquize** [comment]
https://github.com/Unknwon/com/blob/c672f81f814bd7f81ac92957c615a2b345e48d2d/file.go#L127
should write 0644

**Comment by Unknwon** [comment]
Hi, fixed code has been pushed `master`, thanks your feedback!
