### ISSUE TITLE
Repo naming inconsistency

### ISSUE THREAD

**Issue by martinnix** [gogits/gogs#1213]
Repos created or mirrored have there name stripped of case (ie always converted to lower case) on the filesystem.

Accessing the repo over https causes no issue as gogs handles the conversion between case but if you use SSH to say clone a repo you have to refer to it by its lower case name causing confusion. This is inconsistent with the UI

**Comment by michaelPf85** [comment]
It also breaks mirroring ! I'm mirroring one of the Mantis BugTracker plugins and the gogs.log gives me this :
2015/08/24 04:52:48 [session.go:933 Iterate()] [E] Fail to update mirror repository(/var/lib/git/gogs-repositories/externe/mantisbt-plugins-EmailReporting.git): chdir /var/lib/git/gogs-repositories/externe/mantisbt-plugins-EmailReporting.git: no such file or directory

The folder is named  mantisbt-plugins-emailreporting.git.

**Comment by Unknwon** [comment]
Hi @martinnix , I believe Gogs handles conversion to lower case in the latest version.

@martinnix Thanks your report! Hasn't met this issue before, I'll test one with mixed cases and see what can be done to fix it. :sunny:

**Comment by michaelPf85** [comment]
I'm installing from binary on CentOS and the latest available version is 0.6.5, the issue is still there. I'll try 0.6.6 or .7 when they become available.

**Comment by Unknwon** [comment]
Oops... didn't notice I @ same person twice....:scream:

Yes, @michaelPf85 the mirror issue hasn't been fixed.

**Comment by michaelPf85** [comment]
@Unknwon  Ok ! Tell me if I should file another issue. I just came back from a vacation and noticed some problems with the Gogs installation I was testing before leaving :)

**Comment by Unknwon** [comment]
It's OK to keep trace on this issue as the mirror problem is also caused by `Repo naming inconsistency` :smile:

**Comment by Unknwon** [comment]
Hi @michaelPf85 I've checked that it's still there in v0.6.5: https://github.com/gogits/gogs/blob/v0.6.5/models/repo.go#L1133

But has been fixed somehow while I was working on something else: https://github.com/gogits/gogs/blob/master/models/repo.go#L1194

**Comment by Unknwon** [comment]
Close as implemented. :tada:

**Comment by michaelPf85** [comment]
Looks good, though I've never compiled a Go app, so I'll test it when released.

**Comment by Unknwon** [comment]
@michaelPf85 no problem :)
