### ISSUE TITLE
gobuild.io links to a chinese toy company

### ISSUE THREAD

**Issue by sjums** [gogits/gogs#1214]
The guide here http://gogs.io/docs/installation/install_gogs_on_ubuntu.html reference certain resources. Those resources are obviously not there to find.

**Comment by lunny** [comment]
Gobuild.io now is down. we are connecting the mantainer to resolve this issue. And you can download the source and compile it your self at the moment.

**Comment by Unknwon** [comment]
It's sad but gobuild.io is no longer running....
