### ISSUE TITLE
404 errors when terminating SSL at web proxy (lighttpd)

### ISSUE THREAD

**Issue by adamierymenko** [gogits/gogs#1219]
I'm trying to place Gogs behind lighttpd, and I don't think it is respecting ROOT_URL. I have:

    [server]
    ROOT_URL = https://www.zerotier.com/gogs/
    PROTOCOL = http
    DISABLE_SSH = true
    DOMAIN = zerotier.com
    HTTP_ADDR = 127.0.0.1
    HTTP_PORT = 3000
    OFFLINE_MODE = true

Going to https://www.zerotier.com/gogs/ generates a lot of:

    [Macaron] Started GET /gogs/ for 184.177.20.169
    2015/04/20 19:59:36 [home.go:179 Profile()] [E] GetUserByName: User does not exist
    [Macaron] Completed /gogs/ 404 Not Found in 2.239694ms
    [Macaron] Started GET /gogs/ng/css/magnific-popup.css for 184.177.20.169
    [Macaron] Completed /gogs/ng/css/magnific-popup.css 404 Not Found in 4.262942ms
    ... and so on

I don't think it's respecting www.zerotier.com/gogs as the path or making URLs relative properly. I'm running 0.6.1, and found a few similar issues but they all seem closed. Nothing seems to work.

Anyone able to proxy this correctly?

**Comment by matt-h** [comment]
It looks like it isn't passing the modified url with /gogs/ stripped in your proxy. What do you have for your proxy settings?

In nginx it is:
```
location /gogs/ {
    proxy_pass http://localhost:3000/;
}
```

I'm not really familiar with lighttpd, but from what I gather from the documentation: http://redmine.lighttpd.net/projects/1/wiki/Docs_ModProxyCore
Something like this should work.
```
server.modules  += ( "mod_proxy_backend_http" )
$HTTP["url"] =~ "^/gogs" {
        proxy-core.protocol = "http"
        proxy-core.backends = ( "localhost:3000" )
        proxy-core.rewrite-request = (
          "_uri" => ( "^/gogs/?(.*)" => "/$1" ),
          "Host" => ( ".*" => "localhost:3000" ),
        )
}
```

**Comment by adamierymenko** [comment]
Ahh... it has to be stripped. Docs aren't entirely clear on that. Thanks.

**Comment by Unknwon** [comment]
@matt-h thanks for the help!

**Comment by mckaygerhard** [comment]
the provided settings on documentations for lighttpd its only for 1.5.X version, and for 1.4.X does not work!
