### ISSUE TITLE
Does not allow anonymous clone over SSH

### ISSUE THREAD

**Issue by lnyk** [gogits/gogs#1222]
gogs: 0.6.1.0325 Beta Linux x64 Binary
system: ubuntu 14.04

use nginx to "proxy_bypass"
nginx user: www www

use supervisor
supervisor set to run gogs as user: git

gogs RUN_USER = git

git user password deleted (# passwd -d git)
git user shell: /bin/bash

chown everything in /home/git/ to git:git

The problem is:
ssh with key clone/pull/push all OK
http with username/password all OK
but when I clear my .ssh directory and clone via SSH as anonymous (without any permissions but just clone like github), I got password asking and been denied.

/home/git/.ssh/authorized_keys contains only one correct pub-key added by gogs web myself.

I found a .gitconfig file under /home/git:
[user]
        name = Gogs
        email = gogs@fake.local
[core]
        quotepath = false

does that matter?

I've closed User Registration and Hide Register Button
does that matter?

I know it may not be a bug, but I got nowhere but here for asking, and I'm searching solutions the whole day
anything can be helpful guys~

**Comment by matt-h** [comment]
It seems this is either a bug or a feature request.

Gogs does not currently allow anonymous clone over SSH even with public repositories. It requires public key authentication of any user to clone over SSH.

**Comment by lnyk** [comment]
Indeed... Just my guess...
Thanks very much bro~

and another questiong please:
1. I'v set a repo to be private, but I can still clone via HTTP with knowing its URL, can I control that?
2. Just cloned a test repo via HTTP anonymously, but I found I can push! I really need help now....

**Comment by okket** [comment]
Known problems, see https://github.com/gogits/gogs/issues/1128 and https://github.com/gogits/gogs/issues/1127

**Comment by okket** [comment]
I deal with these problems by putting Gogs behind a reverse SSL proxy that requires separate authentication.

**Comment by lnyk** [comment]
Got it!

Thanks My Friends!!!!!!!!!!!!!!

I think I should be waiting for 0.6.2 release... My server is in the public network....

**Comment by Unknwon** [comment]
Should be fixed once you add your SSH key, you can clone other public repos.
