### ISSUE TITLE
Error when using `#` in database password

### ISSUE THREAD

**Issue by jsenjoy** [gogits/gogs#1225]
I use `#` in my database password, first time installing is ok, but fail to setup next time because `gopkg.in/ini.v1` treat `#` as comments, then of cause password is wrong. Maybe give a notice when enter database password to install program or other better ways?

**Comment by Unknwon** [comment]
Actually you can edit it in the config file like:

```ini
PASSWORD= `my#password`
```

**Comment by Unknwon** [comment]
Updated `gopkg.in/ini.v1` package to add quotes around value with it contains `#`.

**Comment by jsenjoy** [comment]
:+1:

**Comment by Unknwon** [comment]
Closed as implemented. :octocat:
