### ISSUE TITLE
Repository name in URL doesn't link to the URL with .git appended

### ISSUE THREAD

**Issue by spideynn** [gogits/gogs#1227]
When I try to access my repository from some applications, it links to `http://localhost:3000/spideynn/example.git` which doesn't exist, but `http://localhost:3000/spideynn/example` exists.

**Comment by robinpaulson** [comment]
Could this be fixed with an apache (or whatever) mod_rewrite rule dropped in /etc/apache2/conf.d/ by the install package? So, going to the first link redirects to the second?

**Comment by spideynn** [comment]
Forgot to mention I'm running this with the .exe on Windows

**Comment by Unknwon** [comment]
Hi there, fixed code has been pushed to `master` can you can also test on https://try.gogs.io/unknwon/gogs.git

**Comment by spideynn** [comment]
@Unknwon  It works, thanks!

**Comment by Unknwon** [comment]
No problem!
