### ISSUE TITLE
Gogs Very Cool !!!

### ISSUE THREAD

**Issue by jniltinho** [gogits/gogs#1228]
Gogs run in my Project (SPAMD), manager Private GIT Web Repos.

Fast and Simple
Ubuntu 14.04 32Bits + Gogs + Nginx frontend.
Drop GITLAB.
:100: 
:+1: 

My Project: https://github.com/revel/revel/issues/917#issuecomment-88620648
http://demo.spamd.com.br

Soon I will contribute to the project with the installation and configuration howtos

My personal blog: http://linuxpro.com.br

**Comment by lunny** [comment]
I'm happy you like Gogs. Your project looks very nice.

**Comment by eaigner** [comment]
@jniltinho how is this an issue? /close

**Comment by Unknwon** [comment]
Glad you like it! But right now I'm going to close this issue. :beer:
