### ISSUE TITLE
Label disappeared after mange and save it.

### ISSUE THREAD

**Issue by nadoo** [gogits/gogs#1229]
both on my own deployment and on https://try.gogs.io.

**Comment by nadoo** [comment]
Version: 0.6.1.0325 Beta

**Comment by WimpyMan** [comment]
We have the same problem here on our on-premises setup

**Comment by flomine** [comment]
seems related to #542

**Comment by flomine** [comment]
Then we cannot see the label anymore in the label panel but this label remains on previously labelled issues. We can't change it anymore even if this label seems to still exist somewhere

**Comment by Unknwon** [comment]
Duplicated to #542 and has been fixed. Thanks your feedback!
