### ISSUE TITLE
mirror repo which sync failed will show the user password in plaintext

### ISSUE THREAD

**Issue by laofo** [gogits/gogs#123]
If the mirror repo sync failed, the gogs server will print the log in the server side. However, gogs should not pint the user and the passowrd in plaintext.

>2014/04/25 01:24:14 [repo.go:172] [E] repo.MirrorUpdate: fatal: unable to access 'https://user:password@github.com/gogits/gogs.git/': Failed to connect to github.com port 443: Connection refused
>error: Could not fetch origin

**Comment by Unknwon** [comment]
This is somewhat fixed...
