### ISSUE TITLE
Gogs CI

### ISSUE THREAD

**Issue by Cysioland** [gogits/gogs#1232]
Okay, so maybe this is kinda high demand.

We already have a great, light and efficient Git service written in Go, Gogs. But we don't have a great, light and efficient CI solution, easily integrated with Gogs. Maybe you could incorporate this plan into your roadmap?

**Comment by vtolstov** [comment]
Use drone.io it have integration with gogs
24 апр. 2015 г. 23:08 пользователь "Cysioland" <notifications@github.com>
написал:

**Comment by lunny** [comment]
drone.io +1

**Comment by Cysioland** [comment]
@vtolstov @lunny But that's not a self-hosted solution, and you need to pay the guys at drone.io for it.

**Comment by vtolstov** [comment]
You not right,drone is the self hosted.
26 апр. 2015 г. 12:21 пользователь "Cysioland" <notifications@github.com>
написал:

**Comment by mcheng89** [comment]
+1 for drone

**Comment by XVilka** [comment]
Just for the reference - drone github repository https://github.com/drone/drone

And :+1: for the better integration from the gogs side.

**Comment by mgracer48** [comment]
+100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000100001000010000

**Comment by cusspvz** [comment]
Does drone mark commits as valid/invalid? I've set it up with gogs but i cannot see those kind of checks.

**Comment by Unknwon** [comment]
I'm closing this as I prefer use Gogs + Drone.io so everyone can work on things they are good at.

**Comment by jpic** [comment]
Sorry for necro bumping, but anybody here got drone to work with pull requests ?

Documentation mentions that it doesn't support merge requests on gogs: http://readme.drone.io/setup/remotes/gogs/

How do drone+gogs users here deal with this ?

**Comment by Unknwon** [comment]
@jpic best couple :)

**Comment by jpic** [comment]
I see, I guess we'll go for a quick'n'dirty python script that sets labels on PRs and pastes build links in comments for now. Thanks for your feedback !

**Comment by bkcsoft** [comment]
I think that the biggest issue is that Gogs currently doesn't shoot
webhooks for PRs (AFAIK), if this is implemented then we can have
drone-builds on PRs :wink:

**Comment by strk** [comment]
Webhooks for PR landed in Augost 2016, via commit 3f7f4852efaaa56a0dada832dc652a1fc8869ae7 (see #2246)

**Comment by HelloEdit** [comment]
Hello,
sorry to relaunch the debate, but Drone.io is NOT available on ARM platforms, conclusion: we can not have a Gogs + Drone.io solution on the same Rpi, and that's really sad

**Comment by strk** [comment]
Jenkins does have a plugin for Gogs (and one for Gitea)
Dunno if that helps your case.

**Comment by HelloEdit** [comment]
Thank you very much for your advice, but Gogs is thought to work with Git, it would be a shame not to enjoy it :)
For now, we will say that we do not need """test""" 😄

Thanks,

**Comment by strk** [comment]
I don't understand your observation. Jenkins is a CI application, like Drone. It is able to fetch code from Git as well...

**Comment by HelloEdit** [comment]
Oh I'm sorry, I did not quite understand ... But yes, Jenkins could do the trick, I would just have to look if he does not consume too much in resource 👍 
Thank
