### ISSUE TITLE
Navbar UI doesn't match rest of the site

### ISSUE THREAD

**Issue by spideynn** [gogits/gogs#1235]
For example, the navbar UI for https://try.gogs.io/spideynn/Test/issues is different than the rest of the site.

**Comment by linquize** [comment]
gogs issues still using the old theme
The rest pieces of the software are using the new theme (`ng` folder)

**Comment by spideynn** [comment]
I was confused as to why that was happening, thanks!

**Comment by lunny** [comment]
@fuxiaohei I think we can resolve this issue first! @Unknwon
