### ISSUE TITLE
How to transform local user into ldap users?

### ISSUE THREAD

**Issue by flotho** [gogits/gogs#1237]
Hy,

I have local users that have been created waiting a correct ldap conf from my side.
From now I succeed having ldap new users. Is it possible to transform the old local one to new ldap ones?
regards

**Comment by lunny** [comment]
Just Edit user on your admin ui and change user's type from local to one of your ldap auth source.

**Comment by flotho** [comment]
hy,

unfortunately, it doesn't work

**Comment by Unknwon** [comment]
It it now possible on `develop` branch!

**Comment by Unknwon** [comment]
Close as fixed.
