### ISSUE TITLE
Crash when connect to LDAP with SSL

### ISSUE THREAD

**Issue by xujinzheng** [gogits/gogs#1238]
linux 14.04.2 amd64 release v0.6.1

panic 内容如下

[Macaron] Started POST /user/login for 123.118.11.224
panic: runtime error: index out of range

goroutine 1938 [running]:
github.com/gogits/gogs/modules/ldap.(*Conn).reader(0xc208bd5600)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/ldap/conn.go:267 +0x30f
created by github.com/gogits/gogs/modules/ldap.(*Conn).start
	/home/wuwen/go/src/github.com/gogits/gogs/modules/ldap/conn.go:83 +0x32

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc20816de90, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20816de90, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20816de30, 0x0, 0x7f28c10427c0, 0xc2083e83e0)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2084bbc40, 0x6e2b2e, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2084bbc40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20886f860, 0x7f28c105a758, 0xc2084bbc40, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20886f860, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc208279c10, 0xc, 0x7f28c105a6f8, 0xc20806c0e0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1808 +0xba
github.com/gogits/gogs/cmd.runWeb(0xc2080e20e0)
	/home/wuwen/go/src/github.com/gogits/gogs/cmd/web.go:490 +0x21da
github.com/codegangsta/cli.Command.Run(0xde4150, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe466d0, 0x15, 0xf2e730, ...)
	/home/wuwen/go/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208090000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/home/wuwen/go/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
	/home/wuwen/go/src/github.com/gogits/gogs/gogs.go:40 +0x367

goroutine 5 [runnable]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2080395c0)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/home/wuwen/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 17 [chan receive, 4 minutes]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
	/home/wuwen/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:53 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
	/home/wuwen/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:47 +0xea

goroutine 18 [runnable]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20819a100)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/home/wuwen/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 35 [select, 4 minutes]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20819b6c0)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/home/wuwen/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 34 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc20815d800)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/cron/cron.go:162 +0xa65
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
	/home/wuwen/go/src/github.com/gogits/gogs/modules/cron/cron.go:137 +0x3d

goroutine 33 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc20820a500)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 49 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 1905 [runnable]:
sync.(*Mutex).Lock(0xc208bd5668)
	/usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(*Once).Do(0xc208bd5668, 0xc208ec98f0)
	/usr/local/go/src/sync/once.go:40 +0x65
github.com/gogits/gogs/modules/ldap.(*Conn).Close(0xc208bd5600)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/ldap/conn.go:106 +0x54
github.com/gogits/gogs/modules/auth/ldap.Ldapsource.SearchEntry(0xc2083e92c0, 0x4, 0xc2083e9300, 0xe, 0x298c, 0x0, 0xc2083e9320, 0xf, 0xc2083e92c9, 0x3, ...)
	/home/wuwen/go/src/github.com/gogits/gogs/modules/auth/ldap/ldap.go:71 +0x61a
github.com/gogits/gogs/models.LoginUserLdapSource(0x0, 0xc208d631d6, 0xa, 0xc208425728, 0x8, 0x1, 0xc2082ca420, 0x1, 0xc20854abde, 0x0, ...)
	/home/wuwen/go/src/github.com/gogits/gogs/models/login.go:230 +0xa3
github.com/gogits/gogs/models.UserSignIn(0xc208d631d6, 0xa, 0xc208425728, 0x8, 0x0, 0x0, 0x0)
	/home/wuwen/go/src/github.com/gogits/gogs/models/login.go:188 +0x517
github.com/gogits/gogs/routers/user.SignInPost(0xc20880b040, 0xc208d631d6, 0xa, 0xc208425728, 0x8, 0x0)
	/home/wuwen/go/src/github.com/gogits/gogs/routers/user/auth.go:106 +0x364
reflect.Value.call(0xbb21c0, 0xf94b78, 0x13, 0xdb7d70, 0x4, 0xc208d63440, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xbb21c0, 0xf94b78, 0x13, 0xc208d63440, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc2084a2e80, 0xbb21c0, 0xf94b78, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3c7
github.com/Unknwon/macaron.(*Context).run(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:113 +0x95
github.com/Unknwon/macaron.(*Context).Next(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:104 +0x33
github.com/macaron-contrib/session.func·004(0xc20845d710)
	/home/wuwen/go/src/github.com/macaron-contrib/session/session.go:188 +0x968
reflect.Value.call(0xb86ca0, 0xc20883ab60, 0x13, 0xdb7d70, 0x4, 0xc2084a32e0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xb86ca0, 0xc20883ab60, 0x13, 0xc2084a32e0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc2084a2e80, 0xb86ca0, 0xc20883ab60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3c7
github.com/Unknwon/macaron.(*Context).run(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:113 +0x95
github.com/Unknwon/macaron.(*Context).Next(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:104 +0x33
github.com/Unknwon/macaron.func·008(0xc20845d710, 0xc208156460)
	/home/wuwen/go/src/github.com/Unknwon/macaron/recovery.go:161 +0x73
reflect.Value.call(0xba60a0, 0xf94130, 0x13, 0xdb7d70, 0x4, 0xc208d630e0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xba60a0, 0xf94130, 0x13, 0xc208d630e0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc2084a2e80, 0xba60a0, 0xf94130, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3c7
github.com/Unknwon/macaron.(*Context).run(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:113 +0x95
github.com/Unknwon/macaron.(*Context).Next(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:104 +0x33
github.com/Unknwon/macaron.func·004(0xc20845d710, 0xc208156460)
	/home/wuwen/go/src/github.com/Unknwon/macaron/logger.go:40 +0x280
reflect.Value.call(0xba60a0, 0xf94120, 0x13, 0xdb7d70, 0x4, 0xc208d63080, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0xba60a0, 0xf94120, 0x13, 0xc208d63080, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc2084a2e80, 0xba60a0, 0xf94120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3c7
github.com/Unknwon/macaron.(*Context).run(0xc20845d710)
	/home/wuwen/go/src/github.com/Unknwon/macaron/context.go:113 +0x95
github.com/Unknwon/macaron.func·015(0x7f28c105a900, 0xc208859cc0, 0xc20863d5f0, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/router.go:158 +0x3ec
github.com/Unknwon/macaron.(*Router).ServeHTTP(0xc20819b7c0, 0x7f28c105a900, 0xc208859cc0, 0xc20863d5f0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/router.go:245 +0x3b8
github.com/Unknwon/macaron.(*Macaron).ServeHTTP(0xc20806c0e0, 0x7f28c105a900, 0xc208859cc0, 0xc20863d5f0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/macaron.go:171 +0x17c
net/http.serverHandler.ServeHTTP(0xc20886f860, 0x7f28c105a900, 0xc208859cc0, 0xc20863d5f0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208846dc0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by xujinzheng** [comment]
看之前的文档截图是支持SSL的，所以填写的SSL端口，结果不行，换成普通的就可以了

**Comment by Unknwon** [comment]
Yeah, SSL is not supported in Go, so we don't know how to fix it yet. :joy:

**Comment by Unknwon** [comment]
Hi there, by mering PR #1476 into develop, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by Unknwon** [comment]
Close as implemented. :tada:
