### ISSUE TITLE
Dashboard error: nil commits

### ISSUE THREAD

**Issue by williamn** [gogits/gogs#1246]
I got this error in Dashboard page

`template: user/dashboard/feeds:30:29: executing "user/dashboard/feeds" at <$push.Commits>: nil pointer evaluating *base.PushCommits.Commits`

My setup

- Gogs 0.6.1.0325 Beta
- Git 1.9.1
- Ubuntu 14.04.1 LTS

**Comment by Unknwon** [comment]
Thanks your reporting!

What did you do(push) before you see this error?

**Comment by williamn** [comment]
The issue is gone now. Maybe because of my commit is too big?

**Comment by Duckbrain** [comment]
I am getting this error too. I just migrated to MySQL after having issues with my SQLite database locking up, so there could be any number of things I changed.

I get this on the dashboard as well as the "Public Activity" tab in my profile, but not others' profiles. I can't find the commit log of any repos that cause this error.

Gogs 0.6.1.0325 Beta
git version 2.5.0
Arch Linux (up to date)

Here are the last few lines of my orm log after attempting to load the page
[xorm] [info]  2015/08/03 17:01:38.226839 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `lower_name` = ? LIMIT 1 [args] [duckbrain]
[xorm] [debug] 2015/08/03 17:01:38.236854 time(4) key[Created]: 2015-03-13 01:13:34 +0000 UTC | sdata: [2015-03-13 01:13:34]
[xorm] [debug] 2015/08/03 17:01:38.238586 time(4) key[Updated]: 2015-06-03 23:14:00 +0000 UTC | sdata: [2015-06-03 23:14:00]
[xorm] [info]  2015/08/03 17:01:38.244114 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `lower_name` = ? LIMIT 1 [args] [duckbrain]
[xorm] [debug] 2015/08/03 17:01:38.254507 time(4) key[Created]: 2015-03-13 01:13:34 +0000 UTC | sdata: [2015-03-13 01:13:34]
[xorm] [debug] 2015/08/03 17:01:38.256765 time(4) key[Updated]: 2015-06-03 23:14:00 +0000 UTC | sdata: [2015-06-03 23:14:00]
[xorm] [info]  2015/08/03 17:01:38.261326 [sql] SELECT `id`, `user_id`, `repo_id`, `mode` FROM `access` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [1 33]

None of the other logs update when the page is loaded.

**Comment by Unknwon** [comment]
Thanks @Duckbrain , did you forget to migrate `content` field in `action` table?

@williamn I think it may because some kind of push does not contain any commit, not commit is too large, I need to do some tests before knowing the answer, but thanks for your reply!

**Comment by Duckbrain** [comment]
You know what, I think a commit was made to a repository outside of Gogs while someone was trying to get around the locked database. I changed the permissions so Gog's could access the files, but they are not going to be in the database. (@williamn Sorry for taking your issue we can move this to another)

**Comment by Unknwon** [comment]
@Duckbrain not sure, but yes Gogs needs a nil value checker in the dashboard. :star:

**Comment by williamn** [comment]
@Duckbrain no worry, that is GitHub is all about. Social coding.
@Unknwon nil checker will be great

**Comment by Unknwon** [comment]
Just added a nil checker to `master` branch, please help test again! :grinning:

**Comment by Unknwon** [comment]
Close as implemented. :tada:

**Comment by williamn** [comment]
:beers:
