### ISSUE TITLE
Issues/Milestones page buggy?

### ISSUE THREAD

**Issue by TheExoduser** [gogits/gogs#1247]
Hey there,

and first of all, thanks for this awesome git server solution. I've already migrated all of my projects to gogs. But today I've mentioned, that the Issues/Milestones page of a project, is always in english and it shows the "Sign up" button in the top right corner. Thats the only page where the button is visible, since registrations are disabled on my server. 
Also in some of the download/clone popups the ssh link is listed even though I've disabled that feature.
And last but not least the download link on the issues page always links to a not existent file under /archive/master/anyzip.zip.

Would be awesome if you could fix that.

**Comment by bkidwell** [comment]
It looks like Issues and Milestones are using a completely different theme from the rest of the app.

[source screenshot](https://cloud.githubusercontent.com/assets/723919/8905449/62aaaaee-3434-11e5-98d0-2190a96d631f.png)
[issues screenshot](https://cloud.githubusercontent.com/assets/723919/8905453/68373414-3434-11e5-8654-27d797c2ae32.png)
[milestones screenshot](https://cloud.githubusercontent.com/assets/723919/8905455/6bcfa21e-3434-11e5-9487-f73c8f1d83c4.png)

**Comment by Unknwon** [comment]
@bkidwell it's transforming by pages, a lot work to replace all of them entirely.

**Comment by bkidwell** [comment]
Okay, thanks. I didn't understand that this was a change in process over several releases.

**Comment by Unknwon** [comment]
Hi @bkidwell @TheExoduser , the new issue/milestone pages have been finished and can be seen at:

- https://try.gogs.io/unknwon/gogs/issues
- https://try.gogs.io/unknwon/gogs/milestones

**Comment by Unknwon** [comment]
For 

> Also in some of the download/clone popups the ssh link is listed even though I've disabled that feature.

This should be fixed as well.

**Comment by Unknwon** [comment]
Code are pushed to `develop` branch, you can update and test it out!

**Comment by Unknwon** [comment]
Close as implemented. :blush:
