### ISSUE TITLE
Feature request: Integrated wiki

### ISSUE THREAD

**Issue by TheExoduser** [gogits/gogs#1248]
As some of you might have seen on hosters like GitHub there is an integrated wiki feature available for projects, hosted on their servers. 
Gogs is without a doubt pretty awesome already, but maybe you could add this request to your roadmap?

**Comment by matt-h** [comment]
This is a duplicate of #270

**Comment by HLFH** [comment]
@Unknwon Hi. It's a duplicate. Please close this issue.
