### ISSUE TITLE
Creating a new Migration can show user/pass in plane text on authorization fail. 

### ISSUE THREAD

**Issue by fredghostkyle** [gogits/gogs#1250]
In the error that say that the authentication failed, in the URL it shows the pass in plain text. If possible, please remove. Thanks.

**Comment by Unknwon** [comment]
I think we can hide this info in `prod` mode but still show in `dev` mode for debug purpose.

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/9288067/10c30b26-4367-11e5-9a28-a5b6cbfa7216.png)

This is how it looks like on `develop` branch.

**Comment by Unknwon** [comment]
Close as implemented. :blush:
