### ISSUE TITLE
More easy way to install?

### ISSUE THREAD

**Issue by gutenye** [gogits/gogs#1251]
I've followd the guide in http://gogs.io/docs/installation/install_gogs_on_ubuntu.html , it works, but that's too complicated. 

I just wonder if there is any easier way to install? For example https://about.gitlab.com/downloads/. 

What I want is:

```
1. apt-get install gogs
2. That's it. Easy and simple, and everyone loves it.
```

**Comment by dentmaged** [comment]
I made a pretty easy to use guide for Mac users, which can be found here: https://github.com/dentmaged/gogs.io-mac-installation/wiki

Possibly ```brew install gogs``` for mac users.

+1

**Comment by suksit** [comment]
I use Packager.io service and it works smoothly.

**Comment by dentmaged** [comment]
@suksit 191 failed, did packager glitch or is it okay to download?

**Comment by suksit** [comment]
I guess I'm still on 190…

I installed it like two months ago and have been keeping it updated with apt-get update && apt-get upgrade from time to time.

**Comment by crohr** [comment]
@dentmaged there was a network issue while fetching dependencies. I just relaunched the packaging and it went through [successfully](https://packager.io/gh/pkgr/gogs/build_runs/191). Note that even if the last build was failed, you could still install the most recent working deb/rpm (i.e. failing builds do not result in broken packages being released).

**Comment by crohr** [comment]
@gutenye [Packager.io](https://packager.io) was built to simplify the installation process of software, using tools that everyone understands. So please do use the Gogs deb/rpm package!

**Comment by gutenye** [comment]
@crohr, Thanks, Packager.io is the way I looking for.

**Comment by XadillaX** [comment]
packager.io is not that friendly in china.

any way to download the deb file?

**Comment by Unknwon** [comment]
@XadillaX currently... hmm... no. Why not just download compiled binary zip file?
