### ISSUE TITLE
Repo migration with a git:// URL does not require any authentication

### ISSUE THREAD

**Issue by seventh** [gogits/gogs#1252]
I tried to migrate some repos into gogs 0.6.1. For that, I needed each time to clear user/password from the form, as I was using a git:// URL as source, which were automatically provided otherwise.

**Comment by linquize** [comment]
did you save password in your web browser?

**Comment by seventh** [comment]
Seems to. I retried after clearing firefox saved passord, and all went OK.

**Comment by Unknwon** [comment]
Hmm.. seems it's browser auto-save feature for the web form, close it now but open for continuing discussion. :dizzy:
