### ISSUE TITLE
迁移外部仓库的问题

### ISSUE THREAD

**Issue by axlrose** [gogits/gogs#1254]
环境: win7 64位系统，选择sqlite3数据库
使用迁移外部仓库时，使用 https方式同步git.oschina.net的仓库，点击  [需要授权验证] 不会显示输入用户名和密码的输入框，当填写所有信息后，点 迁移仓库里，提示验证失败，此时出现输入 需要迁移仓库的用户名和密码框，输入完毕后再点迁移，此时显示仓库已存在

是否应该是点击需要授权验证时就显示出用户密码输入框？

**Comment by linquize** [comment]
現在的gogs首先创建 Repository, 然后才 clone, 
如果 clone 失敗(包括网络问题/错误密码)，就沒有删除 Repository，所以显示仓库已存在

**Comment by axlrose** [comment]
主要原因我觉得还是因为无法输入用户名和密码，此时点击 需要授权验证 无法显示输入框，应该是个BUG吧

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version? And your browser? 

> 是否应该是点击需要授权验证时就显示出用户密码输入框？

Yes. You misunderstand the migrate flow, you should enter auth info first, then clone. And the problem in your case is why the input boxes didn't show up after you click the button, not why the repository exists(this is bug if you auth is invalid).

In the `v0.6.3` release, auth fail will be reported in the UI and will not create a useless repository anymore.

**Comment by Unknwon** [comment]
What is the status of this issue?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
