### ISSUE TITLE
LDAP Base DN and Search Filter Has No Effect on User Authorization

### ISSUE THREAD

**Issue by msimpson** [gogits/gogs#1257]
The [**LoginUserLdapSource**](https://github.com/gogits/gogs/blob/master/models/login.go#L229) method relies upon [**SearchEntry**](https://github.com/gogits/gogs/blob/18c06973292a3d20b8ad72575c819fbe3287a9ad/modules/auth/ldap/ldap.go#L58) to perform an authentication check during the LDAP login process. This happens by way of the **SearchEntry** method binding to the domain with the given user's credentials, thereby providing authentication, and applying both the configured *base dn* and *search filter* to query the user's attributes for the possible use in auto registration.

However, if an administrator (such as myself) attempts to restrict those who could feasibly login by way of altering the *search filter* to a specific group, like the example given below:

```
(&(objectClass=user)(memberOf=cn=developers,cn=users,dc=domain,dc=com)(sAMAccountName=%s))
```

Then the **SearchEntry** method could end up returning a successful authentication but with blank attributes (`"", "", "", "", true`) for those users who successfully bind but ultimately fall outside of the *search filter*, or even *base dn*. And if this is the initial login for that user as well, then the profile which is created in turn is also blank (see below). This causes a situation where the user can never login a second time once they have logged out of the first.

![bad](https://cloud.githubusercontent.com/assets/730334/7537507/75e886c8-f567-11e4-951e-6cd7d4097938.png)

A quick fix would simply entail checking more of the returned attributes from the **SearchEntry** query, such as ***name***, instead of relying on the bind itself as the sole method of authentication and authorization.

Although, a better alternative would be to rewrite the method by which Gogs users are authenticated and authorized against LDAP entirely. Possibly providing a bind user in the LDAP configuration for all queries during auto registration would allow for an empty return from the **SearchEntry** query to be treated as "user not found" and hence unauthorized, instead. Whereas a successful query would be treated as an authorization and move on to a test bind for the given user's credentials to prove authentication as well.

**The main point being that a successful bind is only authentication and not authorization as well.**

#### Information:
**Gogs Version:** 0.6.1.0325 Beta
**Git Version:** 2.4.0
**Gogs Host System:** Arch Linux (lts)
**LDAP:** Windows Server 2008 R2 Active Directory

**Comment by Unknwon** [comment]
Hi there, by mering PR https://github.com/gogits/gogs/pull/1476 into `develop`, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by Unknwon** [comment]
Close as implemented. :tada:
