### ISSUE TITLE
请问什么时候能增加PHP语言选择和wiki 以及代码质量等功能？

### ISSUE THREAD

**Issue by xuwu125** [gogits/gogs#1258]
请问什么时候能增加PHP语言选择和wiki 以及代码质量等功能？
Could you tell me what time can increase the PHP language choice and wiki, and code quality, etc?

**Comment by Unknwon** [comment]
> PHP语言选择

Should have been added (with framework name, not literally `PHP`).

> wiki

Please follow https://github.com/gogits/gogs/issues/270

> 代码质量等功能

Not in the plan...
