### ISSUE TITLE
在点击工单管理后,界面语言自动切换成了英文

### ISSUE THREAD

**Issue by mazhaoyong** [gogits/gogs#1259]
我是自己编译的源码,在系统中建立了一个组织,在组织中创建了项目,所有人配置了项目操作权限.在跳转到项目issue时,界面语言自动变成了英文.
刚试了下try.gogs.io,也存在同样的问题
另外,我建立的工单,在选择分配时,找不到可以分配的人.下拉列表是空的.

go语言版本:1.3
系统版本:0.6.1.0325 Beta
操作系统:win2003
数据库:mysql

**Comment by Unknwon** [comment]
Duplicated to #736.
