### ISSUE TITLE
Can I use github.com/gogits/gogs/modules/git as a library?

### ISSUE THREAD

**Issue by bronze1man** [gogits/gogs#1261]
Can I use github.com/gogits/gogs/modules/git as a library?
Will you guys keep the compatible of the old version of the library?

The library looks like a pure golang implement of libgit.
I can cross compatible my tools to another platform eaiser.

**Comment by linquize** [comment]
note: currently, it relies on git command line.

**Comment by bronze1man** [comment]
Sorry,I just find that it is not meet my needs.
I need get the index tree of the repository.
I use github.com/libgit2/git2go again..

**Comment by Unknwon** [comment]
`modules/git` is a git-shell implementation, so... yeah, closing issue. :flushed:
