### ISSUE TITLE
Will there be a packager.io package for Ubuntu 15.04?

### ISSUE THREAD

**Issue by gutenye** [gogits/gogs#1263]
The big changes for Ubuntu 15.04 is use systemd as default init .

**Comment by Unknwon** [comment]
Well... you have to ask @crohr about it. :satisfied:

**Comment by crohr** [comment]
@gutenye only LTS versions of ubuntu will be supported by Packager.io, so you'll have to wait for ubuntu 16.04. Note that systemd is already supported for other distributions (centos 7 and debian 8), so that's not a blocking point.

**Comment by tboerger** [comment]
@crohr it's sad to have only that limited amount of distros for packaging, especially for that easy kind of packages with golang applications :(

**Comment by crohr** [comment]
Well, true for Go apps (but Packager is not limited to Go only), but at the same time I'm not sure why you would want to use anything other than LTS versions for your servers.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.

**Comment by dudheit** [comment]
Hi, same question for Ubuntu 16.04 :-)

**Comment by Buzut** [comment]
@dudheit Meanwhile you can use the debian package. As both Debian 8 and Ubuntu 16.04 use systemctl its works perfectly!

**Comment by tmortagne** [comment]
packager.io now claim they support Ubuntu 16.04 but I don't see it listed on https://packager.io/gh/pkgr/gogs/install?bid=481#ubuntu-14-04-gogs so I guess it require something on gogs side too.

**Comment by tboerger** [comment]
It have to be enabled at https://github.com/gogits/gogs/blob/master/.pkgr.yml

**Comment by Unknwon** [comment]
Free to send a PR :)

**Comment by angelog** [comment]
Is it as simple as this?
```  ubuntu-16.04:
<<: *debian```
Currently looking for solutions to my broken instance.. :)
