### ISSUE TITLE
How to completely remove Gogs from my VPS

### ISSUE THREAD

**Issue by infoir** [gogits/gogs#1264]
I configured Gogs onmy Ubuntu 14.04 VPS.But now I am facing some problem with it. I want to remove it from my VPS. What is the procedure to remove it completely.

**Comment by m-json** [comment]
1. kill all gogs processes
2. rm -rf ./folder-you-saved-gogs/
3. delete any additional cronjobs or init scripts you may have made

quite simple? or did you install from some package? i can't imagine why one would do so

**Comment by Unknwon** [comment]
@json-m said pretty much everything.

Also don't forget to remove the directory you set Gogs to store all repositories. And the SSH auth file.

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:

**Comment by YugoCode** [comment]
I also wanted to delete GOGS and then setup new. I deleted everything but if I make a ssh to server I still get the message: PTY allocation request failed on channel 0
bash: /home/git/gogs/gogs: No such file or directory
Connection to myserver closed.

Why?

**Comment by tboerger** [comment]
@YugoCode you have to remove the content of ~/.ssh/authorized_keys as well. On all systems you've got configurations for all kind of software that can not get purged automatically.

**Comment by Unknwon** [comment]
@YugoCode On admin dashboard,

![image](https://cloud.githubusercontent.com/assets/2946214/11427917/abb6aad4-9434-11e5-89ad-64b59f16d056.png)

**Comment by YugoCode** [comment]
Thank you guys, your tips worked! :)
