### ISSUE TITLE
"Gogs: Internal error" When using 'git clone'

### ISSUE THREAD

**Issue by Jsewill** [gogits/gogs#1266]
Below is the message I receive (though I replaced the actual repository name) when I attempt to clone a repository created in Gogs via ssh.

```
fatal: 'repositoryname' does not appear to be a git repository
Gogs:  Internal error
fatal: Could not read from remote repository.
```

I've noticed in some other issues that it could be duplicated authorized keys, but in my case there aren't any duplicates.

**Comment by Jsewill** [comment]
It appears that Gogs output the organization name in the repository url with capital letters.  I blindly copied and pasted.  Shortly after opening this issue I returned to the repository page in Gogs to find the correct URL.  The same thing happened to another developer I am working with, so I'm quite sure it wasn't just my mistake.

**Comment by Unknwon** [comment]
Thanks your feedback!

I think it's not about the upper/lower case thing, it's another bug that Gogs cannot handle anonymous SSH clone, which has been fixed in `develop` branch. Please help test again, thanks!

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.

**Comment by romain-poirson** [comment]
Hello,

I can confirm Jsewill, when the organization or the repository has Capital letter, git clone fails (but works in https).

Thx

**Comment by Unknwon** [comment]
@romain-poirson can you reproduce this on https://try.gogs.io ?

**Comment by patryk-s** [comment]
I have the same problem. I named my organization in all capital letters and could only clone/push via https. But it works through SSH if I lowercase the name in URL (without changing organization name in Gogs).
Hope that helps in debugging.

**Comment by Unknwon** [comment]
Same comment as above of mine...

**Comment by romain-poirson** [comment]
@Unknwon : in have reproduced the bug on try.gogs.io, as you can see it : https://try.gogs.io/CapitalizeCompagnie/CapitalizeGit
my id user : 3971

Thx

**Comment by Unknwon** [comment]
@romain-poirson it gives me 404 which I can't tell what bug do you mean?

**Comment by romain-poirson** [comment]
My bad, the repository was not public.

**Comment by Unknwon** [comment]
@romain-poirson no worries. I can open it now, it's an empty repo... what's next?

**Comment by romain-poirson** [comment]
you must be in the same organization (git clone via SSH), what is your account on try.gogs.io ?

**Comment by Unknwon** [comment]
@romain-poirson same as GitHub: `unknwon`

**Comment by romain-poirson** [comment]
Ok i I put back the repository in private, still it works effectively.
I added you to our organization and I created a new repository in this organization : "AnotherCapitalize". I can't clone it via SSH. And you ?

**Comment by romain-poirson** [comment]
NB : during the creation, this repository was in private by defaut. If you confirm the error, i will try to put in public, then in private and try to clone it again. I think it will work.

**Comment by Unknwon** [comment]
@romain-poirson Got it, I can reproduce it now!

**Comment by romain-poirson** [comment]
Nice one :)

**Comment by Unknwon** [comment]
@romain-poirson OK! Please test on try again, it should be fixed by `develop` branch.

**Comment by romain-poirson** [comment]
it works, thx a lot.

**Comment by Unknwon** [comment]
@romain-poirson thanks for following up!
