### ISSUE TITLE
https 下 配置 duoshuo 的代理 gravatar 服务

### ISSUE THREAD

**Issue by leecade** [gogits/gogs#1267]
不确定 duoshuo 有没有 https 的, 目前配置 duoshuo 的话是 http 的

这会导致混合了 http, 报安全问题

**Comment by Unknwon** [comment]
Hi! Looks like duoshuo does not have HTTPS proxy for Gravatar...

For that reason, maybe you can disable Gravatar and let use upload their pictures?

**Comment by leecade** [comment]
ok upload maybe is a feasible way.
