### ISSUE TITLE
Running under subdirectory

### ISSUE THREAD

**Issue by frenchja** [gogits/gogs#1269]
Is it possible to run gogs on the subdirectory of an existing domain?  I own an SSL cert to `cloud.domain.org` which already runs Owncloud.  I wanted to play around with gogs before purchasing another SSL cert.  I attempted to run it under `cloud.domain.org/git` by adding this to my `/etc/nginx/conf.d/owncloud.conf`:

```
location /git {
		proxy_pass http://localhost:6000;
	}
```

Likewise, I also played around with the `ROOT_URL` in `/etc/gogs/conf/app.ini`, but this change ended up in a redirect loop:

```
ROOT_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/git
```

**Comment by saboya** [comment]
I don't know the details of your install, but I suspect it's pretty close to mine. I installed via apt on Ubuntu 14.04 and had the exact same issue.

The thing is you cannot run GoGS under a subdir for the first time. Set it to /, do the initial config and then change your nginx config to the following:

    location ^~ /git/ {
        proxy_pass http://localhost/6000/;
    }

And then on app.ini:

    ROOT_URL = https://example.com/git/

Notice the ending slashes, they have to be exactly like that. I hope this solves your problems. If you are doing SSL on nginx DO NOT set PROTOCOL to http on app.ini or it will complain about the certificates.

**Comment by Unknwon** [comment]
Hi @frenchja , see http://gogs.io/docs/intro/faqs#set-up-with-suburl for how to config with Nginx, every character helps. :bowtie:

**Comment by frenchja** [comment]
Thanks for the tip, I'll check it out

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
