### ISSUE TITLE
raw files charset

### ISSUE THREAD

**Issue by ElessarWebb** [gogits/gogs#1273]
I have a repository with agda code in gogs, which is displayed fine normally, but the "raw file" looks like a mess.

**gogs version**: Version: 0.6.1.0325 Beta
**go version**: Go1.4.2
**git version**: 2.3.2
**system**: arch linux

**Comment by ElessarWebb** [comment]
I suppose that's the HTTP charset parameter that is not set properly?

**Comment by Unknwon** [comment]
Thanks your feedback! 

It's been a while and a merged PR had focused on this problem, try https://try.gogs.io/unknwon/gogs/raw/master/gogs.go see if problem still exists. :dizzy:

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
