### ISSUE TITLE
OSX Installation Error

### ISSUE THREAD

**Issue by nixdaemon** [gogits/gogs#1278]
Hi,
I am getting error when i run the ./gogs web for the first time after i fill out the installation form. It looks like its failing on one of the migration task. Below is the error i got.

[install.go:65 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: pq: column a.user_name does not exist

i am using binary 0.61. Please Help.
Thanks

**Comment by makhov** [comment]
Try execute ./gogs update

**Comment by nixdaemon** [comment]
looks like that fixed the issue. Thanks!
