### ISSUE TITLE
Allow editing of past comments

### ISSUE THREAD

**Issue by 5paceManSpiff** [gogits/gogs#1280]
I can't seem to be able to edit previous comments I've made in my issue tracker.  Am I missing something or is this not implemented?

**Comment by jstonne** [comment]
+1. I would love this feature as well. I noticed the Edit Comment and Remove Comment was commented out in the issue/view.tmpl file.

**Comment by Unknwon** [comment]
It is now possible to edit issue and comments! https://try.gogs.io/unknwon/gogs/issues

**Comment by Unknwon** [comment]
Close as implemented. :tada:
