### ISSUE TITLE
Can't filter issues by milestone

### ISSUE THREAD

**Issue by jiku** [gogits/gogs#1281]
```http://127.0.0.1:4444/user/Project/issues?milestone=1``` shows all issues. (Already referenced on [trello](https://trello.com/c/ZrOnknP0) but leaving open ahead of updated Issues interface.)

**Comment by Unknwon** [comment]
Thanks your feedback!

It should be fixed with `develop` branch, and you can also test on https://try.gogs.io/unknwon/gogs/issues?type=all&state=open&labels=0&milestone=46 . :beer:

**Comment by Unknwon** [comment]
Close as implemented. :sunny:
