### ISSUE TITLE
请问升级到最新版还有505错误该怎么解决？

### ISSUE THREAD

**Issue by HowieWang** [gogits/gogs#1282]
505来源：
原来有个文件夹a，a里有个b，b我先加了git，然后又在a加（当时忘记b在里面了--！），这个时候a的项目里b的文件夹是空的，a的页面出现505，删除b后，再提交还是505.  

尝试解决：
在仓库里把整个a删掉了，回到页面还是505，因为进不到具体设置，所以实在不知怎么删除这个多余的项目了。  
多谢多谢！

**Comment by Unknwon** [comment]
Gogs does not support subrepo as described in https://github.com/gogits/gogs/issues/1061, and I think this one is duplicated. :grinning:
