### ISSUE TITLE
Failed to install using docker and docker-compose

### ISSUE THREAD

**Issue by luckcolors** [gogits/gogs#1283]
Hello i'm trying to install gogs in docker debian 8 64. But it keeps failing at the compile of gogs.
System packets installed using apt
sudo
docker (using get.docker.com)
golang
 here's the full log:

Building web...
Step 0 : FROM google/golang:latest
 ---> 3cc1d7ae0e9c
Step 1 : ENV TAGS "sqlite redis memcache cert" USER "git" HOME "/home/git"
 ---> Using cache
 ---> ecd45e472843
Step 2 : COPY . /gopath/src/github.com/gogits/gogs/
 ---> Using cache
 ---> f7b882c7d54b
Step 3 : WORKDIR /gopath/src/github.com/gogits/gogs/
 ---> Using cache
 ---> 49b3f0f049ba
Step 4 : RUN go get -v -tags="$TAGS" github.com/gogits/gogs   && go build -tags="$TAGS"   && useradd -d $HOME -m $USER   && chown -R $USER .
 ---> Running in e9ca025201c6
github.com/Unknwon/cae (download)
github.com/Unknwon/com (download)
github.com/Unknwon/i18n (download)
Fetching https://gopkg.in/ini.v1?go-get=1
Parsing meta tags from https://gopkg.in/ini.v1?go-get=1 (status code 200)
get "gopkg.in/ini.v1": found meta tag main.metaImport{Prefix:"gopkg.in/ini.v1", VCS:"git", RepoRoot:"https://gopkg.in/ini.v1"} at https://gopkg.in/ini.v1?go-get=1
gopkg.in/ini.v1 (download)
github.com/Unknwon/macaron (download)
github.com/codegangsta/cli (download)
github.com/go-sql-driver/mysql (download)
github.com/go-xorm/core (download)
github.com/go-xorm/xorm (download)
github.com/gogits/chardet (download)
github.com/gogits/go-gogs-client (download)
github.com/macaron-contrib/cache (download)
github.com/bradfitz/gomemcache (download)
Fetching https://gopkg.in/redis.v2?go-get=1
Parsing meta tags from https://gopkg.in/redis.v2?go-get=1 (status code 200)
get "gopkg.in/redis.v2": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v2", VCS:"git", RepoRoot:"https://gopkg.in/redis.v2"} at https://gopkg.in/redis.v2?go-get=1
gopkg.in/redis.v2 (download)
Fetching https://gopkg.in/bufio.v1?go-get=1
Parsing meta tags from https://gopkg.in/bufio.v1?go-get=1 (status code 200)
get "gopkg.in/bufio.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bufio.v1", VCS:"git", RepoRoot:"https://gopkg.in/bufio.v1"} at https://gopkg.in/bufio.v1?go-get=1
gopkg.in/bufio.v1 (download)
github.com/macaron-contrib/oauth2 (download)
github.com/macaron-contrib/session (download)
github.com/nfnt/resize (download)
github.com/microcosm-cc/bluemonday (download)
Fetching https://golang.org/x/net/html?go-get=1
Parsing meta tags from https://golang.org/x/net/html?go-get=1 (status code 200)
get "golang.org/x/net/html": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html?go-get=1
get "golang.org/x/net/html": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
github.com/russross/blackfriday (download)
github.com/shurcooL/sanitized_anchor_name (download)
Fetching https://golang.org/x/net/html/charset?go-get=1
Parsing meta tags from https://golang.org/x/net/html/charset?go-get=1 (status code 200)
get "golang.org/x/net/html/charset": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html/charset?go-get=1
get "golang.org/x/net/html/charset": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding?go-get=1 (status code 200)
get "golang.org/x/text/encoding": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding?go-get=1
get "golang.org/x/text/encoding": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding/charmap?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding/charmap?go-get=1 (status code 200)
get "golang.org/x/text/encoding/charmap": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding/charmap?go-get=1
get "golang.org/x/text/encoding/charmap": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding/japanese?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding/japanese?go-get=1 (status code 200)
get "golang.org/x/text/encoding/japanese": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding/japanese?go-get=1
get "golang.org/x/text/encoding/japanese": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding/korean?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding/korean?go-get=1 (status code 200)
get "golang.org/x/text/encoding/korean": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding/korean?go-get=1
get "golang.org/x/text/encoding/korean": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding/simplifiedchinese?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding/simplifiedchinese?go-get=1 (status code 200)
get "golang.org/x/text/encoding/simplifiedchinese": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding/simplifiedchinese?go-get=1
get "golang.org/x/text/encoding/simplifiedchinese": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding/traditionalchinese?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding/traditionalchinese?go-get=1 (status code 200)
get "golang.org/x/text/encoding/traditionalchinese": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding/traditionalchinese?go-get=1
get "golang.org/x/text/encoding/traditionalchinese": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
Fetching https://golang.org/x/text/encoding/unicode?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding/unicode?go-get=1 (status code 200)
get "golang.org/x/text/encoding/unicode": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding/unicode?go-get=1
get "golang.org/x/text/encoding/unicode": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
github.com/lib/pq (download)
github.com/mattn/go-sqlite3 (download)
github.com/macaron-contrib/binding (download)
github.com/macaron-contrib/csrf (download)
github.com/macaron-contrib/i18n (download)
github.com/macaron-contrib/captcha (download)
github.com/macaron-contrib/toolbox (download)
github.com/codegangsta/cli
github.com/Unknwon/cae
github.com/Unknwon/cae/zip
github.com/Unknwon/com
github.com/Unknwon/macaron/inject
gopkg.in/ini.v1
github.com/Unknwon/macaron
github.com/gogits/go-gogs-client
github.com/go-sql-driver/mysql
github.com/go-xorm/core
github.com/go-xorm/xorm
github.com/gogits/gogs/modules/log
github.com/gogits/gogs/modules/bindata
github.com/bradfitz/gomemcache/memcache
github.com/macaron-contrib/cache
github.com/macaron-contrib/cache/memcache
gopkg.in/bufio.v1
gopkg.in/redis.v2
github.com/macaron-contrib/cache/redis
github.com/macaron-contrib/oauth2/jws
github.com/macaron-contrib/session
github.com/macaron-contrib/oauth2
github.com/macaron-contrib/session/redis
github.com/gogits/gogs/modules/setting
github.com/gogits/gogs/models/migrations
github.com/gogits/gogs/modules/asn1-ber
github.com/gogits/gogs/modules/ldap
github.com/gogits/gogs/modules/auth/ldap
github.com/nfnt/resize
github.com/gogits/gogs/modules/avatar
github.com/Unknwon/i18n
github.com/gogits/chardet
golang.org/x/net/html/atom
golang.org/x/net/html
github.com/microcosm-cc/bluemonday
github.com/shurcooL/sanitized_anchor_name
github.com/russross/blackfriday
golang.org/x/text/transform
golang.org/x/text/encoding
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
golang.org/x/text/encoding/korean
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/text/encoding/traditionalchinese
golang.org/x/text/encoding/unicode
golang.org/x/net/html/charset
github.com/gogits/gogs/modules/base
github.com/gogits/gogs/modules/git
github.com/gogits/gogs/modules/httplib
github.com/gogits/gogs/modules/process
github.com/gogits/gogs/modules/uuid
github.com/lib/pq/oid
github.com/lib/pq
github.com/mattn/go-sqlite3
github.com/gogits/gogs/models
github.com/macaron-contrib/binding
github.com/gogits/gogs/modules/auth
github.com/gogits/gogs/modules/auth/apiv1
github.com/macaron-contrib/csrf
github.com/macaron-contrib/i18n
github.com/gogits/gogs/modules/middleware
github.com/gogits/gogs/modules/cron
github.com/gogits/gogs/modules/mailer
github.com/gogits/gogs/modules/social
github.com/macaron-contrib/captcha
github.com/gogits/gogs/routers/user
github.com/gogits/gogs/routers
github.com/gogits/gogs/routers/admin
github.com/gogits/gogs/routers/repo
github.com/gogits/gogs/routers/api/v1
github.com/gogits/gogs/routers/dev
github.com/gogits/gogs/routers/org
github.com/macaron-contrib/toolbox
github.com/gogits/gogs/cmd
github.com/gogits/gogs
# github.com/gogits/gogs
/goroot/pkg/tool/linux_amd64/6l: running gcc failed: Cannot allocate memory
Service 'web' failed to build: The command [/bin/sh -c go get -v -tags="$TAGS" github.com/gogits/gogs   && go build -tags="$TAGS"   && useradd -d $HOME -m $USER   && chown -R $USER .] returned a non-zero code: 2

**Comment by luckcolors** [comment]
resolved need atleast 1gb of ram for building.

**Comment by Unknwon** [comment]
Hmm... interesting that Docker needs more memory...
