### ISSUE TITLE
这个项目是不是不准备继续开发了？

### ISSUE THREAD

**Issue by storezhang** [gogits/gogs#1285]
我看你们的代码已经很久没有提交过啦？还继续开发吗？

**Comment by s7v7nislands** [comment]
同问,正准备开始使用.

**Comment by linquize** [comment]
我也担心

**Comment by lunny** [comment]
嗯。我们权限都被剥夺了。现在只有无闻有权限了。要么Clone走另开一个？

**Comment by JKair** [comment]
创建了issue之后才发现已经2个月没有更新过代码了，目测这项目已经被放弃了。。。

**Comment by decker502** [comment]
团队闹别扭了吗？很好的项目，千万别废了啊

**Comment by storezhang** [comment]
哎，这造型，还没成功就开始闹别扭！现在问题这么多，就不齐心了！

**Comment by storezhang** [comment]
lunny 你是做什么的？前端还是git后端？

**Comment by melote** [comment]
请问无闻怎么回事，如果大不算维护的话，我们重新起名另开一个开发。

**Comment by Unknwon** [comment]
目前正在继续开发 :grinning:
