### ISSUE TITLE
Analytics/Custom HEAD content

### ISSUE THREAD

**Issue by blasphemy** [gogits/gogs#1286]
Hi, I'd like to add a tracking code to all my gogs pages. Is there an established way to do this, or am I better off forking and editing the template for head?

Thanks!

**Comment by quux** [comment]
+1

**Comment by cybernet** [comment]
+1

**Comment by tboerger** [comment]
Would make sense to add some form field to the admin settings to be able to add snippets like that to the footer.

**Comment by mxmehl** [comment]
+1
Especially when hosting a Gogs installation in Germany, users are forced to add "imprint" links on all their websites, linking to their full name, address, phone number etc. A user can be sued if he does not comply to that law. So yes, please enable Gogs users to add HTML code somewhere without manually editing /templates/base files :)

**Comment by Unknwon** [comment]
> Especially when hosting a Gogs installation in Germany, users are forced to add "imprint" links on all their websites, linking to their full name, address, phone number etc. A user can be sued if he does not comply to that law.

This.... is ... real?

**Comment by tboerger** [comment]
> Especially when hosting a Gogs installation in Germany, users are forced to add "imprint" links on all their websites, linking to their full name, address, phone number etc. A user can be sued if he does not comply to that law. So yes, please enable Gogs users to add HTML code somewhere without manually editing /templates/base files :)

That's not entirely true. The imprint is just required if you've got a commercial use for the website/gogs.

**Comment by mxmehl** [comment]
>> Especially when hosting a Gogs installation in Germany, users are forced to add "imprint" links on all their websites, linking to their full name, address, phone number etc. A user can be sued if he does not comply to that law. So yes, please enable Gogs users to add HTML code somewhere without manually editing /templates/base files :)

> That's not entirely true. The imprint is just required if you've got a commercial use for the website/gogs.

Nope, it's not about commercial usage. According to §55(1) RStV you can only leave away the imprint if the website is only for familiar and personal purposes. So offering people to register with one's Gogs installation, or even using it to make one's code public enforces you to have an imprint.

> This.... is ... real?

Yes. Of course, private people aren't sued very often but if you want to comply with the law it's necessary. Now imagine a company or larger organization using Gogs.

**Comment by Unknwon** [comment]
Alpha support for custom templates has been pushed to `develop` branch, you can put template file with same name/path under your `custom/templates` directory.

Some warnings:

- Make as minimal changes as possible
- No guarantee for compatibility with future changes
- Do not rely on template variables as much as possible, just change static content is recommended

Example usage:

- Custom version of your home page (`home.tmpl`)
- Add additional content to head (`base/head.tmpl`) or footer (`base/footer.tmpl`)

**Comment by Unknwon** [comment]
It is now possible to inject content into head and footer without losing upstream updates!

For example, create `custom/templates/inject/footer.tmpl`:

```
my content injected!
```

Restart or refresh (`dev` mode) your Gogs!
