### ISSUE TITLE
Any reason to use gogit instead of the libgit2 go bindings?

### ISSUE THREAD

**Issue by nacho** [gogits/gogs#1291]
This is just a question, why to spend time and effords on creating a gogit while you can use the well maintained library libgit2 which is also btw used by github.

**Comment by nacho** [comment]
Here you can find the bindings: https://github.com/libgit2/git2go

**Comment by tboerger** [comment]
Because some of the contributors dont't like cgo libraries. Wontfix.

**Comment by Unknwon** [comment]
Thanks for asking!

But Libgit2 is well maintained does not necessary mean that the Go binding is well maintained, and there is a hard time install libgit2 on windows and all other kinds of version break stuff with Go binding. So maybe wait until libgit2 reaches to v1 release.

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
