### ISSUE TITLE
Can't access repositories with Git over SSH

### ISSUE THREAD

**Issue by csu** [gogits/gogs#1292]
I added an ssh key: `2015/05/25 02:31:23 [T] SSH key added: csu`

I am using a non-standard port for ssh. When I try using ssh, I get:
```
csu:import (master)$ ssh -p nnnnn git@xyz
PTY allocation request failed on channel 0
Hi csu ! You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
Connection to xyz closed.
```

From the above output, it appears that the SSH connection over the port works and that authentication succeeded. However, this happens when I try using Git over SSH:
```
csu:import (master)$ setgip
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tboerger** [comment]
You can't connect through SSH to the Gogs user.

**Comment by csu** [comment]
Then how do you use Git over SSH?

**Comment by tboerger** [comment]
Git over SSH is a total different thing. You just can't connect a normal SSH session.

**Comment by csu** [comment]
That's not what the issue is about. The issue is saying that connection to normal SSH works, but when trying to use Git over SSH on the same port, it fails.

**Comment by lalomartins** [comment]
Seems to be the same problem as #1306 — in fact, your error message says already:
```
Please make sure you have the correct access rights
and the repository exists.
```

The tl;dr: you need to have your SSH key in your gogs account, not on the system's authorized_keys.

**Comment by csu** [comment]
It's in both. It's added through the gogs account, which then appends it to the gogs user's authorized_keys automatically.

**Comment by lalomartins** [comment]
Then I can't help you, sorry :-(

Ah, in fact the message does say `Permission denied (publickey).` I missed that the first time.

This is probably obvious, so I hope you're not offended, but you're using the git url provided by the gogs UI, right?

And does that url provide your non-standard port? It could be that gogs only provides scp-style addresses, which don't allow a port. If that's a case, it's a bug. With a non-standard port, it should look like `ssh://git@host.xz:xxxx/path/to/repo.git/`. If this is the problem, you can work around it by of course tweaking the URL by hand, or by putting an alias in you ssh config.

http://stackoverflow.com/questions/1558719/using-a-remote-repository-with-non-standard-port

**Comment by csu** [comment]
I'm using the one from Gogs. From what I recall, it did include the non-standard port in the url. Anyways, I've since given up on getting it to run on my own machine and have just installed it on a cloud VPS. Working perfectly on that :)

**Comment by Unknwon** [comment]
Looks this thread is finished?

Just a note before closing:

> Permission denied (publickey).

This error shows that your request is denied by the SSH server, the Git request does not even get to Gogs. :joy:

**Comment by lalomartins** [comment]
FWIW

> I'm using the one from Gogs. From what I recall, it did include the non-standard port in the url. Anyways, I've since given up on getting it to run on my own machine and have just installed it on a cloud VPS. Working perfectly on that :)

Sounds like it was something in your system (global) sshd config :smile_cat:

**Comment by trektrek** [comment]
here the same message, i solve changing the permission of ssh folder:
sudo chmod -R 600 .ssh 
i hope this help somebody...

**Comment by doct0rX** [comment]
@trektrek  worked 👍
