### ISSUE TITLE
How to start as a deamon

### ISSUE THREAD

**Issue by luckcolors** [gogits/gogs#1295]
Please make a better guide on how to start as an deamon.
I tried creating an debian service but it doen't complete the startup and instead it just start gogs as a normal command so when i close the ssh gogs closes.
Here's what happens to me log:

root@odroid-server:/home/luckcolors# service gogs start
2015/05/25 22:37:20 [W] Custom config (/media/Storage/bin/gogs/custom/conf/app.ini) not found, ignore this if you're running first time
2015/05/25 22:37:20 [T] Custom path: /media/Storage/bin/gogs/custom
2015/05/25 22:37:20 [T] Log path: /media/Storage/bin/gogs/log
2015/05/25 22:37:20 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/05/25 22:37:20 [I] Log Mode: Console(Trace)
2015/05/25 22:37:20 [I] Cache Service Enabled
2015/05/25 22:37:20 [I] Session Service Enabled
2015/05/25 22:37:20 [I] Run Mode: Development
2015/05/25 22:37:21 [I] Listen: http://0.0.0.0:3000

and here's the service file that i have created:
 for service config:
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Gogs web service deamon"
NAME=gogs
DAEMON=/media/Storage/bin/gogs/$NAME
DAEMON_ARGS="web"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

service startup method:
do_start()
{
        # Return
        #   0 if daemon has been started
        #   1 if daemon was already running
        #   2 if daemon could not be started
        export HOME=/root //added because gogs couldn't get home path automatically
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --t$
                || return 1
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
                $DAEMON_ARGS \
                || return 2

Thanks in advance for your help :)

**Comment by csu** [comment]
Try using supervisor

**Comment by luckcolors** [comment]
Sorry i cannot get to work supervisord could you help me to make the supervisord conf?
my gogs executable is in /media/Storage/bin/gogs

**Comment by matt-h** [comment]
You can try this one: https://github.com/gogits/gogs/blob/master/etc/supervisord.conf

**Comment by csu** [comment]
@luckcolors can you post your `supervisord.conf` here?

**Comment by voxxit** [comment]
@luckcolors There is a Dockerfile you could use to build a container which you can set to `--restart always`? https://github.com/gogits/gogs/blob/master/Dockerfile

**Comment by luckcolors** [comment]
@csu @matt-h I tried using the provided supervisord file. it doesn't work it says started but gogs it's not really started.
@voxxit The server is 32 bit (armv7) i cannot install docker. get.docker.
wget -qO- https://get.docker.com/ | sh 
Error: you are not using a 64bit platform.
Docker currently only supports 64bit platforms.

**Comment by luckcolors** [comment]
How can i create a service that works and it's not starting gogs as a application on my ssh session?

**Comment by Unknwon** [comment]
Hi @luckcolors , try supervisor conf:

```
[program:gogs]
directory=/home/git/go/src/github.com/gogits/gogs/
command=/home/git/go/src/github.com/gogits/gogs/gogs web
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/gogs/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/gogs/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
environment = HOME="/home/git", USER="git"
```

**Comment by luckcolors** [comment]
Hey Unknwon.
I don't know what i am doing wrong but supervisor doesn't seems to work for me? Any other methods that i could use?

**Comment by Unknwon** [comment]
@luckcolors what system are you using?

**Comment by luckcolors** [comment]
Ubuntu server for the moment but i'm probably going to switch to debian server.

**Comment by Unknwon** [comment]
Have you tried https://github.com/gogits/gogs/blob/master/scripts/supervisor/gogs for supervisor?

**Comment by voxxit** [comment]
@luckcolors I'd highly recommend running with Docker & `--restart always`.
https://github.com/gogits/gogs/tree/master/docker

**Comment by luckcolors** [comment]
@voxxit docker is an option but the problem is that the target server is armv7.
@Unknwon yes but it doesn't work.

**Comment by Unknwon** [comment]
> yes but it doesn't work.

What is your definition of `doesn't work`?

**Comment by luckcolors** [comment]
Ok sorry i wasn't able to  test when i answered in the last message. So i am testing it now again.
I copied supervisord.conf in the gogs folder. i mean the gogs root folder.
Changed the paths in the conf to respect where i placed gogs.
then i runned :
luckcolors@odroid-server:/media/Storage/bin/gogs$ sudo $PWD/scripts/supervisor/gogs
/media/Storage/bin/gogs/scripts/supervisor/gogs: 1: /media/Storage/bin/gogs/scripts/supervisor/gogs: [program:gogs]: not found
/media/Storage/bin/gogs/scripts/supervisor/gogs: 3: /media/Storage/bin/gogs/scripts/supervisor/gogs: web: not found
/media/Storage/bin/gogs/scripts/supervisor/gogs: 15: /media/Storage/bin/gogs/scripts/supervisor/gogs: user: not found
/media/Storage/bin/gogs/scripts/supervisor/gogs: 16: /media/Storage/bin/gogs/scripts/supervisor/gogs: environment: not found

**Comment by luckcolors** [comment]
Also running the command: supervisord    in the gogs root folder gives error: 
```
luckcolors@odroid-server:/media/Storage/bin/gogs$ supervisord
Error: .ini file does not include supervisord section
For help, use /usr/local/bin/supervisord -h
```

**Comment by Unknwon** [comment]
@luckcolors I really don't understand why you start what why, maybe just because I don't familiar with supervisor enough.

I recommend you read: https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04

**Comment by Unknwon** [comment]
What is the status of this issue?

**Comment by luckcolors** [comment]
OK sorry if i kept you waiting but i FINALLY managed to fix my friend's server and now gogs ir rocking!
The thing is that i didn't know how to use supervisord before.. now i do!
So thanks again for helping me. :)

**Comment by Unknwon** [comment]
OK, @luckcolors good to know! Thanks for your confirmation!
