### ISSUE TITLE
Can't open repository settings

### ISSUE THREAD

**Issue by csu** [gogits/gogs#1296]
![untitled](https://cloud.githubusercontent.com/assets/164822/7802408/acf8fbe0-02e9-11e5-8b83-98709140018f.gif)

**Comment by linquize** [comment]
Are you the owner of that repo, or
do you belongs to that organization?

**Comment by csu** [comment]
I am not the owner of the repo, but I am an admin on the installation. I was just trying to figure out how to delete a repository as an admin. There doesn't seem to be a way to do it from the admin panel either.

**Comment by linquize** [comment]
admin role does not mean you can directly change settings of repo owned by others?
