### ISSUE TITLE
Can't create an issue

### ISSUE THREAD

**Issue by yeleleo** [gogits/gogs#1298]
got error 
pq: duplicate key value violates unique constraint "issue_user_pkey"

**Comment by jeromenerf** [comment]
@yeleleo isn't the issue actually created, despite the error?

**Comment by jeromenerf** [comment]
It seems that the issues templates are quite outdated. The navbar isn't the same between issues and releases for instance and the template seems to have some issues getting the actual connected user.

**Comment by Unknwon** [comment]
Thanks for your feedback! I believe this issue is same as https://github.com/gogits/gogs/issues/1073 and has beed fixed in the latest version.

**Comment by Unknwon** [comment]
Closing it for now, feel free to continue discussion. :beer:
