### ISSUE TITLE
Gogs user and commit author correlation

### ISSUE THREAD

**Issue by jineff** [gogits/gogs#1299]
Gogs correctly identifies the commit author from his email. But email addresses are not case sensitive while Gogs compare is.

Gogs version: 0.6.1.0325 Beta

Thanks for your great work !

**Comment by tboerger** [comment]
:+1: Makes sense to always down-case the email address.

**Comment by Unknwon** [comment]
Thanks your feedback!

Pushed some changes as shown above, not sure fixed all places. Feedback welcome!

**Comment by Unknwon** [comment]
Close as fixed?
