### ISSUE TITLE
Unable to create a new repo: 500

### ISSUE THREAD

**Issue by n1try** [gogits/gogs#1300]
When I'm trying to create or migrate a new repository, gogs is showing a big, fat "500" to me. The logs say:
    `[repo.go:128 CreatePost()] [E] CreatePost: initRepository: open /opt/gogs/conf/content/git-bare.zip: no such file or directory`

**Comment by linquize** [comment]
What repo name, migrate URL did you enter?

**Comment by n1try** [comment]
It doesn't matter what name or URL I enter. I have tried many different, but the problem occurs with all of them. According to the logs, a zip-file which seems to be needed can't be found. Actually, the `content` directory mentioned in this logline doesn't exist. I installed Gogs via the Debian package manager.

**Comment by linquize** [comment]
Which version of gogs are you using?
Why git-bare.zip was not found?

**Comment by n1try** [comment]
It's 0.6.1.0325 Beta.
And git-bare.zip was not found because actually it's not there.

**Comment by n1try** [comment]
Totally purging and re-installing it from source code has helped. Sorry for the false alarm...
