### ISSUE TITLE
"read-only" users

### ISSUE THREAD

**Issue by alangrafu** [gogits/gogs#1301]
It would be useful to have "read-only" users that can clone repositories but can't create their own. This would be useful when you have stakeholders without strong technical expertise.

**Comment by carloscarcamo** [comment]
:+1:

**Comment by csu** [comment]
:+1: Even a global config option to disable repository creation on the entire site or for all non-admins would be great.

**Comment by y-ponomarev** [comment]
:+1:

**Comment by dentmaged** [comment]
:+1:

**Comment by tboerger** [comment]
@alangrafu Maybe you can create a pull request? I'm pretty sure @Unknwon is open for features like that :)

**Comment by ngloom** [comment]
readonly needed :+1:   :)

**Comment by Unknwon** [comment]
Now on `develop` branch, you can set user's repo limit to `0` on admin panel, so this user becomes `read-only`.

**Comment by Unknwon** [comment]
Close as implemented.

**Comment by alangrafu** [comment]
Thanks for the great work! 

User can still create organizations and migrations, will that be limited as well?

**Comment by Unknwon** [comment]
@alangrafu Yes... somewhere is the issues... can't remember which one exactly...
