### ISSUE TITLE
Dashboard Repository Sorting

### ISSUE THREAD

**Issue by Sauermann** [gogits/gogs#1302]
Currently repositories on the dashboard (quick-access on the right side) are sorted in a random order.
Having more than a dozen repositories makes finding them a bit tedious in the list.
I want to suggest to display them in a alphabetically sorted order, so that finding them becomes easier.

Collaborative Repositories would also benefit from sorting. I am however not sure if sorting by repository name or sorting by organization name would make more sense ... probably sorting by organization name.

**Comment by vtolstov** [comment]
Why not sort by commits count from some days?more active repos on top.
29 мая 2015 г. 11:25 пользователь "Markus Sauermann" <
notifications@github.com> написал:

**Comment by tboerger** [comment]
Sorting by activity makes much more sense than alphabetically.

**Comment by Sauermann** [comment]
I just noticed that on the dashboard the repositories seem to be sorted by last activity and not randomly.
However to make it consistent, it would make sense to sort the list of collaborative repositories in the same way.

**Comment by tboerger** [comment]
> However to make it consistent, it would make sense to sort the list of collaborative repositories in the same way.

:+1:

**Comment by ChangePlaces** [comment]
Sorting alphabetically makes more sense to me!

**Comment by tboerger** [comment]
@ChangePlaces github got the same behavior (sorted by activity) and I never got big problems to find the right repository.

**Comment by ChangePlaces** [comment]
Dare I say it, how about a 'dashboard sort order' in the admin somewhere? either 'random' / 'alphabetical' / 'commit date'?

**Comment by Unknwon** [comment]
Collaborative repositories are now sroted in the same way.

**Comment by Sauermann** [comment]
Looks good, closing as resolved.

@ChangePlaces regarding "'dashboard sort order' in the admin somewhere" it would probably be best if you would make for this feature-request a separate issue, so that it does not get lost.

**Comment by Unknwon** [comment]
@Sauermann thanks your confirmation!
