### ISSUE TITLE
Documentation is missing Mailer - From

### ISSUE THREAD

**Issue by gregorko** [gogits/gogs#1303]
The configuration cheat sheet is missing the From configuration of the mailer section.
http://gogs.io/docs/advanced/configuration_cheat_sheet.html

I took me quite some time and finally I found multiple reports of people who are stuck because of a missing From configuration. I think this could be solved if it would be added to the cheat sheet.

Gregor

**Comment by tboerger** [comment]
In worst case just look at https://github.com/gogits/gogs/blob/master/conf/app.ini, you can always find the latest available config options over there.

Maybe @Unknwon can open the documentation process for others to get contributions in that section.

**Comment by Unknwon** [comment]
Thanks! It's been added now: http://gogs.io/docs/advanced/configuration_cheat_sheet#mailer
