### ISSUE TITLE
Organization settings update, Avatar cannot be empty.

### ISSUE THREAD

**Issue by jmptbl** [gogits/gogs#1305]
When updating organization settings, an error appears after submitting: Avatar cannot be empty.

0.6.1.0325 Beta

**Comment by linquize** [comment]
duplicate of #1293?

**Comment by jmptbl** [comment]
Yes, looks like it might be.  In my setup the Gravatar email form field doesn't appear though.

**Comment by gitsnaf** [comment]
I have the same problem with 0.6.1.0325 Beta. I can't update an organization. And I would very much like to upload an avatar for a organization.

**Comment by stewartpark** [comment]
I'm experiencing the same problem. I'm using 0.6.1.0719 Beta

**Comment by Unknwon** [comment]
Hi there, fixed code has been pushed to `develop` branch and you can now test on https://try.gogs.io/ .
