### ISSUE TITLE
内存占用接近 80%

### ISSUE THREAD

**Issue by DrayChou** [gogits/gogs#1307]
目前服务器内存占用超过 80%，最高的时候到达 90%。
这个应该不算正常吧？

![gj55s7 0 a2m6ep b_ckhjc](https://cloud.githubusercontent.com/assets/760245/7957153/e3b82e8c-0a17-11e5-93e4-5b18ee54fa8d.jpg)

目前我们这个项目比较大。包含 20k+ 个文件，1k+ 个文件夹。

**Comment by linquize** [comment]
占用 10G RAM?

**Comment by Unknwon** [comment]
Can you retest on latest release 0.7.6?

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
