### ISSUE TITLE
Removing a collaborator deletes a repo

### ISSUE THREAD

**Issue by alangrafu** [gogits/gogs#1310]
I tried it twice to make sure I could replicate the problem: I created a repo and added a collaborator. Then I removed the collaborator and the repository is gone. Not only that, it is not possible to create a new repository with the same name, so probably only part of the repo's data is deleted from the database.

**Comment by da-kid** [comment]
I could not reproduce such behaviour.
Are you using the `dev` branch?

**Comment by dentmaged** [comment]
@da-kid The issue is from 6 days ago, I believe it wasn't fixed then.

**Comment by da-kid** [comment]
@dentmaged I tried it out with the newest release (master branch) and could not reproduce it.

**Comment by Unknwon** [comment]
This wrong behaviour has been fixed in latest version `master` and release `v0.6.3`, please upgrade to avoid it! :flushed:

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
