### ISSUE TITLE
checkVersion()] [E] Fail to read 'templates/.VERSION'

### ISSUE THREAD

**Issue by lkalneus** [gogits/gogs#1311]
I tried to test an installation from the source and got an error on startup:

```
22015/06/05 10:47:43 [W] Custom config (/opt/gopath/bin/custom/conf/app.ini) not found, ignore this if you're running first time
2015/06/05 10:47:43 [T] Custom path: /opt/gopath/bin/custom
2015/06/05 10:47:43 [T] Log path: /opt/gopath/bin/log
2015/06/05 10:47:43 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/06/05 10:47:43 [I] Log Mode: Console(Trace)
2015/06/05 10:47:43 [I] Cache Service Enabled
2015/06/05 10:47:43 [I] Session Service Enabled
2015/06/05 10:47:43 [I] Run Mode: Development
2015/06/05 10:47:43 [web.go:74 checkVersion()] [E] Fail to read 'templates/.VERSION': open /opt/gopath/bin/templates/.VERSION: no such file or directory

```

**Comment by lunny** [comment]
You should changed templates/.VERSION's to 0.6.1.0325 Beta.

**Comment by Unknwon** [comment]
You are missing template files. :joy:

Download zip and keep them all.

**Comment by tony** [comment]
Maybe I am misunderstanding this conversation, I continued this topic on #2995.  I do not consider it solved at this point.

Ideally, I think its the spirit of https://github.com/gogits/docs/blob/master/en-US/installation/install_from_source.md that ``go run ./gogs.go web`` would just run after ``go get -u github.com/gogits/gogs``.

**Comment by Unknwon** [comment]
@tony there is nowhere tells you use `go run`, but do `go build`.

**Comment by flyingoctopus** [comment]
I too am having the problem despite running ```go build```

erorr:

```
kanaloa ॐ  ~/Documents/sandbox/go/src/github.com/gogits/gogs:(4d17h55m|git@master)
1299 ± gogs web
2016/05/11 10:58:01 [W] Custom config '/Users/vincent/Documents/sandbox/go/bin/custom/conf/app.ini' not found, ignore this if you're running first time
2016/05/11 10:58:01 [T] Custom path: /Users/vincent/Documents/sandbox/go/bin/custom
2016/05/11 10:58:01 [T] Log path: /Users/vincent/Documents/sandbox/go/bin/log
2016/05/11 10:58:01 [I] Gogs: Go Git Service 0.9.25.0506
2016/05/11 10:58:01 [I] Log Mode: Console(Trace)
2016/05/11 10:58:01 [I] Cache Service Enabled
2016/05/11 10:58:01 [I] Session Service Enabled
2016/05/11 10:58:01 [I] Run Mode: Development
2016/05/11 10:58:01 [...gits/gogs/cmd/web.go:73 checkVersion()] [E] Fail to read 'templates/.VERSION': open /Users/vincent/Documents/sandbox/go/bin/templates/.VERSION: no such file or directory

```

**Comment by Unknwon** [comment]
@flyingoctopus I think the error is very obvious that the file is missing on the given path.

**Comment by flyingoctopus** [comment]
@Unknwon but is that not a ```go build``` issue?

**Comment by Unknwon** [comment]
@flyingoctopus no, it has nothing to do with `go build`. And docs asks you do `./gogs web` not `gogs web` explictly.

**Comment by tony** [comment]
my thing with this is i want to hit the ground running for developing on gogs.

what is your work flow when you're developing on gogs for local development @Unknwon ?

here is what i do:

```go
go get -u github.com/mattn/go-sqlite3
cd $GOPATH/src/github.com/gogits/gogs
GOGS_WORK_DIR=$PWD go run -tags "sqlite" gogs.go web
```

Do you run ``go install``, or do you run ``go build`` when a change happens? Do you use any tools to automatically run tests or build when developing gogs on your local environment?

**Comment by Unknwon** [comment]
@tony I do `go build -tags "sqlite"` and `./gogs web`. Never `go run`.
