### ISSUE TITLE
Credentials are “more or less” preserved across browser sessions

### ISSUE THREAD

**Issue by lalomartins** [gogits/gogs#1312]
I have my browser set to reopen tabs from last time.

When I go to my (private) gogs repository in a restored tab, I have a 404, and the UI indicates I'm not logged in. However, if I then click “log in” in the toolbar, instead of a login page, I go directly to my dashboard — which implies gogs does know who I am after all.

Might just be something to do with recovering state from the browser? Or is it session cookies? Anyway, probably easy to reproduce and by no means a big deal.

**Comment by Unknwon** [comment]
Thanks your feedback!

Which browser are you using?

I'm using Chrome and if I close and restore it with two ways:

1. Close tab, and restore tab
2. Exit Chrome completely and restore after reopen Chrome

Both ways are automatically logged in to Gogs.

My guess is the different behavior of restore a page, some browsers may not resent cookie to the site after restore.

**Comment by lalomartins** [comment]
Firefox, but I can't reproduce it consistently either, and I don't remember whether or not it happens on chrom*. Here's all the information I have:

- My Firefox is set up to reopen tabs from last time
- And of course nowadays Firefox does lazy loading of restored tabs
- I have my gogs permanently open in a tab
- I don't know if that matters, but I also use tab groups, in case you're wondering if I don't drown in open tabs ;-)

So when I click the gogs tab it loads; sometimes I'm logged in, sometimes I'm not. If I haven't been there for a couple of days, I'm definitely not.

I *think* (guesswork) it might have something to do with whether my IP changed?

**Comment by Unknwon** [comment]
Thanks your reply!

> I think (guesswork) it might have something to do with whether my IP changed?

It is possible that your session is expired so Gogs logged you out.

**Comment by lalomartins** [comment]
That makes sense, but why then does it log me immediately back (without asking for password or even showing login screen) when I click login?

How long does the session last? A quick look at the cookies suggests they're set for a week, and it definitely takes me less time than that for this to happen  — usually I see it from one day to the next.

I'm going to leave the tab open in the office computer's firefox when I shut down in a few minutes, then tomorrow morning I'll see if this is reproduced and let you know.

**Comment by Unknwon** [comment]
> How long does the session last? A quick look at the cookies suggests they're set for a week, and it definitely takes me less time than that for this to happen — usually I see it from one day to the next.

Cookie life time is one week, but if you're inactive for 24hours(86400s), session expired.

**Comment by lalomartins** [comment]
That seems likely to be it, combined with Firefox' lazy load.

Anyway :smiley_cat: the point is the behaviour is inconsistent; either it knows who I am (so display the repo contents) or it doesn't (so give me a login screen when I click login). IMHO, if loading a page with restricted content and my credentials are still valid, we could just renew the session.

**Comment by Unknwon** [comment]
> IMHO, if loading a page with restricted content and my credentials are still valid, we could just renew the session.

Definitely, just not sure if Firefox would re-send needed information(e.g. cookie) to server when reopen the tab.

**Comment by lalomartins** [comment]
I can probably do some debugging in the weekend, if I can find my way around the sources :smile_cat: if I artificially set the session expiration to a few minutes, then attempt to reproduce it, and dump what Firefox sends when the session is valid versus what it sends when it's expired… I'll let you know.

BTW, you have an awesome github username.

**Comment by Unknwon** [comment]
> I can probably do some debugging in the weekend, if I can find my way around the sources :smile_cat: if I artificially set the session expiration to a few minutes, then attempt to reproduce it, and dump what Firefox sends when the session is valid versus what it sends when it's expired… I'll let you know.

Sure, waiting for your result. 

> BTW, you have an awesome github username.

Beautiful mistake, if I have to say something about it :joy:

**Comment by lalomartins** [comment]
I overestimated how much time I was going to have over the weekend :frowning: sorry!

But my over-the-weekend test gave strange results :D on Firefox, I'm still logged in and the repo page displayed just fine. On Chromium, I was fully logged out, and clicking “login” took me to the normal login page.

???

**Comment by Unknwon** [comment]
I completely have no idea about what is going on ....

**Comment by lalomartins** [comment]
same :D

I'll really try to find a couple of hours this week to debug it

**Comment by Unknwon** [comment]
It's OK, take your time :bowtie:

**Comment by Unknwon** [comment]
OK, I fount out why.

Some pages that are not required sign in, so it does not check your information on the cookie.

But when you visit pages that require signin, it auto-redirects to sign in page which checks your cookie.

I'm fixed this problem on `pull_request2` branch, should be soon pushed on `develop` and `master`.

**Comment by lalomartins** [comment]
Aha, reproduced it :smiley_cat: skipping work Friday did it! In both browsers, too.

Screencasts: [Firefox](https://youtu.be/mIf0ZGb42Cw), [Chromium](https://youtu.be/iq5cBNpBzy4) — see if it's the same behaviour you found.

**Comment by Unknwon** [comment]
Exactly the same!

So, please try `master` see if problem is solved. Or maybe I could miss some special pages.

**Comment by lalomartins** [comment]
That's great to hear :smile_cat: I'll try on my private install when I get home tonight, although of course it will take a couple of days to see whether that fixed it :sweat:

**Comment by Unknwon** [comment]
> although of course it will take a couple of days to see whether that fixed it :sweat:

Actually you can change config to a shorter time for `remember me` options.

**Comment by lalomartins** [comment]
`LOGIN_REMEMBER_DAYS`?

**Comment by Unknwon** [comment]
Correct.

**Comment by Unknwon** [comment]
Or, just hack on cookie through browser...

**Comment by lalomartins** [comment]
Right — yesterday, my local test was positive! :+1: 

… then I went around figuring out how to update my actual production server ;) now it's running master (which is all right since I'm the only user), in a few days I'll let you know for sure if the bug disappeared.

**Comment by Unknwon** [comment]
@lalomartins sounds good!

**Comment by lalomartins** [comment]
sorry, so much stuff going on with the new job, I forgot to give you a final :+1: 

So today I turned on a laptop I haven't used in a couple of months, and the gogs tabs I had open from last time Just Worked™. As far as I'm concerned, this is proven fixed :smile_cat:

**Comment by Unknwon** [comment]
This is great, thanks your confirmation!
