### ISSUE TITLE
error adding ed25519 key

### ISSUE THREAD

**Issue by kyrias** [gogits/gogs#1313]
I get the following error when trying to add ed25519 key to try.gogs.io:

``Sorry, we're not able to verify your SSH key: ssh-keygen -l -f: line 1 too long: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa2...``

**Comment by Unknwon** [comment]
How long is a ed25519 key? :scream:

**Comment by kyrias** [comment]
@Unknwon An ed25519 public key is around 80 chars + the comment,

**Comment by Unknwon** [comment]
Well... that shouldn't be long...

But what do you mean by the 

> the comment

**Comment by kyrias** [comment]
The same comment that every SSH key has, most often being the hostname or username + hostname.

**Comment by Unknwon** [comment]
Thanks your info!

**Comment by Unknwon** [comment]
I've did some researching that I can't find out why Gogs gives you this error.

So... would you mind save your key content into a file, and do `ssh-keygen -l -f filename` see what system returns you?

**Comment by kyrias** [comment]
```
256 SHA256:KImNN87f1lzuLGHkm4hXrlIgJwxjF9OqzY8T8uDywjg kyrias@zorg.kyriasis.com (ED25519)
```

like it should.

**Comment by Unknwon** [comment]
Well... thanks your info. Let me generate a ED25519 key and add to Gogs.

**Comment by Unknwon** [comment]
Hmm...facing another problem myself with `unknown key type ed25519`.

:joy:

**Comment by arnehormann** [comment]
@Unknwon you need at least [OpenSSH version 6.5](http://www.openssh.com/txt/release-6.5), ed25519 is not supported in older versions.

**Comment by Unknwon** [comment]
@arnehormann thanks for the tip!

cc @kyrias can you check on that?

**Comment by arnehormann** [comment]
I should probably add that I use gogs with a ed25519 key. Works for me! :grinning:

**Comment by Unknwon** [comment]
@arnehormann :eyes:

**Comment by arnehormann** [comment]
@Unknwon does that mean you'd like a screenshot or you want to see the configuration?
I think you only need OpenSSH 6.5+ for the (superior) ed25519 keys, that's it. I'm running Gogs 0.6.9, it worked on 0.6.3, too.

**Comment by Unknwon** [comment]
@arnehormann no ... :sweat_smile: that's just a emoji .. no special meaning..

**Comment by arnehormann** [comment]
@Unknwon no problem, my bad :-)

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion. I suppose it has same solution to #1717

**Comment by arnehormann** [comment]
@Unknwon I did not try it yet, but since last week, ed25519 is supported by Go SSH: https://godoc.org/golang.org/x/crypto/ssh#pkg-constants
https://github.com/golang/crypto/commit/1e61df8d9ea476e2e1504cd9a32b40280c7c6c7e and https://github.com/golang/crypto/commit/5bcd134fee4dd1475da17714aac19c0aa0142e2f
If Gogs waited for the right time to drop dependencies on external SSH (at least when run in a container), it could be now 😀

**Comment by Unknwon** [comment]
@arnehormann That's a good news! But we have to wait until Gogs stops supporting Go 1.6 I guess.

**Comment by arnehormann** [comment]
@Unknwon thankfully not, the x/crypto release cycle is decoupled from Go itself.
