### ISSUE TITLE
PHP & Hack Syntax Highlighting

### ISSUE THREAD

**Issue by aewing** [gogits/gogs#1315]
It would be very much appreciated if something could be done to better support PHP and Hack (.hh) syntax highlighting. Currently prettify has some very weak PHP syntax highlighting support, and my PHP and Hack projects are less readable than others. An implementation of highlight.js or something with functioning PHP syntax highlighting, paired with recognition for .hh files, would do wonders for my repositories.

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/gogs/gogs

**Comment by Unknwon** [comment]
Close as fixed.
