### ISSUE TITLE
Memcached, Can gogs connect to a unix socket?

### ISSUE THREAD

**Issue by techzilla** [gogits/gogs#1318]
I'm Configuring Memcached, and was unable to determine if Gogs has the ability to connect to a unix socket.

For example, /var/run/memcached/memcached_socket

Is this possible?  Or will the configuration only do an IP at this time?

**Comment by Unknwon** [comment]
Hi there, based on the library that connects Memcached in Go(https://github.com/bradfitz/gomemcache/blob/master/memcache%2Fmemcache_test.go#L50), it can work with unix socket.

Hope helps!

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
