### ISSUE TITLE
error: failed to push some refs to ...

### ISSUE THREAD

**Issue by janviehweger** [gogits/gogs#1320]
pushing tags to remote repo produces following error:

```
Pushing to ssh://git@server:10022/user/foo.git
To ssh://git@server:10022/user/foo.git
 * [new tag]         test -> test
error: failed to push some refs to 'ssh://git@server:10022/user/foo.git'
```

although the tag gets inserted into the database. Accessing the tag in the gogs backend produces a http 500 error. 

i'm running Gogs version 0.5.13.0214 Beta on a docker container with mysql ...

**Comment by Unknwon** [comment]
Thanks your feedback!

It seems a bit old version 0.5.13, would you mind to try on latest release `v0.6.3`, or test on https://try.gogs.io ?

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
