### ISSUE TITLE
Could not appear to be a git repository or you do not have access rights

### ISSUE THREAD

**Issue by dns25** [gogits/gogs#1324]
$ git clone ssh://admin@DISHANT/Employee.git
Cloning into 'Employee'...
admin@dishant's password:
fatal: '/Employee.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
I am using CopSSH in windows as a sserver
Help me to solve this issue thanks in advance

**Comment by Unknwon** [comment]
It happens when your SSH key file on your server is used by other applications as well. Especially when you have added your client computer SSH key to the file, and add same key thorough Gogs again.

**Comment by manfer** [comment]
If that is a repository created with gogs most probable the uri is wrong. When you create a repository with gogs you can use a name that starts with an uppercase char but the repo itself will be in lowercase.

This mean that the correct SSH uri will be ssh://admin@DISHANT/employee.git and not ssh://admin@DISHANT/Employee.git

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion. :dizzy:

**Comment by rajvijay68** [comment]
Any solution to this? This problem occurs randomly. Once I restart my system, it starts working.

**Comment by Megavolv** [comment]
I have the same problem.
