### ISSUE TITLE
Markdown Info Strings

### ISSUE THREAD

**Issue by remexre** [gogits/gogs#1327]
Fenced code blocks with [info strings](http://spec.commonmark.org/0.19/#info-string) seem to not result in the info strings propagating to the generated HTML.

Example:
```
    ```java
    class IPromiseIUseNewlinesInRealCode { public static void main(String ... args) {
    System.out.println("Hello, World!");
    }}
    ```
```
should have its code tag something like `<code class="language-java">`, rather than just `<code>`.

**Comment by dentmaged** [comment]
What about ```
<code lang="java">
public static void main(String[] args) {
   System.out.println("Hello World!");
}
</code>
```

**Comment by linquize** [comment]
The author of [pandoc](https://github.com/jgm/pandoc) writes the markdown spec document.

**Comment by odinuge** [comment]
I think this was sorted out in [blackfriday](https://github.com/russross/blackfriday) some time ago. See commit  [#_1337886_](https://github.com/russross/blackfriday/commit/133788657b0ddebf0e884571fc99a5528e55a10f) and [_#15eb452_](https://github.com/russross/blackfriday/commit/15eb452ae4d56122e8f4ddb29f9787345fceff34)

Anyway, it works on [try.gogs.io](https://try.gogs.io/odinuge/markdown-testing).

**Comment by neolit123** [comment]
@remexre, the exact code block you have posted in the issue description indeed does not produce the "code" tag with class="language-java" at try.gogs.io.

but if i move the trailing [backquote][backquote][backquote] to be at the start of a line (i.e. at the 1st column) it produces the correct result.

it seems that the blackfridayparser is slightly less flexible compared to the github parser which allows the trailing [backquote][backquote][backquote] to be indented to the same column as the previous line (or something like that).

give it a try...

**Comment by Unknwon** [comment]
Thanks your info! @odinuge  @neolit123

**Comment by Unknwon** [comment]
Close as already possible.
