### ISSUE TITLE
Paths generated by Markdown are not relative

### ISSUE THREAD

**Issue by da-kid** [gogits/gogs#1328]
The markdown compiler correctly replaces the relative paths in the repositories root directory.
For example, `foo.png` gets `/foo/bar/raw/foo.png`.
But if you have the same markdown file, e.g. in the subdirectory `md`, the path stays `example.com/foo/bar/raw/foo.png`, even though it should be `/foo/bar/raw/`**`md`**`/foo.png`

**Comment by Unknwon** [comment]
This should have been fixed with latest release.
