### ISSUE TITLE
Images are missing the mimetype

### ISSUE THREAD

**Issue by da-kid** [gogits/gogs#1329]
Images that are accessed via the `/user/repo/raw/branch/file.img` route are missing the mime-type.

**Comment by Unknwon** [comment]
Thanks your feedback!

Please checkout link https://try.gogs.io/unknwon/gogs/raw/master/public/img/404.png now see if problem solves.

**Comment by peppage** [comment]
This seems fine to me

**Comment by Unknwon** [comment]
@peppage thanks your confirmation!

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
