### ISSUE TITLE
docker 搭建的 gogs 添加ssh key 后无法生效

### ISSUE THREAD

**Issue by nicky1108** [gogits/gogs#1330]
我用docker 搭建的 docker-gogs ，添加了sshkey 后，本地push 和 clone 还是需要密码，无法生效

**Comment by Unknwon** [comment]
Thanks your feedback!

But there is not enough details for me to debug.

- Quick answer: 

You didn't config SSH server right, and push/pull request didn't even get to Gogs.

- Long questions:

1. What is your dockerfile?
2. Gogs is running under which user?
3. What is your SSH clone URL?

**Comment by Unknwon** [comment]
Please use new official Docker image of Gogs.

Close for now, but open for continuing discussion. :dizzy:
