### ISSUE TITLE
Disable Gravatar option when install

### ISSUE THREAD

**Issue by zoowar** [gogits/gogs#1333]
The current default avatar is set to fetch an image from gravatar. Please do not do this as many do not wish to share their browsing activity with tracking systems. Please include a default avatar image in the gogs release and fetch it from the local server.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I don't understand the problem you describle very well as I suppose you didn't read/understand [docs](http://gogs.io/docs/advanced/configuration_cheat_sheet.html) deeply.

You can just disable the Gravatar and there is a local default avatar in the Gogs.

**Comment by zoowar** [comment]
My suggestion is that the default behavior with respect to avatars should be "DISABLE_GRAVATAR true". People should have to opt-in to tracking systems.

**Comment by manfer** [comment]
+1 for gravatar being disabled by default and turned on in config by any admin that wants to use it.

If possible it could be even a per user option instead of a side wide option imposed by admin.

**Comment by Unknwon** [comment]
Well... I agree, how about add this config option in the `/install` page, so user can disable/enable it at the beginning?

**Comment by Unknwon** [comment]
Hi, I've pushed code to `develop` branch that has `Disable Gravatar` checkbox with default checked.

**Comment by Unknwon** [comment]
Closed as implemented. :tada:
