### ISSUE TITLE
UNIQUE constraint failed: issue_user.id

### ISSUE THREAD

**Issue by ptx0** [gogits/gogs#1335]
```
2015/06/16 10:55:30 [issue.go:251 CreateIssuePost()] [E] issue.CreateIssuePost(?): UNIQUE constraint failed: issue_user.id
```

This occurs on every new issue being created after I added the first collaborator to a project.

**Comment by ptx0** [comment]
Sorry, this looks like #1298

**Comment by Unknwon** [comment]
No worries, please follow on #1298. :smile:
