### ISSUE TITLE
Deleting a user corrupts issues

### ISSUE THREAD

**Issue by 1Hyena** [gogits/gogs#1337]
After a user is deleted all the issues that contain comments from that user will become corrupt and start giving error 500 as a response to HTTP GET requests.

Temporary fix:
Edit the `comment` table in your `gogs` database and make sure that all rows have a `poster_id` field set to the ID of an existing user.

**Comment by Unknwon** [comment]
Thanks your feedback!

And please follow updates on https://github.com/gogits/gogs/issues/1419 :star:
