### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by simechiang** [gogits/gogs#1340]
I get a problem, I can not push any code to my server.
run the `git push --set-upstream origin feature/xxx`, then input my username with password.
```bash
$ git push --set-upstream origin feature/xxx
Username for 'http://host:port': username
Password for 'http://username@host:port': 
fatal: Authentication failed for 'http://host:port/xxx/xxx/'
```
Any body help me ?

**Comment by Unknwon** [comment]
Thanks your report!

I suppose you setup user as LDAP/SMTP or something else other than plain username/password?

Is this the case?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
