### ISSUE TITLE
commit中文乱码

### ISSUE THREAD

**Issue by meilihao** [gogits/gogs#1341]
Bug Description:

查看commit(`/:username/:project/commit/:commit_id`)发现一些commit里的中文是乱码,有些又是正常的.

乱码举例(正常注释应是`单位名称`):
```
+	t_name := ctx.R.FormValue("Name") //å�•ä½�å��ç§°
```

查看源文件(`/:username/:project/src/:commit_id/:file_path`),发现中文是正常的,用`git log`检查发现commit中文正常,再用`file`命令检查了相关源文件(commit里中文正常或不正常时的关联文件)编码都是"UTF-8 Unicode text".

Gogs Version : 0.6.1.0325 Beta
Git Version : 2.4.0
System Type : ubuntu 15.04 x64
Error Log : no

**Comment by linquize** [comment]
what is your platform: windows / linux?
locale?

**Comment by meilihao** [comment]
linux : ubuntu 15.04 x64

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=
```

**Comment by Unknwon** [comment]
Thanks your feedback!

There are some fixes in v0.6.3 release for this problem as an example of result: https://try.gogs.io/unknwon/diff-encoding/commit/8700bc8fd7a53d45a0eb06a74a3ceeb2664015dd 

Would like mind to push your repository to https://try.gogs.io and see if problem still exists(or upgrade Gogs should also work)?

**Comment by meilihao** [comment]
It,s OK now.Thanks!

**Comment by weihoop** [comment]
windows下，下载zip包，用360压缩打开没有乱码。不过下载tar.gz包，还是空包。

**Comment by Unknwon** [comment]
@weihoop can you reproduce this on https://try.gogs.io ?
