### ISSUE TITLE
issue 很多的时候没有分页

### ISSUE THREAD

**Issue by zileyuan** [gogits/gogs#1342]
显示不全

**Comment by linquize** [comment]
issue list no pagination if too many issues

**Comment by Unknwon** [comment]
Hi @zileyuan , with new code in `develop` branch, this issue should be fix. You can also test on https;//try.gogs.io .

**Comment by Unknwon** [comment]
https://try.gogs.io/unknwon/gogs/issues

**Comment by Unknwon** [comment]
Closed as implemented. :octocat:
