### ISSUE TITLE
Support for Synology Nas

### ISSUE THREAD

**Issue by Solido** [gogits/gogs#1344]
Since GoGs is an autonomous low resources system, a Nas is a perfect place to put it in so we even have the security of multi disk. We may already deploy it but Synology offers a plugin system, easy to setup. I'm sure it can help the fast growing pace of GOGS and it would also be my best case for use.

**Comment by Unknwon** [comment]
Hi @Solido , thanks your feedback!

As I did some googling and found out that Synology Nas is a hardware? So, hmmm... it's more likely a feature request for Go to support it's architecture.

**Comment by tboerger** [comment]
Please take a look at https://github.com/SynoCommunity/spksrc/issues/1522

**Comment by Unknwon** [comment]
Oh, wow, thanks @tboerger !

**Comment by Unknwon** [comment]
Hmm, I think you should keep track on upstream, there is very little (nothing) we could do?
