### ISSUE TITLE
Delete/Add a user via API

### ISSUE THREAD

**Issue by uncled1023** [gogits/gogs#1345]
Currently I am using my SMTP db to allow users to authenticate, while disabling registration.  When they login for the first time it will add them correctly, but there is no mechanism for their account to be deleted besides them deleting it from the gogs interface.  If they delete their SMTP account, I would like to be able to delete their git account as well.  

I tried doing a post command to [url]/user/security/delete but it requires a csrf which I can't get if I don't generate the full html of the page.  

Do you think we could add an API command to allow the administrator to delete users?

Thanks!

**Comment by kernel164** [comment]
+1

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/go-gogs-client/wiki/Administration-Users
