### ISSUE TITLE
Issue adding webhooks

### ISSUE THREAD

**Issue by CTrauma** [gogits/gogs#1346]
I'm trying to add a webhook to test out the taiga integration and keep getting

```
template: repo/settings/hook_gogs:1:63: executing "repo/settings/hook_gogs" at <eq .HookType "Gogs">: error calling eq: invalid type for comparison
```

Is there some kind of cast that needs to take place or is there a missing function that has to do the compare of the data type? I'm on the latest development branch, but I get the same result from stable.

**Comment by r1se** [comment]
I have this problem too.
Latest stable version gogs, and taiga.

**Comment by Unknwon** [comment]
Thanks feedback for you both!

Would you mind to test on https://try.gogs.io again and see if problem has been solved?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
