### ISSUE TITLE
Lost the repository after doing a push

### ISSUE THREAD

**Issue by vantt** [gogits/gogs#1348]
I am using gogs 0.6.1.
I did a push to gogs and it was completed successful. After that I went to gogs and click on Releases menu (on the right sidebar) to create a new release and got an 500 error.

After a few browser refresh, access to my repository gave a 404 error. I went to the Organization page, it show total repositories is 6, but actually display 5 repositories. Re-create a new repo with the same name got an error which told the repository name already existed.

Thanks.

**Comment by vantt** [comment]
I temporary can solve the 404 problem. My repository originally was belonged to a user. After that, I moved it to an organization (before doing the steps I listed above) . But after investigate the database, I set is_private = 0 in the repository db-table, and now I can access to this repo. But access to Releases feature still giving 500 error.

Thanks.

**Comment by vantt** [comment]
I can now temporary fix the 505 error. As said above, the repository was originally belong to other user (Which is now deleted. I transferred this repository to a new-created organization and delete original user). 

By updating the publisher_id to an user-id (which is still exist)  I now can access to Releases page. By the way, I now don't see the New Release button.

Thanks

Thanks

**Comment by vantt** [comment]
By manually insert a record into table access I can now access to New Release button.

I think the system did something inconsistency when doing transfer the ownership from a normal user to an organization. Before doing that, everything was very normal.

Thanks.

**Comment by Unknwon** [comment]
Thanks your report!

> to create a new release and got an 500 error.

We need to log info for this 500 error in your console or `path/to/gogs/log/gogs.log`. Only having 500 is debugging based on guess... :flushed:

**Comment by Unknwon** [comment]
Also, it would be much more helpful if you don't mind upgrade Gogs to `master` branch.

Thanks again!

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
