### ISSUE TITLE
Is it ok to use SQLite3 now?

### ISSUE THREAD

**Issue by crocket** [gogits/gogs#1349]
There has been a lot of SQLite3 issues around Gogs.
While it is convenient to just use SQLite3, I'm afraid of it.

Is it safe to use SQLite3 now?

**Comment by linquize** [comment]
What kind of problem did you encounter?

**Comment by crocket** [comment]
I haven't encountered a problem yet because previously reported SQLite 3 issues scared me.

**Comment by Unknwon** [comment]
SQLite3 is always in the official support, and all problems have been reported is about session transaction, which can be done another way, no data damage by using SQLite3.
