### ISSUE TITLE
Webhook doesn't deliver any data

### ISSUE THREAD

**Issue by Cysioland** [gogits/gogs#1351]
While integrating Gogs with Drone CI, I encountered a problem. Despite `.drone.yml` file being pushed to the target repository, Drone still didn't react.
I checked nginx log, and webhook call ended with 400 Bad Request error.

So I set up another hook, which purpose was to log every request POST and GET data to a file. And it turned out, that Gogs doesn't send **any** data with that hook at all. Nothing. Just empty hook.

**Version**: 0.6.1.0325 Beta

**Comment by Cysioland** [comment]
x-www-form-urlencoded hooks work, json hooks don't

**Comment by Unknwon** [comment]
Thanks your feedback!

I've tested webhook in type JSON, and it does not occur the problem you describe.

Would you like to upgrade to `develop` branch and test again so it's easier for us to debug on it?

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
