### ISSUE TITLE
You're not dogfooding

### ISSUE THREAD

**Issue by markshep** [gogits/gogs#1353]
Ironically you're using GitHub to host a GitHub replacement.  Why are you not hosting gogs development on a gogs instance?  Is it not stable enough for that yet?

**Comment by theroyalstudent** [comment]
I'm sure Gogs isn't hosted on an Gogs instance as there aren't the 'Issues' feature yet, like the one we have here...

**Comment by topherredden** [comment]
Gogs is an app, not free storage. Where would they host gogs for free, for everyone? You offering markshep?

**Comment by Unknwon** [comment]
Hmm... @theroyalstudent made a good point, thanks!

And there is actually an example of Gogs hosts Gogs... https://try.gogs.io/unknwon/gogs :joy:

**Comment by GrayCoder** [comment]
@markshep I agree that the project probably should eventually host itself, but I also think it solves a different problem than github. Some people/teams might want their own locally hosted version of Github. That's basically what gogs is, plus it's good to see projects trying to create open source alternatives.

**Comment by kasoki** [comment]
Don't think it's a good idea, you won't get nearly as much attention from random developers. Even Gitlab is still hosted on Github: https://github.com/gitlabhq/gitlabhq

**Comment by denisdulici** [comment]
@kasoki GitLab says it just a canonical source and the original one is hosted on GitLab.com

**Comment by manfer** [comment]
@denisdulici The gitLab source in github is the CE (community edition) version. Installation from source requires a clone of the github repo from one of the stable branches or from the master branch if you want to test latest features (not recommended for production).

It is possible they do the development on their own server and only push features to github when they want. A server where they probably have their private versions of the app. But for community collaboration looks github is what they are using.

**Comment by pchaganti** [comment]
Hosting on github is probably the best way to get attention from users/devs that are looking at alternatives ways of hosting git repos, at least for now.

**Comment by codeskyblue** [comment]
Agree to keep code in github and Sync code to gogs.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
