### ISSUE TITLE
Show raw file?

### ISSUE THREAD

**Issue by theroyalstudent** [gogits/gogs#1354]
It does not seem to be working. Any fix? Running on 20150707 (`develop` branch) here :)

http://git.theroyalstudent.com/theroyalstudent/romstats-server/src/master/README.md

**Comment by ooxi** [comment]
Do you have any kind of access control or URL rewriting in place? It's not possible to visit anything below http://git.theroyalstudent.com/theroyalstudent/romstats-server/src/master/

**Comment by theroyalstudent** [comment]
Nope...

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name git.theroyalstudent.com;

	proxy_set_header X-Real-IP  $remote_addr; # pass on real client IP

	location / {
		proxy_pass http://0.0.0.0:3000/;
	}
}
```

**Comment by Unknwon** [comment]
Sorry, it seems your URL is for view rendered file, the correct URL for raw file is for example: https://try.gogs.io/unknwon/gogs/raw/master/README.md , where replace `src` with `raw`.

**Comment by stdhi** [comment]
there will be a problem, the markdown file can not rendering the link, such as /images/1.jpg will be parsed into https://gitlab.grepcode.cn/xxx/doc/raw/master/images/1.jpg. and the preview can not display the image.
