### ISSUE TITLE
Failing Build

### ISSUE THREAD

**Issue by 0x42424242** [gogits/gogs#1357]
**OS:** Debian Jessie x64 
**Commands:** 
```
./assemble_blocks.sh docker_gogs w_db option_db_mysql
Copying blocks/docker_gogs/Dockerfile to docker/Dockerfile
Adding blocks/w_db/fig to fig.yml
Adding blocks/option_db_mysql/config to conf.tmp
Adding blocks/option_db_mysql/fig to fig.yml
Creating docker/init_gogs.sh
Removing temporary GoGS config
```
`sudo fig up`

**Output:**
```
....
Step 17 : RUN go build github.com/gogits/gogs
 ---> Running in e9533b38779d
# github.com/msteinert/pam
../../msteinert/pam/transaction.go:3:31: fatal error: security/pam_appl.h: No such file or directory
 //#include <security/pam_appl.h>
                               ^
compilation terminated.
Service 'gogs' failed to build: The command [/bin/sh -c go build github.com/gogits/gogs] returned a non-zero code: 2
```

**Comments:**
I think the issue is pretty self explanatory so I won't add much more here. I did some research and found I possibly needed 'libpam0g-dev' installed. Installing this and reattempting installation still failed. 

Any ideas?

Thanks

**Comment by Unknwon** [comment]
Have remove `github.com/msteinert/pam` dependency by default, should build easily right now! Thanks your feedback!

**Comment by Unknwon** [comment]
Have remove `github.com/msteinert/pam` dependency by default, should build easily right now! Thanks your feedback!
