### ISSUE TITLE
Constructing SSH address with default port error

### ISSUE THREAD

**Issue by coenm** [gogits/gogs#1361]
Gogs renders a wrong ssh address to clone the respository. It is not prefixed with "ssh://" and the domain and path are sperated by ":" instead of a "/".

**Comment by Unknwon** [comment]
Commented on your PR. :dizzy:

**Comment by wqweto** [comment]
For ssh links to work it seems that `gogs-repositories` has to be home directory of `git` or any other `setting.RunUser` which is weird.

There is no way to specify a directory beneath `setting.SSHDomain` that could be symlinked to `gogs-repositories`. I tried putting it in `DOMAIN = server:gogs-repositories` but this produces invalid ssh links in the end.

**Comment by tboerger** [comment]
You can put the repositories whereever you want, you just need to tell gogs where they are. The SSH routes are always the same, but this is related to the magic within authorized_keys.

**Comment by wqweto** [comment]
Any pointers/what to search for on the topic of "the magic within authorized_keys"?

**Comment by tboerger** [comment]
Just take a look at the generated ~/.ssh/authorized_keys, this is openSSH magic. It's limited to specific commands like the gogs handler (which knows the path to the repositories from the configuration of course)

**Comment by wqweto** [comment]
Thank you, I will.

**Comment by Unknwon** [comment]
Close for now and open for continuing discussion.
