### ISSUE TITLE
Is this repo dead? It looks like the main developer doesn't care at all

### ISSUE THREAD

**Issue by zenati** [gogits/gogs#1363]
Is this repo dead? It looks like the main developer doesn't care at all neither about issues nor new features. If it's the case, may be putting a "Maintainers Wanted" in the Readme could be a good idea. With so much stars, it's a pity that this project is still not taking of seriously.

**Comment by Aidoboy** [comment]
The main developer, Unknwon, made a commit 5 days ago to master, 4 days ago to develop, and 9 days ago to feature/pull_request. I would say not.

**Comment by FSMaxB** [comment]
@zenati The owner just got back a few days ago, see https://github.com/gogits/gogs/issues/1304

**Comment by Unknwon** [comment]
Hi all, thanks for asking and sorry for a late response. 

Really appreciate for all who love Gogs, it's the greatest honor we've got so far! :grinning:

And of course, Gogs is not dead. :dizzy:
