### ISSUE TITLE
Inconsistent UI

### ISSUE THREAD

**Issue by kasoki** [gogits/gogs#1366]
Why does the look and feel of gogs change if you visit the "Issues" page?

The usual look:
![The usual look](https://monosnap.com/file/2yrtriv4OEQdlzVE6UvqV9jwZz5bx2.png)

Issues page:
![Issues](https://monosnap.com/file/2iMpdUaWT5nwleebB5bGKbU4BpbsgN.png)

EDIT:

Some minor inconsistencies:
* Submenu disappears when you select the "Commits" page
* Menus are always at the left except for Settings and Admin panel

**Comment by Aidoboy** [comment]
The login page is different too.

**Comment by KevinHivert** [comment]
The commits page is also different. No more submenu (source / commits / issues) at all.

**Comment by linquize** [comment]
There is `issue2` handler which is WIP that has a consistent theme

**Comment by Unknwon** [comment]
Duplicated to #650
