### ISSUE TITLE
Screencast Install Gogs

### ISSUE THREAD

**Issue by jniltinho** [gogits/gogs#1367]
Screencast Install Gogs on Ubuntu 14.04 64Bits (PT-BR)

https://www.youtube.com/watch?v=DFNifgEHOzk

**Comment by Unknwon** [comment]
Thanks, has been added to README!

**Comment by jniltinho** [comment]
Script Install
https://gist.github.com/jniltinho/280573e10206e31ab1c7

**Comment by Unknwon** [comment]
@jniltinho thanks your info!

BTW, it can be updated to v0.6.3 release now.

**Comment by jniltinho** [comment]
OK, Ubuntu now -> https://gist.github.com/jniltinho/280573e10206e31ab1c7

:+1:

**Comment by Unknwon** [comment]
Awesome, thanks!
