### ISSUE TITLE
Adding Team Member to Owners Hangs

### ISSUE THREAD

**Issue by andrewrynhard** [gogits/gogs#1369]
As the title describes, GoGS hangs on a blank page when trying to add a user to the `Owners` team. Adding a repository to a team results in a blank page as well.

````
Gogs · Version: 0.6.1.0714 Beta 
Go1.4.2
````

**Comment by pigulon** [comment]
I can confirm this happening on my instance as well.  Using the SQLite3 backend... not sure if it helps.

**Comment by arynhard** [comment]
@Unknwon : I would like to help with this issue. I have repositories that I cannot push to because of this bug. I don't have time to track down where the issue might be. Could you point me to the code that is responsible for handling the `Add Team Member` option?

**Comment by Unknwon** [comment]
Hi @arynhard , thanks your feedback!

Are you using SQLite3 as database as well?

**Comment by arynhard** [comment]
Hello @Unknwon. I am using PostgreSQL

**Comment by Unknwon** [comment]
> As the title describes, GoGS hangs on a blank page when trying to add a user to the Owners team. 

I did test on SQLite3 and didn't hang both add user to a normal team or `Owners` team. Do you have more specific details/steps to reproduce...?

> Adding a repository to a team results in a blank page as well.

I've reproduced this error but just to make sure we are getting into same issue, is your Gogs log shows there is panic about `nil pointer`?

Thanks!

**Comment by arynhard** [comment]
@Unknwon : I reinstalled and now I can add a user to the `Owners` team. Unfortunately I can't reproduce it. I was able to reproduce a hanging page when adding a repo to a team. If by logs you mean the ones in  `github.com/gogits/gogs/log` I saw no mention of a nil pointer.

**Comment by Unknwon** [comment]
@arynhard I see. Thanks for your info!

Keep me update if anything goes wrong again. :grinning:

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
