### ISSUE TITLE
git clone https:xxx error

### ISSUE THREAD

**Issue by polaris1119** [gogits/gogs#1371]
remote: Counting objects: 3964, done.
remote: Compressing objects: 100% (3138/3138), done.
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOFs:   2% (80/3964)
fatal: index-pack failed

**Comment by Unknwon** [comment]
Thanks your feedback!

It is because your push contains a large amount of objects.

See http://stackoverflow.com/questions/17683295/git-bash-error-rpc-failed-result-18-htp-code-200b-1kib-s for solutions.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
