### ISSUE TITLE
SMTP authentication fails after password change within Gogs

### ISSUE THREAD

**Issue by nurtext** [gogits/gogs#1374]
Hi all,

I've enabled the SMTP authentication provider and login as well as auto profile creation works so far. 

But if a user wants to change his password within Gogs, logins with the new password aren't possible. Instead, he gets a 500 message shown. But if he logs in with the old password (which is actually the one for his mail account) it works fine.

In my opinion the behavior of the SMTP authentication and auto profile creation should be changed to something like this:

1. First time login with email address and email password using SMTP authentication creates a new profile (provisoning)
2. If the user changes his/her email address and/or password from within Gogs, the authentication source for the particular user should be set to local instead of SMTP, because the provisioning has already been made within Gogs. This could easily be done by changing the columns `login_type` and `login_source` in table `user`.

Btw: I already tried to change the authentication source using an admin account in the backend, but this doesn't seem to work as well. See #1375 for more details.

**Comment by stonerl** [comment]
Another (better) option would be, to disable password change for this authentication source

**Comment by Unknwon** [comment]
I agree with @stonerl , same apply for LDAP in another issue thread.

**Comment by nurtext** [comment]
I disagree, because the user should always be capable of changing his password, even if the original authentication source is SMTP or LDAP. Changing the email password has more drawbacks than just changing the password for Gogs. E.g. the user needs to enter the new password on all devices he has setup the email account.

**Comment by stonerl** [comment]
@nurtext I disagree I for example use the SMTP authentication to allow users to use Gogs to have just one username and password for all services. Our university has a destingushed site where users can change there password. 
Furthermore when a user does not have his university account I don't want him to be able to login anymore. If want this I as an admin would change his authentication source deliberately. I think it is a bad idea to let user change the authentication source just by chanheing his password in gogs.
Also it would confuse users. I tell them they can use their email account to login. Then they change the password in gogs, believing that they changed there password for all accounts.

**Comment by nurtext** [comment]
@stonerl Good point.

**Comment by Unknwon** [comment]
Now on `develop` branch, non-local users are not allowed to change their password.

**Comment by janh** [comment]
To improve user experience, a possibility to add a link to the actual password management page (of a single sign-on system) would be nice. The URL could be set up in the settings of each authentication source.

**Comment by Unknwon** [comment]
@janh Thanks for the suggestion but I think it does not matter as Gogs is not a public site provider, you always know you're logging with what account.

**Comment by Unknwon** [comment]
Close as implemented.
