### ISSUE TITLE
Admin can't change "Authorization Source" for users in Gogs

### ISSUE THREAD

**Issue by nurtext** [gogits/gogs#1375]
Hi all, 

this is an addition to #1374. I've setup and SMTP Authentication source to allow users with valid email address to login into Gogs. This works well.

But if I try to change the "Authentication Source" for a paticular user from the "Edit Account" screen, the changes won't get saved. I had to manually change the columns `login_type` and `login_source` in table `user` to get this working.

Cheers,
Cedric

**Comment by Unknwon** [comment]
Somewhat I believe this has been implmented..
