### ISSUE TITLE
使用0.6.1.0714 Beta，发现三个问题

### ISSUE THREAD

**Issue by allan852** [gogits/gogs#1376]
1. 在组织中的仓库无法添加管理协作者，将仓库转移到个人后，可以添加
1. 组织中新建的团队不能添加仓库
1. 组织中Owners团队不能移除成员

版本： 0.6.1.0714 Beta

以上都是500错误。

**Comment by Unknwon** [comment]
Thanks your feedback!

> 以上都是500错误。

What is the log for 500 error?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
