### ISSUE TITLE
配置文件不起作用

### ISSUE THREAD

**Issue by DuanPengfei** [gogits/gogs#1378]
二进制安装方式，在 custom/conf/app.ini 中修改配置后重启没有任何错误，但是配置没有生效。

**Comment by allan852** [comment]
遇到同样的问题。
我是源码方式安装，重启后生效。

**Comment by Unknwon** [comment]
Hi thanks your feedback!

Should restart Gogs after change configuration, did you do that?

**Comment by DuanPengfei** [comment]
@Unknwon Yes, I did. And I have already given in the problem description.

**Comment by Unknwon** [comment]
@DuanPengfei OK... go to `/admin/config` and see if Gogs recognized your changes in config file.

**Comment by DuanPengfei** [comment]
@Unknwon My Gogs binary in the path `/home/username/gogs` and  the `custom/conf/app.ini` absolute path is `/home/username/gogs/custom/conf/app.ini`.

And I don't understand where is the path '/admin/config'? Is it refer to in the installation directory `admin/config`? Or in my root directory `/`?

**Comment by Unknwon** [comment]
Your files location looks right.

`/admin/config` is the URL.

And what config option did you change? Post corresponding content maybe helpful!

**Comment by DuanPengfei** [comment]
```
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE = sqlite3
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD =
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[server]
DOMAIN = code.xxx.cn
HTTP_PORT = 3000
ROOT_URL = https://code.xxx.cn/

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info

[security]
INSTALL_LOCK = true
SECRET_KEY = uULMyh73awvq4qF

REQUIRE_SIGNIN_VIEW = true
ENABLE_CACHE_AVATAR = true
DISABLE_REGISTRATION = true
```

This is my `app.ini` content. But Gogs still allow to registration.

<img width="370" alt="qq20150723-1 2x" src="https://cloud.githubusercontent.com/assets/4469502/8849531/15da5fe8-3173-11e5-9dfd-13aa5ec50859.png">

Did I made some mistakes?

**Comment by Unknwon** [comment]
Yes, you did. `DISABLE_REGISTRATION` in under `service` section, not `security`.

**Comment by DuanPengfei** [comment]
Oh, I am so foolish. I misunderstand the `[]` is comments, actually it is a block. Thank you.

**Comment by Unknwon** [comment]
No worries, it's common... :joy:
