### ISSUE TITLE
Running gogs on OS startup?

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#1381]
First, thank you for the awesome work on Gogs!

Gogs is pretty easy to deploy, since we just have to run `gogs web` on console to get it running.

My problem is I don't know how we can configure it to autostart on OS startup (running Windows Server here), since it isn't a OS service.

Just want to know what approach do you use.

---

Another thing:

Windows user names are case insensitive, but Gogs gives me an error when I sign in on Windows as "User" and `app.ini` point to "user" or vice-versa.

**Comment by andreynering** [comment]
Got it working with this tool: http://www.nssm.cc/

**Comment by Aidoboy** [comment]
I'm curious about how to do it on a Raspberry Pi

**Comment by Duckbrain** [comment]
@Aidoboy Assuming you are running Raspian, you can use the init.d file included in the project

https://github.com/gogits/gogs/blob/master/scripts/init/debian/gogs

**Comment by Aidoboy** [comment]
Awesome! This will solve a lot of problems for me! THank you so much, @Duckbrain !

**Comment by Unknwon** [comment]
@andreynering have your issue been solved?

**Comment by andreynering** [comment]
@Unknwon Thank you for asking.

As I said in a former comment, I used this open source utility (http://www.nssm.cc/) to register the Gogs executable as a Windows service, and it worked very well. I've used it in my own Go projects, too. =)

Maybe we could pack Gogs in an installer in Windows, and automate the process of registrating it as a service.

**Comment by Unknwon** [comment]
@andreynering thanks the info!

**Comment by ZhuBicen** [comment]
How to do it on linux? for root I can add command to /etc/rc.local. But gogs need to be running by "git" user

**Comment by Unknwon** [comment]
@ZhuBicen `export USER=git`.

**Comment by ZhuBicen** [comment]
Thank you. I got a script in FAQ. It works perfectly
