### ISSUE TITLE
No closed issues count when filtered

### ISSUE THREAD

**Issue by alexclifford** [gogits/gogs#1385]
By default the issue count shows open issues. If you change the filter to closed issues it shows content on the right but the counters on the left do not change. This is a little misleading:

![gogs_issue_open_closed_count](https://cloud.githubusercontent.com/assets/184942/8826740/ea9e1042-30cb-11e5-90bb-6777bed8fccc.png)

**Comment by Unknwon** [comment]
Please checkout new UI for this page!

And only shows open issues count is on purpose actually..
