### ISSUE TITLE
Failed migration leaves project which can't be opened

### ISSUE THREAD

**Issue by kordianbruck** [gogits/gogs#1386]
Bug Description: while importing a project from bitbucket somehow the server died because of the action taking very long and the reverse proxy. Anyways this leaves me with a project I can't open up because of a 500 error. So it can't be deleted nor overwritten. Any suggestions on how to delete it would be great!

Gogs Version: 0.6.1.0325 Beta
Git Version:  1.7.10.4
System Type: docker / debian jessie
Error Log:
The *gogs.log* contains the following line:
```
[repo.go:281 func·008()] [E] GetTags: 
```

By the way: doing the migrations asynchronously would be a great idea!

**Comment by Unknwon** [comment]
It is now possible to delete repository in admin panel.
