### ISSUE TITLE
Dump database and import to other supported databases

### ISSUE THREAD

**Issue by crocket** [gogits/gogs#1388]
Since SQLite 3 looks ok, I want to remove PostgreSQL which is another piece of software that adds complexity to my system administration.

http://gogs.io/docs/intro/ doesn't tell me how to migrate gogs database.

Can anyone document how to do it on the website?

**Comment by Unknwon** [comment]
Hmm... I think it's kind of database migration thing than a Gogs feature. 

Maybe dump SQL from PostgreSQL and import to SQLite3?

Did some googling: http://manuel.manuelles.nl/blog/2012/01/18/convert-postgresql-to-sqlite/

**Comment by crocket** [comment]
I read the article, and it doesn't apply well to gogs.
It seems like a non-intuitive administration task.

**Comment by Unknwon** [comment]
The article link I posted just an example that how migrate between databases.

Right now Gogs does not have somewhat in the middle format to support this kind of operation.

**Comment by crocket** [comment]
I spent some time on fiddling with PostgreSQL and SQLite 3 and migrated the database.
But, I am not sure whether the migration caused any glitches.
Perhaps, it should become a feature request.

**Comment by Unknwon** [comment]
I've changed title, please check and see if you're OK with it.

**Comment by crocket** [comment]
I'm ok with it.

**Comment by slaskis** [comment]
Could [this](https://github.com/go-xorm/cmd/blob/master/README.md#dump) be used perhaps?

**Comment by lunny** [comment]
This is an interesting question. The dump will automatically generate create table, create index and insert into SQLs. For all kind of databases, the differences between them are  create table and create index.

**Comment by jdroot** [comment]
Would there be a downside to `gogs dump` dumping serialized structs instead of SQL? An import/restore feature could then be created that was database agnostic.

**Comment by lunny** [comment]
I will try to implement this on xorm via `engine.DumpAll(w, dbtype)`. @Unknwon

**Comment by Unknwon** [comment]
> Would there be a downside to gogs dump dumping serialized structs instead of SQL? An import/restore feature could then be created that was database agnostic.

@jdroot SQL isn't 100% compatible across all types of databases, but Gogs understands its convetion.

@lunny Is it possible to dump SQLite3 and import to MySQL?

**Comment by lunny** [comment]
@Unknwon I think Yes. The new `DumpAll` method could dump SQL to any xorm supported databases.

**Comment by Unknwon** [comment]
@lunny that sounds cool!

**Comment by lunny** [comment]
It's difficult to convert sqlite's datatypes to mysql's datatypes. There are some work to do.

**Comment by Unknwon** [comment]
> It's difficult to convert sqlite's datatypes to mysql's datatypes. There are some work to do.

That's why I suggest this issue to dump a in-middle format specifically for Gogs purpose.

**Comment by lunny** [comment]
Another idea, we can generate table creation SQL according Go's struct not from database. And generate Insert SQL from database. I will try this way later.

**Comment by Unknwon** [comment]
> Another idea, we can generate table creation SQL according Go's struct not from database.

I think it is a good idea.

**Comment by lunny** [comment]
I just pushed a commit to xorm 4bcbb95688b3cdb1635915ee8aa78d7f17e31a25, now I think Gogs could implement this feature via `DumpTables`, the usage is below:

```Go
var tbs = []interface{}{
		new(AccessToken),
		//new(DeployKey),
		new(Collaboration),
		new(Notice),
		new(Access),
		new(Label),
		new(EmailAddress),
		new(TeamRepo),
		new(TeamUser),
		new(OrgUser),
		new(HookTask),
		new(UpdateTask),
		new(Webhook),
	}

	var tables []*core.Table
	for _, tb := range tbs {
		tables = append(tables, engine.TableInfo(tb))
	}

	err = engine.DumpTables(tables, os.Stdout, core.MYSQL)
	if err != nil {
		panic(err)
	}
```

@Unknwon

**Comment by Unknwon** [comment]
Thanks, how to import back?

**Comment by lunny** [comment]
`engine.Import` or `engine.ImportFile`.

**Comment by Unknwon** [comment]
Got it, I'll try that.

**Comment by jdroot** [comment]
@Unknwon What I meant by my comment earlier was something like the following. Basically, don't deal with SQL at all. (Code might be bad, I am very new to Go)
```go
func DumpAllAsGob(filePath string) error {
	f, err := os.Create(filePath)
	if (err != nil) {
		return err
	}
	defer f.Close()

	enc := gob.NewEncoder(f)

	for _, table := range tables {
		slice := reflect.MakeSlice(reflect.SliceOf(reflect.TypeOf(table)), 0, 0)
		slicePointer := reflect.New(slice.Type())
		slicePointer.Elem().Set(slice)
		sliceInterface := slicePointer.Interface()
		err = x.Find(sliceInterface)
		if (err == nil) {
				enc.Encode(slicePointer.Elem().Interface())
		} else {
			return err
		}
	}
	return nil
}
```

**Comment by Unknwon** [comment]
@jdroot Yes, that is my original thought. But if XORM already works with export and import, I don't think gob thing is worth investigating.

**Comment by FyinInc** [comment]
+1

**Comment by bkcsoft** [comment]
This thingie here kinda does that (if you edit the config-file or pass a new one as a flag) https://github.com/gogits/gogs/compare/develop...bkcsoft:feature/restore-dump *coughing*

**Comment by aventrax** [comment]
hello. I'd want to convert ftom mysql to postgresql. Is there a way to do so? In case there is not,  and because my gogs is pretty empty (just addes 20 commits to 2 repos), what would I lost to start from scratch? Would be the commit's comments visible to a new gogs deploy with the same git repos?

**Comment by Unknwon** [comment]
Hi @aventrax , forgot to update this issue. This feature has been supported quite a while, you can read more about how to do that: https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991

**Comment by aventrax** [comment]
@Unknwon many thanks, i migrated successfully!
