### ISSUE TITLE
packager 上 0.6.1 版本应该安装哪一个？

### ISSUE THREAD

**Issue by ngloom** [gogits/gogs#1389]
hi，无闻，想省事点直接从packager 上apt-get安装，我看到github里3个月前就已经 release了0.6.1版本，但我看到packager上的0.6.1版本在github release之后，还有很多build，其中还有几个状态是fail和partial fail, 现在我有点不知道应该装哪一个了, 还是说保险点直接装个0.6.0版本？
救助

**Comment by Unknwon** [comment]
Actually I'm not quite sure how packager.io works, but I suppose choose any one that shows `success` should get you into right path.

**Comment by ngloom** [comment]
好的，感谢无闻。

**Comment by Unknwon** [comment]
No problem!
