### ISSUE TITLE
Copy link button

### ISSUE THREAD

**Issue by wqweto** [gogits/gogs#1396]
... seems to be implemented w/ Adobe Flash Player and the latter often gets disabled for security reasons. This is the result on Chrome. The button beneath the player can be clicked but nothing happens.

![Flash](https://dl.unicontsoft.com/upload/pix/ss_gogs_flash.png)

**Comment by tboerger** [comment]
This is an external script... Maybe it can be configured different with a better fallback detection.
This is used: http://zeroclipboard.org/

**Comment by wqweto** [comment]
[Cut and Copy Commands](https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en) on Google Developers.

Firefox 41 seems to support these too.

**Comment by tboerger** [comment]
> Cut and Copy Commands on Google Developers.
> Firefox 41 seems to support these too.

That's absolute not an option, to quote the support: "IE 10+, Chrome 43+, and Opera 29+ support these commands. Firefox supports this but requires a preference change (See cut and copy commands here). Without this Firefox throws an error. Safari does not support these commands.". That new requirements are just a no-go for this kind of project.

**Comment by wqweto** [comment]
@tboerger: What kind of project is this? Can you just take a look how they did clipcopy on github.com... I bet there is no sign of Flash. (I'm positive as it works with Flash disabled in chrome)

**Comment by manfer** [comment]
If I'm not wrong github uses [zeroclipboard](http://zeroclipboard.org/) which fallback to flash when necessary. Which is exactly the one used on this project as @tboerger said. I suggest rereading his first message more carefully.

**Comment by manfer** [comment]
Current major version of zeroclipboard: 2.2.0
Version of zeroclipboard in github: 2.1.6
Major 1.x version of zeroclipboard: 1.3.5
Version of zeroclipboard in gogs: 1.1.1

Looks like the library needs to be updated.

But besides I'm not sure if zeroclipboard can work without flash. Maybe github is only using zeroclipboard as fallback if access to clipboard is not directly available on the browser.

**Comment by manfer** [comment]
@wqweto I can confirm Github uses the clipboard API from the browser (cut and copy commands as in the link you provide) when it is available and only fallbacks to zeroclipboard if it is not available. So doing something similar would be an enhancement for sure.

**Comment by manfer** [comment]
I link here the [discussion](https://github.com/zeroclipboard/zeroclipboard/issues/171) on zeroclipboard because it can contain useful info for ideas.

In this discussion @jonrohan github staff member provides a link to a gist with the [code (in coffescript) that github uses](https://gist.github.com/jonrohan/81085b119d16cdd7868a) which is a lot more readable than the obfuscated github javascript.

We must take in mind that github has in the repository pages two copy to clipboard buttons, one for the SHA1 and one for the textfield that contains the clone url.

For just a clone url textfield as gogs has some parts of the code will not be nedded.

**Comment by Unknwon** [comment]
@manfer thanks for your info!

**Comment by manfer** [comment]
I was wrong about the library used on gogs. The library that is being used is jquery zclip which is somehow related to zeroclipboard 1.x.

I have made a PR to add the copy command when the browser supports it.

I have not been able to make zeroclipboard 2.x work so I didn't changed the code and is still using zclip. I have added direct copy to clipboard without flash when the browser supports it.

**Comment by Fastidious** [comment]
Something like this would be great:

![d0a508dc-61d9-11e5-8769-b9c9ccb26bce](https://cloud.githubusercontent.com/assets/8352292/10089059/a687442e-62ed-11e5-9bd6-6540e557aa9a.png)

**Comment by Fastidious** [comment]
Just saw this on Hacker News today: https://github.com/zenorocha/clipboard.js. It relates.

**Comment by manfer** [comment]
> Just saw this on Hacker News today: https://github.com/zenorocha/clipboard.js. It relates.

Now go to the bottom of that page and look at the browser compatibility.

**Comment by Fastidious** [comment]
I see all browsers supported, but Safari, and I am on Safari and it works for me.

**Comment by manfer** [comment]
> I see all browsers supported, but Safari, and I am on Safari and it works for me.

Browser versions?????

Chrome 42+ Do you seriously think all people using chrome are using a version greater or equal to 42?

Firefox 41+ Which at most is 2 months old, maybe only one month. Do you really think all users of firefox had such a recent version?

Opera 29+. Just the same. It was released on May more or less.

IE9+ I don't exactly know which is the way how that library support all those versions. If it is a direct copy to clipboard without any user interaction in IE9, IE10, IE11. I doubt it though I'm not sure now.

I would like to test how it works when it can't copy though I can't test now.

**Comment by Fastidious** [comment]
Anyone using Gogs will most likely be using, or be willing to upgrade to, those versions. Anyone in my office (I work at a State university) is using a version higher than the one listed on that page, and they are developers, managers and secretaries. Where do you live, that everyone is so behind?

Latest Chrome under OS X is `45.0.2454.101` (no beta, no developer, but latest from https://google.com/chrome/). Safari 9 works just fine. See [browser market share](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0&qpob=UV+DESC) for some stats.

**Comment by manfer** [comment]
> Where do you live, that everyone is so behind?

It is not about where I live and where you live. It is about gogs being a web application used world wide and browsers having a specific world wide usage. Maybe you have to pay more attention to the browser market share graph you are linking and count which percentage doesn't meet that library requirements which is not little amount at all.

These means there are a lot of people arround the world behind those versions even if it sounds strange to you.

And I don't understand how it can sound so strange to you when firefox 41+ is a month old and opera 29+ 4 months old.

**Comment by Fastidious** [comment]
@manfer it is strange, because as I said, people who use `git` and `gogs` (tinkerers, to say the least) will have the latest browser running (many even nighties). Don't fool yourself, `gogs` is not Facebook--as in, not used by *almost* everyone (I do not use Facebook, but that's irrelevant).

Firefox seems to have a very short release timetable. Opera, I don't know. I care less about those two. :-)

**Comment by manfer** [comment]
> Firefox seems to have a very short release timetable. Opera, I don't know. I care less about those two. :-)

Maybe this is the problem. It seems you care only for yourself and that's not what a developer should do.

My opinion is that it is pretty soon to move to a library like that. Actual version of gogs already has copy&paste without flash and if it is not working as expected that's what should be corrected and enhanced if necessary.

**Comment by Fastidious** [comment]
I think we are having a language specific communication problem.

How is *this* working without Flash?

![screen shot 2015-09-30 at 18 13 24](https://cloud.githubusercontent.com/assets/8352292/10208114/022c0840-679f-11e5-96b8-17ba3a1d2f14.png)

I will agree to disagree, with the upmost respect.

**Comment by manfer** [comment]
If it is not working as expected that is what can be enhanced. I said on Chrome and that image is clearly Safari. And it maybe even fails on chrome but if it does that should be reported as a bug.

Points that should be taken into account:
* As of today there is not a solution that works everywhere. Not even the one you are suggesting.
* The one that you suggest works for you and that is why you prefer that one.
* The one you suggest is not going to work for some other people.

So if someone comes with a solution with the library you suggest and a fallback for older browsers I would like that solution too. But only the library you suggest is not something I would suggest to use.

**Comment by manfer** [comment]
In Chrome if I'm not wrong it works.

So your only problem is Safari. As Chrome works and you don't mind about Opera or Firefox.

**Comment by manfer** [comment]
Actually it already works in firefox 41+ version which is the version that has added copy to clipboard feature. And considering Opera seems to be using nowadays chromium engine and V8 I bet I will not be wrong if I say gogs is working correctly on Opera 29+ too.

So actually the problem is just Safari and probably IE.

**Comment by manfer** [comment]
@Unknwon I would suggest reopening this issue for discussion.

### Copy to Clipboard

For security reasons direct copy to clipboard has been not available from browser except using a third party extension like flash (or java if I'm not wrong). Flash trick is the one that has been widely used.

Recently a new [clipboard API](http://www.w3.org/TR/clipboard-apis/) has been proposed by W3C and is actually a Working Draft. Major browsers have already implemented -not sure if partially or totally- the API.

#### The problem

The flash trick consists of a flash transparent object in front of the button to handle the user click so to use this trick the flash object must be included on page load. In other words there is no way to try to use copy to clipboard API and if it fails fallback to flash trick.

#### Solution 1 (actually used)

By checking the browser agent in the server determine if the browser supports copy to clipboard and don't load flash in that case. *Actual browser agent check must be reviewed just in case it can be enhanced*

In case it doesn't support copy to clipboard use flash trick. *This must be enhanced to handle no flash available error. In this enhanced no flash handling the text should be selected showing a tooltip with the shorcut to copy.*

#### Solution 2

Use only copy to clipboard and if it fails just fallback to select the text and let the user copy to clipboard manually with mouse or with keyboard shortcut. This can be done with the library suggested by @Fastidious

**Comment by TheHowl** [comment]
![](http://i.imgur.com/c7NJRa2.gif)

1. Detect if the browser supports copy to clipboard without flash (using something similiar to https://gist.github.com/jonrohan/81085b119d16cdd7868a#file-supports_copy-rb with the other browsers). If it does, use clipboard.js.
2. Detect if the user has flash enabled using http://stackoverflow.com/a/4565606/5328069 - if it does, fallback to flash.
3. At last, if not even flash is installed, fallback to popup or something where text is selected and suggests the user to do "ctrl+c" to copy to clipboard.

**Comment by manfer** [comment]
That is Solution 1 which is being used currently and must be enhanced.

> Actual browser agent check must be reviewed just in case it can be enhanced

At least Opera must be added. I have already checked it is not working on Opera 29+ and added the code to repo.go that solves that case.

> This must be enhanced to handle no flash available error. In this enhanced no flash handling the text should be selected showing a tooltip with the shorcut to copy.

Ideally would be great if we can upgrade zclip 1.1 (previous name of zeroclipboard I think) to zeroclipboard 2.x. When I tried I couldn't because the input we need to copy is inside a hidden layer that is only visible on clicking a button. I didn't try to much because this is just a UI component and the UI is being updated. I will try again to upgrade the zeroclipboard library.

And we must use the onError from that library to handle flash not available. Selecting text and showing on a tooltip the shortcut "ctrl+c" or "command+c" will be enough.

**Comment by TheHowl** [comment]
oh wait, my bad. i didn't fully read your post (in the solution 1 :P)

**Comment by Unknwon** [comment]
How about https://github.com/zenorocha/clipboard.js ?

**Comment by tboerger** [comment]
> How about https://github.com/zenorocha/clipboard.js ?

That's a nice fallback for safari.

**Comment by Fastidious** [comment]
@Unknwon this has gone in a look to [my comment](https://github.com/gogits/gogs/issues/1396#issuecomment-144341468). Hahahahaha!

**Comment by Unknwon** [comment]
@Fastidious oops... how come I didn't notice...

**Comment by Fastidious** [comment]
@Unknwon not a biggie, it is a long thread. I like the approach clipboard.js takes.

**Comment by Unknwon** [comment]
Based on https://github.com/Semantic-Org/Semantic-UI#browser-support , I think https://github.com/zenorocha/clipboard.js is acceptable, but I just not sure does it behave the same in Safari if my Chrome has like version 30...

**Comment by Unknwon** [comment]
@manfer by reading the docs of https://github.com/zenorocha/clipboard.js , I think it uses the same API as you did in the PR?

**Comment by Unknwon** [comment]
>  but I just not sure does it behave the same in Safari if my Chrome has like version 30...

Based on https://github.com/zenorocha/clipboard.js/issues/2#issuecomment-143382834 , I think it behaves well on lower version of browsers.

**Comment by manfer** [comment]
> Based on zenorocha/clipboard.js#2 (comment) , I think it behaves well on lower version of browsers.

I have not doubt it works on older versions in a totally different way. In older version it is not a copy to clipboard button but selection of the text with a tooltip showing the shortcut the user must use to copy. It can't be anything different than that as copy to clipboard is only available in modern browsers with the new Clipboard API or in older browsers with a third party extension (flash or java, maybe silverlight exposes the clipboard too).

As I mention in a previous message
> Solution 2
> Use only copy to clipboard and if it fails just fallback to select the text and let the user copy to clipboard manually with mouse or with keyboard shortcut. This can be done with the library suggested by @Fastidious

It is of course an options if that is what is wanted. But it is not the same that is available just now.

**Comment by Unknwon** [comment]
@manfer Try create an empty repo on https://try.gogs.io , the clipboard.js  is used there see how it goes.

**Comment by manfer** [comment]
This is what I suggest.
http://jsfiddle.net/qyv5h73t/2/

(on chrome this test on jsfiddle on flash version doesn't work correctly. A mouseleave is happening on entering the invisible flash movie. But it works well outside of jsfiddle so shouldn't be a problem. I didn't figure out the reason why it fails. The difference is that in jsfiddle the code runs inside an iframe. On firefox works correctly in jsfiddle flash version)

Here is the code that can be tested outside of jsfiddle
```html
<!DOCTYPE html>

<html>

<head>

  <meta charset="UTF-8">

  <title>Testing zeroclipboard 2.x with clipboard.js</title>

  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/jquery.tipsy/1.0.2/jquery.tipsy.css" media="screen" />
  
  <style type="text/css">
    #popupcontainer {
      margin: 20px;
      position: relative;
      width: 30px;
    }

    #popup {
      position:absolute;
      width: 250px;
      padding: 20px;
      margin: 0;
      background: #fcfcfc;
      border: 1px solid rgba(0,0,0,0.3);
      display: none;
    }

    #textareacontainer {
      margin-top: 50px;
      margin-left: 20px;
    }
  </style>

</head>

<body>

  <div id="popupcontainer">

    <button id="showpopup">Popup</button>

    <div id="popup">
 
      <input type="text" id="tocopy" />

      <button id="btn" original-title="Click to copy" data-original-title="Click to copy" data-after-title="Copied!" data-tipsy-gravity="n" data-clipboard-target="#tocopy">Copy</button>

    </div>

  </div>

  <div id="textareacontainer">

    <textarea id="textarea" rows="10" cols="50" placeholder="You can paste here..."></textarea>

  </div>

  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.tipsy/1.0.2/jquery.tipsy.js"></script>
  
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js"></script>
  
  <script type="text/javascript" src="//cdn.rawgit.com/zenorocha/clipboard.js/master/dist/clipboard.min.js"></script>

  <script type="text/javascript">

    $(function(){

      // this will determined server side
      // by inspecting user agent
      // browser supports execCommand("copy") or not
      var IS_COPY_ENABLED = false;

      // tooltip on button
      $("#btn").tipsy({
        title: function() {
          return this.getAttribute('original-title');
        },
        fade: true,
        gravity: function () {
            return this.getAttribute('data-tipsy-gravity') || 'n';
        }
      }).on("mouseleave", function(event) {
        $(this).attr("original-title", $(this).data("original-title"));
      });

      // popup must be done with js and not with css
      $("#popupcontainer").hover(function(event) {
        $("#popup").show();
      }, function(event) {
        $("#popup").hide();
      });
      
      if ( IS_COPY_ENABLED ) {

        // zenorocha clipboard.js
        // when browser supports execCommand("copy")
        var clipboard = new Clipboard("#btn");
        clipboard.on("success", function(event) {
          $("#btn").tipsy("hide")
          .attr("original-title", $("#btn").data("after-title"))
          .tipsy("show");
        });

      } else {

        // zeroclipboard 2.x
        // when execCommand("copy") is not supported
        // and flash is available
        var client = new ZeroClipboard($("#btn"));

        client.on("copy", function(event) {

          var t = $("#tocopy").val();
          var clipboard = event.clipboardData;
          clipboard.setData( "text/plain", t );
          $("#btn").tipsy("hide")
          .attr("original-title", $("#btn").data("after-title"))
          .tipsy("show");

        }).on("error", function(event) {

          // zenorocha clipboard.js
          // when not flash available
          var clipboard = new Clipboard("#btn");
          clipboard.on("success", function(event) {
            $("#btn").tipsy("hide")
            .attr("original-title", $("#btn").data("after-title"))
            .tipsy("show");
          });

        });

      };

    });

  </script>

</body>

</html>
```

I will try to implement it on gogs code as soon as possible and PR.

**Comment by Unknwon** [comment]
@manfer thanks!

Here is the [code](https://github.com/gogits/gogs/blob/master/public/js/gogs.js#L627-L643) Gogs currently uses clipboard.js .

**Comment by manfer** [comment]
> Here is the code Gogs currently uses clipboard.js .

But where exactly is that code used? At least for me in repo pages the old theme is still used and it loads 'public/ng/js/gogs.js'  and not the file you link 'public/js/gogs.js.

Beside the button in the template 'repo/header_old.tmpl' is this one:

```
<button id="repo-clone-copy" class="btn btn-black left btn-right-radius js-copy-bind" data-copy-val="val" data-copy-from="#repo-clone-url" original-title="Copiar al portapapeles" data-original-title="Copiar al portapapeles" data-after-title="Copiado correctamente">Copiar</button>
```

which hasn't a class `clipboard`. So even if that code were loaded it will not be binded to any button in the page.

**Comment by Unknwon** [comment]
@manfer I have commented and mentioned you in comment above.

**Comment by zenorocha** [comment]
+1 for clipboard.js ;)

**Comment by net** [comment]
+1 zenorocha/clipboard.js

Copy to clipboard in one button is really not a requirement. Gogs as the modern git server interface it tries to be should really be moving away from flash. clipboard.js degrades nicely on buttons that don't support javascript clipboards.

**Comment by Unknwon** [comment]
@zenorocha :joy:

**Comment by Unknwon** [comment]
OK! It's now done via clipboard.js with new UI! https://try.gogs.io/gogs/gogs

**Comment by ChangePlaces** [comment]
like it muchly :+1:

**Comment by zenorocha** [comment]
lol

**Comment by Unknwon** [comment]
@zenorocha thanks for the great thing!

**Comment by Unknwon** [comment]
Close as fixed.
