### ISSUE TITLE
Admin should be able to see private repositories

### ISSUE THREAD

**Issue by 94else** [gogits/gogs#1401]
管理员无法查看别人创建的私有仓库

**Comment by Unknwon** [comment]
It is similar to https://github.com/gogits/gogs/issues/493 , which asks for edit settings of all repositories.

But from my current point of view, it will never possible for admin see any repository in normal page(`/:username/:reponame`), but it's OK in admin dashboard(`/admin/reposiotry/:repoid`).

**Comment by keenwon** [comment]
+1
管理应该有最高权限，方便团队开发

**Comment by Unknwon** [comment]
@keenwon What I'm thinking is admin can view/edit repo settings on admin dashboard, but to view actual content of the repository, add as collaborator can fix your concern.

**Comment by keenwon** [comment]
@Unknwon 这要看你们的产品定位了，你们想实现的是类似github的git平台，还是用于企业开发的内部系统，对于内部系统，管理员应该拥有最高权限。即使是一款公开的产品，用户出于“恶意”创建的仓库，管理员也应该有权限进行操作。至少我是这么感觉的...

**Comment by Unknwon** [comment]
> 用户出于“恶意”创建的仓库，管理员也应该有权限进行操作。至少我是这么感觉的...

In this case, yes admin can delete repo on the admin dashboard...

I just think admin can definitely have whatever power it needs to have on admin dashboard.

But just don't mixed up with normal access control system like you can somehow view a private repo which you don't completely has access to.

**Comment by jonathonf** [comment]
If I've followed the discussion correctly it looks like you're thinking of limiting an admin's permissions.

Administrative users are responsible for the running of the instance, so lacking the ability to view private repos is a bit odd. If an admin has SSH access they can probably get access to the repo content anyway, and "untrusted administrator" is an oxymoron. If you limit viewing by default it should at least be an ```app.ini``` option so someone with root-level access can make the choice about how much access they want admins to have.

**Comment by Unknwon** [comment]
@jonathonf yes, all of you are right, I've thought through this, that's way I marked this as a feature.

**Comment by jonathonf** [comment]
Ah, right! :) Apologies for the extra noise.

**Comment by Unknwon** [comment]
@jonathonf no problem :wink:

**Comment by nanoant** [comment]
:+1:

I run University source code server, I am considering moving from GitLab (very complicated updates/maintanance) to Gogs, but inability to see student's repositories when being admin is quite a shortcoming of Gogs.

**Comment by Unknwon** [comment]
You can now test this on `develop` branch.

**Comment by stonerl** [comment]
@Unknwon :+1:  works.

**Comment by vinsonzou** [comment]
@Unknwon :+1: works.
