### ISSUE TITLE
creating new milestone results in 404 but is successfull 

### ISSUE THREAD

**Issue by sschober** [gogits/gogs#1407]
Hi there,

i am on `0.6.3.0726 Beta`, Commit `31f6069dbe` and seeing a 404 when creating new issues. The creation is successful however, only the redirect seems to target `<user>/<project>/issues/milestones` instead of `<user/<project>/milestones`.

**Comment by sschober** [comment]
Here is a screenshot, for what it's worth:

<img width="870" alt="screen shot 2015-07-30 at 10 07 17" src="https://cloud.githubusercontent.com/assets/100225/8978553/797bf1f8-36a3-11e5-9e77-7128f7e932bb.png">

**Comment by Unknwon** [comment]
Thanks for reporting!

**Comment by Unknwon** [comment]
Oops, closed by commit. :joy:

Thanks your report!

Fixed code has been pushed `master` and you can try on https://try.gogs.io now.

**Comment by sschober** [comment]
Thanks! Tried it and it works like a charm!

**Comment by Unknwon** [comment]
Thanks for your confirmation!
