### ISSUE TITLE
新版本什么时候能出来

### ISSUE THREAD

**Issue by xuhuan** [gogits/gogs#1408]
看到变更日志里已经有v0.6.3的更新日志了，
但是下载只有v0.6.1的下载。
github页面说当前最新的是v0.6.2 Beta。
问下什么时候能提供最新版？

**Comment by Unknwon** [comment]
Plan is to release v0.6.3 on next Tuesday(Aug 4th, 2015).

Hope this answers your question!

**Comment by Unknwon** [comment]
Close for now and open for continuing discussion.
