### ISSUE TITLE
bash as hard requirement

### ISSUE THREAD

**Issue by 7heo** [gogits/gogs#1409]
I tried installing gogs on a system that doesn't have bash installed (alpine linux), and it worked great until I tried to create a repository. I believe that it is totally possible (and even probably simple) to use sh instead of bash. `/bin/sh` is POSIX, and is the only interpreter know to be present on all UNIXes. Therefore, I open a ticket for this issue to be solved. I'd rather have gogs working on as many platforms as possible; especially when the requirement is artifical.

Also, while I'm at it, kudos: gogs is very cool.

**Comment by Unknwon** [comment]
Hi @7heo , thanks your feedback!

There is actually an [config option](https://github.com/gogits/gogs/blob/master/conf/app.ini#L13) to set to `sh`. But this option is for Git repo update hook file(if this is what your problem located, cannot push repo).

Hope helps!

**Comment by 7heo** [comment]
@Unknwon indeed, setting `SCRIPT_TYPE = sh` solves the issue. Given that `sh` is a symlink to `bash` in most distributions, I would recommend setting the default to `sh` (and take care to avoid any bashism!).

Feel free to close the issue depending on what you think about setting the default to `sh`. Thanks for the help, and again, congrats for gogs, so far it's excellent.

**Comment by Unknwon** [comment]
Thanks your confirmation and suggestion!

But I think it's better to keep `bash` as default as it is default in the Git hook samples. :beer:
