### ISSUE TITLE
issues and assign bug still not fixed

### ISSUE THREAD

**Issue by ElvizLai** [gogits/gogs#1412]
![qq20150731-1](https://cloud.githubusercontent.com/assets/501861/8998731/d4843a9a-3763-11e5-89e8-14d2ff6ca790.png)

![qq20150731-2](https://cloud.githubusercontent.com/assets/501861/8998733/da8d0836-3763-11e5-968d-9d8a1e7068f7.png)

**Comment by Unknwon** [comment]
Thanks your feedback but it is duplicated to #1116

**Comment by Unknwon** [comment]
Just a note: work is in progress, improving pages one by one right now, so it should be fixed when we rewrite the `new issue` and `issue view` pages. :grinning:
