### ISSUE TITLE
Markdown in Gogs incorrectly renders nested lists when nested list uses bullets

### ISSUE THREAD

**Issue by trejder** [gogits/gogs#1415]
According to [Markdown Basics](https://help.github.com/articles/markdown-basics/#nested-lists) you can have nested list in form of:

```markdown
1. Item 1
  1. A corollary to the above item.
  2. Yet another point to consider.
2. Item 2
  * A corollary that does not need to be ordered.
    * This is indented four spaces, because it's two spaces further than the item above.
    * You might want to consider making a new list.
3. Item 3
```

In Gogs only first scenario (both outer and inner list uses numbers) works fine. When you have second scenario (outer list uses number, inner list uses bullets), this is ignored and you end up with dual number nested list. See below images as examples.

From left to right: Markdown code | rendering effect in GitHub | rendering effect in Gogs:

Case 1: Inner list uses dashes and items are separated with blank line:

![c1-items-separated-by-blank-line-using-dashes](https://cloud.githubusercontent.com/assets/2903392/9003037/c47b01b8-376a-11e5-84f5-11699e9a22a1.png)

Case 2: Inner list uses asterisks and items are separated with blank line:

![c2-items-separated-by-blank-line-using-asterisks](https://cloud.githubusercontent.com/assets/2903392/9003059/fa9e22ca-376a-11e5-9512-4000ea9f584c.png)

Case 3: Inner list uses asterisks, but there is no blank line separation:

![c3-no-blank-line-separation](https://cloud.githubusercontent.com/assets/2903392/9003068/0871e21a-376b-11e5-92b0-1d99081f2a49.png)

You can also notice, that in case 1 and 2, when there is a blank line separation after each item, inner list also has an ugly empty line intro in the beginning.

Please, consider fixing this ASAP, as nested lists are very useful for step-by-step guides or TODO lists. Currently, they can't be used in Gogs, because rendered final effect is quite ugly.

Issue somehow related to #1416.

**Comment by Unknwon** [comment]
Thanks a lot!

**Comment by manfer** [comment]
I made this pull request to solve the nested unordered list inside an ordered list appearing as an ordered list.

About the the ugly line it must be solved in [blackfriday](http://github.com/russross/blackfriday) library. Or maybe there is an option to configure blackfriday in a way that it won't happen. We will need to append a new commit with the configuration solution if there is one.

**Comment by trejder** [comment]
Thank you for a super-fast response and fix! I'm shocked to see how quick things happens here! :>

**Comment by Unknwon** [comment]
See https://try.gogs.io/manfer/MarkDownSample for fixed version on `develop`.

**Comment by trejder** [comment]
I must admit, that I don't understand you! :> Without fix introduced in @manfer PR Gogs was not rendering nested list correctly. See my examples (case 3) and compare with link you provided. Do you mean, that _after_ this PR is merged, then now all styles from given example should work fine?

**Comment by manfer** [comment]
@trejder Yes, all should look the same as they look on github. Needs to be fully tested anyway.

I down recall if this issue had the first markdown sample that it has now at the beginning which has a second nested unordered list on the second item of the ordered list. That one in gogs is not rendering a new list but interpreted as items of the same unordered list. But that could be just that the markdown is not valid for blackfriday markdown. We will have to find which is the correct markdown so it is interpreted as a new list. Maybe with four spaces instead of two or maybe a new line is needed to break the first unordered list. Anyway that would be for sure a blackfriday issue.

The blackfriday output of your markdown sample is:
```
<ol>
<li>Item 1<br>

<ol>
<li>A corollary to the above item.<br></li>
<li>Yet another point to consider.<br></li>
</ol></li>
<li>Item 2<br>

<ul>
<li>A corollary that does not need to be ordered.<br></li>
<li>This is indented four spaces, because it's two spaces further than the item above.<br></li>
<li>You might want to consider making a new list.<br></li>
</ul></li>
<li>Item 3<br></li>
</ol>
```
And there is little gogs can do about it.

**Comment by manfer** [comment]
I added list samples at the end of the demo in https://try.gogs.io/manfer/MarkDownSample

**Comment by manfer** [comment]
I added a nested unordered sample and I can confirm you need four spaces to nest unordered lists, two spaces is not enough.

I added the needed spaces to this sample:
```
1. Item 1
  1. A corollary to the above item.
  2. Yet another point to consider.
2. Item 2
  * A corollary that does not need to be ordered.
      * This is indented six spaces, because it's four spaces further than the item above.
      * You might want to consider making a new list.
3. Item 3
```
And now it works fine https://try.gogs.io/manfer/MarkDownSample

**Comment by Unknwon** [comment]
@manfer amazing examples, thanks!

**Comment by trejder** [comment]
@manfer Thank you for detailed explanation and examples. Now (nearly) everything is fine and understandable. The only thing is I don't know or I do miss is your last example with nesting code inside a list. It is a key of my #1416 bug report and now (in your examples) it seems fixed (i.e. nested code is rendered as line code, not as in-line code) thought there is no PR to #1416 nor I can find any change to Gogs, that would fix that. And #1416 remains open. What am I missing? Why examples works fine for this part? When and how it was fixed?

**Comment by manfer** [comment]
Same PR https://github.com/gogits/gogs/pull/1425 fixes both ;)

**Comment by Unknwon** [comment]
> @manfer Thank you for detailed explanation and examples. Now (nearly) everything is fine and understandable. The only thing is I don't know or I do miss is your last example with nesting code inside a list. It is a key of my #1416 bug report and now (in your examples) it seems fixed (i.e. nested code is rendered as line code, not as in-line code) thought there is no PR to #1416 nor I can find any change to Gogs, that would fix that. And #1416 remains open. What am I missing? Why examples works fine for this part? When and how it was fixed?

Normally I will for poster's confirmation then close issue. 

But will be forced close after a certain days like now... :joy:
