### ISSUE TITLE
Markdown in Gogs incorrectly renders code when it is nested inside a list

### ISSUE THREAD

**Issue by trejder** [gogits/gogs#1416]
If you have a some form of step-by-step guide and put code examples inside list, then Markdown renderer insider Gogs changes styling and styles inner code as it would be inline code, not full-line code. See examples below.

From left to right: Markdown code | rendering effect in GitHub | rendering effect in Gogs:

Case 1: Code is formatted using backticks:

![c4-code-indent-ticks](https://cloud.githubusercontent.com/assets/2903392/9003131/841f80ca-376b-11e5-9cbe-a59b9ce869f5.png)

Case 1: Code is formatted using space indent:

![c5-code-indent-spaces](https://cloud.githubusercontent.com/assets/2903392/9003137/8ccb3a16-376b-11e5-8700-33be4e0df5e2.png)

As I said, this Markdown construction is very useful for step-by-step guides, so it would be wonderful, if this could be fixed ASAP. Thank you!

Issue somehow related to #1415.

**Comment by Unknwon** [comment]
See https://try.gogs.io/manfer/MarkDownSample for fixed version on `develop`.

**Comment by Unknwon** [comment]
Closed as implemented. :star:
