### ISSUE TITLE
Gogs seems to be using Gravatar's cached images for too long

### ISSUE THREAD

**Issue by trejder** [gogits/gogs#1417]
I have changed my Gravatar photo over a week ago and my local Gogs installation is still showing my "old" photo. I haven't cleared cookies ever since that, but I did closed my browser and turned off my computer each day during that week period.

I think, that Gogs should invalidate its Gravatar cache upon session end (browser close) not upon cookies clearing.

**Comment by Unknwon** [comment]
Thanks your feedback!

What happens if press `command+r` or `F5`?

The default cache time is 10 mins, so I think it is more like a HTTP cache policy matter of browser?

**Comment by trejder** [comment]
Yes, refreshing with `Ctrl+F5` / `Shift+F5` does the job.

Yes, I think, we can make this issue report as incorrect and you're free to close it.

**Comment by Unknwon** [comment]
Good to hear! Thanks for your confirmation!
