### ISSUE TITLE
500 when visit a issue with comments of deleted user

### ISSUE THREAD

**Issue by test000123** [gogits/gogs#1419]
If you reply to an existing issue and then you delete your account, the issue becomes inaccessible and gives error 500.
Here the issues I'm talking about:
http://neetcode.xyz/explouad/testing/issues/1
http://neetcode.xyz/explouad/testing/issues/2

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by jamesa** [comment]
Would you expect a user's comments to be deleted when they remove their account? Along with issues?

**Comment by Unknwon** [comment]
Hi @test000123 , right now in `develop`, it handles comments by deleted user, you can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Close as implemented. :blush:
