### ISSUE TITLE
Make issue preview matching actual result

### ISSUE THREAD

**Issue by trejder** [gogits/gogs#1420]
Can we have issue preview screen using the same styling (and possible sizes) than actual resulting issue screen uses? Currently these two uses two different set of styles and font-sizes and both preview and issue screen uses different dimension of text box:

Issue in preview:

![una-1](https://cloud.githubusercontent.com/assets/2903392/9006056/80befa06-3783-11e5-897b-2aed1d3f61fc.png)

Issue after saving it:

![dua-1](https://cloud.githubusercontent.com/assets/2903392/9006061/8508ccf4-3783-11e5-8ae8-4774089ca750.png)

This could be a bottle-neck problem in situations, where formatting, line breaking etc. does matter.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
It looks like a problem with `font-size` which should have been fixed within v0.6.5 release. :grinning:
