### ISSUE TITLE
Empty "Assignee" list

### ISSUE THREAD

**Issue by trejder** [gogits/gogs#1423]
My Gogs installation has one organization (with six repos) and three users of which two (including my own) are organization's owners. However, when I create any issue I can't assign anyone -- neither myself nor any of these three users.

What am I missing or what steps should I undertake to not have "Assignee" list empty, as currently?

**Comment by matt-h** [comment]
This is currently a bug and is reported here: #1116

**Comment by trejder** [comment]
Thanks. Closing. A duplicate of #1116.
