### ISSUE TITLE
Problem with cookie-stored text for issues / milestones

### ISSUE THREAD

**Issue by trejder** [gogits/gogs#1424]
Gogs saves (for future-reuse?) issue or milestone body in cookies and restores it upon reentering the same screen. However, it seems, that it is not purging cookie-based cache upon successful creation of particular item.

For example, when you create a milestone, but not save it and return to milestone screen, it is nice, that your not saved milestone description is saved to cookie and restored, because it helps in case of some hangups etc. But, when you successfully save that particular milestone, cookie cache should be purged. When you enter the same screen again, because you want to add another milestone and you see previous milestone description again restored from cookie, then this seems to be a bug and it is inconvenient for user to remove this restored entry each time.

This goes even further. I have just notices situation, when I created and saved one milestone, I re-entered the same screen to create another one, I saw restored description of previous milestone, I deleted it, created another milestone, saved it, then I went to create new issue and... saw previous milestone's description restored as new issue body. This seems to be a bug.

**Comment by Unknwon** [comment]
This issue no longer exists when new issue/milestone pages. :dizzy:
