### ISSUE TITLE
Error 500 when trying to view a repository that contains . (period)

### ISSUE THREAD

**Issue by sonnyvan** [gogits/gogs#1428]
I am running V   0.6.1.0325 Beta.

I get Error 500 when trying to view a repository that contains . (period) after creating and pushing for the first time.

**Comment by Unknwon** [comment]
Thanks your feedback!

> I get Error 500 when trying to view a repository that contains . (period) after creating and pushing for the first time.

What is exact error message in your log?

**Comment by sonnyvan** [comment]
Hi, this is what I see in the console:

[Macaron] Completed [path to gogs] 500 Internal Server Error in 16.783889ms
2015/08/01 10:23:29 [view.go:141 Home()] [E] GetSubModule: GetTreeEntryByPath: error not exist

**Comment by Unknwon** [comment]
Well... this is completely not about `.` in repo name, but git submodule.

What is the submodule in your repository?

**Comment by sonnyvan** [comment]
My apologies, I have found the fix in https://github.com/gogits/gogs/issues/714

Thank you for your help!
