### ISSUE TITLE
LDAP : connect to an OpenLDAP (yunohost)

### ISSUE THREAD

**Issue by dolanor** [gogits/gogs#1429]
Hi,
I try to activate an LDAP authentication that is configured by the yunohost team.
The schema is as followed (from ldapvi)
```
11 uid=dolanor,ou=users,dc=yunohost,dc=org
uid: dolanor
objectClass: mailAccount
objectClass: inetOrgPerson
objectClass: posixAccount
uidNumber: 1377
displayName: Dolanor Tharivae
gidNumber: 1377
homeDirectory: /home/dolanor
loginShell: /bin/bash
givenName: Dolanor
cn: Dolanor Tharivae
maildrop: dolanor
sn: Tharivae
mail: dolanorgit@mydomain.org
mail: dolanor2@mydomain.org
```

What I tried was :
```
Authorization name : mydomain.org
Domain: mydomain.org
Host: IP
Port: 389
Base DN: ou=users,dc=yunohost,dc=org
Username attribute: uid
First name attribute: givenName
Surname attribute: sn
E-mail attribute: mail
Search Filter: (&(objectClass=mailAccount)(uid=%s))
Ms Ad SA: uid=%s,ou=users,dc=yunohost,dc=org
```

It doesn't work, and I have no idea where it fails. No log, nothing.
I tried to `go test` in `modules/ldap` by replacing some info with my ldap server and the test seem to work. But it doesn't work for the login.

Also, the screenshots from http://gogs.io/docs/features/authentication.html should be updated with the new Authentication screen.

**Comment by Unknwon** [comment]
Thanks your feedback!

What behavior of Gogs did you see when `it fails`?

**Comment by dolanor** [comment]
It just says "username or password is not correct". 
I see nothing in the logs. Even though I tried to activate the `Debug` or `Trace` version in the `/data/gogs/conf/app.ini` for all log Modes. Because I want to know if it fails at the bind, the connect or if my filters are not good.

From what I understand, I should try to connect just with my uid, and not with the mail (which is uid@mydomain.org).

By the way, I have plenty of email address on this account which are just alias that redirect to my main one. Do you handle that case too ? (but I think it is not the problem here. It is just an `off topic` question)

**Comment by Unknwon** [comment]
Thanks your info!

Not very familiar with LDAP(but trying hard), so it takes time to debug on the problem.

BTW,

> Even though I tried to activate the Debug or Trace version in the /data/gogs/conf/app.ini for all log Modes.

You should edit `custom/conf/app.ini` for any config changes.

> By the way, I have plenty of email address on this account which are just alias that redirect to my main one. Do you handle that case too ?

Not sure what do you mean by the `that case`, but Gogs can add more e-mails into 1 account.

**Comment by dolanor** [comment]
when launching the app from docker, the options are taken into account
```
2015/08/01 12:31:12 [T] Custom path: /data/gogs
2015/08/01 12:31:12 [T] Log path: /gopath/src/github.com/gogits/gogs/log
2015/08/01 12:31:12 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/08/01 12:31:12 [I] Log Mode: File(Debug)
2015/08/01 12:31:12 [I] Redis Enabled
2015/08/01 12:31:12 [I] Cache Service Enabled
2015/08/01 12:31:12 [I] Session Service Enabled
2015/08/01 12:31:12 [I] Mail Service Enabled
2015/08/01 12:31:12 [I] Register Mail Service Enabled
2015/08/01 12:31:12 [I] Notify Mail Service Enabled
2015/08/01 12:31:12 [I] SQLite3 Enabled
2015/08/01 12:31:12 [I] Run Mode: Development
2015/08/01 12:31:12 [I] Listen: http://0.0.0.0:3000
```
I'm well in File(Debug) but still, it doesn't seem to output anything looking like debug. It seems my custom data path is `/data/gogs/ `so it is not the default `./custom/`. Am I right ?

**Comment by Unknwon** [comment]
> when launching the app from docker, the options are taken into account

Well... that's off my knowledge, maybe the dockerfile writer made that path to be the custom path of custom directory.

> By that case, I mean. An LDAP account having multiple emails as aliases can be identified by any of those emails? Or only the first one? Or is it a random number through the list?

I think Gogs hasn't thought about your case yet, could be a bug/feature about this.

**Comment by Unknwon** [comment]
Hi there, by mering PR #1476 into develop, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by Unknwon** [comment]
Close as implemented. :tada:

**Comment by dolanor** [comment]
Sorry for the late reply, but I tried again with :
```
Authorization name : Yunohost LDAP
Domain: mydomain.org
Host: internal IP of my Yunohost LXC
Port: 389
Bind DN : cn=admin,dc=yunohost,dc=org
Bind password : *********
User Search Base : ou=users,dc=yunohost,dc=org
User Filter : (&(objectClass=mailAccount)(uid=%s))
Admin Filter : **empty**
First name attribute : givenName
Surname attribute : sn
E-mail attribute : email
```
and everything works great ! :+1:

**Comment by Unknwon** [comment]
Thanks for your confirmation!
