### ISSUE TITLE
Cannot connect through ssh

### ISSUE THREAD

**Issue by haltsir** [gogits/gogs#1434]
After setting up Gogs, I tried connecting to it with ssh. I added my key through the web interface, the user's authorized_keys file was updated, but I cannot connect:

> ssh -t go@x.x.x
Connection closed by x.x.x.x

In /var/log/system.log this was the output:

Aug  3 12:27:02 home com.apple.xpc.launchd[1] (com.openssh.sshd.0875FFE6-240A-4D75-AAC0-53E6AC317646): Service instances do not support events yet.
Aug  3 12:27:02 home sshd[419]: reverse mapping checking getaddrinfo for x.x.x.x.x [x.x.x.x] failed - POSSIBLE BREAK-IN ATTEMPT!
**Aug  3 12:27:02 home sshd[419]: fatal: Access denied for user go by PAM account configuration [preauth]**
Aug  3 12:27:02 home com.apple.xpc.launchd[1] (com.openssh.sshd.0875FFE6-240A-4D75-AAC0-53E6AC317646[419]): Service exited with abnormal code: 255

My sshd_config has "UsePAM yes". I can also login to the server via ssh with another user.

Any ideas?

**Comment by Unknwon** [comment]
You cannot do anything other than Git operations(push/pull) for the user who is running Gogs. I'm not sure what exactly does `ssh -t` do, but yes, login is no longer possible.

**Comment by haltsir** [comment]
I get the same error when trying this:

git clone go@x.x.x:myuser/repo.git

ssh -t should execute this command:

/Users/go/services/gogs/gogs serv key-2 --config='/Users/go/services/gogs/custom/conf/app.ini'

which provides this output:

Hi myuser ! You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.

**Comment by Unknwon** [comment]
Well... it seems more like a SSH server config issue than a Gogs SSH handle issue to me. If something is wrong with Gogs SSH handle, that's all about Git errors, not like this kind of system auth. 

Try to login this user(who runs Gogs) and see what server gives back to you?

**Comment by haltsir** [comment]
You're absolutely right. It turns out that when I enabled "Remote Login", I enabled it only for Administrators. Now it's for all users and the ssh git is working. Thanks!

**Comment by Unknwon** [comment]
No problem! :beer:
