### ISSUE TITLE
Install gogs on Plesk managed VPS

### ISSUE THREAD

**Issue by dudheit314** [gogits/gogs#1435]
I'm trying to setup gogs on a virtual server which is managed by Plesk. I created a subdomain git.domain.de and database cogs using Plesk and configured gogs like this:
```
ROOT_URL https://git.domain.de
HTTP_ADDR https://git.domain.de
```

When I navigate to the subdomain nothing happens. How can I use the apache2 subdomain configured in Plesk as cogs entry point?

**Comment by Unknwon** [comment]
Hi there,

First you need to make sure Gogs is actually running.

And then check your Apache2 config make sure request has been correctly redirected(I don't know Apache2 so can't tell more).

**Comment by dudheit314** [comment]
```
$ service gogs status
gogs start/running
```
But I don't know where Apache should redirect to? So where is the webpage frontend of gogs located? I guess I have to config something like ServerRoot /path/to/webpage/gogs/

**Comment by Unknwon** [comment]
> But I don't know where Apache should redirect to

Redirect to whatever value you set Gogs listen on localhost.

**Comment by dudheit314** [comment]
How do I instruct gogs to listen to the subdomain? I configured /opt/gogs/custom/conf/app.ini setting both ROOT_URL and HTTP_ADDR to https://git.domain.de. Is there another option I missed or something I have to do after changing the config?

**Comment by Unknwon** [comment]
> How do I instruct gogs to listen to the subdomain?

Gogs has nothing to with subdomain, it's about your Apache/nginx config redirection.

Gogs only listens on a port on localhost.

**Comment by Unknwon** [comment]
Redirect whatever your domain is in apache/nginx and redirect to this localhost:port, for example in Nginx, redirect try.gogs.io to http://localhost:3000

**Comment by dudheit314** [comment]
Ah, now I get it. So what you have to do in Plesk environment, navigate to your subdomain server settings and add the following additional directives for HTTP and HTTPS:
```
RewriteEngine On
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/
```

**Comment by dudheit314** [comment]
Thanks for your support!

**Comment by Unknwon** [comment]
No problem! Glad to hear it. :beer:
