### ISSUE TITLE
Config option for custom SSH authorized_keys file

### ISSUE THREAD

**Issue by HowieWang** [gogits/gogs#1436]
i have installed ssh server(COPSSH ) on pc, and generate authorized_keys and private key in folder:
`C:\SSH\home\Administrator\.ssh`
but when using `git bash`, the default `authorized_keys` is in:
`~\.ssh` 
after add ssh key in gogs settings, i can see some lines add into `~\.ssh\authorized_keys`.
But i cannot using something like `git clone git@.... `to clone.

what is the relationship between the two `authorized_keys`?

Anyone help?
Thanks!

**Comment by Unknwon** [comment]
Hmm... well, `~\.ssh\authorized_keys` is a common place to put authorized_keys, but in your case, based on your information, I suppose the real file is in `C:\SSH\home\Administrator\.ssh`, so whatever you added through Gogs web UI doesn't take effect.

There are two ways to solve it right now:

1. Is there anyway you can change the authorized_keys file in your ssh server(COPSSH )?

2. Add a config option setting for custom SSH authorized_keys file for Gogs.

Which way is best for you?

**Comment by HowieWang** [comment]
> Add a config option setting for custom SSH authorized_keys file for Gogs.   

how can i config this one?

**Comment by Unknwon** [comment]
It's not available yet, but if you think it's the better solution, I'll add this and let you know when it's done.

**Comment by Unknwon** [comment]
It is now possible to use [this config option](https://github.com/gogits/gogs/blob/develop/conf/app.ini#L61) to indicate which directory that your `authorized_keys` file lives.

**Comment by HowieWang** [comment]
wow, thanks sooooo much!　i'll give it a try!

**Comment by Unknwon** [comment]
:trollface: recommend builtin SSH server under Windows as well.

**Comment by HowieWang** [comment]
got it！　ｓｏ　ｎｉｃｅ！
