### ISSUE TITLE
(presumed bug) Lost access to repo from webapp after mistaken actions with collaborators list

### ISSUE THREAD

**Issue by mdolidon** [gogits/gogs#1437]
**Bug Description**

*Pre-conds :* We had a Gogs with 7 users, one organization, one repo inside that organization. Nothing else.

*What happened :* One user was new and we hadn't set him up as a member of the organization. Wanting to do so, instead I mistakenly added him as a repo collaborator. Shortly after, I rightly added him to the organization, and went back to remove him from being the only person  on the repo's collaborator list. Right after I clicked the little red cross, I got a big 404.

*Post-conds :* the repo is unaccessible through the webapp. The direct URL yields a 404, and the welcome screen does not show it. However, the repo count is valid. I looked into the DB repository table. The line was there, but all fields seemed reset to default values, though I'm not completely sure about that. I've tried restarting Gogs and all, to no avail. Trying to access the repo over Git through https brings up an authentication failure.

*Current mitigation :* I tried to create a new repo and copy the old repo's .git folder content. Git was happy enough like that, by Gogs' webapp still showed me a newly created repo, even after restarting the Gogs server. So I deleted the new repo and went on as follows.

I've cloned the old repo directly in git command line, thus making a temporary client repo on the server outside of gogs' dir tree, using the file system as the upstream (no network, pointing to my old .git directory in gogs-repositories). Then I've created a new repo through the webapp, and pushed all branches to it through https://localhost. Gogs was happy with that, though for now I have not been able to restore access to the original repo.

Please see screen capture, showing the discrepancy between repo count and repo list.

http://kibu.fr/entrepot/imgdiv/gogsbug.png

**Gogs Version**
0.6.1.0325 Beta

**Git Version**
1.9.5.msysgit.1

**System Type**
Windows Server 2008 R2 Standard
Service Pack 1
Xeon CPU ; 2 Go RAM (VM), over 1.0Go free
Sqlite

**Error Log**

There's stuff in the `C:\gogs\log\gogs.log` several days BEFORE (we had a days long break), and more starting back ten minutes AFTER the event. But absolutely no trace of the event itself. I've checked for clock discrepancies, and they're not accountable for that gap in the log.

In `gogs-nssm.log` the event has been captured as such : 

    [Macaron] Started GET /FakeOrgName/constellation/settings/collaboration for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration 200 OK in 66.0038ms
    [Macaron] Started GET /api/v1/users/search?q=o for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=o 200 OK in 4.0003ms
    [Macaron] Started GET /api/v1/users/search?q=p for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=p 200 OK in 4.0002ms
    [Macaron] Started GET /api/v1/users/search?q=pa for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=pa 200 OK in 4.0002ms
    [Macaron] Started GET /api/v1/users/search?q=pan for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=pan 200 OK in 3.0001ms
    [Macaron] Started POST /FakeOrgName/constellation/settings/collaboration for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration 302 Found in 80.0046ms
    [Macaron] Started GET /FakeOrgName/constellation/settings/collaboration for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration 200 OK in 67.0038ms
    [Macaron] Started GET /admin for 10.5.0.109
    [Macaron] Completed /admin 200 OK in 12.0007ms
    [Macaron] Started GET /admin/users for 10.5.0.109
    [Macaron] Completed /admin/users 200 OK in 8.0004ms
    [Macaron] Started GET /admin/users/3 for 10.5.0.109
    [Macaron] Completed /admin/users/3 200 OK in 8.0004ms
    [Macaron] Started GET /admin/orgs for 10.5.0.109
    [Macaron] Completed /admin/orgs 200 OK in 8.0004ms
    [Macaron] Started GET /org/FakeOrgName for 10.5.0.109
    [Macaron] Completed /org/FakeOrgName 200 OK in 17.001ms
    [Macaron] Started GET /org/FakeOrgName/invitations/new for 10.5.0.109
    [Macaron] Completed /org/FakeOrgName/invitations/new 200 OK in 6.0003ms
    [Macaron] Started GET /api/v1/users/search?q=p for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=p 200 OK in 4.0002ms
    [Macaron] Started GET /api/v1/users/search?q=pa for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=pa 200 OK in 3.0002ms
    [Macaron] Started GET /api/v1/users/search?q=pan for 10.5.0.109
    [Macaron] Completed /api/v1/users/search?q=pan 200 OK in 3.0002ms
    [Macaron] Started POST /org/FakeOrgName/invitations/new for 10.5.0.109
    [Macaron] Completed /org/FakeOrgName/invitations/new 302 Found in 13.0007ms
    2015/08/04 15:48:54 [T] New member added(FakeOrgName): pan
    [Macaron] Started GET /org/FakeOrgName/members for 10.5.0.109
    [Macaron] Completed /org/FakeOrgName/members 200 OK in 18.001ms
    [Macaron] Started GET /org/FakeOrgName for 10.5.0.109
    [Macaron] Completed /org/FakeOrgName 200 OK in 15.0009ms
    [Macaron] Started GET /FakeOrgName/constellation for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation 200 OK in 334.0191ms
    [Macaron] Started GET /FakeOrgName/constellation/settings for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings 200 OK in 85.0049ms
    [Macaron] Started GET /FakeOrgName/constellation/settings/collaboration for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration 200 OK in 68.0038ms
    [Macaron] Started GET /FakeOrgName/constellation/settings/collaboration?remove=pan for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration?remove=pan 302 Found in 72.0041ms
    [Macaron] Started GET /FakeOrgName/constellation/settings/collaboration for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration 404 Not Found in 6.0003ms
    [Macaron] Started GET /img/404.png for 10.5.0.109
    [Macaron] Completed /img/404.png 200 OK in 0
    [Macaron] Started GET /FakeOrgName/constellation/settings/collaboration for 10.5.0.109
    [Macaron] Completed /FakeOrgName/constellation/settings/collaboration 404 Not Found in 7.0004ms

**Other information**

Yes. The person I added is my manager. It might actually be a feature.

Best regards.

**Comment by Unknwon** [comment]
Thanks your feedback!

`v0.6.1` does have this issue but it should be fixed with `v0.6.3`, try upgrade your Gogs and see if problem remains! :star:

**Comment by mdolidon** [comment]
Hello Unknwon. Cheers for that swift answering. :)

I've stopped the Windows service, copied all 0.6.3 files, and restarted. Checked the version number in the webapp : 0.6.3.0802 Beta
The problem is still there : I can't see the old repo in the webapp.

I looked into the DB table to compare values between the new repo and the old (invisible) repo : they are exactly the same (apart of the obvious id, name and time of creation) ; in practice, one is visible, the other one is not.

**Comment by Unknwon** [comment]
Hmm... @mdolidon , well, by `fixed` I mean if you do same operation, owner will not lose repository access anymore, but for the ones already lost access, need some other ways to fix with.

**Comment by mdolidon** [comment]
Ah OK.
1- indeed, I replayed the scenario on our real organization, a test repo and a test user. It's gone all fine. Bug fixed apparently.

2- concerning our situation, is there a way for me to fix it by hand ? Do you know what may have become corrupted, at least a hint to where I may look ?

**Comment by Unknwon** [comment]
> 2- concerning our situation, is there a way for me to fix it by hand ? Do you know what may have become corrupted, at least a hint to where I may look ?

In the `access` table, add a record with correct `user_id`, `repo_id` and mode `4`, should fix this problem.

**Comment by mdolidon** [comment]
Awesome, it's fixed. All access data for the old repo was gone. Thank you :+1:

**Comment by Unknwon** [comment]
Glad to hear it! :beer:
