### ISSUE TITLE
关于权限，代码导出

### ISSUE THREAD

**Issue by zzvv** [gogits/gogs#1438]
1.团队内部已正式部署至协同平台，作为代码仓库使用。由于对git的使用熟练度普及不够，导致经常有代码推送错误的情况，遂走控制面板看gogs关于权限的一个控制。
   现权限只控制一个用户对整个仓库的读写权限，没有控制到分支级别吗？
2.需要同步服务端代码至其他仓库，已做备份。例如，同步到coding的私有库。在操作过程中，
使用coding的“导入外部仓库”功能，导入失败。github公开项目，导入无问题。

**Comment by Unknwon** [comment]
Thanks your feedback!

> 现权限只控制一个用户对整个仓库的读写权限，没有控制到分支级别吗？

Yes, Gogs hasn't had this feature yet, but someone else has requested something similar: https://github.com/gogits/gogs/issues/776

> 使用coding的“导入外部仓库”功能，导入失败。

Did you use `HTTP/HTTPS` or `SSH` address to migrate? Gogs currently does not allow anonymous SSH clone so this may cause your migration through SSH fail.

**Comment by Unknwon** [comment]
Just pushed code to `develop` that allows anonymous SSH clone, you can now try on https://try.gogs.io

**Comment by Unknwon** [comment]
Please follow updates on https://github.com/gogits/gogs/issues/776
