### ISSUE TITLE
Error leads to no admin user (PostgreSQL back end)

### ISSUE THREAD

**Issue by xxorde** [gogits/gogs#1443]
Even if the creation of the first user fails at first try, the user id is counted up (user_id_seq).
This leads to the fact that there is no user with the id 1, which means: no admin.

In my case I got an permission error and after fixing it, I registered to the gogs and got the id 3;
 [...routers/user/auth.go:266 SignUpPost()] [E] CreateUser: mkdir /home/gogs/gogs-repositories/xxorde: permission denied

**Comment by Unknwon** [comment]
Thanks your feedback!

I've pushed code to `develop` branch with should fix this problem. 

To get admin account, in your case, kill your account until there is no user left.

Register again, now it should be a admin user.

**Comment by xxorde** [comment]
Thank you!

If anyone has the same issue and does not want to delete and recreate their account, I used the following SQL statement.

UPDATE public.user SET is_admin = true  WHERE name = 'xxorde';

**Comment by Unknwon** [comment]
> UPDATE public.user SET is_admin = true WHERE name = 'xxorde';

Yeah, that's what I originally wanted to tell you, but I thought it is reasonable that why cannot the first user in Database be admin.
