### ISSUE TITLE
version 0.6.3.0802 ignores user setting for ssh

### ISSUE THREAD

**Issue by oO** [gogits/gogs#1445]
After upgrading to 0.6.3.0802 I can't access any repositories over SSH with the user "git" somehow it only works with the default "gogs" user.

I've tried updating the /etc/gogs/conf/app.ini and /etc/conf.d/other to use the "git" user as well as updating all files to be owned by "git:git" but I can only make it work if I use the "gogs" user for everything, including owning all of my git repositories.

This forces me to use git clone git clone gogs@SERVER:project/repository.git instead of the git user I had specified before.

**Comment by Unknwon** [comment]
Thanks your feedback!

> After upgrading to 0.6.3.0802 I can't access any repositories over SSH with the user "git" somehow it only works with the default "gogs" user.

There is no such thing default user...

What is the clone URL Gogs web UI gives you?

**Comment by matt-h** [comment]
You also need to make sure that the gogs process is being run by the user `git` if you want to use that user.

**Comment by oO** [comment]
I'm using the 0.6.3-1438741749.487fc8c.trusty package.
/opt/gogs is owned by gogs
/data/git ( repository location ) is owned by git
/etc/gogs/conf/app.ini ( /opt/gogs/custom/conf/app.ini) 
RUN_USER= git
ROOT = /data/git
/etc/gogs/conf.d/other 
export USER="git"

Web Interface runs, clone URL says "git@SERVER:/PROJECT/REPO.git"
When run from a client I get 
```
Gogs:  internal error
fatal: Could not read from remote repository.
```
If I change the RUN_USER and export USER to "gogs" and change the /data/git to also be owned by "gogs" It works, but only if i use a git remote url of "gogs@SERVER:PROJECT/REPO.git" which is problematic to change on all my settings

**Comment by Unknwon** [comment]
Thanks for your reply!

> /opt/gogs is owned by gogs
> /data/git ( repository location ) is owned by git

I'm confused by this, shouldn't there is only one user called `git` who owns both of this two directories(files)?

> Gogs:  internal error

There should be log in `path/to/gogs/log/serv.log` shows what's exactly the internal error is.

**Comment by kseistrup** [comment]
Gogs is looking for your key in the file `~/.ssh/authorized_keys` where `~` is the home directory of `RUN_USER`, then runs the command associated with your key in that file.

That said, I can't access my repositories either…

**Comment by Unknwon** [comment]
Close by now and open for continuing discussion. :octocat:
