### ISSUE TITLE
Creating an issue results on json page

### ISSUE THREAD

**Issue by tarioch** [gogits/gogs#1446]
I just setup gogs and a dummy project. If I create an issue, after pressing create I end up on a json page

```json
{"data":"/tarioch/asdfasdfasdf/issues/3","ok":true,"status":200}
```

the url is

http://myhost:myport/tarioch/asdfasdfasdf/issues/new

The issue gets created correctly as far as I'm able to tell. But strange enough editing doesn't work (pressing the edit button has no effect)

Log does not provide anything.

**Comment by Unknwon** [comment]
Thanks your feedback, and what your Gogs version?

**Comment by tarioch** [comment]
Installed: 0.6.3-1438741749.487fc8c.jessie

**Comment by Unknwon** [comment]
Actually I met this issue few days ago and forgot how I solved it. Can you try force refresh resources and test again?

**Comment by tarioch** [comment]
You mean website refresh or something else? I even tried with a different browser and same behavior (Firefox and Chrome, latest versions each)

**Comment by Unknwon** [comment]
Well...

Would you mind open the network inspect on Chrome or Firefox see if there is any unusual response code on resource?(404, 500, etc.)

**Comment by tarioch** [comment]
When loading the create issues page I get an 404 for the color picker css, everything else looks fine
When pressing create I only see a POST to the url indicated above.

**Comment by Unknwon** [comment]
> When loading the create issues page I get an 404 for the color picker css, everything else looks fine

It reminds me how I fixed it. Because of the 404 issue, JS stops there and so doesn't redirect you to the right page.

Where did you get your Gogs, from release binary? Or GitHub source code clone?

**Comment by tarioch** [comment]
Debian repository: https://packager.io/gh/pkgr/gogs

**Comment by Unknwon** [comment]
Hi @tarioch , I've tested that if I just checkout v0.6.3 release code is just works file(404 still there for css though, but won't stop executing JS).

What is the version of Gogs shows in the bottom of the page?

**Comment by tarioch** [comment]
Version: 0.6.3.0802 Beta

**Comment by Unknwon** [comment]
Hmm... I would recommend that you try download zip files from https://github.com/gogits/gogs/releases/tag/v0.6.3 and test again(if you're willing to). That way we don't have to debug problem in the black box, and just in case packager.io didn't build this version of Gogs right.

**Comment by tarioch** [comment]
With this it works (although the css files with 404 still seem to be missing)

**Comment by Unknwon** [comment]
That's good news though :flushed:

This problem should be fixed with next Gogs release, along with this 404 thing.

**Comment by Unknwon** [comment]
This issue should be completely fixed by `develop` branch.

**Comment by Unknwon** [comment]
Close as implemented. :blush:

**Comment by tarioch** [comment]
Unfortunately after updating to the latest version from packager.io (0.6.5-1440073749.d7c3c79.jessie)  I have the same issue again. Looks like still something is broken with packager.

Exchanging simply the binary from packager with the one from the release here on github solves the issue.

**Comment by Unknwon** [comment]
@tarioch what is the Gogs version shows on the bottom of the page?

And what JSON response do you see?

**Comment by tarioch** [comment]
Ok, very strange, now after reinstalling back the binary from the package. It works fine. So maybe it was some strange issue with my installation. Looks good now. Will check again on the next update.
