### ISSUE TITLE
Pages with different design

### ISSUE THREAD

**Issue by gustavopaes** [gogits/gogs#1448]
Hello,

The page "deploy key" in repository  (/user/repository/settings/keys) and repository issues list have a different layout.

Wrong (or not):
![deploy-keys](https://cloud.githubusercontent.com/assets/227400/9150936/14ac1f34-3dc7-11e5-8065-5381372d0fec.png)

![issues](https://cloud.githubusercontent.com/assets/227400/9150980/f0f59ad2-3dc8-11e5-973d-4344db1cf2f2.png)

Right:
![webhook](https://cloud.githubusercontent.com/assets/227400/9150937/14ad2c8a-3dc7-11e5-995b-adf3d97e5dbd.png)

Thanks

**Comment by Unknwon** [comment]
Thanks for asking!

Pages are converting to use Semantic UI framework page by page, so there is a period of time two designs of UI exist at the same time.

And of course, there is no right or wrong UI in this particular case. :smile:

**Comment by Unknwon** [comment]
Please test out `master` or https://try.gogs.io

**Comment by xPaw** [comment]
org pages still use old design: https://try.gogs.io/org/gogs
