### ISSUE TITLE
Empty repository page show "ssh" even when off

### ISSUE THREAD

**Issue by gustavopaes** [gogits/gogs#1453]
Hello,

In my app.ini I have defined DISABLE_SSH = true, but when I create an empty project, the SSH option is shown to clone.

![screenshot from 2015-08-09 13 51 17](https://cloud.githubusercontent.com/assets/227400/9155881/c4f1c03e-3e9d-11e5-926f-f52d0b2408d6.png)

Thanks.

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by gustavopaes** [comment]
Can I resolve it?

**Comment by Unknwon** [comment]
Hmm... if you mean make a Pull Request, Yes.

Otherwise, you can just wait for me to fix it for you.

**Comment by gustavopaes** [comment]
Yes, I mean make a PR.

**Comment by Unknwon** [comment]
Sure, I guess just hide "SSH" button can fix the problem.

**Comment by gustavopaes** [comment]
Not just it, need to change the urls in field and help text too. But it's simple.

**Comment by Unknwon** [comment]
Well, yes. Should be simple:)

**Comment by Unknwon** [comment]
Closed by #1454
