### ISSUE TITLE
Poor TLS ciphers

### ISSUE THREAD

**Issue by kseistrup** [gogits/gogs#1455]
Out of the box Gogs sports pretty poor TLS ciphers — e.g., RC4 — and get a low rating on [SSL Labs](https://www.ssllabs.com/ssltest/). Could we have configurable TLS ciphers and protocols, please?

**Comment by Unknwon** [comment]
Thanks your feedback!

Looks like RC4 is the default suite in Go.

And by some researching I found https://wiki.mozilla.org/Security/Server_Side_TLS#Go

And can do a similar way like [here](https://github.com/mholt/caddy/pull/78/files#diff-09288858c7c25d9e084be2aae690d472R14) to allows custom configuration of TLS.

How do you think?

**Comment by kseistrup** [comment]
That sounds like a good idea.  Right now I'm actually solving the “problem” by putting Caddy in front of Gogs (which also gives the benefit of HTTP/2).

**Comment by Unknwon** [comment]
Good to know!

**Comment by nd2s** [comment]
As far as I remember Go's cryptographic functions can **not** be considered secure as only a single crypto expert reviewed (or wrote?) them.

**Comment by klauern** [comment]
Just a note on this, but I was wondering what level of effort it would take to embed [Caddy](https://caddyserver.com) in the app directly, which might make things more interesting all around: https://godoc.org/github.com/mholt/caddy/caddy

**Comment by Unknwon** [comment]
@klauern thanks for pointing out, but seems overkill, and expose Gogs directly without proxy seems unusual as well (unless in the local network).

**Comment by Skrupellos** [comment]
Hm, by combining answers so far, I would conclude that it is best to remove web encryption completely.
The reasons are:
* **No false sense of security**
  * No weak default crypto is used.
  * No one has to be an "expert" to find a good crypto setup (and has to keep it up to date!)
* **No overkill**
  * As pointed out: Who needs a secure server normally uses an proxy, which also does encryption (setting up caddy or the let's encrypt client isn't that complicated).
  * A smaller gogs code base makes it easier to maintain, configure and a little tiny bit more secure :)
  * Stick to the unix philosophy of creating "small sharp tools" and not an allrounder.
* The official Let's Encrypt client works well with Apache and Nginx, but not Gogs.

**Comment by Unknwon** [comment]
Related https://github.com/gogits/gogs/pull/4116.

**Comment by Unknwon** [comment]
I think this issue can be closed by merging https://github.com/gogits/gogs/pull/4116.
