### ISSUE TITLE
Authorities were messed up when using mysql database

### ISSUE THREAD

**Issue by Coolerfall** [gogits/gogs#1458]
在同一个组织中创建多个团队（如4个），第一个团队能看到后面团队的仓库；在没有给第一个团队分配仓库时也能看到后面团队的仓库。使用sqlite则没有这个问题。

**Comment by Unknwon** [comment]
Thanks your feedback!

> 第一个团队

What does this mean? Is it the `Owners` group?

**Comment by Coolerfall** [comment]
就是管理员创建出的组织团队（不是owners）

**Comment by Unknwon** [comment]
Thanks your reply!

> 第一个团队能看到后面团队的仓库

Does this mean they can see on organization home page, or they can actually view the repository while it is private?

**Comment by Coolerfall** [comment]
They can actually view the repository while it is private.

**Comment by Unknwon** [comment]
OK, I understand the problem now. Thanks again!

**Comment by Unknwon** [comment]
Hi there, I've pushed fix on `develop` branch, you can also test on https://try.gogs.io/ . To make things right, you would have to remove and re-add repository to a team(any team, just once), then the access rights will be fixed.

**Comment by Coolerfall** [comment]
OK, thanks:)

**Comment by Unknwon** [comment]
Close as implemented. :tada:
