### ISSUE TITLE
Dashboard issues lacks sorting

### ISSUE THREAD

**Issue by manfer** [gogits/gogs#1459]
User issues page, `/issues` path, lacks a paginator and needs inverse timestamp order.

**Comment by Unknwon** [comment]
paginator is implemented.

**Comment by manfer** [comment]
Works. The only thing I don't like is the order. I don't like the default in github either. I would like an order like in forums. The one with last activity first. While the actual order is just inverse order of creation date. At least for me this makes it difficult to find issues with more recent replies.

In github there is the sort feature to deal with this problem. The default order is inverse creation date but you can choose to sort by creation date, more recently updated (forum like), etc.

But this would be a new issue. A sorting feature request. Which I don't know if it has been already suggested. I can open another issue if you can confirm is not a duplicate.

This issue is sorted out and can be closed.

**Comment by Unknwon** [comment]
@manfer I will add sort feature like the one you can use from repository issues page.

**Comment by Unknwon** [comment]
And it's OK to keep this one open as I already linked this one on the todo list...

**Comment by Unknwon** [comment]
Please checkout `develop` branch or https://try.gogs.io/issues

**Comment by Unknwon** [comment]
Close as implemented.
