### ISSUE TITLE
Error when entering the Admin config path

### ISSUE THREAD

**Issue by uriel-fanelli** [gogits/gogs#1462]
Hi, I found a strange message error when entering the /admin/config path. Instead of returning the config dump, after the last update it returns:

<pre>
template: admin/config:105:50: executing "admin/config" at <.Webhook.QueueLength>: QueueLength is not a field of struct type interface {}
</pre>

version is Version: 0.6.4.0809 Beta
Go version is 1.4.2 

Is is a bug?

**Comment by Unknwon** [comment]
It looks like you updated Gogs but didn't recompile it...

**Comment by uriel-fanelli** [comment]
What you mean? I rebuild it from the source code after a git clone...

**Comment by Unknwon** [comment]
The missing field in your error are newly added, so if your template files are up-to-date but Gogs program didn't recompile or you didn't notice you are executing the old/wrong file, this type of errors could occur.

**Comment by uriel-fanelli** [comment]
Again. I deleted the complete folder. I git-cloned again from github. I compiled from scratch. Again, the error is there.

It is physically impossible there is a mistake like "old binaries"

**Comment by Unknwon** [comment]
What is the version shows at the bottom of the page in other pages?

**Comment by uriel-fanelli** [comment]
© 2015 Gogs · Version: 0.6.4.0809 Beta ·

You can see it at boseburo.ddns.net , just ignore the certificate error, it is selfsigned by me.

**Comment by Unknwon** [comment]
> Again. I deleted the complete folder. I git-cloned again from github. I compiled from scratch.

Would you mind to provide some step infos(commands)?

**Comment by uriel-fanelli** [comment]
of course. 

I did a 

git clone https://github.com/gogits/gogs.git  

which created the folder gogs

then I enter gogs

go clean all
go get
go build

and then i get a brand new executable. 

Then I copy the custom config folder I have saved before, and 

./gogs web

please notice it works. It only has several issues. Btw, the SSH problem happens only for the account which used to have a ssh key saved. I created a new one, and this doesn't happens.

Where exactly gogs stores the keys?

**Comment by Unknwon** [comment]
Very strange, I just checked out and tested that everything works fine. :sweat:

> Where exactly gogs stores the keys?

Currently, same file as other SSH keys `~/.ssh/authorize_keys`

**Comment by uriel-fanelli** [comment]
I check, and the old key is there. Also I asked gogs to rewrite the file with keys, which has worked, and still the keys are there. 

So I have no idea what's happening. I can confirm this is only affecting old accounts, new accounts are working fine. So the problem is: where data are stored exactly?

**Comment by Unknwon** [comment]
> So I have no idea what's happening. I can confirm this is only affecting old accounts, new accounts are working fine. So the problem is: where data are stored exactly?

Hmm.. I don't think I understand your problem very well.

There is a `public_key` table to store SSH keys, but in order to make SSH clone/push work, Gogs write those keys into `~/.ssh/authorize_keys`.

Also, rewrite operation is based on `public_key` table.

**Comment by manfer** [comment]
> Is there any other folder/fle I need to copy if I want to upgrade gogs with a brand new version?

* custom/

  Your custom preferences
* data/

  Uploaded avatars and maybe nothing else as everything else should be in the database. Not sure if something more finishes in this folder.
* log/

  I copy this one too. Though I suppose not mandatory. Should be possible to just create a brand new log folder.

If the used database is an SQLite database I don't know where it is stored. For this last one maybe @Unknwon can explain better. But if almost everything is working then not finding the database is the problem. Unless the new installatio is using a totally new database.

**Comment by Unknwon** [comment]
> If the used database is an SQLite database I don't know where it is stored. For this last one maybe @Unknwon can explain better. But if almost everything is working then not finding the database is not the problem. Unless the new installation is using a totally new database.

It's in `data/gogs.db`

**Comment by uriel-fanelli** [comment]
No, the new installation uses the same database. 

I started the server and reproduced the error, but in console I see:

[Macaron] Started GET /img/favicon.png for 127.0.0.1
[Macaron] Completed /img/favicon.png 304 Not Modified in 434.626µs
[Macaron] Started GET /img/favicon.png for 127.0.0.1
[Macaron] Completed /img/favicon.png 200 OK in 832.096µs
**[Macaron] Started GET /user/settings/ssh for 127.0.0.1
[Macaron] Completed /user/settings/ssh 500 Internal Server Error in 12.362636ms**
[Macaron] Started GET /favicon.ico for 127.0.0.1
[Macaron] Completed /favicon.ico 302 Found in 6.44361ms
[Macaron] Started GET /img/favicon.png for 127.0.0.1
[Macaron] Completed /img/favicon.png 200 OK in 658.539µs

is there any way to start it in some "debug", so we can have more details?

**Comment by uriel-fanelli** [comment]
Hi guys, found the problem! 

<pre>
diff sshkeys.tmpl ~/gogs.working/templates/user/settings/sshkeys.tmpl
31c31
<                                     <input name="id" type="hidden" value="{{.ID}}">
---
>                                     <input name="id" type="hidden" value="{{.Id}}">
</pre>

I just edited the file sshkeys.tmpl and changed **.ID** with **.Id** , and now it works back.

Seems somebody has uppercase/lowercase sensitivity, and somebody has not?

**Comment by uriel-fanelli** [comment]
Also I did a diff with the old template:

 diff ~/gogs/templates/admin/config.tmpl  ~/gogs.working/templates/admin/config.tmpl
104,105c104,105
<                                     <dt>{{.i18n.Tr "admin.config.queue_length"}}</dt>
<                                     <dd>{{.Webhook.QueueLength}}</dd>
---
>                                     <dt>{{.i18n.Tr "admin.config.task_interval"}}</dt>
>                                     <dd>{{.Webhook.TaskInterval}} {{.i18n.Tr "tool.raw_minutes"}}</dd>
124,125d123
<                                     <dt>{{.i18n.Tr "admin.config.mailer_disable_helo"}}</dt>
<                                     <dd><i class="fa fa{{if .Mailer.DisableHelo}}-check{{end}}-square-o"></i></dd>

If I put the old one there, it works again....

**Comment by Unknwon** [comment]
Thanks your info!

But based on how you did fix the problem, I still think you Gogs didn't compile right...

**Comment by uriel-fanelli** [comment]
I check the file you suggested , and they are the same. Also the md5 is the same. I have the same code of you, at least the file you mentioned in the other thread.

**Comment by Unknwon** [comment]
> Then I copy the custom config folder I have saved before

Would you mind to dump your custom `app.ini` here?

**Comment by uriel-fanelli** [comment]
Sure

(lalalalala) is for credentials.

==================8X============================

RUN_USER = git
RUN_MODE = prod
APP_NAME = WolfStep Git Repo


[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = lalalala
USER = lalalala
PASSWD = lalalala
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories
SCRIPT_TYPE = bash

[server]
DOMAIN = www.wolfstep.cc
HTTP_PORT = 8080
ROOT_URL = https://www.wolfstep.cc/
LANDING_PAGE = explore
OFFLINE_MODE = false
PROTOCOL = http
DISABLE_SSH = false



[mailer]
ENABLED = true
SEND_BUFFER_LEN = 10
SUBJECT = %(APP_NAME) Message
HOST = lalalala
DISABLE_HELO =
HELO_HOSTNAME = lalalala
SKIP_VERIFY = true
USE_CERTIFICATE = false
FROM = lalalala
USER = lalalala
PASSWD = lalalala



[service]
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL = false
DISABLE_REGISTRATION = true
SHOW_REGISTRATION_BUTTON = false
ENABLE_CACHE_AVATAR = true

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info

[security]
INSTALL_LOCK = true
SECRET_KEY = lalalalala

[picture]
DISABLE_GRAVATAR = false

[oauth]
ENABLED = true

[oauth.github]
ENABLED = true
CLIENT_ID = lalalala
CLIENT_SECRET = lalalala
SCOPES = https://api.github.com/user
AUTH_URL = https://github.com/login/oauth/authorize
TOKEN_URL = https://github.com/login/oauth/access_token

[attachment]
ENABLE = true
PATH = /gogs/data/attachments
ALLOWED_TYPES = image/jpeg|image/png
MAX_SIZE = 32
MAX_FILES = 10


[git.fsck]
ENABLE = true
INTERVAL = 6

**Comment by Unknwon** [comment]
Well... one last shot, are you using 64 bit system? If yes, try one of zip file: https://github.com/gogits/gogs/releases/tag/v0.6.3 and see if it works.

**Comment by uriel-fanelli** [comment]
Yes, I am using a 64bit system. 

I downloaded and compiled the tarfile , and I have to say:

1) The ssh problem is NOT there. (yuppy!).
2) Still the error template: admin/config:105:50: executing "admin/config" at <.Webhook.QueueLength>: QueueLength is not a field of struct type interface {} 
3) When clicking on "View comparison for these 2 commits " I get a 404.

About 2), I didn't configured the webhook parameter in the app.ini, so I am gonna try to do it.

I put the server on "Trace", so I will check a little better.

**Comment by uriel-fanelli** [comment]
Sorry, even configuring the Webhook section the error is still this:

admin/config:105:50: executing "admin/config" at <.Webhook.QueueLength>: QueueLength is not a field of struct type interface {}

**Comment by Unknwon** [comment]
Fine... I'm lost...:sob:

**Comment by uriel-fanelli** [comment]
Well, actually One problem (ssh) went away, the other is not blocking to use the system... it is 1-1 :)

**Comment by Unknwon** [comment]
@uriel-fanelli sorry about it :joy: maybe at some point, suddenly I know what's going on.

**Comment by uriel-fanelli** [comment]
Well, I understood why the 404 when comparing files:

In the logs I see that:

[Macaron] Started GET /https://www.wolfstep.cc/boseburo/anzeigen/compare/bde2bd1ab6bf5ad317d35d2eedc3e37b39b59359...56fb8dba9da88ad682cf8f76669cfd93a3fff9fd for 127.0.0.1
[Macaron] Completed /https://www.wolfstep.cc/boseburo/anzeigen/compare/bde2bd1ab6bf5ad317d35d2eedc3e37b39b59359...56fb8dba9da88ad682cf8f76669cfd93a3fff9fd 404 Not Found in 12.442326ms

and the url shown on the browser is this:

https://www.wolfstep.cc/https://www.wolfstep.cc/boseburo/anzeigen/compare/bde2bd1ab6bf5ad317d35d2eedc3e37b39b59359...56fb8dba9da88ad682cf8f76669cfd93a3fff9fd


seems the server is somehow attaching the whole URL to the base URL, so that https://www.wolfstep.cc/ is appearing twice.....

**Comment by Unknwon** [comment]
> seems the server is somehow attaching the whole URL to the base URL, so that https://www.wolfstep.cc/ is appearing twice..... as I see in the page, this comes from the html which is generated.

I really have no idea about Gogs on your machine, you was running somewhat `v0.6.4` but it didn't do auto-migration for your database, and now it somehow append prefix of the commit compare URL which is newly added after v0.6.3...

**Comment by uriel-fanelli** [comment]
The problem appears in this moment:

templates/user/dashboard/feeds.tmpl:                {{if $push.CompareUrl}}<li><a href="{{$.AppSubUrl}}/{{$push.CompareUrl}}">{{$.i18n.Tr "action.compare_2_commits"}} »</a></li>{{end}}

I just fixed it on my machine like:

  {{if $push.CompareUrl}}<li><a href="{{$push.CompareUrl}}">{{$.i18n.Tr "action.compare_2_commits"}} \xc2\xbb</a></li>{{end}}


and now it works.

**Comment by uriel-fanelli** [comment]
Well, if you like I can check into the database, but please don't ask me to wipe it out, I don't want to configure the site from scratch...  :disappointed:

**Comment by Unknwon** [comment]
> but please don't ask me to wipe it out, I don't want to configure the site from scratch...

That's not an option, of course. 

The problem we face right now is your Gogs code doesn't match template files.

So, in order to get us on the same page, would you like to do following commands to build Gogs from `develop` branch.

```
$ git clone git@github.com:gogits/gogs.git
$ git checkout develop
$ go build -v
$ ./gogs web
```

And please dump everything from console here.

**Comment by uriel-fanelli** [comment]
(14:24:53)[~/mygo/src/gogs]
[loweel@AltPanzer]#  git checkout develop
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'

(14:24:56)[~/mygo/src/gogs]
[loweel@AltPanzer]#  go build -v
gogs

(14:26:11)[~/mygo/src/gogs]
[root@AltPanzer]# ./gogs web
2015/08/11 14:26:33 [T] Custom path: /home/git/gogs/custom
2015/08/11 14:26:33 [T] Log path: /home/git/gogs/log
2015/08/11 14:26:33 [I] WolfStep Git Repo 0.6.4.0810 Beta
2015/08/11 14:26:33 [I] Log Mode: File(Info)
2015/08/11 14:26:33 [I] Cache Service Enabled
2015/08/11 14:26:33 [I] Session Service Enabled
2015/08/11 14:26:33 [I] Mail Service Enabled
2015/08/11 14:26:33 [I] Register Mail Service Enabled
2015/08/11 14:26:33 [I] Oauth Service Enabled [GitHub]
2015/08/11 14:26:34 [I] Run Mode: Production
panic: template: repo/pulls/fork:50: function "Safe" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x8010ed440, 0xc20844d130, 0x0)
        /home/loweel/go/src/html/template/template.go:304 +0x50
github.com/Unknwon/macaron.compile(0xc2082312c0, 0x18, 0x0, 0x0, 0xc2082312e0, 0x2, 0x2, 0xc20802d558, 0x1, 0x1, ...)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:275 +0x400
github.com/Unknwon/macaron.(*templateSet).Set(0xc20823fd40, 0xc938e0, 0x7, 0xc20815a000, 0x0)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:300 +0x51
github.com/Unknwon/macaron.renderHandler(0xc2082312c0, 0x18, 0x0, 0x0, 0xc2082312e0, 0x2, 0x2, 0xc20802d558, 0x1, 0x1, ...)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:367 +0x248
github.com/Unknwon/macaron.Renderer(0xc2083dd240, 0x1, 0x1, 0x0, 0x0)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:404 +0xea
github.com/gogits/gogs/cmd.newMacaron(0xc20815a2a0)
        /home/loweel/golib/src/github.com/gogits/gogs/cmd/web.go:126 +0x6a2
github.com/gogits/gogs/cmd.runWeb(0xc20815a2a0)
        /home/loweel/golib/src/github.com/gogits/gogs/cmd/web.go:185 +0xbe
github.com/codegangsta/cli.Command.Run(0xcbd7e0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd1d390, 0x15, 0xdf20d0, ...)
        /home/loweel/golib/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208186000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /home/loweel/golib/src/github.com/codegangsta/cli/app.go:154 +0xd04
main.main()
        /home/loweel/mygo/src/gogs/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2080415c0)
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 23 [chan receive]:
database/sql.(*DB).connectionOpener(0xc2081e4780)
        /home/loweel/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /home/loweel/go/src/database/sql/sql.go:452 +0x31c

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /home/loweel/golib/src/github.com/gogits/gogs/modules/mailer/mailer.go:53 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /home/loweel/golib/src/github.com/gogits/gogs/modules/mailer/mailer.go:47 +0xea

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208167b40)
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 24 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc20816b540)
        /home/loweel/golib/src/github.com/gogits/gogs/modules/cron/cron.go:162 +0xa65
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /home/loweel/golib/src/github.com/gogits/gogs/modules/cron/cron.go:137 +0x3d

goroutine 25 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208041e40)
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 105 [chan send]:
text/template/parse.lexRightDelim(0xc208377680, 0xe56710)
        /home/loweel/go/src/text/template/parse/lex.go:263 +0xb7
text/template/parse.(*lexer).run(0xc208377680)
        /home/loweel/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /home/loweel/go/src/text/template/parse/lex.go:191 +0x1ac

**Comment by Unknwon** [comment]
........... what the heck: https://github.com/gogits/gogs/blob/develop/modules/base/template.go#L135

**Comment by Unknwon** [comment]
> [loweel@AltPanzer]# go build -v
> gogs

> (14:26:11)[~/mygo/src/gogs]
> [root@AltPanzer]# ./gogs web

Why user are different here? `root`/`loweel`

**Comment by uriel-fanelli** [comment]
I have the same in the source code:

=================8X======================

      "LoadTimes": func(startTime time.Time) string {
                return fmt.Sprint(time.Since(startTime).Nanoseconds()/1e6) + "ms"
        },
        "AvatarLink": AvatarLink,
        "Safe":       Safe,
        "Str2html":   Str2html,
        "TimeSince":  TimeSince,
        "FileSize":   FileSize,
        "Subtract":   Subtract,
        "Add": func(a, b int) int {
                return a + b

========================================

Then we are looking at the same code.

the md5 of the file is 70e0a0dbcdbb25f5478e16b66d72c743

**Comment by uriel-fanelli** [comment]
Users are different because I don't compile as root. I used root because I am testing and I don't want to get crazy for a stupid permission problem. 

Using the same user is exactly the same, anyhow.

**Comment by Unknwon** [comment]
> Users are different because I don't compile as root. I used root because I am testing and I don't want to get crazy for a stupid permission problem.

Different users can certainly cause many hidden problems.

**Comment by Unknwon** [comment]
What happens if you clone but don't compile, does system complains that Gogs does not exist?

**Comment by uriel-fanelli** [comment]
Ok, let's run it again with the same user, then.  

(14:40:27)[~/mygo/src]
[loweel@AltPanzer]# ./gogs web
2015/08/11 14:40:53 [T] Custom path: /home/git/gogs/custom
2015/08/11 14:40:53 [T] Log path: /home/git/gogs/log
2015/08/11 14:40:53 [I] WolfStep Git Repo 0.6.4.0810 Beta
2015/08/11 14:40:53 [I] Log Mode: File(Info)
2015/08/11 14:40:53 [I] Cache Service Enabled
2015/08/11 14:40:53 [I] Session Service Enabled
2015/08/11 14:40:53 [I] Mail Service Enabled
2015/08/11 14:40:53 [I] Register Mail Service Enabled
2015/08/11 14:40:53 [I] Oauth Service Enabled [GitHub]
2015/08/11 14:40:54 [I] Run Mode: Production
panic: template: repo/pulls/fork:50: function "Safe" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x8010ed440, 0xc2084328d0, 0x0)
        /home/loweel/go/src/html/template/template.go:304 +0x50
github.com/Unknwon/macaron.compile(0xc20818de00, 0x28, 0x0, 0x0, 0xc208176ac0, 0x2, 0x2, 0xc20802c258, 0x1, 0x1, ...)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:275 +0x400
github.com/Unknwon/macaron.(*templateSet).Set(0xc20818de90, 0xc938e0, 0x7, 0xc20815a380, 0x0)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:300 +0x51
github.com/Unknwon/macaron.renderHandler(0xc20818de00, 0x28, 0x0, 0x0, 0xc208176ac0, 0x2, 0x2, 0xc20802c258, 0x1, 0x1, ...)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:367 +0x248
github.com/Unknwon/macaron.Renderer(0xc208399240, 0x1, 0x1, 0x0, 0x0)
        /home/loweel/golib/src/github.com/Unknwon/macaron/render.go:404 +0xea
github.com/gogits/gogs/cmd.newMacaron(0xc20815a2a0)
        /home/loweel/golib/src/github.com/gogits/gogs/cmd/web.go:126 +0x6a2
github.com/gogits/gogs/cmd.runWeb(0xc20815a2a0)
        /home/loweel/golib/src/github.com/gogits/gogs/cmd/web.go:185 +0xbe
github.com/codegangsta/cli.Command.Run(0xcbd7e0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd1d390, 0x15, 0xdf20d0, ...)
        /home/loweel/golib/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208182000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /home/loweel/golib/src/github.com/codegangsta/cli/app.go:154 +0xd04
main.main()
        /home/loweel/mygo/src/gogs/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2080435c0)
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /home/loweel/golib/src/github.com/gogits/gogs/modules/mailer/mailer.go:53 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /home/loweel/golib/src/github.com/gogits/gogs/modules/mailer/mailer.go:47 +0xea

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208154640)
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/loweel/golib/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 84 [chan send]:
text/template/parse.lexRightDelim(0xc2083e5a00, 0xe56710)
        /home/loweel/go/src/text/template/parse/lex.go:263 +0xb7
text/template/parse.(*lexer).run(0xc2083e5a00)
        /home/loweel/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /home/loweel/go/src/text/template/parse/lex.go:191 +0x1ac

**Comment by uriel-fanelli** [comment]
(14:47:32)[~/mygo/src/gogs]
[loweel@AltPanzer]#  go version
go version go1.4.2 linux/amd64

**Comment by uriel-fanelli** [comment]
(14:48:22)[~/mygo/src/gogs]
[loweel@AltPanzer]#  set | grep GO
GOARCH=amd64
GOBIN=
GOCHAR=6
GOEXE=
GOHOSTARCH=amd64
GOHOSTOS=linux
GOOS=linux
GOPATH=/home/loweel/golib:/home/loweel/mygo
GORACE=
GOROOT=/home/loweel/go
GOTOOLDIR=/home/loweel/go/pkg/tool/linux_amd64

**Comment by Unknwon** [comment]
> [loweel@AltPanzer]# git checkout develop
> [loweel@AltPanzer]# go build -v

Are those commands executed in home dir or you hide the path?

**Comment by uriel-fanelli** [comment]
No, I didn't hide: as you see above:

(14:24:53)[~/mygo/src/gogs]
[loweel@AltPanzer]# git checkout develop
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'

(14:24:56)[~/mygo/src/gogs]
[loweel@AltPanzer]# go build -v
gogs

the path is always into the GOPATH folder, which is /home/loweel/mygo

where /home/loweel is represented by ~

**Comment by Unknwon** [comment]
Thanks! Understood! 

Let's try remove `gogs` binary in `[~/mygo/src/gogs]` and do `./gogs web` or `gogs web`

**Comment by uriel-fanelli** [comment]
(15:10:16)[~/mygo/src/gogs]
[loweel@AltPanzer]#  rm gogs

(15:10:20)[~/mygo/src/gogs]
[loweel@AltPanzer]#  ./gogs web
-bash: ./gogs: No such file or directory

(15:11:34)[~/mygo/src/gogs]
[loweel@AltPanzer]#  gogs web
-bash: gogs: command not found



well, I have more than twenty years of experience as sysadmin and operations, and this is the most strange request I have seen.  Just in case:

(15:12:24)[~/mygo/src/gogs]
[loweel@AltPanzer]#  which gogs

(15:12:26)[~/mygo/src/gogs]
[loweel@AltPanzer]#  which bash
/bin/bash

maybe you wanted to check which binary I was running, in the path there is no other gogs. :smile:

**Comment by Unknwon** [comment]
> well, I have more than twenty years of experience as sysadmin and operations, and this is the most strange request I have seen. Just in case:

Special case needs special OPs :stuck_out_tongue_closed_eyes:

**Comment by uriel-fanelli** [comment]
Also I tried to strace it, but 


    lstat("/home/loweel/mygo/src/gogs/templates/repo/pulls/fork.tmpl",{ mode=-rw-r--r-- ,inode=81700,size=2685,blksize=4096 }) = 0 (0x0)
    open("/home/loweel/mygo/src/gogs/templates/repo/pulls/fork.tmpl",O_CLOEXEC,00) = 4 (0x4)
    fstat(4,{ mode=-rw-r--r-- ,inode=81700,size=2685,blksize=4096 }) = 0 (0x0)
    read(4,"{{template "base/head" .}}\n<div"...,3197) = **2685** (0xa7d)
    read(4,0xc2081fe47d,512)                         = 0 (0x0)
    close(4)                                         = 0 (0x0)

the file is read correctly, (2685 Bytes)

and stripping the binary had no result. :sad:

**Comment by uriel-fanelli** [comment]
The funny think is the previous version (the one before you paused developing) was working perfectly on the same machine, so this is why I doubt the problem is the compilation or the environment.

**Comment by Unknwon** [comment]
Yeah, it does not make sense that you download compiled zip file and still has same errors.

**Comment by uriel-fanelli** [comment]
Uhm... well, I didn't downloaded a compiled file, I downloaded the tar zipped file and I created from scratch, as you requested...

**Comment by uriel-fanelli** [comment]
I downloaded it on a FreeBSD machine also, and it is doing the same.

**Comment by Unknwon** [comment]
Well......... what did I mean is this file: https://github.com/gogits/gogs/releases/download/v0.6.3/linux_amd64.zip

**Comment by uriel-fanelli** [comment]
This one works, but it is not the same size of the file I get compiling the code. Which go compiler are you using?

**Comment by Unknwon** [comment]
GCC I believe?

**Comment by uriel-fanelli** [comment]
I meant, which version of go compiler.

**Comment by Unknwon** [comment]
Go version? 1.4.2

**Comment by uriel-fanelli** [comment]
Well, I've tried on several machines. The binary you sent me works, the source I compile is not. I will try to compile this very tag this evening...

**Comment by Unknwon** [comment]
So weird...

**Comment by uriel-fanelli** [comment]
Well, it is not the first time I see something to compile properly only on the developer's machine.

:smiley: 

I will get rid of this problem, too.

:smiley:

**Comment by Unknwon** [comment]
Haha, actually that's not compiled from my develop machine, I installed a Debian distro for better support of Linux system, which I only power it when release...

**Comment by manfer** [comment]
In the config file.
```
[database]
...
PATH = data/gogs.db
```
that line can be deleted because is for SQLite configuration. Thouth it is not harm being there as it is ignored and unrelated to the problem.
```
[server]
...
ROOT_URL = https://www.wolfstep.cc/
...
PROTOCOL = http
...
```
something looking strange to me there. But don't know if it is related to the problem.

**Comment by uriel-fanelli** [comment]
Manfer the URL  this is normal. This is because there is a haproxy in front of the gogs itself, taking care of doing the https. But this has never created issues, I used gogs for months before of unknwon leaving and it was ok. 

I asked on the go-nuts mailing list about this issue, because of caching or tmp file. I will wait their answers.

**Comment by uriel-fanelli** [comment]
So at the end I found the problem.

Just  take a vanilla machine and do a 

     git clone https://github.com/gogits/gogs.git

then you enter the folder gogs and type :

      go get -u -v

then it will end like that:

    ../../../golib/src/github.com/gogits/gogs/models/issue.go:202: undefined: setting.IssuePagingNum
    ../../../golib/src/github.com/gogits/gogs/models/issue.go:253: undefined: setting.IssuePagingNum
    ../../../golib/src/github.com/gogits/gogs/models/issue.go:717: undefined: setting.IssuePagingNum
    ../../../golib/src/github.com/gogits/gogs/models/issue.go:720: undefined: setting.IssuePagingNum
    ../../../golib/src/github.com/gogits/gogs/models/repo.go:252: undefined: setting.SSHDomain 
    ../../../golib/src/github.com/gogits/gogs/models/repo.go:254: undefined: setting.SSHDomain
    ../../../golib/src/github.com/gogits/gogs/models/webhook.go:404: setting.Webhook.QueueLength undefined (type struct { TaskInterval int; DeliverTimeout int; SkipTLSVerify bool } has no field or method QueueLength)

which means, it only compiles on some machines which are having the proper dependencies, for any reason. But you can't get them from the internet.

Sorry, I am giving up. Please close the issue.

**Comment by Unknwon** [comment]
It is really... :joy: Anyway, good to know the ending story.
