### ISSUE TITLE
Error when entering the user settings/sshkeys 

### ISSUE THREAD

**Issue by uriel-fanelli** [gogits/gogs#1463]
Hi, I updated gogs to the latest version today, and I see this error:

<pre>
template: user/settings/sshkeys:31:76: executing "user/settings/sshkeys" at <.ID>: ID is not a field of struct type *models.PublicKey
</pre>

when I try to manage my ssh keys via web.

Version: 0.6.4.0809 Beta
Go lang version is 1.4.2

**Comment by Unknwon** [comment]
Same as my comment on https://github.com/gogits/gogs/issues/1462

**Comment by uriel-fanelli** [comment]
I recompiled it from scratch right now. And what I get is:

panic: template: repo/pulls/fork:50: function "Safe" not defined

this is just because there is a |Safe in the template. If I just remove it manually editing the template, it starts, but still the error mentioned is there.

**Comment by uriel-fanelli** [comment]
Hi guys, found the problem! 
I had make a backup of the working gogs before of updating, and...

<pre>
diff sshkeys.tmpl ~/gogs.working/templates/user/settings/sshkeys.tmpl
31c31
`<`                                    `<`input name="id" type="hidden" value="{{.ID}}"`>`
---
`>`                                     `<`input name="id" type="hidden" value="{{.Id}}"`>`
</pre>

I just edited the file sshkeys.tmpl and changed .ID with .Id , and now it works back.

Seems somebody has uppercase/lowercase sensitivity, and somebody has not? Maybe a windows/unix issue?

**Comment by manfer** [comment]
###### template
https://github.com/gogits/gogs/blob/master/templates/user/settings/sshkeys.tmpl#L31

###### router
https://github.com/gogits/gogs/blob/master/routers/user/setting.go#L274-L287

###### model
https://github.com/gogits/gogs/blob/master/models/publickey.go#L381-L385
https://github.com/gogits/gogs/blob/master/models/publickey.go#L88-L100

In my opinion ID uppercase looks totally correct so I don't know what is wrong on your installation but the master branch has no bugs there.

I understand you are trying master branch. Develop has no bug there either.

Maybe I'm wrong but that looks the trace for that specific page and noone else is having trouble.

It all indicates the error is on your end. I can be wrong but I don't see any error on the code.

**Comment by Unknwon** [comment]
@manfer ,

there is a very long thread: https://github.com/gogits/gogs/issues/1462 :joy:

**Comment by Unknwon** [comment]
Close with https://github.com/gogits/gogs/issues/1462
