### ISSUE TITLE
Differences between packaged version and source

### ISSUE THREAD

**Issue by tamagokun** [gogits/gogs#1465]
I set up gogs initially with the "packaged" version from packager.io. It works great, but it uses the user `gogs` and runs everything under that user which means my git URLs look like `git clone gogs@.....` but I would like to use the user `git`

I noticed that in master the default configuration uses git. Am I better of just installing from source?

**Comment by Unknwon** [comment]
Ideally, packager.io should allow you choose which user to run Gogs, but in your case, the easiest approach would be installing from source.

**Comment by tamagokun** [comment]
Got it! Thanks.

**Comment by Unknwon** [comment]
No problem! :grinning:

**Comment by tboerger** [comment]
Uhm, packager allows user switching? Like that: https://github.com/gogits/gogs/blob/master/packager/debian/postinst#L7

This is an example of getting the user, but setting it should work as well (maybe you need to tweak the permissions manually)

**Comment by Unknwon** [comment]
Thanks @tboerger .

**Comment by tboerger** [comment]
And that for reference how to handle the config vars: https://packager.io/documentation/environment-variables/

@crohr can tell more about it for sure.

**Comment by Unknwon** [comment]
So many times I want to `@crohr` but just can't remember his GitHub username... :joy:

**Comment by tamagokun** [comment]
Ok, I saw the `postinst` script and gave setting `APP_USER` a shot before installing, but that didn't seem to actually work. It still created a `gogs` user, the app config still have `RUN_USER = gogs` and I couldn't actually get gogs to start. First, it would complain about starting it with either the gogs user or root. Once I got past that error, it was trying to modify `/home/gogs/.gitconfig` which didn't exist.

I would imagine the issue is on my end. Maybe I need to also set APP_HOME and APP_GROUP when doing the install. I ended up just installing from source and got it all working.

**Comment by crohr** [comment]
Hi there, if the policy for gogs is to use the `git` user instead of `gogs`, then it's just a matter of setting the following in the [`.pkgr.yml`](https://github.com/gogits/gogs/blob/master/.pkgr.yml) file:

```yaml
user: git
group: git
```

The issue being that it may break existing installs...
