### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by pitchforks** [gogits/gogs#1468]
On http://gogs.io/docs/installation/install_from_binary.html

    Currently we only provides 64-bit build binaries.

should be

    Currently we only provide 64-bit build binaries.

**Comment by Unknwon** [comment]
Good catch!

Would you like to make a PR about it?

https://github.com/gogits/docs

Or I can do a quick fix for it.

**Comment by Unknwon** [comment]
Fixed... website should be updated within 5 mins.
