### ISSUE TITLE
您好，国内引用头像问题

### ISSUE THREAD

**Issue by fewiki** [gogits/gogs#1470]
国内引用https://1.gravatar.com/avatar/69d9d7e98d058a2a19eb717b2013fbc4 这类的头像，
因为gravatar.com被墙，访问不动哇
能否在下次更新统一替换下

**Comment by Unknwon** [comment]
Thanks your feedback!

But if you have read the docs: http://gogs.io/docs/advanced/configuration_cheat_sheet.html#picture

**Comment by fewiki** [comment]
Thanks you very much. I set the 'OFFLINE_MODE' to 'true', it's ok now, thanks

**Comment by Unknwon** [comment]
No problem. :smile:
