### ISSUE TITLE
Is it possible to have PAM-less gogs?

### ISSUE THREAD

**Issue by pitchforks** [gogits/gogs#1473]
Problem: the official Linux binary releases link against PAM libraries and PAM is mentioned as dependency here: https://github.com/gogits/gogs/blob/master/.gopmfile

But Slackware Linux has no PAM.

Is it possible to build gogs from source without PAM support, will it build?

**Comment by linquize** [comment]
With PAM: `go build -tags pam`
Without PAM, exclude `pam` from `-tags` option

**Comment by pitchforks** [comment]
Thanks for the hints. Build succeeded. Closing issue.

**Comment by Unknwon** [comment]
Thanks @linquize for the tip!

And a note, latest Gogs does not build with PAM be default. Maybe you were compiling the old version of Gogs.
