### ISSUE TITLE
UpdateGravatarSource() assumes insecure protocol

### ISSUE THREAD

**Issue by kseistrup** [gogits/gogs#1474]
The function `UpdateGravatarSource()` in `modules/avatar/avatar.go` makes an unfounded assumption about the gravatar source: that the server only offers the insecure HTTP protocol:

```go
func UpdateGravatarSource() {
	gravatarSource = setting.GravatarSource
	log.Debug("avatar.UpdateGravatarSource(gavatar source): %s", gravatarSource)
	if !strings.HasPrefix(gravatarSource, "http:") {
		gravatarSource = "http:" + gravatarSource
		log.Debug("avatar.UpdateGravatarSource(update gavatar source): %s", gravatarSource)
	}
}
```

This means that if you have e.g.

```ini
[pictures]
GRAVATAR_SOURCE = https://secure.gravatar.com/avatar/
```

in `custom/conf/app.ini` the custom source will be ignored and avatars will be fetched from `http://1.gravatar.com/avatar/` as per default.

**Comment by Unknwon** [comment]
Good catch! Thanks!

**Comment by Unknwon** [comment]
Please check out this change: https://github.com/gogits/gogs/commit/4cfa2ca40d4f211a124ab9973dfc814190b758b9#diff-956cf9bdfecd1e386632c82860016dc1

**Comment by Unknwon** [comment]
Hi, I've pushed another fix: https://github.com/gogits/gogs/commit/5ddcd8420b0631bd741b69cac02f9a4d4b6a3349
