### ISSUE TITLE
Error viewing issues with assigned milestone

### ISSUE THREAD

**Issue by mexthemax** [gogits/gogs#1480]
When viewing an issue with an assigned milestone I get the following error:
`template: repo/issue/view:254:97: executing "repo/issue/view" at <.Milestone.Index>: Index is not a field of struct type interface {}`

This is the case for issues directly created with milestone and issues created without and later assigned milestone.

I'm using gogs version 0.6.4.0808 Beta.

**Comment by Unknwon** [comment]
Thanks your feedback!

Which branch of Gogs are you using?

**Comment by mexthemax** [comment]
Master branch
got it with
go get -u github.com/gogits/gogs

**Comment by Unknwon** [comment]
I see! This issue is fixed in `develop` and I've pushed code to `master` as well, please help test again!

**Comment by mexthemax** [comment]
Issue is indeed fixed (now using version 0.6.4.0812 Beta on master branch) Thanks.

**Comment by Unknwon** [comment]
@mexthemax good to know!
