### ISSUE TITLE
USER in [mailer] section is not being populated at install time

### ISSUE THREAD

**Issue by pecastro** [gogits/gogs#1481]
After going through the /install process all the mailer details are defined except the USER which will show as empty in the app.ini config file.
This is preventing correct authentication with a mail server ...

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version?

**Comment by pecastro** [comment]
I think this might be a quick fix. Either that or a class and code change.

https://github.com/pecastro/gogs/commit/63f7edde30b344d3372b269e7d6a8c95bd50d774

**Comment by Unknwon** [comment]
Good fix! Thanks.

**Comment by Unknwon** [comment]
Fixed by #1482
