### ISSUE TITLE
Compare two branches

### ISSUE THREAD

**Issue by gustavopaes** [gogits/gogs#1483]
Hello,

Is there plans to implement this feature: show diff between two branches?

Example:
https://github.com/gogits/gogs/compare/master...develop

Thanks.

**Comment by Unknwon** [comment]
Thanks your feedback!

But it's duplicated to https://github.com/gogits/gogs/issues/1405 .

And for your question, yes, once Pull Request is released, compare two branches just a piece of cake. :smile:
