### ISSUE TITLE
Readme Template

### ISSUE THREAD

**Issue by ajtroxell** [gogits/gogs#1487]
When creating a new repository an option for initializing with a custom predefined readme would be useful. In a company environment a lot of readme files have the same general information or sections.

**Comment by linquize** [comment]
+1

**Comment by Unknwon** [comment]
Thanks your feedback!

I've renamed title to `Readme template`, ping me if I understand it wrong. :grinning:

**Comment by tboerger** [comment]
I think he want's to provide a custom README.md on repo creation, like you can preselect a license or a gitignore.

**Comment by ajtroxell** [comment]
Yes, either a dropdown with predefined readme files, or just a single default readme in the confit folder that can be customized and is used when initializing a new repo.

**Comment by de-live-gdev** [comment]
+1 Selecting a template readme (like gitignore / license) would be very useful!

**Comment by Unknwon** [comment]
Hi @ajtroxell @de-live-gdev , it is now possible to init repo when your custom README templates.

See UI on: https://try.gogs.io/repo/create

Currently, it only has 4 variables supported:

```
# repo name is: {Name}

{Description}

You can the development version of this repo via `git clone {CloneURL.SSH}` or `git clone {CloneURL.HTTPS}`
```

**Comment by de-live-gdev** [comment]
@Unknwon Wow, that was fast, great work!  
Automatically ticking the option to init repo, when something gets selected (gitignore, readme,license) could also be an option

**Comment by Unknwon** [comment]
@de-live-gdev yeah, but the readme template is selected anyway, so maybe it's more about personal taste...

**Comment by Unknwon** [comment]
Closed as implemented. :tada:
