### ISSUE TITLE
Add project Gogs on waffle.io

### ISSUE THREAD

**Issue by jniltinho** [gogits/gogs#1489]
Add project Gogs on http://waffle.io

**Comment by Unknwon** [comment]
Thanks your feedback, and http://waffle.io really cool. But I really think it's more like a feature request on http://waffle.io not on Gogs.

**Comment by tboerger** [comment]
Not really, you just create a waffle project as the github repo owner like you created the gitter chat :)

**Comment by Unknwon** [comment]
@tboerger oh really...! I only saw GitHub on the site.

Is this a misunderstanding here? Does @jniltinho want waffle to support track Gogs issues, or he just wants Gogs project's issue self to be managed on waffle?

**Comment by tboerger** [comment]
I think he wants to introduce it as some kind of task management. It's an alternative to trello that is directly coupled with github.

**Comment by Unknwon** [comment]
Hmm... OK, I like Trello more...

**Comment by Unknwon** [comment]
Thanks again for the advice, but, 

from my point of view and quick experience, http://waffle.io is still in too early stage compares to Trello.
