### ISSUE TITLE
Update Script Install on Ubuntu 14.04 -- Gogs 0.6.5

### ISSUE THREAD

**Issue by jniltinho** [gogits/gogs#1491]
Update Script Install on Ubuntu 14.04 + Webserver Nginx.
Set by Dominio in Nginx
https://gist.github.com/jniltinho/280573e10206e31ab1c7

Next update -> Screencast
http://blog.linuxpro.com.br/2015/08/14/instalando-gogs-no-ubuntu/

:+1:

**Comment by Unknwon** [comment]
Thanks!

Updated link on https://github.com/gogits/gogs/tree/develop#screencasts

**Comment by jniltinho** [comment]
Support and Tested Ubuntu 14.04 64Bits LTS, Debian 8 64Bits, OpenSUSE 13.2 64Bits !!!

Next test on CentOS 7 64Bits
:100:

**Comment by jniltinho** [comment]
Script run
Install Debian 8
Install Ubuntu 14.04
Install OpenSUSE 13.2

:+1:

**Comment by Unknwon** [comment]
@jniltinho aweosme!

**Comment by jniltinho** [comment]
Update URL Script Install PT-BR + Screencast Youtube
http://www.linuxpro.com.br/2015/09/instalando-gogs-no-ubuntu.html

**Comment by Unknwon** [comment]
Thanks @jniltinho
