### ISSUE TITLE
Add inactive account to organization

### ISSUE THREAD

**Issue by ElvizLai** [gogits/gogs#1493]
1、Make an account inactive.
2、Using Operations `Delete all inactive accounts`.
3、Then the organization that has this deleted account shows 500 error.

I had to remove the deleted `uid` in table `org_user` annually, it works ok for me.

The script(operation) does not do the relevant delete.

**Comment by Unknwon** [comment]
Thanks your feedback!

Just to make sure,

Did you(owner user) add a inactive user to organization?

Because inactive accounts are not allowed to see any page.

**Comment by ElvizLai** [comment]
@Unknwon 
1、I'm the admin and I wants to remove the user quickly.
2、So I made the `active user` became `inactive` and then use that operations.

**Comment by Unknwon** [comment]
OK, I see... I'll push a quick fix ASAP.

**Comment by Unknwon** [comment]
By principle of deleting a user, this user should not own any repository or belong to any organization. 

So right now in `develop` branch, users who own repo or belong to org will be ignored, and you have to remove repos and membership of orgs before perform delete operation on them.

**Comment by Unknwon** [comment]
Closed as implemented. :tada:
