### ISSUE TITLE
When gogs show .md content ,lost new line  v0.6.5

### ISSUE THREAD

**Issue by cnzzr** [gogits/gogs#1495]
README content

\# Tomcat X64
\*\*部署方法，请参阅：\*\* 
分支用途：
\*\*master\*\* 用于Tomcat正式发布
portal41   Portal Framework发布代码
coa

\* \* \*
应用集成门户项目代码。

\*创建日期：20150701\*

![20150817v1](https://cloud.githubusercontent.com/assets/239363/9301574/13297200-4502-11e5-99a8-bfb7e9ffd7a2.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

Actually it is syntax problem of Markdown, in standard markdown, you would have to add a blank to actually break content into a new line.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion. :dizzy:
