### ISSUE TITLE
下载包乱码

### ISSUE THREAD

**Issue by luoshupeng** [gogits/gogs#1501]
gogs用zip下载源码包中文件名都是乱码，用tar.gz下载是0K。我的操作系统是Centos6.6英文版

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you reproduce this on https://try.gogs.io ? And if it's possible to upload your repository to https://try.gogs.io see if problem is the same?

**Comment by Unknwon** [comment]
From my experience, it is very likely that your ZIP software doesn't support the filename encoding.

**Comment by luoshupeng** [comment]
我在https://try.gogs.io上试试了，确实没有乱码了。
那么我的服务器上需要安装哪些包呢？

**Comment by luoshupeng** [comment]
我的仓库第一次点击tar.gz包下载，会出现500页面，以后再点击tar.gz包下载，都是0KB

**Comment by Unknwon** [comment]
> 我的仓库第一次点击tar.gz包下载，会出现500页面，以后再点击tar.gz包下载，都是0KB

What is the error message for 500?

**Comment by luoshupeng** [comment]
2015/08/19 09:17:22 [1;31m[...routers/repo/repo.go:345 Download()] [E] Download -> CreateArchive /home/git/gogs-repositories/root/test.git/archives/targz/95f0e2f39c.tar.gz: fatal: Unknown archive format 'tar.gz'

**Comment by luoshupeng** [comment]
[Macaron] Started GET /root/test/archive/master.zip for 127.0.0.1
[Macaron] Completed /root/test/archive/master.zip 200 OK in 203.189665ms
[Macaron] Started GET /root/test/archive/master.tar.gz for 127.0.0.1
2015/08/19 09:17:22 [1;31m[...routers/repo/repo.go:345 Download()] [E] Download -> CreateArchive /home/git/gogs-repositories/root/test.git/archives/targz/95f0e2f39c.tar.gz: fatal: Unknown archive format 'tar.gz'
[0m
[Macaron] Completed /root/test/archive/master.tar.gz 500 Internal Server Error in 29.372069ms
[Macaron] Started GET /img/500.png for 127.0.0.1
[Macaron] [Static] Serving /img/500.png
[Macaron] Completed /img/500.png 304 Not Modified in 274.777µs

**Comment by Unknwon** [comment]
Thanks for following up!

It seems like your Git on your server does not support `.tar.gz` format. What is your Git version on your server?

**Comment by luoshupeng** [comment]
the unzip version is 6.0.1 and the git version is 1.7.1.
it seems is an old version, What version should I installed?

**Comment by Unknwon** [comment]
Any progress on this one?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
