### ISSUE TITLE
Fail to initialize ORM engine

### ISSUE THREAD

**Issue by chengziqing** [gogits/gogs#1508]
2015/08/19 14:58:20 [...s/routers/install.go:66 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: update action[%!s(int64=2)]: Error 1030: Got error -1 from storage engine

下载的二进制里没有log和custom文件，你们觉得这样合适吗？并且出现上面错误

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version? Database type and database version?

> 下载的二进制里没有log和custom文件，你们觉得这样合适吗？

I don't understand your question in two parts:

1. Why should Gogs contains `log` directory? What is the value of giving you an empty directory which can be generated at runtime as needed?
2. How does Gogs possibly know what is your custom configuration? 

> 2015/08/19 14:58:20 [...s/routers/install.go:66 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: update action[%!s(int64=2)]: Error 1030: Got error -1 from storage engine

If you just do a Google search: http://stackoverflow.com/questions/4067461/mysql-error-code-1030got-error-1-from-storage-engine-ive-tried-to-delete-dat

**Comment by chengziqing** [comment]
原来是数据库关闭了
