### ISSUE TITLE
Updating gogs by source doesn't work as expected

### ISSUE THREAD

**Issue by de-live-gdev** [gogits/gogs#1510]
I pulled all commits til 390027496c26402c0e4cf985ea225dd7be0a2433 from master and now can't compile gogs anymore.

Errors:
routers/api/v1/user.go:20: unknown gogs.User field 'ID' in struct literal
routers/api/v1/user.go:49: unknown gogs.User field 'ID' in struct literal

Also not starble any more:... -->
 [...gits/gogs/cmd/web.go:78 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?

Seems to come from commit 54b52de6eed4eb2f76620c48189ba3167c290121

Linux  i386, go 1.4.2

**Comment by Unknwon** [comment]
You have to update `github.com/gogits/go-gogs/client`

**Comment by de-live-gdev** [comment]
Thanks for the hint, that helped. Can this be added somehwhere to http://gogs.io/docs/installation/install_from_source.html#install-from-source that updating other go-packages is also needed?
Or in general a sub-chapter where **updating from git** is noted?
I could also provide a PR on gogits/docs for that.  

Currently I am running gogs on i386 ->  packager.io and project only provides x64 builds so I can only use git to update my installation

**Comment by Unknwon** [comment]
In http://gogs.io/docs/installation/install_from_source.html#install-gogs , it does tell you use `-u` flag.

**Comment by de-live-gdev** [comment]
Says
>package github.com/gogits/gogs: github.com/gogits/gogs is a custom import path for >https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked >out from https://github.com/gogits/gogs.git

As it was created by following >Build from develop branch< from docs, but switched to master.  
I just though
>cd $GOGSDIR
>git pull
**>go get ./...**
>go build

would also update other packages

**Comment by Unknwon** [comment]
Yeah, stupid Go compiler...

**Comment by Unknwon** [comment]
Should change `go get ./...` to `go get -u ./...`

**Comment by de-live-gdev** [comment]
ok, changed update-script to this ->

>
go get -u github.com/gogits/gogs
cd "$GOGSDIR"
git pull
go get -u ./...
go build
>echo -e "\033[0;36mCompleted\033[0m"

Running that script produces like 10 times
>package github.com/gogits/gogs: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
>Already up-to-date.

But I will try it these days if it works that way, best regards

**Comment by Unknwon** [comment]
> Running that script produces like 10 times 

it Really depends on the network connection. do `go get -u -v` so you can see stuck on which one.

**Comment by de-live-gdev** [comment]
Produces same output like without verbose

**Comment by Unknwon** [comment]
> Produces same output like without verbose

What is the `same output` exactly?

**Comment by de-live-gdev** [comment]
package github.com/gogits/gogs: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git

**Comment by Unknwon** [comment]
> package github.com/gogits/gogs: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git

This is a really stupid warning by Go, Gogs really cannot help with it.

`go get -u -v ./...` can't help?

**Comment by de-live-gdev** [comment]
How does gopm solve this? Doesn't gopm also use git for checking out?

As said, it ouputs many times the same: 
>gogs@server:~/goWorkspace/src/github.com/gogits/gogs$ go get -u -v ./...
package github.com/gogits/gogs: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/cmd: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/models: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/models/cron: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/models/migrations: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/asn1-ber: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/auth: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/auth/apiv1: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/auth/ldap: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/auth/pam: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/avatar: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/base: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/bindata: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/cron: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/git: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/httplib: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/identicon: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/ldap: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/log: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/mailer: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/middleware: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/process: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/setting: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/social: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/ssh: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/user: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/modules/uuid: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers/admin: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers/api/v1: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers/dev: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers/org: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers/repo: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out from https://github.com/gogits/gogs.git
package github.com/gogits/gogs/routers/user: github.com/gogits/gogs is a custom import path for https://github.com/gogits/gogs, but /home/gogs/goWorkspace/src/github.com/gogits/gogs is checked out >from https://github.com/gogits/gogs.git

**Comment by Unknwon** [comment]
> How does gopm solve this? Doesn't gopm also use git for checking out?

Gopm does not do Git at all, it only download a copy of repo in given commit.

**Comment by Unknwon** [comment]
OK, let's try backup your `custom` directory, and remove gogs repo directory, then do `go get -u -v github.com/gogits/gogs`, then put custom directory back to the old location, finally recompile Gogs.

**Comment by Unknwon** [comment]
OK, found a solution.

Change in `.git/config` from 

```
[remote "origin"]
    url = https://github.com/gogits/gogs.git
```

to 

```
[remote "origin"]
    url = https://github.com/gogits/gogs
```

@de-live-gdev

**Comment by de-live-gdev** [comment]
@Unknwon Seems to work! No error output, only some import lines

**Comment by Unknwon** [comment]
@de-live-gdev thanks your confimation!
