### ISSUE TITLE
Allow local import only for admin users

### ISSUE THREAD

**Issue by de-live-gdev** [gogits/gogs#1511]
Currently any gogs-user can import repos from hosts computer, I think thats a security risk. I and many others create repos for like every thing, and if a user finds out where he needs to look he could easily get data he shouldn't be allowed to get.  Yeah, theres chmod and so on, but for normal gogs-users it shouln't be possible to even know whats on the system running gogs,even if the gogs-system-useraccount would have access to.
Please make migration from host only allowed as gogs-admin user. (Or a switch to opt-in local migration for normal users)

My gogs is only used by people who I can trust, but for other/bigger servers I think thats maybe a thing that should be considered as high level security issue.

**Comment by Unknwon** [comment]
Thanks your feedback!

Hmm.. so, sounds good!

So, people who can migrate must fits one of following rules:

1. he/she is an admin.
2. he/she has given permission to do so.

Does the solution look good to you?

**Comment by de-live-gdev** [comment]
Thanks, that sounds great (even better)!  
Don't look at the report like enforcement, it's only a suggestion :smiley:

**Comment by Unknwon** [comment]
> But please don't look at the report like it's an enforcement, it's only a suggestion :smiley:

Hmm, yeah, it's actually was discuss somewhat long time ago: https://github.com/gogits/gogs/issues/729

**Comment by Unknwon** [comment]
OK, please try on `develop` branch, permission can be given in admin panel.

**Comment by Unknwon** [comment]
Close as implemented.
