### ISSUE TITLE
Gogs crash with 800MB textfile

### ISSUE THREAD

**Issue by hanliumaozhi** [gogits/gogs#1513]
存在一个800M的文本文件，通过git操作无问题。但是当通过网页浏览该文件，gogs会崩溃，并且没有日志记录。

**Comment by Unknwon** [comment]
> 存在一个800M的文本文件，通过git操作无问题。但是当通过网页浏览该文件，gogs会崩溃，并且没有日志记录。

By word `crash`, do you mean Gogs exits or just not respond on the web UI?

**Comment by hanliumaozhi** [comment]
gogs 会在UI无反应后 自动退出

**Comment by Unknwon** [comment]
Thanks for following up!

I'll try on a 800MB text file ASAP, and see what is the problem and how much should be done to fix this issue. :octocat:

**Comment by hanliumaozhi** [comment]
谢谢!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3253, please help test on `develop` branch or https://try.gogs.io.
