### ISSUE TITLE
Docker image size is large

### ISSUE THREAD

**Issue by nekop** [gogits/gogs#1521]
Gogs Docker image size is large, almost 1GB because it uses `FROM google/golang:latest` and this image is 700MB large including many language runtimes. Is it really necessary? I expected it's small because it's golang, Gogs itself is 300MB or so I expect < 500MB image.

**Comment by Unknwon** [comment]
https://hub.docker.com/r/microbox/gogs/ makes Gogs image really small, just don't know what Dockerfile they uses...

**Comment by linquize** [comment]
Some app may ship only the executable file + C runtime library files in a docker image, in order to keep small.

**Comment by tboerger** [comment]
This is far too large. The container needs to be built differently and not from golang base container.

For example https://github.com/dockhippie/skydns results in an 18MB container for SkyDNS

**Comment by sapk** [comment]
You can see there Dockerfile here : https://github.com/microbox/gogs/blob/master/Dockerfile
They don't use a complete docker os image but a tiny rootfs with i think a gogs already compiled.

**Comment by Unknwon** [comment]
@sapk thanks for the info!

**Comment by Unknwon** [comment]
@nekop I've pushed new Dockerfile to `develop` which I tested locally it only has total size of 299MB now. :tada:

If you want to test it now, remember use `docker pull gogs/gogs:develop`

**Comment by nekop** [comment]
Nice, I think it's now acceptable size. Also microbox one is interesting, thanks for the info.

**Comment by Unknwon** [comment]
Close this now by merging `develop` to `master` so both tags are now under 300MB.
