### ISSUE TITLE
请问LDAP可以直接同步AD域帐号吗？

### ISSUE THREAD

**Issue by lvkaiwen** [gogits/gogs#1522]
我想直接通过LDAP，同步AD域账户过来，不知道是否支持？如何设置LDAP。版本：0.6.5

**Comment by Unknwon** [comment]
I'm not sure but if AD works with LDAP, then:

config LDAP as normal, and tell user to login with AD username and password, enable auto-registration.

**Comment by lvkaiwen** [comment]
![2015-08-24_102845](https://cloud.githubusercontent.com/assets/4863791/9431796/f20378b6-4a4a-11e5-8524-317c81fdd425.png)
Base DN，用户名属性，邮箱属性，Search Filter，Ms Ad SA，是应该怎么设置呢？

**Comment by Unknwon** [comment]
@lvkaiwen I have no experience with AD, but if you want to update to `master` branch version, you can use better(new) improvement of LDAP in Gogs, and there is a [detailed docs](https://github.com/gogits/gogs/blob/master/modules%2Fauth%2Fldap%2FREADME.md) for it.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
