### ISSUE TITLE
Triggere mailer for admin created accounts

### ISSUE THREAD

**Issue by Naxiz** [gogits/gogs#1525]
The mailer doesn't get triggered at all, my configuration is as follows:

````
[mailer]
ENABLED = true
HOST = localhost:587
FROM = git@example.com

[service]
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL = true
````

When I create a new issue or user, I only get the following line in my log, not any error from the mail service:

````
Issue created: 4/3
````

Also, my mail server's log doesn't contain anything about an email being sent. I've also tried providing an username and password, but it doesn't change anything.

Is this a bug? I'm on the latest release (0.6.5.0815 Beta).

**Comment by Naxiz** [comment]
Okay, when I register myself using another email address without using the admin panel I do get an email.

Why don't I get an email when I create an issue or when I create an user using the admin panel? Could this be an option?

**Comment by Unknwon** [comment]
@Naxiz good catch!

Yes, mailer only be triggered by self-sign up page, I can add a checkbox says something like `send registration confirmation e-mail` when you create a user through admin panel.

How does it sound?

**Comment by Naxiz** [comment]
Yes, that would be great! Thanks!

**Comment by Unknwon** [comment]
No problem :grinning:

**Comment by Unknwon** [comment]
It's now possible on `master` branch!

![image](https://cloud.githubusercontent.com/assets/2946214/10114395/fb941732-63bd-11e5-93bb-271a2c4ddb62.png)

**Comment by Naxiz** [comment]
Nice!
