### ISSUE TITLE
 % symbol interpreted as URL escape characters in Postgres password

### ISSUE THREAD

**Issue by JohnMaguire** [gogits/gogs#1526]
```
2015/08/22 21:40:43 [W] Register Mail Service: Mail Service is not enabled
2015/08/22 21:40:43 [...s/routers/install.go:66 GlobalInit()] [E] Fail to initialize ORM engine: Fail to connect to database: parse postgres://gogs:2wPb*%tBQyjP@127.0.0.1:5432/gogs?sslmode=disable: invalid URL escape "%tB"
```

(I've obviously changed my password.) The characters "%tB" in my password caused me to be unable to connect after upgrading from v0.60 to v0.65.

**Comment by Unknwon** [comment]
Thanks your report!

I'm not sure how exactly PostgreSQL handles about this case, but for the experiment, what if you give password `2wPb*%tBQyjP` to `2wPb*%25tBQyjP` which let Go escape `%25` to `%`. And if this way works, I can change Gogs to add a step for converting `%` in password all to `%25`.

Thanks! :grinning:

**Comment by jcracknell** [comment]
https://github.com/gogits/gogs/blob/a7686e8749f46b13c62c67c7b4fc5dbc0c5a42c3/models/models.go#L135

Username and password at least should be URL encoded.

**Comment by Unknwon** [comment]
Hi, just pushed fix to `master`, please help test again!

**Comment by jcracknell** [comment]
Maybe do mysql as well? ;)

**Comment by JohnMaguire** [comment]
Thanks @jcracknell and @unknwon for being so on top of this. I originally changed my password but I can definitely test this for you later today or tomorrow. :) Thanks for the fix.

**Comment by Unknwon** [comment]
@jcracknell I just looked [xorm's code](https://github.com/go-xorm/xorm/blob/master/mysql_driver.go#L21) for MySQL, it seems that it does not do URL parse for MySQL, so no need to escape for MySQL.

Correct me if I'm wrong. :eyes:

**Comment by Unknwon** [comment]
Close as implemented. :tada:
