### ISSUE TITLE
Repository name showing user's name

### ISSUE THREAD

**Issue by JohnMaguire** [gogits/gogs#1527]
On the settings page (e.g. http://git.leftforliving.com/jmaguire/Cardinal/settings), the form says "Repository Name" but shows "jmaguire" instead of "Cardinal."

**Comment by JohnMaguire** [comment]
Okay, so I just spent 30 minutes tearing my hair out, searching the codebase for what could possibly causing this issue. Every reference looked correct, even Firefox / Chrome Dev Tools were telling me the value was set to the repository's name, not the owner's name.

It was LastPass.

**Comment by Unknwon** [comment]
Hmm... I got confused... so what is going on now?

**Comment by JohnMaguire** [comment]
@Unknwon Sorry about this one, I closed the issue as it was not a bug at all. This was entirely my environment (browser plugin)'s doing. :) Thanks again for gogs.

**Comment by Unknwon** [comment]
OK, no problem!
