### ISSUE TITLE
Always use Mailer FROM setting when sending email

### ISSUE THREAD

**Issue by goldbattle** [gogits/gogs#1528]
Currently the mailer seems to error if the email section `FROM` in the config is supplied.
When the config line reads: `FROM = "Gogs" <noreply@****.com>` I get this error
```log
2015/08/23 21:47:11 [.../runtime/asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: noreply@****.com, info: Subject: [Test-Repo] Test(#1), send issue mention emails err: mail: missing phrase`
```

When I have this `FROM = noreply@****.com`, it still does not use this value and instead uses the email of the user that triggers the event.

I think it would be better if people want to functionality of being able to reply to the person that triggered the email event is to use the `FROM` address and then use the `Reply-To:` email header with the user's email.

**Comment by goldbattle** [comment]
Tested with `0.6.3.0802 Beta` and `0.6.5.0815 Beta` according to the configuration page

**Comment by Unknwon** [comment]
Thanks your feedback!

> I think it would be better if people want to functionality of being able to reply to the person that triggered the email event is to use the FROM address and then use the Reply-To: email header with the user's email.

I'm confused by this line. So you say ` it still does not use this value and instead uses the email of the user that triggers the event.`, and then you want to reply to the user who triggered the event(which is the way Gogs does right now).

**Comment by goldbattle** [comment]
It does not use the `FROM` email as the email the email has been sent from.
As you said it sends it as the user sent the email, not the server that is sending it.

**Comment by Unknwon** [comment]
OK... Gogs uses `FROM` you configured on `app.ini` when sends so-called `system` e-mails, and use user's e-mail as `FROM` for sending mention e-mails is on purpose that shows who actually mentioned you. 

Does my explanation of the behavior make sense to you?

**Comment by goldbattle** [comment]
Yes!

That make sense.
I am looking for all messages to be sent from the server, and the ones that the user triggered instead use the `Reply-To:` flag. All emails are being mail from the server and not the person themselves, the current way makes it seem that the person sent that email, not the server. This causes issues as a smtp server is sending mail as a non-verified address that it doesn't own.

> If I use noreply@domain.com it should always send from that as it, as domain.com is the domain that I own and I have rights over, not gmail.com or whatever email domain that the user's email is hosted on.

The server should always send from the from address, but the user can still reply to the original sender using the `Reply-To:` header.

**Comment by Unknwon** [comment]
OK, I understand now! 

And I agree your point about `makes it seem that the person sent that email, not the server`.

**Comment by Unknwon** [comment]
Hi @goldbattle , by merging https://github.com/gogits/gogs/pull/1596 to `develop` branch, this issue is claimed to be fixed. Can you help test again? Thanks!

**Comment by Unknwon** [comment]
Closed as implemented.

**Comment by JokerQyou** [comment]
Maybe it's too late to say now, but I was also experiencing error if I set FROM value to the form of `"name" <name@addr.ext>`, it said something about `missing angle address` or what.

**Comment by Unknwon** [comment]
@JokerQyou someone reported this before, I think the solution was using:

`"Name" <email@example.com>`

Two "`" around your value in custom app.ini.
