### ISSUE TITLE
组织查看仓库问题

### ISSUE THREAD

**Issue by patzheng** [gogits/gogs#1529]
我使用A账户创建一个组织G，组织里面添加成员B。在组织G的面板上面创建一个仓库。使用A可以看见这个项目，但是使用B登录访问报404错误

**Comment by Unknwon** [comment]
Thanks your feedback.

So...

> 在组织G的面板上面创建一个仓库

Is it a private repository?

> 组织里面添加成员B

Does B in the `Owners` team?

**Comment by Unknwon** [comment]
Hmm? What is the situation here?

**Comment by tkisme** [comment]
B 不在 Owners team是不是就无法访问，只能在dashboard看到

**Comment by Unknwon** [comment]
> B 不在 Owners team是不是就无法访问，只能在dashboard看到

@tkisme yes, B has to be in a team that has access to the repository.
