### ISSUE TITLE
Things go wrong when the network is bad and the repo is big.

### ISSUE THREAD

**Issue by melote** [gogits/gogs#1530]
I always receive this message when the repo is big and the network could be bad, so sad :(
```
Compressing objects: 100% (4537/4537), done.
Writing objects: 100% (6381/6381), 43.95 MiB | 12.00 KiB/s, done.
Total 6381 (delta 1334), reused 6381 (delta 1334)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
```
version: 0.6.5.0815 Beta

**Comment by Unknwon** [comment]
Thanks your report!

Can you post the exact error of 500 logged in Gogs?

**Comment by melote** [comment]
015/08/27 10:35:38 [...s/middleware/repo.go:288 func·009()] [E] GetTags: fork/exec /bin/git: cannot allocate memory
2015/08/27 10:36:07 [I] Log Mode: File(Info)
2015/08/27 10:36:07 [I] Redis Supported
2015/08/27 10:36:07 [I] Memcache Supported
2015/08/27 10:36:07 [I] Cache Service Enabled
2015/08/27 10:36:07 [I] Session Service Enabled
2015/08/27 10:36:08 [I] SQLite3 Supported
2015/08/27 10:36:08 [I] Run Mode: Production
2015/08/27 10:36:08 [I] Listen: https://0.0.0.0:443
2015/08/27 11:21:02 [...s/middleware/repo.go:288 func·009()] [E] GetTags: fork/exec /bin/git: cannot allocate memory
2015/08/27 11:21:39 [...s/middleware/repo.go:288 func·009()] [E] GetTags: fork/exec /bin/git: cannot allocate memor

**Comment by Unknwon** [comment]
Well... the error is pretty obvious.

Which version of Gogs are you running?

**Comment by melote** [comment]
version: 0.6.5.0815 Beta，the latest released version.

**Comment by Unknwon** [comment]
@melote thanks for following up!

But still, it is caused your memory is all being used.

What does Gogs `/admin` panel say about how much memory has been used by Gogs?

**Comment by melote** [comment]
@Unknwon , Let me check that, Hmm,  now 500 code error happend, the monitor info is:
```
Server Uptime
2 hours, 23 minutes, 20 seconds
Current Goroutines
20
Current Memory Usage
72MB
Total Memory Allocated
176MB
Memory Obtained
154MB
Pointer Lookup Times
1883
Memory Allocate Times
670280
Memory Free Times
584384
Current Heap Usage
72MB
Heap Memory Obtained
143MB
Heap Memory Idle
69MB
Heap Memory In Use
74MB
Heap Memory Released
36MB
Heap Objects
85896
Bootstrap Stack Usage
416KB
Stack Memory Obtained
416KB
MSpan Structures Usage
100KB
MSpan Structures Obtained
143MB
MCache Structures Usage
1.2KB
MCache Structures Obtained
16KB
Profiling Bucket Hash Table Obtained
1.4MB
GC Metadada Obtained
9.0MB
Other System Allocation Obtained
480KB
Next GC Recycle
143MB
Since Last GC Time
34.2s
Total GC Pause
0.7s
Last GC Pause
0.011s
GC Times
79
```

**Comment by Unknwon** [comment]
OK... So does restart Gogs solves your problem? Because code in master has attempted to fix a memory leak on HTTP push/pull . This could be a reason.

**Comment by Unknwon** [comment]
If not, then means your push is so large that really needs more RAM...

**Comment by melote** [comment]
@Unknwon , yes, everything has been all right since restart gogs.

**Comment by Unknwon** [comment]
@melote OK, let's see how things are going after next release!

**Comment by Unknwon** [comment]
The possible leak has been fixed. Remain close until negative feedback.

**Comment by senden9** [comment]
I thing i have a similar (same) problem:
Start gogs:
```
2016/02/26 11:29:16 [I] Log Mode: File(Debug)
2016/02/26 11:29:16 [I] Cache Service Enabled
2016/02/26 11:29:16 [I] Session Service Enabled
2016/02/26 11:29:16 [I] Git Version: 1.7.10.4
2016/02/26 11:29:25 [I] Run Mode: Production
2016/02/26 11:29:31 [I] Listen: http://0.0.0.0:3000
```
Do a initial push of a existing repo with a larger file in it (41M): ([ORB_SLAM](https://github.com/raulmur/ORB_SLAM) by the way)
```
$ git push -u origin master
Username for 'http://***:3000': ***
Password for 'http://***@***:3000': 
Counting objects: 586, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (351/351), done.
Writing objects: 100% (586/586), 89.88 MiB | 1.66 MiB/s, done.
Total 586 (delta 233), reused 586 (delta 233)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```
On the same time on the server:
```
2016/02/26 11:29:35 [D] Session ID: f5dbfd6e312ab8bb
2016/02/26 11:29:35 [D] CSRF Token: VgqC_lnRvI2XF6QTICM74d2giuw6MTQ1NjQ4MjU3NTk0OTE5NzM5Nw==
2016/02/26 11:29:42 [D] Session ID: c71adc66352d90c0
2016/02/26 11:29:42 [D] CSRF Token: Oa8rC-cTcNuUjj0Ehn4J6Cz54bw6MTQ1NjQ4MjU4MjIyNjMzNTkxMg==
2016/02/26 11:29:44 [D] Session ID: 767616329b551dc2
2016/02/26 11:29:44 [D] CSRF Token: bN5BWqycBr5wSJNXUvXsQyr-f8E6MTQ1NjQ4MjU4MjMzMzk1Nzg1Nw==
2016/02/26 11:29:48 [D] Session ID: 65780843e2d3cd9c
2016/02/26 11:29:48 [D] CSRF Token: 6XKX9pBA9hgpe9woWlPw8q0hYJU6MTQ1NjQ4MjU4NjU0NTM3NDE5Ng==
2016/02/26 11:29:52 [D] Session ID: e9c5ca6ae0f206bc
2016/02/26 11:29:52 [D] CSRF Token: yOnJAM_dVt_rnfHbczKddRxtED06MTQ1NjQ4MjU5MDUzMzE2Mjk2MA==
```
Try to any repo on the webinterface:
```
2016/02/26 11:31:12 [D] Session ID: 9baa8ed774b030bf
2016/02/26 11:31:12 [D] CSRF Token: -vlr5zKhZ0905DhN-4t-sjCcYts6MTQ1NjQ4MTM5MzExNDIyNjk4Ng==
2016/02/26 11:31:12 [D] Template: user/dashboard/dashboard
2016/02/26 11:31:16 [D] Session ID: 9baa8ed774b030bf
2016/02/26 11:31:17 [D] CSRF Token: -vlr5zKhZ0905DhN-4t-sjCcYts6MTQ1NjQ4MTM5MzExNDIyNjk4Ng==
2016/02/26 11:31:17 [...s/middleware/repo.go:151 func1()] [E] GetTags: fork/exec /usr/bin/git: cannot allocate memory
2016/02/26 11:31:17 [D] Template: status/500
```

As hardware i use a Raspberry Pi. RAM with all services are started normally:
```
             total       used       free     shared    buffers     cached
Mem:          434M       189M       244M         0B        10M        65M
-/+ buffers/cache:       113M       320M
Swap:          99M        18M        81M
```
I need to restart gogs to let the service operate normally again.

**Comment by Unknwon** [comment]
@senden9 Please use SSH to push large content, HTTP is consuming huge memory with big commits.

**Comment by sithembiso** [comment]
@Unknwon, I'm having a similar issue when I try to pull repos that are more than 1MB (I added a 4MB file in one of the repos, and I started getting this error in `http.log`).
```
[...ters/repo/http.go:380 serviceRpc()] [E] fail to serve RPC(upload-pack): exit status 141
```
I have a `12GB` RAM and Gogs records the following:
```
Current Memory Usage
11MB
Total Memory Allocated
107MB
Memory Obtained
28MB
```
Which leads me to believe that this probably isn't a memory issue.

**Comment by Unknwon** [comment]
@sithembiso are you using Windows?

**Comment by sithembiso** [comment]
No, I'm using `Ubuntu 14.04 LTS 64-bit`.

**Comment by Unknwon** [comment]
@sithembiso having on ideas right now...

**Comment by bkcsoft** [comment]
`git-upload-pack --timeout=n` perhaps?
https://git-scm.com/docs/git-upload-pack

**Comment by sithembiso** [comment]
Turns out the issue was on the Git client I was using. I was hanging up too early.
