### ISSUE TITLE
Add test mailer functionality

### ISSUE THREAD

**Issue by Naxiz** [gogits/gogs#1531]
When I was setting up the mailer, it took me a few hours to realize that I was trying to send a test email using a function that doesn't send emails at all.

Maybe a "send test email" button can be added to the configuration page (see added screenshot). This will save some time when testing the mailer service.

![Screenshot](https://cloud.githubusercontent.com/assets/1782761/9442448/490f3c04-4a7c-11e5-8a64-d7029ef5d794.png)

**Comment by goldbattle** [comment]
Could add just a button and send it to the current user's email account.

**Comment by Unknwon** [comment]
Good suggestion!

**Comment by dakira** [comment]
I also think this would be a helpful feature.

**Comment by romainreuillon** [comment]
+1

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2660

**Comment by Unknwon** [comment]
Close as implemented.

**Comment by anothergituser** [comment]
I can not seem to find this functionality, only configuration is custom/conf/app.ini
Has this been removed lately? 
Thansk

**Comment by Fastidious** [comment]
@anothergituser screenshot from my install:

![screen shot 2017-11-02 at 17 12 56](https://user-images.githubusercontent.com/8352292/32350567-22cb6af8-bff1-11e7-990c-07965fa1e885.png)

Running latest.
