### ISSUE TITLE
Copy Button Styling

### ISSUE THREAD

**Issue by goldbattle** [gogits/gogs#1532]
Have this style error on a newly created repo:
![image](https://cloud.githubusercontent.com/assets/2222562/9442389/be90694a-4a49-11e5-8b61-bfef08633f27.png)

Seems that the copy button is forced to the next line if the 200px margin is removed then it works fine.
![image](https://cloud.githubusercontent.com/assets/2222562/9442467/165c5c24-4a4a-11e5-98dc-09d815c9fd37.png)

Using chrome `Version 45.0.2454.46 beta-m (64-bit)`. Style in question:
```css
.repo-bare #repo-clone-copy {
    margin-right: 200px;
}
```
https://github.com/gogits/gogs/blob/54b52de6eed4eb2f76620c48189ba3167c290121/public/ng/css/gogs.css#L1502-L1504

**Comment by Unknwon** [comment]
Thanks your reporting!

**Comment by JokerQyou** [comment]
I'm experiencing height related styling issue on Chrome `45.0.2454.99 m (64-bit)`, as seen in the following screenshot, the height of the `copy` button does not match the input left to it.
![image](https://cloud.githubusercontent.com/assets/1465267/10096645/c69adf88-63a5-11e5-965b-dae24965bab0.png)

**Comment by Unknwon** [comment]
Please test on https://try.gogs.io/unknwon/bare again!

**Comment by goldbattle** [comment]
Looks good to me, on the large screen.
But it seems to not be responsive when you look at it on a smaller one.
![image](https://cloud.githubusercontent.com/assets/2222562/10355157/75d8fe46-6d36-11e5-9fe2-b1a898df0124.png)

On your `#repo-clone-url` remove the width:100% and instead apply it to the container div, with classes `ui action small input`. It would then look like:
![image](https://cloud.githubusercontent.com/assets/2222562/10355195/f50427e0-6d36-11e5-9ba8-1e3efd1b0baa.png)
![image](https://cloud.githubusercontent.com/assets/2222562/10355199/063afff2-6d37-11e5-977d-903bd218dfd8.png)

**Comment by Unknwon** [comment]
@goldbattle thanks your tip!

But just to be clear: https://github.com/gogits/gogs#browser-support

**Comment by goldbattle** [comment]
I was wondering that, either way, thanks for the UI upgrade!

**Comment by Unknwon** [comment]
@goldbattle pushed fix with your suggestion to `develop` branch, thanks again!

**Comment by goldbattle** [comment]
Looks better, thanks!

**Comment by Unknwon** [comment]
Cool! So have your issue been solved?

**Comment by goldbattle** [comment]
Yep!

**Comment by Unknwon** [comment]
Thanks your confirmation!
