### ISSUE TITLE
Always use Mailer FROM setting when sending email

### ISSUE THREAD

**Issue by Naxiz** [gogits/gogs#1533]
When an user updates an issue, an email will be send to all other members of the project.

The problem is that the sender of the email will be the email address of the user who created or updated the issue. This will result in the email going to the spam box for most users (because my mail server is not allowed to send email from other domains than its own), and email spoofing is even illegal in some jurisdictions.

I suggest to use the user's name, and the Mailer's FROM setting's email address to send emails. For example, if my Mailer's FROM settings is git@mydomain.com, the sender will be:

    Naxiz <git@mydomain.com>

This is how most websites handle this issue, for example GitHub does this too.

**Comment by Unknwon** [comment]
Thanks your feedback!

But it seems same as https://github.com/gogits/gogs/issues/1528

**Comment by Naxiz** [comment]
Oh yes, I'm sorry, I didn't see that one! :smile:

**Comment by Unknwon** [comment]
No worries, indeed you made a better title :grinning:

So I'm going to close this one.
