### ISSUE TITLE
Removing deploy key does not remove key

### ISSUE THREAD

**Issue by amavis442** [gogits/gogs#1535]
Version:0.6.5.0815
When removing an added deploy key. It says it has removed the key, but in the view the removed key is still visible. Neither database nor authorized_keys will be updated.

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
Hi, I've pushed fixed code to `develop`  branch and you can also test on https://try.gogs.io !

**Comment by amavis442** [comment]
It works :) Removal confirmed. Authorized_keys is clean and table public_key is clean. 
Tested with 1 and with 2 keys just to check if with 2 keys it did not remove all keys.
- Thanx

**Comment by Unknwon** [comment]
@amavis442 thanks your confirmation!
