### ISSUE TITLE
Current Docker tag latest broken

### ISSUE THREAD

**Issue by Luzifer** [gogits/gogs#1537]
Image: `gogs/gogs:latest`

```
# docker logs 99f3d0ae03aa
unknown key type ed25519
Could not load host key: /data/ssh/ssh_host_ed25519_key
Starting OpenBSD Secure Shell server: sshd.
sending incremental file list

sent 2788 bytes  received 40 bytes  5656.00 bytes/sec
total size is 356612  speedup is 126.10
mkdir: cannot create directory `/home/git/.ssh': No such file or directory
chmod: cannot access `/home/git/.ssh': No such file or directory
./docker/start.sh: line 41: /home/git/.ssh/environment: No such file or directory
chown: cannot access `/home/git/.ssh/environment': No such file or directory
chown: cannot access `/home/git/.ssh/environment': No such file or directory
2015/08/24 22:46:08 [.../models/publickey.go:76 init·4()] [E] fail to create '/home/git/.ssh': mkdir /home/git: file exists
```

**Comment by Unknwon** [comment]
Thanks your feedback!

What is the steps/commands to reproduce this error? And what is your host system?

**Comment by szalwia** [comment]
This is a permission issue when the filesystem used for the docker /data volume does not support symbolic links (i.e. ntfs/cifs).

**Comment by Unknwon** [comment]
@szalwia thanks for your tip!

**Comment by Luzifer** [comment]
Sorry for the late response:

- Steps to reproduce: Start that container.
- OS: Ubuntu 14.04 LTS with local disk

It does support symlinks and it does not use any remote storage like cifs. The filesystem is a plain ext4 filesystem.

**Comment by winpat** [comment]
I've the same problem.

* Steps to reproduce: Start that container.
* OS: Debian 8.1 with local disk


```
unknown key type ed25519
Starting OpenBSD Secure Shell server: sshdCould not load host key: /data/ssh/ssh_host_ed25519_key
.
mkdir: cannot create directory `/home/git/.ssh': No such file or directory
chmod: cannot access `/home/git/.ssh': No such file or directory
./docker/start.sh: line 37: /home/git/.ssh/environment: No such file or directory
chown: cannot access `/home/git/.ssh/environment': No such file or directory
chown: cannot access `/home/git/.ssh/environment': No such file or directory
2015/09/23 08:01:56 [.../models/publickey.go:76 4()] [E] fail to create '/home/git/.ssh': mkdir /home/git: file exists
```

**Comment by bruno-durand** [comment]
Same issue on Synology DSM 5

    2015/09/23 14:31:54 [1;31m[.../models/publickey.go:76 4()] [E] fail to create '/home/git/.ssh': mkdir /home/git: file exists[0m

**Comment by Unknwon** [comment]
Thanks all!

Anyone knows how to correct this code block: https://github.com/gogits/gogs/blob/master/docker/start.sh#L29-L33 ? :sweat_smile:

**Comment by winpat** [comment]
It works if you build the image directly from the Dockerfile...

**Comment by Unknwon** [comment]
@winpat hmm... but there is a check if directory already exists... why that doesn't work?

**Comment by Fastidious** [comment]
@Unknwon wouldn't it be:

```
if ! test -d ~/git/.ssh
then
  mkdir ~/git/.ssh
  chmod 700 ~/git/.ssh
fi
```

instead? I think it is just missing the `/` in front of `git`.

**Comment by bruno-durand** [comment]
Cant test it but some thoughts
~git lead to the home of the git user, ~/git lead to the git directory in the home of the user running the script.

if the test is a link it will fail. dont know if it help.

    if [[ -L "$file" && -d "$file" ]]
    then
        echo "$file is a symlink to a directory"
    fi

**Comment by Unknwon** [comment]
Thanks @Fastidious and @bruno-durand , but see code here: https://github.com/gogits/gogs/blob/master/docker/start.sh#L4-L12

If the shell command is wrong, shouldn't be error in these two previous places first?

**Comment by Unknwon** [comment]
Can you guys check with latest Docker image?

**Comment by alvaroaleman** [comment]
The latest docker image broke it for me. I want to use an existing config and to avoid mounting /data, since it contains logs which are supposed to be exposed via ``docker logs``. Thats why I created a simple Dockerfile:

```Dockerfile
FROM gogs/gogs                                                                                                                                                                                                       
RUN mkdir -p /data/gogs/data /data/gogs/conf /data/gogs/log /data/git                                                                                                                                                
ADD conf.ini /data/gogs/conf/app.ini                                                                                                                                                                                 
RUN chmod 0444 /data/gogs/conf/app.ini
```

This doesn't work anymore, since for some reason ``/data/gogs/{data,logs}`` don't exist after running the image, apparently the run script ends up deleting them.

Also, is there a specific reason to have the Dockerfile on .gitignore?

**Comment by Unknwon** [comment]
> Also, is there a specific reason to have the Dockerfile on .gitignore?

That's for old things...

**Comment by Unknwon** [comment]
> This doesn't work anymore, since for some reason /data/gogs/{data,logs} don't exist after running the image, apparently the run script ends up deleting them.

See https://github.com/gogits/gogs/blob/master/docker/s6/gogs/setup#L19-L20 , they should exist.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
