### ISSUE TITLE
Remove hardcoded home directory in modules/ssh/ssh.go

### ISSUE THREAD

**Issue by lf-** [gogits/gogs#1540]
This isn't a good idea.

Also, what is this still doing in master with #1060 closed, saying that it was fixed?

**Comment by tboerger** [comment]
Who cares as it's not used anywhere yet?

**Comment by tboerger** [comment]
And master gets only updated for releases. The question is if it still exists in develop branch.

**Comment by Unknwon** [comment]
> Also, what is this still doing in master with #1060 closed, saying that it was fixed

I type every word in purpose, the original one was:

> closing it with the release

Not necessary mean that's equal to 

> this is fixed

If that's the case, I would say:

> Closed as implemented

Or

> Fixed code has been pushed to `xxx`

But thanks your feedback, I'll leave this open until built-in SSH server is working. :grinning:

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/commit/18c841050b4c843ef723e788d4c0a4c29c67ffe3
