### ISSUE TITLE
docker web show localhost instead of server name 

### ISSUE THREAD

**Issue by pykiss** [gogits/gogs#1541]
`git remote add origin git@localhost:user/repo`

I preffer `git remote add origin ssh://git@myservername:mysshport/user/repo`

**Comment by Unknwon** [comment]
If you setup your SSH port non-22, the link will be `git remote add origin ssh://git@myservername:mysshport/user/repo`

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by bestplay** [comment]
I set up gogs in docker.

Everything working fine.

But it show the container URL: localhost:3000 instead of the outer physics host

When I add drone. drone will get wrong URLs of projects and fails when git clone of builds.

**Comment by Unknwon** [comment]
@bestplay because you configured to show "localhost:3000". See https://github.com/gogits/gogs/blob/master/docker/README.md.

**Comment by bestplay** [comment]
#### Drone showing errors
![image](https://user-images.githubusercontent.com/3828277/37336464-68f5da42-26ec-11e8-9b85-bbb9df5a8221.png)
#### GOGS clone URL works fine
![image](https://user-images.githubusercontent.com/3828277/37336622-eca33510-26ec-11e8-8ffe-a5c694e2c4e0.png)
#### GOGS app.ini contents
![image](https://user-images.githubusercontent.com/3828277/37336564-c50ab992-26ec-11e8-8d3e-6a70d36f45ac.png)

**Comment by bestplay** [comment]
And I know there is a [go-gogs-client](https://github.com/gogits/go-gogs-client) APIs for drone.

I think the API of repos reponse "localhost:3000" as `clone_url` to drone client.

I missed something?

**Comment by Unknwon** [comment]
@bestplay Configuration on Gogs's side looks good, how did you configure Drone? I think there might be a misconfiguration there.

**Comment by bestplay** [comment]
Here is my .drone.yml 
```
workspace:
  base: /go
  path: src/my_project/code

pipeline:
  backend-server3:
    image: golang
    commands:
      - go build
      - go test
```
#### docker-compose.yml of drone
![image](https://user-images.githubusercontent.com/3828277/37381042-274b3a1c-2776-11e8-8263-450d64bea8fe.png)

**Comment by bestplay** [comment]
This "localhost:3000" string can only come from gogs' docker-compose configuration. 

And the `clone_url` is given by gogs' web APIs. 

Am i wrong?

**Comment by bestplay** [comment]
Also i didn't dig Gogs's source code deep enough to find out how Gogs's APIs get `clone_url` and response to Drone.

**Comment by Unknwon** [comment]
Running out of ideas... the Clone URL exposed to API is the same as web interface, so if you're web interface looks good, API is good.

I suspect Drone didn't read `DRONE_GOGS_URL` correctly and fall back to default URL which is `http://localhost:3000`. Do you mind open a new issue (refer to this thread) to track down this issue? I need to setup my test Drone installation to see where is the problem.

**Comment by lk0606** [comment]
> @unknwon Thank you for your quick response.
> 
> I follow the README.md set my app.ini as below:
> 
> ```
> [server]
> DOMAIN           = xxx.200.55.221
> HTTP_PORT        = 3000
> ROOT_URL         = http://xxx.200.55.221:10080/
> DISABLE_SSH      = false
> SSH_PORT         = 22
> START_SSH_SERVER = false
> OFFLINE_MODE     = false
> ```
> 
> My docker-compose export port is 10080.
> 
> I `prune -f` my containers and restarted all of them.
> 
> Then gogs is showing the right clone URL.
> 
> But the drone still get clone_url localhost:3000
> 
> `fatal: unable to access 'http://localhost:3000/xxx'`

Did you solve it
