### ISSUE TITLE
A way to skip TLS verify for SMTP authentication

### ISSUE THREAD

**Issue by stewartpark** [gogits/gogs#1542]
The following error occurs when the SMTP server uses a self-signed certificate, and there seems to be no way to work around this. 

```
2015/08/26 17:48:06 [W] Fail to login(foo@bar.com) by SMTP(Foobar): x509: certificate is valid for xxxxxxxxxxxx, not mail.bar.com
```

Is there a way to use self-signed certificates for SMTP authentication? Or is the option omitted on purpose?

Thanks,

**Comment by Unknwon** [comment]
Hi there,

yes, please see http://gogs.io/docs/advanced/configuration_cheat_sheet.html#mailer `SKIP_VERIFY`. :grinning:

**Comment by stewartpark** [comment]
I have tried this, but it didn't work. Does this also apply to authentication methods as well?

(I'm talking about the methods you can auto-register with email accounts; along with LDAP and PAM)

**Comment by Unknwon** [comment]
@stewartpark Oh! OK! My bad... :joy:

All right, I see the problem, I can add same config option for SMTP auth, too.

**Comment by Kruemmelmonster** [comment]
i can assure that its already implemented! he is right with the skip_verify i am using it. be sure to add it under `[Mailer]`

**Comment by stewartpark** [comment]
The below is my mailer configuration:

```
[mailer]
ENABLED = true
HOST = mail.bar.com
FROM = """"No-reply" <noreply@bar.com>"""
USER = foo@bar.com
PASSWD = pa$$
SKIP_VERIFY = true
```

If I'm doing something wrong, please let me know :)

and in my opinion, even if it was able to do so by changing the `SKIP_VERIFY` option, I don't think that's a wise architectural decision. What if an organization has multiple means of authentication and some of them should not skip the verification? (e.g. multiple SMTP servers and LDAP)

The authentication methods are currently stored in the database in the `login_source` table, maybe add a new column that can suggest if the gogs server should skip TLS verify or not?

**Comment by Unknwon** [comment]
Hi, I've added an option when create SMTP auth on `develop` branch, please help test again!

**Comment by Unknwon** [comment]
Closed as implemented. :tada:

**Comment by mwaeckerlin** [comment]
It would be nice to have an option to remove StartTLS at all.

Typical use case: In a docker swarm stack, smtp is another image nearby with internal access only, so there is no need do enable TLS for internal only communication.

**Comment by Unknwon** [comment]
>Typical use case: In a docker swarm stack, smtp is another image nearby with internal access only, so there is no need do enable TLS for internal only communication.

@mwaeckerlin Good point, please feel free to file an issue about this.

**Comment by mwaeckerlin** [comment]
@Unknwon, I solved the problem by extending [mwaeckerlin/postfix-tls](https://github.com/mwaeckerlin/postfix-tls) from [mwaeckerlin/postfix](https://github.com/mwaeckerlin/postfix). So, works for me now…
