### ISSUE TITLE
Support running on sandstorm.io

### ISSUE THREAD

**Issue by timshannon** [gogits/gogs#1543]
Just a quick feature request, but it would be fantastic to run gogs from a [sandstorm](https://sandstorm.io/) instance.  Sandstorm already has gitlab as an app.

**Comment by Unknwon** [comment]
Thanks your feedback!

Sandstorm looks great, but after reading through their docs, it may require much work on testing and modifications on Gogs.

But I'll leave this issue open to see if somehow Gogs can just easily integrate with Sandstorm as development of Gogs is going on.

**Comment by timshannon** [comment]
Looks like this has since been done:

https://apps.sandstorm.io/app/d9ygf47xrtnw12j92cyt6cu8ut75esx01u4q3kcrn8415w9qzzgh

**Comment by strugee** [comment]
@Unknwon would you take PRs to upstream the work done in cem/gogs-sandstorm? I'm somewhat interested in taking this on.

**Comment by Unknwon** [comment]
@strugee I remember that branch has hard/dirty changes to the main branch, if we can solve that, I'm happy to review.

**Comment by bkcsoft** [comment]
If it can be cleanly put in a separate build-tag then it could be an option
