### ISSUE TITLE
Creating new repository fails occasionally

### ISSUE THREAD

**Issue by vijairaj** [gogits/gogs#1544]
The issue happens occasionally and I am not able to reproduce it consistently. 

Gogs Version: 0.6.5.0820 Beta (Running from source)
git version: 1.9.5.msysgit.1
OS: Windows XP
Error message: 

```
2015/08/27 09:30:58 [...routers/repo/repo.go:131 CreatePost()] [E] CreatePost: initRepository: git clone: fatal: destination path 'C:\WINDOWS\TEMP\203125000' already exists and is not an empty directory.
```

Like the message above says, the path already exists and it has a .git folder which seems to be a partially initialized git repo.

I am able to successfully create a repo after retrying the process without having to actually do anything on the server.

**Comment by Unknwon** [comment]
Thanks your report!

It looks like that somehow the temp dir for init a repository is being used by some other apps.

But should be straightforward to fix it.

**Comment by Unknwon** [comment]
Hi there, I've pushed fix to `master`, please help test!

**Comment by vijairaj** [comment]
I seem to face a different issue now, repo creation fails consistently.

Version: 0.6.7.0829 Beta 

```
2015/08/30 19:33:36 [...routers/repo/repo.go:121 CreatePost()] [E] initRepository: initRepoCommit: git push: remote: error: hook declined to update refs/heads/master[K
To d:\__ALL_DATA__\gogs-repos\tester\rep2.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'd:\__ALL_DATA__\gogs-repos\tester\rep2.git'

2015/08/30 19:33:36 [...routers/repo/repo.go:91 handleCreateError()] [E] CreatePost: delete repo directory tester/rep2 failed(2): remove d:\__ALL_DATA__\gogs-repos\tester\rep2.git\objects\66\1ec2002ed247054eab6defcd68d50903cbdb47: Access is denied.
2015/08/30 19:34:17 [...routers/user/home.go:319 Profile()] [E] GetUserByName: user does not exist: [uid: 0, name: repo]
2015/08/30 19:36:29 [...routers/repo/repo.go:121 CreatePost()] [E] initRepository: initRepoCommit: git push: remote: error: hook declined to update refs/heads/master[K
To d:\__ALL_DATA__\gogs-repos\tester\rep3.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'd:\__ALL_DATA__\gogs-repos\tester\rep3.git'

2015/08/30 19:36:29 [...routers/repo/repo.go:91 handleCreateError()] [E] CreatePost: delete repo directory tester/rep3 failed(2): remove d:\__ALL_DATA__\gogs-repos\tester\rep3.git\objects\09\98641d21b1dc069aebac78f8ee8f618284ed4a: Access is denied.
```

**Comment by vijairaj** [comment]
On more testing, the above issue seems to be a caused because of running the server as a service with Local System Account. Running it as a service with Administrator or running it in console didn't have any issues.

**However I have a couple of concerns:**
(1) The logic to construct temp dirname still has possibilities of duplicates
> tmpDir := filepath.Join(os.TempDir(), "gogs", repo.Name, com.ToStr(time.Now().Nanosecond()))

[Time.Nanosecond document](http://golang.org/pkg/time/#Time.Nanosecond) says:
>  Nanoseconds returns the duration as an integer nanosecond count. 

and this is what I got on my machine:

    C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\gogs\repo6\812500000

(2) The temp directory is not deleted.

**Comment by Unknwon** [comment]
> The logic to construct temp dirname still has possibilities of duplicates

It is certainly possible in very edge case, but is low enough that two person create exactly same repository at exactly same nano second.

> The temp directory is not deleted. 

Gogs does execute the delete commands, but as your error shows that `Access is denied`. So... I don't know how to help on this one.

**Comment by vijairaj** [comment]
>> The logic to construct temp dirname still has possibilities of duplicates

> It is certainly possible in very edge case, but is low enough that two person create exactly same repository at exactly same nano second.

On other OS' I agree, but on XP it looks to be providing only millisecond resolution.

>> The temp directory is not deleted.

> Gogs does execute the delete commands, but as your error shows that Access is denied. So... I don't know how to help on this one.

The access issue went away after I changed the service to run as Administrator however the issue with delete is that a directory hierarchy like `tmp\gogs\repo6\812500000` is created but after deleting `tmp\gogs\repo6` still stays. Instead I would suggest to create a temp directory like `tmp\gogs-repo6-812500000`.

**Comment by Unknwon** [comment]
> On other OS' I agree, but on XP it looks to be providing only millisecond resolution.

Hmm... this is... I don't know what to do yet.

**Comment by Unknwon** [comment]
> Instead I would suggest to create a temp directory like tmp\gogs-repo6-812500000.

OK, it's on `develop` now.

**Comment by vijairaj** [comment]
Tested it in _Version: 0.6.9.0903 Beta_ and it works great.
This issue can now be closed - thanks.

**Comment by Unknwon** [comment]
@vijairaj thanks your confirmation!
