### ISSUE TITLE
Cross reference the commit from the issue when it is closed by the commit

### ISSUE THREAD

**Issue by vijairaj** [gogits/gogs#1545]
I believe this is a feature request rather than an issue.

I am able to close an issue through a commit but when viewing the issue I can't identify the commit that fixes the issue. It would be great if the link to the commit is provided from the issue.

Gogs Version: 0.6.5.0820 Beta running from source on 64 bit Ubuntu 14.04

**Comment by Unknwon** [comment]
Oh yes, I think it is implemented a while ago, but forgot to put commit reference back after redesign the issues page. :sweat_smile:

**Comment by Unknwon** [comment]
Hi, I've pushed fix on `develop`, you can also test on https://try.gogs.io . :grinning:

**Comment by vijairaj** [comment]
Thanks, this works now. But I have two observations...

1. When the issue is mentioned multiple times in a comment, then a reference is created for each mention of the issue.
2. For longer comments it would be convenient to have the comment collapsed and just the first line displayed.

**Comment by Unknwon** [comment]
> When the issue is mentioned multiple times in a comment, then a reference is created for each mention of the issue.

I got your point 2, but for this, I'm not quite sure? Can you give an example?

**Comment by vijairaj** [comment]
Ok, for (1) Say for e.g. I have a comment like below:
> This commit fixes `#32` and partially fixes `#33`. There are more changes to follow for `#33`.

Now in the issue page for `#33`, the comment will be repeated two times.

**Comment by Unknwon** [comment]
@vijairaj OK, I got it!

**Comment by Unknwon** [comment]
Hi, I've pushed fix about duplicated refs to `develop` and have updated try.gogs.io as well.

**Comment by vijairaj** [comment]
Testing it on _Version: 0.6.9.0903 Beta_, I executed some test cases and could see that the actual issue with multiple reference is fixed now. 

But I see a behaviour that needs some more investigation, the gist is that for a comment like: `Fixes #2... but there are more changes comming for #2. It will follow fixes for other issues in #1.` I see both `#1` and `#2` closed.

**Comment by Unknwon** [comment]
> But I see a behaviour that needs some more investigation, the gist is that for a comment like: Fixes #2... but there are more changes comming for #2. It will follow fixes for other issues in #1. I see both #1 and #2 closed.

Hi, it seems that I can't produce this. Can you prove that it can be reproduced on https://try.gogs.io .

**Comment by vijairaj** [comment]
It works correctly. Sorry for the mix-up, I was checking out the new pull request feature and since the ids are allocated from the same range for issues and pull requests, I got a little carried away.

**Comment by Unknwon** [comment]
OK great, thanks your confirmation!
