### ISSUE TITLE
Attachment does not work with suburl

### ISSUE THREAD

**Issue by harmw** [gogits/gogs#1548]
I'm running Gogs behind a proxy, using a https://bla.bla/gogs url as entry. This runs fine, except from uploading attachments. Those receive a 404. Digging a little shows uploads always go to /issues/attachments, which doesn't exists at that level.

Like this: https://github.com/gogits/gogs/blob/master/cmd/web.go#L373

**Comment by Unknwon** [comment]
Which version of Gogs are you running?

**Comment by Unknwon** [comment]
> Like this: https://github.com/gogits/gogs/blob/master/cmd/web.go#L373

This is the router path, has nothing to do with system path...

**Comment by harmw** [comment]
oh ok, didn't know that :)

This is with:
 Version: 0.6.5.0820

**Comment by Unknwon** [comment]
That's OK.

>  Those receive a 404.

Can you open web console and tell me what exact URL JS was requesting?

**Comment by harmw** [comment]
POST /issues/attachments
Also:
 GET /attachments/bb37fe2c-8a19-4d9d-9281-f3c210bfc8c6

**Comment by Unknwon** [comment]
I just tested upload attachment is working fine on https://try.gogs.io .

So... are you running under suburl ?

**Comment by harmw** [comment]
yep, as I said :)
http://git.bla.bla
This redirects to:
https://everything.bla.bla/code
Which proxies to http://192.168.0.254:3000

Using mod_rewrite the uploading works, but sometimes throws a CSRF error...

**Comment by Unknwon** [comment]
Sorry I didn't notice that.

Have pushed fix on `develop`!

**Comment by harmw** [comment]
Cool, thanks!

Does this take care of the CSRF as well?

**Comment by Unknwon** [comment]
Gogs uses dropzone.js which handles CSRF for you in the HTML.

For `mod_rewrite`, I can't promise anything because your CSRF can change constantly to keep your data safe.

**Comment by Unknwon** [comment]
Close as implemented. :tada:
