### ISSUE TITLE
The syntax highligther interprets shell scripts incorrectly

### ISSUE THREAD

**Issue by mortie** [gogits/gogs#1549]
The syntax highlighter interprets a `/*` in my shell script as the start of a block comment, when that's not how shell scripts work: http://git.mort.coffee/mort/nixConf/src/master/bin/mnote#L21

The line in question:

    		for F in "$P"/*.md; do

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/gogs/gogs

**Comment by Unknwon** [comment]
Close as fixed.
