### ISSUE TITLE
undefined: gogs.Payloader

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#1550]
I upgraded my gogits and after deleting the gogs folder and:

    git clone --depth=1 -b develop https://github.com/gogits/gogs.git
    cd gogs
    go get -u -tags "sqlite" ./...
    go build -tags "sqlite"

there was the following error messange:

    # github.com/gogits/gogs/models
    models/webhook.go:288: undefined: gogs.Payloader

**Comment by peppage** [comment]
You have the old version of github.com/gogits/go-gogs-client

**Comment by focmb** [comment]
Thanks. I updatet go-gogs-client and now gogits 0.6.7 beta works.

**Comment by Unknwon** [comment]
@peppage thanks for your answer!

Actually go get -u ./... should update your reps to latest version if they were downloaded by go get command. Not sure it's not working sometimes, but glad you solved the problem, and I'm changing APIs a lot these days so you would expect similar errors again. :)

**Comment by focmb** [comment]
I downloaded the latest version via **git clone**, not **go get**

**Comment by Unknwon** [comment]
@focmb Yes, but i see in your comment you use `go get -u ./...` for dependencies.
