### ISSUE TITLE
Username being blocked by absence of validation

### ISSUE THREAD

**Issue by greut** [gogits/gogs#1555]
Hi,

I've created an account from work today without realizing that I didn't had access to my e-mails. Hence, I wanted to activate it later when I came back home. But, the validation is expired and now, my username is bagysied: `Username has been already taken.` :cry: 

Expected result: a username is really booked only when the account has been properly activated.

**EDIT:** the password recovery works as a work around though.

**Comment by Unknwon** [comment]
Thanks your feedback!

> Expected result: a username is really booked only when the account has been properly activated.

So what to do when both users are activated at the same time?

**Comment by greut** [comment]
Since, it managed to be fixed by going for the lost password session. It could tell something along those lines.

_Ooops, it seems that this username already exists. If it's yours, you may want to **Sign in**._

**Comment by Unknwon** [comment]
> Ooops, it seems that this username already exists. If it's yours, you may want to Sign in.

This looks good but too verbose in my opinion.

`Account already exists` tells enough information that username is used by you or someone else.

**Comment by matt-h** [comment]
Perhaps delete the account if the validation expires and hasn't been activated yet?

**Comment by Unknwon** [comment]
@matt-h that is what exactly in my mind, a expiration time for inactive account(PS: admin can remove them manually in admin panel right now).

**Comment by greut** [comment]
@Unknwon Yup, you're probably right.

Probably then, the activation page should (or could) give you a way to re-send a fresh activation link or something.

**Comment by Unknwon** [comment]
@greut I believe there is a re-send button....

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/9615360/9417d748-50c5-11e5-88a8-d5de5f242d3c.png)

**Comment by greut** [comment]
Dammit, epic fail ;-) Let's close this then.

**Comment by Unknwon** [comment]
@greut :wink:
