### ISSUE TITLE
Team member in Organization cannot Publish release

### ISSUE THREAD

**Issue by iballbar** [gogits/gogs#1559]
Hi , I have a problem member in Team cannot publish release
When press Publish release button got error 403 Forbidden
[Macaron] Completed Organize_name/repo_name/releases/new 403 Forbidden in 325.0253ms

repo_name is in team repositories , Owner is Organize_name
even I've add admin right to this member.

Gogs Version: 0.6.5 from binary
OS: Windows Server 2007

Best Regards

**Comment by iballbar** [comment]
PS. Sorry If this is the right way,  then I request a feature for add permissions to member in team can publish releases. 

Thank you in advance.

**Comment by Unknwon** [comment]
Thanks your feedback!

Yeah, I'm thinking that team who has `admin` level access can public release as well.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1181.
