### ISSUE TITLE
modify ssh url/path

### ISSUE THREAD

**Issue by port22** [gogits/gogs#1560]
Hi, as per default the ssh clone url/path is like: 

$RUN_USER@$HOSTNAME:$USER/$REPO.git

As I am embedding gogs into a server configuration with existing ssh users, I have to modify this like so:

$USER@$HOSTNAME:$REPO.git

How could I achieve that? 
The intention behind is that I have symlinked every user's repository into the actual user's home directory.

And furthermore, I don't really "like" the .git - extension in the URL and directory names. Can't I clean out that too?

Thanks a lot!!

**Comment by Unknwon** [comment]
> As I am embedding gogs into a server configuration with existing ssh users, I have to modify this like so:

> $USER@$HOSTNAME:$REPO.git

> How could I achieve that? 

It is workable to add a config option to not use `RUN_USER`.

> And furthermore, I don't really "like" the .git - extension in the URL. Can't I clean out that too?

I just tested that currently implementation already supported this(without `.git` suffix).

**Comment by port22** [comment]
>It is workable to add a config option to not use RUN_USER.
If I delete the config option RUN_USER then gogs won't start - as the documentation says:  
>Gogs may crash if this value is not set properly

> but you can actually ignore it
only http-clone works without this extension. The real repo folder has this extension, so I have to add this everytime I want to access the repo. I'm very lazy in typing useless stuff :D

**Comment by Unknwon** [comment]
> It is workable to add a config option to not use RUN_USER.

Well, I mean I can add this feature...

> only http-clone works without this extension. The real repo folder has this extension, so I have to add this everytime I want to access the repo. I'm very lazy in typing useless stuff :D

No, Gogs's implementation doesn't care about this extension. If you can't do that, probably mean you didn't config things right...

**Comment by port22** [comment]
> Well, I mean I can add this feature...

Oh I understand :-)  Actually it would be fine to have the freedom to completely modify the url with variables.

> Gogs's implementation doesn't care about this extension

yea right, but it creates the repo folders with that extension, and that's what I actually want to avoid

**Comment by port22** [comment]
If I'd pull the source, can't I modify the code where this url is generated to my needs?

**Comment by Unknwon** [comment]
> because via ssh I am not accessing Gogs at all

Yeah, that's what I expected.

> but it creates the repo folders automatically with that extension,

Can't change that at least not in neat future. :flushed:

> Actually it would be fine to have the freedom to completely modify the url with variables.

The `user` part is the only thing left to custom right now.

**Comment by Unknwon** [comment]
> If I'd pull the source, can't I modify the code where this url is generated to my needs?

If you mean hack Gogs source code, https://github.com/gogits/gogs/blob/master/models/repo.go#L314

**Comment by port22** [comment]
> If you mean hack Gogs source code, https://github.com/gogits/gogs/blob/master/models/repo.go#L314

yeah that's it !  And ... How much places have to be modified to remove the .git-extension from the folders? (creating,modifying functions..)

**Comment by Unknwon** [comment]
>  How much places have to be modified to remove the .git-extension from the folders? (creating,modifying functions..)

For a quick thought, https://github.com/gogits/gogs/blob/master/models/repo.go#L768

**Comment by port22** [comment]
perfect, I think I just modify the source to suit my needs. Thank you very much  :-)

**Comment by tboerger** [comment]
You know that you can use an SSH key only once per use? And the ssh keys for accessing gogs repositories are limited to git actions only, so no normal SSH connection anymore.

**Comment by port22** [comment]
SSH keys are managed within the users home directorys as it is default on unix systems. I don't use the gogs keystore at all. Users have full SSH access and own .ssh-directories.

**Comment by Unknwon** [comment]
@port22 OK... are you still want me to add config option for the `user` part or you're happy with hack on source code?

**Comment by tboerger** [comment]
So you are not using the user and key management of gogs? I still don't get it how that should ever work :)

**Comment by tboerger** [comment]
And i don't get it why you want to use gogs in that case :)

**Comment by Unknwon** [comment]
> So you are not using the user and key management of gogs? I still don't get it how that should ever work :)

Clone with abspath on the server can actually work...

**Comment by tboerger** [comment]
Sure, that can work. But than there is still the question why he needs or wants gogs as he's anyway doing everything different. If he just wants a UI for browsing repos he don't need gogs :)

**Comment by Unknwon** [comment]
> Sure, that can work. But than there is still the question why he needs or wants gogs as he's anyway doing everything different. If he just wants a UI for browsing repos he don't need gogs :)

I don't know... just used as web UI could work since Gogs reads info of repo directly from git data, and not rely on push/pull events.

**Comment by tboerger** [comment]
Sorry but this "solution" sounds pretty crappy. There are enough tools out there that are used just for displaying repos, and they are doing nothing else and they are doing it pretty good

**Comment by Unknwon** [comment]
> There are enough tools out there that are used just for displaying repos, and they are doing nothing else and they are doing it pretty good

:eyes: maybe not enough tools to setup so easy...

**Comment by port22** [comment]
>  I still don't get it how that should ever work 
Please don't be confused with how I handle the ssh connections, that's not the reason for this issue.
I just wanted to modify the line which is displayed for copying the ssh url to the clipboard for cloning, since every user logs in as himself, since every user already has a full ssh account.

And yes, I tried out the alternatives. Gitlab is too much (and setup is a mess), and the only-displaying-tools are not enough.
Gogs is just perfect :-) 

@Unknwon: I just wanted to configure the line to clone. I am certainly one of the very few who handle it  the typical linux openssh way with user based authorized_keys and it is actually against the design of Gogs which has this all built-in, but unfortunately I can't use it just because it's all already there.

But I think it would be not bad idea to just omit the .git-extensions. Or does someone ever need it? :-)

**Comment by tboerger** [comment]
But why do you want to reinvent the wheel? ALL git hosting solutions are doing it through the git user...

And which functionality of gogs are you using now? If I see it correctly just the repo browsing functionality...

**Comment by Unknwon** [comment]
> But I think it would be not bad idea to just omit the .git-extensions. Or does someone ever need it? :-)

It is good that Gogs doesn't force you to use its SSH feature, kind of open design I would say. 

But yes, you're really the first seen this as feature, other people just reports as bugs in the exactly opposite way.(why they need to clone by abspath from server). :mask:

**Comment by port22** [comment]
Hm actually I find that the github-alike programs are reinventing the wheel! I am hosting real (not virtual) users with full user homes and very own authorized_keys

**Comment by tboerger** [comment]
All these webbased solutions are serving it as a single user because they are running as a single user for virtual users. I don't know ANY company that tries to solve it like you do, and as I'm working for SUSE i already have seen a lot crazy stuff. You are just using the file browsing functionality, so why not simply use a tool like https://github.com/klaussilveira/gitlist (PHP), http://klausdemo.lophus.org/ (Python), http://ginatra-na.rhcloud.com/ (Ruby), http://www.gitalist.com/ (Perl)? Just to name some in various languages. They are pretty nice and they are fine for browsing repos. All the key features of gogs are just not usable for you Oo

**Comment by Unknwon** [comment]
Maybe @port22 just like Gogs. :eyes:

**Comment by tboerger** [comment]
@Unknwon if he likes it so much he would just use the features of Gogs. For example including PAM auth as this is anyway available for Gogs ;)

**Comment by Unknwon** [comment]
@tboerger I'm just guessing, what you have is what you need and discard rest of everything is the best way to work.

**Comment by port22** [comment]
@tboerger  I'ts ridiculus that I discuss about that. This is no crazy stuff. That's the original way of Authentication of Users agains a Server. There are still people out there who have real system accounts with ssh-keys per person. Why should I use the virtual implementation of an application (what actually makes it more complex as it could be) when I already have full configured SSH for all users? Althoug I did not had a look at the PAM auth I think that wouldn't be a solution because it would bypass my ssh configuration and would require just more configuration.

I already have what I want, except the copy-to-clipboard url doesn't fit my server configuration.

**Comment by Unknwon** [comment]
Well... just realize you ignored my original question, but looks like problem is solved now.

**Comment by port22** [comment]
alright, I adjusted the lines you mentioned, go build and voila, the url suits my needs and the .git folder extension is deleted. I'm happy :+1:  thankya :-)

**Comment by Unknwon** [comment]
@port22 :beers:
