### ISSUE TITLE
LDAP Binding Broken in 0.6.5

### ISSUE THREAD

**Issue by samlcharreyron** [gogits/gogs#1561]
The refactored LDAP settings in commit 7d84d4a8f0cb30df04241f528ed74672a485274a has broken authentication for me.

**Before**
I used the login credentials as bind credentials. Using the Ms Ad SA, attribute, I could format the login credential to match the LDAP logins on my server.

**Now**
Have the option of :
* Specify a bind DN (username) and bind password. The password is displayed in plain text on the configuration page and stored in plaintext in the DB. This is unsafe and not an option for us.
* Use an anonymous bind which is not an option for me. 

I would like to be able to do as before and use the user's login crendentials as LDAP bind credentials and not use fixed LDAP credentials.

**Comment by Unknwon** [comment]
Thanks your feedback!

I would try to see if it's possible to make two types of LDAP exists at same time so users can have more choice, like your case.

**Comment by SergioBenitez** [comment]
Note that this is being tracked on #1524.

**Comment by SergioBenitez** [comment]
@samlcharreyron #1581 should have fixed this.

**Comment by Unknwon** [comment]
any updates on this?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
