### ISSUE TITLE
Labels Template

### ISSUE THREAD

**Issue by ajtroxell** [gogits/gogs#1562]
It would be extremely useful for organizations like mine who typically create the sams issue labels for every repo to be able to set default labels for every repo. Typically we use Bug, Enhancement, Third-Party, and Feedback Needed.

**Comment by Unknwon** [comment]
Thanks your feedback!

Looks like a very useful feature!

So to make things clear, my quick thought about this(list of thoughts for discussion):

1. Allow clone labels from another repo when create a new repo
2. Create labels template for organization or user

How do you think?

**Comment by ajtroxell** [comment]
Both would work well. I think at a minimum #2 would be ideal. Kind of like my previous request with readme files and like you have done with .gitignore files, allowing standardization across repos is a great option.

**Comment by Unknwon** [comment]
OK.. I see. So just like README template, now add a labels template, and there is a default one, also you can default custom ones as you want.

**Comment by ajtroxell** [comment]
Exactly mate!

Sent from Outlook




On Wed, Sep 2, 2015 at 11:20 AM -0700, "无闻" <notifications@github.com> wrote:
OK.. I see. So just like README template, now add a labels template, and there is a default one, also you can default custom ones as you want.

---

**Comment by vijairaj** [comment]
+1. The colors for the label should be copied as well so that they look consistent across projects.

**Comment by ajtroxell** [comment]
Agreed. Perhaps template is a txt file structured like:
Label | Text Color | Label Color
Or just the label color. Some examples
Bug | #FF0000Enhancement | #00FF00Third-Party | #FFFFFF | #000000





On Wed, Sep 2, 2015 at 8:00 PM -0700, "vijairaj" <notifications@github.com> wrote:
+1. The colors for the label should be copied as well so that they look consistent across projects.

---

**Comment by JokerQyou** [comment]
GitHub has a small set of predefined labels for every repository, I think that would give us some ideas.

**Comment by moltam** [comment]
Why the bug label? This is a feature request. Or am I missing something?

Also +1 for this feature :)

**Comment by Unknwon** [comment]
@moltam you're right :sweat_smile:

**Comment by lepe** [comment]
For the moment, you can "copy" them from your database (e.g. using MySQL): `INSERT INTO label SELECT 0,$TARGET_REPOS_ID,name,color,0,0 FROM label WHERE repo_id = $SOURCE_REPOS_ID;`. Not sure if it may have side effects, but so far seems to work. (to get the repo_id: `SELECT id,name FROM repository`);

**Comment by 0xbaadf00d** [comment]
For a first try, I can implement this feature with text files on the directory `custom/label` (or `custom/conf/label` like translation customization ?). The filename will be used in the select box and file will use this format:

    color <tab> name

By example: 

__custom/conf/label/github__
```
#fc2929 bug
#cccccc duplicate
#84b6eb enhancement
#159818 help wanted
#e6e6e6 invalid
#cc317c question
#ffffff wontfix
```

The selection of the labels model to use will be made during the creation of a repository (_/repo/create_). If they are no label template files on the directory, the select box will not be displayed.

Of course, if the need is changing in the future (ie: different templates per organizations), we can move from simple text files to a  specifif models on database (ie: org_label_tmpl)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3459, please help test on `master` branch or https://try.gogs.io.

**Comment by gsantner** [comment]
Hi there, thanks for implementation. Tried it on my instance and found no problems so far.
I created a small (hacky) script to export issue labels and colors from github repositories. I thought maybe someone wants todo similar, so here's the bash script:

```
#!/bin/bash
URL="https://github.com/gogits/gogs/labels"
[ -n "$1" ] && URL="$1"
labelFile="/tmp/labels.html"
wget "$URL" -O "$labelFile"
cat "$labelFile" | grep "label label-link" | cut -b 59- | sed -r 's/%2F/\//g' | sed -r 's/%20/ /g' \
                        | cut -d \" -f 1,3 | sed -e "s/\"background-color://" | cut -d ";" -f 1  \
                        | awk 'BEGIN {OFS=FS=" ";} {temp=$NF; $NF = ""; sub(",$", ""); print temp, $0}'

```

Checking out labels of Gogs:
```
bash extractLabelsFromGithub.sh "https://github.com/gogits/gogs/labels"

#f7c6c7 dont send pull request 
#009800 help wanted 
#fc2929 kind/bug 
#c7def8 kind/deployment 
#c7def8 kind/documentation 
#c7def8 kind/enhancement 
#5319e7 kind/feature 
#0052cc kind/plugin 
#006b75 kind/proposal 
#e11d21 kind/security 
#eb6420 kind/third-party 
#006b75 kind/ui 
#1d76db open for pull request 
#e11d21 priority/critical 
#feffc0 priority/low 
#F5F3EB priority/maybe 
#cccccc reviewed/duplicate 
#e6e6e6 reviewed/invalid 
#ffffff reviewed/wont fix 
#ffffff reviewed/wont merge 
#0052cc status/assigned to community 
#1A3661 status/assigned to maintainer 
#fef2c0 status/await 
#fbca04 status/needs feedback 
#eb6420 status/needs reproduce 
#fef2c0 status/reported upstream 
#fad8c7 status/review later 
#0e8a16 status/reviewed 
#bfe5bf status/waits for review 
```

Just visit the `Issues -> Labels` page and pass the url as parameter.

**Comment by Unknwon** [comment]
@gsantner Awesome, useful! Would you mind post this to https://discuss.gogs.io/t/how-to-use-predefined-label-templates/599?

**Comment by gsantner** [comment]
Yeah, will add it in some minutes.
