### ISSUE TITLE
Show regarding repo in issue overview

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#1567]
In the issue overview alle issues of all repos are shown. But it is not easy to see, which issue belongs to which repo (see screenshot). The repo name should be part of the issue description.
![pic1](https://cloud.githubusercontent.com/assets/261217/9652348/bbe059d4-521a-11e5-8113-a512576ff6f1.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/9652939/f807f62e-51ed-11e5-8500-2f7ebb3069a2.png)

Does this one look like to you? Or you want to clickable link?

**Comment by focmb** [comment]
I mean the name of the repo, not the status of the issue. In my screenshot I can not see, which repo belongs to the issues. 

For example: my first issue belongs to the repo "BTLogger_GoogleMaps". This name should be part of the repo. Instead of the status in your screenshot ("opened") there should be the name ("BTLogger_GoogleMaps"). See my new screenshot.


![pic2](https://cloud.githubusercontent.com/assets/261217/9653361/3db0f0a6-5223-11e5-8753-3faddc5da64d.png)

**Comment by Unknwon** [comment]
> I mean the name of the repo, not the status of the issue. In my screenshot I can not see, which repo belongs to the issues.

I think you focused on the completely wrong thing of my screenshot which I have already marked as red box..

**Comment by focmb** [comment]
Aaah, ok. I see the repo number. This could be very helpful

**Comment by Unknwon** [comment]
Yeah, so I was asking if you need the repo name to be clickable? 

PS: code is already in `develop` and deployed to try.gogs.io

**Comment by focmb** [comment]
a clickable repo name should be a nice to have but it is not necessary.

**Comment by Unknwon** [comment]
OK, closing now. :tada:

**Comment by focmb** [comment]
Thanks a lot. Now it is possible to see issue with its repos in the overview

**Comment by Unknwon** [comment]
:clap:
