### ISSUE TITLE
can't delete user

### ISSUE THREAD

**Issue by YoungHu** [gogits/gogs#1568]
Hi Unknown,

When I try to delete a normal user with manager role, after click the confirm button find that user have not deleted, my gogs version is ***0.6.8.0902 Beta***, you can check it at your side. app compiled from *develop* branch

**Comment by Unknwon** [comment]
Thanks your feedback!

> When I try to delete a normal user with manager role, after click the confirm button find that user have not deleted

Are you saying delete by admin or delete yourself?

**Comment by Unknwon** [comment]
Never mind, reproduced. :mask:

**Comment by Unknwon** [comment]
Ok, fixes have been push to `develop` and updated try.gogs.io as well.

**Comment by YoungHu** [comment]
tested, issue fixed. thanks

**Comment by Unknwon** [comment]
Thanks your confirmation!
