### ISSUE TITLE
Can not install on MySQL because of a duplicate index

### ISSUE THREAD

**Issue by dasJ** [gogits/gogs#1569]
When installing gogs 0.6.5.0815 Beta (Go 1.5) using an empty MySQL database, the following error is shown in the wizard:
```
Database setting is not correct: Error 1061: Duplicate key name 'IDX_comment_issue_id'
```

EDIT: Default DB Type is Aria. Can this be a problem?

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your MySQL version?

**Comment by dasJ** [comment]
```
Server type: MariaDB
Server version: 10.0.21-MariaDB-log - MariaDB Server
Protocol version: 10
```

**Comment by Unknwon** [comment]
I'm not sure what exact meaning of DB type, but if it means DB engine, Gogs only works with [XORM](http://github.com/go-xorm/xorm)) with InnoDB.

**Comment by YoungHu** [comment]
@dasJ  MariaDB is a branch of MySQL but not means it's MySQL. So you'd better change your DB to MySQL.

**Comment by dasJ** [comment]
MariaDB is a drop-in replacement for MySQL. It is fully compatible to MySQL but offers more features (like the Aria Engine which was my default). Setting the Engine to InnoDB fixes the problem. To prevent problems with the default engine, Gogs should explicitly set the engine when creating the tables.

**Comment by tboerger** [comment]
> @dasJ MariaDB is a branch of MySQL but not means it's MySQL. So you'd better change your DB to MySQL.

It would be better to use only MariaDB and no more MySQL ;)

**Comment by Unknwon** [comment]
> When installing gogs

What is the exactly time for this? Click on `install` button in install page?

**Comment by dasJ** [comment]
Yes, I click the button, it takes a while and then the error appears. When I check the database, there are already some tables created, but using Aria.

**Comment by Unknwon** [comment]
OK, was having it when [normal start](https://github.com/gogits/gogs/blob/develop/models/models.go#L198), but missing for install which has been added on `develop` branch.

**Comment by hhenkel** [comment]
@dasJ MariaDB might be a drop-in replacement as long as you're talking about version 5.5.x. With version 10.x there are new features and backports from mysql 5.6.x , which should in theory should not cause trouble (https://mariadb.com/kb/en/mariadb/upgrading-from-mariadb-55-to-mariadb-100/).

**Comment by dasJ** [comment]
Well, I guess this is fixed. Thank you very much!

**Comment by Unknwon** [comment]
@dasJ thanks your confirmation!
