### ISSUE TITLE
go get emits error about xorm and docs submodules

### ISSUE THREAD

**Issue by pmezard** [gogits/gogs#1571]
Hello,
I get the following errors/warnings when go getting gogs with Go 1.5+ on OSX:
```
$ go get github.com/gogits/gogs
# cd .; git --git-dir=~/go/path/src/github.com/go-xorm/xorm/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'docs/manual-en-US'
package github.com/go-xorm/xorm: exit status 1
```

**Comment by Unknwon** [comment]
Thanks your feedback!

But... well... I think it should be reported to [xorm](https://github.com/go-xorm/xorm).

**Comment by pmezard** [comment]
Oh right, I will do that, thanks.

**Comment by Unknwon** [comment]
Thanks for quick response! :wink:

**Comment by pmezard** [comment]
Follow-up here https://github.com/go-xorm/xorm/issues/294

**Comment by Unknwon** [comment]
:clap:
