### ISSUE TITLE
Show current branch in commit overview

### ISSUE THREAD

**Issue by mexthemax** [gogits/gogs#1572]
On the commit overview there is no indication for which branch the commits are (except for the url)

It would be nice to have something like the following 
![branchname](https://cloud.githubusercontent.com/assets/13781012/9656946/e4908422-523c-11e5-998e-f976c7db103e.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by mexthemax** [comment]
There is a similar feature I miss:
When viewing issues for a certain milestone I can't see what milestone (if any) I am viewing at.
GitHub doesn't have this feature either (but at least they show the milestone in the search field).
It would be nice to have some sort of indication that I'm looking at issues only for a certain milestone. :smile:

PS: I don't know if this belongs here, if you want I can open a new issue.

**Comment by Unknwon** [comment]
> When viewing issues for a certain milestone I can't see what milestone (if any) I am viewing at.

I'm not quite understand your request, but https://try.gogs.io/gogs/gogs/issues already has milestone filter.

**Comment by mexthemax** [comment]
Yes you are right, but unless I click on the milestone filter selector (the drop down menu) I don't see that there is a milestone filter applied. The same goes with the other filters.

~~What I meant was something at the top of the page that says something like "You are viewing issues for milestone xy".~~ But I now think it would be better to show what filters are applied. Like for example do not only display the type of filter but also e.g. Milestone: xy as the text for the drop down selector. (see screenshot)
![filter](https://cloud.githubusercontent.com/assets/13781012/9814399/1739eee8-588e-11e5-9df8-53e52b9498c2.png)

This is no problem when I actively select a filter, because then I know that I am only looking at issues for a certain filter. 
But if someone sends me a link to issues with a certain filter applied or if I leave the tab in my browser open and visit it later I don't see that there is a filter applied. It also helps to identify if you misclicked in the filter dropdown menu.

It would help me to recognise what I'm looking at more easily.

**Comment by Unknwon** [comment]
Thanks your suggestion!

Currently, if you open https://try.gogs.io/gogs/gogs/issues?type=all&sort=&state=open&labels=0&milestone=46&assignee=0 , you will see that the issues are only showing the milestone with `mile1`. Label is working the same way.

However, your example screenshot has UI issues with screen in 1024*768, so the better solution is having a search box in Gogs UI as well(which is a completely new feature request and should open another issue)

**Comment by mexthemax** [comment]
> you will see that the issues are only showing the milestone with mile1.

I see your point. But if I don't know if there are other milestones I still don't know if a filter is applied.

> However, your example screenshot has UI issues with screen in 1024*768, so the better solution is having a search box in Gogs UI as well

I think you are right this could be a problem on small screens and a search box is a lot nicer in that case.

There already is an open feature request (issue #938) for a search box and I will post my thoughts there.

**Comment by Unknwon** [comment]
> There already is an open feature request (issue #938) for a search box and I will post my thoughts there.

That would be the best. Thanks!

**Comment by Unknwon** [comment]
Hi, i've pushed fix to `develop` branch and you can also test on https://try.gogs.io/gogs/gogs/commits/master

**Comment by mexthemax** [comment]
This works great and is exactly what I was looking for, thanks! :smile:

**Comment by Unknwon** [comment]
@mexthemax thanks your confirmation!
