### ISSUE TITLE
problem connect with ssh

### ISSUE THREAD

**Issue by Anyconcept** [gogits/gogs#1574]
Hi 

( first, sorry for my english :) )

I have a problem for using ssh connection...
When i want to push, I have that : 
gogs@mon-site.net's password:   (and,  don't have)

I test with gogs password but, no result..

and after..
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

On my server, user "gogs" has my key in "authorized_keys" 
And, i use the same key on github and, I don't have this problem...

I'have generate a new key for test but, not working..

And, for more info,
Air-de-Fabe:fabe-angular Fabe-Air$ git remote -v
origin	ssh://gogs@mon-site.net:222/fabrice/fabe-angular.git (fetch)
origin	ssh://gogs@mon-site.net:222/fabrice/fabe-angular.git (push)
(Yes, i changed my ssh port)
I have remove the remote and add again but, nothing..

---

my .git project on server
root@server:/home/fabe# ls /home/gogs/gogs-repositories/fabrice/
fabe-angular.git

Thanks for help :)

**Comment by Unknwon** [comment]
Thanks your feedback!

Make sure there is only one public key of yours and that one must be added by Gogs(any addition before Gogs can cause the issue you have).

**Comment by Anyconcept** [comment]
Hi,

My key is an id_rsa.pub., I suppose it's good..

I'm not sure what's you mean by : "and that one must be added by Gogs"
But, the key are added by Gogs webApp with "Add Key" in "SSH Keys" menu

And, for info, 
My key has not "paraphrase" (is it the same in english ? .. I mean, password when generated)

thanks for help ;)

**Comment by Unknwon** [comment]
> I'm not sure what's you mean by : "and that one must be added by Gogs"
But, the key are added by Gogs webApp with "Add Key" in "SSH Keys" menu

Sorry about confusion. I should have said that make sure you didn't add your same public key before to the `.ssh/authorize_keys` file.

**Comment by Unknwon** [comment]
If that's not the case, check the file permission, it has to be `600`.

**Comment by Anyconcept** [comment]
i think is good,

the permission for /home/gogs/.ssh/ 
-rw------- 1 gogs gogs 886 sept.  3 16:21 authorized_keys

No problem for chown ?

**Comment by Unknwon** [comment]
Please don't jump over my comments.... :flushed:

> make sure you didn't add your same public key before to the .ssh/authorize_keys file. Please open that file and check it.

Have you checked on this one?

**Comment by Anyconcept** [comment]
Oups, sorry :) 
yes, same keys

**Comment by Unknwon** [comment]
> same keys

hmm.. what do you mean by `same keys`?

**Comment by Anyconcept** [comment]
I del the key in .ssh/authorized_keys and add again for be sure..
same problem

**Comment by Unknwon** [comment]
OK... if SSH asks for password, that means the request does not even get to Gogs.

**Comment by Unknwon** [comment]
Remember check SSH server's auth.log see what is really going wrong.

**Comment by Anyconcept** [comment]
... I've not find logs for Auth.. 
gogs user  isn't  yet in "allowUsers" config for ssh connection !

goes user added and, it works :)

Tank you Unknwon :)

**Comment by Unknwon** [comment]
@Anyconcept No problem :wink:

**Comment by IJeffray** [comment]
Argh!  This has bugged me forever that I couldn't get GOGS ssh working... only now do I find the hidden limitation "Make sure there is only one public key of yours".  This is kind of disappointing... why is there this weird limitation for gogs?  [This basically means I still can't use ssh for gogs, but at least I know why now!]
