### ISSUE TITLE
Limit repo creation

### ISSUE THREAD

**Issue by jonathonf** [gogits/gogs#1575]
Possible enhancement.

I'd like to be able to limit repo creation. For example, limit unprivileged users to a certain number, and, if possible, limit the repos to a certain size.

Ideally there should be a global setting which an admin can override for individual users.

Limiting repo creation should prevent users maxing out disk resources.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
It's now possible on `develop` branch by https://github.com/gogits/gogs/blob/develop/conf/app.ini#L18-L19

**Comment by Unknwon** [comment]
Close as implemented.
