### ISSUE TITLE
Cannot clone repo

### ISSUE THREAD

**Issue by reisi007** [gogits/gogs#1576]
Hi,

I am trying to clone a freshly created repo (I tested it with a mirrored repo yesterday, which worked)
![cmdline](https://cloud.githubusercontent.com/assets/2719454/9678800/29ae15b8-52e9-11e5-8bc8-2da1bba90ff8.PNG)
[This can also be misconfiguration!]
As you can see I added an SSH key and I was surprised, that
![sshkey](https://cloud.githubusercontent.com/assets/2719454/9678842/7bbb0faa-52e9-11e5-9be9-5e93f573b93a.PNG)
As far as I can tell permissions look good 
![permissions](https://cloud.githubusercontent.com/assets/2719454/9678859/bf041270-52e9-11e5-99d8-1ddb583e826c.PNG)

Version: As I had to compile via commandline I first tried a 1.4 version and now I am on master (I guess you call it develop)
My config 
![unbenannt](https://cloud.githubusercontent.com/assets/2719454/9678944/64e008fc-52ea-11e5-8261-b44f145f27a5.PNG)

I hope you are able to understand the problem. I reinstalled the master version of gogs on the same database as the old .4.* version

This might the reason, why I get "Invalid csrf token." when try to delete the repo... But that's another bug and I try to delete the database and reinstall gogs now.

System raspian, gogs 0.6.9.0903 Beta, git version 1.7.10.4

**Comment by reisi007** [comment]
I did more review with a cleaner installation: SSH does not work. Host is reisi007.ddns.net Port is 2222
Works over http
![unbenannt](https://cloud.githubusercontent.com/assets/2719454/9679215/f04a61ba-52ec-11e5-89e7-d4a5e0dae4b1.PNG)

**Comment by Unknwon** [comment]
Hi @reisi007 , thanks your feedback!

1. Check there is only one public key of yours is in `.ssh/authorize_keys` file
2. ... and that key is added by Gogs
3. Check `.ssh/authorize_keys` file permission is 600
4. Check your SSH auth.log

**Comment by TheOneValen** [comment]
Hat the same problem, fetching an already working (before) repo. Cloning it again solved the problem for me. Since then no other occurence.

**Comment by reisi007** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/2719454/9683252/b1051abe-530e-11e5-98b7-ea3b6947333b.PNG)
For me it seems it has been added by gogs and the key is ok.

![unbenannt](https://cloud.githubusercontent.com/assets/2719454/9683276/e22846f2-530e-11e5-9846-be57932a0dc1.PNG)
For me it seems like 590
![unbenannt](https://cloud.githubusercontent.com/assets/2719454/9683301/10b8c5d2-530f-11e5-8b62-f92b56fe3312.PNG)
Running chmod did not help

I do not know where the ssh log is...

Anyway I think I know the problem....

I did not initialize the repo and thus the repo did not exist :/
Closing this issue... Sorry...

**Comment by Unknwon** [comment]
@reisi007 just want to point out that `590` is the file size in `byte`.... not permission. `--rw-------` is the permission which is `600` right now..

**Comment by reisi007** [comment]
@Unknwon : Thanks! Started to get in touch with Linux a few days ago. Did know some things before, but not this ^^

**Comment by Unknwon** [comment]
No problem :beers:

**Comment by evrial** [comment]
So that means I can't use the same SSH key or duplicate key for Git connecting the server *and* access trivial SSH.
The solution is to create system user for Gogs, but that's clumsy.
```$ ssh myhost
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
Connection to *** closed.```
How can we adress it for one user?

**Comment by tboerger** [comment]
@evrial it's simply not possible with a single user.
