### ISSUE TITLE
Paginator problem

### ISSUE THREAD

**Issue by manfer** [gogits/gogs#1577]
I have seen that the paginator in Explore is shown even when there is only one page. I have reviewed the template and it includes the `gt TotalPages 1` test so the only explanation is that TotalPages is not set.

In issues list it is working fine. I have not tested if the problem is happening in other places.

**Comment by Unknwon** [comment]
OK, so ... I guess forgot to filter private repositories...

**Comment by manfer** [comment]
That could be possible too. The TotalPages value being larger than it should.

**Comment by Unknwon** [comment]
Just pushed fixes to `master` branch!

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/commit/d023e81a8f6016db0bdaf8a935f273cc6e0d9a49#diff-d4e2553a87eb8b329efd7335f028903c

**Comment by manfer** [comment]
solved

**Comment by Unknwon** [comment]
Thanks your confirmation!

**Comment by richmahn** [comment]
I am wondering if when this change was made, that now no pager is shown. I have over 500 repos, but no pager on the Explore page. I noticed try.gogs.io/explore also has no pager. I'm sure there are many more repos than displayed.

**Comment by Unknwon** [comment]
Ah... @richmahn I think you're right... the code is done, but templates didn't update.

**Comment by Unknwon** [comment]
@richmahn Pushed fixed to `develop`, test on https://try.gogs.io/explore
