### ISSUE TITLE
error 500 after creating a repo in a team/organization which has "_" or Upper characters

### ISSUE THREAD

**Issue by delanoe** [gogits/gogs#1578]
I can push, pull but I cannot click on it
So if I share it, others members cannot push/pull/fetch (wrong url, maybe related with upper characters)
Gogs Application Version: 0.6.7.0901 Beta

**Comment by delanoe** [comment]
suppose you create a team with only lower case char and without "_"
when you invite some members, they receive an email with wrong url: gogs@www.blabla.org:user/repo.git
whereas it should be : gogs@www.blabal.org:team/repo.git

**Comment by Unknwon** [comment]
Thanks your feedback!

What is the exact error for `500`?

**Comment by delanoe** [comment]
NetworkError: 500 Internal Server Error
nothing more

**Comment by Unknwon** [comment]
Please check on your log file, normally in `path/to/gogs/log/gogs.log`.

**Comment by delanoe** [comment]
2015/09/04 07:16, 无闻:
> Please check on your log file, normally in path/to/gogs/log/gogs.log.

> 2015/09/04 07:19:22 [...s/middleware/repo.go:256 func·009()] [E]
> GetUserByName: user does not exist: [uid: 0, name: admin]
> 2015/09/04 10:48:02 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 10:48:16 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 10:50:50 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 10:50:57 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 10:52:51 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 15:30:47 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 15:37:10 [...ters/repo/setting.go:162 SettingsPost()] [E]
> DeleteRepository: RepoPath: user does not exist: [uid: 12, name: ]
> 2015/09/04 15:40:00 [...ters/repo/setting.go:162 SettingsPost()] [E]
> DeleteRepository: RepoPath: user does not exist: [uid: 12, name: ]
> 2015/09/04 15:51:47 [...s/middleware/repo.go:269 func·009()] [E]
> GetRepositoryByName: repository does not exist [id: 0, uid: 12, name:
> gargantext]
> 2015/09/04 16:11:40 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 16:11:56 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1
> 2015/09/04 16:13:15 [...s/middleware/repo.go:373 func·009()] [E]
> GetBranches: exit status 1

Cheers,
Alexandre

**Comment by Unknwon** [comment]
Thanks, can you post what exact steps you do to reproduce this problem?

Because it is not possible to create a user with name `admin`.

**Comment by delanoe** [comment]
2015/09/04 07:45, 无闻:
> Thanks, can you post what exact steps you do to reproduce this problem?

Sure.

> Because it is not possible to create a user with name admin.

Let me some time to be make a good report (I have to reproduce it).

-- 
Alexandre Delanoë

**Comment by Unknwon** [comment]
:wink: no problem

**Comment by delanoe** [comment]
I cannot reproduce the previous error... :)

So Everything is fine, I keep an eye on it.

**Comment by Unknwon** [comment]
Thanks your confirmation!
