### ISSUE TITLE
Unable to login using email address longer than 35 chars

### ISSUE THREAD

**Issue by vijairaj** [gogits/gogs#1579]
eg: `123456789@123456789.123456789.123456` would give the error:
```Username must contain at most 35 characters.```

Version: 0.6.7.0829 Beta.
Also reproducible at https://try.gogs.io

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
OK, so.... how long should be an e-mail address allowed in Gogs? Currently is 50.

**Comment by vijairaj** [comment]
This issue is now __resolved__, but I am not able to register with email id longer than 50.

**Comment by Unknwon** [comment]
>  but I am not able to register with email id longer than 50.

Why not?

**Comment by vijairaj** [comment]
I am trying to sign up on https://try.google.com using email: `123456789012345678901234567890123456@mailinator.com` but it says `E-mail address must contain at most 50 characters.`

**Comment by Unknwon** [comment]
OK...haven't update that yet...

**Comment by Unknwon** [comment]
Updated.

**Comment by vijairaj** [comment]
Tested up to 254 chars and works great now. thanks!

**Comment by Unknwon** [comment]
No problem.

Thanks your confirmation!
