### ISSUE TITLE
order owners list by last changed time

### ISSUE THREAD

**Issue by de-live-gdev** [gogits/gogs#1585]
See gitter between
https://gitter.im/gogits/gogs?at=55eb493d24228c321f1ae160
and
https://gitter.im/gogits/gogs?at=55eb55842e48d88a543da38b

**Comment by Unknwon** [comment]
Hi @de-live-gdev , I've pushed changes to `develop` and you can also test on https://try.gogs.io/repo/create

**Comment by de-live-gdev** [comment]
@Unknwon Thanks for your attention, I much appreciate your work!
Tried it on develop server, and can confirm it works

**Comment by Unknwon** [comment]
@de-live-gdev thanks your confirmation!

**Comment by de-live-gdev** [comment]
Could also be used in any other Context-Selector  (  /issues,  /pulls, /) on top
