### ISSUE TITLE
"Binary and template file version does not match, did you forget to recompile?"

### ISSUE THREAD

**Issue by harmw** [gogits/gogs#1587]
Just upgraded (pulled) my container to the latest gogs/gogs, now it fails to start with my existing datadir:

2015/09/06 15:25:47 [...gits/gogs/cmd/web.go:78 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?

**Comment by Unknwon** [comment]
Hi, please try https://github.com/gogits/gogs/tree/master/docker#troubleshooting

**Comment by harmw** [comment]
Didn't help. The templates dir is recreated after I deleted it at the dockerhost and it still fails to start:

2015/09/06 17:47:12 [T] Doing: CheckRepoStats
2015/09/06 17:47:12 [...gits/gogs/cmd/web.go:78 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?

**Comment by Unknwon** [comment]
What is full log output from Gogs before it prints an error?

**Comment by harmw** [comment]
Could not load host key: /data/ssh/ssh_host_ed25519_key
Starting OpenBSD Secure Shell server: sshd.
sending incremental file list

sent 3113 bytes  received 40 bytes  6306.00 bytes/sec
total size is 379222  speedup is 120.27
2015/09/06 17:59:44 [T] Custom path: /data/gogs
2015/09/06 17:59:44 [T] Log path: /app/gogs/log
2015/09/06 17:59:44 [I] harmw dev 0.6.9.0903 Beta
2015/09/06 17:59:44 [I] Log Mode: File(Info)
2015/09/06 17:59:44 [I] Redis Supported
2015/09/06 17:59:44 [I] Memcache Supported
2015/09/06 17:59:44 [I] Cache Service Enabled
2015/09/06 17:59:44 [I] Session Service Enabled
2015/09/06 17:59:44 [I] Mail Service Enabled
2015/09/06 17:59:44 [I] Notify Mail Service Enabled
2015/09/06 17:59:44 [I] SQLite3 Supported
2015/09/06 17:59:44 [I] Run Mode: Production
2015/09/06 17:59:44 [T] Doing: CheckRepoStats
2015/09/06 17:59:44 [...gits/gogs/cmd/web.go:78 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?

**Comment by Unknwon** [comment]
Thanks!

Just to confirm that you did use `-v /var/gogs:/data` to do volume?

**Comment by harmw** [comment]
I ran it like this:
`docker run -d --name=gogs -p 55522:22 -p 3000:3000 -v /data/docker/storage/gogs/:/data/ gogs/gogs`

So yes, the mounting is just fine :)

**Comment by Unknwon** [comment]
OK, so did you execute `rm -rf /data/docker/storage/gogs/templates`?

**Comment by harmw** [comment]
yes I did, but without the intended result :(

**Comment by Unknwon** [comment]
OK... let me see if I can do something with Dockerfile.

**Comment by Unknwon** [comment]
Hi @harmw  I've pushed new Dockerfile to tag `latest`, please help test again!

**Comment by harmw** [comment]
it works now, great! (without looking at the Dockerfile, what did you change?)

Also, could you tag the images according to the Gogs version inside?

**Comment by Unknwon** [comment]
@harmw the Dockerfile was using rsync to sync the template files from your local directories(can be a problem like your case), but right it only uses templates from GitHub, and deleted rsync.

**Comment by Unknwon** [comment]
Also, I've added `0.6.5` and `0.6.9`, they are building in progess.

**Comment by harmw** [comment]
great!

**Comment by Unknwon** [comment]
:beers:

**Comment by harmw** [comment]
Reopening here, forgot to check actual Git-part...
```
bash: /gopath/src/github.com/gogits/gogs/gogs: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Whenever I docker exec into the gogs container, I get a pwd of /app/gogs. This is obviously wrong, and changed since the other container. Could you revert *something* and make it behave like it used to, or instruct me on how to get my setup aligned again :)

**Comment by Unknwon** [comment]
@harmw it's easy... run following two things in `/admin` page:

- Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)	 
- Rewrite all update hook of repositories (needed when custom config path is changed)

**Comment by harmw** [comment]
excellent! is this something that is documented somewhere, or perhaps something that can be automatically done when Gogs detects it has been updated?

**Comment by Unknwon** [comment]
@harmw there are just quick fix through UI... not needed every time but sometime, that's why put them in `/admin` as admin operations.

**Comment by harmw** [comment]
ok, fair enough :)

**Comment by Unknwon** [comment]
:wink:

**Comment by unclegaara** [comment]
Hello!
I'm tried to update container from 0.6.5 to latest (0.8.33) and got the following error:
```
bash: /gopath/src/github.com/gogits/gogs/gogs: No such file or directory
fatal: Could not read from remote repository.
```
I'm ran commands at /admin page:
> Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)
> Rewrite all update hook of repositories (needed when custom config path is changed
but without result.

Can you help me with that?

**Comment by Unknwon** [comment]
@unclegaara looks like the rewrite `.ssh/authorized_keys` isn't successful, can you check the content of that file?

**Comment by unclegaara** [comment]
I think problem with app path. Old is /gopath/src/github.com/gogits/gogs/gogs new is /app/gogs

**Comment by Unknwon** [comment]
@unclegaara yes, but the rewrite should correct them all, unless the file path of ` .ssh/authorized_keys` that Gogs thinks is not right. Or Gogs does not have permissions to rewrite.
