### ISSUE TITLE
500 after migrating repo from local bare repo

### ISSUE THREAD

**Issue by siadat** [gogits/gogs#1588]
I migrated a repo using its local file path successfully, but when I go to the page I get a 500 error:

    [Macaron] Started GET /org/repo for 127.0.0.1
    2015/09/06 11:43:46 [...s/middleware/repo.go:361 func·009()] [E] GetBranches:
    [Macaron] Completed /org/repo 500 Internal Server Error in 16.84093ms

What could be the reason?

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version?

**Comment by siadat** [comment]
I am using v0.6.5. I realised that the repo I was migrating was empty. The error is happening here:

```go
stdout, stderr, err := com.ExecCmdDir(repo.Path, "git", "show-ref", "--heads")
```

The exit status for `git show-ref --heads` is 1 and nothing is printed in stderr. Instead of a 500 error page, I think it should show a page saying that the repo is empty or render the bare.tmpl file. I would be glad to work on a patch for this. Let me know your opinion.

**Comment by Unknwon** [comment]
@siadat thanks for following up!

OK, so if there is anyway(git command) can detect migrated repository is empty, you can set `Repository.IsBare` to true, then the web UI will be fixed.

And yes, it would great if you can make a patch for this.

Comment here if you have any questions! Or https://gitter.im/gogits/gogs

**Comment by siadat** [comment]
Thank you for your help! :smiley:

**Comment by Unknwon** [comment]
My pleasure!
