### ISSUE TITLE
增加指定通知邮件发送者的能力

### ISSUE THREAD

**Issue by denghongcai** [gogits/gogs#1591]
现在通知邮件的`From`字段被限定为了`issue`或者`comment`更新者的邮箱地址

有些邮件系统不能随意伪装为不属于自己的邮箱地址发送邮件，希望可以提供限定通知邮件发送者为硬编码值的能力

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Please follow on #1528 for updates.
