### ISSUE TITLE
404 when Repository name contains "git"

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#1593]
Reproduce:
 - Try to create a repository with white spaces in its name
 - Error occurs
 - remove the white space
 - try recreation of repository: "repository already exists"
 - try opening repository: error 404

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version?

**Comment by carli2** [comment]
0.6.9.0903 Beta

**Comment by Unknwon** [comment]
>  a repository with white spaces in its name

Can you post the exact name you used? Thanks.

**Comment by carli2** [comment]
"DigitaleInfoprodukte"

Other camel case names do work

**Comment by carli2** [comment]
It also works with "DigitaleInfotainment" or "DigitaleInfo"

**Comment by carli2** [comment]
After another test, it also fails at "dogit", so every project name containing "git" leads to this error.

**Comment by Unknwon** [comment]
Thanks, I'm working on it!

**Comment by Unknwon** [comment]
Hi there, I've pushed fix on `master` and you can test on https://try.gogs.io as well! https://try.gogs.io/unknwon/dogit

**Comment by Unknwon** [comment]
Closed as fixed.

**Comment by guotie** [comment]
现在的0.6.9二进制版本解决此问题了吗

**Comment by guotie** [comment]
看说明，似乎没有啊，那应该再发布一个版本啊

**Comment by Unknwon** [comment]
@guotie it's not necessary to make a new release after every bug fix.
