### ISSUE TITLE
Collaborative Repositories missing suburl on Dashboard

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#1594]
I am serving gogs from launix.de/gogs
In the dashboard view, there is "Collaborative Repositories" on the right side. Clicking on links there leads me to launix.de/path/to/repos which leads to 404. Correct would be launix.de/gogs/path/to/repos. ROOT_URL is correctly set.

**Comment by Unknwon** [comment]
Hi there, thanks your feedback!

I've pushed fix on `master` branch, please help test again!

**Comment by carli2** [comment]
thanks for fast reply. It works now.

**Comment by Unknwon** [comment]
No problem, thanks your confirmation!
