### ISSUE TITLE
pushing new branch will rereference issues in previous branch

### ISSUE THREAD

**Issue by mexthemax** [gogits/gogs#1595]
Pushing a new branch will re reference issues in the previous branch.  
Steps to reproduce:

- reference a issue in one branch (e.g. master) and push commits
- create a new branch
- commit to new branch
- push new branch (via git push origin --all)

Issues with references from commits in master branch will then have another reference from the same commit but at another time.

example: https://try.gogs.io/mexthemax/TestRepoForMe/issues/3

This was tested with gogs 0.6.9.0906 Beta on private instance and on try.gogs.io with same version.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Hi, I've pushed fixes to `develop` branch, you can also test on https://try.gogs.io/

**Comment by mexthemax** [comment]
I tested it on https://try.gogs.io/ with the same steps as before and the problem is solved.

**Comment by Unknwon** [comment]
@mexthemax thanks your confirmation!
