### ISSUE TITLE
Symbol for programming language

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#1598]
Hi,

I have different projects with different programming/scripting languages (java, c#, php, html). In the overview a can not see the language of each project. Perhaps the projects should be marked with a special symbol for the language that everyone can see which langugae is used for the projects. This can be made by symbol which is selectable in the corresponding project settings via a dropdown menu. At this time I can only choose the programming language (php is missing ;) ) but it is not shown anywhere.

**Comment by Unknwon** [comment]
Thanks your feedback!

The **Language** section at https://try.gogs.io/repo/create is a bit confusing which actually is choosing initial .gitignore files.

To your needs, Gogs can add section in repository settings, which allows you type in what language of this repository should be considered as.

How do you think?

**Comment by manfer** [comment]
Having another attribute for repositories makes no harm. Anyway many projects use mixed code languages so such an attribute will make no sense for a lot of projects unless the coder wants to tag the primary project language.

**Comment by Unknwon** [comment]
@manfer yes.

And consider the feature of labeling repository, this one may become redundant.

**Comment by focmb** [comment]
I know this feature from bitbucket where projects get a special symbol depending of the programming language. It is not an important feature but I like it to see which language is used for a project in the repo overview. instead of an language symbol I can choose my own icon for a project on bitbucket, for example the icon of my application (like a avatar for projects). This would be nice but I can live without that ;)

**Comment by 0xbaadf00d** [comment]
Maybe replacing "_Language_" with "_.gitignore template_" on repository creation could avoiding any kind of confusion.

**Comment by Unknwon** [comment]
@0xbaadf00d thanks, please create another issue.

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogits/gogs/issues/4154.
