### ISSUE TITLE
octicons on semantic templates issue

### ISSUE THREAD

**Issue by manfer** [gogits/gogs#1599]
On more than one template that has already been converted to semantic there is a problem with octicons. You must add the semantic class "icon". Otherwise the icon is just next to the text label without any space in between. Non breaking spaces (`&nbsp;`) are totally ignored and should be removed. The "icon" class is just enough and will add a right margin.

On adding the "icon" class take in mind that some icons can change size because they inherit the size of the container. If for some reason you prefer to preserve the octicon size then you would have to include "!important" on the octicon class font rule.

So, instead of:
```html
<i class="octicon octicon-whatever"></i>
```
you have to use:
```html
<i class="icon octicon octicon-whatever"></i>
```

**Comment by Unknwon** [comment]
Thanks!

**Comment by Unknwon** [comment]
I've checked most of places and sometimes you don't really need a `icon` class for that because that has too much `margin-right`.

If you have any specific places think that need to add `icon` class, please point them out! :smile:

**Comment by manfer** [comment]
On organizations issues you have a secondary menu which has nothing between the icon and the text label. All places where opened/close filter buttons appear there is nothing between the icon and the text label.

**Comment by Unknwon** [comment]
Pushed some fixes, please visit https://try.gogs.io/issues without cache.

**Comment by manfer** [comment]
That's fine for the Open/Closed filter.

Feeds / Issues / Pull Requests secondary menu in Organizations issues page needs "icon" class.

**Comment by Unknwon** [comment]
Pushed. :wink:

**Comment by manfer** [comment]
Adding the icon class but removing its margin almost voids its purpose. I know it is a matter of taste but just in case you want to do it that way at least don't remove the margin to the icon class but only on that very specific case.

```css
.ui.secondary.head.menu .icon { margin: 0; }
```

or even a more specific rule for that page.

Otherwise if you have to use semantic icon class in some other place you will have removed the margin. Actually it already breaks the look&feel of buttons watch/unwatch/star/unstar/fork in the pages that have been already converted to semantic and contain those buttons.

**Comment by Unknwon** [comment]
I've changed to just use margin-right:joy:

**Comment by manfer** [comment]
Ok now both has margin.

**Comment by Unknwon** [comment]
Any other places in mind?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
