### ISSUE TITLE
Accessing Private repo with admin account gives 404

### ISSUE THREAD

**Issue by jonathonf** [gogits/gogs#1600]
When logged in with an admin account, trying to browse to a Private repository leads only to a 404 error.

Steps to replicate:
* Create an private repository with any account
* Sign in with an admin account
* Visit %{URL}/admin/repos
* Click on the name of the Private repo
* Page loads as stripey 404.

Gogs version: 0.6.9.0907.
Package: 0.6.9-1441642153.5020576.trusty

**Comment by Unknwon** [comment]
Thanks your feedback!

But it's duplicated to https://github.com/gogits/gogs/issues/1401 .
