### ISSUE TITLE
Wrong commit order on issue page when pushing multiple commits

### ISSUE THREAD

**Issue by gwTumm** [gogits/gogs#1602]
When pushing multiple commits (in one go) that mention one issue, the commit messages get sorted upside down on the issues page (the last reference should be at the bottom).

![gogsissuepage](https://cloud.githubusercontent.com/assets/2026103/9732333/65476a9c-5623-11e5-8c35-48bdec2f459f.png)

Commit history page:

![gogscommitpage](https://cloud.githubusercontent.com/assets/2026103/9732334/6548009c-5623-11e5-90f4-278c90dce512.png)

I hope this wasn't reported before, I couldn't find a matching issue.

**Comment by Unknwon** [comment]
Hi thanks your feedback!

But I think what you're reporting is a expected behavior.

In the commits page, commits are sorted from latest to oldest.

But in issue reference page, it is ordered by the time it referenced issue, which is from oldest to latest.

**Comment by gwTumm** [comment]
Ah okay, it just kind of confused me because I thought the "close issue" message should be at the bottom since I closed it *after* doing the other commits. On the issues page, it appears above the other commits of that push which suggests the issue was closed before the commits were made.

**Comment by Unknwon** [comment]
@gwTumm yes, hmm... actually the current button says `close and comment`, so it's a bug or a feature either way.

Let me change it to `comment and close`.

**Comment by Unknwon** [comment]
Pushed fixes to `develop` branch, and you can test here: https://try.gogs.io/gogs/gogs/issues/21

**Comment by Unknwon** [comment]
Any updates on this?

**Comment by gwTumm** [comment]
Sorry, I didn't try this again until now. I think the issue still persists:

I opened a test repository on try.gogs.io: https://try.gogs.io/Tumm3/ordertest/issues/1 . I committed "1. Commit", "2. Commit" and "3. Commit" in this order and then pushed those commits together. On the issue page, the newest submission should be at the bottom, I think, so the commits should be sorted like I committed them. However, they're in the exact opposite order. (1. Commit is at the bottom, but 3. Commit and the "Close issue" message should be there instead)

**Comment by Unknwon** [comment]
@gwTumm thanks for following up!

I get your point now. Did you pushed 3 commits all at once or you pushed 3 times?

**Comment by gwTumm** [comment]
I pushed together in one go. I think if one pushes them seperately, they're properly sorted

**Comment by Unknwon** [comment]
Fixes has been pushed to `develop` branch and you can also test on https://try.gogs.io !

**Comment by Unknwon** [comment]
Closed as fixed.
