### ISSUE TITLE
Upload image does not handle suburl

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#1603]
It would be nice to have some log message like "please chmod 666 on folder xyz" or similar. Uploads don't work. I just see a broken image.

Uploading creates a database entry in table attachment. /home/gogs shows no additional files.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I'm not quite understood the problem you're describing:

> It would be nice to have some log message like "please chmod 666 on folder xyz" or similar.

How do you determine this is a chmod issue?

>  I just see a broken image.

What do you mean by `broken image`? 

>  /home/gogs shows no additional files.

Attachments are saved in `path/to/gogs/data/attchements`

**Comment by carli2** [comment]
The issue is that I don't know why it dosen't work and I don't get any clue why.

Do I have to create the folder data/attachments?

**Comment by Unknwon** [comment]
> The issue is that I don't know why it dosen't work and I don't get any clue why.

Can you take a screenshot for comment page after uploaded a image that is failed?

> Do I have to create the folder data/attachments?

No

**Comment by carli2** [comment]
![bildschirmfoto von 2015-09-08 12-43-55](https://cloud.githubusercontent.com/assets/852396/9733927/93c1ebe8-562f-11e5-9cb9-de511c323fb4.png)

**Comment by Unknwon** [comment]
Please take another screenshot for you uploaded image but not yet click on "comment" button.

**Comment by Unknwon** [comment]
And what does web console says about this image request? 

And log from Gogs?

**Comment by carli2** [comment]
![bildschirmfoto von 2015-09-08 14-05-36](https://cloud.githubusercontent.com/assets/852396/9734365/bb0096f2-5632-11e5-93c5-1a9318cbce82.png)

No log messages in gogs.log
web-1.log:
[Macaron] Started POST /issues/attachments for 188.101.157.237
2015/09/08 14:27:01 [T] New attachment uploaded: 93824b6b-0c72-436f-a3db-b06bc8af7382
[Macaron] Completed /issues/attachments 200 OK in 4.293742475s

**Comment by Unknwon** [comment]
Thanks!

Can you open the web console and see what is the response code for the `broken image`?

**Comment by carli2** [comment]
GET 
http://launix.de/attachments/0e8e0660-3edd-4505-b113-2182d7642b5e [HTTP/1.1 404 Not Found 57ms]
GET 
http://launix.de/attachments/93824b6b-0c72-436f-a3db-b06bc8af7382 [HTTP/1.1 404 Not Found 78ms]
GET 
http://launix.de/attachments/b924b7da-ebf3-4bca-b45b-d61c2b69b650 [HTTP/1.1 404 Not Found 77ms]

**Comment by carli2** [comment]
Oh, seems I found the reason: our gogs installation is reachable under http://launix.de/gogs
You forgot to add the sub-path to the download url.

**Comment by Unknwon** [comment]
> Oh, seems I found the reason: our gogs installation is reachable under http://launix.de/gogs
You forgot to add the sub-path to the download url.

Right!

**Comment by Unknwon** [comment]
I've pushed fix to `master`, please help test again!

**Comment by carli2** [comment]
Maybe it makes sense for you to test from an installation with a non-empty suburl to prevent any of these flaws.

**Comment by Unknwon** [comment]
@carli2 yeah, I'll try to setup a local installation with suburl while developing.

**Comment by Unknwon** [comment]
Closed as fixed.
