### ISSUE TITLE
Markdown preview for release description shows "no content"

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#1604]
When I write a description for a release and click on "preview", the preview shows always "no content"
![1](https://cloud.githubusercontent.com/assets/261217/9735009/e29bf4c2-5637-11e5-99c0-974759585796.png)
![2](https://cloud.githubusercontent.com/assets/261217/9735010/e43bf71e-5637-11e5-8dd0-c55f14932337.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Can you open web console see what is the response from server?

**Comment by focmb** [comment]
No Response from the web server. Here the last 2 lines of log output:

    [Macaron] Started GET /pi/getOUItxt/releases/edit/getOUI_cli for 2a00:0:ed0c:1::34
    [Macaron] Completed /pi/getOUItxt/releases/edit/getOUI_cli 200 OK in 148.093502ms

When I click on preview there are no new lines of output

**Comment by Unknwon** [comment]
You need to open web console and refresh the page to be able to see the log... if there is a Gogs log output, there is web console request/response log.

**Comment by Unknwon** [comment]
Please notice if there is any JS error...

**Comment by focmb** [comment]
my ssl log:
    "POST /api/v1/markdown HTTP/1.1" 404 694 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0"

the web console in firefox told me only: 
    
    toggleAjax: post /api/v1/markdown Object { mode: "gfm", context: "/gogs/pi/getOUItxt", text: "Das ist die erste Version des klein…" } gogs.js:97:13
    POST XHR https://DOMAIN/api/v1/markdown

Should this contains the suburl? Then it should be:
     POST XHR https://DOMAIN/gogs/api/v1/markdown

**Comment by Unknwon** [comment]
> Should this contains the suburl? 

Yes, it should.

Then this is the problem, thanks!

**Comment by Unknwon** [comment]
OK, I've pushed fix to `master`, please help test again!

**Comment by focmb** [comment]
Thanks. Now it works.

**Comment by Unknwon** [comment]
Thanks your confirmation!
