### ISSUE TITLE
user.CurrentUsername() is empty

### ISSUE THREAD

**Issue by tkisme** [gogits/gogs#1605]
I use `Do-It-Yourself 0.1` in openshift
here is how to deploy
now and error occur
```
2015/09/09 02:58:34 [...s/setting/setting.go:339 NewConfigContext()] [E] Expect user(55efb6e42d5271989200019e) but current user is: 
```
the only way to work out is run it via ssh
```
export HOME=$OPENSHIFT_DATA_DIR
cd $HOME/gogs
HOME=$OPENSHIFT_DATA_DIR nohup $OPENSHIFT_DATA_DIR/gogs/gogs web -c $OPENSHIFT_DATA_DIR/gogs/conf/app.ini>>$OPENSHIFT_DATA_DIR/gogs/err.log 2>&1 & echo $! > $OPENSHIFT_DATA_DIR/gogs/run.pid
```

**Comment by tkisme** [comment]
sorry, I try it with go1.5.1 and it works!

**Comment by tkisme** [comment]
now I try build form source

**Comment by tkisme** [comment]
find the bug in 
modules/setting/setting.go
Line 344,get empty
I try this code
```
log.Fatal(4, curUser)
```
and get output
```
[...s/setting/setting.go:344 NewConfigContext()] [E] 
```

**Comment by tkisme** [comment]
建议能在配置文件中设置运行用户

**Comment by Unknwon** [comment]
Thanks your feedback!

But based on the code: https://github.com/gogits/gogs/blob/master/modules/user/user.go#L11

I think all you need to do it set a env var.

> 建议能在配置文件中设置取得为空的时候默认是RunUser

Hmm... sorry I think there are too much grammar error for preventing me to understand the meaning of your sentence. :dizzy_face:

**Comment by tkisme** [comment]
```
export USERNAME=$OPENSHIFT_APP_UUID
```
It works,thanks
