### ISSUE TITLE
GUI bug while adding ldap user

### ISSUE THREAD

**Issue by renebigot** [gogits/gogs#1606]
Hello,
I'm trying to add an ldap user from gogs v0.6.1 web gui (binary for windows version). It's asking me to type a password retry but not a password.
If I leave the password retry field empty, a popup tells me to fill the field. If I fill it, its asking me to type the password too. So, I need to delete the 'hidden' class attribute on the password field from firefox / chrome inspector to create a user. As the auth is done by ldap, I think gogs should not ask for a password for this kind of users.

Regards,

René

**Comment by Unknwon** [comment]
Thanks your feedback!

But currently version of Gogs release is v0.6.9 ....

I certainly want to help you but can not continue without having same version of Gogs. :mask:

**Comment by renebigot** [comment]
My bad... I'm running 0.6.9 with the new ldap auth module.

I don't know why I've typed  0.6.1. Sorry.

**Comment by mexthemax** [comment]
I have the same problem on version 0.6.9.0907 Beta (pulled from develop branch an hour ago) with smtp authenticated users. see picture below 
![smtp_auth](https://cloud.githubusercontent.com/assets/13781012/9768820/822de9f2-5726-11e5-8e08-353682fa42ab.png)
authentication source google is a smtp authentication source with google smtp
When i fill out everything and press enter i get back to the same page with local authentication source selected and smtp source not available anymore. see picture below
![local_auth](https://cloud.githubusercontent.com/assets/13781012/9768932/338993e0-5727-11e5-9d30-03a0d21a1e4c.png)

**Comment by Unknwon** [comment]
@mexthemax thanks your info!

**Comment by renebigot** [comment]
Yes, same problem with ldap: when I hit enter, local is selected and ldap is not available.

**Comment by cnzzr** [comment]
这个问题在 0.6.5 版本就已经存在了

**Comment by Unknwon** [comment]
Hi! I've pushed fix on `develop` branch, please help test again!

**Comment by mexthemax** [comment]
Hey @Unknwon thanks for the fix, creating an smtp user now works.
However I mistyped the Authentication Login Name and when I try to update it, it doesn't get changed. So in order to make the account usable I have to recreate it with the correct Authentication Login Name. 
Updating other fields like Full Name etc.

**Comment by Unknwon** [comment]
@mexthemax yes! I'm working the edit page right now, will push an update soon.

**Comment by mexthemax** [comment]
ok thanks :smiley: 
While you work on that page, you might want to include some sort of "help" to indicate that the protocol for the website field has to be specified (e.g. http: or https:)

**Comment by Unknwon** [comment]
@mexthemax I'll add a placeholder like "e.g. http://mydomain.com"

**Comment by mexthemax** [comment]
@Unknwon yeah sounds good

**Comment by Unknwon** [comment]
@mexthemax pushed to `develop`!

**Comment by mexthemax** [comment]
@Unknwon the placeholder looks good
but I still can't change the Authentication Login Name.
Im in develop branch and the last commit (according to git log) was 98108e379d8931dc7eeafa25acf4e523039b6502 this includes the commit referenced here 83e747bfda43c2c8fa0aceb2c989d42fe5ca1582

**Comment by Unknwon** [comment]
@mexthemax oops! 

It was fixed and somehow I remade the bug... fixed again on `develop`.

Sorry about inconvenience!

**Comment by mexthemax** [comment]
@Unknwon no problem
It works now, thanks

**Comment by Unknwon** [comment]
@mexthemax thanks your confirmation!

**Comment by Unknwon** [comment]
Close as fixed.
