### ISSUE TITLE
Cannot delete repo when not initialised

### ISSUE THREAD

**Issue by romainreuillon** [gogits/gogs#1610]
When I create an empty repo and try to delete it, I obtain a 503 error. (I am using SQLite).

**Comment by romainreuillon** [comment]
I cannot reproduce that... ignore.

**Comment by Unknwon** [comment]
:joy:

**Comment by romainreuillon** [comment]
I think it was due to a bad config of the server regarding the authentication. We just configured pam on it.

**Comment by Unknwon** [comment]
@romainreuillon cool! Report if you meet any other issues!
