### ISSUE TITLE
SQL query,  xorm ?... bool not being translated to sqlite3. Passing literally 

### ISSUE THREAD

**Issue by techzilla** [gogits/gogs#1611]
[xorm] [info]  2015/09/09 17:26:00.239241 [sql] SELECT `id`, `owner_id`, `lower_name`, `name`,     `description`, `website`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_bare`, `is_mirror`, `is_fork`, `fork_id`, `created`, `updated` FROM `repository` WHERE (is_private=false) AND (lower_name like ?) LIMIT 10 [args] [%.%]

Specifically *is_private=false*,  SQlite lacks a native BOOL type, so it uses values 0 or 1.

 Thus all queries return, 
> {"data":[],"ok":true}

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by techzilla** [comment]
Version: 0.6.9.0903 Beta,

**Comment by Unknwon** [comment]
Thanks for following up!

Can you tell me what page exactly produces this SQL query? That would help me to justify or report an issue to XORM.

**Comment by techzilla** [comment]
It appears to be on any of the API searches, For example if i curl, /api/v1/repos/search

**Comment by Unknwon** [comment]
Hi @techzilla ! Thanks for pointing that out, I've found the bug and fixed it and pushed to `master` branch.

Please help test again!

**Comment by Unknwon** [comment]
Close as fixed.
