### ISSUE TITLE
Error 500 when trying to merge pull request between out of sync forked repo

### ISSUE THREAD

**Issue by bhchew** [gogits/gogs#1613]
Loving this already =)

Tried to submit a pull request for a outdated forked repo while simulating a conflict between a file.
While merging a pull request, page returns 500.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by qsodev** [comment]
i get Error 500 by trying to merge a pull request without any conflict. just added a new file to the fork and tried to merge the pull request...

**Comment by Unknwon** [comment]
@qsodev your error is due to permission issue, you should give write permission to Gogs.

**Comment by Unknwon** [comment]
**Important update** 

I've pushed code to `develop` branch and https://try.gogs.io that check if pull request has conflict with upstream every time fork repository or upstream repository is updated, so conflict will be detected correspondingly right now.

Leave feedback here so I can help with further problems you may encounter! :beers:

**Comment by Unknwon** [comment]
Close as fixed.
