### ISSUE TITLE
Add additional files to a release

### ISSUE THREAD

**Issue by Depado** [gogits/gogs#1614]
Hello there.

First of all, great work on the PR thing ! :smile: 

When I create a relase on Github for a Go program for example, I like to add the compiled binaries for the major platforms (Linux/Darwin/Windows). Although right now on Gogs there is no way to do such a thing. I couldn't find any feature request about that, so I create one. 

Is that planned ? Is it not ? Is there a simple way I could add those files without them being always in the repository ? 

Thanks a lot ! :+1:

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
This should be pretty much same as https://github.com/gogits/gogs/issues/698 , but I'm kind of confused what was the original purpose of that one, so I'll keep this open. :smile:

**Comment by Depado** [comment]
Pretty much, except it could be cool if you could add not only binaries but also any additionnal files. 
Thanks a lot you're really reactive ! :D

**Comment by Unknwon** [comment]
Yes, attachments is the thing I'm thinking about...

**Comment by ENDev15** [comment]
I would really appreciate seeing this too. Will be really happy to see this before 0.10 though. In fact, I would look into it my self but am not at all familiar with Go.

**Comment by jlprat** [comment]
I would also really appreciate this feature! It is extremely useful to be able to attach custom files to the release.

**Comment by jhit** [comment]
+1 from me to add this feature.
Wanted to add electron app release binaryies to one of our projects and did realise I can't do it :(

**Comment by MoeMorox** [comment]
+1

**Comment by octacian** [comment]
So... is there any chance of this actually happening, @Unknwon? There hasn't been a single commit to this repo for almost a month now.... I understand people get busy and have to do others things, but really.

**Comment by Depado** [comment]
@octacian There is now a milestone attributed for this, so I guess it's in the pipe. I'd be the first one to be happy with that feature, but I find it rather uncool to remind @Unknwon that there was no commit for a month on the Gogs repo :disappointed:

**Comment by octacian** [comment]
@Depado I guess that is true. I was just wondering if there was actually progress on this specifically. I understand you could see it as "uncool to remind" the developers of, I was just curious what was going on with Gogs in general. I understand that sometimes open source projects kinda "freeze" at times, people get busy and can't put in much time, or for other reasons. So, sorry if I annoyed anyone, as I said, I was just wondering what was happening with Gogs in general. Oh, and FYI, I wasn't really trying to specifically point out to Unknwon that there hadn't been a commit in a while, more so in general just asking what was going on.

Well, with all that said, I hope I haven't annoyed anyone :smiley:

I might actually learn Go sometime soon.. :thinking:

**Comment by saviourofdp** [comment]
A workaround could be to add your binary to the repo itself, then link to its raw view (making sure it's the correct commit url) via the content notes in the release. I realise that might not be appropriate for large binaries but it works for me for small stuff.
![capture](https://cloud.githubusercontent.com/assets/9444683/23543350/ab329b8c-ffe9-11e6-8ea6-bdeeeb14a71e.PNG)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/unknwon/hello/releases.

**Comment by jhit** [comment]
Looks great to me.

**Comment by Depado** [comment]
Amazing, thanks 👍 🎉

**Comment by octacian** [comment]
Thanks so much! I'll give this a try in a few days after i get home.

**Comment by melote** [comment]
Wow, this it most wonderful feature! I cannot wait any more!
