### ISSUE TITLE
Inconsistency between pages CSS

### ISSUE THREAD

**Issue by Depado** [gogits/gogs#1616]
Hi,
The theme used by Gogs is not always the same. For example, it won't be the same on the homepage of a repo and the page of a specific commit.

![capture d ecran de 2015-09-10 18-01-53](https://cloud.githubusercontent.com/assets/694365/9793515/1c5c43e2-57e6-11e5-875e-4296dbaed091.png)
![capture d ecran de 2015-09-10 18-02-04](https://cloud.githubusercontent.com/assets/694365/9793516/1c5ff24e-57e6-11e5-8f8d-ecfce4175e59.png)

This is a fresh install of the latest version of Gogs (0.6.9) on Debian 8. Installed from binary and using nginx as a reverse proxy (if that matters).

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is pretty much duplicated to #650

Quick answer is we are converting to new theme by page bases.
