### ISSUE TITLE
Error when upgrading to latest version

### ISSUE THREAD

**Issue by jenssegers** [gogits/gogs#1617]
I just upgraded my gogs installation to 0.6.9 from 0.6.3, and now I'm getting this error when starting gogs:

```
2015/09/10 20:21:03 [T] Custom path: /usr/share/gogs/custom
2015/09/10 20:21:03 [T] Log path: /usr/share/gogs/log
2015/09/10 20:21:03 [I] Gogs: Go Git Service 0.6.9.0903 Beta
2015/09/10 20:21:03 [I] Log Mode: File(Trace)
2015/09/10 20:21:03 [I] Redis Supported
2015/09/10 20:21:03 [I] Memcache Supported
2015/09/10 20:21:03 [I] Cache Service Enabled
2015/09/10 20:21:03 [I] Session Service Enabled
2015/09/10 20:21:03 [I] SQLite3 Supported
2015/09/10 20:21:03 [I] Run Mode: Production
2015/09/10 20:21:03 [T] Doing: CheckRepoStats
panic: template: base/head_old:16: function "CdnMode" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x7fafd0535028, 0xc820355ab0, 0x0)
	/usr/local/go/src/html/template/template.go:330 +0x4b
github.com/Unknwon/macaron.compile(0xc82000b5e0, 0x19, 0x0, 0x0, 0xc82000b600, 0x2, 0x2, 0xc82037e248, 0x1, 0x1, ...)
	/home/wuwen/go/src/github.com/Unknwon/macaron/render.go:276 +0x98e
github.com/Unknwon/macaron.(*templateSet).Set(0xc8204cb500, 0xf49708, 0x7, 0xc8201ca700, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/render.go:301 +0x4a
github.com/Unknwon/macaron.renderHandler(0xc82000b5e0, 0x19, 0x0, 0x0, 0xc82000b600, 0x2, 0x2, 0xc82037e248, 0x1, 0x1, ...)
	/home/wuwen/go/src/github.com/Unknwon/macaron/render.go:368 +0x211
github.com/Unknwon/macaron.Renderer(0xc8201bcec8, 0x1, 0x1, 0x0, 0x0)
	/home/wuwen/go/src/github.com/Unknwon/macaron/render.go:405 +0x1ee
github.com/gogits/gogs/cmd.newMacaron(0xc8201781e0)
	/home/wuwen/go/src/github.com/gogits/gogs/cmd/web.go:129 +0x768
github.com/gogits/gogs/cmd.runWeb(0xc8201781e0)
	/home/wuwen/go/src/github.com/gogits/gogs/cmd/web.go:188 +0xc2
github.com/codegangsta/cli.Command.Run(0xf55310, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfddf20, 0x15, 0x1096100, ...)
	/home/wuwen/go/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc8201fb700, 0xc82000a160, 0x2, 0x2, 0x0, 0x0)
	/home/wuwen/go/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
	/home/wuwen/go/src/github.com/gogits/gogs/gogs.go:40 +0x35c
```

**Comment by jenssegers** [comment]
Downgrading to 0.6.3 does not help...

**Comment by Unknwon** [comment]
Thanks your feedback!

Based on the documentation: http://gogs.io/docs/installation/install_from_binary.html#how-to-upgrade-from-binary%3F

You would have to remove old templates directory first before moving in new template files.

**Comment by jenssegers** [comment]
I got the issue fixed. But now the init.d script doesn't work anymore. When I launch `./gogs web` manually it does work. But `service gogs start` doesn't do anything.

**Comment by Unknwon** [comment]
> I got the issue fixed.

Great!

> But now the init.d script doesn't work anymore. When I launch ./gogs web manually it does work. But service gogs start doesn't do anything.

I can't help with this limited information, at least should have error info.

**Comment by jenssegers** [comment]
Thing is that I could not really see any errors. I changed my init.d file to the one on master and set /bin/bash as shell for the git user, and now it seems to work.

**Comment by Unknwon** [comment]
> Thing is that I could not really see any errors. I changed my init.d file to the one on master and set /bin/bash as shell for the git user, and now it seems to work.

Check `path/to/gogs binary/log/gogs.log` may find something helpful.

**Comment by jenssegers** [comment]
Thought I had it fixed but it isn't. Might need to switch to supervisord.

**Comment by Unknwon** [comment]
Sounds better to me. :mask:

**Comment by jenssegers** [comment]
Supervisord gave this error:

```
[.../models/publickey.go:60 homeDir()] [E] Fail to get home directory: Cannot specify home directory because it's empty
```

Was it not needed before?

**Comment by Unknwon** [comment]
> Was it not needed before?

It is required since v0.2 :joy:

**Comment by jenssegers** [comment]
Also, the style/theme seems to change for a couple of pages. Sometimes I get the one with the blue header, and other times I get a white version. Is this related to the upgrade, or is this a known issue?

**Comment by Unknwon** [comment]
Please see https://github.com/gogits/gogs/issues/650

**Comment by Unknwon** [comment]
Any updates on this?

**Comment by Unknwon** [comment]
Close for now but open continuing discussion.
