### ISSUE TITLE
Logic loophole leads to no admin

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1619]
If I choose to disable user registry and not to add admin account at the installation, then I would end up with a Gogs server with no admin. Yes, this happened right a few minutes ago. What am I supposed to do now?

**Comment by vijairaj** [comment]
A workaround right now would be to manually enable user registration and register one user who would automatically become the admin then you can revert to the old config.
[DISABLE_REGISTRATION = false](http://gogs.io/docs/advanced/configuration_cheat_sheet.html#service)

**Comment by JokerQyou** [comment]
Thanks, I'll take a look at the configuration file later. I think there should be a verification mechanism that prevent this from happening.

**Comment by Unknwon** [comment]
@JokerQyou thanks your feedback!

You're right, if you checked disable registration at install step, Gogs should force you create a admin account at the same time.

**Comment by Unknwon** [comment]
@JokerQyou Hi, just pushed code to `master` that checks violation of disable registration and no admin account.

**Comment by Unknwon** [comment]
Closed as fixed.

**Comment by JokerQyou** [comment]
Umm, sorry I have no time to test recently, my domain is during beian-ing, and my server is currently in migration. I'll have to wait until all these are done.

**Comment by Unknwon** [comment]
@JokerQyou no problem. You can update the result if the you get into same problem after update.
