### ISSUE TITLE
Restrict smtp auth to specific domains

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#1620]
Hi guys,

I'm testing Gogs here and it's amazing, I put the smtp authentication and works very fine, but I think I should have the option of restricting by domains optionally.

But, why?

If you have domain on Google Apps or Zoho Mail is necessary to restrict, else all users from this smtp can be login.

On my tests as example, I have 3 domains hosted on Zoho Mail and was possible to auth with all my domains, but I want to auth with only one domain.

Then I think that is good idea to restrict smtp auth with domains if is necessary.

I'm usgin Gogs v0.6.5.0815 Beta, SQLite3, Ubuntu 14.04.

Thanks

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

Just to confirm that set `Host` value to a domain other than a IP address couldn't help in your case?

**Comment by joubertredrat** [comment]
Hi @Unknwon ,

I think that doesn't help, because is necessary to restrict by domain.

One example:
smtp.gogs.io have domains binslashbash.net, bsb.org, bsb.com.br, bsbash.me and anothers.

On my Gogs I add smtp.gogs.io and allow only binslashbash.net and bsb.org domains to login, then If I login with me@bsb.org, will login with success, If I login with contact@binslashbash.net, will login with success.
But, If I login with me@bsb.com.br or eu@bsbash.me will not login, because although bsb.com.br and bsbash.me is on smtp.gogs.io, domain bsb.com.br isn't allowed to login, only binslashbash.net and bsb.org is allowed.

**Comment by Unknwon** [comment]
@joubertredrat thanks for following up!

Does the following thing is what you want?

- Add a field in SMTP form to specify a list allowed domains.
- First check if e-mail address matches one of allowed domain before sending auth request to real SMTP server.

For example:

Allowed domains: `binslashbash.net`, `gogs@binslashbash.net` will approve, but `gogs@bsbash.me` will not.

**Comment by joubertredrat** [comment]
Hi @Unknwon 

Exactly! You liked this? =)

**Comment by Unknwon** [comment]
Yes, I do, I'm working on it.

(PS: have to go to class right now)

**Comment by Unknwon** [comment]
OK! Just pushed a quick fix to `develop`, please help test!

**Comment by joubertredrat** [comment]
Hi @Unknwon ,

I can develop only in PHP, javascript or bash, but I can help with test and translate :)

I will test here and talk here.

Thanks again

**Comment by joubertredrat** [comment]
Hi @Unknwon,

I did the tests here, worked very fine, thanks. I will provide Brazilian Portuguese translation for milestone.

There was only one problem in the test, but it is not related to this issue.

On my example I have e-mail redrat@gogs.io, when I login, Gogs creates user redrat. If I try to login with e-mail redrat@gogs.org, will not possible to login because Gogs reports that already exists user redrat, as a log below:

```
[Macaron] Started POST /user/login for 201.17.202.104
[Macaron] Completed /user/login 200 OK in 2.003552214s
2015/09/11 21:50:51 [W] Failed to login 'bsb@mydomain.top' via 'yeah': user already exists: [name: bsb]
```
What do you think @Unknwon? I open new issue about this or you think that isn't necessary?

**Comment by Unknwon** [comment]
> On my example I have e-mail redrat@gogs.io, when I login, Gogs creates user redrat. If I try to login with e-mail redrat@gogs.org, will not possible to login because Gogs reports that already exists user redrat, as a log below:

It is unable to fix at current stage, because username is `unique` in database table.

**Comment by joubertredrat** [comment]
Hi @Unknwon,

No problem, this is very very small problem, just did it to see if I had need to inform you about this limitation.

@Unknwon thanks again :)

**Comment by Unknwon** [comment]
@joubertredrat no problem :smile:

**Comment by Unknwon** [comment]
Close as implemented.
