### ISSUE TITLE
Restrict the user login

### ISSUE THREAD

**Issue by ohko** [gogits/gogs#1621]
Some times, we need to disabled one user login system.
Whether or not add a new field restrict the user login.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by joubertredrat** [comment]
+1

**Comment by matrixise** [comment]
Add a field "active" on the user

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/2937 which has implemented this feature.
