### ISSUE TITLE
LDAP authentication not allowing users to login

### ISSUE THREAD

**Issue by variablenix** [gogits/gogs#1625]
Using => Gogs 0.6.9.0903 Beta 

I have entered the correct info to bind to my LDAP server using cn=Manager and specified a valid 'User Search Base' -- but when I try to login using my LDAP UID and password I get **Username or password is not correct** but they are correct. I have tried a few different 'User Filter' including (&(objectClass=posixAccount)(uid=%s)) to no avail. I know my credentials are correct because LDAP says they are.

$ ldapwhoami -vvv -h localhost -p 389 -D "uid=lee,ou=People,dc=domain,dc=net" -W
ldap_initialize( ldap://localhost:389 )
Enter LDAP Password:
dn:uid=lee,ou=People,dc=domain,dc=net
Result: Success (0)

![original](https://cloud.githubusercontent.com/assets/472631/9827259/4a68c418-5895-11e5-92de-9e9e26311704.jpg)

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you check on the console that what is outputting when you login with LDAP?

Also, can you make sure you enabled this auth?(activate)

**Comment by variablenix** [comment]
Hey -- thanks for your response!

I made sure "This authentication has activated" is enabled for LDAP. When I tail xorm.log and attempt to login via LDAP I see this entry.

[xorm] [info]  2015/09/11 23:20:32.621129 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `lower_name` = ? LIMIT 1 [args] [lee]

I did not find anything relevant to the login in gogs.log and http.log.

**Comment by Unknwon** [comment]
@variablenix thanks for following up!

Sorry I forgot to mention that change following value in your corresponding custom `app.ini`:

```ini
[log]
LEVEL = Trace
```

**Comment by variablenix** [comment]
Thanks @Unknwon! What I see is this with Trace logging. 

2015/09/12 14:30:59 [I] Log Mode: File(Trace)
2015/09/12 14:30:59 [I] Redis Supported
2015/09/12 14:30:59 [I] Memcache Supported
2015/09/12 14:30:59 [I] Cache Service Enabled
2015/09/12 14:30:59 [I] Session Service Enabled
2015/09/12 14:30:59 [I] Mail Service Enabled
2015/09/12 14:30:59 [I] Register Mail Service Enabled
2015/09/12 14:30:59 [I] Notify Mail Service Enabled
2015/09/12 14:30:59 [I] SQLite3 Supported
2015/09/12 14:30:59 [T] Doing: CheckRepoStats
2015/09/12 14:30:59 [I] Run Mode: Development
2015/09/12 14:30:59 [I] Listen: https://0.0.0.0:8000

The LDAP authorization settings seem to register, but nothing in console and logs related to LDAP authentication failure.

2015/09/12 15:06:25 [T] Authentication changed by admin(lee): LDAP
2015/09/12 15:07:31 [T] Authentication changed by admin(lee): LDAP

**Comment by Unknwon** [comment]
Hi @variablenix !

The log only shows that you changed your LDAP setting.

But have you tried login a user with LDAP? If the LDAP is sent, it must be logged according to https://github.com/gogits/gogs/blob/master/modules%2Fauth%2Fldap%2Fldap.go#L106

**Comment by Unknwon** [comment]
BTW, what LDAP server do you use? I think I should install one locally to help test.

**Comment by variablenix** [comment]
Thanks for the info @Unknwon !

Using OpenLDAP 2.4.4. I have tried different LDAP users part of *ou=People,dc=domain,dc=net*. It's strange that my Gog logs don't show anything about LDAP binding even with LDAP auth as one enabled source.

**Comment by Unknwon** [comment]
@variablenix I'm not sure if that matters, but in your screenshot, you have a typo:

cn=Manager,dc=domain.net ** = ** dc=com

Which should be 

cn=Manager,dc=domain.net**,**dc=com

I think.

**Comment by Unknwon** [comment]
I've pushed a fix on `master` may indicate this bug, please help test again! :stuck_out_tongue_closed_eyes:

**Comment by variablenix** [comment]
Thanks a lot @Unknwon!

I can now see LDAP bind log entries.

2015/09/12 17:30:31 [T] LDAP will use BindDN.
2015/09/12 17:30:31 [T] Search for LDAP user: tony
2015/09/12 17:30:31 [T] Bound as BindDN uid=tony,ou=People,dc=domain,dc=net
2015/09/12 17:30:31 [T] Searching using filter (&(objectClass=posixAccount)(uid=tony))
2015/09/12 17:30:31 [T] Binding with userDN: uid=tony,ou=People,dc=domain,dc=net
2015/09/12 17:30:31 [T] Bound successfully with userDN: uid=tony,ou=People,dc=domain,dc=net

It looked like it was going to login successfully, but ran into a PANIC with PANIC reference: http://ix.io/kMp

![panic](https://cloud.githubusercontent.com/assets/472631/9834585/cd45c418-5975-11e5-9456-fadd7f5b842c.png)

**Comment by Unknwon** [comment]
@variablenix Thanks!

Just to confirm what is your Gogs version? master branch?

**Comment by variablenix** [comment]
@Unknwon 

The former [1] Gogs was 1:0.6.9-1 and now [2] Gogs-Git 1:20150823-1. 

[1] https://aur.archlinux.org/packages/gogs/
[2] https://aur.archlinux.org/packages/gogs-git/

**Comment by SergioBenitez** [comment]
@Unknwon That push you just made makes signing in less efficient and will lead to a null pointer exception at some point, at least for LDAP. With your changes, when autoregister is turned off, Gogs will do everything including communicating with the LDAP server and authenticating against LDAP and then simply return (nil, nil). Thus, UserSignIn will return (nil, nil). I imagine the caller of UserSignIn expect that if the second return parameter is nil, then the first is not nil.

**Comment by Unknwon** [comment]
@SergioBenitez you made the point, and I just removed the `AutoRegister` field from database table.

**Comment by Unknwon** [comment]
@variablenix please update to `master` again, sorry about inconvenience!

**Comment by SergioBenitez** [comment]
@Unknwon Hmm, okay. But you've removed a degree of flexibility. Before, it was possible to allow existing users to sign in with LDAP but not new users. Now, that's not possible as account will always be created on-the-fly. Perhaps that's okay, but it is less flexible than before.

**Comment by Unknwon** [comment]
>  Hmm, okay. But you've removed a degree of flexibility. Before, it was possible to allow existing users to sign in with LDAP but not new users. Now, that's not possible as account will always be created on-the-fly. Perhaps that's okay, but it is less flexible than before.

@SergioBenitez I agree. But without auto-create, from my understanding of Gogs, every single page will make a auth request to backend auth, which is something.... I can't imagine :mask:

**Comment by SergioBenitez** [comment]
@Unknwon Well, the correct check, as the code is written now would be to add the following check as the first line of LDAP's login function (or maybe to ExternalLogin so that is happens for all functions):

```
if !(u != nil || autoRegister) {
    return nil, ErrUserNotExist{0, name}
}
```

This way, the auth request will not happen unless an existing user is trying to sign in (u != nil) or we can create new accounts on the fly (autoRegister).

**Comment by Unknwon** [comment]
@SergioBenitez my change does not make difference for LDAP because the previous one has force value `true` for LDAPSourceLogin.

**Comment by SergioBenitez** [comment]
@Unknwon In the previous version, "true" was forced because only sourced that had "AllowAutoRegister" set to true were retrieved from the database: See [this commit](https://github.com/gogits/gogs/blob/2d1db4bf055a425bf4529b2f9f0378d58e3ec648/models/login.go#L214).

**Comment by variablenix** [comment]
@Unknwon Thank you very much! I have verified LDAP users can now login with latest master.

**Comment by Unknwon** [comment]
> @Unknwon In the previous version, "true" was forced because only sources that had "AllowAutoRegister" set to true were retrieved from the database: See this commit. Now, of course, this isn't possible.

@SergioBenitez yes, it ignored all LDAP auth that are not auto register, what is the difference?

**Comment by Unknwon** [comment]
@variablenix thanks your confirmation!

You can consider close this issue when you think things are going well.

**Comment by SergioBenitez** [comment]
@Unknwon That now you call ExternalUserLogin with sources that are not auto register and say that they are.

**Comment by Unknwon** [comment]
@SergioBenitez feature removed :stuck_out_tongue_closed_eyes: and consider most of users just use LDAP as auth server, so it does not make difference to them.

**Comment by variablenix** [comment]
All good. Thanks! :+1:

**Comment by Priyanka201192** [comment]
I'm facing similar issue in authetictaing the user via LDAP. Provided below the link to the issue. Please help.
https://github.com/Priyanka201192/Springboot/issues/1
