### ISSUE TITLE
default db_type mismatch

### ISSUE THREAD

**Issue by manfer** [gogits/gogs#1626]
The default db_type in app.ini is mysql but when you first run the install script it shows SQLite3.

The DB_TYPE value in app.ini should be changed to sqlite3 if that is the database that is wanted to be configured as the default.

Then if a custom app.ini file is already available in `custom/conf/` folder the database values already configured on that file, database password included, should be prepopulated in install script fields as any other value already does. Only database values in `custom/conf/app.ini` are ignored, all the rest of configuration options get correct values.

**Comment by Unknwon** [comment]
> The default db_type in app.ini is mysql but when you first run the install script it shows SQLite3.

SQLite3 is shown because it is supported, if SQLite3 is not supported, then shows MySQL.

> Then if a custom app.ini file is already available in custom/conf/ folder the database values already configured on that file, database password included, should be prepopulated in install script fields as any other value already does. 

It is in purpose which discussed in an older that to prevent accidentally missing custom app.ini and result in install page which can leak the database password.

**Comment by manfer** [comment]
> SQLite3 is shown because it is supported, if SQLite3 is not supported, then shows MySQL.

I can't understand this logic. If the one you want to be the default, the preferred one, is SQLite3 then gogs `conf/app.ini` should read:

```
DB_TYPE = sqlite3
```

and in case sqlite3 is not supported on the system then because of that ineludible reason you choose other different database than the configured one.

What makes no sense in my opinion is to have an app.ini that reads:

```
DB_TYPE = mysql
```

but then, if sqlite3 is supported that one is used instead of the configured database. It is a quite strange logic.

The logic in my opinion should be:
- custom/conf/app.ini has priority over anything else. Don't use the password if you think that's the best idea but use anything else at least. If mysql is configured, use mysql. If someone has mysql configured in the file but wants to use other database he can change the form values. What makes no sense is that who has configured it on purpose on the file has to change the form.
- conf/app.ini should be the next in priority. So if mysql is configured in that file then it should be the one that install script shows. If you want SQLite3 as the default change that default value to sqlite3.
- In case the configuration on app.ini is not possible because the configured database is not supported show other one instead.

It is not a big deal to have to change the database type dropdown but looks quite strange. Those who should have to change the dropdown should be the ones that are not ok with configured values not the opposite.

**Comment by manfer** [comment]
I would change app.ini to:

```
[database]
; Either "mysql", "postgres" or "sqlite3", it's your choice
DB_TYPE = sqlite3

; For "sqlite3" only
PATH = data/gogs.db

; For "mysql" or "postgres"
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD =

; For "postgres" only, either "disable", "require" or "verify-full"
SSL_MODE = disable
```

**Comment by Unknwon** [comment]
> conf/app.ini should be the next in priority

Actually it has the lowest priority.

**Comment by Unknwon** [comment]
> and in case sqlite3 is not supported on the system then because of that ineludible reason you choose other different database than the configured one.

It can be type mismatch in another way.

**Comment by manfer** [comment]
> Actually it has the lowest priority.

No. Now it has same priority than custom/conf/app.ini. Which is none at all. Because the db_type configured in both files is ignored. It is always using SQLite3 as value ignoring what is configured.

I'm talking only about the install script prepopulated values.

Most probable the worst situation is if someone has configured Postgres in custom/conf/app.ini because his configuration will be totally ignored. If SQLite3 is supported that would be the one selected and if it is not supported I bet MySQL will be selected and maybe (I didn't looked into the code to know this) if MySQL is not supported too then Postgres will be selected.

**Comment by Unknwon** [comment]
> No. Now it has same priority than custom/conf/app.ini.

`conf/app.ini` loads first so whatever in it is overwrite by whatever loads next, and next, etc.

**Comment by Unknwon** [comment]
But I think not force choose SQLite3 when it is supported is acceptable, working on it.

**Comment by Unknwon** [comment]
Change has been pushed to `develop`.

**Comment by manfer** [comment]
Thanks @Unknwon. I can't test now but just inspecting the code that logic looks a lot better. Now it is not ignoring DB_TYPE configuration.

**Comment by Unknwon** [comment]
:smiley:

**Comment by Unknwon** [comment]
Close as fixed.
