### ISSUE TITLE
auto login after install if admin is configured

### ISSUE THREAD

**Issue by manfer** [gogits/gogs#1627]
This is not very important but would be an usability enhancement if after install script the app redirects to the login page if no admin has been configured but auto signs into gogs if an admin has been configured on install form.

**Comment by ChangePlaces** [comment]
don't like this idea! logging in isn't such a big problem and feels safer!

**Comment by tboerger** [comment]
What should be safer? You have defined admin username and password anyway within the install page.

**Comment by Unknwon** [comment]
It is now possible on `develop` branch.

**Comment by ChangePlaces** [comment]
what if you get up and walk away whilst it's installing? another person neaby has admin access whilst you're away.

**Comment by Unknwon** [comment]
@ChangePlaces Gogs does not take that long to install.

**Comment by Unknwon** [comment]
Close as implemented.
