### ISSUE TITLE
Mailer from does not match app configuration value

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1628]
Ive configured `FROM = xxx@mydomain.ext` in `custom/conf/app.ini`, but the notification email I received still shows the `from` section value is the issue owner's email address.

By the way, the page title for `应用配置管理` is misspelled as `用户管理`.

**Comment by tboerger** [comment]
Do you send and receive through gmail or google apps? Within google it seems to be always rewritten to the SMTP user email address, regardless what you have configured as a sender.

**Comment by JokerQyou** [comment]
No, I'm using QQ domain mail to send through SMTP. Since it cannot deliver emails to Gmail at the time, I'm sending emails to a `qq.com` mail address, but the `from` value of these mails are always my primary email address, which is a gmail address.

**Comment by JokerQyou** [comment]
I've turned to use Mailgun's SMTP server to send email notifications, but the `from` value is still the issue owner's email address.
Besides, the notification email lacks some basic information. Right now it's just come plain texts, I don't even know what email it is when I first look at it.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by Unknwon** [comment]
> By the way, the page title for 应用配置管理 is misspelled as 用户管理.

Good catch!

**Comment by JokerQyou** [comment]
I'm using latest gogs binary downloaded from official site

**Comment by Unknwon** [comment]
@JokerQyou OK, this is a issue claimed to be fixed in `master` branch: https://github.com/gogits/gogs/issues/1528
