### ISSUE TITLE
use docker volumes to separate data from application

### ISSUE THREAD

**Issue by andrewrothstein** [gogits/gogs#1631]
the sshd keys/certs and the ultimately the raw repos should be on docker volumes so they're not versioned with the union filesystem. happy to raise a pull request to create volumes for...

/data/gogs/data
/data/gogs/conf
/data/gogs/log
/data/git

any thoughts or concerns?

**Comment by Unknwon** [comment]
Thanks your feedback!

But not sure if you have read https://github.com/gogits/gogs/tree/master/docker ?

**Comment by andrewrothstein** [comment]
I read the docs. They describe how to mount the data directories outside the application container. And that's cool. I want to use a data volume container to hold the data. I'm excited by the prospects of https://clusterhq.com/flocker/introduction/. It's a one line change to the Dockerfile and probably five lines of text to the docker/README.md to document this option.

**Comment by Unknwon** [comment]
@andrewrothstein thanks your info!

But why it is necessary to use flocker which increase unnecessary image size....?

**Comment by andrewrothstein** [comment]
flocker is not the point. sorry I confused you by including that.
https://docs.docker.com/userguide/dockervolumes/
here's what I want to be able to do.
docker create --name gogs_data gogs/gogs
docker run -d --name gogs_app --volumes-from gogs_data

I can do it with a bunch -v s on the create command but I'd rather bake that into the Dockerfile

**Comment by Unknwon** [comment]
Hmm.... OK.

So the reason volume is not put into Dockerfile is because we want to keep it open as you have choice of how to volume and what to volume.

**Comment by andrewrothstein** [comment]
ok, thanks for the consideration
