### ISSUE TITLE
Can't close issues without comment

### ISSUE THREAD

**Issue by kasoki** [gogits/gogs#1632]
Clicking this Close button only reloads the page without closing the issue:

![close button](https://monosnap.com/file/Vt3kpD8U5xRNC9VHI7JaP66wPMqabM.png)

If I however add a comment I can close the issue as expected.

**Comment by Unknwon** [comment]
Hi! I've pushed fix to `develop` branch and you can also test on https://try.gogs.io

**Comment by hasufell** [comment]
had the same issue, works fine with latest master
