### ISSUE TITLE
Deleting User from Admin panel results in 500 and is not possible if user owns repository

### ISSUE THREAD

**Issue by mexthemax** [gogits/gogs#1633]
When deleting a user from admin panel gogs redirects to a Error 500 page. The user gets still deleted. From the logs I assume it tries to redirect to the settings for user with uid 0 (which at least in my case does not exist) instead of the users overview.
>  [Macaron] Started GET /admin/users/undefined for [insert ip here]
2015/09/13 18:45:54 [...uters/admin/users.go:128 prepareUserInfo()] [E] GetUserByID: user does not exist: [uid: 0, name: ]
[Macaron] Completed /admin/users/undefined 500 Internal Server Error in 94.552373ms

Also when trying to delete a user that still owns a repository nothing happens.
The logs indicate a 500 Internal Server Error
>2015/09/13 18:38:08 [...uters/admin/users.go:244 DeleteUser()] [E] DeleteUser: deleteUser: user still has ownership of repositories: [uid: 11]
>[Macaron] Completed /admin/users/11/delete 500 Internal Server Error in 174.132163ms

I would expect that deleting a user will delete all its repositories.
The confirmation dialog should in this case explicitly state that all repositories of this user will be deleted.

**Comment by Unknwon** [comment]
Thanks your feedback!

> When deleting a user from admin panel gogs redirects to a Error 500 page.

I've pushed fix to `master` branch.

> Also when trying to delete a user that still owns a repository nothing happens.

It is by design, you can't delete a user owns any repo or belongs to any org.

**Comment by mexthemax** [comment]
Deleting users without repository works for me now.

As for deleting users with repositories: I see there is now a notice when you try to delete such a user. So whats missing now is the ability to delete repositories from the admin panel but I think there already is a feature request about that.

thanks for the quick fix

**Comment by Unknwon** [comment]
@mexthemax thanks for your quick follow up! :smile:
