### ISSUE TITLE
Not able to view commits of pull request if it a private forked repo 

### ISSUE THREAD

**Issue by bhchew** [gogits/gogs#1634]
Not sure if this should be label under a workflow or a bug...

If it is a private repo and being forked, the owner of the parent repo is not able to review commits of pull requests from a forked repo, as it is also private

One approach is to add the owner of the parent repo to be the collaborator of the forked repo. But should this be the case?

**Comment by Unknwon** [comment]
Thanks your feedback! 

I think it is a bug!

**Comment by Unknwon** [comment]
Hi @bhchew , can you test again with latest `master` branch? Because I can't reproduce this problem...

My simulated case:

- A has private repo R, B is collaborator so it can fork R to R2
- B push something to R2, and make a PR.

Then, A and B can both view conversation, commits, files of PR.

**Comment by bhchew** [comment]
Hi Unknown,

I tested against latest docker develop tag, 2015 Gogs Version: 0.6.18.1025 Beta and view conversation, commits, files tabs of PR and it seems fine now. tks

**Comment by Unknwon** [comment]
Thanks your confirmation!
