### ISSUE TITLE
Gogs should allow usage of self signed certificates

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#1637]
When trying to connect via Port 636 to an active directory domain controller I see the following error:

```
2015/09/14 18:11:39 [T] LDAP will use BindDN.
2015/09/14 18:11:39 [D] Using TLS for LDAP
2015/09/14 18:11:39 [...es/auth/ldap/ldap.go:91 SearchEntry()] [E] LDAP Connect error, AD01.example.com:LDAP Result Code 200 "": x509: certificate signed by unknown authority
````

From my understanding there are two possible solutions - either don't enforce strict checking via a checkbox or make it possible to provide the necessary ca information to gogs.

**Comment by Unknwon** [comment]
Hi, I've pushed a fix to `develop` which now you can check `skip verify` on LDAP settings.

**Comment by hhenkel** [comment]
@Unknwon I can confirm that I'm able to open up a encrypted connection with ldap bind dn over port 636 against the "load-balanced" address example.com and no more errors show up.

**Comment by Unknwon** [comment]
@hhenkel thanks your confirmation!
