### ISSUE TITLE
Gogs should allow to disable strict hostname checking for tls/ssl

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#1638]
When using some kind of DNS round-robin with multiple active directory controller one might get the following error: 

```
2015/09/14 17:56:17 [T] LDAP will use BindDN.
2015/09/14 17:56:17 [D] Using TLS for LDAP
2015/09/14 17:56:17 [...es/auth/ldap/ldap.go:91 SearchEntry()] [E] LDAP Connect error, example.com:LDAP Result Code 200 "": x509: certificate is valid for AD01.example.com, not example.com
```

It would be nice to have a checkbox to disable that behavior.

**Comment by Unknwon** [comment]
Thanks your feedback!

I think it is the same as https://github.com/gogits/gogs/issues/1637 in Go's perspective.

**Comment by hhenkel** [comment]
@Unknwon you're right - from a go perspective it seems to be the same. I'm closing this as #1637 is resolved. Thanks again!
