### ISSUE TITLE
Create pull request tutorial

### ISSUE THREAD

**Issue by christophschlosser** [gogits/gogs#1639]
Could somebody create a tutorial on how to create pull requests with gogs?
Ideally with screenshots and a step-by-step guide, I seem to be unable to create new pull requests.

I seem to be missing something really obvious.

**Comment by Unknwon** [comment]
Hi! What is your version of Gogs?

**Comment by christophschlosser** [comment]
Hi,
I'm running "Version: 0.6.12.0914 Beta" with Go1.4.2!
Thank you in advance!

**Comment by Unknwon** [comment]
@christophschlosser OK.. so first you would have to fork a repository, and then there is a small green button on the forked repository home page.

But if you does not commit anything new, you would not be allowed to create a PR.

**Comment by hakur** [comment]
![qq 20150915110347](https://cloud.githubusercontent.com/assets/12321972/9866818/e9f49690-5b99-11e5-9ca5-dd09d3c2538e.png)

**Comment by christophschlosser** [comment]
@Unknown and hakur

Thank you! I totally missed that green button!

It's working now :)

**Comment by Unknwon** [comment]
Closing now :)

**Comment by beowulf13th** [comment]
Hi! What about pull request from branch to branch?

**Comment by Unknwon** [comment]
@beowulf13th please follow on https://github.com/gogits/gogs/issues/1597

**Comment by babkamen** [comment]
maybe it's better to add PR letters to button?
