### ISSUE TITLE
[Feature Request] Slack message on issue

### ISSUE THREAD

**Issue by bennygit** [gogits/gogs#1641]
Hello, 

it would be nice if on can add a web hook that is sending a message to slack if on is creating a issue in gogs.

Thanks for all your work!

**Comment by tboerger** [comment]
Some slack webhook is already integrated

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

As @tboerger mentioned that Slack has integrated but Gogs hasn't had issue hooks, so will be added as Gogs adds more hook types.

**Comment by bennygit** [comment]
Thank you very much Unknown! It would be great to see this in 0.7.0.

**Comment by quux** [comment]
+1

**Comment by supermomonga** [comment]
+1

**Comment by TheBlusky** [comment]
+1

**Comment by tex0l** [comment]
+1 :)

**Comment by arantes555** [comment]
+1 :)

**Comment by tex0l** [comment]
+1

**Comment by tboerger** [comment]
Please stop the +1 comments, you can simply use the new `Add your reaction` functionality of the issue/feature request.

**Comment by Unknwon** [comment]
I think this is already implemented.
