### ISSUE TITLE
Pull request diff not updated when master changes

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#1642]
How to replicate:

1. Create a "upstream" repository
2. Add initial file
3. Fork the repo
4. Alter the file to create a conflict and create a pull request against the upstream repo
5. Change the file in upstream to something different then the pr.
6. Look at the pr - you'll see two commits, one from the inital pr and the altered upstream one (which I guess is wrong)
7. Look at the pr - Files changed still shows the old diff.

Diff:
![2015-09-15 11_45_05-other header - gogs_ go git service](https://cloud.githubusercontent.com/assets/2813782/9873339/7d7fa832-5b9f-11e5-9de9-1977061bbf05.png)

Commits shown in pr:
![2015-09-15 11_45_54-other header - gogs_ go git service](https://cloud.githubusercontent.com/assets/2813782/9873349/8c0a17b6-5b9f-11e5-9241-a1d982397e33.png)

Commits shown in repo:
![2015-09-15 11_46_24-is-ito-as-linux_test - gogs_ go git service](https://cloud.githubusercontent.com/assets/2813782/9873351/8fa49fea-5b9f-11e5-9afd-5906e3416ac0.png)

Changed in upstream (5.):
![2015-09-15 11_48_49-changed in upstream daf608e80c - gogs_ go git service](https://cloud.githubusercontent.com/assets/2813782/9873406/d2304ce2-5b9f-11e5-9a51-0ce8ea33d954.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
**Important update** 

I've pushed code to `develop` branch and https://try.gogs.io that check if pull request has conflict with upstream every time fork repository or upstream repository is pushed, so conflict will be detected correspondingly right now.

Leave feedback here so I can help with further problems you may encounter! :beers:

**Comment by hhenkel** [comment]
This seems to be resolved now with your last commit b9f5def5dc177e683c6c2946498bd2eabb82d16a

**Comment by Unknwon** [comment]
:trollface:

**Comment by Unknwon** [comment]
Close as fixed.
