### ISSUE TITLE
Unable to delete a milestone

### ISSUE THREAD

**Issue by MathB** [gogits/gogs#1643]
First of all thanks for your great work on Gogs !

On Version: 0.6.9.0907, I tried to delete a milestone and i get the confirmation message but it's still there.

I've tried to execute manually the delete query from the log and it don't delete anything because the dates don't match ! I think it's a time zone handling bug.

Here is the content of 'milestone' table : 
 deadline  =  9999-12-31 02:00:00
 closed_date = 2015-09-15 11:32:28

The query parameters :
deadline  = 9999-12-31 03:00:00 
closed_date = 2015-09-15 13:32:28

I'm in Paris time zone...

**Comment by Unknwon** [comment]
Hi @MathB !

Thanks you feedback! I've pushed a fix to `master`, please help test again!

**Comment by MathB** [comment]
Fixed ! Thanks

**Comment by Unknwon** [comment]
@MathB thanks your confirmation!
