### ISSUE TITLE
Packager.io debian/ubuntu script has wrong port number

### ISSUE THREAD

**Issue by MathB** [gogits/gogs#1645]
On the [packager.io debian page](https://packager.io/gh/pkgr/gogs/install?bid=275#debian-8-gogs) the script configure nginx to serve as proxy for port 6000 but since #1277 debian gogs install listen on 3000.

A fix will save people (like me) some time to find out why nginx return a proxy error...

**Comment by Unknwon** [comment]
Thanks your feedback!

But I'm not sure what the is expectation from you? 

> A fix will save people 

What fix?

**Comment by MathB** [comment]
Sorry wrong formulation. Was just saying that solving this problem should save a bit of time to the next person who will do the installation via this script

**Comment by Unknwon** [comment]
> Was just saying that solving this problem should save a bit of time to the next person who will do the installation via this script

Which problem? ...

**Comment by YamashitaRen** [comment]
The problem is that the installation instructions on the packager.io page "say" that gogs port is 6000.
BUT packager.io packages install gogs with a default port of 3000.

**Comment by Unknwon** [comment]
@YamashitaRen thank you :sweat_smile:

cc @crohr

**Comment by Unknwon** [comment]
Ping @crohr

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.

**Comment by crohr** [comment]
Just fixed it.
