### ISSUE TITLE
Incorrect redirect for account activation

### ISSUE THREAD

**Issue by initbar** [gogits/gogs#1646]
>`Bug Description`

Using `try.gogs.io` (unsure if latest version of Gogs), creating a sample account and clicking `Sign in to your e-mail` button redirects to `mail.8282.8282/`. Used following values: username => `test8282` and email => `test8282@8282.8282`.

>`Gogs Version`

`© 2015 Gogs · Version: 0.6.12.0914 Beta`

>`Git Version`

N/a

>`System Type`

Linux

>`Error Log`

N/a

>`Other information`

![signup](https://cloud.githubusercontent.com/assets/12630151/9881946/4295e622-5ba0-11e5-9df4-970a739bf3dd.png)
![signin](https://cloud.githubusercontent.com/assets/12630151/9881945/428cf3fa-5ba0-11e5-80a7-6cf677a9fb55.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

Gogs does not know what the URL of mail service you're using, so `mail.*` is just a good guess.

Do you have any other good suggestion on how to precisely get the correct URL on the fly? Thanks.

**Comment by initbar** [comment]
Hello~

I could think of couple (following) possible solutions:

1) keeping large table of known domains (i.e. `gmail.com`) and redirect to matching key:value set. However, I think this is suboptimal and inefficient method as the maintainer is required to keep track of growing population of email services.

2) just redirecting to the domain provided (i.e. `outlook.com|yahoo.com`) after `@` (and without `mail.*`). If the email address was just a throwaway email and invalid (i.e. `@8282.8282`), then the expected result of "signing-in" would've been failed anyways. For example:

Test cases:

| User Input | Redirect To | Should be Redirected? | Success/Fail |
| :------------: | :----------: | :----------------------------: | :---------------: |
| `test@gmail.com` | `gmail.com` | :white_check_mark: | :white_check_mark: |
| `test@outlook.com` | `outlook.com` | :white_check_mark: | :white_check_mark: |
| `test@yahoo.com` | `yahoo.com` | :white_check_mark: | :white_check_mark: |
| `test@1238.234` | `1238.234` | :white_check_mark: | :x: | :x: |
| `test@1232.com` | `1232.com` | :white_check_mark: | :x: | :x: |
| `test@.com` | `(caught by initial regex filter)` | :x: | :x: |
| `test@.` | `(caught by initial regex filter)` | :x: | :x: |
| `test@!.!` | `(caught by initial regex filter)` | :x: | :x: |
| `test@@` | `(caught by initial regex filter)` | :x: | :x: |

As long as the email domain is alphanumeric, I think this could work.

**Comment by Unknwon** [comment]
@initbar thanks to your very nice table!

**Comment by Unknwon** [comment]
I've pushed some code to redirect to the domain without `mail.` prefix as you suggested to `develop` branch.

**Comment by initbar** [comment]
~(˘▾˘~)

**Comment by Unknwon** [comment]
Close as fixed :joy:
