### ISSUE TITLE
Faster webhooks?

### ISSUE THREAD

**Issue by brandonsturgeon** [gogits/gogs#1648]
The current config only allows for a minimum of 1 minute interval for webhooks. Github has very quick webhooks, and I'd like to be able to set the webhook interval to much lower than 1 minute.

**Comment by Unknwon** [comment]
Hi @brandonsturgeon , what is you version of Gogs? Seems pretty old version... Gogs has realtime webhook since 0.6.5.

**Comment by brandonsturgeon** [comment]
Errmm, yup that was it. Somehow I'm on 0.6.1 Beta. That's concerning.

Thanks for the lightning quick reply, much appreciated.

**Comment by Unknwon** [comment]
:beers:
