### ISSUE TITLE
Restrict Delete repo on Teams to only Admins

### ISSUE THREAD

**Issue by FyinInc** [gogits/gogs#1650]
It looks like any team member on a team can delete a repository.  Can this be just an admin privilege or am I configured wrong?

**Comment by Unknwon** [comment]
Thanks your feedback!

Anyone in Owners team can has `owner`(highest) access to all repositories in the organization, can you check if that's the case?

**Comment by FyinInc** [comment]
All Team members can see the repo and delete.  If they are not part of the team, they cannot see the repo.  I'd prefer allow delete to only Admin's of GoGS.

**Comment by Unknwon** [comment]
Thanks for following up!

But I'm not clear about your situation:

1. What is the team name you have?
2. What is the team access level of that team?
3. What do you exactly mean by `see` and `delete`?
4. What is the exactly meaning of ` Admin's of GoGS`, admin in the organization or the admin of Gogs instance?

**Comment by FyinInc** [comment]
I hope these screen shots help.  Scott is not an admin, he is just part of
the Fyin.com team.  Yet Scott has the power to delete any repo.  If I
remove Scott from the team then Scott can not access the project.

Fyin.com team settings - logged in as David:


Logged in as Scott:

Admin Settings for All Users - logged in as David:

​

**Comment by Fastidious** [comment]
@FyinInc I think @Unknwon wrote "Anyone in Owners team can has owner(highest) access to all repositories in the organization." It seems everyone (the three users) on that team is owner. To accomplish what you want, do not make everyone owner.

**Comment by Unknwon** [comment]
Hi @FyinInc , I think @Fastidious has made my point...

**Comment by FyinInc** [comment]
I got it - you have to create a new team.  Works like a charm.  Thank you.

**Comment by Unknwon** [comment]
@FyinInc awesome, so has the problem been solved?

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
