### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by ApfelUser** [gogits/gogs#1651]
The SSL certificate on

  * **[gogs.io](https://gogs.io/)** and
  * **[try.gogs.io](https://try.gogs.io/)**

expired 1 day ago.

**Comment by Unknwon** [comment]
Thanks!

But just to be clear that `gogs.io` does not use SSL :smile:

**Comment by Unknwon** [comment]
Fixed! Thanks again!

**Comment by ApfelUser** [comment]
@Unknwon Okay, didn't know that.

**Comment by Unknwon** [comment]
I should config Nginx to redirect...
