### ISSUE TITLE
Restart docker container stops the web interface

### ISSUE THREAD

**Issue by reinos** [gogits/gogs#1656]
Installing the Gogs docker container on my Synology 713+ whas a great thing. It works great and it is super fast.

But when i stop and then start my container, the web interface is gone. Via ssh it is working, but the whole web interface is gone... Any idea what that might be?

<img width="935" alt="screen shot 2015-09-18 at 00 17 57" src="https://cloud.githubusercontent.com/assets/633730/9947479/c0095098-5d9a-11e5-8c90-fb551ce9e910.png">

**Comment by Unknwon** [comment]
Hi @reinos , thanks your feedback!

Few questions:

1. Are you using official Docker image of gogs/gogs ?
2. What is the screenshot saying? The running process inside the container?
3. ... if yes, then check the port expose, make sure Gogs web server port has exposed.

**Comment by reinos** [comment]
Hi @Unknwon 

Thanks for your reply. 

1. Yes im using the official docker image
2. Yes, the screenshot shows the processes that are running
3. how do i check that?

**Comment by Unknwon** [comment]
Thanks for following up!

1. How did you start at first time?
2. How did you start at the second time?

**Comment by reinos** [comment]
Im using synology for this. It has a start and stop button...
<img width="1019" alt="screen shot 2015-09-18 at 00 34 24" src="https://cloud.githubusercontent.com/assets/633730/9947768/0fad3194-5d9d-11e5-924d-f26249e1c984.png">

**Comment by Unknwon** [comment]
I'm not which UI tool you're using, but in the case of Kitematic, there are settings for exposed ports:

![image](https://cloud.githubusercontent.com/assets/2946214/9947767/c18240d6-5d6a-11e5-8257-a21e900f92a2.png)

**Comment by reinos** [comment]
Well it should work fine if i see the ui...

<img width="948" alt="screen shot 2015-09-18 at 00 35 40" src="https://cloud.githubusercontent.com/assets/633730/9947790/418095c6-5d9d-11e5-88ba-5c8038c44eb0.png">

But is there a way to check it on the commandline?

**Comment by Unknwon** [comment]
Can post some logs you can get from container here?

**Comment by reinos** [comment]
Here you go;

<img width="849" alt="screen shot 2015-09-18 at 00 38 28" src="https://cloud.githubusercontent.com/assets/633730/9947826/9eef1dd6-5d9d-11e5-9a90-beac060e7f5a.png">

**Comment by Unknwon** [comment]
Thanks!

So since the process show Gogs web server is actually running, I think it should be some kind of port mapping problem.

You said the SSH push/pull are working, and what SSH URLs you are using?

And what URLs you're trying to access the web UI but failed?

**Comment by Unknwon** [comment]
I also see there is a `terminal` tab, what does it do? Maybe can get into container and check something.

**Comment by reinos** [comment]
the ssh url is ssh://git@<domain-name.com>:1022

yes the terminal can be used

**Comment by reinos** [comment]
ssh url is: ssh://git@fakedomain.com:1022/reinos/prins-hovenier.nl.git

**Comment by reinos** [comment]
the url that failed is http://fakedomain.com:1080/

**Comment by reinos** [comment]
fakedomain.com is not the real domain ;-)

**Comment by Unknwon** [comment]
OK... I think I know the problem.

Just in case you haven't read the README specifically for Docker: https://github.com/gogits/gogs/tree/master/docker

You given the `HTTP Port` value `1080` while the install page, so next time Gogs starts with 1080 port, but actually you only mapped 3000 from container's perspective.

**Comment by Unknwon** [comment]
The quick solution as follows:

1. get into container
2. edit `/data/gogs/conf/app.ini`
3. change `HTTP_PORT` to `3000`.
4. restart container

**Comment by reinos** [comment]
yeah! that works!

Thanks you and my fault not reading the readme totally...

And thanks again for your quick and solid support :+1:

**Comment by Unknwon** [comment]
No problem :beers:

**Comment by reinos** [comment]
just one question, what is the best way to update the container when there is a new release?

**Comment by Unknwon** [comment]
Can you take a screenshot on `volume` tab?

If you have did as README describes, just fetch the image again.

**Comment by reinos** [comment]
<img width="516" alt="screen shot 2015-09-18 at 00 55 10" src="https://cloud.githubusercontent.com/assets/633730/9948053/f36ef5f0-5d9f-11e5-9ac5-5166b175b371.png">

Ok thanks, again fail on my side for not reading the readme...

**Comment by Unknwon** [comment]
OK, so if you now go to `/docker/gogs` directory, you should see something as follows:

```
|-- git
|   |-- gogs-repositories
|-- ssh
|   |-- # ssh public/private keys for Gogs
|-- gogs
    |-- conf
    |-- data
    |-- log
    |-- templates
```

And just to make sure, please check all of these directories are not empty. Especially the `git/gogs-repositories` and `gogs/data`.

If you're using SQLite3, the `gogs/data/gogs.db` should exists(or other name as you specified while install)

**Comment by Unknwon** [comment]
More notes on upgrade container:

- docker pull gogs/gogs
- remove old container
- run image as a new container and do the same volume and port mapping

**Comment by Unknwon** [comment]
FYI, I've added a line in the install page that remind people like you doesn't aware of the README for using Docker image.

And I'm going to close this issue as problem solved.

If you have more questions you consider small/simple/quick, you can reach me on https://gitter.im/gogits/gogs

:tada:

**Comment by reinos** [comment]
Thanks for your help! :+1:

**Comment by Unknwon** [comment]
No problem!

**Comment by davideuler** [comment]
Also I met the problem. I search in the issues and finally solved it. Thanks, it worked after restart.

By the documentation, the name of SSH Port and HTTP Port is a little confused to understand:
SSH Port: Use the exposed port from Docker container...
HTTP Port: Use port you want Gogs to listen on inside Docker container...

Maybe it would be easier to understand if "HTTP Port" is changed to "HTTP Port to Listen".

**Comment by Unknwon** [comment]
@davideuler good to know you fixed it!

**Comment by Donny2333** [comment]
I solve the same problem by reading this: https://github.com/gogs/gogs/issues/3039
