### ISSUE TITLE
allow forcing all private repos

### ISSUE THREAD

**Issue by v01d** [gogits/gogs#1657]
It would be nice to have a config option forcing all repos to be created as private repos. This is to compartmentalize access to repos, which I would like to give on a per-team or per-user basis. Otherwise, no user without specific rights should be able to see repos.

**Comment by Unknwon** [comment]
Thanks your feedback!

If I'm understanding your situation correctly:

More than one teams are working together in one Gogs instance, and you don't want them to see each others repository?

**Comment by v01d** [comment]
Actually, I have a team where some users should not see these repositories,
so in principle I could have everything public except these. However, other
external users should be given access to only specific repos. This would
force me to make everything private and manage everything by giving users
permision. So this feature would help with this situation.

Otherwise, it would be better to have some form of "guest" user which does
not have access to anything except particular teams/repos.

**Comment by Unknwon** [comment]
Thanks for the details!

Just some thoughts as follows:

 Why can't create an organization help?

Having a config option to force all repos to be private is kind of overkill because check the private checkbox is all you have to do and Gogs now remembers it so you don't need to check it every time.

And then, you create a team called "guests" and only given them read access.

**Comment by v01d** [comment]
Well, another issue I have is that I'm used to gitolite where I had
"namespaces" for repos, to avoid having one big mess of repos for everyone.
So, it would not be just one team, but one for each organization (which is
the closest to a "namespace"). Also, this means that for each new user, I
have to manually add it to the relevant team of each organization.

By setting everything to private, I'm relying on every user not
accidentally forgetting of clicking "private". Thus, under this scheme, I
would need to force everything to be private.

In gitolite it is easier, since "teams" (or "groups") are independent of
"namespaces" or "organizations", so I just defined the access rules for
each group, and for new users I just add it to the corresponding group.
Also, I can make everything unreadable by-default, to have special users
not part of any group.

**Comment by Unknwon** [comment]
@v01d thanks again!

Make sense, Gogs right now have different mechanism which GitHub uses. So, hmm, sorry about that. (PS: it can be a separate feature request but no promise in case it conflicts too much with current design).

**Comment by v01d** [comment]
Maybe just adding support for "guest" users would be enough for this use
case. These would not be able to see even public repos, unless they are
added as collaborators for that repo. If you think this would be feasible,
I can rename this request. Otherwise, feel free to close it =)

**Comment by Unknwon** [comment]
> Maybe just adding support for "guest" users would be enough for this use
case

Can you define this "guest"? Who guests to what? Is it like something read-only access collaborators?

**Comment by v01d** [comment]
These users are not part of my everyday colleagues. But they may want to
contribute to some of our repos. Thus, since I would have mostly everything
public (since I assume only logged-in users can access gogs), for these
"guest" users, I need them to not be able to see anything but the specific
repo I want.

**Comment by Unknwon** [comment]
Hmm... understand some of, but not entirely.

Anyway, I'm going to add this config option for you.

**Comment by v01d** [comment]
Maybe it helps with an actual example. This is a research group where we
have repos for c++ projects, latex presentations and also maybe some data
sensitive repos. Researchers are able to see everything. Then we have
master students who can create personal repos. They can see everything but
data-sensitive repos (which can be marked as private). Then there are
persons not working at our lab, who may we want to work with over a
specific code repo and thats it. So we dont want to let everything be
readable for them just to access a single repo.

Since we would organize repos under different organizations, this
protection would require setting several teams which would be cumbersome.
So, by marking these users as "guests" they can log-in but cannot see
anything unless they are marked as collaborators.

Makes sense?

**Comment by Unknwon** [comment]
I understand now! Thanks a lot!

Yeah, so if access control can cross organization can make things much easier in your case, like the namespace you talked about.

PS: Maybe this is something you're looking for https://github.com/gogits/gogs/issues/1062

**Comment by v01d** [comment]
Yes, that would also make everything easier, and might be a more general
solution. Maybe it would be called "global teams".

I don't really need wild repos, as I switched to manual repo creation. Too
many botched repos were created by typos =b

**Comment by Unknwon** [comment]
LOL.

**Comment by linquize** [comment]
This feature (all private repos) is useful for company environment.

**Comment by Unknwon** [comment]
Please try out `develop` branch!

**Comment by Unknwon** [comment]
Forgot to mention the config option is `[repository] FORCE_PRIVATE = true`.

**Comment by Unknwon** [comment]
Close as implemented.
