### ISSUE TITLE
500 when filename contains Chinese

### ISSUE THREAD

**Issue by lgzhang** [gogits/gogs#1658]
您好，现在我有存入一些中文 文件名文档的一些需求
通过gogs，存入没有问题。 
但在网页上打开时，会报500错误。改成英文的没有此问题。
请问下，这个可以有办法解决么，非常感谢~

**Comment by Unknwon** [comment]
Thanks your feedback!

1. What is your Gogs version?
2. What is the 500 error in the log exactly?
3. What is the exact file name?
4. Can you reproduce on https://try.gogs.io ?

**Comment by Unknwon** [comment]
Remain close until more feedback.
