### ISSUE TITLE
Change label title resets color

### ISSUE THREAD

**Issue by jjjabc** [gogits/gogs#1659]
version:*0.6.9.0903*
* 修改已有标签文字，不做颜色修改。
![只修改文字](https://cloud.githubusercontent.com/assets/10386570/9952642/c765bee2-5e0a-11e5-9a99-562e38bde396.jpg)

* 点击确认后，标签颜色变为绿色
![标签颜色变为绿色](https://cloud.githubusercontent.com/assets/10386570/9952650/d2b8a2f0-5e0a-11e5-9b78-659d00f62c2e.jpg)

**Comment by Unknwon** [comment]
Thanks your feedback!

I've pushed a fix to `develop` branch and you can also test on https://try.gogs.io .

**Comment by jjjabc** [comment]
@Unknwon confirmed that bug has been fixed

**Comment by Unknwon** [comment]
Thanks your confirmation!
