### ISSUE TITLE
Limit 401 only to real Git URLs

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#1660]
Visiting an url like `<user>/<repo>/badurl` will show an authentication window, and if you cancel it, it will render a `401 Unauthorized` message. I believe this error should be 404, and there shouldn't be basic-auth window anyway.

This https://github.com/gogits/gogs/blob/6a5c87afdd32286cb1e8f92d330960f5f8641967/routers/repo/http.go#L31 function should probably display gogs login page if user is not logged in?

**Comment by Unknwon** [comment]
> Visiting an url like <user>/<repo>/badurl will show an authentication window, and if you cancel it, it will render a 401 Unauthorized message.

If you're meeting this, you're going into somewhere git protocol uses, 404 will make your HTTP/HTTPS auth never happen again. Where returns 401 so Git knows it's time to ask your username and password.

Maybe should do user-agent check see who is requesting?

**Comment by xPaw** [comment]
I'm just opening it my browser (chrome). You can put any word there, and it will show basic auth window.

https://try.gogs.io/unknwon/gogs/badurl this just shows plain text "Not Found"

**Comment by Unknwon** [comment]
I think you're not reading my comments. :mask:

**Comment by xPaw** [comment]
Oh you meant a suggestion for the code, I thought you asked to check my user agent :D

Perhaps it should just do basic auth for real urls that git calls?

**Comment by Unknwon** [comment]
> Perhaps it should just do basic auth for real urls that git calls?

Yes, I think we can make routing rules more specifically for real URLs, let me check carefully with Git documentation and give you feedback. :wink:

**Comment by bkcsoft** [comment]
This would be a security issue, since you can then hit the server with random URLs and see which ones exist and which don't by checking if it's 404 or 401...

**Comment by Unknwon** [comment]
Should work better now.
