### ISSUE TITLE
Cannot delete repository

### ISSUE THREAD

**Issue by dicarlosystems** [gogits/gogs#1661]
When attempting to delete a repository that is no longer needed, I get a message stating:

Please make sure that the repository name you entered is correct.

![2015-09-18 10_08_31-settings - gogs_ go git service](https://cloud.githubusercontent.com/assets/3483368/9961207/4969456c-5ded-11e5-9e9c-ddbe4ae4030d.png)

I have confirmed the repository name is correct but always receive the error.

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you upgrade to the latest version of Gogs and test again?

**Comment by dicarlosystems** [comment]
I can try but the issues feature was not working with the latest version, hence why I downgraded.  I will try it again and post results.

**Comment by Unknwon** [comment]
> was not working with the latest version,

Thanks but it is inappropriate description which really means nothing helpful :mask:

You can also test on https://try.gogs.io, it is always running latest version of Gogs in `develop` branch.

**Comment by dicarlosystems** [comment]
Perfect, working now.

**Comment by Unknwon** [comment]
:beers:
