### ISSUE TITLE
Build error after remove of oauth2 package from .gopmfile

### ISSUE THREAD

**Issue by fanningert** [gogits/gogs#1664]
Hi,
with the commit 3fb1b6a608625067a76ba90f9855d48c4d6555bd the oauth2 package is removed from the .gopmfile. But when I build the package I get following error.

```
modules/setting/setting.go:21:2: cannot find package "github.com/macaron-contrib/oauth2" in any of:
/tmp/yaourt-tmp-user/aur-gogs-git/src/build/go/src/github.com/macaron-contrib/oauth2 (from $GOROOT)
/tmp/yaourt-tmp-user/aur-gogs-git/src/build/src/github.com/macaron-contrib/oauth2 (from $GOPATH)
```

I think there is a open dependence for this package in the setting.go.

**Comment by Unknwon** [comment]
Thanks! I've pushed fix to `master`.
