### ISSUE TITLE
documentation for docker Domain setting incorrect

### ISSUE THREAD

**Issue by llamahunter** [gogits/gogs#1665]
The docs say to set the Domain to the container's IP address.  Actually, you want to set it to the docker hosts IP address.  As the docker container is running in non-host networking mode, the IP address of the container is unreachable from the outside.  That's why you need to port map 22 and 3000 though to the host ports 10022 and 10080.

**Comment by Unknwon** [comment]
Hmm... thanks!

I didn't thought about access from outside network, the original purpose was only to access Docker-based Gogs locally.

**Comment by Unknwon** [comment]
Please help check again: https://github.com/gogits/gogs/tree/master/docker#settings

**Comment by llamahunter** [comment]
Thanks!  Why would one run gogs in docker and then try to access it only from within the docker engine, tho?  Also, I think the text might be more clear as  
"But if you want to access your Gogs instance from a different physical machine, please fill in with the hostname or IP address of the docker host machine".

**Comment by Unknwon** [comment]
> Thanks! Why would one run gogs in docker and then try to access it only from within the docker engine, tho? Also, I think the text might be more clear as

If you're running in some embedded system, it could happen that Docker has a IP address can be accessed from all local computers.

**Comment by Unknwon** [comment]
Updated docs again.

**Comment by Unknwon** [comment]
Close as fixed.
