### ISSUE TITLE
Add examples of api usage with curl

### ISSUE THREAD

**Issue by strato190** [gogits/gogs#1667]
I'm trying to migrate my repos to gogs, but i'm missing something at curl command and got: 
```
{"message":"user does not exist: [uid: 0, name: ]"} 
```
everytime. 
not working curl:
```
curl -H "Content-Type: application/json" -X POST \
    -d '{ \
        "username": "strato190", \
        "password": "passwordgoeshere ", \
        "clone_addr": "/var/tmp/redminerepos/fail2ban_base.git", \
        "uid":2, \
        "repo_name": "fail2ban_base", \
        "mirror":false, \
        }'\
  http://git.domail.local/api/v1/repos/migrate?token=mytoken
```
  It would be great to have some working curl examples at docs

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

And in case you're not aware of this: https://github.com/gogits/go-gogs-client/wiki/Repositories#migrate

**Comment by strato190** [comment]
Thanks for response. Gogs installed from apt repo. version: `0.6.9-1442326153.e303d74.trusty`

**Comment by strato190** [comment]
Issue solved. The problem was at multiline json construction. json written in one line worked perfectly.

 Also found small bug. when gogs starts local migration and gogs user don't have permissions to access repository directory it show "repository does not exist" error instead of permission denied.
```
{"message":"git clone --mirror --bare --quiet: fatal: repository '/var/tmp/redminerepos/fail2ban_base.git' does not exist\n"} 
```

**Comment by Unknwon** [comment]
Thanks @strato190 !

> show "repository does not exist" error instead of permission denied.

I think it is error returned directly by Go, and Gogs doesn't know the detailed of the actual error...

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
