### ISSUE TITLE
download archive UI glitch

### ISSUE THREAD

**Issue by googlaev** [gogits/gogs#1668]
When you click to download the archive. When trying to catchup on the link above .zip .tar.gz closes the window.

**Comment by Unknwon** [comment]
Thanks your feedback!

Are you saying the problem with UI?

**Comment by googlaev** [comment]
Yes. in the UI. When you try to download the file hidden field with the link!

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/gogs/gogs

**Comment by Unknwon** [comment]
Close as fixed.
