### ISSUE TITLE
service restart packager.io

### ISSUE THREAD

**Issue by preovaleo** [gogits/gogs#1669]
HI,

Is it possible to do an automatic service restart at the end of the update on packager.io?

Have a nice day

**Comment by Unknwon** [comment]
Thanks your feedback!

cc @crohr can you help on this?

**Comment by crohr** [comment]
@Unknwon Sure, the easiest way is to add `service gogs restart || true` at the end of this file: https://github.com/gogits/gogs/blob/master/packager/debian/postinst

**Comment by Unknwon** [comment]
Thanks @crohr !

**Comment by Unknwon** [comment]
Closed by #1686
