### ISSUE TITLE
Automatic upgrade

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1670]
Though it's not the same kind of program, but I've recently tried [Syncthing](https://github.com/syncthing/syncthing). It is also written in Golang, and it offers automatic upgrade. Yes, which means, it will upgrade once a new version is available, and automatically restart itself.
I hope this will be implemented in Gogs too.

**Comment by Unknwon** [comment]
Thanks your feedback!

This feature has been thought long time ago, but based on the usage situation, people are often running Gogs in local network where does not have internet access to outside world.

I can make it as a optional feature, but may have low priority, if you wish. :smiley:

**Comment by focmb** [comment]
That would be a very nice feature.
At this time I have to do a lot of things:

- stop the sserver (sudo service gog-service stop)
- make a backup of the folder gogoits
- delete the folder gogs in gogits
- clone the dev-repo
- go to new gogs folder
- do a go get -u -tags "sqlite" ./...
- do a go build - tags "sqlite"
- copy the custom and the data folder from backup to the new gogs folder
- start the service

If an automatic update could do these steps I would be very happy

**Comment by Unknwon** [comment]
Hi @focmb ,

> clone the dev-repo

If you are using `git clone` to install Gogs from source, all you need to do it just do `git pull` and rebuild with `go build -tags "sqlite"` and you're good to restart again.

**Comment by focmb** [comment]
Oh, I will try that. Thanks for that hint.

**Comment by tboerger** [comment]
What about just using the packager.io packages?

**Comment by focmb** [comment]
running gogs on araspberry pi2. there is no packager.io package

**Comment by tboerger** [comment]
Than prebuilt binaries should help @Unknwon :)

**Comment by Unknwon** [comment]
@tboerger yes, if this is implemented, definitely will use binary or `git pull` if possible.

**Comment by joubertredrat** [comment]
+1
This feature is good, but I think that need to be possible to enable or disable this option if you can.

**Comment by mgracer48** [comment]
+1

**Comment by tboerger** [comment]
Maybe use https://github.com/sanbornm/go-selfupdate?

**Comment by Unknwon** [comment]
> Maybe use https://github.com/sanbornm/go-selfupdate?

Looks good.

**Comment by 0xbaadf00d** [comment]
Is it possible to use Github API to get latest release created (and know if update is available or not) GET /repos/:owner/:repo/releases/latest (https://developer.github.com/v3/repos/releases/#get-the-latest-release) and get link to download right package (ie: linux_amd64.zip).

Or maybe adding a new gogs cmd action like  `./gogs upgrade [--yes]` (--yes stand for auto-accept migration if new version is available) could be a good option.

**Comment by tboerger** [comment]
Than I'm pretty sure the github ratelimiting will be an issue for various people

**Comment by bkcsoft** [comment]
I threw together a small test for this a while back. It's crude but semingly works. I just need to integrate it into Gogs admin-panel somehow :laughing:
And yes, ratelimiting applies...

https://gist.github.com/bkcsoft/7129de478392a09994384f3d2b3e096f

**Comment by tboerger** [comment]
go-selfupdate works pretty good for my projects, but all my projects are single file deployments

**Comment by bkcsoft** [comment]
@tboerger yeah, that's what I tried to "fix" with that one. I run it as part of a weekly cron-job. If the program (in the gist) updates gogs the script (ran by cron) restarts gogs :smiley:

**Comment by bkcsoft** [comment]
Also, the rate-limit is 5000 hits per hour :trollface:

**Comment by tboerger** [comment]
Don't forget company networks ;)

**Comment by bkcsoft** [comment]
Not sure how that would change the rate-limit though :confused:

**Comment by tboerger** [comment]
> Not sure how that would change the rate-limit though 😕

I'm hitting quite often the rate limit of GitHub in my office. And this will happen for others as well, so pretty bad behavior especially since gogs can be easy used within corporate networks.

**Comment by bkcsoft** [comment]
Corps don't auto-upgrade, problem solved :trollface: 

But if they do wanna auto-upgrade, it's easy enough to provide gogs with a specific auth-token for that :smile: And (preferably) it would only check at "slow" intervals (think daily at most), so I don't really see how it would affect anyone at all.

**Comment by Unknwon** [comment]
We don't have to call GitHub APIs, we can host a file on https://dl.gogs.io . Also, I propose change this issue to check updates, but do not update itself which seems dangerous...

**Comment by JokerQyou** [comment]
My first thought is to host a RSS feed file on gogs website, and to have
gogs instances regularly check that RSS feed to see if there's an update.
And speaking of file operations, making a backup of current gogs
installation would be just OK. Gogs can delete the backup archive after
running for several days, just like how Windows backup its system files
before updating.

**Comment by bkcsoft** [comment]
or just "cache" the result from githubs release-api? cache as in save the output on dl.gogs.io when you make a release

**Comment by itsgarryb** [comment]
Would love to see a feature like this! It's just fine if you let the user choose whether to upgrade or not, as long as the upgrade process is all (or almost all) automatic.

**Comment by Unknwon** [comment]
I wouldn't plan to implement automatic upgrade, but new version check.

**Comment by joubertredrat** [comment]
> I wouldn't plan to implement automatic upgrade, but new version check.

Why not automatic upgrade as optional then? You can enable or not, but default is not enabled.

**Comment by itsgarryb** [comment]
> Why not automatic upgrade as optional then? You can enable or not, but default is not enabled.

Yes, maybe the reason for this is obvious but I can't see nor find it. Can you point out why are you not considering to implement the automatic upgrade feature?

**Comment by Unknwon** [comment]
@joubertredrat taking care of upgrade is much more non-core work and very environment dependent, use Docker instead.

**Comment by Unknwon** [comment]
Merge to https://github.com/gogits/gogs/issues/2986
