### ISSUE TITLE
Debian daemon not works

### ISSUE THREAD

**Issue by mirkhamidov** [gogits/gogs#1671]
Istalled under user git to directory /home/git/gogs

If run 
`./gogs/gogs web --config ./gogs/custom/conf/app.ini`
all works
```
2015/09/21 20:01:18 [T] Custom path: /home/git/gogs
2015/09/21 20:01:18 [T] Log path: /home/git/gogs/log
2015/09/21 20:01:18 [I] GitMelarn 0.6.9.0903 Beta
2015/09/21 20:01:18 [I] Log Mode: File(Info)
2015/09/21 20:01:18 [I] Redis Supported
2015/09/21 20:01:18 [I] Memcache Supported
2015/09/21 20:01:18 [I] Cache Service Enabled
2015/09/21 20:01:18 [I] Session Service Enabled
2015/09/21 20:01:18 [I] Mail Service Enabled
2015/09/21 20:01:19 [I] SQLite3 Supported
2015/09/21 20:01:19 [I] Run Mode: Production
2015/09/21 20:01:19 [T] Doing: CheckRepoStats
2015/09/21 20:01:19 [I] Listen: http://0.0.0.0:3000
```

than a file from `scripts/init/debian/gogs` were copied to `/etc/init.d/gogs` and all works with adding it to system done.
when
`$ sudo service gogs start`
server gogs not work (it gives '502 Bad Gateway')

and if

```
$ sudo service gogs status
● gogs.service - LSB: A self-hosted Git service written in Go.
   Loaded: loaded (/etc/init.d/gogs)
   Active: active (exited) since Пн 2015-09-21 19:49:03 MSK; 14min ago
```

and nothing here
```
ps ax | grep gogs
 1028 pts/0    S+     0:00 grep gogs
```
and here 
`sudo netstat -tulpn`

and more

```
$ sudo service gogs stop
$ sudo service gogs status
● gogs.service - LSB: A self-hosted Git service written in Go.
   Loaded: loaded (/etc/init.d/gogs)
   Active: inactive (dead) since Пн 2015-09-21 20:05:11 MSK; 1s ago
  Process: 984 ExecStop=/etc/init.d/gogs stop (code=exited, status=0/SUCCESS)

сен 21 20:05:11 mgit gogs[984]: Stopping Go Git Service: gogs.
```

What im doing wron?

**Comment by oxyno-zeta** [comment]
I don't for your version. But I see that the init script has been changed between 0.6.1 and 0.6.13. I do the update from one to the other and I keep the old script. No problem for me. Maybe try with the old one.

**Comment by JokerQyou** [comment]
I've seen this today.

If I run `sudo service gogs start`, and gogs will not start, the init script left the `/var/run/gogs.pid` file there, but there is no gogs process, and `sudo service gogs status` will tell you that too.
But if I run `/etc/init.d/gogs start`, gogs will run, and `sudo service gogs status` gives the status too. 

I think there's something wrong with the startup procedure.

**Comment by JokerQyou** [comment]
http://download.prodigy7.de/files/programs/any/syncthing/syncthing This might help.

**Comment by Unknwon** [comment]
Thanks your feedback!

But you have to dump the log info here so we can help you...

**Comment by JokerQyou** [comment]
Right now I'm using the init script just before [98c719c](https://github.com/gogits/gogs/commit/98c719c342d796e4e651270ca4a43523df721251) and it's working fine. I'll try the latest script and see what's in the log once I get back home.

**Comment by mirkhamidov** [comment]
I tried to watch log, there is empty

**Comment by Unknwon** [comment]
@mirkhamidov I've met someone has similar issue before, so if there is no log for daemon(whatever service tool you use), it does not start Gogs anyway.

The final solution to him is switch to supervisor and works very well.

**Comment by mirkhamidov** [comment]
Can you explain how?

**Comment by Unknwon** [comment]
@mirkhamidov please see https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04#step-3-—-install-and-start-gogs-as-a-service as a reference.

**Comment by mirkhamidov** [comment]
tnx, I will try

**Comment by Unknwon** [comment]
:wink:

**Comment by mirkhamidov** [comment]
@JokerQyou it helped!)))


but, now, if I restart server I got in `/home/git/gogs/log/gogs.log`:
```
2015/09/28 11:44:00 [I] Log Mode: File(Info)
2015/09/28 11:44:00 [I] Redis Supported
2015/09/28 11:44:00 [I] Memcache Supported
2015/09/28 11:44:00 [I] Cache Service Enabled
2015/09/28 11:44:00 [I] Session Service Enabled
2015/09/28 11:44:00 [I] Mail Service Enabled
2015/09/28 11:44:00 [...s/routers/install.go:65 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: pq: система баз данных запускается
```

but if I did 
```
sudo service gogs restart
```
 it starts properly

```
2015/09/28 11:45:31 [I] Log Mode: File(Info)
2015/09/28 11:45:31 [I] Redis Supported
2015/09/28 11:45:31 [I] Memcache Supported
2015/09/28 11:45:31 [I] Cache Service Enabled
2015/09/28 11:45:31 [I] Session Service Enabled
2015/09/28 11:45:31 [I] Mail Service Enabled
2015/09/28 11:45:32 [I] SQLite3 Supported
2015/09/28 11:45:32 [I] Run Mode: Production
2015/09/28 11:45:32 [I] Listen: http://0.0.0.0:3000
```

im using postgresql, why it wrote `SQLite3 Supported`?((

**Comment by tboerger** [comment]
> im using postgresql, why it wrote SQLite3 Supported?((

This just shows that gogs is compiled with SQLite3 support, nothing else.

**Comment by JokerQyou** [comment]
I suppose it's just because SQLite is supported, it did not say 'SQLite enabled' or 'SQLite in use'.
Which script are you using? The old version in this repo or the one of `syncthing`?

I think it might be because by the time Gogs starts, your Postgres daemon has not yet finished starting.

**Comment by mirkhamidov** [comment]
@tboerger, @JokerQyou I see

@JokerQyou this one https://github.com/gogits/gogs/commit/98c719c342d796e4e651270ca4a43523df721251

But what should I do, to work it properly?

**Comment by JokerQyou** [comment]
I know very little about shell script, so sorry I cannot say. I've not tested server reboot yet.

**Comment by Unknwon** [comment]
@mirkhamidov I think you should just Google the posgresql error and I can't help because the error message is not in English :sob:

**Comment by JokerQyou** [comment]
The meaaage simply indicates the database server has started

**Comment by Unknwon** [comment]
@JokerQyou Hmm... if just a info message, when pg returns as error?

**Comment by JokerQyou** [comment]
This is the result of Google translate.
![image](https://cloud.githubusercontent.com/assets/1465267/10134449/4f783a3e-6618-11e5-8e49-b45a3d6b8b5b.png)

If it was 'database system not launched', it would make sense.

**Comment by mirkhamidov** [comment]
gogs need to start after pg started

**Comment by Unknwon** [comment]
@mirkhamidov seems like you found solution?

**Comment by mirkhamidov** [comment]
no, just, not using gogs yet. Will wait when it will be ready.
For tests, I just restart service after booting, and all works fine.

**Comment by Unknwon** [comment]
> gogs need to start after pg started

Then what does this comment suppose to mean... ?

**Comment by JokerQyou** [comment]
I think we know the reason why it's behaving that way -- Gogs started before Postgres server is ready, but I don't have any solution.

**Comment by Unknwon** [comment]
I'm not using init.d but for systemd, see https://github.com/gogits/gogs/blob/master/scripts/systemd/gogs.service#L5 . I suppose init.d has something similar...

**Comment by mirkhamidov** [comment]
ok

**Comment by manfer** [comment]
It should be easy to tell the init script that it requires postgreSQL.

Those that use PostgreSQL change line:

https://github.com/gogits/gogs/blob/master/scripts/init/debian/gogs#L4

to:
```
# Required-Start:    $syslog $network postgresql
```

This will ensure that gogs runs after postgreSQL daemon has started. You need to enable the postgresql script to run on start too if it hasn't been already done.
```
sudo chkconfig postgresql on
```

**Comment by seeseekey** [comment]
After use the current init file (not the file in the release) (https://github.com/gogits/gogs/commit/4a05c4a759a71706a897075405be5f437d5530a1#diff-2010a922586cdf277b495c360c8a66a3) it works.

**Comment by Unknwon** [comment]
@seeseekey thanks your confirmation!

**Comment by MarcosBL** [comment]
This change fixed the issue for me as well

https://github.com/gogits/gogs/commit/4a05c4a759a71706a897075405be5f437d5530a1#diff-2010a922586cdf277b495c360c8a66a3

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
