### ISSUE TITLE
Large amount of files in single directory causes freeze (with high CPU usage)

### ISSUE THREAD

**Issue by saskadev** [gogits/gogs#1672]
Opening directory in git repo with large amount of files (9500~ in my case) through web interface causes the Gogs to hang indefinitely without returning the page. This has also side effect of high CPU usage.
It may be good idea to limit the files viewed at once to specific number (specified in config file, perhaps) or even have paging system which only displays certain amount of files at a time but user still can go through the pages to view all files in given directory.

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/1505
