### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#1673]
Do each user on gogs has to have a shell account on the server hosting it? I have a test instance, and new users can register fine. But when trying to push a repo, gogs wants them to enter the password for the user running gogs. Could someone provide some lead on how to properly setup authentication?

**Comment by SergioBenitez** [comment]
How are you pushing to gogs? If you're using SSH, and you haven't disabled remote password login, and your users don't have their public keys uploaded to Gogs, then the remote SSH server will ask for the user's password to try to authenticate the connection. You should disable remote SSH password login via your servers SSH config. If you do this, then the SSH connection will simply fail when the connecting user doesn't have any valid keys to present.

If you're using HTTPs, it should be asking for a Gog's username/password, not a shell username/password.

P.S: Github issues are the improper venue to ask support questions. Unfortunately, I don't know of the proper venue. You should only open an issue when you strongly feel that there might be something wrong with the _software_ and can provide a paper-trail to help identify the issue.

**Comment by Fastidious** [comment]
> If you're using SSH, and you haven't disabled remote password login, and your users don't have their public keys uploaded to Gogs, then the remote SSH server will ask for the user's password to try to authenticate the connection

Right, but do the users need to exist as local accounts? Right now, registering on Gogs *does not* creates a shell account for the user.

**Comment by MathB** [comment]
No all the gogs users use the same local account "gogs" to access the repo via SSH but with their own SSH key.
Each user need to set SSH key in their account settings page.

**Comment by Fastidious** [comment]
@MathB excellent! Got it working now, thank you much. I am way too used to have the client do that for me--in the case of GitHub, the client creates the key for you, if I remember correctly.

I will try to come up with a tip, to add it to the documentation.

**Comment by Unknwon** [comment]
@Fastidious glad you found out the reason.
