### ISSUE TITLE
Multiline log message displayed on a signle line

### ISSUE THREAD

**Issue by MathB** [gogits/gogs#1674]
The problem:
On the commit page, multiline log messages are diplayed on a single line.
On the repo browser page and on the log page, only the first line is shown.

Where there is not enough space, It would be great to show the full message on mouse over in a tooltip and put an icon indicating that the message is truncated.

Gogs: 0.6.12.0914 Beta 
Git: 2.1.4
Debian 8

**Comment by MathB** [comment]
I updated Gogs and it seems that it's solved in the Commit page. Thanks
I leave this issue open for the repo browser page and on the log page showing only the first line.

**Comment by Unknwon** [comment]
@MathB thanks your update info!

**Comment by Unknwon** [comment]
This should be fixed by `master` branch.
