### ISSUE TITLE
Bad link in gogs web interface to git submodule

### ISSUE THREAD

**Issue by klingtnet** [gogits/gogs#1675]
![gogs_issue](https://cloud.githubusercontent.com/assets/1538057/10044325/361b01e2-61fa-11e5-9218-d6070f2535bf.png)

I've got a project that contains a git submodule which is stored on the same gogs server. 
The only issue is, that gogs will add the ssh port, in my case `20022`, to the link in the webinterface of the submodule: `http://some.domain/20022/username/some-project-name`. Removing the port will fix the issue.
Cloning the project and everything else works fine.

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by LeKovr** [comment]
+

**Comment by Unknwon** [comment]
Merge this thread into https://github.com/gogits/gogs/issues/2953
