### ISSUE TITLE
Flash is required to copy

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#1677]
May I suggest eliminating the need for Flash to copy the git address? I simple select/copy should suffice. Perhaps doing something like Google URL shortener does?

![screen shot 2015-09-23 at 9 59 15 am](https://cloud.githubusercontent.com/assets/8352292/10046981/d0a508dc-61d9-11e5-8769-b9c9ccb26bce.png)

**Comment by Unknwon** [comment]
Thank your suggestion, I think it's better.

But can you close this one can comment to https://github.com/gogits/gogs/issues/1396 because I think these two are talking the same thing.

**Comment by Fastidious** [comment]
Rats, yes, you are right! (I need to search first, sorry).
