### ISSUE TITLE
Allow using localhost for mailer

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#1679]
I would like to be able to use the localhost, or a different non-authenticated mailer to send out notifications, etc. It seems not possible at the moment, unless I am missing something.

**Comment by matrixise** [comment]
Have you used the configuration?

**Comment by matrixise** [comment]
see http://gogs.io/docs/advanced/configuration_cheat_sheet.html#mailer

**Comment by Fastidious** [comment]
@matrixise yes. It doesn't allow to use localhost (using a local instance of postfix or sendmail) for that. It requires a server (authentication, etc.).

**Comment by matrixise** [comment]
This config does not work with you?
```ini
[mailer]
HOST = 127.0.0.1
```

**Comment by Fastidious** [comment]
@matrixise is it working for you? I bet it is not.

**Comment by matrixise** [comment]
disable the verify of your certificate

**Comment by Fastidious** [comment]
@matrixise now you are talking, thanks! Had to do:

`SKIP_VERIFY = false`

and that worked.

**Comment by matrixise** [comment]
welcome

**Comment by gboudreau** [comment]
Quick note to whoever finds this : it seems recent versions of gogs require the port too, on the HOST; I had to use `HOST = 127.0.0.1:25` for it to work.
