### ISSUE TITLE
error: RPC failed; result=22, HTTP code = 500

### ISSUE THREAD

**Issue by FyinInc** [gogits/gogs#1682]
Trying to push about 5gb of files and cannot get pass this error: 

git -c diff.mnemonicprefix=false -c core.quotepath=false commit -q -F C:\Users\David\AppData\Local\Temp\fmxamqvy.1bt

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin master:master
POST git-receive-pack (chunked)

fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

error: RPC failed; result=22, HTTP code = 500

Pushing to https://git.XYZ.com:3000/XYZ.com/ZYZ.git
Everything up-to-date

Completed with errors, see above.

**Comment by carlosfvp** [comment]
I am having the same issue with a push of a repository wich contains multiple files wich total size of around 3.5GB

**Comment by Unknwon** [comment]
Thank you both!

Since it's a 500 error, please post the error from Gogs...

**Comment by Unknwon** [comment]
Also, I think it is related/same to https://github.com/gogits/gogs/issues/1530

**Comment by carlosfvp** [comment]
This is from http.log
2015/09/24 12:40:52 [...routers/repo/http.go:344 serviceRpc()] [E] fail to serve RPC(receive-pack): exit status 128


gogs.log have usual log
2015/09/24 16:43:42 [I] Log Mode: File(Trace)
2015/09/24 16:43:42 [I] Redis Supported
2015/09/24 16:43:42 [I] Memcache Supported
2015/09/24 16:43:42 [I] Cache Service Enabled
2015/09/24 16:43:42 [I] Session Service Enabled
2015/09/24 16:43:42 [T] Doing: CheckRepoStats
2015/09/24 16:43:42 [I] SQLite3 Supported
2015/09/24 16:43:42 [I] Run Mode: Development
2015/09/24 16:43:42 [I] Listen: http://0.0.0.0:3000

I have tried changing the log level, production or development but the log detail is doesn't change.

**Comment by Unknwon** [comment]
Can you check with this see if it helps? http://stackoverflow.com/questions/10790232/hanging-at-post-git-receive-pack-chunked

**Comment by carlosfvp** [comment]
I have found that post. I tried changing that to 512MB and 1GB and I still got the same issue.

**Comment by Unknwon** [comment]
> 2015/09/24 12:40:52 [...routers/repo/http.go:344 serviceRpc()] [E] fail to serve RPC(receive-pack): exit status 128

From what I understand based on the code, Git has failed itself and prints all the error message to you(the client side), Gogs is transparent here.

Are you also using Nginx? The HTTP buffer can be limited by Nginx config as well.

**Comment by carlosfvp** [comment]
Nope. I am not using any proxy at all. I am testing changing the buffer to 5kbytes and I will post the results here.

**Comment by carlosfvp** [comment]
Still the same error.

Counting objects: 106486, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (39200/39200), done.
Writing objects: 100% (106486/106486), 2.59 GiB | 11.19 MiB/s, done.
Total 106486 (delta 60867), reused 101269 (delta 55947)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date


This are the results of the push.

**Comment by Unknwon** [comment]
@carlosfvp Just a suggestion, why don't you push through SSH for this large amount of content?

**Comment by carlosfvp** [comment]
Thank you for the suggestion. I will test this and I will post the results.

**Comment by Unknwon** [comment]
:wink:

**Comment by FyinInc** [comment]
How would one do this on a Windows 2012 server?

**Comment by carlosfvp** [comment]
@FyinInc You can do that by installing ssh as any other service under Windows. At the end I figured that the server was running out of memory. I was confident this wasn't the issue because I had 8gb of ram free. There must be some kind of memory leak. As I saw on the related issue, this memory leak might not be fixed yet. Anyway, I will test tomorrow adding some extra RAM on the server.

**Comment by linquize** [comment]
Chunked transfer caused me some troubles when hosting apps via an HTTP server.

**Comment by carlosfvp** [comment]
Maybe the http library used for gogs is not fully compatible with chunked transfers.

**Comment by Unknwon** [comment]
@carlosfvp about memory leak:

Even if there is no memory leak, Go GC can't collect objects back because it is in use while you're still transfer data.

**Comment by carlosfvp** [comment]
I needed 10GB free RAM. So the HTTP library seems to work fine but at the end of the process there is still 4GB of RAM used by gogs.exe process.

This project is amazing and I will give a try to learn GO and add some commits.

Thank you!

**Comment by JokerQyou** [comment]
Simply mirroring a large repository would cause a `bad gateway` error, it seems like Gogs is doing synchronous action to pull the target git repo after the form is submitted.

**Comment by Unknwon** [comment]
@carlosfvp thanks your info!

Which version of Gogs are you using?

**Comment by FyinInc** [comment]
Increasing the virtual memory I got:

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags
origin master:master
POST git-receive-pack (chunked)

fatal: The remote end hung up unexpectedly

fatal: The remote end hung up unexpectedly

error: RPC failed; result=22, HTTP code = 500

Pushing to https://git...
Everything up-to-date

**Comment by Unknwon** [comment]
Why do people not reading docs and not response to my question....?

Please read https://github.com/gogits/gogs/blob/master/CONTRIBUTING.md#bug-report :sweat_smile:

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by Eng3l** [comment]
I have the same problem

**Comment by Unknwon** [comment]
@Eng3l can you update to latest `develop` branch see if error prints more accurately?
