### ISSUE TITLE
Disable clicking on avatar

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#1683]
For example, go https://try.gogs.io/makhov, click on the avatar, it opens the image. I propose to disable that.

**Comment by Unknwon** [comment]
Hmm, right. 

If you're viewing your own profile page, it links to your settings. But yes, make no sense to a raw picture.

**Comment by Unknwon** [comment]
Hi! I've pushed a quick fix for this to `develop` branch and has updated https://try.gogs.io as well.

PS: There is still a small UI problem, but link has been removed, will fix that at the right time.

**Comment by Fastidious** [comment]
Looks much better!

**Comment by Unknwon** [comment]
Thanks your confirmation! 

I will close this issue when I fix the UI style(the little hand of your indicator)
