### ISSUE TITLE
“控制面板”首页有一个用户的提交记录不显示呢

### ISSUE THREAD

**Issue by lyongde** [gogits/gogs#1685]
项目里有3人，我的“控制面板”首页只能看到其中1人提交，同时对方也看不到我的提交和其他人的提交呢，哪里设置不对吗？

**Comment by Unknwon** [comment]
> 项目里有3人

Which one you can see? And what are the roles of others, are they collaborator?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by lyongde** [comment]
开发者都不是协作者，新项目是同一个组织的成员，只能能看到其中一个。

**Comment by Unknwon** [comment]
Thanks your info!

Can you give an example?

Also, please report you version of Gogs, database and system info.
