### ISSUE TITLE
Git bash error when moving to a different directory structure

### ISSUE THREAD

**Issue by dabaer** [gogits/gogs#1688]
Hi, I get the following error when trying to push to the remote server:

```
bash: /home/gogs/go/src/github.com/gogits/gogs/gogs: No such file or directory
fatal: Could not read from remote repository.
```

I had copied the configuration and database only to the new binary distribution of gogs under a different directory. I looked through the config file but there was nothing referring to that location, so I am unsure of how to fix this.

The gogs binary is currently at `/home/gogs/gogs/gogs`.

**Comment by Unknwon** [comment]
There is a link called `Rewrite all update hook of repositories`, try that and see if it works.

**Comment by dabaer** [comment]
Hmm - that looked like it was what i needed to fix it, but I still get the error

**Comment by Unknwon** [comment]
Hmm... forgot that one, do `rewrite all authorize keys file` as well please.

**Comment by dabaer** [comment]
Ah yes, that was it - thanks!

**Comment by Unknwon** [comment]
:wink:
