### ISSUE TITLE
Auto/Manual session clean, in-memory session

### ISSUE THREAD

**Issue by BurakDev** [gogits/gogs#1690]
Hello,

I have 70 Gb sessions file on my server.. Why gogs didn't clean automacly folder ? Or using a manual button in admin area.

And why you don't use in-memory session storage ?

Thanks in advance and sorry for my bad english

**Comment by tboerger** [comment]
You can configure gogs to use memory or even redis as a session storage.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I don't understand your situation. 

If you didn't config anything, Gogs uses in-memory session. So I don't know where the 70gb data comes from and how do you know Gogs generates that?

**Comment by BurakDev** [comment]
A http flood against my gogs, data/sessions/ folder, I deleted it (90 Gb deleted)

**Comment by Unknwon** [comment]
@BurakDev hmm... well that seems reasonable to me. 

My mistake, after installation, the default file provider is `file`, and by default, it lives 7 days.

**Comment by TheHowl** [comment]
What I noticed though is that when files are pruned, empty folders are not. Which, at continuated use, may lead to having quite a huge folder size (as every folder's index is at least 4KB). I've put a workaround to it on my server by adding this to my crontab:

```
0 * * * * find <type_gopath_here>/src/github.com/gogits/gogs/data/sessions/ -type d -empty -delete
```

**Comment by Unknwon** [comment]
@TheHowl you can change to use Redis which should avoid the index 4kb.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
