### ISSUE TITLE
supervisor管理gogs,需要增加environment=HOME="xxx",USER="xxx"

### ISSUE THREAD

**Issue by yijunjun** [gogits/gogs#1695]
如题，希望这两个能增加到配置文件中指定。
缺HOME环境变量-错误提示:
https://github.com/gogits/gogs/blob/master/models/publickey.go:60 homeDir()] [E] Fail to get home directory: Cannot specify home directory because it's empty

https://github.com/Unknwon/com/blob/master/path.go
// HomeDir returns path of '~'(in Linux) on Windows,
// it returns error when the variable does not exist.
func HomeDir() (home string, err error) {
	if runtime.GOOS == "windows" {
		home = os.Getenv("USERPROFILE")
		if len(home) == 0 {
			home = os.Getenv("HOMEDRIVE") + os.Getenv("HOMEPATH")
		}
	} else {
		home = os.Getenv("HOME")

缺USER环境变量-错误提示:
https://github.com/gogits/gogs/blob/master/modules/setting/setting.go:339 NewConfigContext()] [E] Expect user(root) but current user is: 

https://github.com/gogits/gogs/blob/master/modules/user/user.go
func CurrentUsername() string {
	curUserName := os.Getenv("USER")
	if len(curUserName) > 0 {
		return curUserName
	}

	return os.Getenv("USERNAME")
}

**Comment by Unknwon** [comment]
Thanks your feedback!

But the template file for supervisor here: https://github.com/gogits/gogs/blob/master/scripts/supervisor/gogs

Has already implied you need set those two values.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
