### ISSUE TITLE
Support for todo list in markdown document

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1696]
Like the one among additional features of GitHub flavored markdown, as seen [here][1]

[1]: https://help.github.com/articles/writing-on-github/#task-lists

**Comment by Unknwon** [comment]
Thanks your feedback!

Somehow I remember someone has requested, but I can't find it now, so I'll keep this as record.

**Comment by ChangePlaces** [comment]
Personally, I prefer to go in and edit the comment when completing an item on the list! Having a task list would make it too easy to accidently click.

**Comment by tboerger** [comment]
@ChangePlaces I believe that you are pretty rare with your opinion. I know only about people that really like this feature of Github.

**Comment by ChangePlaces** [comment]
@tboerger  maybe it's a good thing i'm "rare" ;)

**Comment by tboerger** [comment]
@ChangePlaces you can take it however you want ;)

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/1048
