### ISSUE TITLE
Inconsistent link of e-mail URL after sign up 

### ISSUE THREAD

**Issue by Sauermann** [gogits/gogs#1697]
I tried to set up an account on try.gogs.io
The Button "Sign in to your account" points to the domain of the E-Mail I entered.

Here is an extract of the html-code of the confirmation page:

    <div class="text right">
        <a class="ui green button" href="http://mysurname-consulting.de">Sign in to your account</a>
    </div>

I would expect that the link of the button stays on the same domain.

**Comment by TheHowl** [comment]
>It's not a bug, it's a feature!
>
>_-- Every developer_

That's actually intended. As it requires email confirmation, the link sends you to the website that _should_ have a web email interface for your email address, through which you can click on the confirmation link for your account.

**Comment by Sauermann** [comment]
Thanks for the explanation - this is a behaviour I have not seen before. Perhaps it would be better to explicitely state on the button that it links to the most likely webmailer.

**Comment by Unknwon** [comment]
Thanks your feedback!

>  it links to the most likely webmailer

What does this mean?

And as @TheHowl mentioned, it is designed to do so.

**Comment by TheHowl** [comment]
"it links to the webmail interface which is very probably the one associated with the email address"

**Comment by TheHowl** [comment]
So, what he means is that the button should rather say: "Go check your email", or something of the sort.

**Comment by Fastidious** [comment]
> And as @TheHowl mentioned, it is designed to do so.

Right, but the assumption is there that *everyone* is using Gmail, Yahoo, Outlook, Hotmail [insert other major email provider here]. That is far from the truth. Many users are using Google Apps, Outlook Enterprise, etc., with their own domains.

I **strongly** recommend we do not assume, if user enters `user@example.com`, that there is a webmail interface at `example.com`, because that isn't true, more often than you think. I would rather have to message stating "Check your mail, etc., etc." and a link to login, or back to root instead.

**Comment by Sauermann** [comment]
Thanks @TheHowl that is precisely what I mean.

**Comment by Unknwon** [comment]
Gogs used to point you to mail.xx.xx but someone isn't happy, so now it's more general. I decide to make me happy this time... 😭

**Comment by Fastidious** [comment]
@Unknwon you are the boss! :-)

**Comment by Unknwon** [comment]
In fact, what can be a better, more general solution to this?

**Comment by TheHowl** [comment]
Perhaps not link to anything, and just write "Check your email (email@address.com) to confirm your account."?

**Comment by Fastidious** [comment]
I agree with @TheHowl.

**Comment by Fastidious** [comment]
This reminds me so much of this one, https://github.com/flarum/core/issues/541. In fact, it is the same "dilemma."

**Comment by Unknwon** [comment]
@TheHowl I just thought the same :100:

cc @Sauermann

**Comment by Naxiz** [comment]
The button to go to the webmail is completely unnecessary in my opinion. Everyone knows how to access their email, so I suggest just removing the button and displaying a message like "please check [email address] to confirm your account".


There's no way to get the URL right in all cases. The only thing the button does is create confusion.

**Comment by TheHowl** [comment]
@Naxiz We already got to that conclusion in the past 4 comments :P

**Comment by Unknwon** [comment]
I fount that Gogs already says please sign in to xxx, so I simply removed the button. :trollface:

**Comment by Sauermann** [comment]
Thanks, looks much less confusing now. Closing issue as resolved.

**Comment by Unknwon** [comment]
:trollface:
