### ISSUE TITLE
500 error when adding new issue with labels defined

### ISSUE THREAD

**Issue by kpande** [gogits/gogs#1701]
Produces 500 error every time -

[...outers/repo/issue.go:362 NewIssuePost()] [E] NewIssue: newIssue: label does not exist [id: 6]

The labels all exist, though. Removing label assignment, adding issue, and re-adding label works.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by neolit123** [comment]
@Unknwon
i've encountered this bug yesterday.

setup:
```
- Gogs version (or commit ref):
gogs_v0.8.25_linux_amd64.zip
- Git version:
git version 1.7.9.5
- Operating system:
Ubuntu 12.04.1 LTS (almost a clean install, running in VBox)
- Database:
SQLite
```

steps:
- create a new repository via the Web UI
- push something
- create a couple of labels for the issue tracker
- create issue
- write some text for the title and message of the issue
- add both labels on the right
- error 500

```
repo/issue.go:427 NewIssuePost()] [E] NewIssue: newIssue: label does not exist [id: XXXXX]
# where XXXX seems to be an index out of the whole range of user labels
```
if you select only a single or no labels out of the list when creating the issue it does work.

**Comment by Unknwon** [comment]
@neolit123 Hi, can you reproduce this on https://try.gogs.io?

I tested create a new issue with two labels and no error occurs.

**Comment by neolit123** [comment]
> I tested create a new issue with two labels and no error occurs.

indeed, it doesn't happen on that server.

**Comment by neolit123** [comment]
@Unknwon, let me know how i can help further with logs, screen captures and so on.

**Comment by Unknwon** [comment]
@neolit123 new release was out yesterday, please try again with the new one?

**Comment by neolit123** [comment]
@Unknwon, ok will do later today.

**Comment by neolit123** [comment]
@Unknwon, i can reproduce the issue with 0.8.43.0223.

i removed the previous installation folder (i.e. home/myuser/gogs/ which includes the sqlite3 database, custom/conf/app.ini), recreated the server completely and the first thing i've tried is to create a project and an issue with the two labels.

**Comment by Unknwon** [comment]
I think it is a SQLite3 specific problem, please file an issue for this.

**Comment by kpande** [comment]
This issue has been a major problem for my installation too on sqlite3

**Comment by neolit123** [comment]
@Unknwon 
> I think it is a SQLite3 specific problem, please file an issue for this.

file a new Gogs issue, you mean?

**Comment by Unknwon** [comment]
Yes.
