### ISSUE TITLE
French men to approuve on crowdin

### ISSUE THREAD

**Issue by preovaleo** [gogits/gogs#1702]
Hello,

The french translation is bad.
Can you please add someone that he can approve good new translation on crowdin

Thank you

**Comment by Unknwon** [comment]
Hi! What's your username on Crowdin? I can give you permission to approve/disapprove French translation.

**Comment by preovaleo** [comment]
preovaleo

**Comment by Unknwon** [comment]
OK! You are able to approve/disapprove French translation now.

**Comment by preovaleo** [comment]
OK Thank you i will do that tomorrow

**Comment by Unknwon** [comment]
:wink:
