### ISSUE TITLE
Webhook only triggered on gogs restart

### ISSUE THREAD

**Issue by tarioch** [gogits/gogs#1703]
I added my first webhook to a repository and now have the strange effect, that they don't get executed until I restart gogs.

So on this repository the behavior is:
* push happens
* I see an error entry with 1970-01-01 01:00:00 CET on the recent deliveries page

now if I restart gogs, it will trigger all the missing hooks and update the recent deliveries page.

This basically makes webhooks not working at all.

I'm running from the latest packages: package version is 0.6.9 but strange enough page shows 0.6.13.0918

**Comment by Unknwon** [comment]
Thanks your feedback!

> I see an error entry with 1970-01-01 01:00:00 CET on the recent deliveries page

What does this mean?

**Comment by Unknwon** [comment]
> I'm running from the latest packages: package version is 0.6.9 but strange enough page shows 0.6.13.0918

Can you try install Gogs without third-party packages(0.6.15 just released) and test again?

**Comment by tarioch** [comment]
Retried with 0.6.15 same error still exists.

Basically after the webhook is triggered, there is an entry on the Webhooks "Recent Deliveries" page with a hash, a date of 1970-01-01 01:00:00 CET and no request/response

One such entry is added for each additional push (so basically whenever the webhook should get triggered)

If I now restart gogs the actual webhook calls take place and the information gets updated in "Recent Deliveries"

**Comment by Unknwon** [comment]
Thanks for following up!

1. How did you retry? From source or binary?
2. Can you reproduce on try.gogs.io?

**Comment by tarioch** [comment]
1. I retried from binary
2. Unfortunately I can't use try.gogs.io to test this out

**Comment by Unknwon** [comment]
Uh...? Why can't test on try.gogs.io?

**Comment by tarioch** [comment]
Not able to clone through office firewalls.

**Comment by Unknwon** [comment]
😂😂😂😂😂

**Comment by Unknwon** [comment]
Which database are you using?

**Comment by tarioch** [comment]
mysql

**Comment by Unknwon** [comment]
Do you push by HTTP/HTTPS or SSH?

**Comment by tarioch** [comment]
ssh

**Comment by tarioch** [comment]
I did some more investigation, maybe any of the following could be useful:
* The repository I'm trying to have the webhook triggering is in an organization
* The repository name has a "-" in the name
* After the push there is an entry in hook_task db
Content of it is
id: 29
repo_id: 5
hook_id: 2
uuid: deab6d8a-e138-4326-bada-935b59633f3c
type: 1
url: MYTESTURL
payload_content:LOOKS VALID
content_type: 1
event_type: push
is_ssl: 0
is_delivered: 0
delivered: 0
request_content: EMPTY
response_content: EMPTY
is_succeeded: 0

**Comment by Unknwon** [comment]
Thanks for the detail!

**Comment by tarioch** [comment]
Any further idea what could go wrong or what I could test?
It looks like at least the communication from git push to gogs works (as I guess otherwise there wouldn't be a db entry)

**Comment by Unknwon** [comment]
I'm sorry have got time to debug, will do ASAP.

**Comment by Unknwon** [comment]
Update: I'm testing with MySQL and 0.6.15, push through SSH to an organization owned repo and webhook is sent.

**Comment by Unknwon** [comment]
So I recommend you update to `master` or 0.6.15 version and test again... :smiley:

**Comment by tarioch** [comment]
I did upgrade to 0.6.15 but unfortunately it still has the same issue :(

**Comment by Unknwon** [comment]
Can you check the router log that right after you SSH push, there is something like:

```
[Macaron] Completed /org7/repo-name/hooks/trigger 200 OK in 1.73489ms
```

which triggers the webhook deliver event.

**Comment by Ronmi** [comment]
I have same issue in 0.6.15 and master branch 79fb24a397f4c49d03b8fa09a6dd3c4226247637 (both installed from source)
The router log is empty after I did ssh push, but webhook task seem stored into database correctly.

Go version: 1.5.1
configuration file: `custom/data/app.ini`

```
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE = sqlite3
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = 
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[server]
DOMAIN = my.test.server
HTTP_PORT = 3000
ROOT_URL = http://my.test.server/
DISABLE_ROUTER_LOG = false

[session]
PROVIDER = file

[log]
MODE = console
LEVEL = Trace

[security]
INSTALL_LOCK = true
SECRET_KEY = SOME_SECRET

[service]
DISABLE_REGISTRATION = true

[webhook]
SKIP_TLS_VERIFY = true
```

dump of webhook table:

```
$ sqlite3 data/gogs.db 'select * from webhook'
1|3|http://127.0.0.1:6789/|1|qwe|{"push_only":false,"send_everything":true,"choose_events":false,"events":{"create":false,"push":false}}|0|1|1||0|2015-10-05 06:32:38|2015-10-05 07:58:55|1
$ sqlite3 data/gogs.db '.schema webhook'
CREATE TABLE `webhook` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `repo_id` INTEGER NULL, `url` TEXT NULL, `content_type` INTEGER NULL, `secret` TEXT NULL, `events` TEXT NULL, `is_ssl` INTEGER NULL, `is_active` INTEGER NULL, `hook_task_type` INTEGER NULL, `meta` TEXT NULL, `org_id` INTEGER NULL, `created` DATETIME NULL, `updated` DATETIME NULL, `last_status` INTEGER NULL);
$ date
一 10月  5 15:59:32 CST 2015
```

Hope these information can help you find out the bug :)

**Comment by Unknwon** [comment]
Thanks @Ronmi , can you check https://github.com/gogits/gogs/issues/1703#issuecomment-145158591 in your router log as well?

**Comment by Ronmi** [comment]
The router log is empty after I push through ssh, and console does not output anything right after I did the push.

**Comment by Unknwon** [comment]
@Ronmi I kind of know why... are you running Gogs under suburl?

**Comment by Ronmi** [comment]
No, but behind a nginx reverse proxy.

**Comment by Unknwon** [comment]
What is your URL of Gogs home page looks like?

**Comment by Unknwon** [comment]
BTW, does you NGINX rejects `HEAD` http request?

**Comment by Ronmi** [comment]
Just same as I posted configuration, `http://my.test.server/`. I'm going to introduce gogs to our company, and making a server for demo, using a faked host name with modified `/etc/host` file.

**Comment by Ronmi** [comment]
I  use apt-get to install nginx in debina jessie, my nginx site configuration is 

```
server {
    listen 80;
    server_name my.test.server;
    location / {
        proxy_pass http://127.0.0.1:3000;
        include proxy_params;
    }
}

**Comment by Unknwon** [comment]
Thanks again!

I just pushed https://github.com/gogits/gogs/commit/db00aa7653937ce62d1ffa37661e50ea4bee80cd to add log for triggering hook after SSH push to `develop` branch.

Can you help test again?

**Comment by Ronmi** [comment]
I'm home now, maybe I can build another gogs instance in my own computer :)

**Comment by Unknwon** [comment]
@Ronmi I think you will find out everything is suddenly working and still broken on company's machine.. :joy:

**Comment by Ronmi** [comment]
Yup, it's work now, and that's great new for me :)

BTW, I found the UI color theme looks much different with what I saw at work, maybe the reason is I forget to clean the template cache?

**Comment by Unknwon** [comment]
> BTW, I found the UI color theme looks much different with what I saw at work, maybe the reason is I forget to clean the template cache?

No, it's not your fault, it's hmm.. change in the progress... sorry about that.

**Comment by tarioch** [comment]
Currently on vacation, so can't check at work. But we're running behind nginx as well, I think config is similar to the one from ronmi

**Comment by Unknwon** [comment]
@tarioch  no problem, enjoy your vocation!

**Comment by Ronmi** [comment]
Go back to office and everything works now (without any updating or recompiling, weird).

I've cherry picked db00aa7653937ce62d1ffa37661e50ea4bee80cd onto v0.6.15, so we can get fresh data if it happens again.

**Comment by Unknwon** [comment]
@Ronmi :joy:

**Comment by tarioch** [comment]
I don't see 

```
[Macaron] Completed /org7/repo-name/hooks/trigger 200 OK in 1.73489ms
```

in any log files. I also don't have a router.log file.

But this gives me a new idea what could be wrong. How is the process of the webhook triggering? This sounds almost as if it would be something like

1) git push, triggers gogs cmd line
2) gogs cmd line fires http request to gogs website?
3) gogs website triggers webhook call

Is this correct? I did not think that there was a roundtrip via the web. This could open up a couple of more things that could be wrong. How exactly does the call happen? Can I manually trigger this (e.g. with curl) to figure out if things like hostname/ip and so on are working?

**Comment by tarioch** [comment]
WORKS!!! 

Stupid mistake on my end. Now that I knew what was happening it's easy to figure out:

ROOT_URL was wrong

**Comment by Unknwon** [comment]
@tarioch glad you found the issue!

**Comment by Fusty** [comment]
I'm having this exact same issue, but there is nothing wrong with my ROOT_URL

When I hit the "Test Delivery" button that test succeeds.  Both Request and Response areas are filled and I get the messaging in Slack. 

When I submit a push it fails.  I get a red triangle with an exclamation mark.  Both Request and Response areas are "n/a".  The date shows "1970-01-01 00:00:00 UTC".

If I restart gogs the one with the red triangle winds up getting pushed to Slack just fine, a good date is filled in, the Request and Response areas are filled and it appears as if there was never a problem.

Is there some further configuration for gogs like a crontab task that I'm missing to support webhooks?

**Comment by Unknwon** [comment]
@Fusty Please check your `log/serv.log` file see if any errors there.

**Comment by homme** [comment]
@Fusty I had the same symptoms and checked `log/serv.log` as suggested by @Unknwon. This showed errors containing this string:

    2016/05/26 13:06:06 [...ts/gogs/cmd/serve.go:128 handleUpdateTask()] [E] Fail to trigger task: Head http://localhost:3000/geodata/web-observatory-geoapi/tasks/trigger?branch=master&secret=xxx: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

This led me to fix the issue by setting `LOCAL_ROOT_URL = https://localhost:3000/` by amending instructions [here](https://github.com/gogits/gogs/issues/3077#issuecomment-219573984).
