### ISSUE TITLE
How to upgrade gogs from 0.5.11.0103 Beta

### ISSUE THREAD

**Issue by guileen** [gogits/gogs#1704]
I use gogs 0.5.11.0103 Beta for several months. But I found there is a bug that I can't get right access rights to orgnization repositories.  

So I need to upgrade my gogs.  I install 0.5.11.0103 Beta via binary release. I notice recently release version is 0.6. There must be some different in database scheme and folder structure. I can't just replace `gogs` executable file.

Are there any safe and simple way to upgrade my gogs, keep all my data.

**Comment by tboerger** [comment]
It's should work to replace just the binary. There are some config updates, but there is a default config anyway. The database should get automatically migrated.

**Comment by Unknwon** [comment]
Thanks your feedback!

As @tboerger mentioned, from 0.5.11 to 0.6.15 is still simply replace the binary.

> I can't just replace gogs executable file.

What do you mean?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
