### ISSUE TITLE
Migrated repository incompatible with --all flag

### ISSUE THREAD

**Issue by mirkhamidov** [gogits/gogs#1705]
I need to create a repo like this scheme:
on BitBucket created a private repo `gogs_test1`
and cloned it to my server like 
```git clone --bare git@bitbucket.org:***/gogs_test1.git```
and now, developers can push/pull to my local server (to this bare repo), and i can sync that local server with BitBucket without any problem like:
to push to bitbucket
```git push --all```
and if needed to sync from bitbucket
```git fetch origin +*:* --prune```
(pull/push could be done with hooks, its not a problem too)

But, if I create `New Migration` via web interface
![2015-09-28_12-09-55](https://cloud.githubusercontent.com/assets/2736223/10131609/36022c6a-65da-11e5-9ae2-7502c90e464a.png)

and try to push it shows
```
git@mgit:/repos/miroff/testgo.git$ git push --all
error: --all and --mirror are incompatible
```

but: 
```
git@mgit:/repos/miroff/testgo.git$ git remote -v
origin	https://mirkhamidov:***@bitbucket.org/***/gogs_test1.git (fetch)
origin	https://mirkhamidov:***@bitbucket.org/***/gogs_test1.git (push)
```

**Comment by Unknwon** [comment]
Thanks your feedback!

I understand the content of your issue, but what does this mean?

> as real bare repo

**Comment by mirkhamidov** [comment]
this means that seem it works line `--mirror`, but alike, can push on it, but cant push to remote, strange.

It perfectly works if I create normal repo in gogs, than manually add remote (as I need, but not in interface).

**Comment by Unknwon** [comment]
> git@mgit:/repos/miroff/testgo.git$ git push --all
error: --all and --mirror are incompatible

Based on the error message, the way Gogs migrate a repo has conflict with `--all` flag. I think this is the problem.

**Comment by Unknwon** [comment]
Hi there, I've pushed fix to `develop` branch, you can also test on https://try.gogs.io

**Comment by Unknwon** [comment]
Close as fixed.
