### ISSUE TITLE
Add VOLUME to Dockerfile

### ISSUE THREAD

**Issue by freemountain** [gogits/gogs#1708]
Please add ```VOLUME /data``` into the Dockerfile.
So you could use ```--volumes-from``` to link containers.

Thank you in advance

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think this is basically same as https://github.com/gogits/gogs/issues/1631 and please read the docs here: https://github.com/gogits/gogs/tree/master/docker

**Comment by freemountain** [comment]
Thank your for the quick response.
I read the docs but i didnt see the other issue.
The docs describe how to mount a host directory as a data volume.
This is possible but i think using data volume containers is a better (and more 'dockerish') approach.
Adding ```VOLUME /data``` doesent prevent someone from adding other volumes using the ```-v```flag.

**Comment by Unknwon** [comment]
> Adding VOLUME /data doesent prevent someone from adding other volumes using the -vflag.

But why would you need two volumes for same purpose, as explained in #1631, the Dockerfile tries to leave open choices for volume.

**Comment by freemountain** [comment]
I just wanted to clarify, that even if you add the volume directive to the dockerfile, you leave open choices for volumes.
It is a way to tell docker where you need persistence in your container, so you could use ```--volumes-from```like this:
```
run --name gogs-data --entrypoint /bin/true gogs/gogs 
run --name=gogs --volumes-from gogs-data gogs/gogs
```

**Comment by Unknwon** [comment]
Thanks your explanation! 

I'm kind of confused by dockerfile command `VOLUME /data`, what does it supposed to mean? Does it only for giving the ability to mount to another data container?

**Comment by freemountain** [comment]
http://container-solutions.com/understanding-volumes-docker:
>In order to understand what a Docker volume is, we first need to be clear about how the filesystem normally works in Docker. Docker images are stored as series of read-only layers. When we start a container, Docker takes the read-only image and adds a read-write layer on top. If the running container modifies an existing file, the file is copied out of the underlying read-only layer and into the top-most read-write layer where the changes are applied. The version in the read-write layer hides the underlying file, but does not destroy it — it still exists in the underlying image. When a Docker container is deleted, relaunching the image will start a fresh container without any of the changes made in the previously running container — those changes are lost. Docker calls this combination of read-only layers with a read-write layer on top a Union File System.

https://docs.docker.com/reference/builder/#volume:
> The VOLUME instruction creates a mount point with the specified name and marks it as holding externally mounted volumes from native host or other containers.

Adding ```VOLUME /data```ist the same as using ```docker run -v /data ...```. It tells docker to bybass the Union File System for /data.

I hope this helps, if not, feel free to ask me again

**Comment by Unknwon** [comment]
Thank you, very helpful!

So there should add this line `VOLUME /data` in the Dockerfile?

**Comment by freemountain** [comment]
That would be cool.
But i think you should also add this to the docs:
```
# Create data container
docker run --name=gogs-data --entrypoint /bin/true gogs/gogs
# Use `docker run` for the first time.
docker run --name=gogs --volumes-from gogs-data -p 10022:22 -p 10080:3000 gogs/gogs
# Use `docker start` if you have stopped it.
$ docker start gogs 
```
But this make it harder to change the config files or the ssh keys...

**Comment by Unknwon** [comment]
> But this makes it harder to change the config files or the ssh keys...

If it's harder, why need add this though?

**Comment by freemountain** [comment]
Good point.
If you add ```VOLUME /data```to the dockerfile you have two options handling persistent data:
Method one:
```
# Create data container
docker run --name=gogs-data --entrypoint /bin/true gogs/gogs
# Use `docker run` for the first time.
docker run --name=gogs --volumes-from gogs-data -p 10022:22 -p 10080:3000 gogs/gogs
```
Method two (the old one):
```
# Create local directory for volume.
$ mkdir -p /var/gogs
# Use `docker run` for the first time.
$ docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```
You should add VOLUME into the Dockerfile, becaue both methods work now but I dont knwo which method should be mentioned in the docs.
Method one prevents permission issues, will work with remote docker hosts and is the recommended one (IMHO). The fact that the config files and keys are hidden is a Limitation.

**Comment by Unknwon** [comment]
Thanks for explanation!

So if people who choose to use methods two, there is nothing different after I add line VOLUME, right?

I can put both docs in the README and explain to them they are free to choose one of them.

**Comment by freemountain** [comment]
Yes, you are right.

BTW, gogs is great :thumbsup:

**Comment by Unknwon** [comment]
Just an update that `VOLUME` line has been added, but docs not not yet. You can test with it and leave feedback here. :smiley:

**Comment by Unknwon** [comment]
Update docs see: https://github.com/gogits/gogs/blob/e34d0063c3e47ad71c94ea49142fd006cb29754b/docker/README.md#volume-with-data-container

**Comment by Unknwon** [comment]
Close as fixed.
