### ISSUE TITLE
HTML isn't being encoded on issue commenting

### ISSUE THREAD

**Issue by ChubbyNinja** [gogits/gogs#1709]
Loving gogs - I've been using it for a little while, but one thing I've noticed is when commenting on issues, if I for instance type:

A random &lt;/div&gt; tag was causing the issue.

It breaks the rest of the issue page layout, because I forgot to use backticks `</div>`

Is this expected behaviour or should it be encoding HTML?

Using: Version: 0.6.9.0903 Beta with Go 1.5

**Comment by Unknwon** [comment]
Thanks your feedback!

> It breaks the rest of the issue page layout, because I forgot to use backticks </div>
Is this expected behaviour or should it be encoding HTML?

Yes it is expected, markdown render in Gogs does not tend to fix your "bad HTML" because it just makes things a lot complicated, how does Gogs know you're intended or just a mistake?

**Comment by ChubbyNinja** [comment]
Sure i understand that - perhaps encoding tags is a good idea though - as I suppose there is the more malicious side of this too - `<script>window.location...` etc

**Comment by Unknwon** [comment]
> as I suppose there is the more malicious side of this too - <script>window.location... etc

Gogs handles it. :wink:

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
