### ISSUE TITLE
merge pull request results in error 500

### ISSUE THREAD

**Issue by qsodev** [gogits/gogs#1711]
trying to merge a pull request results in error 500.  
reproducible in archlinux arm (armv7h cubietruck) with all 3 packages from aur ( gogs, gogs-git and gogs-git-dev )

git version 2.5.3
gogs-git-dev version 0.6.15.0926 Beta, but also with gogs package and gogs-git package

## scenario
* clean install using sqlite, changed url to get correct lan accessable clone urls
* creating user A and B
* create a repository with user A
* fork repository with user B
* clone user B's repo locally and add a new file, commit and push changes
* create pull request
* try to merge pull request with user A
=> Error 500

gogs.log shows:
[...routers/repo/pull.go:379 MergePullRequest()] [E] GetPullRequestByPullID: git clone: fatal: could not create leading directories of 'data/tmp/repos/491717577.git': Permission denied

**Comment by qsodev** [comment]
after some investigation it seems that there is a problem with "tmpBasePath" in function Merge in issue.go

Adding "/tmp" fixes the issue but is not a solution:

```
diff --git a/models/issue.go b/models/issue.go
index 2bc25da..8292129 100644
--- a/models/issue.go
+++ b/models/issue.go
@@ -995,7 +995,7 @@ func (pr *PullRequest) Merge(doer *User, baseGitRepo *git.Repository) (err error
        }
 
        // Clone base repo.
-       tmpBasePath := path.Join("data/tmp/repos", com.ToStr(time.Now().Nanosecond())+".git")
+        tmpBasePath := path.Join("/tmp/data/tmp/repos", com.ToStr(time.Now().Nanosecond())+".git")
        os.MkdirAll(path.Dir(tmpBasePath), os.ModePerm)
        defer os.RemoveAll(path.Dir(tmpBasePath))
```

A gogs go expert could possible fix this correctly very easy :)

**Comment by sapk** [comment]
I think it could be more a problem of permission in the folder data where all the data of the gogs instance are stored. Because if you use the absolute path /tmp you use the temporary folder of your distrib (not really a problem but ...) it's accesible bay all the user by default. This why your fix work but it's not the solution because, I think it will not work on windows so it break portability.

Simply try to make the user you sue for lanching gogs the owner of the data folder. ;-)

**Comment by qsodev** [comment]
i tried that but this does not work! E.g. attachements work fine. They are also stored in /srv/gogs/data/attachements folder.  
Even if I create /srv/gogs/data/tmp and chown it to the user it does not work.  
It seems more that the prefix is missing here in the basepath variable.  
I think it should be something like "GOGS_ROOT_PATH" + /data/tmp

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
**Important update** 

I've pushed code to `develop` branch and https://try.gogs.io that check if pull request has conflict with upstream every time fork repository or upstream repository is pushed, so conflict will be detected correspondingly right now.

Leave feedback here so I can help with further problems you may encounter! :beers:

**Comment by qsodev** [comment]
I just found out that the working directory is possibly not set correctly in systemd gogs init script.
It points to /usr/share/gogs but the gogs' repo and data files are located in /srv/gogs.

Changing /usr/share/gogs to /srv/gogs fixes the merge issue for the arch linux aur package.

But anyway I think it would be better if tmpBasePath := path.Join("data/tmp/repos"... ( now located in pull.go) is an absolute instead of a relative path.

**Comment by Unknwon** [comment]
>  absolute instead of a relative path.

absolute path is a thing sounds easy but very hard to do. How do you determine what absolute path you use in first option that works on all operating system without configuration?

**Comment by qsodev** [comment]
Since this folder is needed only during merging pull request it could be in temporary folder. 
I think there is something like os.TempDir() 
Would this be a configuration free os independent solution?

**Comment by Unknwon** [comment]
It used to be system temp directory but had somewhat permission issues too. And the "data" directory is required anyway in current releases for some purposes, so I think it would be fine just keep it there and being able to change it in the future. Also makes debug much more easier.

**Comment by Unknwon** [comment]
Hmm.. let's focus on the issue itself first, does 500 still presents?

**Comment by qsodev** [comment]
With the old systemd working directory set to "/usr/share/gogs" i just get an empty page instead of 500. When I reload the page I get "not found".
When the working dir set to "/srv/gogs" I do not get 500 anymore.

**Comment by qsodev** [comment]
Update: changing working directory to "/srv/gogs" works only in master branch!
current develop branch always gives a blank page regardless of working directory or absolute tmpPath patch.

**Comment by Unknwon** [comment]
I have no idea what you're saying...

**Comment by qsodev** [comment]
The gogs packages in aur are changed now. The working directory of gogs systemd service is set to "/srv/gogs/". When I install gogs-git (master branch) then everything is working fine. 
But gogs-git-dev (develop branch) is not working: When trying to merge a pull request I get an empty page now. It does not contain any html code and no log entry is created. It seems that gogs does not even try to merge the pull request.

**Comment by Unknwon** [comment]
> I get an empty page now. It does not contain any html code and no log entry is created

What is the page response code and which log file did you check?

**Comment by qsodev** [comment]
it is a completely empty html page (url: localhost:3000/username/reponame/pulls/2/merge) with no html code when i view page source. gogs.log shows no error this time. http.log is empty. Only xorm.log shows:
```
[xorm] [info]  2015/10/25 22:16:33.769939 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [1]
[xorm] [info]  2015/10/25 22:16:33.770874 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [1]
[xorm] [info]  2015/10/25 22:16:33.771425 [sql] SELECT `id`, `owner_id`, `lower_name`, `name`, `description`, `website`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_bare`, `is_mirror`, `is_fork`, `fork_id`, `created`, `updated` FROM `repository` WHERE `owner_id` = ? AND `lower_name` = ? LIMIT 1 [args] [1 testing]
[xorm] [info]  2015/10/25 22:16:33.771876 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [1]
[xorm] [info]  2015/10/25 22:16:33.777887 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [1 1]
[xorm] [info]  2015/10/25 22:16:33.778178 [sql] SELECT `id`, `uid`, `repo_id` FROM `star` WHERE `uid` = ? AND `repo_id` = ? LIMIT 1 [args] [1 1]
[xorm] [info]  2015/10/25 22:16:33.787043 [sql] SELECT `id`, `repo_id`, `index`, `name`, `poster_id`, `milestone_id`, `assignee_id`, `is_pull`, `is_closed`, `content`, `priority`, `num_comments`, `deadline`, `created`, `updated` FROM `issue` WHERE `repo_id` = ? AND `index` = ? LIMIT 1 [args] [1 2]
[xorm] [info]  2015/10/25 22:16:33.787626 [sql] SELECT `id`, `uuid`, `issue_id`, `comment_id`, `release_id`, `name`, `created` FROM `attachment` WHERE issue_id=? AND comment_id=0 [args] [2]
[xorm] [info]  2015/10/25 22:16:33.787822 [sql] SELECT `id`, `type`, `poster_id`, `issue_id`, `commit_id`, `line`, `content`, `created`, `commit_sha` FROM `comment` WHERE issue_id=? ORDER BY `created` ASC [args] [2]
[xorm] [info]  2015/10/25 22:16:33.788134 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/10/25 22:16:33.788769 [sql] SELECT `id`, `type`, `status`, `issue_id`, `index`, `head_repo_id`, `base_repo_id`, `head_user_name`, `head_branch`, `base_branch`, `merge_base`, `has_merged`, `merged_commit_id`, `merged`, `merger_id` FROM `pull_request` WHERE `issue_id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/10/25 22:16:33.789226 [sql] SELECT `id`, `owner_id`, `lower_name`, `name`, `description`, `website`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_bare`, `is_mirror`, `is_fork`, `fork_id`, `created`, `updated` FROM `repository` WHERE `id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/10/25 22:16:33.789675 [sql] UPDATE `issue_user` SET is_read=? WHERE uid=? AND issue_id=? [args] [true 1 2]
[xorm] [debug] 2015/10/25 22:16:33.836147 [time] UPDATE `issue_user` SET is_read=? WHERE uid=? AND issue_id=? - args [true 1 2] - execution took: 46421608ns
[xorm] [info]  2015/10/25 22:16:33.836341 [sql] SELECT `id`, `type`, `status`, `issue_id`, `index`, `head_repo_id`, `base_repo_id`, `head_user_name`, `head_branch`, `base_branch`, `merge_base`, `has_merged`, `merged_commit_id`, `merged`, `merger_id` FROM `pull_request` WHERE `issue_id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/10/25 22:16:33.837211 [sql] BEGIN TRANSACTION
[xorm] [info]  2015/10/25 22:16:33.837322 [sql] UPDATE `issue` SET `is_closed` = ?, `updated` = ? WHERE `id` = ? [args] [true 2015-10-25 22:16:33 2]
[xorm] [debug] 2015/10/25 22:16:33.837580 [time] UPDATE `issue` SET `is_closed` = ?, `updated` = ? WHERE `id` = ? - args [true 2015-10-25 22:16:33 2] - execution took: 219344ns
[xorm] [info]  2015/10/25 22:16:33.837620 [sql] UPDATE `issue_user` SET is_closed=? WHERE issue_id=? [args] [true 2]
[xorm] [debug] 2015/10/25 22:16:33.837766 [time] UPDATE `issue_user` SET is_closed=? WHERE issue_id=? - args [true 2] - execution took: 120917ns
[xorm] [info]  2015/10/25 22:16:33.837838 [sql] SELECT `id`, `issue_id`, `label_id` FROM `issue_label` WHERE issue_id=? ORDER BY `label_id` ASC [args] [2]
[xorm] [info]  2015/10/25 22:16:33.838038 [sql] INSERT INTO `comment` (`type`, `poster_id`, `issue_id`, `commit_id`, `line`, `content`, `created`, `commit_sha`) VALUES (?, ?, ?, ?, ?, ?, ?, ?) [args] [2 1 2 0 0  2015-10-25 22:16:33 ]
[xorm] [debug] 2015/10/25 22:16:33.838254 [time] INSERT INTO `comment` (`type`, `poster_id`, `issue_id`, `commit_id`, `line`, `content`, `created`, `commit_sha`) VALUES (?, ?, ?, ?, ?, ?, ?, ?) - args [2 1 2 0 0  2015-10-25 22:16:33 ] - execution took: 177057ns
[xorm] [info]  2015/10/25 22:16:33.838295 [sql] UPDATE `repository` SET num_closed_pulls=num_closed_pulls+1 WHERE id=? [args] [1]
[xorm] [debug] 2015/10/25 22:16:33.838429 [time] UPDATE `repository` SET num_closed_pulls=num_closed_pulls+1 WHERE id=? - args [1] - execution took: 111061ns
[xorm] [info]  2015/10/25 22:16:33.838585 [sql] SELECT `id`, `owner_id`, `lower_name`, `name`, `description`, `website`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_bare`, `is_mirror`, `is_fork`, `fork_id`, `created`, `updated` FROM `repository` WHERE `id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/10/25 22:16:33.838815 [sql] ROLL BACK
```

**Comment by Unknwon** [comment]
> [xorm] [info]  2015/10/25 22:16:33.838815 [sql] ROLL BACK

If XORM rolls back there must be an error log...

**Comment by Unknwon** [comment]
Can you reproduce it on https://try.gogs.io ?

**Comment by Unknwon** [comment]
I indicated a SQLite3-specific session issue in `develop` branch, please update and help test!

**Comment by qsodev** [comment]
It is working fine now! Thanks!

**Comment by Unknwon** [comment]
:trollface: my tears are falling down...

**Comment by Unknwon** [comment]
Close as fixed.
