### ISSUE TITLE
syntax highlight ?

### ISSUE THREAD

**Issue by matrixise** [gogits/gogs#1712]
Hi all,

when Gogs shows the content of a file, there is no syntax highlighting. Is there a reason ?

Thanks.

**Comment by Unknwon** [comment]
Currently Gogs uses Google code prettify which is very... poor on highlighting somehow.

We're going to use highlightjs in the new theme.

**Comment by ChangePlaces** [comment]
As long as it's light and fast, then all's good :)

**Comment by matrixise** [comment]
highlight.js is great, I use it for a presentation, very fast.

**Comment by ChangePlaces** [comment]
what version is the 'new theme' going to come in on? I find gitlab's "new theme" to be unusable to the point of risibility!

**Comment by matrixise** [comment]
I don't know, I use the version 8.8.0

**Comment by BurakDev** [comment]
Just clone GitHub theme :(

**Comment by Unknwon** [comment]
Hopefully, new theme could come at the end of this year. :trollface:

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/gogs/gogs

**Comment by Unknwon** [comment]
Close as fixed.
