### ISSUE TITLE
panic: fail to set message file(fr-CA): open conf/locale/locale_fr-CA.ini: no such file or directory

### ISSUE THREAD

**Issue by guotie** [gogits/gogs#1713]
build from source.

[root@host-80 gogs]# ./gogs web
2015/09/29 15:07:46 [T] Custom path: /root/go/src/github.com/gogits/gogs/custom
2015/09/29 15:07:46 [T] Log path: /root/go/src/github.com/gogits/gogs/log
2015/09/29 15:07:46 [I] Gogs: Go Git Service 0.6.15.0926 Beta
2015/09/29 15:07:46 [I] Log Mode: File(Trace)
2015/09/29 15:07:46 [I] Cache Service Enabled
2015/09/29 15:07:46 [I] Session Service Enabled
2015/09/29 15:07:46 [I] Run Mode: Production
2015/09/29 15:07:46 [T] Doing: CheckRepoStats
panic: fail to set message file(fr-CA): open conf/locale/locale_fr-CA.ini: no such file or directory

goroutine 1 [running]:
github.com/macaron-contrib/i18n.initLocales(0xc8202bdd93, 0x0, 0xe30350, 0xb, 0xc820669740, 0xc8206542c0, 0x36, 0xc8202a0b60, 0x7, 0x7, ...)
        /root/go/src/github.com/macaron-contrib/i18n/i18n.go:54 +0x781
github.com/macaron-contrib/i18n.I18n(0xc820352580, 0x1, 0x1, 0x0, 0x0)
        /root/go/src/github.com/macaron-contrib/i18n/i18n.go:151 +0xd0
github.com/gogits/gogs/cmd.newMacaron(0xc8201ae1e0)
        /root/go/src/github.com/gogits/gogs/cmd/web.go:145 +0xc22
github.com/gogits/gogs/cmd.runWeb(0xc8201ae1e0)
        /root/go/src/github.com/gogits/gogs/cmd/web.go:180 +0xc2
github.com/codegangsta/cli.Command.Run(0xe19b08, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe9b650, 0x15, 0xf447e0, ...)
        /root/go/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc82022bc00, 0xc820084000, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
        /root/go/src/github.com/gogits/gogs/gogs.go:40 +0x35c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc82006fc00)
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 22 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc8202d1d80)
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 38 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820408540)
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 37 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
        /root/go/src/github.com/gogits/gogs/models/webhook.go:576 +0x52a
created by github.com/gogits/gogs/models.InitDeliverHooks
        /root/go/src/github.com/gogits/gogs/models/webhook.go:594 +0x2b

goroutine 36 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc820268a40)
        /root/go/src/github.com/gogits/gogs/modules/cron/cron.go:161 +0x9e8
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /root/go/src/github.com/gogits/gogs/modules/cron/cron.go:136 +0x40

goroutine 34 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8203305a0)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336

**Comment by Unknwon** [comment]
Thanks your feedback!

Try remove the `[i18n]` section in your custom app.ini file.

**Comment by guotie** [comment]
是conf/locale目录下没有locale_fr-CA.ini文件导致，

    cp locale_fr-FR.ini locale_fr-CA.ini

解决了。

**Comment by Unknwon** [comment]
Based on the log you provide, the Gogs 0.6.15 no longer uses name `fr-CA` but `fr-FR`, and it has all locale files store within Go code file in gzip format.

But, anyway. Have your problem been solved?

**Comment by guotie** [comment]
solved.

**Comment by Unknwon** [comment]
Thanks your confirmation!

**Comment by AndreaGiardini** [comment]
Hi

I had the same problem with my installation. Gogs didn't start, nothing in `service gogs status` or `/var/log/gogs/gogs.log`. I had to look in `/var/log/messagges` to find this error (which is not visible at all in my opinion). Should we replace `fr-CA` with `fr-FR` ? I can send a PR if you want

**Comment by AndreaGiardini** [comment]
Sorry, i've just seen that it's already fixed. But not yet updated in the puppet module that i'm using :)

Thanks for the great job!

**Comment by Unknwon** [comment]
@AndreaGiardini :trollface:
