### ISSUE TITLE
adding repository to team fails

### ISSUE THREAD

**Issue by arnehormann** [gogits/gogs#1714]
Hi, I can't add a repo to a team, I'm getting a 500 error and this log entry:
```
2015/09/29 09:00:45 [...routers/org/teams.go:141 TeamsRepoAction()] [E] Action(add): 'developers' watchRepo: UNIQUE constraint failed: watch.user_id, watch.repo_id
2015/09/29 09:00:45 [...routers/org/teams.go:142 TeamsRepoAction()] [E] TeamsRepoAction: watchRepo: UNIQUE constraint failed: watch.user_id, watch.repo_id
```
The Team view doesn't show any associated repos (neither before nor after) and my coworker can't push. It's the second team for this organization, so maybe there's something wrong with the unique constraints?

System details:
Gogs 0.6.9 (binary install, using embedded sqlite), Git 2.1.4, inside a Debian Jessie based Docker container

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your database?

**Comment by arnehormann** [comment]
the embedded sqlite

**Comment by Unknwon** [comment]
Oops sorry... Didnt notice you posted at original comment

**Comment by Unknwon** [comment]
Actually, can you try v0.6.15 again?

**Comment by arnehormann** [comment]
Same error with `0.6.15.0926 Beta`... only the timestamp changes

**Comment by Unknwon** [comment]
@arnehormann OK thanks!

**Comment by Unknwon** [comment]
I think I've found the problem, and pushed a fix to `develop` branch, can you help test again?

**Comment by arnehormann** [comment]
@Unknwon yeah, of course.
I'll need a while, the whole container creation is scripted and I'm using the binary distribution download link, not the installation from source. You got that stuff set up already, can you give me a link to another zip (or tar)?
If you can, I can provide an answer in about 30 minutes, otherwise it'll probably be tomorrow :grinning:

**Comment by Unknwon** [comment]
Of course, what is your system ?

**Comment by arnehormann** [comment]
linux 64 bit (docker container based on debian jessie)

**Comment by Unknwon** [comment]
If you're using container.... Just pull develop tag from Docker Hub.

**Comment by arnehormann** [comment]
Not the docker hub one, another container; I built it myself before Gogs first got one.

I wanted to chime in on the Docker-PR, but I lacked the time to clean ours up; I'm trying rather hard to conform to the [12 factor model](12factor.net). That's very, very different to how the current container works. I'm also messing around with hostkeys, the website and all container-internal state. But to fit it to our data layout, I have to start from the binary distribution.

Ours is built by creating `/dev/null` symlinks for xorm.log and http.log to disable file logging, adding hostkeys from a tar-file on startup (so they are preserved when I'm switching containers), creating all config files based on environment variables in a generated `start.sh` (which includes completely silencing sshd and redirecting gogs-logging to console), starting sshd in there and finishing it with `exec gogs web`. At the end, I'm running gogs with the website, configuration and all repositories in host directories (or volumes) and all configuration created on startup. I'm also able to start the whole thing with `docker run --rm` because the container has no persistent state any more.
But I'm making some assumptions about the host directory structure and the ports used, so the resulting container is not applicable everywhere.

**Comment by tboerger** [comment]
So it's nearly like my container for gitea :D I will build one for gogs as well. https://github.com/dockhippie/gitea

**Comment by Unknwon** [comment]
@arnehormann OK... let's wait until tomorrow...

**Comment by arnehormann** [comment]
@Unknwon ok, thanks!

**Comment by arnehormann** [comment]
@Unknwon works now! Thanks!
Should I discuss or even try to submit some of my Docker stuff in another issue?

**Comment by Unknwon** [comment]
@arnehormann no, it's actually a bug/feature with go-sqlite3 driver, so needs special handle.
