### ISSUE TITLE
Settings button shown to normal user if repo is empty

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1715]
1. User A created a public repo AP;
2. User A did not add user B as a member;
3. user A did not push any commit to AP;
2. User B can see the settings button on the top right corner of the page.

**Comment by Unknwon** [comment]
Thanks your feedback!

Just to confirm that user B will get 404 if he clicks on the settings button?

**Comment by JokerQyou** [comment]
Yes he will get a 404 page if he click on that button.

**Comment by Unknwon** [comment]
Thanks your info!

**Comment by Unknwon** [comment]
Please test on https://try.gogs.io/unknwon/bare again!

**Comment by Unknwon** [comment]
Close as fixed.
