### ISSUE TITLE
provide tar based images for linux

### ISSUE THREAD

**Issue by arnehormann** [gogits/gogs#1716]
Hi, I'm trying to use gogs in a docker container.
The base distro I use (debian jessie) doesn't contain unzip, so I have to install it.
If you were to provide tar files, I could get rid of that step.

Thanks!

**Comment by Unknwon** [comment]
Thanks! Will do next time!

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/releases/tag/v0.7.0
