### ISSUE TITLE
Gogs docker don't support ED25519 keys

### ISSUE THREAD

**Issue by ogarcia** [gogits/gogs#1717]
If you try to add an ed25519 user ssh key the web responds:
> Sorry, we're not able to verify your SSH key: ssh-keygen -l -f: line 1 too long: ssh-ed25519 AAAAC3NsdaP5lJHI1NTA5BBBBIHSi...

Could be cause a very old SSH server?

**Comment by Fastidious** [comment]
Duplicate of #1313.

**Comment by ogarcia** [comment]
I not sure if is a dupicate of #1313, probably this error is caused by old version of ssh server into docker.

**Comment by Unknwon** [comment]
Please checkout new Docker images.

**Comment by Unknwon** [comment]
Any updates on this?

**Comment by ogarcia** [comment]
Is closed. With the new containers it works like a charm.

**Comment by Unknwon** [comment]
Thanks your confirmation!
