### ISSUE TITLE
smaller code fontsize (feature request)

### ISSUE THREAD

**Issue by initbar** [gogits/gogs#1720]
Can the code font size be set to GitHub level font size? For example:

![github](https://cloud.githubusercontent.com/assets/12630151/10183593/70c1c1b4-66ff-11e5-8467-17742b27b45b.png)

Currently, GitHub code font is set around `12px` (above). However, the current Gogs uses `1em` (which is slightly too bulky and big (below).

![before](https://cloud.githubusercontent.com/assets/12630151/10183594/70c2ac0a-66ff-11e5-8d73-6afd20ef9fbb.png)

If the font size is set to static `12px`, then our code looks more compact and GitHub - and BitBucket - like (which is what my eyes are used to).

![after](https://cloud.githubusercontent.com/assets/12630151/10183592/7091e8fe-66ff-11e5-854a-5024674157d1.png)

**Comment by Unknwon** [comment]
Thanks your feedback!
