### ISSUE TITLE
Commits with many files make gogs timeout

### ISSUE THREAD

**Issue by karasz** [gogits/gogs#1723]
Here is an example:
https://try.gogs.io/karasz/package/commit/b00f14379fb4e718ae37697a0604f75e65656bca

That commit touches 1485 files

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Should have been fixed with 0.8.10 release.

**Comment by Dasoren** [comment]
@Unknwon Just to make sure I understand this. You made it so that if this diff is to big gogs will just stop trying and not show any diff info, correct?

**Comment by Unknwon** [comment]
@Dasoren currently yes, another issue suggests to show changed file list.

**Comment by SoftCreatR** [comment]
FYI: I'm currently experiencing the same issue using the latest release.
