### ISSUE TITLE
Binary download unavailable

### ISSUE THREAD

**Issue by steronydh** [gogits/gogs#1724]
The binary download page returns a 404 error:

http://gogs.io/docs/installation/install_from_binary.html

**Comment by manfer** [comment]
http://gogs.io/docs/installation/install_from_binary

without .html

**Comment by manfer** [comment]
Some links in the docs are broken. The correct one for that one is:
http://gogs.io/docs/installation/install_from_binary

**Comment by steronydh** [comment]
Great, thanks!

**Comment by Unknwon** [comment]
Oops, sorry about that. 

Should we still support arbitrary extension or simply result 404?

**Comment by delucks** [comment]
There's also 404 for other documentation pages- for example [the "Configuration and Run" page](http://gogs.io/docs/installation/configuration_and_run.md).

**Comment by Unknwon** [comment]
@delucks just remove all extensions like ".md" and ".html" should work.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
