### ISSUE TITLE
Spelling Issue :c

### ISSUE THREAD

**Issue by nxxv0** [gogits/gogs#1726]
Bug Description:
The plural form of repository is repositories, isn't it?
http://puu.sh/kvfn3/8a854464e3.png

Gogs Version:
0.6.15.0926 Beta

Greetings

Navo

**Comment by linquize** [comment]
locale_de-DE.ini

**Comment by manfer** [comment]
In english it is `repositories` but considering that image shows gogs in a language that is not english but Deutch then should be a german who clarifies if it is a wrong string or not.

If you are german and you think that translation is a bug then go to https://crowdin.com/project/gogs to suggest another translation.

**Comment by Unknwon** [comment]
Thanks your feedback!

And mentioned by @manfer , you can correct it at https://crowdin.com/translate/gogs/1/enus-de#q=explore%3Arepos

**Comment by nxxv0** [comment]
I suggested some translations, there were many spelling mistakes. Take a look :)

**Comment by Unknwon** [comment]
@nxxv0 thanks! I've approved those.

**Comment by Unknwon** [comment]
BTW, I've gave you approve/disapprove permission so you can fix them in the future without my help.

**Comment by nxxv0** [comment]
Ok, nice :+1:

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by veluria** [comment]
Repositories is *not* the correct German spelling. Repositorys is correct. That goes for all plurals of English words in German: Partys, Babys, etc. 

§ 21 of the German spelling:
>Fremdwörter aus dem Englischen, die auf -y enden und im Eng-
lischen den Plural -ies haben, erhalten im Plural ein -s.

**Comment by nxxv0** [comment]
> Repositories is not the correct German spelling. Repositorys is correct. That goes for all plurals of English words in German: Partys, Babys, etc.

Hmm ok, for me Repositorys sounds really strange :/

> The German translation could seriously use some work, though. I especially dislike the usage of ‘Du’ instead of ‘Sie’.

I agree.

**Comment by tboerger** [comment]
Sorry but for me as a german repositorys sounds totally wrong oO

**Comment by tboerger** [comment]
And on top of that I would prefer Du instead of Sie.

**Comment by nxxv0** [comment]
> Sorry but for me as a german repositorys sounds totally wrong oO

For me too, but it seems to be right. It's the new spelling ("Neue deutsche Rechtschreibung") :wink: 

> And on top of that I would prefer Du instead of Sie.

I used both in the translation of Gogs.
In my opinion sometimes "Du" sounds better and sometimes "Sie". :confused:

**Comment by tboerger** [comment]
I am oldschool... I don't like the new german spelping ;) Damn, I'm getting old...
