### ISSUE TITLE
Add custom link support in commit message

### ISSUE THREAD

**Issue by beowulf13th** [gogits/gogs#1737]
I write regex with some #PREFIX-ID and it changes on to my youtrack URL. Like in bitbucket.
I think it will be really useful functionality.

Thanks

**Comment by Unknwon** [comment]
Indeed, so to be clear.

Are you suggesting a custom link format?

For example, default is `#11` -> `/:username/:reponame/issues/11`.

And you want to `#11` -> `/:custom/11`?

**Comment by beowulf13th** [comment]
@Unknwon 

I don't know what "/:" mean :) But I think it something what I meant.
I push commit with comment:

"TT-11 some issue title 
- did something
- did something else
<...>
"

And when I open commit information in gogs I want to have opportunity change "TT-11" on custom url. For example

(TT\-[0-9]+) -> http://domain.com/some_tracker_system/issue-$1

**Comment by Unknwon** [comment]
So are you completely using a external issue tracker or you use both Gogs one and the you track?

**Comment by beowulf13th** [comment]
@Unknwon 
Yes, I use Youtrack for issues.

**Comment by Unknwon** [comment]
OK, it's more general now, which is good!

You can search "external issue tracker" and you will find out this one is duplicated. 😜

**Comment by beowulf13th** [comment]
@Unknwon
Whoops, sorry :) I found #890 now. Thanks.
Will it be implemented?

**Comment by Unknwon** [comment]
Yes will be. But may not as fast as you expect.... If you can't wait... You can hack Gogs...

**Comment by beowulf13th** [comment]
Sorry, I cannot do it :) 
I don't know Go :) I think it not very hard, but I really have no time for one more programming language :D

**Comment by Unknwon** [comment]
😀 It's OK.
