### ISSUE TITLE
UI style differs in different parts of service

### ISSUE THREAD

**Issue by cynthia** [gogits/gogs#1740]
After upgrading to 0.6.15.0926, I noticed that there are two UI styles which are inconsistent around different parts of the service.

It seems like certain parts use /ng/css/gogs.css (e.g. home) and certain parts use /css/gogs.min.css (e.g. diff view) - which looks extremely weird.

**Comment by tboerger** [comment]
That's expected. The UI get's migrated to a totally new theme and as you can currently see not all parts are migrated yet.

**Comment by cynthia** [comment]
Wow, really? I'd imagine a rollout like this to happen in one go.

**Comment by tboerger** [comment]
The resources are limited so it's not done in a single go ;)

**Comment by Unknwon** [comment]
Thanks your feedback!

But it is duplicated to https://github.com/gogits/gogs/issues/650
