### ISSUE TITLE
Update default branch in git repository while change in web view

### ISSUE THREAD

**Issue by soul9** [gogits/gogs#1742]
when I set a branch to be the default, I would like gogs to set it on the git repository as well. The command for this, in a bare repository, is:
git symbolic-ref HEAD refs/heads/mynewdefaultbranch

I am using gogs develop branch, on commit 215920772ab8d84418e982ee1de8986f911fe3c1 , git version 2.1.4 , on ubuntu, but I'm pretty sure this is irrelevant.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
You can now test it on `develop` and https://try.gogs.io

**Comment by Unknwon** [comment]
Close as implemented.
