### ISSUE TITLE
Private repositories under organization

### ISSUE THREAD

**Issue by aaronseng** [gogits/gogs#1744]
I have an organization under my account which is created by me and subscribed by two other users. When I create a new repository under that organization as "private" other users able to see that repository under repository browser in Organization but when they click to repository none of them able to see content of repository. They're getting 404 error. IS that missing feature or kinda bug ?

 Using latest gogs installed from binary. Using sqlite as database.

**Comment by aaronseng** [comment]
Adding those users to team under organization solves to issue. Somehow we expected to default behavior of joining an Organization should give those users to read permission.

**Comment by Unknwon** [comment]
:sweat_smile:
