### ISSUE TITLE
Can't close/reopen issue with team has admin access

### ISSUE THREAD

**Issue by mauricemeyer** [gogits/gogs#1748]
I found a strange behavior I consider to be a bug: I can't close issues I didn't create.
I am member of a team with admin access to the repository. 

The repository owner can always close an issue, regardless of who created it and to whom it is assigned.

The close button is always displayed to me and I can click it, but it apparently does have no effect clicking it. The same applies to the reopen button for closed issues

#### I can close/reopen the issue if
I created it. If the issue is assigned to anyone else than me, they can't close/reopen the issue (even when they have admin rights).
Neither can any other admin (besides the repo owner) close/reopen the issue.

#### I can't close/reopen the issue if
I didn't create it. It doesn't matter if it is assigned to me or not.

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
Hi there, I've pushed fix to `develop` branch, you can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Close as fixed.
