### ISSUE TITLE
Stale repos on reinstall

### ISSUE THREAD

**Issue by drahnr** [gogits/gogs#1749]
On a reinstall, with existing db items but an empty fs (use a docker container, keep the tables in a mysql docker container but reset the gogs container) gogs does not allow to delete those repos but results in a 500 internal server error. Which is not exactly helpful.

**Comment by drahnr** [comment]
True, but I would still expect to wipe the projects from the database via an UI button. But that is not the case. I am stuck with unusable ghose repos.

**Comment by Unknwon** [comment]
OK, but currently you would have to hack on database directly. :flushed:

**Comment by Unknwon** [comment]
I think it is possible since 0.8 release.

1. Remove repositories that are missing files.
2. Delete from admin - repository panel.
