### ISSUE TITLE
Error when trying to clone

### ISSUE THREAD

**Issue by peterbrinck** [gogits/gogs#1751]
Hi!

I've installed Gogs with the Packager package
And I've finally got it to work!

But now, I can't clone...
I get this error:
`gnutls_handshake() failed: An unexpected TLS packet was received.`

And if I access the page with SSL/HTTPS, then I get Secure Connection Failed

I'm not quite sure how to fix this
I'm using CloudFlare and Vesta to handle my DNS and SSL

**Comment by Unknwon** [comment]
Thanks your feedback!

Have you actually enabled HTTPS for Gogs?

**Comment by peterbrinck** [comment]
If I enable HTTPS from CloudFlare then Gogs doesn't work, at all

Also, I'm running Gogs on a subdomain

**Comment by Unknwon** [comment]
> If I enable HTTPS from CloudFlare then Gogs doesn't work, at all

I don't understand, so if you enabled HTTPS from CloudFlare, it sounds like a reverse proxy thing to me, and your Gogs instance should not even aware of there is a HTTPS thing.

**Comment by Unknwon** [comment]
Hmm.. I haven't had chance to use CF's HTTPS, what configuration has been changed in your Gogs for the HTTPS?

**Comment by peterbrinck** [comment]
I'm not that much into servers, SSL etc.
So maybe it's just because I'm doing something completely stupid

But last time I was running Gogs, on a different server, there was no problems
But that time I installed Gogs from source


I'm not sure what to do or what to look for?

**Comment by Unknwon** [comment]
From my understanding, I think CF's HTTPS is handled before the request is get into your server, so the actual request be sent to server is a non-HTTPS request(normal HTTP), and then Gogs should be started as if it is serving normal HTTP requests.

But I could be wrong of course.

**Comment by peterbrinck** [comment]
Okay, so now I've changed the protocol in the app.ini to HTTPS, and enabled HTTPS from CF, and now I just get infinite loading, no error, no nothing

If I keep the app.ini with HTTP, and still have HTTPS enabled from CF, I get infinite loading again

If I keep both HTTP everything, besides cloning, works


Or at least that's how it was.. Now I'm just getting infinite loading, regardless of my settings..

**Comment by Unknwon** [comment]
I think we're not going to find an answer unless we know how the CF's HTTPS works...

**Comment by Unknwon** [comment]
Based on https://www.cloudflare.com/ssl , what is the type of your SSL setup on CF?

**Comment by peterbrinck** [comment]
I'm using Full SSL, and the certificate is generated from Vesta

**Comment by Unknwon** [comment]
OK, so are you using NGINX?

**Comment by peterbrinck** [comment]
Yeah, I am, and Apache

**Comment by Unknwon** [comment]
Cool, so it's a classic reverse proxy model.

As I mentioned, you should use Apache to handle HTTPS with corresponding certificates, and proxy as normal HTTP requests to Gogs.

**Comment by peterbrinck** [comment]
Okay, I'll look into that
I'm not quite sure how it's done when Vesta in controlling things

**Comment by Unknwon** [comment]
In NGINX, I would do:

```nginx
server {
        listen 443 ssl;
        server_name try.gogs.io;
        ssl_certificate /path/to/gogs.io.unified.crt;
        ssl_certificate_key /path/to/gogs.io-decrypted.key;

        location / {
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_pass http://localhost:3000$request_uri;
        }
}
```

**Comment by peterbrinck** [comment]
Thanks for the help!
I'll try some different things out

I'll let you know what I find out!

**Comment by Unknwon** [comment]
No problem. :wink:

**Comment by peterbrinck** [comment]
@Unknwon 

I've tried changing the port to 2053, instead of the default 3000, because CloudFlare SSL doesn't support 3000, but 2053

But... Now the page won't load at all
I've changed the port in `custom/conf/app.ini`

**Comment by Unknwon** [comment]
Have you restarted?

**Comment by peterbrinck** [comment]
I've restarted Gogs, but not the server

**Comment by Unknwon** [comment]
You should check Gogs's router log see if requests are actually arrived to Gogs.

**Comment by Unknwon** [comment]
If you don't disable it, it should prints to console.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by gchan** [comment]
I encountered the same issue (unable to clone via SSH) and discovered that Cloudflare only proxies HTTP traffic as per [this article](https://support.cloudflare.com/hc/en-us/articles/200169406-How-do-I-SSH-).

If you want to use Cloudflare's reverse proxy (and their features), you define a secondary domain for SSH traffic which doesn't proxy through Cloudflare. For example you could have git.example.com for HTTP traffic and git-ssh.example.com for your SSH traffic.
