### ISSUE TITLE
每次push的时候都会超时

### ISSUE THREAD

**Issue by wiseideal** [gogits/gogs#1753]
我的系统是windows2003 网页内网外网访问没问题 我使用的http协议 没有用https或者ssh
现在每次做push的时候都会超时 我打开了router log发现我在做push时 log里一点反应没有 我用net stat -an 也看不到任何3000端口的连接 下面是我的配置文件

APP_NAME = Gogs: Go Git Service
RUN_USER = Administrator
RUN_MODE = prod

[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = 
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = C:/Documents and Settings/Administrator/gogs-repositories

[server]
PROTOCOL = http
DOMAIN = *.*.*.*
HTTP_PORT = 3000
ROOT_URL = http://*.*.*.*:3000/
DISABLE_SSH = true
SSH_PORT = 22
OFFLINE_MODE = false
DISABLE_ROUTER_LOG = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
DISABLE_REGISTRATION = true
ENABLE_CAPTCHA = false
REQUIRE_SIGNIN_VIEW = false

[picture]
DISABLE_GRAVATAR = false

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info
LOG_ROTATE = true

[security]
INSTALL_LOCK = true
SECRET_KEY = DyXG7FDtQDrrykF

**Comment by Unknwon** [comment]
> 现在每次做push的时候都会超时 我打开了router log发现我在做push时 log里一点反应没有

Can you do `git pull`?

**Comment by wiseideal** [comment]
still the same. I'll give a try under https

**Comment by Unknwon** [comment]
Please check your IIS or firewall make sure there is no authentication problem. :smiley:

**Comment by wiseideal** [comment]
finally problem solved. Replace the ip address with Domain name

**Comment by Unknwon** [comment]
Thanks your confirmation!
