### ISSUE TITLE
Missing migration for Gogs MySQL table(s)?

### ISSUE THREAD

**Issue by moritzheiber** [gogits/gogs#1754]
I just created a new repository for an organization, which I didn't do in a while. Gogs has been upgraded using packages in the meantime, without me actively running any other commands before/after the upgrades.

I'm running 0.6.1.0325 on MySQL 5.5.44, git 1.9.1 on Ubuntu 14.04.3 using the regular Ubuntu packages from packager.io.

### Error log

This happens when I try to push to the newly created repository:

```
2015/10/09 16:32:54 [...ts/gogs/cmd/serve.go:110 runServ()] [F] Failed to get repository owner(my_organization): Error 1054: Unknown column 'last_repo_visibility' in 'field list'
```

**Comment by Unknwon** [comment]
Thanks your feedback!

1. Can you post full log from start to error here?
2. Does restart Gogs help?

**Comment by moritzheiber** [comment]
@Unknwon No, it's not fixed by a restart. Also not by running `gogs update`.

What do you mean with "full log"? The only statement in the `serv.log` is the line I pasted above (repeated a couple of times, from trying multiple times), that's it. Let me know if you need the content of any of the other log files.

**Comment by Unknwon** [comment]
> No, it's not fixed by a restart. Also not by running gogs update.

`gogs update` is not for this purpose.

> 2015/10/09 16:32:54 [...ts/gogs/cmd/serve.go:110 runServ()] [F] Failed to get repository owner(my_organization): Error 1054: Unknown column 'last_repo_visibility' in 'field list'

Where did you see this?

**Comment by moritzheiber** [comment]
In `/opt/gogs/log/serv.log`.

**Comment by Unknwon** [comment]
OK... I suppose you're having two versions of Gogs on your system. Which means the one serves HTTP requests is not the one serves SSH requests.

A quick fix (ignore old Gogs) to my assumption is go to URL `/admin/` and do:

- Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)
- Rewrite all update hook of repositories (needed when custom config path is changed)

**Comment by moritzheiber** [comment]
Hm, indeed. The version run by `authorized_keys` is:
```
$ ./gogs -v
Gogs version 0.6.16.1002 Beta
```
But the version reported by the gogs web instance is 0.6.1.0325.

**Comment by Unknwon** [comment]
Cool, but have you done what I suggested?

**Comment by moritzheiber** [comment]
Ha, found the difference: `.ssh/authorized_keys` is running `/opt/gogs/gogs. But the upstart script is running `/usr/bin/gogs`.

I'd rather rewrite the upstart script to be honest, it's not running the latest version of gogs after all?

If that's not the preferred way of doing it, what should I "rewrite" `authorized_keys` and the update hook with?

**Comment by Unknwon** [comment]
> A quick fix (ignore old Gogs) to my assumption is visiting URL `/admin` and do:
- Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)
- Rewrite all update hook of repositories (needed when custom config path is changed)

I have mentioned in my former comment.

**Comment by moritzheiber** [comment]
Right, I just now realized there are links I can click on .. Sorry for being a jackass.

**Comment by Unknwon** [comment]
:sweat_smile:

**Comment by moritzheiber** [comment]
Aaand that fixed the issue. Thanks @Unknwon!

**Comment by Unknwon** [comment]
Awesome! :smiley:
