### ISSUE TITLE
Volume directive in Dockerfile prevents folders in /data to be created

### ISSUE THREAD

**Issue by alvaroaleman** [gogits/gogs#1759]
Steps to reproduce:

Build the following image:

```Dockerfile
FROM gogs/gogs
RUN /bin/bash -c 'set -exuo pipefail && mkdir -p /data/gogs/data /data/gogs/conf /data/gogs/log /data/git && ls -l /data && ls -l /data/gogs'
```

execute ``docker run $imageid ls -l /data``

Expected result: subfolders

Actual result: ``total 0``

This issue was introduced in e63e0b3105124bd8ec3028a39dc71c8d8ca103e3 and is caused by the the [volume directive](https://github.com/gogits/gogs/blob/master/Dockerfile#L19).

This behaviour forces users to mount the whole ``/data```folder as volume even if e.g. the logs are not wanted.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think it is done by purpose: https://github.com/gogits/gogs/tree/master/docker#usage

**Comment by alvaroaleman** [comment]
Thanks for commenting.

Yep I read the docs, but there are two things I dislike about that approach:

* Logs are imho nothhing a container should output via file, this is done using [logging drivers](https://docs.docker.com/reference/logging/overview/)
* To easely deploy containers on different hosts, I like to put the config inside the container. This means I only have to distribute the container but not additional configuration files

Also, could you tell me what's the advantage of using the ``volume`` directive? Since ``docker run -v $source:$target`` can be used to mount any folder anywhere in the container, I don't quite see the advantage of marking folders like this. Only thing the ``volume`` directive seems to do is delete everything below that folder, or did I miss something here?

**Comment by Unknwon** [comment]
> To easely deploy containers on different hosts, I like to put the config inside the container. This means I only have to distribute the container but not additional configuration files

Custom configuration will never be a part of container.

**Comment by Unknwon** [comment]
> Logs are imho nothhing a container should output via file, this is done using logging drivers

Gogs is not Docker specific application, so it may be supported in the future but not a hard requirement.

**Comment by tboerger** [comment]
@alvaroaleman your way can never work. The folders are getting created within the s6 start process. It's starting with the `CMD` defined in the Dockerfile. You have overwritten `CMD`, so s6 gets never started and https://github.com/gogits/gogs/blob/master/docker/s6/gogs/setup#L3-L5 never gets executed.

So what do you expect if you are just using the docker image the wrong way?

**Comment by alvaroaleman** [comment]
@tboerger  Can you elaborate on where I overwrote ``CMD``?


@Unknwon has a point with
> Custom configuration will never be a part of container.

Still, having to create a share for the whole app including configuration sucks. Probably the best solution here is to offer an alternate way of configuring gogs using environment variables, which is how Docker is supposed to work after all.

**Comment by tboerger** [comment]
> @tboerger Can you elaborate on where I overwrote CMD?

You overwrite `CMD` with `docker run $imageid ls -l /data`

**Comment by alvaroaleman** [comment]
> You overwrite CMD with docker run $imageid ls -l /data

Oh yeah but that run is just for demonstration purposes, not for running the application. As you can see in the Dockerfile I posted in my first comment on the issue, I manually create the folders using
``RUN /bin/bash -c 'set -exuo pipefail && mkdir -p /data/gogs/data /data/gogs/conf /data/gogs/log /data/git && ls -l /data && ls -l /data/gogs'``

**Comment by tboerger** [comment]
Ok, the issue is quite easy resolvable. We just need to update the setup script. Instead of this:

```bash
if ! test -d /data/gogs; then
    mkdir -p /data/gogs/data /data/gogs/conf /data/gogs/log /data/git
fi
```

we should do this:

```bash
if ! test -d /data/gogs/data; then
    mkdir -p /data/gogs/data
fi

if ! test -d /data/gogs/conf; then
    mkdir -p /data/gogs/conf
fi

if ! test -d /data/gogs/log; then
    mkdir -p /data/gogs/log
fi

if ! test -d /data/git; then
    mkdir -p /data/git
fi
```

Then you are able to do something like `docker run -ti --rm --name gogs -v /storage/gogs/data:/data/gogs/data -v /storage/gogs/conf:/data/gogs/conf -v /storage/gogs/git:/data/git -p 10022:22 -p 8080:3000 gogs/gogs`

**Comment by alvaroaleman** [comment]
Oh you're right, that's indeed a better solution

**Comment by Unknwon** [comment]
> Still, having to provide a share for the whole app including configuration sucks. Probably the best solution here is to offer an alternate way of configuring the gogs container using environment variables, which is how Docker is supposed to work after all.

You're talking about private distribution, not official.

**Comment by Unknwon** [comment]
Please check #1764

**Comment by alvaroaleman** [comment]
Yup, this solves the issue. Thanks @tboerger and @0rax

**Comment by Unknwon** [comment]
Thanks your confirmation!
