### ISSUE TITLE
Gogs (installed from package) tries to start before postgresql and fails

### ISSUE THREAD

**Issue by Sam-Izdat** [gogits/gogs#1761]
Gogs was installed from package on Ubuntu 14.04 and postgres was configured as the database. Upon reboot, the server did not come up. Restarting with `service gogs restart` brought it back up. The log explained that Gogs couldn't make a database connection, apparently because it was starting before postgres was ready to accept connections. The workaround was to edit `/etc/init/gogs.conf` and change the first line to the following:

    start on started postgresql

... in place of:

    runlevel [2345]

**Comment by Unknwon** [comment]
Thanks your feedback!

But this file you talked about does not exist in Gogs repository, I think it is generated by packager.io .

cc @crohr

**Comment by Sam-Izdat** [comment]
Apologies, I'm not familiar with the deployment process or upstart – just thought you might want to know. I have not checked with MySQL yet, so this may be specific to some assumption packager makes that postgres doesn't satisfy. Just in case it might matter, the postgres version is 9.3.9.

**Comment by Unknwon** [comment]
@Sam-Izdat thanks your info!

**Comment by Unknwon** [comment]
ping @crohr :trollface:

**Comment by stonerl** [comment]
I do have the same problem with mysql. I had to replace 
```
runlevel [2345]
``` 
with 
```
start on started mysql
```
It would work also with this:
```
start on (started mysql or started postgresql)
```
But if a user does use sqlite and has neither mysql nor postgresl running, gogs would probably not start.

**Comment by crohr** [comment]
@Unknwon is there any way to make gogs not crash if it can't connect to the db when it starts? Because as it is, we can't have an init script magically reconfigure itself depending of which db a user is using. Also, it wouldn't work anyway if the user uses an external database.

**Comment by Unknwon** [comment]
@crohr Gogs tries to connect db when start... so it is kind of hard to do..

**Comment by stonerl** [comment]
@crohr 

I modified gogs-web-1.conf

```
start on starting gogs-web
stop on stopping gogs-web
respawn
respawn limit 6 60

env PORT=6000

exec gogs run web >> /var/log/gogs/web-1.log 2>&1
post-stop exec sleep 10
```
And now it starts correctly after rebooting

@Sam-Izdat could you revert your changes in gogs.conf to ```runlevel [2345]``` and modify gogs-web-1.conf and test it?

**Comment by Sam-Izdat** [comment]
@stonerl Yup. That did it.

**Comment by Unknwon** [comment]
What is the status of this issue now?

**Comment by linquize** [comment]
Can you adjust the dependency order in system  init?

**Comment by Unknwon** [comment]
@linquize never used that... can you help make up a PR?

**Comment by stonerl** [comment]
@Unknwon The recommendation I posted seems to work for @Sam-Izdat. How do this sciprts get generated? I know that it uses foreman, but get these scripts generated during the creation of the package?

**Comment by stonerl** [comment]
@linquize it is not the dependencie-order, it has to work with all kind of configurations. That's why you cannot simply create a e.g. mySQL or Postgres dependencies.

**Comment by Unknwon** [comment]
I guess.... they are generated by packager.io directly? (it seems to use build-pack from heroku)

**Comment by stonerl** [comment]
We just need those lines:
```
respawn 
respawn limit 6 60
```
and
```
post-stop exec sleep 10
```

added as you can see in my former comment. What it does is; the respawn limit is set to 6 attempts in 60 seconds. When one attempt fails it waits 10 seconds before it tries to restart the service which gives the db services enough time to start. In the worst case Gog's would need 1 minute before it fails because it cannot connect to the db.

**Comment by Unknwon** [comment]
cc @crohr

**Comment by stonerl** [comment]
This seems to be the file in question:

https://github.com/crohr/pkgr/blob/master/data/init/upstart/1.5/process.conf.erb

**Comment by stonerl** [comment]
@Unknwon I opened an PR

**Comment by Unknwon** [comment]
@stonerl :+1:

**Comment by stonerl** [comment]
@Unknwon @crohr 

I think I found a solution that works even better. But we need to decide which path we use for users who prefer to use sqlite3 databases.

The needs to replace ```runlevel [2345]``` in ```/etc/init/gogs.conf````
```
start on (started mysql or started postgresql or file FILE=/path/to/sqlite-db.sqlite)
```
Here gogs would start if either the mysql or postgesql is running or the sqlite-db-file is present. So we would have covert all 3 databases.

**Comment by Unknwon** [comment]
Hmm... feels like needs hack on Gogs source code.

**Comment by stonerl** [comment]
@Unknwon would it be somehow possible that gogs is aware of a missing database? When gogs got properly configured but for some reason the database is missing gogs could still start, but when trying to connect to the page it should show an 500 or 503 HTTP-Status. Meanwhile gogs could try to connect to the configured db every x seconds/minutes.

**Comment by Unknwon** [comment]
@stonerl I think it is possible, but should be put into a separate issue.

**Comment by stonerl** [comment]
OK I'm gone open another issue regarding this topic.

-----Original Message-----

**Comment by Unknwon** [comment]
So... what is the status of this issue now..

**Comment by crohr** [comment]
The init script can't be updated on packager.io, because we can't assume that all apps packaged with that solution want that change to their init script. The solution here is to implement #2305 (which is what Rails apps do for instance), or have users setup `monit` to restart failing services.

**Comment by Unknwon** [comment]
Thanks @crohr

**Comment by fake-name** [comment]
This is still happening.

Why is this issue closed?
