### ISSUE TITLE
Incorrect SSH URL for cloning (installed from package)

### ISSUE THREAD

**Issue by Sam-Izdat** [gogits/gogs#1762]
Gogs was installed from package on Ubuntu 14.04. The URL that Gogs offers to users for cloning via SSH reads:

    gogs@example.com:username/reponame.git

This fails:

    fatal: 'username/reponame.git' does not appear to be a git repository

When the "gogs-repositories" parent directory is included before "username" the problem is resolved, i.e.:

    git clone gogs@example.com:gogs-repositories/username/reponame.git

**Comment by Unknwon** [comment]
Please see https://github.com/gogits/gogs/issues/1576#issuecomment-137675306

**Comment by COLABORATI** [comment]
I see absolutely no connection to #1576. 

Could you please describe what factors do affect that url generation? I have configured the ROOT - but I do not understand why gogs generates a wrong path. Could you please describe with a few words what exactly is considered by gogs to generate the repo url? Where exactly in the code is  this url generated? Thank you very much for your attention!

**Comment by Unknwon** [comment]
@COLABORATI What I posted is the link of comment, not issue itself.

**Comment by COLABORATI** [comment]
OK, after doing a clean reinstall not from the packages but from the binary and a double check with all configuration options it know works! YEAH! 

I know understand that the "aliasing" of the repo url is done via the gogs serv command - this was not obvious, but with some patience it is possible to figure it out. You should *not* add this info to the docs to give people some motivation to read the sources - go is an interesting language! :) 

Thanks again for your efforts and have a nice weekend!

**Comment by Unknwon** [comment]
> You should not add this info to the docs to give people some motivation to read the sources

:trollface: someone asked to add that in doc...

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by Spaider** [comment]
Sorry, but still I do not understand what is wrong with my config. I had the same problem, when **gogs-repositories** is missing from clone URL. Did install by simply un'tar'ing into /home/jail/home/git directory (yeah, non-default, but everything seems to be working). For now I don't have much time to lure through Go code :(
Could someone please explain what needs to be done for displaying correct clone URL for git:// protocol?

**Comment by Unknwon** [comment]
@Spaider what URLs you should use are displaying on the Gogs web UI, if not working, config is wrong...

**Comment by Spaider** [comment]
@Unknwon exactly as in initial post: directory name `gogs-repositories` is missing on web UI. Everything works fine if I add this dir name manually. Probably, config is wrong but I am not able to understand, which way is right :)

**Comment by Unknwon** [comment]
@Spaider it is not **missing**, it is not supposed to use.

**Comment by Spaider** [comment]
@Unknwon great, thanks. But still, how did it happen that I can only work with repo over SSH/git if I specify that directory name? :) Obviously, something is nor right but I can't figure out what exactly.

**Comment by Unknwon** [comment]
@Spaider try operations here: https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook
