### ISSUE TITLE
git --mirror 或 git push 一个大项目时会出错

### ISSUE THREAD

**Issue by ganxiangdong** [gogits/gogs#1763]
命令 git push --mirror http://xxxxxxx/xxxx/xxx.git 或 git push -f http://xxxxxxx/xxxx/xxx.git 报如下错误：
Counting objects: 4077, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2078/2078), done.
Writing objects: 100% (4077/4077), 80.64 MiB | 905.00 KiB/s, done.
Total 4077 (delta 2360), reused 3473 (delta 1954)
efrror: RPC failed; result=22, HTTP code = 500
atal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

然后web访问就是500了，重启后不报500，但是代码没有push上去

**Comment by Unknwon** [comment]
> git push 一个大项目时会出错

What is error log for this?

**Comment by john-hu** [comment]
I met the same issue today. It's because the server is out of memory. We run it at aliyun with 512MB VM. While pushing a repo with large file, it gives us out of memory error. The largest file is about 28,221,118 bytes. The while repo for upload is about 260MB. The error message looks like:

```
 2015/10/12 12:15:22 ^[[1;31m[...s/middleware/repo.go:322 func1()] [E] GetTags: fork/exec /usr/bin/git: cannot allocate memory^[[0m
 runtime: out of memory: cannot allocate 268435456-byte block (279969792 in use)
2133 fatal error: out of memory
```

<img width="464" alt="screen shot 2015-10-12 at 3 44 36 pm" src="https://cloud.githubusercontent.com/assets/6179015/10423344/40ad3302-70f8-11e5-9f82-10462c38b41a.png">

<img width="427" alt="screen shot 2015-10-12 at 3 44 47 pm" src="https://cloud.githubusercontent.com/assets/6179015/10423348/44bd36a4-70f8-11e5-95fb-5be882aed267.png">

**Comment by john-hu** [comment]
BTW, I had tried to push the repo to our local server which has 4GB memory. It works correctly.

```
Counting objects: 2401, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1877/1877), done.
Writing objects: 100% (2401/2401), 260.94 MiB | 6.03 MiB/s, done.
Total 2401 (delta 599), reused 1710 (delta 458)
```

Is there any memory usage estimation based on repo size?

**Comment by Unknwon** [comment]
@john-hu thanks for the details!

Are you pushing through HTTP/HTTPS? Because it seems impossible to free memory during a HTTP request cycle before it is finished so far. 

> Is there any memory usage estimation based on repo size?

What is the actual repo size which uses `260MB` memory for pushing?

**Comment by john-hu** [comment]
@Unknwon 
We are using `HTTPS`.

The local file size of `.git` folder is about 273MB. I don't know why we need 260MB memory for pushing, neither.

**Comment by Unknwon** [comment]
@john-hu I don't know right now as well. For such large repository, maybe you should try SSH.

**Comment by john-hu** [comment]
@Unknwon 

Ok, got it. We prefer to use https because we only want to open a https port in our firewall. We don't want to open too much ports at our firewall. Is there any solution with this? Or the only way is to use SSH.

**Comment by Unknwon** [comment]
@john-hu I can't think of a way right now, because normally you can't release memory of the request until the request is finished, I think this is way memory is keep going up.

**Comment by john-hu** [comment]
@Unknwon is there possible to stream https request to file and to pipe partial content to memory for processing?

**Comment by Unknwon** [comment]
That is the advanced thing I'm looking for, I don't know yet, but hope :D

**Comment by john-hu** [comment]
Got it!!! Thanks for the analysis.....

**Comment by melote** [comment]
I met this before, the repo become a 500 error code. and never delete it, so I deleted the database and rebuilt it

**Comment by Unknwon** [comment]
Hmm.. what is the status of this issue?

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
