### ISSUE TITLE
Git push includes my github username in non-github gogs repo

### ISSUE THREAD

**Issue by 1Hyena** [gogits/gogs#1771]
I'm using Gogs · Version: 0.6.16.1002 Beta and when I pushed changes to a private git repository that repository is showing my github username (1Hyena) as the author of the commit. Instead, it should show the username I registered with gogs for that private repository. When I push changes to the private repository I am asked the username and password correctly. However, gogs displays my github username instead. This may or may not be gogs related issue, but it definitely is someone's issue. Any ideas what could be happening?

**Comment by Unknwon** [comment]
Thanks your feedback!

One thing to clarify:

> However, gogs displays my github username instead

It just happens your local git setting uses same name as your GitHub username, and it is **not** actually your GitHub username.

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/issues/1564 is what you're looking for.

**Comment by 1Hyena** [comment]
Ok thanks for the info. This explains it: 
```
hyena@Scourge ~ $ git config -l
user.name=1Hyena
user.email=hyena@hyena.net.ee
push.default=simple
```

Is there any way to change the user.name field for a specific cloned repository but leave it the same for all the others on my system?

**Comment by Unknwon** [comment]
> Is there any way to change the user.name field for a specific cloned repository but leave it the same for all the others on my system?

I suppose you can, but never tried...

**Comment by 1Hyena** [comment]
Ok, it works. Here's the tutorial:
http://www.thebuzzmedia.com/git-tip-git-config-user-name-and-user-email-for-local-not-global-config/

After changing the user.name and user.email locally a push resulted in showing the username correctly in Gogs. This is a good workaround.

**Comment by Unknwon** [comment]
Great! So have the issue been resolved?

**Comment by 1Hyena** [comment]
To me it's resolved but as a software developer I would say that Gogs should highlight the username who was authenticated during the push rather than the username defined in the pusher's local repository. Or, at least, gogs should display both of them and differentiate between them, to make it explicit.

**Comment by Unknwon** [comment]
Then it is duplicated #1564

**Comment by 1Hyena** [comment]
And what's your policy on duplicated issues? Should this one be closed?

**Comment by Unknwon** [comment]
Yes :D
