### ISSUE TITLE
Please add autocomplete support on tagging other user

### ISSUE THREAD

**Issue by john-hu** [gogits/gogs#1772]
It would be nice to have autocomplete support while typing `@` character at comment of PR or issues.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by ChangePlaces** [comment]
How would this work? Would typing "@a" list all users in the team that begin with 'a'. Or maybe all users in the system beginning with 'a'? What if there is no team? What if there are no users beginning with 'a' in the project?

**Comment by Unknwon** [comment]
>  What if a user wanted to be 'private'?

It does not matter, just matter of notify him/her or not, but you can always `@`.

**Comment by Unknwon** [comment]
Note: http://yuku-t.com/jquery-textcomplete/

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/2957
