### ISSUE TITLE
500 on file history

### ISSUE THREAD

**Issue by dotwoo** [gogits/gogs#1773]
版本信息:
© 2015 Gogs 当前版本: 0.6.15.0926 Beta 页面: 4ms 模板: 2m
uname -a 
Linux localhost.localdomain 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
git --version
git version 1.7.1

错误日志:

2015/10/13 17:41:25 [...uters/repo/commit.go:151 FileHistory()] [E] repo.FileHistory(GetCommitsCount): usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

**Comment by Unknwon** [comment]
Thanks your feedback, can you share your repository for reproducing this error?

**Comment by Unknwon** [comment]
Also, would you mind update to `develop` branch again, because I just added a log to print what is the version Gogs captures.

It seems a problem to me that Gogs does not recognize your Git version correctly.

**Comment by dotwoo** [comment]
git version output :
[root@localhost gogs]# git --version 
git version 1.7.1

**Comment by Unknwon** [comment]
Thanks, but again: would you mind update to develop branch again, because I just added a log to print what is the version Gogs captures.

**Comment by dotwoo** [comment]
我今天会编译develop版本试试,不过没有那么快.请稍等一下

**Comment by dotwoo** [comment]
2015/10/14 16:50:32 [T] regulateTimeZone: 2015-10-13 00:56:48 +0800 CST - +0800
2015/10/14 16:50:32 [...uters/repo/commit.go:151 FileHistory()] [E] repo.FileHistory(GetCommitsCount): usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

2015/10/14 16:50:32 [I] New random avatar created: 1
[Macaron] Completed /wow/tyrande/commits/master/build.gradle 500 Internal Server Error in 46.767654ms

**Comment by dotwoo** [comment]
这个git 版本 git rev-list 不支持 --count

**Comment by dotwoo** [comment]
update git can fix the problem

 rpm -ivh http://mirror.symnds.com/distributions/gf/el/6/gf/x86_64/gf-release-6-8.gf.el6.noarch.rpm
 yum --enablerepo=gf-plus update git -y

# git version 
git version 2.6.0

**Comment by Unknwon** [comment]
Thanks.

Have your problem been solved?

**Comment by Mrhyuan** [comment]
@Unknwon 按照 @dotwoo 说的方式更新git即可 问题会解决 可以close了

**Comment by Unknwon** [comment]
@Mrhyuan thanks your confirmation!

Even thought I was trying to locate the real problem :D
