### ISSUE TITLE
Can't git clone using http after refresh install

### ISSUE THREAD

**Issue by qianlifeng** [gogits/gogs#1774]
I got following errors when I run `git clone http:/xxxx`
```
Cloning into 'xxxxx'...
fatal: unable to access 'http://xxxx.xxx.xxx.xx:3000/user/xxx.git/': The requested URL returned error: 500
```

ssh clone is ok, any thoughts?

**Comment by Unknwon** [comment]
Thanks your feedback!

1. What is your Gogs version?
2. What is your system?
3. What is the database you're using?
4. What is the error log of `500`?

**Comment by qianlifeng** [comment]
What is your Gogs version?
0.6.15.0926

What is your system?
CentOS 6

What is the database you're using?
Mysql

What is the error log of 500?

![qq 20151014103746](https://cloud.githubusercontent.com/assets/1725475/10473584/aad4333a-725f-11e5-844d-14b01ec2f4b8.png)

**Comment by Unknwon** [comment]
There is nothing about 500, how do you know it is a 500 error?

**Comment by qianlifeng** [comment]
You are right, it's my linux problem (iptables?), I can git clone in the server which hosts Gogs. Closing this issue now and thx for response :smile:

**Comment by Unknwon** [comment]
Cool! Glad you found the solution!
