### ISSUE TITLE
How to setup hooks

### ISSUE THREAD

**Issue by RobertWang** [gogits/gogs#1775]
如何设置hook，完成自动部署或自动化脚本的执行。谁有例子也可以。Linux环境的，多谢了。

我试了几个都不行，不能完成自行复制。求熟悉的高手指点一二。

初步怀疑以下几点
1. 环境变量问题
2. 用户权限

但不知道如何调试。

求授以以渔。再次感谢。

**Comment by Fastidious** [comment]
我也沒有辦法。你可以擴大你的潛在傭工游泳池，如果您在英語這些請求。

**Comment by Unknwon** [comment]
Hi there, match one of following conditions you will be able customize hook script of a repository:

1. You're site admin
2. You're given permission by site admin

![image](https://cloud.githubusercontent.com/assets/2946214/10466528/b521cda4-71c2-11e5-9ea9-dec72a435fed.png)

**Comment by Unknwon** [comment]
Any updates?
