### ISSUE TITLE
一个建议，什么时候能在gogs中集成代码编辑功能？

### ISSUE THREAD

**Issue by RobertWang** [gogits/gogs#1776]
一个建议，什么时候能在gogs中集成代码编辑功能？

开发团队是否有集成计划？

**Comment by Fastidious** [comment]
我建議你檢查: https://trello.com/b/uxAoeLUl/gogs-go-git-service

**Comment by Unknwon** [comment]
Thanks your feedback!

But it is duplicated to https://github.com/gogits/gogs/issues/485 .

Quick answer for your question: yes it will be implemented but not in the near future. :smiley:
