### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by smallnewer** [gogits/gogs#1780]
对GO没太多经验，MAC的10.11.
不太清楚哪里出的问题。
使用下面的命令进行安装
````
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 /usr/local/go/bin/go get -u -v github.com/gogits/gogs
````

中间有个报错
````
gopkg.in/ini.v1
github.com/go-xorm/core
github.com/gogits/gogs/modules/bindata
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
github.com/gogits/gogs/modules/user
github.com/gogits/gogs/modules/asn1-ber
....
````

build时也有错
````
$ CGO_ENABLED=1 GOOS=linux GOARCH=amd64 /usr/local/go/bin/go build
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

````
$ /usr/local/go/bin/go version
go version go1.4.2 darwin/amd64
````
gcc版本是Mac自带的，成功执行了xcode-select install
编译Mac版本是没问题的。但linux就不行了。已经执行了make.sh

**Comment by smallnewer** [comment]
是因为交叉编译不支持跨平台编译么？

**Comment by matrixise** [comment]
Please, could you translate the bug in english. We can't fix it if we can't read the description of this one. Thank you

**Comment by Unknwon** [comment]
Thanks your feedback!

I suggest you upgrade go to 1.5.

PS:

> 是因为交叉编译不支持跨平台编译么？

It is not a valid statement, you're saying `true` is not `true`, those two things you're saying mean exactly same thing.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
