### ISSUE TITLE
Clone over SSH hangs

### ISSUE THREAD

**Issue by gvansanden** [gogits/gogs#1782]
Running Gogs 0.6.15-1444686551.a425146.trust on Ubuntu 14.04 x64 with Git 1.9.1 from repos, I cannot do a clone over SSH, it starts but hangs indefinately.

In the log I get:
2015/10/13 19:17:39 [...ts/gogs/cmd/serve.go:199 runServ()] [F] Failed to execute git command: signal: broken pipe

Google pointed ad GZIP but that is off by default I see

**Comment by gvansanden** [comment]
The error message is a consequence of me aborting the clone, but the core issue remains, it never finishes (shows the /etc/issue.net of the remote host and stops there)

**Comment by preovaleo** [comment]
Same error with the last packager.io release (0.6.16.1008 Beta)
However the http clone still works

**Comment by de-live-gdev** [comment]
+1

**Comment by mexthemax** [comment]
I got the same problem (can't clone or push via ssh). But I was able to fix it by reverting the changes in commit 570ddefc3259b8bebebf6db6b7d9029b749358f9 .

My gogs version is: 0.6.16.1008 Beta

**Comment by xoxys** [comment]
Same here

**Comment by gvansanden** [comment]
﻿Rerverting those changes and restarting gogs did not solve the issue for me



-----Original message-----

**Comment by de-live-gdev** [comment]
@gvansanden 
Did you rebuild gogs?

    sudo systemctl stop gogs
    sudo su git
    cd GOGSDIR
    revert (e.g. git checkout 5676fa5b5d818867a26aeddfbc48f593fab957df)
    go build
    sudo systemctl start gogs

**Comment by gvansanden** [comment]
@de-live-gdev 
No, I didn't.  I have it installed from apt.  just did a locate on the file...  So probably that is why

**Comment by james2doyle** [comment]
Is the solution here to rollback? 

I have managed to clone over HTTP fine, it's just SSH that hangs for me.

**Comment by Unknwon** [comment]
@mexthemax thanks your tip!

@all I've rolled backed the change to `master`.
