### ISSUE TITLE
git hooks doesn't execute

### ISSUE THREAD

**Issue by Fchen48** [gogits/gogs#1783]
Hi, 

I installed gogs for first time, and tried to use git hooks but they won't work. 
I wrote `touch test` in post-commit, post-update and post-recieve, after a commit it doesn't execute any of the hooks, if I try to manually execute the hook, everything works perfectly, permission setting is also ok. 
I'm using version: 0.6.16.1008 Beta

**Comment by Unknwon** [comment]
Thanks your feedback!

> I wrote touch test in post-commit, post-update and post-recieve, after a commit it doesn't execute any of the hooks

Executing hook scripts are not called by Gogs, but by git itself. So I'm not sure what is the problem exactly right now.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.

**Comment by Fchen48** [comment]
git hooks work with 0.8.X - no change of hooks since 0.6.16.X

**Comment by Unknwon** [comment]
Thanks @Fchen48 , so do you mean there is no problem using Git hooks right now for you?

**Comment by Fchen48** [comment]
Yes, that's right

**Comment by Unknwon** [comment]
OK, great.
