### ISSUE TITLE
Error resolving database IP ( using docker ) 

### ISSUE THREAD

**Issue by rahal** [gogits/gogs#1784]
Hi,

For some reason, gogs don't use the hostnames defined in /etc/hosts while trying to connect to the database.
Here is the error I found in the log files

.s/routers/install.go:63 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp: lookup dbgogs on 8.8.8.8:53: no such host .

I also noticed that It worked when I installed gogs, but it saved the IP adress in  app.ini , this IP adress can change if I restart my mysql container, so I think that we should always use the hostname.

Thank you

**Comment by 0rax** [comment]
Hi @rahal,

What version of the docker container are you using ?

FYI, in the latest version of it we added the possibility to refere to linked service as `localhost` using socat link. This way any service linked to the docker container will be available as `localhost:service_port` from the docker container itself.

If you give me a little bit more information about which image you are using I will try to take a deeper look into this problem.

**Comment by rahal** [comment]
Thank you @0rax !!
It didn't work with localhost,  then I used 127.0.0.1:port then it worked :)  .

Thank
