### ISSUE TITLE
Is PAM authentication working ?

### ISSUE THREAD

**Issue by marcolefo** [gogits/gogs#1785]
Hi !

Gogs 0.6.16.1008 Beta
Installed by packager.io
Debian 8

I am testing Gogs with PAM. But I can't manage to make it work.

I have configured Gogs PAM like that 
- Authentication Name : pam_gogs
- PAM Service Name : gogs (I have also tried to let it empty)
  
I have created a file named gogs in /etc/pam.d/ : 
```
@include common-auth
@include common-account
@include common-password
@include common-session
```

But I have "Username or password is not correct" when I try to log in.

/var/log/gogs/gogs.log : 
```
2015/10/14 17:29:01 [W] Failed to login 'toto' via 'pam_gogs': PAM not supported
```

Thanks for you work. Gogs is great ;)

**Comment by Unknwon** [comment]
Hi there, if you want to use PAM, you have to compile Gogs with `go build -tags "pam"`.

Or, download binaries from https://github.com/gogits/gogs/wiki/Download

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
