### ISSUE TITLE
creating new repo from a template

### ISSUE THREAD

**Issue by bhchew** [gogits/gogs#1786]
Not raising a issue but seeking advice.

If we create a 'template' repo, and we create a new repo by migration from the 'template' repo, will git/web hooks be migrated too?

**Comment by Unknwon** [comment]
> If we create a 'template' repo, and we create a new repo by migration from the 'template' repo, will git/web hooks be migrated too?

Most likely not.

And I think your title is somewhat quite different with the actual content?

**Comment by bhchew** [comment]
Yep, changing title for clarity.

Actually my thought is to init a repo with predefined hooks and files/dir in the repo.

Similarly to the below option but with customizable templates. Maybe the feature is already so seeking advise =)

![image](https://cloud.githubusercontent.com/assets/1488128/10567995/3a32fa38-7644-11e5-9124-0ce25737bf3f.png)

**Comment by Unknwon** [comment]
> Actually my thought is to init a repo with predefined hooks and files/dir in the repo.

For `files/dir in the repo`, why don't just create a repository and migrate from it every time?

For `hooks`, haven't got a good idea.

**Comment by bhchew** [comment]
Yep, that's my thought too.

Just exploring whether there's a way to migrate hooks too. Maybe if the community find this feature useful than will revisit this =)

Closing for now.

**Comment by Unknwon** [comment]
Have a template of hooks is not a problem, but how to make it fit in the UI is the key.
