### ISSUE TITLE
FIDO U2F

### ISSUE THREAD

**Issue by andrewrothman** [gogits/gogs#1787]
What do you think about support for the FIDO U2F two-factor authentication standard?

GitHub, Google, and Dropbox currently support this.

I've tested this in Chrome with a YubiKey and it works great. I would love to secure Gogs and I believe this would be a great feature.

Also, while we're on the topic of 2FA, what's the low-down on HOTP/TOTP authentication? (ex. using the Google Authenticator or FreeOTP mobile apps)

**Comment by Unknwon** [comment]
Thanks your feedback!

But it is basically duplicated to https://github.com/gogits/gogs/issues/945 .

I've linked your comment in that thread. :wink:
