### ISSUE TITLE
the tag dropdown menu don't cover some tag on my README.md

### ISSUE THREAD

**Issue by liangx8** [gogits/gogs#1789]
when I open Tag drop down menu on project home page. it's covered by some tag on my README.md file. and it very difficult  to click. can it be improved?

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs and can you reproduce this on https://try.gogs.io ?

**Comment by liangx8** [comment]
your web need a active account. can you give me some trial account so that I can create project to reproduce it?

**Comment by liangx8** [comment]
I use  0.6.9.0903 Beta,

**Comment by liangx8** [comment]
or please take a look attached picture
![tag drop down list interfere with element in README.md](https://cloud.githubusercontent.com/assets/1329556/10569333/3238e190-7657-11e5-89a5-cd9001bbeac5.png) there is a tag call "pump_??" covered by "motor" that is in README.md

**Comment by Unknwon** [comment]
There is no trial account, and please update to v0.6.15 and report back :)

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by liangx8** [comment]
I update to version 0.7.19, problem is gone. thanks

**Comment by Unknwon** [comment]
:trollface:
