### ISSUE TITLE
Huge diff causes out of memory

### ISSUE THREAD

**Issue by webhat** [gogits/gogs#1790]
After requesting a huge diff the server returns 500 errors. I'm guessing the data is never freed.

```
$ ./gogs web
2015/10/15 15:25:19 [T] Custom path: /home/gogs/custom
2015/10/15 15:25:19 [T] Log path: /home/gogs/log
2015/10/15 15:25:19 [I] Gogs: Go Git Service 0.6.16.1008 Beta
2015/10/15 15:25:19 [I] Log Mode: File(Info)
2015/10/15 15:25:19 [I] Cache Service Enabled
2015/10/15 15:25:19 [I] Session Service Enabled
2015/10/15 15:25:19 [I] Run Mode: Production
2015/10/15 15:25:19 [T] Doing: CheckRepoStats
2015/10/15 15:25:20 [I] Listen: http://0.0.0.0:3000
[Macaron] Started GET /webhat/jobs/commit/638b05b8b81e8cab485bb9e67d9ef39b22a20739 for X.X.X.X
2015/10/15 15:25:53 [W] Diff data too large
[Macaron] Started GET / for X.X.X.X
[Macaron] Completed / 200 OK in 1.847545929s
[Macaron] Started GET /avatars/2 for X.X.X.X
[Macaron] [Static] Serving /2
[Macaron] Completed /avatars/2 304 Not Modified in 977.191µs
[Macaron] Started GET /avatars/4 for X.X.X.X
[Macaron] [Static] Serving /4
[Macaron] Completed /avatars/4 304 Not Modified in 143.42µs
[Macaron] Started GET /webhat/jobs for X.X.X.X
2015/10/15 15:26:29 [...s/middleware/repo.go:321 func1()] [E] GetTags: fork/exec /usr/bin/git: cannot allocate memory
[Macaron] Completed /webhat/jobs 500 Internal Server Error in 105.414694ms
[Macaron] Started GET /js/gogs.js?v=0.6.16.1008%20Beta for X.X.X.X
[Macaron] Started GET /css/gogs.css?v=0.6.16.1008%20Beta for X.X.X.X
[Macaron] [Static] Serving /js/gogs.js
[Macaron] Completed /js/gogs.js?v=0.6.16.1008%20Beta 304 Not Modified in 5.32421ms
[Macaron] [Static] Serving /css/gogs.css
[Macaron] Completed /css/gogs.css?v=0.6.16.1008%20Beta 304 Not Modified in 3.723538ms
[Macaron] Started GET /img/500.png for X.X.X.X
[Macaron] [Static] Serving /img/500.png
[Macaron] Completed /img/500.png 200 OK in 20.761721ms
[Macaron] Started GET / for X.X.X.X
[Macaron] Completed / 200 OK in 571.088665ms
[Macaron] Started GET /webhat/jobs/src/master for X.X.X.X
[Macaron] Completed /webhat/jobs/src/master 500 Internal Server Error in 373.698742ms
2015/10/15 15:26:42 [...s/middleware/repo.go:321 func1()] [E] GetTags: fork/exec /usr/bin/git: cannot allocate memory
[Macaron] Started GET /css/gogs.css?v=0.6.16.1008%20Beta for X.X.X.X
[Macaron] Started GET /js/gogs.js?v=0.6.16.1008%20Beta for X.X.X.X
[Macaron] [Static] Serving /css/gogs.css
[Macaron] Completed /css/gogs.css?v=0.6.16.1008%20Beta 304 Not Modified in 2.670188ms
[Macaron] [Static] Serving /js/gogs.js
[Macaron] Completed /js/gogs.js?v=0.6.16.1008%20Beta 304 Not Modified in 3.38677ms
```

**Comment by Unknwon** [comment]
Thanks your feedback!

To clarify the problem, 

> [W] Diff data too large

>  [E] GetTags: fork/exec /usr/bin/git: cannot allocate memory

They are not relevant as far as I know. Do you have any evidence that proves the relation between them?

>  [E] GetTags: fork/exec /usr/bin/git: cannot allocate memory

Your server is running out of memory, please check it first, and GC may be not fast enough to recycle the diff data I suppose.

**Comment by webhat** [comment]
The diff it's trying to load is the checkin of a huge project, before the diff is called gogs is a constant size, about 36 Mb. After the call to diff it balloons to over 2 Gb and starts returning status 500 on any git calls. The memory is not released.

`$ cat /proc/18252/status`
```
...
VmPeak:    37260 kB
VmSize:    37260 kB
...
```

`$ cat /proc/18252/status`
```
...
VmPeak:  3017336 kB
VmSize:  3017336 kB
...
```

**Comment by tboerger** [comment]
@Unknwon as the memory consumtion stuff pops up quite often you should consider to use a better git integration for go, as far as it can reduce the used memory in comparision to invoking the git cli.

**Comment by Unknwon** [comment]
@webhat thanks your info!

How long(mins) have you waited for memory to release?

**Comment by Unknwon** [comment]
@tboerger pops up for different things. And change another integration does not necessary that one both does better on this side, and the other side.

**Comment by tboerger** [comment]
@Unknwon only if it works better overall of course.

**Comment by webhat** [comment]
@Unknwon I didn't wait, I simply restarted. IMHO anything longer than a couple of seconds of downtime is too much.

**Comment by Unknwon** [comment]
@webhat no further information means cannot debug the problem. :flushed:

**Comment by webhat** [comment]
You should be able to reproduce it. Try this:
   1. Clone the linux kernel
   2. Remove the .git dir
   3. Push to gogs repository
   4. View the diff

**Comment by tboerger** [comment]
Ok, that is not a suprise... Maybe it makes sense to cut off the diff like github did it for large diffs.

**Comment by Unknwon** [comment]
> 2015/10/15 15:25:53 [W] Diff data too large

This line means reached 10000 lines, so Gogs gives up continuing parsing diff data.

**Comment by webhat** [comment]
The exception here is: `line[0] != '@' && strings.HasPrefix(line, DIFF_HEAD)`. AFAICS if the `case` statement [line 122](https://github.com/gogits/gogs/blob/c60d8bc069491295300969b185a47587dfdd03a6/models/git_diff.go#L122) or `if` [line 164](https://github.com/gogits/gogs/blob/c60d8bc069491295300969b185a47587dfdd03a6/models/git_diff.go#L164) are never hit it never breaks out of the loop.

**Comment by webhat** [comment]
I also think [this](https://github.com/gogits/gogs/blob/c60d8bc069491295300969b185a47587dfdd03a6/models/git_diff.go#L110-L113):

```
		if i == maxlines {
			isTooLong = true
			log.Warn("Diff data too large")
		}
```
should actually be this:
```
		if i >= maxlines {
			isTooLong = true
			log.Warn("Diff data too large")
		}
```

**Comment by Unknwon** [comment]
@webhat that is indeed a good catch! 

Let me take a look. :trollface:

**Comment by webhat** [comment]
:+1:

**Comment by Unknwon** [comment]
Hi @webhat !

I've pushed a fix to `develop` branch, please help test again!

**Comment by webhat** [comment]
Thank you, I'll run it tomorrow thanks!

**Comment by Unknwon** [comment]
:wink:

**Comment by webhat** [comment]
It works, thanks!

**Comment by Unknwon** [comment]
Awesome!
