### ISSUE TITLE
README.md doesn't support german umlauts 

### ISSUE THREAD

**Issue by Fchen48** [gogits/gogs#1792]
Actually the readme.md file doesn't support german umlauts like öäü, they are shown as �.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by focmb** [comment]
I have some README.md files with umlauts like ä and ö and this umlauts are shown in a right way. I wrote the README-md files with Atom Editor in Linux with UTF 8

**Comment by Fchen48** [comment]
Ok thanks, I changed my editor and now it's working fine.

**Comment by Unknwon** [comment]
@focmb :100:
