### ISSUE TITLE
Git Hooks: Update Hook

### ISSUE THREAD

**Issue by jnlin** [gogits/gogs#1793]
Hi,

I just installed gogs but found that I can not setup the "update" git hook.
Ref: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

Does gogs support the "update" hook or not? Thank you for your great work!

**Comment by Unknwon** [comment]
@jnlin Hi, because currently, Gogs uses Update hook itself, so customize it may cause problem.

**Comment by jnlin** [comment]
Hi,

Can gogs use a update hook chain? i.e. After running the customized update hook script, execute the update hook of gogs, or a reversed order.

You can take Gitolite for reference. Gitolite contains a directory named "update.secondary.d". We can put the update hook scripts in this directory and git will execute them while pushing.

Thank you!

**Comment by Unknwon** [comment]
Thanks your info!

Never knew about `update.secondary.d`, is it a git standard or Gitolite specific?

**Comment by jnlin** [comment]
I think `update.secondary.d` is not a git standard, but all git hosting software requires the `update` hook to work, so a chained hook is required if customized hook is supported.

**Comment by Unknwon** [comment]
Thanks, I'll take a look!

**Comment by Unknwon** [comment]
This will be solved by https://github.com/gogits/gogs/issues/1623

**Comment by Unknwon** [comment]
With latest `develop` branch, you're able to setup `update` hook via web UI.
