### ISSUE TITLE
Bad repository link with gogs behind reverse proxy

### ISSUE THREAD

**Issue by xoxys** [gogits/gogs#1794]
Hi,
i use gogs at localhost and use a reverse proxy to make gogs accable from the internet. Because i use gogs at a shared hoster its the only way... 

Because gogs runs on localhost i have bad links to the Repo:
SSH user@localhost:user/test.git
HTTP http://localhost:60000/user/test.git

It wourd be nice to have an option in configuration to modify the links. gogs runs on http but the reverse proxy redirect to https so it would be also nice to change http to https but only for the displayed link.

Thanks for your great work.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is the reverse proxy tool you use?

**Comment by xoxys** [comment]
I use Apache with this .htaccess
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{ENV:HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
RewriteRule (.*) http://localhost:61002/$1 [P]

**Comment by Unknwon** [comment]
I guess this is what you need: https://github.com/gogits/gogs/issues/1435#issuecomment-127536714

I don't know Apache, but certainly there is some problem with the configuration.

**Comment by JokerQyou** [comment]
In fact, the root URL for displaying can be set in `custom/conf/app.ini` in the `server` section.
```conf
[server]
ROO_URL = https://yourdomain.com/path/
```

And it will be used for displaying.

**Comment by xoxys** [comment]
Changin ROOT_URL in custom config do the trick for the http link but ssh is unchanged and displays localhost.

**Comment by JokerQyou** [comment]
`DOMAIN` option in `server` section will fix ssh link, I think.

**Comment by JokerQyou** [comment]
Set it like this:

```conf
DOMAIN = yourdomain.com
```

Mine is working fine.

**Comment by xoxys** [comment]
Thanks i tried it and it is working. But i think i missunderstood something. If i change DOMAIN to yourdomain.com is gogs now running on localhost which would mean 127.0.0.1 or on yourdomain.com which would be in my case a totally different szenario :-)

**Comment by JokerQyou** [comment]
Sorry I did not understand what you mean... I think the `DOMAIN` options is just for ssh link displaying.
The actual address and port gogs bind is set by `HTTP_ADDR` and `HTTP_PORT`.
`HTTP_ADDR` defaults to `127.0.0.1` or `0.0.0.0`.

**Comment by JokerQyou** [comment]
You can read more about these options in the doc, see [here]( http://gogs.io/docs/advanced/configuration_cheat_sheet )

**Comment by xoxys** [comment]
You are right this is what i mean :-) i have not seen the HTTP_ADDR option. Thanks again.

**Comment by evrial** [comment]
It's still an issue with Gogs, it has no clue about reverse proxy external port. [Screen](http://take.ms/IGImv)
```
[server]
PROTOCOL = http
HTTP_ADDR = localhost
HTTP_PORT = 3001
DOMAIN = evrial.com
ROOT_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/gogs/
```

**Comment by Unknwon** [comment]
Thanks @JokerQyou !

**Comment by kolesar-andras** [comment]
Issues referenced in issues have bad link if Gogs is behind a reverse proxy in a directory. Link does not have repository name. Looks like this:

    <a href="/git/username/issues/1" rel="nofollow">#1</a>

Directory name is git, username is gogs username, repository name is missing here. My setup:

    ROOT_URL = http://proxy.external.address/git

Apache rules:

    ProxyPass /git http://internal.address:3000
    ProxyPassReverse /git http://internal.address:3000

I have tried accessing the same page directly. Modified ROOT_URL:

    ROOT_URL = http://internal.address:3000

The referenced issue has correct link when I accessing the server directly:

    <a href="/git/username/repositoryname/issues/1" rel="nofollow">#1</a>

I think it's a bug.

**Comment by Unknwon** [comment]
@kolesar-andras thanks! It is indeed a bug, please rise another issue for this specific purpose.
