### ISSUE TITLE
Build error after package removals

### ISSUE THREAD

**Issue by variablenix** [gogits/gogs#1795]
Hello,

It seems the recent commit [932dbc](https://github.com/gogits/gogs/commit/932dbccb6738b2894e4faafce4f834ef6803efc6) has caused build errors.

`
../../klauspost/compress/flate/crc32_amd64.go:9:2: cannot find package "github.com/klauspost/cpuid" in any of:
	$HOME/builds/AUR/gogs-git/src/build/go/src/github.com/klauspost/cpuid (from $GOROOT)
	$HOME/builds/AUR/gogs-git/src/build/src/github.com/klauspost/cpuid (from $GOPATH)
../../klauspost/compress/gzip/gunzip.go:13:2: cannot find package "github.com/klauspost/crc32" in any of:
	$HOME/builds/AUR/gogs-git/src/build/go/src/github.com/klauspost/crc32 (from $GOROOT)
	$HOME/builds/AUR/gogs-git/src/build/src/github.com/klauspost/crc32 (from $GOPATH)
modules/setting/setting_memcache.go:10:2: cannot find package "github.com/macaron-contrib/cache/memcache" in any of:
	$HOME/builds/AUR/gogs-git/src/build/go/src/github.com/macaron-contrib/cache/memcache (from $GOROOT)
	$HOME/builds/AUR/gogs-git/src/build/src/github.com/macaron-contrib/cache/memcache (from $GOPATH)
modules/setting/setting_redis.go:10:2: cannot find package "github.com/macaron-contrib/cache/redis" in any of:
	$HOME/builds/AUR/gogs-git/src/build/go/src/github.com/macaron-contrib/cache/redis (from $GOROOT)
	$HOME/builds/AUR/gogs-git/src/build/src/github.com/macaron-contrib/cache/redis (from $GOPATH)
modules/setting/setting_redis.go:11:2: cannot find package "github.com/macaron-contrib/session/redis" in any of:
	$HOME/builds/AUR/gogs-git/src/build/go/src/github.com/macaron-contrib/session/redis (from $GOROOT)
	$HOME/builds/AUR/gogs-git/src/build/src/github.com/macaron-contrib/session/redis (from $GOPATH)
`

I think this is similar to issue [#1664] (https://github.com/gogits/gogs/issues/1664)

**Comment by Unknwon** [comment]
Hi,

How did you build?

**Comment by TheHowl** [comment]
Do a `go get`, then try to build gogs again.

**Comment by Unknwon** [comment]
Do `go get -u` would be better.

**Comment by variablenix** [comment]
`go get -u` returns
_package github.com/gogits/gogs: unable to parse output of git config remote.origin.url_

**Comment by Unknwon** [comment]
ping @fanningert

**Comment by fanningert** [comment]
I will check it
