### ISSUE TITLE
Git HTTP(S) auto-login doesn't work

### ISSUE THREAD

**Issue by evrial** [gogits/gogs#1796]
It seems to me Gogs unaware of user credentials which git sends from ~/.netrc
Correct me if I'm doing it wrong.

**Comment by Unknwon** [comment]
Thanks your feedback!

I don't know what `~/.netrc` is, so I think you are right.

Do you have any resources that shows how should server handle this?

**Comment by evrial** [comment]
Ok my mistake, after double check both git credential helper and .netrc auth working fine (it's simple protocol agnostic authfile). Please close :8ball:

**Comment by Unknwon** [comment]
:trollface:
