### ISSUE TITLE
Webhooks do not work

### ISSUE THREAD

**Issue by inktrap** [gogits/gogs#1797]
# Bug Description

First: thank you guys, gogs is awesome, fast like hell and i simply love it! A nice motivation to learn go as well. Really: good job!

My bug: Gogs-Webhook is not working for me. I did the following:

 - create a repository: ``test``
 - create a webhook for ``test``:
   - url: ``http://127.0.0.1:8080``
   - trigger on ``push``
   - send ``application/x-www-form-urlencoded``
 - run a [simple websever](https://snipt.net/raw/f8ef141069c3e7ac7e0134c6b58c25bf/?nice) that shows post requests on port ``8080`` (changed the linked script)
     - use ``curl -v --data "param1=value1&param2=value2" -k http://127.0.0.1:8080`` to test my server (works)
 - changed my cloned repository and push: ``echo " - $RANDOM" >> README.md && git commit -am "test" && git push``

## Expected Outcome

 - I would like to see a post-request, like documented
 - the date should not be the beginning of time, see below
 - additional request: I would like to be able to enter ip-adresses in the webhook config formular

## What actually happens

 - I get an error under recent deliveries for my commit and the request and response is ``N/A``:

~~~ 
73222ee5-cbd1-4ad0-a0a1-3494a2943fb6            1970-01-01 01:00:00 CET
N/A 
~~~

 - where does this show up in the logs?
 - i do not see anything in ``gogs.log``:

~~~
2015/10/17 18:04:45 [I] Log Mode: File(Info)
2015/10/17 18:04:45 [I] Redis Supported
2015/10/17 18:04:45 [I] Memcache Supported
2015/10/17 18:04:45 [I] Cache Service Enabled
2015/10/17 18:04:45 [I] Session Service Enabled
2015/10/17 18:04:45 [I] SQLite3 Supported
2015/10/17 18:04:45 [I] Run Mode: Production
2015/10/17 18:04:46 [I] Listen: http://0.0.0.0:3000

~~~
 - and the other logfiles are older or normal
 - program output from http-request

~~~
@400000005622a9f120e2c8fc [Macaron] [Static] Serving /fonts/fontawesome-webfont.woff
@400000005622a9f120e3af74 [Macaron] Completed /fonts/fontawesome-webfont.woff?v=4.4.0 304 Not Modified in 242.71µs
@400000005622a9f306b892cc [Macaron] Started GET /inktrap/test/settings/hooks/1 for 127.0.0.1
@400000005622a9f309d937a4 [Macaron] Completed /inktrap/test/settings/hooks/1 200 OK in 52.495194ms
@400000005622a9f30f2697ec [Macaron] Started GET /css/gogs.min.css?v=0.6.9.0903%20Beta for 127.0.0.1
@400000005622a9f30f29c46c [Macaron] [Static] Serving /css/gogs.min.css
@400000005622a9f30f2a6494 [Macaron] Completed /css/gogs.min.css?v=0.6.9.0903%20Beta 304 Not Modified in 265.388µs
@400000005622a9f30fb18e24 [Macaron] Started GET /js/gogs.js?v=0.6.9.0903%20Beta for 127.0.0.1
@400000005622a9f30fb5241c [Macaron] [Static] Serving /js/gogs.js
@400000005622a9f30fb7951c [Macaron] Completed /js/gogs.js?v=0.6.9.0903%20Beta 304 Not Modified in 357.432µs
~~~

# Versions

 - gogs version: gogs_v0.6.9
 - git version: 1.7.10.4

# System Type

 - uname: ``Linux nas 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux``
 - debian wheezy, omv (yes, I know it's old, but omv is pretty cool ;) …)

# Other information

 - I am using offline-mode
 - I changed the ``static_path``
 - I am running gogs with daemontools from djb as the user ``gogs``
 - I am running gogs behind nginx with https

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you try use `JSON` format and test again? In case it is a problem with ` application/x-www-form-urlencoded` format.

Also I recommend you upgrade to `v0.6.15` first so we're on the same page. :smile:

**Comment by inktrap** [comment]
The result is the same, I do not get a request and the log-message in the gui has no details.
I will update to ``v0.6.15`` tomorrow and report back :)

**Comment by Unknwon** [comment]
@inktrap OK. Thanks your info! I'll wait.

**Comment by inktrap** [comment]
Okay, I updated to ``Version: 0.6.15.0926 Beta``.
I tested json and form-data again. It gives me the following output:

 - [1-after-upgrading](http://bugs.inktrap.org/gogs/webhooks-1-status.png). Note that the timestamps for the webhooks that happened yesterday are now set to the date of the update/restart. The timestamps for the newly fired webhooks are still set to 0.
 - [2-json](http://bugs.inktrap.org/gogs/webhooks-2-json.png). A json request that got no response. Just to give you some details.
 - [3-status](http://bugs.inktrap.org/gogs/webhooks-3-status.png). I restarted the server and this is the result. Two webhooks went through.
 - [4-restart](http://bugs.inktrap.org/gogs/webhooks-4-restart.png). I send two webhooks again and restarted the server again and this is the result. Two other webhooks went through. Ignore the failing request in the middle, thats a server issue on my side. :)

So it appears that I have to restart gogs so it can pick up the calls.

**Comment by Unknwon** [comment]
> So it appears that I have to restart gogs so it can pick up the calls.

If this is the case, please see: https://github.com/gogits/gogs/issues/1703

**Comment by inktrap** [comment]
Yes, this solved my problem. I did not use placeholders.

For reference and other people that might have this problem: if you want to check your config, here are [examples](https://github.com/gogits/gogs/blob/master/conf/app.ini) and here is a [description](http://gogs.io/docs/advanced/configuration_cheat_sheet.html).

**Comment by Unknwon** [comment]
:clap:
