### ISSUE TITLE
Gogs web interface not working

### ISSUE THREAD

**Issue by ZlatyChlapec** [gogits/gogs#1798]
Hello, I am really lost, I googled for ages and I wasn't able to find anything helpful. So I installed gogs I configured it through web interface and it's actually working but when I try to access web interface I am left with just blank page and gogs gives me this errors: http://pastebin.com/MNfZ6iCw . I tried everything I could think of.

**Comment by Unknwon** [comment]
Thanks your feedback!

I think it is very obvious that:

> [Macaron] PANIC: session(start): mkdir data: permission denied

You didn't give Gogs correct permission with creating directories.

**Comment by ZlatyChlapec** [comment]
On web configuration page which I got first time I set certain user to use app so I guess same user needs permissions no? I tried to change all files from go folder on same user but it still didn't work. Gonna try look into it more.

**Comment by Unknwon** [comment]
Gogs creates `data` subdir at the same dir where Gogs binary is located, make sure Gogs has permission to create subdir at that directory.

**Comment by ZlatyChlapec** [comment]
Oh man thank you very much. It would be very useful if it would actually said on which files there are wrong permissions. Everything is working now.

**Comment by Unknwon** [comment]
> [Macaron] PANIC: session(start): mkdir data: permission denied

It actually said `data` subdir....

**Comment by ZlatyChlapec** [comment]
I am sorry but I didn't have any idea where to look for that dir from that line. All I got from it is that it failed to create folder data because of wrong permissions and right on next line there is something with totally different directory so I got pretty confused.

**Comment by Unknwon** [comment]
That is indeed confusing, I'll add to Troubleshooting of docs. :wink:
