### ISSUE TITLE
Export User Data

### ISSUE THREAD

**Issue by faggy** [gogits/gogs#1801]
Please add a button to export user data (issues, comments, etc.) into a machine readable format (JSON, XML, YAML, or whatever...)

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you give more clear definition of `user data`?

**Comment by faggy** [comment]
Mainly, let people download (in a machine readable format) all the issues of a repo.

**Comment by ChangePlaces** [comment]
I wouldn't find being able to download user data useful at all. I wouldn't be able to think of a use-case for this at all.

Being able to download all issues for a project would probably be pointless for me too as that's what browsing the site allows me to do.

**Comment by faggy** [comment]
@ChangePlaces your comment is completely pointless, as there are *many* reasons to let users export data. If this is a problem to develop, at least letting users export a repository's "Issues" would be good enough.

**Comment by ChangePlaces** [comment]
@Faggy my comment is stating how I'd find this feature irrelevant. That's my... "feedback". Why would a user want to export a repository's issues? Why would a site maintainer want to allow that?

**Comment by faggy** [comment]
> Why would a user want to export a repository's issues? Why would a site maintainer want to allow that?

Either you're trolling or these kind of questions aren't worth answering to anyway

**Comment by ChangePlaces** [comment]
Still sounds like a useless idea to me. You haven't been able to answer with at least one reason and only given bad attitude when asked why. :-1:

**Comment by tboerger** [comment]
@faggy what do you want to do with this data? As long as there is no counterpart to import this kind of data it is pretty useless. If you want to have it as some kind of backup you need some way to restore. Just to export for no reason is just a waste of time and developer resources.

Real feature requests explain one or more use cases...

**Comment by kellpossible** [comment]
@tboerger maybe @faggy just wants some peace of mind, knowing that they can jump into using this platform without worrying about getting locked in so to speak (an easy way out if things don't work out in the end)?

**Comment by ChangePlaces** [comment]
That's a good suggestion, but that would still need an import in the other git repository management system to be imported into so this feature would still be useless without that. The data is in a database, manually doing a sql dump isn't difficult and writing an import script wouldn't be difficult. We're coders after all!

**Comment by Unknwon** [comment]
SQL dump is machine readable format and its widely adapted after all.
