### ISSUE TITLE
500 when opening forked repo while base repo has been deleted

### ISSUE THREAD

**Issue by michaelPf85** [gogits/gogs#1813]
I was toying around with mirrors and forks and decided to clean up some unneeded repositories.
So I deleted a "base" repository that was mirroring some existing github repo, since I cannot push to a mirror.
Now when I want to access the "forked" repo I have an 500 error page and this shows up in the log file : `2015/10/21 16:04:08 [...s/middleware/repo.go:297 func·009()] [E] GetBaseRepo: repository does not exist [id: 3, uid: 0, name: ]`
I kind of expected that and don't know which would be a proper behavior : preventing deletion of a forked repository, transforming forks into "standalone" repo when the base is deleted ?
Thanks for you help. For the time being I'll see what I can do in the database to keep on using my repo.

**Comment by michaelPf85** [comment]
Just updated repository table : is_fork=0, fork_id=0, it now works OK.

**Comment by Unknwon** [comment]
Thanks your feedback!

Which version of Gogs are you suing?

**Comment by michaelPf85** [comment]
Did I dare to forget mentioning it ! The latest released one : Version: 0.6.5.0815 Beta

**Comment by Unknwon** [comment]
No, the latest release is `v0.6.15` :trollface:

**Comment by michaelPf85** [comment]
It kind of looked the same to me, I'm upgrading right now :astonished:

**Comment by Unknwon** [comment]
Haha, no, no no, it's not so true. :D

**Comment by michaelPf85** [comment]
I was so sure I had already upgraded... Turns out I did not create the symlink properly and the older version was sill running instead of the new one! I had again misread "5" for "15".

It works properly now, so i'm closing this issue. My forked repo now turns into a standalone repo. Thanks and sorry for the mistake !

**Comment by Unknwon** [comment]
LOL.
