### ISSUE TITLE
Issues: Fixes works only one time

### ISSUE THREAD

**Issue by de-live-gdev** [gogits/gogs#1816]
I noticed that a commit only will close one issue in gogs when the message contains multiple ids -->

    "Updated to v1.11, fixes #1 #2"
only closes Issue #1  
Is that the right behaviour?   
Should it be one of those? :
* `fixes #1 fixes #2` 
* `fixes #1,#2`  

Personally I don't really use Issue Management on Gogs, but maybe Community has some ideas about / needs this.

**Comment by Unknwon** [comment]
> Is that the right behaviour?

Yes it is.

**Comment by Unknwon** [comment]
I think assume `#2` has same action as `#1` is not consistent. e.g. `Fixed #1, #2 more on the way`
