### ISSUE TITLE
 error: failed to write new configuration file /home/gogs/.gitconfig.lock

### ISSUE THREAD

**Issue by tubia** [gogits/gogs#1817]
Hi,
this is a strange issue that I encountered after upgrading to the last release.
It happens when I launch
```
sudo -u gogs ./gogs web
```
This is the error I got:
```
2015/10/22 17:35:41 [T] Custom path: /var/www/html/gogs/custom
2015/10/22 17:35:41 [T] Log path: /var/www/html/gogs/log
2015/10/22 17:35:41 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/10/22 17:35:41 [I] Log Mode: Console(Trace)
2015/10/22 17:35:41 [I] Redis Enabled
2015/10/22 17:35:41 [I] Memcache Enabled
2015/10/22 17:35:41 [I] Cache Service Enabled
2015/10/22 17:35:41 [I] Session Service Enabled
2015/10/22 17:35:41 [I] Mail Service Enabled
2015/10/22 17:35:41 [I] Register Mail Service Enabled
2015/10/22 17:35:41 [I] Notify Mail Service Enabled
2015/10/22 17:35:41 [repo.go:113 NewRepoContext()] [E] Fail to set git user.name(exit status 4): error: failed to write new configuration file /home/gogs/.gitconfig.lock
```
Checking permissions on `/home/gogs/` everything it's fine and belongs to `gogs` user.

Also, downgrading to my previous backup didn't changed the situation so I'm actually blocked.

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you try delete `.gitconfig.lock` file and start Gogs again?

**Comment by tubia** [comment]
Hi @Unknwon,
I'm sorry to have bothered here without checking everything on my system: it was an error due to my storage, which was full.  
With more disk space free everything works :)

**Comment by Unknwon** [comment]
:trollface: LOL, no problem.

**Comment by findSaif** [comment]
Deleting the .gitconfig.lock file did for me. The source of the lock file was Visual Studio in my case.

**Comment by skumar1122** [comment]
Hi @findSaif , I am seeing same error today, where do I check this .gitconfig.lock file ?
