### ISSUE TITLE
Error 1054: Unknown column 'pull_id' in 'where clause'

### ISSUE THREAD

**Issue by rvalle** [gogits/gogs#1818]
Just installed GOGs and I am testing around.
I created a few test repos, and everything seems to work fine, but creating a full request.

I am getting this error, and I have no idea what could be related to.
I have installed the package and reported version is: 0.6.16.1018 Beta

**Comment by Unknwon** [comment]
Thanks your feedback!

I just pushed a quick fix to `master` branch, can you help test again?

**Comment by rvalle** [comment]
wow! I did and apt-get update, and there it was a new package waiting.
It is now working, I can create pull requests.
thanks!

**Comment by Unknwon** [comment]
:100:
