### ISSUE TITLE
Commits not showing up due to date parsing error

### ISSUE THREAD

**Issue by xplodwild** [gogits/gogs#1819]
Hello! During importing some of my repositories, I get a few errors in serv.log:

2015/10/23 10:53:50 [...ts/gogs/cmd/serve.go:212 runServ()] [E] Failed to update: Find CommitsBefore erro: parsing time "odific <> 1319194510 +0200" as "Mon Jan _2 15:04:05 2006 -0700": cannot parse "odific <> 1319194510 +0200" as "Mon"
2015/10/23 10:54:10 [...ts/gogs/cmd/serve.go:212 runServ()] [E] Failed to update: Find CommitsBefore erro: parsing time "odific <> 1319194510 +0200" as "Mon Jan _2 15:04:05 2006 -0700": cannot parse "odific <> 1319194510 +0200" as "Mon"

The result is that the commits/branches aren't appearing in the Web UI.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by xplodwild** [comment]
Tried the latest stable (0.6.x), as well as master. Worked it around by commenting the if error != nil return error in the commits date parsing file

**Comment by Unknwon** [comment]
> commenting the if error != nil return error in the commits date parsing file

Never an option to comment error checking.

Let me see what is different from supported date format. :trollface:

**Comment by xplodwild** [comment]
Hence why I mentioned it as a "workaround" :P

**Comment by Unknwon** [comment]
Can you do `git cat-file -p` in any repository on your machine and post the results here?

**Comment by xplodwild** [comment]
Here's the output for `git cat-file -p HEAD` :

```
git cat-file -p HEAD
tree 2fae3b323b9c7c30c6952bd58bac60f17ae6c3b8
parent 88117c81ddce47ff7e86a8a90d14162155b9e19c
author Xxxx Xxxxx <xxxx@xxxxx.fr> 1445412825 +0200
committer Xxxxx Xxxxxx <xxxxx@xxxxx.fr> 1445412862 +0200

Form > submit name avoid empty submit

(cherry picked from commit 6cf180732af92ba16e4aea8bbb68a2e5eb7fc62f)
```

**Comment by xplodwild** [comment]
FWIW, some of our commits have an invalid mail due to misconfigured interns (such as Intern <intern@macbook-intern.(none)>), could that lead to the parsing problem?

**Comment by Unknwon** [comment]
@xplodwild thanks!

I think the problem is Gogs doesn't think you're using timestamp, I'll look into it see why is that.

**Comment by Unknwon** [comment]
It is so strange that I directly unit test `Intern <intern@macbook-intern.(none)> 1445412825 +0200` does not have any problem...

**Comment by Unknwon** [comment]
Can you recall what is the full information of `odific <> 1319194510 +0200`?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
