### ISSUE TITLE
Issue closing to appear in dashboard feed

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1821]
When closing an issue - can it appear in the dashboard feed please - "User a closed issue #whatever" etc

I think it'd be very useful!

**Comment by Unknwon** [comment]
Please update to latest `develop` branch or test on https://try.gogs.io.

**Comment by ChangePlaces** [comment]
good stuff! love the little icon as well. 

however, if a comment is added along with the close ("comment and close") instead of it taking two lines in the dashboard, could it be one line: "user foo commented and closed issue 123" with the comment below?

**Comment by Unknwon** [comment]
> however, if a comment is added along with the close ("comment and close") instead of it taking two lines in the dashboard, could it be one line: "user foo commented and closed issue 123" with the comment below?

Based on how close issue works, no...

**Comment by Unknwon** [comment]
Close as implemented.
