### ISSUE TITLE
Tabbing when editing a comment / issue

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1824]
When editing a comment or issue, if I tab, I'd like to be taken to the save button so I can then press spacebar and have the issue / comment update. However this doesn't happen. Tabbing takes me to the next comment save button instead! (0.6.9)

**Comment by Unknwon** [comment]
Thanks your feedback!

But I'm not quite sure which button is which, can you make a screenshot to illustrate?

**Comment by ChangePlaces** [comment]
![editing-comment](https://cloud.githubusercontent.com/assets/302031/10694477/43944488-7996-11e5-8924-e843ce200254.png)

When I press on the edit pen, I see this. Once typing inside this box, pressing tab doesn't take me to the 'save' button for this comment!

**Comment by Unknwon** [comment]
I see what is the problem now. :sweat_smile:

**Comment by ChangePlaces** [comment]
it's the same for the issue edit as well.

**Comment by Unknwon** [comment]
You should now be able to use tab switch to buttons and press `enter` key to trigger click event on `develop` and https://try.gogs.io .
