### ISSUE TITLE
Refer to an issue from another repo

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1825]
If hash issue number is for the current project, how do I refer to an issue from another project?

(Great work on Gogs btw, just added a few of my small suggestions and issues)

**Comment by Unknwon** [comment]
Currently not possible...

**Comment by ChangePlaces** [comment]
May I propose that if `#123` is used, could something like: `repo-key-name#123` be used to refer to another repo? I ask because I work with repo's that connect together and have issues relating to each other.

**Comment by Unknwon** [comment]
The format should be `username/reponame#123`, which is same as GitHub.

**Comment by ChangePlaces** [comment]
sounds great - thanks!

**Comment by Unknwon** [comment]
Just realized this is duplicated to https://github.com/gogits/gogs/issues/360
