### ISSUE TITLE
The secondary navbar is too thick?

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1827]
![secondary-navbar](https://cloud.githubusercontent.com/assets/302031/10691031/e294fc58-797d-11e5-810c-62a0567ce000.png)

I think this bar below the top blue bar could do with being thinner - the information it shows is relatively unimportant, and occupies too much vertical space. (0.6.9)

**Comment by Unknwon** [comment]
The page in your screenshot is still the old theme, which will be changed to the following one:

![image](https://cloud.githubusercontent.com/assets/2946214/10694426/06e4bd30-796c-11e5-9d02-3b73e4ec1c33.png)

**Comment by ChangePlaces** [comment]
Looks better, but still looks a little too thick. The padding is a little much as the content for that page is pushed down somewhat unnecessary!

**Comment by Unknwon** [comment]
> The padding is a little much as the content for that page is pushed down somewhat unnecessary!

I think it is pretty necessary to look comfortable as right now.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
