### ISSUE TITLE
"Drop files here" box is too damn thick!

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1828]
This is what an issue screen looks like for me on my laptop.

I would consider the "create issue" button is more important than the box for dragging files as attachments. Could the box be made much thinner as it's more of a secondary feature than a primary issue feature? Or, maybe just have the dragbox on the left-hand side?

![issue-screen](https://cloud.githubusercontent.com/assets/302031/10691112/93522110-797e-11e5-9aab-e61206b26897.png)

**Comment by Unknwon** [comment]
Actually I'm pretty OK which it... what is the resolution of your screen?

PS: https://github.com/gogits/gogs#browser-support

**Comment by ChangePlaces** [comment]
In over 200 issues, I think I personally have used the drop-box once, maybe twice. I think its size should be made a little smaller! Would it just be possible to drop files onto the comment text box, removing the need for that area altogether?

**Comment by Unknwon** [comment]
I found out why:

the size is manipulated by dropzone.js and I don't know how to change it.

**Comment by ChangePlaces** [comment]
Just had a quick look in the dropzone.css file

`.dropzone {
  min-height: 150px;`

That's probably the culprit! You should be able to overwrite that with another css declaration. Though it appears depending on the type of file dropped, the height then changes!

**Comment by Unknwon** [comment]
Hmm... simply change `min-height` or `height` does not work.. :sweat:

**Comment by ChangePlaces** [comment]
Mhh, could you contain the dropzone in a div of say width 200px, and float left? then add a clear both after the buttons?

**Comment by Unknwon** [comment]
>   div of say width 200px, and float left

What does this done?

**Comment by ChangePlaces** [comment]
A `float:left` will float the dropbox div to the left of the buttons. As a float takes the element outside the box model, you'd then have to `clear:both` after the buttons so the container knows where the bottom of the dropbox is.

**Comment by Unknwon** [comment]
It does change the width but I think height is the problem here...

**Comment by ChangePlaces** [comment]
Implementing dropzones is relatively simple in jquery, and has native support in HTML 5 I believe. MAybe something custom could be done?

**Comment by ChubbyNinja** [comment]
We use the drop-box fairly often - it's very useful for people to visualise the error (as you have in this issue)

Personally, I don't see the issue with how big it is at the moment

**Comment by Unknwon** [comment]
If you mean configuration, there is a something that you can customized the dropzone area, but never got it to work... so I use the default one.

**Comment by Unknwon** [comment]
Close as `wontfix`.
