### ISSUE TITLE
Remove "Pull Request" option

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1829]
As a developer, I use Gogs for my own personal projects because it's small, light and fast. I don't have any pull requests for projects so it would be nice, if in the options somewhere, there's an option to remove the feature or just removal of the button at least.

**Comment by BurakDev** [comment]
+1

**Comment by faggy** [comment]
? Why don't you just avoid clicking the button?!

**Comment by JohnMaguire** [comment]
I'm with @faggy on this one. It seems like settings UI clutter to add a checkbox for that. I'm not sure the maintenance or UI clutter of this is worth removing that tiny little button.

I don't know of any other Git management tools that offer the ability to disable pull requests.

**Comment by ChangePlaces** [comment]
Settings ui clutter? You mean one checkbox is clutter to you? UI clutter? Uhm, this is about removing useless clutter from a single-dev perspective. Tiny button? it's kinda big.

why should gogs emulate other git management tools?

Or, I could make a suggestion as I'm sure other people will find it useful.

**Comment by tboerger** [comment]
There are for sure projects that want to disable issues or pull requests

**Comment by Unknwon** [comment]
Disable issues/wiki/pull request , etc was on the todo actually.

**Comment by JohnMaguire** [comment]
> Settings ui clutter? You mean one checkbox is clutter to you? UI clutter?

No need to be hostile. One option certainly isn't, the problem is it's a slippery slope. This blog post can explain it better than I can: http://swreflections.blogspot.com/2014/08/feature-toggles-are-one-of-worst-kinds.html

In any case, that was just my feelings on it. :)

**Comment by ChangePlaces** [comment]
Sorry, I didn't mean to sound hostile!

**Comment by JohnMaguire** [comment]
:beers:

**Comment by Unknwon** [comment]
OK, now possible to disable wiki/issues/pull requests on `develop` branch, test here: https://try.gogs.io/unknwon/Issue-1829
