### ISSUE TITLE
"close and comment" should be "comment and close"

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1831]
I think it would make more sense (as a single action) to comment on an issue then close it. At the moment, the "close and comment" button does exactly that - it closes, then comments. This can be hard to tell if the comment was made AFTER the close, and is suggesting a re-open without actually reading the comment. Whereas, if the comment followed by a close is the last comment, it's easy to see there's no commentary after the close! (0.6.9)

**Comment by TheHowl** [comment]
Actually, on my local gogs instance it comments and THEN closes. So perhaps we should just change it to "Comment and reopen/close"

**Comment by ChangePlaces** [comment]
@TheHowl What version are you using?

**Comment by TheHowl** [comment]
0.6.16.1017

**Comment by ChangePlaces** [comment]
Interesting, I wonder if that's been changed between 0.6.9 and 0.6.16

I tried to find something in the issues to no avail

**Comment by Unknwon** [comment]
> Interesting, I wonder if that's been changed between 0.6.9 and 0.6.16

Yes, behavior was changed.

**Comment by ChangePlaces** [comment]
In that case, let's ignore this then! Thanks

**Comment by ChangePlaces** [comment]
Actually, @TheHowl is right. Maybe the wording should be changed to "Comment And Close"

**Comment by Unknwon** [comment]
Yeah, agree.
