### ISSUE TITLE
Bug on user link in issues

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#1832]
On issues list and issue detail, user link is wrong on a white theme.

**Comment by Unknwon** [comment]
Can you give an example?

**Comment by joubertredrat** [comment]
On listing issues, on user link is wrong, correct is http://domain/user but is display //user
On issue detail is same issue

**Comment by Unknwon** [comment]
Listing issues on dashboard or repository?

**Comment by joubertredrat** [comment]
I'm trying to discover if problem is on one of this lines:

https://github.com/gogits/gogs/blob/master/templates/repo/issue/list.tmpl#L112
https://github.com/gogits/gogs/blob/master/routers/repo/issue.go#L149
https://github.com/gogits/gogs/blob/master/models/issue.go#L620

**Comment by joubertredrat** [comment]
@Unknwon on repository issues list and issue view

**Comment by joubertredrat** [comment]
The problem is on this line:
https://github.com/gogits/gogs/blob/master/templates/repo/issue/list.tmpl#L112
I'm trying to understand now how to convert this to html

**Comment by joubertredrat** [comment]
This is a problem with pt-br translation. Fixed on Crowdin.

**Comment by Unknwon** [comment]
Just a backup: will update and close at some point.

**Comment by Unknwon** [comment]
> This is a problem with pt-br translation. Fixed on Crowdin.

I didn't see a change on pr-br?

**Comment by Unknwon** [comment]
Ping

**Comment by joubertredrat** [comment]
@Unknwon 
You suggested 3 translations
Oct 23, 2015 (1 day ago) - Details
Translation	File	Time
Milestones	Base Locale	17:43
Milestones	Base Locale	17:43
%[1]s foi aberto por <a href="%[2]s">%[3]s</a>	Base Locale	17:42

**Comment by Unknwon** [comment]
OK, I can see it now.

**Comment by Unknwon** [comment]
Close as fixed.
