### ISSUE TITLE
Add user problem

### ISSUE THREAD

**Issue by lucevers** [gogits/gogs#1837]
1) Installed gogs via docker and a host volume.
    Defined a user  example user = James

2) Remove docker container and Host volume

3) Install gogs via docker and a container data volume.

-> Add user James and I got a remark that user James already exists!
    How is this possible, after a new install ?  (Browser cash data ?)

**Comment by ogarcia** [comment]
Are you completely SURE that you removed **ALL** data from volume?
And. What data backend are you using? If you are using MySQL or PostgreSQL. Are you completely SURE that you removed the database?

**Comment by Unknwon** [comment]
@ogarcia has mentioned some, plus https://github.com/gogits/gogs/blob/master/CONTRIBUTING.md#bug-report

**Comment by lucevers** [comment]
I'm using SQLite. 
The database dir name (./data) (host volume) was moved to ./dataold, but even if I didn't moved the /data in the Host file it may not happen.
Because I made for my second datastore a DOCKER volume and not a host volume.
The second installation was also started again from zero. The old docker container was stopped and removed.

**Comment by Unknwon** [comment]
> Add user James and I got a remark that user James already exists!

Can you given detailed steps about how you first and second time create an account?

**Comment by lucevers** [comment]
First time I didn't made an administrator login, so I made a usr by the
register button.
Second time , I configured an admin user. So then John was made via the
admin Panel -> Users -> create New Account.
There was only the admin user on the list, but when I introduced John (not
in the user Mange Panel), the system made a warning that the user already
exist.

 The problem was solved via the Dashboard -> Delete all inactive accounts
-> run.

 Because the database is on another place I think it could be the browser
cache?

**Comment by Unknwon** [comment]
> Because the database is on another place I think it could be the browser cache?

No, it's not the browser cache, the old database is being used from what I understand of Gogs.

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
