### ISSUE TITLE
hooks/update: Permission denied

### ISSUE THREAD

**Issue by Refactoring** [gogits/gogs#1840]
我使用管理员账户A，创建了一个项目，并推送了几次数据。 之后我又创建了新组织1，将项目管理权移交至组织1， 现在我使用账户A无法推送数据至仓库(本地库推送地址已经修改为新的组织地址)。 
我使用Docker hub上的gogs/gogs，版本: 0.6.16.1023 Beta

推送错误日志如下：
```log
remote: hooks/update: line 2: /root/gogs/gogs: Permission denied
remote: error: hook declined to update refs/heads/master
To http://xxxxx.git
! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'http://xxx.git'
```

**Comment by Refactoring** [comment]
我在try.gogs.io上按如上步骤，测试没有问题...

**Comment by Unknwon** [comment]
> remote: hooks/update: line 2: /root/gogs/gogs: Permission denied

You server has permission issue with executing git hooks, please check that...

**Comment by Refactoring** [comment]
我是使用Docker拉取了你的库gogs/gogs安装的，默认的账户密码是？  或者ssh_host_rsa_key的密码？

**Comment by Unknwon** [comment]
How you read https://github.com/gogits/gogs/tree/master/docker ?

**Comment by Refactoring** [comment]
Repository Root Path: keep it as default value /home/git/gogs-repositories...
这个路径不能改....

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/tree/master/docker#usage

> Directory /var/gogs keeps Git repositories and Gogs data:

**Comment by Unknwon** [comment]
BTW, what is your system?

**Comment by Refactoring** [comment]
CentOS 7 
我完全按照https://github.com/gogits/gogs/tree/master/docker 的说明操作。 只不过你建议的数据路径/var/gogs,我替换成另外一个路径了.

**Comment by Unknwon** [comment]
Hmmm... I may found the problem, shouldn't the hook/update tries to execute `/app/gogs/gogs` (https://github.com/gogits/gogs/blob/master/docker%2Fs6%2Fgogs%2Fsetup#L13) instead of `/root/gogs/gogs`?

Have you ran Gogs before without Docker?

**Comment by Unknwon** [comment]
cc @0rax

**Comment by Refactoring** [comment]
耽误你时间了，感谢不厌其烦的帮助我。 
我先把项目放到创建者这边推送代码吧. 找个时间我自己编译个Docker库. 

刚还发现个问题. 这个问题在客户端提示失败，Gogs服务器上却有提交信息， 但在Git仓库中找不到提交记录.
![qq 20151026143629](https://cloud.githubusercontent.com/assets/451129/10722786/02c12100-7bef-11e5-8dbc-25916c89b361.png)

**Comment by Unknwon** [comment]
Please do not ignore my question:

> Have you ran Gogs before without Docker?

Otherwise this thread will be dead and closed which does not help you at all.

**Comment by Refactoring** [comment]
的确是在运行Docker前，直接在系统中安装过gogs，路径也正好和我问题中的/root/gogs/gogs匹配，不过我觉得这不应该，也不可能影响我Docker中的Gogs运行吧。 

我下午把库删除，在组织中创建了版本库，将本地库同步进去，可以提交。

**Comment by Unknwon** [comment]
When Gogs binary path is changes, you need to run following two things in admin dashboard:

![image](https://cloud.githubusercontent.com/assets/2946214/10730690/d50cdbea-7bc7-11e5-83aa-126ab9b5afa1.png)

**Comment by Refactoring** [comment]
执行上面两个操作，好像可以了。我重新操作了一遍，没有我之前描述的问题了。
感谢.

**Comment by Unknwon** [comment]
:trollface:

**Comment by wisebeer** [comment]
> When Gogs binary path is changes, you need to run following two things in admin dashboard:
> 
> ![image](https://cloud.githubusercontent.com/assets/2946214/10730690/d50cdbea-7bc7-11e5-83aa-126ab9b5afa1.png)

It works for me. Thanks a lot!
