### ISSUE TITLE
question: running locally

### ISSUE THREAD

**Issue by gedw99** [gogits/gogs#1842]
I am looking for something (preferably written in go) that is  a local web based git dashboard.
- see status of each branch
- have GUI to help me with merging and branching.
- only be dependent on standard .git directory. This is important aspect.

I used to use a nodejs one but its too slow :)
https://github.com/FredrikNoren/ungit

Can i easily run Gogs locally for this purpose ?

**Comment by Unknwon** [comment]
Hi there,

what does this line exactly mean?

> see status of each branch

**Comment by gedw99** [comment]
in ungit you can see each branch in relation to each other as a tree.

**Comment by Unknwon** [comment]
Gogs is not exactly same purpose for ungit, but you can try on https://try.gogs.io/

**Comment by ChangePlaces** [comment]
in the first 30s of the ungit introduction video, it states git has a "pretty steep learning curve"! I find the branching display fairly useless, even on gitlab. It looks pretty, but I think has no real use unless you have HUGE repo's with hundreds of commits and many branches.

**Comment by Unknwon** [comment]
From what I understand from the intro video, Ungit is a git client, not a git hosting server like Gogs.

**Comment by gedw99** [comment]
All of that is true.
And yes ungit allows abuse.

Best I close this
