### ISSUE TITLE
Creating mirrors via API

### ISSUE THREAD

**Issue by rubenv** [gogits/gogs#1843]
I was looking into creating mirrors via the Go client, but that doesn't seem to be supported yet.

Is this simply a matter of adding the missing fields to the request (I'll make a pull request), or will this be difficult to add?

**Comment by Unknwon** [comment]
Hi, please see https://github.com/gogits/go-gogs-client/wiki/Repositories#migrate

**Comment by rubenv** [comment]
Oh, that's fantastic, I'll see what I can do!

**Comment by rubenv** [comment]
Fixed in gogits/go-gogs-client#9
