### ISSUE TITLE
Reverse Proxy with nginx under a sub directory

### ISSUE THREAD

**Issue by fanningert** [gogits/gogs#1844]
*GOGS-Version:* 0.6.15

I used the description in the faq. http://gogs.io/docs/intro/faqs#set-up-with-suburl
Everything is working perfect. The only problem is that no Js, CSS or Image is accessible (Get 404 error).
When I use the gogs server directly, everything is visible.
I use the nginx proxy as HTTPS->HTTP proxy.

Here the config out of my nginx config file.
```
  location /gogs/ {
    proxy_pass http://localhost:3000/;
  }
```

I also tested with other configurations.
```
  location /gogs/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Fix the  ^ ^ It appears that your reverse proxy set up is broken" error.
    proxy_pass          http://localhost:3000/;
    proxy_read_timeout  90;

    proxy_redirect      http://localhost:3000/ https://sub.domain.com/gogs/;
  }
```

Regards
Thomas

**Comment by Unknwon** [comment]
Hi, you need to change Gogs config `ROOT_URL` as well.

**Comment by fanningert** [comment]
I changed the ROOT_URL to `https://sub.domain.com/gogs/`. But I get also the same problem.

Currently I tested GOGS without ReverseProxy but with ROOT_URL = `https://sub.domain.com:3000/gogs/`. But I get the same problem.

**Comment by Unknwon** [comment]
Can you open web console see what request URL is actually sent for static resouces.

**Comment by fanningert** [comment]
Here is the screenshot. Looks like gogs has some problem with the routing.
![screenshot_2015-10-26_20-09-14](https://cloud.githubusercontent.com/assets/365219/10739637/e517cae4-7c1d-11e5-9cee-970e61862447.png)

Here also the request url of one of the js files
```
http://192.168.1.11:3000/gogs/js/jquery-1.11.3.min.js
```

**Comment by Unknwon** [comment]
just make sure that you know ROOT_URL is under server section

**Comment by Unknwon** [comment]
Routing is giving 404 means your sub-path is not configed right.

**Comment by fanningert** [comment]
Here the config part.
ROOT_URL is under SERVER section.

```
[server]
PROTOCOL = http
DOMAIN = vienna.fanninger.at
ROOT_URL = http://192.168.1.11:3000/gogs/
```

**Comment by Unknwon** [comment]
Hmm.... I can't remember exactly why because I think `192.168.1.11:3000` or `vienna.fanninger.at` should only have one of those.

**Comment by fanningert** [comment]
Ok,
I replaced the domain with '192.168.1.11', but I also get the same problem.

**Comment by Unknwon** [comment]
You did restart Gogs, right?

**Comment by fanningert** [comment]
Yes, :)

**Comment by Unknwon** [comment]
OK, I know the problem, if you use sub-path, you must use reverse proxy, simply type a sub-path with directly access won't work.

**Comment by fanningert** [comment]
Ok, then back to reverse proxy.

**Comment by Unknwon** [comment]
Then, you need to access web UI by `vienna.fanninger.at`, and set this value to config as well, don't use `192.168.1.11:3000` anymore.

**Comment by fanningert** [comment]
Thanks,
I found the problem. In my nginx config was a extra part for the serving of static content. I commented the part out, everything is looking fine.

Thanks for your help.

**Comment by Unknwon** [comment]
:trollface:

**Comment by fanningert** [comment]
I will create a custom rule for the static content and add the info to the docs.

**Comment by changsijay** [comment]
@fanningert I got the same issue with you that I have below section for my wordpress service

```
        location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
              expires max;
              log_not_found off;
        }
```

do you know how to make this part work with gogs?
Although after comment out it works fine.
