### ISSUE TITLE
Problem with creating a pull request

### ISSUE THREAD

**Issue by bioven** [gogits/gogs#1850]
Hey guys,

i have a problem with creating a pull request. 
I don't know how i create one. Maybe i'm just dumb and/or did something wrong in the installation part. 

But there is no button to create a pull request even when i'm in the menu for the pull request. There is only a button to create an issue. 

I assume this could be a bug, but i'm no really sure.
Here is picture of my case: http://imgur.com/iyQoyDY

I'm using the following version of gogs.
Gogs-Version: 0.6.16.1022 Beta

I hope you can help me and tell me how to do it.

Greetings, 
Ben

**Comment by andreynering** [comment]
To create a pull request you have to fork the repository and click in this button:

![image](https://cloud.githubusercontent.com/assets/7011819/10805070/5afc7562-7db2-11e5-9b99-a1f9cce9fdda.png)

**Comment by Unknwon** [comment]
@andreynering said what I'm going to say :D

**Comment by bioven** [comment]
Thanks guys,

i feel pretty dumb now for asking this question. xP

But i get it now.

**Comment by Unknwon** [comment]
:trollface:

**Comment by Unknwon** [comment]
Close as fixed...
