### ISSUE TITLE
Docker hostnames for postgres

### ISSUE THREAD

**Issue by ryanwr** [gogits/gogs#1851]
Hello,

Under the new docker build system post 0.6.15 I can't get hostnames to work for the postgres host.

I'm using docker-compose to create a postgres and a gogs instance and referring to the postgres host by name results in "dial tcp: lookup postgres on 8.8.8.8:53: no such host", however using the internal docker ip works fine. Using a hostname in 0.6.15 works exactly as intended.

The only thing I can think of is the s6 supervisor messing with something.

Thanks for the help

**Comment by tboerger** [comment]
As the new container starts socat you just need to link the postgres container and use localhost or 127.0.0.1 for the postgres server.

**Comment by tboerger** [comment]
And bedide that, what gets printed on this command?

docker exec -ti gogs-container env | sort

**Comment by ryanwr** [comment]
@tboerger Your first suggest worked perfectly thanks!

For reference, is there a way to use hostnames and disable socat? If I needed to use two containers exposing the same port for example?

**Comment by tboerger** [comment]
There is some socat detection that binds only a single port. Totally disable it doesnt work. But if linked correctly it should be still possible to connect by linkname.

**Comment by uranium62** [comment]
I have a similar problem
When I use:

`$ docker exec -it gogs bash 
`$ ping <linkdb> 

ping goes...

**Comment by AdamYang121** [comment]
Yes, like @uranium62 said, I run the command like this:
**docker exec -ti my_docker_demo_postgres_1 cat "/etc/hosts"**
I get:
......
**172.17.0.3	2b1eef9162f5**

Then I use this IP as my host in database config file, it works!
