### ISSUE TITLE
Show issue title for comment news feeds

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1854]
it could go just under the header line:

**username commented on issue organisation/project-name#221**
*Need to process the input using sql queries directly*
"Comment text goes here"

This is because with so many issues, it can become a little confusing what issue number refers to what issue!

**Comment by Unknwon** [comment]
Hi, you now can test this on `develop` branch and https://try.gogs.io

**Comment by ChangePlaces** [comment]
Tested and seems to work fine. However, when you create a new issue, on the dashboard, it just displays the title where the comment body goes for this issue - could this same style in this issue be applied to new issues?

e.g.:

Username opened issue org/projname#44 - Something is broken
A short few lines of the body of the issue here...

**Comment by Unknwon** [comment]
Make sense..

**Comment by Unknwon** [comment]
Here we go again! https://try.gogs.io/
