### ISSUE TITLE
Migrating repo to an organization when I am watching the repo

### ISSUE THREAD

**Issue by carlosfvp** [gogits/gogs#1860]
Hi,

I am here to report that I can't transfer a repo to an organization when I am currently watching the repo.

Look https://github.com/gogits/gogs/blob/c60d8bc069491295300969b185a47587dfdd03a6/models/org.go 

line 504.

I am not sure what that for-loop is for but, when I "unwatched" the repo I was able to transfer it to an organization.

**Comment by Unknwon** [comment]
What is the exact error you have?

**Comment by carlosfvp** [comment]
a 500 HTTP error and the line wich shows the error is 504.

**Comment by Unknwon** [comment]
Thanks but you're still not answering my other questions...

**Comment by carlosfvp** [comment]
This is the error printed on the log.

2015/10/29 16:20:02 [...ters/repo/setting.go:141 SettingsPost()] [E] TransferOwnership: add to owner team: watchRepo: UNIQUE constraint failed: watch.user_id, watch.repo_id

And the webpage only showed a big 500 http error.

**Comment by Unknwon** [comment]
Thanks but you're still not answering my other questions...

>  And your version, database and system?

**Comment by carlosfvp** [comment]
Sorry It's been a long day. I haven't read the whole question.

gogs v0.6.15 (lastest release)
sqlite
windows server 2008

**Comment by Unknwon** [comment]
OK, thanks again!

It indeed is a bug with SQLite3 in 0.6.15 (https://github.com/gogits/gogs/blob/v0.6.15/models%2Frepo.go#L1588) which has been fixed in `master` branch code (https://github.com/gogits/gogs/blob/master/models%2Frepo.go#L1661).

**Comment by carlosfvp** [comment]
Oh amazing, I've been using only the binaries. Sorry anyway and good job. This project is amazing. I will give a try anytime soon and send some pull requests.

**Comment by Unknwon** [comment]
:trollface:

**Comment by Unknwon** [comment]
Close as `you need to update Gogs in next release`...
