### ISSUE TITLE
Ubuntu upstart scripts

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#1867]
Currently there are 3 upstart-scripts installed when using the package from packager.io

gogs.conf
```
start on started mysql
stop on runlevel [06]
```
gogs-web.conf
```
start on starting gogs
stop on stopping gogs
```
gogs-web-1.conf
```
start on starting gogs-web
stop on stopping gogs-web
respawn

env PORT=6000

exec gogs run web >> /var/log/gogs/web-1.log 2>&1
```

These could all be in one file

```
start on started mysql
stop on runlevel [06]
respawn

exec gogs run web >> /var/log/gogs/gogs-web.log 2>&1
```

also the ```env PORT=6000``` is not needed.

**Comment by tboerger** [comment]
This could not work. Packager.io works with foreman, and this got the option to scale up the web workers, so the port is required and the different upstart files are intended, just look at https://github.com/ddollar/foreman.

So this is a won't fix.

**Comment by Unknwon** [comment]
cc @crohr :sailboat:

**Comment by crohr** [comment]
Yes this is the intended behaviour. For other apps you could also have more than just the web process (e.g. a background worker with scale=2) so that explains why the init scripts are separated.

**Comment by stonerl** [comment]
Ok, I understand.
