### ISSUE TITLE
Html tags not being closed across issue comments

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1873]
In a previous comment I have `<strike>foo bar</strik>` (deliberate typo)

Then I save the comment and that strike continues across the design, including comment header details, and the next comment body all the way down the page.

Is there any way broken tags can be sorted? Maybe HTML tidy?

**Comment by Unknwon** [comment]
Test <strike>foo bar</strik>

**Comment by Unknwon** [comment]
Looks like GitHub has some tools fix this.

**Comment by tboerger** [comment]
I'm pretty sure github tries to fix bad html. An alternative should be stripping of invalid tags.

**Comment by Unknwon** [comment]
Haha, fixed.
