### ISSUE TITLE
Corruption of a ticket content when closing ticket

### ISSUE THREAD

**Issue by zorun** [gogits/gogs#1875]
Hi,

When closing a ticket, the first comment of this ticket was corrupted, and has now the same content as the closing content.

The affected ticket is here: https://code.ffdn.org/FFDN/celutz/issues/4 .  Note that the first and last comment are identical, but this was not the case before closing the ticket (the first comment described the needed feature).

The version is 0.6.16.1002 Beta, with MySQL backend, on Debian wheezy.

Is this a known issue?  I couldn't find any (open or closed) ticket related to this.

Thanks!

**Comment by ChangePlaces** [comment]
First, the connection to your site is untrusted - I guess the HTTPS certificate is out of date or shared with other sites.

Secondly, I've seen this issue before and it revolves around when the user submits a comment then presses the back and presses submit again.

**Comment by Unknwon** [comment]
Thanks your feedback1

This is a bug has been fixed in `master` branch.

**Comment by Unknwon** [comment]
I can't remember/find which issue was it exactly...

**Comment by Unknwon** [comment]
OK, here we go: https://github.com/gogits/gogs/issues/1830#issuecomment-150556772
