### ISSUE TITLE
Issue paginator is not showing last page of issues when issue count changes

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1876]
If you open the issues queue with say 21 issues, you'll see paginator with numbers 1,2,3. If you close one of those issues (in a separate tab), then click the "3" on the paginator to open the last page of issues, it takes you to page 2, with no issues showing. Clicking the "2" on the paginator doesn't show the issues either. You have to go to a different page then click on the last paginator number.

The issue seems to be around the fact that is the paginator number is higher than the amount of issues, it should ignore the number, and just show the last page of issues.

**Comment by Unknwon** [comment]
Thanks your feedback!

But the idea I was taken from GitHub: https://github.com/gogits/gogs/issues?page=100&q=is%3Aissue+is%3Aopen

**Comment by Unknwon** [comment]
You can now test on `develop` or https://try.gogs.io

**Comment by ChangePlaces** [comment]
Just tested and works as expected! Thanks!

**Comment by Unknwon** [comment]
:trollface:
