### ISSUE TITLE
go get sub-pkg

### ISSUE THREAD

**Issue by webhat** [gogits/gogs#1878]
To be able to use go imports with remote services, like this:

```
import "example.org/repo.git/foo/bar"
```

The repo needs to contain a `<meta>` tag which describes the repo to go:

```
<meta name="go-import" content="import-prefix vcs repo-root">
```

https://golang.org/cmd/go/#hdr-Remote_import_paths

**Comment by webhat** [comment]
This is something we would like, so I would also be open to sending a PR to fix this.

**Comment by tboerger** [comment]
@webhat you already know about https://github.com/gogits/gogs/blob/master/templates/ng/base/head.tmpl#L11-L14?

**Comment by tboerger** [comment]
The source of https://try.gogs.io/tboerger/go-foobar?go-get=1 will display:

```html
<meta name="go-import" content="try.gogs.io/tboerger/go-foobar git https://try.gogs.io/tboerger/go-foobar.git">
<meta name="go-source" content="try.gogs.io/tboerger/go-foobar _ https:/try.gogs.io/tboerger/go-foobar/src/master{/dir} https:/try.gogs.io/tboerger/go-foobar/src/master{/dir}/{file}#L{line}">		
```

**Comment by tboerger** [comment]
@Unknwon But it fails to get it:

```
# go get try.gogs.io/tboerger/go-foobar
can't load package: package try.gogs.io/tboerger/go-foobar: no buildable Go source files in /home/tboerger/Projects/golang/src/try.gogs.io/tboerger/go-foobar
```

**Comment by tboerger** [comment]
So, I can verify that it definitly already works. Just try `go get try.gogs.io/tboerger/go-foobar`.

**Comment by TheHowl** [comment]
I think the real problem OP has is that they can't import specific folders from the source.

**Comment by Unknwon** [comment]
@TheHowl oh right, I think you made the point. @webhat ?

**Comment by tboerger** [comment]
Ok, that's true

```
# go get try.gogs.io/tboerger/go-foobar/subpkg
package try.gogs.io/tboerger/go-foobar/subpkg: unrecognized import path "try.gogs.io/tboerger/go-foobar/subpkg"
```

**Comment by tboerger** [comment]
But I can confirm that `go get try.gogs.io/tboerger/go-foobar.git/subpkg` works. So maybe we should get rid of the `.git` part.

**Comment by webhat** [comment]
Apologies, my original example show not have the `.git` prefix.

```
import "example.org/repo/foo/bar"
```

**Comment by Unknwon** [comment]
> I specifically meant import and not go get

Import is same as go get from my perspective.

**Comment by tboerger** [comment]
an import path must be go getable as far as i know.

**Comment by hazrd** [comment]
I am seeing different error output. Create a repo, add a main.go file. Run:
```
go get -v -u "git.example.com/user/testrepo"
```
See error:
```
Fetching https://git.example.com/user/testrepo?go-get=1
https fetch failed.
Fetching http://git.example.com/user/testrepo?go-get=1
Parsing meta tags from http://git.example.com/user/testrepo?go-get=1 (status code 404)
import "git.example.com/user/testrepo": parse http://git.example.com/user/testrepo?go-get=1: no go-import meta tags
package git.example.com/user/testrepo: unrecognized import path "git.example.com/user/testrepo"
```

Funny this is written in Go but you can't ```go get```! (yet... :+1: ) Can't wait!

**Comment by Unknwon** [comment]
404 means not found, isn't that obvious? go get does not support private repo

**Comment by hazrd** [comment]
Ah thanks!

**Comment by jsevilleja** [comment]
I can't clone public subpkgs:

```
# go get -v git.example.org/user/pkg/subpkg
Fetching pkgs://git.example.org/user/pkg/subpkg?go-get=1
Parsing meta tags from pkgs://git.example.org/user/pkg/subpkg?go-get=1 (status code 404)
package git.example.org/user/pkg/subpkg: unrecognized import path "git.example.org/user/pkg/subpkg" (parse pkgs://git.example.org/user/pkg/subpkg?go-get=1: no go-import meta tags)
```

**Comment by MehSha** [comment]
same here, is there any fix in the sight?

**Comment by hochhaus** [comment]
@Unknwon This issue is a show stopper when using the bazel build tool with external dependencies to Gogs hosted Go sub-packages. Any pointers for how to fix this?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by hochhaus** [comment]
Thanks @Unknwon. I built from `develop`, tested and can confirm that this change correctly resolves my issue.
