### ISSUE TITLE
Panic when init settings

### ISSUE THREAD

**Issue by techzilla** [gogits/gogs#1879]
Public keys are not being accepted, even  the ones that worked before recent update.

I've just re-compiled the master, thus I believe the SSH key check may be the cause.

**Comment by techzilla** [comment]
O wait, i'll check my configs, was reading
https://github.com/gogits/gogs/pull/1871

**Comment by techzilla** [comment]
OK, nothing is indeed working, copying the config to custom results in an error,

2015/11/02 13:11:35 [T] Custom path: /opt/gogs/custom
2015/11/02 13:11:35 [T] Log path: /opt/gogs/log
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/gogits/gogs/modules/setting.newService()
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/modules/setting/setting.go:457 +0x50c
github.com/gogits/gogs/modules/setting.NewServices()
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/modules/setting/setting.go:640 +0x14
github.com/gogits/gogs/routers.NewServices()
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/routers/install.go:46 +0x14
github.com/gogits/gogs/routers.GlobalInit()
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/routers/install.go:56 +0x1fa
github.com/gogits/gogs/cmd.runWeb(0xc8202b60f0)
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/cmd/web.go:178 +0xb8
github.com/codegangsta/cli.Command.Run(0xf04b50, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf89970, 0x15, 0x1037920, ...)
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc820296600, 0xc820072000, 0x2, 0x2, 0x0, 0x0)
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/gogs.go:40 +0x35c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820061c80)
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
	/home/jbecker/.go/src/github.com/gogits/gogs/.vendor/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

**Comment by techzilla** [comment]
I started building older commits, until I got one far enough to work, 

When I finally got did a reset to 0fbb8c8826771e92e890fb1c72b356d3e62c7b01, I was able to add my user's ssh-key

**Comment by Unknwon** [comment]
Based on the panic message, it's caused by #1871 , I'm working on it.

**Comment by Unknwon** [comment]
Hi, I just pushed fix, can you rebuild `master` and test again?

**Comment by techzilla** [comment]
keys can be uploaded now, this problem looks resolved.
