### ISSUE TITLE
Cannot add ssh key

### ISSUE THREAD

**Issue by lukasdietrich** [gogits/gogs#1880]
I just wanted to try gogs and installed it using **docker** (gogs version **0.6.20.1102**).
Whenever I try to add an ssh key the following error occurs:

`Sorry, we're not able to verify your SSH key: unrecognized public key type: RSA)`

On the <http://try.gogs.io> demo the same key works.

**Comment by Unknwon** [comment]
Hi there, fix has been pushed to `master` branch, and updated http://try.gogs.io as well.

**Comment by lukasdietrich** [comment]
Hi, I pulled the latest version and can confirm it works now.
Thanks for the quick fix!

**Comment by Unknwon** [comment]
:trollface:
