### ISSUE TITLE
Install from package fails (CentOS 7)

### ISSUE THREAD

**Issue by depl0y** [gogits/gogs#1881]
I am trying to install Gogs on my CentOS 7 machine, following this guide:

https://packager.io/gh/pkgr/gogs/install?bid=305#centos-7-gogs

Once I try to `sudo yum install gogs`, I get the following error:

```
Running transaction
  Installing : gogs-0.6.15-1446509350.8eb4c31.centos7.x86_64                                1/1
/var/tmp/rpm-tmp.AxAXv9: line 62: /tmp/tmp.gUDOpe0lpR: Permission denied
warning: %post(gogs-0.6.15-1446509350.8eb4c31.centos7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package gogs-0.6.15-1446509350.8eb4c31.centos7.x86_64
  Verifying  : gogs-0.6.15-1446509350.8eb4c31.centos7.x86_64                                1/1
Installed:
  gogs.x86_64 0:0.6.15-1446509350.8eb4c31.centos7
```

Once the installation is done, gogs isn't running and I am unable to start the service so I am guessing some stuff is going wrong. The file that is referenced in the error message is empty.

**Comment by depl0y** [comment]
Ok, changing my TMPDIR variable to /var/tmp and then installing fixed this problem.

**Comment by Unknwon** [comment]
:trollface:
