### ISSUE TITLE
500 When transfering repo ownership

### ISSUE THREAD

**Issue by techzilla** [gogits/gogs#1882]
500 When transferring repo ownership,
The only thing I found in the xorm.log was, 

    [xorm] [info]  2015/11/03 12:43:20.215774 [sql] ROLL BACK

and in the gogs.log,

    2015/11/03 12:43:20 [...ters/repo/setting.go:141 SettingsPost()] [E] TransferOwnership: GetOwnerTeam: Team does not exist

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/blob/master/CONTRIBUTING.md#bug-report

If you're using SQLite3 and 0.6.15, this is a fixed problem in `master`.

**Comment by techzilla** [comment]
Nope, Using Sqlite3 on the newest master, as of 15 min ago rebuild.

**Comment by Unknwon** [comment]
What is the version show bottom of the page?

**Comment by techzilla** [comment]
Version: 0.6.22.1103 Beta

**Comment by Unknwon** [comment]
OK, can you try `master` again?

**Comment by techzilla** [comment]
2015/11/03 13:37:08 [...ters/repo/setting.go:141 SettingsPost()] [E] TransferOwnership: GetOwnerTeam: Team does not exist

**Comment by Unknwon** [comment]
If you did update and recompile the Gogs, the error message has been changed:

> https://github.com/gogits/gogs/commit/8411b50f5d4e3b30d7d601612ee2aa5e4921c968#diff-d4e2553a87eb8b329efd7335f028903cR953

`GetOwnerTeam` -> `getOwnerTeam`

**Comment by techzilla** [comment]
ill do a full clean, and recompile

**Comment by techzilla** [comment]
"Please make sure that the repository name you entered is correct.", was reported on the page.

**Comment by Unknwon** [comment]
Cool! Thanks your confirmation.
