### ISSUE TITLE
Installation issues Debian jessie

### ISSUE THREAD

**Issue by daald** [gogits/gogs#1883]
When trying to get gogs ready for a first test, I had the following problems:

System: Debian jessie; documentation from https://packager.io/gh/pkgr/gogs/install?bid=307#debian-8-gogs

1) On a freshly installed lxc container, the following **extra packages** have to be installed (should go to documentation):

    apt-get install apt-transport-https wget sudo

2) There is **no service startup script**.
I found https://github.com/gogits/gogs/issues/433 which refers to a systemd service file which calls /opt/gogs/docker/start.sh (this should go into the package)

3) The script contains the **wrong path** `/app/gogs/docker/`, the application is in `/opt/gogs/docker/` (this should be fixed in the package)

4) after fixing 3, the script runs with the following **error**:

    /opt/gogs/docker/start.sh: 39: exec: /usr/bin/s6-svscan: not found

Until now, I was unable to find an executable called s6-svscan. So I have no idea how I can make gogs ready.

5) I would prefer a setup using **sqlite** as described in the comment in the install documentation.

**Comment by Unknwon** [comment]
Thanks your feedback!

> 1) On a freshly installed lxc container, the following extra packages have to be installed (should go to documentation):
> 5) I would prefer a setup using sqlite as described in the comment in the install documentation.

cc @crohr 

> 2) There is no service startup script.
I found #433 which refers to a systemd service file which calls /opt/gogs/docker/start.sh (this should go into the package)

The scripts under `docker` is only used for Docker, and which comment exactly pointed out uses Docker one?

> 3) The script contains the wrong path /app/gogs/docker/, the application is in /opt/gogs/docker/ (this should be fixed in the package)
> 4) after fixing 3, the script runs with the following error:

The scripts under `docker` is only used for Docker, inside Docker, it is `/app/gogs/gogs`. cc @0rax

**Comment by crohr** [comment]
@daald within a docker container you probably want your entrypoint to be `gogs run web`. You can also `gogs scale web=1` to setup an init script, but I don't think that would work in docker.

**Comment by daald** [comment]
If the script start.sh is for docker only, it shouldn't be packed into this .deb. Everyone using this .deb (doesn't matter if real machine, docker, lxc, virtualbox, lxc etc.) will have the files placed in `/opt/gogs/docker/` because inside the .deb all files are located under this path. A script pointing to another path should not be part of this .deb

@crohr I will try these commands ASAP

@Unknwon 
> The scripts under docker is only used for Docker, and which comment exactly pointed out uses Docker one?

Sorry, not sure if I understood your question correctly. https://github.com/gogits/gogs/issues/433 mentions a `start.sh` file, so I did a `find` over all installed files and found this one.

**Comment by Unknwon** [comment]
> Sorry, not sure if I understood your question correctly. #433 mentions a start.sh file, so I did a find over all installed files and found this one.

It does not mattar at this point, still, the scripts under docker is only used for Docker.

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by daald** [comment]
@Unknwon Just a little demonstration:

    me$ cat Dockerfile
    from debian:jessie
    
    run apt-get update \
     && apt-get install -y sudo wget apt-transport-https \
     && apt-get clean
    run wget -qO - https://deb.packager.io/key | sudo apt-key add - \
     && echo "deb https://deb.packager.io/gh/pkgr/gogs jessie pkgr" | sudo tee /etc/apt/sources.list.d/gogs.list \
     && sudo apt-get update \
     && sudo apt-get install -y gogs

    me$ docker build .
    Sending build context to Docker daemon 2.048 kB
    Sending build context to Docker daemon 
    Step 0 : FROM debian:jessie
     ---> 6845b83c79fb
    Step 1 : RUN apt-get update  && apt-get install -y sudo wget apt-transport-https  && apt-get clean
     ---> Using cache
     ---> 7ed4cc329dc4
    Step 2 : RUN wget -qO - https://deb.packager.io/key | sudo apt-key add -  && echo "deb https://deb.packager.io/gh/pkgr/gogs jessie pkgr" | sudo tee /etc/apt/sources.list.d/gogs.list  && sudo apt-get update  && sudo apt-get install -y gogs
     ---> Running in b10d76f396d8
    OK
    deb https://deb.packager.io/gh/pkgr/gogs jessie pkgr
    Ign http://httpredir.debian.org jessie InRelease
    Hit http://httpredir.debian.org jessie-updates InRelease
    Hit http://security.debian.org jessie/updates InRelease
    Hit http://httpredir.debian.org jessie Release.gpg
    Get:1 http://httpredir.debian.org jessie Release [148 kB]
    Get:2 http://security.debian.org jessie/updates/main amd64 Packages [189 kB]
    Get:3 http://httpredir.debian.org jessie-updates/main amd64 Packages [3619 B]
    Get:4 https://deb.packager.io jessie InRelease
    Ign https://deb.packager.io jessie InRelease
    Get:5 http://httpredir.debian.org jessie/main amd64 Packages [9035 kB]
    Get:6 https://deb.packager.io jessie Release.gpg [473 B]
    Get:7 https://deb.packager.io jessie Release [3712 B]
    Get:8 https://deb.packager.io jessie/pkgr amd64 Packages [12.9 kB]
    Fetched 9393 kB in 36s (256 kB/s)
    Reading package lists...
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following extra packages will be installed:
      git git-man less libalgorithm-c3-perl libarchive-extract-perl libbsd0
      libcgi-fast-perl libcgi-pm-perl libclass-c3-perl libclass-c3-xs-perl
      libcpan-meta-perl libdata-optlist-perl libdata-section-perl libedit2
      liberror-perl libexpat1 libfcgi-perl libgdbm3 liblog-message-perl
      liblog-message-simple-perl libmodule-build-perl libmodule-pluggable-perl
      libmodule-signature-perl libmro-compat-perl libpackage-constants-perl
      libparams-util-perl libpod-latex-perl libpod-readme-perl libpopt0 libpq5
      libreadline5 libregexp-common-perl libsoftware-license-perl libsqlite3-0
      libsub-exporter-perl libsub-install-perl libterm-ui-perl
      libtext-soundex-perl libtext-template-perl libx11-6 libx11-data libxau6
      libxcb1 libxdmcp6 libxext6 libxml2 libxmuu1 libxslt1.1 mysql-common
      openssh-client patch perl perl-modules rename rsync sgml-base xauth xml-core
    Suggested packages:
      gettext-base git-daemon-run git-daemon-sysvinit git-doc git-el git-email
      git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn ssh-askpass
      libpam-ssh keychain monkeysphere ed diffutils-doc perl-doc
      libterm-readline-gnu-perl libterm-readline-perl-perl make libb-lint-perl
      libcpanplus-dist-build-perl libcpanplus-perl libfile-checktree-perl
      libobject-accessor-perl openssh-server sgml-base-doc debhelper
    Recommended packages:
      ssh-client libarchive-tar-perl
    The following NEW packages will be installed:
      git git-man gogs less libalgorithm-c3-perl libarchive-extract-perl libbsd0
      libcgi-fast-perl libcgi-pm-perl libclass-c3-perl libclass-c3-xs-perl
      libcpan-meta-perl libdata-optlist-perl libdata-section-perl libedit2
      liberror-perl libexpat1 libfcgi-perl libgdbm3 liblog-message-perl
      liblog-message-simple-perl libmodule-build-perl libmodule-pluggable-perl
      libmodule-signature-perl libmro-compat-perl libpackage-constants-perl
      libparams-util-perl libpod-latex-perl libpod-readme-perl libpopt0 libpq5
      libreadline5 libregexp-common-perl libsoftware-license-perl libsqlite3-0
      libsub-exporter-perl libsub-install-perl libterm-ui-perl
      libtext-soundex-perl libtext-template-perl libx11-6 libx11-data libxau6
      libxcb1 libxdmcp6 libxext6 libxml2 libxmuu1 libxslt1.1 mysql-common
      openssh-client patch perl perl-modules rename rsync sgml-base xauth xml-core
    0 upgraded, 59 newly installed, 0 to remove and 0 not upgraded.
    Need to get 30.8 MB of archives.
    After this operation, 112 MB of additional disk space will be used.
    Get:1 ...
    Unpacking ...
    [...]
    gogs: unrecognized service
    Processing triggers for libc-bin (2.19-18+deb8u1) ...
    Processing triggers for systemd (215-17+deb8u2) ...
    Processing triggers for sgml-base (1.26+nmu4) ...
     ---> 7674cfde6bd3
    Removing intermediate container b10d76f396d8
    Successfully built 7674cfde6bd3

    me$ docker run 7674cfde6bd3 ls -d /app/gogs/ /opt/gogs/
    ls: cannot access /app/gogs/: No such file or directory
    /opt/gogs/

    me$ docker run 7674cfde6bd3 /opt/gogs/docker/start.sh
    find: `/app/gogs/docker/s6/': No such file or directory
    /opt/gogs/docker/start.sh: 55: exec: /usr/bin/s6-svscan: not found

    me$ 

What I want to show: This is probably the simplest possible way to install the .deb (containing the start.sh) using docker. You see: the file is useless because dependencies and path are wrong. I assume, in your docker scenario you use another source than the .deb, and install the files to another place.

But for this package, including docker-relevant files to a place different than `/usr/share/doc/gogs/examples` is as useless as including Fedora-relevant files or a Windows batchfile into a Debian package

@crohr Thx this helped. Is there an official init.d file for gogs?

**Comment by Unknwon** [comment]
@daald you should use `go get xxx` instead of relying on packager.io for build Docker images.

**Comment by tboerger** [comment]
The packager.io files are just for normal system installation. The files from the docker folder are just for the official gogs docker container.

**Comment by daald** [comment]
For my server I use a normal installation. This was only a demonstration. You should not pack the full source repo inside a .deb package but only the files which are really needed.

`dpkg -L gogs | grep docker` should not show the following result because there is *no* use-case for them:

    /opt/gogs/.dockerignore
    /opt/gogs/docker-compose.yml
    /opt/gogs/docker
    /opt/gogs/docker/README.md
    /opt/gogs/docker/s6
    /opt/gogs/docker/s6/openssh
    /opt/gogs/docker/s6/openssh/run
    /opt/gogs/docker/s6/openssh/setup
    /opt/gogs/docker/s6/syslogd
    /opt/gogs/docker/s6/syslogd/run
    /opt/gogs/docker/s6/gogs
    /opt/gogs/docker/s6/gogs/run
    /opt/gogs/docker/s6/gogs/setup
    /opt/gogs/docker/s6/.s6-svscan
    /opt/gogs/docker/s6/.s6-svscan/finish
    /opt/gogs/docker/build.sh
    /opt/gogs/docker/sshd_config
    /opt/gogs/docker/start.sh

**Comment by panticz** [comment]
Hi, it would by helpful if you add on the [Installation instructions page](https://packager.io/gh/pkgr/gogs/install?bid=440) in the Debian/Ubuntu section this command
> apt-get install apt-transport-https
before "# setup mysql server and database" otherwise the https repository can not be used.
