### ISSUE TITLE
Question: SSH on Windows

### ISSUE THREAD

**Issue by pecigonzalo** [gogits/gogs#1884]
Can we use SSH feature when HOSTING gogs on a windows server?
I could not find any other topics really clear on this.

Thanks

**Comment by Unknwon** [comment]
Hi, there: http://gogs.io/docs/installation

> A functioning SSH server (ignore this if you’re only using HTTP/HTTPS)
Recommend Cygwin OpenSSH or Copssh under Windows.

**Comment by pecigonzalo** [comment]
Great that clarifies it.
I would recommend not having the titles be content pages on some and not other sections, and adding that to the windows section.

Thanks a lot.

**Comment by Unknwon** [comment]
:trollface:
