### ISSUE TITLE
今天用包管理更新了gogs,然后出错了，重装也不行

### ISSUE THREAD

**Issue by sunjian2009** [gogits/gogs#1886]
点开项目如下：
template: repo/view_list:15:81: executing "repo/view_list" at <.LastCommit.Id>: Id is not a field of struct type interface {}

**Comment by Unknwon** [comment]
Thanks! Can you retry `master` branch?

**Comment by sunjian2009** [comment]
ok,thanks

**Comment by AdrianVerde** [comment]
Had the same error a couple hours ago, now it's fixed.
