### ISSUE TITLE
Ask password for SSH

### ISSUE THREAD

**Issue by cartmanchen** [gogits/gogs#1887]
如题

**Comment by Unknwon** [comment]
Please check your SSH auth.log.

**Comment by cartmanchen** [comment]
git clone ...
fatal: unrecognized command '/var/gogs/gogs serv key-4 --config='/var/gogs/custom/conf/app.ini''
fatal: The remote end hung up unexpectedly

**Comment by Unknwon** [comment]
Please dump your `~/.ssh/authorized_keys` file here.

**Comment by cartmanchen** [comment]
command="/var/gogs/gogs serv key-3 --config='/var/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeAMM0T7FVALCcBkf3X9jI6ps
I2HxDYWy8ijTTn5AER/3B7anl2TS7Tw/331FghKGlu/Y9nFpUynphUu/PEbaRnQIb8iU5ySzlJWdPODI7YEL8wi2bQwV8jH5OFfL+I70VX6pnUnImzmsOGSHJG+uLYcFkY6qV6xX02JcUK7sAxpHNo47ZDGvqEV7Pk4mEx+Mr2Fn36CPjlaHuJsz0Ovm1AHyLPThTrRhqVMK
ujwUYGxX4uqyfZYQjMDTTxWVP56DNOgxxC2u7KFuMC+3SFrr/3FWd0ChMlFhSa6JtpaP9zdJchyboMRtU/TDWAoz+foIZ5YRN2aqNOeKuUyyUchzj Administrator@YOS-20150914TX10
command="/var/gogs/gogs serv key-4 --config='/var/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwu6U98tzqH8oQgOCEpf7WGUPY2z
Wbr2JNRjfE6vQaxX5tqpAWpkvMnadhLlwT6MCrvsQ1iBbFGvbH/FjuENz7ibQ/r1GNIS0S9ky0NS4LvZq0ltP5LwfjOOYfsk013pmkWAUXsXrlHWQALvOKL81yXpneb1d4zz5ijzbAC1wdg7Nio7t/DB62hj1AxnlD9jfjPLb+twe1Vjv7nyZml9qbTASQwFJdzq6nYkUp8F
RD8Q6thKLsZ8NGSJCYWnXdZ4aQ5FJe50qfgk6OePcQLplEUhCRlrLLlIX4WIs44/0raojllenrsdDfzcj39K6gWyK2H0mDORXqwXoWlakX8kJYw== root@vultr.guest
command="/var/gogs/gogs serv key-1 --config='/var/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeAMM0T7FVALCcBkf3X9jI6ps
I2HxDYWy8ijTTn5AER/3B7anl2TS7Tw/331FghKGlu/Y9nFpUynphUu/PEbaRnQIb8iU5ySzlJWdPODI7YEL8wi2bQwV8jH5OFfL+I70VX6pnUnImzmsOGSHJG+uLYcFkY6qV6xX02JcUK7sAxpHNo47ZDGvqEV7Pk4mEx+Mr2Fn36CPjlaHuJsz0Ovm1AHyLPThTrRhqVMK
ujwUYGxX4uqyfZYQjMDTTxWVP56DNOgxxC2u7KFuMC+3SFrr/3FWd0ChMlFhSa6JtpaP9zdJchyboMRtU/TDWAoz+foIZ5YRN2aqNOeKuUyyUchzj Administrator@YOS-20150914TX10
command="/var/gogs/gogs serv key-2 --config='/var/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwu6U98tzqH8oQgOCEpf7WGUPY2z
Wbr2JNRjfE6vQaxX5tqpAWpkvMnadhLlwT6MCrvsQ1iBbFGvbH/FjuENz7ibQ/r1GNIS0S9ky0NS4LvZq0ltP5LwfjOOYfsk013pmkWAUXsXrlHWQALvOKL81yXpneb1d4zz5ijzbAC1wdg7Nio7t/DB62hj1AxnlD9jfjPLb+twe1Vjv7nyZml9qbTASQwFJdzq6nYkUp8F
RD8Q6thKLsZ8NGSJCYWnXdZ4aQ5FJe50qfgk6OePcQLplEUhCRlrLLlIX4WIs44/0raojllenrsdDfzcj39K6gWyK2H0mDORXqwXoWlakX8kJYw== root@vultr.guest

**Comment by cartmanchen** [comment]
my sshd port is 28044

**Comment by Unknwon** [comment]
Thanks. Please execute following task in admin dashboard and see if your `~/.ssh/authorized_keys` remains the same:

![image](https://cloud.githubusercontent.com/assets/2946214/10932756/786a440a-82a1-11e5-9289-e7a8ec20b430.png)

And what is your Gogs version?

**Comment by cartmanchen** [comment]
![image](https://cloud.githubusercontent.com/assets/8955461/10932793/a798f952-830e-11e5-940c-ca24cfd28932.png)

**Comment by cartmanchen** [comment]
v0.6.15

**Comment by Unknwon** [comment]
Now try `git clone` again.

**Comment by cartmanchen** [comment]
fatal: unrecognized command '/var/gogs/gogs serv key-2 --config='/var/gogs/custom/conf/app.ini''
fatal: The remote end hung up unexpectedly

**Comment by cartmanchen** [comment]
gogs运行用户：
`useradd -s /usr/bin/git-shell gogs`

**Comment by Unknwon** [comment]
> useradd -s /usr/bin/git-shell gogs

Based on the error, I think the way you start Gogs is not working.

**Comment by Unknwon** [comment]
May be helpful: http://stackoverflow.com/questions/14460967/custom-commands-with-git-shell

**Comment by cartmanchen** [comment]
I replace `/usr/bin/git-shell` to `/bin/bash`,than it works!

**Comment by Unknwon** [comment]
Cool! :trollface:

**Comment by charliegreen** [comment]
I just had the same problem, and this does fix it, but it also makes it so you can login as gogs with a password and get a bash shell. Is there a fix that doesn't cause this problem? Thanks!
