### ISSUE TITLE
use docker install and cannot visit repo on web

### ISSUE THREAD

**Issue by silentred** [gogits/gogs#1888]
use docker to install gogs/gogs, and run as follow.

`docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs`

After I pushed local code to new repository, the following error occured no matter the repo was created or imported from other repo.

template: repo/view_list:15:81: executing "repo/view_list" at <.LastCommit.Id>: Id is not a field of struct type interface {}

**Comment by Unknwon** [comment]
Please update again... just fixed minutes ago.

**Comment by silentred** [comment]
Thanks. It is solved.

**Comment by Unknwon** [comment]
:trollface:
