### ISSUE TITLE
Unable to login with local admin account after update

### ISSUE THREAD

**Issue by samlcharreyron** [gogits/gogs#1892]
In the updates following 0.6.5, I can no longer login using my admin account. The account is a local account of type 0. Instead, it tries to log in via LDAP, which fails. I see this in the code:

    func (source *LoginSource) BeforeSet(colName string, val xorm.Cell) {
	switch colName {
	case "type":
		switch LoginType((*val).(int64)) {
		case LDAP, DLDAP:
			source.Cfg = new(LDAPConfig)
		case SMTP:
			source.Cfg = new(SMTPConfig)
		case PAM:
			source.Cfg = new(PAMConfig)
		default:
			panic("unrecognized login source type: " + com.ToStr(*val))
		}
	}
    }

Since the type is 0 for local accounts, it tries LDAP. I'm not too sure how to fix this other than reverting back to 0.6.5

**Comment by Unknwon** [comment]
Thanks your feedback!

>  Instead, it tries to log in via LDAP, which fails. 

How do you know?

**Comment by samlcharreyron** [comment]
> How do you know?

I can see it in the logs that it attempts to bind via LDAP and does a search on the username.

> Same as above.

I checked the DB in the login_sources table.

**Comment by Unknwon** [comment]
Thanks.

> I checked the DB in the login_sources table.

`login_sources table` tells you nothing about a account's login type.

Check `user` table `login_type` of your admin account.

**Comment by samlcharreyron** [comment]
Sorry I meant the login_type for the user. The login type is 0 as expected.

**Comment by Unknwon** [comment]
Thanks.

Then I think you are login without exactly same username or email, so Gogs thinks you're trying to login with new user.

Or, the database you think which Gogs connects to isn't the one gogs actually connected.

**Comment by samlcharreyron** [comment]
But when I downgrade the gogs version to 0.6.5, it works. I'm pretty sure it's not the DB then...

**Comment by Unknwon** [comment]
There are a lot information is missing in your description, so I need detailed steps about how you upgrade.

**Comment by samlcharreyron** [comment]
I upgrade using the debian packages from packager.io and use

    sudo apt-get upgrade

**Comment by Unknwon** [comment]
In that case please check the custom app.ini for db information, some people reported that packager.io may overwrite some configs.

**Comment by samlcharreyron** [comment]
What should I look for? All I see in app.ini are settings to connect to the mysql DB. There isn't anything about login_types

    
[database]
; Either "mysql", "postgres" or "sqlite3", it's your choice
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gogs
USER = *******
PASSWD = ******
; For "postgres" only, either "disable", "require" or "verify-full"
SSL_MODE = disable
; For "sqlite3" only
PATH = data/gogs.db

**Comment by Unknwon** [comment]
Looks good to me. Can you register a new account after upgrade see if you become an admin automatically.

**Comment by samlcharreyron** [comment]
sorry for the late reply. I boiled it down to a Chrome issue. When I use other browsers or when I use Chrome in the incognito, it works fine. I've tried deleting cookies and cache but I still have this issue. Do you know what it could be from?

**Comment by Unknwon** [comment]
@samlcharreyron Great, finally we found the problem!

If it's an issue about auto-fill of form, section `Delete Autofill info for computers and Chromebooks` on https://support.google.com/chrome/answer/142893?hl=en should help.

**Comment by samlcharreyron** [comment]
Ok I figured it out... I had a typo in the autofilled username in Chrome. Not sure why/if this was only causing a problem in the newer versions of Gogs. Thanks for your help!!

**Comment by Unknwon** [comment]
:trollface:
