### ISSUE TITLE
LDAP authentication with TLS

### ISSUE THREAD

**Issue by AceSlash** [gogits/gogs#1894]
Hello,

When I try to use TLS to connect to OpenLDAP, I have the following error:

```
Nov  4 18:25:18 gogs-test gogs-web-1.service[8722]: [Macaron] Started POST /user/login for 10.99.1.1
Nov  4 18:25:18 gogs-test gogs-web-1.service[8722]: 2015/11/04 18:25:18 #033[1;36m[T] LDAP will use BindDN.#033[0m
Nov  4 18:25:18 gogs-test gogs-web-1.service[8722]: 2015/11/04 18:25:18 #033[1;34m[D] Using TLS for LDAP without verifying: true#033[0m
Nov  4 18:25:18 gogs-test gogs-web-1.service[8722]: 2015/11/04 18:25:18 #033[1;31m[...es/auth/ldap/ldap.go:125 SearchEntry()] [E] LDAP Connect error, ldap1.example.com:LDAP Result Code 200 "": EOF#033[0m
Nov  4 18:25:18 gogs-test gogs-web-1.service[8722]: [Macaron] Completed /user/login 200 OK in 9.410884ms
```
I'm using the following versions:
gogs version 0.6.15-1446616151.1b5e1be.jessie
git version 2.1.4-2.1
postgresql 9.4.5
Debian Jessie (8.2)

I tried both STARTTLS and SSL port (389 and 636, which are both open). The certificate used by the LDAP server is signed by an internal private authority (not commercial), TLS is working with ldapsearch from the server with the credential configured on GOGS without any issue.

Both the boxes "Enable TLS Encryption" and "Skip TLS Verify" are checked.

The settings I changed from the default configuration are:

PROTOCOL = https
DOMAIN = scm.example.com
DISABLE_SSH = true
CERT_FILE = (path to a valid commercial certificate)
KEY_FILE = (path to a valid commercial certificate key)

And the settings to the database and debug level to trace.

If I deactivate TLS on the OpenLDAP server and on GOGS, everything works as expected.

Logs from OpenLDAP during the exchange available here: 

```
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: activity on 1 descriptor
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: activity on:
Nov  4 18:25:19 ldap1-test slapd[11954]: 
Nov  4 18:25:19 ldap1-test slapd[11954]: slap_listener_activate(8): 
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=8 busy
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=9 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=10 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=11 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=12 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=13 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: >>> slap_listener(ldap://ldap1.example.com:389/)
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: listen=8, new connection on 21
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: added 21r (active) listener=(nil)
Nov  4 18:25:19 ldap1-test slapd[11954]: conn=1007 fd=21 ACCEPT from IP=10.99.1.63:51833 (IP=10.99.1.61:389)
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: activity on 2 descriptors
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: activity on:
Nov  4 18:25:19 ldap1-test slapd[11954]:  21r
Nov  4 18:25:19 ldap1-test slapd[11954]: 
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: read active on 21
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=8 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=9 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=10 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=11 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=12 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=13 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: connection_get(21)
Nov  4 18:25:19 ldap1-test slapd[11954]: connection_get(21): got connid=1007
Nov  4 18:25:19 ldap1-test slapd[11954]: connection_read(21): checking for input on id=1007
Nov  4 18:25:19 ldap1-test slapd[11954]: ber_get_next on fd 21 failed errno=34 (Numerical result out of range)
Nov  4 18:25:19 ldap1-test slapd[11954]: connection_read(21): input error=-2 id=1007, closing.
Nov  4 18:25:19 ldap1-test slapd[11954]: connection_closing: readying conn=1007 sd=21 for close
Nov  4 18:25:19 ldap1-test slapd[11954]: connection_close: conn=1007 sd=21
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: removing 21
Nov  4 18:25:19 ldap1-test slapd[11954]: conn=1007 fd=21 closed (connection lost)
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: activity on 1 descriptor
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: activity on:
Nov  4 18:25:19 ldap1-test slapd[11954]: 
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=8 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=9 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=10 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=11 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=12 active_threads=0 tvp=NULL
Nov  4 18:25:19 ldap1-test slapd[11954]: daemon: epoll: listen=13 active_threads=0 tvp=NULL
```

Am I doing something wrong?

**Comment by Unknwon** [comment]
Thanks your feedback!

> ldap1.example.com:

I'm not sure but this indicates you're not giving any port number?

cc @SergioBenitez

**Comment by AceSlash** [comment]
The port number is configured, for this specific trace, it was "389"

**Comment by Unknwon** [comment]
My bad, the log is correct.

Are you able to connect without TLS?

**Comment by SergioBenitez** [comment]
Is there a specific reason you have "skip TLS verified" enabled? How do things fare with the setting disabled?

**Comment by AceSlash** [comment]
@Unknwon : yes, I am able to connect without TLS (but I'll have to use it in production).

@SergioBenitez : I'm using "Skip TLS verify" because the certificate of the OpenLDAP server is not from a commercial entity, but I just tried without this settings and the log is pretty similar:
```
2015/11/04 19:14:55 [T] LDAP will use BindDN.
2015/11/04 19:14:55 [D] Using TLS for LDAP without verifying: false
2015/11/04 19:14:55 [...es/auth/ldap/ldap.go:125 SearchEntry()] [E] LDAP Connect error, ldap1.example.com:LDAP Result Code 200 "": EOF
```

**Comment by Unknwon** [comment]
> Result Code 200 "": EOF

I think the EOF is the problem...

**Comment by AceSlash** [comment]
JoBbZ on the OpenLDAP irc chan suggested that there may be a step missing to issue the STARTTLS operation.

Also from my quick search, the OpenLDAP message "ber_get_next on fd 21 failed errno=34 (Numerical result out of range)" seems to mean that a messages was to big to be processed, which may corroborate the idea that STARTTLS is not working correctly ( source: http://www.linuxtopia.org/online_books/network_administration_guides/ldap_administration/appendix-common-errors_Other_Errors.html ).

**Comment by SergioBenitez** [comment]
There is no support for StartTLS in the LDAP client implementation Gogs is using. If you'd like to access LDAP securely, use LDAPS. There's another issue, which you can search for, with a longer discussion on this subject you might find useful.

**Comment by AceSlash** [comment]
@SergioBenitez : okay, sorry for the confusion then, I was under the impression that STARTTLS was supported.
