### ISSUE TITLE
Case sensitive clone URL

### ISSUE THREAD

**Issue by pennatil** [gogits/gogs#1895]
It seems like the URL for the clone gets converted to lower case, meaning that if I have a repo with a name such as `lowerAndUpperCase`, the clone URL will be `http://gogs.yourserver.com/user/loweranduppercase.git`, making so that when the clone happens, the folder is all lower case. Would it be possible to keep the URL case sensitive? The system already supports it, it should be an easy fix in the pop up window with the url

**Comment by Unknwon** [comment]
Gogs does not care what cases you choose to clone, it treats them all lower cases.

**Comment by Unknwon** [comment]
It is not likely going to be supported before 1.x...

**Comment by Unknwon** [comment]
But if you mean just a case match check for HTTP clone, yes that can be done but doesn't see a example of why. 😀

**Comment by linquize** [comment]
I need a **case-preserving** git hosting, even if the matching is case-insensitive.

**Comment by tboerger** [comment]
But that can work only for ssh, http doesnt care about case sensitivity

**Comment by Unknwon** [comment]
actually if you SSH clone correctly, Gogs does not care cases as well.

**Comment by pennatil** [comment]
I think I did not explain myself well enough. Let us assume I create a repo called `myNewRepo`, under the username `user`.
 * The URL is `https://gogs.server.io/user/myNewRepo` -> This is perfect
 * when clicking the clone icon (little cloud) and selecting http, the url is `http://gogs.server.io/user/mynewrepo.git` -> converted to lower case

The problem is, that when on the local machine you run `git clone http://gogs.server.io/user/mynewrepo.git`, the folder that is created is all lower case. This is because (I assume) the `git clone` command truncates the url and extracts the repo name. What I would appreciate, is that the clone URL that is given by the clone icon would replicate the camel case notation that I used in the repo name. 

Hope I made myself a bit more clear

**Comment by Unknwon** [comment]
Thanks for clarifying, the problem becomes much easier now. :D

**Comment by Unknwon** [comment]
Hi @pennatil , I just pushed code to `develop` and https://try.gogs.io , please help test.

**Comment by pennatil** [comment]
That seems to have solved it. Thank you!

**Comment by Unknwon** [comment]
@pennatil thanks your confirmation!

**Comment by AnumSheraz** [comment]
Don't know about Git. But i was facing same issue in BitBucket. I made it work by changing the repo url. My original repo name was FlaskApp and the url I got from bitBucket was git clone https://AnumSheraz@bitbucket.org/AnumSheraz/flaskapp.git And I pasted it in my terminal as git clone https://AnumSheraz@bitbucket.org/AnumSheraz/FlaskApp.git , which worked Perfect !

**Comment by Unknwon** [comment]
I really have no idea what you are saying...
