### ISSUE TITLE
How to alter configuration while running in Docker?

### ISSUE THREAD

**Issue by ibigbug** [gogits/gogs#1899]
Such as disable new user register

**Comment by Unknwon** [comment]
Hi, if you have read https://github.com/gogits/gogs/blob/master/docker/README.md , you should know that custom config file is volumed to your local file system, just change `path_to_volume/gogs/conf/app.ini` and restart container.

**Comment by ibigbug** [comment]
Thanks for that. I read the guide of course and it was just because I'm not so familiar with docker. I'll try it, thank you!
