### ISSUE TITLE
Commits show the right time on repo pages, explore page doesn't

### ISSUE THREAD

**Issue by AdrianVerde** [gogits/gogs#1900]
Commits show the right time (e.g. "3 minutes ago") in the repo page, but in the explore page, the "Updated x time ago" doesn't follow, it shows instead, the time of the commit before the last time I updated gogs, which was yesterday.

I updated to develop, then deleted it and installed back again from master branch.

My current gogs version is 0.6.25.1104, installed from source.
I'm using "MySQL DB Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (i686)"
Gogs is installed in a Debian Wheezy i386 machine,
Running git 1.7.10.4

What could be causing this and how can I diagnose it?

Thanks.

**Comment by Unknwon** [comment]
Thanks your feedback!

> Commits show the right time (e.g. "3 minutes ago") in the repo page, but in the explore page, the "Updated x time ago" doesn't follow, it shows instead, the time of the commit before the last time I updated gogs, which was yesterday.

How did you push the code?

**Comment by AdrianVerde** [comment]
With GitHub Desktop for windows, with the origin set to the gogs repo, which is the same way I pushed previous commits that showed the right time on "Explore"

**Comment by Unknwon** [comment]
Hmm.. are you pushing by HTTP or SSH?

**Comment by AdrianVerde** [comment]
HTTP

**Comment by Unknwon** [comment]
Thanks.

> Commits show the right time (e.g. "3 minutes ago") in the repo page, but in the explore page, the "Updated x time ago" doesn't follow, it shows instead, the time of the commit before the last time I updated gogs, which was yesterday.

Can you given some screenshots?

**Comment by AdrianVerde** [comment]
Repo pages with correct date, time:
![doncasting - gogs go git service - google chrome](https://cloud.githubusercontent.com/assets/1646766/10985581/b4e22fce-8422-11e5-82a4-973c00b5809a.png)
![qrkeychains - gogs go git service - google chrome](https://cloud.githubusercontent.com/assets/1646766/10985585/b7d0775e-8422-11e5-872d-9b28f6c06879.png)

Explore page with old time:
![explore - gogs go git service - google chrome2](https://cloud.githubusercontent.com/assets/1646766/10985594/c84b9938-8422-11e5-9788-c278c88fe284.png)

**Comment by Unknwon** [comment]
Thanks, I got it.

**Comment by Unknwon** [comment]
Hi there, can you checkout `develop` branch see if the fix works?

**Comment by AdrianVerde** [comment]
Checked, it doesn't yet, made one more last commit a minute ago, which consisted only in deleting some files, did not add new lines of code, I don't know if that could have any effect on showing or not the correct Updated time.

**Comment by Unknwon** [comment]
What is the version you just tested?

**Comment by AdrianVerde** [comment]
0.6.26.1104 Beta

**Comment by Unknwon** [comment]
The version of `develop` is `0.6.27.1104`.

**Comment by AdrianVerde** [comment]
True, when I run "go get -u ./..." just before "go build", it downloads "0.6.26.1104 Beta" again, overwriting the already present "0.6.27.1104" in the gogs directory

**Comment by AdrianVerde** [comment]
Ok, I was following this http://gogs.io/docs/installation/install_from_source#build-from-develop-branch when it downloaded the previous version.
But I ran "git checkout develop" after "cd gogs" and did "go get ./..." instead of "go get -u ./...", then built successfully, made an additional commit to one of the repos and checked that now it works perfectly:

![explore - gogs go git service - google chrome](https://cloud.githubusercontent.com/assets/1646766/10989866/f329c948-844c-11e5-9fb4-d421f49c23d4.png)

Thanks man! :smile:

**Comment by Unknwon** [comment]
Thanks your confirmation!
