### ISSUE TITLE
Creating pull requests within the same repository (pull branch-foo into branch-bar)

### ISSUE THREAD

**Issue by ZeerakW** [gogits/gogs#1901]
I don't seem to be able to create pull requests from web-ui, is there another way to create pull requests or something terribly obvious that I'm missing?

**Comment by satheeshwaran** [comment]
+1 need this feature, I am evaluating Gogs to use it so please add this.

**Comment by lukasdietrich** [comment]
This feature has already been requested, see #1597.

**Comment by ZeerakW** [comment]
Somehow missed that when going through the list. Thanks for letting letting me know!

**Comment by Unknwon** [comment]
:trollface:
