### ISSUE TITLE
Translation word order

### ISSUE THREAD

**Issue by AdrianVerde** [gogits/gogs#1902]
![explorar - gogs go git service - google chrome](https://cloud.githubusercontent.com/assets/1646766/10990018/cb9e3a88-844e-11e5-90a2-277c147310d0.png)
In Spanish, the correct way of saying "Updated 11 minutes ago" is "Actualizado hace 11 minutos", that word sorting in English would be "Updated ago 11 minutes", meaning that the translation is correct, only the position of the words should be changed when in Spanish, I guess this also applies to other languages.

**Comment by Unknwon** [comment]
Thanks, to help fix it, please see http://gogs.io/docs/features/i18n

**Comment by AdrianVerde** [comment]
Ok, understanding that "%s" = "ago", and "%d" equals the number of minutes, seconds or time unit in question, I proposed the changes in crowdin to fix it.

**Comment by Unknwon** [comment]
Thanks, I've approved your suggestion.

**Comment by AdrianVerde** [comment]
Suggested the same change for every available time unit

**Comment by Unknwon** [comment]
All done :D

**Comment by AdrianVerde** [comment]
Ok thanks!

**Comment by Unknwon** [comment]
Will merge to main repo in new release :D thank you!
