### ISSUE TITLE
请问怎么以守护进程的方式启动gogs呢？

### ISSUE THREAD

**Issue by finereport2001** [gogits/gogs#1903]
现在直接用 ./gogs web的方式启动的话，我关闭了ssh连接，服务器也就停止了

**Comment by ArkBriar** [comment]
@finereport2001 
后台运行：./gogs web 2>/dev/null &
或者使用screen命令

拙见见笑

**Comment by Unknwon** [comment]
Please see http://gogs.io/docs/intro/faqs

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by hellowords** [comment]
@Unknwon 你好，我安装新版ubuntu Gogs 将scripts/init/debian/中的gogs 复制到/etc/init.d/gogs 并给予775的权限，servers gogs start 的时候启动不了，gogs文件里面配置项需要修改吗？

**Comment by roxma** [comment]
@hellowords 

Could you provide the error message if it is not working?

By the way, I assume you mean `service gogs start` instead of `servers gogs start `

**Comment by hellowords** [comment]
hi @roxma thx for you reply , i'm not sure chinese about you. but my english is not good~
我是用`service gogs start` 来启动 gogs 服务的。但是没任何的报错，用`/etc/init.d/gogs start` 也是没有任何的效果，我访问对应配置的域名或者ip加上3000端口号，都是无法访问
>  root@vultr:~# /etc/init.d/gogs start
> root@vultr:~# service gogs start
> root@vultr:~# 

这是我用两个命令之后的状况，没有任何的报错。`gogs/log/` 中的两个日志文件也没有对应的错误信息

**Comment by hellowords** [comment]
@roxma 我将`custom/conf/app.ini` 文件中的RUN_USER 改成 root ，在gogs目录中`./gogs web` 能运行，改成 git 就不可以了。

**Comment by hellowords** [comment]
@roxma 将 `custom/conf/app.ini` 中的 `RUN_USER` 改成 root 可以运行，改成git 报下面的错误
![image](https://cloud.githubusercontent.com/assets/13344029/25135488/1596a1a2-2485-11e7-8b5a-0dc861f2a92b.png)

**Comment by hellowords** [comment]
你好  @roxma 
我用Systemd 服务启动不了，下面是报错信息

![snipaste_20170419_005520](https://cloud.githubusercontent.com/assets/13344029/25143275/6731f162-249c-11e7-89bb-06c9d06392f9.png)

>git@asd:/home/gogs/log$ sudo journalctl -b -u gogs
-- Logs begin at Wed 2017-04-19 00:27:27 CST, end at Wed 2017-04-19 00:47:29 CST. --
Apr 19 00:27:29 vultr.guest systemd[1]: Started Gogs.
Apr 19 00:27:29 vultr.guest systemd[1]: gogs.service: Main process exited, code=exited, status=210/CHROOT
Apr 19 00:27:29 vultr.guest systemd[1]: gogs.service: Unit entered failed state.
Apr 19 00:27:29 vultr.guest systemd[1]: gogs.service: Failed with result 'exit-code'.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Service hold-off time over, scheduling restart.
Apr 19 00:27:30 vultr.guest systemd[1]: Stopped Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: Started Gogs.
Apr 19 00:27:30 vultr.guest systemd[1432]: **gogs.service: Failed at step CHROOT spawning /home/git/gogs/gogs: No such file or directory**
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Main process exited, code=exited, status=210/CHROOT
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Unit entered failed state.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Failed with result 'exit-code'.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Service hold-off time over, scheduling restart.
Apr 19 00:27:30 vultr.guest systemd[1]: Stopped Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: Started Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Main process exited, code=exited, status=210/CHROOT
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Unit entered failed state.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Failed with result 'exit-code'.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Service hold-off time over, scheduling restart.
Apr 19 00:27:30 vultr.guest systemd[1]: Stopped Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: Started Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Main process exited, code=exited, status=210/CHROOT
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Unit entered failed state.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Failed with result 'exit-code'.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Service hold-off time over, scheduling restart.
Apr 19 00:27:30 vultr.guest systemd[1]: Stopped Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: Started Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Main process exited, code=exited, status=210/CHROOT
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Unit entered failed state.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Failed with result 'exit-code'.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Service hold-off time over, scheduling restart.
Apr 19 00:27:30 vultr.guest systemd[1]: Stopped Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Start request repeated too quickly.
Apr 19 00:27:30 vultr.guest systemd[1]: Failed to start Gogs.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Unit entered failed state.
Apr 19 00:27:30 vultr.guest systemd[1]: gogs.service: Failed with result 'exit-code'.

**Comment by arkbriar** [comment]
看了眼 init 脚本，大概是你参数一个都没改

挂在这句，改脚本参数，要么手动加 git 用户

```bash
Apr 19 00:27:30 vultr.guest systemd[1432]: gogs.service: Failed at step CHROOT spawning /home/git/gogs/gogs: No such file or directory
```

参数 in [/etc/init.d/gogs](https://github.com/gogits/gogs/blob/master/scripts/init/debian/gogs)，大概改 **WORKINGDIR** 和 **USER**

```sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Gogs"
NAME=gogs
SERVICEVERBOSE=yes
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
WORKINGDIR=/home/git/gogs
DAEMON=$WORKINGDIR/$NAME
DAEMON_ARGS="web"
USER=git
```

**Comment by hellowords** [comment]
@arkbriar thx it works!
