### ISSUE TITLE
Images in subdirectory does not have correct relative links

### ISSUE THREAD

**Issue by tyro668** [gogits/gogs#1904]
`![picture](screenshots/demo.png)`

cannot be link to the correct url,how can I resolve this problem?

**Comment by tboerger** [comment]
@Unknwon I just wanted to show https://try.gogs.io/Unknwon/gogs but you removed the screenshots :D

**Comment by Unknwon** [comment]
What does the link looks right now what is the correct link you expect? And please report with your version of Gogs.

**Comment by ChangePlaces** [comment]
Interesting - I've just tried to create an issue with the same text - https://try.gogs.io/gogs/gogs/issues/25

**Comment by Unknwon** [comment]
Image link render has a problem with relative links which should be fixed with my last push to `develop` branch, and you can also test on https://try.gogs.io

**Comment by ChangePlaces** [comment]
I think these are the exact steps to reproduce:

    Open an issues queue in a tab.
    Leave it for a certain number of hours (I'm not sure if it's, say 2, or lots more like 8).
    Afterwards, go back to that tab, and click the 'create new' issue or open an issue
    Either create a new issue, or add a new comment
    Invalid csrf

To resolve, you can just press back, refresh (which leaves your text there) then submit again. But this is messy. As a (hopefully) temporary solution, I'm using a reload plugin for firefox which reloads the issue pages every x minutes. (I have the tabs pinned open)

**Comment by Unknwon** [comment]
@ChangePlaces you put in wrong thread.

**Comment by Unknwon** [comment]
Closed as fixed.

**Comment by tyro668** [comment]
as this url:http://www.finedevelop.com:2000/finesoft/plugins/src/master/plugin-message
© 2015 Gogs · 当前版本: 0.7.0.1107 Beta,cannot dispay images correct too

**Comment by Unknwon** [comment]
@tyro668 thanks your example! I know what's wrong now :D

**Comment by Unknwon** [comment]
Here we go: https://try.gogs.io/unknwon/plugin/src/master/plugin-message

**Comment by tyro668** [comment]
@Unknwon ，thanks，waiting for the next version，^_^

**Comment by Unknwon** [comment]
@tyro668 what will be a long way to wait...
