### ISSUE TITLE
Triming the issue title

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1905]
If I create a title: `"This is an issue "` with the trailing space, it doesn't get trimmed when the issue is created!

**Comment by Unknwon** [comment]
I've pushed fix to `develop` and updated https://try.gogs.io , please help test!

**Comment by ChangePlaces** [comment]
Awesome, but don't forget the body as well! The title is trimmed, but the body isn't!

https://try.gogs.io/gogs/gogs/issues/26

**Comment by Unknwon** [comment]
I don't think body needs to be cared, HTML does not care them.

**Comment by Unknwon** [comment]
Close as fixed.
