### ISSUE TITLE
Bad redirects when trying to change the http subpath

### ISSUE THREAD

**Issue by javieralmancevo** [gogits/gogs#1906]
I just installed the last version of gogs from github in a Ubuntu 14.04 machine. I tested going to http://localhost:3000 and it works fine, I get redirected to http://localhost:3000/install and I can see the webpage with all the options. But I wanted to change the path so it was in http://localhost:3000/gogs. For this I created a new conf file in custom/conf/app.ini with exactly this:

```
[server]
ROOT_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/gogs
```

The Faq seem to say you can do it (in the Nginx conf part):

> Then set [server] ROOT_URL = http://git.crystalnetwork.us/gogs/ in your configuration.

But then if I try to access http://localhost:3000/gogs, both Firefox and Chromium give a redirect error and a blank page.

**Comment by Unknwon** [comment]
> But then if I try to access http://localhost:3000/gogs, both Firefox and Chromium give a redirect error and a blank page.

What Gogs supports is **reverse proxy** sub-path, it is simply not going to work without reverse proxy.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by javieralmancevo** [comment]
Hi

I tried to do a reverse proxy sub-path for gogs but I did not manage. Do you have a template on how to configure ngynx or apache to create a reverse proxy sub-path? It would be helpfull. Thanks.

**Comment by Unknwon** [comment]
Please see FAQs on gogs.io
