### ISSUE TITLE
发现两个使用问题

### ISSUE THREAD

**Issue by cnsilvan** [gogits/gogs#1907]
1.使用HTTPS后，用HTTP去访问会弹出下载一个文件的操作。
2.未支持markdown语言。
可能是我还不会使用，求指导。
version:0.6.15.0926 Beta

**Comment by Unknwon** [comment]
Thanks your feedback!

But I don't understand what are the issues you're describing, can you rephrase and provides more details?

**Comment by cnsilvan** [comment]
1.我按照配置文档：
设置为：PROTOCOL：https配置好证书后使用HTTPS+localhost:3000是能访问的
但是用http+localhost：3000后就会直接弹出下载框。
2.我发现我部署完后，并不支持markdown

**Comment by Unknwon** [comment]
> 1.我按照配置文档：
设置为：PROTOCOL：https配置好证书后使用HTTPS+localhost:3000是能访问的
但是用http+localhost：3000后就会直接弹出一个下载框。

Can you given a screenshot?

> 2.我发现我部署完后，并不支持markdown

Can you given a screenshot?

**Comment by cnsilvan** [comment]
使用http访问就出现下面这种情况
![image](https://cloud.githubusercontent.com/assets/15416002/11027490/ade7386a-86f0-11e5-8704-56047860224c.png)
下载下来的文件打开是这样的
![image](https://cloud.githubusercontent.com/assets/15416002/11027495/bf3651f0-86f0-11e5-9da8-dbc005ed5611.png)
2.
![image](https://cloud.githubusercontent.com/assets/15416002/11027501/cb3339e6-86f0-11e5-9f20-f4217e25c14d.png)
md文件原格式显示了。

**Comment by Unknwon** [comment]
> 设置为：PROTOCOL：https配置好证书后使用HTTPS+localhost:3000是能访问的
但是用http+localhost：3000后就会直接弹出一个下载框。

What is the HTTP URL?

> md文件原格式显示了。

What is your Markdown source code?

**Comment by cnsilvan** [comment]
TEST URL：grraintech.com:3000
```markdown
   ﻿# driverserver
   代驾APP后台服务
```

**Comment by Unknwon** [comment]
> TEST URL：grraintech.com:3000

Can't open, but the filename you provide does not belong to Gogs anyhow.

>   ﻿# driverserver
   代驾APP后台服务

I think you need an empty line after `# driverserver`

**Comment by cnsilvan** [comment]
加了以后一样的原格式显示。
# 服务器挂了。。。。。。。。。

**Comment by Unknwon** [comment]
> 加了以后一样的原格式显示。

Can you give full screen screenshot, I don't get enough information to be able to response.

**Comment by cnsilvan** [comment]
现在可以访问了。你看看吧。
HTTP访问的时候很奇怪。

**Comment by Unknwon** [comment]
> 现在可以访问了。你看看吧。

... I still can't visit...

**Comment by cnsilvan** [comment]
如果用http访问
log:TLS handshake error from 127.0.0.1:50290: tls: first record does not look like a TLS handshake

**Comment by Unknwon** [comment]
It is so obvious that you enabled HTTPS but try to visit as HTTP. This is expected behavior. :)

**Comment by cnsilvan** [comment]
重点是 我一用http访问就弹出下载框。。。
![2015-11-09 21 10 09](https://cloud.githubusercontent.com/assets/15416002/11034416/5aed9dda-8726-11e5-9f08-0d8d37fef1ba.png)

**Comment by Unknwon** [comment]
Visit by HTTP is wrong at the very beginning, all errors caused by it is not worth investigating.

**Comment by cnsilvan** [comment]
1.既然开启了HTTPS，那么肯定就希望全部都走HTTPS，要不就把HTTP禁了，要不就指向HTTPS。
2.MarkDown依然原格式显示的。

**Comment by Unknwon** [comment]
For 2. Can you reproduce on https://try.gogs.io ?

**Comment by cnsilvan** [comment]
no.我准备再重新安装一次。。。MAC下

**Comment by Unknwon** [comment]
Any updates?

**Comment by cnsilvan** [comment]
sorry 忘记了，我重装后支持markdown了。。。原因不知。。。

**Comment by Unknwon** [comment]
:trollface:
