### ISSUE TITLE
Require_Signin_view does not work

### ISSUE THREAD

**Issue by apachemaven** [gogits/gogs#1908]
![image](https://cloud.githubusercontent.com/assets/4485890/11028888/b6291d9c-86fd-11e5-924e-b7402572e52c.png)

As shown, I have set the `Require_Signin_view` to true by set the config at `~/gogs_root/custom/conf/app.ini`, while the anonymous user are not redirected to the login page when they tried to view the home page or the explore page.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your Gogs version and have you restart Gogs?

**Comment by apachemaven** [comment]
Version:

gogs_v0.7.0_windows_amd64


And I  have restarted gogs once I modify the configuration.

**Comment by Unknwon** [comment]
Thanks. Can you check o admin configuration page make sure that Gogs actually recognize your config for sign in view.

**Comment by apachemaven** [comment]
Seems Gogs have recognized that configuration, but it did not work as it should.

![image](https://cloud.githubusercontent.com/assets/4485890/11050652/cc92bbd0-8782-11e5-83d5-70a46b010e9f.png)

**Comment by Unknwon** [comment]
@apachemaven Hmm.. I just tested and it works... is there some information I'm still missing from your side?

**Comment by apachemaven** [comment]
I am not sure, I even re-installed the whole gogs, while it does not work as expected.

**Comment by Unknwon** [comment]
> while the anonymous user are not redirected to the login page when they tried to view the home page or the explore page.

Which anonymous way did you use?

**Comment by apachemaven** [comment]
Open a new browser window, and enter the `http://xxx:3000/explore`, then I can see all the repositories which I think I should be redirected to the login page.

**Comment by Unknwon** [comment]
> http://xxx:3000/explore

From your previous screenshot, you're setting ROOT_URL to `http://localhost:3000`, is this the URL you replace for `xxx`?

**Comment by apachemaven** [comment]
OK, I fix that, and `192.168.1.13` is the IP of the  server where gogs are installed at, my local IP is `192.168.1.10`.

**Comment by Unknwon** [comment]
OK, so by visiting `http://192.168.1.13:3000/explore` on a new private mode window, you can see the explore page?

**Comment by Unknwon** [comment]
If I understand correctly,

> Open a new browser window

Browser maintains same session data which you're still logged in.

**Comment by apachemaven** [comment]
I logged out first. And yes, I can see the explore page,even the repository

![image](https://cloud.githubusercontent.com/assets/4485890/11051605/7d2958de-878b-11e5-9870-f745cefef93e.png)

**Comment by Unknwon** [comment]
Hmm... I still think you did not enable `require sign in view` successfully... 

How did you setup your Gogs?

**Comment by apachemaven** [comment]
Download the binary package `gogs_v0.7.0_windows_amd64.zip`, and unzip it to `D:/install/gogs_v0.7.0_windows_amd64`, then run `gogs web` to install it, after that, stop gogs service by close the windows prompt window. Then modify the file at `D:/install/gogs_v0.7.0_windows_amd64/custom/conf/app.ini`, restart gogs.

**Comment by Unknwon** [comment]
@apachemaven I tested on Windows with exactly same steps you provide and it works...

**Comment by Unknwon** [comment]
PS: Same browser as your screenshot.

**Comment by apachemaven** [comment]
I will try another server and post the result. BTW, which kind of database do you choose?

**Comment by Unknwon** [comment]
SQLite3, although this is irrelevant :D

**Comment by apachemaven** [comment]
Ao, I am sorry but I do not know why, I re-install gogs in a clean server and it works now.

**Comment by Unknwon** [comment]
@apachemaven :trollface: no problem! Maybe someday, suddenly truth will come out.

**Comment by emrahcom** [comment]
I have the same issue. I installed gogs (version 0.9.113-1483413028.e8c3e9b.jessie) from deb.packager.io repo on a Debian Jessie box.

I checked "Require Sign in View" option and I saw that it's changed in /etc/gogs/conf/app.ini file too.

But the change take effect after restart gogs service with systemctl restart gogs.service

**Comment by erguotou520** [comment]
I have the same issue on ubuntu64 and windows. Install from docker on ubuntu and .exe file on windows. I have checked the configs. But I can still explore all the repos after logout(even clear site data). 😢

**Comment by erguotou520** [comment]
Tested `0.11.4` is ok while `0.11.19` not on windows.

**Comment by Unknwon** [comment]
You need restart Gogs after made config changes.
