### ISSUE TITLE
CDN download over HTTPS

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1909]
I noticed there are only HTTP links for CDN download on the 'Download binary' page. I think it's better to provide CDN download over HTTPS, since HTTP hijacking is pretty widespread nowadays.

**Comment by Unknwon** [comment]
Qiniu does not have HTTPS for global speed up domains on my account...

**Comment by tboerger** [comment]
So don't use a CDN? :)

**Comment by JokerQyou** [comment]
@tboerger I can download from Github release link, but that's from Amazon servers, it would take hours to wait before I can do anything.

**Comment by JokerQyou** [comment]
@Unknwon I think you can enable HTTPS support in the bucket settings page, go to the 'Domain bindings' tab. Have to wait for their auditing ( as long as two work days ).

**Comment by Unknwon** [comment]
I do have on HTTPS domain, but that's not global speed up domain... And has significant problem in US

**Comment by JokerQyou** [comment]
Sad story... I wonder if there are CDN providers out there willing to provide secured downloading for open source projects like this one.

**Comment by Unknwon** [comment]
I'll contact them later tonight see if possible. :)

**Comment by Unknwon** [comment]
Hmm... they responded, I need to call 400-xxx which looks like huge amount of money to me. So I guess HTTPS is impossible right now.

**Comment by Unknwon** [comment]
After let's encrypt goes public, I think I can put those downloads on my server with HTTPS.

**Comment by JokerQyou** [comment]
Otherwise you can put the official website under HTTPS, and provide MD5 or SHA256 hash for the binary packages.

**Comment by tboerger** [comment]
> After let's encrypt goes public, I think I can put those downloads on my server with HTTPS.

Even without it you get free certs at StartSSL. Ugly page, but the certs are working.

**Comment by ChangePlaces** [comment]
why is http hijackign an issue as payment is not occuring? what am i missing?

**Comment by tboerger** [comment]
> why is http hijackign an issue as payment is not occuring? what am i missing?

Because of changing the binary download with a malicious binary?

**Comment by ChangePlaces** [comment]
by a cdn which would it would be knownif they have done it before?

**Comment by tboerger** [comment]
> by a cdn and it would be known if they have done it before?

I have no idea what you mean

**Comment by JokerQyou** [comment]
An HTTP hijacking could happen on the whole chain of transport, not only by the CDN provider. A normal case would be performed by local ISP, they could easily replace the response with a malicious software, just like they replace those `js` files.

**Comment by Unknwon** [comment]
I used to put gogs.io under HTTPS but the two GitHub buttons are HTTP, which makes the icon yellow on Chrome... that's so...

**Comment by Unknwon** [comment]
OK, just tested, they have HTTPS now for GitHub buttons.

**Comment by Unknwon** [comment]
Here we go! https://gogs.io/docs/installation/install_from_binary

**Comment by Unknwon** [comment]
https://dl.gogs.io/

**Comment by ChangePlaces** [comment]
@JokerQyou  I really feel like I'm missing something here! Who replaces what js files? Are we talking corrupt IPS?

**Comment by JokerQyou** [comment]
@ChangePlaces Local Internet service provider could replace the js files on your website with `the original js file + advertisement js files`, this replacement happens when the response traffic is transporting to your users. This is happening almost everyday here in China.

**Comment by ChangePlaces** [comment]
@JokerQyou wow. It's amazing what western media doesn't report! So, that bypasses all ad-block technology unless it grep's for specific patterns?

**Comment by JokerQyou** [comment]
They don't get reported even here in China, few people realize it being an security issue. But these days social media take them out to the public, so more and more people is reporting those ISP to the government department. 
At first these 'second-hand' traffic would probably bypass all adblock tech, but if the `advertisement js` is trying to load the real advertisement content, adblock plugins can still stop them if those plugins were properly configured. But you don't expect much people to install adblock software on their mobile devices, so there's still much profit there.
