### ISSUE TITLE
Spanish translation reorder fail

### ISSUE THREAD

**Issue by AdrianVerde** [gogits/gogs#1910]
![explorar - gogs go git service - google chromeas](https://cloud.githubusercontent.com/assets/1646766/11041535/ae9d5ae2-8712-11e5-9d91-0204bafd0995.png)
Since the reorder of the strings in the locales, this happens (when in Spanish), why?
btw if %s is the number and %d is the time unit, they should be swapped.

It also happens in Russian when in "months" time unit:
![- gogs go git service - google chromrue](https://cloud.githubusercontent.com/assets/1646766/11041831/14a0a136-8714-11e5-88fd-448f388e482f.png)

**Comment by Unknwon** [comment]
You may need to use %[2]d %[1]s, sorry forgot to mention that

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by AdrianVerde** [comment]
Added the suggestion to Crowdin

**Comment by Unknwon** [comment]
Cool!

**Comment by AdrianVerde** [comment]
After "%[2]d %[1]s segundos" was comitted I tried it and see this:

![explorar - gogs go git service - google chrome](https://cloud.githubusercontent.com/assets/1646766/11308090/8295a104-8fbc-11e5-9f34-d674d8dd6978.png)

I see that because go is using printf positional formatting and gogs passes number first then string second there is a parameters type mismatch.

So I suggested the swapped ("d" by "s") "%[2]s %[1]d segundos" expecting that the order is now correct, but also correctly printed

**Comment by xxxtonixxx** [comment]
+1, it's so annoying

**Comment by Unknwon** [comment]
You guys can correct it on Crowdin.... https://gogs.io/docs/features/i18n#make-corrections

**Comment by xxxtonixxx** [comment]
Ok, I have fixed in Crowdin. I think that It was more difficult, so thanks!

**Comment by Unknwon** [comment]
:trollface: Thank you!

**Comment by AdrianVerde** [comment]
@Unknwon as can be seen in the last release (I tested creating a repo on https://try.gogs.io and then went to the "Explore" tab)

![explorar - gogs go git service - google chrome2](https://cloud.githubusercontent.com/assets/1646766/11413790/8c6bdd62-93ed-11e5-89aa-f3bb78f7f995.png)

Since the last approved changes in crowdin, the order is now correct ("hace" is placed before the number of seconds "10") but still, keeps showing that one is an integer and the other a string, and the one showing seconds (first repo on screenshot "test2"), has the correct "%[2]s %[1]d segundos" translation, so, what else can we do to fix it?

**Comment by xxxtonixxx** [comment]
I think that in gogs.io still hasn't updated... For me is all right, I see all good... after I will upload a image  :thumbsup:

**Comment by xxxtonixxx** [comment]
Here is the image!! I have done the changes in my local repository and I have manually modified the locales in conf/locales/... and I have added the last changes :ok_hand:
<img src="http://fdzeta.com/subir/images/mNAMO.png" border="0" />

**Comment by AdrianVerde** [comment]
Awesome then! :)

**Comment by Unknwon** [comment]
Will merge new translation to main repo soon!

**Comment by xxxtonixxx** [comment]
:smile:  :thumbsup:
