### ISSUE TITLE
optional build automation into Makefile

### ISSUE THREAD

**Issue by tjyang** [gogits/gogs#1911]
Hi Unknown

This is RFE.
Can you automation the optional tag build as a target in in main Makefile ?
ie, "make optional" will automate the following steps

<pre>
Build with Tags

A couple of things do not come with Gogs automatically, you need to compile Gogs with corresponding build tags.

Available build tags are:

sqlite3/tidb: SQLite3/TiDB database support
redis/memcache: Redis/Memcache cache/session backend support
pam: PAM authentication support
cert: Generate self-signed certificates support
For example, you want to support all of them, first delete directory $GOPATH/pkg/${GOOS}_${GOARCH}/github.com/gogits/gogs and then do:

$ go get -u -tags "sqlite tidb redis memcache pam cert" github.com/gogits/gogs
$ cd $GOPATH/src/github.com/gogits/gogs
$ go build -tags "sqlite tidb redis memcache pam cert"
</pre>

**Comment by Unknwon** [comment]
You can always use `make build/release TAGS="xxx"`, the tags are not available all at once based on your platform, so I don't think there is any value to add this command.

**Comment by tjyang** [comment]
Thanks for the quick response and this tip "make build/release TAGS="xxx"". I am good now.
