### ISSUE TITLE
组织和团队有啥区别

### ISSUE THREAD

**Issue by xiaomi008** [gogits/gogs#1912]
如题，这俩有啥区别，分别对应什么场景？

我们想找一个本地git托管服务用于部门代码归档、开发协作，大概20多个人，不想有太复杂的权限设置，每个人都能创建仓库，公开的话默认其他组员都能看到，同时具备推拉权限，该如何设置能够实现？

**Comment by Unknwon** [comment]
Hi,

1. Meaning of team and organization are the same in the dictionary. 
2. Teams belong to organization which should be very obvious by just looking at the web UI.
3. For your situation, create a `members` teams with `push` permission level, and add all repositories to `members` team.

**Comment by xiaomi008** [comment]
用了一天，非常无语。
1 团队、组织区分没发现有啥意义。

2 首先后台添加了2个不同账号（用户），A、B和C。

3 之后创建了一个组织O，然后在这个组织下创建了一个团队T，设置权限为读取+写入。

4 把创建的A和B账户加入到这个团队T成员里面。

5 退出，用A账户登录，创建了一个仓库R，发现这个仓库只能属于A，不能属于整个团队，然后往仓库推送内容，成功。
6 退出，用B账户登录，你知道想找到A的那个仓库R有多难吗？先点右边的组织O，然后跳到组织O页面，然后在点击右边的团队T，注意上面提示2个成员，0个仓库，我的R仓库被吃了吗？然后点击A用户，才看到A用户下面那个R仓库。
7 直接用C账户竟然也可以下载R仓库的内容，这是闹哪样啊？C不是跟A在一个团队啊

按照我的理解，A和B是一个团队，仓库就默认是共享的，A的任何非私有仓库，团队成员都是具备读、写操作的，团队以外都是不可见的，而在试用了几次，真的是摸不着头绪，不知道gogs搞什么组织、团队有啥意义？

**Comment by Unknwon** [comment]
Your information contains many vague words and vague concepts.

> 2 首先后台添加了2个不同账号（用户），A、B和C。

2 or 3?

> 5 退出，用A账户登录，创建了一个仓库R，发现这个仓库只能属于A，不能属于整个团队，然后往仓库推送内容，成功。

Create R for who? personal or for organization? 

> 6 退出，用B账户登录，你知道想找到A的那个仓库R有多难吗？先点右边的组织O，然后跳到组织O页面，然后在点击右边的团队T，注意上面提示2个成员，0个仓库，我的R仓库被吃了吗？然后点击A用户，才看到A用户下面那个R仓库。

Same as above, why should a personal repository show as a organization's if you create it as personal?

>  直接用C账户竟然也可以下载R仓库的内容，这是闹哪样啊？C不是跟A在一个团队啊

If you created a public repository, why can't people clone it? And you did not provide information about you created a private or public repository for A.

> 按照我的理解，A和B是一个团队，仓库就默认是共享的，A的任何非私有仓库，团队成员都是具备读、写操作的，团队以外都是不可见的，而在试用了几次，真的是摸不着头绪，不知道gogs搞什么组织、团队有啥意义？

From mu understanding, you have many missing concepts about what is private and what is public, what is a unit and what is not.

I'm sorry for that but we do not provide this kind of training here.

**Comment by BizShuk** [comment]
organization => company
team => department  or small unit 
@Unknwon  you are right

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
