### ISSUE TITLE
select a repository show 500 error

### ISSUE THREAD

**Issue by soaringloong** [gogits/gogs#1913]
when recover the sql database from a backup, but no recover the repository file, select the repository will show 500 error page. 
The log is :
![image](https://cloud.githubusercontent.com/assets/11831154/11053403/b4b7e97c-879b-11e5-9518-0a00e7d8b757.png)
 maybe in this case should tell user the repository cannot find and give user two choice : 1:remove the repository from db, 2: upload the repository files.
Thinks.

**Comment by Unknwon** [comment]
Thanks your feedback!

> when recover the sql database from a backup, but no recover the repository file, select the repository will show 500 error page. 

This is what exactly 500 error means, internal server error.

> 1:remove the repository from db

If you want this, you should change the issue title to something like `able to remove missing repositories`.

> 2: upload the repository files.

I can change the error message to like `directory not found` instead of `GetTags fail xx`. Do you want this?

**Comment by soaringloong** [comment]
show 500 error cannot help location problem. show the directory file not found is better.

1:And if the login user is admin or the repository owner, show the remove button. just like you sayed
"able to remove missing repositories."

2:upload the files maybe is no need. because this is uncommon case. so please ignore it.

**Comment by Unknwon** [comment]
> show 500 error cannot help location problem.

If you're running dev mode, page will have error itself.

> 1:And if the login user is admin or the repository owner, show the remove button. just like you sayed
"able to remove missing repositories."

No, it's going to be added in admin dashboard, to scan all repositories, not for a single repo.
