### ISSUE TITLE
some repository pull/push with ssh show "Gogs:Internal error"

### ISSUE THREAD

**Issue by soaringloong** [gogits/gogs#1914]
When i pull/push some repository with ssh, it failed and the message is 
![default](https://cloud.githubusercontent.com/assets/11831154/11054631/6e215bac-87a9-11e5-9e4c-c17498b4ab84.png)

but when i do it with http, it's OK.

**Comment by Unknwon** [comment]
Please see https://gogs.io/docs/intro/troubleshooting#git

**Comment by Unknwon** [comment]
A quick solution is to use all lower case letters.
