### ISSUE TITLE
push error, the hooks/update path is not config file path.

### ISSUE THREAD

**Issue by soaringloong** [gogits/gogs#1916]
the log:
git.exe push -v --progress  "http" master:master

Counting objects: 125, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (73/73), done.
Writing objects: 100% (124/124), 108.75 KiB | 0 bytes/s, done.
Total 124 (delta 41), reused 121 (delta 41)
POST git-receive-pack (111518 bytes)
<b>remote: hooks/update: line 2: /opt/gogs/gogs: No such file or directory</b>
remote: error: hook declined to update refs/heads/master
Pushing to http://git.sloong.com:3333/public/tools.git
To http://git.sloong.com:3333/public/tools.git
! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'http://git.sloong.com:3333/public/tools.git'

I install the gogs by binary, and the path is /home/www/git/ the opt folder no have gogs folder.
so now, i should do what?

**Comment by Unknwon** [comment]
I suppose you copied the repositories from another Gogs installation.

Go to admin dashboard and do:

![image](https://cloud.githubusercontent.com/assets/2946214/11071509/30b61dc4-87af-11e5-9303-f2e48d993017.png)

**Comment by soaringloong** [comment]
thinks, when i run "Rewrite all update hook of repositories" . it is OK.

**Comment by Unknwon** [comment]
:100:

**Comment by oldthreefeng** [comment]
> I suppose you copied the repositories from another Gogs installation.
> 
> Go to admin dashboard and do:
> 
> ![image](https://cloud.githubusercontent.com/assets/2946214/11071509/30b61dc4-87af-11e5-9303-f2e48d993017.png)


@unknwon  this helps me !~!  谢谢
