### ISSUE TITLE
Can't tab into "close and comment" button

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1917]
I think related to #1824 it seems impossible to tab into the close and comment button after typing the message.

**Comment by Unknwon** [comment]
You should now be able to use tab switch to buttons and press `enter` key to trigger click event on `develop` and https://try.gogs.io .

**Comment by ChangePlaces** [comment]
I've been trying to tab here https://try.gogs.io/asdf3/test2/issues/1#issuecomment-363

One tab still hits the comment button, and not the close and comment button

**Comment by Unknwon** [comment]
@ChangePlaces make sure you did hard refresh, and the order is `textarea` - `comment` - `comment and close`, the highlight for `comment and close` is not visible.

**Comment by ChangePlaces** [comment]
ohhh I use the spacebar key to simulate a button press which doesn't work (but works for the comment button)

**Comment by Unknwon** [comment]
Yes, I have explicitly said works with `enter` key.

**Comment by Unknwon** [comment]
test

**Comment by Unknwon** [comment]
OK, I think I can make `space` bar work as well.

**Comment by Unknwon** [comment]
Please do a hard refresh and test with space bar.

**Comment by ChangePlaces** [comment]
just tested, and space bar doesn't have any effect other than scrolling the page down!

**Comment by Unknwon** [comment]
I'm very sure space bar works.

**Comment by ChangePlaces** [comment]
I type something in the comment box, then press tab and I'm on the comment button, I press tab again, and then press space and nothing happens other than the page scrolling down!

**Comment by Unknwon** [comment]
I just follow the steps you provided and made the comment: https://try.gogs.io/gogs/gogs/issues/26#issuecomment-373

**Comment by ChangePlaces** [comment]
interesting - i'm using firefox 42 - you?

**Comment by Unknwon** [comment]
Chrome 46... I think it's better to use `enter` key.

**Comment by ChangePlaces** [comment]
the tab key is on the left side of the keyboard, the enter key is on the far right side. so it becomes difficult to comment / close and comment with one hand negating the use of a keybaord shortcut!

**Comment by Unknwon** [comment]
> the tab key is on the left side of the keyboard, the enter key is on the far right side. so it becomes difficult to comment / close and comment with one hand negating the use of a keybaord shortcut!

I do not get the point at all. If just one side, why use keyboard at all?
