### ISSUE TITLE
repo address is not clickable / scrollable

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1918]
After creating a new repo, after clicking on the cloud icon, the ssh url isn't clickable - only copy-able. So, if I remember part of the url and type it out, I can't then go to the address and see what the last part is. This is also an issue if, instead of copying, you just want to see what it all is, for typing on a different machine.

**Comment by Unknwon** [comment]
Sorry I don't understand the problem?

**Comment by tboerger** [comment]
@Unknwon you can not read the full content of the copy-to-clipboard form field :)

**Comment by Unknwon** [comment]
Thanks. Any screenshot?

**Comment by Unknwon** [comment]
As I completely not understand and no further feedback, I'm going to close this issue for now.
