### ISSUE TITLE
Docker image tags on hub.docker.com

### ISSUE THREAD

**Issue by janos** [gogits/gogs#1919]
Hi,

Could you create release tags on hub.docker.com/r/gogs/gogs? It is very convenient to deploy gogs using docker containers and it works great. Using release tags would make it even easier to upgrade and use stable version and even rollback to the previous one.

Thank you,
Janos

**Comment by Unknwon** [comment]
Docker hub holds my request for 2 hours and hasn't started building.... WTH....

**Comment by Unknwon** [comment]
I think Docker hub is broken... I'll try later.

**Comment by Unknwon** [comment]
Docker hub is still broken for building image of a tag....

**Comment by janos** [comment]
Thank you for trying. I have successfully build the image locally `docker build -t gogs:0.7.0 .`, but after a few failed attempts where Step 4 or Step 8 are failing because of alpinelinux update/install failed or there were problems downloading packages. The build is taking very long and alpine actions is taking most of the time. I can not tell that this is the problem on public docker hub, but probably is related.

**Comment by Unknwon** [comment]
Thanks your info...

Possible, but the build details show that it is pending like 2 hours... and failed (I guess for timeout).

**Comment by Unknwon** [comment]
Good news... after pending 35mins... it is finally built: https://hub.docker.com/r/gogs/gogs/tags/

The funny thing is, it takes 1 minute to finish build..

**Comment by janos** [comment]
Great! Thank you. :)

**Comment by Unknwon** [comment]
:trollface:
