### ISSUE TITLE
500 error when merging a pull request

### ISSUE THREAD

**Issue by ChubbyNinja** [gogits/gogs#1921]
Been using a forked repo for a while with no issues, I have 29 merged pull requests on the master repo from this fork

Trying to merge the 30th and it comes up with a 500 error

In the stdout.log this is what it says:

```
[Macaron] Completed /svr1/si/pulls?type=all&sort=&state=open&labels=0&milestone=0&assignee=0 200 OK in 50.264442ms
[Macaron] Started GET /svr1/si/pulls/79 for 217.xx.xx.xx
[Macaron] Completed /svr1/si/pulls/79 200 OK in 302.220192ms
[Macaron] Started POST /svr1/si/pulls/79/merge for 217.xx.xx.xx
2015/11/10 14:54:56 [...routers/repo/pull.go:380 MergePullRequest()] [E] GetPullRequestByPullID: git pull: From /home/gitgogs/gogs-repositories/chubbyninja/si
 * branch            master     -> FETCH_HEAD

[Macaron] Completed /svr1/si/pulls/79/merge 500 Internal Server Error in 1.125154275s
```

fork repo is `chubbyninja/si` and master is `svr1/si`

I'm using Go 1.5 and Gogs · Version: 0.6.9.0903 Beta

Any idea what could be causing this error? Thanks!

**Comment by Unknwon** [comment]
@ChubbyNinja Hi... can you update to 0.7.0...

**Comment by ChubbyNinja** [comment]
Sure, doing that now and report back!

**Comment by ChubbyNinja** [comment]
Awesome - I didn't realise PR wasn't finished in 0.6.9.

0.7.0.1107 told me there was a conflict so couldn't auto merge - sorted :+1: thanks

**Comment by Unknwon** [comment]
:100:
