### ISSUE TITLE
Pull request fail to merge with BIN

### ISSUE THREAD

**Issue by wsantos** [gogits/gogs#1922]
I've tried to merge a PR within a binary and it says that PR has confict, after futher investigation I've found this problems:

1 - Patch file is incorrect, maye we should use `--binary` and `--full-index` in patch creation
```
diff --git a/containers/galera.ca/files/xz-5.2.2.tar.xz b/containers/galera.ca/files/xz-5.2.2.tar.xz
new file mode 100644
index 0000000..2997653
Binary files /dev/null and b/containers/galera.ca/files/xz-5.2.2.tar.xz differ
```
2 - If you try to apply the patch manually we receive this error:

```
error: cannot apply binary patch to 'containers/galera.ca/files/xz-5.2.2.tar.xz'; without full index line
error: containers/galera.ca/files/xz-5.2.2.tar.xz: patch does not apply
```

Suggestions: We should be able to see git commands output and also the full command in logs if debug is enabled, it would help a lot to track down problems between git+gogs.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Hi, I've pushed fix to `develop`, add `--binary` should solve the problem (it includes --full-index by default I think). And print full output when there is conflict.

**Comment by Unknwon** [comment]
Close as fixed.
