### ISSUE TITLE
How config the HTTPS?

### ISSUE THREAD

**Issue by soaringloong** [gogits/gogs#1924]
I ues the chrome open the website, it show the url is unsafe. 
![image](https://cloud.githubusercontent.com/assets/11831154/11082332/3eccd8b6-885f-11e5-9328-6fb3e2109b1d.png)
![image](https://cloud.githubusercontent.com/assets/11831154/11082460/5188b67c-8860-11e5-826b-aefccf897388.png)

I ues https url to connect to nginx and nginx use http agence to gogs.
I was configured the ssl key in nginx.
And i just have two keys file : .crt and .key.
How should i do now? change the nginx agence to https ?

**Comment by JokerQyou** [comment]
You should configure `ROOT_URL ` and `DOMAIN` options for gogs to render all resource links correctly. Doc ref: [here]( http://gogs.io/docs/advanced/configuration_cheat_sheet )

**Comment by soaringloong** [comment]
ROOT_URL and DOMAIN is configured . but it is used the 3000 port . 
I don't want input the port number in url .

**Comment by JokerQyou** [comment]
No you don't need to put port in these option values. Gogs will listen on the port specified by `HTTP_PORT` option. `ROOT_URL` and `DOMAIN` are used for links only. See #1794 .

**Comment by soaringloong** [comment]
![image](https://cloud.githubusercontent.com/assets/11831154/11088183/2e5c9502-889b-11e5-970c-e3c85d247902.png)
this is my gogs config.

![image](https://cloud.githubusercontent.com/assets/11831154/11088202/59a3d6bc-889b-11e5-8b3d-a98c55b53eea.png)
this is my nginx config.
If i want to go the gogs site have two url:
http://git.sloong.com:3000/
https://git.sloong.com

I just used the https://git.sloong.com ..

**Comment by JokerQyou** [comment]
For HTTPS, simply proxy all traffic from 443 port to `HTTP_ADDR:HTTP_PORT` of gogs, and set `ROOT_URL` to a URL starting with `https://`.
But I'm not sure if gogs can support HTTP and HTTPS at the same time, have to wait for @Unknwon 's reply on that.

**Comment by Unknwon** [comment]
Here is an example config for https://try.gogs.io:

```nginx
server {
        listen 443 ssl;
        server_name try.gogs.io;
        ssl_certificate /etc/ssl/startssl/gogs.io.unified.crt;
        ssl_certificate_key /etc/ssl/startssl/gogs.io-decrypted.key;

        location / {
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_pass http://localhost:3001$request_uri;
        }
}

server {
        listen 80;
        server_name try.gogs.io;
        return 301 https://$host$request_uri;
}
```

**Comment by tboerger** [comment]
You want to set ROOT_URL to https://git.sloong.com and you want to append $request_uri to the proxy_pass nginx directive. Then it should already work.

**Comment by tboerger** [comment]
Take a look at https://www.ssllabs.com/ssltest/analyze.html?d=git.sloong.com it will show and more or less explain which parts are configured bad.

**Comment by Unknwon** [comment]
> Take a look at https://www.ssllabs.com/ssltest/analyze.html?d=git.sloong.com it will show and more or less explain which parts are configured bad.

Nice tool!

**Comment by soaringloong** [comment]
I didn't do anything. but when i open it today, it is be safe'd site....
![image](https://cloud.githubusercontent.com/assets/11831154/11140407/f3ff37cc-8a14-11e5-8aa9-de609e9be182.png)

**Comment by JokerQyou** [comment]
O well that's about resource cache then. :)
