### ISSUE TITLE
Side-by-side diff view

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#1925]
I don't know how hard it would be to implement it. Feel free to close this issue if you don't intent to bring this to Gogs.

Side-by-side diff is supported by GitHub and GitLab, and I think it is much easier to see a what changed in a commit. Don't know what tool they use, though.

![sidebyside3](https://cloud.githubusercontent.com/assets/7011819/11095885/45f39520-887e-11e5-9d18-48aa52988fc1.png)

![sidebyside2](https://cloud.githubusercontent.com/assets/7011819/11095819/fb67fbcc-887d-11e5-894b-627433d48b09.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

But may take long long time... I am not sure.. :sweat_smile:

**Comment by andreynering** [comment]
No problem. :+1: 

Yeah, it seems harder than I thought. I know you take care of everything alone here. Thank you for your work!

**Comment by Unknwon** [comment]
Hmmm... I don't think you need to close it, you can keep it open maybe one day this can be implemented.

**Comment by andreynering** [comment]
@Unknwon :+1:

**Comment by bkcsoft** [comment]
I'm currently working on this, will claim the issue as soon as I'm in front of a computer again

**Comment by bkcsoft** [comment]
Got it working! Now I just need some buttons for it ;)
![2015-12-26-114558_1600x900_scrot](https://cloud.githubusercontent.com/assets/4726179/12006108/fe028894-abc7-11e5-901e-b617752bb379.png)

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2296

**Comment by bkcsoft** [comment]
shouldn't this be closed? as the feature was merged with #2296 :)

**Comment by Unknwon** [comment]
@bkcsoft auto-close happens with commits are merged to `master`.

**Comment by bkcsoft** [comment]
Aah, that explains it :)

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by illyasv** [comment]
just installed Gogs 0.9.115.0103 on the server, but can't find where to see the diff side by side, only Split View is available. Searched the discussions, but not found how to enable this function on our installation. 

Can anyone help me to get that working?

**Comment by bkcsoft** [comment]
@illyasv Split view is Side-by-Side view :)

**Comment by illyasv** [comment]
@bkcsoft but it doesn't work that way, please take a look at the attachment, when i click on Split View it just shows the same as on the screenshot, and there is no other option to change to other view. 
![split](https://cloud.githubusercontent.com/assets/1158142/22552446/a89a2140-e961-11e6-8e10-ffa102e71377.png)

**Comment by illyasv** [comment]
@bkcsoft  one more adjustment to the issue: it appears when I want to compare branches, if I go to commit and open it's details, then the diff is shown side by side, but if I go to compare branches, the side-by-side option doesn't work.

**Comment by bkcsoft** [comment]
@illyasv Seems to work just fine on try.gogs.io
![2017-02-02-163136_1916x1036_scrot](https://cloud.githubusercontent.com/assets/4726179/22555769/1f223426-e965-11e6-942f-b7a075442bde.png)

**Comment by illyasv** [comment]
@bkcsoft I've just created a TestRepo1 there and added you as a collaborator. If you go to the Source tab, then click on the green "Compare" button, choose master and branch1 to compare you will see there is an option there to see a Split View, but it doesn't work, if you click on it you'll stay with the same inline view. Okay, i think it works this way not only for this TestRepo1, but for all currently hosted on try.gigs.io. Please try and you'll see what I mean.

**Comment by bkcsoft** [comment]
Interesting, the compare-controller doesn't have any logic for split-view 😕 Should be relatively easy to add but I unfortunately don't have any time to work on it 🙁 

@Unknwon Maybe open this again? or a new issue for that bug.

**Comment by Unknwon** [comment]
@bkcsoft I think file a new issue would be more clean and appropriate?
