### ISSUE TITLE
Wrong redirection after deleting system notice

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#1930]
I noticed there are some system notices in the admin panel, all of them are about network error when updating mirror repos. So I deleted one of them, but after the deletion, gogs redirected me to the wrong position. 
Let's say I have control of the domain `a.com`, and I use `a.com/b/` for gogs, and I've configured gogs options as followed.

```ini
[server]
DOMAIN = a.com
ROOT_URL = https://a.com/b/
```

But after deleting the system notices (the deletion request wen well with `https://a.com/b/admin/notices/{ID}/delete`), gogs keeps redirecting me to `/admin/notices`, while the right URL would be `https://a.com/b/admin/notices`.

I think gogs should respond with full URL instead of only the path of target URL.

**Comment by Unknwon** [comment]
Hi! I've pushed fix to `master`, please help test again. (though I'm going to release new version now...)

**Comment by JokerQyou** [comment]
Just upgraded to `0.7.6`, fix confirmed.
