### ISSUE TITLE
Test patch does not checkout correct base branch

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#1931]
I'm using version ```0.7.4.1110 Beta```.

1. I created an organization and migrated a repository.
2. I forked this repository.
3. I changed one line and pushed this back to my gogs repo.
4. I open a pull-request to the organization's repo.
5. gogs tells me that there is an merge conflict.

![screen shot 2015-11-12 at 15 47 45](https://cloud.githubusercontent.com/assets/2091312/11121190/c3cbe0e8-8954-11e5-9605-dac393e35913.png)

![screen shot 2015-11-12 at 15 46 27](https://cloud.githubusercontent.com/assets/2091312/11121168/9b86508c-8954-11e5-9d91-73d26632fbf1.png)

**Comment by stonerl** [comment]
This is the patch file in the gogs repo:

```diff
diff --git a/config/deploy.rb b/config/deploy.rb
index 1761ac1..df56e74 100644
--- a/config/deploy.rb
+++ b/config/deploy.rb
@@ -5,7 +5,7 @@ require 'rvm/capistrano' # Load RVM's capistrano plugin.
 set :rvm_type, :system # Copy the exact line. I really mean :system here
 
 set :application, 'Zenodotos'
-set :repository, 'git://rokuhara.japanologie.tld/Zenodotos.git'
+set :repository, 'http://rokuhara.japanologie.tld/gogs/Bibliothek/Zenodotos.git'
 
 set :scm, :git
 # Or: `accurev`, `bzr`, `cvs`, `darcs`, `git`, `mercurial`, `perforce`, `subversion` or `none`
```

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your PR index? `/user/repo/pulls/{index}`.

And use this index to find the corresponding patch file at `repo_root_path/user/repo/pulls/{index}.patch`.

Then try to apply this patch to your organization's repository, see what Git gives you.

**Comment by stonerl** [comment]
@Unknwon 

The PR index is ```1``` and the file is called ```1.patch```

When I download the patch-file and apply it to my local organization repo I don't get any error.

```bash
$ git apply --stat 1.patch
 config/deploy.rb |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
```bash
$ git apply -v 1.patch
Checking patch config/deploy.rb...
Applied patch config/deploy.rb cleanly.
```

**Comment by Unknwon** [comment]
Thanks! Is the patch content same as you post at https://github.com/gogits/gogs/issues/1931#issuecomment-156133423 ?

**Comment by stonerl** [comment]
Yes that is the patch. I only shortened the URL in the comment.

**Comment by Unknwon** [comment]
This is .. hmm, OK.

Can you try close and reopen this PR?

**Comment by stonerl** [comment]
Tried this the PR still has conflicts here is the log:

```
[Macaron] Started POST /Bibliothek/Zenodotos/issues/1/comments for xxx.xxx.xxx.xxx
2015/11/12 18:57:34 [T] TestPullRequests[14]: processing test task
2015/11/12 18:57:34 [T] PullRequest[14].testPatch(patchPath): /home/gogs/gogs-repositories/bibliothek/zenodotos.git/pulls/1.patch
2015/11/12 18:57:34 [T] PullRequest[14].testPatch(apply): has conflit
2015/11/12 18:57:34 [T] Issue[14] status changed to closed: false
[Macaron] Completed /Bibliothek/Zenodotos/issues/1/comments 302 Found in 271.681444ms
[Macaron] Started GET /Bibliothek/Zenodotos/pulls/1 for xxx.xxx.xxx.xxx
[Macaron] Completed /Bibliothek/Zenodotos/pulls/1 200 OK in 169.526997ms
```

**Comment by Unknwon** [comment]
OK, just to make sure:

1. the forked repo was keep in sync with the organization one
2. and you changed a line in forked repo

Yes?

**Comment by stonerl** [comment]
Exactly.
1. I forked it from the organization.
2. Changed one line in the forked repo.
3. The organization repo was never changed.

**Comment by Unknwon** [comment]
OK, let me check. Thanks for following up!

**Comment by Unknwon** [comment]
Hi @stonerl , would you be able to reproduce it on https://try.gogs.io ?

**Comment by stonerl** [comment]
Hi @Unknwon here is the PR https://try.gogs.io/Bibliothek/Zenodotos/pulls/1

**Comment by Unknwon** [comment]
Thanks!

**Comment by Unknwon** [comment]
OK, I've found and fixed the bug, please try again! https://try.gogs.io/Bibliothek/Zenodotos/pulls/1

**Comment by stonerl** [comment]
@Unknwon you're awesome. Could merge it now.

**Comment by Unknwon** [comment]
Thanks!

But found some UI issue, working on it now :joy:

![image](https://cloud.githubusercontent.com/assets/2946214/11170611/a678faa8-8ba7-11e5-9e24-f23b068e7fac.png)

**Comment by stonerl** [comment]
:+1: :smile:

**Comment by Unknwon** [comment]
OK fixed!
