### ISSUE TITLE
Problem with certain characters

### ISSUE THREAD

**Issue by Crayon2000** [gogits/gogs#1937]
Hello, I'm having some problems when I enter the character `'` for the full name. It is being replaced with the HTML code `&#39;`
The same problem occurred with `&` in the Organization Full Name. It was replaced with `&amp;`
It was tested with Version: 0.7.6.1112 Beta.

This is what happens when using the name Conan O'Brien:
![character-escape](https://cloud.githubusercontent.com/assets/11451841/11134369/1ea68756-896a-11e5-95ab-df63abedf3b8.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
This character is sanitized by Gogs's Sanitizer. Currently have no idea how to fix it, because https://try.gogs.io/testuser

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

You need update name again.

**Comment by Crayon2000** [comment]
@Unknwon, I have just tested on https://try.gogs.io and it seems to work great for the **User Full Name** and the **Organization Full Name**. My colleague with an apostrophe in is name will be thankful that it is fixed 😄
