### ISSUE TITLE
Disable change Username and Password for LDAP users

### ISSUE THREAD

**Issue by Crayon2000** [gogits/gogs#1938]
Hi, when a user uses LDAP authentication, he should not be able to change is Username and Password.

Advantages of **not** letting the user change is credetials:
* User will use a known credential. Less chances of losing the password.
* When a member of staff leaves you can simply disable / delete the Active Directory account but the details will still be availible in Gogs.

I'm using a Bug Tracker named [Mantis](https://www.mantisbt.org/). Here is the UI with LDAP enabled and disabled:
![mantis-ldap](https://cloud.githubusercontent.com/assets/11451841/11134904/7b236edc-896e-11e5-9f8d-fbfa959f90be.png)

They also have a setting to force the email address from the Active Directory (`$g_use_ldap_email = ON;`). In Gogs this would mean to disable changing the primary e-mail. But for now, this might be a problem because the primary e-mail is not retrieved on Active Directory.

They have another setting for the user Full Name (`$g_use_ldap_realname = OFF;`) in case we want LDAP to mange it. In that case the Full Name would also be disabled.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Now on `develop` branch, non-local users are not allowed to change their password.

**Comment by Unknwon** [comment]
Close as implemented.
