### ISSUE TITLE
ldap authentication

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#1939]
I have been trying to setup the ldap authentication, but i am not able to get it working, so i could use other eyes on this. I am rather new to ldap, so im am not sure what to put where in the settings screen.
If i use ldap browser by softerra i will find all my users in this path or what ever it's called. note that i changed company name and initials.

CN=My Full Name,OU=AAR,OU=DK,OU=VISTA,OU=Company group,DC=domain,DC=net

beneath here is a lot of attributes, one of them is initials 

User DN: OU=AAR,OU=DK,OU=VISTA,OU=Company group,DC=domain,DC=net
User Filter: (&(objectCategory=Person)(objectClass=User)(initials=%s))

the log stats: 
[Macaron] Started POST /user/login for 192.168.1.2
2015/11/13 07:32:33 [T] LDAP will bind directly via UserDN template: OU=AAR,OU=DK,OU=VISTA,OU=Company group,DC=domain,DC=net
2015/11/13 07:32:33 [T] Binding with userDN: OU=AAR,OU=DK,OU=VISTA,OU=Company group,DC=domain,DC=net%!(EXTRA string=my initials)
2015/11/13 07:32:33 [D] LDAP auth. failed for OU=AAR,OU=DK,OU=VISTA,OU=Company group,DC=domain,DC=net%!(EXTRA string=my initials), reason: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1

**Comment by Unknwon** [comment]
Hi,

I'm not sure what exactly the problem is, but I suppose you have read https://gogs.io/docs/features/authentication ?

**Comment by variablenix** [comment]
Hello,

The log provided seems to indicate a problem with user credentials. Please check this.

`ldapwhoami -vvv -h <hostname> -p <port>  -D <user-bind-dn> -x -W`

should return 

`Result: Success (0)`

**Comment by renewsorensen** [comment]
I did read the manual yes, but i am not that familiar with ldap though. What i am trying is to have my users authenticate against our domain. In the image attached, i used softerra ldap browser to drill down into where a section, where our users begin. The base line is OU=VISTA. Underneath OU=AAR is my users. An example is Abhay Kant beneath him is attributes like initials etc.

I don't know the tool ldapwhoami, and it seems to me, that it is part of an enterprise solution, correct me if i am wrong, or please provide me with a link where i can download that tool?

![ldap_attributes](https://cloud.githubusercontent.com/assets/10239939/11207840/e7d273be-8d17-11e5-8ca8-a9d522a983c9.PNG)

![ldap](https://cloud.githubusercontent.com/assets/10239939/11207546/2121d3aa-8d16-11e5-84a9-798d58601379.PNG)

**Comment by tboerger** [comment]
ldapwhoami is a command line tool on Linux.

**Comment by Unknwon** [comment]
cc @SergioBenitez

**Comment by Unknwon** [comment]
Form the error message, I think you're missing some placeholder `%s` in the settings.

Would you mind take a full screenshot of settings page?

**Comment by wqweto** [comment]
@renewsorensen: Here is my config agains our AD
```
Authentication Type LDAP (via BindDN)
Authentication Name: ucs.local
Host: 172.17.17.98
Port: 389
Bind DN: CN=gogs,OU=System,OU=UCS Users,DC=ucs,DC=local
Bind Password: •••••••••• (Warning: This password is stored in plain text. Do not use a high privileged account.)
User Search Base: OU=UCS Users,DC=ucs,DC=local
User Filter: (&(objectClass=user)(sAMAccountName=%s))
Admin Filter:
First name attribute: givenName
Surname attribute: sn
E-mail attribute: mail
```
My domain controller is at `172.17.17.98`. `Bind DN` is a designated gogs@ucs.local in `UCS Users\System` org. unit (make it a member of Domain Guests to strip permissions) that is used for LDAP quering. User accounts for gogs are in `UCS Users` org. unit, my admin filter is empty so only first "standard" gogs user is the administrator.

User Filter might include only *active* accounts but I'm unable to query `(!(userAccountControl:1.2.840.113556.1.4.803:=2))` -- probably a bug here in LDAP connector implementation.

Attributes are important to set properly for gogs to be able to format `"FirstName LastName <email@domain.com>"` on user actions.

You can use `dsquery` utility on the AD machine to get LDAP connection strings like this
```
C:\Users\wqw>dsquery user -name a*
"CN=Administrator,CN=Users,DC=ucs,DC=local"
"CN=apacheservice,OU=System,OU=UCS Users,DC=ucs,DC=local"
```

@Unknwon @SergioBenitez: Current implementation of `User/Admin Filter` uses `sprintf` to replace `%s` with username. This limits possible uses here e.g. `(&(|(sAMAccountName=%s)(mail=%s))(objectClass=user))` would allow users to logon either with AD account name or AD email but now produces invalid query `(&(|(sAMAccountName=wqw)(mail=%!s(MISSING)))(objectClass=user))` in gogs.log. Probably a simple `strings.Replace` is better for placeholders completion here.

**Comment by wqweto** [comment]
Ahhh, `explicit argument indexes` again! `(&(|(sAMAccountName=%[1]s)(mail=%[1]s))(objectClass=user))` works as expected.

Sorry to bother you, again.

**Comment by SergioBenitez** [comment]
@wqweto I'm glad you found that.

@renewsorensen Indeed, as @Unknwon pointed out, your settings aren't using the placeholder '%s' for the login name. Based on what you said so far, you should likely configure LDAP in Gogs via Simple Auth and use settings similar to the following:

UserDN: CN=%s,OU=AAR,OU=DK,OU=VISTA,OU=Company group,DC=domain,DC=net
Filter:  (&(objectCategory=Person)(objectClass=User))

Then, a user would log in with their full name, i.e., "Abhay Kant", and their LDAP password.

**Comment by Unknwon** [comment]
@SergioBenitez 

> Then, a user would log in with their full name, i.e., "Abhay Kant", and their LDAP password.

I think wouldn't be able to allow space in the username?

**Comment by renewsorensen** [comment]
Well it turned out that i did not understand ldap enough, i was missing a binding dn that pointed directly to an ad user, and my uesr dn should point at the top level of the user area, and then use the filter (initials=%s). That worked, thanks for a good service you provide here :+1:

**Comment by Unknwon** [comment]
:tada:

**Comment by codecrafting-net** [comment]
With the new version 0.11.39 I was able to connect with ldap (Microsoft AD) with BindDN option using DOM\\%s. However, I have to give the password. Would be nice to get the password from the login form and use it as the password to bind the ldap. When I provide no password (on the authentication config screen) gogs will perform a anonymous search, which on my case is not allowed. My account don't have write permissions, so I can't create a user for the gogs. On the authentication menu could have a checkbox like "use login password to bind".
