### ISSUE TITLE
看不到指派给我的工单

### ISSUE THREAD

**Issue by cyqluowang** [gogits/gogs#1940]
在私有仓库，添加协作者后，给他发工单，在主页的工单管理看不到   指派给您的  工单。
创建组织后同样给队友创建工单，在主页的工单管理也是看不到的。
要进入的项目才能看到，逻辑不对吧？
难道一定要public 的项目才可以？

**Comment by Unknwon** [comment]
Thanks your feedback!

Currently you can only see issues in the repository you're owner of, and this is duplicated to https://github.com/gogits/gogs/issues/1820
