### ISSUE TITLE
can't change domain name

### ISSUE THREAD

**Issue by amery** [gogits/gogs#1941]
I'm running master as of 2015-11-04 (603c7389b8e56740033e51b36b79e61136b46002) using docker-compose as provided. Now I need to change the "domain" from the temporary name to the permanent.

unfortunately changes done to /data/gogs/conf/app.ini are totally ignored and the containers don't provide a command line `mysql` client.

I couldn't even find the schema to attempt to write a go app for the purpose...

**Comment by Unknwon** [comment]
Hi, I suppose you have read the docker dictionary Readme and restarted Gogs?

**Comment by Unknwon** [comment]
Typo: directory

**Comment by amery** [comment]
I used `docker-compose` instead of docker manually as I assumed that was the preferred way. after stopping rm-ing and restarrting the problem is solved. thank you.

**Comment by Unknwon** [comment]
Cool! I should remove that compose file 😂😂
