### ISSUE TITLE
Branch/Tag-Selection has wrong z-index

### ISSUE THREAD

**Issue by Janfred** [gogits/gogs#1942]
I found the problem, that you can't select the last few branches/tags, if they are vertically under the Headline of the Readme.

A sample is in https://git.local.janfred.de/rieckers/issue-1932

**Comment by Unknwon** [comment]
Thanks, I've noticed this.

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/janfred/issue-1932/

**Comment by Janfred** [comment]
Looks good!
Thanks :)

**Comment by Unknwon** [comment]
@Janfred thanks your confirmation!
