### ISSUE TITLE
Able to config fsck timeout

### ISSUE THREAD

**Issue by rubenv** [gogits/gogs#1943]
It seems that the timeout for fsck is 60 seconds.

One of the git repositories I'm hosting is 9 gigabytes, which causes the health check to be marked as failed (sometimes, not all the time, depends on the system load).

Could we increase this timeout slightly for health checks?

**Comment by Unknwon** [comment]
Hmm... yeah, should be able to add a config option for this.

**Comment by Unknwon** [comment]
Now on `develop` branch, you can use https://github.com/gogits/gogs/blob/develop/conf/app.ini#L299 to config timeout, the syntax is 

> A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

**Comment by rubenv** [comment]
That's perfect. Thanks a lot!

**Comment by linquize** [comment]
What happen when timeout?  Kill git fsck?

**Comment by Unknwon** [comment]
@linquize yes

**Comment by linquize** [comment]
When and where to do fsck in gogs?

**Comment by Unknwon** [comment]
Admin monitoring panel.

**Comment by Unknwon** [comment]
Close as implemented.
