### ISSUE TITLE
Drop /org/ URL path prefix in organization home page

### ISSUE THREAD

**Issue by nanoant** [gogits/gogs#1944]
Since anyway we cannot organizations and users with same name co-exists (which is okay), what is the point of having URL for organization in form `gogs.org/org/orgname` where user page is simply `gogs.org/username`. Why we cannot have simply `gogs.org/userororgname` like in GitHub? It would be great to keep URLs as simple as possible.

**Comment by Unknwon** [comment]
Hi, maybe you're right. 

For now, if you visit `gogs.org/userororgname` gogs will redirect for you.

**Comment by nanoant** [comment]
> For now, if you visit gogs.org/userororgname gogs will redirect for you.

Yeah I know. Still I'd prefer it works like others, GitLab, Twitter, Facebook, they all use simple `service/name` schema regardless if name is organization or user.

Keeping it at same level would help to avoid simple mistakes, like I wanted share link to README of my project: `https://try.gogs.io/myteam/myproject/src/master/README.md`, oops that's 404, I forgot `org` should write `https://try.gogs.io/org/myteam/myproject/src/master/README.md`

This is because you redirect just `try.gogs.io/myteam` -> `try.gogs.io/org/myteam` but not every URL starting with that.

And finally it may happen that somebody wants "convert" user into organization, then all existing URLs will stop working, even the name will be still there.

**Comment by Unknwon** [comment]
Make sense, will do.

**Comment by Unknwon** [comment]
Just realized that your example is invalid. 

> https://try.gogs.io/org/myteam/myproject/src/master/README.md

This is indeed 404.

Close until better example prove.

**Comment by nanoant** [comment]
@Unknwon You are right, the example was purely theoretical and invalid. Now let's consider real test with two repositories:

1. https://try.gogs.io/nanoant/somerepo/src/master/README.md (repo under user account)
2. https://try.gogs.io/nanoants/somerepo/src/master/README.md (repo under organization account)

Gogs is not adding `/org/` prefix to repo URL, it uses it only for organization pages:

1. https://try.gogs.io/nanoant
2. https://try.gogs.io/org/nanoants

So my complaint still somehow holds, because:

1. https://try.gogs.io/org/nanoants/somerepo gives 404 and there's no redirect to https://try.gogs.io/nanoants/somerepo
2. https://try.gogs.io/org/nanoants is not parent of https://try.gogs.io/nanoants/somerepo, so `somerepo/` relative link from org page does not point to the repository. (this works for user)
3. URL scheme for user is not consistent with scheme for organization.

Finally my question to you is what is the purpose of `/org/` prefix at all? Does it bring any benefit?

**Comment by Unknwon** [comment]
OK, I think your point the is home page of organization should remove `org` prefix.

> Finally my question to you is what is the purpose of /org/ prefix at all? Does it bring any benefit?

Organization has many things personal account does not have, such as teams, members, teams settings. Add `org` prefix is more precise for routing.

**Comment by nanoant** [comment]
@Unknwon Thanks for renaming the subject of this issue. Yes, dropping `/org/` prefix is what I wanted. (btw. I've mistakenly put "suffix" there in subject).
P.S. I am really impressed by your work and your support.

**Comment by Unknwon** [comment]
:trollface: Glad you like Gogs!

**Comment by Unknwon** [comment]
Hi, I've pushed code to `develop`, you can also test on https://try.gogs.io/gogs

**Comment by nanoant** [comment]
Works like a charm. Thank you!

**Comment by Unknwon** [comment]
Thanks your confirmation!
