### ISSUE TITLE
centos7 install ,then miss the page

### ISSUE THREAD

**Issue by greatpie** [gogits/gogs#1945]
我用的是二进制安装，然后在http://domin:3000/install 填写了配置信息，接着整个页面打不开了，再次打开http://domin:3000/也会报错

**Comment by Unknwon** [comment]
> 然后在http://domin:3000/install 填写了配置信息

Have you changed the HTTP port?

**Comment by greatpie** [comment]
However,I haven't change it.I input "./gogs web" and start it again,then the install page run well and the same problem exists.In the last time, I try to fill user with "root" not "git" in the form so I got it.It seems to be a permission problem that I haven't find it.Thanks a lot after all.

**Comment by Unknwon** [comment]
Hmm... I don't get it, so what is the problem now exactly?

**Comment by Unknwon** [comment]
Any updates?

**Comment by greatpie** [comment]
sorry , I receive your message a liiter late.The problem is user permission of my operate system not your code.

**Comment by Unknwon** [comment]
:trollface: Hmm... OK, so have you resolved the problem?

**Comment by greatpie** [comment]
Yeah,Thanks a lot.I am trying to use git hooks now.I must say gogs is quite easy to get start.

**Comment by Unknwon** [comment]
:tada: Glad you like it!
