### ISSUE TITLE
Error message while updating

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#1946]
Hi,

on my Raspberry 2 I treid to update gogs. Before I updated go-gogs-client.
    
    pi@focmb-pi ~/srcs/go/src/github.com/gogits $ git clone -b develop https://github.com/gogits/gogs.git
    cd gogs
    go get -u -tags "sqlite" ./...
    package github.com/gogits/gogs/modules/template: cannot find package "github.com/gogits/gogs/modules/template" in any of:
	/opt/go/src/github.com/gogits/gogs/modules/template (from $GOROOT)
	/home/pi/srcs/go/src/github.com/gogits/gogs/modules/template (from $GOPATH)

**Comment by Unknwon** [comment]
You need to update Gogs itself first.

**Comment by focmb** [comment]
I found the error.  I did a mistake when I copy the files. After deleting the gogs and clonign the dev branch again all is working. the issue can be closed. Thanks.

**Comment by Unknwon** [comment]
:trollface:
