### ISSUE TITLE
If issue form is filled in and user clicks close, open dialog with warning 

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1947]
If the user types in a title or a body for an issue, then presses the close on the tab, it'd be nice to have a pop up asking if they're sure they want to close down the tab.

**Comment by bkcsoft** [comment]
I think putting something like this in gogs.js would suffice: http://stackoverflow.com/questions/11844256/alert-for-unsaved-changes-in-form

**Comment by Unknwon** [comment]
@bkcsoft looks good! I'll try.

**Comment by bkcsoft** [comment]
Closed by #2980 (April 15th)
