### ISSUE TITLE
500 error on settings page

### ISSUE THREAD

**Issue by Sauermann** [gogits/gogs#1948]
When I try to access the settings page of the respository https://try.gogs.io/o1/r1/settings (Application Version: 0.7.10.1114 Beta) while I am logged in with my account "Sauermann", I get an 500 internal server error as response. It is a newly created repository without a single push to it.

After pushing the first commit, the 500 error vanishes and the correct setting page is displayed (tested it on https://try.gogs.io/o2/r2/settings)

Note: both are private repositories.

**Comment by Unknwon** [comment]
Thanks your feedback!

Please test again https://try.gogs.io/o1/r1/settings or `develop` branch.

**Comment by Sauermann** [comment]
https://try.gogs.io/o1/r1/settings looks now good. Thanks for the fast support.

**Comment by Unknwon** [comment]
No problem :trollface:
