### ISSUE TITLE
Debian Jessie - Init script not working

### ISSUE THREAD

**Issue by SoftCreatR** [gogits/gogs#1952]
● gogs.service - LSB: A self-hosted Git service written in Go.
	   Loaded: loaded (/etc/init.d/gogs)
	   Active: active (exited) since Sun 2015-11-15 18:16:58 CET; 6min ago
	  Process: 754 ExecStart=/etc/init.d/gogs start (code=exited, status=0/SUCCESS)

	Nov 15 18:16:57 rs000086 gogs[754]: Starting Go Git Service: gogs.

It doesn't create the pid file nor start gogs. Any idea what could be the problem?

gogs is installed in `/home/git/go/src/github.com/gogits/gogs` so `WORKINGDIR` has been overwritten via /etc/default/gogs:

	WORKINGDIR=/home/git/go/src/github.com/gogits/gogs
	DAEMON=/home/git/go/src/github.com/gogits/gogs/gogs

**Comment by SoftCreatR** [comment]
I was able to automate the startup using systemctl:

	[Unit]
	Description=Gogs (Go Git Service)
	After=syslog.target
	After=network.target
	After=mysql.service

	[Service]
	Type=simple
	User=git
	Group=git
	WorkingDirectory=/home/git/go/src/github.com/gogits/gogs
	ExecStart=/home/git/go/src/github.com/gogits/gogs/gogs web
	Restart=on-failure
	Environment=USER=git HOME=/home/git

	[Install]
	WantedBy=multi-user.target

**Comment by Unknwon** [comment]
I'm using systemd as well, can you make a PR to fix the init.d?

**Comment by Unknwon** [comment]
Any updates？

**Comment by SoftCreatR** [comment]
Just, that i'm no longer using the init.d script. Instead, i use a modified version (see above) of this: https://github.com/gogits/gogs/blob/master/scripts/systemd/gogs.service

I havent found the reason, why my Debian wont start gogs using the init.d script.

**Comment by Unknwon** [comment]
Cool, good to know. :trollface:

Closing it.

**Comment by SpikeShape** [comment]
I keep pulling my hair out on this init script. It's not working for me either. I am glad I found this issue here so I know I am not the only one with that problem.

Now I am gonna try using @SoftCreatR's systemctl. Thank you in advance!
