### ISSUE TITLE
500 error on dashboard

### ISSUE THREAD

**Issue by Sauermann** [gogits/gogs#1953]
After having deleted all my repositories, I get an 500 internal server error message on my dashboard https://try.gogs.io/ while logged in with my account Sauermann.

**Comment by Unknwon** [comment]
Thanks, I've noticed as well. But working on another issue now, may have to wait :D

**Comment by Unknwon** [comment]
OK, should be fixed by now!

**Comment by stonerl** [comment]
Can confirm that it is fixed.

**Comment by Unknwon** [comment]
Thanks your confirmation!
