### ISSUE TITLE
Cloudflare Full-SSL + nginx + gogs = failure

### ISSUE THREAD

**Issue by SoftCreatR** [gogits/gogs#1954]
I am currently trying to make the whole combination of Cloudflare (Full-SSL) + nginx (1.9.6) and gogs work, but it doesn't.

My config:

	[server]
	DOMAIN = gogs.host.tld
	HTTP_PORT = 3000
	PROTOCOL = https
	ROOT_URL = https://gogs.host.tld/
	DISABLE_SSH = true
	OFFLINE_MODE = true
	CERT_FILE = /home/git/go/src/github.com/gogits/gogs/custom/ssl/cert.cert
	KEY_FILE = /home/git/go/src/github.com/gogits/gogs/custom/ssl/key.key

And this is what happens:

`http: TLS handshake error from 127.0.0.1:33569: tls: first record does not look like a TLS handshake`

However, if i change `PROTOCOL` to `http` and start it, it works fine (and it's accessible via https).

My (very simple) nginx config:

	server {
		listen 80;
		listen [::]:80;
		
		server_name		gogs.host.tld;
		
		return 301 https://$host$request_uri;
	}

	server {
		listen 443 ssl http2;
		listen [::]:443 ssl http2;
		
		server_name		gogs.host.tld;
		
		access_log		/var/log/nginx/gogs.access.log;
		error_log		/var/log/nginx/gogs.error.log;
		
		location / {
			proxy_pass	http://gogs;
		}
	}

I'm afraid, that this could be a problem with go itself. But hope dies last.

**Comment by TheHowl** [comment]
What about letting nginx handle the HTTPS, and then redirecting everything through HTTP to gogs?

**Comment by SoftCreatR** [comment]
That's what i do atm. Interesting is, that i can't clone on Windows:

    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

While it works properly on the server. But this isn't a gogs problem.

**Comment by Unknwon** [comment]
Please checkout this issue: https://github.com/gogits/gogs/issues/1751

**Comment by Unknwon** [comment]
> But what exactly does the PROTOCOL option, if it works when HTTPS is handled by nginx?

It should be `http`.

**Comment by SoftCreatR** [comment]
With a little bit of work, i was able to make everything work as expected. Even Github for Windows does it's job now.

Just in case, that anyone tried it without success: The mingw lib that's shipped in Github for Windows is outdated and needs to be updated manually. Doing so allows you to get rid of

    SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

If you are using another client, make sure, that your local OpenSSL and Git installations are up to date.

**Comment by Unknwon** [comment]
@SoftCreatR thanks. So does the problem has been resolved?

**Comment by SoftCreatR** [comment]
For me, it is.

**Comment by Unknwon** [comment]
:trollface:

**Comment by khs1994** [comment]
location / {
        proxy_pass  http://gogs;
    }

http 改为 https
