### ISSUE TITLE
Disable version display

### ISSUE THREAD

**Issue by SoftCreatR** [gogits/gogs#1957]
For security reasons, there should be an option to disable the display of the version numbers (for gogs and also for go). I prefer not to expose it to everyone (specially on BETA software).

**Comment by TheHowl** [comment]
Why is that? It helps quickly understanding in what version errors happen when they do happen. What are these "security reasons" you are talking about? Say like, security vulnerability in gogs only for specific version?

**Comment by Unknwon** [comment]
Disable version will make debug quite hard.

**Comment by SoftCreatR** [comment]
To make this more clear: I am talking about the version number display in the page footer. An admin should be able to disable it. However, it should also be displayed in the admin dashboard and also be visible in logfiles. I am just talking about the public exposure.

> Say like, security vulnerability in gogs only for specific version?

Not just gogs. I mean... Even the go version is being exposed.

**Comment by Unknwon** [comment]
Thanks for clarifying!

Make sense, yes, can add an option to only display version in admin dashboard.

**Comment by Unknwon** [comment]
Fixed by #1992.
