### ISSUE TITLE
[UI] Release Page broken/inconsistent

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#1958]
The Release Page seems to be broken. It looks broken/is inconsistent when compared to the other sites.
e.g. the Header is blue.

**Comment by Unknwon** [comment]
Thanks, I'm aware of it... :joy:

**Comment by stonerl** [comment]
OK good to know :smile: . Just another thing I realized. You have this new nice bar for Issues/Pull Requests/Commits/Releases. This new shiny bar is only displayed when on is in the code-section or the commits section. Wouldn't it be nice to have this new bar on all pages?

**Comment by Unknwon** [comment]
> This new shiny bar is only displayed when on is in the code-section or the commits section. Wouldn't it be nice to have this new bar on all pages?

Hmm, yes, currently only home, settings, commits

release will be added with new UI.

but issues/pulls are already have a small nav bar, wouldn't it be too verbose?

**Comment by Unknwon** [comment]
New UI: https://try.gogs.io/gogs/gogs/releases
