### ISSUE TITLE
Error UI Style in /user-name?tab=activity

### ISSUE THREAD

**Issue by eryx** [gogits/gogs#1960]
Error UI Style in /user-name?tab=activity

![screenshot-profile - gogs go git service - google chrome](https://cloud.githubusercontent.com/assets/275347/11176517/c6570d20-8c78-11e5-80e8-b31db1bc6ad8.png)

**Comment by Unknwon** [comment]
Please provide needed information.

**Comment by Unknwon** [comment]
Please test out again!

**Comment by eryx** [comment]
Fixed!

**Comment by Unknwon** [comment]
:tada:
