### ISSUE TITLE
New UI for Issue/Pull Request

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#1961]
Hi @Unknwon,

as I asked you yesterday about the new UI for the Issues and Pull Request page I'd like to show you some mockups.

1. Issues:
![issue](https://cloud.githubusercontent.com/assets/2091312/11182044/fc8657e0-8c67-11e5-935c-b5912350d41f.png)

2. Pull Request:
![pr](https://cloud.githubusercontent.com/assets/2091312/11182046/0659ff10-8c68-11e5-922e-f0be5fe5dc8a.png)

What do you think? It would make the overall appearance much more consistent, IMHO.

**Comment by Unknwon** [comment]
Very cool! But what URL should new pull request have?

**Comment by stonerl** [comment]
The URL I think should be related to to the user who creates a new pull request.

e.g. I want to create a pull request to push my code into your repo. When I go to your Repo and click on "New Pullrequest" it should take your Repo as "base" and my Repo that is forked from yours as "base".

Maybe this button should only be active if I have code in my Repo that is actually mergeable.

**Comment by Unknwon** [comment]
The situation is very complicated if you don't have any forked repo for it.

**Comment by stonerl** [comment]
Well in this case the button should be inactive/nonclickable, if this is possible. Much like the current situation. The Pull Request button only appears when i have a forked repo with with code I can merge.

**Comment by stonerl** [comment]
Another solution would be. You click the button and get a message that you don't have any repo/code where you can merge code from.

But this is totally up to you since you are the ingenious Programmer :smiley: , and I don't know the code.

**Comment by Unknwon** [comment]
Sounds good.

But what do you mean "you can merge"? Shouldn't be you have forked the current repo?

**Comment by stonerl** [comment]
3 possible Situations I can Imagine:

1. I forked your repository and did changes to the code and wan't to open a PR. I click on "New Pull Request" and open the new PR.

2. I forked your repo but I did not change any code. Here are two optiones, first; I cannot click the "New Pull Request"-Button. Second; I can click the Button but I get a message that there is no code for a Pull request.

3. I did not fork the repo. Here again two options, first: I cannot click the button. Second; I can click the Button and get a message that I have not forked the repo.

**Comment by Unknwon** [comment]
OK I see.

**Comment by Unknwon** [comment]
OK, please checkout https://try.gogs.io/gogs/gogs/pulls

**Comment by stonerl** [comment]
Great work. :bow:  Tested all 3 cases. :+1:

**Comment by Unknwon** [comment]
:tada:

**Comment by stonerl** [comment]
Just one thing, but I'm sure you are aware of it. When you click on an issue or PR the new top bar is not shown:
https://try.gogs.io/gogs/gogs/issues/25

**Comment by Unknwon** [comment]
OK, fixed that locally.

**Comment by ChangePlaces** [comment]
loving the new ui! Just a thought, maybe the "new xyz" buttons should have little icons in them? Because, when you have many tabs open, the green buttons all look the same! I could go looking for some suitable icons?

**Comment by Unknwon** [comment]
I don't think have icon in `new xyz` buttons is a good idea...

**Comment by stonerl** [comment]
@Unknwon two more things:

When you have a Pull Request open you have the "New Issue" Button instead of the "New Pull Request" Button in the top right corner.

https://try.gogs.io/gogs/gogs/pulls/27

The second thing. When you click on "Pull Request" or "Issues", in the new bar theses entries are highlighted. When you click on "Commits", "Releases" or "Settings" these are not highlighted.

**Comment by stonerl** [comment]
@ChangePlaces I also don't think icons would be a good idea. Since the new topbar highlights the currently active section and the two buttons are also different in size, I think it is quite easy to distinguish.

**Comment by ChangePlaces** [comment]
ok, it was just an idea :)

**Comment by Unknwon** [comment]
> When you have a Pull Request open you have the "New Issue" Button instead of the "New Pull Request" Button in the top right corner.

https://try.gogs.io/gogs/gogs/pulls/27

The second thing. When you click on "Pull Request" or "Issues", in the new bar these entries are highlighted. When you click on "Commits", "Releases" or "Settings" these are not highlighted.

Fixed.

**Comment by Unknwon** [comment]
Brand new profile page :D https://try.gogs.io/unknwon

**Comment by stonerl** [comment]
Great. And the new profile page looks terrific. :+1: 

Just another question (you are going to kill me :smile: ) You said that you fixed the missing topbar locally. Did you also remove the "Issues/Pull Request" Buttons that are currently shown when you have an issue/pr open? I mean the one next to "Labels/Milestones".

**Comment by Unknwon** [comment]
I think I didn't: https://try.gogs.io/gogs/gogs/pulls/28

**Comment by Unknwon** [comment]
all my changes have been pushed to https://try.gogs.io , just test there and leave feedback :D

**Comment by stonerl** [comment]
:smile: 
OK here is an issue:
![screenshot-try gogs io 2015-11-16 17-32-07](https://cloud.githubusercontent.com/assets/2091312/11187800/23c5d4f0-8c88-11e5-9019-64187d345e84.png)
The new Topbar is missing and the buttons I circled red need to be removed.

Here is an PR:
![screenshot-try gogs io 2015-11-16 17-31-09](https://cloud.githubusercontent.com/assets/2091312/11187822/40b73e5a-8c88-11e5-90f1-b50a90b70131.png)
The new Topbar is missing and the buttons I circled red need to be removed.

**Comment by Unknwon** [comment]
I put that in purpose...

**Comment by stonerl** [comment]
Ah OK... why, if I may ask? :fearful:

**Comment by ChangePlaces** [comment]
why does " stonerl created pull request gogs/gogs#28 " appear in your public activity unknwon? is that supposed to be there?

**Comment by Unknwon** [comment]
> why does " stonerl created pull request gogs/gogs#28 " appear in your public activity unknwon? is that supposed to be there?

This is indeed a bug...

**Comment by Unknwon** [comment]
> Ah OK... why, if I may ask? :fearful:

Make it feels same with create new milestone/label...

**Comment by Unknwon** [comment]
@ChangePlaces fixed.

**Comment by stonerl** [comment]
Aah, I see. OK I would change that too, to have an consistent UI all over the place, BUT you are the one who is writing the code so I have to leave this up to you. :smile: :bow: And you're doing a great job.

**Comment by Unknwon** [comment]
> Aah, I see. OK I would change that too, to have an consistent UI all over the place, BUT you are the one who is writing the code so I have to leave this up to you. :smile: :bow: And you're doing a great job.

I'm not quite sure, because it may feel too verbose to have this top navbar on every single page...

**Comment by stonerl** [comment]
Yeah you may be right. I just did another mockup (just for PR) so that one could see how it would actually look like.

![pr-open](https://cloud.githubusercontent.com/assets/2091312/11188823/20c0046a-8c8d-11e5-9d93-73809cff67e6.png)

I like this look but that is because I want everything to be as consistent as possible. But I am not the center of the world :smile: and there would be many sites to update...

**Comment by Unknwon** [comment]
It pushes down the main content too much... that's why I think it's too verbose.

**Comment by stonerl** [comment]
Yeah, your completely right. 

Once again, I have to thank you for your awesome work.

**Comment by ChangePlaces** [comment]
@Unknwon ahh you fixed it already! I was going to start an issue about it as it was kind of separate to this! Well done!

**Comment by stonerl** [comment]
Btw. I found one more page that is inconsistent: It is the Collaboration-Tab on the Settings-Page that looks different then the other three.
![screenshot-try gogs io 2015-11-16 18-22-34](https://cloud.githubusercontent.com/assets/2091312/11189234/5d5cc672-8c8f-11e5-9bf1-b0c4ff0b0100.png)

**Comment by Unknwon** [comment]
@stonerl the search list is another UI component which takes time, already in my todo list :D

**Comment by stonerl** [comment]
@Unknwon I see. :D I hope I don't annoy with all my comments.

**Comment by Unknwon** [comment]
It's OK :D But I'm gong out now, may not be able to reply as quick as right now
