### ISSUE TITLE
Restrict user sign-up to particular e-mail domains

### ISSUE THREAD

**Issue by nanoant** [gogits/gogs#1963]
I am considering moving to Gogs from GitLab - quite heavy web app with many dependencies. However for my university server I need to ensure that user registration is only available to the students having emails within our domain.

Can you please add such restriction setting, eg. as a simple comma separated list of authorized domains, maybe something like X-509 Name Constraints:

* `example.com` - only users from *example.com* can sign-up
* `.example.com` - only users from subdomains of *example.com*, but not *example.com* domain can sign-up
* `.example.com,example.com` - only users from domain & subdomains of *example.com* can sign-up

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by tboerger** [comment]
Is that domain check already part of the SMTP auth?

**Comment by Unknwon** [comment]
@tboerger indeed, but it's more flexible to be able to use custom username.

How do you think? @nanoant

**Comment by Unknwon** [comment]
Any updates?

**Comment by nanoant** [comment]
I am sorry but I don't follow what SMTP check has to do with my proposition.

Why I want to do is to restrict service only to students of University, assuming they all have e-mail accounts in certain (University) domain, eg. `university.edu` or some subdomains such as `students.university.edu`. I want to allow them to sign-up (register) independently from university LDAP (or any other auth system) as long they provide email that belongs to `university.edu` and they activate their Gogs account using link from activation mail sent to their email address.

So for example when I set restriction in config `restrictEmail = .university.edu,university.edu` then:

1. On the Register page I'd expect the additional note present under E-mail field, eg.: *"This e-mail must belong to university.edu domain or its subdomain and will be used to activate your account."*
2. When someone puts not matching email then an error should be shown: *"Provided email does not belong to university.edu domain or its subdomain."*

This is of course just a proposition, the way the restriction is defined is up to you, it can be also a regex (eg. `(^|\.)university.edu`), wildcard match, or anything feasible.

Of course the restriction is to be enforced upon Registration form validation, not later, and has nothing to do with way Gogs sends out activation emails. It is just an additional restriction on user's email.

**Comment by Unknwon** [comment]
OK.. make sense, thanks for the detail.

**Comment by nanoant** [comment]
@Unknwon FYI I already went different path integrating LDAP authentication that worked even better than proposed solution. Therefore please either close this or make it low priority (not really next release). Anyway someone may still want this feature as for example GitLab has this restriction setting.

**Comment by Unknwon** [comment]
@nanoant OK, let's keep it closed until someone else request.

**Comment by miniluigi008** [comment]
I would also like this feature, I run a small private webserver with gogs and give each of my friends a domain-specific email. In order to keep the gogs usage only to my friends and I, checking the domain of their email would be useful.

**Comment by Unknwon** [comment]
@miniluigi008 you probably just need to add a new SMTP add login source in admin panel.

![image](https://user-images.githubusercontent.com/2946214/28232879-120fdc1c-68c1-11e7-9bae-c0d1d86cb836.png)

![image](https://user-images.githubusercontent.com/2946214/28232887-1a65e71c-68c1-11e7-885e-a5b375693c5e.png)

**Comment by miniluigi008** [comment]
That worked, thanks!
