### ISSUE TITLE
Error 500 when viewing specific repository

### ISSUE THREAD

**Issue by TheHowl** [gogits/gogs#1964]
* Bug Description: When viewing a repository of one of my users, an error 500 appears. The logs suggests it has to deal with submodules, although the repository doesn't contain any submodules.
* Gogs Version: 0.7.13.1116
* Git Version: 1.5.1
* System Type: Arch Linux x64
* Error Log:
```
2015/11/16 22:54:32 [...routers/repo/view.go:148 Home()] [E] GetSubModule: GetTreeEntryByPath: error not exist
```

**Comment by TheHowl** [comment]
(fuck, i accidentally pressed ctrl+enter before i should have had)

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think this is duplicated to https://github.com/gogits/gogs/issues/1647
