### ISSUE TITLE
The hyperlink to the branch is wrong if the branch is in a folder or the branch name has '#'

### ISSUE THREAD

**Issue by arthuroy** [gogits/gogs#1965]
Suppose I have a branch named ```'feature/#1965'```, and the following history will be listed on the page of the dashboard feed after I push something to the repository.

***[john.doe](/john.doe) pushed to [#1965](/x_corp/project_x/src/#1965) at [x_corp/project_x](/x_corp/project_x)***

```html
<p class="text-bold">
    <a href="/john.doe">john.doe</a>
    pushed to <a href="/x_corp/project_x/src/#1965" rel="nofollow">#1965</a> at <a href="/x_corp/project_x" rel="nofollow">x_corp/project_x</a>
</p>
```

When I click the hyperlink, ```/x_corp/project_x/src/#1965```, the page show 'Not Found'.

The hyperlink of the branch, ```'feature/#1965'```, shall be:

 /x_corp/project_x/src/***feature/%231965***

and the branch name to display shall be ```'feature/#1965'```, not ```'#1965'```

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by tboerger** [comment]
You are really including a hash within the branch name? Sounds pretty error proven on the terminal

**Comment by arthuroy** [comment]
@tboerger Well, it's not my decision to define the branch name ;) But I had told the management team about the hash thing.

**Comment by arthuroy** [comment]
@Unknwon 
About the [pull request 1986](https://github.com/gogits/gogs/pull/1986), do I need to provide you the bug example? I thought this issue had provided it. Please enlighten me, thanks.

**Comment by Unknwon** [comment]
> About the pull request 1986, do I need to provide you the bug example? I thought this issue had provided it. Please enlighten me, thanks.

Yes, please.

**Comment by arthuroy** [comment]
@Unknwon 
Ok, I setup a branch like the issue said at https://try.gogs.io/john.doe/project_x
And I had add your account to the collaborator, you can see what listed below on the dashboard afte you logined:

```
john.doe pushed to #1965 at john.doe/project_x

 ceb578ba4e Initial commit
 bfd5a61610 Initial commit
```

**Comment by Unknwon** [comment]
Thanks, I can see it now on https://try.gogs.io/john.doe?tab=activity

**Comment by arthuroy** [comment]
@Unknwon 
Ahhh, I didn't know it can be viewed from personal activity page. Thanks.

**Comment by Unknwon** [comment]
I have updated everything to `master`.

**Comment by arthuroy** [comment]
Test OK on https://try.gogs.io/john.doe?tab=activity
