### ISSUE TITLE
Create team under Repo, not in Organization

### ISSUE THREAD

**Issue by serkon** [gogits/gogs#1967]
When create repos under the organization the teams management is very hard. If you create more than 10 repo under the organization and create 2 diffrent permison team (read team/write team) for  each repo, there are a lot team will be created.

If team management under repo, we just see 2 team for one repo.

**Comment by Unknwon** [comment]
Thanks your feedback!

But no, it's not going to happen.

The thing on the plan is collaborators can have different level of access (read/write/admin).

> If you create more than 10 repo under the organization and create 2 diffrent permison team (read team/write team) for each repo

I'm not sure why you are doing this but I would think you may need to reconsider to not use organization.

**Comment by serkon** [comment]
One day, you ll be understand... ;)

**Comment by Unknwon** [comment]
:trollface:
