### ISSUE TITLE
Run error after git pull

### ISSUE THREAD

**Issue by yrmt** [gogits/gogs#1970]
The error I get is:

template: user/dashboard/feeds:42:47: executing "user/dashboard/feeds" at <$push.AvatarLink>: AvatarLink is not a field of struct type *base.PushCommits

**Comment by yrmt** [comment]
Nevermind, I simply deleted my gopath directory and go get -v again. Not sure how I'm supported to keep dependencies up to date along with git pulling gogs.

**Comment by TheHowl** [comment]
Just do a `go get -u` after updating with git and you're done.

**Comment by Unknwon** [comment]
:trollface:
