### ISSUE TITLE
Wrong migration URL gives 500 error

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#1971]
Here is an example for a repo that does not exists ```https://rokuhara.japanologie.kultur.uni-tuebingen.de/Zenodotos.git/```

When I do a local ```git clone```:
```
$ git clone https://rokuhara.japanologie.kultur.uni-tuebingen.de/Zenodotos.git/
Cloning into 'Zenodotos'...
fatal: repository 'https://rokuhara.japanologie.kultur.uni-tuebingen.de/Zenodotos.git/' not found
```
When I use the above URL to migrate a repository to GOGS, GOGS does not notice that this is an invalid URL. It tries to clone from the URL for about <strike>two</strike> three minutes and eventually gives a 500 errorpage.

Instead it should notify the user that the URL is wrong.

**Comment by Unknwon** [comment]
Thanks. What is your version of Gogs?

**Comment by stonerl** [comment]
@Unknwon I did this on https://try.gogs.io

**Comment by Unknwon** [comment]
That is a wise place :clap:

**Comment by Unknwon** [comment]
Hmm.. Not sure why https://try.gogs.io looks for so long, but for that matter, I consider 500 is correct response because on local machine, I quickly get:

![image](https://cloud.githubusercontent.com/assets/2946214/11253088/82e6e67e-8e07-11e5-9dde-e291a56be32c.png)

**Comment by Unknwon** [comment]
So if the error 500 is the main purpose here, the topic is duplicated to https://github.com/gogits/gogs/issues/1386

**Comment by stonerl** [comment]
Hmm in my local machine cloning this specific address also takes very long and gives me a 500.

But when it fails I don't have an unusable repository as described in #1386.

The repo only exists as long as Gogs is trying to clone from the incorrect URL. As soon as I get the 500 it deletes the repo.

**Comment by Unknwon** [comment]
I see. But the URL you give me is a real URL, that's maybe the reason Git is keep trying, but you give a real fake URL, it fails very quick.

**Comment by stonerl** [comment]
Yes the URL is real. Just the protocol is wrong. If you would clone this address ```git://rokuhara.japanologie.kultur.uni-tuebingen.de/Zenodotos.git/``` everything works fine.

**Comment by Unknwon** [comment]
I have edited my last comment.

**Comment by stonerl** [comment]
On my gogs-server it is v1.9.1. Maybe that is the reason if so just close this issue.

**Comment by Unknwon** [comment]
@stonerl It would be better to test again locally with higher version, just to make sure.

**Comment by stonerl** [comment]
@Unknwon when I try to clone the ```https``` Address on my gogs-server from the commadline with git 1.9.1 I get this error:

```
Cloning into 'Zenodotos'...
fatal: unable to access 'https://rokuhara.japanologie.kultur.uni-tuebingen.de/Zenodotos.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```
This error is different from the one I get on my local machine. Where I have git 2.6.3. Could this be the reason?

**Comment by Unknwon** [comment]
@stonerl so in higher version (2.x), it fails quick?

**Comment by stonerl** [comment]
When I clone from the commandline the time is the same (around one second). But the error-messages are different. So maybe the reason why Gogs takes so long is that the error message is different?

With git 2.6.3 on my Mac it says:
```
fatal: repsitory 'XXX' not found
``` 
But on my server with git 1.9.1 the error is 
```
fatal: unable to access 'XXX' server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

**Comment by Unknwon** [comment]
Maybe it's a 1.8.x issue. I clone on my demo server in command line, it hangs as well.

**Comment by stonerl** [comment]
I upgrade git on my server to 2.6.3 now it does not take 3 Minutes, I get a 500 within 1 second.

I don't know how gogs handles git errors but his one:

```
fatal: unable to access 'XXX' server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```
seems to result in an 500 instead of of:

![error](https://cloud.githubusercontent.com/assets/2946214/11253088/82e6e67e-8e07-11e5-9dde-e291a56be32c.png)

**Comment by Unknwon** [comment]
I've updated `master`.

**Comment by stonerl** [comment]
:+1: great work only one thing: Since this clearly is not an Authentication Error the message is a little misleading:

![screenshot-rokuhara japanologie kultur uni-tuebingen de 2015-11-19 19-34-55](https://cloud.githubusercontent.com/assets/2091312/11280182/f4a16d1e-8ef4-11e5-854e-feb7223d7fa1.png)

 Besides that, thank you for your quick fix.

**Comment by Unknwon** [comment]
Pushed to `master`:

![image](https://cloud.githubusercontent.com/assets/2946214/11280374/c9edc698-8ec3-11e5-8412-6e828fce308f.png)

**Comment by stonerl** [comment]
@Unknwon you are my personal hero :beers: :smile:

**Comment by Unknwon** [comment]
:trollface:
