### ISSUE TITLE
While add local url to webhook getting "Payload URL is invalid" error

### ISSUE THREAD

**Issue by serkon** [gogits/gogs#1972]
I get this error while add local hosted domains. For example;  when I write "http://test/hook.php" to payload field and send, getting "Payload URL is invalid" error.

**Comment by serkon** [comment]
We work on intranet...

**Comment by Unknwon** [comment]
@serkon I know it, you can use hosts file to redirect test.local to any IP.

Because if I remove the validation soon enough someone will ask why Gogs does not check. I can't make everyone happy... so let's follow the simple standard way. :D

**Comment by serkon** [comment]
I have not been managing servers so i can't change host file quickly. You could not remove validation, just change validation pattern ... If not,  I'll find my solution, thanks

**Comment by Unknwon** [comment]
Directly use IP should pass the validation, if you have that...

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by letorbi** [comment]
It took me about 20mins to solve this problem (for some reason this issue report didn't show up on Google).

It think there should be at least a hint in the error message how a correct URL should look like.
Perhaps an even better approach would be to allow a hostname-only urls, but warn the user that a fully qualified domain name would be a better choice. This would give users the freedom to use hostname-only urls (which are quire common in small intranets) while still warning them about possible problems.
