### ISSUE TITLE
UI inconsistencies

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1973]
I noticed inconsistencies between page UI.

### Pages that don't have the new "white dominant" (Semantic-based?) UI

- Organization: Home, Invite, Create new Team.
- Admin: Dashboard, Configuration.

This is very confusing, especially because the top menus are different, so the popups are not the same and the placement is different also.

### Header Action-Bar Issue (Solved in `0.7.16.1117 Beta #develop`)

- ~~When on a repository main page, there is a neat header on top saying `Issues`, `Pull Requests`, `Commits`, `Releases` and `Settings`. This header is very good looking, it has icons and it is very clear (Full width).~~
- ~~But when you click any of those links, the header is different... IMO it should stay the same, and the section should load below it. Having no more icons, and having the `New Issue / Label / PR...` on the right replacing the `Settings` button is very confusing... IMO, the `New Issue / Label / PR...` button should be placed at the same vertical level as the filters, not in this header, and this header should stay the same across all pages.~~

### No Direct Organization Links

Let's say that I’m navigating to a page like my settings, something is bothering me: there is no way for me to see a link or an area that would list Organisations. Maybe a small adition in the popup menu "Organizations" after the "Signed-In as xxx" entry would come in handy?

Gogs version `0.7.12.1116 Beta` from docker image.
**Partially** still problematic in `0.7.16.1117 Beta #develop`.

**Comment by stonerl** [comment]
@hickscorp try the latest version ``` 0.7.16.1117``` some of this ui inconsistency should be resolved. @Unknwon is currently changing the design but he has to do this page by page.

**Comment by stonerl** [comment]
Also take a look at https://try.gogs.io there he has always running the latest development version.

**Comment by hickscorp** [comment]
@stonerl Thanks. Just updated the initial post with my feedback from the latest #develop version.
@Unknwon I see that you're still working on Gogs... I really like where the project is going. Congratulations.

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/650 :trollface:
