### ISSUE TITLE
Import / Export feature

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1977]
Hello,

I have been working on using the docker version of Gogs, and here is a very neat feature that would make migrations a lot easier:

- From an existing Gogs, allow administrators to export data to a standardized format (YML with relationship nesting rather than SQL).
- Then, putting the YML or alike file inside the data folder under a specific name would tell Gogs to automatically import and restore the settings upon fresh deployment. The security behind this would be to only import the data file if locked = false in the configuration, bypassing the install step.

I'm aware that this is a feature that might be used not very often, but it would appear to be super-handy when needed!

What do you guys think?

Gogs version `0.7.12.1116 Beta` from docker image.

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is pretty much duplicated to https://github.com/gogits/gogs/issues/1388 , please follow on that one.
