### ISSUE TITLE
"Watch" count is incorrect for organizations.

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1978]
Hello,

If you have an organization set-up, and create a repository, the default "Watched" count becomes 2. If you unwatch it with your user, the watch count becomes 1, and there is no way to put it down to 0.

Gogs version `0.7.12.1116 Beta` from docker image.
Still problematic in `0.7.16.1117 Beta #develop`.

**Comment by Unknwon** [comment]
Organization watches itself in order to get news feeds, so code logic is much simpler.

**Comment by hickscorp** [comment]
Understood, now that i know that it makes perfect sense. Will close the issue.

**Comment by Unknwon** [comment]
:trollface:
