### ISSUE TITLE
No links in email for admin created account

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1979]
Hello,

Yesterday, I did something on our Gogs instance on behalf of a friend:

- Created his account,
- Added him to an organization,
- Added him to a team.

My friend received various emails confirmations, and the links were pointing to the Gogs website rather than to our instance.

Gogs version `0.7.12.1116 Beta` from docker image.
Not tested with `0.7.16.1117 Beta #develop`.

**Comment by stonerl** [comment]
I can confirm this with version ```0.7.16.1117``` the E-Mail does not contain any link to the instance where the account has been created.

**Comment by Unknwon** [comment]
If it was admin created the account, yes I can confirm there is no link to the instance. Is this the case?

**Comment by stonerl** [comment]
@Unknwon yes that's the case.

**Comment by hickscorp** [comment]
@Unknwon Yes, you nailed it. As i said, I basically went through the whole user creation on behalf of my friend using my administrative account.

**Comment by Unknwon** [comment]
It looks like as follows right now:

![image](https://cloud.githubusercontent.com/assets/2946214/11252436/331b4732-8e04-11e5-8e4c-c95a4354312e.png)
