### ISSUE TITLE
Explaination for public / private members in organizations

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1980]
Hello,

If you go to an organization members page like so `http://gogs.instance.int/org/organization_name/members`, there is a link next to the currently logged-in user: "make public". What is that exactly? I think a small pop-up might come in handy for people trying to understand the feature.

Gogs version `0.7.12.1116 Beta` from docker image.
Still problematic in `0.7.16.1117 Beta #develop`.

**Comment by stonerl** [comment]
@hickscorp 
it means that everyone can see this user as a member of the organization.

**Comment by hickscorp** [comment]
All right, thanks for the explanation. Should there be a small tooltip explaining that (Implications of a user taking the action without being aware of them)?

**Comment by Unknwon** [comment]
This page pretty much explains the way it works: https://help.github.com/articles/publicizing-or-hiding-organization-membership/
