### ISSUE TITLE
Project description is not copied when forking

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1981]
When creating a fork of a project, the description field is initially set with the same content as the original repository being forked.

However, after doing the fork, the description is blank.

Edit: Might be related to #1987.

Gogs version `0.7.12.1116 Beta` from docker image.
Still problematic in `0.7.16.1117 Beta #develop`.

**Comment by hickscorp** [comment]
Mighe be related to #1987

**Comment by hickscorp** [comment]
@Unknwon Do you need me to edit my initial post so this remains undercover until fixed?

**Comment by Unknwon** [comment]
> @Unknwon Do you need me to edit my initial post so this remains undercover until fixed?

Hmm, I'm not sure what do you mean.. current one LGTM..

**Comment by stonerl** [comment]
@Unknwon it hink he meant this bug report #1987

**Comment by Unknwon** [comment]
@stonerl OK... thanks.

**Comment by Unknwon** [comment]
You can now test it on https://try.gogs.io
