### ISSUE TITLE
Pull requests: clarification

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1982]
Hello,

I have forked a test project from an organization to my individual account. I have then committed to the individual repository, and from the Gogs UI i have pushed the small green button (Pull request).

The page that I’m seeing is pretty neat, but I thought of two improvements:

- On the top section, the branch comparison makes close to no sense, because there is no way to tell from which repositories they belong (Comparing master with master, but what repo is on the left, what repo is on the right?).
- ~~In the middle section, the tabs allowing to write a summary for the PR are not translated (I see `release.write` and `release.preview` instead of the titles)~~ (Solved in  `0.7.12.1116 Beta`).
- On the bottom section (Files diffs), I previously experienced major issues with this kind of view: when the PR has lots of changes (Say 20k lines), it is most likely to fail to display the page. There should be a test on the server-side, if there is more than X lines, don't display the diff.
- Then, once validating the PR, the next screen shows the sentence `username wants to merge username/master with organization/master`, but the two last indicators are in blue (Links) without a link.
- Edit: Also, when merging a pull request, it appears that the originator user is "Gogs" when navigating to the main repository page (See screenshot), while when inspecting the PR page the correct user is shown.

I would like to finish this issue by congratulating all Gogs foundators and contributors. When I tried the PR feature, I was truly amazed by the "click-click-go" feeling, and I have to say that the pages overall offer an awesome UX. Keep up the good work, the result is just **amazing**.

Gogs version `0.7.12.1116 Beta` from docker image.
Partially persists in  `0.7.12.1116 Beta`.

![screenshot_2015-11-18_14-15-18](https://cloud.githubusercontent.com/assets/822933/11243242/d3511f8e-8dfe-11e5-8854-759156dccd51.png)

**Comment by stonerl** [comment]
@hickscorp 

Regarding your first question. Since Gogs does not support pullrequest in the same repo, The Branch on the left is always the the one from the repo you forked and the left is your repo.

btw. Which version of Gogs are you using?

**Comment by hickscorp** [comment]
@stonerl Yes, i'm used to this behavior, but what i'm saying is that a small indication of the repository name might really clarify what the user is actually doing. Thanks for your explaination!

**Comment by linphy** [comment]
@stonerl  Hi, Why Gogs does not support pullrequest in the same repo? this is my expect function.

**Comment by stonerl** [comment]
Not implemented yet. But there is annopen issue: #1597

**Comment by hickscorp** [comment]
@linphy I'm not sure I understand what would be the benefit of such feature, unless Gogs also implements per-branch authorizations. Anyone with push access on a full repo can directly merge branches. Gitlab solves this by introducing per-branch per user rights. So far, having each of our team member fork the project and issue PRs on the original repo solves all the problems.

**Comment by hickscorp** [comment]
@stonerl Please see my updated original post, with one new issue and screen-shot.

**Comment by Unknwon** [comment]
> On the top section, the branch comparison makes close to no sense, because there is no way to tell from which repositories they belong (Comparing master with master, but what repo is on the left, what repo is on the right?).

This will be fixed along with #1597 so you should follow on that one.

> On the bottom section (Files diffs), I previously experienced major issues with this kind of view: when the PR has lots of changes (Say 20k lines), it is most likely to fail to display the page. There should be a test on the server-side, if there is more than X lines, don't display the diff.

Maxline of git diff default is 10k lines, you can change it in settings.

> Then, once validating the PR, the next screen shows the sentence username wants to merge username/master with organization/master, but the two last indicators are in blue (Links) without a link.

Indeed an enhancement. 

> Also, when merging a pull request, it appears that the originator user is "Gogs" when navigating to the main repository page (See screenshot), while when inspecting the PR page the correct user is shown.

This is an old issue, you had wrong setting in your server I think. "Gogs" is a fake one, but is never used.

**Comment by hickscorp** [comment]
@Unknwon Regarding your answer to the last point, I don't see any particular settings in the configuration file. Here is why (Along with a suggestion):

The default gogs docker image has a single config file: `app.ini`. Therefore, when new to Gogs, the immediate reflex is to use `app.ini` and customize it, therefore overwriting any new `app.ini` when future Gogs docker image releases will come up.

May I suggest that you adopt the same strategy as you did for the old "regular release" before docker, using `conf/app.ini` and `custom/conf/app.ini`? This way, it would always be possible to see differences between custom and vanilla config.

**Comment by Unknwon** [comment]
> Regarding your answer to the last point, I don't see any particular settings in the configuration file. What is this setting you're telling me about? Here is why (Along with a suggestion):

I mean it needs to go another issue because it's irrelevant to this one (title).

Also, the one you're talking is already the custom `app.ini`: https://github.com/gogits/gogs/blob/master/Dockerfile#L12

**Comment by Unknwon** [comment]
> Then, once validating the PR, the next screen shows the sentence username wants to merge username/master with organization/master, but the two last indicators are in blue (Links) without a link.

In the case when forked repo/branch is deleted, the translation string will break, and it adds unnecessary complicity to the I18N (two exactly same strings but with link) and a database query.

Since all point are invalid to this thread, I'm closing it. But thanks your feedback!
