### ISSUE TITLE
Better mirror repo management

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1984]
When forking a project, the original repository is mentioned on the fork page. However, when mirroring a repository (Migration feature), the fork only says "Mirror" but doesn't show any link. It would be nice and more consistent to add a link to the forked repository.

Gogs version `0.7.12.1116 Beta` from docker image.
Still problematic in `0.7.16.1117 Beta #develop`.

**Comment by Unknwon** [comment]
Make sense.

**Comment by hickscorp** [comment]
@Unknwon I think it does yes.

I really think the best layout regarding the header is the "fork" layout. The title is nice and big, and the small subtitle is visible but yet doesn't takes too much attention, which is good. Maybe using the exact same template for the mirror would be nice?

**Comment by Unknwon** [comment]
@hickscorp Good point.

**Comment by Unknwon** [comment]
Just some additions:

- Able to change mirror source
- Able to convert to/from a mirror repository

**Comment by Unknwon** [comment]
It is now possible to show and edit mirror address in `develop` branch and https://try.gogs.io

**Comment by Unknwon** [comment]
Close as implemented.
