### ISSUE TITLE
Feature Suggestion: Virtual Groups

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1985]
Hello,

I used to be a fervent user of Gitolite, and one of the best feature we used was the virtual group system.

Basically, the ability to put slashes in the repository name would make repositories belonging to the same "virtual group" displayed inside of a tree on the various Gogs UI pages, while keeping full Git standard compatibility. Let's say we have those repos:

- pqr-backend
- pqr-client-ios
- pqr-client-macos
- pqr-client-android

They all appear on Gogs user profile with their full name, and it ends-up showing a quite long list (On my Gogs repo, i have close to 45 private repos shown this way).

Instead, allowing users to create the repositories with slashes would transform to:

- pqr/backend
- pqr/client/ios
- pqr/client/macos
- pqr/client/android

So on the dashboard page, a nice fold-able tree could be displayed, automatically grouping by project (pqr), then by scope (backend / client). Again, i'm speaking purely aesthetics.

Then, if this sounds like a good idea, something could be done automatically by Gogs. Let's say a user tries to clone the `pqr` virtual folder, then Gogs could automatically generate a virtual repository (Read-only) that would only contain submodules, so the user could later init recursive and have everything neatly cloned automatically.

What do you guys think?

Gogs version `0.7.12.1116 Beta` from docker image.

**Comment by Unknwon** [comment]
It sounds good but violates the current design of Gogs, so I think it's possible until 1.x.

**Comment by hickscorp** [comment]
@Unknwon I'm glad that you're around, it's very nice to see you again. Ok, understood.

**Comment by Unknwon** [comment]
:trollface:
