### ISSUE TITLE
SECURITY: Forked project becomes public without user being aware of it

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1987]
Hello,

To reproduce the problem:

- Create a **private** project in an organization, and **put a description**.
- Fork the project using an individual account.
- The project **description is empty** (See #1981), and the project is **private** (Good).
- Go to the fork's settings, and copy paste the same description, validate.
- The **forked project somehow becomes public**, and there is no way to put it back private (No `private` checkbox in forked project settings)!
- At this point, removing the description doesn't put the project back to private... So there is no other option than deleting the fork.

**Comment by Unknwon** [comment]
To fix forked visibility, change base repo to public and back to private. Then you can test again.
