### ISSUE TITLE
Translation: Missing ugly entry when creating new repository.

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1988]
When creating a new repository, a nice page shows commands that can be issued to add it as a remote.

The title of the page shows `Clone this repository`, but then the description shows `clone_helper%!(EXTRA string=http://git-scm.com/book/en/Git-Basics-Getting-a-Git-Repository)`

**Comment by Unknwon** [comment]
Do you have screenshot?

**Comment by stonerl** [comment]
@Unknwon
Have a look here: https://try.gogs.io/stonerl/NewOne

**Comment by stonerl** [comment]
@Unknwon here is the screenshot
![tmp_6559-screenshot_2015-11-18-16-22-36-252114451](https://cloud.githubusercontent.com/assets/2091312/11246050/4d6157aa-8e16-11e5-948a-801aa5aa7d4f.png)

**Comment by Unknwon** [comment]
@stonerl thanks! Fixed.
