### ISSUE TITLE
git patch apply no such file or directory when creating a PR

### ISSUE THREAD

**Issue by ryanb-hc** [gogits/gogs#1989]
I'm running Gogs  0.7.6.1112 Beta and have an organizational repo with a forked repo of that  under my own account in Gogs.

When trying to submit a PR from my forked branch to the same branch in the organization repo, I am met with a 500 page.  The gogs.log shows the following:

2015/11/18 10:40:02 [...routers/repo/pull.go:642 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: git apply --check: exit status 1 - error: path/to/valid/file.txt: No such file or directory

However, on the PR creation page, the diff shows up correctly, and I can see that the file exists in the matching branch of both repos.

Setting the run mode to test and dev did not produce any other helpful information.

**Comment by stonerl** [comment]
@ryanb-hc 
Can you try to reproduce this on https://try.gogs.io

maybe your bug is related to this one: #1931

**Comment by ryanb-hc** [comment]
I've tried it out on https://try.gogs.io and was unable to reproduce the problem.  Reading through that issue it looks like it could be similar.  

It appears that your issue has been fixed on gogs/master as of 3 days ago, I'll update my server and test it out there again.

**Comment by Unknwon** [comment]
@ryanb-hc you need to update your Gogs.

**Comment by ryanb-hc** [comment]
Upgraded our local gogs server from source just now.  PRs worked exactly as expected.

@stonerl Thanks for the quick response and direction

@Unknwon Thank you for all your time and dedication to making such a wonderful piece of software!

**Comment by Unknwon** [comment]
:tada:
