### ISSUE TITLE
Gopm not getting any packages

### ISSUE THREAD

**Issue by techzilla** [gogits/gogs#1991]
[GOPM] 15-11-18 15:20:29 [ERROR] github.com/Unknwon/cae: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/Unknwon/com: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/Unknwon/i18n: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/Unknwon/paginater: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/codegangsta/cli: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/go-macaron/binding: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/go-macaron/cache: fail to extract archive: zip: not a valid zip file
    [GOPM] 15-11-18 15:20:29 [ERROR] github.com/go-macaron/captcha: fail to extract archive: zip: not a valid zip file

.... and so on

**Comment by Unknwon** [comment]
Please report to gopm...
