### ISSUE TITLE
template view_list - Id is not a field of struct type interface

### ISSUE THREAD

**Issue by otih** [gogits/gogs#1993]
Have some issue when accessing the following repo:
https://git.okoyono.de/mezzomix/buch_des_monats

template: repo/view_list:15:81: executing "repo/view_list" at <.LastCommit.Id>: Id is not a field of struct type interface {}

gogs:   0.6.15.0926 Beta
go:  go1.5 linux/amd64

**Comment by Unknwon** [comment]
Hi, you Gogs version is too low, please upgrade to 0.7.6 :D

**Comment by otih** [comment]
thx, update script was not pulling correctly. Thanks!

**Comment by Unknwon** [comment]
:trollface:
