### ISSUE TITLE
Email Confirmation Issues

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#1996]
Hello,

I sometimes received emails from Gogs to verify additional email addresses. Two things:

- First of all, if i add 2 email addresses to my account, all the confirmation emails were sent to my primary email, which doesn't make much sense.
- When clicking the confirmation link in the email, the Gogs page that is supposed to give a confirmation message is missing a translation (See screenshot) for `add_email_success`.

![screenshot_2015-11-19_09-40-39](https://cloud.githubusercontent.com/assets/822933/11267233/0a772032-8ea2-11e5-9409-d2d1c8754a4e.png)

Best,
Doodloo.

**Comment by Unknwon** [comment]
What is your version of Gogs?

**Comment by Unknwon** [comment]
> First of all, if i add 2 email addresses to my account, all the confirmation emails were sent to my primary email, which doesn't make much sense.

I can't reproduce this on https://try.gogs.io ...

**Comment by stonerl** [comment]
@Unknwon 0.7.18.1118

**Comment by Unknwon** [comment]
I have fixed the translation problem, but the other I can't reproduce.

**Comment by stonerl** [comment]
@Unknwon I also only had the translation problem. When I add new email addresses they get send to the correct address.

**Comment by Unknwon** [comment]
Close as fixed?
