### ISSUE TITLE
Handling of non existing issues

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#1999]
Currently gogs converts all ```#<number>``` to links. The problem though, if such an issue does not exist clicking such a link would result in a 404.

<strike>There are two ways to handle this.</strike>
1. Gogs should check such ```#<number>``` and not link them if they do not exist.
<strike>2. Gogs should open a "New Issue" Page to create this issue.</strike>

**Comment by Unknwon** [comment]
@stonerl It is a problem, however, if check if issue exists every time, performance is so damn bad....

Also, there is another issue asks for external issue tracker, which make sense that this # of issue does not exist inside Gogs.

**Comment by stonerl** [comment]
So the links get created dynamically? GitHub e.g. only creates links when they exist #3333 does not exist so it is not saved as link #1999 exists so it safes this as a link.

When #3333 gets created later on it still does not link this because issue must exist during creation of th issue

**Comment by Unknwon** [comment]
I'm not sure how GitHub exactly did it, but I guess tons of cache is in the play.

**Comment by Unknwon** [comment]
So for external issue tracker, you can define URL format like `https://github.com/gogits/gogs/issues/{index}`, so I can host Gogs on Gogs and still able to use GitHub's issue tracker.

**Comment by stonerl** [comment]
OK, makes sense. Closing this one. And Thank you for your patience. :bow:

**Comment by Unknwon** [comment]
:trollface: No, I'm not a patient person, I just want to respect your time for opening this issue.
