### ISSUE TITLE
Assign more than one user to an issue

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2000]
Would it be possible to assign more than one user to an issue? Might be related to #1729

**Comment by Unknwon** [comment]
From my understanding, if a issue needs two people work on it, that should really be two issues.

**Comment by stonerl** [comment]
Hmm, maybe you are right, or those two are in a team and on would assign this team. Closing this one and waiting for #1729

**Comment by Unknwon** [comment]
Congrats, #2000 !
