### ISSUE TITLE
Always conflicts in pr

### ISSUE THREAD

**Issue by googolmo** [gogits/gogs#2001]
I use version 0.7.6
Every Pull Request show me "You can't perform auto-merge operation because there are conflicts between commits."
I have rebase from up/master but always show it to me.
And i can merge it use command line tool

**Comment by Unknwon** [comment]
Hi, in the matter of PR, you need to update to `master` branch, test again and give feedback! :smile:

**Comment by googolmo** [comment]
± % git rebase up/master                                                                                                                            Current branch xxxx is up to date.

**Comment by Unknwon** [comment]
Source code up to date does not mean your Gogs is up to date.

You need to recompile and tell me the version at the bottom of every page.

**Comment by googolmo** [comment]
0.7.18.1119 Beta is ok!!!

**Comment by googolmo** [comment]
But in my repo, I need push a new commit to make the status to " You can perform auto-merge operation on this pull request."

**Comment by Unknwon** [comment]
Close and reopen the PR will preform retest .

**Comment by Unknwon** [comment]
Close as fixed?

**Comment by googolmo** [comment]
Ja. Danke
