### ISSUE TITLE
All merge pr commiter is Gogs

### ISSUE THREAD

**Issue by googolmo** [gogits/gogs#2002]
After i merge a pr, this action's author is Gogs not me.
I think i should become the author of the merge action.

**Comment by Unknwon** [comment]
Work on it now.

cc @hickscorp I now understand what you were trying to report.

**Comment by Unknwon** [comment]
Pushed fix to `master`!

**Comment by googolmo** [comment]
I click the button which displayed "Merge Pull Request", Then display error page "500". I think you can find the log in the server of try.gogs.io

**Comment by Unknwon** [comment]
Which PR you were trying to merge?

**Comment by googolmo** [comment]
@Unknwon https://try.gogs.io/Meister/Test_Project/pulls/1

**Comment by Unknwon** [comment]
Fixed :wink:

**Comment by googolmo** [comment]
@Unknwon Thank u!
