### ISSUE TITLE
WebHook Sample

### ISSUE THREAD

**Issue by serkon** [gogits/gogs#2003]
Hi, i have created a githook. Maybe someone want to use this Bash Script. 

When a commit pushed or created new repository using gogs interface, this bash script will be run and makes these changes:

1- For web server, create new a new folder with  owner/repositoryname at defined www folder.
2- When commit pushed, it will make "git checkout" to above www folder 
3- Create for download directory that has latest.zip file all www folder.
4- It will create virtual host config file with reponame at defined Nginx vhost folder (you must include *.conf at nginx.conf file within http property)
5- It will add reponame to windows host file if you want to see at browser latest version of file.

I hope, it will help someone

http://serkankonakci.com/webhook/ it could be download from here

**Comment by Unknwon** [comment]
Hmm... thanks your script. But I don't think it's a good place to put it...

Maybe I should really setup a discourse...
