### ISSUE TITLE
List of pages that needs to be converted to new UI

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2004]
@Unknwon since there have been some Issues regarding pages that have not been converted to the new UI, I thought I'd make a list of sites that still need work. So people can see that you are still working on it. I hope you're OK with this.

- [ ] Admin-Panel -> Configuration
- [ ] Organization -> Main Page
- [ ] Organization -> Member Page
- [ ] Organization -> Member Page -> Invitations
- [ ] Organization -> Teams Page
- [ ] Organization -> Teams Page -> Create Team
- [ ] Organization -> Teams Page -> Team Overview
- [ ] Organization -> Teams Page -> Teams Settings

**Comment by Unknwon** [comment]
Thanks your list.

But please report this to https://github.com/gogits/gogs/issues/650

**Comment by stonerl** [comment]
Man I mus be blind.... :sob:

**Comment by Unknwon** [comment]
:trollface: https://trello.com/c/aDv3sA7D/567-all-pages-use-semantic-ui
