### ISSUE TITLE
Config Panel in Administrators is still as per old theme

### ISSUE THREAD

**Issue by micaelsutherland** [gogits/gogs#2005]
Config Panel in Administrators is still as per old theme

**Comment by stonerl** [comment]
@micaelsutherland look here for a list of pages that still need to be converted https://github.com/gogits/gogs/issues/650#issuecomment-158352057
@Unknwon :smile:

**Comment by micaelsutherland** [comment]
Ahhh. many thanks and apologies for raising an issue when it appears it is already being dealt with

**Comment by Unknwon** [comment]
:trollface:
