### ISSUE TITLE
German needs two locals

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2006]
In German there are two ways of addressing people. One formal (Sie) and the other is informal (Du). 

http://www.dw.com/en/the-du-sie-dilemma-in-german/a-16494631

Currently Gogs has only one translation for German and these two forms get mixed up. So a second translation for German (formal) would be necessary.

**Comment by tboerger** [comment]
I think it's much better to just take one and use that one entirely.

**Comment by stonerl** [comment]
Well I have to object here. Informal and formal speech are 2 distinct forms. Much like Portuguese and Brazilian Portuguese. Or Traditional Chinese and Simplified Chinese.

**Comment by Unknwon** [comment]
Any help in screenshot?

![image](https://cloud.githubusercontent.com/assets/2946214/11301393/c6c05200-8f64-11e5-8824-deb0dabf6f95.png)

**Comment by stonerl** [comment]
I see... Crowdin does not Support German formal. Pity! :disappointed: 

So back to @tboerger 's proposal I guess. The question is how do other translation handles this? German is not the only language that has formal and informal speech.

**Comment by Unknwon** [comment]
@stonerl it can create custom one, how should i call it ? `de-xx`?

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/11301615/83823ac4-8f66-11e5-990a-fd9bc1a26d9e.png)

**Comment by stonerl** [comment]
i would use ```de``` for informal and ```de-DE``` for informal. That is what e.g. owncloud does.

**Comment by stonerl** [comment]
updated my comment.

**Comment by Unknwon** [comment]
Hmm, somewhat Crowdin has problem with `de`... 

![image](https://cloud.githubusercontent.com/assets/2946214/11301884/0a702c8e-8f68-11e5-9c7c-1bed48a53b03.png)

**Comment by tboerger** [comment]
I am german, and IMHO it's bullshit to differ between formal and informal. To compare pt-br with pt-pt is like comparing apples with pears....

**Comment by tboerger** [comment]
Wrong wording... comparing this topic with pt-br/pt-pt.

**Comment by tboerger** [comment]
Beside that there are not many serious OSS projects that differ between that which makes imho anyway no sense as long as it's written properly.

**Comment by stonerl** [comment]
@tboerger That is your opinion but there are plenty of people who dislike the fact that some Websites don't differentiate between formal and informal speech. If it would be possible to have both, users would have the freedom to choose.

If it would be a problem due to technical limitations I would second your first comment on deciding on one and go with that choice.

By the way, I consider owncloud as a serious OSS project...

**Comment by tboerger** [comment]
It depends on the target audience. Owncloud got a target on personal and enterprise usage. So maybe it makes sense there. Ogs is pretty useless for personal usage, so it should simply use the formal translation.

**Comment by stonerl** [comment]
@tboerger I second your opinion. Formal speech would be appropriate.

**Comment by Unknwon** [comment]
Hmm... are we having a conclusion here?

**Comment by stonerl** [comment]
The conclusion would be: We only have one German translation. All strings need to be converted to formal speech. I would go through the translations on crowdin...

**Comment by Unknwon** [comment]
:trollface: don't be sad, but I'm going to close this thread, you can continue discussion on http://forum.gogs.io/category/2/general-discussion :sweat_smile:

**Comment by stonerl** [comment]
@Unknwon no problem at all.
