### ISSUE TITLE
CSRF token verification ramdonly fails

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#2007]
I am using the latest version, but this actually have been happened since I installed it by the very first time.

On submitting forms (can be anyone: like creating a repository, a issue, etc.), it ramdomly (maybe 1 time each 10?) fails, with error 500 and the message: "Cannot verify CSRF token".

Windows Server 2012 x64
Gogs version: 0.7.6.1112
Database: PostgreSQL

**Comment by Unknwon** [comment]
This should have been fixed in master.

**Comment by Unknwon** [comment]
Maybe it's not exactly the same, but the expected error should be `invalid csrd token` when a blank page.

**Comment by andreynering** [comment]
Yes, the exact message is "invalid csrd token" in a blank page.

I didn't notice before that it was already reported before (https://github.com/gogits/gogs/issues/1891). I think it is the exact the same.

**Comment by Unknwon** [comment]
:trollface: Cool, so please follow on that.

**Comment by Unknwon** [comment]
@andreynering forum app has a stupid bug, I reinstalled, sorry I see you registered account.

**Comment by andreynering** [comment]
No problem, I was just taking a look. :shipit: 

Wouldn't be simpler to just create a mailing list on Google Groups?

**Comment by Unknwon** [comment]
That is so hard for me....
