### ISSUE TITLE
Native support for pre-receive hooks

### ISSUE THREAD

**Issue by iamgroot42** [gogits/gogs#2008]
How do I use pre-receive git hooks on Gogs ? (If they exist in the first place. If they don't,it would be awesome to have them).

**Comment by Unknwon** [comment]
User has to be given permission in order to use git hooks.

**Comment by Unknwon** [comment]
Admin can give permission in users dashboard

**Comment by iamgroot42** [comment]
I'm talking about 'pre-receive' hook.
The current user has permission to use git hooks (I've tried it with a post-receive hook).

**Comment by Unknwon** [comment]
I see, my bad. No, not yet, but can be added I think.

**Comment by Unknwon** [comment]
:trollface:

**Comment by Unknwon** [comment]
Please test out `develop` branch, I've added more Git hooks in the list.

**Comment by Unknwon** [comment]
Close as implemented.
