### ISSUE TITLE
Pull request error

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#2011]
Application Version: 0.7.6.1112 Beta

I have experienced a few issues with PR. 
The first thing i see, is when i select develop branch on my forked repository, and press the PR button, it automatically selects base:master, which in my case is a branch that is 6 month behind the develop, so that takes a very long time to compare.

Next thing is if i want to change that, i change the base:master to base:develop

![gogs_problem1](https://cloud.githubusercontent.com/assets/10239939/11318281/567cea5c-904b-11e5-91f0-5aa9283dc27a.PNG)

The url is weird
![gogs_problem2](https://cloud.githubusercontent.com/assets/10239939/11318287/aa8a86fe-904b-11e5-86fd-1ecb70e09d43.PNG)

If i change the url manually it seems to do the right thing.
![gogs_problem3](https://cloud.githubusercontent.com/assets/10239939/11318295/f0750428-904b-11e5-9742-15f7131b4459.PNG)

If i now do the pull request i just get the 500 error.
![gogs_problem4](https://cloud.githubusercontent.com/assets/10239939/11318297/1425dd3e-904c-11e5-99e0-7970e512368c.PNG)

from the logs
2015/11/21 12:12:24 [...routers/repo/pull.go:642 CompareAndPullRequestPost()] [E] NewPullRequest: SavePatch: WriteFile: open g:\Git\scada\vob.server.git\pulls\1.patch: The system cannot find the path specified.
2015/11/21 12:12:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:12:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:12:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token

The last thing i see is that my log is filled with thees lines
2015/11/21 12:15:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:15:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:15:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:16:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:16:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:16:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:16:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:16:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:17:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:17:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:17:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:18:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:18:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:18:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:18:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:18:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:19:29 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:19:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token
2015/11/21 12:19:41 [...routers/repo/http.go:119 HTTP()] [E] invalid token

**Comment by stonerl** [comment]
Try to upgrade to the latest master there have been some PR related fixes.

**Comment by Unknwon** [comment]
Thanks your feedback!

1. The error produced by manually change URL is not quite valid since many background work can not apply.
2. As @stonerl mentioned, there are a lot changes about PR after 0.7.6. please first test on https://try.gogs.io and then upgrade.

**Comment by renewsorensen** [comment]
Ok fair enough, i just tried different approaches to see if i could somehow get around that error. 

i can confirm that i am not able to reproduce that particular error on https:/try.gogs.io.

I am not able to build (don't know how) go apps, so i wait for your next release.

**Comment by Unknwon** [comment]
0.7.19 is already released.

**Comment by renewsorensen** [comment]
nice :+1:  thanks!!

**Comment by Unknwon** [comment]
I'm going to close this now, please reopen if problem still exits. :mask:

**Comment by renewsorensen** [comment]
It was maybe unclear to me what was fixed in the current release, but after the upgrade to 0.7.19.1121 i still get the 400 if i change repo on one of the sides in PR

![gogs_problem9](https://cloud.githubusercontent.com/assets/10239939/11322869/c795cc54-90ff-11e5-983f-6eaa9a19740c.PNG)
