### ISSUE TITLE
Miss match between url and label

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#2013]
A small thing.
![gogs_problem5](https://cloud.githubusercontent.com/assets/10239939/11322579/45cd18b4-90f3-11e5-8370-602376783c2c.PNG)

**Comment by Unknwon** [comment]
Thanks, but please upgrade to latest version first :)

**Comment by Unknwon** [comment]
Fixed on `master`.

**Comment by Unknwon** [comment]
New UI looks like: 
![image](https://cloud.githubusercontent.com/assets/2946214/11322630/10a82a82-90c3-11e5-98b2-990e4ec47e8f.png)

**Comment by renewsorensen** [comment]
on it :+1:  and no more post before i update :-)

**Comment by renewsorensen** [comment]
After upgrade i am not able to start the service.
![gogs_problem6](https://cloud.githubusercontent.com/assets/10239939/11322707/f32a94aa-90f8-11e5-
8cd0-7c0d713268aa.PNG)

**Comment by renewsorensen** [comment]
I am not able to start service after update

![gogs_problem6](https://cloud.githubusercontent.com/assets/10239939/11322715/324dea7e-90f9-11e5-9888-bd007b5d3f40.PNG)

**Comment by Unknwon** [comment]
Because you did not follow the instructions which asks you to delete old templates folder.

**Comment by renewsorensen** [comment]
Your right i did not follow the instructions, i was not able to see them
![gogs_problem8](https://cloud.githubusercontent.com/assets/10239939/11322764/26728c08-90fb-11e5-8f50-bee004e23ee2.PNG)

The main issue seems to remain after the upgrade.
![gogs_problem7](https://cloud.githubusercontent.com/assets/10239939/11322766/3fbcc6a6-90fb-11e5-9460-a79f6b3b624d.PNG)

And i swear i did upgrade :-)

**Comment by Unknwon** [comment]
This fix is made after release, it's on master, which means you need to update by source code.

**Comment by renewsorensen** [comment]
well this is not a big issue for me so i just wait the next release.

Thanks for your help though :+1:

**Comment by Unknwon** [comment]
:trollface:

**Comment by stonerl** [comment]
@Unknwon I run Gogs in http-mode behind a Reverse-Proxy that is doing the https

![screenshot-rokuhara japanologie kultur uni-tuebingen de 2015-11-22 10-29-45](https://cloud.githubusercontent.com/assets/2091312/11322988/0d8ebdde-9104-11e5-8f31-c7b24206917d.png)

**Comment by Unknwon** [comment]
@stonerl Oops... good catch.

**Comment by Unknwon** [comment]
More fix pushed.

**Comment by stonerl** [comment]
:+1:
