### ISSUE TITLE
Pull request can not change branch when both sides are organizations

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#2014]
I was not able to reopen issue #2011. I made a comment to issue, addition to that comment is that, i tried this again on https://try.gogs.io and found that did not work either. First time i tried this on https://try.gogs.io i did it on a personal repository. I did not find any problems at this point. Then i tried it on a organization on both sides, at this point the 400 error code appeared.

you can try it with user u: rene p:1234 and u: rene2 p: 1234

**Comment by Unknwon** [comment]
> Then i tried it on a organization on both sides, at this time the the 400 error code appeared.

Two accounts you give are both personal, I don't get this sentence. And what is a 400 error? Please be precise on description. :sweat:

**Comment by Unknwon** [comment]
OK, anyway, I can reproduce the bug now, PR between two organizations.

**Comment by renewsorensen** [comment]
Well its good to hear that you are able to reproduce.

**Comment by Unknwon** [comment]
:trollface: Please be more precise on error description next time. Guess is not good for debugging.

**Comment by renewsorensen** [comment]
Well i thought i was pretty clear in issue #2011, were you wrote that i should reopen if the problem  remained. I was not able to reopen, so I created this issue and referenced to #2011. It is actully pretty to communicate bugs, where i as a user don't realize there are then one approache.That is why i nearly allways uses screen shorts, so you don't have to guess, you see what i see.

**Comment by Unknwon** [comment]
:sweat: you're right, my bad.

**Comment by Unknwon** [comment]
Hi, can you test `develop` branch or https://try.gogs.io again?

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by renewsorensen** [comment]
Sorry for a delayed answer, i have been on a long vacation, but i can
confirm that it is fixed, thanks...


*Med Venlig Hilsen / Best RegardsRené Sørensen*


Egevej 44
7470  Karup J
Mobil: +45 2283 8469

rene@egevej44.dk


2015-12-20 7:07 GMT+01:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
Thanks your confirmation!
