### ISSUE TITLE
Add "Sync now" button to mirror repository

### ISSUE THREAD

**Issue by lenucksi** [gogits/gogs#2018]
As a user of the mirrored repository feature, I would like to be able to kick off an update / sync of the mirror with a button in the mirrored repositories UI.

**Comment by KillTheIdols** [comment]
:+1:

**Comment by Unknwon** [comment]
@bkcsoft maybe we should have something like **Mirror Settings** panel?

**Comment by bkcsoft** [comment]
Yeah, I thought about that as well. Doing it like the mock-up would be hard-ish

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
