### ISSUE TITLE
Disable version display #2

### ISSUE THREAD

**Issue by SoftCreatR** [gogits/gogs#2020]
Just performed the upgrade and everything works as expected. However, there are still some references to the gogs version left (#1992)

Two i found are the version strings for the gogs.css and gogs.js. Dunno, if there are more, but i didn't took a closer look.

**Comment by stonerl** [comment]
The version is still shown on 404 pages:
![screenshot-rokuhara japanologie kultur uni-tuebingen de 2015-11-23 11-48-41](https://cloud.githubusercontent.com/assets/2091312/11334913/725ea736-91d8-11e5-8f06-94bdab7336aa.png)
I assume the same applies for 500 pages.

**Comment by Unknwon** [comment]
Good catches!

**Comment by Unknwon** [comment]
Pushed those fixes to `develop` branch.
