### ISSUE TITLE
Manually sorting issues

### ISSUE THREAD

**Issue by mkaito** [gogits/gogs#2023]
I would like to use gogs itself to manage my code based projects. I've gotten used to having a prioritized "stack" of issues. When one gets done, I just do the next in the list. I actually think @Unknwon does the same, except he does it in trello.

Now that I said that, a per-repo task board that integrates well with git would be a dream!

**Comment by Unknwon** [comment]
> Now that I said that, a per-repo task board that integrates well with git would be a dream!

It is indeed a dream :trollface:

Gogs has no wishes to integrate kanboard-like thing into it, you can always use APIs to integrate together for what they do best in each part.

**Comment by Unknwon** [comment]
However, you may want to follow on https://github.com/gogits/gogs/issues/1741

**Comment by mkaito** [comment]
I've seen that there's a bunch of kanban things that integrate with github. I'm not sure what can be done to integrate them with gogs.

**Comment by Unknwon** [comment]
I don't know about those Chrome plugins, but others use GitHub APIs, so you can use Gogs APIs.

**Comment by Unknwon** [comment]
Closing now and please continue discussion on http://forum.gogs.io/category/2/general-discussion
