### ISSUE TITLE
Domain of email in login must be same as uppercase as lowercase

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2026]
I logged with my email and I like to write the first letter in uppercase (ex, myUser@Gmail.com) but Gogs think that the email that I write and It verify (myUser@gmail.com) are different, but only change a letter (g) and it's irrelevant because the domain of a email can't be in uppercase.

Sorry for my bad english, saludos!

**Comment by Unknwon** [comment]
Thanks your feedback!

But can you give more detail of words `Domain email login`?

**Comment by xxxtonixxx** [comment]
Hahah, I'm sorry, I refers to domain of email when you log in

![issue](https://cloud.githubusercontent.com/assets/7110786/11354918/8ff78a92-9250-11e5-95fa-ad6c5c393200.png)

**Comment by Unknwon** [comment]
Thanks, are you using SMTP auth or just try to login via e-mail?

**Comment by xxxtonixxx** [comment]
I try to only login via email, I prefer this.

**Comment by Unknwon** [comment]
I think you are not answering my question...

**Comment by xxxtonixxx** [comment]
Ok, sorry, I don't use SMTP auth and the email is indifferent, I can use anythingUser@anythingDomain.hello as my email to log in.

**Comment by Unknwon** [comment]
I see, let me check. It should all converts to lowercases.

**Comment by xxxtonixxx** [comment]
I think that, but I don't log in if I use myuser@Gmail.com, but yes, if I use myuser@gmail.com. When I registered I write my email so myuser@Gmail.com (uppercase) and this saved as myuser@gmail.com (lowercase)

**Comment by Unknwon** [comment]
I've pushed a fix to `develop`, which converts to lower case first and try to match on database.

**Comment by xxxtonixxx** [comment]
Ok, thank you!

**Comment by roidelapluie** [comment]
@Unknwon is there a security risk?

It should be forbidden to have 2 users registered: foo@Gail.com and foo@gail.com because one could login to the other account...

**Comment by Unknwon** [comment]
No, it's not possible to register same email with diff cases.

**Comment by Unknwon** [comment]
It was just login check didn't convert to lower case first.

**Comment by Unknwon** [comment]
Hmm, why I forgot close this one...
