### ISSUE TITLE
组织工单只能指派成员中只有创建者

### ISSUE THREAD

**Issue by mindfocus** [gogits/gogs#2027]
Rt. 最新版gogs 感谢

**Comment by Unknwon** [comment]
Issues can only be assigned to who has write access.

**Comment by mindfocus** [comment]
组织里面有成员，但是只能显示指派给创建者这一个成员，同时组织的库里面不需要添加协作者，则默认为组织成员都是协作者，错误应该是在这个位置吧

**Comment by mindfocus** [comment]
是有写权限，想指派给创建issue者的

**Comment by Unknwon** [comment]
> 同时组织的库里面不需要添加协作者，则默认为组织成员都是协作者

I have no idea what do you mean by this.

Repository and member belong to team, this team must have write access in order to give write access to its members.

**Comment by mindfocus** [comment]
明白了 组织成员可以提交issue ，但是需要设置他到owner组中才可以指派  但是这样的话就需要把所有成员都加入到owner组才可以啊 这样给出的权限是不是太多了？

**Comment by Unknwon** [comment]
You can create another team that has write access, and add corresponding repositories and members to that team.

**Comment by mindfocus** [comment]
谢谢 完全明白了

**Comment by Unknwon** [comment]
:trollface: No problem.
