### ISSUE TITLE
Do not show content of issue in activity timeline

### ISSUE THREAD

**Issue by melote** [gogits/gogs#2029]
I found something that may help
1. The dashboard displays the issue content completely，so that if we have many contents, all page view will be full of it.
2. The dashboard issue seems not to support markdown, so it's full of mess when we have many contents .

**Comment by Unknwon** [comment]
Thanks!

> 1. The dashboard displays the issue content completely，so that if we have many contents, all page view will full of it.

How about only show the first sentence? Or x characters?

**Comment by melote** [comment]
@Unknwon I think there is no need to display the issue contents because the markdown will lead to font size inconsistency if decide to use it, I think just showing the head title is a good idea, how do you think?

**Comment by Unknwon** [comment]
@melote I can extract out content from markdown which becomes plain text. 

Rethink based on my new information?

**Comment by melote** [comment]
Aha, agreed, that's best but need more work.

**Comment by Unknwon** [comment]
@melote someone has implemented and I use that in another project, so port work should be easy.

**Comment by mkaito** [comment]
Currently, markdown is presented without a render pass, in a single line. This makes text largely unreadable, as it's just a mush of text. Showing the issue title should be enough. One can always click on it to see the entire issue, content and discussion.

**Comment by Unknwon** [comment]
I finally decided to just show the issue title :D

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by melote** [comment]
test is ok.

**Comment by Unknwon** [comment]
:clap:
