### ISSUE TITLE
Consistency in data location

### ISSUE THREAD

**Issue by pennal** [gogits/gogs#2030]
As of now, gogs saves the data of the installation in two different places:
 * `custom/conf/` - Configuration File
 * `data/avatars/` - User Avatars (if enabled)

This means that if the user is to reinstall the program, he has to dig through different paths to restore the system. Wouldn't it be better to put all installation data in a common location, as to simplify backups/restores? What I propose would be:
 * `custom/conf/` - Configuration File
 * `custom/avatars/` - Folder for avatars
 * `custom/...` - Any other user data

**Comment by Unknwon** [comment]
Hi,

- `custom` is for customization, it is a system admin level config, by dictionary, it is not equivalent to `data`.
- `data` is what program (Gogs) and users generated.

**Comment by Unknwon** [comment]
You can continue discussion on http://forum.gogs.io/category/2/general-discussion .

Close this by https://github.com/gogits/gogs#notices
