### ISSUE TITLE
Migrating plotly/plotly.js from GitHub as mirror results in 500 and empty repo page

### ISSUE THREAD

**Issue by starbugs** [gogits/gogs#2031]
I tried mirroring https://github.com/plotly/plotly.js.git. It looks as if the actual migration worked, but gogs returns an empty page for the repo with a 500 HTTP status. Unfortunately, I didn't find more info in the log files.

gogs 0.7.19.1121 Beta
git 1.7.9.5
Ubuntu 12.04 LTS

**Comment by Unknwon** [comment]
Hi, I just tried on https://try.gogs.io/unknwon/plotly.js

**Comment by Unknwon** [comment]
Make sure your network connection is good.

**Comment by starbugs** [comment]
Tried again. Same result. Is there any way I can get more debug info/logs? And is there a way to remove the repo? I cannot get to the settings page anymore and the admin panel seems to only list the repos, but doesn't offer an option to delete. Thanks!

**Comment by Unknwon** [comment]
>  Same result. Is there any way I can get more debug info/logs? 

You can find at `/path/to/gogs/log/gogs.log`.

> And is there a way to remove the repo? I cannot get to the settings page anymore and the admin panel seems to only list the repos, but doesn't offer an option to delete.

In this case, please follow on https://github.com/gogits/gogs/issues/1386

**Comment by starbugs** [comment]
Thanks. gogs.log doesn't have anything regarding the empty repo page. I check the repo and it has been cloned succesfully.

Regarding the deletion of the repositories that aren't accessible anymore I can't find anything in #1386. Sorry to bother you with this, maybe I'm just overlooking something.

**Comment by Unknwon** [comment]
I'm not sure what's going on your side based on the info you posted here.

And if you want to delete that, you can delete repo files first, then go to admin dashboard click `remove repo that missing Git files`.

**Comment by starbugs** [comment]
Great thanks!

I ran gogs from the command line and here's the output for the error:
[Macaron] Started POST /repo/migrate for 95.119.65.22
2015/11/24 20:53:42 [T] action.newRepoAction: starbugs/plotly.js
[Macaron] Completed /repo/migrate 302 Found in 17.618104956s
2015/11/24 20:54:00 [T] Repository migrated[29]: starbugs/plotly.js
[Macaron] Started GET /starbugs/plotly.js for 95.119.65.22
[Macaron] PANIC: runtime error: index out of range
/usr/local/go/src/runtime/panic.go:423 (0x4c2169)
/usr/local/go/src/runtime/panic.go:12 (0x4c0649)
/home/vagrant/go/src/github.com/gogits/gogs/modules/base/markdown.go:293 (0xa3759c)
/home/vagrant/go/src/github.com/gogits/gogs/modules/base/markdown.go:312 (0xa37842)
/home/vagrant/go/src/github.com/gogits/gogs/routers/repo/view.go:205 (0x95d3f1)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86dacc)
/home/vagrant/go/src/github.com/go-macaron/session/session.go:186 (0x7bd9a4)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86dacc)
/home/vagrant/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x882f52)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86dacc)
/home/vagrant/go/src/gopkg.in/macaron.v1/logger.go:40 (0x881b9e)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:184 (0x8846c4)
/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:286 (0x87b04d)
/home/vagrant/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x872f8a)
/usr/local/go/src/net/http/server.go:1862 (0x7757be)
/usr/local/go/src/net/http/server.go:1361 (0x772fae)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x4f5701)
[Macaron] Completed /starbugs/plotly.js 500 Internal Server Error in 785.83792ms

**Comment by Unknwon** [comment]
OK, thanks!

Now this issue is duplicated to https://github.com/gogits/gogs/issues/2019
