### ISSUE TITLE
Fatal large repo push over http

### ISSUE THREAD

**Issue by externl** [gogits/gogs#2032]
```
Username for 'http://foo.bar.com': externl
Password for 'http://externl@foo.bar.com':
Counting objects: 309856, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (75859/75859), done.
error: RPC failed; result=55, HTTP code = 0GiB | 1.42 MiB/s
fatal: The remote end hung up unexpectedly
Writing objects: 100% (309856/309856), 1.56 GiB | 97.66 MiB/s, done.
Total 309856 (delta 208305), reused 302647 (delta 202233)
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

The server also seems to crash.

**Comment by stonerl** [comment]
@externl which version of gogs do you use?

**Comment by Unknwon** [comment]
Please post your server side log.

**Comment by externl** [comment]
```© 2015 Gogs Version: 0.7.19.1121 Beta Page: 133ms Template: 62ms```

**Comment by externl** [comment]
Looks like I'm running out of memory. Probably the same issue as https://github.com/gogits/gogs/issues/636.

**Comment by Unknwon** [comment]
Thanks for following up.

> Looks like I'm running out of memory

Yes, in this case, this issue is a duplication. :mask:

**Comment by externl** [comment]
Any idea if SSH have the same issue?

**Comment by Unknwon** [comment]
> Any idea if SSH have the same issue?

Any more info?

**Comment by externl** [comment]
Does pushing a large repo over SSH also consume lots of memory?

**Comment by Unknwon** [comment]
> Does pushing a large repo over SSH also consume lots of memory

From my experience, SSH does not behave the same, it seems directly writes to file system.

**Comment by externl** [comment]
Worked fine with SSH.

**Comment by Unknwon** [comment]
Very well. :clap:
