### ISSUE TITLE
Label readability 

### ISSUE THREAD

**Issue by lukasdietrich** [gogits/gogs#2033]
Labels with a dark color aren't very readable:

![image](https://cloud.githubusercontent.com/assets/1913775/11382975/4ac63bac-9305-11e5-90d5-548ffd6e4643.png)

It would be nice, if the font color could be adjusted according to the background color:

![image](https://cloud.githubusercontent.com/assets/1913775/11382996/6f68fc88-9305-11e5-9221-aa13a50f6b67.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

Indeed.

**Comment by nanoant** [comment]
@Unknwon I think the problem is that instead of using Semantic UI colors, Gogs uses its own palette. I humbly suggest to stick to Semantic UI label colors, it is 14 colors altogether (13 colored + 1 default light gray).

http://semantic-ui.com/elements/label.html#colored

**Comment by Unknwon** [comment]
@nanoant you're right, but I don't see it supports custom hex color code for labels in docs?

**Comment by nanoant** [comment]
@Unknwon  Any reason to use more than 14 colors?

**Comment by Unknwon** [comment]
@nanoant 14 colors is normally good enough, but then someone will come up say why Gogs only limits to 14 colors.

**Comment by nanoant** [comment]
@Unknwon fair enough, but then you can call it custom color, and use current approach, and simply don't care about side-effects (aka unreadibility). My suggestion is that make default (built-in) colors to be Semantic UI colors (CSS classes).

**Comment by Unknwon** [comment]
@nanoant I know it does not care when I wrote the code.

The solution is quite simple actually, find a center point (I believe SUI already has one), then use a template function to return whether white or black color on text.

**Comment by nanoant** [comment]
@Unknwon Yeah, you're right.

**Comment by exmex** [comment]
+1 (y) could this please be implemented? It's VERY hard to read some labels..

**Comment by ciruz** [comment]
Why you not just invert the background-color and use this color as text color?

Sadly I'm not familiar with go, but inverting is not hard with JS / PHP, cant be this harder in go:

http://jsfiddle.net/salman/f9Re3/
http://www.mattlag.com/scripting/hexcolorinverter.php
http://www.jonasjohn.de/snippets/php/color-inverse.htm

**Comment by Unknwon** [comment]
@ciruz thanks!

**Comment by lukasdietrich** [comment]
Inverting colors is not per se readable. Take for example the color [`#7f7f7f` ](http://jsfiddle.net/3r0q40xu/).
I think a lightness threshold that decides if the text color is white or black would be a better solution.

**Comment by Unknwon** [comment]
@lukasdietrich yes, would `7f7f7f` be a good split point for black and white?

**Comment by lukasdietrich** [comment]
@Unknwon I was talking about lightness. See <https://en.wikipedia.org/wiki/Relative_luminance> and <http://jsfiddle.net/3r0q40xu/1/>

**Comment by Unknwon** [comment]
:100:

**Comment by lukasdietrich** [comment]
See https://github.com/gogits/gogs/pull/2710.

**Comment by Unknwon** [comment]
You can now test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Quick demo: 

![image](https://cloud.githubusercontent.com/assets/2946214/13374014/0296557a-dd46-11e5-966f-7ccf2be4b51d.png)

**Comment by ciruz** [comment]
Thanks @Unknwon works fine (tested in 0.8.46.0227).
