### ISSUE TITLE
Cannot find upstream after git clone

### ISSUE THREAD

**Issue by xvector** [gogits/gogs#2034]
After I clone the repository from remote, it claims 'the upstream is gone', when I try to pull or push ,it tells me 'Gogs: Key permission denied'.
This issue dissappears not only on my own vps but on try.gogs.io.
This issue occurs when i use 'ssh'. 
> version: gogs_v0.7.19_linux_amd64.tar.gz

**Comment by Unknwon** [comment]
Thanks your feedback!

> it claims 'the upstream is gone'

How? Any screenshot?

> 'Gogs: Key permission denied'.

The only possible error message for this, is you added your SSH key as a deploy key, which does not have permission to push.

**Comment by Unknwon** [comment]
FYI https://github.com/blog/2024-read-only-deploy-keys

**Comment by xvector** [comment]
![11 25 2015 11 57](https://cloud.githubusercontent.com/assets/7066268/11388032/2f2b5e06-936c-11e5-86b0-1ec7e81885f1.gif)
![11 25 2015 11 58](https://cloud.githubusercontent.com/assets/7066268/11388033/2fce7122-936c-11e5-81b3-6680a8738c2a.gif)

**Comment by Unknwon** [comment]
Thanks for screenshots.

But I have same comments as previous.

**Comment by xvector** [comment]
Thank u!
I misunderstood the meaning of "deploy key".

**Comment by Unknwon** [comment]
:trollface:
