### ISSUE TITLE
Show author e-mail in commit diff

### ISSUE THREAD

**Issue by karasz** [gogits/gogs#2035]
Is it possible to show somehow in gogs the git headers of a commit like Author, Commiter with emails?

**Comment by Unknwon** [comment]
Hi,

What and how to get git headers you are saying for a commit? Any examples?

**Comment by karasz** [comment]
Hi,
the date is already there in newSignatureFromCommitline, in sig.Email. You just have to display it in the commit page. Here is an example:
![screenshot](https://cloud.githubusercontent.com/assets/74192/11405390/140cab68-93b0-11e5-985a-6dc14ca7743d.png)

**Comment by Unknwon** [comment]
Thanks for the info.

But Gogs already displays author, commit, tree, parent. Which one you think is missing?

**Comment by karasz** [comment]
Just the emails of the author and commiter.

**Comment by Unknwon** [comment]
OK, I see.

**Comment by Unknwon** [comment]
It is now possible in `develop` branch and https://try.gogs.io/unknwon/gogs/commit/6a5c87afdd32286cb1e8f92d330960f5f8641967

(email is hidden for non-login visitors)

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/11691876/f798ae26-9e6a-11e5-8536-63f2ca828a52.png)

**Comment by Unknwon** [comment]
Close as implemented.
