### ISSUE TITLE
Add "New Mirror" button on Dashboard

### ISSUE THREAD

**Issue by MarvinMenzerath** [gogits/gogs#2037]
Hi,

I just noticed that on the Dashboard the two tabs "Repository" and "Organization" both have a "New Repository" and "New Organization" button, but the tab "Mirror" is missing a button to create a new mirror:

![Image](https://cloud.githubusercontent.com/assets/2064514/11405381/a6d463b8-93a7-11e5-8f48-fb0344919536.png)

Gogs Version is 0.7.22.1125 Beta.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Gibheer** [comment]
With my pull request merged, I think this can be closed.

**Comment by Unknwon** [comment]
That is the first step, but migration is not quite same as mirror, so I need to fix some minor things.

**Comment by Unknwon** [comment]
It is now possible on `develop` branch and https://try.gogs.io

**Comment by Unknwon** [comment]
Close as implemented.
