### ISSUE TITLE
Motivation for reserving user names

### ISSUE THREAD

**Issue by gramakri** [gogits/gogs#2040]
I see in the code reserves certain user names and patterns

https://github.com/gogits/gogs/blob/52c8f691630548fe091d30bcfe8164545a05d3d5/models/repo.go#L393

What is the motivation for this? In our case, we had a user named 'admin' who could not login because of this.

**Comment by Unknwon** [comment]
For routing purpose, in Gogs `/:username` is in the top-level, so you can't tell `/admin` is admin dashboard or it's a user's profile page.

**Comment by gramakri** [comment]
@Unknwon ah, i see. I guess this can be disambiguated by moving the routes to the /username/:username (or similar). It seems a little dangerous to have /:username in toplevel just like that. What do you think?

**Comment by Unknwon** [comment]
> It seems a little dangerous to have /:username in toplevel just like that. 

Need proven on this. As something similar to GitHub, it's better to use similar routing for user experience.

**Comment by Unknwon** [comment]
Also for the use case of `admin`, it's too obvious user name to guess for social engineering.

**Comment by Unknwon** [comment]
Closing now and please continue discussion on http://forum.gogs.io/category/2/general-discussion

**Comment by gramakri** [comment]
@Unknwon Tried signing up, but I don't get the confirmation email from the forum. Tried to post the below.

```
Continuing discussion of  https://github.com/gogits/gogs/issues/2040 here.

Thanks for the explanation, I get the problem now. IMO, github routing is not ideal. May I suggest reddit style, reddit.com/u/<username> ? But I can understand if you don't want to fix it for aesthetics :-)

We should probably fix the login form to atleast say the name is reserved.
```

**Comment by Unknwon** [comment]
> We should probably fix the login form to atleast say the name is reserved.

You hacked `admin` into database so you do get this, when you try to sign up with admin, Gogs does tell you that is reversed.

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/11449115/621e1c2c-9538-11e5-8972-760b8b776052.png)
