### ISSUE TITLE
Webhook will sometimes use other format

### ISSUE THREAD

**Issue by mkaito** [gogits/gogs#2041]
I've configured a webhook to poke a drone service for CI goodness. After 4 successful requests in gogs format, gogs decided to start using slack format instead.

**Comment by Unknwon** [comment]
What is your Gogs version?

**Comment by mkaito** [comment]
0.7.22 binary

**Comment by mkaito** [comment]
I removed and re-added the webhook, and it was stuck in slack format again. Removed again, added again, and it worked a few times, then switched to slack format.

**Comment by Unknwon** [comment]
Thanks. What does delivery history show?

**Comment by mkaito** [comment]
I just pushed some commits.... and it worked. For no apparent reason. It was using the wrong format 10 minutes ago!

Anyway, delivery history will show a payload in slack format, even though it is a gogs type webhook, and the server returns a 500 (index out of range in drone logs, presumably because it's trying to index a nonexistent field in the json payload).

**Comment by Unknwon** [comment]
Ok, thanks your info!

**Comment by mkaito** [comment]
I've pushed a couple times today. Sometimes it works, sometimes it won't. Seems random to me, I can't seem to find a pattern.

**Comment by Unknwon** [comment]
The webhook that randomly sends slack format, does it still show it is Gogs format when you try edit its settings?

**Comment by mkaito** [comment]
You know, I haven't seen it fail since I upgraded to `devel`. I'm not sure the bug is still there.

**Comment by Unknwon** [comment]
Yes, but you still need to answer my question:

> The webhook that randomly sends slack format, does it still show it is Gogs format when you try edit its settings?

**Comment by mkaito** [comment]
I can't reproduce right now, so speaking from memory: yes it did show up as a gogs type webhook in the settings, but the payload was in slack format when sent.

**Comment by Unknwon** [comment]
> yes it did show up as a gogs type webhook in the settings, but the payload was in slack format when sent.

OK I see, I'm trying to spot when the unexpected behavior happen, looks like it happens when delivery the hook.

**Comment by mkaito** [comment]
Sounds right. It all looks A-okay right up to when the payload is delivered.

FYI, I once had a hook stuck in slack-mode right as it was created, but that hook was created by Drone, the CI server, which led me to open an issue with them. Manually recreating the hook seemed to fix it, but it only delivered a gogs-format payload a couple times before getting stuck in slack-mode again. After that, it would intermittently deliver in either format.

**Comment by Unknwon** [comment]
Thanks your detail!

Let's see if it happens again and find a pattern for it.

**Comment by bhchew** [comment]
After upgrading to 0.7.33 beta from 0.7.22, seems the form is wrong. Prior to the upgrade seems to work fine.

Screenshots attached.
![slack-result](https://cloud.githubusercontent.com/assets/1488128/11618579/c870a1f6-9cd7-11e5-85f9-b77976c3213d.JPG)
![slack-request](https://cloud.githubusercontent.com/assets/1488128/11618580/c873c0e8-9cd7-11e5-8680-ee4a9db07e37.JPG)

**Comment by Unknwon** [comment]
@bhchew Hi! Thanks your report!

I've pushed fix to `master` branch, can you help test again?

**Comment by bhchew** [comment]
Yep it works on this build now!

https://hub.docker.com/r/gogs/gogs/builds/bvmnrq6tdsgm2trtmte9oa7/

**Comment by Unknwon** [comment]
@bhchew awesome! :wink:

**Comment by mkaito** [comment]
Works as far as I can tell. Will reopen if it happens again. Thanks!
