### ISSUE TITLE
Delete repository does not remove its stars

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2042]
If I go to the admin panel statistic I can see that there are more stars then I have repositories. In the database is seems that the table star is not being cleared after an repository is deleted.

**Comment by Unknwon** [comment]
What is your version of Gogs?

**Comment by drsect0r** [comment]
Gogs Version: 0.7.22.1125

**Comment by Unknwon** [comment]
Thanks.

> If I go to the admin panel statistic I can see that there are more stars then I have repositories

So you sure that you're the only user?

**Comment by Unknwon** [comment]
Based on https://github.com/gogits/gogs/blob/master/models/repo.go#L1564-L1569 , it recount after every start, so you may want to look at your star table.

**Comment by drsect0r** [comment]
Yes, i'm the only active user. Before opening this issue I verified in the database that the stars where on my account but linking to a non existed repository. I have now removed the stars but have database backups; if you would like a screenshot.

**Comment by drsect0r** [comment]
Seems not to be working. I update gogs almost every day. I noticed the incorrect star count around the beginning of this week.

**Comment by Unknwon** [comment]
Are all records in stars table valid?

**Comment by drsect0r** [comment]
Now they are, I removed the incorrect ones manually.

**Comment by Unknwon** [comment]
OK, so does count go right now ?

**Comment by drsect0r** [comment]
No, I just created a new repository, give it a star and removed the repository. I now have 11 stars and 10 repositories.

**Comment by Unknwon** [comment]
I see, I saw code does not remove stars when delete repo.

**Comment by drsect0r** [comment]
I have also restarted Gogs with the following commands. The stars remain the same. 
```
root@summit:~# systemctl stop gogs
root@summit:~# systemctl start gogs
```

**Comment by damianb** [comment]
This would be easily fixed by use of a foreign key and using ON DELETE CASCADE for the big two dbs, though on a cursory look I can't see if/where foreign keys are defined.

**Comment by Unknwon** [comment]
@drsect0r Hi, I've pushed a fix which should remove corresponding stars when delete a repository.

**Comment by drsect0r** [comment]
@Unknwon Thanks :)

**Comment by Unknwon** [comment]
:beers:
