### ISSUE TITLE
Team repo user access

### ISSUE THREAD

**Issue by ChkonCSD** [gogits/gogs#2043]
In 0.7.20.1121 Beta on x64 windows server team members (not owners) of organization can't access (404) to private repository page.

**Comment by Unknwon** [comment]
Because the user is not in any team has access to that private repository.

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.

**Comment by bhchew** [comment]
Hmm maybe more meaningful pages explaining they don't have access?

Members in the same organization are able to view activities in the dashboard on repos that are not accessible to them. Clicking on it will return 404 which might be mistaken for a bug.

Or a better suggestion is to hide all the activities for repos that they do not have access.

**Comment by Unknwon** [comment]
@bhchew 

> Or a better suggestion is to hide all the activities for repos that they do not have access.

Good point, please file an issue for this.

**Comment by bhchew** [comment]
yep will do!
