### ISSUE TITLE
Slack hook too verbose on fallback

### ISSUE THREAD

**Issue by mkaito** [gogits/gogs#2045]
We use Slack, which I use over IRC, so I get the fallback text for hooks. I've found the gogs notifications to be... verbose. Let me illustrate:

I force-pushed to a repo, which is not really the average case, but it serves to illustrate the spam.

This is what it looks like in the Slack client:
![gogs_slack_web](https://cloud.githubusercontent.com/assets/20434/11443742/7920ff3c-9517-11e5-81b6-650a83370cbb.png)

This looks sweet, and thanks to the goodness of hyperlinked text, it is concise yet practical.

Now, on IRC it looks like this:
![gogs_slack_fallback](https://cloud.githubusercontent.com/assets/20434/11443760/99e6864c-9517-11e5-9dd2-6784cd45a4cb.png)

The first line contains a full link to the repo, a full link to the branch, and a full link to the full diff. Then we have a line for each commit with a full link to that changeset.

While that certainly contains every link one could possibly want, I think it's actually *too much*. Extensive linking is fine with hyperlinked text, but plaintext links are huge, and the amount of links actually makes it hard to read.

I propose reducing the amount of text to the bare minimum, with only a single link where one can see everything. As an IRC user, I'm perfectly fine with not getting every bell and whistle present in the full slack interface. That's precisely *why* I use IRC.

So here's what I'd put in the fallback, at most:

```
mkaito pushed 5 new commits to potato/master:  http://git.guildpad.com/haven/potato/compare/8317d2518487c1950626babacd95aa584ff486da...4912bcf99b04691f67913cdd7ffccdcbcc666489
```

As a bit of a minimalist, I still think that link is a bit on the longer side. One way to work around this would be shortening the link to use only the minimum necessary part of the SHA, which is usually the first 6 characters:

```
mkaito pushed 5 new commits to potato/master:  http://git.guildpad.com/haven/potato/compare/8317d2...4912bc
```

Alternatively, just link to the commits page, and let the user work out what he wants to see. This would be further supported by the ability to compare commits right from the commits page (but that's a separate issue).

```
mkaito pushed 5 new commits to potato/master: http://git.guildpad.com/haven/potato/commits/master
```

**Comment by mkaito** [comment]
> Alternatively, just link to the commits page, and let the user work out what he wants to see. This would be further supported by the ability to compare commits right from the commits page (but that's a separate issue).

#2046 <-- It **is** a separate issue now :stuck_out_tongue:

**Comment by Unknwon** [comment]
Hmm.. I never know about the `fallback` think, as it's a Slack webhook, it's obvious that make sure the hook looks nice on Slack.

Anyway to config fallback inside Slack hook?

**Comment by mkaito** [comment]
It's part of the JSON payload. It's a toplevel string field:

```json
{
    "fallback": "Text to show as fallback"
}
```

**Comment by Unknwon** [comment]
@mkaito thanks your info!

**Comment by Unknwon** [comment]
Did some research, looks like `fallback` is not in top-level? https://api.slack.com/docs/attachments

**Comment by Unknwon** [comment]
Hi, just pushed a commit to `develop` branch, can you help test again?

**Comment by mkaito** [comment]
I'll have to figure out how to build gogs and push the binary to the server.

**Comment by Unknwon** [comment]
@mkaito you need to upload everything, not just binary.

**Comment by mkaito** [comment]
Well, it still feels very verbose.

![gogs_slack_fallback](https://cloud.githubusercontent.com/assets/20434/11581412/943bd4dc-9a39-11e5-8dbf-b33acc959258.png)

Not sure what you think?

**Comment by mkaito** [comment]
I think it still feels too verbose.

![gogs_slack_fallback](https://cloud.githubusercontent.com/assets/20434/11581424/c46f4724-9a39-11e5-98e1-eb7ce28e44d9.png)

What do you think?

**Comment by mkaito** [comment]
Oh, and when clicking on that particular webhook:

```
runtime error: invalid memory address or nil pointer dereference

/usr/lib/go/src/runtime/panic.go:423 (0x42ba09)
/usr/lib/go/src/runtime/panic.go:42 (0x42a0c9)
/usr/lib/go/src/runtime/sigpanic_unix.go:24 (0x440a2a)
/home/chris/dev/go/src/github.com/gogits/gogs/routers/repo/setting.go:441 (0x82397d)
/home/chris/dev/go/src/github.com/gogits/gogs/routers/repo/setting.go:478 (0x8243fb)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:104 (0x73b8bc)
/home/chris/dev/go/src/github.com/go-macaron/session/session.go:186 (0x68b624)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:104 (0x73b8bc)
/home/chris/dev/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x750da2)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:104 (0x73b8bc)
/home/chris/dev/go/src/gopkg.in/macaron.v1/logger.go:40 (0x74f9ee)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/router.go:184 (0x752524)
/home/chris/dev/go/src/gopkg.in/macaron.v1/router.go:286 (0x748e9d)
/home/chris/dev/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x740dda)
/usr/lib/go/src/net/http/server.go:1862 (0x642d5e)
/usr/lib/go/src/net/http/server.go:1361 (0x64054e)
/usr/lib/go/src/runtime/asm_amd64.s:1721 (0x45ef21)
```

**Comment by Unknwon** [comment]
> Oh, and when clicking on that particular webhook

Can you reproduce on https://try.gogs.io ?

**Comment by Unknwon** [comment]
Pushed more fixes to make fallback shorter to `develop` branch, please help test again!

**Comment by mkaito** [comment]
> Can you reproduce on https://try.gogs.io ? (if yes, please post the link here so I can debug)

It only happens with that particular webhook. Opening other webhooks works fine. It's an organization-wide webhook that posts activity to slack. So it might be tricky to reproduce on the demo site.

> Pushed more fixes to make fallback shorter to develop branch, please help test again!

Will do.

**Comment by Unknwon** [comment]
> It's an organization-wide webhook that posts activity to slack. So it might be tricky to reproduce on the demo site.

It would be helpful try to upgrade to latest `master`, so the panic line number should become helpful.

**Comment by mkaito** [comment]
I just tried adding an organization webhook on try.gogs.io and it shows a blank page. Presumably, it panics on your end?

**Comment by mkaito** [comment]
Here's the backtrace from my server. Compiled 5 minutes ago off the develop branch:

```
runtime error: invalid memory address or nil pointer dereference

/usr/lib/go/src/runtime/panic.go:423 (0x42ba09)
/usr/lib/go/src/runtime/panic.go:42 (0x42a0c9)
/usr/lib/go/src/runtime/sigpanic_unix.go:24 (0x440a2a)
/home/chris/dev/go/src/github.com/gogits/gogs/routers/repo/setting.go:315 (0x82135c)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:104 (0x73b8bc)
/home/chris/dev/go/src/github.com/go-macaron/session/session.go:186 (0x68b624)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:104 (0x73b8bc)
/home/chris/dev/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x750da2)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:104 (0x73b8bc)
/home/chris/dev/go/src/gopkg.in/macaron.v1/logger.go:40 (0x74f9ee)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/lib/go/src/reflect/value.go:432 (0x85ed9a)
/usr/lib/go/src/reflect/value.go:300 (0x85da61)
/home/chris/dev/go/src/github.com/go-macaron/inject/inject.go:117 (0xb014b2)
/home/chris/dev/go/src/gopkg.in/macaron.v1/context.go:113 (0x73b9d7)
/home/chris/dev/go/src/gopkg.in/macaron.v1/router.go:184 (0x752524)
/home/chris/dev/go/src/gopkg.in/macaron.v1/router.go:286 (0x748e9d)
/home/chris/dev/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x740dda)
/usr/lib/go/src/net/http/server.go:1862 (0x642d5e)
/usr/lib/go/src/net/http/server.go:1361 (0x64054e)
/usr/lib/go/src/runtime/asm_amd64.s:1721 (0x45ef21)
```

**Comment by Unknwon** [comment]
@mkaito yes, thanks a lot! I'll take a deep look.

**Comment by mkaito** [comment]
Have fun :smile_cat:

**Comment by Unknwon** [comment]
Just pushed a fix for panic to `develop` branch. :D

**Comment by mkaito** [comment]
Seems to have fixed the panic, indeed.

**Comment by Unknwon** [comment]
> I don't suppose you could add a "test webhook" button, for convenience, at some point?

I think you should follow: https://github.com/gogits/gogs/issues/1857

**Comment by mkaito** [comment]
I'm not entirely sure what was changed, to be honest:

![gogs_slack_fallback](https://cloud.githubusercontent.com/assets/20434/11603336/f224ff66-9ad8-11e5-9f1d-fe5431d8df0f.png)

I feel like there's a lot of superfluous information in what I get to see in IRC.

There are two very long lines containing:
* A link to the repo
* A link to the branch that received commits
* A full link for a diff of all pushed commits

And for each pushed commit, up to 5:
* My full name
* My email with a mailto link
* My nickname
* Another full diff link

That's a lot of stuff.

Instead, I'd really like to get just one line with a single:

    mkaito pushed 5 new commits to potato/master:  http://git.guildpad.com/haven/potato/compare/8317d2...4912bc

This would require gogs to accept a shortened SHA1 for the `/compare` URL, which would go a very long way to clean up the clutter.

Even if you decide you don't want to do shortened SHA1, cutting the payload to a single line with a single link would go a long way.

**Comment by Unknwon** [comment]
I'm not sure how really fallback works with Slack, but 

> mkaito pushed 5 new commits to potato/master:  FULL_COMPARE_URL

Is all Gogs puts into `fallback`.

**Comment by mkaito** [comment]
It's probably the attachments. I think you attach up to 5 commits? Maybe try setting the fallback for attachments to an empty string. It's not very well documented in that regard.

**Comment by Unknwon** [comment]
Attachment is only corresponding to a payload, and there is only one attachment in the payload... not sure how to improve that.. :sweat:

**Comment by mkaito** [comment]
Some testing seems to indicate that `fallback` only applies to attachments. That is... disappointing. I'll bring it up with the slack devs.

However, I've also found that setting `fallback` to an empty string for attachments means they won't be echoed for fallback clients. Please do that. The main text contains more than enough information. Hell, it still contains too much, but there's nothing we can do about that without a top-level `fallback` field.

**Comment by Unknwon** [comment]
> However, I've also found that setting fallback to an empty string for attachments means they won't be echoed for fallback clients

Pushed to `develop` branch.

**Comment by mkaito** [comment]
Just recompiled off `develop`, and this is the resulting payload:

```json
{
  "channel": "#general",
  "text": "[\u003chttp://git.onhaven.net/haven/potato|potato\u003e:\u003chttp://git.onhaven.net/haven/potato/src/master|master\u003e] \u003chttp://git.onhaven.net/haven/potato/compare/5efbfa8d08af9682d8516ae09903c2d74387a4d4...7d169742d4fd3e75bba03dd92b7bd4035a87070f|1 new commit\u003e pushed by Chris Hoeppner",
  "username": "Gogs",
  "icon_url": "",
  "unfurl_links": 0,
  "link_names": 0,
  "attachments": [
    {
      "fallback": "\u0026{Chris Hoeppner mkaito@onhaven.com mkaito} pushed 1 new commit to potato/master: http://git.onhaven.net/haven/potato/compare/5efbfa8d08af9682d8516ae09903c2d74387a4d4...7d169742d4fd3e75bba03dd92b7bd4035a87070f",
      "color": "",
      "text": "\u003chttp://git.onhaven.net/haven/potato/commit/7d169742d4fd3e75bba03dd92b7bd4035a87070f|7d16974\u003e: Bogus commit - Michishige Kaito"
    }
  ]
}
```

As you can see, the fallback field is not an empty string.

**Comment by Unknwon** [comment]
I think you're not sync with `develop` branch.

**Comment by mkaito** [comment]
```bash
~/dev/go/src/github.com/gogits/gogs develop
❯ git pull origin develop
From https://github.com/gogits/gogs
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
```

**Comment by mkaito** [comment]
I recompiled and pushed again to the server, just in case:

```json
{
  "channel": "#general",
  "text": "[\u003chttp://git.onhaven.net/haven/potato|potato\u003e:\u003chttp://git.onhaven.net/haven/potato/src/master|master\u003e] \u003chttp://git.onhaven.net/haven/potato/compare/7d169742d4fd3e75bba03dd92b7bd4035a87070f...3f1b59f883ad3082f203bb170eeca3a3613cb2a6|1 new commit\u003e pushed by Chris Hoeppner",
  "username": "Gogs",
  "icon_url": "",
  "unfurl_links": 0,
  "link_names": 0,
  "attachments": [
    {
      "fallback": "\u0026{Chris Hoeppner mkaito@onhaven.com mkaito} pushed 1 new commit to potato/master: http://git.onhaven.net/haven/potato/compare/7d169742d4fd3e75bba03dd92b7bd4035a87070f...3f1b59f883ad3082f203bb170eeca3a3613cb2a6",
      "color": "",
      "text": "\u003chttp://git.onhaven.net/haven/potato/commit/3f1b59f883ad3082f203bb170eeca3a3613cb2a6|3f1b59f\u003e: Bogus commit - Michishige Kaito"
    }
  ]
}
```

**Comment by Unknwon** [comment]
I'm pretty sure you're not sync or not use the newly compiled binary, because if I delete [this line](https://github.com/gogits/gogs/blob/master/models%2Fwebhook_slack.go#L36), no compile error.

**Comment by mkaito** [comment]
The newest commit on my end is 76d4b9288b60ed6c037257415a570225764ff0a0. That's where the github develop branch's HEAD is at, too. Not sure what I'd be missing, unless you had forgotten to push to github :stuck_out_tongue:

**Comment by Unknwon** [comment]
The only thing I can think of you executed the old binary...

**Comment by mkaito** [comment]
I accidentally did that before. The logs would complain about a version mismatch. Just in case, I've wiped the gogs folder and unpacked the zipfile again. Same result.

**Comment by Unknwon** [comment]
OK, I just pushed something for other issues, now the `develop` branch should have version `0.7.30.1204 Beta`, please make sure you test under this version.

**Comment by mkaito** [comment]
I can confirm that `Gogs Version: 0.7.29.1204 Beta` is shown in the site footer. Here's the resulting JSON payload:

```json
{
  "channel": "#general",
  "text": "[\u003chttp://git.onhaven.net/haven/potato|potato\u003e:\u003chttp://git.onhaven.net/haven/potato/src/master|master\u003e] \u003chttp://git.onhaven.net/haven/potato/compare/3f1b59f883ad3082f203bb170eeca3a3613cb2a6...0fb713b4679b410302196a83fce83638d068db7a|1 new commit\u003e pushed by Chris Hoeppner",
  "username": "Gogs",
  "icon_url": "",
  "unfurl_links": 0,
  "link_names": 0,
  "attachments": [
    {
      "fallback": "\u0026{Chris Hoeppner mkaito@onhaven.com mkaito} pushed 1 new commit to potato/master: http://git.onhaven.net/haven/potato/compare/3f1b59f883ad3082f203bb170eeca3a3613cb2a6...0fb713b4679b410302196a83fce83638d068db7a",
      "color": "",
      "text": "\u003chttp://git.onhaven.net/haven/potato/commit/0fb713b4679b410302196a83fce83638d068db7a|0fb713b\u003e: Bogus commit - Michishige Kaito"
    }
  ]
}
```

**Comment by Unknwon** [comment]
The version I posted is `0.7.30.1204`...

**Comment by mkaito** [comment]
Oh dear. Let me see if I can clean that up.

**Comment by Unknwon** [comment]
:sob:

**Comment by mkaito** [comment]
Seems I had to run `make clean` or things got jumbled up. Server is now running `Gogs Version: 0.7.30.1204`, and I finally get an empty `fallback` for attachments.

This is the best we can do until Slack adds a top-level `fallback` field. Thanks!

**Comment by Unknwon** [comment]
:tada: Fianlly.
