### ISSUE TITLE
Why pull request button not working

### ISSUE THREAD

**Issue by SimonSun1988** [gogits/gogs#2047]
I create a new branch and push to remote, but I can't create pull request

I have a lot of branches
![](http://i.imgur.com/H6QjPbv.png)

but I can't create pull request
![](http://i.imgur.com/MSkbj30.png)

**Comment by tboerger** [comment]
Currently you can not create pull requests within a single repository, you can create pull requests only from forks.

**Comment by SimonSun1988** [comment]
Now, I can create pull request after fork some repository.

But after I create this pull request. I can create pull request in the same repository lol.

**Comment by mkaito** [comment]
> Currently you can not create pull requests within a single repository, you can create pull requests only from forks.

Is this by design? I'd *really* like to have intra-repo PRs.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think the purpose is duplicated to https://github.com/gogits/gogs/issues/1597
