### ISSUE TITLE
Migrating repository doesn't migrate githooks

### ISSUE THREAD

**Issue by iamgroot42** [gogits/gogs#2048]

**Comment by Unknwon** [comment]
Gogs uses `git clone --mirror`, do you know any commands that migrates hooks?

**Comment by iamgroot42** [comment]
You're right : ```git clone ``` does not support cloning githooks  (unless they're moved to another folder). I guess a script to copy the hooks into the desired folder will work.

**Comment by Unknwon** [comment]
> I guess a script to copy the hooks into the desired folder will work.

I think it will not work when you clone through HTTPS, also, it creates security concerns because git hooks' execution can be very dangerous.

I'll keep this closed until stronger prove of how it should work.
