### ISSUE TITLE
Diff data too large

### ISSUE THREAD

**Issue by SoftCreatR** [gogits/gogs#2051]
I'm experiencing a strange bug. When opening a commit, it shows "Diff Data Not Available." and when checking the `gogs.log` it contains `[W] Diff data too large`

When checking with an external client (e.g. Github for Windows) i can see the full Diff.

**Comment by Unknwon** [comment]
Hi, please checkout this: https://gogs.io/docs/advanced/configuration_cheat_sheet#git-(git)

**Comment by SoftCreatR** [comment]
The strange thing is, that it just affects commits with many changed files, not all.

**Comment by SoftCreatR** [comment]
Added

```
[git]
MAX_GITDIFF_LINES = 3000000
```

and restarted gogs. No change.

**Comment by Unknwon** [comment]
Which file did you add those lines?

**Comment by SoftCreatR** [comment]
That did the trick, ty. However, this leads me to a feature request :D

**Comment by Unknwon** [comment]
> this leads me to a feature request

What is it...? :trollface:
