### ISSUE TITLE
Ability to batch delete system notices

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#2052]
I once mirrored a git repo from Github to my gogs server, and server weeks ago I deleted the source repo from Github, but forgot to delete the mirrored repo from gogs. So now there are 3 or 4 pages of system notices in the control panel of gogs. It would be nice if I could select a whole page of them and delete by one click.

**Comment by Unknwon** [comment]
I just pushed a commit which allow you empty all notices at once to `develop` branch.

Of course, if you want to delete by page, please say it and I'll implement it.

**Comment by JokerQyou** [comment]
Being able to empty all system notices is a good feature, but sometimes we do need to delete by page, or even delete only selected notices on the page. Because some notices are more important than others (system related issues v.s. network problems), and maybe we need to delete the less important notices before dig into the important ones. 

Of course, if this requires much effort to get implemented, you could consider put it in future milestone queue other than to do it now.

**Comment by Unknwon** [comment]
Working on it :D

**Comment by Unknwon** [comment]
LOL. Please try out `develop` branch now!

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/11606410/9a70e53a-9aee-11e5-90a9-f26009a11660.png)

**Comment by Unknwon** [comment]
@JokerQyou time for you to response :D

**Comment by JokerQyou** [comment]
UI looks good, but I haven't tried yet. I'm still `go get -u github.com/gogits/gogs`. :sob:

**Comment by Unknwon** [comment]
@JokerQyou Are you on gitter.im ? I can give you temporary admin access to demo site.
