### ISSUE TITLE
Internal SSH server only listen on ip6 port

### ISSUE THREAD

**Issue by fanningert** [gogits/gogs#2055]
I activated the internal SSH server on a custom port (`9922`). But the internal ssh server only listen on the ipv6 port. For the most clients it is not a problem. But some android clients have problems to find the host, when only ipv6 is active. And some clients don't support ipv6 at the current state.
The default SSH server (screenshot second netstat command) listen on ipv4 (`0.0.0.0:22`) and ipv6 (`:::22`). Gogs custom SSH server (first netstat command) only listen on ipv6 (`:::9922`).
![screenshot_2015-11-29_09-53-38](https://cloud.githubusercontent.com/assets/365219/11456162/464b3dde-967f-11e5-845c-db2b1b01e988.png)

Used Linux server OS: **Archlinux**

**Comment by Unknwon** [comment]
This is strange to me...

The code shows it is listening on `0.0.0.0:xxxx`: https://github.com/gogits/gogs/blob/master/modules%2Fssh%2Fssh.go#L111

**Comment by fanningert** [comment]
Ok, it is correct. Here the answer.
https://groups.google.com/forum/#!msg/golang-nuts/F5HE7Eqb6iM/q_um2VqT5vAJ
