### ISSUE TITLE
Web Interface Cannot Access After Docker Container Stop And Restart

### ISSUE THREAD

**Issue by fzx** [gogits/gogs#2056]
My script file is as follows:
```
docker stop gogs
docker rm gogs
docker run \
    --name=gogs \
    --restart unless-stopped \
    -d \
    -p 10080:3000 \
    -v ~/work/gogs:/data  \
    gogs/gogs
```
After start the container, I fill the install page(use sqlite) and then login. Then I run the above script file again, the web page cannot access anymore.

**Comment by Unknwon** [comment]
> the web page cannot access anymore.

I suppose your Docker container config is changed.

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
