### ISSUE TITLE
Wrong URL path in markdown previewing

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#2057]
I installed gogs in a sub path, let's say `https://a.com/b/`. When I edit an issue comment, activating the preview panel will trigger a request to `https://a.com/api/v1/markdown`. which is wrong.

**Comment by fanningert** [comment]
What proxy server did you using (nginx, apache, ...)?

**Comment by fanningert** [comment]
Here are my `Nginx` config variant. My proxy is a `https -> http` proxy. And nginx run on the same machine like gogs. So gogs can run without `https`, but it is only accessible on the machine (127.0.0.1 or localhost).

```
server {
  ...
  location /gogs/ {
    proxy_pass          http://localhost:3000/;
  }
  ...
}
```

and in the gogs config file. (`{gogs-install}/config/app.ini`)
```
[server]
PROTOCOL = http
DOMAIN = a.com
ROOT_URL = https://a.com/b/
```

**Comment by JokerQyou** [comment]
I am using the exact config and proxy as yours.

**Comment by JokerQyou** [comment]
This only happens if I try to preview the content when I'm **editing an existing comment** of an issue. When I preview the content of a new comment, it is okay.

**Comment by Unknwon** [comment]
What is your version of Gogs and can you reproduce on https://try.gogs.io?

**Comment by JokerQyou** [comment]
I'm using gogs version ` 0.7.22.1125 Beta`. Of course I cannot reproduce on gogs demo site, because this only happens on gog servers installed in sub path.

**Comment by Unknwon** [comment]
@JokerQyou You're right, keep forgetting that... :sweat:

**Comment by Unknwon** [comment]
I pushed fix to `develop` branch, can you help test again?

**Comment by JokerQyou** [comment]
Sorry for late reply, I was kind of busy. I have not yet setup Golang environment on my server (or maybe I have, but I forget how to use it...), so I'm currently not able to test from source code.
Do you provide nightly binary build? If not, I'll see if I get time to setup the environment.

**Comment by Unknwon** [comment]
@JokerQyou currently, no, but should have soon https://github.com/gogits/gogs/pull/2010
