### ISSUE TITLE
Upgrading to v0.7.22

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#2061]
Hi,
Do i need to do anything special when i upgrade from v0.7.19 to v0.7.22. is there a link or?. Either i don't know where to look?Or no information exists? I am on windows and not able to start gogs after upgrade, and i can see this in the log 'Unknown database type: sqlite3??

The settings is:

[database]
DB_TYPE = sqlite3
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = 
SSL_MODE = disable
PATH = data/gogs.db

**Comment by Unknwon** [comment]
> Unknown database type: sqlite3??

Hi, please see https://gogs.io/docs/installation/install_from_source#build-with-tags

**Comment by renewsorensen** [comment]
Hi
Just to be clear, because it is not obvious to me, on Windows from version 0.7.22, i need to build gogs my self and with sqlite3 support?

**Comment by Unknwon** [comment]
> Just to be clear, because it is not obvious to me, on Windows from version 0.7.22,

It's not clear to how did you upgrade as well.

**Comment by renewsorensen** [comment]
I used the guide, https://gogs.io/docs/installation/install_from_binary
Download latest binary release ZIP archive.
Remove old templates directory.
Extract archive and copy-paste everything to corresponding (old) location.

**Comment by Unknwon** [comment]
@renewsorensen Does the start prompt shows that `SQLite3 supported`?

**Comment by renewsorensen** [comment]
Hi
I will check that when i get to work in a few hours, and reporter back to you. But i recall that it is written to the logs as well, and i notics yesteday that sqlite3 was missing, so my conclusion was that i nust build it my self with sqlite3 support from now on. I will still check thoug ☺

**Comment by Unknwon** [comment]
@renewsorensen no problem. If you're using 386, you have to build yourself for SQLite3 support.

**Comment by renewsorensen** [comment]
Ohh ☺ and i use amd64 is sqlite3 supported out og the box?

**Comment by Unknwon** [comment]
Yes, it's supposed to.

**Comment by renewsorensen** [comment]
Thanks for that, i picked the wrong linke yesteday when i downloadede gogs (386). Thanks for the Intel on that 😀
