### ISSUE TITLE
Ability to delete repo from admin panel

### ISSUE THREAD

**Issue by ipfans** [gogits/gogs#2063]
If repo have a error like #714 the repo main page will get 500 error.

But that means I can not delete this repo from repo main page. And administrator can not delete repo from admin panel.

**Comment by Depado** [comment]
A quick fix for now is to hit directly on the settings page of the repo instead of accessing the main repo page. But I agree, admin user(s) should be able to delete a repository from any user in case something goes wrong.

**Comment by Unknwon** [comment]
Please try out `develop` branch!

**Comment by Unknwon** [comment]
Close as implemented.
