### ISSUE TITLE
Builtin SSH Server activated => Web Server not started

### ISSUE THREAD

**Issue by MrFloppy** [gogits/gogs#2065]
Hi guys,

Thank you for gogs at first. I just tried to use the builtin SSH server.
As soon as it is active in my custom conf, the web server stops working.

The logs when the SSH server is inactive:
```
2015/11/30 20:21:51 [I] Log Mode: File(Info)
2015/11/30 20:21:51 [I] Cache Service Enabled
2015/11/30 20:21:51 [I] Session Service Enabled
2015/11/30 20:21:51 [I] Mail Service Enabled
2015/11/30 20:21:51 [I] Notify Mail Service Enabled
2015/11/30 20:21:51 [I] Git Version: 2.1.0
2015/11/30 20:21:52 [I] Run Mode: Production
2015/11/30 20:21:52 [I] Listen: http://localhost:6000
```

As soon as the SSH server is active:
```
2015/11/30 20:23:33 [I] Log Mode: File(Info)
2015/11/30 20:23:33 [I] Cache Service Enabled
2015/11/30 20:23:33 [I] Session Service Enabled
2015/11/30 20:23:33 [I] Mail Service Enabled
2015/11/30 20:23:33 [I] Notify Mail Service Enabled
2015/11/30 20:23:33 [I] Git Version: 2.1.0
2015/11/30 20:23:34 [I] Run Mode: Production
2015/11/30 20:23:34 [I] SSH server started on :22
```

This is repeated eleven times inside the log.

Here is the part of my config:
```
HTTP_ADDR = localhost
HTTP_PORT = 6000
; Disable SSH feature when not available
DISABLE_SSH = false
START_SSH_SERVER = true
SSH_PORT = 22
```

I also tried a different port. No change.

Can you help me?

**Comment by fanningert** [comment]
Did run any other SSH server on port 22 on your machine (On most linux system is this). Change the SSH_PORT to a different port. Example: `9922`
Beware in the current `master` branch and release `0.7.22` is a bug (#1681) with the internal ssh server. It's corrected with the commit 9950f5a in the `develop` branch.

**Comment by Unknwon** [comment]
ping @MrFloppy

**Comment by MrFloppy** [comment]
I already changed the port. My SSH server is running on another port. On port 22 is nothing to connect to. 
Is there an ubuntu package for the master branch? I am currently using the .deb file to have gogs on my server.

**Comment by Unknwon** [comment]
No... I think you would have yo build yourself for `develop` branch...

**Comment by MrFloppy** [comment]
Okay. I guess that issue is solved then. I will close it until 0.8.0 is out and test again. If the problem still occurs I will let you know!

**Comment by Unknwon** [comment]
Sure!

**Comment by andryyy** [comment]
Just ran into it today. You cannot spawn ports <1024 with an unprivileged user. You would need to start it on 2222 etc. and nat' it to 22. :)
