### ISSUE TITLE
Make UI use pure Semantic UI as much as possible

### ISSUE THREAD

**Issue by nanoant** [gogits/gogs#2066]
Long story short it is about using pure Semantic UI constructs where possible across whole HTML code. I found quite many places Gogs uses own CSS approach, where Semantic UI could be used. This leads to UI L&F inconsistencies, and also can cause many problem if we will be considering usage of alternative Semantic UI themes.

Here's a WIP TODO list:

- [ ] Use pure SUI label colors - #2033
- [x] Use pure SUI tables layout - #2064

**Comment by Unknwon** [comment]
What is the status of this issue now?

**Comment by nanoant** [comment]
@Unknwon I have partially addressed it, but still there are couple of places that use some custom CSS where Semantic UI have stuff that provide desired behavior, eg. hard coded `box-shadow` for Admin `segments` in `_admin.less`. You can have same behavior simply wrapping segment groups into `ui segments` divs.

I'll get back to this subject soon revising all these places.
