### ISSUE TITLE
Diff is not showing full content when has super long one line

### ISSUE THREAD

**Issue by dabaer** [gogits/gogs#2071]
Gogs does not show the entirety of commits, when compared to the command line diffstat.

https://github.com/dabaer/Test - Shows the full content, but when viewed in gogs shows an incorrect diffstat

**Comment by Unknwon** [comment]
OK, now on `develop` branch, this should be fixed.

Quite a deep hidden bug, thanks for your report!

Test online: https://try.gogs.io/unknwon/Issue-2071/commit/ac30d3aa6af19bdfcefe3140f6ea9cc1239b4214

**Comment by dabaer** [comment]
Ah good catch - I assume you mean the minified normalize in app.css?

**Comment by Unknwon** [comment]
@dabaer yes, somehow the old approach stops parsing when meet this minified super long line.

So I use another way to parse the diff data now.

**Comment by Unknwon** [comment]
Close as fixed.
