### ISSUE TITLE
Standard exportable format for issue tracker data

### ISSUE THREAD

**Issue by 5paceManSpiff** [gogits/gogs#2072]
This would easily allow administrator backups and command line management of issue tracker data associated with repositories.

**Comment by Unknwon** [comment]
Thanks, it is a cool idea, but how and why?

**Comment by 5paceManSpiff** [comment]
Well I got the idea after watching [this Eric S. Raymon talk (from 2009 omg how does this issue still exist)](https://www.youtube.com/watch?v=_BgRBjQOnJU) where he describes the painful loss of data he experienced after a centralized cvs/issue tracker/mailing list host went down.  He was able to find backups of various source revisions and mirrored archives of the mailing list, but was not able to recover the issue tracker data.  He noted that most revision control web portals that include issue trackers only store the data internally on some sort of SQL database.

This prevents users from accessing the revision history of issues directly, a property which could be used to view issues when offline, perform manual commits and pushes, and allow for easy export and import of issue tracker data into other open source software.  As someone who has started using gogs as an alternative source portal on my own servers, I feel that these benefits are in line with the goals of the gogs project, to be the easiest to setup, run, and use.  It's about time issue trackers start embracing an offline first workflow.

This feature could be implemented by storing issues and comments as markdown files with [YAML frontmatter](http://jekyllrb.com/docs/frontmatter/) metadata describing the author, time created, open status, tags, and time last modified.  Each file would be named after a hash of the initial metadata, providing a unique id for each entry to reference eachother by.  Comment files will additionaly include the id of the issue file and the id of the previous comment.  Issue files will include a the id of the newest comment. The git repository file tree might look something like this.

```
├── comments
│   ├── 06198e758d64e7646ed1f9db0acbb1255f11053fb0c0ad6859ccd23a26f55624
│   └── 85b4f9c9a8e480fd2c9655622c646e13a103157d88c477b0f22ec918fe0dd1ea 
└── issues
    └── 39d2cf562c8911d0ea931fdf2d126a81ab877db12e8ada53162055fb4f56292b
```

Here we have one issue file with the id (in this case `sha256sum`) of `39d2cf562c8911d0ea931fdf2d126a81ab877db12e8ada53162055fb4f56292b`.  This file contains the following.

```
---
title: Should this feature be implemented?
author: 5paceManSpiff
created: Tue Dec 01 2015 15:29:42 GMT-0500 (EST)
modified: Tue Dec 01 2015 15:41:49 GMT-0500 (EST)
status: open
tags: feature
newest: 06198e758d64e7646ed1f9db0acbb1255f11053fb0c0ad6859ccd23a26f55624
---

Yo do you think we should implement this feature?
```

It contains all requisite issue data along with the id of the newest comment, `06198e758d64e7646ed1f9db0acbb1255f11053fb0c0ad6859ccd23a26f55624`.  If we take a look at this file it contains the following.

```
---
author: 5paceManSpiff
created: Tue Dec 01 2015 15:41:49 GMT-0500 (EST)
modified: Tue Dec 01 2015 15:41:49 GMT-0500 (EST)
issue: 39d2cf562c8911d0ea931fdf2d126a81ab877db12e8ada53162055fb4f56292b
previous: 85b4f9c9a8e480fd2c9655622c646e13a103157d88c477b0f22ec918fe0dd1ea
---

Yeah true too much work :P.
```

This contains all requisite comment data as well as the id of the previous comment, `85b4f9c9a8e480fd2c9655622c646e13a103157d88c477b0f22ec918fe0dd1ea`.

Using this structure gogs could manage flatfile version controlled records of the issue tracker through the issue tracker interface, as well as through direct git pushes.

**Comment by 5paceManSpiff** [comment]
[I've uploaded my example repository to my github profile.](/5paceManSpiff/flatfile-issue-tracker)

**Comment by Unknwon** [comment]
Just wonder why not just dump the database?

**Comment by 5paceManSpiff** [comment]
Plain text markdown files are easier to manually edit and parse than database dumps.  Dumping the database would certainly be the easiest way to implement issue tracker backups, but would make interoperability between other git management systems more difficult.  I don't think it makes sense to create an offline backup of a repository that requires importing into a database or into gogs itself.  Flat files would allow users to query individual issues and comments without the need for a database.

**Comment by 5paceManSpiff** [comment]
@nanoant what do you think about this?  I think this has implications for #2070.

**Comment by Unknwon** [comment]
It sounds more like export issue data other than backup.

**Comment by nanoant** [comment]
@5paceManSpiff Honestly I've seen many solutions that tried to use Git repo for storing issues, but none were widely adapted. Most didn't went out of prototype. Such approach may be good for command line users, but IMHO Web interface is just much convenient. My personal preference is *sqlite* database for single node server. This can be easily backed up, transferred etc. etc.

Also such solution would require dropping completely (X)ORM approach or writing own Git based ORM. Both would require serious amount of coding and time.

**Comment by 5paceManSpiff** [comment]
I'm considering writing my own Git based ORM library with an included cli client.  Given the relative stability of that effort I'll attempt integrating it into gogs.

**Comment by nanoant** [comment]
@5paceManSpiff still I don't see how this new ORM library can work along with existing XORM using same relational DB paradigm. If you will be wanting to use relation paradigm for Git ORM you effectively will be emulating relational DB on Git which will get you not really good outcome. If you will create Git ORM using Git's own versioned objects, trees, commits with SHA1 paradigm you will need to rewrite most of Gogs code using the relational paradigm.

**Comment by Unknwon** [comment]
After reading @nanoant 's comment, I think I misunderstand the purpose of this issue.

If the case it use text file other than database to manage issue and comments, no, it's not going to happen with Gogs.

**Comment by 5paceManSpiff** [comment]
@nanoant It can't work directly with the existing XORM but can work along side it.  I'm proposing that the code used to store issue tracking be replaced with a library that creates and updates versioned flat files in an attempt to change the paradigm of git source portals storing issue tracking data in the same way websites store data.  Issue tracking data should not be linked to any one particular git host, and I believe that designing some sort of way of managing them in plain text would allow maximum interoperability between competing distrobutions.

The purpose of the issue is to suggest an alternative format for issue tracking that does not depend on the existence or nonexistence of specific database layers, but rather can be parsed using a single spec implemented across all git hosts.

**Comment by 5paceManSpiff** [comment]
I'm going to rename the title accordingly.

**Comment by de-vri-es** [comment]
@SpaceManSpiff: Do you think that #2210 would address the underlying problem to your issue?

**Comment by Unknwon** [comment]
On `release/0.11`, after `./gogs backup ....`, you will get JSON format everything from DB.
