### ISSUE TITLE
non Org Member could clone Org Repo

### ISSUE THREAD

**Issue by MorphBonehunter** [gogits/gogs#2074]
Hi @all,
i'm new to gogs and i try a few things the last days.
What i realize is, that it is possible to clone an organisation repository for everyone who has an account on gogs.

Steps to reproduce:
1. create an organisation
2. create an organisation repository and remember the clone url 
3. create an new user and leave it as it is
4. git clone the repository from Step 2 -> it works

I don't think this should be possible or did i misunderstand something?
In my eyes this is an security relevant issue as it also happens if you kick someone out of an organisation. After that for the user it is still possible to track the progress in the organisational repositorys.

**Comment by MorphBonehunter** [comment]
as an addition: this does not work with private repositorys, there i got an "Authentication failed"

**Comment by MorphBonehunter** [comment]
sorry, push the wrong button :(

**Comment by sapk** [comment]
It's normal since by default the repo is public so a non-org user could clone and pull but not push the (public) repo. Therefor if you put it in a private only org members can see it and clone/pull/push in it.

**Comment by Unknwon** [comment]
Hi,

> What i realize is, that it is possible to clone an organisation repository for everyone who has an account on gogs.

This is the design and definition of a public repository.

**Comment by MorphBonehunter** [comment]
Ok, so i definitively misunderstand this. Sorry, case closed.

**Comment by Unknwon** [comment]
:trollface:
