### ISSUE TITLE
Meet 500 error when creating repo

### ISSUE THREAD

**Issue by geekpi** [gogits/gogs#2075]
Gogs version: 0.7.22.1125 Beta 
Go version: 1.5
backend: mysql  Ver 14.14 Distrib 5.5.35, for Linux (x86_64) using readline 5.1

==> /var/log/gogs/gogs.log <==
2015/12/01 17:14:33 [...routers/repo/repo.go:92 handleCreateError()] [E] CreatePost: Error 1210: Incorrect arguments to mysqld_stmt_execute

==> /var/log/gogs/web-1.log <==
2015/12/01 17:14:33 [...routers/repo/repo.go:92 handleCreateError()] [E] CreatePost: Error 1210: Incorrect arguments to mysqld_stmt_execute

**Comment by Unknwon** [comment]
Thanks your feedback! 

It seems either a database driver bug or MySQL bug, please see:

1. http://stackoverflow.com/questions/10053955/mysqli-bind-param-giving-error-1210-incorrect-arguments-to-mysql-stmt-execute
2. https://github.com/go-sql-driver/mysql/issues/374

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.

**Comment by javydreamercsw** [comment]
I'm seeing this on version 0.9.97.0901as well. Will post logs in a bit. Should I continue here or open a new issue?

**Comment by javydreamercsw** [comment]
Different error:

2016/10/21 10:22:14 [...routers/repo/http.go:118 HTTP()] [E] invalid token
2016/10/21 10:22:27 [...routers/repo/http.go:118 HTTP()] [E] invalid token
2016/10/21 14:33:38 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: InitRepository: chdir /home/git/gogs-repositories/synamicd/ring_veteran_server.git: no such file or directory
2016/10/21 14:33:43 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: InitRepository: chdir /home/git/gogs-repositories/synamicd/ring_veteran_server.git: no such file or directory
2016/10/21 14:34:21 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: InitRepository: chdir /home/git/gogs-repositories/synamicd/ring-veteran-server.git: no such file or directory
2016/10/21 14:34:26 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: InitRepository: chdir /home/git/gogs-repositories/synamicd/ring-veteran-server.git: no such file or directory
2016/10/21 14:34:31 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: InitRepository: chdir /home/git/gogs-repositories/synamicd/ring-veteran-server.git: no such file or directory
2016/10/21 14:34:36 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: InitRepository: chdir /home/git/gogs-repositories/synamicd/ring-veteran-server.git: no such file or directory
