### ISSUE TITLE
Dashboard history incorrect after rebase

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2082]
Take the following as a sample scenario.
- I have a repo with eight separate commits;
- after each commit I have done a separate push.

In my dashboard history, I now see eight entries with each of them containing one single commit. This is correct. 

Now I want to reword my last two commit messages and do so by using the rebase command: `git rebase -i HEAD~2` and do a force push `git push -f`.

This will add one entry in the dashboard, and in my case the last five commits being shown. I would expect that only the last two commits are shown, that are the ones that I modified.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
A possible pointer for who wants to help on this: https://github.com/gogits/gogs/blob/master/models%2Fupdate.go#L124

Be sure to claim first to prevent two people work on same thing. :wave:

**Comment by Unknwon** [comment]
Please notify when this happens again.
