### ISSUE TITLE
data

### ISSUE THREAD

**Issue by googlaev** [gogits/gogs#2083]
You do not see the date pravelno commit.
![error](https://cloud.githubusercontent.com/assets/8578823/11530915/68450922-991a-11e5-8341-9aebfeb0034a.png)

**Comment by googlaev** [comment]
As the date of the creation of a bug .

![errror1](https://cloud.githubusercontent.com/assets/8578823/11531264/6293e446-991d-11e5-8df4-78e2349fa3a7.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

You can help fix it with [this guide](https://gogs.io/docs/features/i18n)

**Comment by Unknwon** [comment]
Which language are you using?

**Comment by Unknwon** [comment]
Should be fixed in `master` and you can try on https://try.gogs.io

**Comment by googlaev** [comment]
I am very interested in your projects sometimes try to look testit contribute. I am Russian. And are interested in the Russian language localization . Since gogs interesting project .

**Comment by Unknwon** [comment]
:trollface:

**Comment by Unknwon** [comment]
You can help translation Russian on https://crowdin.com/project/gogs

**Comment by googlaev** [comment]
I'll try to do my best !!!

**Comment by googlaev** [comment]
And your lecture on golang available in English ???

**Comment by Unknwon** [comment]
No..
