### ISSUE TITLE
wrong date

### ISSUE THREAD

**Issue by BurakDev** [gogits/gogs#2084]
![gogserror](https://cloud.githubusercontent.com/assets/3963184/11535382/f4fb0b2a-9913-11e5-910a-6d93d682f408.png)

Still have this issue, running version 0.7.22.1125

**Comment by BurakDev** [comment]
Related to #1500

**Comment by Unknwon** [comment]
Thanks your feedback!

When you say `wrong date`, what is the right date?

**Comment by Gibheer** [comment]
@Unknwon the screenshot says "2 weeks from now", not 2 weeks ago.

@BurakDev did you check the time on the server and the timestamp of the commits? Which timezone is the server using?

**Comment by Unknwon** [comment]
@Gibheer Oh, thanks. I see, but still... the time in tooltip looks reasonable to me, so still need comparison.

**Comment by MorphBonehunter** [comment]
Maybe some helpful note: i also had wrong date (always show UTC, but i'm on CET) on the webui but right on the server an in the logs.
As i use gogs on Arch Linux, there ist no /etc/timezone as the system not use this file.
I could fix the behavior by create the /etc/timezone file and insert "Europe/Berlin" in it.
Maybe this gives an hint what could be wrong with the date stuff?

**Comment by Unknwon** [comment]
@MorphBonehunter MySQL does not store timezone info for date, and the way Go convert time to local somehow depends on `/etc/timezone`... so... I don't know what to say next :sweat_smile:

@BurakDev can you try @MorphBonehunter 's solution?

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.

**Comment by BurakDev** [comment]
I changed timezone, last commits are 2 days ago but still show 2 weeks ago..

https://i.gyazo.com/9e5335f6347e8752c782fabcb3ca4729.png

**Comment by linquize** [comment]
Relate to system date format?

**Comment by BurakDev** [comment]
https://i.gyazo.com/8293c95da9f4c62bf682461153e54250.png

On dashboard is okay.

But on project main page/commits page still show "2 weeks ago".

https://i.gyazo.com/b745578190769dc91475aacfc864ef22.png
https://i.gyazo.com/297b552151f82740c56c2d57fb3f7c9a.png

Gogs version : 0.8.10, database engine : SQLite3

ping @Unknwon

**Comment by Unknwon** [comment]
Hi @BurakDev , what is the datetime you expect and what is show on the small black tooltip?

**Comment by BurakDev** [comment]
Tue, 22 Dec 2015 11:06:13 EST

If I commited a hour ago, why still show 2 weeks from now ?

On my private gogs I don't have this problem

**Comment by Unknwon** [comment]
I am confused by your last sentence, so you can reproduce on demo site?

**Comment by BurakDev** [comment]
https://i.gyazo.com/9a0c22b9a65c4237386efb2affc19f38.png

You don't see the problem ?

**Comment by BurakDev** [comment]
https://i.gyazo.com/0e48630c7862f95d01ab317ac170b8c2.png

Same repository (mirrored) on my second gogs (first is my work).

First use SQLite3, second use MySQL

**Comment by Unknwon** [comment]
Thanks.

Are two Gogs instances on the same machine?

**Comment by BurakDev** [comment]
No it isn't

**Comment by Unknwon** [comment]
OK, then I think it still could be problem of machine time zone or other settings.

**Comment by rugk** [comment]
BTW a correct time is very important for https://github.com/gogits/gogs/issues/945

**Comment by bkcsoft** [comment]
@rugk 2FA only need the server to have a correct timezone, this seems to be a UI-bug only.
