### ISSUE TITLE
rename repository broken

### ISSUE THREAD

**Issue by niphor** [gogits/gogs#2090]
只有硬盘上的目录重命名了
数据库没更新

原URL 报500
旧URL 报404

only folder on fs renamed
database not updated

old url : ERROR 500
new url : ERROR 404

**Comment by Unknwon** [comment]
Thanks your feedback! 

I've pushed fix to `master`, please help test again!

**Comment by niphor** [comment]
fixed 可以了

**Comment by Unknwon** [comment]
Thanks your confirmation!

**Comment by rzshuo** [comment]
0.12.3  也是这个问题！
