### ISSUE TITLE
Migrate from gitweb?

### ISSUE THREAD

**Issue by lucaspiller** [gogits/gogs#2091]
Is there an easy way to migrate from gitweb? I was hoping it would work magically by creating an organisation and symlinking `repos/org/` to `/opt/git`, but it didn't. We have over 100 repos so I don't really want to have to import everything manually :)

**Comment by lunny** [comment]
You can find Gogs api and write some scripts to import external git repositories to Gogs.

**Comment by Unknwon** [comment]
@lucaspiller Current `master` APIs already allows admin to migrate repository for any user, you can try it. 

 https://github.com/gogits/go-gogs-client/wiki/Repositories#migrate

In your case, you can migrate by local path.

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
