### ISSUE TITLE
Error 500 when create pull request on Windows

### ISSUE THREAD

**Issue by bouffa** [gogits/gogs#2093]
I got error 500 when trying to do a pull request on a fresh install of gogs (built out of sources as of december 3rd). In the log file, I found this error :

    2015/12/03 13:27:28 [...routers/repo/pull.go:632 CompareAndPullRequestPost()] [E] NewPullRequest: SavePatch: WriteFile: open MY_REPO_DIR\pulls\1.patch: The system cannot find the path specified.

Where MY_REPO_DIR is the folder of the repository. I found out that the subfolder **pulls** does not exists. I created it manually, and since then pull requests works.

**Comment by Unknwon** [comment]
Please see https://github.com/gogits/gogs/blob/master/CONTRIBUTING.md#bug-report

**Comment by bouffa** [comment]
Yes I'm using Windows, and the problem is now fixed.
Thanks,

**Comment by Unknwon** [comment]
@bouffa thanks your confirmation!
