### ISSUE TITLE
Empty commit amount bubble

### ISSUE THREAD

**Issue by lukasdietrich** [gogits/gogs#2095]
Version: 0.7.28.1203
When you are on the issue details page, the bubble for the amount of commits is empty:

![image](https://cloud.githubusercontent.com/assets/1913775/11561935/fafc76b4-99ca-11e5-8131-f398c38a1c93.png)

**Comment by Unknwon** [comment]
Hi, I've pushed fix to `master`, you can also test on https://try.gogs.io/gogs/gogs/issues/31

**Comment by lukasdietrich** [comment]
Thanks :smiley:

**Comment by Unknwon** [comment]
:octocat:
