### ISSUE TITLE
Install page after apt-get upgrade

### ISSUE THREAD

**Issue by mijndert** [gogits/gogs#2096]
I installed Gogs with the packager.io packages. There was a new version available so I did 'apt-get upgrade'.

0.7.22-1448564961.aaa3f1b.trusty => 0.7.22-1449149590.37a372f.trusty

After the upgrade the install page came up again and my admin settings were gone.

**Comment by mijndert** [comment]
/etc/gogs/conf/app.ini seems to be filled with the defaults, not the database settings, etc.

Where does Gogs save its credentials? 
It seems like every time I restart Gogs I should do the install thing again.

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/1897
