### ISSUE TITLE
webhooks not called

### ISSUE THREAD

**Issue by mikecar** [gogits/gogs#2099]
running © 2015 Gogs Version: 0.7.22.1125 Beta
I define a webhook, which never gets called, log shows nothing, apache access.log shows nothing.
calling url via wget works. 
pushing via ssh.

**Comment by Unknwon** [comment]
Hi, please check `path/to/gogs/log/serv.log` see if any errors there.

**Comment by mikecar** [comment]
yes. here it is:
root@dev2:/home/git/gogs/log# cat serv.log
2015/12/05 20:00:46 [T] No update task is presented: 11533a84-c57e-41ea-a86a-b7b857b89219
2015/12/05 20:11:42 [T] No update task is presented: 65bd0ba8-c24f-41dc-af39-9193a89d48ce

**Comment by Unknwon** [comment]
Try following thing in the admin dashboard and test again:

![image](https://cloud.githubusercontent.com/assets/2946214/11609344/55d33fc2-9b52-11e5-963b-b3f80a8753fa.png)

**Comment by mikecar** [comment]
yep, this fixed it.
btw, I have another issue :
it seems gogs listens on port 8888 as well as 3000. is there any way to disable this, as it clashes with one of my apps ?

finally: excellent work!

**Comment by Unknwon** [comment]
No, Gogs does not listen on `8888`.

**Comment by Unknwon** [comment]
:sailboat:

**Comment by mikecar** [comment]
Look at this :

netstat -tanp|grep gogs
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      1049/gogs
tcp        0      0 10.90.0.9:43218         10.90.0.5:3306          ESTABLISHED 1049/gogs
tcp        0      0 10.90.0.9:43216         10.90.0.5:3306          ESTABLISHED 1049/gogs
tcp6       0      0 :::3000                 :::*                    LISTEN      1049/gogs
tcp6       0      0 127.0.0.1:3000          127.0.0.1:45974         ESTABLISHED 1049/gogs
root@dev2:~#

**Comment by Unknwon** [comment]
You need find prove of code that listens on second port in Gogs, otherwise, it can be anything that relates to system.

Output from my CentOS 7 (https://try.gogs.io) of exact same command:

```sh
15:48:51 # netstat -tanp|grep gogs
tcp        0      0 127.0.0.1:51290         127.0.0.1:3306          ESTABLISHED 9361/gogs
tcp        0      0 127.0.0.1:51295         127.0.0.1:3306          ESTABLISHED 9361/gogs
tcp6       0      0 :::3001                 :::*                    LISTEN      9361/gogs
tcp6       0      0 ::1:3001                ::1:42101               ESTABLISHED 9361/gogs
tcp6       0      0 ::1:3001                ::1:42099               ESTABLISHED 9361/gogs
```

**Comment by mikecar** [comment]
Well, this is strange, I definitely see 8888 associated with gogs. Can you suggest how I should debug this ?

**Comment by Unknwon** [comment]
Did you use builtin SSH server?

If not, try `curl http://localhost:8888` and look at Gogs's log, see if anything comes up.

**Comment by mikecar** [comment]
Intersting. I tried this, nothing came up in the logs. I then tried this:

root@dev2:/home/git/gogs/log# telnet localhost 8888
Trying 127.0.0.1...
Connected to dev2.singularlogic.eu.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sat, 05 Dec 2015 23:49:34 GMT
Content-Length: 19

404 page not found

So something is listening on 8888, and understands http protocol, and linux says it is gogs…
What to do ?

**Comment by Unknwon** [comment]
The only result I search `8888` and get this: https://github.com/gogits/gogs/blob/3460ec103902a53430ec6efb345dfb827af70468/public/config.codekit#L683

But this is a codekit config file, unless your system understands it?

**Comment by mikecar** [comment]
I don’t even know what that is!
My system is a vanilla Ubuntu 14.04.
Weirder and weirder…
I am running the ready-made binary. Maybe if I try to compile locally ? can you give me some tips on how to do this?

**Comment by Unknwon** [comment]
See https://gogs.io/docs/installation/install_from_source

**Comment by Unknwon** [comment]
You may need cross-compile http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

**Comment by mikecar** [comment]
I installed the version from packager.io for Ubuntu, and this does NOT do the 8888 thing!
Therefore, I conclude that the binary package I used before is damaged/Trojan or what.

I got it from https://dl.gogs.io/gogs_v0.7.22_linux_amd64.tar.gz

You may want to check this out….

**Comment by Unknwon** [comment]
Haha, good to know!

PS: I use Ubuntu 14.04 compiled the binary package.
