### ISSUE TITLE
API support?

### ISSUE THREAD

**Issue by ChubbyNinja** [gogits/gogs#2100]
Does gogs have an API? I would like to be able to do things like

- Create a release
- Create/list/close issues
- Comment on issues

The reason for this is: When i do updates to a website and sync from beta to live, I do a file-modified comparison and overwrite those files, It would be handy if at that time, I could also tick what issues are fixed in this sync, as that would allow me to create a release and close the issues too (automagically).

I realize this is quite a specific case - but it may also have benefits for other people to be able to do things with the API.

**Comment by fanningert** [comment]
When it is the same like GitHub. You can add the issue number in to the commit message. So the commit should be linked with the issue.
```
git commit -m "#2100 comment"
```

**Comment by ChubbyNinja** [comment]
Thanks for the speedy reply - sure, I do this now

But i have written an integration script which compares my beta and live files, i would like to extend it to automatically close issues that i select - and create a new release of that code for the release tab

**Comment by hhenkel** [comment]
There is an basic API (https://github.com/gogits/gogs/tree/develop/routers/api/v1) and there is also currently a pr pending (#2039) to add more features.

**Comment by Unknwon** [comment]
Thanks your feedback!

And @fanningert @hhenkel , but I think this is basically duplicated to https://github.com/gogits/gogs/issues/1692 , please follow on that one.
