### ISSUE TITLE
Send SSH address along with webhook data

### ISSUE THREAD

**Issue by letorbi** [gogits/gogs#2105]
I want to use a webhook to call a script, which uses a deploy key to get read-only access to the repository. As far as I understand deploy keys only work with SSH pulls, but there is no direct way to get the SSH address of a repository from the data sent along with the webhook.

I suggest an additional field `ssh` in the `repository` section, which contains the SSH address of the repository:

    [...]
    "repository": {
      "id": 140,
      "name": "gogs",
      "url": "https://try.gogs.io/gogs/gogs",
      "ssh": "gogs@try.gogs.io:gogs/gogs",
      "description": "Gogs(Go Git Service) is a painless self-hosted Git Service written in Go.",
      "website": "",
      "watchers": 6,
      "owner": {
        "name": "gogs",
        "email": "u@gogs.io",
        "username": "gogs"
      },
      "private": false
    },
    [...]

**Comment by Unknwon** [comment]
Just pushed a commit to `develop`, you can also test on https://try.gogs.io

**Comment by letorbi** [comment]
Thanks for the fast fix.

**Comment by Unknwon** [comment]
Thanks your confirmation!
