### ISSUE TITLE
Update hooks use incorrect path

### ISSUE THREAD

**Issue by nioc** [gogits/gogs#2107]
Hello,

I installed from binary (version 0.7.22.1125 Beta) in this folder : `/usr/local/bin/gogs/` and when I pushed commit, I had an error message.
I fixed it by updating the path in the default update hook (`/myuser/myrepo/hooks/update`)
```bash
#!/usr/bin/env bash
#"/home/git/go/src/github.com/gogits/gogs/gogs" update $1 $2 $3 --config='/home/git/go/src/github.com/gogits/gogs/custom/conf/app.ini'
"/usr/local/bin/gogs/gogs" update $1 $2 $3 --config='/usr/local/bin/gogs/custom/conf/app.ini'
```

When I try to figure out why this default hook uses this path, I found a reference in the [scripts/supervisor/gogs]
(https://github.com/gogits/gogs/blob/master/scripts/supervisor/gogs)

When the user installs, this file should be set with the current installation path?

**Comment by Unknwon** [comment]
> scripts/supervisor/gogs

This file is just a template, not grantees to work out of box.

And once you change your Gogs binary path, you should do following in admin dashboard:

![image](https://cloud.githubusercontent.com/assets/2946214/11609107/19165cf6-9b4b-11e5-9255-ba8b68e13eaa.png)

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.

**Comment by nioc** [comment]
Hello, it is ok with the Rewrite hooks button.
I think this should be noticed in the documentation in [Install from binary] (https://gogs.io/docs/installation/install_from_binary) or [Configuration and run](https://gogs.io/docs/installation/configuration_and_run)?

**Comment by Unknwon** [comment]
@nioc thanks your confirmation!

I'll put into FAQ.

**Comment by Unknwon** [comment]
Here we go: https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook

**Comment by nioc** [comment]
You're fast, even in French, thanks :smile

**Comment by Unknwon** [comment]
:wink:
