### ISSUE TITLE
SPF

### ISSUE THREAD

**Issue by ponzipoh** [gogits/gogs#2108]
Email sent by Gogs are *not* [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework) compliant, and consequently email are treated as spam by major providers (google, microsoft, ...)

**Comment by Unknwon** [comment]
Hi @ponzipoh , I'm not sure which `Gogs` you mean, you are talking https://try.gogs.io or self-host instance?

**Comment by SoftCreatR** [comment]
Good question, since every admin is reliable for his own installation. So if any Gogs installation is not SPF compliant, it's the fault of the admin who runs it (SPF compliance is done via DNS record, not by the mail sender software).

**Comment by nanoant** [comment]
AFAIK Gogs has nothing to do with SPF. It uses given SMTP server, and it is up to the system administrator who has setup that SMTP server and related domain, to ensure that SMTP server's IP is listed properly under SPF DNS records entries.
So IMHO this issue is invalid.

**Comment by Unknwon** [comment]
Remain closed until better prove.
