### ISSUE TITLE
External URL for wiki

### ISSUE THREAD

**Issue by rhaamo** [gogits/gogs#2114]
Like the Issue Tracker "external url" would it be possible to have one for the Wiki link ?

**Comment by Unknwon** [comment]
It's now possible on `develop` and see in action here: https://try.gogs.io/gogs/gogs

**Comment by stonerl** [comment]
It works so far but there is on minor annoyance. 

You have to enable the wiki even if you use the external address. Which does not make much sense IMHO

![screenshot-try gogs io 2015-12-12 23-02-43](https://cloud.githubusercontent.com/assets/2091312/11764144/a44c5774-a124-11e5-97a6-0582685bb1ba.png)

**Comment by Unknwon** [comment]
If you do not enable, the tab is not even visible. Same rule apply for `issues`.

**Comment by stonerl** [comment]
Yes but the difference is when you use an external wiki url you cannot use gogs internal wiki. But when you enable the issues you can use gogs internal issue tool even if you have added the external issue url.

**Comment by Unknwon** [comment]
@stonerl make sense, let me think...

**Comment by stonerl** [comment]
My suggestion would be. When Using the internal Wiki on cannot use the external-wiki-url. When using the internal issue tracker one cannot use the external issue-tracker-url. I think one will run into problems with the issues-tracker-linking when the external and the internal-numbers are the same.

**Comment by Unknwon** [comment]
@stonerl yes, I think it would be better to rise another issue.
