### ISSUE TITLE
Remove SHA1 from "Code" and "Commits" tabs

### ISSUE THREAD

**Issue by ponzipoh** [gogits/gogs#2116]
If you look at [this repo](https://try.gogs.io/delitrem/testrep) for example, in both "Code" and "Commits" tabs there are the SHA1 value of the commits. You could remove the hash, and add the link to the commit's comment instead (for example add the link to the text "initial commit" instead of "8d009042b5")

**Comment by Unknwon** [comment]
It is not that simple when you have "#xxx" in commit message, and likely will not be implemented until more strong prove of need or good solution to fit.
