### ISSUE TITLE
Improve PR messages

### ISSUE THREAD

**Issue by ponzipoh** [gogits/gogs#2117]
When submitting a PR, the text says "You can perform auto-merge" or "You can't perform auto-merge operation because there are conflicts between commits.". This is a bit ambiguous, because it seems to suggest that I (who created the PR) am required or allowed to merge. Please change it with something more impersonal, for example "This pull request can be automatically merged because there are no conflicts", or "This pull request cannot be automatically merges because there are conflicts. Please merge manually in order to resolve the conflicts.".

Alternatively, you can just hide that message to everybody except the users how own the repo and can actually merge.

**Comment by Unknwon** [comment]
I think better message should be:

- `repo.pulls.can_auto_merge_desc`: `This pull request can be merged automatically.`
- `repo.pulls.cannot_auto_merge_desc`: `This pull request cannot be merged automatically because there are conflicts.`
- `repo.pulls.cannot_auto_merge_helper`: `Please use command line tool to pull from upstream solve the conflicts.`

**Comment by angus-g** [comment]
I'd suggest for `repo.pulls.cannot_auto_merge_helper` something like:

     Please use the command line tool to pull from upstream and resolve the conflicts.

**Comment by Unknwon** [comment]
@angus-g +1

**Comment by ponzipoh** [comment]
Wait... if I've forked a repo and submitted a PR, shouldn't I be "downstream" technically speaking, and not "upstream"?
Anyway, I vote to remove both the words "upstream" and "command line tools". Keep things simple instead, just write **"Please merge manually in order to resolve the conflicts".**

**Comment by Unknwon** [comment]
Good point.

**Comment by angus-g** [comment]
Not to argue semantics, but I do think it is "upstream". Regardless, :+1: on making the message simpler and clearer by removing it anyway.

**Comment by Unknwon** [comment]
@angus-g would you like to make this PR?

**Comment by Unknwon** [comment]
Should be fixed by merging https://github.com/gogits/gogs/pull/2139

**Comment by Unknwon** [comment]
Close as fixed.
