### ISSUE TITLE
Tidb forces to listen on port 8888

### ISSUE THREAD

**Issue by jerusalemdax** [gogits/gogs#2118]
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      1051/gogs
tcp6       0      0 :::3000                 :::*                    LISTEN      1051/gogs

It's strange that gogs listen two ports 3000, and 8888 when I run the service. And I can't find any place to config the port 8888 which is conflict with my local service.

**Comment by Unknwon** [comment]
Note: https://github.com/pingcap/tidb/issues/684

**Comment by Unknwon** [comment]
As TiDB no wishes to disable this by default, Gogs's prebuild binaries will exclude it until then.

**Comment by linquize** [comment]
That PR has been merged

**Comment by Unknwon** [comment]
@linquize yes, but still listens on :8888 by default, the desired behavior is just the opposite.
