### ISSUE TITLE
ENABLE_HARD_LINE_BREAK is not configurable

### ISSUE THREAD

**Issue by tboerger** [gogits/gogs#2119]
As you can see on the source the value of ENABLE_HARD_LINE_BREAK is currently not configurable as the mapping to the correct config key is missing, just the variable itself is referenced here: https://github.com/gogits/gogs/blob/master/modules/setting/setting.go#L116

**Comment by Unknwon** [comment]
See https://github.com/gogits/gogs/blob/master/modules/setting/setting.go#L415 ...

**Comment by tboerger** [comment]
Ah, the full section is mapped at once. Sorry for the noise.

**Comment by Unknwon** [comment]
:trollface:
