### ISSUE TITLE
可见性和迁移类型这两个词用的很不妥当

### ISSUE THREAD

**Issue by interchen** [gogits/gogs#2123]
我今天在迁移旧Git仓库，在镜像问题上就折腾了几次
1. 可见性：鬼看的懂勾上后是可见还是不可见！而且不管勾没勾上，后面都一直显示着“该仓库为 私有的”
2. 迁移类型：鬼看的懂迁移类型勾上后是镜像还是非镜像！而且不管勾没勾上，后面都一直显示着“该仓库将是一个 镜像”

希望你们可以把这两个词修改一下
建议修改为
1. “不可见”： 未勾选是私有仓库，勾选为公开仓库，默认不勾选
2. “镜像”：未勾选为非镜像，勾选为镜像，默认不勾选

**Comment by hackerpl** [comment]
支持啊~歧义太大了

**Comment by Unknwon** [comment]
Thanks your feedback!

I think it is very obvious convention that checked is for `true`, uncheck is for `false`, and the statement is affirmative.

According to:

> Please start discussion or ask a question on the forum. GitHub issue tracker only keeps bugs and feature requests, all other topics will be closed without reason.

Please continuing discussion on http://forum.gogs.io/

**Comment by interchen** [comment]
But there is still a bug.
Whatever check or uncheck, the description for these two option state is not changed.

**Comment by Unknwon** [comment]
Yes, this is exactly what I commented:

> convention that checked is for true, uncheck is for false, and the statement is affirmative.
