### ISSUE TITLE
Cannot create pull request on version 0.7.33

### ISSUE THREAD

**Issue by rifatmahmud** [gogits/gogs#2124]
Althoguh the release's stated to fix the issue, I ran the gog binary in Ubuntu 14.04, but the, the new pull request button is not usable, both in Ubuntu and Linux.
I ran the service as ./gogs web.

![prblm](https://cloud.githubusercontent.com/assets/5104472/11654857/1adb9c74-9dd3-11e5-817a-879af0df738d.PNG)

**Comment by stonerl** [comment]
What kind of pull request? In the same repo or from your forked repo to the origin?

**Comment by stonerl** [comment]
PR in the same repo have not been implemented yet: #2111

**Comment by rifatmahmud** [comment]
Yes, between branches of same repo.

**Comment by stonerl** [comment]
As I mentioned before this is not yet implemented.

**Comment by Unknwon** [comment]
Thanks your feedback!

But as @stonerl mentioned, same issue has been created.

PS: the correct indicator is https://github.com/gogits/gogs/issues/1597
