### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#2128]
Hi, 

I tried to update my gogs on my Raspberry. I am using go language 1.5.2. At first I updated teh go-git-client. After that I cloned the new gogs:
            
    git clone -b develop https://github.com/gogits/gogs.git

Then I did:
 
    cd gogs
    go get -u -tags "sqlite" ./...

With this command I got the following error message:

    # github.com/gogits/gogs/models
    models/repo.go:348: not enough arguments in call to "github.com/gogits/git-shell".Clone

**Comment by Unknwon** [comment]
Please do `go get -u github.com/gogits/git-shell`.

**Comment by Unknwon** [comment]
Please try to pull from `master` again now :)

**Comment by focmb** [comment]
Thanks, updating the git-shell solved it.

**Comment by Unknwon** [comment]
😉
