### ISSUE TITLE
go install gogs -> error

### ISSUE THREAD

**Issue by dedalqq** [gogits/gogs#2129]
in git-shell (in commit 05d41d51a12bbe6572dd338afaf486ff2998c5d0) to method Clone was added third option.

because of this:
$ go install
models/repo.go:344: not enough arguments in call to "github.com/gogits/git-shell".Clone

in gogs version v0.7.33
=(

**Comment by Unknwon** [comment]
Please try pull from `master` again now :)

**Comment by dedalqq** [comment]
It worked
Thanks =)

**Comment by Unknwon** [comment]
:wink:
