### ISSUE TITLE
500 error when migrating empty bare repository

### ISSUE THREAD

**Issue by garygreen** [gogits/gogs#2131]
When you migrate a local bare repository (that is empty / no commits) it will give 500 error.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by garygreen** [comment]
2015/12/09 11:23:50 [I] Gogs: Go Git Service 0.7.33.1205 Beta

**Comment by garygreen** [comment]
Just tried latest and still getting same problem

**Comment by Unknwon** [comment]
Ps: I've edited my comment.

**Comment by garygreen** [comment]
It says 500 on the page. It creates the repository page on gogs... but just displays big 500

**Comment by Unknwon** [comment]
Please check on your server side.

**Comment by garygreen** [comment]
This is the error log

```
[Macaron] Started POST /repo/migrate for 192.168.50.112
2015/12/09 11:57:46 [T] action.newRepoAction: SquareHalo/Test
2015/12/09 11:57:46 [T] Repository migrated[13]: SquareHalo/Test
[Macaron] Completed /repo/migrate 302 Found in 108.3121ms
[Macaron] Started GET /SquareHalo/Test for 192.168.50.112
2015/12/09 11:57:46 [...s/middleware/repo.go:196 func1()] [E] GetBranches: exit status 1
[Macaron] Completed /SquareHalo/Test 500 Internal Server Error in 8.5057ms
2015/12/09 11:57:46 [...s/middleware/repo.go:196 func1()] [E] GetBranches: exit status 1
```

**Comment by Unknwon** [comment]
Thanks! 

What is your system and Git version?

Because when I try to migrate an empty repo:

![image](https://cloud.githubusercontent.com/assets/2946214/11685058/382886e0-9e44-11e5-971a-d51fc0318798.png)

**Comment by garygreen** [comment]
Hmm I think the repository I'm cloning is corrupted in some way. It works to clone locally but can't seem to replicate the problem when I test with another bare repository.

**Comment by Unknwon** [comment]
:sweat: so... is that repository can be public? Do you mind upload to https://try.gogs.io ?

**Comment by garygreen** [comment]
Sorry, its private repo and also once I did a push it seemed to fix itself. Closing for now

**Comment by Unknwon** [comment]
Sounds... awesome...
