### ISSUE TITLE
Page rendering is slow in Docker

### ISSUE THREAD

**Issue by limbo-lab** [gogits/gogs#2141]
I setup gogs using docker and everything works great except that page rendering is slow.

    © 2015 Gogs 当前版本: 0.7.37.1209 Beta 页面: 1683ms 模板: 979ms

    [Macaron] Started GET / for 192.168.31.194
    [Macaron] Completed / 200 OK in 2.846906187s
    [Macaron] Started GET /issues for 192.168.31.194
    [Macaron] Completed /issues 200 OK in 390.429455ms
    [Macaron] Started GET /pulls for 192.168.31.194
    [Macaron] Completed /pulls 200 OK in 381.901141ms
    [Macaron] Started GET /explore for 192.168.31.194
    [Macaron] Completed /explore 200 OK in 961.351999ms
    [Macaron] Started GET /iOS/KFramework for 192.168.31.194
    [Macaron] Completed /iOS/KFramework 200 OK in 368.597163ms
    [Macaron] Started GET /js/libs/highlight-8.9.1.pack.js for 192.168.31.194
    [Macaron] Started GET /css/highlight-8.9.1/github.css for 192.168.31.194
    [Macaron] [Static] Serving /css/highlight-8.9.1/github.css
    [Macaron] [Static] Serving /js/libs/highlight-8.9.1.pack.js
    [Macaron] Completed /css/highlight-8.9.1/github.css 200 OK in 2.369435ms
    [Macaron] Completed /js/libs/highlight-8.9.1.pack.js 200 OK in 48.050193ms

![a161e383-1e10-462f-85cf-0ad81fab0304](https://cloud.githubusercontent.com/assets/5107346/11709333/a5fd7dfc-9f51-11e5-8b74-b224832f0b23.png)

**Comment by cybernet** [comment]
you should use a dedicated vps ...

**Comment by Unknwon** [comment]
Thanks your feedback!

Have you enabled `prod` mode?

**Comment by limbo-lab** [comment]
Sure, the `prod` mode is enabled by default.
This is my app.ini configuration file:
```ini
APP_NAME = Gogs: Go Git Service
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
...
```

**Comment by Unknwon** [comment]
Thanks for following up!

Which Docker image are you using?

**Comment by limbo-lab** [comment]
The `gogs/gogs:latest` pulled yesterday which seems to be `0.7.37.1209` and I tried `gogs/gogs:0.7.0` which remains the same.

**Comment by Unknwon** [comment]
> The gogs/gogs:latest pulled yesterday which seems to be 0.7.37.1209 and I tried gogs/gogs:0.7.0 which remains the same.

@limbo-lab if that's the case, I suppose there is nothing to do with Gogs, because a lot people are using Docker.

**Comment by Unknwon** [comment]
Remain close until further feedback. :sailboat:

**Comment by linquize** [comment]
Do you enable logging in docker?
