### ISSUE TITLE
Disable password change if using external authentication, eg AD

### ISSUE THREAD

**Issue by bhchew** [gogits/gogs#2144]
If change password settings page doesn't support changing external authentication accounts passwor d like AD, think it make sense to hide the page.

**Comment by angus-g** [comment]
This is a duplicate of e.g. #1938 and should be fixed in the `develop` branch

**Comment by Unknwon** [comment]
Thanks your feedback!

As @angus-g mentioned, this is a duplicated issue, and has been fixed in `master`.
