### ISSUE TITLE
Still rewrites authorized_keys when builtin SSH server is enabled

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#2147]
Hi,

When I enable the builtin SSH server of Gogs it still writes to my `~/.ssh/authorized_keys` file. Perhaps it is a good idea to disable writing authorized_keys.

Also when disabling the `START_SSH_SERVER` option it should rewrite the authorized keys in that case.

Kind regards,

Rik

**Comment by Unknwon** [comment]
It is now fixed in `develop` branch, please help test.

**Comment by Unknwon** [comment]
Close as fixed.
