### ISSUE TITLE
Old activities still visible for repos that team members no longer have access in the organization

### ISSUE THREAD

**Issue by bhchew** [gogits/gogs#2148]
When creating teams in a organization, admin is able to grant different privilege to teams, eg write/read/admin and assign repositories to team.

Currently different team members having different access to repositories are able to view activities for all repositories in the dashboard. Clicking on the link of repo activities will bring them to a 404 page if they are not granted access to it. This might be mistaken for a bug.

Suggest to hide all activities for repositories that team members do not have access to it. 

Cheers

**Comment by Unknwon** [comment]
Note: docs for organization

**Comment by Unknwon** [comment]
Just found: https://unknwon.io/organize-your-teams-with-gogs-organization/

**Comment by Unknwon** [comment]
@bhchew Hi, how can you reproduce this?

My quick tests show that organization member who does not have access to private repository does not receive news feeds on dashboard.

**Comment by bhchew** [comment]
I think the old news feeds still shows after team member was revoked access to the repo. Previously the member have access to the repo.

Hmm not sure if its critical to fix if that's the case..

**Comment by Unknwon** [comment]
> I think the old news feeds still shows after team member was revoked access to the repo. Previously the member have access to the repo.

Oh... OK... I thin I can do something with it.

**Comment by Unknwon** [comment]
Renamed title to fit the pupose.

**Comment by Unknwon** [comment]
This should have been fixed by merging https://github.com/gogits/gogs/pull/2567

**Comment by Unknwon** [comment]
Close as fixed.
