### ISSUE TITLE
Global issue labels

### ISSUE THREAD

**Issue by ChubbyNinja** [gogits/gogs#2149]
Any chance of having issue labels that can span across a organisation or perhaps even global?

I think this would be beneficial to quite a few users

**Comment by Unknwon** [comment]
> Any chance of having issue labels that can span across a organisation or perhaps even global?

Can you give more detail?

**Comment by Unknwon** [comment]
Same to https://github.com/gogits/gogs/issues/1562 ?

**Comment by stonerl** [comment]
To me this looks like #1562

**Comment by Unknwon** [comment]
Remain close until further feedback. :sailboat:

**Comment by ChubbyNinja** [comment]
Yep absolutely correct - sorry for dupe!
