### ISSUE TITLE
SMTP authentication makes invalid assumption on protocol

### ISSUE THREAD

**Issue by janh** [gogits/gogs#2152]
When authentication using SMTP fails, the server response is search for the string "Username and Password not accepted". If the server does respond with another message, Gogs will display an internal server error.

However, the SMTP spec does not define specific messages, as clients should rely on status codes. [RFC 2554](https://www.ietf.org/rfc/rfc2554.txt) recommends the status code 535 to be sent. Thus, the check for the server response in Gogs should be less strict.

**Comment by Unknwon** [comment]
Thanks!

> However, the SMTP spec does not define specific messages, as clients should rely on status codes. RFC 2554 recommends the status code 535 to be sent. Thus, the check for the server response in Gogs should be less strict.

Maybe you can give more details on this because I can't see the contrast?

**Comment by janh** [comment]
Applications should not interpret the message text in SMTP, they are only meant for humans (for example as error message in mail applications).

A solution would be to check that the status code is 535. Most SMTP servers probably use this code for authentication failure.

So instead of checking for the string you could check if the error is a [textproto.Error](https://golang.org/pkg/net/textproto/#Error) and contains the *Code* 535.

**Comment by Unknwon** [comment]
> So instead of checking for the string you could check if the error is a textproto.Error and contains the Code 535.

Just to make sure, what is the benefit or real effect differences by using this approach?

**Comment by janh** [comment]
The current implementation works only if the server uses the message text "Username and Password not accepted". Most SMTP servers don't do this.

The issue is: Gogs shows a 500 error instead of the "wrong password" message (when signing in with wrong password, but correct username).

**Comment by Unknwon** [comment]
@janh thanks for your clarifying! I got it now.

**Comment by Unknwon** [comment]
Pushed fix to `develop` branch, please help test!

**Comment by janh** [comment]
It is fixed now!

**Comment by Unknwon** [comment]
Thanks your confirmation!
