### ISSUE TITLE
Email address is not set correctly after auto-registration

### ISSUE THREAD

**Issue by janh** [gogits/gogs#2153]
When SMTP authentication is enabled and the user is auto-registered the *email* and *avatar_email* fields are set to the user name.

This causes problems, if login is done with the username only and not an e-mail address.
For example, the user can't change his profile, as there will always be the error "Gravatar is not a valid email address."

A solution would be to force the user to enter an email address after his first login. This way, it could be ensured that every user has a valid email address set up.

**Comment by Unknwon** [comment]
Hi,

> This causes problems, if login is done with the username only and not an e-mail address.
For example, the user can't change his profile, as there will always be the error "Gravatar is not a valid email address."

Have you met this problem or you just think?

**Comment by janh** [comment]
Yes, this problema actually occurs for me.

In the database, the field *avatar_email* is set to the user name (which is not a email address) during auto-registration. This may be the reason.

**Comment by Unknwon** [comment]
Thanks! But why user can't just give a correct email for gravatar before updating his/her profile?

**Comment by janh** [comment]
I use offline mode and Gravatar is disabled. There is no way to change the Gravatar email in the profile with this configuration.

**Comment by Unknwon** [comment]
I see,I'll check for this. Thanks again!

**Comment by Unknwon** [comment]
Hi, I just pushed fix to `develop` branch, please help test again!

**Comment by janh** [comment]
The profile can now be changed.

**Comment by Unknwon** [comment]
Close as fixed.
