### ISSUE TITLE
Admin unable to edit organization max repo creation

### ISSUE THREAD

**Issue by KillTheIdols** [gogits/gogs#2156]
For example, we have no way to define max repositories for an organization and it is currently set to unlimited by default.

This means a user with limited repositories can simply create an organization and create unlimited repositories.

**Comment by Unknwon** [comment]
Hi, please try out `develop` branch, you can edit max_repo_creation in normal organization settings page when you login as admin.

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by KillTheIdols** [comment]
Awesome, do you reckon you would be able to create a link to an edit page like users? 

For example /admin/users/1 is the admin edit page for users, but add /admin/orgs/1 for an admin edit page for orgs?

**Comment by Unknwon** [comment]
@KillTheIdols good point, so you mean redirect ` /admin/orgs/1` to corresponding organization's settings page?

**Comment by KillTheIdols** [comment]
That's right, and also add add a link to an edit page like the same for users:

on admin/users there's a direct link to edit the orgs, but admin/orgs contains no such link.

**Comment by Unknwon** [comment]
@KillTheIdols Working it.

**Comment by KillTheIdols** [comment]
You're a beast, thanks! :bow:

**Comment by Unknwon** [comment]
@KillTheIdols Added to `master` branch.

**Comment by KillTheIdols** [comment]
Looks good to me, thanks :) :+1:

**Comment by Unknwon** [comment]
:blush:
