### ISSUE TITLE
Private repository with public wiki

### ISSUE THREAD

**Issue by BruinY** [gogits/gogs#2157]
add Private repository with public wiki,thanks

**Comment by thehowl** [comment]
While we're at it, I'd purpose to do it for everything in the repo, so to have a panel to set rules on whether the following are public:

* Code (and pull requests)
* Issues
* Releases
* Wiki

**Comment by Unknwon** [comment]
@thehowl issues are in another issue thread..

**Comment by BruinY** [comment]
It seems that in 0.9 milestone cannot be achieved

**Comment by Unknwon** [comment]
Yes, too many issues make 0.9 impossible.

**Comment by BruinY** [comment]
gogs function and external system demain point is not the same

**Comment by Unknwon** [comment]
> gogs function and external system demain point is not the same

What does this mean?

**Comment by BruinY** [comment]
#2642 is links in wiki, not gogs function.
Private repository with public wiki is gogs function

**Comment by Unknwon** [comment]
See https://github.com/gogits/gogs/issues/2642#issuecomment-185391491

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
