### ISSUE TITLE
Accept sending email (unkown authority)

### ISSUE THREAD

**Issue by Timetopretend** [gogits/gogs#2158]
Hi,

I have my own mail server using tls but I have not paid a certificate. I would like to use this server to send email from gogs git. But gogs does not accept to bypass verification certicate.
"could not send email 1: x509: certificate signed by unknown authority"
I think it would be a useful feature to add.

Gogs version: v0.7.33

I want to congratulate you for the work done for this project. I am the project for a long time and it has evolved in the right direction.

**Comment by Timetopretend** [comment]
Apologies that is in the documentation ...

**Comment by Unknwon** [comment]
😅
