### ISSUE TITLE
Dashboard "new" button text too long

### ISSUE THREAD

**Issue by NAAVOO** [gogits/gogs#2159]
http://i.imgur.com/GYUSZR0.png

Gogs Version: 0.7.33.1205 Beta

**Comment by Unknwon** [comment]
The issue will be certainly closed if you call it `Responsive`.

Just note https://github.com/gogits/gogs#browser-support

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/11763536/dbd7f268-a0dc-11e5-8d49-62df8cb82854.png)

**Comment by stonerl** [comment]
Problem exists with organizations in 1024*768. The german words are to long :smiling_imp: 

![screen shot 2015-12-12 at 22 36 17](https://cloud.githubusercontent.com/assets/2091312/11764032/021ec110-a121-11e5-91e6-1f78a77e2963.png)

**Comment by Unknwon** [comment]
@stonerl Thanks!

Let me change the button to an icon with tooltip, that should work.

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/11764089/f0170b92-a0f0-11e5-8829-72edd40ea151.png)
![image](https://cloud.githubusercontent.com/assets/2946214/11764090/f2c4ab9c-a0f0-11e5-8c17-7300b3743e4c.png)

**Comment by Unknwon** [comment]
You can test on https://try.gogs.io

**Comment by stonerl** [comment]
:+1:

**Comment by Unknwon** [comment]
Close as fixed.
