### ISSUE TITLE
No issue linking in commits when issue number in brackets

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2161]
When the issue-number is written in brackets gogs does not link to the issue.

https://try.gogs.io/stonerl/test-mirror/commit/575fc9acbdfb90c493d0568f354224d1af6fac25

**Comment by Unknwon** [comment]
Here you go: https://try.gogs.io/stonerl/test-mirror/commit/575fc9acbdfb90c493d0568f354224d1af6fac25

**Comment by stonerl** [comment]
Wow... that was fast... :+1:

**Comment by Unknwon** [comment]
:smile:

**Comment by stonerl** [comment]
I think it introduced a bug:

https://try.gogs.io/stonerl/test-mirror/commits/master
https://try.gogs.io/stonerl/test-mirror/commit/cec4b803cf9394b64d8c7e2647b8f2ad9f3ab978

lots of 39.

**Comment by Unknwon** [comment]
Thought `/W` to be a shortcut, turns out I still need to explicitly define `(`...

**Comment by stonerl** [comment]
seems to have something to do with #1937 ?

its the ```'``` character.

**Comment by Unknwon** [comment]
Fixed: https://try.gogs.io/stonerl/test-mirror/commit/cec4b803cf9394b64d8c7e2647b8f2ad9f3ab978

**Comment by stonerl** [comment]
:+1:

**Comment by Unknwon** [comment]
> seems to have something to do with #1937 ?

That was because bluemonkey... looks same but completely different.

**Comment by stonerl** [comment]
OK
