### ISSUE TITLE
Only use internal or external Issue-Tracker/Wiki

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2162]
As mentioned here: https://github.com/gogits/gogs/issues/2114#issuecomment-164198779 either use the internal issue-tracker and wiki or the external.

The Problem is that if the internal Issue-Tracker and an External-Issue-Tracker URL is given gogs links to the external issues but not the internal. When an external Wiki-URL is given one has to enable the internal wiki to make the wiki appear but clicking on the Wiki-link redirects to the external wiki.

**Comment by stonerl** [comment]
When enabling the internal Issue-Tracker/Wiki the user should not be allowed to enter an URL for an external URL or these URLs should be disabled.

When using an external Issue-Tracker/Wiki the Issue and Wiki tabs should appear on the top of the repo but clicking on them should redirect the user to the external url.

**Comment by rhaamo** [comment]
It would be great to be able to use ```{repo}``` etc. in the External Wiki URL too.
Maybe opening another issue for that @Unknwon ?

**Comment by Unknwon** [comment]
@rhaamo I think wiki does not need placeholders as it only redirects for one link...

**Comment by rhaamo** [comment]
Oops yes sorry. dont know what my brain was thinking...

**Comment by Unknwon** [comment]
:joy:

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by stonerl** [comment]
hmm, does not seem to work. I tried it on try.gogs.io, when I select external issue tracker I'm still able to create issues in the internal issue tracker.

**Comment by Unknwon** [comment]
Note: should disable issue-related APIs when use external tracker.

**Comment by Unknwon** [comment]
@stonerl now patch pushed to `develop` and demo site.
