### ISSUE TITLE
Make PostgreSQL and Redis databases optional

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2163]
Install screen asks to choose between PostgreSQL and SQLite. Yet tags only offer to choose SQLite as optional. Shouldn't PostgreSQL also be optional based on tags?

Then Redis: docker/build.sh suggests that redis is also optional (it one of the tags), but when gopkg.in/redis.v2 is removed I get this error:
```
../../go-macaron/cache/redis/redis.go:25:2: cannot find package "gopkg.in/redis.v2" in any of:
        /usr/local/go/src/gopkg.in/redis.v2 (from $GOROOT)
        /usr/ports/devel/gogs/work/gogs-0.151211/src/gopkg.in/redis.v2 (from $GOPATH)
```

Same with github.com/bradfitz/gomemcache/memcache - it is in tags but is always required

**Comment by Unknwon** [comment]
Hi, `tags` you're saying is [build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints), not feature choose tag, they are completely different.

> Then Redis: docker/build.sh suggests that redis is also optional (it one of the tags),

You should always get latest docs from [official website](https://gogs.io/docs/installation/install_from_binary).

**Comment by yurivict** [comment]
So how do I disable features Postgre/MySQL/Redis? It still wants them during build.

Link you provided only talks about installing from binary, which isn't what I am doing.

**Comment by Unknwon** [comment]
> So how do I disable features Postgre/MySQL/Redis? It still wants them during build.

https://gogs.io/docs/installation/install_from_source#build-with-tags

**Comment by Unknwon** [comment]
If you don't want to use them just change the config file, I don't see any problem point that if you don't need a feature and remove it from source code.

**Comment by yurivict** [comment]
> I don't see any point that
When people ask something, there is usually a point behind the questions.

I am making the FreeBSD port for gogs. There are port options SQLITE PGSQL REDIS. When these options aren't selected, this means that the user doesn't want these parts.

So why do I need to download these files when the user says he doesn't want this support:
go-redis-redis-781f7f8_GH0.tar.gz
mattn-go-sqlite3-5651a9d_GH0.tar.gz
?

For SQLite tag="sqlite" is the the "feature choose tag" because when tag=sqlite is removed the feature disappears.

**Comment by Unknwon** [comment]
Gogs has `sqlite` not because want to give choice of feature, it is the side effect. The real reason is it uses CGO and so can't be used with go1.5 cross-compile feature.

**Comment by linquize** [comment]
This is because sqlite binding is written in C and requires a C compiler.
If you do not need sqlite, you can compile a pure go binary by omitting sqlite tag to go compiler.

**Comment by yurivict** [comment]
Is this correct that gogs is able to work with all DBs w/out requiring any external libraries?

**Comment by Unknwon** [comment]
Except SQLite3, you need to build with tags.

**Comment by yurivict** [comment]
Cool, thanks, I didn't realize this.

**Comment by Unknwon** [comment]
:trollface:

**Comment by yurivict** [comment]
I recommend you make SQLite option the first in list when enabled, because this is what is the easiest for people to try.

**Comment by Unknwon** [comment]
@yurivict It shows the same one in your configuration, which is more precise.

**Comment by yurivict** [comment]
Help me here: I have built with tags="sqlite redis", yet SQLite3 shows in the combobox, and Redis doesn't. Is something broken or missing?

> It shows the same one in your configuration, which is more precise.

You mean I can I set the order in the config file? How?

**Comment by Unknwon** [comment]
> Help me here: I have built with tags="sqlite redis", yet SQLite3 shows in the combobox, and Redis doesn't. Is something broken or missing?

Redis is not a backend DB for Gogs.

> You mean I can I set the order in the config file? How?

No, you can't set order. What I mean is it highlights the one you already chosen.
