### ISSUE TITLE
Add pagination to releases

### ISSUE THREAD

**Issue by roidelapluie** [gogits/gogs#2164]
All the releases come in one page. I have a git repo with thousands of tags, where it would be appreciated to limit the number of releases to 10 per page.

This lack of pagination causes the relases page to hang for several minutes.

**Comment by JonLundy** [comment]
This feature would be nice when viewing folders with lots of files also.

**Comment by Unknwon** [comment]
@JonLundy thanks for the comment but I think that's irrelevant to this thread.

**Comment by eByte23** [comment]
I will do this.
Cheers

**Comment by bkcsoft** [comment]
@eByte23 are you still working on this?

**Comment by eByte23** [comment]
@bkcsoft I was working on this until something else came up but I can continue to do it?

**Comment by bkcsoft** [comment]
If you wanna work on it that's awesome, otherwise I'll take it :smile:

**Comment by eByte23** [comment]
Sure see what I can do hey :D

**Comment by tomterl** [comment]
We were hoping to deploy gogs inhouse, but this issue is a showstopper -- is there progress? Maybe something a go-beginner can work on?

**Comment by amavlyanov** [comment]
Actually this should be treated as a bug, since with a lot's of "releases" one can not use this in "production" environment.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/gogs/gogs/releases.

**Comment by jxsl13** [comment]
Shouldn't you change the two buttons next and previous?
I get the page in German and it contains the next button, showing previous releases.
and the other way around. Previous page for later/newer releases.

**Comment by Unknwon** [comment]
@jxsl13 it is the exact same behavior as GitHub: https://github.com/gogits/gogs/releases

**Comment by jxsl13** [comment]
Hm, true, weird :D 
A great feature would be to upload an own binary instead of only the code being packed as zip/tar

**Comment by Unknwon** [comment]
@jxsl13 sure, there is already an issue asks for that: https://github.com/gogits/gogs/issues/1614

**Comment by jxsl13** [comment]
I'm kind of wondering, do you actually sleep?

**Comment by Unknwon** [comment]
@jxsl13 .... why not..?

**Comment by jxsl13** [comment]
It seems like you are working 24/7 and you seem to be always online.

**Comment by Unknwon** [comment]
@jxsl13 ... not true.. I do sleep.. (we can talk on gitter.im to not spam on this thread)
