### ISSUE TITLE
Can't identify git version on Windows

### ISSUE THREAD

**Issue by i00** [gogits/gogs#2167]
0.7.33.1205 worked fine, but with 0.8 I cannot start it as I get:

.../gogs/models/repo.go:108 NewRepoContext()] [E] Gogs requires Git version greater or equal to 1.7.1

My git version is 2.6.3.windows.1

**Comment by Unknwon** [comment]
What is the output when you execute:

```
$ git version
```

**Comment by i00** [comment]
2.6.3.windows.1 is the output from git --version, this is the command on Windows... btw I am using the x64 version

**Comment by Unknwon** [comment]
Oh... I see, that is the problem.

Gogs only recognizes output format like `git version 1.8.3.1`.

**Comment by Unknwon** [comment]
Hi, I just pushed a fix to `develop` branch, please update dependency by `go get -u github.com/gogits/git-shell`.

**Comment by andreynering** [comment]
I just tried the `develop` branch and had the same issue. I had to comment [these lines](https://github.com/gogits/gogs/blob/master/models/repo.go#L107-L109) and everything worked fine.

The output to `git --version` is:

```bash
git version 2.5.2.windows.2
```

**Comment by Unknwon** [comment]
Now someone is talking... I see the problem now

**Comment by Unknwon** [comment]
Hi @andreynering , can you `go get -u github.com/gogits/git-shell` again and test, thanks!

**Comment by andreynering** [comment]
@Unknwon It's fixed now.

**Comment by Unknwon** [comment]
@andreynering thanks your confirmation!

**Comment by Unknwon** [comment]
cc @i00

**Comment by i00** [comment]
Thanks :+1: ...

And not trying to sound impatient ... but when will this be in a release?

**Comment by Unknwon** [comment]
@i00 18th this month...so it will be Friday?

**Comment by Unknwon** [comment]
Close as fixed.
