### ISSUE TITLE
Support multi-licensing when create repository

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2173]
Some software is multi-licensed: https://en.wikipedia.org/wiki/Multi-licensing

This isn't a very important feature, but some will find it necessary.

**Comment by Unknwon** [comment]
Thanks your feedback!

But what is your real suggestion that is related to Gogs? As you have full control of the repository.

**Comment by stonerl** [comment]
I think what he means is that, when you create a repo you con only choose one license. When you want to have two licenses you want to apply you have to add the second one manually and not during repo creation.

**Comment by yurivict** [comment]
> I think what he means is that, when you create a repo you can only choose one license. 

Exactly.

**Comment by Unknwon** [comment]
Thanks, so how should this feature exactly work?

**Comment by yurivict** [comment]
Allow selecting more than one license (just like for language). Place all licenses into the project with the suffix, ex. LICENSE -> {LICENSE_MIT, LICENSE_BSD} or similar

**Comment by Joshua-Anderson** [comment]
@yurivict What other licences do you need? The MIT licence is really permissive and basically imposes no restrictions.

**Comment by Unknwon** [comment]
How about put all license files into `licenses` directory, I think this is more organized way.

**Comment by yurivict** [comment]
@Joshua-Anderson I personally don't need any licenses at all -)

It's that *some other people* for whatever reasons think they need them.

**Comment by yurivict** [comment]
> How about put all license files into licenses directory, I think this is more organized way

Sounds good, but not what the practice has been. People are used to see the LICENSE* or COPYING* files at the top level. You better keep them there.

**Comment by Unknwon** [comment]
@yurivict do you have example of repository use multi-licensing?

**Comment by yurivict** [comment]
@Unknwon No, I just know they exist

**Comment by Unknwon** [comment]
> No, I just know they exist

If this is the case, I would think close this issue until someone is really using it.

**Comment by yurivict** [comment]
From WIkipedia:
>Examples of multi-licensed software include Oracle's NetBeans IDE, MySQL AB's database, Asterisk, Oracle Corporation's Berkeley DB, Modelio, ZeroC's Ice, Magnolia CMS and Qt Software's Qt development toolkit.

**Comment by Unknwon** [comment]
> From WIkipedia:
> Examples of multi-licensed software include Oracle's NetBeans IDE, MySQL AB's database, Asterisk, Oracle Corporation's Berkeley DB, Modelio, ZeroC's Ice, Magnolia CMS and Qt Software's Qt development toolkit.

Still can't find real usage of multiple license files.

**Comment by Joshua-Anderson** [comment]
@yurivict The point of multi licencing is that projects have a restrictive licence like the GPL, but they licence their software under a proprietary licence for companies that pay to use it commercially. Since gogs is licenced under the unrestrictive MIT licence, there is little reason that somebody would want to licence it under anything else, since the MIT allows them to do almost anything with it.

**Comment by Unknwon** [comment]
@Joshua-Anderson I think @yurivict 's request is allow Gogs to create multi-licensing repositories.

**Comment by yurivict** [comment]
> Examples include the source code of Mozilla Application Suite and previously Mozilla Thunderbird and Mozilla Firefox, that have used tri-licensing under the Mozilla Public License (MPL) 1.1, GNU General Public License (GPL) 2.0 or GNU Lesser General Public License (LGPL) 2.1[12] before the latter upgraded to GPL-compatible MPL 2.0, making the tri-licensing unnecessary;[13] Perl, which is dual-licensed under the GPL or Artistic License;[14] and Ruby, whose license contains explicit GPL dual licensing.

**Comment by Joshua-Anderson** [comment]
That makes more sense. :smiley:  Sorry, I misunderstood.

**Comment by yurivict** [comment]
I am not an expert on licensing myself. What Wikipedia  says is all I know. :-)

**Comment by Unknwon** [comment]
OK, finally found something useful:

![image](https://cloud.githubusercontent.com/assets/2946214/11770271/1546a576-a1c8-11e5-84c6-11dbd75a76d9.png)

Looks like just put license file with its name under root directory.

**Comment by nanoant** [comment]
IMHO there is no point to complicate repo initialization process and Gogs itself just to support edge case.

1. I doubt anyone wants to start empty project with 2 licenses right away. Even given some examples of projects using dual licensing, there were not dual licensing on project creation.
2. Any time wanted user is free to add 2nd license file.

Just to remind, repo README & License initialization is just a convenience helper, not a must and not an only way to add these files.

**Comment by stonerl** [comment]
I second @nanoant here. I also think this is an edge case. Github for example does not even support choosing a license when initializing an empty repo.

**Comment by Unknwon** [comment]
Remain closed until someone is **really** using it and have **real** feedback.
