### ISSUE TITLE
How to set proper custom config file?

### ISSUE THREAD

**Issue by z0rr0** [gogits/gogs#2174]
Custom config `/opt/gogs/custom/conf/app.ini` was removed from debian package ver. **0.8.0**, so custom configuration settings are not used. As I understand it was done in the commit fa8bf0f1d. 

How can I set custom settings?

Gogs deb package version: 0.8.0-1449979765.4df378b.trusty
OS: Ubuntu GNU/Linux 14.04 3.13.0-71-generic x86_64
Git: 1.9.1

**Comment by stonerl** [comment]
/etc/gogs/conf/app.ini

**Comment by z0rr0** [comment]
@stonerl , the file `/etc/gogs/conf/app.ini` contains a header:

```
# NEVER EVER MODIFY THIS FILE
# PLEASE MAKE CHANGES ON CORRESPONDING CUSTOM CONFIG FILE
```

I am not sure it's a good idea to edit it.

**Comment by stonerl** [comment]
That's because it takes the file from  /opt/gogs/conf/ and copies it to /etc/gogs/conf you must not change the file into /opt/...

-----Original Message-----

**Comment by stonerl** [comment]
@z0rr0 have a look here: https://gogs.io/docs/advanced/configuration_cheat_sheet ```custom/conf/app.ini```does not exist anymore for the deb packages. Therefore you have to use ```/etc/gogs/conf/app.ini```

**Comment by stonerl** [comment]
This has been changed because some users where hitting a severe bug #1897

**Comment by Unknwon** [comment]
cc @crohr :

I think it's not a good idea to keep full version of default configuration as default configuration may have bug sometimes, so the best way is just use the parts that user customized. 

In this case, 

- Is it possible to check if user is installing Gogs for the first time? If yes, remove the default `/etc/gogs/conf/app.ini` and let Gogs generates a partially modified one itself.
- for second or later time, just keep the way right now.

How do you think?

**Comment by Unknwon** [comment]
@z0rr0 what is the situation of this issue now...?

**Comment by z0rr0** [comment]
@Unknwon I don't know how to set custom configuration properly.

One my project uses ubuntu-based docker image with gogs deb package. It rewrited a custom config file and worked well before.

**Comment by Unknwon** [comment]
>  I don't know how to set custom configuration properly.

What does this mean?

**Comment by z0rr0** [comment]
@Unknwon `properly` means a proper file, `/opt/gogs/custom/conf/app.ini` and `/etc/gogs/conf/app.ini` don't work. My usecase is: 1) install gogs 2) create a custom config 3) run gogs

Do I right understand that gogs replaces `/etc/gogs/conf/app.ini` during the first start?

**Comment by Unknwon** [comment]
@z0rr0 No, Gogs replaces nothing. It was replaced by packager.io builder, but I think they have fixed this problem.

**Comment by z0rr0** [comment]
@Unknwon I see this behavior using a package `0.8.25-1454711359.e797a22.trusty`

**Comment by Unknwon** [comment]
According to https://github.com/gogits/gogs/blob/master/packager/hooks/postinst#L18 , you should use `/etc/gogs/conf/app.ini`.

**Comment by z0rr0** [comment]
I use this `app.ini` and can login through web, but `git pull` returns:

```
Gogs: Internal error
Failed to get repository owner (user): dial tcp 127.0.0.1:3306: getsockopt: connection refused
fatal: Could not read from remote repository.
```

And `/var/log/gogs/serv.log` contains:

```
 [...ts/gogs/cmd/serve.go:167 runServ()] [F] Failed to get repository owner (user): dial tcp 127.0.0.1:3306: getsockopt: connection refused
```

Why IP `127.0.0.1` is used to connect to database? My configuration has no this value.

**Comment by Unknwon** [comment]
If you use MySQL, `127.0.0.1` is the default value.

**Comment by z0rr0** [comment]
@Unknwon yes, it's expected, but can I set another value? My custom `app.ini` contains a name of remote MySQL host `HOST = mysqlhost:3306` in section `[database]`. 

I used a configuration file `/opt/gogs/custom/conf/app.ini` with gogs deb package `0.7.33`, it worked without any problems. I moved the file to `/etc/gogs/conf/app.ini` and tried to use new version of the package, but got "database connection refused" error for some operations.

**Comment by Unknwon** [comment]
Can you the stdout of Gogs? Because Gogs prints which custom file it uses there.

**Comment by z0rr0** [comment]
```
2016/02/07 20:57:44 [T] Custom path: /etc/gogs
2016/02/07 20:57:44 [T] Log path: /opt/gogs/log
2016/02/07 20:57:44 [I] Softlation Git Repository 0.8.31.0205
2016/02/07 20:57:44 [I] Log Mode: File(Info)
2016/02/07 20:57:44 [I] Cache Service Enabled
2016/02/07 20:57:44 [I] Session Service Enabled
2016/02/07 20:57:44 [I] Mail Service Enabled
2016/02/07 20:57:44 [I] Notify Mail Service Enabled
2016/02/07 20:57:44 [I] Git Version: 1.9.1
2016/02/07 20:57:44 [I] Migration: generate rands and salt for organizations
2016/02/07 20:57:44 [I] Run Mode: Production
2016/02/07 20:57:44 [T] Doing: CheckRepoStats
2016/02/07 20:57:45 [I] Listen: http://0.0.0.0:9000
```

```
grep "127.0.0.1\|3306" /etc/gogs/conf/app.ini 
HOST = mysql:3306
; memcache: `127.0.0.1:11211`
```

**Comment by Unknwon** [comment]
@z0rr0 Please try this: https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook

**Comment by z0rr0** [comment]
@Unknwon It helped! All works perfect. Thank you very much!

**Comment by Unknwon** [comment]
@z0rr0 Great, so there was an old binary lives somewhere that still reads wrong configuration.

**Comment by trompx** [comment]
Hello,

I am struggling to run gogs without install step with docker.

So in my Dockerfile I add a custom app.ini in a temporary folder at image build, then in the start.sh, once the /data/gogs folder are created (i added /data/gogs/custom/conf in the create_volume_subfolder function), I sed the custom app.ini file to update variable like domain / db_type and set INSTALL_LOCK = true.

But when I run the gogs container (with -v /gogs:/data), and browse my_server_ip:proxy_port, I hit directly the install page. If I exec -it bash in the container, I see my custom app.ini at /data/gogs/custom/conf/app.ini but it is not used. Before install, no other app.ini file is present on the image when I `find / -name app.ini`, only the custom one I added.

I am a bit lost with all the paths :
- /opt/gogs/custom/conf/app.ini
- /etc/gogs/conf/app.ini
- /data/gogs/custom/conf/app.ini


Which one is the correct one (the one gogs reads before install step) that I need to edit/create to skip this install step ?

I tried with gogs/gogs:latest and 0.8.25

Thanks

**Comment by Unknwon** [comment]
@trompx For the Docker case, please read https://github.com/gogits/gogs/blob/master/docker/README.md

**Comment by trompx** [comment]
I already did, and it's quite unclear.

On this page, Settings - Applications. Are the settings the one we are supposed to fill on the install page ? If yes, that's those variables I'd like to set in a custom app.ini file to not have to fill them at install.
In the same section of the page your mentionned, a link redirect to https://gogs.io/docs/advanced/configuration_cheat_sheet.html which talks about the custom app.ini file (while it is not mentionned on the docker gogs page). So where does this file is supposed to be in the first place ? running the gogs/gogs:latest just after pulling it from the repo, doing `find / -name app.ini` returns no result, no app.ini, no custom app.ini either.

So where are those files, when are they created, or where are we supposed to create them ?

**Comment by Unknwon** [comment]
It is very clear where the custom files are stored:

```
/var/gogs
|-- git
|   |-- gogs-repositories
|-- ssh
|   |-- # ssh public/private keys for Gogs
|-- gogs
    |-- conf
    |-- data
    |-- log
```

**Comment by trompx** [comment]
At https://gogs.io/docs/advanced/configuration_cheat_sheet.html, `custom/conf/app.ini` is a path.

At https://github.com/gogits/gogs/blob/master/docker/README.md, the directory structure you copied is refered to as the `local path /var/gogs`. And there is not the `custom` folder in any of them.

So you are saying that the `custom` = `var/gogs` ?

**Comment by Unknwon** [comment]
You only need to follow the README unless you want to dig into details: https://github.com/gogits/gogs/blob/master/Dockerfile#L9

`custom` is just a name, like computer, you can call it `windows crap` as you prefer, but it is still a computer.

**Comment by trompx** [comment]
Thanks for the clarification.

**Comment by toddkaufmann** [comment]
I found this very confusing as well.  Maybe it's more so for docker where there isn't an existing directory with `app.ini`.  The docs that say

> ... if you are not allowed to edit `conf/app.ini`? Well, create `custom/conf/app.ini`  ...

led me to think I should create a folder called `custom` at the same level as `conf`.  
It would be more clear with a metavariable such as `<gogsRoot>/` or `$gogsRoot/`.

After trying `strace` to see what files `gogs` was trying to read, and reading many messages here, I did see this a few thousand lines back in my terminal buffer: 
```2016/03/30 06:35:52 [T] Custom path: /data/gogs```

Apparently this message only goes to stdout, not the log file?  This info though is the most useful, especially when trying to find where configuration is read from and what the values are.

Also helpful would be clarification that if `app.ini` doesn't exist, it will get created for you
(and when you write it you can add a header message 
"`; This it your config file, created by gogs 0.9.15.0323; please edit to customize your server`"
this would be useful when upgrading or looking at release notes to see what new settings might exist etc.

Otherwise it's working pretty well!  Thanks.
