### ISSUE TITLE
Support download for abbreviated versions

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2175]
git sites usually support archive URLs, like this one: https://go.googlesource.com/net/+archive/d75b190.tar.gz

I couldn't get this to work with Gogs: "Not Found"

**Comment by Unknwon** [comment]
I have no idea what is issue about....

![image](https://cloud.githubusercontent.com/assets/2946214/11769795/7f4d2b62-a1bd-11e5-8424-9e715f2a167f.png)

**Comment by stonerl** [comment]
I'm not entirely sure but the site @yurivict revers to seems to allow downloads of tar files for a specific commit. So you choose a commit e.g. this one: https://go.googlesource.com/net/+/da05ccad07ec039aa9acfb9514a129ba46844152

and then you can download the source for this specific state of the repo during this very commit I guess.

**Comment by Unknwon** [comment]
Thanks @stonerl ,

> I'm not entirely sure but the site @yurivict revers to seems to allow downloads of tar files for a specific commit. So you choose a commit e.g. this one: https://go.googlesource.com/net/+/da05ccad07ec039aa9acfb9514a129ba46844152

and then you can download the source for this specific state of the repo during this very commit I guess.

If this is the case, then the link format is `https://try.gogs.io/gogs/gogs/archive/{SHA}.tar.gz` in Gogs. For example, https://try.gogs.io/gogs/gogs/archive/59c965a5ec2553b40a76cc322855b62116eac5f0.tar.gz

**Comment by yurivict** [comment]
Yes. git-archive feature is hoked up to the web interface with this type of URL. This is useful when people want to download distfiles right from the git site.

https://git-scm.com/docs/git-archive

**Comment by stonerl** [comment]
@Unknwon maybe an additional download-button on the detailed commitview that allows you to download a tar/zip-file?

**Comment by yurivict** [comment]
It should be URL-based. The +archive form (see above) is used by googlesource.com, GitHib uses this form:
```
https://codeload.github.com/golang/{acct}/{user}/{fmt(ex.tar.gz)}/{7-char tag}
```
(maybe other tag abbreviations also work, didn't check)

**Comment by Unknwon** [comment]
https://try.gogs.io/gogs/gogs/archive/59c965a5ec2553b40a76cc322855b62116eac5f0.tar.gz is not a URL?

`https://try.gogs.io/{user}/{repo}/archive/{branch,tag,40-char SHA}.{format}`.

**Comment by yurivict** [comment]
For some reason this doesn't work on my local install:

```
$ fetch http://localhost:15123/yuri/qTox/archive/d6473d66d2.tar.gz
fetch: http://localhost:15123/yuri/qTox/archive/d6473d66d2.tar.gz: Not Found
```

**Comment by Unknwon** [comment]
Yes, I have explicitly noted it is `40-char SHA`...

**Comment by yurivict** [comment]
Then the bug is that you don't support the abbreviated versions :-)

**Comment by Unknwon** [comment]
So I think you need to change issue title to `Support download for abbreviated versions`.

**Comment by ralphtheninja** [comment]
> If this is the case, then the link format is https://try.gogs.io/gogs/gogs/archive/{SHA}.tar.gz in Gogs. For example, https://try.gogs.io/gogs/gogs/archive/59c965a5ec2553b40a76cc322855b62116eac5f0.tar.gz

@Unknwon Is this documented anywhere? I was trying to find out how I could get archives using the 40 char sha1 (I obviously know now ;)) and couldn't find it in the docs

**Comment by Unknwon** [comment]
@ralphtheninja it is a visual button:

![image](https://cloud.githubusercontent.com/assets/2946214/16457025/aab6bd5a-3e4c-11e6-9789-5bbc2aa6ba18.png)

**Comment by Unknwon** [comment]
For API: https://github.com/gogits/go-gogs-client/wiki/Repositories-Contents#download-archive

**Comment by Unknwon** [comment]
I think this is fixed already.
