### ISSUE TITLE
Error 500 on /watchers & /stars

### ISSUE THREAD

**Issue by LeKovr** [gogits/gogs#2176]
I open project page and click to watcher or start counter. This gives me error 500 (both org/repo/watchers and  org/repo/stars)
in logs:
```
...routers/repo/view.go:262 renderItems()] [E] getter: pq: syntax error at or near "."
```
Gogs v0.7.33 
DB: Postgresql 9.3.10

**Comment by LeKovr** [comment]
The same error in 0.8.0.1212

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you dump the `xorm.log` here as well?

**Comment by LeKovr** [comment]
For this gogs.log record:
```
2015/12/14 01:34:13 [...routers/repo/view.go:260 renderItems()] [E] getter: pq: syntax error at or near "."
```
attached [xorm.log.txt](https://github.com/gogits/gogs/files/60635/xorm.log.txt)

**Comment by Unknwon** [comment]
Thanks!

Is this a valid SQL query in PostgreSQL?

```
SELECT * FROM "user" LEFT JOIN "watch" ON user.id=watch.user_id WHERE repo_id=1
```

If not, can you help debug which part is exactly wrong? The error from pg is so disappointing...

**Comment by LeKovr** [comment]
No, this is invalid SQL.
You should use this
```
SELECT * FROM "user"  LEFT JOIN "watch" ON "user".id=watch.user_id WHERE repo_id=1;
```
or even
```
SELECT * FROM "user" u LEFT JOIN "watch" ON u.id=watch.user_id WHERE repo_id=1;
```

**Comment by Unknwon** [comment]
Thanks, the `user` is the problem I'm thinking.

Does 

```
SELECT * FROM "user"  LEFT JOIN "watch" ON `user`.id=watch.user_id WHERE repo_id=1;
```

would work?

**Comment by LeKovr** [comment]
Nope, only double quotes allowed. And `user` must be doublequoted - it is keyword

**Comment by Unknwon** [comment]
Hi, can you checkout `develop` branch and help test?

**Comment by LeKovr** [comment]
Yes I can)

**Comment by LeKovr** [comment]
Develop branch works fine. Thank you, Unknwon!

**Comment by Unknwon** [comment]
:clap: Thanks your confirmation!

**Comment by kolesar-andras** [comment]
I have got the same error 500, and the same message in xorm.log. Thank you for the fix.
