### ISSUE TITLE
Format warning in Russan translation

### ISSUE THREAD

**Issue by LeKovr** [gogits/gogs#2178]
At issue page only in Russian translation showed warning `%! (template.HTML=`.

### En screenshot:

![fmt_en](https://cloud.githubusercontent.com/assets/1528068/11768684/6912b5f6-a1e5-11e5-8603-e68f8f6cdf7b.png)

### Ru screenshot:

![fmt_ru_error](https://cloud.githubusercontent.com/assets/1528068/11768696/8d2d9e42-a1e5-11e5-88ac-2c55c4161e7b.png)

**Comment by stonerl** [comment]
Which version are you using. I cannot reproduce this on https://try.gogs.io

**Comment by LeKovr** [comment]
0.8.0.1212 
I reprodice it -
https://try.gogs.io/LeKovr/sample1512/issues/1

**Comment by stonerl** [comment]
What browser are you using? 
Here is a screenshot from Firefox 42 and it looks fine to me:
![screenshot-try gogs io 2015-12-13 21-07-15](https://cloud.githubusercontent.com/assets/2091312/11768989/b40dbb94-a1dd-11e5-9dfd-d9016395ced8.png)

**Comment by stonerl** [comment]
I also tried it with Safari 9.0.2 and Chrome 47 and can't see anything wrong.

**Comment by LeKovr** [comment]
FF 42 on Ubuntu 14.04
But I guess it does not matter.  It is the same on Chromium 47.0.2526.73 Ubuntu 14.04 (64-bit)
![chromium](https://cloud.githubusercontent.com/assets/1528068/11769025/3ca89bfc-a1ef-11e5-8dbf-93598114b675.png)

BTW, I sad - Russian only, in other langs all ok

**Comment by stonerl** [comment]
I know, I tested in Russian. And it looks fine here, with all the browsers I can test with. Strange...

**Comment by stonerl** [comment]
Oh Sorry. I'm stupid. Your right. It appears here as well.

**Comment by LeKovr** [comment]
This is a source for Russian:
```
<span class="time-desc">
			
				%! (template.HTML=<span class="time-since" title="Sun, 13 Dec 2015 15:05:01 EST">минут назад: 22</span>)открыта <a href="/LeKovr">LeKovr</a>
			
			·
			комментариев: 0
		</span>
```
and for English:
```
<span class="time-desc">
			
				opened <span class="time-since" title="Sun, 13 Dec 2015 15:05:01 EST">21 minutes ago</span> by <a href="/LeKovr">LeKovr</a>
			
			·
			0 comments
		</span>
```

**Comment by LeKovr** [comment]
Problem was located and solution exists already (missing `s` in `%[1]`).
I vote for right choice here - https://crowdin.com/translate/gogs/1/enus-ru#q=issues.opened_by

**Comment by stonerl** [comment]
Glad you found it. :clap:

**Comment by Unknwon** [comment]
@LeKovr thank you! Approved.
