### ISSUE TITLE
Cannot add SSH key when running via systemd

### ISSUE THREAD

**Issue by david-at** [gogits/gogs#2179]
OS: CentOS 7. I have a systemd script setup to start gogs, when I am running via that systemd script I cannot add ssh keys and get the following error: 

Sorry, we're not able to verify your SSH key: ssh-keygen -lf: ssh-keygen: /tmp/keytest422813223: Permission denied

If I run the service by hand it works fine: sudo ./gogs web

Here is my systemd service: 

```
[Unit]
Description=Gogs (Go Git Service)
After=syslog.target
After=network.target
#After=mysqld.service
#After=postgresql.service
#After=memcached.service
#After=redis.service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/home/gogs/gogs
ExecStart=/home/gogs/gogs/gogs web
Restart=always
Environment=USER=root HOME=/home/gogs

[Install]
WantedBy=multi-user.target
```

Originally I had it setup to use the gogs user,  but for testing I switched it to root. Still no luck.

**Comment by Unknwon** [comment]
This is the sysmted config for demo site:

```
[Unit]
Description=Gogs - try.gogs.io
After=syslog.target
After=network.target
After=mysqld.service

[Service]
User=git
Group=git
WorkingDirectory=/home/git/apps/gogs
ExecStart=/home/git/apps/gogs/gogs web
Restart=always
Environment="USER=git","HOME=/home/git"

[Install]
WantedBy=multi-user.target
```

Compare two versions, I think the problem is `Type=simple` even though I don't know what it does.

**Comment by xor-gate** [comment]
`Type=simple` means the process stays in the foreground and wont fork. The default when omitted is `Type=simple` which is good in both of you.

http://www.freedesktop.org/software/systemd/man/systemd.service.html#Options

I think the problem is here:

```
Environment=USER=root HOME=/home/gogs
vs
Environment="USER=git","HOME=/home/git"
````

@david-at see if this works.

**Comment by Unknwon** [comment]
@xor-gate thanks your help!

**Comment by xor-gate** [comment]
Have a deep look how `Environment=` is expanded: http://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines

**Comment by Unknwon** [comment]
Close for lacking of feedback.

**Comment by david-at** [comment]
Sorry for just now getting to this.

I updated the conf with the env settings, and still no luck: 

```
[Unit]
Description=Gogs (Go Git Service)
After=syslog.target
After=network.target
#After=mysqld.service
#After=postgresql.service
#After=memcached.service
#After=redis.service

[Service]
Type=simple
User=gogs
Group=gogs
WorkingDirectory=/home/gogs/gogs
ExecStart=/home/gogs/gogs/gogs web
Restart=always
Environment="USER=gogs",HOME="/home/gogs"

[Install]
WantedBy=multi-user.target
```

**Comment by Unknwon** [comment]
Hi,

> Sorry, we're not able to verify your SSH key: ssh-keygen -lf: ssh-keygen: /tmp/keytest422813223: Permission denied

Is it possible to verify key if you start at terminal?

**Comment by david-at** [comment]
Yes. I tested with a brand new key.

**Comment by Unknwon** [comment]
> Environment="USER=gogs",HOME="/home/gogs"

Shouldn't this line be 

`Environment="USER=gogs","HOME=/home/gogs"`?

**Comment by david-at** [comment]
Oh jeez Louise. Let me test and I will report back.

**Comment by david-at** [comment]
Still no luck. leaving an updated copy of the systemd script:

```
[Unit]
Description=Gogs (Go Git Service)
After=syslog.target
After=network.target
#After=mysqld.service
#After=postgresql.service
#After=memcached.service
#After=redis.service

[Service]
User=gogs
Group=gogs
WorkingDirectory=/home/gogs/gogs
ExecStart=/home/gogs/gogs/gogs web
Restart=always
Environment="USER=gogs","HOME=/home/gogs"

[Install]
WantedBy=multi-user.target
```

**Comment by Unknwon** [comment]
Does user `gogs` has permission to create tmp files?

**Comment by david-at** [comment]
Yup.

**Comment by Unknwon** [comment]
Does Gogs has permission to execute `ssh-keygen`?

**Comment by david-at** [comment]
Yes. It works fine when I run the executable from a session as the gogs user

**Comment by Unknwon** [comment]
OK... I have no idea, but someone else has sent a patch for using another way to verify SSH keys.

I'll come back to this issue later.

**Comment by Unknwon** [comment]
```diff
models/ssh_key.go | 40 +--------------------------------------- 
1 file changed, 1 insertion(+), 39 deletions(-) 

diff --git a/models/ssh_key.go b/models/ssh_key.go 
index f0db4de..60d73e2 100644 
--- a/models/ssh_key.go 
+++ b/models/ssh_key.go 
@@ -164,48 +164,10 @@ func CheckPublicKeyString(content string) (_ string, err error) { 
 	return "", errors.New("only a single line with a single key please") 
 	} 
  
-	// write the key to a file… 
-	tmpFile, err := ioutil.TempFile(os.TempDir(), "keytest") 
+	_, err = ssh.ParsePublicKey(content) 
 	if err != nil { 
 	return "", err 
 	} 
-	tmpPath := tmpFile.Name() 
-	defer os.Remove(tmpPath) 
-	tmpFile.WriteString(content) 
-	tmpFile.Close() 
- 
-	// Check if ssh-keygen recognizes its contents. 
-	stdout, stderr, err := process.Exec("CheckPublicKeyString", "ssh-keygen", "-lf", tmpPath) 
-	if err != nil { 
-	return "", errors.New("ssh-keygen -lf: " + stderr) 
-	} else if len(stdout) < 2 { 
-	return "", errors.New("ssh-keygen returned not enough output to evaluate the key: " + stdout) 
-	} 
- 
-	// The ssh-keygen in Windows does not print key type, so no need go further. 
-	if setting.IsWindows { 
-	return content, nil 
-	} 
- 
-	sshKeygenOutput := strings.Split(stdout, " ") 
-	if len(sshKeygenOutput) < 4 { 
-	return content, ErrKeyUnableVerify{stdout} 
-	} 
- 
-	// Check if key type and key size match. 
-	if !setting.Service.DisableMinimumKeySizeCheck { 
-	keySize := com.StrTo(sshKeygenOutput[0]).MustInt() 
-	if keySize == 0 { 
-	return "", errors.New("cannot get key size of the given key") 
-	} 
- 
-	keyType := strings.Trim(sshKeygenOutput[len(sshKeygenOutput)-1], " ()\n") 
-	if minimumKeySize := setting.Service.MinimumKeySizes[keyType]; minimumKeySize == 0 { 
-	return "", fmt.Errorf("unrecognized public key type: %s", keyType) 
-	} else if keySize < minimumKeySize { 
-	return "", fmt.Errorf("the minimum accepted size of a public key %s is %d", keyType, minimumKeySize) 
-	} 
-	} 
  
 	return content, nil 
}
```

**Comment by barracks510** [comment]
Hi. I am the author of the patch. On all RedHat systems with SELinux enabled, SELinux prevents the keytest from operating on `/tmp`. This only applies when gogs is running as a systemd service and has nothing to do with the environment. It is unwise and unnecessary to run any service including gogs as a root user.

You can temporarily allow ssh-keytest to operate under `/tmp` by executing the following as root to add to the stock SELinux policy.
```
cat /var/log/audit/audit.log | grep denied | grep ssh | audit2allow -M gogs-ssh
semodule -i gogs-ssh.pp
```
However, this is not ideal, and the patch provides a more permanent solution.

**Comment by Unknwon** [comment]
@barracks510 thank you again!

Will merge this patch ASAP.

**Comment by Unknwon** [comment]
@barracks510 I don't know why, but `ssh.ParsePublicKey` always returns `ssh: short read` error...

**Comment by barracks510** [comment]
Sorry about that. I have sent you another patch that should fix the issue.

**Comment by Unknwon** [comment]
@barracks510 thanks. It would be much easier for me to just post patch here actually.

**Comment by Unknwon** [comment]
```diff
 models/ssh_key.go | 42 +++--------------------------------------- 
 1 file changed, 3 insertions(+), 39 deletions(-) 

diff --git a/models/ssh_key.go b/models/ssh_key.go 
index f0db4de..9ae2b82 100644 
--- a/models/ssh_key.go 
+++ b/models/ssh_key.go 
@@ -25,6 +25,7 @@ import ( 
 	"github.com/gogits/gogs/modules/log" 
 	"github.com/gogits/gogs/modules/process" 
 	"github.com/gogits/gogs/modules/setting" 
+	"golang.org/x/crypto/ssh" 
 ) 
  
 const ( 
@@ -164,48 +165,11 @@ func CheckPublicKeyString(content string) (_ string, err error) { 
 	return "", errors.New("only a single line with a single key please") 
 	} 
  
-	// write the key to a file… 
-	tmpFile, err := ioutil.TempFile(os.TempDir(), "keytest") 
+	key, err := base64.StdEncoding.DecodeString(strings.Fields(content)[1]) 
+	_, err = ssh.ParsePublicKey([]byte(key)) 
 	if err != nil { 
 	return "", err 
 	} 
-	tmpPath := tmpFile.Name() 
-	defer os.Remove(tmpPath) 
-	tmpFile.WriteString(content) 
-	tmpFile.Close() 
- 
-	// Check if ssh-keygen recognizes its contents. 
-	stdout, stderr, err := process.Exec("CheckPublicKeyString", "ssh-keygen", "-lf", tmpPath) 
-	if err != nil { 
-	return "", errors.New("ssh-keygen -lf: " + stderr) 
-	} else if len(stdout) < 2 { 
-	return "", errors.New("ssh-keygen returned not enough output to evaluate the key: " + stdout) 
-	} 
- 
-	// The ssh-keygen in Windows does not print key type, so no need go further. 
-	if setting.IsWindows { 
-	return content, nil 
-	} 
- 
-	sshKeygenOutput := strings.Split(stdout, " ") 
-	if len(sshKeygenOutput) < 4 { 
-	return content, ErrKeyUnableVerify{stdout} 
-	} 
- 
-	// Check if key type and key size match. 
-	if !setting.Service.DisableMinimumKeySizeCheck { 
-	keySize := com.StrTo(sshKeygenOutput[0]).MustInt() 
-	if keySize == 0 { 
-	return "", errors.New("cannot get key size of the given key") 
-	} 
- 
-	keyType := strings.Trim(sshKeygenOutput[len(sshKeygenOutput)-1], " ()\n") 
-	if minimumKeySize := setting.Service.MinimumKeySizes[keyType]; minimumKeySize == 0 { 
-	return "", fmt.Errorf("unrecognized public key type: %s", keyType) 
-	} else if keySize < minimumKeySize { 
-	return "", fmt.Errorf("the minimum accepted size of a public key %s is %d", keyType, minimumKeySize) 
-	} 
-	} 
  
 	return content, nil 
 }
```

**Comment by barracks510** [comment]
Ok. I will keep that in mind with future patches. Would you be against a rewrite of the ssh_keys.go file to use the Google maintained golang.org/x/crypto/ssh library?

**Comment by Unknwon** [comment]
@barracks510 

> Google maintained golang.org/x/crypto/ssh library?

Which one?

**Comment by barracks510** [comment]
I believe that the golang project (and thereby Google) maintains the golang.org/x/ repository as a staging code. The following excerpt is from the website. 
> These packages are part of the Go Project but outside the main Go tree. They are developed under looser compatibility requirements than the Go core.

**Comment by Unknwon** [comment]
@barracks510 Gogs is using the one you're talking...

**Comment by Unknwon** [comment]
@barracks510 your code works right now, thanks again!

@david-at would you mind checkout `develop` and test again?

**Comment by barracks510** [comment]
@Unknwon I believe the built in SSH module is using the Google crypto libs, but there is a lot of duplicate code being written in the model/ssh_keys.go file that has only just included the Google crypto libs.

**Comment by Gibheer** [comment]
@Unknwon that patch removed the ability to blacklist specific kinds of keys and minimum key lengths. I will create a patch to add it again, as I and some others were using the feature. Is that okay with you?

Apart from that, I think we should support both ssh-keygen and golang ssh. When the system sshd is used, we should also accept keys the server supports, so use ssh-keygen. When using the internal server, we should only allow these keys.

Also, I will try to figure out, what exactly went wrong with @david-ats setup.

**Comment by david-at** [comment]
@Gibheer It was specifcially the SELinux issue, I used audit2allow to create a rule to allow ssh-keygen in /tmp.

Would a better solution be to move the check/tmp folder into the gogs directory? I know we're not talking about it, but I think it would never be acceptable to disable SELinux.

**Comment by mhartkorn** [comment]
`golang.org/x/crypto/ssh` does not support ed25519 keys, yet. At least adding them is not possible in `0.8.22.0115`. See golang/go#8581

**Comment by barracks510** [comment]
Gitlabs &ldquo;solved&rdquo; this problem in [this commit](https://gitlab.com/ashby/omnibus-gitlab/commit/89bc0bf45a2728c54cb7dd36cb2b993c622aedb0) by inserting a new SELinux policy module to allow ssh-keygen to operate on `/tmp`. To me, this is unacceptable as a permanent solution on production systems. I would much rather sacrifice the use of EdDSA keys than to allow a Gogs service to inject SELinux modules. Perhaps there should be an option in the configuration to allow the systems administrator to determine what is optimal for his/her setup.

**Comment by Unknwon** [comment]
@Gibheer 

> @Unknwon that patch removed the ability to blacklist specific kinds of keys and minimum key lengths. I will create a patch to add it again, as I and some others were using the feature. Is that okay with you?

Yes of course if you know how to achieve that.

> Apart from that, I think we should support both ssh-keygen and golang ssh. When the system sshd is used, we should also accept keys the server supports, so use ssh-keygen. When using the internal server, we should only allow these keys.

SSH key verification does not relate to builtin server or external SSH server... but what we could provide an option to let user choose which one to use? This could also solve problem @mhartkorn describes.

**Comment by Unknwon** [comment]
@david-at focus on this issue specifically, does the validation problem have been solved?

**Comment by Gibheer** [comment]
On Mon, 25 Jan 2016 10:31:50 -0800
无闻 <notifications@github.com> wrote:

> @Gibheer 
> 
>  [...]  
> 
> Yes of course if you know how to achieve that.
> 
>  [...]  
> 
> SSH key verification does not relate to builtin server or external
> SSH server... but what we could provide an option to let user choose
> which one to use? This could also solve problem @mhartkorn describes. 

The SSH key verification does relate to the builtin server as long as
both implementations can't handle all key types.
At the moment the go ssh implementation does not handle DES and ed25519
keys (wether one wants to use DES or not).
I would therefore make it the default to use ssh-keygen when using the
system sshd, but use the golang library when using the internal sshd.
This way, gogs will check only the keys which are supported by the
server implementation.

Further, I would add two options. The first is to adjust the checker to
either use ssh-keygen or the golang one, independant which sshd is used.

The next option is to override where the temporary files for ssh-keygen
are placed, to make it possible to use it with SELinux.

After I have that working, I will add back the public key filter. It
should be possible to build an API on top of both, the golang lib and
ssh-keygen output, to make this easily possible. Most of the stuff
already existed and I will revive it from git history :)

**Comment by Gibheer** [comment]
As a small update, I am working on the issue, but it will take much longer than expected. The ssh key API is not built in a way, that it is easily usable. To make things easier, I wanted to use as much from their API as possible, but much of what I need is hidden or not even available. So that will take some more time to figure out.
The other thing taking up time at the moment are private matters, but I hope I can get a working piece delivered in 2 to 4 weeks.

**Comment by Unknwon** [comment]
@Gibheer which way are you working on? 

I think revert back the delete code (old approach) and make two methods of validation both exist and a config option to let user choose should fix the problem?

**Comment by Gibheer** [comment]
@Unknwon that was my initial plan, but the golang ssh code doesn't provide a way to check the key length, which the other part I wanted to restore. I'm currently trying to figure out if I can implement that feature somehow or not.

**Comment by Unknwon** [comment]
@Gibheer OK. That's a good try!

As the old approach had been used for a fairly long time, revert that back wouldn't hurt. (I might do that first, but if you just work on check key length, then our work shouldn't have conflict parts)

**Comment by Gibheer** [comment]
Yes, I could just restore the previous behavior, but I would like to not break stuff for people again :) My pull request will come when I have worked out a way, that it works for most people without problems with the next update.

**Comment by Unknwon** [comment]
OK, new methods are implemented now in `develop` branch, everyone watches on this thread please help test!!!

**Comment by Unknwon** [comment]
This post may help as well: https://discuss.gogs.io/t/how-to-config-ssh-settings/34

**Comment by Unknwon** [comment]
OK, at this point, close as fixed.

**Comment by quirxmode** [comment]
So how is this fixed? What am I supposed to do? If i set the SSH_KEY_TEST_PATH e.g. to
`SSH_KEY_TEST_PATH = /home/git/tmp`
i get a 500 server error, and the log says
`2016/07/21 21:20:16 [...ters/user/setting.go:335 SettingsSSHKeysPost()] [E] AddPublicKey: addKey: 'ssh-keygen -lf /tmp/230725223/id_rsa.pub' failed with error 'exit status 255': ssh-keygen: /tmp/230725223/id_rsa.pub: Permission denied`
which is interestingly not the directory that was specified in the configuration. Am I doing it wrong?

**Comment by david-at** [comment]
quirxmode: Are you using the SSH server built into gogs or the ssh server that comes with your box? 

SSH_KEY_TEST_PATH will only work with the built in SSH server. If you want to use the SSH server that comes with your box, you will either need to disable SELinux or make an exception for Gogs as listed earlier by barracks510:

`cat /var/log/audit/audit.log | grep denied | grep ssh | audit2allow -M gogs-ssh
semodule -i gogs-ssh.pp`

**Comment by quirxmode** [comment]
oh :( Is there a special reason it only works with the built-in server?

**Comment by david-at** [comment]
@Unknwon : should there probably be documentation added for SSH_KEY_TEST_PATH? I don't see it on the cheat sheet? https://gogs.io/docs/advanced/configuration_cheat_sheet If so it should probably be a new issue.

**Comment by david-at** [comment]
@quirxmode Because gogs doesn't control the SSH server on the box :)

**Comment by quirxmode** [comment]
`SSH_KEY_TEST_PATH` is only the path used by the `ssh-keygen` command, which seems to be executed the same way no matter which ssh server you are using, or am i completely wrong?

**Comment by david-at** [comment]
@quirxmode wanted to make sure I had the right info: so yes the test function does not evauluate the SSH_KEY_TEST_PATH when using ssh-keygen:

https://github.com/gogits/gogs/blob/004fb30ebe403625b2315b284a85124611ba303b/models/ssh_key.go#L198

**Comment by LukasMa** [comment]
I just wanted to report: I installed gogs on a fresh CentOS 7 installation and I had to apply the SELinux policy described above to make it work!

**Comment by chrisniael** [comment]
https://www.pyrosoft.co.uk/blog/2013/01/12/setting-up-ssh-authorized_keys-with-selinux-enabled/
