### ISSUE TITLE
GRAVATAR disabled but user links to gravatar.com

### ISSUE THREAD

**Issue by kernel164** [gogits/gogs#2180]
**Settings:**
DISABLE_GRAVATAR = true

**Issue:**
On click of user profile picture (@url: http://gogs:3000/user1 ), the links goes to http://gravatar.com/emails/

**Expected:**
On click of user profile picture (@url: http://gogs:3000/user1 ), nothing should happen.

**Comment by Unknwon** [comment]
Please test `develop` branch or on https://try.gogs.io

**Comment by Unknwon** [comment]
Close as fixed.
