### ISSUE TITLE
Ability to delete wiki page and entire data

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2183]
I created a new wiki for testing purposes. After testing, I couldn't find how to delete this wiki so I ended up deleting it from my filesystem. This appeared to work. However now,  when trying to create a new wiki a wild 500 error page appears. 

Second time creating a wiki page
```
2015/12/14 00:02:19 [...routers/repo/wiki.go:215 NewWikiPost()] [E] AddWikiPage: UpdateLocalWiki: Pull: exit status 1 - You asked to pull from the remote '--all', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
```

After the above error this will be shown when you try to access the wiki page. 
```
2015/12/14 00:02:28 [...routers/repo/wiki.go:53 renderWikiPage()] [E] GetBranchCommit: exit status 128 - fatal: 'refs/heads/master' - not a valid ref
```

Version number: 
```
0.8.0.1212
```

**Comment by Unknwon** [comment]
> I couldn't find how to delete this wiki so I ended up deleting it from my filesystem

This is not acceptable action as you may break internal process of Gogs and didn't clean up all the places.

I suggest you consider change purpose of issue to be `ability to delete wiki page and entire data`.

**Comment by drsect0r** [comment]
Noted :+1: 

How could I resolve this however?

**Comment by Unknwon** [comment]
Change database table `repository` filed `enable_wiki` to false, and delete `path/to/gogs/data/tmp/local-wiki`

**Comment by drsect0r** [comment]
Thanks, much appreciated!

**Comment by Unknwon** [comment]
:smiley:

**Comment by seferis101** [comment]
As a reminder - copy from description of [Feature request: Delete a page in gogs-wiki](https://github.com/gogits/gogs/issues/2698):

Feature request / user story:

As a user of gogs (my version is 0.8.10.1217), I would like to delete a page from the gogs-wiki of my repository. I want to be asked by the system if I really want to delete the page, before the page is actually deleted.

Possible way to achieve this:
Provide a remove button next to the already existing buttons "Edit" and "New Page" on the wiki-page the user wants to delete. When this button is pressed a confirmation popup is shown which asks "Do you really want to delete this page?" (yes/no). If yes is chosen the page is deleted and removed from the wiki-repository. If no is chosen the confirmation popup disappears and nothing happens.

**Comment by Unknwon** [comment]
Erase entire wiki data is now working both on `develop` branch and https://try.gogs.io/, please help test!

**Comment by Unknwon** [comment]
OK, you should be able to test it on `develop` branch or https://try.gogs.io

**Comment by Unknwon** [comment]
Close as implemented.

**Comment by drsect0r** [comment]
Thanks! Awesome @Unknwon

**Comment by seferis101** [comment]
Works fine since pages can now be deleted from git by removing the .md file and committing this change. Unfortunately, there is still no direct button in the Wiki-GUI which triggers the removal of the corresponding wiki page.
