### ISSUE TITLE
New Screencast Install Gogs on Linux

### ISSUE THREAD

**Issue by jniltinho** [gogits/gogs#2186]
First screencast come to the Gogs
https://www.youtube.com/watch?v=4UkHAR1F7ZA

@Unknwon 
Congratulations on Gogs project
Thank's

**Comment by jniltinho** [comment]
Install Gogs on Linux
https://gist.github.com/jniltinho/280573e10206e31ab1c7

**Comment by Unknwon** [comment]
Thanks, will update link on README.

Next time, please post these info on http://forum.gogs.io/category/3/show-tell :sailboat:

**Comment by jniltinho** [comment]
Very good forum @Unknwon
