### ISSUE TITLE
Ability to retrigger webhook history

### ISSUE THREAD

**Issue by freshcn** [gogits/gogs#2187]
when we use web hook to deploy out program,sometimes the network has timeout. may be gogs should try again later?

**Comment by Unknwon** [comment]
No, try again is a sounds cool but complicated things a lot feature.

You may want to increase timeout, or change the purpose of this issue to be `Ability to trigger resent webhook`

**Comment by freshcn** [comment]
that cool

**Comment by Unknwon** [comment]
I have changed the title for you. :sailboat:

**Comment by scofieldpeng** [comment]
都是中国人,却用英语来交流,这是一种什么样的体验...

**Comment by Unknwon** [comment]
Because other users may have the same issue/question.

**Comment by scofieldpeng** [comment]
ok...

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
