### ISSUE TITLE
GetSubModule: object does not exist

### ISSUE THREAD

**Issue by silverwind** [gogits/gogs#2188]
Pushed my first (big) repo to an org, got the following error which seems to persist after reloading the server:

```
2015/12/14 06:02:19 [...routers/repo/view.go:151 Home()] [E] GetSubModule: GetTreeEntryByPath: error not exist
```

Gogs Version: 0.7.33.1205 Beta
Server version: 10.1.9-MariaDB-log MariaDB Server

**Comment by Unknwon** [comment]
Thanks your feedback!

What does this submodule looks like? Can you reproduce on https://try.gogs.io ?

**Comment by silverwind** [comment]
I'm not using any git submodules, basically just a directory with a few thousand files added through `git add --all` and pushed. While I can't push my private data to your server, I'll see tomorrow if I can reproduce with a smaller subset of data first.

**Comment by Unknwon** [comment]
No problem.

**Comment by silverwind** [comment]
Updated to 0.8.0, the error is now slightly different:

```
2015/12/14 15:10:13 [...routers/repo/view.go:149 Home()] [E] GetSubModule: object does not exist [id: , rel_path: .gitmodules]
```

**Comment by Unknwon** [comment]
@silverwind Thanks for following up!

Any progress on reproducing this on https://try.gogs.io?

**Comment by silverwind** [comment]
I didn't realize a repo inside another repo was autmatically identified as a submodule. The troubling submodule was a clone of http://sdelements.github.io/lets-chat/. Removing it from the commit fixed the issue. I then tried to push the exact repo to the try server but couldn't reproduce anymore unfortunately, no matter what I tried.

I'll close this, thanks for the quick response!

**Comment by Unknwon** [comment]
Hmm.... thanks :trollface:
