### ISSUE TITLE
windows service could not be started using nssm with 0.8.0, but 0.7.33 is ok.

### ISSUE THREAD

**Issue by bygreencn** [gogits/gogs#2189]

**Comment by Unknwon** [comment]
Hi, the way Gogs supports Windows service in since 0.8 has been changed: https://gogs.io/docs/installation/install_gogs_on_windows#run-gogs-as-a-service

**Comment by andreynering** [comment]
Same here. v0.8.0 simply doesn't work anymore. v0.7.33 is OK.

> The way Gogs supports Windows service in since 0.8 has been changed.

Does this mean using Gogs with NSSM was discontinued?

**Comment by Unknwon** [comment]
> Does this mean using Gogs with NSSM was discontinued?

Actually I don't know how and why NSSM was working... but recommend way right is using the builtin ability.

**Comment by bygreencn** [comment]
useing nssm to building as service run at Local Area Network not just local machine, the configuration file is the same for 0.7.33 and 0.8.0, the first is running correctly, but the second failed.
run_user is an user at win7 system and configure at service correct.

**Comment by Unknwon** [comment]
@bygreencn please read my comments.

**Comment by bygreencn** [comment]
@Unknwon Yes, but i really think something was wrong at version 0.8.0.

**Comment by Unknwon** [comment]
This is the only change relates to Windows: https://github.com/gogits/gogs/pull/2133/files

**Comment by Unknwon** [comment]
I really know nothing about Windows service, maybe you guys can help...

**Comment by bygreencn** [comment]
@Unknwon yeah, i think gogs and nssm also set and check the service status, which cause nssm decide the service failed, but the minwinsvc service stub run not correctly. Maybe it is not the best choice.

**Comment by Unknwon** [comment]
Another person has the exactly same problem, he used to use NSSM, but he has successfully changed to minwinsvc now.

**Comment by bygreencn** [comment]
Also could you please give some manual to compile gogs at windows platform, i want to build it from myself and cancel this pull request. thanks a lot!!!

**Comment by andreynering** [comment]
@Unknwon 

I think is kind of potentially breaking change should be tested by more people.

You can always have it in an separated branch first and tell people to test it. If we have sure it works, so it can be merged.

**Comment by Unknwon** [comment]
@bygreencn the docs are pretty much same for Windows, just replace some commands that are not available for Windows: https://gogs.io/docs/installation/install_from_source

@andreynering not many people will test until things break...

**Comment by Unknwon** [comment]
OK... the ultimate solution again, maybe we should add a build tag?

**Comment by Unknwon** [comment]
The question is ... if miniwinsvc does do the work, just change NSSM to this is just once forever change.

**Comment by andreynering** [comment]
I never used miniwinsvc before. I don't even know how it work.

**Comment by Unknwon** [comment]
The link I gave described how it works: https://gogs.io/docs/installation/install_gogs_on_windows#run-gogs-as-a-service

**Comment by andreynering** [comment]
I tried commenting [the import line](https://github.com/gogits/gogs/blob/master/gogs.go#L15) and NSSM worked again. It seems that we can't use both at the same time.

**Comment by Unknwon** [comment]
So...... do we need a tag to disable this line?

**Comment by andreynering** [comment]
> So...... do we need a tag to disable this line?

Is it possible to make this import optional while compiling? If yes, I think it would be good, at least for some more releases, so people have more time to migrate to the new service mode.

**Comment by Unknwon** [comment]
> Is it possible to make this import optional while compiling? 

Yes, but it does not solve the problem actually... as every binary release will include all tags possible.

**Comment by Unknwon** [comment]
Any updates?

**Comment by andreynering** [comment]
I think if you want to support both NSSM and native service you will need to make two separated binaries.

**Comment by Unknwon** [comment]
Looks like so... :sob:

**Comment by Unknwon** [comment]
OK, now in `develop` branch, need use tags `miniwinsvc` to enable builtin support, and by default it supports NSSM.

**Comment by Unknwon** [comment]
https://gogs.io/docs/installation/run_as_windows_service
