### ISSUE TITLE
Not all branches are listed on gogs

### ISSUE THREAD

**Issue by pentix** [gogits/gogs#2190]
I have a local repository with multiples remotes set up. One of these remotes is a gogs server (gogs 0.7.22.1125 Beta / git version 1.7.10.4). Let's call those remotes `remoteA` and `remoteB`, where `remoteA` is the gogs server.

As you know git maintains remotes as branches. For example the *master* branch from `remoteA` is a local branch called `remoteA/master`

Now I just pushed my local branch `remoteB/master` to remote A:
`git push remoteA remoteB/master`

git showed that the refs were submitted to the server:
`[new branch]      remoteB/master -> remoteB/master`

But gogs does not display this branch in the list... I guess it is because `git branch` per default doesn't show *all* branches.

If I open ssh to the server and check the repo where it is saved by gogs I can see the branch.
(Using `git branch --all`)

**Comment by Unknwon** [comment]
Hi,

> Now I just pushed my local branch remoteB/master to remote A:
git push remoteA remoteB/master

It looks you're pushing `remote A` to `remoteB/master`... just opposite of what you say...

**Comment by pentix** [comment]
Hi

As far as I know the syntax is `git push {remote} {branch1 branch2 branch3}`
so `git push remoteA remoteB/master` would push B's master to remoteA. Am I wrong?

**Comment by pentix** [comment]
I could reproduce it creating an empty repo on try.gogs.net (Gogs Version: 0.8.4.1214).
Pushed all refs using `git push --mirror remoteC`

**Comment by Unknwon** [comment]
You're right...

**Comment by Unknwon** [comment]
Can you post link on try.gogs.io?

**Comment by pentix** [comment]
Sure, here you go: https://try.gogs.io/pentix/space/

**Comment by Unknwon** [comment]
Thanks!

Which branch you're expecting to see but missing?

**Comment by Unknwon** [comment]
OK... I think you have ran into conflict of branch naming... I think branches start with `remotes/` is convention of non-local branches, which Gogs is right about not showing them.

**Comment by pentix** [comment]
Hmm okay, I can remember cgit as well as github showing them... Would you mind adding an option
in gogs config **[ ] Display remote branches as well**

Anyway, thanks! :)

**Comment by Unknwon** [comment]
> Hmm okay, I can remember cgit as well as github showing them

Can you create an example repository on GitHub?

**Comment by pentix** [comment]
You're right, GitHub doesn't show branches like `remoteB/dev`  anymore...

**Comment by Unknwon** [comment]
:joy: so... what now...?

**Comment by pentix** [comment]
It is up to you whether you'd like to have an option to show these branches or not :smiley:

**Comment by Unknwon** [comment]
Theoretically, unless it's a mirror repository, there is no remote needed for repositories managed by Gogs, because it is already the remote to your local. Closing it now. :sailboat:
