### ISSUE TITLE
When the new user registers browser shouldn't ask to memorize the password for /user/sign_up screen

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2193]
Browser asks to memorize the login/password twice. /user/sign_up isn't necessary. /user/login  is okay.

Observed in chrome.

**Comment by Unknwon** [comment]
This is the automatically behavior of browser as submitting a form.

I consider this is invalid issue until more strong proves.

**Comment by yurivict** [comment]
Here they claim that autocomplete="off" disables memorization. There is also some other solution mentioned there.

But I can't test this easily.

http://stackoverflow.com/questions/32369/disable-browser-save-password-functionality

**Comment by Unknwon** [comment]
`autocomplete="off"` disables memorization but I don't think it is the same thing.

BTW, it does not work based on my quick test.
