### ISSUE TITLE
problem start gogs due to libpam.so.0

### ISSUE THREAD

**Issue by limbo-lab** [gogits/gogs#2194]
I'm using the latest binary package and when I run:

```bash
./gogs
```

outputs:
```bash
./gogs: error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory
```

then I install `libpam-dev`:
```bash
apt-get install libpam-dev
```

but complains as usual.

**Comment by Unknwon** [comment]
Thanks your feedback!

You may want report this to https://github.com/msteinert/pam .

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close as lack of feedback.

**Comment by Semyazz** [comment]
Had the same issue when I tired to launch it on 64-bits linux. Fixed after installing libpam-dev:i368 library

```
apt-get install libpam-dev:i386
```

**Comment by chingli** [comment]
This may happen when installing a i386 version of gogs on a amd64 linux release.
