### ISSUE TITLE
Very large text files shouldn't be just displayed

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2195]
This is an example: https://github.com/mattn/go-sqlite3/blob/master/code/sqlite3-binding.c

Instead of just truncating, you can load the file in portions when the user scrolls. This would be better than GitHub.

**Comment by xor-gate** [comment]
In my opinion the behaviour of github is not bad because you are doing weird things when you want to view large (source) files. This introduces more complexity in the backend and UI to have chunk file viewing which can break.

**Comment by Unknwon** [comment]
I think this issue is solved.
