### ISSUE TITLE
Visual issue when changing organization full name

### ISSUE THREAD

**Issue by KillTheIdols** [gogits/gogs#2197]
When adding apostrophes to an organization title it results in it being displayed/encoded as:
```
&#39;
```

Even when manually changing in the database it still displays this, so I'm assuming there's an encoding error.

Not a major issue.

Running version: 0.8.3.1213

**Comment by xxxtonixxx** [comment]
This has just been reported here #1937

**Comment by KillTheIdols** [comment]
Oops, I tried to search but no results. Thanks. :+1:
