### ISSUE TITLE
Syntax highlight class for e.g CMake (and others)

### ISSUE THREAD

**Issue by xor-gate** [gogits/gogs#2199]
I see gogs uses highlight.js and CMake is supported (build framework) used in C/C++ style projects.

When gogs sees one of the following files it could highlight with CMake markup: 
* `CMakeLists.txt` (with correct casing)
* `*.cmake`

I search through the gogs sourcecode but as far as I can tell you let highlight.js automatic select the syntax highlighting and dont set the div class attribute as specified here: https://highlightjs.org/usage/

**Comment by Unknwon** [comment]
How does a normal `CMakeLists.txt` looks like?

**Comment by xor-gate** [comment]
Example from https://highlightjs.org/static/demo:
```cmake
cmake_minimum_required(VERSION 2.8.8)
project(cmake_example)

# Show message on Linux platform
if (${CMAKE_SYSTEM_NAME} MATCHES Linux)
    message("Good choice, bro!")
endif()

# Tell CMake to run moc when necessary:
set(CMAKE_AUTOMOC ON)
# As moc files are generated in the binary dir,
# tell CMake to always look for includes there:
set(CMAKE_INCLUDE_CURRENT_DIR ON)

# Widgets finds its own dependencies.
find_package(Qt5Widgets REQUIRED)

add_executable(myproject main.cpp mainwindow.cpp)
qt5_use_modules(myproject Widgets)
```

**Comment by Unknwon** [comment]
Thanks, so `CMakeLists.txt` this name is unique? Like `Makefile`, `Dockerfile`, etc.?

**Comment by xor-gate** [comment]
Yes it is, it works also for `*.cmake` files

**Comment by Unknwon** [comment]
Latest `master` and demo site should be able to show highlight for cmake files correctly, any example repository to test on demo site?

**Comment by xor-gate** [comment]
Awesome it seems to work:
https://try.gogs.io/admin1/mpack/src/cmake/CMakeLists.txt
https://try.gogs.io/admin1/cmaketest/src/2015.06/CommonQtSupport.cmake

Thanks for your time and effort!

**Comment by Unknwon** [comment]
Thank your confirmation!

**Comment by bouffa** [comment]
Syntax highlighting no longer works for `CMakeLists.txt` files, see https://try.gogs.io/admin1/mpack/src/cmake/CMakeLists.txt

**Comment by Unknwon** [comment]
@bouffa highlight of `.txt` has disabled by default.

**Comment by bouffa** [comment]
@Unknwon  adding `cmakelists.txt` to [highlight.go#L21-L25](https://github.com/gogits/gogs/blob/master/modules/template/highlight/highlight.go#L21-L25) solves the issue :

	highlightFileNames = map[string]bool{
		"cmakelists.txt": true,
		"dockerfile": true,
		"makefile":   true,
	}

**Comment by Unknwon** [comment]
@bouffa good fix! Would you mind propose a PR?

**Comment by bouffa** [comment]
@Unknwon sure, i'll do it shortly.

**Comment by Unknwon** [comment]
https://try.gogs.io/admin1/mpack/src/cmake/CMakeLists.txt is now highlighted again!
