### ISSUE TITLE
Add an option to disable Gravatar

### ISSUE THREAD

**Issue by ponzipoh** [gogits/gogs#2201]
I have many problems using Gravatar, because it's a 3rd party company tracking users who use my local Gogs instance, I don't need it and I do not want to depend on files hosted on another company's servers.
Please remove Gravatar support, or add a setting somewhere such that I can disable it (even a simple flag in a plaintext file will do).
Thanks a lot!

**Comment by lukasdietrich** [comment]
There is already an option for that. 
See [conf/app.ini#L21](https://github.com/gogits/gogs/blob/0cce4439ceab9d53592e526f8840348a293e463d/conf/app.ini#L211]).

**Comment by ponzipoh** [comment]
Thanks @lukasdietrich
Does it work though? According to [this issue](https://github.com/gogits/gogs/issues/2180) users are still redirected to gravatar.com

**Comment by stonerl** [comment]
The global off switch does not work but you can disable it in your user profile.

**Comment by stonerl** [comment]
See here: #2180

**Comment by Unknwon** [comment]
Disable gravatar already work when you disable it, #2180 is talking about wrong link on UI.
