### ISSUE TITLE
Assigned issues don't show up for organization repos

### ISSUE THREAD

**Issue by jabeuy** [gogits/gogs#2202]
On v0.8.0.

I may just be missing something, but I've tried this on my installation and on the demo site.

When assigning an issue to a user (the user belongs to the org and has access to the repo) on a repo that is owned by an organization, the assignment doesn't show up in the user's Issues dashboard. 
If you switch the dashboard context to the organization rather than the user's context, the issues show up, but the user has to filter through them to see which issues they are assigned to. Ideally these issues would show up in the user's dashboard context, under the 'Assigned to you' tab.

Hopefully that made sense :)

If the existing behaviour is what was intended, and this isn't an issue, is there a way for a user to see what issues have been assigned to them (for repos owned by an organization)?

**Comment by Unknwon** [comment]
Thanks your feedback!

Yes you can view by repository for issues that are assigned to someone.

For you key request, it is duplicated to https://github.com/gogits/gogs/issues/1820 .
