### ISSUE TITLE
Instructions to generate SSL keys aren't accurate

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2204]
app.ini says:
```
; Generate steps:
; $ cd path/to/gogs/custom/https
; $ ./gogs cert -ca=true -duration=8760h0m0s -host=myhost.example.com
```
First: there is no ./gogs there. Should say ../../gogs (?)
Second:
```
# /usr/local/libexec/gogs/gogs cert -ca=true -duration=8760h0m0s -host=myhost
Incorrect Usage.

NAME:
```
But usage is the same as recommended!

**Comment by Unknwon** [comment]
Because you did not [build with tags](https://gogs.io/docs/installation/install_from_source#build-with-tags).

I'll fix docs in recent pushes.

**Comment by yurivict** [comment]
'pam' tag was off, you are right.

Instead of "Incorrect Usage." please say "Not built with pam support."

**Comment by Unknwon** [comment]
> 'pam' tag was off, you are right.
Instead of "Incorrect Usage." please say "Not built with pam support."

Actually... I don't know what you're talking ... :sweat:

**Comment by yurivict** [comment]
I meant: Instead of "Incorrect Usage." please say "Not built with cert support."
:-)

**Comment by Unknwon** [comment]
LOL. https://github.com/gogits/gogs/commit/8ecbf0f16d90ad63a3c3ddc856df7b76aa0c328f#diff-61a68e2ec3cfcbe7c16047bb4d7ee950R19
