### ISSUE TITLE
wiki 500 after changed REPO_ROOT_PATH

### ISSUE THREAD

**Issue by nzlov** [gogits/gogs#2205]

**Comment by burgerga** [comment]
Is there a workaround for 0.8.25?

**Comment by Unknwon** [comment]
@burgerga what workaround?

**Comment by burgerga** [comment]
I am on 0.8.25 and I have this issue on a repo that I transfered from my personal account to an organizational account. I can still read the wiki, but if I try to edit I get a 500. I was wondering if I could fix it without updating gogs.

**Comment by Unknwon** [comment]
@burgerga are you using windows?

**Comment by burgerga** [comment]
No, docker on a ubuntu server

**Comment by Unknwon** [comment]
@burgerga thanks. Can you check directories of `data/tmp/local/` under volume path that they are empty but have `.git` directories only?

**Comment by burgerga** [comment]
@Unknwon Which directory do you mean? I have `git`, `gogs` and `ssh` directories only in the `/data` directory. If I browse the `/data/git/gogs-repositories/<organization>/<repo>` directory, I can see that the `wiki.git` is there.

**Comment by Unknwon** [comment]
In your case, it should be `gogs/data/tmp/local/`.

**Comment by burgerga** [comment]
@Unknwon I can reproduce it with new repositories and new organizations.

**Comment by Unknwon** [comment]
Good to know, but this does not answer to the question...

**Comment by burgerga** [comment]
Ah yes, in `gogs/data/tmp/local-wiki` I have a directory `3` and a directory `5`

**Comment by Unknwon** [comment]
@burgerga OK... then looks like you're having different problem. Can you check the server log from Gogs for 500 error?

**Comment by burgerga** [comment]
Got it:

```bash
[...routers/repo/wiki.go:252 EditWikiPost()] [E] EditWikiPage: UpdateLocalWiki: Pull: exit status 1 - fatal: '/data/git/gogs-repositories/gerhard/test_bug.wiki.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

The actual path should be `/data/git/gogs-repositories/TEST/test_bug.wiki.git` where `TEST` is the organization.

**Comment by Unknwon** [comment]
Thanks.

Which version of Gogs are you running? 0.8.25?

**Comment by burgerga** [comment]
0.8.24.0128

**Comment by Unknwon** [comment]
Well... according to https://github.com/gogits/gogs/blob/master/models/repo.go#L133 , a restart should delete the `tmp` directories.

**Comment by burgerga** [comment]
Yes thank you, I can confirm that this works!

**Comment by Unknwon** [comment]
:100:
