### ISSUE TITLE
No syntax highlighting on some files

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2206]
When I import my repository https://github.com/yurivict/vm-to-tor into Gogs, the shell scripts rc.conf.simple.sample, rc.conf.complex.sample aren't highlighted. Or maybe they are highlighted with wrong syntax?

**Comment by Unknwon** [comment]
Yes, without common extensions, they're expected to not be highlighted correctly. 

Please follow on https://github.com/gogits/gogs/issues/2103
