### ISSUE TITLE
SSL certificate generated by gogs doesn't work

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2209]
I generate the certificate with the recommended command:
```
gogs cert -ca=true -duration=8760h0m0s -host=localhost:15123
```
Import cert.pem into firefox, but gogs prints:
```
2015/12/15 18:31:54 http: TLS handshake error from 127.0.0.1:57158: remote error: unknown certificate authority
```

Same with -ca=false.

Please note that -host=localhost:15123 doesn't cause firefox to show localhost:15123 in the Server column. But the certificate that Firefox generates itself as an exception does have Server column set.

**Comment by Unknwon** [comment]
> Import cert.pem into firefox

Why import to your browser?

Have you really read https://gogs.io/docs/intro/faqs#how-do-i-set-up-https%3F ?

**Comment by yurivict** [comment]
I thought when you import the certificate into the browser this authorizes the browser to trust this one certificate without going through the higher authorities. I might be missing something.

**Comment by Unknwon** [comment]
Let's Encrypt is in public beta... don't see why you still use this feature.. maybe removed from Gogs in the future releases.

**Comment by yurivict** [comment]
I don't use public beta. I use sources from 20 min ago.

**Comment by Unknwon** [comment]
> I don't use public beta. I use sources from 20 min ago.

.... what is source?

**Comment by Unknwon** [comment]
Close as original purpose of this thread is resolved. Feel free to continue discussion usage questions on http://forum.gogs.io/

**Comment by Unknwon** [comment]
Mistake, any updates?

**Comment by Unknwon** [comment]
Ok, just tested is it working:

> ./gogs cert -ca=true -duration=8760h0m0s -host=localhost

Note that port is not part of `domain`.
