### ISSUE TITLE
Config option to auto-redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2211]
This is the normal practice and about every site does this.

**Comment by Jonny007-MKD** [comment]
Could be integrated into #2782:

    if http && redirect enabled {
        send 302 code with https URL
    }

**Comment by Jonny007-MKD** [comment]
I stumpled upon the *Upgrade-Insecure-Requests* HTTP header. We can support this as well.
https://www.w3.org/TR/upgrade-insecure-requests/#preference

**Comment by Jonny007-MKD** [comment]
This redirect feature implicates listening on two ports: 80 and 443. Otherwise no redirect is possible.

**Comment by Unknwon** [comment]
> This redirect feature implicates listening on two ports: 80 and 443. Otherwise no redirect is possible/usable

It does not have to, if behind a reverse proxy, Gogs only listen on HTTP, the web server (such as NGINX) handles HTTP.

**Comment by Jonny007-MKD** [comment]
That's true :)

But after a quick search it seems as nginx by default is not telling gogs whether it is serving a http or a https request. If there is more to do in nginx setup than setting `proxy_pass` then the forwarding can be done in nginx as well.

**Comment by Unknwon** [comment]
@Jonny007-MKD that's the point, this is very very rare case.

**Comment by Jonny007-MKD** [comment]
So I'd say as long as gogs doesn't implement a second listener just for this feature it is no case at all.

**Comment by Unknwon** [comment]
Yes, might close this issue.

**Comment by Unknwon** [comment]
I think it is more likely a job for reverse proxy.
