### ISSUE TITLE
[feature request] Show "my fork" repository when the logged in user has forks of the repository he looks at

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2212]
Just like you say "forked from" under the repository name, add "my fork" when the user has a fork. There can (unlikely) be multiple forks too, so this is actually a list.

It is convenient to know that you already have a fork of it. Otherwise people who have a lot of forks might forget and fork again.

**Comment by Unknwon** [comment]
Thanks your feedback!

But no, user can't fork same repository twice, it will be redirected to the repository he/she already forked.

So this is a invalid argument. And show `my fork` is also inappropriate because you can fork to organizations you own.

**Comment by yurivict** [comment]
Why can't you just show if I personally already forked?

**Comment by Unknwon** [comment]
What is the use case of `show if I personally already forked`?

**Comment by yurivict** [comment]
So that people will see that they already forked.

**Comment by Unknwon** [comment]
> So that people will see that they already forked.

Why this is not more confusing that make people wonder which account I exactly was forked to?
