### ISSUE TITLE
html/template: "install" is undefined

### ISSUE THREAD

**Issue by kaizengliu** [gogits/gogs#2215]
I get the "html/template: "install" is undefined" when i first visit the site, and the console print "Completed /install 500 Internal Server Error", How can trace the error.

**Comment by Unknwon** [comment]
I suppose you did not run put `templates` under same directory as your Gogs binary. Please follow the [documentation](https://gogs.io/docs/installation/install_from_source).

And usage question please go http://forum.gogs.io/

**Comment by kaizengliu** [comment]
Oh, yes, I wrongly though that the templates are also build into the binary. It works now, thank you  very much.

**Comment by Unknwon** [comment]
:trollface:
