### ISSUE TITLE
Ability to serve HTTP requests on unix socket

### ISSUE THREAD

**Issue by kernel164** [gogits/gogs#2217]

**Comment by nivan22** [comment]
For example, a mysql sever could be staging or production, but it could also be master or slave. Allowing multi-tag-- DNS perspective production.master.mysql.service.consul and master.production.mysql.service.consul are supposed to be separate hosts, but for service discovery it would be the same. A small price. That's if we really care that production.primary.mysql.service.consul and primary.production.mysql.service.consul are the same. Personally I think that's a non-issue that only affects DNS caching and frankly not !!!!

**Comment by Unknwon** [comment]
@nivan22 thanks your comment.... but I don't quite get what you were trying to say..?

**Comment by Unknwon** [comment]
@kernel164 Thanks your feedback!

Please clarify your title more specific, unix socket support of what

**Comment by JokerQyou** [comment]
I suppose database connection or something?

**Comment by Unknwon** [comment]
Database socket has supported I think.

**Comment by kernel164** [comment]
Oops I missed the description. I have a requirement to make gogs listen in [unix socket](https://en.wikipedia.org/wiki/Unix_domain_socket). We have nginx to handle ssl and gogs would be served @ /gogs/ subpath.

We were able to make gogs 0.8.0 work with the following config in nginx.
```
    location /gogs/ {
        rewrite ^/gogs/(.*)$ /$1 break;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_pass http://localhost:3000;
        proxy_redirect http://localhost:3000/ $scheme://$host/gogs/;
        access_log /var/log/nginx/gogs.access.log;
        error_log /var/log/nginx/gogs.error.log;
    }
```

We need ```proxy_redirect http://unix:/var/run/gogs.sock; ``` support for better security.

**Comment by Unknwon** [comment]
Thanks for following up!

> We need proxy_pass http://unix:/var/run/gogs.sock; support for better security.

Why this have better security?

**Comment by kernel164** [comment]
If we listen on localhost any one can access gogs from localhost. If we listen on unix socket we could give permission like root:nginx which would make only nginx to access it.

**Comment by Unknwon** [comment]
OK... make sense.

But I currently don't know how to let Go listens in unix socket and serve HTTP requests...

**Comment by kernel164** [comment]
Here is the code that gin uses for unix socket support - https://github.com/gin-gonic/gin/blob/52fcc5dbf6e94df33ad313858fb94b713e9d1b4a/gin.go#L254

**Comment by Unknwon** [comment]
@kernel164 good indicator, looks very similar to what I'm going to support change listening port on the fly.

**Comment by emansom** [comment]
I'd also like this feature to get rid of unnecessary overhead introduced by using TCP.

**Comment by EtienneBruines** [comment]
Would FastCGI help?

https://golang.org/pkg/net/http/fcgi/

**Comment by Unknwon** [comment]
@EtienneBruines I think FCGI is already supported: https://github.com/gogits/gogs/blob/master/cmd/web.go#L566

**Comment by EtienneBruines** [comment]
@Unknwon If you'd replace the `nil` parameter with something that actually created a unix socket, then you'd have fixed this issue. Roughly, you could do things like:

```go
l, err := net.Listen("unix", "/tmp/echo.sock")
    if err != nil {
        log.Fatal("listen error:", err)
    }
```

When you keep the `nil` parameter (in the code-reference you sent me), you only accept FCGI from Stdin. When replacing it with the `l` in the example, a socket is created. (Of course, you'd have to handle permissions for that socket, and be sure to clean-up the socket after usage, but that's the basic idea).

**Comment by Unknwon** [comment]
Thanks @EtienneBruines !

Since I've not familiar with socket thing, someone who does and want to help this issue with a PR would be awesome!

**Comment by Crafter6432** [comment]
Wouldn't it be easier to support binding to localhost for now?

**Comment by bkcsoft** [comment]
> Wouldn't it be easier to support binding to localhost for now?

We already do that :)

**Comment by Unknwon** [comment]
I think Gogs already supports this...

**Comment by yan12125** [comment]
That's a great feature! I'd like to share how I configured gogs to use a Unix domain socket with Apache's reverse proxy feature. In gogs' app.ini:
```
PROTOCOL               = unix
HTTP_ADDR              = /var/run/gogs/gogs.sock
```
And in Apache configuration files:
```
ProxyPass /gogs unix:/var/run/gogs/gogs.sock|http://127.0.0.1:3000
ProxyPassReverse /gogs unix:/var/run/gogs/gogs.sock|http://127.0.0.1:3000
```
Also I need to tell systemd to create necessary folders for gogs. Create /etc/tmpfiles.d/gogs.conf:
```
d /var/run/gogs 0755 gogs gogs
```
Finally, create it and restart all relevant services:
```
sudo systemd-tmpfiles --create
sudo systemctl restart gogs
sudo systemctl restart httpd
```

(I'm using Arch Linux with its official gogs package, version 0.11.29.0727)
