### ISSUE TITLE
Pinging user with @username doesn't send a notification

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2219]
I couldn't see anything on the target account.

Actually, you could even allow an instant message delivery using websockets.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is the definition of your `notification`?

**Comment by yurivict** [comment]
There must be for example the red circle with the number of pending messages left of "+" (Create) menu. You click on it, and see the list with items.

Wikipedia for example does this too.

**Comment by Unknwon** [comment]
Thanks for your clarifying! 

This is now duplicated to https://github.com/gogits/gogs/issues/2109
