### ISSUE TITLE
Diff style

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#2220]
Currently the diff is compared by line, but Github and GitLab do provide more detailed diff. Let's compare the page style and you could see they seem to diff the files by word / letter.

Github:
![image](https://cloud.githubusercontent.com/assets/1465267/11863515/6caecea6-a4cf-11e5-87a5-d0bef0c10c46.png)

Gogs:
![image](https://cloud.githubusercontent.com/assets/1465267/11863516/722a3208-a4cf-11e5-9a5d-69faf302daff.png)

And also, the padding / margin of the diff view seem to be different from other elements on the page, which make the page look strange.

**Comment by Unknwon** [comment]
Thanks your feedback!

I think you should continue commenting on https://github.com/gogits/gogs/issues/1925 for your thoughts?

BTW, your version is old... take a look at demo site.

**Comment by JokerQyou** [comment]
Hmm, this is strange, I'm using version ` 0.8.0.1212 ` which was the first version without 'beta'.

**Comment by JokerQyou** [comment]
Since you've referenced this on #1925 , I think this can be closed for now.
I did not notice that the diff view on my server was an old one, but you remind me. I'll check my gogs installation once I get home.

**Comment by Unknwon** [comment]
Yeah, actually you're in the latest release that's right, but diff UI is slightly changed in `master` and demo site :D
