### ISSUE TITLE
LDAP authentication does not work as expected

### ISSUE THREAD

**Issue by velislav** [gogits/gogs#2221]
Gogs Version: 0.8.0.1212 with LDAP (via BindDN) configured with Microsoft Active Directory with the following filter: (&(objectClass=Person)(|(sAMAccountName=%[1]s)(mail=%[1]s))) 

If you log in for first time with user: user.name@example.com this will create the user user.name@example.com in gogs. However: 
   1. It is NOT possible to log in with user: user.name 
   2. It is possible to log in only with user: user.name@example.com

If you log in for first time with user: user.name this will create the user user.name in gogs. In this case everything is fine and it is possible to log in with both users: user.name and user.name@example.com

**Comment by Unknwon** [comment]
Thanks your feedback!

I suppose you have read https://gogs.io/docs/features/authentication

and there is a `Username attribute` to allow you specify unified username by an additional LDAP query for username.

**Comment by velislav** [comment]
I tried with the following options for Username atribute:
   1. sAMAccountName
   2. (&(objectClass=Person)(|(sAMAccountName=%[1]s)(mail=%[1]s)))
   3. (&(objectClass=Person)(|(sAMAccountName=%s)(mail=%s)))

The result is the same. When I create user with user.name@example.com I am unable to log in with user.name. I can only log in with user.name@example.com

**Comment by Unknwon** [comment]
Can you given a screenshot of LDAP config page?

**Comment by Unknwon** [comment]
cc @nanoant

**Comment by nanoant** [comment]
OMG, the reason is that there's mistake in the documentation, the Username attribute is an attribute name NOT a (extra) query.

So this is wrong:

> * Username attribute (optional)

>    * The attribute of the user’s LDAP record containing the user name. Leave empty to use sign-in form value for user name.
>    * Example: `(&(objectClass=Person)(|(uid=%[1]s)(mail=%[1]s)))`

Expected documentation:

> * Username attribute (optional)

>    * The attribute of the user’s LDAP record containing the user name. Leave empty to use sign-in form value for user name.
>    * Example: `AccountName`

The example of 2 attributes checked at login should be extended:

> * User Filter (required)

>    * An LDAP filter declaring how to find the user record that is attempting to authenticate. The ‘%s’ matching parameter will be substituted with the user’s username.
>    * **Use `%[1]s` to substitute more than once.**
>    * Example: `(&(objectClass=posixAccount)(uid=%s))` **(authenticating with username only)**
>    * **Example: `(&(objectClass=posixAccount)(|(uid=%[1]s)|(mail=%[1]s)))` (authenticating with either username or mail)**

**Comment by Unknwon** [comment]
Oops... really... :scream: Can you make a PR for docs?

**Comment by nanoant** [comment]
@Unknwon tommorow. I am going to party in 30 min :tada:

**Comment by Unknwon** [comment]
Haha, no problem.

cc @velislav could you try the what @nanoant commented?

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by velislav** [comment]
This was my first setup and the authentication is not working for user.name if the user is created with user.name@example.com: 

Username attribute: sAMAccountName
User Filter: (&(objectClass=Person)(|(sAMAccountName=%[1]s)(mail=%[1]s)))

Note that User Filter: (&(objectClass=Person)(|(sAMAccountName=%[1]s)|(mail=%[1]s))) suggested from nanoant should be (&(objectClass=Person)(|(sAMAccountName=%[1]s)(mail=%[1]s))). Without second pipe |  

Happy new year :)

**Comment by nanoant** [comment]
@velislav I don't understand, what do you mean by *"if the user is created with  `user.name@example.com`"*. Created where? In Gogs on 1st login? If you use `Username attribute: sAMAccountName` setting then Gogs user names shouldn't be email. Does it mean you have some users that were created when there was no `Username attribute`?

Moreover are you sure your BindDN user has permissions to search on `sAMAccountName` attribute? Did you try to check if your server responds properly on both:
~~~bash
# via user name
ldapsearch -H ldaps://YOURSERVER -b YOURSEARCHBASE -D BINDDN -w BINDDNPASSWORD '(&(objectClass=Person)(|(sAMAccountName=some.user)(mail=some.user)))' uid mail cn dn

# via email
ldapsearch -H ldaps://YOURSERVER -b YOURSEARCHBASE -D BINDDN -w BINDDNPASSWORD '(&(objectClass=Person)(|(sAMAccountName=user.name@example.com)(mail=user.name@example.com)))' uid mail cn dn
~~~

> (...) Without second pipe |

2nd pipe was a mistake, luckily there's no 2nd pipe in docs and examples use proper prefix notation.

**Comment by velislav** [comment]
@nanoant If you log in for first time in gogs with mail like user.name@example.com the user that is created in gogs is NOT user.name but user.name@example.com even with Username attribute set to: sAMAccountName

Both queries works and return dn, cn, mail and sAMAccountName but in my case is not "uid" but "sAMAccountName" because of the AD:

ldapsearch -H ldap://example.com -b 'OU=Users,OU=Company,DC=example,DC=com' -D 'CN=Git Server,OU=ServiceAccounts,OU=Users,OU=Company,DC=example,DC=com' -w 'password' '(&(objectClass=Person)(|(sAMAccountName=user.name)(mail=user.name)))' sAMAccountName mail cn

ldapsearch -H ldap://example.com -b 'OU=Users,OU=Company,DC=example,DC=com' -D 'CN=Git Server,OU=ServiceAccounts,OU=Users,OU=Company,DC=example,DC=com' -w 'password' '(&(objectClass=Person)(|(sAMAccountName=user.name@example.com)(mail=user.name@example.com)))' sAMAccountName mail cn

**Comment by Unknwon** [comment]
Any updates could for this issue?

**Comment by nanoant** [comment]
@velislav @Unknwon PR #2579 contains fix-up for that. My fault, forgot to fetch the username attribute value from the server on LDAP search query. With PR it should work fine now.
