### ISSUE TITLE
Context of dashboard doesn't show feeds correct

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2223]
When I select the context of some organization, I see feeds of other organizations that it isn't the organization that I have selected...There is too information that It should not be there.

I see my feed when I should not see my feed. It should only see the organization's feed selected.

Gogs version -> 8.0

Saludos!

- Gogs
![GOGS](http://s10.postimg.org/wvgr1tdpl/issue.png)

- Github
![Github](http://s30.postimg.org/672bvwa6p/issue.png)

**Comment by Unknwon** [comment]
Thanks, fix has been pushed to `develop` and you can test on https://try.gogs.io
