### ISSUE TITLE
Mirror repository does not choose master as default branch when possible 

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2225]
For default branches is sorted in alphabetical order when you visit a repository, you don't see master, you see "gh-pages" or "a-master", for example. But, I think and in Github is that the main branch when you visit it is master.

Saludos!! :smile: 

- Example

![Example](http://s11.postimg.org/8mm1c0sur/issue2.png)

--
- Update 1: I have created a mirrored repository and this have not default branch. [This is a repository from Github](https://github.com/oslugr/curso-git.git) and [this is a repository from Gogs](https://try.gogs.io/xxxtonixxx/curso-git)
![image](http://s18.postimg.org/uxpdu7dk9/issue.png)

**Comment by lukasdietrich** [comment]
Hey, you can actually set a default branch in the repository settings:

![image](https://cloud.githubusercontent.com/assets/1913775/11883835/d96e7438-a515-11e5-8aba-eb2240a0d1b7.png)

**Comment by xxxtonixxx** [comment]
Ohh, I didn't see that, thank you! :+1: :smile: 

But, It would be interesting that the branch for default was master

**Comment by lukasdietrich** [comment]
No Problem :smile:.
I just tried to recreate your issue, but when I create a new repository with two branches `alpha` and `master`, the `master` branch is set as default automatically.

**Comment by xxxtonixxx** [comment]
Hmmm, then, this can be because I have mirrored a repository from github and for default there isn't default branch, that input is empty... [This is a repository](https://github.com/oslugr/curso-git) that I have mirrored :+1:

Thanks! :smile:

**Comment by Unknwon** [comment]
Yes, mirror repo could have this problem. I'll look into it.

**Comment by joshfng** [comment]
I can confirm that creating a mirror in gogs does not set the default branch to master.

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2744, please help test on `develop` branch or https://try.gogs.io.

**Comment by xxxtonixxx** [comment]
Works well! :+1: [test](https://try.gogs.io/xxxtonixxx/prueba_master)

**Comment by Unknwon** [comment]
Thanks your confirmation!
