### ISSUE TITLE
A markdown file doesn't show how it should

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2226]
- Original file in Github:
[Original file](https://github.com/oslugr/curso-git/blob/master/texto/Modulos.md)

- Mirror to repository of Github, it's same file:
[Mirror file](https://try.gogs.io/xxxtonixxx/curso-git/src/master/texto/Modulos.md)

And this too:
- Original file in Github:
[Original file](https://github.com/oslugr/curso-git/blob/master/texto/uso_basico.md#en-linux)

- Mirror to repository of Github, it's same file:
[Mirror file](https://try.gogs.io/xxxtonixxx/curso-git/src/master/texto/uso_basico.md#instalar-git)

** There's more markdown files but that see ok

Saludos!

**Comment by Unknwon** [comment]
Thanks!

Gogs only supports standard markdown, you can report this problem to https://github.com/russross/blackfriday

**Comment by bkcsoft** [comment]
Actually, blackfriday doesn't support (and won't support) GFM: https://github.com/russross/blackfriday/issues/192 so if you want GFM you'd have to change the renderer to e.g. https://github.com/shurcooL/github_flavored_markdown/

**Comment by Unknwon** [comment]
@bkcsoft thanks your info!

Blackfriday is widely used and many work of Gogs is done by its conventions and features, it mostly likely not possible to change to another render.

**Comment by bkcsoft** [comment]
@Unknwon Yeah, I looked at changing the renderer to shurcooL/githubc_flavored_markdown but it wasn't really viable. So if we want this it'd have to be added in modules/base/markdown.go as a PreProcessingStep (like with the issue/commit-link shortener)

**Comment by xxxtonixxx** [comment]
Does that want to say that it isn't possible to fix?

**Comment by Unknwon** [comment]
> Does that want to say that it isn't possible to fix?

Yes.

**Comment by xxxtonixxx** [comment]
Ok, thanks!

**Comment by shurcooL** [comment]
> @Unknwon Yeah, I looked at changing the renderer to shurcooL/github_flavored_markdown but it wasn't really viable.

@bkcsoft, can you please elaborate on why? I'd like to understand. Thanks!
