### ISSUE TITLE
[idea] Support mercurial as one of the version control systems

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2227]
My suggestion is to make Gogs support multiple version control systems, and add Mercurial as another supported one.

Reasons:
1. Mercurial has a lot of very devoted, hardcore followers. They are often ignored, but if you also support Mercurial, you will easily earn their hearts.
2. Mercurial is functionally quite similar to git, and I heard it is as good as git
3. It doesn't hurt Gogs to support more than one version control systems

It is possible to put version control system behind the abstraction layer, and make them work like plugins.

This isn't an immediate request, just an idea for the consideration in the long run.

Please note that BitBucket, GitHub look-alike (https://bitbucket.org/) is doing what GitHub does, only with Mercurial.

https://en.wikipedia.org/wiki/Mercurial

**Comment by Unknwon** [comment]
Thanks your feedback!

But the answer is no. It distracts focus and purpose of Gogs too much.

BTW, thanks your recent active feedbacks to Gogs project, but please talk to us on Gitter.im next time before filling this type of issues.

**Comment by icefoxen** [comment]
This is perfectly reasonable, but, I love Gogs and want hg support...

Would you be willing to accept patches that add it? Or should I fork Gogs and make it do what I want?  (Maybe call the new program Ghogs...)

**Comment by Unknwon** [comment]
@icefoxen you should probably fork Gogs...

**Comment by icefoxen** [comment]
Okay, thanks.

**Comment by Unknwon** [comment]
A side note: Gogs may abstract Git operation level that allows any implementation to plugin with Gogs, but not sure when...

**Comment by icefoxen** [comment]
That would be nice eventually, but unless you want me to write that module for you it sounds like I'm probably better off making a fork...

**Comment by Unknwon** [comment]
:sweat_smile:
