### ISSUE TITLE
Issue references have bad links behind a reverse proxy sub-path

### ISSUE THREAD

**Issue by kolesar-andras** [gogits/gogs#2229]
Issues referenced in issues have bad link if Gogs is behind a reverse proxy in a directory. Link does not have repository name. Looks like this:

    <a href="/git/username/issues/1" rel="nofollow">#1</a>

Directory name is git, username is gogs username, repository name is missing here. My setup:

    ROOT_URL = http://proxy.external.address/git

Apache rules:

    ProxyPass /git http://internal.address:3000
    ProxyPassReverse /git http://internal.address:3000

I have tried accessing the same page directly. Modified ROOT_URL:

    ROOT_URL = http://internal.address:3000

The referenced issue has correct link when I accessing the server directly:

    <a href="/git/username/repositoryname/issues/1" rel="nofollow">#1</a>

I think it's a bug. Previously reported in #1794.

**Comment by dakira** [comment]
I've got the same problem. Any workaround available until this is fixed? I need to run gogs in a sub-path because the root needs to be available for letsencrypt so that it can auto-renew TLS-certificates.

**Comment by Unknwon** [comment]
@dakira I think here is the problem: https://github.com/gogits/gogs/blob/master/modules/base/markdown.go#L198

**Comment by dakira** [comment]
@Unknwon yeah, that clearly doesn't work at all with subdirectories. So I'm not at all a Go developer (yet), but my solution would be this:

We already have ROOT_URL. Maybe count the number of slashes in that and use the number to cut of the part of the urlPrefix you don't want? I'm not sure how to access config variables but that should be the fix, right?

**Comment by dakira** [comment]
Totally untested, but this should fix it, right?

```go
func appUrlSlashes(appUrl string) int {
	count := 0
	for i := 0; i < len(appUrl); i++ {
		if appUrl[i] == '/' {
			count++
		}
	}
	return count
}


func cutoutVerbosePrefix(prefix string) string {
	count := 0
	for i := 0; i < len(prefix); i++ {
		if prefix[i] == '/' {
			count++
		}
		if count >= appUrlSlashes(setting.AppUrl) {
			return prefix[:i]
		}
	}
	return prefix
}
```

**Comment by Unknwon** [comment]
Thanks @dakira ! This is very similar to what I have in mind.

**Comment by Unknwon** [comment]
@dakira can you try out latest `develop` branch?

**Comment by dakira** [comment]
@Unknwon Yup. Can confirm this fixes it! Thanks.

**Comment by Unknwon** [comment]
@dakira Cool, thanks your confirmation!

cc @kolesar-andras

**Comment by Unknwon** [comment]
Close as fixed.
