### ISSUE TITLE
Unlisted, not private.

### ISSUE THREAD

**Issue by Taekus** [gogits/gogs#2230]
Downloaded and configured the latest version (at the time Version: 0.7.6.1112 Beta).

Everything is working greate, even got Apache2.x configured on a seperate server with reverse proxy.
My only thing is, I would like to have some projects unlisted, but not private.
This way I can still give certain people a direct URi, but it would not be listed under Explore.

(URi domain.ext/user/repo)

**Comment by Unknwon** [comment]
Thanks your feedback!

> This way I can still give certain people a direct URi

After this, then what...?

**Comment by Taekus** [comment]
For some reason it didn't post the whole thing.

The purpose of this request is to give specific people access to the source code and change comparison without listing it, and without the person having to sign-up with the site system.

Listing as public, becomes visible under under explore.
Listing as private, requires to be signed up and part of the project to view it.

my request: not listed under explore, but still accessible without signup using direct URi/URL

**Comment by Unknwon** [comment]
Thanks for clarifying!

> my request: not listed under explore, but still accessible without signup using direct URi/URL

This requires guest account feature in Gogs, which currently it does not have. And if you request for this, it will have low priority...

**Comment by Taekus** [comment]
I don't know much about Go, but in php it's very simple to not list something in a database, Just adding an additional field in the database for the specific project with a 1 or 0, true or false when the script checks for listed/unlisted, probably more similar to the way that the private/not private works.

I'm not exactly sure what you mean by "guest account", as such a thing shouldn't be needed to have a non-private non-listed repo. Perhaps my logic differs from yours.

**Comment by Unknwon** [comment]
Of course I know how easy it is to implement.

But the question is what is the difference of not listing a public repository?

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by veecue** [comment]
A good argument for this is the `go get` logic. If you have a private repo or lib, but want it to be go-gettable, you have to go through the trouble of reconfiguring go to ask for a password. However, if the project isn't that critical, it would be way easier to rely on the import path as a "secret", so even third partys can simply pull it via `go get`.

**Comment by Unknwon** [comment]
@veecue you can always use `.netrc` file to config username and password thing I think.

**Comment by veecue** [comment]
Thanks for the tip. However, this does not work, when sharing your code to others who do not have an account on gogs

**Comment by Unknwon** [comment]
@veecue yes, it will not, only work with `go get` and who has real access to the repository.
