### ISSUE TITLE
Can't clone repository through ssh: login fails

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2232]
In app.ini I have an IP address:
```
[server]
PROTOCOL = http
DOMAIN = 192.168.2.10
ROOT_URL = http://192.168.2.10:15123/
HTTP_ADDR =
HTTP_PORT = 15123
LOCAL_ROOT_URL = http://192.168.2.10:%(HTTP_PORT)s/
```
User name is 'yuri', computer has the local hostname=yuri.myhost.com

On the remote machine I try to clone:
```
$ git clone gogs@192.168.2.10:yuri/TestRepository.git
Cloning into 'TestRepository'...
Password for gogs@yuri.myhost.com:
Password for gogs@yuri.myhost.com:
```

gogits user yuri definitely exists, password is correct. But login fails. This is the first problem.

The second problem: It looks like ssh sends the hostname 'yuri.myhost.com' from the server to the client. But client doesn't know this name - it isn't global and shouldn't be sent to remote hosts. Gogs should only use what .ini file says DOMAIN is, and this is an IP address in my case.

**Comment by Unknwon** [comment]
Please check your SSH server's `auth.log`.

**Comment by stilet** [comment]
I confirm the problem.
Gogs Version: 0.8.10.1217

**Comment by Unknwon** [comment]
@stilet Please check your SSH server's `auth.log`.

**Comment by yurivict** [comment]
```
Dec 18 01:10:15 yuri sshd[46751]: Connection from 192.168.2.11 port 46838 on 192.168.2.10 port 22
Dec 18 01:10:15 yuri sshd[46751]: Postponed keyboard-interactive for gogs from 192.168.2.10 port 46838 ssh2 [preauth]
Dec 18 01:10:19 yuri sshd[46751]: error: PAM: authentication error for gogs from 192.168.2.11
Dec 18 01:10:19 yuri sshd[46751]: Failed keyboard-interactive/pam for gogs from 192.168.2.10 port 46838 ssh2
```

It says PAM error. But all remote users can't know the password for gogs UNIX user. They can only know the password of users in gogs system.

PAM option of off for me.

**Comment by Unknwon** [comment]
The log says you're not allow yourself login with SSH key to me.

**Comment by yurivict** [comment]
Ah, this is only allowed with ssh keys .... I was expecting it to ask user password.

**Comment by Unknwon** [comment]
:trollface:

**Comment by khromov** [comment]
@Unknwon Just to clarify, the `gogs` user does not have a password set and can only be logged into via authorized key? Is that correct?

**Comment by Unknwon** [comment]
@khromov No, it does not matter. ALA you do not use same SSH key to login and do git push/pull.

**Comment by khromov** [comment]
@Unknwon Of course! I figured out you set your SSH keys on your profile, similar to GitHub. Thank  so much and thank you for this incredible piece of software! :trophy:
