### ISSUE TITLE
Only print color terminal sequences when log goes to the terminal

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2233]
When I redirect log to a file I see this:

```
2015/12/17 23:45:46 ^[[1;31m[...s/setting/setting.go:292 NewCon
```

**Comment by Unknwon** [comment]
Gogs already writes log into file after your installation without color sequences. Also I think redirection is not detectable from Gogs.

**Comment by yurivict** [comment]
It still prints the sequences to stdout, and these have color sequences.

What do you mean "not detectable"? This is always detectable.

**Comment by Unknwon** [comment]
> This is always detectable.

How?

**Comment by yurivict** [comment]
```
$ man isatty
...
     The isatty() function determines if the file descriptor fd refers to a
     valid terminal type device.
...
```

Given the file descriptor, this function determines if the fd goes straight to terminal, or is redirected to file.

**Comment by Unknwon** [comment]
Thanks your info and good to know.

But in `prod` mode, color is off already for terminal, I don't think it is worth using it.

**Comment by yurivict** [comment]
I run in production mode and colors are still on:
```
2015/12/18 01:10:09 ^[[1;32m[I] Run Mode: Production^[[0m
```

**Comment by yurivict** [comment]
You don't need to turn the color off in production mode. No reason.
You only need to print them to terminal, and not to file.

**Comment by Unknwon** [comment]
> You only need to print them to terminal, and not to file.

Why?

**Comment by yurivict** [comment]
Because why does anybody need terminal sequences in file?

**Comment by Unknwon** [comment]
> Because why does anybody need terminal sequences in file? They are designed for terminal.

Why do you need duplicated logs in same format?

**Comment by yurivict** [comment]
Here is what happens:
I run gogs under daemon:
```
# daemon -p /var/run/gogs.pid gogs web > /var/log/gogs.log 2>&1
``

This writes everything it prints to file. Once you print something to output, people can redirect it to file. And if it has colors. they go to file. The question is: why gogs prints to output then?

**Comment by Unknwon** [comment]
> The question is: why gogs prints to output then?

Good question! You can change purpose of issue to `Ability to disable log to terminal`.

**Comment by yurivict** [comment]
I actually like that it prints some important logs to terminal. I can see that it started, protocol, etc.

* Two problems: It prints too much, no need to print every http query
* The terminal sequences are still present when redirected to file

Once the program prints something to stdout under any conditions, it should check if this is a terminal or not. This is a common thing for all terminal programs.

**Comment by Unknwon** [comment]
> Two problems: It prints too much, no need to print every http query

You can disable by https://github.com/gogits/gogs/blob/master/conf/app.ini#L62

> The terminal sequences are still present when redirected to file

I may have some ideas, but the purpose of this issue has to be changed to `do not print color to terminal in prod mode`.

**Comment by yurivict** [comment]
When you print anything, regardless of any other logic, right before write to stdout/stderr there should be isatty check.

"do not print color to terminal in prod mode" - this is another topic. I personally like colors, when they are on terminal.

**Comment by Unknwon** [comment]
OK, you win!

Note: https://github.com/mattn/go-isatty

**Comment by ayosec** [comment]
It will be nice if there is an option to disable the bright (i.e. remove the `1` in the ANSI sequence `ESC[1`).

The current messages are hard to read on a white background.

**Comment by yurivict** [comment]
@ayosec  Please open a separate bug for this, because this has nothing to do with this bug.

**Comment by ptman** [comment]
It would be nice to be able to disable colors from console logs. Docker captures console output to file and the color escape sequences just make it hard to read.

**Comment by Unknwon** [comment]
Implemented.
