### ISSUE TITLE
Add API for syncing mirror

### ISSUE THREAD

**Issue by Janfred** [gogits/gogs#2235]
To avoid polling a feature to add a webhook to Gogs in the source repository would be good (In addition to the "Sync now" mentioned in #2018 )

**Comment by Unknwon** [comment]
> To avoid polling a feature to add a webhook to Gogs in the source repository

Sorry I don't understand this...

**Comment by Janfred** [comment]
e.g. you enter a Webhook in your Github-Repository to call gogs to update the mirror

**Comment by Unknwon** [comment]
Like webhook-based mirror polling?

**Comment by Janfred** [comment]
Actually I dont think you can call it polling...
It is a "workaround" way for "pushing" source repo updates to the mirrored respositories

**Comment by Unknwon** [comment]
My bad, I mean `webhook-based mirror pulling`?

**Comment by Janfred** [comment]
yep.

**Comment by 0rax** [comment]
:+1: Can be useful when proxying build through a private gogs instance !

**Comment by bkcsoft** [comment]
So this isn't really a webhook but an API-endpoint like `/api/v1/repo/:owner/:repo/trigger_update` ?

**Comment by yellowmegaman** [comment]
Since "Sync now" button already exist, maybe we already can curl something to trigger it from cli?
Thanks in advance for reply.

**Comment by hochhaus** [comment]
@yellowmegaman The UI for "Sync now" just POSTs to `/<user>/<repo>/settings` with `action: mirror-sync`. The tricky part about curling that URL is setting up the cookies and CSRF. Currently the endpoint isn't exposed as an API intended to be called from a non-browser context as best I can tell.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

See usage: https://github.com/gogits/go-gogs-client/wiki/Repositories#mirror-sync

**Comment by hochhaus** [comment]
I built from `develop` and tested this end point. It works well and addresses my need to update mirrors in real time. Thanks for addressing the issue so quickly!
