### ISSUE TITLE
Mirror repo password in logging output on update error

### ISSUE THREAD

**Issue by Janfred** [gogits/gogs#2236]
If an Mirror update fails (in my case the lookup for the repository) the complete URL with username and password appears in the logs.

`[...xorm/xorm/session.go:982 Iterate()] [E] Fail to update mirror repository(/path/to/git.git): error: Couldn't resolve host 'my.gitlab.hoster' while accessing https://*USERNAME*:*PASSWORD*@my.gitlab.hoster/username/git.git/info/refs`

**Comment by novaeye** [comment]
this problem also exists when create a new mirror repo.

**Comment by Unknwon** [comment]
I think this is solved already in `master`.
