### ISSUE TITLE
New migration with the mirror option doesn't migrate all commits

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2240]
When I migrate https://github.com/tux3/qTox.git without the mirror option, I get all 4046 commits.

But when I migrate it with the mirror option, it only migrates 3891 commits. Latest commits aren't migrated for some reason.

**Comment by lukasdietrich** [comment]
I just tried to reproduce your problem.
The mirror is actually complete, but the default branch is not master. 
There is already an issue regarding that problem, see #2225.

**Comment by yurivict** [comment]
But the commit counts should be the same, and they aren't.

**Comment by lukasdietrich** [comment]
Try switching to master branch. The amount of commits is displayed per branch.

**Comment by yurivict** [comment]
You are right! Thanks.
