### ISSUE TITLE
After migration is successful, gogs should go to the migrated repository, not to the previous one

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2241]

**Comment by Unknwon** [comment]
Sorry, I don't understand this?

**Comment by yurivict** [comment]
After I performed migration, currently gogs goes back to what repository I was looking at. The rigth behavior is to open the new one.

**Comment by Unknwon** [comment]
Thanks. How to reproduce this?

**Comment by stonerl** [comment]
I cannot reproduce this issue. Whenever I create a migration it goes directly to the new migrated repo.

**Comment by yurivict** [comment]
I can't reproduce this now either.

**Comment by Unknwon** [comment]
:sweat:
