### ISSUE TITLE
Archive tarballs are created without the top-level directory

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2242]
Command
```
https://{host}/{user}/{repo}/archive/{branch,tag,40-char SHA}.tar.gz
```
creates the tarball without the top directory, with the project files in the root of the tarball.

Please compare with
```
https://codeload.github.com/gogits/gogs/tar.gz/09c9818?dummy=/gogits-gogs-v0.151218-09c9818_GH0.tar.gz
```
which creates the top level directory gogs-09c9818/ with project files under it.

The top-level directory is usually expected in UNIX tarballs. Please note that 'tar' command has --strip option that allows to remove the top level directories while extracting.

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/518
