### ISSUE TITLE
/install screen shouldn't accept the SMTP host without the port

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2243]
Because later gogs fails to send an e-mail: "missing port in address"

**Comment by Unknwon** [comment]
For whoever wants to help, do a regexp check would be sufficient.

**Comment by Jonny007-MKD** [comment]
Could be solved in #2777

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
