### ISSUE TITLE
Failure to send mail: handshake failure

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2244]
Getting this error:
```
2015/12/18 20:57:30 .../runtime/asm_amd64.s:1696 goexit()] [E] Fail to send e-mails [yuri@xxx.com]: Subject: [test-repo] 'Another test pull request', issue notify - gomail: could not send email 1: remote error: handshake failure
```

[mailer] has:
```
ENABLED = true
SEND_BUFFER_LEN = 100
SUBJECT = %(APP_NAME)s
HOST=smtp.{domain}.com:587
USE_CERTIFICATE = false
USER = {user}@{domain}.com
PASSWD = {correct password}
FROM = "Gogs Service" <gogs@{domain}.com>
```
Thunderbird works with this account: STARTTLS/Normal passwd

**Comment by Unknwon** [comment]
Looks like port 587 is SSL port, and Go only supports TLS.

**Comment by yurivict** [comment]
Thunderbird offers the option "Connection security" with choices: STARTTLS/SSL/TLS.

**Comment by Unknwon** [comment]
> Thunderbird offers the option "Connection security" with choices: STARTTLS/SSL/TLS.

What does this supposed to mean?

**Comment by yurivict** [comment]
Protocols:
STARTTLS: https://en.wikipedia.org/wiki/STARTTLS (can later switch to SSL or TLS)
SSL/TLS: https://en.wikipedia.org/wiki/Transport_Layer_Security

In my case STARTTLS works.

**Comment by yurivict** [comment]
https://golang.org/src/net/smtp/smtp.go

**Comment by Unknwon** [comment]
OK, I've pushed a commit to `develop` to make mailer log more verbose. Please help test again.

**Comment by yurivict** [comment]
Ok thanks, will test.

**Comment by yurivict** [comment]
I retested. I have two different SMTP accounts, and both fail.

The first one normally works through STARTTLS on port 587, and it failed the same way:
```
2015/12/19 00:08:40 .../runtime/asm_amd64.s:1696 goexit()] [E] Fail to send e-mails [yuri@xxx.com]: Subject: [vm-to-tor] Some pull request (#2), issue notify - gomail: could not send email 1: StartTLS: remote error: handshake failure
```

The second one normally works through TLS 1.2 on port 465, and fails:
```
2015/12/19 00:12:56 [.../runtime/asm_amd64.s:1696 goexit()] [E] Fail to send e-mails [yuri@xxx.com]: Subject: [vm-to-tor] Another one (#3), issue notify - gomail: could not send email 1: NewClient: x509: certificate signed by unknown authority
```

**Comment by Unknwon** [comment]
For the first, does not seem like Go supports it anyway.

For the second, you have to disable verification: https://github.com/gogits/gogs/blob/master/conf/app.ini#L162

**Comment by yurivict** [comment]
I had SKIP_VERIFY=, it still failed.

**Comment by Unknwon** [comment]
`SKIP_VERIFY=true`.

**Comment by yurivict** [comment]
Ok, the second one works!

STARTTLS demo is here: https://golang.org/src/net/smtp/smtp.go

**Comment by Unknwon** [comment]
Sorry, what demo? Gogs is using this package already.

**Comment by yurivict** [comment]
STARTTLS is another, completely separate protocol. Maybe gogs needs to tell it to use STARTTLS?

**Comment by Unknwon** [comment]
See https://github.com/gogits/gogs/blob/master/modules%2Fmailer%2Fmailer.go#L132

**Comment by yurivict** [comment]
Does this mean that there is no such extension?

**Comment by Unknwon** [comment]
Based on the error, I think it has, but then fails on `StartTLS` method.

**Comment by yurivict** [comment]
So it must be a bug in this package.

**Comment by Unknwon** [comment]
Feel free to report to https://github.com/golang/go :trollface:

**Comment by yurivict** [comment]
https://github.com/golang/go/issues/13694

This is the general Go problem. Go fails with pure TLS with the same server. The failing account supports fewer ciphers than accounts that work.

**Comment by Unknwon** [comment]
:trollface:
