### ISSUE TITLE
[feature request] Add "command" webhook that will execute a command and pass json to it

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2245]
I would like gogs to add the "Command" hook as a type of a webhook.

It will send the same json to the stdin of the user specified command instead of sending it into the POST request.

The reason: it is much easier to do something simple from the script, rather than having another web server listening to the POST requests. I need to listen to the pull request submission events, and fire up some side process. But I don't want to have to run another web server app for this. Shell script is much simpler.

"Command" hook should only be allowed for the admin user for security reasons.

**Comment by Unknwon** [comment]
Thanks your feedback!

I think you should use Git hooks.

**Comment by yurivict** [comment]
Once the local admin wants to use the webhook, he doesn't want http/push. He wants the shell command executed, because this is much easier.

Any ability to run scripts by the user should be authorized by the admin, because otherwise this is a security violation.

Whether to use git hooks - is another issue.

**Comment by Unknwon** [comment]
Web hooks are called web hooks because they hooks called by web.

You're requesting different things.

**Comment by LeKovr** [comment]
There is a [webhook](https://github.com/adnanh/webhook) solution which do the same - execute a command and pass json to it. With nice improvements.

**Comment by Unknwon** [comment]
> There is a webhook solution which do the same - execute a command and pass json to it. With nice improvements.

Yes, but it still receives webhook and then do the custom tasks. If it is integrated into the server, such as Gogs. It is a different thing, because "web" is never part of it.

**Comment by LeKovr** [comment]
I don't offer to integrate webhook into gogs. They all does own things. Very fine, I sure.
BTW, in case they run on same host there is no any web there.

**Comment by yurivict** [comment]
Just call them "GogsHooks"? Github calls them "webhooks" because GitHub is web-only for clients, and gogs isn't.

Any admin will say they want commands rather than http/post. I don't think git hooks have access to the pull request numbers, etc.

**Comment by Unknwon** [comment]
> I don't think git hooks have access to the pull request numbers, etc.

It would be better to call APIs (thought APIs aren't complete yet).

**Comment by Unknwon** [comment]
What is the status of this issue?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
