### ISSUE TITLE
Webhooks for pull request

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2246]
When the pull request is created, the repository owner might need to do something special about this. So it is nice if webhook can be called on pull request creation.

**Comment by bhchew** [comment]
+1

one use case I can think of is to trigger a CI build, or a notification to slack

**Comment by yurivict** [comment]
I think hooks available on this GitHub page /{user}/{repo}/settings/hooks/new "Let me select individual events." should be implemented as much as possible, because they all look like useful hooks.

**Comment by trobert2** [comment]
+1
I also want this for a job in a CI

**Comment by yurivict** [comment]
For the record, #2253 is the reverse of this one: API for the pull requests.

**Comment by chuck7000** [comment]
+1 - we use this with gitlab currently to notify the team via slack when a pull request is waiting to be reviewed.  We're looking at migrating to gogs and would really like this feature.

**Comment by kmadel** [comment]
I just wanted to mention that I have written a Gogs Plugin for Jenkins to support Pipeline Multibranch and Org Scanning (auto creates project folders for repos and Pipeline projects for branches that have a Jenkinsfile in them). Initial release is available here: https://github.com/kmadel/gogs-branch-source-plugin/releases/tag/v0.1-alpha

The biggest missing features is support for Pull Requests. Even without a webhook or a Rest API to interact with them - is there anyway to interact with PRs via plain vanialla Git?

Thanks for the awesome work!

**Comment by Unknwon** [comment]
Hi @kmadel , I'm not sure what does `via plain vanialla Git` mean, but I think you can checkout PR locally just like the way GitHub does: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by kmadel** [comment]
@Unknwon Yes, I understand that you can checkout PRs from refs/pull/{ID}/head - but there isn't an easy way to retrieve Pull Requests for give repo (and I know this is already a requested feature). But this feature is also very important to allow auto-project generation for Jenkins Pipeline Multibranch whenever a new pull request is created on a repository.

**Comment by Unknwon** [comment]
What do you mean by `retrieve Pull Requests`?

**Comment by yurivict** [comment]
retrieve Pull Requests = get json with the pull request without checking out the full repository.

**Comment by Unknwon** [comment]
How can you achieve this with GitHub as an example?

**Comment by yurivict** [comment]
@Unknwon You can't achieve this with github, but gogs should be better than github -) Once you support APIs, it is natural that people will want to read certain data subsets using APIs.

For example, if I want to periodically check from the script if the new pull requests are available, I can't currently do this without checking out the repository.

**Comment by Unknwon** [comment]
>You can't achieve this with github, but gogs should be better than github -)

Thanks, but this does not make me understand what is `retrieve`, without examples..

**Comment by kmadel** [comment]
GitHub does have an API - to retrieve PRs by repo:

https://developer.github.com/v3/pulls/#list-pull-requests

GET /repos/:owner/:repo/pulls

**Comment by kmadel** [comment]
Basically, a REST API that wraps [GetUnmergedPullRequestsByBaseInfo] (https://github.com/gogits/gogs/blob/master/models/pull.go#L404)

**Comment by Unknwon** [comment]
Todos:

- [x] Open
- [ ] Closed (merged)
- [ ] Reopened
- [ ] Edited
- [ ] Assigned
- [ ] Unassigned
- [ ] Labled
- [ ] Synchronized

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by kmadel** [comment]
First, huge thanks! The webhook looks good so far to include same repo and forked repo. 

However, in order to integrate it with the Jenkins plugin I am writing (https://github.com/kmadel/gogs-branch-source-plugin) I will need an API endpoint to retrieve Pull Requests for the (base) repo specified in the webhook payload. I am starting to look at the code, but am new to Go, so may take some time before I am able to contribute.

Here is an examples of what I am trying to accomplish with Gogs: https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L463

**Comment by hhenkel** [comment]
I played around a bit with it today, looks good so far - will have a closer look tomorrow. One thing I noticed and might come in handy would be a notifications on comments. IMHO new/ edited / deleted(if that is possible) comments on a pull request should also trigger a webhook.

**Comment by Unknwon** [comment]
@hhenkel there will be another webhook type `issue_comment` as GitHub.

**Comment by hhenkel** [comment]
@Unknwon yes that is propably better handled there, you're right. I then will just try to keep calm and wait what good things come in next. :)

**Comment by hhenkel** [comment]
@Unknwon I'm currently trying to build my own handler script for Gogs in [rocket.chat](http://rocket.chat) and so far there are two things so far:

- at least for rocket.chat the slack hook works, however it seems like the actual text / url representation is broken when one submits a new PR. It shows up as something like:

```
[someOrg/webhook_test] Pull request submitted by someUser

<https://git.example.com/gogs/someOrg/webhook_test/pulls/2|#2 TEST 2 - HEADING>
With some text
```

- when playing with the gogs native hook I see most of the required parameters, but I guess it would be nice  to have a url to the actual pull request, this seems currently missing. What do you think?

**Comment by hhenkel** [comment]
@Unknwon another thing I just saw is somewhat an edge case I guess. When creating a new pull request and selecting an assignee no webhook for the assignee is triggered nor is the information available in the webhook data. I'm not sure what the best solution is for such cases. Maybe include by default all possible data chunks even if they are empty - another solution might be to trigger the necessary hooks after another, but not sure if that is a good solution.

**Comment by Unknwon** [comment]
@hhenkel 

>at least for rocket.chat the slack hook works, however it seems like the actual text / url representation is broken when one submits a new PR. It shows up as something like:

I think it could be incompatible syntax of rocket.chat, Slack looks fine:

 
![image](https://cloud.githubusercontent.com/assets/2946214/17703207/c15b1778-6385-11e6-84cb-e7ad8f3788b6.png)

**Comment by Unknwon** [comment]
@hhenkel two other concerns are fixed/improved.

**Comment by atsepkov** [comment]
Is this pull request feature accessible via the api? I'm not seeing it in the docs (https://github.com/gogits/go-gogs-client/wiki/Repositories-Webhooks). Would it be accessible via the 'pull' or 'pull_request' string in the `events` array?

**Comment by Unknwon** [comment]
@atsepkov technically it is "pull_request", I'll update the docs, good catch!
