### ISSUE TITLE
git-upload-pack failing on push

### ISSUE THREAD

**Issue by sid-kurias** [gogits/gogs#2248]
Using the latest gogs docker image 0.8.10 along with drone.io 0.4. Running on ubuntu 14.04 within a kubernetes cluster. Using postgres as the database.

I can do git push (using ssh) successfully from my local repository and the changes are reflected in the master repositories managed by gogs. But the builds on drone.io are not triggered.

I checked the configuration and can successfully trigger the configured webhook from the Test Delivery button.  

I see the following error when I execute docker logs command

[Macaron] Started POST /sid/kk-people.git/git-upload-pack for 172.16.23.1
2015/12/19 18:25:28 http: multiple response.WriteHeader calls
[Macaron] Completed /sid/kk-people.git/git-upload-pack 500 Internal Server Error in 24.429607ms

In my http log file I see the following

2015/12/19 18:25:28 [...routers/repo/http.go:370 serviceRpc()] [E] fail to serve RPC(upload-pack): exit status 128

I do not see a file called srv or serv in the log directory. Even though i have seen people referring to it.

**Comment by Unknwon** [comment]
Thanks your feedback!

But the logs you posted does not seem like you are push thought SSH? It is made by HTTP pushes.

**Comment by sid-kurias** [comment]
The push from my local dev machine to the gogs service is via ssh.

Dec 20 03:11:31 sshd[370]: Accepted publickey for git from 172.16.23.1 port 34829 ssh2: RSA SHA256:3OXR9T4LqlH9dkxBmIOFJWBMw4QIhCdWOGKzxmBHZDM
Dec 20 03:11:31 sshd[370]: Received disconnect from 172.16.23.1: 11: disconnected by user
Dec 20 03:11:31 sshd[370]: Disconnected from 172.16.23.1


Drone on the other hand seems to be using http to clone/fetch the repo before it does the build. Or at least that is what it seems like it is doing. 

But I have noticed the failure of git-update-pack is not consistent. Sometimes nothing happens.  Nothing is seen in the logs.

When I execute the *Test Delivery* I see the following in the logs

2015/12/20 03:17:00 [T] DeliverHooks [1]: processing delivery hooks
[Macaron] Completed /sid/kk-people/settings/hooks/1/test 200 OK in 57.612726ms
[Macaron] Started GET /api/v1/repos/sid/kk-people/raw/299ec8c1b71b5a99d8e5129297dd5d2aba351d0b/.drone.yml for 172.16.23.1
[Macaron] Completed /api/v1/repos/sid/kk-people/raw/299ec8c1b71b5a99d8e5129297dd5d2aba351d0b/.drone.yml 200 OK in 74.310495ms
[Macaron] Started GET /api/v1/repos/sid/kk-people/raw/299ec8c1b71b5a99d8e5129297dd5d2aba351d0b/.drone.sec for 172.16.23.1
[Macaron] Completed /api/v1/repos/sid/kk-people/raw/299ec8c1b71b5a99d8e5129297dd5d2aba351d0b/.drone.sec 200 OK in 73.508145ms
2015/12/20 03:17:01 [T] Hook delivered: 764a8b29-ca00-4eab-bec8-0c79ac74b937

That seems to work. The 172.16.23.1 is the address of the docker0 interface. 

It is quite possible that my configuration is messed up. I am not sure I have understood all the config options. Here is my custom config
APP_NAME = Gogs: Go Git Service
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE = postgres
HOST = 127.0.0.1:5432
NAME = gogs
USER = gogs
PASSWD =
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /data/git/gogs-repositories/

[server]
DOMAIN = 192.168.1.5
HTTP_PORT = 3000
ROOT_URL = http://192.168.1.5:30300/
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = true

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
DISABLE_REGISTRATION = false
ENABLE_CAPTCHA = true
REQUIRE_SIGNIN_VIEW = false

[picture]
DISABLE_GRAVATAR = false

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info

[security]
INSTALL_LOCK = true
SECRET_KEY = e7b71e321fbbdbc66a92bb3e239f77f2db34e7d6

[webhook]
DELIVER_TIMEOUT=120
SKIP_TLS_VERIFY=true

The repository is very small.  A Readme and minimum files for a dart program.

Thanks for looking into this. The project is really cool.

**Comment by Unknwon** [comment]
```
HTTP_PORT = 3000
ROOT_URL = http://192.168.1.5:30300/
```

OK... I may find the problem.

Try setting up https://github.com/gogits/gogs/blob/master/conf/app.ini#L54 to

```
LOCAL_ROOT_URL =  http://192.168.1.5:30300/
```

**Comment by sid-kurias** [comment]
Nothing wrong with the times other than they seem to be logged at utc.

Did modify the LOCAL_ROOT_URL and the SSH_PORT variables since the ssh server is running on 30022 not 22. There is some change that I observe.

1. The ssh push from local dev machine to gogs server does not cause the error I used to see. Also it does not trigger a build

Dec 20 10:45:27 sshd[73]: Accepted publickey for git from 172.16.23.1 port 42682 ssh2: RSA SHA256:3OXR9T4LqlH9dkxBmIOFJWBMw4QIhCdWOGKzxmBHZDM
Dec 20 10:45:27 sshd[73]: Received disconnect from 172.16.23.1: 11: disconnected by user
Dec 20 10:45:27 sshd[73]: Disconnected from 172.16.23.1

2. When I do run *Test Delivery* I get the following

[Macaron] Started POST /sid/kk-people/settings/hooks/1/test for 172.16.23.1
[Macaron] Completed /sid/kk-people/settings/hooks/1/test 200 OK in 581.752487ms
2015/12/20 10:46:06 [T] DeliverHooks [1]: processing delivery hooks
[Macaron] Started GET /api/v1/repos/sid/kk-people/raw/b3df69680c22967853129ef98aa045d1f7ffc6c6/.drone.yml for 172.16.23.1
[Macaron] Completed /api/v1/repos/sid/kk-people/raw/b3df69680c22967853129ef98aa045d1f7ffc6c6/.drone.yml 200 OK in 170.48547ms
[Macaron] Started GET /api/v1/repos/sid/kk-people/raw/b3df69680c22967853129ef98aa045d1f7ffc6c6/.drone.sec for 172.16.23.1
[Macaron] Completed /api/v1/repos/sid/kk-people/raw/b3df69680c22967853129ef98aa045d1f7ffc6c6/.drone.sec 200 OK in 110.905602ms
2015/12/20 10:46:07 [T] Hook delivered: d3a32078-26b0-4798-af8d-624ed086fa1b
[Macaron] Started GET /sid/kk-people/settings/hooks/1 for 172.16.23.1
[Macaron] Completed /sid/kk-people/settings/hooks/1 200 OK in 73.964811ms
[Macaron] Started GET /sid/kk-people.git/info/refs?service=git-upload-pack for 172.16.23.1
[Macaron] Completed /sid/kk-people.git/info/refs?service=git-upload-pack 200 OK in 149.882656ms

=====================
[Macaron] Started POST /sid/kk-people.git/git-upload-pack for 172.16.23.1
2015/12/20 10:46:20 http: multiple response.WriteHeader calls
[Macaron] Completed /sid/kk-people.git/git-upload-pack 500 Internal Server Error in 27.8611ms
[Macaron] Started POST /sid/kk-people.git/git-upload-pack for 172.16.23.1
[Macaron] Completed /sid/kk-people.git/git-upload-pack 200 OK in 769.579921ms

=====================

As you can see the request fails initially, seems to be retried and then works the second time.
 So the issue now is that the webhook is not getting triggered and notifying drone about the build.

hope that helps

**Comment by Unknwon** [comment]
Thanks. But I don't think you answered my question.

**Comment by Unknwon** [comment]
Attach a screenshot of recent history of that webhook is the best.

**Comment by sid-kurias** [comment]
attached is the screen shot for the payload url
http://192.168.1.5:31111/hook?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0Ijoic2lkL2trLXBlb3BsZSIsInR5cGUiOiJob29rIn0.eWPERRAX_MK3tBHqvuMJJQ4bD6PfiIqAvqQm9eWYPiU

![gogs-delivery](https://cloud.githubusercontent.com/assets/3319034/11917739/36c0c886-a73a-11e5-8df7-ffab6c8c2a41.png)

**Comment by sid-kurias** [comment]
with one delivery expanded
![gogs-payload](https://cloud.githubusercontent.com/assets/3319034/11917745/8f1451f6-a73a-11e5-91f1-dfb5cefcb1bf.png)

**Comment by Unknwon** [comment]
Sorry... hmm, I can't see the delivery time.

**Comment by Unknwon** [comment]
OK, so I'm confused.

Are those the history of "Test Delivery" or made by real pushes?

**Comment by sid-kurias** [comment]
no there is no history recorded for real pushes, nothing seems to happen The only time the history is recorded is when I hit the Test Delivery button.

![gogs-deliverytime](https://cloud.githubusercontent.com/assets/3319034/11917783/37c4eea4-a73c-11e5-8687-77b40566a248.png)
.

**Comment by Unknwon** [comment]
> no there is no history recorded for real pushes, nothing seems to happen

Please check `path/to/gogs/log/serv.log` and `path/to/gogs/log/update.log`.

**Comment by sid-kurias** [comment]
yes that is the funny thing. I do not see those log files. All I see are http.log, gogs.log and xorm.log and a symbolic link to /data/gogs/log, which seems to be a circular link. Is there any other place to look at?

**Comment by Unknwon** [comment]
I see you enabled Trace level logging, so there must be a `serv.log` file, otherwise you pushing is not delegated by Gogs.

What is your SSH push URL?

**Comment by sid-kurias** [comment]
ssh://git@192.168.1.5:30022/~/gogs-repositories/sid/kk-people.git

This is the section from the modified ini file. Modified for local host and ssh port as I had mentioned earlier

[server]
DOMAIN = 192.168.1.5
HTTP_PORT = 3000
ROOT_URL = http://192.168.1.5:30300/
LOCAL_ROOT_URL = http://192.168.1.5:30300/
DISABLE_SSH = false
SSH_PORT = 30022
OFFLINE_MODE = true

**Comment by Unknwon** [comment]
> ssh://git@192.168.1.5:30022/~/gogs-repositories/sid/kk-people.git

No, this is not right.

You have to:

1. Add your SSH key through web UI.
2. Use the SSH URL copied from web UI.
3. Push.

**Comment by sid-kurias** [comment]
That worked!!! Thank you.

Sorry about that,  I should have used the web interface from the start.

Thanks again

**Comment by Unknwon** [comment]
:clap: first good news today. :trollface:
