### ISSUE TITLE
Update, errors everywhere.

### ISSUE THREAD

**Issue by scuba323** [gogits/gogs#2249]
I just downloaded the latest version, and I am trying to run the script this is what I get.

    panic: template: user/settings/social:17: function "Oauth2Icon" not defined

[Full Paste](https://scuba323.com/url/JLXYt)

**Comment by jbub** [comment]
Did you update your templates ?

**Comment by Unknwon** [comment]
Hi, you must delete old `templates` directory and then put new ones.
