### ISSUE TITLE
Use HTTP/HTTPS as default clone option

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2250]
For example, it's selected for default HTTP/S to clone repository (as for a repository as all repositories, global)

Github, for example, has for default HTTP/S how choice recommended.

- Gogs
![gogs](http://s24.postimg.org/44op5kwp1/issue.png)

- GitHub

![](http://s4.postimg.org/51wp51yjx/issue.png)

Saludos! :+1: :smile:

**Comment by linquize** [comment]
Some users may think that HTTP(s)  is easier to set up.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I don't get the purpose of this?

Are you suggesting make HTTP/HTTPS as default option? Or something else?

Personally, I think SSH is much more fast and low memory cost.

**Comment by xxxtonixxx** [comment]
Yes, That is exactly! :+1: 

Hmm, but it would need a username and password or public key...

**Comment by Unknwon** [comment]
OK... yeah, so the purpose of this issue is:

change HTTP/HTTPS as default clone option?

**Comment by xxxtonixxx** [comment]
Yeah! :sweat_smile:

**Comment by Unknwon** [comment]
Thanks for clarifying!

**Comment by xxxtonixxx** [comment]
Thanks to you! :+1:

**Comment by Unknwon** [comment]
Please try out `develop` branch again!

**Comment by xxxtonixxx** [comment]
Ok, thank you very much! :smile:

I can't try develop branch... I will wait to try when it's in try.gogs.io :+1:

**Comment by Unknwon** [comment]
Updated demo side.

**Comment by xxxtonixxx** [comment]
Ok, I just understand you that you would say me. Sorry :sweat_smile:, I would want to say that we could choose (with a option in app.ini) HTTP/S or SSHW how our preference to all repositories of site.

**Comment by Unknwon** [comment]
> I would want to say that we could choose (with a option in app.ini) HTTP/S or SSH how our preference to all repositories of site.

I think this is an over-kill of a config option...

**Comment by xxxtonixxx** [comment]
Hmmm, ok, maybe when it's done custom templates, isn't it? I don't know :sweat: :laughing:

thanks!

**Comment by Unknwon** [comment]
Yeah, custom template is the ultimate solution to many problems.... LOL.

**Comment by xxxtonixxx** [comment]
irony? hahaha

**Comment by Unknwon** [comment]
So... what is the status of this issue now...?

**Comment by xxxtonixxx** [comment]
Hmm, I would say that it's closed

**Comment by Unknwon** [comment]
:trollface:

**Comment by linquize** [comment]
With current system,  you may disable SSH if you do not want your users to use.  Then http(s) will be the only option.

**Comment by linquize** [comment]
If the repo is public repo,  it does not make sense to require SSH.
