### ISSUE TITLE
Duplicate of files in directory

### ISSUE THREAD

**Issue by pudovmaxim** [gogits/gogs#2254]
I created project with silex-framework, commit first changes and then push it in remote repo under gogs. 

And at project's **var** folder, at gogs's fronted appear two same directory **cache** instead **cache** and **logs**. If I clone this repo, then all right. It is just relative to view. 

![gogs](https://cloud.githubusercontent.com/assets/5713098/11918314/b67b9db0-a73c-11e5-94d4-8ac981380a81.png)

It is copy of repo: https://github.com/pudovmaxim/overshovel/tree/master/var
And here all right too.

**Comment by pudovmaxim** [comment]
I added new directory into **var** and push it. Now, in **var** show 3 directories of **cache**.
I push through ssh and https. Same things.

Gogs version: 0.8.10.1217
Debian-8-x86_64 (2.6.32-042stab112.15)

**Comment by pudovmaxim** [comment]
Ok, in other repo, same thing. Here is 3 dirs:
- framework
 - cache
 - session
 - views

But repo at site looks like that:
![gogs](https://cloud.githubusercontent.com/assets/5713098/11918689/b962b6a2-a74c-11e5-9b53-f731bd6f5a5c.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by elzofranklin** [comment]
We are seeing this as well,  Can reproduce with very simple repository.

**Comment by pudovmaxim** [comment]
I did tested different causes. And this bug happens when in child's directories exist files with same content. For my cause it is .gitkeep files. Here repo for test:
https://github.com/pudovmaxim/gogs-bug-2254

At gogs I see correct **test** dir and it's content, but in **var** showed **app** dir many times.
![Screen](https://cloud.githubusercontent.com/assets/5713098/11991468/c8a226de-aa2b-11e5-8713-c509b1d3ed89.png)

**Comment by Unknwon** [comment]
@pudovmaxim thanks! Very helpful info!

**Comment by elzofranklin** [comment]
Thank you!

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging https://github.com/gogits/git-module/pull/3

**Comment by Unknwon** [comment]
ping @pudovmaxim

**Comment by pudovmaxim** [comment]
pong. I am updated gogs and now all work correctly. Thanks :)

**Comment by Unknwon** [comment]
:trollface:
