### ISSUE TITLE
Webhook: Send X-Hub-Signature header instead plain text secret in payload

### ISSUE THREAD

**Issue by LeKovr** [gogits/gogs#2256]
gogs sends plain text secret in payload:

``` json
{
  "secret": "****",

}
```

When is it planned to change to [X-Hub-Signature](https://developer.github.com/webhooks/) header?

**Comment by raphink** [comment]
For what it's worth, here is my bash implementation of GitHub's signature mechanism: https://github.com/camptocamp/docker-git-puppetmaster/blob/master/post-receive.d/25-push-to-r10k.sh

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/3692.
