### ISSUE TITLE
I/O error in serv.log

### ISSUE THREAD

**Issue by ptx0** [gogits/gogs#2259]
I run a Gogs setup behind a firewall and I see messages like these;
```
dial tcp 167.x.y.z:443: i/o timeout
```

Where `167.x.y.z` is the public IP of the HTTPD.

A side-effect of my firewall is that the VM cannot contact its own public IP.

**Comment by Unknwon** [comment]
Hi,

What is your version of Gogs?

If not the latest, please update and then give feedback again.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
