### ISSUE TITLE
Join all empty folder

### ISSUE THREAD

**Issue by BurakDev** [gogits/gogs#2260]
Hello, just a feature request

https://i.gyazo.com/c103c9ef849513596be5a9e2bc6e350b.png

For example Java projects contains a lot of empty folder containing sources files, it will be easier if we can jump to final folder directly like Github

**Comment by saboya** [comment]
Duplicate for #1149?

**Comment by Unknwon** [comment]
@saboya yeah, didn't notice that, thanks!
