### ISSUE TITLE
Fail to initialize ORM engine

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#2261]
I did an update from gogs 8.10 to 8.13. After copying my custom and data folder in to the gogs folder I got an error message:

    [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: Cannot add a NOT NULL column with default value NULL

I am using gogs with sqlite

**Comment by jbub** [comment]
There is 8.13 version available ?

**Comment by focmb** [comment]
0.8.13. Sorry, my fault

**Comment by acrade** [comment]
@angus-g Thanks，the problem is solved:grinning:

**Comment by focmb** [comment]
Fine. The solution of angus-g works. Thanks a lot

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging #2262
