### ISSUE TITLE
Monospace commit IDs on dashboard

### ISSUE THREAD

**Issue by rubenv** [gogits/gogs#2264]
Design suggestion: could we make commit IDs on the dashboard monospace? It'll look much nicer.

Here's the original version:

![screen shot 2015-12-22 at 09 55 10](https://cloud.githubusercontent.com/assets/42904/11951566/3e3d5fda-a892-11e5-92ff-87815e4a17d4.png)

Here's the version with monospace IDs:

![screen shot 2015-12-22 at 09 55 01](https://cloud.githubusercontent.com/assets/42904/11951570/476a23d6-a892-11e5-9b46-9d9270720cae.png)

Notice how everything is nicely aligned.

**Comment by BurakDev** [comment]
Nice idea @rubenv

**Comment by tkschmidt** [comment]
:+1: good idea

**Comment by Unknwon** [comment]
Please check out `develop` branch or test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Close as implemented.
