### ISSUE TITLE
Pushing a commit with emoji does not send a webhook and doesn't show the commit in dashboard

### ISSUE THREAD

**Issue by xPaw** [gogits/gogs#2265]
Try `git commit -a -m "🌟"` and push it. Commit is displayed fine in commit list, but it doesn't appear in dashboard, or user activity. And there was no webhook sent for this commit.

**Comment by Unknwon** [comment]
Please check your `path/to/gogs/log/serv.log` file see if any errors are there.

**Comment by xPaw** [comment]
This is most likely it:
```
2015/12/22 12:53:37 [...ts/gogs/cmd/serve.go:108 handleUpdateTask()] [E] Update: runUpdate.models.CommitRepoAction: NotifyWatchers: insert new actioner: Error 1366: Incorrect string value: '\xF0\x9F\x8C\x9F\n...' for column 'content' at row 1
```

Which means columns/connection to mysql isn't using utf8mb4

**Comment by Unknwon** [comment]
Oh.. OK. What is version of your MySQL?

**Comment by xPaw** [comment]
5.7, it doesn't really matter as `utf8` in mysql does not actually support full UTF-8, which is why `utf8mb4` needs to be used.

https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8mb4.html

https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by Unknwon** [comment]
Maybe minimum requirement of MySQL should be rise to 5.5.3 and set default encoding to `utf8mb4`?

**Comment by xPaw** [comment]
5.5.3 was released in 2010-03-24, I don't see why not.

**Comment by Unknwon** [comment]
OK, I'll update the docs.

**Comment by Unknwon** [comment]
Updated: https://gogs.io/docs/installation

**Comment by xPaw** [comment]
Are you going to create a migration to correct existing databases/tables? Keep in mind that opened connection needs to have correct charset set too.

**Comment by Unknwon** [comment]
> Are you going to create a migration to correct existing databases/tables? Keep in mind that opened connection needs to have correct charset set too.

I tested change a charset of MySQL database, and I think it handles automatically by xorm.

**Comment by Unknwon** [comment]
Close as fixed?

**Comment by xPaw** [comment]
I am running 0.9.13.0318, and this bug still exists. It still does not create webhook event for commits with emoji.
