### ISSUE TITLE
Strike through closed issue ids in commit list

### ISSUE THREAD

**Issue by lukasdietrich** [gogits/gogs#2266]
On Bitbucket the ids of closed issues are displayed crossed out.
I would like to have the ids on Gogs displayed the same way, to make it more clear, if a commit closes an issue or just references it.

**Comment by Unknwon** [comment]
Thanks your feedback!

This feature sounds cool, but requires a lot extra calculations for a quick thought.

Maybe you have something in mind?

**Comment by lukasdietrich** [comment]
Couldn't one use regular expressions in the frontend, the same way they are used to close issues in the backend ? I don't think that would slow down the page a lot.

What do you think ?

**Comment by Unknwon** [comment]
> I don't think that would slow down the page a lot.

Each issue needs an extra query (one page may have 10-50 issue IDs), things could be faster when Gogs has cache.

I'll leave it open and wait for application cache implementation.

**Comment by lukasdietrich** [comment]
> Each issue needs an extra query

What do you mean with query ?
I guess one could replace the generic id pattern in [markdown.go#RenderIssueIndexPattern](https://github.com/gogits/gogs/blob/master/modules/base/markdown.go#L153) with distinct patterns for references and closes, or am I missing something ?

**Comment by Unknwon** [comment]
> What do you mean with query ?

Database query.
