### ISSUE TITLE
Index number problem while creating Issue 

### ISSUE THREAD

**Issue by serkon** [gogits/gogs#2269]
Hi, i have upgrade gog to 0.8.10 version after that when i create new issue, index number start from one. I have change index number manually to latest index number but create new one again set index number to from two...

I have created new issue with in newly created milestone, before that i just added issues without milestone. Maybe problem was there. When create new issue in milestone index number start from "1" so when i click issue is not going correct issue. Going to old issue which created before that index.

**Comment by Unknwon** [comment]
Hi, can you reproduce this on https://try.gogs.io ?

**Comment by serkon** [comment]
Yes i tried this case in try.gogs.io, but everthing is gone fine... 
Maybe there was a problem on Database side. Did you change anything on database after gogs v.0.7.16?

You will see my test repo here https://try.gogs.io/srknc/test/issues

In my gog server repo when i click issue#3 that goes to issue#1 because index number has #1 in database...

**Comment by serkon** [comment]
In database i have update "num_issue" column on "repository" table to latest issue number. So problem was resolved for me. When i create new issue, index number starts latest index number now...

**Comment by Unknwon** [comment]
@serkon it's possible that you were in a state that Gogs had a index bug (somewhere in the issues) and made some actions based on that.

Latest release should work fine. :trollface:

**Comment by Unknwon** [comment]
Close as fixed?
