### ISSUE TITLE
tag 有问题

### ISSUE THREAD

**Issue by cyqluowang** [gogits/gogs#2271]
打了tag,显示不出来500

**Comment by cyqluowang** [comment]
![qq20151223-1 2x](https://cloud.githubusercontent.com/assets/5178594/11974513/c7dd67a4-a99f-11e5-9cbb-cb6b53723c2a.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

1. What is your version of Gogs?
2. What is the server error log?

**Comment by cyqluowang** [comment]
gogs version: 0.8.0.1212

the error in gogs.log:
[...routers/repo/view.go:132 Home()] [E] ListEntries: exit status 128 - fatal: not a tree object

**Comment by Unknwon** [comment]
Can you reproduce on demo site?

**Comment by cyqluowang** [comment]
i can reproduce on my site.用的是tower打的tags有问题，如果再网页端打tags没有发现问题，打好的tags代码看不了，但是可以下载zip.

**Comment by Unknwon** [comment]
Hi, can you reproduce on https://try.gogs.io/ ?

**Comment by Unknwon** [comment]
ping @cyqluowang

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by cyqluowang** [comment]
我在你们的网站还原不了。

**Comment by cyqluowang** [comment]
我是用tower打的标签，推送过来，显示的是不对的，但是如果直接在浏览器里打标签是可以的。

**Comment by Unknwon** [comment]
> 显示的是不对的，

What does this mean exactly?

And do not skip my comments:

- What is your version of Gogs?
- What is the server error log?
