### ISSUE TITLE
Negative commits

### ISSUE THREAD

**Issue by elvizlai** [gogits/gogs#2275]
version：0.8.10.1217

![qq20151224-0](https://cloud.githubusercontent.com/assets/501861/11988519/0f254b36-aa2c-11e5-98c3-fd66fdab5305.png)

Actually，there are no commits. Should be 0.

**Comment by Unknwon** [comment]
Can you reproduce this on https://try.gogs.io ?

And did you rebase or force push?

**Comment by Unknwon** [comment]
ping @ElvizLai

**Comment by xor-gate** [comment]
I have exactly the same problem by playing with gogs on the `try.gogs.io`:

https://try.gogs.io/admin1/cmaketest/releases

<img width="614" alt="screen shot 2016-01-02 at 20 33 25" src="https://cloud.githubusercontent.com/assets/1050166/12075869/1b6ccbb0-b190-11e5-9c67-a80b9474c3c0.png">

**Comment by Unknwon** [comment]
@xor-gate thanks!

Can you provide steps to reproduce this?

**Comment by xor-gate** [comment]
1. Mirror repo https://github.com/Eyescale/CMake
2. Select `2015.12` branch and create `0.0.1-beta` release
3. View the `-171 commits` in the release tab

Maybe this has something todo where Gogs looks as reference point against the release (git HEAD pointer)? Probably it sees there are 171 commits to "master" since the release?

**Comment by Unknwon** [comment]
Thanks again, but it still not very clear to me. I'll test out later ASAP.

**Comment by allonsy** [comment]
@xor-gate I'm unable to reproduce the error as mentioned (see my [mirror here](https://try.gogs.io/allonsy/Eyescale/releases)
Is the problem persisting for you still?

**Comment by xor-gate** [comment]
<img width="681" alt="screen shot 2016-03-11 at 21 13 40" src="https://cloud.githubusercontent.com/assets/1050166/13714412/a8a4f06a-e7ce-11e5-804b-9014d876d924.png">
<img width="706" alt="screen shot 2016-03-11 at 21 16 10" src="https://cloud.githubusercontent.com/assets/1050166/13714413/a8a52a8a-e7ce-11e5-9a24-ca484896ca42.png">

**Comment by allonsy** [comment]
I'm addressing the time issue in PR #2804

**Comment by aroma890225** [comment]
1. Create a release from one branch.
2. Delete this release.
3. Create a new release from other branch using the same Tag.

**Comment by allonsy** [comment]
Hmm, unable to reproduce still. Are you using the most recent develop code? Are you able to provide some screenshots?

**Comment by Unknwon** [comment]
Close as unable to reproduce.
