### ISSUE TITLE
Cannot add SSH key

### ISSUE THREAD

**Issue by wutongci** [gogits/gogs#2276]
很抱歉，我们无法验证您输入的 SSH 密钥：Invalid key format

添加ssh key的时候出现这个问题，key是可以添加进去github的

**Comment by jamadams** [comment]
I also am unable to add an SSH key. I have checked that there is no extra white space in the pasted data. The error returned is:

Sorry, we're not able to verify your SSH key: Invalid key format

**Comment by Unknwon** [comment]
Which key format you're using actually? SSH2?

**Comment by Unknwon** [comment]
Close due to lack of feedback.
