### ISSUE TITLE
Links to issues broken (404)

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#2278]
In commit overview (http://domain.tld/gogs/Organization/Project/commits/master), all links to issues in commmit messages are broken. They lead to http://domain.tld/gogs/Organization/issues/31 which results in 404. Correct would be http://domain.tld/gogs/Organization/Project/issues/31

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/2229
