### ISSUE TITLE
Merged commits not considered for issues

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#2279]
Steps to reproduce:
 - Check out repository twice, in a/ and b/
 - Create Issue #2
 - do something in a, commit -m "ref #2", push
 - do something in b, commit -m "ref #2", push
 - pushing to b shall fail: do git pull; commit the merge
 - push the merge
 - Go to issue #2 again, you will only see the commit from a/, not the one from b/

**Comment by Unknwon** [comment]
Hi, can you do this reproduce on https://try.gogs.io ?

**Comment by carli2** [comment]
I'm not able to reproduce. Maybe I'll need a newer version of gogs.
