### ISSUE TITLE
[Feature request] Log the client IP in the serv.log file

### ISSUE THREAD

**Issue by quantonganh** [gogits/gogs#2280]
I saw something like this in the `serv.log` file:

```
2015/12/24 15:17:03 [...ts/gogs/cmd/serve.go:212 runServ()] [F] Key access denied: 16-46
2015/12/24 15:18:04 [...ts/gogs/cmd/serve.go:212 runServ()] [F] Key access denied: 16-46
2015/12/24 15:18:05 [...ts/gogs/cmd/serve.go:212 runServ()] [F] Key access denied: 16-46
```

but I don't know which client caused this.

I would be helpful if we could log the client IP.

**Comment by Unknwon** [comment]
Hi, Gogs have no idea of client IP because it is called by SSH server.

BTW, this error only occurs when user tried to use a deploy key for the repositories that are not permitted.

**Comment by quantonganh** [comment]
I saw something like this in the `gogs.log`:

```
2015/12/27 00:22:19 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshaking: write tcp 107.170.x.y:22->222.186.z.t:2234: write: connection reset by peer
```

We cannot do the same for `serv.log`?

> BTW, this error only occurs when user tried to use a deploy key for the repositories that are not permitted.

I know that but I need to find out which is the culprit.

**Comment by quantonganh** [comment]
OK, I know the way to find out the client IP.

Commented out the log level in the config file to set it to the default value (Trace), then restart the gogs daemon. When an "Key access denied" error appear in the `serv.log` file, look at the `gogs.log`, search for that timestamp, you'll see something like this:

```
2015/12/30 05:18:12 [T] Connection from 128.199.x.x:37820 (SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3)
2015/12/30 05:18:12 [T] Payload: git-upload-pack 'dev/pillars.git'
2015/12/30 05:18:12 [T] Arguments: [serv key-16 --config=/etc/gogs.ini]
2015/12/30 05:18:12 [...s/modules/ssh/ssh.go:99 func1()] [E] Wait: exit status 1
```
