### ISSUE TITLE
500 Error on pull-compare-merge submission

### ISSUE THREAD

**Issue by techzilla** [gogits/gogs#2281]
Getting a 500 error after comparing a pull request, when I attempt to submit.

VERY much like,
https://github.com/gogits/gogs/issues/1711

gogs.log

    2015/12/24 11:25:44 [I] Log Mode: File(Info)
    2015/12/24 11:25:44 [I] Cache Service Enabled
    2015/12/24 11:25:44 [I] Session Service Enabled
    2015/12/24 11:25:44 [I] Mail Service Enabled
    2015/12/24 11:25:44 [I] Git Version: 1.7.1
    2015/12/24 11:25:44 [I] SQLite3 Supported
    2015/12/24 11:25:44 [I] Run Mode: Production
    2015/12/24 11:25:44 [I] Listen: http://127.0.0.1:8080

...

    2015/12/24 11:42:06 [...routers/repo/pull.go:632 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Clone: mkdir data: permission denied

xorm.log

    [xorm] [info]  2015/12/24 11:42:06.972990 [sql] INSERT INTO `action` (`user_id`, `op_type`, `act_user_id`, `act_user_name`, `act_email`, `repo_id`, `repo_user_name`, `repo_name`, `ref_name`, `is_private`, `content`, `created`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [args] [19 7 20 21807 21807@amtrustservices.com 104 Jenkins-CI winrm-plugin  false 1|avc 2015-12-24 16:42:06]
    [xorm] [debug] 2015/12/24 11:42:06.973081 [time] INSERT INTO `action` (`user_id`, `op_type`, `act_user_id`, `act_user_name`, `act_email`, `repo_id`, `repo_user_name`, `repo_name`, `ref_name`, `is_private`, `content`, `created`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) - args [19 7 20 21807 21807@amtrustservices.com 104 Jenkins-CI winrm-plugin  false 1|avc 2015-12-24 16:42:06] - execution took: 69621ns
    [xorm] [info]  2015/12/24 11:42:06.973301 [sql] ROLL BACK

I've also done a full reset on all permissions.

**Comment by Unknwon** [comment]
The error is very clear that is `permission denied`.

Make sure Gogs binary has permission to create `data` subdirectory under same directory.

**Comment by techzilla** [comment]
I'm not sure what directory your referring to as `data`, I have one that already exists, keep in mind other actions are working as expected.

drwxrwxr-x. git git unconfined_u:object_r:usr_t:s0   conf/
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   custom/
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   data/
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   etc/
    -rwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   gogs*
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   gogs-repositories/
    -rw-r--r--. git git unconfined_u:object_r:usr_t:s0   LICENSE
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   log/
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   public/
    -rw-r--r--. git git unconfined_u:object_r:usr_t:s0   README.md
    -rw-r--r--. git git unconfined_u:object_r:usr_t:s0   README_ZH.md
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   scripts/
    drwxr-xr-x. git git unconfined_u:object_r:usr_t:s0   templates/

**Comment by Unknwon** [comment]
Thanks your info, but I don't have any idea yet.

**Comment by vilppuvuorinen** [comment]
I am looking at this very same thing. The location of this elusive data directory does not seem all that constant and cannot be configured. The entire gogs home directory (`/gogs`) is writable by gogs user/process, but for some reason `data/tmp/local` exists outside of this path. 

Most likely the process is initialized from wrong directory context and gogs tries to create a directory to wrong path - like `/data` - which obviously is not going to work and certainly should not work. Maybe the location of the `data/tmp` dir should be configurable after all. Otherwise I'll have to resort to guesswork to create suitable symlink to get the data on an external volume.

**Comment by techzilla** [comment]
@vilppuvuorinen 

Thank you for posting that info, it wasn’t working with my init script due to doing a chdir before starting the process.

**Comment by bkcsoft** [comment]
@vilppuvuorinen the data directory is configurable with envvar `GOGS_CUSTOM`
source: https://github.com/gogits/gogs/blob/7ef9a055886574655d9f2be70c957bc16bf30500/modules/setting/setting.go#L263-L270

**Comment by vilppuvuorinen** [comment]
Aren't `/data` and `/custom` pretty much parallel elements in the directory structure and both of them are located inside the presumed `gogs` directory?

If `GOGS_CUSTOM` really can be used to move the `/data` dir, it is more of a design issue than fix. I did not go through the code, but I hope I would not find the following statement in there:

```go
DataPath = CustomPath + "/../data"
```

**Comment by bkcsoft** [comment]
heh, I confused `/data` and `/custom` ^.^ `/data` is hard-coded here https://github.com/gogits/gogs/blob/7ef9a055886574655d9f2be70c957bc16bf30500/modules/setting/setting.go#L56

**Comment by Unknwon** [comment]
Maybe we could use `GOGS_DATA` to config `/data` path as well?
