### ISSUE TITLE
Does not show correct character when use UTF-8

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2282]
I have verified the encoding of text from Linux and this return `text/x-python; charset=utf-8`

I have uploaded the code when I have the problem [in try.gogs](https://try.gogs.io/xxxtonixxx/Python/src/master/passwordGenerator.py#L52), that character must be `í` but it doesn't show how it must...

Saludos! :+1: :smile:

**Comment by Unknwon** [comment]
>  that character must be í but it doesn't show how it must...

Which character?

**Comment by xxxtonixxx** [comment]
Sorry!!! I'm stupid :sweat_smile:

This character `Ã`, It must be `í`

![image](https://cloud.githubusercontent.com/assets/7110786/11998987/e9f6e20a-aab4-11e5-918c-c3326561e94e.png)

**Comment by Unknwon** [comment]
Thanks! So the file encoding is `utf-8`?

**Comment by xxxtonixxx** [comment]
Yeah. And It has been created with Atom editor.

**Comment by Unknwon** [comment]
OK, fixes have been pushed to `develop` branch and you can test on https://try.gogs.io/xxxtonixxx/Python/src/master/passwordGenerator.py#L52 as well.

**Comment by xxxtonixxx** [comment]
It seems that it's ok! Thank you very much! :smile: :+1:

**Comment by mukaiu** [comment]
![image](https://cloud.githubusercontent.com/assets/7746790/12006777/66437218-ac1f-11e5-8349-1adffffc2e79.png)

刚才测试了下，try上还存在此问题~

**Comment by Unknwon** [comment]
@mukaiu the URL is...?

**Comment by Unknwon** [comment]
@mukaiu just pushed another commit, diff should be fixed as well.

**Comment by mukaiu** [comment]
太激动了，，diff页面~

**Comment by mukaiu** [comment]
赞，try上面已经没有问题了

**Comment by Unknwon** [comment]
Close as fixed.
