### ISSUE TITLE
HTML pages are rendered in raw mode

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2283]
When I show a HTML file in RAW mode, this doesn't show its code, this is being rendering when It mustn't be so.

- Example
![image](https://cloud.githubusercontent.com/assets/7110786/11999028/92ab0750-aab5-11e5-9724-7942180ef2da.png)

Saludos! :+1:

**Comment by Unknwon** [comment]
Can you reproduce this on https://try.gogs.io ?

**Comment by xxxtonixxx** [comment]
Yeah! [Here is](https://try.gogs.io/xxxtonixxx/bug_html_rendering_raw_mode/src/master/toni/LenMar/HTML/index.html)! :+1:

**Comment by Unknwon** [comment]
Thanks! How does GitHub handles it?

I think this is expected behavior. Gogs does not give any assumption for raw format of content, and browser determines it automatically. 

Since you use `.html` as extension, it is reasonable that browser treats it as an HTML page.

**Comment by xxxtonixxx** [comment]
Yeah, I thought same, but GitHub use the `<pre>` tag.

For example, [a web page in RAW mode of GitHub](https://raw.githubusercontent.com/adobe/brackets/d939740fd5c368c347ac6a8c7cef2941981aa2fb/samples/da/Kom%20godt%20i%20gang/index.html)

**Comment by Unknwon** [comment]
> but GitHub use the <pre> tag.

How do you know?

**Comment by xxxtonixxx** [comment]
Thanks to inspect element of Chrome...

![image](https://cloud.githubusercontent.com/assets/7110786/11999333/894697e6-aabb-11e5-8cd9-25fbe9ba605a.png)

**Comment by xxxtonixxx** [comment]
So, the HTML text isn't interpreted by browser :+1:

**Comment by Unknwon** [comment]
I see. I think GitHub only does this for `.html` and `.xml`?

**Comment by xxxtonixxx** [comment]
I think that for all of them. I'm just see that javascript and php text use it too.

**Comment by Unknwon** [comment]
OK... I think it involves something else bigger... I believe if you do `curl xxx`, GitHub responses pure raw content of any types.

**Comment by xxxtonixxx** [comment]
It's possible!

**Comment by novaeye** [comment]
how about this:
```go
func ServeData(ctx *middleware.Context, name string, reader io.Reader) error {
	buf := make([]byte, 1024)
	n, _ := reader.Read(buf)
	if n > 0 {
		buf = buf[:n]
	}

	_, isTextFile := base.IsTextFile(buf)
	if !isTextFile {
		_, isImageFile := base.IsImageFile(buf)
		if !isImageFile {
			ctx.Resp.Header().Set("Content-Disposition", "attachment; filename="+path.Base(ctx.Repo.TreeName))
			ctx.Resp.Header().Set("Content-Transfer-Encoding", "binary")
		}
	} else {
		ctx.Resp.Header().Set("Content-Type", "text/plain; charset=utf-8") // <<<<<<
	}
	ctx.Resp.Write(buf)
	_, err := io.Copy(ctx.Resp, reader)
	return err
}

```

**Comment by novaeye** [comment]
@xxxtonixxx I think it is a feature of the browser(FF/IE/Chrome), not github

**Comment by xxxtonixxx** [comment]
@novaeye Hmmm, It's true that in source code doesn't appear the `<pre>` tag ... Good catch! :+1:

**Comment by Unknwon** [comment]
Thanks @novaeye !

@xxxtonixxx here we go: https://try.gogs.io/xxxtonixxx/bug_html_rendering_raw_mode/raw/master/toni/LenMar/HTML/index.html

**Comment by xxxtonixxx** [comment]
It's ok! but... There is a problem with encoding characters (áéíóú...).

- These show so:
![image](https://cloud.githubusercontent.com/assets/7110786/12004111/8dce81ce-ab3e-11e5-9457-02aac21f0e52.png)

- And these must show [so](https://try.gogs.io/xxxtonixxx/bug_html_rendering_raw_mode/src/master/toni/LenMar/HTML/index.html#L5):
![image](https://cloud.githubusercontent.com/assets/7110786/12004113/d2e1a16a-ab3e-11e5-9ac3-7989cb07c961.png)

**Comment by andreynering** [comment]
Github raw view shows files with `Content-Type: text`. This means that neither HTML, CSS or JS can be used directly in web pages.

There's a services that serve files from Github with proper content type headers: https://rawgit.com

Maybe in Gogs we could have a URL parameter to it: `http://.../index.html?raw=1`. So people could still use files directly if they want.

(I think it should default to false if not provided so something like `<style href="my.css">` will work by default in a web page, without having to add `?raw=1`).

**Comment by xxxtonixxx** [comment]
That will be interesnting :+1:, but... to work from the address bar doesn't think that it's the best way...

**Comment by Unknwon** [comment]
@xxxtonixxx your screenshots more like browser auto-detection thing for me. My Chrome show what I expect:

![image](https://cloud.githubusercontent.com/assets/2946214/12012320/f54aafec-acbc-11e5-86bf-5ca848decb41.png)

**Comment by xxxtonixxx** [comment]
Ok! I already have changed and right now it's working... but, it's strange that with GitHub's raw mode was working without I change nothing... With Firefox was equal but with IE is working good!

Thank you!!! :smile: :+1:

**Comment by Unknwon** [comment]
@xxxtonixxx GitHub may did a encoding transformation, but Gogs serves "raw" from Git blob.

**Comment by pykiss** [comment]
what if somebody want a raw html rendered.

To get something like gitpages, or so.

Use case:
I want to have a tiddlywiky in my repo, and to serve it directly from gogs.

**Comment by Unknwon** [comment]
@pykiss Hmm... maybe you can file another issue and ask likes `Allow request header to set HTML rendered` in raw mode?

**Comment by tkschmidt** [comment]
@pykiss have you already filed a new issue? I would also have such a feature back. All my analysis in R (statistics) are rendered in the end to a html page. Normally I just compare different reports by looking in my git history but now it is broken. It worked until last release.

![image](https://cloud.githubusercontent.com/assets/409660/12941407/4dd4e58c-cfd2-11e5-9746-3d4ea326dcf1.png)

**Comment by Unknwon** [comment]
@tkschmidt 

> Normally I just compare different reports by looking in my git history but now it is broken. It worked until last release.

What does this mean specifically?

**Comment by tkschmidt** [comment]
sry, for bad wording. Until last release while looking at the raw file type i got my rendered html. Now, because it is wrapped into another html it is broken and I get the view above.

**Comment by Unknwon** [comment]
@tkschmidt OK.. I think this is intended to not render. 

You may want to follow up on https://github.com/gogits/gogs/issues/2593

**Comment by Antisunny** [comment]
Still unsolved?

I wget a python file via its raw url, but the downloaded file is in html format ???????
