### ISSUE TITLE
仓库点击去显示500

### ISSUE THREAD

**Issue by xiuchanghu** [gogits/gogs#2284]
仓库点击去显示500，Internal Server Error

**Comment by xiuchanghu** [comment]
是什么原因呢

**Comment by xiuchanghu** [comment]
[xorm] [info]  2015/12/25 10:43:45.260359 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/12/25 10:43:45.262700 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/12/25 10:43:45.264724 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `lower_name` = ? LIMIT 1 [args] [chuangwei]
[xorm] [info]  2015/12/25 10:43:45.266827 [sql] SELECT `id`, `owner_id`, `lower_name`, `name`, `description`, `website`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_bare`, `is_mirror`, `enable_wiki`, `enable_issues`, `enable_external_tracker`, `external_tracker_format`, `enable_pulls`, `is_fork`, `fork_id`, `created`, `updated` FROM `repository` WHERE `owner_id` = ? AND `lower_name` = ? LIMIT 1 [args] [3 jkgz_api]
[xorm] [info]  2015/12/25 10:43:45.268768 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [3]
[xorm] [info]  2015/12/25 10:43:45.276345 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [2 9]
[xorm] [info]  2015/12/25 10:43:45.277747 [sql] SELECT `id`, `uid`, `repo_id` FROM `star` WHERE `uid` = ? AND `repo_id` = ? LIMIT 1 [args] [2 9]
[xorm] [info]  2015/12/25 10:47:12.281353 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [2]
[xorm] [info]  2015/12/25 10:47:12.296153 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [2]

**Comment by Unknwon** [comment]
1. What is version of your Gogs?
2. What is server side error log (not database log)?

**Comment by xiuchanghu** [comment]
Gogs 当前版本: 0.7.33.1205 Beta

**Comment by Unknwon** [comment]
Thanks. But do not skip my questions.

**Comment by xiuchanghu** [comment]
我看得xorm.log日志

**Comment by xiuchanghu** [comment]
好的

**Comment by xiuchanghu** [comment]
我升级一下看下

**Comment by Unknwon** [comment]
Check your `path/to/gogs/log/gogs.log` file.

**Comment by xiuchanghu** [comment]
升级后问题解决了，tks！

**Comment by Unknwon** [comment]
:trollface:
