### ISSUE TITLE
ssh: unexpected message type 1 (expected 50)

### ISSUE THREAD

**Issue by gclove** [gogits/gogs#2285]
SSH 功能现在是不是还有问题哈 ?

具体表现是内置 SSH  不会要求输入用户名密码 (只能用 SSH KEY)

2015/12/25 13:24:11 [I] Log Mode: File(Info)
2015/12/25 13:24:11 [I] Cache Service Enabled
2015/12/25 13:24:11 [I] Session Service Enabled
2015/12/25 13:24:11 [I] Mail Service Enabled
2015/12/25 13:24:11 [I] Register Mail Service Enabled
2015/12/25 13:24:11 [I] Notify Mail Service Enabled
2015/12/25 13:24:11 [I] Git Version: 2.6.4
2015/12/25 13:24:11 [I] SQLite3 Supported
2015/12/25 13:24:11 [I] Run Mode: Production
2015/12/25 13:24:11 [I] SSH server started on :22
2015/12/25 13:24:11 [I] Listen: http://0.0.0.0:3000
2015/12/25 13:24:20 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshaking: ssh: unexpected message type 1 (expected 50)
2015/12/25 13:24:23 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshaking: ssh: unexpected message type 1 (expected 50)

**Comment by gclove** [comment]
SMTP 的原因好像是 ：
registration notify - gomail: could not send email 1: missing port in address smtp.aliyun.com

**Comment by Unknwon** [comment]
You need a port after `smtp.aliyun.com`.

**Comment by Unknwon** [comment]
> ssh: unexpected message type 1 (expected 50)

It should be a bug in Go's stdlib, seeking for solutions...

**Comment by quantonganh** [comment]
I also got this problem:

```
2016/01/04 01:38:33 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshaking: ssh: unexpected message type 1 (expected 50)
2016/01/04 01:38:35 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshaking: ssh: unexpected message type 1 (expected 50)
2016/01/04 01:38:37 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshaking: ssh: unexpected message type 1 (expected 50)
```

It happened a lot and I'm not sure it's reason that caused the built-in ssh server [seems to be hang](https://github.com/gogits/gogs/issues/1681#issuecomment-167065203) or not.

**Comment by Unknwon** [comment]
Following along [this thread](https://github.com/coreos/fleet/issues/565#event-609751312), I think upstream repo has fixed the problem.
