### ISSUE TITLE
Can't display minus sign (-) correctly when file is txt  

### ISSUE THREAD

**Issue by jenningsloy318** [gogits/gogs#2286]
I push a txt file which contains the minus sign (e.g -1) will  be display as " â€“ " in the web page, but when i view   the original file, it is correct.

Type            number of bypes                             Range of value
------------------------------------------------------------------------------------
char                    1                                           â€“128 to +127 or 0 to +255

should be
 
char                    1                                           -128 to +127 or 0 to +255

Environment:
gogs: 0.8.10 
OS: ubuntu 15.04
git: 2.1.4

**Comment by Unknwon** [comment]
Can you reproduce on https://try.gogs.io ?

**Comment by yurivict** [comment]
@jenningsloy318  You might have some unicode character for "minus". Please look at it in hexffump or hd. Gogs should still understand such symbol.

**Comment by yurivict** [comment]
I can't confirm after trying few unicode '-' characters.

Gogs prints unicode characters from particular source files as-is, and page has charset=UTF-8. 

So the user needs to provide what character this was in hex, what browser/OS did he use.

**Comment by jenningsloy318** [comment]
I used the VIM to edit the file. 
when i ued hex edit to display the -, it give me 

 â --->20

**Comment by jenningsloy318** [comment]
I used the VIM to edit the file., and VIM shows me that the file is UTF-8.
HEX shows the character (-) is E2

not tested in try.gogs.io

**Comment by Unknwon** [comment]
Please reproduce on demo site, otherwise we can't help and no idea of what is going on.

**Comment by jenningsloy318** [comment]
Tested in try.gogs.io, but it displays normal.
Is there any other config relevant with this?

**Comment by Unknwon** [comment]
No config, maybe you need to upgrade?

**Comment by jenningsloy318** [comment]
wii try to edit the file and re-push again to see if this issue is fixed.

**Comment by jenningsloy318** [comment]
I found that gogs can't display the "±"      " ’ " used in  isn’t .

**Comment by Unknwon** [comment]
Sorry, I dont know what you are talking until you can show us on the demo site.

**Comment by yurivict** [comment]
@jenningsloy318 : The way to deal with such problem:
1. What does hexdump say the characters hex representation is?
2. What does the 'file' utility say the file encoding is?
3. Does the source of the gogs html page have "<meta charset='utf-8'>" in it?
4. What browser do you use? Did you try another browser? (chrome, firefox, opera)

Because I can't reproduce the problem.

**Comment by jenningsloy318** [comment]
I can't  get this situation react, will close this issue.
