### ISSUE TITLE
Allow users without account create issues and pull requests

### ISSUE THREAD

**Issue by M5oul** [gogits/gogs#2289]
Thanks for the hard work.

I'm running a Gogs instance on [YunoHost](https://yunohost.org/) thanks to [a Gogs package integration](https://github.com/mbugeia/gogs_ynh).

Gogs is working well for mono user, but external users needs an accounts to contribute.

My main issue to really use it is that only YunoHost users based on LDAP users can contribute to Gogs repositories.

I can create an account for people who ask me, but it's not enough.

I think we should allow people without account to create issues and pull requests to permit external contributions.

That's the main issue with many Gogs instances (decentralized), you need many accounts not like with GitHub where all repositories and accounts are centralized.

Issues and pull requests forms could ask for their email address to identify contributors.

Issue of that feature is spam, like blogs are countering on comments with captcha to prevent bot spam.

**Comment by Unknwon** [comment]
Thanks your feedback!

Gogs needs something (user ID) to track user-issue relations which requires someone must register first.

It sounds great, but I don't think it's going to be implemented.

**Comment by stevenroose** [comment]
Ideally, for myself, I would not like users without accounts to be able to file PRs. I would prefer for them to be authenticated using OpenID, so that they can use their own GitHub account or the like to do that.
They do not need to be LDAP users, though.

**Comment by stevenroose** [comment]
So, ideally, LDAP users can login directly into Gogs using their LDAP credentials, while "guests", as I call them, can use OpenID to give feedback.

**Comment by stonerl** [comment]
I don't think it is a good idea to allow everyone to add issues and PRs. This could be used to spam your Gogs installation, hence there is a reason why many project only allow editing e.g. their wikis for registered users.

**Comment by Unknwon** [comment]
Ping @M5oul ?

**Comment by stevenroose** [comment]
@Unknwon OpenID is supported, right? I can't seem to find anything about it even though I thought it was...

**Comment by Unknwon** [comment]
@stevenroose It is not..

**Comment by stevenroose** [comment]
@Unknwon Damnit. Is it on the todo list? Would be awesome if the scenario I
described above would be possible!

**Comment by Unknwon** [comment]
@stevenroose opened an old issue from you.

**Comment by Unknwon** [comment]
ping @M5oul

**Comment by M5oul** [comment]
[OpenID](https://github.com/gogits/gogs/issues/1297) is a better proposition than my idea.

**Comment by Unknwon** [comment]
@M5oul thanks for following up!

So I'm going to do is close this one and let you follow on https://github.com/gogits/gogs/issues/1297
