### ISSUE TITLE
Some link is broken

### ISSUE THREAD

**Issue by imbear** [gogits/gogs#2295]
https://store.lertsenem.com/syncthing-ppc/Xcompile_syncthing_for_ppc_recipe.html

**Comment by Unknwon** [comment]
What is this link supposed to mean?

**Comment by stonerl** [comment]
@imbear Whatever your link is supposed to mean your running an outdated version of gogs: `0.6.13.0918` please upgrade first, check again whether your problems exists and if so, please elaborate in more detail.
