### ISSUE TITLE
multiple 0-byte filenames are bundled into one

### ISSUE THREAD

**Issue by initbar** [gogits/gogs#2297]
> Bug Description

I have created a [test repository](https://try.gogs.io/j1236242/test/src/master/0ByteTest) with the following directory structure:

```
[root]
  |-- README.md
  \-- 0ByteTest
       |-- __init__.py (0B)
       |-- pre.py (0B)
       \-- post.py (24B)
```

Locally, the files are shown correctly as needed:

![bug](https://cloud.githubusercontent.com/assets/12630151/12019857/86e249de-ad43-11e5-903f-c836d81ab879.png)

However, on Gogs, the two empty files (`pre.py` and `__init__.py`) are displayed as two `pre.py`s.

![bug2](https://cloud.githubusercontent.com/assets/12630151/12019880/bb109c38-ad43-11e5-8581-2b2a54af7213.png)

> Gogs Version

`© 2015 Gogs Version: 0.8.13.1227`

> Git Version

`Git 1.9.1`

> System Type

Ubuntu x64 (`Linux dv0rak 3.19.0-30-generic #34~14.04.1-Ubuntu SMP Fri Oct 2 22:09:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`)

> Error Log

N/A

> Other information

I think it's just a web UI bug because filenames are untouched when cloned back from the repo:

![bug3](https://cloud.githubusercontent.com/assets/12630151/12020017/40a6e9b4-ad45-11e5-8e8f-2ee0ffd0614b.png)

**Comment by novaeye** [comment]
maybe same problem with #2254 ?

**Comment by initbar** [comment]
Oh, yes - sorry I might have skipped over that issue when I was looking for related ones. Should I close this?

**Comment by Unknwon** [comment]
Yes, @novaeye is correct. It is caused by the same reason of #2254 .
