### ISSUE TITLE
page cannot loaded (Diff data too large)

### ISSUE THREAD

**Issue by kakhavk** [gogits/gogs#2303]
Some commit which has many changes I want to open repository with this commit, gogs server is waiting for long time.

Other commits can open without problem

log looks like this:

Dec 30 12:55:19 local gogs: [Macaron] Started GET /commit/b4babb781daf3ebf9482b9a647d2eef4a3..... for 127.0.0.1
Dec 30 12:55:20 local gogs: 2015/12/30 12:55:20 #033[1;33m[W] Diff data too large#033[0m

**Comment by kakhavk** [comment]
I solved this problem by increasing MAX_GIT_DIFF_LINES

**Comment by Unknwon** [comment]
Close as fixed?

**Comment by kakhavk** [comment]
Yes  thanks
