### ISSUE TITLE
Webhooks no longer working

### ISSUE THREAD

**Issue by bashtoni** [gogits/gogs#2304]
When I upgraded to Gogs 0.8.10 from 0.7.33 webhooks stopped working.

On further investigation I see an error like this in the logs whenever a webhook should be sent.  This occurs both with Slack webhooks and Gogs webhooks.

`http: TLS handshake error from [::1]:42335: tls: first record does not look like a TLS handshake`

I've pasted in the `[server]` section of my config below.

```
[server]
PROTOCOL = https
DOMAIN = gogs.<redacted>
ROOT_URL = https://git.<redacted>/
HTTP_ADDR = 
; We need HTTP_PORT to be unprivileged
; It gets remapped by Kubernetes
HTTP_PORT = 3000
SSH_PORT = 22
OFFLINE_MODE = false
DISABLE_ROUTER_LOG = false
CERT_FILE = custom/https/gogs.crt
KEY_FILE = custom/https/gogs.key
STATIC_ROOT_PATH = 
ENABLE_GZIP = true
LANDING_PAGE = home
```

**Comment by Unknwon** [comment]
Thanks your feedback!

> http: TLS handshake error from [::1]:42335: tls: first record does not look like a TLS handshake

Where did you find this?

**Comment by bashtoni** [comment]
This is from the gogs log - everything is being logged to the console (Gogs is running in a container).

**Comment by Unknwon** [comment]
Please post full line of log.

**Comment by bashtoni** [comment]
Unfortunately that's the full log line.  Here are the entries logged after every push today.
```
2015/12/31 08:30:25 http: TLS handshake error from [::1]:41533: tls: first record does not look like a TLS handshake
2015/12/31 08:51:25 http: TLS handshake error from [::1]:49102: tls: first record does not look like a TLS handshake
2015/12/31 10:38:25 http: TLS handshake error from [::1]:58945: tls: first record does not look like a TLS handshake
2015/12/31 14:45:34 http: TLS handshake error from [::1]:60529: tls: first record does not look like a TLS handshake
```

**Comment by Unknwon** [comment]
Please post errors in `path/to/gogs/log/serv.log` here.

**Comment by bashtoni** [comment]
OK this gives some more details - it seems to be trying to trigger the task via a callback over HTTP instead of HTTPS?

```
2016/01/05 08:50:06 [T] Trigger task: http://localhost:3000/Bashton/redacted/tasks/trigger?branch=master&secret=f7cc9e8f355ef6ad680b70631e277744
2016/01/05 08:50:06 [...ts/gogs/cmd/serve.go:126 handleUpdateTask()] [E] Fail to trigger task: Head http://localhost:3000/Bashton/redacted/tasks/trigger?branch=master&secret=f7cc9e8f355ef6ad680b70631e277744: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

**Comment by Unknwon** [comment]
You may want to change this value: https://github.com/gogits/gogs/blob/master/conf/app.ini#L54

**Comment by bashtoni** [comment]
Thanks, that fixed it!

**Comment by Unknwon** [comment]
:trollface:
