### ISSUE TITLE
Branches page

### ISSUE THREAD

**Issue by pentix** [gogits/gogs#2310]
This is a feature request:

I'd love to have a page integrated in gogs similar to gogs' page on GitHub (https://github.com/gogits/gogs/branches). ~~It could be extended to compare branches over forks like this: (https://github.com/gogits/gogs/network)~~

**Comment by pentix** [comment]
Any updates here? I tried to understand gogs models & code to try to implement this at my own, however I'm new to Go, those Templates and I don't understand gogs structure fully. 

AFAIK, there is no branch struct/class to check the last modification date, is there?

**Comment by Unknwon** [comment]
Sad but nothing happens about this... but there is a PR for API to list all branches of given repository.

**Comment by pentix** [comment]
@Unknwon  Thanks for pinging. Looks like PR #2419 would implement #2410 and give an easy solution to access the branches. I'll try again to implement this as soon as #2419 has been merged.

**Comment by sapk** [comment]
The API is implemented and merge in dev in PR #2506. You may need some extra info to show all the same information as in the example.

**Comment by pentix** [comment]
Thank you @sapk ! I'll have a look at it!

**Comment by Unknwon** [comment]
Limit this issue only about **branches**, **forks** merges to https://github.com/gogits/gogs/issues/19.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/gogs/gogs/branches.

**Comment by pentix** [comment]
Works on try.gogs.io perfectly for me! +1
