### ISSUE TITLE
"no basic auth and digit auth" when user tries to push to repo without write permission

### ISSUE THREAD

**Issue by danielskowronski** [gogits/gogs#2311]
When user does not have write permission (read only) and tries to push there is strange error - "no basic auth and digit auth". I've found in gogs sources it's HTTP 401. 
I think message should be more accurate.
![gogs_auth_failed](https://cloud.githubusercontent.com/assets/8194525/12058819/9f835d7a-af50-11e5-98f3-7c59b41a1be7.png)
I'm using version 0.8.10.1217 on Windows with sqlite database.

**Comment by Unknwon** [comment]
Pushed something to `develop` branch, please checkout.

**Comment by Unknwon** [comment]
Close as fixed.
