### ISSUE TITLE
升级新版本git出现 wiki不能提交的错误

### ISSUE THREAD

**Issue by mindfocus** [gogits/gogs#2314]
Git版本从1.9升级到了2.6 
Gogs版本 0.8.10.1217
升级git版本以后wiki不能编辑了，错误为 
Updatelocalwiki:pull:exit status 128 -fatal:not a git repo 
但是新创建的版本库可以提交wiki
并且通过客户端git也可以提交gogs提交出错的版本库的wiki
希望您能帮忙解决一下
谢谢啦

**Comment by Unknwon** [comment]
I think you have also changed the Gogs `REPO_ROOT_PATH`?

Delete `path/to/gogs/data/tmp` should solve the problem.

**Comment by mindfocus** [comment]
没有任何改动
只有升级git版本
我解决这个问题的方法是删除了重新建立
就好了

**Comment by Unknwon** [comment]
OK.... has the problem solved?

**Comment by mindfocus** [comment]
yeah,解决嘞...谢谢

**Comment by Unknwon** [comment]
:trollface:
