### ISSUE TITLE
panic: template: repo/view_list:33: function "AppUrl" not defined

### ISSUE THREAD

**Issue by codewisdom** [gogits/gogs#2318]
Getting the exception above when upgrading to 0.8.10.

simply running:
`./gogs web`

Requested info:

* Gogs Version: 0.8.10.1217
* Git Version: 2.6.3
* System Type: FreeBSD 9.3
* Error log:
```
    goroutine 1 [running]:
    html/template.Must(0x0, 0x801e91028, 0xc820197920, 0x0) /usr/local/go/src/html/template/template.go:330 +0x4b
    gopkg.in/macaron%2ev1.compile(0xc82035ada0, 0x1b, 0x0, 0x0, 0xc82035adc0, 0x2, 0x2,     0xc82036c0b0, 0x1, 0x1, ...)
    /home/gogs/go/src/gopkg.in/macaron.v1/render.go:244 +0x98e gopkg.in/macaron%2ev1.    (*templateSet).Set(0xc82040cab0, 0x1001960, 0x7, 0xc8203a6380, 0x0)
    /home/gogs/go/src/gopkg.in/macaron.v1/render.go:269 +0x4a
    gopkg.in/macaron%2ev1.renderHandler(0xc82035ada0, 0x1b, 0x0, 0x0, 0xc82035adc0, 0x2, 0x2,     0xc82036c0b0, 0x1, 0x1, ...)
    /home/gogs/go/src/gopkg.in/macaron.v1/render.go:336 +0x211
    gopkg.in/macaron%2ev1.Renderer(0xc820594b68, 0x1, 0x1, 0x0, 0x0)
    /home/gogs/go/src/gopkg.in/macaron.v1/render.go:373 +0x1ee
    github.com/gogits/gogs/cmd.newMacaron(0xc8202926c0)
    /home/gogs/go/src/github.com/gogits/gogs/cmd/web.go:127 +0x768
    github.com/gogits/gogs/cmd.runWeb(0xc8202926c0)
    /home/gogs/go/src/github.com/gogits/gogs/cmd/web.go:180 +0xc2
    github.com/codegangsta/cli.Command.Run(0x100d8b8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x109ec50,     0x15, 0x11633e0, ...)
    /home/gogs/go/src/github.com/codegangsta/cli/command.go:137 +0x107e
    github.com/codegangsta/cli.(*App).Run(0xc820292480, 0xc82000a160, 0x2, 0x2, 0x0, 0x0)
    /home/gogs/go/src/github.com/codegangsta/cli/app.go:175 +0xfff
    main.main()
    /home/gogs/gogsrv/gogs.go:40 +0x35c

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

    goroutine 5 [select]:
    github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc82004dcc0)
    /home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
    created by github.com/gogits/gogs/modules/log.newLogger
    /home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

    goroutine 13 [select]:
    github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc8202d62c0)
    /home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
    created by github.com/gogits/gogs/modules/log.newLogger
    /home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

    goroutine 14 [chan receive]:
   github.com/gogits/gogs/modules/mailer.processMailQueue()
    /home/gogs/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:186 +0x94
    created by github.com/gogits/gogs/modules/mailer.NewContext
    /home/gogs/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:205 +0x72

    goroutine 39 [select]:
    github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820410100)
    /home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
    created by github.com/gogits/gogs/modules/log.newLogger
    /home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

    goroutine 38 [chan receive]:
    github.com/gogits/gogs/models.TestPullRequests()
    /home/gogs/go/src/github.com/gogits/gogs/models/pull.go:540 +0x1de
    created by github.com/gogits/gogs/models.InitTestPullRequests
    /home/gogs/go/src/github.com/gogits/gogs/models/pull.go:558 +0x2b

    goroutine 37 [chan receive]:
    github.com/gogits/gogs/models.DeliverHooks()
    /home/gogs/go/src/github.com/gogits/gogs/models/webhook.go:600 +0x465
    created by github.com/gogits/gogs/models.InitDeliverHooks
    /home/gogs/go/src/github.com/gogits/gogs/models/webhook.go:620 +0x2b

    goroutine 36 [select]:
    github.com/gogits/gogs/modules/cron.(*Cron).run(0xc82024aa80)
    /home/gogs/go/src/github.com/gogits/gogs/modules/cron/cron.go:161 +0x9e8
    created by github.com/gogits/gogs/modules/cron.(*Cron).Start
    /home/gogs/go/src/github.com/gogits/gogs/modules/cron/cron.go:136 +0x40

    goroutine 34 [chan receive]:
    database/sql.(*DB).connectionOpener(0xc820368000)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
    created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336
```
* Other stuff:
I removed AppUrl from the templates/repo/view_list.tmpl which temporarily fixed the issue.  I'm a newbie with Go, so there may be something messed up in my Go environment.  I can see what appears to be the implementation in modules/template/template.go.

**Comment by Unknwon** [comment]
Hi, I think you updated source code but did not recompile Gogs.

**Comment by codewisdom** [comment]
Nope, I recompiled goes multiple times.  Using master.  I confirmed I'm using a technique you or another maintainer mentioned in another issue.

**Comment by Unknwon** [comment]
Not defined only happens when binary has older version than templates. Make sure you run the newly compiled binary.

**Comment by codewisdom** [comment]
I know I've rebuilt it multiple times.  I went back and forth between different release tags on the master branch and was unable to repo this exact issue when moving back to a late 7.x version.  Each time, I deleted the binary before compiling.

See the version confirmation screenshots below:

<img width="599" alt="gogsversion" src="https://cloud.githubusercontent.com/assets/20617/12072134/a38cd572-b086-11e5-907a-7b2a3de09124.png">

<img width="874" alt="gogsrvcommand" src="https://cloud.githubusercontent.com/assets/20617/12072150/e0d3cb84-b086-11e5-851f-e33e614ae229.png">

**Comment by Unknwon** [comment]
OK, let me check again later.

**Comment by Unknwon** [comment]
@codewisdom is it possible to upload the problematic repository to the https://try.gogs.io ?

**Comment by codewisdom** [comment]
Nope, not that codebase. I'm not sure it is the codebase.  I couldn't repo when I compiled gogs on OS X.

**Comment by Unknwon** [comment]
OK... what is the content of `templates/.VERSION`?

**Comment by codewisdom** [comment]
Just updated to 0.8.15.1231.  Recompiled.  Same issue on startup with ````./gogs web````

Screenshot evidence:
<img width="744" alt="gogstemplateversion" src="https://cloud.githubusercontent.com/assets/20617/12133171/7d6f0b9a-b3d7-11e5-8e8b-8cbb795564fb.png">

**Comment by Unknwon** [comment]
OK. I need you repost full error output here...

**Comment by codewisdom** [comment]
No problem. Startup and error output attached.

[gogserr.txt](https://github.com/gogits/gogs/files/79485/gogserr.txt)
[startup.txt](https://github.com/gogits/gogs/files/79486/startup.txt)

**Comment by Unknwon** [comment]
Thanks. What is your Go version?

**Comment by Unknwon** [comment]
The actual error line is `panic: template: repo/view_list:33: function "AppUrl" not defined`.

Where the template function is obviously defined here: https://github.com/gogits/gogs/blob/master/modules/template/template.go#L37

**Comment by codewisdom** [comment]
I noticed that error message.  It's the title of this issue.   My Go version is: ````Go1.5.1````

Not a Go programmer by any means, but I could see the definition.  Did you notice my platform is FreeBSD?  A FreeBSD jail running on a FreeNAS box.

**Comment by Unknwon** [comment]
> Did you notice my platform is FreeBSD? A FreeBSD jail running on a FreeNAS box to be exact.

Never used that, what is different from other Linux systems?

PS: I think it should be same in the Go level, so must be something else.

**Comment by codewisdom** [comment]
FreeBSD?  Quite different from Linux. :)  See [FreeBSD] (https://www.freebsd.org).

However, I agree it is probably a issue at teh Go level.  Maybe an issue with Go on FreeBSD.  I'll look into that a bit later.

**Comment by Unknwon** [comment]
I'll close this until someone else reports on it.
