### ISSUE TITLE
Webhooks for issues

### ISSUE THREAD

**Issue by brandonsturgeon** [gogits/gogs#2319]
It'd be awesome to have some webhooks for issues being created/resolved and maybe even commented on

**Comment by brandonsturgeon** [comment]
Actually, just having the same (if not more) webhook capabilities as Github would be a good goal.

https://developer.github.com/v3/activity/events/types/

**Comment by lostsnow** [comment]
+1

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by brandonsturgeon** [comment]
Which hooks have been added? Is there a commit or changelog I can read?

Thanks for your work on this!

**Comment by Unknwon** [comment]
@brandonsturgeon 
![image](https://cloud.githubusercontent.com/assets/2946214/23761237/20e1ec2c-04c0-11e7-9672-53e9e13f950c.png)

**Comment by Unknwon** [comment]
Also issue comment events are added in the following commit.
