### ISSUE TITLE
Allow migration of issues

### ISSUE THREAD

**Issue by i00** [gogits/gogs#2320]
I don't know if this is possible, but would it be possible to be able to migrate the issues from GitHub (and / or Gogs) somehow?

I find it kind of frustrating that when I migrate repos across I cannot see what that commit with # 123 refers to!

**Comment by stonerl** [comment]
@i00 seems to be a duplication of #809

**Comment by Unknwon** [comment]
Yes, this is duplicated to #809 . :sweat_smile:
