### ISSUE TITLE
CSRF Handling with Ajax components

### ISSUE THREAD

**Issue by dabaer** [gogits/gogs#2324]
This issue is slightly similar to others, but is more of a UX suggestion than anything else:

When using a component that utilizes ajax (i.e. editing an issue) sometimes the CSRF token will be invalid (browsed another tab, etc) and the submitted content will erase itself and the action does not complete (with no way to retrieve what you typed and tried to submit).

This should have a check before clearing the textbox and closing the editor that the action actually completed successfully, because by the time i click submit on a long message i forgot the details of what i typed and have to type all over again.

This is valid as of v0.8.10.1217.

**Comment by Unknwon** [comment]
I think this is solved.

**Comment by dabaer** [comment]
wew :+1:
