### ISSUE TITLE
Cannot delete user with at least one public key

### ISSUE THREAD

**Issue by FGM** [gogits/gogs#2326]
If a user has entered a public key, their account can no longer be deleted, without any information in the UI : after the confirmation popup, the browser returns to the unchanged user list and the user is still in the DB. Apparently, this is because gogs is fails deleting the user key info.

The logs contain this error:
DeleteUser()] [E] DeleteUser: deletePublicKey: open /home/gogs/.ssh/authorized_keys: no such file or directory[0m
[Macaron] Completed /admin/users/3/delete 500 Internal Server Error in 16.149551ms

This seems to happen because the format in authorized_keys is not standard:

command="/opt/gogs/gogs serv key-2 --config='/etc/gogs/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAA<snip> UsualKey

The second part, starting with the snipped AAAA.. is normal, but the beginning is not.

Removing the public key manually from the public_keys table allows user removal to proceed without error.

**Comment by Unknwon** [comment]
Hi, is `/home/gogs/.ssh/authorized_keys` the real/correct path for the file?

**Comment by FGM** [comment]
Yes /home/gogs is the home directory for user gogs, which was created during install from the packager.io package for Ubuntu 12.04 LTS. As you can see, the end of the line for the remaining key does contain the usual info for a public key: the key itself and an associated name.

**Comment by Unknwon** [comment]
Yes, it is very strange that the error is confusing.

Are you able to reproduce this error 100%?

**Comment by Unknwon** [comment]
Close due to lack of feedback.
