### ISSUE TITLE
A duplicate in conf/license

### ISSUE THREAD

**Issue by l2dy** [gogits/gogs#2327]
Creative Commons CC0 1.0 Universal and Creative Commons Zero v1.0 Universal have the same content.

**Comment by Unknwon** [comment]
@l2dy you're right!

Which name is more commonly used then?

**Comment by l2dy** [comment]
I think the first one is the official name. Because it's the first line in both files and see https://creativecommons.org/publicdomain/zero/1.0/legalcode and https://tldrlegal.com/license/creative-commons-cc0-1.0-universal.

**Comment by Unknwon** [comment]
OK, just pushed fix to `develop` branch and you can also test on https://try.gogs.io/repo/create
