### ISSUE TITLE
Repositories created though the api allows illegal characters

### ISSUE THREAD

**Issue by xiegeo** [gogits/gogs#2329]
I created repos with the api using go-gogs-client, with names containing some characters such as '+' and '='. When editing such a repo's description using the web interface I got "Repository name must be valid alpha or numeric or dash(-_) or dot characters."

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
Please update `go-gogs-client` and help test again!

**Comment by xiegeo** [comment]
I am confused, shouldn't I be also updating the Gogs server? Since it was the server API that is also allowing the illegal characters through.

**Comment by Unknwon** [comment]
No, Gogs uses go-gogs-client as well.

**Comment by xiegeo** [comment]
Fixed, although the error message   <code>json: cannot unmarshal array into Go value of type map[string]interface {}</code> when using illegal characters is not descriptive.

**Comment by Unknwon** [comment]
That is type error, which I think is not even reach to illegal characters check yet.
