### ISSUE TITLE
Error 500 when creating a pull request

### ISSUE THREAD

**Issue by quantonganh** [gogits/gogs#2330]
```
cat templates/.VERSION
0.8.10.1217
```

I have just suddenly got an error when creating a PR:

```
2016/01/04 06:48:40 [T] PullRequest[0].testPatch(patchPath): /var/lib/gogs/repositories/dev/common.git/pulls/12.patch
2016/01/04 06:48:40 [...routers/repo/pull.go:632 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 1 - You asked to pull from the remote '--all', but did not specify a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
```

I understand what it said, but where does Gogs keep the local copy?
How to solve this problem?

According to the issue #2183, I guess that I should not delete the PR from the filesystem (`/var/lib/gogs/repositories/dev/common.git/pulls/12.patch`).

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you make a 500 error on https://try.gogs.io as well?

**Comment by micaelsutherland** [comment]
Hi, 

Think i am having the same issue. tried mirroring a repo 

https://github.com/RealJohnGalt/OpenELEC.tv

seems to mirror correctly but when i try to access it i get "Error 500" page. 

is there any more information i can give you to help?

**Comment by Unknwon** [comment]
Thanks @micaelsutherland ! I see the repository you post does not have `master` branch, maybe that's the problem.

**Comment by Unknwon** [comment]
Also by `mirror`, do you mean `mirroring` or `migrate`?

**Comment by micaelsutherland** [comment]
HI, 

Yes when mirroring the repo mentioned above i just get an error 500 page

**Comment by Unknwon** [comment]
Hi, @micaelsutherland 

1. You did not answer my question.
2. Please post your server side error log.

**Comment by micaelsutherland** [comment]
Hi, 

By mirror i mean "

[gogs.zip](https://github.com/gogits/gogs/files/80851/gogs.zip)


mirroring"

**Comment by Unknwon** [comment]
Thanks, but I don't see why its content has anything to do with mirroring.

And error indicates you're running out of memory. 

I think you're following on the wrong issue.

**Comment by micaelsutherland** [comment]
Apologies then for following the wrong issue.

**Comment by micaelsutherland** [comment]
It appears i have plenty of memory no?

![image](https://cloud.githubusercontent.com/assets/5029232/12166214/311df4d6-b51c-11e5-8929-807d0574bdc2.png)

**Comment by Unknwon** [comment]
@micaelsutherland the error could not be wrong, when it says out of memory, it can't get more memory to use.

**Comment by micaelsutherland** [comment]
ok, 

Apologies if i sound like i haven't got a clue what i am talking about. would this be an error with gogs or my system? (1&1 VPS)

**Comment by micaelsutherland** [comment]
there sems to be an awful lot of memory instances for gogs 
![image](https://cloud.githubusercontent.com/assets/5029232/12166433/e12e99ba-b51d-11e5-8990-6005273cd9d8.png)

**Comment by Unknwon** [comment]
ping @quantonganh

**Comment by Unknwon** [comment]
Close due to lack of feedback.
