### ISSUE TITLE
Line break in email notification should be in html format

### ISSUE THREAD

**Issue by biji** [gogits/gogs#2331]
Currently email notification for new issue is just one line text. Should be in html formatted to make it more pretty

thanks

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you give a more specific example?

**Comment by biji** [comment]
When I create new issue, all watcher get notification email, email source follow:

```
--cd8461cec9bcaef98ae5349397f93dfbf68c80f5c9a993e1084e6c325299
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

TODO
1. Task 1
1. Task 2
1. Task 3
1. Task 4
<br>-<br> <a href=3D"http://git.local:3000/abc/def/issues/3">View =
it on Gogs</a>.
--cd8461cec9bcaef98ae5349397f93dfbf68c80f5c9a993e1084e6c325299
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

TODO
1. Task 1
1. Task 2
1. Task 3
1. Task 4
<br>-<br> <a href=3D"http://git.local:3000/abc/def/issues/3">View =
it on Gogs</a>.
--cd8461cec9bcaef98ae5349397f93dfbf68c80f5c9a993e1084e6c325299--
```

When opening in mail client it will shown as:
```
TODO 1. Task 1 1. Task 2 1. Task 3 1. Task 4
[Link]
```

It would be good if the email formatted using markdown as shown in issue page


Thanks

**Comment by Unknwon** [comment]
It is markdown formatted before sending...

**Comment by Unknwon** [comment]
What is the actual content of issue thought?

**Comment by Unknwon** [comment]
ping @biji

**Comment by biji** [comment]
Hi Unknwon,

Issue entered as:
TODO
1. Task 1
1. Task 2
1. Task 3
1. Task 4

Gogs shown as:
TODO
1. Task 1
2. Task 2
3. Task 3
4. Task 4

Email sent should be:
TODO<br>
1. Task 1<br>
2. Task 2<br>
3. Task 3<br>
4. Task 4<br>

Thanks

**Comment by Unknwon** [comment]
Thanks for following up!

**Comment by Unknwon** [comment]
This issue is claimed to be fixed ber meging https://github.com/gogits/gogs/pull/2659

**Comment by Unknwon** [comment]
Close as fixed.
