### ISSUE TITLE
User profile organisations and teams

### ISSUE THREAD

**Issue by xor-gate** [gogits/gogs#2332]
Maybe it would be nice to show in the user profile the organisations and teams it is part of like on github.

Something like this:
![2016-01-04 10_19_26-spf13 steve francia](https://cloud.githubusercontent.com/assets/1050166/12086705/eb5751fa-b2cc-11e5-80e6-4dedb4caf70f.png)

**Comment by Unknwon** [comment]
Somehow... it is implmented already..
