### ISSUE TITLE
Truncate links to commits

### ISSUE THREAD

**Issue by brandonsturgeon** [gogits/gogs#2338]
For example, `/commit/440c62a29faa6bf113da2d9eeb820d88a105f340` to `a href="/commit/440c62a29faa6bf113da2d9eeb820d88a105f340" 440c62a29f`

This is especially nice in comments on issues (eg: `resolved in 440c62a29f`)

Edit: I see this is already done in email alerts.

**Comment by Unknwon** [comment]
Hmm... can you give some visual comparison for this?

**Comment by brandonsturgeon** [comment]
Sorry, how do you mean? 

When you paste a full link to a specific commit, I was suggesting that it gets truncated to a link with the only text being the first 10 or so characters of the commit hash.

For example:
`https://github.com/gogits/gogs/commit/e0f0f72a362e98073980d9e3c70cde8cd161614b` when pasted here becomes https://github.com/gogits/gogs/commit/e0f0f72a362e98073980d9e3c70cde8cd161614b

**Comment by Unknwon** [comment]
Thanks.

Why would you paste link in the commit message?

**Comment by brandonsturgeon** [comment]
Sorry, the link wouldn't be in a commit message. The link would be on a comment in an issue. 

For example, 

Someone opens up an issue "We need to speed up our app" and it sits there for awhile.

Someone else makes a bunch of changes, one of the changes speeds up the app. This person didn't reference the issue # in the commit message.

When cleaning up issues, you could post in the comments "This was resolved in [link to commit that sped up the app]" and then close the issue

**Comment by Unknwon** [comment]
Please see https://try.gogs.io/gogs/gogs/issues/1 ... is that what you're looking for?

**Comment by brandonsturgeon** [comment]
Yup! That seems like the kind of thing I'm looking for!

**Comment by Unknwon** [comment]
Great... then this issue is no longer needed.
