### ISSUE TITLE
Feature request: command line parameter for custom config ini

### ISSUE THREAD

**Issue by fanningert** [gogits/gogs#234]
It is only a idea do make it easier to install and run more than one instance of gogs on one machine, without to install gogs over a container like docker.

My idea is to get the custom app.ini over following rule.

1. read the command line parameter: `gogs web /etc/gogs/app.ini`
2. the command line is empty, read the enviroment variable `GOGS_CUSTOM`
3. ...

**Comment by Unknwon** [comment]
Somewhat implemented: https://github.com/gogits/gogs/blob/master/cmd/web.go#L59
