### ISSUE TITLE
Still serving static files from the server instead of the CDN when offline-mode is off

### ISSUE THREAD

**Issue by StdioA** [gogits/gogs#2344]
我没有开启Offine Mode, 可是很多静态文件（比如`semantic-2.1.6.min.css`）都从服务器下载而不是CDN. 如何改为从CDN获取所有静态资源？

**Comment by Unknwon** [comment]
Hi, these kind of files are always get from server, you can't get it from CDN.

Some of files are modified version, so CDN does not apply.
