### ISSUE TITLE
Disallow wiki for empty project

### ISSUE THREAD

**Issue by stonewareslord** [gogits/gogs#2345]
Currently, the tabs for issues,wiki... are only shown when the repository is not empty:

![i](https://cloud.githubusercontent.com/assets/7482347/12125707/e4a0b5c4-b3ba-11e5-9d4e-83849d50bb4f.png)

![i](https://cloud.githubusercontent.com/assets/7482347/12125847/b40f6c10-b3bb-11e5-90cf-342bc0ba18eb.png)

However, if you go to http://gogs/test/repo-2/wiki, you can add a wiki to an empty project:

![i](https://cloud.githubusercontent.com/assets/7482347/12125793/56cc7976-b3bb-11e5-9f94-98064e94fb56.png)

I think that either adding a wiki to a blank project should not be allowed or the tabs should be visible in blank projects.

**Comment by Unknwon** [comment]
Yes, I think this is a UI bug. Thanks for your report!

**Comment by Unknwon** [comment]
I just pushed a fix to `develop` and you can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Close as fixed.
