### ISSUE TITLE
PANIC: interface conversion: interface is []uint8, not int64

### ISSUE THREAD

**Issue by Ingramz** [gogits/gogs#2349]
After adding PAM as an authentication method, I am immediately greeted with a blank page and following panic.

Installed from source with pam tag using [this guide](https://gogs.io/docs/installation/install_from_source). Using Debian 8 if that matters.

```
[Macaron] PANIC: interface conversion: interface is []uint8, not int64
/usr/local/go/src/runtime/panic.go:423 (0x42ba09)
/usr/local/go/src/runtime/iface.go:221 (0x40d5f0)
/home/git/go/src/github.com/gogits/gogs/models/login.go:111 (0x548dd2)
        (*LoginSource).BeforeSet: switch LoginType((*val).(int64)) {
/home/git/go/src/github.com/go-xorm/xorm/session.go:1656 (0x6e8da5)
        (*Session)._row2Bean: b.BeforeSet(key, Cell(scanResults[ii].(*interface{})))
/home/git/go/src/github.com/go-xorm/xorm/session.go:1625 (0x6e8783)
        (*Session).rows2Beans: err := session._row2Bean(rows, fields, fieldsCount, bean, &dataStruct, table)
/home/git/go/src/github.com/go-xorm/xorm/session.go:1365 (0x6e4617)
        (*Session).Find: return session.rows2Beans(rawRows, fields, fieldsCount, table, newElemFunc, sliceValueSetFunc)
/home/git/go/src/github.com/go-xorm/xorm/engine.go:1347 (0x6b1389)
        (*Engine).Find: return session.Find(beans, condiBeans...)
/home/git/go/src/github.com/gogits/gogs/models/login.go:191 (0x549768)
        LoginSources: return auths, x.Find(&auths)
/home/git/go/src/github.com/gogits/gogs/routers/admin/auths.go:32 (0x7f69fc)
        Authentications: ctx.Data["Sources"], err = models.LoginSources()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/local/go/src/reflect/value.go:432 (0x87fe4a)
/usr/local/go/src/reflect/value.go:300 (0x87eb11)
/home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb28a42)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x74b8d7)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x74b7bc)
        (*Context).Next: c.run()
/home/git/go/src/github.com/go-macaron/session/session.go:186 (0x698f84)
        Sessioner.func1: ctx.Next()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/local/go/src/reflect/value.go:432 (0x87fe4a)
/usr/local/go/src/reflect/value.go:300 (0x87eb11)
/home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb28a42)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x74b8d7)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x74b7bc)
        (*Context).Next: c.run()
/home/git/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x760ca2)
        Recovery.func1: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/local/go/src/reflect/value.go:432 (0x87fe4a)
/usr/local/go/src/reflect/value.go:300 (0x87eb11)
/home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb28a42)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x74b8d7)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x74b7bc)
        (*Context).Next: c.run()
/home/git/go/src/gopkg.in/macaron.v1/logger.go:40 (0x75f8ee)
        Logger.func1: ctx.Next()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45cbce)
/usr/local/go/src/reflect/value.go:432 (0x87fe4a)
/usr/local/go/src/reflect/value.go:300 (0x87eb11)
/home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb28a42)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x74b8d7)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/git/go/src/gopkg.in/macaron.v1/router.go:184 (0x762424)
        (*Router).Handle.func1: c.run()
/home/git/go/src/gopkg.in/macaron.v1/router.go:286 (0x758d9d)
        (*Router).ServeHTTP: h(rw, req, p)
/home/git/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x750cda)
        (*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1862 (0x65065e)
/usr/local/go/src/net/http/server.go:1361 (0x64de4e)
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x45ef41)
[Macaron] Completed /admin/auths 500 Internal Server Error in 7.649728ms

```

**Comment by bitbyt3r** [comment]
I am seeing this same issue adding any type of external authentication.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I can't reproduce this locally, can you provide more details on steps?

**Comment by xiegeo** [comment]
@Ingramz  @bitbyt3r Which databases are you using?

**Comment by Ingramz** [comment]
@xiegeo mysql 5.5.46

**Comment by Ingramz** [comment]
Here's a way to reproduce this using docker.

Install from docker official debian:latest **with port 3000 exposed if needed**, so you can access it from your host machine

enter that container's shell and run:

```
adduser --disabled-login --gecos 'Gogs' git

debconf-set-selections <<CONFIG
mysql-server-5.5 mysql-server/root_password password change_me
mysql-server-5.5 mysql-server/root_password_again password change_me
CONFIG

apt-get update
apt-get install -y --force-yes mysql-server wget git
service mysql start
mysql -uroot -pchange_me -e "create database if not exists gogs;"

su - git
mkdir local
wget https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz
tar -C /home/git/local -xzf go1.5.2.linux-amd64.tar.gz

echo 'export GOROOT=$HOME/local/go' >> $HOME/.bashrc
echo 'export GOPATH=$HOME/go' >> $HOME/.bashrc
echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> $HOME/.bashrc
source $HOME/.bashrc

go get -u github.com/gogits/gogs
cd $GOPATH/src/github.com/gogits/gogs
go build

./gogs web
```

Now browse that address (for me it was localhost:3000)

install as usual (I disabled self-registration and created an user), mysql password is change_me

go to /admin/auths

add a new source, eg pam with some dummy data

as soon as you click add, panic will occur

**Comment by Unknwon** [comment]
Thanks @Ingramz ,

not talking adding PAM first, the way you compile Gogs does not support PAM anyway...

**Comment by Ingramz** [comment]
@Unknwon I did it like that on purpose, because the issue isn't related to PAM directly.

**Comment by Unknwon** [comment]
@Ingramz does add a dummy LDAP auth source panic too?

**Comment by Ingramz** [comment]
@Unknwon yes. Adding any auth source does that.

**Comment by Unknwon** [comment]
OK... can you dump the database table `login_source` see what is the value of filed `type`?

**Comment by Ingramz** [comment]
Added LDAP this time.

```
mysql> select type from gogs.login_source;
+------+
| type |
+------+
|    2 |
+------+
1 row in set (0.00 sec)

mysql> describe gogs.login_source;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| type       | int(11)      | YES  |     | NULL    |                |
| name       | varchar(255) | YES  | UNI | NULL    |                |
| is_actived | tinyint(1)   | NO   |     | 0       |                |
| cfg        | text         | YES  |     | NULL    |                |
| created    | datetime     | YES  |     | NULL    |                |
| updated    | datetime     | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)
```

**Comment by Unknwon** [comment]
Thanks.

Suppose you're using the `master` version,

it would be very helpful if you can add a line right after [this line](https://github.com/gogits/gogs/blob/master/models/login.go#L110):

```go
fmt.Println(*val)
```

**Comment by Ingramz** [comment]
I'm getting `[50]` which is ASCII code for `2`

**Comment by Unknwon** [comment]
Thanks. Though I don't know why it gets `[]int8`, but I think I know how to convert :trollface:

**Comment by Ingramz** [comment]
Also `/admin/users/new` and `/admin/users/1` are failing to load for the same reason, seems like they all enumerate the `login_source` in some way.

**Comment by Unknwon** [comment]
OK... seems to be a bigger problem.

What if you use compiled binary (not compile by yourself)?

**Comment by Ingramz** [comment]
originally I tried packages from https://packager.io/gh/pkgr/gogs, these had the same problem.

**Comment by Unknwon** [comment]
By `compiled binary`, I mean https://dl.gogs.io/ , packager.io is no difference from compiling yourself.

**Comment by Ingramz** [comment]
`gogs_v0.8.10_linux_amd64.tar.gz` is working perfectly

**Comment by Unknwon** [comment]
Hi @Ingramz , can you help test `develop` branch again?

**Comment by Ingramz** [comment]
@Unknwon I tried and that won't work for 2 reasons. `[]int8` should be `[]uint8` and if you simply take the first value of the byte array, you'll get the ASCII integer value, which for digits is in range 48-57. So it would  give `PANIC: unrecognized login source type: 4` from https://github.com/gogits/gogs/blob/develop/models/login.go#L130 where it constructs a string from `*val` - in this case the '4' was actually intval 52

Any idea as to why it gives a different type for different systems on that interface, perhaps an issue with ORM?

**Comment by Unknwon** [comment]
> Any idea as to why it gives a different type for different systems on that interface, perhaps an issue with ORM?

Actually I don't know why MySQL driver could return different type in different system... I believe it supposed to be in a unified format. Yeah, maybe it's ORM's problem.

**Comment by Unknwon** [comment]
Just pushed another fix to `develop`.

**Comment by Ingramz** [comment]
@Unknwon now seems to be working. I added also a trace for `int64` and now I see that on some pages (like when logging in) it uses `int64` and for instance on `/admin/auths` it uses `[]uint8`, very strange.

**Comment by Unknwon** [comment]
@Ingramz great... quite hard to trace the original bug location.

**Comment by Ingramz** [comment]
Only difference I can see is that in stack trace. https://www.diffchecker.com/ldcgb7fr - this is what is done differently. I have very little experience with go and xorm, so I'll just leave it here. The current solution is good enough to work around the problem.

**Comment by Unknwon** [comment]
Very helpful!

I think the driver may behave differently for `Get` (get on record) and `Find` (get all records).

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by lei314121077** [comment]
this is redis process data error , get key is interface type but your process is []int8 case
