### ISSUE TITLE
Grammar error found whilst deleting non-empty organisation

### ISSUE THREAD

**Issue by deavmi** [gogits/gogs#2350]
Grammar error.

It should say:

`This organization still has ownership of the repositories, you have to delete or transfer them first.`

![2016-01-06 17_13_22-settings - notabug org_ free code hosting](https://cloud.githubusercontent.com/assets/5207740/12145778/e06720ea-b498-11e5-9a94-fa9265636ef3.png)

**Comment by Walkman100** [comment]
Or even better: `This organization still has ownership of repositories, you must delete or transfer them first.`

**Comment by deavmi** [comment]
@Walkman100 Your's is better.

**Comment by Unknwon** [comment]
I just pushed a fix for this to `develop` branch, you can also test on https://try.gogs.io

**Comment by deavmi** [comment]
Awesome.

**Comment by deavmi** [comment]
Did you use the one by @Walkman100?

**Comment by Unknwon** [comment]
Yes.

**Comment by deavmi** [comment]
@Unknwon **awesome** (lol) thanks.
