### ISSUE TITLE
Long repo name formatting issues

### ISSUE THREAD

**Issue by stonewareslord** [gogits/gogs#2351]
Gogs Version: 0.7.33.1205 Beta

When repositories have long names, they break formatting of gogs:

![selection_005](https://cloud.githubusercontent.com/assets/7482347/12149353/52e243b6-b471-11e5-919c-4c55b8d912b3.png)

The names stretch past the "My Repositories" box and push the stars down. The second repo's star shifts `repo-2`'s star to the left. In the news feed, the name overlaps with the repo icon. Github has some examples of of how this could be fixed

by using ellipses:

![selection_014](https://cloud.githubusercontent.com/assets/7482347/12149579/58dae5b0-b472-11e5-81b7-d99d570dca4a.png)

by breaking the line:

![selection_013](https://cloud.githubusercontent.com/assets/7482347/12149547/38a5b450-b472-11e5-8614-507804033e34.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/2287 .

It would be very helpful if you post these details on that thread.
