### ISSUE TITLE
Installation instructions wrong for CentOS7

### ISSUE THREAD

**Issue by bash99** [gogits/gogs#2354]
in
https://packager.io/gh/pkgr/gogs/install?bid=404#centos-7-gogs
you can easy found the script is for centos 6(which use service not systemctl, mysql instead of mariadb)
I've made a correct one

APP_NAME="gogs"
MYSQL_PASSWORD="change_me"
HOSTNAME="YOUR_HOSTNAME"

# setup mysql
yum install mariadb-server -y
systemctl start mariadb
systemctl enable mariadb

mysqladmin -u root password "${MYSQL_PASSWORD}"
mysqladmin -u root --password="${MYSQL_PASSWORD}" password "${MYSQL_PASSWORD}"
mysql -u root -p${MYSQL_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${APP_NAME}; use ${APP_NAME}; set global storage_engine=INNODB;"

# install nginx
rpm -Uhv http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
 yum install -y nginx

cat > /etc/nginx/conf.d/default.conf <<EOF
server {
  listen          80;
  server_name     ${HOSTNAME};
  location / {
    proxy_pass      http://localhost:3000;
  }
}
EOF

systemctl start nginx
systemctl enable nginx

**Comment by Unknwon** [comment]
cc @crohr

**Comment by ExiaSR** [comment]
When I open up the installation page, I got an error from nginx. (It's running on centos 7 as well)

**Comment by Unknwon** [comment]
I have literally no control of packager.io 's documentation, I might close this one if the author of that site not responding to this thread. (he is a busy man) :sweat:

**Comment by crohr** [comment]
Well I'm happy to point the doc to somewhere else (a file in this repo?), so that more people can propose fixes / improvements.

**Comment by Unknwon** [comment]
@crohr yes! That would be awesome. 

Maybe under `packager/dcs` directory?

And have `centos-6.md`, `centos-7.md`, `ubuntu-12.04.md`, etc?

Or is it better to put in `gogits/docs` repository?

**Comment by crohr** [comment]
@Unknwon really sorry for the wait. I think it would be best to put that doc in `gogits/docs`, and have a single file per distribution? Then I can update the page on `pkgr/gogs` on packager.io so that it points to the doc.

**Comment by Unknwon** [comment]
@crohr No problem! Just tell me which files should I have on that repository, I'll update them, and you can make a initial PR for those files which could be the best :D

**Comment by ciruz** [comment]
Hey @crohr and @Unknwon, I just want to inform you again that the latest packages are failing since a month

https://packager.io/gh/pkgr/gogs

**Comment by Unknwon** [comment]
Close since there is basically not much things we can do on Gogs side.

**Comment by mbi** [comment]
/ping @crohr hey, the [last build on packager.io is two months old](https://packager.io/gh/pkgr/gogs), what gives? 😏

**Comment by mbi** [comment]
Hello @crohr, Gogs builds are again [stuck at a two months old version](https://packager.io/gh/pkgr/gogs). 🙏
