### ISSUE TITLE
Prestashop is not a language, unlike PHP

### ISSUE THREAD

**Issue by chazzbg** [gogits/gogs#2357]
http://prntscr.com/9n3jxn
This is nonsense ... most of the used php frameworks and apps are there, but not the language itself.

**Comment by r0cknfire** [comment]
And... What should be ignored by default on PHP ? I mean, frameworks and Prestashop have things that shouldn't be committed (caches, config files...), but PHP itself, I can't really think of a gitignore for it.

**Comment by chazzbg** [comment]
I'm sorry, i really didn't realized that this selection is just for file templates for initializing repository. 
I've used bitbucket a lot for our company projects, and thought that language selection is for some repository categorization. 
Please excuse my ignorance and ignore this issue . I'll be more  observant next time.

Regards.
