### ISSUE TITLE
Add Permissions to Branches

### ISSUE THREAD

**Issue by i00** [gogits/gogs#2358]
I would like the feature of allowing Gogs to be able to set different users up with individual permissions for various branches.

For Eg (my case).
If I have a user called Jack I want to be able to give him permissions to publish new branches that start with Jack/ only (so I know exactly what user published a branch at a glance and don't end up with "junk" branches everywhere).
I want to be the only one who can push to the master.

I want to be able to restrict publishes, pushes and pulls (preferably visibility entirely if I don't grant pull permissions).
All of this should hopefully be able to be done with wildcards to suit my purposes..

Thanks, for the great work :)

**Comment by Unknwon** [comment]
Hi, I think this is duplicated to https://github.com/gogits/gogs/issues/776 .

You can leave your feedback on that thread.
