### ISSUE TITLE
Auto Migration Failed between version 0.8.5 and 0.8.17

### ISSUE THREAD

**Issue by elzofranklin** [gogits/gogs#2362]
Using sqlite engine in our version of gogs, 32 bit linux build.

For a certain repository we have about 180 issue records, pre-migrate.  After migration to 0.8.17, the same repo only shows about 140 issues.  It looks like the last 2 weeks of new issues did not translate over correctly.  The migration logs shows "Updating issue count" for the first 140 issues.

btw, we migrated to 0.8.5 from a much older 0.6? version without any problems about 2 weeks ago.  Our guess is that only issues created using 0.8.5 had problems surviving the migration to 0.8.17.

We had to roll back to 0.8.5 because we can't lose those issues.  Any help is appreciated.

**Comment by stonerl** [comment]
maybe related to this one #2269?

**Comment by Unknwon** [comment]
Thanks your report!

If 0.8.5 works correctly, then there is no migration between 0.8.5 and 0.8.17.

> "Updating issue count" for the first 140 issues.

If this is the case, are you sure database has 180 records instead of old counter was wrong?

**Comment by Unknwon** [comment]
SQL to query count: `SELECT COUNT(*) FROM issue WHERE repo_id={repo_id}`

**Comment by elzofranklin** [comment]
Thanks for the response guys.  You comments made me realize I had inadvertantly copied in the wrong database to 0.8.17, and thats why I lost the issues, NOT because of migration software.

Very sorry for wasting your time.

**Comment by Unknwon** [comment]
:trollface:
