### ISSUE TITLE
Error building tidb support

### ISSUE THREAD

**Issue by michaelgibson** [gogits/gogs#2364]
When including -tags "tidb" I was running into this error:

src/github.com/pingcap/tidb/parser/yy_parser.go:42: undefined: NewLexer
src/github.com/pingcap/tidb/parser/yy_parser.go:44: undefined: yyParse

According to this issue:
https://github.com/pingcap/tidb/issues/88

You need to first compile tidb's parser before you can compile yy_parser
I was able to get around it by adding the following build steps:

export PATH=$PATH:$GOPATH/bin
go get -v -u -d github.com/pingcap/tidb
cd src/github.com/pingcap/tidb
make

Then normally:
https://gogs.io/docs/installation/install_from_source#build-with-tags
go get -v -u -tags="sqlite tidb pam cert" github.com/gogits/gogs
cd $GOPATH/src/github.com/gogits/gogs
go build -tags="sqlite tidb pam cert"

It may be useful to update the docs to contain this information at least Linux builds?

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Myke** [comment]
Another note - on FreeBSD you want to use gmake instead of make.
