### ISSUE TITLE
Unable to delete repos v8.10? Latest binary

### ISSUE THREAD

**Issue by km4efp** [gogits/gogs#2367]
On user view I am unable to delete a repo when I click on delete or change ownership there is no pop up.  Nothing happens in multiple browsers.

On administrator view nothing happens either when clicking on the red trash can.

Anny suggestions?

I was able to manual delete the repos on the OS level and run the cleanup missing repo script from web admin panel.

**Comment by km4efp** [comment]
Also another issue is when disabling gravatar and viewing user profile and clicking the avatar it still takes you to the gravatar website

**Comment by Unknwon** [comment]
Thanks your feedback!

Please use Chrome and open web console see if any errors there?

**Comment by km4efp** [comment]
Nothing related to my knowledge

gogs.js?v=86fbae3d4ac88fbee334e9f57e7bd750:869 Uncaught ReferenceError: emojify is not defined(anonymous function) @ gogs.js?v=86fbae3d4ac88fbee334e9f57e7bd750:869j @ jquery-1.11.3.min.js:2k.fireWith @ jquery-1.11.3.min.js:2m.extend.ready @ jquery-1.11.3.min.js:2J @ jquery-1.11.3.min.js:2

**Comment by Unknwon** [comment]
OK... so I see there is an error, which makes JS stops working.

Please take screenshots for web console.

**Comment by km4efp** [comment]
I figured it out based off that error!
You were actually a ton of help.
Apparently the footer.tmpl loads a lot of background stuff and it was in there.  I removed the file without looking at its contents.  So it was my mistake.
I had modified the template.

**Comment by Unknwon** [comment]
So problem solved?... :trollface:

**Comment by km4efp** [comment]
Yes resolved, though unrelated...
The gravatar error persists though when you disable gravatar in config file and view your profile and click on image it still takes you to gravatar.  Unless you go to settings and disable fetch from gravatar.  It would be nice to take you to upload a custom image in your profile page instead.

**Comment by km4efp** [comment]
I would really like custom templates in the future.
So far this has been a great product!
I just see updating and manually editing my template every time may lead to troubleshooting.  :-)

**Comment by Unknwon** [comment]
> The gravatar error persists though when you disable gravatar in config file and view your profile and click on image it still takes you to gravatar. Unless you go to settings and disable fetch from gravatar. It would be nice to take you to upload a custom image in your profile page instead.

Just pushed a fix to `develop` for this.

**Comment by km4efp** [comment]
Excellent.  No other complaints.  Keep up the good work.
