### ISSUE TITLE
500 Error,delete and rebuild the same name of the repo

### ISSUE THREAD

**Issue by cnwangzd** [gogits/gogs#2368]
Delete and rebuild the same name of the repo, the system reported 500 error.

please, what is the reason? thanks!

**Comment by Unknwon** [comment]
I think it's same as https://github.com/gogits/gogs/issues/1738 ?

**Comment by Unknwon** [comment]
ping @cnwangzd

**Comment by cnwangzd** [comment]
13311595834@189.cn

Best Regards,
===========================================
Email: cnwangzd@gmail.com

2016-01-09 13:03 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
Close due to lack of feedback.
