### ISSUE TITLE
Unable to access from Xcode (401)

### ISSUE THREAD

**Issue by helli72** [gogits/gogs#2371]
Just found Gogs and tried it. Looks very good! But when I want to access Gogs from Xcode, I get following error:
[Macaron] Started GET /adm/test1.git/info/refs?service=git-upload-pack for 192.168.1.6
[Macaron] Completed /adm/test1.git/info/refs?service=git-upload-pack 401 Unauthorized in 107.980111ms

Gogs is installed without any special settings for now (sqlite, http, user: adm, pw: test..., no smtp), just wanted test Gogs.

Tried different versions form 0.7.6 to 0.8.x

Is this a bug in Gogs?

**Comment by Unknwon** [comment]
Hi, 401 means you're accessing a private repository without authorization.

**Comment by helli72** [comment]
Yes, if testing works it should be accessable from the Internet, user+pass is a must-have.

Really using a very basic config for now. Gogs runs on TCP 3000, no Webserver acting as a reverse proxy. Also tried Webserver (Apache) with proxypass, but behaves the same.

I tried 0.7.6 and 0.8.10 (and some versions in-between from "install the binary")

Also I tried Xcode with try.gogs.io and this works. try.gogs.io use 0.8.18. Is there a difference in Auth-Mode?

Where can I get log files? I set log level to trace and log mode to file. But no auth logs in /var/log and in gogs/data.

**Comment by Unknwon** [comment]
> Also I tried Xcode with try.gogs.io and this works. try.gogs.io use 0.8.18. Is there a difference in Auth-Mode?

No.

>Where can I get log files? I set log level to trace and log mode to file. But no auth logs in /var/log and in gogs/data.

401 error is too obvious to have any logs.

You should try command line first determine it works, then try GUI tools.

**Comment by helli72** [comment]
git command from Shell works, but there isn't always a "command line". I also want/need to use Dringend App on iOS with Gogs:
http://dringend.cc

Dringend App behaves the same like Xcode. Xcode is just better known, so I used Xcode.

But both, Xcode and Dringend App, works with Gitlab (on premise), github.com and a basic Apache/git-backend-http setup without problems even with authentication.

**Comment by Unknwon** [comment]
Gogs only support smart HTTP and basic HTTP auth, any tools that does not support that can't work with Gogs, and we don't have any plan for doing that.

>I also want/need to use Dringend App on iOS with Gogs: http://dringend.cc

It seems to me that more about this app supports Gogs other than in the opposite way.

**Comment by helli72** [comment]
Ok, thanks.
