### ISSUE TITLE
500 when filename starts with ':'

### ISSUE THREAD

**Issue by congeal** [gogits/gogs#2373]
I tried migrating an existing repo into Gogs, but it shows 500 server error.
Log message showed like below:
routers/repo/view.go:134 Home()
[E} GetCommitsInfo: GetCommitByPath (/:source): Length must be 40.
I found out that the filename ':source' caused the error.
After I renamed the filename to be without ':', pushed the original repo and retried migration, it works without any error.
However, since the name is still starting with ':' in the other branches, the error shows whenever I change the branches.
I'd like you to fix this problem so that I don't have to rename files staring with a colon.

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
@congeal is that repository public so I can directly test against it?

**Comment by congeal** [comment]
Yeah, you reproduced it! I think it has something to do with git-module that is another github project of yours.

**Comment by Unknwon** [comment]
Yes, I've found the way to solve it, working on it.

**Comment by congeal** [comment]
:thumbsup:

**Comment by Unknwon** [comment]
OK, `go get -u github.com/gogits/git-module` then recompile Gogs should solve the problem.

**Comment by Unknwon** [comment]
See in action: https://try.gogs.io/unknwon/issue-2373

**Comment by congeal** [comment]
I confirmed that the problem has gone.
Thank you a lot.

**Comment by Unknwon** [comment]
:beers:
