### ISSUE TITLE
Add participants to issue tracker

### ISSUE THREAD

**Issue by i00** [gogits/gogs#2377]
In the issue tracker in github, when you have an issue open, there is a list of "contributers" to the discussion on the right hand side.

Is it possible to add this to Gogs?

**Comment by Unknwon** [comment]
Hi, isn't it `participant`?

**Comment by i00** [comment]
Oh yea :)

**Comment by bkcsoft** [comment]
If no-one else is working on this I'll take it :smile:

**Comment by i00** [comment]
Thanks bkcsoft :+1:

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging #2444.
