### ISSUE TITLE
SSH无法clone，还是does not appear to be a git repository问题

### ISSUE THREAD

**Issue by Veitor** [gogits/gogs#2378]
通过地址ssh://root@xxxx.com/hc/test.git无法clone下来
会出现
```
fatal: '/hc/test.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
```
这个问题通过https://gogs.io/docs/intro/troubleshooting#git看了
还有这个问题https://github.com/gogits/gogs/issues/545
都没解决，我的`~/.ssh/authorized_keys`中没有重复的key

=========================================
但还发现一个奇怪的现象，我的电脑A上生成了一个公钥分别放到服务器B和服务器C上的`~/.ssh/authorized_keys`中，用于通过SSH登录到这两个服务器。

其中服务器B上搭建gogs存放版本库，服务器C上用于部署项目。

然后在服务器C上生成一个公钥加到了项目test的部署密钥中，此时服务器B上的`~/.ssh/authorized_keys`应该包含我电脑A的公钥和服务器C的公钥，并且不会重复

但在服务器C上clone时就会报上面那个错误，如果我把服务器B的`~/.ssh/authorized_keys`中删掉电脑A的公钥，那么在服务器C上就能clone下来了。如果不删除电脑A的公钥，在服务器C上把SSH地址改成完整地址ssh://root@xxxx.com/home/repositories/rehc/test.git则也能clone下来

=========================================

这到底是什么问题？难道是服务器B和服务器C的`~/.ssh/authorized_keys`中不能有相同key？
那么如果我从服务器B上把电脑A的公钥删掉，就可以部署，但我也不能登录到服务器B了。。。
怎么解决？
第一次提问，多多包涵

**Comment by Unknwon** [comment]
> fatal: '/hc/test.git' does not appear to be a git repository

What is the commands you use to clone? Please post full input and output here.

**Comment by Veitor** [comment]
我是直接在页面上复制项目右上角的ssh地址，然后git clone
```
[root@wyq gitceshi]# git clone root@git.veitor.net:veitor/ceshi.git
Initialized empty Git repository in /home/www/gitceshi/ceshi/.git/
fatal: 'veitor/ceshi.git' does not appear to be a gi
```
但通过http输入密码clone是有用的

================================================

另外又发现一个现象，我换台电脑D，并且电脑D上的SSH密钥对从电脑C上拷过来的，所以通过电脑D我也能登录两个服务器，此时我通过电脑D在服务器C上`clone root@git.veitor.net:veitor/ceshi.git`是可以的
所以我开始怀疑会不会是电脑A上的配置问题？至少感觉不是gogs的问题
不知作者您凭经验觉得是哪出问题了？

**Comment by Veitor** [comment]
ok..我最后找到原因了，是我电脑A本身原因，使用的secureCRT版本太低，导致了这问题。。。现在升级了新版的secureCRT就可以了

**Comment by Unknwon** [comment]
> ok..我最后找到原因了，是我电脑A本身原因，使用的secureCRT版本太低，导致了这问题。。。现在升级了新版的secureCRT就可以了

:sweat: ....epic discovery!
