### ISSUE TITLE
Real-time synchronization mirror

### ISSUE THREAD

**Issue by ghost** [gogits/gogs#2380]
Hello,

We'd like to use Gogs 0.8.15 and Gitolite to manage our Git repositories.
We need Gitolite for advanced access control (per-branch write access, and
so on).

We need to have a real-time synchronization between our Gitolite repository
and Gogs (which are both hosted on the same server).
Is there a way to do this, or is there a plan to add this feature?  We've
only found an hourly update feature.

Thank you in advance for your reply.
Best regards.

**Comment by Unknwon** [comment]
Hi, there is no such solution, but the only way could work is this: https://github.com/gogits/gogs/issues/2235

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/2235
