### ISSUE TITLE
.gopmfile needs to update git-module

### ISSUE THREAD

**Issue by Eriner** [gogits/gogs#2385]
After the change introduced by https://github.com/gogits/gogs/commit/db719abff2d645672b686ea69c94683f49340761, the following error occurs upon running gogs:
```
2016/01/12 03:55:45 [I] Log Mode: File(Info)
2016/01/12 03:55:45 [I] Cache Service Enabled
2016/01/12 03:55:45 [I] Session Service Enabled
2016/01/12 03:55:45 [I] Git Version: 2.7.0
2016/01/12 03:55:45 [T] Doing: CheckRepoStats
2016/01/12 03:55:45 [I] SQLite3 Supported
2016/01/12 03:55:45 [I] Run Mode: Production
2016/01/12 03:55:45 [...gits/gogs/cmd/web.go:97 checkVersion()] [E] Package 'github.com/gogits/git-module' version is too old (0.2.2 -> 0.2.3), did you forget to update?
```

Relevant git-module commit https://github.com/gogits/git-module/commit/081966e117b616a730296a19c55fa8dd2152ec56

**Comment by Unknwon** [comment]
Thanks your report!

I've pushed fix to `develop` branch, please help test again.

**Comment by Eriner** [comment]
Commit https://github.com/gogits/gogs/commit/ab89be33a9d02cf12e55c12bfe5367c33faac8d5 has fixed the issue. Thanks!

**Comment by Unknwon** [comment]
Thanks your confirmation!
