### ISSUE TITLE
what's inside gogs/data/session directory?

### ISSUE THREAD

**Issue by kybin** [gogits/gogs#2386]
Hi, I backup my gogs/data directory with syncthing.

Recently I found files in the session directory keep changing.
I assume those are http session file. Is it correct?
If so, should I keep backup the session files?

Thank you!

**Comment by exmex** [comment]
Maybe not use issues to ask questions. There is a forum if you didn't know:
http://forum.gogs.io

**Comment by kybin** [comment]
ah, sorry. I will ask it there.
