### ISSUE TITLE
Trigger webhook when publish a new release

### ISSUE THREAD

**Issue by bojoyzhou** [gogits/gogs#2387]
git在服务端进行git tag tagname操作的时候不会触发钩子,gogs是否可以代替git做这个操作?
另外建议使用git tag -a tag -m message方式来打tag这样能够从git命令中获取到tagger属性,从而知道是谁提交的tag.

**Comment by xor-gate** [comment]
It would be appreciated to write your issues in english so !chinese people can collaborate :-)

**Comment by bkcsoft** [comment]
@xor-gate or just use google translate? :smile: 
anyhow, title is `Git hooks when not trigger a new release` and text is
> In the server side git git tag tagname when the operation does not trigger hook, gogs whether can replace git to do this operation?
Also recommended to use git tag -a tag -m message this way to play tag can be obtained from the git command to tagger property, so they know who is the tag submitted.

I read that as "I want webhooks for newly pushed tags, also would be nice if one can see who tagged the release"

**Comment by Unknwon** [comment]
> git在服务端进行git tag tagname操作的时候不会触发钩子,gogs是否可以代替git做这个操作?

Why would you tag something on Gogs managed repository?

**Comment by bojoyzhou** [comment]
when i use `/:user/:repo/releases/new` to public release, i wish i can capture that and do something. for example i can write some script to sync file to another server.

**Comment by Unknwon** [comment]
Sorry I'm confused. 

Are you performing all operations through Gogs web UI?

**Comment by bojoyzhou** [comment]
just code review and manage release

**Comment by Unknwon** [comment]
Thank for following up, but I don't think you're answering my question.

How did you make the tag? You said you use command `git tag tagname` on your server?

**Comment by bojoyzhou** [comment]
when i make the tag through Gogs web UI, i found that don't trigger hook. i hope i can sync file to another server when i make the tag.

我使用页面里面的发布新版本进行打tag的时候,后台无法捕捉到事件进行回调,我希望在打tag的时候进行文件同步到另一台机器

**Comment by Unknwon** [comment]
Thanks, I got it now.

I think Git itself does not detect tag event maybe.

So the only thing you could do it use Gogs's webhook.

However, Gogs does not trigger the event too when you publish new release through web UI.

I suggest turn this issue into `trigger webhook and publish a new release`, what do you think?

**Comment by bojoyzhou** [comment]
Thanks. It's OK

**Comment by bojoyzhou** [comment]
I try to use `git tag -a tagname -m "message" && git push --tags` to make a tag. Git detect tag event like  `refs/tags/1233 0000000000000000000000000000000000000000 2b25fb255b5c0bce7457d7c665f449e529d68531`.

**Comment by Unknwon** [comment]
It only detects when you push, but it's not what happening on the server side.

**Comment by bojoyzhou** [comment]
Thanks, that explains a lot.

**Comment by bkcsoft** [comment]
@Unknwon you realize that the WebUI for webhooks actually mentions "creation of tags" right? so according to the WebUI this should work :)
![gogs_webhook](https://cloud.githubusercontent.com/assets/4726179/12371554/e5ad7e90-bc37-11e5-9d2c-fc70e557efac.png)

**Comment by Unknwon** [comment]
@bkcsoft yes, but detection only happens when you `push`.

**Comment by Miminoux** [comment]
Hell, I fell in the same headacke, adding tags in gogs doesn't trigger webhook.
Will it be left the way it is ? I see it removed from the next milestone (0.9.0) 4 days ago, why so ?

**Comment by Unknwon** [comment]
>  I see it removed from the next milestone (0.9.0) 4 days ago, why so ?

Too many issues in 0.9, which makes it never come..

**Comment by liebo** [comment]
+1, trigger tag from web ui is quite important

**Comment by Fchen48** [comment]
1+, if it's possible, add also a server-side git hook for post-release

**Comment by renewsorensen** [comment]
+1

**Comment by chrisbrookes** [comment]
+1

**Comment by alexlcdee** [comment]
## Quick solution as it works in Gogs v0.9.71.0809

1. You can create tag with git-cmd or your prefered git-client
2. Push this tag to your gogs server. Server will trigger a webhook for this action
3. Go to releases page and simply create a new release. You can use existing tag, so put it's name in the tagname field.
4. Excelent! You have decorated release page in gogs and allready fired webhook event for this release (at the step 2).

**Comment by rskumar** [comment]
when you are creating `tag` from `release` page, you already know about the action that's happening. Why cann't a webhook be fired, once tag is created and its confirmed by checking?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

![image](https://cloud.githubusercontent.com/assets/2946214/23827799/6eb6f25a-068a-11e7-8d3b-a4eafdb70dcd.png)

Note that **Save draft** will not fire webhook until you click **Publish**.

**Comment by rskumar** [comment]
Thanks, provided option through UI looks useful

**Comment by Unknwon** [comment]
:trollface: powerful
