### ISSUE TITLE
Sorting repositories into sections

### ISSUE THREAD

**Issue by simonszu** [gogits/gogs#2389]
Hi,

it would be great if there could be a feature that you can sort repositories into sections to clean up your profile a bit. Currently i have around 60 repositorys in my profile, this starts to get messy. 
Maybe provide each section an own URL as well, so instead of 'git@git.hostname.tld:user/repo.git' you have 'git@git.hostname.tld:user/section/repo.git'. I think, gitlab has this feature as well, and since i like the "gitlab, but in simple"-approach of gogs, i want to submit this feature proposal.

**Comment by sapk** [comment]
You could maybe use organization for that ? 
You could make url like that 'git@git.hostname.tld:user-section/repo.git'

**Comment by bkcsoft** [comment]
gitlab doesn't have this feature, they have "groups" which are equivalent of "organizations" :)
and I suggest the same as above

**Comment by Unknwon** [comment]
Same as above ...

**Comment by Unknwon** [comment]
Close due to lack of feedback.
