### ISSUE TITLE
Emoji in old commits

### ISSUE THREAD

**Issue by exmex** [gogits/gogs#2390]
So we recently switched from gitbucket to gogs because gitbucket was using far too much resources.

After the "migration", (changed all origin urls to the new gogs system and pushing it). I noticed that emojis don't work for older commits. This commit is not the newest one (The newest is 3 commits newer)
![](http://i.imgur.com/KBI3vFH.png)

Same emoji in an issue comment:
![](http://i.imgur.com/6brphqZ.png)

**Comment by bkcsoft** [comment]
does it work on any commit? or just not on older ones?

**Comment by Unknwon** [comment]
What is your version of Gogs?

**Comment by exmex** [comment]
Newest self-compiled source ;).
--------
We didn't tested it yet with newer commits. But the old ones are definitely not working.

**Comment by Unknwon** [comment]
OK, reproduced here: https://try.gogs.io/unknwon/issue-2390

**Comment by Unknwon** [comment]
I think it is caused by bug https://github.com/Ranks/emojify.js/issues/154

**Comment by exmex** [comment]
=). That sucks. But at least we know now where it comes from..

**Comment by Unknwon** [comment]
I'm thinking handle this directly in Go...

**Comment by exmex** [comment]
The emoji conversion? I thought you'd already do this. But after I looked I noticed you're not. It would certainly be better to convert it directly and just send the emoji url to the page.

**Comment by Unknwon** [comment]
> convert it directly and just send the emoji url to the page.

Yes, agree.

**Comment by exmex** [comment]
So If a couple guys from us are implementing it, where do you think should we put it? As 3rd party library (I'm not a fan of this idea.), in the template.go file, or as a seperate module in the modules folder?

**Comment by Unknwon** [comment]
Actually, I'm going to implement as 3rd party library because somewhere else is using empjify.js and met the same problem...

**Comment by bkcsoft** [comment]
I'd have a look at this: https://github.com/shurcooL/github_flavored_markdown/issues/1 :smile:

**Comment by Unknwon** [comment]
It's not just markdown, but everywhere... needs something more general. I've already got some idea.

**Comment by exmex** [comment]
Sooo. I tinkered with it and the result was.... The emojify.js is either old or broken. The current from the website works!

http://hassankhan.me/emojify.js/javascripts/emojify.min.js

![](http://i.imgur.com/eSTqxpS.png)

**Comment by Unknwon** [comment]
Somehow, https://github.com/gogits/gogs/pull/2738 solved this.

**Comment by Unknwon** [comment]
Should be fixed by #2738 : https://try.gogs.io/unknwon/issue-2390

**Comment by Unknwon** [comment]
Close as fixed.
