### ISSUE TITLE
dev mode redirects to /install instead of ./install, causes proxy issues 

### ISSUE THREAD

**Issue by dacresni** [gogits/gogs#2391]
I can't proxy to /gogs because the initial redirect is to /install instead of ./install which causes example.com/gogs/install to redirect to example.com/install  which doesn't exist

**Comment by novaeye** [comment]
in [GOGS_ROOT]/custom/conf/app.ini

```
[server] 
ROOT_URL = http://example.com/gogs/
```

**Comment by Unknwon** [comment]
ping @dacresni

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by dacresni** [comment]
sorry, I'll try this out. Commenting doesn't open this does it?

**Comment by Unknwon** [comment]
:trollface:
