### ISSUE TITLE
Gogs under subdomain with CloudFlare timeout

### ISSUE THREAD

**Issue by Wargog** [gogits/gogs#2392]
Gogs will not allow me to connect through a subdomain of my businesses website, but it will let me use my server's DNS name to connect. I have checked gogs-nssm.txt and there no errors coming through, and my browser goes from `Waiting for proxy tunnel` (even though I'm not using one, other than CloudFlare which I had disabled on that subdomain but it did nothing) to `ERR_TIMED_OUT`. The odd thing is the web server I have running on that same subdomain works perfectly. I have also tried using PROTOCOL = http and that didn't work either. I am running Gogs 0.8.10 on Windows Server 2012 R2.

My `custom/conf/app.ini`:
```[server]
DOMAIN = remote.omacostudio.com
PROTOCOL = https
HTTP_ADDR =
HTTP_PORT = 3000
OFFLINE_MODE = false
ROOT_URL = https://remote.omacostudio.com:3000/
CERT_FILE = gogs.crt
KEY_FILE = gogs.key
LOCAL_ROOT_URL = http://localhost:%(HTTP_PORT)s/
DISABLE_SSH = true```

**Comment by novaeye** [comment]
```
HTTP_PORT = 3000
ROOT_URL = https://remote.omacostudio.com:3000/
```
HTTP_PORT access by https?

**Comment by xPaw** [comment]
https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-CloudFlare-work-with-

This is probably the case?

**Comment by Wargog** [comment]
I'll try it, but the weird thing is even disabling CloudFlare for that subdomain didn't work

**Comment by Wargog** [comment]
Thanks @xPaw, switching a proxy supported port worked
