### ISSUE TITLE
cannot install on window7-64bit because cannot identify git cmd

### ISSUE THREAD

**Issue by bobdog1986** [gogits/gogs#2395]
Hello everyone!
I try to install it on my windos7-64bit pc, but fail because:
无法识别 'git' 命令：exec: "git": executable file not found in %PATH%

After add  C:\Program Files (x86)\Git\bin as PATH, still not work.

![image](https://cloud.githubusercontent.com/assets/9330555/12289687/ca9979e6-ba17-11e5-882c-88b0c9fea73e.png)

**Comment by xiegeo** [comment]
在命令行（cmd.exe）里运行一下set path看看PATH有没有更新。命令行得从起一下才能显示新的设置，还有确保设置PATH和运行命令行是一个用户（专门开的管理员命令行可能不管你的用户设置）。

**Comment by bobdog1986** [comment]
你好，xiegeo！
我set path之后，又重启cmd，输入path还是看不到Git的Path，但是有Git Extensions的：
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>path
PATH=C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\Syst
em32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MyS
QL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fa
bric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;%USERPROFILE%\.dnx\b
in;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\GitExtensions\

C:\Users\Administrator>

**Comment by bobdog1986** [comment]
你好，xiegeo！
我自己二了，小白不太懂哈。PATH已经设置好了，谢谢！将git.exe的路径添加到PATH。
