### ISSUE TITLE
Wild Card SSL

### ISSUE THREAD

**Issue by FyinInc** [gogits/gogs#2400]
The GoGS website works great with our wild card SSL.  However, we can only pull/push files using SSH.  If we switch the certs back to our self signed certs - the HTTPS works perfect.  

Over HTTPS we get:

---Git Client---
/fyin.com/project.git/': SSL certificate problem: unable to get local issuer certificate
git did not exit cleanly (exit code 128) (515 ms @ 1/13/2016 12:03:02 PM)

---Console App---
[Macaron] Completed /Fyin.com/PROJECT 200 OK in 15.9320929s
2016/01/13 19:03:08 http: TLS handshake error from 67.166.54.130:38124: remote e
rror: unknown certificate authority
2016/01/13 19:04:56 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshak
ing: EOF
2016/01/13 19:04:58 [...s/modules/ssh/ssh.go:127 listen()] [E] Error on handshak
ing: EOF

---Log---
S:\GoGS\log 
The log file returns no errors or any information

**Comment by Unknwon** [comment]
Hi, are you using any reserve proxy?

**Comment by FyinInc** [comment]
No

 
______________________________________________________
Fyin, Incorporated  :  david@fyin.com   
Phone  :  414.274.0101  :  Fyin.com
 




On Wed, Jan 13, 2016 at 10:45 PM -0800, "无闻" <notifications@github.com> wrote:












Hi, are you using any reserve proxy?

**Comment by Unknwon** [comment]
OK... what I recommend is use a reverse proxy such as NGINX to do such wild card SSL, because I don't know whether Go supports it or not. If Go supports it that's great but I've never used so don't know how exactly... if not, mostly like Gogs won't be able to have it...

**Comment by matt-h** [comment]
Another thing to check would be it you have the full chain in your certificate. I think that not having the full chain can cause this issue with git.

**Comment by FyinInc** [comment]
Would you like to use TeamViewer to see what is going on?
The confusing part is the GoGS web server runs perfectly. We just cannot connect GIT via https. 


 
______________________________________________________
Fyin, Incorporated  :  david@fyin.com   
Phone  :  414.274.0101  :  Fyin.com
 




On Thu, Jan 14, 2016 at 6:29 AM -0800, "Matt" <notifications@github.com> wrote:












Another thing to check would be it you have the full chain in your certificate. I think that not having the full chain can cause this issue with git.

**Comment by Unknwon** [comment]
> The GoGS website works great with our wild card SSL. However, we can only pull/push files using SSH.

What did you do with Gogs to use `wild card SSL`?

**Comment by Unknwon** [comment]
ping @FyinInc

**Comment by FyinInc** [comment]
?

 
______________________________________________________
Fyin, Incorporated  :  david@fyin.com   
Phone  :  414.274.0101  :  Fyin.com
 




On Sat, Feb 6, 2016 at 6:15 PM -0800, "无闻" <notifications@github.com> wrote:












ping @FyinInc

**Comment by Unknwon** [comment]
> What did you do with Gogs to use wild card SSL?

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by FyinInc** [comment]
Odd - I replied to your WildCard question via email - but it didn't make it here. 

All I did was follow the same directions for the self signed cert.  I just updated to the most recent GoGS 0.8.25 and I still have the same error when using HTTPS to get files from GIT. 

From Console window:
"2016/02/23 19:26:01 http: TLS handshake error from a.b.c.d:39731: remote error: unknown certificate authority"

Here is my cert settings:
[server]
PROTOCOL = https
DOMAIN = git.abc.com
HTTP_PORT = 3000
ROOT_URL = https://git.abc.com:3000/
CERT_FILE = custom/https/cert.pem
KEY_FILE = custom/https/key.pem
START_SSH_SERVER = true
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false

SSH works, the web portal works over https:// - we just cannot pull files via https.  

-David

**Comment by Unknwon** [comment]
> From Console window:
"2016/02/23 19:26:01 http: TLS handshake error from a.b.c.d:39731: remote error: unknown certificate authority"

What console? Client? Gogs?

**Comment by FyinInc** [comment]
The console window is from GoGS.

We have tested retrieving from GIT over HTTPS SourceTree, TortoiseGIT and GITExt.  SSH does work.  Our self generated CRT does work.

**Comment by Unknwon** [comment]
I think you maybe just should use NGINX or Apache2, Go maybe not support wildcard SSL very well, as I never used so I can't tell...

**Comment by Unknwon** [comment]
You can continue discussion on https://discuss.gogs.io/ since it is a configuration problem.
