### ISSUE TITLE
Using HTTPS not working (Error code: ssl_error_rx_record_too_long) 

### ISSUE THREAD

**Issue by ChristianAE** [gogits/gogs#2401]
I just installed gogs using Docker. The command I used to run it looks like this:
>  docker run --name=gogs -p 9022:22 -p 9080:3000 -v /mnt/data/programs/gogs:/data gogs/gogs

I used ./go cert to generate key and cert for HTTPS. My config files looks like this:

> [server]
> DOMAIN = DevBox
> PROTOCOL = https
> HTTP_PORT = 3000
> ROOT_URL = https://devbox:3000/
> CERT_FILE = custom/https/cert.pem
> KEY_FILE = custom/https/key.pem

When I try to open the website I get this error: An error occurred during a connection to devbox:9080. SSL received a record that exceeded the maximum permissible length. (Error code: ssl_error_rx_record_too_long)

Looking in the gogs.log I found this entry: Listen: http://0.0.0.0:3000

Is there something wrong with my configuration? According to the log it is not even trying to listen on https. Why do I still get a response on https. I would have expected a 404.

**Comment by Unknwon** [comment]
It seems like you did not change your config correctly, how did you change it?

**Comment by ChristianAE** [comment]
I created an new app.ini file at /mnt/data/programs/gogs/gogs/custom/conf
It contains:
> [server]
> DOMAIN = DevBox
> PROTOCOL = https
> HTTP_PORT = 3000
> ROOT_URL = https://devbox:3000/
> CERT_FILE = custom/https/cert.pem
> KEY_FILE = custom/https/key.pem

> [log]
> LEVEL = Trace

The certificate and key I placed at:
/mnt/data/programs/gogs/gogs/custom/https

The original app.ini file created during intallation I did not alter.
Could this problem somehow be related to wrong permissions? At the moment I need to sudo to be able to edit the app.ini.
And what is the right way to set the log level. According to the documentation it is trace. But opening gogs.log it seems still to log on Info.

**Comment by Unknwon** [comment]
According to the https://github.com/gogits/gogs/tree/master/docker , I think you're editing something that Gogs will never read from it...

**Comment by ChristianAE** [comment]
By my understanding by using the parameter "-v /mnt/data/programs/gogs:/data" when running the docker file I bin it's internal data folder to /mnt/data/programs/gogs.
Creating a repository I could confirm that it is accessible from outside the container at /mnt/data/programs/gogs/git/gogs-repositories.
Shouldn't this also apply to the app.ini?
Can I log this somehow?

**Comment by Unknwon** [comment]
OK in your case I think it should be `/mnt/data/programs/gogs/gogs/conf/app.ini`.

This file should already there after installation.

**Comment by ChristianAE** [comment]
I didn't just alter the created app.ini because of in this articel(https://gogs.io/docs/advanced/configuration_cheat_sheet)  it says: "Before we get started, make sure you know that any change of configuration should be made in custom/conf/app.ini or any corresponding location."

But you are definetly on to something. I now made my changes directly in the conf/app.ini.
The log now prints: 
> 2016/01/14 08:50:28 [I] Listen: https://0.0.0.0:3000
> 2016/01/14 08:50:28 [...gits/gogs/cmd/web.go:573 runWeb()] [E] Fail to start server: open /conf/cert.pem: no such file or directory

Which is partly a success. It means that my changes have an impact. I just can't see why it does not find the file. I placed it now at mnt/data/programs/gogs/gogs/conf/cert.pem

**Comment by Unknwon** [comment]
You setting configurations with relative path, you may want to change it to absolute path.

**Comment by ChristianAE** [comment]
Still the same result:
> 2016/01/14 09:00:47 [...gits/gogs/cmd/web.go:573 runWeb()] [E] Fail to start server: open /mnt/data/programs/gogs/gogs/conf/cert.pem: no such file or directory

Here is the folder it is stored in:

> administrator@DevBox:/mnt/data/programs/gogs/gogs/conf$ ls -l
> total 12
> -rw-r--r-- 1 administrator administrator  837 Jan 14 09:00 app.ini
> -rwxrw-r-- 1 administrator administrator 1131 Jan 13 21:31 cert.pem
> -rwxrw-r-- 1 administrator administrator 1679 Jan 13 21:31 key.pem

**Comment by Unknwon** [comment]
> The certificate and key I placed at:
/mnt/data/programs/gogs/gogs/custom/https

Not same path as I see?

**Comment by Unknwon** [comment]
What is the config values right now in `[server]` section?

**Comment by ChristianAE** [comment]
Here it is:
> [server]
> DOMAIN = localhost
> HTTP_PORT = 3000
> ROOT_URL = https://devbox:3000/
> DISABLE_SSH = false
> SSH_PORT = 22
> OFFLINE_MODE = false
> PROTOCOL = https
> CERT_FILE = /mnt/data/programs/gogs/gogs/conf/cert.pem
> KEY_FILE = /mnt/data/programs/gogs/gogs/conf/key.pem

**Comment by ChristianAE** [comment]
I'll try next to place the file inside of the container. I don't see why that should make a difference since the configuration can also be changed outside from it. But it might pinpoint the problem further. 

I might only find time to do that tomorrow. If you have any suggestions in the meantime let me know.

**Comment by Unknwon** [comment]
Don't have any ideas yet, the path looks correct to me... :sweat:

**Comment by ChristianAE** [comment]
Any chance for you to try to reproduce it using docker?

**Comment by Unknwon** [comment]
I think I may know the problem.

You should use `/data/gogs/conf/cert.pem`, etc. This is the real path inside container.

**Comment by ChristianAE** [comment]
Spot on!

Now using
> docker run --name=gogs -p 9022:22 -p 9080:3000 -v /mnt/data/programs/gogs/data:/data gogs/gogs
to create/run the container and editing conf/app.ini, placing cert and key also in conf works!

It still bothers me a little that the documentation recommends not to alter the conf/app.ini but to create a separate one placed at "custom/conf/app.ini" on just override the neccessary parameter. When I find the time I'll have another look at this and might open a separate issue for it. Otherwise I guess it'll bite me in the ass when I update gogs the next time.

Thank you for your help!

**Comment by Unknwon** [comment]
The one you see is already the custom one without `custom` in the path: https://github.com/gogits/gogs/blob/master/Dockerfile#L12 :trollface:

Everything is special inside Docker container...

**Comment by fenque** [comment]
Same error
