### ISSUE TITLE
Commits time does not match up

### ISSUE THREAD

**Issue by i00** [gogits/gogs#2402]
On the Dashboard when I commit something it says that it was committed 1 min ago.

When I go into the commits it says 18 hours ago... I am in Australia, all the times in gogs seem to be in PST.  The dashboard screen seems to take my local time zone into account, the +18 is the -8 to +10 timezone difference.

I don't know if there is a way to change the time-zone (please let me know)

Regardless, if it can take local timezone into account, it should show all timezones as the browsers timezone should it not?

Also when I hover over the 1 min ago it still states that it was 18 hours ago, but PST (so now but a diff time zone).

**Comment by Unknwon** [comment]
Hi, can you take screenshots of commits time (in hover) and actual time of commit (in command line)?

**Comment by i00** [comment]
Here is the screenshot of the web page...
![screenshot](https://cloud.githubusercontent.com/assets/1435262/12405369/3e453760-be8f-11e5-98be-c7ab569c61b0.png)
Will have to check @ home for the command line as I am @ work.

**Comment by Unknwon** [comment]
@i00 , thanks your info!

But I think you have misunderstanding between **time of activity** and **time of commitment**, they are obviously different, and no guarantee to be the same.

**Comment by i00** [comment]
The time was the same.. It was pushed when it was committed.

**Comment by Unknwon** [comment]
I need you to hover on the time to get exact time of commit:

![image](https://cloud.githubusercontent.com/assets/2946214/12573606/e80a75c4-c3c8-11e5-961b-fc5ae45ce2c1.png)

And exact time from command line such as output of `git log -1`.

Relative time adds no value for debugging.

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by i00** [comment]
The time zone when I hover it is in PST ... my computer is set to EST (Australia Eastern time, Brisbane), also I use the Windows version of Git.

The commits in the screenshots were committed and pushed at the same time ... the screenshots were taken at the same time ... therefore the X Hours ago should be the same???

**Comment by i00** [comment]
I will check the other things that you stated when I get back to work on Monday.

**Comment by Unknwon** [comment]
Thanks for following up!

> The commits in the screenshots were committed and pushed at the same time

I need to know exact (absolute) time, not `same time`, and such relative time.

**Comment by i00** [comment]
Hrm... strange...
![ss](https://cloud.githubusercontent.com/assets/1435262/12879283/bb31c48a-ce7c-11e5-940a-67ed34607ffb.png)
Both my client and my server are set up as AEST??

**Comment by Unknwon** [comment]
Yes, and please do:

> And exact time from command line such as output of git log -1.

**Comment by Unknwon** [comment]
ping @i00

**Comment by i00** [comment]
commit 6e6ca41128b04289c3e17e2294f9aaa9bc998bdc
Author: Kris Bennett <KrisBennett@i00Productions.org>
Date:   Sun Feb 7 22:55:17 2016 +1000

    Comment follows...

**Comment by Unknwon** [comment]
@i00 is anywhere I can get this repository history?

**Comment by Unknwon** [comment]
ping @i00

**Comment by i00** [comment]
Sorry it is private.. Any other way?

**Comment by Unknwon** [comment]
OK, I rechecked your screenshot, I think commit time are showing exactly right.

Only the timezone is different.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
