### ISSUE TITLE
Logs are appearing inspite we've set logging to console

### ISSUE THREAD

**Issue by cusspvz** [gogits/gogs#2404]
We are using latest version available on *Docker Hub* of *Gogs*.

Inspite we've set on `app.ini` to log on *console*, the folder `/data/gogs/log/` have logs from `http`, `update` and `xorm`.

Is that an expected behavior from the *docker image*?

**Comment by Unknwon** [comment]
> Inspite we've set on app.ini to log on console, the folder /data/gogs/log/ have logs from http, update and xorm.

@cusspvz yes, it is expected behavior of all Gogs installation.

**Comment by Unknwon** [comment]
Close according to:

> Please start discussion or ask a question on the forum. GitHub issue tracker only keeps bugs and feature requests, all other topics will be closed without reason.

http://forum.gogs.io/

**Comment by cusspvz** [comment]
@Unknwon just asked for courtesy and to have sure if it was intentional or not.

Now, my request is to log them as specified on the `app.ini`. I don't want to have logs on the FS since we use console for gathering logs from services end we also keep the FS synced between nodes. Because iof its logging into FS, we're having issues between syncs because of constantly changing log files.

**Comment by cusspvz** [comment]
`app.ini`

```
[log]
MODE = console
LEVEL = Info
```

```
josemoreira@MacBook-Pro-de-JM ~/D/B/f/gogs> ls gogs/log/
serv.log   update.log xorm.log
```

**Comment by Unknwon** [comment]
The quick answer is they are in (different) files because they can't be printed on console.

**Comment by cusspvz** [comment]
Are they specific to gogs or to third party software running on Docker?

**Comment by cusspvz** [comment]
ping @Unknwon

**Comment by Unknwon** [comment]
> Are they specific to gogs or to third party software running on Docker?

They are specific to gogs

**Comment by cusspvz** [comment]
So, if we are configuring `logs` to land into process's `stdout`, should them also respect that choice?

Can you please point me why we can't do that? Maybe I could help you with this, I'm not good with Go, but I'm an expert on streams / piping.

**Comment by cusspvz** [comment]
Also, as I see this as a bug once it is doing something it shouldn't, can you re-open please?

**Comment by Unknwon** [comment]
> So, if we are configuring logs to land into process's stdout, should them also respect that choice?

If logs in `serv.log`, `update.log` and `xorm.log`are printed to stdout always, all SSH connections will just break because content of logs are never part of SSH protocol.

For `http.log`, it may possible to print to stdout.

**Comment by Unknwon** [comment]
For SSH connections, there will be handled by another Gogs process, not the main process started by `gogs web`, so `stdout` won't work for those processes.

**Comment by cusspvz** [comment]
But couldn't just you pipe them into the main process?

**Comment by cusspvz** [comment]
Is `gogs update` being called by `gogs web` somehow?

**Comment by 0rax** [comment]
@cusspvz something that can be done with the logs inside the docker container is to create a special service that replace those log files with fifo file that are then piped to a `cat` process. I dont know how effective this could be but it might be a solution for your problem.

We can make that this behaviour is enabled using an enironment variable inside the container.

**Comment by cusspvz** [comment]
[I see](https://github.com/gogits/gogs/blob/master/cmd/update.go#L19). Just a note, on this, SSH already means shell (Secure Shell) :smile: 

Tomorrow I will take a deep look on entire Gogs code and try to help with hints on the better way to do it.

> @cusspvz something that can be done with the logs inside the docker container is to create a special service that replace those log files with fifo file that are then piped to a `cat` process.

@0rax that could work! But if they want all sub-processes of `gogs web` we can arrange a way to pipeline their data streams. Also, `s6` is equipped with a log management cli `s6-log`, which could replace `syslogd` service and also take care of `sshd` logs properly.

Unfortunately docker misses some points when it comes to logs management on clusters. :/

**Comment by 0rax** [comment]
I was aware of `s6-log` but wasnt sure if I would be able to handle sshd logs using it, will look more into it when I have more time. Same goes for the fifo thing, I might try to do this during this week depending on my free time.

**Comment by Unknwon** [comment]
> Is gogs update being called by gogs web somehow?

1. `gogs serv` is called by SSH server, in the builtin server case, it is indeed called by `gogs web`.
2. `gogs update` is called by Git, `gogs web` completely has no control to it.
