### ISSUE TITLE
想问下，copssh和gogs如何关联在一起

### ISSUE THREAD

**Issue by stoneStyle** [gogits/gogs#2405]
官方文档的安装前置条件是需要有copssh，但是怎么配置copssh使其和gogs关联在一起没有详细的说明。我配置的目标是可以让gogs的注册用户通过privite key直接拉取代码，无需每次更新都输入密码，这个该如何配置

**Comment by Unknwon** [comment]
> 官方文档的安装前置条件是需要有copssh

No, it does not.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
