### ISSUE TITLE
View diff file on submodule gives a 404 page

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#2407]
In one of my project i use submodules. When i commit changes that includes changes in a submodule. Submodules appears on the page that shows changes in a commit hash. The url below here is an example 
url http://servername/SCADA/vob.server/commit/9352a729485ed1eac4e81bf655c21c46e96c2ee7

Now if i press the view file button marked in the picture, a 404 page appear.
![capture_commithash](https://cloud.githubusercontent.com/assets/10239939/12317795/bb76b2c6-ba94-11e5-8b80-c68b1df3be87.PNG)

**Comment by nawa** [comment]
PR for fix it #3097

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3097, please help test on `develop` branch or https://try.gogs.io.
