### ISSUE TITLE
Cannot start gogs service -system error 1067: win7 64bit

### ISSUE THREAD

**Issue by bobdog1986** [gogits/gogs#2408]
Hello everyone.
I can start gogs by using command line: gogs web
But I cannot register gogs as windows service by following guide.
If I try "net start gogs", there will be a system error code as "1067":
It seem like ref to mysql , but I cannot find reason , anyone can help?

c:\>net start gogs
gogs 服务正在启动 .    //gogs is starting
gogs 服务无法启动。  //gogs cannot start

系统出错。                 //system error

发生系统错误 1067。 //code 1067

进程意外终止。          //process abort

Following is my custom\conf\app.ini

APP_NAME = eTw-Servo:Gogs Git Server
RUN_USER = 11-PC$
RUN_MODE = prod

[database]
DB_TYPE = mysql
HOST = localhost:3306
NAME = gogs
USER = root
PASSWD = ******
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = C:/Users/Administrator/gogs-repositories

[server]
DOMAIN = gogs
PROTOCOL = http
HTTP_ADDR = 127.0.1.1
HTTP_PORT = 80
OFFLINE_MODE = true
ROOT_URL = http://gogs/

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
DISABLE_REGISTRATION = false
ENABLE_CAPTCHA = true
REQUIRE_SIGNIN_VIEW = false

[picture]
DISABLE_GRAVATAR = true

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info

[security]
INSTALL_LOCK = true
SECRET_KEY = RALYtmZNoZBO35v

![2016-01-14_160339](https://cloud.githubusercontent.com/assets/9330555/12318887/db345570-bad8-11e5-8375-01aaca27a0e0.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

> But I cannot register gogs as windows service by following guide.

Which guide? And how did you get/install your Gogs?

**Comment by bobdog1986** [comment]
Hi, follow this link: https://gogs.io/docs/installation/run_as_windows_service
I had try to register as windos service but fail. I used built-in way.

I  had already solve this issue by add a link to a batch file to start "c:\gogs\gogs web" to the windows start-up folder.
But I must login administrator on my pc after power on .............

**Comment by bobdog1986** [comment]
I install gogs by binary way.
run c:\gogs\gogs web
after that I can use browers.

**Comment by Unknwon** [comment]
>  I used built-in way.

For this case, did you download the version with `mws`?

**Comment by bobdog1986** [comment]
Yes ,I use the mws package.
Doed this issue related to mysql?

**Comment by Unknwon** [comment]
Have you followed the **exactly** same commands provided in the docs?

Especially, 

> C:\> sc create gogs start= auto binPath= ""C:\gogs\gogs.exe" web --config "C:\gogs\conf\app.ini""

**Comment by Unknwon** [comment]
Oh, I think you also need to check windows service log? And `path/to/gogs/log/gogs.log`?

**Comment by exmex** [comment]
Yes I tested that too. And the windows service doesn't work. It's broken.

**Comment by uranium62** [comment]
I have a similar problem...

**Comment by bobdog1986** [comment]
Hello Unknwon:
下午试了不同的mws和non-mws包，在non-mws包里也试着delete\add gogs服务几次。貌似现在已经可以start gogs service，但是还是有些问题，应该是我的custom\conf\app.ini设置的问题。
如果，我在局域网内，PC固定的IP=10.76.100.124，PC的computername=11-PC，想让其他用户直接通过像类似http://10.76.100.124:3000的方式直接访问，应该怎么设置app.ini等文件呢？

**Comment by Unknwon** [comment]
> 我在局域网内，PC固定的IP=10.76.100.124，PC的computername=11-PC，想让其他用户直接通过像类似http://10.76.100.124:3000的方式直接访问，应该怎么设置app.ini等文件呢？

You must have a public IP.

@exmex @uranium62  what is your system? and what's your response to my [comment](https://github.com/gogits/gogs/issues/2408#issuecomment-171575445)?

**Comment by uranium62** [comment]
I found a source of error (-system error 1067)
I changed the service to start under the current user.

**Comment by Unknwon** [comment]
Thanks @uranium62

**Comment by exmex** [comment]
Service creation works fine, starting doesn't work. I'm running Windows Server 2008 R2

**Comment by Unknwon** [comment]
@exmex how you checked `path/to/gogs/log/gogs.log`?

**Comment by exmex** [comment]
I didn't tried creating a service again, so the last answer is still valid:
```
With mws package, AND self compiled with the tag. Both don't work. As far as I remember it didn't created a log either.
```

**Comment by exmex** [comment]
Yup @uranium62 's approach worked.

```
I found a source of error (-system error 1067)
I changed the service to start under the current user.
It helped me in my case.
```

**Comment by Unknwon** [comment]
@exmex I see, so I believe it's the `RUN_USER` check prevents Gogs itself to start.

**Comment by exmex** [comment]
Yup.

**Comment by Unknwon** [comment]
ping @bobdog1986

**Comment by bobdog1986** [comment]
ping what?

**Comment by Unknwon** [comment]
Please check your `RUN_USER` if you still have problem start service. Or maybe the problem have be solved already?

**Comment by bobdog1986** [comment]
I use gogs in local network. No public ip.
I had added a exe-link to windows system start-up folder to solve this issue.

**Comment by Unknwon** [comment]
> I use gogs in local network. No public ip.

Can't help on this.. sorry

> I had added a exe-link to windows system start-up folder to solve this issue.

So the service is working now?

**Comment by bobdog1986** [comment]
Yes. I built gogs for my colleages(3-4 people). Until now , only I pushed 3 repos on gogs(these repos had git on cloud). 
They had never use any version-control tool , just save a .rar file on local computer for every offical release version...

**Comment by Unknwon** [comment]
:joy: Welcome to Git!

**Comment by dongfo** [comment]
PS D:\> net start gogs
服务没有响应控制功能。

请键入 NET HELPMSG 2186 以获得更多的帮助。

and logs:

2018/06/13 15:44:40 [TRACE] Log Mode: File (Trace)
2018/06/13 15:44:40 [ INFO] Gogs 0.11.53.0603
2018/06/13 15:44:40 [ INFO] Cache Service Enabled
2018/06/13 15:44:40 [ INFO] Session Service Enabled
2018/06/13 15:44:40 [ INFO] Mail Service Enabled
2018/06/13 15:44:40 [ INFO] Register Mail Service Enabled
2018/06/13 15:44:40 [ INFO] Notify Mail Service Enabled
2018/06/13 15:44:40 [ INFO] Git Version: 2.15.1
2018/06/13 15:44:40 [ INFO] SQLite3 Supported
2018/06/13 15:44:40 [ INFO] Run Mode: Production
2018/06/13 15:44:40 [TRACE] Doing: CheckRepoStats
2018/06/13 15:44:41 [ INFO] Listen: http://0.0.0.0:3000

**Comment by hellorayza** [comment]
I have the same problem. Acoording to [Use Builtin Functionality ](https://gogs.io/docs/installation/run_as_windows_service#use-builtin-functionality)
I'm sure follow the [tutorial](https://gogs.io/docs/installation/run_as_windows_service) strictly.
when I use `gogs web` under gogs folder,it warn ` [FATAL] [gogs.io/gogs/internal/cmd/web.go:769 runWeb()] Failed to start server: listen tcp 127.0.1.1:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

or use `net start gogs`,
```
PS C:\Users\admin> net start gogs
gogs 服务正在启动 .
gogs 服务无法启动。

系统出错。

发生系统错误 1067。

进程意外终止。
```
**Environment:**

Windows | amd64 |ZIP w/ mws

app.ini
```
BRAND_NAME = Gogs
RUN_USER   = COMPUTERNAME$
RUN_MODE   = prod

[database]
TYPE     = postgres
HOST     = 127.0.0.1:5432
NAME     = gogs
USER     = postgres
PASSWORD = XXX
SSL_MODE = disable
PATH     = D:\gogs\data\gogs.db

[repository]
ROOT = D:/gogs/gogs-repositories

[server]
DOMAIN           = gogs
PROTOCOL         = http
HTTP_PORT        = 80
OFFLINE_MODE     = true
EXTERNAL_URL     = http://gogs/
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = true
OFFLINE_MODE     = false
APP_DATA_PATH    = D:/gogs/data

[mailer]
ENABLED = true
HOST    = smtp.mail.qq.com:25
FROM    = XXX@qq.com
USER    = XXX@qq.com
PASSWD  = udmmkestoygkbega

[service]
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL     = true
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = console, file
LEVEL     = Info
ROOT_PATH = D:/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = 0m7OOiJXe6eBs0n


```

thanks in advance  to anyone with any suggestions

**Comment by unknwon** [comment]
@hellorayza 

>Failed to start server: listen tcp 127.0.1.1:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

I think this is the problem, Gogs does not have permissions to bind 80.
