### ISSUE TITLE
Getting branches from the API

### ISSUE THREAD

**Issue by xsteadfastx** [gogits/gogs#2410]
I need to get a list of branches from a repo for using it with the Jenkins DSL plugin. To create jobs for each branch in the repo. The GitHub-API has something like `/repos/:user:/:repo:/branches`. This didnt worked in gogs. 

And btw: thanks for this wonderful piece of software. Im using it daily and loving it so far.

**Comment by sapk** [comment]
Should not be too hard to do. I will propose something in a PR.

**Comment by sapk** [comment]
This one could be close since PR #2506 is merge if it is ok for @xsteadfastx.

**Comment by Unknwon** [comment]
Close as implemented.
