### ISSUE TITLE
Sometime cannot add a issue - win7

### ISSUE THREAD

**Issue by bobdog1986** [gogits/gogs#2412]
Hello everyone!
I meet a 'bug' that sometime user cannot add a new issue on his repo. And retry is ok.
My usage is:
1. user repo has 5 issue tags like:bug\feedback\enhancement\issue\new feature.
2. user repo has 1 milestone: 2.0
3. user add a new issue and select tag and milestone , after that commit issue then someting wrong happen . There is a 500 error code on web page 
Follow is the console log:
![image](https://cloud.githubusercontent.com/assets/9330555/12344808/5c9df7c6-bb7c-11e5-8982-550e5438a1ad.png)

**Comment by Unknwon** [comment]
Hi, what database are you using?

**Comment by bobdog1986** [comment]
mysql 5.7
If I keep stay at that page, this error will always be there. I must click other title or menu buttons to leave that page and get a update , after that I will be able to add a new issue.Shown as picture above.

In addtion, this issue happens two time today. I just user another laptop and test gogs server.
Next time it happens , I will do more test and hope give you more detail info.

**Comment by TilmannBach** [comment]
i can confirm this happens sometimes on my installation on a Windows Server 2008 R2

the website says something with * invalid token *

**Comment by Unknwon** [comment]
Thanks your info!

Which version of Gogs are you using?

**Comment by bobdog1986** [comment]
© 2015 Gogs 当前版本: 0.8.10.1217

**Comment by Unknwon** [comment]
Thanks. Can you try `go get -u github.com/go-sql-driver/mysql` then recompile the Gogs, and try again?

**Comment by Unknwon** [comment]
Close due to lack of feedback.
