### ISSUE TITLE
Build process on packager.io is failing

### ISSUE THREAD

**Issue by mbi** [gogits/gogs#2414]
https://packager.io/gh/pkgr/gogs

Logs suggest that: `ln: creating symbolic link /opt/gogs/code: No such file or directory`

**Comment by Unknwon** [comment]
Thanks your feedback!

But sadly we can do nothing about it...

**Comment by Unknwon** [comment]
cc @crohr

**Comment by crohr** [comment]
I'll have a look this weekend

**Comment by Unknwon** [comment]
@crohr thank you!

**Comment by crohr** [comment]
This is now fixed (https://packager.io/gh/pkgr/gogs/build_runs/409#48315).

**Comment by mbi** [comment]
Thank you @crohr!
