### ISSUE TITLE
Chinese character encoding problem

### ISSUE THREAD

**Issue by kokororin** [gogits/gogs#2417]
Chinese words in php file has a encoding problem:
[problem in src](https://git.kotori.love/Changle/v2ex/src/master/App/Controller/UserController.class.php)
[the same code with no problem in commits](https://git.kotori.love/Changle/v2ex/commit/a9a67943e3286421a1d79abc66b82370c39fa92f)
[the same code with no problem in raw](https://git.kotori.love/Changle/v2ex/raw/master/App/Controller/UserController.class.php)
[other language code with Chinese has no problem](https://git.kotori.love/Changle/v2ex/src/master/App/View/User/login.html)
Thanks

**Comment by xiegeo** [comment]
Related to issue #2185.

If you can, change all you files to use utf-8 encoding. This will work best. 

Alternatively, you can change https://github.com/gogits/gogs/blob/master/conf/app.ini#L15 to <code>ANSI_CHARSET = GB18030</code> for Simplified Chinese.
