### ISSUE TITLE
Error 500 when creating a pull request

### ISSUE THREAD

**Issue by getson** [gogits/gogs#2418]
cat templates/.VERSION
0.8.10.1217
I have just suddenly got an error when creating a pull request,

log:
[...routers/repo/pull.go:632 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

**Comment by Unknwon** [comment]
Try delete `path/to/gogs/data/tmp` and try again.

**Comment by getson** [comment]
the same with #2490

**Comment by eqbala** [comment]
Same issue we too face any solution
