### ISSUE TITLE
Question about using Git Attributes (filters) with Gogs

### ISSUE THREAD

**Issue by arvislacis** [gogits/gogs#2427]
Hi,

Just wanted to ask if it is possible in Gogs web interface to view blob file diff using Git Attribute filters? More info at https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes I am trying to use odt2txt filter, I think that I have configured everything to work (also git command-line utility now diffs files in text mode) but in Gogs interfece I still see file diff as blob. Thanks for information.

**Comment by arvislacis** [comment]
Found solution for this problem myself.

**Comment by Unknwon** [comment]
:trollface:
