### ISSUE TITLE
post-receive hook: remote: fatal: cannot exec 'hooks/post-receive': Exec format error

### ISSUE THREAD

**Issue by CloudSurgeon** [gogits/gogs#2428]
Using the gogs/gogs:latest container. I have logged into the container and successfully executed the hook via bash shell. I cannot find anything in any of the logs to help me diagnose where the issue lies. I have also successfully tested this hook in my other git repository.

docker logs -f gogs:
Jan 17 20:28:48 sshd[1144]: Accepted publickey for git from 192.168.2.192 port 53500 ssh2: RSA SHA256:XuSh2jyPuIrLTJHslMpGVic/KEhXICEPkB/jnhGLRmg
[Macaron] Started HEAD /user/test_repo/tasks/trigger?branch=master&secret=0900438ecdff1a910fdca275d53c4dda for [::1]
2016/01/17 20:28:48 [D] Session ID: 1a1a7ea8ef494935
2016/01/17 20:28:48 [D] CSRF Token: 63OV5qfXSUhjh1J_l0V65xt1Xx46MTQ1MzA2MjUyODU4MzYyOTg3MA==
[Macaron] Completed /user/test_repo/tasks/trigger?branch=master&secret=0900438ecdff1a910fdca275d53c4dda 202 Accepted in 1.236294ms
2016/01/17 20:28:48 [T] TriggerTask [1].(new request): master
2016/01/17 20:28:48 [T] AddTestPullRequestTask[head_repo_id: 1, head_branch: master]: finding pull requests
2016/01/17 20:28:48 [T] DeliverHooks [1]: processing delivery hooks
Jan 17 20:28:48 sshd[1144]: Received disconnect from 192.168.2.192: 11: disconnected by user
Jan 17 20:28:48 sshd[1144]: Disconnected from 192.168.2.192
2016/01/17 20:28:49 [T] AddTestPullRequestTask[base_repo_id: 1, base_branch: master]: finding pull requests

local Git commit:
[user@linuxtarget testrepo]$ echo `date` >> README.md; git add README.md;git commit -m "third commit"; git push -u origin master
[master 726111d] third commit
 1 files changed, 1 insertions(+), 0 deletions(-)
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 284 bytes, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: fatal: cannot exec 'hooks/post-receive': Exec format error
To ssh://git@linuxtarget:10022/user/test_repo.git
   237746f..726111d  master -> master
Branch master set up to track remote branch master from origin.

post-receive hook:
curl http://linuxtarget.delphix.local:8080/git/notifyCommit?url=ssh://git@linuxtarget:10022/user/test_repo.git

**Comment by bkcsoft** [comment]
Can you post the contents of the post-recieve-hook?

**Comment by CloudSurgeon** [comment]
It was at the bottom:
post-receive hook:
curl http://linuxtarget.delphix.local:8080/git/notifyCommit?url=ssh://git@linuxtarget:10022/user/test_repo.git

**Comment by CloudSurgeon** [comment]
I slept on it and figured out the issue this morning. The same error message occurs, even if I commented out the line. So, I put a shebang at the top and everything worked fine. Final hook:
```
#!/bin/sh
curl http://linuxtarget.delphix.local:8080/git/notifyCommit?url=ssh://git@linuxtarget:10022/adam.bowen/test_repo.git
```

**Comment by Unknwon** [comment]
Hmm, so what is the status of this issue now?

**Comment by CloudSurgeon** [comment]
Ultimately, we could just close it as a non-issue, if you like. But a more descriptive error message would have been beneficial.

**Comment by Unknwon** [comment]
Hmm, right.

> remote: fatal: cannot exec 'hooks/post-receive': Exec format error

I think it is returned by Git (all hooks are called by Git itself), not by Gogs.
