### ISSUE TITLE
TeamCity CI server fails fetch from gogs

### ISSUE THREAD

**Issue by nd** [gogits/gogs#2431]
TeamCity uses java git and ssh implementation (JGit & Jsch). When it tries to list refs of the remote repository hosted by Gogs it fails with timeout exception. Debugging shows that Jsch sets WantReply flag for its ssh requests and waits for reply from Gogs but never gets one. It seems like Gogs doesn't handle ssh requests with WantReply flag set to true.

Gogs Version: v0.8.10 @ 2015-12-18, as well as Gogs built from master branch
Git Version: not applicable since TeamCity uses JGit - java git implementation
System Type: all systems
Error Log: there is no errors in the Gogs logs

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging #2432

**Comment by redoz** [comment]
I'll try to get this fix verified as soon as possible (probably end of this week, beginning of next).

**Comment by redoz** [comment]
I can confirm that this works now. (Running x64 version on Windows)

**Comment by Unknwon** [comment]
Thanks @redoz !
