### ISSUE TITLE
404 for tag with slash

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#2437]
I have a repository that contains tags with slashes, like `something/v1.3`. Only for some of them (interestingly all with the same prefix so the full tag format would be `darkroomtv/vX.Y`), I get a 404 page when I want to browse the source at that tag. I can browse the source at the respective commit without problem though.

The gogs.log shows the following line

    2016/01/19 01:59:05 [...routers/repo/view.go:63 Home()] [E] GetTreeEntryByPath: object does not exist [id: , rel_path: v1.3]

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by NiklasRosenstein** [comment]
It's 0.8.10.1217 (the latest binary package from [here](https://gogs.io/docs/installation/install_from_binary)

**Comment by Unknwon** [comment]
Thanks! Would you be able to produce this on https://try.gogs.io with tag names that have problem?

**Comment by Unknwon** [comment]
Close due to lack of feedback.
