### ISSUE TITLE
SSH issues

### ISSUE THREAD

**Issue by Fnux** [gogits/gogs#2441]
I already installed gogs 2-3 times without any problem, but I really don't understand this one.

Basic setup : PostgresSQL + Gogs + Nginx

The HTTP(S) clone works fin but I can't use ssh : 

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

The `ssh -T  gogs@server` works but returns nothing. I think that `/srv/gogs/app/gogs serv key-1 --config='/srv/gogs/app/custom/conf/app.ini'` is not executed when I use `ssh -T` or `git clone`, which would mean the problem comes from the openSSH server...

I saw the issue [#486](https://github.com/gogits/gogs/issues/486), but it did not help me at all...
Any idea ?

Thank you !

**Comment by Fnux** [comment]
Nevermind, I was able to find the issue with sshd in debug mode + `ssh -Tvvv gogs@server`. My bad. Looks like the gogs user need a shell.
My bad.

**Comment by Unknwon** [comment]
:trollface:
