### ISSUE TITLE
Delete public key does not update '.ssh/authorized_keys' file

### ISSUE THREAD

**Issue by JohnMaguire** [gogits/gogs#2447]
![2016-01-20-220054_849x98_scrot](https://cloud.githubusercontent.com/assets/440033/12470339/4b89ea8c-bfc1-11e5-9b89-5a42ca672af1.png)

```
-> % ssh-keygen -lf ~/.ssh/id_rsa.pub
1024 SHA256:OJv3RI8574AydwpFVjwYiq8R8uYeEbozpGqUaEosbCI /home/john/.ssh/id_rsa.pub (RSA)
```

```
-> % git push
Enter passphrase for key '/home/john/.ssh/id_rsa': 
Gogs: Invalid key ID
Invalid key ID[key-5]: public key does not exist [id: 5]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-> % git pull
Enter passphrase for key '/home/john/.ssh/id_rsa': 
Already up-to-date.
```

```
2016/01/20 21:54:31 [...ts/gogs/cmd/serve.go:201 runServ()] [F] Invalid key ID[key-5]: public key does not exist [id: 5]
```

I created a key, deleted the key (to rename it), and then re-added it. I now can't seem to push. Pulling does seem to work, however it's a public repo (is any SSH key allowed for pulls on public repos?)

v0.8.19.0111. I tried restarting gogs, it did not help.

Thanks (again!) for Gogs! :+1:

**Comment by Wirzi** [comment]
Same problem here!

**Comment by JohnMaguire** [comment]
@Wirzi I'm guessing your repository is marked secret/private? Mine is public, I think that's why I can pull!

**Comment by Wirzi** [comment]
I have deleted the content of the authorized_keys file and created the ssh keys again on gogs and it worked good. The only problem is deleting and readding the same key again.

**Comment by Unknwon** [comment]
@Wirzi  @JohnMaguire Can you reproduce this by same steps on https://try.gogs.io?

**Comment by JohnMaguire** [comment]
I cannot with a different key. Perhaps it has been resolved since 0.8.19? I will try again with the key that was failing on my own installation within the next few days.

**Comment by JohnMaguire** [comment]
I'm not sure how Gogs stores SSH keys, but could this be a permissions issue somewhere on my machine?

**Comment by JohnMaguire** [comment]
Interestingly it seems to have added the key three times to my `.ssh/authorized_keys` -- as if it didn't remove it when I deleted the key.
```command="/home/gogs/go/bin/gogs serv key-5 --config='/home/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAn9BKWOgRXkMtDXe/sKZNPDTqGwDbsEaZHYMZgKMsIZCnvAYM7cvlLhA54lLoTtX78j8pU1qsU2Myp8m6NFSr78vuAg8ffMGz5zRRFxioLHPueqYyeVRhhcrngNxaSIOpMZLpRZqUY/Wy74cOPuCHNG2lDSak13uInX6IEHKTRCM=
command="/home/gogs/go/bin/gogs serv key-6 --config='/home/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAn9BKWOgRXkMtDXe/sKZNPDTqGwDbsEaZHYMZgKMsIZCnvAYM7cvlLhA54lLoTtX78j8pU1qsU2Myp8m6NFSr78vuAg8ffMGz5zRRFxioLHPueqYyeVRhhcrngNxaSIOpMZLpRZqUY/Wy74cOPuCHNG2lDSak13uInX6IEHKTRCM=
command="/home/gogs/go/bin/gogs serv key-7 --config='/home/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAn9BKWOgRXkMtDXe/sKZNPDTqGwDbsEaZHYMZgKMsIZCnvAYM7cvlLhA54lLoTtX78j8pU1qsU2Myp8m6NFSr78vuAg8ffMGz5zRRFxioLHPueqYyeVRhhcrngNxaSIOpMZLpRZqUY/Wy74cOPuCHNG2lDSak13uInX6IEHKTRCM
```

**Comment by JohnMaguire** [comment]
I updated to v0.8.23, removed the old key, added a new key, and deleted it, and I now have four lines in my `.ssh/authorized_keys`.

And I'm still unable to push. :( I'm guessing it's finding the first key in `.ssh/authorized_keys`, calling "gogs serv key-5", but since it was deleted in the DB, it's causing gogs to error out.

**Comment by JohnMaguire** [comment]
**INTERIM SOLUTION**: I deleted the lines from `.ssh/authorized_keys` and added the key again -- everything works as intended.

**Comment by Unknwon** [comment]
@JohnMaguire I see the problem... the delete operation somehow did not delete the old keys.

But regenerate ` .ssh/authorized_keys` file operation on admin panel should work?

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2540

**Comment by nouchka** [comment]
Hello,

experienced a special behavior similar to this one, with theses steps:
- had a key, generate an error adding to gogs, no sure if it was a whitespace, maybe a special characters
- generated a new key, added to gogs without issue, got "public key does not exist" message triying to use it
- loggued to my database (sqlite) and the key_id from error message was not the key_id of my last added key, was the first one
- had to update the database to make the id of the new key match the old one and it was ok

**Comment by emielmolenaar** [comment]
I am still experiencing this issue, running Gogs 0.11.19. Once you delete one or more keys, you are screwed :smiley:

**Comment by bonki** [comment]
@Unknwon Please reopen this, I can confirm that this is still broken in 0.11.29 in the way that @nouchka describes.

**Comment by Unknwon** [comment]
@bonki what is your reproduce steps?
