### ISSUE TITLE
Mac OS X binary offers only MySQL and Postgres support

### ISSUE THREAD

**Issue by jmtd** [gogits/gogs#2453]
```
f6b42bcf7f2bb1daa919bf3b3086d1f87a44551a  ../gogs_v0.8.10_darwin_amd64.zip
```

When running `./gogs web`, the install/setup page offers a choice of PostgreSQL or MySQL DB backends only. However the [downloads page](https://gogs.io/docs/installation/install_from_binary) suggests that SQLite should also be supported.

**Comment by jmtd** [comment]
The `0.8.0` binary *does* offer SQLite.

**Comment by Unknwon** [comment]
Thanks your report!

Updated: https://dl.gogs.io/?sort=time&order=desc
