### ISSUE TITLE
"News Feed" to just "Feed"?

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2454]
I just upgraded today - it was easy and painless! Gogs rocks!

However, I see the "News feed" tab which usually implies an external source for news, and so how about the term "feed" which is usually used for local data. Or, maybe just "Timeline"?

**Comment by exmex** [comment]
Again. Gogs is github inspired. And github uses the term News Feed also.

I don't see any reason for rambling about naming things.

![](http://i.imgur.com/Yu8nX76.png)

**Comment by ChangePlaces** [comment]
Excuse me? I've put forwards some good ideas which have been invorporated into Gogs.  Again, I don't see any reason for _your_ ramblings. See What I did there.

"Naming things" as you refer to it, is about useability. I don't care what Github does, I use gogs as my repo manager, not github. When I put an image into a git repo, is that "code" or is the fact that I've just committed something "news". No.

You may disagree, that's fine. but don't rubbish another person's opinion as "ramblings" - that's just immature..

**Comment by Unknwon** [comment]
Hmm... why "News Feed" is bad?

**Comment by ChangePlaces** [comment]
It isn't 'bad' as such, I don't think commit, and issue etc is "news". like you can subscribe to a blog's "feed", not a blog's "news feed". I think 'feed' is more apt because it's a feed of activity, rather than news.

**Comment by bkcsoft** [comment]
GitLab calls it `Activity Feed` and Bitbucket calls it `Recent Activity`, which IMO makes more sense :)

**Comment by Unknwon** [comment]
+1 for `Recent Activity`...

**Comment by ChangePlaces** [comment]
"Recent Activity" / "Activity Feed" all take up more space than just "feed" and the top of the screen is starting to look cluttered as it is

**Comment by bkcsoft** [comment]
In the profile it says "Public Activity", so WRT keeping it consistent it should be named something with "Activity" in it at least.

Looking at it and comparing to the other buttons/tabs that are there, I'd go for just `Activity` TBH. Since it's short, to-the-point, and consistent with the rest :smile:

**Comment by ChangePlaces** [comment]
@bkcsoft  +1 I like "Activity"

**Comment by Unknwon** [comment]
Looks like we have an agreement on `Activity`?

**Comment by TilmannBach** [comment]
+1 `Activity`

**Comment by Unknwon** [comment]
Please test on `develop` and https://try.gogs.io
