### ISSUE TITLE
"Code" tab to "Files"?

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2455]
Git isn't just about code files, but could be other text-based files. Maybe change the "Code" tab to "Files" to reflect this?

**Comment by emansom** [comment]
What about "Source"?

**Comment by ChangePlaces** [comment]
"Source" would just be short for "source code". Again, git isn't all about code! "Files" covers it all, including image files, config files, documentation etc etc

**Comment by exmex** [comment]
Gog is inspired by github. And github has also a "Code" tab.

**Comment by Unknwon** [comment]
Hmm... I'm open for votes. :trollface:

**Comment by bkcsoft** [comment]
"Source" isn't short for "source code", it's short for "source" and can be pretty much anything, like documentation, notes, music, images, song-lyrics, old receipts and images.

Oh, and "Files" isn't correct either since gogs is also showing directories :trollface:

**Comment by ChangePlaces** [comment]
> "Source" isn't short for "source code", it's short for "source"
In the context of where my water comes from, it would be correct. In the context of coding, it's wrong. Read some old programming books that classically trained programmers have read (think C, C++, assembler) and see how they mention source code, not source.

> Oh, and "Files" isn't correct either since gogs is also showing directories :trollface:
Again, nope; a directory is a file...

**Comment by Unknwon** [comment]
Why `File` is better than `Code`? I prefer `Code` more.

**Comment by floorish** [comment]
It all comes down to what is clear to the user, not what is 100% semantically correct. A `Code` tab is clear to the user coming to Gogs as a git service: it shows the code of the repository. It doesn't matter that it is not 100% code, you'll know what to find there. `Files` could also mean uploaded files, or downloadable binaries. 

Note that Git is a SCM, i.e. source control management system (or source code management). not a file manager. Personally I think `Code` is fine as it is, if it *has* to change then I'd vote  for `Source`.

> Again, nope; a directory is a file...

Never heard that before, source?

**Comment by ChangePlaces** [comment]
>> Again, nope; a directory is a file...

> Never heard that before, source?

According to this thread,  "source" means "code", but not sure what code you want as an answer... I'm not your personal search assistant, try to help yourself.

>Note that Git is a SCM

Git is a VCS - a version control system; a distributed one at that. I quote from the site:
>  Git is a free and open source <b>distributed version control system</b> designed to handle everything from small to very large projects with speed and efficiency.
Git is easy to learn and has a tiny footprint with lightning fast performance. <b>It outclasses SCM tools</b> like Subversion, CVS, Perforce, and ClearCase with features like cheap local branching, convenient staging areas, and multiple workflows. 

Again, git is not about code, it's managing versions of <b>files</b>.

**Comment by bkcsoft** [comment]
@ChangePlaces could you please make up your mind, first you say
> git isn't all about code

and then you say
> in the context of coding

Obviously people are gonna think in the context of whatever they're using it for (except for now when it's called "Code", "Code" is really niched for coding and I don't think that anyone here disagrees with that).
Musicians will think of "source" as whatever files they use for their music-project (samples, project-files, etc).
Coders will (as you said) think of "source code", which actually includes anything that is required to build the application/library (not only code, but also re`source`s :stuck_out_tongue_winking_eye:).
Artists will think of it as psd-files (the source-file from where they export/render) or whatever they're using.

And I agree that git is a VCS (Version Control System), but it is often used for SCM (Source Control Management), and speaking in terms of git it would be called `Blobs` :D

@floorish in a unix-like system, `everything is a file` ;) (you can search for that exact term and get buttloads of sources :smile: )

**Comment by ChangePlaces** [comment]
When I work in photoshop on a project with a graphic designer, I don't think of the output of Photoshop as a source (where stuff comes from), I think of it as a PSD file. Github may be catering to the majority of their userbase (free and / or premium paying users) and that may be code-related, but using a self-hosted git service allows you the freedom to upload large files without having to worry about bandwidth / accout limits etc.

**Comment by floorish** [comment]
@bkcsoft thanks, that gives me enough sources indeed :smile: 

@ChangePlaces 
> Do you mean the c++ code of Git

You're a user of Gogs, open a repository and expect to find Gogs code in the `Code` tab? That does not make sense. Let's be honest, nobody expects that.

> What if there is no code in the repo?

My point is that it does not need to be 100% semantically correct, for it to be intuitive. But let's agree to disagree.

> According to you, "source" means "code"

I never did say that.

> I quote from the site:

I guess your source is http://git-scm.com right? :trollface:

**Comment by ChangePlaces** [comment]
>My point is that it does not need to be 100% semantically correct, for it to be intuitive.

Tomatoes. I like tomatoes. I propose we call the files tab, "tomatoes". It doesn't have to be semantically correct, and we all know that tomatoes refers to whatever is in your git repo.

Tomatoes.

**Comment by Unknwon** [comment]
1. Why `Code` has to be replaced?
2. If `Code` can't do the job perfectly, why the new word can?

**Comment by emansom** [comment]
You shouldn't use git for data anyway. There's [dat](http://dat-data.com/) now.

**Comment by Unknwon** [comment]
I'll stay with `Code`. :mask:
