### ISSUE TITLE
Current version: 0.8.22 -> no binary packages, no tag

### ISSUE THREAD

**Issue by sluedecke** [gogits/gogs#2456]
Github names 0.8.22 as the current version, but I cannot find neither a binary nor a tag in te repository.  Looking in the wrong place?

**Comment by alimy** [comment]
in develop branch of this repository is version of 0.8.22 now. develop branch is the newest version of gogs.

**Comment by alimy** [comment]
@sluedecke maybe [gogs-upgrade tool](https://github.com/alimy/gogs-upgrade) can help you update gogs to the newest version from source build.

**Comment by sluedecke** [comment]
Upgrade tool is good stuff - I'll use it!  Still a 'official' binary download would be great!

**Comment by TilmannBach** [comment]
you can find the commit in gogs.go history
there you can see that develop-release 0.8.22 is tree
https://github.com/gogits/gogs/tree/7ef9a055886574655d9f2be70c957bc16bf30500

**Comment by Unknwon** [comment]
0.8.22 is a version marker but not an official release, so we currently do not provide downloads for it. Sorry about it. :mask:
