### ISSUE TITLE
Packager builds have no sqlite support (but binary does).

### ISSUE THREAD

**Issue by skgsergio** [gogits/gogs#2457]
Hi,

The packager builds lacks of sqlite support (and I don't know if they have PAM support since I couldn't test it), it would be nice if you can enable both sqlite and pam support.

Binary distribution from https://gogs.io/docs/installation/install_from_binary have support for both,

Regards,
Sergio Conde.

**Comment by Unknwon** [comment]
Thanks your feedback!

cc @crohr

**Comment by ytifle** [comment]
I tried to make it work, but it seems that 
https://packager.io/ 
is using the heroku builder, 
https://github.com/heroku/heroku-buildpack-go
that itself uses godep,
https://github.com/tools/godep
and it does not support -tags
https://github.com/tools/godep/issues/59

So, the build tags needed ( -tags "sqlite cert pam" ), are not called, instead, the command 
 -----> Running: go get -tags heroku ./...

**Comment by Unknwon** [comment]
Thanks @ytifle !

Indeed you made a good trick by adding `heroku` tag. If you and @crohr can confirm this does work, I'll merge the PR.

**Comment by crohr** [comment]
@Unknwon sorry, but which PR?

**Comment by ytifle** [comment]
I deleted my fork, I couldn't make it work, as I am not that proficient in Go.

I believe it's a step in the right direction, but I could not manage to make it work. (That's why I deleted the fork)

**Comment by Unknwon** [comment]
@crohr Hmm... sorry no PR, but a commit: https://github.com/gogits/gogs/commit/64ad51c3795b503563c6fd89bd499a66d56ffc2c

**Comment by ytifle** [comment]
It is just a partial commit, it doesn't include all the necessary code.

Sorry

**Comment by Unknwon** [comment]
Oops, that's sad...

**Comment by Unknwon** [comment]
ping for any updates...

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by Outurnate** [comment]
As of today, the current packager.io build doesn't include sqlite or Pam support.  I believe the above fix (making heroku a synonym for "sqlite cert pam") would fix the issue

**Comment by Unknwon** [comment]
@Outurnate Sounds like a good idea in the first thought, but still needs further evaluation. Tag is used not because it works, but it is doing what it intends to do.

**Comment by Outurnate** [comment]
So the intention is to leave pam/sqlite support out of the packager.io build?

**Comment by Unknwon** [comment]
@Outurnate packager.io is not maintained by this repository, you should ask site admin of packager.io to use correct build tag(s).

**Comment by Outurnate** [comment]
@Unknwon while yes, packager.io is a separate service from this repository, the settings it uses are dictated by this repository.  [.pkgr.yml](https://github.com/gogs/gogs/blob/master/.pkgr.yml#L36) sets the heroku buildpack that packager.io uses, which in turn, detects godep and calls it with the heroku flag.  As far as I can see, heroku doesn't seem to have a way to add custom flags to the build process

**Comment by Unknwon** [comment]
As I said, "Sounds like a good idea in the first thought, but still needs further evaluation".

>As far as I can see, heroku doesn't seem to have a way to add custom flags to the build process

This is a good point.

Overall, I suggest open a new ticket to track on this issue.

**Comment by Outurnate** [comment]
I agree - no sense necro'ing this one
