### ISSUE TITLE
Emojis are removed when issue is edited

### ISSUE THREAD

**Issue by dakira** [gogits/gogs#2458]
When you create an issue with emoji, they are removed as soon as you click the edit button.

**Comment by exmex** [comment]
I can confirm this.

**Comment by faouzzz** [comment]
same for me

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by dakira** [comment]
Just updated my install to  0.9.42.0712, can confirm this is fixed now.

Just as a sidenote: I couldn't easily upgrade because there were problems with xorm. Looks like a pull was not possible because you edited the history of already published changes which resulted in conflicts. I had to go to `src/github.com/go-xorm/xorm` and run `git fetch --all && git reset --hard origin/master` to fix this. You should not rebase commits that were already visible on Github.

**Comment by Unknwon** [comment]
@dakira you can just delete `src/github.com/go-xorm/xorm` and re-run `go get`

**Comment by dakira** [comment]
@Unknwon of course that works, too. I just wanted to let you know that it's not good to edit history on public commits. ;)

**Comment by Unknwon** [comment]
@dakira I don't maintain XORM.

**Comment by dakira** [comment]
@Unknwon ouch.. sorry.. I always thought you did ;)
