### ISSUE TITLE
Type error when accessing admin/config

### ISSUE THREAD

**Issue by jeppech** [gogits/gogs#2459]
When accessing above mentioned url, this error occurs `template: admin/config:82:38: executing "admin/config" at <.Service.DisableMini...>: DisableMinimumKeySizeCheck is not a field of struct type interface {}`

I'm on version `0.8.22.0115`

DISABLE_MINIMUM_KEY_SIZE_CHECK is not set in custom/conf/app.ini

**Comment by drsect0r** [comment]
Hi! I also posted this issue https://github.com/gogits/gogs/issues/2449. This is a duplicate off https://github.com/gogits/gogs/issues/2416

**Comment by jeppech** [comment]
Oh sorry, I forgot to search for the issue before posting. Closing this :)

**Comment by drsect0r** [comment]
Thanks! :+1:
