### ISSUE TITLE
Emojis in commit messages breaks json

### ISSUE THREAD

**Issue by MattAndDev** [gogits/gogs#2460]
Adding Emojis to commit messages causes the JSON inserted in DB to be broken.
The broken JSON causes error while displaying the dashboard of the User who did the commit.

This is the error:
```
template: user/dashboard/feeds:41:18: executing "user/dashboard/feeds" at <$push.Commits>: nil pointer evaluating *models.PushCommits.Commits
```

Coming from failure in JSON validation here:
```
func ActionContent2Commits(act Actioner) *models.PushCommits {
	push := models.NewPushCommits()
	if err := json.Unmarshal([]byte(act.GetContent()), push); err != nil {
		return nil
	}
	return push
}
```

Hope this helps to find a workaround and fix the issue.

**Comment by exmex** [comment]
Works fine here. Don't have any problems with it. Is it every commit with emoji's?

**Comment by MattAndDev** [comment]
Yes it appears to be, I made 3 test with different emojis to reproduce the error and I always got the exact same result.
This is true for the two environment I tested with, both virtual servers.
All the Emojis have been typed on Osx using the cmd+ctrl+space shortcut. 

1.
Ubuntu 15.10
git 2.5.0
go 1.4.2
gogs 8.10

2.
Ubuntu 13.4.3
Ubuntu 15.10
git 2.5.0
go 1.4.2
gogs 8.10

Can I do something else to help you debug?

**Comment by exmex** [comment]
Couple of questions still remain:
- Tried with the newest 8.22?
- Where are the emojis? Start, end, middle? 
- What json in DB do you mean?

**Comment by MattAndDev** [comment]
Tried all three: start, middle, end.
In the action Table the content column.

Just updated to 8.22 and made another test:

```
tmp git:(master) ✗ touch test.html
➜  tmp git:(master) ✗ git add test.html
➜  tmp git:(master) ✗ gcmsg "A 🐛  fix"
[master fa90577] A 🐛  fix
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.html
```

caused the JSON for this entry in the described column to be:
```
{"Len":1,"Commits":[{"Sha1":"fa905774f37344bd5ae5eac4983dbe055224395f","Message":"A 
```

**Comment by exmex** [comment]
Problem is with mac. gogits is NOT expecting the characters from emoji. Just the raw string.

**Comment by MattAndDev** [comment]
Thanks for the reference, I tried this but the Emojis are not displayed:

<img width="236" alt="screen shot 2016-01-23 at 11 37 04" src="https://cloud.githubusercontent.com/assets/4579203/12529795/b44b5de8-c1c5-11e5-8572-b10ee8660dd0.png">

You can see the last one is working, this I achieved by closing up the broken JSON on the DB that I described before:
```
{"Len":1,"Commits":[{"Sha1":"fa905774f37344bd5ae5eac4983dbe055224395f","Message":"A 
```
to
```
{"Len":1,"Commits":[{"Sha1":"fa905774f37344bd5ae5eac4983dbe055224395f","Message":"A "}]} 
```

I can surely live without Emojis in git in general, it's just to give red or green light to other developers to use them or not.

**Comment by exmex** [comment]
The (:) has to be replaced with :. Or else github transforms it. :bug: <-- replaced (:) with :

**Comment by MattAndDev** [comment]
Yes this was my first try:
<img width="685" alt="screen shot 2016-01-23 at 11 46 14" src="https://cloud.githubusercontent.com/assets/4579203/12529829/27d0e4a8-c1c7-11e5-936d-deec7602a25e.png">

Typed directly to the terminal.

**Comment by exmex** [comment]
As I said. The emojify that is shipped with gog is somewhat broken. Taking the file from the link and replacing
*GOG DIRECTORY*/public/js/libs/emojify-1.1.0.min.js

works.

**Comment by MattAndDev** [comment]
Sorry my bad, replacing file fixes the issue.

Thank you very much!

**Comment by exmex** [comment]
Glad I could help you,
If this issue is fixed, please close it :)

**Comment by MattAndDev** [comment]
Yes, once last note for reference, with the new file also mac-type Emojis work. (:
Thanks for the effort and great job (:
