### ISSUE TITLE
Can not view closed issues

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#2461]
__Gogs 0.8.10.1217__ -- I can not view the list of closed issues. It actually follows to the new URL, but still displays the open issues. URI for open issues and closed issues compared:

* nrplugins/someproject/issues?type=all&sort=&state=open&labels=0&milestone=0&assignee=0
* nrplugins/someproject/issues?type=all&sort=&state=closed&labels=0&milestone=0&assignee=0

**Comment by NiklasRosenstein** [comment]
The same seems to apply for closed Milestones.

**Comment by NiklasRosenstein** [comment]
In fact, none of the issue filters seem to have any effect.

**Comment by exmex** [comment]
You're using an outdated version. The current version is 0.8.22.

Works fine here.

![](http://i.imgur.com/ubCJaOx.png)

**Comment by NiklasRosenstein** [comment]
Thanks for checking. 0.8.10 is the recent binary release from [here](https://gogs.io/docs/installation/install_from_binary). Guess I'll need to compile it from source to get the recent version. :)

**Comment by Unknwon** [comment]
@NiklasRosenstein can you reproduce this on https://try.gogs.io？

**Comment by NiklasRosenstein** [comment]
No, I can't. Must have been fixed in the meantime, I think that is what @exmex was saying. When I find the time, I'll try to upgrade to 0.8.22 and let you know if its fixed.

**Comment by NiklasRosenstein** [comment]
I've upgrade to Gogs 0.8.25.0129 but the problem persists. I will try to reproduce this on http://try.gogs.io

**Comment by NiklasRosenstein** [comment]
Turns out this issue isn't related to Gogs at all but just an error in my NGinx config. Sorry for the troubles! :disappointed:

**Comment by Unknwon** [comment]
:trollface:
