### ISSUE TITLE
Comparing commits results in an empty changelog

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2462]
A picture is worth a thousand words; I would expect that text would be present here. 
![screenshot from 2016-01-22 15-48-08](https://cloud.githubusercontent.com/assets/9106228/12513725/a15a87be-c11f-11e5-9d3f-8e2a7bf8d924.png)

Aditional information: 
Version: 0.8.22.0115

This only happens when clicking on the link 'View comparison for these x commits' from the dashboard. The differences from the individual commits does work as expected.

**Comment by exmex** [comment]
Please add more information. Diffing works on 0.8.22 on our end.

**Comment by drsect0r** [comment]
@exmex I updated my original post.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #2480

**Comment by drsect0r** [comment]
:+1: Thanks!
