### ISSUE TITLE
Long web hook URL trimmed

### ISSUE THREAD

**Issue by nikdoof** [gogits/gogs#2465]
I'm trying to configure a webhook for Puppet Enterprise Code Manager which accepts Github style webhooks, PE requires that the authentication token is included as either a URL parameter (```&token=```) or as ```X-Authentication``` which Gogs doesn't support. As such the URL is extremely long, for example:

    https://puppetpe.xxxxxxxx.com:8170/code-manager/v1/webhook?type=github&token=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRfdHJpZ2dlciIsImlhdCI6MTQ1MzUwOTgxMywiZXhwIjoxNDg1MTMyMjEzLCJzdWIiOnsiaWQiOiIyOTZkODk5Mi01MzRmLTRlNTktODlmZS1kMzZlNTUzYmFkZGQiLCJsb2dpbiI6ImdpdF90cmlnZ2VyIn19.d1r--SOhl0yvKgevYmDEHuCoEEpqHntAGdVb5I1apwFK8qyvSvGksbbtQas7_KKq2raYpaH_OCZPi7ktnBxTd4qnzGVIRZDVTSwBsmdVsVahiV9BuWRKjoffh1aJ7kD80VFqWk2eIbhiePuULmk63B0gRnzkurSIJYyYJ9j0vAQ7uf6PkdQe8KH1wIpcopSdJklGvTYwXod2-YZfDZ_laI88tCaOrAzZrYG5xHgE3AM544GiitVjQfX4ecVfdbNggCRLNfVyR4FKFm_VOOox4GBrqkj0SNtv3dn5fmhx32Pi0TcsFTYM1qs4DatyMI6bBgF1HapFEZ-5NNT-h9sHO9ONCpMu1B0ctBsS51NW99WXQ6plgEEkRdxPee9f_q0A4gIuvaiyOVea26Uic0mQyE3-zj7c2flCFb2Wgzl0Kfpz-v-n7PeA7_m2dFNCbYfDVRaKlOf3wZvNhen5kWMVg0t3YsFRV_6SGsEPYNGJYxqR8W2dTdWhY425eD5g5zr5saEcl0-2w7liFx0As3CyNqFhJsxlMgqVde5hdoYdcRMIrYvr1sKwFGfq624m4PdDL_h0G7guuy2Z_bLm4rLJD8409DB38IpV3TY929RO7ycMLeLWrWSyhxQ_jyM0WOJ2ei2S7GI-myqn2aTL_QXxq6aCGqHcCn4McZ4Gt5ukm7IXg

This stores correctly in the configuration, but once a request is made the URL is cropped to 255 characters:

    Request URL: https://puppetpe.xxxxxxxx.com:8170/code-manager/v1/webhook?type=github&token=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRfdHJpZ2dlciIsImlhdCI6MTQ1MzUwOTgxMywiZXhwIjoxNDg1MTMyMjEzLCJzdWIiOnsiaWQiOiIyOTZkODk5Mi01MzRmLTRlNTktODlmZS1kMzZlNTUzY
    Request method: POST
    Content-Type: application/json
    X-Gogs-Delivery: abe3956c-3a7b-4cee-a97c-20a6097136bc
    X-Gogs-Event: push

From the server logs:

    10.4.1.115 - - - 23/Jan/2016:01:17:07 +0000 "POST /code-manager/v1/webhook?type=github&token=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRfdHJpZ2dlciIsImlhdCI6MTQ1MzUwOTgxMywiZXhwIjoxNDg1MTMyMjEzLCJzdWIiOnsiaWQiOiIyOTZkODk5Mi01MzRmLTRlNTktODlmZS1kMzZlNTUzY HTTP/1.1" 401 81 10.4.1.115 10.4.1.115 8170 100

Running on Gogs 0.8.15.1231

**Comment by exmex** [comment]
You're using an outdated version.. The current version is 0.8.22.

**Comment by nikdoof** [comment]
Updated to 0.8.22.0115. Still had the same problem.

After a bit of digging in the database it seems that hook_task table still had a 255 len varchar URL field, once upped to a medium text everything worked as expected. I'm guessing the schema has changed slightly since 0.8.15 but with no migration.

**Comment by dakira** [comment]
So the actual bug is a missing migration. Maybe rename the issue to reflect that? BTW: looking at "releases" the latest version is 0.8.10 and not 0.8.22.

**Comment by nikdoof** [comment]
Looking at the code, its not a missing migration issue as its exactly the same as when the webhook_task table was introduced into the codebase. Maybe @exmex is running his dev instance of Gogs on Sqlite, which generally ignores length limits on strings.

**Comment by nikdoof** [comment]
Just checked, v0.8.10 running on Sqlite works as expected. 

At a guess, the solution to this would be correct [the URL field](https://github.com/gogits/gogs/blob/master/models/webhook.go#L288) to be the same as the [Webook table](https://github.com/gogits/gogs/blob/master/models/webhook.go#L87) and create a migration as needed. I have very little golang skills so can't really generate the pull for this.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #2483

BTW, my MySQL server creates TEXT in current version... don't know what happened...

**Comment by Unknwon** [comment]
Close as fixed.
