### ISSUE TITLE
Add CLI install method

### ISSUE THREAD

**Issue by cweagans** [gogits/gogs#2468]
The web installer is nice, but I'd love to be able to do `./gogs install [params]` as part of my deployment scripts, so that when they finish running, I have a fully configured Gogs instance that's ready to go with no further configuration.

**Comment by bkcsoft** [comment]
I can have a look at this later today :smile:

**Comment by Unknwon** [comment]
@cweagans Just set this value to `true` in your custom configuration file: https://github.com/gogits/gogs/blob/master/conf/app.ini#L97

**Comment by cweagans** [comment]
@Unknwon Right, but that requires that I have a configuration file. As part of my deployment automation, I need to do the following:

* Run `gogs install --flag1=whatever --flag2=whatever` (and so forth) and have Gogs generate the initial directory structure for me (inc. the config file and all that)
* Tell the system to make sure Gogs is running on boot using those files ^

Right now, I have to start gogs and then *manually* go in and configure everything on the install page, which is kind of annoying.

**Comment by bkcsoft** [comment]
@cweagans `Tell the system to make sure Gogs is running on boot` not really part of what gogs does, and generally can't be expected to do since every single init-system has their own way of doing it...
The other part I can agree with. Though I'd expect `gogs dump` to save the config-file as well (and be able to extract it with `gogs install/restore`

**Comment by cweagans** [comment]
@bkcsoft Right, I don't expect Gogs to handle that. That's something that would be in my provisioning scripts as something completely separate from the actual Gogs software. The main point I was trying to make is that I need to install Gogs if it's not already installed, and then run it however I'm going to run it. Without the first step, the second step is kind of useless.

**Comment by Unknwon** [comment]
> but that requires that I have a configuration file

Even if you don't need, where do you remember arguments of `gogs install --flag1=whatever --flag2=whatever`?

Directly give a configuration file is the most obvious and simple way. You have default everything here: https://github.com/gogits/gogs/blob/master/conf/app.ini

**Comment by mbugeia** [comment]
Provide a configuration then start gogs. I do this for the yunohost package https://github.com/mbugeia/gogs_ynh and it works well.

**Comment by Unknwon** [comment]
@mbugeia Thanks, added to https://github.com/gogits/gogs/tree/develop#deploy-to-cloud

Close due to lack of feedback.
