### ISSUE TITLE
Where can I find the smart commits documentation?

### ISSUE THREAD

**Issue by renannprado** [gogits/gogs#2472]

**Comment by Unknwon** [comment]
What is `smart commits documentation`?

**Comment by renannprado** [comment]
It's basically when you put special "commands" in the comment of a commit.
For example "this change fixes #(ISSUE_ID)" and then the referenced ISSUE_ID gets actually closed in gogs.
Take a look at here:
https://confluence.atlassian.com/fisheye/using-smart-commits-298976812.html

If gogs doesn't support it, I'm sorry. But I've seen some sample commits in the demo where I see references to issues, so I thought it had support.

**Comment by Unknwon** [comment]
I think Gogs only has reference by `xxx #id yyy`, and close and reopen: https://github.com/gogits/gogs/blob/master/models/action.go#L50-L51

Do you mean docs for these features?

**Comment by renannprado** [comment]
Yep. That's what I meant.
It would be nice to have that pointed in the documentation instead inside of the code.

https://help.github.com/articles/closing-issues-via-commit-messages

Thanks!

**Comment by Unknwon** [comment]
Here you go: https://gogs.io/docs/features/smart_commits

**Comment by renannprado** [comment]
I wonder why this was removed.

**Comment by Unknwon** [comment]
@renannprado https://discuss.gogs.io/c/how-tos
