### ISSUE TITLE
Add option for showing a user list

### ISSUE THREAD

**Issue by loosebits** [gogits/gogs#2477]
Please make a non admin page for listing users (enabled via configuration perhaps)

We have small team (~10 devs) and we've set up gogs so all of our "main" repos are in a single organization however many users have one-off repos in their own name for smaller libraries they wrote being used in the main repos.

It would be nice to have a page (similar to /admin/users) showing a user list so that team members can easily find another team member's repos without having to know the user name.

Right now, the workaround is to create a team under the organization and make sure all devs are in that team.

**Comment by bkcsoft** [comment]
There's the "Explore"-page in the header :) https://try.gogs.io/explore

**Comment by loosebits** [comment]
That just shows the last 20 recently updated repos across all users.

**Comment by bkcsoft** [comment]
Oh right, missed that...

If all users are in the Org you should be able to see them listed under "People" in the Organization-page.

Listing all users (even paginated) is very rarely useable, since for any setup larger than 20-30 people it'd be next to useless. Though a search-bar (like Github has) would be very useful :smile:

**Comment by bkcsoft** [comment]
Erm, totally missed the part about not having to know their Username

**Comment by Unknwon** [comment]
> If all users are in the Org you should be able to see them listed under "People" in the Organization-page.

Hmm, doesn't this help?

**Comment by loosebits** [comment]
Yeah, that's what we're doing, it's a lost of mouse clicks to get there.. why not another section under "Explore" to show a user list if enabled in the app.ini?

**Comment by Unknwon** [comment]
Ultimately, I would like to add user search/list like the way GitHub does.

**Comment by Unknwon** [comment]
I think this is implemented already...
