### ISSUE TITLE
Main branch when migrating repository

### ISSUE THREAD

**Issue by M5oul** [gogits/gogs#2479]
When migrating a repository, the main branch become the first alphabetically branch. I have just tried it for mirrorring.

Can we do something to keep main branch from the original repository

I am using Gogs 0.8.10.

**Comment by bkcsoft** [comment]
main branch isn't a concept that git understands, so this would have to be fetched from wherever you're migrating from, which isn't' possible with HTTP/HTTPS/GIT-urls :disappointed:

**Comment by Unknwon** [comment]
Thanks your feedback!

I think this is basically duplication to https://github.com/gogits/gogs/issues/2225?

**Comment by bkcsoft** [comment]
@Unknwon it is :)

**Comment by M5oul** [comment]
So, let's follow #2225.
