### ISSUE TITLE
Mirror doesn't update repository

### ISSUE THREAD

**Issue by floorish** [gogits/gogs#2481]
I might have a wrong understanding of how the mirror option works, but it does not update commits for me. I have a local bare repository to which new commits are pushed. In Gogs I created a new mirrored repo and set update interval to every hour.

When I push new commits to the bare repo, the mirrored Gogs repo won't show those commits (Log shows only `[T] Doing: MirrorUpdate`)

I checked the code in `repo.go` and in `MirrorUpdate()` it does `"git", "remote", "update", "--prune"`.
What is it supposed to do if it only updates the remotes? This does not update the branches and commits, right?

Should Gogs not create a mirrored repository with `git clone --mirror` and update via `git fetch --all`?
See also: http://stackoverflow.com/a/6079064/695215

**Comment by Unknwon** [comment]
Hmm... this is interesting...

As you can see, all mirror repositories are working properly on demo site ASAIK, example: https://try.gogs.io/gogs/gogs

Which the command itself shouldn't have problem? See https://git-scm.com/docs/git-remote

Did you miss any errors that are presents on log? Or `/admin/notices` page?

**Comment by floorish** [comment]
Yes, it is weird, don't know what's the problem/why it works.
Logging shows no errors, neither does `/admin/notices`. I think it executes the git command just fine, just the branches in the mirrored repository are not updated. Might be due to an old git version? (using git version 1.7.10.4)

I'm using a local mirror (i.e. `/home/floorish/myRepo`), that might be different than a remote link (i.e. github)?

But try this in git: (tried on git version 2.5.4)

```
# create original repository with single commit
git init originalRepo
cd originalRepo && echo "test" > test && git add test && git commit -am "commit 1"

# create mirrored repository
cd ..
git clone --bare originalRepo mirrorRepo

# create second commit in original repository
cd originalRepo && echo "test2" > test && git add test && git commit -am "commit 2"

# check commits in mirror
cd ../mirrorRepo && git log
# it shows "commit 1"

# now update remotes and check commits again in mirror
git remote update
git log
# still shows only "commit 1" as the *local* master branch of the bare mirror is not updated, only 
```

**Comment by Unknwon** [comment]
> \# create mirrored repository
>cd ..
>git clone --bare originalRepo mirrorRepo

It is not the right command to create a mirror repo I think?

You should use `git clone --mirror originalRepo mirrorRepo`.

**Comment by floorish** [comment]
Ah, you're right, sorry. Couldn't find how Gogs created a mirror repository in the code ;)
Ok that works just fine. Then I think there is some problem with my setup. I will check it out and let you know.

**Comment by Unknwon** [comment]
Maybe it's really the version problem...

**Comment by floorish** [comment]
Quick follow-up question: should issues automatically close in the mirrored repository when a commit message includes `fixes #1`, or does that only work when pushing to Gogs directly?

**Comment by Unknwon** [comment]
> or does that only work when pushing to Gogs directly?

Yes.

**Comment by floorish** [comment]
Thanks, you can close this issue for now. I will reopen if it doesn't work with newer version ;)

**Comment by Unknwon** [comment]
:trollface:
