### ISSUE TITLE
tabbing from body of issue textarea and pressing space doesn't submit

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2482]
1. create a new issue
2. tab from the issue title into the body textarea, type description
3. tab from body and press space (which is a button press when a button is highlighted) and issue is not submitted. instead the page just moves down.

**Comment by bkcsoft** [comment]
Tabbing from the body actually makes it select the gogs-logo in the header (FWIW, still a bug)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #2582

**Comment by ChangePlaces** [comment]
works a treat :)

**Comment by Unknwon** [comment]
Thanks your confirmation!
