### ISSUE TITLE
Multiple Webhooks sends wrong payload

### ISSUE THREAD

**Issue by mathicalee** [gogits/gogs#2485]
I had 2 webhooks registered to my gogs repository: to slack and to drone.
The slack webhook works fine, but the drone webhook has a payload that should be sent to slack, which leads to 500 error in drone.

If I remove the slack webhook, then the drone webhook works fine.

**Comment by Unknwon** [comment]
Thanks your feedback!

What's your Gogs version?

**Comment by mathicalee** [comment]
I use gogs/gogs latest docker image, it's 0.8.23.0126.

**Comment by Unknwon** [comment]
Thanks. Does this problem happen 100%?

**Comment by Unknwon** [comment]
ping @mathicalee

**Comment by thehowl** [comment]
I just got the same problem. And here's all the info I could get:

Custom built hook which gets push events works fine, and outputs standard payload.

Slack hook with default settings, outputs slack payload.

Drone hook which gets push events outputs slack payload.

They were ordered in the database in the same order I wrote them (std -> slack -> std)

Removing the slack hook, test delivery and everything's working smoothly. When I added back the slack hook, as it was added after the drone hook, everything worked smoothly again. So my best guess is that a value that switches between the two hook types is changed when it gets to a slack webhook, but it does not "change back" when it gets to a standard webhook.

Gogs version 0.8.31.0205

**Comment by Unknwon** [comment]
> Removing the slack hook, test delivery and everything's working smoothly. When I added back the slack hook, as it was added after the drone hook, everything worked smoothly again. So my best guess is that a value that switches between the two hook types is changed when it gets to a slack webhook, but it does not "change back" when it gets to a standard webhook.

@thehowl thanks for the info!

**Comment by Unknwon** [comment]
Just pushed a fix to `develop` branch, welcome to test on it and demo site.

**Comment by Unknwon** [comment]
ping @mathicalee

**Comment by Unknwon** [comment]
Close as fixed.
