### ISSUE TITLE
Pull request issue on Windows

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#2490]
We have been using pull request for a time now and on one project, where the user created 6 pull requests the last 2 weeks, we now encounter a situation where gogs show a page with a big 500.  

So my user prepares the pull request
![pull request4](https://cloud.githubusercontent.com/assets/10239939/12614445/52b386e4-c500-11e5-93ef-9dd9b1c612cf.png)

Then he push the *Create Pull Request*

And this page appears 
![pull request3](https://cloud.githubusercontent.com/assets/10239939/12614488/928cc4f6-c500-11e5-9890-a2fcb7d05c53.png)

A snip from the log
2016/01/27 14:05:58 [T] PullRequest[0].testPatch(patchPath): g:\Git\scada\vo.downloadsite.git\pulls\7.patch
2016/01/27 14:05:58 [...routers/repo/pull.go:632 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you find out what is the repo ID of the repository you're sending PR to?

If you can, can you check if `path/to/gogs/data/tmp/local/{ID}` is a Git directory or not?

**Comment by renewsorensen** [comment]
There is 2 directories in path *d:\gogs\data\tmp\local*, both of them contains a *.git* folder, and both of the folders only contains 1 folder, and that is *objects* folder from the git structure
![pull request5](https://cloud.githubusercontent.com/assets/10239939/12638304/541277c4-c59c-11e5-844a-2505e6c72d0e.png)

![pull request6](https://cloud.githubusercontent.com/assets/10239939/12638305/580461c6-c59c-11e5-8673-306f255b5b8f.png)

**Comment by Unknwon** [comment]
Thanks! Which system are you using? Feels like Gogs tried to delete the directory but failed to delete `.git` ones (and made it think the directory was not deleted).

**Comment by renewsorensen** [comment]
I use a Windows 2012 R2.
Will i be able to delete the folders under *d:\gogs\data\tmp\local* and make the pull request work, or will that ruin something?



![pull request7](https://cloud.githubusercontent.com/assets/10239939/12642990/a36487f0-c5b9-11e5-93bc-bbc48952231b.png)

**Comment by Unknwon** [comment]
> Will i be able to delete the folders under d:\gogs\data\tmp\local and make the pull request work

Yes, delete by hand will work, `tmp/local` is some kind of cache.

**Comment by Unknwon** [comment]
Actually, can you help check, if these directory are read-only mode?

**Comment by renewsorensen** [comment]
The directories is not, but the files is?
![pull request8](https://cloud.githubusercontent.com/assets/10239939/12655828/27d6bc42-c5fb-11e5-8274-35fa4b884ce1.png)

**Comment by Unknwon** [comment]
I see... then we have the same problem here: https://github.com/gogits/gogs/issues/1738

**Comment by congeal** [comment]
I have similar problem too.
Dogs showed 500 server error when I created a pull request, but I got a different message:

> router/repo/pull.go:633
> CompareAndPullRequestPost()
> [E] NewPullRequest: testPatch: git apply --check: exit status 1 - error: <filename>: ?? ????

**Comment by Unknwon** [comment]
> [E] NewPullRequest: testPatch: git apply --check: exit status 1 - error: : ?? ????

Error is ...???

**Comment by congeal** [comment]
I changed the filename following 'error:' to <filename>.
What I can see in my terminal was '?? ???? ????'
I'm not sure what it is.

**Comment by Unknwon** [comment]
.... I can't get any info from `????` ..... :joy:

**Comment by congeal** [comment]
I did 'git apply' with the new pull request patch the same way gog does, and then I realized that the PR tried to patch a file that is not exist anymore.
I think you can reproduce this problem:
1) 'git rm' a file from a repsoitory (upstream)
2) modify the removed file in a forked repository
3) create PR
You should be able to see 500 server error.

**Comment by Unknwon** [comment]
@congeal what is your version of Gogs?

**Comment by congeal** [comment]
The version of Gogs that I'm using is 0.8.20.0111. 
Do I need to update Gogs?

**Comment by Unknwon** [comment]
Can you try to reproduce this on https://try.gogs.io?

**Comment by congeal** [comment]
@Unknwon I reproduced this problem on https://try.gogs.io.
You should be able to see 500 server error when you create a pull request at branch, 'new_feature' in repository, freezer/gogs_test.
I changed my password to 'qwerty' so you can log-in with the account.

**Comment by Unknwon** [comment]
Thanks!

> You should be able to see 500 server error.

What is the error log from Gogs backend?

**Comment by Unknwon** [comment]
@congeal BTW, please file another issue and we continue dicussion. Yours is completely different from this.

**Comment by Unknwon** [comment]
@congeal anyway, just pushed [a fix](https://github.com/gogits/gogs/commit/a47baa1b7ae08fbcc6946b6c168e69cd4c9894b4) to `develop` branch, and you can retest on https://try.gogs.io now.

**Comment by Unknwon** [comment]
Since https://github.com/gogits/gogs/issues/1738 is fixed.

@renewsorensen can you help retest with `master` branch?

**Comment by renewsorensen** [comment]
I am out of office until next week, but i will test it when i am back...

man. 15. feb. 2016 02.16 skrev 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
ping @renewsorensen ....

**Comment by renewsorensen** [comment]
Sorry @Unknown, i did a few tests yesteday and i was not able to reproduce, sø the fix seems to work  :-)

**Comment by Unknwon** [comment]
@renewsorensen OK, great!
