### ISSUE TITLE
Pull Requests create errors when its creator changes their name

### ISSUE THREAD

**Issue by mhartkorn** [gogits/gogs#2495]
I am using Gogs version 0.8.23.0126 in Docker (`gogs/gogs:latest`).

Changing the name of a user breaks some links on the Pull Request pages.

- 500 Server Error on the "Files changed" tab (URL: /:user/:repo/pulls/:id/files)
- 404 Not Found on the "Commits" tab when you click a revision number of a commit

This is because Gogs does not update the column `head_user_name` in the table `pull_request`.

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging #2494
