### ISSUE TITLE
Create a team with blacklisted name causes error 500

### ISSUE THREAD

**Issue by ciruz** [gogits/gogs#2497]
Hi guys,

if you create a organization team called "admin" or "user" (I guess this are blacklisted) you get an error 500. Creating teams with name "Owner" or another taken team name, gives you the correct alert that this name has been taken.

http://i.imgur.com/NobOfwk.gifv

Gogs Version: 0.8.23.0126

**Comment by Unknwon** [comment]
Thanks your feedback!

> if you create a organization team called "admin" or "user" (I guess this are blacklisted) you get an error 500

Can you post what exactly the error content is from server side of Gogs?

**Comment by ciruz** [comment]
Hey @Unknwon sure, here you go:

```log
2016/01/28 09:16:37 [...routers/org/teams.go:198 NewTeamPost()] [E] NewTeam: name is reserved [name: admin]
2016/01/28 09:16:41 [...routers/org/teams.go:198 NewTeamPost()] [E] NewTeam: name is reserved [name: user]
```

**Comment by Unknwon** [comment]
Thanks! I think forgot to detect reserved error.

**Comment by Unknwon** [comment]
Hi, I just pushed a fix to `develop` branch, feel free to test on https://try.gogs.io/

**Comment by Unknwon** [comment]
ping @ciruz

**Comment by ciruz** [comment]
Hey @Unknwon, thanks for the ping, I really missed the notification.

We already tested your fix and everything works fine, thank you, you're pretty fast.
Right now we're running version 0.8.25.0129 :sunglasses:

**Comment by Unknwon** [comment]
Thanks your confirmation!
