### ISSUE TITLE
Team's permission per repository

### ISSUE THREAD

**Issue by lucacervasio** [gogits/gogs#2499]
Hi All,
I couldn't find this elsewhere so sorry if this is a well-know question.

Is it possible to set permission per repository ?
In my team we have 10 repositories, i want to invite a team member and give him access only to 2 of them, then another team member seeing 3 of them and so on...

Thanks

**Comment by Unknwon** [comment]
Hi, I think it is not implemented...

**Comment by Unknwon** [comment]
> In my team we have 10 repositories, i want to invite a team member and give him access only to 2 of them, then another team member seeing 3 of them and so on...

You should create different teams...

**Comment by Unknwon** [comment]
ping @lucacervasio

**Comment by lucacervasio** [comment]
ok i'll go this way
