### ISSUE TITLE
Markdown different from GitHub? Problem with Image size

### ISSUE THREAD

**Issue by ciruz** [gogits/gogs#2500]
Hi guys,

I've created a `readme.md` with an `<img>` tag inside and noticed that Gogs filters out the `height` and `width` information in the file preview.

My `readme.md` looks like this:
```
# Dev Repo

<img src="https://git-scm.com/images/logos/downloads/Git-Logo-2Color.png" height="100px">
```

I expected that the image is resized to 100px height (like on GitHub), instead this happend and you see the image in original size:

<img src="http://i.imgur.com/HCkKpmL.png">

Also happens with `width` attribute, both attributes gets removed in preview.

Thanks.

Gogs Version: 0.8.24.0128

**Comment by ciruz** [comment]
It works perfect without the `px`, damn css and html mixture. My Mistake. Closed! :-)

**Comment by Unknwon** [comment]
:trollface:
