### ISSUE TITLE
nginx + ssl = bad gateway

### ISSUE THREAD

**Issue by xelfe** [gogits/gogs#2504]
I'm trying to use a signed certificate for the https protocol.é I'm using nginx like proxy;

```
server {
        listen 443 ssl;
        proxy_set_header X-Real-IP  $remote_addr;
        ssl_certificate /etc/letsencrypt/live/git.*******/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/git.*******/privkey.pem;
        location / {
                proxy_pass https://127.0.0.1:3000;
        }
}
```

My custom server app.ini is like;
```
`[server]
PROTOCOL = https
DOMAIN = git.*******
HTTP_PORT = 3000
ROOT_URL = https://git.*******/
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false
CERT_FILE = /etc/letsencrypt/live/git*******/fullchain.pem
KEY_FILE =  /etc/letsencrypt/live/git.*******/privkey.pem`
```
If I put  "proxy_pass http://127.0.0.1:3000;" instead of  "proxy_pass https://127.0.0.1:3000;" and replace into app.ini the protocol http instead of https It's working with the browser but dont with a git client. 

Did i something wrong ?

**Comment by Unknwon** [comment]
> Did i something wrong ?

Yes, with reverse proxy, you only need to setup Gogs as HTTP server, the only place you need to tell Gogs you're using HTTPS is the `ROOT_URL`.

```
[server]
DOMAIN = git.*******
ROOT_URL = https://git.*******/
```

Is good enough.

**Comment by xelfe** [comment]
yeah like I said, it's working with only the http server set and the root url of app.ini set to https but it's not working with git client from any IDE (Eclipse, Netbean, Webstorm, etc)

**Comment by Unknwon** [comment]
> but it's not working with git client from any IDE (Eclipse, Netbean, Webstorm, etc)

What is the error?

**Comment by mhartkorn** [comment]
My reverse proxy nginx is working fine. Try this in your nginx config:

            listen *:443 ssl;

**Comment by xelfe** [comment]
Nevermind. It was a registrar issue with the java cacerts. Thanx for all your help !!

**Comment by Unknwon** [comment]
:trollface:
