### ISSUE TITLE
Fork a mirror feature

### ISSUE THREAD

**Issue by maxchill** [gogits/gogs#2505]
Since the mirrors are readonly, it would be handy to still have the ability to fork, even if you can't push it back to origin.

**Comment by Unknwon** [comment]
Thanks your feedback!

But it may have very low priority...

**Comment by Unknwon** [comment]
This feature is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2663

**Comment by Unknwon** [comment]
Close as implemented.
