### ISSUE TITLE
cloning with ssh doesn't work

### ISSUE THREAD

**Issue by AmbareeshV** [gogits/gogs#2510]
C:\Users\username\git>git clone git@some.com:cid/test.git
Cloning into 'test'...
/usr/bin/bash: git@some.com: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

https is working when used with clone but ssh isn't working,please hel[p me to find it out

**Comment by AmbareeshV** [comment]
I found solution to this problem
http://stackoverflow.com/questions/2499331/git-with-ssh-on-windows

**Comment by Unknwon** [comment]
:+1:
