### ISSUE TITLE
Dashboard history pagination

### ISSUE THREAD

**Issue by MarcosBL** [gogits/gogs#2511]
Add a pagination to dashboard, so user can easily see recent work done, not just the latest

Related to discussion at http://forum.gogs.io/topic/26/recent-activity/2

**Comment by henkjan** [comment]
+1 pagination, or user configurable how much items are displayed on the dashboard is highly desired

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

![image](https://cloud.githubusercontent.com/assets/2946214/24026075/fe22ab06-0a94-11e7-90dc-a8ee6f20e820.png)
