### ISSUE TITLE
Delete corrupt repository

### ISSUE THREAD

**Issue by simonszu** [gogits/gogs#2512]
Hi,

i have a problem with a corrupt repository on my server. I cannot access it via gogs (Error 500) or push/pull from it. So i want to completely remove it from my server and push a clean working copy. But there is a problem: I cannot delete it from gogs due to the error 500 i get every time i try to access the repository. I can physically delete it from my disk, though, but gogs has it still marked as existing, since it is still in the database. 
Is there a way to remove this repository consistencely from the database?

**Comment by ivanmarban** [comment]
What about Repository Manage Panel on admin settings?

**Comment by Unknwon** [comment]
Update to latest version ,then go to `/admin/repos`, you can delete it with ease :100:

**Comment by simonszu** [comment]
I will check the next time. For now, i physically deleted the repo from the disk, and went through the Database manually and removed every reference of the repo_id manually. 
But thanks for your help, i will use it next time.

**Comment by Unknwon** [comment]
:trollface:
