### ISSUE TITLE
Can't push using SSH keys

### ISSUE THREAD

**Issue by the-useless-one** [gogits/gogs#2514]
Hi,

my coworker and I deployed a Gogs server internally, but we're having problem using SSH keys as an authentication method.

We get the following error:
```
$ git push
Gogs: Repository owner does not exist
Unregistered owner: XXX
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The serv.log file says:
```
2016/01/29 16:14:35 [...ts/gogs/cmd/serve.go:165 runServ()] [F] Unregistered owner: XXX
```

If we try to login via SSH, we obtain this successful message:
```
$ ssh -T git@gogs
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
```

We already tried using the "Rewrite the .ssh/authorized_keys file" functionality, or linking the conf/app.ini to the custom/conf/app.ini file, but to no avail.

However, we can connect and push to the server using HTTPS.

Can you help us find the problem? We're running a Gogs compiled from the sources on a Debian 8, using SQLite3 as the DBMS.

Thanks!

**Comment by Unknwon** [comment]
Hi, 

1. What is your version of Gogs?
2. Can you try use absolute path to SQLite3 file path? (in some cases Gogs can't find the right file, which it thinks you're not registered.)

**Comment by the-useless-one** [comment]
1. According to the web interface, we're running version 0.8.24.0128.
2. We tried putting the absolute path to the SQLite3 file, but it didn't work. We couldn't even connect to the web interface.

**Comment by Unknwon** [comment]
> We couldn't even connect to the web interface.

What does this mean?

**Comment by the-useless-one** [comment]
Never mind, my worker didn't put the correct SQLite3 full path (shame on him). We put the correct path and everything works now, even the SSH connection!

Is there somewhere in the documentation where it's advised to put the full path to the SQLite3 file?

Thanks again.

**Comment by Unknwon** [comment]
@the-useless-one no... because in most of cases, the Gogs can correctly detect its binary location and then find the correct location for SQLite3 as well.

I've experienced this problem under Windows, so I know this is the solution, but don't know the cause :D

I'll add this to troubleshooting page ASAP.

**Comment by Unknwon** [comment]
Updated: https://gogs.io/docs/intro/troubleshooting#connect-to-wrong-sqlite3-database

**Comment by theskumar** [comment]
I'm facing similar issue.
1. git clone works over ssh for a private repo.
2. git push works for https
3. ssh -v git@gogs, says i'm authenticated.
4. when I push to remote named `origin` it displays the error although i'm owner of the repo.
```
Gogs: Repository owner does not exist
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
5. If I change the remote name to something else, git push works over ssh. 

Thoughts?

**Comment by Unknwon** [comment]
@theskumar the problem you met is very clear, the repository you try to clone does not exist. Are you able to access the repository via web UI?

**Comment by theskumar** [comment]
@Unknwon yes. I'm able to access the repository via web-UI.

**Comment by Unknwon** [comment]
@theskumar I guess you're using SQLite3 as database? Maybe helpful: https://gogs.io/docs/intro/troubleshooting#connect-to-wrong-sqlite3-database

**Comment by theskumar** [comment]
@Unknwon we use MySql. Just so we are on the same page. Push over ssh works for remote names anything other than `origin`.

The same thing happens while pushing to Gitlab hosted Service (observed for multiple people). So I'm not sure if it's this can be something related to my local git setup.

**Comment by Unknwon** [comment]
@theskumar what is the URL of your `origin`? And is the URL copied from web UI?

**Comment by theskumar** [comment]
yes. the ssh url is copied from web UI
```
$ git remote -v 
essentia	gogs@git.essentiasoftserv.com:essentia/static-website.git (fetch)
essentia	gogs@git.essentiasoftserv.com:essentia/static-website.git (push)
origin	gogs@git.essentiasoftserv.com:essentia/static-website.git (fetch)
origin	gogs@git.essentiasoftserv.com:essentia/static-website.git (push)
```

`git push essentia master` works, but `git push origin master` doesn't.

Web UI
![image](https://cloud.githubusercontent.com/assets/236356/22382889/9adf237a-e4ed-11e6-8af0-da0ee8548e4d.png)

**Comment by Unknwon** [comment]
Hmm... I think indeed you would have to check your local Git settings, at least try another fresh machine.

**Comment by theskumar** [comment]
Sounds like a plan, I'll update if I find anything.

**Comment by vmwsree** [comment]
@theskumar  ssh -T is showing that i am authenticated , 
But still raising 
Gogs: Repository owner does not exist
fatal: Could not read from remote repository.

Not able to pinpoint the fix , adding an extra remote worked on my machine but not on others.

**Comment by ceremcem** [comment]
For those who uses SSH on a different port from 22, solution is adding `ssh://` at the beginning: 

    git push ssh://example.com:1234/myuser/myrepo

**Comment by thurt** [comment]
Thanks @ceremcem, that fixed the issue for me. I am running gogs from a docker container so the my docker host port 10022 was being forwarded to the container ssh port 22. side-note: you forgot `.git` at the end of your address example.
