### ISSUE TITLE
Can clone & push private repository when using apache proxy

### ISSUE THREAD

**Issue by arctican** [gogits/gogs#2515]
Hi. I've created an instance of Gogs on a subdomain in apache, using a proxy in the VirtualHost, but it allows anyone to clone, and push to a private repository. 
 
Setting it up using `example.com:3000` results in an authentication check, but using the proxy, and `git.example.com` simply allows all access.

The web interface works as expected, and stops access to the repo, its just the command line.

In my apache config, I have (as per @Unknwon suggestion at https://github.com/gogits/gogs/issues/158):
```
<VirtualHost *:80>
ServerName git.example.com     
ProxyPass / http://127.0.0.1:3000/     
</VirtualHost>
```

and my Gogs URL settings are:
```
DOMAIN = git.example.com
ROOT_URL = http://git.example.com/
```
I am using the latest binary release version of Gogs - 0.8.10.1217
Apache is version - Apache/2.4.7 (Ubuntu)

**Comment by Unknwon** [comment]
>  but it allows anyone to clone, and push to a private repository.

What are the steps to reproduce this on your server?

**Comment by arctican** [comment]
It is over HTTP.

After creating a private repo on my Gogs instance, I run `git clone http://git.example.com/arctican/test.git` from a completely separate machine, and it clones it without asking for username/password. I can then make changes, and upload to the repository using `git push`.

**Comment by Unknwon** [comment]
Thanks.

Have you tried another machine?

**Comment by arctican** [comment]
Yes, I tried to clone from my brother's machine, with the same result.

**Comment by Unknwon** [comment]
Would you be possible to do tests directly use http://localhost:3000 without Apache?

**Comment by arctican** [comment]
Sure. 

I SSH'd into the machine and stopped apache. 
Running `git clone http://localhost:3000/arctican/test.git` successfully asks for a password.

**Comment by Unknwon** [comment]
OK... there is no chance anyone could bypass authorization and pull/push through HTTP.

Any chance you have saved user/pass info in git config for the domain?

**Comment by arctican** [comment]
Sorry, you are correct. It appears to have stored my git username/password. I created a new user on my machine, and it asked for the username/password. 

However, I don't know why my brother's machine allowed a clone. He has never used git so it can't have stored anything in the past. I possibly changed the apache config between testing his machine and creating this issue, and it was incorrectly set up before. I will test his machine again in the morning, but I feel this can be closed.

Thanks for your help.

**Comment by Unknwon** [comment]
> However, I don't know why my brother's machine allowed a clone. He has never used git so it can't have stored anything in the past. I possibly changed the apache config between testing his machine and creating this issue, and it was incorrectly set up before. I will test his machine again in the morning, but I feel this can be closed.

Maybe you tested with a public repository? :trollface:

**Comment by weaming** [comment]
Same issue. Anyone can clone/push public or private repository over HTTP without asking for username and password.
