### ISSUE TITLE
Global issue list empty when issues are in organization's issues

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#2518]
reproduce:
 - create organization
 - create repos in organization
 - create issue in repos
 - assign issue to you
 - browse to gogs/issues
 - that list is empty

**Comment by Unknwon** [comment]
What is `Global issue list`?

**Comment by carli2** [comment]
![gogs](https://cloud.githubusercontent.com/assets/852396/12696701/8583eed8-c771-11e5-8448-98256f70f7c6.png)

**Comment by Unknwon** [comment]
Thanks, I think this is duplicated to https://github.com/gogits/gogs/issues/1820 ?

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by carli2** [comment]
I uploaded a screenshot, but seems that the upload failed

**Comment by Unknwon** [comment]
@carli2 ....what does that suppose to mean... next?
