### ISSUE TITLE
Some errors happend after I sent an comment under a issue

### ISSUE THREAD

**Issue by mafrashteh** [gogits/gogs#2521]
I got this error after send an comment

template: repo/issue/view_content:56:39: executing "repo/issue/view_content" at <.Poster.Id>: nil pointer evaluating *models.User.Id

I checked my ID in User table in MySQL but I have this problem now!

**Comment by Unknwon** [comment]
Hi, what is your version of Gogs? And can you reproduce this on https://try.gogs.io ?

**Comment by Unknwon** [comment]
ping @mafrashteh

**Comment by Unknwon** [comment]
Close due to lack of feedback.
