### ISSUE TITLE
Add redirection when changing repository owner

### ISSUE THREAD

**Issue by M5oul** [gogits/gogs#2522]
When changing a repository owner, the old URL is broken. It would be great if there could be a redirection toward that new URL.

**Comment by bkcsoft** [comment]
Almost a duplicate of #1566 :trollface: Though I don't agree with @Naxiz. Github keeps the old URLs around as a redirect to the new one, so it would not be too much to ask of Gogs to do the same :stuck_out_tongue_winking_eye:

**Comment by Unknwon** [comment]
as @bkcsoft suggested, maybe we should combine this as same issue of #1566? cc @M5oul

**Comment by M5oul** [comment]
Yep, I close that one.
