### ISSUE TITLE
Plugin for Jenkins

### ISSUE THREAD

**Issue by renannprado** [gogits/gogs#2525]
I'am happy to say that I've just released my first open source project!
It's a plugin for **Jenkins** to integrate with Gogs (http://gogs.io).

Please check it out:
https://github.com/renannprado/gogs-repository-viewer-plugin

**Comment by Unknwon** [comment]
Thanks for letting us know!

Next time it would be better to post this kind of information on http://forum.gogs.io/ .

BTW, put some screenshots may help people (like me) to know what exactly this plugin does.

**Comment by renannprado** [comment]
I didn't know you guys had a forum. Cool. I'll add more information as you asked, some description and then post in the forum!

**Comment by Unknwon** [comment]
:100:
