### ISSUE TITLE
LDAP: Pass through user/pass via `%s` token in BindDN

### ISSUE THREAD

**Issue by galaktor** [gogits/gogs#2526]
Hi guys. First of all, gogs is awesome!

I'm trying to hook it into LDAP at a company. The problems is, I need to use simple LDAP so they login user ("%s") is passed into the LDAP bind credentials (can't store a hard-coded user).

For this, I set the _User DN_ to be `DOM\%s`, where `DOM` is the AD domain and the login name in gogs is used as the username for AD. So when a user `bob` logs into gogs, the ldap binds with his credentials and prepends the domain, i.e. `DOM\bob`.  By doing this, the **bind** (authentication to the AD server) works.

_But_ the actual query to AD FAILS because the "CN" part of the AD query needs to be in a different format. Gogs seems to re-use the `DOM\bob` as part of the query, but our servers use `Lastname, Firstname` instead.

I can reproduce the situation using ldapsearch.

If I do 

```
# uses Lastname and Fistname in query, but DOMAIN\username for binding
ldapsearch -h my.domain.server.com -p 123 -x -b "CN=Builder\, Bob,OU=Users,DC=blah,DC=blah,DC=blah,DC=com" -D "DOM\bob" -W
```

then I will retrieve the user successfully.

But the simple LDAP settings in gogs force me to use the `DOM\bob` (via the login screen) as the "CN" part of the query, so it seems to be sending

```
# uses DOMAIN\username in both query and bind
ldapsearch -h my.domain.server.com -p 123 -x -b "CN=DOM\bob,OU=Users,DC=blah,DC=blah,DC=blah,DC=com" -D "DOM\bob" -W
```

and the output is an error from the AD server.

```
LdapErr: DSID-0C09076F, comment: Error processing name, data 0, v2580
```

I have verified that when I use the BindDN authentication with my credentials hard-coded for the bind, gogs authenticates fine against our AD servers, just as I would expect. But I do not want to use a single persons credentials for this purpose. I want to pass through the username and password from the gogs login for _bind_ in LDAP. When I try to do that in BindDN, it doesn't seem to pass through the username and password via the `%s` token ( a password token would be needed, too) as it does in simple DN. So I'm stuck.

When I use BindDN, I have to hard-code my credentials in order to successfully bind to LDAP, which I don't want to do.

If I want to pass through user/pass from gogs login, I have to use simple DN, but in that case my query is broken.

What can I do here?

**Comment by Unknwon** [comment]
Do you guys have time to take a look?

cc @nanoant @SergioBenitez

**Comment by galaktor** [comment]
I think what I need is what [kanboard's *user mode*](http://kanboard.net/documentation/ldap-authentication) for Active Directory via LDAP is.

It separates the DN from the LDAP authentication user.

Fwiw I'm no AD or LDAP expert, so if this is already possible using gogs, I'd love to know how to make it work.

Cheers guys

**Comment by SergioBenitez** [comment]
The BindDN method allows you to accomplish exactly what you'd like, as you've identified. Unfortunately, the way you've tried using it isn't the way it's meant to be used. 

The idea behind the BindDN is that there is an unprivileged LDAP user with read-only permissions to a few user fields. That user is used as the BindDN. This way, no privileged information is stored in the database.

**Comment by galaktor** [comment]
@SergioBenitez The issue is that I do not want BindDN - I want Simple DN, where the login user is used to authenticate on LDAP.

The problem with SImpleDN is that it doesn't allow me to provide a base DN, it only let's me set the User DN for authentication (in my case needs to be "DOMAIN\username"), but then seems to use that for the User *query* as well (not just authentication).

If the Simple DN had an additional field to specify the query (not filter), like BindDN has, I'd be sorted.

**Comment by SergioBenitez** [comment]
I understand what it is that you'd like, and it seems reasonable to allow this in the future. I'll look into implementing this.

At the moment, however, assuming you can create users on the LDAP server, using a BindDN should meet your needs. What's holding you back from using a BindDN?

**Comment by galaktor** [comment]
I'm afraid I can't create users, it's a highly regulated corporate environment, making changes to AD is not done lightly. Plus I use other tools like this already and they support this for AD.

If it's any help, maybe the following images will illustrate my issue. I need to use Simple DN, but that won't allow me to specify query+filter and auth credentials separately.

![1-ldap-works](https://cloud.githubusercontent.com/assets/1070055/12705208/9c1469b8-c864-11e5-9c69-88054a698b4c.png)

![2-ldap-not-works](https://cloud.githubusercontent.com/assets/1070055/12705210/a1608ae6-c864-11e5-945f-197103e1dfc4.png)

![3-ldap-error](https://cloud.githubusercontent.com/assets/1070055/12705212/a5bb6354-c864-11e5-83c8-3b63563e65f9.png)

**Comment by galaktor** [comment]
Notice the LDAP query bombs out because it won't tolerate "DOMAIN\username" as valid DN syntax - which it isn't. It's the authentication user. If I put in a query, I get credential errors on LDAP because it wants "DOMAIN\username" for auth...

**Comment by nanoant** [comment]
@galaktor What if Gogs escaped properly the backslash character? Would it work then? I dunno if LDAP spec wants the `\` to be escaped but Active Directory apparently does.
Anyways, if yes, then it is just a matter of patching Gogs so it properly escapes the characters, no extra functionality needed.

**Comment by galaktor** [comment]
I'm not sure what exactly LDAP is tripping over when using "DOMAIN\username" for the query, and if that would even work on AD. When I do try to use a query rather than "DOMAIN\username" for SimpleDN User DN, I get the below credentials error.

![4-ldap-cred-error](https://cloud.githubusercontent.com/assets/1070055/12705300/aab1dd5a-c866-11e5-978f-2070ac73dde2.png)

What about allowing to specify auth user template and the Base DN query separately? Similar to what kanboard does (and other tools that support AD via LDAP):

![image](https://cloud.githubusercontent.com/assets/1070055/12705318/1b4ddcc6-c867-11e5-87b8-134eed258167.png)

**Comment by galaktor** [comment]
I am willing to try hack this in myself, but don't know the frameworks (macaron etc.). Can anyone point me at the right place to change

* Authentication UI form for simple LDAP
* Backend that operates on LDAP / AD

I am familiar with golang so it's the architecture that I could use some pointers for.

**Comment by Unknwon** [comment]
Here you go:

1. UI: https://github.com/gogits/gogs/tree/master/templates/admin/auth
2. Backend: https://github.com/gogits/gogs/blob/master/routers/admin/auths.go

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Could anyone remind what is the core problem here?...

**Comment by avindra** [comment]
Can this be reopened? 

The issue is here:

https://github.com/gogits/gogs/blob/a752f0905551a0d8fd6edb893f748cb9490a28dc/modules/auth/ldap/ldap.go#L74

Basically, instead of just passing BindDN, it should allow taking it as a template. For example, we should be able to define our Bind DNs as `%[1]@example.com` or `MYDOMAIN\%[1]`. Then, when the user logs in with `myusername`, it would bind automatically as `myusername@example.com`.

Based on my reading of the code, this is currently not supported, and would be a great enhancement to have.

**Comment by Unknwon** [comment]
@avindra thanks for outstanding explanation. 

So we should allow use `BindDN` value as a template that accepts placeholder like `%s` or `%[1]s`?

**Comment by avindra** [comment]
@Unknwon : Yes, and that placeholder should receive the username that is being bound.

I'm not too familiar with working with Go, but I can try to help testing this

**Comment by Ratcreamsoup** [comment]
We're currently facing the very same problem. I cannot add an unprivileged account to the AD and there seem to be policy issues that actually forbid us from creating such accounts with no password expiry policies, so I currently cannot use AD at all, if I don't wish to set my own account as BindDN and store my password in plain text on the server (and update that whenever I change it). We're already using AD for DokuWiki (via AD/LDAP-Plugin) and I'd very much like to do the same with gogs. Is there any news on an ETA for this issue?

**Comment by Unknwon** [comment]
@Ratcreamsoup Hi, aside from dynamically passing login user's username as query parameter, how about password? Should Gogs send login user's password dynamically as well? (only very little knowledge about LDAP).

**Comment by Ratcreamsoup** [comment]
Sorry, I have exactly zero knowledge about LDAP, I'm barely able to set up the configuration for an LDAP-capable app that needs to authenticate against our company's AD. I only know that with DokuWiki, no separate unpriviledged user is required for AD authentication via LDAP, so I assume that they are using the login users credentials for all of the authentication flow. For the time being my inhouse IT team has set up an unpriviledged account with no password expiry for me to use with gogs, so everything is working satisfactorily right now. Still, a flow like implemented in DokuWiki seems more straightforward. Maybe someone with more insight into both LDAP and gogs source can draw some conclusions from the DokuWiki plugin:authldap source?

https://www.dokuwiki.org/plugin:authldap
https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/authldap/auth.php

Kind regards

  Markus

**Comment by Unknwon** [comment]
@Ratcreamsoup Thanks for the links! The docs are indeed helpful!

**Comment by notes-jj** [comment]
I found a curious flavor of searching LDAP, which makes it impossible to use Gogs with Microsoft Active Directory or IBM Domino LDAP, but it works on OpenLDAP.

With `LDAP (simple auth)` the search uses the `userDN` as `baseDN` for the LDAP search. In the simple auth case the baseDN is a concrete User (a leave not a node). MS AD and Domino LDAP won't return anything in that case.  

I suggest to leave the `User Search Base` field in the LDAP Simple Auth HTML Form and use it as `baseDN`. The User is filtered through the user filter.

Change Lines in Source: [gogs/pkg/auth/ldap/ldap.go - a1d411a](https://github.com/gogits/gogs/commit/a1d411a0182dd5c5ba227acf43781181c11a1ae3) Line 226 ff

    search := ldap.NewSearchRequest(
        userDN, ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false, userFilter,
        []string{ls.AttributeUsername, ls.AttributeName, ls.AttributeSurname, ls.AttributeMail, ls.UserUID},
        nil)

### Bind DN in different LDAP Directries

The Bind DN doesn't have to be an X.400 formated address. For MS AD the valid User Names are (see [MS KB](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380525(v=vs.85).aspx):
- NETBIOS-DOMAIN\sAMAccountName (e.g. domain\johndoe)
- sAMAccountName@dns-domain-name (e.g. johndoe@domain.example.com)
- userPrincipalName which might be different from sAMAccountName@dns-domain-name (e.g. john.doe@example.com)

For Domino LDAP there are other options as well.

For a reason, I could no find in the source code the pure `%s` in the `User DN` will invalid the whole LDAP Configuration and no LDAP trace message is shown in the log. Please modify the code to leave the `Bind DN` in that format, the user enters in the logon field. The user can be found with the User Filter: `(&(objectClass=person)(userPrincipalName=%s))`

Sorry. I'm no the great GO developer nor I'm deeply involved in Gogs , so I don't feel capable to create a pull request, fix the problem and test it in an adequate way.

**Comment by bmullen** [comment]
Having same issue here.  Dokuwiki does work here, a setup similar should work for many who are having similar issues.

**Comment by linuxflavoredterminals** [comment]
Any update on this? My org also isn't willing to add anonymous searching OR give me an unprivileged LDAP account for searches.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by codecrafting-net** [comment]
With the new version 0.11.39 I was able to connect with ldap (Microsoft AD) with BindDN option using DOM\\%s. However, I have to give the password. Would be nice to get the password from the login form and use it as the password to bind the ldap. When I provide no password (on the authentication config screen) gogs will perform a anonymous search, which on my case is not allowed. My account don't have write permissions, so I can't create a user for the gogs. On the authentication menu could have a checkbox like "use login password to bind".

**Comment by Unknwon** [comment]
> On the authentication menu could have a checkbox like "use login password to bind".

@codecrafting-net good point, can you open another issue to track this new suggestion?
