### ISSUE TITLE
URLs to a non-existing user/org result in a blank page

### ISSUE THREAD

**Issue by fnkr** [gogits/gogs#2529]
URLs to a non-existing user/org result in a blank page.

- https://try.gogs.io/give_me_404 <-- blank page
- https://try.gogs.io/give_me_404/with_nice_ui <-- nice error page

![screenshot from 2016-01-31 19-24-01](https://cloud.githubusercontent.com/assets/616991/12703958/4fc35e3e-c850-11e5-88ea-973a7af6fcfa.png)
![screenshot from 2016-01-31 19-24-12](https://cloud.githubusercontent.com/assets/616991/12703959/4fc38940-c850-11e5-8c26-37d6446449ba.png)

Gogs version: 0.8.25.0130

**Comment by Unknwon** [comment]
Thanks your feedback!

Just pushed a fix to `develop` and you can test on https://try.gogs.io/give_me_404

**Comment by fnkr** [comment]
Works for me. Thanks for fixing.
