### ISSUE TITLE
Error after upgrading from 0.8.10 to 0.8.25, while restarting

### ISSUE THREAD

**Issue by Rickou412** [gogits/gogs#2532]
```
2016/01/31 21:07:03 [I] Gogs: Go Git Service 0.8.25.0129
2016/01/31 21:07:03 [I] Log Mode: File(Info)
2016/01/31 21:07:03 [I] Cache Service Enabled
2016/01/31 21:07:03 [I] Session Service Enabled
2016/01/31 21:07:03 [I] Mail Service Enabled
2016/01/31 21:07:03 [I] Notify Mail Service Enabled
2016/01/31 21:07:03 [I] Git Version: 1.7.10.4
2016/01/31 21:07:03 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: pq: la colonne « num_following » de la relation « user » existe déjà
2016/01/31 21:07:03 [I] SQLite3 Supported
2016/01/31 21:07:03 [I] Run Mode: Production
2016/01/31 21:07:03 [T] Doing: CheckRepoStats
2016/01/31 21:07:04 [I] Listen: http://0.0.0.0:3500/gogs
...
```

Application seems to work normally and display correctly followers and followings

**Comment by Unknwon** [comment]
Thanks your feedback!

Just to clarify, there is no database migration from 0.8.10 to 0.8.25.

> pq: la colonne « num_following » de la relation « user » existe déjà

Can you help translate to English?

**Comment by Rickou412** [comment]
pq: the column "num_following" from the relation "user" already exists

**Comment by Unknwon** [comment]
Thanks. Is this 100% reproducible?

**Comment by Rickou412** [comment]
From a fresh install of gogs 0.8.10, it's not reproductible (tested in a docker container)

My installation was pretty old, with frequent migration from version 0.5.x

**Comment by Unknwon** [comment]
Thanks. I meant is this error happens every time you try to start Gogs?

**Comment by Rickou412** [comment]
The error appears only on the first start after the upgrade. I only see it one time.

**Comment by Unknwon** [comment]
So you're able to use Gogs normally now?

**Comment by Rickou412** [comment]
Yes gogs is 100% functionnal

**Comment by Unknwon** [comment]
:joy::joy::joy:

**Comment by Rickou412** [comment]
thank you! With your questions I realize how stupid was this new issue.
