### ISSUE TITLE
Relative Links in markdown

### ISSUE THREAD

**Issue by exmex** [gogits/gogs#2545]
Relative links are a great thing. I'd like to have them in gogs too.

https://github.com/blog/1395-relative-links-in-markup-files

I've tried it like so:
`[Sample File](REPONAME/SampleFile.obj)`

it didn't show a link to it.

**Comment by fnkr** [comment]
Try it like this:

```
Link to other issue: [#1](/issues/1)  
Link to file: [README.md](/src/master/LICENSE)
```

Demo: https://try.gogs.io/fnkr/demo/issues/1

**Comment by Unknwon** [comment]
Hi @exmex , your comments isn't very clear to me...?

https://try.gogs.io/unknwon/issue-2545

**Comment by exmex** [comment]
`[Sample.fpm](/src/master/File%20Definitions/FPM/Sample.fpm)`

Doesn't get resolved for me.

**Comment by Unknwon** [comment]
> Doesn't get resolved for me.

In which page and how to reproduce?

**Comment by exmex** [comment]
I have a file in

src/master/File Definitions/FPM/FPM Definition.md

which should link to a sample file in
src/master/File Definitions/FPM/Sample.fpm

but it doesn't show a link.


Markdown file:
`[Sample.fpm](/src/master/File%20Definitions/FPM/Sample.fpm)`

Displayed:
![](http://i.imgur.com/HyWU9ih.png)

**Comment by Unknwon** [comment]
What is the raw content of your markdown?

And by `Doesn't work`, what does it mean? No link at all? Wrong link?

**Comment by exmex** [comment]
> What is the raw content of your markdown?

See comment above. the Markdown file content is there.

\/ This is the raw markdown. (Tried both. Not working)
Markdown file:
`[Sample.fpm](/src/master/File%20Definitions/FPM/Sample.fpm)` <- Doesn't work
`[Sample.fpm](File%20Definitions/FPM/Sample.fpm)` <- Doesn't work

> And by Doesn't work, what does it mean? No link at all? Wrong link?

See screenshot. No link at all. It's truncated.
![](http://i.imgur.com/VrMjxIk.png)

**Comment by Unknwon** [comment]
See here: https://try.gogs.io/unknwon/issue-2545/issues/1

The one with `%20` does work.

**Comment by exmex** [comment]
In the issue page yes. But not in a markdown (md) file.

**Comment by Unknwon** [comment]
No? ... https://try.gogs.io/unknwon/issue-2545

**Comment by exmex** [comment]
Hm.. Doesn't work for me.. Weird.

**Comment by Unknwon** [comment]
Always make sure you have the latest version?

**Comment by exmex** [comment]
We're using a fork of gogits (latest developer branch), but on the local copy (sqlite) it works for some reason. Not on the production server (mysql). I'll look into this and will report back.

**Comment by exmex** [comment]
Reproduced here:
https://try.gogs.io/exmex/issue-2545-test/src/master/File%20Definitions/FPM/fpm%20Definition.md

**Comment by Unknwon** [comment]
OK, great!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2836, you can test on demo site: https://try.gogs.io/exmex/issue-2545-test/src/master/File%20Definitions/FPM/fpm%20Definition.md
