### ISSUE TITLE
Gogs web interface broken after update

### ISSUE THREAD

**Issue by adrien-thebault** [gogits/gogs#2549]
Hello,

I just updated Gogs on my server and now it doesn't work anymore when I try to access the web interface, it wants me to download some file that seems empty and meaningless.

(You can try by yourself by going here https://src.adrien-thebault.fr/) 

stderr.log only contains this : 
> 2016/02/03 18:08:11 http: multiple response.WriteHeader calls

but stdout.log contains this : 
> [Macaron] PANIC: middleware render hasn't been registered

followed by the trace

I don't understand why this is happening, any idea?

- Gogs version : 0.8.25
- Git version : 2.1.4
- OS : Debian 8.3
- Using nginx 1.8.0 as a reverse proxy

**Comment by Unknwon** [comment]
Hi @adrien-thebault , how did you upgrade?

**Comment by adrien-thebault** [comment]
using `go get -u github.com/gogits/gogs` and then `go build` in `$GOPATH/src/github.com/gogits/go-gogs-client` & `$GOPATH/src/github.com/gogits/gog`

**Comment by Unknwon** [comment]
Thanks. If you can't view web, how do you know you're in version 0.8.25?

**Comment by adrien-thebault** [comment]
It's written in README.md : 
> ##### Current version: 0.8.25

(Thanks for your help)

**Comment by adrien-thebault** [comment]
Hmm, maybe the problem is not coming from Gogs, when I try `wget localhost:3131/`, it seems to work (I'm able to get the index.html), but nothing changed in my nginx config, did I miss something ?

**Comment by Unknwon** [comment]
When you do `wget localhost:3131/`, the content looks like normal?

**Comment by adrien-thebault** [comment]
Well, it looks like a perfectly normal web page. Also, the footer contains `© 2016 Gogs Version: 0.8.25.0129 Page: <strong>3ms</strong> Template: <strong>2ms</strong>` which tends to confirm that I'm in version 0.8.25.

What is even more strange is that it also works with "wget src.adrien-thebault.fr/" from the server and from my computer (which is on another network), but it doesn't work on Chrome or on Firefox!

**Comment by Unknwon** [comment]
I have no idea... the only thing I can think of is you have broken source code of Gogs but I don't think that's possible.

**Comment by adrien-thebault** [comment]
Sure, but I don't think it will help much, it's quite a basic config : 

> #HTTP
> 
> server {
> 
>         listen 80;
>         server_name src.adrien-thebault.fr;
> 
>         # Forcing HTTPS
>         rewrite ^ https://$server_name$request_uri? permanent;
> 
>         location / {
>                 proxy_pass http://localhost:3131;
>         }
> 
>         access_log /var/log/nginx/access.log;
>         error_log /var/log/nginx/error.log;
> 
> }
> 
> #HTTPS
> 
> server {
> 
>         listen 443;
>         server_name src.adrien-thebault.fr;
> 
>         ssl on;
>         ssl_certificate ssl/certs/src.adrien-thebault.fr.chained.crt;
>         ssl_certificate_key ssl/private.key;
> 
>         include ssl/ssl.conf;
> 
>         location / {
>                 proxy_pass http://localhost:3131;
>         }
> 
>         access_log /var/log/nginx/access.log;
>         error_log /var/log/nginx/error.log;
> 
> }

Where *ssl.conf* is SSL/TLS related stuff (Cipher list, DH Params, HPKP, HSTS, Elliptic Curves & OCSP Stapling)

**Comment by adrien-thebault** [comment]
Made a fresh install, I only kept my old config, here's what happens : 

> 2016/02/03 23:33:07 [T] Custom path: /home/git/go/src/github.com/gogits/gogs/custom
> 2016/02/03 23:33:07 [T] Log path: /home/git/go/src/github.com/gogits/gogs/log
> 2016/02/03 23:33:07 [I] Gogs 0.8.25.0129
> 2016/02/03 23:33:07 [I] Log Mode: File(Trace)
> 2016/02/03 23:33:07 [I] Cache Service Enabled
> 2016/02/03 23:33:07 [I] Session Service Enabled
> 2016/02/03 23:33:07 [I] Mail Service Enabled
> 2016/02/03 23:33:07 [I] Register Mail Service Enabled
> 2016/02/03 23:33:07 [I] Notify Mail Service Enabled
> 2016/02/03 23:33:07 [I] Git Version: 2.1.4
> 2016/02/03 23:33:08 [T] Doing: CheckRepoStats
> 2016/02/03 23:33:08 [I] Run Mode: Production
> 2016/02/03 23:33:09 [I] Listen: http://localhost:3131
> [Macaron] PANIC: middleware render hasn't been registered
> /usr/local/go/src/runtime/panic.go:423 (0x42b649)
> /home/git/go/src/gopkg.in/macaron.v1/render.go:608 (0x758855)
> 	renderNotRegistered: panic("middleware render hasn't been registered")
> /home/git/go/src/gopkg.in/macaron.v1/render.go:612 (0x758874)
> 	(*dummyRender).SetResponseWriter: renderNotRegistered()
> /home/git/go/src/github.com/go-macaron/gzip/gzip.go:90 (0x68fbc9)
> 	Gziper.func1: ctx.Render.SetResponseWriter(gzw)
> /usr/local/go/src/runtime/asm_amd64.s:437 (0x45c5ce)
> /usr/local/go/src/reflect/value.go:432 (0x88691a)
> /usr/local/go/src/reflect/value.go:300 (0x8855e1)
> /home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb7cc02)
> 	(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
> /home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x74dbd7)
> 	(*Context).run: vals, err := c.Invoke(c.handler())
> /home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x74dabc)
> 	(*Context).Next: c.run()
> /home/git/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x763432)
> 	Recovery.func1: c.Next()
> /usr/local/go/src/runtime/asm_amd64.s:437 (0x45c5ce)
> /usr/local/go/src/reflect/value.go:432 (0x88691a)
> /usr/local/go/src/reflect/value.go:300 (0x8855e1)
> /home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb7cc02)
> 	(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
> /home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x74dbd7)
> 	(*Context).run: vals, err := c.Invoke(c.handler())
> /home/git/go/src/gopkg.in/macaron.v1/router.go:184 (0x764bb4)
> 	(*Router).Handle.func1: c.run()
> /home/git/go/src/gopkg.in/macaron.v1/router.go:286 (0x75b52d)
> 	(*Router).ServeHTTP: h(rw, req, p)
> /home/git/go/src/gopkg.in/macaron.v1/macaron.go:176 (0x75304a)
> 	(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
> /usr/local/go/src/net/http/server.go:1862 (0x651d9e)
> /usr/local/go/src/net/http/server.go:1361 (0x64f58e)
> /usr/local/go/src/runtime/asm_amd64.s:1696 (0x45e911)
> 2016/02/03 23:33:11 http: multiple response.WriteHeader calls

`[Macaron] PANIC: middleware render hasn't been registered` and what follows happens each time I try to access the web interface

**Comment by Unknwon** [comment]
At this point, I suggest you use compiled version for now... have no idea at the moment...

**Comment by adrien-thebault** [comment]
It must be something that comes from my config, I removed my custom/conf/app.ini and now it works, do you mind if I put my config here so you have a look?

**Comment by Unknwon** [comment]
... Sure, you can join https://gitter.im/gogits/gogs and DM to me.

**Comment by moritzheiber** [comment]
I just hit the same roadblock, and it turns out I had to disable `gzip` in the configuration:

    ENABLE_GZIP = false

For some reason it used to work before, but now it doesn't anymore. I'm also using nginx as a proxy, and it does indeed do `gzip` (Chrome/Firefox are requesting gzipped content and are getting back gzipped content). My log looks exactly the same:

```
[Macaron] Started GET / for <ip-address>
[Macaron] PANIC: middleware render hasn't been registered
/usr/local/go/src/runtime/panic.go:423 (0x42b5c9)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/render.go:608 (0x75c0f5)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/render.go:612 (0x75c114)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/github.com/go-macaron/gzip/gzip.go:90 (0x692cc9)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45c4ee)
/usr/local/go/src/reflect/value.go:432 (0x88ae9a)
/usr/local/go/src/reflect/value.go:300 (0x889b61)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/github.com/go-macaron/inject/inject.go:117 (0xb81122)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/context.go:113 (0x751477)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/context.go:104 (0x75135c)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x766cd2)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45c4ee)
/usr/local/go/src/reflect/value.go:432 (0x88ae9a)
/usr/local/go/src/reflect/value.go:300 (0x889b61)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/github.com/go-macaron/inject/inject.go:117 (0xb81122)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/context.go:113 (0x751477)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/context.go:104 (0x75135c)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/logger.go:40 (0x76591e)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x45c4ee)
/usr/local/go/src/reflect/value.go:432 (0x88ae9a)
/usr/local/go/src/reflect/value.go:300 (0x889b61)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/github.com/go-macaron/inject/inject.go:117 (0xb81122)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/context.go:113 (0x751477)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/router.go:184 (0x768454)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/router.go:286 (0x75edcd)
/tmp/d20160205-14-wnm2my/opt/gogs/.heroku/go/src/gopkg.in/macaron.v1/macaron.go:176 (0x7568ea)
/usr/local/go/src/net/http/server.go:1862 (0x654e9e)
/usr/local/go/src/net/http/server.go:1361 (0x65268e)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x45e831)
2016/02/13 17:01:21 http: multiple response.WriteHeader calls
[Macaron] Completed / 500 Internal Server Error in 84.831858ms
```

I'm guessing

    web -- gzip --> nginx -- gzip --> gogs

used to work, but now only

    web -- gzip --> nginx ----> gogs

does?

**Comment by Unknwon** [comment]
If used to work... I think it was bug.

Now it is fixed?

**Comment by moritzheiber** [comment]
It really is. And yes, without `gzip` enabled (i.e. `ENABLE_GZIP = false`) is works. So I guess this is .. ok?

**Comment by Unknwon** [comment]
@moritzheiber yeah, if you already used gzip in NGINX, there is no point gzip again between NGINX and Gogs (both local to each other) other than wasting CPU?

**Comment by moritzheiber** [comment]
I concur. I wonder why it left it as enabled in the first place.

Cheers for the help :+1:

**Comment by Unknwon** [comment]
It is `false` by default... https://github.com/gogits/gogs/blob/master/conf/app.ini#L85

**Comment by moritzheiber** [comment]
Oh, sorry, didn't mean to imply it was a default. I meant more like "Why did I leave it enabled after going through the file, testing options". Entirely my fault :smiley:

**Comment by Unknwon** [comment]
@moritzheiber Oh... not sure how old version you were using, but there was a bug that gzip isn't taking effect at all in very very old time.

**Comment by moritzheiber** [comment]
I feel like I've been using Gogs for ages now. That might be the case :)

**Comment by Unknwon** [comment]
:joy:

**Comment by loxK** [comment]
Just got the exact same issue upgrading from apt-get.

Disabling GZIP made it work again and it also used to work with GZIP enabled until this update.
