### ISSUE TITLE
SSH on Windows with OpenSSH failing

### ISSUE THREAD

**Issue by rjrudman** [gogits/gogs#2551]
Hi,

I've spent the last few hours trying to get this working. I've installed OpenSSH on a windows machine, and that all works perfectly when manually adding keys into authorized_keys, etc.

Going through the Gogs UI and adding the same key produces this file:

`command="c:/Gogs/gogs.exe serv key-1 --config='c:/Gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa */MyKey/*  `

Now, running the command: `c:/Gogs/gogs.exe serv key-1 --config='c:/Gogs/custom/conf/app.ini'` on the remote machine works fine, giving the welcome message "Hi there, you've successfully authenticated", etc.

sshing into and pushing both fail:

```
$ ssh -v rudman@192.168.1.176
OpenSSH_7.1p1, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to 192.168.1.176 [192.168.1.176] port 22.
debug1: Connection established.
debug1: identity file /c/Users/Rob/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Rob/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
debug1: match: OpenSSH_7.1p1 Microsoft_Win32_port_with_VS pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.1.176:22 as 'rudman'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:IM2wIjS1RZ78HmZsBDQmE4H2Ju/OsH9nDx0jMQbtUls
debug1: Host '192.168.1.176' is known and matches the ECDSA host key.
debug1: Found key in /c/Users/Rob/.ssh/known_hosts:1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /c/Users/Rob/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.1.176 ([192.168.1.176]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: Forced command.
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: Pty allocation disabled.
PTY allocation request failed on channel 0
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to 192.168.1.176 closed.
Transferred: sent 3448, received 2872 bytes, in 0.1 seconds
Bytes per second: sent 30024.1, received 25008.5
debug1: Exit status 0

```

There are no logs whatsoever output from gogs, and there are no logs in windows event viewer for OpenSSH (and none in the log.txt file either).

Any ideas?

**Comment by Unknwon** [comment]
Thanks your feedback!

So bad I can't see any obvious reason why connection fails.

But for special care of Windows users, if you're running version higher than 0.8, you can use [this config option](https://github.com/gogits/gogs/blob/master/conf/app.ini#L58) to enable builtin SSH server of Gogs which should work very smoothly.

**Comment by rjrudman** [comment]
Thank you - that works perfectly now. I am not sure if it's an issue, but sshing (not pushing with git) causes the process to hang (instead of showing the MOTD/Greeting). Minor issue though, since it works perfectly with git. Thanks! :+1:

**Comment by Unknwon** [comment]
> sshing (not pushing with git) 

How to reproduce this?

**Comment by bkcsoft** [comment]
@Unknwon mostlikely do doing `ssh git@gogs-host` :trollface:

**Comment by Unknwon** [comment]
Ah... what is the error though?

**Comment by rjrudman** [comment]
@Unknwon There is no error. It gives a warning about 'PTY allocation request failed on channel 0' and then ends the connection. Removing the `no-pty` gets rid of the warning, but the connection immediately closes. I wasn't able to find any logs or output about what went wrong, the above verbose ssh is as much information as I was able to get.

**Comment by Unknwon** [comment]
@rjrudman you should looks at gogs backend console see if any log prints (upgrade to latest version first `master`). If no log, which means the request never arrives to Gogs...

**Comment by rjrudman** [comment]
@Unknwon There was no output at all on the gogs console (using the latest binaries - amd | ZIP w/ mws). I wasn't able to find any logs, unfortunately. Though it does definitely seem that it never executed the `gogs.exe`

**Comment by Unknwon** [comment]
Well... I'm lost..
