### ISSUE TITLE
Clone this repository does not include HTTP Port

### ISSUE THREAD

**Issue by rjrudman** [gogits/gogs#2552]
When using a custom port, the 'clone this repository page' gives an invalid address for HTTP(s):

[See here](http://i.imgur.com/Uy7MG4Q.png)

**Comment by tkausl** [comment]
Cannot reproduce on develop-branch:
http://i.imgur.com/1L9lBGZ.png

**Comment by Unknwon** [comment]
+1 to @tkausl 's solution.

**Comment by rjrudman** [comment]
I thought I had tried that - guess not. Fixes the problem, thanks! :+1:
