### ISSUE TITLE
Fail to initialize ORM engine: migrate: sync

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#2553]
Hi! I'm using a MySQL database. I'm not sure what changed, but now it shuts down after some time. I get this error in `gogs.log`:

    2016/02/04 13:35:11 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 127.0.0.1:3306: getsockopt: connection refused

This is my database configuration

    [database]
    DB_TYPE = mysql
    HOST = 127.0.0.1:3306
    NAME = gogs
    USER = gogs
    PASSWD = ******
    SSL_MODE = disable
    PATH = data/gogs.db

Any idea what could cause this error? And I'm also unsure about the `PATH = data/gogs.db` part since I'm using a MySQL server it shouldn't need the path to a database file?

Thanks

**Comment by Unknwon** [comment]
Hi, based on the error it means connection failed.... maybe there is a bug in the Go MySQL driver...

`PATH = data/gogs.db` and `SSL_MODE` are ignored when you use MySQL.

**Comment by NiklasRosenstein** [comment]
It used to work before so I'm not sure what has changed. This one's still running 8.10 maybe an upgrade would fix it. Is there a way to debug the MySQL connection?

**Comment by Unknwon** [comment]
Is it failing 100% at start?

**Comment by NiklasRosenstein** [comment]
No only after some time (last time about 19 hours later). Here's some more from the log:

```
2016/02/03 09:20:09 [I] Log Mode: File(Info)
2016/02/03 09:20:09 [I] Cache Service Enabled
2016/02/03 09:20:09 [I] Session Service Enabled
2016/02/03 09:20:09 [I] Mail Service Enabled
2016/02/03 09:20:09 [I] Register Mail Service Enabled
2016/02/03 09:20:09 [I] Notify Mail Service Enabled
2016/02/03 09:20:09 [I] Git Version: 2.6.0.rc3
2016/02/03 09:20:09 [I] SQLite3 Supported
2016/02/03 09:20:09 [I] Run Mode: Production
2016/02/03 09:20:09 [I] Listen: http://0.0.0.0:3000
2016/02/03 16:41:38 [I] Log Mode: File(Info)
2016/02/03 16:41:38 [I] Cache Service Enabled
2016/02/03 16:41:38 [I] Session Service Enabled
2016/02/03 16:41:38 [I] Mail Service Enabled
2016/02/03 16:41:38 [I] Register Mail Service Enabled
2016/02/03 16:41:38 [I] Notify Mail Service Enabled
2016/02/03 16:41:38 [I] Git Version: 2.6.0.rc3
2016/02/03 16:41:38 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 127.0.0.1:3306: getsockopt: connection refused
2016/02/03 18:27:05 [I] Log Mode: File(Info)
2016/02/03 18:27:05 [I] Cache Service Enabled
2016/02/03 18:27:05 [I] Session Service Enabled
2016/02/03 18:27:05 [I] Mail Service Enabled
2016/02/03 18:27:05 [I] Register Mail Service Enabled
2016/02/03 18:27:05 [I] Notify Mail Service Enabled
2016/02/03 18:27:05 [I] Git Version: 2.6.0.rc3
2016/02/03 18:27:05 [I] SQLite3 Supported
2016/02/03 18:27:05 [I] Run Mode: Production
2016/02/03 18:27:05 [I] Listen: http://0.0.0.0:3000
2016/02/04 13:35:11 [I] Log Mode: File(Info)
2016/02/04 13:35:11 [I] Cache Service Enabled
2016/02/04 13:35:11 [I] Session Service Enabled
2016/02/04 13:35:11 [I] Mail Service Enabled
2016/02/04 13:35:11 [I] Register Mail Service Enabled
2016/02/04 13:35:11 [I] Notify Mail Service Enabled
2016/02/04 13:35:11 [I] Git Version: 2.6.0.rc3
2016/02/04 13:35:11 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 127.0.0.1:3306: getsockopt: connection refused
```

**Comment by Unknwon** [comment]
If I search error `getsockopt: connection refused` on Google.... it happens all around Go community :joy:

**Comment by NiklasRosenstein** [comment]
It seems to work again, I haven't experienced this issue again. I think it had something to do with permissions in the MySQL database.

**Comment by Unknwon** [comment]
:+1:

**Comment by galactic-void** [comment]
Hi,
I had this problem when the server was rebooted. In my case the problem was Gogs starting before Mysql.

My server is running Debian 8 (Jessie) so modifying `/etc/init.d/gogs` Required-Start and adding mysql to it has fixed it:
`# Required-Start:    $syslog $network mysql`

and then run `insserv -d`

So for the op the problem might be with Mysql rather than Gogs.

**Comment by Unknwon** [comment]
@galactic-void maybe you should tell script start Gogs after MySQL?

**Comment by aty010** [comment]
I am running Gogs version 0.9.20.0404 on centos7 with exact same issue of gogs failed to connect to mysql. Following is my work around script.

```
#!/bin/bash
#  work around untils issue is fixed at https://github.com/gogits/gogs/issues/2553
PATH=$PATH:/sbin:/bin:/usr/sbin:/usr/bin
PIDS=$(pidof gogs)

if test -z "${PIDS}"
then
   echo  `date`  | mailx -s "gogs is dead, restarting... " me@test.com
   /usr/bin/systemctl restart gogs
fi

```

**Comment by tjyang** [comment]
Just to add a note for future reference.

I am running Gogs version 0.9.20.0404 on centos7 with exact same issue of gogs failed to connect to mysql. Following is my work around script.

```
#!/bin/bash
#  work around untils issue is fixed at https://github.com/gogits/gogs/issues/2553
PATH=$PATH:/sbin:/bin:/usr/sbin:/usr/bin
PIDS=$(pidof gogs)

if test -z "${PIDS}"
then
   echo  `date`  | mailx -s "gogs is dead, restarting... "  me@test.com
   /usr/bin/systemctl restart gogs
fi
```

**Comment by ntomka** [comment]
According to @galactic-void init.d file is indeed wrong. I used his required-start section and on Ubuntu server this is the bare minimum to run gogs on system startup properly (using mysql as database server), in `/etc/init.d/gogs`

```SH
#!/bin/sh
### BEGIN INIT INFO
# Required-Start: $syslog $network mysql
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Provides: gogs
# Required-Stop:
### END INIT INFO

echo "This job runs via upstart, invoking upstart now..."
exec initctl $1 gogs
```

Then run this as root:

```SH
update-rc.d gogs defaults
update-rc.d gogs enable
```

Notice Default-Start and Default-Stop is set to mysql defaults.

**Comment by lambarena** [comment]
. I fixed this on Debian Jessie by adding `After=mysql.service` to gogs.service.

**Comment by DanielGilbert** [comment]
The `After=mysql.service` line alone didn't help me. I also had to change `Type=simple` to `Type=idle`, so that the service gets started as the very last. That made the error disappear and everything works fine.

**Comment by benediktg** [comment]
@DanielGilbert The `After=` line alone should be adequate according to https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=:

> `Type=`
> Behavior of `idle` is very similar to `simple`; however, actual execution of the service binary is delayed until all active jobs are dispatched. This may be used to avoid interleaving of output of shell services with the status output on the console. Note that this type is useful only to improve console output, it is not useful as a general unit ordering tool, and the effect of this service type is subject to a 5s time-out, after which the service binary is invoked anyway.

(I also had this issue with Debian 8 – the resaon was that I had `mysqld.service` instead of `mysql.service` in the systemd unit. :wink:)

**Comment by DanielGilbert** [comment]
@benediktg Thanks for the info. Of course I read that man page (first thing to do, right?), and I can confirm there wasn't a typo. It was that change that did the trick - I can't tell why. It also stopped working again when I reverted it back, so there had to be some kind of link. If it where the sideeffects of that command that made it working, or the command itself - I can't tell.

However, this has all been vanished since then, because I switched to the docker image. Pleasure to work with. :)

**Comment by Marko-M** [comment]
My 2c,
on Ubuntu 14.04 with packager.io Gogs both MySQL and Gogs are upstart services. So:

`/etc/init/gogs.conf`

and change:

```
start on runlevel [2345]
stop on runlevel [06]
```

into

```
start on started mysql
stop on runlevel [06]
```
else, Gogs will fail to start after server reboot.

**Comment by tassoevan** [comment]
Is it worth it to add a comment in `gogs.service` highlighting the `mysqld`/`mysql` mess? It's a not so obvious source of errors.

**Comment by m2nlight** [comment]
$vim /etc/systemd/system/gogs.service
Append `mysql.service` to `Alfter=` line.

**Comment by alierdogan7** [comment]
> $vim /etc/systemd/system/gogs.service
> Append `mysql.service` to `Alfter=` line.

Thanks,
In my case `gogs.service` file contains `mysqld.service` appended line starting with `After=` 
However, `mysqld.service` is not recognized on my  Ubuntu 18.04, so I appended `mysql.service` and problem solved.
