### ISSUE TITLE
Admin tool to initialize all repos from the db

### ISSUE THREAD

**Issue by loosebits** [gogits/gogs#2554]
When bringing up gogs on a new box (e.g. after a system failure of the current box), each repo in the database needs to be manually initialized (e.g. `git init --bare user/repo.git`) before users can repush all their code.

An admin tool to reinitialize all missing repos from the db would be handy.

**Comment by Unknwon** [comment]
Hi,

> When bringing up gogs on a new box (e.g. after a system failure of the current box), each repo in the database needs to be manually initialized (e.g. git init --bare user/repo.git) before users can repush all their code.

What kind of this situation is...? Where does Gogs know what repos should have?

**Comment by loosebits** [comment]
Sorry, here's the scenario..

Gogs DB is hosted on a different box from Gogs.  The Gogs box dies and we bring up a new Gogs instance on another box and point it to the existing DB.  To recover, we have to query the gogs tables to build a list of paths for the repos and init them all.  It would be nice if there was an admin tool to handle this much like the inverse of "Delete all repository records that lost Git files"

**Comment by Unknwon** [comment]
Thanks for the explanation!

But where are the old files..? Or you just want empty new repos?

**Comment by loosebits** [comment]
You mean where are the actual repos?  They are on the dev's machines, they just need to do a `git push origin *:*` to rebuild the gogs repos.  Ah, the beauty of git.

**Comment by Unknwon** [comment]
I see..........

OK.. not hard to implement, just the situation is true weird for me :trollface:

**Comment by galaktor** [comment]
Out of curiosity, in the reverse case where gogs dies and I want to re-add the git repos to a new install of gogs... will gogs automatically find and add the repos inside of its repo URL, or are additional steps needed to make it re-scan the file system, update DB or similar?

**Comment by Unknwon** [comment]
>  will gogs automatically find and add the repos inside of its repo URL, or are additional steps needed to make it re-scan the file system, update DB or similar?

No, you would need to make a scripts to call migrate APIs (as admin user) to migrate repos from a local path.

**Comment by Unknwon** [comment]
Just pushed a commit for this to `develop` branch.

**Comment by loosebits** [comment]
Wow, that was fast.

**Comment by Unknwon** [comment]
Close as implemented.
