### ISSUE TITLE
Image path break when it contains space

### ISSUE THREAD

**Issue by NiuXWolf** [gogits/gogs#2556]
like this ![redis](./pic/220px-Redis_Logo.svg.png)  in *.md file ,it can't show the picture in the web.

**Comment by Unknwon** [comment]
Picture is broken...

**Comment by NiuXWolf** [comment]
picture is not broken ,i think is the path not map to right path in server.

**Comment by Unknwon** [comment]
... Sorry I don't understand what is going on?

**Comment by NiuXWolf** [comment]
![capture](https://cloud.githubusercontent.com/assets/8829072/12837058/b54723b0-cbf9-11e5-8caa-e0baeade9367.PNG)

i insert a pic in the markdown file ,but the web do not show it .In the github.com,it works well.

**Comment by Unknwon** [comment]
So what is the raw markdown?

**Comment by NiuXWolf** [comment]
![capture](https://cloud.githubusercontent.com/assets/8829072/12837128/5d80f1c8-cbfa-11e5-9681-2ba68875b2e8.PNG)

**Comment by Unknwon** [comment]
Try replace `%20` when ` ` see if it work.

**Comment by NiuXWolf** [comment]
![capture](https://cloud.githubusercontent.com/assets/8829072/12837159/bec96c9e-cbfa-11e5-8039-3396dd885aeb.PNG)

the url not have blank

**Comment by Unknwon** [comment]
> What is your version of Gogs?
Can you reproduce on https://try.gogs.io/?

**Comment by NiuXWolf** [comment]
Application Version: 0.8.25.0129

http://52.76.244.92:3000/yang/Training/src/master/WEB%20101/Files/text.md
you can use my site

**Comment by Unknwon** [comment]
Thanks, I can reproduce now.

**Comment by Unknwon** [comment]
OK, I found the problem, it's because you have space in your path and Gogs does not handle it.

You can update to `develop` branch, or if you don't want, you can remove all spaces in your directory name for the moment.

Test: https://try.gogs.io/unknwon/issue-2556/src/master/WEB%20101/Files/text.md

**Comment by NiuXWolf** [comment]
Thank you

**Comment by Unknwon** [comment]
:beers:

**Comment by bobdog1986** [comment]
I meet same issue. After remove space in image file folder ,it works well.

**Comment by Unknwon** [comment]
@bobdog1986 I think you just need to read through the comments...
