### ISSUE TITLE
wiki: 500 errors on save after transfer

### ISSUE THREAD

**Issue by arnehormann** [gogits/gogs#2558]
We have problems when
* ownership of a repository is changed or
* a repository is renamed

Under these conditions, Wiki pages can no longer be saved; doing so always causes a 500 error.

We use Gogs 0.8.25.0129

Sidenote: Thanks for Gogs!

**Comment by Unknwon** [comment]
Hi, for now you can restart Gogs to solve this problem automatically. Or delete `path/to/gogs/data/tmp` manually.

**Comment by Unknwon** [comment]
Hi, please try out `develop` branch now!

Or on https://try.gogs.io

**Comment by Unknwon** [comment]
ping @arnehormann

**Comment by arnehormann** [comment]
@Unknwon I just tried on try.gogs.io, it still failed. Sorry...

Steps to reproduce:

1. create organisation
2. create project initialized with default files
3. add Wiki page (I called mine "Page")
4. transfer project to organisation
5. on organisation page, add new Wiki page ("Home")

-> 500 error on save

**Comment by dakira** [comment]
I can reproduce this with @arnehormann's steps.

**Comment by Unknwon** [comment]
This is is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2604 .

Please help test on `develop` branch or https://try.gogs.io/

**Comment by arnehormann** [comment]
@Unknwon following my steps again just now crashed try.gogs.io for me. Really crashed - I can't even reach the welcome page. Maybe you're deleting too much now?

**Comment by Unknwon** [comment]
@arnehormann no, I was just updating the Caddy web server... try again...

**Comment by arnehormann** [comment]
@Unknwon all fine, works as intended :+1:

**Comment by Unknwon** [comment]
:trollface: Thanks your confirmation!

**Comment by dakira** [comment]
Can confirm the fix in my own install, too.

**Comment by omniscient** [comment]
I am on Gogs 0.9.13.0319 and I still get:

 [...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage: UpdateLocalWiki: Pull: exit status 1 - fatal: 'c:\@git\xxxxxx\business.wiki.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin

2016/05/10 09:45:39 [D] Template: status/500

where xxxxxx is the old repo URL...

I have made the repo name change while on gogs 0.9.13.0319 if that helps...

**Comment by Unknwon** [comment]
@omniscient are you using Windows?

**Comment by omniscient** [comment]
Yes, Windows 2016 CTP4

**Comment by Unknwon** [comment]
@omniscient Go has some problem delete read-only files on Windows, if restart Gogs does not solve the problem, you would have to delete `path/to/gogs/data/tmp` directory manually for now.

The `master` branch should have merged new patch to solve this problem. cc/ @andreynering

**Comment by omniscient** [comment]
Restart didn't work but manually deleting the tmp dir worked super well! Thanks.
