### ISSUE TITLE
Repository panel jumps to the bottom

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#2560]
I don't how to reproduce it, but the repository panel sometimes jump to the bottom of the page. It usually happens or back normal when someone pushes something or open an issue, etc. So the feed in the left is probably causing this.

AFIK, it happen in all version. The pictures below were taken in 5d192c2ebf0703fa0e7a5af7adbcaaec0d3b7dc9

![1](https://cloud.githubusercontent.com/assets/7011819/12855856/ffe6e5b6-cc28-11e5-99d1-fb406af6cce2.png)

![2](https://cloud.githubusercontent.com/assets/7011819/12855858/042c8ed2-cc29-11e5-841c-3ab6ac5aba85.png)

**Comment by Unknwon** [comment]
What browser are you using?

**Comment by andreynering** [comment]
Chrome.

**Comment by Unknwon** [comment]
I'm not seeing this on Chrome Mac 48.0.2564.103 (64-bit) no matter how I resize the Window...

**Comment by Unknwon** [comment]
Not In Safari and Firefox as well.

Maybe check web console?

**Comment by andreynering** [comment]
> Maybe check web console?

Will do when have the time, but I think it might be someting with the CSS/HTML, not the JS.

> no matter how I resize the Window

I think it depends on the content of the feed. I may take a look in the CSS when have the time.

**Comment by Unknwon** [comment]
> I think it depends on the content of the feed. I may take a look in the CSS when have the time.

It's possible....

**Comment by andreynering** [comment]
@Unknwon Found the problem.

I investigated and found that the layout problem was caused by a unclosed `<a></a>` tag.

In a deeper look in the translation I found that some strings that should contains backtick `` ` `` actually had a single quote `'` in portuguese, which was causing the unclosed tag:

- English: https://github.com/gogits/gogs/blob/10fbb1aa2f641546c4fdaee6c6ef7111586bd4e3/conf/locale/locale_en-US.ini#L1033
- Portuguese: https://github.com/gogits/gogs/blob/10fbb1aa2f641546c4fdaee6c6ef7111586bd4e3/conf/locale/locale_pt-BR.ini#L1031

Changing and generating the bin data solved it. Will correct in Crowdin.

**Comment by Unknwon** [comment]
Thanks! I remember you have the permission to approve, right?

**Comment by andreynering** [comment]
Yes. Already changed and approved the changes.
