### ISSUE TITLE
DueDate field on creating/editing milestones modify date by -1 day

### ISSUE THREAD

**Issue by Alphanumerix** [gogits/gogs#2563]
Issue found on https://try.gogs.io (v0.8.31.0205).

On the right side of the screen we can see two fields. Shorter one have label "Due Date (optional)" and it allow us to set end date for given milestone. There is a problem with field on saving changes. After save date is modified by 1 day backward. 

This issue can be connected somehow with #2564

**Comment by Unknwon** [comment]
Thanks your feedback!

Does the server runs on the different timezone that you're located?

**Comment by Alphanumerix** [comment]
If viewdns.info is correct and http://try.gogs.io IP is 159.203.18.145 (located in Palatine, Illinois, USA), than yes. I'm testing it from Poland, Europe (my timezone is GMT+1).

**Comment by Unknwon** [comment]
OK... I might know the problem, which I've noticed... but no solution yet. :sweat:

**Comment by tkausl** [comment]
Found the problem, I'll open a PR for it.

**Comment by Unknwon** [comment]
@tkausl looking forward!

**Comment by tkausl** [comment]
Added pr #2563, however `regulateTimeZone` is just a bad hack to fix a bug in the orm-engine. We should either get the orm-owner to fix it or fork the orm and fix it ourselfs. See https://github.com/go-xorm/xorm/pull/226 (its a pr for mssql but mysql has the exact same problem)

**Comment by Unknwon** [comment]
@tkausl you're absolutely right.
