### ISSUE TITLE
500 error for PR creation after repo transfer to a team

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [gogits/gogs#2569]
The issue in the title was found on https://try.gogs.io while investigating a 500 error on a locally-hosted gogs server.

The local issue I have is similar to #1711 : I sent a PR to a team-owned repo. When a team member tried to merge, the result was a 500 page.

I went to try.gogs.io to see if I could replicate the local issue; I could not. However I found the issue stated in the title.

To reproduce on try.gogs.io:
1. Create two users A and B. Create a team TeamAB with A and B.
2. Make A create a repo and transfer repo to TeamAB.
3. Make B fork repo.
4. Make B try to open PR. **=> 500**

Notes:
* This only happens with team repos. If A transfers to C which B then forks from, B can still open PR's and have them accepted.
* This doesn't happen if you start by creating the repo with TeamAB as the owner.

But actually it gets weirder:
5. Make A fork TeamAB's repo.
6. Make A open PR **=> PR page will be generated but Gogs will say there are conflicts.**
7. Make B try to open **=> PR page will be generated but Gogs will say there are conflicts.**

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you post what error for 500 logged in Gogs server console?

**Comment by Unknwon** [comment]
And what is your version of Gogs?

**Comment by absolutelyNoWarranty** [comment]
Unfortunately I don't have access to the local Gogs right now (also I'm not the admin so I'll have to ask him about the server console logs.) Judging from what I remember about the UI I think it's an older version.

Also, I forgot to mention that on try.gogs.io if you create a PR *before* the repo transfer to a team, it can still be accepted after.

**Comment by Unknwon** [comment]
OK, you can test it ASAP and report back :smile:

**Comment by absolutelyNoWarranty** [comment]
OK but it'll be a while because CNY ... 
(Just to clarify, all the detailed info discussed in this Issue is for what I observed on try.gogs.io and not on the local Gogs.)

**Comment by misugijunz** [comment]
Hi, I've experience the same thing with similar scenario but I didn't transfer the repo to the team. The repo was created under the team. At first, my team member was able to make a pull request to this team repo but after restarting gogs (due to CNY, our servers went for regular maintenance), we can't do PR to our team repo from fork repository by a team member

**Comment by Unknwon** [comment]
Hmm... what is `CNY`?

> we can't do PR to our team repo from fork repository by a team member

@misugijunz what is your definition of `can't do PR`?

**Comment by misugijunz** [comment]
Chinese (Lunar) New Year. can't do PR means blocked by 500 (internal server error), I'll have my friend posted the error message, etc.

**Comment by misugijunz** [comment]
After removing tmp folder, we are able to solve the issue. I wonder why it is not deleted if it is blocking

**Comment by Unknwon** [comment]
@misugijunz Good info! What is your version of Gogs?

**Comment by billy93** [comment]
![error gogs](https://cloud.githubusercontent.com/assets/1745697/12938992/1c5cced2-cfed-11e5-8903-78389d092012.PNG)

This is the error message that is intended by @misugijunz

**Comment by billy93** [comment]
My current version is 0.8.25, is the fix already on 0.8.31?

**Comment by Unknwon** [comment]
Thanks @billy93 , will check it.

> My current version is 0.8.25, is the fix already on 0.8.31?

Maybe not, will keep you posted.

**Comment by Unknwon** [comment]
@billy93 Did you do any thing like rename a repo? Rename the org?

**Comment by misugijunz** [comment]
I asked him, he said no.

**Comment by Unknwon** [comment]
@misugijunz can you update to `develop` branch test again?

**Comment by absolutelyNoWarranty** [comment]
Hi, this morning we updated to 0.8.33.0210 which appears to have fixed our PR merge issues.

**Comment by Unknwon** [comment]
@absolutelyNoWarranty thanks!

It would be better to do some more testings... with lastest `develop` branch.

**Comment by Unknwon** [comment]
ping @absolutelyNoWarranty

**Comment by absolutelyNoWarranty** [comment]
I asked our guy in charge of the git server if moving to `develop` was possible but he is currently busy with other things. Sorry ... :/

**Comment by Unknwon** [comment]
:sweat:...

**Comment by Unknwon** [comment]
Close due to lack of feedback.
