### ISSUE TITLE
Profile shows organisations if you are an admin

### ISSUE THREAD

**Issue by jamierocks** [gogits/gogs#2571]
Profiles only show organisations that your are an owner of.
![img](https://i.lexteam.xyz/zlBmMKOCng.png)
The profile should really show all organisations that your are part of and have set public visibility.

**Comment by fnkr** [comment]
Is already fixed in develop branch.

See #2527.
Related: #2530, #2567.

**Comment by jamierocks** [comment]
Oh - my bad.

**Comment by fnkr** [comment]
@jamierocks Don't you want to close this issue? :-)

**Comment by Unknwon** [comment]
I think @jamierocks 's point is admin could view all organization no matter public or private membership?

**Comment by jamierocks** [comment]
My point was that the profile doesn't adhere to the visibility of that organisation ;)

**Comment by fnkr** [comment]
So #2527 did what you wanted to be done?

**Comment by jamierocks** [comment]
Yes.

**Comment by fnkr** [comment]
So, why don't you close this issue? :D

**Comment by jamierocks** [comment]
My bad - I thought it was closed after your original comment :P
