### ISSUE TITLE
Let collaborators & team members (with write permissions) update issues, wiki

### ISSUE THREAD

**Issue by fnkr** [gogits/gogs#2572]
Collaborators and team members with write permissions should be able to:

- edit issue labels
- edit issue milestone
- edit issue assignee
- write wiki

Current permission set:

Action | Collaborators | Team members (write) | Team members (admin)
--- | --- | --- | ---
edit issue labels | no | no | yes
edit issue milestone | no | no | yes
edit issue assignee | no | no | yes
write wiki | yes | no | yes
push code | yes | yes | yes

Proposal:

Action | Collaborators | Team members (write) | Team members (admin)
--- | --- | --- | ---
edit issue labels | yes | yes | yes
edit issue milestone | yes | yes | yes
edit issue assignee | yes | yes | yes
write wiki | yes | yes | yes
push code | yes | yes | yes

@Unknwon Do you agree?

**Comment by Unknwon** [comment]
Thanks for the details!

I think Collaborators should not be consider in an individual category. After https://github.com/gogits/gogs/issues/1146 , access rights are unified to `read`, `write`, and `admin`.

**Comment by fnkr** [comment]
That would be great. It seems like #1146 also contains giving edit issue labels/milestone/assignee permissions to people with `write` access.

---

Duplicate of #1146, closed.
