### ISSUE TITLE
Failed to get repository owner (user): no such table: user

### ISSUE THREAD

**Issue by openscript** [gogits/gogs#2574]
First of all, I like gogs very much! Thank you for your effort :+1: 

For the last hour I've been struggling with the following error:

```
/tmp ➜ git clone git@myhost.mydomain:robin/documents.git
Cloning into 'documents'...
Gogs: Internal error
Failed to get repository owner (robin): no such table: user
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

My `app.ini` looked like this (shortened):
```
...
[database]
DB_TYPE = sqlite3
PATH = data/gogs.db

[repository]
ROOT = /var/repositories
...
```

Gogs lives in `/opt/gogs` and the SQLite database was created in `/var/repositories/data/gogs.db`. Somehow when I try to clone a repo, gogs looks up the user in `/opt/gogs/data/gogs.db` instead of `/var/repositories/data/gogs.db`.

When I change `PATH = data/gogs.db` to `PATH = /var/repositories/data/gogs.db` (and restart gogs) it **works**.

Maybe it's not an issue, but I had to debug gogs to figure this out. Probably a hint about this should be added to the documentation?

**Comment by Unknwon** [comment]
@openscript Can you try to use absolute path for SQLite3 database?

**Comment by openscript** [comment]
@Unknwon Yes, I did that in the end and it worked!

**Comment by Unknwon** [comment]
Oh, great! https://gogs.io/docs/intro/troubleshooting#connect-to-wrong-sqlite3-database

**Comment by aoi-umi** [comment]
i  use absolute path ,but throw this while i pushing
```
Gogs: Internal error
Fail to get repository owner 'username': dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.
```
OS: windows
config
```
[database]
DB_TYPE  = sqlite3
; HOST     = 127.0.0.1:3306
; NAME     = gogs
; USER     = root
; PASSWD   = 
; SSL_MODE = disable
PATH     = d:/data/gogs/data/gogs.db
```

**Comment by unknwon** [comment]
@aoi-umi If you're running 0.13.0+dev, the config option has been changed to:

```diff
[database]
-DB_TYPE  = sqlite3
+TYPE = sqlite3
```

**Comment by aoi-umi** [comment]
> @aoi-umi If you're running 0.13.0+dev, the config option has been changed to:
> 
> ```diff
> [database]
> -DB_TYPE  = sqlite3
> +TYPE = sqlite3
> ```
my version is
>Gogs version 0.11.91.0811

**Comment by unknwon** [comment]
> > @aoi-umi If you're running 0.13.0+dev, the config option has been changed to:
> 
> > 
> 
> > ```diff
> 
> > [database]
> 
> > -DB_TYPE  = sqlite3
> 
> > +TYPE = sqlite3
> 
> > ```
> 
> my version is
> 
> >Gogs version 0.11.91.0811

In that case, based on the error, the config file you're editing seems not used by Gogs at all. Please check you've edited the correct app.ini.

**Comment by aoi-umi** [comment]
it work
>https://github.com/go-gitea/gitea/issues/10813
