### ISSUE TITLE
Disable HTTP cloning

### ISSUE THREAD

**Issue by garygreen** [gogits/gogs#2583]
Is it possible to disable the HTTP cloning method?

![gogsclone](https://cloud.githubusercontent.com/assets/1702638/12885139/68bb0296-ce5b-11e5-8116-67d085506f73.JPG)

**Comment by Unknwon** [comment]
Currently... no, but can be a feature request...

**Comment by Hospes** [comment]
If you add config flag to hide "http" button it would be an awesome!!!

**Comment by devotoare** [comment]
+1 Would love to see this

**Comment by 0xbaadf00d** [comment]
It must be globally disabled or onu for some repositories ?

**Comment by devotoare** [comment]
Personally I would like to disable is globally as I use it in an intranet where I am not wanting users to have the choice to work without SSH.

**Comment by 0xbaadf00d** [comment]
OK, I could propose a PR within one or two days.

**Comment by devotoare** [comment]
That would be amazing, thank you

**Comment by estan** [comment]
Would love to see this feature as well. We also have an internal network and don't use HTTP(S) at all, only SSH. Any chance that PR could be merged before the next release?

**Comment by obuiron** [comment]
+1
[PR#3367](https://github.com/gogits/gogs/pull/3667) seem approved and CI passed any idea when this PR will be merged ?

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/pull/3667.
