### ISSUE TITLE
Git push --force is painfully slow for larger repositories

### ISSUE THREAD

**Issue by nanoant** [gogits/gogs#2586]
It happens sometimes that you want quickly amend some commit that is already pushed to remote server and you do `git commit --amend` then `git push --force` to overwrite remote HEAD. This is not a big deal, but Gogs stalls for at least 5-10 seconds when the repository you are trying is larger project.

This problem can be quickly reproduced:
1. forking Gogs
2. cloning the fork
3. doing `git commit -C HEAD --amend`
4. going `git push --force` (Gogs will stall now for 5-10 seconds)

I did some little investigation and the problem lies in `models.Update` calling `newCommit.CommitsBeforeUntil(oldCommitID)`. The `CommitsBeforeUntil` is pretty suboptimal in this case, because it parses ALL commits (which may be tens of thousands) to find out that `oldCommitID` is not ancestor of `newCommit`, because it isn't!

Therefore `CommitsBeforeUntil` should use `git rev-list oldCommitID..newCommitID` to quickly get the matching commits, instead walking each commit one by one.

**Comment by Unknwon** [comment]
`git rev-list` is not supported before 1.8 so only newer git client could fix the problem with new patch.
