### ISSUE TITLE
Protected branches: git push --force/--delete should be available only to administrators

### ISSUE THREAD

**Issue by nanoant** [gogits/gogs#2587]
Right now Gogs allows `git push --force/--delete` to anyone having write permissions. This is pretty dangerous, and potentially security hole, because some "evil" developer, eg. dude that is getting fired from the company, can reset whole Git history pushing forcefully some stupid stuff or deleting some important branches.

Therefore Gogs should introduce idea of "protected branch" list repository setting that can be only deleted or forcefully pushed only by administrator. This should basically work the same as in GitHub or GitLab. I also propose to make "master" by default a protected branch when creating new repo.

WDYT?

**Comment by Unknwon** [comment]
Thanks, maybe you should follow on https://github.com/gogits/gogs/issues/776?

**Comment by nanoant** [comment]
@Unknwon I think #776 mixes two concepts/ideas in one single issue (may be bad for Gogs project management). Code review is good idea, but it is somehow complicated, not well defined and "big" feature. This issue here is more simple and about security, and has nothing to do with #776 code review functionality.

I think the security concern about NOT letting to `--force/--delete` to anyone but administrators is really important, otherwise Gogs may be no go for enterprise.

I think I can try to implement that, but next week earliest. IMHO the implementation should include following atomic steps (commits):

### Preparation
1. Gogs adds own `pre-recive` hooks, all existing `pre-recive` hooks should be renamed to `pre-receive-local`. Editing `pre-receive` hook should effectively edit `pre-receive-local`. The Gogs own `pre-revice` hook should simply check for existence of `pre-recive-local` and fire it, so administrators are able to customize/extend `pre-receive` hook.
2. (optional) We may do the same with `update` hook, currently in-editable. Introduce `update-local` fired if present by Gogs managed `update`.

### Actual implementation
2. Introduce internal API that return true if the given user is allowed to push/delete given ref. We may start by assumption that `master` is protected and required administrator and anything else is no protected.
3. In `pre-receive` hook we check if the pushed stuff deletes or forcefully updates some ref, we ask Gogs via new API is it is allowed. If not, we return error in the hook.

Next having this basic implementation we may start implementing protected branch list and extending the API to actually check if ref belong to protected list rather than simply checking if it is `master`.

**Comment by Unknwon** [comment]
In my point of view, disable `--force/--delete` is part of the protected branch feature, so I still think you should follow #776.

**Comment by Unknwon** [comment]
ping @nanoant

**Comment by nanoant** [comment]
Okay, closing this one in favor of #776.

**Comment by Unknwon** [comment]
:smiley:
