### ISSUE TITLE
Path to repository forked must be org(or org)/nameOfRepository

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2588]
I have a alias configured in Apache2 that is `mydomain.com/gogs/` and when I fork a repository take `/gogs/` to complete the path to repository that I have forked when this must take `user/nameRepository` only... but in previous version of Gogs doesn't happen. For example:
- My repository forked of `DAW(org)/Ejercicios`
![image](https://cloud.githubusercontent.com/assets/7110786/12900082/c63c9840-ceb4-11e5-97c6-9c4438553be2.png)
- The original repository from I have forked (DAW)
![image](https://cloud.githubusercontent.com/assets/7110786/12900106/e578966e-ceb4-11e5-8f1f-9dae39e86c97.png)

- A image of URL
![image](https://cloud.githubusercontent.com/assets/7110786/12900261/bf4e0ca2-ceb5-11e5-8f31-091785be5601.png)

- version of Gogs:  0.8.25.0129

I'm sorry for my english... and saludos! :+1:

**Comment by Unknwon** [comment]
Thanks your feedback!

> when I fork a repository take /gogs/ to complete the path to repository that I have forked when this must take user/nameRepository only

I don't understand this part?

**Comment by xxxtonixxx** [comment]
yeah, sorry... Hmmm, I forked any repository of any org (e.g `gogits/gogs`), its URL would be (using subpath) `try.gogs.io/subpath1/gogits/gogs`, then I have created a fork of gogits/gogs, no subpath1/gogits/gogs how you can see in the first image... better? :sweat_smile: 

- This image

![image](https://cloud.githubusercontent.com/assets/7110786/12902075/2d10319e-cebf-11e5-9b96-35c95b60d7eb.png)

**Comment by Unknwon** [comment]
I see, thanks. So you mean only the UI is incorrect, others work fine?

**Comment by xxxtonixxx** [comment]
Yes!! :+1:

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2757.

**Comment by xxxtonixxx** [comment]
@Unknwon Ok, I can say that it's okay! And this issue can be closed :+1:

![image](https://cloud.githubusercontent.com/assets/7110786/13551745/e359890c-e344-11e5-8673-c1a1e8be0af9.png)

**Comment by Unknwon** [comment]
Thanks your confirmation!
