### ISSUE TITLE
Dashboard cannot show tag names contain '/' correctly

### ISSUE THREAD

**Issue by loosebits** [gogits/gogs#2589]
Tag names with a `/` in them only show the text after the `/` in both the name and the URL (giving 404s) in the Dashboard.

Our CI build process pushes tags like `build/123` and the dashboard shows it as `123`.  The tag shows correctly in other places and navigating to `/user/repo/src/build/123` works as well.

Gogs version:  0.8.10.1217
Git version: 2.0 
OS: OS X (10.11)

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2603

Can you help test on `develop` or https://try.gogs.io/?

**Comment by loosebits** [comment]
Looks good.
