### ISSUE TITLE
Malformed SSH authorized_keys file

### ISSUE THREAD

**Issue by keuv-grvl** [gogits/gogs#2590]
Hi! I successfully ran Gogs v0.8.25 (`/home/git/gogs/gogs web`) with SQLite on Ubuntu 15.10 (x86_64) as user `git` but I have an issue cloning repos via SSH.

Linux user `kgravouil` have its own SSH key (generated using `ssh-keygen`). Uploading the public key to Gogs *via* `http://localhost:3000/user/settings/ssh` just works fine. But cloning an existing repo (created within Gogs) using `git clone git@localhost:gogs-repositories/kgravouil/test-repo.git` fails:
```
Clonage dans 'test-repo'...
Gogs: Internal error
Failed to get repository owner (kgravouil): no such table: user
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The table `public_keys` in the SQLite database `data/gogs.db` seems to be populated correctly. But `/home/git/.ssh/authorized_keys` contains:
```
command="/home/git/gogs/gogs serv key-1 --config='/home/git/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa <my SSH public key>
```

If user `kgravouil` runs `copy-ssh-id git@localhost` then try to `git clone git@localhost:gogs-repositories/kgravouil/test-repo.git`, it will work finally.

I guess adding the SSH public key to `/home/git/.ssh/authorized_keys` fails at some point, but I could not figure out why.

Please also note that the `git clone` relative path is not the one proposed by Gogs after a repo creation, just like #170.

Thanks

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is exact duplicated of https://github.com/gogits/gogs/issues/2574
