### ISSUE TITLE
Fail to initialize ORM engine: Can't create/write to file 

### ISSUE THREAD

**Issue by floffel03** [gogits/gogs#2591]
Hi! I'm using a MySQL Database for gogs. 
Everything was running perfect, until one day i tried to push and the push wasn't successfull. 
The error was simple - too simple: no space left on the hdd. So I cleand everything up & tried to restarded gogs (the webinterface throwed some 500 Errors and some endless redirections)..

But gogs won't restart anymore: 
`Feb 10 00:33:14 blubb.minnecker.com systemd[1]: Unit gogs.service entered failed state.
Feb 10 00:33:14 blubb.minnecker.com systemd[1]: gogs.service failed.
Feb 10 00:33:14 blubb.minnecker.com systemd[1]: gogs.service holdoff time over, scheduling restart.
Feb 10 00:33:14 blubb.minnecker.com systemd[1]: start request repeated too quickly for gogs.service
Feb 10 00:33:14 blubb.minnecker.com systemd[1]: Failed to start Gogs (Go Git Service).
Feb 10 00:33:14 blubb.minnecker.com systemd[1]: Unit gogs.service entered failed state.
Feb 10 00:33:14 blubb.minnecker.com systemd[1]: gogs.service failed.`

In the corresponding log file, gogs throws following error:
`2016/02/10 00:33:14 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1: Can't create/write to file '/tmp/#sql_94a_0.MAI' (Errcode: 2)`

(yes, i deleted a lot of the /tmp/ directory, mby I deleted this file too.. And `touch /tmp/#sql_94a_0.MAI` dosn't help :-1: )
I can't find anything according to this issue (mby becourse I'm the only idiot arround here) but anyway, I think some error handling for 'no space left on device' would be cool for gogs too :)
I would really appreciate help on this issue.. :)

**Comment by Unknwon** [comment]
Sorry about your situation, but this error is directly throwing from MySQL and Gogs can't help with it at all.

Maybe help: http://dev.mysql.com/doc/refman/5.7/en/cannot-create.html

**Comment by Unknwon** [comment]
ping @floffel03

**Comment by Unknwon** [comment]
Close due to lack of feedback.
