### ISSUE TITLE
Allow request header to set HTML rendered in raw mode

### ISSUE THREAD

**Issue by pykiss** [gogits/gogs#2593]
It would be nice, if we can configure gogs some way, to allow get HTML files rendered in raw mode.

Maybe other people need configure it diferently for each repository (or even folder...), but for my case use, It would be enough  to configure it globally to all repos in the gogs configuration files for instance.

**Comment by iar-wain** [comment]
Hi!

I'm looking forward to this option as well.
I have external documents containing links to HTML pages stored on gogs, however since #2283 their source is now displayed instead of their content. I haven't found a workaround to get their content rendered instead.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Unknwon** [comment]
Raw: https://try.gogs.io/xxxtonixxx/bug_html_rendering_raw_mode/raw/master/toni/LenMar/HTML/index.html
Render: https://try.gogs.io/xxxtonixxx/bug_html_rendering_raw_mode/raw/master/toni/LenMar/HTML/index.html?render=1
