### ISSUE TITLE
500 Server error when PR with a patch to a file that is removed is created

### ISSUE THREAD

**Issue by congeal** [gogits/gogs#2595]
This issue has been fixed, but I posted this to another issue(#2490) that is not the same as this.
For the record, I submit a new issue about this.

> Dogs showed 500 server error when I created a pull request, but I got a different message:
> 
> router/repo/pull.go:633
> CompareAndPullRequestPost()
> [E] NewPullRequest: testPatch: git apply --check: exit status 1 - error: <filename>: ?? ????

> I think you can reproduce this problem:
> 1) 'git rm' a file from a repsoitory (upstream)
> 2) modify the removed file in a forked repository
> 3) create PR
> You should be able to see 500 server error.

**Comment by congeal** [comment]
@Unknwon, thanks a lot

**Comment by Unknwon** [comment]
:sweat_smile:

**Comment by eqbala** [comment]
did this work
