### ISSUE TITLE
500 error in releases after deleting an user

### ISSUE THREAD

**Issue by hexadecy** [gogits/gogs#2596]
2016/02/10 11:27:09 [...ters/repo/release.go:50 Releases()] [E] GetUserById: user does not exist [uid: 2, name: ]

I finally recreated the user and updated the uid in the database.

**Comment by Unknwon** [comment]
Thanks your feedback!

What is your version of Gogs?

**Comment by mhartkorn** [comment]
The corresponding code is in the `master` branch in `/routers/repo/release.go` line 46 and 106 (both the same code):

	rel.Publisher, err = models.GetUserByID(rel.PublisherID)
	if err != nil {
		ctx.Handle(500, "GetUserByID", err)
		return
	}

It should use a placeholder in the template if the user got deleted instead of fail with HTTP 500. I can prepare a PR within a few hours. If nobody else wants to take it.

**Comment by Unknwon** [comment]
Thanks @mhartkorn !

You can call [this function](https://github.com/gogits/gogs/blob/master/models%2Fuser.go#L465) in the `/routers/repo/release.go` if the error is https://github.com/gogits/gogs/blob/master/models%2Ferror.go#L62

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging #2599

**Comment by Unknwon** [comment]
Close as fixed.
