### ISSUE TITLE
Marketing Gogs To Audiences

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2600]
This isn't an issue with the code as such, but as Gogs is an absolutely awesome lightweight git repo manager, I wanted to raise some discussion about how to get the word out and who to advertise to.

Here are a few thoughts, and if you can, feel free to chime in!

## Audiences (the not so obvious)
- Raspberry Pi / Hard Kernal users
- Small entrpreneural teams working on a low-budget kick-starter-type projects
- mobile app / mobile games dev teams
- single web developers (they probably don't realise the advantages of git as they may  not have techical background)
- authors?

## Reaching Out
- There are lots of magazines for these audiences so, maybe an email / article on how to set up gogs on that particular platform would see it published / incorporated into a bigger article. 
- Particular specialise websites that may hit the above audiences
- blog posts for search engine traffic for these users

Please help add to this list, and I shall update this original post to list them all in one place

**Comment by Unknwon** [comment]
Thanks your suggestions, but what is the motivation behind this?

**Comment by ChangePlaces** [comment]
@Unknwon The motivation is simply to get even more people using gogs!

**Comment by Unknwon** [comment]
Thanks, but I think people (like you) spread the words to your friends who need a self-hosted Git service to use Gogs is very good enough. :100:

I personally do not like word **marketing** for the open source project because I'm not doing business but making something cool.

**Comment by allustin** [comment]
@ChangePlaces simply add to you site something like this

![](https://try.gogs.io/img/favicon.png)
**[Gogs is Awesome !!!](https://github.com/gogits/gogs)**

in the open source projects i think maintainer need a collaborators, who make a pull request to a projects

![image](https://cloud.githubusercontent.com/assets/55323/12969502/6d25889a-d092-11e5-9122-e24014d89dcf.png)

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
