### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by steffansk1997** [gogits/gogs#2601]
When I submit git requests through https I get this error: SSL certificate problem: unable to get local issuer certificate

The certificate is a wildcard signed by comodo, Should I include the ca somewhere?
[server]
DOMAIN = git.skblue.com
HTTP_PORT = 3000
PROTOCOL = https
ROOT_URL = https://git.skblue.com/
CERT_FILE = custom/STAR_skblue_com.crt
KEY_FILE = custom/skblue.com.key
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false

apache config:

	ServerName git.skblue.com
	ServerAlias git	
	SSLEngine on
	SSLCertificateFile /ssl/skblue.com/STAR_skblue_com.crt
	SSLCertificateKeyFile /ssl/skblue.com/skblue.com.key
	SSLCertificateChainFile /ssl/skblue.com/COMODORSAAddTrustCA.crt
	ProxyRequests     Off
	ProxyVia On
	ProxyPreserveHost On
	AllowEncodedSlashes NoDecode
	<Proxy *>
		Order deny,allow
		Allow from all
	</Proxy>
	ProxyPass         /  http://localhost:3000/ nocanon
	ProxyPassReverse  /  http://localhost:3000/

**Comment by Unknwon** [comment]
Hi, looks like you setup the HTTPS but still tell Apache to talk through HTTP to Gogs.

Please read [this article](https://unknwon.io/setup-gogs-with-https/) which may help you solve the problem.

**Comment by steffansk1997** [comment]
So I updated the gogs config to work as http and the apache to work as reverseproxy, but it still thows the unable to get local issuer error

[server]
DOMAIN = git.skblue.com
HTTP_PORT = 3000
ROOT_URL = https://git.skblue.com/
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false

        ServerName git.skblue.com
        ServerAlias git	
		SSLEngine on
		SSLProxyEngine On
		SSLCertificateFile /ssl/skblue.com/STAR_skblue_com.crt
		SSLCertificateKeyFile /ssl/skblue.com/skblue.com.key
		SSLCertificateChainFile /ssl/skblue.com/COMODORSAAddTrustCA.crt
		ErrorLog /var/www/html/logs/skblue.com/error.log
		CustomLog /var/www/html/logs/skblue.com/requests.log combined
		
		ProxyRequests     Off
		ProxyPreserveHost On
		
		<Proxy *>
                 Order allow,deny
                 Allow from all
        </Proxy>

        ProxyPass / http://localhost:3000/
        ProxyPassReverse / http://localhost:3000/

**Comment by Unknwon** [comment]
Did a google search: http://stackoverflow.com/questions/24372942/ssl-error-unable-to-get-local-issuer-certificate

**Comment by steffansk1997** [comment]
Fixed the problem with a new startssl cert, it's working fine now

**Comment by Unknwon** [comment]
:joy: Let's encrypt is cool, too!

**Comment by CodeSurfing145** [comment]
@Unknwon Let's Encrypt is what I am using but I can't seem to get it working =/
I got 3 files
```
ca_bundle.crt
certificate.crt
private.key
```
And I got this in my config

```
[server]
DOMAIN = HIDDEN
PROTOCOL = https
HTTP_PORT = 8080
ROOT_URL = https://HIDDEN/
DISABLE_SSH = false
CERT_FILE = /SSL-Certs/certificate.crt
KEY_FILE = /SSL-Certs/private.key
SSH_PORT = 22
OFFLINE_MODE = false
```

And whenever I try cloning i get this

```
Cloning into 'CashRegister'...
fatal: unable to access 'https://HIDDEN/kodserfing145/CashRegister.git/': SSL certificate problem: unable to get local issuer certificate
```

**Comment by CodeSurfing145** [comment]
Okay, I fixed it 👍 
For anyone else from Google coming on this issue...

Make sure to add
`SSLCertificateChainFile /SSL_Certs/ca_bundle.crt`
To your apache2 virtual host else it won't work and will result in this error.

**Comment by seal61** [comment]
> Okay, I fixed it 👍
> For anyone else from Google coming on this issue...
> 
> Make sure to add
> `SSLCertificateChainFile /SSL_Certs/ca_bundle.crt`
> To your apache2 virtual host else it won't work and will result in this error.

for gogs 0.11.86.0130 I came to a similar problem under webserver nginx; I didn't use the whole certificate chain, so pull and push didn't work correctly. I re-exported the certificate with the whole chain again and included it with ssl_certificate in nginx, then it worked. 

thanks for your hint.
