### ISSUE TITLE
Add ability to alter an existing repository from "mirroring" to "normal" behavior

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#2607]
IMHO it would be nice if one could create a repository mirror and decide later, if that this repository should be standalone from now on. I guess that could be handy to have if one is doing preparations for moving towards gogs. It would be possible to keep the repositories in sync, till everything is in place.

**Comment by Unknwon** [comment]
This feature is claimed to be implemented by merging #2624

**Comment by hhenkel** [comment]
I will give it a try tomorrow when I'm back to work.

**Comment by Unknwon** [comment]
ping @hhenkel

**Comment by hhenkel** [comment]
Sorry for the delay, just started testing - so far it looks good to me. Will do some more testing and provide more feedback.

**Comment by hhenkel** [comment]
@mhartkorn thanks for implementing - this works for me. 

@Unknwon closing as resolved.

**Comment by Unknwon** [comment]
Thanks your confirmation!
