### ISSUE TITLE
Using SSH as well (or: not having to specify the alternative port)

### ISSUE THREAD

**Issue by djcf** [gogits/gogs#2608]
Hi there,

First off, truly excellent piece of software. Gogs is one of my favourite projects on github.

Like most people I run GOGS on a remote server for which I also access using SSH. If I set Gogs to run on port 22, I'd like to have it so that admins can ssh into the server without having to specify the port, or conversely, if Gogs is running on some alternative port e.g. port 2222, I'd like devs to be able to push and pull code without having to undergo any kind of special configuration. If I understand the concept correctly, gogs (like github and bitbucket) uses the special "git" user over ssh so surely this must be possible? Some kind of proxy which forwards SSH requests for the git user to Gogs, and SSH requests for all other users to the SSH server?

(My setup is actually not that simple: users access Gogs from an Nginx proxy on the subdomain labs., but the actual Gogs instance runs on a different server named ethel., which also uses SSH. So to push and pull code devs currently have to specify to push and pull from ethel. on port 2222. I would like them just to be able to push and pull to labs. on the normal port without special client configuration.)

I would have thought this was not an unusual request -- presumably organisations like Github and Bitbucket don't rely on their admins using a special port for ssh!

Thanks in advance,

Daniel

* Question also posted here: http://unix.stackexchange.com/questions/260564/forward-ssh-for-git-user-to-git-server

**Comment by Unknwon** [comment]
Hi @djcf , thanks for the great details!

I think you have something misunderstandings here. (or maybe I understand wrongly)

1. How HTTP proxy is configed has no effect to how SSH should be configed.
2. If you're running Gogs under user `ethel`, then I supposed you have configed Gogs the `RUN_USER` to be `ethel` otherwise you can't even start Gogs. Then, you should just copy the SSH clone URL Gogs presents on the Web UI. Should be something like `ethel@git.youdomain.com/user/repo.git`.
3. The way SSH works with Gogs is just like any other software, user connects to it and SSH daemon executes some commands.

**Comment by djcf** [comment]
Yasss... :-)

I'm sorry. ethel. is the name of the server, i.e. ethel.domain.com. I of course realise entirely that the way the HTTP proxy works is entirely unrelated to the way SSH works. I am asking because there are two solutions that I can see:

- Configure the SSH daemon on labs.domain.com in a way I do not know how to forward SSH requests to ethel.domain.com when they are for the git user.

- Configure an SSH proxy to forward requests to ethel.domain.com when they are for the git user --  in a way similar to how the nginx proxy forwards HTTP requests to ethel.domain.com when they are for the labs.domain.com virtual host. 

Please ignore the fact that I have two different machines here -- the principal and the solutions would be the same if they run on the same machine, I would think.

Thank you for your time,

Daniel

**Comment by Unknwon** [comment]
If you're running Gogs in a separate user, what is the matter of using port 22?

**Comment by djcf** [comment]
Well the thing is I would like administrators (e.g. daniel@domain.com, tom@domain.com, etc.) to be able to SSH into the machine named labs.domain.com on port 22, and also for developers to be able to connect to the labs.domain.com repositories without having to configure their SSH client to use a different port.

Maybe I am not understanding something here. I thought GOGs uses a separate custom SSH server, which has to run on some other port, like port 2222, if port 22 is already taken.

**Comment by Unknwon** [comment]
If you run Gogs and use SSH, users are **not** be able to login and use shell anymore.

**Comment by djcf** [comment]
I see. And there is no way round this?

**Comment by Unknwon** [comment]
@djcf No...


But if you must run under same user with different port, you can enable builtin SSH server: https://github.com/gogits/gogs/blob/master/conf/app.ini#L65

**Comment by djcf** [comment]
I'm sorry, I do not understand the part of your answer about the same linux user.

For example, we have one administration, daniel@example.com, and we have one SSH server running at example.com on port 22, and we have GOGs installed in example.com. The Gogs SSH server listens for git push and pull etc. on port 2222. The GOGS service runs under the "gogs" user.

**Comment by Unknwon** [comment]
> Normally in this scenario my developer must type
>$ git clone -p 2222 git@example.com:/developer/my-repository

Please see http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/

**Comment by Unknwon** [comment]
ping @djcf

**Comment by djcf** [comment]
Thank you, yes I was trying to avoid using ssh config files because my developers are not necessarily sys admins and probably don't want the hassle of setting up an ssh config file on every new machine and server they use. I had assumed this might be a common request especially given that other organisations (presumably github and bitbucket for example) presumably have a work around....

Perhaps in the future it might be possible to bundle an ssh server which forwards non-gogs git users to a different port?

**Comment by djcf** [comment]
May I clarify one thing briefly?

When connecting to the gogs server via ssh for code pulls, pushes and clones do all users do so using the git@ user?

**Comment by Unknwon** [comment]
> Thank you, yes I was trying to avoid using ssh config files because my developers are not necessarily sys admins and probably don't want the hassle of setting up an ssh config file on every new machine and server they use. I had assumed this might be a common request especially given that other organisations (presumably github and bitbucket for example) presumably have a work around....

They do not give you shell access, only git commands.

> Perhaps in the future it might be possible to bundle an ssh server which forwards non-gogs/git ssh system users to a different port?

Possible, but not by Gogs.

> When connecting to the gogs server via ssh for code pulls, pushes and clones do all users do so using an account named git@ ?

I don't understand your question very well. `xx` in `xx@` mean which user SSH connects to.

I'm going to close this issue since it is a configuration and conceptual problem.

**Comment by djcf** [comment]
Right, so I came back to this after some time with a clarification for the use-case. Basically, it would be great if we could create system users which use a restricted login shell, where the login shell only accepts commands passed by the git client. That way we could login as $my-gogs-user using SSH on the normal port. SSH would start the gogits login shell, and the user would notice anything different from connecting to say github. Later, the same user could connect to the same host on the same port as $my-system-user and get a bash shell instead.

Gitlab has just this mechanism. Described here: https://gitlab.com/gitlab-org/gitlab-shell

**Comment by Unknwon** [comment]
Thanks for the details, but I have hard time understand what it means exactly in order to make valuable responses.

**Comment by Stuey2** [comment]
Firstly I'd also like to say well done on Gogs, it's great.

@djcf I agree, it would be nice to use port 22 for both git and ssh admin on your box. It's possible as outlined in this blog: [gogs share port 22](http://www.ateijelo.com/blog/2016/07/09/share-port-22-between-docker-gogs-ssh-and-local-system). Unfortunately that's too much scripting from my point of view. I can't justify automating the whole process, including the backup / restore, etc. 

I don't think it's easy for Gogs or Docker to provide a solution, as it's outside their remit. You need to somehow proxy SSH requests for a non-existent user to a Docker container. Perhaps there's a way to configure OpenSSH locally to do so. I'm sticking with a different port.

**Comment by Furgas** [comment]
I also wanted to:
* use system SSH and port 22
* disallow shell access through SSH

I thought that setting `git-shell` as `git` user's shell would do the trick but of course it did not:
```
fatal: unrecognized command '/opt/gogs/gogs serv key-2 --config='/opt/gogs/custom/conf/app.ini''
```

So, unless there will be some special `gog-shell` that I can use instead of `git-shell` I will have to live with using another port for Gogs (and maybe use [aliasing](https://unix.stackexchange.com/a/260579)).

**Comment by Furgas** [comment]
Oh, never mind. It seems that in my scenario Gogs prohibits shell access:
```
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
```

Hooray!
