### ISSUE TITLE
Add some information about workload in documentation

### ISSUE THREAD

**Issue by baby-gnu** [gogits/gogs#2610]
Hello,

I try to review several Git hosting services and I wonder how many users/repository Gogs can handle correctly.

The documentation introduction speak about **self-hosted** Git service but how big can it be?

Regards.

**Comment by tkausl** [comment]
This depends on many factors, how big the repositories are, how good the server is, harddrive, the database-system, and so on. It can probably handle thousands of repositories if they are not all accessed at the same time but it might slow down if hundred users are browsing a repository like the linux-kernel, but this all depends.

**Comment by Unknwon** [comment]
As @tkausl mentioned, and there is no answer even with given hardware requirement, mostly relates to user activities, repo size, etc.

This is the simple stats of demo site, but rarely user activities is performing, $5 DO VPS could handle them all.

![image](https://cloud.githubusercontent.com/assets/2946214/13018659/c9cc11ac-d198-11e5-8e42-d5bc45ffcbe0.png)

**Comment by Unknwon** [comment]
ping @baby-gnu

**Comment by baby-gnu** [comment]
Thanks.

We thought about switching our Redmine + [Redmine Backlog](https://github.com/backlogs/redmine_backlogs) to Gogs + [kanboard](http://kanboard.net/plugin/gogs-webhook) but it does not fit our requirements:

1. Synchronize tasks between Gogs and kanboard (kanboard/plugin-gogs-webhook#1)
2. Creating project hierarchies sharing the same taskboard.

Now, we keep redmine for our internal work and think about opening a Gogs for contributions / side projects.

Regards.

**Comment by Unknwon** [comment]
Thanks your info!

However you did not answer the question at all, how many people and how often for a push.

**Comment by baby-gnu** [comment]
Our internal needs are quite low:

* around 300 repositories, 10GB
* around 30 people
* around 1500 push per day, max 300.

I have no idea for the future contrib repositores, we have 3415 users in our Redmine LDAP and I don't know how many will play the game.

Regards.

**Comment by Unknwon** [comment]
Thanks, if you're going to use HTTP, maybe no luck, but SSH I think it would be OK although I can't be sure.

**Comment by Unknwon** [comment]
You can continue the discussion on https://discuss.gogs.io/ since it's a question.
