### ISSUE TITLE
Ubuntu 14:04 Cannot select SQLite

### ISSUE THREAD

**Issue by louwers** [gogits/gogs#2613]
This shows on the /install page:

![screenshot_2016-02-12_18-49-37](https://cloud.githubusercontent.com/assets/649392/13015451/64a4706e-d1b9-11e5-9855-d6a15566fdb0.png)

The settings show up in the HTML source though:
```html
<div id="sqlite_settings" class="hide">
    <div class="inline required field ">
        <label for="db_path">Path</label>
        <input id="db_path" name="db_path" value="/home/git/gogs.db">
        <span class="help">The file path of SQLite3 or TiDB database. <br>Please use absolute path when you start as service.</span>
     </div>
</div>
```

**Comment by tkausl** [comment]
If you compiled gogs yourself from sourcecode read the Documentation at https://gogs.io/docs/installation/install_from_source
The **Build with Tags**-Section handles sqlite

**Comment by louwers** [comment]
RTFM! Thanks!
