### ISSUE TITLE
Cannot recognize MySQL password correctly when contains ';'

### ISSUE THREAD

**Issue by IaBurton** [gogits/gogs#2615]
Hello,

I seem to be running into an issue when trying to upgrade from Gogs version 0.7.22 to any newer version (I've tried 0.7.33, 0.8 and 0.8.25). The machine is a Centos 6 box with MySQL 5.1.69 and Git version 1.8.3.1

```
2016/02/12 15:28:09 [T] Custom path: /asc/array1/gogs/gogs/custom
2016/02/12 15:28:09 [T] Log path: /asc/array1/gogs/gogs/log
2016/02/12 15:28:09 [I] Gogs: Go Git Service 0.8.25.0129
2016/02/12 15:28:09 [I] Log Mode: File(Info)
2016/02/12 15:28:09 [I] Cache Service Enabled
2016/02/12 15:28:09 [I] Session Service Enabled
2016/02/12 15:28:09 [I] Git Version: 1.8.3.1
2016/02/12 15:28:09 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
```

The mysql password hasn't changed (and I can log into mysql with the password fine), but everytime I try to upgrade I get this access denied error. When reverting back to 0.7.22 (without changing anything in the app.ini) it works fine. Could something have changed between 0.7.22 and above for gogs or xorm that could be causing this?

I took a look at issue #385 about old mysql passwords, and while our password didn't match that case I wen't ahead with the solution anyways and it didn't fix it.

I also noticed this on the Troubleshooting page in the comments, not sure if its related, but there was no answer 
![gogs](https://cloud.githubusercontent.com/assets/4121211/13023718/593c3324-d1a0-11e5-9604-9a8505b0ae79.png)

Unfortunately when I enabled general logging for our mysql server I still couldn't see any issue. Finally I decided to ditch mysql for sqlite (should have done this to begin with) using some tools to dump the mysql database into a sqlite3 one and point gogs at that instead

```
[database]
;DB_TYPE = mysql
;HOST = 127.0.0.1:3306
;NAME = gogs
;USER = root
;PASSWD = **********
;SSL_MODE = disable
DB_TYPE = sqlite3
PATH = data/gogs.db
```

but when I do that I get this

`2016/02/12 13:04:16 [T] Custom path: /asc/array1/gogs/gogs/custom
2016/02/12 13:04:16 [T] Log path: /asc/array1/gogs/gogs/log
2016/02/12 13:04:16 [I] Gogs: Go Git Service 0.8.25.0129
2016/02/12 13:04:16 [I] Log Mode: File(Info)
2016/02/12 13:04:16 [I] Cache Service Enabled
2016/02/12 13:04:16 [I] Session Service Enabled
2016/02/12 13:04:16 [I] Git Version: 1.8.3.1
2016/02/12 13:04:16 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: duplicate column name: id`

Anyways, hope we can figure this out, Gogs has been awesome so far and while I don't care so much about mysql vs sqlite3, it is important I can upgrade without losing my data :smile: thank you

**Comment by Unknwon** [comment]
Thanks your feedback!

But the requirement for MySQl is 5.5.3... https://gogs.io/docs/installation

**Comment by IaBurton** [comment]
Ha, I tried looking around for as much info as possible before creating the issue and cannot believe I missed that. Ok so I shouldn't have used mysql to begin with, thanks. Do you have any suggestions to moving the data out and into something else, or upgrading? I suppose my next action will be to upgrade our mysql version if nothing else

**Comment by Unknwon** [comment]
> I suppose my next action will be to upgrade our mysql version if nothing else

Yeah... you can only do that. But you can first backup data as SQL. In case data lost, you can import them back.

**Comment by IaBurton** [comment]
Ok I updated it to 5.5.48 and I'm still seeing it. So I have a few questions for you then before I try something else.

Could the issue be that the database was originally created under 5.1 and is now a lost cause?
Have you ever seen a duplicate column issue with sqlite3?
If I turn the install lock off and start over but leave my gogs-repositories how will Gogs treat that?

Thanks again for your help

**Comment by Unknwon** [comment]
I'm confused by what database are you using?

**Comment by IaBurton** [comment]
I upgraded MySQL from 5.1 to 5.5.48 and I'm still getting the access denied error with the newer gogs versions, but not 0.7.22

**Comment by Unknwon** [comment]
So what is the error for MySQL?

**Comment by IaBurton** [comment]
`2016/02/12 16:30:02 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)`

Access denied for using a password. As I mentioned earlier, this lead me to issue #385 and that post on the troubleshooting page but I cannot determine whats causing it, since without changing the password gogs 0.7.22 has no issues. I was hoping updating mysql as you mentioned the minimum version was 5.5.3 would fix it, but it doesnt seem like it has

`[root@STARFISH ~]# mysql --version
mysql  Ver 14.14 Distrib 5.5.48, for Linux (x86_64) using readline 5.1`

**Comment by IaBurton** [comment]
I should mention that the password works fine for all other apps, including gitlab which is what we're moving from to gogs, and gogs version 0.7.22, but not newer versions of gogs. I turned production mode off for gogs but didn't see any additional output about that error

**Comment by Unknwon** [comment]
Thanks for the explanation but isn't the error is very clear your password is not correct?

**Comment by Unknwon** [comment]
Cause is listed on https://gogs.io/docs/intro/troubleshooting.html#outdated-mysql-password-setting ... that's all I know for now.

**Comment by Unknwon** [comment]
So, are you able to access web UI?

**Comment by IaBurton** [comment]
I know the error seems straight forward, and that the password must be wrong, but it works everywhere else except newer gogs versions. Thats why I tried enabling debug mode for gogs and mysql to see what the actual password was that was being attempted (silly but thats all I could think of)

Our password didn't match the "old" or insecure style of passwords for mysql which is what that link references, but I did try that anyways (resetting the password, flushing privileges) and that still didn't resolve it.

The password does have special characters in it which requires escaping on bash/shell just to login to mysql, could the Go ini app you're using not be catching those and passing the password incorrectly? But thats why its weird that gogs 0.7.22 works fine. It doesnt throw an error and serves the UI just fine. but the newer versions throw that fatal access denied error and I cannot get to the UI with them.

I'm at a loss as to what this could be

**Comment by Unknwon** [comment]
Thanks,

Are you able to access web UI?

**Comment by IaBurton** [comment]
Of the old gogs version yes, of the new version no.

**Comment by Unknwon** [comment]
How did you setup the newer version?

**Comment by IaBurton** [comment]
Exactly as demonstrated here https://gogs.io/docs/upgrade/upgrade_from_binary

I've tried all versions newer than 0.7.22 using that method

**Comment by Unknwon** [comment]
@IaBurton So how did you finish install if you can't access database?

**Comment by IaBurton** [comment]
I'm not sure what you mean.

The password works fine for me and other apps to connect to mysql. I can login and see all of gogs tables/data. When upgrading from the binary, the last step which is running gogs itself fails because it gets the access denied. But if I move back the old version of gogs and start it it accesses the database just fine.

If you're referring to the /install step, that was done in the old version, are you supposed todo /install again for every version? If thats the case I hadn't read that anywhere, especially since there is an install lock in the app.ini (which you say to copy in that upgrade_from_binary link)

**Comment by IaBurton** [comment]
If I turn off the install lock I can get to the UI at /install, but as I asked earlier, I didn't know what that would do to existing data and hadn't read anywhere that /install was necessary again

**Comment by Unknwon** [comment]
Can you dump the database config section here again for MySQL (without password)?

**Comment by IaBurton** [comment]
[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = **********

I've tried using localhost:3306 as well as the external ip and hostname for the server (just to see if that would work) and nada. The password has semicolons in it btw, if that makes a difference in how it is read

**Comment by Unknwon** [comment]
> The password has semicolons in it btw, if that makes a difference in how it is read

That somehow could be the problem but I can't entirely sure, may try something without it?

The Gogs code for treating MySQL password is the same between 0.7.22 and `master` branch, but no insurance that dependency or MySQL driver might change its behaviors.

**Comment by IaBurton** [comment]
Success! Honestly not sure why I didn't try that earlier, would have saved us a lot of time.

I made a new MySQL user for gogs just to use, with a different password without the special characters of the other one, and now its working, 0.8.25 didn't get the access denied error and the upgrade was successful.

It seems the mysql driver or some other package changed between versions and caused this. It might be worth noting somewhere (maybe the troubleshooting page?) or investigating further so someone else doesn't have the same problem.

Thanks again @Unknwon :smile:

**Comment by Unknwon** [comment]
I might know how to solve this because someone else reported this problem with PostgreSQL as well.

I'll change the purpose of this issue and try to fix it.

Thanks for following up!

**Comment by IaBurton** [comment]
No problem! I'll be checking back to figure out what the issue was as I'm curious, so let me know if you need anything else.

**Comment by Unknwon** [comment]
@joshfng would you like help with this?

A reference: https://github.com/gogits/gogs/blob/master/models/models.go#L143

Not sure if this is going to fix the problem as PosgreSQL does, but will be a good try!

**Comment by joshfng** [comment]
@Unknwon yep I'll take a look

**Comment by joshfng** [comment]
This is not a code problem, it's an ini limitation. `;` is a comment in `ini`, so everything after the `;` was disregarded by the ini parser.

In order to get this to work you need to quote the password in the ini file using "`"

example app.ini that failed:
```
[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = something;random
```

Resulting log output with password debugging:
```
2016/02/12 23:19:05 [W] Password: "something
2016/02/12 23:19:05 [T] Custom path: /Users/joshfng/go/src/github.com/gogits/gogs/custom
2016/02/12 23:19:05 [T] Log path: /Users/joshfng/go/src/github.com/gogits/gogs/log
2016/02/12 23:19:05 [I] Gogs: Go Git Service 0.8.33.0210
2016/02/12 23:19:05 [I] Build Time: 2016-02-13 04:16:32 UTC
2016/02/12 23:19:05 [I] Build Git Hash: 600d8edaca56ac9b74bd73c3625c17875ecb848e
2016/02/12 23:19:05 [I] Log Mode: File(Info)
2016/02/12 23:19:05 [I] Cache Service Enabled
2016/02/12 23:19:05 [I] Session Service Enabled
2016/02/12 23:19:05 [I] Git Version: 2.7.1
Password: "something
Con String: "root":"\"something"@tcp(127.0.0.1:3306)/gogs?charset=utf8&parseTime=true
2016/02/12 23:19:05 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1045: Access denied for user '"root"'@'localhost' (using password: YES)
```

app.ini with correctly quoted password:
```
[database]
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = `something;random`
```

Correct output and startup:
```
2016/02/12 23:21:10 [T] Custom path: /Users/joshfng/go/src/github.com/gogits/gogs/custom
2016/02/12 23:21:10 [T] Log path: /Users/joshfng/go/src/github.com/gogits/gogs/log
2016/02/12 23:21:10 [I] Gogs: Go Git Service 0.8.33.0210
2016/02/12 23:21:10 [I] Build Time: 2016-02-13 04:21:01 UTC
2016/02/12 23:21:10 [I] Build Git Hash: 600d8edaca56ac9b74bd73c3625c17875ecb848e
2016/02/12 23:21:10 [I] Log Mode: File(Info)
2016/02/12 23:21:10 [I] Cache Service Enabled
2016/02/12 23:21:10 [I] Session Service Enabled
2016/02/12 23:21:10 [I] Git Version: 2.7.1
Password: something;random
Con String: root:something;random@tcp(127.0.0.1:3306)/gogs?charset=utf8&parseTime=true
2016/02/12 23:21:11 [T] Doing: CheckRepoStats
2016/02/12 23:21:11 [I] Run Mode: Production
2016/02/12 23:21:11 [I] Listen: http://0.0.0.0:3000
```

**Comment by joshfng** [comment]
Note: no code needed to change. Adding `url.QueryEscape()` to the values actually broke it.

**Comment by Unknwon** [comment]
Good catch! @joshfng Should add this to documentation.

cc @IaBurton

**Comment by joshfng** [comment]
I can update the docs for those who manually edit the ini file.

We should change the installer to write the mysql password inside of `` ` `` also.

**Comment by Unknwon** [comment]
@joshfng thanks, yes, I think we need to change the INI package.

The `Write` method in INI package does not detect `#;` etc, so the backquote will be ignored when to rewrite.

**Comment by Unknwon** [comment]
Oh... didn't expect this is already implemented in INI package: https://github.com/go-ini/ini/blob/master/ini.go#L1135

**Comment by Unknwon** [comment]
So if @IaBurton was using install page, the backquotes should be added automatically.

**Comment by joshfng** [comment]
Yep! I just did an install with `something;random` as the password and it correctly wrote it to the ini file as `` `something;random` ``. I think this was just an issue with older versions and existing PASSWD values.

**Comment by IaBurton** [comment]
Interesting. Glad the "fix" is so painless :smile: 

I've been using gogs since version 0.5.x or 0.6.x and did use the installer on the very first use. Not sure if I edited the password sometime after that or it wasn't escaped in those versions, I just know I started having issues with versions after 0.7.22 and didn't have time to dig into it until today. Thanks @Unknwon and @joshfng

**Comment by Unknwon** [comment]
@IaBurton thanks for your support along the way, hope upgrade is smooth except this password problem  :trollface:

**Comment by joshfng** [comment]
Docs were updated and I confirmed the INI package correctly quotes illegal characters during install. I think this is safe to close.
