### ISSUE TITLE
Installing in macosx is not so easy

### ISSUE THREAD

**Issue by yackitotreeville** [gogits/gogs#2618]
I installed bower, go, gopm, git and postgresql

1. The Instructions here https://gogs.io/docs/installation/install_gogs_on_mac doesn't work any more

Alternatively

1. I downloaded gogs-master.zip
2. I ran gogs-master/gopm get -v
3. I ran gogs-master/gopm build -v

This is the strack trace: 

[GOPM] 02-13 03:01:15 [ INFO] ===== application outputs start =====

github.com/gogits/gogs/routers/api/v1/convert
.vendor/src/github.com/gogits/gogs/routers/api/v1/convert/convert.go:55: undefined: gogs.Branch
.vendor/src/github.com/gogits/gogs/routers/api/v1/convert/convert.go:56: undefined: gogs.Branch
[GOPM] 02-13 03:01:24 [ INFO] ====== application outputs end ======
[GOPM] 02-13 03:01:24 [ INFO] Setting GOPATH back to /usr/local/opt/go
[GOPM] 02-13 03:01:24 [FATAL] fail to build program: exit status 2

**Comment by Unknwon** [comment]
Thanks your report!

It might be a wrong commit SHA tag in the .gopmfile but I've checked it is up-to-date in the `master` so it could be some problem with gopm.

I'll delete the page, and you can just download packed zip from https://dl.gogs.io/
