### ISSUE TITLE
Can't add localhost as webhook payload URL

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#2620]
When I enter a URL like `http://localhost:4042/hook/push` as webhook to a repository, Gogs errors with "Invalid Payload URL". Luckily `http://127.0.0.1:4042/hook/push` works, too. But I feel like it should work with `localhost` as well.

PS: Gogs 0.8.25.0129

**Comment by Unknwon** [comment]
Reference: https://github.com/go-macaron/macaron/issues/69

**Comment by Unknwon** [comment]
Do `go get -u github.com/go-macaron/binding` and recompile Gogs should solve the problem.

**Comment by NiklasRosenstein** [comment]
Thanks! I'll try it during this week.

**Comment by Unknwon** [comment]
Close as fixed.
