### ISSUE TITLE
Webhook response sometimes monospace, sometimes not

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#2623]
See screenshot below. Looks like a bug in Gogs to me, the response Content-type is `text/plain` in both cases. Seems to depend on the actual content of the output whether its monospaced or not. So every time the second version is returned by the webhook, it's not monospaced.

![screen shot 2016-02-14 at 14 09 55](https://cloud.githubusercontent.com/assets/1318438/13033834/be9c9ff8-d324-11e5-8aa3-7005f7963751.png)

**Comment by Unknwon** [comment]
Thanks your report!

Can you use Chrome/Firefox web console inspect to see how HTML elements are different under the **Body** section?

**Comment by NiklasRosenstein** [comment]
The monospaced version has `<pre class="raw"><code class="hljs nimrod">...` and the non-monospaced version is `<pre class="raw"><code class="hljs markdown">...`

**Comment by Unknwon** [comment]
OK... I guess `markdown` class is the problem... try hack it to `nimrod`?

**Comment by NiklasRosenstein** [comment]
Yes, then it's monospaced. There seems to be syntax highlighting in both cases, I would suggest disabling that. If the idea was to do syntax highlighting eg. for JSON responses, then the syntax highlighting could be based on the response Content-Type. Eg. use no syntax highlighting for `text/plain`, JSON highlighting for `application/json` etc.

**Comment by Unknwon** [comment]
It might be good to merge your last comment into https://github.com/gogits/gogs/issues/2255 , core problem is basically the same.

**Comment by Unknwon** [comment]
@NiklasRosenstein Hi, sorry I forgot what's the situation of this issue right not, can you recap a bit?

**Comment by Unknwon** [comment]
Pushed a fix to `develop` and you can test on https://try.gogs.io

**Comment by Unknwon** [comment]
Close as fixed.
