### ISSUE TITLE
username in HTTPS URL

### ISSUE THREAD

**Issue by mrexodia** [gogits/gogs#2627]
When you create a new repo it says:

```
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://git.myserver.com:443/user/repo.git
git push -u origin master
```

Tt would be nice if the `user` was in the https clone url like so:

```
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://user@git.myserver.com:443/user/repo.git
git push -u origin master
```

This saves time typing the user/password when cloning.

**Comment by xxxtonixxx** [comment]
Yeah, that would be a good feature when you are logged :+1:

**Comment by mrexodia** [comment]
I looked at how to implement it but I never programmed it Go so I'm now
sure I can do it. There should also be checks on if you have access to the
repository and stuff.

**Comment by Unknwon** [comment]
Note for who wants to help:

1. This information will only be shown for who has write access to the empty repository.
2. We can show the user name by using template variable `{{.SignedUserName}}` to whoever signed in and view this page.

**Comment by sapk** [comment]
I can do it

**Comment by Unknwon** [comment]
Thanks @sapk

**Comment by sapk** [comment]
Just to do the right thing, can we apply to all clone (also wiki) url or just for the init of the repo ?

**Comment by Unknwon** [comment]
> just for the init of the repo

I think that's enough.

**Comment by xxxtonixxx** [comment]
why?, I think that it would be well for everything... are there differences between a repo doesn't initialized and a repo already initialized?

**Comment by Unknwon** [comment]
> why?, I think that it would be well for everything...

Init page is more meant to be inited and push, URLs in other pages are not.

**Comment by xxxtonixxx** [comment]
Ok, make sense! :+1:

**Comment by mrexodia** [comment]
I disagree. It should be also in the clone Url (like bitbucket). Including
it there saves typing a username which is never a bad thing in my opinion.

**Comment by Unknwon** [comment]
> it there saves typing a username which is never a bad thing in my opinion.

I do not think this saving is necessary.

**Comment by mrexodia** [comment]
Well in that case add an option to enable/disable adding a username to the
HTTPS url. Bitbucket has been doing this for years now (for clone URLs) and
I never had any trouble with it.

Now that I think of it, I did see some option to customize the HTTPs URL.
Is it possible to include this in there?

**Comment by Unknwon** [comment]
> Now that I think of it, I did see some option to customize the HTTPs URL.
Is it possible to include this in there?

Good suggestion, but I don't think worth it? Isn't the same you use https://git-scm.com/docs/git-credential-store ?

**Comment by mrexodia** [comment]
I do use credential store but why make me type my username when it's not
needed? What are the downsides of putting a username in the clone url?

**Comment by Unknwon** [comment]
@mrexodia people who just want to clone and no wish to push.

**Comment by mrexodia** [comment]
Oh, the username would only be added to repositories you actually have push
access to. I will check what Bitbucket's behavior is on this matter and
report back here.

**Comment by mrexodia** [comment]
So Bitbucket just puts your username in from of every clone url even if you have no write access to the repository (this is just a random repo I found, not affiliated with it):

```
user@ubuntu:~$ git clone https://iamnotregisteredatbitbucket@bitbucket.org/fenics-project/dolfin.git
Cloning into 'dolfin'...
remote: Counting objects: 195973, done.
remote: Compressing objects: 100% (45637/45637), done.
remote: Total 195973 (delta 151082), reused 190462 (delta 146330)
Receiving objects: 100% (195973/195973), 27.54 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (151082/151082), done.
Checking connectivity... done.
user@ubuntu:~$ 
```

If the repo is public the username is completely ignored so adding it doesn't matter. I don't have any public repositories on my Gogs server so I cannot test what Gogs does right now but I will soon and report back.

**Comment by Unknwon** [comment]
This is not a good idea in a second thought, closing...

**Comment by mrexodia** [comment]
So why exactly? BitBucket have been doing it for years without problems.
