### ISSUE TITLE
Authentication Question

### ISSUE THREAD

**Issue by LukeMauldin** [gogits/gogs#2629]
I have LDAP authentication setup to connect to Active Directory.  I went to create a new user account and I put in my username/password that matched my Active Directory account and the account creation worked.  How can I make sure that Gogs is authenticating that user against the LDAP authentication configuration I setup vs just creating the user locally?

**Comment by Unknwon** [comment]
> How can I make sure that Gogs is authenticating that user against the LDAP authentication configuration I setup vs just creating the user locally?

Go to admin dashboard `/admin/users` see the user account type, you will find out. :trollface:

Closed by 

> Please start discussion or ask a question on the forum. GitHub issue tracker only keeps bugs and feature requests, all other topics will be closed without reason.

**Comment by LukeMauldin** [comment]
I navigated to `/admin/users` but I don't see an Account Type listed?  Please see attached screenshot. I am using the latest released version of Gogs

![useraccount](https://cloud.githubusercontent.com/assets/1440808/13059338/0b7ea27e-d3ef-11e5-82db-d360a8438dc5.png)

**Comment by Unknwon** [comment]
Why don't you click the the edit?

**Comment by LukeMauldin** [comment]
I clicked on the edit, I didn't realize it would show me a different view for a user authenticated via LDAP.  I a manually created a user and selected the Authorization Source: LDAP. However, I now cannot login with that user.  How can I turn on logging to troubleshoot the problem more?

**Comment by Unknwon** [comment]
> I a manually created a user and selected the Authorization Source: LDAP

What does this mean?

**Comment by LukeMauldin** [comment]
I went to `/admin/users/new` and selected `Authentication Source` Active Directory.  I was able to view more of the logs by stopping the Gogs systemd service and launching 'gogs web' and viewing the stdout to fix the LDAP bindings. Thank you for the help.

**Comment by Unknwon** [comment]
:sweat:....
