### ISSUE TITLE
Wrong avatar_url in webhook payload

### ISSUE THREAD

**Issue by lukasdietrich** [gogits/gogs#2630]
The payload of webhooks has a field `sender.avatar_url`, which is set at [routers/repo/webhook.go](https://github.com/gogits/gogs/blob/dce2a9e7e1146293f711c0dbd9725ac7eb0b8a16/routers/repo/webhook.go#L367).

This results in the wrong avatar url in the form of `https://my_host.com/https://secure.gravatar.com/avatar/avatar_hash`

**Comment by Unknwon** [comment]
Thanks your report!

Just pushed a fix to `develop` and you can test on https://try.gogs.io as well.

**Comment by lukasdietrich** [comment]
Can confirm, working as intended :+1:

Thanks!

**Comment by Unknwon** [comment]
Thanks your confirmation!
