### ISSUE TITLE
page titles across pages

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2632]
The dashboard for your home account and for an organisation account has the same title "Dashboard - ..."

Could there be some sort of identification for which user the dashboard is for such as "MyCompany Dashboard" or "Dashboard MyCompany" for an organisation called "MyCompany"? It'd make things easier when you have multiple tabs open!

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2797.

Please help test on `develop` branch or demo site.

**Comment by moltam** [comment]
It's working:

https://try.gogs.io/
`<title>moltam - Gogs: Go Git Service</title>`

https://try.gogs.io/org/apple/dashboard
`<title>apple - Gogs: Go Git Service</title>`

Altough the profile pages have the same title (username). Isn't this confusing?

**Comment by Unknwon** [comment]
@moltam yeah..

cc @allonsy my bad, can you add ` - ctx.Tr("dashboard")` after display name?

**Comment by moltam** [comment]
Special chars are also escaped: `<title>Tamás Molnár &amp;amp; &amp;lt; - Gogs: Go Git Service</title>`

**Comment by Unknwon** [comment]
@moltam this is not relevant to this thread, please search on issue tracker.

**Comment by moltam** [comment]
@Unknwon Sorry, this wasn't meant to be an issue report. I've tested, that special characters are properly escaped.

**Comment by allonsy** [comment]
@Unknwon will do, should I submit changes on the merged PR or create a new one?

**Comment by Unknwon** [comment]
@allonsy you can't update merged PR, need to send a new one.

**Comment by Unknwon** [comment]
Everything should be good now!

**Comment by Unknwon** [comment]
Close as fixed.
