### ISSUE TITLE
Error message in Admin Config Panel

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#2633]
When I am logged in in my googs an go to the admin panel und click on "Configuration" I get an error message:
`template: admin/config:78:38: executing "admin/config" at <.Service.EnableCache...>: EnableCacheAvatar is not a field of struct type interface {}`

I am using the gogs version 0.8.37.0215 with go language 1.5.3

**Comment by Unknwon** [comment]
Just pushed a fix to `develop`, can you help test again?

**Comment by focmb** [comment]
Cloned the last develop branch and it works

**Comment by Unknwon** [comment]
Thanks your confirmation!
