### ISSUE TITLE
how to config an external issue tracker in gogs?

### ISSUE THREAD

**Issue by MIYU-G** [gogits/gogs#2638]
I can't any config option about it in repos setting,just "External Issue Tracker URL Format"

**Comment by Unknwon** [comment]
Yes, that is all Gogs have. :sweat_smile:

Close according to:

> Please start discussion or ask a question on the forum. GitHub issue tracker only keeps bugs and feature requests, all other topics will be closed without reason.

**Comment by MIYU-G** [comment]
you mean I can't set the external issue tracker url now like external wiki ?

**Comment by Unknwon** [comment]
@MIYU-G 

> External Issue Tracker URL Format

This is exactly what you need, the help description is right near the input box.
