### ISSUE TITLE
Webhook test deliver wrong Git ref

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#2639]
Doing a Webhook test delivery sends "master" as Git ref instead of "refs/heads/master". Gogs 0.8.25

**Comment by Unknwon** [comment]
Hi, please test on `develop` branch or https://try.gogs.io again.

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by NiklasRosenstein** [comment]
Looking good, thanks!
