### ISSUE TITLE
Ability to download diff as patch

### ISSUE THREAD

**Issue by biji** [gogits/gogs#2641]
Please add feature to download as patch while viewing commit detail:
[Split View]  [Show Diff Stats] [Download as patch]

Thanks

**Comment by eriknelson** [comment]
+1

Is it possible to generate a .diff or .patch via a commit today? Very useful feature available on Github and Gitlab.

**Comment by jag3773** [comment]
Looks like Github accomplishes this by simply allowing you to append '.patch' to the URL, might be a good way to go if you don't want to add a UI for this.

**Comment by odinuge** [comment]
Need any help on this?

Have been looking into implementing the ability to append '.patch' and '.diff' to the url. Would be great for quickly getting a  .patch file, or getting the _whole_ diff.

**Comment by Unknwon** [comment]
@odinuge yes, please go ahead :smiley:

**Comment by biji** [comment]
when implemented, maybe adding explicit link to .patch and .diff would be great. so this is not a hidden feature :smile:

**Comment by renard** [comment]
Hi,

Will this feature be added in the next release? That would be great. Thanks.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.
