### ISSUE TITLE
Problem of links in wiki

### ISSUE THREAD

**Issue by Twisterat57** [gogits/gogs#2642]
Hi great gogs developers.
First of all, many thanks for this amazing open source project!
I would like to be able to **share setup links on the wiki page** of the projects (ie: we have a team that prepares our Windows CE devices with specific customer applications to be installed on it) and also with Sales team for example.

### Sharing Wiki (read only) and issues (Read/Write) for specific teams:

Those teams should not have access to the source code, but only to the wiki (Read only) and maybe on the issues (Read and Write i guess). OK this is not a standard function but this should be awesome to use gogs as a release share platform also!

### Issues with wiki links:
there is also an issue with links on wiki, when the **setup files are in an other server** and when i try to link it on the wiki page in gogs, it adds the server URL before the link (not tested when files are in the same server): 
ie:
**the specified link:**
file://10.93.167.28/Department$/ServiceSupport/App%20Database/device/Customer/Installer.CAB
**When we click the link:**
http://Server/Customer/RepositoryName/file:/10.93.167.28/Department$/ServiceSupport/App%20Database/device/Customer/Installer.CAB

Navigator always asks for a password to access the link from the gogs server (btw the link is wrong and i get a 404 error after authentification)=> [note: i am the gogs server Admin...]

**This URI is not recognised as a link:**
\\\\10.93.167.28\Department$\ServiceSupport\App Database\device\Customer\Installer.CAB

**Comment by Unknwon** [comment]
Thanks your feedback!

> Sharing Wiki (read only) and issues (Read/Write) for specific teams:

>Those teams should not have access to the source code, but only to the wiki (Read only) and maybe on the issues (Read and Write i guess). OK this is not a standard function but this should be awesome to use gogs as a release share platform also!

I think you're talking private repository with public wiki and issues?

> Issues with wiki links:

I suggest you open another issue for this and discuss.

**Comment by Twisterat57** [comment]
Many thanks for your feedback @Unknwon ...
You mean that i should open a new issue named "private repository with public wiki and issues"?
Should i open a new issue for the links which are not working on wiki or should this one stay?

Best regards

**Comment by Unknwon** [comment]
> Should i open a new issue for the links which are not working on wiki or should this one stay?

You can change the title of this issue to about this.

> You mean that i should open a new issue named "private repository with public wiki and issues"?

- https://github.com/gogits/gogs/issues/649
- https://github.com/gogits/gogs/issues/2157

**Comment by Twisterat57** [comment]
Ok i have copy/paste the "private repository with public wiki and issues" to one of the already existing issues and renamed this one "Issues with wiki links" :then it will be more clear.

**Comment by bkcsoft** [comment]
> **the specified link:**
> file://10.93.167.28/Department$/ServiceSupport/App%20Database/device/Customer/Installer.CAB
> **When we click the link:**
> http://Server/Customer/RepositoryName/file:/10.93.167.28/Department$/ServiceSupport/App%20Database/device/Customer/Installer.CAB

This can be fixed (by the gogs admin) by setting adding `file` to `CUSTOM_URL_SCHEMES` in `app.ini`
Like this:
```
[markdown]
CUSTOM_URL_SCHEMES = file
```

Though the link has to be written in `[name](url)`-form to work (bug in blackfriday)

**Comment by Twisterat57** [comment]
Hi @bkcsoft i have tried your suggestion and restarted gogs web. Now each time i save a wiki page, even without any link i get an "500 internal server error" message and the wiki page changes are not applied and if this is a new page, it is not created nor not shown on the wiki tab...

here is the actual gogs Application Version: 0.8.10.1217

of course the url is wrote as expected on the editor:
`[Latest release](file://10.93.167.28/Department$/ServiceSupport/App%20Database/device/Customer/Installer.CAB)`

**Comment by bkcsoft** [comment]
@Twisterat57 can you paste the logs from gogs?

**Comment by Twisterat57** [comment]
Ooo Seems even if i remove the markdown section from the ini file, i get this 500 error...
here is the log file:
[gogs.txt](https://github.com/gogits/gogs/files/136158/gogs.txt)

**Comment by bkcsoft** [comment]
Yeah, seems like the wiki-repo is borken or missing :worried:

**Comment by Twisterat57** [comment]
The wiki repo is there... Strange thing:
- Existing pages before ini change can be viewed (not possible to edit)
- If there is no wiki page, i have the "welcome to wiki" web page shown to be able to create it: then if i try to create one, i get directly the error 500 and then i always get the error 500 instead of the  "welcome to wiki" web page. The only way to get back the  "welcome to wiki" web page is to delete the Wiki repository

**Comment by Twisterat57** [comment]
in the gogs server console i get:
2016/02/18 16:53:09 [...routers/repo/wiki.go:53 renderWikiPage()] [E] GetBranchC
ommit: exit status 128 - fatal: 'refs/heads/master' - not a valid ref

So i have been navigating trough the directories of the reposiitory and there is no "Master" file in the sub directory "refs\heads" of the repository... gogs seems not to create the Master branch anymore when creating the first wiki page...

git version: 2.7.0.windows.1
OS: Windows server 2008 R2
GOGS: 0.8.25.0129 (64 bits version: used binaries to setup gogs)

**Comment by Unknwon** [comment]
@Twisterat57 You need to update to `master` in order to fix that.

**Comment by Twisterat57** [comment]
ok.. done it, now i get:
`
c:\gogs>gogs web
2016/02/19 14:17:34 [T] Custom path: c:/gogs/custom
2016/02/19 14:17:34 [T] Log path: c:/gogs/log
2016/02/19 14:17:34 [I] Avery Dennison's Git service 0.8.37.0217
2016/02/19 14:17:34 [I] Log Mode: File(Info)
2016/02/19 14:17:34 [I] Cache Service Enabled
2016/02/19 14:17:34 [I] Session Service Enabled
2016/02/19 14:17:34 [I] Mail Service Enabled
2016/02/19 14:17:34 [I] Notify Mail Service Enabled
2016/02/19 14:17:34 [I] Git Version: 2.7.0
2016/02/19 14:17:35 [...s/routers/install.go:70 GlobalInit()] [E] Fail to initia
lize ORM engine: Fail to connect to database: Unknown database type: sqlite3
`
SQlite database type is not recognized animore

**Comment by Unknwon** [comment]
https://gogs.io/docs/installation/install_from_source#build-with-tags

**Comment by Twisterat57** [comment]
Ah already back from holidays...

i had file not found issues with tags sqlite and tidb... so i didn't succeed to install from source...
**BUT** i have updated from the new version "0.8.43.0223" and here is the following:

Creating link as follow on the wiki page
`[Link a](file://10.10.10.10/Department$/ServiceSupport/App%20Database/6057/customer/Install.CAB)`

doesn't generate an error 500 wen saveing/going back to the wiki page, but... Nothing happens when i click on it: this is pretty strange because i can see the correct link when the mouse is over it and if i right click on google chrome and copy the link, then paste on a new tab i can access to the file.

I guess it's due to "nofollow" in the following generated link (got from wiki page inspection on google chrome)
`<a href="file://144.93.167.28/Department$/ServiceSupport/App%20Database/6057/SKF/SKFInstaller.CAB" rel="nofollow">Link a</a>`

is it for a security reason?

BTW if i try to use a URI to the file i get an error 500 while trying to save the wiki page: is there an other ini change to do?

here is my ini markdown section:
`[markdown]
CUSTOM_URL_SCHEMES = "git,file,magnet"`

**Comment by Unknwon** [comment]
> i had file not found issues with tags sqlite and tidb... 

I don't understand this sentence....

> I guess it's due to "nofollow" in the following generated link (got from wiki page inspection on google chrome)

`nofollow` only affects search engines.

> file://144.93.167.28/Department$/ServiceSupport/App%20Database/6057/SKF/SKFInstaller.CAB

What happens if you directly open this link on your browser?

**Comment by neolit123** [comment]
> file://10.10.10.10/Department$/ServiceSupport/App%20Database/6057/customer/Install.CAB

TMK, many browsers nowadays don't support direct, out-of-the box support for the file:// scheme.
it would be best to expose the files via http://, really.

**Comment by neolit123** [comment]
on *nix, you can create a symbolic link (e.g. named "customer") inside the "gogs/public" folder and link to a mounted location where the actual "10.10.10.10/..../customer/" folder is.
then the user can access the files via the http://<theserver>/customer/somefile.cab

i haven't tried Gogs on Windows, so i'm not sure, but my guess is that you can just copy the CAB files in the "gogs/public/customer" folder and again use http:// instead of file://.

**Comment by Unknwon** [comment]
@neolit123 good tip! Never thought of this way :joy:

**Comment by Twisterat57** [comment]
@unknown if I copy/paste the link, chrome opens the save file dialog box and file is downloaded (IE also does)

**Comment by neolit123** [comment]
@Twisterat57 the address bar relocation should work, as that's OS integrated. also, if you create the following HTML file (e.g. named ```test.html```):
```
<a href="file://test.txt">link</a>
```

and open it locally the ```file://``` URI scheme *should* work.

however, if you upload the file to the web, browsers like chrome will not validate the HREF and the click will not work. there was a security option to enable that for chrome, but that's a complication on the user side.

**Comment by neolit123** [comment]
> Btw ftp://// header will not be recognised by gogs no?

it won't work for a lot of modern browsers, including chrome and firefox and that's not Gogs' fault. :)
one of your best options is to simply copy the CAB files to the ```gogs/public``` folder, and link like so:

```
http://server.com/somefile.cab
```

something else you can try is the Windows alternative to *nix symbolic links - [mklink](https://technet.microsoft.com/en-us/library/cc753194.aspx)

and create a symbolic link of the shared folder in ```gogs/public```, but there is a good chance that won't work.

**Comment by Unknwon** [comment]
@Twisterat57 What happens if you delete `nofollow` attributes through inspection and click that link again?

**Comment by neolit123** [comment]
@Twisterat57 
> it won't work for a lot of modern browsers, including chrome and firefox and that's not Gogs' fault. :)

sorry, i misread you comment; was a talking about ```file://``` obviously there.

you can add ```ftp``` to list in CUSTOM_URL_SCHEMES and it *should* work just fine.

there is not much point to enable ```file``` to CUSTOM_URL_SCHEMES, because the moment you enable the server on the web, most users browsers will not allow the ```file://``` links. ```nofollow``` should not make a difference.

**Comment by Unknwon** [comment]
Any updates?

**Comment by Twisterat57** [comment]
Hi,
OK you are right, it is locked for security reasons by Chrome. When you inspect the page you get the following error at the bottom of the inspector:

8test:1 Not allowed to load local resource: 
file://....

@neolit123 is right:
seems that you can only open a file if the link is in "http" and not in "file"

other option is to use the command parameter "--allow-file-access-from-files" when starting Chrome. but it will enable it to all web pages :( they could allow those kind of link for approved site.

Or... call an HTTP file within the same directory as the file: **this works**, and i guess it's because the HTML file is in the same host has the file, so yes i should use the public gogs, but i'm not able to do so:

i have put the following link:
`[Link a](http://apdvwoo05/CustomerFiles/LM/Setup%20Applications%20LM6057.CAB)`

And i get a "500" error when saving the wiki page
`error not a Git repository (or any of the parent direcories)`

if i copy paste the link:"http://apdvwoo05/CustomerFiles/LM/Setup%20Applications%20LM6057.CAB"
Browser opens it

On the ini, i have added the http pattern on CUSTOM_URL_SCHEMES

**Comment by neolit123** [comment]
@Twisterat57,  @Unknwon 
> error not a Git repository (or any of the parent direcories)

to me this looks like a separate issue.

**Comment by neolit123** [comment]
@Unknwon has better understanding of why this may happen.

i suggest a close of this issue, since:
"Issues with wiki links:" - solved
"Sharing Wiki (read only) and issues (Read/Write) for specific teams:" - duplicate

@Twisterat57

first of all, use the latest gogs (0.9.0):
https://dl.gogs.io/

you might have corrupted your wiki git repository.
try creating the wiki page in a new repository to see if it works.
log an issue if you have found a new bug.

the following might also be an option: 0.9.0 should also allow deleting the wiki from the repository settings. thus, backup your wiki pages, delete the wiki and re-create the pages.

**Comment by Unknwon** [comment]
@neolit123 yes, @Twisterat57 is using two old version.
