### ISSUE TITLE
Can't clone over https Invalid Token

### ISSUE THREAD

**Issue by pollend** [gogits/gogs#2644]
I can't seem to clone my repository over https. I have this configured over an apache reverse proxy if that is potentially an issue. the log just reads this: 

2016/02/17 06:55:38 [...routers/repo/http.go:122 HTTP()] [E] invalid token

**Comment by Unknwon** [comment]
Hi,

I think you're cloning with wrong user name and password.

**Comment by pollend** [comment]
It never requested a username and password.

**Comment by Unknwon** [comment]
Because you set git to remember one?

**Comment by pollend** [comment]
this is only a problem with private repositories.

**Comment by Unknwon** [comment]
If it is a private repository, Gogs will always ask for a username and password.

If you did not see Gogs ask, that means Git remembers that.

**Comment by Unknwon** [comment]
ping @pollend

**Comment by pollend** [comment]
I tired another computer and it still complains about the token.  It works find with an ssh key though so ill probably just use that. I don't actually know what is wrong.

**Comment by Unknwon** [comment]
You should probably check logs from Gogs server, see if any erorrs there.

**Comment by Unknwon** [comment]
Close due to lack of feedback.

You can continue the discussion on https://discuss.gogs.io/.

**Comment by pollend** [comment]
thanks for the help anyways. sorry, I couldn't of been of much help resolving this. I couldn't find much in the logs to really help resolve this.

**Comment by Unknwon** [comment]
@pollend if you're using any reverse proxy, can clone without it, see if it works.

**Comment by AlexGhiti** [comment]
Sorry to reopen this ticket, but I am not able to clone/push/whatever through an apache reverse proxy (but I can navigate through the website with my browser without any problem, and create repos too).
I can clone/push/whatever without it, so my user/password is correct, but through reverse proxy, I constantly get "invalid token" ("2016/04/22 11:36:52 [...routers/repo/http.go:122 HTTP()] [E] invalid token").

Any idea ?

Thanks :)

**Comment by Unknwon** [comment]
@AlexGhiti does it work without reverse proxy?

**Comment by AlexGhiti** [comment]
Yes it does, to summarize:
- with reverse proxy on: I can navigate through the website, but I can't clone any repos, I get "invalid token".
- without reverse proxy: Everything works.

**Comment by Unknwon** [comment]
@AlexGhiti any chance your reverse proxy does not pass HTTP Basic Auth header right?

**Comment by AlexGhiti** [comment]
Good idea !
Actually, in my apache setup, I had added a basic authentication to access any of my website this way: 

<Location /gogs>
   AuthType Basic
   AuthName "Restricted Files"
   # (Following line optional)
   AuthBasicProvider file
   AuthUserFile "/home/**/.config/apache/passwords"
   Require user **
 </Location>

When I removed this from my config file, I can clone/push/everything over my reverse proxy !
However, I'm not entirely sure to understand how this would raise problem: does the basic authentication of my apache server intercept every http basic auth packets and does not transmit them to gogs server ?

Anyway, thank you for your idea !

**Comment by Unknwon** [comment]
@AlexGhiti I think the problem is, Apache pass the auth, but the auth info does not get pass to Gogs correctly.

**Comment by knedlsepp** [comment]
I'm also experiencing this issue.
- Fresh installation of Gogs version 0.9.113.1223
- Create admin account
- Create private repository
- Try to push to repository
```
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin http://server:3000/knedlsepp/gogs-configuration.git
git push -u origin master

Username for 'http://server:3000': knedlsepp
knedlsepp@server:3000': 
remote: invalid token
fatal: Authentication failed for 'http:/server:3000/knedlsepp/gogs-configuration.git/'
```
