### ISSUE TITLE
Incorrect Dashboard History (Database)

### ISSUE THREAD

**Issue by MarcosBL** [gogits/gogs#2650]
## Problem
When I do commits, I can't see them in my dashboard because of a weird database problem

## Versions

- gogs v 0.8.25.0129
- go 1.5.3
- MySQL 5.5.47 - InnoDB

## Repo data

**Username**: MarcosBL
**Email**: soy@marcosbl.com
**Repo**: www.risas.dev
**Repo visibility**: private (doesn't matter in my tests)
**Repo created**: Through web interface
**Organization**: Lab

## Analysis

Tracing the problem, I found the `**action**` table to not have the correct username for those commits: instead of "**MarcosBL**" it shows my email as my username "**soy@marcosbl.com**"

A trace of gogs log shows the query to get the user is correct:

[xorm] [info]  2016/02/18 02:35:09.681702 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `last_repo_visibility`, `max_repo_creation`, `is_active`, `is_admin`, `allow_git_hook`, `allow_import_local`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_following`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `email` = ? LIMIT 1 [args] [soy@marcosbl.com]

but the insertion isn't (field and value in bold and cursive, showing email instead of user)

[xorm] [info]  2016/02/18 02:35:09.792435 [sql] INSERT INTO `action` (`user_id`, `op_type`, `act_user_id`, **_act_user_name_**, `act_email`, `repo_id`, `repo_user_name`, `repo_name`, `ref_name`, `is_private`, `content`, `created`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [args] [1 5 1 **_soy@marcosbl.com_**  54 Lab www.risas.dev master true {"Len":1,"Commits":[{"Sha1":"496bc34791ef8d6fe256cec6ca215777d4554b1b","Message":"Commit message\n","AuthorEmail":"soy@marcosbl.com","AuthorName":"MarcosBL"}],"CompareUrl":"Lab/www.risas.dev/compare/b908228c6fd2ca18eb7dd6679765be89f7b20d45...496bc34791ef8d6fe256cec6ca215777d4554b1b"} 2016-02-18 02:35:09]

In the insertion, `user_id` and `act_user_id` are correct, it even creates 2 events, for the organization and the user, but you can see how it stores **_soy@marcosbl.com_** in the `act_user_name`

![vj4kue4](https://cloud.githubusercontent.com/assets/389801/13131408/965dd5ec-d5eb-11e5-989e-f8a5bb5c3b50.png)

## Tests

If I update the commits with my correct username in `act_user_name`, it shows in the dashboard, both "Lab", the organization, and "MarcosBL", the user:

`update `action` set act_user_name="MarcosBL" where act_user_name="soy@marcosbl.com"`

![](http://i.imgur.com/t1Cq2Nz.png)

I also checked my git conf it's not the problem, it happens both in Smartgit and manual bash git

![](http://i.imgur.com/5GSX3EA.png)

## Conclusion

It seems to me that, for some reason, gogs is inserting the wrong history `act_user_name` in the table `action`: email instead of name, breaking the dashboard functionality

## Links

- [Related forum post with the first problem detection (thought it was solved, seem it wasn't)](http://forum.gogs.io/topic/26/recent-activity/2)
- Related issue #2511

**Comment by Unknwon** [comment]
Thanks your report!

Are you able to reproduce this on https://try.gogs.io ?

**Comment by MarcosBL** [comment]
Just tried and it works fine, but it also works fine in some repos at my install... can it be related to logging into the web interface sometimes using my username and sometimes my email? As it works with both of them, maybe the problem is creating the repo after a email login instead of a username login?

Just ask me for any debug/test you need

**Comment by Unknwon** [comment]
> maybe the problem is creating the repo after a email login instead of a username login?

Possible, can you try this with demo site?

**Comment by MarcosBL** [comment]
It also works... no idea on what can be happening

Tried with different repos, all of them shows the history
Tried login with username & email, no difference
The repo that fails to update started updating correctly after i ran the "update..." query shown above

Do you want me to upload a database dump ? I even checked the rows one by one and couldn't find anything different in that repo, not even in the related tables, everything seems normal, but that insert query, that inserts email instead of username

**Comment by MarcosBL** [comment]
I think I found something, after some more tests.

I had git credential cache set, as you can see in the screenshot above. 
I deleted it, no credentials cached, and made a new commit: it showed instantly, with the correct username in the database

So I suppose I used my email and password as credentials in a past commit, as it works, the commit passed, and credentials got stored. But it doesn't show in the Dashboard, because of the wrong username being stored.

So I don't know how to avoid this happening again, as I think I will not be the only one using sometimes the email, sometimes the username:

- Don't get the commit stored with the wrong username (email) instead of using the name, when you are getting the correct user from the database (as you can see in the query above)
- Show the commits in the Dashboard, even having the wrong username in the table, as long as it has the correct user id, so you can easily match against the user ID instead of the stored user name

I suppose any of the two would solve this problem... both better, but I don't know if that's how gogs work internally.

In fact, I don't even know if that's the problem! :D

**Comment by Unknwon** [comment]
Good info!

But that's a bit weird because you have tried use email as username to push, and it does not occur the problem ,right?

**Comment by Unknwon** [comment]
You're pushing through by HTTP right?

If yes, I might find the bug, and working on it.

**Comment by Unknwon** [comment]
If possible, please update to `develop` branch and help test again?

**Comment by MarcosBL** [comment]
I suppose I can't reproduce because I hadn't stored "wrong" credentials (email & pass instead of username & pass) in the demo.

I use the binary packages but will try to get it working with the dev version as soon as I reach the office, thanks !

**Comment by MarcosBL** [comment]
I wasn't able to compile the develop branch, will try later in a clean VPS, but I can confirm the email issue:

- Created a new repo, used username & password to commit: everything ok
- As soon as I use the email & password combo, commits work, but dashboard doesn't (because of wrong user stored in the database)
- Of course, if I have set the credentials cache, future commits will not work until it gets outdated and I re-enter the credentials using username & password

So I'm pretty sure that's the problem, storing the email instead of the username when the auth from git comes with an email in the username.

Not sure if it should store the username always, or simply use the user ID in the dashboard, but I think your commit addresses this, doesn't it? (sorry, never saw a line of Go code before!)

**Comment by Unknwon** [comment]
Thanks your info!

But you need to update to `develop` and test, all evidence from previous versions are now unimportant.

**Comment by Unknwon** [comment]
ping @MarcosBL

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by MarcosBL** [comment]
So sorry for the lack of updates, personal problem.

Just wanted to confirm the issue is resolved in a new clean VPS using latest develop
