### ISSUE TITLE
git 提交文件有中文名字，web 浏览500

### ISSUE THREAD

**Issue by xiuzhifu** [gogits/gogs#2651]
用最新版本的gogs，windows，
git提交文件有中文名字，web页面就打不开返回500
我在 try.gogs.io 上试了一下，是没问题的，是因为我用了windows？

**Comment by Unknwon** [comment]
Hi, I think this is duplicated to https://github.com/gogits/gogs/issues/2536

**Comment by xiuzhifu** [comment]
yes, i closed this one
