### ISSUE TITLE
团队授权问题

### ISSUE THREAD

**Issue by wzhuzhu** [gogits/gogs#2652]
## 操作流程

1. 注册账户A，B，C
2. A添加组织： OA
3. A在OA下创建新团队: read ，授权: 读取权限
4. A在团队中将 用户B，C加入到 read 团队.
5. A在组织OA下创建项目 test

## 问题

 用户B，C通过web访问项目 test,提示<font color=red>404</font>错误

## 我的应用场景
 
 * 我有用户A，B，C
 * 我创建了项目 test1
 * 我希望A对项目 test1 有读写权限，B,C 只有访问权限.

**是否是我操作有误？**

**Comment by Unknwon** [comment]
Hi,

> 用户B，C通过web访问项目 test,提示404错误

You need to add repository `test` to the team as well.

> 我希望A对项目 test1 有读写权限，B,C 只有访问权限.

You need to create different team with different access.

**Comment by wzhuzhu** [comment]
我创建 `test`项目的时候选择的拥有者是： `OA`
请问我如何操作，对于您的回复：
`You need to add repository test to the team as well.`

**Comment by Unknwon** [comment]
You need add both members and repositories to team.

**Comment by Unknwon** [comment]
Close due to lack of feedback.

You can continue the discussion on https://discuss.gogs.io/.
