### ISSUE TITLE
Make clone timeout configurable

### ISSUE THREAD

**Issue by jeffrey4l** [gogits/gogs#2653]
In current implementation, the timeout is fixed to 10 minute[0]. But when cloning a big repository or having a bad network, 10 minute is not enough. So please make the this value configuration in the app.ini file.

thanks alot

[0] https://github.com/gogits/gogs/blob/master/models/repo.go#L645

**Comment by Unknwon** [comment]
Hi, now in `develop` branch, you can increase [this value](https://github.com/gogits/gogs/blob/develop/conf/app.ini#L336) and test again.

**Comment by Unknwon** [comment]
Close as implemented.
