### ISSUE TITLE
https://packager.io/gh/pkgr/gogs not up to date

### ISSUE THREAD

**Issue by ciruz** [gogits/gogs#2654]
Hey @Unknwon,

the packages on https://packager.io/gh/pkgr/gogs are not up to date, any reason why? :smile: 

Thanks.

**Comment by Unknwon** [comment]
Hi, please follow https://github.com/gogits/gogs/issues/2354#issuecomment-185374807

**Comment by mbi** [comment]
@Unknwon I kindly disagree this is the same issue as #2354, which is related to documentation (displayed on packager.io), while this one seems to be a build issue, i.e. automatic builds not happening on packager.io? /cc @crohr

**Comment by Unknwon** [comment]
@mbi you're right, but I think people should directly contact support for the service provider? As @crohr seems very busy and can't follow on every issue that meantions him.

**Comment by crohr** [comment]
Right now I need to run a cron job to regularly update my fork (at pkgr/gogs) against upstream, which then triggers a build. For some reason this didn't run in the last days and I'll re-enable it.

However it would be easier if gogs enabled gogits/gogs directly on Packager... That would allow anyone to make changes to the package without waiting for me, and you would also have direct control over the documentation provided on Packager. Would that be something you would consider @Unknwon?

**Comment by ciruz** [comment]
@Unknwon I didnt know what or who packager.io is, for me this is was a service where you upload or build the latest gogs release to download for us users. And since you write in documentation, that we can download the latest version from gogs on packager.io (See: https://gogs.io/docs/installation/install_from_packages.html), why should I as a user contact and register myself on packager.io to tell them that gogs package is not up to date.

**Comment by Unknwon** [comment]
@crohr That is great!

**Comment by mbi** [comment]
@crohr hello, it looks like your cron job is failing to run again, the last build on packager.io is two weeks old :disappointed:
