### ISSUE TITLE
License +x permissions

### ISSUE THREAD

**Issue by goblinslovemarmalade** [gogits/gogs#2655]
When selecting a license while creating a repository, the license file has +x permissions: Is that supposed to be? Since it's pure text and not meant/possible to be executed, this should probably be changed.

**Comment by Unknwon** [comment]
Hi, Gogs writes out file with permission 0644: https://github.com/gogits/gogs/blob/master/models%2Frepo.go#L812

So I think there is something else going around?

**Comment by Unknwon** [comment]
ping @goblinslovemarmalade

**Comment by Unknwon** [comment]
Close due to lack of feedback.

You can continue the discussion on https://discuss.gogs.io/.
