### ISSUE TITLE
SSH commits fail to show until HTTP commit made

### ISSUE THREAD

**Issue by oneirosFade** [gogits/gogs#2662]
Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.8.25_raspi2
- Git version: 2.1.4
- Operating system: Raspbian, Kernel 4.1.17-v7+
- Database: SQLite

## Description

I create a new repo in gogs, set my remote on the local codebase to the SSH address, commit, and push. At this time, gogs shows an empty repo still (instructions on how to add remotes, etc). Further pushes to the SSH change nothing. The repository has the code, however, because cloning it via local file (rather than the gogs service) shows exactly what was pushed.
Pushing via HTTP then causes the repo to show as if nothing was wrong, and further SSH pushes from that point on will show just fine.

**Comment by Unknwon** [comment]
>Please take a moment to search that an issue doesn't already exist.

This issue certainly exists.

Please check your `path/to/gogs/log/serv.log` file.

**Comment by oneirosFade** [comment]
I apologize, I didn't search well enough.
The log has four instances of "[T] No update task is presented:" followed by long IDs.

**Comment by Unknwon** [comment]
Thanks, are you use NFS or any sort of mount to store repositories that are managed by Gogs?

**Comment by oneirosFade** [comment]
The repositories are on an external drive that is directly mounted to the system gogs lives on as ext4.

**Comment by Unknwon** [comment]
OK... I think this is duplicated to https://github.com/gogits/gogs/issues/2550?

**Comment by oneirosFade** [comment]
Actually it seems much closer to #1864 (even the fact that it's an ARM device running gogs). The main differences seem to be the gogs version, and mine is a Raspbian system, not Arch-ARM.

**Comment by Unknwon** [comment]
> even the fact that it's an ARM device running gogs

No, many people run Gogs on ARM devices without any issue. So I think it is the problem with mount, wheich is #2550.

**Comment by bkcsoft** [comment]
@Unknwon #2550 is about as unrelated as you can get since it's about UNC paths in Windows (`\\server\path`) and not about mounted drives... #1864 is pretty much spot on though...

@oneirosFade can you paste the relevant line(s) from `/etc/fstab` (if it's there) and whatever `mount` is saying about the mount

**Comment by oneirosFade** [comment]
Yeah. The repository root is at `/media/storage/git/` which is on:
`UUID=29bcc075-3d81-4dc4-aece-664c3d249904       /media/storage  auto    auto,nofail,user        0 0` 
and reported as:
`/dev/sda1 on /media/storage type ext4 (rw,nosuid,nodev,noexec,relatime,data=ordered)`

On a whim, I just disabled nosuid and noexec which seems to have fixed the issue (allowing the git hooks to run on SSH commit).

**Comment by Unknwon** [comment]
> On a whim, I just disabled nosuid and noexec which seems to have fixed the issue (allowing the git hooks to run on SSH commit).

This seems to be the real problem :D

**Comment by Unknwon** [comment]
Updated toubleshooting here: https://gogs.io/docs/intro/troubleshooting#push-was-successful-but-no-activities-are-shown-on-dashboard

**Comment by usagirei** [comment]
@oneirosFade 
How's your fstab mount now? I still run on this issue on a Raspbian, with this mount:
`UUID=7664-B942  /mnt/usbdisk    vfat    rw,nodev,relatime,uid=1000,gid=1000,dmask=000,fmask=111 0       0`

**Comment by oneirosFade** [comment]
Same as before, but I added the `exec` option. gogs now works just fine. I'm just guessing, but is `fmask=111` does what I *think* it does, then that may be your problem (strips the execution permission from everything on that mount). The git hooks need execution permissions to run (thus pushing via SSH can *write* the files, but can't execute the hooks to update gogs).

**Comment by usagirei** [comment]
@oneirosFade yeah, fmask will make all files rw-, since vfat has no individual file permissions, it does infer a little security issue, but then again why *does* it work under https (with fmask rw) is beyond me.

Making fmask 000 (thus everything rwx) does solve the issue

**Comment by Unknwon** [comment]
@oneirosFade Can you help put better wording (as I'm not familiar with mount thing)? I think the way I described how to solve this issue has some problem. 

https://github.com/gogits/docs/blob/master/en-US/intro/troubleshooting.md

**Comment by oneirosFade** [comment]
@usagirei If you're concerned about the security risk of having your entire mount executable (and I don't blame you) you could possibly leverage the user/group settings of the mount. In my case I'd probably have it mounted to the "removable" group (or something like that) with fmask of 101 or 001 (so only the owner and/or group has execute permissions), then adding the gogs user to that group.

@Unknwon Sure, I'll give it a look and PR you when I'm done.

**Comment by usagirei** [comment]
Just letting the feedback that letting the only the user and group with executing permission while mounted as the specific group/user does keeps it working as intended, so there should be no unexpected issues
