### ISSUE TITLE
can't log when using nginx reverse proxy on centos7

### ISSUE THREAD

**Issue by ExiaSR** [gogits/gogs#2666]
Hi,

I was trying to setup the gogs (from binary) on my server, and I use nginx reverse proxy(to access it with git.domain.com)

I can open up the page with git.domain.com:3000 (the default port), but with git.domain.com I got a 502 error instead.

what can I do?

here's my configuration
```
#nginx 1.9.9
server {
    listen 80;
    server_name git.domain.com;

    location / {
        proxy_pass http://localhost:3000;
    }
}
```
/custom/conf/app.ini
```
[server]
ROOT_URL = http://git.domain.com/
```

**Comment by Unknwon** [comment]
Because you did not tell NGINX to reload config?

**Comment by ExiaSR** [comment]
I've try running both
```
sudo nginx -s reload 
```
OR
```
sudo systemctl restart nginx

```
still not working

**Comment by Unknwon** [comment]
1. If you are 100% sure Gogs is running on port 3000.
2. Then you must have used the wrong config, or did not include that file in main NGINX conf (normally would be `/etc/nginx/nginx.conf`).

**Comment by ExiaSR** [comment]
I'm 100% thay gogs is listening at 3000.

do I have to literally write
```
include /etc/nginx/nginx.conf
```
into the configuration file for git.domain.conf

**Comment by Unknwon** [comment]
Hmmm... no, that's not what I meant.

I really mean, the configuration of your NGINX for Gogs, is not taking effect...

**Comment by ExiaSR** [comment]
alright..it seems like it's all selinus's fault

i just diable it, for now.

**Comment by Unknwon** [comment]
:joy:...
