### ISSUE TITLE
Userprofile not shown for not authenticated user

### ISSUE THREAD

**Issue by xoxys** [gogits/gogs#2667]
Hi,
why is  the profile page from a user not displayed for non authed users? If a user without login explore a repo and clicks on the username it opens the page http://your-domain/username but the page is blank... If a logged in user browse to the profile page he got some informations like full name, username, homepage or mail address. I think it would be nice if all users can get contact informations to the owner of a repo.

Thanks for your work.

**Comment by Unknwon** [comment]
It is a bug fixed yesterday already. Just update to lastest `master`...
