### ISSUE TITLE
Gogs doesn't work no more... after server reboot. 

### ISSUE THREAD

**Issue by bernalau** [gogits/gogs#2668]
Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):aa12135
- Git version:
- Operating system:Debian
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Log gist:

## Description

Hello. 

Last week, i have install gogs with the tutorial on your site. 
All worked properly... But i have to restart my server this day and gogs doesn't work. 
The process run, i process connexion to mysql database. 
But when i try to reach the webpage on 3000 ports, it takes a long time before give me message : 
Web page unavailable. ERR_CONNECTION_TIMED_OUT.

I read logs : gogs log seems to be OK. No error, log finish with : 

2016/02/20 16:57:09 [I] Log Mode: File(Info)
2016/02/20 16:57:09 [I] Cache Service Enabled
2016/02/20 16:57:09 [I] Session Service Enabled
2016/02/20 16:57:09 [I] Git Version: 2.1.4
2016/02/20 16:57:09 [I] Run Mode: Production
2016/02/20 16:57:10 [I] Listen: http://0.0.0.0:3000

http.log is empty.
xorm.log has no error...

I have try to resinstall all : go + gogs... but i have always the same issue. 

A telnet from another workstation on the tcp port answer... 

Can you help me ?

**Comment by Unknwon** [comment]
....So... what is going on now?

**Comment by bernalau** [comment]
i don't know really, but this is a issue with my fail2ban config... 
After a reboot, impossible to access and when i fail2ban, after restart gogs : all work fine... even if i start fail2ban... 
Certainly config issue.

**Comment by Unknwon** [comment]
:sweat_smile: OK!
