### ISSUE TITLE
Set HTML meta values for repository

### ISSUE THREAD

**Issue by enplotz** [gogits/gogs#2670]
Hi there :)
While sharing a gogs link, I noticed that the preview had the generic "Gogs (Go Git Service) is a ..." in it. While I am sure this is nice advertisement :) I would like to propose a feature:

Could the description of the repository and author be included as the value in the HTML meta fields?

So e.g. instead of 
```html
<meta name="author" content="Gogs - Go Git Service" />
<meta name="description" content="Gogs (Go Git Service) is a painless self-hosted Git service written in Go" />
```

```html
<meta name="author" content="enplotz" />
<meta name="description" content="Cool program for foo." />
```

I realize it's just a small feature, but I find it nice nonetheless, so users can see what the shared link is really about  :)

**Comment by Unknwon** [comment]
Yep, sounds good!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2824, you can test on https://try.gogs.io/

**Comment by moltam** [comment]
If a repo description is empty, you get something like this:
`<meta name="description" content="yii2 - " />` (reponame - )

I don't know how important to fix this.

Apart from this looks good to me!

**Comment by Unknwon** [comment]
@moltam should be fixed by https://github.com/gogits/gogs/pull/2829

**Comment by Unknwon** [comment]
Close as implemented.
