### ISSUE TITLE
Can't push then 500 error (started with docker)

### ISSUE THREAD

**Issue by peez80** [gogits/gogs#2671]
I just found gogs and like it.
I'm running it via Docker but Unfortunately I can't push once I'm using volume mapping - no matter if it's host volume or a data volume.

Everything looks good until I do the first push to the repository.	

git push fails with this message:

```
! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'https://git.myurl.de/peez/test10.git'
```

gogs log looks good in my opinion:
```
[Macaron] Started GET /peez/test10.git/info/refs?service=git-receive-pack for 82.135.90.50
2016/02/21 07:44:02 [D] Session ID: bc7a05ec841629d4
2016/02/21 07:44:02 [D] CSRF Token: bdXzYMyADk7FRdxqDC6wvUh7xz06MTQ1NjA0MDY0Mjc4NzMzMzY1NA==
[Macaron] Completed /peez/test10.git/info/refs?service=git-receive-pack 401 Unauthorized in 3.69792ms
[Macaron] Started GET /peez/test10.git/info/refs?service=git-receive-pack for 82.135.90.50
2016/02/21 07:44:02 [D] Session ID: 7758078be843c370
2016/02/21 07:44:02 [D] CSRF Token: SPKUnGBgvtlU48qmj9Ev8PicfXQ6MTQ1NjA0MDY0Mjc5NTQyNDQ1NA==
[Macaron] Completed /peez/test10.git/info/refs?service=git-receive-pack 200 OK in 140.650544ms
[Macaron] Started POST /peez/test10.git/git-receive-pack for 82.135.90.50
2016/02/21 07:44:03 [D] Session ID: 312c165b8db1278a
2016/02/21 07:44:03 [D] CSRF Token: wTLva_S8E7AY5SGty8eAaljIuws6MTQ1NjA0MDY0MzA5NDEyNjA3Ng==
2016/02/21 07:44:03 [T] DeliverHooks [5]: processing delivery hooks
2016/02/21 07:44:03 [T] AddTestPullRequestTask[head_repo_id: 5, head_branch: master]: finding pull requests
[Macaron] Completed /peez/test10.git/git-receive-pack 200 OK in 234.686399ms
2016/02/21 07:44:03 [T] AddTestPullRequestTask[base_repo_id: 5, base_branch: master]: finding pull requests
```

After this I see a commit at gogs dashboard but when navigating to the repo I get a 500 error. Gogs log says this:
```
2016/02/21 07:46:44 [...s/middleware/repo.go:198 func1()] [E] GetBranches: exit status 1
2016/02/21 07:46:44 [D] Template: status/500
[Macaron] Completed /peez/test10 500 Internal Server Error in 25.735483ms
```

When not using volume mappings at all everything works fine but doing this isn't a good idea when you want to keep your data persistent ;)

Any ideas on this?

Running on ubuntu 14 host with docker 1.10. This is my start command:
```
docker run -itd --name gogs \
	-v /mnt/E/dockervolumes/gogs:/data \
	-p 44807:3000 \
	gogs/gogs:latest
```

**Comment by Unknwon** [comment]
Can you check `path/to/volume/log/serv.log` see if any errors there?

**Comment by peez80** [comment]
There is no serv.log. Only gogs.log with the GetBranches error above.

**Comment by Unknwon** [comment]
OK, the main problem is `! [remote rejected] master -> master (hook declined)`, you would have to let git accept your push, otherwise, Gogs can't read anything... 

From your description, I think post-receive rejected your push somehow.

**Comment by Unknwon** [comment]
I see you use `/mnt` so maybe it's hook execution permission problem when you mount?

**Comment by peez80** [comment]
This behaviour is on every repo I create directly after creation. I don't enter any hooks in my test repos. Additionally the repo seems to be damaged (because of the push event in the dashboard but 500 when klicking on the repo). So probably this error message is somehow misleading by the git client?

If it really was some hook problem, shouldn't I see something about that in the log? 
I'm not absolutely sure about the permissions... The files in the volume have the same permissions as they have when starting the container without volume mounts (gogs data: uid 1000, ssh dir: uid 0).

**Comment by Unknwon** [comment]
Try to mount to local file system?

**Comment by peez80** [comment]
Yes
The /mnt path is a relic from the time I migrated my server from windows and tried to find an appropriate path for "Drive E". But it's a fixed disk, fstab:

```
UUID=270bdd2f-13ed-4600-8260-31200ec1ac09 /mnt/E ext4 defaults,noatime,errors=remount-ro 0 1
```

**Comment by peez80** [comment]
Btw. the same behaviour happens when I use a docker data volume.

**Comment by Unknwon** [comment]
Are you pushing by HTTP or SSH?

**Comment by Unknwon** [comment]
When `hook declined`, that means one of the Git hooks exit with non-zero status.

And if no errors reported by Gogs, that means it is not `update` hook.

Please check every possible permission and read the link I posted above.

**Comment by Unknwon** [comment]
Maybe @0rax can help a bit more?

**Comment by peez80** [comment]
I'm pushing by HTTP.
Hm... According to the link everything looks good. I also checked the permissions already by comparing file permissions inside a container running without volume mount and one container with mounts, but all permissions are the same.

**Comment by Unknwon** [comment]
According to the doc, give a try with `exec` permission?

> UUID=270bdd2f-13ed-4600-8260-31200ec1ac09 /mnt/E ext4 defaults,noatime,errors=remount-ro 0 1

And can you test with a directory without `/mnt` as well?

**Comment by peez80** [comment]
Gave both a try but with same behaviour. :-(

**Comment by peez80** [comment]
The behaviour is reproducible. Just tried it on a clean new docker-machine VM to make sure it's not related to my server:

1. create docker machine:
```
docker-machine create ...
```

2. inside docker machine:
```
docker run --name=gogs-data --entrypoint /bin/true gogs/gogs
docker run --name=gogs --volumes-from gogs-data -p 3000:3000 gogs/gogs
```

3. create new repository in gogs UI

4. follow the instructions on the repository home page:
```
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin http://192.168.99.100:3000/peez/test16.git
git push -u origin master
```

**Comment by thetooth** [comment]
I have the exact same issue upgrading from 0.7 to 0.8.39.0219, it def something broken in the new version.

Also missing serv.log, nothing odd in any of the log files that are there except for:
`2016/02/21 20:03:13 [...s/middleware/repo.go:198 func1()] [E] GetBranches: exit status 1`

A have a few repos on this installation, after the upgrade they were all fine, but now each time you push that repo is broken, 500 on the UI and pulls/pushes all fail with the same error message. So the only option now is to use the older version.

**Comment by 0rax** [comment]
@peez80 Just tested with a brand new VM & the latest version of the container (master) and wasn't able to reproduce this with Docker 1.10.1 (latest boot2docker) using your [method](https://github.com/gogits/gogs/issues/2671#issuecomment-186797364).

You can see my tests here: [screenshot 1](https://cloud.githubusercontent.com/assets/2822534/13219797/2c0a3b04-d96a-11e5-91c4-38fb425cab88.png) & [screenshot 2](https://cloud.githubusercontent.com/assets/2822534/13219796/2c09e9e2-d96a-11e5-853d-59e581432ffe.png)

Can I get the output of your `docker info` please and maybe your `conf/app.ini` so I can better recreate such a case ?

@thetooth will check doing such an upgrade and see what can cause that, will keep your informed here.

**Comment by bemayr** [comment]
Maybe it helps if I add my results in analyzing this problem.
I set up a Gogs Instance with Docker last week (on virtualbox) and it worked without any problems. Today I moved to digitalocean and got the exact same error as @peez80 described.

My Gogs configuration:
- *virtualbox*: Gogs Version: 0.8.37.0217 & Gogs Version: 0.8.39.0219 (tried both)
- *digitalocean*: Gogs Version: 0.8.39.0219

My Docker configuration:
- Docker version 1.10.1, build 9e83765
- docker-compose version 1.6.0, build d99cad6
- https reverse proxy via [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) (http on virtualbox)

I use the following docker-compose.yml file:
```yml
version: "2"
volumes:
    data:
        driver: local

services:
    gogs:
        container_name: gogs
        image: gogs/gogs
        restart: always
        network_mode: "bridge" # used for reverse-proxying
        volumes:
            - data:/data
        environment:
            - ... # reverse-proxy variables
```

After 8.37 did not work on virtualbox I tried to go to 8.39 by `docker-compose pull` without removing my data. The same error occured, so I rebuilt your setup @0rax and with removing the data-volume and doing a fresh `docker-compose up -d` and after initializing Gogs and a test-repo the same error happened again. Really weird...

[app.ini.txt](https://github.com/gogits/gogs/files/141086/app.ini.txt)
[docker-info.txt](https://github.com/gogits/gogs/files/141087/docker-info.txt)


### temporary solution
I found #2646 and decided to go back to *Gogs Version: 0.8.25.0129* and with that version everything works as expected. (BTW: Gogs is awesome!)

**Comment by 0rax** [comment]
Okay thanks for your information will try to reproduce this on Digital Ocean then ! Keep your informed here.

**Comment by thetooth** [comment]
We're also on Digital Ocean behind jwilder/nginx-proxy + cloudflare, so may be something to do with that that specific scenario, could also just be a coincidence. This is using the Ubuntu 14.04.3 LTS image with Docker 1.9.1

**Comment by peez80** [comment]
Just pulled the newest version. Everything's working fine now.

**Comment by Unknwon** [comment]
@peez80 :joy: I don't what noticeable things are changed.

**Comment by peez80** [comment]
Funny ;) Nothing changed on my side either. Not even a reboot and used exactly the same start script that pulls and runs gogs/gogs:latest.

**Comment by Unknwon** [comment]
Any updates on this?

**Comment by peez80** [comment]
It's still working reliably at my site. Sorry I forgot to close the issue. Will do it now ;)

**Comment by Unknwon** [comment]
:sweat_smile:

**Comment by JefferyKu** [comment]
HI,
I got the similar issue. 
Do you use nginx for your server? 
I guess the matter is on the path-"one of a path of nginx configuration different to one of a path of gogs container".  
Anyway, I give it up. A way is to delete the hooks folder inside of your local repositories(inside of the .git this hidden folder.). Then, you are able to make git push work.
