### ISSUE TITLE
Ability to import a git repository

### ISSUE THREAD

**Issue by JokerQyou** [gogits/gogs#2675]
It would be nice to be able to import an external git repository. It's like mirroring an external git repository, but do it only once after creating a project in gogs.
This is useful for this scenario:
- I have a project template as a git repository
- I want to start a new project using this template

**Comment by royalterra** [comment]
what do you means? I can import repository from github in my private gogs

**Comment by JokerQyou** [comment]
I'm so sorry. I have not been using gogs for quite a while and I failed to do so. Sorry again.

**Comment by Unknwon** [comment]
:joy:

**Comment by jhnferraris** [comment]
@royalterra How did you do it? Is there a button in Gogs to allow me to transfer a git repository from github to our gogs?

**Comment by Unknwon** [comment]
@jhnferraris "New Migration"
