### ISSUE TITLE
Panic with bad .gitmodules file

### ISSUE THREAD

**Issue by gramakri** [gogits/gogs#2677]
Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.8.25
- Git version: 2.5.0
- Operating system: Cloudron
- Database:
  - [ ] PostgreSQL
  - [ X ] MySQL
  - [ ] SQLite
- Log gist:
```
20:53:10 [main] [Macaron] PANIC: runtime error: slice bounds out of range
20:53:10 [main] /usr/local/go/src/runtime/panic.go:423 (0x433d89)
20:53:10 [main] /usr/local/go/src/text/template/exec.go:100 (0x50e71b)
20:53:10 [main] /usr/local/go/src/runtime/asm_amd64.s:437 (0x46512e)
20:53:10 [main] /usr/local/go/src/runtime/panic.go:423 (0x433d89)
20:53:10 [main] /usr/local/go/src/runtime/panic.go:18 (0x4322c9)
20:53:10 [main] /home/vagrant/go/src/github.com/gogits/git-module/submodule.go:54 (0x81e1c5)
20:53:10 [main] /usr/local/go/src/runtime/asm_amd64.s:438 (0x4651ce)
20:53:10 [main] /usr/local/go/src/reflect/value.go:432 (0x928caa)
20:53:10 [main] /usr/local/go/src/reflect/value.go:300 (0x927971)
```
## Description
Gogs has a PANIC when loading repositories with bad .gitmodules. See https://git.girish.in/hacks/xembedoffscreen.

The .gitmodules files in the repo has the following content. The url is not valid (the server doesn't exist anymore).
```
[submodule "npploader"]
	path = npploader
	url = git+ssh://git@git.forwardbias.in/npploader.git
```
...

**Comment by gramakri** [comment]
You can get hold of the repo by
```
git clone ssh://git@git.girish.in:29418/hacks/xembedoffscreen
```

**Comment by Unknwon** [comment]
Thanks your feedback!

Maybe this is same as https://github.com/gogits/gogs/issues/1926?

**Comment by gramakri** [comment]
@Unknwon From the code at https://github.com/gogits/git-module/blob/e092efdab2c2e03bcda02f8d838fa829ac4b64e3/submodule.go#L50, the issue is reproduced as:
```
	url := "git+ssh://git@git.forwardbias.in/npploader.git"
	i := strings.Index(url, "@")
	j := strings.LastIndex(url, ":")
	
	fmt.Println("Hello, playground", url[i+1:j])
```

Maybe a hotfix is to change https://github.com/gogits/git-module/blob/e092efdab2c2e03bcda02f8d838fa829ac4b64e3/submodule.go#L52 to have ```&& i < j``.

**Comment by Unknwon** [comment]
Code pushed, please do `go get -u github.com/gogits/git-module` and recompile Gogs.

**Comment by gramakri** [comment]
Seems to work, thanks!

**Comment by Unknwon** [comment]
:+1:
