### ISSUE TITLE
SMTP Authentication not working / Error: Login sourcs is unknown

### ISSUE THREAD

**Issue by wackerm** [gogits/gogs#2678]
Infos:
- Gogs version (or commit ref): 0.8.31.0205
- Git version: 1.7.10.4
- Operating system: Debian Wheezy
- Database: MySQL

We would like to use SMTP authentication agains our own mailserver (postfix/dovecot) with enabled encryption (StartTLS, skip verify, SMTP authentication is active).

Even with log level "trace" the error log contains (beside session and csrf tokens) only one line:
`[...routers/user/auth.go:65 SignInPost()]  [E] UserSignIn: Login source is unknown`

On GUI: "500"

In the remote mail server log there are these lines:
`connect from gogs[10.0.0.111]`
`lost connection after EHLO from gogs[10.0.0.111]`
`disconnect from gogs[10.0.0.111]`

We were checking the connection and are able to login via startssl (checked via openssl) from the gogs host.

Any hints where to look further?

**Comment by Unknwon** [comment]
Hi, are you able to edit and update this SMTP authentication?

The error looks like you have wrong value in database.

**Comment by wackerm** [comment]
yes i am able to update this and checked it multiple times..
i will now reinstall gogs from scratch

**Comment by Unknwon** [comment]
If possible, can you check database table `login_source` and find out what value of field `type` is?

**Comment by wackerm** [comment]
```
mysql> select * from login_source;
+----+------+------+------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| id | type | name | is_actived | cfg                                                                                                                                         | created             | updated             |
+----+------+------+------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
|  1 |    3 | SMTP |          1 | {"Auth":"PLAIN","Host":"10.5.5.10","Port":587,"AllowedDomains":"example.com,example.de","TLS":true,"SkipVerify":true}                       | 2016-02-19 13:41:38 | 2016-02-22 18:25:46 |
+----+------+------+------------+---------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

**Comment by Unknwon** [comment]
The type value is correct... let me check.

**Comment by Unknwon** [comment]
I just tested by adding Gmail as SMTP login source and it works.

Maybe you have some information that have not shared?

**Comment by Unknwon** [comment]
ping @wackerm

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by wackerm** [comment]
Problem solved!

Sorry, I've been busy these days..
Since there is a new version 0.90, i completely purged gogs and reinstalled it from binaries...
but we still it seemed i could not use smtp-auth, the error persisted. on the fronted there is no more "500" but "Username or password is not correct." an in the gogs.log:
``2016/03/12 17:52:47 [W] Failed to login 'xyz@example.de' via 'SMTP': Login source is unknown``

I found out, the error was indeed not on the gogs side, but in the configuration of postfix: since i configured the gogs-servers ip in "my_network" (watch the value at ``smtpd_sasl_exceptions_networks``) postfix did not offer any auth method (plain, login,...) to gogs. 
i changed it and.... smtp-auth in gogs is working! nice!

Just the error-message from gogs could have been a bit more clear on this error ;-)

**Comment by Unknwon** [comment]
> I found out, the error was indeed not on the gogs side, but in the configuration of postfix: since i configured the gogs-servers ip in "my_network" (watch the value at smtpd_sasl_exceptions_networks) postfix did not offer any auth method (plain, login,...) to gogs. 
i changed it and.... smtp-auth in gogs is working! nice!

Thanks for the info!

So basically the login attempt was failed, right?

**Comment by wackerm** [comment]
The login failed, because the remote smtp server did not provide any auth method.  But in the logs there was only the error message "Login source is unknown"...

**Comment by Unknwon** [comment]
But your database filed value was wrong, right?

**Comment by wackerm** [comment]
no the database field was correct, see above...

**Comment by Unknwon** [comment]
Completely lost... :sob:

**Comment by dadosch** [comment]
I'm having this issue as well. Because Gogs and the mail server run on the same host, Postfix isn't offering the possibility to check the entered credentials. The way @wackerm solved this problem, to remove the own host from the list of "mynetworks", isn't any practical at all, because then every (system) user would need a password too.
I suggest the possibility to authenticate against IMAP (ie to Dovecot).

**Comment by Unknwon** [comment]
@dadosch 

>I suggest the possibility to authenticate against IMAP (ie to Dovecot).

You can file a new issue for this feature request, but I'm not sure if Go has IMAP package support yet.
