### ISSUE TITLE
Duplicates in Pull requests

### ISSUE THREAD

**Issue by mvasu** [gogits/gogs#2680]
- Gogs version (or commit ref): 0.8.10.1217
- Git version: 2.4.1
- Operating system: linux
- Database: MySQL

Creation of pull requests duplicated. we found when we create a pull request, a duplicate with the same number also gets created and it does not happen frequently. When we merge one of the pull request, it is successfully merged and closed, but the duplicate still exists in open pull request queue and the status is merged. We have to manually update the status of the pull request manually in DB and the duplicate PR gets in to closed queue. It would be great, if we have an immediate solution addressing this issue.

![image](https://cloud.githubusercontent.com/assets/8197541/13229438/df69302a-d955-11e5-94aa-6a572ce2d953.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

But 0.8.10 was released quite a while ago, and I remember someone reported before, but can't find it on GitHub at the moment.

I suggest you first upgrade to 0.8.25 and see if problem still occurs (though we can't fix ones already broken).

**Comment by Unknwon** [comment]
ping @mvasu

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by jmbello** [comment]
Hi, i am facing similar behavior, i made a PR, merged and closed, but still is showing as open. But, is not showing duplicate as first reporter. I'm using unity, git client 2.8.1 and gogs 0.9.3

![pic1](https://cloud.githubusercontent.com/assets/7688401/17518662/d20e0040-5e16-11e6-83e5-5bd593db4b04.png)

![pic2](https://cloud.githubusercontent.com/assets/7688401/17518671/d78892ba-5e16-11e6-9d64-71935b0b0a9f.png)

**Comment by Unknwon** [comment]
@jmbello this could happen in early 0.9.* version, so I can't help you anything right now..

**Comment by jmbello** [comment]
ok. anyway could you tellme where to update that PR to closed? I cannot do any PR in that branch

**Comment by Unknwon** [comment]
In `issue` table, find where `index` is `40`, then set `is_closed = true`.
