### ISSUE TITLE
go get meta tag only has a single slash

### ISSUE THREAD

**Issue by mattddowney** [gogits/gogs#2682]
- Gogs version (or commit ref): 0.8.42.0222
- Git version: 2.5.3
- Operating system: ubuntu 16.04
- Database: SQLite

## Description

Having a problem with go get.
Adding ?go-get=1 to the end of the URL and inspecting results in the following meta tag:

```
<meta name="go-source" content="redacted.local/redacted/redacted _ http:/redacted.redacted.local/redacted/redacted/src/master{/dir} http:/redacted.redacted.local/redacted/redacted/src/master{/dir}/{file}#L{line}">
```

Not sure why there would be only a single slash after the protocol, but this is the only thing I can think of that would be causing go get to fail.

Thanks for the excellent system, it's been working great for us.

**Comment by mattddowney** [comment]
Reproducable on http://try.gogs.io:

```
curl --silent https://try.gogs.io/thecanadianbaker/test-repo?go-get=1 | grep go-source
```

Produces:

```
<meta name="go-source" content="try.gogs.io/thecanadianbaker/test-repo _ https:/try.gogs.io/thecanadianbaker/test-repo/src/master{/dir} https:/try.gogs.io/thecanadianbaker/test-repo/src/master{/dir}/{file}#L{line}">
```

**Comment by Unknwon** [comment]
Thanks your feedback!

But I don't understand the problem here? 

> Not sure why there would be only a single slash after the protocol, but this is the only thing I can think of that would be causing go get to fail.

What is your definition of `fail`? And what URL you're trying to `go get`?

**Comment by mattddowney** [comment]
Upon closer inspection, this appears related to bad TLS configuration on my part:

```
matt@CO-IT-026-ubuntu:~$ go get -v codehost.empereon.local/matt.downey/go-get-test
Fetching https://codehost.empereon.local/matt.downey/go-get-test?go-get=1
https fetch failed.
import "codehost.empereon.local/matt.downey/go-get-test": https fetch: Get https://codehost.empereon.local/matt.downey/go-get-test?go-get=1: dial tcp 172.21.11.60:443: getsockopt: connection refused
package codehost.empereon.local/matt.downey/go-get-test: unrecognized import path "codehost.empereon.local/matt.downey/go-get-test"
```

It should work with -insecure, but gogs does not supply the meta tags when using http:
```
matt@CO-IT-026-ubuntu:~$ go get -v -insecure codehost.empereon.local/matt.downey/go-get-test
Fetching https://codehost.empereon.local/matt.downey/go-get-test?go-get=1
https fetch failed.
Fetching http://codehost.empereon.local/matt.downey/go-get-test?go-get=1
Parsing meta tags from http://codehost.empereon.local/matt.downey/go-get-test?go-get=1 (status code 504)
import "codehost.empereon.local/matt.downey/go-get-test": parse http://codehost.empereon.local/matt.downey/go-get-test?go-get=1: no go-import meta tags
package codehost.empereon.local/matt.downey/go-get-test: unrecognized import path "codehost.empereon.local/matt.downey/go-get-test"
```

Seems I need to configure TLS and then pass port 443 to the docker container.

**Comment by Unknwon** [comment]
Just pushed a fix for the `slash` thing to `develop` branch, and updated https://try.gogs.io as well.

And Gogs does not care you use TLS or not, as long as you have `?go-get=1`.

![image](https://cloud.githubusercontent.com/assets/2946214/13242393/37e570f8-d9c2-11e5-90ed-65bafd568bfe.png)

**Comment by Unknwon** [comment]
Close as fixed.
