### ISSUE TITLE
Wrong SSH-URL (:CloneLink.SSH) in templates with gogs-ssh-server and NAT-Firewall

### ISSUE THREAD

**Issue by genofire** [gogits/gogs#2687]
Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.8.43.0223
- Git version: -
- Operating system: -
- Database:
  - [x] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Log gist: -

## Description
The Template `CloneLink.SSH` is wrong after firewall (PAT).
There should be a settings for gogs own sshport `SSH_PORT_GOGS` and the public ssh port `SSH_PORT`.
(Maybe for users too: `RUN_USER` and `SSH_USER`)

_(Hope the description is okay)_

**Comment by Unknwon** [comment]
Thanks your feedback!

> The Template CloneLink.SSH is wrong after firewall (PAT).
There should be a settings for gogs own sshport SSH_PORT_GOGS and the public ssh port SSH_PORT.
(Maybe for users too: RUN_USER and SSH_USER)

Actually, I have no idea what is going on for your situation...

**Comment by genofire** [comment]
Installation and used urls:
```
server      <----------->      router      <----------->  inet
open-ssh: 22                  8080 <- ssl -> 443        http-url: https://gog.examp.le
gogs-web: 8080             8082 <- pat -> 22          ssh-url: git@gog.examp.le
gogs-ssh: 8082
```

Installation and showed urls
```
server      <----------->      router      <----------->  inet (happen)
open-ssh: 22                  8080 <- ssl -> 443         http-url: https://gog.examp.le
gogs-web: 8080             8082 <- pat -> 22          ssh-url: ssh://nobody@gog.examp.le:8082/
gogs-ssh: 8082
```

APP.INI:
```
RUN_USER=nobody
[server]
ROOT_URL = https://gog.examp.le/
HTTP_ADDR = 127.0.0.1
HTTP_PORT = 8080
DISABLE_SSH = false
START_SSH_SERVER = true
SSH_PORT = 8082
```

Needer a section for the web templates in app.ini
(instatt of manuiplate the templates at own,like i do it now):
```
[templating]
SSH_USER=git
SSH_PORT=22
```

With pleasure :)
Do you know what i mean?

**Comment by Unknwon** [comment]
Thanks for the details.

But what is the problem exactly?

**Comment by genofire** [comment]
Helps this?:

![gogs-wrong-urls](https://cloud.githubusercontent.com/assets/6905586/13334052/3f05904e-dc0a-11e5-995a-6862d1efd763.png)

**Comment by Unknwon** [comment]
@genofire Thanks.

But what I don't know is what is the expected value, and what is Gogs currently presenting?

**Comment by genofire** [comment]
Expected: `git@gog.examp.le`
Current presenting: `ssh://nobody@gog.examp.le:8082/`

**Comment by Unknwon** [comment]
Thanks.

> Gogs version (or commit ref): 1.5.2 (master)

There is no such version: 1.5.2.

Upgrade to latest `develop` branch, then you can follow [this post](https://discuss.gogs.io/t/how-to-config-ssh-settings/34) to solve your problem.

**Comment by genofire** [comment]
You are right, it is 1.5.3
Nothing matter.

The Post did not help.
[server] `SSH_PORT` defines which port the SSH service is listening on, this port number is used to be exposed in clone URL. 

This Parameter should splitted in two, on for where the service listening on and the other for the exposed clone URL. (Sometime there is a port address translateion (PAT) https://en.wikipedia.org/wiki/Network_address_translation#MASQUERADING)

**Comment by Unknwon** [comment]
>You are right, it is 1.5.3

No such version either, Gogs not even reach 1.0. :flushed:

From post:

> ## Use built-in SSH server
> ...
> By default, it listens on the same port as exposed in the clone URL, you can change the listening port through config option [server] SSH_LISTEN_PORT to 2222 or whatever.

Please finish reading before talking.

**Comment by genofire** [comment]
With:
```
SSH_PORT = 22
SSH_LISTEN_PORT = 8082
```
I got:
```
Feb 26 18:33:27 web sh[14568]: 2016/02/26 18:33:27 [I] Run Mode: Production
Feb 26 18:33:27 web sh[14568]: panic: listen tcp 0.0.0.0:22: bind: permission denied
```

And with this:
```
[server]
SSH_PORT = 8082
SSH_LISTEN_PORT = 22
```

i got the wrong url:
`ssh://nobody@gog.examp.le:8082/`
----
I got it - i ready the go version (i updated to : 0.8.43.0223)

**Comment by genofire** [comment]
If it will work, is there a option to change the user in then url `nobody` is not beautiful.
But it need to be nobody in `RUN_USER`.

**Comment by Unknwon** [comment]
Sorry I edited my last comment but stated in the beginning of the post:

>This post is based on Gogs 0.8.44.0225.

Also stated in my previous comment:

> Upgrade to latest `develop` branch, then you can follow this post to solve your problem.

---

> I got it - i ready the go version (i updated to : 0.8.43.0223)

It is not Go version, it is Gogs version.

---

Not sure why you keep skipping my comments? ....

**Comment by genofire** [comment]
Now i got it, it's late here sry.
But what is with the username?

**Comment by Unknwon** [comment]
@genofire you cannot change `nobody` unless you change the user you run Gogs.

**Comment by genofire** [comment]
the build in ssh-server except every username, why should be not the shown url username a other like gogs run with?

**Comment by Unknwon** [comment]
@genofire what username you're talking?

**Comment by genofire** [comment]
in the shown ssh url `ssh://nobody@gog.examp.le:8082/`

**Comment by Unknwon** [comment]
`nobody` is your `RUN_USER`, it has nothing to do with users in Gogs database, it is SSH protocol.

**Comment by genofire** [comment]
I know
```
2016/02/26 19:09:00 [...s/setting/setting.go:383 NewContext()] [E] Expect user(git) but current user is: nobody
```

**Comment by Unknwon** [comment]
You configed `git`, so you need to run Gogs use user `git`.

**Comment by genofire** [comment]
i want run it with `nobody` but shown in the clone url `git`

**Comment by Unknwon** [comment]
@genofire no, it is not possible AFAIK.

**Comment by genofire** [comment]
okay, now lets clean up the issue its so ridiculous.

**Comment by Unknwon** [comment]
:joy:

So what's now?

**Comment by genofire** [comment]
I try to build it and maybe figure out to manipulate the username (without changing the templates) for a pull request.

**Comment by Unknwon** [comment]
I don't think users will be able to connect to Gogs without same system user name (from My limited knowledge of how SSH works).

I'm closing this since right now. Have a good night!

**Comment by genofire** [comment]
i have problems with my internet connection, so i will try it to get run ... #2708 should be the solution for the username.

**Comment by Unknwon** [comment]
Thanks, but you have to test and verify first. :smiley:

**Comment by Download-Fritz** [comment]
I'm not too 'educated' in the terms of SSH either, but it should be obvious to anyone who thinks about this for longer than a minute that the name is not cosmetical. You can't just use git@ instead of @nobody and expect stuff to work (which is what the PR does). I don't know if one can make accounts on SSH (not OS) base, but I do know that you can't just pick one out of the blue.

So, create a user named 'git', run gogs on it and stop wasting your and other's time. :)

**Comment by genofire** [comment]
why we speek here? -> now i have test it.
