### ISSUE TITLE
Review access without clone permission.

### ISSUE THREAD

**Issue by Qapular** [gogits/gogs#2688]
Dear gogs server developer.
 
> Thanks for your work, I love your server.

Could you tell, is it possible to provide access for some user to review repository via web interface, without (HTTPS/SSH) cloning possibility ?

- Gogs version (or commit ref):0.8.22.0115
- Git version: 2.6.4
- Operating system: FreeBSD
- Database:
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] SQLite
- Log gist:

**Comment by Unknwon** [comment]
> Could you tell, is it possible to provide access for some user to review repository via web interface, without (HTTPS/SSH) cloning possibility ?

No... it is not possible, what is the point that someone can view your repo but can't clone?

**Comment by Qapular** [comment]
The main goal, it is some `code overview`. We need to share our code for brief architecture review. Height level design review.

**Comment by Unknwon** [comment]
If someone can view the repo, they can get the code downloaded anyway, so what is the point of not allow them to clone?

**Comment by Unknwon** [comment]
ping @Qapular

**Comment by Qapular** [comment]
Sorry for delay. 
 One of the use case is: You have software product. External company needs to get some kind of security and architecture audit of your code. They need code review before :
 a) to buy a product;
 b) to understand could they use your product? Is it safe?;
 c) You need some external code review.

In that case you don't want to provide full read - access.

**Comment by Qapular** [comment]
I understand, that you can copy&past all files from web page. But in big project with lots of modules it is really difficult.

**Comment by Unknwon** [comment]
> I understand, that you can copy&past all files from web page. But in big project with lots of modules it is really difficult.

It is a false assumption.

I don't understand business model very much, but in terms of Gogs, it is not a valid feature request...

**Comment by Qapular** [comment]
Thanks for your time.
