### ISSUE TITLE
 the web-interface does not reflect repository changes

### ISSUE THREAD

**Issue by neolit123** [gogits/gogs#2689]
hello,

my problem is pretty much described here:
https://gogs.io/docs/intro/troubleshooting.html
"Push succeeds, but the dashboard timeline doesn’t update"
but what is explained there doesn't seem to cover my use case.

i've also tried searching for similar reports to no avail.

setup:
```
- Gogs version (or commit ref):
gogs_v0.8.25_linux_amd64.zip
- Git version:
git version 1.7.9.5
- Operating system:
Ubuntu 12.04.1 LTS (almost a clean install, running in VBox)
- Database:
SQLite
```

- the first run and user setup via the web interface works great.
- i can confirm this problem:
https://github.com/gogits/gogs/issues/1306
the solution is to use full path for the remote as described in the comments.

- the push to the new repository works, the files are actually at the repository, but the web UI doesn't reflect the update.

my understanding is that some hooks are not being called. any idea how to solve the issue?

**Comment by Unknwon** [comment]
Hi,

1. How did you push?
2. Please try https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook

**Comment by neolit123** [comment]
thanks for the response,

> How did you push?

the standard steps which are shown in the web UI when a new repository is created, except with the full path tweak, as per #1306:
```
git add .
git remote add origin someuser@theserver.com:~/gogs-repositories/someuser/test.git
git push -u origin master
```
> Please try https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook

just tried the two operations and pushed a new commit to the repository.
the push succeeds and i can confirm that the commit is present in test.git, but the dashboard doesn't update.

**Comment by Unknwon** [comment]
> just tried the two operations and pushed a new commit to the repository.
the push succeeds and i can confirm that the commit is present in test.git, but the dashboard doesn't update.

Make sure you run both operations.

And check your `path/to/gogs/log/gogs.log` file.

**Comment by neolit123** [comment]
running the operations doesn't seem to update gogs.log, it remains at:
```
2016/02/24 00:38:29 [I] Log Mode: File(Info)
2016/02/24 00:38:29 [I] Cache Service Enabled
2016/02/24 00:38:29 [I] Session Service Enabled
2016/02/24 00:38:29 [I] Git Version: 1.7.9.5
2016/02/24 00:38:29 [I] SQLite3 Supported
2016/02/24 00:38:29 [I] Run Mode: Production
2016/02/24 00:38:29 [I] Listen: http://0.0.0.0:3000
```

**Comment by Unknwon** [comment]
My bad, I edited the comment, please check `path/to/gogs/log/serv.log` file.

**Comment by neolit123** [comment]
there is no serv.log, but only gogs.log, http.log (which remains always empty) and a xorm.log which does update after the operations:

before:
https://gist.github.com/neolit123/e30940d4263b8d0cda79

after:
https://gist.github.com/neolit123/4916fc45fd61036984ce

**Comment by neolit123** [comment]
i just did a:
```
$ sudo find / -name serv.log
```
and the file seems to be missing on the hard drive.

**Comment by Unknwon** [comment]
Are you still using full path to push?

**Comment by neolit123** [comment]
> Are you still using full path to push?
yes, the shortened path doesn't seem to work.

**Comment by Unknwon** [comment]
If shorthand does not work, everything after that is pointless.

**Comment by Unknwon** [comment]
What is the error for using shortpath?

**Comment by neolit123** [comment]
> What is the error for using shortpath?

```
fatal: 'XX/XX.git' does not appear to be a git repository
```

i'm now trying your SSH_ROOT_PATH suggestion, except that i don't know which path to set...should that be?:
```
SSH_ROOT_PATH = ~/gogs-repositories
```

**Comment by Unknwon** [comment]
> SSH_ROOT_PATH = ~/gogs-repositories

No, it's SSH root path, usually is `~/.ssh`, but you must give specify path, Gogs does not read env vars like `~`

**Comment by neolit123** [comment]
> No, it's SSH root path, usually is ~/.ssh, but you must give specify path, Gogs does not read env vars like ~

ok, trying it out.

**Comment by neolit123** [comment]
i've stopped the server and added the following line in app.ini:
```
SSH_ROOT_PATH = /home/myuser/.ssh
```
then restarted the server and changed the path for the remote to the short one. then tried to push, but the error is thrown again.

could this be caused by gitolite, which is also installed here?

**Comment by Unknwon** [comment]
After change the configuration, do the same operations asked by https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook

**Comment by neolit123** [comment]
same push error after running the two operations.

**Comment by Unknwon** [comment]
Please dump your `~/.ssh/authorized_kesy` file here.

**Comment by neolit123** [comment]
it's actually empty, for some odd reason.

**Comment by Unknwon** [comment]
That means `myuser` is the not the user you run Gogs.

**Comment by neolit123** [comment]
well, the folder "gogs-repositories" was created in /home/myuser.
so there must be something else.

**Comment by Unknwon** [comment]
The problem is very clear, Gogs is not generating `authorized_keys` file to right place, either you run with wrong user, or you have wrong configuration.

**Comment by neolit123** [comment]
here is the configuration:
https://gist.github.com/neolit123/104c9359a9b0054a905d

the is the same as far as i can tell.

**Comment by Unknwon** [comment]
Please try https://gogs.io/docs/intro/troubleshooting#connect-to-wrong-sqlite3-database

**Comment by neolit123** [comment]
- stopped the server
- modified the DB path to be "/home/lubo/gogs/data/gogs.db"
- started the server and ran the two operations
- authorized_keys is still empty

**Comment by Unknwon** [comment]
Content of  `/home/lubo/.ssh/authorized_keys` is empty?

**Comment by neolit123** [comment]
> Content of /home/lubo/.ssh/authorized_keys is empty?

yes

**Comment by Unknwon** [comment]
Did you really add public key to Gogs?

**Comment by Unknwon** [comment]
Also, if the authorized_keys file is empty, how you able to SSH it?

**Comment by neolit123** [comment]
that's a good set of questions. the only user of this machine is "lubo", and i have zero why the full path SSH push works.

**Comment by neolit123** [comment]
i'm laying this issue to rest for today, as it's 2AM. will check it out again tomorrow.

**Comment by neolit123** [comment]
the cause was a bad copy-paste of the text in "id_rsa.pub"...
the short path push works for me now, so thanks for the help.

for any of the users that reported in #1306 some of the steps in this thread might help.

**Comment by Unknwon** [comment]
>  i have zero idea why the full path SSH push works.

Because then you bypass the Gogs to do push through normal SSH operations.

> the cause was a bad copy-paste of the text in "id_rsa.pub"...

How bad....?

**Comment by neolit123** [comment]
> How bad....?

i pretty much chopped part of the key, for some reason.

**Comment by Unknwon** [comment]
.............................. :flushed:

**Comment by neolit123** [comment]
it *can* happen if you are doing many things at once! :)
sorry for your troubles. tomorrow i'm going to recommend gogs over gitlab to a certain group of people as the performance is simply horrible with gitlab, while being great with gogs.

**Comment by Unknwon** [comment]
> tomorrow i'm going to recommend gogs over gitlab to a certain group of people as the performance is simply horrible with gitlab, while being great with gogs.

This how the help reflects its value :eyes:
