### ISSUE TITLE
Remembering Milestone/Label on Issues Page

### ISSUE THREAD

**Issue by nuss-justin** [gogits/gogs#269]
Hi,

when navigating the issues page of a repository, I noticed that the selected label and/or milestone gets lost, when I filter issues (e.g. switching to closed issues).

I didn't test it with navigation between page, so I don't know if this also applies there (e.g. page 2).

I'd really like to see my labels/milestones getting rembembered while navigating the issues page. (Probably by appending them to each URL or using something like local storage)

**Comment by Unknwon** [comment]
Has been fixed in v0.6.3 release.
