### ISSUE TITLE
IP whitelist for REQUIRE_SIGNIN_VIEW

### ISSUE THREAD

**Issue by mkoitka** [gogits/gogs#2690]
If using _REQUIRE_SIGNIN_VIEW = true_ it would be nice to have the possibility to set this option to _false_ for some defined IP addresses.

Example option:
_SIGNIN_VIEW_EXCLUSIONS = 192.168.1.0/24, 192.168.2.5_

If this does make sense as an official feature and it is technically possible to implement I could have a look at it and create a pull request.

**Comment by Unknwon** [comment]
Thanks your feedback!

But what is the use case?

**Comment by mkoitka** [comment]
An organization has a Gogs instance that should require a sign-in by default to view the repositories.
For convenience reasons users with a specific IP address/within an IP range should not have to sign in to view all repositories. Please note that there is no LDAP/Auth server in reach which could be used, so that is no option.

**Comment by Unknwon** [comment]
Thanks for clarifying!

**Comment by mkoitka** [comment]
So, you think it's technically possible to implement and worth an official feature? If yes I would take the chance to dig into Go for the first time and create a pull request when I have some spare time.

**Comment by Unknwon** [comment]
Yes, I have some ideas about how to implement that, but it might be difficult to write actual code.

**Comment by mkoitka** [comment]
Okay, thanks. That's good to know. I will have a look what I can contribute to that.

**Comment by 0xbaadf00d** [comment]
You can already filtering access by IP by using Nginx (for instance, you could use another Http serverà has reverse proxy.
