### ISSUE TITLE
SSH config doesn't update on RUN_USER change

### ISSUE THREAD

**Issue by jlsjonas** [gogits/gogs#2691]
- Gogs version (or commit ref): 0.8.25.0129
- Git version: 1.8.4
- Operating system: OS X 10.11.3
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Log gist: (pretty sure the logs won't do any good, but do request them if required)

## Description

after testing gogs using my own user account I decided to make a git user for it, and move permissions & config over there. However it seems that gogs made permanent changes to my ssh login(1), and doesn't make those changes for the changed username(2); this results in me being unable to use ssh when running gogs under the new "git" user, and me being unable to use regular ssh on my own account

when logging in on my own account, with gogs configured for the git user:
`PTY allocation request failed
2016/02/23 21:30:15 [...s/setting/setting.go:378 NewContext()] [E] Expect user(git) but current user is: jonas`

when logging in using the git account, expecting to get:
`PTY allocation request failed
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.`
I'm getting prompted for my password, which (after entering) logs me in to the newly created git account

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think documentation already proposed how to solve this: https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook

**Comment by jlsjonas** [comment]
Hi, I looked over that title indeed, is does fix the ssh hook for the git user

HOWEVER my regular user ssh is still crippled, even after manually removing the command= & options= part in my authorised_keys file (I knew it must've been somewhere, but couldn't find it)
and after restarting ssh (to be safe)

any ideas for that part?

**Comment by Unknwon** [comment]
> HOWEVER my regular user ssh is still crippled, even after manually removing the command= & options= part in my authorised_keys file (I knew it must've been somewhere, but couldn't find it)
and after restarting ssh (to be safe)

I don't understand the situation?

**Comment by jlsjonas** [comment]
in short:

1. configured everything under my personal user account (jonas)
2. everything worked as expected
3. moved everything to work under "git" user
4. fix in [the docs](https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook) as reported in above comment fixed git ssh
5. removed `command="/.../gogs sera key-1 --config='/.../custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty` from user "jonas" 's authorised keys file
5. logging into git using (original) "jonas" user still results in: 
`PTY allocation request failed
2016/02/24 00:07:13 [...s/setting/setting.go:378 NewContext()] [E] Expect user(git) but current user is: jonas`

**Comment by Unknwon** [comment]
> logging into git using (original) "jonas" user still results in: PTY allocation request failed 2016/02/24 00:07:13 [...s/setting/setting.go:378 NewContext()] [E] Expect user(git) but current user is: jonas

That means you are not running Gogs as user `git`, or the env var `USER` is wrong.

**Comment by jlsjonas** [comment]
to clarify 

> logging into git using (original) "jonas" user still results in: PTY allocation request failed 2016/02/24 00:07:13 [...s/setting/setting.go:378 NewContext()] [E] Expect user(git) but current user is: jonas

Happens when I issue `ssh jonas@server`

and I verified that gogs is running as git user (hence `ssh git@server` does work):

`ps aux | grep gogs
jonas           95275   0.0  0.0  2434840    780 s010  S+   12:19AM   0:00.00 grep gogs
git             92801   0.0  0.3 573469376  23160 s008  S+   11:55PM   0:00.93 ./gogs web`

**Comment by Unknwon** [comment]
> Happens when I issue ssh jonas@server

When Gogs says you're running in different user from what you config, you are. Your `.ssh/authorized_keys` file is not cleaned as you stated.

**Comment by Unknwon** [comment]
What do you get at this point of you `ssh git@server`?

**Comment by jlsjonas** [comment]
I can verify that authorized_keys is cleaned as I previously stated, containing:

> .ssh jonas$ pwd
> /Users/jonas/.ssh
> .ssh jonas$ cat authorized_keys
> ssh-rsa AAAAB3NzaC1..... my@email

as mentioned before on `ssh git@server` I get the expected: 

> PTY allocation request failed
> Hi there, You've successfully authenticated, but Gogs does not provide shell access.
> If this is unexpected, please log in with password and setup Gogs under another user.

**Comment by Unknwon** [comment]
OK, if you do `ssh jonas@server` and Gogs responses, check you SSH server config, I think it is using the wrong authorized_keys file or you think what file it is using is wrong.

**Comment by jlsjonas** [comment]
well it is that file that I've used to authenticate my key before, anyway I suppose it might be some sort of cache (on OS X's side) so I will try a complete reboot soon. Can't do that at the moment though because of other critical systems.
I will keep you posted on evolvements.

ps: I would suggest adding a line to [this article](https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook) marking that you might have to do some manual cleanup in your authorized_keys file

Thanks for the help so far, great product!

**Comment by Unknwon** [comment]
Close by https://discuss.gogs.io/t/how-to-config-ssh-settings/34/1
