### ISSUE TITLE
Clone fails (401 Unauthorized)

### ISSUE THREAD

**Issue by Zamicol** [gogits/gogs#2692]
## Relevant info
Gogs version: v0.8.25
Git version: 2.7.0.windows.1
Operating system: Windows Server 2008 R2 Standard
Database: SQLite
Last line in gogs.log: Listen: http://0.0.0.0:3000/gogs

Reversed proxied through IIS 7.5

### This is what I see on the command line output server side:

[Macaron] Started GET [repo].git/info/refs?service=git-upload-pack for [IP address]:50673
2016/02/23 14:36:26 [D] Session ID: 32ceb61ccd7132c0
2016/02/23 14:36:26 [D] CSRF Token: DUpRkQ_r7kYBSRwMijEY7P3ekmk6MTQ1NjI2MzM4NjU1
MTA5MjIwMA==
[Macaron] Completed [repo].git/info/refs?service=git-upload-pack 401
 Unauthorized in 5.0003ms

### This is what I see client side: 

git clone [repoUrl].git --verbose
Cloning into '[repo]'...
fatal: unable to access '[repoUrl].git/': The requested URL returned error: 500

I'm trying to see if there is any other way to debug this.  Nothing is really showing in the logs.  

So far everything non-git works fine.  Nothing appears in the IIS logs.

**Comment by Unknwon** [comment]
Hi, I think you did not config sub-path right.

Git receives 502 for bad gateway as I can think of.

**Comment by Zamicol** [comment]
That might be the case.  It's a 500 error, not 502.   Server side it is saying "401 Unauthorized".

It works fine when not using the proxy.

**Comment by Unknwon** [comment]
> That might be the case. It's a 500 error, not 502. Server side it is saying "401 Unauthorized".

It works fine when not using the proxy.

I think your proxy is not sending basic auth header to Gogs?

**Comment by Zamicol** [comment]
I think you are probably right.  

The logs appear sparse on information to pinpoint the problem.  Any suggestions?

**Comment by Unknwon** [comment]
Maybe this helps? http://stackoverflow.com/questions/6264878/no-basic-authentication-choice-available-in-iis7

**Comment by Unknwon** [comment]
ping @Zamicol

**Comment by Zamicol** [comment]
Thanks Unknwon, 

Basic Authentication is enabled.  I've looked through every IIS option I know of and nothing appears in the IIS logs.  Not sure how to debug from here.

**Comment by Unknwon** [comment]
If clone works without IIS, and 500 is not from Gogs, I think it must about configuration stuff. 

As I never used IIS, couldn't help very much.... sorry about that. 

It may be possible that IIS treats 401 as 500 and response to client, can you check logs from that?

I suggest we move the discussion to https://discuss.gogs.io/ since it is a deploy/config problem.

**Comment by Unknwon** [comment]
Moved discussion to https://discuss.gogs.io/t/iis-7-5-reverse-proxy-clone-fails-401-unauthorized/77
