### ISSUE TITLE
Feature request: Delete a page in gogs-wiki

### ISSUE THREAD

**Issue by seferis101** [gogits/gogs#2698]
Feature request / user story:

As a user of gogs (my version is 0.8.10.1217), I would like to delete a page from the gogs-wiki of my repository. I want to be asked by the system if I really want to delete the page, before the page is actually deleted.

Possible way to achieve this:
Provide a remove button next to the already existing buttons "Edit" and "New Page" on the wiki-page the user wants to delete. When this button is pressed a confirmation popup is shown which asks "Do you really want to delete this page?" (yes/no). If yes is chosen the page is deleted and removed from the wiki-repository. If no is chosen the confirmation popup disappears and nothing happens.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think this is duplicated to https://github.com/gogits/gogs/issues/2183
