### ISSUE TITLE
All organization's repos are visible to user

### ISSUE THREAD

**Issue by olafure** [gogits/gogs#2699]
- Gogs version: gogs_v0.8.25 linux/amd64
- Git version: 2.4.3
- Operating system: Amazon Linux 2015.09
- Database: MySQL

## Description
When a user looks at a organization on the Gogs web, he sees **all** it's repositories.  Including repositories which he doesn't have access to.  When he clicks on them, he gets an 404 error (rightly so).

Problem: he shouldn't see repos which he doesn't have access to.

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you reproduce this on https://try.gogs.io?

It should be a fixed issue already.

**Comment by olafure** [comment]
Interesting.  I can't reproduce it on try.gogs.io.  Perhaps the fix didn't make it into the latest release? Anyway, unless I report back on this it should be safe to close this issue.  Thanks for speedy response!

**Comment by Unknwon** [comment]
@olafure the latest release was 0.8.43 and published yesterday. :sweat_smile:

**Comment by Unknwon** [comment]
Close due to lack of feedback.

You can continue discussion on https://discuss.gogs.io/.
