### ISSUE TITLE
Wiki Support

### ISSUE THREAD

**Issue by MohsenK** [gogits/gogs#270]
Hi Guys.
Very Thanks for this project.
gogits supporting wiki for projects ?

**Comment by phaidros7** [comment]
any news here?

**Comment by Unknwon** [comment]
@phaidros7 Yeah, it's on the waiting list.

**Comment by krazyjakee** [comment]
I am waiting for this feature too. If anyone is in the same boat but only requires a single wiki page, don't forget you can use the readme to serve up useful information. May sound obvious but took me a while :+1:

**Comment by hermanbergwerf** [comment]
+1

**Comment by adithyank** [comment]
:+1: 
:+1: 
:+1: 
:+1:

**Comment by bastiao** [comment]
+1 :)

**Comment by adithyank** [comment]
:+1:

**Comment by matiux** [comment]
:+1:
:+1:
:+1:

**Comment by ingro** [comment]
That would be great! :+1:

**Comment by sapk** [comment]
:+1: for the wiki.
Gogs is going in the rigth way keep it up

**Comment by repejota** [comment]
:+1: Yeah! Would be so nice

**Comment by mephist** [comment]
+1

**Comment by uchti** [comment]
+1

**Comment by squarerootfury** [comment]
:+1:

**Comment by theAdmiral777** [comment]
+1

**Comment by winpat** [comment]
+1

**Comment by mozgovipc** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by linquize** [comment]
Already implemented in https://github.com/go-gitea/gitea

**Comment by HLFH** [comment]
It seems that we have to migrate to gitea. https://news.ycombinator.com/item?id=9708832

**Comment by rhaamo** [comment]
:+1:

**Comment by vijairaj** [comment]
How will wiki pages be stored - in the same repo or as a new repo?
In fact right now we can have wiki like functionality sans web based editing through a set of markdown files. IMHO all we need is the ability to create a new file, edit and commit the files through the web interface. Storing the wiki in the same repo has some advantages for collaboration as one can send pull requests for any changes in the wiki too.

**Comment by Unknwon** [comment]
@vijairaj will be a separate Git repo with only root directory with batch of files.

**Comment by Unknwon** [comment]
Backup: https://github.com/NextStepWebs/simplemde-markdown-editor

**Comment by tboerger** [comment]
The editor looks nice, maybe add it to issues as well?

**Comment by Unknwon** [comment]
issues？

**Comment by JohnMaguire** [comment]
I think he means, for example, what we're on right now, but in Gogs.

Personally I like the simplified text box -- devs probably know how to write Markdown anyway.

**Comment by tboerger** [comment]
> issues？

Taking this editor for writing issues and comments.

**Comment by tboerger** [comment]
> Personally I like the simplified text box for a lightweight page like this -- devs probably know how to write Markdown anyway.

As you can see at the demo you are still writing plain markdown that just gets a little bit different formatting but it doesn't hide the written text/markers.

**Comment by ChangePlaces** [comment]
I kinda like not having a wiki because it forces me to write documentation!

**Comment by tboerger** [comment]
> I kinda like not having a wiki because it forces me to write documentation! A wiki would be useful, but I like the idea of having it as documentation inside a repo, rather than an internal gogs feature, which really, gogs already has because you can create a docs folder and just fill it up with md files

Wiki is simply something totally different. And not all people/devs want to have this stuff together with the codebase. Different people, different requirements.

To make people like you happy there should be a per repo option to enable/disable wikis, issues and pull requests.

**Comment by mkurz** [comment]
Checkout this WYSIWYG markdown editor: http://hectorguo.com/CKEditor-Markdown-Plugin/
It is a addon for the CKEditor, see [this answer](http://stackoverflow.com/a/28373012/810109) on stackoverflow.

**Comment by Unknwon** [comment]
Thanks @mkurz Quick question: does it support customized all icon titles and render results?

**Comment by mkurz** [comment]
@Unknwon I have no idea. You can check https://github.com/hectorguo/CKEditor-Markdown-Plugin and ask the author for information about your questions.

**Comment by Unknwon** [comment]
Now on `develop` and https://try.gogs.io

**Comment by HLFH** [comment]
@Unknwon Thank you so much. You rock.

**Comment by zhuchun** [comment]
@Unknwon Super awesome! I tried GitLab and its configuration is full of pain. Gogs is perfect if it have wiki support!

**Comment by hellywangxiaoyun** [comment]
when i submited some messages in the gogs wiki, I found the others submit was disappear。then I wanted to found the Operation record，but Ican not.How could I do

**Comment by HLFH** [comment]
@hellywangxiaoyun Maybe you could open another issue.

**Comment by pwFoo** [comment]
Wiki would be great for repository related documentation and howtos!

+1

**Comment by tboerger** [comment]
> Wiki would be great for repository related documentation and howtos!
> 
> +1

And we can see that you didn't realized that this feature is implemented for ages ;)

**Comment by pwFoo** [comment]
Thanks... Searched global settings and documentation first without success...
After search again I found it inside the repo configuration...

Gogs is awesome. Looks great and works smooth.
