### ISSUE TITLE
Create issue with multiple labels throws an error 500 with sqlite3

### ISSUE THREAD

**Issue by neolit123** [gogits/gogs#2700]
```
- Gogs version (or commit ref):
 0.8.43.0223
- Git version:
git version 1.7.9.5
- Operating system:
Ubuntu 12.04.1 LTS
- Database:
SQLite
```

seems to happen only for sqlite3!

steps:
```
- create a new repository via the Web UI
- push something
- create a couple of labels for the issue tracker
- create issue
- write some text for the title and message of the issue
- add both labels on the right
- done
- error 500
```

```
repo/issue.go:427 NewIssuePost()] [E] NewIssue: newIssue: label does not exist [id: XXXXX]
# where XXXX seems to be an index out of the whole range of user labels
```

if you select only a single or no labels out of the list when creating the issue it does work.

original thread:
https://github.com/gogits/gogs/issues/1701

**Comment by sapk** [comment]
I have the same problem with sqlite (Gogs Version: 0.8.43.0223)

**Comment by Unknwon** [comment]
Hi, I just pushed a fix to `develop` branch, please help test again.

**Comment by neolit123** [comment]
hello @Unknwon, thanks for looking into this.
i need to find the time to prepare the Gogs build setup to test it, unless you can provide some sort of a daily build (which is a good idea to have on a regular basis at least for Linux-64bit and if automated properly).

in the meantime pinging @kpande, who reported the original issue to see if he has the build setup to quickly test the _develop_ branch.

**Comment by neolit123** [comment]
@Unknwon, i was able to build Gogs (0.8.49.0229) and test it with sqlite3.
the issue seems to be fixed!

**Comment by Unknwon** [comment]
@neolit123 thanks your confirmation!
