### ISSUE TITLE
Ability to config test patch timeout

### ISSUE THREAD

**Issue by congeal** [gogits/gogs#2701]
- Gogs version (or commit ref): 0.8.41.0221
- Git version:2.6.4
- Operating system: Centos 6
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Log gist:

## Description
Someone pushed a commit into a branch on PR that isn't merged.
Gogs web says 'The conflict checking is still in progress, please refresh page in few moments.'
But, after a long time, it still says the same.
Gogs in terminal says like below:
```
[.../runtime/asm_amd634.s:1721 goexit()] [E] testPatch[23]: UpdateLocalCopy: Clone: execution is time out [duration: 1m0s] - Cloning into 'data/tmp/local/1'...
done.
Checking out files: 100% (9737/9737), done.
```
I think this happens when I enter the PR page before the conflict check isn't done.

**Comment by Unknwon** [comment]
Thanks your feedback!

How large is your repository?

**Comment by congeal** [comment]
The repository size is 243MB, and it has 38638 objects and 3436 commits.
It takes 1min 30sec to clone it.

**Comment by Unknwon** [comment]
I see, you can change title of this issue to `Ability to config test patch timeout`.

**Comment by congeal** [comment]
Ok. I'll change it.
So, you might solve this issue by letting users change the timeout, right?

**Comment by Unknwon** [comment]
> So, you might solve this issue by letting users change the timeout, right?

Correct, and increase default to 5 minutes may be a good idea too

**Comment by congeal** [comment]
Ok. thanks.

**Comment by Unknwon** [comment]
Hi, now in `develop` branch, you can increase [this value](https://github.com/gogits/gogs/blob/develop/conf/app.ini#L338) and test again.

**Comment by Unknwon** [comment]
Close as implemented.
