### ISSUE TITLE
LDAP(simple auth) failed on logging in the second time (the first time was OK) with Gogs0.8.43

### ISSUE THREAD

**Issue by ufosaga** [gogits/gogs#2702]
## Description

Config the Gogs v0.8.43 with OpenLDAP simple auth. 
The ldap user can log on the first time without any problems, however the same user cannot log on again any more once logged out.

This issue does not happen with the previous v0.8.25

## Details
- Gogs version (or commit ref): 0.8.43
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.4 LTS
- Database: MySQL
- Log gist:
```
2016/02/26 15:35:01 [D] Template: home
[Macaron] Started GET /user/login for 113.235.121.216
2016/02/26 15:35:03 [D] Session ID: f4353464572117f8
2016/02/26 15:35:03 [D] CSRF Token: PnDY3roGAXOTtIp3quDpDhxMcmQ6MTQ1NjQ3MjEwMTk2MzM3MzQ2NA==
[Macaron] Completed /user/login 200 OK in 2.502751ms
2016/02/26 15:35:03 [D] Template: user/auth/signin
[Macaron] Started POST /user/login for 113.235.121.216
2016/02/26 15:35:04 [D] Session ID: f4353464572117f8
2016/02/26 15:35:04 [D] CSRF Token: PnDY3roGAXOTtIp3quDpDhxMcmQ6MTQ1NjQ3MjEwMTk2MzM3MzQ2NA==
2016/02/26 15:35:04 [T] LDAP will bind directly via UserDN template: cn=%s,ou=people,dc=wtom,dc=org
2016/02/26 15:35:04 [T] Binding with userDN: cn=thomas,ou=people,dc=wtom,dc=org
2016/02/26 15:35:04 [T] Bound successfully with userDN: cn=thomas,ou=people,dc=wtom,dc=org
2016/02/26 15:35:04 [T] Fetching attributes 'displayName', 'givenName', 'sn', 'mail' with filter (cn=thomas) and base cn=thomas,ou=people,dc=wtom,dc=org
2016/02/26 15:35:04 [W] Failed to login 'thomas' via 'OpenLDAP (simple auth)': user already exists [name: Thomas Wang]
2016/02/26 15:35:04 [D] Template: user/auth/signin
[Macaron] Completed /user/login 200 OK in 10.916977ms
...
```

**Comment by ufosaga** [comment]
It seems that the problem happens during the post process after retrieving the user info from LDAP server, in other words, the LDAP auth is not to blame.

**Comment by Unknwon** [comment]
@ufosaga I think you have a user with same username `thomas` and is the login type is not LDAP.

**Comment by ufosaga** [comment]
@Unknwon my test environment was a clean system without any duplicate user. Gogs has only a 'root' admin account before I add the LDAP source to it.

**Comment by Unknwon** [comment]
> Gogs had only a 'root' admin account before I added the LDAP source to it.

Both of them have same email addresses?

**Comment by ufosaga** [comment]
@Unknwon no, they have different email account.
Per we talked via IM, the reason was I wrongly config the `username` field which can provide the data string may contain white space. I left this field empty and the problem solved.

**Comment by Unknwon** [comment]
> Per we talked via IM, the reason was I wrongly config the username field which can provide the data string may contain white space. I left this field empty and the problem solved.

I suggest you file another issue or change the title of this issue to `Did not validate attributes fetch from LDAP`, I think username allow whitespace from LDAP is a bug.

**Comment by ufosaga** [comment]
@Unknwon Done, new issue [https://github.com/gogits/gogs/issues/2709](url) filed.
Thanks a lot for all the help.
