### ISSUE TITLE
Commits don't closing issues anymore and the dashboard shows empty notification instead of commit message.

### ISSUE THREAD

**Issue by ciruz** [gogits/gogs#2703]
- Gogs version (or commit ref):  0.8.43.0223
- Git version: latest
- Operating system: debian 8
- Database:
  - MySQL

## Description
When i commit something with one of the closing keywords (``close``, ``closes``, ``closed``, ``fix``, ``fixes``, ``fixed``, ``resolve``, ``resolves``, ``resolved``) the referenced issue gets linked, but not closed, this worked some versions ago without any problems.

___

**Commit message:**

<img src="http://i.imgur.com/jiexD6J.png">
___

**Issue gets referenced but not closed:**

<img src="http://i.imgur.com/6tDZDkM.png">

___

**Only a empty message in the Dashbaord, instead of the commit message:**

<img src="http://i.imgur.com/V817f9U.png">

___

Any ideas?

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/2697
