### ISSUE TITLE
Ability to config migration timeout

### ISSUE THREAD

**Issue by psaavedra** [gogits/gogs#2704]
- Gogs version (or commit ref): https://github.com/gogits/gogs/commit/d324500959c06e975921790f8770aa5d1bdf2344
- Git version: 2.1.4
- Operating system: Debian 8.3 into a LXC
- Database:
  - [ ] PostgreSQL
  - [ X] MySQL
  - [ ] SQLite
- Log gist:

```
2016/02/26 09:24:28 ESC[1;34m[D] Session ID: b8a23c38ff951cd9ESC[0m
2016/02/26 09:24:28 ESC[1;34m[D] CSRF Token: 9uWLR21qBEGH_sahigQcNSPjldU6MTQ1NjQwNDQ2ODA4NjA4NDgzNw==ESC[0m
2016/02/26 09:24:28 ESC[1;31m[...s/middleware/repo.go:198 func1()] [E] GetBranches: exit status 1ESC[0m
2016/02/26 09:24:28 ESC[1;34m[D] Template: status/500ESC[0m
[Macaron] Completed /psaavedra/mytest 500 Internal Server Error in 8.559002ms
```

## Description

A 550 internal error is displayed when I perform a mirroring action:

How to reproduce it:

(in the webapp) Go to : mirror -> + -> and perfrom the replica of: git://anongit.freedesktop.org/libreoffice/core

A error 500 will be registered on the log, additionally refering to some kind of problems getting the branches list.

...

**Comment by neolit123** [comment]
mirroring smaller repositories works for me on sqlite3, so it could be the massive size of the libreoffice repository.

**Comment by psaavedra** [comment]
excuse me,  bad description, the DB is MySQL

**Comment by Unknwon** [comment]
Thanks your feedback!

Same thing? https://discuss.gogs.io/t/mirroring-a-github-repository/42

**Comment by psaavedra** [comment]
Looks similar but the error  in my case is:

  `[...s/middleware/repo.go:198 func1()] [E] GetBranches: exit status 1`

**Comment by Unknwon** [comment]
@psaavedra it is the same thing when you visit a failed migration repo.

**Comment by psaavedra** [comment]
So,  is there a chance to setup that timeout in order to avoid this 500 error?

**Comment by Unknwon** [comment]
Currently, not possible.

You can title of this issue to `Ability to config migration timeout`.

**Comment by psaavedra** [comment]
OK. Title updated. Thanks again for you support.

**Comment by Unknwon** [comment]
Hi, now in develop branch, you can increase [this value](https://github.com/gogits/gogs/blob/develop/conf/app.ini#L336) and test again.

**Comment by Unknwon** [comment]
Close as implemented.
