### ISSUE TITLE
database table is locked

### ISSUE THREAD

**Issue by LukeMauldin** [gogits/gogs#2705]
- Gogs version: 0.8.25
- Git version: 2.7.1
- Operating system: CentOS
- Database: SQLite
- Log:
2016/02/25 07:11:46 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: database table is locked: repository

Occasionally when trying to create a new repository I get the error above.  Our team using Gogs is small and I am sure that there are not two people trying to create a repository at one time.  The only way I can resolve the error is to restart Gogs.  I cannot reproduce it 100% of the time but it has happened most often if I am on the repository create page for a long period of time before I hit submit and I get an error (probably due to my session timing out).  If I close my web browser, reopen Gogs and try to create another repository, then sometimes I get the error above.

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you upgrade to 0.8.43 first and test again?

**Comment by Unknwon** [comment]
ping @LukeMauldin

**Comment by LukeMauldin** [comment]
I have not experienced the problem again in Gogs 0.8.43 although the problem was intermittent before.

**Comment by Unknwon** [comment]
Thanks for following up!

Please reopen this issue if it occurs again.

**Comment by jeremyandrews** [comment]
I ran into the problem today for the first time, using Gogs 0.10.18.0313. I started to create a migration, then got distracted by other tasks for a while -- I returned to the migration creation tab and when I hit submit I got a 500 error and the above message, "An error has occurred : database table is locked: repository"

Repeatedly trying to create the migration failed with the same error. I finally restarted Gogs and everything is fine.

**Comment by jeremyandrews** [comment]
Here's what's in the logs around this time:

`2017/03/17 12:23:30 [TRACE] Template: repo/migrate
2017/03/17 12:24:08 [TRACE] Doing: CheckRepoStats
2017/03/17 12:24:08 [TRACE] Doing: MirrorUpdate
2017/03/17 12:24:08 [TRACE] Updating repository count 'num_watches': 283
2017/03/17 12:24:08 [TRACE] Doing: GitFsck
2017/03/17 12:24:08 [TRACE] Doing: DeleteOldRepositoryArchives
2017/03/17 12:28:02 [TRACE] Session ID: ....
2017/03/17 12:28:02 [TRACE] CSRF Token: ...==
2017/03/17 12:28:02 [ERROR] [...s/context/context.go:98 Handle()] MigratePost: database table is locked: repository
2017/03/17 12:28:02 [TRACE] Template: status/500
`
