### ISSUE TITLE
Did not validate attributes fetch from LDAP

### ISSUE THREAD

**Issue by ufosaga** [gogits/gogs#2709]
## Description
- Gogs version (or commit ref): 0.8.25
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.4 LTS
- Database: MySQL
- Auth type: Simple auth
- User DN: `cn=%s,ou=people,dc=test,dc=com`
- User Filter: `(cn=%s)`
- Username attribute: `displayName`

**[Step to reproduce]**
1. Config the Gogs v0.8.25 with OpenLDAP simple auth. 
2. Config the `Username attribute` with a ldap entry which can return value with white space e.g. `displayName`
3. Log in Gogs with a user which has white space in `displayName`field.

**[Expect result]**
user cannot log in

**[Actual result]**
user can login

**[Parent issue]**
https://github.com/gogits/gogs/issues/2709

**Comment by FibreFoX** [comment]
@ufosaga 
> [Expect result]
> user cannot log in
> 
> [Actual result]
> user can login

Shouldn't this be the opposite? Acual result of not being able to login?

**Comment by ufosaga** [comment]
@FibreFoX 
The expect result is indeed 'usr cannot log in' because the step 2 in the [Step to reproduce] introduce the white space, which should be able to cause the ldap auth fails.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by barracks510** [comment]
This fix did not work for me. Now, completely sane user names are blocked.

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/issues/3295
