### ISSUE TITLE
Markdown weird http link render

### ISSUE THREAD

**Issue by drym3r** [gogits/gogs#2711]
Hi,

I'm using notabug.org and I found one rendering problem. I'll give you examples sinces it's a little difficult for me to explain. 

In my [cgit repo](http://daemons.cf/cgit/gnusrss/about/#orgheadline3) webpage, you can see the Requirements section correctly rendered. But if you go to the [notabug repo](https://notabug.org/drymer/twitter2rss/src/master/README.md#sec-1-1-3), you can see there's a carriage return after the dot and before the first word, although is the same README file, since the notabug repo is just a mirror.

You can see the raw files from cgit [here](https://daemons.cf/cgit/twitter2rss/tree/README.md) and from notabug [here](https://notabug.org/drymer/twitter2rss/raw/master/README.md).

Thanks for your time.

**Comment by Unknwon** [comment]
Thanks your feedback!

However notabug.org is running very outdated version and you should report bug directly to https://notabug.org/hp/gogs/issues.

Unless you can reproduce the same problem on https://try.gogs.io

**Comment by drym3r** [comment]
Ok, I've tried on https://try.gogs.io and it's rendered ok, i'll open an issue to them. Thanks

**Comment by Unknwon** [comment]
No problem :open_hands:
