### ISSUE TITLE
Feature request: Add ability to migrate wiki when migrating a repo

### ISSUE THREAD

**Issue by sapk** [gogits/gogs#2713]
Maybe in the migration process we could (optionality) check if a repo with $reponame.wiki exist in the source and clone it as the repo wiki ?

**Comment by Unknwon** [comment]
Thanks your feedback!

But repository is not always come with a wiki. So I don't think it is a good idea.

**Comment by richmahn** [comment]
@Unknwon Would this also be applicable to forking a repo? Or is that different in its mechanics? We would like a Wiki to come along with a forked repo. It actually does in GitHub, yet you have to create a page for the upstream wiki to show up...not sure why.

**Comment by Unknwon** [comment]
@richmahn technically, yes it is possible with fork as well.

**Comment by richmahn** [comment]
@Unknwon Is it technically possible for someone with only access to the front end to fork the wiki with the repo? I can copy the wiki.git file to the other repo manually on the file systme, but not in the UI.

**Comment by Unknwon** [comment]
> @Unknwon Is it technically possible for someone with only access to the front end to fork the wiki with the repo? I can copy the wiki.git file to the other repo manually on the file systme, but not in the UI.

Out of scope of this thread. You can discuss this on the forum.

**Comment by Unknwon** [comment]
I think this is implemented already...
