### ISSUE TITLE
Coffeescript code support

### ISSUE THREAD

**Issue by casdr** [gogits/gogs#2714]
Currently, coffeescript files are recognized as raw files, it would be nice to be able to read the code in gogs itself.

**Comment by Unknwon** [comment]
Thanks your feedback!

But `Currently` is a vague word.

**Comment by casdr** [comment]
@Unknwon I'm not sure what was wrong with me yesterday, I've updated the message a bit so there is actually an issue :P

**Comment by Unknwon** [comment]
Thanks... but I still don't understand..

> Currently, coffeescript files are recognized as raw files

Can you give an example on https://try.gogs.io?

**Comment by casdr** [comment]
Weird, somehow it works now. This issue can be ignored :)

**Comment by Unknwon** [comment]
:flushed:...........
