### ISSUE TITLE
want option to create repositories by pushing to them

### ISSUE THREAD

**Issue by majewsky** [gogits/gogs#2715]
Gitolite has a nice option to create a repository when you first push to it. This would be nice for Gogs, too, so that when I want to create a new private repository, I don't need to go through the UI. I just

```bash
git remote add origin gogs@my.domain.tld:myuser/newreponame
git push -u origin master
```

**Comment by Unknwon** [comment]
Thanks your feedback!

Maybe it is a part of https://github.com/gogits/gogs/issues/1062? Or maybe not... never used Gitolite.

**Comment by majewsky** [comment]
Oh yeah, that's the same.
