### ISSUE TITLE
Download as archive button on wiki pages downloads main repo archive, not wiki archive

### ISSUE THREAD

**Issue by chriswatt** [gogits/gogs#2718]
![gogsdownloadarchive](https://cloud.githubusercontent.com/assets/488912/13382854/5134f17e-de76-11e5-9a87-6195446486b2.PNG)

**Comment by Unknwon** [comment]
I think it is actually a bug to show this button on wiki page.

**Comment by ultralisk-** [comment]
If no one else has claimed it I'll remove the hide the button.

**Comment by chriswatt** [comment]
If no one else has claimed it I'll remove the hide the button.

**Comment by Unknwon** [comment]
Fixed by #2722.
