### ISSUE TITLE
go get private repos (using application token from ~/.netrc)

### ISSUE THREAD

**Issue by martinhpedersen** [gogits/gogs#2721]
By adding an application token to `~/.netrc` it is now possible to git clone/push private repositories over https. See issue #842.

If this token authentication method was extended to include `https://{host}/{organization}/{repo}?go-get=1`, private repositories would be go get-able :)

This method works for github repositories (see ttps://coderwall.com/p/jtujgw/use-netrc-to-allow-go-get-for-private-repos).

**Comment by Unknwon** [comment]
It should be possible now.

**Comment by martinhpedersen** [comment]
I have tested with the latest release (0.9.71) and it is not working.

>package git.easyconnect.no/ec/vittorio: unrecognized import path "git.easyconnect.no/ec/vittorio" (parse https://git.easyconnect.no/ec/vittorio?go-get=1: no go-import meta tags)

Curl reveals that Gogs responds with 302 Found with a ```Location: /user/login``` even when the Authorization header is set:

```bash
curl -n -v 'https://git.easyconnect.no/ec/vittorio?go-get=1'
* Server auth using Basic with user 'my-token-from-.netrc'
> GET /ec/vittorio?go-get=1 HTTP/1.1
> Authorization: Basic ZVNkaWpla3JIc2RjZDYzMWJiNmQyNTcwODFhNGIyZHVzb3J1d29oZAo
> User-Agent: curl/7.38.0
> Host: git.easyconnect.no
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Thu, 25 Aug 2016 07:34:15 GMT
* Server Apache/2.4.10 (Debian) is not blacklisted
< Server: Apache/2.4.10 (Debian)
< Location: /user/login
< Content-Length: 34
< Content-Type: text/html; charset=utf-8
< Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
< Set-Cookie: i_like_gogits=4b088667ec30e7dc; Path=/; HttpOnly; Secure
< Set-Cookie: _csrf=qL89mRw8Jgpb_rzTvsjB_f3pmzc6MTQ3MjExMDQ1NTY4NDUyMjA0Mw%3D%3D; Path=/; Expires=Fri, 26 Aug 2016 07:34:15 GMT; HttpOnly
< Set-Cookie: redirect_to=%252Fec%252Fvittorio%253Fgo-get%253D1; Path=/
< 
<a href="/user/login">Found</a>.

* Connection #0 to host git.easyconnect.no left intact
```

(I have verified that the token in .netrc is working when using git clone over https).

**Comment by Unknwon** [comment]
You must test and prove on demo site.

**Comment by martinhpedersen** [comment]
Ok, did not realize that you where referring to tip when you said "should be possible now". Sorry about that!

I can confirm that it is working as expected on try.gogs.io :+1: 

Thanks, my co-workers and I are looking forward to the next release!
