### ISSUE TITLE
Does not sync with local changes

### ISSUE THREAD

**Issue by LukeMauldin** [gogits/gogs#2724]
- Gogs version (or commit ref): 0.8.43
- Git version: 2.7.1
- Operating system: CentOS 7
- Database: SQLite

I have used the Gogs interface to create a new Git repository.  If I push into that repository locally from the server using a relative or absolute file path to the repository then Gogs does not "see" the changes and will not display them in the UI.  I have restarted Gogs but it seems like Gogs is caching something about the status of the repository that survives restarts.  How can I force Gogs to reexamine the Git repository on disk and update the UI accordingly?
As a side note, if I create a repository in Gogs, do a Git push to that repo through SSH or HTTPS, then Gogs will show new commits if I make them locally on the file system.  The above problem only occurs when I populate the new repository from a blank state.

**Comment by Unknwon** [comment]
Hi, please read this post: https://discuss.gogs.io/t/how-to-config-ssh-settings/34

**Comment by Unknwon** [comment]
It is very common questions and exists a lot in GitHub, so I'm closing this one.
