### ISSUE TITLE
while edit wiki,it return 500

### ISSUE THREAD

**Issue by julor** [gogits/gogs#2725]
- Gogs version (or commit ref):0.8.43.0223
- Git version:2.6.3
- Operating system:windows7
- Database:sqlite
  - [ ] PostgreSQL
  - [ ] MySQL
  - [*] SQLite
- Log gist:[...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage:UpdateLocalWiki:Pull:exit status128 - fatal: Not a git repository (or any of the parent directories): .git

## Description

while New or modify wiki ,gogs will return 500 code

**Comment by andreynering** [comment]
I can confirm, I also experienced this in Windows, but with PostgreSQL.

After few edits, I got the given error.

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you reproduce this on https://try.gogs.io?

**Comment by Unknwon** [comment]
Any updates?

**Comment by julor** [comment]
only on my computer! I have several update from last year version.This could cause the problem?

**Comment by Unknwon** [comment]
@julor 

1. Update to latest `master`.
1. Restart
2. Try again

**Comment by andreynering** [comment]
I have no idea about what is causing this issue, but it still happens.

Seems very random. You can create a wiki and do many edits without any problem, but after some days, you just get error 500 while trying to edit or create a new page.

Seems to be Windows only.

> [...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage:UpdateLocalWiki:Pull:exit status128 - fatal: Not a git repository (or any of the parent directories): .git

Definitely there is no problem with the Git repo, cause I can manually clone, edit and push without any problem.

**Comment by Unknwon** [comment]
@andreynering 

1. Did you rename anything?
2. Does restart Gogs solve the problem?

**Comment by andreynering** [comment]
> Did you rename anything?

Yes, I renamed the repo name, but the `reponame.wiki.git` folder was also renamed correctly, so this isn't the problem, I think. Or there is something else that should be renamed?

> Does restart Gogs solve the problem?

No luck on restart.

**Comment by Unknwon** [comment]
@andreynering check system notices... maybe delete fails again somehow.

**Comment by andreynering** [comment]
Yep, there's the following notice there:

> Delete repository wiki local copy [data/tmp/local-wiki/8]: exit status 1

**Comment by Unknwon** [comment]
Hmm... can you help check why commands are not working anymore?

**Comment by andreynering** [comment]
I will take a look.
