### ISSUE TITLE
Error trying to get to Dashboard

### ISSUE THREAD

**Issue by maximaldesign** [gogits/gogs#2726]
- Gogs version (or commit ref): 0.8.46.0227
- Git version: latest
- Operating system: Ubuntu Apache2
- Database: 
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] SQLite
- Log gist: 

## Description
Everything worked fine at first. After adding two repos i wanted to switch back to the Dashboard and received this message:
```template: user/dashboard/feeds:47:18: executing "user/dashboard/feeds" at <$push.Commits>: nil pointer evaluating *models.PushCommits.Commits```

**Comment by Unknwon** [comment]
Thanks your feedback!

Same thing to https://github.com/gogits/gogs/issues/2448?

**Comment by Unknwon** [comment]
Close due to lack of feedback.
