### ISSUE TITLE
Organization (with several  teams) dashboard Error 500

### ISSUE THREAD

**Issue by igrampe** [gogits/gogs#2729]
- Gogs version: 0.8.46.0227
- Git version: 2.6.4
- Operating system: ubuntu 14.10
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Log gist:

> 2016/03/01 23:47:11 [...routers/user/home.go:115 Dashboard()] [E] GetUserRepositories: GetUserRepositories: get repositories: pq: invalid input syntax for integer: "14,15"

## Description
If you have an organization with several teams and you try add one user to two or more teams, when this user try to open organization dashboard, gogs fails with 500.
...

**Comment by neolit123** [comment]
might be related to a possible PostgreSQL-only bug:
https://github.com/gogits/gogs/issues/2727

can you reproduce the same scenario on http://try.gogit.com?

**Comment by Unknwon** [comment]
Thanks your feedback!

But as @neolit123 mentions, this one is duplicated to #2727
