### ISSUE TITLE
Write Access Team Members can't access Labels while add new Issue

### ISSUE THREAD

**Issue by serkon** [gogits/gogs#2731]
Hi there,

on gogs 0.8.43 under organization repositories: When add a team with read access to a repo, this team members could not see the labels while add new issue. Just has owner permission user can access  the labels.

**Comment by neolit123** [comment]
hello @serkon ,

thanks but your report is incomplete. what OS, database type and git version?

also, can you reproduce the same if you register an account @ http://try.gogs.com, which is a newer version than 0.8.43?

**Comment by serkon** [comment]
Hi again,

My gogs versiyon windows 386 0.8.43, mysql,  git version 2.6.2.windows.1.

How could i reproduce the same thing? i am the only one persone at my organization on http://try.gogs.io.

If you want to try it, add some people without owner access permission to organization repository and sign in with one of them account. And try to add new issue. You will see, can not add any label if entered account is owner of the repository.

**Comment by neolit123** [comment]
> How could i reproduce the same thing? i am the only one persone at my organization on http://try.gogs.io.

create a team for this organisation and add me @ http://try.gogs.io, my user is ```neolit123```.

**Comment by neolit123** [comment]
> create a team for this organisation and add me @ http://try.gogs.io, my user is neolit123.

scratch that.
bug confirmed with 0.8.49.0229 on my local server.

steps:
```
- create an organisation
- add a team with read access to organisation
- add another user as member to said team
- create a organisation repository
- add some labels
- login as the read access team member
- team member cannot see the labels
```

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think Gogs is working as it should, read access is supposed be only have read access, modifying issue labels belong to write access.

**Comment by serkon** [comment]
@neolit123 
    actually, i think only the repository owner or collaborators should be able to add labels to an issue.
if at team member has read only access he cannot be a collaborator.

I dont try, but i can say just owners can **select labels**  while adding new issue, so maybe collaborators can't select labels too while adding one. 

@Unknwon 
I want to select one of labels while add new issue with any team permission even admin rights. We don't want to modify current labels.

Maybe, it was made for manage issue labels by just owners.

**Comment by Unknwon** [comment]
> I want to select one of labels while add new issue with any team permission even admin rights. We don't want to modify current labels.

Add or modify, sounds same to. Read access are supposed just do read only operations.

**Comment by serkon** [comment]
@Unknwon 
I want to **_select one_** of labels....

Maybe i can't explain correctly sorry for english...

**Comment by Unknwon** [comment]
@serkon you can't create issue with labels for gogits/gogs can you? That's what i mean.

**Comment by serkon** [comment]
Nope. While team members add new issue **can't select any labels** even they have admin rights...

**Comment by Unknwon** [comment]
@serkon yes, so the title of this issue should be `Team members with write access should be able to select labels when create issue`

**Comment by serkon** [comment]
:) great progress ... So we can close now..

**Comment by Unknwon** [comment]
:100:

**Comment by Unknwon** [comment]
I think this is fixed already.
