### ISSUE TITLE
Always show commits count of default branch on tab

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#2735]
- Gogs version: 0.8.43.0223
- Operating system: Debian Linux 8 amd64
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

## Description

When viewing a certain commit  in the history with: `/<userorcompany>/<repo>/commit/<hash>` the commits button at the top only shows the number of commits from the beginning until this commit instead of the total number of commits. Also when you click on the 'commits' button, it doesn't list all commits but only those instead. The button refers to: `/<userorcompany>/<repo>/commits/<hash>` instead of `/<userorcompany>/<repo>/commits/master`

**Comment by neolit123** [comment]
confirmed with 0.8.49.0229,

i think the number in the "commits" button should show the total number of commits in the repository at all times and the button should always link to ```<userorcompany>/<repo>/commits/<currentbranch>```

**Comment by Unknwon** [comment]
> <userorcompany>/<repo>/commits/<currentbranch>

There is no such thing called `currentbranch` when view a commit. But I think we can use the default branch.

**Comment by neolit123** [comment]
> There is no such thing called currentbranch when view a commit. But I think we can use the default branch.

i think there should be, check github. the total number of commits updates based on the selected branch. on github the "commits" links to ```https://github.com/<user>/<repo>/<tree>/<currentbranch>```

**Comment by Unknwon** [comment]
@neolit123 I don't think you can select a branch while viewing the commit. Git does not have such concept. Branch is just a collection of commits, so one commit can belong to many branches.

**Comment by neolit123** [comment]
@Unknwon, yes of course.

the thing is, there is a number of commits per branch. for github this isn't visible once you enter the UI to view a commit (like you said a commit can belong to many branches). for gogs the "commits (N)" button is visible when a commit is viewed, so either it should be *hidden* or it should show the number of commits for the last branch the user selected - presumably the branch from which the user navigated to the currently viewable commit.

this gets complicated if the user navigated from a direct link to this commit; in that case the commits for the default branch, might be shown. but, always showing the number of commits for the default branch, even if the user selected another branch previously might be confusing.

just some thoughs...hiding the button is probably the best option, like github does.

**Comment by Unknwon** [comment]
@neolit123 That .. could be an option, which I was thinking, when commits number are very large, count operation slows down everything.

It would be better to propose PR for this.
