### ISSUE TITLE
Add ability for contributors to add labels to issues

### ISSUE THREAD

**Issue by i00** [gogits/gogs#2737]
Currently all contributors can add issues.

It would be nice if there was an option to set permissions for contributors to also:
-Add labels
-Assign milestones
-Delegate (set Assignees')
-And maybe also disable certain users from being able to add issues at all!

I really only need it for labels... but still the others would be good too

Cheers

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think this is duplicated to https://github.com/gogits/gogs/issues/1146

**Comment by i00** [comment]
This is specifically for issues not for repos.. as discussed in #1146

**Comment by Unknwon** [comment]
Issue or repo, it sounds same thing to in terms of labels, access rights controls both of them.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
