### ISSUE TITLE
"Fatal error: out of memory" when pushing complete repository converted with svn2git

### ISSUE THREAD

**Issue by bmerlet90** [gogits/gogs#2741]
I converted a svn repository with the svn2git (github repo [here](https://github.com/nirvdrum/svn2git) )

After the conversion was complete I tried to push it to an empty repository on our gogs server using these git commands

```
git remote add origin http://domain.com/user/Repository.git
git push -u origin master
```

During the process, the server crashed completely with this error:

```
runtime: memory allocated by OS (1942999040) not in usable range [0x974e0000,0x174e0000)
runtime: out of memory: cannot allocate 268435456-byte block (279969792 in use)
fatal error: out of memory
```

Here is the complete stack of the error:
[gogs_fatal_error_stack_trace.txt](https://github.com/gogits/gogs/files/156684/gogs_fatal_error_stack_trace.txt)

I had to restart the server and found that the repository was still empty.

- Gogs version (or commit ref): 0.8.25.0129
- Git version: 1.9.1
- Operating system: Ubuntu 14
- Database: MySQL

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think this is duplicted to https://github.com/gogits/gogs/issues/636. And please use SSH for huge repos.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
