### ISSUE TITLE
Support environment variables to override app.ini

### ISSUE THREAD

**Issue by wrouesnel** [gogits/gogs#2742]
Deploying gogs via docker is a reasonably common mode of operation these days. To better support this type of deployment, it would be excellent if Gogs supported reading configuration from gogs.ini from environment variables instead (as these can be passed to docker containers easily by most orchestration systems).

**Comment by Jonny007-MKD** [comment]
> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore)

So for compatibility I suggest to prepend the sections with `__` as separator, making them uppercase and replace dots with `_`.

Examples:
 -  APP_NAME=Gogs
 -  REPOSITORY__SCRIPT_TYPE=bash
 -  UI_ADMIN__USER_PAGING_NUM=50

these variable have to be read at start, this could happen in setting.go, doing the same as `Cfg.Append`

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogits/gogs/issues/3682.
