### ISSUE TITLE
Server Error 500 when viewing dashboard

### ISSUE THREAD

**Issue by Totwart** [gogits/gogs#2743]
Application Version: 0.8.49.0229
- Ubuntu Server 14.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Log gogs:
[...routers/user/home.go:57 retrieveFeeds()] [E] GetFeeds: GetUserRepositories: get teams: Error 1054: Unknown column 'team`.`id' in 'field list'
## Description

This Error occurs when someone is entering the overview of their account. Everybody can create Repositories etc. But when someone tries to open the Overview, the Server sends an Error 500.
...

**Comment by Unknwon** [comment]
Can you reproduce this on https://try.gogs.io?

And what is the `Overview` you're talking?

**Comment by Totwart** [comment]
i cant. I set up a fresh installation.
The start page of everybody when you log in.

**Comment by Unknwon** [comment]
Thanks, are you sure you're using MySQL?

**Comment by Totwart** [comment]
jop, i am sure. The installation created all tables

**Comment by Unknwon** [comment]
OK, I reproduced it, feels like recent update of XORM changed something. cc @lunny

**Comment by Totwart** [comment]
ok, all right. Thank you for response!

**Comment by Unknwon** [comment]
Please help test `master` again, did a quick wordaround.

**Comment by Totwart** [comment]
Hi, can't test it today. On the road until tomorrow evening :/
Am 03.03.2016 4:58 nachm. schrieb "无闻" <notifications@github.com>:

**Comment by Unknwon** [comment]
... OK, I think some others would come to this thread as well.

**Comment by okket** [comment]
` 0.8.51.0303` is showing the dashboard again for me (MariaDB).

**Comment by Unknwon** [comment]
Thanks @okket

**Comment by masterodie** [comment]
For me 0.8.51.0303 seems to fix the issue too. Dashboard is back. (MariaDB, Debian 7.9)

**Comment by Schroedingers-Cat** [comment]
0.8.51.0303 works for me, too. Thank you!

**Comment by Unknwon** [comment]
Pushed another fix in case some people still have problem described in this thread.

**Comment by Totwart** [comment]
Dashboard works for me now. Ty

**Comment by Unknwon** [comment]
@Totwart Thanks for your confirmation.

**Comment by xuanduc987** [comment]
@Unknwon 

Organization page still error 500

xorm:
```
[xorm] [info]  2016/03/04 14:12:38.791576 [sql] SELECT `team``.`* FROM `team` INNER JOIN `team_user` ON `team_user`.team_id=`team`.id WHERE (`team_user`.org_id=?) AND (`team_user`.uid=?) [args] [2 1]
```

Now `.` is surrounded by 1 pair of backticks instead of 2

ref go-xorm/xorm/#365

**Comment by Unknwon** [comment]
@xuanduc987 I don't think you have updated to latest version of Gogs.

**Comment by xuanduc987** [comment]
@Unknwon 

I had updated to the latest version of Gogs, and #2751 had been fixed for me too.

In #2752, the error querry is

```
SELECT `team```.``* FROM `team`
```

and with the latest version:

```
SELECT `team``.`* FROM `team`
```

You can see that a pair of back tick ` had been deleted compare to the previous version

**Comment by Unknwon** [comment]
There is no such thing from my log `team.*`:

```
[xorm] [info]  2016/03/04 14:28:30.205895 [sql] SELECT `id`, `org_id`, `lower_name`, `name`, `description`, `authorize`, `num_repos`, `num_members` FROM `team` WHERE org_id=? [args] [6]
[xorm] [info]  2016/03/04 14:28:30.206415 [sql] SELECT team.id FROM team 
INNER JOIN team_user ON team_user.team_id = team.id
WHERE team_user.org_id = ? AND team_user.uid = ? [args] [6 1]
[xorm] [info]  2016/03/04 14:28:30.206870 [sql] SELECT repository.* FROM repository
INNER JOIN team_repo ON team_repo.repo_id = repository.id
WHERE (repository.owner_id = ? AND repository.is_private = ?) OR team_repo.team_id IN (?)
GROUP BY repository.id [args] [6 false 4,5]
```

Make sure you updated **everything** by `go get -u`

**Comment by xuanduc987** [comment]
I installed with packager, from https://packager.io/gh/pkgr/gogs/
Maybe I should install from source

**Comment by Unknwon** [comment]
@xuanduc987 what is the version show on the bottom of the page?

**Comment by xuanduc987** [comment]
@Unknwon 

> © 2016 Gogs Version: 0.8.55.0304

**Comment by Unknwon** [comment]
@xuanduc987 looks right to me, but the SQL is obviously seems wrong to me.

**Comment by xuanduc987** [comment]
@Unknwon 

Like this page: https://try.gogs.io/rails

I had build gogs from source, using go 1.6 but the results still the same.
When member loged in, then the error occurs when he go to his Org profile page
But if he is not logged in, or if he is an admin then he can view this page normaly

**Comment by Unknwon** [comment]
I am running out of ideas.

**Comment by xuanduc987** [comment]
@Unknwon 

I don't know `go`
But I think the cause is here
https://github.com/gogits/gogs/blob/master/models/org.go#L1091-L1098

```go
func (org *User) GetUserTeams(userID int64) error {
	if err := x.Cols("`team`.*").
		Where("`team_user`.org_id=?", org.Id).
		And("`team_user`.uid=?", userID).
		Join("INNER", "`team_user`", "`team_user`.team_id=`team`.id").
		Find(&org.Teams); err != nil {
		return fmt.Errorf("GetUserTeams: %v", err)
	}
```

**Comment by Unknwon** [comment]
@xuanduc987 good catch!

BTW, which MySQL version you're running?

**Comment by xuanduc987** [comment]
@Unknwon 
I'm runing it on CentOS, so it is actually MariaDB
```
+-------------------------+---------------------+
| Variable_name           | Value               |
+-------------------------+---------------------+
| innodb_version          | 5.5.43-MariaDB-37.2 |
| protocol_version        | 10                  |
| slave_type_conversions  |                     |
| version                 | 5.5.44-MariaDB      |
| version_comment         | MariaDB Server      |
| version_compile_machine | x86_64              |
| version_compile_os      | Linux               |
+-------------------------+---------------------+

```

**Comment by Unknwon** [comment]
@xuanduc987 are you able to try `develop` branch again?

**Comment by xuanduc987** [comment]
@Unknwon 

I got the this error with develop branch:

```sql
[xorm] [info]  2016/03/05 12:13:27.356742 [sql] SELECT repo.id FROM `repository` repo WHERE repo.num_forks!=(SELECT     COUNT(*) FROM `repository` WHERE fork_id=repo.id)
```

empty SELECT part

**Comment by Unknwon** [comment]
> empty SELECT part

I don't understand this.

**Comment by xuanduc987** [comment]
@Unknwon 

What I mean is this part:
```sql
 WHERE repo.num_forks!=(SELECT     COUNT(*) FROM `repository`
```

And this is from gogs.log
```
2016/03/05 12:30:26 [...es/middleware/org.go:98 HandleOrgAssignment()] [E] GetUserTeams: GetUserTeams: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM `team` INNER JOIN `team_user` ON `team_user`.team_id=`team`.id WHERE (`team' at line 1
```

**Comment by Unknwon** [comment]
@xuanduc987 http://stackoverflow.com/questions/10439122/select-count-from-select

**Comment by xuanduc987** [comment]
@Unknwon 

Sorry, my mistake. I were reading the wrong log file.

Somehow, the error is still the same:

```sql
[xorm] [info]  2016/03/05 12:30:26.865616 [sql] SELECT `team``.`* FROM `team` INNER JOIN `team_user` ON `team_user`.team_id=`team`.id WHERE (`team_user`.org_id=?) AND (`team_user`.uid=?) [args] [2 1]
```
from gogs.log
```
2016/03/05 12:30:26 [...es/middleware/org.go:98 HandleOrgAssignment()] [E] GetUserTeams: GetUserTeams: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM `team` INNER JOIN `team_user` ON `team_user`.team_id=`team`.id WHERE (`team' at line 1
```

**Comment by Unknwon** [comment]
@xuanduc987 looks like you are not on the `develop` branch?

**Comment by Unknwon** [comment]
FYI, `develop` is more updated than `master`.

**Comment by xuanduc987** [comment]
@Unknwon 
The version number in footer is from `develop` isn't it
>© 2016 Gogs Version: 0.8.57.0305

**Comment by Unknwon** [comment]
Look at the version, yes, please dump full xorm.log after you hit the error.

**Comment by xuanduc987** [comment]
@Unknwon 

Sorry, it's because I don't know how go build works.
I had forgot to run `go get -u` before build the first time.
I've built again after `go get -u` and now it works as expected

**Comment by Unknwon** [comment]
@xuanduc987 :trollface:

**Comment by enderjo** [comment]
Application Version:0.9.13release
Mysql config:
sql_mode=ONLY_FULL_GROUP_BY,NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,PIPES_AS_CONCAT,ANSI_QUOTES
error Message:
[...routers/user/home.go:57 retrieveFeeds()] [E] GetFeeds: get repositories: Error 1055: 'gogs.repository.owner_id' isn't in GROUP BY

reference:https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by Unknwon** [comment]
@enderjo please dump your `xorm.log` file here right after this error occur.

**Comment by enderjo** [comment]
I delete xorm.log then retry the error,there's no xorm.log.
maybe wrong at org.go line:1077, DISTINCT will be better

**Comment by Unknwon** [comment]
> I delete xorm.log then retry the error,there's no xorm.log.

Restart Gogs.

**Comment by enderjo** [comment]
Use  a mysql docker whitout sql_mode=ONLY_FULL_GROUP_BY, It works.

**Comment by Unknwon** [comment]
@enderjo hmm... not sure what's the default behavior, I use everything default to test.
