### ISSUE TITLE
Migrate MySQL to sqlite

### ISSUE THREAD

**Issue by jeppech** [gogits/gogs#2747]
I've been running my Gogs instance on a MySQL database for some time. I've dump the database to an sqlite file, by using this https://gist.github.com/esperlu/943776 and the structure seems intact. However, when i boot up the Gogs instance with the config changed to
```
DB_TYPE = sqlite
DB_PATH = data/gogs.db
```

It throws this error: `[...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: duplicate column name: id` - I suspect Gogs, for trying to re-create the database which is throwing this error, as it already exists.

I'm using the latest master as of this writing: v0.8.51.0303

**Comment by andreynering** [comment]
I think this question would be more apropriate in the forum: https://discuss.gogs.io/

Maybe you have better luck letting Gogs create the schema to you? You would run just the `INSERT`s after, skipping `CREATE TABLE`s and all.

Don't know if will work, just something to try.

**Comment by jeppech** [comment]
Thanks @andreynering, I'll try that

**Comment by Unknwon** [comment]
I'm closing this since it's more like a deployment thing.

Maybe come back to this issue later.
