### ISSUE TITLE
Redirect loop to /

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#2748]
- Gogs version (or commit ref): Current develop: dfbda48afc805095693ffa21925aea95efc8e5ff
- Git version: 2.7.2
- Operating system: Windows Server 2012
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/andreynering/bc7945bcde1a7148b0a2

## Description

After updating Gogs to develop, it keeps redirecting to `/` over and over again. [See on Chrome](https://cloud.githubusercontent.com/assets/7011819/13525838/9081f9e8-e1e2-11e5-9d84-d71c76e302a5.png). Seems related to f946040fa94a3acb3b1f54873e6f95766595829c? Strangely, do not happens on http://try.gogs.io

**Comment by Unknwon** [comment]
Just pushed a fix to `develop`, please help test again!

**Comment by andreynering** [comment]
Perfect, thanks!
