### ISSUE TITLE
Gogs Crashes on git push via remote

### ISSUE THREAD

**Issue by Flare183** [gogits/gogs#2749]
When I goto push a massive ~200MB music archive that I have versioned with git to my gogs server. It crashes giving me this error:
runtime: memory allocated by OS (1935654912) not in usable range [0x975a8000,0x175a8000)
runtime: out of memory: cannot allocate 268435456-byte block (278921216 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x8a7ac60, 0xd)
	/usr/local/go/src/runtime/panic.go:527 +0x7f
runtime.largeAlloc(0xffffe00, 0x1, 0x97ee6894)
	/usr/local/go/src/runtime/malloc.go:750 +0xc3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:637 +0x30
runtime.systemstack(0x975c4000)
	/usr/local/go/src/runtime/asm_386.s:267 +0x57
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

goroutine 168 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_386.s:222 fp=0x97ee67c8 sp=0x97ee67c4
runtime.mallocgc(0xffffe00, 0x8895980, 0x1, 0x975d0580)
	/usr/local/go/src/runtime/malloc.go:638 +0x77f fp=0x97ee6830 sp=0x97ee67c8
runtime.newarray(0x8895980, 0xffffe00, 0x3ba)
	/usr/local/go/src/runtime/malloc.go:780 +0xbc fp=0x97ee6854 sp=0x97ee6830
runtime.makeslice(0x8885f40, 0xffffe00, 0x0, 0xffffe00, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x180 fp=0x97ee6894 sp=0x97ee6854
bytes.makeSlice(0xffffe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:195 +0x67 fp=0x97ee68c4 sp=0x97ee6894
bytes.(*Buffer).ReadFrom(0x97ee696c, 0x8517fcf8, 0x97e58fc0, 0x7fffe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:167 +0xa7 fp=0x97ee6924 sp=0x97ee68c4
io/ioutil.readAll(0x8517fcf8, 0x97e58fc0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x136 fp=0x97ee69c8 sp=0x97ee6924
io/ioutil.ReadAll(0x8517fcf8, 0x97e58fc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:42 +0x51 fp=0x97ee69f0 sp=0x97ee69c8
github.com/gogits/gogs/routers/repo.serviceRpc(0x8a7b4a0, 0xc, 0x97ebd860, 0x85b2fa90, 0x97ec2a40, 0x97e4a0e0, 0x97dfeac0, 0x38, 0x97ec0ad0, 0x10)
	/home/vagrant/go/src/github.com/gogits/gogs/routers/repo/http.go:362 +0x485 fp=0x97ee6ae8 sp=0x97ee69f0
github.com/gogits/gogs/routers/repo.serviceReceivePack(0x97ebd860, 0x85b2fa90, 0x97ec2a40, 0x97e4a0e0, 0x97dfeac0, 0x38, 0x97ec0ad0, 0x10)
	/home/vagrant/go/src/github.com/gogits/gogs/routers/repo/http.go:330 +0x6a fp=0x97ee6b14 sp=0x97ee6ae8
github.com/gogits/gogs/routers/repo.HTTPBackend.func1(0x85b2fa90, 0x97ec2a40, 0x97e4a0e0)
	/home/vagrant/go/src/github.com/gogits/gogs/routers/repo/http.go:314 +0x414 fp=0x97ee6bf0 sp=0x97ee6b14
github.com/gogits/gogs/routers/repo.HTTP(0x97e439c0)
	/home/vagrant/go/src/github.com/gogits/gogs/routers/repo/http.go:231 +0xcd0 fp=0x97ee6d84 sp=0x97ee6bf0
runtime.call16(0x97b982d0, 0x8bbbf0c, 0x97a9e0c8, 0x4, 0x4)
	/usr/local/go/src/runtime/asm_386.s:442 +0x3a fp=0x97ee6d98 sp=0x97ee6d84
reflect.Value.call(0x889fb00, 0x8bbbf0c, 0x13, 0x8a1c918, 0x4, 0x97ef5dc0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0xee8 fp=0x97ee6f40 sp=0x97ee6d98
reflect.Value.Call(0x889fb00, 0x8bbbf0c, 0x13, 0x97ef5dc0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0x8c fp=0x97ee6f70 sp=0x97ee6f40
github.com/go-macaron/inject.(*injector).Invoke(0x97ef41f0, 0x889fb00, 0x8bbbf0c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 +0x374 fp=0x97ee7024 sp=0x97ee6f70
gopkg.in/macaron%2ev1.(*Context).run(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 +0x84 fp=0x97ee70ac sp=0x97ee7024
gopkg.in/macaron%2ev1.(*Context).Next(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 +0x28 fp=0x97ee70b4 sp=0x97ee70ac
github.com/go-macaron/session.Sessioner.func1(0x97e4cdc0)
	/home/vagrant/go/src/github.com/go-macaron/session/session.go:186 +0x72a fp=0x97ee722c sp=0x97ee70b4
runtime.call16(0x97c5f890, 0x97cafce0, 0x97aec480, 0x4, 0x4)
	/usr/local/go/src/runtime/asm_386.s:442 +0x3a fp=0x97ee7240 sp=0x97ee722c
reflect.Value.call(0x88a1540, 0x97cafce0, 0x13, 0x8a1c918, 0x4, 0x97ef42d0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0xee8 fp=0x97ee73e8 sp=0x97ee7240
reflect.Value.Call(0x88a1540, 0x97cafce0, 0x13, 0x97ef42d0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0x8c fp=0x97ee7418 sp=0x97ee73e8
github.com/go-macaron/inject.(*injector).Invoke(0x97ef41f0, 0x88a1540, 0x97cafce0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 +0x374 fp=0x97ee74cc sp=0x97ee7418
gopkg.in/macaron%2ev1.(*Context).run(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 +0x84 fp=0x97ee7554 sp=0x97ee74cc
gopkg.in/macaron%2ev1.(*Context).Next(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 +0x28 fp=0x97ee755c sp=0x97ee7554
gopkg.in/macaron%2ev1.Recovery.func1(0x97e4cdc0, 0x97a57530)
	/home/vagrant/go/src/gopkg.in/macaron.v1/recovery.go:161 +0x4b fp=0x97ee7570 sp=0x97ee755c
runtime.call16(0x97c5f680, 0x8bbc2ec, 0x97aec450, 0x8, 0x8)
	/usr/local/go/src/runtime/asm_386.s:442 +0x3a fp=0x97ee7584 sp=0x97ee7570
reflect.Value.call(0x88c3ec0, 0x8bbc2ec, 0x13, 0x8a1c918, 0x4, 0x97ec2ac0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0xee8 fp=0x97ee772c sp=0x97ee7584
reflect.Value.Call(0x88c3ec0, 0x8bbc2ec, 0x13, 0x97ec2ac0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0x8c fp=0x97ee775c sp=0x97ee772c
github.com/go-macaron/inject.(*injector).Invoke(0x97ef41f0, 0x88c3ec0, 0x8bbc2ec, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 +0x374 fp=0x97ee7810 sp=0x97ee775c
gopkg.in/macaron%2ev1.(*Context).run(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 +0x84 fp=0x97ee7898 sp=0x97ee7810
gopkg.in/macaron%2ev1.(*Context).Next(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 +0x28 fp=0x97ee78a0 sp=0x97ee7898
gopkg.in/macaron%2ev1.Logger.func1(0x97e4cdc0, 0x97a57530)
	/home/vagrant/go/src/gopkg.in/macaron.v1/logger.go:40 +0x2ae fp=0x97ee7988 sp=0x97ee78a0
runtime.call16(0x97c5f680, 0x8bbc2dc, 0x97aec408, 0x8, 0x8)
	/usr/local/go/src/runtime/asm_386.s:442 +0x3a fp=0x97ee799c sp=0x97ee7988
reflect.Value.call(0x88c3ec0, 0x8bbc2dc, 0x13, 0x8a1c918, 0x4, 0x97ec2aa0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0xee8 fp=0x97ee7b44 sp=0x97ee799c
reflect.Value.Call(0x88c3ec0, 0x8bbc2dc, 0x13, 0x97ec2aa0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0x8c fp=0x97ee7b74 sp=0x97ee7b44
github.com/go-macaron/inject.(*injector).Invoke(0x97ef41f0, 0x88c3ec0, 0x8bbc2dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 +0x374 fp=0x97ee7c28 sp=0x97ee7b74
gopkg.in/macaron%2ev1.(*Context).run(0x97e4cdc0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 +0x84 fp=0x97ee7cb0 sp=0x97ee7c28
gopkg.in/macaron%2ev1.(*Router).Handle.func1(0x85b2f9a8, 0x97d78d00, 0x97e4a0e0, 0x97ec29e0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:184 +0x322 fp=0x97ee7d08 sp=0x97ee7cb0
gopkg.in/macaron%2ev1.(*Router).ServeHTTP(0x97a57500, 0x85b2f9a8, 0x97d78d00, 0x97e4a0e0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:286 +0x14d fp=0x97ee7d4c sp=0x97ee7d08
gopkg.in/macaron%2ev1.(*Macaron).ServeHTTP(0x97adb8c0, 0x85b2f9a8, 0x97d78d00, 0x97e4a0e0)
	/home/vagrant/go/src/gopkg.in/macaron.v1/macaron.go:176 +0x1cf fp=0x97ee7dac sp=0x97ee7d4c
net/http.serverHandler.ServeHTTP(0x97c56540, 0x85b2f9a8, 0x97d78d00, 0x97e4a0e0)
	/usr/local/go/src/net/http/server.go:1862 +0x156 fp=0x97ee7ddc sp=0x97ee7dac
net/http.(*conn).serve(0x9790b800)
	/usr/local/go/src/net/http/server.go:1361 +0xc05 fp=0x97ee7fc0 sp=0x97ee7ddc
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1662 +0x1 fp=0x97ee7fc4 sp=0x97ee7fc0
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x343

goroutine 1 [IO wait]:
net.runtime_pollWait(0x85b29a40, 0x72, 0x97ed53b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x97c565f8, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x97c565f8, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x97c565c0, 0x0, 0x851c5280, 0x97ed53c0)
	/usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x978a95d8, 0x97c0d620, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net/http.tcpKeepAliveListener.Accept(0x978a95d8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2135 +0x3d
net/http.(*Server).Serve(0x97c56540, 0x851c5260, 0x978a95d8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0x98
net/http.(*Server).ListenAndServe(0x97c56540, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1877 +0xe4
net/http.ListenAndServe(0x97ec0cd0, 0xc, 0x851c5228, 0x97adb8c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1967 +0x7a
github.com/gogits/gogs/cmd.runWeb(0x976166e0)
	/home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:559 +0x1c16
github.com/codegangsta/cli.Command.Run(0x8a1a6c8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8aa0bd0, 0x15, 0x0, ...)
	/home/vagrant/go/src/github.com/codegangsta/cli/command.go:174 +0x10fc
github.com/codegangsta/cli.(*App).Run(0x976165a0, 0x97618050, 0x2, 0x2, 0x0, 0x0)
	/home/vagrant/go/src/github.com/codegangsta/cli/app.go:187 +0xeca
main.main()
	/home/vagrant/go/src/github.com/gogits/gogs/gogs.go:40 +0x29a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1662 +0x1

goroutine 185 [IO wait]:
net.runtime_pollWait(0x85b299c8, 0x72, 0x97618000)
	/usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x97ada0b8, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x97ada0b8, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).Read(0x97ada080, 0x97ebb000, 0x1000, 0x1000, 0x0, 0x85b24018, 0x97618000)
	/usr/local/go/src/net/fd_unix.go:232 +0x19a
net.(*conn).Read(0x97aec3a8, 0x97ebb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xb9
net/http.(*liveSwitchReader).Read(0x979c9f44, 0x97ebb000, 0x1000, 0x1000, 0x97eb2500, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0x84
io.(*LimitedReader).Read(0x97de9560, 0x97ebb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xcb
bufio.(*Reader).fill(0x97c5f5c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x172
bufio.(*Reader).ReadSlice(0x97c5f5c0, 0x9754430a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x1b4
bufio.(*Reader).ReadLine(0x97c5f5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:357 +0x4b
net/textproto.(*Reader).readLineSlice(0x97a0f280, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x59
net/textproto.(*Reader).ReadLine(0x97a0f280, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x39
net/http.ReadRequest(0x97c5f5c0, 0x97be4a80, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:653 +0x9a
net/http.(*conn).readRequest(0x979c9f20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:633 +0x368
net/http.(*conn).serve(0x979c9f20)
	/usr/local/go/src/net/http/server.go:1319 +0x7a9
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x343

goroutine 34 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0x977246e0)
	/home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x2ff
created by github.com/gogits/gogs/modules/log.newLogger
	/home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x11d

goroutine 24 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0x97825100)
	/home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x2ff
created by github.com/gogits/gogs/modules/log.newLogger
	/home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x11d

goroutine 31 [chan receive]:
database/sql.(*DB).connectionOpener(0x977fdb60)
	/usr/local/go/src/database/sql/sql.go:634 +0x3c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x276

goroutine 33 [select]:
github.com/gogits/cron.(*Cron).run(0x976ad120)
	/home/vagrant/go/src/github.com/gogits/cron/cron.go:158 +0x923
created by github.com/gogits/cron.(*Cron).Start
	/home/vagrant/go/src/github.com/gogits/cron/cron.go:133 +0x3a

goroutine 50 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
	/home/vagrant/go/src/github.com/gogits/gogs/models/webhook.go:603 +0x3d6
created by github.com/gogits/gogs/models.InitDeliverHooks
	/home/vagrant/go/src/github.com/gogits/gogs/models/webhook.go:623 +0x2a

goroutine 51 [chan receive]:
github.com/gogits/gogs/models.TestPullRequests()
	/home/vagrant/go/src/github.com/gogits/gogs/models/pull.go:612 +0x19b
created by github.com/gogits/gogs/models.InitTestPullRequests
	/home/vagrant/go/src/github.com/gogits/gogs/models/pull.go:630 +0x2a

goroutine 52 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0x9791a120)
	/home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x2ff
created by github.com/gogits/gogs/modules/log.newLogger
	/home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x11d

What should I do about this?

**Comment by Unknwon** [comment]
Thanks your feedback!

But if you don't follow issue template, I can't offer any help.
