### ISSUE TITLE
Template problem in organization page

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#2750]
- Gogs version (or commit ref): develop: f6759a731a063d5d2be8a932f8d1e1a784cc0528
- Operating system: any
- Database: any
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

There's something strange with the repo listing in a organization page. Noticed local and on try: https://try.gogs.io/rails

**Comment by Unknwon** [comment]
Hmm... merge this issue to #2751
