### ISSUE TITLE
Organization page doesn't show repository, creation date 2044 years ago

### ISSUE THREAD

**Issue by xuanduc987** [gogits/gogs#2751]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.8.51.0303
- Git version: 1.8.3.1
- Operating system: centos 7
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

![capture](https://cloud.githubusercontent.com/assets/1186411/13532979/e289771a-e260-11e5-9234-7a30c208e419.PNG)

Maybe same as #2750

**Comment by Unknwon** [comment]
Pushed fix to `master` and updated https://try.gogs.io.

**Comment by xuanduc987** [comment]
@Unknwon 
Thank you, this issue had been fixed

But I still got #2743  https://github.com/gogits/gogs/issues/2743#issuecomment-192422691

**Comment by Unknwon** [comment]
Great!
