### ISSUE TITLE
500 error when viewing Organization with MySQL

### ISSUE THREAD

**Issue by xuanduc987** [gogits/gogs#2752]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.8.51.0303
- Git version: 1.8.3.1
- Operating system: centos 7
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [x] No
  - [ ] Not relevant
- Log gist:

xorm log
```sql
[xorm] [info]  2016/03/04 11:02:17.875821 [sql] SELECT `team```.``* FROM `team` INNER JOIN `team_user` ON `team_user`.team_id=`team`.id WHERE (`team_user`.org_id=?) AND (`team_user`.uid=?) [args] [2 1]
```
var/log/gogs/gogs.log
```
2016/03/04 11:02:17 [...es/middleware/org.go:98 HandleOrgAssignment()] [E] GetUserTeams: GetUserTeams: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM `team` INNER JOIN `team_user` ON `team_user`.team_id=`team`.id WHERE (`team' at line 1
```
## Description

As you can see the error is `.` somehow is surrounded by two back tick
```
 SELECT `team```.``* FROM
```

But, when login as admin, the error #2751 shows up

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2743
