### ISSUE TITLE
[FEATURE] Comment webhook

### ISSUE THREAD

**Issue by Download-Fritz** [gogits/gogs#2754]
Dear developers,

I'm currently working on setting up Jenkins CI to build certain repositories and their Pull Requests hosted via Gogs. To achieve this, I added a post-receive hook to the main repository, which is correctly triggered each time a PR is opened.
Now, the PR may needs to be updated several times to comply with the standards, but the following commits to the PR branch will not be covered in CI as the post-receive hook only triggers once.

Because of that and as otherwise a massive build queue could be created (in the case post-receive ws triggered with each new commit), I found a webhook for PR comments to be a good idea. The hook could be caught by Jenkins and checked for the string "Jenkins, build this." or whatever (checked on CI side, no need for Gogs to do anything) to queue a build when really desired.

As I don't have enough skill in the Go language and because I barely know the inner workings of Gogs, I would be happy if someone who has the time and skills needed to look into this. Thank you very much.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I think this is duplicated to https://github.com/gogits/gogs/issues/2319

**Comment by Download-Fritz** [comment]
Yes, you are right
I specifically searched for PRs, so this one did not pop up.

Thanks! :)
