### ISSUE TITLE
Allow to delete current avatar of organizations

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2763]
An image
![image](https://cloud.githubusercontent.com/assets/7110786/13552165/d6322736-e356-11e5-98bf-6b34d3747ea8.png)

**Comment by Unknwon** [comment]
Same thing has been done for user settings, if someone want to take this, claim and go ahead.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2766

**Comment by Unknwon** [comment]
Close as implemented.
