### ISSUE TITLE
Translate dialogs without translation

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2764]
- Collaborators
![image](https://cloud.githubusercontent.com/assets/7110786/13552176/6e33eaf6-e357-11e5-885d-25839495be3f.png)

- New page's editor of Wiki
![image](https://cloud.githubusercontent.com/assets/7110786/13552199/2096b9e8-e359-11e5-8fde-e61f1e85ec81.png)

- Gravatar email dialog in profile.tmpl (it's a concatenation string)
![image](https://cloud.githubusercontent.com/assets/7110786/13552232/63a71894-e35a-11e5-8b67-0d178acd4489.png)

Thank you and saludos! :+1:

**Comment by Unknwon** [comment]
This is on purpose, I think these English words express things more precise.

**Comment by xxxtonixxx** [comment]
Hmmm, in spanish is common to see "read" and "write" how "lectura" and "escritura". "Admin" is equal, "Administrador".

**Comment by Unknwon** [comment]
**Gravatar** is a special term which should not be translated ever.

**Comment by Unknwon** [comment]
And.. I really don't understand the issue title....

**Comment by xxxtonixxx** [comment]
Yes, but the problem is the order of the strings. In spanish "Gravatar correo electrónico" doesn't have too sense.

**Comment by xxxtonixxx** [comment]
Ok, I'm sorry for my bad english... :sweat:

**Comment by Unknwon** [comment]
> New page's editor of Wiki

It won't be fixed because that's directly from editor, out of Gogs control.

**Comment by Unknwon** [comment]
Will consider the other two though.

**Comment by xxxtonixxx** [comment]
Ok, and thanks for all :+1: :sweat_smile:

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3100, please help test on `develop` branch or https://try.gogs.io.
