### ISSUE TITLE
Error 500 on wiki - "not a valid ref"

### ISSUE THREAD

**Issue by nd2s** [gogits/gogs#2765]
I tried creating a (first) wiki page on a repo and getting error 500 since then when visiting wiki tab.

```
2016/03/06 14:15:32 [...routers/repo/wiki.go:54 renderWikiPage()] [E] GetBranchCommit: exit status 128 - fatal: 'refs/heads/master' - not a valid ref
2016/03/06 14:15:32 [D] Template: status/500
```

Gogs version: 0.8.59.0305 (also happened on a previous version, don't know which one, though).
Git version: 2.7.2
OS: FreeBSD 10.2
DB: PostgreSQL 9.4

Could not reproduce on try.gogs.io.

**Comment by Unknwon** [comment]
Thanks your feedback!

Is it 100% reproducible for **every new repository and after create first wiki page**?

**Comment by nd2s** [comment]
I created a new repository + wiki page and got a different error: turns out `data/tmp` directory was missing (no idea why). I created it with proper permissions, and recreated wiki page of first repo - now everything is working.

Closing this now, thanks.

**Comment by Unknwon** [comment]
:+1:
