### ISSUE TITLE
OpenLDAP connection using StartTLS

### ISSUE THREAD

**Issue by tuudik** [gogits/gogs#2767]
- Gogs version (or commit ref): 0.8.55.0304
- Operating system: Ubuntu 14.04 LTS Server
- Database:
  - [X] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Not relevant

## Description

I've tried to configure Gogs to use OpenLDAP as authentication source with following configuration:

Parameter | Value
------------ | -------------
Authentication Type | LDAP (via BindDN)
Authentication Name | helpme LDAP
Host | ldap.helpme.com
Port | 389
Bind DN | cn=Gogs User,ou=Service Accounts,dc=helpme,dc=com
Bind Password | GogsUser password
User Search Base | dc=helpme,dc=com
User Filter | (&(uid=%{user})(objectClass=posixAccount)(memberof=CN=GogsUsers,OU=Groups,DC=helpme,DC=com))
Admin Filter | (&(uid=%{user})(objectClass=posixAccount)(memberof=CN=GogsAdmins,OU=Groups,DC=helpme,DC=com))
Username Attribute | uid
Firstname Attribute | givenName
Surname Attribute | sn
Email attribute | mail
AttributesInBind | true
Enable TLS Encryption | true
Skip TLS Verify | true
This Authentication is Active | true

But it doesnt work.
In LDAP logs i see following:
```
Mar  6 19:11:54 ldap slapd[12252]: conn=3479 fd=23 ACCEPT from IP=*.*.*.*:57530 (IP=0.0.0.0:389)
Mar  6 19:11:54 ldap slapd[12252]: conn=3479 fd=23 closed (connection lost)
```

In Gogs logs:
```
2016/03/06 19:11:54 [...gogs/models/login.go:246 LoginUserLDAPSource()] [E] LDAP Connect error, ldap.helpme.com:LDAP Result Code 200 "": EOF
2016/03/06 19:11:54 [W] Failed to login 'username' via 'helpme LDAP': user does not exist [uid: 0, name: username]
```

I have configured LDAP to use StartTLS.

**Comment by tuudik** [comment]
Also, if I want to disable "Skip TLS Verify", it's unclear where do I specify the CA certificate, which was used to issue OpenLDAP certificate.

**Comment by Unknwon** [comment]
> Also, if I want to disable "Skip TLS Verify", it's unclear where do I specify the CA certificate, which was used to issue OpenLDAP certificate.

Skip verify means no verify, so you don't need to given CA certificates. 

cc @nanoant @SergioBenitez can you guys help?

**Comment by tuudik** [comment]
But I want it to check:D But lets try first to get some progrss with skip.

Another question, is there some way to endable debug? I use init.d script to launch gogs.

**Comment by Unknwon** [comment]
> Another question, is there some way to endable debug? I use init.d script to launch gogs.

Change `[log] LEVEL = Trace` and start without daemon, trace log will be printed to console.

**Comment by tuudik** [comment]
Unfortunately nothing extra:(
`
[Macaron] Started POST /user/login for *.*.*.*
2016/03/06 20:22:47 [D] Session ID: 0bbfc4ce55a41760
2016/03/06 20:22:47 [D] CSRF Token: -c7vEcWy_RJ58j8D5BoTAWRvCjk6MTQ1NzI3MDMwMTY5MTgzODI1NA==
2016/03/06 20:22:47 [D] Using TLS for LDAP without verifying: true
2016/03/06 20:22:47 [...gogs/models/login.go:246 LoginUserLDAPSource()] [E] LDAP Connect error, ldap.roksnet.com:LDAP Result Code 200 "": EOF
2016/03/06 20:22:47 [W] Failed to login 'ldapuser' via 'helpme LDAP': user does not exist [uid: 0, name: ldapuser]
[Macaron] Completed /user/login 200 OK in 21.090721ms
2016/03/06 20:22:47 [D] Template: user/auth/signin
`

**Comment by Unknwon** [comment]
This is the core problem:

>LDAP Connect error, ldap.roksnet.com:LDAP Result Code 200 "": EOF

**Comment by SergioBenitez** [comment]
@tuudik: Indeed, as @Unknwon has identified, it looks like the machine running the Gogs instance can't connect to your LDAP server. Try using `ldapsearch` on the same machine, if it's installed, to ensure you can connect to the server.

As far as verifying certificates goes, this is actually broken on the current Gogs instance. I've fixed this in my current version (it's a very small fix) but have yet to send in a PR. Will do so soon.

**Comment by tuudik** [comment]
Oh, 
> Gogs doesn't support StartTLS at the moment.

I guess case closed then, is there a feature request somewhere that I can check for updates?

**Comment by tuudik** [comment]
Oh, 
> Gogs doesn't support StartTLS at the moment.

I guess case closed then, is there a feature request somewhere that I can check for updates?
@SergioBenitez @Unknwon

**Comment by Unknwon** [comment]
@tuudik maybe this? https://github.com/gogits/gogs/pull/2376
