### ISSUE TITLE
二进制安装，异常

### ISSUE THREAD

**Issue by githublaohu** [gogits/gogs#2769]
按照

    解压压缩包。
    使用命令 cd 进入到刚刚创建的目录。
    执行命令 ./gogs web，然后，就没有然后了。

在ubuntu14，centos6.5与7。都是64位操作系统。
执行 ./gogs web 
error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory

实在找不到问题解决方案。麻烦解决下。
多谢。麻烦了 。

**Comment by Unknwon** [comment]
Close by 

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

**Comment by Unknwon** [comment]
Possible solutions: http://www-01.ibm.com/support/docview.wss?uid=swg21664818

**Comment by githublaohu** [comment]
[root@iZ11rl3hsntZ ~]# rpm -qa *Xext*
libXext-1.3.1-2.el6.x86_64
[root@iZ11rl3hsntZ ~]# rpm -qa pam
pam-1.1.1-20.el6_7.1.x86_64
[root@iZ11rl3hsntZ ~]# cd /data/olds/
du-tomcat/                     gogs/                          gogs_v0.8.43_linux_386.tar.gz  tomcat/                        
[root@iZ11rl3hsntZ ~]# cd /data/olds/gogs
[root@iZ11rl3hsntZ gogs]# ./gogs .web
./gogs: error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory
[root@iZ11rl3hsntZ gogs]# ./gogs web
./gogs: error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory
[root@iZ11rl3hsntZ gogs]# 

还是无用。

**Comment by novaeye** [comment]
@githublaohu 

> [root@iZ11rl3hsntZ ~]# rpm -qa pam
pam-1.1.1-20.el6_7.1.x86_64
[root@iZ11rl3hsntZ ~]# cd /data/olds/
du-tomcat/ gogs/ gogs_v0.8.43_linux_386.tar.gz tomcat/
> 

看上去是在64位linux上运行32位版本的gogs?
