### ISSUE TITLE
Users can circumvent the repository limit

### ISSUE THREAD

**Issue by kaini** [gogits/gogs#2773]
- Gogs version (or commit ref): 0.8.61.0306
- Git version: 2.1.4
- Operating system: up to date Debian 8
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [X] Not relevant (no admin access)
- Log gist: not relevant

## Description

When creating a user with a repository limit of 0, the user cannot create repositories. But the user can still create an organization and create an endless amount of repositories in the organization, rendering the repository limit useless.

**Comment by Unknwon** [comment]
Duplicated of https://github.com/gogits/gogs/issues/2643 and please follow https://github.com/gogits/gogs/issues/1556
