### ISSUE TITLE
Allow custom the SSH clone URL

### ISSUE THREAD

**Issue by sblu** [gogits/gogs#2776]
In my environment of gogs I have to change the ssh clone url to get ssh git checkout fully running. 

Example: 
* git clone git@gogs.local.de:tools/test.git 
    * doesn't work
* git clone ssh://git@gogs.local.de/~/app-root/data/gogs-repositories/tools/test.git 
    * would work

What I get so far is to set the SSH_DOMAIN in app.ini but this will not include the ssh:// at the beginning and also will create a : in the clone url:

    gogs@gogs.local.de/~/app-root/data/gogs-repositories/:tools/test.git

So this works when I manually remove the : 

It's not possible to change the environment.

**Comment by biocyberman** [comment]
Faced the same problem and found the same solution before trying to report the same problem here :)

**Comment by Unknwon** [comment]
Thanks your feedback!

Please read https://discuss.gogs.io/t/how-to-config-ssh-settings/34

**Comment by sblu** [comment]
Jep, i read this before I opened this issue. I can't use the build in SSH Server. So there is no solution or change in gogs?

**Comment by Unknwon** [comment]
@sblu If use full path solved the problem, it is the problem with `authorized_keys`. Where is this file located in your case?

>We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

**Comment by sblu** [comment]
Sorry that's not my Problem. I need a URL like explained above because of my openshift environment. I told how it works I just need a possibility to change the git Clone URL like explained above.

**Comment by Unknwon** [comment]
> git clone ssh://git@gogs.local.de/~/app-root/data/gogs-repositories/tools/test.git

It looks like full path to me.

**Comment by sblu** [comment]
I ran into a script on git clone called oo-trab-user that disables a git clone without ~ in the URL. Does it help to paste the script part. I can't change this script, just for notice.

**Comment by Unknwon** [comment]
OK... I think you're requesting a complete different feature, which allows you custom the SSH URL format. For example, `ssh://git@gogs.local.de/~/app-root/data/gogs-repositories/{owner}/{repo}.git`.

If this is what you want, please change title to `Allow custom the SSH clone URL`.

**Comment by sblu** [comment]
renamed the title please reopen.

**Comment by zacheryph** [comment]
Im not completely understanding of what is going on here.  It looks like you are not letting `gogs serv` handle the SSH session at all.  Due to this new url going directly into the gogs-repositories I am only assuming you are in fact bypassing `gogs serv` and losing all possibilities of permissions, protections, etc.

Given that you are completely bypassing gogs in this matter I can understand why its not being friendly in giving you a proper URL.  I personally see no reason why gogs should be handing out URLs that bypass itself.  It could be asked, Why do you want to use gogs if you are not going to use gogs? :wink:

Is there any reason you cannot just use `http[s]://` for cloning?

**Comment by sblu** [comment]
HM I'm using gogs in an openshift environment I want to use gogs but if I want to clone a git via SSL i need a ~ in the git clone URL.  https is possible to use in this environment.

**Comment by zacheryph** [comment]
Please read up.  Updated to slowly :disappointed:

**Comment by zacheryph** [comment]
Either way, I'd personally not enjoy seeing this _feature_ in gogs.  Albeit definable, if it is put in I think it needs to have a giant red flag letting the person know that if they are using this feature they are _HIGHLY_ likely to be bypassing `gogs serv`.  Allowing _anyone_ with an account and ssh key to access any repository regardless of ownership, group/organization membership, and repository visibility.

**Comment by sblu** [comment]
Yes but this is restricted via openshift SSH Management

**Comment by zacheryph** [comment]
Correct.  _restricted via openshift_.  Openshift is to blame here.  This sounds like it stops any and all intelligent `authorized_keys` command execution, I'm surprised this isn't a known issue in the openshift world.  Or is it?

Their are options for this already.  Use `http[s]://`.  set `DISABLE_SSH = true` in your `app.ini`.  Bypassing all of gogs permissions/visibility settings hardly sounds like a proper solution here though.

The decision of course is not up to me.  I'd personally, and highly recommend just using `http[s]://` or try to lift this restriction from Openshift for this account.

**Comment by Unknwon** [comment]
OK wait, so this is bypassing `gogs serv`? Did not realize that, which is not acceptable...

**Comment by pnovotnak** [comment]
I think that this is the right GH issue to report my problem... Is it possible to have a custom location for git repositories? In my setup;

`/home/gogs/`
`/mnt/drive/gogs-repositories`

HTTPS works fine, but SSH doesn't because path implicitly starts with `~/`. Is it possible to set the root path for SSH `clone` urls?

**Comment by Unknwon** [comment]
Hi @pnovotnak , I think it's probably not the right now. I suggest you post your problem on [the forum](https://discuss.gogs.io/).

**Comment by Unknwon** [comment]
Close as lack of feedback.
