### ISSUE TITLE
Database Locked SQLite

### ISSUE THREAD

**Issue by shyim** [gogits/gogs#2779]
- Gogs version (or commit ref): d324500959c06e975921790f8770aa5d1bdf2344
- Git version: 2.7.2
- Operating system: OSX El Captain
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [X] Not relevant
- Log gist:
https://gist.github.com/shyim/82947b2751c6c7f86a05

## Description
After some days gogs running, he locks every second time the database and ignores all pushs. Only the solution for a week is restarting gogs.

**Comment by Unknwon** [comment]
The relevant code has been changed a lot, I recommend you upgrade to latest `master` and re-test.

**Comment by shyim** [comment]
I will test it next days
