### ISSUE TITLE
High CPU usage and timeout while repository listing

### ISSUE THREAD

**Issue by juanfcocontreras** [gogits/gogs#2786]
- Gogs version (or commit ref): 0.9.0 (also with previous versions: 0.8.43, 0.8.25, 0.8.10, 0.7.33). Both binary and built from source code versions
- Git version: 1.8.2.1 (also with 1.7.1)
- Operating system: CentOS 5.4 2.6.18-238.19.1.el5
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant

## Description

I would like to install Gogs in my linux cluster but I have two major issues. Every time I start Gogs in my 8-core cluster node, Gogs is running at 300-400% CPU for several minutes. Also, this behavior happens every now and then while using Gogs. The other issue is with an empty repository, most of the times I can't browse it because a timeout error happens. Nevertheless, I can browse most of the other options without problem (issues, commits, releases...) and immediately.

I don't if both issues are related. I've tried all the latest versions, and also with both the binary and source versions. Also, I've tried with Git 1.7.1 and 1.8.2.1 versions. I don't know what more can I do in order to find out what is happening. I've searched but I can't found any issue related or other people with the same problems. I've found that CentOS 5 is not officially supported by Go, but I've heard that most of applications are running without issues.

If you could help me to know what is happening, I would be very grateful. I would like a lot to offer Gogs to my cluster users!

**Comment by Unknwon** [comment]
Hi, please check gogs server log for "timeout" operations.

**Comment by juanfcocontreras** [comment]
Thanks for your prompt reply! Which log file? I have only two log files: http.log is empty, and xorm.log seems to have only sql queries.

**Comment by Unknwon** [comment]
`path/to/gogs/log/gogs.log`

**Comment by juanfcocontreras** [comment]
I don't have that file. I launch gogs vía a init.d script, and this file is deleted once Gogs is totally launched. Do I launch gogs Cía ./gogs web?

**Comment by Unknwon** [comment]
> Do I launch gogs Cía ./gogs web?

Yes, please do that.

**Comment by juanfcocontreras** [comment]
I've doing some research, and I forgot to mention that I'm using gogs via apache. If I use gogs server directly, there aren't timeouts, but loading a repository is very slow. I think that this make apache returns a timout. For example:

Completed /python/issues 200 OK in 34m38.978975763s (issues webpage)
Completed /python 200 OK in 74h0m38.131986309s (repository index)

I have just one repository (called python), with 3 files: .gitignore, LICENSE and README.md

Also, I've found that when CPU is high, some entries appear:

[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: MirrorUpdate
[T] Doing: CheckRepoStats
[T] Doing: GitFsck

Is that normal? I have just one user with an almost empty repository, and I'm just browsing for now.

**Comment by Unknwon** [comment]
Please do not truncated the log in the way you think it would be nice, I need complete, full dump of log, thanks!

**Comment by juanfcocontreras** [comment]
Ok, here they are (I've just removed ips and emails from logs).

One user (called pythonuser) with one repository (called python). I've started gogs from scratch (removing previous logs):
- user logs in
- user browse to the repository (fast)
- user browse to issues (very fast)
- user browse back to the repository (very very slow)

Please, tell me if you need more files or tests.

Thanks!

[logs.zip](https://github.com/gogits/gogs/files/165014/logs.zip)

**Comment by Unknwon** [comment]
The log you packaged does not look like the one you posted on your previous comments.

**Comment by juanfcocontreras** [comment]
Yes, because I delete previous logs. These ones are generated from scratch just a moment ago.

**Comment by Unknwon** [comment]
OK, the log looks right to me.

**Comment by Unknwon** [comment]
Check your anti-virus?

**Comment by juanfcocontreras** [comment]
It don't have any anti-virus. Is that normal that an empty repository lasts so much?

**Comment by Unknwon** [comment]
Consider upgrade your system.... :sweat:

**Comment by juanfcocontreras** [comment]
Do you think it's a matter of CentOS 5?

**Comment by juanfcocontreras** [comment]
Or do you think it's a power issue?

Because the first time is loaded well:
[Macaron] Completed /pythonuser/python/issues 200 OK in 1h58m35.815553505s

The second one is:
[Macaron] Completed /pythonuser/python 200 OK in 162h41m30.093555215s

**Comment by Unknwon** [comment]
`1h58m35.815553505s` does not look well to me...

**Comment by Unknwon** [comment]
How long it takes to run `git version` command?

**Comment by juanfcocontreras** [comment]
I can save a screencast for you. I think units are not well. The first webpage is loaded in a couple the seconds. The second time takes more than a minute.

The machine is a node cluster Intel Xeon E5620 2.40GHz with 32 GB with just gogs.

**Comment by juanfcocontreras** [comment]
`git version` is run immediately

**Comment by Unknwon** [comment]
What is your Go version?

**Comment by juanfcocontreras** [comment]
Now I'm running latest binary version (Gogs 1.9), so Go is 1.6. Previous binary versions were compiled in previous Go compiler version. I've also compiled from sources with Go 1.4 with the same result.

**Comment by Unknwon** [comment]
I'm out of ideas. Is it possible to remote login a user of your node so I can do some tests?

**Comment by juanfcocontreras** [comment]
Sorry, but that is not possible because of security policy. But I could run logs more verbose if you want.

I'm also out of ideas, and that is why I write this issue. I think that is maybe related that Go is not supported in CentOS 5, because no more people seems to have this issue. But upgrading the cluster is not possible right now.

**Comment by Unknwon** [comment]
OK, dump log again after some repository view opeations.

**Comment by juanfcocontreras** [comment]
Remote login is not possible but you can browse the repository if you want, and I can dump log file for you. How can I give you the details privately?

**Comment by Unknwon** [comment]
@juanfcocontreras Let's start with dump log again after some repository view operations first...

**Comment by juanfcocontreras** [comment]
Ok. More logs here:

[logs2.zip](https://github.com/gogits/gogs/files/165193/logs2.zip)

**Comment by Unknwon** [comment]
Looks like your system time is messed up, I see 2016-5-1 at the beginning, and 2016-3-xx at the end.

**Comment by juanfcocontreras** [comment]
I think that is the reason because time units were wrong. But I don't have any related issue in other software, and I have many installed.

The only thing I think could be is CentOS 5 and Go:
http://dave.cheney.net/2013/06/18/how-to-install-go-1-1-on-centos-5

Does it make sense to you? It's too low-level language for me...

**Comment by Unknwon** [comment]
> Important Go 1.0 or 1.1 has never supported RHEL5 or CentOS5. In fact, I don’t think Go will even compile on RHEL5/CentOS5 after version 1.3.

I see this in the article...

**Comment by juanfcocontreras** [comment]
Yes, but I'm not sure if this is related or not with this issue. I'm very new to Go. I've also read this:

https://www.reddit.com/r/golang/comments/2u3bb7/running_go_on_centos5/

"We use nothing but CentOS 5 for our servers (overdue for an upgrade). We've been doing all sorts of go development with no problems whatsoever."

"We've also used Go 1.2/1.3 in production with RHEL 5.3 and 5.11 for a year, without any problems."

"I've had this website running on a Webfaction CentOS 5.11 shared server for a month or so. I have Go 1.3 installed and have not had any problems."

**Comment by juanfcocontreras** [comment]
BTW, I compile Go 1.3 without any issue.

**Comment by Unknwon** [comment]
The problematic thing about slow when view repository files is Gogs calling `git xxx` commands through shell. You might have some ideas?

**Comment by juanfcocontreras** [comment]
How do you call shell commands? I can make a very simple Go app calling git command within Go and directly in the prompt shell to compare.

**Comment by Unknwon** [comment]
Change `RUN_MODE` to `dev` should print commands that are called in console.

**Comment by juanfcocontreras** [comment]
initial commit

[git-module] /test/gogs/repositories/pythonuser/python.git: git rev-list --count bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] stdout:
1

[git-module] /test/gogs/repositories/pythonuser/python.git: git ls-tree e36145dddcb6ca653f4e7bbcf5ab4992b14434d9
[git-module] stdout:
100644 blob 7f7cccc3ee86243eec31cbfe384e68f9aa71e055	.gitignore
100644 blob 61ea6dadc474e470429ee5e4662443e1f4db5747	LICENSE
100644 blob 3529f15dbb2bd7b611bc06cf602f4c7695636d94	README.md

Got stuck here...

2016/04/16 15:06:09 [T] Doing: MirrorUpdate
[git-module] /test/gogs/repositories/pythonuser/python.git: git log -1 --pretty=format:%H bc82ce325db8eced1011fe1243987f0086d533ea -- README.md
[git-module] /test/gogs/repositories/pythonuser/python.git: git log -1 --pretty=format:%H bc82ce325db8eced1011fe1243987f0086d533ea -- .gitignore
[git-module] /test/gogs/repositories/pythonuser/python.git: git log -1 --pretty=format:%H bc82ce325db8eced1011fe1243987f0086d533ea -- LICENSE
[git-module] stdout:
bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] Hit cache: bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] stdout:
bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] Hit cache: bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] stdout:
bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] Hit cache: bc82ce325db8eced1011fe1243987f0086d533ea
[git-module] /test/gogs/repositories/pythonuser/python.git: git show 3529f15dbb2bd7b611bc06cf602f4c7695636d94
[git-module] stdout:
# python

Description
[git-module] /test/gogs/repositories/pythonuser/python.git: git cat-file -s 3529f15dbb2bd7b611bc06cf602f4c7695636d94
[git-module] stdout:
21

2016/04/16 15:38:19 [D] Template: repo/home
[Macaron] Completed /pythonuser/python 200 OK in 156h48m31.466025889s

**Comment by juanfcocontreras** [comment]
Command are executed quickly. Problem seems to be related to:

2016/04/16 15:06:09 [T] Doing: MirrorUpdate

The rest of the code is executed immediately. What does it do?

**Comment by Unknwon** [comment]
It is very obvious it updates your mirror repositories, but since you have none, it should do nothing.

Again, your system time is very wrong, there is no guarantee everything works as expected.

**Comment by juanfcocontreras** [comment]
Any idea of debugging about debugging system time? I don't have any issue in bash scripts, python or php.

**Comment by Unknwon** [comment]
I don't think wrong system time is a right environment setup, and the statement ` I don't have any issue in bash scripts, Python or PHP.` is invalid because Gogs is not written in bash scripts, Python or PHP, and even you don't have problem with other Go apps, there is no guarantee Gogs should function the same.

I don't think it is worth investigating until the system time problem is solved.

**Comment by juanfcocontreras** [comment]
Yes, I totally agree with you. I think everything could be related to system time, because is something very sensible.

What I meant is that when you say "system time" as something affecting the whole system,  it's something I found very weird because I have a lot of things running in the system without any similar time issue.

So I think is something related to both Gogs and my system. In one hand, because Gogs is the only app with the issue. On the other hand,,if there aren't any other Gogs users with the same problem, is obviously something related also to my system.

Do you think I can do anything to debug it? Do you think it's time to give up?

**Comment by Unknwon** [comment]
It's not a good practice to skip my comments...

> Where can I get a copy of the distribution that is same as yours? So I could setup a VM and test.

**Comment by juanfcocontreras** [comment]
Sorry, with so many comments, I missed that one.

My exact system is this one "Rocks Cluster Distribution 5.4.3":
ftp://ftp.rocksclusters.org/pub/rocks/rocks-5.4.3/linux/area51+base+bio+condor+ganglia+hpc+java+kernel+os+perl+python+sge+web-server+xen-5.4.3.x86_64.disk1.iso

It's a customized version of CentOS 5.6 for cluster systems. So I think you could use CentOS 5.6:
http://archive.kernel.org/centos-vault/5.6/isos/x86_64/CentOS-5.6-x86_64-LiveCD.iso

Thank you very much.

**Comment by Unknwon** [comment]
I downloaded the FTP one but can't seem to start installing with VirtualBox:

![image](https://cloud.githubusercontent.com/assets/2946214/13646027/a3f6ff2e-e5fb-11e5-91ea-a9a0e9c1e022.png)

**Comment by juanfcocontreras** [comment]
Is that Rocks? I think CentOS should work out of the box.

**Comment by Unknwon** [comment]
> I think CentOS should work out of the box.

It does but too minimal, looks too different than I would expect, VB plugins are not able to install either so I can't share clipboard which is a huge pain.

I'm closing this since it's more like deployment environment specific issue. Please post future updates on https://discuss.gogs.io/.

**Comment by juanfcocontreras** [comment]
Do you mind if I try to set up a VM for you?

**Comment by Unknwon** [comment]
It might be easier for you just find one with correct system time and test again.

**Comment by juanfcocontreras** [comment]
Ok, then I'll try another Git system.

If changing a cluster system with several dozens of nodes and users was an option, be sure I didn't waste your time in this thread.

Thanks anyway.

**Comment by juanfcocontreras** [comment]
Ok, then I'll try another Git system.

If changing a cluster system with several dozens of nodes and users was an option, be sure I didn't waste your time in this thread.

Thanks anyway.
