### ISSUE TITLE
Provided package for amd64 don't work

### ISSUE THREAD

**Issue by matunixe** [gogits/gogs#2787]
Hello there,

I'm unable to launch gogs.
- Gogs version (or commit ref): 0.9.0
- Git version: git-2.6.4
- Operating system: Alpine Linux
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist: Nothing

## Description
I followed the installation process and when I try to launch the daemon with `./gogs web` my shell return me `not found` and no more information. I already check the rights, the ownership, later versions (same problem) and there is no logs.

 
Thanks for helping.

**Comment by Unknwon** [comment]
You need to compile from source inside Alpine Linux in order to run, provided binaries are not static linked.

**Comment by Unknwon** [comment]
Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
