### ISSUE TITLE
特性请求：在线编辑源代码

### ISSUE THREAD

**Issue by xdsnet** [gogits/gogs#2788]
当前版本只提供了在线浏览代码的功能，而不能在线编辑，对于一些文档类的项目其实不太方便，有时一些小的问题也需要重新拖库提交。github就提供了在线编辑源代码的能力，希望在以后更新升级中能加上这个特性。
谢谢。

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1071
