### ISSUE TITLE
Issue count mismatch

### ISSUE THREAD

**Issue by ChubbyNinja** [gogits/gogs#2789]
- Gogs version (or commit ref): 0.9.0.0306
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.4 LTS 
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [x] No
  - [ ] Not relevant

The Issue count out of sync with the open issues, I do close issues sometimes via the commit message but not a lot!

![capture](https://cloud.githubusercontent.com/assets/6347946/13631430/8db36334-e5dc-11e5-8da7-2c2497c4e5e3.JPG)

**Comment by Unknwon** [comment]
Thanks your feedback!

Are you upgrading from (initially) very old version of Gogs?

**Comment by ChubbyNinja** [comment]
Originally version v0.6.0 - but i have upgraded with every release :) (not missed out any that i'm aware of)

**Comment by Unknwon** [comment]
@ChubbyNinja OK, I'll add a count corrector for issues.

**Comment by Unknwon** [comment]
What is the status of this issue right now with latest `master`?
