### ISSUE TITLE
Problem with large repository

### ISSUE THREAD

**Issue by ptman** [gogits/gogs#279]
We have a large repository (~2GB .git) with a bit under ~40k commits and over 30k files in the master branch. It cannot be pushed to an empty repository in gogs without errors. Unfortunately I cannot publish the repository as it is a commercial software product.

**Comment by b6d** [comment]
I'd like to add another data point:

We maintain a 1.2 GB repository with less than 100 commits (manually tracking a vendor).

A first push to Gogs 0.6.1 via https works, but trying to view the repository in the web interface afterwards results in a HTTP 500:

    [Macaron] Completed /vw-it/test 500 Internal Server Error in 3.783941ms
    2015/06/12 14:35:42 [repo.go:281 func·008()] [E] GetTags: 

Only after we restart Gogs web, the error goes away. Subsequent (smaller) pushes seem to work without problem. How Tags fit in this (`GetTags` from the log), I don't know, this particular repository doesn't have any Tags.

**Comment by Unknwon** [comment]
Everyone on this thread please checkout `develop` branch.

**Comment by Unknwon** [comment]
Tested with https://github.com/torvalds/linux with SSH as well.

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by Longshot123** [comment]
Is is required to use SSH to fix this problem? We are having the same issue pushing 1.4GB repo with 1255 commits over http.

**Comment by Unknwon** [comment]
@Longshot123 

> Is it required to use SSH to fix this problem?

Yes...
