### ISSUE TITLE
Diff split view not working on pull requests

### ISSUE THREAD

**Issue by mebaumgart** [gogits/gogs#2790]
The diff split view is not working on pull requests. Clicking on the Split view button does not throw an error, it just shows no difference to the unified view. It does work on single commits though. 

I have made an example on try.gogs.io:
https://try.gogs.io/meb/splitViewTest/compare/master...feature/test?style=split

- Gogs version (or commit ref): 0.9.0.0306
- Git version: 2.1.4
- Operating system: Linux x86_64
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
