### ISSUE TITLE
Feature request: Directly link to the last folder 

### ISSUE THREAD

**Issue by sapk** [gogits/gogs#2791]
In order to go quickly throw empty sub-folder and directly to the one containing files. It's could be interesting to link to folder containing file when it's a sub-folder of folder containing only one folder. To explain more easely look at this schema showing a folder structure.

/other.file
/etc -> /app -> /sub-folder -> - file.1
                                              - file.2 

For example in the root of the project clicking on the etc folder could get us directly to the sub-folder since there is nothing to see in the folder between.

I know that gitbucket does it like that :
![capture d ecran_2016-03-09_18-37-34](https://cloud.githubusercontent.com/assets/4052400/13644425/08932186-e626-11e5-9edb-bb21c310f43b.png)
 
The folder custom only contain a folder agirar01 so when we click on it we go directly to custom/agirar01.

I hope it' clear enough to understand.  :smirk:

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated to https://github.com/gogits/gogs/issues/1149
