### ISSUE TITLE
Fullname search

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2792]
- Gogs version (or commit ref): 0.9.0.0306
- Git version:
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I would not say that this is a bug but an annoyance. When one tries to invite another user to his team, Gogs only searches for the username but not the fullname. This is quite cumbersome because we use the smtp-auth-backend  and the usernames look like this: xbnd76 or klaw01. So if one does not know the username but the fullname there is nearly no way to add a user.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2831, you can test on demo site.

**Comment by stonerl** [comment]
Looks good.

**Comment by stonerl** [comment]
Closing this one.
