### ISSUE TITLE
Console logging ignores app.ini settings

### ISSUE THREAD

**Issue by minecrafter** [gogits/gogs#2798]
- Gogs version (or commit ref): 0.9.0.0306
- Git version: 1.9.1
- Operating system: Ubuntu 14.04 LTS
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [X] Not relevant
- Log gist:
```
2016/03/09 21:59:26 [T] Custom path: /home/git/gogs/custom
2016/03/09 21:59:26 [T] Log path: /home/git/gogs/log
2016/03/09 21:59:26 [I] [REDACTED] Gogs 0.9.0.0306
2016/03/09 21:59:26 [I] Log Mode: File(Info)
2016/03/09 21:59:26 [I] Cache Service Enabled
2016/03/09 21:59:26 [I] Session Service Enabled
2016/03/09 21:59:26 [I] Git Version: 1.9.1
2016/03/09 21:59:26 [I] SQLite3 Supported
2016/03/09 21:59:26 [I] Run Mode: Production
2016/03/09 21:59:26 [T] Doing: CheckRepoStats
2016/03/09 21:59:26 [I] Listen: http://127.0.0.1:3000
```
## Description

My config is:
```
[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = <snip>/log
```

However, when launching Gogs, it does an early initialization of logging (`setting.go` line 234):

```go
log.NewLogger(0, "console", `{"level": 0}`)
```

This registers a logger that logs _all_ messages to the console, regardless of if they are debug messages or errors. Furthermore, it does not seem that the settings from `app.ini` are obeyed. For instance, this config fails to stop the logging:

```
[log]
MODE      = console
LEVEL     = Info

[log.console]
LEVEL     = Info
```

**Comment by thoraxe** [comment]
I'm about to hit this issue I think... is there an ETA for a fix?

**Comment by minecrafter** [comment]
Still looking to get this fixed.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
