### ISSUE TITLE
Repository description encoding / HTML entities

### ISSUE THREAD

**Issue by ciruz** [gogits/gogs#2800]
- Gogs version (or commit ref):
- Git version:
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The repository description is not always encoded the same way. Check out my screenshots:

**Repository description:**
![01_settings](https://cloud.githubusercontent.com/assets/987947/13671440/4200d7b0-e6d0-11e5-86ed-82ccafab4e0f.PNG)

---

**Repository:**

![02_repository](https://cloud.githubusercontent.com/assets/987947/13671568/e0ad0eb0-e6d0-11e5-9d33-c89ce73854d9.PNG)

---

**Explore:**

![03_explore](https://cloud.githubusercontent.com/assets/987947/13671597/1439bbde-e6d1-11e5-8b0d-443e8c9adbfb.PNG)

---

**User profile:**

![04_profile](https://cloud.githubusercontent.com/assets/987947/13671606/1b710e70-e6d1-11e5-9c79-3b06833e6438.PNG)

**Comment by Unknwon** [comment]
Thanks your feedback!

Please post links of example on demo site.

**Comment by ciruz** [comment]
Here you go https://try.gogs.io/ciruz/dev :smiley:

**Comment by xxxtonixxx** [comment]
When I click on RAW button or "View RAW" should the README file download?? is it a bug? https://try.gogs.io/ciruz/dev/src/master/readme.md

**Comment by Unknwon** [comment]
@xxxtonixxx maybe because it has size 0. And this is not relevant to this thread.

**Comment by xxxtonixxx** [comment]
@Unknwon Hmmm, ok, sorry!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #2803 .
