### ISSUE TITLE
remote users can retrieve password from gogs 

### ISSUE THREAD

**Issue by renothing** [gogits/gogs#2801]
- Gogs version (or commit ref):0.9
- Git version:1.8.1
- Operating system:Linux
- Database:Mysql
- Can you reproduce the bug at http://try.gogs.io:
   Not relevant
- Log gist:

## Description
in fact, remote users can not be allowed to retrieve password from gogs. but I found it works fine. the "forgot password" works fine for all reomte users if you know their email.  so it's easy to do email flood for users.(also for normal local user)
 I think this should be fix and set an interval option in gogs.
...

**Comment by Unknwon** [comment]
>in fact, remote users can not be allowed to retrieve password from gogs. but I found it works fine.

I don't understand this sentence.

> the "forgot password" works fine for all reomte users if you know their email. so it's easy to do email flood for users.(also for normal local user)

I don't think it's Gogs's responsibility to keep your email account not be hacked.

**Comment by renothing** [comment]
yes, I know it, but it will take user confusion, I think remote user shouldn't be able to use "forgot password"

**Comment by zacheryph** [comment]
Define "remote user" in this case.  How else do you propose someone reset a forgotten password?

**Comment by zacheryph** [comment]
Also from what I see (at least in `0.9.1.0306`) this can not be *abused* for "mail bombing" as it does not allow you to request an email be sent multiple times.  I imagine this times out after so long but as of right now I see no obvious cause for concern.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
