### ISSUE TITLE
Suggest update golang source(net,crypto,text) from github

### ISSUE THREAD

**Issue by shionphan** [gogits/gogs#2805]
Hi,

We have more error about golang.org when install the gogs source, just because of we can not get those from google. but github also has golang source project, why we can not update golang source(net,crypto,text) form github?

if it possible, thanks a lot.

**Comment by shionphan** [comment]
go on.

We cant find those in here : https://github.com/golang. I think we cant checkout a new branch for Chinese participants. but i have no any idea about that.

**Comment by Unknwon** [comment]
Hi, there answer is that we're not allowed to do so: https://github.com/golang/crypto/blob/master/ssh/doc.go#L18

Close by 

>We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
