### ISSUE TITLE
Last updated in overview is wrong for Mirror repositories

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#2807]
- Gogs version (or commit ref): 0.9.0
- Git version: 2.1.4
- Operating system: Debian 8
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

When seeing a repository in an overview it shows e.g. `Updated 2 days ago` when there were commits 1 hour ago.

For example on try.gogs.io:
https://try.gogs.io/cs

The Go repo (https://try.gogs.io/cs/Go/commits/master) shows (at time of writing): `Updated 2 days ago`
But when I click on it, it shows commits: `1 hour ago`

Can this be fixed?
Thanks!

Rik

**Comment by nawa** [comment]
@rikvdh I can't reproduce this. Does bug exist now?

**Comment by xor-gate** [comment]
I have tried to create a repository and waited for a few minutes

* On try.gogs.io 
* Version 0.9.33.0630

The following html is generated (https://try.gogs.io/admin1 - repo test_issue_2807):
```html
<p class="time">Updated <span class="time-since" title="Thu, 30 Jun 2016 09:00:45 EDT">3 minutes ago</span></p>
```

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
