### ISSUE TITLE
Gogs building issue

### ISSUE THREAD

**Issue by de-live-gdev** [gogits/gogs#2808]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 97c48da49fb8493059d5b52e435fadc508c78966
- Git version: 2.1.4
- Operating system: Debian x64
- Database:
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x ] Not relevant
- Log gist: https://gist.github.com/de-live-gdev/72a210306c11cdcb8d59

## Description
Gogs can't be builded on develop branch, see gist.
Seems to be a dependency problem.

**Comment by Unknwon** [comment]
Hi, looks like you're not having everything up-to-date?

Please do `go get -u .`.

**Comment by de-live-gdev** [comment]
I definitely updated every thing (using `go get -u .` and `go get -u ...`) . I even deleted go-oxrm folder and pulled the latest version again using go get. I checked the sha, and its the latest version from master.

**Comment by Unknwon** [comment]
What is your Go version?

**Comment by de-live-gdev** [comment]
Thanks, updating Go to 1.6 resolved the issue.  
Seems like a recent commit made changes that were not compatible with the old version.

**Comment by Unknwon** [comment]
How ` old version` was it？

**Comment by de-live-gdev** [comment]
1.4.3

**Comment by Unknwon** [comment]
It should work, I use this version compile sometimes...
