### ISSUE TITLE
LDAP User can change his/her password.

### ISSUE THREAD

**Issue by barracks510** [gogits/gogs#2811]
- Gogs version (or commit ref): 0.9.0
- Git version: 1.8
- Operating system: GNU/Linux
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:
No log entry describes the problem

## Description
LDAP Users who click on "Forgot Password" are able to reset his/her password. However, this is not the desired or consistent behavior. "Forgot Password" should identify the login source, and display an error to the user if the password cannot be changed.

**Comment by zacheryph** [comment]
I will claim this ticket.  Will let know if something comes up or have any questions.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2823, please help test under `develop` branch.

**Comment by Unknwon** [comment]
Close as fixed.
