### ISSUE TITLE
packets.go:33: unexpected EOF

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2812]
- Gogs version (or commit ref): 0.9.0.0306 
- Git version: 2.1.4
- Operating system: Debian Jessie 8.3
- Database: 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

I'm using Monit to track service behavior. I have seen an increase in Gogs changing it's PID. (it's seems te be restarting) This happens with the following error message. 

`[mysql] 2016/03/11 14:33:10 packets.go:33: unexpected EOF`

I did found this issue: https://github.com/gogits/gogs/issues/721 I am unsure if it is the same problem, I don't see any `broken pipe` messages.

**Comment by Unknwon** [comment]
It would be better if you can dump more logs about what Gogs is doing before this error.

**Comment by drsect0r** [comment]
@Unknwon I checked the following log files /var/log/gogs/gogs.log, /var/log/gogs/xorm.log and /var/log/gogs/http.log. These where all empty. I get this error message from /var/log/daemon.log.

I noticed that there seems to be no consistency. I'm the only user of this Gogs installation and it happens without me being active on Gogs. I

```
Mar 11 10:01:37 gogs-web-1.service[21692]: 2016/03/11 10:01:37 #033[1;36m[T] Doing: MirrorUpdate#033[0m
Mar 11 10:01:37 gogs-web-1.service[21692]: [mysql] 2016/03/11 10:01:37 packets.go:33: unexpected EOF
Mar 11 10:17:35 gogs-web-1.service[21692]: [Macaron] Started GET /... for ...
Mar 11 10:17:35 gogs-web-1.service[21692]: [mysql] 2016/03/11 10:17:35 packets.go:33: unexpected EOF
```
```
Mar 11 11:01:37 gogs-web-1.service[21692]: 2016/03/11 11:01:37 #033[1;36m[T] Doing: MirrorUpdate#033[0m
Mar 11 11:01:37 gogs-web-1.service[21692]: 2016/03/11 11:01:37 #033[1;36m[T] Doing: GitFsck#033[0m
Mar 11 11:01:37 gogs-web-1.service[21692]: 2016/03/11 11:01:37 #033[1;36m[T] Doing: CheckRepoStats#033[0m
Mar 11 11:01:37 gogs-web-1.service[21692]: [mysql] 2016/03/11 11:01:37 packets.go:33: unexpected EOF
```
```
Mar 11 14:33:10 gogs-web-1.service[21692]: [Macaron] Started GET ... for ...
Mar 11 14:33:10 gogs-web-1.service[21692]: [mysql] 2016/03/11 14:33:10 packets.go:33: unexpected EOF
Mar 11 14:33:10 gogs-web-1.service[21692]: [mysql] 2016/03/11 14:33:10 packets.go:33: unexpected EOF
```
```
Mar 11 15:01:37 gogs-web-1.service[21692]: 2016/03/11 15:01:37 #033[1;36m[T] Doing: MirrorUpdate#033[0m
Mar 11 15:01:37 gogs-web-1.service[21692]: [mysql] 2016/03/11 15:01:37 packets.go:33: unexpected EOF
```
```
Mar 11 16:01:37 gogs-web-1.service[21692]: 2016/03/11 16:01:37 #033[1;36m[T] Doing: MirrorUpdate#033[0m
Mar 11 16:01:37 gogs-web-1.service[21692]: [mysql] 2016/03/11 16:01:37 packets.go:33: unexpected EOF
```

**Comment by Unknwon** [comment]
Thanks, this is indeed very helpful!

**Comment by drsect0r** [comment]
@Unknwon _I'm not sure if this is related:_ My infrastructure currently consists of multiple virtual servers all behind a central firewall. My logs are indicating that there are hundreds of packets being blocked flowing from my dedicated Gogs server to my database server. 

This is very unusual behavior for the following reasons:

- virtual machines are all behind a DMZ furthermore internally, every server can access the database server without any limitations;
- this server is dedicated to Gogs and this is the only server that presents these symptoms.

There are around 400 events a day with the above criteria. I'm going to stop the Gogs process for the night to see if this stops the firewall events from coming in.

**Comment by dinacel** [comment]
With MariaDB on Debian 8, that's what I have with tcp connection:

```
Mar 20 08:26:00 gogs-web-1.service[6942]: 2016/03/20 08:26:00 #033[1;36m[T] Doing: MirrorUpdate#033[0m
Mar 20 08:26:00 gogs-web-1.service[6942]: [mysql] 2016/03/20 08:26:00 packets.go:33: unexpected EOF
Mar 20 08:26:00 gogs-web-1.service[6942]: [mysql] 2016/03/20 08:26:00 packets.go:124: write tcp 127.0.0.1:43876->127.0.0.1:3306: write: broken pipe
```

If I connect to MariaDB through an unix socket I have similar results:

```
Mar 22 11:28:15 poseidon gogs-web-1.service[29293]: 2016/03/22 11:28:15 #033[1;36m[T] Doing: MirrorUpdate#033[0m
Mar 22 11:28:15 poseidon gogs-web-1.service[29293]: [mysql] 2016/03/22 11:28:15 packets.go:124: write unix @->/var/run/mysqld/mysqld.sock: write: broken pipe
Mar 22 11:28:15 poseidon gogs-web-1.service[29293]: [mysql] 2016/03/22 11:28:15 packets.go:124: write unix @->/var/run/mysqld/mysqld.sock: write: broken pipe
```

I didn't debug more, but it seems gogs try to used a closed connection (closed by wait_timeout probably).

**Comment by mehmet6parmak** [comment]
I am able to re-produce the issue with a push command, i can provide further details if that would help,

the logs in the console is as follows,  
`[Macaron] 2016-08-10 09:04:02: Started POST /mehmet6parmak/mdis/git-receive-pack for 10.10.12.205
[Macaron] 2016-08-10 09:04:02: Completed /mehmet6parmak/mdis/git-receive-pack 500 Internal Server Error in 2m0.0573797s
2016/08/10 09:04:02 [D] Session ID: 87e9551ed2cbfb32
2016/08/10 09:04:02 [D] CSRF Token: ja6zhpOD-mdwFDT4dctKyEBKv9Q6MTQ3MDgwOTA0MjI4NzI4MzcwMA==
[Macaron] 2016-08-10 09:06:02: Completed /mehmet6parmak/mdis/git-receive-pack 500 Internal Server Error in 1m59.9975621
[Macaron] 2016-08-10 09:06:02: Started POST /mehmet6parmak/mdis/git-receive-pack for 10.10.12.205
2016/08/10 09:06:02 [D] Session ID: e8ff524210796910
2016/08/10 09:06:02 [D] CSRF Token: VcS7Ys8Y4JO62WgsCX_1qwlmF3s6MTQ3MDgwOTE2MjUzNTg2MDEwMA==
[Macaron] 2016-08-10 09:06:02: Completed /mehmet6parmak/mdis/git-receive-pack 500 Internal Server Error in 236.0135ms
[Macaron] 2016-08-10 09:06:02: Started POST /mehmet6parmak/mdis/git-receive-pack for 10.10.12.205
2016/08/10 09:06:02 [D] Session ID: a2c396ccc7a57942
2016/08/10 09:06:02 [D] CSRF Token: HmIvg_WgkWq2EeLj7pTwMrCaQ-06MTQ3MDgwOTE2Mjc4NDg3NDQwMA==
[Macaron] 2016-08-10 09:08:02: Started POST /mehmet6parmak/mdis/git-receive-pack for 10.10.12.205
[Macaron] 2016-08-10 09:08:02: Completed /mehmet6parmak/mdis/git-receive-pack 500 Internal Server Error in 2m0.0441118s
2016/08/10 09:08:02 [D] Session ID: c76942b67004b65d
2016/08/10 09:08:02 [D] CSRF Token: admzWprYPn8mFm-rVatmPhN7rfA6MTQ3MDgwOTI4MjgyODk4NjEwMA==
[Macaron] 2016-08-10 09:10:02: Completed /mehmet6parmak/mdis/git-receive-pack 500 Internal Server Error in 2m0.0368658s
2016/08/10 09:13:23 [T] Doing: MirrorUpdate
2016/08/10 09:23:23 [T] Doing: MirrorUpdate`

Logs from http.log:

`2016/08/10 09:06:02 [...routers/repo/http.go:383 serviceRPC()] [E] fail to serve RPC(receive-pack): exit status 128
2016/08/10 09:08:02 [...routers/repo/http.go:368 serviceRPC()] [E] fail to read request body: unexpected EOF
2016/08/10 09:10:02 [...routers/repo/http.go:368 serviceRPC()] [E] fail to read request body: unexpected EOF`

Git push command output,

`Counting objects: 1873, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1782/1782), done.
error: RPC failed; result=56, HTTP code = 0
fatal: WThe remote end hung up unexpectedly
Writing objects: 100% (1873/1873), 17.65 MiB | 33.00 KiB/s, done.
Total 1873 (delta 344), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
Everything up-to-date`

**Comment by Unknwon** [comment]
@mehmet6parmak thanks for the report, but what you have is not the same thing here.

**Comment by mehmet6parmak** [comment]
uh, sorry about that, i am creating a new issue and deleting the previous comment not to pollute here, thanks.

**Comment by Unknwon** [comment]
Please notify when this happens again.
