### ISSUE TITLE
SSH links retain [server] DOMAIN after changing [server] ROOT_URL

### ISSUE THREAD

**Issue by furhouse** [gogits/gogs#2813]
For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.1.0306 
- Git version: 2.6.4
- Operating system: docker gogs/gogs tag latest id cb017a6b346e 
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I've set up a reverse proxy for the docker, changed the `[server] ROOT_URL` accordingly, it only seems to change the HTTP link, the SSH link retains the `[server] DOMAIN`. This seems to happen with existing and new repositories.

https://gist.github.com/furhouse/5eb51f3e09cbb1c064be

...

**Comment by Unknwon** [comment]
Thanks your feedback!

But why it should not retain?

**Comment by Unknwon** [comment]
Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

**Comment by furhouse** [comment]
Thanks, `[server] SSH_DOMAIN` is exactly what I was looking for. It would make a good addition to the FAQ regarding the reverse proxy.

If the IP of the docker/server running gogs would change, you'll end up having to change the remote urls of existing repositories which used ssh, instead of having to purge a single entry from a KnownHost file if it retains.

**Comment by Unknwon** [comment]
If you wrong domain, what you put right now is IP, not domain, which should be `git.example.lan`.
