### ISSUE TITLE
Allow searching for users by full name

### ISSUE THREAD

**Issue by richmahn** [gogits/gogs#2814]
With the search on the explore/users and admin users page, it would be nice to also be able to search the full_name of the user. Thus the search would search for the username OR the full_name.

**Comment by stonerl** [comment]
#2792

**Comment by richmahn** [comment]
@stonerl: This is a little different. This is regarding the new search field at the top of expore/users and the users page in the admin tools, not when adding a user to a team.

**Comment by stonerl** [comment]
@richmahn I know, but I think that this feature should not only be available in certain parts of gogs but in general. Therefore I referenced the issue I opened, because both have the request for full name search in common.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2831, you can test on demo site.

**Comment by richmahn** [comment]
This is not working for me...I just updated from develop, did a rebuild...restarted server...still nothing: http://test.door43.org:3000/explore/users?q=Admini (yet if you remove the last 'i' it finds admin)

**Comment by richmahn** [comment]
hmm, but it does work on try.gogs.io. Maybe doesn't work with Postgres? Will troubleshoot.

**Comment by moltam** [comment]
I think it is PostgreSQL specific, the search is case sensitive: `SELECT count(*) FROM user WHERE ((lower_name like ?) OR (full_name like ?)) AND (type = ?)`.

Because the keyword is [transformed into lower case](https://github.com/odinuge/gogs/blob/6ccb2d36cfbe030cb1a72263d6889e79d738df3f/models/user.go#L1131) the search only finds lower case names with PostreSQL.

**Comment by odinuge** [comment]
That could be the case... I dont have PostgreSQL accessible right now, so i can't test.

Here is a patch you can try: [search-sql-case](https://github.com/odinuge/gogs/tree/search-sql-case)

**Comment by Unknwon** [comment]
Looks like a workaround: http://stackoverflow.com/questions/7005302/postgresql-how-to-make-not-case-sensitive-queries

**Comment by moltam** [comment]
It works with `LOWER(full_name) like ?`.

**Comment by Unknwon** [comment]
Not sure... have not tested...

**Comment by moltam** [comment]
@Unknwon I tested it, and it does :)

**Comment by richmahn** [comment]
Is it also calling LOWER() on the search term?

**Comment by moltam** [comment]
Search term is already in lower case for lower_name search. No need for calling LOWER on it.

**Comment by richmahn** [comment]
Right, I realize that is the reason this is failing, because the search term is always lower.

**Comment by richmahn** [comment]
Is there a pull request for the fix?

**Comment by Unknwon** [comment]
Looks like MySQL,SQLite3 and PostgreSQL all have `LOWER()`, I'm working on it.

**Comment by Unknwon** [comment]
@richmahn can you pull `develop` again?

**Comment by richmahn** [comment]
@Unknwon Done. It works! :+1:

**Comment by Unknwon** [comment]
Close as implemented.
