### ISSUE TITLE
config ssl main domain and subdomain bug

### ISSUE THREAD

**Issue by shionphan** [gogits/gogs#2820]
- Gogs version (or commit ref): 0.9.1.0306 
- Git version: 1.9.1
- Operating system: Ubuntu 14.4
- Database:
  - [ ] PostgreSQL
  - [+] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [+] No
  - [ ] Not relevant
- Log gist:

## Description

Setup Nginx reverse proxy for gogs, I configed ssl on the nginx server, everything is ok.

This is app.ini:

```
[server]

DOMAIN = domain.com
ROOT_URL = https://domain.com/
CERT_FILE = custom/https/cert.pem
KEY_FILE = custom/https/key.pem
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false
ENABLE_GZIP = true
LANDING_PAGE = explore
```

This is Nginx config:

```
server {  
    listen 443 ssl;
    server_name domain.com;
    ssl_certificate /home/git/go/src/github.com/gogits/gogs/custom/https/cert.pem;
    ssl_certificate_key /home/git/go/src/github.com/gogits/gogs/custom/https/key.pem;

    location = /favicon.ico {
        try_files /home/www/static/images/favicon.ico =404;
    }

    location / {
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_pass http://127.0.0.1:3000$request_uri;
    }
}
```

When i visit https://www.domain.com, the page style was worked, bug https://domain.com was not. then console display error:

(from semantic-2.1.8.min.js:16 Popup: Popup does not fit within the boundaries of the viewport ....)
```
Popup: Popup does not fit within the boundaries of the viewport <div class=​"ui dropdown head link jump item poping up" data-content=​"用户信息及更多" data-variation=​"tiny inverted" tabindex=​"0">​…​</div>​
Popup: Popup does not fit within the boundaries of the viewport <div class=​"ui dropdown head link jump item poping up" data-content=​"创建..." data-variation=​"tiny inverted" tabindex=​"0">​…​</div>​
Popup: Popup does not fit within the boundaries of the viewport <div class=​"ui dropdown head link jump item poping up" data-content=​"用户信息及更多" data-variation=​"tiny inverted" tabindex=​"0">​…​</div>​
```

All of there

**Comment by Unknwon** [comment]
Gogs can work with or without a domain, and I don't think it has anything to do with SSL...

Basically I don't know what are you talking...

Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
