### ISSUE TITLE
Subtle register captcha url problem

### ISSUE THREAD

**Issue by hosiet** [gogits/gogs#2821]
- Gogs version (or commit ref): packages.io latest (201603)
- Git version: debian unstable latest
- Operating system: Debian unstable
- Database:
  - [ ] PostgreSQL
  - [ X ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [ X ] Not relevant
- Log gist:

## Description
I have noticed that gogs was smart enough to rewrite all its URL by adding URL prefix (which is configured by admin) to all its URLs in the webpages. For example, the signin page would be http://mydomain.name/git/user/sign_up if I set the prefix to be "mydomain.name/git/".

Just one exception: the URL of captcha image. It remains to be "/captcha....", which made the captcha unusable.

I am using packages.io deb file for installation, with Apache2 2.4.18 as reverse proxy server to localhost:3000. I must set a `RewriteRule` explicitly to workaround this problem.

**Comment by Unknwon** [comment]
Hi,

Captcha does have reverse sub-path support. I think it's your config problem for `ROOT_URL`.

Close by 

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

**Comment by hosiet** [comment]
I'm sure that `ROOT_URL` is correctly set (e.g., `https://example.com/git/`). Anyway, we could just leave this issue here and see if there could be more similar cases in the future.
