### ISSUE TITLE
Problems with '#' in branch name

### ISSUE THREAD

**Issue by dafes** [gogits/gogs#2822]
- Gogs version (or commit ref):  0.9.0.0306
- Operating system: debian
- GIT: 2.14
- Database:
  - MySQL
- Can you reproduce the bug at http://try.gogs.io:
  - [X ] Yes

Hi,
with an '#' in the Tag name a diff and Pull-Requests creation are not possible.
You only receive a Page Not Found 404
Example:
https://try.gogs.io/dafes/test123/compare/test#11...master

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2830, you can test on the demo site.

**Comment by Unknwon** [comment]
Close as fixed.
