### ISSUE TITLE
Error when user is in multiple teams in the organization

### ISSUE THREAD

**Issue by lammas** [gogits/gogs#2827]
- Gogs version (or commit ref): 0.9.0
- Git version: 2.1.4
- Operating system: Debian jessie
- Database: PostgreSQL
- Can you reproduce the bug at http://try.gogs.io: No
- Log gist:

    [...routers/user/home.go:336 showOrgProfile()] [E] GetUserRepositories: get repositories: pq: invalid input syntax for integer: "1,3"

## Description
When user is in multiple teams the organization dashboard gives error 500.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2727
