### ISSUE TITLE
Add mattermost integration

### ISSUE THREAD

**Issue by geromueller** [gogits/gogs#2834]
http://www.mattermost.org/ is a perfect match to gogs, as it is also in Go and uses same databases ~~and is MIT licencend~~.

Mattermost should be Slack compatible, but currently it does not work.

The response is 500 "Channel not found.".

**Comment by graywolf336** [comment]
Since both Mattermost and Rocket.Chat accept Slack's format of webhooks, I would like the option to turn the Slack webhook option into one where we can just input the url where we want the webhook to be posted to. This way we can ideally use it for both Mattermost and Rocket.Chat without much work.

**Comment by geekgonecrazy** [comment]
This would be great, looks like its just pulling the team name and id out of the url.  So if we could just accept the URL as is?

@geromueller just a note.  Only the binary they(mattermost) distributes is MIT.  The rest AGPLv3 :frowning: got me at first too.

**Comment by engelgabriel** [comment]
It would be awesome to include Rocket.Chat integration too, should we open another issue for the feature request?

**Comment by graywolf336** [comment]
@engelgabriel The way I suggested in my comment above would eliminate the need to have chat specific plugins and instead have a "slack payload format", which both Rocket.Chat and Mattermost are able to use those.

**Comment by engelgabriel** [comment]
Yes, understood, but it if is not clearly stated that users can use Rocket.Chat, it may not be used. They can use the same code, but it would be nice if the name Rocket.Chat appears on the list.

**Comment by saboya** [comment]
Well, it already works. Just select Slack and set the payload URL to yout Mattermost webhook URL. I tested this today and it worked fine. Customizing icon URL did not work, but I'm unsure if this is a Gogs problem. More investigation is needed.

**Comment by graywolf336** [comment]
Due to @saboya's comment, I decided to give it another shot and it worked nicely with Rocket.Chat! The channel, username, icon url, and color all worked like one would expect them to on the push event (I haven't tested the Create event). So, maybe just a wording change is all that would be helpful for others.
![screen shot 2016-03-19 at 9 47 08 pm](https://cloud.githubusercontent.com/assets/850391/13902592/2e146796-ee1c-11e5-98eb-6e5a2f9a1bf4.png)

**Comment by Unknwon** [comment]
So.... what is the situation right now?

**Comment by saboya** [comment]
@Unknwon Mattermost uses the same API as Slack for incoming webhooks, so it already works.

**Comment by Unknwon** [comment]
OK, closing now.

**Comment by geromueller** [comment]
Actually it does NOT work, thats what i wrote in my initial post. MM 2.1 requires the Channel field to be empty, but gogs requires this field. You receive the message "Channel not found!"

**Comment by saboya** [comment]
@geromueller I currently have MM 2.1 running, and it works just fine. Where in the documentation it says that channel has to be empty?

http://docs.mattermost.com/developer/webhooks-incoming.html

**Comment by engelgabriel** [comment]
@Unknwon: Is it ok if we submit a PR with the changes on wording to explain that you can use the Slack integration for Rocket.Chat and Mattermost?

**Comment by Unknwon** [comment]
@engelgabriel Yes.

**Comment by Unknwon** [comment]
Hint:

1. https://github.com/gogits/gogs/blob/master/templates%2Frepo%2Fsettings%2Fhook_slack.tmpl#L2
2. https://github.com/gogits/gogs/blob/master/conf%2Flocale%2Flocale_en-US.ini#L660
3. `make bindata`

**Comment by engelgabriel** [comment]
@geekgonecrazy or @geekgonecrazy can you do this?

**Comment by geromueller** [comment]
Since it works for @saboya i played around a bit. It indeed works but:
- the MM docs says you should leave the channel empty, to use the channel assisiated with the api key in the hook (thats what i referred to by the initial post). Since this does not work in gogs you have to provide a channel
- The channel name is all lower cases! That's why it did not work for me. I guess this is kind of of MM bug.

The ticket can stay closed in terms of implementation, but should be opened here or somewher else as text/docs is concerened.

Cheers!

**Comment by saboya** [comment]
The "empty channel" instruction is [specific to the GitLab integration](http://docs.mattermost.com/developer/webhooks-incoming.html#connecting-mattermost-to-gitlab-using-slack-ui).

In regular use, the channel has to be the same as displayed in the channel URL. For example:

https://example.mattermostserver.com/<TEAM_NAME>/<CHANNEL_URL>/

<CHANNEL_URL> would be the correct string to use.
