### ISSUE TITLE
exec: "git": executable file not found in $PATH

### ISSUE THREAD

**Issue by sunzhiguang** [gogits/gogs#2839]
whereis git
git: /usr/local/git

输入git
git version 2.7.0

path
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/usr/local/nginx/sbin:/usr/local/mongodb/bin:/usr/local/git/bin:/root/bin:/usr/local/go/bin:/usr/local/nginx/sbin:/usr/local/git/bin:/usr/local/mongodb/bin:/usr/local/go/bin:/usr/local/nginx/sbin:/usr/local/git/bin:/usr/local/mongodb/bin:/usr/local/go/bin:/usr/local/nginx/sbin:/usr/local/git/bin/:/usr/local/mongodb/bin

**Comment by Unknwon** [comment]
Hi, if you start with script, you need to add `git` path to your `PATH` as well.

Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

**Comment by sunzhiguang** [comment]
start with  sudo ./gogs web  then....

**Comment by Unknwon** [comment]
`sudo` does not guarantee have `git` in `PATH`.

**Comment by sunzhiguang** [comment]
but  login with user git  
echo path 
show /usr/local/go/bin:/usr/local/nginx/sbin:/usr/local/git/bin/:/usr/local/mongodb/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

**Comment by Unknwon** [comment]
1. I don't understand why you use `sudo`.
2. `sudo` does not guarantee have `git` in `PATH`.

**Comment by sunzhiguang** [comment]
start ./gogs web 
install  
Connect to database: Fail to create directories: mkdir data: permission denied

**Comment by Unknwon** [comment]
Give the permission to `git` user then.

**Comment by Unknwon** [comment]
http://stackoverflow.com/questions/12996397/command-not-found-when-using-sudo

**Comment by sunzhiguang** [comment]
thanks
