### ISSUE TITLE
build problem with 0.9.0

### ISSUE THREAD

**Issue by ibotty** [gogits/gogs#2840]
- Gogs version (or commit ref):
   git tag 0.9.0
- Operating system:
  Alpine v3.3
- Database:
  Not relevant
- Can you reproduce the bug at http://try.gogs.io:
  Not relevant
- Log gist:

```
routers/api/v1/convert/convert.go:42: unknown gogs.Repository field 'Id' in struct literal
routers/api/v1/convert/convert.go:43: cannot use *ToApiUser(owner) (type gogs.User) as type gogs.User in field value
```

## Description
I cannot build gogs 0.9.0 using go 1.5.3 on docker hub.

See the full log on https://hub.docker.com/r/ibotty/gogs/builds/bbzvwlxkycnzgq9mhtvdboq/

The docker file is on https://github.com/ibotty/openshift-gogs

...

**Comment by ibotty** [comment]
I can reproduce the bug using go 1.5.3 in fedora 23.

**Comment by Unknwon** [comment]
Hi, please update all deps with `go get -u .`.

**Comment by ibotty** [comment]
That does not work when building from a release (i.e. w/o .git directory):

    > go get -u -v -tags sqlite redis memcache cert pam 
    package github.com/gogits/gogs: directory "/tmp/go/src/github.com/gogits/gogs" is not using a known version control system 

Furthermore, I don't think that a docker build (that starts pristine) has stale go dependencies somewhere. Maybe I don't quiet understand go's build system.

**Comment by ibotty** [comment]
Running (locally) `go get -u ...` resets my v0.9.0 checkout to master and builds fine. When I check v0.9.0 out again and `go get ...` without `-u`, I get the mentioned error. How can one build the v0.9.0 release? Is there some arcane command line switch to `go get` to check out versions that work together?

**Comment by Unknwon** [comment]
@ibotty Why not use 0.9.0 official Docker image?

**Comment by ibotty** [comment]
Reasons ;). In short, it does too much and runs as root. My image can be run either as ssh container or gogs container. Both run as non-root and run only one process. They have to use the same uid and access the same file system/volume though. Kubernetes' Pod abstraction allows that. (I plan to wrap the actual uid with nss_wrapper, so it can be specified by the cluster orchestration)

The most important part is that it runs an non-root.

**Comment by Unknwon** [comment]
You could try fetch dependencies though gopm, other ways... I don't know...

**Comment by ibotty** [comment]
Ah, I see. So there is no way for standard go to specify dependency version ranges? That's unexpected. I'll have to rethink my approach on how I docker-package go applications... Thank you for your input.

**Comment by Unknwon** [comment]
> Ah, I see. So there is no way for standard go to specify dependency version ranges?

No way, indeed...
