### ISSUE TITLE
Display full name

### ISSUE THREAD

**Issue by stonerl** [gogits/gogs#2841]
For bug reports, please give the relevant info:

- Gogs version (or commit ref):
- Git version: 0.9.0
- Operating system: Ubuntu 14.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

This is somewhat similar to this issue #2792. When one hovers over an username, e.g. in the People overview in an organisation, Gogs only shows the username. If the username looks like this: xbsh01 it is very hard to distinguish who this user is. It would be nice if the full name could be displayed as well. E.g. in braces, much like it is displayed when one adds a user to a team.

**Comment by moltam** [comment]
Do you mean this part (hovering on an avatar)?

![41d92ace_o](https://cloud.githubusercontent.com/assets/4578365/13828339/509b3702-ebc1-11e5-9b68-6588f1f3e5ed.png)

@Unknwon I can do this.

**Comment by stonerl** [comment]
@moltam Yes.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2845, you can test on demo site.

**Comment by stonerl** [comment]
Looks good, closing this one.
