### ISSUE TITLE
Incorrect diff after rebase

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2843]
- Gogs version (or commit ref): 0.9.0.0306 
- Git version: 2.1.4
- Operating system: Debian Jessie 8.3
- Database: 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

After rebasing (private server) I noticed  that the diff is showing incorrect information. In my rebase work I change the word server to service. However this is what Gogs diff shows:

![screenshot from 2016-03-16 18-30-18](https://cloud.githubusercontent.com/assets/9106228/13822249/3173f0d8-eba5-11e5-8969-43b83e249472.png)

**Comment by Unknwon** [comment]
Hi, I think you can reproduce an example on http://try.gogs.io?

**Comment by drsect0r** [comment]
@Unknwonnot at the moment, will try to reproduce after the weekend.

**Comment by Unknwon** [comment]
ping @drsect0r

**Comment by drsect0r** [comment]
@Unknwon pong, apologies for the delay. I can reproduce: https://try.gogs.io/testdemo/test/compare/b4cc027402b9c66282f226228c7f23608f7dc7d0...c0c825c9c512be98818297b8f25aefab1796b8a5

**Comment by Unknwon** [comment]
Thanks, so what is expected "right", and what is "wrong" right now?

**Comment by drsect0r** [comment]
@Unknwon Good question, I'm not sure if it is meant like this but the diff just seemed very odd to me. 

- the coloring of the individual letters (I understand that what I did and I understand why the `r` is red and `ic` is green, I just feel that it takes to much thinking for somebody not familiar with my commit what happens here + also why not server with a red `r` and service with green `ic` ) 
- serv**c**er and servic**c**e? (where did the extra c come from?)
- why is this not simply server and service as green red?

**Comment by Unknwon** [comment]
If you run `git diff xxx yyy` with same arguments (commit SHA), what do you get?

**Comment by drsect0r** [comment]
@Unknwon Sorry for the late repley. On both tries I get `fatal: bad object 'commit hash'`

**Comment by Unknwon** [comment]
.... `xxx` and `yyy` are just placeholders, use real hash on your repository.

**Comment by drsect0r** [comment]
... That I understood. :-)

**Comment by drsect0r** [comment]
@Unknwon That I understand. Thank you. 

```
$ git clone https://try.gogs.io/testdemo/test.git
Cloning into 'test'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
                                                                
$ cd test 

$ git diff b4cc027402b9c66282f226228c7f23608f7dc7d0 c0c825c9c512be98818297b8f25aefab1796b8a5
fatal: bad object b4cc027402b9c66282f226228c7f23608f7dc7d0

$ git diff c0c825c9c512be98818297b8f25aefab1796b8a5 b4cc027402b9c66282f226228c7f23608f7dc7d0
fatal: bad object b4cc027402b9c66282f226228c7f23608f7dc7d0
```

**Comment by Unknwon** [comment]
I think you need do `git diff b4cc027402b9c66282f226228c7f23608f7dc7d0...c0c825c9c512be98818297b8f25aefab1796b8a5`.

**Comment by drsect0r** [comment]
@Unknwon 
```
$ git clone https://try.gogs.io/testdemo/test.git
Cloning into 'test'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.

$ cd test

$ git diff b4cc027402b9c66282f226228c7f23608f7dc7d0...c0c825c9c512be98818297b8f25aefab1796b8a5
fatal: Invalid symmetric difference expression b4cc027402b9c66282f226228c7f23608f7dc7d0...c0c825c9c512be98818297b8f25aefab1796b8a5

$ git diff c0c825c9c512be98818297b8f25aefab1796b8a5...b4cc027402b9c66282f226228c7f23608f7dc7d0                                           
fatal: Invalid symmetric difference expression c0c825c9c512be98818297b8f25aefab1796b8a5...b4cc027402b9c66282f226228c7f23608f7dc7d0
```

**Comment by Unknwon** [comment]
I might know the problem, can you provide reproduce steps?

**Comment by drsect0r** [comment]
@Unknwon It's the usual, create an empty repository and commit files. Push this to server and do some rebasing, after this do a push -f.

**Comment by Unknwon** [comment]
Note: the data are right based on the commits that are compared. But Gogs should however, detects correct two commits to compare.

**Comment by Unknwon** [comment]
Please notify when this happens again.
