### ISSUE TITLE
LDAP - Confirm if user belongs to group, without memberOf overlay

### ISSUE THREAD

**Issue by tuudik** [gogits/gogs#2844]
Please help me understand what filter to use to check if logged in user belongs to certain group (in my case group with gid number 10007),
without using memberOf overlay. Is it even possible? If yes, then how?

Currently I have tried it with using filter:
```
(&(objectClass=posixGroup)(gidNumber=10007))
```

Here's a flow how application is currently logging in user through LDAP.

Logging user in:
```
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=0 BIND dn="cn=AppUser,ou=Service Accounts,dc=domain,dc=com" method=128
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=0 BIND dn="cn=AppUser,ou=Service Accounts,dc=domain,dc=com" mech=SIMPLE ssf=0
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=0 RESULT tag=97 err=0 text=
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=1 SRCH base="dc=domain,dc=com" scope=2 deref=0 filter="(&(uid=AdminUser)(objectClass=posixAccount))"
Mar 16 08:54:50 mail slapd[1073]: <= bdb_equality_candidates: (uid) not indexed
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=2 SRCH base="cn=Admin User,ou=Admins,dc=domain,dc=com" scope=2 deref=0 filter="(&(uid=AdminUser)(objectClass=posixAccount))"
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=2 SRCH attr=uid givenName sn mail
Mar 16 08:54:50 mail slapd[1073]: <= bdb_equality_candidates: (uid) not indexed
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=2 SEARCH RESULT tag=101 err=0 nentries=1 text=
```

Check if user belongs to group with gid number:
```
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=3 SRCH base="cn=Admin User,ou=Admins,dc=domain,dc=com" scope=2 deref=0 filter="(&(objectClass=posixGroup)(gidNumber=10007))"
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=3 SRCH attr=givenName
Mar 16 08:54:50 mail slapd[1073]: <= bdb_equality_candidates: (gidNumber) not indexed
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=3 SEARCH RESULT tag=101 err=0 nentries=0 text=
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=4 BIND anonymous mech=implicit ssf=0
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=4 BIND dn="cn=Admin User,ou=Admins,dc=domain,dc=com" method=128
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=4 BIND dn="cn=Admin User,ou=Admins,dc=domain,dc=com" mech=SIMPLE ssf=0
Mar 16 08:54:50 mail slapd[1073]: conn=2424 op=4 RESULT tag=97 err=0 text=
Mar 16 08:54:50 mail slapd[1073]: conn=2424 fd=23 closed (connection lost)
```

**Comment by Unknwon** [comment]
cc @nanoant @SergioBenitez can you guys help, thx!

**Comment by tuudik** [comment]
Actually I would like to note out, perhaps it would be better, if the admin filter would work, by comparing the user to users in group that is defined as Admin group.

**Comment by SergioBenitez** [comment]
@tuudik: That's much too specific, constricting, and a potential security vulnerability. The current implementation allows you to do this and more.

By the way, do your LDAP user entries have a `gidNumber` attribute? Have you tried your query using `ldapsearch`? The query (of course, using a different server/binddn/base) works for me. Your base looks a bit odd, by the way: there's no user group.

Try something like the following to confirm that your LDAP parameters are correct:

```
ldapsearch -H "ldap://yourldapserver" -D "cn=AppUser,ou=Service Accounts,dc=domain,dc=com"  -b "dc=domain,dc=com" "(&(objectClass=posixAccount)) -W"
```

Then, change the query to match against the `gid` as well:

```
ldapsearch -H "ldap://yourldapserver" -D "cn=AppUser,ou=Service Accounts,dc=domain,dc=com"  -b "dc=domain,dc=com" "(&(objectClass=posixAccount)(gidNumber=10007)) -W"
```

If the former works but not the latter, ensure users have the `gidNumber` attribute. If the latter works, and the parameters match what you've input into Gogs exactly, then there's a problem with Gogs.

**Comment by tuudik** [comment]
Here's my LDAP structure, perhaps this would help to understand the situation:)
```
domain.com
	Service Accounts (Application Bind Users)
		AppUser
	Admins (Admin accounts)
		AdminUser
	Persons (regular accounts)
		Ted
		Kelly
		Ned
	Groups (Groups to define access level to applications)
		GogsAdmins
		GogsUsers
```

**Comment by SergioBenitez** [comment]
Did you try the commands? That doesn't help very much.

**Comment by Unknwon** [comment]
ping @tuudik

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Comment by tuudik** [comment]
The first command gives me following response:
```
# Entry 1: cn=Gogs User,ou=Service Accounts,dc=roksnet,dc=com
dn: cn=AppUser,ou=Service Accounts,dc=domain,dc=com
cn: AppUser
sn: User
uid: appuser
```

The second command gives me 0 response. But this is also irrelevant command since the base should be actually: "cn=Admin User,ou=Admins,dc=domain,dc=com".

Then the response is also zero. But this is due to that gid is not assigned to user (for this Base).


If I could define Base DN for admin filter as: " cn=GogsAdmins,ou=Groups,dc=domain,dc=com", search filter "(objectClass=posixGroup)", attributes "memberuid", it would give list of this group members uid, that could be used for checking if user is admin or not.

Result of such query:
```
# Entry 1: cn=GogsAdmins,ou=Groups,dc=domain,dc=com
dn: cn=GogsAdmins,ou=Groups,dc=domain,dc=com
memberuid: AdminUser
```

**Comment by Unknwon** [comment]
cc @SergioBenitez

**Comment by SergioBenitez** [comment]
@tuudik It seems relatively clear that the schema you're using doesn't include a `gidNumber` field. Thus, nothing will match a query involving the `gidNumber` field. Does that make sense?

This doesn't appear to be a Gogs issue.

**Comment by tuudik** [comment]
@SergioBenitez 

Never wanted to say it's an issue, but perhaps LDAP auth can be improved for Gogs.

I have also Dokuwiki setup for same LDAP, for different users, different groups, where users have different permissions according to the groups they belong.

I guess dokuwiki logic for LDAP work as following (https://www.dokuwiki.org/plugin:authldap:openldap#with_anonymous_bind_and_filters):

1. Get list of groups from LDAP
2. Admin belongs in group WikiAdmins
3. On user login, following filter is checked: 
```
(&(objectClass=posixGroup)(|(memberUid=[ADMIN_USER_UID])(gidNumber=[ADMIN_GROUP_GID])))
```

Reponse to this filter is for example as following:
```cn=WikiAdmins
dn	cn=WikiAdmins,ou=Groups,dc=domain,dc=com
cn	WikiAdmins```

In my opinion, the current LDAP auth handling would allow dynamic admin groups.
There are only super admins, which are users, created for example under "ADMINS" group, no option to have different users with different admin accesses to different applications.

**Comment by Unknwon** [comment]
@tuudik sounds like you're getting off the primary purpose of this thread (according to the issue title)?

**Comment by tuudik** [comment]
@Unknwon Seems so, since I understand now better, how gogs handles LDAP authentication.

Shall I change the title, or just forget it and leave it as is?

**Comment by Unknwon** [comment]
@tuudik since this discussion is quite long, I suggest you close this one and file a new one about **dynamic admin gourp** thing.

**Comment by tuudik** [comment]
Feature/enhance request:
https://github.com/gogits/gogs/issues/2913
