### ISSUE TITLE
Outdated .gopmfile CSRF dependency

### ISSUE THREAD

**Issue by ypnos-web** [gogits/gogs#2848]
In b4f47a762338abe6ce3a6e3d6d0896b8a387228d you introduced dependency to a newer version of CSRF.

The commit for that version is go-macaron/csrf@6a9a7df172cc1fcd81e4585f44b09200b6087cc0
It needs to be updated here: https://github.com/gogits/gogs/blob/9bd9ad420582a7a34d18011847bb789f64271b1f/.gopmfile#L10

Right now the build with get_gopm leads to an unusable binary.

**Comment by Unknwon** [comment]
Thanks, should work now!
