### ISSUE TITLE
Concurrency issue when cloning using built-in SSH server

### ISSUE THREAD

**Issue by redoz** [gogits/gogs#2850]
- Gogs version (or commit ref):
Reproduced on: 0.8,0.9

- Git version:
git version 2.6.2.windows.1

- Operating system:
Windows Server 2012

- Database:
SQLite

- Can you reproduce the bug at http://try.gogs.io:
Haven't tried, not sure if try.gogs.io uses the built-in SSH server or not.

What happens is that I clone repository X but what actually gets cloned is repository Y. It appears that the requests are getting cross-connected somehow so you get the results from a different SSH request in progress.
However, the client doesn't report any odd errors at this time, it simply gets the wrong repository.

It also appears to affect other commands than "clone", but I've managed to reproduce is by running multiple workers that continuously clone a repository each, every so often they'll end up with a clone of a repository that's being requested by another worker.

I've only tested it with Private repositories that belong to a single organization.

I've discussed the issue quickly with @bkcsoft on Gitter

**Comment by Unknwon** [comment]
Please help test `develop` branch again.

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by redoz** [comment]
Yeah I can no longer reproduce this using the 0.9.13.0319 build.
