### ISSUE TITLE
Cannot run as service

### ISSUE THREAD

**Issue by tcpluess** [gogits/gogs#2853]
When I try to run Gogs as service with the script provided, I get the error:

"[...s/setting/setting.go:419 NewContext()] [E] Expect user(root) but current user is:"

I am using Centos 6.7. Unfortunately it seems impossible to autostart the Gogs service with this script.

**Comment by Unknwon** [comment]
Hi, you did not set `USER` env var in your script.

Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
