### ISSUE TITLE
Support HTTP HEAD requests

### ISSUE THREAD

**Issue by aclindsa** [gogits/gogs#2857]
- Gogs version (or commit ref): v0.9.0
- Git version: 0ea0c5ec4f24f0fc5ef3231085c74b33a16f98ec
- Operating system: Arch Linux
- Database: MySQL
- Can you reproduce the bug at http://try.gogs.io: Yes
## Description

Gogs does not support HEAD requests (https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4). While not typically used by common web browsers, it is commonly used by testing and monitoring software. From the link above: "This method is often used for testing hypertext links for validity, accessibility, and recent modification". One example of this is the 'monit' monitoring software, which recently moved to using HEAD requests instead of GET ones to reduce the traffic sent/received for simple service monitoring (see the Version 5.16 section at https://mmonit.com/monit/changes/).

The current behavior is that Gogs returns a 404 error code when it encounters a HEAD request. You can see this for yourself by doing `curl --head https://try.gogs.io`. Gogs should instead return the same headers it would for a GET request to the same URL (including the status code), but omit the response body.

**Comment by Unknwon** [comment]
If you want to do health check, do

```
curl https://try.gogs.io/healcheck
```

**Comment by aclindsa** [comment]
Supporting HEAD HTTP requests is the standard and widely-accepted way to check if you're able to connect to a service without returning all the data from a given URL. It is supported by every other web service I've tried it with (try my `curl --head` command with any other website to see for yourself, github.com for example), and a wide variety of tools therefore expect it to be supported. Since it is so widely used, I think it is important for Gogs to conform to this standard.

Also, I didn't know about /healthcheck, thanks!

**Comment by Unknwon** [comment]
It's not about how others do, but why they do that.

Since your purpose is health check and avoid load full content, `/healthcheck` is more than enough.

**Comment by aclindsa** [comment]
My point is not that /healthcheck doesn't serve a similar purpose as HEAD requests. It does [1]!

However, web standards exist for a reason. My point is that in order to work well with monitoring tools which frequently assume the service you're monitoring follows common web conventions, it would be helpful for Gogs to support HEAD requests.

[1] Though it is not quite as flexible - HEAD allows you to check whether any individual URL is working, while /healthcheck just allows you to check if Gogs thinks it's working properly. For example, if I wanted to monitor to ensure someone didn't delete a repository I cared about, I could do that with HEAD requests.

**Comment by Unknwon** [comment]
> The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response.

Gogs does not have any special care to not return the message body.

**Comment by aclindsa** [comment]
I don't think I understand. What do you mean when you say "does not have any special care"?

**Comment by Unknwon** [comment]
By definition, server should only return header right? But Gogs always return full content.

**Comment by aclindsa** [comment]
Yes, that's correct. In order to support HTTP HEAD, Gogs would have to omit the content for those requests.

**Comment by Unknwon** [comment]
That feels not worth for me.

**Comment by Jonny007-MKD** [comment]
Implementing this common web standard is one line of code:

https://go-macaron.com/docs/middlewares/routing
> In some cases, HEAD method is also used wherever GET method is registered. To reduce redundant code, there is a method called SetAutoHead can help you automatically register it:

    m := New()
    m.SetAutoHead(true)
    m.Get("/", func() string {
        return "GET"
    }) // HEAD method for path "/" is now registered as well.

It is true that there is no advantage for gogs to support the HEAD method (the amount of computation stays the same, the template still has to be rendered by Macaron), but many tools rely on our because it reduces the site of the transmitted data a lot.
Due to the easy implementation with Macaron I recommend to add it. If you want, I can make a PR.

**Comment by Unknwon** [comment]
Someone sent a PR before but I rejected.

I of course know that's just one line of change because I wrote Macaron.

**Comment by Jonny007-MKD** [comment]
Oh, I didn't know you're the author of Macaron :)

Then why don't you want to implement the HEAD method? It is audio used by caching servers to check the validity of their stored information.

**Comment by Unknwon** [comment]
What is worth having two identical methods return the same thing?

**Comment by Jonny007-MKD** [comment]
The PR was #2676 (for reference)

Well, GET returns the header and the body and HEAD only returns the body. So HEAD is a lightweight version of GET that is used to reduce the amount of bits bring transferred when someone is only interested in the headers (like caching proxies and monitor daemins)

**Comment by Jonny007-MKD** [comment]
After some thinking about the rejected PR:

I've got no overview about the responses which gogs gives in the various situations (404 if no access to private repositories and so on). As the HEAD method is processed completely identical to the GET method, no information is leaked nor any security issue is introduced, are they?

**Comment by Unknwon** [comment]
I know the definitions, but Gogs always returns everything, wich make HEAD useless.

**Comment by Jonny007-MKD** [comment]
gogs returns everything to Macaron, is this correct? This is necessary to calculate the correct size value in the header, so I see no problem.
But Macaron must not send everything to the client, which makes HEAD useful.

**Comment by Unknwon** [comment]
> But Macaron must not send everything to the client, which makes HEAD useful.

Now we are talking, I suggest file an issue on Macaron for this, and reference that issue on this thread.

**Comment by nathan-osman** [comment]
Could we at least get `HEAD` support for `/healthcheck`? I can't monitor Gogs with Monit as it stands now.

**Comment by dakira** [comment]
@Unknwon Not adhering to this standard prevents most uptime monitors from being able to check Gogs (as they only send HEAD requests).

**Comment by Unknwon** [comment]
As a quick fix, you can now do:

```sh
13:42:24 $ curl -I https://try.gogs.io/healthcheck
HTTP/1.1 200 OK
Content-Length: 26
Content-Type: text/plain; charset=utf-8
Date: Mon, 20 Feb 2017 18:42:35 GMT
Server: Caddy
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gogits=89c5c14cf2a8eca4; Path=/; HttpOnly
Set-Cookie: _csrf=MrVtiliXHzBjJGFW0Kiy5bH-Byo6MTQ4NzYxNjE1NTMzNTQwMzU2OQ%3D%3D; Path=/; Expires=Tue, 21 Feb 2017 18:42:35 GMT; HttpOnly
```

**Comment by dakira** [comment]
Nice! That helps a lot. Thanks!

**Comment by sausages** [comment]
I also think supporting HEAD requests would be a good idea. While /healthcheck does indeed fulfil the same function, I've just spend a couple of hours trying to work out why Monit doesn't think that my Gogs server is up. Supporting this standard would save others the same trouble.

**Comment by gyppo** [comment]
I also think supporting HEAD requests would be a good idea. While /healthcheck does indeed fulfil the same function, I've just spend a couple of hours trying to work out why Monit doesn't think that my Gogs server is up. Supporting this standard would save others the same trouble.

**Comment by cpoulsen-dezide** [comment]
We've just been bitten by this at work. We apply some remote gradle scripts using <gogs>/raw/file.gradle (shared config across builds)

In gradle 4.2 they attempt to check whether the url exist (and possible some headers) before deciding whether they can use the cached version or have to retrieve the remote version.

The gradle cache checking totally breaks down as the HEAD request returns a error, while the GET works. I'm inclined to think that their way of performing lightweight remote checking is correct and it is sub-optimal that gogs always fail on HEAD requests.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

```sh
✗ curl -I https://try.gogs.io
HTTP/2 200
content-type: text/html; charset=UTF-8
date: Tue, 06 Mar 2018 06:28:36 GMT
server: Caddy
set-cookie: lang=en-US; Path=/; Max-Age=2147483647
set-cookie: i_like_gogits=4b8d864f50be4f96; Path=/; HttpOnly
set-cookie: _csrf=MAZnBlmI6H94wZ-Xo97RxUM7-Gk6MTUyMDMxNzcxNjEzMjg1MTYxOA%3D%3D; Path=/; Expires=Wed, 07 Mar 2018 06:28:36 GMT; HttpOnly
```
