### ISSUE TITLE
gogs V.9.0 windows service fails to run

### ISSUE THREAD

**Issue by smasherprog** [gogits/gogs#2858]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): .9.0
- Git version:
- Operating system: Windows 7
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ X ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ X] No
  - [ ] Not relevant
- Log gist:

When starting go git as a service on windows 7, it fails with 
![capture](https://cloud.githubusercontent.com/assets/3393733/13891539/ef9f24fa-ed0e-11e5-91ae-5fe1e1334c10.PNG)
I was running the previous version without issue .8.43. It seems to be something in the binary itself. I tried an inplace replacement of the exe and i received the error.
I then tried a new setup and received the same error message. 

Windows event viewer has no information other than "The gogs service terminated unexpectedly." This happens to all versions of the windows release, 32 bit and 64 bit

...

**Comment by Eeems** [comment]
Make sure the user the service is running as has permission on the folders used (logs etc).

Also make sure the binPath is 'C:\path\to\gogs.exe web --config C:\path\to\app.ini' or something similar.

**Comment by Unknwon** [comment]
Hi, please always check Gogs log, nothing else help debug.

Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
