### ISSUE TITLE
Feature request: Tags order

### ISSUE THREAD

**Issue by rnarian** [gogits/gogs#2859]
I think it would make more sense to reverse the order of the tags so that newer versions are always on top.

**Gogs:**
![image](https://cloud.githubusercontent.com/assets/1174951/13901637/9b974d5c-ee2a-11e5-9335-fbc0856128a6.png)

**Github** (for example):
![image](https://cloud.githubusercontent.com/assets/1174951/13901629/85b51654-ee2a-11e5-9836-63a50bc6a342.png)

**Comment by Unknwon** [comment]
This is claimed to be fixed be merging https://github.com/gogits/git-module/pull/8, you can test on demo site.

**Comment by rnarian** [comment]
Awesome! Works as expected. :sunglasses: :ok_hand:
