### ISSUE TITLE
Log level not working as expected

### ISSUE THREAD

**Issue by Jonny007-MKD** [gogits/gogs#2860]
- Gogs version: 0.9.13.0318
- Git version: 2.1.4
- Operating system: Debian 8
- Database: 
  - [x] MySQL
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Not relevant
- Log gist:

## Description

The log level is not doing what I exepect it to do. I tried setting it to `Trace` and to `Warn` but I experience not difference in the output of gogs on the console (aside from the Log Mode statement).

Differences are bold:

### Level = Trace
> [T] Custom path: /home/git/custom
> [T] Log path: /home/git/log
> [I] Gogs 0.9.13.0318
> [I] Build Time: 2016-03-20 11:12:41 UTC
> [I] Build Git Hash: 3fb4f7f4980b4339fd9ef6a3ba5b0acab83d264d
> [I] Log Mode: Console(**Trace**)
> [I] Cache Service Enabled
> [I] Session Service Enabled
> [I] Mail Service Enabled
> [I] Notify Mail Service Enabled
> [I] Git Version: 2.1.4
> [T] Doing: CheckRepoStats
> [I] Run Mode: Production
> [I] Listen: http://127.0.0.1:17017

### Level = Warn
> [T] Custom path: /home/git/custom
> [T] Log path: /home/git/log
> [I] Gogs 0.9.13.0318
> [I] Build Time: 2016-03-20 11:12:41 UTC
> [I] Build Git Hash: 3fb4f7f4980b4339fd9ef6a3ba5b0acab83d264d
> [I] Log Mode: Console(**Warn**)
> [I] Cache Service Enabled
> [I] Session Service Enabled
> [I] Mail Service Enabled
> [I] Notify Mail Service Enabled
> [I] Git Version: 2.1.4
> [T] Doing: CheckRepoStats
> [I] Run Mode: Production
> [I] Listen: http://127.0.0.1:17017

Also, later on statements like `[D] Session ID: 1dc8d7a421ee7d01` are printed with both configurations.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2798
