### ISSUE TITLE
Private forks should not be deletable by upstream

### ISSUE THREAD

**Issue by hasufell** [gogits/gogs#2863]
1. someone writes a latex skeleton (macros and stuff) for a thesis and pushes it to a private repository
2. someone forks it
3. both write their thesis, with completely different content
4. the guy who wrote the initial skeleton is finished first and deletes his repository
5. the guy who forked the skeleton now has a problem, unless his local backup is still intact

And this is just one example how this can go wrong. I don't even understand the reasoning behind it and what it is supposed to accomplish.
If you give untrusted users access to your private repository at any time and then want to remove all traces of your code... you are screwed anyway. And gogs cannot help you with that. Neither can it help with licensing situations.

To me this looks like a backdoor to delete other peoples repositories. It should not be possible. And it's highly unintuitive behavior.

**Comment by Unknwon** [comment]
The purpose of fork is to send requests back to upstream, if upstream decide not exist anymore, why should forks do?

**Comment by hasufell** [comment]
> The purpose of fork is to send requests back to upstream

I think that's an assumption that cannot be verified. That's just one way people use that feature.

**Comment by phtan** [comment]
I want to work on this issue. Nobody has claimed this yet, s'far as I can see.

**Comment by Unknwon** [comment]
@phtan Go ahead :smiley:

**Comment by phtan** [comment]
@Unknwon will you close this issue? #3231 - to be closed, too?
