### ISSUE TITLE
Add the feature to obtain raw patch of a commit in Gogs

### ISSUE THREAD

**Issue by ronisbr** [gogits/gogs#2864]
Hi guys!

In GitHub, if you add `.patch` after the link of a commit, then you get the raw patch that can be used with `patch` tool. This is a very nice feature that I use a lot. Is it possible to add such option to Gogs?

For example, see these links:

https://github.com/gogits/gogs/commit/004fb30ebe403625b2315b284a85124611ba303b.patch
https://github.com/gogits/gogs/commit/004fb30ebe403625b2315b284a85124611ba303b

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2641
