### ISSUE TITLE
No issues showing up on Issues tab

### ISSUE THREAD

**Issue by johnnylee** [gogits/gogs#2865]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database:
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

I don't see any issues in the `Issues` tab, even though I have an assigned issue, and an issue in one of my repositories, and I have created issues. 

Looking at the log files, the problem appears to be due to the query here:

```sql
[xorm] [info]  2016/03/21 08:58:48.617567 [sql] SELECT COUNT(*) FROM "issue"  WHERE issue.is_closed=$1 AND issue.repo_id=0 AND issue.is_pull=0 AND assignee_id=$2 [args] [false 1]
```

Specifically `issue.repo_id=0` doesn't make sense.

**Comment by TilmannBach** [comment]
I think its another duplicate to #1820 ?

**Comment by johnnylee** [comment]
It looks like it.
