### ISSUE TITLE
Correct changelog

### ISSUE THREAD

**Issue by OhDaeto** [gogits/gogs#2868]
Mistake in release description

"Site admin cannot see private repositories on organization home page" probably points to wrong issue. Maybe to this https://github.com/gogits/gogs/pull/2785

**Comment by Unknwon** [comment]
You can make a PR for this...

**Comment by Eeems** [comment]
@Unknwon I was not aware that PR's allowed you to change release information.

**Comment by Unknwon** [comment]
Fixed.
