### ISSUE TITLE
CSS: Use monospace font in wiki editor

### ISSUE THREAD

**Issue by nd2s** [gogits/gogs#2869]
Code snippets, tables and similar are very hard to write without fixed-width font.

**Comment by Unknwon** [comment]
Can you give examples with screenshots?

**Comment by dakira** [comment]
I think this is a good idea (and extremely easy to implement). Here's an example here on Github:

![current](https://cloud.githubusercontent.com/assets/576555/13951375/d6d9ab96-f030-11e5-9d0f-bb6649166af6.png)

vs.

![monospaced](https://cloud.githubusercontent.com/assets/576555/13951385/eb119e0c-f030-11e5-8c54-f1e9f37455c4.png)

**Comment by Unknwon** [comment]
I think this only works for ASCII characters? Not very helpful for people who use other languages a lot.

**Comment by dakira** [comment]
Just copy and pasting from discuss here:

![bildschirmfoto vom 2016-03-22 20-23-30](https://cloud.githubusercontent.com/assets/576555/13964834/016a67d4-f06c-11e5-8db6-33bc981d52f8.png)

I just changed the style of the textfield to `font-family: monospace`, I don't see why that wouldn't work. Nothing else happens when you display code. You wouldn't be able to use Chinese (or Greek or Cyrilic) characters in code otherwise.

```
monospaced
decapsonom
注册邮箱限定
```

**Comment by Unknwon** [comment]
Good prove! But the `monospace` font feels not nature to me.

**Comment by moltam** [comment]
@Unknwon I thought this first too, but Github uses monospaced font in the wiki editor. Even wikipedia uses monospaced font in their editor.
So this convinced me, that there is nothing wrong with this idea :)

**Comment by nd2s** [comment]
markdown is "code" that's why it needs monospace.

**Comment by dakira** [comment]
@Unknwon It's only in the editor. Not in the display. Non code content shouldn't be displayed in monospace. But it should be edited in monospace if you ask me (for the reasons already mentioned by others). The same holds true for the issue editor, btw.

**Comment by Unknwon** [comment]
OK, @dakira mind send a PR?

**Comment by dakira** [comment]
@Unknwon Sure, would this be the right file for the changes? https://github.com/gogits/gogs/blob/master/public/less/_form.less

**Comment by Unknwon** [comment]
@dakira `make less`.

**Comment by andreynering** [comment]
Because of Windows, sites usually do:

```css
textarea {
    font-family: "Consolas", monospace;
}
```

Because Consolas looks better than Courier New.

**Comment by dakira** [comment]
True, I saw that on many sites. Will include that in my pull request.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2879, you can test on demo site.

**Comment by moltam** [comment]
Looks good!
