### ISSUE TITLE
require new user permission level: can only access issues but not code

### ISSUE THREAD

**Issue by localvar** [gogits/gogs#2870]
my project has some external users, I wish they could submit/modify issues, but I don't want them to clone/view the code. so I'd like to require a new permission level. or is it already exist? thanks.

seems already required by many people. #649

**Comment by Download-Fritz** [comment]
You linked the previous issue, which means you saw it. So, why create a second issue for the same thing?

**Comment by localvar** [comment]
at first, I use some keywords to search existing issues, but didn't find any related one. so I create this issue, but after that I find 649 by other keywords, then I revised the issue.
