### ISSUE TITLE
internal server error after wiki page added

### ISSUE THREAD

**Issue by imwower** [gogits/gogs#2871]
添加wiki页面并提交之后，服务器显示500错误；现在不能添加wiki页面了。版本号见下面截图。
流程：
1. 点击导航上的”WIKI“，添加一个页面，进入编辑器，输入一些内容，并提交，
![1](https://cloud.githubusercontent.com/assets/1744486/13941714/5166e7f4-f025-11e5-8e81-1bb1e8e7d2f3.jpg)
2. 点击”保存页面“之后，出现500错误，
![unnamed qq screenshot20160322113422](https://cloud.githubusercontent.com/assets/1744486/13943298/14698620-f036-11e5-9e76-ab097eb0df84.png)
3. 以下是控制台输出的错误信息：
![3](https://cloud.githubusercontent.com/assets/1744486/13943313/40133726-f036-11e5-83d5-65ede7dc31de.png)
4. 服务器上这个目录不存在：
![4](https://cloud.githubusercontent.com/assets/1744486/13943334/7682a364-f036-11e5-87dd-d1bf63e30fe0.png)

**Comment by Unknwon** [comment]
Hi, please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by imwower** [comment]
已将此求助提交至：[https://discuss.gogs.io/t/wiki-500/157](https://discuss.gogs.io/t/wiki-500/157)
请关闭此issue，谢谢！
