### ISSUE TITLE
Error 500 on creating PULL Request

### ISSUE THREAD

**Issue by Gabbalo** [gogits/gogs#2872]
For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.0
- Git version: 2.7.3.windows.1
- Operating system: Windows Server 2012 R2 SE
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [x] No
  - [ ] Not relevant
- Log gist:

```
[Macaron] Started POST /USERNAME/psGIZMO/compare/master...BRANCHNAME_dev for 10.122.5.113
2016/03/22 08:01:58 [D] Session ID: e05b31345570fc81
2016/03/22 08:01:58 [D] CSRF Token: ZPK2pTneP#####################1ODYyOTgwMzI5ODI0NDgwMA==
2016/03/22 08:01:58 [T] PullRequest[0].testPatch (patchPath): C:\gogs-repositories\USERNAME\psgizmo.git\pulls\7.patch
2016/03/22 08:01:58 [...routers/repo/pull.go:680 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocal
Copy: Pull: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

2016/03/22 08:01:58 [D] Template: status/500
[Macaron] Completed /USERNAME/psGIZMO/compare/master...BRANCHNAME_dev 500 Internal Server Error in 437.5039ms
```

## Description

Hi,

upon creating a new PULL Request on the Website, I only get a http errocode 500. Everything else seems to work.
PULL requests worked last week, since than, the webserver was shut down forcefully once (by logging of the user under which the server runs -.-)

[Edit] Updated the version-details

**Comment by Unknwon** [comment]
Hi, please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Gabbalo** [comment]
Um ... 

_We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist._

??

I don't know, what else is missing from the template, sry. Could you help me out with an a little bit more detailed request? Maybe its because english is not my native language :/

**Comment by Unknwon** [comment]
>Gogs version (or commit ref):
Git version:
Operating system:

**Comment by Gabbalo** [comment]
:facepalm:
I am really sorry for overseeing that ones -.-

Here you go.

Gogs version (or commit ref): 0.9.0
Git version: 2.7.3.windows.1
Operating system: Windows Server 2012 R2 SE

**Comment by Unknwon** [comment]
Does restart fix the problem?

**Comment by Unknwon** [comment]
Since you're using 0.9, this should be a fixed issue: https://github.com/gogits/gogs/issues/1738

**Comment by Gabbalo** [comment]
Restart: Won't fix it (tried just now)
Correction: Error 500 shows up upon *submitting* the PULL request, not on *creating* it. Updated screenshot attached.

![gogs](https://cloud.githubusercontent.com/assets/5897819/13977592/cc886bec-f0ca-11e5-8149-caa9e96676dd.PNG)

The repository was neither deleted nor is it actually gone. I checked both, database and explorer, for presence. The entry and files are where they should be. That seemed to be the problem in the mentioned issue, wasn't it?

repo.git-folder is read-only, files within are not.

In the mentioned issie, there is [another issue](https://github.com/gogits/gogs/issues/2490) linked, which seems to be just the same problem. At least, if I ignore the fact, that in those cases, a repository was deleted and in my case it should not be. And beside the used version, of course.
I followed up the instructions in there. 
The only folder in C:\gogs\data\tmp\local\ is "1", which is empty. There are at least two repositories in GoGS which both are accessable from page and git-client, if this information is relevant to this.

Can I provide additional informations which would help to track the issue down? =)

**Comment by Unknwon** [comment]
Delete `tmp\local` should fix your problem.

Check your **Admin -> System Notices** page, there should be a lot of records by now.

**Comment by Gabbalo** [comment]
Actually, there is not a single record in the System Notice section. 
If there should be, I think they are not stored properly in my installation.

Nevertheless: Deleting the tmp-folder *was* the solution. I shut down the server, deleted the folder, started it up again --> PULL request created.

Thank you for your exeptional fast and helpfull (and patient :D ) support on this topic.

**Comment by Unknwon** [comment]
OK, I might know the problem. Basically this is same to https://github.com/gogits/gogs/issues/1738.

But that only fixed the new ones (rename repo, rename user) after the fix. I'll push a quick fix to old ones.

**Comment by Unknwon** [comment]
Pushed.

**Comment by phonicmouse** [comment]
Same issue on linux, deleting `tmp/local` works fine.
