### ISSUE TITLE
Dashboard feeds has unexpected line break on Mac OS X Safari

### ISSUE THREAD

**Issue by cipherboy** [gogits/gogs#2875]
- Gogs version (or commit ref): https://try.gogs.io
- Operating system: Mac OS X - 10.11.3 (15D21) 
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes   -- u: testing-abcde (pictured)
## Description

Safari has a fairly long standing display bug on the dashboard page. The _div.left_ in _div.news_ appears directly above the _div.grid_ elements for all the feed items. It appears that, using the same (maximized) viewport with, Safari gives the _div.grid_ element 40px greater width than Chrome does, forcing it below the _div.left_ element. Attached are screenshots comparing the differences. 

Safari - v9.0.3 (11601.4.4)

![screen shot 2016-03-22 at 13 22 40](https://cloud.githubusercontent.com/assets/914030/13963291/d1e75852-f032-11e5-8827-a128a15ced69.png)

![screen shot 2016-03-22 at 13 24 49](https://cloud.githubusercontent.com/assets/914030/13963298/d820fd2c-f032-11e5-8434-cdb6b80c044f.png)

Chrome - v49.0.2581.0:

![screen shot 2016-03-22 at 13 23 04](https://cloud.githubusercontent.com/assets/914030/13963303/dd6c556a-f032-11e5-9c5e-6ede692763f8.png)

![screen shot 2016-03-22 at 13 25 23](https://cloud.githubusercontent.com/assets/914030/13963306/e133a48c-f032-11e5-9a92-f365f0103fbb.png)

Thanks for all of your hard work on Gogs!

-- Alex

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3569, please help test on `develop` branch or https://try.gogs.io.

**Comment by Mab879** [comment]
Tested on Safari Version 9.1.3 (11601.7.8). Looks good.
<img width="1680" alt="screen shot 2016-09-02 at 11 40 51 am" src="https://cloud.githubusercontent.com/assets/207087/18211214/2f9f0594-7102-11e6-9bb3-50f7b0964e6d.png">
