### ISSUE TITLE
git clone error in docker env

### ISSUE THREAD

**Issue by uname-yang** [gogits/gogs#2877]
- Gogs version (or commit ref): 0.9.13.0319
- Git version:2.6.4
- Operating system:docker in windows
- Database:
   SQLite
- Can you reproduce the bug at http://try.gogs.io:
   No
- Log gist:

## Description
i install gogs in  kitematic .everything in web is ok .but i can't clone the repo which i create on website.
it report a permission error as below.
![capture](https://cloud.githubusercontent.com/assets/8829072/13977506/7732a18c-f104-11e5-8562-465aa65de166.PNG)

...

**Comment by Unknwon** [comment]
Why it looks like your do not have permission on the client site?

**Comment by uname-yang** [comment]
Sorry ,maybe is windows git client error.
Fuck Windows

**Comment by Unknwon** [comment]
..........
