### ISSUE TITLE
Cannot click through to Releases page

### ISSUE THREAD

**Issue by smcquay** [gogits/gogs#2880]
- Gogs version (or commit ref): d3db1b25913e06
- Git version: git version 2.5.0
- Operating system: Ubuntu 15.10, up to date
- Database:
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ X] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
[...ters/repo/release.go:97 Releases()] [E] GetTagCommit: exit status 128 - fatal: 'refs/tags/' - not a valid ref

## Description

I have no releases on any of my repos, yet it claims I have one and it 500s when I click through to see what's happening.

**Comment by Unknwon** [comment]
Hi, what is the example URL on demo site?

**Comment by smcquay** [comment]
to repro on try.gogs.io I just clicked through to the first project:

https://try.gogs.io/danil/dotfiles/releases

Sorry for not including the url initially.

Does that help?

**Comment by Unknwon** [comment]
Yes, thanks.

**Comment by Unknwon** [comment]
This should be fixed.

You need do `go get -u github.com/gogits/git-module` and recompile Gogs.

**Comment by smcquay** [comment]
Works for me. Thanks!!
