### ISSUE TITLE
ask user to confirm when he/she leaves wiki edit page if the page not saved

### ISSUE THREAD

**Issue by localvar** [gogits/gogs#2881]
I'm editing a wiki page but didn't save it, and hit the backspace outside the edit box by an accident, then I lost all my work.

suggest to save wiki to a local storage like cookie periodic during edit. and ask user to recover when he/she comes back

another way for this issue may be: ask user to confirm when he/she leaves the edit page. this maybe easier to implement.

**Comment by Unknwon** [comment]
Hi,

> another way for this issue may be: ask user to confirm when he/she leaves the edit page. this maybe easier to implement.

I suggest your change title of issue to this one. Because save to cookie will not be implemented.

**Comment by localvar** [comment]
title updated. in short, what I'm asking for is a way to recover unsaved work, because there are so many cases that user leave the edit page without save it.

**Comment by Unknwon** [comment]
Thanks.

But I think save automatically edit page is somewhat over complicated. But save new page to local storage is acceptable. 

Also, current title is not what I suggested, what I suggested is:

> ask user to confirm when he/she leaves the edit page. this maybe easier to implement.

**Comment by localvar** [comment]
title updated

**Comment by bkcsoft** [comment]
What about this? http://plugins.jquery.com/are-you-sure/

**Comment by Unknwon** [comment]
@bkcsoft:

> What about this? http://plugins.jquery.com/are-you-sure/

Looks simple and does the job :smiley:

**Comment by bkcsoft** [comment]
@Unknwon I need to update the SimpleMDE-dependency for this to work, see release-notes under "New" (forceSync) https://github.com/NextStepWebs/simplemde-markdown-editor/releases/tag/1.10.1
Acceptable ?

Without the update areYouSure can't know if the wiki-text has been changed...

**Comment by bkcsoft** [comment]
The other option is to enable AutoSave (LocalStorage... :unamused:) in SimpleMDE. Though AutoSave can't (easily) separate different pages, meaning it will break if you dont' save and then go to edit another page (it will actually overwrite the new page you open...)

Anyhow, upgrading SimpleMDE seems best, so it uses areYouSure correctly :smile:

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #2980, please help test on `develop` branch or https://try.gogs.io.

**Comment by localvar** [comment]
yes, this is fixed.
