### ISSUE TITLE
Add config option to set a cookie value indicates login status

### ISSUE THREAD

**Issue by barracks510** [gogits/gogs#2885]
## Description

Currently, there is no trivial way to detect whether a request contains a logged-in user or not. This feature makes caching public pages possible. The status right now is that every unique session gets it's own session cookie that is updated as a user does various tasks. My suggestion is that a secure cookie is set for a cache proxy to differentiate public sessions and private ones. This way, the cache proxy can use something like this:

``` nginx
location / {
    ...
    proxy_cache_bypass $cookie_user;
    ...
}
```

Where a cookie `user` is `true` when the session is logged in and `user` is `false` when the session is not logged in.

**Comment by Unknwon** [comment]
Hi,

> This feature makes caching public pages possible. 

What `feature`?

> My suggestion is that a secure cookie is set for a cache proxy to differentiate public sessions and private ones.

I don't get this part, Gogs is behind proxy, how can it manuplate it?

**Comment by barracks510** [comment]
Does this patch explain what I am trying to do?
```diff
From e0a77b6e1390ba0ba9f293dadec9d5c3077cfe37 Mon Sep 17 00:00:00 2001
From: Dennis Chen <barracks510@gmail.com>
Date: Thu, 24 Mar 2016 18:05:28 -0700
Subject: [PATCH] Add Caching Proxy Cookie

---
 modules/setting/setting.go |  8 ++++++++
 routers/user/auth.go       | 13 +++++++++++++
 2 files changed, 21 insertions(+)

diff --git a/modules/setting/setting.go b/modules/setting/setting.go
index 92eb04d..77bb35a 100644
--- a/modules/setting/setting.go
+++ b/modules/setting/setting.go
@@ -202,6 +202,8 @@ var (
 	ShowFooterBranding    bool
 	ShowFooterVersion     bool
 	SupportMiniWinService bool
+	StatusCookie          bool
+	CookieLoginStatus     string
 
 	// Global setting objects
 	Cfg          *ini.File
@@ -473,8 +475,14 @@ func NewContext() {
 	Names = Cfg.Section("i18n").Key("NAMES").Strings(",")
 	dateLangs = Cfg.Section("i18n.datelang").KeysHash()
 
+	// Other Settings
 	ShowFooterBranding = Cfg.Section("other").Key("SHOW_FOOTER_BRANDING").MustBool()
 	ShowFooterVersion = Cfg.Section("other").Key("SHOW_FOOTER_VERSION").MustBool()
+	StatusCookie = Cfg.Section("other").Key("PROVIDE_STATUS_COOKIE").MustBool()
+	var CookieLoginStatus string
+	if StatusCookie {
+		CookieLoginStatus = Cfg.Section("other").key("COOKIE_LOGIN_STATUS").MustString("user")
+	}
 
 	HasRobotsTxt = com.IsFile(path.Join(CustomPath, "robots.txt"))
 }
diff --git a/routers/user/auth.go b/routers/user/auth.go
index 9b48357..91ea718 100644
--- a/routers/user/auth.go
+++ b/routers/user/auth.go
@@ -44,6 +44,9 @@ func AutoSignIn(ctx *context.Context) (bool, error) {
 			log.Trace("auto-login cookie cleared: %s", uname)
 			ctx.SetCookie(setting.CookieUserName, "", -1, setting.AppSubUrl)
 			ctx.SetCookie(setting.CookieRememberName, "", -1, setting.AppSubUrl)
+			if setting.StatusCookie {
+				ctx.SetCookie(setting.CookieLoginStatus, "", 0, setting.AppUrl)
+			}
 		}
 	}()
 
@@ -64,6 +67,10 @@ func AutoSignIn(ctx *context.Context) (bool, error) {
 	ctx.Session.Set("uid", u.Id)
 	ctx.Session.Set("uname", u.Name)
 	ctx.SetCookie(setting.CSRFCookieName, "", -1, setting.AppSubUrl)
+	if setting.StatusCookie {
+		ctx.SetCookie(setting.CookieLoginStatus, "true", -1, setting.AppUrl)
+	}
+
 	return true, nil
 }
 
@@ -118,6 +125,9 @@ func SignInPost(ctx *context.Context, form auth.SignInForm) {
 	ctx.Session.Set("uid", u.Id)
 	ctx.Session.Set("uname", u.Name)
 
+	if setting.StatusCookie {
+		ctx.SetCookie(setting.CookieLoginStatus, "true", -1, setting.AppUrl)
+	}
 	// Clear whatever CSRF has right now, force to generate a new one
 	ctx.SetCookie(setting.CSRFCookieName, "", -1, setting.AppSubUrl)
 
@@ -139,6 +149,9 @@ func SignOut(ctx *context.Context) {
 	ctx.SetCookie(setting.CookieUserName, "", -1, setting.AppSubUrl)
 	ctx.SetCookie(setting.CookieRememberName, "", -1, setting.AppSubUrl)
 	ctx.SetCookie(setting.CSRFCookieName, "", -1, setting.AppSubUrl)
+	if setting.StatusCookie {
+		ctx.SetCookie(setting.CookieLoginStatus, "", 0, setting.AppUrl)
+	}
 	ctx.Redirect(setting.AppSubUrl + "/")
 }
 
-- 
2.5.5
```

**Comment by Unknwon** [comment]
Kind of. So why do you need this?

**Comment by barracks510** [comment]
Because this way, a webcache can separate the cachable items (for example, an unlogged in index.html)  from a sessioned item (for example, a logged in index.html) via use of cookie. So this way, putting items in a webcache is safe, because it can determine what is user-specific and what is not.

**Comment by Unknwon** [comment]
>  because it can determine what is user-specific and what is not.

I don't think it can even with this **special** cookie, many pages allows non-log in users to view as well.

**Comment by barracks510** [comment]
I just tested this on my local machine and I realize why you might not understand. Sorry for this confusion, let me try to reexplain this. 

A web cache (like Nginx for example), works by saving every request it receives. In practice, this works very well, until the first user logs in. Then, every other user ends up using the cached pages from the first user. The way around this is to "punch a hole in the cache". The goal of the cookie is to give the web cache a way of distinguishing whether the request deserves the cached version, or the request should hit the Gogs server. The logic is that all logged in users can bypass the cache, and all public users can use the cached version, the cookie is just one of the ways of distinguishing the two. 

See this link: https://www.nginx.com/blog/nginx-caching-guide/

**Comment by Unknwon** [comment]
Thanks, I get it now.

**Comment by Thomasdezeeuw** [comment]
@Unknwon does the label `dont send pull request` mean you will implement this, or does it mean you won't accept the change?

Because I could really use this feature as well.

**Comment by Unknwon** [comment]
@Thomasdezeeuw means I'll do it.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch, see details https://github.com/gogits/gogs/commit/becaec19a773301546045294d850d79614809c7c.
