### ISSUE TITLE
Raw Code View UTF8 Problem

### ISSUE THREAD

**Issue by Kambaa** [gogits/gogs#2888]
## Description
My code is filled with turkish comments and when i tried to view the code via clicking the 'raw' button, characters are garbled. No problem on default viewing though. Thank you...
![adsiz](https://cloud.githubusercontent.com/assets/5601326/14062544/d16a0b64-f3ab-11e5-8fdb-dd5bb3ace4b3.png)

**Comment by Unknwon** [comment]
Thanks your feedback!

Can you make up an example on GitHub so I can see how GitHub treats this situation?

**Comment by Kambaa** [comment]
Hello, you can see the github repo file at this address:
https://github.com/Kambaa/gogs-raw-code-test
![adsiz2](https://cloud.githubusercontent.com/assets/5601326/14066370/8107b284-f450-11e5-9e7f-ff6abec54908.png)

My server has the same exact file and it prints raw data like this:
![adsiz](https://cloud.githubusercontent.com/assets/5601326/14066367/60fb1f30-f450-11e5-8dd7-6ca579b56153.png)

**Comment by Unknwon** [comment]
Got it, thanks.

**Comment by Unknwon** [comment]
Hmm? I made a test repo on https://try.gogs.io/unknwon/issue-2888/raw/master/test-code-with-turkish-comments.php, and if I visit, I can see utf-8 characters correctly. Latest chrome...

**Comment by moltam** [comment]
@Unknwon For me this file is displayed with incorrect characters. I tested with Latest Firefox, and Chromium (on Ubuntu).

**Comment by Unknwon** [comment]
Maybe latest Chrome is a bit smarter :sweat_smile:

**Comment by moltam** [comment]
I'll try to fix this, but not today :)

**Comment by jekriske** [comment]
Latest chrome

<img width="388" alt="screen shot 2016-04-20 at 3 08 54 pm" src="https://cloud.githubusercontent.com/assets/3432769/14687117/d9deaaa4-0709-11e6-9ee5-27c774b66464.png">
<img width="459" alt="screen shot 2016-04-20 at 3 08 44 pm" src="https://cloud.githubusercontent.com/assets/3432769/14687116/d9da8366-0709-11e6-9b3e-69253af5a2eb.png">

**Comment by moltam** [comment]
The fix is now available on https://try.gogs.io

My example file: https://try.gogs.io/moltam/utf8-test/raw/master/README.md

I think we can close this issue now.

**Comment by jekriske** [comment]
Nice! looks good.

**Comment by Unknwon** [comment]
ping @Kambaa
