### ISSUE TITLE
Mirroring *to* a GitHub repository

### ISSUE THREAD

**Issue by joepie91** [gogits/gogs#2896]
On my old Gitolite setup, I had post-receive hooks set up in such a way that every push would also be automatically mirrored (`git push --mirror`) to an equivalent repository on GitHub (where the actual issue management and such lives).

While it's possible to specify this kind of hook manually in each repository's settings, it'd be nicer to have a "mirror to remote Git repository" button to set it up more or less automatically. Would this be a possibility?

**Comment by Unknwon** [comment]
Thanks your feedback!

I think this is duplicated to https://github.com/gogits/gogs/issues/96?

**Comment by joepie91** [comment]
Ah yes, you are correct, that indeed seems like the same request. I searched for a while but I couldn't find a previous issue for this - probably because it was titled 'sync' rather than 'mirror' :)

**Comment by Unknwon** [comment]
> EDIT: The 'have to confirm host key' point is a good one, I hadn't thought about that. Maybe there is an SSH flag to automatically trust on first contact?

I don't know about that and looking for a solution, you can post any possible solution to that thread.
