### ISSUE TITLE
Encourage usage of certain licenses

### ISSUE THREAD

**Issue by gtirloni** [gogits/gogs#2901]
- Gogs version (or commit ref): 0.9.18.0327
- Git version: N/A
- Operating system: N/A
- Database: N/A
- Can you reproduce the bug at http://try.gogs.io: Yes
- Log gist: N/A

## Description

It would help users if Gogs would provide a set of 3-4 licenses at the top of the license drop-down when creating a new repository, just like GitHub does with Apache, GNU and MIT licenses. It would help preventing license fragmentation when few users have the legal background to choose among dozens of licenses (and their different versions).

**Comment by bkcsoft** [comment]
Do you want the ability to set the "defaults" in app.ini?

**Comment by gtirloni** [comment]
@bkcsoft the ability to specify, in `app.ini`, the license file names that should be at the top would be nice. another possibility is to define some convention around how the file names are organized in the `conf/license` dir (e.g. add a prefix or suffix to identify the top ones).

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
