### ISSUE TITLE
Reserved-words list for repository is very broad

### ISSUE THREAD

**Issue by crrobinson14** [gogits/gogs#2903]
When creating new repositories in Gogs, a broad list of words is forbidden as repository names, such as `api`, `admin`, etc. Every other major Git service has no problem with names like this, so it's frustrating to migrate because it's common (at least for the projects I oversee) to have these be their original names. As a feature request, it would be VERY nice if Gogs could block only poorly-formatted repo names (`*.git`, 0-length names, etc.)

Just my opinion, but if naming a repo `issues` is actually going to disrupt the formatting of an API call, that seems error-prone to me. You'll have to continually maintain this blockword-list over time, and may have trouble in the future if you want/need to add a term that existing users have already used in repository naming...

**Comment by Joshua-Anderson** [comment]
@crrobinson14 Gogs tries to give the shortest URL possible for repositories by not prefixing them with anything. While this is helpful and saves typing, it also gets in the way of some logical and useful urls used by the service. In the `issues` case, the https://gogs.url/issues is a list of issues that the logged in user has created. This is the same behavior as https://github.com/issues. One would also expect other urls, such as https://gogs.url/login to be the login page, not an user called login.

It is a little confusing, but I think this is preferable to prefixing every repository URL with something to prevent namespace conflicting (such as https://gogs.io/u/user/repo).

**Comment by crrobinson14** [comment]
@Joshua-Anderson I hear you... But it seems misguided, just IMHO. People don't type URLs by hand all that often. Remember, they have to type http://git.someurl.com/someorg/somerepo to get to something in the first place. I think if you actually dug into this one, you'd find that people don't hand-type `/issues` any more than they type a repo URL. They go to a Git host and navigate. They bookmark. They follow a pasted link in Slack. They do any number of things, but hand-typing URLs like "I want my issues, let me type http://git.mycompanysrepo.com/issues" isn't covering the "90% of all users..." case.

On the other hand. I DO believe folks are going to have all kinds of repo names to migrate into Gogs, and I do think this can't be the last time somebody has a battle over a reserved keyword. With all respect to the FREAKING AMAZING project you folks have built here, this seems like an odd, antiquated policy. In point of fact, Gogs is the ONLY Git hosting tool I can think of that has any kind of policy like this at all.

I guess a fair, objective question is: does anybody have any data at all that indicates the prevalence of users who want to type `myrepoURL/issues` vs users who want to migrate in a repo called `api` (as I did earlier today)?

**Comment by crrobinson14** [comment]
It's also worth noting that I'm specifically referring to a case where I DO have an organization prefix. Even in a world where you accept that `/api` should be protected, is it still reasonable to say that `/my-project/admin` ALSO needs to be protected? I have something like 4-5 repos in various organizations that I deal with that use "admin" as the name of the project for an admin panel or tool of some kind. This seems like an unnecessary burden to have to rename them just to provide the convenience of a "nice" URL for some admin endpoint within Gogs itself...

**Comment by Unknwon** [comment]
Thanks your feedback!

> I guess a fair, objective question is: does anybody have any data at all that indicates the prevalence of users who want to type myrepoURL/issues vs users who want to migrate in a repo called api (as I did earlier today)?

I do, that's the primary reason why Gogs does.

But you bring up an interesting point that reversed words for user names and repo names should be different. Because repository names are already under namespace of user.

**Comment by Unknwon** [comment]
>@Joshua-Anderson I hear you... But it seems misguided, just IMHO. People don't type URLs by hand all that often. Remember, they have to type http://git.someurl.com/someorg/somerepo to get to something in the first place. I think if you actually dug into this one, you'd find that people don't hand-type /issues any more than they type a repo URL. They go to a Git host and navigate. They bookmark. They follow a pasted link in Slack. They do any number of things, but hand-typing URLs like "I want my issues, let me type http://git.mycompanysrepo.com/issues" isn't covering the "90% of all users..." case.

Whatever you call (let's say X), you need to reverse X again. Or you maybe think `/my/issues`, then `my` and `issues` are both becoming reversed, which is worse.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by crrobinson14** [comment]
Very nice approach, I will test as soon as I can. Thanks for doing this!
