### ISSUE TITLE
WebHooks UI is not correctly rendered

### ISSUE THREAD

**Issue by gembin** [gogits/gogs#2909]
- Gogs version (or commit ref):  0.9.13.0319
- Git version: 1.5.3
- Operating system: Mac OS X - 10.9.5
- Browsers: Safari Version 9.1 (9537.86.5.17.4), Chrome 48.0.2564.116, Firefox 42.0

Screenshot:
<img width="1013" alt="gogs-webhookui" src="https://cloud.githubusercontent.com/assets/26495/14118301/79d9af86-f61b-11e5-98f3-d7042429cb3e.png">

**Comment by exmex** [comment]
Maybe related #2465 ?

**Comment by Thomasdezeeuw** [comment]
Leaving this: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/ here, for possible solutions.

**Comment by bkcsoft** [comment]
Claimed

**Comment by bkcsoft** [comment]
Fixed in #2979 

@gembin mind trying it and see if it works on your end? Easiest way to test is to replace `public/css/gogs.css` with this one https://raw.githubusercontent.com/bkcsoft/gogs/issue-2909/public/css/gogs.css

**Comment by gembin** [comment]
Awesome, tested, it works fine, thanks!

**Comment by bkcsoft** [comment]
We keep issues open until it's merged into master :wink:

**Comment by bkcsoft** [comment]
@gembin how many browsers did you try btw? I've confirmed Firefox and Chrome :smile:

**Comment by gembin** [comment]
Works on Firefox, Safari and Chrome.

**Comment by bkcsoft** [comment]
Awesome. I'll merge the fix asap :)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #2979, please test on `develop` branch or https://try.gogs.io.
