### ISSUE TITLE
迁移外部仓库(比较大时)超时

### ISSUE THREAD

**Issue by cjl3230** [gogits/gogs#2915]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):0.9.13.0318
- Git version:1.7.1
- Operating system:CentOS release 6.6 (Final)
- Database: MySQL
- Can you reproduce the bug at http://try.gogs.io:
              Yes (provide example URL):https://github.com/TrinityCore/TrinityCore.git
- Log gist:

=======================   log begin  =============================
2016/03/31 16:07:43 ^[[1;34m[D] Session ID: aa007e03be687eee^[[0m
2016/03/31 16:07:43 ^[[1;34m[D] CSRF Token: WFoSXhJGivza6F7eXymNFNB6UmY6MTQ1OTM5NjMxMTU2MjM5Mzg0NA==^[[0m
2016/03/31 16:07:43 ^[[1;36m[T] action.newRepoAction: chenjl/TrinityCore^[[0m
2016/03/31 16:15:49 ^[[1;36m[T] Doing: MirrorUpdate^[[0m
2016/03/31 16:35:41 ^[[1;31m[...routers/repo/repo.go:101 handleCreateError()] [E] MigratePost: Clone: execution is timeout [duration: 10m0s]^[[0m
2016/03/31 16:35:41 ^[[1;34m[D] Template: status/500^[[0m
[Macaron] 2016-03-31 16:35:41: Completed /repo/migrate 500 Internal Server Error in 27m57.411993908s
=======================   log  end  =============================
## Description
      迁移外部仓库https://github.com/TrinityCore/TrinityCore.git,仓库较大,10分钟超时。另外不知道是不是配置的问题(如果配置文件里可以配超时时间,而我没有配置)

...

**Comment by Unknwon** [comment]
Thanks your feedback!

Please follow in this thread: https://github.com/gogits/gogs/issues/829
