### ISSUE TITLE
'sort' field missing on issue pagination link

### ISSUE THREAD

**Issue by kuuyee** [gogits/gogs#2916]
http://127.0.0.1/developer/zngh_platform_fix/issues?type=all&sort=oldest&state=open&labels=0&milestone=0&assignee=0
![page1](https://cloud.githubusercontent.com/assets/110851/14193114/cdbd9846-f7d4-11e5-81bb-dad721198f99.png)

http://127.0.0.1/developer/zngh_platform_fix/issues?type=all&state=open&labels=0&milestone=0&assignee=0&page=2
![page2](https://cloud.githubusercontent.com/assets/110851/14193266/f64cfdb4-f7d5-11e5-910b-ae4868cb459a.png)

**Comment by Unknwon** [comment]
Hi, I've pushed fix to `develop` branch, you can also test on https://try.gogs.io

**Comment by Unknwon** [comment]
Close as fixed.
