### ISSUE TITLE
[E] LDAP Admin Search failed

### ISSUE THREAD

**Issue by jaydio** [gogits/gogs#2922]
## Platform Details

* Gogs version (or commit ref):
  * gogs-0.9.13-1458763757.5ec8ef0.centos7.x86_64
* Operating system:
  * CentOS 7
* Database:
  * MariaDB (mariadb-server-5.5.47-1.el7_2.x86_64)

## Description

When using the **Admin Filter** gogs always throws the following error:

<pre>
2016/04/04 19:42:08 [...gogs/models/login.go:267 LoginUserLDAPSource()] [E] LDAP Admin Search failed
2016/04/04 19:43:30 [...gogs/models/login.go:267 LoginUserLDAPSource()] [E] LDAP Admin Search failed
</pre>

Tried the following (valid) filter statements:

* ```(&(objectClass=*)(employeeNumber=12345))```
* ```(employeeNumber=12345)```
* ```(objectClass=*)```

All with the same result. Leaving the Admin Filter empty doesn't result in any errors.

**Comment by Unknwon** [comment]
cc @SergioBenitez @nanoant

**Comment by heioghaa** [comment]
You will get some additional info in the log if you set log level to Trace.
