### ISSUE TITLE
Add documentation for manual backup

### ISSUE THREAD

**Issue by Flux159** [gogits/gogs#2924]
Currently, the gogs documentation does not have any documentation on backing up gogs data.

It would be helpful if there was a section covering Administration / Backup practices that also mentions the `./gogs dump` command.

As referenced here: https://discuss.gogs.io/t/suggestion-on-repository-load-balancing-and-replication-hot-backup-strategy/182/8

**Comment by Liquidream** [comment]
I would also be very interested in some documentation to help me automate a nightly backup of my Gogs site (data/files/config/etc.) to somewhere like an archive. That I could then send up to a cloud backup or something. 
I'm only just starting to use Gogs, but wouldn't want to get complacent and forget to do any backups. 
Many thanks.

**Comment by laoshaw** [comment]
Same here need docs on how to backup gogs, until then it's just nervous to put gogs for serious use.

**Comment by jmgilman** [comment]
+1 A well tested method would be appreciated rather than trying to cobble my own together

**Comment by Eng3l** [comment]
I made a script that backups my postgresql database, compress my repo directory, pack all and send this pack via ssh to my backup server. Is not complicated at all.

**Comment by jmgilman** [comment]
The object is identifying what needs to be backed up and the best way to do it. Anyone can just grab and compress everything, but that's not what this issue is about.

**Comment by Eng3l** [comment]
@jmgilman ok, just saying the way I solved, my backups are up to 1 GB so I can keep an entire month. But is not a elegant solution.

**Comment by barbuslex** [comment]
+1

**Comment by jgreth** [comment]
+1

**Comment by Unknwon** [comment]
You can use `./gogs backup --database-only --target=./` and `./gogs restore --from=gogs-backup.zip`.

Also possible to backup from SQLite3 and restore to MySQL.

**Comment by fake-name** [comment]
So it sounds like  `gogs backup` supports a bunch of arguments (`--database-only`, `--target`, `--from`, etc....). Where are they documented? 

What is the difference between `gogs dump` and `gogs backup`?

**Comment by Unknwon** [comment]
No such command `dump` right now.

**Comment by Unknwon** [comment]
I'm writing a post, should be up soon.

**Comment by fake-name** [comment]
Maybe close the issue when it's available?

**Comment by fake-name** [comment]
Ok, trying `gogs backup`, it fails. This is on a running and functional gogs instance.

```
gogs@vcssrv:~$ /opt/gogs/gogs backup
2017/03/16 16:18:55 [ WARN] Custom config '/opt/gogs/custom/conf/app.ini' not found, ignore this if you're running first time
2017/03/16 16:18:55 [ INFO] Backup root directory: /tmp/gogs-backup-513963060
2017/03/16 16:18:55 [ INFO] Packing backup files to: gogs-backup-1489706335.zip
2017/03/16 16:18:55 [FATAL] Fail to dump database: fail to dump table 'User': dial tcp 127.0.0.1:3306: getsockopt: connection refused
```

**Comment by Unknwon** [comment]
@fake-name apparently you should tell Gogs which custom/conf/app.ini to use.

**Comment by fake-name** [comment]
That's the thing. The gogs server is currently running, and has been being used for ~6 months now. It knows where it's server is.

**Comment by Unknwon** [comment]
>Custom config '/opt/gogs/custom/conf/app.ini' not found, ignore this if you're running first time

Log already told you custom config file not found.

**Comment by Unknwon** [comment]
Please don't just dump questions and errors without stop a second and thinking.

**Comment by fake-name** [comment]
I understand it's not finding it's configuration. My issue is how does it *normally* determine from where to load it's config? I've been looking through the `/usr/bin/gogs` bootstrap script, and looked at `ps -lafA`, and I don't see where the path is being specified at all. 

Sure, I can hard-code the ini path in my backup script, but that seems like a bad idea, given that it must be pulling it from *somewhere*. I'd assume at this point that you can probably specify an environment variable to gogs that tells it where it should get it's config from. I'd like to use *that* for my backup scripts, so if I wind up moving anything at some point, the backup script will work without having to patch that too.

**Comment by Unknwon** [comment]
@fake-name if you start Gogs with `--config` flag, everything you do should always carry `--config` flag.

Default `custom` directory is under the same directory as Gogs **binary**, not work directory.

Post is up: https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991

**Comment by fake-name** [comment]
> @fake-name if you start Gogs with --config flag, everything you do should always carry --config flag.

That would make sense, but the gogs invocation is *only* `./gogs web -p 6000`, ergo my confusion.

**Comment by Unknwon** [comment]
How did you install Gogs?

**Comment by fake-name** [comment]
Packager.io.

Host system is Ubuntu 14.04 x64. As far as I know, I've changed very little from the defaults, though the original install (more then a year ago) was done manually.

**Comment by Unknwon** [comment]
You can also specify `GOGS_CUSTOM` env var for custom **directory**, that's a secret trick, could explain your situation.

**Comment by fake-name** [comment]
Bingo!
```

root@vcssrv:/etc# grep -ir gogs_custom .
./gogs/conf.d/other:export GOGS_CUSTOM="/etc/gogs"

```

Now to figure out how the heck that `conf.d` entry is being loaded. Thanks!
