### ISSUE TITLE
Restore data from dump command

### ISSUE THREAD

**Issue by Flux159** [gogits/gogs#2925]
Currently there is a ./gogs dump command that will generate a backup, but no way to automatically restore back.

As referenced here: https://discuss.gogs.io/t/suggestion-on-repository-load-balancing-and-replication-hot-backup-strategy/182/8

**Comment by zacheryph** [comment]
#648

**Comment by bkcsoft** [comment]
Closing as duplicate of #648 
Also see PR #3109
