### ISSUE TITLE
当组织把仓库删除后建立一个同名仓库会产生500错误

### ISSUE THREAD

**Issue by sharkrice** [gogits/gogs#2926]
- Gogs version (or commit ref): 0.8.25.0129
- Git version: 2.6.4.windows.1
- Operating system: windows
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
当组织把仓库删除后建立一个同名仓库会产生500错误，在try.gogs.io上不能重现。
...

**Comment by Unknwon** [comment]
Hi, your version is too old... duplicated to https://github.com/gogits/gogs/issues/1738
