### ISSUE TITLE
Participants of an issue or pull request should receive email notifications

### ISSUE THREAD

**Issue by zorun** [gogits/gogs#2929]
- Gogs version (or commit ref): 0.8.39.0219
- Git version: 2.1.4
- Operating system: Debian jessie
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes: https://try.gogs.io/gogs-test-2/Test_PR/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

Issues and pull requests have a list of "participants" (e.g. the person creating the issue, or anybody commenting).  However, these participants do not receive notification emails when the issue or pull request is changed (new comment, closed issue, merged pull request, etc).

Participants should receive notification emails, especially the person creating the issue (otherwise, it's impossible to know when something has changed, and casual participants may not want to watch the whole repository).

**Comment by mrkeuz** [comment]
It seems a duplicate #2854

**Comment by zorun** [comment]
Yes, it may be related, but not a duplicate, I believe.

**Comment by mrkeuz** [comment]
Yes, related, of course. 
Just I've I tried to explore this notification behavior just yesterday (on local instance). And I faced with a similar problem. As I understood when you create or comment an issue, creator in this case not appends to watching list of repo.

**Comment by Unknwon** [comment]
Postponed, this issue should fix together with users can subscribe/unsubscribe an issue thread.

**Comment by strk** [comment]
@zorun, @DblK could you please check if this issue is still present in https://github.com/go-gitea/gitea and file a ticket there if still needed ? Even better, a pull request :)

**Comment by psaavedra** [comment]
What is the current status of this issue? I wonder if there is something that I can do it to pussh forward this feature in Gogs.

**Comment by Unknwon** [comment]
@psaavedra it is in the current release cycle already...

**Comment by strk** [comment]
@Unknwon you mean it's committed already ? If so, which commit ?

**Comment by Unknwon** [comment]
@strk 
![image](https://cloud.githubusercontent.com/assets/2946214/23799060/290e3aee-0575-11e7-819f-7e3885e745e7.png)

**Comment by strk** [comment]
Milestone 0.11 (for those like me who don't want to start a GUI
to read a comment :)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by strk** [comment]
For the record, this landed with commit 23da90e25d610e94a50dd27223baaa8834f61607
