### ISSUE TITLE
Cannot type \ in issue: it becomes Yen symbol ¥

### ISSUE THREAD

**Issue by Jonny007-MKD** [gogits/gogs#2930]
- Gogs version (or commit ref): 0.9.13.0318
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
  - [ ] Test later

## Description
Whenever I try to enter a backslash '\' into an issue in gogs it is displayed as ¥. This seems to be some weird encoding issue, but I haven't experienced this in my entire life, yet. German umlauts and so an do work. I will attach two screenshots as soon as Githubs accepts the images.

This is what I typed:

    This is what I type when I press "Alt Gr" + 
    2: ²
    3: ³
    7: {
    8: [
    9: ]
    0: }
    ?: \

I can copy the backslash into it and it becomes a Yen, when copying it somewhere else it becomes a backslash again.
After submitting it the character gets removed:

    "Alt Gr" + 2: ² 3: ³ 7: { 8: [ 9: ] 0: } ?: 

For german keyboard layout see: https://de.wikipedia.org/wiki/Tastaturbelegung#Deutschland_und_.C3.96sterreich (T1)

**Comment by Jonny007-MKD** [comment]
Now the screenshots:
[gogs](https://s15.postimg.org/6qh7e6o8p/gogs.jpg)
[notepad](https://s15.postimg.org/cz2j7rltl/notepad.png)

**Comment by Unknwon** [comment]
Why your local font is different from try.gogs.io?

**Comment by Jonny007-MKD** [comment]
I don't know. I simply noticed the letters look different. Did you change the font in the develop branch recently?

**Comment by herby** [comment]
It's the font issue. Some fonts show yen instead of backslash (I think ones used to provide CJK support for terminals). AFAICT not a gogs issue.

**Comment by Unknwon** [comment]
Thanks @herby !

So... what do we do now?

**Comment by bkcsoft** [comment]
Set the font with @font-face and pull it from googles font-library perhaps? This will make every web browser show the exact same font and It's a relatively easy fix :smiley"

**Comment by Unknwon** [comment]
> Set the font with @font-face and pull it from googles font-library perhaps?

I don't think this is acceptable?

**Comment by bkcsoft** [comment]
Obviously with self-hosting as an option (we already have "offline mode")

https://developers.google.com/fonts/faq#can_i_download_the_fonts_on_google_fonts_to_my_own_computer

**Comment by Unknwon** [comment]
The file is pretty large I gues...

**Comment by Jonny007-MKD** [comment]
I don't know why the font in my instance is different to the one on try.gogs.io. Still, this tells us that my browser isn't the problem. I have activated the `offline_mode`, could this be the reason?

The calculated `font-family` for `textarea#content` at my local instance is
 `"Helvetica Neue","Meiryo Ui","Microsoft YaHei",Arial,Helvetica,sans-serif`
(from gogs.css:7, selector: `body`)

whereas at try.gogs.io it is
`"Consolas",monospace`
(from gogs.css:1589, selector: `.repository .comment.form .content textarea`)


Here is the CSS (gogs.css:1589) from my instance:

    .repository .comment.form .content textarea {
        height: 200px;
    }

and this is the CSS from try.gogs.io:

    .repository .comment.form .content textarea {
        height: 200px;
        font-family: "Consolas", monospace;
    }

**Comment by Jonny007-MKD** [comment]
> The file is pretty large I guess...

I downloaded Consolas.ttf (not from Google Fonts as I couldn't find it) and its 117 kB. I don't expect "normal" fonts to get any larger than a few hundred kB.

**Comment by andreynering** [comment]
@Jonny007-MKD 

> I don't know why the font in my instance is different to the one on try.gogs.io

You probably have to compile from the `develop` branch again. I think you have an older version.

**Comment by Jonny007-MKD** [comment]
This is true :+1: and thus this issue is already fixed: 3decc0b3d6db450d1885ea5cffef8491136d72ca (22 days ago). The latest release (the one I'm using) is 26 days old. On the current master I can use the '\'.
