### ISSUE TITLE
Unfriendly default value for "Run User" on install

### ISSUE THREAD

**Issue by strk** [gogits/gogs#2933]
Upon installation, the default "Repository Root Path" is under the home dir of the user who launched "gogs",  but the default  "Run User" does not that same user. On clicking the "Install" (or is it "create"? I don't remember) a check is made by the code and if "Run User" doesn't match the user who did run "gogs" an error is reported about the mismatch.

So question: why not defaulting to the user running gogs ? Is gogs meant to be run as root for later switching user ?

**Comment by Unknwon** [comment]
Hi, it is on purpose, to tell you change a user to run Gogs. Make user panic to raise their notice on that field.

I don't consider this is as a bug.
