### ISSUE TITLE
Inactive, Deactivated user can still log in

### ISSUE THREAD

**Issue by lubko** [gogits/gogs#2937]
In admin interface for each user, there is a checkbox "This account is activated".
Upon disabling, and saving the change, the user can still log in.
Restarting gogs does not help.

- Gogs version (or commit ref): 0.9.15.0323
- Database:
  - [ ] MySQL

**Comment by vivace-io** [comment]
I am able to replicate this. 

The `is_active` value appears to be set as expected in the database. I'm trying to find where a check for this value is in authentication methods, but I can't seem to find any...?

**Comment by Unknwon** [comment]
`is_active` is used for check if user has verified the email, added new option `ProhibitLogin` to restrict user login by admin, pushed to `develop` branch.
