### ISSUE TITLE
gogs_v0.9.0_linux_amd64 升级 gogs_v0.9.13_linux_amd64 失败.

### ISSUE THREAD

**Issue by yzdel200** [gogits/gogs#2944]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.1.4
- Operating system: debian8
- Database:
  - [ ] PostgreSQL
  - [x] MySQL(MariaDB10.0.23)
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

升级覆盖相关文件后，在服务器启动，提示警告，然后就不能访问了.
错误日志:
2016/04/07 10:09:04 [I] Gogs: Go Git Service 0.9.13.0318
2016/04/07 10:09:04 [I] Log Mode: File(Trace)
2016/04/07 10:09:04 [I] Cache Service Enabled
2016/04/07 10:09:04 [I] Session Service Enabled
2016/04/07 10:09:04 [I] Git Version: 2.1.4
2016/04/07 10:09:04 [I] Migration: convert date to unix timestamp
2016/04/07 10:09:04 [I] Converting table: action
2016/04/07 10:09:04 [T] Table [action]: offset: 0, beans: 100
2016/04/07 10:09:09 [T] Table [action]: offset: 100, beans: 100
2016/04/07 10:09:15 [T] Table [action]: offset: 200, beans: 100
2016/04/07 10:09:20 [T] Table [action]: offset: 300, beans: 100
2016/04/07 10:09:24 [T] Table [action]: offset: 400, beans: 100

**Comment by terrywh** [comment]
你这个日志就是还没升级完成，正在做 migrate，我这个升级等了好久的。。。

**Comment by Unknwon** [comment]
@terrywh has said what needs to be said...
