### ISSUE TITLE
error: RPC failed; result=22, HTTP code = 413

### ISSUE THREAD

**Issue by strk** [gogits/gogs#2945]
I cannot push a relatively large repo over HTTPS. This is what I get:

On the pushing side:
```
Compressing objects: 100% (60002/60002), done.
error: RPC failed; result=22, HTTP code = 413 | 282.00 KiB/s
fatal: The remote end hung up unexpectedly
Writing objects: 100% (315257/315257), 592.69 MiB | 75.62 MiB/s, done.
Total 315257 (delta 262546), reused 304787 (delta 254543)
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

On the gogs console:
```
[Macaron] 2016-04-07 17:34:28: Completed /osgeo/qgis.git/git-receive-pack 0  in 5.364572757s
```

But the repository has no data in it.
Trying to push an older version (so less objects) eventually succeeded.

**Comment by strk** [comment]
Oh, but then the server is crashed on trying to access the successfully pushed-to repo:
```
2016/04/07 17:41:48 [...ules/context/repo.go:221 func1()] [E] GetBranches: exit status 1
```

**Comment by strk** [comment]
Sorry, this is with "develop" branch as of 0f28690

**Comment by strk** [comment]
One of the repositories that failed locally succeeded on try.gogs.io: https://try.gogs.io/strk/postgis (although it is slow to render the page).
Another one, bigger, failed with the same error (at the client side, dunno what happened at the server side): https://try.gogs.io/strk/qgis

The repo that fails pushing, if you want to try (pushed via https) is from https://github.com/qgis/qgis

**Comment by strk** [comment]
NOTE: I used "git push --all" when qgis push failed, hadn't tried reducing to a single branch.

**Comment by Unknwon** [comment]
It is your configuration issue, whatever proxy you're using limited size of HTTP buffer.
