### ISSUE TITLE
mysql not accepted as session provider

### ISSUE THREAD

**Issue by Marco01809** [gogits/gogs#2947]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.1.4
- Operating system: Debian 8 x64
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description
I've installed the latest binary package of gogs.
When trying to use 'mysql' as [session] PROVIDER:

> Apr 08 00:46:28 proteus gogs[13894]: panic: session: unknown provider 'mysql'(forgotten import?)
Apr 08 00:46:28 proteus gogs[13894]: goroutine 1 [running]:
Apr 08 00:46:28 proteus gogs[13894]: panic(0xf931e0, 0xc820c12df0)
Apr 08 00:46:28 proteus gogs[13894]: /usr/local/src/go/src/runtime/panic.go:464 +0x3e6
Apr 08 00:46:28 proteus gogs[13894]: github.com/go-macaron/session.Sessioner(0xc820c205a0, 0x1, 0x1, 0x0, 0x0)
Apr 08 00:46:28 proteus gogs[13894]: /home/vagrant/go/src/github.com/go-macaron/session/session.go:149 +0x13c
Apr 08 00:46:28 proteus gogs[13894]: github.com/gogits/gogs/cmd.newMacaron(0xc8202db2c0)
Apr 08 00:46:28 proteus gogs[13894]: /home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:158 +0x1094
Apr 08 00:46:28 proteus gogs[13894]: github.com/gogits/gogs/cmd.runWeb(0xc8202db2c0)
Apr 08 00:46:28 proteus gogs[13894]: /home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:185 +0xbb
Apr 08 00:46:28 proteus gogs[13894]: github.com/codegangsta/cli.Command.Run(0x112d1a0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11cf950, 0x15, 0x0, ...)
Apr 08 00:46:28 proteus gogs[13894]: /home/vagrant/go/src/github.com/codegangsta/cli/command.go:174 +0x1399
Apr 08 00:46:28 proteus gogs[13894]: github.com/codegangsta/cli.(*App).Run(0xc8202db040, 0xc820066100, 0x4, 0x4, 0x0, 0x0)
Apr 08 00:46:28 proteus gogs[13894]: /home/vagrant/go/src/github.com/codegangsta/cli/app.go:187 +0x112b
Apr 08 00:46:28 proteus gogs[13894]: main.main()
Apr 08 00:46:28 proteus gogs[13894]: /home/vagrant/go/src/github.com/gogits/gogs/gogs.go:40 +0x368

Please let me know if you need any more information.

**Comment by Unknwon** [comment]
Hmm... Gogs does not support MySQL as session provider actually...

**Comment by Unknwon** [comment]
Comment in the `app.ini` is wrong, sorry about that...
