### ISSUE TITLE
[...s/routers/install.go:102 InstallInit()] [E] Install: Installation is prohibited

### ISSUE THREAD

**Issue by hellywangxiaoyun** [gogits/gogs#2949]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):
- Git version:
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by Unknwon** [comment]
It is prohibited because the instance (someone else) has went through the install process before you send the form.
