### ISSUE TITLE
每次通过Windows服务启动gogs都会默认到install

### ISSUE THREAD

**Issue by Andecy** [gogits/gogs#2952]
我的启动参数：

sc create gogs start= auto binPath= "C:\Program Files (x86)\gogs\gogs.exe web --config C:\Program Files (x86)\gogs\custom\conf\app.ini"

系统：Win2008 R2

**Comment by Unknwon** [comment]
What is the content of `C:\Program Files (x86)\gogs\custom\conf\app.ini`?

**Comment by Andecy** [comment]
thanks, I fix it with nssm
