### ISSUE TITLE
when   I  open this url 'http://xx.xx.xx:3000/.user/reps/src/refs/remotes/gogs/repository',

### ISSUE THREAD

**Issue by everhopingandwaiting** [gogits/gogs#2955]
For bug reports, 
- Gogs version : Version: 0.9.13.0318 
- Git version: Version: 2.5.0
- Operating system: rpi -  raspbian -- jessie  armv7
- Database:
  - [ ] PostgreSQL
  - [ * ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ * ] No
  - [ ] Not relevant

- Log gist:

2016/04/11 09:39:27 [W] Diff data too large
2016/04/11 10:29:19 [...ers/repo/download.go:59 SingleDownload()] [E] ServeBlob: w                                          rite tcp 222.30.64.155:3000->218.69.11.110:2327: write: broken pipe
2016/04/11 10:29:19 [...ers/repo/download.go:59 SingleDownload()] [E] ServeBlob: w                                          rite tcp 222.30.64.155:3000->218.69.11.110:2330: write: broken pipe
2016/04/11 10:31:35 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/origin/graduation-lib
2016/04/11 10:31:38 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/origin/graduation-lib
2016/04/11 10:31:44 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/origin/graduation-lib
2016/04/11 10:31:47 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/origin/graduation-lib
2016/04/11 10:41:50 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/gogs/graduation-lib
2016/04/11 10:46:53 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/gogs/graduation-lib
2016/04/11 10:49:36 [...ules/context/repo.go:370 func1()] [E] RepoRef invalid repo                                          : branch or tag not exist: refs/remotes/gogs/graduation-lib

## Description

...

 is now  not support refs ?
and  when I  push  the changes to remote, in  gogs I cann't see anything, but  there has  msg
 ` j.yao.SUSE 推送了 refs/remotes/gogs/repository 分支的代码到 username/repository`
![pic](http://222.30.64.155:3000/img/404.png)

-----------
then  maybe  rpi's cpu freq is too  lower ,and when I  have a pull request , it's  response is very slow

**Comment by Unknwon** [comment]
Actually, I don't get your error description... ?
