### ISSUE TITLE
[Feature] Honour partially matching Accept-Language HTTP request header

### ISSUE THREAD

**Issue by strk** [gogits/gogs#2958]
It would be useful to talk with new users in their preferred language, honouring the HTTP Accept-Language request header (using the first known language found in the header).

I don't see that happening as of 0.9.13.0318  (the user is always given the english version by default)

**Comment by andreynering** [comment]
> the user is always given the english version by default

Works for me. My main language is shown by default, no English.

**Comment by strk** [comment]
Uhm, then maybe I'm messing up with the proxy. Which version are you using ?

**Comment by andreynering** [comment]
Develop branch, but ever worked for me.

**Comment by strk** [comment]
I'm testing with `Accept-Language: it,en-US;q=0.7,en;q=0.3`, can it be I would need `it-IT` instead of just `it` ? Could you share your language for me to try that one ?

**Comment by andreynering** [comment]
Try:

```
pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
```

**Comment by strk** [comment]
Ok I confirm `it-IT` works while `it` does not.
As the `it` value is given by default by firefox 45.0 upon setting the user's "preferred language" I guess the matcher in Gogs could try to cope better with these "partial matches". What do you think ?

**Comment by andreynering** [comment]
Yes, I think `it` should, especially if it works for other websites.

**Comment by strk** [comment]
Uhm, as I usually prefer english I don't know if it works on other websites, do you have a suggestion for one to try with this setting ?

**Comment by strk** [comment]
Well, I tried facebook.com and yes, it does recognize `it` too. Will update summary ticket to reflect the actual problem.

**Comment by strk** [comment]
FYI: trac also correctly recognizes `it`

**Comment by xiegeo** [comment]
I read about this some where, it is harder then it looks.
Found it: https://blog.golang.org/matchlang
And it works: https://play.golang.org/p/bXXbd4JfHI

**Comment by xiegeo** [comment]
@Unknwon Are you working on this, or waiting for something?

**Comment by Unknwon** [comment]
@xiegeo No I am not, I think it requires changing Macaron i18n middleware, not on Gogs side.

**Comment by Unknwon** [comment]
The third-party issue (https://github.com/go-macaron/i18n/issues/4) has been solved, please update this dependency and recompile Gogs to test the change.

**Comment by strk** [comment]
Confirmed, thanks !
