### ISSUE TITLE
Current version on README for master is wrong

### ISSUE THREAD

**Issue by Nhoya** [gogits/gogs#2959]
The current version (referred to the last release on github is 0.9.13 not 0.9.15)
https://github.com/gogits/gogs/blob/master/README.md#current-version-0915
https://github.com/gogits/gogs/releases

**Comment by moltam** [comment]
This is normal, not a typo. Gogs has several versions in the master branch, which aren't tagged (these can be compiled from source). Tagged versions usually come once in a month with binaries compiled.

**Comment by Nhoya** [comment]
But in this way source users have an updated version instead of binary users

**Comment by Unknwon** [comment]
@moltam has posted what needs to be said...

**Comment by sbrl** [comment]
Ok. Perhaps something small in brackets saying that this is the latest master version would avoid confusion?

**Comment by Unknwon** [comment]
GitHub releases already listed binary versions: https://github.com/gogits/gogs/releases

**Comment by Unknwon** [comment]
README updated: https://github.com/gogits/gogs/tree/develop
