### ISSUE TITLE
Qualify cross-repository ticket references

### ISSUE THREAD

**Issue by strk** [gogits/gogs#2960]
As of 0.9.13.0318 referencing a ticket of a different repository results in rendering just the target ticket number w/out the target ticket repository name. It is confusing, IMHO.
On github those kind of references are rendered as `org/repo#ticketnum` instead.

**Comment by Unknwon** [comment]
Can you given examples on https://try.gogs.io?

**Comment by strk** [comment]
https://try.gogs.io/strk/test2/issues/1 -- see how the reference to `#3` does not include the repository name (`kalxas/OSGeoLive`)

**Comment by strk** [comment]
Another test (so it doesn't point to a 404): https://try.gogs.io/strk/test1/issues/1

it would be also nice to get a back-reference, but I guess that's for another ticket ?

**Comment by lstahlman** [comment]
I can pick this up.

**Comment by Unknwon** [comment]
Fixed by #3436.
