### ISSUE TITLE
Markdown issue in README.md

### ISSUE THREAD

**Issue by orbistertius** [gogits/gogs#2962]
I created a mirror of [elastic-etcd](https://github.com/sttts/elastic-etcd) in a gogs 0.9.15.0323 running in Docker container (with SQLite database). The README.md is rendered with errors:

In section "Output Format", second item in the list, after "prints", the block of code is not rendered. 

The issue is reproduced in try.gogs.io [here](https://try.gogs.io/emiliano/elastic-etcd).

The same README.md seems to be rendered correctly in [dillinger.io](http://dillinger.io/) and [stackedit.io](https://stackedit.io/editor) for example.

EDIT: it seems that block code fences ``` may be not rendered well if they aren't at start of the line.

**Comment by Gibheer** [comment]
Hi,

the problem is the missing empty line between the fence and the line before. The problem would come from [blackfriday](https://github.com/russross/blackfriday), the markdown library used.

**Comment by Unknwon** [comment]
Hi, Gogs only supports standard Markdown syntax as @Gibheer mentioned we use blackfriday, please file issues to upstream repository.
