### ISSUE TITLE
nil pointer in overview on using unicode in commit message

### ISSUE THREAD

**Issue by Jofkos** [gogits/gogs#2963]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.1.4
- Operating system: Debian
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

The overview isn't displayed, but i get that error message:
```
template: user/dashboard/feeds:53:18: executing "user/dashboard/feeds" at <$push.Commits>: nil pointer evaluating *models.PushCommits.Commits
```
When i looked in the database, i found the reason: the `action` was incomplete. The gson string was cut of and the part after the unicode symbol (:smirk:) was missing.
I wasn't able to reproduce it, because my commits weren't displayed at the test repos overview

**Comment by bkcsoft** [comment]
You forgot to include gogs/git-versions (yes, they are relevatnt :smiley: )

**Comment by Unknwon** [comment]
Hi, if you're not able to reproduce on demo site, please update to `master` version and try again.
