### ISSUE TITLE
organization on explore page

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#2964]
Hi guys,

I'm looking here that on explore page have a sidebar with repositories and users, but, why not add organizations too?

What you think? thanks

**Comment by FibreFoX** [comment]
It was very frustrating to only find users or repositories ... took me some time to realize that no organisation-overview was existing.

As organisations are somewhat like users, they should be listed there, or better as requested, on a separated overview-page.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2951...
