### ISSUE TITLE
Default config: use HTTP_ADDR in LOCAL_ROOT_URL

### ISSUE THREAD

**Issue by nd2s** [gogits/gogs#2968]
I could be wrong but I think gogs is currently listening on ipv4 only with default config. 

The config key `server.LOCAL_ROOT_URL` is currently set to `http://localhost:%(HTTP_PORT)s/`. It should use the `HTTP_ADDR` variable instead of `localhost` as `localhost` is very likely pointing to the ipv6 loopback address as well, where gogs isn't listening.

**Comment by bkcsoft** [comment]
gogs is indeed only listening on ipv4 (a bug IMO and it should be changed to use `HTTP_ADDR` instead), but the rest is incorrect.

`net.Dial` will fetch all ip-addresses mapped to `localhost` and try to connect to them all, first one wins.

A simple test will show this :smile: (after some testing it seems like golang is even doing reverse lookups o.O )

```
[bkc@bkc-900] $ ADDR="localhost:3000" go run main.go 
Serving on  localhost:3000
Trying [::1]
 - [::1] Worked
Trying 127.0.0.1
 - 127.0.0.1 Worked
Trying localhost
 - localhost Worked
[bkc@bkc-900] $ ADDR="127.0.0.1:3000" go run main.go 
Serving on  127.0.0.1:3000
Trying [::1]
 - [::1] Worked
Trying 127.0.0.1
 - 127.0.0.1 Worked
Trying localhost
 - localhost Worked
[bkc@bkc-900] $ ADDR="[::1]:3000" go run main.go 
Serving on  [::1]:3000
Trying [::1]
 - [::1] Worked
Trying 127.0.0.1
 - 127.0.0.1 Worked
Trying localhost
 - localhost Worked
[bkc@bkc-900] $ ADDR=":3000" go run main.go 
Serving on  :3000
Trying [::1]
 - [::1] Worked
Trying 127.0.0.1
 - 127.0.0.1 Worked
Trying localhost
 - localhost Worked
```

Code:
```go
package main

import (
	"os"
	"fmt"
	"net/http"
)

func main() {
	serv := &http.Server{ Addr: os.Getenv("ADDR") }
	go serv.ListenAndServe()

	fmt.Println("Serving on ", os.Getenv("ADDR") )
	fmt.Println("Trying [::1]")
	if _, err := http.Get("[::1]:3000"); err != nil {
		fmt.Println(" - [::1] Worked")
	} else {
		fmt.Println(" - [::1] Failed")
	}
	fmt.Println("Trying 127.0.0.1")
	if _, err := http.Get("127.0.0.1:3000"); err != nil {
		fmt.Println(" - 127.0.0.1 Worked")
	} else {
		fmt.Println(" - 127.0.0.1 Failed")
	}
	fmt.Println("Trying localhost")
	if _, err := http.Get("localhost:3000"); err != nil {
		fmt.Println(" - localhost Worked")
	} else {
		fmt.Println(" - localhost Failed")
	}

}
```

**Comment by nd2s** [comment]
The `localhost` is also used in the git hooks. On my FreeBSD system pushing a repository always took ages because the hook tried to connect to the ipv6 address first, and only retried with ipv4 after the first request timed out.

Or does gogs use Go binaries in git hooks?

**Comment by Unknwon** [comment]
Please test out `develop` branch again.

**Comment by Unknwon** [comment]
Close as fixed.
