### ISSUE TITLE
Can't access Teams Access to Repo from Repo pages

### ISSUE THREAD

**Issue by Dortamur** [gogits/gogs#2970]
There does not seem to be any way to view or change which Teams have access to a Repo from either the Repo's home page, the Repo Settings page, or the list of Repos on the Organization page. It would be of great use to be able to see which teams have access to a repo, and be able to edit this, from the repo info places.

I know you can go to a Team, and add a Repo, but this seems counter-intuitive.
The normal workflow is to create a Repo, and then from the Repo, add which Teams have access - not the other way around.

Ideas for Improvements:

- On the homepage for a repo, show the Teams with access to the Repo, or a Teams Count, and link to a "Edit Teams for this Repo" screen
- Under the Repo Settings, either under Collaboration, or a separate "Teams" section, add the capability to view, add & remove Teams for the repo, including showing the Team access level
- On the Organization home, for the main list of Repositories, include a list of Teams with access next to each repo
- When creating a new Repository, if the Owner is an Organisation, give the ability to add Teams straight away, as part of the Creation process

Thanks

**Comment by Unknwon** [comment]
Hi, one team only has one level of access to repositories it contains, and it is in the team settings page.

I remember there are corresponding issues already, closing this.
