### ISSUE TITLE
[FR] Sync fork with upstream repo from UI

### ISSUE THREAD

**Issue by mrkeuz** [gogits/gogs#2973]
It is possible to sync fork with upstream repo? (fork <-- upstream)
After  merge pull request i.e. When upstream repo more fresh than fork.

Maybe feature request if can't?

**Comment by barracks510** [comment]
It's a simple command. 
`git pull $upstreamlocation`

**Comment by k13elle** [comment]
do not have button in Web GUI?

**Comment by Unknwon** [comment]
Since it could cause many conflicts, web UI can handle very little, I don't think it is a good idea.
