### ISSUE TITLE
[Feature Request] Easier Team Allocation for Repositories

### ISSUE THREAD

**Issue by luxlogica** [gogits/gogs#2975]
Right now, allocating a repository to a team is a bit of a chore... Let's say that the 'mobile-dev' team needs a new repository, for a new project, "mobile-proj". The steps in Gogs (0.9.13) are:

1. create a new "mobile-proj" repository, and make the company the owner
2. go to the Company page
3. go to the "mobile-dev" Team page
4. click on the small  "repositories" link there
5. enter the new repository name, "mobile-proj", and click "Add Team Repository"

It's quite convoluted. A wonderful solution would be, if when creating the project with a company as the owner, we were able (right there in the creation screen) to already select a team. That would be incredibly useful!

Another possible solution could be, to be able to select and allocate teams from a repository's "Settings" page - i.e., if the owner is a company, then there could be settings there that allowed team allocation for the repository. That would also be an incredibly handy solution.

**Comment by Unknwon** [comment]
I think this is basically same to https://github.com/gogits/gogs/issues/568...
