### ISSUE TITLE
MathJax support in Markdown pages

### ISSUE THREAD

**Issue by olaf1** [gogits/gogs#2977]
## Description

I would love to have [MathJax](https://www.mathjax.org/) support in gogs when editing markdown files (e.g. README.md, wiki entries). Actually this only needs adding some lines to the appropriate __html header__, e.g.:
```html
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
see [MathJax documentation](http://docs.mathjax.org/en/latest/start.html).

How can I accomplish editing the html header for markdown pages in gogs?

**Comment by andreynering** [comment]
You could use the [alpha support for custom templates](https://github.com/gogits/gogs/issues/2098#issuecomment-195785397) to do it yourself in your own instance. I think it isn't in the stable binary still, so you would have to compile Gogs from source.

**Comment by olaf1** [comment]
Thanks for the fast answer / suggestion!

As I understand [alpha support for custom templates](2098#issuecomment-195785397), a single template file only references a single file in the gogs/git file hierarchy. For my purpose this seems a bit awkward, since I want __every__ Markdown file (i.e. all files in all projects with extension *.md) to include the above mentioned html header line(s) for MathJax. I guess I will rather go for some ugly hack like injecting the required header lines via an fastcgi script or similar.

**Comment by andreynering** [comment]
Isn't it enought to include the Javascript in the HTML `<head></head>` of every page (or in the bottom before `</body>`)?

I don't know how MathJax works, and if it would work, just trying to help.

**Comment by olaf1** [comment]
### Enabling [MathJax](https://www.mathjax.org/) using Apache mod_ext_filter

The only way I found to globally enable MathJax is to _inject_ a `<script>` tag into each header section of Gog's generated html-files. This is a bit hackish, but is fully practicable, as long as we don't have a realy busy site (the sed script only takes approx. 2ms extra time). It works for me, anyway. 

Still I thing MathJax should be a standard configurable server option. Here are some MathJax examples (not rendering here but beautifully rendering on my private Gogs site, thanks to the mod_ext_filter based hack described below:

#### MathJax examples

This \\(\int_{a}^{b}\frac{1}{x} = \log(|b|) -\log(|a|)\\) is __inline mode__.

And this is __display mode__:

\\[
\int_{a}^{b}\frac{1}{x} = \log(|b|) -\log(|a|)
\\]

#### Using Apache mod_ext_filter

In order to inject the required MathJax header lines, add the following lines to the your Apache `VirtualHost` configuration (see Apache documentation on [mod_ext_filter](https://httpd.apache.org/docs/current/mod/mod_ext_filter.html#extfilterdefine)):

```apache
ExtFilterDefine insert_mathjax mode=output intype=text/html outtype=text/html \
	cmd="/bin/sed -es#</head>#\\t<script\ src=\"https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>\\n</head>#"

<Location "/">
	SetOutputFilter insert_mathjax
</Location>
```

**Comment by Chupaflo** [comment]
I added the lines given by @olaf1 in his first post between the `<head></head>` in the file `gogs\templates\base\head.tmpl` and it worked fine with a restartof the gogs server.
