### ISSUE TITLE
every time push, it can only push one image file

### ISSUE THREAD

**Issue by niluanxy** [gogits/gogs#2982]
every time push,it can only push one image file,if file number more then one,it will push error and message:

POST git-receive-pack (chunked)
error: RPC failed; result=22, HTTP code = 413
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

Gogs Version: 0.8.43
OS Version: CentOS 7 x64
Database Version: mysql

**Comment by jeppech** [comment]
HTTP 413, indicates that the request is too large, e.g the objects being pushed to server exceeds a limit, that is defined within the webserver you're using. 

I actually don't know if you can increase this size in the Gogs config, but I know that you could use the SSH address instead of HTTP, as the remote for  your repositories.

**Comment by niluanxy** [comment]
i have edit push file size,and now it can push one file like 2mb,but when i push two file that size is 1mb,it will faild.


原始邮件
发件人:Jeppe Christiansennotifications@github.com
收件人:gogits/gogsgogs@noreply.github.com
抄送:木风niluanxy@163.com
发送时间:2016年4月15日(周五) 18:39
主题:Re: [gogits/gogs] every time push, it can only push one image file(#2982)


HTTP 413, indicates that the request is too large, e.g the objects being pushed to server exceeds a limit, that is defined within the webserver you're using.
I actually don't know if you can increase this size in the Gogs config, but I know that you could use the SSH address instead of HTTP, as the remote for your repositories.

**Comment by jeppech** [comment]
Try pushing to the remote using the ssh address for the server. I don't know exactly, what the limit for Gogs is. But usually, by default it's 2MB. So it's could seem that you're still hitting the limit in the webserver.

**Comment by jeppech** [comment]
The webserver has a request limit, the only limit when using the SSH server, is the disk size of the server :)

**Comment by niluanxy** [comment]
thank you,i will try to change limit.

**Comment by flotho** [comment]
Hi @niluanxy , did you solve your issue?
Did you found the option to setup the webserver?
