### ISSUE TITLE
when  use 'git  push origin -f ' ,it cann't to push the webhook message !

### ISSUE THREAD

**Issue by everhopingandwaiting** [gogits/gogs#2983]
- Gogs version (or commit ref):
- Git version:  
 2016 Gogs Version: 0.9.13.0318 Page: 189ms Template: 36ms
English
Website Go1.6

- Operating system: rpi
- Database:
  -  [ X ] sqlite3

## Description

...

![_040](https://cloud.githubusercontent.com/assets/6021724/14565871/ad439606-035f-11e6-8c96-2c4c6a869edb.png)

**Comment by everhopingandwaiting** [comment]
also if don't use '-f' ,there still hava this problem, 

I use the https protocol ,

**Comment by Unknwon** [comment]
Please check if there is any error in `path/to/gogs/log/serv.log`.

**Comment by everhopingandwaiting** [comment]
yes ,it cause by issue  #3078

**Comment by Unknwon** [comment]
So it is fixed now?

**Comment by everhopingandwaiting** [comment]
yeah. it is, you can close this issue.hha
