### ISSUE TITLE
Unable to remove repository, white screen

### ISSUE THREAD

**Issue by rikvanderkemp** [gogits/gogs#2984]
- Gogs version (or commit ref):  0.9.13.0318
- Git version: 2.1.4
- Operating system: Debian 8.4
- Database: MySQL
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X ] No
  - [ ] Not relevant

## Description
Whenever I try to remove a repository I get a white screen and the repository isn't removed. I am unsure which log file should contain an error but `gogs.log` does not get information about a possible error. I checked the rights on the `gogs-repository` folder but that does not yield any incorrect settings. 

I run gogs directly using `./gogs web` (configured with supervisor) and proxy through nginx. This also occurs without nginx.

**Comment by krembo99** [comment]
Did you tried to see permissions ? Assign Access ?

**Comment by Unknwon** [comment]
Please post Gogs backend logs here.
