### ISSUE TITLE
automated backups to S3

### ISSUE THREAD

**Issue by harmw** [gogits/gogs#2985]
I'd like Gogs to do automated scheduled backups of *everything* to a S3 bucket.

**Comment by bkcsoft** [comment]
IMO this is way outside the scope of gogs, and is easier (and more reliable) to do as a cron-script.
You'd need to run `gogs dump` and copy the repo-directory.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/353...
