### ISSUE TITLE
Issue comment notification mail do not contain comment author

### ISSUE THREAD

**Issue by strk** [gogits/gogs#2988]
Mail notifications for issue comments do not contain comment author name, but do contain full comment. It'd be more useful to have the commenter name in there too.

Beside, the issue comment notification body is hard-coded in mail.go (SendIssueNotifyMail) so the content cannot be tweaked using templates.

**Comment by strk** [comment]
I was just hit by this again, and found my previously reported issue before filing a new one.
Is a self upvote valid ? :)

**Comment by Unknwon** [comment]
Can you give an example.... ?

**Comment by strk** [comment]
Your comment arrived with `From: 无闻 <notifications@github.com>` so I guess it could be considered as including the comment author (in the From field). Closing. Will re-file with an example if it doesn't include the author.
