### ISSUE TITLE
Pull request merge manually

### ISSUE THREAD

**Issue by skaren** [gogits/gogs#2989]
Is there a way to set a pull request to 'merged' if I do the merge manually?

Gogs version: 0.9.15.0323

**Comment by jmtinghir** [comment]
+1

Also, after the manual merge, we can't see the changes anymore : 
![capture d ecran 2016-04-19 a 16 18 43](https://cloud.githubusercontent.com/assets/806239/14642367/7c8c3110-064a-11e6-97da-ca49b545640a.png)

**Comment by xxxtonixxx** [comment]
+1

**Comment by Unknwon** [comment]
Maybe you could just close that...

**Comment by Unknwon** [comment]
Any updates?

**Comment by skaren** [comment]
The problem is still present.

Gogs Version: 0.9.22.0425

![test - gogs go git service 2016-07-12 13-08-43](https://cloud.githubusercontent.com/assets/2912000/16765028/f57444e0-4831-11e6-99f7-8ce3ea8ef129.png)
