### ISSUE TITLE
PDF previewing

### ISSUE THREAD

**Issue by tforgione** [gogits/gogs#2993]
[This post explains](https://github.com/blog/1974-pdf-viewing) explains how github allow users to see a versionned pdf file directly on the website.

There is an example [here](https://github.com/nasa/pvslib/blob/5e52ed24e8dafab5ee1de8626f6fcd721a292547/vectors/doc/intersection-paper-eberly.pdf).

It would be nice to have such a feature on Gogs !

**Comment by bkcsoft** [comment]
This is pretty simple. Claimed ^.^

**Comment by bkcsoft** [comment]
@tforgione feel free to checkout #3000 and see if it works

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging #3000 , please help test on `develop` branch or https://try.gogs.io.

**Comment by tforgione** [comment]
I installed the develop version of gogs on my pc, and added a pdf on a test repository.

The pdf preview works successfully !

**Comment by Unknwon** [comment]
@tforgione Thanks your confirmation!
