### ISSUE TITLE
Pull Request error

### ISSUE THREAD

**Issue by eqbala** [gogits/gogs#2994]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):
- Git version:
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
We get the following error when we try to create a PR out of a particular repo.  What could be the fix 
CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 128 - error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
...

**Comment by eqbala** [comment]
We would like to know if there is a fix for this we gogs we use 0.8 version

**Comment by Unknwon** [comment]
@eqbala you should update Gogs in any rate if you're not using latest version for bug reporting...

**Comment by Unknwon** [comment]
ping
