### ISSUE TITLE
checkVersion()] [E] Fail to read 'templates/.VERSION' #1311 (documentation issue?)

### ISSUE THREAD

**Issue by tony** [gogits/gogs#2995]
See also #1311

Greetings, this may be a documentation issue (I can make a PR) if necessary.

I *already* use gogs in production, but using it locally for development hasn't always been streamlined for me (I think it *should* be).

I am following https://github.com/gogits/docs/blob/master/en-US/installation/install_from_source.md.

- Gogs version (or commit ref): 5ec8ef023057c8250ae9fab6a2fa26951eec848b
- Git version: 2.8.1
- Operating system: OS X
- Database: sqlite
- Can you reproduce the bug at http://try.gogs.io: Not relevant
- Log gist:

## Description

https://github.com/gogits/docs/blob/master/en-US/installation/install_from_source.md will get you

```[...gits/gogs/cmd/web.go:73 checkVersion()] [E] Fail to read 'templates/.VERSION':```

To reproduce, do ``go get -u github.com/gogits/gogs``, ``cd $GOPATH/src/github.com/gogits/gogs`` and ``go run gogs.go web``.

Also with ``go get -u github.com/gogits/gogs``, ``cdcd $GOPATH/src/github.com/gogits/gogs``, ``go build ./...`` and ``gogs web``.

**Comment by tony** [comment]
I received a reply here: https://github.com/gogits/gogs/issues/1311#issuecomment-212605643

@Unknwon I may have a different workflow than you for developing locally.

To anyone who finds the same issue, the problem is gogs isn't finding static files. The templates are there. Currently as of April 21, 2016 39356f4, the way to get this working is to set the environmental variable ``GOGS_WORK_DIR``.

To get running with sqlite:

```sh
go get -u github.com/mattn/go-sqlite3
cd $GOPATH/src/github.com/gogits/gogs
GOGS_WORK_DIR=$PWD go run -tags "sqlite" gogs.go web
```

I may follow up with some patches to the docs / project. Thanks for your patience

**Comment by Unknwon** [comment]
Don't use `go run` and run as `./gogs web`...
