### ISSUE TITLE
suggest,label can't set text color

### ISSUE THREAD

**Issue by niluanxy** [gogits/gogs#2996]
gogs support label,but it only can set background color,can't set text color,that's made some times,the label will very ugly,i supoort add to edit text color on label set window.

<img width="1204" alt="qq20160420-1 2x" src="https://cloud.githubusercontent.com/assets/7076522/14662777/20ea6690-06ec-11e6-90b8-0fdea241446b.png">

**Comment by cstroe** [comment]
Would a simpler solution be to have a predefined text color for each background color?  That way the user doesn't have more options to configure, and the colors don't clash by default.

**Comment by niluanxy** [comment]
@cstroe my suggest is add a text color box to set text color,now gogs only has one color box and only can set background-color.

**Comment by Unknwon** [comment]
Hi. I'm sorry but yes this is on purpose that you can't set text color. Only black/white is much more obvious to me.
