### ISSUE TITLE
怎么组织的其他人对组织里面的仓库有读写权限？

### ISSUE THREAD

**Issue by zhouyixing** [gogits/gogs#2998]
如题，本人在gogs上建立了组织，然后把其他同事也拉进了组织。但是其他同事只有读权限，没有写权限。这样不方便协调工作。请问如何设置呢？

**Comment by bkcsoft** [comment]
When you create a team to place colleagues in, you tell it that that team should have "Write Access" (寫入權限). Or you can place your colleagues in the Owner-group.

**Comment by zhouyixing** [comment]
谢谢(thanks)！ @bkcsoft

**Comment by l2dy** [comment]
Please close this issue if the problem is solved.

**Comment by bkcsoft** [comment]
Closed as resolved
