### ISSUE TITLE
二进制安装的程序，如何修改默认端口

### ISSUE THREAD

**Issue by AlphaSRE** [gogits/gogs#2999]
Hi all：
        二进制安装的，如何修改默认端口，app.ini文件需要放到什么地方？

**Comment by bkcsoft** [comment]
in `app.ini` set
```
[server]
HTTP_PORT = 8080
```
change 8080 to whatever port you want

**Comment by bkcsoft** [comment]
@AlphaSRE did that fix it?

**Comment by AlphaSRE** [comment]
yes，thanks

2016-04-23 10:27 GMT+08:00 Kim Carlbäcker <notifications@github.com>:
