### ISSUE TITLE
[SECURITY] git hook editing allows any user to run any shell command as the gogs service user

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3001]
The subject tells it all, letting users define git hooks allows them to run arbitrary commands on the machine running the gogs service as the user running the service. This lets, for example, anyone with an account read any repository (including private ones) or corrupt any repository (to mention a few possibility).

The only workaround currently is to forbid POSTs to ``/*/*/settings/hooks/git`` as a whole.

A more flexible system could allow selecting hooks from a list of standard hook scripts made available by the system administrator (they could be shipped as plugins).

An intermediate fix could be to only let system administrator roles edit git hooks.

**Comment by strk** [comment]
\cc @bkcsoft @Unknwon

**Comment by Eeems** [comment]
Running the hooks in a sandbox of some sort (chroot jail maybe?) Would also be a solution. This can be a bit more difficult to achieve across different platforms.

**Comment by Unknwon** [comment]
>git hook editing allows any user to run any shell command as the gogs service user 

`any user` is not valid here, please reevaluate this issue.

**Comment by strk** [comment]
Confirmed. It took some time to test (sorry) but there's indeed a specific "can create git hooks" configuration for users, which defaults to false on new users creation.

Sorry for the noise, I'm being extra paranoid, and @bkcsoft didn't help reducing that :)

**Comment by strk** [comment]
It may be useful to have the "can create git hooks" information available in the users summary table (as right now the only way to find the list of privileged users requires opening each one from the GUI, if I'm not mistaken, or running an sql query directly on the database).

**Comment by Unknwon** [comment]
> It may be useful to have the "can create git hooks" information available in the users summary table

@strk You can propose another issue for that.
