### ISSUE TITLE
[Feature Request] File / Folder Editor

### ISSUE THREAD

**Issue by ENDev15** [gogits/gogs#3002]
It would be great to see some way to edit files online like we can with GitHub, as well as create new files and folders, and of course, commit things. So far I am really liking Gogs since I can run it on my own servers, but this is one feature I really miss.

Thanks for all the great work! However, if this could be added, Gogs would **definitively** be comparable with GitHub.

**Comment by TheGreen** [comment]
See #1071

**Comment by bkcsoft** [comment]
Closed as duplicate

**Comment by sbrl** [comment]
@bkcsoft Suggestion: Add a duplicate tag to this issue tracker.
