### ISSUE TITLE
[Feature suggestion] custom js on pages

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#3004]
Hi,

I'm suggesting this because have times that you need to put custom js on Gogs. I'm as example, I need to put [piwik](https://piwik.org) js to track visitors on Gogs pages and I can't inject this js with apache because isn't possible to use proxy and sed same time.

I think that is good feature, but, with big attention alert that bad js may causes problems on Gogs instance.

What you think?

**Comment by andreynering** [comment]
For now you can override the `<head></head>` in a still experimental feature, custom templates: https://github.com/gogits/gogs/issues/2098#issuecomment-195785397 Just add you `<script></script>` there.

For more advantage customization, you may want to follow: https://github.com/gogits/gogs/issues/2438
