### ISSUE TITLE
Markdown stripping parameters from URLs when the URL contains the word 'issues'

### ISSUE THREAD

**Issue by chriswatt** [gogits/gogs#3006]
- Gogs version (or commit ref): 0.9.13.0319
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.4 LTS
- Database:
  - [x] PostgreSQL
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes https://try.gogs.io/ultralisk/ultratest/issues/2

## Description

I pasted a link into an issue comment which happened to have a similar structure to a gogs URL, gogs treated the URL like a reference link as well as stripped the parameters that the linked contained.

...

**Comment by tcarrio** [comment]
The regex processing I could find in the code starts at `./modules/markdown.go` [at line 79](https://github.com/gogits/gogs/blob/004fb30ebe403625b2315b284a85124611ba303b/modules/markdown/markdown.go#L79).

Testing off of the Go code:

```go
IssueFullPattern = regexp.MustCompile(`(\s|^)https?.\*`issues/[0-9]+(#+[0-9a-zA-Z-]\*`)?\`)
```

This essentially means any URL with the format `http://...issues/[0-9]` will format as a link to an issue, all `?`s are optional expressions so it could be either `http` or `https` 

Test Cases:

| Input URL | Output Formatting |
|-----------|-------------------|
|`http://1111/2222/ssss-issues/3333?param=blah&blahh=333` | #3333 |
|`http://test.com/issues/33333`|#33333|
|`http://test.com/issues/3`|#3|
|`http://issues/333`|#333|
|`https://issues/333`|#333|
|`http://tissues/0`|#0|

The outputs were links, you can check the actual output from my post at https://try.gogs.io/ultralisk/ultratest/issues/3

**Comment by tcarrio** [comment]
In addition to that, IssueFullPattern is used to process later in `markdown.go` [at line 128](https://github.com/gogits/gogs/blob/master/modules/markdown/markdown.go#L128). 

```go
m = IssueFullPattern.Find(link)
	if m != nil {
		m = bytes.TrimSpace(m)
		i := strings.Index(string(m), "issues/")
		j := strings.Index(string(m), "#")
		if j == -1 {
			j = len(m)
		}
		out.WriteString(fmt.Sprintf(` <a href="%s">#%s</a>`, m, base.ShortSha(string(m[i+7:j]))))
		return
	}
```

If it could be done with logic to detect the hostname or network address then this could process regex on only valid hosts. Not that it can be done to work 100% of the time, but it definitely is a starting concept.

**Comment by bkcsoft** [comment]
@tcarrio injecting settings.AppSubUrl in the regex would fix this issue, and is IMO preferable :)

**Comment by tcarrio** [comment]
@bkcsoft I'm only concerned that won't consider instances that are run using `localhost` or a direct IP address where `settings.AppSubUrl` returns the hostname

**Comment by bkcsoft** [comment]
well, I meant `settings.AppUrl` which is set in https://github.com/gogits/gogs/blob/master/modules/setting/setting.go#L309
and default being https://github.com/gogits/gogs/blob/master/conf/app.ini#L55

**Comment by bkcsoft** [comment]
That would go a long way in fixing this issue

**Comment by cstroe** [comment]
I'm going to try to work on it.  My work will be on this branch: https://github.com/cstroe/gogs/tree/issue-3006

**Comment by cstroe** [comment]
I have a fix in this PR https://github.com/gogits/gogs/pull/3121
Please feel free to test and suggest any changes.

**Comment by Unknwon** [comment]
Close as fixed.
