### ISSUE TITLE
Hide useless client-side-only Git hooks

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3007]
According to https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks only 3 hooks make sense on the server side: pre-receive, update, post-receive.

Gogs is instead allowing to edit a lot of hooks. Do they ever run ?

**Comment by bkcsoft** [comment]
They never run. And should IMO be removed since there's no way to make them run client-side automatically anyhow.

**Comment by MitchTalmadge** [comment]
Huh. Spent the last 30 minutes trying to make post-commit work (not knowing it was a client side hook.. First time using hooks). This would have saved me some time. Glad I saw this issue.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
