### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by tsukanov-as** [gogits/gogs#3009]
- Gogs version (or commit ref): [0.9.13.0319](https://github.com/gogits/gogs/commit/004fb30ebe403625b2315b284a85124611ba303b)
- Git version: 2.8.1
- Operating system: Windows 10
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (~~provide example URL~~ see screenshot)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

It is not possible to give the name of the repository in Unicode
![unicode](https://cloud.githubusercontent.com/assets/17392154/14760235/b8db23b6-0946-11e6-826e-2c91789ad30b.png)

A related issue is here: https://github.com/go-macaron/binding/issues/11

I made a small change of the regular expression, and it works well

**Comment by Unknwon** [comment]
Thanks your feedback!

Just want to make sure, will then require specific database charset in order to support unicode? 

And why `PostgreSQL` is not chekced?

**Comment by tsukanov-as** [comment]
I dont use PostgreSQL. Well, I can check it out if I can find time :pensive:

**Comment by Unknwon** [comment]
No.. you don't need to, I think the validation rule is blocked using non-english letters anyway..

**Comment by tsukanov-as** [comment]
I changed the validation rules and use for three months without any problems :sunglasses:
![unicode](https://cloud.githubusercontent.com/assets/17392154/18019801/888e0a72-6be6-11e6-98dc-1ae7eb78c254.png)

**Comment by Unknwon** [comment]
I think to make progress on this, you can instead, suggest custom validation rule for user name and repo name, so for standard Gogs installation, won't have to deal with any possible strange unicode problem.

**Comment by tsukanov-as** [comment]
Suggest here or in the go-macaron?

**Comment by Unknwon** [comment]
Here. Better to file a new issue and reference this thread.
