### ISSUE TITLE
Slack integration doesn't work properly

### ISSUE THREAD

**Issue by dobegor** [gogits/gogs#3010]
Gogs Version: 0.9.15.0323
## Description
After adding `Slack` integration, most of times Slack webhooks don't work:
`Delivery: Post https://hooks.slack.com/services/<censored>/<censored>/<censored>: dial tcp: i/o timeout`.

Sometimes (1 of ~20) it works. Using gogs from docker container (official image from Dockerhub).

**Comment by Unknwon** [comment]
Feels like your network error to me...

**Comment by liline** [comment]
I am also receiving this error at all times. in the Slack integration. The Slack webhooks are not working for me and give the error message:
`Delivery: Post https://hooks.slack.com/services/<censored>/<censored>/<censored>: dial tcp: i/o timeout.`

When I try to curl from that server, it works.
`curl -X POST --data "payload={\"text\": \"testmsg\" }" https://hooks.slack.com/services/<censored>/<censored>/<censored>
`
Am I missing a webhook setting?

Thanks in advance.

**Comment by bkcsoft** [comment]
@liline which version of gogs are you running?

**Comment by liline** [comment]
@bkcsoft Thanks for responding so quickly. I'm using  gogs version 0.9.97

**Comment by liline** [comment]
Is there perhaps a setting I neglected to modify? 

Or @dobegor were you able to solve this issue?

**Comment by FarooqKhan** [comment]
Exact Same Issue: When testing using curl from a ssh session on the gogs server it works, when testing webhook from gogs web interface it gives exact same error
Error: Delivery: Post https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXX: dial tcp: i/o timeout

My Gogs Version: 0.10.18.0313

**Comment by dobegor** [comment]
@liline no, I haven't solved that.
No network issues at all. Maybe something's wrong with Gogs' http client (idk).
I don't know why it was closed, but, anyway, there's more actively maintained fork: Gitea.

**Comment by FarooqKhan** [comment]
Thanks for the quick reply much appreciated. 
For now I will stay with Gogs, l love it and love the fact that all you people put in so much of your time into it.

**Comment by ogarcia** [comment]
I have the same issue. I think that this issue not be closed.

```
Delivery: Post https://hooks.slack.com/services/<id>/<id>/<id>: dial tcp 54.192.60.152:443: i/o timeout
```

Gogs Versión: 0.11.19.0609

Sometimes it works, sometimes it give me the error and if press "Redelivery" it works. But if I send notification by hand (with curl) always works. Maybe a problem with http client as @dobegor says?

**Comment by dobegor** [comment]
@ogarcia use Gitea. Gogs has inadequate default timeouts for hook delivery (setting.Webhook.DeliverTimeout) and the code is messy as hell.
