### ISSUE TITLE
Word wrapping in diff view

### ISSUE THREAD

**Issue by Mihara** [gogits/gogs#3012]
This is a feature request tangentially related to #1071, I suppose, because any online editor involved would also need to account for this...

It is very convenient to use git when working collectively on a large book, because it allows an editor to easily see what the author changed. However, it is also very common to write Markdown in a one-line-per-paragraph style. This results in some very long lines.

In the Gogs diff viewer, those lines are not word-wrapped, which makes them very difficult to read. I'm not sure what would be the ideal solution, providing some sort of a toggle to turn wrapping on and off, or wrap them always, but this would greatly improve the usability of Gogs for this purpose.

**Comment by Unknwon** [comment]
Please give example URLs.

**Comment by otherjoel** [comment]
@Unknwon To see what this is about, go to a commit diff containing edits to any Markdown file without hard line breaks. [Here’s one I made on the demo site](https://try.gogs.io/TLY/Smells/commit/1770ce2e3dd110eb974e804a9ac2bf8b49c85518)

* In “Unified View” the lines of text in the diff **do not** wrap. ([example](https://try.gogs.io/TLY/Smells/commit/1770ce2e3dd110eb974e804a9ac2bf8b49c85518))
* In “Split View” the lines of text **do** wrap. ([example](https://try.gogs.io/TLY/Smells/commit/1770ce2e3dd110eb974e804a9ac2bf8b49c85518?style=split))

For prose documents, the edits are **much** easier to see in split view, where the lines are wrapped.

The ideal solution: an app.ini setting like [`LINE_WRAP_EXTENSIONS`](https://gogs.io/docs/advanced/configuration_cheat_sheet#repository---editor-(repository.editor)) containing a list of file extensions whose diffs will always be line-wrapped. Either (A) the existing setting in the `[repository.editor]` section could be used for this purpose in addition to its primary purpose; or (B) a new setting added to the [`[git]`](https://gogs.io/docs/advanced/configuration_cheat_sheet#git-(git)) section.

It would also be ideal to have a setting in `app.ini` to configure the default diff view as split or unified. Currently it always defaults to unified.

Let me know which of these you'd be willing to accept pull requests for (and whether you favor A or B for the first one).

**Comment by Unknwon** [comment]
Hi @otherjoel ,

I think these two sounds good to me:

> (A) the existing setting in the [repository.editor] section could be used for this purpose in addition to its primary purpose;
>
>It would also be ideal to have a setting in app.ini to configure the default diff view as split or unified. Currently it always defaults to unified.

However... I think the reason wordwarp in split view is I couldn't figure out how to not wordwarp and make the UI work :sweat_smile:
