### ISSUE TITLE
Able to connect to the postgres unix socket

### ISSUE THREAD

**Issue by rgl** [gogits/gogs#3013]
currently, gogs is using the xorm/pq URL syntax as can be seen at:

  https://github.com/gogits/gogs/blob/004fb30ebe403625b2315b284a85124611ba303b/models/models.go#L109

which translates to:

  "postgres://git:password@/var/run/postgresql:5432/gogs?sslmode=disable"

but that does not seem to work with an unix domain socket.

but using the [alternative syntax](https://godoc.org/github.com/lib/pq) does work:

  "user=git host=/var/run/postgresql port=5432 dbname=gogs sslmode=disable"

can gogs use the alternative syntax instead?

**Comment by merlin-tc** [comment]
I'd be really interested in that too.

**Comment by Unknwon** [comment]
What do you mean by `but that does not seem to work with an unix domain socket`?

**Comment by rgl** [comment]
To connect to the unix domain socket you have to use the alternative syntax, the URL syntax does not work. Also, the alternative syntax works fine with non-unix domain sockets.

**Comment by Unknwon** [comment]
How can I find docs about connection string? I remember `"user=git host=/var/run/postgresql port=5432 dbname=gogs sslmode=disable"` is deprecated way and I don't think PostgreSQL guys not even support unix in new connection string format?

**Comment by Unknwon** [comment]
Fount it: https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING

Also, you still have port number with unix socket seems wrong anyway?

**Comment by rgl** [comment]
Having the "port number" is correct as postgres actually uses it. Its described on the link you've found:

> port
> Port number to connect to at the server host, or socket file name extension for Unix-domain connections.

**Comment by Unknwon** [comment]
OK... good to know. Anyway we have found the cause.

**Comment by mcheng89** [comment]
From Unknwon's link:

Note, however, that the slash is a reserved character in the hierarchical part of the URI. So, to specify a non-standard Unix-domain socket directory, either omit the host specification in the URI and specify the host as a parameter, or percent-encode the path in the host component of the URI:

postgresql:///dbname?host=/var/lib/postgresql
postgresql://%2Fvar%2Flib%2Fpostgresql/dbname

Try escaping the slashes :)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by rgl** [comment]
Thanks! Works fine at https://github.com/rgl/gogs-vagrant/commit/e3de5a3808beef57ccdf1ac94c836c8b78254c40 :-)
