### ISSUE TITLE
[Feature request] Private files / keys sharing with collaborators

### ISSUE THREAD

**Issue by prankymat** [gogits/gogs#3014]
It'd be great if there is a way to add privately shared files / keys between collaborators. Files that are private to the collaborators or keys that are used to deploy the project can be shared in that section.

![proposal](https://cloud.githubusercontent.com/assets/2998111/14770918/9664feb6-0a30-11e6-89cb-84ef72335f3b.png)

Would you think this is useful or a bad idea? Please advice!

**Comment by bkcsoft** [comment]
This is in my opinion outside the scope of gogs. When I share said files with collaborators I usually setup a separate repo for that which only the collabs have access to.

**Comment by Unknwon** [comment]
I think you should use Dropbox or Google Drive....
