### ISSUE TITLE
Unable to create and modify the wiki page

### ISSUE THREAD

**Issue by MetSystem** [gogits/gogs#3015]
gogs  0.9.0.0306 
- Gogs version (or commit ref):
- Git version: git version 2.7.2.windows.1
- Operating system:windows 2008 r2
- Database: 
  - [ √] MySQL  
## Description

Unable to create and modify the wiki page

## new 
``` cs
2016/04/25 10:00:35 [...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage:
 UpdateLocalWiki: Pull: exit status 128 - fatal: Not a git repository (or any of
 the parent directories): .git
```
## edit 
```cs
2016/04/25 10:06:07 [...routers/repo/wiki.go:253 EditWikiPost()] [E] EditWikiPag
e: UpdateLocalWiki: Pull: exit status 128 - fatal: Not a git repository (or any
of the parent directories): .git

2016/04/25 10:06:07 [D] Template: status/500
[Macaron] Completed /root/DdFramework/wiki/1.2-%e8%8e%b7%e5%8f%96%e5%bd
%93%e5%89%8d%e4%bd%8d%e7%bd%ae/_edit 500 Internal Server Error in 1.6237062s
...

**Comment by MetSystem** [comment]
The updated Gogs v0.9.13.0319  resolve

**Comment by Refactoring** [comment]
The problem persists... v0.9.13.0319, Windows Server 2008 R2, Mysql5.6.

`2016/07/07 02:28:38 [I] Log Mode: File(Info)
2016/07/07 02:28:38 [I] Cache Service Enabled
2016/07/07 02:28:38 [I] Session Service Enabled
2016/07/07 02:28:38 [I] Git Version: 2.8.1
2016/07/07 02:28:38 [I] SQLite3 Supported
2016/07/07 02:28:38 [I] Builtin Windows Service Supported
2016/07/07 02:28:38 [I] Run Mode: Production
2016/07/07 02:28:39 [I] Listen: http://0.0.0.0:3000`

`2016/07/07 02:28:47 [...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage: UpdateLocalWiki: Pull: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git`

**Comment by Unknwon** [comment]
Upgrade to latest `master`.
