### ISSUE TITLE
issues's attachment bug. 工单上传附件存在的问题

### ISSUE THREAD

**Issue by cnzzr** [gogits/gogs#3018]
- Gogs version (or commit ref): 0.9.13
- Git version:2.7.4
- Operating system: Windows Server 2008 X64
- Database:
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - 尚未测试
- Log gist:无

## Description
问题1：
在app.ini中配置
ALLOWED_TYPES = image/jpeg|image/png|application/pdf|application/zip
后可以选择 zip、pdf文件但是选择文件提示“您不能上传此类型的文件”
将配置文件修改为
ALLOWED_TYPES = */*
后才可以添加附件到工单

问题2：
上传zip文件后未显示正常的附件图标，点击附件下载链接后下载的文件名称为“下载”，经查上传附件的文件名称是已经保存到数据库中的

![gogs-bugs](https://cloud.githubusercontent.com/assets/239363/14780125/fe5febec-0b0d-11e6-8960-098ca4341193.png)

**Comment by Unknwon** [comment]
Hi,

> Can you reproduce the bug at http://try.gogs.io:
尚未测试

Please test before posting.

**Comment by harry91** [comment]
@Unknwon I meet exactly the same problem. But I can't test it on http://try.gogs.io , because you disabled the zip and pdf type on this site. My Go version is 1.6 and gogs version is 0.9.13.0318. Please help me out~!
![default](https://cloud.githubusercontent.com/assets/1702291/17624416/20b38ec8-60d7-11e6-95dc-20de6fc913b3.PNG)

**Comment by Unknwon** [comment]
You posted a comment and I don't get the purpose of it.

**Comment by harry91** [comment]
I mean, can you fix this bug?

**Comment by Unknwon** [comment]
We explicitly ask to do a search before posting: https://github.com/gogits/gogs/issues/3215

**Comment by harry91** [comment]
OK, thanks a lot and sorry for missing THAT one. I mean I do find this one through A "search".

**Comment by harry91** [comment]
@cnzzr 请问，在GOGS最新的版本里，你的这个问题解决了吗？
我今天早上build了最新的master分支代码，使用后发现非图片文件显示为一个下载图标了，但用windows的Chrome和IE点击下载，依旧没有文件扩展名，Firefox有扩展名，你那儿也这样吗？
try.gogs.io上不允许上传非图片附件，因此没法在那上面测试这问题。

**Comment by Unknwon** [comment]
>Gogs version (or commit ref):

master is not a valid description.

**Comment by harry91** [comment]
没事，因为这不是重点，如果他build最新的代码发现这问题解决了的话，那我这问题也就解决了。
