### ISSUE TITLE
wiki page title that contains no escape #

### ISSUE THREAD

**Issue by MetSystem** [gogits/gogs#3021]
gogs 0.9.13.0319

Gogs version (or commit ref):
Git version: git version 2.7.2.windows.1
Operating system:windows 2008 r2
Database:
[ √] MySQL
## Description

wiki page title that contains no escape #

http://192.168.0.1:3000/root/test/wiki/_pages##-1-%e4%b8%9a%e5%8a%a1%e9%83%a8%e5%88%86/_edit

**Comment by vsund** [comment]
- Gogs version: 0.9.15.0323
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database: MySQL

--

I have the same problem with `?` in file names in a "normal" repository.

Currently: `https://gogs.tld/user/repository/src/master/abc?def`
Should be: `https://gogs.tld/user/repository/src/master/abc%3Fdef`
(Replaced all `?` with `%3F`)

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/pull/3287 has some related changes, back on this until that PR has been merged.

**Comment by Unknwon** [comment]
This is fixed in `master`.
