### ISSUE TITLE
pre-commit not pulled

### ISSUE THREAD

**Issue by metal3d** [gogits/gogs#3025]
- Gogs version (or commit ref): 0.9.15.0323
- Git version: (git provided in Docker container)
- Operating system: Linux
- Database:
  - [x] PostgreSQL (Container)
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (No git hooks ?)

## Description

I just installed gogs with Docker (gogs/gogs) and created a clean repository. I changed pre-commit git hooks in repository parameters.

![image](https://cloud.githubusercontent.com/assets/100080/14837290/4c66506a-0c17-11e6-8dba-ff38059cf972.png)

The content is:

![image](https://cloud.githubusercontent.com/assets/100080/14837354/bd016d32-0c17-11e6-8f57-421afd798fa8.png)

Then I've cloned project on my host. I tried a commit and no pre-commit is executed.

The .git/hooks has only "samples", and the sample hasn't my pre-commit code (in case of, I checked).

```bash
ls .git/hooks/
applypatch-msg.sample*  post-update.sample*     pre-commit.sample*          pre-push.sample*    update.sample*
commit-msg.sample*      pre-applypatch.sample*  prepare-commit-msg.sample*  pre-rebase.sample*
```

Any idea ? bug ?
...

**Comment by bkcsoft** [comment]
They never run, and they aren't cloned into your repo. See https://github.com/gogits/gogs/issues/3007 for more information on which runs and which doesn't.

**Comment by bkcsoft** [comment]
Closing this since it is almost identical to #3007 (and the described use-case is not possible with git at all)

**Comment by metal3d** [comment]
So maybe removing the git hooks panel can be a good idea. I imagine that a lot of identical issues will come if the panel still exists.

Thanks for your answer anyway :)
