### ISSUE TITLE
Tutorial on Docker Setup and SSH Key Authentication

### ISSUE THREAD

**Issue by oleersoy** [gogits/gogs#3026]
Hi,

I was having some issues with the Docker setup, so I wrote a mini tutorial to guide myself through it.  Figured I'd share it.  I'd be happy to help integrate this into the documentation.

# Gogs Docker Installation and SSH Authentication Example

This document contains an example of how to setup Gogs using Docker on Ubuntu 14.04.  It also walks through the process of adding an SSH key and working with a `test` repository using SSH key based authentication.

First start the Gogs docker container:

    shell:~$ docker run --name=gogs -p 10022:22 -p 10080:3000 -v gogs-data:/data gogs/gogs
    Apr 26 21:43:43 syslogd started: BusyBox v1.24.1
    Apr 26 21:43:44 sshd[32]: Server listening on :: port 22.
    Apr 26 21:43:44 sshd[32]: Server listening on 0.0.0.0 port 22.
    2016/04/26 21:43:50 [W] Custom config '/data/gogs/conf/app.ini' not found, ignore this if you're running first time
    2016/04/26 21:43:50 [T] Custom path: /data/gogs
    2016/04/26 21:43:50 [T] Log path: /app/gogs/log
    2016/04/26 21:43:50 [I] Gogs: Go Git Service 0.8.42.0222
    2016/04/26 21:43:50 [I] Log Mode: Console(Trace)
    2016/04/26 21:43:50 [I] Cache Service Enabled
    2016/04/26 21:43:50 [I] Session Service Enabled
    2016/04/26 21:43:50 [I] SQLite3 Supported
    2016/04/26 21:43:50 [I] Run Mode: Development
    2016/04/26 21:43:50 [I] Listen: http://0.0.0.0:3000        

Find the gogs ip address:    

    shell:~$ docker inspect gogs | grep IPAddress
            "IPAddress": "172.17.0.2"

Configure Gogs (Leave the other fields to their defaults):
    Database: SQLite3
    Domain: 172.17.0.2
    Application URL: http://172.17.0.2:3000/

Add yourself as the admin user.  I added myself as `ole`.  After selecting `Install` gogs redirects the browser to http://172.17.0.2:3000/.  Select `Your Settings > SSH Key > Add Key` and add your public `~/.ssh/id_rsa.pub` key.  For more information see this article [SSH Key Authentication](https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server)

Create a repository named `test`.  Click on the `ssh` button to get the `ssh` clone URL for the repository.  For this case the clone url will be `git@172.17.0.2:ole/test.git`.  Note that the port is missing and that is OK.

Next clone the repository:

    git clone git@172.17.0.2:ole/test.git
    cd test
    touche README.md
    git add README.md
    git commit -m 'Added README.md'

Now push the commit:

    ole@MKI:~/test$ git push origin master
    Counting objects: 3, done.
    Writing objects: 100% (3/3), 219 bytes | 0 bytes/s, done.
    Total 3 (delta 0), reused 0 (delta 0)
    To git@172.17.0.2:ole/test.git
     * [new branch]      master -> master

Congratulations you are now authenticating to your repository using your ssh public key.

**Comment by Unknwon** [comment]
Hi, please post this to https://discuss.gogs.io/ ...

**Comment by zzxiang** [comment]
I've struggled for a day on the ssh issue. Thanks for saving me!
