### ISSUE TITLE
Macaron PANIC mkdir data: permission denied

### ISSUE THREAD

**Issue by bonanza123** [gogits/gogs#3029]
I'm running gogs version 0.9.22.0425 on a QNAP armv5tel device where I compiled gogs according to the tutorial on the website with go version "go1.4.2 linux/arm".

I'm using PostgreSQL and gogs is working fine for a couple of hours until it stops working and I have logs like this: https://gist.github.com/bonanza123/6209d7b5f4b97696e1e06a57e24273dc

Following the instructions in issue https://github.com/gogits/gogs/issues/2115, I also recompiled it but beforehand executed `go get -u gopkg.in/ini.v1`. But this didn't help as the same error occurs. This is also why I'm creating a new issue, as most of the users in the other thread reported that the fix works.

For the sake of completeness, my gogs folder looks like this: https://gist.github.com/bonanza123/d0fe007b4002737b5d94995ed5040689 and I'm running gogs using `sudo -u git ./gogs web` in that folder.

Here my custom config file in `/share/homes/git/gogs/custom/conf/app.ini`: https://gist.github.com/bonanza123/1c1af18c8d972640049718d6cf11a87c

**Comment by Unknwon** [comment]
What is the exact error message?

**Comment by Corben78** [comment]
I'm running into the same issue, while trying to start gogs as a service on a SuSE distribution.
Here is the complete [error log](https://gist.github.com/Corben78/ea37a4dfa8b36828670d8afa05f25339).

Maybe it's the same problem, when I try to start gogs as a service through `startproc` (SuSE's way of starting services):
```bash
host# /sbin/startproc -u wwwrun /opt/gogs/gogs web
2016/08/31 11:34:24 [...s/setting/setting.go:456 NewContext()] [E] Expect user 'wwwrun' but current user is: root
startproc:  exit status of parent of /opt/gogs/gogs: 1
```

**Comment by Unknwon** [comment]
@Corben78 run under user `wwwrun` as you configed.

**Comment by Corben78** [comment]
It's running without problems, when I start a shell as user `wwwrun`, but I want to start it as a service from an init-script, where I have to change the user to `wwwrun`. It doesn't work neither with `sudo -u wwwrun` (PANIC) nor with `startproc -u wwwrun` (Expect user).
Unfortunately there is no init-script under `scripts/init` for SuSE distributions.
How can I achieve this?

**Comment by Unknwon** [comment]
>How can I achieve this?

I don't know, maybe change `USER` env var in your script?

**Comment by Unknwon** [comment]
Running as root is very bad practice.

**Comment by Corben78** [comment]
That's why I want to change the user. All init-scripts are called from root, and with `sudo -u` or with `startproc -u` the called program started is using the given user id.

But looks like `su - wwwrun -c "USER=wwwrun /opt/gogs/gogs web` works.
Seems `USER=wwwrun /sbin/startproc /opt/gogs/gogs web` works, too. But here the process is running with root privileges.
I think this helped me already to progress, thank you.

**Comment by Unknwon** [comment]
Use systemd... 0.0

**Comment by Corben78** [comment]
This is a SysV init system. systemd is not possible without a lot of effort.

**Comment by miqmago** [comment]
After some frustrating trials, I've started the systemctl service as root and searched where `data` folder was being created. Surprisingly it was under /.

So what I did is to leave this directory created, change ownership of this directory and then reload service as gogs user. That works :)

So resuming just run:

```sh
sudo mkdir /data
sudo chown gogs:gogs /data -R
```

**Comment by Grief** [comment]
I got the same error when the current dir is not gogs dir i.e. when you start it from script via absolute path. To fix that, I now start it with 
`(cd /apps/gogs; /usr/bin/sudo -u git ./gogs web>/apps/gogs/log/console.log 2>&1)&`

**Comment by jmgiaever** [comment]
What I did was creating a file called _run_, and giving it permissions to execute:
`chmod +x run`
This file contains the following:
```#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "* Going into directory ${DIR}"
cd ${DIR}
echo "* Running GOGS-web"
USER=gogsuser ./gogs web
```
Change _gogsuser_ to the actual user you're using.
