### ISSUE TITLE
Ability to send test delivery for specific webhook

### ISSUE THREAD

**Issue by mcanevet** [gogits/gogs#3030]
- Gogs version (or commit ref): 0.9.13.0318
## Description

When you click on "Test delivery" on a webhook for debugging purpose, the payload is sent to all webhooks of the repository.

**Comment by bkcsoft** [comment]
Looking at the code, there's actually no way to only fire a single selected webhook (without disabling all the others first). So either have this fixed or have the "Test Delivery"-button moved

**Comment by Unknwon** [comment]
How does "Test Delivery" know which endpoint to shoot?

**Comment by mcanevet** [comment]
I was hoping that clicking "test delivery" on one secific webhook, send the payload to this webhook only

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
