### ISSUE TITLE
Non-admin user cannot list teams

### ISSUE THREAD

**Issue by fawick** [gogits/gogs#3031]
- Gogs version (or commit ref):5ec8ef023057c8250ae9fab6a2fa26951eec848b
- Git version:
- Operating system:Linux
- Database:
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

For an organization we added multiple teams and sorted users into them. When a regular user is logged in (regular as in non-Gogs-admin) and they open the origanization page, the "People" list is filled with all organization members, but the team list is always empty. Not even the teams, that the user is a member of, are listed.

As a user, I would expect to see the list of the teams I am a member of, at least.

**Comment by bkcsoft** [comment]
Looking at the code, there's actually no way to only fire a single selected webhook (without disabling all the others first). So either have this fixed or have the "Test Delivery"-button moved

**Comment by bkcsoft** [comment]
@Unknwon correct me if I'm wrong here, but is org.Teams ever set in here? o.O https://github.com/gogits/gogs/blob/master/models/org.go#L476-L491

**Comment by bkcsoft** [comment]
Should be fixed with #3048

**Comment by bkcsoft** [comment]
As per #2530, viewing teams you're not in (as a non-admin/owner) is forbidden

**Comment by fawick** [comment]
@bkcsoft Thanks for addressing the issue. 

I understand and agree with the design decision of #2530 that a non-admin user should not see any teams she/he is not part of.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3048, please help test on `develop` branch or https://try.gogs.io.

**Comment by mbugeia** [comment]
I confirm it's fixed on https://try.gogs.io.
