### ISSUE TITLE
Featurerequest: Enable more Creative Commons Licenses when creating new Repo

### ISSUE THREAD

**Issue by jgreth** [gogits/gogs#3032]
Hi,

as far as i can see i can only choose the "Creative Commons CC0 1.0 Universal" License when i create a new Repo. There should be a possibility to choose also other CC licenses.

Neither directly via the Dropdown nor via an extra Config option (e.g. in app.ini).

I would be glad if you could implement that.

**Comment by bkcsoft** [comment]
Licenses are stored in (and fetched from) `conf/license`. It is as easy as adding the license files to `conf/license`

If you feel that Gogs should include them per default then:
```
<copy files into conf/license>
$ make bindata
$ git add modules/bindata/bindata.go conf/license
$ git commit -m "moar cc license"
$ git push
```
:wink:

**Comment by jgreth** [comment]
Aaargh... i should open my eyes... 
Thanks for the hint - BUT im facing a new problem now.
I copied the plain textfiles (ANSI encoded like the others, no filetype suffix, filenames like "Creative Commons BY SA 4.0") to my conf/license dir but they did'nt show.
Then i saw the hint `$ make bindata` - so i did it, but resulted in that:
````
$ make bindata
go-bindata -o=modules/bindata/bindata.go -ignore="\\.DS_Store|README.md|TRANSLATORS" -pkg=bindata conf/...
/bin/sh: 1: go-bindata: not found
Makefile:42: recipe for target 'modules/bindata/bindata.go' failed
make: *** [modules/bindata/bindata.go] Error 127
```

What could be wrong there? do you have a clue?

**Comment by bkcsoft** [comment]
> `bin/sh: 1: go-bindata: not found`

Means that go-bindata isn't installed (not found)

Read the `build from source` docs on how to install it :smile:

**Comment by jgreth** [comment]
Mh... ok it was a missing path in my $PATH...
Now i have 
```
$ make bindata
go-bindata -o=modules/bindata/bindata.go -ignore="\\.DS_Store|README.md|TRANSLATORS" -pkg=bindata conf/...
```

No errors, but sadly also no new licenses

**Comment by Unknwon** [comment]
put under `custom/conf/license` requires you changes nothing but restart Gogs.
