### ISSUE TITLE
派生仓库在请求合并时500错误，求解决，谢谢

### ISSUE THREAD

**Issue by sugerdudu** [gogits/gogs#3035]
派生仓库在请求合并时报以下错误，求解决，谢谢
异常代码如下：

2016/04/29 16:45:11 [D] CSRF Token: VP9JOMioD2W_XrCSNGCuWtcZ9TI6MTQ2MTkxODMwMDE1MjQzMDQwMA==
2016/04/29 16:45:12 [T] PullRequest[0].testPatch (patchPath): E:\GitRes\content\sugerdudu\oainterfacesv2.git\pulls\4.patch
2016/04/29 16:45:12 [...routers/repo/pull.go:677 CompareAndPullRequestPost()] [E] NewPullRequest: **testPatch: UpdateLocalCopy: Pull: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git**

2016/04/29 16:45:12 [D] Template: status/500
[Macaron] 2016-04-29 16:45:12: Completed /sugerdudu/OAInterfacesV2/compare/release...sixi:release 500 Internal Server Error in 1.2187673s
[Macaron] 2016-04-29 16:45:51: Started GET /sugerdudu/ERP.git/info/refs?service=git-upload-pack for 192.168.3.216

**Comment by 502647092** [comment]
是的 我也遇到了这个问题 @Unknwon 希望解决一下

**Comment by Unknwon** [comment]
Hi, please follow the template:

https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by xingxing122** [comment]
I also encountered this problem  

2020/09/30 01:38:15 [ERROR] [...g/context/context.go:191 ServerError()] Merge: git merge --no-ff --no-commit [data/tmp/repos/284636393.git]: exit status 1 - 
2020/09/30 01:40:33 [ERROR] [...g/context/context.go:191 ServerError()] Merge: git merge --no-ff --no-commit [data/tmp/repos/910916864.git]: exit status 1 - 
2020/09/30 01:40:48 [ERROR] [...g/context/context.go:191 ServerError()] Merge: git merge --no-ff --no-commit [data/tmp/repos/780707494.git]: exit status 1 - 
2020/09/30 01:41:58 [ERROR] [...g/context/context.go:191 ServerError()] Merge: git merge --no-ff --no-commit [data/tmp/repos/576279750.git]: exit status 1 - 
2020/09/30 01:47:00 [ERROR] [...g/context/context.go:191 ServerError()] Merge: git merge --no-ff --no-commit [data/tmp/repos/256679763.git]: exit status 1 -
