### ISSUE TITLE
Docker gogs web/ssh does not restart after reboot

### ISSUE THREAD

**Issue by cryptax** [gogits/gogs#3039]
I am using a fresh install from docker gogs/gogs on Linux. Initially, gogs works fine. But when I reboot the host, the dockers do relaunch but do not serve the web interface :(

```
curl http://127.0.0.1:10080
curl: (7) Failed to connect to 127.0.0.1 port 10080: Connection refused
```

This is how I started gogs. Note the restart policy + I am publishing ports 10022 and 10080.
```
docker run --restart=always --name gogs-db -e MYSQL_DATABASE=gogs -e MYSQL_ROOT_PASSWORD=MYSECRET -d mysql:5.6.27
docker run --restart=always -d --name gogs-cuckoo --link gogs-db:mysql --publish 10022:22 --publish 10080:3000 -v /var/gogs:/data gogs/gogs
```

I continued the installation without any problems, and then managed to log on to gogs and work with it without any problem. The web interface is expected to work on http://MYIP:10080, and that worked fine, and I created repositories etc.

However, when I reboot the host, the 2 docker containers do relaunch thanks to the restart policy

```
axelle@cuckoo:~$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
05d957d48fd6        gogs/gogs            "docker/start.sh /bin"   2 hours ago         Up 2 hours          0.0.0.0:10022->22/tcp, 0.0.0.0:10080->3000/tcp   gogs-cuckoo
aa9ee4739825        mysql:5.6.27         "/entrypoint.sh mysql"   6 hours ago         Up 2 hours          3306/tcp                                                 gogs-db
```

but they do not serve the HTTP (nor SSH).

```
$ curl http://127.0.0.1:10080
curl: (7) Failed to connect to 127.0.0.1 port 10080: Connection refused
```

Though gogs seems to be listening on 10080 correctly:

``
$ docker logs gogs-cuckoo
2016/04/29 12:58:18 [T] Custom path: /data/gogs
2016/04/29 12:58:18 [T] Log path: /app/gogs/log
2016/04/29 12:58:18 [I] Gogs: Go Git Service 0.9.22.0425
2016/04/29 12:58:18 [I] Log Mode: File(Info)
2016/04/29 12:58:18 [I] Cache Service Enabled
2016/04/29 12:58:18 [I] Session Service Enabled
2016/04/29 12:58:18 [I] Git Version: 2.6.6
2016/04/29 12:58:23 [I] SQLite3 Supported
2016/04/29 12:58:23 [I] Run Mode: Production
2016/04/29 12:58:23 [T] Doing: CheckRepoStats
2016/04/29 12:58:23 [I] Listen: http://0.0.0.0:10080
2016/04/29 13:58:23 [T] Doing: MirrorUpdate
2016/04/29 14:58:23 [T] Doing: MirrorUpdate
``

**Comment by bkcsoft** [comment]
There's your erfor, it should listen on 3000, not 10080

**Comment by bkcsoft** [comment]
@cryptax was this resolved?

**Comment by cryptax** [comment]
@bkcsoft No, that does not solve it.

The curl http://127.0.0.1:10080 I am trying is not inside the docker, but outside. So, it should not be port 3000, but port 10080. Indeed, the docker is publishing port 3000 to 10080 in my configuration (see --publish 10080:3000).

Nevertheless, I tried it, and I confirm it does not work:

```
$ curl http://127.0.0.1:3000
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
axelle@cuckoo:~$ curl http://127.0.0.1:10080
curl: (56) Recv failure: Connection reset by peer
```

And the port 10080 is shown as listening:
```
$ netstat -tulpn | grep 10080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::10080                :::*                    LISTEN      -      
```

I currently have no particular error in the docker logs:

```
2016/04/29 15:14:08 [I] Listen: http://0.0.0.0:10080
...
2016/05/02 06:14:08 [T] Doing: MirrorUpdate
2016/05/02 07:14:08 [T] Doing: MirrorUpdate
2016/05/02 08:14:08 [T] Doing: MirrorUpdate
```

There is something strange, though, when I get in the container, it seems the web is listening on 10080. I would have expected 3000.

```
axelle@cuckoo:~$ docker exec -it gogs-cuckoo bash
bash-4.3# netstat -tulpn                                                              
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      32/socat
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      33/sshd
tcp        0      0 :::10080                :::*                    LISTEN      -
tcp        0      0 :::22                   :::*                    LISTEN      33/sshd
```

**Comment by bkcsoft** [comment]
As you can see here:

> 2016/04/29 15:14:08 [I] Listen: http://0.0.0.0:10080

Gogs is listening on 10080 not 3000 as it should :smile:

**Comment by cryptax** [comment]
@bkcsoft well, no the gogs container does not respond neither on 3000 nor on 10080.

```
$ curl http://127.0.0.1:3000
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
$ curl http://127.0.0.1:10080
curl: (56) Recv failure: Connection reset by peer
```

**Comment by cryptax** [comment]
Ok - looks like _I misread the install guidelines_.
**Everything is fine**.
For those having the same issue as me:

- **domain**: ensure that is the IP address of your docker host
- **SSH port**: that is the forwarded ssh port. So if you forward 22 to 10022, it's 10022.
- **HTTP port**: my error, here, you must enter the HTTP in the container. So **it's 3000**. _Even if you forward it to 10080 ;)_
- **Application URL**: this is a combination of **domain + forwarded HTTP port** (I got this one wrong too). So, if you're forwarding 3000 to 10080, then it's http://domain:10080.

The issue can be closed, thanks!
