### ISSUE TITLE
Licence Variables + New Installs

### ISSUE THREAD

**Issue by richardskumat** [gogits/gogs#3040]
For bug reports, please give the relevant info:

- Git version: 0.9.22.0425
- Operating system: Linux
- Database:
  - [Y] PostgreSQL
  - [Y] MySQL
  - [Y] Mariadb
- Can you reproduce the bug at http://try.gogs.io:
  - [Y] Not relevant

## Description

Hi, new installs seems to have a few minor bugs on Gogs.

I've got the following versions on different servers:

0.9.1.0306 - Debian Wheezy Openvz Container

0.9.15.0323 - Raspbian 7

0.9.22.0425 - Ubuntu 14.04 LTS Xen ec2 vps

Regardless of the OS, it seems licences files don't have the year and owner replaced with "actual data".

It's a minor issue anyway. Example:

http://i.imgur.com/tfQLKH7.png

Seen this issue at least on MIT and BSD 3 and 4 clause licences.

They've all been installed from source with go 1.6.

**Comment by richardskumat** [comment]
For bug reports, please give the relevant info:

- Git version: 0.9.22.0425
- Operating system: Linux
- Database:
  - [Y] PostgreSQL
  - [Y] MySQL
  - [Y] Mariadb
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [Y] Not relevant


## Description

Also on 0.9.22.0425, it seems after you supply the database credentials, admin user details and modify the other settings, Gogs redirects to the login page regardless if you created the admin user. Which results in an initial 404 error.

It's a minor one-time issue only.

**Comment by bkcsoft** [comment]
These are two unrelated issues, please open a separate issue for the other one.

You're supposed to fill in the year and owner yourself, as with any licenses

**Comment by richardskumat** [comment]
@bkcsoft 

Thank you, I didn't know the intention behind the placeholders. Opened a new issue, so I'm closing this then.
