### ISSUE TITLE
New installs on version 0.9.22.0425 redirect to https://IP or hostname/install/user/login with admin account created resulting in a one-time 404

### ISSUE THREAD

**Issue by richardskumat** [gogits/gogs#3041]
For bug reports, please give the relevant info:

- Git version: 0.9.22.0425
- Operating system: Linux
- Database:
  - [Y] PostgreSQL
  - [Y] MySQL
  - [Y] Mariadb
- Can you reproduce the bug at http://try.gogs.io:
  - [Y] Not relevant

## Description

On 0.9.22.0425, it seems after you supply the database credentials, admin user details and modify the other settings, Gogs redirects to the login page regardless if you created the admin user. Which results in an initial 404 error.

This occurs after building from source with go 1.6 and 1.6.2 as well. Never tried the binaries or docker. Nginx is used to reverse-proxy gogs with a self-signed ssl certificate(not sure if this matters).

URL being redirected to is:

https://IP or hostname/install/user/login

It's a minor one-time issue only.

**Comment by Unknwon** [comment]
Hi, actually I don't get this part:

> Gogs redirects to the login page regardless if you created the admin user. Which results in an initial 404 error.

Can you 100% reproduce this and what're the URLs?

**Comment by richardskumat** [comment]
Of course.

All my installs with https://github.com/richardskumat/gogsi have been having the same one time issue regardless of being installed on Centos/RHEL/Debian/Ubuntu/Fedora.

I don't know if it has something to do with the custom app.ini file or not?

Anyway, a few screenshots after a new test:

https://s33.postimg.org/5ls5uyk19/Screenshot_290616_22_15_49.png

https://s33.postimg.org/d4fwhc0rx/Screenshot_290616_22_16_10.png

https://s33.postimg.org/gqlptz759/Screenshot_290616_22_17_12.png

https://s33.postimg.org/6s0r7hxpp/Screenshot_290616_22_17_29.png

Custom app.ini:

https://paste.ee/r/ZbluC

I took the server offline already.

**Comment by richardskumat** [comment]
It looks it also happens when not creating an admin during the installation page:

https://s33.postimg.org/juzlidyi5/Screenshot_290616_22_53_56.png

https://s33.postimg.org/i4gkgwgz1/Screenshot_290616_22_54_08.png

https://s33.postimg.org/4otjrg8h9/Screenshot_290616_22_54_28.png

**Comment by Unknwon** [comment]
One question first: you're visiting using IP `192.x...`, why do you still have app URL `localhost:3000`?

**Comment by Unknwon** [comment]
For the record, I installed my Gogs again and it redirects to login page correctly.

**Comment by richardskumat** [comment]
> One question first: you're visiting using IP 192.x..., why do you still have app URL localhost:3000?

Localhost:3000 is for binding Gogs to listen on localhost, a choice I made for myself when installing nginx in front of it as reverse proxy. This way it doesn't accept outside connections on port 3000.

> For the record, I installed my Gogs again and it redirects to login page correctly.

That's I guess how it works, but I think nginx misinterprets the request somehow after you click "Install Gogs" on the install page.

From the 404 request URL, it can be seen Gogs redirects to the login page, but nginx somehow makes it http://ipaddress/install/user/login which leads to a one time 404.

I'll close this as I suspect it's either nginx or my settings and not Gogs.

**Comment by Unknwon** [comment]
Yeah.... your server setting looks unusual to me..
