### ISSUE TITLE
DEPRECATED Action signature erorr

### ISSUE THREAD

**Issue by james2doyle** [gogits/gogs#3045]
- Gogs version (or commit ref): 0.9.22.0425
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.4 LTS "3.13.0-24-generic #46-Ubuntu 14.0 SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux"
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (**version mismatch**)
- Log gist:

```
[mysql] 2016/05/01 15:39:30 packets.go:33: unexpected EOF
[mysql] 2016/05/01 15:39:30 packets.go:124: write tcp 127.0.0.1:3306: broken pipe
[mysql] 2016/05/01 15:39:30 packets.go:33: unexpected EOF
[mysql] 2016/05/01 15:39:30 packets.go:124: write tcp 127.0.0.1:3306: broken pipe
```

## Description

Updated my Gogs installation this morning. Went to push, and got the following error:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

The push was still successful, but this error was displayed during the push.

**Comment by adamkiss** [comment]
That is deprecation notice added in codegangsta/cli 1.15.0 — [release changelog](https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#1150---2016-04-30)

**Comment by bkcsoft** [comment]
Gogs has codegangsta/cli locked at https://github.com/codegangsta/cli/commit/aca5b047ed14d17224157c3434ea93bf6cdaadee (which is pre 1.14.0) via glide, if an upgrade is required or requested this will be fixed :wink:

**Comment by adamkiss** [comment]
@bkcsoft Maybe binary? Installing from source installs 1.15.0

**Comment by prakashsinhab** [comment]
Steps to correct this please!

Facing the same with todo go microservice by ben

**Comment by khera** [comment]
I just did a fresh build using "go get/go build" on FreeBSD 10, and my first repo push to it gave me the same above error. The push seems to have succeeded, though. I cannot see anything missing.

**Comment by james2doyle** [comment]
Yeah this error seems purely information and does not impact the state or code in a push.

**Comment by bkcsoft** [comment]
Glide is a vendoring tool (dependency manager, think npm, bower, pip). `glide install` will put all dependencies in `./vendor`. For golang 1.6 this works automagically, for 1.5 theres a env-var that has to be set (google is your friend)

**Comment by belak** [comment]
It doesn't look like the dockerfile is actually using glide. This is causing anyone who uses the dockerfile and runs :latest to get these warnings.

**Comment by james2doyle** [comment]
I don't run a docker image for my installation of gogs. I got this error after an upgrade using `go get -u all` and then doing a build.

**Comment by rralf** [comment]
Any updates on this or quick fixes?
I'm facing the same issue on 0.9.25.0506 on Debian Jessie / gogs installed via .deb package.

**Comment by qbit** [comment]
The [official documentation](https://gogs.io/docs/installation/install_from_source#build-from-develop-branch) doesn't make mention of using glide. Perhaps it is out of date?

**Comment by jloic** [comment]
Same here on ubuntu 14.04

**Comment by belak** [comment]
Yeah, it looks like the documentation is out of date. If you build using glide, the error goes away.

**Comment by rralf** [comment]
Well, building is not an option if you install gogs using the binary packages. I don't want to compile gogs on my server :-)

Anyway - according to many replies on this thread this one really seems to be a bug of gogs, at least in the binary distribution of gogs. Is there some more official way to report this issue?

This one is already 11d old without any substantial progress.

**Comment by james2doyle** [comment]
I got this error after building using `go get`. Not sure about anyone else.

**Comment by jakimfett** [comment]
Getting the same error on Debian 8.3 after following the [instructions to install the package for Gogs](https://packager.io/gh/pkgr/gogs/install?bid=439#debian-8-gogs).

**Comment by Unknwon** [comment]
Problem should be fixed in `develop` branch.

**Comment by qbit** [comment]
Seems to have created some new issues: `2016/05/12 22:38:39 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: unable to open database file`

Perhaps the docs need to be updated? is there a new process that uses glide?

**Comment by de-live-gdev** [comment]
Resolved the issue on my instance

**Comment by khromov** [comment]
+1 same issue, looking forward to a permanent fix!

**Comment by FloSchramm** [comment]
Same Issue here on Ubuntu.

**Comment by chaorunrun** [comment]
Same issue here. I have gogs 0.9.13-1462579758.3c0c7a9.wheezy running. When the fix is going to be released?

**Comment by de-live-gdev** [comment]
@khromov  @FloSchramm @chaorunrun Please be so kind and scroll up. There is already a fix in develop branch. If your gogs is below version 0.9.27.0512 you won't have that fix included.

**Comment by Unknwon** [comment]
Fix has been pushed to `master`, closing.

**Comment by mbi** [comment]
@Unknwon 👍 thank you!

**Comment by Marko-M** [comment]
Thanks @Unknwon.

**Comment by james2doyle** [comment]
👍
