### ISSUE TITLE
Custom Release Files

### ISSUE THREAD

**Issue by ENDev15** [gogits/gogs#3047]
I am not sure if this is already available, but here's my question.

Can I create custom release files as in GitHub? 

Such as a compiled Debian file or something of that sort. Or an edited ZIP file, with another directory within the ZIP before getting to the actual files and folders.

**Comment by bkcsoft** [comment]
Not yet, there's already an issue for that IIRC

**Comment by bkcsoft** [comment]
There was #1614 AND #698 so I'm closing this as a duplicate, feel free to re-open if you feel that they are separate issues :smile:
