### ISSUE TITLE
仓库A派生出仓库B，如果后期A有更新，怎么同步到B？

### ISSUE THREAD

**Issue by renyanwei** [gogits/gogs#3051]
经过试验和使用，发现仓库B的更新可以通过合并请求同步到A上，但是反向操作貌似不行， 还是我没有掌握正确的姿势，请指教~

**Comment by 502647092** [comment]
拉取A到本地然后推送到B

**Comment by Unknwon** [comment]
@502647092 has posted the correct way.

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
