### ISSUE TITLE
Pagination not working properly for issues in some cases

### ISSUE THREAD

**Issue by cjeanneret** [gogits/gogs#3054]
- Gogs version (or commit ref): 0.9.13.0318

Hello,

We currently have a webhook on our gogs instance that check code for unused classes/files on each push on a specific branch.
So far, so good, that works as expected.

The called script pushes new issues on gogs itself, specifying the class name, file path and so on.
So far, so good, still working.

The "small" issue is that many issues are created at the same time. This leads to a nice issue on the «issue display page», where we're in fact unable to sort the issues by age (many are created at the same minute). It also appears the pagination goes amok, as page 2 displays the 4 last issues of page one, then 6 "new" issues that weren't displayed on the later page, and this is for every pagination.

I'm not sure if this has to do with the fact we create many issues at the same time on the same repository, but I suspect it plays a role as the issue IDs aren't following on the page (with default order)…
It might be useful to order the issues with two keys:
- creation datetime
- issue id

That would sort out the problem in a smart way, and shouldn't really impact the other ordering stuff in a negative way:
as the ID seems to be a simple increment, the older issues will get a smaller ID while the newer a bigger one.

Cheers,

C.

**Comment by Unknwon** [comment]
No, it's not ever possible for a human create two issues in the same nano second.

Please test and verify your situation on https://try.gogs.io or latest `master` branch.
