### ISSUE TITLE
Do app.ini keys have to be unique?

### ISSUE THREAD

**Issue by oleersoy** [gogits/gogs#3055]
If they do then there is an issue in the app.ini cheatsheet documentation.

http://stackoverflow.com/questions/37005792/gogs-turning-off-cron-jobs

**Comment by bkcsoft** [comment]
They have to be unique in their scope
```
[scope1]
ENABLED = True
DISABLED = False

 [scope2]
ENABLED = False # Works
DISABLED = True # Works
DISABLED = False # Breaks...
```
