### ISSUE TITLE
Search Repositories API results are always capped to 20

### ISSUE THREAD

**Issue by neutrinog** [gogits/gogs#3058]
- Gogs version (or commit ref): 0.9.23.0426 (We've made some modifications as well for git.door43.org)
- Git version: 1.8.3.1
- Operating system: CentOS Linux release 7.2.1511
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL): `curl -I "https://try.gogs.io/api/v1/repos/search?q=a&limit=200"`
  - [ ] No
  - [ ] Not relevant
- Log gist: 

## Description

If you run the example command above you always get 20 results back. The limit works for anything under 20 results but once you hit 20 it is capped.

**Comment by Unknwon** [comment]
I guess it is not working at all... https://github.com/gogits/gogs/blob/6f6b37f148428eb83cbefdf84253ab7f412e2537/models/issue.go#L506

**Comment by Unknwon** [comment]
You're now able to test on `develop` branch or https://try.gogs.io/ . To change default max response number: https://github.com/gogits/gogs/commit/4b25bdfbc45479d64e3ffb04abbd08672ccc47fb#diff-c4893a32340ee2cee87e664d67f8abf3R350
