### ISSUE TITLE
Search Repositories API does not provide link header for pagination

### ISSUE THREAD

**Issue by neutrinog** [gogits/gogs#3059]
- Gogs version (or commit ref): 0.9.23.0426 (We've made some modifications as well for git.door43.org)
- Git version: 1.8.3.1
- Operating system: CentOS Linux release 7.2.1511
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL): `curl -I "https://try.gogs.io/api/v1/repos/search?q=a&limit=200"`
  - [ ] No
  - [ ] Not relevant
- Log gist: **N/A**

## Description

First of all there's another related issue #3058 where the limit is always capped to 20. 

In github a link header is provided in long results to allow pagination. See example below

![20160504-100554](https://cloud.githubusercontent.com/assets/166412/15022292/d2edc866-11df-11e6-9918-ee21ad1a49e9.png)

However no such link is provided in gogs.

**Comment by Unknwon** [comment]
You're now able to test on develop branch or https://try.gogs.io/ .
