### ISSUE TITLE
gogs web doesn't work

### ISSUE THREAD

**Issue by bhua** [gogits/gogs#3061]
- Gogs version (or commit ref): linux amd64
- Git version: 1.9.1
- Operating system: ubuntu 14.04
- Database:mysql
- Can you reproduce the bug at http://try.gogs.io:no
## Description
i installed by step following the docs, and when i run gogs with command `./gogs web` in its folder, it tells me the error  `-bash: ./gogs: No such file or directory`,  so how can i fix this?
![screen shot 2016-05-05 at 14 08 40](https://cloud.githubusercontent.com/assets/535675/15037146/f1a5e84c-12ca-11e6-8fb1-d041ed33a606.png)

**Comment by joubertredrat** [comment]
Hi @bhua 

This is very strange, probably is problem on your bash, but tries this command on gogs folder
```
root@jc:/var/gogs# $(pwd)/gogs web
```
With this command you will run gogs with absolute path to test if works.

**Comment by bhua** [comment]
@joubertredrat can't run, the same error `-bash: /var/gogs/gogs: No such file or directory`

**Comment by rielzzapps** [comment]
You probably have downloaded a 32bit version without 32bit support, or vice versa.
