### ISSUE TITLE
upgrade gogs_0.8.43 to gogs_0.9.13

### ISSUE THREAD

**Issue by dwercn** [gogits/gogs#3064]
出现“502 Bad Gateway”
错误日志显示“2016/05/05 23:45:18 [...ts/gogs/cmd/serve.go:175 runServ()] [F] Failed to get repository owner (     pft): Error 1054: Unknown column 'created_unix' in 'field list' ”  @Unknwon

**Comment by dwercn** [comment]
回退到0.8.43去就又正常了，不知道是不是0.8到0.9不能升级?

**Comment by dwercn** [comment]
gogs.log 里面的错误日志
    2016/05/05 23:50:27 ^[[1;36m[T] Table [comment]: offset: 0, beans: 0^[[0m
134 2016/05/05 23:50:27 ^[[1;32m[I] Converting table: issue^[[0m
135 2016/05/05 23:50:30 ^[[1;36m[T] Table [issue]: offset: 0, beans: 0^[[0m
136 2016/05/05 23:50:30 ^[[1;32m[I] Converting table: milestone^[[0m
137 2016/05/05 23:50:33 ^[[1;36m[T] Table [milestone]: offset: 0, beans: 0^[[0m
138 2016/05/05 23:50:33 ^[[1;32m[I] Converting table: attachment^[[0m
139 2016/05/05 23:50:35 ^[[1;36m[T] Table [attachment]: offset: 0, beans: 0^[[0m
140 2016/05/05 23:50:35 ^[[1;32m[I] Converting table: login_source^[[0m
141 2016/05/05 23:50:38 ^[[1;36m[T] Table [login_source]: offset: 0, beans: 0^[[0m
142 2016/05/05 23:50:38 ^[[1;32m[I] Converting table: pull_request^[[0m
143 2016/05/05 23:50:39 ^[[1;36m[T] Table [pull_request]: offset: 0, beans: 0^[[0m
144 2016/05/05 23:50:39 ^[[1;32m[I] Converting table: release^[[0m
145 2016/05/05 23:50:40 ^[[1;36m[T] Table [release]: offset: 0, beans: 1^[[0m
146 2016/05/05 23:50:40 ^[[1;36m[T] Table [release]: offset: 100, beans: 0^[[0m
147 2016/05/05 23:50:40 ^[[1;32m[I] Converting table: repository^[[0m
148 2016/05/05 23:50:40 [I] Converting table: repository

**Comment by dwercn** [comment]
@Unknwon  麻烦给个看下哈。

**Comment by Unknwon** [comment]
Hi,

From https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md:

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please post details about how you upgrade on https://discuss.gogs.io/c/getting-help/getting-help-chinese
