### ISSUE TITLE
AdminCreateOrg API ignores FullName property

### ISSUE THREAD

**Issue by rgl** [gogits/gogs#3066]
- Gogs version (or commit ref): 
 - 0.9.22.0425
 - 7049cb9d975505a6f1fa3fad809dd92c1078360f
- Database:
  - [x] PostgreSQL
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No... because I don't known how to create a new organization in my account with `client.AdminCreateOrg`...
  - [ ] Not relevant

## Description

The `FullName` property from bellow seems to be ignored by the gogs API endpoint. It seem to end up with the same value as the `UserName`  property.

```go
	org, err := client.AdminCreateOrg(
		"gogs",
		gogs.CreateOrgOption{
			UserName:    "acmeOrganization",
			FullName:    "acmeOrganization Full Name", // XXX this is ignored.
			Description: "Description",
			Website:     "http://acme.example.com",
			Location:    "Lisbon, Portugal",
		})
```

**Comment by bkcsoft** [comment]
@Unknwon this requires fiddling with go-gogs-client right?

**Comment by Unknwon** [comment]
@bkcsoft Yes, I think so

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
