### ISSUE TITLE
[SECURITY ISSUE] world-readable repos and database

### ISSUE THREAD

**Issue by majewsky** [gogits/gogs#3070]
As of Gogs 0.9.0, all repositories and the SQLite database are world-readable, so every rogue user account can access all private data and secrets.

```
$ stat /srv/gogs
  File: '/srv/gogs'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 1310725     Links: 7
Access: (0755/drwxr-xr-x)  Uid: (  995/    gogs)   Gid: (  994/    gogs)
Access: 2016-05-06 17:51:59.043553378 +0200
Modify: 2016-02-27 00:46:14.708055495 +0100
Change: 2016-03-07 12:47:12.839604905 +0100
 Birth: -

$ stat /srv/gogs/sqlite
  File: '/srv/gogs/sqlite'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 1310731     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  995/    gogs)   Gid: (  994/    gogs)
Access: 2016-05-06 17:52:32.031104912 +0200
Modify: 2016-05-06 17:50:12.490695465 +0200
Change: 2016-05-06 17:50:12.490695465 +0200
 Birth: -

$ stat /srv/gogs/sqlite/gogs.db
  File: '/srv/gogs/sqlite/gogs.db'
  Size: 243712    	Blocks: 488        IO Block: 4096   regular file
Device: 802h/2050d	Inode: 1310733     Links: 1
Access: (0644/-rw-r--r--)  Uid: (  995/    gogs)   Gid: (  994/    gogs)
Access: 2016-05-06 17:50:12.614032109 +0200
Modify: 2016-05-06 17:50:12.277356406 +0200
Change: 2016-05-06 17:50:12.277356406 +0200
 Birth: -

$ stat /srv/gogs/sqlite/gogs.db
  File: '/srv/gogs/repo'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 1310734     Links: 8
Access: (0755/drwxr-xr-x)  Uid: (  995/    gogs)   Gid: (  994/    gogs)
Access: 2016-05-06 18:02:03.443103650 +0200
Modify: 2016-02-29 22:41:32.844253112 +0100
Change: 2016-03-07 12:47:12.839604905 +0100
 Birth: -

$ stat /srv/gogs/repo/stefan
  File: '/srv/gogs/repo/stefan'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 1310736     Links: 16
Access: (0755/drwxr-xr-x)  Uid: (  995/    gogs)   Gid: (  994/    gogs)
Access: 2016-05-06 18:02:15.910104892 +0200
Modify: 2016-05-06 17:50:12.050683655 +0200
Change: 2016-05-06 17:50:12.050683655 +0200
 Birth: -

$ stat /srv/gogs/repo/stefan/somerepo.git
  File: '/srv/gogs/repo/stefan/somerepo.git'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 131707      Links: 7
Access: (0755/drwxr-xr-x)  Uid: (  995/    gogs)   Gid: (  994/    gogs)
Access: 2016-05-06 18:02:15.910104892 +0200
Modify: 2016-02-28 20:55:49.103654898 +0100
Change: 2016-03-07 12:47:12.809604045 +0100
 Birth: -
```

**Comment by Lafriks** [comment]
Does not seem to be big problem. You should just set /srv/gogs/repo directory to 750 and all repositories will not be world readable as parent directory is not. I don't think gogs should mess with parent directory rights, that's administrators responsibility.

**Comment by majewsky** [comment]
Your comment proved that the task clearly isn't that easy. You cannot "just" set `/srv/gogs/repo` to 0750. That will still leave the SQLite database vulnerable (and also the `app.ini`, but I'm not sure if that file contains any credentials).

It is every program's responsibility to ensure proper permissions on the files that it creates. As a minimal solution, I would want to see the following provisions:

1. set (at least on creation) proper permissions (i.e. 0750) on
  - all repos created by Gogs, and on
  -  the SQLite database (if one is used)
2. If app.ini contains credentials, refuse to start when app.ini is world-readable.

**Comment by horazont** [comment]
@Lafriks It is not about the parent directory. The sqlite database is managed by gogs (in the sense that it is neither filled nor necessarily created by the administrator) and it may contain private information which must be protected from other accounts and only needs to be read by gogs itself. Strict permissions don’t do any harm here.

Same goes for the app.ini, although here it is the administrators responsibility to ensure that the permissions are sane. Gogs must enforce this by not starting when the permissions are not sane (i.e. at least if it is world readable).

**Comment by bkcsoft** [comment]
Relates to #2950, though not exactly the same so I'm keeping this open (thought please read #2950 as it has already discussed possible solutions in length...).
@strk Might be an idea to merge the issues?

**Comment by strk** [comment]
Sounds about the same issue to me.

**Comment by Unknwon** [comment]
Feels the same issue to me as well... same argument as https://github.com/gogits/gogs/issues/2950
