### ISSUE TITLE
Visibility checkbox behaviour is confusing

### ISSUE THREAD

**Issue by megaknoc** [gogits/gogs#3072]
Hello,

I found the Visibility checkbox when creating a new repository in the web-interface a bit confusing.

It is presented in this form:
Visibility [ ] This repository is Private

And I thought the string on the rightside of the checkbox (this --> [  ]) will be a verbose description of the visibility checkbox and would change  when clicked on the visibility checkbox to something like "This repository is Public"

Could be combined with the following related feature request which wants a "Protected" visibility option by providing a dropdown list for all three options instead of one ore more checkboxes.
(https://github.com/gogits/gogs/issues/2308)

cogs version is: 0.9.22.0425

**Comment by Unknwon** [comment]
Please merge discussion to https://github.com/gogits/gogs/issues/2308
