### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by ohko** [gogits/gogs#3073]
今天我Mirror了git的项目：https://git.kernel.org/pub/scm/git/git.git，我的测试服务CPU双核(Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz)不快，内存足够8GB（剩余7G左右未用）。发现以下问题：

1. 在“代码”栏目中，文件过多性能下降，要等好23秒：当前版本: 0.9.13.0318 页面: 23798ms 模板: 220ms
2. 在“版本发布”栏目，版本有600多个，要等375秒：当前版本: 0.9.13.0318 页面: 375041ms 模板: 177ms
3. “提交历史”栏目很快，4万过个提交：当前版本: 0.9.13.0318 页面: 3274ms 模板: 64ms

没看源代码，分析建议一下几点：
1. “代码”和“版本发布”栏目会用git读取原始信息，是不是可以少读点，这样性能就提高了。
2. “版本发布”栏目应该分页，否则版本多了，页面卡死，CPU疯狂。
3. 页面先渲染几本内容，提交信息或其它信息使用异步读取，因为有时可能并不关心提交信息。但是再离开页面时，未执行完的异步请求要终止是个问题。

**Comment by Unknwon** [comment]
Thanks your advice, but please post to https://discuss.gogs.io/ :)
