### ISSUE TITLE
The From: field is ignored when e-mail sent (Exchange 2013) - alias not working?

### ISSUE THREAD

**Issue by rbukovansky** [gogits/gogs#3074]
- Gogs version (or commit ref): latest develop branch synced on May 08
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

I have this in my custom app.ini:

; Mail from address, RFC 5322. This can be just an email address, or the `"Name" <email@example.com>` format
FROM            = `"Gogs My Company" <no-reply@company.com>`
; Mailer user name and password
USER            = support@company.com
PASSWD          = <password>

but testing e-mail comes from support@company.com. The Gogs can't work with e-mail aliases? Or it is some issue with Gogs and Exchange 2013, which is used?

Thanks.

**Comment by bkcsoft** [comment]
http://www.msoutlook.info/question/send-mail-from-additional-exchange-address-or-alias

> Unfortunately, there is no native way to choose which one of your
Exchange mailbox addresses (or aliases) to use when sending out an email.
The outgoing address that will be used will be the address that has been
set as the “Reply address” for your user account by your Exchange
administrator.

**Comment by rbukovansky** [comment]
Hm... We are using osTicket http://osticket.org for customer support and I'm able to do exactly that (1 mailbox, 3 aliases, and e-mails are sent with correct From: as they should).

**Comment by Unknwon** [comment]
What about non-test emails?

**Comment by Unknwon** [comment]
ping

**Comment by rbukovansky** [comment]
Sorry, I have missed this... Which action will force Gogs to send e-mail? Thanks.

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/blob/master/conf/app.ini#L141 and will send confirmation email when register.

**Comment by rbukovansky** [comment]
Well, I will open the registrations for the testing then... Thx.

**Comment by rbukovansky** [comment]
I tried to register new user as system admin, sent the e-mail about the registration and voila... It came with correct From: e-mail address. Alright then, this issue is officially closed.

Thanks.
