### ISSUE TITLE
DEPRECATED Action signature

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#3075]
- Gogs version (or commit ref): 0.9.25.0506
- Git version: 2.1.4
- Operating system: Debian Jessie 8.3
- Database: 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When pushing: 
```
remote: DEPRECATED Action signature.  Must be 'cli.ActionFunc'.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

**Comment by rralf** [comment]
Confirmed. Same configuration and error here. Maybe Duplicate of issue #3045 ?

Though it seems, that this is 'only' an annoying warning.

**Comment by drsect0r** [comment]
@rralf My search-fu abandoned me when I was searching. Same bug. I will close this one.

**Comment by belak** [comment]
If you build using glide, the error goes away.
