### ISSUE TITLE
500 error when creating a release with an invalid tag name

### ISSUE THREAD

**Issue by beta** [gogits/gogs#3076]
- Gogs version: 0.9.13.0318
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database: MySQL (MariaDB)
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/beta/test-repo/releases/new
  - [ ] No
  - [ ] Not relevant
- Log:
    
    ```
    2016/05/09 12:02:14 [...ters/repo/release.go:195 NewReleasePost()] [E] CreateRelease: exit status 128 - fatal: '1.0 alpha' is not a valid tag name.
    ```

## Description

When creating a release and input an invalid tag name (e.g., `1.0 alpha`), a 500 server error will be shown. There should be a guide to what a valid tag name is and also a gentle error info after failing.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by beta** [comment]
Sorry for seeing your reply this late. I've tested on [https://try.gogs.io](https://try.gogs.io) and found the problem solved.

However there might be another thing that could be taken into consideration. When an invalid tag name is found, the branch dropdown menu is also marked red, which is a little bit puzzling.

<img width="421" alt="screen shot 2016-07-25 at 18 08 49" src="https://cloud.githubusercontent.com/assets/5000910/17098022/d8fa13b0-5292-11e6-859e-cdda01459b2d.png">

**Comment by Unknwon** [comment]
@beta you're right, but conceptually they belong to same UI element so it is very hard to split them.
