### ISSUE TITLE
wget a release from a private repo no longer works

### ISSUE THREAD

**Issue by lavvy** [gogits/gogs#3081]
hello it seems that getting a specific release package from a private repo as added in this issue #842  no longer work or its broken. please can it be re introduced . it is very important in versioning our installations.
it used to be this format
 wget {HOST}/api/v1/repos/{username}/{reponame}/archive/{ref}.{format}?token={token}     
 as stated by @Unknwon .in that issue #842  please could it return or has the format changed ?

**Comment by Unknwon** [comment]
Hi, just tested on https://try.gogs.io and it is working. Please follow https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md for report.

**Comment by lavvy** [comment]
please what am i doing wrong . i get a 404 error
![screenshot from 2016-05-12 00 13 22](https://cloud.githubusercontent.com/assets/7013091/15204054/7855755e-17d7-11e6-9a0f-6bb8d84a9b8a.png)

**Comment by Unknwon** [comment]
I do not think you use using the same URL in your original post.

**Comment by lavvy** [comment]
i keep getting a 404 . what am i doing wrong
![screenshot from 2016-05-12 00 23 47](https://cloud.githubusercontent.com/assets/7013091/15204119/07cba1a4-17d8-11e6-8fce-8089b6d41525.png)

**Comment by Unknwon** [comment]
>it used to be this format
wget {HOST}/api/v1/repos/{username}/{reponame}/archive/{ref}.{format}?token={token}

**Comment by lavvy** [comment]
oh ok , i am missing the /api/v1/repos in the url

**Comment by Unknwon** [comment]
:joy:
