### ISSUE TITLE
custom conf file doesn't work

### ISSUE THREAD

**Issue by grunmin** [gogits/gogs#3082]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.25.0506
- Git version: 1.7.1
- Operating system:CentOS 6.2
- Database: MySQL
- Can you reproduce the bug at http://try.gogs.io:
## Description

...

遵照官方文档说明，在/opt/gogs/custom/conf/下创建app.ini文件修改自定义配置，重启了gogs服务，这些配置没有生效。查看issue，好像已经改了读取自定义配置文件的方式是吗？改成/etc/gogs/conf/app.ini？至少我修改这里的文件是生效的，修改/etc/gogs/custom/conf/app.ini也不行。

**Comment by Unknwon** [comment]
There is no fixed place to put your custom app.ini, it is based on your installation.

It is defaulted to `path/to/gogs/custom/conf/app.ini`.

**Comment by grunmin** [comment]
用yum安装的，一开始纠结了很久，直到看到你回复其他人包管理器安装的自定义配置文件路径是/etc/gogs/conf/appi.ini

**Comment by kinglionsoft** [comment]
I installed gogs with yum too. And [https://gogs.io/docs/advanced/configuration_cheat_sheet ](https://gogs.io/docs/advanced/configuration_cheat_sheet ) confuses me.

**Comment by grunmin** [comment]
建议文档里面写下yum安装后的配置文件路径 @Unknwon
