### ISSUE TITLE
Health check timeout should be configurable

### ISSUE THREAD

**Issue by wolkenschieber** [gogits/gogs#3083]
I'm migrating a subversion repository to git. Gogs will serve as version control frontend end. 
The repository contains about 100'000 revisions and is about 3GB in data.

With this size a git garbage collections takes about 2 minutes an the hosting machine.

So the gogs scheduled health checks also take longer than the fixed timeout. In consequence it reports failed health checks:
`[W] Fail to health check repository (repo-path): execution is timeout [duration: 1m0s]`

The timeout of these cron jobs, respective the health check should be configurable.

- Gogs version (or commit ref):  0.9.13.0318
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database: SQLite
- Can you reproduce the bug at http://try.gogs.io: Not relevant

**Comment by bkcsoft** [comment]
from `conf/app.ini`:
```
; Repository health check
[cron.repo_health_check]
SCHEDULE = @every 24h
TIMEOUT = 60s
```

**Comment by wolkenschieber** [comment]
Thanks a lot. That's the parameter is was missing.

I see, all available parameters are listed in the [Configuration cheat sheet](https://gogs.io/docs/advanced/configuration_cheat_sheet).
