### ISSUE TITLE
Configuration rewritten after package update

### ISSUE THREAD

**Issue by hynekcer** [gogits/gogs#3085]
Gogs configuration completely rewritten after standard update of installed packages (`apt-get upgrade`). All URLs redirected again to the initial "/install" URL and the setup page was public without warning to all people on the production site long time.

My configuration use the username "git" that is recommended on [Configuration Cheat Sheet](https://gogs.io/docs/advanced/configuration_cheat_sheet). The configuration file `/etc/gogs/conf/app.ini` was readable only by user "git" due to passwords protection.

- Version numbers before and after update are very similar: gogs:amd64 
  from 0.9.13-1461606557.7049cb9.jessie  to 0.9.13-1462579758.3c0c7a9.jessie  
  It was the first "apt-get upgrade" after Gogs package installation.
- Operating system: Debian 8
- syslog message (the only relevant message from all logs):  
  ... gogs-web-1.service[...]: 2016/05/10 10:58:27 [W] Custom config '/etc/gogs/conf/app.ini' not found, ignore this if you're running first time.
- The custom config  "/etc/gogs/conf/app.ini" and the directory "/etc/gogs" was originally writable only by git user and readable by git group, not accessible by other users. The user "gogs" was completely renamed to "git".

After package update and restarted services:
The new username and group "gogs" was created by update, the new "/home/gogs" directory beside "/home/git" created again, rewritten "/etc/gogs/conf/app.ini", changed ownership of /opt/gogs etc. The worst was the redirect to unprotected page "/install". (Fortunately I didn't lost any data  and the fix was relatively easy finally, but it was a very dark time.)

I think that more conditions should be tested to recognize a possible running production server, before possible overwriting. The page "/install" should be never redirected automatically if a customized configuration exists and is strange for you.

The recommended configuration with username "git" is nice and I like it in the usual SSH url `ssh://git@example.com/...`.

**Comment by bkcsoft** [comment]
is this installed from packager.io?

**Comment by hynekcer** [comment]
Yes, gogs is added by the line `deb https://deb.packager.io/gh/pkgr/gogs jessie pkgr`.

**Comment by Unknwon** [comment]
I think you should file bug to packager.io...
