### ISSUE TITLE
landing page lost after login

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3089]
Signing-in after a 404 response (due to attempts to access a private repo w/out being signed in) takes you to the dashboard rather than back to where you started the navigation (ex 404 page, which would be visible after sign-in).

**Comment by bkcsoft** [comment]
I don't think that gogs has a `?redirect={{previousUrl}}` on
login-redirects, this would most likely be a quick fix with MiddleWares
:smiley:

**Comment by strk** [comment]
I've seen auth.go uses a "redirect_to" cookie, when found.
The only code setting "redirect_to" seems to be repo/issue.go, so you're redirected to "new issues" after login. Should all pages (but the auth one) set "redirect_to" ? What woud the best way be to do that ? Any file that is always included in all page views ?

**Comment by Unknwon** [comment]
Note: Could use HTTP header referrer.

**Comment by strk** [comment]
This issue is still not fixed and should thus be re-opened (I cannot reopen it myself).
While a "redirect_to" query parameter is being passed to the login page as of c922199, the login page is not taking it into account and thus failing to take the user back to the original page after login.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

**Comment by strk** [comment]
Works for me. Thanks !
