### ISSUE TITLE
User keys file not readable when REQUIRE_SIGNIN_VIEW

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3090]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.1.4
- Operating system: Debian 8.4
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I do not know if this is desired behavior. When `REQUIRE_SIGNIN_VIEW` is set to true the file: `http://gogs-uri/<username>.keys` is restricted and redirects to the login page. Perhaps getting the public keys should be possible with `REQUIRE_SIGNIN_VIEW` enabled.

### output with curl

```
> GET /<user>.keys HTTP/1.1
> User-Agent: curl/7.38.0
> Host: <hostname>
> Accept: */*
>
< HTTP/1.1 302 Found
* Server nginx/1.6.2 is not blacklisted
< Server: nginx/1.6.2
< Date: Fri, 13 May 2016 06:50:51 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 38
< Connection: keep-alive
< Location: /user/login
< Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
< Set-Cookie: i_like_gogits=dc48c08a2f4e1c77; Path=/; HttpOnly
< Set-Cookie: _csrf=PDkzUCQfyr2rcZsze87xEYCmRi06MTQ2MzEyMjI0OTY5NTUzMTcyOQ%3D%3D; Path=/; Expires=Sat, 14 May 2016 06:50:49 GMT; HttpOnly
< Set-Cookie: redirect_to=%252F<user>.keys; Path=/
<
<a href="/user/login">Found</a>.

* Connection #0 to host <hostname> left intact

```

**Comment by bkcsoft** [comment]
Any reason why you want the keys public in that scenario?

**Comment by xor-gate** [comment]
For server configuration management, as an alternative for LDAP. We use ansible to configure linux servers with ssh and extract the public keys from gogs. 

See: 
http://docs.ansible.com/ansible/authorized_key_module.html

Example ansible playbook:
```
# Using validate_certs:
- authorized_key: user=charlie key=https://github.com/charlie.keys validate_certs=no
```

**Comment by Unknwon** [comment]
> The script/app is ofcourse unable to login into gogs, and exposing public keys is not a problem.

You can create a personal access token and visit URL with `URL?token=xxx`.

**Comment by xor-gate** [comment]
This is a workaround for having a gogs-wide pubkey expose function, but it works. I'm not 100% happy with it as we need to have api-keys floating around. As you see for github anyone is able to access the public keys without any API access token.

**Comment by Unknwon** [comment]
1. Visit any page except login is the purpose of `REQUIRE_SIGNIN_VIEW`.
2. >As you see for github anyone is able to access the public keys without any API access token.

False argument as GitHub does not have such settings, and you can view anyone's public key when `REQUIRE_SIGNIN_VIEW=false`: https://try.gogs.io/unknwon.keys

**Comment by xor-gate** [comment]
The token-based approach is not bad, but as mentioned before it adds some extra configuration and management. It improves security because then the usernames can still not be guessed.

**Comment by Unknwon** [comment]
>It improves security because then the usernames can still not be guessed but the client is able to access the keys.

I don't understand this sentence...

**Comment by xor-gate** [comment]
I will rephrase. 

Security is improved when gogs forces api-tokens for access when `REQUIRE_SIGNIN_VIEW` is active. The `client` which has a token is then able to access the user public keys. Without api-token nobody is able to guess/brute-force usernames with public keys.

**Comment by Unknwon** [comment]
>Security is improved when gogs forces api-tokens for access when REQUIRE_SIGNIN_VIEW is active. The client which has a token is then able to access the user public keys. Without api-token nobody is able to guess/brute-force usernames with public keys.

That is correct... so the issue should be closed I think?

**Comment by xor-gate** [comment]
Yeah as you already mentioned this feature is not the path Gogs wants to take. And I agree with this,
as api-token access is implemented.

It should be closed.

Thanks for your feedback!
