### ISSUE TITLE
Garbage collection timeout should be configurable

### ISSUE THREAD

**Issue by wolkenschieber** [gogits/gogs#3091]
I'm migrating a subversion repository to git. Gogs will serve as version control frontend end. 
The repository contains about 100'000 revisions and is about 3GB in data. With this size a git garbage collections takes about 2 minutes an the hosting machine.

The garbage collection can be triggered through gogs in
 Admin Panel -> Dashboard -> Do garbage collection on repositories

This task fails with error message:
`Process execution timeout: Process execution timeout`

Gogs version (or commit ref): 0.9.13.0318
Git version: 2.7.4
Operating system: Ubuntu 16.04 LTS
Database: SQLite
Can you reproduce the bug at http://try.gogs.io: Not relevant

**Comment by wolkenschieber** [comment]
When looking through the source, I found that the garbage collection is done via `GitGcRepos()` and `process.ExecDir()` with a hardcoded default timeout of one minute.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

You can now config GC timeout via `[git.timeout] GC = 999`.

**Comment by wolkenschieber** [comment]
I'm afraid this is not testable on https://try.gogs.io

**Comment by wolkenschieber** [comment]
The option works nicely in `develop`. When setting a lower value, the timeout is imminent.

However the option is not listed in the configuration overview: `http://host:port/admin/config`

**Comment by Unknwon** [comment]
OK, patch pushed to `develop`.

**Comment by wolkenschieber** [comment]
Everythings fine.
