### ISSUE TITLE
采用工具 sourceTree 没有用用户名和密码即可对私有库进行提交。

### ISSUE THREAD

**Issue by xdsnet** [gogits/gogs#3101]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):0.9.13.0318
- Git version: 利用sourceTree 1.8.30 内置的git工具
- Operating system:Linux
- Database:
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No，本地是http协议头，而try.gogo.io是https协议头
  - [ ] Not relevant
- Log gist:

## Description
一个私有仓库，可以用系统不存在的用户名无密码提交成功。
...

**Comment by Unknwon** [comment]
Hi, which tool you used to clone the private repository?

**Comment by xdsnet** [comment]
就是用的sourceTree 1.8.30 内置的git工具，拉数据的时候并没有登陆的

**Comment by Unknwon** [comment]
If you can't reproduce this on https://try.gogs.io , I think there is a config you made for you username and password and remembered in sourceTree for the local URL you tested.
