### ISSUE TITLE
Picking up of configuration

### ISSUE THREAD

**Issue by joelchen** [gogits/gogs#3102]
Shutting down and starting up the VM with Gogs running in Docker, will go to install page in the browser, with logs outputting, "Custom config '/data/gogs/conf/app.ini' not found, ignore this if you're running first time".

It happens on my Mac with CoreOS VM, running Docker 1.10.3. Issue does not occur with `docker restart gogs`. However, issue resolves after performing `docker restart gogs`.

**Comment by Unknwon** [comment]
I think it is because you did not volume the custom directory... deployment problem please go to https://discuss.gogs.io/...
