### ISSUE TITLE
Blank spaces on tags list

### ISSUE THREAD

**Issue by razvan-cons** [gogits/gogs#3103]
When adding many tags there are white spaces between them on the issue page. Non selected tags are hidden but there's a blank space that persists.

![tags_spaces](https://cloud.githubusercontent.com/assets/1147214/15358975/5b8755de-1d07-11e6-89c5-6602cd0ac513.png)

- Gogs version (or commit ref): 0.9.13.0319
- Git version: 2.6.3.windows.1

Tcl/Tk version 8.6.4
- Operating system: Windows 7 x64
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

**Comment by bkcsoft** [comment]
> Can you reproduce the bug at http://try.gogs.io:
> - [x] Yes (**provide example URL**)

**Comment by razvan-cons** [comment]
[x] Yes: https://try.gogs.io/gogstest123/testrepo2/issues/1

**Comment by razvan-cons** [comment]
This seems to be fixed in PR https://github.com/gogits/gogs/pull/3200

**Comment by BurakDev** [comment]
Yes, waiting for @Unknwon merge it

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3200, please help test on `develop` branch or https://try.gogs.io.

**Comment by BurakDev** [comment]
@Unknwon Thanks ! Tested it with XP Chrome - Firefox - Opera - IE, Win10 Chrome - Firefox - Edge and seems fixed now

**Comment by Unknwon** [comment]
Close as fixed.
