### ISSUE TITLE
Add support for custom Git location

### ISSUE THREAD

**Issue by LukeMauldin** [gogits/gogs#3106]
Gogs should support configuration to specify the location to the Git executable.  My problem is that I am running CentOS 6, which only has Git 1.8.3.1.  I would like to upgrade the version of Git that Gogs is using but I cannot upgrade the system level Git on the machine.

**Comment by xiegeo** [comment]
Doesn't setting the PATH environmental variable work?

**Comment by LukeMauldin** [comment]
I tried modifying the path variable in systemd but gogs wouldn't start up and I couldn't figure out why.

**Comment by xiegeo** [comment]
Make sure you are appending to path (or prepend in your case to take
precedence).
'export PATH=/path/to/dir:$PATH'

Also, you can test everything out in terminal first. You can 'echo $PATH'
or just run 'path' before and after you change path to see what changes you
made.

**Comment by Unknwon** [comment]
I think @xiegeo has given the correct solution... it's more like configuration problem.
