### ISSUE TITLE
Mention fails, when username contains dash

### ISSUE THREAD

**Issue by jeppech** [gogits/gogs#3107]
- Gogs version (or commit ref): 0.9.25.0506 0a78d99
- Git version: 2.8.1
- Operating system: FreeBSD 10.1-RELEASE-p34

Reproduced at https://try.gogs.io/jeppech-aaa/testtestesetsetset/issues/1

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by jeppech** [comment]
Works! 👍
