### ISSUE TITLE
private repo can be cloned with empty user/password

### ISSUE THREAD

**Issue by dcale** [gogits/gogs#3110]
I'm running Gogs Version: 0.9.15.0323 on Ubuntu. I changed a previously public repo to a private one and can still clone if I know the URL (using the http scheme). Git will prompt me for a username/password but by simply hitting "enter" twice the request passes through and I can clone the repository.

**Comment by dcale** [comment]
changed title

**Comment by terrywh** [comment]
0.9.13.0318 same problem, this is serious.

**Comment by kinnarr** [comment]
I have the same behavior, if my account has an access token. After deleting this, cloning with empty username and password doesn't work any more.

**Comment by kinnarr** [comment]
I found the source for this behavior and will submit a pull request later today

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3136, please help test on `develop` branch or https://try.gogs.io.
