### ISSUE TITLE
Cannot delete organization

### ISSUE THREAD

**Issue by Lertsenem** [gogits/gogs#3112]
- Gogs version (or commit ref): **0.9.13.0318**
- Git version: _irrelevant_
- Operating system: **Linux**
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

I can't find a way to delete an organization, both as owner or administrator.

The "Delete Organization" form asks for a password (probably the password of the organization since they seem to be created as user internally), but I never provided any password during the organization creation. I tried several different password (empty string, name of the org, name of the user, pass of my user, ...) to no avail.

When looking inside the sqlite database, the password field for the organization is empty.

## Reproduce

- Create a new organisation.
- Go to the setting page of the organization and select "Delete Organization".
- Try to delete the organization.

**Comment by bkcsoft** [comment]
Works perfectly fine here. The password is your logged in users password.

**Comment by Lertsenem** [comment]
Okay, my bad, it seems I did not check this properly enough.
And for the record: when you log in with a reverse proxy and activate the creation of accounts automatically, the password is actually your username.

Thanks a lot, and sorry for the wrong issue.
