### ISSUE TITLE
无法提交

### ISSUE THREAD

**Issue by jnan77** [gogits/gogs#3113]
我安装完毕后，使用user1建立一个组，把user2加到组里面，然后user2在组里建立一个项目，但是我push代码时却提示权限不足（User permission denied），无法提交。

Centos7x64，gogs-0.9.13，是使用二进制安装的

**Comment by xxxifan** [comment]
我也碰到这种问题，push的时候提示User permission denied,好像几乎都是在组织里面push的时候会出现！

**Comment by Unknwon** [comment]
https://unknwon.io/organize-your-teams-with-gogs-organization/#createnewteam

**Comment by kukuzhang** [comment]
我碰到的情况是 只有root用户的仓库可提交 新用户创建的仓库不能提交。
