### ISSUE TITLE
gogs appears to check for specific uid

### ISSUE THREAD

**Issue by thoraxe** [gogits/gogs#3114]
In Docker it is generally a best practice not to try to run as a specific UID for security reasons. See:

https://docs.openshift.com/enterprise/latest/creating_images/guidelines.html

In trying to prepare a Docker image for use with OpenShift, I am running into an issue where, despite being the "gogs" user as far as the shell session is concerned, gogs still refuses to run:

```
bash-4.2$ id
uid=10101(gogs) gid=0(root) groups=0(root)
bash-4.2$ whoami
gogs
bash-4.2$ gogs run web
Error: You must be executing as the user 'gogs' or with root privileges to launch commands.
Either log in as 'gogs', root, use sudo, or add sudo privileges for running gogs with your current user.
```

I cannot seem to find in the code where this check is enforced, but I would think this seems to be not the best way to check (by specific UID).

gogs-0.9.13-1462579758.3c0c7a9.centos7.x86_64

**Comment by sapk** [comment]
If I remember well this is set at install and can be change in https://github.com/gogits/gogs/blob/master/conf/app.ini .

**Comment by thoraxe** [comment]
Changing this does not seem to fix the problem:

```
bash-4.2$ gogs run web
Error: You must be executing as the user 'gogs' or with root privileges to launch commands.
Either log in as 'gogs', root, use sudo, or add sudo privileges for running gogs with your current user.
bash-4.2$ id^C
bash-4.2$ head /opt/gogs/conf/app.ini 
# NEVER EVER MODIFY THIS FILE
# PLEASE MAKE CHANGES ON CORRESPONDING CUSTOM CONFIG FILE

; App name that shows on every page title
APP_NAME = Gogs: Go Git Service
; Change it if you run locally
RUN_USER = gogs
; Either "dev", "prod" or "test", default is "dev"
RUN_MODE = dev

bash-4.2$ id
uid=10101(gogs) gid=0(root) groups=0(root)
```

My environment thinks I am the `gogs` user. Changing `RUN_USER` to either 10101 (my id) or "gogs" I get the same error about the user/privileges.

**Comment by thoraxe** [comment]
I just noticed the warning:

`# PLEASE MAKE CHANGES ON CORRESPONDING CUSTOM CONFIG FILE`

Where is the "custom config file"???

**Comment by sapk** [comment]
it's generated after install and contain all modification from this base file. It's should be in  /opt/gogs/custom if gogs is installed in /opt/gogs

**Comment by thoraxe** [comment]
So actually it looks like there were permissions issues on reading /etc/gogs and, after those were fixed, gogs started running no problem -- even if the system didn't think my ID was the "gogs" user... so that's good I guess.

It still might require some tweaking for me, but, we'll see.
