### ISSUE TITLE
Can't configure logs at install for console

### ISSUE THREAD

**Issue by thoraxe** [gogits/gogs#3119]
- Gogs version (or commit ref): gogs-0.9.13-1462579758.3c0c7a9.centos7.x86_64
- Git version: not relevant
- Operating system: CentOS 7
- Database: (not really relevant)
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
## Description

When going through the installation dialogue, the only option is to set a folder for logs to go to. Then, you are "stuck" with file unless you edit the ini file.

This is also related to #2798 in that even if I configure console logging after the fact, it looks like it won't work.

Also #2799 and #2860 
...

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

![image](https://cloud.githubusercontent.com/assets/2946214/24028659/1d0cbcd4-0aa7-11e7-8a3c-f80c39e22dd7.png)
