### ISSUE TITLE
PID file

### ISSUE THREAD

**Issue by captainark** [gogits/gogs#3120]
Hi,

I use [Monit](https://mmonit.com/monit/) to monitor daemons running on my systems. It needs a PID file to be able to check whether a process is running or not.

Could you please provide an option to generate a PID file when gogs starts ?

Thanks.

**Comment by stevenroose** [comment]
@captainark I don't think it is up to Gogs to create PID files. I suggest using [`start-stop-daemon`](http://manpages.ubuntu.com/manpages/trusty/man8/start-stop-daemon.8.html) to maintain and monitor daemons and their PID files.

**Comment by captainark** [comment]
Most apps that run as a daemon do provide a way to write a PID file when they start.

I can't use `start-stop-daemon` since I run systemd.

For the time being, I've added the following in my gogs.service unit file : 
```
ExecStartPre=/bin/bash -c "/bin/rm -f /run/gogs/gogs.pid"
ExecStartPost=/bin/bash -c "/usr/bin/pgrep -fx '/opt/gogs/gogs web' > /run/gogs/gogs.pid"
ExecStopPost=/bin/bash -c "[[ -f /run/gogs/gogs.pid ]] && /bin/rm /run/gogs/gogs.pid"
```

I've also created a `/etc/tmpfiles.d/gogs.conf` file to manage the `/run/gogs` folder creation when the server reboots : 
```
d /run/gogs  0755  git  git  -
```

I still hope PID file management will get implemented in a future version of gogs, though ;)

**Comment by Unknwon** [comment]
How to generate a PID file?

**Comment by captainark** [comment]
Maybe you could use [this package](https://github.com/facebookgo/pidfile) ?

**Comment by Marco01809** [comment]
@captainark Putting
```
ExecStartPost=/bin/bash -c 'echo $MAINPID > /run/gogs.pid'
PIDFile=/run/gogs.pid
```
into the systemd unit file should be sufficient and more reliable.
Using the ">" pipe operator overwrites the old contents, so no need to delete the file beforehand, and by specifying PIDFile, systemd will the delete the file when stopping the service.

**Comment by stevenroose** [comment]
The pidfile package @captainark suggests looks ok. But make sure to also make it possible to specify the location of the pidfile in the config file.

**Comment by captainark** [comment]
@Marco01809 Thanks, good to know, I have few unit files to edit now ! Since I'm not running gogs as root, I modified what you posted a bit, but it's working great, and it's much cleaner than what I was using : 
```
ExecStartPost=/bin/bash -c 'echo $MAINPID > /run/gogs/gogs.pid'
PIDFile=/run/gogs/gogs.pid
```

I'd still rather the pid file be managed by gogs, though. I think the pid file should always be created, using the `$APP_DATA_PATH/gogs.pid` path by default, with an option to modify the path should the user decide to do so.

**Comment by Marco01809** [comment]
@captainark You're right, I have overlooked that one. I think adding `PermissionsStartOnly=true` should be enough to make it work for non-root users. With this directive, the ExecStartPre/ExecStartPost commands are always run as root, but the `User=` directive still applies to ExecStart.

Regarding the default path for the pid file; I agree on the path you suggested for the source/binary versions of gogs. For packaged versions (deb, rpm) however, the default should be /run, since that's the expected standard path for pid files.

**Comment by captainark** [comment]
@Marco01809 systemd has `tmpfiles.d` for that purpose. Creating a `/etc/tmpfiles.d/gogs.conf` with the following content will create the `/run/gogs` folder during boot with the `git` user as its owner : 
```
d /run/gogs  0755  git  git  -
```

I might be wrong, but I believe it's better for a daemon's PID file to be owned by the user that's running it.

I agree with you regarding the distinction between source and packaged versions of gogs. Those packages should contain the `tmpfiles.d` configuration file or the `sysv-rc` init script should take the folder creation and permission management into account.

**Comment by Unknwon** [comment]
Close as Gogs should not do this itself.
