### ISSUE TITLE
See code base?

### ISSUE THREAD

**Issue by i00** [gogits/gogs#3123]
On GitHub when you are viewing the files there is a bit "up top" to allow you to see what code bases are used (the colorful line under the commit, branch, release, and contributer, counts) that you can click on for more info...

Can this be implemented in GoGit?

Kris

**Comment by stevenroose** [comment]
You mean what programming languages?

**Comment by i00** [comment]
Yes

**Comment by bkcsoft** [comment]
There's already an issue for this (search for code statistics). Close #3123
as duplicate
