### ISSUE TITLE
Docker root repository setting documentation needs updating

### ISSUE THREAD

**Issue by oleersoy** [gogits/gogs#3126]
The Docker documentation says this:

>Repository Root Path: keep it as default value /home/git/gogs-repositories because start.sh already made a symbolic link for you.

I think this is out of date.  I don't see a symbolic link being created in start.sh and /data/gogs/conf/app.ini has the following settings:
```
[repository]
ROOT = /data/git/gogs-repositories
```

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/blob/master/docker/s6/gogs/setup
