### ISSUE TITLE
delete single user cause all users ssh pub key missing from .ssh/authorized_keys file

### ISSUE THREAD

**Issue by terrywh** [gogits/gogs#3128]
Delete single user cause all users ssh pub key missing from .ssh/authorized_keys file.

version: 0.9.13.0318 
database: sqlite
os: CentOS 7

use admin account and delete a normal user account after which .ssh/authorized_keys is emptied; all other users have to remove ssh key and add it again.

**Comment by terrywh** [comment]
gdb backtrace to ssh_key.go:595 `RewriteAllPublicKeys` method which generate a empty `authorized_keys.tmp` file

**Comment by Unknwon** [comment]
Have you tested latest `master` branch?
