### ISSUE TITLE
Provide checksums for releases

### ISSUE THREAD

**Issue by stevenroose** [gogits/gogs#3129]
Would it be a lot of hassle to provide checksums for the archives for every release? Just a `archive.tar.md5` file next to every archive file would be ok.

**Comment by bkcsoft** [comment]
This seems fairly simple, I can have a look tomorrow. Golang has built-in
support for different chechsums so generating one is easy.

**Comment by stevenroose** [comment]
Yeah, I just don't know how the releases are made. Probably not Go, but some kind of GitHub WebHook feature, no?

**Comment by Unknwon** [comment]
See https://dl.gogs.io/checksum_sha256_v0.9.48.txt
