### ISSUE TITLE
Restrict certain users to only issues/PRs

### ISSUE THREAD

**Issue by stevenroose** [gogits/gogs#3130]
As suggested by @strk in https://github.com/gogits/gogs/issues/1297:

It would be useful to restrict certain users (f.e. new users or external users (see OpenID)) until they are approved. More generally, permission levels could be `none`, `feedback-only` (being issues and PRs) and `full` (being also able to have repositories). Ideally of course, this would be defined for each individual user so that new users could be approved to gain full permissions.

**Comment by strk** [comment]
I think one issue with PR is that making a PR _implies_ the ability to create a repository (to hold the PR branch). So granting PR would automatically be granting creation of repositories.

Ideally, federated PR should be supported (ie: PR linking to branches residing elsewhere)

**Comment by stevenroose** [comment]
@strk True. However, I remember making an issue for that too, but I can't find it. Perhaps it was just a discussion on the Gitter.

**Comment by stevenroose** [comment]
I made a new one here: https://github.com/gogits/gogs/issues/3131

**Comment by Unknwon** [comment]
What's this different from https://github.com/gogits/gogs/issues/649 and https://github.com/gogits/gogs/issues/2157?

**Comment by strk** [comment]
They all mention different "units". How about keeping them open until all fixed ?
I'd look at #3049 to move this further.

**Comment by Unknwon** [comment]
I think this one is duplicated..

**Comment by sbrl** [comment]
@Unknwon How does this have anything to do with #3049? I think I'm missing something here.

**Comment by Unknwon** [comment]
@sbrl https://github.com/gogits/gogs/issues/3130#issuecomment-230105649

**Comment by sbrl** [comment]
@Unknwon I'm confused.
