### ISSUE TITLE
My issues don't show up when repo belongs to organisation

### ISSUE THREAD

**Issue by DeKugelschieber** [gogits/gogs#3132]
- Gogs version (or commit ref): 0.9.13.0318
- Operating system: Ubuntu 14.04 LTS (Server)
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not tried yet

## Description

Issues assigned to me won't show up below the "Issues" section when the repo the issue is created for belongs to an organisation. Also on the left: "Assigned to you" shows 0.

I'll may try it on try.gogs.io later.

**Comment by edacval** [comment]
#1820 ?

**Comment by DeKugelschieber** [comment]
Yes, sound familiar :)
