### ISSUE TITLE
Admin passwort stored in clear text in Config-File

### ISSUE THREAD

**Issue by Der-Arzt** [gogits/gogs#3134]
- Git version: newest stable in Debian repositories
- Operating system: Debian
- Database:
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant

## Description
I recognized that my password for the admin user I created during the installation is stored in clear in the config-file. Why not hashed like the other passwords located in the database?
I installed GOGS together with a friend of mine using TeamViewer and while looking at the file he could read the password... not that fatal but it's a security lack, isn' t it?

**Comment by Der-Arzt** [comment]
Version: v0.9.13

**Comment by bkcsoft** [comment]
It does not store the admin password in `app.ini`. Unless you mean the
database password, which have to stored in plain-text AFAIK

**Comment by Der-Arzt** [comment]
Ok, sorry - I mixed things up. The password in the config-file was the
password for the SMTP-Server.
But thanks a lot for your help.
