### ISSUE TITLE
迁移失败

### ISSUE THREAD

**Issue by weisong-icarbonx** [gogits/gogs#3139]
迁移失败：Clone: execution is timeout [duration: 10m0s] - error: unable to write sha1 filename /data/gogs/gogs-repositories/icarbonx/cos-java-sdk.git/objects/pack/pack-522c4ac57b9e6e51220d7da87a313ce6d3ac1652.pack: No such file or directory fatal: cannot store pack file fatal: index-pack failed

src:https://github.com/tencentyun/cos-java-sdk

**Comment by Unknwon** [comment]
Hi, apparently, it could be a disk problem: https://try.gogs.io/unknwon/issue-3139 succeed within seconds...
