### ISSUE TITLE
Support authentication source config file

### ISSUE THREAD

**Issue by stevenroose** [gogits/gogs#3142]
We are trying to [package](https://github.com/YunoHost-Apps/gogs_ynh) Gogs to work with [YunoHost](https://yunohost.org/), but this issue affects anyone packaging Gogs automatic installation.

We want to enable LDAP authentication during installation, but when automating the installation, it is hard to inject the authentication config into the SQL table because the table is only initialized on the first run.
Since the `app.ini` is the place we can manipulate Gogs configuration for automated installation, ideally authentication configuration should be here too.

Since I have no idea of how authentication is implemented in general, I don't know if there are arguments why authentication should be in SQL at all. If there are no fundamental arguments, I would be willing to try and migrate authentication config to `app.ini`, making sure compatibility is maintained for upgrading users.

**Comment by Unknwon** [comment]
Hi... actually I'm not quite understand what you're trying to describe... but set auth info in `app.ini` would be acceptable, it seems a dirty workaround instead of a solution.

**Comment by stevenroose** [comment]
It just seems to me that authentication settings are part of the installation configuration rather than something to do at runtime. So it should be put in `app.ini` instead of the database.

Many packaged versions of Gogs that are specifically made for a certain software distribution will want to automatically integrate Gogs with the authentication scheme they use during the installation period. That is currently impossible because the authentication section from Gogs can only be accessed while it is running through the web interface or through the underlying SQL DB.

So what I propose is a new `app.ini` section f.e. `[authentication]` or `[ldap]` where the required LDAP parameters can be provided.

Examples of apps using config files for auth (I think the ones that don't are actually very rare) are: [Owncloud](https://github.com/YunoHost-Apps/owncloud_ynh/blob/master/conf/config.json#L13), [Seafile](https://github.com/YunoHost-Apps/seafile_ynh/blob/4e82eba40931cd168dd66a9c3e0f3b3611e46cb0/scripts/install#L100), [Roundcube](https://github.com/YunoHost-Apps/roundcube_ynh/blob/master/conf/config.inc.php#L103), [Ampache](https://github.com/YunoHost-Apps/ampache_ynh/blob/master/conf/ampache.cfg.php#L609), [Baikal](https://github.com/YunoHost-Apps/baikal_ynh/blob/master/conf/config.php#L43) and actually all of the ones that I came across when packaging apps for YunoHost.

**Comment by Unknwon** [comment]
Gogs supports theoretically unlimited authentication sources, that's why config in file is not possible.

**Comment by jerrykan** [comment]
Having to configure the authentication sources in the DB is an impediment to being able to deploy gogs using configuration management tools. I imagine it would be possible to implement any number of authentication sources using the following sort of scheme in the `app.ini` 

```
[auth]
backend = ldap_ad, ldap_openldap, pam

[auth_ldap_ad]
type = ldap
... (other ldap specific settings) ..

[auth_ldap_ad]
type = ldap
... (ldap specific settings) ..

[auth_pam]
type = pam
... (pam specific settings) ..

```

the `backend` value in the `[auth]` section defines the priority of the authentication sources that are enabled and are references to the `[auth_*]` sections which contain the configuration for each authentication source.

It may require a little more processing of the `app.ini` file to load the configuration settings, but it should be possible.

**Comment by Unknwon** [comment]
@jerrykan good point, but I think we probably should just make a new file named `auth_sources.ini`?

**Comment by jerrykan** [comment]
@Unknwon my personal preference would be to keep everything in `app.ini` so there is only one file to configure/manage, but I don't see any major issues if it were to be implemented in another config file.

**Comment by Unknwon** [comment]
`app.ini` is more about site configuration, but authentication sources are data in my opinion.

**Comment by jerrykan** [comment]
I don't see configuring authentication backends as being any different to configuring the database or mail servers. It is site specific, generally configured during initial setup, and rarely changes. So I wouldn't really consider the it data.

**Comment by stevenroose** [comment]
@Unknwon Can you point me to where auth configuration is located? Perhaps I can try and implement the migration myself.

**Comment by Unknwon** [comment]
@stevenroose `login_source` table.

**Comment by stevenroose** [comment]
This issue was moved to go-gitea/gitea#183

**Comment by jerrykan** [comment]
Closing the issue without any explanation about why the issue has been moved is a bit weird? Is there any explanation about what gitea is and why the issue has be moved there instead of fixing it in gogs?

**Comment by stevenroose** [comment]
Oh, that's on accident. I use an issue migration tool to copy the issues to Gitea, it should not have closed them here. I'll fix it.

**Comment by Unknwon** [comment]
Note: add another file `admin.ini`.

**Comment by ebartz** [comment]
It would be awesome if there would be a way of setting the auth sources automatically either through files of the command line tool.

I guess I would prefer the config file because auth sources are somthing verry basic that most users don't change very often.

For the different Auth sources there should also be a way for the user to decide which one he wants to use for login.

In most cases this does not matter but if you have 2 directories with the same username in it, that could be a problem.

From the UI perspective you could adopt from the login mask of GitLab: 
![image](https://user-images.githubusercontent.com/6342767/38021681-d4a1eb22-327d-11e8-88ac-e4ed6addc13b.png)

**Comment by Unknwon** [comment]
This feature is now completed.

Before docs comes online, quick intro is to put your config files under `custom/auth.d` directory. You can find examples at https://github.com/gogits/gogs/tree/f2ecfdc96a338815ffb2be898b3114031f0da48c/conf/auth.d

**Comment by mikaraunio** [comment]
I realise this issue is closed, let me know if you want me to open a new issue.

Looking at the new authentication docs, I can't seem to find a way to select a default authentication method for the login dialog. It always defaults to "Local", yet we only log in using LDAP, so this means an  extra click for the user on each login.

Is there an (undocumented) way to select the default?

In many cases where other auth methods are configured, local auth is only used for a "failsafe" admin user, and is then not a sensible default.

**Comment by Unknwon** [comment]
@mikaraunio Thanks for pointing out!

>It always defaults to "Local", yet we only log in using LDAP, so this means an extra click for the user on each login. 

Yes, please open a new issue for specific problem.

**Comment by randyesq** [comment]
Is is possible to to oauth in the config file?

**Comment by Unknwon** [comment]
No oauth support at all...
