### ISSUE TITLE
通过ssh远程登录服务器（root账号），出现账号没有shell的权限问题

### ISSUE THREAD

**Issue by xufanghui** [gogits/gogs#3143]
通过ssh远程登录服务器（root账号），出现账号没有shell的权限问题，下面是提示内容
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.

有没有好的解决方法，最不幸的是我gogs服务已经关了

**Comment by wj5346599** [comment]
同样是这个问题。

**Comment by xxxifan** [comment]
因为你是用的root帐号启动的gogs服务吧，应该用另外的一个帐号
或许使用内置的ssh服务，指定另外的端口也可以，没有试过

**Comment by Unknwon** [comment]
This expected behavior and the error message already said what's need to be done to fix this problem.

**Comment by smallnerd** [comment]
同样是这个问题，有人解决了吗？GOOGLE不到原因啊，求大神

**Comment by thinkhy** [comment]
同问

**Comment by Pimaweichai** [comment]
试下在服务器里创建gogs用户，在gogs用户下安装启动gogs，远程用gogs用户登录

**Comment by weifansym** [comment]
@Pimaweichai 这个只是换成了别的用户，但是没有解决上面的问题啊，这样同样会导致gogs用户出现这个问题。

**Comment by weifansym** [comment]
我找到一个解决方案，我这边是使用user1搭建的gogs，在使用ssh 用户为user1登录的时候出现了你说的问题。我这边切换到root登录，然后切到user1的.ssh文件夹下，然后执行```ls```你会在看到authorized_keys文件，把这个文件删了就好了。我就是这么解决的，希望对你们有用。
参考：[https://discuss.gogs.io/t/how-to-config-ssh-settings/34](https://discuss.gogs.io/t/how-to-config-ssh-settings/34)

**Comment by dshame** [comment]
服务器配置只能使用ssh密钥登录(root用户)
在root用户下安装gogs, 然后覆盖了/root/.ssh/authorized_keys 文件.导致ssh登录服务器失败.重写authorized_keys也是不能登录.
重写的authorized_keys 文件也是带有特殊处理的.这就导致服务器永远登录不上. 需要重装系统,并且不能备份资料.(这才是最头痛的地方)
这应该算不是bug的bug.
解决办法.
在开始安装之前, 新建一个用户.在新建用户安装gogs.重新生成的authorized_keys文件不会阻碍其他用户登录

gogs增加功能. 重写不带特殊处理的authorized_keys文件.作为紧急修复功能

不说了,准备重装系统. 头痛!
https://discuss.gogs.io/t/how-to-config-ssh-settings/34 
如果我没操作错误,应该不能解决上述情况
