### ISSUE TITLE
Repository `official website` field disallows non-standard top-level domain public suffixes

### ISSUE THREAD

**Issue by irstacks** [gogits/gogs#3144]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.7.3
- Operating system: Linux
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
Repository `official website` field (via __Settings__) disallows non-standard public suffixes/top-level domains like _.info_ or  _.me_.
Error message is `Website is not a valid URL.`.  

...

**Comment by bkcsoft** [comment]
I'll have a look at fixing this tomorrow :)

**Comment by irstacks** [comment]
I think I'm wrong -- it seems instead it requires an _http://_-esque prefix. Oops.
