### ISSUE TITLE
SSH and port is not supported

### ISSUE THREAD

**Issue by lifehome** [gogits/gogs#3146]
- Gogs version (or commit ref): 0.9.28.0527
- Git version: e9ae926e040c94ce66666ae6c330c93918fa321c
- Operating system: ArchLinux
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

I am creating a migration repo, however the following error appeared:

```
Migration failed: Clone: exit status 128 - fatal: Unable to look up gitlab:@example.org:1234 (port 9418) (Name or service not known)
```

What I am trying to do, is create a mirror repo from a private Gitlab repo, however the following things I found in Gogs is not respected/supported:

- Git over SSH is not supported
- Port is hardcoded at 9418
- The following format is not supported: ssh://_domain.tld_:*port**/path/to-repo.git

What left remain in the list is HTTP/HTTPS, however both options are not viable, as Gitlab does not support HTTP auth, therefore I have no choice left behind.

## Suggestions

- Supporting Git over SSH
- Respect the port filled in the URL box, instead of hardcode, set the input port as preferred.
- Support the ssh URL format I guess?

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/1565
