### ISSUE TITLE
Gogs fails to start

### ISSUE THREAD

**Issue by Marcel-Robitaille** [gogits/gogs#3148]
- Gogs version (or commit ref): 1:0.9.13-3
- Git version: 2.8.3
- Operating system: Arch linux (`uname -a`: `Linux nas 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux`)
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/Marcel-Robitaille/fb42ffb6d213f6990dab6422a6b386a3

## Description

I have just installed gogs version 1:0.9.13-3 using `yaourt -S gogs`. I was following the guide [here](https://wiki.archlinux.org/index.php/Gogs#Installation). When I try to start gogs with `systemctl start gogs.service`, I get no errors. When I run `systectl status gogs` I get something similar to the above gist.

**Comment by edacval** [comment]
According to log , something is already listening on port 3000 (nodejs?) .   `sudo ss -lptn|grep 3000` will give an answer

**Comment by Marcel-Robitaille** [comment]
Thanks @edacval, I should have caught that one. Changing the port in `/srv/gogs/conf/app.ini` seems to have fixed it.
