### ISSUE TITLE
glide breaks raspberry pi/arm docker build

### ISSUE THREAD

**Issue by atomi** [gogits/gogs#3152]
- Gogs version (or commit ref):
https://github.com/gogits/gogs/commit/bcd4adb3a0b59581ee3ddca2c31ae8d339b92cfd
- Operating system:
arch linux docker/raspberry pi
- Can you reproduce the bug at http://try.gogs.io:
  - [x ] Not relevant
## Description

This commit https://github.com/gogits/gogs/commit/bcd4adb3a0b59581ee3ddca2c31ae8d339b92cfd which adds glide, breaks the raspberry pi docker build.
Glide error: `cannot detect vcs` only on gopkg.in packages.
...

**Comment by vitorsilvalima** [comment]
Further Information:
+ git clone -b 0.10.2 https://github.com/Masterminds/glide /tmp/go/src/github.com/Masterminds/glide
Cloning into '/tmp/go/src/github.com/Masterminds/glide'...
Note: checking out '2d0eb388e16d833ba3c55068335b3577b6b09ff0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

+ cd /tmp/go/src/github.com/Masterminds/glide
+ make build
go build -o glide -ldflags "-X main.version=0.10.2" glide.go
+ go install
+ mkdir -p /tmp/go/src/github.com/gogits/
+ ln -s /app/gogs/ /tmp/go/src/github.com/gogits/gogs
+ cd /tmp/go/src/github.com/gogits/gogs
+ glide install
[ERROR] Failed to find glide.yaml file in directory tree: Cannot resolve parent of /
The command '/bin/sh -c ./docker/build.sh' returned a non-zero code: 2

**Comment by vitorsilvalima** [comment]
I ran 'ls -lah' inside the directory to see the symbolic links and this is what I got. There is no glide.yaml inside that directory

+ go install
+ mkdir -p /tmp/go/src/github.com/gogits/
+ ln -s /app/gogs/ /tmp/go/src/github.com/gogits/gogs
+ cd /tmp/go/src/github.com/gogits/gogs
+ ls -lah .
total 24764
drwxr-xr-x    6 root     root        4.0K Jun  4 04:28 .
drwxr-xr-x    3 root     root        4.0K Jun  4 04:28 ..
-rw-r--r--    1 root     root         903 Jun  4 03:41 Dockerfile
-rw-r--r--    1 root     root        1.0K Mar  6 21:05 LICENSE
-rw-r--r--    1 root     root        7.1K Mar  6 21:05 README.md
-rw-r--r--    1 root     root        5.0K Mar  6 21:05 README_ZH.md
drwxr-xr-x    3 root     root        4.0K Jun  4 04:27 docker
-rwxr-xr-x    1 root     root       24.1M Mar  6 21:05 gogs
drwxr-xr-x    7 root     root        4.0K Mar  6 21:05 public
drwxr-xr-x    7 root     root        4.0K Mar  6 21:05 scripts
drwxr-xr-x   10 root     root        4.0K Mar  6 21:05 templates

**Comment by vitorsilvalima** [comment]
I think it isn't an error. I have just tested it again.
Follow the steps bellow:
1- git clone git@github.com:gogits/gogs.git
2 - cp Dockerfile.rpi Dockerfile
3 - docker build --tag='gogs' .

It correctly worked for me.

**Comment by atomi** [comment]
I think my Pi is burnt out I'm not able to test it again. 
By the way you can tell docker build to use just the .rpi file
`docker build -t my/gogs -f Dockerfile.rpi .`
But i don't think our errors were similar anyway.

**Comment by vitorsilvalima** [comment]
hahah how did  you burn it? Anyway, I compiled using your command.
docker build -t my/gogs -f Dockerfile.rpi .
Sending build context to Docker daemon 16.62 MB
Step 1 : FROM hypriot/rpi-alpine-scratch:v3.2
 ---> f87d69083db4
Step 2 : MAINTAINER jp@roemer.im, raxetul@gmail.com
 ---> Using cache
 ---> 703a0f4bbfa3
Step 3 : ADD https://github.com/tianon/gosu/releases/download/1.9/gosu-armhf /usr/sbin/gosu
Downloading [==================================================>] 1.469 MB/1.469 MB
 ---> Using cache
 ---> 2771d2813b6d
Step 4 : RUN chmod +x /usr/sbin/gosu  && echo "http://dl-4.alpinelinux.org/alpine/v3.3/main/"      | tee /etc/apk/repositories     && echo "http://dl-4.alpinelinux.org/alpine/v3.3/community/" | tee -a /etc/apk/repositories  && apk -U --no-progress upgrade && rm -f /var/cache/apk/APKINDEX.*  && apk --no-cache --no-progress add ca-certificates bash git linux-pam s6 curl openssh socat
 ---> Using cache
 ---> 9a7743e68335
Step 5 : ENV GOGS_CUSTOM /data/gogs
 ---> Using cache
 ---> 74c10ebb7c88
Step 6 : COPY . /app/gogs/
 ---> Using cache
 ---> 59b7f5d23de7
Step 7 : WORKDIR /app/gogs/
 ---> Using cache
 ---> 335d48c1c2d4
Step 8 : RUN ./docker/build.sh
 ---> Using cache
 ---> c02cf9bce1d0
Step 9 : COPY docker/nsswitch.conf /etc/nsswitch.conf
 ---> Using cache
 ---> bb8884668861
Step 10 : VOLUME /data
 ---> Using cache
 ---> 94c523954a38
Step 11 : EXPOSE 22 3000
 ---> Using cache
 ---> 88efd6a64670
Step 12 : ENTRYPOINT docker/start.sh
 ---> Using cache
 ---> 51c601c546dd
Step 13 : CMD /bin/s6-svscan /app/gogs/docker/s6/
 ---> Running in 481a69e132bb
 ---> ded63013e40b
Removing intermediate container 481a69e132bb
Successfully built ded63013e40b

**Comment by atomi** [comment]
It got too hot.  I'll close this for now. Thanks.
