### ISSUE TITLE
can not fetch golang.org/x/.. package

### ISSUE THREAD

**Issue by kakamessi99** [gogits/gogs#3153]
when i use glide upate the project ,some errors occurred like this 

![1](https://cloud.githubusercontent.com/assets/7124009/15667764/813b8d70-274a-11e6-82b4-f1ce25c678cc.png)
what shoud i do to make it work

**Comment by novaeye** [comment]
maybe you need a "ladder"...

**Comment by Unknwon** [comment]
Connect a VPN...
