### ISSUE TITLE
Remove RUN_USER check on Windows

### ISSUE THREAD

**Issue by elead1** [gogits/gogs#3158]
- Gogs version (or commit ref): 0.9.13.0319
- Operating system: Windows
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite

## Description

...
Regarding Disqus comment located [here](https://disqus.com/home/discussion/gogsweb/gogs_go_git_service_a_self_hosted_git_service_written_in_go_092/?utm_source=reply&utm_medium=email&utm_content=read_more#comment-2705997342), please remove the RUN_USER check for Gogs user accounts under Windows, to allow seamless transition from running locally to running as a service. Currently, each setting of RUN_USER in app.ini has a separate set of user accounts.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
