### ISSUE TITLE
Issue count wrong

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#3159]
- Gogs version (or commit ref): https://github.com/gogits/gogs/commit/c041273dd334fc7a45ca6cb67ea2c2b492c4a5ed with rebased https://github.com/gogits/gogs/pull/2966 applied.
- Git version: 1.8.3.1
- Operating system: Red Hat 7.2
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description

It seems like the the issue count changed in the last view commits. Earlier I was using a version based on https://github.com/gogits/gogs/commit/7826eae452360913b7c9e476566dc30601270c75. With the current version the issue count is negativ:

![gogs_issue_count](https://cloud.githubusercontent.com/assets/2813782/15713827/52bf52c8-2818-11e6-9d72-8e6db6f8a2da.png)

Repository shown has now open/closed issues - only the shown PRs.

**Comment by xor-gate** [comment]
It is also broken on https://try.gogs.io

* Gogs version: `0.9.30.0601` 
* Repo: [admin1/whots](https://try.gogs.io/admin1/whots)

**Comment by BurakDev** [comment]
Pull request fixing this issue is here #3207

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3207, please help test on `develop` branch or https://try.gogs.io.

**Comment by xor-gate** [comment]
@hhenkel, probably this can be closed as my repo now reports 0 issues instead of -1. With latest 0.9.30.0601 after merge of #3207. Thanks all!

**Comment by BurakDev** [comment]
Tested, seems fixed !

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by xor-gate** [comment]
:+1:
