### ISSUE TITLE
Gogs answers to go-get with a 404 when requesting nested packages

### ISSUE THREAD

**Issue by jsevilleja** [gogits/gogs#3161]
Hi,

when requesting a package like git.jsevilleja.org/golibs/http/handlers gogs answers with a 404, which causes this:

package git.jsevilleja.org/golibs/http/handlers: unrecognized import path "git.jsevilleja.org/golibs/http/handlers" (parse https://git.jsevilleja.org/golibs/http/handlers?go-get=1: no go-import meta tags)
package git.jsevilleja.org/golibs/http/utils: unrecognized import path "git.jsevilleja.org/golibs/http/utils" (parse https://git.jsevilleja.org/golibs/http/utils?go-get=1: no go-import meta tags)

Github behaviour is to download the whole main package.

Regards,

**Comment by strk** [comment]
I *think* github support is built into "go get" (hard-coded).
It would be nice to provide some mechanism to make what you'r asking for possible though.
It takes exposing a "go-import" meta tag, like here: http://strk.kbt.io/projects/go/libravatar/ (view sources)

The only thing to deal with would be either letting the user decide whether or not to enable the "go-import" tag (which only makes sense with go code) or always making it available.

**Comment by strk** [comment]
Oops sorry, I see it's already implemnted via go-get param as per #1878 (is this  a duplicate of that ticket, btw?)

**Comment by jsevilleja** [comment]
I think it is, yes. Sorry for the duplicate. I'm going to close it and continue on #1878
