### ISSUE TITLE
Assign organisation member to issue

### ISSUE THREAD

**Issue by DeKugelschieber** [gogits/gogs#3163]
- Gogs version (or commit ref): 0.9.13.0318
- Operating system: Ubuntu 14.04 LTS Server
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

## Description

I cannot assign an organisation member to an issue within a repository which belongs to the organisation. The only user listed when trying to assign him is me. I couldn't reproduce it on try.gogs.io. Should I upgrade?

Edit:
The repo has been transfered from my account to the organisation before. I haven't tried that yet on try.gogs.io...

**Comment by DeKugelschieber** [comment]
Additionally organisation members can't see repos which have been moved to the organisation.

**Comment by Unknwon** [comment]
Please upgrade and test again.

**Comment by DeKugelschieber** [comment]
Well I'm on 9.13 and waiting for the next version. I'm not in a hurry :)

**Comment by Unknwon** [comment]
If you can't reproduce on demo site, I'm going to close this...

**Comment by DeKugelschieber** [comment]
Well I couldn't reproduce this on the demo site. I'll try to fix it manually in the database.
