### ISSUE TITLE
Cannot clone repository with `ssh://` in front of url

### ISSUE THREAD

**Issue by cmpis** [gogits/gogs#3165]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.6.1.0325 Beta
- Git version: git version 1.7.10.4
- Operating system: Debian; Linux s2 2.6.32-042stab113.21 #1 SMP Wed Mar 23 11:05:25 MSK 2016 i686 GNU/Linux
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [X] Haven't
- Log gist: https://gist.github.com/cmpis/c52694a40762cbdf15c59a7c48644a7a

## Description
If you try to clone or pull a URL from gogs with `ssh://` it will say the Gogs repository is an "Invalid repository path".

It works without `ssh://`.

**Comment by Unknwon** [comment]
What is your URl?

**Comment by Unknwon** [comment]
Use whatever URL Gogs web UI shows you...
