### ISSUE TITLE
hand in gogs sera when pushing to large repo

### ISSUE THREAD

**Issue by smcquay** [gogits/gogs#3166]
- Gogs version (or commit ref): first noted in c041273dd334fc7a45ca6cb67ea2c2b492c4a5ed
- Git version: git version 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database:
  - [X ] PostgreSQL
- Can you reproduce the bug at http://try.gogs.io:
  - [X ] Yes (provide example URL): https://try.gogs.io/smcquay/go

## Description

When I try to push a commit to a large repo (i.e. the go source tree) and push, I hang here:

```
git commit --amend --no-edit && time git push -f
[issues/15947 4de4004] Match go-import package prefixes by slash
 Author: Stephen McQuay <stephen@mcquay.me>
 Date: Thu Jun 2 23:54:24 2016 -0700
 2 files changed, 60 insertions(+)
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.80 KiB | 0 bytes/s, done.
Total 7 (delta 6), reused 0 (delta 0)
```

And I get a process that hangs around:

    /home/git/src/github.com/gogits/gogs/gogs serv key-23 --config=/home/git/src/github.com/gogits/gogs/custom/conf/app.ini

If I kill the `git push -f` process the `gogs serv` process hangs around, but the push seems to succeed.

I don't know if it's relevant but this repo started out as a mirror. I performed the same operations on try.gogs.io with the smcquay/go.git repo and the pathology only happened after I force-pushed to a branch (see branch issues/15947 on try.g.i)

On my server I ran this and could see stray processes:

    ps aux  | grep gogs | grep serv | grep key

**Comment by BurakDev** [comment]
Duplicate, try using SSH

**Comment by smcquay** [comment]
```

git remote -v                                                               
gogs    git@try.gogs.io:smcquay/go.git (fetch)
gogs    git@try.gogs.io:smcquay/go.git (push)
```

I believe that is a spelling to use ssh, no?

**Comment by BurakDev** [comment]
yes, strange. You use openssh or built-in SSH server ?

**Comment by smcquay** [comment]
On my instance I use openssh.

**Comment by Unknwon** [comment]
Hi, this is duplicated to https://github.com/gogits/gogs/issues/2586
