### ISSUE TITLE
New access rights : only issues

### ISSUE THREAD

**Issue by benoitjupille** [gogits/gogs#3167]
Hi,

I was wondering if it would be a good idea to create a new access right, to authorize a user to see only issues. 

With this functionnality, we could give access to gogs to customers, or beta-testers, but without giving them access to the source code. They can only read / post / edit issues. 

Some thoughts for a "issues-only" user : 

- When he access a repo, only "Issues" and "Wiki" tabs are showing. The tabs "Code", "Commits", "Release" etc... are hidden. 
- Maybe blocking the clone authorization by http for this user ?
- Url to commits in comments are disabled

What do you think about it ?

**Comment by bkcsoft** [comment]
Not sure if duplicate or not, you decide :) #3027

**Comment by benoitjupille** [comment]
Not sure I understand everything, but it seems to be close. :)

I was just thinking about it as a scenario : you create a new user for your customer, assign it to the repo, and set his access to "issues-only". So if you think that's the same, you can close this issue. :)

**Comment by bkcsoft** [comment]
From what I can tell it seems to be the same :)

**Comment by benoitjupille** [comment]
Ok, thanks for that :)
