### ISSUE TITLE
Rocket.Chat webhook: slack failed with: {"success":true}

### ISSUE THREAD

**Issue by beniwtv** [gogits/gogs#3169]
- Gogs version:  0.9.28.0527
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log: 

"[...rc/runtime/asm_arm.s:990 goexit()] [E] slack failed with: {"success":true}
[T] Hook delivery failed: 1053b9b9-2c6f-48c6-8c40-cba5c420ace2"

Hello,

I am using Rocket.Chat and have configured a webhook in "slack" format in Gogs (since Rocket.Chat does support this without much configuration).

Even though the webhook works fine, Gogs thinks it failed, because the body response is "{"success":true}", instead of the "ok" that Gogs seems to expect.

I've been looking at Slack's webhook documentation, and it does not specify what response Slack will return. Instead it only says: "[..] in most cases you'll receive a "HTTP 200 OK" response with a JSON body indicating that your message posted successfully, [...]".

So I feel Gogs should just look at HTTP 200 OK (like it does on the custom format code path), since assuming the response is always going to be the text "ok" seems problematic if Slack changes this.
(As they have not defined the response format, they probably don't expect people to rely on this exact format either).

Anyway, still works, just thought it might confuse people.

**Comment by bkcsoft** [comment]
Got a link to the docs for that quote? :smiley: 

If it's true then we have a bug that should be fixed :laughing:

**Comment by beniwtv** [comment]
Sure, here you go:
https://api.slack.com/incoming-webhooks
(Scroll down to "Handling errors")

**Comment by fsotomsk** [comment]
May be #3254

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3256, please help test on `develop` branch or https://try.gogs.io.

**Comment by beniwtv** [comment]
Seems to work fine now, with the latest compiled version from the repo.
Thanks!

**Comment by bkcsoft** [comment]
Kept open until merged into master :)

**Comment by Unknwon** [comment]
Already in.

**Comment by bkcsoft** [comment]
Hah! Working hard :thumbup:
