### ISSUE TITLE
Markdown code blocks not rendered correctly

### ISSUE THREAD

**Issue by stonewareslord** [gogits/gogs#3171]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.30.0601
- Git version: Unknown
- Operating system: Unknown
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes: https://try.gogs.io/stonewareslord/test/src/master/test.md, source: https://try.gogs.io/stonewareslord/test/raw/master/test.md
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Using the characters `[]:` breaks a code block and renders the entire line and sometimes the next line blank.

**Comment by bkcsoft** [comment]
I'll have a look at this tomorrow, but it's most likely a bug in blackfriday (the markdown-parser/renderer) and not Gogs itself.

**Comment by bkcsoft** [comment]
Yes it's an issue with https://github.com/russross/blackfriday https://gist.github.com/bkcsoft/dce1a2e16db28b46e1ce4c8df18caaba

**Comment by xor-gate** [comment]
@bkcsoft is this reported upstream to `russross/blackfriday` ?, this would be a good idea and cross-reference to this issue also.

**Comment by bkcsoft** [comment]
Not yet, I'll do that now :)

**Comment by xor-gate** [comment]
Define now @bkcsoft :+)

**Comment by bkcsoft** [comment]
@xor-gate "now" as in *now* :trollface: russross/blackfriday#279

Sorry, other issues have had priority :)

**Comment by xor-gate** [comment]
:+1: first things first, good for having this also active upstream.

**Comment by shurcooL** [comment]
Thanks for reporting the bug in blackfriday. I've fixed this in https://github.com/russross/blackfriday/pull/280, so this should no longer be an issue.

You'll need to update to latest version if you're vendoring blackfriday.

**Comment by xor-gate** [comment]
Nice work @shurcooL !!!

**Comment by Unknwon** [comment]
Looks like fixed: https://try.gogs.io/stonewareslord/test/src/master/test.md

**Comment by gsantner** [comment]
Happens still on my gogs. version  0.9.83.0816.

![bildschirmfoto von 2016-08-25 18-29-21](https://cloud.githubusercontent.com/assets/6735650/17977508/4c99f9da-6af2-11e6-9c71-64b9b1f4e8c3.png)

**Comment by shurcooL** [comment]
@gsantner, can you please check if that problem occurs in the latest `master` version of blackfriday?

If so, please report it in that repo. Otherwise, gogs just needs to update the outdated vendored version it's using.
