### ISSUE TITLE
Plans for a new Gogs release

### ISSUE THREAD

**Issue by ronisbr** [gogits/gogs#3172]
Hi guys!

Is there any plans for a new Gogs release? There is some new features committed after the 0.9.13 release that I am really wanting, e.g. https://github.com/gogits/gogs/pull/3000

**Comment by bkcsoft** [comment]
> We DO NOT take **questions** or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Closing with a semi-answer: Author of gogs is currently busy, no idea when the next release will be
