### ISSUE TITLE
Gogs not rendering escaped characters in organisation names correctly. 

### ISSUE THREAD

**Issue by alfiepates** [gogits/gogs#3173]
- Gogs version (or commit ref): v0.9.13
- Operating system: Linux, AMD64
- Database: SQLite

## Description

Simple little bug today. I created an organisation, and then edited an apostrophe (`'`) into the organisation's full name. The name was stored and rendered with a `&#39;` in place of the apostrophe, which isn't exactly the prettiest. 

Prod example at https://git.alfiepates.me/alfies-dotfiles

**Comment by bkcsoft** [comment]
Closing as duplicate of #1937

**Comment by alfiepates** [comment]
Apologies, Search didn't turn anything up. Or maybe I didn't search hard enough, one of the two.
