### ISSUE TITLE
Pull request gives Internal Server Error (500)

### ISSUE THREAD

**Issue by renewsorensen** [gogits/gogs#3175]
- Gogs version (or commit ref): 0.9.13.0319
- Git version: git version 2.5.2.windows.1
- Operating system: Windows Server 2012 R2 Standard
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:
2016/06/07 11:20:44 [T] PullRequest[0].testPatch (patchPath): g:\Git\scada\vob.server.git\pulls\3.patch
2016/06/07 11:20:45 [...routers/repo/pull.go:677 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 128 - fatal: Not a git repository (or any of the parent directories): .git

## Description
I am trying to create a new pull request, this gives me an internal server error 500. Everything works well until i press the button "Create Pull Request", after that i get a big 500 screen. 

http://myserver3000/SCADA/vob.server/compare/release-3.12.0.0...bug-bkv-5265

...

**Comment by renewsorensen** [comment]
I found that deleting the content of tmp fixed the issue.

**Comment by Unknwon** [comment]
Hi, this is a fixed issue in `master` branch.
