### ISSUE TITLE
Including a slash in a wiki page title results in a 404 on saving the page

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3177]
If you include a slash ("/") in a wiki page title, saving the page results in a 404 (unstiled, btw).

**Comment by strk** [comment]
For the record: the slash addition was my attempt at doing a wiki hierarchy (see #3087)

**Comment by Unknwon** [comment]
I think this is basically same to https://github.com/gogits/gogs/issues/3087

**Comment by bkcsoft** [comment]
@Unknwon IMO this is a bug, and while related to #3087, it is not a duplicate. Gogs should not allow for slashes in the wiki-pages name until it has support for  hierarchy. My 2 cents :smiley:

**Comment by Unknwon** [comment]
@bkcsoft I think you won't get 404 anymore on `master`...
