### ISSUE TITLE
LDAP auto register toggle

### ISSUE THREAD

**Issue by jmptbl** [gogits/gogs#3179]
Hello,

It looks like LDAP auto register control was removed in #1625, although the database table field seems to still work.  How do we control that field without querying the database directly?  The feature was useful to us.  Don't understand the motivation for removing it?

**Comment by Unknwon** [comment]
Hi, what is the motivation for having that?

**Comment by jmptbl** [comment]
Our organisation LDAP includes user accounts who shouldn't access our code repositories, so we only enable auto-register when a new user is going to login for the first time.

**Comment by Unknwon** [comment]
.... even if not auto-registered, the user is still able to view the repositories from what I remember.

**Comment by jmptbl** [comment]
Nope, if auto-registration is disabled, an LDAP user can't register, and authentication fails for him.

**Comment by Unknwon** [comment]
But they can still login...

**Comment by jmptbl** [comment]
I see you are right, however it was not like that in the past. It used to block the login too.

**Comment by Unknwon** [comment]
Yeah, so it's not possible anymore.
