### ISSUE TITLE
500 error when attempting to view issues of type 'Mentioning you'

### ISSUE THREAD

**Issue by danherd** [gogits/gogs#3180]
**Gogs version:** 0.9.28.0527
**Git version:** 1.7.10.4
**OS:** Debian 7
**Database:** MySQL 5.6.29
**Can reproduce at http://try.gogs.io:** Yes
**Reproduce URL:** https://try.gogs.io/dannherd/sdfsddsf/issues?type=mentioned&sort=&state=open&labels=0&milestone=0&assignee=0
**Description:** Whenever I attempt to view issues of type 'Mentioning you', it crashes with a 500 error.
**Log line:** 2016/06/08 12:28:15 [...outers/repo/issue.go:185 Issues()] [E] Issues: %v: Error 1052: Column 'is_closed' in where clause is ambiguous

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3269, please help test on `develop` branch or https://try.gogs.io.
