### ISSUE TITLE
Pull request gives 500 error after deleting "base" branch from old pull request

### ISSUE THREAD

**Issue by alpettit** [gogits/gogs#3181]
- Gogs version (or commit ref): 0.9.13.0319
- Git version: 2.8.1.windows.1
- Operating system: Windows Server 2012 R2
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io: https://try.gogs.io/apettit/test500error/
  - [X ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:[E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 1 - Your configuration specifies to merge with the ref 'refs/heads/branch_to_delete'

## Description

You will get a 500 error if you delete a "base" branch of an old pull request.
Reproduction steps

1. Start with one branch "master" with a "test.txt" file
2. Make 2 additional branches "test" and "branch_to_delete" from master and push them
3. Change the contents of test.txtC
4. heck in on "test" branch and push
5. In GOGs create a pull request to merge the branch "test" into "branch_to_delete".  Do not accept or merge pull request at this time.
6. Delete branch "branch_to_delete" (origin/branch_to_delete)
7. In GOGs attempt to create a pull request to merge "test" into "master".  The initial diff will work, but when you click "create pull request" you will get a 500 error.

Additional info:  You also get a 500 error if you try to back into the first pull request to close it.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by alpettit** [comment]
Looks like it is working.  Thanks!
