### ISSUE TITLE
Allow for displaying tabs as 4 spaces

### ISSUE THREAD

**Issue by squarefractal** [gogits/gogs#3182]
Gogs currently shows tabs as `\t`, which is rendered as eight spaces on every browser.

Given that displaying tabs as four spaces is the default in many editors and environments, could there be an option to display them as such?

**Comment by andreynering** [comment]
As I said [here](https://github.com/gogits/gogs/pull/3092#issuecomment-219088923), one possible way is using what is specified in the [.editorconfig file](http://editorconfig.org/). This is how it [work on GitHub](https://github.com/RReverser/github-editorconfig#readme).

**Comment by bkcsoft** [comment]
Could be set as a user-setting as well, with default to the current
behaviour. Regexp replace should be fast enough on page-views :)

**Comment by silverwind** [comment]
The proper way to solve this would be through CSS, so tab characters are preserved:

````
     tab-size: 2 !important;
-moz-tab-size: 2 !important;
````
Could be easily put in a userstyle as well ;)

**Comment by squarefractal** [comment]
@silverwind Why not send in a PR with your proposed solution?

**Comment by Unknwon** [comment]
I think it is more nature to set when Gogs supports custom static resources. (have we already supported somehow?)

**Comment by Unknwon** [comment]
`.editorconfig` could be another kind of support, too. @andreynering would you mind send a PR for this?

**Comment by andreynering** [comment]
@Unknwon I'll try to implement editorconfig support when have a little free time.

But maybe I should wait for the web editor PR first? #3151

**Comment by richmahn** [comment]
@andreynering @Unknwon Yeah, this is something I have worked with and fiddled with in the editing feature, and while I separated the JS call to the Wiki editor from the File editor, they are in the same JS file and similar in function. We can change how tabbing works.

**Comment by andreynering** [comment]
PR for editorconfig: #3241

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by silverwind** [comment]
Looking good!

https://try.gogs.io/silverwind/with-editorconfig/src/master/testtab.js
https://try.gogs.io/silverwind/without-editorconfig/src/master/testtab.js
