### ISSUE TITLE
add xorm.log loglevel settings

### ISSUE THREAD

**Issue by brechsteiner** [gogits/gogs#3183]
Add a config option to set the loglevel from xorm.log. The loglevel default is debug, this is a very bad idea on productive systems.
- Gogs version: 0.8.43-1456609760.d320915.jessie amd64
- Operating system: Debian 8.4
- Database: PostgreSQL

app.ini
[log]
ROOT_PATH =
MODE =
BUFFER_LEN = 10000
LEVEL = Error

[log.console]
LEVEL = Error

[log.file]
LEVEL = Error
LOG_ROTATE = true
MAX_LINES = 1000000
MAX_SIZE_SHIFT = 28
DAILY_ROTATE = true
MAX_DAYS = 7

[log.conn]
LEVEL = Error
RECONNECT_ON_MSG = false
RECONNECT = false
PROTOCOL = tcp
ADDR =

[log.smtp]
LEVEL = Error
SUBJECT = Diagnostic message from serve
HOST =
USER =
PASSWD =
RECEIVERS =

[log.database]
LEVEL = Error
DRIVER = postgres
CONN =

**Comment by redoz** [comment]
This is important, Gogs is writing 100MB/secs sustained to this log file which is causing an abnormal load on my server. It seems to be exasperated by all the "gogs serve" processes writing to the same file, all opening it up with Truncate.

**Comment by redoz** [comment]
![image](https://cloud.githubusercontent.com/assets/1670030/19038056/00590f88-897a-11e6-9868-2a218d9ab829.png)

It's writing almost 400MB/sec sustained to a log file that's 5kB in size, there is something seriously wrong going on here.

**Comment by 0xbaadf00d** [comment]
I agree, in few days, on our corporate environment, this file reach easily 500 Mb. Any chance to have ability to set XORM logger level to Error or Info soon ?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch, see details on https://github.com/gogits/gogs/commit/8a3f4fc616086af121ab0c79aa3a24d30703acc9.
