### ISSUE TITLE
Repository named 'bin' results in error

### ISSUE THREAD

**Issue by uncled1023** [gogits/gogs#3184]
- Gogs version (or commit ref): 1.5.1
- Git version: 1.9.5
- Operating system: Windows Server 2012
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io: 
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Example Url: https://git.teknik.io/shaggytwodope/bin

## Description

If a user creates a repository named **bin**, whenever that repo is viewed, the following error message is displayed: Theresource you are looking for has been removed, had its name changed, or is temporarily unavailable.

I am able to delete the repo fine through the admin portal, but the users cannot delete them as they need to view it to delete it.

**Comment by Unknwon** [comment]
>the following error message is displayed: Theresource you are looking for has been removed, had its name changed, or is temporarily unavailable.

I don't understand this part...

**Comment by firestalk** [comment]
as for now, I see at https://git.teknik.io/shaggytwodope/bin normal repo too

**Comment by uncled1023** [comment]
Can verify it was an issue on my end.  IIS was blocking that directory.
