### ISSUE TITLE
Tmp folder with Window service to add a wiki page

### ISSUE THREAD

**Issue by byzheng** [gogits/gogs#3185]
For bug reports, please give the relevant info:

- Gogs version (or commit ref):  0.9.13.0319
- Git version: 2.5.1
- Operating system: Windows 7
- Database:
  - SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Not relevant
- Log gist:
2016/06/10 15:01:22 [...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage: UpdateLocalWiki: Clone: exit status 128 - fatal: destination path 'data/tmp/local-wiki/14' already exists and is not an empty directory.
## Description
I am running gogs with Windows service. gogs add a data/tmp folder under "C:\Windows\System32\data\tmp\local-wiki" and "C:\Windows\SysWOW64\data\tmp\local-wiki". The tmp folder supposed to under the installed folder of gogs.

**Comment by Unknwon** [comment]
The fail to delete folder on Windows bug is fixed in `master` branch.
