### ISSUE TITLE
派生仓库中创建合并请求404

### ISSUE THREAD

**Issue by 94else** [gogits/gogs#3186]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):
- Git version: git version 2.7.4 (Apple Git-66)
- Operating system: mac os x ei 10.11.4
- Database:
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes   https://try.gogs.io/snow/test1/pulls
- Log gist:

## Description
1.派生一个仓库
2.进入派生的仓库中，仓库设置里勾选 启用合并请求以接受社区贡献
3.合并请求，创建合并请求

...

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
