### ISSUE TITLE
Redis cache doesn't seem to actually do anything

### ISSUE THREAD

**Issue by qbit** [gogits/gogs#3187]
- Gogs version: 0.9.30.0601
- Git version: 2.8.3
- Operating system: OpenBSD-current
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Adding the below to my app.ini file results in no entries in db 1 when listing via redis-cli:

```
[cache]
ADAPTER = redis
HOST = network=tcp,addr=127.0.0.1:6379,db=1,pool_size=100,idle_timeout=180,hset_name=MacaronCache,prefix=cache
```

Checking redis via:

```
$ redis-cli -n 1                                                                                                                                                                                
127.0.0.1:6379[1]> keys *
(empty list or set)
127.0.0.1:6379[1]> 
```

Under `/admin/config` it shows a cache configuration with a 0 second interval.
...

**Comment by clone1018** [comment]
Might be relevant https://github.com/gogits/gogs/issues/2363#issuecomment-169854067

**Comment by Unknwon** [comment]
Answered by @clone1018 ...
