### ISSUE TITLE
Javascript is detected as disabled 

### ISSUE THREAD

**Issue by JocelynDelalande** [gogits/gogs#3191]
Randomly gogs starts telling me « Please enable JavaScript in your browser! » ; then gogs stop working on my browser (as js is a requirement for most actions on gogs).

A browser restart fix the issue.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.15.0323
- Browsers tested, facing the bug :
  - firefox 46 (ubuntu 14.04)
 - iceweasel : 31.7 (Debian Jessie)

**Comment by BurakDev** [comment]
How is possible ? There is <noscript> tag on the message

**Comment by JocelynDelalande** [comment]
I don't know, that's why I'm asking :-) I'm not event telling it's gogs fault, but just noticing that I have the same bug on two different systems.

**Comment by silverwind** [comment]
Sounds like an issue with your browser, `<noscript>` behaviour is not something controllable from the site.

**Comment by JocelynDelalande** [comment]
> Sounds like an issue with your browser, `<noscript>` behaviour
> is not something controllable from the site.

You're probably right, that remains odd, but maybe too much
irrelevant here. Closing, thanks for answers.
