### ISSUE TITLE
Use repository name in repository page html title

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3192]
As of Gogs 0.9.27 the html title for a repository page is set to the repository name followed by the global instance description.
It would be useful instead to use the repository description (and maybe also include the namespace, as done on github).

Compare for example:
https://try.gogs.io/strk/postgis ( html title is "postgis - Gogs: Go Git Service" )
https://github.com/strk/postgis ( html title is "strk/postgis: PostGIS spatial database extension to PostgreSQL" )

**Comment by strk** [comment]
It looks like the HTML title is in this template: templates/base/head.tmpl
How do I know which variables are available in the template ? And how to make more variables available ?

**Comment by clone1018** [comment]
Here's what you're looking for @strk https://github.com/gogits/gogs/blob/master/routers/repo/view.go#L33

**Comment by strk** [comment]
Thanks ! PR ready: #3193

**Comment by odinuge** [comment]
If you look at #2829 , the meta-tag "description" contains what you are looking for. The repo "https://try.gogs.io/strk/postgis" does not have a description, and therefore the meta-tag contains the gogs placeholder info.

Doing the same with the title would also be nice!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3194, please help test on `develop` branch or https://try.gogs.io.

**Comment by strk** [comment]
Fixed on try.gogs.io
