### ISSUE TITLE
Is it possible to change the Gogs HTTP_PORT for the Docker Install?

### ISSUE THREAD

**Issue by oleersoy** [gogits/gogs#3196]
Summary:
http://stackoverflow.com/questions/37872265/is-it-possible-to-change-the-gogs-http-port-for-the-docker-install

Gogs seems like it's hard coded to run on port 3000?  Is this correct?

**Comment by BurakDev** [comment]
Isn't hardcoded. On your app.ini you can edit the value HTTP_PORT to other value. (0-1024 ports require root or special authorization, don't forget that)

**Comment by oleersoy** [comment]
Thanks - I just looked at the Docker log and saw the port 80 could not be bound to as you say.  I'd probably have to do something like this:
http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l

I'll close this issue.  Thanks again.
