### ISSUE TITLE
../../../gopkg.in/gomail.v2/mime.go:7:2: cannot find package "mime/quotedprintable"

### ISSUE THREAD

**Issue by James-Gallagher** [gogits/gogs#3197]
:/home/git/go/src/github.com/gogits/gogs# go build
../../../gopkg.in/gomail.v2/mime.go:7:2: cannot find package "mime/quotedprintable" in any of:
	/usr/local/src/go/src/mime/quotedprintable (from $GOROOT)
	/home/git/go/src/mime/quotedprintable (from $GOPATH)
package github.com/gogits/gogs
	imports runtime: C source files not allowed when not using cgo or SWIG: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c panic.c parfor.c proc.c runtime.c signal.c signal_amd64x.c signal_unix.c stack.c string.c sys_x86.c vdso_linux_amd64.c
package github.com/gogits/gogs
	imports github.com/codegangsta/cli
	imports errors
	imports runtime
	imports runtime/internal/sys: cannot find package "runtime/internal/sys" in any of:
	/usr/local/src/go/src/runtime/internal/sys (from $GOROOT)
	/home/git/go/src/runtime/internal/sys (from $GOPATH)

I can't seem to launch Gogs? Any ideas?

**Comment by nkovacs** [comment]
mime/quotedprintable was added in go 1.5: https://golang.org/doc/go1.5
