### ISSUE TITLE
Versioning consistency across Github, Docker Hub, and Gogs' footer.

### ISSUE THREAD

**Issue by Morpheu5** [gogits/gogs#3198]
I was wondering why the latest release on Github says 0.9.13, while on Docker Hub it's 0.9.30 but then the app I get pulling that image lists 0.9.28.0527 in its footer. This is all very confusing, can someone explain it?

**Comment by YugoCode** [comment]
Is the 0.9.13 binary the latest? I mean it says its from march?
Where can I get the latest binary?
