### ISSUE TITLE
Add option to delete source branch after merge

### ISSUE THREAD

**Issue by rsids** [gogits/gogs#3201]
It would be nice if the source branch could get deleted when a pull request is approved (as an option). Bitbucket & gitlab both offer this feature.

**Comment by alpettit** [comment]
This would be wonderful!

**Comment by steelbrain** [comment]
@tsidei I see you made a commit about this issue a while back, any updates?

**Comment by Unknwon** [comment]
Isn't this already supported... should be closed.

**Comment by steelbrain** [comment]
I'm on v0.9.97.0901 and don't have this, will update and report back

**Comment by Unknwon** [comment]
You might want wait for few days new release next Tuesday. Unless you compile from source code..

**Comment by mkny** [comment]
This will be implemented?

**Comment by unknwon** [comment]
@mkny it is implemented.

**Comment by mkny** [comment]
> @mkny it is implemented.

Correct me if I'm wrong.. But the issue is for deleting a Branch, and you say that is implemented.. But I cant find it. You're sure is for Branching deletion or Pull request deletion?
