### ISSUE TITLE
Feature Request: Direct access to java files (And other resources with no ancestor files)

### ISSUE THREAD

**Issue by oleersoy** [gogits/gogs#3202]
With github java classes that are nested deep in a package hierarchy are directly accessible with two clicks.

For example suppose a module only has one file called `hello.java` located at:
`com/example/module/hello/hello.java`

To get to the hello.java file Gogs makes use click `com` then `example` then `module` then `hello` then `hello.java`.  Github realizes that `hello.java` is the first file in that directory structure and only makes us click on time one `com/example/module/hello` which then lists the contents of the hello package.

**Comment by bkcsoft** [comment]
There's already an issue for this (and IIRC a PR as well)

**Comment by oleersoy** [comment]
Do you have a link to it?  I scanned the PRs and did not see one ...

**Comment by bkcsoft** [comment]
#2818 is the PR :)

**Comment by oleersoy** [comment]
Thanks - I'll link and close this as duplicate:
https://github.com/gogits/gogs/pull/2818
