### ISSUE TITLE
create repo on first push

### ISSUE THREAD

**Issue by vv01f** [gogits/gogs#3204]
## Description

tl;dr: would like to create a repo with a first push to make usage of the ui completely obsolete for publishing a project.

must address:
* [ ] support password authentication as in the normal push process
* [ ] double check existing repo names for the addressed account/group
* [ ] create private repo as default without any more requirements

should address:
* [ ] enforce a LICENSE file for public repo
* [ ] enforce a README file for public repo
* [ ] support pki authentication
* more ideas to come …

ma address:
* [ ] new feature: purge remote repo

**Comment by bkcsoft** [comment]
https://github.com/github/hub - Fork it, change a few endpoints (disable some missing ones), done :trollface:

Serious question though. Why use Gogs if you're not gonna use the UI? (or at least the API)

**Comment by vv01f** [comment]
In my mind it is not about a single user, there are different kinds of users. Some prefer GUI, some prefer CLI. This way it may make things more comfortable for the latter.

**Comment by jhasse** [comment]
What if I misspelled my origin URL?

**Comment by vv01f** [comment]
@jhasse You intend to add a call for drop remote repo? I guess this would be another, although connected, feature.

I do not see a problem in the test case for this feature. Just delete the remote repo and do it again, not necessarily in this order.

**Comment by jhasse** [comment]
Correct me if I'm wrong:

You want that when I do

```sh
git init
git remote add origin https://mygogsserver/foo/bar
// commit ...
git push -u origin master
```

and `foo/bar` doesn't exist, it gets created automatically? But what if `foo/abr` exist and `foo/bar` was just a typo?

**Comment by Unknwon** [comment]
Thanks your feedback! But I would rather recommend you follow https://github.com/gogits/gogs/issues/1062
