### ISSUE TITLE
Preassign domain name on googs install page

### ISSUE THREAD

**Issue by panticz** [gogits/gogs#3205]
Hi, it would by helpful when the domain in "Application General Settings" section on the gogs install page should by preassign with SERVER_NAME variable from webserver instead of "localhost"

```
# Application General Settings
Domain: localhost
Application URL: http://localhost:3000/
```
Tested with
gogs version: 0.9.28.0527
OS: Ubuntu (Installed from package)

**Comment by Unknwon** [comment]
Does `SERVER_NAME` some kind of standard?

**Comment by panticz** [comment]
I m not realy familiar with Go but as far i can see is this variable also avaiable in go (see line 122):
https://golang.org/src/net/http/cgi/host.go
see also PHP documentation: http://php.net/manual/en/reserved.variables.server.php

**Comment by Unknwon** [comment]
>I m not realy familiar with Go but as far i can see is this variable also avaiable in go (see line 122):
https://golang.org/src/net/http/cgi/host.go

I think you did not look it carefully...
