### ISSUE TITLE
Newlines in commit message when referenced to issue are not properly rendered

### ISSUE THREAD

**Issue by xor-gate** [gogits/gogs#3206]
- Gogs version (or commit ref): 0.9.30.0601 (and older self-hosted 0.9.13.0318)
- Git version: n/a
- Operating system: n/a
- Database: n/a
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes, https://try.gogs.io/admin1/testnewlines_in_reference/issues/1
## Description

When referencing a issue from a commit message where multiple lines are seperated with a newline character (\n, under linux). Then the whole message is flattend onto one single which looks ugly when using ascii lists, diagrams etc.

See screenshots below:

![2016-06-24 12_15_15-settings](https://cloud.githubusercontent.com/assets/1050166/16335155/6d8a2700-3a05-11e6-968d-5aae45e56ba2.png)
![2016-06-24 12_15_28-settings](https://cloud.githubusercontent.com/assets/1050166/16335154/6d8a12c4-3a05-11e6-8a9f-bcb239d69740.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

For new commit references, only title of commit message will be shown. People can just click on the link and see the full commit body.
