### ISSUE TITLE
OS X binary - Segmentation fault: 11

### ISSUE THREAD

**Issue by iEFdev** [gogits/gogs#3211]
I tried the `gogs_v0.9.13_darwin_amd64.zip` binary file… When running, it returns an error.

	$ ./gogs web
	Segmentation fault: 11

What are the OS X sys requierments? (I use 10.7.5)

- - -

_Using “build from source” works fine, no sqlite3 though so I'll look at using the `-tags` installation option._

**Comment by Unknwon** [comment]
I think your OS X is too low, at least 10.8 to use compiled binary, and I don't have that low version to compile.

So... you would have to compile from source code.
