### ISSUE TITLE
Add a vendor/ submodule

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3214]
A vendor/ directory lets you publish specific versions of dependencies.
See https://blog.gopheracademy.com/advent-2015/vendor-folder/

Registering it as a submodule allows users to opt-out of them to get the dependencies from their source (for development purpose, for example).

The use of vendor was first proposed on the forum to get reproducible builds:
https://discuss.gogs.io/t/proposal-do-vendoring-for-reproducible-builds/178/5

It would also solve the problem of dependencies availability so not limit dependencies to those which are available from github.com (see https://github.com/gogits/gogs/pull/3115#discussion_r68599262 for example)

This proposal was made into an issue to gather votes/reactions. \cc @andreynering, @Unknwon

**Comment by tboerger** [comment]
Submodules aren't a solution for reproducible builds, if the repo is not available or have been deleted the build is broken, than you can keep it directly like it is

**Comment by strk** [comment]
@tboerger maybe I wasn't clear, my proposal is for a _single_ submodule pointing to github.com/gogits/gogs-dependencies, so avaialbility woudl be exactly the same as the one for gogits/gogs. It's a submodule ONLY to let developers choose to build with the newest version of all deps.

**Comment by tboerger** [comment]
That doesn't make sense at all to me.

**Comment by strk** [comment]
@tboerger talking with @Unknwon in chat I understood his goal was to make `go get github.com/gogits/gogs` have the least point of failures. For this reason he limits the dependencies to those hosted on GitHub and BitBucket (https://github.com/gogits/gogs/pull/3115#issuecomment-228786460); but he also accepts pointing to dependencies via gopkg.in (which redirects to github.com), and he also include dependencies from golang.org. This approach counts at least 4 point of failures at build time (github.com, bitbucket.com, golang.org or gopkg.in being down). Additionally, all dependencies can be updated independently from Gogs, adding another point of feailure for each and every dependency, which may break the API unexpectedly.

Using a vendor/ directory would reduce points of failure to just one: github.com being down.
This is because specific versions/snapshots of each dependency would be hosted on the same facility as the main codebase (github.com, in this case). This is the case for both using or not using one or more submodules for holding dependencies, as long as the submodules point to repositories on github.com itself.

If it still doesnt' make sense please ask specific questions.
