### ISSUE TITLE
Support binary (non-image) attachments on issues

### ISSUE THREAD

**Issue by mappu** [gogits/gogs#3215]
Hi,

Right now, images can be attached to issues. Then there's an `<img src` with the same target as the `<a href`. It works great for jpeg/png. But it works badly for other file types (zip/tar, deb, pdf, exe).

It would be good to have full support for uploading binary (non-image) attachments on issues.

Related issues:
- #3065 for attachment icons
- #698 / #1614 for general handling of uploaded binaries

**Comment by andreynering** [comment]
Have you tried `*/*` on the `ALLOWED_TYPES` config on `app.ini`?

https://gogs.io/docs/advanced/configuration_cheat_sheet#attachment-(attachment)

**Comment by mappu** [comment]
Yes, that was necessary for binary uploads to succeed at all. But when they do upload, then, there's an `<img src` to the same target - it's crazy and meaningless when the uploaded file was e.g. a 50MB zip file.

I suppose that's a more specific description of the issues i faced when trying to use this feature.

**Comment by andreynering** [comment]
I see. So you just want `target="_blank"`?

**Comment by mappu** [comment]
I want the 50MB zip file attachment to not be sent to the browser via `<img src`.
I want some adequate replacement for the `<img` tag, when the uploaded attachment was not an image.

`target="blank"` would be nice on the `<a>`, but i didn't check if it was there already.

**Comment by mappu** [comment]
In https://github.com/gogits/gogs/blob/master/templates/repo/issue/view_content.tmpl#L42 

All attachments are treated as images since there is an `<img src` tag here. If i upload a non-image attachment, it is treated as an image regardless, the browser wastes time and bandwidth attempting to parse a 50MB zip file as if it were an image.

There is already a `target="blank"`, so that's fine.

**Comment by andreynering** [comment]
@mappu OK, sorry for the misunderstanding. This should not be hard to fix, we could whitelist some extensions (.jpg, .png, etc) to add the img tag or add a link instead.

**Comment by bkcsoft** [comment]
@andreynering or just allow `image/*` :)

**Comment by andreynering** [comment]
@bkcsoft Good idea. I think both would work.

**Comment by andreynering** [comment]
PR for this: https://github.com/gogits/gogs/pull/3311

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
