### ISSUE TITLE
Windows-styled directory delimiters in a dumped zip-archive

### ISSUE THREAD

**Issue by morrah** [gogits/gogs#3216]
- Gogs version: 0.9.13
- Operating system: Windows 7  

Command ```gogs dump``` on Windows creates a zip-archive that uses ```\``` delimiters instead of ```/```, so there are problems unpacking it on Linux:
```
$ unzip gogs-dump-1467111811.zip 
Archive:  gogs-dump-1467111811.zip
   creating: custom/
   creating: custom\conf/
  inflating: custom\conf\app.ini     
  inflating: gogs-db.sql             
  inflating: gogs-repo.zip           
   creating: log/
  inflating: log\gogs.log            
  inflating: log\gogs.log.2016-06-28.001  
  inflating: log\http.log            
  inflating: log\xorm.log
```

**Comment by bkcsoft** [comment]
@Unknwon the bug is here: https://github.com/Unknwon/cae/blob/master/zip/zip.go#L196

It should be
```
file.absPath = strings.Replace(absPath, "\\", "/", -1)
```

Not entirely sure how that lib works, so `file.Name` might need the same `replace` :smiley:

**Comment by Unknwon** [comment]
Please `go get -u github.com/Unknwon/cae` and recompile Gogs.
