### ISSUE TITLE
Overspecific validation of SMTP auth user on install page

### ISSUE THREAD

**Issue by ncadou** [gogits/gogs#3220]
- Gogs version (or commit ref): 0.9.30.0601
- Git version: official gogs docker image
- Operating system: official gogs docker image
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
## Description

Upon firing up a brand new gogs instance, on the installation page, filling out the sender email field (`smtp_email`) from the email service settings section with anything other than an email address results in a validation error.

This is incorrect because some SMTP servers (e.g. WebFaction's,) use short usernames instead.

The workaround is to make up an email address in that field for the sake of finishing the installation process, to enter the docker container (in my case), manually modify `mailer.USER` in `app.ini`, and restart the container. A needlessly cumbersome way to get things going.

**Comment by Jonny007-MKD** [comment]
Yeah, I mentioned that in #2777, too.

The user name (`mail.USER`) doesn't have to be an email address, whereas the sender does.

**Comment by Unknwon** [comment]
I think this fixed in `master`.
