### ISSUE TITLE
wiki 标题含义 # 可以建立但不可以编辑提交

### ISSUE THREAD

**Issue by zanjs** [gogits/gogs#3221]
由于建立了 有 # 号标题的 wiki  编辑不了 也删除不了 ，链接的 是 SQLite，wiki 在哪张表里

**Comment by Unknwon** [comment]
Hi, this is duplicated to https://github.com/gogits/gogs/issues/3021 .

There is no table for wiki, you can clone to local and delete file, commit and push.
