### ISSUE TITLE
LDAP authentication fails repeatedly, then goes though

### ISSUE THREAD

**Issue by wsw70** [gogits/gogs#3223]
- Gogs version (or commit ref): `0.9.30.0601`
- Git version: `2.6.6`
- Operating system: `Debian`
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Gogs is configured to authenticate against an Active Directory via LDAP. The authentication process fails in ~50% of the cases with the log

```
2016/06/30 09:01:55 [...gogs/models/login.go:267 LoginUserLDAPSource()] [E] LDAP Connect error, ldap.my-ldap-server-here.com:
LDAP Result Code 200 "": read tcp 172.17.0.2:55326->10.81.180.7:636: read: connection reset by peer
```

After trying a few times the connection goes though. The LDAP endoint is HA F5 device which serves LDAP services to an extensive range of clients and the LDAP query works flawlessly from them. This is to say the the issue is not likely to be on the server side.

**Comment by Unknwon** [comment]
From what I experienced, whenever `read: connection reset by peer` occur, that means server declined the request, possibly too many requests and it has to kill some of them.

**Comment by wsw70** [comment]
The problem is that this F5 is serving thousands of connections and only the ones from gogs fail

**Comment by Unknwon** [comment]
http://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean
