### ISSUE TITLE
Re-write UI in React.js

### ISSUE THREAD

**Issue by DenisIzmaylov** [gogits/gogs#3226]
Dear, nowadays React.js is close to be a standard for UI in JavaScript. It will takes a possibility to quick growth and cheap maintenance. A lot of already-done solutions with great quality.

**Comment by Xe** [comment]
Gogs is not facebook, you don't need react. Even using jQuery can be overkill. Maintainers please ignore this ticket.

**Comment by DenisIzmaylov** [comment]
So agressive.
React can provide extendable UI layer which allow to make Gogs is more like platform to customize according to business needs.

**Comment by andreynering** [comment]
I dislike this proposal. This would require more maintenance, and I am not sure of the benefits.

We have to remember that many people know HTML, but just a few know React. The may keep away new contributors.

> It will takes a possibility to quick growth and cheap maintenance.

I don't think the statement above is true. I know React and it is not easy to learn for beginners. (This is why I prefer [VueJS][vuejs], but static HTML, when enough, is even better).

It's a possibility to add more interaction just to some pages, though.

[vuejs]: https://vuejs.org

**Comment by bkcsoft** [comment]
When Gogs JSON-API is fullt implemented one could write their own frontend, so I'd push for that instead if I were you :)

**Comment by DenisIzmaylov** [comment]
Great. Disagreed with those people who declined React.js because is really biggest UI ecosystem (have a look at jobs trends). React.js code is best for maintenance ever.

But it seems the best idea to keep MSA way. And seperate Gogs as a web service and UI service. Like [Concourse](https://github.com/concourse/concourse).

**Comment by xor-gate** [comment]
You cant just request a complete rewrite to a different framework because X or Y is better at A and B. This will take many many man hours. Keep in mind there are only a few core-developers with limited time.

**Comment by Unknwon** [comment]
I would rather write in VueJS... after 1.0 release...
