### ISSUE TITLE
500 error after rename repository because of path change

### ISSUE THREAD

**Issue by pwFoo** [gogits/gogs#3228]
There is a warning that path will change during rename a repository, but after repo name is changed the user shouldn't get served an 500 error. User should be redirected to the new url instead of the old one.

**Comment by Unknwon** [comment]
Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by pwFoo** [comment]
Renamed repo from settings and get an 500 error message after save and page reload.

**Log**
`2016/07/02 09:13:07 [...ters/repo/setting.go:118 SettingsPost()] [E] SaveAddress: Load: open /data/git/gogs-repositories/<GOGS-USERNAME>/<GIT-REPO-NAME>.git/config: no such file or directory`

Running gogs docker image inside a container.

https://discuss.gogs.io/t/500-error-after-rename-repository-because-of-path-change/449

**Comment by lstahlman** [comment]
I could reproduce this. ctx.Repo.Mirror's Repo reference is not updated on the repository name change, so when SaveAddress is called it attempts to look up the git config path using the old name.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3276, please help test on `develop` branch or https://try.gogs.io.
