### ISSUE TITLE
Repositories named '..' and '.' cannot be entered.

### ISSUE THREAD

**Issue by Tmplt** [gogits/gogs#3229]
- Gogs version (or commit ref): `0.9.13`
- Git version: `2.9.0`
- Operating system: Arch Linux
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes: https://try.gogs.io/Tmplt
  - [ ] No
  - [ ] Not relevant
- Log gist: I was unable to find a log which mentioned the created repositories.

## Description
If I create a repository named `..` or `.`, trying to enter them will instead direct me to `git.hostname.tld`, respectively `git.hostname.tld/<repo owner>`.

These repositories can, however, be pushed to with `git`.

**Comment by Unknwon** [comment]
Hi, I think it is browser's automatic behavior, should we disable such names?

**Comment by bkcsoft** [comment]
Yes we should disallow such names :)

**Comment by Unknwon** [comment]
It's now fixed on `develop` branch.
