### ISSUE TITLE
Translate deletion notices

### ISSUE THREAD

**Issue by phtan** [gogits/gogs#3231]
After issue #2863 , one expects that the deletion notices will reflect the new behaviour. However, the deletion notices explain the old behaviour, which is the following:

> If this repository is public, all forks will become independent after deletion.
>  If this repository is private, all forks will be removed at the same time.
> If you want to keep all forks after deletion, please change visibility of this repository to public first.

(from https://github.com/gogits/gogs/blob/7049cb9d975505a6f1fa3fad809dd92c1078360f/conf/locale/locale_en-US.ini#L604 )

I suggest a new deletion notice: ' All forks will become independent after deletion '

This requires a translation across all the locales.

**Comment by Unknwon** [comment]
@phtan you only need to change in `en-US`. Please do that in your PR.

**Comment by phtan** [comment]
By PR, you mean my existing PR (https://github.com/gogits/gogs/pull/3232 ) right?

**Comment by Unknwon** [comment]
Yes

**Comment by Unknwon** [comment]
I think you just remove the existing one and modify it to what you proposed above.

**Comment by phtan** [comment]
@Unknwon done
