### ISSUE TITLE
Repository names with dots cause internal server error

### ISSUE THREAD

**Issue by letorbi** [gogits/gogs#3242]
I have some repositories that contain dots (".") in their name. This worked once (dunno what version, but AFAIK I've accessed the repos last time in March or April), but getting the repository (`GET https://gogs.letorbi.de/letorbi/reds.web`) now causes a 500 error response.

I'm using version 0.9.28.0527.

**Comment by Unknwon** [comment]
Please reproduce one on https://try.gogs.io as required.

**Comment by letorbi** [comment]
Sry for not reading the requirements - I was in a hurry when posting this issue. I'm unable to reproduce the bug neither on try.gogs.io nor on my own system today. The latter is strange, but anyway. I'm closing this issue and start feeling stupid instead ;)

**Comment by Unknwon** [comment]
:joy:
