### ISSUE TITLE
中文用户名

### ISSUE THREAD

**Issue by chywu** [gogits/gogs#3245]
可否增加中文用户名和仓库名。我们想用GOGS管理一些二进制文件，做一些简单的版本控制管理，库比较多，人员也比较多，全用英文看起来眼花缭乱，如果能支持用户名和仓库名中文就好了。谢谢

**Comment by Unknwon** [comment]
Hi, we have no plan to support this kind of feature, you could use Pinyin with dot (e.g. jinping.xi) instead :).
