### ISSUE TITLE
[feature] Support custom profile photo at the commits page

### ISSUE THREAD

**Issue by arno01** [gogits/gogs#3247]
- Gogs version (or commit ref):
0.9.37.0708 / in docker

- Database:
  - [x] PostgreSQL

## Description

It would be good to have custom profile photo support at the commits page in case when user chooses a custom profile photo. Currently it points to the gravatar.

Thanks!

P.S.
I am new to Gogs (just installed), I might have overlooked something.

**Comment by Unknwon** [comment]
Can you give screenshots for exmaple?

**Comment by arno01** [comment]
@Unknwon here you go:

![tt](https://cloud.githubusercontent.com/assets/3791945/16709478/1dc463d4-4612-11e6-88f1-b2209a6ae1ae.png)

![tt2](https://cloud.githubusercontent.com/assets/3791945/16709481/24e46222-4612-11e6-8e39-ed8b21853c79.png)

**Comment by Unknwon** [comment]
I think you do not have same email address?

**Comment by arno01** [comment]
@Unknwon Humm... that explains everything!
Thank you very much for the great product! :-)
