### ISSUE TITLE
[feature] Activate/Deactivate Explore

### ISSUE THREAD

**Issue by berkutta** [gogits/gogs#3248]
Couldn't find any option to deactivate the Explore Tab completely or only things like the user list in the Explore Tab.

**Comment by Unknwon** [comment]
What is the purpose of deactivate explore?

**Comment by berkutta** [comment]
I want to give users access to a repository which don't want to publish their e-mail address together with it's name to the internet. Would be nice to deactivate the user list in the explore.

**Comment by Unknwon** [comment]
You can force any visiter login before view anything by https://github.com/gogits/gogs/blob/master/conf/app.ini#L143

**Comment by blamh** [comment]
For future reference:
```ini
[service]
REQUIRE_SIGNIN_VIEW = true
```

https://github.com/gogits/gogs/blob/4b25bdfbc45479d64e3ffb04abbd08672ccc47fb/conf/app.ini#L143

**Comment by Sfinx** [comment]
The users, commits, cimments and repository names still exposed to public. With REQUIRE_SIGNIN_VIEW = true Explore link **must be** disabled until user not logged in.

**Comment by Sfinx** [comment]
oops, builded wrong commit. please ingore previous

**Comment by tomkcook** [comment]
I'm using the `gogs/gogs` docker image and have set `REQUIRE_SIGNIN_VIEW = true` in `app.ini` (actually set it through the install page that comes up when you first connect to the container).  But the explore page is still visible and I can still see users and non-private repositories as a non-signed-in guest.

**Comment by Unknwon** [comment]
@tomkcook hmm.. this option only works after restart Gogs..

**Comment by tomkcook** [comment]
Ah, thanks.  That's done it.

**Comment by Unknwon** [comment]
@gocursor I think it is not possible right now. I'm not sure if there is any issue about this request exists, you can file a feature request if not found any.

**Comment by gocursor** [comment]
I thought this issue is a feature request for disabling/deactivating the "Explore" page, because the name is "[feature] Activate/Deactivate Explore". Please let me know if this is not the case (then I will create a new feature request as a new GitHub issue).

**Comment by Unknwon** [comment]
@gocursor hmm, since it's closed, better to have a new one...

**Comment by gocursor** [comment]
Issue created (#5080).

**Comment by konohanaruto** [comment]
> For future reference:
> 
> ```ini
> [service]
> REQUIRE_SIGNIN_VIEW = true
> ```
> 
> https://github.com/gogits/gogs/blob/4b25bdfbc45479d64e3ffb04abbd08672ccc47fb/conf/app.ini#L143

Thank you very much! It works for me.

**Comment by ramosisw** [comment]
> @tomkcook hmm.. this option only works after restart Gogs..

That's right
