### ISSUE TITLE
 How do you close an issue without referencing it via a commit?

### ISSUE THREAD

**Issue by vonHabsi** [gogits/gogs#3257]
Is there a button or link in the UI that marks an issue as closed?

I can't see one in the UI.

Using a commit to mark an issue as closed feels odd as it requires to make an arbitrary change to the code in for the sake of a commit.

I have asked this question at https://discuss.gogs.io/t/473 but haven't got a response

**Comment by andreynering** [comment]
It's at the bottom of the screen. If you can't see it, maybe it's due permission?

![1](https://cloud.githubusercontent.com/assets/7011819/16767451/ebc05cc0-4815-11e6-8190-077cffdf7127.png)

**Comment by vonHabsi** [comment]
Seen it, thanks.
How do you as 'fixed', 'won't fixed', 'needs more info', etc as well, ie additional info besides the fact that it is closed?

**Comment by andreynering** [comment]
Use labels. Go to `/user/project/labels` URL to see them. (E.g. https://try.gogs.io/andreynering/gogs/labels)

You can pin labels in issues/PRs.
