### ISSUE TITLE
/bin/bash in hooks = error: failed to push some refs

### ISSUE THREAD

**Issue by bartlomiej-kurek** [gogits/gogs#3259]
Pushing repository fails due to update hook having shebang set to #!/usr/bin/env bash.
On some systems (e.g. FreeBSD) bash is not installed in default configuration, and it should not be required for such a simple command as:
"/usr/home/git/gogs/gogs" update $1 $2 $3 --config='/usr/home/git/gogs/custom/conf/app.ini'

**Comment by Unknwon** [comment]
What `-sh` do you have if you don't have `bash`?

**Comment by bkcsoft** [comment]
@Unknwon plain old `sh` :trollface:

**Comment by bartlomiej-kurek** [comment]
Hi, on FreeBSD there's just /bin/sh.
-r-xr-xr-x  1 root  wheel  142184 Nov 26  2014 /bin/sh

On Ubuntu /bin/sh is dash:
lrwxrwxrwx 1 root root 4 Jul  8 21:47 /bin/sh -> dash*

I can easily think that different people have ksh, zsh, and whatever they like.
That's why the shell is always linked to /bin/sh, and this it the one that should be used.
The problem with bash is "bashism", if you write the scripts using bash extensions then they are not standard compliant

**Comment by Unknwon** [comment]
Change https://github.com/gogits/gogs/blob/master/conf/app.ini#L13 to `sh` should solve your problem.

**Comment by bartlomiej-kurek** [comment]
Yes, it solved the problem, thank you. And you meant custom/conf/app.ini, right?
I tried with the default conf/app.ini and it didn't propagate (still got bash).

**Comment by Unknwon** [comment]
>Yes, it solved the problem, thank you. And you meant custom/conf/app.ini, right?

Yes..
