### ISSUE TITLE
Large directories - long time or 504 error

### ISSUE THREAD

**Issue by lenisko** [gogits/gogs#3264]
- Gogs version (or commit ref): 0.9.28.0527
- Git version: 2.1.4
- Operating system: Debian x86_64
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
When entering large directory I'm getting **504 Gateway Time-out**. 
Created mirror of youtube-dl on try.gogs.io seems to work in there (mine gives 504) but it takes very long time.
https://try.gogs.io/lenisko/youtube-dl/src/master/youtube_dl/extractor

**Comment by BurakDev** [comment]
![image](https://cloud.githubusercontent.com/assets/3963184/16802968/cc3a50c4-4903-11e6-9a54-8d87b5ea0097.png)

What do you think about this ? Can be a nice feature.

**Comment by lenisko** [comment]
I was rather thinking that there might a bug in code, so that's why it's taking so long to load.
But if there is not bug, this might be only one option.

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/1518

**Comment by bkcsoft** [comment]
Agreed

**Comment by Unknwon** [comment]
@BurakDev please repost your advice to #1518 :)

**Comment by martijintro** [comment]
same problem here

**Comment by martijintro** [comment]
`same problem (504) here when i use a migration with "mirror" option`


...i opened a new case:

https://github.com/go-gitea/gitea/issues/8250
