### ISSUE TITLE
Invalid csrf token

### ISSUE THREAD

**Issue by oleersoy** [gogits/gogs#3270]
If I leave a page open for a while and create an issue, I get a `Invalid csrf token` message.  I then open fresh gogs page at the same URL and I can then submit the issue.

So it seems that all that is needed is a new authentication token.  Is there a way for Gogs to realize that I have not logged out and should not need to get a new token ....

**Comment by Unknwon** [comment]
Hi, your Gogs version is too old.

**Comment by oleersoy** [comment]
Has the gogs docker image been updated with the fix?

**Comment by Unknwon** [comment]
I don't know what to say based the context you give..

**Comment by oleersoy** [comment]
I scanned the Gogs docker github commits at:
https://github.com/gogits/gogs/tree/master/docker

It looks like most of them are 5 months old, so I'm just curious as to whether the Docker container downloaded from Docker Hub:
https://hub.docker.com/r/gogs/gogs/

Has been updated to include the fix.

I'm also getting some other strange behavior WRT using SSH keys.  On a new repository that I recently commited, Gogs asks me for a username and password when I try to clone it, but it does not ask me for this for other repositories ... so it seems like my SSH key is working for some repositories only ...

**Comment by Unknwon** [comment]
Just use latest version should be fine.

**Comment by oleersoy** [comment]
OK Cool - Thanks

**Comment by oleersoy** [comment]
Started a new one - Noticing that the response time on UI clicks is much faster.  Nice!

**Comment by Unknwon** [comment]
I can't say anything based the context you provide.

**Comment by oleersoy** [comment]
Well you could just leave the ticket open until someone investigates it.

**Comment by Unknwon** [comment]
See https://github.com/gogits/gogs/issues/1891

**Comment by oleersoy** [comment]
OK - I put in an additional observation in that issue.  I'll just comment there as I become aware of more scenarios that trigger the behavior.
