### ISSUE TITLE
API Commit "author" is actually the committer

### ISSUE THREAD

**Issue by hrobertson** [gogits/gogs#3271]
- Gogs version: 0.9.42.0712
- Reproduced at http://try.gogs.io:
https://try.gogs.io/api/v1/repos/hamish.robertson/committer-test/branches/master

Git commits can have a different author and committer.
In the Gogs web interface the author of a commit is shown correctly.
The issue is that retrieving the commit via the API shows the committer's name and email in a property called `"author"`.

**Reproduction**
I created a repo here https://try.gogs.io/hamish.robertson/committer-test
I made one commit:
Author: `test-author <test-author@example.com>`
Committer: `test-committer <test-committer@example.com>`

`GET https://try.gogs.io/api/v1/repos/hamish.robertson/committer-test/branches/master?token=xxx` (where xxx is my token)

```
{
  "name": "master",
  "commit": {
    "id": "a60eed9ab3bcbb8e7f5a06afe8c6a6825fae97b6",
    "message": "A commit with different author and committer\n",
    "url": "Not implemented",
    "author": {
      "name": "test-committer",
      "email": "test-committer@example.com",
      "username": ""
    }
  }
}
```

1. I would expect the `"author"` property to contain details of the author, not the committer.
2. Ideally there would be another property `"committer"` with the name and email of the commiter.

**Comment by lstahlman** [comment]
I can pick this up if @bkcsoft doesn't have time for it.

**Comment by lstahlman** [comment]
@Unknwon and @bkcsoft do you mind if I submit a PR for this? I have a proposal for fixing the bug and filling out the author/committer metadata for both the API and webhooks.

**Comment by Unknwon** [comment]
@lstahlman please go ahead :)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by hrobertson** [comment]
Works as expected:

`GET https://try.gogs.io/api/v1/repos/hamish.robertson/committer-test/branches/master?token=xxx`
```
{
  "name": "master",
  "commit": {
    "id": "a60eed9ab3bcbb8e7f5a06afe8c6a6825fae97b6",
    "message": "A commit with different author and committer\n",
    "url": "Not implemented",
    "author": {
      "name": "test-author",
      "email": "test-author@example.com",
      "username": ""
    },
    "committer": {
      "name": "test-committer",
      "email": "test-committer@example.com",
      "username": ""
    },
    "timestamp": "2016-07-14T04:58:34-04:00"
  }
}
```
