### ISSUE TITLE
Valid link for XMPP

### ISSUE THREAD

**Issue by chteufleur** [gogits/gogs#3272]
Hi,

It would be great to add `xmpp:` as a valid link beside `http:` or `mailto:`.
See [http://wiki.xmpp.org/web/XMPP_URIs](http://wiki.xmpp.org/web/XMPP_URIs).

Thanks for your great work.

**Comment by Unknwon** [comment]
Please give context of what you're talking about...

**Comment by chteufleur** [comment]
Ho yes, sorry.

Talking about link in markdown like README.md file or issue. It is possible to make a link like this : `[link](mailto://toto@example.org)`.
It could be usefull to add XMPP link `[link](xmpp://toto@example.org)`.

**Comment by Unknwon** [comment]
Please follow issue template to reproduce on demo site.

**Comment by bkcsoft** [comment]
See Custom Schemes under `[markdown]` in `app.ini`

**Comment by chteufleur** [comment]
Great ! Thanks guys.
