### ISSUE TITLE
v0.9.46 missing release binaries

### ISSUE THREAD

**Issue by gramakri** [gogits/gogs#3277]
Some binaries including linux_amd64 are missing at https://github.com/gogits/gogs/releases/tag/v0.9.46

Thanks for the release! :tada:

**Comment by Unknwon** [comment]
I don't have enough machines and no good internet to setup VMs yet, will upload ASAP.

**Comment by BurakDev** [comment]
@Unknwon What do you think about create a building platform like jenkins ?

**Comment by Unknwon** [comment]
@BurakDev I need native system to compile, so Jenkins might not help.

**Comment by techzilla** [comment]
What about doing some build/release enginering  for the project, or allowing a devops systems engineer to work with you to clean up some of the practices.  We do that, and you can get automated builds and release, and even packaging anywhere you wanted.. or manual, and it would be perfect every time.

**Comment by xor-gate** [comment]
Vagrant can be used to build machines and could be jenkins nodes which are controlled from a jenkins master. Probably Gogs can use a build/test system the same as Syncthing does (https://docs.syncthing.net/dev/infrastructure.html).

**Comment by Xe** [comment]
I have found that https://drone.io combined with Gogs works extremely well for CI for git repos.

**Comment by gramakri** [comment]
@Unknwon thanks for adding them!

**Comment by xor-gate** [comment]
Also thanks from me 👍
