### ISSUE TITLE
Gogs 0.9.46 GlobalInit() error 

### ISSUE THREAD

**Issue by BoboTiG** [gogits/gogs#3278]
As there is an error 500 when connected on https://discuss.gogs.io, I post my issue here.

- Gogs version (or commit ref): 0.9.46
- Git version: 2.1.4
- Operating system: Raspbian on Raspberry Pi 2
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [d6c3f73707f23a372453b1f49bfc0e7c](https://gist.github.com/BoboTiG/d6c3f73707f23a372453b1f49bfc0e7c)

## Description

After I upgraded from 0.9.13 to the latest stable 0.9.46 (downloaded on [dl.gogs.io](https://dl.gogs.io/gogs_latest_linux_arm.zip)), I am not able to start Gogs anymore. Before or between the upgrade, the OS does not change, no system upgrade nor configuration modifications.

This is my `app.ini` (that does not change too):
```conf
[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = root
PASSWD   =
SSL_MODE = disable
PATH     = /home/git/gogs/data/gogs.db
```

**Comment by Unknwon** [comment]
raspi2 version is not available yet, https://gogs.io/docs/installation/install_from_binary says very clear about which version support what...
