### ISSUE TITLE
email notification for new issue does not have issue author as From

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3279]
The "From" header of email notification triggered by the creation of a new issue is set to the generic system From rather than being the name of the issue author. This happens as of version 0.9.27.0512

**Comment by Unknwon** [comment]
Please upgrade to latest version and report, things are changed a bit after 0.9.27

**Comment by strk** [comment]
I've just tried on try.gogs.io and got the same behavior.
The email I received for a new test issue:

```
  Date: Mon, 18 Jul 2016 06:19:36 -0400
  From: gogitservice@gmail.com
  To: xxxxx
  Subject: [test1] test (#2)

  test2

  ---
  View it on Gogs ( https://try.gogs.io/strk/test1/issues/2 ) .
```

You can see the "From" line is `gogitservice@gmail.com` instead
of `strk2`, which is the issue creator

**Comment by strk** [comment]
For the record, try.gogs.io runs Gogs 0.9.46.0717 at the time of the
test

**Comment by strk** [comment]
The same happens with pull requests (only tested with 0.9.27.0512)

**Comment by strk** [comment]
I confirm it still also happen with pull requests as of 0.9.46.0717

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch. You can't test on https://try.gogs.io because GMail seems not allow such modification.

**Comment by Unknwon** [comment]
Was using wrong value, now showing user name on FROM as well as on demo site.
