### ISSUE TITLE
cannot clone git whose repo's suffix is ".wiki", like "abc.wiki"

### ISSUE THREAD

**Issue by liuyang1** [gogits/gogs#3280]
- Gogs version (or commit ref): v0.9.0
- Git version: -
- Operating system: linux
- Database: sqlite
- Can you reproduce the bug at http://try.gogs.io: not try
- Log gist:

## Description
I have a repo whose name is "abc.wiki" style. fail to clone it.
when I rename it to "abc_wiki", then it works well everywhere.

I think there should be a bug, for example try to check wiki of this repo.

**Comment by liuyang1** [comment]
check logic in cmd/serve.go 164-170line.
It assume every repo which name's suffix is ".wiki" is a wiki repo.

It's wrong.

at least, need try both these two conditions:

- it's a wiki repo.
- it's a normal repo, but name have ".wiki" suffix by user.

**Comment by Unknwon** [comment]
There is no way to tell when you use `.wiki` as repo name suffix, so I think we should disallow such repo name.

**Comment by liuyang1** [comment]
That's OK.

github forbid repo's name end in .wiki. we also could do this style.

**Comment by Unknwon** [comment]
Just want to say `*.wiki` was already in reversed name list, your version is too old..

**Comment by liuyang1** [comment]
Verified, 0.9.13 version fix this bug. Thanks! :smile:
