### ISSUE TITLE
Authorized_keys file empty after deleting a user

### ISSUE THREAD

**Issue by smiquee** [gogits/gogs#3281]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 1.8.3.1
- Operating system: RHEL 7.2
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ X ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X ] Not relevant
- Log gist:
 Nothing related to the file appears in the logs. We just see that the HHTP request for deletion returns ok.

## Description

Hello,

Today I found a bug that is major. All our users use their ssh key to work with gogs, and when deleting the account of a person that left the team, it resulted in an empty ~/.ssh/authorized_keys file. Thus, nobody can use the git+ssh protocol anymore.

I didn't found anything related to such a bug in the past issues.

**Comment by Unknwon** [comment]
Please upgrade to latest version and re-test..

**Comment by Unknwon** [comment]
ping

**Comment by smiquee** [comment]
Hello.

I'm currently quite busy on our projects, but I will try the new version as soon as possible. Normally I will have some time in the beginning of next week.

Also, there is no "binary" package available for last version, so I have to deploy all the compilation environment on the target machine.

**Comment by smiquee** [comment]
Hello!

I just tried the two last releases 0.9.46 and 0.9.48, and the issue still exists.

**Comment by Unknwon** [comment]
Does file content come back if you go to `/admin` and run regenerate `~/.ssh/authorized_keys` file?

**Comment by smiquee** [comment]
Yes, this is ok.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by smiquee** [comment]
The bug is fixed within the develop branch.
