### ISSUE TITLE
Commit-Message with backslash is rendered wrong

### ISSUE THREAD

**Issue by mrdrogdrog** [gogits/gogs#3283]
I found a bug in the list of commits ($server/$repo/commits/$branch) in the latest version of gogs (0.9.46.0717).

I have a commit with a backslash in the message. The backslash is rendered with the "Yen"-Character.
But only on this url in this list.
I tried chrome and firefox on linux.
It seems like the font "Meiryo Ui" causes this bug.

Reproduce:
commit something and put a backslash in your commit message.

Thanks for your attention.

**Comment by DerUser** [comment]
same bug here
happend with this old-school emoji "\o/"

**Comment by Unknwon** [comment]
Please reproduce one on demo site as required.

**Comment by mrdrogdrog** [comment]
https://try.gogs.io/mrdrogdrog/test

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/16982676/c410e71e-4ea3-11e6-8e84-774c653e727e.png)

Like this?

**Comment by mrdrogdrog** [comment]
![bildschirmfoto vom 2016-07-20 12-07-44](https://cloud.githubusercontent.com/assets/6124140/16982925/b6c6e620-4e72-11e6-986b-562a16d1c2d3.png)

more like this.

"Helvetica Neue" is a non-free font and not preinstalled on linuxsystems

**Comment by Unknwon** [comment]
Any thoughts regarding this problem? @Laica-Lunasys

**Comment by mrdrogdrog** [comment]
Some fonts (e.g. Libersation Sans) are very similar to Helvetica Neue. You could use them as a backup or replacement.

http://graphicdesign.stackexchange.com/a/9054

**Comment by Unknwon** [comment]
Font removed.
