### ISSUE TITLE
Problem to compile Gogs with Glide

### ISSUE THREAD

**Issue by fanningert** [gogits/gogs#3284]
- Gogs version (or commit ref): 0.9.46
- Git version: 2.9.0
- Operating system: ArchLinux
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes (provide example URL) <- no URL (compile error)
  - [ ] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/jakschu/f66b0b5863d06cf6d61577cd94bc4e41

## Description
When I and other people compile the package with glide (0.11.0), we get following error with different repositories.

'''
[WARN]	Unable to checkout gopkg.in/alexcesaro/quotedprintable.v3
[ERROR]	Update failed for gopkg.in/alexcesaro/quotedprintable.v3: Unable to get repository
'''

Could be the problem by glide? I found the issue https://github.com/Masterminds/glide/issues/476.

**Comment by Unknwon** [comment]
Thanks, cloud be because gopkg.in/alexcesaro/quotedprintable.v3 is online, but Docker image building seems using glide as well but without error: https://hub.docker.com/r/gogs/gogs/builds/bxcu3sjadbnwcbloeekwbo6/

**Comment by fanningert** [comment]
It is really strange. One time it is working. One time I get the error. Did you know a log parameter for 'glide install'? <- Currently I download the dependencies with this command.

**Comment by Unknwon** [comment]
Sorry.. but I don't know very much about glide actually..

**Comment by fanningert** [comment]
I would say we can close this issue on GOGS and can say it is more a problem of glide. I will create or use the existent issue on the glide page on GitHub.
