### ISSUE TITLE
Search in issues

### ISSUE THREAD

**Issue by xp65** [gogits/gogs#3293]
Thanks for the hard work on this great project! 
A missing feature is a search in issues. Going over the long list to find issues isn't productive.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/13?

What is `search in issues`?

**Comment by xp65** [comment]
Yes, that seems to be exactly the requested feature. Search similar as the search implemented with commits. Thanks for the quick follow up.
