### ISSUE TITLE
LDAP username issue in v0.9.46

### ISSUE THREAD

**Issue by nrclark** [gogits/gogs#3295]
I'm a big fan of Gogs - I've been using it to host my department's Git repositories for the past 4 months. Gogs 0.9.13 works flawlessly with my company's LDAP server (using the BindDN authentication type). 

Using the same settings, LDAP doesn't seem to work for me in Gogs 0.9.46. I tried each of the new "Security Protocol" settings, and also went through all of the TLS checkbox settings for each protocol mode.

In the logfile, I found the following message:

```
2016/07/20 17:39:27 [W] Failed to login 'nicholas.clark' via 'Boulder_Bind': Invalid pattern
for attribute 'username' [Nicholas.Clark]: must be valid alpha or numeric or dash(-_) or dot
characters
```

Is this some kind of a regex bug somewhere? The username "nicholas.clark" is only letters and dots, so I would have expected it to work. It also worked fine in Gogs 0.9.13.

Here's my setup:
Git: 2.7.4
Operating System: Ubuntu 16.04
Database: SQLite

**Comment by Unknwon** [comment]
Thanks your feedback!

Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

**Comment by barracks510** [comment]
This works now. Thanks!

**Comment by gramakri** [comment]
Just hit this when updating the cloudron app. For those wondering, the fix is at https://github.com/gogits/gogs/commit/57af7432fc07f630e435228a306a9deeb3fefa1e
