### ISSUE TITLE
gogs "tmp" must be on same volume as the git repo root dir

### ISSUE THREAD

**Issue by kardianos** [gogits/gogs#3298]
- Gogs version (or commit ref): Gogs version 0.9.46.0717
- Git version: git version 2.9.2.windows.1
- Operating system: windows server 2012
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log:
```
2016/07/20 14:52:42 [...routers/repo/repo.go:131 CreatePost()] [E] initRepository: initRepoCommit: git push: error: cannot spawn hooks/update: No such file or directory
remote: error: hook declined to update refs/heads/master        
To T:\GoGitService\root\danielt\test1.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'T:\GoGitService\root\danielt\test1.git'

2016/07/20 14:52:42 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: delete repo directory danielt/test1 failed(2): remove T:\GoGitService\root\danielt\test1.git\objects\44\f67c15774802d93d1e2588855f1c69e106428e: Access is denied.
```

## Description

When setting up gogs on windows, I found that if the TMP directory was on a different volume than the root directory, the git init or git push process would fail, and then show a 500 when you try to view the page. This failed at the `GetBranches` call which called the git command `git show-ref --heads` which returned a non-zero return value (no heads), possibly because the repo failed to be setup correctly.

Solved this issue locally by setting the TMP env var for the process to a local path. Is it possible a copy or more probable, a move, is failing between the tmp dir and the repo root dir?

Possibly need a more robust file operation, or a detection for this case on program init.

Oddly enough, I had to add the "sh" to the PATH or I got an error there. Possibly unrelated.

Possibly related to #2646

**Comment by Unknwon** [comment]
Hi, based on the errors in the log you posted, I don't see anything related to `tmp` directory?

**Comment by kardianos** [comment]
Correct. I only modified the TMP env var (windows uses that first) after I looked at the git operation code and noticed it is creating a tmp dir and doing some operations in that. I then took a leap of faith that it might be related. Moving the TMP dir to the same drive fixed it.

That could be a false lead, but unsure what else to think it may be.

**Comment by Unknwon** [comment]
>git push: error: cannot spawn hooks/update: No such file or directory

For me, it looks like the `path/to/repo.git/hooks/update` file is missing?

**Comment by kardianos** [comment]
That is vary likely. What I found was that until I specified the TMP folder, the repo would be in various states of disarray. But I think it was the result of some underlying issue, not the cause.

When I get a chance I can see if I can reproduce.

**Comment by Unknwon** [comment]
Any updates?

**Comment by kardianos** [comment]
Sorry, no. I will try to reproduce within a day though. Sorry for leaving this open so long.

**Comment by kardianos** [comment]
I was unable to reproduce on Linux. I will try again on Windows (original test case) tomorrow or the next day.

**Comment by Unknwon** [comment]
ping

**Comment by kardianos** [comment]
Thanks for the ping. I cannot reproduce in the latest release.
