### ISSUE TITLE
Gogs pops up "Do you want to leave this site" on login page

### ISSUE THREAD

**Issue by bulletmark** [gogits/gogs#3299]
I upgraded from v0.9.13 to v0.9.46 today and immediately noticed a new bug which appears to be due to the changes done for issue #2881.

If I go to my gogs login page then chrome automatically pre-fills my name etc into the login form just like any other site login page. If I immediately try to close the tab, without typing anything, then gogs pops up a "Do you want to leave this site. Changes you made may not be saved" window. This is annoying to the user and no other login page does it.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.
