### ISSUE TITLE
RewriteRepositoryUpdateHook does not fix or report missing executable permissions

### ISSUE THREAD

**Issue by lhw** [gogits/gogs#3302]
- Gogs version (or commit ref): 0.9.47.0721 (docker container)
- Git version: (docker container)
- Operating system: (docker container)
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (needs wrongfully updated repository)
  - [ ] Not relevant 
- Log gist:
/

## Description
A previously not correctly updated _update_ hook had no executable permissions. I noticed it just now as a commit did not trigger a explorable site update. While this most likely was a fault from copying over a repository the "Rewrite all update hook of repositories" should probably check if the _update_ hook has executable permissions for the gogs user or attempt a fix.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by lhw** [comment]
Can't really verify it on your installation. But I will try it out when it comes up in the following weeks in master. Thanks for your quick work!

**Comment by Unknwon** [comment]
New version was released yesterday..
