### ISSUE TITLE
Can't migrate repositories onto a CIFS/Samba filesystem

### ISSUE THREAD

**Issue by nrclark** [gogits/gogs#3303]
I'd like to be able to move our Git repositories onto our IT department's CIFS/Samba server so that we don't need to worry about doing our own backups.

I set `[repository]/ROOT` set to the path of a Samba share in `conf/app.ini`, and it seemed to work OK. I can create and access new repos. However, Gogs won't let me migrate existing repositories onto a Samba share. I get errors like this:

```
Migration failed: Clone: exit status 128 - error: chmod on /mnt/1usbrfile01/common/nrclark/
gogs-repos/nicholas.clark/gogs-pkg.git/config.lock failed: Operation not permitted error:
chmod on /mnt/1usbrfile01/common/nrclark/gogs-repos/nicholas.clark/gogs-pkg.git/
config.lock failed: Operation not permitted error: chmod on /mnt/1usbrfile01/common/nrclark/
gogs-repos/nicholas.clark/gogs-pkg.git/config.lock failed: Operation not permitted error:
chmod on /mnt/1usbrfile01/common/nrclark/gogs-repos/nicholas.clark/gogs-pkg.git/
config.lock failed: Operation not permitted error: chmod on /mnt/1usbrfile01/common/nrclark/
gogs-repos/nicholas.clark/gogs-pkg.git/config.lock failed: Operation not permitted error:
chmod on /mnt/1usbrfile01/common/nrclark/gogs-repos/nicholas.clark/gogs-pkg.git/
config.lock failed: Operation not permitted fatal: 'origin' does not appear to be a git
repository fatal: Could not read from remote repository. Please make sure you have the
correct access rights and the repository exists. 
```

It's true that 'chmod' won't work on the files (because they're mounted on a permissionless filesystem). However, I can create _new_ repositories and they work fine. Can we suppress the chmod errors?

**Comment by nrclark** [comment]
As a workaround, I tweaked how I mounted the Samba share. Closing this issue.

**Comment by Unknwon** [comment]
Sounds more like you did not give your `git` binary enough permission.
