### ISSUE TITLE
Some suggestions about conf file dir for Nix pm.

### ISSUE THREAD

**Issue by Losiara** [gogits/gogs#3304]
I am preparing gogs package to "functional" package manager NIX (nixos). There is an issue about custom conf. Hard fixed directory /etc/custom/conf makes some pain inside NIX pm.
Is it possible someway to set custom conf directory via env variable?

**Comment by nrclark** [comment]
This is already possible (or at least - it works on my machine!). The GOGS_CUSTOM environment variable can be used to control the location.

I've got a set of debhelper scripts for packaging Gogs for Debian/Ubuntu - in my .deb package, I place my custom config file here: `/etc/gogs/conf/app.ini` then, in the service's unit file, I call gogs with: `GOGS_CUSTOM=/etc/gogs` set as an environment variable.

**Comment by Losiara** [comment]
GOGS_CUSTOM is about only config or it influence other params?

**Comment by nrclark** [comment]
I just did a test search of the repository. Looks like it also controls the expected location of 'robots.txt':
``` Go

	...
	
	CustomPath = os.Getenv("GOGS_CUSTOM")
	if len(CustomPath) == 0 {
		CustomPath = workDir + "/custom"
	}
	
	if len(CustomConf) == 0 {
		CustomConf = CustomPath + "/conf/app.ini"
	}
	
	...
	
	HasRobotsTxt = com.IsFile(path.Join(CustomPath, "robots.txt"))
```

**Comment by Losiara** [comment]
Thanks a lot.
