### ISSUE TITLE
Let teams inherit organization repositories

### ISSUE THREAD

**Issue by nrclark** [gogits/gogs#3307]
I'd love to be able to structure my teams' git repos like this:

- Organization: Project_Group_1, most repos are private
    - Team: Admin (r/w/admin)
    - Team: Devs (r/w)
    - Team: Test  (r)
- Organization: Project_Group_2, most repos are private
    - Team: Admin (r/w/admin)
    - Team: Devs (r/w)
    - Team: Test  (r)

As Project_Group_1 and Project_Group_2's repo counts grow, it's hard to manually add every new repo to every team in an organization.

Would it be possible to add a setting in the `[Organization] -> [Options]` menu that lets an organization's teams auto-inherit all of the organization's repos?

**Comment by Unknwon** [comment]
Hi, it is not going to change how organization, teams and repositories work together in the near future. However, you can follow on https://github.com/gogits/gogs/issues/568.
