### ISSUE TITLE
Suspected bug in pull requests (getting an Error: 500)

### ISSUE THREAD

**Issue by nrclark** [gogits/gogs#3308]
I'm experimenting with Gogs' pull-requests, and I can't make them work. Our existing workflow doesn't use pull requests, but we've got a team that wants to try them. On my development server, I tried to make a couple of accounts and experiment with pull requests.

I made a new repo called `less` in my main LDAP-authenticated account, and then added it as a remote master and pushed into it. That was all fine. I was also able to fork the repo onto a local-user account that I created (which also works fine).

When I try to generate a PR, however, Gogs reports a 500 error. Looking at the log file, I see the following error: `[...routers/repo/pull.go:679 CompareAndPullRequestPost()] [E] NewPullRequest: newIssue: GetRepositoryByID: repository does not exist [id: 13, uid: 0, name: ]`

I verified that both repos exist on the filesystem, and I also tried deleting both repos and redoing the experiment with new repos. I also tried rebooting the server.

My setup:

- Gogs version: v0.9.46
- Git version: v2.7.4
- Operating system: Ubuntu 16.04
- Database: SQLite
- Can't replicate it on try.gogs.io.

**Comment by akademic** [comment]
Duplicate: #3291
