### ISSUE TITLE
500 error when posting issue

### ISSUE THREAD

**Issue by dealloc** [gogits/gogs#3310]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): Application Version: 0.9.46.0717
- Git version: git version 2.1.4
- Operating system: Linux DebianDevCave 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When I or one of my team members try to create an issue we get a 500 error. However when I follow the same steps on try.gogs.io I don't seem to be able to reproduce this issue. When scimming through the log files I encountered this:
```
2016/07/23 07:07:34 [I] Log Mode: File(Info)
2016/07/23 07:07:34 [I] Cache Service Enabled
2016/07/23 07:07:34 [I] Session Service Enabled
2016/07/23 07:07:34 [I] Git Version: 2.1.4
2016/07/23 07:07:34 [I] SQLite3 Supported
2016/07/23 07:07:34 [I] Run Mode: Production
2016/07/23 07:07:35 [I] Listen: http://0.0.0.0:3000
2016/07/23 07:07:46 [...outers/repo/issue.go:435 NewIssuePost()] [E] NewIssue: newIssue: GetRepositoryByID: repository does not exist [id: 7, uid: 0, name: ]
2016/07/23 07:08:43 [...outers/repo/issue.go:435 NewIssuePost()] [E] NewIssue: newIssue: GetRepositoryByID: repository does not exist [id: 7, uid: 0, name: ]
2016/07/23 07:10:07 [...outers/repo/issue.go:435 NewIssuePost()] [E] NewIssue: newIssue: GetRepositoryByID: repository does not exist [id: 7, uid: 0, name: ]
```

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3291

**Comment by dealloc** [comment]
Ah, fixed by updating to .48
My apologies, I had not realised that the PR issue was about the same.
