### ISSUE TITLE
Divide GOGS_WORK_DIR and GOGS_CUSTOM pathes.

### ISSUE THREAD

**Issue by Losiara** [gogits/gogs#3312]
- Gogs version (or commit ref): latest 0.9.48

I am preparing gogs package for Nix package manger.
And I need such thing.
a) My custom conf directory must be placed in home folder.
b) Gogs bin must be placed in $instpath/bin
c) templates, public and so on must be placed in $instpath
I set GOGS_WORK_DIR = $instpath
and GOGS_CUSTOM = $HOME/gogscustom
But cant run binary. Shows an 
`error "Binary and template file version does not match, did you forget to recompile?"`

Is it possible to prepare config described above?

**Comment by Unknwon** [comment]
The error is saying you have template files from older version, please use the ones as your Gogs binary version. In your case, it is 0.9.48.

**Comment by Losiara** [comment]
Sorry my inattentiveness.
Changed version. Now all seems work right.
