### ISSUE TITLE
JS line number breaks syntax highlight element block

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3316]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Color issue on comments following JavaDoc syntaxe.

**For bug reports, please give the relevant info:**
- *Gogs version (or commit ref):* 0.9.48
- *Git version:* 1.8.3.1
- *Operating system:* Linux CentOS 7 64bit
- *Database:* SQLite
- *Can you reproduce the bug at http://try.gogs.io:*
  - [x] Yes (https://try.gogs.io/zero-x-baadf00d/psychic-soul/src/master/src/main/java/core/Settings.java)
  - [ ] No
  - [ ] Not relevant

## Description

![capture](https://cloud.githubusercontent.com/assets/1005086/17085892/2d2ae8f6-51e4-11e6-928a-7c291029af31.JPG)

**Comment by Unknwon** [comment]
This could be fixed by https://github.com/gogits/gogs/pull/2942

**Comment by nrclark** [comment]
Saw this bug on our server as well.

**Comment by Unknwon** [comment]
Fixed by #2941, see https://try.gogs.io/zero-x-baadf00d/psychic-soul/src/master/src/main/java/core/Settings.java
