### ISSUE TITLE
Short commit references not turning into links.

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3321]
See https://git.osgeo.org/gogs/geos/php-geos/issues/6#issuecomment-182 and subsequent comment.
The first comment used ca42d272d8 as a commit reference, the second used the full hash and the full url.
Only the second comment turned both references into links, while the first did not.

**Comment by Unknwon** [comment]
Why did I see both have correct links?

**Comment by Unknwon** [comment]
You have to use 40 length SHA in order to generate the link, https://github.com/gogits/gogs/blob/master/modules/markdown/markdown.go#L93 . Because Gogs correct does not support variable length SHA to show the commit page.

**Comment by Unknwon** [comment]
`git-module` has supported abbreviated commit IDs, https://github.com/gogits/git-module/pull/10/files .

**Comment by 0xbaadf00d** [comment]
I can do modification

**Comment by ronnicek** [comment]
Hey guys, sorry to writing or opening old issue, but is this working for you in latest version (0.11.53.0603)? When I use short commit SHA it doesnt create a link :-/ (https://git.vypni.net/ronny/wemos-projects/issues/1). Long commit SHA is working correctly..

**Comment by Unknwon** [comment]
@ronnicek can you try to reproduce on https://try.gogs.io?

**Comment by ronnicek** [comment]
@Unknwon https://try.gogs.io/ronnicek_test/test/issues/1 here :)

**Comment by Unknwon** [comment]
@ronnicek thanks! I tested the regexp works for the content you posted, I'll look into why it does not render the short one to a link.

**Comment by Unknwon** [comment]
Ah... I found that somehow the code reverted back to only match SHA1 with length 40: https://github.com/gogs/gogs/blob/master/pkg/markup/markup.go#L58

**Comment by Unknwon** [comment]
OK, it is now fixed again: https://try.gogs.io/ronnicek_test/test/issues/1
