### ISSUE TITLE
authentication failed 

### ISSUE THREAD

**Issue by xchunzhao** [gogits/gogs#3323]
* gogs version:0.7.33.1205 Beta

i add ssh key to the author_keys, but find that authentication failed
![rtx](https://cloud.githubusercontent.com/assets/13491131/17127495/a8be7096-5338-11e6-8d0f-5280d8639afb.png)

**Comment by Unknwon** [comment]
1. Your version is too old.
2. Not enough details to say nothing.

Please follow https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md
