### ISSUE TITLE
Wording change proposal on "create new repository" page

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3325]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

**For bug reports, please give the relevant info:**

- *Gogs version (or commit ref):* 0.9.48.0722
- *Git version:* 1.8
- *Operating system:* CentOS 7
- *Database:*
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- *Can you reproduce the bug at http://try.gogs.io:*
  - [x] Yes : Create a repository
  - [ ] No
  - [ ] Not relevant

## Description
This issue is related to last comment on #1598. When user create a repository, he can found an option named _Language_ with multiple choices from a list of programming language. In fact, it seem that this option is only to create a _.gitignore_ file on the newly created repository and not to indicate which programming languages are used on the project.

Maybe replacing "_Language_" with "_.gitignore template_" or "_.gitignore rules_" on repository creation could avoiding any kind of confusion.

![screenshot from 2016-07-26 10-00-35](https://cloud.githubusercontent.com/assets/1005086/17130245/d9e5382e-5317-11e6-9cee-c83af6403ab5.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
