### ISSUE TITLE
500 error when filtering issues by label

### ISSUE THREAD

**Issue by galactics** [gogits/gogs#3327]
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.48.0722
- Git version: 1.7.1
- Operating system: CentOS
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Whe trying to filter issues by labels I get a 500 error and the log shows

    2016/07/26 09:34:45 [...outers/repo/issue.go:184 Issues()] [E] Issues: %v: no such column: issue.label_id

**Comment by Unknwon** [comment]
> Yes (provide example URL)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by galactics** [comment]
Whoa man ! A fix in less than 2h, that rocks !
It seems to work fine now, thanks !
