### ISSUE TITLE
Upgrades from 0.9.27.0512 to 0.9.55.0726 breaks LDAP login source

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3328]
Upgrading Gogs from 0.9.27 to 0.9.55 results in an system not accepting any LDAP login.
The logs say: [I] Migration: convert LDAP UseSSL option to SecurityProtocol
and I confirm the change was in the database, with SecurityProtocol value 1
but I could not login with my LDAP credentials anymore. Logging in with a non-LDAP user was fine.

The working (0.9.27) value of the configuration has `SkipVerify:true` and `UseSSL:true`.
The broken (0.9.55) value was `SecurityProtocol:1` and `SkipVerify:true`

**Comment by Unknwon** [comment]
>but I could not login with my LDAP credentials anymore. 

error log?

**Comment by strk** [comment]
The only traces in the logs are:


``
2016/07/25 12:12:22 [I] Migration: convert LDAP UseSSL option to SecurityProtocol
2016/07/25 12:21:07 [...ules/context/repo.go:115 func1()] [E] GetUserByName: user does not exist [uid: 0, name: css]
2016/07/25 13:38:14 [...ules/context/repo.go:115 func1()] [E] GetUserByName: user does not exist [uid: 0, name: js]
2016/07/25 14:12:05 [W] Failed to login 'xxx' via 'OSGeo LDAP': user does not exist [uid: 0, name: xxx]
``

**Comment by Unknwon** [comment]
Thanks, but I don't see any trace level logs, have you changed the log level?

**Comment by strk** [comment]
LEVEL = Info

What should I set it to ?

**Comment by strk** [comment]
It would help if Gogs printed its own version on starting, btw,
so I could tell which traces came from which version (I've been
doing back and forth a few times).

For example I believe this comes from the old version after
the migration:

```
2016/07/26 01:13:21 [...gogs/models/login.go:267 LoginUserLDAPSource()] [E] LDAP Connect error, ldap.osgeo.org:LDAP Result Code 200 "": tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

(which was fixed by logging as the administrator [no LDAP] and
checking the "Use TLS" checkbox again)

**Comment by Unknwon** [comment]
>It would help if Gogs printed its own version on starting, btw,

It does.

>LEVEL = Info
What should I set it to ?

`Trace`.

**Comment by strk** [comment]
On Tue, Jul 26, 2016 at 04:04:47AM -0700, 无闻 wrote:
> >It would help if Gogs printed its own version on starting, btw,
> 
> It does.

It does not:

    2016/07/26 04:07:11 [I] Log Mode: File(Trace)
    2016/07/26 04:07:11 [I] Cache Service Enabled
    2016/07/26 04:07:11 [I] Session Service Enabled
    2016/07/26 04:07:11 [I] Mail Service Enabled
    2016/07/26 04:07:11 [I] Notify Mail Service Enabled
    2016/07/26 04:07:11 [I] Git Version: 1.7.10.4
    2016/07/26 04:07:12 [I] Run Mode: Production
    2016/07/26 04:07:12 [T] Doing: CheckRepoStats
    2016/07/26 04:07:12 [I] Listen: http://127.0.0.1:3000/gogs

The above is with Trace level (activated now)

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/blob/master/modules/setting/setting.go#L528

>The above is with Trace level (activated now)

No error at all from what I see.

**Comment by strk** [comment]
What I pasted was the startup message, not the error message.
The error message was pasted before.

I'm not in a position to try the upgrade again with traces enabled,
not before a couple of months.

**Comment by Unknwon** [comment]
You need to provide Trace level log for trying to login via LDAP, otherwise this is not a valid report.
