### ISSUE TITLE
No more Linux i386 builds?

### ISSUE THREAD

**Issue by Gui13** [gogits/gogs#3329]
Since v0.9.46, there are no Linux i386 binaries anymore.

I couldn't find any explanation of why this support has been dropped.
I'm using it on an i386 Synology NAS, and I'd rather grab an official version than go through the cross-compilation process, if possible.

Any reason why these images were not generated?
I'm not asking for a build, really, just the reason of the drop.

**Comment by bkcsoft** [comment]
I'm working on that. Though setting up a 32bit VM on Proxmox was harder than I thought :laughing:

**Comment by bkcsoft** [comment]
The reason for using a VM is that you can't cross-compile with sqlite-support, since that requires CGO :unamused:

**Comment by Gui13** [comment]
Humm, strange, I just cross compiled gogs with my Ubuntu 16.04. I installed the last Go release, and apt-get sqlite3:i386, and executed:

    CGO_ENABLED=1 GOARCH=386 GOOS=linux go build -v -tags "sqlite"

It produced an executable that works on my NAS.

**Comment by bkcsoft** [comment]
@Unknwon ^

@Gui13 yeah, Multilib might do the trick :laughing:
