### ISSUE TITLE
Data folder with ssh keys created in wrong location

### ISSUE THREAD

**Issue by shytikov** [gogits/gogs#3334]
- Gogs version (or commit ref): 0.9.46.0717
- Git version: 1.9.5
- Operating system: Windows 10
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: no log applicable 

## Description
If `gogs` executable location is added to the `PATH` variable it's possible to start `gogs web` form any folder. Which is convenient sometimes if you need to have on-demand functionality. But this is very unexpected for `gogs`.

This scenario leads to reading SQLite database from incorrect location, if location was not set with absolute value (workaround was discussed in #2514). But not only!

`Gogs` will anyway create `data` sub folder in the folder it was called, and this folder will contain `sessions` and `ssh` sub folders. Most unpleasant is `ssh`, since it contains private and public keys generated for the server, and this means if `gogs` is started in different folders, same ssh location will receive different footprints. And it would be impossible to connect to it without modification of `known_hosts` file.

Suggested  solution: not use current working directory of console running `gogs` at the moment to determine where data folder should be located, instead use folder information from `gogs` binary file location.

**Comment by Unknwon** [comment]
Thanks your feedback but it is very bad practice to run Gogs from global environment, please start with `./gogs web` as [documented](https://gogs.io/docs/installation/configuration_and_run#for-deployment).

**Comment by Unknwon** [comment]
PS: it is configurable: https://github.com/gogits/gogs/blob/master/conf/app.ini#L103
