### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by ogomez92** [gogits/gogs#3338]
Hello,
There are many accessibility issues in gogs. Can you enable a mode that doesn't use all this mouse over actions or use aria to tell screen readers about these opening menus etc?
I am using a reader and I installed gogs and, while it is usable, I have a hard time creating new repos etc because I need to use the mouse cursor all the time and this isn't at all optimal.

Please fix?We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):
- Git version:
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

...

**Comment by ogomez92** [comment]
Like I said, there are many places in gogs like the create menu.. settings... profile... that need to be fixed for accessibility.

**Comment by Unknwon** [comment]
Hi, please follow https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md, remind closed until information are filled.
