### ISSUE TITLE
Migration fails when no master branch is found

### ISSUE THREAD

**Issue by fungl164** [gogits/gogs#3339]
## Setup
- Gogs version (or commit ref): `0.9.48.0722`
- Git version: `2.9.2`
- Operating system: `OSX`
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

When trying to migrate a repo that only has a develop branch and no commits to master fails with following message on the ui:
`Migration failed: Clone: exit status 128 - remote: Not Found fatal: repository 'https://github.com/owner/repo...' not found`

**Comment by Unknwon** [comment]
I think the solution to this problem is you need to change the default branch before migration.

In other words, change `HEAD` file to point to a non-master branch.
