### ISSUE TITLE
Deployment Key Support

### ISSUE THREAD

**Issue by Someguy123** [gogits/gogs#334]
A rather important issue for organisations I work with, is that there's no deployment key support.

Deployment Keys are SSH keys added to a repository to give a server read-only access to the repository. This is to prevent someone from git push'ing on one of the servers, and it also protects us in case we were hacked so that the hacker couldn't push out malicious changes to our repositories.

I think this feature is pretty important and would like to see it in Gogs soon.

**Comment by gittex** [comment]
:+1: a must have

**Comment by richardzone** [comment]
Very much needed! ++++++

**Comment by ncraike** [comment]
+1

**Comment by fjorgemota** [comment]
+1

**Comment by jalada** [comment]
:+1:

**Comment by kotchuprik** [comment]
+1

**Comment by nvx** [comment]
+1

**Comment by csu** [comment]
+1

**Comment by mvallerie** [comment]
+1

**Comment by frett27** [comment]
+1

**Comment by CambridgeMBN** [comment]
+1

**Comment by Unknwon** [comment]
Hi all, this feature has been implemented in `develop` branch code, you can also test on https://try.gogs.io ! :beer:

**Comment by kotchuprik** [comment]
wow! cool, thanks!
