### ISSUE TITLE
provide more user friendly information when e-mail has been used

### ISSUE THREAD

**Issue by CptTZ** [gogits/gogs#3341]
- Gogs version (or commit ref): 0.9.58.0726
- Git version: Irrelevant
- Operating system: CentOS 7.2 (Using a docker container which is officially supported)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (example URL can't be provided in this issue)
  - [ ] No
  - [ ] Not relevant
- Log:
  - 2016/07/28 14:01:16 [...routers/user/auth.go:274 Activate()] [E] UpdateUser: e-mail has been used [email: xxx@example.com]
# Description

When this issue happens, user will get a HTTP 500 error only while trying to activate his account.
I think it's better to tell user that the e-mail has been used when he is registering, not when he is trying to activate his account. Besides, a HTTP 500 error seems rather weird, I considered it a server error first time when I encountered this 'e-mail' problem.

**Comment by Unknwon** [comment]
User in newer version will not be allowed to sign up with used email, so this case should not happen anymore.
