### ISSUE TITLE
Feature Request: Wiki and Issues for Organisations

### ISSUE THREAD

**Issue by agaida** [gogits/gogs#3342]
Central wika and issues per organisation would be nice to have, for issues with the possibility to aggregate issues in the organisation repos in this tracker. Don't know how others think about, but this is a feature that i really miss in gogs (of course in github too)

**Comment by Unknwon** [comment]
Hi, 

1. central wiki is not going to be added in near future
2. you can already view organization issues in its dashboard `/org/:orgname/issues`.
