### ISSUE TITLE
Absolute links images breaks nginx image displays as reverse proxy

### ISSUE THREAD

**Issue by richardskumat** [gogits/gogs#3348]
Edit:

Only avatars seem to be affected.

- Gogs version (or commit ref): 0.9.58.0726
- Git version: 2.1.4
- Operating system: Linux/Raspbian 8
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

Upgrading source build from 0.9.42.0712 to 0.9.58.0726 seems to have replaced image links on Gogs web dashboard with links to the http://%domain values in the custom app.ini values.

This results in broken images because I use nginx on port 80 and 443 to reverse proxy Gogs which runs on localhost:3000.

Reverting to 0.9.42.0712 leaves me with working image links.

0.9.42 seem to have linked to relative image paths so the reverse proxy could display images as if they were for eg. avatars: https://hostname/avatars/userid(eg. 2).

0.9.58 have broken images on the main page(ie. news, commits and your repos) and also on the profile page.

The gogs web server itself serves the image however absolute links to https://%domain values.

I could get the images from the gogs web server(macaron) by:

```
ssh gogs-host "curl localhost:3000/avatars/2" | display
```

"display" needs ImageMagick, but what matters is that the output is the avatar image for profile id 2. So what I mean that Macaron still works, but links to images break with nginx as a reverse proxy.

So what I request is reverting image links to the previous version if possible.

**Comment by Unknwon** [comment]
How did you config your NGINX?

**Comment by richardskumat** [comment]
I'm sorry. It seems to be only avatars.

If I log out, the default page seems to have properly working images with links https://hostname/img/gogs-lg.png.

Also attachments in issues seem to work OK.

Here's the custom app.ini:

```
[server]
PROTOCOL               = http
DOMAIN                 = localhost
ROOT_URL               = http://localhost:3000/
HTTP_ADDR              = 127.0.0.1
HTTP_PORT              = 3000
; Local (DMZ) URL for Gogs workers (such as SSH update) accessing web service.
; In most cases you do not need to change the default value.
; Alter it only if your SSH server node is not the same as HTTP node.
LOCAL_ROOT_URL         = http://localhost:%(HTTP_PORT)s/
; Disable SSH feature when not available
DISABLE_SSH            = false
```

Here's the nginx config with SSL:

```
server {
    listen 192.168.200.1:80;
#   listen [::]:80;
    return 301 https://$server_name$request_uri;
    server_name hostname.tld www.hostname.tld;
}

server {
    listen 192.168.200.1:443 ssl;
#   listen [::]:80;
    server_name hostname.tld www.hostname.tld;

        ssl_certificate         /etc/nginx/ssl/gogs/gogs.crt;
        ssl_certificate_key     /etc/nginx/ssl/gogs/gogs.key;
        server_tokens off;
        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:...';
        ssl_dhparam /etc/nginx/ssl/dhparam.pem;
        add_header Strict-Transport-Security max-age=15768000;
        ssl_session_timeout 30m;

        access_log  /var/log/nginx/gogs.log;
        error_log /var/log/nginx/gogs.error.log;

    location / {
        proxy_pass      http://localhost:3000;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        Host $http_host;
        proxy_read_timeout      90;
        proxy_redirect  http://localhost:3000 https://$http_host$request_uri;
    }
}
```

**Comment by Unknwon** [comment]
You config to use `server_name hostname.tld www.hostname.tld` as your domain name, why you set `ROOT_URL               = http://localhost:3000/` still in `localhost`?

**Comment by richardskumat** [comment]
That binds Gogs web server Macaron to listen on localhost(127.0.0.1 and ipv6 equivalent) only, so no connections can be made from other machines.

I've updated my gogs app.ini to the following:

```
[server]
PROTOCOL               = http
DOMAIN                 = localhost
ROOT_URL               = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
HTTP_ADDR              = 127.0.0.1
HTTP_PORT              = 3000
; Local (DMZ) URL for Gogs workers (such as SSH update) accessing web service.
; In most cases you do not need to change the default value.
; Alter it only if your SSH server node is not the same as HTTP node.
LOCAL_ROOT_URL         = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
```

This way Gogs still listens on the local machine only.

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.200.1:80        0.0.0.0:*               LISTEN      10164/nginx -g daem
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      20666/sshd      
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      14605/gogs
```

**Comment by richardskumat** [comment]
Gravatar images are not effected.

**Comment by Unknwon** [comment]
Just to confirm, only avatars are affected?

**Comment by richardskumat** [comment]
Yes, I couldn't find any other issues.

Last time I've tried was around 5 days ago.

**Comment by richardskumat** [comment]
See the ```<img src="http://localhost:3000/avatars/1?s=290" />``` link on the side.

http://s31.postimg.org/5lw68hytj/gogs6.png

See screenshots for examples:

http://s31.postimg.org/z7fjklchz/gogs1.png

http://s31.postimg.org/y6favgvif/gogs2.png

http://s31.postimg.org/ke0vzu4qv/gogs3.png

http://s31.postimg.org/sksvreutj/gogs4.png

http://s31.postimg.org/45knqcvwn/gogs5.png

http://s31.postimg.org/5lw68hytj/gogs6.png

Otherwise all other images are OK:

https://s31.postimg.org/bwef42fij/gogs7.png

https://s31.postimg.org/ymdjx1yq3/gogs8.png

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

cc @andreynering

**Comment by andreynering** [comment]
@Unknwon Checked and fixed. Thank you again.

**Comment by richardskumat** [comment]
Updated 0.9.42 to 0.9.64.0805. Custom avatar images work again well.

Thanks!

**Comment by 18augst** [comment]
I run into the same issue. I configured `Nginx` with `SSL` as reverse-proxy to `gogs` in `http` mode.
When I try to update `gogs` with latest commits in master with `go get -u github.com/gogits/gogs` command it throws following errors:

    a-gogs:~$ go get -u github.com/gogits/gogs
    # github.com/gogits/gogs/models
    go/src/github.com/gogits/gogs/models/action.go:278: undefined: gogs.PayloadAuthor
    go/src/github.com/gogits/gogs/models/action.go:283: undefined: gogs.PayloadCommitter
    go/src/github.com/gogits/gogs/models/action.go:524: unknown gogs.PayloadUser field 'ID' in struct literal
    go/src/github.com/gogits/gogs/models/action.go:525: unknown gogs.PayloadUser field 'AvatarUrl' in struct literal
    go/src/github.com/gogits/gogs/models/action.go:534: unknown gogs.PushPayload field 'CompareUrl' in struct literal
    go/src/github.com/gogits/gogs/models/action.go:537: undefined: gogs.PayloadAuthor
    go/src/github.com/gogits/gogs/models/pull.go:238: unknown gogs.PushPayload field 'CompareUrl' in struct literal
    go/src/github.com/gogits/gogs/models/pull.go:241: undefined: gogs.PayloadAuthor
    go/src/github.com/gogits/gogs/models/pull.go:248: unknown gogs.PayloadUser field 'ID' in struct literal
    go/src/github.com/gogits/gogs/models/repo.go:456: undefined: gogs.PayloadRepo
    go/src/github.com/gogits/gogs/models/pull.go:248: too many error

What I'm doing wrong?

**Comment by Unknwon** [comment]
Continue doing until it works..

**Comment by 18augst** [comment]
@Unknwon thanks, anyway) got `gogs` working from `develop` branch... Very strange that master doesn't work...

**Comment by Unknwon** [comment]
Yeah, will sync up master soon.
