### ISSUE TITLE
Add optional support for other VCS

### ISSUE THREAD

**Issue by jcmdln** [gogits/gogs#3350]
An interesting feature would be the possibility of using ```hg``` or others to import/mirror repositories, as this would assist users of platforms such as BitBucket who may not want to outright switch to git for various reasons.

This issue is mainly for tracking purposes and to encourage discussion about adding additional VCS's.

**Comment by dsafbvbvnjk** [comment]
How would you do that? VCS have different features, I don't think you can easily implement all of them. Lot of work.

**Comment by 0xbaadf00d** [comment]
Mercurial / Git could lives together with minor workarounds but other like CVS, SVN, ... i dont think it was possible.

**Comment by rikvdh** [comment]
Yes, this would be interesting. Now some obscure `git-to-svn` tooling must be used for this (or other tools for other VCS's. For my purpose `svn` is wanted.

**Comment by Unknwon** [comment]
Thanks your feedback! 

But this is far from Gogs meant to do, and not going to happen in the next one or two years.

**Comment by jrmiller82** [comment]
+1 to adding in mercurial support. Not simultaneous git/hg in the same individual repository. But being able to choose git or hg at repository creation a la bitbucket.

**Comment by lanybass** [comment]
+1.
want a plugin for gogs like git-as-svn
做成插件，可以开可以关，不影响正常功能
