### ISSUE TITLE
Wiki pages max size

### ISSUE THREAD

**Issue by morriswinkler** [gogits/gogs#3354]
Large wiki pages get cut at some point, havn't really checke the code, but i guess there is a maximum size for the markdown parser somewhere.

sorry if this is a duplicate, cause i remember reading about that somewhere, just could not find it in issues.

**Comment by dsafbvbvnjk** [comment]
+1  major bug! If there is a limit, it should be very high, like 1MB or so

**Comment by Unknwon** [comment]
Example URL?

**Comment by morriswinkler** [comment]
We do not have public git repositories, but all i can tell you is that if i save a big wiki page it is cut off at around a 

```
-rw-r--r--  1 user  staff  101287 Aug  3 06:51 Max Size Test.md
```

The content can be downloaded at [BIG MARKDOWN FILE](https://owncloud.laydrop.com/index.php/s/Ah6xWNcF6TaiRe3/download)

**Comment by Unknwon** [comment]
Demo on https://try.gogs.io as requested.

**Comment by morriswinkler** [comment]
Ok i tested it at https://try.gogs.io/nananana/try/wiki/Home and the text is not cut, looks like i have to update my version of gogs. Or maybe it is the apache proxy.
