### ISSUE TITLE
how to avoid user regiest wildly?

### ISSUE THREAD

**Issue by liugang1014** [gogits/gogs#3355]
I donot want any body can regiest my gogs and view my repo, is there an auth check when user regiested?

**Comment by 0xbaadf00d** [comment]
You can disable user registration or simply add a captcha (REQUIRE_SIGNIN_VIEW + DISABLE_REGISTRATION).

**Comment by dsafbvbvnjk** [comment]
You can already do this, there's an option when you install Gogs. You can both disable registrations (only admins can create new accounts), and you can also make your instance private.

**Comment by liugang1014** [comment]
I have resolved by modifing /gogs/custom/conf/app.ini 
@all ,thanks all the same!
