### ISSUE TITLE
Add option to disable Slack WebHook

### ISSUE THREAD

**Issue by dsafbvbvnjk** [gogits/gogs#3356]
Could you please add an option somewhere to **disable** Slack web hooks?
Gogs already has an option to disable gravatar for example; I'd also like an option to use "Gogs Webhooks ONLY" and **no slack**.

Thank you

**Comment by Unknwon** [comment]
Real life use cases?

**Comment by ftrtyyuukjnbvd** [comment]
> Real life use cases?

I use Gogs for my team, internally at my business. I want to disable all 3rd party services. This is possible for Gravatar and "CDN mode" simply by changing an option flag, but unfortunately it's not possible for Slack. Moreover there isn't a "disable 3rd party services" option anywhere.

Anyway I don't understand the question. Just add an extra option similar to the ones for Gravatar/CDN, how difficult can this be?

**Comment by 0xbaadf00d** [comment]
But it seems that Slack webhook must configured before it was used (`/settings/hooks`). So it could be considered as "disabled" by default.

**Comment by ftrtyyuukjnbvd** [comment]
@0xbaadf00d OK cool. So is it possible to remove it from 
![here](https://cloud.githubusercontent.com/assets/20780135/17355962/a8b4e18a-5954-11e6-9675-e3c10bd3a9d7.png) as well?

**Comment by 0xbaadf00d** [comment]
Why remove it ? By default it is not enabled/configured. Just don't use it.

**Comment by ftrtyyuukjnbvd** [comment]
@0xbaadf00d if I don't need this feature, why should Gogs confuse users into thinking that it's available to use (but it's not)? I really don't understand such useless arguments as "Why you want to remove it?" Why do you want it there, if it's not used? Following your same reasoning, Gogs should allow to not use CAPTCHAS, but still show CAPTCHAS to the user, even if the user doesn't have to solve them; or send users a verification email even if I've disable email verification and they are totally useless; or ask users for their gravatar email, even if it's not used... this is just confusing and unnecessary. What is difficult to understand about this?!

**Comment by bill-auger** [comment]
+1
ftrtyyuukjnbvd's reasoning is sound

notabug use case:

notabug does not wish to be associated with proprietary 3rd-party services and explicitly removes this feature currently as a routine upgrade chore

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
