### ISSUE TITLE
Fail to initialize ORM engine (Postgresql) - attempting to create indexes that exist?

### ISSUE THREAD

**Issue by jerrykan** [gogits/gogs#3359]
- Gogs version (or commit ref): 0.9.48.0722
- Git version: 2.1.4
- Operating system: Debian 8/jessie
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/jerrykan/95944b21de45b303523bc3e48f76b207

After running a clean install the DB seems to be initialised OK, but when gogs is restarted I get the following error:

    [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: pq: relation "UQE_user_lower_name" already exists

I tried dropping the `user` table to see if it would be regenerated (which it is), but then gogs falls over with:

    [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: pq: relation "IDX_public_key_owner_id" already exists

Looking at the logs (linked above) it seems as though the indexes are trying to be created even though they already exist.

**Comment by jerrykan** [comment]
On a whim I also tried this by building the latest develop branch (0.9.58.0726) and still get the same error.

**Comment by jerrykan** [comment]
Digging into this a bit more it seems like this issue occurs when the default `public` schema is not being used. Creating the DB using the following works fine:

    postgres@host$ psql --dbname=postgres --username=postgres
    CREATE USER gogs ENCRYPTED PASSWORD 'gogspass';
    CREATE DATABASE gogs OWNER=gogs;

But if I want to use a schema by setting up the DB as follows:

    postgres@host$ psql --dbname=postgres --username=postgres

    CREATE USER gogs ENCRYPTED PASSWORD 'gogspass';
    CREATE DATABASE gogs OWNER=gogs;

    postgres@host$ psql --dbname=gogs --username=gogs

    CREATE SCHEMA gogs AUTHORIZATION gogs;
    GRANT USAGE ON SCHEMA gogs TO gogs;
    ALTER ROLE gogs SET search_path TO gogs;

then gogs attempts to create indexes that already exist and errors out.

**Comment by lunny** [comment]
Currently, xorm doesn't support to customrize your schema on postgres database. So gogs too.

**Comment by Unknwon** [comment]
Thanks @lunny .

@jerrykan please post issue/feature request to upstream https://github.com/go-xorm/xorm
