### ISSUE TITLE
如果某用户的注册邮箱与管理员的邮箱一致时，系统无法创建新的仓库，也无法迁移其他仓库。

### ISSUE THREAD

**Issue by lendo** [gogits/gogs#3360]
如果某用户的注册邮箱与管理员的邮箱一致时，该用户和管理员均无法正常创建新的仓库，也无法迁移其他仓库。

此问题貌似会影响与个人邮箱信息相关的所有操作，当我修改该用户的邮箱，让其与管理员的邮箱不一致后，一切操作恢复正常。

后台的错误堆栈信息如下：
[Macaron] 2016-08-03 00:07:34: Completed /repo/migrate 500 Internal Server Error in 5.996372ms
2016/08/03 00:07:34 [...routers/repo/repo.go:101 handleCreateError()] [E] MigratePost: updateUser: e-mail has been used [email: gogs@163.com]
2016/08/03 00:07:34 [D] Template: status/500

**Comment by Unknwon** [comment]
Please follow https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md.
