### ISSUE TITLE
Dumps are created world readable

### ISSUE THREAD

**Issue by waldiTM** [gogits/gogs#3361]
- Gogs version (or commit ref): 0.9.48
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The dump files created by gogs have permissions directly derived from the umask, so 0644 aka word readable, by default. The dumps include private information like database credentials and repositories.

**Comment by Marco01809** [comment]
good luck with this. see #2950

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
