### ISSUE TITLE
Logs sensitive info to console by default

### ISSUE THREAD

**Issue by waldiTM** [gogits/gogs#3362]
- Gogs version (or commit ref): 0.9.48
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

gogs logs debug information to the console by default. I saw no way to disable this. systemd captures stdout by default.

The debugging info includes the session id and csrf token.

    2016/08/02 19:13:21 [D] Session ID: XXXXXXXXXXXXXXXX
    2016/08/02 19:13:21 [D] CSRF Token: XXXXXXXXXXXXXXXXVSViUBzH21M6MTQ3MDE2NDY1MTA3NzUyNTcwOQ==
    2016/08/02 19:13:21 [D] Bare repository: /example/example
    2016/08/02 19:13:21 [D] Template: repo/bare

**Comment by Unknwon** [comment]
You can change log level to `Info`: https://github.com/gogits/gogs/blob/master/conf/app.ini#L260

**Comment by waldiTM** [comment]
It is nice that you can, I obviously can't as it is already set:

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /srv/git/gogs/log

In modules/settings/setting.go I see:

        log.NewLogger(0, "console", `{"level": 0}`)

How is this hardcoded debug log changed by the config?

**Comment by Unknwon** [comment]
```ini
[log]
MODE      = console,file
```
