### ISSUE TITLE
Session storage world readable

### ISSUE THREAD

**Issue by waldiTM** [gogits/gogs#3363]
- Gogs version (or commit ref): 0.9.48
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

Session storage is created world readable. There seems to be no way to change that.

**Comment by waldiTM** [comment]
Where is this code coming from? I was not able to identify the source.

**Comment by Unknwon** [comment]
FYI https://github.com/go-macaron/session/blob/master/file.go

**Comment by aaronjwood** [comment]
Can `os.ModePerm` be changed to a parameter that can be tied to some user configuration? Or can it at least be changed to sane defaults?

Is there any reason directories and files aren't 0700 and 0600 respectively?

**Comment by Unknwon** [comment]
@aaronjwood 

>Is there any reason directories and files aren't 0700 and 0600 respectively?

No particular reason... just everyone seems using `os.ModePerm`.

**Comment by aaronjwood** [comment]
PR opened https://github.com/go-macaron/session/pull/21

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

New permission mode would only work for newly created/modified files. You can deleted all current files and restart Gogs for testing.
