### ISSUE TITLE
Can't edit Wiki page if page name contain #

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3364]
- _Gogs version (or commit ref):_ 0.9.59.0730
- _Can you reproduce the bug at https://try.gogs.io:_
  - [x] https://try.gogs.io/zero-x-baadf00d/psychic-soul/wiki/DEMO-ISSUE-%233354
  - [ ] No
  - [ ] Not relevant

## Description

I have created a wiki page named "DEMO ISSUE #3354".  The href link for all button (Edit / Delete / Save page) was not correct.

By instance, the href link on the button "Edit" ("Modifier" in French) was `https://try.gogs.io/zero-x-baadf00d/psychic-soul/wiki/DEMO-ISSUE-%233354/_edit` rathen than `https://try.gogs.io/zero-x-baadf00d/psychic-soul/wiki/DEMO-ISSUE-#3354/_edit`

If I enter manually `https://try.gogs.io/zero-x-baadf00d/psychic-soul/wiki/DEMO-ISSUE-#3354/_edit`, I can get the edit page form. But the "Save page" button href link was not correct too.

Maybe it could be nice to create a slug for wiki page URL with all special chars removed or replaced with dash ?

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3021
