### ISSUE TITLE
Problems using Docker-Image with jwilder/nginx Reverse Proxy

### ISSUE THREAD

**Issue by dblM90** [gogits/gogs#3366]
Hello everyone,

i'm using the latest docker repo version of gogs to run the application. I configured it not to forward any port to the outside world, because these connections are managed by a nginx reverse proxy container (https://github.com/jwilder/nginx-proxy), which is also dealing with all the ssl stuff.

So the problem is, that pulling repos over https doesn't work properly. I get the following error (e.g. in Sourcetree): _fatal: unable to access 'mydomain'/user/test.git': SSL certificate problem: unable to get local issuer certificate_

I tried so far to provide gogs the certificates and set the KEY_FILE and CERT_FILE setting in the app.ini. Also, i set the root-url to 'https://mydomain/', but nothing seems to change anything. The website is working fine with https, but repo pull does not work.

Here is my configuration app.ini file:

APP_NAME = Code
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE =sqlite3
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = 
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /data/git/gogs-repositories

[server]
DOMAIN = mydomain
HTTP_PORT = 3000
ROOT_URL = https://mydomain/
DISABLE_SSH = true
SSH_PORT = 22
OFFLINE_MODE = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = false
DISABLE_REGISTRATION = true
ENABLE_CAPTCHA = true
REQUIRE_SIGNIN_VIEW = false

Thanks in advance

**Comment by Unknwon** [comment]
>but repo pull does not work.

Vague words.

**Comment by Unknwon** [comment]
cc @0rax

**Comment by dblM90** [comment]
sorry for my english, i'm not a native english speaker. What I meant, is: Trying to clone or pull a repo within git command line tools, or gui's like Sourcetree, don't work an i get an error message. this message was described by me one paragraph above of "but repo pull does not work"

**Comment by Unknwon** [comment]
Got it.

Please read https://unknwon.io/setup-gogs-with-https/ and continue discussion on https://discuss.gogs.io/.
