### ISSUE TITLE
[feature request] file upload to repository

### ISSUE THREAD

**Issue by irstacks** [gogits/gogs#3367]
It's be really great to be able to upload files directly to a repository! 

> a la Github...
![screen shot 2016-08-03 at 06 42 52](https://cloud.githubusercontent.com/assets/10228550/17362945/a3321bb0-5945-11e6-909a-b88751bde1ee.png)

I don't know whether an upload would constitute a `commit`, a `stage`d change, or what exactly, but it sure would make everything a lot more accessible to users without skills (or interest) in working from the command line. 

And, by the way, Gogs rocks. It's awesome. Thank you.

**Comment by xor-gate** [comment]
Probably #1071 web editor for repository files will cover file upload into the repository.

Related issues:

* #3065 for attachment icons
* #2263 wiki add file upload
* #698 / #1614 for general handling of uploaded binaries

**Comment by Unknwon** [comment]
Yes, duplicated to https://github.com/gogits/gogs/issues/1071

**Comment by irstacks** [comment]
Thanks for pointing me there! I just submitted another issue with regard to some bugs I'm having via the PR.

**Comment by cutec-chris** [comment]
#1071 is only for text files right ? What about Binary Files ?

**Comment by cutec-chris** [comment]
Upload and replace (commit)

**Comment by Unknwon** [comment]
Oh, maybe, right. You can't replace. Just commit and push!

**Comment by cutec-chris** [comment]
Maybe should this request reopened ?

**Comment by Unknwon** [comment]
@cutec-chris I just tested, you can't edit binary file but if you just reupload, file will be replaced with new one.
