### ISSUE TITLE
Python docstring are not correctly rendered.

### ISSUE THREAD

**Issue by sciunto** [gogits/gogs#3368]
Hi,
Python docstring must be in red. However, only the first line is in red. (See picture).

- Gogs version (or commit ref): v0.9.48

![spectacle x13191](https://cloud.githubusercontent.com/assets/335370/17368241/76c93f92-5993-11e6-99a9-41bfd280f0ec.png)

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3316
