### ISSUE TITLE
Allow specifying CA (Certificate Authority) for LDAP over TLS

### ISSUE THREAD

**Issue by ToBeReplaced** [gogits/gogs#3372]
If your LDAP provider's certificate is signed by a private CA, you will get messages like the following when trying to connect over TLS:

```
2016/08/02 18:00:44 [...gogs/models/login.go:284 LoginUserLDAPSource()] [E] LDAP Connect error, ipa.example.com:StartTLS: LDAP Result Code 200 "": TLS handshake failed (x509: certificate signed by unknown authority)
```

With openldap-based applications, I have fixed this kind of issue by adding a line like `TLS_CACERT /etc/ldap/ca.crt` to its configuration file at `/etc/ldap/ldap.conf`.

It would be nice to be able to specify the CA for GOGS' LDAP connection. This *may* just be a matter of finding the appropriate configuration setting in go-ldap and exposing it to the user in gogs, but I'm not familiar with go and have been unable to do that work myself.

Thanks for all of the hard work on this project.

**Comment by Unknwon** [comment]
Hi, you can skip verify on LDAP settings page 
![image](https://cloud.githubusercontent.com/assets/2946214/17384290/e36733ba-598f-11e6-9ef2-e2a5af85e640.png)

**Comment by ToBeReplaced** [comment]
Yes, if you are okay with the security risks. I'm not, so in addition to selecting `Skip TLS Verify` I also put an LDAP server on the same host as gogs and am connecting to it via a local ipv4. I'd much rather connect to a remote LDAP server and not have to skip the verification.

**Comment by silverwind** [comment]
I think go looks for root certs at certain system locations [1]. Tryp putting your root into `/etc/ssl/certs`.

[1] https://golang.org/src/crypto/x509/root_unix.go

**Comment by ToBeReplaced** [comment]
@silverwind Yep, that'll do. Thanks.

**Comment by sploadie** [comment]
On Debian Jessie, simply adding my certificate to `/etc/ssl/certs` didn't work for me, but [this source](https://golang.org/src/crypto/x509/root_linux.go) pointed me in the right direction, and once I injected my certificates to the end of `/etc/ssl/certs/ca-certificates.crt` everything worked as intended.
Just in case anyone lse gets stuck as I did.

**Comment by herbat73** [comment]
Tested on Ubuntu 16.10

1. copy your ldap server certificate (ca_server.pem) on your gogs machine and execute

`cat ~/ca_server.pem | sudo tee -a /etc/ssl/certs/ca-certificates.crt`

2. restart server to get access to CA
