### ISSUE TITLE
请问怎么自定义配置端口号。默认端口3000被node服务器占领着。需要修改为其他的。

### ISSUE THREAD

**Issue by 602884291** [gogits/gogs#3373]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please do NOT post questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
2. Please take a moment to search that an issue doesn't already exist.
3. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by bkcsoft** [comment]
In `custom/conf/app.ini` change to
```
[server]
HTTP_PORT = 3001
```

**Comment by bkcsoft** [comment]
Also this is a config-question so I'm closing this anyway :)
