### ISSUE TITLE
Repository for Ubuntu 16.04

### ISSUE THREAD

**Issue by Bambie07** [gogits/gogs#3375]
- Gogs version (or commit ref): 0.9.48-1469893795.10dc330.trusty
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
Running gogs on an Ubuntu 16.04 system causing apt warnings:
```W: https://deb.packager.io/gh/pkgr/gogs/dists/trusty/Release.gpg: Signature by key 6257DF9972462F57A20FFB2AB6D583CCBD33EEB8 uses weak digest algorithm (SHA1)```

Can you provide an updated repository for 16.04 and an working systemd template?

Thanks, Bambie

**Comment by Unknwon** [comment]
From 

> https://deb.packager.io/gh/pkgr/gogs/dists/trusty/Release.gpg

It does not look like it is problem of Gogs itself, please report to packager.io.

**Comment by Bambie07** [comment]
Reading the documention [here](https://packager.io/documentation/distributions/) i think you have to enable builds for Ubuntu 16.04 Xenial. I'm currently using 14.04 packages for 16.04.

I don't want to make a PR because I'm not sure if you have to do other stuff in your packager.io account.

**Comment by Unknwon** [comment]
I don't have such account..

**Comment by VarunAgw** [comment]
I'm also having the same issue since I upgraded

**Comment by VarunAgw** [comment]
I looked into it earlier.

Apparently adding `ubuntu-16.04` into `.pkgr.yml` is not enough. https://packager.io/gh/VarunAgw/gogs/build_runs/4. I don't know why but it is failing for Ubuntu 16.04 each time.

The simplest temporary solution I am aware of is to install gogs from Ubuntu 14.04 PPA followed by creating a crontab for it. Here is also a systemd template. I don't know how to make it work https://github.com/gogits/gogs/blob/master/scripts/systemd/gogs.service.

**Comment by jhasse** [comment]
Can this issue be reopened?

**Comment by jhasse** [comment]
Would be fixed by #3617
