### ISSUE TITLE
DB Problem upgrading from 0.9.28.0527 to 0.9.40.0709

### ISSUE THREAD

**Issue by sokoow** [gogits/gogs#3377]
- Gogs version (or commit ref): 0.9.40.0709
- Git version: 2.7.4
- Operating system: Ubuntu Xenial
- Database (use `[x]`):
  - [ X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ X] No
  - [ ] Not relevant
- Log gist:

## Description

I'm getting following when trying to start 0.9.40.0709 instance on  0.9.28.0527 populated Postgres database:
```
2016/08/04 17:26:47 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: pq: syntax error at or near ""enable_prune""
```

**Comment by Unknwon** [comment]
1. Try upgrade to latest version.
2. Please dump full `xorm.log` here. 

cc @lunny

**Comment by sokoow** [comment]
Latest fails to compile with:
```
lessc public/less/gogs.less public/css/gogs.css
go install "-v" -ldflags '-X "github.com/gogits/gogs/modules/setting.BuildTime=2016-08-04 06:31:30 UTC" -X "github.com/gogits/gogs/modules/setting.BuildGitHash=ee28fd92551961070cff4fe1b37ab94268c2f111"' -tags '""'
github.com/gogits/gogs/models
# github.com/gogits/gogs/models
models/login.go:299: undefined: binding.AlphaDashDotPattern in binding.AlphaDashDotPattern.MatchString
models/mail.go:47: undefined: macaron.NewTemplateSet
models/mail.go:48: undefined: macaron.DEFAULT_TPL_SET_NAME
models/mail.go:51: unknown macaron.TplRender field 'TemplateSet' in struct literal
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 2
```

How can I get xorm.log?

**Comment by Unknwon** [comment]
Looks like you have very outdated dependencies.

https://gogs.io/docs/upgrade/upgrade_from_source

**Comment by sokoow** [comment]
Ok my fault, I didn't do glide install, it compiles fine.

So it seems like Gogs version 0.9.60.0803 works fine, thanks
