### ISSUE TITLE
500 when user leaves organization without relations to any repositories

### ISSUE THREAD

**Issue by pgaborwolters** [gogits/gogs#3379]
- Gogs version (or commit ref): 0.9.58.0726
- Git version: 2.1.4
- Operating system: debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I try leave an organization and the result is:
`{"err":"pq: syntax error at or near \")\"","ok":false}`

Maybe help this thread:
http://stackoverflow.com/questions/21073650/golang-pq-syntax-error-when-executing-sql

**Comment by Unknwon** [comment]
>Can you reproduce the bug at https://try.gogs.io:

**Comment by pgaborwolters** [comment]
No, because I cant leave all team. So, I haven't team, but I'm in organization. This is an anomaly.

**Comment by strk** [comment]
The last time I saw this message (https://github.com/drone/drone/pull/1702) it was an SQL in the form:
``` WHERE x IN () ```, the empty content inside the parenthesis being the culprit.
Were you the last member of the organization, maybe ?
@Unknwon could try.gogs.io possibly be affected or does its backend accept similar queries ?

**Comment by pgaborwolters** [comment]
Im not the last member.

**Comment by Unknwon** [comment]
@strk good hint! But demo site should be affected too if we compose a IN query with 0 value.

**Comment by 0xbaadf00d** [comment]
@pgaborwolters I can't reproduce issue (CentOS 7 / PostgreSQL 9.5 / Gogs 0.9.60.0803). Could you post a list of steps to follow to reproduce issue ?

**Comment by 0xbaadf00d** [comment]
I will submit a PR for this today.
