### ISSUE TITLE
源码安装报错

### ISSUE THREAD

**Issue by toyang** [gogits/gogs#3382]
$ go get -u -v github.com/gogits/gogs
github.com\gogits\gogs (download)
github.com\codegangsta\cli (download)
github.com\Unknwon\cae (download)
github.com\Unknwon\com (download)
github.com\go-macaron\binding (download)
Fetching https://gopkg.in/macaron.v1?go-get=1
Parsing meta tags from https://gopkg.in/macaron.v1?go-get=1 (status code 200)
get "gopkg.in/macaron.v1": found meta tag main.metaImport{Prefix:"gopkg.in/macar
on.v1", VCS:"git", RepoRoot:"https://gopkg.in/macaron.v1"} at https://gopkg.in/m
acaron.v1?go-get=1
gopkg.in\macaron.v1 (download)
github.com\go-macaron\inject (download)
Fetching https://gopkg.in/ini.v1?go-get=1
Parsing meta tags from https://gopkg.in/ini.v1?go-get=1 (status code 200)
get "gopkg.in/ini.v1": found meta tag main.metaImport{Prefix:"gopkg.in/ini.v1",
VCS:"git", RepoRoot:"https://gopkg.in/ini.v1"} at https://gopkg.in/ini.v1?go-get
=1
gopkg.in\ini.v1 (download)
github.com\go-macaron\cache (download)
github.com\go-macaron\captcha (download)
github.com\go-macaron\csrf (download)
github.com\go-macaron\session (download)
github.com\go-macaron\gzip (download)
github.com\klauspost\compress (download)
github.com\klauspost\cpuid (download)
github.com\klauspost\crc32 (download)
github.com\go-macaron\i18n (download)
github.com\Unknwon\i18n (download)
Fetching https://golang.org/x/text/language?go-get=1
https fetch failed: Get https://golang.org/x/text/language?go-get=1: dial tcp 21
6.58.203.17:443: connectex: A connection attempt failed because the connected pa
rty did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond.
package golang.org/x/text/language: unrecognized import path "golang.org/x/text/
language" (https fetch: Get https://golang.org/x/text/language?go-get=1: dial tc
p 216.58.203.17:443: connectex: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connecti
on failed because connected host has failed to respond.)
github.com\go-macaron\toolbox (download)
github.com\go-xorm\xorm (download)
github.com\go-xorm\core (download)
github.com\gogits\git-module (download)
github.com\mcuadros\go-version (download)
github.com\gogits\go-gogs-client (download)
github.com\go-sql-driver\mysql (download)
github.com\gogits\chardet (download)
github.com\bradfitz\gomemcache (download)
Fetching https://gopkg.in/redis.v2?go-get=1
Parsing meta tags from https://gopkg.in/redis.v2?go-get=1 (status code 200)
get "gopkg.in/redis.v2": found meta tag main.metaImport{Prefix:"gopkg.in/redis.v
2", VCS:"git", RepoRoot:"https://gopkg.in/redis.v2"} at https://gopkg.in/redis.v
2?go-get=1
gopkg.in\redis.v2 (download)
Fetching https://gopkg.in/bufio.v1?go-get=1
Parsing meta tags from https://gopkg.in/bufio.v1?go-get=1 (status code 200)
get "gopkg.in/bufio.v1": found meta tag main.metaImport{Prefix:"gopkg.in/bufio.v
1", VCS:"git", RepoRoot:"https://gopkg.in/bufio.v1"} at https://gopkg.in/bufio.v
1?go-get=1
gopkg.in\bufio.v1 (download)
github.com\satori\go.uuid (download)
Fetching https://gopkg.in/ldap.v2?go-get=1
Parsing meta tags from https://gopkg.in/ldap.v2?go-get=1 (status code 200)
get "gopkg.in/ldap.v2": found meta tag main.metaImport{Prefix:"gopkg.in/ldap.v2"
, VCS:"git", RepoRoot:"https://gopkg.in/ldap.v2"} at https://gopkg.in/ldap.v2?go
-get=1
gopkg.in\ldap.v2 (download)
Fetching https://gopkg.in/asn1-ber.v1?go-get=1
Parsing meta tags from https://gopkg.in/asn1-ber.v1?go-get=1 (status code 200)
get "gopkg.in/asn1-ber.v1": found meta tag main.metaImport{Prefix:"gopkg.in/asn1
-ber.v1", VCS:"git", RepoRoot:"https://gopkg.in/asn1-ber.v1"} at https://gopkg.i
n/asn1-ber.v1?go-get=1
gopkg.in\asn1-ber.v1 (download)
github.com\issue9\identicon (download)
github.com\jaytaylor\html2text (download)
Fetching https://golang.org/x/net/html?go-get=1
https fetch failed: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.58.
203.17:443: connectex: A connection attempt failed because the connected party d
id not properly respond after a period of time, or established connection failed
 because connected host has failed to respond.
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html"
(https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.58.203.17
:443: connectex: A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed becau
se connected host has failed to respond.)
Fetching https://golang.org/x/net/html/atom?go-get=1
https fetch failed: Get https://golang.org/x/net/html/atom?go-get=1: dial tcp 21
6.58.203.17:443: connectex: A connection attempt failed because the connected pa
rty did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond.
package golang.org/x/net/html/atom: unrecognized import path "golang.org/x/net/h
tml/atom" (https fetch: Get https://golang.org/x/net/html/atom?go-get=1: dial tc
p 216.58.203.17:443: connectex: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connecti
on failed because connected host has failed to respond.)
Fetching https://gopkg.in/gomail.v2?go-get=1
Parsing meta tags from https://gopkg.in/gomail.v2?go-get=1 (status code 200)
get "gopkg.in/gomail.v2": found meta tag main.metaImport{Prefix:"gopkg.in/gomail
.v2", VCS:"git", RepoRoot:"https://gopkg.in/gomail.v2"} at https://gopkg.in/goma
il.v2?go-get=1
gopkg.in\gomail.v2 (download)
github.com\microcosm-cc\bluemonday (download)
github.com\russross\blackfriday (download)
github.com\shurcooL\sanitized_anchor_name (download)
github.com\lib\pq (download)
github.com\nfnt\resize (download)
github.com\sergi\go-diff (download)
Fetching https://golang.org/x/crypto/ssh?go-get=1
https fetch failed: Get https://golang.org/x/crypto/ssh?go-get=1: dial tcp 216.5
8.199.17:443: connectex: A connection attempt failed because the connected party
 did not properly respond after a period of time, or established connection fail
ed because connected host has failed to respond.
package golang.org/x/crypto/ssh: unrecognized import path "golang.org/x/crypto/s
sh" (https fetch: Get https://golang.org/x/crypto/ssh?go-get=1: dial tcp 216.58.
199.17:443: connectex: A connection attempt failed because the connected party d
id not properly respond after a period of time, or established connection failed
 because connected host has failed to respond.)
Fetching https://golang.org/x/net/html/charset?go-get=1
https fetch failed: Get https://golang.org/x/net/html/charset?go-get=1: dial tcp
 216.58.199.17:443: connectex: A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connectio
n failed because connected host has failed to respond.
package golang.org/x/net/html/charset: unrecognized import path "golang.org/x/ne
t/html/charset" (https fetch: Get https://golang.org/x/net/html/charset?go-get=1
: dial tcp 216.58.199.17:443: connectex: A connection attempt failed because the
 connected party did not properly respond after a period of time, or established
 connection failed because connected host has failed to respond.)
Fetching https://golang.org/x/text/transform?go-get=1
https fetch failed: Get https://golang.org/x/text/transform?go-get=1: dial tcp 2
16.58.199.17:443: connectex: A connection attempt failed because the connected p
arty did not properly respond after a period of time, or established connection
failed because connected host has failed to respond.
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text
/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial
 tcp 216.58.199.17:443: connectex: A connection attempt failed because the conne
cted party did not properly respond after a period of time, or established conne
ction failed because connected host has failed to respond.)
github.com\Unknwon\paginater (download)
github.com\gogits\cron (download)

golang.org/x/crypto这个golang.org/x域名下的所有依赖都无法下载，是不是地址改了？直接访问这个地址就重定向到另外的地址了

**Comment by Unknwon** [comment]
Please use VPN.

**Comment by toyang** [comment]
本来就是用的VPN啊，这个golang.org/x下的包域名已经访问不了了

**Comment by toyang** [comment]
现在直接跳到https://go.googlesource.com/text/了

**Comment by Unknwon** [comment]
That is how `go get` for custom domain works, we don't teach Go here, sorry.
