### ISSUE TITLE
"Copyright All Gogs Contributors"

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3384]
Do you actually feel that [this copyright line](
https://github.com/gogits/gogs/blob/v0.9.60/LICENSE#L1) would be accepted by any court?

"Copyright contributors" is well... a bit too broad AFAIK. I am no lawyer, but it would be better to have either:
* Copyright to a single person (usually the maintainer)
* Copyright to an organisation ( (c) Gogs Blablabla )
* Copyright to a list of authors (usually listed in a file called AUTHORS or CONTRIBUTORS)

"All Gogs Contributors" is just way too unclear, too unspecific and you could mean anyone or no one with this claim. I mean who is a contributor: Everyone who made a PR? (Even if it is just a typo fix?), Everyone who created an issue? Everyone who has direct commit access?
And all of them should have the copyright for the gogs project. So the copyright is split like a cake into pieces :cake: for everyone contributing?

To some amount - at least in the US - you can apply common sense, but this is clearly too uncertain.

Please treat copyright issues seriously.
Of course as long as you (Gogs) do not sue anyone of us that we used your code and  - e.g.  - created a Gogs++ (or whatever... :laughing: ) this is no practical problem, but when you would get the idea of suing everyone who is using Gogs, you may use this "invalid license" as an argument and courts may decide that the license is invalid and that it means all this code here was not released under the MIT license.
To prevent this, just do it right. :smiley: 

**FYI**: Of course, independently of the one mentioned in the LICENSE file contributors always reserve copyright for their own contributions.

**Comment by Unknwon** [comment]
Thanks for your kind advice, but we do not argument non-bug, feature request things here, and currently I completely have no interests on such topic.

License might change if we have to, but not right now. MIT explains things very well, https://opensource.org/licenses/MIT.

I'm 100% OK with Gogs+, Gogs++, Gogs+++, whatever, this is MIT meant to be.

**Comment by rugk** [comment]
You do not seem to understand the issue and it clearly is a bug, so please reopen it.

As said you
1) cannot change the license. You would have to ask all contributors.
2) the current "author" listed in the license file is invalid.

This has nothing to do with the MIT license or whether you like Gogs+, Gogs2 or whatever. It's just a legal issue.

**Comment by Unknwon** [comment]
Please give references to prove your observations.

**Comment by rugk** [comment]
For this:
> 1) You cannot change the license. You would have to ask all contributors.

https://en.wikipedia.org/wiki/Contributor_License_Agreement
https://opensource.stackexchange.com/questions/23/what-are-the-advantages-of-adding-a-contributor-license-agreement-to-a-project/49

2) And the current "author" listed in the license file is invalid.

I currently only have this: https://opensource.stackexchange.com/questions/1522/what-should-be-written-in-mit-license-year-full-name

But I have asked a more generic question: https://opensource.stackexchange.com/questions/4273/which-author-copyright-holder-type-is-allowed-in-the-mit-license-pseudonym-c

**Comment by FSMaxB** [comment]
The license clearly states that the license **can** be changed!

The MIT license allows you to sublicense copies of the software under the condition that the copyright notice and permission notice are included.

**Comment by FSMaxB** [comment]
You only need a CLA in case of Copyleft licenses like the GPL. Permissive ones like the MIT can just be sublicensed however you like.

**Comment by Unknwon** [comment]
CLA has been added (just not sure if it works..)

**Comment by rugk** [comment]
> You only need a CLA in case of Copyleft licenses like the GPL. Permissive ones like the MIT can just be sublicensed however you like.

Mhh, yeah. That's right, but PR might want to [explicitly state](https://opensource.stackexchange.com/questions/4267/how-does-contributing-to-a-floss-project-work-from-a-legal-perspective#comment-11309) they they release their changes under the MIT license.
So yes the CLA can indeed be removed.

----

And BTW: @Unknwon you still completely misunderstand me: **I never wanted a CLA here!** I just provided sources for your bad copyright holder name, which is the actual issue, which is still not fixed.
And as you see it already [scares away Contributors](https://github.com/gogits/gogs/pull/3381#issuecomment-238450837).

1. So at first: Could you finally reopen this issue? (and only close it when it is really fixed)
2. Remove the CLA. I never wanted that and as @FSMaxB correctly pointed out it is quite useless.
3. Change [this line](https://github.com/gogits/gogs/blob/master/LICENSE#L1). I finally have an [answer here](https://opensource.stackexchange.com/questions/4273/which-author-copyright-holder-type-is-allowed-in-the-mit-license-pseudonym-c), so you might have a look at that.
4. If all this is done you might add add [such a statement to your PR template](https://github.com/PrivateBin/PrivateBin/commit/cc65b3b700093c2aebdd73ad35b33b9eec0e3cc0) - if you want.

Just please remove the CLA. I never wanted to get a CLA here. All I want is a better "author" than "Gogs contributors". You may even put your name or pseudonym there.

**Comment by Unknwon** [comment]
Which name do you think is more accurate to put in the LICENSE file?

For CLA, is suggested by my friend, just happens someone mentioned here, so I don't think I'm going to remove that.

**Comment by rugk** [comment]
> Which name do you think is more accurate to put in the LICENSE file?

Your name. :smiley: 
At least if you contributed the most code to this project and were involved from the beginning.

But as you see [there are many choices](https://opensource.stackexchange.com/questions/4273/which-author-copyright-holder-type-is-allowed-in-the-mit-license-pseudonym-c). Some are just worse than others.

> For CLA, is suggested by my friend, just happens someone mentioned here, so I don't think I'm going to remove that.

See @FSMaxB statement. It is useless. What is the aim you want to reach with this CLA?
(Probably a new issue about this should be opened as it is not related to this issue here.)

**Comment by Unknwon** [comment]
>Your name. 😃 
At least if you contributed the most code to this project and were involved from the beginning.

If I changed the name in the LICENSE file, sounds like I need to change all source code file header as well? Because the copyright holder name is changed? I don't think it is a good idea to put under my personal name.

Maybe `Gogs Project` or `Gogs Maintainers`?

>See @FSMaxB statement. It is useless. What is the aim you want to reach with this CLA?

Sounds reasonable, will remove that.

**Comment by Unknwon** [comment]
OK, realized the source file header actually uses `The Gogs Authors`, sounds good to me to put in the LICENSE file.

**Comment by rugk** [comment]
> If I changed the name in the LICENSE file, sounds like I need to change all source code file header as well?

Yes, of course, but a "search & replace" should do it.
I mean the author is even different currently. [Here](https://github.com/gogits/gogs/blob/develop/models/access.go#L1) it e.g. is "The Gogs Authors". I think this is a good string too if you really don't want to use your name.

Although I don't understand why you do not want to use your name as it clearly seems to be *your* project...

> Maybe Gogs Project or Gogs Maintainers?

That's okay too (if you don't want to use your name - again). However "maintainers" is probably not so good as there is only one(?).

**Comment by Unknwon** [comment]
I found pretty common that jQuery and .NET Core states `xx Foundation and Contributors`, is that any different from what Gogs has now?

**Comment by rugk** [comment]
Yeah, because `xx Foundation` is a registered/official foundation. See https://blog.jquery.com/2012/03/06/announcing-the-jquery-foundation/ for jQuery.

Of course you can add `and Contributor`, but this does not make a big difference.

**Comment by Unknwon** [comment]
OK, license file updated, should be good now.

PS: found Rails is using DDH's personal name, so I use `The Gogs Authors` to remind consistency of all existing source files.

**Comment by rugk** [comment]
@FSMaxB FYI: I've [asked this CLA/MIT license question](https://opensource.stackexchange.com/questions/4284/is-a-cla-only-useful-for-copyleft-licensed) on Stackoverflow.

**Comment by FSMaxB** [comment]
To summarize what is said on StackOverflow: You don't need it to change the license but might want it for other reasons.

https://opensource.stackexchange.com/questions/23/what-are-the-advantages-of-adding-a-contributor-license-agreement-to-a-project
