### ISSUE TITLE
Logged in after verification without login check

### ISSUE THREAD

**Issue by waldiTM** [gogits/gogs#3389]
- Gogs version (or commit ref): 0.9.64.0805
- Git version: ?
- Operating system: ?
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/user/activate?code=XXX)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

After using the verification URL sent by unsecured email, the user is logged in immediately without asking for the password to the newly created account. An attacker can use this link to gain access to newly created accounts without any further check.

**Comment by ftrtyyuukjnbvd** [comment]
@waldiTM can you please provide a step by step instruction to reproduce this?

The token is used only once. So, after you've clicked the link in the email and you've been signed in, it's no longer valid. If you use the same token again you should get this error message:

> Sorry, your confirmation code has expired or not valid.
