### ISSUE TITLE
init and systemd script error

### ISSUE THREAD

**Issue by WangQiru** [gogits/gogs#3392]
Hi there,

I encountered this bug when using [systemd script from master](https://raw.githubusercontent.com/gogits/gogs/master/scripts/systemd/gogs.service) to run gogs 
`gogs Active: failed (Result: start-limit)`

or randomly it became 
`start request repeated too quickly, refusing to start.`

When using init script from [master](https://raw.githubusercontent.com/gogits/gogs/master/scripts/init/debian/gogs)  `do_start()` , though it returned 0 but `gogs web` was not executed. I have to manually start gogs again otherwise git.exmaple.com will give 500 error.

Final solution is to use supervisord, seems wasted because I only use it for gogs.

Running Debian 8 x64, tried with nginx and apache.

**Comment by Unknwon** [comment]
Scripts are just template, not usable directly, and not enough information about what you have done.

Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.

**Comment by atul9911** [comment]
Remove `Restart=always` from systemd file and error will be resoved. This is worked for me
```
[Unit]
Description=Gogs
After=syslog.target
After=network.target
#After=mariadb.service mysqld.service postgresql.service memcached.service redis.service

[Service]
# Modify these two values and uncomment them if you have
# repos with lots of files and get an HTTP error 500 because
# of that
###
#LimitMEMLOCK=infinity
#LimitNOFILE=65535
Type=simple
ExecStart=/etc/init.d/gogs start
ExecStop=/etc/init.d/gogs stop
ExecReload=/etc/init.d/gogs restart
User=root
Group=root

[Install]
WantedBy=multi-user.target
```

**Comment by WangQiru** [comment]
@atul9911 Thanks pal 👍 , I think we are all using Docker nowadays, aren't we?

**Comment by atul9911** [comment]
@WangQiru Actually yes. But we are not using that until now .could  you please help me to understand how the docker will be helpful  in this??

**Comment by Fastidious** [comment]
@WangQiru nope, no Docker here.

**Comment by WangQiru** [comment]
@atul9911 If you get Docker up and running , just follow [the official guide](https://github.com/gogits/gogs/tree/master/docker), all you need to do is add `--restart=always` to you docker run command, in this case it does the exact job as systemd.

@Fastidious Docker makes my life easier, give it a try?

**Comment by atul9911** [comment]
But how would you do custom settings if you are using docker @WangQiru

**Comment by WangQiru** [comment]
@atul9911  use `-v` volume command to mount your file or folder to the container. see [the official guide](https://github.com/gogits/gogs/tree/master/docker#usage).

**Comment by atul9911** [comment]
You still not get the actual problem. I want to use custom settings for gogs.could you please help me how can I do that?? @WangQiru

**Comment by WangQiru** [comment]
@atul9911 Read my reply to your email, and docker's volume command 😆

**Comment by denisgolius** [comment]
Therefore, Docker does not solve all the problems in our days.
