### ISSUE TITLE
Broken avatars when using gogs in a subfolder

### ISSUE THREAD

**Issue by AsamK** [gogits/gogs#3393]
- Gogs version (or commit ref): 08c976f8117b92b25ea197e7dc0372b49d9ee412
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
When using gogs in a subfolder, e.g. https://domain.tld/gogs/ , avatar images fail to load. Gogs uses an avatar path relative to the location of the gogs path, not relative to the server root.
Instead of loading the avatars from https://domain.tld/gogs/avatars/1 , gogs tries to load them from https://domain.tld/avatars/1 , which fails.
The problem seems to be caused by the fix for #3348 : 50422f1fc226d71fe2f5f701c7ebdd1a5f2d143e .

app.ini:
DOMAIN = domain.tld
ROOT_URL = https://domain.tld/gogs/

**Comment by Unknwon** [comment]
Dump your `app.ini` and reverse proxy settings.

**Comment by AsamK** [comment]
nginx config, gogs is listening on port 3000:

        location /gogs {
                rewrite /gogs/(.*) /$1 break;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_read_timeout 120;
                proxy_connect_timeout 10;
                proxy_pass http://127.0.0.1:3000/;
                proxy_redirect default;
        }

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by AsamK** [comment]
The fix works, thanks for fixing this so quickly!
