### ISSUE TITLE
Failed to push: remote already exists

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3394]
Attempts to force-push to a pull-request associated branch fails with "remote already exists".
Full error, with trace enabled:
```
2016/08/06 05:53:58 [T] PushToBaseRepo[4]: pushing commits to base repo 'refs/pull/4/head'
2016/08/06 05:53:58 [.../gogs/models/pull.go:555 AddTestPullRequestTask()] [E] PushToBaseRepo: headGitRepo.AddRemote: exit status 128 - fatal: remote tmp-pull-10 already exists.
```

Originally reported here: https://git.osgeo.org/gogs/postgis/postgis/pulls/4#issuecomment-217

Gogs version is 0.9.27.0512 

Ideas of whether this is a known bug and/or of workarounds ?

**Comment by strk** [comment]
I've noticed that the data/tmp/local directory does contain a folder named "4" (as the pull request) which looks like containing the code from the "postgis" project (although it does not have any namespacing). Is it expected for that folder to even exist ? Creation date is 2 days ago.

**Comment by strk** [comment]
The http.log file contains this error:
```
2016/08/07 14:33:19 [...routers/repo/http.go:380 serviceRpc()] [E] fail to serve RPC(upload-pack): exit status 128
```

It's actually repeated many times, at different times, with no further detail

**Comment by Unknwon** [comment]
Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md
