### ISSUE TITLE
Redefine global mirror interval

### ISSUE THREAD

**Issue by colundrum** [gogits/gogs#3398]
Hi,

Can you create a variable in the custom/conf/app.ini to redefine the value of Interval (we can see this value at https://github.com/gogits/gogs/blob/master/models/repo.go#L722) without recompiling Gogs.

I've already asked to the discuss : [Is it possible to redefine the global mirror interval?](https://discuss.gogs.io/t/is-it-possible-to-redefine-the-global-mirror-interval/540)

Thanks

- Gogs version (or commit ref): 0.9.48.0722
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

**Comment by 0xbaadf00d** [comment]
I can implement this issue if no one already took it.

@Unknwon Do you have any advice for the key name and on what category put it ?

**Comment by Unknwon** [comment]
@0xbaadf00d thanks, maybe `DEFAULT_INTERVAL` is more obvious?

**Comment by 0xbaadf00d** [comment]
Of course, I'll make the changes in the evening.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
