### ISSUE TITLE
Crash upon visiting /pulls

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3399]
- Gogs version (or commit ref): 0.9.67.0806 
- Can you reproduce the bug at https://try.gogs.io: NO

## Description

I get a fatal error printed in the page:
```
template: repo/issue/list:11:148: executing "repo/issue/list" at <.PullRequestCtx.Base...>: nil pointer evaluating *models.Repository.Link
```

When visiting the ``/strk/test2/pulls`` page while logged as ``strk2`` (who has a fork of ``/strk/test2``).
Visiting that page from an unlogged window succeeds.
Visiting that page as the ``strk`` user succeeds.

The only trace of error in the logs, when the visit fails, is:
```
[Macaron] 2016-08-08 19:58:49: Completed /strk/test2/pulls 500 Internal Server Error in 24.107373ms
```

**Comment by strk** [comment]
Exact commit giving the problem is e5bf4281b5519d845dd85a153831ba5cc1117590

**Comment by strk** [comment]
Database backend is PostgreSQL 9.3.6

**Comment by strk** [comment]
The referenced line in the template is:
```
          <a class="ui green button {{if not .PullRequestCtx.Allowed}}disabled{{end}}" href="{{if not .PullRequestCtx.Allowed}}#{{else}}{{.PullRequestCtx.BaseRepo.Link}}/compare/{{.Repository.DefaultBranch}}...{{.PullRequestCtx.HeadInfo}}{{end}}">{{.i18n.Tr "repo.pulls.new"}}</a>
```

Whereas column 148 is ``{{.PullRequestCtx.BaseRepo.Link}}``, which is in the block where PullRequestCtx.Allowed is true (which I guess is the reason why it works fine when NOT logged in).

**Comment by strk** [comment]
Ok, I could reproduce on try.gogs.io:
https://try.gogs.io/unknwon/issue-2556/pulls

It was enough for me to fork the above repository and then visit its /pulls url.

@Unknwon I guess you can reproduce as well by forking someone's repository and then visit its pull list.

I do belive the repository being forked needs to have no other pull requests

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by strk** [comment]
Seems to be working fine on try.gogs.io, thanks.
