### ISSUE TITLE
SSH-Keys should be trimed 

### ISSUE THREAD

**Issue by Di3g0** [gogits/gogs#3400]
" " (ASCII 32 (0x20)), an ordinary space.
"\t" (ASCII 9 (0x09)), a tab.
"\n" (ASCII 10 (0x0A)), a new line (line feed).
"\r" (ASCII 13 (0x0D)), a carriage return.
"\0" (ASCII 0 (0x00)), the NUL-byte.
"\x0B" (ASCII 11 (0x0B)), a vertical tab.

should be removed from ssh-keys

**Comment by Unknwon** [comment]
Any references?

**Comment by 0xbaadf00d** [comment]
A co-worker encountered this issue today, maybe yes the SSH public key must be trimmed to remove, at least extra space before and after the SSH public key.
