### ISSUE TITLE
Updating a PR original description fails silently

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3406]
- Gogs version (or commit ref): 0.9.68.0807
- Database (use `[x]`): irrelevant (both PostgreSQL and whatever is used on try.gogs.io)
- Can you reproduce the bug at https://try.gogs.io: yes, see https://try.gogs.io/tests/test-pr-summary-update/pulls/1#issuecomment-997

## Description

Descriptions of Pull Request for a Repository with Internal Issue Tracker disabled cannot be updated.
When you try, hitting "Save" results in the old content remaining in place and no error being shown to the user.

Both the PR title _and_ the PR original submission/description cannot be updated.
It is no problem updating the subsequent comments.

Initially reported here: https://git.osgeo.org/gogs/postgis/postgis/pulls/4#issuecomment-231

Note: there's no problem IFF the target repository has internal tracker enabled.

cc @Unknwon

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.
