### ISSUE TITLE
Log rotation only rotates gogs.log

### ISSUE THREAD

**Issue by vroomanj** [gogits/gogs#3413]
- Gogs version (or commit ref): 0.9.64.0805
- Git version: 2.9.2
- Operating system: FreeBSD
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

Opening issue at the request of @Unknwon 

With the following settings for log rotation only gogs.log gets rotated:

```
[log.file]
LOG_ROTATE      = true
DAILY_ROTATE    = true 
MAX_DAYS        = 25
```

The http.log, update.log and xorm.log do not get rotated. This is problematic for me because we have a policy on log retention that I need to follow. What is the appropriate work around for this issue and/or can it be fixed relatively easy and soon?

**Comment by Unknwon** [comment]
Note: because rotate requires app running long enough, but processes to write other log files usually lives only for few seconds.

**Comment by vroomanj** [comment]
@Unknwon: I'm not sure if this is an appropriate place to put this but this is my opinion on how log rotation should work. Let me know your thoughts.

Logs should rotate on only one of either a daily basis, number of lines basis, or size basis. I don't believe they should rotate on multiple factors. For daily log rotation ALL Gogs logs should rotate at midnight. Ideally there would also be the option to compress rotated logs. And to take it a step further sometimes there is the option for a delayed compression of logs (meaning the previous log stays uncompressed until the next rotation).

**Comment by Unknwon** [comment]
@vroomanj yes, I think you're right, the currently log implementation is crap..

**Comment by Unknwon** [comment]
`xorm.log` is now the only file won't rotate.

**Comment by Unknwon** [comment]
For `xorm.log`, please follow https://github.com/gogits/gogs/issues/3183.
