### ISSUE TITLE
Raspberry Pi Zero - Illegal Instruction error when running "./gogs web"

### ISSUE THREAD

**Issue by neonn** [gogits/gogs#3415]
- Gogs version (or commit ref): v0.9.48 and above, Linux arm build.
- Git version: 2.1.4
- Operating system: Raspbian (latest version, installed via NOOBS), Raspberry Pi Zero with camera port
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes
  - [ x] No
  - [ ] Not relevant
- Log gist:
?? Not sure if this is needed. 
## Description
Gogs fails to initialise when running `./gogs web` for the first time and every subsequent time, making installation impossible unless reverting to v0.9.13 or below. It will always appear with `Illegal instruction` and immediately quit.

I understand that this may not be the correct hardware to run Gogs on, but it can be done, as seen in v0.9.13.

I do not understand Go well enough to help with this, so I would appreciate any help with this, as I want to use it for university work.

I am using a default Raspbian install from NOOBS.
...

**Comment by Unknwon** [comment]
Hi, currently, Gogs is only field tested on raspi2, that is the reason we only provide that binary.

If you want to run on raspi0, you might have to compile yourself [from source code](https://gogs.io/docs/installation/install_from_source).

>Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
