### ISSUE TITLE
如果在已经部署的Gogs中，将源码自动发布到其他的服务器

### ISSUE THREAD

**Issue by Brave-Cheng** [gogits/gogs#3416]
看了文档，没有这块相关的内容，我的问题是，在一台服务器中部署并配置了gogs后，如果在本地push 代码到gogs后，自动发布到其他的服务器中

**Comment by Unknwon** [comment]
Git hook or webhook.

**Comment by Brave-Cheng** [comment]
@Unknwon Please give me a introduction
