### ISSUE TITLE
Wrong Issue Count - Due to duplicate code

### ISSUE THREAD

**Issue by palamccc** [gogits/gogs#3417]
- Gogs version (or commit ref): develop
- Git version: 2.7.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In Dashboard, Issues count are wrong, 'Created by you' and 'Assigned to you' are same.
When i tried to debug, i found **identical code** for both count.
https://github.com/gogits/gogs/blob/699c71d319138b326bcb4fdf8e6eeac03c82e5b9/models/issue.go#L909-L915

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.
