### ISSUE TITLE
Bad URL generation if same commit referenced multiple times on same message

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3420]
- Gogs version (or commit ref): 0.9.71.0808
- Git version: 1.8.3.1
- Operating system: CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zero-x-baadf00d/psychic-soul/issues/1)
  - [ ] No
  - [ ] Not relevant

## Description

when the same commit tag is referenced more than one time on a single message, generated link are not valids.

By example:
```
2eb7f261c1502b6f8981267f6c142f4563da5f37 or 2eb7f261c1502b6f8981267f6c142f4563da5f37
```

become 

![image](https://cloud.githubusercontent.com/assets/1005086/17545254/6f118176-5edc-11e6-9cf5-d6a869faf25a.png)
 
I think it come from `modules/markdown/markdown.go::RenderSha1CurrentPattern::line.260`

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
