### ISSUE TITLE
Failed to add Webhook

### ISSUE THREAD

**Issue by carliandro** [gogits/gogs#3428]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
Hi guys,
I installed Gogs and I am trying integrate with Jenkins. I did read documentation but I don't found nothing about the integration. 

Both are installed on my network.

I have installed Gogs Plugin(1.0.4) on my Jenkins server.
I create a job on jenkins configured to "see" my gogs repository. I can execute a build and the Jenkins get all sources and build them.

In Gogs I configured a Webhook pointing out for my job. But I receive the follow message: 
Problem accessing /jenkins/. 
No valid crumb was included in the request

Can you help me
...

**Comment by Unknwon** [comment]
Hi, please follow the issue template. You should probably file issue to the plugin author not here..
