### ISSUE TITLE
Give Gogs a feature to auto update or ask if you want the new update

### ISSUE THREAD

**Issue by Madmorgan007** [gogits/gogs#3429]
Hi,

First of all I love this project I have noticed over the last month that @Unknwon has done 4 releases and four times I have updated my server it would be nice if Gogs could auto update or ask if you want to update so I don't have to keep recompiling source code on my server to run the new version.

Thanks

**Comment by 0xbaadf00d** [comment]
Maybe a cron every 24 hours (or with an interval configurable via app.ini) could fetch `https://raw.githubusercontent.com/gogits/gogs/master/templates/.VERSION` to check if a newest version is available.

**Comment by Madmorgan007** [comment]
OK @0xbaadf00d I agree with the self auto update is a bad idea. But if your the admin on the Gogs site then in the admin section it would be nice to have there a option to check or apply update. I do like the `./gogs upgrade [--yes]` as well but this was still means you have to keep coming back to GitHub to check for new releases that @Unknwon has created. That option would be OK if the web site had a banner or popup letting the admin know to run that command.

**Comment by 0xbaadf00d** [comment]
Is it possible to use Github API to get latest release created `GET /repos/:owner/:repo/releases/latest` (https://developer.github.com/v3/repos/releases/#get-the-latest-release) and get link to download right package (ie: linux_amd64.zip).

**Comment by Unknwon** [comment]
Hi, please merge result of this thread to https://github.com/gogits/gogs/issues/1670
