### ISSUE TITLE
Cannot connect to PostgreSQL via IPv6 address

### ISSUE THREAD

**Issue by pmattern** [gogits/gogs#3437]
Directive `HOST` in section `[database]` of `app.ini` doesn't support IPv6 addresses which makes Gogs fail, at least when PostgreSQL is used.

When IPv6 addresses get stated without brackets `gogs.log` reads
> [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 0.0.7.211:74: connect: invalid argument

When brackets are used there are messages like this
> [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: Fail to connect to database: parse postgres://\<user\>:\<password\>@[fd99:aaaa/gogs1?sslmode=disable: missing ']' in host

connecting to a ULA `fd99:aaaa:bbbb:...` which all in all suggest there's something wrong with the parsing of the addresses.
Both FQDNs and IPv4 addresses are accepted. The connection to the database server works flawlessly via IPv6 as can be seen by setting the hostname in `HOST` of app.ini and configuring the database server to accept corresponding IPv6 connections only.
On a side note directive `HOST_ADDR` in `[server]` accepts IPv6 addresses, too.

Seen running b756806 on Arch Linux, hence PostgreSQL 9.5.3.

**Comment by Unknwon** [comment]
Nore: ref: https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by 0xbaadf00d** [comment]
Issue seem come from _[models/models.go line.117](https://github.com/gogits/gogs/blob/aa1fc30b898a928ddafbfd0fddc47547c04f96e5/models/models.go#L117)_. conn string are splitted on the first found ":" and not the last

**Comment by Unknwon** [comment]
@0xbaadf00d not only that, IPv6 requires special syntax: `[2001:db8::1234]`

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by pmattern** [comment]
Running f59d2dd of branch `develop` the problem seems to be fixed.
All values of directive `HOST` stated in the first comment of #3442 are working here, too, much as ULA or Global Unicast addresses with or without stating the port.
