### ISSUE TITLE
Cant use _ in repository-name

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3440]
- Gogs version (or commit ref):  0.9.71.0809 
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When I try to use `_` in the repository name it changes it to a space. When I try to create it with the spaces it says `Repository name has already been taken.`

**Comment by Unknwon** [comment]
https://try.gogs.io/unknwon/_

**Comment by rikvdh** [comment]
Ok, i see. Why I cant see the underscores while typing?

**Comment by Unknwon** [comment]
Ask your browser maybe?....

**Comment by bkcsoft** [comment]
@rikvdh most likely a font-issue. try copy-pasting it to e.g. notepad and verify if it's been removed

**Comment by rikvdh** [comment]
I see,

The `font-family: "Helvetica Neue", "Meiryo Ui", "Microsoft YaHei", Arial, Helvetica, sans-serif !important` messes it up. I use Chrome on Windows 10. It uses the `"Microsoft YaHei"` from this family. When I remove this via developer-tools in chrome it appears in Gogs.

My setup isn't that odd.
