### ISSUE TITLE
Cant use _ in issue title

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3441]
- Gogs version (or commit ref):  0.9.71.0809 
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When I create an issue `_` is replaced with a space while typing. This is not desirable since sometime referencing to functions in issue-titles can become very confusing when having `_` in function names.

**Comment by Unknwon** [comment]
https://try.gogs.io/unknwon/_/issues/1
