### ISSUE TITLE
Labels are not ordered by name

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3445]
- Gogs version (or commit ref): 0.9.71.0809
- Git version: 2.9.2
- Operating system: CentOS 7 64 bit
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zero-x-baadf00d/psychic-soul/labels)
  - [ ] No
  - [ ] Not relevant

## Description
Labels are not ordered by name but by ID (primary key). For a project with a lot of labels (like Gogs) it could become tricky to find the needed labels if the list is not order by name.

![image](https://cloud.githubusercontent.com/assets/1005086/17620032/ac087ae0-6089-11e6-9d4b-e8673e5be77a.png)

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3189
