### ISSUE TITLE
500 when an organization is deleted

### ISSUE THREAD

**Issue by xgaia** [gogits/gogs#3447]
- Gogs version (or commit ref): 0.9.71.0809
- Git version: 2.1.4
- Operating system: Raspbian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If i delete an organization, Dashboard, issues and PR tab show me an error 500

![screenshot_20160812_174903](https://cloud.githubusercontent.com/assets/18330770/17628304/175e1c20-60b5-11e6-80ac-bb08dcfd5b28.png)

But all my repos are here and I can access them by clicking to "your profile"

**Comment by xgaia** [comment]
EDIT: I fix this by deleting infos in the org_user table

```sql
DELETE FROM org_user;
```

**Comment by Unknwon** [comment]
>Log gist:

**Comment by dlamb5** [comment]
Can confirm this error.  Error in log ('6' in this scenario is the deleted organization):

2016/08/25 12:33:50 [...routers/user/home.go:47 getDashboardContextUser()] [E] GetOrganizations: user does not exist [uid: 6, name: ]

**Comment by Unknwon** [comment]
On demo site?

**Comment by dlamb5** [comment]
Ah, no I was not able to reproduce on the demo site.  It looks like my version is slightly behind (0.9.71.0809), I will try updating to see if it resolves the issue.

I believe these are the pertinent xorm logs (gathered from my local machine):
https://gist.github.com/dlamb5/bd2dc25cbf76f5850f23367e5424b3d7

**Comment by dlamb5** [comment]
I guess I'll chuck these in here to be thorough:

* Gogs version (or commit ref): 0.9.71.0809
* Git version: 2.9.3.windows.1
* Operating system: Windows 10
* Database (use `[x]`):
 * \[ ] PostgreSQL
 * \[ ] MySQL
 * \[x] SQLite
* Can you reproduce the bug at https://try.gogs.io:
 * \[ ] Yes (provide example URL)
 * \[x] No
 * \[ ] Not relevant
* Log gist:
