### ISSUE TITLE
Add subcommand to create user

### ISSUE THREAD

**Issue by jonathan-kosgei** [gogits/gogs#3454]
Hi,

I'm looking to automate a gogs install with a default user already setup. A default api user.
Or how to automate creation of admin user.
How exactly do I go about this?

Thanks.

**Comment by jonathan-kosgei** [comment]
Fabric8 have a docker image that creates a default admin user, they seem to do it via sqlite though I'm not sure. Any idea how I could do this myself? https://github.com/fabric8io/docker-gogs

**Comment by Unknwon** [comment]
As long as you can compute same hash result as Gogs, it's just simply insert a row in table.

**Comment by Unknwon** [comment]
If you pull latest `develop`, now you can create new user in CLI after install:

```
/gogs admin create-user --name=user4 --password=applejoe --email=user4@user.com --admin=true
```

Get help from by `./gogs admin create-user -h`.

**Comment by jonathan-kosgei** [comment]
Brilliant! That was incredibly responsive! 5 hours from issue to feature! Thank you ! I'm just picking up Go, can't wait to be able to contribute to gogs! Again thank you!

**Comment by jonathan-kosgei** [comment]
Hi,
So in this version of gogs , there's the admin command that does:
```
# gogs admin
NAME:
   Gogs admin - Allow using internal logic of Gogs without hacking into the source code
to make automatic initialization process more smoothly

USAGE:
   Gogs admin command [command options] [arguments...]

COMMANDS:
     create-user  Create a new user in database

OPTIONS:
   --help, -h  show help
```

Is it possible to flesh out the admin command with at least : 
 - create-repo
and 
 - create-webhook

Is it possible to point me to the code used to setup the create-user I could attempt to add the above commands and any others in future, this can be handled via the API but it would make sense to have these available under the admin command.

Thanks.

@Unknwon

**Comment by jonathan-kosgei** [comment]
Found this https://github.com/gogits/gogs/blob/a5b88c4d0cd7ff7e167fe1c62a40ff8c103909f3/cmd/admin.go, will try to add the above commands.

**Comment by rulatir** [comment]
Can I please have the *exact* incantation or sequence of incantations for creating the admin user on a freshly installed gogs using the gogs/gogs docker image from dockerhub? I was able to successfully run the whole thing, set up database for it etc., but I am locked out of it because there is no admin user. Quite a showstopper!

**Comment by initbar** [comment]
@rulatir it should've been part of the setup process under **Admin Account Settings**.

![202_gogs_setup](https://user-images.githubusercontent.com/12630151/38157981-97bbf372-345a-11e8-8226-623ef968d87b.png)

**Comment by raquelhortab** [comment]
> Hi,
> 
> I'm looking to automate a gogs install with a default user already setup. A default api user.
> Or how to automate creation of admin user.
> How exactly do I go about this?
> 
> Thanks.

Hi! 
I am trying to do something similar and I was wondering how you achieved to automate the gogs install so that it is not necessary to use the browser.
 I am trying to use gogs inside a docker container so I have to set everything up in the Dockerfile, however, all the documentation I find tells you to enter the setup webpage and click the install button...

Thanks!

**Comment by achilleas-k** [comment]
The installation is basically just the creation of an app.ini file, so if you have a app.ini in the default location (or the custom location if configured) the service will start up normally and it will be "installed".
