### ISSUE TITLE
Gogs uses `http` proto instead of `https` for avatars

### ISSUE THREAD

**Issue by 18augst** [gogits/gogs#3456]
- Gogs version (or commit ref): 0.9.77.0814
- Git version: 2.8.3
- Operating system: Alpine Linux 3.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I got gogs working with Nginx as reverse-proxy. Nginx uses SSL, but Gogs not. Here's relevant section from my gogs config:

    [server]                                                                       
    PROTOCOL               = http                                                      
    DOMAIN                 = gogs                                                      
    ROOT_URL               = https://gogs/                                             
    HTTP_ADDR              = 10.0.0.40                                                 
    HTTP_PORT              = 8080                                                              
    LOCAL_ROOT_URL         = https://%(HTTP_ADDR)s:%(HTTP_PORT)s/              
    ... ssh_conf_skipped
    OFFLINE_MODE           = true                                                      
    STATIC_ROOT_PATH       =         

But, it still writes `http://gogs/....` as avatars source instead of `https://gogs/...`.
I looked into [this](https://github.com/gogits/gogs/issues/3348) and [that](https://github.com/gogits/gogs/issues/3393)

**Comment by Unknwon** [comment]
I don't know what you're talking about. What is "it" and write "what"?

**Comment by 18augst** [comment]
Here is screenshot:
![gogs_bug](https://cloud.githubusercontent.com/assets/6197738/17655412/1ebcd57c-62bf-11e6-8a63-d4596f601213.png)

**Comment by Unknwon** [comment]
How do you determine you changed the right config file?

**Comment by 18augst** [comment]
All my issues are related to my system's RC
