### ISSUE TITLE
404 js/jquery.are-you-sure.js

### ISSUE THREAD

**Issue by 18augst** [gogits/gogs#3457]
- Gogs version (or commit ref): 0.9.77.0814
- Git version: 2.8.3
- Operating system: Alpine 3.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
After I've updated gogs to latest `develop` it began to throw a new error:

    https://gogs/js/jquery.are-you-sure.js
    
There's no such file in `$GOGSROOT/public/js` directory.

**Comment by Unknwon** [comment]
Reproduce on demo site as required.

**Comment by 18augst** [comment]
Did you mean upload my current gogs source there?

**Comment by Unknwon** [comment]
I have reason to believe you have outdated `templates` files.

**Comment by 18augst** [comment]
Pulled `develop` branch again, restarted gogs, cleaned browser's cache, no luck.

**Comment by Unknwon** [comment]
How do you confirm you're running version `0.9.77.0814`?

**Comment by 18augst** [comment]
@Unknwon you were right about outdated templates. All my issues are related to my system's RC. it's a shame for me. Very sorry, I'll close it myself.

**Comment by Kruemmelmonster** [comment]
@18augst what did you do to resolve this issue?
