### ISSUE TITLE
Security issue on repository creation

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3461]
- Gogs version (or commit ref): 0.9.77.0814
- Operating system: CentOS 7 / Ubuntu 16.04
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes ~~(https://try.gogs.io/zero-x-baadf00d/test)~~ _force deletion by @unknwon_
  - [ ] No
  - [ ] Not relevant

## Description

Is it possible, for a attacker, to edit HTML (ie: with Chrome developper tools) and change value in form for the _Readme_ and _Licence_ to use.

By example:

If we put __../app.ini__ rather than __Default__ for the Readme. The created repository will have a Readme file containing the content of `app.ini`

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by 0xbaadf00d** [comment]
yeah issue seams fixed (tested on Linux and Windows)
