### ISSUE TITLE
Error while upgrading gogs

### ISSUE THREAD

**Issue by gshan88** [gogits/gogs#3463]
- Gogs version (or commit ref):  0.9.71
- Git version: 2.6.6
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist:

## Description

We are trying to upgrade gogs to the version 0.9.71. While upgrading we are getting the following error

[...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: Error 1062: Duplicate entry '4-61' for key 'UQE_issue_REPO_INDEX.

Can you advise on the solution.

...

**Comment by Unknwon** [comment]
1. Upgrade from which version?
2. InnoDB?

**Comment by gshan88** [comment]
Upgrade from which version :  0.8.10
InnoDB? : Yes

**Comment by Unknwon** [comment]
OK, I think the problem is somehow the database unique constraint is broken before we force add it. Find record `repo_id=4` and `index=61` in table `issue`, there could be two or more results. Right now you have to manually change those indexes.

Continue discussion on https://discuss.gogs.io/
