### ISSUE TITLE
Diff signs (+/-) are not showing

### ISSUE THREAD

**Issue by peterurk** [gogits/gogs#3464]
- Gogs version (or commit ref): 0.9.74.0811
- Git version: 1.7.1
- Operating system:  Windows 10.0 build 14903
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When using Windows High Contrast mode the '+' and '-' icons in diffs are not being shown. The most probable cause of this issue is that most major browsers working with the windows high contrast mode hide background images. The easiest solution is to either replace the images with actual text or using a font to display the icons. I know this is a very specific problem but still hope that it can be tackled.

**Comment by Unknwon** [comment]
Hi, I can't understand this without screenshots.

**Comment by peterurk** [comment]
Here is a screenshot of the diff window.

![screenshot](https://cloud.githubusercontent.com/assets/3061456/17665299/6014751c-62fa-11e6-90b7-a9ef8724115a.png)

**Comment by peterurk** [comment]
The problem can most probably be found and fixed in the file gogs.css. After taking a closer look i noticed that you are not using '+/-' to show which lines are changed. Instead, you are using two different colors to display these lines. However, in windows high contrast mode these colors are removed. I can't really think of a solution except for replacing the colors with '+' and '-'.

	# gogs/public/css/gogs.css 
	1981| .repository .diff-file-box .code-diff tbody tr.del-code td.add-code {
	1982|   background-color: #eaffea !important;
	1983|   border-color: #c1e9c1 !important;
	1984| }
	1985| .repository .diff-file-box .code-diff tbody tr.del-code td.add-code pre {
	1986|   background-color: #eaffea !important;
	1987|   border-color: #c1e9c1 !important;
	1988| }
	1989| .repository .diff-file-box .code-diff tbody tr.del-code td,
	1990| .repository .diff-file-box .code-diff tbody tr.del-code pre {
	1991|   background-color: #ffecec !important;
	1992|   border-color: #f1c0c0 !important;
	1993| }
	1994| .repository .diff-file-box .code-diff tbody tr.del-code td.halfwidth {
	1995|   width: 50%;
	1996| }
	1997| .repository .diff-file-box .code-diff tbody tr.add-code td,
	1998| .repository .diff-file-box .code-diff tbody tr.add-code pre {
	1999|   background-color: #eaffea !important;
	2000|   border-color: #c1e9c1 !important;
	2001| }
	2002| .repository .diff-file-box .code-diff tbody tr.add-code td.halfwidth {
	2003|   width: 50%;
	2004| }
	2005| .repository .diff-file-box .code-diff tbody tr .removed-code {
	2006|   background-color: #ff9999;
	2007| }
	2008| .repository .diff-file-box .code-diff tbody tr .added-code {
	2009|   background-color: #99ff99;
	2010| }

**Comment by Unknwon** [comment]
Good point.

cc @andreynering

**Comment by andreynering** [comment]
I don't think we could fix this with CSS (but I may be wrong).

@Unknwon Re-adding the `+` and `-` signs would be very simple, so let's go to this solution? I just noticed GitHub also shows it.

**Comment by Unknwon** [comment]
@andreynering agree. 

I remember we do have signs (checking with disabling HighlightJS)

**Comment by Unknwon** [comment]
Committed wrong file in first mention commit... 0.0

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/gogs/gogs/commit/2625193a4820a89355ca1b8b7c910f0f4243baab.

**Comment by peterurk** [comment]
Thumbs up for the quick response and solution. Seems to be working the way I would expect it to.
