### ISSUE TITLE
Blank PR title causes exception.

### ISSUE THREAD

**Issue by binford2k** [gogits/gogs#3466]
- Gogs version (or commit ref): 94392a7af3d07f79adab195acfb7c1b545f68be9
- Git version: git version 1.8.3.1
- Operating system: CentOS Linux release 7.2.1511
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL) https://try.gogs.io/poop/blahs/compare/master...adgdsgdsg
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When creating a pull request, if you neglect to put in a title, you get a blank white page with the error:

    template: repo/commits_table:13:219: executing "repo/commits_table" at <.AfterCommitID>: invalid value; expected string

Go to https://try.gogs.io/poop/blahs/compare/master...adgdsgdsg and click "Create pull request" without adding a title.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
