### ISSUE TITLE
Can not create first Wiki page

### ISSUE THREAD

**Issue by Jaydyou** [gogits/gogs#3467]
- Gogs version (or commit ref): 94392a7af3d07f79adab195acfb7c1b545f68be9
- Git version: 2.9.3
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

After creating a new project I cannot create the first wiki page. It seems that an empty wiki repo is created, but it cannot be checked out with branch master, because its empty. After manually committing data into the empty repo everything is working like a charm

```
[git-module] /home/git/gogs-repositories/jan/test001.wiki.git: git init
[git-module] stdout:
Initialized empty Git repository in /home/git/gogs-repositories/jan/test001.wiki.git/.git/

[git-module] Setting update hook: /home/git/gogs-repositories/jan/test001.wiki.git
[git-module] git clone -b master /home/git/gogs-repositories/jan/test001.wiki.git data/tmp/local-wiki/1
2016/08/15 22:19:45 ^[[1;31m[...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage: UpdateLocalWiki: Clone: exit status 128 - Cloning into 'data/tmp/local-wiki/1'...
fatal: Remote branch master not found in upstream origin
fatal: The remote end hung up unexpectedly
```

**Comment by Unknwon** [comment]
Hi, if you can't reproduce on demo site, it maybe you have old temp data. Try restart Gogs and do again.

**Comment by Jaydyou** [comment]
Unfortunately restarting does not help. `data/tmp/local-wiki` is empty since initial clone of the wiki-repo fails.

**Comment by Unknwon** [comment]
Does the real wiki repo has any content? I can't reproduce this..

**Comment by Jaydyou** [comment]
If real wiki repo is the repo in gogs-repository-folder: no its empty and executing
`$ git clone -b master /home/git/gogs-repositories/jan/test001.wiki.git`
fails as well with 
```
Cloning into 'test001.wiki'...
fatal: Remote branch master not found in upstream origin
fatal: The remote end hung up unexpectedly
```
In contrast  
`$ git clone /home/git/gogs-repositories/jan/test001.wiki.git` is working with a warning: You appear to have cloned an empty repository

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

**Comment by Jaydyou** [comment]
Thanks for your quick response and fix. Now it is working as expected.
