### ISSUE TITLE
[Feature suggestion] lock "migrate repository" button

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#3470]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Gogs have a option to migrate git repositories, but, is repo origin is big, clone gonna take a while, but don't have status for a user that is migrating repo, then it could end up clicking on the button "migrate repository" again.

Then, I think that is good option if click on "migrate repository" button, lock this button and display some status or loading indicative, then user will see that migration is running.

I tested this on https://try.gogs.io/

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/829
