### ISSUE TITLE
Problem with connecting to ORM

### ISSUE THREAD

**Issue by cierzniak** [gogits/gogs#3471]
- Gogs version (or commit ref): **Gogs version 0.9.60.0803**
- Git version: **git version 2.1.4**
- Operating system: **Linux raspberry 4.4.16-v7+** (*Raspbian Jessie*)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL (**MariaDB**)
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
````
2016/08/16 18:31:44 [I] Log Mode: File(Info)
2016/08/16 18:31:44 [I] Cache Service Enabled
2016/08/16 18:31:44 [I] Session Service Enabled
2016/08/16 18:31:44 [I] Mail Service Enabled
2016/08/16 18:31:44 [I] Register Mail Service Enabled
2016/08/16 18:31:44 [I] Notify Mail Service Enabled
2016/08/16 18:31:44 [I] Git Version: 2.1.4
2016/08/16 18:31:44 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1130: Host '10.0.0.4' is not allowed to connect to this MariaDB server
````

## Description
Hi, I've got problem with my GOGS. Everything worked fine until first Raspberry Pi restart. My `/home/git/gogs/custom/conf/app.ini`:

````
RUN_USER = git
RUN_MODE = prod
[server]
DOMAIN       = git.cierzniak.ml
HTTP_ADDR    = 127.0.0.1
HTTP_PORT    = 3000
ROOT_URL     = https://git.cierzniak.ml/
DISABLE_SSH  = false
SSH_PORT     = 22
OFFLINE_MODE = false
[database]
DB_TYPE  = mysql
HOST     = 127.0.0.1:3306
NAME     = ml_cierzniak_git
USER     = git
PASSWD   = *******
SSL_MODE = disable
PATH     = data/gogs.db
````
So I don't know where is the problem with connecting to Rapsberry Pi eth0 address 10.0.0.4.

Should I give access to *git* MySQL user to this 10.0.0.4 address?

**Comment by Unknwon** [comment]
I think this is your MySQL access control problem with IP. See http://stackoverflow.com/questions/1559955/host-xxx-xx-xxx-xxx-is-not-allowed-to-connect-to-this-mysql-server
