### ISSUE TITLE
Replacement  for Convoy by gogs

### ISSUE THREAD

**Issue by RotemEmergi** [gogits/gogs#3472]
Hi all , 

I am using docker 1.12 and docker-compose 1.8 and  rancher 1.1.2.

I tried to install  gluster-convoy and see that there is a problem with mapping .

I want to know if gogs is solution for shared storage?

If yes, how can I mount the volume? 

Best regards

**Comment by Unknwon** [comment]
Hi, I don't know and have never used Convoy, but here are the Docker volume info: https://github.com/gogits/gogs/blob/master/docker/README.md
