### ISSUE TITLE
Debian binary package - how to apply custom configuration

### ISSUE THREAD

**Issue by rkubik** [gogits/gogs#3474]
- Gogs version (or commit ref): 0.9.71-1471414190.a00c932 (Debian package)
- Git version: a00c932
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:N/A

## Description
I am trying to apply custom configuration and I've followed multiple guides but I am confused as to what I need to do after creating a `/opt/gogs/custom/conf/app.ini` file[1].

My custom `app.ini` contains:

```
[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true
```

Then I restart the service `systemctl restart gogs`. But the configuration is not sticking.

I am also referencing the official "Config and run" doc[2] but it does not describe how to do this in production (with binaries).

1. https://www.progville.com/tools/gogs-setting-self-hosted-github-clone/
2. https://gogs.io/docs/installation/configuration_and_run
...

**Comment by Unknwon** [comment]
Hi, this package is not built by us (me), so I'm not sure how exactly. Maybe helpful: https://github.com/gogits/gogs/issues/2174

**Comment by rkubik** [comment]
Was very helpful, thank you.
