### ISSUE TITLE
no sqlite as "database type" option during installation

### ISSUE THREAD

**Issue by xtavras** [gogits/gogs#3478]
- Gogs version (or commit ref): 0.9.71-1471499392.7f7216b.jessie
- Git version: 2.1.4-2.1+deb8u2
- Operating system: Debian Jessie amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist: nothing useful

## Description

after installation and going to http://MYIP:3000/install , the webui doesn't show **sqlite** as database type option, it shows only mysql or postgresql. 
sqlite3 package is installed, gogs installed via apt.
![selection_028](https://cloud.githubusercontent.com/assets/1867300/17777570/49a29bf6-6561-11e6-9a32-163280c95edb.png)

**Comment by 0xbaadf00d** [comment]
If you compile Gogs by yourself, you have to add tags to include SQLite  

```
#> go build -tags "sqlite"
```
