### ISSUE TITLE
Adding SSH key with newline yields invalid key format

### ISSUE THREAD

**Issue by Daxda** [gogits/gogs#3480]
- Gogs version (or commit ref): 0.9.83.0816
- Git version: 2.9.3
- Operating system: CentOS
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
## Description

Upon adding a new public SSH key by issuing

``` bash
cat ~/.ssh/id_rsa.pub | xclip -selection c
```

and then inserting it on the Gogs' settings tab it produces the error `Sorry, we're not able to verify your SSH key: extractTypeFromBase64Key: invalid key format:`

I guess that's because the terminating null byte is also copied by my command above.
Would it be possible to fix this _issue_ by a simple replace of the null byte?

**Comment by gramakri** [comment]
Ah, thanks for opening this. I hit exactly this in the cloudron.io app and was talking about this on gitter.

**Comment by gramakri** [comment]
This worked in 0.9.48 and stopped working from 0.9.60

**Comment by Daxda** [comment]
Okay I was wrong about the null byte, it seems to be a plain `\n`

**Comment by bkcsoft** [comment]
Remove `ssh-<crypto>` and `<user>@<host>` and it works. I'll see if I can make a patch for this

**Comment by Daxda** [comment]
It also just works if I remove the trailing newline :)

**Comment by bkcsoft** [comment]
ooh... that's even easier :laughing:

**Comment by W-quan** [comment]
Use gedit to open it and copy. It work.

**Comment by strk** [comment]
I was just struck by this issue, sounds like an easy fix indeed

**Comment by Unknwon** [comment]
Should be fixed by https://github.com/gogits/gogs/pull/3565.
