### ISSUE TITLE
Push rejected due to database lock

### ISSUE THREAD

**Issue by wolkenschieber** [gogits/gogs#3483]
- Gogs version (or commit ref): 0.9.71.0809
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
## Description

When trying to push my latest changes to the gogs hosted repository, the update was declined due to a locked database. The push command show following errors:

```
$ git push
Zähle Objekte: 367, Fertig.
Delta compression using up to 8 threads.
Komprimiere Objekte: 100% (70/70), Fertig.
Schreibe Objekte: 100% (367/367), 313.59 KiB | 0 bytes/s, Fertig.
Total 367 (delta 178), reused 347 (delta 165)
remote: error: hook declined to update refs/heads/master
Gogs: Internal error
UpdatePublicKey: database is locked
To ssh://host/user/repository.git
 ! [remote rejected] master -> master (hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'ssh://git@host/user/repository.git'
```

On server-side the update.log showed following entry

```
2016/08/19 13:28:38 [...s/gogs/cmd/update.go:54 runUpdate()] [F] AddUpdateTask: database is locked
```

After a restart of the gogs server, I could do the push.

**Comment by Unknwon** [comment]
How do you confirm you're running which version?

**Comment by wolkenschieber** [comment]
I copied the version string from the bottom of admin page.

**Comment by Unknwon** [comment]
Cool.

**Comment by wolkenschieber** [comment]
It's just happend again. I think, I was the only user at the time of error.
On client-side I did:

```
$ git status
Auf Branch master
Ihr Branch und 'origin/master' sind divergiert,
und haben jeweils 1 und 2 unterschiedliche Commits.
  (benutzen Sie "git pull", um Ihren Branch mit dem Remote-Branch zusammenzuführen)
nothing to commit, working tree clean
$ git pull --no-rebase
Gogs: Internal error
UpdatePublicKey: database is locked
automatischer Merge von internal/gittest/file
KONFLIKT (Inhalt): Merge-Konflikt in internal/gittest/file
Automatischer Merge fehlgeschlagen; beheben Sie die Konflikte und committen Sie dann das Ergebnis.
```
On server-side following items are logged in `serv.log`:

```
2016/08/23 16:03:22 [T] Trigger task: http://127.0.0.1:3000/user/repository/tasks/trigger?branch=master&secret=8db47cbde342e87f5c41d0202b2defa0
2016/08/23 16:09:10 [...ts/gogs/cmd/serve.go:290 runServ()] [F] UpdatePublicKey: database is locked
2016/08/23 16:11:06 [...ts/gogs/cmd/serve.go:290 runServ()] [F] UpdatePublicKey: database is locked
2016/08/23 16:11:06 [...ts/gogs/cmd/serve.go:175 runServ()] [F] Failed to get repository owner (org): database is locked
2016/08/23 16:11:06 [...ts/gogs/cmd/serve.go:175 runServ()] [F] Failed to get repository owner (org): database is locked
2016/08/23 16:11:11 [...ts/gogs/cmd/serve.go:290 runServ()] [F] UpdatePublicKey: database is locked
2016/08/23 16:11:16 [T] No update task is presented: 4e27e850-f506-443a-ac20-1062b30be282
2016/08/23 16:11:21 [...ts/gogs/cmd/serve.go:290 runServ()] [F] UpdatePublicKey: database is locked
```

I'm not sure how to reproduce the locked database.

Sorry for German language in client-side logs.

**Comment by wolkenschieber** [comment]
This issue some kind of show stopper. When the database gets locked no further respository actions are possible. The only remedy is to restart the gogs server. Since there's no reproducable scenario, the emergency solution is to migrate the sqlite3 database to MySQL.

With the help of the [pythom dump conversion script](https://gist.github.com/wolkenschieber/4cb84a4e2e0f4e0748abeb342a7ed5fb) an sqlite3 dump can be converted to a MySQL dump.

Since my gogs database has some `TEXT` fields where MySQL would have `VARCHAR` additional conversion is necessary. However the whole conversion can be done within one bash line:

```
$ sqlite3 gogs.db .dump | ./sqlite3-to-mysql.py -u gogs -p newdbpassword -d gogs | sed 's/UUID/TEXT/g' | sed 's/TEXT/VARCHAR(255)/g' | sed 's/`avatar` VARCHAR(255)/`avatar` VARCHAR(2048)/g' | sed 's/`content` VARCHAR(255)/`content` TEXT/g' | sed 's/`url` VARCHAR(255)/`url` TEXT/g' | sed 's/`cfg` VARCHAR(255)/`cfg` TEXT/g' | sed 's/`description` VARCHAR(255)/`description` TEXT/g' | sed 's/`note` VARCHAR(255)/`note` TEXT/g' | sed 's/`secret` VARCHAR(255)/`secret` TEXT/g' | sed 's/`events` VARCHAR(255)/`events` TEXT/g' | sed 's/`meta` VARCHAR(255)/`meta` TEXT/g' | mysql --user=root --password=rootpassword --default-character-set=utf8
```

Maybe this helps others with the same problem.

**Comment by 0xbaadf00d** [comment]
SQLite is good during development but is not suited for production or multi-threaded environment. You can read more information about lock at https://www.sqlite.org/lockingv3.html and https://www.sqlite.org/threadsafe.html

**Comment by Unknwon** [comment]
From the log, I suspect `./gogs web` is doing something long running task while you're pushing, that's the kind of case cause SQLite3 to report `database is locked`..

**Comment by wolkenschieber** [comment]
Currently the server serves nine repositories. The machine has a decent cpu and good network connection. So there shouldn't be any issue.

I also tried reproducing the database lock by a adding long running server side hook, but with no success.

**Comment by LefsFlarey** [comment]
Like what @0xbaadf00d has mentioned, SQLite is really not good for production, mainly used for miniature setups and developmental phases for it's easy of setup/installs. Can you try migrating to a proper daemonized database setup like MySQL?

**Comment by Unknwon** [comment]
Is this still an issue?

**Comment by wolkenschieber** [comment]
The server having the original problem has been migrated to MySQL. 

I only have one instance of gogs left using a SQLite database. There I haven't seen a database lock in quite some time. However it's only me using this server. So this might not be a representative example.

**Comment by Unknwon** [comment]
Thanks for the info! ... please notify here when issue happened again with latest version.

**Comment by cruwe** [comment]
Thanks for your DB-migration tool!

**Comment by wolkenschieber** [comment]
Migration between different databases and database types can be done using gogs' backup and restore function. See https://github.com/gogits/gogs/issues/2924#issuecomment-287216941 and [How to backup, restore and migrate](https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991).

**Comment by gurov81** [comment]
It seems I've got the same issue.
I'm using gogs 0.11.53.0603 with sqlite database. My build system uses yocto (https://www.yoctoproject.org/), spawning 'git ls-remote' for a set of repos in parallel at startup. So I have the following errors:
> ...
> git -c core.fsyncobjectfiles=0 ls-remote ssh://git@server/2.2:repo.git failed with exit code 128, output:
> Gogs: Internal error
> fatal: Could not read from remote repository.

Gogs serv.log has the following:
> [FATAL] [...ogs/gogs/cmd/serv.go:160 runServ()] Fail to get repository owner '2.2': database is locked

Is it possible to fix the issue?
