### ISSUE TITLE
Pull request webhook should contain information about the target branch

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#3484]
- Gogs version (or commit ref):  0.9.83.0816
- Git version: 1.8.3.1
- Operating system:  Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

I'm still playing around with the webhook information gogs provides and it seems like there is no information available what the targeted branch of the pr is. Would it be handy to include that data somewhere - does github provide this information?

**Comment by kmadel** [comment]
The GitHub pull_request webhook includes extensive info for both head and base repos: https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/pull/3547.
