### ISSUE TITLE
Pull request webhook should provide information when milestone is set/cleared

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#3485]
- Gogs version (or commit ref):  0.9.83.0816
- Git version: 1.8.3.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

The current implementation of the pull request webhook generates events for the assignee and the label changes but nothing seems to be triggered for milestones.

**Comment by Unknwon** [comment]
I don't understand the title.

**Comment by hhenkel** [comment]
Sorry - typing and talking at the sametime sometimes gives strange results....trying to clearify.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
