### ISSUE TITLE
Pull request webhook action 'label_update' does not contain label information

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#3486]
- Gogs version (or commit ref):  0.9.83.0816
- Git version: 1.8.3.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

The current webhook implementation triggers a 'label_update' action but it seems like it currently does not contain information what was set in the update. It seems that the label information (what labels are set) is available with the next triggered webhook.

**Comment by bkcsoft** [comment]
It's returning stale data (in other words, the previous state).

Claimed :)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
