### ISSUE TITLE
AppSubUrl not used to define URLs

### ISSUE THREAD

**Issue by agrn** [gogits/gogs#3490]
- Gogs version (or commit ref): 0.9.83.0816
- Git version: 2.7.3
- Operating system: Gentoo Linux, Debian GNU/Linux 8.5
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
The variable AppSubUrl (defined by ROOT_URL in app.ini) is supposed to be an URL prefix, but is not used in web.go when defining URLs.

However, the variable is used in assets and avatar URLs (so no CSS, JS, images, etc.), and in ctx.Data["Link"], causing pages to have broken links. For instance, if you try to login, the form will be sent to a non-existent page.

**Comment by Unknwon** [comment]
Because you config wrong reverse config, or not using reverse proxy at all. It is reverse proxy sub-path, not arbitrary URL sub-path.
