### ISSUE TITLE
[Feature request] add tar.gz binaries for pi2

### ISSUE THREAD

**Issue by robbix1206** [gogits/gogs#3491]
Most Rasberry pi are under Rasbian which hasn't got an unziper by default  but have the tar command.
So that's why I ask if it is possible to add tar.gz binaries format for pi2 architecture.
PS: Can you precise the version of ARM use to compile gogs ? It look like this one is not compatible with ARMv6l (Raspberry B+)

**Comment by Xe** [comment]
The `file` command will tell you everything you need to know. Ex:

```console
$  file /bin/ls
/bin/ls: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, 
  interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, 
  BuildID[sha1]=87efec13ca0b4ffa75dda873cad8a8db7ae22def, stripped
```
