### ISSUE TITLE
Gitlab to gogs automigration?

### ISSUE THREAD

**Issue by kirillDanshin** [gogits/gogs#3493]
## Feature request, not relevant.
- Gogs version (or commit ref): 0.9.71
- Git version: 2.7.4
- Operating system: Fedora 24/CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Hi! Can we create an automatic importer from gitlab with support for issues/milestones etc.?

**Comment by bkcsoft** [comment]
will probably not get into Gogs itself (if we support gitlab someone else will want github, bitbucket, teamcity, etc...), though building it as a separate tool is easy enough... using e.g. https://github.com/gogits/go-gogs-client and https://github.com/plouc/go-gitlab-client to make a simple migrator

**Comment by Unknwon** [comment]
I agree this should all be API-based, not built into the product.
