### ISSUE TITLE
SSH: Invalid env arguments for environment vars

### ISSUE THREAD

**Issue by waldiTM** [gogits/gogs#3496]
- Gogs version (or commit ref): 0.9.71.0809
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

gogs logs several warnings for every environment variable provides by the client to the internal ssh server.

    [W] SSH: Invalid env arguments: '[]string{"\aLC_TIME\nde_DE.utf8"}'
    [W] SSH: Invalid env arguments: '[]string{"", "LC_MESSAGES", "en_GB.UTF-8"}'
    [W] SSH: Invalid env arguments: '[]string{"\x0eLC_MEASUREMENT\nde_DE.utf8"}'
    [W] SSH: Invalid env arguments: '[]string{"\nLC_NUMERIC\nde_DE.utf8"}'
    [W] SSH: Invalid env arguments: '[]string{"\bLC_PAPER\nde_DE.utf8"}'

The default config of openssh enables sending this environment variables by default:

    Host *
      SendEnv LANG LC_*

**Comment by Unknwon** [comment]
Why should it not warning if the software does not understand the argument?
