### ISSUE TITLE
Security: Internal SSH server allows arbitrary environment injection

### ISSUE THREAD

**Issue by waldiTM** [gogits/gogs#3497]
- Gogs version (or commit ref): 7f7216be6e4a55af83a614fb2782d643af40825a

## Description

``modules/ssh/ssh.go`` parses environment variables provided by the ssh client. The names of the variables are not checked or sanitized in any way. The variables are then passed on to the executed tool. This allows a client to inject arbitrary environment variables into whatever is executed.

This type of vulnerability is tracked as [CWE-78 (command injection)](http://cwe.mitre.org/data/definitions/78.html).

**Comment by Unknwon** [comment]
Hi, please give real, working example.
