### ISSUE TITLE
Include HTTPS into the official Dockerfile

### ISSUE THREAD

**Issue by Moep90** [gogits/gogs#3499]
- Gogs version (or commit ref): 0.9.71.0809
- Git version:  na
- Operating system: Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
It would be nice to have everything ready for https.
Maybe as commented version.

Regards

Danny.

**Comment by Unknwon** [comment]
Hi, please send PR, otherwise I don't know what you're referring to.
