### ISSUE TITLE
 Email notifications - "gomail: could not send email 1: gomail: invalid address"

### ISSUE THREAD

**Issue by Marko-M** [gogits/gogs#3501]
- Gogs version (or commit ref): 0.9.83.0816
- Git version: 2.9.3
- Operating system: Ubuntu Trusty 64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/Marko-M/cff1fc09790d816a57b3bd84da7798ce

## Description
Somewhere along the recent upgrades our company gogs stopped sending email notifications with error as in log gist.

Email server is Postfix which sends the rest of our company email, here's relevant app.ini sections

```
[service]
ACTIVE_CODE_LIVE_MINUTES               = 180
RESET_PASSWD_CODE_LIVE_MINUTES         = 180
; User need to confirm e-mail for registration
REGISTER_EMAIL_CONFIRM                 = true
; Does not allow register and admin create account only
DISABLE_REGISTRATION                   = true
; User must sign in to view anything.
REQUIRE_SIGNIN_VIEW                    = true
; Mail notification
ENABLE_NOTIFY_MAIL                     = true
```

```
[mailer]
ENABLED         = true
; Buffer length of channel, keep it as it is if you don't know what it is.
SEND_BUFFER_LEN = 100
; Name displayed in mail title
SUBJECT         = %(APP_NAME)s
; Mail server
; Gmail: smtp.gmail.com:587
; QQ: smtp.qq.com:25
; Note, if the port ends with "465", SMTPS will be used. Using STARTTLS on port 587 is recommended per RFC 6409. If the server supports STARTTLS it will always be used.
HOST            = mail.somedomain.com:25
; Disable HELO operation when hostname are different.
DISABLE_HELO    =
; Custom hostname for HELO operation, default is from system.
HELO_HOSTNAME   =
; Do not verify the certificate of the server. Only use this for self-signed certificates
SKIP_VERIFY     =
; Use client certificate
USE_CERTIFICATE = false
CERT_FILE       = custom/mailer/cert.pem
KEY_FILE        = custom/mailer/key.pem
; Mail from address, RFC 5322. This can be just an email address, or the `"Name" <email@example.com>` format
FROM            = Gogs <gogs@somedomain.com>
; Mailer user name and password
USER            =
PASSWD          =
```
Any help is appreciated.

Additionally I'll use this opportunity to say thanks on this wonderful piece of software ;), great job!

...

**Comment by Marko-M** [comment]
An update, test email in Admin Panel -> Configuration goes through for both emails, so I guess it's something comment notification specific.

**Comment by Unknwon** [comment]
Hi, this is duplicated to https://github.com/gogits/gogs/issues/3487

**Comment by strk** [comment]
I actually think this would be fixed by #3616, can you confirm @Marko-M ?

**Comment by Marko-M** [comment]
Hi @strk, running with Ubuntu 14.04 Packer latest version at this time, issue comment emails are still not sent.

**Comment by strk** [comment]
@Marko-M r #3616 wasn't merged yet, so you would need to build it yourself to try it.
