### ISSUE TITLE
Web editor should use proper author name and email

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#3505]
- Gogs version (or commit ref): 0.9.83.0816
- Git version: 2.7.4
- Operating system: Linux Debian and Linux Fedora 
- Database
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I noticed that when using the online commit functionality it uses incorrect information inside the commit. It think it should have the same functionality as in GitLab. 

Fullname should be used for both author and committer name where the email should be used for both author email and committer email.

**Comment by de-vri-es** [comment]
Not sure if this would happen automatically, but you want the same behaviour for merge commits for accepted pull requests.

**Comment by Unknwon** [comment]
@de-vri-es it's not a good idea to report different issue in one thread, please file another issue.

**Comment by de-vri-es** [comment]
I would say that is is not a separate issue since it is another commit generated through web interface of gogs. I'd say making sure that gogs behaves consistent is important, and as such this is a relevant concern.

**Comment by Unknwon** [comment]
@de-vri-es you can reference issue, but not the same issue. 

(once you filed another issue, I'm going to remove our conversation here to keep thread focus)

**Comment by hgaiser** [comment]
I agree that this seems like the same issue. Gogs is creating a commit using the wrong author name, regardless of whether this happens through the online commit or through a merge from a pull request. In addition it seems like a minor adjustment to the way gogs commits but makes merging more logical. Now you'd have commits under the full name of an individual followed by one merge commit using its username instead of full name, this doesn't make sense to me.

**Comment by Unknwon** [comment]
The title of this thread is made things very clear this thread is only going to be able web editor.

**Comment by hgaiser** [comment]
Fine, but then accept this as a +1 that this is also bothering people when merging pull request at the least....

**Comment by de-vri-es** [comment]
Well, apologies for trying to help get consistent behaviour across gogs.

**Comment by Unknwon** [comment]
I have made statement very clear

> it's not a good idea to report different issues in one thread, please file another issue.

I'm not ignoring the issue about pull request commit, but that is not the purpose of this thread unless author of this issue change the title of issue.

I'm going to delete all previous comments.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.
