### ISSUE TITLE
Profile Picture and Avatar unscalable

### ISSUE THREAD

**Issue by peterurk** [gogits/gogs#3506]
- Gogs version (or commit ref): 0.9.83.0816
- Git version: 1.7.1
- Operating system: Scientific Linux 6.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
When uploading a custom avatar, the image is being pulled out of proportions. It can not be scaled and gives a very strange stretched result. This can result in some quite amusing results but it would be great if the image dimensions would be taken in account.
...

**Comment by Unknwon** [comment]
I think this is on purpose to make UI element not break.

**Comment by peterurk** [comment]
It most probably is. However, there is no way to slice your image and there are no specifications as to what dimensions should be used. If the dimensions dont fit, it would be a solution to fill the image with whitespace. That will make it look alot better than stretched images.

**Comment by Unknwon** [comment]
You can use as large as possible as long as the picture has similar height and width.
