### ISSUE TITLE
Pull Request in dashboard

### ISSUE THREAD

**Issue by hgaiser** [gogits/gogs#3511]
- Gogs version (or commit ref): 0.9.71
- Git version: 2.9.3
- Operating system: Arch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

Adding Pull Requests or assigning Pull Requests to people does not make them appear in the Dashboard (under Pull Requests). The Pull Requests section under Dashboard simply shows 0 active Pull Requests. Is there anyway I can debug what is going wrong here? I tried it on try.gogs.io and it seems to work there.

**Comment by Unknwon** [comment]
Hi, this is basically same to https://github.com/gogits/gogs/issues/1820, you can comment on that thread.
