### ISSUE TITLE
500/Unique Constraint error when creating LDAP with same name

### ISSUE THREAD

**Issue by avindra** [gogits/gogs#3515]
- Gogs version (or commit ref): 0.9.71.0809 
- Git version: 2.9.3
- Operating system: SLES 11 SP4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant ( I dont have admin access)
- Log gist:

## Description

Just create an LDAP source, and try to create another with the same name. You will be greeted with a 500 error, and this is the error in the backend:

> 2016/08/25 11:30:31 [...uters/admin/auths.go:155 NewAuthSourcePost()] [E] CreateSource: UNIQUE constraint failed: login_source.name

**Comment by Unknwon** [comment]
OK... why would you need same name for two different login sources?

**Comment by avindra** [comment]
I don't need it, but it would make for better UX if the name was validated up front, rather than bombing out with a 500 error upon submission. 

It's a minor issue, but I figured I'd report it anyway.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch.
