### ISSUE TITLE
Web editor changes line endings to DOS

### ISSUE THREAD

**Issue by jcgruenhage** [gogits/gogs#3516]
- Gogs version (or commit ref): 0.9.83.0816
- Git version: 2.7.4
- Operating system: Fedora 24 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL):https://try.gogs.io/jcgruenhage/bash-test
  - [ ] No
  - [ ] Not relevant

## Description
If you edit bash files with the web editor, you will not be able to run them, until your change back the line endings with dos2unix for example. In the repo I have linked above, the last version is edited online, the one before local with vim, the vim version runs perfectly, the one from the online editor does not work, as you can see below.

```
[jcgruenhage@greenbox bash-test]$ git add test.sh 
[jcgruenhage@greenbox bash-test]$ git commit
[master (root-commit) 6767298] Initial Commit
 1 file changed, 2 insertions(+)
 create mode 100644 test.sh
[jcgruenhage@greenbox bash-test]$ chmod +x test.sh 
[jcgruenhage@greenbox bash-test]$ git add test.sh 
[jcgruenhage@greenbox bash-test]$ git commit
[master eac90c5] Made it executable
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 test.sh
[jcgruenhage@greenbox bash-test]$ ./test.sh 
Does this work?
[jcgruenhage@greenbox bash-test]$ git remote add origin git@try.gogs.io:jcgruenhage/bash-test.git
[jcgruenhage@greenbox bash-test]$ git push -u origin master
[...]
[Did the web edit here]
[...]
[jcgruenhage@greenbox bash-test]$ git pull
[...]
[jcgruenhage@greenbox bash-test]$ ./test.sh 
bash: ./test.sh: /bin/bash^M: bad interpreter: No such file or directory
[jcgruenhage@greenbox bash-test]$ dos2unix test.sh 
dos2unix: converting file test.sh to Unix format...
[jcgruenhage@greenbox bash-test]$ ./test.sh 
Does this still work?

```

**Comment by Unknwon** [comment]
What does `line endings to DOS` exactly mean?

**Comment by jcgruenhage** [comment]
This: http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html
Unix uses \n, DOS uses \r\n, and files edited with the web editor appear to have \r\n file endings, no matter what the original file used.
Additional side effect that is really not nice either: this obviously changes every line, so it is harder to see the differences in text files, since gogs shows every line as deleted and every line as new also.

**Comment by jcgruenhage** [comment]
what could be done, but that would be more of unix centric solution, is to tell codemirror to generally just use Unix EOLs, as seen in their documentation:

> 
> Configuration
> 
> Both the CodeMirror function and its fromTextArea method take as second (optional) argument an object containing configuration options. Any option not supplied like this will be taken from CodeMirror.defaults, an object containing the default options. You can update this object to change the defaults on your page.
> 
> Options are not checked in any way, so setting bogus option values is bound to lead to odd errors.
> 
> These are the supported options:

[Some things not relevant here]

> lineSeparator: string|null
> Explicitly set the line separator for the editor. By default (value null), the document will be split on CRLFs as well as lone CRs and LFs, and a single LF will be used as line separator in all output (such as getValue). When a specific string is given, lines will only be split on that string, and output will, by default, use that same separator.

**Comment by silverwind** [comment]
I think a better solution would be to search for the predominant line-ending style and pass that to `editor.getValue` when retrieving the contents. Don't let yourself be fooled by the `lineSeparator` option, it is only used when CodeMirror reads a file, not when saving.

**Comment by jcgruenhage** [comment]
During reading that passage again I noticed that by default CodeMirror should use LF, if I have understood that correctly:
>By default [...] a single LF will be used as line separator in all output.

@silverwind But my answer was not wrong either, specifying LF should work too:

>When a specific string is given [...] output will, by default, use that same separator

But maybe I'm all wrong, I don't know that much about how CodeMirror works.

**Comment by silverwind** [comment]
You can try on http://codemirror.net/demo/theme.html in the console.

```js
editor.lineSeparator = "\r\n"
editor.setValue("a\r\nb\r\nc")
editor.getValue().split("\r\n")
// [ "a b c" ]
editor.getValue("\r\n").split("\r\n")
// [ "a", "b", "c" ]
```

I think that proves that 

> When a specific string is given [...] output will, by default, use that same separator

Is not working as described. Not that it really helps us here, but that looks like a CM bug. I'll report it.

**Comment by silverwind** [comment]
So here a propsed complete solution:

1) before setting the contents of Codemirror, store the result of the following function:

  ````js
  function dominantLineEnding(str) {
    var numCRLF = (str.match(/\r\n/gm) || []).length;
    var numLF = (str.match(/[^\r]\n/gm) || []).length;
    return (numCRLF > numLF) ? "\r\n" : "\n"
  }
  ````
2) When the commit is saved, call `.getValue(storedSeparator)` on the CodeMirror instance.

That way, the file will be saved with the dominant ending. Mixed files will be converted to this ending style, but I guess that's acceptable.

**Comment by silverwind** [comment]
Tweaked regex to match on a empty line 1:

```js
  function dominantLineEnding(str) {
    var numCRLF = (str.match(/\r\n/gm) || []).length;
    var numLF = (str.match(/([^\r]|^)\n/gm) || []).length;
    return (numCRLF > numLF) ? "\r\n" : "\n";
  }
```

**Comment by silverwind** [comment]
Iterated over that regex which counts LF a few times because it's rather tricky to correctly count a `\n` at position 0 with Javascript's negative lookbehind. Here's my latest version:

```js
  function dominantLineEnding(str) {
    var numCRLF = (str.match(/\r\n/gm) || []).length;
    var numLF = (str.split("").reverse().join("").match(/\n(?!(\r))/gm) || []).length;
    return (numCRLF > numLF) ? "\r\n" : "\n";
  }
```

**Comment by Unknwon** [comment]
OK, to simplify the situation, I force the line ending to be `\n` from web editor. 

Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by silverwind** [comment]
It's an improvement for projects using LF, but the unnecessary conversion of CRLF files to LF isn't right:

- [diff of adding a line to a LF file](https://try.gogs.io/silverwind/line-endings/commit/811673db34c0fc404f27a61f9a276196f7c084e3)
- [diff of a line to a CRLF file](https://try.gogs.io/silverwind/line-endings/commit/c123d19fe84dd00d322621e50ca1b4f6984ecb28)

I think this can only be solved by making CodeMirror aware which line-ending style it should output. I might have a PR for you later.

**Comment by jcgruenhage** [comment]
@silverwind We had the same problem before, with LF to CRLF before, and since LF is probably used more this is at least a good workaround until we have a good fix.

**Comment by silverwind** [comment]
Yes, I imagine LF is better than CRLF for the majority of projects.

I think the overall goal should be to support the `end_of_line` option of  `.editorconfig`, and only if it's not found, perform above detection as a fallback.

**Comment by Unknwon** [comment]
@silverwind Use `.editorconfig` is a good idea, please file another issue to keep track on that.
