### ISSUE TITLE
Error 500 while raising a pull request

### ISSUE THREAD

**Issue by gshan88** [gogits/gogs#3517]
- Gogs version (or commit ref): 0.8.10
- Git version: 2.6.6
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
We are getting 500 error while raising a pull request.

Please find the  logs,

 [...routers/repo/pull.go:632 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 128 - error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

Can u advise on the solution.
...

**Comment by gshan88** [comment]
Can you help on this.

**Comment by Unknwon** [comment]
Hi, your version is too old to debug, please upgrade.
