### ISSUE TITLE
Allow UID for git user in docker container to be specified via ENV variable

### ISSUE THREAD

**Issue by JohnOmernik** [gogits/gogs#3520]
- Operating system: Docker 
- Feature Request:
  ## Description
  It would be helpful for users who may use NFS or other shared storage for the gogs volume to have the UID of the git user specified in the add user command in build.sh.  Basically, a variable such as GIT_UID, if set would invoke the add user command with the speceific user id, if not set, then don't run the command with a UID specified. 

Thanks

**Comment by Unknwon** [comment]
cc @0rax

**Comment by 0rax** [comment]
Hi there, sorry for the delay.

The thing being that the Git user is created a the creation of the container and not at runtime does not really allow us to make that configurable on a user to user basis.

Nonetheless, this can still be possible by creating this user during container initialization (before Gogs is started). I totally understand the need for this kind of feature and will definitly try to implement that.

I will keep you informed here, but as said, there is two way to do that:
- At container build time (which requires people to build their own version of the container to run with a specific UID) using [Docker build-args](https://docs.docker.com/engine/reference/commandline/build/#/set-build-time-variables-build-arg).
- Or move the creation of the user during container initialization and using an environment variable, by adding something like this to [`docker/s6/gogs/setup`](https://github.com/gogits/gogs/blob/master/docker/s6/gogs/setup) or [`docker/start.sh`](https://github.com/gogits/gogs/blob/master/docker/start.sh):
```sh
GIT_UID=$(GIT_UID:-500) # default

adduser -H -D -g 'Gogs Git User' git -h /data/git -s /bin/bash -u ${GIT_UID} && passwd -u git
```

**Comment by davidjb** [comment]
Could this be implemented with the ability to set GID as well?

Either way, ability to set UID/GUID would help avoid conflicts of user/group between host and container.  Gogs is currently writing files as the `git` user inside the container, but it ends up as a different user outside because of the UID being reused.

An example of UID/GID setting from env variables, if it helps:
https://github.com/plexinc/pms-docker/blob/d1ea49cc79deaad395f8448a606811aafc64d402/root/etc/cont-init.d/40-plex-first-run#L37

**Comment by Unknwon** [comment]
Do need someone with expertise to propose a PR...

**Comment by robertbeal** [comment]
Made a PR, hope it's ok. It uses `usermod` and `groupmod` to change the id's of the user/group. A fairly common technique for handling this sort of issue. Means the user creation can stay in the build process, the setting of the uid/gid happens at runtime. 

Like others, I noticed the file ownership of my /var/gogs directory was 1000:1000 which mapped to my user (when I have a `gogs` system user for all things gogs).

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4776, please help test on `develop` branch or https://try.gogs.io.

**Comment by ccvca** [comment]
Just one notice: Jenkins does this by a build argument:
https://github.com/jenkinsci/docker/blob/master/Dockerfile-alpine

I do not know the pros and cons for this approach instead of environment variables, ...

**Comment by robertbeal** [comment]
Both can be done. via build argument means you have to build the container yourself (which can be a nuisance as you'll have to manage changes and updates etc...)

Using environment variable means you can use the official image and specify the ID's at runtime. The downside is that you can't run your container in `--read-only` mode as this method modifies `/etc/passwd`. 

I run my own image here: https://github.com/robertbeal/docker-gogs. The readme probably better explains the above.
