### ISSUE TITLE
Wrong git clone url for wiki

### ISSUE THREAD

**Issue by tsukanov-as** [gogits/gogs#3521]
- Gogs version (or commit ref): 0.9.85.0824
- Can you reproduce the bug at https://try.gogs.io:
  - [ x] Yes (https://try.gogs.io/tsukanov.as/test/wiki)  

## Description
Wrong git clone url for wiki.
Must be .../test.wiki.git

## Sreenshot
![wiki](https://cloud.githubusercontent.com/assets/17392154/18018630/a4f851f0-6be0-11e6-9cb4-ffe4956da871.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

**Comment by tsukanov-as** [comment]
Checked. Url is correct. Thanks!
