### ISSUE TITLE
Source Update: Fail to initialize ORM engine: migrate

### ISSUE THREAD

**Issue by MojoDwarf** [gogits/gogs#3522]
Gogs version built from source: 0.9.87.0826
Database: MariaDB 10.1.14
OS: FreeBSD 10.3-RELEASE-p5
GO version: 1.6.3_1,1

**2016/08/26 23:37:24 [I] Migration: set comment updated with created
2016/08/26 23:37:24 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: set update_unix: Error 1054: Unknown column 'updated_unix' in 'field list'**

Updating from version 0.9.83.0816 using source.

**Comment by Wonderfall** [comment]
Same here, using gogs/gogs Docker image. Very annoying. :(

**Comment by MojoDwarf** [comment]
@Wonderfall what version were you updating from?

**Comment by Unknwon** [comment]
Thanks! Should be fixed in `master` now.

**Comment by MojoDwarf** [comment]
Updated again and I can confirm this is fixed on my system. Thank You!
