### ISSUE TITLE
[Solved] Repos gone after Upgrade

### ISSUE THREAD

**Issue by Moep90** [gogits/gogs#3523]
- Gogs version (or commit ref):  0.9.87.0826
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist:

## Description
I removed my old container but my volume consists.
After recreate with newer image, I can login and everything else consists. But my Repos are gone in the webinterface.

After Logging in: 
![git-go-gitserver](https://cloud.githubusercontent.com/assets/3042152/18025647/757019a4-6c30-11e6-9134-df6e9dd148d8.JPG)

## Commands
docker stop Go-Git-Server
docker rm Go-Git-Server
docker rmi <CID>
docker run -d --name=Go-Git-Server -p 10022:22 -p 10080:3000 -v gogs-data:/data gogs/gogs

```
tree -L 3
.
└── gogs-data
    ├── git
    │   ├── git -> /data/git
    │   └── gogs-repositories
    ├── gogs
    │   ├── conf
    │   ├── data
    │   └── log
    └── ssh
        ├── ssh_host_dsa_key
        ├── ssh_host_dsa_key.pub
        ├── ssh_host_ecdsa_key
        ├── ssh_host_ecdsa_key.pub
        ├── ssh_host_ed25519_key
        ├── ssh_host_ed25519_key.pub
        ├── ssh_host_rsa_key
        └── ssh_host_rsa_key.pub

```

**Comment by Unknwon** [comment]
Does `gogs-data/git/gogs-repositories` contain repository data?

**Comment by Moep90** [comment]
Yes.

## Commands

gogs-data/git$ tree -L 3
.
├── git -> /data/git
└── gogs-repositories
    └── moep_moep
        ├── repo1.git
        ├── repo2.git
        ├── repo3.git
        └── repo4.git

**Comment by Unknwon** [comment]
I suspect you did not connected to old volumed directory at all.

**Comment by Moep90** [comment]
If so, why I didn't need to set the server up again? All files are stored in the same directory...

**Comment by Moep90** [comment]
**Solved
1st I issued: 
docker run -d --name=<Name> -p <Port> -p <Port> -v gogs-data:/data gogs/gogs 
Ive been in the dir which contains "gogs-data". So I had just my account..

2nd I issued:
docker run -d --name=<Name> -p <Port> -p <Port>-v /<absolute path>/gogs-data:/data gogs/gogs

Now it is working again. I'm pretty sure its not the repos fault.
