### ISSUE TITLE
Nested comments result in highlighting bug

### ISSUE THREAD

**Issue by GottemHams** [gogits/gogs#3524]
- Gogs version (or commit ref): 0.9.85.0824
- Can you reproduce the bug at https://try.gogs.io: Yes ([click for repo](https://try.gogs.io/GottemHams/SyntaxBug))

## Description

> When using nested comments, gogs sometimes runs into a syntax highlighting bug. Let's say I forked someone's code and find certain features don't work anymore. I comment out those parts but leave them in there for reference. This may result in __everything__ from the nested comment till the end looking like it's commented out.

> I realise it's mostly human error to have comments like this, but I personally like to prefix no longer relevant stuff within block comments with `//` so I can quickly skim over it. It's easily forgotten to add a space between a `*` and `//`. =]

> Also, some people may not realise nested comments behave like this in conjunction with gogs anyways. It works fine with vim and Sublime Text, for example.

(description is also in the repo's readme so simply quoted it here)

**Comment by Unknwon** [comment]
Thanks for the report! But I think you would have to report this to upstream: https://github.com/isagalaev/highlight.js

**Comment by bkcsoft** [comment]
@Unknwon just a thought, but wouldn't it be good to keep third-party bugs open until they are resolved upstream? since gogs is still impacted by the bug. And most people who run into this bug are only gonna check open bugs. I know it will clutter the issue-page, but it might keep duplicates down :smile:

**Comment by Unknwon** [comment]
I think it is not worth keeping open unless we can actually do something to "fix" it.

**Comment by GottemHams** [comment]
Well, they've fixed it upstream: https://github.com/isagalaev/highlight.js/issues/1283

**Comment by Unknwon** [comment]
Awesome, waiting for next release.
