### ISSUE TITLE
Startup issues ("Fail to initialize ORM engine")

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3526]
- Gogs version (or commit ref): v0.9.71
- Git version: 2.1.4
- Operating system: Debian 8 (ARM)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log:

    ```
    2016/08/27 16:17:17 [I] Log Mode: File(Info)
    2016/08/27 16:17:17 [I] Cache Service Enabled
    2016/08/27 16:17:17 [I] Session Service Enabled
    2016/08/27 16:17:17 [I] Git Version: 2.1.4
    2016/08/27 16:17:17 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 127.0.0.1:XXXX: getsockopt: connection refuse
    ```

## Description

I use [the official init.d script](https://github.com/gogits/gogs/blob/master/scripts/init/debian/gogs), but at server startup Gogs seem to fail to bind to the TCP socket.
I even changed the init header to this one requiring more services at startup:
```
#! /bin/sh
### BEGIN INIT INFO
# Provides:          gogs
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A self-hosted Git service written in Go.
# Description:       A self-hosted Git service written in Go.
### END INIT INFO
```

But this did not fixed the issue either.
I always need to manually run Gogs after the system startup.

**Comment by Unknwon** [comment]
You need start MySQL before Gogs.

**Comment by rugk** [comment]
I added `mysql` to  `Required-Start`, but it's still not working. Additionally other programs running on the same server do start correctly when executed (without "mysql" in "Required-Start").

Also I need to double-check wheter I actually have configured Gogs to use MySQL somewhere.

**Comment by rugk** [comment]
Okay, it now works...
