### ISSUE TITLE
Possibilities to change settings directly as admin in browser

### ISSUE THREAD

**Issue by GinoHereIam** [gogits/gogs#3527]
- Gogs version (0.9.83.0816): 
- Git version: 2.7
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The possibilities to change all settings as admin directly in the web browser would be nice.

Regards
Gino
...

**Comment by Unknwon** [comment]
This is duplicated to https://github.com/gogits/gogs/issues/1072
