### ISSUE TITLE
Unable to post comments using regular account

### ISSUE THREAD

**Issue by harmw** [gogits/gogs#3528]
## Description

Hi, I recently upgraded my container to gogs/gogs:0.9.71 running 0.9.71.0809 (coming from 0.8.old) and now my users are unable to comment on issues and get a 404 on /comments.

I can however comment just fine using an _admin_ account, as can be seen here:

```
[Macaron] 2016-08-28 20:02:49: Started POST /bla.nl/bla.nl/issues/1/comments for 94.214.254.254
2016/08/28 20:02:49 [D] Session ID: c61d70975f11ee05
2016/08/28 20:02:49 [D] CSRF Token: iJ7d2iv1ZE-a2HN1d2ABCF6EgIg6MTQ3MjQxMzE3NjYzMTE3NzkzOA==
[Macaron] 2016-08-28 20:02:49: Completed /bla.nl/bla.nl/issues/1/comments 302 Found in 58.303235ms
[Macaron] 2016-08-28 20:02:49: Started GET /bla.nl/bla.nl/issues/1 for 94.214.254.254
2016/08/28 20:02:49 [D] Session ID: c61d70975f11ee05
2016/08/28 20:02:49 [D] CSRF Token: iJ7d2iv1ZE-a2HN1d2ABCF6EgIg6MTQ3MjQxMzE3NjYzMTE3NzkzOA==
2016/08/28 20:02:50 [D] Template: repo/issue/view
[Macaron] 2016-08-28 20:02:50: Completed /bla.nl/bla.nl/issues/1 200 OK in 133.845428ms
```

Using a regular account, the output is logged like this:

```
[Macaron] 2016-08-28 20:04:11: Started POST /bla.nl/bla.nl/issues/1/comments for 94.214.254.254
2016/08/28 20:04:11 [D] Session ID: 3b5e65fdcad19696
2016/08/28 20:04:11 [D] CSRF Token: KwgITNfpoUHf9TE0v4wsH11mM8Y6MTQ3MjQxNDQxODI1ODU5NjUyNA==
[Macaron] 2016-08-28 20:04:11: Completed /bla.nl/bla.nl/issues/1/comments 404 Not Found in 85.373985ms
2016/08/28 20:04:11 [D] Template: status/404
```

- Gogs version (or commit ref): 0.9.71.0809
- Operating system: container pulled from https://hub.docker.com/r/gogs/gogs/tags/0.9.71
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Webbrowser used: Chrome

**Comment by Unknwon** [comment]
This is fixed issue in `master`.

**Comment by harmw** [comment]
ah great, is it known when this will be pushed to a new release and essentially hit dockerhub?

**Comment by Unknwon** [comment]
See https://hub.docker.com/r/gogs/gogs/builds/
