### ISSUE TITLE
add tag support for repository

### ISSUE THREAD

**Issue by morganwu** [gogits/gogs#3531]
when developing a project across platforms, we may need to create a separated project for each platform, and we want them to share the same project name, then things will become confusing when we browse them in Gogs. Of course we can use prefix to distinguish them instead, but I'm not sure that is the best practice,  like we have a network library for both android and ios platforms, we may not want to create an 'android_network' and 'ios_network' projects. As a simple solution, I believe a tag on project will work, show tags in project list and tag filter on the top, that will be enough. Does anyone has the same thoughts?

**Comment by tsukanov-as** [comment]
+1

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1253?

**Comment by morganwu** [comment]
Yes, same with the first part of it, applying labels and label filter to repositories. Sorry I didn't find it using keyword 'tag'.
