### ISSUE TITLE
Tag / Release archive downloads include full path on Windows

### ISSUE THREAD

**Issue by mohamme89d** [gogits/gogs#3535]
- Gogs version (or commit ref): (latest on develop and all previous)
- Git version: 2.9.3 (this issue has nothing to do with git)
- Operating system: (Windows 10)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When downloading archive for (Tag, release, branch or commit) system includes full path in the archive table, this behavior is less useful as it exposes **actual storage location** on server and introduces less usable archives for deployments and other build systems.  _(What if repos are stored on network drive ?)_

Example : 
- Server Config 
     ....
     [repository]
     ROOT 	= D:/BUILD/GOGS/Repositories
     ....

- Repository on server :
     Repository Name : TestRepo
     Files : file.1, file.2, folder_x(file.x)

- Action :
     Download archive (ZIP or TZG)

- Result (Actual)
     An archive file what looks like
     Archive : (CommitId|Tag).[extension]
```
     |__D:
          |__BUILD
               |__GOGS
                    |__Repositories
                        |__file.1
                        |__file.2
                        |__folder_x
                            |__file.x
```

Suggested fix is included in the pull request attached, behavior stays the same unless user sets a config flag to NOT include full path on archiving, please do review
- Server Config :
     ....
     [repository]
     ROOT 	= D:/BUILD/GOGS/Repositories
     ARCHIVE_FULL_PATH	= false
     ....

- Result (Expected after fix)
     An archive file what looks like
     Archive : (CommitId|Tag).[extension]
```
      |__file.1
      |__file.2
      |__folder_x
          |__file.x

```

**Comment by Unknwon** [comment]
> Yes (provide example URL)

**Comment by Unknwon** [comment]
I have realized this only happens on Windows, thanks your fixes but they are not correct.. will push soon.

**Comment by mohamme89d** [comment]
thank you, looking forward :)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch.

Do `go get -u github.com/gogits/git-module` and recompile Gogs should fix this.

**Comment by mohamme89d** [comment]
Issue verified on windows, thank you again :+1:
