### ISSUE TITLE
Issue reporter does not receive email-notifications when not watching the repository

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3539]
- Gogs version (or commit ref): v0.9.71
- Git version: v2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

When someone reports an issue and not watches the repository, this person does not receive e-mail notifications. The reporter should get notified on issue changes.

Also having an option to subscribe to an issue (and not need to watch the full repository) would be nice.

**Comment by Unknwon** [comment]
Why can't you reproduce on demo site?
