### ISSUE TITLE
webhooks is invalid

### ISSUE THREAD

**Issue by Yunlong2cn** [gogits/gogs#3542]
![image](https://cloud.githubusercontent.com/assets/1751219/18081727/266f0f4a-6ece-11e6-97cd-c087598d5249.png)

hooks.php
```
file_put_contents('x.txt', 'datass' . PHP_EOL);
$data = file_get_contents('php://input');
file_put_contents('x.txt', $data, FILE_APPEND);
```
then x.txt has no data!

**Comment by Unknwon** [comment]
Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md
