### ISSUE TITLE
Add code-coverage to Gogs

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3543]
- Gogs version (or commit ref): v0.9.71
- Git version: v2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Since there are some tests now, perhaps it is a good idea to add code-coverage. Maybe with coveralls.io.

**Comment by Unknwon** [comment]
Hi, I consider this is duplicated to https://github.com/gogits/gogs/issues/2293
