### ISSUE TITLE
Stuck with "The conflict checking is still in progress, please refresh page in few moments."

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3544]
Gogs Version: 0.9.68.0807
A PR shows the "conflict checking in progress, please refresh page in few moments" since over 24 hours.
Here's a snapshot:
![screenshot from 2016-08-30 10 36 03](https://cloud.githubusercontent.com/assets/289678/18082150/d4f2b304-6e9d-11e6-989d-612a8b2f7599.png)

See it live on https://git.osgeo.org/gogs/postgis/postgis/pulls/4

Some traces from the logs which seem to be related:

```
2016/08/28 11:06:07 [T] AddTestPullRequestTask[head_repo_id: 63, head_branch: asgeobuf5]: finding pull requests
2016/08/28 11:06:07 [T] DeliverHooks [63]: processing delivery hooks
2016/08/28 11:06:07 [T] addHeadRepoTasks[10]: composing new test task
2016/08/28 11:06:07 [T] PushToBaseRepo[4]: pushing commits to base repo 'refs/pull/4/head'
2016/08/28 11:06:07 [.../gogs/models/pull.go:562 AddTestPullRequestTask()] [E] PushToBaseRepo: headGitRepo.AddRemote: exit status 128 - fatal: remote tmp-pull-10 already exists.
```

**Comment by Unknwon** [comment]
How about restart Gogs?

**Comment by strk** [comment]
I've just restarted and reloaded the page.
The page took forever to render, enough to timeout the browser.
Waiting some time and finally reloading did show a green check, with times:
```Page: 2415ms Template: 42ms```

**Comment by strk** [comment]
It just happened again: https://git.osgeo.org/gogs/postgis/postgis/pulls/4
Seems to be related to force-pushing

**Comment by strk** [comment]
From the logs there's a `goexit` which may explain:
```
2016/09/13 11:07:12 [...ogs/models/update.go:167 PushUpdate()] [E] updateIssuesCommit: No issue number specified
2016/09/13 11:07:12 [T] DeliverHooks [repo_id: 4]
2016/09/13 11:07:12 [T] AddTestPullRequestTask [head_repo_id: 4, head_branch: svn-trunk]: finding pull requests
2016/09/13 11:07:12 [T] AddTestPullRequestTask [base_repo_id: 4, base_branch: svn-trunk]: finding pull requests
2016/09/13 11:07:12 [T] TestPullRequests[10]: processing test task
2016/09/13 11:07:12 [T] PullRequest[10].testPatch (patchPath): /home/git/gogs-repositories/postgis/postgis.git/pulls/4.patch
2016/09/13 11:07:13 [.../runtime/asm_amd64.s:2086 goexit()] [E] testPatch[10]: UpdateLocalCopy: git pull origin svn-trunk: exit status 1 - From /home/git/gogs-repositories/postgis/postgis
 * branch            svn-trunk  -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        regress/estimatedextent_expected
        regress/sfcgal/tickets_expected
Please, commit your changes or stash them before you can merge.
Aborting

2016/09/13 11:07:13 [T] TestPullRequests[8]: processing test task
2016/09/13 11:07:13 [T] PullRequest[8].testPatch (patchPath): /home/git/gogs-repositories/postgis/postgis.git/pulls/2.patch
2016/09/13 11:07:13 [.../runtime/asm_amd64.s:2086 goexit()] [E] testPatch[8]: UpdateLocalCopy: git pull origin svn-trunk: exit status 1 - From /hom
e/git/gogs-repositories/postgis/postgis
 * branch            svn-trunk  -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        regress/estimatedextent_expected
        regress/sfcgal/tickets_expected
Please, commit your changes or stash them before you can merge.
Aborting

```

**Comment by strk** [comment]
@bjornharrtell maybe you could try to reproduce the problem here:
https://try.gogs.io/strk/postgis

Could be enough to just fork postgis above and *also* force-push there in addition to force-pushing on osgeo...

**Comment by guaguasi** [comment]
I also experienced this issue. A restart still had the conflict check going for a moment before turning green. Also with a forced push.

Upstream was forked by a 3rd party, I fetched and checked out a branch on their fork to my local upstream repo, rebased their branch with my development branch and resolved the conflicts. `git status` said the branch and the remote diverged so I did a force push. The original PR was automatically updated to reflect the new commits but hung there for a while. 

The following are the relevant lines in the log; the last two. I think the first line was before I ran the push without the `--force` flag, but maybe not:

`2016/09/27 16:22:17 [...ogs/models/update.go:167 PushUpdate()] [E] updateIssuesCommit: No issue number specified`
`2016/09/27 16:22:39 [.../runtime/asm_amd64.s:2086 goexit()] [E] testPatch[2]: UpdateLocalCopy: git checkout development: exit status 1 - error: you need to resolve your current index first`

**Comment by Unknwon** [comment]
Does this still happen in the latest release?

**Comment by strk** [comment]
I think our next upgrade would be a migration to gitea so don't count
on me to be able to test. Feel free to close, and thanks for the great
gift you gave to the world !

**Comment by Unknwon** [comment]
Thanks for the response!
