### ISSUE TITLE
Disabeling the issue tracker breaks label/milestone operations on PRs

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#3548]
- Gogs version (or commit ref): 0.9.94.0829
- Git version: 1.8.3.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/hhenkel/label_milestone_test)
  - [ ] No
  - [ ] Not relevant

If one disables the issue tracker for a repository under settings the UI in the future will deliever a 404 on all actions that involve the management of labels/milestones (creating/deleting etc.). It still is possible to perform these actions through the api.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

**Comment by hhenkel** [comment]
Seems to be fixed - tested it locally and on try.gogs.io.
