### ISSUE TITLE
 0.9.71 update error

### ISSUE THREAD

**Issue by wenhongquan** [gogits/gogs#3551]
`root@ubuntu:/opt/gogs# 2016/08/31 10:47:28 [T] Custom path: /opt/gogs/custom
2016/08/31 10:47:28 [T] Log path: /opt/gogs/log
2016/08/31 10:47:28 [I] Gogs: Go Git Service 0.9.71.0809
2016/08/31 10:47:28 [I] Log Mode: File(Info)
2016/08/31 10:47:28 [I] Cache Service Enabled
2016/08/31 10:47:28 [I] Session Service Enabled
2016/08/31 10:47:28 [I] Git Version: 1.9.1
2016/08/31 10:47:28 [T] Doing: CheckRepoStats
2016/08/31 10:47:28 [I] SQLite3 Supported
2016/08/31 10:47:28 [I] Run Mode: Production
2016/08/31 10:47:28 [...gits/gogs/cmd/web.go:76 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?
`

**Comment by 0xbaadf00d** [comment]
You probably forgot to upgrade the `templates` directory or `gog` binary.

**Comment by wenhongquan** [comment]
Thank you, I have updated the `templates` directory is ok, I see the website updated understand wrong, sorry
