### ISSUE TITLE
Inputs in issues are weird

### ISSUE THREAD

**Issue by ccatlett2000** [gogits/gogs#3553]
- Gogs version (or commit ref): 0.9.25.0506 (Latest docker I think)
- Git version: N/A
- Operating system: Alpine 3.3 (Dockerized)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) https://try.gogs.io/formsweirdstuff/formsinissues/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

In issues input fields normally don't display when added to an issue. However, they do display if they have an ID.

**Comment by Unknwon** [comment]
Thanks, but what is the practice purpose of this issue?
