### ISSUE TITLE
Windows 10 | SSH | extractTypeFromBase64Key: invalid key format: <nil>

### ISSUE THREAD

**Issue by Zellcore** [gogits/gogs#3556]
- Gogs version: 0.9.71.0809 & 0.9.97.0830 (basically every version)
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (install Win10 and try to add a ssh key)
  - [ ] No
  - [ ] Not relevant

## Description
Everytime I want to add a ssh key to my account I get the following error

> Sorry, we're not able to verify your SSH key: extractTypeFromBase64Key: invalid key format: <nil>

I can add any ssh key when I login with my Ubuntu Computer. But I get this error when using my Windows 10 Computer. Even if I add the ssh key with ubuntu and then want to work on my Win10 PC I can not get a connection. It is like Windows 10 is a forbidden OS for Gogs :)

**Comment by Unknwon** [comment]
Any invisible space characters in the pasted content?

**Comment by Unknwon** [comment]
Sounds like to this: https://github.com/gogits/gogs/issues/3480

**Comment by Zellcore** [comment]
Thanks. That helped me. I was copy and pasting the key's from gedit/notepad to the browser. Unfortunaly the notepad added a newline. I thought I tested this scenario. Anyway. Maybe a trim after clicking "Add key" would fix it? 
And the second issue was simply my stupidity adding the wrong ssh-key......
Thank you and keep up the good work :)

**Comment by Unknwon** [comment]
:joy:

**Comment by hhstore** [comment]
mac osx +1.

> copy ssh-key from id_rsa.pub, but has a newline. 
> delete the newline.
> fix it.


should the manage ssh-key service  omit the `blank symbol` at the end of the ssh-key line?
