### ISSUE TITLE
Unable to view repository due to template: repo/view_file error expected string

### ISSUE THREAD

**Issue by xor-gate** [gogits/gogs#3559]
- Gogs version (or commit ref): 0.9.97.0830
- Git version:  n/a
- Operating system:  n/a
- Database (use `[x]`): n/a
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/admin1/testnewlines_in_reference)
  - [ ] No
  - [ ] Not relevant

## Description

```
template: repo/view_file:49:30: executing "repo/view_file" at <$.RawFileLink>: invalid value; expected string
```

This is repository did work on version 0.9.30.0601 (used in other issue #3206)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by xor-gate** [comment]
The patch is looking good, seems to work again! Thanks for the fix!
