### ISSUE TITLE
Inconsistent relative links in web editor preview

### ISSUE THREAD

**Issue by tsukanov-as** [gogits/gogs#3561]
- Gogs version (or commit ref): 0.9.97.0830
- Can you reproduce the bug at https://try.gogs.io:
  - [Yes (https://try.gogs.io/tsukanov.as/test/src/master/README.md)
## Description

Inconsistent relative links (web-editor preview VS markdown view)
## Tested link:

`[test link](/../test)`
## Web-editor preview

![web-editor](https://cloud.githubusercontent.com/assets/17392154/18139623/ef509a2c-6fba-11e6-9f1e-75ba696523d5.png)
## Markdown view

![markdown](https://cloud.githubusercontent.com/assets/17392154/18139667/1af04cc2-6fbb-11e6-8a02-745c8477293f.png)

...

**Comment by Unknwon** [comment]
I think it's already fixed in latest release.
