### ISSUE TITLE
Youtube video embed in readme file not working

### ISSUE THREAD

**Issue by ESTAVEX** [gogits/gogs#3564]
I came across this post: http://stackoverflow.com/questions/11804820/embed-a-you-tube-video/29862696#29862696

It works fine on github, but not on gogs. When I click on the image, it displays an image - not a youtube video, because it adds an image URL to the `img` tag AND the `href`.

Can this please be fixed?

**Comment by Unknwon** [comment]
>It works fine

What works file?

>not working

What is expected to work?

**Comment by ESTAVEX** [comment]
When you try to embed a youtube video with image in README.md file on github, for example:

`[![Alt Text](http://img.youtube.com/vi/StTqXEQ2l-Y/0.jpg)](https://www.youtube.com/watch?v=StTqXEQ2l-Y "Alt Text")`

You get the result of this:

http://prnt.sc/ccvdgj

When you click on that image, it redirects you to youtube.com and opens that video. **This works fine on github.**

When you do the exact same on gogs, and when you click on the image, it does NOT open youtube.com - it opens the image itself. Take a look at this screenshot on gogs:

http://prnt.sc/ccvfo7

I pulled out inspect element, and as you can see, it creates an anchor tag which opens the image, instead of a youtube link.

I hope this is a bit more clear now.

**Comment by Unknwon** [comment]
Thanks, sounds like duplication to https://github.com/gogits/gogs/issues/2636

**Comment by ESTAVEX** [comment]
Yeah that's it. Sorry for duplicate post. Is there a chance for this to get fixed any time?

**Comment by Unknwon** [comment]
Can't promise on that..
