### ISSUE TITLE
web commit Failed

### ISSUE THREAD

**Issue by hzkeung** [gogits/gogs#3567]
Gogs Version: 0.9.97.0901
git version 2.9.3

Failed to update/create file 'README.md' with error: CommitChanges: exit status 129 - Unknown option: -c usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path] [-p|--paginate|--no-pager] [--no-replace-objects] [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE] [--help] COMMAND [ARGS]

**Comment by Unknwon** [comment]
Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by hzkeung** [comment]
Thank you! This issues have been resolved, my plaform is centos and and gogs init scripts read /etc/init.d/functions PATH but the default PATH using system git (version giv 1.7.1), add 'export PATH=/usr/local/git/bin:$PATH' after /etc/init.d/functions can resolved it.
