### ISSUE TITLE
Issue tracker returns 404 when the repository is empty.

### ISSUE THREAD

**Issue by squarefractal** [gogits/gogs#3572]
- Gogs version (or commit ref): 0.9.98.0901 
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/squarefractal/test-repository/issues)
  - [ ] No
  - [ ] Not relevant

## Description

When a repository is empty ("empty" as in nothing has been pushed yet to a newly created repository), trying to view the issue tracker results in a 404.

**Comment by Unknwon** [comment]
Hi, this is expected behavior.
