### ISSUE TITLE
Service not responding on windows

### ISSUE THREAD

**Issue by barbuslex** [gogits/gogs#3574]
Hi,

I have tried to install gogs as a service on Windows Server 2012 R2.
Here the error message : 
![image](https://cloud.githubusercontent.com/assets/113057/18169789/0ac4040a-705c-11e6-851d-1a4a3e581b68.png)

When i type this command in cmd: C:\www\gogs\gogs.exe web

It work's perfectly... Have you an idea ?

Thanks in advance,

++

**Comment by Unknwon** [comment]
Check your log file: `log/gogs.log`, there are errors. 

Continue discussion on https://discuss.gogs.io/
