### ISSUE TITLE
Sign commits & tags

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3575]
You should consider signing git commits & releases of Gogs.

* https://github.com/micahflee/onionshare/issues/221#issuecomment-220317661
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2981?

**Comment by rugk** [comment]
No, because this issue is not about signature verification in Gogs, but a request to you, @Unknwon, to sign commits you submit here (on GitHub).

**Comment by Unknwon** [comment]
Thanks, added to my account, will sign for future commits.
