### ISSUE TITLE
Webeditor - [UI] Wrong avatar uri when creating new file

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3577]
- Gogs version (or commit ref): v0.9.97
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (because it is configured differently)
  - [ ] Not relevant
- Log gist: not relevant

## Description

I have installed Gogs in a subdirectory and set `ROOT_URL` to the new value (assume it is set to `https://example.com/mysubdir` here).

So now here is how the page for creating a new file with the web editor looks:

![filecreationavatarissue](https://cloud.githubusercontent.com/assets/11966684/18171168/397f9d0e-7061-11e6-9f33-8e74c75d46da.png)

In the console I can see that Gogs tries to load the avatars from `https://example.com/mysubdir/mysubdir/avatars/xx` instead of `https://example.com/mysubdir/avatars/xx`.
Note that the avatar in the upper right is however loaded correctly.

Gogs is running behind nginx as a reverse proxy.

**Comment by Unknwon** [comment]
Please give a screenshot of _Web Console - Network_ of this page.

**Comment by rugk** [comment]
It shows 404 errors for `https://example.com/mysubdir/mysubdir/avatars/xx`.
Everything else is loaded correctly.

**Comment by rugk** [comment]
It is wrong in the HTML code as I can see:
```html
<img class="ui image commit-avatar" src="https://example.com/mysubdir/mysubdir/avatars/xx" height="48" width="48">
```

**Comment by Unknwon** [comment]
Please give a screenshot of Web Console - Network of this page.

**Comment by rugk** [comment]
Can I also give you the har file?

**Comment by rugk** [comment]
![gogs404avatar](https://cloud.githubusercontent.com/assets/11966684/18174834/554ade8c-706f-11e6-8882-643a4737c049.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
