### ISSUE TITLE
LDAP first login fails since 0.9.97

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3578]
Upgrading from 0.9.68 to 0.9.97 left us with a blank page resulting from login attempts by new LDAP users.
Reverting to 0.9.68 allowed people to perform their first login.

The database was just not being updated, with 0.9.97, so the new user was not being created locally.
No traces of errors in the logs, and just a blank page.
This cannot be tested on try.gogs.io for obvious reasons (no LDAP there).

It's not easy to test because existing users could login just fine, so you need to either create a new LDAP user or locally delete an existing LDAP user, and try to login again.

**Comment by Unknwon** [comment]
Fixed already in `master` https://github.com/gogits/gogs/commit/7c1fbed05764ff27c0684df92961a030e2e3344b

**Comment by strk** [comment]
Will test ASAP. Meanwhile a question: should I see any error in the logs ? Because I didn't see any...

**Comment by Unknwon** [comment]
I think it is crashed, panic does not go into log file, only to terminal.

**Comment by strk** [comment]
Uhm, so maybe scripts/init/debian/gogs should not redirect stdout to
/dev/null as it does, but rather direct it to another logfile

**Comment by strk** [comment]
Fails again as of commit 491407ddf89fb4182c5401c47d2af38f0a30adca (0.9.99.0903) -- please reopen

**Comment by strk** [comment]
Tested again, works as 491407ddf89fb4182c5401c47d2af38f0a30adca -- don't bother opening

**Comment by herbat73** [comment]
works fine with OpenLDAP with the latest 0.9.99.0915 sources 
binary version is a bit outdated and it does not work properly with LDAP auth
