### ISSUE TITLE
panic messages lost on starting gogs via script/init/debian/gogs

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3580]
panic messages lost on starting gogs via script/init/debian/gogs.
The script could be tweaked to log somewhere ( ie: http://stackoverflow.com/questions/8251933/how-can-i-log-the-stdout-of-a-process-started-by-start-stop-daemon )

Alternatively, when gogs configuration requests logging to files, panic should also go there, as done by PR #3579

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1022
