### ISSUE TITLE
Migrating a local repository to the same path where its located deletes it

### ISSUE THREAD

**Issue by doppioandante** [gogits/gogs#3581]
- Gogs version (or commit ref): 0.9.95.0830
- Git version: 2.1.4
- Operating system: Linux
- Database: SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
After having wiped out my local go folder I had lost my account data on gogs.
When trying to restore the old repositories under the same username and path I got a 500 error and the .git repository was gone.

**Comment by Unknwon** [comment]
I don't understand what you're saying at all. Sounds like Ops issue, which is you deleted your database..

**Comment by doppioandante** [comment]
It has nothing to do with the fact that I had deleted gogs, because the repositories are intact.
I have edited the issue, I hope it is clearer now.

**Comment by Unknwon** [comment]
>Migrating a local repository to the same path where its located deletes it

I still don't understand..

**Comment by doppioandante** [comment]
What I added is the *How to reproduce* in the issue body, sorry for the confusion.
I think that the title is clear enough

**Comment by Unknwon** [comment]
OK, then don't put under Gogs's managed directory and migrate.

**Comment by doppioandante** [comment]
Fair enough, but as the interface permits it, I would at least expect the repo not to be blown away.

**Comment by Unknwon** [comment]
You can't expect anything to work if you try to go the hacky way..

**Comment by doppioandante** [comment]
Mmh.. although the reproductions steps seem hacky, it is a totally legit scenario, e.g. when you have an old gogs installation which got corrupted, it is reasonable to use the new installation and migrate the repositories from where they previously were.

**Comment by lstahlman** [comment]
For what it's worth, MigrateRepository actually has some missing logic that could avoid this issue: https://github.com/gogits/gogs/blob/master/models/repo.go#L616

A tmpDir is created to house a temp clone of the repo, but it's never used.  If the git repo was first cloned there (before calling os.RemoveAll(repoPath)) and then later moved, data loss would not occur.
