### ISSUE TITLE
Pagination at top of issues page

### ISSUE THREAD

**Issue by Mindiell** [gogits/gogs#3582]
Actually pagination is shown only at the bottom of the page of the issues. It should be great to have it at the top too in order to not have to scroll down just to go to another page.

**Comment by Unknwon** [comment]
Thanks your feedback, but I don't think that's useful at all.

If you know which page to go, just modify the URL.

**Comment by Mindiell** [comment]
Well, it's not very user-friendly… Sometimes you just want to list issues (even after some filtering). Is it so difficult to add ?

**Comment by Unknwon** [comment]
I don't get the purpose of jumping to next page without going through issues in the current page.

**Comment by Mindiell** [comment]
Well, if you know that an issue is on another page but you don't remember exactly which page (since it can change with closed and opened issues). Maybe a search bar for issue title ?

**Comment by Unknwon** [comment]
OK, you can file another issue called `Advanced issue search box`.
