### ISSUE TITLE
git clone https (like Drone does) results in 500 internal server error

### ISSUE THREAD

**Issue by martinhpedersen** [gogits/gogs#3583]
After upgrading to v0.9.97, Drone CI was no longer able to `git clone` over https.

Long story short, the panic was at [models/login_source.go#L543](https://github.com/gogits/gogs/blob/v0.9.97/models/login_source.go#L543), which I guess was fixed hours later by 7c1fbed05764ff27c0684df92961a030e2e3344b.

Just thought it was worth reporting that the latest release will break Drone CI integration (builds).

**Comment by Unknwon** [comment]
Thanks.. but I'm going to close this issue anyway as already fixed... 

(writing on-demand binary building system, so people don't have to wait releases for binaries)
