### ISSUE TITLE
Create label faster

### ISSUE THREAD

**Issue by Mindiell** [gogits/gogs#3584]
When you create a label, once it's done you have to reclick the "New label" button to show the form. Would it be possible that after a label creation the form is still there in order to be able to create multiple label faster ?

**Comment by Unknwon** [comment]
Thanks your feedback, but I don't think it's worthing investigating. 

I would rather recommend you use [Label Template](https://discuss.gogs.io/t/how-to-use-predefined-label-templates/599).

**Comment by Mindiell** [comment]
oh god, thx ! :o)
