### ISSUE TITLE
No preview when editing release

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3588]
- Gogs version (or commit ref): 0.9.97.0830
- Git version: 2.9.3
- Operating system: CentOS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zero-x-baadf00d/psychic-soul/releases/new)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

They are no preview tab (like Ticket creation) during Release creation or edition.

![image](https://cloud.githubusercontent.com/assets/1005086/18209934/69d04500-7136-11e6-9aca-b61a92a25c7f.png)

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2919
