### ISSUE TITLE
404 on release draft edition

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3590]
- Gogs version (or commit ref): 0.9.98.0901
- Git version: 2.9.3
- Operating system: CentOS
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zero-x-baadf00d/test/releases => https://try.gogs.io/zero-x-baadf00d/test/releases/edit/test)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
2016/09/03 07:36:39 [...ules/context/repo.go:432 func1()] [E] RepoRef invalid repo: branch or tag not exist: r/1
```

## Description

We can't edit / publish a release draft.

## How to reproduce

1. Go to releases tab
2. Click on 'New Release'
3. Choose a 'Tag name' and fill other fields
4. Click on 'Save draft'
5. On the releases tab, click 'Edit' for the newly created draft

**Comment by 0xbaadf00d** [comment]
I do a try by removing `context.RepoRef()` from `web.go`.

```
m.Group("/releases", func() {
			m.Get("/new", repo.NewRelease)
			m.Post("/new", bindIgnErr(auth.NewReleaseForm{}), repo.NewReleasePost)
			m.Get("/edit/*", repo.EditRelease)
			m.Post("/edit/*", bindIgnErr(auth.EditReleaseForm{}), repo.EditReleasePost)
			m.Post("/delete", repo.DeleteRelease)
		}, reqRepoWriter)
```

and the issue seams fixed. The _/releases/xxxxxx_  don't use repository reference and don't handle it on the different URLs  _/releases_  _/releases/<tagname>/edit_ ...  

Or maybe add a new `else if` on `context.RepoRef()` to add an exception for releases.

**Comment by Unknwon** [comment]
Let me guess... the commits count is now missing from the repository header bar?

**Comment by 0xbaadf00d** [comment]
Hmm you right. The commit count is missing :-(

I try with `context.RepoRef()` but by commenting the last line 

```
ctx.Handle(404, "RepoRef Invalid repo", fmt.Errorf("branch or tag not exist: %s", refName))
```

Page is OK, but commit count always missing.

Maybe, in fact, the issue is Gogs try to request Git repository for something (Release)  that it must be only database requested ?

**Comment by lstahlman** [comment]
The issue is with using * here: https://github.com/gogits/gogs/blob/master/cmd/web.go#L499
`			m.Get("/edit/*", repo.EditRelease)`
`			m.Post("/edit/*", bindIgnErr(auth.EditReleaseForm{}), repo.EditReleasePost)`

The * causes context.RepoRef to try loading the tag from Git, which doesn't work if the draft release is referencing a new tag.

@Unknown, any reason why this * can't be changed to the following?
`			m.Get("/edit/:tag", repo.EditRelease)`
`			m.Post("/edit/:tag", bindIgnErr(auth.EditReleaseForm{}), repo.EditReleasePost)`
...and of course updating the EditRelease and EditReleasePost methods to use the modified param.

This would make context.RepoRef load the default branch.

**Comment by 0xbaadf00d** [comment]
@lstahlman is not a issue, is the way used to handle all valid release name (eg: release-1.3.3  is valid,  release/1.3.3 is a valid tagname too)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by 0xbaadf00d** [comment]
Ok it working. Thanks

**Comment by richbl** [comment]
Is there any way to back out of that draft release (short of applying the patch)?

We're in a production environment, and I'd rather not make changes to the GOGS backend.

Thanks

**Comment by Unknwon** [comment]
@richbl Hi, what is "back out of that draft release (short of applying the patch)?"?

**Comment by richbl** [comment]
@Unknwon,
I'd like to remove/delete that draft release entirely. Is it possible?

Thanks

**Comment by Unknwon** [comment]
@richbl to hack the DB:

1. Find `repo_id`, which you can search by name on `/admin/repos`
2. Delete row from table `release` where `repo_id` and `is_draft=true`.

**Comment by richbl** [comment]
@Unknwon, thanks!
