### ISSUE TITLE
gogs.io certificate has an invalid OCSP

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3592]
Firefox 47.0 refuses to render https://gogs.io, while it is happy with https://try.gogs.io.
The problem is in the OCSP of the certificate.

sslabs.com confirms, compare these two:
https://www.ssllabs.com/ssltest/analyze.html?d=gogs.io
https://www.ssllabs.com/ssltest/analyze.html?d=try.gogs.io

For the first, the analysis reports:
```
OCSP stapling: Invalid   Failed to validate response 
```

**Comment by strk** [comment]
Firefox reports, for gogs.io:
```
An error occurred during a connection to gogs.io. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT 
```

The openssl command found in https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx says something about StartSSL being involved in the OCSP, while the certificate is issued by LetsEncrypt, maybe there lies the problem ?

**Comment by Unknwon** [comment]
gogs.io used to use StartSSL, but then changed to LetsEncrypt.

So guess it's more about caching?

Close since it's not a Gogs bug.

**Comment by strk** [comment]
I dubt ssllabs.com had a cache as it took a long time to produce the analysis I saw

**Comment by strk** [comment]
I just stumbled upon this same issue with Firefox version 45.3.0 (on a different machine, being the 3rd confirmation of he problem) -- once again, there's no problem with try.gogs.io (where would it be more appropriate to report these kind of non-code issues ?)

**Comment by hhenkel** [comment]
I see the same issue on linux with firefox 48.0.2

**Comment by Unknwon** [comment]
I have rolled back the Caddy server to 0.8.1 and fixed the problem.

cc @mholt

**Comment by mholt** [comment]
Did you at least restart Caddy before rolling back to such an old version? (I don't recommend using old versions. They have known OCSP stapling bugs :wink:)

**Comment by Unknwon** [comment]
@mholt hmm.. not tried.. but rolling back to 0.8.1 works immediately.. this old version is running fairly long time without any problem reported.

**Comment by mholt** [comment]
Okay, well, you should use the latest version anyway since it fixes a bug with renewal that was caused by an unexpected change upstream (inside Let's Encrypt's server software). If you run it with `-log` flag and specify a log file, then keep an eye on it, it would be useful to know if the problem happens again. Thanks for your patience and help!

**Comment by Unknwon** [comment]
@mholt Updated to latest (0.9.4) version, everything seems good so far! :D

**Comment by wyattoday** [comment]
This is still broken in Firefox. I'm using Firefox 49.0.1 and trying to access https://gogs.io/

It fails with "An error occurred during a connection to gogs.io. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT"

**Comment by mholt** [comment]
What's in the process log @Unknwon?

**Comment by strk** [comment]
Confirmed, it's happening again (but it did work at one point).

**Comment by patatetom** [comment]
Confirmed with Firefox 49.0.1(SEC_ERROR_OCSP_INVALID_SIGNING_CERT)
OK with Chromium 53.0.2785.116

**Comment by joubertredrat** [comment]
Same here. Firefox 49 stable, Firefox 51.0a2 Aurora, SeaMonkey and Palemoon on Ubuntu. 
`An error occurred during a connection to gogs.io. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT`.

Chorme, Chromium, Opera, Midori, Iridium, Vivaldi and Brave is normal.
