### ISSUE TITLE
Fail to initialize ORM engine

### ISSUE THREAD

**Issue by SupFrost** [gogits/gogs#3593]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.7.4
- Operating system: Ubuntu Server 16.04 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

I get the following after I upgraded from version 0.9.60 to 97.

```
2016/09/03 19:25:46 [T] Custom path: /var/opt/gogs/custom
2016/09/03 19:25:46 [T] Log path: /var/opt/gogs/log/
2016/09/03 19:25:46 [I] Redundant Games: Go Git Service 0.9.97.0901
2016/09/03 19:25:46 [I] Log Mode: File(Trace)
2016/09/03 19:25:46 [I] Cache Service Enabled
2016/09/03 19:25:46 [I] Session Service Enabled
2016/09/03 19:25:46 [I] Mail Service Enabled
2016/09/03 19:25:46 [I] Register Mail Service Enabled
2016/09/03 19:25:46 [I] Notify Mail Service Enabled
2016/09/03 19:25:46 [I] Git Version: 2.7.4
2016/09/03 19:25:46 [I] Migration: set comment updated with created
2016/09/03 19:25:46 [...s/routers/install.go:72 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: Sync2: unable to open database file
```

**Comment by Unknwon** [comment]
I think the error is very obvious, ORM can't find database file. 

> migrate: do migrate: Sync2: unable to open database file

Please report deploy issue to our forum.
