### ISSUE TITLE
Try to support atlassian pull request workflow

### ISSUE THREAD

**Issue by grotesque** [gogits/gogs#3594]
Currently anybody with write access can commit to master. Forking a repo before pull request is pretty heavy operation and out of question.

This frankly makes the gogs workflow not worthy of production. 

Solution:-

Taken from: https://github.com/gogits/gogs/issues/1597#issuecomment-180648381

a. There will be a master branch that will updated periodically.
b. There will be several dev branches. Let say we have R1 for release one dev branch.
c. Developer should create a new branch when working on a feature/bugfix against dev branch. For example, a new feature for R1 will be developed under 'feature/name_r1_featurename' (change feature to bug fix if it is bug fixing). He/she is committing and pushing the works to the organization repository.
d. Dev login the stash and create new pull request from his branch to existing dev branch and assign few peer devs to review it (ex: feature/name_r1_featurename to R1)
e. Assigned peer devs can review the changes made and acknowledge the pull request if there is no issue.
f. Team lead can merge it (since usual dev don't have capability to merge it).

**Comment by Unknwon** [comment]
I don't understand, hasn't Gogs already support PR between branches?

**Comment by grotesque** [comment]
> Gogs already support PR between branches

Yes. But to do that I need to give write access to the entire repo.

Anybody with write access to repo can :

1. push anything to master
2. destroy master using git reset --hard and git push --force. 

I don't think anyone use could gogs in production with this. Please support atlassian pull request workflow.

**Comment by bkcsoft** [comment]
So what you're really asking for is protected branches, which is in another
issue :)

**Comment by grotesque** [comment]
Hi @bkcsoft 
I just wanted to convey that it is impossible to use gogs in production without the, as you put it, "protected branches" feature.

I recently was asked to evaluate gogs(among others) for a small-medium scale app. development company that was using fossil scm and wanted a similar solution for git. I could not recommend gogs even though I liked its minimal and self contained design which is similar to fossil scm.

**Comment by Unknwon** [comment]
Thanks your comments, I consider this is a duplication of https://github.com/gogits/gogs/issues/776
