### ISSUE TITLE
Some wrong when parsing Markdown

### ISSUE THREAD

**Issue by wangwanqiang** [gogits/gogs#3596]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

there is some wrong parsing Markdown .

this works well:

```
## this is a title.
```
but this do NOT work well:

```
##this is a title.
```

when I clone a repo from github. This issue do not makes some markdown files show correctly.
...

**Comment by LFlare** [comment]
Hello,

Markdown's specification is exactly like that, for a title must be written like

    # Title
    `# Title`

and not

    #Title
    `#Title`

**Comment by Unknwon** [comment]
Hi, this is expected behavior, Gogs only support standard Markdown syntax.
