### ISSUE TITLE
https://gogs.io/ : cannot connect

### ISSUE THREAD

**Issue by auzias** [gogits/gogs#3597]
Your website seems down.
Just making this as an issue as I don't know where to contact you otherwise.

**Comment by BoringCode** [comment]
Specifically this appears to be a TLS misconfiguration.

> An error occurred during a connection to gogs.io. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT

**Comment by 0xbaadf00d** [comment]
Maybe you have to upgrade your web browser. Work very well on IE, Edge, Opera Beta, Chrome and cUrl.

No issue found with OCSP too: https://www.ssllabs.com/ssltest/analyze.html?d=gogs.io

**Comment by auzias** [comment]
Weird.
Same error on Fx [1] but it actually works on Chromium [2].

Furthermore, no [certificate error according to ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=gogs.io).

[1]: Mozilla Firefox 47.0 (on UNIX, idk which version I had on Windows)
[2]: Chromium 50.0.2661.94

**Comment by BoringCode** [comment]
Can confirm that the issue seems to be confined to Firefox. I'm using FF 48.0.2 on Windows 10. I'm having no other issues with loading TLS sites.

**Comment by auzias** [comment]
Not related with the project.

Issue closed.

**Comment by leitzler** [comment]
As for the "contact" part, you could always try https://gitter.im/gogits/gogs
