### ISSUE TITLE
gogs Update

### ISSUE THREAD

**Issue by System9Sys0mat** [gogits/gogs#3600]
Hello, i want update from 0.9.83.0816 to the newest version on ubuntu 16.06
by the command go get -u github.com/gogits/gogs i get an error 
"error: Your local changes to the following files would be overwritten by merge:
        conf/app.ini
Please, commit your changes or stash them before you can merge."
what can i do ?

**Comment by 0xbaadf00d** [comment]
You can try to stash your modifications and re-apply these after upgrade.

```
git stash
```

**Comment by System9Sys0mat** [comment]
Thanks

**Comment by bkcsoft** [comment]
Closed as resolved
