### ISSUE TITLE
Create Pull Request ends with 404 HTTP error

### ISSUE THREAD

**Issue by rbukovansky** [gogits/gogs#3603]
- Gogs version (or commit ref): 0.9.99.0903 - build from develop branch: commit 491407ddf89fb4182
- Git version: 1.8.3.1
- Operating system:  CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/TestNETTO/Test/compare/develop...rbukovansky:develop
  - [ ] No
  - [ ] Not relevant
- Log gist:

I'm trying to create PR from my feature branch to develop branch on org repo, but I'm getting 404 HTTP error. Not sure why. Org repo has master & develop branches, my repo has master, develop and given feature branch.

**Comment by Jaxmetalmax** [comment]
I confirm this issue on gogs version v0.9.97 
Git version: 2.1.4
OS: debian 8.5 64bits
DB: SQLite

creating a fork and trying to compare o create a pull request ends with a 404 HTTP on logs shows this:

[Macaron] 2016-09-06 10:20:06: Started GET /SML/IPN/compare/developer...jacquemc:developer for 189.174.143.173
Sep 06 10:20:06 spiraldev gogs[3492]: 2016/09/06 10:20:06 [D] Session ID: 37f6e9c6e6273fc5
Sep 06 10:20:06 spiraldev gogs[3492]: 2016/09/06 10:20:06 [D] CSRF Token: Ns_rlFpggOTwgX3UVoyzsVbEACM6MTQ3MzE4MjMyNTwerzUzODkwMA==
Sep 06 10:20:07 spiraldev gogs[3492]: 2016/09/06 10:20:07 [...uters/repo/commit.go:230 CompareDiff()] [E] GetCommit: exit status 128 - fatal: ambiguous argument 'jacquemc': unknown revision or path n
Sep 06 10:20:07 spiraldev gogs[3492]: Use '--' to separate paths from revisions, like this:
Sep 06 10:20:07 spiraldev gogs[3492]: 'git <command> [<revision>...] -- [<file>...]'
Sep 06 10:20:07 spiraldev gogs[3492]:
Sep 06 10:20:07 spiraldev gogs[3492]: 2016/09/06 10:20:07 [D] Template: status/404

**Comment by guaguasi** [comment]
I am having the same issue. Version is the same as @rbukovansky, 0.9.99.0903, and log is the same as @Jaxmetalmax : 

`2016/09/27 14:07:59 [...uters/repo/commit.go:230 CompareDiff()] [E] GetCommit: exit status 128 - fatal: ambiguous argument 'prodala': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

It appears that when making the PR, if I choose the his feature branch first then choose my upstream development branch, it works just fine.

A thing I noticed is that all his branches work fine when upstream master is selected but only his feature branches in the format of `feature/<feature-name>` work when upstream development is selected. His branches are `master`, `development`, `develop`, and 2 `feature/<feature-name>`. 

Please advise.

**Comment by Marahin** [comment]
Same issue here, with error as above. 

However it seems that if upstream branch is `master`, then it works just fine. Switching to any other branch makes it drop 404.

Please help, this makes collaboration highly difficult.

**Comment by Marahin** [comment]
OKay so workaround for it for me was:

https://git.3lab.re/mirkots/mirkots-engine/compare/development...marahin:development (returns 404)
https://git.3lab.re/mirkots/mirkots-engine/compare/development...Marahin:development (returns OK) 

So basicly capitalizing the first letter of USERNAME. Case insensitivity is bugged.

**Comment by liline** [comment]
I also confirm I am receiving this issue as stated above

And I confirm Marahin's solution works when I capitalize the first first character of the word after 

> OKay so workaround for it for me was:
> 
> repo-url/compare/development...marahin:development (returns 404)
> repo-urlcompare/development...Marahin:development (returns OK)
> 
> So basicly capitalizing the first letter of USERNAME. Case insensitivity is bugged.

**Comment by guaguasi** [comment]
That also worked for me, however, it didn't have to be the first letter. Capitalizing any character worked. In my case, a branch with a `/` in it also worked by default. That may have been a coincidence.

**Comment by liline** [comment]
Unfortunately when I create a pull request afterwards, I get a 505 error. Are you getting this as well?

**Comment by rbukovansky** [comment]
@Unknwon Hi, could you please take a look? Thank you.

**Comment by Marahin** [comment]
@liline yes, not always, but sometimes yes. *Even though 505 is returned, pull request is created and PERSISTS*, and works just fine. Something is terribly wrong there :)

**Comment by Marahin** [comment]
@Unknwon bump. I believe this is an issue related mainly to MySQL

**Comment by Unknwon** [comment]
I tried following steps but couldn't reproduce:

1. Create a repository under an organization
2. Fork to my own account
3. Make some push to my fork
4. Propose a PR to upstream
5. Page loads normal

Correct me if I miss something?

**Comment by rbukovansky** [comment]
@Unknwon just retested on `try.gogs.io` and the issue seems to be gone. :+1:
Keeping open until I test it on my production Gogs machine.

Thanks.

**Comment by Marahin** [comment]
@Unknwon @rbukovansky I will retest on my production machine as soon as I update it to the bleeding-edge version. Consulting with friends that use GOGS too, however, it would be wise to retest on Ubuntu 12.04 & perhaps on MySQL than on SQLite/PostgreSQL - most issues happen on that particular setup. 
Also nginx as reverse proxy.

**Comment by rbukovansky** [comment]
@Unknwon OK. I new build of Gogs it seems to be gone. Now, could we please get #3604 fixed? Thank you.
