### ISSUE TITLE
Changed branch not reflected when creating PR

### ISSUE THREAD

**Issue by rbukovansky** [gogits/gogs#3604]
- Gogs version (or commit ref): 0.9.99.0903 - build from develop branch: commit 491407ddf89fb4182
- Git version: 1.8.3.1
- Operating system:  CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/rbukovansky/Test/src/feature/yeah
  - [ ] No
  - [ ] Not relevant
- Log gist:
1. Change to branch you want to make PR from in your own repo, i.e. feature/yeah.
2. Hover over Create PR button (small green one) with your mouse and you will see that it will create PR from your_repo:develop to org_repo:develop instead of your_repo:feature_branch to org_repo:develop.
   See here:

![wrong_branch_pr](https://cloud.githubusercontent.com/assets/1004491/18254261/4ad0bc58-739c-11e6-89a8-f77d00c5fb18.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/rbukovansky/Test/src/Test.

**Comment by rbukovansky** [comment]
@Unknwon Yup, seems to be working. Thanks!
