### ISSUE TITLE
Add config option for HTML render mode

### ISSUE THREAD

**Issue by kookxiang** [gogits/gogs#3608]
As in #2593 , you add a `?render=1` which could render html file instead of raw mode.

This may lead to a security problem.
1. First, a user upload a repository, like https://try.gogs.io/kookxiang/demo
2. Then, the user can send a link to admin with the `render` param, like: https://try.gogs.io/kookxiang/demo/raw/master/index.htm?render=1
3. When other user access that page, my ssh key was insert into their setting. (check in https://try.gogs.io/user/settings/ssh , with this method, they could do anything you can do without password confirm)

Just like Github, an html cannot be render under github.com domain.
So they use a github.io domain to keep main domain secure.

Please remove this param, or at least move the option into config file.

**Comment by geek1011** [comment]
I would like this option to remain because I depend on it, but it should be off by default.

**Comment by geek1011** [comment]
Have a look at https://github.com/go-gitea/gitea/pull/685

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

This is disabled by default, see details https://github.com/gogits/gogs/commit/b3c4a39208331fd3798923bde01bf556b9e90c0d.
