### ISSUE TITLE
Login: Wrong username causes 500 error

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3612]
- Gogs version (or commit ref): v0.9.97
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (I assume it does not run behind a reverse proxy)
  - [ ] Not relevant
- Log gist: (Nothing special)
## Description

When I try to login with a non-existent username I always get a 500 error. When I however just use an existent username with a wrong password, the usual error message is shown.

Note: Gogs runs behind nginx as a reverse proxy in my configuration.

Possibly related to https://github.com/gogits/gogs/issues/3605

**Comment by bwbroersma** [comment]
I'm running Gogs 491407ddf89fb4182c5401c47d2af38f0a30adca behind Nginx 1.10.1 with a `location ^~ /gogspath/ { proxy_pass http://127.0.0.1:3000/; }` config and I cannot reproduce your problem.

**Comment by rugk** [comment]
Yeah, I have a similar setup...
However I always get this error.

**Comment by bwbroersma** [comment]
Is is a 500 error from nginx or gogs?
Can you try running gogs from the command line with `./gogs web` and see what shows in the log when you encounter this? Maybe supply your nginx gogs `location` part + `[server]` part of `custom/conf/app.ini`?

**Comment by rugk** [comment]
The error is from nginx, but it must be caused by Gogs somehow as the site requests with a valid name and an invalid password

> Can you try running gogs from the command line with ./gogs web and see what shows in the log when you encounter this? 

I did this already. The result is nothing is logged there...

> Maybe supply your nginx gogs location part + [server] part of custom/conf/app.ini?

There is nothing special:
```
[server]
ROOT_URL      = https:/mysite.example/subdir/
HTTP_ADDR     = 127.0.0.1
HTTP_PORT     = 12345
OFFLINE_MODE  = true
```

**Comment by rugk** [comment]
So now I tested it without nginx as a reverse proxy by sending request to Gogs directly and I could confirm my assumptions:
Correct user name: `HTTP/1.1 200 OK` and HTML document is returned
Wrong user name: `HTTP/1.1 500 Internal Server Error` and nothing (0 bytes) is returned

**Comment by 0xbaadf00d** [comment]
Can't reproduce this issue on Gogs 0.9.99.0903. Maybe try to upgrade to newest version.

**Comment by rugk** [comment]
I'll test it again when a new stable is released.

**Comment by beppler** [comment]
I posted on #3605 . It appears that there are some problem on user validation logic.

Using v0.9.91 and SMTP external authentication I always get error 500 both on clone or pull commands from git.

If I rollback to v0.9.71 the problem disappears.

The following log is generated.

```
[Macaron] 2016-09-09 08:27:47: Started GET /gti/fenix.git/info/refs?service=git-uplo
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:458 (0x434743)
/usr/local/go/src/runtime/panic.go:62 (0x43329d)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd
/home/vagrant/gopath/src/github.com/gogits/gogs/modules/auth/auth.go:129 (0x803531)
/home/vagrant/gopath/src/github.com/gogits/gogs/modules/context/context.go:165 (0x84
/usr/local/go/src/runtime/asm_amd64.s:481 (0x4646b6)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
```

**Comment by gronke** [comment]
fixed by [a recent commit](https://github.com/gogits/gogs/commit/7c1fbed05764ff27c0684df92961a030e2e3344b).

**Comment by BOBYou** [comment]
应该是同样问题，nginx反向代理后，无法登陆
**v0.9.97.0901**

2016/11/18 16:26:38 [T] Custom path: /data/gogs/custom
2016/11/18 16:26:38 [T] Log path: /data/gogs/log
2016/11/18 16:26:38 [I] Git Server 0.9.97.0901
2016/11/18 16:26:38 [I] Log Mode: File(Info)
2016/11/18 16:26:38 [I] Cache Service Enabled
2016/11/18 16:26:38 [I] Session Service Enabled
2016/11/18 16:26:38 [I] Mail Service Enabled
2016/11/18 16:26:38 [I] Notify Mail Service Enabled
2016/11/18 16:26:38 [I] Git Version: 1.8.3.1
2016/11/18 16:26:38 [I] SQLite3 Supported
2016/11/18 16:26:38 [I] Run Mode: Production
2016/11/18 16:26:38 [T] Doing: CheckRepoStats
2016/11/18 16:26:38 [I] Listen: http://0.0.0.0:3000
[Macaron] 2016-11-18 16:26:43: Started GET /user/login for 127.0.0.1
2016/11/18 16:26:43 [D] Session ID: 220f5622222ae932
2016/11/18 16:26:43 [D] CSRF Token: thn45jMlioVl----------------DMwNQ==
[Macaron] 2016-11-18 16:26:43: Completed /user/login 200 OK in 2.21451ms
2016/11/18 16:26:43 [D] Template: user/auth/signin
[Macaron] 2016-11-18 16:26:43: Started GET /img/favicon.png for 127.0.0.1
[Macaron] [Static] Serving /img/favicon.png
[Macaron] 2016-11-18 16:26:43: Completed /img/favicon.png 200 OK in 5.747248ms
[Macaron] 2016-11-18 16:26:50: Started POST /user/login for 127.0.0.1
2016/11/18 16:26:50 [D] Session ID: 220f5622222ae932
2016/11/18 16:26:50 [D] CSRF Token: thn45jMlioVl----------------DMwNQ==
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:458 (0x434743)
/usr/local/go/src/runtime/panic.go:62 (0x43329d)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
/home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
/usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
[Macaron] 2016-11-18 16:26:50: Completed /user/login 500 Internal Server Error in 3.070465ms

**Comment by cmsimike** [comment]
I am currently experiencing a similar problem when trying to login with ldap.

**Comment by Unknwon** [comment]
I believe this was fixed in https://github.com/gogits/gogs/commit/7c1fbed05764ff27c0684df92961a030e2e3344b which is right after 0.9.97 release.
