### ISSUE TITLE
Double html encoding of Organization Full Name

### ISSUE THREAD

**Issue by bwbroersma** [gogits/gogs#3614]
- Gogs version (or commit ref): 491407ddf89fb4182c5401c47d2af38f0a30adca
- Git version: 2.1.4
- Operating system: Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

Double html encoding of `Organization Full Name`, see https://try.gogs.io/specialchars

Using Organization Full Name: `We like 'quotes'`
Expecting: `We like &#39;quotes&#39;` in HTML
Getting: `We like &amp;#39;quotes&amp;#39;`

**Comment by saboya** [comment]
It seems correct here, maybe the issue is in your browser?
![chrome_2016-09-10_14-38-33](https://cloud.githubusercontent.com/assets/67044/18412422/53c3c280-7764-11e6-9aa9-5961ed46f208.png)

**Comment by bwbroersma** [comment]
I mean I would expect `We like 'quotes'` as display value (so a `We like &#39;quotes&#39;` HTML source) but I get `We like &#39;quotes&#39;` as display value (and `We like &amp;#39;quotes&amp;#39;` as HTML source).

**Comment by saboya** [comment]
Oh I see, I guess I misunderstood. I think you're right.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1937.
