### ISSUE TITLE
RPC failed; HTTP 500 curl 22 The requested URL returned error: 500 Internal Server Error

### ISSUE THREAD

**Issue by lanyur** [gogits/gogs#3619]
- Git version: 2.8.1 windows
- Gogs version: 0.9.97.0901
- Operating system: windows2003
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
## Description

```
$ git push
Counting objects: 2999, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (2899/2899), done.
Writing objects: 100% (2999/2999), 254.98 MiB | 13.20 MiB/s, done.
Total 2999 (delta 736), reused 0 (delta 0)
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500 Internal Server Error
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

**Comment by Unknwon** [comment]
Please try the latest release and report back.

**Comment by snaildos** [comment]
I;m getting this error too.
