### ISSUE TITLE
Advanced issue search box

### ISSUE THREAD

**Issue by Mindiell** [gogits/gogs#3620]
It should be great to have a simple textbox to filter issues on their title in the issue list. Search could be as simple as showing all issues having at least a word from the box in their title.

**Comment by sh2ka** [comment]
+1. Without this feature it's difficult to work when you have a lot of issues.

**Comment by Biromain** [comment]
+1, already 350 issues and it's already hell.

**Comment by sha-red** [comment]
Duplicate of #13

**Comment by bkcsoft** [comment]
Closed as duplicate of #13
