### ISSUE TITLE
Failed to update/create file 'README.md' with error: CommitChanges

### ISSUE THREAD

**Issue by khromov** [gogits/gogs#3625]
Received error when trying to edit README.md in a repository.

```
Failed to update/create file 'README.md' with error: CommitChanges: exit status 129 - Unknown option: -c usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path] [-p|--paginate|--no-pager] [--no-replace-objects] [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE] [--help] COMMAND [ARGS] 
```

Nothing in `gogs.log`
- Gogs version (or commit ref):  0.9.99.0903
- Git version: 1.7.1
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

**Comment by saboya** [comment]
Your git version is too old. -c parameter was introduced in Git 1.7.2.

It would be wise for Gogs to check Git version and warn users though.

**Comment by bkcsoft** [comment]
This should be documented somewhere ^.^

**Comment by khromov** [comment]
Thanks for the feedback. This is the default Git version on CentOS 6, so a fair amount of people would be affected by this issue and there is no easy solution other than adding custom RPMs. Could hiding the feature or popping up a dismissable warning be an option?

**Comment by saboya** [comment]
I believe this is the code that is giving you troble:
https://github.com/gogits/git-module/blob/b3009dc4f5842cf9e2e80fef1e125e79c38e4949/commit.go#L119

I'm not certain that it would work, but maybe the same effect could be achieved using env vars instead of the -c parameter, using `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL`, according to:
https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#Committing

Not sure how hard this refactor would be since I didn't look at the rest of the code, but if this works it should work for more Git version, including 1.7.1, and seems simple enough.

**Comment by saboya** [comment]
Ok, I took a shot at enabling this for Git 1.7.1, opened a pull request for the git-module:
https://github.com/gogits/git-module/pull/19

From my tests, it's working fine, and the fix seems proper/simple enough.

**Comment by hjoukl** [comment]
FWIW this issue also affects the wiki functionality. E.g. when trying to add a 1st wiki page (gogs 0.9.97.0901):

```
2016/10/12 09:09:47 [...routers/repo/wiki.go:216 NewWikiPost()] [E] AddWikiPage: CommitChanges: exit status 129 - Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
```

Current installation requirements on https://gogs.io/docs/installation state a git dependency of >= git 1.7.1.
git 1.7.1 is also the default version on Red Hat 6.5.

**Comment by Unknwon** [comment]
This is fixed in recent releases.
