### ISSUE TITLE
Fail to initialize ORM engine: migrate: do migrate: set update_unix: Error 1054: Unknown column 'updated_unix' in 'field list'

### ISSUE THREAD

**Issue by Morpheu5** [gogits/gogs#3629]
Hi, I'm not sure for how long this has been going on since I haven't been using my own repos for a while. I run gogs in a docker container, and I mindlessly upgraded all my containers a while ago, so it could be less than 10 days.

Anyway, this is the log that gogs keeps spitting out:

```
2016/09/09 09:53:18 [T] Custom path: /data/gogs
2016/09/09 09:53:18 [T] Log path: /app/gogs/log
2016/09/09 09:53:18 [I] Morpheu5.net Git Vault 0.9.99.0903
2016/09/09 09:53:18 [I] Build Time: 2016-09-09 01:01:58 UTC
2016/09/09 09:53:18 [I] Build Git Hash:
2016/09/09 09:53:19 [I] Log Mode: File(Info)
2016/09/09 09:53:19 [I] Cache Service Enabled
2016/09/09 09:53:19 [I] Session Service Enabled
2016/09/09 09:53:19 [I] Mail Service Enabled
2016/09/09 09:53:19 [I] Migration: set comment updated with created
2016/09/09 09:53:19 [...s/routers/install.go:69 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: set update_unix: Error 1054: Unknown column 'updated_unix' in 'field list'
```

It seems it's failing to migrate the db because the migration contains a column that isn't in the actual db.

I'm confused.

**Comment by Morpheu5** [comment]
I checked the `comment` table and in fact there is no `update_unix` column in its schema.

**Comment by Morpheu5** [comment]
So, I manually created that column, but then a host of new issues popped up, including duplicate FKs and the likes. I probably can't do all the updates manually on my own. Suggestions?

**Comment by Morpheu5** [comment]
Eventually I had to re-install the whole thing (and I switched to SQLite while I was at it, for memory issues with InnoDB tables…). Not a great experience, but hey.

**Comment by Unknwon** [comment]
I think you migrated from too old version that no longer supported by migration.
