### ISSUE TITLE
ROOT_URL documentation is wrong

### ISSUE THREAD

**Issue by mvrhov** [gogits/gogs#3630]
The issue will be closed without any reasons if it does not satisfy any of following requirements:
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.9.3
- Operating system: Xenial
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

The wiki says that ROOT_URL should contain the domain name and also the installer recommends to put the FQDN into that field. However when you write the https://git.example.com into the ROOT_URL, and start up the gogs, the log says `Listen: https://localhost:3000/git.example.com`.  Accessing the site on https://git.example.com redirects you on https://git.example.com/git.example.com

Of course this then doesn't work as expected as at least all styles are missing and the browser url is clearly wrong.

**Comment by Unknwon** [comment]
Thanks for the feedback! But I'm very sure the wiki is correct, and you might have wrong config on your proxy.

**Comment by mvrhov** [comment]
This is the location part in nginx config.

```
        location / {
                proxy_set_header X-Real-IP  $remote_addr;
                #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_set_header        Host $http_host;
                proxy_read_timeout      120;
                proxy_http_version      1.1;

                proxy_pass http://localhost:3000/;
        }
```
The gogs doesn't seem to use use neither of the commented headers.

The server section is as following:
```
[server]
DOMAIN       = git.example.com
HTTP_ADDR    = localhost
HTTP_PORT    = 3000
ROOT_URL     = https://%(HTTP_ADDR)s:%(HTTP_PORT)s/
DISABLE_SSH  = false
SSH_PORT     = 22
OFFLINE_MODE = false
```

**Comment by Unknwon** [comment]
I don't believe you can access your site on the web via `https://localhost:3000`, so it is wrong for whatever reason. But if you're using it good, just keep it.

**Comment by mvrhov** [comment]
Well this still means that the docs ARE wrong.
The other problem with my solution is that the http repository url shown in the GUI is pointing at the `https://localhost:3000` and not to `https://git.example.com`

So basically there are 2 issues.

**Comment by Unknwon** [comment]
>The other problem with my solution is that the http repository url shown in the GUI is pointing at the https://localhost:3000

Because you tell the config to do so.

**Comment by Unknwon** [comment]
The NGINX config you post is not complete, post everything for Gogs.

**Comment by mvrhov** [comment]
This is "everything".  The remaining part is ssl and gzip configuration. At least the FAQ says this is all it's needed.

**Comment by Unknwon** [comment]
Maybe this is helpful: https://unknwon.io/setup-gogs-with-https/

**Comment by mvrhov** [comment]
Well your example is saying to use `proxy_pass http://localhost:3000$request_uri;`, this results in a bad gateway error code at least on nginx 1.10

**Comment by Unknwon** [comment]
Then it's your server config problem to make proxy working.
