### ISSUE TITLE
Add new separate repositories for issues and pullrequests

### ISSUE THREAD

**Issue by randomdudette** [gogits/gogs#3632]
- Gogs version (or commit ref):    try.gogs.io
- Git version:    try.gogs.io
- Operating system:    try.gogs.io
- Database (use `[x]`):   try.gogs.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes   https://try.gogs.io/wakawaka/repo
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

Currently Gogs has to 2 repositories for each repo:
1. one for the source code, for example https://try.gogs.io/[user]/[repo].git
2. one for wikis, for example https://try.gogs.io/[user]/[repo].wiki.git

Could you please add another for issues and for pull requests? For example
- https://try.gogs.io/[user]/[repo].issues.git
- https://try.gogs.io/[user]/[repo].pr.git

This would be **extremely useful** because users can backup all their data (code/issues/wikis/prs). And even more useful, if I want to move from one server to another server, I could just `git clone` and `git push` all my repos _easily_ (which at the moment is not possible).

Thank you!

**Comment by Unknwon** [comment]
Issues and pull request are stored in database, I recommend use API to do the backup..
