### ISSUE TITLE
Toolbar notifications for issues, PRs

### ISSUE THREAD

**Issue by randomdudette** [gogits/gogs#3634]
- Gogs version (or commit ref): try.gogs.io
- Git version:  try.gogs.io
- Operating system:  try.gogs.io
- Database (use `[x]`): try.gogs.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/  (dashboard, user logged in)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

This is the Gogs toolbar

![issue](https://cloud.githubusercontent.com/assets/22113076/18409211/95149bf2-7731-11e6-91ee-5342d0b7c111.png)

Would it be possible to add a notification label next to _Issues_ and _Pull requests_? For example if there is something new that I haven't looked yet, you could display **Issues (3)** or **Pull Requests (1)**, or **New comments (5)**. Would be very useful to see new issues and new comments!

**Comment by Unknwon** [comment]
Thanks for the feedback!

I think implements https://github.com/gogits/gogs/issues/2109 would solve the problem more generally.
