### ISSUE TITLE
user/forget_password confirmation/error messages should be changed

### ISSUE THREAD

**Issue by ng-0** [gogits/gogs#3639]
You should change the error output the page "user/forget_password" gives when the email address is not known. Currently it is "This email address is not associated with any account." while it should just print a positive confirmation like mailman does[0] something like "if this email account exists (etc etc)", likewise the positive result "A new confirmation email has been sent to name@host.tld, please check your inbox within the next 3 hours to complete the registration process." should be something similar.

At the moment I don't know enough about gogs to fix it myself, I'm just packaging it.

[0]: "If you are a list member, your password has been emailed to you."

**Comment by bkcsoft** [comment]
IMO it should be ambigous whether the email is associated or not. Meaning it should *always* say "Email sent", otherwise it can be used to get a list of registered users...

**Comment by LefsFlarey** [comment]
# May I request that I'm currently on this issue? :)

**Comment by LefsFlarey** [comment]
and done!~

**Comment by ng-0** [comment]
Thanks, @LefsFlarey !

**Comment by Unknwon** [comment]
Closed by #3654
