### ISSUE TITLE
Migration Clone Release information not copied

### ISSUE THREAD

**Issue by DblK** [gogits/gogs#3640]
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) : https://try.gogs.io/dblk/MigrationReleaseProblem/releases
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

After I set-up a new migration for the repo Gogs as following:
![image](https://cloud.githubusercontent.com/assets/832617/18427506/e3b0cef0-78c8-11e6-865a-84854de91809.png)

I got a clone but the release part only display some of the attached files and no information text.
Here is what I got from github:
![image](https://cloud.githubusercontent.com/assets/832617/18427573/5edcd4de-78c9-11e6-82fe-5cc7131f3db4.png)

And here from try.gogs.io:
![image](https://cloud.githubusercontent.com/assets/832617/18427585/7336c80e-78c9-11e6-8f56-eb8c0a8ccd21.png)

**Comment by Unknwon** [comment]
Please refer to [this comment](https://github.com/gogits/gogs/issues/4004#issuecomment-275879027).
