### ISSUE TITLE
Fail of editing files after renaming of a repository (web editor)

### ISSUE THREAD

**Issue by iu0v1** [gogits/gogs#3641]
- Gogs version (or commit ref): v0.9.97
- Operating system: linux
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/lord/test-rename)
## Description

Hello. After renaming of a repository it is impossible to edit files through the web editor.

Steps to reproduce:
1. Create repo `test`
2. Add README
3. Rename repo `test` -> `test-rename`
4. Edit README & commit

Error message:
 `Failed to update/create file 'README.md' with error: UpdateLocalCopyBranch [branch: master]: git pull origin master: exit status 1 - fatal: '/home/git/gogs-repositories/lord/test.git' does not appear to be a git repository fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.`

**Comment by saboya** [comment]
Not MySQL specific, I tested with SQLite and got the same error.

Restarting the app makes the problem go away. This is most likely a cache issue.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
