### ISSUE TITLE
Invalid data in .editorconfig will result in 500 error page

### ISSUE THREAD

**Issue by jvandertil** [gogits/gogs#3643]
- Gogs version (or commit ref): 0.9.99.0903 (gogs/gogs docker)
- Git version: ??? (gogs/gogs docker)
- Operating system: Ubuntu 16.04 host (gogs/gogs docker)
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes: https://try.gogs.io/bugmenot12/editorconfig-test
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
[Macaron] 2016-09-13 08:41:45: Started GET /jvandertil/Lunar for ########
2016/09/13 08:41:45 [D] Session ID: 9d14413.......
2016/09/13 08:41:45 [D] CSRF Token: XmRgOBjxjPfbeQpuPZvN0eZvAzU......
2016/09/13 08:41:45 [...routers/repo/view.go:250 Home()] [E] Repo.GetEditorconfig: key-value delimiter not found: 0Zoeken

2016/09/13 08:41:45 [D] Template: status/500
```
## Description

Having invalid content in the .editorconfig file will result in a error 500 page. In the above example I had the text '0Zoeken' as the last line in the editorconfig file (don't know how it got there). This results in the 500 error page being displayed.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3758, please help test on `develop` branch or https://try.gogs.io.
