### ISSUE TITLE
Make release .tar.gz files contain a directory

### ISSUE THREAD

**Issue by snheath** [gogits/gogs#3644]
- Operating system: Linux
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes: https://try.gogs.io/guest/my-new-test/archive/0.1.tar.gz
  - [ ] No
  - [ ] Not relevant
## Description

To conform with usual conventions, release .tar.gz files should contain a toplevel directory with the same name as the tarfile.  ie, `foo-0.1.tar.gz` should untar into a directory called `foo-0.1` which contains the contents of the repo.  There's various software that expects this which gets confused otherwise -- in my case, I want to use rpmbuild to build packages with source from a gogs repo.  Some software (rpmbuild again) also gets confused if the link URL says the file is "0.1.tar.gz" but the file is actually called "foo-0.1.tar.gz".

Neither of these seem like a huge change, I will try to find time to contribute a patch for this if you want.  (Too busy to do it just now I'm afraid.)

**Comment by Unknwon** [comment]
I think it's already implemented.
