### ISSUE TITLE
Possibility to set external issue tracker link in repo settings

### ISSUE THREAD

**Issue by Corben78** [gogits/gogs#3645]
I want to migrate several git repos to gogs, but some of them have already a [trac](http://trac.edgewall.org/) issue tracker attached, and I haven't found a solution to migrate the trac tickets to gogs yet. As it is possible to specify an external tracker, I'm linking to those trac systems. Which works great with git commit messages referring to tickets.
But when I specify an external tracker system, the Issue link disappears between `code` and `pull requests`.
It would be great to be able to set an external link to the tracker, so this link remains, as it does with the wiki link, when an external wiki is set.

Referring to my question in the the [discussion forums](https://discuss.gogs.io/t/keep-issue-link-when-external-tracker-is-set/645).

**Comment by DblK** [comment]
I think I will take this one.

**Comment by DblK** [comment]
And it's done, just waiting for the merge ;)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3646, please help test on `develop` branch or https://try.gogs.io.

**Comment by Corben78** [comment]
Works as expected. Issue Tracker link remains and opens the configured URL.
Tried on https://try.gogs.io.
(so, should I close this issue?)

**Comment by Unknwon** [comment]
Thanks for confirmation!
