### ISSUE TITLE
@mention link is not parsed correctly

### ISSUE THREAD

**Issue by xor-gate** [gogits/gogs#3649]
- Gogs version (or commit ref):  0.9.99.0903
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: https://try.gogs.io/admin1/mention_rendering/issues/1

## Description

Mentioning with `@` is not parsed correctly. On github you can have a line ending dot or place it between parentheses. Which is not correctly parsed in gogs. The one with the dot at the end will link to a non-existing profile. This is how it works on github:

* Works: @xor-gate 
* Broken (dot after mention is not stripped). @xor-gate.
* Broken (between parentheses). (@xor-gate).

**Comment by DblK** [comment]
Seems to be a regexp problem.
Will look at it.

**Comment by DblK** [comment]
General remarks: The mention in markdown are done by regexep only without checking if a user exists or not; that is the implementation @Unknwon wanted (at least for now).

Test 1: Okay, working
Test 2: The dot character is an accepted character for the name so it's working as expected. ==> Nothing to fix
Test 3: The parenthesis has been an issue; I have just made a PR for this issue (#3655).

**Comment by Unknwon** [comment]
Fixed by #3655.
