### ISSUE TITLE
Push webhook - Payload no longer compatible with Drone CI.

### ISSUE THREAD

**Issue by martinhpedersen** [gogits/gogs#3653]
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
## Description

Hi,

I've recently noticed that our latest builds in Drone is missing author information. After some investigation I discovered that the webhook payloads sent from Gogs changed after upgrading from Gogs v0.9.71 (I believe).

Drone is expecting to find the author information in `sender->login`, but the login attribute have been renamed to `username`. _See [github.com/drone/drone/gogs/helper.go](https://github.com/drone/drone/blob/f52feeceb172372f047a4d7afdf39a1eec6313dc/remote/gogs/helper.go#L73) and [github.com/drone/drone/gogs/types.go](https://github.com/drone/drone/blob/f52feeceb172372f047a4d7afdf39a1eec6313dc/remote/gogs/types.go#L35)._

Was this change intentional? I am unsure of the goal of Gogs webhook format, but github's format is `sender->login`, not `sender->username`. _See https://developer.github.com/webhooks/._

If this change was intentional I can open a new Drone issue so they can fix this incompatibility.

**Comment by bkcsoft** [comment]
Here's the offending commit: https://github.com/gogits/go-gogs-client/commit/e363d3ff8f70d0fe813324eedf228684af41c29c
as you can see, the old struct had
```go
UserName  string `json:"login"`
```
while the new one has:
```go
UserName string `json:"username"`
```

And yes, Gogs goal is to be compatible with GitHub API, so it should be changed back

**Comment by Unknwon** [comment]
cc @bradrydzewski

**Comment by bkcsoft** [comment]
@Unknwon what I meant was that Gogs API has changed, and is no longer compatible with GitHub, i.e. the structure should (IMO) be changed back to 
```
UserName string `json:"login"`
```

**Comment by martinhpedersen** [comment]
If this was an unintentional change that broke Github API compatibility (a project goal), I believe this issue at least should get some new labels to reflect this.

If the webhook API change was intentional and is permanent, then please let me know so I can open an issue for github.com/drone/drone.

**Comment by martinhpedersen** [comment]
Oh wait - now I get the relationship.
