### ISSUE TITLE
[Feature] Adding +1 on issue

### ISSUE THREAD

**Issue by DblK** [gogits/gogs#3656]
**Short Explanation**: Allow users to vote for issues in repo. 

**How to use it:**
Each user will have a defined number of vote (default: 10) to dispatch in various issues.
He/She can vote up to +3 (so +1, +2 or +3) on a issue.
Once the issue is closed, he/she take back the point and dispatch to other issue.
Before the issue is closed, he/she can take back the points to attribute to another issue.

**I suggest the following implementation for +1 on issue:**
- [ ] Add a new settings in repo to setup the number of vote (default 10)
- [ ] In the issue list, display the number of "+1" left to the number of comments (yellow area bellow).
  ![image](https://cloud.githubusercontent.com/assets/832617/18541325/c62b773c-7b24-11e6-8282-4c0f7b9a4cc8.png)
- [ ] When viewing as issue, add the the right the sum of the vote
- [ ] Add a button (maybe mix with the previous one) to assign and take back vote points (+1/+2/+3) to/from this issue
- [ ] Add a way to filter issues based on the number of vote

Will it do the trick?

**Comment by LefsFlarey** [comment]
I reckon this feature can be implemented through the addition of another table in the database.

## issue_votes table
user_id | issue_id | votes
---|---|---
 1 | 1 | 3
1 | 2 | 2
1 | 3 | 5

Additionally some database `JOIN`s can be done to check total points available, something like

    SELECT `t1`.`user_id` AS `user_id`, 10 - SUM(`t1`.`votes`) AS `available_votes`
    FROM `issue_votes` `t1`
        INNER JOIN `issues` `t2` ON `t1`.`issue_id` = `t2`.`id`
    WHERE `user_id` = '%user_id';

**Disclaimer:** None of the above code works, just some brainstorming session.

**Comment by AlexDaniel** [comment]
Nah, too complicated. What's wrong with simple :+1: :-1: buttons?

**Comment by LefsFlarey** [comment]
@AlexDaniel It is **not** complicated at all. As far as I can see it, this sort of feature would prevent +1 spam and only allow users to vote on the most important issues.

**Comment by DblK** [comment]
@AlexDaniel, it's on the [trello board for 0.11.0](https://trello.com/c/p1OdMM63/405-1-issues).
Beside #3650, which is only for comments inside an issue, this one is an abilities to know the community priority about a small number of issues.
If we allow unlimited 👍 or 👎, this feature will be less useful than with a quota.

However, I can add a "-1" value to set this as unlimited even if I think it shouldn't be used.

**Comment by AlexDaniel** [comment]
> prevent +1 spam

More like encourage multiple accounts.

**Comment by LefsFlarey** [comment]
@AlexDaniel I don't think anyone is as hardworking as you are, to create multiple accounts to `+1` yourself or anyone else on issues. In any case, it ***is a planned feature***.

**Comment by Unknwon** [comment]
I think https://github.com/gogits/gogs/issues/3650 is better than just "+1" in terms of design.
