### ISSUE TITLE
API, Webhooks and Integrations

### ISSUE THREAD

**Issue by nuss-justin** [gogits/gogs#366]
I'd like to discuss some stuff about APIs, Webhooks and Integrations.

I thought about integrations proposed/mentioned in other issues and came to the conclusion that (in my opinion) there should be some focus on an API, Webhooks and Integrations.
This would make working on such features much easier, as (with a good API and Webhooks) this features can be developed without affecting the develoment of Gogs itself. 
Right now for many things proposed here today we would need to change some functions.

Until here I think there even could be plans (or some kind of tracking bug here on Github or on Trello).
But let's talk more about integrations now.

When integrating for example a CI tool the developer needs a way to show the build status for a pull request.
This means that we need (special) write access to the repository. For this we need a way for this kind of integrations to authenticate.
The best solution would probably be an option to generate special access tokens for URLs/Services in the project settings.

Here comes what I'm really interested in (everything I wrote before is nothing new):

A good idea for a tool like Gogs is to ship with some integrations for other tools/services (say drone).
Now one could create an external tool that integrates drone in Gogs through communicating with Gogs/drone over their APIs(/Webhooks).

The thing about this is, that every integration shipping with Gogs would be it's one server this way.
My question is: Should everything be an external tool or should some integrations be build in?
Having an integration built in would allow easy enabling/disabling of it in the project settings and would allow us to update the integrations with Gogs.

On the other side updates for the integrations would then mean a new version of Gogs (because it would ship as one part/binary) and also it would require a way to
invoke the API as functions (without ugly (fake) HTTP requests) and receiving the webhooks.

I thought about all this and would love to here your answer/opinions.
Do you have the same (or an similar) opinion or do you think I'm crazy? (Which I probably wouldn't even deny ;-))

(OMG, so much text)

**Comment by hickscorp** [comment]
+1 for API and it's documentation companion. I have tried to write a Strider plugin for Gogs, it's very hard in the current state of the Gogs project.
Also, having a way to get a CI indicator for every commit in the Gogs UI would be awesome.

See:
https://github.com/gogits/gogs/issues/813
https://github.com/gogits/gogs/issues/793

**Comment by Unknwon** [comment]
@hickscorp I personally really like #793 , but #813 may need more effort to work on.

**Comment by hickscorp** [comment]
@Unknwon Whenever (If) you decide that it's worth working on #813, please tell me. I will be very happy to help. I myself code in Go, but i obviously am not as advanced as you guys are, and i wouldn't dare submitting any Go code to this repository. However, if you prepare the tasks for me to work on, i will be more than able to do so.

**Comment by Unknwon** [comment]
@hickscorp sure thing!

**Comment by Unknwon** [comment]
Close discussion for now.
