### ISSUE TITLE
Citrix NetScaler SSH check log error

### ISSUE THREAD

**Issue by zijam** [gogits/gogs#3660]
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 2.6.6
- Operating system: Docker gogs/gogs
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: https://gist.github.com/zijam/12157126740d3a5ee4754c19621e27be
## Description

We are using Citrix NetScaler to do SSL offloading and it is checking if the SSH is running on the Gogs server, but we gets lots of logs with "TLS handshake error" and "Did not receive identification string from"

Do you have any recommendation to make gogs not to log these messages?

**Comment by Unknwon** [comment]
Thanks for the feedback, but the those log message does not come from Gogs. It's other processes inside Docker....
