### ISSUE TITLE
"?" handling in folder names

### ISSUE THREAD

**Issue by tuudik** [gogits/gogs#3666]
- Gogs Version: 0.9.99.0903 
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
## Description

Having "?" in folder names, will cause error 404.
For example:
- "Are we there?" will direct to: https://mygit.eu/user/repo/src/master/Are%20we%20there?
  - This will not work, it will cause error 404
- When changing "?" in URL to "%3F": https://mygit.eu/user/repo/src/master/Are%20we%20there%3F
  - This works perfectly

**Comment by LefsFlarey** [comment]
That is unfortunate but `?` symbols are almost universal for stating GET variables. In this case, perhaps a small fix can be made to url_encode it first?

**Comment by LefsFlarey** [comment]
I can try to work on this but I need to know where this error occurs.

**Comment by 0xbaadf00d** [comment]
Using "?" for a file or directory name is not common and some file systems can't handle special char (like NTFS on Windows by instance)

**Comment by tuudik** [comment]
I think it doesnt matter if it's common to use somekind of symbols or not imho. Currently the issue is that URL encoding is not done properly.

**Comment by 0xbaadf00d** [comment]
Just tested on Github.  Github replace ? with %3F on URL. I can push/clone on Linux, but not on windows.

@LefsFlarey You can probably just replace special char (eg: ? = , ; &) by the URL encode value.  Slash must stay as "/" to avoid weird URL.

**Comment by LefsFlarey** [comment]
Okay, I am now doing some testing for fixing this issue.

**Comment by LefsFlarey** [comment]
I'm done :)
Let me know if I missed anything but it should work in every sense.

**Comment by Unknwon** [comment]
Should have been fixed by https://github.com/gogits/gogs/pull/3668.
