### ISSUE TITLE
Can't save Release draft as draft

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3669]
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 2.10
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zero-x-baadf00d/test/releases/edit/draft)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

We can't save a Release draft modification as draft.
## How to reproduce
1. Go to release tab
2. Create a new draft and click on "Save Draft"
3. On release tab, click on "Edit" button for the newly created draft
4. The button "Save Draft" is now show

**Comment by dotwoo** [comment]
遇到一个相同的问题.
日志上显示:

2016/12/20 10:35:54 [...ules/context/repo.go:432 func1()] [E] RepoRef invalid repo: branch or tag not exist: Beta
2016/12/20 10:35:58 [...ules/context/repo.go:432 func1()] [E] RepoRef invalid repo: branch or tag not exist: Beta

**Comment by Unknwon** [comment]
>The button "Save Draft" is now show

I don't understand what does this supposed to mean?

**Comment by 0xbaadf00d** [comment]
now show -> not show.

**Comment by Unknwon** [comment]
Thanks for clarifying!

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
