### ISSUE TITLE
I want create a static website on gogs.

### ISSUE THREAD

**Issue by kirigayakazushin** [gogits/gogs#3670]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist:

## Description
how to create static page website on gogs?
...

**Comment by 0xbaadf00d** [comment]
Currently, you can't. But you could use Caddy server with Git extension (https://caddyserver.com/docs/git).

**Comment by kirigayakazushin** [comment]
thx

**Comment by LefsFlarey** [comment]
I like how he was too lazy to delete the above lines.
