### ISSUE TITLE
Panic when trying to delete team with -1 repositories

### ISSUE THREAD

**Issue by jhasse** [gogits/gogs#3671]
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/jhasse/7b9822405c314bf9664eea85a149ceb6
## Description

Somehow I've ended up with an invalid team. It has only one member, but `-1` repositories. When I'm trying to delete the team it results in an internal server error.

**Comment by Unknwon** [comment]
Does this still happen in latest release?

**Comment by jhasse** [comment]
Yes, still happens with 0.9.128.0130.

**Comment by Unknwon** [comment]
@jhasse does restart fixes the `-1` issue? This might be a bug in old Gogs version but doesn't possible to make this situation anymore.

**Comment by jhasse** [comment]
Restarting Gogs? While updating, it was restarted multiple times.

**Comment by Unknwon** [comment]
Indeed... I think you would need to connect to your database and find `team` table, looking for the row with `num_repos=-1` and make it `0`.

**Comment by jhasse** [comment]
Wouldn't it be possible to include a check in Gogs for `num_repos < 0`?

**Comment by Unknwon** [comment]
Yes, it is possible, if you don't mind wait for the fix..

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by jhasse** [comment]
It worked! The team showed up with 0 repositories and I could remove it without a problem.

Thank you very much :)
