### ISSUE TITLE
webhook with https

### ISSUE THREAD

**Issue by vanloswang** [gogits/gogs#3672]
Deploy a gogs server by container which is fabric8/gogs:v0.9.97. and then create a repo and create a webhook for it. The webhook url is https://192.168.4.212:8443/oapi/v1/namespaces/mdbuild/buildconfigs/mdbuild/webhooks/123456/github, then click test push on gogs, the reponse show me as following:
```bash
Delivery: Post https://192.168.4.212:8443/oapi/v1/namespaces/mdbuild/buildconfigs/mdbuild/webhooks/123456/github: x509: certificate signed by unknown authority
```
I run a curl cmd as following to debug it, when I did not set the option '--insecure', it show me the result like gogs. But after set the option '--insecure', it show me the right result.
```bash
# curl --insecure -i -H "Accept: application/json" -X POST -d "" https://192.168.4.212:8443/oapi/v1/namespaces/mdbuild/buildconfigs/mdbuild/webhooks/123456/github
HTTP/1.1 500 Internal Server Error
Cache-Control: no-store
Content-Type: application/json
Date: Mon, 19 Sep 2016 17:37:10 GMT
Content-Length: 393

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Internal error occurred: hook failed: unsupported Content-Type application/x-www-form-urlencoded",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "hook failed: unsupported Content-Type application/x-www-form-urlencoded"
      }
    ]
  },
  "code": 500
``` 

So how could I set insecure options on gogs or how to resolve it? 
Besides on GitLab, there is a choice of SSL verification. Does gogs provide this feature?
a refenrece is https://github.com/openshift/origin/issues/10986.

**Comment by vanloswang** [comment]
Another refenrece is https://github.com/openshift/origin/issues/11002. Now I can setup GitLab webhook without SSL verification now, and it work well together with Origin. I do not find out a feature to disable SSL verification like GitLab on Gogs yet.

**Comment by LefsFlarey** [comment]
The 2nd code example you provided of using curl to test, appears to return an error caused by how you used the `-d ""` incorrectly.

Currently, there is not a precedent for allowing insecure certificates or self-signed ones, generally to prevent downgrade and/or SSL attacks. What you can try to do, is register for a domain (_costs like $10/yr_) and use LetsEncrypt to register a **free** SSL certificate with them.
