### ISSUE TITLE
Wiki entries containing question sign "?" cannot be edited/deleted

### ISSUE THREAD

**Issue by gsantner** [gogits/gogs#3674]
- Gogs version (or commit ref): 
- Git version:  0.9.99.0903
- Operating system: Deb 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes - Cannot register account - error 500
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

Wiki entries containing question sign "?" in title cannot be edited or deleted.
Seems to be an problem in encoding the question sign char:

The edit button tries to make an get request to https://SERVER/gogs/account/repo/wiki/How-do-I-disable-X-at-boot-time-so-that-the-system-boots-in-text-mode?/_edit  
-> URL with parameter "/_edit" 
-> Question sign MUST be encoded. `%3F`

**Comment by LefsFlarey** [comment]
I've pushed an issue #3668 awhile ago that fixed repo files with filenames having symbols but I did not realise that wiki pages suffer from the same issue too. Try the PR out, it should solve your issue.

**Comment by gsantner** [comment]
Thanks for adding this to your PR!

I'm quite unsure myself if files really should be created with such an character, because e.g. NTFS doesn't allow it on the filesystem. Usually I won't create files with such characters, but whilr creating an entry in Wiki I didn't thought about the underlying architecture

**Comment by LefsFlarey** [comment]
@gsantner, it is important to note however, that NTFS by itself is fundamentally flawed in it's acceptable characters space. The only question that needs to be asked is, _do we limit the usable symbols/characters to that of NTFS or do we try to work around the limit of NTFS and allow end-users to use standard filenames?_

**Comment by gsantner** [comment]
Thats nothing I can or would decide. It's not affecting me, but I thought to note it.

**Comment by LefsFlarey** [comment]
Definitely, since Golang by itself is a cross-platform language, we should take into account cross-platform limitations like filenames.

**Comment by gsantner** [comment]
We can forbid to create **new** files with "?" in the repo window, and in the wiki. But we still must be able to handle them in gogs (edit, delete,..). 
Users still can commit/push files containing "?" when they are on a non-ntfs file system.

**Comment by Unknwon** [comment]
Does this still happen in latest release?

**Comment by gsantner** [comment]
@Unknwon On try.gogs.io it seems fixed
