### ISSUE TITLE
500 error when userid doesn't exist

### ISSUE THREAD

**Issue by kpande** [gogits/gogs#3675]
On latest version when browsing to a page of issues that has one created by a user who no longer exists:

```
2016/09/20 00:43:17 [D] CSRF Token: ndGTQptT4O0uhq8vu8PXMh5w_Jk6MTQ3NDMzMTkyOTM4OTMxMDUyMQ==
2016/09/20 00:43:17 [...outers/repo/issue.go:183 Issues()] [E] Issues: LoadAttributes [66]: user does not exist [uid: 1, name: ]
```

**Comment by LefsFlarey** [comment]
Could you follow issue formatting? We cannot tell if this affects everyone or just you alone.

**Comment by LefsFlarey** [comment]
I have submitted a PR that will fix this issue, I believe, PR #3676

**Comment by 0xbaadf00d** [comment]
I think it could be interresting to link issues to another user (like YouTrack) during the user deletion process rather than just fallback to -1  (not sure postgres allow this with foreign key) or null when user not found on DB when issues are listed/show.

**Comment by LefsFlarey** [comment]
@0xbaadf00d X-Post.
