### ISSUE TITLE
Add organisation member as collaborator

### ISSUE THREAD

**Issue by theredcat** [gogits/gogs#3680]
Hi!

I want to know why we can't add an organisation member as a collaborator on a repo that is not on his organisation.

E.g. :

  - `User X` is in `Org X`
  - `Repo Y` is in `Org Y`
  - I can't add `User X` as collaborator to `Repo Y`

My use case : 

I have : 
  - A `<brandname>` organisation that contain 
    - all my developers users 
    - applications repositories
  - An `infrastructure` organisation that contain
    - my sysadmin users
    - 2 repos : 
      - `Saltstack formulas` : server deployment code
      - `Saltstack pillars` : parameters for the deployment code

Pillars contains sensitive data and I don't want developers to be able to access it, So  I can't add them to `infrastructure` organisation, I just want them to be able to access with read-only permissions the  repo `Saltstack formulas`

**Comment by bkcsoft** [comment]
All Repos under an Organization have to be managed by Teams.  
You create a Team in `infrastructure`-organization, give it Read-only access. Add all devs to that Team, and give that Team access to `Saltstack formulas`. Done :smiley:

**Comment by theredcat** [comment]
I didn't clicked on the repo list :)

I've found the setting now
