### ISSUE TITLE
Different users with same e-mail causes error on create repositores and user creation from register

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#3681]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.5 LTS x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/user/activate?code=2016092109210001800019682194a3e5a3bfe65a90bcd11eb7a010eea972656472617432) 
  - [ ] No
  - [ ] Not relevant
- Log gist: https://gist.github.com/joubertredrat/7792a5e54410795c8cca270f96a4efe2
## Description

I identified 2 issues about different users with same e-mail, one on my environment and other on demo.

On mine Gogs instance I have my one user provided by SMTP authentication with e-mail `my@email`. Today I created one local user with same e-mail `my@email`. After this, both users can't create repositories, as is in gist above. Other users can create repositories without problems.

For see if I can reproduce same problem, I go to test on Gogs demo, I created user [`redrat1`](https://try.gogs.io/redrat1) without problems. Then, I created user [`redrat2`](https://try.gogs.io/redrat2) with same email from [`redrat1`](https://try.gogs.io/redrat1). I received email to activate account, but If I try to enable user [`redrat2`](https://try.gogs.io/redrat2), causes error 500.

**Comment by philippdieter** [comment]
I would like to mention, that this happens too, if you create an user and let a second user login via ldap which has the same email address.

gogs.log:
`[...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: updateUser: e-mail has been used [email: my@email.de]`

**Comment by Unknwon** [comment]
I think the solution is edit user's email by admin, as the protocol is no two users can use same email..
