### ISSUE TITLE
Fail to send notification e-mail, to non-existent address

### ISSUE THREAD

**Issue by jeppech** [gogits/gogs#3686]
Gogs v0.9.98.0901

Hi. Gomail fails to send e-mails, to an address that does not exists. This happend, when gogs was about to notify watches of a repository.

```
gomail: could not send email 1: Rcpt: 550 5.1.1 <no@nonononono.com>: Recipient address rejected: User unknown in virtual mailbox table
```

**Comment by Unknwon** [comment]
I don't think its go-mail problem because it seems to me that the mail service provider rejected...
