### ISSUE TITLE
wrong dependency version in glide.lock   and .gopmfile

### ISSUE THREAD

**Issue by edacval** [gogits/gogs#3690]
- Gogs version (or commit ref): 
  master HEAD
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Not relevant

gopkg.in/macaron.v1 locked at  7564489a79f3f96b7ac8034652b35eeebb468eb4 , but  no such ref exist. Compared go-macaron/macaron local copy refs against github history, looks all commits after 9eb6aa1af19e4076afc0763adeb65aab610a8c6e was replaced ( git push -f  or something worse ? )

**Comment by LefsFlarey** [comment]
You can try `go get -u all` for now

**Comment by saboya** [comment]
This fixes it:

```diff
diff --git a/glide.lock b/glide.lock
@@ -146,7 +146,7 @@ imports:
 - name: gopkg.in/ldap.v2
   version: d0a5ced67b4dc310b9158d63a2c6f9c5ec13f105
 - name: gopkg.in/macaron.v1
-  version: 7564489a79f3f96b7ac8034652b35eeebb468eb4
+  version: 4974334b10dbb6f5c0e17f4c10555ff050a16329
 - name: gopkg.in/redis.v2
   version: e6179049628164864e6e84e973cfb56335748dea
 devImports: []
```

**Comment by LefsFlarey** [comment]
Want to open a PR for that? :)

**Comment by saboya** [comment]
I would, but I bumped into other problems when trying to compile after that change, related to #3685. Apparently there are other places that need the interface change. Even though I feel confident that fixes the issue correctly, I'm hesitant to offer a PR that does not compile, even if if it's not related to the issue at hand.

**Comment by squash** [comment]
This is still broken.

**Comment by saboya** [comment]
Is there anyone with commit power besides @Unknwon that can review some critical PRs?

**Comment by ben-burlingham** [comment]
I'm sure you're all painfully aware, but Gogs can't be installed at the moment (afaik).  

Following any official install guide, for example https://gogs.io/docs/installation/install_from_source#build-from-develop-branch, the command `go get -u ./...`  results in

> cd /home/deploy/go/src/gopkg.in/macaron.v1; git pull --ff-only
> fatal: Not possible to fast-forward, aborting.
> package gopkg.in/macaron.v1: exit status 128

...which then blocks `go build` from running with something like

> ../../../gopkg.in/macaron.v1/context.go:36:2: cannot find package "github.com/go-macaron/inject"

Replacing the hash as suggested above does not seem to resolve it; and neither does using the latest macaron hash (https://github.com/go-macaron/macaron/commit/826ddf13862c544525338a2deda6f57ffd1a9083). 

I've been using Gogs for a while now and it's been working great, thank you all for your work! Hopefully this critical issue can be resolved soon.

**Comment by eljojo** [comment]
This is so frustrating to the point I stopped trying to help.
@ben-burlingham I feel you, I was in the same situation you are.

You can tell that master is also broken: https://hub.docker.com/r/gogs/gogs/builds/
And yes, the suggested solution didn't do the job for me either.

My advise to you, and what I ended up doing, is using the published docker image: https://hub.docker.com/r/gogs/gogs/

**Comment by ben-burlingham** [comment]
@eljojo confirming yes, the Docker image does provide a fresh install instance as you reported. It will need some configuration updates to work with my current (broken) installation.  

Thank you for your response and good luck to all!

**Comment by LefsFlarey** [comment]
@ben-burlingham @eljojo @saboya @squash @edacval 
The maintainer of Gogs, @Unknwon, has been off-and-on checking in. As of now, he is probably in the 'off' state, resulting in the sea of unmerged/uncommitted PRs. If you want, you can check out go-gitea/gitea, where a bunch ol' 'velopers have forked out Gogs source and continued development on it.

**Comment by eljojo** [comment]
Hi, the issue is still not solved. Check the docker build here: https://hub.docker.com/r/gogs/gogs/builds/bc3zhswzlnf8i348pwffcuk/

**Comment by Unknwon** [comment]
@eljojo thanks, new builds are running, should be good after few mintues.

**Comment by ben-burlingham** [comment]
New build does indeed work. Back on track - thank you @Unknwon!
