### ISSUE TITLE
ssh -T return message

### ISSUE THREAD

**Issue by ZhangTingkuo** [gogits/gogs#3691]
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.

希望可以手动设置这个信息

**Comment by bkcsoft** [comment]
That is the intended behaviour of git-shells. the `git`-user is only for `git clone/pull/push` not shell access.

**Comment by Unknwon** [comment]
This information is very critical to tell people what is expect. Being able to change it makes a lot confusion, so I don't think it's a good idea.
