### ISSUE TITLE
Split Diff View does not work when creating Pull Request

### ISSUE THREAD

**Issue by duckbrain** [gogits/gogs#3695]
- Gogs version (or commit ref): 0.9.97.0901, 0.9.99.0903
- Git version: 2.10.0, 1.7.1
- Operating system: Arch Linux, CentOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes: https://try.gogs.io/duckbrain/pull-request-example/compare/master...pull-request?style=split
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

It seems that `?style=split` is ignored when creating a pull request. Once the pull request is created, I can view the split view.

Note: you may need to fork the repository to create the pull request on https://try.gogs.io

![screenshot](https://cloud.githubusercontent.com/assets/587790/18801427/792628be-8197-11e6-8352-74aa505ec8a8.png)

Related #2790
...

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by duckbrain** [comment]
Looks fixed to me. Thank you very much!
