### ISSUE TITLE
gogs web no files shown in repository

### ISSUE THREAD

**Issue by iowahc** [gogits/gogs#3697]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.7.2.windows.1
- Operating system: Windows
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
## Description

Step 1: create git repository with gogs web interface
Step 2: add git repository as remote to local repository with SSH
Step 3: push changes to remote origin

Result: After finished upload (over 500MB of files) no Browse is shown, only the description how to clone the repository.

Expectation: After finished upload, the Browse option should be possible and the files visible within the web interface

**Comment by bkcsoft** [comment]
Why can't you reproduce on https://try.gogs.io ?

I can not reproduce this on my gogs-instance running 0.9.97.0901

**Comment by LefsFlarey** [comment]
Is there a reason why you have code over 500MB in size?

**Comment by krendil** [comment]
I'm having the same issue.  Additionally, ssh updates don't show up in the activity feed, and the repository shows it contents as normal after pushing via HTTP, so it matches the symptoms of #2662 and #1864.

- Gogs version: 0.9.97.0901
- Git version: 2.10.1.windows.1
- Operating System: Windows Vista (don't ask)
- Database: sqlite
- Log file and app.ini: https://gist.github.com/krendil/d4349f44b63bcaa2d8efca8d252ba375

**Comment by gragib** [comment]
In MySQL, check if the `is_bare` column in the `repository` table is `0` or `1`. If it is `1`, change it to `0` and reload the web page.

**Comment by Unknwon** [comment]
I think you did not config SSH setup for Gogs correctly, see https://discuss.gogs.io/t/how-to-config-ssh-settings/34.
