### ISSUE TITLE
中国地区使用docker方式安装后时间混乱

### ISSUE THREAD

**Issue by ShookGao** [gogits/gogs#3698]
应该是时区影响造成的，在个人首页看到是几分钟前提交的代码，但是在仓库页面看到的提交时间却是8小时以前。可否在docker里面引出一个时区参数，docker run 的时候使用参数来设置时区？
我使用的版本是gogs 0.9.99.0903，数据库使用的是sqlite3。

**Comment by rugk** [comment]
You have not read the **bold** text...

**Comment by bkcsoft** [comment]
Closed as duplicate #1500. Also please speak English or the issue will be closed by default (see the issue template).
