### ISSUE TITLE
Cannot go to page 2 if more than 15 repos

### ISSUE THREAD

**Issue by J-Siu** [gogits/gogs#3700]
- Gogs version (or commit ref): https://dl.gogs.io/gogs_v0.9.97_linux_amd64.tar.gz, also tested with source install 0.9.99.0915
- Git version: 2.9.3
- Operating system: Ubuntu 14.04.5 LTS (GNU/Linux 2.6.32-042stab116.2 x86_64) 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No - try.gogs.io only allow 10 repos
  - [ ] Not relevant
- Log gist:
## Description
1. Create over 15 repos
2. In 'dashboard', under 'my repositories', click 'show more repositories'
3. Click 'Next' or '2' at the bottom of page, it will remain in page 1

**Comment by LefsFlarey** [comment]
I'm entirely unable to reproduce this bug.

**Comment by J-Siu** [comment]
@LefsFlarey You need over 15 repos to reproduce this.

![screen shot 2016-10-01 at 14 51 17](https://cloud.githubusercontent.com/assets/3171920/19016452/2451b270-87e8-11e6-9a98-6e500e4a58bc.png)

![screen shot 2016-10-01 at 14 52 10](https://cloud.githubusercontent.com/assets/3171920/19016450/18a79732-87e8-11e6-86d8-2955a959ded6.png)

**Comment by J-Siu** [comment]
I changed log level to trace:

Click to dashboard:
```
2016/10/01 21:34:27 [D] Session ID: 11ad1ea4cd3d0dcc
2016/10/01 21:34:27 [D] CSRF Token: X66o5Y3VnCUgW90N98KFpK0m4mw6MTQ3NTM0OTI2NjU4MDEwNjIxOA==
2016/10/01 21:34:27 [D] Template: user/dashboard/dashboard
```

Click Show more repositories:
```
2016/10/01 21:34:43 [D] Session ID: 11ad1ea4cd3d0dcc
2016/10/01 21:34:43 [D] CSRF Token: X66o5Y3VnCUgW90N98KFpK0m4mw6MTQ3NTM0OTI2NjU4MDEwNjIxOA==
2016/10/01 21:34:43 [D] Template: user/profile
```

Click Next:
```
2016/10/01 21:34:49 [D] Session ID: 11ad1ea4cd3d0dcc
2016/10/01 21:34:49 [D] CSRF Token: X66o5Y3VnCUgW90N98KFpK0m4mw6MTQ3NTM0OTI2NjU4MDEwNjIxOA==
2016/10/01 21:34:49 [D] Template: user/profile
```

**Comment by J-Siu** [comment]
Following is log with 0.9.99.0915 running ./gogs web
```
2016/10/01 22:02:22 [D] Session ID: 9abdab7fc1392faa
2016/10/01 22:02:22 [D] CSRF Token: pK6vDCfpyGUl-FtvHbyo_-zsRaE6MTQ3NTM3MzczNzY0Njk0MDQ0MQ==
2016/10/01 22:02:22 [D] Template: user/auth/signin
[Macaron] 2016-10-01 22:02:22: Completed /user/login?redirect_to= 200 OK in 35.936298ms
[Macaron] 2016-10-01 22:02:29: Started POST /user/login for 127.0.0.1
2016/10/01 22:02:29 [D] Session ID: 9abdab7fc1392faa
2016/10/01 22:02:29 [D] CSRF Token: pK6vDCfpyGUl-FtvHbyo_-zsRaE6MTQ3NTM3MzczNzY0Njk0MDQ0MQ==
[Macaron] 2016-10-01 22:02:30: Completed /user/login 302 Found in 318.656337ms
[Macaron] 2016-10-01 22:02:30: Started GET / for 127.0.0.1
2016/10/01 22:02:30 [D] Session ID: 9abdab7fc1392faa
2016/10/01 22:02:30 [D] CSRF Token: NK0Luad9w8IohLhb22RInO_6sa06MTQ3NTM3Mzc1MDIxMDk3OTExMg==
2016/10/01 22:02:30 [D] Template: user/dashboard/dashboard
[Macaron] 2016-10-01 22:02:30: Completed / 200 OK in 271.76912ms
[Macaron] 2016-10-01 22:02:35: Started GET /js for 127.0.0.1
[Macaron] 2016-10-01 22:02:35: Completed /js 302 Found in 124.99µs
[Macaron] 2016-10-01 22:02:35: Started GET /js/ for 127.0.0.1
2016/10/01 22:02:35 [D] Session ID: 9abdab7fc1392faa
2016/10/01 22:02:35 [D] CSRF Token: NK0Luad9w8IohLhb22RInO_6sa06MTQ3NTM3Mzc1MDIxMDk3OTExMg==
2016/10/01 22:02:35 [D] Template: user/profile
[Macaron] 2016-10-01 22:02:35: Completed /js/ 200 OK in 22.795076ms
[Macaron] 2016-10-01 22:02:38: Started GET /js?page=2&q= for 127.0.0.1
[Macaron] 2016-10-01 22:02:38: Completed /js?page=2&q= 302 Found in 130.78µs
[Macaron] 2016-10-01 22:02:38: Started GET /js/ for 127.0.0.1
2016/10/01 22:02:38 [D] Session ID: 9abdab7fc1392faa
2016/10/01 22:02:38 [D] CSRF Token: NK0Luad9w8IohLhb22RInO_6sa06MTQ3NTM3Mzc1MDIxMDk3OTExMg==
2016/10/01 22:02:38 [D] Template: user/profile
[Macaron] 2016-10-01 22:02:38: Completed /js/ 200 OK in 6.177859ms
```

**Comment by J-Siu** [comment]
@LefsFlarey I think I found the issue. It only happen if username is "js".

**Comment by LefsFlarey** [comment]
That is now ultra strange.

**Comment by J-Siu** [comment]
I tried with both binary install (0.9.97) and compile from source (0.9.99) and encounter the same. I believe username "js" is conflicting with `public/js`.

**Comment by LefsFlarey** [comment]
Yeah, I have to cook up an emergency patch since this could be a vulnerability.

**Comment by J-Siu** [comment]
One possible fix I can think of is to add a virtual path like "user" in the url before <username>, so username will not conflict/hijack any gogs system path.

**Comment by LefsFlarey** [comment]
Tossed a fix, try it.

In reply to that possible fix, it no longer follows Github convention and thus such, we cannot do that :)

**Comment by J-Siu** [comment]
Do I have to change username? I am actually using "js" right now.

**Comment by LefsFlarey** [comment]
Another way would be to host assets on a CDN or mirror but I can't make that decision, so, @Unknwon

**Comment by bkcsoft** [comment]
@LefsFlare or just namespace them to `public/` where they belong :trollface:

**Comment by LefsFlarey** [comment]
We definitely could do that but we have to live with the guilt that some guy named `public` wouldn't be able to register.

**Comment by J-Siu** [comment]
Not sure if I am doing it right when I test @LefsFlarey issue/3700 branch. But seems admin user is not being check against reserve keywords.

**Comment by LefsFlarey** [comment]
In setup page?

**Comment by J-Siu** [comment]
Yes

**Comment by LefsFlarey** [comment]
Hmm, interesting.

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/pull/3728.
