### ISSUE TITLE
online editor create a  new branch and PR

### ISSUE THREAD

**Issue by wxd237** [gogits/gogs#3701]
- Gogs version (or commit ref):  0.9.99.0903
- Git version: 1.7.1
- Operating system: RedHat7.1 
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

in my company,many developer is not good at git.so, I try to found a easy way to Code review.
I found the online edit can create a new branch and a pull request.but I found the PR is not successed;

...

**Comment by LefsFlarey** [comment]
Sorry, I'm completely unable to reproduce this bug as well, can you provide logs?

**Comment by rguichard** [comment]
Hello,

I have same behaviour. When I try to commit into a new branch and start a PR, the new branch is the only thing that's actually happen. No new PR.

Gogs : 0.9.99.0915
Docker image : 
gogs/gogs:develop             sha256:eb19bf731ae437174a9886bb62f84efec43b9a787b508183f817d8e412378dbe

**Comment by Unknwon** [comment]
You checked the `Yes` for demo site, and no example URL? ....
