### ISSUE TITLE
Issue and commit progression

### ISSUE THREAD

**Issue by Corben78** [gogits/gogs#3703]
## Description

For better readability and traceability, a cross reference to other issues, commits and how labels are used in the Issue history would help.

So, when somebody adds a label to an issue, this should be shown in the Issue progression (like github does), e.g.:
`Corben78 added the feature label on 26 September 2016` or
`Corben78 added the bug feature labels on 26 September 2016`
Same for assignments, milestones etc. when added later.

Also, when an Issue references a commit by typing the hash in the Issue text, when viewing the commit it would be great to have a backwards link under the commit message, e.g.:
Issue text: `This issue is solved in commit d09fca3ca9f40be6b4c291028418d5c95428db17`
Under commit message from that commit: `Corben78 references Issue #3703`

Additional, when referencing an Issue #1 in another Issue #2, a backwards link to Issue #2 from Issue #1 would be nice. Maybe all optically done like with added Labels between Issue messages.
`Corben78 references Issue #1`

So you are able to jump back and forth from every point, and get all related items linked together.

**Comment by LefsFlarey** [comment]
Definitely an interesting idea but somewhat tricky to implement... @bkcsoft

**Comment by bkcsoft** [comment]
Nah not really, this feature is kinda close to audit-logs so it's relatively straight forward to do.

**Comment by LefsFlarey** [comment]
Hahaha, I'm not too sure how I may implement this, may have to go through mountains of existing code...

**Comment by Unknwon** [comment]
- Update of labels for issues and PRs: https://github.com/gogits/gogs/issues/2520https://github.com/gogits/gogs/issues/2520
- Smart commits: https://discuss.gogs.io/t/how-to-use-smart-commits/55
