### ISSUE TITLE
Dockerfile.rpi build results in Failed to set version on gopkg.in/macaron.v1

### ISSUE THREAD

**Issue by shaula** [gogits/gogs#3705]
Hi, I tried to build a Docker image upon Dockerfile.rpi on a Raspberry PI from master as well as from the latest tag. Both build failed on Hypriot OS using Docker version 1.12.1, build 23cf638.

`$ git clone -b "master" --single-branch https://github.com/gogits/gogs.git repo`
`$ cd repo`
`$ docker build -f Dockerfile.rpi .`

Output is:
`Step 8 : RUN ./docker/build.sh
 ---> Running in a14d626c3959
+ set -e
+ export GOPATH=/tmp/go
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/go/bin
+ export GO15VENDOREXPERIMENT=1
+ apk --no-cache --no-progress add --virtual build-deps build-base linux-pam-dev go
fetch http://dl-4.alpinelinux.org/alpine/v3.3/main/armhf/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/v3.3/community/armhf/APKINDEX.tar.gz
(1/29) Installing binutils-libs (2.25.1-r0)
(2/29) Installing binutils (2.25.1-r0)
(3/29) Installing gmp (6.1.0-r0)
(4/29) Installing isl (0.14.1-r0)
(5/29) Installing libgomp (5.3.0-r0)
(6/29) Installing libatomic (5.3.0-r0)
(7/29) Installing pkgconf (0.9.12-r0)
(8/29) Installing pkgconfig (0.25-r1)
(9/29) Installing mpfr3 (3.1.2-r0)
(10/29) Installing mpc1 (1.0.3-r0)
(11/29) Installing libstdc++ (5.3.0-r0)
(12/29) Installing gcc (5.3.0-r0)
(13/29) Installing make (4.1-r0)
(14/29) Installing musl-dev (1.1.12-r5)
(15/29) Installing libc-dev (0.7-r0)
(16/29) Installing fortify-headers (0.7-r0)
(17/29) Installing g++ (5.3.0-r0)
(18/29) Installing build-base (0.4-r1)
(19/29) Installing expat-dev (2.1.1-r1)
(20/29) Installing ncurses-dev (6.0-r6)
(21/29) Installing zlib-dev (1.2.8-r2)
(22/29) Installing libxml2 (2.9.4-r0)
(23/29) Installing libxml2-dev (2.9.4-r0)
(24/29) Installing libintl (0.19.6-r3)
(25/29) Installing gettext (0.19.6-r3)
(26/29) Installing gettext-dev (0.19.6-r3)
(27/29) Installing linux-pam-dev (1.2.1-r0)
(28/29) Installing go (1.5.4-r0)
(29/29) Installing build-deps (0)
Executing busybox-1.24.2-r0.trigger
OK: 317 MiB in 67 packages
+ git clone -b 0.10.2 https://github.com/Masterminds/glide /tmp/go/src/github.com/Masterminds/glide
Cloning into '/tmp/go/src/github.com/Masterminds/glide'...
Note: checking out '2d0eb388e16d833ba3c55068335b3577b6b09ff0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

+ cd /tmp/go/src/github.com/Masterminds/glide
+ make build
go build -o glide -ldflags "-X main.version=0.10.2" glide.go
+ go install
+ mkdir -p /tmp/go/src/github.com/gogits/
+ ln -s /app/gogs/ /tmp/go/src/github.com/gogits/gogs
+ cd /tmp/go/src/github.com/gogits/gogs
+ glide install
[WARN] Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/bradfitz/gomemcache.
[INFO] Fetching updates for github.com/go-macaron/binding.
[INFO] Fetching updates for github.com/urfave/cli.
[INFO] Fetching updates for github.com/go-macaron/csrf.
[INFO] Fetching updates for github.com/go-macaron/i18n.
[INFO] Fetching updates for github.com/go-macaron/inject.
[INFO] Fetching updates for github.com/go-macaron/session.
[INFO] Fetching updates for github.com/go-sql-driver/mysql.
[INFO] Fetching updates for github.com/go-macaron/toolbox.
[INFO] Fetching updates for github.com/go-xorm/core.
[INFO] Fetching updates for github.com/go-macaron/captcha.
[INFO] Fetching updates for github.com/go-xorm/xorm.
[INFO] Fetching updates for github.com/issue9/identicon.
[INFO] Fetching updates for github.com/jaytaylor/html2text.
[INFO] Fetching updates for github.com/go-macaron/cache.
[INFO] Fetching updates for github.com/gogits/git-module.
[INFO] Fetching updates for github.com/gogits/cron.
[INFO] Fetching updates for github.com/gogits/chardet.
[INFO] Fetching updates for github.com/gogits/go-gogs-client.
[INFO] Fetching updates for github.com/go-macaron/gzip.
[WARN] Unable to checkout github.com/gogits/git-module
[ERROR] Update failed for github.com/gogits/git-module: Cloning into '/tmp/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module'...
fatal: unable to access 'https://github.com/gogits/git-module/': Couldn't resolve host 'github.com'
: exit status 128
[INFO] Fetching updates for github.com/kardianos/minwinsvc.
[WARN] Unable to checkout github.com/kardianos/minwinsvc
[ERROR] Update failed for github.com/kardianos/minwinsvc: Cloning into '/tmp/go/src/github.com/gogits/gogs/vendor/github.com/kardianos/minwinsvc'...
fatal: unable to access 'https://github.com/kardianos/minwinsvc/': Couldn't resolve host 'github.com'
: exit status 128
[INFO] Fetching updates for github.com/klauspost/compress.
[INFO] Fetching updates for github.com/klauspost/cpuid.
[INFO] Fetching updates for github.com/klauspost/crc32.
[INFO] Fetching updates for github.com/lib/pq.
[INFO] Fetching updates for github.com/mattn/go-sqlite3.
[INFO] Fetching updates for github.com/mcuadros/go-version.
[INFO] Fetching updates for github.com/microcosm-cc/bluemonday.
[INFO] Fetching updates for github.com/msteinert/pam.
[INFO] Fetching updates for github.com/nfnt/resize.
[INFO] Fetching updates for github.com/russross/blackfriday.
[INFO] Fetching updates for github.com/satori/go.uuid.
[INFO] Fetching updates for github.com/sergi/go-diff.
[INFO] Fetching updates for github.com/strk/go-libravatar.
[INFO] Fetching updates for github.com/shurcooL/sanitized_anchor_name.
[INFO] Fetching updates for github.com/Unknwon/cae.
[INFO] Fetching updates for github.com/Unknwon/com.
[INFO] Fetching updates for github.com/Unknwon/i18n.
[INFO] Fetching updates for github.com/Unknwon/paginater.
[INFO] Fetching updates for golang.org/x/crypto.
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for golang.org/x/sys.
[INFO] Fetching updates for golang.org/x/text.
[INFO] Fetching updates for gopkg.in/alexcesaro/quotedprintable.v3.
[INFO] Fetching updates for gopkg.in/asn1-ber.v1.
[INFO] Fetching updates for gopkg.in/bufio.v1.
[INFO] Fetching updates for gopkg.in/editorconfig/editorconfig-core-go.v1.
[INFO] Fetching updates for gopkg.in/gomail.v2.
[INFO] Fetching updates for gopkg.in/ini.v1.
[INFO] Fetching updates for gopkg.in/ldap.v2.
[INFO] Fetching updates for gopkg.in/macaron.v1.
[INFO] Fetching updates for gopkg.in/redis.v2.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[ERROR] Failed to set version on github.com/gogits/git-module to 5e0c1330d7853d1affbc193885d517db0f8d1ca5: open /tmp/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module: no such file or directory
[ERROR] Failed to set version on github.com/kardianos/minwinsvc to cad6b2b879b0970e4245a20ebf1a81a756e2bb70: open /tmp/go/src/github.com/gogits/gogs/vendor/github.com/kardianos/minwinsvc: no such file or directory
[INFO] Setting version for github.com/urfave/cli to 1efa31f08b9333f1bd4882d61f9d668a70cd902e.
[INFO] Setting version for github.com/go-macaron/binding to 9440f336b443056c90d7d448a0a55ad8c7599880.
[INFO] Setting version for github.com/go-macaron/captcha to 8aa5919789ab301e865595eb4b1114d6b9847deb.
[INFO] Setting version for github.com/go-macaron/inject to c5ab7bf3a307593cd44cb272d1a5beea473dd072.
[INFO] Setting version for github.com/go-macaron/csrf to 6a9a7df172cc1fcd81e4585f44b09200b6087cc0.
[INFO] Setting version for github.com/bradfitz/gomemcache to fb1f79c6b65acda83063cbc69f6bba1522558bfc.
[INFO] Setting version for github.com/issue9/identicon to d36b54562f4cf70c83653e13dc95c220c79ef521.
[INFO] Setting version for github.com/go-macaron/gzip to cad1c6580a07c56f5f6bc52d66002a05985c5854.
[INFO] Setting version for github.com/go-xorm/xorm to c6c705684057842d9854e8299dd51abb06ae29f5.
[INFO] Setting version for github.com/gogits/go-gogs-client to c52f7ee0cc58d3cd6e379025552873a8df6de322.
[INFO] Setting version for github.com/go-xorm/core to 5bf745d7d163f4380e6c2bba8c4afa60534dd087.
[INFO] Setting version for github.com/jaytaylor/html2text to 52d9b785554a1918cb09909b89a1509a98b853fd.
[INFO] Setting version for github.com/gogits/cron to 7f3990acf1833faa5ebd0e86f0a4c72a4b5eba3c.
[INFO] Setting version for github.com/go-macaron/toolbox to 82b511550b0aefc36b3a28062ad3a52e812bee38.
[INFO] Setting version for github.com/go-macaron/session to 66031fcb37a0fff002a1f028eb0b3a815c78306b.
[INFO] Setting version for github.com/gogits/chardet to 2404f777256163ea3eadb273dada5dcb037993c0.
[INFO] Setting version for github.com/go-sql-driver/mysql to 0b58b37b664c21f3010e836f1b931e1d0b0b0685.
[INFO] Setting version for github.com/go-macaron/i18n to ef57533c3b0fc2d8581deda14937e52f11a203ab.
[INFO] Setting version for github.com/klauspost/compress to 14eb9c4951195779ecfbec34431a976de7335b0a.
[INFO] Setting version for github.com/go-macaron/cache to 56173531277692bc2925924d51fda1cd0a6b8178.
[INFO] Setting version for github.com/klauspost/cpuid to 09cded8978dc9e80714c4d85b0322337b0a1e5e0.
[INFO] Setting version for github.com/nfnt/resize to 891127d8d1b52734debe1b3c3d7e747502b6c366.
[INFO] Setting version for github.com/klauspost/crc32 to 19b0b332c9e4516a6370a0456e6182c3b5036720.
[INFO] Setting version for github.com/mcuadros/go-version to d52711f8d6bea8dc01efafdb68ad95a4e2606630.
[INFO] Setting version for github.com/sergi/go-diff to ec7fdbb58eb3e300c8595ad5ac74a5aa50019cc7.
[INFO] Setting version for github.com/msteinert/pam to 02ccfbfaf0cc627aa3aec8ef7ed5cfeec5b43f63.
[INFO] Setting version for github.com/lib/pq to 80f8150043c80fb52dee6bc863a709cdac7ec8f8.
[INFO] Setting version for github.com/russross/blackfriday to 93622da34e54fb6529bfb7c57e710f37a8d9cbd8.
[INFO] Setting version for github.com/mattn/go-sqlite3 to e118d4451349065b8e7ce0f0af32e033995363f8.
[INFO] Setting version for github.com/microcosm-cc/bluemonday to 9dc199233bf72cc1aad9b61f73daf2f0075b9ee4.
[INFO] Setting version for github.com/Unknwon/i18n to 39d6f2727e0698b1021ceb6a77c1801aa92e7d5d.
[INFO] Setting version for github.com/strk/go-libravatar to 5eed7bff870ae19ef51c5773dbc8f3e9fcbd0982.
[INFO] Setting version for github.com/shurcooL/sanitized_anchor_name to 10ef21a441db47d8b13ebcc5fd2310f636973c77.
[INFO] Setting version for github.com/Unknwon/paginater to 7748a72e01415173a27d79866b984328e7b0c12b.
[INFO] Setting version for github.com/satori/go.uuid to 0aa62d5ddceb50dbcb909d790b5345affd3669b6.
[INFO] Setting version for github.com/Unknwon/com to 28b053d5a2923b87ce8c5a08f3af779894a72758.
[INFO] Setting version for github.com/Unknwon/cae to 7f5e046bc8a6c3cde743c233b96ee4fd84ee6ecd.
[INFO] Setting version for golang.org/x/crypto to bc89c496413265e715159bdc8478ee9a92fdc265.
[INFO] Setting version for golang.org/x/net to 57bfaa875b96fb91b4766077f34470528d4b03e9.
[INFO] Setting version for golang.org/x/text to 2910a502d2bf9e43193af9d68ca516529614eed3.
[INFO] Setting version for golang.org/x/sys to a646d33e2ee3172a661fc09bca23bb4889a41bc8.
[INFO] Setting version for gopkg.in/bufio.v1 to 567b2bfa514e796916c4747494d6ff5132a1dfce.
[INFO] Setting version for gopkg.in/asn1-ber.v1 to 4e86f4367175e39f69d9358a5f17b4dda270378d.
[INFO] Setting version for gopkg.in/editorconfig/editorconfig-core-go.v1 to a872f05c2e34b37b567401384d202aff11ba06d4.
[INFO] Setting version for gopkg.in/alexcesaro/quotedprintable.v3 to 2caba252f4dc53eaf6b553000885530023f54623.
[INFO] Setting version for gopkg.in/ini.v1 to cf53f9204df4fbdd7ec4164b57fa6184ba168292.
[INFO] Setting version for gopkg.in/ldap.v2 to d0a5ced67b4dc310b9158d63a2c6f9c5ec13f105.
[INFO] Setting version for gopkg.in/gomail.v2 to 81ebce5c23dfd25c6c67194b37d3dd3f338c98b1.
[INFO] Setting version for gopkg.in/macaron.v1 to 7564489a79f3f96b7ac8034652b35eeebb468eb4.
[INFO] Setting version for gopkg.in/redis.v2 to e6179049628164864e6e84e973cfb56335748dea.
[ERROR] Failed to set version on gopkg.in/macaron.v1 to 7564489a79f3f96b7ac8034652b35eeebb468eb4: exit status 128
An Error has occurred
ERROR: Service 'git-server' failed to build: The command '/bin/sh -c ./docker/build.sh' returned a non-zero code: 2
`

Is this an error in your repository? How can I recover from the failure?

**Comment by techmunk** [comment]
In docker/build.sh, just before the line "glide install" add a "glide update", so it will end up being the following around line 24:

```
cd ${GOPATH}/src/github.com/gogits/gogs
glide update
glide install
```

I was building this using archlinux, and came across the same error. The above fixed my issue. Hopefully it works for you. If not, I honestly have no idea!

**Comment by edacval** [comment]
Its caused by #3690 .

**Comment by bkcsoft** [comment]
Duplicate of #3690, closing
