### ISSUE TITLE
Add abability to add path to gogs dump command

### ISSUE THREAD

**Issue by barbuslex** [gogits/gogs#3708]
Hi,

This could be useful to have the abability to specify a path parameter of the command "gogs dump" to store the backup in another location.

Exemple: 
`gogs dump "C:\temp"`

Thanks

**Comment by LefsFlarey** [comment]
Implementable, I think I can implement this. However, is this feature really needed?

**Comment by Unknwon** [comment]
On `release/0.11` branch, it's now possible to use `./gogs backup --target=...`
