### ISSUE TITLE
gogs dump command not working in powershell script

### ISSUE THREAD

**Issue by barbuslex** [gogits/gogs#3709]
Hi,

When i try to automate the gogs dump with a powershell script. I have this error: 

> .\gogs.exe : 2016/09/28 13:56:39 Creating tmp work dir: 
> C:\Users\USER~1\AppData\Local\Temp\3\gogs-dump-037245327
> Au caractère C:\scripts\POWERSHELL\dump_gogs.ps1:11 : 1
> - .\gogs.exe dump
> - ~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (2016/09/28 13:5...-dump-037245327:String) [], RemoteException
>   - FullyQualifiedErrorId : NativeCommandError
> 
> 2016/09/28 13:56:39 Dumping local repositories...C:/wwwroot/git/gogs

The script : 

```
cls

$GogsSetupPath = "C:\www\gogs"
$GogsBackupPath = "D:\Backups\GOGS"

Set-Location $GogsSetupPath
.\gogs.exe dump
Remove-Item "$GogsBackupPath\*"
Move-Item "$GogsSetupPath\gogs-dump-*.zip" $GogsBackupPath
```

This problem seems to occur because the output of gogs.exe is stderr.

Can you solve it please ?

Thanks

**Comment by LefsFlarey** [comment]
Would it be possible to get a output that is not shortened?

**Comment by barbuslex** [comment]
I dont have more output... an stderr message from gogs.exe cause this failed output.
Here the screenshot of the script's execution ; 
![capture](https://cloud.githubusercontent.com/assets/113057/19032306/3c5d4be6-8959-11e6-838a-e2ddfede45cf.PNG)

**Comment by Unknwon** [comment]
Is this still an issue?

**Comment by Unknwon** [comment]
Please notify when this issue happens again.
