### ISSUE TITLE
Explore page does not show private repo owned by login user

### ISSUE THREAD

**Issue by J-Siu** [gogits/gogs#3710]
- Gogs version (or commit ref): https://dl.gogs.io/gogs_v0.9.97_linux_amd64.tar.gz
- Git version: 2.9.3
- Operating system: Ubuntu 14.04.5 LTS (GNU/Linux 2.6.32-042stab116.2 x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No - I created 10 public repo and cannot delete them
  - [ ] Not relevant
- Log gist:
## Description
1. Create a private repo
2. Go to Explore page, the repo will not show up

...

**Comment by LefsFlarey** [comment]
I *do not* think this is a bug, as the Explore page is meant for public repositories only. You can always view private repositories on the dashboard and/or your user page.

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/3947.
