### ISSUE TITLE
registering new user with existing email address gives 500 error on confirmation

### ISSUE THREAD

**Issue by stroucki** [gogits/gogs#3713]
- Gogs version (or commit ref): 0.9.97
- Git version: 2.1.4-2.1+deb8u2
- Operating system: debian amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
  2016/09/28 18:56:22 [...routers/user/auth.go:281 Activate()] [E] UpdateUser: e-mail has been used
## Description

When creating a test account using an existing email address, the process lets Gogs register the account and send an email confirmation request. When clicking on that, a 500 error appears. Tested on try.gogs.io (user ids sepoy and gaul).
If it is an error to have two accounts with the same email address, it should be prevented to register a new account. At least, it should display an error instead of just the 500.
...

**Comment by estan** [comment]
I had this issue as well, I think it should give an error already when trying to sign up. Or it should allow multiple users with the same e-mail. But the 500 on confirmation is just confusing.

**Comment by joubertredrat** [comment]
Duplicate with https://github.com/gogits/gogs/issues/3681
