### ISSUE TITLE
Failed to send notify email when user has non-ascii characters in name

### ISSUE THREAD

**Issue by wociscz** [gogits/gogs#3714]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: 
- Operating system: Ubuntu 16.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

When user has non-ascii characters (czech utf-8 glyphs in my case) in name, gogs fail to send notify email.
When i change username to only ascii, email sent & delivered without problem.
In this scenario user name is "Testovací Uživatel" (aka testing user in english)
gogs.log:

```
2016/09/29 14:29:58 [T] Issue created: 3/7
2016/09/29 14:29:58 [T] New e-mail sending request [user@mydomain.cz]: Subject: [testovaci] Nove issue (#7), issue comment
2016/09/29 14:29:58 [...les/mailer/mailer.go:201 processMailQueue()] [E] Fail to send emails [user@mydomain.cz]: Subject: [testovaci] Nove issue (#7), issue comment - gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?\"Testovac=C3=AD_U=C5=BEivatel\"_<gogsgit@mydomain.cz>?=": mail: expected single address, got "?="
```

Relevant mailer part from config:

```
[mailer]
ENABLED = true
SEND_BUFFER_LEN = 100
SUBJECT = %(APP_NAME)s
HOST = 10.10.42.1:25
DISABLE_HELO =
HELO_HOSTNAME =
SKIP_VERIFY = true
USE_CERTIFICATE = false
CERT_FILE = custom/mailer/cert.pem
KEY_FILE = custom/mailer/key.pem
FROM = "Gogs Git" <gogsgit@mydomain.cz>
USER = gogsgit@mydomain.cz
PASSWD =
ENABLE_HTML_ALTERNATIVE = false
```

Looks to me like wrong type of utf-8 encoding of user name...
...

**Comment by RichieB2B** [comment]
You should only specify a plain E-mail address as FROM:
```
FROM = gogsgit@mydomain.cz
```

**Comment by flomine** [comment]
same problem and I have a plain E-mail address as FROM

**Comment by ogarcia** [comment]
Same here:

```
2017/01/24 10:55:23 [...les/mailer/mailer.go:201 processMailQueue()] [E] Fail to send emails [anon1@anon.com anon2@anon.com anon3@anon.com]: Subject:  [ssh-config] Cambiado el nombre de pro-mc-al a mcs-salto (#2), issue comment - gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?\"=C3=93scar_Garc=C3=ADa_Amor\"_<>?=":  mail: invalid string
2017/01/24 10:57:13 [...les/mailer/mailer.go:201 processMailQueue()] [E] Fail to send emails [anon1@anon.com anon2@anon.com anon3@anon.com]: Subject:  [ssh-config] Cambiado el nombre de pro-mc-al a mcs-salto (#2), issue comment - gomail: could not send email 1: gomail: invalid address "\"Eric Sanchez Diaz\" <>": mail: invalid string
```

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4055, please help test on `develop` branch.

**Comment by ogarcia** [comment]
@Unknwon I do severar tests and my PR fix all related bugs except this. There is an issue with UTF-8 characters.

```
2017/01/25 13:12:43 [...les/mailer/mailer.go:201 processMailQueue()] [E] Fail to send emails [user@example.com]: Subject: [os2config] Updated deprecated code (#1), issue comment - gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?\"=C3=93scar_Garc=C3=ADa_Amor\"_<git@git.server.lan>?=": mail: expected single address, got "?="
```

I have in _Full Name_ **Óscar García Amor**.

Unfortunately my go knowledge not is strong enough to make a PR to fix this 😢

**Comment by Unknwon** [comment]
@ogarcia thanks for the info! Found the issue: https://github.com/golang/go/issues/12492

**Comment by Unknwon** [comment]
GitHub seems handling it without any problem, I think a work around solution would be fall back to username (which only possible to be ASCII characters) if display name contains non-ASCII characters.

**Comment by ogarcia** [comment]
Yes, is a good work around :+1: 

But I'm see the module that gogs uses to send mail and it supports well the non-ascii chars in *FROM* header.

I do small sample that works.

```go
package main

import (
  "io"
  "fmt"
  "gopkg.in/gomail.v2"
) 

func main () {
  m := gomail.NewMessage()
  m.SetAddressHeader("From", "oscar@example.com", "Óscar García Amor")
  m.SetHeader("To", "alice@example.com", "bob@example.com")
  m.SetHeader("Subject", "Hello!")
  m.SetBody("text/html", "Hello <b>Alice</b> and <i>Bob</i>!")
    
  d := gomail.NewDialer("smtp.server.example.org", 587, "username", "password")

  // Send the email
  if err := d.DialAndSend(m); err != nil {
    panic(err)
  }
} 
```

It sends me the mail well formated with *Óscar García Amor* in FROM.

I think that the key is use `SetAddressHeader` for format the from.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4060, please help test on `develop` branch or https://try.gogs.io.

**Comment by tldzyx** [comment]
@Unknwon 测试当前最新版本 gogs-0.11.53-windows_amd64_mws.zip 时, 配置 `app.ini`文件中

``` ini
[mailer]
ENABLED = true
HOST    = smtp.qiye.aliyun.com:465
FROM    = "静静" <noreply@example.com>
```

经过测试发不出邮件, 提示为
```
发送测试邮件至 'test@example.com' 时失败：gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?\"=E9=9D=99=E9=9D=99\"_?=": mail: expected single address, got "?="
```

将FROM 改为

``` ini
FROM    = "JingJing" <noreply@example.com>
```

则正常接收到了, 希望对修复问题有用.

**Comment by Unknwon** [comment]
@tldzyx I think it is problem of gomail package, and the active fork https://github.com/go-mail/mail also does not seem to have fixed this problem.
