### ISSUE TITLE
jupyter notebook support

### ISSUE THREAD

**Issue by oroszl** [gogits/gogs#3715]
One of the neatest features of github is its ability to render jupyter notebooks.
This sort of feature has also came up as a request in the gitlab community.
So I thought I might bring it to gogs as well. 
Github uses nbconvert as a server side solution for rendering the notebooks but there have been some client side proposals for the same, see for example [here](https://github.com/kokes/nbviewer.js) and [here](https://github.com/nteract/notebook-preview).
I think having this feature would greatly increase the appeal of gogs for certain type of users.

**Comment by kellpossible** [comment]
I've got a few notebooks in one of my repos, might check out how hard this would be to do

**Comment by bkcsoft** [comment]
https://github.com/fabian-z/gopherlab would probably be a good starting-point if anyone wanna have a crack at this

**Comment by oroszl** [comment]
@bkcsoft I dont think your link is relevant here.. my suggestion was to have the capability in gogs to display jupyter notebooks not to have a go kernel for jupyter. The stuff you see in the link you posted is just a display of github's capability to rendner notebooks for a go kernel.

**Comment by tgy** [comment]
**I would also be greatly interested in seeing this feature in Gogs.**

I wonder how it's implemented on GitHub but I don't think it is too complicated.

If I had to implement it I would use a program that converts notebooks to HTML server-side like [nbconvert](https://nbconvert.readthedocs.io/en/latest/) and include this HTML in the page showing the notebook file. The problem with this approach is that there is a need for `jupyter` to be installed on the server (I'm not entirely sure but if the notebook's version and the version installed server-side differ there might be a problem). What would be better is to convert the notebook directly on the client's browser using JavaScript but I'm not convinced such a tool exists and it doesn't solve the potential version mismatch issue.

**Comment by prinsherbert** [comment]
I created a PR for this feature, regarding **Python** notebooks. Probably there are some easy fixes to also make it work for other languages, but I can not test this as I have only experience using i**py**nb's.

https://github.com/gogits/gogs/pull/4067

**Comment by oroszl** [comment]
As far as I know there is not a lot of difference to other kernels in the ipynb format, if you work with other kernels they will use the same format, with maybe a minimal overhead in metadata specifying the language..

**Comment by prinsherbert** [comment]
@oroszl Indeed, there isn't a lot of difference to the best of my knowledge. However, styling can go wrong and possibly also other stuff that I can't test thoroughly because I'm not using non-python notebooks.

If someone wants to include non-python support, (s)he would have to add the right syntax highlighting class [here](https://github.com/gogits/gogs/pull/4070/commits/a26630232eaf4a4685d89a985449f244d6ef8658#diff-2ec327528ed2be8dd3c2201ef8e6a42cR52).

And possibly consider changing the id `#ipython-notebook` to something else, like `#jupyter-notebook`.

Finally the detection of ipython notebooks is done by file extension, no idea how that works for non-python: [link](https://github.com/gogits/gogs/pull/4070/commits/a26630232eaf4a4685d89a985449f244d6ef8658#diff-e94e9b4d4f46155b5196a1a895c3136fR159)

Like said, I'm not touching the non-python issue myself.

**Comment by prinsherbert** [comment]
@Unknwon merged a [PR](https://github.com/gogits/gogs/pull/4070) for ipython notebook render support.

@oroszl If you wish to include support for non-python languages, now might be a good time to create a PR for that. Also see the aforementioned comments.

**Comment by oroszl** [comment]
This is great!
I just pulled the fresh docker container and it works out of the box!
I also tried just how it handles a note book in R and it seemed to do the job.. although it was a pretty basic example notebook..

**Comment by Unknwon** [comment]
@oroszl I guess any notebook that produces JSON with same format, the notebook.js can render it regardless of language because no computation was involved.

**Comment by prinsherbert** [comment]
That is correct, as long as the filename ends with `.ipynb`. However, all code is shown with python syntax highlighting.

**Comment by Unknwon** [comment]
@prinsherbert maybe we should not explicitly tell highlightJS what language to render, but let it detects?

**Comment by prinsherbert** [comment]
@Unknwon Actually, the language is in the JSON:

https://nbformat.readthedocs.io/en/latest/format_description.html

One might consider to hard-code some popular language and gracefully degradate to automatic detection/

I'm still not sure what non-python notebook file extensions are common, can someone with experience expand on this?

**Comment by Unknwon** [comment]
@prinsherbert no, I mean after rendered by notebook.js, highlightJS is able to detect and highlight code blocks based on result of notebook.js.

**Comment by prinsherbert** [comment]
@Unknwon I get that, but that sounds like magic which can go wrong, especially for one-liners or expressions. Hence I would suggest to use if after *hard detecting* some popular languages using the meta information in the notebook.

**Comment by Unknwon** [comment]
@prinsherbert OK.. let's just keep the way it is for now.

**Comment by oroszl** [comment]
is there a way to wire out some config options and let the admin decide ?

**Comment by Unknwon** [comment]
@oroszl does notebook-like in other language, let's say R, have different or identical file extension?

**Comment by oroszl** [comment]
identical.. all notebooks come in the `.ipynb` extension.

**Comment by Unknwon** [comment]
@oroszl that's is.... hard to make a configuration.

**Comment by oroszl** [comment]
@prinsherbert Why do you think trusting highlightJS is such a bad idea ?
I have tried some further notebooks, mainly the ones provided at [try.jupyter](https://try.jupyter.org/)
And the `haskell` and `julia` examples do not rendner, but I suspect it is not a language specific problem as you also mentioned in the PR  thread that you had some `python` notebooks not rendnered.. 
Any idea why this might be ?

**Comment by Unknwon** [comment]
This one (https://github.com/gopherds/gophernotes) looks interesting, too.

**Comment by oroszl** [comment]
[This](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) is a list of currently available jupyter kernel with some examples where available.

**Comment by Unknwon** [comment]
Guess we need repo-based configuration for `.ipynb` to let author of notes to decide what language to highlight.

**Comment by oroszl** [comment]
is that hard ?

**Comment by Unknwon** [comment]
It is easy in terms of implementation, but hard to make a kind of standard because it opens a new way to customize Gogs. 

So I think the purpose of this issue has been transformed to: customized syntax highlighting language for jupyter notebook?

**Comment by oroszl** [comment]
yep
I am also tempted to close the original issue, since it now does the notebook rendering and it works quite well. Shall I close it ?

**Comment by Unknwon** [comment]
@oroszl I prefer to close and create a new one to be focus on the customization part.

**Comment by oroszl** [comment]
OK lets close! Issue solved!

**Comment by Unknwon** [comment]
Follow up issue: https://github.com/gogits/gogs/issues/4097
