### ISSUE TITLE
Install: allow sender's username to be non-email

### ISSUE THREAD

**Issue by 2ion** [gogits/gogs#3717]
The issue will be closed without any reasons if it does not satisfy any of following requirements:
- Gogs version (or commit ref):  0.9.97.0901
- Operating system: Debian Linux Jessie amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
## Description

When performing the installation via the web UI, the mailer does not allow for configuring the SMTP authentication credentials user/password to be configured indepedently from the From: address but assumes that the authenticated user name is equal to the From: address. Moreover, form validation leads to the user always being a 'valid' mail address.

This breaks the mailer config whenever user != From: address, which is not an unusual occurence.

It would be great if this scenario could be supported by the installer mask, as fixing configuration keys manually after they should have been set by the installer routine is an unnecessary duplication of effort.

**Comment by CWempe** [comment]
I totally agree.

In fact both my main email providers (private and at work) don't use the mail address as user name.

**Comment by Unknwon** [comment]
Just realize this is already implemented:

![image](https://cloud.githubusercontent.com/assets/2946214/22852398/6ddab6b0-f009-11e6-962c-e8e172809500.png)

**Comment by CWempe** [comment]
This is not fixed.

The form still does not allow user name other than valid mail adress.

![image](https://cloud.githubusercontent.com/assets/1270359/22853568/6c5a8abc-f05a-11e6-9e30-dd9c2d7677cf.png)

**Comment by Unknwon** [comment]
Didn't clear about the problem, got it now. :sweat:

**Comment by Unknwon** [comment]
But, @CWempe your request is different from what the thread's original title.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by CWempe** [comment]
It works!

Thanks
