### ISSUE TITLE
Support for SSL client certificate verification

### ISSUE THREAD

**Issue by estan** [gogits/gogs#3718]
We would love to use Gogs, but our organization has a policy that all external access to internal web sites must be done using verified SSL client certificates (we each have our own SSL client certificate). I've looked through the Gogs config, but can't find an option to require SSL client certificate verification for the Gogs web UI. This would be an option equivalent to the `SSLVerifyClient require` Apache option.

Hopefully this is something that can be added relatively easy?

**Comment by sqc1999** [comment]
I think it'll be better to use a reverse proxy(e.g. nginx) and configure it for client certificates.

**Comment by estan** [comment]
@sqc1999: Ah yes, I just found out about that possibility. I should be able to set up a reverse proxy on the Apache instance we already have.

So feel free to close this issue, or at least give it a very low priority.
