### ISSUE TITLE
Better ways to find interesting repositories

### ISSUE THREAD

**Issue by dasyrw9hfh** [gogits/gogs#3720]
- Gogs version (or commit ref): dev
- Git version: dev
- Operating system: GNU
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes   https://try.gogs.io/explore/repos
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

It's very difficult to find interesting projects when there are a lot of repositories. Could you please add a better way to search repositories? Right now it's only possible to search by repo name.
For example you could add a "tag/label" system to tag repositories, such that other people can search interesting repositories by tag.

**Comment by Unknwon** [comment]
Thanks for the feedback!

This sounds very fancy but I think all you need is https://github.com/gogits/gogs/issues/1253.
