### ISSUE TITLE
Labels are not visible in organisation issue overview or user issue overview

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3723]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.1.5
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) (needs login)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

See attached screenshots.

![screen1](https://cloud.githubusercontent.com/assets/1267617/19053383/00f359a8-89bb-11e6-9f18-9934db2e6641.PNG)
![screen2](https://cloud.githubusercontent.com/assets/1267617/19053384/00f6ebcc-89bb-11e6-9851-cf8af9e705c3.PNG)

**Comment by Unknwon** [comment]
Because it is just impossible or will be a mess to show all labels from all repos from all related repositories. This is by design!

**Comment by xor-gate** [comment]
Great!
