### ISSUE TITLE
Filtering on assignee and labels in organization issue overview.

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3724]
- Gogs version (or commit ref): 0.9.97.0901 
- Git version: 2.1.5
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

It is now not possible from the /org/<org>/issues overview to filter issues by label or assignee. Filtering on assigned to me is greatly appreciated.

**Comment by Unknwon** [comment]
Same response as https://github.com/gogits/gogs/issues/3723 ....
