### ISSUE TITLE
Assigning a user or adding a label to an issue is not registered and also not updates the last-changed date/time 

### ISSUE THREAD

**Issue by rikvdh** [gogits/gogs#3725]
- Gogs version (or commit ref): 0.9.97.0901 
- Git version: v2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

When changing an issue's milestone, assignee and/or labels the last modified is not updated and also are these mutations not logged.

Having this traceability is greatly appreciated.

**Comment by Unknwon** [comment]
Hmm, what is definition of your **last modified** here?
