### ISSUE TITLE
Incompatible Issues API

### ISSUE THREAD

**Issue by bkcsoft** [gogits/gogs#3729]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

The current implementation for Issues API isn't compatable with GitHubs API. I'm proposing that this is fixed.
Reasons being:
- Docs states that Gogs aims to be compatible.
- Ability to use existing libs for talking to Gogs
- External services can support Gogs "for free" by having support for GitHub (which most do already)
#### Data-format

gogs:

``` json
{
  "id": 1,
  "name": "foobar",
  "color": "#bada55"
}
```

GitHub:

``` json
{
  "name": "foobar",
  "color": "bada55",
  "url": "https://api.github.com/repos/foo/bar/labels/foobar"
}
```
#### Fetching by `:id` instead of `:name`

Gogs: `/repos/:owner/:repo:/labels/:id`
GitHub: `/repos/:owner/:repo/labels/:name`

I'll add more things here as they appear

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/pull/4549
