### ISSUE TITLE
Runtime error on Login

### ISSUE THREAD

**Issue by MrFloppy** [gogits/gogs#3730]
Today I installed gogs from binary and received the following error on Ubuntu 16.04 64bit:

> Oct  4 19:31:29 shadow gogs[14427]: [Macaron] 2016-10-04 19:31:29: Started POST /user/login for 192.168.2.109
> Oct  4 19:31:29 shadow gogs[14427]: 2016/10/04 19:31:29 #033[1;34m[D] Session ID: a034226c031a88f4#033[0m
> Oct  4 19:31:29 shadow gogs[14427]: 2016/10/04 19:31:29 #033[1;34m[D] CSRF Token: wIpxhrvHAmtGUCfNyM1XLSsG4Qc6MTQ3NTYwMjEzMjMyMDkwNDM0Mw==#033[0m
> Oct  4 19:31:29 shadow gogs[14427]: [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/panic.go:458 (0x434743)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/panic.go:62 (0x43329d)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
> Oct  4 19:31:29 shadow gogs[14427]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/net/http/server.go:2202 (0x70144d)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/net/http/server.go:1579 (0x6fde57)
> Oct  4 19:31:29 shadow gogs[14427]: /usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
> Oct  4 19:31:29 shadow gogs[14427]: [Macaron] 2016-10-04 19:31:29: Completed /user/login 500 Internal Server Error in 26.694022ms

Is this my fault?

**Comment by bkcsoft** [comment]
Running v0.9.97 and LDAP? there's a known bug in that version
https://github.com/gogits/gogs/issues/3578

**Comment by MrFloppy** [comment]
v0.9.97 is correct but not LDAP. Just a fresh installed instance with only the admin user created.
Any further ideas?

**Comment by maksar** [comment]
@MrFloppy I was able to reproduce this too. It happens only if no admin user credentials were specified on setup.
If admin user settings was specified on setup – error disappears.

**Comment by bourbonspecial** [comment]
Im seeing this on a fresh install of gogs on windows 7 64 bit (happened to try it on an EC2 instance running windows server 2012 and had the same issue).

@maksar your suggestion works.

Pretty nasty bug from a user experience point of view as it breaks the default install (create admin account details is collapsed on the install page).

**Comment by MrFloppy** [comment]
@maksar: You are right. I did this (by accident to be honest). 
Probably the creation of an admin user should be forced or this needs a bugfix.

Thank you for the great research!

**Comment by hsharrison** [comment]
Not sure if I'm having the same problem, but my Gogs server was working for a while but now after a restart I'm getting this error. I think I setup an admin account. Is there a way to do so now?

**Comment by mbugeia** [comment]
Hi, same problem with the yunohost integration here https://github.com/YunoHost-Apps/gogs_ynh
 
The issue is not present in v0.9.71 and everything works fine if I do an install of v0.9.71 login then upgrade to v0.9.97.

**Comment by Unknwon** [comment]
I think this is a fixed bug in `master`.
