### ISSUE TITLE
Admin panel allow to create user with email address already used by another user.

### ISSUE THREAD

**Issue by J-Siu** [gogits/gogs#3731]
- Gogs version (or commit ref): https://dl.gogs.io/gogs_v0.9.97_linux_amd64.tar.gz
- Git version: 2.9.3
- Operating system: Ubuntu 14.04.5 LTS (GNU/Linux 2.6.32-042stab116.2 x86_64) 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No - Need access to admin panel
  - [ ] Not relevant
- Log gist:

  `2016/10/05 02:07:58 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: updateUser: e-mail has been used [email: <email address>]`

### Step to reproduce

1. Configure admin user profile email.
2. Use admin panel to create user with same email address as admin.
3. Login to new user with username. Create new repo will result in "Error 500" page.

### Expected behavior

Admin panel should not allow new user with email address already used by another account.

**Comment by joubertredrat** [comment]
Duplicated with #3681

**Comment by J-Siu** [comment]
oops, sorry, please close!

**Comment by joubertredrat** [comment]
@J-Siu nah, no problem, your help are welcome :)
