### ISSUE TITLE
How to Configure Gogs docker repository.upload Allowed_Types?

### ISSUE THREAD

**Issue by kolbma** [gogits/gogs#3733]
Hi,
how do you set the Allowed_Types in the official Docker Container?
I've tried to set it in /data/gogs/conf/app.ini and /data/gogs/custom/conf/app.ini with no success.

In the 2nd I've put in
[repository.upload]
ALLOWED_TYPES = image/jpeg|image/png|application/pdf|application/zip|text/plain

The file selection dialog shows only jpg and png files and if I select all files and use a text/plain file it says in the upload area that this filetype is not allowed.

How do I do it?

**Comment by Unknwon** [comment]
For issue/comment attachment, you should use https://github.com/gogits/gogs/blob/master/conf/app.ini#L288.

**Comment by martinellison** [comment]
Does not work for me. I say:

```
[repository.upload]
ENABLED = yes
ALLOWED_TYPES =
```
I just get JPEG and PNG.

**Comment by Unknwon** [comment]
@martinellison https://github.com/gogits/gogs/blob/master/conf/app.ini#L275

**Comment by martinellison** [comment]
Yes, I saw that. But we want to be able to upload any kind of attachment, and I thought that we could do that by setting ALLOWED_TYPES to blank. But it does not work that way; I have set ALLOWED_TYPES to blank and we cannot upload DOCX files as we want.

**Comment by martinellison** [comment]
* You might want to give the deduced type (`fileType`) in the log message (in `routers/repo/issue.go`) so that administrators can set it in `app.ini`.
* I'm not sure whether the file types should be separated by '|' or ','. You seem to be doing both.

**Comment by Unknwon** [comment]
Actually `*/*` allows everything.

**Comment by kolbma** [comment]
Why you've closed this? I've no solution. If I add filetypes to the app.ini, it doesn't change anything during runtime.

**Comment by Unknwon** [comment]
Because post template says more than clear this is not a place to ask questions.

**Comment by kolbma** [comment]
Up to now this is a bug, because description in configuration file app.ini says it should work like this and it doesn't! You can also put image/gif in there and you can't upload gif files.

**Comment by Unknwon** [comment]
>The file selection dialog

1. This is vague sentence,
2. take a screenshot

**Comment by martinellison** [comment]
I changed the config line to `ALLOWED_TYPES = */*`, restarted gogs, and tried to upload a TXT file. 

There is nothing in the issue page now to visibly indicate any uploaded file, nor any message in the gogs log about uploading (successfully or otherwise). So presumably gogs did not do the upload.

**Comment by Unknwon** [comment]
@martinellison please provide screenshots to prove your report.

**Comment by martinellison** [comment]
![screenshot_2017-02-28_09-40-54](https://cloud.githubusercontent.com/assets/8916354/23387897/41d66b1a-fd9a-11e6-9879-50f79ff63b7b.png)
![screenshot_2017-02-28_09-43-30](https://cloud.githubusercontent.com/assets/8916354/23387930/692381a8-fd9a-11e6-90be-dc640a121640.png)

**Comment by Unknwon** [comment]
@martinellison thanks. Can you check web console see if JS or network errors there?

**Comment by Unknwon** [comment]
@martinellison apparently I think you just ignored my comment which told you changed the wrong config option, demo site can upload any file type without problem. https://try.gogs.io/unknwon/hello/issues/1

**Comment by martinellison** [comment]
![screenshot_2017-02-28_09-43-30](https://cloud.githubusercontent.com/assets/8916354/23388129/615f799e-fd9b-11e6-8834-a807bece0a22.png)
![screenshot_2017-02-28_09-40-54](https://cloud.githubusercontent.com/assets/8916354/23388130/61652fe2-fd9b-11e6-9254-1211243421cf.png)

**Comment by martinellison** [comment]
I'm running 0.9.141.0211, is the `*/*` new since then? 

I've added an "[attachment]" section as per your example, and it did not change things. But when I have time I will upgrade to the latest if that will help.

**Comment by Unknwon** [comment]
@martinellison your `grep` doesn't even give you line number which proves nothing: https://github.com/gogits/gogs/blob/master/conf/app.ini#L269-L275 Make sure you change the value under correct section.

**Comment by martinellison** [comment]
I have now upgraded to 0.10 and */* is working now,
