### ISSUE TITLE
[Feature Request] Project tab for organizing

### ISSUE THREAD

**Issue by pchaganti** [gogits/gogs#3734]
- Gogs version (or commit ref): NA
- Git version: NA
- Operating system: 
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

GH has a projects tab to organize your work and plan projects. Are there any plans to add something like this? This would be seriously useful for organizing things.

thanks!

**Comment by andreynering** [comment]
Duplicated of #3716
