### ISSUE TITLE
Add subdirectory to repository

### ISSUE THREAD

**Issue by dzach** [gogits/gogs#3735]
- Gogs version (or commit ref):  0.9.97.0901
- Git version: 2.1.4
- Operating system: Linux Rasbian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist:

## Question / Feature request
Is there any way to add a subdirectory to a repository? Mirroring a repository already recreates the original subdirs, but that's a very cumbersome workaround.

Thanks!

**Comment by pyhedgehog** [comment]
```shell
git clone .../foobar.git
cd foobar
mkdir aaabbb
git add aaabbb
git commit -m "add aaabbb"
git push
```

**Comment by dzach** [comment]
Thank you for the quick reply and the suggestion.
However the suggested workaround requires using a local git repository, or direct access to the remote (gogs') git repository, and it does not involve Gogs. I was looking for a way to do it using Gogs web interface.

Would be very helpful to have this functionality added to Gogs.
Thanks!

**Comment by bkcsoft** [comment]
To create new dirs, name the file `subdir/.gitkeep` and put a space in it.

**Comment by dzach** [comment]
Nice!
Thank you!
