### ISSUE TITLE
Assign issue to user with read only

### ISSUE THREAD

**Issue by uziel200** [gogits/gogs#3739]
When an issue is created just is possible to assign to a member who has write access. 

In development, sometimes an issue is not about code is about client feedback, so a member of the organization is assign to document that issue to the client and don't need to have write access to the code.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

If the user doesn't show up, try to change visibility of the repository (private -> public, public -> private)
