### ISSUE TITLE
Pull requests don't work if branch name is 7 characters or longer

### ISSUE THREAD

**Issue by samuelson** [gogits/gogs#3743]
- Gogs version (or commit ref): 0.9.99.0903, 0.9.97, 0.9.99.0915
- Git version: 2.1.3.36.g8e36a6d
- Operating system: OSX 10.11.6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: https://try.gogs.io/samuelson/foo/compare/product...product
  - [ ] No
  - [ ] Not relevant
- Log gist: No relevant logs
## Description

We'd like to use gogs for a Puppet control-repo. This usually means making the default branch "production" instead of "master".

It seems that any name beginning with the string "product" triggers this issue. When I use any other name for the base branch, the new Pull Request dialog shows drop down menus to select the branches.  When I use "product", it doesn't show drop down menus and only shows links to the product branch.

Attempting to track this down, I tried some protected words from the code, and the word "present" also triggered the bug.   I was able to repro with any branch name that is 7 characters or longer.

This is currently a blocker for us.

Edit: Narrowed down issue to branches 7 characters or longer

**Comment by samuelson** [comment]
I suspect this is related to how the SHA's are shortened when comparing two commits instead of two branches.

**Comment by samuelson** [comment]
Is it related to this? https://github.com/gogits/git-module/pull/10

**Comment by samuelson** [comment]
I'm pretty sure this is the source of the problem:
https://github.com/gogits/gogs/commit/7eafe3213f456bb4fcbaeea5562ab60c4ef6cf87

**Comment by samuelson** [comment]
Ok, it looks like it's any branch name that's 7 characters or longer not just the base.

Sorry to keep updating my own ticket, I'm trying to figure this out and I'm hoping someone who has a better understanding of this project will know how to fix it.

**Comment by samuelson** [comment]
@Unknwon that PR fixed it for me ^^ but I don't know enough about the project to know if that might break something else.

**Comment by 0xbaadf00d** [comment]
I think, Is not the root of the problem, cause now if your branch name length = 40 characters you will still have the same issue.

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/gogs/pull/3851.
