### ISSUE TITLE
User login still required in order to see public repositories even though REQUIRE_SIGNIN_VIEW is set to false

### ISSUE THREAD

**Issue by jaydio** [gogits/gogs#3744]
The issue will be closed without any reasons if it does not satisfy any of following requirements:
- Gogs version (or commit ref): 

gogs-0.9.97-1472903388.491407d.centos7.x86_64
- Operating system: 

CentOS7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (no admin access)
- Log gist:
## Description

Currently REQUIRE_SIGNIN_VIEW is set to false but users are still required to sign in to explore public repositories. I've tested this on another server running version gogs-0.9.71-1471499392.7f7216b.centos7.x86_64 where it's working fine.

**Comment by wjx0912** [comment]
i have the same problem:
(1)current version 0.9.71 work fine, if not login, the main page will auto redirect x.x.x.x/user/login
(2)if update to 0.9.113, if not login, anonymous can see some repositories

it's a bug?

**Comment by Unknwon** [comment]
Hi, I believe your configuration did not take effect, which could possible you're targeting the real config file you're intended to after upgrade. Because you can surely view any public repositories on https://try.gogs.io without sign in.
