### ISSUE TITLE
[feature request] Add option to set a per-user value of "maximum number of repositories"

### ISSUE THREAD

**Issue by not-the-smartest-pikachu-in-the-world** [gogits/gogs#3745]
- Gogs version (or commit ref):  dev
- Git version:  dev
- Operating system:  Fedora
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

There is [a global limit](https://github.com/gogits/gogs/blob/master/conf/app.ini#L18) of the number of repositories that a user can create.
Would it be possible to add a per-user value to override the default global limit? Say, if this option is set, than users have a limit specified by this value, otherwise they use the default global value.

**Comment by joubertredrat** [comment]
I think that is possible to set this on user options, if exists limits, override defaults, if not, use system configs

**Comment by strk** [comment]
Yep, I'm also seeing the option in `/admin/users/###`
`Maximum Repository Creation Limit ... (Set -1 to use global default limit)`

Does it not work for you @not-the-smartest-pikachu-in-the-world ?
If so, please close the issue.
