### ISSUE TITLE
Can't disable response times in footer

### ISSUE THREAD

**Issue by LukasMa** [gogits/gogs#3746]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 1.8.3.1
- Operating system: CentOS 7 (7.2)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
## Description

I can't get rid of the response times in the footer. This is set in my custom `app.ini` file:

```
[other]
SHOW_FOOTER_VERSION            = false
SHOW_FOOTER_TEMPLATE_LOAD_TIME = false
```

Has some experienced a similar issue?

**Comment by bkcsoft** [comment]
This was added in bc902b8f745efe91e9dce5e4c5f5f2d5d760fbfb which isn't released yet unfortunately.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3492.
