### ISSUE TITLE
Date/time when using CZ localization

### ISSUE THREAD

**Issue by mhaluska** [gogits/gogs#3751]
- Gogs version (or commit ref): gogs 0.9.97-1472903388.491407d.jessie amd64
- Git version: N/A
- Operating system: Debian GNU/Linux 8.6 (jessie)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/explore/repos --> and change language to "čeština"
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A
## Description

Showed time/date is wrong when using CZ localization, see difference below between EN->CZ. Issue not found for other of languages.
EN: Updated 22 minutes ago
-->
CZ: Upraveno %!s(int64=22) %!d(string=před) minutami

**Comment by Unknwon** [comment]
I think it's fixed now.
