### ISSUE TITLE
Error remover user of organization  

### ISSUE THREAD

**Issue by avelino** [gogits/gogs#3752]
The issue will be closed without any reasons if it does not satisfy any of following requirements:
1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**
- Gogs version (or commit ref): 0.9.58.0726
- Git version: 2.6.6
- Operating system: alpine:3.3
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
## Description

{"err":"pq: syntax error at or near \")\"","ok":false}
URL: http://beta.shelfgit.com/org/nuveo/members/action/remove?uid=8

Used docker image: https://hub.docker.com/r/gogs/gogs/

**Comment by vivace-io** [comment]
@avelino you have given no information to work from as far as Gogs/Git/OS versions and other info. Could you provide this?

**Comment by avelino** [comment]
@vivace-io sorry, update meta info on description

**Comment by Unknwon** [comment]
Thanks for the feedback, but I do recommend upgrade Gogs and report back...
