### ISSUE TITLE
if repo is empty, and push fails due to hook declining, Gogs shows 500 page

### ISSUE THREAD

**Issue by stroucki** [gogits/gogs#3753]
- Gogs version (or commit ref): 2bec8a4f1ef6b48220a0010c1482e561abd55810
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
  2016/10/08 01:18:30 [...ules/context/repo.go:284 func1()] [E] GetBranches: exit status 1
## Description

Gogs repositories in my install get a pre-receive hook from a template that tries to police against abuse.

If a repository is freshly created, and the user pushes to a repository, the git receive-pack --stateless-rpc command is run. It will output status information, including something matching ^[0-9a-f]{4}ng refs/heads/master pre-receive hook declined$ if the pre-receive hook declines.

If the hook declined, the execution if the git command itself is considered successful. The OnSuccess callback is called, which calls PushUpdate, which calls CommitRepoAction, which sets repo.IsBare to false.

When trying to view the repo in the web interface, Gogs returns a 500 error, and logs the above line, because the repo is still empty, yet the repo.IsBare flag is false at models/context/repo.go:268.

**Comment by Unknwon** [comment]
Hi, does this still happen in the latest `master`?

**Comment by Unknwon** [comment]
Please notify when this issue happens again.
