### ISSUE TITLE
Wiki-Files with a dash (-) in it can not be navigated to

### ISSUE THREAD

**Issue by tkausl** [gogits/gogs#3754]
- Gogs version (or commit ref): 0.9.99.0903 (try.gogs.io)
- Git version: unknown (try.gogs.io) and not relevant
- Operating system: not relevant
- Database: not relevant
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes: https://try.gogs.io/tkausl/Gogs/wiki/_pages
  - [ ] No
  - [ ] Not relevant
## Description

Try to navigate to `Contributing-Code` on https://try.gogs.io/tkausl/Gogs/wiki/_pages, it redirects you right back to `_pages`. The problem is, gogs replaces all spaces in filenames with dashes `-` to build the URL and undoes this replacement to find the file, see https://github.com/gogits/gogs/blob/master/models/wiki.go#L26-L37
The problem is, if a filename originally contained the dash (`Contributing-Code`) it replaces this dash with a space anyway and tries to load a `Contributing Code` which does not exist.

**Comment by bkcsoft** [comment]
Unable to reproduce this since the test-repo doesn't exist (or is made private). And when creating a page called `Foo-Bar` on 0.9.99.915 it will name it `Foo Bar` instead.

**Comment by tkausl** [comment]
Sorry, it's public now.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
