### ISSUE TITLE
Fail to initialize ORM engine: migrate: do migrate: Sync2: no such index: IDX_comment_"idx_comment_IDX_comment_issue_id"

### ISSUE THREAD

**Issue by andreasfaerber** [gogits/gogs#3759]
Greetings,
- Gogs version (or commit ref): 0.9.99.0915
- Git version: n/a?
- Operating system: CentOS7, Docker 1.10.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
## Description

when trying to update my docker container from 0.9.71 to the currently latest version 0.9.99.0915 gogs won't start up with the following output and error:

gogs    | 2016/10/12 16:38:58 [T] Custom path: /data/gogs
gogs    | 2016/10/12 16:38:58 [T] Log path: /app/gogs/log
gogs    | 2016/10/12 16:38:58 [I] MAEH Gogs: Go Git Service 0.9.99.0915
gogs    | 2016/10/12 16:38:58 [I] Build Time: 2016-09-16 12:10:06 UTC
gogs    | 2016/10/12 16:38:58 [I] Build Git Hash:
gogs    | 2016/10/12 16:38:58 [I] Log Mode: File(Info)
gogs    | 2016/10/12 16:38:58 [I] Cache Service Enabled
gogs    | 2016/10/12 16:38:58 [I] Session Service Enabled
gogs    | 2016/10/12 16:38:58 [I] Migration: set comment updated with created
gogs    | 2016/10/12 16:38:59 [...s/routers/install.go:69 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: Sync2: no such index: IDX_comment_"idx_comment_IDX_comment_issue_id"

When looking at the database schema it looks like this:

sqlite> .schema comment
CREATE TABLE `comment` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT
,  `type` integer DEFAULT NULL
,  `poster_id` integer DEFAULT NULL
,  `issue_id` integer DEFAULT NULL
,  `commit_id` integer DEFAULT NULL
,  `line` integer DEFAULT NULL
,  `content` text
,  `created` datetime DEFAULT NULL
,  `commit_sha` varchar(40) DEFAULT NULL
,  `created_unix` integer DEFAULT NULL
, `updated_unix` INTEGER NULL);
CREATE INDEX "idx_comment_IDX_comment_issue_id" ON "comment" (`issue_id`);

So maybe this is some kind of spelling / quoting issue?

Going back to 0.9.71 fixes the issue and i can startup gogs normally.

Regards,
Andreas

**Comment by andreasfaerber** [comment]
Greetings,

for now I fixed the issue by dropping the above index:

DROP INDEX idx_comment_IDX_comment_issue_id;

Afterwards I was able to upgrade and run the newer gogs docker containers. Not sure if that was the proper way - however, my comments table was empty.

Regards,
Andreas

**Comment by termlimit** [comment]
I did the same as @andreasfaerber and gogs upgraded without issue.
