### ISSUE TITLE
Code comments doesn't render well in wiki

### ISSUE THREAD

**Issue by javydreamercsw** [gogits/gogs#3766]
- Gogs version (0.9.97.0901): 
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/javydreamercsw/test/wiki/Code-formatting)
  - [ ] No
  - [ ] Not relevant
- Log gist:

The comments just look out of place identation wise.

**Comment by bkcsoft** [comment]
I can't see the raw text for that one so I can't debug it. Could you push that file to the repo README so I can take a look? :) (or add user `bkc` as a collaborator so I can see for myself)

**Comment by Fastidious** [comment]
@bkcsoft this is 100% reproducible. Try it, it is not too hard.

**Comment by javydreamercsw** [comment]
This is the source:

```
/*****************************************
* Comment
*     
******************************************/

methodName(string param_1, string param_2, string param_3) {
```

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

Make sure to do a force refresh!
