### ISSUE TITLE
Wiki pages with # in title don't behave correctly

### ISSUE THREAD

**Issue by javydreamercsw** [gogits/gogs#3767]
- Gogs version (0.9.97.0901): 
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/javydreamercsw/test/wiki/C%23-Page)
  - [ ] No
  - [ ] Not relevant
- Log gist:

None of the actions (Edit, Delete, etc.) don't work and redirects to page list in some cases.

**Comment by jorgesumle** [comment]
> None of the actions (Edit, Delete, etc.) don't work and redirects to page list in some cases.

Happens the same for me with a ? in the title. I'm using NotABug.org.

The title is "How to announce a new release of the game?"

**Comment by javydreamercsw** [comment]
I guess those are url special characters, code just needs to escape them or prohibit them altogether.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by javydreamercsw** [comment]
Seems to work fine. Thanks a lot!

**Comment by Unknwon** [comment]
Thanks your confirmation!
