### ISSUE TITLE
SSH_KEYGEN_PATH not working

### ISSUE THREAD

**Issue by bang88** [gogits/gogs#3770]
- Gogs version (or commit ref): 
- Git version: 0.9.97.0901
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
  
  `exec: "ssh-keygen": executable file not found in %PATH%`
## Description

Due to some reasons I can not add `ssh-keygen` to system path(No system permission),after some search I found we can  config `SSH_KEYGEN_PATH` in `app.ini`  just like this:

``` ini
[server]
START_SSH_SERVER = true
DOMAIN          = git.xxx.com
HTTP_PORT       = 3100
ROOT_URL        = http://git.xxx.com/
DISABLE_SSH     = false
SSH_PORT        = 22
OFFLINE_MODE    = true
DISABLE_ROUTER_LOG = true
ENABLE_GZIP     = true
SSH_KEYGEN_PATH = C:/path/to/usr/bin/ssh-keygen.exe
```

I have tested this path is exist and its working as expected,It looks like `gogs` does not use the config path: 

https://github.com/gogits/gogs/blob/master/models/ssh_key.go#L373

**Comment by cccross** [comment]
I have the same problem.

**Comment by cccross** [comment]
Is it the fix as simple as use   setting.SSH.KeygenPath instead of  "ssh-keygen"?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
