### ISSUE TITLE
500 Error when viewing issues where one of the issue creators is deleted

### ISSUE THREAD

**Issue by uncled1023** [gogits/gogs#3771]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 
- Operating system: Windows Server 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] Can't validate account email on test (500 error)
- Log gist:

```
2016/10/14 16:43:43 [D] Session ID: 284669d5247d4d9a
2016/10/14 16:43:43 [D] CSRF Token: IdsbE30cAhz-LsSpmb-QBWIu4wk6MTQ3NjQ4ODYyMzQwMjAwODcwMA==
2016/10/14 16:43:43 [...outers/repo/issue.go:183 Issues()] [E] Issues: LoadAttributes [42]: user does not exist [uid: 1225, name: ]
2016/10/14 16:43:43 [D] Template: status/500
```
## Description

When viewing the issues for a repository, and one of the issues was created by a user that no longer exists, the page throws a 500 error.  

I delete users by using the Admin API.  It looks like it is not unlinking a user from issues they have created when the user is deleted.

**Comment by carli2** [comment]
Thanks. This issue explains why gogs is not working properly anymore.

Is there a workaround?

**Comment by mukaiu** [comment]
今天碰到此问题，手动删除对应用户的issue后，恢复正常

**Comment by Unknwon** [comment]
This is fixed in `master`.
