### ISSUE TITLE
Allow user to choose use built in SSH server at installation

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#3773]
I love gogs! I have moved from running in a VM to running it directly in windows. To save having to enter the username / password I use SSH to pull and push, however after installing, it took me a while to figure out how to enable the SSH server that I read Gogs has. I discovered I had to add another option to the ini config file which wasn't there before. 

`START_SSH_SERVER = true`

I think this SSH server start option should be added to the config file so one doesn't have to go away and search for it after installation - possibly with the default option of false.

**Comment by Unknwon** [comment]
I think the issue should be better described as allow user to choose use built in SSH server at installation.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
