### ISSUE TITLE
Add a batch file for Windows Users

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#3774]
Instead of opening git bash, then starting gogs (and instead of running as a service), a `bat` file in the main directory may be a nice simple way to start gogs when needed:

`start "" "%SYSTEMDRIVE%\Program Files (x86)\Git\bin\sh.exe" --login -i -c "gogs.exe web"`

Including this text renamed to `gogs.bat` would allow a windows user to double-click it and have gogs start without any direct console work.

**Comment by Unknwon** [comment]
Thanks for the advice! Feel free to send a PR to `scripts` directory :)

**Comment by ChangePlaces** [comment]
why close the issue if you want a pr?

**Comment by Unknwon** [comment]
But I don't like the idea, but it's up to you to send a PR.
