### ISSUE TITLE
Different icons used for "settings" makes usability difficult

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#3776]
I think Gogs should choose one icon for the "settings" icon and stick with it! It's currently using 
- a screwdriver and spanner on: http://localhost:3000/username/reponame/settings
  ![settings1](https://cloud.githubusercontent.com/assets/302031/19417902/558329fe-93b0-11e6-8798-cee8c87f1648.png)
- a cog on: http://localhost:3000/orgName by the name.
  ![settings2](https://cloud.githubusercontent.com/assets/302031/19417903/55895c34-93b0-11e6-851c-58f8e4e265cd.png)

I prefer the screwdriver one as it's black and easier to see than a grey icon. Please choose one and let's stick with it! It'll help users to detect the settings much easier

**Comment by Unknwon** [comment]
Thanks for your feedback!

But I think current icon fits the best for both cases. You can always change the `.tmpl` file to desired output.
