### ISSUE TITLE
Request for Bookmark feature

### ISSUE THREAD

**Issue by NgYueHong** [gogits/gogs#3778]
When there is a lot of repository hosted in Gogs, the "Explore" page list will become long and hard to find the wanted repository. It would be nice if Gogs has the feature like bookmark to enable user to bookmark the repository and it will appear on Dashboard to allow user easy access next time.

**Comment by ChangePlaces** [comment]
I usually pin tabs in my browser! But for now you could put bookmarks in your browser on your toolbar area

**Comment by andreynering** [comment]
Actually, Gogs already has a "bookmark" feature. You can bookmark a repo by starring it.

It's just missing a page where one can see/search the starred repos. A panel in the right of the dashboard page would be nice, too.

**Comment by Unknwon** [comment]
I think this is basically the same request as https://github.com/gogits/gogs/issues/2198.
