### ISSUE TITLE
LICENSES automatically creaeted from the new repository menu have a different layout from the original licenses

### ISSUE THREAD

**Issue by jorgesumle** [gogits/gogs#3783]
Opened originally in https://notabug.org/hp/gogs/issues/120

![com](https://cloud.githubusercontent.com/assets/14212780/19468834/d25ef66a-9518-11e6-8fa1-4e71c9dbbdc8.png)

**Comment by LefsFlarey** [comment]
Both licenses are valid, with the latter being limited to 80 characters width.

**Comment by jorgesumle** [comment]
But why doesn't gogs use the original license with the original layout? It's more readable and it's more conservative.

**Comment by LefsFlarey** [comment]
Actually, there are many reasons for this, one being that the 80-characters limit was originally designed for terminals. As such, the 80-characters width licenses exist today. 

In any case, if you don't like it, you are free to substitute them with your own in your `custom/` folder.

**Comment by blondeponytail** [comment]
@LefsFlarey I agree with @jorgesumle, and I also think it would be a better idea to use licenses with a fixed margin. They look better, and have a better formatting; moreover, they are the most popular format by far and pretty much any project uses this format of the license. I really don't understand why Gogs is using this non-formatted version by default.

> Actually, there are many reasons for this, one being that the 80-characters limit was originally designed for terminals. As such, the 80-characters width licenses exist today.

So, considering that most (sane) developers use terminals, it only makes sense to stick to the default version (and not long unformatted strings). Source code files with license headers also use fixed margins; you don't want to put the whole license in one line...

**Comment by LefsFlarey** [comment]
@blondeponytail As both licenses are similar, I actually am not agreeing or disagreeing with anyone. While the latter with the fixed margin looks better and has better formatting, the former makes copying easier, as newlines clearly dictate each new clauses. As to why Gogs is using this *formatted(actually, it is formatted, properly as clauses should be)*, you would have to ask @Unknwon.

Considering that most (sane) developers use terminals, which have word-wrap by default, both cases won't matter. Additionally, how often do you even look at your own LICENSE file?

**Comment by blondeponytail** [comment]
> Additionally, how often do you even look at your own LICENSE file?

To be honest this question is equally valid the other way around. That is, if you don't look at your own LICENSE file that often, you could as well stick with the default formatting instead of pushing the non formatted version.

**Comment by LefsFlarey** [comment]
Exactly, that's why I'm suggesting that no changes be made, as the end result won't change.

**Comment by jorgesumle** [comment]
> why I'm suggesting that no changes be made, as the end result won't change.

Then why don't we use the original licenses, just as the license writers created them? 

I'll reopen this issue. As I don't see an agreement and a reason why gogs should use a different formatting style as the original license. What about making a voting and a discussion and then decide? Github, Bitbucket... use the original licenses. There must be a strong reason why gogs uses a different formatting style. Otherwise, why alter the original license?

**Comment by LefsFlarey** [comment]
@jorgesumle 

> Then why don't we use the original licenses, just as the license writers created them?

If you actually look carefully, there **IS NO REASON** to downvote me because Gogs **IS ALREADY** using original licenses. The one you want, is the 80-character width version. Get that right. The original version **NEVER** had the 80-character width.

> What about making a voting and a discussion and then decide?

I have never disagreed, I just wanted to put it out there that its no longer the original license that was original created in 80-character width.

> Github, Bitbucket... use the original licenses.

No they do not. They used the 80-character width.

> There must be a strong reason why gogs uses a different formatting style.

Good point, you will have to ask @Unknwon for that but he has gone back to the inactive graveyards again.

>  Otherwise, why alter the original license?

It **is** the original license.

> As an end-user, I don't understand why should we bother the license readers making the licenses less readable, with the current formatting style they'll have to scroll right in some editors.

Actually, it is fully readable. Each new clause, is a new line, just like in your country's law book. I'm sure word-wrapping is not hard to enable.

> How can I do that in notabug.org?

Create the license at `custom/conf/license/{LICENSE_NAME}` according to `conf/license`.

**Comment by Unknwon** [comment]
Thanks for pointing out... actually I didn't notice that. I download from a hosting site (can't remember which exactly). You're free to make a PR to update all of them... but closing this as this is not really a bug or feature request.
