### ISSUE TITLE
Extremely slow commit page access

### ISSUE THREAD

**Issue by NgYueHong** [gogits/gogs#3784]
When I try to access commit page, it page is very slow and take about 4715ms to generate the page. Hope there is an option for us to reduce the number of commit displayed on the page to improve the load speed.

**Comment by LefsFlarey** [comment]
How many commits do you have?

**Comment by NgYueHong** [comment]
@LefsFlarey about 800+ commits.

**Comment by LefsFlarey** [comment]
Hm, I think there might be a problem with your setup, considering that listed commits are limited. Do you run any other sorts of stuff on the same machine as Gogs?

**Comment by Unknwon** [comment]
What page is your **commit page**?

**Comment by NgYueHong** [comment]
@Unknwon On the first page of commit listing page.  It would be great to have the option to control number of commit show on one page. This way we can change and reduce the number to make it faster.

**Comment by Unknwon** [comment]
>On the first page of commit listing page. It would be great to have the option to control number of commit show on one page. This way we can change and reduce the number to make it faster.

This is same request to https://github.com/gogits/gogs/issues/3965

And you did not answer my question...

**Comment by NgYueHong** [comment]
@Unknwon Erm.. My answer is on the first page of commit listing page. Or, you are asking for something different?

**Comment by Unknwon** [comment]
Oh OK... as mentioned by @LefsFlarey 800+ commits is not an issue at all. You need generally 10k+ commits in order to have noticeable slow page time on commits list page.

You can upload your repository to demo site and see how long it takes.

**Comment by NgYueHong** [comment]
@Unknwon I have just updated to the latest version. It seems to be much faster now and I notice that the pageSize is now limit to 30. I can easily change the pageSize number from the browser address bar. 

However, how can I change the pageSize default number via app.ini file? I want to make the number to be even smaller like 15 to make the commit list page load faster.

Thank you.

**Comment by Unknwon** [comment]
@NgYueHong sure, please file another issue for tracking it.

**Comment by NgYueHong** [comment]
@Unknwon I have created another issue here: #4230
