### ISSUE TITLE
Cannot update user via admin interface - email exists

### ISSUE THREAD

**Issue by kdoichinov** [gogits/gogs#3787]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.5 LTS (server)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (Couldn't understand how to login to the admin panel there, sorry)
  - [ ] Not relevant
- Log gist:
## Description

Error message at the top:
**Email address has already been used.**
...
Whenever I try to update a user's settings (for example "This account has permissions to import local repositories") in the admin panel, I get an error that the user's email already exists.

**Comment by Unknwon** [comment]
It's not a bug, it is telling you email is used (caused by a fixed bug allows register with used email). Please upgrade your Gogs.
