### ISSUE TITLE
Team with "New" in name caused go to the create page of team

### ISSUE THREAD

**Issue by robinshi007** [gogits/gogs#3789]
Server info:
- Gogs version (or commit ref):  v0.9.97
- Git version:  1.9.1
- Operating system:  ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io: I have no orgination right to set this.
  - [ ] Yes (provide example URL)
  - [x] No ( have no orgination right)
  - [ ] Not relevant
- Log gist:
## Description

step to reproduce:
1. login gogs site with admin account
2. create a new orgaziation.
3. create a new team in that organization with name "New"
4. go to detail page of the newly created team.

Actual result:
step 4 goes to the create page of team, not detail page of that team. this cause by the url "*/team/new"

**Comment by LefsFlarey** [comment]
Working on a fix right about now, thanks for reporting.

**Comment by Unknwon** [comment]
Name "new" is now reserved word for team name, so users won't mistakenly create a team with such name.
