### ISSUE TITLE
mailto link incorrectly parsed in MD (at least in preview)

### ISSUE THREAD

**Issue by pyhedgehog** [gogits/gogs#3790]
- Gogs version: 0.9.78.0815
- Git version: Not relevant (webui bug)
- Operating system: 4.4.17-boot2docker SMP x86_64 Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at try.gogs.io: https://try.gogs.io/pyhedgehog/markdown-mailto-bug/src/master/README.md
- Log gist: Not relevant.
## Description

Link with `mailto:` protocol should be copied literally, without expecting slashed to specify absolute URL.

[Link with mailto address](mailto:somebody@example.com) should refer to `mailto:somebody@example.com` instead of `/*user*/*project*/.../mailto:somebody@example.com` as it does here (in GitHub).

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
