### ISSUE TITLE
LDAP login with spaces in CN

### ISSUE THREAD

**Issue by Geoffry304** [gogits/gogs#3791]
Hello, 

I have a question is it possible with ldap to login with CN=  Geoffry Van den Eede
I get the following error when I try that.
Or is there another solution so I can login with the sAMAccountName attribute? I can't get that to work :(

2016/10/20 15:36:26 [T] LDAP will bind directly via UserDN template: CN=%s,OU=DVIT Users,DC=DVIT,DC=LOCAL
2016/10/20 15:36:26 [D] 'Geoffry Van den Eede' contains invalid DN characters. Aborting.
2016/10/20 15:36:26 [W] Failed to login 'Geoffry Van den Eede' via 'login': user does not exist [uid: 0, name: Geoffry Van den Eede]

Thanks already!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #3906, please help test on latest release or `master` branch.
