### ISSUE TITLE
TLS/OSCP Issues on gogs.io with Firefox

### ISSUE THREAD

**Issue by maxf130** [gogits/gogs#3793]
As per some previous issues ( #3613, #3606 ect.), there are problems with accessing [https://gogs.io](https://gogs.io) with firefox.  

For the time being one can turn of OSCP stapling to work around this, but it should be fixed.

**Comment by JonasT** [comment]
Yup, broken for me as well, and SSL labs confirms the problem again: https://www.ssllabs.com/ssltest/analyze.html?d=gogs.io (scroll down to "OSCP stapling" where it says: "Invalid  Failed to validate response")

**Comment by strk** [comment]
It's not the first time it happens, #3592 was probably the first occurrence (and might contain instructions to solve it too)

**Comment by JonasT** [comment]
@strk since ssllabs.com is showing this as well, this is most certainly a server problem and can only be solved by the administrators of gogs.io.

**Comment by LefsFlarey** [comment]
Yes and I believe that @Unknwon is the only one managing the server too, so nothing can be done about that.

**Comment by silverwind** [comment]
Yep, same issue as last time. Probably some remnant of the previous CA in the configuration. The gogs.io server is contacting the wrong CA (StartCom) for the OCSP data.

```sh
$ openssl s_client -connect gogs.io:443 -servername gogs.io -status 2&>1 < /dev/null | grep "OCSP Response Data" -A14
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = IL, O = StartCom Ltd., OU = Secure Digital Certificate Signing, CN = StartCom Class 1 Primary Intermediate Server CA OCSP Responder
    Produced At: Oct 23 00:29:16 2016 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 6568874F40750F016A3475625E1F5C93E5A26D58
      Issuer Key Hash: EB4234D098B0AB9FF41B6B08F7CC642EEF0E2C45
      Serial Number: 0693FC2B7F5872
    Cert Status: good
    This Update: Oct 23 00:29:16 2016 GMT
    Next Update: Oct 27 00:39:16 2016 GMT
```

**Comment by strk** [comment]
Yes, agreed it's a server problem

**Comment by RichieB2B** [comment]
I propose leaving Startcom to die on it's own and move to Let's Encrypt.

**Comment by strk** [comment]
+1 (but this bug is hardly Startcom fault)

**Comment by nylocx** [comment]
Is there a timeline when this issue will be fixed. I lately had a bad time advocating gogs in our team when half of the people couldn't even visit the website. ;)

**Comment by 0xbaadf00d** [comment]
gogs.io use Let's Encrypt SSL and Caddy server. I 'have exactly the same configuration on my own dedicated server. Maybe @Unknwon add non-default value on Caddy configuration file who break OCSP.

**Comment by silverwind** [comment]
Definitely sounds like a Caddy bug. Probably some bad cache. It's certainly not possible to misconfigure nginx alone in such a way.

**Comment by RichieB2B** [comment]
Perhaps the problem is that dl.gogs.io (which is hosted on the same server) still uses a StartCom certficate? https://www.ssllabs.com/ssltest/analyze.html?d=gogs.io vs https://www.ssllabs.com/ssltest/analyze.html?d=dl.gogs.io

**Comment by silverwind** [comment]
Ah, so it looks like dl.gogs.io is the default server and it may wrongly fall back to it for OCSP. The StartTLS certificate is going to expire in 8 days, btw.

**Comment by SchoolGuy** [comment]
This issue seems to be fixed and should be closed because I can now visit the site again with Firefox

**Comment by silverwind** [comment]
Yes, looking good right now. I wonder what was the issue.

````
$ openssl s_client -connect gogs.io:443 -servername gogs.io -status 2&>1 < /dev/null | grep "OCSP Response Data" -A14
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
    Produced At: Nov 11 03:10:00 2016 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 7EE66AE7729AB3FCF8A220646C16A12D6071085D
      Issuer Key Hash: A84A6A63047DDDBAE6D139B7A64565EFF3A8ECA1
      Serial Number: 036A5435B12431953B0045A6ED28988ECD63
    Cert Status: good
    This Update: Nov 11 03:00:00 2016 GMT
    Next Update: Nov 18 03:00:00 2016 GMT
````

**Comment by strk** [comment]
Confirmed, looks good.

**Comment by maxf130** [comment]
Working for me too.   Fixed as far as I'm concerned.
