### ISSUE TITLE
new version can't be installed on linux arm

### ISSUE THREAD

**Issue by chenjb1975** [gogits/gogs#3794]
The issue will be closed without any reasons if it does not satisfy any of following requirements:
1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

...
Can't install the 0.9.97 binary on Qnap hs-210 (linux arm v5). error message: "illegal instruction"
but 0.9.13 is ok!

**Comment by ChangePlaces** [comment]
"You MUST delete above content including this line before posting; too lazy to take this action considered invalid report."

**Comment by LefsFlarey** [comment]
Requesting for deletion 😆
