### ISSUE TITLE
Rewrite hooks from console

### ISSUE THREAD

**Issue by schneefux** [gogits/gogs#3796]
I am [packaging](https://github.com/NixOS/nixpkgs/pull/19361) Gogs for [NixOS](https://nixos.org/).
With every update of the Gogs package, the Gogs binary path changes so that it is necessary to rewrite all git hooks.
Can you provide a shell command, for example `gogs admin rewrite-hooks` so that this can be done automatically by NixOS?

**Comment by LefsFlarey** [comment]
I don't remember the binary path changing, is there a special way you are compiling it?

**Comment by Mic92** [comment]
@LefsFlarey on nixos, we store every package with the scheme `/nix/store/<hash>-<package>-<version>`. This way we resolve version conflicts between packages and can also rollback to older version.

**Comment by LefsFlarey** [comment]
I see, in that case, would a solution like symlinking it to a standard path regardless of versions solve it?

**Comment by Mic92** [comment]
As long as the old gogs service exists, the referenced binary should be not garbage-collected.
So it would sufficient to update gogs hooks, when the corresponding service is started/restarted. We could also solve this on our own using sed, I think.

**Comment by LefsFlarey** [comment]
I was thinking of more of having a python like structure, where all python version are symlinked to simpler executable names. There are, after all, no incompatibilities between Gogs versions and repositories.

Nevertheless, you guys do what you guys gotta do ^_^

**Comment by knedlsepp** [comment]
I've made a PR for this feature: https://github.com/gogits/gogs/pull/4813
