### ISSUE TITLE
Search does not include private repositories

### ISSUE THREAD

**Issue by pentix** [gogits/gogs#3798]
# Make private repositories accessible to the search function.
## Steps to reproduce
1. Create a public repo on try.gogs.io
2. Search try.gogs.io for the repo using the search bar
3. Repository is shown correctly
4. Create a private repo on try.gogs.io
5. Search for the repo using the search bar
6. "Couldn't find any repositories"
## System information

Could reproduce this on try.gogs.io (Gogs Version: 0.9.99.0915)

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/3947.
