### ISSUE TITLE
go get with sub directory failed

### ISSUE THREAD

**Issue by athurg** [gogits/gogs#3799]
For example:
user `xxx` have a golang library repo named `repotest`. it should be access at [https://https://try.gogs.io/xxx/repotest](https://https://try.gogs.io/xxx/repotest). and it has a sub directory named `sub1`.

You can import this repo by add `import "try.gogs.io/xxx/repotest"` in your golang source file (which will be fetched with command `go get try.gogs.io/xxx/repotest`).  Buf for the sub directory, if you import it by `import try.gogs.io/xxx/repotest/sub1` (also be fetched by `go get try.gogs.io/xxx/repotest/sub1`), it will be failed, with error noticed below:

> package try.gogs.io/xxx/repotest/sub1: unrecognized import path "try.gogs.io/xxx/repotest/sub1" (parse https://try.gogs.io/xxx/repotest/sub1?go-get=1: no go-import meta tags)

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/1878.
