### ISSUE TITLE
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lvyue** [gogits/gogs#3801]
/usr/local/go/src/runtime/panic.go:458 (0x42be33)
    gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:62 (0x42a98d)
    panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x440d34)
    sigpanic: panicmem()
/opt/go/src/github.com/gogits/gogs/models/login_source.go:491 (0x555419)
    ExternalUserLogin: if !source.IsActived {
/opt/go/src/github.com/gogits/gogs/models/login_source.go:549 (0x555a2d)
    UserSignIn: authUser, err := ExternalUserLogin(nil, username, passowrd, source, true)
/opt/go/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x87c813)
    SignInPost: u, err := models.UserSignIn(form.UserName, form.Password)
/usr/local/go/src/runtime/asm_amd64.s:480 (0x45bb0c)
    call64: CALLFN(·call64, 64)
/usr/local/go/src/reflect/value.go:434 (0x4ea308)
    Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4e9c24)
    Value.Call: return v.call("Call", in)
/opt/go/src/github.com/go-macaron/inject/inject.go:177 (0xaf1833)
    (_injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/opt/go/src/github.com/go-macaron/inject/inject.go:137 (0xaf11f2)
    (_injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x793902)
    (_Context).run: vals, err := c.Invoke(c.handler())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:104 (0x793826)
    (_Context).Next: c.run()
/opt/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/session/session.go:186 (0x6fe575)
    Sessioner.func1: ctx.Next()
/usr/local/go/src/runtime/asm_amd64.s:479 (0x45ba5c)
    call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:434 (0x4ea308)
    Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4e9c24)
    Value.Call: return v.call("Call", in)
/opt/go/src/github.com/go-macaron/inject/inject.go:177 (0xaf1833)
    (_injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/opt/go/src/github.com/go-macaron/inject/inject.go:137 (0xaf11f2)
    (_injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x793902)
    (_Context).run: vals, err := c.Invoke(c.handler())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:104 (0x793826)
    (_Context).Next: c.run()
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x7a693b)
    Recovery.func1: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:479 (0x45ba5c)
    call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:434 (0x4ea308)
    Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4e9c24)
    Value.Call: return v.call("Call", in)
/opt/go/src/github.com/go-macaron/inject/inject.go:177 (0xaf1833)
    (_injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/opt/go/src/github.com/go-macaron/inject/inject.go:137 (0xaf11f2)
    (_injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x793902)
    (_Context).run: vals, err := c.Invoke(c.handler())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:104 (0x793826)
    (_Context).Next: c.run()
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:43 (0x7a5b0e)
    Logger.func1: ctx.Next()
/usr/local/go/src/runtime/asm_amd64.s:479 (0x45ba5c)
    call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:434 (0x4ea308)
    Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4e9c24)
    Value.Call: return v.call("Call", in)
/opt/go/src/github.com/go-macaron/inject/inject.go:177 (0xaf1833)
    (_injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
/opt/go/src/github.com/go-macaron/inject/inject.go:137 (0xaf11f2)
    (_injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x793902)
    (_Context).run: vals, err := c.Invoke(c.handler())
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:184 (0x7a7ccc)
    (_Router).Handle.func1: c.run()
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:286 (0x79fe9e)
    (_Router).ServeHTTP: h(rw, req, p)
/opt/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x7981bb)
    (_Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:2202 (0x6b21ed)
    serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1579 (0x6aebf7)
    (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x45e5c1)
    goexit: BYTE    $0x90   // NOP
[Macaron] 2016-10-24 16:36:44: Completed /user/login 500 Internal Server Error in 22.555609ms

**Comment by alvaroaleman** [comment]
I am hitting the same issue as well. This is on a Server that worked fine for for about a month with Gogs v. 0.9.97, since today I can not login anymore. SSH pushes work fine.

I think this is pretty urgent as it makes Gogs unusable. I will gladly provide any further info needed.

Error log (hostname, session id and csrf token obfuscated by me):

```
Oct 29 16:53:59 obfuscated gogs[10000]: [Macaron] 2016-10-29 16:53:59: Started GET / for 127.0.0.1
Oct 29 16:53:59 obfuscated gogs[10000]: 2016/10/29 16:53:59 [D] Session ID: obfuscated
Oct 29 16:53:59 obfuscated gogs[10000]: 2016/10/29 16:53:59 [D] CSRF Token: obfuscated
Oct 29 16:53:59 obfuscated gogs[10000]: [Macaron] 2016-10-29 16:53:59: Completed / 302 Found in 1.048207ms
Oct 29 16:53:59 obfuscated gogs[10000]: [Macaron] 2016-10-29 16:53:59: Started GET /user/login for 127.0.0.1
Oct 29 16:53:59 obfuscated gogs[10000]: 2016/10/29 16:53:59 [D] Session ID: obfuscated
Oct 29 16:53:59 obfuscated gogs[10000]: 2016/10/29 16:53:59 [D] CSRF Token: obfusctated
Oct 29 16:53:59 obfuscated gogs[10000]: [Macaron] 2016-10-29 16:53:59: Completed /user/login 200 OK in 1.041805ms
Oct 29 16:53:59 obfuscated gogs[10000]: 2016/10/29 16:53:59 [D] Template: user/auth/signin
Oct 29 16:54:02 obfuscated gogs[10000]: [Macaron] 2016-10-29 16:54:02: Started POST /user/login for 127.0.0.1
Oct 29 16:54:02 obfuscated gogs[10000]: 2016/10/29 16:54:02 [D] Session ID: obfuscated
Oct 29 16:54:02 obfuscated gogs[10000]: 2016/10/29 16:54:02 [D] CSRF Token: obfuscated
Oct 29 16:54:02 obfuscated gogs[10000]: [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/panic.go:458 (0x434743)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/panic.go:62 (0x43329d)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:434 (0x4f6148)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
Oct 29 16:54:02 obfuscated gogs[10000]: /home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/net/http/server.go:2202 (0x70144d)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/net/http/server.go:1579 (0x6fde57)
Oct 29 16:54:02 obfuscated gogs[10000]: /usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
Oct 29 16:54:02 obfuscated gogs[10000]: [Macaron] 2016-10-29 16:54:02: Completed /user/login 500 Internal Server Error in 4.495268m
```

**Comment by 0xbaadf00d** [comment]
Do you have this issue on specific page(s) or on all pages ?

**Comment by alvaroaleman** [comment]
After login. The login page itself is displayed, after entering my
credentials and trying to log in , browser gets a http 500. Upon reloading,
I'm requested to login again.

**Comment by 0xbaadf00d** [comment]
Do you login using local account or something like SMTP or LDAP ?

**Comment by alvaroaleman** [comment]
Its a local account. Another thing I just noted: The session id is always
the same I would have expected Gogs to genereate one, thus not having the
same on two different attemps.

**Comment by alvaroaleman** [comment]
After looking in the DB; I realized I was using the wrong username. With the right one I can login use gogs.
If I use a wrong password on my existing user, I get the expected "Wrong usrename or password".

That does however not explain why Gogs throws a http 500 when using a non-existent user.

**Comment by 0xbaadf00d** [comment]
Have you try to upgrade to the last version available on `develop` branch ? Maybe this issue already fixed.

**Comment by alvaroaleman** [comment]
Issue is indeed gone when building gogs from
develop: 6bcff7828f117af8d51285ce3acba01a7e40a867

Thanks for your help!

**Comment by tumoxep** [comment]
Happened with me in `0.9.97` docker version when tried to push changes into freshly created repo. Fixed after switching to a `latest`
A repo was created in web ui by organization. User is a member of some of that organization's team which is set to have administrative access 

```
2016/12/14 07:21:29 [D] Session ID: 
2016/12/14 07:21:29 [D] CSRF Token: VG9wIEtlaw==
[Macaron] 2016-12-14 07:21:29: Completed <author/repo.git>/info/refs?service=git-receive-pack 401 Unauthorized in 2.175413ms
[Macaron] 2016-12-14 07:21:29: Started GET<author/repo.git>/info/refs?service=git-receive-pack for <docker-server-ip>
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/lib/go/src/runtime/panic.go:423 (0x433f79)
/usr/lib/go/src/runtime/panic.go:42 (0x432639)
/usr/lib/go/src/runtime/sigpanic_unix.go:24 (0x448f9a)
/tmp/go/src/github.com/gogits/gogs/models/login_source.go:491 (0x58f585)
/tmp/go/src/github.com/gogits/gogs/models/login_source.go:549 (0x58ff34)
/tmp/go/src/github.com/gogits/gogs/modules/auth/auth.go:129 (0x87b40a)
/tmp/go/src/github.com/gogits/gogs/modules/context/context.go:165 (0x8d69d8)
/usr/lib/go/src/runtime/asm_amd64.s:439 (0x465471)
/usr/lib/go/src/reflect/value.go:432 (0x50d07a)
/usr/lib/go/src/reflect/value.go:300 (0x50bd41)
/tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:117 (0xc189d2)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x854a47)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:104 (0x85492c)
/tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/session/session.go:186 (0x798494)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x46531e)
/usr/lib/go/src/reflect/value.go:432 (0x50d07a)
/usr/lib/go/src/reflect/value.go:300 (0x50bd41)
/tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:117 (0xc189d2)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x854a47)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:104 (0x85492c)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x86ac52)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x46531e)
/usr/lib/go/src/reflect/value.go:432 (0x50d07a)
/usr/lib/go/src/reflect/value.go:300 (0x50bd41)
/tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:117 (0xc189d2)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x854a47)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:104 (0x85492c)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:43 (0x8697cb)
/usr/lib/go/src/runtime/asm_amd64.s:437 (0x46531e)
/usr/lib/go/src/reflect/value.go:432 (0x50d07a)
/usr/lib/go/src/reflect/value.go:300 (0x50bd41)
/tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:117 (0xc189d2)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:113 (0x854a47)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:184 (0x86c5f4)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:286 (0x862b9d)
/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x85a09a)
/usr/lib/go/src/net/http/server.go:1862 (0x74f7ae)
/usr/lib/go/src/net/http/server.go:1361 (0x74cece)
/usr/lib/go/src/runtime/asm_amd64.s:1721 (0x467691)
[Macaron] 2016-12-14 07:21:29: Completed <author/repo.git>/info/refs?service=git-receive-pack 500 Internal Server Error in 1.625187ms
[Macaron] 2016-12-14 07:21:32: Started GET <author/repo.git>/info/refs?service=git-upload-pack for <docker-server-ip>
```

**Comment by alvaroaleman** [comment]
Please do not reap existing issues. As stated by @0xbaadf00d  and verified by me, this is fixed in current devel.

**Comment by unlucio** [comment]
I'm having the same error and I haven't even configured the server.
Jut launched the container and boom, the logs are full of this:

```
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:212 (0x6398b)
runtime/signal_unix.go:695 (0x63864)
xorm.io/xorm@v0.8.0/session.go:94 (0x57fe8c)
xorm.io/xorm@v0.8.0/engine.go:317 (0x56d67f)
xorm.io/xorm@v0.8.0/engine.go:328 (0x56d654)
gogs.io/gogs/internal/db/models.go:234 (0x9b3053)
github.com/go-macaron/toolbox@v0.0.0-20190813233741-94defb8383c6/healthcheck.go:69 (0xa577a7)
reflect/value.go:460 (0xdc88f)
reflect/value.go:321 (0xdc06f)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x39d4ab)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x39cf97)
gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x3c7a5f)
gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x3d7487)
gopkg.in/macaron.v1@v1.4.0/recovery.go:161 (0x3d7470)
gopkg.in/macaron.v1@v1.4.0/logger.go:40 (0x3cafa7)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x39d247)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x39d047)
gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x3c7a5f)
gopkg.in/macaron.v1@v1.4.0/router.go:187 (0x3d846f)
gopkg.in/macaron.v1@v1.4.0/router.go:294 (0x3d1f07)
gopkg.in/macaron.v1@v1.4.0/macaron.go:220 (0x3cc167)
net/http/server.go:2836 (0x347933)
net/http/server.go:1924 (0x343ef3)
runtime/asm_arm.s:857 (0x7dccf)
```

and in between each `[Macaron] PANIC` I've this line:

```
Dec 12 19:38:27 sshd[122]: error: kex_exchange_identification: Connection closed by remote host
```

Just keeps printing this every 30 secs.

What gives?

**Comment by unknwon** [comment]
@unlucio Looking at the stack trace combine with the "every 30 secs" observation, looks like something is hitting the health check endpoint (maybe Docker builtin health checking), and somewhere in the XORM is panicing.

But I wonder how is it related to not able to send emails... 🤔
