### ISSUE TITLE
Forks on Travis spams Gitter channel

### ISSUE THREAD

**Issue by LefsFlarey** [gogits/gogs#3803]
- Gogs version (or commit ref): 471431e87c223ff553c6df33ca8b01363bc6a06d onwards
- Git version: Not Relevant
- Operating system: Not Relevant
- Database (use `[x]`): Not Relevant
- Can you reproduce the bug at https://try.gogs.io: Not Relevant
- Log gist: Not Relevant
## Description

Gogs developers out there know how our dear friends Gogs, Travis and Gitter interact with one another, especially if Gogs happens to be on a fork. Commit `471431e87c223ff553c6df33ca8b01363bc6a06d` causes Gitter spam.

**Comment by Unknwon** [comment]
Hmm, thanks for the feedback but currently no good solution to that. And maybe we should report to those service providers.
