### ISSUE TITLE
reverse pull request creation

### ISSUE THREAD

**Issue by oouyang** [gogits/gogs#3805]
Currently, we can have pull request from forked repository.
But if we would like have reversed pull request, it's cannot.

For example, I forked a repository X from A to B.
And I have some changes in B/X and I can have pull request to A.
But if I have some changes in A/X and I cannot have pull request from A/X to B/X.

Hope you understand what I said.
- Gogs version (or commit ref):  0.9.99.0915
- Git version: 2.7.4
- Operating system: Mac OS 10.11
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

...

**Comment by oouyang** [comment]
Update version: Gogs version: 0.9.99.0915

**Comment by pyhedgehog** [comment]
According to help [article](https://help.github.com/articles/creating-a-pull-request/) this is possible on GitHub. Had anyone checked if this work?

**Comment by Dark-Passenger** [comment]
yes a reverse pull request is possible.

**Comment by Dark-Passenger** [comment]
just reverse the head and base fork. I think github even has a button for this.

**Comment by Unknwon** [comment]
I think this is basically same to https://github.com/gogits/gogs/issues/2770..
