### ISSUE TITLE
Problem with login when HTTPS is forced for sessions

### ISSUE THREAD

**Issue by carli2** [gogits/gogs#3810]
For all my clients it was confusing that when they use http for login but https is forced for sessions, login was not possible.

Gogs version:  © 2016 Gogs Version: 0.9.99.0903 on Ubuntu Linux, Apache Server, MySQL

Steps to reproduce:
- Set FORCE_HTTPS in session config (app.ini)
- Browse to login page with http
- Enter your credentials
- browser stucks in redir-URL

Expected behaviour:
- Login credentials shall be sent to https page when https is forced
- redirects shall redirect to https once you logged in when https is forced

**Comment by Unknwon** [comment]
I think it is the server proxy config responsibility to correctly redirect user from HTTP to HTTPS, not Gogs.
