### ISSUE TITLE
ARM build failed

### ISSUE THREAD

**Issue by cdpb** [gogits/gogs#3812]
related to #3794 

- Gogs version (or commit ref): 
**latest**
- Git version: 
**2.4.11**
- Operating system: 
**hypriot/rpi-alpine-scratch:v3.2 ( orginal Dockerfile.rpi )**
- Log gist:
**https://gist.github.com/cdpb/20f87ce8f9cdfc3a9d6b9b78809630e7**

Running from raspberry pi 3, raspbian jessie latest, docker 1.12.2

> [ERROR] Failed to set version on gopkg.in/macaron.v1 to 7564489a79f3f96b7ac8034652b35eeebb468eb4: exit status 128

Update: same error with **hypriot/rpi-alpine-scratch:v3.4**

**Comment by saboya** [comment]
This is fixed by #3727

**Comment by cdpb** [comment]
Thanks, waiting for merge ...
