### ISSUE TITLE
RSA2 fingerprint TYPE WARNING

### ISSUE THREAD

**Issue by kay54068** [gogits/gogs#3813]
請問我使用tortoisegit 會有以下警告:
...
![image](https://cloud.githubusercontent.com/assets/3054544/19715550/8413327a-9b88-11e6-9d6a-ce4db73266c6.png)

我匯入SSH Key 的格式都是...
![image](https://cloud.githubusercontent.com/assets/3054544/19715583/cbfc7db2-9b88-11e6-98f4-6bce16dbc8eb.png)

請問這個有解嗎?

**Comment by LefsFlarey** [comment]
> 1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).

**Comment by bkcsoft** [comment]
The server has another host-key, ask the administrator if it's been replaced. If yes, press "yes", otherwise you should press "no" and inform whomever is in charge of security.

Closing because it's not related to Gogs.
