### ISSUE TITLE
Dashboard only shows updates to first repo for each organization

### ISSUE THREAD

**Issue by IJeffray** [gogits/gogs#3817]
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 2.1.4
- Operating system: Debian 8.5 "Jessie"
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

I've several organizations, each with several repos.   All's working fine except the dashboard only shows commits to the FIRST repo for each organization.   This is a bit of a pain because it looks like no commits have happened in a team until I dig in to each individual repo view.  I consider this a bug, or at least a missed feature -- it's not obvious what was going on until we did some experimenting to notice that the first repo for each organization was always showing updates on the dashboard correctly.

This problem could NOT be readily replicated at try.gogs.io which is "interesting"

**Comment by Unknwon** [comment]
Hi, are you using the exact same way (e.g. SSH/HTTP) for all repositories of pushing commits?

>This problem could NOT be readily replicated at try.gogs.io which is "interesting"

Maybe you need to upgrade your Gogs.
