### ISSUE TITLE
Broken proxy page

### ISSUE THREAD

**Issue by gerroon** [gogits/gogs#3819]
Hi

I am trying to set it up with Apache proxy (based on FAQ). I can open http://url/git but the page is broken (like it is a simple html page) and apache error log has these. 

I am using it on Debian Wheezy, Apache/2.2.22 (Debian)

this is the relevant portion of the apache site file. It is under the standard web path. Basically I am  trying to serve it under my standard web server path. I am not sure if that is suported or not.

<Proxy *>
                 Order allow,deny
                 Allow from all
        </Proxy>

```
    ProxyPass /git http://127.0.0.1:3000/
    ProxyPassReverse /git http://127.0.0.1:3000/
    #ErrorLog ${APACHE_LOG_DIR}/error.log
```

Thu Oct 27 09:44:23 2016] [error] [client 192.168.10.111] File does not exist: /var/www/js
[Thu Oct 27 09:44:23 2016] [error] [client 192.168.10.111] File does not exist: /var/www/img
[Thu Oct 27 09:44:23 2016] [error] [client 192.168.10.111] File does not exist: /var/www/img
[Thu Oct 27 09:44:23 2016] [error] [client 192.168.10.111] File does not exist: /var/www/js
[Thu Oct 27 09:44:23 2016] [error] [client 192.168.10.111] File does not exist: /var/www/js

2016/10/27 09:47:17 [T] Custom path: /opt/gogs/custom
2016/10/27 09:47:17 [T] Log path: /opt/gogs/log
2016/10/27 09:47:17 [I] Gogs: Go Git Service 0.9.97.0901
2016/10/27 09:47:17 [I] Build Time: 2016-09-01 06:10:22 UTC
2016/10/27 09:47:17 [I] Build Git Hash: 8ee14db51ebc92728e1edba4545c7d4ea4b21c65
2016/10/27 09:47:17 [I] Log Mode: File(Info)
2016/10/27 09:47:17 [I] Cache Service Enabled
2016/10/27 09:47:17 [I] Session Service Enabled
2016/10/27 09:47:17 [I] Git Version: 1.7.10.4
2016/10/27 09:47:17 [T] Doing: CheckRepoStats
2016/10/27 09:47:17 [I] SQLite3 Supported
2016/10/27 09:47:17 [I] Run Mode: Production
2016/10/27 09:47:17 [I] Listen: http://0.0.0.0:3000

**Comment by strk** [comment]
Ad you tweaked `ROOT_URL` parameter under `[server]` section of `custom/conf/app.ini` to contain the `/git/` subpath ?

**Comment by Unknwon** [comment]
Maybe [this post](https://discuss.gogs.io/t/apache-sub-url-with-gogs/129) is helpful.
