### ISSUE TITLE
Can't login with SMTP authentication / no auto registration for remote users?

### ISSUE THREAD

**Issue by nurtext** [gogits/gogs#3824]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: nothing special
## Description

Gogs shows error 500 upon login (if user wasn't found), I guess this has been fixed in a recent commit (see issue #3612), but question remains: Why aren't remote users created automatically upon first login? I remember using an older version of Gogs when this was working fine. 

Btw:If I'm adding the user as an administrator, the user can login.

**Comment by joubertredrat** [comment]
Hi guys, 

Same issue here, if user already exists on base, login normal, but if doesn't exist user, get error on login.
```
[Macaron] 2016-11-01 14:42:07: Completed /user/login 500 Internal Server Error in 1.364496ms
```

**Comment by Unknwon** [comment]
I think this is a fixed issue in latest `master` branch.
