### ISSUE TITLE
Empty repo after push

### ISSUE THREAD

**Issue by gerroon** [gogits/gogs#3825]
Hi

This is what I did.

I created a new repo in Gogs. Then on my other computer created a new git init inside a folder. I added and commited my files. Then I added the origin remote. I pushed the files over ssh. I used standard ssh push path of the location of the repo (direct folder path on the server) as in I used git push origin master (server:/GOG_REPO_PATH/REPO.git is the remote origin in ./git/config)

The repo looks empty in Gogs but when I clone from it it gets all the files. So I am not sure why that is the case because I just followed these instructions when an empty repo initiated in the gui.

```
Create a new repository on the command line

touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin http://localhost:3000/user/REPO.git
git push -u origin master
```

I just used my custom full path to repo on the server when pushing it.

016/10/27 09:47:17 [T] Custom path: /opt/gogs/custom
2016/10/27 09:47:17 [T] Log path: /opt/gogs/log
2016/10/27 09:47:17 [I] Gogs: Go Git Service 0.9.97.0901
2016/10/27 09:47:17 [I] Build Time: 2016-09-01 06:10:22 UTC
2016/10/27 09:47:17 [I] Build Git Hash: 8ee14db
2016/10/27 09:47:17 [I] Log Mode: File(Info)
2016/10/27 09:47:17 [I] Cache Service Enabled
2016/10/27 09:47:17 [I] Session Service Enabled
2016/10/27 09:47:17 [I] Git Version: 1.7.10.4
2016/10/27 09:47:17 [T] Doing: CheckRepoStats
2016/10/27 09:47:17 [I] SQLite3 Supported
2016/10/27 09:47:17 [I] Run Mode: Production
2016/10/27 09:47:17 [I] Listen: http://0.0.0.0:3000

**Comment by gerroon** [comment]
I did more testing and here is the issue. I am not sure if this is a bug or by design thing.

If I do push the cloned repo at least once over the http then I can push files over ssh subsequently.

The weird thing is that none of the files were showing upin  Gogs as I outlined above, but once I pushed a single file over http url then the repo showed all the files etc like normal repo in Gogs.

**Comment by niknah** [comment]
I have this same problem but it doesn't go away with after a push via http.

gogs is not syncing with git.

Now in gogs I have my latest commit which was pushed via http.  But it's missing a lot of commits that were done via ssh.

How can I refresh gogs?

**Comment by gyppo** [comment]
I have a similar problem. I can create a new repo 'test' via the gogs web interface, then clone/push/pull to ssh://my.site:repos/user/test.git (the [repository] ROOT is /home/git/repos, this isn't reflected in the #repo-clone-url input). However, the web ui doesn't recognise any chages until the first push (of any branch) to http://my.site/user/test.git

I'm currently migrating by using the work-around of pushing to a new gogs repo over ssh, then pushing a dummy file to a dummy branch over http. Afterwards any ssh activity is recognised by the web ui.

Gogs Version: 0.9.99.0915 Go1.7.3

**Comment by Unknwon** [comment]
Because you did not config SSH correctly, please read https://discuss.gogs.io/t/how-to-config-ssh-settings/34.

**Comment by gerroon** [comment]
How do I know that I misconfigured the ssh server? My ssh server on thats server has been working fine for last 10 years. 

The issue is not the ssh, I push the files to the repo but gogs is not updating the hooks or whatever mechanism that it is using to update the repo. The repo in the web interface is not updated after a successful push.

If my ssh config was wrong I cannot push the files to the server in the first place.

**Comment by leogout** [comment]
Hi,
Same here, after a successfull push in ssh, I still have an empty gogs repo. The new directory have been created on my server but gogs doesn't seem to see it. After a push through http, the repo is displayed and ssh pushs works again.
@gerroon did found a way out of this ?

**Comment by gerroon** [comment]
@leogout I did not find a solution and I moved to gitblit project instead.

**Comment by mkrsn** [comment]
Problem still exist :/

I'll switch now to gitea...

**Comment by smaeul** [comment]
See my comment on https://github.com/go-gitea/gitea/issues/2898. In my case, `git` hooks weren't getting run because the filesystem was mounted `noexec`. Maybe it's the same issue, or helps you find yours.
