### ISSUE TITLE
Repos with capital letters are unreachable over ssh. Case sensitivity problem.

### ISSUE THREAD

**Issue by credomane** [gogits/gogs#3826]
Gogs Version [v0.9.97](https://github.com/gogits/gogs/releases/tag/v0.9.97)

1. Make a new org `TEST`
2. Make a new repo `TEST/tSt`  
 - gogs web interface says:  
`HTTP->http://yourserver:3000/TEST/tSt.git`  
`SSH-> git@yourserver:TEST/tSt.git`

3. Clone the repo 
 - over http `git clone http://yourserver:3000/TEST/tSt.git` will succeed.
 - over ssh `git clone git@yourserver:TEST/tSt.git` will fail [on a case-sensitive filesystem] with `fatal: Could not read from remote repository.`.

This issue stems from when creating a new repo it is forced to all lowercase letters when created on the filesystem (`test/tst.git`). However, the selection boxes in the web interface respect the original letter casing. This results in a mismatch and cloning subsequently failing over ssh. While the https cloning lowercases the requested repo path allowing the git clone to succeed.

The repo on the filesystem is `/home/git/gogs-repositories/test/tst.git` but I told gogs over ssh to look for `/home/git/gogs-repositories/TEST/tSt.git`.

Putting the text in the display boxes to lowercase or have the gogs ssh shell force the repo to lower case should solve the issue. About gave up on gogs and uninstalled it. This was a far bigger headache than I would have preferred my first 20 minutes with gogs experience to be.

**Comment by 0xbaadf00d** [comment]
What FS are you using @credomane ?

**Comment by credomane** [comment]
I was actually coming back to close this as I screwed up. I wasn't paying close enough attention and cloned repo twice over http twice. fail me. So I thought I have it figured out but nope.

My FS is ext4. My issue seems to be along the lines of this https://github.com/gogits/gogs/issues/1306
No matter what I do over ssh fails with `fatal: Could not read from remote repository.`

This is a fresh vm. I have two. One running gitlab which is working perfect out of the box other than being a complete resource hog. and the other running gogs which so far work far better than gitlab outside of ssh.

I'm bashing my head against the wall here. :(
