### ISSUE TITLE
Add a preview option to wiki pages

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#3828]
It'd be nice to be able to preview wiki pages with a 'preview' tab showing the rendered markup

**Comment by saboya** [comment]
Well, there is:

![preview](https://cloud.githubusercontent.com/assets/67044/19829496/1dd7f036-9dc2-11e6-80e6-a924e2d18b5c.png)

**Comment by Fastidious** [comment]
I would have missed that one too. Thanks @saboya!

**Comment by ChangePlaces** [comment]
that'd be it - thanks! though i'm going to forget what that button does in 6 months time! Is there some way it can be textual, or a button at the top (before "New Page") doing the same action?

**Comment by 0xbaadf00d** [comment]
I agree, text editor / user experience if not the same everywhere. Why not using the same editor used for the wiki page on Ticket and Release pages too ?
