### ISSUE TITLE
Increase commits listing page speed

### ISSUE THREAD

**Issue by 0xbaadf00d** [gogits/gogs#3830]
Commits listing page (eg : https://127.0.0.1:3000/torvalds/linux-kernel/commits/master) could be speed up by stopping to dump whole git repository commits at each page by using `--max-count` and `--skip` arguments with the command `git rev-list`.

Relative to #3818, Linux kernel repository count more than 600K commits and it could be nice to avoid dumping whole commits at each page if this is not necessary.

Or maybe cache usage could be a viable alternative to avoid running this command at each page (even if no modifications has been done on the repo)

**Comment by strk** [comment]
@0xbaadf00d was this addressed/fixed/migrated to gitea ?

**Comment by 0xbaadf00d** [comment]
@strk Yes Gitea is still concerned by this issue.

pro : this will significantly speed up Gitea
con: pagination will be replaced by "Next page" / "Previous page" (except if data are stored on DB)

**Comment by strk** [comment]
@0xbaadf00d would you add this PR to the gitea queue as well ?

**Comment by Unknwon** [comment]
Realize this is same as https://github.com/gogits/gogs/issues/3022.

**Comment by Unknwon** [comment]
Wrongly opened, the problem is https://github.com/gogits/gogs/issues/3518, Gogs calls this function every page which painful when repository is very large.
