### ISSUE TITLE
SQLite3数据库问题

### ISSUE THREAD

**Issue by cheukho** [gogits/gogs#3832]
使用Sqlite3作为数据库，在配置阶段注册了管理员，退出登录并重新登录都能正常。但，当将gogs作为服务启动后，web能打开，但管理员密码一直提示错误。

**Comment by cheukho** [comment]
最新定位出问题情况是：
在git用户下，cd到根目录，通过“/home/git/gogs/gogs web”方式启动是可以正常登录。

若，git用户cd到某一个非根目录，再通过“/home/git/gogs/gogs web”启动，web服务能访问站点，但用户登录就提示密码错误。

请问一下是不是git用户下的sqlite数据库路径有什么权限问题需要添加？

**Comment by stroucki** [comment]
In my case the permissions are:
```
git@cement:~/gogs/custom/hooks$ ls -ld ~/gogs
drwxr-xr-x 8 git git 4096 Oct 26 22:36 /home/git/gogs
git@cement:~/gogs/custom/hooks$ ls -ld ~/gogs/data/
drwxr-xr-x 4 git git 4096 Oct 31 11:44 /home/git/gogs/data/
git@cement:~/gogs/custom/hooks$ ls -ld ~/gogs/data/gogs.db
-rw-r--r-- 1 git git 401408 Oct 31 11:44 /home/git/gogs/data/gogs.db
```

**Comment by cheukho** [comment]
@stroucki I also found this problem，so i create user after i used service start gogs

**Comment by Unknwon** [comment]
Use absolute path for your database. See https://gogs.io/docs/intro/troubleshooting#connect-to-wrong-sqlite3-database
