### ISSUE TITLE
Missing support for short-hash archives download

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3834]
While short-hash are recognised by the commit browser, for example:

 *  https://try.gogs.io/strk/trac2gogs/commit/addbbc52

The same short reference doesn't work at fetching a tarball:

 * https://try.gogs.io/strk/trac2gogs/archive/addbbc52.tar.gz

While full hash does work:

 * https://try.gogs.io/strk/trac2gogs/archive/addbbc524c52f271c2542009bc947c8200b588a9.tar.gz

It would be nice if hashes recognition was consistent.

See how the first one was fixed in #3321

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
