### ISSUE TITLE
Merge between branchs created from master branch

### ISSUE THREAD

**Issue by carliandro** [gogits/gogs#3835]
- Gogs version (or commit ref):  0.9.83.0816
- Git version: 2.9.2
- Operating system: Windows Server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
When I try merge two branches created from master branch I receive error 500.
But if I try merge any branch with master branch it works fine.

**Comment by 0xbaadf00d** [comment]
Maybe duplicate of #3743 ?

**Comment by carliandro** [comment]
I did read and tried the solutions showed on issue but without success.

**Comment by carliandro** [comment]
Some solution for this?

**Comment by Unknwon** [comment]
>Log gist:

Why don't you post error logs from backend?...
