### ISSUE TITLE
Add a "Save Page" button at the top when editing wiki pages

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#3840]
Having the 'save page' button only at the bottom is annoying when you have to scroll down to it to save a page! Please can we have a "Save Page" button at the top next to the "New Page"?

**Comment by 0xbaadf00d** [comment]
Wiki is just normal git repository and we have to enter commit message before save modification.

I'm not sure is a good idea to duplicate "save" part of the form. It will overload the page. The default save button is accessible without scrolling even on small screen.

**Comment by Fastidious** [comment]
I agree with @0xbaadf00d.

**Comment by ChangePlaces** [comment]
I have to scroll on a laptop screen therefore it isn't accessible without scrolling. Duplicating the 'save' button is relatively simple and is a common feature on admin panels

**Comment by megadr01d** [comment]
Why scroll? Just press <kbd>End</kbd> / <kbd>Option + Down Arrow</kbd> on your keyboard.

**Comment by Unknwon** [comment]
I agree with @0xbaadf00d so closing this issue.

**Comment by Fastidious** [comment]
@megadr01d how did you create those buttons? https://github.com/gogits/gogs/issues/3840#issuecomment-275406566

**Comment by Unknwon** [comment]
@Fastidious 
![image](https://cloud.githubusercontent.com/assets/2946214/22351455/f6a4c6d2-e3e5-11e6-8f04-f7975cc83445.png)
