### ISSUE TITLE
Imcomplete anchors for non-latin headings in markdown

### ISSUE THREAD

**Issue by nook-ru** [gogits/gogs#3843]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: not relevant
- Operating system: 
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/nook_ru/test)
  - [ ] No
  - [ ] Not relevant
- Log gist: none

## Description

Each heading has an anchor pointing to it, i.e. https://try.gogs.io/nook_ru/test#test-heading

Unfortunately all non-latin characters are stripped from the heading anchor and replaced with minus sign. So, for example, for cyrillic heading *Еще один заголовок* anchor will look like `#--`. **GitHub** correctly deals with such headings, you can compare same markdown:

* [GitHub](https://gist.github.com/nook-ru/900f4c2d85b0b053f5b9618cd8439743) renders anchor as `#Еще-один-заголовок`
* [Gogs](https://try.gogs.io/nook_ru/test) gives `#--` for the same heading

**Comment by Unknwon** [comment]
This should be fixed by https://github.com/gogits/gogs/pull/3981.
