### ISSUE TITLE
Html font isometric width alignment

### ISSUE THREAD

**Issue by gonboy** [gogits/gogs#3847]
if I want to write some comment by English and Chinese in codes。（write ,md file）
I hope to align the comments.
example
```cpp
void main(void)  //程序开始    comment 1
{                          //主循环模式 comment  2
    while(1)          //启动循环    comment 3
   {
   }
}
```
When browsing the web，Comments 1,2,3 can not be aligned 
**If I can set the monospaced font just fine**

**Comment by 0xbaadf00d** [comment]
@gonboy Please, use english only on Github.

**Comment by Unknwon** [comment]
Actually... I have no idea what is going on here..
