### ISSUE TITLE
panic when login use a deleted user

### ISSUE THREAD

**Issue by UnderTreeTech** [gogits/gogs#3849]
first i delete a user,then a login with the deleted user info,it panic.
my gogs branch is v0.9.97.
here is the error tips:
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:458 (0x434743)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:62 (0x43329d)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
	sigpanic: panicmem()
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
/home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
/usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
	call64: CALLFN(·call64, 64)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
	Value.Call: return v.call("Call", in)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
	call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
	Value.Call: return v.call("Call", in)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
	call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
	Value.Call: return v.call("Call", in)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
	call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
	Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
	Value.Call: return v.call("Call", in)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
	goexit: BYTE	$0x90	// NOP
[Macaron] 2016-11-04 02:10:24: Completed /user/login 500 Internal Server Error in 8.359389ms

**Comment by briancappello** [comment]
I just did a fresh install of 0.9.97 and can confirm this bug. Whenever the given username does not exist, it blows up. Another related report/traceback in the discuss forums: https://discuss.gogs.io/t/500-response-on-wrong-password-after-data-migration/763

**Comment by alvaroaleman** [comment]
This got fixed in 7c1fbed05764ff27c0684df92961a030e2e3344b.

**Comment by briancappello** [comment]
Ah okay, that was a while ago. Any particular reason there hasn't been a binary release bump?

**Comment by Unknwon** [comment]
This is fixed issue in `master`.
