### ISSUE TITLE
Collaborative, private repositories are inaccessible from user desktop 

### ISSUE THREAD

**Issue by robaato** [gogits/gogs#3858]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: irrelevant
- Operating system: docker gogs/gogs:latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist:

## Description

If user was invited to participate in more than 15 collaborative repositories he cannot see some of them on his desktop, as no paging on the list is provided and no other means to look at the list of shared repositories exists. 
This situation happens when all of the collaborative repositories are private. They are also hidden on 'Explore' list even if user is a participant.

Access to invisible repositories is still possible by using a direct URL.

**Comment by Unknwon** [comment]
Considered duplicated to https://github.com/gogits/gogs/issues/3970 + https://github.com/gogits/gogs/issues/3947.
