### ISSUE TITLE
Bug: Web editor's breadcrumb path cuts parent dirs

### ISSUE THREAD

**Issue by megadr01d** [gogits/gogs#3859]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: Not sure (3rd party service - Teknik.io)
- Operating system: Windows Server 2016 Datacenter
- Database: SQL Server 2016
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
  - [x] MS SQL (According to [Teknik's Blog](https://blog.teknik.io/uncled1023/p/160))
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No but I can at [Teknik.io](https://git.teknik.io/dmz76/dotfiles)
  - [ ] Not relevant
- Log gist: None

## Description

When viewing a file in gogs, the breadcrumb path (next to **Branch: master**) works well. In the screencap below, I'm hovering the `openbox-3` dir and the status bar reflects this correctly as `/dotfiles/src/master/.themes/oomox-fray/openbox-3`.

![Screencap 1](https://git.teknik.io/dmz76/test/raw/master/view_path.png "view 1")

When editing a file, the breadcrumb path cuts all the parent dirs up to the hovered dir. Hovering `oomox-fray` leads to `/dotfiles/src/master/oomox-fray` when it should be `/dotfiles/src/master/**.themes**/oomox-fray`.

![Screencap 2](https://git.teknik.io/dmz76/test/raw/master/edit_path-1.png "edit 1")

Hovering `openbox-3` leads to `/dotfiles/src/master/openbox-3` when it should be `/dotfiles/src/master/**.themes/oomox-fray**/openbox-3`.

![Screencap 3](https://git.teknik.io/dmz76/test/raw/master/edit_path-2.png "edit 2")

This results in 404s.

**Comment by megadr01d** [comment]
Maybe related/duplicate of https://github.com/gogits/gogs/issues/3561.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by megadr01d** [comment]
Tested on https://try.gogs.io (Gogs 0.9.151.0216) and reporting to be working fine now. Thanks for the fix. :+1:
