### ISSUE TITLE
404 on not authorized access

### ISSUE THREAD

**Issue by targodan** [gogits/gogs#3862]
## Disclaimer

This is just a tiny bug for http pedants.
Feel free to put this at the lowest possible priority. :wink: 

## Information

- Gogs version: 0.9.97.0901
- Git version: git version 2.10.2
- Operating system: GNU/Linux - Debian 8 (Jessie)
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes [here](https://try.gogs.io/targodan/testrepo404/src/master/README.md)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When you open the URL to a file in a private repo while not being logged in, or being logged in with a user who doesn't have access, you get a 404 response.

## Expected

The RFC's [7235](https://tools.ietf.org/html/rfc7235#section-3.1) and [7231](https://tools.ietf.org/html/rfc7231#section-6.5.3) specify the behaviour in this case.

If you are *not* logged in a 401 should be returned, if you *are* logged in but don't have sufficient rights a 403 should be returned.

**Comment by 0xbaadf00d** [comment]
In some case. A 404 is legit to avoid resource existences leaking.

**Comment by targodan** [comment]
Yes, you are right... So the question comes down to is it more important to avoid resource existence leaking or to be http complient.

I can't answer this question.

**Comment by bkcsoft** [comment]
Leaking information is _never_ acceptable. GitHub, GitLab, BitBucket all have the same behavior as Gogs.

**Comment by targodan** [comment]
That is your oppinion, but all right. Upon opening this issue I just didn't know if this behaviour was intentional or not.

Guess I'll close this then.
