### ISSUE TITLE
Why you deleted gogs v0.8.43???

### ISSUE THREAD

**Issue by aibar** [gogits/gogs#3863]
Where can I download gogs v0.8.43 Docker image?

**Comment by ralphtheninja** [comment]
You can always build it yourself

```
git clone git@github.com:gogits/gogs.git
cd gogs
git checkout v0.8.43
docker build -t gogs:0.8.43 .
```

**Comment by aibar** [comment]
Not always.

Output of docker build -t gogs:0.8.43 .

    # github.com/gogits/gogs/models
    models/access.go:57: cannot use x (type *xorm.Engine) as type Engine in argument to accessLevel:
    	*xorm.Engine does not implement Engine (wrong type for Where method)
    		have Where(interface {}, ...interface {}) *xorm.Session
    		want Where(string, ...interface {}) *xorm.Session
    models/access.go:67: cannot use x (type *xorm.Engine) as type Engine in argument to hasAccess:
    	*xorm.Engine does not implement Engine (wrong type for Where method)
    		have Where(interface {}, ...interface {}) *xorm.Session
    		want Where(string, ...interface {}) *xorm.Session
    models/access.go:225: cannot use x (type *xorm.Engine) as type Engine in argument to r.recalculateAccesses:
    	*xorm.Engine does not implement Engine (wrong type for Where method)
    		have Where(interface {}, ...interface {}) *xorm.Session
    		want Where(string, ...interface {}) *xorm.Session
    models/action.go:198: cannot use x (type *xorm.Engine) as type Engine in argument to newRepoAction:
    	*xorm.Engine does not implement Engine (wrong type for Where method)
    		have Where(interface {}, ...interface {}) *xorm.Session
    		want Where(string, ...interface {}) *xorm.Session
    models/action.go:222: cannot use x (type *xorm.Engine) as type Engine in argument to renameRepoAction:
    	*xorm.Engine does not implement Engine (wrong type for Where method)
    		have Where(interface {}, ...interface {}) *xorm.Session
    		want Where(string, ...interface {}) *xorm.Session
    models/action.go:262: undefined: gogs.PayloadAuthor
    models/action.go:502: unknown gogs.PayloadUser field 'ID' in struct literal
    models/action.go:503: unknown gogs.PayloadUser field 'AvatarUrl' in struct literal
    models/action.go:512: unknown gogs.PushPayload field 'CompareUrl' in struct literal
    models/repo.go:411: undefined: gogs.PayloadRepo
    models/action.go:512: too many errors

**Comment by ralphtheninja** [comment]
Aah bummer :disappointed:

**Comment by aibar** [comment]
I assume that some dependencies updated and old gogs versions are now obsolete. If so, what a horrible dependency management in Go!

So, Switched to gitlab. I don't want to waste time on switching to gogs > 0.9 and error catching. 

Gogs 0.8.43 and drone 0.4 worked for me, not perfectly, but worked.
