### ISSUE TITLE
Unable to send mails

### ISSUE THREAD

**Issue by Nhoya** [gogits/gogs#3864]
- Gogs version (or commit ref): 0.9.97.0901
- Operating system:  Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
2016/11/07 16:24:08 [...les/mailer/mailer.go:201 processMailQueue()] [E] Fail to send emails [mymail@gmail.com]: UID: 7, registration notify - gomail: could not send email 1: dial tcp: lookup my.mailserver.com on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout
```
## Description
I'm unable to send mail (testing or register notify) any suggestions?

**Comment by strk** [comment]
You didn't set your mail server, loos like (`my.mailserver.com`)

**Comment by Nhoya** [comment]
The mailserver is running, the problem is actually gomail can't resolve the Domain Name. using the IP it's working perfectly but this should be fixed

**Comment by jeppech** [comment]
This might sound like some sort of an internal DNS issue? Have you tried resolving the hostname, from the machine that is running Gogs?

**Comment by Nhoya** [comment]
The problem is probably inside the gomail moduel, the machine can resolve without problems the dn

**Comment by Unknwon** [comment]
Does this issue still exist in the latest release of Gogs?
