### ISSUE TITLE
Undesirable plain text highlighting

### ISSUE THREAD

**Issue by megadr01d** [gogits/gogs#3865]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: Not sure (3rd party service - Teknik.io)
- Operating system: Windows Server 2016 Datacenter
- Database: SQL Server 2016
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
  - [x] MS SQL (According to [Teknik's Blog](https://blog.teknik.io/uncled1023/p/160))
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No but I can at [Teknik.io](https://git.teknik.io/dmz76/test)
  - [ ] Not relevant
- Log gist: None

## Description

According to [this](https://github.com/gogits/gogs/issues/2181) issue, is there any special reason to fix incorrect highlighting only on `LICENSE` files? This can't be right.
All files using the standard `.txt` extension or files without an extension (usually in all caps, but not necessarily) like `README, CHANGELOG, LICENSE, HISTORY, meta, todo` etc., should not be highlighted because they're readable plain text.

Some examples below.

[LICENSE](https://git.teknik.io/dmz76/test/src/master/LICENSE) - Not an actual LICENSE file, just renamed that way so no highlighting occurs
[LICENSE2](https://git.teknik.io/dmz76/test/src/master/LICENSE2) - A number added to `LICENSE` automatically highlights the text
[LICENSE.txt](https://git.teknik.io/dmz76/test/src/master/LICENSE.txt) - the standard `txt` extension automatically highlights the text

**Comment by Unknwon** [comment]
For the record, latest `develop` branch has disabled `.txt` but not able to handle `LICENSE{?}` yet.
