### ISSUE TITLE
Markdown, <br> question

### ISSUE THREAD

**Issue by gonboy** [gogits/gogs#3867]
You must add \<br\> to display line breaks。
If you do not add \<br\>, all lines are joined together

**Comment by Fastidious** [comment]
Where are you adding <br />? I mean, what exactly are you referring to, commits, wiki?

**Comment by danbetcher** [comment]
@gonboy In markdown you can end a line with a double space, which gets interpreted as a line break.

**Comment by Unknwon** [comment]
In standard markdown, you should do following to make a new line:

```
first line

second line
```

without using `<br>`
