### ISSUE TITLE
webhook for microsoft teams

### ISSUE THREAD

**Issue by LanceSandino** [gogits/gogs#3869]
Is there anyway to modify the slack webhook to work with microsoft teams? (or create our own?)

So far it works, shows like below:

[http://{repo-url}/{repo-name}|{repo-name}:{repo-url}/src/master|master] //{repo-url}/compare/{SHA1}...{SHA1}|1 new commit> pushed by {username}

It works, however the URLs aren't clickable, due to the  {repo-url}|{repo-name}  
the "|" is messing it up

**Comment by Unknwon** [comment]
The quick answer is no from... but you can write a HTTP middleware that transforms webhook from Gogs to whatever you need, that would be more generic solution I think. Life will be easier when Gogs support generic webhook template.
