### ISSUE TITLE
Log rotation malfunction

### ISSUE THREAD

**Issue by xjj59307** [gogits/gogs#3870]
- Gogs version (or commit ref): gogs_v0.9.97_linux_amd64
- Git version: 
- Operating system: CentOS release 6.3 (Final)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
Log rotation doesn't work correctly.
```
[hello@world logs]$ ls -l
total 160716
-rw-r----- 1 user group       152 Nov  9 11:00 gogs.log
-rw-r--r-- 1 user group  24769706 Nov  9 16:42 gogs.log.2016-11-04.001
-rw-r----- 1 user group       336 Nov  4 12:49 gogs.log.2016-11-05.001
-rw-r----- 1 user group      4294 Nov  5 06:26 gogs.log.2016-11-06.001
-rw-r----- 1 user group      2147 Nov  6 04:51 gogs.log.2016-11-07.001
-rw-r----- 1 user group      8508 Nov  7 17:57 gogs.log.2016-11-09.001
-rw-r----- 1 user group    293826 Nov  9 10:48 http.log
-rw-r----- 1 user group         0 Nov  4 11:23 update.log
-rw-r--r-- 1 user group 139482626 Nov  9 16:42 xorm.log
```

Obviously, logs are still written to gogs.log.2016-11-04.001.
Moreover, xorm.log and http.log aren't rotated.

I am using the default rotation config of [log].
```
[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = log_home
```

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/3413.
