### ISSUE TITLE
Can't create repository, Error 500

### ISSUE THREAD

**Issue by jcgruenhage** [gogits/gogs#3871]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: Don't know
- Operating system:
  - Fedora 24 (but in a Docker container) 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Creating a new repository doesn't work, it results in a Internal Server Error / 500 screen.
The username is jcgruenhage and it is from my LDAP container.  
The weird thing is, that I can reproduce it with that user only, others, be it from LDAP or internal, but with that user, it doesn't work at all.

Any ideas? I already deleted and recreated the account and removed it's folder from the gogs-repositories folder.

Edit:
If this should go under https://discuss.gogs.io/, then I'm sorry for putting this here, but I thought this is probably an issue.

Another edit:
This was a fresh container, no data in the mounted folder and an empty database.

**Comment by jcgruenhage** [comment]
Found a workaround, change the email address: The logs stated that the email address was already used, and I noticed that the email of the admin account was the same as the email of my user account, shouldn't that be no problem on a private repository, that the admin account has no access to anyway?

**Comment by focmb** [comment]
I have the same problem. But when the 500-Site is shown I go one site back (backspace) and the Repo was created

**Comment by jcgruenhage** [comment]
@focmb check your logs, since in my case, the repo was not created, this probably has a different cause.

**Comment by einacio** [comment]
I'm too having problems creating repos on version 0.9.100.1119

when creating a repo on a team, o trying to transfer a personal repo to the team, i got a 500 with this log
```
2016/12/14 13:18:57 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: addRepository: getMembers: get team-users: no such column: team_id
2016/12/14 13:19:24 [...ters/repo/setting.go:227 SettingsPost()] [E] TransferOwnership: add to owner team: getMembers: get team-users: no such column: team_id
```
I'm using sqlite, and going back to previous version 0.9.97 works fine

**Comment by Mikescher** [comment]
Same problem here
~~~
2016/12/15 08:51:04  [1;31m[...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: addRepository: getMembers: get team-users: Error 1054: Unknown column 'team_id' in 'where clause' [0m
2016/12/15 08:51:04  [1;34m[D] Template: status/500 [0m
[Macaron] 2016-12-15 08:51:04: Completed /repo/create 500 Internal Server Error in 21.67738ms
~~~
I can create personal repos but no Organization repos

Database MySQL
Gogs version (or commit ref): 0.9.100.1119
Git version: 1.9.1
Operating system: Ubuntu 14.04.5 LTS

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/3905
