### ISSUE TITLE
Unable to open gogs after stopping docker

### ISSUE THREAD

**Issue by francoism90** [gogits/gogs#3872]
- Gogs version (or commit ref):  Go Git Service 0.9.99.0915 (2016-09-16 12:10:06 UTC)
- Git version: 2.10.2
- Operating system: Arch Linux x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
```
[root@host archie]# cat /var/gogs/gogs/log/gogs.log 
2016/11/10 16:10:37 [I] Log Mode: File(Info)
2016/11/10 16:10:37 [I] Cache Service Enabled
2016/11/10 16:10:37 [I] Session Service Enabled
2016/11/10 16:10:37 [I] Git Version: 2.6.6
2016/11/10 16:10:37 [I] Git config user.name set to Gogs
2016/11/10 16:10:37 [I] Git config user.email set to gogs@fake.local
2016/11/10 16:10:37 [I] SQLite3 Supported
2016/11/10 16:10:37 [I] Run Mode: Production
2016/11/10 16:10:37 [I] First-time run install finished!
2016/11/10 16:10:37 [I] New random avatar created: 1
2016/11/10 16:11:17 [I] Log Mode: File(Info)
2016/11/10 16:11:17 [I] Cache Service Enabled
2016/11/10 16:11:17 [I] Session Service Enabled
2016/11/10 16:11:17 [I] Git Version: 2.6.6
2016/11/10 16:11:17 [I] SQLite3 Supported
2016/11/10 16:11:17 [I] Run Mode: Production
2016/11/10 16:11:17 [I] Listen: http://0.0.0.0:10080
```

## Description
Setup gogs using:
```# docker run -v /run/mysqld/mysqld.sock:/tmp/mysqld.sock --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs```
Stopping container:
```# docker stop gogs```
Starting again:
```# docker start gogs```
...
No interface is showing (Unable to open http://host:10080), however I'm able to execute commands:
```
# docker exec -ti gogs bash
bash-4.3# 
```

Update: Seems to be an issue with the MySQL socket, removing this part results in a working start/stop command. What would be a good solution to connect to a local MariaDB?

Thanks

**Comment by saboya** [comment]
map another port for MariaDB?

**Comment by francoism90** [comment]
@saboya unfortunately it didn't work. This issue happens after installing, and restarting the container. Don't know why, log seems to be OK.

Since I'm now running 'native' I'll close the issue, thanks for your reply. :)
