### ISSUE TITLE
...go-libravatar expects import "strk.kbt.io/projects/go/libravatar"

### ISSUE THREAD

**Issue by gencer** [gogits/gogs#3875]
```
$ ~/go/src/github.com/gogits/gogs
$ go build
```
**modules/setting/setting.go:24:2: code in directory /home/git/go/src/github.com/strk/go-libravatar expects import "strk.kbt.io/projects/go/libravatar"**

I also get this when i try to `go get -u...`

I am trying to install on Debian 8 x64 Psql with GoLang v1.6

Either Documentation nor google shows nothing on this.

Gencer.

**Comment by strk** [comment]
Try https://gitea.io (`go get code.gitea.io/gitea`) it's fixed there

**Comment by smcquay** [comment]
fixed in [pr 3876](https://github.com/gogits/gogs/pull/3876), but I'm wondering if I should update to gitea ... this happened a while ago the Unknwon was in school and then development came back here.

What's the story?

**Comment by strk** [comment]
gitea is already updated. The story is that there are a lot of contributors who'd like to see development moving forward and are feeling too limited with a single person being in charge of accepting them. This time development of contributors who moved to Gitea won't come back.

Gitea has a more distributed project management model, with 3 owners elected yearly and an open set of maintainers (currently 10) -- more info in https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md

**Comment by smcquay** [comment]
Thanks for the pointers. I've moved over.

**Comment by strk** [comment]
This would be fixed in Gogs by #3884

**Comment by tony** [comment]
@Unknwon my friend you have such a great project I'd appreciate if you could stay on top of this.

@strk is gitea compatible with the head/trunk of gogs? what's the scoop on migrating over?

**Comment by strk** [comment]
Yes gitea is compatible with "develop" branch of gogs.
Migrating over would give you some bugfixes (sorry no
file tracks them beside the git log).

Sending PRs would give you higher chances of them being
reviewed/merged, being there over 10 people with permission
to do that.

**Comment by Unknwon** [comment]
Fixed..
