### ISSUE TITLE
打开wiki报错 错误类型500

### ISSUE THREAD

**Issue by ofnhkb1** [gogits/gogs#3883]
Gogs 版本： 0.9.97.0901
系统类型及版本：win2008 r2 x64
数据库：mysql
问题描述：2016/11/15 13:49:17 [...routers/repo/wiki.go:54 renderWikiPage()] [E] GetBranchCommit: object does not exist [id: refs/heads/master, rel_path: ]
前台页面打开wik报错

**Comment by terrywh** [comment]
方便你先使用：在 仓库设置 中，先清空、关闭 wiki 然后重新启用，BUG 解决等作者 ...

**Comment by WebGameLinux** [comment]
![image](https://cloud.githubusercontent.com/assets/19490915/20476851/fc54045a-b00d-11e6-8390-28d94e2db90c.png)
我也一样,我centos2.6上也出现一样情况，求解决，
![image](https://cloud.githubusercontent.com/assets/19490915/20476981/9756fb7e-b00e-11e6-86c8-1f986bea9d8e.png)
