### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by zhusandiao** [gogits/gogs#3886]
OS：Centos 6

![2016-11-18_050443](https://cloud.githubusercontent.com/assets/5675934/20407601/04d29f24-ad4d-11e6-9044-603d1571765f.png)

then I chmod the gogs.log ，still have this problem.

**Comment by zhusandiao** [comment]
![gogs](https://cloud.githubusercontent.com/assets/5675934/20409692/82ae1740-ad55-11e6-92d2-0b1418a9addc.png)

**Comment by slava-vishnyakov** [comment]
Did you install git? 

`yum install -y git`

**Comment by zhusandiao** [comment]
I think I did install git.
