### ISSUE TITLE
Certificate expired 

### ISSUE THREAD

**Issue by ruedigerp** [gogits/gogs#3887]
Hi,

dl.gogs.io uses an invalid security certificate. 
The certificate expired on 10.11.2016 12:22. The current time is 18.11.2016 10:31. 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

cya

**Comment by cardonator** [comment]
Also, your CA is Startcom and they recently got blacklisted for issuing protected domains. I'd recommend switching to Let's Encrypt.
