### ISSUE TITLE
Mirror function stopped working on try.gogs.io

### ISSUE THREAD

**Issue by HelloZeroNet** [gogits/gogs#3888]
- Gogs version (or commit ref): 0.9.99.0915 
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

The sync is stopped working some weeks ago: https://try.gogs.io/ZeroNet/ZeroNet
It's mirrored from: https://github.com/HelloZeroNet/ZeroNet.git, it says Last Synced 2016-11-18 15:46:36 -0500 EST, but the last synced commit is 4 weeks old.

**Comment by Unknwon** [comment]
I think server was out of resources which leads fail to update the mirror, should be fixed by now.
