### ISSUE TITLE
Order feature on repos

### ISSUE THREAD

**Issue by axeloz** [gogits/gogs#3891]
A quick feature request : today repos are ordered by last modified date. I would be very useful to be able to order by name (and set this setting by default). 
Plus, following my previous issue #3890, my Explorer page being empty, the search engine does not return anything. I have now 40+ repos, I must browse page by page on the organisation landing page the repos list to find the one I want. 
Thanks

Axel

**Comment by PatrickWalker** [comment]
I'll take a look at this. 

I am guessing the hope is for a config point for the 3 different explore pages? So we can sort one by Name but maybe another by something else if that makes sense?

**Comment by axeloz** [comment]
Hello @PatrickWalker for your information, I have opened the same kind of thread on Gitea's repo : 
https://github.com/go-gitea/gitea/issues/207

Kind regards

**Comment by ErrolSayre** [comment]
Well, this is pretty close to mine #3949. I'll accept mine as a duplicate though I'd much rather have UI handle the sort selection than hardcoded in the config file.

**Comment by axeloz** [comment]
@ErrolSayre for sure. This feature request has been developed for Gitea and a pull request is pending merge on a future release.

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/3050.
