### ISSUE TITLE
How to increase the size allowed by the webserver 

### ISSUE THREAD

**Issue by flotho** [gogits/gogs#3894]
I would like to push a commit with a 60Mb file. The webserver is indicating that there is a limitation of 3Mb.
I'm looking for the way to setup the webserver to allow such a size.
This issue seems to have the same issue : https://github.com/gogits/gogs/issues/2982 but no obvious solution was proposed.
Any advice?

**Comment by jhasse** [comment]
Are you using nginx? If so, add

```
http {
    // ...
    client_max_body_size 500m;
}
```

to `/etc/nginx/nginx.conf`.

**Comment by Unknwon** [comment]
The answer is given..
