### ISSUE TITLE
Some gogs edited scripts contains CRLF line endings

### ISSUE THREAD

**Issue by lavvy** [gogits/gogs#3898]
i had been noticing this for a while but i didnt know what it was . but recently i found it again when building a docker image.
when you edit some scripts in gogs it kind of restructure the script which will be throwing error when building.
but if you edit that same script in github or gitlab it builds without error.

After a long searching , this stackoverflow question helped me track the bug
http://unix.stackexchange.com/questions/56024/bash-korn-shell-script-edited-on-windows-throws-error-m-not-found

i had to use " sed -i 's/\r$//' cxStopAllServicesOnSERVER.sh " to clean the script before building.
that works for one script, but am worried if there are many affected.

To reproduce 
clone this https://try.gogs.io/oganisa/CRLF_Edit_Bug
build the Dockerfile
then try to run the image , you will get an error
then try to enable the RUN sed command in the dockerfile , then the image will run without error

check my build below 

root@scw-9232fa:~/CRLF_Edit_Bug# ls
Dockerfile  README.md  run.sh
root@scw-9232fa:~/CRLF_Edit_Bug# docker build -t crlf-edit-bug .
Sending build context to Docker daemon 78.85 kB
Step 1 : FROM debian:jessie
 ---> 73e72bf822ca
Step 2 : ADD run.sh /run.sh
 ---> Using cache
 ---> 3dc339462713
Step 3 : RUN chmod 755 /*.sh
 ---> Using cache
 ---> c5da17f000fa
Step 4 : ENV PHP_UPLOAD_MAX_FILESIZE 10M
 ---> Using cache
 ---> 00a95fba3a19
Step 5 : ENV PHP_POST_MAX_SIZE 10M
 ---> Using cache
 ---> 4c20c22f8341
Step 6 : ENV SQLBUDDY_URL https://codeload.github.com/try/sqlbuddy/tar.gz/v1.0.0
 ---> Using cache
 ---> 1fb657f48442
Step 7 : ENV HTTP_DOCUMENTROOT /var/www/html
 ---> Using cache
 ---> ab2daac693b7
Step 8 : CMD /run.sh
 ---> Using cache
 ---> 24d8278529d6
Successfully built 24d8278529d6
root@scw-9232fa:~/CRLF_Edit_Bug# docker run -ti -d crlf-edit-bug
3a1daaf0b90e3839a5c05194e8e3b979a72b7337c9b88b1f60ff0c6f3a88872f
docker: Error response from daemon: Container command '/run.sh' not found or does not exist..
root@scw-9232fa:~/CRLF_Edit_Bug#

**Comment by lavvy** [comment]
@richmahn please can you try and reproduce this error and see if you can fix it please

**Comment by Unknwon** [comment]
Thanks for the feedback!

But I have no clue without knowing version info, and [this commit](https://github.com/gogits/gogs/commit/429c92c0ce15213e52fdacb3d28ee2f3a3a5a63f) seems fixed it.
