### ISSUE TITLE
gogs keep hanging in intranet environment.

### ISSUE THREAD

**Issue by kybin** [gogits/gogs#3899]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.6.4
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

gogs keep hanging in intranet environment.
It finds secure.gravatar.com for a long time.
Although I choose custom avatar.

**Comment by Unknwon** [comment]
You can turn on offline mode: https://github.com/gogits/gogs/blob/master/conf/app.ini#L122

**Comment by kybin** [comment]
Oh, OK. Thank you for letting me know!
