### ISSUE TITLE
The PR does not work very well.

### ISSUE THREAD

**Issue by xiaoshao** [gogits/gogs#3900]
Firstly, I send a PR which contains the conflicts to the repo. But after I fixed that, It still reminds me that the PR can't be merged because there is some conflict .

**Comment by SamboyCoding** [comment]
Oh come ON! That's not their issue! Take it to github themselves!

**Comment by xiaoshao** [comment]
I built a repo based on gogs.

**Comment by SamboyCoding** [comment]
Oh... sorry!
