### ISSUE TITLE
Unable to Disable Caching  (To Edit Template Files)

### ISSUE THREAD

**Issue by atom0s** [gogits/gogs#3902]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: git version 2.9.3.windows.1
- Operating system: Windows Server 2012 R2 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
N/A

## Description

I am trying to modify the templates for the overall look of some pages of Gogs, however with the caching of pages internally, it makes it annoying to modify things and check, as in active development. 

Setting the caching service information in the config file to anything does not appear to change how the pages caching is handled. Setting the interval to 0, 1 or even -1 does not work at all. I have to force reset the service anytime I make any changes to the template files.

Does Gogs have a setting for 'development mode' or something while editing template files?

Otherwise, can there be a setting to fully disable the caching so templates are loaded every page load for development purposes?

**Comment by georgesuba** [comment]
@atom0s hi, you should be able to modify those templates and re-upload them.. changes should be applied right a way after you restart your gogs service.. which is one command like 1 second to execute.

**Comment by atom0s** [comment]
I am trying to do this without having to restart the service after each edit.

**Comment by georgesuba** [comment]
@atom0s well... as I mentioned earlier restart gogs should take less then few milliseconds like 2 or 3? 

What you want to look in @ is - RUN_MODE in /conf/app.ini file. (For performance and other purposes, change this to prod when deployed to a production environment. The installation process will set this to prod automatically). Change this to **RUN_MODE = dev** 

Of course to apply changes you need to restart gogs service. After you're done you should change it back to **RUN_MODE = prod** and restart gogs service once again and you should be done.

Perhaps this is what you looking for?

**Comment by Unknwon** [comment]
@georgesuba has the answer.

**Comment by atom0s** [comment]
Sorry for the late response, been busy. Thanks @georgesuba changing to dev mode works perfectly for this.
