### ISSUE TITLE
Outdated highlight.js library 

### ISSUE THREAD

**Issue by furai** [gogits/gogs#3904]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/Furai/Delphi-tests/commit/3e50999fd3acdb4bf95f5fb91192b6e3240fb909)
  - [ ] No
  - [ ] Not relevant

Hey,

Gogs is currently using version 9.6.0 of highlight.js library. The current stable version of this lib is 9.8.0. I'm interested in it being updated because it has some fixes to Delphi syntax highlighting.

~~On top of that in the link above from try.gogs.io you can see that diffs for pascal files don't get proper syntax highlighting. The code class is `nohighlight`. I tried to figure out why it's happening but I couldn't.~~

~~Also, in  try.gogs.io you can't see that but in my locally deployed version of gogs any `*.pas` file is opened with `doxygene` syntax highlighting but here in try.gogs.io it worked as it should.~~ So I guess I'll try upgrading my local gogs version to the latest one and see if that fixes it.

EDIT: Scratch the problems with highlighting. I've added these to my `custom/conf/app.ini` file and it seems to have fixed the issues. Didn't notice that you could do that, only after investigating closer `highlight.go` file it gave me the idea.

> [highlight.mapping]
> .pas=delphi
> .lpr=delphi
> .inc=delphi
> .pp=delphi
> .dpr=delphi

Cheers,
Furai

**Comment by Unknwon** [comment]
Glad you solve the problem! Will update those libs after release.
