### ISSUE TITLE
500 on creating a new repo when an email has been used more than once

### ISSUE THREAD

**Issue by johnmcdowall** [gogits/gogs#3907]
- Gogs version (or commit ref): 0.9.100.1119
- Git version: 2.7.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
2016/11/25 21:17:42 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: updateUser: e-mail has been used [email: <snip>]
```

## Description

I invite a 2nd user with a different account name, but the same email as the Admin user via Admin > Users > Create New Account . It's then impossible to create new repos either under a user or organization. Either the UI should prevent registering accounts with the same email more than once, or such actions should be allowed. 

On https://try.gogs.io registering the same email twice results in a 500 when trying to activate the 2nd account.

**Comment by Unknwon** [comment]
Hi, I think this was a bug in Gogs (now fixed in `master`) that allows user register with same email.

To fix this, please edit email in admin panel and redo create new repository or other operations.
