### ISSUE TITLE
Not able to select branch to Pull Request when master is not the default branch

### ISSUE THREAD

**Issue by tthock** [gogits/gogs#3910]
- Gogs version (or commit ref): v0.9.97 @ 2016-09-01
- Git version: git version 2.7.4 (Apple Git-66)
- Operating system: MAC OS X
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/tthock/pullrequestbug/pulls)
  - [ ] No
  - [ ] Not relevant
- Log gist: 

When I set a default branch to something else other than **master**, I will not able to select the branch to perform pull request.

**Comment by Unknwon** [comment]
>I will not able to select the branch to perform pull request.

What does this mean exactly?

**Comment by edp** [comment]
I have the same issue : when master is not the default branch on the repository, the branch selector UI on the new pull request page does not appear. You cannot select a branch to merge from, and you can't create the pull request.

**Comment by tthock** [comment]
Previously the highlight section is not show for those project's default branch is not master. but latest release v0.9.113 @ 2016-12-24 had fix this issue. thanks. 

![Item](https://cloud.githubusercontent.com/assets/866351/21527447/60492ccc-cd66-11e6-8fa3-a3c2b18e51a5.png)
