### ISSUE TITLE
fail to serve RPC(upload-pack): exit status 128

### ISSUE THREAD

**Issue by gelim** [gogits/gogs#3914]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.5 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) **read description** (server DOS will occur)
  - [ ] No
  - [ ] Not relevant
- Logs:

2016/11/29 10:39:56 [...routers/repo/http.go:384 serviceRPC()] [E] fail to serve RPC(upload-pack): exit status 128

## Description

When cloning the (big) repo https://github.com/firehol/blocklist-ipsets and pushing to my local gogs instance (8GB RAM 4 CPU), I got a DOS when trying to render the repo (CPU are all spinning for some minutes) with final web timeout.
Watching the processes taking up all the CPU (they are continuously switching files):
```
git      19521  9.0  0.6 284340 49424 ?        R    10:54   0:00 git log -1 --pretty=format:%H 8abe9916a386b27434c5e8a72897dfb10bb5ca34 -- bambenek_cryptowall_ipdeny_country.json
git      19522  8.0  0.5 284332 43560 ?        R    10:54   0:00 git log -1 --pretty=format:%H 8abe9916a386b27434c5e8a72897dfb10bb5ca34 -- bambenek_cryptowall_retention.json
git      19523  0.0  0.3 284068 30628 ?        R    10:54   0:00 git log -1 --pretty=format:%H 8abe9916a386b27434c5e8a72897dfb10bb5ca34 -- bambenek_dircrypt.json
```
I did the same on https://try.gogs.io/gelim/blocklist-ipsets and it looks the same. **WARNING** if you access this URL your server/VM will have a hard time :-| 
NB: The new repo will properly appear in my main list: https://try.gogs.io/gelim/

```
$ git remote add test https://try.gogs.io/gelim/blocklist-ipsets.git
$ git push test
Username for 'https://try.gogs.io': gelim
Password for 'https://gelim@try.gogs.io': 
Counting objects: 314375, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4287/4287), done.
Writing objects: 100% (314375/314375), 363.89 MiB | 6.06 MiB/s, done.
Total 314375 (delta 310921), reused 313466 (delta 310012)
To https://try.gogs.io/gelim/blocklist-ipsets.git
 * [new branch]      gh-pages -> gh-pages
$
```

If you try to access directly one of the files, for instance README.md, it should be here:
https://try.gogs.io/gelim/blocklist-ipsets/src/master/README.md
you'll get a 404. Files haven't been unpacked in the repo.

Is it an upload limit? (NB: I push via SSH on my local gogs instance)

**Comment by Unknwon** [comment]
Please upgrade to latest release 0.9.113 and redo the test, you'll got more specific error message other than just `128`.
