### ISSUE TITLE
Hide unwanted licenses

### ISSUE THREAD

**Issue by dalareo** [gogits/gogs#3915]
- Gogs version (or commit ref): 0.9.99.0915
- Git version: 
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

How can i hide those unwanted licenses??
...

**Comment by Unknwon** [comment]
What is **unwanted licenses**?

**Comment by dalareo** [comment]
Those licenses that you don't want your users to choose. For example, suposing you just want the selector menu to let users choose from 3 or 4 types of licenses.

**Comment by Unknwon** [comment]
Thanks for clarifying!

**Comment by fredhampton** [comment]
Is it possible to hide unwanted licenses ?

**Comment by dalareo** [comment]
I just solved it leaving only desired licences under conf/licenses folder

**Comment by linquize** [comment]
Need to recompile gogs
1. Delete unwanted files in `conf/licenses`
2. run `go-bindata`
3. compile gogs `go build`

However, if all licenses are deleted, gogs will fail to start. Therefore, leave at least one license.
