### ISSUE TITLE
Crash when tabular spaces in title of wiki pages 

### ISSUE THREAD

**Issue by bentau** [gogits/gogs#3916]
- Gogs version (or commit ref): 0.9.71.0809
- Git version: 
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes  https://try.gogs.io/bentau/testwiki2/wiki/-test%26%239%3Btest
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The wiki seems to have problems with \t and  &#9; in the name. Either the wiki throws a 500 or it does not allow to delete pages.

**Comment by Unknwon** [comment]
Quick question, why would you need a tab in the title?

**Comment by bentau** [comment]
No one needs it but users do it and wonder why the kill they system

**Comment by Unknwon** [comment]
**kill they system**? I didn't see any crash.

**Comment by bentau** [comment]
then please have a look there 
https://try.gogs.io/bentau/testwiki2/wiki/_pages

**Comment by Unknwon** [comment]
Thanks for the link!

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io (the original repo was delete by last server cleaning process).
