### ISSUE TITLE
Wrong anchors for non-latin symbols in wiki pages

### ISSUE THREAD

**Issue by tetafro** [gogits/gogs#3919]
- Gogs version (or commit ref): 0.9.100.1119
- Git version: 2.6.6
- Operating system: Ubuntu 16.04 + Docker 1.12.3 + Alpine Linux 3.3 (inside container)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/tetafro/test/wiki/Home)
  - [ ] No
  - [ ] Not relevant
- Log gist: -

## Description

Wrong anchors for non-latin symbols in wiki pages: when head (starts with # symbols) contain non-latin symbols, like cyrillic for example, anchor link for this head will not contain any of these symbols.

**Comment by Unknwon** [comment]
This should be fixed by https://github.com/gogits/gogs/pull/3981.
