### ISSUE TITLE
Cannot create new Repository (for Organization) in latest gogs docker image

### ISSUE THREAD

**Issue by francoishill** [gogits/gogs#3920]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 0.9.100.1119
- Git version: 
- Operating system: CoreOS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description
It fails with internal server error (status code 500) when trying to create a new Repository for an Organization.
...

**Comment by VanCoding** [comment]
https://github.com/gogits/gogs/issues/3905

**Comment by Unknwon** [comment]
This is a fixed bug.
