### ISSUE TITLE
no such column: team_id

### ISSUE THREAD

**Issue by xiaocaimi** [gogits/gogs#3922]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

docker 最新版本创建组织。
在组织中创建仓库 500 错误
报错： [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: addRepository: getMembers: get team-users: no such column: team_id

使用0.9.97版本正常

**Comment by ohholly** [comment]
我也遇到一样的问题了额
2016/12/01 17:18:36 ^[[1;31m[...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: addRep
ository: getMembers: get team-users: Error 1054: Unknown column 'team_id' in 'where clause'^[[0m
2016/12/01 17:18:36 ^[[1;34m[D] Template: status/500^[[0m
[Macaron] 2016-12-01 17:18:36: Completed /repo/create 500 Internal Server Error in 17.813505ms

**Comment by Dolbager** [comment]
Gogs Version: 0.9.100.1119

Database: SQLite

routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: addRepository: getMembers: get team-users: no such column: team_id

**Comment by VanCoding** [comment]
I'm pretty sure this is the same bug as #3905

**Comment by Unknwon** [comment]
This is fixed in `master`.
