### ISSUE TITLE
How to get access to SSHd again once gogs was installed?

### ISSUE THREAD

**Issue by cookiengineer** [gogits/gogs#3924]
I cannot login into SSH anymore, because gogs is blocking SSHd authentication.

I know, I should've used another user. But it's not possible to revert the past, and it's time to fix it now in the future.

1. User Experience Level: -1. I did not expect to completely break my system when I install gogs. Why was there no BIG RED warning that hinted me that my SSHd will never work again?

2. I have access to the physical filesystem of the SD card. I cannot afford to install my OS from scratch, I want to recover it. I had no password for root and only one user that is now used by gogs, which is started by a systemd service. I cannot ssh into the system, because it had only one user and root has no password and the single user is the one that is "blocked" by gogs now.

3. How can I remove the authentication modifications that gogs did to my SSHd? How does it work and how to disable it, so I can go back into my system and login via SSH as before?

**Error message so people can google this issue later**:

```bash
ssh myuser@192.168.0.333; # or whatever...
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
```

**Comment by Mic92** [comment]
mount your sd card on a different machine and delete ~myuser/.ssh/authorized_keys.

**Comment by Unknwon** [comment]
Please read https://discuss.gogs.io/t/how-to-config-ssh-settings/34.
