### ISSUE TITLE
Completed /user/login 500 Internal Server Error 

### ISSUE THREAD

**Issue by J0hnson** [gogits/gogs#3926]
Gogs version (or commit ref): V0.9.97.0901 
Git version: 1.8.3.1
Operating system: CentOS Linux release 7.2.1511 64Bit
Database (use [x]):
 PostgreSQL
 MySQL
 [x]SQLite

If i config gogs authentication with LDAP,when i login with the domain account,there is an error"HTTP 500"

Log gist:

/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
**[Macaron] 2016-12-02 07:25:34: Completed /user/login 500 Internal Server Error in 27.944061ms**

**Comment by parryjacob** [comment]
I'm also encountering this problem with the same version. I'm using the most recent binary distribution (v0.9.97) on Ubuntu 16.04.1 x86_64 using MySQL.

Below is a more complete trace, I am going to install from source so I can see if I can fix the issue and potentially submit a PR.

```
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:458 (0x434743)
/usr/local/go/src/runtime/panic.go:62 (0x43329d)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
/home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
/usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
[Macaron] 2016-12-04 04:09:20: Completed /user/login 500 Internal Server Error in 19.25109ms
```

**Comment by parryjacob** [comment]
Running from the latest source on the `develop` branch (`baeccdb`) fixes this error for me, it may help you @J0hnson

**Comment by J0hnson** [comment]
@parryjacob  Thanks for your suggestion. I will try later. I install gogs in fabric8 on openshift platform, i need to create a new image for developing gogs.

**Comment by Unknwon** [comment]
This is fixed issue in `master`.
