### ISSUE TITLE
gogs should not stop if database is not available at startup

### ISSUE THREAD

**Issue by kakwa** [gogits/gogs#3927]
- Gogs version (or commit ref):  0.9.97
- Git version: 2.10.2
- Operating system: Debian Sid
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
https://gist.github.com/kakwa/e910bcdd7e44fb55783b3babd2bd0873

## Description

At startup, gogs will stop if the Database is unavailable.

This can be quite common if for one reason or another the database starts after the gogs process (for example, if it's on a different server).

It adds unnecessary ordering which can be hard to setup in a multi-node architecture, or unnecessary complexity by using a process watcher like supervisord. 

Gogs should ideally keep running and display something like a maintenance page or even a 500 error page.

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/2305.
