### ISSUE TITLE
Webhooks DELIVER_TIMEOUT issue

### ISSUE THREAD

**Issue by khromov** [gogits/gogs#3929]
Is it possible to increase webhook timeout? Some of my hooks take a long time to run (60-80 seconds) and I get an error message from Gogs:

```
Delivery: Post https://site.com/deploy-hook.php?project=22: read tcp 192.22.222.12:54480->198.166.140.82:443: i/o timeout
```

- Gogs version (or commit ref): 0.9.99.0903
- Git version: 1.7.1
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

**Comment by LeKovr** [comment]
You should look for DELIVER_TIMEOUT [here](https://gogs.io/docs/advanced/configuration_cheat_sheet)

**Comment by khromov** [comment]
@LeKovr Found it. However, there appears to be a bug that prevents the hook output from being saved if it takes a long time (30-60 seconds).

Here's what it looks like:

![2016-12-10 00_26_37-update webhook - gogs_ go git service](https://cloud.githubusercontent.com/assets/1207507/21068012/5710445c-be6f-11e6-9ffa-1e248a8e77ed.png)

Hooks that run within the default time do save a response correctly, but not long-running hooks.

**Comment by Unknwon** [comment]
When you say **long time**, does it time number still smaller than the timeout value?
