### ISSUE TITLE
Logging in with invalid user results in gzip file download

### ISSUE THREAD

**Issue by Dasoren** [gogits/gogs#3930]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

When logging in at https://git.aooki.link/user/login with a invalid username, aka a username not in the system, the user gets a gzip file that downloads onto their computer.
When I tried this at try.gogs.io I did not get this issue and it gave a proper response.

There is nothing in the gogs' logs, or in nginx's logs.

nginx git.access.log (log file for the nginx vhost file for gogs forwarding)
```
*.*.*.* - - [04/Dec/2016:01:09:45 -0500] "GET /user/login?redirect_to= HTTP/2.0" 200 2357 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
*.*.*.* - - [04/Dec/2016:01:09:51 -0500] "POST /user/login HTTP/2.0" 200 357 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
```
It does not matter the browser or computer it is tested on, it happens to all. If you put in the correct username there is no error message. Only when a username that is not in the system/database is used that you get this error.

If you need any other info, please let me know what to provide for testing or log files.
---
Edit 1
I am using standard authentication, no LDAP or SMTP, etc...

**Comment by Unknwon** [comment]
This is fixed issue in `master`.
