### ISSUE TITLE
Show server Git version on admin configuration page

### ISSUE THREAD

**Issue by danowar2k** [gogits/gogs#3934]
- Gogs version (or commit ref): 
Unknown (see https://github.com/gogits/gogs/issues/3933)
EDIT: It's gogs 0.9.100.1119.
- Git version: 
Unknown (hence this feature request)
- Operating system: 
(Client) Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
Unknown...
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
## Description
It would really help to let users report errors if the server git version would be displayed somewhere.
...

**Comment by Unknwon** [comment]
This is already been should on log output:

```
2017/01/22 05:55:59 [I] Build Git Hash: e8c3e9bcf87aa94497561e52e3cd5a15990a3037
2017/01/22 05:55:59 [I] Log Mode: File(Trace)
2017/01/22 05:55:59 [I] Cache Service Enabled
2017/01/22 05:55:59 [I] Session Service Enabled
2017/01/22 05:55:59 [I] Mail Service Enabled
2017/01/22 05:55:59 [I] Git Version: 2.11.0
```

**Comment by danowar2k** [comment]
Where can I access this log? I am only just a client using the provided server. I meant it would be really nice to be able to see it as a user/client using the web interface of the GOGS server.

I don't know if it is considered okay to reopen an issue myself, so I'll wait a bit...

**Comment by Unknwon** [comment]
Thanks for the clarifying.

**Comment by danowar2k** [comment]
Wait, would I as a simple user have access to the admin configuration page?

**Comment by Unknwon** [comment]
@danowar2k no you're not, and I don't think I would allow non-admin user knows what is the server git version on such server specific info.

**Comment by danowar2k** [comment]
Oh, so you want people that report bugs to go through their GOGS server admin because that is then the only way they would know the git version you request when filing a bug. Okay, I didn't know about that restriction.

**Comment by Unknwon** [comment]
If you're not admin to your Gogs instance, there is no way you could get log output, which means impossible to server related bugs.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
