### ISSUE TITLE
"New Pull Request" page does not always show branch selection boxes

### ISSUE THREAD

**Issue by danowar2k** [gogits/gogs#3935]
- Gogs version (or commit ref): 
Unknown (see https://github.com/gogits/gogs/issues/3933)
EDIT: It's gogs 0.9.100.1119
- Git version: 
Unknown (see https://github.com/gogits/gogs/issues/3934)
- Operating system: 
(Server) unknown
(Client) Windows 7, Firefox 50.0.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
Unknown
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
Unknown, I looked for existing repositories with multiple branches, but didn't know how to search explicitly for them. So I gave up after 9 pages.
## Description
We have a repository containing the Moodle files (https://moodle.org/) and ca. 26 branches.  Today I wanted to create a pull request. This automatically led me to /compare/develop...develop. This has worked normally in the past, but today the page said "Diff data not available." and, what's considerably worse, the buttons for selecting the branches didn't work. They were just plain green bootstrap (?) buttons, not selection boxes.
The only thing that's worked was manually changing the URL to /compare/develop...master . This provided me with the selection boxes for the branches. I tested with /compare/master...master, and the selection boxes were visible.
Only this particular comparison /compare/develop...develop yielded the green button error.
When I have more information (error logs, versions see above) I will post them here.

**Comment by cloudfoundation** [comment]
I met the same issue

**Comment by Unknwon** [comment]
Please open your Chrome web console and see if there is any errors during the reproduce operation.

**Comment by danowar2k** [comment]
I tried the Firefox console, only got CSS errors, no JavaScript. Do you need these?

I then tried with Chrome 55.0.2883.87, using the console I can open by "Weitere Tools->Entwicklertools->Console". No messages there. Reloaded the page a couple of times, still no messages.

By the way, comparing develop...develop yields "Diff Data Not Available.".

Comparing master...master yields "There is nothing to compare because base and head branches are even."
![gogs_compare_develop](https://cloud.githubusercontent.com/assets/10991509/21468889/0e0940c8-ca2d-11e6-87ca-5cedab0480d8.png)
![gogs_compare_master](https://cloud.githubusercontent.com/assets/10991509/21468890/0e0d530c-ca2d-11e6-9476-bb6aecd2b833.png)

**Comment by Unknwon** [comment]
Thanks for the info, but I have to close if there is no way to reproduce this.

**Comment by danowar2k** [comment]
Wait...How could I help? I can contact the GOGS admin here. I could let him activate some debug messages. What would you do if you'd look for the error if it was your personal server?

**Comment by Unknwon** [comment]
The easiest way is to reproduce the same issue on demo server (https://try.gogs.io)..

**Comment by danowar2k** [comment]
But I would have to upload my repository there, wouldn't I?

**Comment by Unknwon** [comment]
Basically yes.

For the screenshot you provide, there is indeed nothing could be compared between a branch and itself. So you're looking for something else here.

1. Upgrade to latest Gogs from source.
2. Provide steps how you got to the page in your screenshot.

**Comment by danowar2k** [comment]
Okay, I've decided to use try.gogs.io out, with a private repo for now.
But there's a problem:
I can't migrate/clone the repository from the our server to try.gogs.io because our server isn't visible on the internet. Do you know how I can clone my repo on try.gogs.io via git command line? I'm not that firm with git command line yet.

**Comment by Unknwon** [comment]
Maybe helpful: http://stackoverflow.com/questions/18200248/cloning-a-repo-from-someone-elses-github-and-pushing-it-to-a-repo-on-my-github

**Comment by danowar2k** [comment]
Ah okay, remotes. Didn't think about that. I had to create a new repo on try.gogs.io, but then I could push to that one. I guess there's no difference between that and trying to clone my repo on try.gogs.io . Just the direction.

**Comment by danowar2k** [comment]
Okay, I pushed my repo to try.gogs.io.
I then went to my repo: https://try.gogs.io/danowar/Moodle
Then to the pull request page: https://try.gogs.io/danowar/Moodle/pulls
Then I clicked on "New Pull Request": https://try.gogs.io/danowar/Moodle/compare/master...#377-Gruppen-aus-Gruppen

Then I get...a 404 ? What is up with that?

I added you as a read collaborator, btw.

**Comment by danowar2k** [comment]
Whoops I didn't push all branches...

**Comment by danowar2k** [comment]
Damn. I tried to reproduce the error on try.gogs.io and couldn't.
https://try.gogs.io/danowar/Moodle/compare/develop...develop
Then I looked at our server and couldn't reproduce the error there either...
Sometimes I just want to head->desk all day...

*sigh* Well, this can stay closed until the error pops up again and I reproduce it on try.gogs.io

**Comment by Unknwon** [comment]
OK... just a note try.gogs.io is for demo purpose, don't rely on that..

**Comment by nicle-lin** [comment]
这个issues关闭了吗？我也遇到楼主的问题，一模一样
