### ISSUE TITLE
Local connection to online server times out

### ISSUE THREAD

**Issue by CihanSari** [gogits/gogs#3937]
- Gogs version (or commit ref):  0.9.97.0901
- Git version: 2.9.3
- Operating system: Ubuntu Server 64-bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

A snapshot of console output when the error happened:

2016/12/06 05:00:16 [D] Session ID: f601d81b5b938b61
2016/12/06 05:00:16 [D] CSRF Token: LnLcB_rdDHjqmH8MkqD9aX7N6Mk6MTQ4MDk2MTU4ODE3MjUwMTcyNQ==
[Macaron] 2016-12-06 05:00:16: Completed /org/Resume/dashboard 200 OK in 6.254299ms
2016/12/06 05:00:16 [D] Template: user/dashboard/dashboard
2016/12/06 05:00:32 [T] Doing: MirrorUpdate
[Macaron] 2016-12-06 05:00:35: Started GET /org/Resume/dashboard for 127.0.0.1
2016/12/06 05:00:35 [D] Session ID: f601d81b5b938b61
2016/12/06 05:00:35 [D] CSRF Token: LnLcB_rdDHjqmH8MkqD9aX7N6Mk6MTQ4MDk2MTU4ODE3MjUwMTcyNQ==
[Macaron] 2016-12-06 05:00:35: Completed /org/Resume/dashboard 200 OK in 4.815514ms
2016/12/06 05:00:35 [D] Template: user/dashboard/dashboard
[Macaron] 2016-12-06 05:00:35: Started GET /avatars/1 for 127.0.0.1
[Macaron] [Static] Serving /1
[Macaron] 2016-12-06 05:00:35: Completed /avatars/1 206 Partial Content in 597.41µs
[Macaron] 2016-12-06 05:00:35: Started GET /js/jquery-1.11.3.min.js for 127.0.0.1
[Macaron] [Static] Serving /js/jquery-1.11.3.min.js
[Macaron] 2016-12-06 05:00:35: Completed /js/jquery-1.11.3.min.js 200 OK in 1.558077ms
[Macaron] 2016-12-06 05:00:35: Started GET /assets/font-awesome-4.6.3/css/font-awesome.min.css for 127.0.0.1
[Macaron] [Static] Serving /assets/font-awesome-4.6.3/css/font-awesome.min.css
[Macaron] 2016-12-06 05:00:35: Completed /assets/font-awesome-4.6.3/css/font-awesome.min.css 200 OK in 1.155843ms
[Macaron] 2016-12-06 05:00:35: Started GET /css/semantic-2.2.1.min.css for 127.0.0.1
[Macaron] [Static] Serving /css/semantic-2.2.1.min.css
[Macaron] 2016-12-06 05:00:35: Completed /css/semantic-2.2.1.min.css 200 OK in 2.233622ms
[Macaron] 2016-12-06 05:00:35: Started GET /assets/octicons-4.3.0/octicons.min.css for 127.0.0.1
[Macaron] [Static] Serving /assets/octicons-4.3.0/octicons.min.css
[Macaron] 2016-12-06 05:00:35: Completed /assets/octicons-4.3.0/octicons.min.css 200 OK in 317.571µs
[Macaron] 2016-12-06 05:00:35: Started GET /css/gogs.css?v=35d9ad1c4b8121ec642eac532699e94b for 127.0.0.1
[Macaron] [Static] Serving /css/gogs.css
[Macaron] 2016-12-06 05:00:35: Completed /css/gogs.css?v=35d9ad1c4b8121ec642eac532699e94b 200 OK in 1.903661ms
[Macaron] 2016-12-06 05:00:35: Started GET /js/libs/jquery.are-you-sure.js for 127.0.0.1
[Macaron] [Static] Serving /js/libs/jquery.are-you-sure.js
[Macaron] 2016-12-06 05:00:35: Completed /js/libs/jquery.are-you-sure.js 200 OK in 1.11763ms
[Macaron] 2016-12-06 05:00:35: Started GET /js/semantic-2.2.1.min.js for 127.0.0.1
[Macaron] [Static] Serving /js/semantic-2.2.1.min.js
[Macaron] 2016-12-06 05:00:35: Completed /js/semantic-2.2.1.min.js 200 OK in 1.115183ms
[Macaron] 2016-12-06 05:00:35: Started GET /js/gogs.js?v=35d9ad1c4b8121ec642eac532699e94b for 127.0.0.1
[Macaron] [Static] Serving /js/gogs.js
[Macaron] 2016-12-06 05:00:35: Completed /js/gogs.js?v=35d9ad1c4b8121ec642eac532699e94b 200 OK in 813.109µs
## Description
I have set up a server under cihansari.hopto.org/gogs. I am using nginx to forward /gogs/ traffic directly to port 3000: Listen: http://127.0.0.1:3000/gogs. Instructions on FAQ page is followed.

Access to gogs from outside (my mobile network / work network) is completely fine. I can browse / push / pull etc. However; I am having a huge issue on access from local area network. I _can't push anything, server hangs up. Web interface hangs for a long time (several seconds) and even then website is completely out of order!_

From another PC connected to same router:
![image](https://cloud.githubusercontent.com/assets/2743368/20926506/ec538598-bbbc-11e6-8aaa-318e2df50e7b.png)
From outside:
![image](https://cloud.githubusercontent.com/assets/2743368/20926512/f90736e0-bbbc-11e6-825c-298e01b9210b.png)

**Comment by CihanSari** [comment]
This sounds very much like:

> Error: extremely slow page response but time show on the bottom looks normal(under 100ms)
> Causes: it may be caused by Nginx try to resolve IPv4 address as IPv6.
> Solution: use explicit hostname 127.0.0.1 instead of localhost.

But my server address is already 127.0.0.1 and not localhost.

**Comment by ooxi** [comment]
This sounds much more like a DNS problem. How does `cihansari.hopto.org` resolve from inside your organization? It should resolve to the internal IP to avoid such trouble.

**Comment by CihanSari** [comment]
This is my playground at home. I get my router's global ip address when I ping from my Windows 10:

Pinging cihansari.hopto.org [77.177.56.102] with 32 bytes of data:
Reply from 77.177.56.102: bytes=32 time<1ms TTL=64

When I use any vpn / proxy, I have access to both the web interface and Git just fine (my current workaround).

> How does cihansari.hopto.org resolve from inside your organization? It should resolve to the internal IP to avoid such trouble.

Why does global ip address in contrast to internal, cause trouble ?

**Comment by ooxi** [comment]
> Why does global ip address in contrast to internal, cause trouble ?

This question is much better suited for [superuser](https://superuser.com/) :-)
