### ISSUE TITLE
很抱歉，我们无法验证您输入的 SSH 密钥

### ISSUE THREAD

**Issue by whlno1** [gogits/gogs#3940]
很抱歉，我们无法验证您输入的 SSH 密钥：SSHKeyGenParsePublicKey: fail to parse public key: exit status 1 -

后台-》账户设置-》管理 SSH 密钥。添加管理员公钥的时候报这个错，请问是啥问题。

**Comment by hhstore** [comment]
注意删除 SSH 密钥 字符串 末尾的 空白符(空格, 换行等).

**Comment by linux-mac** [comment]
末尾的空格和 @之类的字符不要就可以了
