### ISSUE TITLE
issue - gogs v0.9.97, huge memory leaks

### ISSUE THREAD

**Issue by hhstore** [gogits/gogs#3941]
# issue:

- I use docker deploy `gogs` for 8 weeks, it runs well.
- but just now i use `docker stats` cmd to check it, find huge memory leaks.
- my server has 96G mem, the `gogs docker container` eats `23G`.
- after i check `/var/gogs/git/gogs-repositories` size,   just `23G`.

# env:

- Operating System: `Ubuntu 14.04.5 LTS`
- Kernel Version: `3.19.0-25-generic`
- Total Memory: `94.35 GiB`
- Docker Server Version: `1.12.1`
- [gogs: 0.9.97 - dockerhub](https://hub.docker.com/r/gogs/gogs/)

# some screenshots:

- `/var/gogs/git/gogs-repositories` size: `23G` 

![image](https://cloud.githubusercontent.com/assets/3252130/21005738/f95ccc80-bd70-11e6-8209-b9aafe8eca5e.png)

- gogs docker container:
![image](https://cloud.githubusercontent.com/assets/3252130/21005389/9823bba0-bd6f-11e6-927b-db9a8c6612f5.png)

- `docker stats`, see memory leaks.
![image](https://cloud.githubusercontent.com/assets/3252130/21005395/9ee917dc-bd6f-11e6-90f6-cfd0cb4cb34d.png)

- after restart the gogs container:

![image](https://cloud.githubusercontent.com/assets/3252130/21005859/7df3a57c-bd71-11e6-88cb-0afe6c5d8ab7.png)

- diff gogs log:

![image](https://cloud.githubusercontent.com/assets/3252130/21005526/28e5e3d4-bd70-11e6-9bc7-92afe647887a.png)

**Comment by deanpcmad** [comment]
Odd, it looks like it's caching the repos in memory?

**Comment by Mic92** [comment]
The application does not really consume 22GB of RAM. `docker stats` is misleading because it also account disk cache, see http://www.linuxatemyram.com/

**Comment by hhstore** [comment]
@deanpcmad  
it looks like this.

@Mic92 
thanks, if so, I don't need to worry about it.
`Mac OS` also do the same thing.

**Comment by Mic92** [comment]
@hhstore go's memory usage can be also a bit misleading. It usually allocates a lot of virtual memory,
which don't not necessarily have to backed by physical. In this case you can check virtual vs resident memory.

**Comment by hhstore** [comment]
@Mic92  thanks a lot. I will check it.

**Comment by Unknwon** [comment]
Thanks for the report but I don't consider this is a bug from Gogs.
