### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by wangwei123** [gogits/gogs#3943]
GetTags: fork/exec /usr/bin/git: cannot allocate memory
handleCreateError()] [E] CreatePost: initRepository: InitRepository: fork/exec /usr/bin/git: cannot allocate memory

**Comment by Mic92** [comment]
Well, apparently your system has not enough memory.
So there is nothing gogs can do about it.
Sometimes it helps to enable memory overcommit in those cases.

**Comment by Unknwon** [comment]
Consider duplicated to https://github.com/gogits/gogs/issues/2464
