### ISSUE TITLE
往新的组织里新建仓库时报错

### ISSUE THREAD

**Issue by linux-mac** [gogits/gogs#3946]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL 5.7.16
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
打不开 **https://try.gogs.io**
- Log gist:

## Description

往新的组织里新建仓库时报错：

2016/12/11 08:25:00 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: addRepository: getMembers: get team-users: Error 1054: Unknown column 'team_id' in 'where clause'

**Comment by linux-mac** [comment]
使用docker部署的

**Comment by linux-mac** [comment]
试了下二进制的部署，没有这个问题，那还是用二进制的吧，等后面有精力看看问题出在哪里

**Comment by Lourens-Rich** [comment]
I don`t know what author wrote, but i have the same problem.

**Comment by palmtale** [comment]
@Lourens-Rich Well, the author said, it would happen only in docker env.
Although it occurred in my docker env, I don't think so. This should be an upgrading issue, if you back to 0.9.97, this issue would disappear.  

感觉好多人报这个issue哎，我感觉是做某功能时数所库新填了字段。因为我这边是从老版本直接变新版发现这个错的，退回0.9.97就不会有这错了。印象中看数据库，不管组织和用户都在user表里，估计在做这方面的区别 更新。
论坛Gogs discussion 里这个问题也炸成了锅，不过我到是希望先把discussion修复一下，我登录不上去，github授权不了，提示错，注册帐号发邮件成激活显示成功，但就是登录不上。

**Comment by jik1992** [comment]
我这里也是docker环境，创建组织无法新建仓库。。。

**Comment by cnzhangquan** [comment]
+1

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3905.
