### ISSUE TITLE
`CurrentUsername` is not always reliable

### ISSUE THREAD

**Issue by mgerner** [gogits/gogs#3948]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.1.4
- Operating system: Debian jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

The file `user.go` looks up the user that is running the `gogs` executable like so:
```
func CurrentUsername() string {
	curUserName := os.Getenv("USER")
	if len(curUserName) > 0 {
		return curUserName
	}

	return os.Getenv("USERNAME")
}
```

However, `$USER`, being a bash construct, is not always set properly, and as such it is not a very reliable way of determining the current user. https://unix.stackexchange.com/questions/76354/who-sets-user-and-username-environment-variables/76369#76369 suggests using `id -un` instead.

For example, `start-stop-daemon` doesn't update $USER when running a daemon under a more limited user than that which started it (`-c git` instructs `start-stop-daemon` to run the target as user `git`):

```
root@server:/opt/gogs# cat test.sh 
#!/bin/bash

echo '$USER:'
echo "$USER"

echo
echo 'id -un:'
echo `id -un`

echo 
echo 'whoami:'
echo `whoami`

echo
echo 'Running gogs...'
./gogs web

root@server:/opt/gogs# start-stop-daemon --start -u git -c git -d /opt/gogs/ --exec /opt/gogs/test.sh
$USER:
root

id -un:
git

whoami:
git

Running gogs...
2016/12/12 02:07:24 [...s/setting/setting.go:486 NewContext()] [E] Expect user 'git' but current user is: root
root@server:/opt/gogs# 
```

Note that in addition to not always being set, `$USER` can also be set by users themselves. So my solution for the time being is to, instead of running `gogs` directly, simply run a script that sets `$USER` to whatever it needs to be, and then runs `gogs` afterwards. This bypasses the user check completely. For example (for illustrative purposes -- I wouldn't actually run gogs as root of course):

```
root@server:/opt/gogs# ./gogs web
2016/12/12 02:12:28 [...s/setting/setting.go:486 NewContext()] [E] Expect user 'git' but current user is: root

root@server:/opt/gogs# export USER=git
root@server:/opt/gogs# ./gogs web
2016/12/12 02:11:46 [T] Custom path: /opt/gogs/custom
2016/12/12 02:11:46 [T] Log path: /var/log/gogs
2016/12/12 02:11:46 [I] xxx 0.9.97.0901
2016/12/12 02:11:46 [I] Log Mode: File(Info)
2016/12/12 02:11:46 [I] Cache Service Enabled
2016/12/12 02:11:46 [I] Session Service Enabled
2016/12/12 02:11:46 [I] Git Version: 2.1.4
2016/12/12 02:11:46 [I] Git config user.name set to Gogs
2016/12/12 02:11:46 [I] Git config user.email set to gogs@fake.local
2016/12/12 02:11:46 [I] SQLite3 Supported
2016/12/12 02:11:46 [I] Run Mode: Production
2016/12/12 02:11:46 [T] Doing: CheckRepoStats
2016/12/12 02:11:47 [I] Listen: http://127.0.0.1:3000
```

**Comment by Unknwon** [comment]
Thanks for the feedback!

It hurts nothing if the user decides to "bypass" the checking, it really doesn't matter. The main point to do this check is making sure Gogs is running under the "user" whatever user expects.

So I don't consider this is an issue at all.

**Comment by jjakob** [comment]
I am experiencing this issue when using the gogs/gogs Docker image.

Steps to reproduce:

Using docker-compose run:
```
root@dev:/docker/gogs# docker-compose run --rm -u git --entrypoint "" gogs /app/gogs/gogs backup -v --target /data/dump/
2018/05/24 14:22:06 [FATAL] [...g/setting/setting.go:577 NewContext()] Expect user 'git' but current user is: 
```
Using docker-compose exec:
```
root@dev:/docker/gogs# docker-compose exec -u git gogs bash
bash-4.3$ echo $USER

bash-4.3$ whoami
git
bash-4.3$ /app/gogs/gogs backup -v --target /data/dump/
2018/05/24 14:27:07 [FATAL] [...g/setting/setting.go:577 NewContext()] Expect user 'git' but current user is: 
bash-4.3$ 
bash-4.3$ export USER=git
bash-4.3$ /app/gogs/gogs backup --target /data/dump/
2018/05/24 14:29:12 [ INFO] Backup root directory: /tmp/gogs-backup-896015789
2018/05/24 14:29:12 [ INFO] Packing backup files to: /data/dump/gogs-backup-20180524142912.zip
2018/05/24 14:29:12 [ INFO] Dumping repositories in '/data/git/gogs-repositories'
2018/05/24 14:29:20 [ INFO] Repositories dumped to: /tmp/gogs-backup-896015789/repositories.zip
2018/05/24 14:29:28 [ INFO] Backup succeed! Archive is located at: /data/dump/gogs-backup-20180524142912.zip
bash-4.3$
```
Using docker run/exec instead of docker-compose would yield the same results, I'm only using compose because of convenience (already having a running gogs container).

Since the official gogs image works, I'm assuming it uses a wrapper script that sets $USER, however, this is not possible when using docker run or exec, as you are invoking the process directly without invoking a shell. Even in the exec case, when we do first invoke bash, no profile file is sourced as that's not bash's default behavior.

So IMO this is best fixed in the binary itself, as opposed to in the docker image, as it would fix most use cases automatically (where there would otherwise be the need for something, f.e. a wrapper script to set $USER beforehand).

**Comment by Unknwon** [comment]
@jjakob this check is on purpose to make your life harder to let you confirm the user you're trying to run the Gogs.
