### ISSUE TITLE
Release-Source-Tarball for Distributionmaintainer

### ISSUE THREAD

**Issue by Mic92** [gogits/gogs#3955]
## Description
Hi, I am working on integration into [Nixos](https://nixos.org/) - https://github.com/NixOS/nixpkgs/pull/19361
It would a nice addition, if in addition to binaries also the source code including `vendor/` would be attached to a release to get reproducible builds (in case other repositories changes). I did not spot release scripts in your repository, otherwise I would have added a line like:

```bash
tar cfz gogs-${VERSION}.src.tar.gz --exclude .git .
```

Thanks

**Comment by Unknwon** [comment]
Thanks for the advice, will do starting next release!

**Comment by Unknwon** [comment]
Now you can download source code of release along with its vendor at https://github.com/gogits/gogs/releases/tag/v0.9.128.

**Comment by Mic92** [comment]
@Unknwon thanks!

**Comment by Mic92** [comment]
this might be interesting for you as well: @schneefux

**Comment by Unknwon** [comment]
Starting next release, the source code is checked in Git, so all you need to do it clone the repo!
