### ISSUE TITLE
discuss.gogs.io is broken

### ISSUE THREAD

**Issue by devployment** [gogits/gogs#3956]
Seems like the signupis broken. Login via Github does not work. After authorizing the app the following message shows

```
Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?
```

Checking Github the application shows up and is approved.

If try to activate the account created by email the following shows after "Click here to activate you account" is clicked.

```
['BAD CSRF']
```

**Comment by pjt33** [comment]
I tried creating an account. The page `/users/account-created` gave the error message:

> We cannot detect if your account was created, please ensure you have cookies enabled.

I do have cookies enabled: I can see Google tracking cookies being sent in my requests to `discuss.gogs.io`. So it seems that the server is failing to set its own session cookie.

When I click on the confirmation link sent to my e-mail, the `activate-account` page says

> Welcome to Gogs Discussion!
>
> Click here to activate your account

But when I "click here" I get the same

> ['BAD CSRF']

error as @devployment.

**Comment by Unknwon** [comment]
Hmm.. should work now!
