### ISSUE TITLE
Deal with '/' in Wiki page title

### ISSUE THREAD

**Issue by aurabindo** [gogits/gogs#3958]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

- Gogs version (or commit ref): 0.9.97-1472903388.491
- Git version: 2.10.2
- Operating system: Debian 8
- Can you reproduce the bug at https://try.gogs.io: Yes

## Description

I know the support for hierarchical wiki is cooking, but if I try to create a new wiki page with title 'A/B', website throws a 404. I think its a good idea to check for `/` in the wiki title name before POST.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4153, please help test on `develop` branch or https://try.gogs.io.

**Comment by Unknwon** [comment]
Since Gogs doesn't support wiki hierarchy, the PR handles the `/` chars so user can redirect correctly.
