### ISSUE TITLE
[Vulnerabilities] Ability to delete other people's secondary emails and application's tokens

### ISSUE THREAD

**Issue by jimen0** [gogits/gogs#3959]
> I reported both them to u[at]gogs[dot]io on 3rd November 2016 and I've had no response until today. I also sent an email asking for updates on 30th November 2016, also, no response to it. I tested both vulnerabilities today and they remain unfixed.

- Gogs version (or commit ref):  0.9.99.0915
- Git version: the one that your [demo site](https://try.gogs.io/) uses as of 14th Dec 2016
- Operating system: same as above answer
- Database: same as above answer
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): URL not relevant
  - [ ] No
  - [ ] Not relevant
- Log gist:

# Description

## First vulnerability: delete other people's application's tokens

I found that I'm able to delete other user's `Manage Personal Access Tokens`.

### To reproduce this vulnerability, please, follow this steps:
1. Create an account for attacker, let's call this account userA.
2. Create an account for victim, let's call this account userB.
3. Activate them both.
4. Login to userA and create a `Manage Personal Access` token via `https://try.gogs.io/user/settings/applications`. For example name it: testReport.
5. Login to userB and create a `Manage Personal Access` token via `https://try.gogs.io/user/settings/applications`. For example name it: thisWillBeDeletedByAttacker.
6. Now, once it has been created, turn on any http traffic proxy with the ability to intercept traffic (Burp Suite was my choice).
7. Enable the proxy and then, delete the token you created in step 4. (the userA's token)
8. Now the request will look like: (see below)
9. Modify the `id` parameter and put the userB's token ID. But... you do not know it, right? See that it is a numeric ID, we could bruteforce it (Burp's intruder or simple python script), Let's assume we know it.
NOTE: to get the victim's id, go to userB's applications settings and view-source, you will see a line like this: `<button class="ui red tiny button delete-button" data-url="/user/settings/applications/delete" data-id="OUR-ID-IS HERE">`, in my test, the ID is `237`.
10. Put that ID in the request and forward it.
11. The userB's application token was removed.
12. Profit (?)
```
POST /user/settings/applications/delete HTTP/1.1
Host: try.gogs.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 73
Cookie: lang=en-US; i_like_gogits=2887387054a1bd79; _csrf=53ODw8PhHy4nWMHy5N5AwJ6F26s6MTQ3ODEzNDQ0NTk0NDM3MjE0Ng%3D%3D
DNT: 1
Connection: close

_csrf=53ODw8PhHy4nWMHy5N5AwJ6F26s6MTQ3ODEzNDQ0NTk0NDM3MjE0Ng%3D%3D&id=236
```

## Second vulnerability: ability to delete other people's secondary emails

Exactly the same happens with the add/delete emails action.

The request looks like this:
URL: https://try.gogs.io/user/settings/email/delete

```
POST /user/settings/email/delete HTTP/1.1
Host: try.gogs.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 72
Cookie: lang=en-US; i_like_gogits=2887387054a1bd79; _csrf=53ODw8PhHy4nWMHy5N5AwJ6F26s6MTQ3ODEzNDQ0NTk0NDM3MjE0Ng%3D%3D
DNT: 1
Connection: close
 
_csrf=53ODw8PhHy4nWMHy5N5AwJ6F26s6MTQ3ODEzNDQ0NTk0NDM3MjE0Ng%3D%3D&id=26
```

By modifying the `ID` we can delete email addresses from other users.

Kind regards,
Miguel Ángel Jimeno

**Comment by Unknwon** [comment]
Fixed in `master`.
