### ISSUE TITLE
Assignee menu text is overwritten when typing name

### ISSUE THREAD

**Issue by Corben78** [gogits/gogs#3963]
- Gogs version (or commit ref): last stable 0.9.71.0809
- Git version: 
- Operating system: OpenSuSE
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When creating a new issue, and assigning somebody to it, the text "Assignee" is overwritten by the entry, when typing his name (or at least the first letter of his name).  
Then the assignee is written twice in that place. Once where the text "Assignee" stood before, and the assignee himself below.  
When clearing the assignee entry again, still the "Assignee" text before with the gear symbol next to it is gone. Either the formerly assigned assignee is still written there, or the text "clear assignee"

Especially when a lot of people are working on a project this list can be quite long, so typing is the faster way than searching in the list manually.

**Comment by markainick** [comment]
The same behaviour can also be seen with Labels and Milestone Menus.

**Comment by Unknwon** [comment]
>the text "Assignee" is overwritten by the entry
What entry?

Hi, can you provide some screenshot because I'm pretty much confused.

**Comment by markainick** [comment]
Here's a gif:

![gogsbug_gif](https://cloud.githubusercontent.com/assets/15358419/22417045/69c43cd0-e6d2-11e6-8afb-760168f7b037.gif)

Basically what you try to select by typing overwrites the controller name (in this case "Labels").

**Comment by Unknwon** [comment]
@markainick thanks, is it on demo site?

**Comment by Corben78** [comment]
Yes, for both labels and assignees.

**Comment by Unknwon** [comment]
What browser are you using? I can't reproduce this on demo site using Chrome 56 on Mac OS X.

**Comment by Corben78** [comment]
I'm using mainly Firefox on Linux, but just tried it in Chrome and it happens there too.
Just cross checked, it's the same behavior with Firefox and Internet Explorer on Windows.

Maybe our explanation wasn't accurate enough, sorry about that. I'll try again:
When clicking on the gear symbol to open the list of labels, milestones or assignees, you have two possibilities to select entries: selecting with mouse, or starting to type the first characters of an entry on your keyboard.
When using the second possibility, as soon as you start typing the text of the item, or only the first letter of it, the entry in the list is "highlighted" with bold font (but neither selected nor checked) and the text next to the gear symbol is overwritten by the text of this entry. The gear symbol vanishes, too.

**Comment by Unknwon** [comment]
I see, I think this is caused by default behavior of Semantic UI, should handle that.

**Comment by spectre013** [comment]
Was looking into this and it happens on the menu items on the upper right of the page that has the list of issues. Currently looking into a fix for it.

**Comment by Unknwon** [comment]
@spectre013 can you take a screenshot?

**Comment by spectre013** [comment]
@Unknwon fixed it and did a pull request. to see the bug go to [try.gogs.io](https://try.gogs.io/gogs/go-gogs-client/issues) click on sort and type "o" and you will see the label item change. It only happens when you type. 

![image](https://cloud.githubusercontent.com/assets/1624093/23967155/7595c0dc-0983-11e7-9b68-baf9621fa874.png)

**Comment by ogarcia** [comment]
@Unknwon if you select "clear labels" the server gives 500 error.

The request:
Request URL:https://try.gogs.io/testador/test/issues/1/label
Request Method:POST
Status Code:500 
Remote Address:159.203.177.156:443
Referrer Policy:no-referrer

The post content:
_csrf:xS9qWwf3zh8qQp-RUn8RISJlCg46MTQ5MDIwMjIxNTI4MjMzMDEwNg==
action:clear
id:

**Comment by Unknwon** [comment]
@ogarcia I was able to reproduce, but after an update for another issue on demo site, it's impossible to 500 anymore.
