### ISSUE TITLE
Server refused our key after installing GOGS?

### ISSUE THREAD

**Issue by adelriosantiago** [gogits/gogs#3964]
I don't know whats going on but after installing GOGS v0.9.97 @ 2016-09-01 from binaries (followed this tutorial: https://gogs.io/docs/installation/install_from_binary) I can no longer login through SSH using my private key. The server responds with a **server refused our key** message.

Prior to installing GOGS everything was working just fine. **What could possibly be causing this?**

**Comment by gsantner** [comment]
Gogs does overwrite ~/.ssh/authorized_keys . How else would users be able to enter keys in the web interface? ;)

**Comment by Unknwon** [comment]
Please read https://discuss.gogs.io/t/how-to-config-ssh-settings/34...

**Comment by adelriosantiago** [comment]
**Isn't this a bug?** It seems that GOGS is rewriting authorized_keys, not adding a new key...

**Comment by Unknwon** [comment]
No, it is expected.
