### ISSUE TITLE
Make commit history page size be a setting

### ISSUE THREAD

**Issue by shushenghong** [gogits/gogs#3965]
Commit history always 51 row per page, can i customize the pagesize in setting or in the get query params like page=5&pagesize=25

https://github.com/gogits/git-module/blob/master/repo_commit.go
line 203
var CommitsRangeSize = 50

https://github.com/gogits/gogs/blob/master/routers/repo/commit.go
line  59
ctx.Data["Page"] = paginater.New(int(commitsCount), git.CommitsRangeSize, page, 5)
...

**Comment by Unknwon** [comment]
Related: https://github.com/gogits/gogs/issues/3830

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

See details: https://github.com/gogits/gogs/commit/c69900325d3b2d5eb7584512547fdc567bf6df91.
