### ISSUE TITLE
Loading repo pages on docker takes 5 seconds

### ISSUE THREAD

**Issue by tony** [gogits/gogs#3973]
Host is Sierra 10.12.2 (16C67)

![screen shot 2016-12-22 at 5 20 29 pm](https://cloud.githubusercontent.com/assets/26336/21443454/f3a66878-c86a-11e6-8565-6630bee2ccd0.png)

Directions used: https://github.com/gogits/gogs/tree/master/docker

28dc5bb  

```
❯ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

❯ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

Any ideas how we can get default instructions to be faster?

**Comment by Unknwon** [comment]
Hi, how many files+directories in the page you view?

**Comment by Unknwon** [comment]
OK.. then I think it's your machine problem: https://try.gogs.io/gogs/gogs/src/develop/models

**Comment by tony** [comment]
Have you tried this with Docker on Sierra @Unknwon

**Comment by Unknwon** [comment]
Yes, all default settings latest Docker Toolbox:

![image](https://cloud.githubusercontent.com/assets/2946214/21444566/c9c06ef2-c87c-11e6-9334-e018db1f662c.png)

**Comment by tony** [comment]
I'm tempted to just close this and troubleshoot next time I try gogs on docker. Since I ended up moving onto something else for the moment. 

I'm in the process of learning more about docker, so if anyone else has this issue please re-open.

**Comment by tony** [comment]
Thank you @Unknwon. I love the project very much

**Comment by Unknwon** [comment]
No problem. Run Gogs natively isn't that bad :D
