### ISSUE TITLE
Use email to  push

### ISSUE THREAD

**Issue by bryant24** [gogits/gogs#3975]
gogs version: 0.9.97.0901

I have some issues,when I push local changes to gogs, the command line always request my password of git user  because of my repos  is git@abc.com, I want to use my gogs email account to log in. So what should I do? I found the Authentication Manage Panel ,some LDAP or SMTP sources, Does this useful? 
Please give me a help! thx!

**Comment by Unknwon** [comment]
Hi, I don't under that does "because of my repos is git@abc.com, " mean, but no you can only use username and password for push/pull on command line.

**Comment by bryant24** [comment]
I use git account to run gogs on my linux,the repos page show  ssh clone address is : git@abc.com:bryant24/x.git, (just example),clone it to local is ok,but when I push,it always require the git account's password, not gogs registed email address acount. If I fill in git account's pwd,the repos show the commit user is git,not my gogs account,I just want use my bryant24 account to commit.
Also,other teamates should use their own gogs account to push,not system account,git.

**Comment by Unknwon** [comment]
Please post all your commands to reproduce this problem here.

**Comment by bryant24** [comment]
When I use http to push

```
MacBook-Air:test_repos $ git push http://bryant24@localhost:3000/bryant24/test_repos.git
Counting objects: 3, done.
Writing objects: 100% (3/3), 260 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To http://localhost:3000/bryant24/test_repos.git
   7948b07..acb28fd  master -> master
```
Everythings ok,but my commit page show the commit author is gogs,not bryant24,I found log below:
```
[git-module] /Users/abc/gogs-repositories/bryant24/test_repos.git: git cat-file -p 56cbd1a0ae3d357faff9f9ffc93b900701d06f88
[git-module] stdout:
tree 36ae6531d58d9fa1e29b67002cefc4f7c3d3c684
author bryant24 <1234567@qq.com> 1482591240 +0800
committer Gogs <gogs@fake.local> 1482591240 +0800

Initial commit
```
why the author email is Gogs<gogs@fake.local>,but not bryant24?

And If I use ssh address to clone:
`git@localhost:bryant24/test_repos.git`
when I push changes to repos,the command line prompt me to write the password of git,but not bryant24,why?

**Comment by bryant24** [comment]
may be I am not config default user  of git when I use http clone address, I config it and the  commit author is ok.

**Comment by bryant24** [comment]
Everythings ok. The reason is I forgot to config the git user and email,thank you,bro, @Unknwon
