### ISSUE TITLE
webhook is not triggered doing release on web interface

### ISSUE THREAD

**Issue by MehSha** [gogits/gogs#3978]
when releasing on web interface of project, it creates a tag. when we have configured the webhook to trigger on create, we expect to do it. but it does not.
I tried it on 0.9.71, 0.9.97 and 0.9.113 none work.
when we push through command line it works on 0.9.71 and 0.9.97, 0.9.113 has another bug in this regard.

- Gogs version (or commit ref):  0.9.113
- Git version: 1.8
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

...

**Comment by Unknwon** [comment]
Can you reproduce on https://try.gogs.io?

**Comment by Unknwon** [comment]
I think this one the same as https://github.com/gogits/gogs/issues/3977 based on what you posted.

**Comment by MehSha** [comment]
this is not the same as that. that is for non working tag and PR in general, this is to track the issue of webui not triggering webhook. seems to be duplicate of 2387
