### ISSUE TITLE
Gogs .deb package has redundant dependency to `mysql-common`

### ISSUE THREAD

**Issue by bozaro** [gogits/gogs#3980]
- Gogs version: 0.9.113
- Operating system: Ubuntu 12.04/14.04/16.04, Debian 7/8

## Description
Gogs .deb packages on Packager.io (https://packager.io/gh/pkgr/gogs/install?bid=557) has redundant dependency to `mysql-common`, but `gogs` executalbe don't require it:

```
bozaro@landfill:/tmp$ ldd gogs 
	linux-vdso.so.1 =>  (0x00007ffd219fe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe99167000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe98f4a000)
	libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 (0x00007fbe98d3b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe98972000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559ceb079000)
	libaudit.so.1 => /lib/x86_64-linux-gnu/libaudit.so.1 (0x00007fbe9874b000)
```

**Comment by Unknwon** [comment]
Thanks for the feedback!

But please send email to admin of https://packager.io, it is not maintained by Gogs.
