### ISSUE TITLE
Connect with MAMP

### ISSUE THREAD

**Issue by choungchamnab** [gogits/gogs#3982]
I can't not connect to my sql server. Below is my information : 
GOGS -> Latest
MySQL Server (install with MAMP )

> Host	 localhost
Port	3306
User	root
Password	root
Socket	/Applications/MAMP/tmp/mysql/mysql.sock

OS : macOS Sierra
Error : Database setting is not correct: dial tcp 127.0.0.1:3306: getsockopt: connection refused
Database : already created with root permission

**Comment by Unknwon** [comment]
I think this is a deployment issue rather than Gogs bug. Based on the error message, I think either your MySQL server is not running, or the connect string is wrong.
