### ISSUE TITLE
How to insert existing repo into gogs

### ISSUE THREAD

**Issue by dbabits** [gogits/gogs#3983]
How can I make an existing repo, created outside of gogs appear in gogs?
gogs 0.9.113.1223

**Comment by bryant24** [comment]
Just update the remote address.
first,remove your remote origin 
`git remote rm origin`

second,add new remote origin
`git remote add origin git@your_gogs_repos_here.com`

at last,push your master branch code
`git push origin master`

Wish it can help you.

**Comment by Unknwon** [comment]
You can use migrate repository from local path.

**Comment by CatsNipYummy** [comment]
When we do the above, what's the password? While I setup my git user, I did not provide a password for it. Did anyone have the same problem?

**Comment by unknwon** [comment]
@CatsNipYummy you need first create the first user via web UI, which becomes the admin automatically.
