### ISSUE TITLE
User/org repository listing API

### ISSUE THREAD

**Issue by pyhedgehog** [gogits/gogs#3984]
Right now gogs has implemented [`GET /api/v1/user/repos`](https://developer.github.com/v3/repos/#list-your-repositories).
Please implement also those two:
  - [ ] [`GET /api/v1/users/:username/repos`](https://developer.github.com/v3/repos/#list-user-repositories)
- [ ] [`GET /api/v1/orgs/:org/repos`](https://developer.github.com/v3/repos/#list-organization-repositories)

**Comment by scriptnull** [comment]
I would like to work on this. I had already set up my local environment. Any pointers regarding this would be helpful. I hope to explore and figure it out myself :slightly_smiling_face:

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Unknwon** [comment]
https://github.com/gogits/go-gogs-client/wiki/Repositories#list-user-repositories
