### ISSUE TITLE
Originator of issue notified on changes

### ISSUE THREAD

**Issue by termlimit** [gogits/gogs#3985]
If a user creates an issue they should be notified if the issue is fixed, changed, and or responded to. Currently the only way to get notifications is to watch the repo. Some people may not want to receive all notifications only updates to their issues. Thoughts?

**Comment by Unknwon** [comment]
If you watch the repository, you will be notified with email and activity feeds. And Gogs does not have notification system like GitHub, so it's impossible to has a nice little dot right now.
