### ISSUE TITLE
about the conflicts

### ISSUE THREAD

**Issue by netcore-jroger** [gogits/gogs#3986]
我使用的是最新版gogs.不过遇到了下面的问题。

我自己搭建了一套 gogs 仓库。创建了账号A，并创建了仓库R。从一个账号A上面 fork了一份代码,然后在账号B上面修改(A也修改了代码)，提交 PR，但是提示冲突了，到这儿还没问题。但提示让我自己解决冲突。我的账号B拉取不到账号A的内容。冲突我怎么解决？把代码还原回去也不现实啊。
能不能先让我从账号A同步代码到账号B再，这样有冲突了我就可以用账号B拉取并解决冲突，再提交PR了啊。

**Comment by netcore-jroger** [comment]
不过按 gitflow 的指导思想，A 的 master 分支是不能直接修改的。一定要从别的地方合并PR。严格按这个来的话，也不会出现A修改代码的情况。但是以防万一啊。

**Comment by Unknwon** [comment]
https://help.github.com/articles/syncing-a-fork/

Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by netcore-jroger** [comment]
@Unknwon 谢谢。不过如果能在线同步就好了。我想的也是这种方式去解决。
