### ISSUE TITLE
creating a new repo: stuck at Quick Guide

### ISSUE THREAD

**Issue by dbabits** [gogits/gogs#3988]
Gogs Version: 0.9.113.1223

Steps to reproduce:
Create a new repo using Gogs UI.
Uncheck "Initialize with selected templates"
Gogs gives you Quick Guide.
Follow the steps in Quick Guide successfully (pushing to the repo)
Refresh - Quick Guide will never go away. Repo view is stuck at it.

**Comment by Unknwon** [comment]
What's the output from your server if you do ssh -T to the server?

**Comment by dbabits** [comment]
with -T, it never gives the prompt, at the end of this:
```
pi@raspberrypi:~ $ ssh -T pi@raspberrypi
pi@raspberrypi's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
sourcing  /home/pi/.bashrc
hello from /home/pi/.bash_profile
```

**Comment by Unknwon** [comment]
Ok, you have bypassed Gogs delegation to your SSH connection. Please read https://discuss.gogs.io/t/how-to-config-ssh-settings/34

**Comment by dbabits** [comment]
I read the referenced page. 
My case is: standalone service like OpenSSH server.
However, I'm not very clear. 
A lot of information in the documentation has to do with the configuration of keys.
But, I don't want to use keys, this is a separate topic. 
I'm happy with typing my password, which ssh allows.

The ssh path that shows on the page looks like this, and it's incorrect.
pi@raspberrypi:dbabits/gogs.git

Config:
```
[repository]
ROOT = /mnt/usb2/gogs-repositories
[server]
DOMAIN       = raspberrypi
HTTP_PORT    = 3000
ROOT_URL     = https://raspberrypi:3000/
DISABLE_SSH  = true
SSH_PORT     = 22
OFFLINE_MODE = true
PROTOCOL     = https
CERT_FILE    = /home/pi/bin/gogs/cert.pem
KEY_FILE     = /home/pi/bin/gogs/key.pem

```
```
pi@raspberrypi:~/bin/gogs $ git remote -v
origin  /mnt/usb2/gogs-repositories/dbabits/gogs.git (fetch)
origin  /mnt/usb2/gogs-repositories/dbabits/gogs.git (push)
```
If I push to that path, it works.

I'm sorry if I misread the docs, but looking at the gogs forum, many people are confused by the exact same thing.
