### ISSUE TITLE
v0.9.113: Which is the correct binary for Raspberry Pi 3?

### ISSUE THREAD

**Issue by rheicide** [gogits/gogs#3989]
Before v0.9.113, I've always used the Linux ARM binary for my RPi 3. Now it has been replaced by the ARMv5 and ARMv6 ones. They might work, but I'd like to know which ones is the best for a RPi 3, which runs on ARMv8. Or could it be the RPi 2 binary that I've always ignored?

It would be great if there could be a line in the documentation and/or the README specifying which binary to use for different versions of the Raspberry Pi.

Thank you for this wonderful project. I enjoy it a lot!

**Comment by Unknwon** [comment]
I think RPi2 binary is the best.
