### ISSUE TITLE
send email error when write comment

### ISSUE THREAD

**Issue by bryant24** [gogits/gogs#3990]
gogs version:0.9.97.0901

```
2016/12/28 15:49:49 [...les/mailer/mailer.go:201 processMailQueue()] [E] Fail to send emails [452870252@qq.com]: Subject: [jxr_api] 测试邮箱 (#2), issue comment - gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?\"=E8=80=BF=E8=88=92\"_<gitserver@mymail.com>?=": mail: expected single address, got "?="
```

When I write comments in issues,send email always fail, I check the gogs.log and found this, this is my mailer config in app.ini:

```
[mailer]
ENABLED = true
HOST    = smtp.exmail.qq.com:465
FROM    = "GIT_SERVER" <gitserver@mymail.com>
USER    = gitserver@mymail.com
PASSWD  = mypassword
```
 And I also viewed the issues in
[https://github.com/gogits/gogs/issues/3714](https://github.com/gogits/gogs/issues/3714)
[https://github.com/gogits/gogs/pull/3960](https://github.com/gogits/gogs/pull/3960)
They edit the `setting.MailService.User` to `setting.MailService.From`
The master branch not merge this pr, should I recompile it myself to resolve this question ?

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/3856.
