### ISSUE TITLE
When I push the two branches, webhook only triggered once

### ISSUE THREAD

**Issue by huijiewei** [gogits/gogs#3991]
Client operate: create hotfix, complete hotfix, push master and develop
Gogs webhook log: only triggered develop push

- Gogs version (or commit ref): 0.9.113.1223
- Git version: 2.11.0
- Operating system: Ubuntu 16.04.1 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

...

**Comment by Unknwon** [comment]
Just realized this is duplicated to https://github.com/gogits/gogs/issues/3337.
