### ISSUE TITLE
API: nil pointer dereference when retrieving content from unintialized repository

### ISSUE THREAD

**Issue by cybe** [gogits/gogs#3992]
- Gogs version: v0.9.113
- Git version: 114c179
- Operating system: Alpine Linux 3.4
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:
Stracktrace: https://gist.github.com/cybe/603458382308f3bd27ee98b95641feb9
## Description
Retrieving a blob from an unintialized repository results in a nil pointer dereference, as shown in the Stacktrace. The corresponding API call looks like this:

`curl -v -H "Authorization: token 30af10dae468fa01d658c2b7962a204880fb6751" https://try.gogs.io/api/v1/repos/cybe/test/raw/master/Dockerfile`
→ HTTP/1.1 500 Internal Server Error

The relevant line in the source code: https://github.com/gogits/gogs/blob/114c179e5a50e3313f7a5894100693805e64e440/routers/api/v1/repo/file.go#L22

**Comment by Unknwon** [comment]
Fixed by #3996.
