### ISSUE TITLE
network of branch

### ISSUE THREAD

**Issue by vision-ken** [gogits/gogs#3993]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: 2.8.4 (Apple Git-73)
- Operating system: mac
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
can gogs provide a network of branch like below?
https://github.com/mojombo/god/network

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/19.
