### ISSUE TITLE
how to expose SSH root path URL when using another SSH server? 

### ISSUE THREAD

**Issue by 2Belette** [gogits/gogs#3995]
- Gogs version (or commit ref): 
- Git version: 0.9.97
- Operating system: 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I am using my own SSH server and I got a little issue where gogs is not exposing the SSH path correctly.
I got this exposed to user : 
`ssh://gogs@server:222/user/repo.git`
but my installation is made on `/srv/gogs/`
so I would like to expose 
`ssh://gogs@server:222/srv/gogs/repo/user/repo.git`
Is there a simple way to do it?
I already took a look on some older post but didn't found the answer, I also tried to tweak some variable in app.ini but not able to make it either.
I thought that SSH_ROOT_PATH would make the tricks but it is not

Many thanks 

Edit : the reason why I want to use another ssh server is mostly because of two factor authentication (yubico)
I also notice a strange behavior when I am not using the included SSH server, if I try to push some data from my local repository I don't see any files pushed but I don't have any error message: all the git push process is working correctly...
Any one who use external SSH server correctly with gogs ?

**Comment by Unknwon** [comment]
Hi, if you don't use Gogs's SSH URL for push, you're bypassing Gogs delegation to collect data, that's why you don't get anything (news feeds, etc.), which is incorrect way of using Gogs..
