### ISSUE TITLE
pull request number displays -1

### ISSUE THREAD

**Issue by light4** [gogits/gogs#3998]
- Gogs version (or commit ref): 0.9.114.1227
- Git version: 2.6.6
- Operating system: Alpine Linux 3.3 in Docker
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
> 2016/12/30 06:39:09 [...routers/repo/pull.go:700 CompareAndPullRequestPost()] [E] NewPullRequest: newIssue: Error 1062: Duplicate entry '5-32' for key 'UQE_issue_REPO_INDEX'
## Description

Gogs can't get the right pull request number after some action I don't remember :(.
It shows like this:
![image](https://cloud.githubusercontent.com/assets/1318472/21560828/990d8ab4-ce9f-11e6-9db8-b9a7a4adbdb1.png)
Server response 500 error when make new pull request. Log:
> 2016/12/30 06:39:09 [...routers/repo/pull.go:700 CompareAndPullRequestPost()] [E] NewPullRequest: newIssue: Error 1062: Duplicate entry '5-32' for key 'UQE_issue_REPO_INDEX'

Thanks for your work.

**Comment by Unknwon** [comment]
Is_ it still happening in the latest `master`?
