### ISSUE TITLE
changes append to a pull request make the gogs process crash

### ISSUE THREAD

**Issue by chinglinwen** [gogits/gogs#3999]
- Gogs version (or commit ref):  Gogs version 0.9.113.1223
- Git version:  git version 2.11.0
- Operating system:  CentOS release 6.4 (Final)
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

```
[Macaron] 2016-12-30 16:30:49: Started POST /wenzhenglin/test.git/git-receive-pack for 192.168.100.69
2016/12/30 16:30:49 [D] Session ID: b5667e06675cb4ba
2016/12/30 16:30:49 [D] CSRF Token: BHx7lvSye-ItV-5XWwhot1pXxwQ6MTQ4MzA4NjY0OTExNDI5NTcxNQ==
2016/12/30 16:30:49 [T] DeliverHooks [repo_id: 3]
[Macaron] 2016-12-30 16:30:49: Completed /wenzhenglin/test.git/git-receive-pack 200 OK in 401.795167ms
2016/12/30 16:30:49 [T] AddTestPullRequestTask [head_repo_id: 3, head_branch: self-pull-request-test]: finding pull requests
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x589625]

goroutine 1063 [running]:
panic(0xdaf7c0, 0xc42000e0c0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gogits/gogs/models.(*Repository).cloneLink(0x0, 0x166ae00, 0x0)
        /home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:561 +0x55
github.com/gogits/gogs/models.(*Repository).CloneLink(0x0, 0x0)
        /home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:579 +0x30
github.com/gogits/gogs/models.(*Repository).APIFormat(0x0, 0x0, 0xc4216efd60)
        /home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:255 +0x2f
github.com/gogits/gogs/models.(*PullRequest).APIFormat(0xc42170ea80, 0x0)
        /home/vagrant/gopath/src/github.com/gogits/gogs/models/pull.go:157 +0x86
github.com/gogits/gogs/models.AddTestPullRequestTask(0xc421cf2600, 0x3, 0xc421af65dd, 0x16, 0x1)
        /home/vagrant/gopath/src/github.com/gogits/gogs/models/pull.go:693 +0x5de
created by github.com/gogits/gogs/routers/repo.HTTP.func1
        /home/vagrant/gopath/src/github.com/gogits/gogs/routers/repo/http.go:230 +0x507

```

## Description

1. A test repo ( private ) ( not a fresh repo )
2. Create a branch at client, send it to gogs  ( by repo's owner )
3. Create a pull request for it  ( by repo's owner )
4. Add a new change and commit  ( by repo's owner )
5. Push that commit to gogs, caused gogs process crash  ( by repo's owner )
    //restart gogs, fix the issue ( gogs working normally )

then gogs process crashed, it's repeatable, by following step (gogs restarted here)
1. add a new change again and commit to that branch( which have pull request, not merge yet )
2. push that commit to the gogs platform ( crash again )

after restart, the gogs work correctly ( the pushed commit is in there, no missed commit ), and merged successfully

more log contents:  [gogs_crash_log.txt](https://github.com/gogits/gogs/files/678459/gogs_crash_log.txt)
app.ini:  [app.ini.txt](https://github.com/gogits/gogs/files/678463/app.ini.txt)

**Comment by akademic** [comment]
Same issue in build from 8059175

**Comment by Unknwon** [comment]
Is it still happening the latest `master` branch?

**Comment by chinglinwen** [comment]
Currently, I'm on vacation, I may try it after February 6.  But I think
it's easy to test, It's not a special environment to reproduce this issue.

**Comment by akademic** [comment]
Bug still here on commit 207960b.

**Comment by Unknwon** [comment]
@akademic can you reproduce on demo site?

**Comment by akademic** [comment]
On try.gogs.io I can't see any crash.
My installation uses sqlite. Demo site probably not.

**Comment by Unknwon** [comment]
@akademic now it's time to upgrade your Gogs, it could be a fixed issue in `master`.

**Comment by akademic** [comment]
https://github.com/gogits/gogs/commit/207960b459d635667226d2d78f11ef3279ba9cc7

This changeset was newest in master when I wrote comment. I've compiled gogs from master. And bug still there. I've seen it today morning. How can I help better?

**Comment by Unknwon** [comment]
The best way to help still make error happen on demo site. If can't, please provide step to make error happen on a fresh new repository.

**Comment by akademic** [comment]
Tested this issue right now. Panic still here.

Steps to reporduce:

1. Clone repository master branch
2. `go get -u -tags "sqlite" github.com/gogits/gogs`
3. `go build -tags "sqlite"`
4. Run `gogs web`,  choose sqlite database and setup user1 account
5. Create new repository test (public) and commit one empty
6. Create new user2 from admin panel
7. Login in user2 and fork repository user1/test.git
8. And new change in user2/test.git, push and create pull request
9. Add another change in user2/test.git, push
10. Wathc panic log
```
[Macaron] 2017-02-02 13:52:01: Started POST /tca/test.git/git-receive-pack for <ip>
2017/02/02 13:52:01 [D] Session ID: dd307745fa16acb8
2017/02/02 13:52:01 [D] CSRF Token: lLuCkH1b-_QbxkLE-gMb3n61zv06MTQ4NjA0MzUyMTU1ODIyNjczNA==
2017/02/02 13:52:01 [T] DeliverHooks [repo_id: 2]
2017/02/02 13:52:01 [T] AddTestPullRequestTask [head_repo_id: 2, head_branch: master]: finding pull requests
[Macaron] 2017-02-02 13:52:01: Completed /tca/test.git/git-receive-pack 200 OK in 351.348774ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x583b15]

goroutine 1004 [running]:
panic(0xda65e0, 0xc420010080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gogits/gogs/models.(*Repository).cloneLink(0x0, 0x165fa00, 0x0)
        /go/src/github.com/gogits/gogs/models/repo.go:562 +0x55
github.com/gogits/gogs/models.(*Repository).CloneLink(0x0, 0x0)
        /go/src/github.com/gogits/gogs/models/repo.go:580 +0x30
github.com/gogits/gogs/models.(*Repository).APIFormat(0x0, 0x0, 0xc421ba5d60)
        /go/src/github.com/gogits/gogs/models/repo.go:256 +0x2f
github.com/gogits/gogs/models.(*PullRequest).APIFormat(0xc421382700, 0x0)
        /go/src/github.com/gogits/gogs/models/pull.go:157 +0x86
github.com/gogits/gogs/models.AddTestPullRequestTask(0xc420f10400, 0x2, 0xc42186e0cd, 0x6, 0x1)
        /go/src/github.com/gogits/gogs/models/pull.go:693 +0x5de
created by github.com/gogits/gogs/routers/repo.HTTP.func1
        /go/src/github.com/gogits/gogs/routers/repo/http.go:230 +0x507
```

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Unknwon** [comment]
Commit referenced to wrong thread: https://github.com/gogits/gogs/commit/afab38b0d74c65e1deb4348a411cd3a13a641b74

**Comment by chinglinwen** [comment]
I test it on version v0.9.141, the issue has been fixed.

**Comment by Unknwon** [comment]
Thanks for the confirmation!
