### ISSUE TITLE
500 when creating an issue with image

### ISSUE THREAD

**Issue by helli72** [gogits/gogs#4001]
- Gogs version (or commit ref): v0.9.113
- Operating system: Ubuntu-Mate 16.04 on Raspberry 3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Not tried

## Description

Create a new issue with image shows a 500.
Create a new issue with text-only works. Add an answer with image works.

**Comment by Unknwon** [comment]
It is fixed in `master`.

**Comment by helmut72** [comment]
now, issues doesn't work at all.

just updated from 0.9.113 to 0.10.18 using this file:
https://dl.gogs.io/0.10.18/raspi2_armv6.zip

and this readme:
https://gogs.io/docs/upgrade/upgrade_from_binary
