### ISSUE TITLE
visiblity of a private repository owned by an organization

### ISSUE THREAD

**Issue by Druson** [gogits/gogs#4002]
- Gogs version (or commit ref):  8059175a5c0363519ba28fb8fc5f9d494f6a209d
- Git version:  2.1.4
- Operating system:  Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

If a **private** repository owned by an **organization**, the non-admin member of the organization can not see the repository, and the member of the organization can not be added as a collaborator to this repository as well. But if the member was added to this repository  as a collaborator  before joined the organization, he still can see this repository after joined the organization.

**Comment by Unknwon** [comment]
Does this problem still exist in latest `develop` branch?

**Comment by Unknwon** [comment]
Please notify when this issue happens again.
