### ISSUE TITLE
Adapt clone link in web interface if using gogs' built-in SSH server

### ISSUE THREAD

**Issue by lorenzschmid** [gogits/gogs#4003]
- Gogs version (or commit ref): 0.9.110.1222
- Git version: 2.11.0
- Operating system: CentOS release 6.8 (Final)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

## Description

Having installed gogs on a shared host where I have only access via single SSH user I use gogs built-in SSH server on a different port than 22. This further allows all my gogs user to access and update repos via (gogs' built-in) SSH.

Unfortunately, these settings are not reflected in the clone URL in the web interface of a repository: I would expect to see now

    [gogs user name]@[DOMAIN]:[SSH_LISTEN_PORT]/[repo url]

instead the following is shown

    [gogs' RUN_USER]@[DOMAIN]:[repo url]

which still refers to an access to the server's default SSH installation and not gogs' built-in server.

**Comment by RodenLuo** [comment]
Hi Lorenz,

Quote from [here](https://github.com/gogits/gogs/tree/master/docker):

> SSH Port: Use the exposed port from Docker container. For example, your SSH server listens on 22 inside Docker, but you expose it by 10022:22, then use 10022 for this value. Builtin SSH server is not recommended inside Docker Container

To realize `[gogs user name]@[DOMAIN]:[SSH_LISTEN_PORT]/[repo url]`, if you are using docker, modify api.ini (Mine is `/var/gogs/gogs/conf/api.ini`), set `SSH_PORT     =` to your port. If you're not using docker, there should be a similiar place to do that.

---
**However**, I was not able to use the address with explicit port in Mac OS X ZSH command line (Not checked the reason yet).  But there is still a way to use SSH connection. Don't perform the above change. Keep using `[gogs' RUN_USER]@[DOMAIN]:[repo url]`. 

Put the following two lines in your `.ssh/config`.

    Host YOUR.GOGS.DOMAIN
        Port SSH_LISTEN_PORT

Then you should be able to use `[gogs' RUN_USER]@[DOMAIN]:[repo url]` to connect to your repo.

**Comment by lorenzschmid** [comment]
> Put the following two lines in your .ssh/config.
>
>    Host YOUR.GOGS.DOMAIN
>        Port SSH_LISTEN_PORT

Thanks for your reply, this is exactly how I have done it.

I opened the issue rather to indicate a misalignment between the URL shown in the web interface and the actual URL needed for git.

**Comment by RodenLuo** [comment]
I see. I tested just now. I am able to clone with 

    git clone ssh://<USER>@<DOMAIN>:<PORT>/PATH/TO.git

And changing settings in api.ini gives you the above URL.

---
I was kinda wrong in the previous reply. What I was not able to execute is the following command for testing connection.

    ssh -Tv <USER>@<DOMAIN>:<PORT>

This feature may not be supported in command.

**Comment by lorenzschmid** [comment]
> I see. I tested just now. I am able to clone with
>
>    git clone ssh://<USER>@<DOMAIN>:<PORT>/PATH/TO.git
> And changing settings in api.ini gives you the above URL.

Just to get back to the original question: What and where do you change in app.ini in order to have the desired output URL in the web interface? Just set `SSH_PORT`?

**Comment by RodenLuo** [comment]
Input the port when you install the instance (I installed it via docker. There is a textfield ask for ssh port.)

OR

Find this [file](https://github.com/gogits/gogs/blob/master/conf/app.ini) in your running instance (Some where in the gogs directory). Change `SSH_PORT = 22`, if you do not have this line, add it under `[server] ` section. Restart the service in your way.

---
### Steps for docker default setting users

1. Change file `/var/gogs/gogs/conf/app.ini`
2. `docker stop gogs`
3. `docker start gogs`

**Comment by lorenzschmid** [comment]
Hi @RodenLuo 

Thanks for your explanations. Unfortunately I do not think that they tackle my original problem. I am using the built-in SSH server (so the `SSH_PORT` setting is irrelevant) on a shared hosting (no docker) and as mentioned previously don't have any issue to make it work. My sole issue is the representation of the clone URL shown in the web interface which I consider a bug.

So to rephrase it: I don't need any help how to adapt my `app.ini` file but rather wanted to report that the shown URL in the web interface is not correct. Please only respond further if you know any setting how to change this URL via dedicated settings.

**Comment by Unknwon** [comment]
>I don't need any help how to adapt my app.ini file but rather wanted to report that the shown URL in the web interface is not correct. Please only respond further if you know any setting how to change this URL via dedicated settings.

The clone URL is composed by your configuration, if you don't see a port number in the URL, then you have to change `SSH_PORT` to whatever number other than **22**. [The comment](https://github.com/gogits/gogs/blob/master/conf/app.ini#L110-L111) described this as well.

**Comment by lorenzschmid** [comment]
Thanks for the answer. It might be worth to add this to the documentation too.
