### ISSUE TITLE
Releases page - Migration loses information

### ISSUE THREAD

**Issue by qdbdbp** [gogits/gogs#4004]
- Gogs version (or commit ref): 0.9.114.1227
- Git version: 2.9.2
- Operating system: FreeBSD 11
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

mirror loses information
lost:
- Pre-release
- Title
- Content

GitHub: 
![github](https://cloud.githubusercontent.com/assets/19255071/21594246/a6d5767e-d120-11e6-9d4f-fd7f3c74ab29.png)

Gogs: 
![gogs](https://cloud.githubusercontent.com/assets/19255071/21594247/ac4b8756-d120-11e6-95af-993f13fdc7c3.png)

**Comment by Unknwon** [comment]
Thanks for the feedback!

However, migration is on Git level, not application level. Content specific belongs to GitHub is not part of Git repository migration.
