### ISSUE TITLE
Releases page - Attach binaries

### ISSUE THREAD

**Issue by qdbdbp** [gogits/gogs#4005]
- Gogs version (or commit ref): 0.9.114.1227
- Git version: 2.9.2
- Operating system: FreeBSD 11
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Will be the place to add binary files?
This is plans to add this functionality?

GitHub: 
![github_release](https://cloud.githubusercontent.com/assets/19255071/21594405/7c447af2-d122-11e6-8cd3-dcb19a9bd98f.png)

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1614.
