### ISSUE TITLE
[Vulnerability] Security Bug Report Sent Notice

### ISSUE THREAD

**Issue by RodenLuo** [gogits/gogs#4006]
- Gogs version: 0.9.114.1227
**The one that your demo site uses as of 2017-01-01.**
- Git version: As above
- Operating system: As above
- Database: As above
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (See my Email for example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

> I see examples that private bug report Emails were ignored. I see the need to remind it here. Please excuse me if this causes you any inconvenience.

I have sent the full report to the indicated Email address. 

    Sent Time: Sun, Jan 1, 2017 at 9:06 PM -08:00
    More details at: Sun, Jan 1, 2017 at 9:39 PM -08:00

I can re-send them upon request.

## Suggestions to the community

1. If you have valuable information on your Gogs instance, then **cut off the public access to your Gogs instance**, use it with trusted users locally/internally. (This is the safest way, but not the necessary. I cannot give the minimal changes before I get the author's reply.)
2. Notify friends who are running Gogs instance or its forks.

Happy New Year! Let's make it better in 2017!
Roden Luo

**Comment by bkcsoft** [comment]
@RodenLuo could you try this on https://try.gitea.io and if the bug exists send the report to security@gitea.io as well? :)

**Comment by RodenLuo** [comment]
@bkcsoft I already gave a try on [ https://try.gitea.io](https://try.gitea.io), aborted that when I thought it existed there. I tried the full process just now. Hacked (You can say that on functionality part, but it's not the whole system). I changed everything back to original. You may notice something or not.

No offense, but if you notice something, and get the bug, please keep quiet. 

I will only release the report to other place if I get reply from `u@gogs.io` in Email or here by @Unknwon . Sorry about that, but there are 10M+ [pulls](https://hub.docker.com/r/gogs/) from Docker! (I guess, he will also consider this carefully. Seems it is used by some companies.) If you know him, tell him about this issue. Or if you are trusted by him, and you can show me he trusts you. I will send to you.

**Comment by bkcsoft** [comment]
@RodenLuo the intent is to keep quiet until Unknwon has responded and made the appropriate changes, just that we would like a heads-up and maybe time to fix the issue (but not release) for when the issue is made public. All in respect of vuln-reports 🙂 

It is unfortunately somewhat of a grey-zone when we are a fork with the same vuln 🙁

**Comment by RodenLuo** [comment]
Hi Kim,
I understand your feelings. However, I cannot leave all those [pulls](https://hub.docker.com/r/gogs/) and the instances [here](https://www.google.com/search?q=Gogs+Version%3A+page+ms+template+ms&oq=Gogs+Version%3A+page+ms+template+ms&aqs=chrome..69i57.625j0j9&sourceid=chrome&ie=UTF-8) as well as the companies mentioned in the footer section of [Gogs](https://gogs.io/), Your forks, other forks, VULNERABLE. Please also think on the other side. 

It's not about the server, it is about the Gogs instance. So, you can **cut off the public access to your Gogs instance**. And then wait for @Unknwon .

Everything will be clear. I hope you understand me when you know the bug.

**Comment by tboerger** [comment]
> It's not about the server, it is about the Gogs instance. So, you can cut off the public access to your Gogs instance. And then wait for @Unknwon .

We have entirely forked the Gogs source and we are building an independent project out of that.

**Comment by RodenLuo** [comment]
Since it has not got attention from the author. And some people may want to at least protect their instances before the fix, and keep it running on the web. I offer the following hack test. Give me the information below **inside this issue**.

Example information I need:

    URL: https://try.gogs.io/
    YOUR username: RodenLuo 

    1. I authorize Roden Luo to perform the hack test.
    2. I will only say "Hacked Serious / Hacked Not Serious / Not Hacked".
       regarding this issue anywhere on the web unless agreed by Roden Luo.
    3. I will not say anything else regarding this issue on the web unless agreed by Roden Luo.

    Your Name, YourEmail@example.com I can contact with.

(The username should be yours, i.e. you know the password, you can login, so that you can understand what I have hacked. ) 

If you give me the information in the box, you agree 1,2,3 in the box. Then I will try to hack it, and give you feedbacks like **"Vulnerable / Vulnerable but you cannot see my hack results / Secure"** here in the issue, and what info I still need to let you understand that I can hack, as well as how to protect your instance via Email. You cannot make public the contents of the communication between you and me unless I agree that.

AGAIN, I will not tell you how I do that. Don't try to ask me that.

@bkcsoft If you want to join, point me who you are in this [list](https://try.gitea.io/explore/users). I will hack against that user.

**Comment by Unknwon** [comment]
Thanks for the report, should be fixed by now.

**Comment by RodenLuo** [comment]
Fixed!
---

But ... Just a suggestion:
Notify some users if you can. See more in Email. But it's totally up to you. If you do not have users to notify, or if you think I can make the bug report public right now, tell me.

**Comment by Unknwon** [comment]
>or if you think I can make the bug report public right now, tell me.

Yes, you can public now. Thanks!

**Comment by lunny** [comment]
Maybe
```Go
if !forkRepo.CanBeForked() || !forkRepo.HasAccess(ctx.User) {
```
?

**Comment by RodenLuo** [comment]
The bug test is very simple:

Just before this fix, Open link https://try.gogs.io/repo/fork/7596, Login, Fork! But that's my private repository. Since it has been fixed, you may test on https://try.gitea.io/repo/fork/4 (Based on the name, it is a test project, so I put it here. ) or your own instance.

**Comment by RodenLuo** [comment]
See my next post on this [issue](https://github.com/gogits/gogs/issues/1791) to know how I find this bug.

**Comment by lunny** [comment]
Please don't publish this since many users haven't upgrade their instances.

**Comment by RodenLuo** [comment]
I erased my report. If you can still see it somewhere, tell me how to delete.

**Comment by StrawberryJuice** [comment]
@Unknwon Could you also build binaries/ tag a new release regarding this vulnerability? Thanks in advance.

**Comment by rugk** [comment]
I'd also say releases are now needed, although also a full vulnerability report should be published (afterwards)!

----

@tboerger Has this been fixed in gitea?

**Comment by tboerger** [comment]
> @tboerger Has this been fixed in gitea?

That should be part of 1.0.1 which is already released.

**Comment by Unknwon** [comment]
Close as release is out today.

**Comment by RodenLuo** [comment]
The bug is very straightforward to understand if one find it. The release [v0.9.128](https://github.com/gogits/gogs/releases/tag/v0.9.128) has it fixed. But before that, you can fork my private repository if you do:

Open link https://try.gogs.io/repo/fork/7596, Login, Fork!

(I was answering #1791 when I found this bug. You will know how to realize that after you get the bug. I will post my answer there later.)

---
/cc @rugk Thanks for cc to me in Issue 4033. Please check the above bug report.

---
### My concern

I do not quite understand why there are different indexing/numbering systems. Maybe it is for the sake of convenience in coding. Since I have not learned Go Language yet, I have not checked the codes or even tried to fix this by myself. I initially suggested using a similar URL to GitHub's (https://github.com/gogits/gogs#fork-destination-box). In this case, (to my understanding) we only need to check the eligibility once for "https://github.com/gogits/gogs". But the author's way to fix it is also very clean. With that, my concern is **Are there other indexing systems in codes which may be subject to vulnerability problems?** And for a broader view, are there other vulnerability problems like this if one read the code? (Hope no) 

Thx!

**Comment by rugk** [comment]
So what was the actual issue? Was it the one where I CCed you?

**Comment by RodenLuo** [comment]
The issue was, before v.0.9.128, you could fork other people's private repo, by changing the NUM in https://try.gogs.io/repo/fork/NUM . I haven't gone through 4033 in detail, but I think these two may be not the same. That issue has been fixed and closed too.
