### ISSUE TITLE
Initial Pull Requests Number Bug

### ISSUE THREAD

**Issue by RodenLuo** [gogits/gogs#4007]
- Gogs version: 0.9.114.1227
**The one that your demo site uses as of 2017-01-01.**
- Git version: As above
- Operating system: As above
- Database: As above
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (See steps below)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Login to https://try.gogs.io with 
User: rodenTestAccount
Passwd: 123

Click Pull Requests tab in the Navigation bar. You will see 1464 pull requests.

Please do not make any changes to this test account. Because create new repo will mask this bug.

**Comment by Unknwon** [comment]
The account does not have any repositories right now... will reopen when further information provided.

**Comment by RodenLuo** [comment]
Please check the screenshot below. The number will become to 0 (zero) if you create a new repository.

![image](https://cloud.githubusercontent.com/assets/8460424/22400958/d9538b48-e577-11e6-9245-b1cc7d63507f.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
