### ISSUE TITLE
Bulk migrate

### ISSUE THREAD

**Issue by Knetic** [gogits/gogs#4012]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: 1.9.1
- Operating system: Linux (any debian-based)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description

I've got a few dozen bare repositories, locally hosted. I'm just using gogs as a frontend to mirror them, my goal isn't to replace anything, just make it easier to visualize and explore them. I want to migrate all of them at once into gogs.

But the migrate endpoint takes one repo at a time. I'd prefer to be able to import dozens at a time from the same directory (for instance, all repos underneath `/some/path/`, max depth 1).

I attempted to accomplish this with a series of curl calls, but the CSRF makes this ridiculously hard. After an hour or so I gave up on the idea.

**Comment by cedricziel** [comment]
Don't know if it's relevant, but I used the API to migrate repos to gogs from a self hosted gitlab after we didn't need the advanced features anymore.

**Comment by jangor** [comment]
@cedricziel is there a guide to the API? I didn't find anything on this subject in [FAQ](https://gogs.io/docs/intro/faqs). Or is [gogs-migrate](https://github.com/valeriangalliat/gogs-migrate) the tool to use?

**Comment by cedricziel** [comment]
There's a wiki entry I used: https://github.com/gogits/go-gogs-client/wiki

I made this simple migration script: https://gist.github.com/cedricziel/6dbf652649a98aee924dd4dc83524581

Hope that helps

**Comment by Unknwon** [comment]
As mentioned above, please use the migration API endpoint.
