### ISSUE TITLE
Mirror URL credentials should be URL encoded

### ISSUE THREAD

**Issue by Chouchen** [gogits/gogs#4014]
- Gogs version (or commit ref): e8c3e9bcf87aa94497561e52e3cd5a15990a3037
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Login and password in the mirror URL should be URL encoded. For example, when a login is an email (which contains a `@`), it'll be invalid.

In my case, my mirror wouldn't update. My (new) password had a `;` in it which created a remote like this `` `https://login:password`` (the backtick was really here and no URL after). I edited it replacing `;` by `%3B` and now mirror updates work.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Unknwon** [comment]
You can try latest 0.11.4.
