### ISSUE TITLE
No Email Duplication Check when create users from Admin Panel

### ISSUE THREAD

**Issue by RodenLuo** [gogits/gogs#4016]
- Gogs version: 0.9.115.0103
- Git version: Go1.5.4
- Operating system: Ubuntu 16.04
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (I do not have admin access to it.)
  - [ ] Not relevant
- Log gist:

## Description
Minor bug. I turned off the public registration. When I create a new user in Admin Panel, if I use an Email address which has already been used, I can still create the new user. (But it does complain in the Edit page later, which is good.)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch.

**Comment by RodenLuo** [comment]
Tested on docker image. Fixed! 

Thx!
