### ISSUE TITLE
Can't use mail notification, maybe something wrong when configure?

### ISSUE THREAD

**Issue by luoxin1992** [gogits/gogs#4019]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
  I CAN NOT FIND IT......

## Description
Is there any tutorial about how to configure mail notification in gogs? I am fresh to that.
I've just add [mailer] configuration in custom/conf/app.ini, refer to [this](https://github.com/gogits/gogs/blob/master/conf/app.ini). I think there is nothing wrong in SMTP server, user name, password and so on.
Then when I try to click "Send Test Mail" in Admin Panel, after a long time wait, I got an HTTP 504 error finally. What's worse, there isn't any log about that. When I open my log folder, only xorm.log has been modified.
So maybe it is not so simple to configure mail notification? Do I lost some important steps? Or how to find the log about why is failure?
And what's more, my gogs server is under nginx proxy, the nginx log shows the 504 error because of upstream server timeout.
...

**Comment by luodaoyi** [comment]
me too

**Comment by Unknwon** [comment]
Based on the information you provide, I think it's because somewhat Gogs can't reach your mail server which leads to timeout(504). Logs are in `path/to/gogs/log/gogs.log`.
