### ISSUE TITLE
500 error at creating pull request after a repository renamed

### ISSUE THREAD

**Issue by grunmin** [gogits/gogs#4021]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 0.9.25.0506
- Git version: 1.5
- Operating system: CentOS6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

```
2017/01/07 14:08:09 [...routers/repo/pull.go:677 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: Pull: exit status 1 - fatal: '/home/gogs/gogs-repositories/myName/lanxin.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
error: Could not fetch origin
```
## Description
I create a pull request after the base repo had rename and I got a 500 error. I refork the repo in new name and the problem occur again. I check the log and source code, it seen to be `xorm`'s problem. The base repo name update successful in mysql and the function `GetRepositoryByID` do not return correct data. I solved this by restart gogs process. But I can't reproduce the bug at try.gogs.io. Maybe it has been fix, but I can't find any helpful info in issues
...

**Comment by Yousefjb** [comment]
The same issue happend to me and fixed by restarting gogs

**Comment by Unknwon** [comment]
Please upgrade your Gogs!
