### ISSUE TITLE
Gogs ran in docker container can not listen on ports <1024 (e.g. 80, 443)

### ISSUE THREAD

**Issue by emempi** [gogits/gogs#4022]
The docker image currently makes gogs listen on http port 3000, with no easy way to switch this to the default 80. Although this is fine for the use case when docker port is mapped to an external address/reverse-proxied, in some cases it makes much more sense to let it run on port 80 directly.

The obvious ugly workaround here is to run gogs as root, but it would be nice if Gogs dropped root privileges afterwards.

**Comment by dchest** [comment]
Go programs can't drop privileges. I'm not sure if it works in Docker, but you can use capabilities to allow a program to bind to < 1024 ports: https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l#414258

**Comment by Unknwon** [comment]
Answer has been given above..
