### ISSUE TITLE
start via sysctl fails in v913 when process is trying update the .gitconfig file

### ISSUE THREAD

**Issue by CodingNomad** [gogits/gogs#4023]
- Gogs version (or commit ref):  0.9.113.1223
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.1 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: [gogit_v913.txt](https://github.com/gogits/gogs/files/692033/gogit_v913.txt)

## Description
Hi, 

I just tried to upgrade from the binary version of gogs 911 to version 913. After having followed the documentation and copied the three required directories (config, data, log) to the new gogs folder. I tried to kick off the process via system daemon (as I did work with the previous version).
However, this time, the process  terminated with the following error message:

```
2017/01/08 09:55:17 [I] Log Mode: File(Info)
2017/01/08 09:55:17 [I] Cache Service Enabled
2017/01/08 09:55:17 [I] Session Service Enabled
2017/01/08 09:55:18 [I] Git Version: 2.7.4
2017/01/08 09:55:18 [.../gogs/models/repo.go:134 NewRepoContext()] [E] Fail to set git user.name(exit status 255): error: could not lock config file :/home/fidelis-it/domains/git.fidelis-it.net/homes/gituser/.gitconfig: No such file or directory

```

however, when the process was kicked off from the shell, it did start up without issues:
```
2017/01/08 09:53:37 [I] Log Mode: File(Info)
2017/01/08 09:53:37 [I] Cache Service Enabled
2017/01/08 09:53:37 [I] Session Service Enabled
2017/01/08 09:53:37 [I] Git Version: 2.7.4
2017/01/08 09:53:37 [I] SQLite3 Supported
2017/01/08 09:53:37 [I] Run Mode: Production
2017/01/08 09:53:38 [I] Listen: http://0.0.0.0:3999
```

after having reverted to the previous version by renaming the backup-folder, the previous version stated immediately, without issues (via service gogs start).

Now, it might be of interest to learn, that obviously, the newer version tried to create / modify a wrong version of the file .gitconfig, named as **.gitconfig:**

"ls -al" in the home directory fo the gituser shows, that there was a new file created with the name "*.gitconfig:*"

```
-rw-r--r--  1 gituser@git.some-it.net some-it   89 Jan  8 09:53 .gitconfig
-rw-r--r--  1 gituser@git.some-it.net some-it    0 Jan  8 09:33 .gitconfig:
```

**Comment by Unknwon** [comment]
Hi, I think maybe the 'user' of your system daemon does not correct permission to access the file.

And the operation to `.gitconfig` file is done via Git itself, not directly from Gogs, you might want to check about that as well.
