### ISSUE TITLE
Move to new Server

### ISSUE THREAD

**Issue by Metti9** [gogits/gogs#4024]
Hallo ,
i have Ubuntu 16.04 and i will move to a new Ubuntu Server, how can i do that ?

**Comment by Fastidious** [comment]
@Metti9 copy the repositories to their final destination on new server. Install `gogs` as you did on old server. On the [configuration](https://github.com/gogits/docs/blob/master/en-US/installation/configuration_and_run.md), set the `repository` to point where yours are. Done.

You might need to fiddle with permissions (never done a migration myself), but troubleshooting should be fairly easy. Alternatively, you could simply start from scratch on the new server and fork your repositories to it.

**Comment by FSMaxB** [comment]
@Fastidious I doubt that this will take care of all the user accounts, settings, issues and pull requests. The database needs to be migrated as well. (don't ask me how to do that).

**Comment by Fastidious** [comment]
@FSMaxB duh, indeed! I forgot about the one, as I have run a one user only `gogs` always. The DB migration will depend on the DB used. Beyond my knowledge as well. Sorry! 😔

**Comment by Metti9** [comment]
i have only 2 users, the root an the gogs, can i only copy the db ?

**Comment by georgesuba** [comment]
@Metti9 what database you used? slqite or mysql? migrating is very easy process, also on old server did you run gogs as git user or gogs user? once you know those answers it would be trivial to move installation from one server to another.

**Comment by Metti9** [comment]
@georgesuba  i have sqlite and run as git user, i have install gogs and copy the gogs from the old server to the new server, now i get this error " [...s/routers/install.go:69 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)" by running ./gogs web

**Comment by georgesuba** [comment]
@Metti9 hi, did you used same settings on old install as well? you know git user and sqlite database or you did had running gogs on old server with mysql and as root user? it seems to me that you had used mysql.

In case you did run it with mysql and as root you will have to migrate this to same settings like on old server then you export db from phpmyadmin and import it to new server. with repositories folder (you just copy that folder to another server into same location. If you would like to switch from mysql database to sqlite, best option would be to do repo by repo manually or with some shell script.

**Comment by Unknwon** [comment]
When I move to a new server, just copy over everything from old server to the new one with exact same path (database name, password, etc.) for everything, and Gogs will just work as before.

But if you have some path changed, you would have to pay special attention about that.

**Comment by lindexi** [comment]
When change the path ,gogs can be push for the hooks/update use the path.
