### ISSUE TITLE
Referencing issues across repositories in organization

### ISSUE THREAD

**Issue by asgozzi** [gogits/gogs#4025]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: unknown
- Operating system: unknown NAS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/testorg2017/OrgRep1/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist: n/a

## Description

Referencing issues logged in another repository does not work when repositories belong to an organization.

See https://try.gogs.io/testorg2017 :

* organization has two repositories, OrgRep1 and OrgRep2
* created issue number 1 in OrgRep2 (https://try.gogs.io/testorg2017/OrgRep2/issues/1)
* created issue in OrgRep1 (https://try.gogs.io/testorg2017/OrgRep1/issues/1) and used syntax

> organization/repository#issue_no

Auto-generated link points to *https://try.gogs.io/t/issues/e* which is obviously incorrect

Is this the expected behavoir?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
