### ISSUE TITLE
500 error when add new issue with picture

### ISSUE THREAD

**Issue by agamem** [gogits/gogs#4026]
- Gogs version (or commit ref):   0.9.113.1223
- Git version: 2.11.0
- Operating system:  Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist:
2017/01/10 10:59:05 [D] Session ID: 570a423c60ca3af3
2017/01/10 10:59:05 [D] CSRF Token: IOCcoAPdcvNZRCWdhOAsXGtpStc6MTQ4Mzk1NjYxMDY3MzAxMTMyNA==
2017/01/10 10:59:05 [T] New attachment uploaded: c5e1b80b-b137-4330-879e-3178036ca4d7
[Macaron] 2017-01-10 10:59:05: Completed /issues/attachments 200 OK in 47.389833ms
[Macaron] 2017-01-10 10:59:10: Started POST /emugroup/v6emuwithportal/issues/new for 10.45.18.12
2017/01/10 10:59:10 [D] Session ID: 570a423c60ca3af3
2017/01/10 10:59:10 [D] CSRF Token: IOCcoAPdcvNZRCWdhOAsXGtpStc6MTQ4Mzk1NjYxMDY3MzAxMTMyNA==
2017/01/10 10:59:10 [...outers/repo/issue.go:436 NewIssuePost()] [E] NewIssue: newIssue: getAttachmentsByUUIDs [uuids: [c5e1b80b-b137-4330-879e-3178036ca4d7]]: no such column: uuid
2017/01/10 10:59:10 [D] Template: status/500
[Macaron] 2017-01-10 10:59:10: Completed /emugroup/v6emuwithportal/issues/new 500 Internal Server Error in 29.139349ms
## Description
When I create a new issue with a picture (drag or add), get a 500 error from gogs.
Logs above. 
...

**Comment by Unknwon** [comment]
This is fixed issue in `master`, make sure you have `go get -u -v github.com/go-xorm/xorm` when you install from source code.
