### ISSUE TITLE
FastCGI protocol is (essentially) useless

### ISSUE THREAD

**Issue by Olipro** [gogits/gogs#4029]
The FastCGI protocol in its current state is essentially useless as a result of no object being passed to the Fcgi instance - this causes it to use stdin/out which is not a particularly reasonable way to use it.

The unix protocol should arguably be removed from the protocol list and Gogs should instead determine whether or not the user wants a TCP socket or unix based on the binding URI. Whether the socket is either of the aforementioned things is independent of it being HTTP or FastCGI.

**Comment by Unknwon** [comment]
Thanks for feedback, but I think you should probably discuss this on https://discuss.gogs.io/ not here..
