### ISSUE TITLE
Editing Comments Removes All Linebreaks

### ISSUE THREAD

**Issue by atom0s** [gogits/gogs#4030]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

- Gogs version (or commit ref): v0.9.113 @ 2016-12-24
- Git version: 2.10.2.windows.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

When you attempt to edit some one elses comment within an issue report, the editor always removes all line breaks smashing the entire report into a single paragraph making it extremely annoying to edit issues or add onto them if need be.

**Comment by Unknwon** [comment]
Thanks for the report, but I can't reproduce, maybe you just need to upgrade your Gogs instance.
