### ISSUE TITLE
[critical] Option to disable local server path import

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#4033]
- Gogs version (or commit ref): v0.9.113
- Operating system: Debian

In the migration settings it is stated that also **local server paths** can be migrated! It explicitly states **local** server paths.

So, but, ... why should I want it!?
When you provide a public Gogs instance this might mean that anyone could import any locally stored git repo or so.

Generally it is a bad idea to allow any (potentially malicious) user to access any local server files, which they can request. Fortunately `/etc` is usually not git repo, otherwise they could have accessed `/etc/passwd` too.

So at least make that thing configurable, but I also recommend you to deactivate it by default. Who needs such a strange feature anyway?

**Comment by bkcsoft** [comment]
As your gogs-server shouldn't run anything else, and we've concluded in other issue-threads that file-level permissions is outside the scope of Gogs, this really isn't that critical. And like you said, the possibility of finding a valid git-repo on any random server isn't that high, and most likely won't include `/etc/passwd`...

**Comment by rugk** [comment]
That's no excuse at all. If there is a repo on the server you cannot say "hey we don't care, usually not there".
Also you cannot claim that there would nothing else on the server. Gogs is an all application for self-hosting and thus or us quite likely that also other things are dine in the server. That's not your decision, that's the decision of the sysadmin. So such a feature here should not be enabled by default.

**Comment by dexter2cz** [comment]
> Fortunately /etc is usually not git repo ...

A lot of sysadmins use "etckeeper", which is just a git in /etc directory ... So, when sysadmin is stupid and lazy and gogs runs as root, you can easily import /etc/.git as local path and gets literally everything.

**Comment by dchest** [comment]
It also makes possible for users with "import local repositories" permission to read any other user's private repositories.

**Comment by rugk** [comment]
Okay, as it was revealed, I think it does not make sense to hide this issue any more. I think this is what https://github.com/gogits/gogs/issues/4006 is basically about.
This issue/request here however goes beyond the other issue as I want an option to completely disable this unnecessary, insecure feature. (& disable it by default)

/cc @RodenLuo

**Comment by Unknwon** [comment]
Thanks for the feedback!

You have to be admin or given permission explicitly by admin in order to clone by local path: https://github.com/gogits/gogs/blob/master/models/user.go#L178-L180

So I don't consider this is an issue.

**Comment by dchest** [comment]
Please reconsider: admin of gogs instance is not equivalent to admin of the server on which it runs.

**Comment by Unknwon** [comment]
Good point. But *admin* is currently the role has highest access level in Gogs, so I would rather recommend running Gogs under a specific user (such as `git`) which has no access to critical directories like `/etc`.

Correct me if I understand wrongly about linux directory permission.

**Comment by dchest** [comment]
You are correct about different user permissions: the attacker will only be able to access repositories which the `gogs` instance user can access. However, this is still an attack vector which is most likely not obvious to the admins, the bare minimum would be to add description of it somewhere (the better way is to disable it by default and add it as an option to .ini).

**Comment by Unknwon** [comment]
>However, this is still an attack vector which is most likely not obvious to the admins

This sounds more like social engineering which is out of range of Gogs.

> the bare minimum would be to add description of it somewhere

Add a quick description about who could import repository by local path would be good?

**Comment by rugk** [comment]
Also note that all mayor Linux distros allow read-access to (if we stay with the example) `/etc`, e.g. because it is needed for `/etc/passwd` for every user. So you cannot rely on the restrictions imposed by user permissions.

**Comment by Unknwon** [comment]
@rugk good point, I'll reopen the issue.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch. See detail in [commit](https://github.com/gogits/gogs/commit/ae319da5fd91c102b387296f9884401e120f9b79).

User who is not allowed to import by local path will see:

![image](https://cloud.githubusercontent.com/assets/2946214/22353763/0f2a418c-e3f0-11e6-8d2a-8adcaffbbd8e.png)

User who is allowed:

![image](https://cloud.githubusercontent.com/assets/2946214/22353774/1bc50c88-e3f0-11e6-806a-adf760f35671.png)

**Comment by dchest** [comment]
@Unknwon looks good, thank you!
