### ISSUE TITLE
Repo URL box showing localhost instead of the domain name

### ISSUE THREAD

**Issue by OkTekk** [gogits/gogs#4035]
- Gogs version (or commit ref): 0.9.115.0103
- Git version: 2.7.4-0ubuntu1
- Operating system: Ubuntu 16.04.1
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

Hi, 

Like the title said, i'm a bit lost.
I imported a repo, then when i'm on it's page, the repo url box (both HTTP and SSH entries) show something like : 
http://localhost:3000/lowlow/vrac.git

where it should show : 
http://git.stfu.be/lowlow/vrac.git (sorry for that, in french stfu means nothing especially)

I'm struggling with this 1st dedicated host so it might only be an error of config/dns/proxy or stuff like that but even after looking on the web since this morning... nothing came up to help my case.

Any ideas/advices ?

**Comment by tobias--** [comment]
Hi @OkTekk,

make sure to set ROOT_URL and DOMAIN under [server] in custom/conf/app.ini e.g.:

    [server]
    DOMAIN       = git.stfu.be
    HTTP_PORT    = 3000
    ROOT_URL     = http://git.stfu.be:3000/

You might also want to have a look at the [config cheat sheet](https://gogs.io/docs/advanced/configuration_cheat_sheet)

**Comment by OkTekk** [comment]
I use a virtual host for reroute http://stfu.be:3000/ to http://git.stfu.be/ with that:

```
<VirtualHost *:80>
    ServerName git.stfu.be
    ServerAlias git.stfu.be
    ProxyPreserveHost On

    # setup the proxy
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

So.. it would be : 
```
[server]
DOMAIN       = git.stfu.be
HTTP_PORT    = 3000
ROOT_URL     = http://git.stfu.be/
```

Or : 
```
[server]
DOMAIN       = git.stfu.be
HTTP_PORT    = 80
ROOT_URL     = http://git.stfu.be/
```

?

Thanks for your answer anyway!

**Comment by OkTekk** [comment]
Ok, the late one (virtual port : 80) and DOMAIN stfu.be it seems (it works anyway).
Many thanks !
