### ISSUE TITLE
Error 404 when creating a pull request on branch "develop"

### ISSUE THREAD

**Issue by smiquee** [gogits/gogs#4038]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 1.8.3.1
- Operating system: RHEL7.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io: ** => unable to create a repository on it **
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

2017/01/16 16:16:53 [...uters/repo/commit.go:230 CompareDiff()] [E] GetCommit: exit status 128 - fatal: ambiguous argument 'USER': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

## Description

You fall in a 404 error when trying to do a pull request on a "develop" branch.
What is very strange is that it appears only when the branch you want to compare in the origin repository is named "develop". I tried other combinations, and don't fall in this error. I'll try to check with different git versions.
...

**Comment by smiquee** [comment]
It is the same error with git 2.7.4

**Comment by Unknwon** [comment]
Hi, have you tried latest `master` branch with install from source code? Because this issue is fixed.

**Comment by smiquee** [comment]
It is fixed by build 0.9.128 :)
