### ISSUE TITLE
try.gogs.io - unable to create repository

### ISSUE THREAD

**Issue by pyhedgehog** [gogits/gogs#4039]
- Gogs version (or commit ref): 0.9.115.0103
- Git version: NA
- Operating system: NA
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes - POST https://try.gogs.io/api/v1/user/repos
  - [ ] No
  - [ ] Not relevant

## Description

On attempt to create new repository (under user [git-repo-test](https://try.gogs.io/git-repo-test)) I have either "`502 Bad Gateway`" or following error:
```
{"message":"initRepository: InitRepository: fork/exec /usr/bin/git: too many open files",
 "url":"https://github.com/gogits/go-gogs-client/wiki"}
```

**Comment by Unknwon** [comment]
Thanks for the report, this is fixed now.

**Comment by guwan** [comment]
Restart gogs can solve the same problem for me
