### ISSUE TITLE
Keeps calling http://<example.com>/user/undefined

### ISSUE THREAD

**Issue by jspatel** [gogits/gogs#4040]
The issue will be closed without any reasons if it does not satisfy any of following requirements:
- Gogs version (or commit ref):  0.9.115.0103
- Git version: 
- Operating system: Ubuntu x64 16.04 LTS
![image](https://cloud.githubusercontent.com/assets/8227572/22002765/4fd48156-dc03-11e6-9dda-1f66fbb26925.png)

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

somehow it keeps calling the http://<example.com>/user/undefined.
Somehow some variable is set to undefined for the web application.
This results in 404 page after login. However clicking on a dashboard works fine.

This is not an issue with other server I installation instance I tried. 
...

**Comment by Unknwon** [comment]
>somehow it keeps calling

What is **it**?

**Comment by jspatel** [comment]
For that installation something got messed up. But I guess it is no longer an issue after a fresh install on a new server.
