### ISSUE TITLE
SSH 客户端连接报 Could not read from remote repository 请问如何设置？

### ISSUE THREAD

**Issue by kaaann** [gogits/gogs#4041]
Connection closed by 192.168.1.252
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

服务器：
windows server 2008 R2

客户端：
windows 7

gogs 里设置了SSH 密钥

每次链接都会报这个问题，
请问有没有思路提供？THX

**Comment by Unknwon** [comment]
Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by kaaann** [comment]
thx try it
