### ISSUE TITLE
Inconsistency in path handling breaks pull requests when running as Windows service

### ISSUE THREAD

**Issue by pjt33** [gogits/gogs#4042]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: 2.11.0.windows.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: `2017/01/17 17:29:15 [...routers/repo/pull.go:700 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: git apply --check: chdir data/tmp/local-rpeo/1: The system cannot find the file specified. - chdir data/tmp/local-rpeo/1: The system cannot find the file specified.`

## Description

I am running Gogs as a Windows service as described in the section "Use Builtin Functionality" of [the installation notes](https://gogs.io/docs/installation/run_as_windows_service).

I can create repositories, fork, clone over http, and push over http. However, when I try to make a pull request from my fork I get an error 500 and the above log message.

If I look at the file system, `c:\gogs\data` contains `avatars` and `sessions`, both of which have content. However, there is no `c:\gogs\data\tmp`. On the other hand, there is a `c:\Windows\System32\data\tmp\local-rpeo\1` which seems to be a checkout of the parent repository's `master` branch. As it happens, a Windows service will run in `c:\Windows\System32` unless it changes its working directory.

My conclusion is that the relative path `data\tmp\local-rpeo\1` is being treated relative to the working directory of the running process for the step which clones a copy, but it's being treated relative to the directory containing `gogs.exe` for the step which runs `git apply --check`.

### Workaround

If I create a batch script

    @echo off
    cd c:\gogs
    c:\gogs\gogs.exe web --config c:\gogs\custom\conf\app.ini

make that the `binPath` of my service, and restart the service then the pull request is created successfully and I then see a clone of the parent repo's master in `c:\gogs\data\tmp\local-rpeo\1`. This gives me a workaround until the bug is fixed, but it also seems to confirm my interpretation of what's happening.

I think it's debatable whether there is one bug here or two. It's definitely a bug that the various operations in the pull request process are treating the same (internally generated) relative path as different absolute paths; it's arguably a separate bug that the `.exe` doesn't change its working directory when run as a Windows service.

**Comment by Unknwon** [comment]
By default the app data path to relative to where Gogs binary sits, in your case, you could change [this config option](https://github.com/gogits/gogs/blob/master/conf/app.ini#L137) to a absolute path, and should solve the issue.

**Comment by pjt33** [comment]
I added `STATIC_ROOT_PATH = c:/gogs`  to the `[server]` section of my custom `app.ini`, deleted `c:\Windows\System32\data`, and restarted the service. No luck. It recreated the directory in `System32` and created `tmp\local-rpeo` etc. under that directory.

I also tried `STATIC_ROOT_PATH = c:/gogs/` with the same lack of success.

**Comment by Unknwon** [comment]
I'm pretty much confused by what you're describing. What was the core problem here? What are you trying to achieve?

**Comment by pjt33** [comment]
The core problem was that pull requests were broken. Forcing `APP_DATA_PATH` to an absolute value seems to be a workaround.

However, the investigation of the core problem showed that its root was that when Gogs is run as a Windows service using built-in functionality it writes some of its own temporary data in a directory which really belongs to the operating system. The closest *nix analogy would be that it defaults to writing session data and temporary checkouts into `/lib`. Forcing `APP_DATA_PATH` fixes the one which is immediately visible because it breaks things in an obvious way, but it doesn't fix the root cause, and other parts of the system continue to effectively use `/lib` as `/tmp`. A full *workaround* for the root cause may be possible by setting various values in `app.ini`, but a full *fix* probably requires a `chdir`.

**Comment by Unknwon** [comment]
Thanks for clarifying! So if I understand correctly, the original problem for this issue is solved.

>The closest *nix analogy would be that it defaults to writing session data and temporary checkouts into /lib. 

This would be another issue to take a look at, feel free to file another issue.
