### ISSUE TITLE
Can not install with MySQL 8.0.0 ?

### ISSUE THREAD

**Issue by edoger** [gogits/gogs#4045]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): V0.9.113
- Git version: 2.10.1 (MacOS) / 1.8.3.1 (CentOS 7)
- Operating system: Mac OS 10.12.2 / CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ X] No
  - [ ] Not relevant
- Log gist:

## Description

Output Message:
[...s/routers/install.go:67 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *string

I've tried the production line server and the local computer.

**Comment by marno2703** [comment]
Why closed? One year later I can't see gogs working with mysql-server 8.
