### ISSUE TITLE
Unable to create mirror in Windows

### ISSUE THREAD

**Issue by aardila** [gogits/gogs#4048]
- Gogs version (or commit ref): 0.9.113
- Git version: 2.8.3.windows.1
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log :
```
2017/01/20 11:16:55 [I] Log Mode: File(Info)
2017/01/20 11:16:55 [I] Cache Service Enabled
2017/01/20 11:16:55 [I] Session Service Enabled
2017/01/20 11:16:55 [I] Git Version: 2.8.3
2017/01/20 11:16:55 [W] Clean up repository temporary data [data\tmp]: exit status 2
2017/01/20 11:16:55 [I] SQLite3 Supported
2017/01/20 11:16:55 [I] Run Mode: Production
2017/01/20 11:16:55 [I] First-time run install finished!
2017/01/20 11:16:55 [I] New random avatar created: 1
2017/01/20 11:17:21 [W] Delete repository wiki [I:user\repo.wiki.git]: exit status 2
2017/01/20 11:17:21 [.../gogs/models/repo.go:328 DeleteWiki()] [E] CreateRepositoryNotice: database table is locked
2017/01/20 11:17:21 [W] Delete repository wiki [data\tmp\local-wiki\1]: exit status 3
2017/01/20 11:17:21 [.../gogs/models/repo.go:328 DeleteWiki()] [E] CreateRepositoryNotice: database table is locked
```

## Description

When trying to create a mirror using a local path in Windows, it errors with

> Migration failed: Clone: exit status 128 - fatal: failed to create directory '`I:user\repo.git/objects`': No such file or directory fatal: The remote end hung up unexpectedly `

where `user` is my gogs username and `I` is a mapped network drive.

Clone address provided: `I:/repo.git`
Repository root provided during initial setup: `I:/`
Relevant section from `app.ini`:
```
[repository]
ROOT = I:/
```

What the configuration page (i.e. localhost:3000/admin/config) shows:

**Repository Root Path**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I:

I see two problems:

1. The slash after the root is missing
1. The backslash after the git username in the path makes it mixed Windows- and Unix-style, whereas everything else in the config file seems to be exclusively Unix-style.

Tying to create the mirror with `I:\repo.git` (instead of `I:/`) also fails with the same error.

Could be related to #4031. However, no gogs version was provided in that issue and the error therein seems to happen under different circumstances. But the issue with Windows separators seems to be there since much longer... #1028

**Comment by Unknwon** [comment]
Hi, I just pushed a patch to first fix the database-lock thing. Can you build from `develop` source code and report back what is still going wrong?

**Comment by aardila** [comment]
Hi, thanks fir the response. I won't have a chance to try this out fir the next couple weeks, unfortunately

**Comment by Unknwon** [comment]
Ah, that's sad. You can report back when you have chance. I'm closing it for now.
