### ISSUE TITLE
Show full path for folder with only one subfolder

### ISSUE THREAD

**Issue by Jofkos** [gogits/gogs#4049]
In Java projects you often have long paths where folders with only one subfolder follow folders with only one subfolder. It'd be nice if you didn't have to click through every single subfolder to get to the actual code.
File structure:
![https://i.imgur.com/PfQUewo.png](https://i.imgur.com/PfQUewo.png)

A solution could be what github does and link to the full path instead to the next subfolder.

Example:  
![Github Example](https://i.imgur.com/3qpUTLV.png)
(Example on Github: [BungeeCord protocol](https://github.com/SpigotMC/BungeeCord/tree/master/protocol))

**Comment by Unknwon** [comment]
Thanks your feedback, but I think this is duplicated to https://github.com/gogits/gogs/issues/1149.
