### ISSUE TITLE
Issues with new PRs

### ISSUE THREAD

**Issue by juan-manuel-alberro** [gogits/gogs#4050]
- Gogs version (or commit ref): latest 
- Git version: 2.1.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
I have this error message in all the pull request that I opened

![image](https://cloud.githubusercontent.com/assets/7114488/22163263/e637599a-df30-11e6-9006-3a77e9d387ba.png)

My master and my code are OK, I just uploaded my code into Bitbucket to verify if there´s some issues with the code but it works in that other site. Also I tried adding a new repository but it didn't work.
Any clue? 
Thanks.

PS: all my branches are rebase with master, the PR it fails even if I add a new empty file to the branch.

**Comment by Unknwon** [comment]
There might be errors, please close and reopen the PR and wait about 10seconds, then post the logs (from `gogs.log`) produced to here.
