### ISSUE TITLE
Display welcome message when testing ssh key

### ISSUE THREAD

**Issue by CWempe** [gogits/gogs#4051]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I think it would be nice to see some kind of welcome message when you test the ssh connection .

When doing this for GitHub you get this:

> Hi username! You've successfully authenticated, but GitHub does not
provide shell access.

see: https://help.github.com/articles/testing-your-ssh-connection/

With Gogs I get:
> ssh_exchange_identification: Connection closed by remote host

As a user with limited experience it is hard to tell if this is a positive or negative message.

...

**Comment by CWempe** [comment]
Sorry.
My bad.

It already works as expected.

**Comment by twkiba** [comment]
i'm seeing this message right now, do you remember what was the issue ?

**Comment by CWempe** [comment]
Sorry, I do not remember.
But I would have posted more information if it was usefull.
