### ISSUE TITLE
issue tracker shows unreachable issues

### ISSUE THREAD

**Issue by msh1n0** [gogits/gogs#4052]
- Gogs version (or commit ref):  0.9.113.1223
- Git version: -
- Operating system: Windows 8.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No, I can't create a repo there
  - [ ] Not relevant
- Log gist:

## Description
I created a repo and some issues for it, but deleted the repo later
the issues were still listed on my account overview but when I clicked on them, I got error 500
the issues should not be there since the repository doesn't exist anymore

I helped myself by deleting the datasets from issues, issues_user and by changing back the value of num_issues of the repository manually

**Comment by Unknwon** [comment]
Hi, you're able to create repository on demo site now, can you help reproduce it?

**Comment by msh1n0** [comment]
I just tried it but somehow it won't happen again, on my system neither. 
As it happened here the server was at a pretty clean state, It was a fresh installation and only had one single repository with two issues saved on it. I will try to retrace the steps I made. If I find out something, I will let you know

**Comment by Unknwon** [comment]
OK sounds great. I'll close the issue until it happens again.
