### ISSUE TITLE
Deployment key has access to all public repositories

### ISSUE THREAD

**Issue by asenci** [gogits/gogs#4058]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: 2.1.4
- Operating system: Debian Jessie 8.7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

Note sure if this was the intended behavior, but adding a deployment key to a repository will allow access to all public repositories. Even with "Require Sign In View" enabled.

Example scenarios:
Public repository with deployment key: https://try.gogs.io/asenci/test1
Public repository with no deployment key: https://try.gogs.io/asenci/test2
Private repository with no deployment key: https://try.gogs.io/asenci/test3
Private repository with deployment key: https://try.gogs.io/asenci/test4

I would expect the deployment key to have access to "test1" and "test4", but it actually has access to "test2" as well:

```
$ git clone git@try.gogs.io:asenci/test1.git
Cloning into 'test1'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), done.
Checking connectivity... done.
```

```
$ git clone git@try.gogs.io:asenci/test2.git
Cloning into 'test2'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), done.
Checking connectivity... done.

```
```
$ git clone git@try.gogs.io:asenci/test3.git
Cloning into 'test3'...
Gogs: Key access denied
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
```
$ git clone git@try.gogs.io:asenci/test4.git
Cloning into 'test4'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), done.
Checking connectivity... done.
```

This is specially confusing with "Require Sign In View" enabled, since I wouldn't expect "test2" to be accessible, despite it being a "public" repository.

**Comment by Unknwon** [comment]
Thanks your feedback!

In my opinion, 

1. For public repositories, deployment key is not as useful as private repositories unless **require sign in** is enabled.
2. The purpose of **require sign in** is only allow signed in users to view site content.
3. If the server has valid deployment key, then it is considered as signed in user. So **require sign in** should not make any differences for the server that has valid deployment key.

Unless, you're arguing that the server should only be allowed to clone repositories which bind to given deployment key.

**Comment by asenci** [comment]
I was expecting the deployment key to be bound to the repository not treated as an authenticated user, but I did some tests on GitHub and Bitbucket for comparison and they both show the same behavior. So I can't see any reason for changing it.

**Comment by Unknwon** [comment]
>I did some tests on GitHub and Bitbucket for comparison and they both show the same behavior.

Thanks for the research, I think we can close the issue now.
