### ISSUE TITLE
Please confirm the httphead is correct?

### ISSUE THREAD

**Issue by binarization** [gogits/gogs#4059]
- Gogs version (or commit ref): v0.9.113 @ 2016-12-24
- Git version: 
- Operating system: Ubuntu Server LTS 16.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io/:
  - [x] Yes (https://try.gogs.io)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When I checked the response header, I found that the server returned a _HTTP/1.1 404 Not Found_. I've been looking for my own mistakes, but I checked that the page is still working. Finally, I found all of your pages are the same httphead (just 404).
I'm not sure if it was designed on purpose. Please confirm.

Try
```
$ curl -I https://try.gogs.io/
```

**Comment by Unknwon** [comment]
Thanks your feedback, but this is duplicated to https://github.com/gogits/gogs/issues/2857.
