### ISSUE TITLE
500 Error on merge request

### ISSUE THREAD

**Issue by sjroh** [gogits/gogs#4062]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) : https://try.gogs.io/sjroh/error_reproduce/src/reproduce_error
  - [ ] No
  - [ ] Not relevant
- Log gist: None

## Description
Below steps are what I've done.
1. Make a branch from the master branch, call it slave_branch.
2. Update slave_branch.
3. Do below sub steps.
3-1. Click "New Pull Request" from the web application.
3-2. Type title, content, and attach any image file.
3-3. Click "Create Pull Request", which is submitting pull request.
4. Gogs web application showed me 500 error.

However, below steps don't make any 500 error.
1. Make a branch from the master branch, call it slave_branch.
2. Update slave_branch.
3. Do below sub steps.
3-1. Click "New Pull Request" from the web application.
3-2. Type title, content.
3-3. Click "Create Pull Request", which is submitting pull request.
4. Pull Request created.
5. Add a comment and attach an image file.
6. Comment uploaded with attached image, no 500 error.

Thanks.

**Comment by Unknwon** [comment]
Hi there, please do `go get -u github.com/go-xorm/xorm` and recompile Gogs, the issue then should be solved.

Demo site forgot to do so but updated now.

**Comment by sjroh** [comment]
Thank you for your fast reply.
I installed gogs by using binary file for the Windows.
As I understand, I need to download the source, and recompile it with the command you gave.
Is this correct?
Thank you for your time.

**Comment by Unknwon** [comment]
Correct, you can refer to https://gogs.io/docs/installation/install_from_source.

Or as you know how to get around with this issue already, you can wait until next release which should be in 1-2 weeks.

**Comment by sjroh** [comment]
Ok, this was very helpful.
Thank you very much.
