### ISSUE TITLE
Markdown file rendering is broken ("<Str2html>: wrong type for value; expected string; got template.HTML")

### ISSUE THREAD

**Issue by sometimesfood** [gogits/gogs#4063]
- Gogs version (or commit ref): 0.9.113, 0.9.119
- Git version: any (tested with 2.1.4)
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes: https://try.gogs.io/test_user123/demo_public/src/master/hello.md
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Markdown file rendering is broken for non-README files. Attempting to view markdown files results in the following error message:

```
template: repo/view_file:41:40: executing "repo/view_file" at <Str2html>: wrong type for value; expected string; got template.HTML
```

This behaviour can be reproduced by adding a markdown file to a repository:
```
touch hello .md
git add hello.md
git commit -m 'Add hello.md'
git push
```

**Comment by sometimesfood** [comment]
This seems to be working as expected in gitea:

https://try.gitea.io/test_user123/demo_public/src/master/hello.md

**Comment by Unknwon** [comment]
Thanks for the report, it's now fixed!
