### ISSUE TITLE
Pull request cannot pull from other branch in forked repo itself

### ISSUE THREAD

**Issue by RodenLuo** [gogits/gogs#4066]
- Gogs version (or commit ref): 0.9.115.0103
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
After I forked a repo, when I tried to create a pull request, it redirected to the original repo. And I can only compare between forked and original repos, but not inside the forked repos between two branches.

Thanks!

## Screenshots

Gogs implementation:

![image](https://cloud.githubusercontent.com/assets/8460424/22401087/2bb1d8c8-e57c-11e6-8d3c-2efeaaea63a1.png)

GitHub's implementation

![image](https://cloud.githubusercontent.com/assets/8460424/22401107/9fac1b08-e57c-11e6-90af-d13135735f48.png)

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogits/gogs/issues/2770.
