### ISSUE TITLE
Clean up repository temporary data [data\tmp]: exit status 2

### ISSUE THREAD

**Issue by ddatsh** [gogits/gogs#4069]
- Gogs version (or commit ref): 0.9.113.1223 
- Operating system: win10

## Description
win下gogs的data目录结构中,默认不会有tmp目录
gogs web启动后，系统提示管理 ,每次必提示 	Clean up repository temporary data [data\tmp]: exit status 2

**Comment by Unknwon** [comment]
Cause: Windows treats delete target not exist as an error
Solution: Ignore delete operation on Windows if the target does not exist.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
