### ISSUE TITLE
Use systemd instead of upstart on Ubuntu 16.04

### ISSUE THREAD

**Issue by jhasse** [gogits/gogs#4072]
While Ubuntu 16.04 was enabled at packager.io by #3617, the package is still using upstart, but Ubuntu 16.04 switched to systemd.

Existing systemd service file: https://github.com/gogits/gogs/blob/master/scripts/systemd/gogs.service

**Comment by Unknwon** [comment]
Thanks for asking, but I think that's beyond the control of this repository.. You can possible contact admin of https://packager.io/.
