### ISSUE TITLE
Small problem with translated dates in issues or pull requests

### ISSUE THREAD

**Issue by ogarcia** [gogits/gogs#4073]
- Gogs version: latest commit
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/testador/test/issues/1)
  - [ ] No
  - [ ] Not relevant

## Description

If you set your browser in foreing language (spanish for example) you can see that dates in pull requests or issues have some bad code.

An small screen capture:
![captura](https://cloud.githubusercontent.com/assets/572924/22501242/3e209780-e868-11e6-8d51-312f6ea92824.png)

In english the HTML code is:
```
<span class="text grey"><a href="/testador">testador</a> commented <a href="#issue-1804"><span class="time-since" title="Wed, 01 Feb 2017 04:10:34 EST">8 minutes ago</span></a></span>
```

But in spanish it appear as:
```
<span class="text grey"><a href="/testador">testador</a> 'comentado <a href="%!(EXTRA string=issue-1804, template.HTML=<span class="time-since" title="Wed, 01 Feb 2017 04:10:34 EST">hace 8 minutos</span>)</span>
```

I think that must be an small problem with function that presents this piece of code.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by ogarcia** [comment]
@Unknwon Yes, but there is a `'` at end of `%s` chain that is unnecessary.

This would be the change:
```diff
-issues.commented_at=`comentado <a href="#%s"> %s'</a>`
+issues.commented_at=`comentado <a href="#%s"> %s</a>`
```

**Comment by Unknwon** [comment]
Approved, will update to main repo soon.
