### ISSUE TITLE
PR on same repository shows 404

### ISSUE THREAD

**Issue by SeaLife** [gogits/gogs#4074]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

- Gogs version (or commit ref): develop, 0.9.130.0131 (docker)
- Git version: 2.6.6 (docker exec -it gogs-r3ktm8 git --version)
- Operating system: (docker, host system Ubuntu 16.10)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Hello,

i was going to make a pull request in the same repository (from develop -> master) and it showed me a 404 Error.

I tried the same on try.gogs.io, same result there: https://try.gogs.io/SeaLife/Arma3-SlottingTool/compare/master...SeaLife:develop

Related Issues:
* #1597

Steps to reproduce:
* Go to Repository
* Click on the "Create Pull-Request green button thing" (stay on master while doing this)
* Select other Branch 'e.g. develop in my case'
* error 404.

Regards
SeaLife

**Comment by SeaLife** [comment]
I tried something out...

if i remove the SeaLife: in develop it works.

https://try.gogs.io/SeaLife/Arma3-SlottingTool/compare/master...develop

Regards
SeaLife

**Comment by techzilla** [comment]
No url with branches resolve correctly, so far only seeing 404s.

**Comment by willy0275** [comment]
I don't want to sound rude but is this project even tested? I can't believe something as big made it through a new release. We're also getting 404 when trying to delete a branch after merge, and when it sometimes work it deletes develop instead of the current branch.

**Comment by Unknwon** [comment]
@willy0275 you're looking for this: https://github.com/gogits/gogs/issues/4089

**Comment by willy0275** [comment]
Thank you, yes. There should really some functional tests implemented in gogs because it seems the URL system is very shacky and developers introduce bugs too easily without any test triggering.

**Comment by Unknwon** [comment]
@willy0275 indeed, thanks for bring this up :smiley:

But discussion here might not be the best choice.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/SeaLife/Arma3-SlottingTool/compare/master...SeaLife:develop.

**Comment by SeaLife** [comment]
Hi,

i updated my gogs and tested it out. Works like a charm now :)

Thanks <3

Regards
SeaLife

**Comment by willy0275** [comment]
Yes we updated this morning and creating a PR now works. Thanks all. Now if you guys could support deleting branches with "/" in the branch name, instead of getting a 404, that would be awesome ;-)

**Comment by Unknwon** [comment]
@willy0275 please monitor another thread, should be out before next release.
