### ISSUE TITLE
Error 404 when creating a pull request in same repository

### ISSUE THREAD

**Issue by zongwei007** [gogits/gogs#4075]
- Gogs version (0.9.130.0131): 
- Git version: 
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x ] Yes (https://try.gogs.io/converseblade0/demo/compare/master...converseblade0:dev)
  - [ ] No
  - [ ] Not relevant

## Description
When creating a pull request in same repository, gogs will show a 404 page that compare between master branch and target branch(example 'dev'). The URL of page is `https://try.gogs.io/converseblade0/demo/compare/master...converseblade0:dev`, if change URL to `https://try.gogs.io/converseblade0/demo/compare/master...dev` Gogs will work and can be create a pull request successfully.

**Comment by SeaLife** [comment]
Duplicated, #4074
