### ISSUE TITLE
Build fails on latest master due to update in gogits/git-module

### ISSUE THREAD

**Issue by zlebnik** [gogits/gogs#4076]
- Gogs version (or commit ref): master
- Git version: 1.9.1
- Operating system: Ubuntu 14.04 server
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

Error during build:
models/repo.go:602: cannot use wikiURL (type string) as type git.NetworkOptions in argument to git.IsRepoURLAccessible

This commit: https://github.com/gogits/git-module/commit/172cbc21accbf0085a58fd0832f46a9f694130e8 makes gogs fail to build properly. Not a Go professional, but seems like there should be some kind of hard dependency on specific commit of git-modules.

**Comment by Unknwon** [comment]
Please do `go get -u github.com/gogits/git-module` and recompile.

**Comment by zlebnik** [comment]
Thank you for so fast response and fix!
Now works like a charm
