### ISSUE TITLE
404 on private repositories

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4077]
- Gogs version (or commit ref): 
- Git version:  `N/A`
- Operating system: `N/A` 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL): https://try.gogs.io/Fastidious/Ideas
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

A private repository shows as [404](https://try.gogs.io/Fastidious/Ideas). It should have a definable verbose (“You have reached a private repository, or a repository for which you have not read access”, or something similar).

**Comment by Unknwon** [comment]
Thanks for feedback! 

This has been discussed many times in older issues. This is the exact behavior users should expect in current design of Gogs.

And you can follow https://github.com/gogits/gogs/issues/838.
