### ISSUE TITLE
Login failure depending on where gogs is started

### ISSUE THREAD

**Issue by ericrector** [gogits/gogs#4080]
I have installed gogs on my Pi.  Setup with defaults. Install user was root. bad I know.  So the problem, If I start with:
cd /path/to/gogs
sudo ./gogs web

It starts and I can log in.

In the console window I see:

2017/02/03 13:13:18 [T] Custom path: /usr/sbin/gogs/custom
2017/02/03 13:13:18 [T] Log path: /usr/sbin/gogs/log
2017/02/03 13:13:18 [I] Gogs: Go Git Service 0.9.128.0131
2017/02/03 13:13:18 [I] Log Mode: File(Info)
2017/02/03 13:13:18 [I] Cache Service Enabled
2017/02/03 13:13:18 [I] Session Service Enabled
2017/02/03 13:13:19 [I] Git Version: 2.1.4
2017/02/03 13:13:19 [I] SQLite3 Supported
2017/02/03 13:13:19 [I] Run Mode: Production
2017/02/03 13:13:19 [T] Doing: CheckRepoStats
2017/02/03 13:13:29 [I] Listen: http://0.0.0.0:3000
[Macaron] 2017-02-03 13:13:30: Started POST /user/login for <my-ip-addr>
2017/02/03 13:13:30 [D] Session ID: f6d43fe364a65896
2017/02/03 13:13:30 [D] CSRF Token: <my-token-here>
[Macaron] 2017-02-03 13:13:32: Completed /user/login 302 Found in 1.985037715s
[Macaron] 2017-02-03 13:13:32: Started GET / for <my-ip-addr>
2017/02/03 13:13:32 [D] Session ID: f6d43fe364a65896
2017/02/03 13:13:32 [D] CSRF Token: <my-token-here>
2017/02/03 13:13:32 [D] Template: user/dashboard/dashboard
[Macaron] 2017-02-03 13:13:32: Completed / 200 OK in 452.785634ms

now I start gogs like this:

sudo /path/to/gogs/gogs web

It starts, but when I log in I see:

[Macaron] 2017-02-03 13:21:55: Started POST /user/login for <my-ip-addr>
2017/02/03 13:21:55 [D] Session ID: c667707cf45a64b2
2017/02/03 13:21:55 [D] CSRF Token: <my-token-here>
2017/02/03 13:21:55 [D] Template: user/auth/signin
[Macaron] 2017-02-03 13:21:55: Completed /user/login 200 OK in 110.90502ms

but I get the message "Username or password is not correct."

Has any one else seen this?

Is seems to have to do with where you start gogs from ????

Thanks,

**Comment by Unknwon** [comment]
Please follow the template.

I guess you're using SQLite, use absolute path for database file.
