### ISSUE TITLE
Everyone can see how many pages are there in user pages including private repositories

### ISSUE THREAD

**Issue by Qs-F** [gogits/gogs#4082]
- Gogs version (or commit ref): 0.9.115.0103
- Git version: 2.11.0.193
- Operating system: Ubuntu 14.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (because I can't create over 10 repositories)
  - [ ] Not relevant
- Log gist:

No related logs.

## Description

Without signin, if someone access to the gogs personal page directly(e.g. try.gogs.io/Qs-F), and the user have many private repositories, Prev/Next buttons appears despite of there are no visible contents.

So we can guess round number of how many private repositories the user have.

This is sample image:

![image](https://cloud.githubusercontent.com/assets/8467289/22619853/d7c9b4fe-eb40-11e6-83a8-2c1e59dafdb4.png)

...

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Qs-F** [comment]
Thank you so much:)
I have checked it, and it works accurately.
