### ISSUE TITLE
LibreJS compatibility

### ISSUE THREAD

**Issue by jorgesumle** [gogits/gogs#4084]
https://freepo.st/post/imtju3v7bj#comments

It would be great if Gogs could be compatible with [LibreJS](https://www.gnu.org/software/librejs/). I've started working in making this possible for NotABug.org, but it would be better if I could do that to this repo. Should I make a pull request with this feature here?

It would mean having to distribute not just the minified JavaScript files, but also the source code (for examble, semantic-2.2.1.min.js **and semantic.js**) and creating a link in the footer template pointing to the JavaScript license information table. It could be a hidden link (not visible).

> `<a hidden href="/librejs" data-jslicense="1">JavaScript licenses</a>`

The JavaScript license table would be something like this (assuming it would be in the `gogs/templates` directory). We could call that file `librejs.tmpl`:

```
{{template "base/head" .}}

<table id="jslicense-labels1">
  <tr>
    <td><a href="/js/libs/jquery.are-you-sure.js">jquery.are-you-sure.js</a></td>
    <td>
      <a href="http://www.freebsd.org/copyright/freebsd-license.html">Expat</a>
      <br>
      <a href="http://www.gnu.org/licenses/gpl-2.0.html">GNU-GPL-2.0-or-later</a>
    </td>
    <td><a href="/js/libs/jquery.are-you-sure.js">jquery.are-you-sure.js</a></td>
  </tr>
  <tr>
    <td><a href="/js/semantic-2.2.1.min.js">semantic-2.2.1.min.js</a></td>
    <td><a href="http://www.freebsd.org/copyright/freebsd-license.html">Expat</a></td>
    <td><a href="/js/semantic-2.2.1.js">semantic-2.2.1.js</a></td>
  </tr>
  <tr>
    <td><a href="/js/gogs.js">gogs.js</a></td>
    <td><a href="http://www.freebsd.org/copyright/freebsd-license.html">Expat</a></td>
    <td><a href="/js/gogs.js">gogs.js</a></td>
  </tr>
  <tr>
    <td><a href="/js/libs/">gogs.js</a></td>
    <td><a href="http://www.freebsd.org/copyright/freebsd-license.html">Expat</a></td>
    <td><a href="/js/gogs.js">gogs.js</a></td>
  </tr>
  <tr>
    <td><a href="/plugins/highlight-9.6.0/highlight.pack.min.js">highlight.pack.min.js</a></td>
    <td><a href="https://github.com/isagalaev/highlight.js/blob/master/LICENSE">BSD 3 Clause</a></td>
    <td><a href="/plugins/highlight-9.6.0/highlight.pack.js">highlight.pack.js</a></td>
  </tr>
<!-- It goes on... -->
</table>
{{template "base/footer" .}}

```

For more information on how to make a site compatible with LibreJS read its manual: https://www.gnu.org/software/librejs/manual/librejs.html

**Comment by Unknwon** [comment]
Hi, thanks for the info. I think it's a good idea, as long as along LiberJS allows pointing source code and its license to a different site (Gogs only keeps min version of all other JS).

**Comment by jorgesumle** [comment]
@Unknwon, great! I think that something like this should work:
```
<tr>
    <td><a href="/js/semantic-2.2.1.min.js">semantic-2.2.1.min.js</a></td>
    <td><a href="http://www.freebsd.org/copyright/freebsd-license.html">Expat</a></td>
    <td><a href="https://github.com/Semantic-Org/Semantic-UI/tree/2.2.1">semantic-2.2.1.js</a></td>
</tr>
```
Note that the URL of the source code points to the version tagged 2.2.1 with Git. It must point to the same version of the minified file.

 Tomorrow, I'll test it and work to make the pull request. Now it's sleep time in my time zone.

**Comment by Unknwon** [comment]
OK, no problem, thanks your effort!
