### ISSUE TITLE
When pushing via SSH: input_userauth_error: bad message during authentication: type 20

### ISSUE THREAD

**Issue by sbrl** [gogits/gogs#4085]
(I assume these are for the server...?)

- Gogs version (or commit ref):  0.9.128.0131
- Git version:  git version 2.7.4
- Operating system: Ubuntu 16.04.1 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist: I don't understand what you are asking for here. If you want the relevant log file entries, here they are:

```
gogs[30867]: 2017/02/04 22:38:38 [T] SSH: Handshaking for x.y.z.w:portnumber
gogs[30867]: 2017/02/04 22:38:39 [W] SSH: Handshaking was terminated: EOF
```

## Description
I have changed _nothing_ except updating gogs to the latest release, and now when I attempt to push from my laptop (`uname -a`: `Linux Hostname 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`) via ssh to my gogs server (`uname -a`: `Linux starbeamrainbowlabs.com 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux`), I geet the following error message:

```
Host key fingerprint is SHA256:K/VB82hyTNzYH2suaufGRPWoqSlbN9C9avFk//yspFs
+---[RSA 2048]----+
|                 |
|         . +  .  |
|          * o..o |
|         + =.o.o.|
|        S B.oo=  |
|       . * o=oo. |
|      . . o=+=E. |
|       ...+o=B.o.|
|        .+.==...B|
+----[SHA256]-----+
input_userauth_error: bad message during authentication: type 20
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have gogs set up to listen on port 22 with it's inbuilt SSH server. I'm happy to provide additional details upon request.

**Comment by sbrl** [comment]
I have more information. This appears to only be an issue when I have an SSH connection open to the same server on port 2403 (that's the port I run the regular SSH over). If I close the normal ssh connection to my server, git interacts fine over ssh with gogs.

**Comment by Unknwon** [comment]
Seems a fixed bug from Go lib: https://github.com/golang/go/issues/18711

Have you tried with `go get -u github.com/gogits/gogs` and recompile?

**Comment by sbrl** [comment]
@Unknwon Yeah, that might be the problem! Unfortunately, I don't have go installed, and I don't particularly want a huge (is it ~250mb?) toolchain installed on my server, so I can't use go get :disappointed:

**Comment by Unknwon** [comment]
@sbrl hmm, but the 0.9.128 release binary was compiled after the issue was closed, strange...

**Comment by sbrl** [comment]
@Unknwon Hrm. Odd. I'm happy to provide more information and test stuff - I just can't compile any go code.

**Comment by Unknwon** [comment]
Can you try solution here: https://github.com/gogits/gogs/issues/4081#issuecomment-277641249?

**Comment by sbrl** [comment]
@Unknwon Sorry! I can't compile gogs myself - someone would have to provide a binary :-(

**Comment by Unknwon** [comment]
OK... I'm merging this thread to https://github.com/gogits/gogs/issues/4081 as the reporter claimed issue was fixed with a recompile of Go 1.7.5.

You can wait for next release...

**Comment by sbrl** [comment]
@Unknwon Sure! If it isn't fixed in the next release, I'll comment again either here or in #4081.

**Comment by Unknwon** [comment]
No problem :D
