### ISSUE TITLE
repeating install page with docker on windows 10

### ISSUE THREAD

**Issue by workmonitored** [gogits/gogs#4086]
using docker-compose.. When I reboot asks install again  

version: '2'                                    
services:                                       
  gogs:                                         
   image: gogs/gogs                             
   restart: always                              
   networks:                                    
       common-net:                              
           aliases:                             
              - gogs                            
   ports:                                       
   - "10080:3000"                               
   - "10022:22"                                 
   volumes:                                     
   - /c/web/gdrive/docker/data/gogs:/data       
                                                
networks:                                       
  common-net:

**Comment by Unknwon** [comment]
I think because the mounted volume doesn't work, which means Gogs couldn't detect file that should be generated from install page.

**Comment by workmonitored** [comment]
I see directories and files in the local directory. Can you tell me which file it is looking for?

**Comment by Unknwon** [comment]
Based on example of https://github.com/gogits/gogs/blob/master/docker/README.md, it should be `/var/gogs/gogs/conf/app.ini`.
