### ISSUE TITLE
gogs Manage SSH Keys 添加后无效

### ISSUE THREAD

**Issue by qinhaxx** [gogits/gogs#4087]
Manage SSH Keys 添加生成的key ，git clone http://mc.abc.tech/test.git 总是提示需要输入用户名
免密码的方式 clone 一直不能成功，请指点，我的问题出现在了哪里，应该怎么设置才好，谢谢！

**Comment by Unknwon** [comment]
Please read https://discuss.gogs.io/t/how-to-config-ssh-settings/34.

**Comment by LintBin** [comment]
@qinhaxx 请问你成功解决了吗？我也出现了这种情况，按照楼上的操作没有解决问题

**Comment by William-Hunter** [comment]
I have the same problem before,I solve it like this:  make sure your **account email** is equal with your ssh-keygen **comment** parameter. then add your RSA public key into gogs "user setting-->SSH key" again.
I hope the follow picture will give you some more visual step.
![image](https://user-images.githubusercontent.com/6015561/38462529-3832d516-3b1b-11e8-8415-ca814b81b368.png)

![image](https://user-images.githubusercontent.com/6015561/38462546-8cacbd5a-3b1b-11e8-8a8e-73aecfd58efd.png)

**Comment by acodercat** [comment]
1
