### ISSUE TITLE
Change slack webhook format slightly, or add Discord

### ISSUE THREAD

**Issue by Meowbeast** [gogits/gogs#4088]
- Gogs version (or commit ref): 
0.9.128.0131
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
The current hook uses the format: Repo:[branch] 5 new commits pushed by Meowbeast which is read by Discords markdown incorrectly and formats the link wrong.

If it was changed from `[ ]` to `( )` then this would fix it as well.

It's a tiny change, but will clean things up in Discord.
...

**Comment by Unknwon** [comment]
Hi, please read the content you just posted... and unless Slack supports the markdown format links (I've not checked yet), otherwise it's not a tiny change I believe.

**Comment by Meowbeast** [comment]
I posted a photo of what that looks like below.  They said it has to do with the `[ ]` and could be anything else and it would work correctly.

Now...if you're interested in supporting Discord directly instead of via Slack hooks, that would be great!

Some Discord resources: https://discordapp.com/developers/docs/resources/webhook#execute-webhook

https://discordapp.com/developers/docs/resources/channel#embed-object

![image](https://cloud.githubusercontent.com/assets/22228023/22635400/07899d72-ebf9-11e6-8b5f-0b2fc31aec96.png)

**Comment by Unknwon** [comment]
I'm pretty much confused by documentation at https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook, it says nothing how to correct format a link in order to make it work...

**Comment by Meowbeast** [comment]
When I talked to the Discord dev about this, he said their parser bugs out due to the link and brackets around the branch.

This is the way they format their Github hooks:
![image](https://cloud.githubusercontent.com/assets/22228023/22856041/bc41edd2-f04f-11e6-9c36-d2711565f821.png)
Maybe if you matched the formatting where the link was the entire line?  

Or if you're wanting to make a seperate call for Discord and leave Slacks as-is, here's a link to the `embed object': https://discordapp.com/developers/docs/resources/channel#embed-object
And here's an image layout of the embed https://cdn.discordapp.com/attachments/84319995256905728/252292324967710721/embed.png

**Comment by Unknwon** [comment]
>formatting where the link was the entire line?

Can you given an example of working link in raw content? Not in rendered result.

**Comment by Meowbeast** [comment]
`[[user:branch] 1 new commit](https://website.com/)` or if this still parses wrong, try:
`[(user:branch) 1 new commit](https://website.com/)`

**Comment by Unknwon** [comment]
Thanks, does this mean only one link is allowed in a line (the whole line)?

**Comment by Meowbeast** [comment]
I don't know, tbh.  Would require testing.  Message me on Discord if you'd like a url for testing.  You can send a few test payloads and see how Discord renders.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

Now Discord look like this:

![](https://cdn.discordapp.com/attachments/278626380596641794/280088128826638337/unknown.png)
