### ISSUE TITLE
管理 SSH 密钥增加key 永久生效

### ISSUE THREAD

**Issue by qinhaxx** [gogits/gogs#4090]
gogs 我使用过程中，发现了一个问题，是用官方的 docker 镜像跑的，首先在管理 SSH 密钥的标签下，增加自己生成的Key，然后使用ssh 免密码 git clone／ push 的功能，这都是正常的，然后我把用户下管理的ssh 密钥删除掉，或者把本地的key 删除掉也不影响使用，一样可以ssh 免密码 git clone／ push，后来我重新启动 docker 镜像，还是如此。

**Comment by Unknwon** [comment]
Hi, please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md.
