### ISSUE TITLE
fatal: protocol error: bad pack header

### ISSUE THREAD

**Issue by Leafney** [gogits/gogs#4091]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 1.9.1
- Operating system: Ubuntu 14.04.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:

gogs.log:

```
exit status 3 - error: sha1 mismatch c644886cc66af78a38c8ba60cb9c6686d09098c5
error: c644886cc66af78a38c8ba60cb9c6686d09098c5: object corrupt or missing
error: sha1 mismatch cfaed4e3143675833448bd70b8af7bcb4fc8cae0
error: cfaed4e3143675833448bd70b8af7bcb4fc8cae0: object corrupt or missing
```

stderr.log:

```
error: corrupt loose object 'c644886cc66af78a38c8ba60cb9c6686d09098c5'
fatal: loose object c644886cc66af78a38c8ba60cb9c6686d09098c5 (stored in ./objects/c6/44886cc66af78a38c8ba60cb9c6686d09098c5) is corrupt
error: corrupt loose object 'c644886cc66af78a38c8ba60cb9c6686d09098c5'
fatal: loose object c644886cc66af78a38c8ba60cb9c6686d09098c5 (stored in ./objects/c6/44886cc66af78a38c8ba60cb9c6686d09098c5) is corrupt
error: corrupt loose object 'c644886cc66af78a38c8ba60cb9c6686d09098c5'
fatal: loose object c644886cc66af78a38c8ba60cb9c6686d09098c5 (stored in ./objects/c6/44886cc66af78a38c8ba60cb9c6686d09098c5) is corrupt
error: corrupt loose object 'cfaed4e3143675833448bd70b8af7bcb4fc8cae0'
fatal: loose object cfaed4e3143675833448bd70b8af7bcb4fc8cae0 (stored in ./objects/cf/aed4e3143675833448bd70b8af7bcb4fc8cae0) is corrupt
fatal: unable to read d003c51e9e9bd9a481061c0f0e8e3fc7d31b69b0
```

## Description

When i use  `git clone` , the result is : 

```
$ git clone http://xxxxxx/xxxxx/SpiderMan.git
Cloning into 'SpiderMan'...
remote: Counting objects: 1030, done.
remote: error: corrupt loose object 'c644886cc66af78a38c8ba60cb9c6686d09098c5'
remote: fatal: loose object c644886cc66af78a38c8ba60cb9c6686d09098c5 (stored in ./objects/c6/44886cc66af78a38c8ba60cb9c6686d09098c5) is corrupt
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
```

I found my local repo ·.git/objects/· contains those file:

cf/cfaed4e3143675833448bd70b8af7bcb4fc8cae0   2.61MB
c6/44886cc66af78a38c8ba60cb9c6686d09098c5   17.33MB
5b/e979f406913a030d4f2b8406f0765cdc34958d   17.35MB

my repo have some files:  

phantomjs-2.1.1-windows.zip   17.3 MB
phantomjs.exe      17.7 MB

But I don't know why it error? How to solve it?

**Comment by Unknwon** [comment]
Can you reproduce the bug at https://try.gogs.io?

**Comment by Leafney** [comment]
@Unknwon I'll try and get back to you when I get the results.

**Comment by Leafney** [comment]
I can't reproduce this bug.
I create a new repository and add some big files and it\`s good for `git clone` or other operations. So i guess It\`t not because of the big files or program bug . Maybe because of system file error for `object corrupt or missing` .

Now my solution is to copy a new repository and keep the error one.
Thanks.

**Comment by Unknwon** [comment]
Thanks for the feedback!

I'm closing this until it happens more reproducibly.
