### ISSUE TITLE
.gopmfile shows dependency with a wrong hash digest

### ISSUE THREAD

**Issue by Dr-Terrible** [gogits/gogs#4093]
- Gogs version (or commit ref): v0.9.128
- Git version: 
- Operating system: Linux 64-bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

When trying to packaging Gogs for [Gentoo/Linux](https://github.com/Dr-Terrible/go-overlay/tree/master/www-apps/gogs) using the source tarball for v0.9.128, the compilation didn't succeeded because the file `.gopmfile` is reporting a wrong digest for dependency:

`github.com/urfave/cli = commit:47a988` 

it should be:

`github.com/urfave/cli = commit:347a988` 

This issue is quite low priority, as I manually fixed the wrong digest in the Gentoo's ebuild for the package and the compilation/installation process completed successfully.

**Comment by Unknwon** [comment]
Thank you! Fixed in `develop` branch.
