### ISSUE TITLE
Export username through environment var for use in hooks

### ISSUE THREAD

**Issue by aurabindo** [gogits/gogs#4094]
I would like to know which user is pushing the commits in the pre receive hook so that I can do things like declining the push to a stable branch, etc., so as to implement "Gatekeepers". Only designated usernames should be able to push to certain branches.

This is only possible if Gogs export something like `GOGS_USERNAME` available to pre recieve hooks. This is similar to how Github Enterprise exports various values as documented in https://help.github.com/enterprise/2.8/admin/guides/developer-workflow/creating-a-pre-receive-hook-script/

**Comment by Unknwon** [comment]
Thanks your feedback! How do you think about the request and https://github.com/gogits/gogs/issues/776?

**Comment by aurabindo** [comment]
@Unknwon that is exactly what I'd like to have :) But until its ready, exporting the username to the hooks env would enable me to implement my own checks the hard way!

**Comment by Unknwon** [comment]
OK, for hooks, we now have following envs (please build from `develop` branch or wait for `0.10 RC` release):

name|description
-|-
`GOGS_AUTH_USER_ID`|User ID who made the push
`GOGS_AUTH_USER_NAME `|User name who made the push (can have mixed cases)
`GOGS_REPO_OWNER_NAME `|Owner name of the repository
`GOGS_REPO_ID `|Repository ID
`GOGS_REPO_NAME`|Repository name

**Comment by fatbigbright** [comment]
New added environment variables help implementing branch protection from collaborators except repo owner. Thanks!
