### ISSUE TITLE
[Feature Req.]Unlisted repositories

### ISSUE THREAD

**Issue by SilverCory** [gogits/gogs#4095]
So a somewhat simple feature request of having publicly unlisted repositories, so that the owners can find them in the list, and share the link publicly.

An example: YouTube unlisted videos.

**Comment by Unknwon** [comment]
What is **publicly unlisted repositories**?

**Comment by SilverCory** [comment]
@Unknwon So if you visit the http link posted to you via chat, you can see the repository, otherwise it's private.

Exactly like an unlisted video on YouTube, I can post a link to [this video](https://www.youtube.com/watch?v=v5bsyZxtf-k) but you won't be able to find it on my channel, because only I can see it..

I'm probably not doing the best job at explaining here so someone help me out.

**Comment by Unknwon** [comment]
I guess you're looking for this? https://github.com/gogits/gogs/issues/2887

**Comment by SilverCory** [comment]
Not quiet, same sort of thing but no, like the entire repository is private unless you get the a link to it..

**Comment by Unknwon** [comment]
Sorry I still don't understand your request...

**Comment by SilverCory** [comment]
I can't explain it any other way, look at my updated comment please.

**Comment by Unknwon** [comment]
I see what's your point now.

No, private is private, unless the person gets permission on the site to access, otherwise it's always showing 404.

**Comment by SilverCory** [comment]
Was this implemented?

**Comment by Unknwon** [comment]
>No, private is private, unless the person gets permission on the site to access, otherwise it's always showing 404.

**Comment by SilverCory** [comment]
....  Nice On 14 Feb 2017 9:03 am, 无闻 <notifications@github.com> wrote:
No, private is private, unless the person gets permission on the site to access, otherwise it's always showing 404.
