### ISSUE TITLE
Status of pull request after manually merging.

### ISSUE THREAD

**Issue by fatbigbright** [gogits/gogs#4099]
Suggest that contributor of upstream repo can do "merge and close" operation or something on a pull request after manually merging and pushing to upstream repo.

**Comment by Unknwon** [comment]
Hi, I'm not very well understand your request?

**Comment by fatbigbright** [comment]
1. If a pull request can be merged automatically, then merge can be done on website and its status can be changed into "merged"
2. But if conflicts exist and the pull request need to be manually merged, then after merged and pushed, its status remain "Open", and it can only be changed to "Closed".

What I need is gogs can automatically detect the 2nd circumstance and changed the pull request into "merged" after manually merged. If it is hard to automatically determined, then I wonder whether there is a chance to change pull request status into "merged" after manually merging.

**Comment by Unknwon** [comment]
I see. Yes, Gogs doesn't detect if a PR is merged manually. I think you're looking for https://github.com/gogits/gogs/issues/3388.

**Comment by fatbigbright** [comment]
Thanks for reply. I wonder whether there is any plan to support this feature? Or at least make it possible to change a pull request into the status of "merged" from website even it is manually merged.

**Comment by Unknwon** [comment]
@fatbigbright I think it's possible to use git itself to detect, please post future thoughts on #3388, I'm closing this one.
