### ISSUE TITLE
Dumps are missing avatar files.

### ISSUE THREAD

**Issue by jmnotin** [gogits/gogs#4100]
Hi,

While trying to use the `dump` command to backup/restore a Gogs deployement, I noticed that avatars are not restored by the process. Indeed, the avatars uploaded by users appear to be stored in `data/avatars`, which is not part of the archive generated by `gogs dump`.

I am using Gogs 0.9.128.

Regards,

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by jmnotin** [comment]
I just tested `gogs dump` from the develop branch. On my installation, it failed with:

    Fail to include data/attachments: open data/attachments: no such file or directory

Indeed, the directory does not exist as i have no attachment yet. Creating the directory fixes the error.

**Comment by Unknwon** [comment]
Thanks for the feedback! Just push another quick fix to the `develop` branch to fix the issue.
