### ISSUE TITLE
Re-deploying docker container from scratch

### ISSUE THREAD

**Issue by naileakim** [gogits/gogs#4101]
Hello,

I just deployed gogs with docker, accessed the application and performed main configurations (databases, admins, etc). Now I want to remove that docker container and build a new one with a different configuration. I did `rm -rf /var/gogs` and `mkdir -p /var/gogs` again, removed the container, started a new one, but I cannot access the first set up configuration page.

How to rebuild the container from scratch?

Thanks

**Comment by Unknwon** [comment]
Based on https://github.com/gogits/gogs/tree/master/docker, you only need change configuration file at `/var/gogs/gogs/conf/app.ini`.
