### ISSUE TITLE
Cannot close a milestone using API

### ISSUE THREAD

**Issue by c-geek** [gogits/gogs#4102]
- Gogs version (or commit ref): 0.9.128
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

The API `PATCH /milestones/:id` does not allow to close a milestone.

This wiki claims we can: https://github.com/gogits/go-gogs-client/wiki/Issues-Milestones#edit-a-milestone

**Comment by c-geek** [comment]
And for sure we cannot when looking at the code: https://github.com/gogits/gogs/blob/develop/routers/api/v1/repo/milestone.go#L63-L89

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
