### ISSUE TITLE
Git ist very slow

### ISSUE THREAD

**Issue by Metti9** [gogits/gogs#4103]
- Gogs version (or commit ref):  0.9.130.0131
- Git version: 1.7.4
- Operating system: Ubuntu 16.10
- Database (use `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist:
© 2016 Gogs Version: 0.9.130.0131 Seite: 7617ms Vorlage: 14ms
## Description

Hallo,

can i simply change my database du mysql, i hope that is not so slow.
Or i there any other solution

**Comment by Fastidious** [comment]
Can’t reproduce on `try` (don’t know what DB backend `try` uses), nor on my local install (SQLite). As `git` doesn’t relate to databases, I am not sure what to say...

**Comment by Unknwon** [comment]
@Metti9 log based on what page? How many commits do your repo have?

**Comment by Metti9** [comment]
the log is by open a repo, i have only 100 commits

**Comment by Unknwon** [comment]
Then I think it is the system problem that made "git" runs slow. You can upload your repository to demo site if possible, otherwise we can't investigate this problem..
