### ISSUE TITLE
Customization for upload file size limitation (not issue attachment)

### ISSUE THREAD

**Issue by Xiao-Zhongzheng** [gogits/gogs#4106]
- Gogs version (or commit ref):  0.9.128.0131
- Git version:  1.9.5.msysgit.0
- Operating system: Win 10 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist:

## Description

When upload a file, I got this error message:  _File size (5.1MB) exceeds maximun size (3MB)._ 

...

**Comment by Unknwon** [comment]
Hi, the configuration is here: https://github.com/gogits/gogs/blob/master/conf/app.ini#L51

**Comment by Xiao-Zhongzheng** [comment]
thanks a lot!
