### ISSUE TITLE
SSH cipher support

### ISSUE THREAD

**Issue by spacetourist** [gogits/gogs#4107]
Hi All, I'm considering adding support for configurable SSH ciphers into the Gogs built-in server. Having reviewed the existing code it looks to be a simple change.

The reason for this request is that I am running Gogs in a PCI-DSS environment and for my needs I would like to disable the weak ciphers arcfour256 and arcfour128.

I plan to modify the SSL module code in Gogs to check the config for a new settings (perhaps SSH_SERVER_CIPHERS) and where it exists I would like to implement it when ssh.ServerConfig is instantiated in ssh.go.

Here is the default cipher support list which we are currently falling back to:

**golang.org/x/crptyo/ssh/common.go**
```
var supportedCiphers = []string{
	"aes128-ctr", "aes192-ctr", "aes256-ctr",
	"aes128-gcm@openssh.com",
	"arcfour256", "arcfour128",
}
```

Please let me know if the team would be happy to consider this as a pull request once implemented? Thanks

**Comment by spacetourist** [comment]
#4109

**Comment by Unknwon** [comment]
Close by https://github.com/gogits/gogs/pull/4109.
