### ISSUE TITLE
Failed mirror results in Error 500

### ISSUE THREAD

**Issue by grisu48** [gogits/gogs#4108]
Migration failure (I've not given authentification details) results in a broken repostiory.

## Description

I just wanted to mirror the following repository:
https://github.com/lirokoa/android_kernel_samsung_n80xx.git

Due to a user error I forgot to provide authentification details. The clone process failed, the resulting repository is broken. It appears as local repository and fails with a 500 error when it's opened.

The issue was reproducible in https://try.gogs.io
https://try.gogs.io/phoenix/android_kernel_samsung_n80xx

## Details

- Gogs version (or commit ref): Linux feldspaten.org 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
- Git version: git version 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/phoenix/android_kernel_samsung_n80xx
  - [ ] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/grisu48/1d977f169062bc78a61aa154847fc15b

**Comment by grisu48** [comment]
Update: After some time the repository recovers. It seems that the process is running in the background and returning a 500 until the clone procedure is completed.

**Comment by Unknwon** [comment]
Yes, currently the migration doesn't send to background so it feels buggy. There is already an issue requests to send migration as background task. So I'm closing this one. https://github.com/gogits/gogs/issues/829

**Comment by grisu48** [comment]
Thanks for the response!
