### ISSUE TITLE
An error of compare the differences between the two commits

### ISSUE THREAD

**Issue by darkskygit** [gogits/gogs#4110]
- Gogs version (or commit ref): 0.9.128.0131
- Git version: git version 2.10.2.windows.1
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist: I can't find related logs.

## Description
I push some commits to localhost gogs, and I do this:
![snipaste20170211_010515](https://cloud.githubusercontent.com/assets/25152247/22836168/404797e4-eff6-11e6-8540-a9fc39676b6d.jpg)
Then i get a template error.

**Comment by Unknwon** [comment]
Hi, Does this error occur on all compares or just these two specific commits?

**Comment by darkskygit** [comment]
This error occurs when comparing multiple commits

For example, this url will occur error:

> http://localhost/user/project/compare/hash...hash

But this url will not occur error:

> http://localhost/user/project/commit/hash

**Comment by Unknwon** [comment]
Hi, I can't reproduce this, can you reproduce on demo site?

**Comment by darkskygit** [comment]
I have to reproduce the error：
https://try.gogs.io/darksky/test1/compare/fb5627621a41f6e2d07a8a498a9c73b370c01cd4...c332b77ac404ebc578b409d5cdfdca6ba2ec18b3

**Comment by Unknwon** [comment]
Thanks, will check it!

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by darkskygit** [comment]
I have successfully tested the develop branch.
Thanks for your fix!

**Comment by Unknwon** [comment]
Thanks your confirmation!
