### ISSUE TITLE
documentation for gogs configure and gogs reconfigure

### ISSUE THREAD

**Issue by aparcar** [gogits/gogs#4111]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I can't find any information how the command line actions `configure` and `reconfigure` works.
The only output generated is `No installer has been configured for gogs` in both cases.
Could you please provide some documentation how these commands are meant to be used?
Thanks in advance!

**Comment by Unknwon** [comment]
>I can't find any information how the command line actions configure and reconfigure works.

Hi, there is no such thing.

**Comment by aparcar** [comment]
Gogs Version: 0.9.133.0207 

```
root@sandbox:~# gogs
Usage:
  gogs run COMMAND [options]
  gogs scale TYPE=NUM
  gogs logs [--tail|-n NUMBER]
  gogs config:get VAR
  gogs config:set VAR=VALUE
  gogs configure
  gogs reconfigure
```

**Comment by Unknwon** [comment]
No, that's not Gogs. That's just maybe a script called "gogs" by packager.io.

The real Gogs is:

```
➜  gogs git:(develop) ✗ ./gogs
NAME:
   Gogs - Go Git Service: a painless self-hosted Git service

USAGE:
   gogs [global options] command [command options] [arguments...]

VERSION:
   0.9.139.0210

COMMANDS:
     web      Start Gogs web server
     serv     This command should only be called by SSH shell
     update   This command should only be called by Git hook
     dump     Dump Gogs files and database
     cert     Generate self-signed certificate
     admin    Preform admin operations on command line
     import   Import portable data as local Gogs data
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

**Comment by aparcar** [comment]
great, thanks for the fast reply!

**Comment by Unknwon** [comment]
The packages from packager.io is now somewhat confusing, you might just want to install yourself: https://gogs.io/docs/installation/install_from_binary
