### ISSUE TITLE
Slow internet connection causing migration error.

### ISSUE THREAD

**Issue by jxsl13** [gogits/gogs#4114]
[Youtube](https://www.youtube.com/watch?v=l48eexOGhW8&feature=youtu.be)
Due to a rather slow internet connection the migration of a bigger repository fails.
The repository is created, but I get some rather strange behaviour. See the video above.
At exactly 1:00 in the video you can see what happens, seems like some timeout was reached causing this behaviour.
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

**Comment by Unknwon** [comment]
Hi, you can increase that: https://github.com/gogits/gogs/blob/master/conf/app.ini#L353
