### ISSUE TITLE
Switch from using MD5 to PBKDF2

### ISSUE THREAD

**Issue by aaronjwood** [gogits/gogs#4117]
I'd like to propose that Gogs moves away from using MD5 to hash secrets in cookies and instead use SHA256. MD5 is pretty weak these days and has some known collision issues too. Also, while SHA2 is not really much more resistant to rainbow tables there is less availability of SHA2 rainbow tables (as far as I know) since they are much larger and need more computation power to produce. That is assuming people aren't using ASICs :)

I was thinking of changing all the areas that are using `base.EncodeMD5` to something like `base.EncodeSha256` but realized that this change tightly dependent on Macaron which expects MD5 https://github.com/go-macaron/macaron/blob/78521e4647ad5dcbabd5734d94582ca2373cbad8/context.go#L443

If I'm able to push some changes into Macaron so that it uses SHA2 instead of MD5 would people be open to making the change here as well? What is the process that Gogs uses for updating vendors?

**Comment by aaronjwood** [comment]
Actually, I was looking into this further and noticed that MD5 is mostly being used to create a key for AES encryption/decryption. I think this has some serious flaws and that PBKDF2 should be used instead. PBKDF2 is slow (key stretching) and specifically designed for this use case since it's a key derivation function.

I'm going to try and propose that Macaron switch to using PBKDF2 in cases like https://github.com/go-macaron/macaron/blob/78521e4647ad5dcbabd5734d94582ca2373cbad8/context.go#L443 instead of using MD5.

**Comment by Unknwon** [comment]
Thanks for bringing this up! @leonklingele has talked about this in an email as well.

**Comment by Unknwon** [comment]
That would be the best if you can propose PRs for both Macaron and Gogs as I, personally, don't do well on Crypto..

**Comment by aaronjwood** [comment]
Sure, no worries! I don't mind helping to contribute the changes on either side as well. I'm waiting to hear what the Macaron devs think of this...

**Comment by Unknwon** [comment]
@aaronjwood I wrote Macaron.. so it would be the same..

**Comment by aaronjwood** [comment]
Oh! Hahaha, I didn't even realize that. Give me some time to put these changes together for both sides. I'll try to have a PR for each repo sometime this week.

**Comment by aaronjwood** [comment]
https://github.com/Unknwon/com/issues/11 is slightly related to this.

**Comment by aaronjwood** [comment]
Now that https://github.com/go-macaron/macaron/pull/120 is in place it'd probably better to move away from MD5 entirely and just pass the `salt` + `username` from Gogs. No need to hash stuff at all since PBKDF2 is deriving your key. It's actually worse that MD5 is used because you run the risk of collisions.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by aaronjwood** [comment]
Awesome!

**Comment by Unknwon** [comment]
OK, should we close this now?

**Comment by aaronjwood** [comment]
I haven't tested it out but it looks good to me.

**Comment by Unknwon** [comment]
If you just want to see the computed result, you can try it on https://try.gogs.io/ and view the cookie `gogs_incredible`.

**Comment by aaronjwood** [comment]
Is there a dummy account I can use for this or do I have to sign up?

**Comment by Unknwon** [comment]
Just created one for you: `test_user2/test_user2`.

**Comment by aaronjwood** [comment]
Thanks! I actually don't see `gogs_incredible` getting set. Only `_csrf`, `lang`, and `i_like_gogits`.

**Comment by Unknwon** [comment]
You need to check "remember me", that's the only place used of `SetSuperSecureCookie`.

**Comment by aaronjwood** [comment]
My fault, I see it now. I think this whole piece is much more secure now. I guess the only other thing that could maybe be for a future release is to not use the secret as both the password and salt to PBKDF2 :)

**Comment by Unknwon** [comment]
Good advice, for places that requires much higher level of security, definitely going to make custom version of it, like how Gogs handles user password right now.

**Comment by aaronjwood** [comment]
Thanks for accepting all of my PRs across your various projects :) I guess we can close this out now.
