### ISSUE TITLE
SMTP From field is not valid: mail: no address

### ISSUE THREAD

**Issue by pigeon1990** [gogits/gogs#4118]
Hi, I'm run latest tag in my environment. But I find an error in install page. "SMTP From field is not valid: mail: no address."  
Enable Mail Notification/Enable Register Confirmation not selected.please help me

**Comment by Unknwon** [comment]
Please read post template and attach a screenshot of your install page.

**Comment by pigeon1990** [comment]
![download 1](https://cloud.githubusercontent.com/assets/25000315/22877351/0f0da102-f210-11e6-9b48-025f803aca09.png) fyi

**Comment by Unknwon** [comment]
You attached nothing..

**Comment by pigeon1990** [comment]
![download 1](https://cloud.githubusercontent.com/assets/25000315/22877396/37c51df0-f210-11e6-970b-c974a1c3c5f1.png)

**Comment by pigeon1990** [comment]
![download](https://cloud.githubusercontent.com/assets/25000315/22877436/63a30b76-f210-11e6-9488-8a04c3d0e5a9.png)

**Comment by Unknwon** [comment]
I see, so you're not using the email service at all?

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by pigeon1990** [comment]
Resolved
