### ISSUE TITLE
Repository local copy stops working after force push

### ISSUE THREAD

**Issue by mkaito** [gogits/gogs#4123]
- Gogs version (or commit ref): 0.9.128.0131
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:
Not relevant.

## Description

I just ran into this issue after doing a `git push -f`. I know, it's bad practice, but it shouldn't break Gogs, right?

When trying to file a PR against master, after a `git push -f origin master`, Gogs failed to update its local copy branch because `git checkout master` fails with file conflicts.

I propose that, since nobody will be working and comitting on this working tree, to use `git fetch origin` followed by `git reset --hard origin/master` to work around such problems.

**Comment by Unknwon** [comment]
Sounds good... would you mind propose a PR?

**Comment by Unknwon** [comment]
BTW, restart Gogs should fix the problem you met.

**Comment by mkaito** [comment]
I've never written any Go, but the language doesn't seem to complicated. I'll see what I can come up with. If you use a git library, would you mind linking me, so I can read up on its methods?

**Comment by Unknwon** [comment]
Quick question, does `git reset --hard origin/master` checkouts to `master` branch?

**Comment by mkaito** [comment]
In a way, yes. A hard reset will make the working tree look exactly like the ref you're resetting to, including removing anything that should not be there.

El 14 de febrero de 2017 16:30:14 GMT+00:00, "无闻" <notifications@github.com> escribió:
>Quick question, does `git reset --hard origin/master` checkouts to
>`master` branch?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Unknwon** [comment]
OK, I think all you need to do is change [this part](https://github.com/gogits/gogs/blob/master/models/repo.go#L497-L500)(`git pull`) to become `git reset --hard origin/{branch}`: https://github.com/gogits/git-module/blob/master/repo.go#L208

**Comment by mkaito** [comment]
You also need to git fetch origin first, though. 

El 14 de febrero de 2017 17:13:48 GMT+00:00, "无闻" <notifications@github.com> escribió:
>OK, I think all you need to do is change [this
>part](https://github.com/gogits/gogs/blob/master/models/repo.go#L497-L500)(`git
>pull`) to become `git reset --hard origin/{branch}`:
>https://github.com/gogits/git-module/blob/master/repo.go#L208

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Unknwon** [comment]
Hi, I'm going to work on this if you have not yet started?

**Comment by mkaito** [comment]
I haven't had a chance, no. Be my guest :)

El 15 de febrero de 2017 10:32:59 GMT+00:00, "无闻" <notifications@github.com> escribió:
>Hi, I'm going to work on this if you have not yet started?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
