### ISSUE TITLE
modules/ssh: SSH_KEYGEN_PATH not used for exec ssh-keygen

### ISSUE THREAD

**Issue by kardianos** [gogits/gogs#4124]
ssh-keygen hard coded in https://github.com/gogits/gogs/blob/859009259a5d02a09b05094070b6db063bfc5a37/modules/ssh/ssh.go#L169

Despite the config file option: https://github.com/gogits/gogs/blob/859009259a5d02a09b05094070b6db063bfc5a37/conf/app.ini#L97

Probably want to have ssh server respect the config.

**Comment by Unknwon** [comment]
Good catch! Would you mind propose a PR? Just make very quick modification based on https://github.com/gogits/gogs/blob/master/models/ssh_key.go#L389.

PS: I'm working something with tons of changed files and a lot dirty work on my local machine.

**Comment by kardianos** [comment]
Sure, I'll see what I can do, might be a day or two.

**Comment by Unknwon** [comment]
Hmm, I'll finish the work on hand today. I think I'll be the person does the quick fix. :trollface:

**Comment by kardianos** [comment]
Okay, sorry about that. If I don't see it closed when I get a minute I'll send a PR :)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
