### ISSUE TITLE
Can't delete branch after merging PR

### ISSUE THREAD

**Issue by willy0275** [gogits/gogs#4128]
After merging a PR, the Delete Branch button shows up. In my scenario, the button only reloads the page and does nothing. 

- Gogs version: 0.9.145.0213
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database: MariaDB 10.1

I could reproduct the bug with the following PR:

https://try.gogs.io/willy0275/TestRepo/pulls/2

I first did my test with a branch created from master, and the deleted worked. Then I created a develop, and did a branch from develop, and did a PR on the branch to merge on develop... and there we go the bug appears!

**Comment by Unknwon** [comment]
I got backend error says the branch is not fully merged... I'll check in detail when I come home.

**Comment by willy0275** [comment]
Thanks!

**Comment by Unknwon** [comment]
I can see the commit is surely merged, maybe it assumes it is fully merged only if it is merged to `master`.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io (I've deleted yours...).

**Comment by willy0275** [comment]
It works now, just tested. Thank you :-)

**Comment by Unknwon** [comment]
Thanks your confirmation!

**Comment by ThisDrunkDane** [comment]
This still happens to me on version 0.11.12.0529

**Comment by Unknwon** [comment]
@ThisDrunkDane can you reproduce on demo site?

**Comment by ThisDrunkDane** [comment]
@Unknwon I can't but I just noticed that the version of the demo site is 0.11.21.0611 so I'll try and update first

**Comment by ThisDrunkDane** [comment]
@Unknwon updated to latest release (0.11.19.0609) and the problem still persists

**Comment by ThisDrunkDane** [comment]
I managed to replicate on the test server now

**Comment by ThisDrunkDane** [comment]
Alright it seems if there is a '#' somwhere in the branch name it does weird stuff like redirect to the main page of the repo or just 404

**Comment by Unknwon** [comment]
@ThisDrunkDane good finding! Please file another issue about "#" problem, thanks!

**Comment by ohunecker** [comment]
The "#"-problem exists still in release 0.11.29.0727.

**Comment by vityafx** [comment]
Guys, could you tell me how to delete a branch please? I don’t see any buttons for removing, nowhere.

**Comment by willy0275** [comment]
Strangely, I don't think there's any way with Gogs to delete a branch outside right after merging a PR...

**Comment by vityafx** [comment]
@willy0275 So I can't delete a branch, is this correct?

**Comment by Unknwon** [comment]
This... ? https://www.git-tower.com/learn/git/faq/delete-remote-branch

**Comment by vityafx** [comment]
Probably this, yes. But this is not really user-friendly.
