### ISSUE TITLE
Can't create issue with 🐞 in title

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4131]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
This is tested in `try.gogs.io`. Can't provide link because issues doesn't get created. Easily reproducible, simply create a new issue, starting the topic with an emoji, and it will render a `500`.
...

**Comment by Unknwon** [comment]
Do you mean Unicode emoji?

**Comment by Fastidious** [comment]
Yes, I assume. Like the lady bug on this issue.

**Comment by Fastidious** [comment]
Same happens if I try to use an emoji on repository description.

**Comment by Fastidious** [comment]
Regarding 500 with emoji on description, I can use it on my test install: https://git.quark.business/david/collantes.us, but on https://try.gogs.io is gives 500. Only difference is I am running `0.10.18.0313` and `try` is newer. What do you think, @Unknwon?

**Comment by Unknwon** [comment]
I think it's MySQL encoding related, demo site is using default, and not all encoding supports Emoji.

**Comment by Fastidious** [comment]
@Unknwon ah! Makes sense, I am using SQLite.

**Comment by m2nlight** [comment]
I have a same error. And I try change the description column type to utf8mb4. But emoji charaters cause error yet.

**Comment by mckaygerhard** [comment]
this its not complete fix, in sqlite this does not work, and this limit the mysql installations to only mysql recents

**Comment by m2nlight** [comment]
Yes, it's fixed MySQL connection only. But the title not supports emoji yet. You can type emoji to the description.

**Comment by mckaygerhard** [comment]
so then the commit are unuseless and limit the installation to only newer ,mysql versions.. puff

**Comment by m2nlight** [comment]
Yes. You must change the columns type to utf8mb.
