### ISSUE TITLE
Up to date docker image : based on alpine 3.5 + go 1.8

### ISSUE THREAD

**Issue by yaourt** [gogits/gogs#4145]
Are you interested in updating the Docker image to up to date version of alpine (3.5) & go (1.8) ?
I have a not yet fully tested Dockerfile to do so.

It is based on the current Dockerfile + https://github.com/docker-library/golang/blob/132cd70768e3bc269902e4c7b579203f66dc9f64/1.8/alpine/Dockerfile

**Comment by Unknwon** [comment]
Hi, as long as current version works and stable, I don't think worth taking risk to upgrade.

Besides I failed to `go get github.com/gogits/gogs` on alpine3.5 not sure what went wrong.

**Comment by yaourt** [comment]
Sorry, I was not so clear ...

> BTW alpine3.5 comes with Go 1.7.3

I have a Dockerfile based on alpine 3.5, that builds Go 1.8, then with Go 1.8 builds Gogs.
The result is then a Docker image based on alpine 3.5, with Gogs (built with Go 1.8).

I'm going to send a PR so that you'll have a better view of what I'm talking about ...

> Besides I failed to go get github.com/gogits/gogs on alpine3.5 not sure what went wrong.

I think the issue is related to this : https://github.com/niemeyer/gopkg/issues/50
The workaround consists in changing git default config : 
`git config --global http.https://gopkg.in.followRedirects true`

**Comment by Unknwon** [comment]
>I think the issue is related to this : niemeyer/gopkg#50
The workaround consists in changing git default config :
git config --global http.https://gopkg.in.followRedirects true

Good point! Looking forward to the PR.

BTW, does the image size reminds at "30M+" range?

**Comment by yaourt** [comment]
I don't know how the "Compressed size" is computed on hub.docker.com, but here it is what I have locally.

- "mygogs" being my docker images with based on alpine 3.5 / Gogs 0.9.41 (built with Go 1.8)

- "gogs/gogs" being the docker image available on hub.docker.com

```
$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
mygogs                                              1.8                 a990323a427b        52 minutes ago      91.9 MB
gogs/gogs                                           0.9.141             0efbc5cc2550        7 days ago          90 MB
```

**Comment by Unknwon** [comment]
Thanks for the info! Size looks good.

But I think "Gogs 0.9.41" fairly too old? Why not use latest `master` or `develop` to test?

**Comment by yaourt** [comment]
0.9.141 I meant ;-)

**Comment by Unknwon** [comment]
That's good :D

Would you mind propose a PR for the new Dockerfile?

**Comment by yaourt** [comment]
I'm testing it locally, then of course I will send the PR.

**Comment by Unknwon** [comment]
Closed by PR https://github.com/gogits/gogs/pull/4151.

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by Unknwon** [comment]
@niemeyer thanks for the info!
