### ISSUE TITLE
Gogs returns HTTP status 404 when only asking for headers

### ISSUE THREAD

**Issue by dakira** [gogits/gogs#4148]
- Gogs version (or commit ref): 0.9.157.0218
- Git version: 1.9.1
- Operating system: Ubuntu 14.04 through 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (see below)
  - [ ] No
  - [ ] Not relevant

## Description

When requesting headers only, from a Gogs-server, it wrongly returns HTTP status 404.

Expected: HTTP 200.

```
~ curl -I https://try.gogs.io
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Sat, 18 Feb 2017 12:32:32 GMT
Server: Caddy
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gogits=9739116c14019b0e; Path=/; HttpOnly
Set-Cookie: _csrf=d-5vrjGenRWk33asTvqp0Kuc-jU6MTQ4NzQyMTE1Mjc0OTA3Mzc5Nw%3D%3D; Path=/; Expires=Sun, 19 Feb 2017 12:32:32 GMT; HttpOnly
```

This is not expected behavior for a site that is available. Uptime-Monitors will show Gogs instances as down because they usually only request the headers.

**Comment by focmb** [comment]
mmh, for my own gogs server I get the right response. But for gogs.io the server reponses 404. Perhasp this is not a gogs issue. It is possible that the webserver is the problem.

**Comment by Unknwon** [comment]
Hi, this is duplicated to https://github.com/gogits/gogs/issues/2857.
