### ISSUE TITLE
Permissions in Organizations do not work

### ISSUE THREAD

**Issue by kapralVV** [gogits/gogs#4149]
- Gogs version : Docker 0.9.141.0211
- Git version: 
- Operating system: Linux 
- Database :
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No (I'll explain why , new bug was found while trying to reproduce) 
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Steps to reproduce (use-case):
- Log in as 'user0'  
- Create new organization "Test-org" 
- Create new "private" repo inside organization -> 'test-repo'
- Create new user 'user1"
- Invite 'user1' as a member as org "Test-org" 
- Create new team inside organization "Test-org" with Read-only access -> "Read-team". Add user 'user1' to it 

'user1' cannot see the repository  AT ALL. 
It can be done neither web interface (404 response) nor via 'git clone' (it hangs without trying to ask the login/pass) 
The same whether 'user1' is added to team with Write access. 
Only when 'user1' in team 'Owners' it can see the contents of repo . 

Why I cannot reproduce the issue at https://try.gogs.io 
I tried to create two users with the same email-adress : 'user0' and 'user1'. 'user0 is ok,  but while creating 'user1' gogs shows that captcha is not passed , however I guess the issue caused by the same email for both accounts.

**Comment by Unknwon** [comment]
>Why I cannot reproduce the issue at https://try.gogs.io
I tried to create two users with the same email-adress : 'user0' and 'user1'. 'user0 is ok, but while creating 'user1' gogs shows that captcha is not passed , however I guess the issue caused by the same email for both accounts.

I only get "email has been used" error. So I think you did not actually input the correct captcha.

**Comment by Unknwon** [comment]
BTW... follow your exact steps, the test-user can access the repository. So probably you should update to `develop` or wait for next Tuesday release. There is indeed a org-related access fix in `develop` branch yesterday.

**Comment by kapralVV** [comment]
Ok, thanks. I'll wait Tuesday release .
