### ISSUE TITLE
[Feature Request] Hide all information for unauthentificated vistors of the web ui

### ISSUE THREAD

**Issue by angrox** [gogits/gogs#4156]
Hi, 

It would be nice if we could hide all informations on the website that an unauthentificated visitor can see. By now everyone visiting the page can see not only the public repositories but all groups and all users.
This could be a configurations options ("hide user/group information").

**Comment by Unknwon** [comment]
Hi, please look at config option [`[service ] REQUIRE_SIGNIN_VIEW `](https://gogs.io/docs/advanced/configuration_cheat_sheet#service-(service)).

**Comment by angrox** [comment]
Thanks. I completely missed that :-/ Sorry

**Comment by adrianlzt** [comment]
And some option so anonymous users just see the public repos, but no other private info, like which users or organizations exists?
We want to have some public repos, but exposing all the users and their names is not an option.

Thanks

**Comment by Unknwon** [comment]
@adrianlzt Hi, I don't think any option exist for your need right now... I think you can file a new issue specifically about this.

**Comment by anthony-vito** [comment]
@adrianlzt Did you ever create an issue for this? I was looking for the same kind of security feature. If no one is working on it I could develop it. Just trying not to duplicate issue tickets and effort.

**Comment by adrianlzt** [comment]
Nope @anthony-vito
