### ISSUE TITLE
Smartypants

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4162]
Would it be possible to implement (or enable, not sure if it is implemented already), [Smartypants](https://daringfireball.net/projects/smartypants/) on rendering (when rendering markdown files on a repository and on the wiki)?

Which rendering engine are you using, [Blackfriday](https://github.com/russross/blackfriday)? If so, it comes with it! :-)

**Comment by Unknwon** [comment]
Looks like it is supported: https://github.com/russross/blackfriday/blob/35eb537633d9950afc8ae7bdf0edb6134584e9fc/html.go#L40

But I don't what side effect will have if enabled by default.

**Comment by Fastidious** [comment]
@Unknwon maybe a setting on `app.ini`? I don't see an issue, if only used on `.md` files.

**Comment by Unknwon** [comment]
OK, sounds good... do you have any test repository?

**Comment by Fastidious** [comment]
@Unknwon I can test it on https://try.gogs.io/Fastidious/Ideas (if you enable on `try`). If not, I will set an instance tonight and let you know.

**Comment by Unknwon** [comment]
Cool! I'll use it for testing.

**Comment by ogarcia** [comment]
I do this _only_ as config setting. But I think that is bad idea.

IMHO markdown is a format itself that not need to be decorated, and change characters in other type of files can break the copy-paste (or add unnecesary non-ascii chars to ascii text).

**Comment by Fastidious** [comment]
@ogarcia this request is not about decorating Markdown (where did you get that idea?). It is about using [Smartypants](https://daringfireball.net/projects/smartypants/) formatting. Follow the link. It has nothing to do with Markdown.

Off-topic, but slightly related. Did you know there are people of all languages using Gogs? Plain ASCII just doesn't cut it.

**Comment by ogarcia** [comment]
@Fastidious in your first commen you said
> Would it be possible to implement (or enable, not sure if it is implemented already), Smartypants on rendering (when rendering markdown files on a repository and on the wiki)?

That is, you pretend add a decorator (Smartypants) when rendering markdown that has no sense cause Markdown is a format itself. 

For example, enabling it impede write simple quotes ('as this') cause transform it in “curly” quotes.

As I say IMHO is bad idea.

**Comment by Unknwon** [comment]
This is feature be added with config option, so default behavior won't change..

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch. See https://github.com/gogits/gogs/blob/ac8b1e595fa7ace7e2539276355954b2dceeb388/conf/app.ini#L127-L132.

**Comment by Fastidious** [comment]
@Unknwon is this enabled on `try`? Can it be (at least for a day, so I can test)?

**Comment by Unknwon** [comment]
@Fastidious enabled on demo site.

**Comment by Fastidious** [comment]
@Unknwon everything works fine. On `ANGLED_QUOTES = true`, if set to `false`, will they be curly instead?

**Comment by Unknwon** [comment]
>they be curly 

What is **they**?

**Comment by Fastidious** [comment]
@Unknwon they refers to the quotes. If angled quotes is false, will quotes be curly instead?

**Comment by Unknwon** [comment]
@Fastidious disabled `ANGLED_QUOTES`, you can check it. I'm really confused... :joy:

**Comment by Fastidious** [comment]
@Unknwon Yes! It works perfectly! I would be confused too, no worries. 😄
