### ISSUE TITLE
Discord webhooks formatting

### ISSUE THREAD

**Issue by Meowbeast** [gogits/gogs#4163]
- Gogs version (or commit ref): e78f252713
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes

## Description

On pull requests, the url of the author sends you to the url of the PR.  None of the other hooks have a url tied to the author except the PR and it leads to the same place as the link in the embed.

Could we make this consistent where all Discord webhooks link to the author's Gogs profile page instead?
...
![image](https://cloud.githubusercontent.com/assets/22228023/23151464/537e9804-f7c0-11e6-9367-4e8ce810b0c0.png)

**Comment by Unknwon** [comment]
Hi, 

> None of the other hooks have a url tied to the author except the PR and it leads to the same place as the link in the embed.

I'm not very well understand this sentence...

**Comment by Unknwon** [comment]
Fixed!
