### ISSUE TITLE
For mirror, set a parameter to keep last n releases of a project

### ISSUE THREAD

**Issue by M5oul** [gogits/gogs#4165]
- Gogs version: v0.9.141

## Description

I am mirroring a [GitHub repository which contains many releases](https://github.com/duniter/duniter/releases).
All this releases are heavy, around 1Gb.
As, I am using [Gogs package for YunoHost](https://github.com/YunoHost-Apps/gogs_ynh) which could backup the app.

I prefer not to backup all releases which make the backup and restore processes complicated.

I suggest to set a parameter to keep only `n` last releases of the project.

This could also bypass the problem [releases pages which do not load](https://github.com/go-gitea/gitea/issues/490).

**Comment by Unknwon** [comment]
Hi,

>This could also bypass the problem releases pages which do not load.

I don't understand why the word **bypass** is used here..?

**Comment by Unknwon** [comment]
I think Git only has ability to mirror without tags completely, `--no-tags`.

**Comment by Fastidious** [comment]
Que quieres decir, @M5oul? You mean, "this could also **solve** the problem" reported on `gitea`?

**Comment by M5oul** [comment]
I don't know if the release page still have issues.
But, It used to takes many times to load that page and sometimes didn't load.
Adding the possibility to reduced the number of saved releases could enhance that part.

**Comment by Unknwon** [comment]
Thanks for the response, but I don't think you have direct response to my previous comment:

>I think Git only has ability to mirror without tags completely, --no-tags.
