### ISSUE TITLE
Problem with reusing a repository name that was just deleted

### ISSUE THREAD

**Issue by nbullock** [gogits/gogs#4167]
- Gogs version (or commit ref):  0.9.141.0211
- Git version: 2.11.1.windows.1
- Operating system: Windows Server 2012 R2
- Database
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes

If I delete a repository, but then immediately re-create it using the same name, I get a 500 error.

If I wait a couple of minutes and try again, it works fine.  

The log showed this on my first attempt to recreate the repository.

    2017/02/21 10:58:37 [TRACE] action.newRepoAction: DRS/DRSQuadrantCharts
    2017/02/21 10:58:37 [ERROR] [...routers/repo/repo.go:144 CreatePost()] CreatePost: initRepository: initRepository: path already exists: e:\gogs-repositories\drs\drsquadrantcharts.git
    2017/02/21 10:58:37 [TRACE] Template: status/500

Having seen this in the log, I checked to see if the folder really did exist and it didn't, which is what prompted me to try again.  This next attempt worked.  

Doing the same thing on try.gogs.io gives the same problem.

**Comment by Unknwon** [comment]
Should be fixed now! New release in few hours.

**Comment by master-d** [comment]
is there a work around for this issue for those of us using the 0.9.141.0211 binary?  I ran into the issue while repeatedly testing an SVN to git migration script that would continually delete and re-add the same git repository

**Comment by Unknwon** [comment]
Why not upgrade to the new release?

**Comment by master-d** [comment]
wow talk about a fast response! you mean compile from source?  I guess I could do that. I was just wondering if this was an issue I could temporarily work around until a new binary was released by running some command at the prompt (i.e. removing some temporary file or restarting gogs etc)

**Comment by Unknwon** [comment]
No, I mean, new binary release just came out today: https://github.com/gogits/gogs/releases/tag/v0.10rc

**Comment by master-d** [comment]
Thank you sir! I was unaware.

**Comment by Unknwon** [comment]
@master-d No problem. You can subscribe the newsletter: https://twitter.com/GogsHQ
