### ISSUE TITLE
HTTS instead of HTTP for clone repo

### ISSUE THREAD

**Issue by pboesch** [gogits/gogs#4169]
Hello all,

Is there a way to change the default protocol HTTP to HTTPS  to clone a repo in gogs? I know we have SSH protocol but HTTPS would be nice instead of HTTP if we purpose 2 solutions.

Thank you :)

**Comment by Unknwon** [comment]
Please read https://unknwon.io/setup-gogs-with-https/.

**Comment by pboesch** [comment]
Ok I forget to configure gogs itself in https.

I reminder why I did not do this:
```
./gogs cert -ca=true -duration=8760h0m0s -host=git.domain.com
Incorrect Usage: flag provided but not defined: -ca
```
Do you know why?

**Comment by Unknwon** [comment]
>First of all, you have to build Gogs with build tags cert (official binaries are included this tag by default).

**Comment by pboesch** [comment]
It is. I am on FreeBSD:

> CC=gcc6 go get -u -tags "cert" github.com/gogits/gogs
> CC=gcc6 go build -tags "cert"
> /gogs -ca=true -duration=8760h0m0s -host=git.domain.com
> Incorrect Usage. flag provided but not defined: -ca
> 

Any idea?

**Comment by Unknwon** [comment]
What does `./gogs cert` give you?

**Comment by pboesch** [comment]
Ok sorry, I forget the argument 'cert' in my command line.

Thank you!

Closed.

**Comment by Unknwon** [comment]
:sweat:
