### ISSUE TITLE
[app.ini] Enable customise CSRF cookie name for "Invalid csrf token"

### ISSUE THREAD

**Issue by zzzeep** [gogits/gogs#4172]
There is a case of `Invalid csrf token` error:

domain: `example.com`
sub-domain1: `normal.example.com` => set cookie `_csrf` **and** cookie domain is `*.example.com`
sub-domain2: `gogs.example.com` => set cookie `_csrf` **and** cookie domain is `gogs.example.com`

If a user just use `gogs.example.com`, everything is fine;
If another user redirect to `gogs.example.com` from `normal.example.com`, he got "Invalid csrf token" because CSRF cookie is mixed.

**Comment by Unknwon** [comment]
Why would you allow user uses different domains to connect your Gogs? I think CSRF did the exactly the right thing.

**Comment by zzzeep** [comment]
Thanks.

It is by design -- share cookies between different sub-domains to keep user status(login、logout、post、comments...)

There are more sub-domains like `a.example.com` `b.example.com` `c.example.com` `gogs.example.com`... 

But the `_csrf` from `gogs.example.com` is conflict with the `_csrf` from global shared cookies

**Comment by Unknwon** [comment]
Thanks for the info, but I still don't see your answer to my question?

**Comment by zzzeep** [comment]
Sorry about that. But the truth is I didn't allow it. Gogs still uses its own reg system to login/logout.

**Comment by Unknwon** [comment]
Shouldn't you only allow one specific domain for users to login/access Gogs?

**Comment by zzzeep** [comment]
`a.example.com` `b.example.com` `c.example.com` use `account.example.com/user/login` to login/access

`gogs.example.com` uses `gogs.example.com/user/login`  to login/access

they are separated

**Comment by Unknwon** [comment]
>If another user redirect to gogs.example.com from normal.example.com, he got "Invalid csrf token" because CSRF cookie is mixed.

OK, then what does this mean? I'm consufed.

**Comment by Unknwon** [comment]
I might see what you mean.

So `normal.exampl.ecom` is also using `_csrf` cookie name which is same as Gogs?

**Comment by zzzeep** [comment]
![image](https://cloud.githubusercontent.com/assets/13196890/23242563/6ccef70e-f9b4-11e6-8347-56f044982fbe.png)

**Comment by zzzeep** [comment]
> I might see what you mean.
>So normal.exampl.ecom is also using _csrf cookie name which is same as Gogs?

Yes, exactly!

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

Add new config option '[session] CSRF_COOKIE_NAME'.

**Comment by zzzeep** [comment]
Thanks very much!
