### ISSUE TITLE
Don't work migration (no such file or directory)

### ISSUE THREAD

**Issue by Pjandro** [gogits/gogs#4173]
- Gogs version (or commit ref):  0.9.160.0219
- Git version: 2.10.2
- Operating system: Gentoo amd64 4.9.6-gentoo-r1
- Database (use `[x]`):
  - [ x ] MySQL
- Can you reproduce the bug at https://try.gogs.io:
  - [ x ] No
- Log gist (usually found in `log/gogs.log`):
2017/02/22 19:57:50 [TRACE] Template: repo/migrate
2017/02/22 19:58:23 [TRACE] Session ID: 4eab9e72ebb07d8f
2017/02/22 19:58:23 [TRACE] CSRF Token: D39ULJAB9f2CsNZU59Bz5FRotFI6MTQ4Nzc4MjU2ODY4OTEwNDAwMA==
2017/02/22 19:58:23 [TRACE] action.newRepoAction: ilya/verdaccio
2017/02/22 19:58:54 [ERROR] [...s/context/context.go:97 Handle()] MigratePost: check bare: chdir /home/git/gogs-repositories/ilya/verdaccio.git: no such file or directory - 
2017/02/22 19:58:54 [TRACE] Template: status/500
## Description
Can't create migrate github.com repo to my server.

Error: An error has occurred : check bare: chdir /path-to-repositories/user/verdaccio.git: no such file or directory -

But I can create repos, push to repos and pull from repos.
All work, but migration doesn't work for me.

**Comment by Unknwon** [comment]
Hi, this is already fixed in `master`.
