### ISSUE TITLE
Cannot edit release

### ISSUE THREAD

**Issue by maddie** [gogits/gogs#4174]
- Gogs version (or commit ref): 0.10rc
- Git version: 2.11.1
- Operating system: ArchLinux 64-bit on 4.9.9 kernel
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
Nothing useful in log really..

## Description

Following is what I did:

1. Create a new release in repository
2. Save
3. Go back the Releases page, click `edit` beside the release topic

The following is shown in the browser:
```
template: repo/header:13:96: executing "repo/header" at <.BaseRepo.Link>: can't evaluate field Link in type *models.Repository
```

Though nothing useful in log, just one line saying the GET request is completed with 500 Internal Server Error response.

**Comment by Unknwon** [comment]
Is it a forked repository?

**Comment by maddie** [comment]
Yes, it is a forked repository

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
