### ISSUE TITLE
Import data from gitlab

### ISSUE THREAD

**Issue by pablo102** [gogits/gogs#4175]
```
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
## How i can import projects and issues from gitlab to my local gogs?

**Comment by jumping** [comment]
I have a same question.

**Comment by Unknwon** [comment]
Hi, there is most likely no official support from migrate any other services to Gogs.

But you can use API: https://github.com/gogits/go-gogs-client/wiki

**Comment by xmik** [comment]
Same problem: https://github.com/gogits/go-gogs-client/issues/30 no solutions there either

**Comment by xmik** [comment]
I just tried this for 1 gitlab namespace and it worked: https://github.com/bishwasubedi/gitlab2gogs

**Comment by micw** [comment]
Today I  migrated all our projects using https://github.com/MarcelSimon/MigrateGitlabToGogs. It had some issues (pending PR) but after fixing them it worked.
