### ISSUE TITLE
Can't set a user whitelist to a protected branch

### ISSUE THREAD

**Issue by Jesus-21** [gogits/gogs#4177]
- Gogs version: 0.9.164.0220 / 0.10 RC
- Git version: 2.1.4
- Operating system: Linux 3.16 x64
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/PLORGANISTION/STEUV/settings/branches/master
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2017/02/23 16:27:47 [TRACE] Session ID: 7d82d54de5d3916a
2017/02/23 16:27:47 [TRACE] CSRF Token: J7rnjp-AwPaWnrIVM8T6J_6uGb06MTQ4Nzg1NjYyNjU2NTE3NjUwNw==
2017/02/23 16:27:47 [TRACE] Template: repo/settings/protected_branch
2017/02/23 16:27:52 [TRACE] Session ID: 7d82d54de5d3916a
2017/02/23 16:27:52 [TRACE] CSRF Token: J7rnjp-AwPaWnrIVM8T6J_6uGb06MTQ4Nzg1NjYyNjU2NTE3NjUwNw==
2017/02/23 16:27:53 [TRACE] Session ID: 7d82d54de5d3916a
2017/02/23 16:27:53 [TRACE] CSRF Token: J7rnjp-AwPaWnrIVM8T6J_6uGb06MTQ4Nzg1NjYyNjU2NTE3NjUwNw==
2017/02/23 16:27:53 [TRACE] Template: repo/settings/protected_branch
```

## Description
For a repository created **under an organization** there is an option for protected branches to "Whitelist who can push to this branch" but checking it does nothing and updating settings unchecks it, it changes nothing.

Is there something more to do to use this functionality or is it just not available yet ?

![protected](https://cloud.githubusercontent.com/assets/8310941/23265690/ad56b704-f9e5-11e6-94b7-0dca2ccc8de6.png)

**Comment by Unknwon** [comment]
Not implemented yet.... forgot to hide.. :joy:

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Jesus-21** [comment]
I tried on https://try.gogs.io , looks good except for the fact that I can't whitelist a user unless he is in **Owners** team. 

Whitelisting a whole team seem to work but it is impossible to  whitelist **Owners** team (expected?)

If it is the expected behavior, I can live with that :)

**Comment by Unknwon** [comment]
@Jesus-21 yes that's expected for now, but I don't know which way would be better yet...

**Comment by Unknwon** [comment]
@Jesus-21 FYI, `Owners` team can be added now.
