### ISSUE TITLE
[FeatureRequest] Auto Update Script

### ISSUE THREAD

**Issue by ModdyLP** [gogits/gogs#4179]
Hello
can you provide an update script that automatic check for new updates and install the new updates? 
Maybe with configuration backup?

It would be nice, if you get a Notification "There is a new Version" and you can simple click on update.

Best Regards
ModdyLP

**Comment by Unknwon** [comment]
>Notification "There is a new Version"

This sounds good.

>you can simple click on update.


This no. You should use Docker.

**Comment by ModdyLP** [comment]
Why not? For Linux it would be a simple shell script which removes any old backups and create a backup of confoguration and then download the latest Version and copy the Konfiguration Form the backup to the New Installation folder. 

And the script can be triggered by a click in the website

**Comment by Unknwon** [comment]
I don't like the auto-upgrade for Gogs other than pop a notification for admin there is a new version available.
