### ISSUE TITLE
Dockerfile and docker hub images for the Raspberry Pi are 5 months old

### ISSUE THREAD

**Issue by praticamentetilde** [gogits/gogs#4180]
As said above, the images in [this docker hub repo](https://hub.docker.com/r/gogs/gogs-rpi/) are quite old. I've tried to `docker build` manually, too. `Dockerfile.rpi` seems not up to date:

- the parent image is quite old. There are new Alpine 3.5 based images now (such as [this](https://hub.docker.com/r/resin/raspberrypi2-alpine/));
- it does not `RUN` `build-go.sh` nor `finalize.sh`;
- from `master`, `RUN` `build.sh` fails at line 16 (`cd ${GOPATH}/src/github.com/gogits/gogs`).

Hope the information above is helpful.

**Comment by Unknwon** [comment]
@praticamentetilde Hi, is it possible that you could make a PR to adjust changes in `Dockerfile.rpi`?

**Comment by praticamentetilde** [comment]
I've already tried to make some adjustments to the Dockerfile, but I hadn't any luck. I will continue to try.

**Comment by atomi** [comment]
I've been using `armhf/alpine:edge` and I build gogs directly on the rpi and not in a docker container, then I just `ADD` the gogs directory in a separate Dockerifle. It takes about 15 minutes to build an on rpi1.

**Comment by Spice-King** [comment]
I just copied Dockerfile to Dockerfile.rpi and changed the FROM directive to `armhf/alpine:3.5` and changed gosu to grab the armhf build. Took a while to build, but it built and ran on my rpi3 just fine. If you want a PR for that, I can do it up.

**Comment by atomi** [comment]
I can vouch for the `armhf/alpine` images. They work on armv6 as well :+1:

**Comment by Unknwon** [comment]
@atomi thanks for the info, the main problem here is continuous building and pushing the arm image, I might have time to investigate this weekend.

**Comment by atomi** [comment]
Yeah if you have an rpi you could use https://github.com/drone/drone since it supports arm now but it would take a little bit of work to set up.

**Comment by Unknwon** [comment]
@atomi might be overkill just for building Docker images...

**Comment by Spice-King** [comment]
Someone has gotten basic QEMU emulation of the Pi working. The terminal works fine, just don't expect a desktop experience to run fast on slower hardware, have GPIO pins, or the VideoCore GPU. How you might want to chase that and build a CI system for it is up to you. And like everything else in life, there are many ways to skin this cat.

**Comment by atomi** [comment]
@Unknwon yeah. Personally I am happy to build gogs myself as I think most arm users are.

**Comment by Unknwon** [comment]
@Spice-King for CI, I would rather rent a better VPS... like $20 DO droplet.

**Comment by Spice-King** [comment]
I was more going for just a script that would make a suable QEMU Pi instance, get docker in the QEMU Pi, then build & push the gogs image to the hub repo. The goal being that you could just plug the script into what ever CI you wanted. Or just run when you feel like it on your local box.

**Comment by atomi** [comment]
I think golang has issues building in QEMU virtualized environments but that would be a lot easier and faster if it works.

**Comment by Spice-King** [comment]
I'll take a crack at seeing how golang, QEMU and fake raspberries play with each other. Going to make the PR for the updated Pi Dockerfile, then call it a night.

**Comment by praticamentetilde** [comment]
I've tried to `docker build` the develop branch, but the build fails with the following error:
`models/webhook.go:484: p.SetSecret undefined (type gogs.Payloader has n
 field or method SetSecret)`

**Comment by Unknwon** [comment]
@praticamentetilde thanks for the report! Should be good now.

**Comment by praticamentetilde** [comment]
Thanks @Unknwon ! I've successfully built the develop branch.

**Comment by Unknwon** [comment]
@praticamentetilde Great, I just (finally) installed Docker on my Raspi2 (after whole night running). Would try to build images during weekends.

**Comment by Unknwon** [comment]
I'm using Raspi2 and got following error while building `master`:

```
$ docker build -f Dockerfile.rpi -t gogs/gogs-rpi:latest .
Sending build context to Docker daemon 20.77 MB
Step 1 : FROM armhf/alpine:3.5
3.5: Pulling from armhf/alpine
7969cec02a78: Pull complete
Digest: sha256:ec9d89108e48bf6089bc56a25c64e6a84155d9ee1b97b0d814d6b39f2d28275a
Status: Downloaded newer image for armhf/alpine:3.5
 ---> c6e4fd5e8ec3
Step 2 : ADD https://github.com/tianon/gosu/releases/download/1.9/gosu-armhf /usr/sbin/gosu
Downloading [==================================================>] 1.469 MB/1.469 MB
 ---> 0c8cfe3ca389
Removing intermediate container 1a601162736e
Step 3 : RUN chmod +x /usr/sbin/gosu  && apk --no-cache --no-progress add ca-certificates bash git linux-pam s6 curl openssh socat tzdata
 ---> Running in e894e48d759d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/armhf/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.5/main/armhf/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/armhf/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.5/community/armhf/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  bash (missing):
    required by: world[bash]
  ca-certificates (missing):
    required by: world[ca-certificates]
  curl (missing):
    required by: world[curl]
  git (missing):
    required by: world[git]
  linux-pam (missing):
    required by: world[linux-pam]
  openssh (missing):
    required by: world[openssh]
  s6 (missing):
    required by: world[s6]
  socat (missing):
    required by: world[socat]
  tzdata (missing):
    required by: world[tzdata]
The command '/bin/sh -c chmod +x /usr/sbin/gosu  && apk --no-cache --no-progress add ca-certificates bash git linux-pam s6 curl openssh socat tzdata' returned a non-zero code: 9
```

Any clues?

**Comment by atomi** [comment]
maybe `apk --update`

**Comment by Unknwon** [comment]
@atomi you mean add `apk --update` before `&& apk --no-cache`?

**Comment by atomi** [comment]
@Unknwon yeah you can add just `--update` for the `apk` command ie. `apk --update --no-cache ....`

**Comment by Unknwon** [comment]
Got it, trying...

**Comment by Unknwon** [comment]
Black magic, restart Docker solved problem.

**Comment by Unknwon** [comment]
Succeed! New image for `master`! https://hub.docker.com/r/gogs/gogs-rpi/tags/

**Comment by atomi** [comment]
Just a quick clarification for future reference: `--no-cache` does do an `apk update` (for anyone else passing through)

**Comment by atomi** [comment]
@Spice-King  @Unknwon  by the way if you're still considering a QEMU wrapper for arm builds this will be helpful https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
