### ISSUE TITLE
User can fork own repository but cant create pull request back to maint repository

### ISSUE THREAD

**Issue by Argentumbolo** [gogits/gogs#4182]
- Gogs version (or commit ref): https://try.gogs.io
- Git version: 
- Operating system: 
- Database (use `[x]`): 
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/ForkTestUser/Test/compare/master...ForkTestUser:master)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

### STEPS TO REPRODUCE
* I create user **ForkTestUser** - https://try.gogs.io/ForkTestUser
* I create repository **Test** - https://try.gogs.io/ForkTestUser/Test
* I make 5 random commits - https://try.gogs.io/ForkTestUser/Test/commits/master
* I fork it for **same user** as **Fork-of-own-repository-Test** - https://try.gogs.io/ForkTestUser/Fork-of-own-repository-Test
* I make 5 commits in new repository - https://try.gogs.io/ForkTestUser/Fork-of-own-repository-Test/commits/master
* I press **compare button** (green one) and see page - https://try.gogs.io/ForkTestUser/Test/compare/master...ForkTestUser:master

### ACTUAL BEHAVIOUR
* I see **There is nothing to compare because base and head branches are even.** on page - https://try.gogs.io/ForkTestUser/Test/compare/master...ForkTestUser:master

### EXPECTED BEHAVIOUR
1. If user can make fork, he may create pull request to main repository.
2. User can't fork own repository.

## Causes(?)
I think it because: /ForkTestUser/**Test**/compare/master...**ForkTestUser**:master
Only one field for repository name.
May be it will be some like:
* /ForkTestUser/**Test**/compare/master...**ForkTestUser**::**Fork-of-own-repository-Test**:master

Or user cant fork)

**Comment by Unknwon** [comment]
Right, I think user can fork their own repository to other accounts (organizations), but can't fork to its own, because it is hard (no way) to know where to send pull request from, and pointless.

**Comment by Unknwon** [comment]
OK, it's now disallow fork to yourself.
