### ISSUE TITLE
Needs restart gogs after changing the repo's name

### ISSUE THREAD

**Issue by hzb** [gogits/gogs#4184]
- Gogs version (or commit ref):  v0.9.128
- Git version:  1.9.1
- Operating system: ubuntu 14.04
- Database (use `[x]`):
  - [x] SQLite

## Reproduce

- Create a project called a, push some commits
- Change the project name to b
- Push some commits you will get the error, such as

```
UpdateLocalCopyBranch [branch: master]: git pull origin master: exit status 1 - fatal: '/root/a.git' does not appear to be a git repository fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
```

If I restart gogs server, and it will runs well.

**Comment by Unknwon** [comment]
Hi, your version is too old!
