### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by KevinGong** [gogits/gogs#4186]
$ git push -u origin master
Gogs: Repository owner does not exist
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
----------------------------------------------------------------------------------
serv.log:

[FATAL] [...its/gogs/cmd/serv.go:157 runServ()] Unregistered owner

**Comment by Unknwon** [comment]
I think you're trying to push a repository that is not managed by Gogs.
