### ISSUE TITLE
Improvement: The {{.DisplayName}} shouled be used instead of {{.Name}} in assignee list of the issue_content page

### ISSUE THREAD

**Issue by yourchanges** [gogits/gogs#4187]
1. The line 331 ( https://github.com/gogits/gogs/blob/master/templates/repo/issue/view_content.tmpl#L331 )

> ```<div class="item" data-id="{{.ID}}" data-href="{{$.RepoLink}}/issues?assignee={{.ID}}" data-avatar="{{.RelAvatarLink}}"><img src="{{.RelAvatarLink}}"> {{.Name}}</div>```

should be updated to

> ```<div class="item" data-id="{{.ID}}" data-href="{{$.RepoLink}}/issues?assignee={{.ID}}" data-avatar="{{.RelAvatarLink}}"><img src="{{.RelAvatarLink}}"> {{.DisplayName}}</div>```

2. The line 339 ( https://github.com/gogits/gogs/blob/master/templates/repo/issue/view_content.tmpl#L339 )

>```<a class="item" href="{{$.RepoLink}}/issues?assignee={{.Issue.Assignee.ID}}"><img class="ui avatar image" src="{{.Issue.Assignee.RelAvatarLink}}"> {{.Issue.Assignee.DisplayName}}</a>```

should be updated to

>```<a class="item" href="{{$.RepoLink}}/issues?assignee={{.Issue.Assignee.ID}}"><img class="ui avatar image" src="{{.Issue.Assignee.RelAvatarLink}}"> {{.Issue.Assignee.DisplayName}}</a>```

for the better user experience.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by yourchanges** [comment]
cool!
