### ISSUE TITLE
Packager.io v0.10rc wrong port

### ISSUE THREAD

**Issue by Chouchen** [gogits/gogs#4188]
- Gogs version (or commit ref): 0.9.168.0223 / 0.10 RC 
- Git version: packager.io build 605
- Operating system: debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I just updated Gogs via `sudo apt upgrade`, it installed v0.10rc.

A 503 error occurred just afterward. With `ps -aux | grep gogs`, I saw it was launched with `./gogs web -p 6000` So I modified my apache settings from 3000 to 6000 ; and it worked.

Anyway, in `/etc/gogs/conf/app.ini`, it's still indicated 3000…

**Comment by borigoto** [comment]
I have same problem, but now using apache to proxy gogs, access direct ip:3000.
To solve my problem, i need to change at: `/etc/default/gogs`:

This:
`export PORT=${PORT:=3000}`
To:
`export PORT=3000`

[] s

**Comment by Chouchen** [comment]
I didn't know about this file ! 

After this update, it's 
```
# Generated by pkgr
export APP_HOME="/opt/gogs"
export APP_NAME="gogs"
export APP_SAFE_NAME="gogs"
export APP_GROUP="gogs"
export APP_USER="gogs"
export APP_WIZARDS=""
export APP_RUNNER_TYPE="systemd"
export APP_RUNNER_CLI="systemctl"
export PORT=${PORT:=6000} 
# ↗ 6000 ! ↗

export HOME="/home/gogs"
```

**Comment by borigoto** [comment]
Yes, Debian using many configuration files inside this directory.
But this file not changed by update, i see this configuration on my backup and still same.

I think this variable PORT using at other way on system.. 

[] s

**Comment by colttt** [comment]
Hello,

i also try to install gogs on debian via package.io.
My problem is when i use port 6000 it dont work, if i use an other port like 8080, 3000 or 5000 etc it works fine but not on port 6000..
can somebody tell me how to debug that?!

**Comment by borigoto** [comment]
Hello colttt,

Probably for this:
http://e1tips.com/2014/03/17/allow-firefox-chrome-to-access-restricted-ports/

[] s

**Comment by Unknwon** [comment]
Hi, duplicated to https://github.com/gogits/gogs/issues/1645

**Comment by Unknwon** [comment]
And no deploy discussion here, please go forum.

**Comment by Chouchen** [comment]
I'm sorry but it's not a dup. 

I'm not using nginx (and the pkgr doesn't configure apache). Since last update (v0.10rc), it does use port 6000 instead of 3000 as it used to be. I'm using Gogs from pkgr for at least 6 months and update regularly.

As you can see by my excerpt 5 messages up from here, it written 6000 by pkgr ! #1645 is closed and marked as fixed and it's not.

Please investigate.

**Comment by Unknwon** [comment]
@crohr Hi, I remember you mentioned once, is it still possible to put build scripts or files in GitHub repository?

**Comment by amaisonneuve** [comment]
so where are we at with this one? 

My app file says 3000.. my log file shows its 6000.. neither works.. and well 6000 is a restricted port in chrome and i don't want to have to change every single users chrome setting.. where did this change come from?

**Comment by FibreFoX** [comment]
I changed this in `/etc/defaults/gogs` after upgrading from some older 0.9.x-version ... this is really annoying, because using packager.io even is part of the documentation. Who is behind that change?

**Comment by Unknwon** [comment]
>Those are third-party providers, use on your own risks.

You had been warned: https://gogs.io/docs/installation/install_from_packages

**Comment by amaisonneuve** [comment]
right.. see the warning, but why did the change happen.. a switch to port 6000 makes no sense..

**Comment by Unknwon** [comment]
I have no idea... that's why I asked how can we make settings inside this repository not in packager.io admin panel (which I don't have access to).

**Comment by amaisonneuve** [comment]
I don't see how/why packager.io would make a change to the port number.. also now the app config file is ignored.
