### ISSUE TITLE
Separate data from configuration (docker)

### ISSUE THREAD

**Issue by xmik** [gogits/gogs#4193]
- Gogs version (or commit ref): 0.9.113.1223
- Git version: 2.6.6
- Docker image: gogs/gogs:0.9.113

When running Gogs in a Docker container, I see that there is a volume, to be mounted as `/data` inside the container. When we want to customize Gogs configuration, we have to provide: `/data/gogs/conf/app.ini`. The problem is as @Unknwon said in https://github.com/gogits/gogs/issues/1899: 
> custom config file is volumed to your local file system

This means, that even if I built another docker image, based on gogs/gogs:0.9.113, with custom config in `/data/gogs/conf/app.ini`, when running a container from that image, the config will be overwritten by the external volume.

Wouldn't it be better to separate data from configuration, so that the custom configuration file is not on a docker volume? If anyone wanted to keep the custom configuration file on a local file system, they could keep it on another docker volume anyways.

**Comment by Unknwon** [comment]
Hi, actually I don't know what you're trying to say... you should probably just read https://github.com/gogits/gogs/blob/master/docker/README.md

**Comment by xmik** [comment]
I did read the readme. I was saying that I'm not comfortable keeping configuration and data on the same volume. It's a devops pattern to keep them separated. I was trying to suggest that maybe Gogs could read custom configuration from e.g. `/etc/gogs/app.ini` instead of from `/data/gogs/conf/app.ini`.

Anyways, I found a workaround, so I am ok with this closed. Thank you for Gogs.

**Comment by Unknwon** [comment]
You lost your config if you don't save to local file system.

**Comment by xmik** [comment]
I built another docker image, based on `gogs/gogs:0.9.113` and I have my config saved there in `/etc/gogs/app.ini`. Then, on container start, that config is being copied onto `/data/gogs/conf/app.ini`. This is my workaround.

**Comment by Unknwon** [comment]
I'm 100% confused....
