### ISSUE TITLE
pg: syntax error when removing user from organization

### ISSUE THREAD

**Issue by juliovalcarcel** [gogits/gogs#4195]
- Gogs version (or commit ref):0.9.169.0224 / 0.10 RC 
- Git version: 1.8.3.1
- Operating system: Centos 7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Log gist (usually found in `log/gogs.log`):
```
2017/02/26 15:59:09 [ERROR] [...src/reflect/value.go:434 call()] Action(remove): pq: syntax error at or near ")"
```
## Description
Trying to remove a user from an organization results in a pg syntax error `{"err":"pq: syntax error at or near \")\"","ok":false}`

**Comment by Unknwon** [comment]
Hi, can you dump the `log/xorm.log` here right after the error occurred?

**Comment by juliovalcarcel** [comment]
There are no new messages in the xorm.log created by removing the user.

**Comment by Unknwon** [comment]
OK, have you tried with latest 0.10.1?

**Comment by juliovalcarcel** [comment]
Yes still same issue with no change to the xorm.log and the same log line from above in gogs.log

**Comment by Unknwon** [comment]
OK... I'll look into it.

**Comment by Unknwon** [comment]
Can you post the new complete log line?

**Comment by juliovalcarcel** [comment]
`2017/03/02 15:29:32 [ERROR] [...src/reflect/value.go:434 call()] Action(remove): pq: syntax error at or near ")"`

**Comment by juliovalcarcel** [comment]
And in the browser it prints out the error `{"err":"pq: syntax error at or near \")\"","ok":false}`

**Comment by Unknwon** [comment]
Got it, I'm testing with PostgreSQL right now.

**Comment by Unknwon** [comment]
Hi, I tested remove a user from organization with or without belong to a team, with or without has access to an organizational repository. No error occurred. 

What is your PostgreSQL version?  I'm using 9.5.

**Comment by juliovalcarcel** [comment]
9.3.14

**Comment by Unknwon** [comment]
Ah... that may explain everything. I think XORM only has best support for 9.5 or higher.

**Comment by juliovalcarcel** [comment]
I just upgraded to 9.5.6 and restarted Gogs still with the same issues (No log in xorg.log) and the same logs as before.

**Comment by juliovalcarcel** [comment]
To complicate this even more I was able to remove a different user no problem. The user I just tried to remove did not have an LDAP account any more so I just added a username back to ldap and logged in with the user and still had access. I was however not able to (as the user) leave the organization and i (as admin) was not able to remove them.

**Comment by juliovalcarcel** [comment]
So I narrowed down the issue. 

1. Add a user to LDAP
2. Login as user in gogs
3. From admin account add new user to organization
4. User account is then deleted in LDAP
5. User can't login anymore (as expected)
6. As admin remove user from organization (This is what fails with the the above error I posted)

**Comment by Unknwon** [comment]
Hi, I think this bug should be fixed in `master`, can you try again?
