### ISSUE TITLE
App unresponsive while looking up avatars

### ISSUE THREAD

**Issue by Zelgadis87** [gogits/gogs#4196]
- Gogs version (or commit ref): 0.9.169.0224 / 0.10 RC
- Git version: 2.11.1
- Operating system: RPi 3 (dockerized)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): 

Entire log not needed, relevant parts of a single request below (notice the timing):

```
2017/02/26 22:24:45 [ERROR] [...modules/base/tool.go:189 AvatarLink()] LibravatarService.FromEmail [***@gmail.com]: lookup _avatars-sec._tcp.gmail.com on 192.168.0.1:53: read udp 172.17.0.2:48949->192.168.0.1:53: i/o timeout
2017/02/26 22:24:55 [ERROR] [...modules/base/tool.go:189 AvatarLink()] LibravatarService.FromEmail [***@gmail.com]: lookup _avatars-sec._tcp.gmail.com on 192.168.0.1:53: read udp 172.17.0.2:47631->192.168.0.1:53: i/o timeout
2017/02/26 22:25:05 [ERROR] [...modules/base/tool.go:189 AvatarLink()] LibravatarService.FromEmail [***@gmail.com]: lookup _avatars-sec._tcp.gmail.com on 192.168.0.1:53: read udp 172.17.0.2:36239->192.168.0.1:53: i/o timeout
```

## Description

I just spent the last few hours trying to understand why Gogs took 20-30 seconds to load pages on my environment. The odd part was that it always took multiples of 10000 milliseconds to load, plus a few hundred ms depending on the page, just to render the template, on almost every page (installation and login pages being the few exceptions).

I found out that, since my Docker container has no access to the physical network, it waits 10 seconds for each avatar before finally giving up. So depending on how many time an avatar had to be retrieved, it took 10*n seconds + a few ms to render the page. I found out that configuring Gogs in Offline mode works as a temporary solution.

The reason I'm opening this issue is because I don't think an application should hang so many seconds just because it cannot retrieve an user avatar. In general, a web page should really not wait for a cosmetic element to be ready before displaying *something* to the user. Couldn't the avatar be loaded asynchronously by the browser, after the actually useful information are loaded?

If this cannot be done, for whatever reason, I think the following should be done to mitigate the time the application is unusable due to a network problem with gravatar (could be everything, from a misconfiguration like in my case, to a temporary network outage):
1. A wait of 10 seconds seems exaggerated to me, shouldn't a few seconds be enough?
2. Cache the avatar responses and do not try to re-download an avatar for some time. In my case, the avatar being retrieved is always the same (mine, being the only user of the system atm), there is no need trying to fetch it 3 times in 30 seconds.
3. Look-up avatars concurrently, so that in all cases, in at most ```timeout``` seconds, all requests have either succeeded or failed.

Thanks

**Comment by Unknwon** [comment]
Hi,

1. If you have connectivity problems to federated avatar servers, you can disable it and just use the Gravatar: https://github.com/gogits/gogs/blob/master/conf/app.ini#L267
2. Or simply use offline mode: https://github.com/gogits/gogs/blob/master/conf/app.ini#L48

**Comment by Zelgadis87** [comment]
Hi @Unknwon,
I have stated in my initial report that I have resolved the issue on my environment for now by using offline mode. 

I think however that addressing the issue could still be useful, for temporary problems (like network outages or gravatar being down), or for other people misconfiguring Gogs (having a page rendered without avatar in 300ms is better than waiting 30 seconds for the exact same page to be rendered without avatar).

**Comment by Unknwon** [comment]
Thanks for the advice, but try to compatible with network errors is:

1. Hard
2. Dirty
3. Nor worth investigating time specifically for Gogs, majority of use are in local network which offline mode is often enabled.
