### ISSUE TITLE
please don't use a restricted port

### ISSUE THREAD

**Issue by colttt** [gogits/gogs#4197]
- Gogs version (or commit ref): 0.10rc-1487894981.cd15a17.jessie
- Git version: 1:2.1.4-2.1+deb8u2
- Operating system: Debian GNU/Linux 8.7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Hi,

I installed gogs via package.io, that works fine, but in the standardconfiguration it is used a restricted Port (6000, see also: http://e1tips.com/2014/03/17/allow-firefox-chrome-to-access-restricted-ports/), it would be nice if you use a non restricted port (like 8080, 3000 or 8000) as default
...

**Comment by Unknwon** [comment]
What's on packager.io is not in control of this repository: https://github.com/gogits/gogs/issues?q=is%3Aissue+package.io+is%3Aclosed

**Comment by colttt** [comment]
ok and who is the maintainer of this package?
