### ISSUE TITLE
API - Branches with "/" cannot be accessed.

### ISSUE THREAD

**Issue by hellhand** [gogits/gogs#4198]
- Gogs version (or commit ref): 0.9.121.0127
- Git version: /
- Operating system: Docker
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

Hi,

There seems to be a problem in the API for branches, it is not possible to retrieve the information for a single branch if it has a "/" in it's name eg feature/dns :
http://gogs.local/api/v1/repos/Development/olomanagement/branches => shows the branch list with the branch but;
http://gogs.local/api/v1/repos/Development/olomanagement/branches/feature%2Fdns
does not give any result.

Thanks.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
