### ISSUE TITLE
Push shows up on "Main Page" although the push was rejected

### ISSUE THREAD

**Issue by Jannik8500** [gogits/gogs#4199]
- Gogs version (or commit ref):  0.9.141.0211
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`): http://pastebin.com/xPfMe0YK

## Description
If the push is rejected, the push showing up on the "Main Page" of Gogs as "successful". 

I updated gogs and changed the directory and forgot to rebuild the Update-Hooks of my repositories so that the push was rejected and this bug happend. 

This bug closes issues after a rejected push as well. 

This looks as follows (after the second push was successful):

![bildschirmfoto 2017-02-27 um 20 13 13](https://cloud.githubusercontent.com/assets/5825853/23375631/4c77549c-fd29-11e6-97d7-971a7c580348.png)

**Comment by Unknwon** [comment]
Please post client side output that proves "push rejected".

**Comment by Jannik8500** [comment]
Here is the client side output:
http://pastebin.com/gzUaPGuB

**Comment by Unknwon** [comment]
Thanks, I think the problem was news feed is not controlled by `update` hook.

But hook-related things have been completely changed after 0.9.141 release. You might want to try out new 0.10 release (tomorrow) and report back.

**Comment by Unknwon** [comment]
New release 0.10.1 just come out, please test.

**Comment by Unknwon** [comment]
@Jannik8500 see [my comment](https://github.com/gogits/gogs/issues/4206#issuecomment-283069098).

**Comment by Jannik8500** [comment]
Looks like this has been fixed.
