### ISSUE TITLE
Wanted: Is it possible to add "work time" and "start/end time" three properties to issue?

### ISSUE THREAD

**Issue by yourchanges** [gogits/gogs#4203]
Wanted: Is it possible to add "work time" and "start/end time" three properties to issue?

so  the team can simple use gogs' "Issues" to manage the daily dev task.

**Issue**
  + assignees
  + Labels
  + Milestone
  + Participants
  + work time            //new added
  + start/end time     //new added

if the main design is approved,  I can help to implement it.

**Comment by Unknwon** [comment]
Hi, seems same to https://github.com/gogits/gogs/issues/286?
