### ISSUE TITLE
MySQL too many connections from pre-receive hook

### ISSUE THREAD

**Issue by stevenbarrehpas** [gogits/gogs#4211]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 1.8.3.1
- Operating system: RHEL 7.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/stevenbarrehpas/e051eb3cfc58259f2f37b9be3e95a85b

## Description
When pushing over SSH receive error repeated 150 times

```
remote: Gogs: Internal error
```

**Comment by Unknwon** [comment]
Hi, please go to `path/to/gogs-repositories/{owner}/{repo}.git` and delete `custom_hooks` directory, then the problem should be solved.

**Comment by stevenbarrehpas** [comment]
Woot. That did work. Where did those come from?

**Comment by Unknwon** [comment]
@stevenbarrehpas this problem should only for users who are following to `develop` branch a few days ago where the migration was not correctly handled (then fixed). Not sure if it's your case?

**Comment by stevenbarrehpas** [comment]
I think so. Thanks for the quick responses!
