### ISSUE TITLE
Creating issue with attachment fails

### ISSUE THREAD

**Issue by martinellison** [gogits/gogs#4212]
- Gogs version (or commit ref):  0.10
- Operating system: Fedora
- Database (use `[x]`):
  - [x ] MySQL

## Description

Tried to create an issue with an uploaded document. Got error from database: no such column uuid.
...

**Comment by Unknwon** [comment]
Don't escape field in post template, that helps nothing.

**Comment by martinellison** [comment]
Worked in try.gogs.io, so will investigate.

**Comment by Unknwon** [comment]
This was an very old issue and should be fixed, make sure you are running the version you think you are.

But it is possible MySQL was fixed but PostgreSQL is not. But ORM shouldn't treat them differently in object mapping level.
