### ISSUE TITLE
Incorrect template for comments of issues in Russian translation

### ISSUE THREAD

**Issue by wavebvg** [gogits/gogs#4213]
HTML in comments of issues is incorrectly formed:
` <span class="text grey"><a href="/ZZZ">ZZZ</a> «прокомментировал <a href="%!(EXTRA string=issue-489, template.HTML=<span class="time-since" title="Wed, 01 Mar 2017 10:04:45 MSK">минут назад: 42</span>)</span>`

In file https://github.com/gogits/gogs/blob/master/conf/locale/locale_ru-RU.ini in line 534 need change to

issues.commented_at=\`прокомментировал \<a href="#%s">\%s</a>\`

**Comment by Unknwon** [comment]
Thank you, fixed now! You can test on demo site.
