### ISSUE TITLE
MySQL database being flooded with connections

### ISSUE THREAD

**Issue by fredska** [gogits/gogs#4217]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 64 bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Starting this morning after moving a large-ish repository (2 GB+, couple thousand files), we have been unable to perform any pushes to any of our repositories.  /var/log/gogs/gogs.log doesn't provide any useful info, but /var/log/gogs/hooks/pre-receive.log does with the following:

    2017/03/01 11:02:37 [FATAL] [...its/gogs/cmd/hook.go:97 runHookPreReceive()]  GetProtectBranchOfRepoByName [repo_id: 21, branch: test-pull-request-branch]: Error 1040: Too many connections
    2017/03/01 11:02:37 [FATAL] [...its/gogs/cmd/hook.go:132 runHookPreReceive()] Fail to execute custom pre-receive hook: exit status 1
    2017/03/01 11:02:37 [FATAL] [...its/gogs/cmd/hook.go:132 runHookPreReceive()] Fail to execute custom pre-receive hook: exit status 1
    ....

Turns out that when the pre-receive hook is run, it floods our mysql instance with connections and eventually gives up after hitting the max # allowed (currently set to 150).  The only way to allow pushing is to remove the pre-receive hook.

So my issue is 1).  Is the default pre-receive hook required and 2). If so, what does it cover (as I can't find any information in the documentation related to it).

Thanks!
...

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/4211.

**Comment by fredska** [comment]
That did it, ty much!

**Comment by Unknwon** [comment]
No problem. Just to check, this problem should only occur for users who have once followed `develop` branch about two weeks ago. Is that your case?

**Comment by fredska** [comment]
It must've been;  Another one of my team members grabbed a copy off of your repo that may have been part of the develop branch.

**Comment by Unknwon** [comment]
Thanks for the confirmation!
