### ISSUE TITLE
 Gogs Version: 0.10.1.0228 git clone failed.

### ISSUE THREAD

**Issue by sailfish009** [gogits/gogs#4218]
latest gogs version show error message:

> Cloning into 'C:\git_project'...
> fatal: repository 'http://x.x.x.x/git_project/' not found
> git did not exit cleanly (exit code 128) (124 ms @ 3/2/2017 9:38:44 AM)

but it show git repository well through web browser.

and i fall backed to old gogs version( Gogs Version: 0.9.141.0211),
it works fine, git clone well.

so i think there is problem with latest  Gogs Version: 0.10.1.0228.

only gogs binary version upgrade cause this problem.

Edit:
* Git version: git version 2.11.1.windows.1
* Operating system: Ubuntu 14.04(Server), MS windows 7 64bit(Client)
* Database: i dont know(maybe SQLite3)

**Comment by Unknwon** [comment]
>Git version:
>Operating system:
>Database (use [x]):
>Can you reproduce the bug at https://try.gogs.io:

**Comment by sailfish009** [comment]
Further information:
after i fall backed old version of gogs, now i couldn't git push.

[client]
> [remote rejected] master -> master (hook declined)
[server]
> ... 401 unauthorized..

after few hours struggle this problem, (even i try gogs on windows platform, all didn't worked.)
i switched from gogs to gitea.

now git repo simply works again.

**Comment by Unknwon** [comment]
Good for you!
