### ISSUE TITLE
Gogs need an option to set the tab char'length

### ISSUE THREAD

**Issue by netmou** [gogits/gogs#4221]
I think that gogs need an option to set the tab char'length,because the default length in file viewer is too long . maybe four is better choice!
The shot of my php file like follow:
![image](https://cloud.githubusercontent.com/assets/7068058/23505691/b00f3f6c-ff7f-11e6-9fee-adc0534c0562.png)

- Gogs version (or commit ref): 0.10.1
- Git version: 2.12
- Operating system: win7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

...

**Comment by Unknwon** [comment]
Hi, you can used [`.editorconfig`](https://try.gogs.io/gogs/gogs/src/develop/.editorconfig).

**Comment by netmou** [comment]
thanks very much !（greatly widen my horizon【长知识了】）
