### ISSUE TITLE
No updates to Mirror repository after a certain time

### ISSUE THREAD

**Issue by hsiddiqui** [gogits/gogs#4222]
- Gogs version: 0.9.141
- Git version: 2.7.4
- Operating system: Amazon Linux AMI release 2016.09
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
No errors in the log. I can see mirror updates running at correct intervals:
[TRACE] Doing: MirrorUpdate

## Description
I have set up 2 mirror repos for my existing gogs repo using the migrate feature on the UI. The cron settings used are as follows:

```
[cron]
ENABLED = true
RUN_AT_START = true

[cron.update_mirrors]
SCHEDULE = @every 10m
```

The updates to mirror worked well for 8 hours for both mirror repos but then the mirroring stopped working. I do not see any error in the logs that would indicate an issue. I did a manual run of the git fetch command and the repo got update correctly.
`git fetch --all `

Could you please help me understand if using a shorter schedule period might be causing this issue. i dont see the same issue on https://try.gogs.io (is it scheduled to be updated every 24h?)

Thanks

**Comment by Unknwon** [comment]
Go to `/admin/notices` I guess there are tons of errors now...

**Comment by Unknwon** [comment]
>The updates to mirror worked well for 8 hours for both mirror repos but then the mirroring stopped working

Define: "stopped working", another 8 hours and no update? You can see the last sync time on repo setting page.

**Comment by hsiddiqui** [comment]
There are no errors on /admin/notices. The logs dont show any thing either apart from Doing: MirrorUpdate

The number of times the cron job got executed is getting updated under `admin/monitor`
`
Update mirrors	@every 10m	Thu, 02 Mar 2017 13:30:02 +0000	Thu, 02 Mar 2017 13:20:02 +0000	101
`

By stopped working, i mean no new updates are being picked up from the original repo where i do see the commits coming in.

**Comment by Unknwon** [comment]
>where i do see the commits coming in

It is not real-time mirror sync, you need wait for 8 hours to next sync, or change to 1 hour. Or "Sync now" on repository setting.

Mirror job is just checking if another x hours reached.

**Comment by hsiddiqui** [comment]
i have set the interval to 10m in app.ini so I should not need to wait for 8h for the updates to be reflected on the mirror repos. It worked well for the first 8 hours after the repo was first setup as a mirror but then the updates stopped happening. I believe the Sync Now button is available on the UI in a later release not in 0.9.141. I want it to happen via the cron job instead of clicking the button manually.

**Comment by Unknwon** [comment]
1. The repo interval is set via repo settings.
2. What's in `app.ini` is for how often to run the checking thread

**Comment by hsiddiqui** [comment]
thanks for the clarification - much appreciated :+1:

**Comment by responsible** [comment]
So how can i set the repo's sync interval less than one hour?
