### ISSUE TITLE
git hook post-receive echo $(pwd) path is "/home/git/gogs/"

### ISSUE THREAD

**Issue by linsfg** [gogits/gogs#4225]
Gogs Version: 0.10.1.0228
git hook post-receive shell echo $(pwd) path is "/home/git/gogs/",not repositories path
old version git hook echo $(pwd) in the repositories path

**Comment by Unknwon** [comment]
Hi, I think the problem has been fixed along with [this commit](https://github.com/gogits/gogs/commit/e08161a3021236d8249a3b426967666b916f7d1e). You can test on `develop` branch.

**Comment by linsfg** [comment]
thx~,is ok
