### ISSUE TITLE
Gogs 0.10.1 overwrites all git hooks for every repo on upgrade

### ISSUE THREAD

**Issue by IaBurton** [gogits/gogs#4227]
- Gogs version (or commit ref): 0.10.1
- Git version: 1.8.3.1
- Operating system: Centos 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Hello again,

As I mentioned in #4226 I recently upgraded gogs versions from 0.9.97 to 0.10.1 (then back down to 0.9.141 after these issues). After reverting versions I discovered that 0.10.1 had overwrote every git hook in every repo with a basic bash script that looked like it was running gogs with a hook command (this hook command appears to be new in 0.10.1 but does not exist in 0.9.x). As I mentioned in the other issue I looked at the release notes and several issues and didn't see why this change happened. Unfortunately for me I now have to go through every repo and restore the git hooks I had. I've been using gogs for a while and there wasn't a way to setup a default git hook for new repos, so I used the .gitconfig on the server running gogs and that has been setting up the git hooks on new repos nicely ever since.

I'm not sure if this is a bug or a documentation issue, but should 0.10.1 have overwritten all of my git hooks without checking beforehand if there was something there? I understand it filling out the ones that were empty but I had important hooks setup on every repo that have to be replaced by hand afaik. Does 0.10.1 change any other settings by default? Thank you.
...

**Comment by IaBurton** [comment]
Shortly after posting this I tried pushing to my test repo again (the one from the other issue) and started getting this, with the push failing.

remote: No help topic for 'hook'
remote: error: hook declined to update refs/heads/master

Since 0.10.1 applies a default to all git hooks if they're there or not, and the update hook seems to be new, it created an update hook in every repo that cannot be seen from the gui's of 0.9.x and is causing the push to fail (tries to exec the older gogs which doesn't have a hook command). The solution is to delete that hook from the server itself (in every repo inside gogs-repositories). Are these changes called out anywhere? I wouldn't have updated to 0.10.1 if I had known (again 0.9.141 the last 0.9.x seems fine). Thank you.

**Comment by Unknwon** [comment]
Hi, this is intended and part of migration. To revert hooks migration, see comments: https://github.com/jenkinsci/gogs-webhook-plugin/issues/14#issuecomment-283642729

**Comment by IaBurton** [comment]
Hi @Unknwon 

I was able to revert the git hooks but I'm unable to get the webhooks to work again. Is there something in that link that I missed? Thank you.

**Comment by Unknwon** [comment]
@IaBurton Go `/admin` and regenerate all update hooks.

**Comment by IaBurton** [comment]
Oh ok, I thought that was for the git hooks (since you're calling it update hooks) not web hooks. I'll try that first thing tomorrow when I have access to the system

**Comment by Unknwon** [comment]
>I thought that was for the git hooks (since you're calling it update hooks) not web hooks

The admin operation is for `update hook`, not webhook.
