### ISSUE TITLE
Webhook Skip TLS Verify setting no longer processed in 0.10

### ISSUE THREAD

**Issue by jsetton** [gogits/gogs#4228]
- Gogs version (or commit ref): 0.10.1
- Git version: 2.11.0
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

It looks like there is a bug that was introduced in 0.10 where the webhook SKIP_TLS_VERIFY option in app.ini is not processed by the application at startup anymore. This setting remains set to false no matter if it set to true or false. Other settings in the webhook section are processed fine. Once I rolled back to 0.9.141, I am no longer experiencing this issue.

```
[webhook]
SKIP_TLS_VERIFY = true
```

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by jsetton** [comment]
Tested fix successfully using 0.10.4.0302. Thanks

![screenshot](https://cloud.githubusercontent.com/assets/12190401/23557247/675aaa44-fffd-11e6-89b2-ccb04be08c20.jpg)
