### ISSUE TITLE
Custom pageSize for commit history page

### ISSUE THREAD

**Issue by NgYueHong** [gogits/gogs#4230]
I have just updated to the latest version. It seems to be much faster now and I notice that the pageSize on commit history page is now limit to 30. I can easily change the pageSize number from the browser address bar.

However, how can I change the pageSize default number via app.ini file? I want to make the number to be even smaller like 15 to make the commit history page load faster.

Thank you.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch, see detail https://github.com/gogits/gogs/commit/bc630cc52b81232d4cd9e8ab5cb9495683c5f7b8.
