### ISSUE TITLE
Pagination shows when many private repos exist

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4232]
- Gogs version (or commit ref): `0.9.113.1223`
- Git version: `N/A`
- Operating system: `N/A` 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No: `Can’t test as I am limited to 10 repositories`
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): `N/A`

## Description

If many `private` repositories exist, pagination will show on users dashboard (for those without access to the repositories). See https://code.pin13.net/aaronpk.

**Comment by Unknwon** [comment]
Hi, this is duplicated to https://github.com/gogits/gogs/issues/4082.
