### ISSUE TITLE
Slow request time when browsing repos / wikis (regression)

### ISSUE THREAD

**Issue by Udo** [gogits/gogs#4235]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 2.11.0
- Operating system: openSuse Tumbleweed 20170215
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Sort-of (https://try.gogs.io/udo/test)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
  - [X] Not relevant

## Description

Browsing even empty repositories and wikis is sluggish and takes at least 400ms on my reasonably fast Xeon server. I recently upgraded from an ancient Gogs version (2015), which had page request times of around 16ms. The core functionality of Gogs has become slower by a factor of 25 in little more than a year.

The problem doesn't exist on other pages such as the Dashboard, although those have become slower by a factor of 2, it's still acceptably below 40ms per page.

I can sort-of reproduce the problem on the public test server (version 0.10.3.0228) Page: 156ms Template: 4ms is not exactly fast for browsing an empty repo, but at least it's about 2.5X faster than it is on my server.

A typical page's footer info on my server goes something like this: Page: 462ms Template: 3ms. On repos that are actually used I get well above 500+ ms, which now makes Gogs painful to use. The exact same machine with exactly the same configuration, on Gogs 0.8.10.1217 typically had Page: 16ms Template 3ms.

**Comment by Unknwon** [comment]
Hi, thanks for the long writing!

But this is impossible to diagnose and "fix" because current version has much more features than it was in 2015. And the time comparison is standing on unequal ground.

**Comment by Udo** [comment]
Thanks, that was more informative to me than you probably realize.

**Comment by dobit** [comment]
I have the same problem with the gogs.   I cleanly installed  the gogs, Then I created a repo named test.  when I browse the test repo, I felt very slow , the repo page bottom shows "page: 1508ms template: 1ms ".
