### ISSUE TITLE
PHP Composer failed to execute git clone

### ISSUE THREAD

**Issue by NgYueHong** [gogits/gogs#4236]
- Gogs version (or commit ref): 0.10.1
- Git version: 1.9.5
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (if REQUIRE_SIGNIN_VIEW is set to true)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When REQUIRE_SIGNIN_VIEW setting is set to true, my php composer will unable to execute git clone with the error "fatal: Authentication failed". But, when REQUIRE_SIGNIN_VIEW setting is set to false, it works fine.

Note: My authentication login is correct and I have no problem login and download using Git, but it doesn't work with Composer.
...

**Comment by Unknwon** [comment]
>php composer 

Hi, what is this?

**Comment by NgYueHong** [comment]
@Unknwon It is dependency manager for PHP (https://getcomposer.org/). It is a very common tool that it is almost like a standard in PHP development. Many (almost all) open source PHP packages were develop and packaged with it's standard.

**Comment by Unknwon** [comment]
Thanks for the info! 

But the problem remains:

You need tell whatever it is to send user/pass to Gogs, otherwise it's not going to allow you access.

**Comment by NgYueHong** [comment]
Yes, I did enter the username and password and but it doesn't get thru.

Does Gogs support Git HTTP access that look something like this?
http://admin:***@192.168.1.100:8000/organization/project.git

Because this is how Composer sending login over.

**Comment by Unknwon** [comment]
@NgYueHong I think it should work, I'll take a look!

**Comment by NgYueHong** [comment]
@Unknwon It's the problem with my composer here. After fixing it, it is working with Gogs. Thanks a lot for looking into the issue and put it into 0.11 milestone. 👍

**Comment by Unknwon** [comment]
Oh... hmm. That's a good news :D
