### ISSUE TITLE
Markdown rendering of symlinks

### ISSUE THREAD

**Issue by mgarces** [gogits/gogs#4237]
- Gogs version (or commit ref): 0.9.145.0213 
- Git version: 2.9.3
- Operating system: Fedora 25 - 4.9.10-200.fc25.x86_64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/mgarces/testing-markdown-symlink)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
When you create, for example, README files, if you do not put .md extension, but then create a symlink with the given extension, Gogs does not render the markdown at all.
...

**Comment by Pezhin** [comment]
I think this is the correct behavior, isn't it? 

You cannot assume that README file is a markdown file.

**Comment by FSMaxB** [comment]
Not only is the file not rendered as Markdown, but the symlink isn't followed at all. Instead it displays the filename that the symlink is pointing to.

**Comment by Unknwon** [comment]
I tested GitHub, it does the exact same thing as Gogs:

![image](https://cloud.githubusercontent.com/assets/2946214/24812685/0cd50936-1b99-11e7-90ca-3a889d223b24.png)

I think it is correct to show what symlink points to, which the real content of that file.
