### ISSUE TITLE
Remove account ssh key also removes non-gogs ssh key

### ISSUE THREAD

**Issue by sunwback** [gogits/gogs#4242]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 1.9.1
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I followed [Share port 22 between Gogs inside Docker & the local system](http://www.ateijelo.com/blog/2016/07/09/share-port-22-between-docker-gogs-ssh-and-local-system) to share port 22 between docker and host, but after I tried to remove my account's ssh key the "real git user" 's ssh key was also removed then I got a `"Permission denied (publickey,keyboard-interactive)"` when I tried to access my repository. I must add "real git user" 's ssh key to authorized_keys again after each time I remove my account's ssh key. Is there any method to solve this?
Thanks.

**Comment by Unknwon** [comment]
Hi, this is the expected behavior.

> I must add "real git user" 's ssh key to authorized_keys again after each time I remove my account's ssh key. Is there any method to solve this?

Log in as root then `su - git` or equivalent command to change user.

**Comment by sunwback** [comment]
I may not explained it clearly, I had trouble accessing my repositories but not the git user in host...
Anyway, if that is an expected behavior, I try to use crontab to periodically check the authorized_keys file and add the ssh key to it...
Thanks for the answer.

**Comment by Unknwon** [comment]
Maybe helpful: https://discuss.gogs.io/t/how-to-config-ssh-settings/34

**Comment by sunwback** [comment]
> https://discuss.gogs.io/t/how-to-config-ssh-settings/34

Thank you! I think that's exactly what I need!

**Comment by sunwback** [comment]
Sadly it still didn't solve my problem. I think I should use crontab eventually...

**Comment by marioosh-net** [comment]
I had the same behaviour - deleting SSH key by frontend cleared my ~/.ssh/authorized_keys file.
gitolite use comments in authorized_keys file:
```
# gitolite start
.... gitolite keys here ...
# gitolite end
```
I think, that GOGS could use something like that to not affect other keys in that file.
