### ISSUE TITLE
Some features to discuss

### ISSUE THREAD

**Issue by kolaente** [gogits/gogs#4243]
I discovered gogs a while ago and am using it since severeal moths for my private projects - I love it so far!

But i think it lacks some features to really make it interesting for companies (like the one i'm working in right now). These are just my thougts, i don't know if these are good or dumb, so i post them here to disscuss a bit. I've already found open issues for some.

## Improvements for issues:
* Priority (#1741)
* Due Date (I know you can add a due date to milestones, but it would be nice to have this feature on issues as well, i.e. for smaller issues not worth pulling out a full new milestone)
* Related Issues (This issue depends on another which you need to close before you can close this one)
* Estimated time for this issue to work on
* Time Tracking (Users can specify the time they were working on this) (#286)
* Stauts (Created, Working on, Needs test, etc.)
* Percent Complete

### Create issues per organisation (Without a repository)
In my company, we have a lot of these (as we create an issue for pretty much everything we do), such as calling a client or repair someones computer.

### Other features:
* Message board (very very simplified slack)
* Chatroom (#3317)
* File storage
* Todo-List (From Issues, maybe add a setting to an issue "make this a todo") -> To have a "per-organisation"-overview of open issues
* Boards (Kanban-like-thing, see "Github Projects") (#3716)

**Comment by Unknwon** [comment]
Hi, thanks for the long post!

However, please repost this to https://discuss.gogs.io/, this is not a place to discuss such general question.

**Comment by kolaente** [comment]
Ok, i'll post it there, thank you!
