### ISSUE TITLE
Webhook is not working when using unix socket

### ISSUE THREAD

**Issue by misuzu** [gogits/gogs#4244]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

```
2017/03/06 01:14:25 [TRACE] Trigger task: unix:///tmp/gogs.sock:3000/misuzu/apulse/tasks/trigger?branch=master&secret=f273f7ed949c03497a65c42895e557f9&pusher=1
2017/03/06 01:14:25 [ERROR] [...its/gogs/cmd/hook.go:224 runHookPostReceive()] Fail to trigger task: Head unix:///tmp/gogs.sock:3000/misuzu/apulse/tasks/trigger?branch=master&secret=f273f7ed949c03497a65c42895e557f9&pusher=1: unsupported protocol scheme "unix"
```
## Description

Webhook is not working when using unix socket. Related #3003 
Config:
```ini
[server]
PROTOCOL           = unix
HTTP_ADDR          = /tmp/gogs.sock
HTTP_PORT          = 3000
DISABLE_SSH        = false
SSH_PORT           = 22
OFFLINE_MODE       = true
```

**Comment by Unknwon** [comment]
Possible solution: use FSNotify to send notification to the web process and trigger task.

**Comment by Unknwon** [comment]
Hi, I think the problem can be solved by config [`LOCAL_ROOT_URL`](https://github.com/gogits/gogs/blob/master/conf/app.ini#L23) to be the URL you visit your Gogs in your browser.
