### ISSUE TITLE
Able to config number of newsfeed showed on Dashboard

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4247]
Newsfeed list, and pretty much everything shown on the `Dashboard`, should have a configurable setting to limit what is shown (number of items). See relevant [forum discussion](https://discuss.gogs.io/t/dashboard-number-of-items/952).

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch via `[ui.user] NEWS_FEED_PAGING_NUM`.

**Comment by Fastidious** [comment]
Works, thanks!
