### ISSUE TITLE
"Change your avatar" link in profile page is wrong

### ISSUE THREAD

**Issue by qmarlats** [gogits/gogs#4251]
- Gogs version (or commit ref): 0.10.1.0228
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

On the profile page of a logged in user, clicking on the avatar should redirect us to the avatar change page:
![capture du 2017-03-07 00-25-03](https://cloud.githubusercontent.com/assets/3251811/23634849/cc911098-02cc-11e7-9c25-cdd1721ce1b4.png)
However, clicking on it redirects to `/user/settings` instead of `/user/settings/avatar`.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by qmarlats** [comment]
Great, thanks!
