### ISSUE TITLE
Export user email info as git hooks environment variable

### ISSUE THREAD

**Issue by sigoden** [gogits/gogs#4252]
I want to protect my branches and tags with git hook, but I don't know who's working on the branch or tag;
Maybe it's better to add some environment likes GOGS_USER_NAME , GOGS_USER_EMAIL to the hook.

**Comment by Unknwon** [comment]
Some of possible variables already: https://github.com/gogits/gogs/issues/4094#issuecomment-280794847

I'll add `GOGS_AUTH_USER_EMAIL`.

**Comment by Unknwon** [comment]
Note: write a post about this.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.
