### ISSUE TITLE
Error 500 after upgrade Git

### ISSUE THREAD

**Issue by NgYueHong** [gogits/gogs#4253]
- Gogs version (or commit ref): 0.10.1
- Git version: 2.12
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
The Git installed on my PC was version 1.9.5. Everything was running smoothly. But after I upgrade Git to version 2.12, all the Git in Gogs become error 500. None of it is accessible. Once I uninstall Git 2.12 and install back Git 1.9.5. Everything is OK already.
...

**Comment by Unknwon** [comment]
》Log gist (usually found in log/gogs.log):

**Comment by NgYueHong** [comment]
@Unknwon Here is the log info:

2017/03/02 18:22:24 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:22:35 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:22:41 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:22:45 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:24:14 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:24:15 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:24:16 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:24:17 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%
2017/03/02 18:24:21 [...ules/context/repo.go:245 func1()] [E] GetTags: exec: "git": executable file not found in %PATH%

**Comment by Unknwon** [comment]
Well... it is very obviously that new Git path you installed is not added to your `%PATH%` variable...
