### ISSUE TITLE
Status not update after upgrade Gogs

### ISSUE THREAD

**Issue by NgYueHong** [gogits/gogs#4254]
- Gogs version (or commit ref): 0.10.8
- Git version: 2.12
- Operating system: Windows 7
- Database (use `[x]`):
  - [x] SQLite

## Description
Ever since I upgrade to version 0.10 from 0.9, the status of the Git is not updated in some part of Gogs. For example, if I push a new commit to a Git repo, inside the repo page I can see the latest commit. Everything is working fine in repo page. However, on the dashboard, it does not show the info for the latest commit for that repo. Also, on the explore page where we can see all public repo, the status is also not updated.
...

**Comment by Unknwon** [comment]
Have you changed your Gogs binary path during upgrade?

**Comment by NgYueHong** [comment]
@Unknwon The binary path is still the same as the old one. Here's how I upgrade:
1. Stop the Gogs from Windows Services
2. Rename "Gogs" folder to "Gogs-old"
3. Extract new Gogs to the same directory
4. Copy "custom", "data" and "log" folder from "Gogs-old" to "Gogs" folder
5. Run Gogs from Windows Services

Is the way I am doing the upgrade correct?

**Comment by Unknwon** [comment]
Looks correct. Are you sure you're running 0.10.8? Because this should be a fixed issue.

**Comment by NgYueHong** [comment]
@Unknwon Yeah, it's version 0.10.8. Everything is working perfectly when I was at 0.9.97. But after I upgrade to 0.10.1 and 0.10.8, the status doesn't get updated. If now I revert back to 0.9.97, things will get working again.

**Comment by Unknwon** [comment]
>If now I revert back to 0.9.97, things will get working again.

The hooks are not working on your system, it is broken even if you roll back to older version, because this bug is hidden and not as obvious as the new version.

Here are two options:

1. If you are fine continue using old version, we can stop investigation here.
2. If you want to offer help, please comment.

**Comment by NgYueHong** [comment]
@Unknwon Although the status update works fine on 0.9.97 for me, but I have bigger problem as I have comment on #4255. So, fixing is definitely needed on new version. Who knows others may also facing the same issue.

**Comment by Unknwon** [comment]
OK,

>Run Gogs from Windows Services

Are you using `mws` version or NSSM?

**Comment by Unknwon** [comment]
If you can speak Chinese, you can join this QQ group so we can debug more easily: 218443817

**Comment by NgYueHong** [comment]
@Unknwon I'm using mws version.

**Comment by Unknwon** [comment]
Let's clarify the problem more clearly:

Push was succeed, absolutely no error, and the only problem is no push news feeds generated on dashboard?

**Comment by NgYueHong** [comment]
@Unknwon Yes. When using 0.10.1 or 0.10.8, even if the push is success, the news feeds on the dashboard and the updated time for the repo on explore page does not get updated.

**Comment by Unknwon** [comment]
Thanks, I'll do some tests on my Windows 10.

**Comment by Unknwon** [comment]
Hi, I tested on my Windows 10, `mws` and run via Windows service, I can push and news feeds are showed as normal.

**Comment by Unknwon** [comment]
Can you check that in file `path/to/gogs-repositories/{owner}/{repo}.git/hooks/post-receive`, the Gogs binary path is the same as the path you installed Gogs?

**Comment by NgYueHong** [comment]
@Unknwon Checked. Yes, the path is correct.

**Comment by Unknwon** [comment]
OK... our of ideas.

**Comment by alunegov** [comment]
After upgrade to 0.10.8 (windows, mws, run as service) Gogs created **pre-receive** custom hook in **custom_hooks** for all repos. This file is the same as pre-receive hook in **hooks**. On push i get the error and `2017/03/09 09:49:25 [FATAL] [...its/gogs/cmd/hook.go:140 runHookPreReceive()] Fail to execute custom pre-receive hook: exec: "C:\\dev\\gogs-repositories\\ros\\ids.git\\custom_hooks\\pre-receive": file does not exist`  in pre-receive.log.
After deleting custom hook push works again and i see updates on a dashboard.

**Comment by NgYueHong** [comment]
@alunegov Thanks a lot for your comment. After deleting the **custom_hooks** folder for all repos, the problem is solved. 🥇

**Comment by Unknwon** [comment]
Thanks @alunegov !

I think the problem is your upgrade and then downgrade, then upgrade again, which confused Gogs migration script and made incorrect copies of hooks.

@NgYueHong is everything good now?

**Comment by NgYueHong** [comment]
@Unknwon Yeah, everything is looking good right now. Thanks a lot for your help and attention here. You did a very good work in Gogs. 🥇
