### ISSUE TITLE
Cannot execute custom hooks on Windows

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#4255]
```
2017/03/07 23:08:23 [FATAL] [...its/gogs/cmd/hook.go:243 runHookPostReceive()] Fail to execute custom post-receive hook: exec: "C:\\path\\to\\repo.git\\custom_hooks\\post-receive": file does not exist
```

**Comment by NgYueHong** [comment]
Ever since I upgrade to version 0.10.1 and 0.10.8, it is very frequently that my Gogs always experience this issue. The big problem is, even if I downgrade back to 0.9.97, the problem still remains. There wasn't any problem before I do the upgrade. Many time when we want to push Git, the error occur. The only thing we can do now is keep retrying until it successfully push to Gogs.

**Comment by Unknwon** [comment]
@NgYueHong please don't mixed up with normal Git hooks don't get executed. This issue is for **custom Git hooks**, which assumes normal Git hooks are working properly.

**Comment by NgYueHong** [comment]
@Unknwon Noted. But the error log message I am getting looks exactly like your posting here:

`[...its/gogs/cmd/hook.go:140 runHookPreReceive()] Fail to execute custom pre-receive hook: exec: "E:\\gogs-repositories\\ngeeheng\\website.git\\custom_hooks\\pre-receive": file does not exist
2017/03/08 11:26:32 [FATAL] `

**Comment by Unknwon** [comment]
@NgYueHong OK, thanks for the error log, this explains well.

**Comment by codecrafting-net** [comment]
I upgraded from the version 0.9.113 to 0.11.4 and the hooks is broken to me, and this still related to custom_hooks folder. If you update the hook content, the custom_hooks folder will be created with the hook (to me post-receive). After any push on this state I will receive Gogs Internal error from remote. If I remove this folder nothing happens on the console, but will be messages on the log about 'file does not exists'. From both ways the hook is not executed. This is a BIG issue to me, I will have to downgrade.

**Comment by Arno234** [comment]
Same problem : to make hooks work, i needed to write directly in the repository hooks folder. The custom_hooks directory usage raises a file does not exist error.

**Comment by Unknwon** [comment]
That is the exact problem, I don't understand why it complains about "file does not exist" while file is there...

**Comment by vebaspect** [comment]
Any progress?

**Comment by codecrafting-net** [comment]
I really wanna update to the newest version, but this is holding me back. Like @Arno234 said you must apply the hook directly to the hooks folder. On my case I have a post receive hook, so on the new version this hook is located on custom_hooks folder, but if you copy the hook on this folder and replace it on the file inside de hooks folder and if you want remove the custom_hooks (not necessary), works fine to me. This does not solves the problem and you have to apply to every other repo and reapply every time you update the post-receive via web ui. Besides this issue, there are any problems to directly put the hook on the repo hooks folder?

Just asking @Unknwon. I noticed that on the logs the error saying that the file does not exist has a path with double back slash "\\\\", but on the app.ini file the path uses the standard slash "/". I really don't know how things works, but it's possibe to this be a problem?

**Comment by Unknwon** [comment]
@codecrafting-net 

>Besides this issue, there are any problems to directly put the hook on the repo hooks folder?

Gogs itself needs delegates these hooks in order function normally for every push you made, you can certainly delete that and replace with your own hook script, but Gogs will not be able detect your push anymore.

>I noticed that on the logs the error saying that the file does not exist has a path with double back slash "\\", but on the app.ini file the path uses the standard slash "/". I really don't know how things works, but it's possibe to this be a problem?

I think I've considered (Generally Go handles both styles) but I'll test again see if it's the problem.

**Comment by Unknwon** [comment]
OK... finally had a solution, pushed on `develop` branch.

As always... you need install Git on your server with git-bash.

Here are my content for `pre-receive`, `update`, and `post-receive` edited on web UI (repository setting page):

`pre-receive`:
```sh
#/bin/bash

while read oldrev newrev ref
do
	echo $oldrev $newrev $ref
done
```

`update`:
```sh
#!/bin/sh
refname="$1"
oldrev="$2"
newrev="$3"

echo $oldrev $newrev $refname
```

`post-receive`:
```sh
#/bin/bash
while read oldrev newrev ref
do
	echo $oldrev $newrev $ref
done
```

Output after a push from client side:

```
$ git add --all && git commit -m "add file" && git push
[master 16d3953] add file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 files/HELLO18
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 284 bytes | 284.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: a773f439b49c8e65cc146a4a5b9abfbda038805c 16d3953bcf1b78b686f82226eb00233976dad05f refs/heads/master
remote: a773f439b49c8e65cc146a4a5b9abfbda038805c 16d3953bcf1b78b686f82226eb00233976dad05f refs/heads/master
remote: a773f439b49c8e65cc146a4a5b9abfbda038805c 16d3953bcf1b78b686f82226eb00233976dad05f refs/heads/master
To http://localhost:3000/unknwon/hello.git
   a773f43..16d3953  master -> master
```

**Comment by vebaspect** [comment]
After upgrade _Gogs_ to **0.11.33** everything works correctly.

Thanks for your help. Best regards from Poland.
