### ISSUE TITLE
docker tag latest should be face to last release instead of develop.

### ISSUE THREAD

**Issue by divinespear** [gogits/gogs#4256]
Currently, `latest` docker image looks facing `develop`, it make `latest` unstable.
so sometimes it opens hellgate (I remember it was around 0.9.141...)

If you expect `latest` is latest stable, It should be face to last stable release, and `develop` stand alone for fearless frontiers.

**Comment by Unknwon** [comment]
Hi,

Just because `master` happens to be even with `develop`, doesn't mean it is based on `develop`:

![image](https://cloud.githubusercontent.com/assets/2946214/23719209/744f5920-0408-11e7-9bd6-72cd1a65d159.png)
