### ISSUE TITLE
Allow local mirrors to update in real time using filesystem notifications

### ISSUE THREAD

**Issue by hochhaus** [gogits/gogs#4257]
This is a feature request to avoid the latency and polling of the current mirroring implementation by using filesystem notifications to detect updates when the mirror is a local git repo (on disk).

I am using `repository.ENABLE_LOCAL_PATH_MIGRATION` to mirror a local git repo (eg: `/home/gerrit2/review_site/git/kdbx.git`). My use case is that I want to use all of the gogs functionality (eg issues, wiki, code browsing, etc) except code review for which I use another tool ([gerrit](https://www.gerritcodereview.com/)). Therefore, I am setting up gerrit as the primary repo where all changes are pushed to, reviewed, and merged. Upon merge, I would like the gogs repo to update in real time (vs the min 1 hour polling currently allowed).

**Comment by Unknwon** [comment]
Kind of related: https://github.com/gogits/gogs/issues/2235

**Comment by hochhaus** [comment]
The solution from #2235 is good enough for me. Closing.
