### ISSUE TITLE
Error 404 when viewing or editing draft release

### ISSUE THREAD

**Issue by philjohnstone** [gogits/gogs#4262]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 1.7.1
- Operating system: CentOS 6.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) 
    - https://try.gogs.io/phil_johnstone/test1/src/test_release
    - https://try.gogs.io/phil_johnstone/test1/releases/edit/test_release
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
   - [TRACE] Template: status/404

## Description
Draft release cannot be viewed or edited after creation; causes error 404

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/phil_johnstone/test1/releases/edit/test_release.

**Comment by philjohnstone** [comment]
It's fixed for editing a draft release but still a 404 for viewing a draft release: https://try.gogs.io/phil_johnstone/test1/src/test_release

**Comment by Unknwon** [comment]
>but still a 404 for viewing a draft release: 

You can't because it's a draft, not a real tag yet.
