### ISSUE TITLE
How to update Web cache

### ISSUE THREAD

**Issue by tusik** [gogits/gogs#4263]
I installed gogs in my local server. And update all data to my VPS by `rsync`.
But i can't see any change in vps's gogs website until restart gogs.
How to Update gogs website cache

**Comment by Unknwon** [comment]
>I installed gogs in my local server. And update all data to my VPS by rsync.

I don't understand this? How?

**Comment by tusik** [comment]
@Unknwon  
use 'rsync' transfer my data to vps include sqlite db file etc.
the vps is my local data backup server.
commond like 'rsync -rv gogs root@xxx.xxx:/home'

**Comment by Unknwon** [comment]
>any change in vps's gogs website until restart gogs.

OK.. if you try to hack data managed by Gogs directly, there is no guarantee Gogs is going to work properly. You should write script to do Git pushes, not `rsync`.
