### ISSUE TITLE
Pull request patch conflict detection isn't working with Git localization

### ISSUE THREAD

**Issue by FibreFoX** [gogits/gogs#4265]
- Gogs version (or commit ref): Gogs Version: 0.10.8.0307 (installed via Packager.io)
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When creating pull-requests, they are checked ONCE if a merge would work. This makes some trouble when having concurrent pull-requests.

When a second pull-request gets merged before the first one, and the second one contains changes which are incompatible with the first one, we only see a 500 error page, while the logs are saying "merge conflict", but this is not visible inside the PR-page nor the recieved 500 error page.

It would be nice if this can be re-evaluated when clicking on a "reanalyse/recheck"-button, or even when opening the PR-page (maybe in addition being configurable). Or maybe it is possible to schedule this as some cron-task which re-validates the merge-ability of the open pull-requests?!

Additional Note: maybe the issue-template should include the way how GOGS was installed (via source or binary from packager.io and such methods)

**Comment by Unknwon** [comment]
Hi, 

>Log gist (usually found in log/gogs.log):

**Comment by FibreFoX** [comment]
Hm, will look into the logs, this is a common problem, will try to have this properly reproduced. Would it be sufficient if I can reproduce this on https://try.gogs.io/ ?

**Comment by Unknwon** [comment]
Yes, of course!

Basically what I need is the exact error message so I'm able detect such cases and make Gogs response better other than 500.

**Comment by FibreFoX** [comment]
Hm ... that's odd, I tried this with that online gogs: https://try.gogs.io/issue4265_org/issue4265_repo1

But this time the pull-requests "recognizes" it ... what version of GIT is running there? I will head to my logfiles to find something. Meanwhile: Does it make a difference when GIT uses german localized strings?

**Comment by Unknwon** [comment]
@FibreFoX 

>what version of GIT is running there?

1.8.3.1

>Meanwhile: Does it make a difference when GIT uses german localized strings?

Could be........ the detection is based on.. hmm, English phrase: https://github.com/gogits/gogs/blob/master/models/pull.go#L333-L338

**Comment by FibreFoX** [comment]
I expected it to be something with localization, because I found some german parts like `- fatal: nicht erkannte Eingabe`. Here some logfile lines:
```
2017/03/08 15:02:20 [T] PullRequest[383].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-repo1.git/pulls/86.patch
2017/03/08 15:02:20 [I] Listen: http://0.0.0.0:3000
2017/03/08 15:02:22 [.../gogs/models/pull.go:758 func1()] [E] testPatch: git apply --check: exit status 128 - fatal: nicht erkannte Eingabe

2017/03/08 15:02:22 [T] PullRequest[718].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-repo1.git/pulls/244.patch
2017/03/08 15:02:23 [.../gogs/models/pull.go:758 func1()] [E] testPatch: git apply --check: exit status 128 - fatal: nicht erkannte Eingabe


2017/03/08 15:04:00 [D] CSRF Token: (...removed...)
2017/03/08 15:04:03 [...routers/repo/pull.go:406 MergePullRequest()] [E] Merge: git merge --no-ff --no-commit [data/tmp/repos/817487280.git]: exit status 1 -
2017/03/08 15:04:03 [T] AddTestPullRequestTask [head_repo_id: 247, head_branch: master]: finding pull requests
2017/03/08 15:04:03 [D] Template: status/500
2017/03/08 15:04:03 [T] DeliverHooks [repo_id: 247]
2017/03/08 15:04:03 [T] AddTestPullRequestTask [base_repo_id: 247, base_branch: master]: finding pull requests
2017/03/08 15:04:03 [T] TestPullRequests[2008]: processing test task
2017/03/08 15:04:03 [T] PullRequest[2008].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/157.patch
2017/03/08 15:04:04 [T] PullRequest[2008].testPatch (apply): has conflit
2017/03/08 15:04:04 [T] TestPullRequests[1881]: processing test task
2017/03/08 15:04:04 [T] PullRequest[1881].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/137.patch
2017/03/08 15:04:04 [T] TestPullRequests[1989]: processing test task
2017/03/08 15:04:04 [T] PullRequest[1989].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/146.patch
2017/03/08 15:04:05 [T] TestPullRequests[1990]: processing test task
2017/03/08 15:04:05 [T] PullRequest[1990].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/147.patch
2017/03/08 15:04:05 [T] PullRequest[1990].testPatch (apply): has conflit
2017/03/08 15:04:05 [T] TestPullRequests[1998]: processing test task
2017/03/08 15:04:05 [T] PullRequest[1998].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/150.patch
2017/03/08 15:04:05 [T] TestPullRequests[2000]: processing test task
2017/03/08 15:04:05 [T] PullRequest[2000].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/151.patch
2017/03/08 15:04:06 [T] TestPullRequests[2004]: processing test task
2017/03/08 15:04:06 [T] PullRequest[2004].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/154.patch
2017/03/08 15:04:06 [T] TestPullRequests[2005]: processing test task
2017/03/08 15:04:06 [T] PullRequest[2005].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/155.patch
2017/03/08 15:04:06 [T] TestPullRequests[2007]: processing test task
2017/03/08 15:04:06 [T] PullRequest[2007].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/156.patch




2017/03/08 15:06:50 [D] CSRF Token: (...removed...)
2017/03/08 15:06:51 [D] Template: repo/issue/list
2017/03/08 15:06:56 [D] Session ID: (...removed...)
2017/03/08 15:06:56 [D] CSRF Token: (...removed...)
2017/03/08 15:06:57 [D] Template: repo/issue/view
2017/03/08 15:07:02 [D] Session ID: (...removed...)
2017/03/08 15:07:02 [D] CSRF Token: (...removed...)
2017/03/08 15:07:04 [...routers/repo/pull.go:406 MergePullRequest()] [E] Merge: git merge --no-ff --no-commit [data/tmp/repos/928937389.git]: exit status 1 -
2017/03/08 15:07:04 [T] AddTestPullRequestTask [head_repo_id: 247, head_branch: master]: finding pull requests
2017/03/08 15:07:04 [D] Template: status/500
2017/03/08 15:07:04 [T] DeliverHooks [repo_id: 247]
2017/03/08 15:07:04 [T] AddTestPullRequestTask [base_repo_id: 247, base_branch: master]: finding pull requests
2017/03/08 15:07:05 [T] TestPullRequests[2008]: processing test task
2017/03/08 15:07:05 [T] PullRequest[2008].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/157.patch
2017/03/08 15:07:05 [T] PullRequest[2008].testPatch (apply): has conflit
2017/03/08 15:07:05 [T] TestPullRequests[1881]: processing test task
2017/03/08 15:07:05 [T] PullRequest[1881].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/137.patch
2017/03/08 15:07:06 [T] TestPullRequests[1989]: processing test task
2017/03/08 15:07:06 [T] PullRequest[1989].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/146.patch
2017/03/08 15:07:06 [T] TestPullRequests[1990]: processing test task
2017/03/08 15:07:06 [T] PullRequest[1990].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/147.patch
2017/03/08 15:07:06 [T] PullRequest[1990].testPatch (apply): has conflit
2017/03/08 15:07:06 [T] TestPullRequests[1998]: processing test task
2017/03/08 15:07:06 [T] PullRequest[1998].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/150.patch
2017/03/08 15:07:06 [T] TestPullRequests[2000]: processing test task
2017/03/08 15:07:06 [T] PullRequest[2000].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/151.patch
2017/03/08 15:07:07 [T] PullRequest[2000].testPatch (apply): has conflit
2017/03/08 15:07:07 [T] TestPullRequests[2005]: processing test task
2017/03/08 15:07:07 [T] PullRequest[2005].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/155.patch
2017/03/08 15:07:07 [T] TestPullRequests[2007]: processing test task
2017/03/08 15:07:07 [T] PullRequest[2007].testPatch (patchPath): /srv/repositories/SOMECOMPANY/SOMECOMPANY-group.git/pulls/156.patch
```

**Comment by Unknwon** [comment]
Detect with strings is already... hmm dirty hack, to make it work with localization, is even... hmm dirtier.

But `exit status 128 - fatal:` seems fixed error message and a better alternative.

**Comment by Unknwon** [comment]
Hi, can you try build from `develop` branch?

**Comment by FibreFoX** [comment]
Maybe this is the "trick" why our pull-requests aren't detected as not being able to merge. Will try to reproduce this on our system with that localized GIT-message, will report back.

**Comment by FibreFoX** [comment]
This might be a real fix 😀, because there are a lot of localized messages: https://github.com/git/git/tree/master/po but the exit-codes are fixed: https://github.com/git/git/blob/d09b6927978d70ca53126e80d0dc8a070cc06635/apply.c#L4668

Don't know if "fatal" will catch them all tho.

Will report back in some time, when I have re-created this on our current GOGS ... and will need some time I have a test-system with a develop-branch being set up (just need to make sure this is reproduced correctly)

**Comment by Unknwon** [comment]
You're right, only 128 is fixed, basically where there is an error, should consider as conflict.

**Comment by Unknwon** [comment]
Please pull the latest `develop` again (sorry!) and perform the tests.

**Comment by FibreFoX** [comment]
Hi :) no worries, I'm able to test this "tomorrow", so I need at least 20 hours for being able to test/reproduce this.

**Comment by Unknwon** [comment]
@FibreFoX No problem :D

**Comment by Unknwon** [comment]
Hi, any updates?

**Comment by FibreFoX** [comment]
Hi there, it is a bit tricky to reproduce this, more than I thought. Currently I'm testing with my own user and small changes/pull-requests. All in all your commit seems very good, as it does not rely on localized strings.

The pull-requests were done with 0.9.x, but my testing on current 0.10.8 seems to not have that problem.

Just to make sure, how does patch-conflict checks happen? On pull-request page visit?

**Comment by Unknwon** [comment]
>On pull-request page visit?

No, background process, basically as soon as it created.

**Comment by Unknwon** [comment]
Close until reoccurred.

**Comment by FibreFoX** [comment]
Just one note here: I can't reproduce that error with current develop-branch ;) seems that it works now
