### ISSUE TITLE
if db (sqlite) get's lost there is no message - just a "pre-receive hook declined" in git

### ISSUE THREAD

**Issue by guido1g** [gogits/gogs#4267]
- Gogs version (or commit ref): 0.10.8 win service
- Git version: 2.2.4
- Operating system:  Windows Server 2012R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
if using sqlite and the db get's lost or corrupted (0 KB) everything seems normal BUT you can't check in files. You are getting "an Error during "send":
gogs ! [remote rejected] master -> master (pre-receive hook declined)
no clue in gogs.log but...
in "hooks.log": [FATAL] [...its/gogs/cmd/hook.go:97 runHookPreReceive()] GetProtectBranchOfRepoByName [repo_id: 4, branch: master]: no such table: protect_branch

A sanity-check or a db-check when viewing the Configuration would be very helpful. 
Took me 3 hours to find this. (moved the new gogs from the DEV- to the PROD-machine)
...

**Comment by Unknwon** [comment]
Please post full output when you try to push.

**Comment by Unknwon** [comment]
Never mind, hook logs already told you that, why should Gogs work if database it depends on is missing or corrupted?
