### ISSUE TITLE
Webhooks - not working properly, only with SHA256 authentication

### ISSUE THREAD

**Issue by slPerryRhodan** [gogits/gogs#4269]
- Gogs version (or commit ref): 0.10.x
- Git version: 2.11.1
- Operating system: Docker version of Gogs (Host System: Ubuntu 16.04.2 LTS)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Hello, 

Gogs is great, but since version 0.10.x Webhooks doesn't work any more with the old Gogs plugin (1.0.8 or less) of Jenkins. And with the new Gogs plugin (1.0.9) it works only with password (SHA256 authentication).

With the Gogs version  0.9.141.0211 or less everything works fine.
In our development environment we use no password/secret for the Webhooks. But since version 0.10.x of Gogs the field secret was removed. Is there anything I have to configure to say Gogs to include the field "secret" in the payload?

It seems it's just the messing field "secret" in the payload, which cause the following error.

## Gogs Webhook Request Header
```
Request URL: https://{DOMAIN}/config-mgmt/gogs-webhook/?job=TestPipeline
Request method: POST
Content-Type: application/json
X-Gogs-Delivery: 38a57511-eead-4183-8231-848550d523b1
X-Gogs-Event: push
X-Gogs-Signature: 
```
## Gogs Webhook Payload

```
 {
   // missing field: "secret": "",
   "ref": "refs/heads/master",
   "before": "eead88db9cf71cb0d7911fbac07b33b8f13ba12f",
   "after": "eead88db9cf71cb0d7911fbac07b33b8f13ba12f",
   "compare_url": "",
   "commits": [
     {
       "id": "eead88db9cf71cb0d7911fbac07b33b8f13ba12f",

    ...... 
 }
```

### Stack trace
<pre style="margin:2em; clear:both">
javax.servlet.ServletException: net.sf.json.JSONException: JSONObject["secret"] not found.
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:362)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        . . . 
Caused by: net.sf.json.JSONException: JSONObject["secret"] not found.
	at net.sf.json.JSONObject.getString(JSONObject.java:2040)
</pre>

**Comment by Unknwon** [comment]
>Webhooks doesn't work any more with the old Gogs plugin (1.0.8 or less) of Jenkins

Yes, it is correct.

>And with the new Gogs plugin (1.0.9) it works only with password (SHA256 authentication).

No, AFAIK, the [discussion thread](https://github.com/jenkinsci/gogs-webhook-plugin/issues/14) said it has back-support for older versions of Gogs.

**Comment by slPerryRhodan** [comment]
>>And with the new Gogs plugin (1.0.9) it works only with password (SHA256 authentication).

> No, AFAIK, the discussion thread said it has back-support for older versions of Gogs.

Sorry, but it's not correct. With Gogs 0.10.x I'm forced to use a password, otherwise the Jenkins plugin of Gogs (1.0.9) throws an exception as mentioned above.
`javax.servlet.ServletException: net.sf.json.JSONException: JSONObject["secret"] not found`

Last test was today:
- Gogs version: 0.10.8.0307
- Jenkins plugin of Gogs: 1.0.9

**Comment by Unknwon** [comment]
You should file bug to Jenkins plugin, not here in Gogs. Because there is nothing we can do.

**Comment by slPerryRhodan** [comment]
As you said: https://github.com/jenkinsci/gogs-webhook-plugin/issues/18

But I would appreciate it, if you could amend the documentation https://gogs.io/docs/features/webhook in the near future. Because it still includes the field "secret" in the payload of a Webhook.

Thanks a lot

**Comment by Unknwon** [comment]
Good catch! Updated.
