### ISSUE TITLE
support for specified ssh keys file name

### ISSUE THREAD

**Issue by garbled1** [gogits/gogs#4270]
- Gogs version (or commit ref):  0.6.2
- Git version: 2.9
- Operating system: RHEL6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):
n/a
## Description
At our site we use authorized_keys files in the format /keydir/%u .  I can tell it to use /keydir, however, it creates a file in there named authorized_keys.   Right now I have a symlink as a workaround, but being able to specify the format as /dir/%u or even just a file name would be ideal.
...

**Comment by Unknwon** [comment]
Hi, isn't this option enough? https://github.com/gogits/gogs/blob/master/conf/app.ini#L37

**Comment by garbled1** [comment]
It ends up not working for me. I need the file to be called the username, so "/keydir/gogs".  Instead, gogs creates it as /keydir/authorized_keys. Additionally, that directory is not world writeable, so it can't create files in there.  When you delete a user from gogs, it attempts to create SSH_ROOT/authorized_keys.tmp and logs an error.

I've worked around it for now with clever use of symlinks, but native support would be nice.
