### ISSUE TITLE
Gogs unavailable for several minutes on startup

### ISSUE THREAD

**Issue by dmlambea** [gogits/gogs#4271]
- Gogs version: tested 0.9.113 and 0.10.8
- Git version: 2.11.1
- Operating system:  Docker version of Gogs over CoreOS Stable 1298.5.0
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (console output):

> init:socat  | Will not try to create socat links as requested
> Mar 10 10:46:36 syslogd started: BusyBox v1.25.1
> Mar 10 10:46:36 sshd[21]: Server listening on :: port 22.
> Mar 10 10:46:36 sshd[21]: Server listening on 0.0.0.0 port 22.
> 2017/03/10 10:50:18 [TRACE] Custom path: /data/gogs
> 2017/03/10 10:50:18 [TRACE] Log path: /data/gogs/log
> 2017/03/10 10:50:18 [TRACE] Log Mode: File (Trace)
> 2017/03/10 10:50:18 [ INFO] STIC :: Git Service 0.10.8.0307

## Description

I'm running Gogs as a docker container in a Kubernetes cluster. Kubernetes can be told to restart Gogs if it becomes unresponsive. I've set the liveness probe to a HTTP GET against a static, fixed content (currently /img/404.png, since it's a small file and is always accessible). The probes are periodically executed by Kubernetes after a configurable initial delay of N seconds, which is used to give the application enough time to start up.

As the number of repositories grows, Gogs takes more and more time on startup, eventually exhausting the initial delay period and making the probes to fail. This is considered by Kubernetes as a sign of unresponsiveness, and then Gogs is restarted, so it all keeps happening again and again.

As can be seen in the console output, it took almost 4 minutes for Gogs to start the web interface. I've had to raise the initial delay from 30 seconds to 60, then 90, then 180, and it's now on 300 seconds, in order to keep Kubernetes from probing Gogs within that initial period of time. Unfortunately, it seems to be a growing problem.

**Comment by Unknwon** [comment]
Gogs demo has over 8k repos

**Comment by Unknwon** [comment]
Gogs demo site has over 6k repos and starts in a second in $5 DO VOS, I suspect it is your server problem.

**Comment by cesargomezvela** [comment]
Hello,

I have the same problem, my environment is very similar.

Docker Image: gogs/gogs:0.11.29
Kubernetes version: 1.9.2
NFS 4 as storage

Gogs gets stuck in this point:
```shell
kubectl logs -f dev-gogs-gogs-6b7ccc5c6f-hm66k
init:socat  | Will not try to create socat links as requested
Aug  9 23:20:10 syslogd started: BusyBox v1.25.1
Aug  9 23:20:59 sshd[23]: Server listening on 0.0.0.0 port 22.
```
The log level is TRACE but it not helps.
Right now I have wait for 10 minutes.
Any help???

**Comment by dmlambea** [comment]
Hi, cesargomezvela

The problem comes from the shared storage requirements. I moved Gogs out of
Kubernetes cluster to a pet machine using local storage and it began to
start up almost instantly.
