### ISSUE TITLE
Setting up mirror repo using config does not show branches in UI

### ISSUE THREAD

**Issue by hsiddiqui** [gogits/gogs#4272]
- Gogs version: 0.9.141
- Git version: 2.7.4
- Operating system: Amazon Linux AMI release 2016.09
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
No errors - the updates to the repo work fine

## Description
I have set up a mirror repos for an existing gogs repo by updating the config for the mirror git repo (instead of using the migrate feature on the UI). The config contains the following content:

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = true

[remote "origin"]
        url    = https://xxxx
        fetch  = +refs/*:refs/*
        mirror = true
```

During chef run, this config gets added and a git fetch --all is run to fetch all branches and refs. i have also set up a cron job to run every 5 mins to take updates from the origin repo which works well (as the migrate functionality allows only hourly updates).

Using git log and git branch -a show the commits and all branches but upon logging into the UI, the branches do not get shown.

Could you please help me understand if there is any other config that i need to update to get the UI to show the repo correctly with all the branches just like the origin server repo.

Many Thanks

**Comment by Unknwon** [comment]
Hi,

1. Hack Gogs data gets no warranty of anything.
2. This is a place to ask questions.
3. If UI doesn't show branches, then you repo simply doesn't have such "branches"
4. Please use migration function.

**Comment by hsiddiqui** [comment]
thanks for the answers - please let me know if there is separate place to ask questions and post suggesstions about the gogs implementation.

**Comment by Unknwon** [comment]
Read the post template you deleted without thinking.

**Comment by hsiddiqui** [comment]
Thanks - found it!
