### ISSUE TITLE
/explore/repos does not show private repos for logged in users

### ISSUE THREAD

**Issue by hochhaus** [gogits/gogs#4274]
- Gogs version (or commit ref): 0.10.8
- Git version: git version 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

This issue a feature request to show private repos for which a logged in user has access on the "/explore/repos" page.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/3088.
