### ISSUE TITLE
[Feature Request] Support layered catalog in wiki like github.

### ISSUE THREAD

**Issue by ElderJames** [gogits/gogs#4275]
I think it would be more convenient to reading while wiki support layered catalog.

Thanks!

**Comment by Unknwon** [comment]
Hi, what is **layered catalog**?

**Comment by ElderJames** [comment]
Like this :)
![qq 20170311115623](https://cloud.githubusercontent.com/assets/7550366/23820384/0a30f37c-0652-11e7-85c7-f347db24db9e.png)

**Comment by Unknwon** [comment]
OK... duplicated to https://github.com/gogits/gogs/issues/3087.

**Comment by Unknwon** [comment]
No, actually this: https://github.com/gogits/gogs/issues/3931
