### ISSUE TITLE
remote: runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by fr33tux** [gogits/gogs#4276]
Hello,
When trying to push to a repository, I got the following stacktrace, after which a loop of "remote: Gogs: Internal error" is displayed:

> remote: runtime/cgo: pthread_create failed: Resource temporarily unavailable
> remote: SIGABRT: abort
> remote: PC=0x7f1fc0601067 m=5 sigcode=18446744073709551610
> remote: 
> remote: goroutine 0 [idle]:
> remote: 
> remote: goroutine 9 [syscall]:
> remote: runtime.notetsleepg(0x1528a98, 0xdf8458b0d, 0x0)
> remote: 	/home/git/local/go/src/runtime/lock_futex.go:205 +0x42 fp=0xc420029f60 sp=0xc420029f30
> remote: runtime.timerproc()
> remote: 	/home/git/local/go/src/runtime/time.go:209 +0x327 fp=0xc420029fe0 sp=0xc420029f60
> remote: runtime.goexit()
> remote: 	/home/git/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420029fe8 sp=0xc420029fe0
> remote: created by runtime.addtimerLocked
> remote: 	/home/git/local/go/src/runtime/time.go:116 +0xed
> remote: 
> remote: goroutine 1 [running]:
> remote: 	goroutine running on other thread; stack unavailable
> remote: 
> remote: goroutine 17 [syscall, locked to thread]:
> remote: runtime.goexit()
> remote: 	/home/git/local/go/src/runtime/asm_amd64.s:2197 +0x1
> remote: 
> remote: goroutine 5 [select]:
> remote: github.com/gogits/gogs/vendor/gopkg.in/clog%2ev1.init.3.func1()
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/clog.v1/logger.go:74 +0x15b
> remote: created by github.com/gogits/gogs/vendor/gopkg.in/clog%2ev1.init.3
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/clog.v1/logger.go:81 +0x35
> remote: 
> remote: goroutine 18 [select]:
> remote: github.com/gogits/gogs/vendor/gopkg.in/clog%2ev1.(*console).Start(0xc4201a3620)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/clog.v1/console.go:84 +0x1be
> remote: created by github.com/gogits/gogs/vendor/gopkg.in/clog%2ev1.New
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/clog.v1/logger.go:121 +0x17b
> remote: 
> remote: rax    0x0
> remote: rbx    0x7f1fc0972708
> remote: rcx    0xffffffffffffffff
> remote: rdx    0x6
> remote: rdi    0x3b59
> remote: rsi    0x3b5e
> remote: rbp    0xef62cb
> remote: rsp    0x7f1fbedc79f8
> remote: r8     0xa
> remote: r9     0x7f1fbedc8700
> remote: r10    0x8
> remote: r11    0x206
> remote: r12    0x0
> remote: r13    0x34
> remote: r14    0x0
> remote: r15    0xf3
> remote: rip    0x7f1fc0601067
> remote: rflags 0x206
> remote: cs     0x33
> remote: fs     0x0
> remote: gs     0x0

Another one:
> Delta compression using up to 8 threads.
> Compressing objects: 100% (3/3), done.
> Writing objects: 100% (3/3), 486 bytes | 0 bytes/s, done.
> Total 3 (delta 2), reused 0 (delta 0)
> remote: runtime/cgo: pthread_create failed: Resource temporarily unavailable
> remote: runtime/cgo: pthread_create failed: Resource temporarily unavailable
> remote: SIGABRT: abort
> remote: PC=0x7f6e87662067 m=5 sigcode=18446744073709551610
> remote: 
> remote: goroutine 0 [idle]:
> remote: 
> remote: goroutine 9 [syscall]:
> remote: runtime.notetsleepg(0x1528a98, 0xdf845e220, 0x0)
> remote: 	/home/git/local/go/src/runtime/lock_futex.go:205 +0x42 fp=0xc420029f60 sp=0xc420029f30
> remote: runtime.timerproc()
> remote: 	/home/git/local/go/src/runtime/time.go:209 +0x327 fp=0xc420029fe0 sp=0xc420029f60
> remote: runtime.goexit()
> remote: 	/home/git/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420029fe8 sp=0xc420029fe0
> remote: created by runtime.addtimerLocked
> remote: 	/home/git/local/go/src/runtime/time.go:116 +0xed
> remote: 
> remote: goroutine 1 [select, locked to thread]:
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.(*Command).RunInDirTimeoutPipeline(0xc420011c00, 0xdf8475800, 0x0, 0x0, 0x1395a00, 0xc42011e7e0, 0x1395a00, 0xc42011e850, 0x411122, 0xc420011c00)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/command.go:83 +0x44e
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.(*Command).RunInDirTimeout(0xc420011c00, 0xffffffffffffffff, 0x0, 0x0, 0xc4200973b8, 0x7f6e87dca000, 0xc4200973b8, 0x411978, 0x40)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/command.go:104 +0xbb
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.(*Command).RunTimeout(0xc420011c00, 0xffffffffffffffff, 0x817df1, 0xdc4120, 0xc420011c00, 0xc420011c00)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/command.go:139 +0x4b
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.(*Command).Run(0xc420011c00, 0x1, 0x1, 0xc420011c00, 0x7f6e87dca000)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/command.go:149 +0x34
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.BinVersion(0x460fed, 0xd92ac0, 0xc420015c10, 0xc420015c10)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/git.go:47 +0xa3
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.init.1()
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/git.go:69 +0x22
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.init()
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/utils.go:94 +0xf0
> remote: github.com/gogits/gogs/models.init()
> remote: 	/home/git/go/src/github.com/gogits/gogs/models/wiki.go:180 +0x7d
> remote: github.com/gogits/gogs/cmd.init()
> remote: 	/home/git/go/src/github.com/gogits/gogs/cmd/web.go:711 +0x6c
> remote: main.init()
> remote: 	/home/git/go/src/github.com/gogits/gogs/gogs.go:43 +0x4e
> remote: 
> remote: goroutine 17 [syscall, locked to thread]:
> remote: runtime.goexit()
> remote: 	/home/git/local/go/src/runtime/asm_amd64.s:2197 +0x1
> remote: 
> remote: goroutine 5 [select]:
> remote: github.com/gogits/gogs/vendor/gopkg.in/clog%2ev1.init.3.func1()
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/clog.v1/logger.go:74 +0x15b
> remote: created by github.com/gogits/gogs/vendor/gopkg.in/clog%2ev1.init.3
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/clog.v1/logger.go:81 +0x35
> remote: 
> remote: goroutine 8 [runnable]:
> remote: github.com/gogits/gogs/vendor/github.com/gogits/git-module.(*Command).RunInDirTimeoutPipeline.func1(0xc4200168a0, 0xc420074b00)
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/command.go:78
> remote: created by github.com/gogits/gogs/vendor/github.com/gogits/git-module.(*Command).RunInDirTimeoutPipeline
> remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/gogits/git-module/command.go:80 +0x1e2
> remote: 
> remote: rax    0x0
> remote: rbx    0x7f6e879d3708
> remote: rcx    0xffffffffffffffff
> remote: rdx    0x6
> remote: rdi    0x4d2d
> remote: rsi    0x4d32
> remote: rbp    0xef62cb
> remote: rsp    0x7f6e85e289f8
> remote: r8     0xa
> remote: r9     0x7f6e85e29700
> remote: r10    0x8
> remote: r11    0x206
> remote: r12    0x0
> remote: r13    0x34
> remote: r14    0x0
> remote: r15    0xf3
> remote: rip    0x7f6e87662067
> remote: rflags 0x206
> remote: cs     0x33
> remote: fs     0x0
> remote: gs     0x0
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> "remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error
> remote: Gogs: Internal error

The load increases a lot during this loop.
There isn't any problem to clone or pull, and it didn't happen with the previous Gogs versions.

Gogs: 0.10.8.0307
Git: 2.5.0
Debian: 8, x64

Thanks,

**Comment by Unknwon** [comment]
Hi, if you have not ever used custom Git hooks, delete all `custom_hooks` subdirs on your `gogs-repositories` can solve the problem. 

Maybe helpful: https://github.com/jenkinsci/gogs-webhook-plugin/issues/14#issuecomment-283833592
