### ISSUE TITLE
Repositories panel in personal settings

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#4277]
List all accessible repositories and their sizes.

Related: https://github.com/gogits/gogs/issues/1158#issuecomment-246634622

**Comment by master-d** [comment]
I could work on this if @DblK doesn't want it

**Comment by Unknwon** [comment]
Blocked by https://github.com/gogits/gogs/pull/4289.

**Comment by Unknwon** [comment]
Closed by https://github.com/gogits/gogs/pull/4312, can be tested on https://try.gogs.io/user/settings/repositories.
