### ISSUE TITLE
Unable to modify picture

### ISSUE THREAD

**Issue by yumemor** [gogits/gogs#4278]
- Gogs version (or commit ref): 0.9.128.0131
- Git version: 1.7.1
- Operating system: centos 6.8 64bit
- Database (use `[x]`):
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes

## Description

Unable to modify picture This includes：The person's image | organization logo

**Comment by Unknwon** [comment]
Hi, please read post template very carefully, I don't know what you are saying.

**Comment by mwaeckerlin** [comment]
I have the same problem, in `https://my.site/org/orgname/settings`:
1. Upload a new PNG-image for an organisation → Result: Still the initial default profile image is shown.
2. Remove the profile image → This works, a 45°-turned `G` is shown, nmot the logo
3. Upload a new PNG-image for an organisation → Result: The initial default profile image is restored.

**Comment by mwaeckerlin** [comment]
Proxy settings look good, they are:
```
server {
  listen 443;
  server_name mrw.sh;
  ssl on;
  ssl_certificate /etc/letsencrypt/live/mrw.sh/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mrw.sh/privkey.pem;
  location / {
    include proxy.conf;
    if ($request_method ~ ^COPY$) {
      rewrite /(.*) /$1 break;
    }
    #if ( $host != 'mrw.sh' ) {
    #  rewrite ^/(.*)$ $scheme://mrw.sh/$1 permanent;
    #}
    proxy_cookie_domain universum mrw.sh;
    proxy_cookie_path / /;
    proxy_pass http://universum:8012/;
    proxy_redirect http://universum:8012/ /;
    proxy_redirect http://universum:8012/ $scheme://mrw.sh/;
    proxy_redirect / $scheme://mrw.sh/;
    proxy_redirect / /;
    proxy_redirect / $scheme://mrw.sh/;
    subs_filter "http://universum:8012" "$scheme://mrw.sh";
    subs_filter "universum:8012" "mrw.sh";
  }
}
```

With `proxy.conf`:
```
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
set $ssl off;
if ($scheme = https) {
    set $ssl on;
}
proxy_set_header X-Forwarded-Ssl $ssl;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Accept-Encoding "";
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Original-Request $request_uri;
proxy_pass_request_headers on;
#proxy_cache off;
#proxy_buffering off;
client_max_body_size 4096m;
client_body_buffer_size 128k;
proxy_connect_timeout 300;
proxy_send_timeout 300;
proxy_read_timeout 300;
proxy_buffers 32 4k;
subs_filter_types text/css text/javascript text/xml;
set $fixed_destination $http_destination;
if ( $http_destination ~* ^https(.*)$ ) {
  set $fixed_destination http$1;
}
proxy_set_header Destination $fixed_destination;
```

So, I don't think it's the reverse-proxy?

**Comment by Unknwon** [comment]
Not sure if it's the problem with reverse proxy, but you definitely need hard refresh after changing the picture.

**Comment by mwaeckerlin** [comment]
Without any changes on gogs, now all pictures are there, so it was either caching or the proxy. Probably the caching, since I just compared, proxy settings haven't changed.

What is a «hard refresh»? Shouldn't that be done automatically when it's necessary?

**Comment by Unknwon** [comment]
@mwaeckerlin https://www.google.com/search?q=What+is+a+%C2%ABhard+refresh&oq=What+is+a+%C2%ABhard+refresh&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8

**Comment by mwaeckerlin** [comment]
Ah, you don't mean on server side. Sorry for the misunderstanding. At least a force-/shift-reload didn't help. Shouldn't that be fixed in the caching/refresh hints passed by the server in the http-headers?

**Comment by Unknwon** [comment]
Keep refreshing until it works. Gogs doesn't cache images, your browser and/or proxy does...
