### ISSUE TITLE
Add support for migrating from SSH

### ISSUE THREAD

**Issue by Flippylosaurus** [gogits/gogs#4279]
Hi. We have about 30 repositories on another Git server which we would like to migrate to Gogs. The problem is that this server is only accessible by SSH and with a key-based authentication.
It would be much appreciated to allow this. 

This can be achieved by allowing users to upload private keys to the Gogs server, which will be used for communicating with the server. 

A user will only be able to clone using his keys. It would be even better if keys can also be assigned to organisations. 

In my opinion keys should not be viewable after uploading. If they should be visible, only the owner or owner of a organisation should be able to view them.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1565.
