### ISSUE TITLE
Windows mws "leaking" files to %WINDIR% System32 / SYSWOW64

### ISSUE THREAD

**Issue by guido1g** [gogits/gogs#4285]
- Gogs version (or commit ref): 10.0.8
- Git version: 2.12
- Operating system: Win Srv 2012R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

When started as a service, some files are created in C:\Windows\SysWow64\Data (for x86) or C:\Windows\System32\Data (amd64)
These are (if only set /data/gogs.db and not C:/GOGS/DATA/gogs.db) the gogs.db
the folders "session" and "temp" (with local-repo/*)
There should be a way to make them "permanent" in the app.ini so you wont wonder "WTF? I just deleted everything and all users and organisations are still there???" or strange behaviour during "changing file via web"

So my old request "database gets corrupted" just disolved in "now you can see me..." ;)
...

**Comment by Unknwon** [comment]
Hi, I think this is duplicated to https://github.com/gogits/gogs/issues/4260. You can comment on that.

**Comment by guido1g** [comment]
it's partly #4260. I confirm the db --- if you just fill in data/gogs.db. If you enter (as shown) a full path like C:\gogs\data\gogs.db this is used. 
BUT tmp and the subfolders still reside in system32 and/or syswow64. 
There should be a "basedir" or something of the like so ALL gogs-folders are in one location (for backup and problem solving highly appreciated) ;)
![17-gogs-files-system32](https://cloud.githubusercontent.com/assets/20678698/23891604/840b778e-0897-11e7-9379-e71b5a301afb.png)

**Comment by Unknwon** [comment]
Why DB setting has anything to do with session? I do not understand the logic and relation here.

**Comment by guido1g** [comment]
the DB is stored correctly in "C:\GOGS\data\gogs.db" if the setting in NOT "data/gogs.db" but "C:/gogs/data/gogs.db".
If you set only "data/gogs.db" (as on linux), it's stored in SYSWOW64 or System32 - depending on the version. If you install i386 on an amd64, it's SYSWOW64. The same path gogs is using für session, temp, local-* and so on.

**Comment by Unknwon** [comment]
Maybe helpful: https://discuss.gogs.io/t/gogs-ignores-app-data-path-from-custom-conf-app-ini/982/6

**Comment by Unknwon** [comment]
https://gogs.io/docs/advanced/configuration_cheat_sheet#server-(server), `APP_DATA_PATH`.
