### ISSUE TITLE
Gogs doesn't seem to care about the config file?

### ISSUE THREAD

**Issue by mortie** [gogits/gogs#4286]
- Gogs version (or commit ref): 0.10.8 (0.10.8-1489430993.f0209ac.jessie 0)
- Git version: 2.1.4
- Operating system: Debian Jessie (Linux weblet 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/mortie/0adfe5d5e82d02f5c01f82e882944f6f

## Description

Gogs doesn't seem to care about the content in my config file. The file `/etc/gogs/conf/app.ini` contains `HTTP_PORT = 8082` under `[server]`, while `/opt/gogs/conf/app.ini` (not modified by me) contains `HTTP_PORT = 3000` under `[server]`, yet Gogs listens to port 6000.

This started happening after an update. I'm not sure which, but I know Gogs used to run on port 8082, and without touching the configuration for a while, it doesn't anymore.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/4188.

PS: there is nothing I can do for you about packager.io.

**Comment by mortie** [comment]
If the packager.io packages don't work, it might be a good idea to remove them from the installation section of your website (https://gogs.io/docs/installation/install_from_packages), or update the stuff about configuring gogs (https://gogs.io/docs/installation/configuration_and_run). I know it says they're third-party, but I imagine most people whose distribution don't natively package gogs will see that page and attempt to use packager.io, and a small mention about how packager.io uses /etc/default/gogs for some settings would probably save a lot of people a lot of time and frustration.

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/23878778/c33a0a60-081f-11e7-95a9-c1679582a799.png)

**Comment by mortie** [comment]
I know it says they're third-party providers. Fact still stands though, that it's a part of your official documentation, and therefore, you have to expect that most of your users are using packages from packager.io. It wouldn't take much to add a tiny sentence to the configuration page about how packager.io uses /etc/default/gogs for some settings.

**Comment by mortie** [comment]
Having thought it over for a second, I can kind of see why you wouldn't necessarily want to add that documentation; the fact that it changed without your knowledge once might mean it will again, and documenting where packager.io has its config file might therefore be an extra maintenance burden. Maybe just add a line about how packager.io might put config files in other places, instead of specifying exactly where they are?

**Comment by Unknwon** [comment]
OK, added: https://gogs.io/docs/installation/install_from_packages
