### ISSUE TITLE
A branch always display in protected branches even it's canceled or deleted

### ISSUE THREAD

**Issue by JayceChant** [gogits/gogs#4288]
- Gogs Version: 0.10.8.0307: 
- Git version: 1.9.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (settings is not a public url)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

### path:

1. enter an repo
2. settings > branches > Protected Branches > Choose a branch to protect > the branch display on the protected list
3. after a period of time, the branch is useless, I cancel the protect (click the branch on the protected list > uncheck `Protect this branch`) > the branch STILL DISPLAY on the list
4. delete the branch > still on the list
5. click it > 404 ERROR

### problems:

* How to cancel a protected branch and remove it from the protected list?
* The link still exists even after the branch is deleted lead to 404 error.

**Comment by Unknwon** [comment]
1. It is intended to still list the branch if you disabled the protection.
2. But indeed it is a bug to show a branch that has been deleted.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by JayceChant** [comment]
I tested on https://try.gogs.io , it's fixed according to your explanation.

However, I think a place to disable a branch to display on the list is still needed.
For example, I make a mistake and choose a wrong branch to protect, and it always list there even I disabled the protection. It do harm  to completists. ^^
Maybe this should be considered as a new feature, not a bug.
