### ISSUE TITLE
Markdown rendering of raw text / code

### ISSUE THREAD

**Issue by irunonayran** [gogits/gogs#4291]
- Gogs version (or commit ref):  0.10.8.0307
- Git version: 
- Operating system: debian jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/irunonayran/rendering_error_raw_text/src/master/README.md)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
There seems to be a markdown rendering bug when having text in the following format (replace hyphens with backticks)
```
'''sometext'''
[optional text]
'''
some code
'''
```
If the first raw string contains two words, it is rendered correctly

**Comment by master-d** [comment]
I looked at this issue briefly and I think it has to do with how the blackfriday markdown renderer is configured to parse markdown code.  I think you need a space after the code fence start and before the end of the code fence in order for the blackfriday renderer to process it correctly.   

[issue 227](https://github.com/russross/blackfriday/issues/227) from the blackfriday project page seems to be related

**Comment by Unknwon** [comment]
Hi, thanks for the feedback, but Gogs only supports standard Markdown, which is:

    ```
    some code
    ```

For inline code block, use:

    `somecode`
