### ISSUE TITLE
unable to upload custom gif avatar

### ISSUE THREAD

**Issue by vilinski** [gogits/gogs#4293]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 1.7.12.4
- Operating system: SUSE Linux Enterprise Server 11 SP3  (x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) https://try.gogs.io/user/settings/avatar
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

```
    [Macaron] 2017-03-15 15:16:55: Started POST /user/settings/avatar for 10.20.12.46
    [Macaron] 2017-03-15 15:16:55: Completed POST /user/settings/avatar 302 Found in 69.037355ms
    [Macaron] 2017-03-15 15:16:55: Started GET /user/settings/avatar for 10.20.12.46
    [Macaron] 2017-03-15 15:16:55: Completed GET /user/settings/avatar 200 OK in 1.865374ms
    [Macaron] 2017-03-15 15:16:55: Started GET /css/semantic-2.2.7.min.css for 10.20.12.46
    [Macaron] [Static] Serving /css/semantic-2.2.7.min.css
    [Macaron] 2017-03-15 15:16:55: Started GET /css/gogs.css?v=cb974d447af2d8d7be110e462f2f5638 for 10.20.12.46
    [Macaron] [Static] Serving /css/gogs.css
    [Macaron] 2017-03-15 15:16:55: Completed GET /css/gogs.css?v=cb974d447af2d8d7be110e462f2f5638 200 OK in 14.004283ms
    [Macaron] 2017-03-15 15:16:55: Completed GET /css/semantic-2.2.7.min.css 200 OK in 30.142275ms
```

- Maybe also relevant my `config.ini`:

```
[server]
PROTOCOL = https
...
OFFLINE_MODE = true
...

[picture]
DISABLE_GRAVATAR = true
ENABLE_FEDERATED_AVATAR = false

...
```

## Description
1. Go to user settings -> Avatar (https://try.gogs.io/user/settings/avatar)
 2. Select "Custom Avatar" and a somepicture.gif from computer
In case of **gif** I get an error `UploadAvatar: Decode: image: unknown format` and nothing is changed.  I can upload avatar.png however. 
I have not found any info about which format are currently supported. Can you provide a link or just say me?
...

**Comment by Unknwon** [comment]
Hi... yes, it is not supported, you can only upload PNGs or JPEGs.
