### ISSUE TITLE
Prefer user namespaces to gosu

### ISSUE THREAD

**Issue by aaronjwood** [gogits/gogs#4299]
Instead of using gosu in all of these places https://github.com/gogits/gogs/search?utf8=%E2%9C%93&q=gosu I propose that it be removed. There could be some documentation written that explains to users how/why you'd use user namespaces.

One big advantage from switching to this model is you are no longer root on the host when you run your container, regardless of what user you are inside of the container. With gosu you are still `root` on the host even though inside of the container you are `git`.

User namespaces are great from a security perspective and it would be nice to further harden Gogs with this feature.

Some more info on user namespaces:
https://lwn.net/Articles/532593/
https://success.docker.com/KBase/Introduction_to_User_Namespaces_in_Docker_Engine

**Comment by Unknwon** [comment]
Hi, thanks for the info!

What should we do?

**Comment by aaronjwood** [comment]
You're welcome! I propose that gosu be removed and instead just rely on having the user make use of user namespaces. I guess you could use user namespaces along with gosu (the `git` user inside of the container) but I was thinking that you could reduce your components/complexity inside of the container by just falling back on yet another kernel-enforced isolation feature.

I'm not sure how others will feel about this, maybe some people won't want to use user namespaces and would prefer to just stick with the `git` user inside of the container.

**Comment by Unknwon** [comment]
>but I was thinking that you could reduce your components/complexity inside of the container by just falling back on yet another kernel-enforced isolation feature.

Not sure how this would be done, but I think it's good to keep `git` user as it is now.

**Comment by aaronjwood** [comment]
If you didn't use the `git` user (and removed gosu from the picture as well) then it'd be up to people to make use of the user namespace feature in Docker 1.10+. I would much rather have real user namespaces than a fake user in the container since with user namespaces you're executing in the context of whatever user you decide to map on the host. Without user namespaces everything is still effectively root everywhere outside of the container.

**Comment by Unknwon** [comment]
For whatever change, I prefer not remove `git` user. Other than that, I have no expertise about what should we do...

**Comment by aaronjwood** [comment]
Okay, then I guess you can close out this issue. I've never tried using user namespaces with gosu so I'm not sure it'll work. There might not be enough privileges inside of the container (with user namespaces enabled, since you are no longer root on the host) to do all of the setuid, etc. stuff that it does. Also, it's not possible to run `--privileged` with user namespace as they totally defeat each other when used together.

**Comment by Unknwon** [comment]
OK... current setup works very well, I think no need to do such changes, besides 1.10+ sounds very high version to me, could break a lot installations.

**Comment by aaronjwood** [comment]
I hope not! :) 1.10 is pretty old now (https://github.com/docker/docker/blob/master/CHANGELOG.md#1100-2016-02-04) and there are a lot of security fixes and enhancements in the newer versions.

Thanks anyway for considering this.

**Comment by Unknwon** [comment]
Hmm... some people I know still using Gogs more than two years old, so I would not think 1 year is enough to make break changes.

**Comment by aaronjwood** [comment]
I see. So you are worried about people using newer releases/containers of Gogs but on top of old Docker versions?

**Comment by Unknwon** [comment]
Yes..
