### ISSUE TITLE
Gogs doesn't return memory after big commit pushed.

### ISSUE THREAD

**Issue by kybin** [gogits/gogs#4302]
- Gogs version (or commit ref): 0.9.97
- Git version: 1.7.1
- Operating system: Centos6.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Our server has only 2GB of ram.

During 450MB size commit pushed, gogs uses large memory and it doesn't return the memory after the push finished.

So we encounter 500 error(when exceeded memory), or service becomes slow down.

**Comment by Unknwon** [comment]
Hi, version too old, please upgrade.
