### ISSUE TITLE
Can't send mail via gmail smtp

### ISSUE THREAD

**Issue by gempir** [gogits/gogs#4310]
- Gogs version (or commit ref): 0.10.18
- Git version: 2.1.4
- Operating system: Debian Jessie 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/03/18 15:28:55 [ERROR] [.../runtime/asm_amd64.s:2197 goexit()] Fail to send emails [myRecevingEmail@something.com]: UID: 1, reset password - gomail: could not send email 1: dial tcp 173.194.79.108:587: getsockopt: connection timed out
## Description
So I was hoping to use gmail to send mails in gogs. My config is very simple:
```
[mailer]
ENABLED = true
HOST    = smtp.gmail.com:587
FROM    = my.email@gmail.com
USER    = my.email@gmail.com
PASSWD  = myPassword
```
I tried switching port to 465 but this won't work either. The error I get is above, I'm sure the password is correct and can't really tell why gogs won't connect to gmail.
...

**Comment by Unknwon** [comment]
>this won't work either

Prove your words.

>dial tcp 173.194.79.108:587: getsockopt: connection timed out

Looks like your firewall connection problem.

**Comment by gempir** [comment]
Same issue with port 465:

`2017/03/18 18:48:46 [ERROR] [.../runtime/asm_amd64.s:2197 goexit()] Fail to send emails [myEmail@gmail.com]: UID: 1, reset password - gomail: could not send email 1: dial tcp 173.194.79.108:465: getsockopt: connection timed out`

I'm running on a scaleway debian vps. I never had any issues relating firewalls, I had bitbucket installed earlier on that same vps and it could send mails just fine over the same account.

**Comment by Unknwon** [comment]
>I'm running on a scaleway debian vps. I never had any issues relating firewalls, I had bitbucket installed earlier on that same vps and it could send mails just fine over the same account.

I've been using `smtp.gmail.com:587` for my Gogs over two years without any error related to `getsockopt: connection timed out` on my DO VPS.

Maybe helpful: https://forums.cpanel.net/threads/cant-send-emails-via-gmail-smtp-timeout-error.480811/

**Comment by gempir** [comment]
I'm so sorry I now realize my mistake. 

I didn't run bitbucket on the same vps and scaleway has a default security setting which blocks smtp.

Thanks for the help though, without it I probably would have needed a few days to figure that one out.
