### ISSUE TITLE
Update profile for non-local users fails: Name cannot be empty

### ISSUE THREAD

**Issue by dtrv** [gogits/gogs#4313]
Gogs version 0.10.18.0313
Debian GNU/Linux 8 (jessie)

Using LDAP (via BindDN) to authenticate user, the users can't change their profile settings.
Because for non-local user it's not allowed to change the user name, it seems that the user name is not sent to within the update request.

So "Name cannot be empty." pops up and updating the profile settings is not possible.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by dtrv** [comment]
dev branch, Gogs version 0.10.24.0320
Debian GNU/Linux 7 (wheezy)
Again Auth via LDAP (BindDN).

Update Profile settings for non-local users is possible. Thanks for patching!
