### ISSUE TITLE
Certificate type not approved for application.

### ISSUE THREAD

**Issue by fanux** [gogits/gogs#4314]
I am run gogs:0.10.8 in container,  using https, came out an error:`Certificate type not approved for application.` when `git push -u origin master`

I use the command to generate .pem:

`./gogs cert -ca=true -duration=8760h0m0s -host=10.1.86.51`

**Comment by Unknwon** [comment]
Hi, I think it's client side problem, and this is the risk you take by using self-signed certificate.

Maybe helpful: http://stackoverflow.com/questions/16971589/certificate-purpose-when-is-it-validated
