### ISSUE TITLE
Redirect to random issue if index does not exist

### ISSUE THREAD

**Issue by hhstore** [gogits/gogs#4315]
## error:

- normal URL: `http://192.168.8.88:10080/web-service/lezu/issues/2`
- exception URL: `http://192.168.8.88:10080/web-service/lezu/issues/2%23issuecomment-9`
- real URL: `http://192.168.8.88:10080/web-service/lezu/issues/2#issuecomment-9`

## situation:
- in exception url :
    - `issue2 comments` has mixed `issue1 comments`, which not belong to it.

## normal case:
![0001](https://cloud.githubusercontent.com/assets/3252130/24087991/54160bd4-0d60-11e7-80b2-c2872fef891c.png)

## exception case:

![0002](https://cloud.githubusercontent.com/assets/3252130/24087994/5d323cd8-0d60-11e7-852a-604c11f4da79.png)

- exception url
- `issue2 comments` has mixed `issue1 comments`, which not belong to it.

## gogs version:

-  version: `0.10.8.0307`

**Comment by hhstore** [comment]
## URL encode:

- exception URL: http://192.168.8.88:10080/web-service/lezu/issues/2%23issuecomment-9
- real URL: http://192.168.8.88:10080/web-service/lezu/issues/2#issuecomment-9

- `#` utf-8 encode is `%23`.

**Comment by Unknwon** [comment]
Hi,

How does Gogs know you really want to visit `%23issuecomment-9` or `#issuecomment-9`?

**Comment by hhstore** [comment]
## github do:

- in real URL, parse ok.
- in exception URL ( `#` => `%23`), return `404 page`.
    - I think `404 page`  is fine.

**Comment by Unknwon** [comment]
I don't understand the problem here, what wrong thing can happen if you visit with `%23`?

**Comment by hhstore** [comment]
## github : 

- just return `404 page`, when url : `#` =>`%23`.


![Uploading 0000000000.png…]()

**Comment by hhstore** [comment]
![Uploading 000====.png…]()

**Comment by Unknwon** [comment]
? What does this broken image prove?

**Comment by hhstore** [comment]
![Uploading retu 404.png…]()

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
