### ISSUE TITLE
Milestone overview shows different number of closed issues/milestones

### ISSUE THREAD

**Issue by arthur-bauer** [gogits/gogs#4316]
- Gogs version (or commit ref): 0.10.18
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

The milestones overview shows a different amount of closed items than the actual milestone when you click on it. 

It seems that, in the overview, gogs displays both closed **issues** and closed **pull requests**, but after clicking on the milestone, it displays only the number of closed **issues**. This should be handled consistently instead.

![screen shot 2017-03-20 at 13 28 57](https://cloud.githubusercontent.com/assets/4696542/24099834/9fcdfc2e-0d71-11e7-91fd-53af781c7d62.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by arthur-bauer** [comment]
Opened and closed issues are now displayed correctly, but the green progress bar still counts issues and PR. 

![bildschirmfoto 2017-03-24 um 23 05 57](https://cloud.githubusercontent.com/assets/4696542/24315286/7e90692a-10e6-11e7-8b5b-8abd2ce62edd.png)

**Comment by Unknwon** [comment]
Good catch, please check demo site again.

**Comment by arthur-bauer** [comment]
Looks good now. 👍
