### ISSUE TITLE
Label character encoding bug

### ISSUE THREAD

**Issue by arthur-bauer** [gogits/gogs#4318]
- Gogs version (or commit ref): 0.10.18
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Labels that contain apostrophes `'` are displayed incorrectly. Seems they are html-encoded twice:

![screen shot 2017-03-20 at 14 38 55](https://cloud.githubusercontent.com/assets/4696542/24102087/1502a216-0d7b-11e7-80e1-372b1f7658d2.png)

**Comment by Unknwon** [comment]
Related to https://github.com/gogits/gogs/issues/1937.

**Comment by Unknwon** [comment]
Hi, for security reason, this won't be fixed, you can use GitHub's convention: `Dont merge`.
