### ISSUE TITLE
Add flag of archive name for backup command

### ISSUE THREAD

**Issue by ModdyLP** [gogits/gogs#4320]
Hello, 

as we have discussed here(https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991/5), i would like to see a parameter to adjust the file name for the backup target file.

Best Regards
ModdyLP

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch, see details on https://github.com/gogits/gogs/commit/8ce23e2c7153aeea2f44cd0355511130bdb5f285.
