### ISSUE TITLE
how redmine+gogs intergrate ？bug？

### ISSUE THREAD

**Issue by hanjs0310293** [gogits/gogs#4322]
# 环境描述：
centos6.6。
nginxnginx version: nginx/1.10.2
passenger passenger-5.1.2。
应用安装了redmine3.1.1。
gogs© 2017 Gogs 当前版本: 0.10.18.0313，
所有的应用都安装在git用户git组下。
# 问题描述
向gogs仓库commit后，redmine的issue不更新状态，无论使用git clone还是git clone --mirror建立的还仓库还是gogs的本地仓库都不更新，开始怀疑是权限问题，下面是尝试过程，全无效。
但是在本地使用命令行，在git用户下建立一个仓库，修改文件，commit后，redmine指向这个仓库，issue状态更新了。
过程中还使用了
curl "192.168.188.12:3000/sys/fetch_changesets?key=UUFnQf6piaD4ZsWwFo3t"和 
rake -f /home/redmine/redmine-2.4.0/Rakefile RAILS_ENV=production redmine:fetch_changesets
无效
redmine的配置检查无问题。
1. test
1. test hook
1. test hook
1. modify dictionary owner，有效
1. chmod 777
1. tset redmine use gogs
1. test u+s，无效
1. chown redmine to git
1. modify nginx worker to git
1. modify test.git manual
1. modify redmine configure's log no
1. open passenger log
1. why git update fail,yes no problem
1. Implement feature #1 @2h  d 
1. Development feature #1 @2h  d no
1. modify u+s no
1. test http git agins ,no fact
1. update #3
1. update #3
1. add nobody to git group
1. 测试url agins

**Comment by baikangwang** [comment]
Did you push the commit?
```
git push
```

**Comment by Unknwon** [comment]
1. Please read issue post template.
2. [Smart commits](https://discuss.gogs.io/t/how-to-use-smart-commits/55) only works for Gogs internal issue tracker.

**Comment by hanjs0310293** [comment]
of course I push

**Comment by hanjs0310293** [comment]
turn out to be the time problem, cause the datetime of redmine server is not synchronized with gogs, thx everyone!

**Comment by Unknwon** [comment]
..... good to hear you found the problem. Although I still don't know what happened :sweat_smile:
