### ISSUE TITLE
Users with only "Issue rights" ?

### ISSUE THREAD

**Issue by Metti9** [gogits/gogs#4323]
is there a way, that a user add issues without see the sourcecode ?
Can i give user any rights ?

**Comment by Fastidious** [comment]
@Metti9 no. Create an empty repository just for issues, if that is what you want.

**Comment by Unknwon** [comment]
I think this is duplicated/part of https://github.com/gogits/gogs/issues/1411.

Or you may also be interested in https://github.com/gogits/gogs/issues/649.
