### ISSUE TITLE
Can't create pull request from the fork of another fork

### ISSUE THREAD

**Issue by nook-ru** [gogits/gogs#4324]
- Gogs version (or commit ref): 0.10.24.0320
- Git version: 2.8.2
- Operating system: CentOS release 6.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/test-org-1/test/compare/master...test-org-2:master)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
https://gist.github.com/nook-ru/3c8c62028148003071855df2a932c408

## Description

Steps to preproduce:

1. Fork a repo, then fork again from that forked repo  
    * https://try.gogs.io/nook_ru/test
      * fork → https://try.gogs.io/test-org-1/test
        * fork → https://try.gogs.io/test-org-2/test
2. Trying to create pull request by clicking *Compare* button on the [last fork](https://try.gogs.io/test-org-2/test)
3. Getting error message `template: repo/header:13:96: executing "repo/header" at <.BaseRepo.Link>: can't evaluate field Link in type *models.Repository`

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by nook-ru** [comment]
@Unknwon, seems to be ok now, thank you. PRs are created and merged correctly.
