### ISSUE TITLE
Settings UI consistency

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4327]
- Gogs version (or commit ref): `N/A`
- Git version: `N/A`
- Operating system: `N/A` 
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) https://try.gogs.io/user/settings/delete and https://try.gogs.io/user/settings/password
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

The password field on "Delete Account" should match the rest on the settings page. Right now it looks out of place.

**Regular fields:**

![Change Password](https://cloud.githubusercontent.com/assets/8352292/24176670/c08bb14c-0e73-11e7-85a3-fb4f63d0a061.png)

**Not matching:**

![Delete account](https://cloud.githubusercontent.com/assets/8352292/24176688/d440dabe-0e73-11e7-8a42-ce2a5c0a46a0.png)

**Comment by Fastidious** [comment]
Something like this (bad editing):

![d440dabe-0e73-11e7-8a42-ce2a5c0a46a0](https://cloud.githubusercontent.com/assets/8352292/24195518/78010992-0ed0-11e7-98f3-547156c626f3.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Fastidious** [comment]
Excellent!
