### ISSUE TITLE
Gogs Deployent over https: "tls: fails to parse ssl private key"

### ISSUE THREAD

**Issue by bmerlet90** [gogits/gogs#4328]
- Gogs version (or commit ref): 0.10.18.0313
- Git version:  1.9.1
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):

2017/03/22 11:28:07 [TRACE] Log Mode: File (Trace)
2017/03/22 11:28:07 [ INFO] Gogs: Go Git Service 0.10.18.0313
2017/03/22 11:28:07 [ INFO] Cache Service Enabled
2017/03/22 11:28:07 [ INFO] Session Service Enabled
2017/03/22 11:28:07 [ INFO] Mail Service Enabled
2017/03/22 11:28:07 [ INFO] Register Mail Service Enabled
2017/03/22 11:28:07 [ INFO] Notify Mail Service Enabled
2017/03/22 11:28:07 [ INFO] Git Version: 1.9.1
2017/03/22 11:28:07 [ INFO] SQLite3 Supported
2017/03/22 11:28:07 [ INFO] Run Mode: Production
2017/03/22 11:28:07 [TRACE] Doing: CheckRepoStats
2017/03/22 11:28:08 [ INFO] Listen: https://0.0.0.0:443/gogs
2017/03/22 11:28:08 [FATAL] [...rfave/cli/command.go:193 Run()] Fail to start server: tls: failed to parse private key

## Description
I'm trying to migrate a existing Gogs server to https. 

Here is the relevant gogs server config (`custom/conf/app.ini`)
```
[server]
PROTOCOL = https
DOMAIN = my-domain.fr
HTTP_PORT = 443
ROOT_URL = https://my-domain.fr/gogs/
CERT_FILE = /etc/apache2/ssl/my-domain_fr.crt
KEY_FILE = /etc/apache2/ssl/private/my-domain.fr.key
```

Virtual host definition in `/etc/apache2/site-enabled/my-site.conf` :
```
<VirtualHost *:443>

        ServerAdmin webmaster@localhost

        DocumentRoot /var/www
        SSLEngine on
        SSLCertificateFile  /etc/apache2/ssl/my-domain_fr.crt
        SSLCertificateKeyFile /etc/apache2/ssl/private/my-domain.fr.key
        SSLCertificateChainFile /etc/apache2/ssl/DigiCertCA.crt

        .....

</VirtualHost>
```

I'm starting Gogs using a `git` user with the following commands:
```
cd gogs
./gogs web 
```

I get get the following output in the console:
```
2017/03/22 11:28:07 [TRACE] Custom path: /home/git/gogs/custom
2017/03/22 11:28:07 [TRACE] Log path: /home/git/gogs/log
2017/03/22 11:28:07 [TRACE] Log Mode: File (Trace)
2017/03/22 11:28:07 [ INFO] Gogs: Go Git Service 0.10.18.0313
```
 then nothing else happens.

What did I miss in the configuration ?

**Comment by Fastidious** [comment]
@bmerlet90 the `git` user doesn’t have read access to the keys.

**Comment by bmerlet90** [comment]
The git user does have access to the key:

I added that user to the ssl-cert group and the key has the following permission
`-rw-r----- 1 root ssl-cert  1743 mars  15 11:03 my-domain.fr.key `

**Comment by bmerlet90** [comment]
Before adding the git user to the `ssl-cert` group, I had the following error in the gogs logs:

`2017/03/22 10:43:41 [FATAL] [...rfave/cli/command.go:193 Run()] Fail to start server: open /etc/apache2/ssl/private/my-domain.fr.key: permission denied`

**Comment by Fastidious** [comment]
@bmerlet90 how about the directories above it? You might have found a bug, indeed. As a workaround (for now), why not to proxy thought Apache?

**Comment by Fastidious** [comment]
Hmm, you are trying to run `gogs` on port 443? I don’t think that will work.

**Comment by bmerlet90** [comment]
I tried both port 3000 and port 443 and got the same error:
```
2017/03/22 11:25:21 [TRACE] Log Mode: File (Trace)
2017/03/22 11:25:21 [ INFO] Gogs: Go Git Service 0.10.18.0313
2017/03/22 11:25:21 [ INFO] Cache Service Enabled
2017/03/22 11:25:21 [ INFO] Session Service Enabled
2017/03/22 11:25:21 [ INFO] Mail Service Enabled
2017/03/22 11:25:21 [ INFO] Register Mail Service Enabled
2017/03/22 11:25:21 [ INFO] Notify Mail Service Enabled
2017/03/22 11:25:21 [ INFO] Git Version: 1.9.1
2017/03/22 11:25:21 [ INFO] Git config user.name set to Gogs
2017/03/22 11:25:21 [ INFO] Git config user.email set to gogs@fake.local
2017/03/22 11:25:21 [ INFO] SQLite3 Supported
2017/03/22 11:25:21 [ INFO] Run Mode: Production
2017/03/22 11:25:21 [TRACE] Doing: CheckRepoStats
2017/03/22 11:25:21 [ INFO] Listen: https://0.0.0.0:3000/gogs
2017/03/22 11:25:21 [FATAL] [...rfave/cli/command.go:193 Run()] Fail to start server: tls: failed to parse private key
```

**Comment by Fastidious** [comment]
@bmerlet90 try it without the key/cert (comment those lines out), does it starts fine, and it becomes accessible through the web browser?

**Comment by Fastidious** [comment]
See this[0] as relevant, perhaps?

[0] https://github.com/gogits/gogs/issues/487

**Comment by bmerlet90** [comment]
@Fastidious gogs and Apache are running at the same time, as I have other applications running on the same server
I already saw the self signed certificate command in the FAQ but i really wanted to use the certificate I have for gogs

**Comment by bmerlet90** [comment]
I commented the cert/key in the app.ini file, the server didn't start.
This is what appears in the logs:
```
2017/03/22 13:21:51 [TRACE] Log Mode: File (Trace)
2017/03/22 13:21:51 [ INFO] Gogs: Go Git Service 0.10.18.0313
2017/03/22 13:21:51 [ INFO] Cache Service Enabled
2017/03/22 13:21:51 [ INFO] Session Service Enabled
2017/03/22 13:21:51 [ INFO] Mail Service Enabled
2017/03/22 13:21:51 [ INFO] Register Mail Service Enabled
2017/03/22 13:21:51 [ INFO] Notify Mail Service Enabled
2017/03/22 13:21:51 [ INFO] Git Version: 1.9.1
2017/03/22 13:21:51 [ INFO] SQLite3 Supported
2017/03/22 13:21:51 [ INFO] Run Mode: Production
2017/03/22 13:21:51 [TRACE] Doing: CheckRepoStats
2017/03/22 13:21:51 [ INFO] Listen: https://0.0.0.0:3000/gogs
2017/03/22 13:21:51 [FATAL] [...rfave/cli/command.go:193 Run()] Fail to start server: open custom/https/cert.pem: no such file or directory
```

**Comment by Fastidious** [comment]
I don’t understand. If key/cert are commented, where is that coming from?

**Comment by Unknwon** [comment]
Hi, maybe helpful: https://unknwon.io/setup-gogs-with-https/.

**Comment by bmerlet90** [comment]
@Unknwon what I do't understand is how to generate the `key.pem` and `cert.pem` files 
The https certificate I have were generated by my research institute, and I am not allowed to use self-signed certificate (this is a institute wide rule). 
But they only gave me `my-domain.key` and `my-domain.crt` files...

Does the `$ ./gogs cert -ca=true -duration=8760h0m0s -host=myhost.example.com` command generate the `.pem` from the `.crt` and `.key` files?

**Comment by bmerlet90** [comment]
@Unknwon I found out how to get my pem files here http://stackoverflow.com/questions/991758/how-to-get-pem-file-from-key-and-crt-files

Gogs worked fine after changing the cert/key in the `app.ini`  to point to them.

Wouldn't be good though that gogs accepts `.crt `and` .key` files ?

**Comment by Unknwon** [comment]
I don't think you've really read the link I commented above, if you're using reverse proxy, there is no need to change Gogs listen for HTTPS at all.

**Comment by Unknwon** [comment]
@xingxing9688 https I think.
