### ISSUE TITLE
External links broken in HTML repo description

### ISSUE THREAD

**Issue by zefie** [gogits/gogs#4329]
- Gogs version (or commit ref): dev: f54bcba3394bf856b77b674203ea0c80b926cd61
- Git version: 2.1.4
- Operating system: Debian 8.7 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zefie_Test)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
(nothing relevant, such as render or parse error, just Session ID and tokens)
## Description

Links to external sites are broken in HTML repo descriptions.
Internal links such as "/user/otherrepo" work fine.

Check the try.gogs.io url I provided, you will see it right away.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by zefie** [comment]
Confirmed working on try.gogs.io as well as locally when updated to commit c238647 .. Thanks!
