### ISSUE TITLE
Webhook is not work on organizations

### ISSUE THREAD

**Issue by pgaborwolters** [gogits/gogs#4331]
- Gogs version (or commit ref): 0.10.18.0313
- Git version:  2.1.4
- Operating system: debian
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
No errors.

Webhook is only work on repositories in real time, but dont work on organizations. If we restart the gogs daemon, then the organization webhook is work at start procedure. So we need always restart the gogs daemon for organization webhook is fired.

**Comment by Unknwon** [comment]
Hi,

Define "collaboration webhook"?

**Comment by pgaborwolters** [comment]
Sorry! Collaboration mean organization.

**Comment by Unknwon** [comment]
Ah.. thanks for clarifying. But why can't you reproduce on demo site?

**Comment by pgaborwolters** [comment]
I cant reproduce on demo site.
