### ISSUE TITLE
404 error when edit my draft release in Google Chrome

### ISSUE THREAD

**Issue by dengni8023** [gogits/gogs#4334]
- Gogs version (or commit ref): 0.9.97.0901
- Git version: 2.10.1 (Apple Git-78)
- Operating system: macOS Sierra
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

**Comment by Unknwon** [comment]
Hi, version too old.
