### ISSUE TITLE
Ability to edit SSH address in "Clone this repository"

### ISSUE THREAD

**Issue by jackjack-jj** [gogits/gogs#4335]
It's already possible to change the URL of the website, but it would be nice to be able to change the SSH address too
For example I access my server through a VPN so my repo is not reachable with ssh://git@localhost:22/admin/repo1.git

**Comment by xmik** [comment]
Doesn't this work for you?
```
[server]
DOMAIN       = example.com
HTTP_PORT    = 3000
ROOT_URL     = http://example.com
```
in `app.ini` file

**Comment by Unknwon** [comment]
Hi, maybe helpful: https://discuss.gogs.io/t/how-to-config-ssh-settings/34
