### ISSUE TITLE
Repo size doesn't work from repo migration

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#4336]
- Gogs version (or commit ref): 0.10.18.0313
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Repository size doesn't work if repository was created from migration, as image below:

dev as created repository, laravel was migration from https://github.com/laravel/laravel and openstack-swift from https://github.com/openstack/swift

![screenshot-0 0 0 0 3000-2017-03-24-11-48-56](https://cloud.githubusercontent.com/assets/1520407/24299414/e74eef90-1087-11e7-8a4c-a07fcd13ab8e.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

Existing repos will be updated once push via Git client or mirror sync.
