### ISSUE TITLE
Cannot restore inside Docker container

### ISSUE THREAD

**Issue by mattddowney** [gogits/gogs#4339]
- Gogs version (or commit ref): 0.10.18
- Git version: 
- Operating system: alpine
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Running `/app/gogs/gogs backup` inside a container fails with the following message:
```
2017/03/25 02:10:27 [ INFO] Backup root directory: /tmp/gogs-backup-766413534
2017/03/25 02:10:27 [ INFO] Packing backup files to: gogs-backup-1490407827.zip
2017/03/25 02:10:27 [FATAL] Fail to dump database: fail to dump table 'User': no such table: user
```

Steps to reproduce:

1. Create a gogs docker container with default config, selecting sqlite as the DB
2. Running backup inside the container fails `docker exec gogs-backup-bug /bin/bash -c "export USER=git && /app/gogs/gogs backup"`

Code to reproduce:

```
#!/bin/bash

# create a docker compose file
cat > ./docker-compose.yml <<-END
version: '3'

services:
  gogs:
    image: gogs/gogs:0.10.18
    container_name: gogs-backup-bug
    ports:
      - "10022:22"    # ssh for git
      - "10080:3000"  # http port
    volumes:
      - ./volumes/gogs:/data
    networks:
      default:
        aliases:
          - gogs
    restart: always
END

# run container described in docker-compose.yml
docker-compose up -d

# get container ip address
container_ip=$(docker inspect --format "{{.NetworkSettings.Networks.docker_default.IPAddress}}" gogs-backup-bug)
echo $container_ip

# wait for container to startup
sleep 5

# save cookies to gogs-cookies file
curl "http://${container_ip}:3000/install" \
    --cookie-jar gogs-cookies

# install selecting "sqlite3", using the container IP above for the domain and app_url
# admin user: gogs_admin, pass: test, email: test@nowhere.com
# everything else default
curl "http://${container_ip}:3000/install" \
    --cookie gogs-cookies \
    -H 'Origin: null' \
    -H 'Accept-Encoding: gzip, deflate' \
    -H 'Accept-Language: en-US,en;q=0.8' \
    -H 'Upgrade-Insecure-Requests: 1' \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/56.0.2924.76 Chrome/56.0.2924.76 Safari/537.36' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
    -H 'Cache-Control: max-age=0' \
    -H 'Connection: keep-alive' \
    -H 'DNT: 1' \
    --data "db_type=SQLite3&db_host=127.0.0.1%3A3306&db_user=root&db_passwd=&db_name=gogs&ssl_mode=disable&db_path=data%2Fgogs.db&app_name=Gogs&repo_root_path=%2Fdata%2Fgit%2Fgogs-repositories&run_user=git&domain=${container_ip}&ssh_port=22&http_port=3000&app_url=http%3A%2F%2F${container_ip}%3A3000%2F&log_root_path=%2Fapp%2Fgogs%2Flog&smtp_host=&smtp_from=&smtp_user=&smtp_passwd=&enable_federated_avatar=on&enable_captcha=on&admin_name=gogs_admin&admin_passwd=test&admin_confirm_passwd=test&admin_email=test%40nowhere.com" \
    --compressed

# backup fails
docker exec gogs-backup-bug /bin/bash -c "export USER=git && /app/gogs/gogs backup"
```

**Comment by mattddowney** [comment]
So after playing with this more, the issue is the default path for sqlite3 database:

![gogs screenshot](http://i.imgur.com/Cx2hJv5.png)

Changing the default path to an absolute `/data/gogs.db` during docker installation seems to make everything work.

Perhaps the docker install instructions need to be updated to reflect this, or maybe a clarifying message under the box?

**Comment by Unknwon** [comment]
Hi,

1. on the [documentation](https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991), it says on the first line:

![image](https://cloud.githubusercontent.com/assets/2946214/24320303/08d0cf22-1109-11e7-963c-686035b2aa21.png)

2. Restore is not specifically designed for Docker container, `invalid cross-device link` is not something I understand, needs more investigation.

**Comment by mattddowney** [comment]
I can change to the directory first instead of running `/app/gogs/gogs` directly and the backup still succeeds:

```
$ sudo docker exec gogs-backup-bug /bin/bash -c "export USER=git && cd /app/gogs && ./gogs backup"
2017/03/25 17:24:36 [ INFO] Backup root directory: /tmp/gogs-backup-537097014
2017/03/25 17:24:36 [ INFO] Packing backup files to: gogs-backup-1490462676.zip
2017/03/25 17:24:36 [ INFO] Dumping repositories in '/data/git/gogs-repositories'
2017/03/25 17:24:36 [ INFO] Repositories dumped to: /tmp/gogs-backup-537097014/repositories.zip
2017/03/25 17:24:36 [ INFO] Backup succeed! Archive is located at: gogs-backup-1490462676.zip
```

Restore fails with the same reason:

```
$ sudo docker exec gogs-backup-bug /bin/bash -c "export USER=git && cd /app/gogs && ./gogs restore --from gogs-backup-1490462676.zip"
2017/03/25 17:25:24 [ INFO] Restore backup from: gogs-backup-1490462676.zip
2017/03/25 17:25:32 [FATAL] Fail to import 'custom': rename /tmp/gogs-backup/custom /data/gogs: invalid cross-device link
```

At this point I am going to chalk this up to running inside docker. I fiddled with different docker configurations for an entire day.

I have an existing process where I just backup the mounted volume on the host, which works, but if there is an official method available, I thought I would try it.

**Comment by Unknwon** [comment]
I don't think you read me comment:

>Restore is not specifically designed for Docker container, invalid cross-device link is not something I understand, needs more investigation.

**Comment by xmik** [comment]
> Changing the default path to an absolute /data/gogs.db during docker installation depicted above will make the backup process work, however the restore process will fail

I confirm that changing to absolute path makes the command
```
USER=git /app/gogs/gogs backup
```
exit with status 0, but the output file (e.g. `gogs-backup-1493407935.zip`) contains many files of size 0. Even the `User.json` is of size 0 and empty, while I have created 1 gogs user.

So it is `gogs backup` command that fails, even though it exits with status 0.

**Comment by Unknwon** [comment]
Possible solution is posted here: https://github.com/gogits/gogs/issues/4641#issuecomment-318011581

**Comment by rmxhaha** [comment]
I just want to make this clear in case I need to migrate gogs inside docker once again as the solution is not explicitly mentioned. 

Backup:
```
docker exec -it <container_id> bash
cd ..
USER=git ./gogs backup
exit
docker cp <container_id>:/app/gogs/<backup_name> .
```

Restore:
Note: cross-device-link is caused by move between 2 mount so the solution is to use tmp folder in the same mount as data where gogs reside which is /data by default for docker gogs.

```
docker cp <backup_name> <container_id>:/data/
docker exec -it <container_id> bash
mkdir /data/tmp
cd /data
USER=git /app/gogs/gogs restore --from="<backup_name>" -t /data/tmp
```

**Comment by kdeenkhoorn** [comment]
I have the same issue restoring a backup with gogs version 0.11.79 running in docker. Problem is the usage of the os.Rename function for moving directories in the restore function. This os.Rename function is not capable of handling directory moves over different devices, which are heavily used in docker, namely docker volumes.

I have no golang knowledge but probably someone else does. Search google for 'os.rename invalid cross-device link' and you will find info about this.

Thanks for fixing in advance!

Kl@@s

**Comment by xingxing9688** [comment]
How does this refer to docker's backup to the host directory instead of the /tmp directory?

**Comment by kdeenkhoorn** [comment]
@xingxing9688; As long as during the restore you're not hitting a file or directory offered by docker volume and stay within the same filesystem, renaming a file works. In my opinion avoiding this problem by using the move command instead of rename would be a better solution.

So if you have this construction for example:
docker run .... -v /data/gogs:/data/gogs -v /myconfig/app.ini:/data/gogs/app.ini .....
Renaming app.ini during restore will likely fail, moving will succeed.
