### ISSUE TITLE
Fail to update ldap authenticated user's profile

### ISSUE THREAD

**Issue by schenkerx** [gogits/gogs#4340]
- Gogs version (or commit ref): 0.10.8.0307
- Git version: 2.11.0
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): No relevant entries found in log

## Description

We are using LDAP to authenticate our users. However, when a user trying to update its website or location field in their profile, **the system refuse to update the profile and say "Name cannot be empty".**
However, LDAP authenticated users are not allowed to update their username in Gogs. Please help fixing this bug, thanks!

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/4313.
