### ISSUE TITLE
Mirror: if no content is fetched, updated should not be changed

### ISSUE THREAD

**Issue by hochhaus** [gogits/gogs#4341]
- Gogs version (or commit ref): 0.10.18
- Git version: git version 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When setting up mirrors, the explore page displays the "Updated" field as the last time the repo was polled for an update. It would be better if it showed the last time it was polled when at least one new change was pulled in from the upstream git repo. Otherwise, all of the projects show as updated every X hours.

Alternatively, as I am now using the [mirror sync API](https://github.com/gogits/go-gogs-client/wiki/Repositories#mirror-sync), having the ability to disable polling all together would also meet my needs.

**Comment by Unknwon** [comment]
How do you determine which branch has the latest commit?

**Comment by hochhaus** [comment]
I would iterate over all of the branches looking for new changes. Does this answer your question?

**Comment by Unknwon** [comment]
Found answer: http://stackoverflow.com/questions/5188320/how-can-i-get-a-list-of-git-branches-ordered-by-most-recent-commit :smile:

```
git for-each-ref --sort=-committerdate refs/heads/
```

**Comment by hochhaus** [comment]
Good find.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by hochhaus** [comment]
Build from source on `develop` branch and tested. This functionality works great. Thanks!
