### ISSUE TITLE
Anyone tried to store Repositories to remote storage

### ISSUE THREAD

**Issue by abhilash07** [gogits/gogs#4347]
Hi is anyone tried to store go-gits repositories, attachments, avatars, sessions data files in remote storage like NFS or s3. If any tried please help me. Thanks in Advance

Regards

Abhilash S

**Comment by cirocosta** [comment]
I was reading http://blog.deveo.com/your-git-repository-in-a-database-pluggable-backends-in-libgit2/ , but couldn't find much about something like that implemented in gogs. 

How are people managing remote storage today?

Thx!

**Comment by Unknwon** [comment]
Hi,

Please read issue post template.
