### ISSUE TITLE
can't use ssh or scp from other server to connet git server

### ISSUE THREAD

**Issue by agamem** [gogits/gogs#4349]
Gogs version (or commit ref): 0.9.113.1223
Git version: 2.11.0
Operating system: Ubuntu 14.04
Database (use [x]):
 PostgreSQL
 MySQL
 SQLite
Can you reproduce the bug at https://try.gogs.io:
 Yes (provide example URL)
 No
[x ] Not relevant

## Description
ubuntu01 is our git-server with a user named git.
when i use scp from another server to copy a file from git-server, get blow info：
>scp git@ubuntu01:/home/git/http.cap .
Gogs: Repository owner does not exist

when use ssh command, get blow：
>ssh git@ubuntu01
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gogs does not provide shell access.
If this is unexpected, please log in with password and setup Gogs under another user.
Connection to ubuntu01 closed.

why?

...

**Comment by Unknwon** [comment]
Maybe helpful: https://discuss.gogs.io/t/how-to-config-ssh-settings/34
