### ISSUE TITLE
PostgreSQL: unique constraint violation after backup restored

### ISSUE THREAD

**Issue by luckcolors** [gogits/gogs#4357]
- Gogs version: 0.9.170.0226 / 0.10 RC 
- Git version: latest
- Operating system: docker on ubuntu (using the provided image.rpi armhf host)
- Database (use `[x]`):
  - [X ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [X] Not relevant

## Description
Hi,
So i've been using gogs for a while. Some months ago i had to use the gogs feature to dump everything because i had to move to another gogs instance (complete server reinstall).
So this time i'm suign docker. Built the docker image myself with docker build command and i've reimported the database and files.

Since i did that everything seemed to be working, but now i notice that everytime i try to create a new repo or user the server returns 500 and the following errors(organizations seems to be fine):
For a repo: '''pq: duplicate key value violates unique constraint "repository_pkey"'''
For a user: '''pq: duplicate key value violates unique constraint "user_pkey"'''
For a migration: '''pq: duplicate key value violates unique constraint "repository_pkey"'''

Log:

'''
2017/03/28 16:23:01 [TRACE] CSRF Token: TOKEN
2017/03/28 16:23:01 [ERROR] [...s/context/context.go:97 Handle()] CreatePost: pq: duplicate key value violates unique constraint "repository_pkey"
2017/03/28 16:23:01 [TRACE] Template: status/500
2017/03/28 16:50:40 [TRACE] CSRF Token: TOKEN
2017/03/28 16:50:41 [ERROR] [...s/context/context.go:97 Handle()] CreateUser: pq: duplicate key value violates unique constraint "user_pkey"
2017/03/28 16:50:41 [TRACE] Template: status/500
2017/03/28 16:52:21 [TRACE] CSRF Token: TOKEN
2017/03/28 16:52:21 [ERROR] [...s/context/context.go:97 Handle()] MigratePost: pq: duplicate key value violates unique constraint "repository_pkey"
2017/03/28 16:52:21 [TRACE] Template: status/500
"""

**Comment by Unknwon** [comment]
Hi, what is "after dump reimport"?

**Comment by luckcolors** [comment]
Oh sorry. I meant that on the first gogs instance i did "gogs dump". And then on the new one i mnaually imported the postgres dump into the database.

**Comment by Unknwon** [comment]
`dump` command is no longer supported, you should try `backup` and `restore`(https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991), but `restore` doesn't work inside Docker container currently (https://github.com/gogits/gogs/issues/4339).

**Comment by luckcolors** [comment]
So what should i do? I don't have the old instance available anymore.

**Comment by Unknwon** [comment]
>Since i did that everything seemed to be working, but now i notice that everytime i try to create a new repo or user the server returns 500 and the following errors(organizations seems to be fine):

So you have new instance running but just can't create new repo?

**Comment by luckcolors** [comment]
Yeah i can't create any kind of repo OR user.
I'm still able to create organizations.

**Comment by Unknwon** [comment]
Are you using latest Gogs? If not upgrade.

**Comment by luckcolors** [comment]
Ok i've upgraded gogs. New version is: 0.10.34.0401. And yeah same problems as before.

**Comment by Unknwon** [comment]
OK, my guess of your issue is the `auto_increment` value is not set correctly because the output from old `dump` command could be buggy.

With latest version you could try new commands `backup` and `restore` which should set database table to a correct state.

Basically what you need to do is `./gogs backup --database-only xxx` and right after that run `./gogs restore`, see more details:  https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991

**Comment by luckcolors** [comment]
Ok i tired that it successfully creates the archive but restore returns the error: 
2017/04/04 20:20:57 [ INFO] Restore backup from:
2017/04/04 20:20:57 [FATAL] Fail to extract backup archive: open : no such file or directory
Already treid to pass the zip file as an argument.
It seems that you mentioned this in thethread too: https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991/3

**Comment by Unknwon** [comment]
Show your commands.

**Comment by luckcolors** [comment]
./gogs backup --database-only
./gogs restore --database-only

Backup succeeds. Restore does not and returns the error i mentioned before.

**Comment by Unknwon** [comment]
Ah, you should use:

```
./gogs restore --database-only --from="gogs-backup-xxx.zip"
```

I've updated the discuss as well.

**Comment by luckcolors** [comment]
Ok so i've successfully reimported the database.
Now all timestamps in gogs are from the current time.

I tried creating an repo and i got the same error.

```
An error has occurred : pq: duplicate key value violates unique constraint "repository_pkey"
```

**Comment by luckcolors** [comment]
Soo any other idea? Should i just make a new database?

**Comment by FSMaxB** [comment]
I have the same issue with 0.11.6.0407 and PostgreSQL 9.6.2. I backed up my database via `gogs backup` (I think it was gogs 10 back then with SQLite and updated gogs several times since then) and now finally realised that creating repositories doesn't work anymore. Same problem with `"repository_pkey"`.

I even tried deleting all tables manually (`with drop table ...;`) before restoring, but no success.

If there's more I can do for debugging, please tell me.

**Comment by xmik** [comment]
@FSMaxB , is the `gogs backup` (when using SQLite backend) result file not full of 0 sized json files? See this comment please: https://github.com/gogits/gogs/issues/4339#issuecomment-298088612

**Comment by FSMaxB** [comment]
@xmik no!

**Comment by Unknwon** [comment]
@FSMaxB Are you backup from one database engine (SQLite3) and restore to another database engine (PostgreSQL)?

I think I know the problem now... the auto increment of PostgreSQL is not update automatically as MySQL does.

**Comment by FSMaxB** [comment]
Yes I did a backup from SQLite3 and restored to PostgreSQL.

**Comment by Unknwon** [comment]
Note: http://stackoverflow.com/questions/10114779/postgressql-how-to-set-up-manually-the-next-value-of-auto-increment

**Comment by FSMaxB** [comment]
I already deleted everything and started a fresh install. If you still need me to confirm a fix or something I can set up a gogs instance on my other server and try it there.

**Comment by Unknwon** [comment]
@FSMaxB thanks, I think I should be able to reproduce this issue easily, but will let you know.

**Comment by luckcolors** [comment]
@Unknwon i still have the broken instance setup. Again if you need anything let me know. :)

**Comment by Unknwon** [comment]
Hi anyone encountered this issue,

update to `develop` branch, rebuild Gogs binary as usual.

1. If you still have old backup archive, do restore again, the sequence should be fixed automatically.
2. If you hast lost previous backup archive, do a backup then restore.

Hope helps!

**Comment by luckcolors** [comment]
Hi, thanks for the help!
Unfortunately for some reason the dockerfile for building the develop branch fails, so i haven't yet been able to test it.
So here's the issue if you want to take a look. :) #4529

**Comment by luckcolors** [comment]
I confirm that this has been fixed! The patch works. :)
So to fix it you have to export and reimport the database from a backup as explained before. Here's a recap of the commands.

For backupping the database:
```
./gogs backup --database-only
```
For restoring the database:
```
./gogs restore --database-only --from="gogs-backup-TIMESTAMP.zip" --config=/data/gogs/conf/app.ini
```
