### ISSUE TITLE
Private repository with public issues/wiki didn't handle anonymous visit properly

### ISSUE THREAD

**Issue by ModdyLP** [gogits/gogs#4359]
- Gogs version (or commit ref): Pre Release 1.11
- Git version: Newest
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)https://try.gogs.io/ModdyLP/Test/
  - [ ] No
  - [ ] Not relevant

## Description
Issues cannot be created by Anonymous. If you click on the create button, then my browser shows me an download or on try.gogs.io the browser says "The Site not working correctly". I dont think that this is the goal.

**Comment by Unknwon** [comment]
Hi,

>Issues cannot be created by Anonymous

Of course can't, the problem is UI didn't prevent anonymous from creating issues.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by ModdyLP** [comment]
Yep now it is Wirkung, you geht redirected to the login Form.
