### ISSUE TITLE
Gogs don't show code structure 

### ISSUE THREAD

**Issue by nguyenphuongthanhf** [gogits/gogs#4364]
- Gogs version (or commit ref): 
- Git version: 0.10.1.0228
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I can't view code when access to repository, but i can access with link /src/master. Please view detail on link below

[http://thanhnp.tumblr.com/post/158990712776/bug](url)
...

**Comment by Unknwon** [comment]
Hi, define "code structure"?

**Comment by Fastidious** [comment]
@Unknwon, based on the post he linked — which got wrongly linked — he is saying he can’t see the repositories list when going to the user’s profile page:

![tumblr_onm2i84usf1qb8caeo1_1280](https://cloud.githubusercontent.com/assets/8352292/24561102/8fd243a2-1613-11e7-8103-5b4629b265ff.png)

But can see it when going straight to the  repository itself:

![tumblr_onm2i84usf1qb8caeo2_1280](https://cloud.githubusercontent.com/assets/8352292/24561108/9760ddae-1613-11e7-8dcc-94b707825fde.png)

**Comment by Unknwon** [comment]
@Fastidious thanks, but I don't know what is the relation between these two "following"s?

**Comment by Fastidious** [comment]
Yeah, he wasn’t too clear (not with language, nor the example provided). Oh well 🤷🏻‍♂️...
