### ISSUE TITLE
ipynb Markdown images with relative path are not displayed

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#4366]
If you have a Jupyter Notebook (`.ipynb`) that contains some Markdown which references an image by relative path, eg.

    ![](img/capture_crop.png)

the image is NOT displayed when viewing the notebook in Gogs. Of course, this makes sense because the raw image does not exist under such a URL. Would it be possible to post-process such relative URLs and point them to the right URL, i.e. `/user/repo/raw/master/img/capture_crop.png`?

Example here: https://try.gogs.io/niklas/ipynb-test

**Comment by Fastidious** [comment]
Try:

`![](/img/capture_crop.png)`

**Comment by Unknwon** [comment]
AFAIK ipynb is not processed by Gogs markdown processor at all, everything is done on the frontend via notebook.js and marked.js.

**Comment by Unknwon** [comment]
So I think it is not possible currently.

**Comment by Unknwon** [comment]
Not sure if marked.js can config something as root URL for relative path images.

**Comment by NiklasRosenstein** [comment]
I think you can override the `renderer.link` function. See the marked.js README

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/niklas/ipynb-test.

**Comment by NiklasRosenstein** [comment]
Thanks. It works in the repository main page, but not when viewing README.ipynb directly.

https://try.gogs.io/niklas/ipynb-test/src/master/README.ipynb

**Comment by Unknwon** [comment]
@NiklasRosenstein good catch!

Should be good now, also tested for ipynb in subdirectories.

**Comment by NiklasRosenstein** [comment]
Works here as well. Thanks! :)
