### ISSUE TITLE
README.ipynb not supported

### ISSUE THREAD

**Issue by NiklasRosenstein** [gogits/gogs#4367]
I like that Gogs has support for `.ipynb` files! What I find unfortunate is that `README.ipynb` is not rendered as a notebook, but as plain text, when viewed from its parent directory.

Example here: https://try.gogs.io/niklas/ipynb-test

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by NiklasRosenstein** [comment]
LGTM, thanks!
