### ISSUE TITLE
Cannot use absolute path for image link

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4368]
- Gogs version (or commit ref): `0.10.34.0330 / 0.11 RC`
- Git version:  `N/A`
- Operating system: `N/A` 
- Database (use `[x]`): `N/A`
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/Fastidious/Ideas
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Image on first README (https://try.gogs.io/Fastidious/Ideas/src/master/README.md), image shows fine. Click "Documentation" (https://try.gogs.io/Fastidious/Ideas/src/master/documentation). Image is broken. Edit document with broken image, preview it, image shows fine. On preview, image path is absolute (as it should be, I think):

`/Fastidious/Ideas/raw/master/images/img-02.png`

Upon saving, image path changes to relative where document is (not desirable):

`/Fastidious/Ideas/raw/master/documentation/images/img-02.png`

**Comment by Unknwon** [comment]
I think it's your syntax problem, I've fixed for you.

**Comment by Fastidious** [comment]
That fixed it, but as it was before it would look fine on preview, but not on regular view. It seems there is an inconsistency between editing preview and saved document.

**Comment by Unknwon** [comment]
>but as it was before it would look fine on preview, but not on regular view.

Define "preview" and "regular view".

**Comment by Fastidious** [comment]
When exiting a document, there is a "preview" tab. That is preview. Regular view is what you see after saving.

**Comment by Unknwon** [comment]
This is not regular view?

![image](https://cloud.githubusercontent.com/assets/2946214/24532432/708fcbb6-158e-11e7-9db3-8c875886e145.png)

**Comment by Fastidious** [comment]
Yes. But change it to how I had it, and see preview. It will work fine. Save it, and the image will show broken.

**Comment by Unknwon** [comment]
I think it's preview's side problem.

**Comment by Fastidious** [comment]
@Unknwon could it be made, so absolute paths were used (or make it a setting, if you want)? That way a user wouldn’t need to worry on how many dots and slashes are needed (`../../../`), it would simply use the absolute path, from repository root (`/images/`, `/documents/images/`, etc.).

**Comment by Unknwon** [comment]
OK, sounds good to me.

**Comment by Unknwon** [comment]
Finally I realize it is impossible to use absolute path because it is no way (too expansive) to determine what branch it is in because branch can have slashes `feature/2fa/a/b/c` etc. So I fixed relative path for preview:

```
![](../images/xxx)
```

You can test on https://try.gogs.io.

**Comment by Fastidious** [comment]
@Unknwon I can settle with that, and it works as advertised. 😄 Thanks!
