### ISSUE TITLE
Run with docker but: Fail to start server: listen tcp 0.0.0.0:80: bind: permission denied

### ISSUE THREAD

**Issue by BigKunLun** [gogits/gogs#4369]
Hi gus, last night I installed gogs and run it good with centos7&docker.But when morning I walk up,find gogs don't work,I see the logs:

        2017/03/31 02:09:10 [TRACE] Log Mode: File (Trace)
        2017/03/31 02:09:10 [ INFO] trygogs 0.10.32.0328 / 0.11 RC
        2017/03/31 02:09:10 [ INFO] Cache Service Enabled
        2017/03/31 02:09:10 [ INFO] Session Service Enabled
        2017/03/31 02:09:10 [ INFO] Git Version: 2.11.1
        2017/03/31 02:09:10 [ INFO] SQLite3 Supported
        2017/03/31 02:09:10 [ INFO] Run Mode: Production
        2017/03/31 02:09:10 [TRACE] Doing: CheckRepoStats
        2017/03/31 02:09:10 [ INFO] Listen: http://0.0.0.0:80
        2017/03/31 02:09:10 [FATAL] [...rfave/cli/command.go:193 Run()] Fail to start server: listen tcp 0.0.0.0:80: bind: permission denied

I run docker with root like this: `docker run --name=gogs -d -p 10022:22 -p 80:3000 -v /root/gogs:/data gogs/gogs`

I search google and gogs-issues,find [http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux](http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux) and [https://github.com/gogits/gogs/issues/4022](https://github.com/gogits/gogs/issues/4022).But don't solve my problem.

Looking forward to your reply.

**Comment by Unknwon** [comment]
Hi, please read https://github.com/gogits/gogs/blob/master/docker/README.md.

**Comment by BigKunLun** [comment]
I read the doc when I want install gogs with docker, you mean port 80 have already used in docker?

**Comment by Unknwon** [comment]
I mean don't use port 80 unless you have a very good reason.

**Comment by BigKunLun** [comment]
I think I find the answer, docker port is no problem.Gogs setting would not set HTTP Port with 80.Thanks.

**Comment by apassi** [comment]
My gogs instance is accessed thru openvpn, and the network is shared with brige. I am not able to publish port to 80, i think it is not possible because the bridge.
So is it possible to run gogs in 80 port?
