### ISSUE TITLE
Slack notifications for issues/replies/status changes

### ISSUE THREAD

**Issue by danherd** [gogits/gogs#4371]
- Gogs version (or commit ref): 0.10.31.0327 / 0.11 RC
- Git version: 1.8
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

It would be great if any issues posted (and updates to issues) could trigger a Slack channel notification (like with webhooks).

Thanks for this software - it is fabulous and I'm plugging it as much as I can on Twitter!

Cheers,

Dan

...

**Comment by Unknwon** [comment]
Hi, I don't understand your request, isn't this already possible?
