### ISSUE TITLE
LDAP authentication fails if User Filter doesn't contain %s

### ISSUE THREAD

**Issue by a-zen** [gogits/gogs#4375]
- Gogs version (or commit ref): 0.9.141
- Git version: 2.10.2
- Operating system: Gentoo
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/04/02 01:15:51 [TRACE] LDAP will bind directly via UserDN template: ou=users,dc=test,dc=com
2017/04/02 01:15:51 [TRACE] Binding with userDN: ou=users,dc=test,dc=com%!(EXTRA string=tester)
2017/04/02 01:15:51 [TRACE] LDAP authentication failed for 'ou=users,dc=test,dc=com%!(EXTRA string=tester)': LDAP Result Code 49 "Invalid Credentials": 

### Problem
When using LDAP the authentication fails if the User Filter doesn't contain a filter with the "%s" string. For example (objectClass=*) will because gogs always adds the value for "%s" (%!(EXTRA string=tester). When setting the User Filter value to a filter with "%s" the authentication works, for example (&(objectClass=*)(cn=%s)) .

### Expected Behaivour
When providing a User Filter without a "%s" string, gogs shouldn't append the variable data.

**Comment by Unknwon** [comment]
Hi, what is the real use case that doesn't need user name for LDAP search?

**Comment by jakape** [comment]
Hi there,

The use case could be to use general User/Group queries, like ```
(&(objectClass=user)
(memberOf=CN=myFancyGogsAdminGroup,DC=company,DC=local))
```
I was surprised to learn that the query is not happening within user context by default.

Do I understandthat correctly, that any given user/group filter does have to include user-context or will be otherwise filled by a query-breaking addendum?

**Comment by knedlsepp** [comment]
This is interesting for setups where we userDN look like this:
```
CN=Surname Lastname,OU=Users,DC=EXAMPLE,DC=local
```
I don't want to use "Surname Lastname" as a gogs user account. In my case the `sAMAccountName` attribute contains a proper username. So the only choice would be to search for a more general DN (which means ls.UserDN does NOT include "%s") and filter out the entry via something like: ` (&(objectClass=user)(objectcategory=person)(sAMAccountName=%s))`

**Comment by knedlsepp** [comment]
Would it be reasonable to exchange:
```go
return fmt.Sprintf(ls.BindDN, username), true
...
return fmt.Sprintf(ls.Filter, username), true
```
with
```go
return strings.Replace(ls.BindDN, "%s", username, -1), true
...
return strings.Replace(ls.Filter, "%s", username, -1), true
```
In the same manner it is handled in: https://github.com/gogits/gogs/blob/6cbaa4787b444babda0ca6b6dd5d2d43d3a2cf99/pkg/auth/ldap/ldap.go#L101

**Comment by knedlsepp** [comment]
@Unknwon: While the PR addresses this issue. Do you have any suggestions on how to handle the related problem of the userDN looking something like `CN=FirstName LastName,OU=Users,DC=EXAMPLE,DC=local` and thus not containing a proper username? I don't know how to set up LDAP using basic authentication when the username is not contained in the distinguished name, but inside the `sAMAccountName` attribute of this object. I have managed to set up BindDN authentication, but this requires saving the password for the username used to bind to the AD.

**Comment by Unknwon** [comment]
@knedlsepp I hope I could help but myself is an entry-level LDAP user so I really don't have such ability to debug config problems :pensive:
