### ISSUE TITLE
Redirect to original page after sign in

### ISSUE THREAD

**Issue by nome** [gogits/gogs#4379]
- Gogs version (or commit ref): 0.10.18.0313
- Git version: 2.1.4
- Operating system: Debian/Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (example: <https://try.gogs.io/nome/hello/_edit/master/README.md>)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description
When following a [direct blob edit link on GitHub](https://github.com/gogits/gogs/edit/master/README.md) while not logged in, one gets a log in prompt, and is afterwards redirected to the file editor. This behaviour is particularly useful in conjunction with "Edit on GitHub" links in documentation generated from a repository.

Gogs also allows one to log in in this case, but redirects to the landing page afterwards instead of the original URL, forcing the user to navigate manually to the correct repository and file. This is certainly not a big issue, but a small feature that would be nice to have.

**Comment by Fastidious** [comment]
Same as #4374?

**Comment by nome** [comment]
@Fastidious Yes, thanks. I missed that one while searching for existing issues. Closing this one as duplicate.
