### ISSUE TITLE
Import/Export user data

### ISSUE THREAD

**Issue by ewr4ter** [gogits/gogs#4381]
Could you please add a feature to export/import repo data (comments etc.). There is probably an API call for this, but I what I mean is a button "Export data" such that I can export everything and re-import into another Gogs instance.

Thanks.

**Comment by Unknwon** [comment]
https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991

**Comment by ewr4ter** [comment]
The link you provide describes how to backup data **for admins**, not **for users**!

**Comment by Unknwon** [comment]
OK... then what is the point "for users"? I don't think it's going to be implemented.
