### ISSUE TITLE
Empty repo (zero commits) is missing buttons for "new file" and "upload file"

### ISSUE THREAD

**Issue by credomane** [gogits/gogs#4388]
1. Create a new Repo.
2. You are greeted with the expected empty repo with no commits.
3. Take note that the "New File" and "Upload File" buttons are no present.
4. Clone the repo as normal.
5. push a commit to the repo as normal.
6. The "New File" and "Upload File" buttons are now present.

I expected the "New File" and "Upload File" buttons to **always** be present and not require the repo to have at least one commit first. Small issue in html templates?

**Comment by Unknwon** [comment]
Hi, this is expected behavior. If you want first commit, just don't make empty repository at the beginning, e.g. choose a README file.
