### ISSUE TITLE
Offline access to issues

### ISSUE THREAD

**Issue by monnier** [gogits/gogs#4390]
I really like being able to consult and even update the wiki offline and without a browser.
I think the same should hold about issues.  IOW I wish they were stored in a Git repository as well.

- Gogs version (or commit ref): 0.10.18.0313 
- Git version: 2.11
- Operating system: GNU/Linux Debian stable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

**Comment by Unknwon** [comment]
Hi, thanks for the feedback, but no, this is not part of design of Gogs. you can always read source code of Gogs and hack database without a browser :D
