### ISSUE TITLE
Custom git hooks

### ISSUE THREAD

**Issue by monnier** [gogits/gogs#4391]
On a related note to #4227, it would be nice for Gogs to explicitly support custom Git hooks (and not just web-hooks), e.g. by documenting a way to manually change the .git/hooks files which will be preserved by Gogs when it regenerates all git hooks.

- Gogs version (or commit ref): 0.10.18.0313
- Git version: 2.11
- Operating system: GNU/Linux Debian stable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

**Comment by Unknwon** [comment]
It is already supported: https://discuss.gogs.io/t/how-to-use-custom-git-hooks/967

**Comment by monnier** [comment]
Great, thanks.  I couldn't find it in the documentation, tho.
