### ISSUE TITLE
Pull request broken if committed separately

### ISSUE THREAD

**Issue by monnier** [gogits/gogs#4393]
If the branch (or set of commits) of a pull-request gets merged outside of Gogs, the pull-request ends up in an incorrect state.  E.g. I just reproduced it as follows:

- create a pull request from a test-user for a trivial branch with just one more trivial commit.
- using Git from a shell, merge that same test-user branch into the main branch.
- git push the result to Gogs

then Gogs will show the pull request as

> This pull request can't be merged automatically because there are conflicts.
> Please merge manually in order to resolve the conflicts. 

and for the number of commits and files-changed in that pull-request, it says "N/A".
I think Gogs should handle this case better.  E.g. it should say `Commits 0  |  Files changed 0`, and it should also indicate that it is already merged.  I guess it could even automatically mark the pull request as closed.

- Gogs version (or commit ref): 0.10.18.0313
- Git version: 2.11
- Operating system: GNU/Linux Debian stable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

**Comment by Unknwon** [comment]
Hi, I think this is duplicated to https://github.com/gogits/gogs/issues/3388.

**Comment by monnier** [comment]
Oh, indeed, sorry
