### ISSUE TITLE
Installation with Mysql not possible

### ISSUE THREAD

**Issue by taut98** [gogits/gogs#4394]
Hey guys,

i just downloaded the Docker image of gogs.
Startet it and connected via localhost:10080 gogs.

I filled in all the required data and clicked Insatll but i am recieving this error:
127.0.0.1:3306: getsockopt: connection refused

Sounds very clear for me, normally means to me wrong user or password or port.

But the setting are correct. I can connect to my server from other devices.
Probably the solution is extremly easy but i just cant see it... 😄 

Thank you

**Comment by Unknwon** [comment]
Make sure you have correct start  order. MySQL should start  before  Gogs, and read issue post template.

**Comment by Andersbiha** [comment]
Looks to be like you're trying to connect to a MySQL instance inside your Gogs container.
If you're running MySQL in a separate container you need to change the host to match that containers IP.

If you're spinning up both MySQL and Gogs with docker-compose it can be as easy as defining a `depends_on: MYSQL_CONTAINER_NAME`  option on your Gogs container in your docker-compose.yml .

This will result in the MySQL container being started first, as well as appending a `MYSQL_CONTAINER_NAME` entry with the correct IP to the Gogs containers hosts file.

Afterwards you can connect to your MySQL container with `MYSQL_CONTAINER_NAME:3306`

**Comment by stargazers** [comment]
Thank you very much Andersbiha, your answer helped a lot. I had issue that I tried 127.0.0.1 on port 3306 even I should have been using "db:3306" because my Docker compose file had name "db" for my MariaDB.
