### ISSUE TITLE
Closing Issues with commits

### ISSUE THREAD

**Issue by Dutzen** [gogits/gogs#4395]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
 No relevant informations. No exceptions thrown
## Description
Since the update to 0.11.4.405 we can't close issues with commits anymore. 

Example commit message:
[fix] undefined articles, closes #32, [fix] changed HideOK method, closes #33

**Comment by Unknwon** [comment]
>Can you reproduce the bug at https://try.gogs.io:
 No

Why?

**Comment by Koogleschreiber** [comment]
maybe this will help to find our problem:
found this in the **post-receive.log** file
`2017/04/10 13:43:09 [ERROR] [...its/gogs/cmd/hook.go:215 runHookPostReceive()] PushUpdate: Fail to call 'git update-server-info': chdir /export/gogs/home/git/gogs/.git: no such file or directory`

seems like repoUserName and repoUser is missing in the path

This is the configuration for the repository location:
`[repository]
ROOT = /export/gogs/home/git/gogs
`

**Comment by Koogleschreiber** [comment]
The cause of this is that environment variables for the **post-receive** hook are not set. Not every repository has this problem. A hint where to continue our search would be helpful.

**Comment by kardianos** [comment]
@Koogleschreiber In the `/admin` panel, there is an option to `Resync pre-receive, update and post-receive hooks of all repositories`.  This may help resolve this issue. I had an issue where some repos had old hooks setup (from old versions of gogs?) that caused it to misbehave.  If this causes the problem, then probably close issue, or diagnose hooks migration code.
