### ISSUE TITLE
Permission denied to git user on the docker image.

### ISSUE THREAD

**Issue by gcavalcante8808** [gogits/gogs#4396]
Hello Folks,

I'm having the same issues described in the https://github.com/gogits/gogs/issues/3029 closed issue, but in my case I'm using the docker image on a docker swarm mode cluster. To fix the issue, normally I run the following command:

docker exec -u root $(docker ps -q --filter ancestor=gogs/gogs) chown -R git:git /app

But when the containers are scaled to another nodes (or recreated with newest versions) I need to run the same command (fortunately my Ansible is working hard for that) again on each node that have gogs started.

Informations about my environment:

Gogs Image: Latest (2017 Gogs Version: 0.11.4.0405, Go 1.8)
Docker 13.0.1/17.03-ce
Operating Systems: CoreOS stable, CentOS 7
Database: PostgreSQL

This is the output for the command  'docker service logs gogs_gogs':

https://gist.github.com/gcavalcante8808/7878776e3583567049aeca2d072b3a2b

I think that a RUN instruction creating the folder 'data' inside the '/app' or giving the ownership of the folder to user git will fix the problem (or using the acl to give the access).

Thanks in Advance.

**Comment by Unknwon** [comment]
Hi, are you using the official Gogs image? If yes, it is created https://github.com/gogits/gogs/blob/master/docker/start.sh#L34. Deployment issue goes to user forum.
