### ISSUE TITLE
after upgrade from 0.9 to 0.10/0.11 push is really slow

### ISSUE THREAD

**Issue by torsten-sauer** [gogits/gogs#4397]
- Gogs version (or commit ref): 0.11.4 (upgrade from 0.10.18, upgrade from 0.9.113)
- Git version: 2.7.4
- Operating system: Ubunut 16.04.2 LTS
- Database (use `[x]`):
  - [x] PostgreSQL (9.5.6)
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
....
2017/04/07 15:24:53 [TRACE] Session ID: 15d6eea37aab399f
2017/04/07 15:24:53 [TRACE] CSRF Token: SdPsrNMRifRE4CKki7e8PXg1PA06MTQ5MTU3MTQ5MzA4MjI0ODY2Mw==
2017/04/07 15:24:53 [TRACE] Session ID: cdf744dca1789fe8
2017/04/07 15:24:53 [TRACE] CSRF Token: FCk4IFYglek_3ZUTsMCNNMF3Qh46MTQ5MTU3MTQ5Mzc0MzEzMzI0Ng==
2017/04/07 15:24:53 [TRACE] HTTPGit - Authenticated user: torsten.sauer
2017/04/07 15:25:49 [TRACE] Session ID: 3544ab32f622bbad
2017/04/07 15:25:49 [TRACE] CSRF Token: Me2i2-WPUm4bA6MLoGkrfJiwJj86MTQ5MTU3MTU0OTAwNzQ0ODQyOA==
2017/04/07 15:25:49 [TRACE] Session ID: 0083cfbbe5cf02cb
2017/04/07 15:25:49 [TRACE] CSRF Token: p4TpH53APKfhxxK_v5ZT_FC6B9w6MTQ5MTU3MTU0OTI1Mzc5MzY3MQ==
2017/04/07 15:25:49 [TRACE] HTTPGit - Authenticated user: torsten.sauer
2017/04/07 15:25:49 [TRACE] Session ID: f53571d7cbc5c8ee
2017/04/07 15:25:49 [TRACE] CSRF Token: dSHvpC22VxqGU7PNHNOLdErjUMo6MTQ5MTU3MTU0OTYxMDY2NzMwNA==
2017/04/07 15:25:49 [TRACE] HTTPGit - Authenticated user: torsten.sauer
2017/04/07 15:27:53 [TRACE] Session ID: 6a5b6166c7e0f02e
2017/04/07 15:27:53 [TRACE] CSRF Token: fN_qTb-7ecX7IlzE8XNXuti4Gh46MTQ5MTU3MTY3MzA3NjE1ODIwOA==
2017/04/07 15:27:53 [TRACE] Session ID: 9108cd3852fe0956
2017/04/07 15:27:53 [TRACE] CSRF Token: nIX5F-TXQdA2mmqfCdNrTjMGo346MTQ5MTU3MTY3MzM0MDI5MDk1Mg==
2017/04/07 15:27:53 [TRACE] HTTPGit - Authenticated user: torsten.sauer
...

## Description
Situation: we have 18 repositories, sizing from a few kilobytes up to 8 GB (only one). We used version 0.9.113 since mid of January and everything was working perfectly. Gogs runs behind nginx as proxy (including SSL).

Two weeks ago we decided to upgrade to 0.10.18. Afterwards we have one really big issue: every push to our repositories is really really slow. I can see a process running `git receive-pack ...` during the push (including the `post-receive hook`) and if that finishes, the push is done.
Before the update the push was really fast, only a few seconds (if not to much data), but now it takes up to two minutes to push a file with 500bytes! I had to increase the proxy timeout for nginx, because first after upgrade every push was failing because of timeout.

There are no errors, no custom hook scripts (I checked the folders twice in every repository), nothing that makes clear, why this is happening. It happens for every repository and it happens with pushing via ssh and https.

If I remove the `post-receive` hook from a repository the push is fast again, but the stream inside gogs isn't updated (what makes sense to me, if I get the code right).

I thought of downgrade to version 0.9 again, because it's really annoying to wait a few minitues to push the work of the day if it worked before the upgrade within a few seconds.

Maybe someone has an idea? Something I could try? Something to debug?

**Comment by Unknwon** [comment]
Set `RUN_MODE = dev` then push again, you'll see log in `log/hooks/post-receive.log` and I guess the callback to web URL is slow. Check on that URL.

**Comment by torsten-sauer** [comment]
I'll did and found following log entry:

`[TRACE] Trigger task: http://0.0.0.0:3000/....`

It's quite obvious that this won't work -.-

I had to set the `HTTP_ADR` - wasn't set before, set to 127.0.0.1 because nginx already proxying it... 

Thanks for pointing me to the right direction! Working again!
