### ISSUE TITLE
Expose the wiki's Git repository

### ISSUE THREAD

**Issue by monnier** [gogits/gogs#4399]
It's great that the Wiki is kept in a Git repository so it can be consulted and edited offline using any standard tool.  But this currently seems to be an accidental feature: it should be documented more prominently and the Git repository should be available for browsing just like the main repository, and many of the other features that apply to the main Git repository should also apply to the Wiki (e.g. webhooks, Git hooks, commit diff notifications, ...).

**Comment by Unknwon** [comment]
Please do search and test before open an issue: https://try.gogs.io/unknwon/blade/wiki

**Comment by monnier** [comment]
Sorry, but I don't see where that lets me see the wiki's history or configure webhooks/githooks.  I do see that it gives me the URL to access the wiki, admittedly.  For example, going to https://try.gogs.io/unknwon/blade.wiki/src/master/ gives me a 404.

**Comment by Unknwon** [comment]
1. Do not put discussion thoughts in one single issue, please go user forum.
2. 
![image](https://cloud.githubusercontent.com/assets/2946214/24817098/2b30bb36-1ba9-11e7-80e5-ac3e9cfae645.png)
3. Wiki is one-flat layer only

**Comment by Unknwon** [comment]
You can always create multiple issues with one single purpose for each issue, and we can determine if issue should be kept after that. Group multiple features together does not work, especially some of them already had related issues. Therefore, best thing to do is post on user forum first.
