### ISSUE TITLE
Preview of a local image not working in fullscreen

### ISSUE THREAD

**Issue by pohy** [gogits/gogs#4402]
- Gogs version (or commit ref): 0.11.6.0407
- Git version: Unkown
- Operating system: Unkown
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io: 
  - [x] Yes https://try.gogs.io/pohy/image-preview-issue/_edit/master/README.md
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): Unkown

## Description

![image](https://cloud.githubusercontent.com/assets/2036806/24821901/9a08abde-1bf1-11e7-80f2-a27aabe5beb1.png)

**Comment by Unknwon** [comment]
>Can you reproduce the bug at https://try.gogs.io:
 Yes

URL?

**Comment by pohy** [comment]
Sorry, updated the issue.

**Comment by Unknwon** [comment]
What I see is you don't have correct file name of image, missing "Screen". Fixed one for you.

**Comment by Unknwon** [comment]
Ah I see, the "Preview" and "Full Screen" buttons are not working.

PS: actually these two buttons shouldn't be showed for repository file editing.

**Comment by Unknwon** [comment]
Please use "Preview" tab!

![image](https://cloud.githubusercontent.com/assets/2946214/24822354/8e57797a-1bc2-11e7-91f7-0e82980a043f.png)
