### ISSUE TITLE
Pushed commits not shown on new empty repo

### ISSUE THREAD

**Issue by olived19** [gogits/gogs#4404]
- Gogs version (or commit ref): 0.11.4
- Git version: 2.9.3
- Operating system: Raspbian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): Logs are empty

## Description
- If I create an empty repository (without "Initialize this repository with selected files and template) then if I try to push from an existing repo (using SSH) the push is successful but files are not shown on the web interface. I still have the "Quick Guide" message.
- I tried to push using HTTP but it failed because of the autosigned cert.
- If I create a repo with the initial commit, then I can pull, commit and push without problem.
...

**Comment by mpmcgrellis** [comment]
I'm seeing the same thing with HTTPS and gogs 0.11.6.0407.

- I create a new empty repo without "initialize this repository..." checked. 
- I add the remote and push according to instructions in the quick guide message
- I see no files in the web UI

Git operation appears to work as expected.  I can clone the repo, push to it, etc.  The web UI just never shows anything.

**Comment by Unknwon** [comment]
Hi, please checkout https://discuss.gogs.io/t/how-to-config-ssh-settings/34.

**Comment by olived19** [comment]
Thank you for your reply.
Actually my SSH config works fine with Gogs, the only problem is when the repo is empty the UI does not show anything. My guess is that the method which triggers the refresh is never called on an empty repo.

**Comment by Unknwon** [comment]
@olived19 show result of `ssh -T {your SSH URL}`.

**Comment by olived19** [comment]
Here is the result :
```
$ ssh -T gitprivate@gogs.my.home
gitprivate@gogs.my.home's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
fatal: Interactive git shell is not enabled.
hint: ~/git-shell-commands should exist and have read and execute access.
```

and this is a copy/paste of the panel admin > config :

> SSH Configuration
> 
> Enabled                                  [x]
> Start Builtin Server                  [ ]
> Domain                                   gogs.my.home
> Port                                         22
> Listen Port                               22
> Root Path                                /home/gitprivate/.ssh
> Key Test Path                         /tmp
> Keygen ('ssh-keygen') Path    ssh-keygen
> Minimum Key Size Check       [ ]

**Comment by Unknwon** [comment]
You bypassed Gogs delegation, that's why I recommend you read https://discuss.gogs.io/t/how-to-config-ssh-settings/34. Gogs didn't know you pushed.

**Comment by olived19** [comment]
OK with the appropriate configuration everything works fine now. Thank you !
One last question, my git user had the shell /usr/bin/git-shell but it wasn't able to run the command from authorized_keys. I had to change it to /bin/bash. Is there any way to keep /usr/bin/git-shell for security reasons ?

**Comment by Unknwon** [comment]
Hmm, I don't know what's different between your `git-shell` and `bash`, so I can't tell...

**Comment by olived19** [comment]
Basically `bash` is the regular shell and `git-shell` is a special one which allows only limited commands on the server.

> This is a login shell for SSH accounts to provide restricted Git access. It permits execution only of server-side Git commands implementing the pull/push functionality, plus custom commands present in a subdirectory named git-shell-commands in the user’s home directory.

(https://git-scm.com/docs/git-shell.html)

**Comment by Unknwon** [comment]
OK... you can try but no guarantee it's going to work...

**Comment by olived19** [comment]
Indeed `git-shell` is not working with the setup for Gogs.
Never mind, thank you for your time !

**Comment by pefimo** [comment]
I'm seeing the same problem as @olived19 did, though I'm not using SSH to push (having all my remotes set to `/http[s]?/` ones). I thought that with this configuration my Gogs instance would "see" objects/change-sets upon their arrival? Do I miss something?

By the way, Gogs is great, thanks a lot for creating it!

**Comment by Unknwon** [comment]
@pefimo Maybe you want to check if there is any error in the `path/to/gogs/log` directory.
