### ISSUE TITLE
FATAL error during restore of backup

### ISSUE THREAD

**Issue by nkanellopoulos** [gogits/gogs#4413]
- Gogs version (or commit ref): 0.11.4.0405 
- Git version: 2.11.0
- Operating system: Mac OS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
[gogs-backup-1491839420.zip](https://github.com/gogits/gogs/files/911126/gogs-backup-1491839420.zip)

## Description

I tried to restore a backup I took in another Mac (same software versions on both machines for OS, git and gogs).

I am getting this error:

```
$ ./gogs restore --from gogs-backup-1491839420.zip
2017/04/10 20:56:24 [ INFO] Restore backup from: gogs-backup-1491839420.zip
2017/04/10 20:56:25 [FATAL] Fail to import 'data': rename /var/folders/r9/vrqrmnx54rn30nd88fvljrs00000gp/T/gogs-backup/data/attachments data/attachments: no such file or directory
```

I attach the backup file. Contains test data.

**Comment by opavader** [comment]
I had the same issue. It seems that its trying to restore the attachments folder even if it didn't existed in the original setup(thus not in backup too). 
Just make a empty directory `data/attachments` there & it will work.

**Comment by Unknwon** [comment]
Hi, I think the real problem is the `data` directory is not created.

Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by fschick** [comment]
> "Just make a empty directory data/attachments there & it will work"

doesn't helped me. If attachments directory is created by hand, it will be moved to attachments.bak and the error is shown unchanged.

**Comment by Unknwon** [comment]
@fschick hi, this issue is meant to be fixed already if you're using 0.11.19 or higher.

**Comment by fschick** [comment]
Unfortunately not, I'm using version 0.11.19.0609 and the problem still exists.

 ./gogs -v
Gogs version 0.11.19.0609

Output from './gogs restore -v': [restore.zip](https://github.com/gogits/gogs/files/1093720/restore.zip)

**Comment by Unknwon** [comment]
@fschick thanks! Just push another path to `master`, please help test again.

**Comment by fschick** [comment]
It's working now with build from master branch. Thank you!
