### ISSUE TITLE
Private repo activity shown in "Public activity" tab, if the repo was once public

### ISSUE THREAD

**Issue by afg984** [gogits/gogs#4414]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: git version 1.8.3.1
- Operating system: CentOS Linux 7.3.1611 Core
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io: 
  - [x] Yes https://try.gogs.io/afg984?tab=activity
  - [ ] No
  - [ ] Not relevant

## Description

1. Create a public repo
2. commit some stuff
3. make the repo private
4. the commits in 2. is still shown at the user's public activity tab

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by afg984** [comment]
I can confirm it's been fixed in https://try.gogs.io.
