### ISSUE TITLE
Updated 🇨🇿 Czech translation

### ISSUE THREAD

**Issue by rbukovansky** [gogits/gogs#4416]
@Unknwon Hi, could you please update Czech (cs-CZ) locale with approved strings from Crowdin? I went through the whole CZ translation again and improved, united and approved a lot's of changes. Thank you.

**Comment by Unknwon** [comment]
Hi, should be updated in https://github.com/gogits/gogs/commit/a11044f78954f5c173d686cd46833386cc43bc16#diff-8d7e6724b1d4111cbb1ef2e5fa7a414c.

Ping me if something is still missing.
