### ISSUE TITLE
An error has occurred : mssql: Incorrect syntax near the keyword 'DISTINCT'

### ISSUE THREAD

**Issue by andr01d** [gogits/gogs#4419]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.12.2.windows.2
- Operating system: Windows Server 2008 R2 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/04/11 19:39:20 [TRACE] Template: status/500
2017/04/11 19:39:30 [TRACE] Session ID: 7130545927b7e2ee
2017/04/11 19:39:30 [TRACE] CSRF Token: K0NUJ7CWWAWA8SD77qkQU4wJfGM6MTQ5MTk1MTUzNjY4Nzg2NzYwMA==
2017/04/11 19:39:30 [ERROR] [...g/context/context.go:109 Handle()] SearchRepositoryByName: mssql: Incorrect syntax near the keyword 'DISTINCT'.
## Description
When trying to access the route "/explore/repos" we get the following error on a 500 page:
mssql: Incorrect syntax near the keyword 'DISTINCT'.
...

**Comment by CodeFunta** [comment]
+1
I've found in SQL Profile the following script that cause the issue:
`exec sp_executesql N'SELECT  TOP 20 DISTINCT "repo".* FROM "repository" AS "repo" LEFT JOIN "access" ON access.repo_id = repo.id WHERE (repo.owner_id = @p1 OR access.user_id = @p2 OR repo.is_private = @p3) ORDER BY repo.updated_unix DESC',N'@p1 bigint,@p2 bigint,@p3 bit',@p1=3,@p2=3,@p3=0`

**`SELECT DISTINCT TOP 20`** will fix the error

**Comment by w3p706** [comment]
+1

could it be a bug in [go-mssqldb driver for xorm](https://github.com/denisenkom/go-mssqldb)?

**Comment by 22222** [comment]
This probably started happening with the change from #4344, when a `Distinct` call was added to a query that already had a `Limit`.  And I'm guessing it needs to be fixed in xorm?  Although it might be possible to do some kind of workaround by making a bigger change to that query.

**Comment by Unknwon** [comment]
Hi, I've updated vendor for `github.com/go-xorm/*`, things should work now, please help test!

**Comment by CodeFunta** [comment]
Hi, seems to be fixed for now. Thank you.
