### ISSUE TITLE
Change files list background color

### ISSUE THREAD

**Issue by gino-il-facchino** [gogits/gogs#4420]
- Gogs version (or commit ref):  dev
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/ZeroNet/ZeroNet
  - [ ] No
  - [ ] Not relevant

## Description

OK this is not a big issue, just a UI thing. In the list of files when I move the mouse over an item, the background changes to a pale, dull yellow. As a designer, this looks very ugly. Would it be possible to replace it with another color, for example a light blue?

**Comment by Unknwon** [comment]
You can include your custom CSS via https://gogs.io/docs/features/custome_template
