### ISSUE TITLE
Older Gogs's Repos( generated with Gogs 0.9.141) could not push after update Gogs0.11.0 or0.11.4

### ISSUE THREAD

**Issue by bygreencn** [gogits/gogs#4424]
- Gogs version (or commit ref):  
- Git version: 0.11.4
- Operating system: windows7 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No  **Since do not have elder gogs's version Repo, So could not test it, but can reproduct it at all  my local repos which are generated with 0.9.141 **
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
[Macaron] 2017-04-13 18:41:42: Started GET /xxx/test1111.git/info/refs?service=git-receive-pack for 192.168.0.175
[Macaron] 2017-04-13 18:41:42: Completed GET /xxx/test1111.git/info/refs?service=git-receive-pack 401 Unauthorized in 9.0005ms
[Macaron] 2017-04-13 18:41:43: Started GET /xxx/test1111.git/info/refs?service=git-receive-pack for 192.168.0.175
[Macaron] 2017-04-13 18:41:43: Completed GET /xxx/test1111.git/info/refs?service=git-receive-pack 200 OK in 266.0152ms
[Macaron] 2017-04-13 18:41:43: Started POST /xxx/test1111.git/git-receive-pack for 192.168.0.175
[Macaron] 2017-04-13 18:41:44: Completed POST /xxx/test1111.git/git-receive-pack 200 OK in 757.0433ms

## Description 
1. the Repos which are generated by Gogs 0.9.141, after update update Gogs to 0.11.0 or 0.11.4, could not push anything to server. The message is  ***localhost has been manual modified to not show IP***
**"C:\Program Files\Git\bin\git.exe" push --progress  "origin" :reremote: Gogs: Internal error
To http://localhost/xxx/test1111.git
 ! [remote rejected] test (pre-receive hook declined)
error: failed to push some refs to 'http://localhost/xxx/test1111.git'
Done
Press Enter or Esc to close console...**
2. the Repos which are generated by Gogs 0.11.0 or 0.11.4, all are OK.
3. Do not have options to close Git HOOK, *or maybe I could not found at your Doc to learn it*.
4. Compare these Repos from server, the the different is the file pre-receive

***Generated by Gogs 0.9.141 are:***
 #!/usr/bin/env bash
 #"C:/git_gogos/gogs.exe" hook --config='C:/git_gogos/custom/conf/app.ini' pre-receive

***Generated by Gogs 0.11.4 are:***
 #!/bin/sh
 #An example hook script to make use of push options.
 #The example simply echoes all push options that start with 'echoback='
 #and rejects all pushes when the "reject" push option is used.
 #To enable this hook, rename this file to "pre-receive".
if test -n "$GIT_PUSH_OPTION_COUNT"
then
	i=0
	while test "$i" -lt "$GIT_PUSH_OPTION_COUNT"
	do
		eval "value=\$GIT_PUSH_OPTION_$i"
		case "$value" in
		echoback=*)
			echo "echo from the pre-receive-hook: ${value#*=}" >&2
			;;
		reject)
			exit 1
		esac
		i=$((i + 1))
	done
fi

**Comment by bygreencn** [comment]
### More Info:
#### Repo Generated by Gogs 0.9.141.
1. not change git hook of pre-receive, **FAILED**.
2. change git hook of pre-receive with empty, **OK**.
3. change git hook of pre-receive without empty, **FAILED**.

#### Repo Generated by Gogs 0.11.4 .
1. not change git hook of pre-receive, **OK**.
2. change git hook of pre-receive with empty, **OK**.
3. change git hook of pre-receive without empty, **FAILED**.

### Resync all hooks could not fix issue.

@Unknwon need tools to fix it.

**Comment by bygreencn** [comment]
@Unknwon any progress?

**Comment by bygreencn** [comment]
![1](https://cloud.githubusercontent.com/assets/22853/25083756/539cdc1e-238b-11e7-9f0f-426061ea939e.png)
@Unknwon

**Comment by bygreencn** [comment]
#### OK, I found a solution to make all Repoes work:
1. At server side, 
2. Enter gogs-repositories directory 
3. Delete all ***user*** \ ***repository.git*** \custom_hooks\pre-receive.
***user*** may all users at this server;
***repository.git*** may all repositories that this user created and forked.
#### But, this may be a version compatibility issue, the file of "custom_hooks\pre-receive" was not generated manually by user.
___
On windows, I make a batch script for do it, move it to gogs repository root directory and run it.
_@echo off
for /r %%s in (.) do (if exist %%s\custom_hooks\pre-receive (echo %%s\custom_hooks\pre-receive & del /f %%s\custom_hooks\pre-receive))_

**Comment by akademic** [comment]
I've got same thing on https://try.gogs.io
I have old repository on try.gogs.io, created by version 0.9.x
And now on push I see `remote: Gogs: Internal error`

Example url: https://try.gogs.io/test_ttt/base_repo

**Comment by LukeMauldin** [comment]
I have this problem too on repos I copied from a Gogs server to a Gogs docker container.  I was able to fix it by making symlinks for the previous location of the Gogs binary and the configuration file.  Still, I think this should be fixed by Gogs.

**Comment by xiaoxinyi** [comment]
```
gogs -v  # 0.9.100.1119
```
At server side:
```
"/app/gogs/gogs" hook --config='./conf/app.ini' pre-receive
```

**Error:**
```
remote: No help topic for 'hook'
```

**Solution:**

```
cd gogs-repositories

find . -iname 'pre-receive' | xargs rm -rf
```

**Comment by Unknwon** [comment]
Hi, based on https://github.com/gogits/gogs/issues/4424#issuecomment-294431594, this is the exact same problem reported in https://github.com/gogits/gogs/issues/4255.
