### ISSUE TITLE
User not redirected after login for new issue

### ISSUE THREAD

**Issue by teadawg** [gogits/gogs#4429]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.11.1
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
If a user wants to submit an issue, he is redirected to Dashboard after log in and not the new issue site. The is especially difficult if the user wants to submit an issue to a private repository, where the issue site can only be found by direct link.

**Comment by meersau** [comment]
And also if the user just wants to access the Repository page.

So it would be great that after authentication the user will be redirected to the URL which he first intended to visit.

**Comment by jaragunde** [comment]
I've noticed that the redirection already happens when the "remember me" checkbox had been checked: you open the link, the browser redirects to the login page and immediately to the expected page. The functionality is already there, it just has to be used in the manual login process.

**Comment by Unknwon** [comment]
This should be fixed already.
