### ISSUE TITLE
No email if issue closed by commit 

### ISSUE THREAD

**Issue by teadawg** [gogits/gogs#4430]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.11.1
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description
If an issue is closed by commit (e.g. fix #X) the user who opened the issue is not informed by email.

**Comment by S3NS4Ti0N** [comment]
I was wondering about this too

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by moltam** [comment]
The patch works, I've closed an issue with a commit, and I've received the notification email.

**Comment by S3NS4Ti0N** [comment]
Can confirm this too
