### ISSUE TITLE
500 Internal Server Error when trying to compare two branches.

### ISSUE THREAD

**Issue by mastorm** [gogits/gogs#4434]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 12.2.2
- Operating system: Microsoft Windows 2016
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist (usually found in `log/gogs.log`):
https://gist.github.com/mastorm/d88bda44601f13f0019fcbfe673791dd
## Description

Server Error 500 when trying to compare two branches of the same repository.

/Company/Product/compare/branch1...Company:branch2

This is the URL we´re trying to invoke(in an anonymized manner). We tried updating Git and Gogs and we also tried deleting the tmp folder. It worked a couple of weeks ago, although that was an older version of gogs(0.9.141).

**Comment by akademic** [comment]
I've got similar issue at https://try.gogs.io

Example url: https://try.gogs.io/test_ttt/test_merge_webhook/compare/master...second

**Comment by mastorm** [comment]
Is there anything I can provide to ease the issue resolution? I tried almost every Issue that ever mentioned a 500 at this point. I also tried removing the repository and recreating it. I also tried doing it on different environments. I have no idea how to resolve this, we cant do any PR anymore

**Comment by Unknwon** [comment]
From example repo provided by @akademic, two branches are in a status that no common parent (two completely different trees), I think that's the problem.

**Comment by Unknwon** [comment]
Which means, it is not even possible to merge. It is wrong from start. GitHub also gives "nothing to compare" if I upload the example repo:

![image](https://cloud.githubusercontent.com/assets/2946214/26769620/552975d8-497e-11e7-8980-cad50735076d.png)

I'll handle this error better by showing nothing to compare also, but I don't think there is a solution on Gogs's end.

**Comment by Unknwon** [comment]
Patch has pushed to work on this issue, please test on `develop` branch or https://try.gogs.io.
