### ISSUE TITLE
Add option to rewrite authorized_keys file at start

### ISSUE THREAD

**Issue by drscream** [gogits/gogs#4435]
- Gogs version (or commit ref): 0.11.6.0407
- Git version: 2.11.0
- Operating system: SunOS / SmartOS Zone
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

This is a feature request to write the `.ssh/authorized_keys` file once at boot / start time of `gogs web`. This would be helpful if maybe the file is broken during reboot or re-provision of an image. It also would guarantee that the file is valid and contains only all valid ssh keys from the gogs application.

If this feature requests doesn't fit the requirements or is not recommended it would be an alternative to provide an admin command to export all SSH key automatically!

**Comment by Unknwon** [comment]
>If this feature requests doesn't fit the requirements or is not recommended it would be an alternative to provide an admin command to export all SSH key automatically!

You can do this already in admin dashboard...
![image](https://user-images.githubusercontent.com/2946214/27063781-c50aa4f0-4fc1-11e7-942c-bf37019b1a02.png)

**Comment by drscream** [comment]
Well this isn't automate-able because I need to login and press a button. I'm looking for a command line or API solution to do that automatically.

**Comment by Unknwon** [comment]
OK... if you want to be able to do this operation at every start, I can make this thread to be a feature request.

**Comment by drscream** [comment]
Thanks a lot! It was never supposed to be a bug report so thanks to assign it as feature requests :-)

**Comment by knedlsepp** [comment]
This could be solved via: https://github.com/gogits/gogs/pull/4813

**Comment by drscream** [comment]
@knedlsepp that would be great :-)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by e-tinkers** [comment]
1) How can this be a feature if only one guy asking for it? I accidentally change something (I think it was DISABLE_SSH) and got locked out from my server and no longer be able to ssh into the system, despite that my REWRITE_AUTHORIZED_KEYS_AT_START is set to false. 2) A setting should have only one meaning and not dependent on other setting's status. 3) If this is a feature,  then there should be a warming and a UI configuration to warm the user explicitly.

**Comment by unknwon** [comment]
>1. How can this be a feature if only one guy asking for it?
I don't see the argue point.

> ... I accidentally change something (I think it was DISABLE_SSH) and got locked out from my server and no longer be able to ssh into the system, despite that my REWRITE_AUTHORIZED_KEYS_AT_START is set to false.
Anyone can get locked out with SSH access for whatever reason `.ssh/authorized_keys` gets messed up for all kinds of possibilities. Proof before arguing is better.

>2. A setting should have only one meaning and not dependent on other setting's status. 
I don't see the argue point for this particular feature.

>3. If this is a feature, then there should be a warming and a UI configuration to warm the user explicitly.
I don't see the argue point for this particular feature.

**Comment by e-tinkers** [comment]
My apology, I'm not trying to argue. I'm new to gogs, and still trying to find out what configuration cause the gogs to override the REWRITE_AUTHORIZED_KEYS_AT_START setting (it is false by default), I think it was when I change the DISABLE_SSH from false to true that caused the .ssh/authorized_keys to be emptied. Can you confirm this is the behaviour? And if this is the case, my suggestion is if REWRITE_AUTHORIZED_KEYS_AT_START is depent on the setting of DISABLE_SSH and its state will be override, then there should be a warning explicitly. 

One of the difference in my configuration is that instead of creating a separate git user, I use my existing Linux username, so when the .ssh/authorized_keys is emptied because the public key is no longer there. This will not be a problem if using a separate user, because git will has its own .ssh/authorized_keys.

Once again, my apology and appreciated your effort in maintaining this project. p.s. I have reversed my server back, thanks to the backup that I have.

**Comment by unknwon** [comment]
>My apology, I'm not trying to argue. I'm new to gogs, and still trying to find out what configuration cause the gogs to override the REWRITE_AUTHORIZED_KEYS_AT_START setting (it is false by default), I think it was when I change the DISABLE_SSH from false to true that caused the .ssh/authorized_keys to be emptied. Can you confirm this is the behaviour? And if this is the case, my suggestion is if REWRITE_AUTHORIZED_KEYS_AT_START is depent on the setting of DISABLE_SSH and its state will be override, then there should be a warning explicitly.

`REWRITE_AUTHORIZED_KEYS_AT_START` is only `true` if you explicitly set it to be `true` [in the configuration](https://github.com/gogs/gogs/search?q=RewriteAuthorizedKeysAtStart&unscoped_q=RewriteAuthorizedKeysAtStart).

>One of the difference in my configuration is that instead of creating a separate git user, I use my existing Linux username, so when the .ssh/authorized_keys is emptied because the public key is no longer there. This will not be a problem if using a separate user, because git will has its own .ssh/authorized_keys.

In this scenario, `DISABLE_SSH` at installation step actually won't wipes out your `.ssh/authorized_keys` content.
