### ISSUE TITLE
web-hook  推送到使用https的持续集成工具的问题.

### ISSUE THREAD

**Issue by airforce-captain** [gogits/gogs#4438]
使用的最新0.11.6 官方docker 镜像.

创建web 钩子，测试推送事件消息.

`https://jenkins/gogs-webhook/?job=demo207`

数据格式:
`application/json`

返回错误信息：

`Delivery: Post https://jenkins/gogs-webhook/?job=demo207: x509: certificate signed by unknown authority`

同样的url ，如果更改为http方式则推送消息成功.

https 使用的是let's encrypt 提供的免费dv 证书, 并非自签名证书. 使用浏览器访问一切正常，并不会像自签名证书有提示不安全的网络.

gogs 不支持https ？ 如何解决？

**Comment by airforce-captain** [comment]
已解决。证书的问题。

**Comment by ddyllen-z** [comment]
@airforce-captain 证书什么问题？
