### ISSUE TITLE
Emoji not rendered on commits view

### ISSUE THREAD

**Issue by carbontwelve** [gogits/gogs#4439]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: n/a
- Operating system: Ubuntu 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes, see https://try.gogs.io/c12/emoji-test/commits/master
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): n/a

## Description

I am not sure if this is or isn't related to #3023, however I am running Gogs version `0.11.4.0405` and have noticed that on the commit history page emoji aren't rendered even though the `<td>` element has the `has-emoji` class.

Having had a look at [gogs.js](https://github.com/gogits/gogs/blob/6ea9642d6415073c6312c80bf6533a5070630ad2/public/js/gogs.js#L1252) the implementation of emojify looks to be correct.

Looking at [commits_table.tmpl])(https://github.com/gogits/gogs/blob/9e3c83372f19853ac1dc164e2fcf58d9779ac0f0/templates/repo/commits_table.tmpl#L43) a fix is to place the `has-emoji` class onto the `<span>` rather than on the `<td>`.

I am going to fork and create a pull request the above effect.

**Comment by carbontwelve** [comment]
The result of my pull request: #4440

Before:
![image](https://cloud.githubusercontent.com/assets/464699/25223534/88e2244a-25b3-11e7-986b-0e0a7b67d8dd.png)

After:
![image](https://cloud.githubusercontent.com/assets/464699/25223456/56560f1e-25b3-11e7-9279-be8d1df1cc64.png)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4440, please help test on `develop` branch or https://try.gogs.io.

**Comment by carbontwelve** [comment]
Confirmed fixed on try.gogs.io
![image](https://cloud.githubusercontent.com/assets/464699/26578176/c2b28aec-4526-11e7-8c17-406247226619.png)

**Comment by Unknwon** [comment]
Mis-click... sorry about any noise.
