### ISSUE TITLE
Explore paging bug

### ISSUE THREAD

**Issue by fromiuan** [gogits/gogs#4441]
- Gogs version (or commit ref): 0.11.4.0405
- Git version:  
- Operating system: centos 6.5 x86
- Database (use `[x]`):
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
page bug
when i click menu Explore ,I see the page count is 8,but when i click page 6,not any content,in my Repositories have 91 project, the project include private and public,

**Comment by fromiuan** [comment]
![](http://i.imgur.com/KYdRSrA.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by fromiuan** [comment]
thinks,
