### ISSUE TITLE
Wrong commit ref in webhook payload after merging pull request

### ISSUE THREAD

**Issue by akademic** [gogits/gogs#4442]
- Gogs version (or commit ref): 0.11.8.0407
- Git version: 2.1.4
- Operating system: N/A
- Database: N/A
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/sjrt/test_merge_webhook2
- Log gist: https://gist.github.com/akademic/5dfe294a0d37d812b5b5097a011586b7

## Description

I've using drone.io for CI.
It uses `after` field from webhook payload json for testing.
But "after" field doesn't points at "merge commit" - latest commit in `commits` list, but it points at last commit in branch.
So drone doesn't tests resulting state of repository, but only merged branch.

I think that "after" field should point at `df35735412f9603256fffa04537c22231e9a1bc9` in my case (look at log gist)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
