### ISSUE TITLE
Cannot push multiple files - Apache Mod Proxy Error?

### ISSUE THREAD

**Issue by rocketdoge** [gogits/gogs#4443]
- Gogs version (or commit ref): 0.11.6.0407
- Git version: Client: 2.12.2; Sever: 2.1.4
- Operating system: Client: Manjaro Arch; Server: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
`2017/04/21 23:13:25 [TRACE] Session ID: cf6bfb33ae944f4a

2017/04/21 23:13:25 [TRACE] CSRF Token: LmEA-CzQeBq3JFDhRSSOKFQU8Nw6MTQ5MjgwOTIwNTA5NjQ0NTA1MQ==

2017/04/21 23:13:25 [TRACE] Session ID: 6b4a2a64901164d3

2017/04/21 23:13:25 [TRACE] CSRF Token: PHlo0sCJdKDFInYFbx11qFIuB4Y6MTQ5MjgwOTIwNTQzMzUzNjI4OQ==`

## Description

I can push single files just fine, but when I try to push multiple files at once I get
`error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502 Bad Gateway`

`fatal: The remote end hung up unexpectedly`

`fatal: The remote end hung up unexpectedly`

`Everything up-to-date`

I think it has something to do with the apache2 reverse proxy I use, heres the log:
`[Fri Apr 21 23:13:25.953039 2017] [proxy:error] [pid 30628] (32)Broken pipe: [client 123.456.789.123:44522] AH01084: pass request body failed to 127.0.0.1:6000 (127.0.0.1)`

`[Fri Apr 21 23:13:25.953260 2017] [proxy_http:error] [pid 30628] [client 123.456.789.123:44522] AH01097: pass request body failed to 127.0.0.1:6000 (127.0.0.1) from 123.456.789.123 ()`

Has anyone had a similar problem? How do I fix that?

My Apache2 VHost:

`ServerName git.example.com`
  `ServerSignature Off`
 `ProxyPreserveHost On`

  `SSLEngine on`
  `SSLCertificateFile /etc/letsencrypt/live/www.example.com/fullchain.pem`
  `SSLCertificateKeyFile /etc/letsencrypt/live/www.eample.com/privkey.pem`

  `ProxyPreserveHost On`
  `ProxyRequests off`
  `ProxyPass / http://127.0.0.1:6000/`
  `ProxyPassReverse / http://127.0.0.1:6000/`

**Comment by justoaguilar** [comment]
Have try this
https://stackoverflow.com/questions/20406845/proxy-error-502-the-proxy-server-received-an-invalid-response-from-an-upstream/21849150#21849150

**Comment by dvarrel** [comment]
i have the same issue, but modifying apache2.conf doesn't change anymore.

`[Sat Nov 28 09:13:04.753605 2020] [proxy_http:error] [pid 23418] [client 86.248.218.176:50492] AH01097: pass request body failed to 127.0.0.1:3000 (127.0.0.1) from 86.248.218.176 ()`
