### ISSUE TITLE
Gogs is wasting server resources because it's not killing jobs

### ISSUE THREAD

**Issue by smiley-smurf** [gogits/gogs#4446]
- Gogs version (or commit ref): dev
- Operating system: gnu/linux
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

## Description

Gogs is not killing long-running, intensive jobs if users disconnect. This results in a lot of wasted resources because the jobs keep running even if the user has disconnected, and it's spending ages doing useless rendering that will be discarded immediately when finished.

**Comment by Unknwon** [comment]
Please define "long-running, intensive jobs".

**Comment by giltee** [comment]
I just ran into this issue today. We have massive uploads to our server (10GB+) and the jobs are not being killed after any uploads. This is causing our server to fault because all the resources are being dedicated to these jobs. Please let me know if I can provide additional information.
