### ISSUE TITLE
Can't git clone using ssh from my gogs repository

### ISSUE THREAD

**Issue by chenshuiluke** [gogits/gogs#4447]
Good night, I set up Gogs today and everything seems to be working fine except for cloning via ssh.

This is what I get:

	git clone gogs@git.lukechenshui.com:chenshuiluke/jresume.git
	Cloning into 'jresume'...
	nologin: invalid option -- 'c'

	Usage:
	 nologin [options]

	Politely refuse a login.

	Options:
	 -h, --help     display this help and exit
	 -V, --version  output version information and exit

	For more details see nologin(8).
	fatal: Could not read from remote repository.

	Please make sure you have the correct access rights
	and the repository exists.

I have already added an extra public key for accessing my gogs repo:

	Host gogs
	    HostName git.lukechenshui.com
	    IdentityFile ~/.ssh/id_rsa_gog.pub
	    IdentitiesOnly Yes

and I added ~/.ssh/id_rsa_gog.pub to the list of public keys for my user in the Gogs web interface. I also tried regenerating the authorized key file from /admin but that didn't help either.

**Comment by chenshuiluke** [comment]
A bit of an update. I was able to get it working using:

	SSH_PORT         = 4096
	SSH_LISTEN_PORT = 4096
	START_SSH_SERVER = true

and cloning using `ssh://gogs@git.lukechenshui.com:4096/chenshuiluke/jresume.git`

**Comment by flortsch** [comment]
Looks like your git user has the wrong shell. Edit /etc/passwd and change /usr/sbin/nologin to /bin/sh or /bin/bash for your git user.

**Comment by chenshuiluke** [comment]
Thanks, I just changed the shell for the `gogs` user to /usr/bin/fish and it seems to be working now!

**Comment by shockerli** [comment]
@chenshuiluke I solved the problem through your solution. Thanks.

**Comment by chenshuiluke** [comment]
@shockerli Glad I could help :)
