### ISSUE TITLE
Fail to initialize ORM engine: sync database struct error: Error 1062: Duplicate entry '40-28' for key 'UQE_issue_REPO_INDEX'

### ISSUE THREAD

**Issue by xiuchanghu** [gogits/gogs#4448]
Gogs version (or commit ref): 0.9.13.0318
Git version:1.9.1
Operating system:
Database (use [x]):
 PostgreSQL
[X ] MySQL
 SQLite
[X ] Not relevant
Log gist:
Description

We are trying to upgrade gogs to the version v0.9.46. While upgrading we are getting the following error

[...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: Error 1062: Duplicate entry '40-28' for key 'UQE_issue_REPO_INDEX'

Can you advise on the solution.

**Comment by Unknwon** [comment]
Hi, the easy way to fix is to delete the row `id = 40 AND index = 28` from your `issue` table.
