### ISSUE TITLE
Configurable TLS Support (Allow min setting)

### ISSUE THREAD

**Issue by spacetourist** [gogits/gogs#4450]
Hello again,

I am about to embark on the development of a feature to allow TLS minimum support levels to be configurable via the config file. This is a requirement for the environment in which I am using Gogs and I hope it will be useful to others.

I intend to leave the default value (tls.VersionTLS10) in place however will be introducing a new config file setting:

TLS_MIN_VERSION

Valid [values](https://golang.org/pkg/crypto/tls/#pkg-constants): 

SSL30
TLS10 (default)
TLS11
TLS12

These will be translated to the appropriate Go tls library constant and applied at runtime. 

The main target code is [here](https://github.com/gogits/gogs/blob/9e3c83372f19853ac1dc164e2fcf58d9779ac0f0/cmd/web.go#L676).

I'll issue a pull request upon completion. 

Thanks!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4451, please help test on `develop` branch.
