### ISSUE TITLE
Implement LDAP via Bind DN in gogs

### ISSUE THREAD

**Issue by prashantprabhakar** [gogits/gogs#4457]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

I tried to integrate LDAP in gogs, I used LDAP via Bind DN for that.

My entries:
```
 Host: 10.10.20.14
 Port: 389
Bind DN: CN=LDAP Admin,OU=ADMN-USRS,DC=GEMSOL,DC=IN
Bind Password: xxxxxxxxxxxxx
 User Search Base: OU=GEMINI, DC=GEMSOL, DC=IN
 User Filter: (&(objectClass=person)(sAMAccountName=%s))
 username attribute: sAMAccount
 First name attribute: cn
 Surname attribute: sn
 Email attribute : mail
```

Then I updated one user from `local` to `ldap-gogs`, and in Authentication Login Name= his ldap credential.

But while logging, I am getting an error of  Username or password is not correct. 

I checked gogs log:
```
2017/04/26 05:14:36 [D] Session ID: 19b21f442d3a45bf
2017/04/26 05:14:36 [D] CSRF Token: sJfQIexgIBV0OwkpCZ0UuPGHR_w6MTQ5MzE3NjU5OTExMTkzMjY1MQ==
2017/04/26 05:14:36 [T] Dialing LDAP with security protocol (0) without verifying: false
2017/04/26 05:14:36 [T] LDAP will use BindDN.
2017/04/26 05:14:36 [T] Search for LDAP user: gemsol\am.handa
2017/04/26 05:14:36 [D] Failed to bind as BindDN[CN=LDAP Admin,OU=ADMN-USRS,DC=gemsol,DC=in]: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903C8, comment: AcceptSecurityContext error, data 52e, v2580
2017/04/26 05:14:36 [W] Failed to login 'gemsol\am.singh' via 'ldap-gogs': user does not exist [uid: 0, name: gemsol\am.am.singh]
2017/04/26 05:14:36 [D] Template: user/auth/signin
[Macaron] 2017-04-26 05:14:36: Completed /user/login 200 OK in 17.397277ms
```

I am not sure what I missed. Also, do I need to specify `Authentication Login Name` for each user?
Isn't there any way to sync data between my ldap server to gogs?

**Comment by ramoneeza** [comment]
I have same problems agains LDAP ACTIVE DIRECTORY.

**Comment by ramoneeza** [comment]
I can solve this USING IPv4 ADDRESS instead HOST NAME.

But I have this strange Trace:

2017/05/11 10:12:25 [TRACE] Search for LDAP user: pi
2017/05/11 10:12:25 [TRACE] Bound as BindDN: CN=Administrador,CN=Users,DC=eeza,xxxx
2017/05/11 10:12:25 [TRACE] Searching for DN using filter '(&(objectClass=person)(sAMAccountName**=pi**))' and base 'CN=Users,DC=eeza,DC=xxxx

Looking for user PI all time... But I have not any PI user.
(It's a GOGs instalation as DOCKER container)

**Comment by Unknwon** [comment]
@ramoneeza "pi" is whatever your user tries to login with.

@prashantprabhakar I think the real error is `Failed to bind as BindDN`, which mean username/password probably wrong.
