### ISSUE TITLE
manage a gogs installation on docker

### ISSUE THREAD

**Issue by cybernet** [gogits/gogs#4458]
i'm new to docker, also new to gogs
however, i followed this tutorial https://github.com/gogits/gogs/blob/master/docker/README.md
and managed to install it with data volume container

all worked perfectly fine until i reboot the host server, i started the container, but without luck i couldn't make gogs to work

```
[docker@dkr root]$ docker exec -it gogs0 ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/s6-svscan /app/gogs/docker/s6/
   19 root       0:00 s6-supervise openssh
   20 root       0:00 s6-supervise crond
   21 root       0:03 s6-supervise gogs
   22 root       0:00 s6-supervise syslogd
   23 root       0:00 /usr/sbin/sshd -D -f /app/gogs/docker/sshd_config
   24 root       0:00 /sbin/syslogd -nS -O-
10947 git        0:00 /app/gogs/gogs web
10959 root       0:00 ps aux
```
```
2e237494c25a        gogs/gogs           "/app/gogs/docker/..."   2 hours ago         Up 2 hours               0.0.0.0:10022->22/tcp, 0.0.0.0:10080->3000/tcp   gogs0
```
when i try to connect to **host:10080**, i get connection refused 

any idea ?
how can i restart the service ( without stopping the container )
were are the logs ?

**Comment by cardonator** [comment]
`docker ps` will tell you what containers are running and what ports they are forwarding.

**Comment by cybernet** [comment]
have you spotted my last line ?

**```
2e237494c25a        gogs/gogs           "/app/gogs/docker/..."   2 hours ago         Up 2 hours               0.0.0.0:10022->22/tcp, 0.0.0.0:10080->3000/tcp   gogs0
```**

also, i just realized that i cannot connect from outside
from host if i $curl it works
also, iptables are flushed ... i don't know what to do ...

**Comment by cardonator** [comment]
Sorry I was clearly blind when I read your post...

The behavior you are discussing points directly to a firewall issue. That issue could be on the host machine or elsewhere on the network. Where is your host machine? Is it on your local network? On a VM on the internet?

**Comment by cybernet** [comment]
is a VPS from vultr ( i don't know how much it matters ) but anyway

before updating the server with newer kernel and rebooted, i couldn't connect to any container ...
like i said. iptables are flushed, no ufw or firewalld installed ...

don't know what do do 😕

**Comment by cybernet** [comment]
the host is CentOS7

**Comment by cardonator** [comment]
Can you post the output of the following commands:

`docker version`

`docker info`

`netstat -tulpn`

**Comment by cybernet** [comment]
```
[root@dkr ~]# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@dkr ~]# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.6 MiB
Name: dkr.xdns.ro
ID: XNIY:OIO6:KJYE:J56E:PQIA:JI7N:PHKW:ZTOF:GT37:XSWT:TWKH:HCJE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
[root@dkr ~]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State                                                                                               PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN                                                                                              386/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN                                                                                              575/master
tcp6       0      0 :::8080                 :::*                    LISTEN                                                                                              12373/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN                                                                                              386/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN                                                                                              575/master
tcp6       0      0 :::10080                :::*                    LISTEN                                                                                              9203/docker-proxy
tcp6       0      0 :::10022                :::*                    LISTEN                                                                                              9213/docker-proxy
udp        0      0 0.0.0.0:53979           0.0.0.0:*                                                                                                                   931/dhclient
udp        0      0 127.0.0.1:323           0.0.0.0:*                                                                                                                   393/chronyd
udp        0      0 0.0.0.0:68              0.0.0.0:*                                                                                                                   931/dhclient
udp6       0      0 ::1:323                 :::*                                                                                                                        393/chronyd
udp6       0      0 :::22193                :::*                                                                                                                        931/dhclient

```

**Comment by Sfinx** [comment]
pulled latest gogs docker image, started. No browser connection to the 10080 which is definitely present at netstat. When trying manually got:

```
telnet some.server.com 10080
Trying xxx.xxx.xxx.xx...
Connected to some.server.com.
Escape character is '^]'.
GET /
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
```

Gog is just throwing the code 400. How to debug further ?

**Comment by cardonator** [comment]
`docker logs` should tell you what is going on in theory. There is also a log file in the container.

Sorry, I totally spaced out this issue...

@cybernet it seems like part of the problem might be that the default docker binding is connecting to the IPv6 addresses and that the IPv4 port forwarding is not working. There is a way to force docker to bind to the IPv4 address... let me look it up in a bit.

**Comment by Sfinx** [comment]
The logs should be printed to stdout as the container launched directly from the console:

```
docker run --rm --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```

But nothing is outputing to the console. I've checked the network by exiting from the container and launching the netcat app by 'nc -l 10080' - network is ok. Can you tell why (or when) the gogs throwing 400 response ?

**Comment by Sfinx** [comment]
So I'm seeing strange Chrome/FF behaviour - the http://some.server.com:10080 URL changes to https with SSL error just after trying to access the gogs.

**Comment by Sfinx** [comment]
And according to pure telnet test - it is definitely binding to IPv4 and you can get the response (400)

**Comment by Sfinx** [comment]
Got the valid response and some gogs log output with the following command:

```
wget some.server.com:10080 -O-
```

Seems like gogs is just screwed by some modern browser header...

**Comment by Sfinx** [comment]
Checked with konqueror - all is working (got the install page) ! So the issue is related to modern browsers.

**Comment by cardonator** [comment]
@Sfinx your issue is likely HSTS key pinning which Chrome added some time ago. You can remove sites from the key pin by following the instructions on this page. https://linux-audit.com/delete-a-hsts-key-pin-in-chrome/

**Comment by Sfinx** [comment]
@cardonator 

1. as I was told - such behavior is 100% reproduced as in chrome as in FF
2. I've deleted the domain from HSTS without any luck
3. I do not think that gogs docker web endpoint named http://some.host:10080 is using SSL

**Comment by Sfinx** [comment]
@cardonator You was right - is was HSTS chrome feature. It is appeared that all subsequent domains must be deleted from HSTS database - not only some.server.com but the server.com too. This is why it was not worked first time. Thanks !

**Comment by Unknwon** [comment]
Thanks @cardonator for all the help! :smile:
