### ISSUE TITLE
No User created

### ISSUE THREAD

**Issue by FlorianTaut** [gogits/gogs#4459]
- Gogs version (or commit ref): 11.0.4
- Git version: 2.1.4
- Operating system: Raspian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
Not information which could help with this issue
## Description

Hi everybody,

i installed my Gogs-Instance yesterday.
When i try to Login as the adminuser im recieving a username or password wrong error.

When i access the Mysql database and do a
`SELECT * FROM user;`

I recieve an empty result.

Probably a Connectionproblem caused that no user was created?
How can i repeat the "First-Start-Setup"

Thank you

**Comment by razzintown** [comment]
This also happened to me. Initially I was stuck because I turned self-registration off, but after starting over completely with self-registration on, I was able to create a user by registration.

**Comment by Unknwon** [comment]
Change [this value](https://github.com/gogits/gogs/blob/master/conf/app.ini#L180) to `false` and create a user at install page.
