### ISSUE TITLE
Password visible in plain text when mirroring a repo over http(s)

### ISSUE THREAD

**Issue by paradoxbound** [gogits/gogs#4461]
- Gogs version (or commit ref): 0.11.4
- Git version: 
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Although the password field is obscured when typing into text field once the migration is run the password is visible in plain text to anyone who has admin rights on a repository by looking at the url.

**Comment by Unknwon** [comment]
That's correct, any suggestion that non-plain text credentials can work with Git clone?
