### ISSUE TITLE
sort most "recent" issue is only available for timestamp of opened issues (creation)

### ISSUE THREAD

**Issue by pedro-nonfree** [gogits/gogs#4462]
- Gogs version (or commit ref): 0.10.18.0313
- Git version: 2.1.4
- Operating system: debian jessie stable
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
  - [x] offline
- Log gist (usually found in `log/gogs.log`):

## Description

At the moment, in the issue tracker **Sort by newest** is the same as **Sort by Recently Updated** updated.
The difference should be:
- **Sort by Newest** -> sort by timestamp of creation/open of issue
- **Sort by Recently Updated** -> sort by timestamp of new comment/updated comment/closed/reoponed/etc (priority: new comment)

I think this is still not implemented. In github after timestamp of "opened", is followed by a timestamp of updated, this updated timestamp is missing

**Comment by Unknwon** [comment]
It turns out the issue's `updated_unix` is not updated for new comments. Patch has been pushed to `master`, you can test locally or on https://try.gogs.io.
