### ISSUE TITLE
500 on wiki page on mirrored repo

### ISSUE THREAD

**Issue by boskiv** [gogits/gogs#4464]
I have mirror repo from our gitlab instance. All perfect, speed is awesome! Great job!
But when I click on Wiki link I've got 500 error
```
[git-module] /data/git/gogs-repositories/exness/backend.wiki.git: git show-ref --verify refs/heads/master
[Macaron] 2017-04-27 08:54:03: Completed GET /Exness/backend/wiki 500 Internal Server Error in 22.691511ms
```
I've tried to turn off/on wiki in project settings but no success. How I can enable it on mirrored repo ?

**Comment by Unknwon** [comment]
Hi, you need upgrade your Gogs and erase wiki data. Caused by a fixed bug.

**Comment by mckaygerhard** [comment]
still reproducible at https://try.gogs.io/mckaygerhard/tested-migrating-wiki-bug/wiki
