### ISSUE TITLE
Snap package issue

### ISSUE THREAD

**Issue by beruic** [gogits/gogs#4465]
- Gogs version (or commit ref): 0.9.99.0915 (Snap installed with `sudo snap install gogs`)
- Git version: N/A
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description
This is probably a packaging error.
The package in quest is the snap package at https://uappexplorer.com/app/gogs.vtuson.
I have tried to find the packager Victor Tuson Palau to report this directly, but I am unable to, and I therefore hope that he is affiliated with you.

The issue is that when trying to upload an avatar to an organization or a user, an error message tells like `UploadAvatar: Create: open /snap/gogs/1/bin/data/avatars/1: no such file or directory` appears.

**Comment by Unknwon** [comment]
Hi, thanks for the feedback!

Unfortunately, I don't know him/her at all, thus I couldn't help in this case... Looks like the package just needs a new version of Gogs with related bugs fixed.
