### ISSUE TITLE
Wrong date on old repositories after upgrade

### ISSUE THREAD

**Issue by ofrzeta** [gogits/gogs#4467]
- Gogs version (or commit ref): 0.11.4.0405
- Git version:  2.7.4
- Operating system: Ubuntu Linux 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

After upgrading from 0.5.13.0212 to 0.11.4.0405 everything is more or less working ok (some problems with pushing repos that we could fix with resync hooks) but there's a wrong date shown on old repos. On a user's repository overview page Gogs claims that it was created 48 years ago (i.e. 1.1.1970). When clicked on the changeset it shows the correct date. The same error occurs on the "/explore/repos" page. When I dump the "Update" field in the template it indeed shows "1970-01-01 01:00:00 +0100 CET". However in the database it is correct: "2015-03-30 18:05:09". 

My xorm.log shows some warnings:
```
....
2017/04/25 16:58:14 [xorm] [warn]  2017/04/25 16:58:14.346673 Table user has column created but struct has not related field
2017/04/25 16:58:14 [xorm] [warn]  2017/04/25 16:58:14.346678 Table user has column updated but struct has not related field
2017/04/25 16:58:14 [xorm] [warn]  2017/04/25 16:58:14.346687 Table user has column num_followings but struct has not related field
2017/04/25 16:58:14 [xorm] [warn]  2017/04/25 16:58:14.346704 Table webhook has column created but struct has not related field
2017/04/25 16:58:14 [xorm] [warn]  2017/04/25 16:58:14.346710 Table webhook has column updated but struct has not related field
2017/04/25 17:20:17 [xorm] [warn]  2017/04/25 17:20:17.367106 table access's column id is not valid or cannot set
2017/04/25 17:20:17 [xorm] [warn]  2017/04/25 17:20:17.367138 table access's column user_id is not valid or cannot set
2017/04/25 17:20:17 [xorm] [warn]  2017/04/25 17:20:17.367144 table access's column repo_id is not valid or cannot set
2017/04/25 17:20:17 [xorm] [warn]  2017/04/25 17:20:17.367151 table access's column mode is not valid or cannot set
2017/04/26 10:20:31 [xorm] [warn]  2017/04/26 10:20:31.765149 table access's column id is not valid or cannot set
```

**Comment by Unknwon** [comment]
Hi, I think you did some hacks while upgrading from such old version. Some an migration (generate `update_unix` from `update` and others) are missing during your upgrade.

Please go forum and post all steps you done to upgrade.

**Comment by ofrzeta** [comment]
I didn't. Actually I did nothing because I didn't know what to do for the upgrade and figured everything (like migrations etc) would run automatically.
