### ISSUE TITLE
Feature request: using gogs in addition to gitolite

### ISSUE THREAD

**Issue by tessus** [gogits/gogs#4471]
I would like to use gitolite and gogs in parallel with the same repositories. gogs as the nice looking, feature rich UI via web, and my current gitolite setup via ssh.

Currently you can only migrate a gitolite setup to gogs, but there's no way to keep the gitoltite setup intact, so that you can use both in parallel.

**Comment by dalu** [comment]
check #96

**Comment by tessus** [comment]
@dalu I don't understand what #96 has to do with my feature request. this is a completely different topic...

**Comment by dalu** [comment]
so mirroring a repo from gogs to gitolite is not what you're trying to do?
what prohibits you from using both then?

**Comment by tessus** [comment]
>so mirroring a repo from gogs to gitolite is not what you're trying to do?

nope, it is not. I've explained it in my first comment: I want to use the same repos and the same credentials with gogs and gitolite at the same time.

>what prohibits you from using both then?

because gogs uses its own authentication mechanism, so when I migrate from gitolite to gogs I will only be able to use gogs authentication, even when I access the repos via ssh.
this means I have 2 sets of repositories in different locations with different authentication mechansims.

**Comment by Fastidious** [comment]
@tessus because of the way `Gogs` works, I don’t think that is possible. I recommend you pick one, and stick with it, at least for the time being.

**Comment by xmik** [comment]
@tessus Gogs has a feature to add a mirror of a remote git repository (probably from gitolite is ok) and Gogs uses a cron job to [update mirrors](https://gogs.io/docs/advanced/configuration_cheat_sheet#cron---update-mirrors-(cron.update_mirrors)). However, I have not used it.

Or you can use ssh authentication to push to Gogs and Gitolite, just set 2 remotes for a git repo. You could push this way:
```
git push gogs master
git push gitolite master
```
or choose 1 to be default remote (`origin`), e.g.
```
git push origin master
git push gitolite master
```
I have never used Gitolite, but sometimes I push changes of one repository to Gogs and Github.

**Comment by Fastidious** [comment]
@xmik it will still not do what @tessus wants: keep only **one** repository, shared by both.

**Comment by xmik** [comment]
Ah ok, now I understand. Thanks @Fastidious for clarification. In this case I think the only way would be to let Gogs and Gitolite share a volume (if Gitolite keeps repositories in the same way as Gogs), but it seems dangerous to let one server change data of another server and also introduces tight coupling while deployment. I would rather avoid this.

**Comment by tessus** [comment]
ok, let's make it more simple. I wan't gogs to be the UI for gitolite.

**Comment by Fastidious** [comment]
@tessus not possible. :-)

**Comment by tessus** [comment]
that's why it is a feature request ;-)

**Comment by Fastidious** [comment]
@tessus, true, completely missed that.

This request is to make `Gogs` repository agnostic, which I am afraid, will strip integrations `Gogs` relies on to interact with its git repositories. All to accommodate a rather obscure tool (`Gitolite`) that tries to do a task similarly to `Gogs`.

I believe you will have to continue using `Gitolite`, and if you like `Gogs` interface, setup a mirror of the `Gitolite`'s repositories on `Gogs`. See @Unknwon [blog entry](https://unknwon.io/setup-your-private-git-hosting-with-gogs/), the "Migrate Repository" portion.

**Comment by tessus** [comment]
@Fastidious hmm, you do know that gitolite was originally used by gitlab and other git hosters (not sure about github) for user handling. calling it obscure is a bit weird.

setting up mirrors is out of the questions as it duplicates the administrative efforts, which is why I asked for this feature request.

gogs is a UI (or at least it started as one), while gitolite is user access control, which is by far more advanced than gogs's access control. I do not understand why gogs decided to implement its own user access when there are so many solutions out there.

anyway, making gogs user access agnostic does not strip integration at all.

as I said, it's a feature request, but I haven't heard anything from the developer yet.

**Comment by Unknwon** [comment]
Replied on the forum, we should continue discuss there. :wink:

**Comment by Unknwon** [comment]
Any... news?

**Comment by tessus** [comment]
I answered in the forum: 

> The pattern seems almost the same, but I might be able to fix this with symlinks as a workaround. The fact that I cannot use gitolite's authorization scheme in gogs makes it a problem. Maybe I can find a workaround for that as well, but I haven't had the time to figure it out yet. 

If you want to, we can close this ticket and use the forum or we can mark the forum ticket as closed and use this ticket to discuss. I think it makes no sense to keep both open. Up to you.

**Comment by Unknwon** [comment]
@tessus thanks for the update!

Yeah, I think it wouldn't be possible to make Gogs accept gitolite's authorization scheme natively in near future or any plan. Just use symlinks for ones you want to expose sounds the best way to me right now.
