### ISSUE TITLE
gogs.io website down

### ISSUE THREAD

**Issue by georgesuba** [gogits/gogs#4472]
- Operating system:  debian 8
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (gogs.io)
  - [x] No
  - [ ] Not relevant

## Description

Hi Guys, I would like to just report that for some reason I cannot access any part of the site gogs.io (not even forums) - its time outing even if I try to connect from various diff countries and different machines.

**Comment by Dreamersoul** [comment]
Same would like to know what happened :/ i was browsing it just this morning

**Comment by georgesuba** [comment]
@Dreamersoul perhaps some fw issue or dns... lets hope folks will fix this.

**Comment by Fastidious** [comment]
No DNS or server issues (server where try.gogs.io is hosted is up).  There has to be related to the new Caddy server release, and proxying not working, or setup properly.

**Comment by georgesuba** [comment]
site appears to work normally again. Thanks all.
