### ISSUE TITLE
重启了电脑之后，启动报错了，sliece bounds out of range，急急急，非常感谢

### ISSUE THREAD

**Issue by fewiki** [gogits/gogs#4473]
![image](https://cloud.githubusercontent.com/assets/13325335/25601626/06574886-2f20-11e7-91d4-f3739c0eb25c.png)

**Comment by Unknwon** [comment]
Hi, your Gogs version is way too old, I'm unable to help you...

**Comment by Unknwon** [comment]
欢迎加入Gogs - 自助 Git 托管服务，群号码：218443817
