### ISSUE TITLE
Unable to run as service

### ISSUE THREAD

**Issue by leinad13** [gogits/gogs#4476]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.10.2
- Operating system: W10 - Microsoft Windows [Version 10.0.14393]
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/05/02 16:16:39 [TRACE] Log Mode: File (Trace)
2017/05/02 16:16:39 [ INFO] Gogs 0.11.4.0405
2017/05/02 16:16:39 [ INFO] Cache Service Enabled
2017/05/02 16:16:39 [ INFO] Session Service Enabled
2017/05/02 16:16:39 [ INFO] Git Version: 2.10.2
2017/05/02 16:16:39 [ INFO] SQLite3 Supported
2017/05/02 16:16:39 [ INFO] Run Mode: Production
2017/05/02 16:16:39 [TRACE] Doing: CheckRepoStats
2017/05/02 16:16:40 [ INFO] Listen: http://127.0.1.1:80
2017/05/02 16:16:40 [FATAL] [...rfave/cli/command.go:193 Run()] Fail to start server: listen tcp 127.0.1.1:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

## Description
Trying to run as a service using nssm - following the guide [here](https://gogs.io/docs/installation/run_as_windows_service).

Get this error when running `nssm.exe start gogs`
 'gogs: Unexpected status SERVICE_PAUSED in response to START control.'

**Comment by kardianos** [comment]
You aren't running nssm under an account with sufficient privileges to bind to port 80 it looks like.

**Comment by leinad13** [comment]
Not really sure what was wrong, but this issue can be closed - I re-ran the config using a newer version of gogs and the windows service method. Didn't bother changing the port from 3000 to 80 this time as I noticed my SYSTEM process was using port 80 - which may have been ws-man.
