### ISSUE TITLE
[log] LEVEL in app.ini does not change overall logging level (but [log.console]/[log.file] LEVEL does work)

### ISSUE THREAD

**Issue by timhurkmans** [gogits/gogs#4478]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.12.2
- Operating system:  Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
``` 
2017/05/03 11:31:07 [TRACE] Log Mode: File (Trace)
2017/05/03 11:31:07 [ INFO] Xelion Git Server 0.11.4.0405
2017/05/03 11:31:07 [ INFO] Cache Service Enabled
2017/05/03 11:31:07 [ INFO] Session Service Enabled
2017/05/03 11:31:07 [ INFO] Git Version: 2.12.2
2017/05/03 11:31:08 [ INFO] SQLite3 Supported
2017/05/03 11:31:08 [ INFO] Builtin Windows Service Supported
2017/05/03 11:31:08 [ INFO] Run Mode: Production
2017/05/03 11:31:08 [TRACE] Doing: CheckRepoStats
2017/05/03 11:31:08 [ INFO] Listen: https://0.0.0.0:8300
```
## Description

**Given** the app.ini configuration:
```
[log]
MODE      = console, file
LEVEL     = Info
```

**When** starting gogs web with that log configuration.
**Then** the file and console logs still print Trace messages.

```
2017/05/03 11:31:07 [TRACE] Log Mode: File (Trace)
...
2017/05/03 11:31:08 [TRACE] Doing: CheckRepoStats
2017/05/03 11:31:08 [ INFO] Listen: https://0.0.0.0:8300
```

### However,

**Given** the app.ini configuration:
```
[log]
MODE      = console, file
LEVEL     = Info

[log.console]
LEVEL     = Info

[log.file]
LEVEL     = Info
```
**When** starting gogs web with that log configuration.
**Then** the file and console logs no longer print Trace messages after startup.
```
2017/05/03 11:31:07 [TRACE] Log Mode: File (Trace)
...
2017/05/03 11:31:08 [ INFO] Listen: https://0.0.0.0:8300
```

This is different from #2798, as it does work for [log.console] and [log.file]

**Comment by Unknwon** [comment]
Hi, the way configuration works is exactly the opposite, subsection overwrites values of parent section.

**Comment by xmik** [comment]
But this way this configuration:
```
[log]
LEVEL     = Info
```
seems to be reluctant, because it changes nothing. If it changes nothing, it should be removed. 

Its [documentation](https://gogs.io/docs/advanced/configuration_cheat_sheet#log-(log)) is misleading: 
> General log level, default is Trace

which I understand as: default log level for any output type.

**Comment by Unknwon** [comment]
@xmik it is the default is the `LEVEL` key is not presented or `empty` in subsections.

**Comment by xmik** [comment]
Ok, thank you @Unknwon for clarifying that. In this case, it may be worth considering whether to add in the documentation, that this field is readonly.

**Comment by Unknwon** [comment]
@xmik it is not read-only, it is default if subsection not specify a value.
