### ISSUE TITLE
Error use /api/v1/repos/migrate if uid = standart gogs user id

### ISSUE THREAD

**Issue by CHERTS** [gogits/gogs#4479]
- Gogs version (or commit ref): 0.11.6.0407
- Git version: 2.1.4
- Operating system: Debian GNU/Linux 8.7 (jessie)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): there are no errors in the log

## Description

I want to run automatic repository migration through the API Gogs:

```
curl -H "Authorization: token MYTOKEN" -H "Accept: application/json" -H "Content-Type:application/json" --data '{"clone_addr": "https://gitlab.xxxx.ru/USERNAME/REPONAME.git", "auth_username": "root", "auth_password": "YYYYY", "uid": 14, "repo_name": "REPONAME", "description": "automatic migration", "private": true}' https://gogs.xxxx.ru/api/v1/repos/migrate
```

responce:

```
{"message":"Given user is not an organization","url":"https://github.com/gogits/go-gogs-client/wiki"}
```

If use user id = 14 - is a standart gogs user (non admin) - migration ends in error
If use org id = 15 - is a standart gogs organisation - migration ends without errors

How to start migration the remote repository for the standart gogs user?

**Comment by xmik** [comment]
Use those standard user's credentials. It worked for me some time ago.

**Comment by CHERTS** [comment]
MYTOKEN is a admin user token, 

What are the standard user credentials to use?

**Comment by CHERTS** [comment]
I fixed this problem this way:
```
--- routers/api/v1/repo/repo.go.orig	2017-05-03 17:42:10.565199900 +0500
+++ routers/api/v1/repo/repo.go	2017-05-03 17:42:24.049548200 +0500
@@ -220,9 +220,6 @@
 				ctx.Error(500, "GetUserByID", err)
 			}
 			return
-		} else if !org.IsOrganization() {
-			ctx.Error(403, "", "Given user is not an organization")
-			return
 		}
 		ctxUser = org
 	}
```

**Comment by ichrispa** [comment]
Hi everyone,

I have the same problem, same point in the code served as a fix. Minute difference though:

```
func Migrate(ctx *context.APIContext, f form.MigrateRepo) {
        ctxUser := ctx.User
        // Not equal means context user is an organization,
        // or is another user/organization if current user is admin.
        if f.Uid != ctxUser.ID {
                org, err := models.GetUserByID(f.Uid)
                if err != nil {
                        if errors.IsUserNotExist(err) {
                                ctx.Error(422, "", err)
                        } else {
                                ctx.Error(500, "GetUserByID", err)
                        }
                        return
                }  else if !org.IsOrganization() && !ctx.User.IsAdmin {
                        ctx.Error(403, "", "Given user is not an organization")
                        return
                }
                ctxUser = org
        }
...
```

I think the check is valid, but should be overwritten for the admin user.

Cheers,

ichrispa

**Comment by CHERTS** [comment]
Hi

In Gitea, this problem is solved as follows:
https://github.com/go-gitea/gitea/blob/master/routers/api/v1/repo/repo.go#L207

**Comment by ichrispa** [comment]
Hi @CHERTS ,

do you know why gitea has moved the conditional out of the 'if f.Uid != ctxUser.ID {...}' block? In all other regards, the gitea solution looks kind of familiar ^^

Best regards,

ichrispa

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

Gitea's solution has a vulnerability that a non-admin user can migrate repository for arbitrary non-organization users.
