### ISSUE TITLE
Feature: Add Repository lang stats like Github

### ISSUE THREAD

**Issue by ftaut** [gogits/gogs#4483]
How about adding an Repository lang stats feature like Github has?

Have 2 Screenshots here to underline what i mean:
![unbenannt1](https://cloud.githubusercontent.com/assets/18403881/25701423/9f19b3a8-30cc-11e7-86e8-533ff8e87387.PNG)
Onclick:
![unbenannt](https://cloud.githubusercontent.com/assets/18403881/25701428/a36d6350-30cc-11e7-8844-7f9c5352db95.PNG)

Cant find similar issues to this one.

**Comment by FlorianTaut** [comment]
Looks like the guys at gogs are in holidays since 2 weeks :laughing:

**Comment by alexanderadam** [comment]
Just to clarify: I'm sure Unknwon added the "dont send pull request" label because [the oldest open pull request](https://github.com/gogits/gogs/pull/2135) handles exactly this. 😉

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogits/gogs/issues/4154.
