### ISSUE TITLE
Gogs docker container should rely on exisisting database (sqlite3)

### ISSUE THREAD

**Issue by Sfinx** [gogits/gogs#4486]
- Gogs version (or commit ref): 

latest docker one

- Operating system: 

Linux

- Database (use `[x]`):

None as this is install issue

- Can you reproduce the bug at https://try.gogs.io:
  Not relevant
## Description

The docker image rely on MySQL DB by default which is not present and not running inside the gogs image. The wise config is to use sqlite3 - this is at least will allow some people to try the gogs...

**Comment by Unknwon** [comment]
Hi, the official image does not assume or "rely" any DB.
