### ISSUE TITLE
Docker git user directory security issue (forced and invalid permission)

### ISSUE THREAD

**Issue by Sfinx** [gogits/gogs#4488]
- Git version:  Latest docker image
- Operating system:  Linux (docker)

The git user home directory is world wide readable which is invalid permission by default unix security policy. Usually the ~/git points to the real host user directory so starting up the gogs docker mangles its permission inevitable. 

```
diff --git a/docker/s6/gogs/setup b/docker/s6/gogs/setup
index 40bd82b..a99e6b7 100755
--- a/docker/s6/gogs/setup
+++ b/docker/s6/gogs/setup
@@ -20,4 +20,4 @@ ln -sf /data/gogs/data ./data
 ln -sf /data/git /home/git
 
 chown -R git:git /data /app/gogs ~git/
-chmod 0755 /data /data/gogs ~git/
+chmod 0750 /data /data/gogs ~git/
```

So this script has two additional bugs:

- the "git" user is hardcoded here
- the "git" user forced to the "git" group which can be non-existent or not valid for it

**Comment by Unknwon** [comment]
Thanks your feedback!

You can propose a PR to dockerfile if you know what can be improved.
