### ISSUE TITLE
Docker gogs do not respect the case when creating company and repositories directory names

### ISSUE THREAD

**Issue by Sfinx** [gogits/gogs#4489]
- Gogs version (or commit ref): latest docker

Steps to reproduce:

- create company with uppercase
- create repository inside the company with uppercase names

Try to fetch them using the gogs UI ssh://git@.... URL. The problem is that gogs shows correct uppercase URL's in Web UI but creates **lowercase** company and respository directory names.
 So there is a bug in URL creating - it definitely should append /mount_point/gogs/git/gogs-repositories to the ssh://git@ URL server path.

**Comment by Unknwon** [comment]
Creating everything in lowercase is the expected and purposed behavior.
