### ISSUE TITLE
Read only collaborator can push into private repo

### ISSUE THREAD

**Issue by slothbag** [gogits/gogs#4491]
Gogs Version: 0.11.4.0405
Linux 64 bit
PostgreSQL DB

I set a new user as a `read only` collaborator on private repo but he was able to push a new branch into the repo.

**Comment by geoherna** [comment]
I get similar issue, if I change a collaborator's permissions to read, it changes back to write.

**Comment by Unknwon** [comment]
I think this is caused by fail to change collaborator's permission and has been resolved.
