### ISSUE TITLE
Feature: set global mirror interval

### ISSUE THREAD

**Issue by mkeedlinger** [gogits/gogs#4493]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Have an option in the config to set a global default for the mirror refresh interval.

Found another request for the same thing, just never happened.
https://discuss.gogs.io/t/is-it-possible-to-redefine-the-global-mirror-interval/540

Thanks for this amazing project :)

**Comment by cez81** [comment]
Fixed in https://github.com/gogits/gogs/pull/3409
```
[mirror]
; Default interval in hours between each check
DEFAULT_INTERVAL = 24
```
