### ISSUE TITLE
Error when adding ssh keys

### ISSUE THREAD

**Issue by kstenerud** [gogits/gogs#4494]
- Gogs version (or commit ref): 0.11.6.0407
- Git version: 2.11.1
- Operating system: gogs Docker image from https://github.com/gogits/gogs/tree/master/docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): No logfile in /var/git or /var/gogs

## Description

Similar issue to https://github.com/gogits/gogs/issues/3480
I try to add an ssh key, but it complains: `Sorry, we're not able to verify your SSH key: extractTypeFromBase64Key: invalid key format: not enough length 813827234`

I've tried with many different keys, and every combination of having trailing whitespace/newlines or not, having `-----BEGIN RSA PRIVATE KEY-----` or not.

**Comment by cez81** [comment]
The key should be your public key, not the private one. So anything with `BEGIN RSA PRIVATE KEY` is incorrect.

It should look like this, one long continuous line:
```
$ cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSUGPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cda3Pbv7kOdJ/MTyBlWXFCR+HAo3FXRitBqxiX1nKhXpHAZsMciLq8V6RjsNAQwdsdMFvSlVK/7XAt3FaoJoAsncM1Q9x5+3V0Ww68/eIFmb1zuUFljQJKprrX88XypNDvjYNby6vw/Pb0rwert/EnmZ+AW4OZPnTPI89ZPmVMLuayrD2cE86Z/il8b+gw3r3+1nKatmIkjn2so1d01QraTlMqVSsbxNrRFi9wrf+M7Q== schacon@mylaptop.local
```

Ref: https://git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key

**Comment by Apokalyptica79** [comment]
Thanks @cez81, your response works for me :)

**Comment by webFrontend2021** [comment]
thanks buddy
