### ISSUE TITLE
Gogs is querying for PI user continuosly

### ISSUE THREAD

**Issue by ramoneeza** [gogits/gogs#4496]
2017/05/11 10:12:25 [TRACE] Search for LDAP user: pi
2017/05/11 10:12:25 [TRACE] Bound as BindDN: CN=Administrador,CN=Users,DC=eeza,xxxx
2017/05/11 10:12:25 [TRACE] Searching for DN using filter '(&(objectClass=person)(sAMAccountName=pi))' and base 'CN=Users,DC=eeza,xxxx

But there is not suck user...

Gogs installed as Docker Container.

**Comment by Unknwon** [comment]
Because it could be someone keeps trying to hack on your system with username "pi".
