### ISSUE TITLE
On upgrade logs and data are chown'ed to gogs not APP_USER

### ISSUE THREAD

**Issue by krsch** [gogits/gogs#4502]
- Gogs version (or commit ref): gogs-0.11.4-1491606599.6ea9642.centos6.x86_64
- Git version: 1.7.11.3
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
  No logs are produced
## Description
When installing, reinstalling or upgrading gogs on Centos6 `/var/log/gogs/` directory is `chown`ed to `gogs`, while my `APP_USER=git`. Therefore gogs cannot write to the log files and exits immediately. The same happens to `/opt/gogs/data/`.

The reason for this is the following lines of postinstall script:
```sh
chown -R ${APP_USER}.${APP_GROUP} ${APP_HOME}
chown -R ${APP_USER}.${APP_GROUP} ${LOGS}
```

Thees lines appear before postinst hook, and so `APP_USER="gogs"`. I could not find them in the repo and i think they might be generated by `packager`. One possible solution would be to add `chown -R ${APP_USER}.${APP_GROUP} ${APP_HOME}/data ${LOGS}` to `packager/hooks/postinst`. However there might exist a better solution through packager which I have no experience of.

**Comment by Unknwon** [comment]
Thanks for the feedback!

However, `packager` is from a third-party provider which this repository has zero control of what scripts it runs.
