### ISSUE TITLE
CI build needs needs a sha1 hash  in pull request event

### ISSUE THREAD

**Issue by d4ddi0** [gogits/gogs#4504]
## head sha1 is needed to fetch pull request based on a webhook
If a pull request is made from a forked repository the branch named in the pull request does not
exist in the target repository. In order to checkout and build the pull request a sha1 ref is needed.
- a commit hash is desirable anyway because the branch can change after teh pull request has been issued. A sha1 is a stable reference to the pull request when it is made, even if it later changes. 

- Gogs version (or commit ref): 0.11RC
- Git version: 2.11
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gogs.io:
  - [x ] Not relevant

## Description
My team uses forked repositories for development, and pull requests into a main repository.
The sha1 value is the only unique feature of a pull request from a fork. (gogs does not create a temporary branch for the PR)
Without the sha1 hash (or some equivalent) my CI server, buildbot cannot fetch the pull request in the target repository prior to merging it.
The github v3 pull request includes a "head" and "base" element, which contain a "sha" of the last commit in the pull request branch.
I don't know if it is helpful, but the gitea pull_request has this feature copied from github.
...

**Comment by Unknwon** [comment]
Hi, I'm not very clear about what you're trying to say.

What does it look right now? And what do you expect instead?
