### ISSUE TITLE
Avatar image link (in quick search for username field) does not contain port number

### ISSUE THREAD

**Issue by sadeqn** [gogits/gogs#4506]
Gogs Version: 0.11.6.0407
- Operating system: Debian 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No 
  - [ ] Not relevant

## Description
I had setup a gogs on my server. It is running on port  3000 . When I begin type a user name in input box (for example for to add user to a repository) if user use internal avatar, the link is not correct.  For example img source must be https://example.test:3000/avatars/123/ but it is https://example.test/avatars/123 and it make problem and do not show the avatar.

...

**Comment by Unknwon** [comment]
I think it is because you didn't set **Application URL** correctly on install page.
