### ISSUE TITLE
SSH Key import fails on CentOS/RHEL 5

### ISSUE THREAD

**Issue by v00d00** [gogits/gogs#4507]
- Gogs version (or commit ref): 0.14.1
- Git version: 1.7.4.1
- Operating system: CentOS 5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

SSHKeyGenParsePublicKey fails with OpenSSH_4.3, shipped with CentOS 5.

This is because as per the Windows check in the method, OpenSSH 4..3 also does not output the key type, therefore there are only 3 fields returned and the check fails.

Therefore adding any key fails, making SSH useless.
```
[user@host ~]$ ssh -V
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
[user@host ~]$ ssh-keygen -l -f /home/user/id_rsa.pub 
4096 04:87:56:4a:55:c6:97:a3:b7:98:92:96:be:ae:00:43 /home/user/id_rsa.pub
```

**Comment by Gibheer** [comment]
One fix that needs to be done is to move the check of the minimum size in [ssh_key.go#L318|https://github.com/gogits/gogs/blob/master/models/ssh_key.go#L318] up some lines to avoid calling ssh-keygen at all. That way you could just disable that check and it would work.
I will send a pull request later today for that.

In the function SSHKeyGenParsePublicKey already is a check for less than 4 fields, but I would like that to stay as an error, else we may run into a problem when something in the output changes without anyone noticing. Also [CentOS 5 is EOL|https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d] so I don't know if gogs wants to support that or not.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4519, please help test on `master` branch.

**Comment by v00d00** [comment]
We can avoid the issue if MinimumKeySizeCheck is not enbaled. It will still fail is MinimumKeySizeCheck is enabled.

**Comment by Unknwon** [comment]
@v00d00 so... what is your suggestion?

**Comment by v00d00** [comment]
It looks like the type was added in [this commit](https://github.com/openssh/openssh-portable/commit/b68fb4ad2118483c84c02633029e86fc20f15bf1) which was on 12 Jun 2008.

The next release of openssh after that date is [5.1](https://www.openssh.com/txt/release-5.1), so perhaps a version check to see if its there, and if not do as Windows and/or skip? Or disable that option in the UI? not sure how it works on windows.

The windows codepath just returns a zero size, which will also always fail as far as I can tell?

**Comment by Unknwon** [comment]
Hmm, I'm unclear about what you're trying to say. What does "its", "that", "it", "codepath" refer to?

**Comment by v00d00** [comment]
Apologies I worded that comment badly.

It looks like the code to output the key type was added in this OpenSSH commit which was on 12 Jun 2008.

The next release of OpenSSH after the commit date is v5.1, so perhaps introduce a version check to see if a supported OpenSSH version is present, and if not do as on Windows and/or skip the check?

The return values of the function if windows mean that the key size check will always fail as far as I can tell, as keysize returned would be 0.

**Comment by Unknwon** [comment]
No worries!

>The next release of OpenSSH after the commit date is v5.1, so perhaps introduce a version check to see if a supported OpenSSH version is present, and if not do as on Windows and/or skip the check?

Sounds good to me, and reference could point me to about how to properly get/check a version of the OpenSSH?

**Comment by v00d00** [comment]
I would just run `ssh -V`

Examples:

Ubuntu 17.04:
`OpenSSH_7.4p1 Ubuntu-10, OpenSSL 1.0.2g  1 Mar 2016`
CentOS 6:
`OpenSSH_5.3p1, OpenSSL 1.0.1e-fips  11 Feb 2013`
CentOS 5:
`OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008`

**Comment by Unknwon** [comment]
OK... so skip version **lower than** 5.1?

**Comment by v00d00** [comment]
Yes.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by v00d00** [comment]
Are binary builds of develop available anywhere?

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/releases/tag/v0.11.19

**Comment by v00d00** [comment]
Works great! Thanks!
