### ISSUE TITLE
Display failed logins in log file

### ISSUE THREAD

**Issue by tcpluess** [gogits/gogs#4511]
It would be handy if failed logins would be reported in the Gogs log file. With the aid of this information, brute-force attacks on a public server could be prevented. For example, write down the date/time and the IP address from which the login failed.

(Using this information, one can use fail2ban to ban IPs which repeatedly try to log in with wring credentials.)

**Comment by AdamEttenberger** [comment]
There's a pull request in the works for this :
#3357

**Comment by Unknwon** [comment]
Hi, based your description, I think this is duplicated to https://github.com/gogits/gogs/issues/2384.
