### ISSUE TITLE
Cannot change permissions of collaborators

### ISSUE THREAD

**Issue by schtiefel** [gogits/gogs#4512]
- Gogs version (or commit ref): 0.11.10.0517 (Testserver)
- Git version: Browser interface
- Operating system: Windows + Chrome
- Database (use `[x]`): (Testserver)
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io/schtiefel/test/settings/collaboration
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): (Testserver)

## Description

Hi, I'm not able to change the access rights of collaborators of a repository.
By default they have 'Write' access.
When changing this via the drop-down-option the new setting is not automatically saved (and there is no separate 'Save' button).

Issue appears for private and public repositories.

**Comment by timwebster9** [comment]
same here (using same version - latest docker image)

**Comment by xjboss** [comment]
same here (using same version)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

**Comment by schtiefel** [comment]
Works perfect - Thx!
