### ISSUE TITLE
Protected branch can be deleted from the web after merge request

### ISSUE THREAD

**Issue by mgxian** [gogits/gogs#4514]
- Gogs version (or commit ref): 0.11.6.0407
- Git version: 2.11.1
- Operating system:  docker on Centos6 (use docker image gogs/gogs:0.11.4)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I protect master branch, preproduction branch and production branch. but when I agree a pull request(merge master branch to preproduction branch), and then there has a delete button, when I click it, my master branch was deleted. I think this is a bug.

**Comment by jakejanson** [comment]
Can confirm this is still a bug in version 0.11.23.0625 with MySQL database. I would make a pull request to fix this, but unfortunately I don't know Go. (If anyone could tell me roughly what and where I have to modify, I could do it.)

**Comment by bayangan1991** [comment]
@jakejanson if you tell me what binary you need I can compile it for you.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4803, please help test on `develop` branch or https://try.gogs.io.
