### ISSUE TITLE
Being able to filter in pull requests using a small filter input field

### ISSUE THREAD

**Issue by peterurk** [gogits/gogs#4515]
- Gogs version (or commit ref): 
Version: 0.11.10.0517

- Git version: 
git version 1.7.1

- Operating system: 
Centos 6.4

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

We've got a bunch of pull request. It would be great if we could somehow filter these pull requests by title or description. A small filter input such as with the branch dropdown would help us a big deal.

**Comment by Unknwon** [comment]
I think this thread can be part of https://github.com/gogits/gogs/issues/4239, closing.
