### ISSUE TITLE
Web Interface doesn't update with successful PUSH over HTTP (Run as Windows Service)

### ISSUE THREAD

**Issue by derrek-miller** [gogits/gogs#4516]
- Gogs version (or commit ref): 
**0.11.4.0405**
- Git version: 
**2.13**
- Operating system: 
**Windows Server 2012 R2**
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [**X**] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [**X**] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
**Nothing in log/gogs.log but there is an entry in the post-recieve.log in the hooks folder

2017/05/18 08:42:02 [ERROR] [...its/gogs/cmd/hook.go:215 runHookPostReceive()] PushUpdate: GetRepositoryByName: repository does not exist [id: 0, user_id: 1, name: Test-1]**

Here are the steps:
1. Create a blank repository with the Gogs Web Interface
2. Push local repository to Gogs Remote server using HTTP
3. Push Succeeds, but updates are not shown on the Web Interface.
- Subsequent Clones from remote do show the updates

Appears that the webhook error above is related to not updating the web interface, however, I can't see what is wrong in my config that would cause that. 

Server custom config

[server]
APP_NAME = COMPANY-NAME
RUN_USER = COMPUTERNAME$
RUN_MODE = prod

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = root
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = repositories

[server]
DOMAIN 	 	 = gogs.mydomain.com
PROTOCOL  	 = http
HTTP_PORT 	 = 3000
ROOT_URL         = http://gogs.mydomain.com:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[session]
PROVIDER = file

[log]
MODE      = file,console
LEVEL     = Info
ROOT_PATH = C:/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = Arz9oIOE4RJioWC

**Comment by Unknwon** [comment]
Hi, you think you need to use absolute path for your SQLite3 file path (`PATH = data/gogs.db`). Then restart Gogs.
