### ISSUE TITLE
go get url without suffix fail for hidden git (requre signin view) 

### ISSUE THREAD

**Issue by chinglinwen** [gogits/gogs#4523]
- Gogs version (or commit ref): 
- Git version:  Gogs version 0.11.4.0405
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (this issue require sign in view config )
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

[gogs-config.tar.gz](https://github.com/gogits/gogs/files/1017637/gogs-config.tar.gz)
[gogs-log.tar.gz](https://github.com/gogits/gogs/files/1017638/gogs-log.tar.gz)

## Description

**go get for hidden git (requre signin view) should work without suffix too ( since it's already work with .git suffix )**

```
config gogs REQUIRE_SIGNIN_VIEW to true

git config --global url."git@git.example.com:".insteadOf "http://git.example.com/"

$ go get --insecure git.example.com/wenzhenglin/libexample.git
        //ok
$ go get --insecure git.example.com/wenzhenglin/libexample
package git.example.com/wenzhenglin/libexample: unrecognized import path "git.example.com/wenzhenglin/libexample" (parse http://git.example.com/wenzhenglin/libexample?go-get=1: no go-import meta tags ())

go get --insecure git.example.com/wenzhenglin/libexample
	//cancel require sign in view config and restart, it is go getable
        //the repo is also set to private
```
> https is not testing at this time

related issue:  https://github.com/gogits/gogs/issues/2825
...

**Comment by chinglinwen** [comment]
Currently, I use following config for nginx can solve the problem.

```
location ~ "(/[^/]+/[^/]+)(/.*)?" {
  if ($arg_go-get = "1") {
    return 200 '<html>\n<head>\n<meta name="go-import" content="$http_host$1 git git+ssh://git@$http_host$1"/>\n</head>\n<body>\ngo get $http_host$1\n</body>\n</html>';
  }
  proxy_pass http://localhost:3000;
}
location / {
  proxy_pass http://localhost:3000;
}
```
As provided here: 
https://github.com/gogits/gogs/issues/2825#issuecomment-291999991

**Comment by Unknwon** [comment]
Hi, I think this issue is co-fixed with https://github.com/gogits/gogs/issues/1878.

**Comment by chinglinwen** [comment]
Good to know it, I may try to verify it for the next release.

By the way, the above nginx need some fix.

When go get some repo, it says the following, maybe caused by remote url different:
```
$ go get -u -v ./...
Fetching https://hdgit.com/spider/spider/api/cmd?go-get=1
Parsing meta tags from https://hdgit.com/spider/spider/api/cmd?go-get=1 (status code 200)
get "hdgit.com/spider/spider/api/cmd": found meta tag main.metaImport{Prefix:"hdgit.com/spider/spider", VCS:"git", RepoRoot:"git+ssh://git@hdgit.com/spider/spider"} at https://hdgit.com/spider/spider/api/cmd?go-get=1
get "hdgit.com/spider/spider/api/cmd": verifying non-authoritative meta tag
Fetching https://hdgit.com/spider/spider?go-get=1
Parsing meta tags from https://hdgit.com/spider/spider?go-get=1 (status code 200)
package hdgit.com/spider/spider/api/cmd: hdgit.com/spider/spider is a custom import path for git+ssh://git@hdgit.com/spider/spider, but H:\gocode\src\hdgit.com\spider\spider is checked out from ssh://git@hdgit.com/spider/spider.git
```

So I make the following change to nginx config to fix it.

old
`content="$http_host$1 git git+ssh://git@$http_host$1"`

new
`content="$http_host$1 git ssh://git@$http_host$1.git"`

**Comment by chinglinwen** [comment]
Tested for version 0.11.19, it's fixed  : )
