### ISSUE TITLE
add "[Gogs]" prefix to the subject of mail notification, for convenience of mail filter.

### ISSUE THREAD

**Issue by polisan** [gogits/gogs#4524]
## Description
Currently, the subject format of mail notification is 
```
"[%s] %s (#%d)", issue.Repo.Name, issue.Title, issue.Index"
```
and one case is 
```
'[nginx] for test (#805)'. 
```

For the fact that the sender field could be rewritten with the committer's name, or the sender address could be shared with other applications for saving purpose, it is not convenient to create a filter in mailbox for gogs notifications. 

Adding a prefix to the subject is a common practice, like JIRA, confluence, etc. So It would be nice to make the tiny improvement.

```
 func (issue *Issue) MailSubject() string {
-       return fmt.Sprintf("[%s] %s (#%d)", issue.Repo.Name, issue.Title, issue.Index)
+       return fmt.Sprintf("[Gogs][%s] %s (#%d)", issue.Repo.Name, issue.Title, issue.Index)
 }
```

**Comment by Addvilz** [comment]
It would also make Subject line much more congested and harder to scan over for some. Suffix might be better idea then.

**Comment by Fastidious** [comment]
I don’t have an issue with the way it is currently implemented. Notifications from a `gogs` installation always come from the same email address, so a filter can be created based on that.

If the change is accepted, I propose changing `gogs` to whatever short name you give to your install (if that setting [assign short name to an installation] is not currently implemented, then implementing it should be a good idea).

**Comment by polisan** [comment]
> Notifications from a gogs installation always come from the same email address, so a filter can be created based on that.

let me give a concrete example, user could use a particular email sender for notification among different applications, like ```notify@foo.com```, and then rewrite the ```FROM``` field in each application, just like the way Gogs provides,
```
FROM = Gogs<notify@foo.com>
```
However, gogs rewrite the ```FROM``` field again, using the committer's name, like ```Bar<notify@foo.com>```.

Then it is hard for user to create a filter to take gogs notification out from all the notifications, since they are all from the same email address ```notify@foo.com```

I know it would be easier to use dedicated email address for each application, while dozens of headless mail address would be needed.

**Comment by carbontwelve** [comment]
I think making gogs more configurable so people wishing to use this feature can, is no bad thing.

**Comment by Unknwon** [comment]
I agree with a short name :+1:

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch or https://try.gogs.io.

You can config it via https://github.com/gogits/gogs/blob/master/conf/app.ini#L230
