### ISSUE TITLE
SSHKeyGenParsePublicKey: invalid public key line

### ISSUE THREAD

**Issue by icyomik** [gogits/gogs#4526]
嗨，今天在某台机器上添加公钥时提示：
『很抱歉，我们无法验证您输入的 SSH 密钥：SSHKeyGenParsePublicKey: invalid public key line』

然而在另外一台机器上却是正常的，我查看了下「ssh_key.go」代码第217行，发现有这个逻辑：
`if len(fields) < 4 {
	return "", 0, fmt.Errorf("invalid public key line: %s", stdout)
}`

再查了下相关的代码，发现原因出在ssh-keygen的版本上，使用以下同样的命令：
`ssh-keygen -lf id_rsa.pub`
报错的机器返回：2048 09:47:43:4c:14:36:7b:xb:8d:73:13:90:b9:41:4e:d5 id_rsa.pub
正常的机器返回：2048 09:47:43:4c:14:36:7b:xb:8d:73:13:90:b9:41:4e:d5 id_rsa.pub (RSA)

如果可以的话，请把这个提示修改明确一些，告知有可能是版本的原因，谢谢~

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK @Unknwon </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by v00d00** [comment]
Same as #4507?

**Comment by Unknwon** [comment]
Hi, please read issue template.
