### ISSUE TITLE
Error when building image Docker.rpi

### ISSUE THREAD

**Issue by luckcolors** [gogits/gogs#4529]
- Gogs version (or commit ref): develop branch latest
- Git version: 2.7.4
- Operating system: linux armhf docker
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Trying to build the docker file Docker.rpi returns the following error:
```
+ mkdir -p /tmp/go/src/github.com/gogits/
+ ln -s /app/gogs/build /tmp/go/src/github.com/gogits/gogs
+ cd /tmp/go/src/github.com/gogits/gogs
+ git config --global http.https://gopkg.in.followRedirects true
+ make build TAGS=sqlite cert pam
go-bindata -o=pkg/bindata/bindata.go -ignore="\\.DS_Store|README.md|TRANSLATORS" -pkg=bindata conf/...
/bin/sh: go-bindata: not found
make: *** [Makefile:60: pkg/bindata/bindata.go] Error 127
The command '/bin/sh -c ./docker/build-go.sh     && ./docker/build.sh     && ./docker/finalize.sh' returned a non-zero code: 2
```
I unfortunately can't test if the same happens with the other Dockerfile.

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK @Unknwon </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by luckcolors** [comment]
@appIeboy ?

**Comment by Unknwon** [comment]
```sh
go-bindata -o=pkg/bindata/bindata.go -ignore="\\.DS_Store|README.md|TRANSLATORS" -pkg=bindata conf/...
```

This line is not supposed to be called, please try to pull again!

**Comment by luckcolors** [comment]
Deleting the source, re cloning it, and deleteing all untagged images from docker did the trick.

**Comment by HelloEdit** [comment]
Hello,

I have the same issue on my Rpi3
```
[...]
Step 5/12 : COPY . /app/gogs/build
 ---> Using cache
 ---> 53c9a6605c5e
Step 6/12 : WORKDIR /app/gogs/build
 ---> Using cache
 ---> ae5cd40fe534
Step 7/12 : RUN ./docker/build-go.sh     && ./docker/build.sh     && ./docker/finalize.sh
 ---> Running in 102c5262cc21
/bin/sh: ./docker/build-go.sh: not found
The command '/bin/sh -c ./docker/build-go.sh     && ./docker/build.sh     && ./docker/finalize.sh' returned a non-zero code: 127
```

**Comment by Unknwon** [comment]
@HelloEdit no, it's not the same, look at your error message.

**Comment by HelloEdit** [comment]
You seem to be partially right, it is not the same error but it happens during the execution of the three scripts ` /docker/build-go.sh     && ./docker/build.sh     && ./docker/finalize.sh`

Anyway, I have to open a new issue?

**Comment by Unknwon** [comment]
Yes you can file a new issue with formal report with reproduce steps.
