### ISSUE TITLE
Feature request Percent of the repository that's in one language or another

### ISSUE THREAD

**Issue by Riamse** [gogits/gogs#4530]
- Gogs version (or commit ref): 0.10.18.0313
- Git version: 2.13.0
- Operating system: Debian 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
N/A

## Description
It would be cool if the main page for a repository showed the distribution of programming languages at the top (e.g. Go 84.6% CSS 9.8% JavaScript 3.9% Shell 1.4% Other 0.3%) like Github does.
...

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK @Unknwon </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/4483.
