### ISSUE TITLE
Wrong with docker usage!

### ISSUE THREAD

**Issue by chrislee87** [gogits/gogs#4532]
docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs

3000 is the port inside docker
10080 is the port exported.

But when you create a new repo, it has a url with port 3000, which can not be accessed!
How to solve this problem.

I think this is a common issue, and the page below is misleading.
https://github.com/gogits/gogs/tree/master/docker

**Comment by chrislee87** [comment]
You should run `docker run --name=gogs -p 10022:22 -p 10080:10080 -v /var/gogs:/data gogs/gogs`

If you had run `docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs`, open /var/gogs/gogs/conf/app.ini and change the server port to 10080.

**Comment by milewski** [comment]
I didnt understand what is wrong... for me it works totally fine i create the server like this

```
docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```

and access it on `MY_IP:10080 ` as expected..

**Comment by Unknwon** [comment]
>But when you create a new repo, it has a url with port 3000, which can not be accessed!
Because you didn't read README carefully to setup current **Application URL** in install page.
