### ISSUE TITLE
User created with wrong shadow entry

### ISSUE THREAD

**Issue by dev00** [gogits/gogs#4533]
- Gogs version (or commit ref): 0.11.4-1495678224.b17995a.xenial
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`): irrelevant

## Description
When installed from the repository, a user will created with the following line in `/etc/shadow`:
```
gogs:!:17313:0:99999:7:::
```

This will disable the possibility of cloning via ssh! The correct line would be `gogs:*:17313:0:99999:7:::` Please fix this in the installer, otherwise this leads to massive confusion since the errors don't show up in the gogs log.
...

**Comment by Unknwon** [comment]
Hi, please contact directly to admin of packager.io, this repository has absolutely no control of it.
