### ISSUE TITLE
[Q] Is it possible to manage the wiki outside gogs?

### ISSUE THREAD

**Issue by wsw70** [gogits/gogs#4537]
- Gogs version (or commit ref): 0.11.4.0405
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
This is not  a bug report but a question: is it possible to manage a repo wiki outside of gogs? 

Ideally - would it be possible to pull/push it as yet another repo?

**Comment by Unknwon** [comment]
1. Interesting idea, but repository layout for wiki system is different from tool to tool, why can't you just let Gogs host the repository?
2. You can link to a external wiki in your repo settings.
