### ISSUE TITLE
Unable to go-get

### ISSUE THREAD

**Issue by sarandafl** [gogits/gogs#4539]
- Gogs version (or commit ref):  0.11.12.0529
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I have check out issue #277, but couldn't find a way to enable the meta tags.
When I run `go get -u -v git.sarandafl.duckdns.org/sarandafl/gobackmeup ` I get the following verbose output:
```
Fetching https://git.sarandafl.duckdns.org/sarandafl/gobackmeup?go-get=1
Parsing meta tags from https://git.sarandafl.duckdns.org/sarandafl/gobackmeup/src/master/cmd?go-get=1 (status code 200)
package git.sarandafl.duckdns.org/sarandafl/gobackmeup: unrecognized import path "git.sarandafl.duckdns.org/sarandafl/gobackmeup" (parse https://git.sarandafl.duckdns.org/sarandafl/gobackmeup?go-get=1: no go-import meta tags)
```
...

**Comment by Unknwon** [comment]
Have you turned on require sign in view?

**Comment by sarandafl** [comment]
@Unknwon Yes I had it on. Disabled it and now getting the same error:
```
[sarandafl@sflsv007 go]$ go get -u -v git.sarandafl.duckdns.org/sarandafl/gobackmeup
Fetching https://git.sarandafl.duckdns.org/sarandafl/gobackmeup?go-get=1
Parsing meta tags from https://git.sarandafl.duckdns.org/sarandafl/gobackmeup?go-get=1 (status code 200)
package git.sarandafl.duckdns.org/sarandafl/gobackmeup: unrecognized import path "git.sarandafl.duckdns.org/sarandafl/gobackmeup" (parse https://git.sarandafl.duckdns.org/sarandafl/gobackmeup?go-get=1: no go-import meta tags (meta tag sarandafl.duckdns.org/sarandafl/gobackmeup did not match import path git.sarandafl.duckdns.org/sarandafl/gobackmeup))

```

**Comment by duckbrain** [comment]
Off topic, but in the years of using their service, I never noticed that DuckDNS gives you unlimited second-level subdomains under your subdomain. Thanks, I'm excited now.

The error is saying that the meta tag is coming back with `sarandafl.duckdns.org/sarandafl/gobackmeup`, but your path is `git.sarandafl.duckdns.org/sarandafl/gobackmeup`. I'd check the `DOMAIN` or something in your `app.ini`.

**Comment by Unknwon** [comment]
I think @duckbrain has given the answer, check your [config option](https://github.com/gogits/gogs/blob/master/conf/app.ini#L14).

**Comment by sarandafl** [comment]
Just to confirm - this was the issue
Thanks @duckbrain
