### ISSUE TITLE
Issue and Pull Request templates

### ISSUE THREAD

**Issue by hochhaus** [gogits/gogs#4544]
- Gogs version (or commit ref): bf060387af47dbc9f0abb06025c754baad093061
- Git version: git version 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

As a feature request, it would be nice if Gogs allowed for specifying issue and pull request templates in a manner similar to GitHub.

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by Unknwon** [comment]
Hi, it is already supported, same way as GitHub does.

**Comment by hochhaus** [comment]
Thanks. Works perfectly.
