### ISSUE TITLE
problems with copying CRLF files in the browser

### ISSUE THREAD

**Issue by mrexodia** [gogits/gogs#4546]
- Gogs version (or commit ref): 0.11.12.0529
- Git version: ?
- Operating system: Windows 8.1 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

When copying a file with CRLF line endings (https://try.gogs.io/mrexodia/testcopy/src/master/crlf.txt) there will be additional lines inserted when pasting in notepad:

![](https://i.imgur.com/mJ4zqU9.png)

**Comment by Fastidious** [comment]
You need to copy from `raw` ([raw version](https://try.gogs.io/mrexodia/testcopy/raw/master/crlf.txt)), not from the `display` version.

**Comment by mrexodia** [comment]
I don't want to, copying this file from Github works without problems.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/mrexodia/testcopy/src/master/crlf.txt.

**Comment by mrexodia** [comment]
Thanks a lot @Unknwon! Everything is working correctly now.
