### ISSUE TITLE
Wiki and Issue section in different languages

### ISSUE THREAD

**Issue by ShalokShalom** [gogits/gogs#4547]
Hi there ^-^

I like to provide the Wiki and Issues section in different languages, so that the content of it changes with the choosen UI language.

**Comment by Unknwon** [comment]
Hi... I still don't get the idea of "different language" from you description...

**Comment by ShalokShalom** [comment]
There are translations available for the UI. I want that this change also the issues and wiki page, so i can use them as language specific sections.

**Comment by ShalokShalom** [comment]
Is there any news?

**Comment by Unknwon** [comment]
@ShalokShalom so you mean.. when user is viewing in en-US, wiki shows content of `article_en-US.md`?

**Comment by ShalokShalom** [comment]
So, something of that?

**Comment by Unknwon** [comment]
I think it's too much for a Git hosting. Maybe future...

**Comment by ShalokShalom** [comment]
Is it that complicated?

**Comment by Unknwon** [comment]
I recommend you use a professional tool for multi-language document hosting. :grin:

**Comment by ShalokShalom** [comment]
I like to host all dynamic content on one page, for the overview.

**Comment by ShalokShalom** [comment]
@Unknwon I think its possible to host multiple instances of Gogs, one for each language and share the code with all of them. Is that somewhat possible? 

Use one and the same repo for different instances?

**Comment by Unknwon** [comment]
No... that's requiring even more man power and time.
