### ISSUE TITLE
资源库莫名其妙丢失

### ISSUE THREAD

**Issue by kokorodo** [gogits/gogs#4554]
请问一下，为什么通过gogs去迁移github的库的时候， 经常会超时，而且重启系统后，gogs中迁移的资源库的名字还在，在数据库表的 repository 中也存在该记录。但是镜像的仓库却不见了，也就是不在我配置的系统路径的目录里面。

**Comment by Unknwon** [comment]
1. You can make migration timeout longer.
2. Gogs does not delete anything unless you ask for it.

**Comment by kokorodo** [comment]
好的，谢谢，那我试试看，将超时设置得长一点。
