### ISSUE TITLE
 Authentication failed when using Git for Windows

### ISSUE THREAD

**Issue by 9chu** [gogits/gogs#4555]
- Gogs version (or commit ref): 0.11.19.0609 (via docker)
- Git version: 2.11.2
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (repo url: https://try.gogs.io/9chu/WatchDog.git)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): no useful logs

## Description

This question occurs when using Git for Windows (git version 2.12.1.windows.1).
Any push request (via http) results in `Authentication failed`.
However, it's ok to push into the same repo through git under msys2/mingw.

The problem may relevant with the `Git Credential Manager for Windows`.
But it works properly under Gitlab.

**Comment by Unknwon** [comment]
Hi, I'm a bit confused here, what is difference between **Git for Windows** and **git under msys2/mingw**?

**Comment by 9chu** [comment]
Different version of git under Windows. Both have its own runtime.

Git for windows: https://git-for-windows.github.io/
msys2: http://www.msys2.org/, installing the git through msys2 bash `pacman -S msys/git`

**Comment by 9chu** [comment]
It seems the Git for Windows uses the Git-Credential-Manager-for-Windows.
https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by 9chu** [comment]
OK, I found the issue in GCM. After upgraded the Git for Windows, the problem was solved.
So it's not the gogs's bug.
https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/399
