### ISSUE TITLE
Accept other contributors

### ISSUE THREAD

**Issue by rotthedamn** [gogits/gogs#4559]
While I use Gogs, the project looks stalled and not making any progress. In fact, it seems on the verge of dying. There are many people who would like to contribute to Gogs, but they are left out simply because @Unknwon doesn't want to accept their contributions.

Would you please change your mind, and allow more people to contribute? I really don't understand what you are gaining by excluding other people from the project.

**Comment by Unknwon** [comment]
I never said I don't accept contributions. People who claim so just want control the project, not contribute to the project.
