### ISSUE TITLE
pq: could not create unique index "UQE_issue_repo_index"

### ISSUE THREAD

**Issue by 502647092** [gogits/gogs#4566]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.1
- Operating system: CentOs7.3
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

0.9.13.0318 Upgrade To Lastest Version

```
2017/06/19 10:49:05 [FATAL] [...s/routers/install.go:66 GlobalInit()] Fail to initialize ORM engine: sync database struct error: pq: could not create unique index "UQE_issue_repo_index"
```

**Comment by 502647092** [comment]
i delete not unique index and repo_id
gogs can start

**Comment by 502647092** [comment]
@Unknwon please fix this bug thanks

**Comment by Unknwon** [comment]
Hi,

1. This is because `issue` table has two or more records has same `repo_id` and `index`, which was caused by exactly the **old old old** version you were using.
2. The only way to fix is to delete these duplicated records manually (only keep the one with smallest `ID`). Possible SQL to find duplicates:

```sql
SELECT   id,
         repo_id,
         `index`,
         count(*)
FROM     issue
GROUP BY repo_id,
         `index`
HAVING   count(*) > 0
```

**Comment by wuyonghai** [comment]
Gogs version (or commit ref):in 0.11.66.0916 
I met : An error has occurred:newIssue :Error 1062 :Duplicate enty '6-507' for key 'UQE_issue_repo_index'
