### ISSUE TITLE
Quick paste Picture in issue input area

### ISSUE THREAD

**Issue by 502647092** [gogits/gogs#4568]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Like Github input area is can paste picture from clipboard

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1915.
