### ISSUE TITLE
migrate personal project to an organization

### ISSUE THREAD

**Issue by 502647092** [gogits/gogs#4569]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Sometimes i need migrate personal project to an organization
can you add this function

**Comment by FloatingGhost** [comment]
You can just change the owner to the organisation

Repo -> Settings -> Transfer ownership -> Type in name of organisation

**Comment by 502647092** [comment]
@fanningert  Thanks

**Comment by depost** [comment]
When I change the owner of the warehouse to the organization：
Repo -> Settings -> Transfer ownership -> Type in name of organisation
============
An error has occurred : rename repository directory: rename /home/git/gogs-repositories/cyb/xjc_timer.git /home/git/gogs-repositories/uninote/xjc_timer.git: invalid cross-device link

Application Version: 0.11.86.0130
