### ISSUE TITLE
[API] Get issue comments 500 error

### ISSUE THREAD

**Issue by afilippov1985** [gogits/gogs#4574]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.9.2
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/api/v1/repos/afilippov1985/test/issues/1/comments
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

[Macaron] 2017-06-21 11:42:56: Started GET /api/v1/repos/root/support/issues/5/comments for 127.0.0.1
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
E:/go/src/runtime/panic.go:489 (0x42e40d)
E:/go/src/runtime/panic.go:63 (0x42d265)
E:/go/src/runtime/signal_windows.go:161 (0x4421eb)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:320 (0xb8ca0d)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:333 (0xb8cb7a)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:274 (0xb8c36a)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:278 (0xb8c3c6)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:282 (0xb8c472)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/issue.go:159 (0xb4db22)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/comment.go:138 (0xb44b4a)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/comment.go:146 (0xb44c86)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/routers/api/v1/repo/issue_comment.go:36 (0xcec8be)
E:/go/src/runtime/asm_amd64.s:514 (0x4592ff)
E:/go/src/reflect/value.go:434 (0x4c59d6)
E:/go/src/reflect/value.go:302 (0x4c4f7b)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:177 (0x89b116)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:137 (0x89aac1)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8b9189)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x8b909d)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/session/session.go:186 (0x913947)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:79 (0x8b8f18)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x89add9)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x89abc2)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8b9189)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x8b909d)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x8ccf12)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:40 (0x8bc70f)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x89add9)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x89abc2)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8b9189)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x8b909d)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:52 (0x8cc18b)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:40 (0x8bc70f)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x89add9)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x89abc2)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8b9189)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:187 (0x8ce230)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:296 (0x8c6184)
C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x8bdd83)
E:/go/src/net/http/server.go:2568 (0x6e5979)
E:/go/src/net/http/server.go:1825 (0x6e1be9)
E:/go/src/runtime/asm_amd64.s:2197 (0x45bb51)
[Macaron] 2017-06-21 11:42:56: Completed GET /api/v1/repos/root/support/issues/5/comments 500 Internal Server Error in 14.0007ms

**Comment by duckbrain** [comment]
#4565 may be related. Both are due to a nil repo.

**Comment by afilippov1985** [comment]
No. Still error 500.

**Comment by Unknwon** [comment]
Merged this thread to https://github.com/gogits/gogs/issues/4587.
