### ISSUE TITLE
Custom system user mismatch on Debian package upgrade

### ISSUE THREAD

**Issue by misotolar** [gogits/gogs#4576]
- Gogs version (or commit ref): 0.11.19-1498081835.11b1498.jessie
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [x] MySQL
- Can you reproduce the bug at https://try.gogs.io:
  - [x] No
- Log gist (usually found in `log/gogs.log`):

## Description

I'm running debian package installation with custom user (git). Every package upgrade recreates `gogs` system user as owner of all relevant files and folders (/etc/gogs, /opt/gogs, /opt/gogs/log) and web interface shows install page.

Gogs run as expected after manually change ownership of that files and folders to my custom user (git).

**Comment by Unknwon** [comment]
Hi, as warned here: https://gogs.io/docs/installation/install_from_packages, please contact admin of https://packager.io/ because I don't have access to those install scripts.
