### ISSUE TITLE
Pull Request compare page delivers http/500 error

### ISSUE THREAD

**Issue by magnadoodle** [gogits/gogs#4578]
- Gogs version (or commit ref): 0.11.19 commit f59500a9
- Git version: 2.5.1
- Operating system: CentOS Linux release 7.3.1611
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:

gogs:
2017/06/21 15:47:51 [TRACE] Template: repo/pulls/compare
2017/06/21 15:48:49 [TRACE] Session ID: e0648324fe6f30e4
2017/06/21 15:48:49 [TRACE] CSRF Token: KAVnHqcMTGuErDyDfQOo5doAsbs6MTQ5ODA1MTM3ODM1NjU0MjAwNQ==
2017/06/21 15:48:50 [TRACE] PullRequest[0].testPatch (patchPath): /data/gogs/gogs-repositories/freshx/ansible.git/pulls/20.patch
2017/06/21 15:49:12 [TRACE] Session ID: e0648324fe6f30e4
2017/06/21 15:49:12 [TRACE] CSRF Token: KAVnHqcMTGuErDyDfQOo5doAsbs6MTQ5ODA1MTM3ODM1NjU0MjAwNQ==
2017/06/21 15:49:13 [TRACE] PullRequest[0].testPatch (patchPath): /data/gogs/gogs-repositories/freshx/ansible.git/pulls/21.patch
2017/06/21 15:49:45 [TRACE] Session ID: e0648324fe6f30e4
2017/06/21 15:49:45 [TRACE] CSRF Token: KAVnHqcMTGuErDyDfQOo5doAsbs6MTQ5ODA1MTM3ODM1NjU0MjAwNQ==
2017/06/21 15:49:45 [TRACE] PullRequest[0].testPatch (patchPath): /data/gogs/gogs-repositories/freshx/ansible.git/pulls/22.patch

Macaron:
Jun 21 15:48:49 cmdb gogs-web-1.service: [Macaron] 2017-06-21 15:48:49: Started POST /FreshX/Ansible/compare/master...kai:master for 127.0.0.1
Jun 21 15:48:51 cmdb gogs-web-1.service: [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/runtime/panic.go:489 (0x42c2bf)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/runtime/panic.go:63 (0x42b16e)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/runtime/signal_unix.go:290 (0x44150f)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/models/repo.go:612 (0xb55ada)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/models/repo.go:630 (0xb55fb0)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/models/repo.go:287 (0xb529af)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/models/repo.go:314 (0xb52cba)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/models/pull.go:140 (0xb43b45)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/models/pull.go:444 (0xb4813d)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/routers/repo/pull.go:705 (0xc07a59)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/runtime/asm_amd64.s:516 (0x458756)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/reflect/value.go:434 (0x4aa7cf)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/reflect/value.go:302 (0x4a9d94)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:177 (0x87b40f)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:137 (0x87adda)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8990b2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x898fd6)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/session/session.go:186 (0x8f1450)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:79 (0x898e51)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x87b0e2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x87aedb)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8990b2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x898fd6)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x8ac8fb)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:40 (0x89c568)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x87b0e2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x87aedb)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8990b2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x898fd6)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:52 (0x8abbb4)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:40 (0x89c568)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x87b0e2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x87aedb)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x8990b2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:187 (0x8adbc9)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:296 (0x8a5cad)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/tmp.Gwyrqt9FGb/.go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x89dbac)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/net/http/server.go:2568 (0x6cbdd2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/net/http/server.go:1825 (0x6c80e2)
Jun 21 15:48:51 cmdb gogs-web-1.service: /tmp/d20170610-15-1588rlv/opt/gogs/.git/cache/go1.8/go/src/runtime/asm_amd64.s:2197 (0x45adf1)
Jun 21 15:48:51 cmdb gogs-web-1.service: [Macaron] 2017-06-21 15:48:51: Completed /FreshX/Ansible/compare/master...kai:master 500 Internal Server Error in 1.217989229s

## Description

Opening a new pull request results in a http/500 error instead of showing the compare page. 
This happens occasionally and I could not manage to reproduce it. Pull requests are created anyway but the compare page results in an http 500 error.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/4572.
