### ISSUE TITLE
Netbeans push to remote gives 401 Unauthorized error

### ISSUE THREAD

**Issue by skylarmt** [gogits/gogs#4581]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): No relevant data in log.
## Description

I just upgraded Gogs from 0.9 to 0.11.  Netbeans is no longer able to push to my repositories.  It continually asks for a username and password, and if I press Cancel it gives up with a "401 unauthorized" error.  Running `git push` from a Terminal works fine.

I think this is related to issues #4466 and #4531, but those are specifically about Eclipse, not Netbeans.

**Comment by Unknwon** [comment]
Hi, based on https://www.quora.com/Why-are-Netbeans-Eclipse-written-in-Java-instead-of-portable-C-C++-code. 

I believe both are using same Git client JGit, so this is duplicated to https://github.com/gogits/gogs/issues/4531.
