### ISSUE TITLE
ssh channel goroutine error?

### ISSUE THREAD

**Issue by lowkey2046** [gogits/gogs#4582]
https://github.com/gogits/gogs/blob/master/pkg/ssh/ssh.go#L46

maybe it should like this:

```go
go func(ch ssh.Channel, in <-chan *ssh.Request) {
/*
...
*/
}(ch, reqs)
```

**Comment by Unknwon** [comment]
Hi, but why?

**Comment by lowkey2046** [comment]
Each ssh client can support multiple interactive sessions 

https://godoc.org/golang.org/x/crypto/ssh#Client.NewSession

```go
ch, reqs, err := newChan.Accept()
```
It accept new ssh session, and the `ch` `reqs` is connected with one session

If i try to create multiple interactive sessions，it may be case some error. But git command just create one session.

**Comment by lowkey2046** [comment]
I did some test, buf failed, may i am wrong.
