### ISSUE TITLE
function "AppSubUrl" not defined

### ISSUE THREAD

**Issue by mk-conn** [gogits/gogs#4585]
- Gogs version (or commit ref): Gogs version 0.11.23.0625 (d1a96c25438e1e63c9e2caf77005ae86da14fc72)
- Git version: git version 2.13.1
- Operating system: FreeBSD 11.0-STABLE (FreeNAS jail)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/06/27 00:44:10 [TRACE] Log Mode: File (Trace)
2017/06/27 00:44:10 [ INFO] Gogs: Go Git Service 0.11.23.0625
2017/06/27 00:44:10 [ INFO] Cache Service Enabled
2017/06/27 00:44:10 [ INFO] Session Service Enabled
2017/06/27 00:44:10 [ INFO] Mail Service Enabled
2017/06/27 00:44:10 [ INFO] Notify Mail Service Enabled
2017/06/27 00:44:13 [ INFO] Git Version: 2.13.1
2017/06/27 00:44:13 [ INFO] SQLite3 Supported
2017/06/27 00:44:13 [ INFO] Run Mode: Production
2017/06/27 00:44:13 [TRACE] Doing: CheckRepoStats
## Description

./gogs web results in:

2017/06/27 00:44:10 [TRACE] Custom path: /usr/home/git/gogs/custom
2017/06/27 00:44:10 [TRACE] Log path: /home/git/gogs/log
2017/06/27 00:44:10 [TRACE] Log Mode: File (Trace)
2017/06/27 00:44:10 [ INFO] Gogs: Go Git Service 0.11.23.0625
panic: template: org/settings/hook_new:13: function "AppSubUrl" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x177f160, 0xc420546090, 0x0)
	/usr/local/go/src/html/template/template.go:360 +0x54
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.compile(0xc42026be00, 0x1c, 0xc4201cc390, 0x1, 0x1, 0x0, 0x0, 0xc42026be20, 0x2, 0x2, ...)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:292 +0x4cc
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.(*TemplateSet).Set(0xc4201c62d0, 0xfd14f4, 0x7, 0xc420484000, 0x0)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:318 +0x63
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.renderHandler(0xc42026be00, 0x1c, 0xc4201cc390, 0x1, 0x1, 0x0, 0x0, 0xc42026be20, 0x2, 0x2, ...)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:385 +0x18d
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.Renderer(0xc4205111e0, 0x1, 0x1, 0xa, 0x1)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:422 +0x172
github.com/gogits/gogs/cmd.newMacaron(0xc4201ff180)
	/usr/home/git/go/src/github.com/gogits/gogs/cmd/web.go:110 +0x5cf
github.com/gogits/gogs/cmd.runWeb(0xc4201ff180, 0x0, 0xc4201ff180)
	/usr/home/git/go/src/github.com/gogits/gogs/cmd/web.go:166 +0x74
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xeb1320, 0x1014b60, 0xc4201ff180, 0xc420159500, 0x0)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xb9
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xfcc9fb, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfe02fe, 0x10, 0x0, ...)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc42005b040, 0xc42000c160, 0x2, 0x2, 0x0, 0x0)
	/usr/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/usr/home/git/go/src/github.com/gogits/gogs/gogs.go:41 +0x3ea

**Comment by linquize** [comment]
This is because some template files has been renamed in the new version. 
Please delete all template files before copying the new one!

**Comment by mk-conn** [comment]
Yep, that did it. Thanx!
