### ISSUE TITLE
ListRepoIssueComments: GetCommentsByRepoIDSince: pq: ORDER BY "created_unix" is ambiguous

### ISSUE THREAD

**Issue by hochhaus** [gogits/gogs#4586]
- Gogs version (or commit ref):  d1a96c25438e1e63c9e2caf77005ae86da14fc72
- Git version: git version 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

2017/06/27 20:29:33 [ERROR] [...epo/issue_comment.go:49 ListRepoIssueComments()] GetCommentsByRepoIDSince: pq: ORDER BY "created_unix" is ambiguous

## Description

When calling the `ListRepoIssueComments()` API from the command line, I receive the following error:

`{"message":"pq: ORDER BY \"created_unix\" is ambiguous","url":"https://github.com/gogits/go-gogs-client/wiki"}`

Also, in `log/gogs.log` I see:

`2017/06/27 20:29:33 [ERROR] [...epo/issue_comment.go:49 ListRepoIssueComments()] GetCommentsByRepoIDSince: pq: ORDER BY "created_unix" is ambiguous`

I am filing this here as the bug appears to be in the server and not go-gogs-client.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by hochhaus** [comment]
Unfortunately, I think this proposed patch results in a new error.

`{"message":"pq: got 2 parameters but the statement requires 1","url":"https://github.com/gogits/go-gogs-client/wiki"}`

I am invoking with `curl -s -w "|||HTTPSTATUS|||%{http_code}" -X GET -H "Authorization: token [redacted]" -H "Content-Type: application/json" [redacted]/api/v1/repos/[redacted]/sg/issues/comments`.

**Comment by Unknwon** [comment]
Good catch, turns out to be easy fix :D

**Comment by hochhaus** [comment]
Nice. I can confirm that with 13cca8a66abaeb6ff93dc4926b2517cf49b44bfa the `ListRepoIssueComments` API works as expected.
