### ISSUE TITLE
Cannot access localhost:10080 by following the default docker tutorials

### ISSUE THREAD

**Issue by jerry-shao** [gogits/gogs#4588]
Hi team,

I have followed the [usage section](https://github.com/gogits/gogs/tree/master/docker) on the wiki.
I can run `docker ps` to check its status.

```bash
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
6d15f2b3a1f1        gogs/gogs           "/app/gogs/docker/sta"   30 minutes ago      Up 19 minutes       0.0.0.0:10022->22/tcp, 0.0.0.0:10080->3000/tcp   gogs
```

But when I was trying to access the web ui by 10080 port, there was no response.
Once I ran `curl localhost:10080` on the host, it shows:

```html
<a href="/install">Found</a>.
```

localhost:10080/install cannot be accessed neither.

Could anyone help me, please

**Comment by Unknwon** [comment]
Not pro on Docker, but I don't think you can access Docker container via **localhost**. Use your Docker VM IP!

**Comment by jerry-shao** [comment]
Issue resolved.

Not pro on Docker and gogs. It was my host security rules don't allow 10080 port inbound.

**Comment by Unknwon** [comment]
66666666666
