### ISSUE TITLE
Cannot Connect via SSH on Windows

### ISSUE THREAD

**Issue by beufordy3k** [gogits/gogs#4591]
- **Gogs version**:  0.11.19.0609
- **Git version**: 2.7.4
- **Operating system**: Windows Server 2012 R2 Standard
- **Database**:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- **Can you reproduce the bug at https://try.gogs.io**:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- **Log gist**:
```text
2017/06/28 02:53:14 [TRACE] SSH: Handshaking for 192.168.1.31:23842
2017/06/28 02:53:27 [TRACE] SSH: Connection from 192.168.1.31:23842 (SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1)
2017/06/28 02:53:27 [ERROR] [.../runtime/asm_amd64.s:2197 goexit()] env: exec: "env": executable file not found in %PATH%
```

## Description
I'm not sure why "env" is not found when authenticating via SSH, is it running under a different process that does not have the correct PATH environment usage? What exactly is it looking for?

Here is my ssh verification from ubuntu on a client:
```text
$ ssh -vT git@git.local
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to git.local [192.168.0.249] port 22.
debug1: Connection established.
debug1: identity file /home/myuser/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/myuser/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug1: Authenticating to git.local:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:7j+uvegXiJhkBHs6J3XBRr+oy7rI7n1K6HgPHKTmqDM
debug1: Host 'git.local' is known and matches the RSA host key.
debug1: Found key in /home/myuser/.ssh/known_hosts:1
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/myuser/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
Enter passphrase for key '/home/myuser/.ssh/id_rsa':
debug1: Authentication succeeded (publickey).
Authenticated to git.local ([192.168.0.249]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2668, received 1592 bytes, in 0.0 seconds
Bytes per second: sent 195831.6, received 116853.0
debug1: Exit status -1
```

**Comment by beufordy3k** [comment]
@Unknwon is there something missing or needed in order for this issue to be looked at? I'd really like to get SSH working on our Windows hosted gogs. thanks!

**Comment by Unknwon** [comment]
@beufordy3k hi, are you using git-bash to run Gogs or...? Looks like some essential binaries are missing.

**Comment by beufordy3k** [comment]
@Unknwon this is the standard x64 binary running under nssm on a Windows OS platform... it looks like the context under which SSH runs on the Windows platform is different than what gogs itself uses perhaps.

**Comment by Unknwon** [comment]
@beufordy3k I think with NSSM, the Windows service does not have required binaries setup for Gogs's internal SSH to work. 

I tested `env` command on git-bash and it works. Not found error in Windows CMD.

**Comment by Unknwon** [comment]
Hi... any news on this? Probably the problem is the git-bash binaries are not added to system path?

**Comment by michbak** [comment]
See here: https://stackoverflow.com/a/29609673
Removing `SendEnv LANG LC_*` on client solves the problem.

**Comment by kani-rifluxyss** [comment]
in my case, client pc is running on ubuntu server is on Windows. 

@unknwon  

> One quick solution right now I think you can start Gogs without Windows service and inside git-bash.

I executed 'gogs.exe web' and I am able to clone the repository now. I would prefer running gogs service via the windows service.  Any idea how to fix this issue when we run it via windows service?

note: for me I was able to authenticate via ssh keys, but it was failed when I tried to clone a repository.

_Cloning into '.'...
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists._

**Comment by kani-rifluxyss** [comment]
Update: All set now!
In my case the env.exe is in C:\Program Files\Git\usr\bin . I updated this path in the nssm  > edit > environment tab. Sample screenshot below (not my exact settings, this is where I added the path for env.exe)

![image](https://user-images.githubusercontent.com/5585046/70386201-780c9e80-195c-11ea-923f-ceed5e620397.png)
