### ISSUE TITLE
Gog Kanban Plugin

### ISSUE THREAD

**Issue by emahuni** [gogits/gogs#4597]
I think it would be a paradigm shift if Gog features a Kanban tracker... much like Gitlab tracks issues. I love the simplicity of the installation and how it is like github. I don't know if there are any takers on this.

**Comment by TrAnn3l** [comment]
Duplicate to #3716

**Comment by skorhone** [comment]
I would rather see gogs made pluggable than see gogs trying to implement all possible features you can come up with.

**Comment by xmik** [comment]
I agree with @skorhone . One of the reasons I migrated from Gitlab to Gogs was that Gitlab is full of features I don't want to use and which are not possible to disable.

**Comment by mariusmg** [comment]
Plugins for more "esoteric" features would be nice. If every new feature gets shoved into core, Gogs will end up like Gitlab, slow as molasses and almost unusable.

**Comment by skorhone** [comment]
And project will never gain traction, if all of features are left half-complete. I'd prefer seeing gogs do one things really well: git repository management. Features such as wiki, issue-tracking, project planning should be outside the scope from core project and they should be provided by plugins

**Comment by emahuni** [comment]
Are there plugins that provide kanban ?
