### ISSUE TITLE
The branch name contains '#' not work correctly

### ISSUE THREAD

**Issue by lostlzual** [gogits/gogs#4601]
- Gogs version (or commit ref): 0.11.4
- Git version: 2.7.4
- Operating system: linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/lostlzual/test/pulls/1)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

I use the suggestion form of the feature branch name in the [Atlassian document](https://www.atlassian.com/git/tutorials/comparing-workflows) like issue-#xxx. When I open a pull request, the webhook action "opened" is work. When I push issue-#xxx again, the webhook action "synchronized" is not work, and can't find any record in the "Recent Deliveries". After merge, the branch can't be delete in the pull request.  

When I use the branch name issue-xxx, the webhook action "synchronized" is work, and the branch can be delete in the pull request.

**Comment by Unknwon** [comment]
Since I don't know what do you mean "work" and "don't work", I'm only fixing the "After merge, the branch can't be delete in the pull request."

**Comment by rokuu** [comment]
@Unknwon How does one create a branch with # in the first place in Gogs? I'm trying on try.gogs.io and I hit this error "New branch name must be valid alpha or numeric or dash(-_) or dot characters or slashes."

**Comment by rokuu** [comment]
@Unknwon the compare button doesn't work https://try.gogs.io/laro/test123/compare/master...issue-#1
but if I compare from the master branch and select the new branch with the # from the dropdown, it works https://try.gogs.io/laro/test123/compare/master...laro:issue-%231

**Comment by Unknwon** [comment]
>the compare button doesn't work

Which one?

**Comment by rokuu** [comment]
![screenshot from 2018-04-17 10-04-21](https://user-images.githubusercontent.com/38368986/38848811-a131f0ea-41f8-11e8-8dc7-43fdaa0586fd.png)

**Comment by Unknwon** [comment]
Got it.

**Comment by lostlzual** [comment]
"Work" means I can find the webhook be triggered in the "Recent Deliveries" at the webhook settings page.

**Comment by rokuu** [comment]
@Unknwon Can confirm using `
<a href="{{.BaseRepo.Link}}/compare/{{.BaseRepo.DefaultBranch}}...{{EscapePound .PullRequestCtx.HeadInfo}}"> ` fixed the green compare button.

I'm confused about the other occurences of `.PullRequestCtx.HeadInfo` in other .tmpl files, listed below : 

https://github.com/gogits/gogs/blob/7e15ff9486cde36b76f3d39b7db23f89278acb7d/templates/repo/pulls/commits.tmpl#L8
https://github.com/gogits/gogs/blob/7e15ff9486cde36b76f3d39b7db23f89278acb7d/templates/repo/pulls/files.tmpl#L8
https://github.com/gogits/gogs/blob/7e15ff9486cde36b76f3d39b7db23f89278acb7d/templates/repo/pulls/files.tmpl#L8
https://github.com/gogits/gogs/blob/66c1e6b0e8308068dbddaec03585f388875f4192/templates/repo/issue/list.tmpl#L11

can you look whether these need modifications as well?

**Comment by Unknwon** [comment]
@lostlzual:

> "Work" means I can find the webhook be triggered in the "Recent Deliveries" at the webhook settings page.

What event(s) you checked for the webhook? Just **Pull Request** or .. ?

@rokuu Yes, maybe `.BaseRepo.DefaultBranch` needs `EscapePound` too.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by lostlzual** [comment]
It works now, thanks!
