### ISSUE TITLE
TeamCity CI server fails fetch from gogs via http

### ISSUE THREAD

**Issue by torjue** [gogits/gogs#4604]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: not relevant
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
More or less the same problem as #2431, but only over HTTP.

**Comment by Unknwon** [comment]
Define "fail".
