### ISSUE TITLE
gogs如何才支持反向代理的用户认证

### ISSUE THREAD

**Issue by cabbage89** [gogits/gogs#4608]
我看到很多文章中提到过
>支持 SMTP、LDAP 和反向代理的用户认证

应该是在http header 中加一个用户名属性就能登录的，可以我一直不知道怎么配置

**Comment by cevin** [comment]
最新版本在后台可以自己设置

**Comment by Unknwon** [comment]
I think this is what you need: https://github.com/gogits/gogs/blob/master/conf/app.ini#L188-L189

**Comment by cabbage89** [comment]
谢谢，但是仅仅一个用户名还不够吧，自动注册用户时还应该需要有“显示名称”，之类的基础信息吧

**Comment by Unknwon** [comment]
@cabbage89 you're right, currently only support authentication, not creation.
