### ISSUE TITLE
Gogs crashes

### ISSUE THREAD

**Issue by Flobbos** [gogits/gogs#4609]
- Gogs version (or commit ref): 0.11.24.0627
- Git version: 1.7.1
- Operating system: CloudLinux 6.9 x86_64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes 
  - [X] No (note description)
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
Log is empty so to say. I can't find any information in the logs.

## Description
Everyday gogs silently crashes and we can not push or pull anything. The web interface shows the login page but you can not log in because the server is unresponsive. The only way to fix this is to log in via SSH and manually restart gogs. After that it works just fine for a day, then silently crashes (usually during the night) and the next day we need to restart it again. I wish I could give you more detailed information about this but I can't.

**Comment by kroppt** [comment]
You can try running something that will restart it for you when the server stops responding. Not sure how to check that, but it is probably worth looking into while this is an issue. You can even run it externally, and use an SSH command to restart (ssh <remote> <command> <args>).

**Comment by Unknwon** [comment]
Hi, CPU usage, RAM usage, how many repositories, how large are the repositories?
