### ISSUE TITLE
Markdown link to HTML

### ISSUE THREAD

**Issue by kerner1000** [gogits/gogs#4611]
I am using this link in my `README.md`:
`+ [Test Coverage](cov/index.html)`
This is not working as expected,` index.html` is not interpreted.

**Comment by kerner1000** [comment]
Why closed? Maybe you can give me some hints on how to fix this.

**Comment by Unknwon** [comment]
Read issue template before you delete it.

**Comment by kerner1000** [comment]
@Unknwon sorry for this, you are right! I updated the issue, maybe its more helpful now.

**Comment by Unknwon** [comment]
Can you reproduce on demo site? Gogs does not auto-append anything.
