### ISSUE TITLE
[CLI] admin auth command

### ISSUE THREAD

**Issue by cyberb** [gogits/gogs#4614]
Could you add auth command (admin CLI) to manage ldap authentications?
it is useful for automated gogs installation so you do not need to create special user and then delete it.

Something like this would help:

gogs admin new-auth ...

I am integrating gogs into syncloud.org and currently we are automating it using a series of rest calls which is very painful.

**Comment by skorhone** [comment]
There's a request #3142 for moving configuration of authentication backends to flat files. I might look into it, if I get my ldap patch pulled.

**Comment by cyberb** [comment]
config files are even better!

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogits/gogs/issues/3142.
