### ISSUE TITLE
adding subdir to ROOT_URL goes 404

### ISSUE THREAD

**Issue by fenchu** [gogits/gogs#4615]
- Gogs version (or commit ref):  
- Git version: Gogs 0.11.19.0609
- Operating system: Git Version: 2.7.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
In order to use my ssl proxy I need to use a subdir on ROOT_URL
aka:  ROOT_URL=http://localhost:8891/git

But if I then access http://localhost:8891/git, I get the html but all css/js links are 404

Also deleted the mysql database and started new, but same issue.
Fine without it, but then I can't put it behind my ssl-proxy, because it hosts lots of other projects.

Is there somewhere else I need to configure, that is not set in the faq:
https://gogs.io/docs/intro/faqs#how-do-i-use-apache-2-with-reverse-proxy%3F
it will not work unless it is the only server on the virtualhost.

Thanks, below it the header, where all the url-paths are ok, but they do not load

```
<!DOCTYPE html>
  | <html>
  | <head data-suburl="/git">
  | <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  |  
  | <meta name="author" content="Gogs" />
  | <meta name="description" content="Gogs is a painless self-hosted Git service" />
  | <meta name="keywords" content="go, git, self-hosted, gogs">
  |  
  | <meta name="referrer" content="no-referrer" />
  | <meta name="_csrf" content="IOS5MblO2_b_zP3nuo5qAW1dfUA6MTQ5OTU0MjM4ODk4NDk2NDU2Mg==" />
  | <meta name="_suburl" content="/git" />
  | <meta property="og:url" content="http://localhost:8891/git/" />
  | <meta property="og:type" content="website" />
  | <meta property="og:title" content="Gogs">
  | <meta property="og:description" content="Gogs is a painless self-hosted Git service.">
  | <meta property="og:image" content="http://localhost:8891/git/img/gogs-lg.png" />
  | <meta property="og:site_name" content="Gogs">
  |  
  | <link rel="shortcut icon" href="/git/img/favicon.png" />
  |  
  | <script src="/git/js/jquery-1.11.3.min.js"></script>
  | <script src="/git/js/libs/jquery.are-you-sure.js"></script>
  | <link rel="stylesheet" href="/git/assets/font-awesome-4.6.3/css/font-awesome.min.css">
  | <link rel="stylesheet" href="/git/assets/octicons-4.3.0/octicons.min.css">
  |  
  | <link rel="stylesheet" href="/git/css/semantic-2.2.10.min.css">
  | <link rel="stylesheet" href="/git/css/gogs.css?v=d9c2d9bb647a949f6d06f4946ab31d91">
  |  
  |  
  | <script src="/git/js/semantic-2.2.10.min.js"></script>
  | <script src="/git/js/gogs.js?v=d9c2d9bb647a949f6d06f4946ab31d91"></script>
  |  
  | <title>Page Not Found - Gogs</title>
  |  
  | <meta name="theme-color" content="#ff5343">

```

**Comment by Unknwon** [comment]
That's too bad...

>Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
