### ISSUE TITLE
Debian 9 Stretch package missing in packager.io

### ISSUE THREAD

**Issue by oschoudhury** [gogits/gogs#4616]
Debian 9 aka Stretch has been released almost a month ago (https://www.debian.org/News/2017/20170617), but there is no debian 9 listed in https://packager.io/gh/pkgr/gogs

At the moment, login via the website fails with a 500 error code and ssh login fails with a 
```
Gogs: Internal error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The gogs log file shows the following error message:
```
[...g/context/context.go:171 ServerError()] UserSignIn: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
```

My naive guess would be that debian 9 is not just missing in the packager.io, but also missing some sort of dependency of configuration option for gogs to run properly. But I really don't have a clue here. Debian 9 changed from MySQL to MariaDB for the backend engine, but no other application caused a problem here.

Details:
- Gogs Version: 0.11.21.0611
- go version go1.7.4 linux/amd64
- git version 2.11.0
- mariadb  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by Chouchen** [comment]
Asked on twitter, here's the reply : https://twitter.com/hellopkgr/status/879786586975727616

**Comment by Unknwon** [comment]
Thanks @Chouchen for the info!

And sorry we don't take packager.io related issues here...
