### ISSUE TITLE
Controlling issues via commit commands

### ISSUE THREAD

**Issue by Cysioland** [gogits/gogs#462]
Like on GitHub and other services, ex. closes #x or fixes #x or reopens #x

**Comment by EtienneBruines** [comment]
Which keywords would be desirable for simple 'referencing'? I can make a PR for that today.

**Comment by Unknwon** [comment]
Hi @Cysioland , I just pushed code for `reopen/reopens/reopened` to `dev` branch, and you can also test on https://try.gogs.io/
