### ISSUE TITLE
添加用户报错500

### ISSUE THREAD

**Issue by fujinzhou** [gogits/gogs#4623]
[Macaron] 2017-02-15 17:03:26: Started POST /user/sign_up for 192.168.0.101
[Macaron] 2017-02-15 17:03:26: Completed POST /user/sign_up 500 Internal Server Error in 128.458068ms

**Comment by fujinzhou** [comment]
[git@localhost gogs]$ go version
go version go1.7.6 linux/amd64
[git@localhost gogs]$ ./gogs --version
Gogs version 0.11.4.0405

**Comment by kangkaime** [comment]
怎么解决的

**Comment by tfzxyinhao** [comment]
应该是没有创建目录的权限
