### ISSUE TITLE
Gogs is not running with Nginx subfolder proxy setting (already solved)

### ISSUE THREAD

**Issue by ceremcem** [gogits/gogs#4626]
I'm trying to serve Gogs behind Nginx under a subfolder for hours. Finally, I managed to understand the problem: 

![image](https://user-images.githubusercontent.com/6639874/28253203-94a13e34-6aa9-11e7-861d-15c5286f7d78.png)

Would you consider pointing out that part in the documentation?

**Comment by Unknwon** [comment]
I think it is really an important skill to read the docs carefully...

**Comment by ceremcem** [comment]
I think it is really an important skill to write the docs carefully...

**Comment by Unknwon** [comment]
Either way you prefer. Customer never satisfied😣

**Comment by ceremcem** [comment]
Haha! That's unfair! =)

Don't be offended, but it's like a simple regex syntax error you've made where you just forgot to add the "global" switch, which made me skip reading in the first match. 

Honestly, I really appreciate you for doing this great job and I want it to be greater (that's why I shared that pitfall). Please consider that I'm not the only one who forgot to add the ending slash. 

[This is the exact post](https://github.com/gogits/gogs/issues/1269#issuecomment-107771898) that helped me solving the problem: 

![image](https://user-images.githubusercontent.com/6639874/28732590-10a8b328-73e1-11e7-8196-77c24680f007.png)

It's up to you.

**Comment by Unknwon** [comment]
Lol, you win.

**Comment by Unknwon** [comment]
OK, how about this:

note to the both suffixes after **location** and **proxy_pass**.

**Comment by ceremcem** [comment]
Now the one must be blind to miss that. That would be quite enough.

**Comment by ceremcem** [comment]
(Upps, not merged yet)

**Comment by Unknwon** [comment]
Updated: https://gogs.io/docs/intro/faqs#how-do-i-set-up-a-sub-path-with-nginx%3F

**Comment by zzbkszd** [comment]
NOT noted that in chinese yet!  ╮(￣▽￣)╭
