### ISSUE TITLE
Creating a Fork gives 500 Internal Server Error

### ISSUE THREAD

**Issue by mamohr** [gogits/gogs#4628]
- Gogs version (or commit ref): 0.11.26.0714
- Git version: 2.11.2
- Operating system: docker container (gogs/gogs:develop) on Core OS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Creating a fork from a repository gives 500 Internal Server Error.

The Server log contains the following line:

`
2017/07/17 22:59:30 [ERROR] [...g/context/context.go:171 ServerError()] HasForkedRepo: getUserByID [0]: user does not exist [user_id: 0, name: ]
`

On [https://try.gogs.io/repo/fork/4044](https://try.gogs.io/repo/fork/4044) I'm also getting a 500 error when trying to fork the repository with my newly created user.

**Comment by xluohome** [comment]
fork 出错 500 ,使用的是 docker gogs版本: 0.11.26.0714

**Comment by Unknwon** [comment]
Hi, this is a fixed issue in `master`. I can fork without a problem.
