### ISSUE TITLE
Landing page option LANDING_PAGE = explore buggy.

### ISSUE THREAD

**Issue by jxsl13** [gogits/gogs#4634]
- Gogs version (or commit ref): 
- Git version: 0.11.28.0718
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Enabling the option 
LANDING_PAGE = explore
has the effect that you can not go back to the original home site.
if you  click on the "home" menu, you are just bought back to the explore site.
I do not know if this is intended, but for me it's a little bit weird to have two menu entries pointing to the same location. 
In my opinion it should be that if you visit the tld e.g. git.example.com
and you are brought to the landing page, from which you can navigate wherever you want. Even to the old / default landing page "home".
...

**Comment by Unknwon** [comment]
>if you click on the "home" menu, you are just bought back to the explore site.

Yes, it is doing what exactly it should be doing. Some people want this because default home page is branding for Gogs.
