### ISSUE TITLE
未知原因导致cpu100%

### ISSUE THREAD

**Issue by wei193** [gogits/gogs#4635]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): Gogs version 0.11.4.0405
- Git version: git version 1.8.3.1
- Operating system: centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
![image](https://user-images.githubusercontent.com/5051170/28447075-327313c6-6e01-11e7-9683-e22515bf3b51.png)

**Comment by 4oo4** [comment]
This sounds like the same issue I had (https://github.com/gogits/gogs/issues/4475), does it still happen when you upgrade to 0.11.19?

**Comment by wei193** [comment]
update to  0.11.19.0609 , Has been resolved
