### ISSUE TITLE
Gogs server-side bug - error: failed to push some refs to my Gogs server

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [gogits/gogs#4636]
ping @Unknwon 

----

- Gogs version: 0.9.141.0211
- Git version: 2.13.0
- Operating system: Windows 10 (64 bit)
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): log is empty

## Description
I thought the issue was from my command line program (Windows PowerShell) so I tested it and tried to push my commits to GitHub and it works but it doesn't work on my Gogs server.

> The issue is completely explained at https://github.com/git-for-windows/git/issues/1204.

**Comment by Unknwon** [comment]
Hi, I think you did the right thing report to corresponding repository. 

Also, it could the problem of the way you setup Git-related thing on Windows.

>so I tested it and tried to push my commits to GitHub and it works but it doesn't work on my Gogs server.

GitHub is not hosted on Windows.

Closing since this is not a Gogs-specific issue.

**Comment by SuriyaaKudoIsc** [comment]
Similar issues:
- https://discuss.gogs.io/t/remote-error-hook-declined-to-update-refs-heads-master/366
- https://github.com/gogits/gogs/issues/1840
- https://stackoverflow.com/questions/16690785/error-hook-declined-to-update-refs-heads-external-pub-while-pushing-a-branch
- https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by SuriyaaKudoIsc** [comment]
I tried it again:

```
C:\Users\Suriyaa\Downloads\testhooks>git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        version.py

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\Suriyaa\Downloads\testhooks>git add *

C:\Users\Suriyaa\Downloads\testhooks>git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   version.py


C:\Users\Suriyaa\Downloads\testhooks>git commit -m ":tada: Initial commit"

Sie benötigen eine Passphrase, um den geheimen Schlüssel zu entsperren.
Benutzer: "suriyaa <isc.suriyaa@gmail.com>"
2048-Bit RSA Schlüssel, ID FDDD96B0, erzeugt 2016-04-08

[master (root-commit) 73573bb] :tada: Initial commit
 1 file changed, 3 insertions(+)
 create mode 100644 version.py

C:\Users\Suriyaa\Downloads\testhooks>git status
On branch master
nothing to commit, working tree clean

C:\Users\Suriyaa\Downloads\testhooks>git push -u origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\Suriyaa\Downloads\testhooks>git remote add origin https://git.suriyaa.tk/SuriyaaKudoIsc/testhooks.git

C:\Users\Suriyaa\Downloads\testhooks>git push -u origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 674 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Skipping command-line '"C:\Program Files\Git\mingw64\bin\..\usr\bin\bashremote:
remote: ('C:\Program Files\Git\mingw64\bin\..\usr\bin\bash.exe' not found)
remote: Need a valid command-line; Edit the string resources accordingly
remote: error: hook declined to update refs/heads/master
To https://git.suriyaa.tk/SuriyaaKudoIsc/testhooks.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'https://git.suriyaa.tk/SuriyaaKudoIsc/testhooks.git'

C:\Users\Suriyaa\Downloads\testhooks>
```

And I get this too:
![screenshot by suriyaa - internal server error - g_ - https___git suriyaa tk_suriyaakudoisc_testhooks](https://user-images.githubusercontent.com/5073946/28995751-dfbd324a-79f1-11e7-8902-9383f070cbed.png)

**Comment by Unknwon** [comment]
Hi, you need to fix this problem:

('C:\Program Files\Git\mingw64\bin\..\usr\bin\bash.exe' not found)

**Comment by SuriyaaKudoIsc** [comment]
✅ Fixed. The problem was the bash command in `cygwin64`.
