### ISSUE TITLE
Docker Windows 10 issues with SSHD setup

### ISSUE THREAD

**Issue by aprofessionalusername** [gogits/gogs#4637]
Windows 10 Anniversary update fails to setup SSHD with a repeating error

Docker version:
Version 17.06.0-ce-win19 (12801)
Channel: stable
c98c1c2

I have four different machines
One is a W10 Creators update build on the latest Docker Stable for Windows.
Second is W10 Anniversary update build on the latest Docker Stable build c98c1c2
Third is a Mac running MacOS Sierra on the latest Docker Stable for Mac
Fourth is a Linux Mint 18 on the current stable branch build 02c1d87

All using the same command
`docker run --name=gogs -p 10080:3000 -v h:/gogs:/data -p 10022:22 gogs/gogs:latest`
or for mac/linux
`docker run --name=gogs -p 10080:3000 -v ~/gogs:/data -p 10022:22 gogs/gogs:latest`

The Mac build functions as intended when pulling the latest Gogs build.
The Creators update build functions as intended when pulling the latest Gogs build.
The Anniversary update build throws the following error immediately upon build

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/data/ssh/ssh_host_ed25519_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private: bad permissions
Could not load host key: /data/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```

Attaching to the docker container and attempting to chmod the file in question to 600 (recommended) does not return any errors, but the file permissions do not change.
I also cannot remove/other wise manipulate the files. Strangely this pertains only to gogs/gogs as far as I can tell, other containers I've tried do not have this issue. I can remove/modify permissions and so on just fine on the Anniversary machine.
Strangely the file IS set to 411! So I'm not sure why SSHD even reports the error it does.
`-rwxr-xr-x    1 root     root           411 Jul 23 21:35 ssh_host_ed25519_key`

Frustratingly no logs appear to be created.

edit:  
Perhaps similar to [1758](https://github.com/gogits/gogs/pull/1758)?

**Comment by Unknwon** [comment]
Found the related file, but I would think it is a Docker on Windows issue? https://github.com/gogits/gogs/blob/7e15ff9486cde36b76f3d39b7db23f89278acb7d/docker/s6/openssh/setup#L23

**Comment by aprofessionalusername** [comment]
Sort of? I think its the way you are handling the SSH key permission setting though.

If I use codeskyblue/gogs version of your image it DOES throw the SSH key error, but stops after the second set of scripts kicks in and doesn't seem to have any further SSH key issues.

Restarting the codeskyblue version and then attaching does not show the SSH-prompt looping either.

Any other information I can provide that might help?

**Comment by Unknwon** [comment]
I really would love to know why but my knowledge about Docker is very limited... even worse, knows nothing about Docker on Windows :joy: Maybe someone with expertise could give some advice...

**Comment by aprofessionalusername** [comment]
Looks like you called it originally, Docker issue at heart. They did something very strange to volume permissions recently. I rebuilt my install of Docker for Win on the Creators update machine. Same issue now.

Work around is to use internal Docker volumes. Which I suppose isn't terrible just remember to make backups.

So change my command to: 
docker volume create gogs
docker run --name=gogs -p 10080:3000 -v gogs:/data -p 10022:22 gogs/gogs:latest

And it behaves as expected again.
