### ISSUE TITLE
Web editor Issue

### ISSUE THREAD

**Issue by fatbigbright** [gogits/gogs#4640]
Hello,
I have an issue when I reconfigure my gogs from simple execute program into windows service.

I found I cannot successfully edit markdown files on the web editor anymore. Every time I finished editing and commit the change online, nothing happens. But I found in dashboard, there is a commit history for my change, while if I click on the MD5 link for the commit, the page leads me to the latest commit that I pushed from client which is different from the right one.

I guess it may have something to do with some permission setup for I changed gogs into Windows service. But I can create new repository, which means gogs has the permission to write the repository folder, and also the sqlite db because the new repository information can be shown normally on the web site.

I am using Windows server 2012R2, and my gogs version is 0.11.4.0405.

Thanks in advance.

Update:

To avoid any influence of the reverse proxy setup I made on the IIS of the server, I downloaded latest release and install it on another server on which there is no special IIS settings. And I followed the guide to set the gogs on the new server as windows service and I found the problem still remains, I can push commits to the server but changes made in web editor doesn't work. Please note that on dashboard there is new commit change history related to that made by web editor, but it cannot be found in the repository pages,

**Comment by Unknwon** [comment]
Hi, if there is an error, this is a log. If there is no log message, I can't help you much...
