### ISSUE TITLE
Gogs does not recognise SYSNAME datatype in MSSQL

### ISSUE THREAD

**Issue by chrislemje** [gogits/gogs#4642]
- Gogs version (or commit ref):  0.11.19.0609 (and previous)
- Git version:  2.12.1.windows.1
- Operating system: Windows Server 2012R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL (2014)
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/07/25 11:02:05 [TRACE] Log Mode: File (Trace)
2017/07/25 11:02:05 [ INFO] Gogs 0.11.19.0609
2017/07/25 11:02:05 [ INFO] Cache Service Enabled
2017/07/25 11:02:05 [ INFO] Session Service Enabled
2017/07/25 11:02:05 [ INFO] Mail Service Enabled
2017/07/25 11:02:05 [ INFO] Notify Mail Service Enabled
2017/07/25 11:02:05 [FATAL] [...s/routers/install.go:66 GlobalInit()] Fail to initialize ORM engine: sync database struct error: Unknown colType SYSNAME for sysdiagrams - name

Starting the Gogs service fails with the above message in the log when the default sysdiagrams table has been created in the Gogs MSSQL database. This table is created when first expanding the Database Diagrams subfolder in SQL server manager and answering "yes" to the "Do you wish to create the diagramming support objects" question.

This issue can be worked around by either deleting the sysdiagrams table or changing the name column datatype from SYSNAME to NVARCHAR(128). The Gogs service will then start.

**Comment by Imhven** [comment]
I have same issue,and then I Delete the sysdiagrams,gogs work!

**Comment by Unknwon** [comment]
Hi, I think it would be better to report this issue to https://github.com/go-xorm/xorm because Gogs relies on this ORM to operate on MSSQL database.

**Comment by andretf** [comment]
My solution was manually create gogs database in MSSQL before install.

**Comment by dongfo** [comment]
where is the sql scripts?@andretf

**Comment by JohnRayson** [comment]
> My solution was manually create gogs database in MSSQL before install.
Same here - Installer wouldn't create the DB

**Comment by Unknwon** [comment]
Dependency package (github.com/go-xorm/core) has been updated, please help check if it is fixed, thanks!
