### ISSUE TITLE
发送测试邮件报错。

### ISSUE THREAD

**Issue by ddyllen-z** [gogits/gogs#4644]
报错内容：
```
gomail: could not send email 1: StartTLS: x509: certificate is valid for dd40882ba0ea
```
用smpt，25端口，我没启用ssl端口。
这个需要怎么设置？

**Comment by ddyllen-z** [comment]
我看到了文档，只支持STARTTLS的SMTP。

**Comment by ddyllen-z** [comment]
还是不行呀，我用letsencrypt的证书给我的smtp服务器加上了ssl，还是报这个错。

**Comment by Unknwon** [comment]
What are you talking?

**Comment by ddyllen-z** [comment]
@Unknwon 测试发送邮件报错呀。
报错内容：`gomail: could not send email 1: StartTLS: x509: certificate is valid for dd40882ba0ea`
这是怎么回事？我的邮件服务器我测试过了，没问题，可以发送邮件。

**Comment by Unknwon** [comment]
I don't know, I think your certificate is invalid or self-signed.

**Comment by ddyllen-z** [comment]
好了，没问题了。邮件服务器证书设置错误，导致的。

**Comment by yaoxiaofdou** [comment]
6666，小伙子，中国人的骄傲

**Comment by ddyllen-z** [comment]
@yaoxiaofdou 这项目的开发者  Unknwon本来就是中国人。他又不是看不懂中文，我英文不怎么样。

**Comment by xingxing9688** [comment]
@ddyllen-z  我邮件也是报这个报错，请问是怎么解决的，有相关配置可以贴出来吗
