### ISSUE TITLE
feature request - http status endpoint for external monitoring

### ISSUE THREAD

**Issue by webervin** [gogits/gogs#4645]
Please add some kind of status endpoint that would return HTTP 200 only if gogs and it's dependencies are running smoothly. (Probably easy solution would be to attempt to SELECT 1 from database). Such endpoint would be useful for infrastructure monitoring tools.

**Comment by Unknwon** [comment]
Hi, you can use `/healthcheck`, e.g.: https://try.gogs.io/healthcheck
