### ISSUE TITLE
Quick guide is only for "RepositoryAdmin" (right is "RepositoryWriter")

### ISSUE THREAD

**Issue by francalek** [gogits/gogs#4646]
More info is here:
https://discuss.gogs.io/t/quick-guide-clone-info-in-bare-repository-only-for-admins/1283/7

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by francalek** [comment]
It's okay, thanks :)
