### ISSUE TITLE
Fail to generate private key: exec: "ssh-keygen": executable file not found in %PATH% - goroutine 1 [running]:

### ISSUE THREAD

**Issue by kyan54** [gogits/gogs#4651]
Fail to generate private key: exec: "ssh-keygen": executable file not found in %PATH% - goroutine 1 [running]:

How to fix it up？

**Comment by Unknwon** [comment]
Install `ssh-keygen`...

**Comment by kyan54** [comment]
window server 。
I have installed git。And add environment variables:%git%;%git%\cmd;%git%\bin.

**Comment by comicfans** [comment]
I suggest to add this requirements to documents, or send info to logfile.  when setting up as windows service ,it's very hard to find the actual problem.

**Comment by Unknwon** [comment]
If you install git-bash, I think it comes with it.

**Comment by comicfans** [comment]
currently windows git do have ssh-keygen, but didn't put its folder in PATH variable.

**Comment by Unknwon** [comment]
@comicfans ah, good point. I'll revise the prerequisite docs.

**Comment by parq** [comment]
Hi,

Same issue. Just add [git path]/usr/bin to windows path.

Regards...

**Comment by xcomhz** [comment]
Hi
Open environment variable in windows settings and add {C:\Program Files\Git\usr\bin} in system and user variables, it is default path of git ,you may need use path as git installed path
** RESTART "Go gits services" in windows services **
