### ISSUE TITLE
Is there a way to not show all of the license options ?

### ISSUE THREAD

**Issue by fredhampton** [gogits/gogs#4652]
I m using the latest master version with the latest build of debain.

Is there a way to not show all of the license options ?

I have tried deleting some of them from the license directory but they still show up in the add repo license section 

Thanks

**Comment by acjh** [comment]
Did you restart your instance after deleting?

**Comment by fredhampton** [comment]
I restarted my instance after deleting.

**Comment by Unknwon** [comment]
Hi, I think this duplicated to https://github.com/gogits/gogs/issues/3915.

**Comment by fredhampton** [comment]
Yes it is duplicate.
Is there a solution ?


Thanks!
