### ISSUE TITLE
Specify gogs-repositories location

### ISSUE THREAD

**Issue by sarandafl** [gogits/gogs#4654]
- Gogs version (or commit ref): 
- Git version: 0.11.29.0727
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Repo data is stored in the home dir of the user running the gogs service. Is it possible to specify an alternative location? Via config file perhaps? 
...

**Comment by sarandafl** [comment]
Nevermind:
https://gogs.io/docs/advanced/configuration_cheat_sheet

**Comment by amitkmr209** [comment]
i have installed gogs in window10 , its not showing actual location of source code , some one can help me
