### ISSUE TITLE
How to connect MySQL with docker instance

### ISSUE THREAD

**Issue by pokapow** [gogits/gogs#4655]
You don't explain how to use the MySQL database with docker instance. So I create another container with mysql inside, created there a database for gogs, and linked the 2 container with:
`docker run --name=gogs --link gogs-db:mysql -p 10022:22 -p 10080:3000 -v /var/www/gogs:/data -d gogs/gogs`

But it's not working. At the install of gogs, it can't connect to MySQL. Could you explain how to do step by step ?

**Comment by Unknwon** [comment]
Hi,

>Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
