### ISSUE TITLE
Gogs behind nginx behind caddy (different machines)

### ISSUE THREAD

**Issue by vClouds** [gogits/gogs#4656]
[gogs.log.txt](https://github.com/gogits/gogs/files/1185402/gogs.log.txt)

- Gogs version (or commit ref): 0.11.19
- Git version: 1.9.1
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
**Gogs - Improper Configurations**
Gogs installed from packages on Ubuntu 14.04 and running on port 6000 with nginx reverse proxy listening to port 3443 ssl.
Gogs is accessible from anywhere through caddy reverse proxy on different machine through https://repo.example.com in URL.

Repo URL still showing the default URL **HTTP**://localhost:6000
Upon changing app.ini from default to the below entries to allow clone/download, nginx shows error 502 and the log shows attempts to access **HTTPS**://localhost:6000

Please advise, it should NOT be the TLS as it resides in nginx and/or caddy and NOT for port 6000.
```
[server]
PROTOCOL               = https
DOMAIN                 = example.com
ROOT_URL               = https://repo.example.com/
HTTP_ADDR              = 127.0.0.1
HTTP_PORT              = 6000
```

**nginx conf**

```
> upstream gogs {
>     server 127.0.0.1:6000;
> }
> server {
>     listen      3443 default;
>     server_name localhost;
> 
>     ssl on;
>     ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
>     ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
>     ssl_session_timeout 5m;
> 
>     ssl_ciphers               'AES128+EECDH:AES128+EDH:!aNULL';
>     ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;
>     ssl_prefer_server_ciphers on;
> 
>     access_log  /var/log/nginx/gogs.access.log;
>     error_log   /var/log/nginx/gogs.error.log;
> 
>     location / {
>         proxy_pass  http://gogs;
>         proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
>         proxy_redirect off;
> 
>         proxy_set_header    Host            $host;
>         proxy_set_header    X-Real-IP       $remote_addr;
>         proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header    X-Forwarded-Proto https;
>     }
> }
```

...

**Comment by Unknwon** [comment]
Hi, 

>Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
