### ISSUE TITLE
Still no mobile friendly UI yet?

### ISSUE THREAD

**Issue by lyuwen** [gogits/gogs#4659]
Is anyone working on this?

**Comment by dalu** [comment]
How about you?

**Comment by 0xpr03** [comment]
it's for devs, you write code so I'm so glad that this site has no mobile first approach

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/144.

**Comment by Unknwon** [comment]
Yes, still... don't. Same as people don't still search before post an issue.....
