### ISSUE TITLE
pulls合并请求关闭后不能被删除

### ISSUE THREAD

**Issue by VAllens** [gogits/gogs#4670]
我创建了个合并请求，然后关闭了它。
我发现在页面上找不到任何可以删除它的地方。
只好直接从数据库里的issue，issue_label，issue_user表找到数据并且硬删除。
这个页面上的删除功能应该很好实现吧，为什么不做么？
难道没有人有这样的需求吗？
或这样的需求在实际业务中不合理，不应该被删除？

**Comment by dwy2002** [comment]
it seems that you remove part of the pull request history by delete it .
could you please help to share more reason why it need ?

**Comment by VAllens** [comment]
Hi, because I deleted a branch and partial push history.
So the associated pulls request merge histories has no meaning...

**Comment by Unknwon** [comment]
Hi, you can't **delete** pull requests or issues, this is by design... sorry..

**Comment by VAllens** [comment]
okey, thanks.
