### ISSUE TITLE
Filing a new issue with a emoji in title causes Gogs to 500

### ISSUE THREAD

**Issue by tilda** [gogits/gogs#4678]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.13.4
- Operating system: Arch Linux x64
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) - ![See this image](https://cdn.discordapp.com/attachments/310876721043865600/344196093703094273/image.png)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
Only 1 line is relevant: 

```
2017/08/07 12:47:51 [ERROR] [...outers/repo/issue.go:878 func1()] ChangeStatus: pq: duplicate key value violates unique constraint "comment_pkey"
```

## Description

This issue is within the Postgres handling. For PRs it has a bonus of breaking the database and you have to go into the database and repair it manually.

**Comment by Mstrodl** [comment]
Can repro

**Comment by Fastidious** [comment]
Dupe of https://github.com/gogits/gogs/issues/4131.

**Comment by tilda** [comment]
Yep, that looks like the same issue. All discussion => #4131
