### ISSUE TITLE
Error when trying to add SSH Key

### ISSUE THREAD

**Issue by jenkk** [gogits/gogs#4683]
- Gogs version:  0.11.28.0718
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 LTS
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

Upon trying to add an SSH key to my account I'm met with this error:

>Sorry, we're not able to verify your SSH key: extractTypeFromBase64Key: invalid key format: not enough length 2224162373

**Comment by Fastidious** [comment]
What type of key is this? RSA, EHDC, etc.?

**Comment by jenkk** [comment]
RSA

**Comment by Fastidious** [comment]
Can’t replicate. Tried on gogs.io, and my own instance, and it just works. Maybe problems with copy and paste? Missing characters? It is the public SSH key which you are adding, correct?

**Comment by jenkk** [comment]
Oh, I was supposed to add my public key? 🤣 
I'll give that a shot.
