### ISSUE TITLE
Improper user or organization names are allowed

### ISSUE THREAD

**Issue by Antimoney** [gogits/gogs#4692]
# This issue is being fixed by a pull request #4695
- Gogs version (or commit ref): 0.11.29.0727
- Git version: Irrelevant
- Operating system: Irrelevant
- Database: Irrelevant
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [x] https://try.gogs.io/explore
  - [x] https://try.gogs.io/explore/repos.git
  - [x] https://try.gogs.io/explore/users.git
  - [x] https://try.gogs.io/explore/organizations.git
  - [x] https://try.gogs.io/explore/repos
  - [x] https://try.gogs.io/explore/users
  - [x] https://try.gogs.io/explore/organizations
  - [x] https://try.gogs.io/org/create/settings
  - [x] https://try.gogs.io/org/create
- Log gist:
  - [ ] I don't have access to log files from https://try.gogs.io

## Description
Users or organizations can be created with an improper name, such as "explore" or "create"

**Comment by Antimoney** [comment]
fixing it in #4695

**Comment by Unknwon** [comment]
Close by merging https://github.com/gogits/gogs/pull/4695.
