### ISSUE TITLE
How to read Gogs?

### ISSUE THREAD

**Issue by zhaoyao91** [gogits/gogs#4696]
How should I read Gogs? does it reads 'go gs' or 'gog s'? If it reads 'go gs', what's the meaning of 'gs'?

**Comment by Antimoney** [comment]
> what's the meaning of 'gs'

It means "git service"

However, I don't know how to pronounce "Gogs", either.

**Comment by zhaoyao91** [comment]
@Antimoney thanks, then I thinks it may be read as 'go gs' to coordinate with another project 'go cd'.

**Comment by Unknwon** [comment]
Hi!

![image](https://user-images.githubusercontent.com/2946214/29246552-850ee0f6-7fcc-11e7-9194-444f63fcb57a.png)

From https://twitter.com/gogshq.

**Comment by zhaoyao91** [comment]
@Unknwon Thanks.  This really should be put on the github main README.

**Comment by Unknwon** [comment]
:rofl: hmm... good point. Will consider!
