### ISSUE TITLE
Removing branches?

### ISSUE THREAD

**Issue by Guard13007** [gogits/gogs#4700]
I see other issues relating to removing branches, so I'm guessing it is supposed to already be a feature, but I have no such option. My only guess is that you can't remove unmerged branches, which is what I need to be able to do.

**Comment by vityafx** [comment]
Interesting, no response here at all. I have created many branches in my project and can't delete them.

**Comment by alexanderadam** [comment]
@vityafx gogs isn't really maintained. Most of the recent commits are locale updates, but PRs and bugs stay mostly open.

If you want a maintained variant of gogs, you want to rather use [gitea](https://github.com/go-gitea/gitea).

**Comment by JaneSmith** [comment]
Did you ever figure this out? I can't find the delete branch option either.

**Comment by vityafx** [comment]
@JaneSmith yes. Delete the repository and create it again, push everything you need there except the branch you wanted to delete.

I moved to gitea with just one click. I suggest you to do this too and don’t spend your gold time with gogs, it is unmaintained.

**Comment by Guard13007** [comment]
Such a shame, but glad to know there is a comparable option available. Unfortunately my version of Gogs is too recent to support importing into Gitea, so I'm going to have to migrate manually. :/

**Comment by Unknwon** [comment]
https://www.git-tower.com/learn/git/faq/delete-remote-branch

Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
