### ISSUE TITLE
Issue mentions should also render with square brackets

### ISSUE THREAD

**Issue by cstroe** [gogits/gogs#4706]
- Gogs version (or commit ref): 0.11.29
- Git version: 2.7.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
    - https://try.gogs.io/cstroe/testrepo/pulls/4#issuecomment-1836
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

Pull Request https://github.com/gogits/gogs/pull/2992 added an alphanumeric style of issue mention like `ABC-123` to Gogs.  While the issue mention is detected when it is surrounded with parentheses `(ABC-123)`, it doesn't work with square brackets `[ABC-123]`.

A user requested this fix: https://github.com/gogits/gogs/pull/2992#issuecomment-323169834

**Comment by cstroe** [comment]
@mqudsi This PR will allow issue mentions to be rendered when they're like `[ABC-123]` or `[#1234]`.

**Comment by mqudsi** [comment]
@cstroe you're awesome!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4707, please help test on `develop` branch or https://try.gogs.io.

**Comment by mqudsi** [comment]
It was fixed by #4707.
