### ISSUE TITLE
关于合并请求冲突的问题

### ISSUE THREAD

**Issue by linghu86** [gogits/gogs#4712]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 0.11.29.0727
- Git version: 2.13.0
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
2017/08/21 11:59:49 [TRACE] PullRequest[0].testPatch (patchPath): E:\GitProjects\zfh\test.git\pulls\3.patch

2017/08/21 11:59:56 [TRACE] PullRequest[0].testPatch (apply): has conflit

error: patch failed: code/Area/.vs/config/applicationhost.config:163

error: code/Area/.vs/config/applicationhost.config: patch does not apply

error: patch failed: code/Area/Area/Area.cs:81

error: code/Area/Area/Area.cs: patch does not apply

error: patch failed: code/Area/Test/Program.cs:10

error: code/Area/Test/Program.cs: patch does not apply

error: patch failed: code/LogHelper/LogHelper/SQLiteORM/SqLite/Internal/TableInfo.cs:3

error: code/LogHelper/LogHelper/SQLiteORM/SqLite/Internal/TableInfo.cs: patch does not apply

error: patch failed: code/RSATool/RSATool/RSATool.csproj:40

error: code/RSATool/RSATool/RSATool.csproj: patch does not apply

error: patch failed: release_product/LogHelper/Config/log4net.config:1

error: release_product/LogHelper/Config/log4net.config: patch does not apply

2017/08/21 11:59:56 [TRACE] PushToBaseRepo[20]: pushing commits to base repo 'refs/pull/3/head'
2017/08/21 11:59:56 [TRACE] Pull request created: 20/19
2017/08/21 11:59:56 [TRACE] Session ID: c99d7f3130a192cb

2017/08/21 11:59:56 [TRACE] CSRF Token: 7gSybWRz-0AV7IxSARvvjC5dDHU6MTUwMzI3NjgyMDEyNzIzNTMwMA==
2017/08/21 11:59:57 [TRACE] Template: repo/issue/view

## Description
我是在本地搭建的git服务器，使用的是http协议，在提交合并请求后，报错误“该合并请求存在冲突，无法进行自动合并操作”

但事实上代码是没有冲突的，在try.gogs.io上面也建了一样的仓库，做了一模一样的操作，但竟然没有问题。
https://try.gogs.io/zfh/test/pulls/2

**Comment by ThirtySomething** [comment]
As far as I understood your comment, you do not have any idea how to solve this issue? Okay - we're using currently another way to backup our repositories, so it doesn't matter. By the way - the posted link is a 404. In which direction you want to point me?
