### ISSUE TITLE
crashed during merge

### ISSUE THREAD

**Issue by guzhongzhi** [gogits/gogs#4714]
while tried to do a pull merge, the main processor of the gogs will be crashed, below is the log

BASED on SQLITE:

[Macaron] 2017-08-21 13:27:28: Started POST /egoint/frontend/pulls/21/merge for [::1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xb8d8fd]

goroutine 1340 [running]:
github.com/gogits/gogs/models.(*Repository).getOwner(0x0, 0x150f820, 0xc04226e960, 0xc0444a8b40, 0x34)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:322 +0x2d
github.com/gogits/gogs/models.(*Repository).mustOwner(0x0, 0x150f820, 0xc04226e960, 0xc0444b1de8)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:335 +0x4a
github.com/gogits/gogs/models.(*Repository).repoPath(0x0, 0x150f820, 0xc04226e960, 0x2, 0x2)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:455 +0x4a
github.com/gogits/gogs/models.(*Repository).RepoPath(0x0, 0x44, 0xc0443e5d08)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/repo.go:459 +0x4a
github.com/gogits/gogs/models.(*PullRequest).PushToBaseRepo(0xc0444b1dc0, 0x0, 0x0)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/pull.go:580 +0x159
github.com/gogits/gogs/models.addHeadRepoTasks(0xc043cd6c70, 0x1, 0x2)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/pull.go:662 +0x16c
github.com/gogits/gogs/models.AddTestPullRequestTask(0xc043f03e00, 0x2, 0xc043e9b3c8, 0x6, 0xc043a6e500)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/pull.go:707 +0x6ad
created by github.com/gogits/gogs/models.(*PullRequest).Merge.func1
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits/gogs/models/pull.go:191 +0xca

**Comment by pgleghorn** [comment]
This was reported to me also, with same stack trace (ending in getOwner), though I didn't witness the exact replication steps. Do you know what exact steps caused it in your case?
I am using 0_11_33 (SQLlite) on Win2012.
