### ISSUE TITLE
LDAP Credentials support

### ISSUE THREAD

**Issue by deepure** [gogits/gogs#472]
访问LDAP的时候需要 Bind DN Bind password

**Comment by Prajithp** [comment]
Any progress here?

**Comment by Unknwon** [comment]
@Prajithp nothing yet.

@lunny do you have time to work on this?

**Comment by dromer** [comment]
Yeah also having issues connecting to OpenLDAP.

We are trying to use anonymous auth with Gogs 0.6.0.0319 Beta

**Comment by Unknwon** [comment]
@dromer don't know what to say, but hmm... Just let you know I read your comment and it's not ignored but haven't got an idea how to do it.

**Comment by flotho** [comment]
Hy,

I vote for implementation of binddn and bind password

**Comment by flotho** [comment]
Hy @deepure , you posted an image with some parameters. Didi you started to implement something regarding to the bind dn etc...

**Comment by deepure** [comment]
@flotho I use the smtp credential instead for ldap at last :)

**Comment by flotho** [comment]
@deepure , thanks for your answer but I'm not sure to understand. 
Do you mean that you are using smtp credentials and bind it to ldap?

regards

**Comment by deepure** [comment]
@flotho  I just use smtp credentials. Beacuase our campany's smtp account is base on the ldap account. It means I did not set the ldap successfully, but another way passed around.

**Comment by flotho** [comment]
@deepure , thanks for this feedback. very sad news that LDAP binddn is not yet functionnal.

**Comment by flotho** [comment]
Hy @Unknwon any milestone for this one?

regards

**Comment by fpoyer** [comment]
Very much interested by having this functionality as well. And no knowledge of Go either...
Any kind of roadmap/milestone for this one?

**Comment by lunny** [comment]
This is a good idea, and could someone has time to help complete this feature?

**Comment by flotho** [comment]
Hy @lunny, no experience at all on Go so I won't be able to code.
Anyway I can lead you and give you some tips.
Usually with binddn and bindpassword, we build a query like this https://access.redhat.com/documentation/en-US/Red_Hat_Directory_Server/8.2/html/Administration_Guide/Examples-of-common-ldapsearches.html :
```
ldapsearch -D "cn=directory manager" -w secret -p 389 -h server.example.com -b "dc=example,dc=com" -s sub "cn=babs jensen"
```
Once you've searched on the table with the user as parameter, you'll recieve an array and in a special field, you'll have the password. 
You'll have to compare SHA1 from the one given by the user in gogs and the other one returned from the ldap.
Is it a great way to help you?

**Comment by Asterix34** [comment]
hi, any news on that feature or a workaround for LDAP ?

**Comment by packageBSConfig** [comment]
hi, any news on that feature or a workaround for LDAP ?

**Comment by Tadzou** [comment]
There must be solutions ?

**Comment by orzechow** [comment]
Also voting on this, but sadly no Go knowledge to help.
Currently the main reason for us not to use gogs...

**Comment by orzechow** [comment]
Also voting on this, but sadly no Go knowledge to help.
Currently the main reason for us not to use gogs...

**Comment by orzechow** [comment]
Okay, I'm not a gogs contributer or anything (and didn't unassign anyone), but why does it say
> lunny was unassigned by orzechow 4 minutes ago

Github bug?!
@lunny

**Comment by lunny** [comment]
I think maybe it's a github bug. @orzechow

**Comment by Unknwon** [comment]
Hi there, by mering PR #1476 into develop, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by Unknwon** [comment]
Close as implemented. :tada:
