### ISSUE TITLE
工单系统是否可以加个重要紧急状态，分重要且紧急，重要不紧急，紧急不重要，不重要不紧急

### ISSUE THREAD

**Issue by cybrobin** [gogits/gogs#4720]
工单系统是否可以加个重要紧急状态，分重要且紧急，重要不紧急，紧急不重要，不重要不紧急

**Comment by Monter** [comment]
In English, please

**Comment by cybrobin** [comment]
Can the work order system be added to a task state?
Four conditions: important and urgent, important not urgent, urgent and not important, not important and not urgent
