### ISSUE TITLE
我在用docker安装gogs后，登陆的时候浏览器一直卡死中，直到网关超时

### ISSUE THREAD

**Issue by jiyi1990118** [gogits/gogs#4732]
大家好，我在用docker安装gogs后，登陆的时候浏览器一直卡死中，直到网关超时。在日志中发现下面内容：

2017/08/30 08:42:40 [ WARN] AvatarLink.LibravatarService.FromEmail [server@xiyuan.name]: lookup _avatars-sec._tcp.xiyuan.name on 192.168.21.1:53: read udp 172.17.0.3:57626->192.168.21.1:53: i/o timeout

请帮忙看看什么问题？谢谢！

**Comment by jiyi1990118** [comment]
问题已解决，结果发现是gravatar服务的问题，禁用就行。坑死啦

**Comment by dohoby** [comment]
怎么看出来的，我装上也是卡死
