### ISSUE TITLE
cannot install postgres DB

### ISSUE THREAD

**Issue by sarahBuisson** [gogits/gogs#4744]
each time I try to install the database in http://0.0.0.0:3000/install, I have this message:
"dial tcp 0.0.0.0:5435: getsockopt: connection refused"

the postgres database is running, 5433 is link to the port 5432, other process can connect to it.
Also, I have the same issue if I specify 172.20.0.2:5435 or postgres:5435

I can ping postgres from the gogs :
`
 ping postgres
PING postgres (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.093 ms
64 bytes from 172.20.0.2: seq=1 ttl=64 time=0.111 ms
`

my docker-compose:

`
version: '2'

services:
  postgres: # jdbc:postgresql://0.0.0.0:5435/gogs
       image: postgres:9.6.3
       restart: always
       ports:
               - "5435:5432"
               - "5436:5433"
       environment:
        - "POSTGRES_USER=root"
        - "POSTGRES_PASSWORD=root"
        - "POSTGRES_DB=gogs"
       volumes:
        - "./db-data2:/var/lib/postgresql/data"

  gogs: # http://0.0.0.0:3000
       image: gogs/gogs:latest
       restart: always
       ports:
        - "10022:22"
        - "3000:3000"
       links:
        - postgres:postgres
       volumes:
        - "./gogs-data:/data"
        - "./gogs-ssh:/etc/ssh"
        - "./gogs-custom:/opt/gogs/custom"
        - "./gogs-home:/srv"
       depends_on:
        - postgres
  jenkins:
       image: jenkins
       ports:
           - "10081:8080"
           - "50000:50000"
       links:
           - gogs:gogs
       volumes:
           - ./jenkins:/var/jenkins_home

volumes:
     db-data:
       driver: local
     gogs-data:
       driver: local

`

gogs log:
`
[Macaron] 2017-09-02 14:44:42: Started POST /install for 172.20.0.1
gogs_1      | 2017/09/02 14:44:42 [TRACE] Session ID: bd9549a7a204ff0b
gogs_1      | 2017/09/02 14:44:42 [TRACE] CSRF Token: sp09dFz6BWPZnG_cK6wosIMKKbM6MTUwNDM2MzQ4MjU0ODczMjAzOQ==
gogs_1      | 2017/09/02 14:44:42 [TRACE] Template: install
gogs_1      | [Macaron] 2017-09-02 14:44:42: Completed POST /install 200 OK in 122.880863ms
gogs_1      | [Macaron] 2017-09-02 14:44:42: Started HEAD /install for 172.20.0.1
gogs_1      | 2017/09/02 14:44:42 [TRACE] Session ID: bd9549a7a204ff0b
gogs_1      | 2017/09/02 14:44:42 [TRACE] CSRF Token: sp09dFz6BWPZnG_cK6wosIMKKbM6MTUwNDM2MzQ4MjU0ODczMjAzOQ==
gogs_1      | 2017/09/02 14:44:42 [TRACE] Template: status/404
gogs_1      | [Macaron] 2017-09-02 14:44:42: Completed HEAD /install 404 Not Found in 105.305979ms

`

**Comment by alexkuznetsov** [comment]
hi @sarahBuisson , can you connect to the postgres via pgadmin, for example? If you can't, please check you pg_hba.conf file.
I use gogs with postgres and don't have any troubles.
