### ISSUE TITLE
Runners system like Gitlab Runners

### ISSUE THREAD

**Issue by scher200** [gogits/gogs#4758]
I really love gogs and it's lightweight footprint. I look forward to use it on a raspberry pi swarm and use it for all of my projects.
The option to add hooks is great, but I would also like to add runners that automatically test/deploy the software. I could not find this option yet, is there anyone working on something like this?

**Comment by S3NS4Ti0N** [comment]
I dont like the idea of implementing build services into gogs. gogs is a great tool for what it currently does what is SCM. Please dont add such a feature.

If you need something that can run builds, take a look at [Jenkins](https://jenkins.io) or if you need something with a more lightweight footprint try [Drone.io](https://github.com/drone/drone)

**Comment by scher200** [comment]
Drone.io, beeing also lightweigth would seem like the right choice.
Looking at the [Gogs Drone site](http://readme.drone.io/0.4/setup/remotes/gogs/)
I see the implementation is pretty limited:
Feature/Remote 	Gogs
Supported version 	0.6.16.1022+
VCS 	git
Auth method 	manual
Push events 	yes
Push tags events 	no
Merge requests 	no
Commit statuses 	no
Restrict by organizations 	no

**Comment by CuBiC3D** [comment]
@scher200 You are looking at a very old documentation - see your link, which points to version 0.4. As of today we are at 0.8. Just try and see if it fits your needs. I use drone in private and company environment with gogs - happy with it so far.

**Comment by scher200** [comment]
@CuBiC3D thank you for letting me know, gonna try this http://docs.drone.io/install-for-gogs/

**Comment by alexanderadam** [comment]
@CuBiC3D I'm pretty sure this issue can be closed as drone is probably what you were looking for, right?

**Comment by scher200** [comment]
yes it is, thank you again

**Comment by CuBiC3D** [comment]
@alexanderadam wasn't me looking, @scher200 can you close please? ;)
