### ISSUE TITLE
centos7  gogs start error

### ISSUE THREAD

**Issue by yunyu2019** [gogits/gogs#4759]
os system: centos 7 64
install:   采用二进制安装包直接安装的
gogs version:   0.11.29
install path:  /data/gogs
直接使用`/data/gogs/gogs web`  **正常**启动gogs项目
但是使用systemd 及/data/gogs/scripts/init/centos/gogs start 都报如下错误：
```
[...gits/gogs/cmd/web.go:163 runWeb()] Fail to test 'git' command: exec: "git": executable file not found in $PATH (forgotten install?)
```

最后附上gogs.service的内容：
```
[Unit]
Description=Gogs
After=syslog.target
After=network.target
After=mysqld.service
  
 [Service]
 # Modify these two values and uncomment them if you have
 # repos with lots of files and get an HTTP error 500 because
 # of that
 ###
 #LimitMEMLOCK=infinity
 #LimitNOFILE=65535
 Type=simple
 User=git
 Group=git
 WorkingDirectory=/data/gogs
 ExecStart=/data/gogs/gogs web
 Restart=always
 Environment=USER=git HOME=/home/git
 
 [Install]
 WantedBy=multi-user.target
```

git已加入了系统环境变量了

**Comment by nan403** [comment]
我有一个和你相同的错误，你找到解决方法了吗

**Comment by oahzuw** [comment]
需要安装git,  centos 安装命令： yum install git

**Comment by nan403** [comment]
我找到解决思路了，gogs对git安装路径有要求[issues](https://github.com/gogits/gogs/issues/3911),坑啊

**Comment by nan403** [comment]
@oahzuw 这种安装方式git版本只有1.8和最新的2.14差距比较大啊

**Comment by yunyu2019** [comment]
最后使用`su - git -c 'nohup /data/gogs/gogs web > /data/gogs/log/gogs_web.log 2>&1 &'`解决了，文档上的守护进程的方法都不好使啊

**Comment by yunyu2019** [comment]
@nan403 ，假如git安装目录为`/usr/local/git`，则将`/usr/local/git/bin`加入环境变量，然后
`ln -s /usr/local/git/bin/git /usr/local/bin/git`，这样就可以了

**Comment by nan403** [comment]
@yunyu2019 谢谢 这个我也解决了，不过我是ln到/usr/bin/git
