### ISSUE TITLE
gogs backup not working in non interactive mode

### ISSUE THREAD

**Issue by ThirtySomething** [gogits/gogs#4764]
- Gogs version: 0.11.19.0609
- Git version: 2.14.1.windows.1
- Operating system: Windows 7 Professional 64-Bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): [gist](https://gist.github.com/ThirtySomething/ce1655667439c090e5d22697f181596c)

## Description

Gogs is installed to run as a Windows service. Per default there is no user logged on at this system. To have a backup, we're running a small batch:

```
@echo off
REM Assumption: Gogs is installed at C:\gogs
c:
cd \
cd \gogs
REM Create gogs backup file
gogs.exe backup
REM Copy gogs backup file on network share
xcopy gogs-backup-*.zip \\<server>\<share>\gogs\ /c /v /y /j
REM Cleanup backup files
del /f /q gogs-backup-*.zip
echo.
cd \
```
But this will work only in `interactive mode` when a user is logged on. For convenience we've added a job in the Windows task scheduler to run this script. The user of the Gogs service is also used for running this batch. But running this script from the task scheduler, no backup file is created by `gogs.exe backup` command.

Question at discuss in this [thread](https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991/23) without any answer/hint.

**Comment by mckaygerhard** [comment]
i think Guindows its not a right operating system for services

**Comment by ThirtySomething** [comment]
I'm sorry, but this is not an option for us. Gogs is offered to run as Windows service, so we use that. Everything works well except the backup.

**Comment by mckaygerhard** [comment]
the firs FOSS software ofered in guiidows was LAMP, as they said, offreed in guindows does not mean recomended for production.. 

as you can see, i do not install a complete setup only to "see" a software runnig, so by the way, its ofered in the current platform to "see" it, testing and in this way prepare a environment to run property..

**Comment by ThirtySomething** [comment]
Okay - do you have any other serious hints and/or tricks?

**Comment by ThirtySomething** [comment]
In case this is the wrong place for this problem, can please anyone point me to the right direction?

**Comment by ThirtySomething** [comment]
Not fixed :-(

**Comment by mckaygerhard** [comment]
time to use good OS as linux, its very complicated support a OS that breaks any standard and security

**Comment by mrichardsonjr** [comment]
I wish they had a fix for this. Sucks for us Windows users.

**Comment by unknwon** [comment]
@mrichardsonjr what is the error message? Maybe (maybe) there is an easy fix...

**Comment by mrichardsonjr** [comment]
@unknwon There is no error message.  I've tried redirecting both standard-out and standard-error to a file, but there's no output in the file.  Strangely, the batch file works just fine when I execute it normally.  However, if I try to execute it in Windows scheduler, the line involving "gogs.exe" simply doesn't seem to do anything, and moves on to the next line in the batch script.  I thought it may have been a permissions issue on Windows scheduler, but I set the scheduled task to run as an admin user, and allowed the task to run with the highest privilege, but still had the same issue.  The exact line I'm running is:
gogs.exe backup --target %dumpDir% --archive-name gogs-backup.zip  1>> %logfile% 2>&1

**Comment by unknwon** [comment]
@mrichardsonjr What is the exact command you used to backup? The log could be written into `path_to_gogs/log/gogs.log`.

**Comment by mrichardsonjr** [comment]
My app.ini file is set as such:
```
[log]
MODE      = file
LEVEL     = Trace
ROOT_PATH = C:/var/gogs/log
```

In C:\var\gogs\log\gogs.log, there are no error statements or anything unusual, only trace statements like:

> 2019/11/17 18:31:12 [TRACE] Doing: MirrorUpdate

**Comment by unknwon** [comment]
Have no idea... but run as Windows service and not as Windows service requires t different versions of Gogs: https://gogs.io/docs/installation/install_from_binary#0.11.91-%40-2019-08-11

**Comment by victorlopresto** [comment]
I realize this is an old thread, but thought this could potentially be helpful to someone.

I had the same issue with my Windows 10 Pro machine.  I created a gogs backup batch script that works fine when run from a command prompt, but refuses to run from Windows task scheduler.  This isn't a solution, but maybe a clue... the backup runs just fine when selecting the option to "Run only when user is logged on".   This is not what I want, but will have to be my workaround until a real solution is found.  I'm using gogs_0.12.3_windows_amd64_mws.zip 

As others noted, there is no error message, no debug information, nothing. The gogs backup call just does nothing unless I run from a command prompt directly or use the "Run only when user is logged on" option.
