### ISSUE TITLE
[Suggestion] Add a config for the SSH path in URL format

### ISSUE THREAD

**Issue by 5lx** [gogits/gogs#4770]
- Gogs version (or commit ref):  docker gogs latest, image id 245abb5da84e
- Git version: 
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When I use docker to start the gogs server, the ssh port is port from the container to 0.0.0.0:10022.
So to correct the ssh path showing on the repo website, I tried to add a port number on the gogs domain setting. I got the following path:

> git@xxx.xxx:10022:xxx/xxx.git

I cannot use this path to clone the repo, because we cannot directly assign a port number on this kind of path. So, I tried using the URL format SSH:

> ssh://git@xxx.xxx:10022/xxx/xxx.git

And this time, It works very well. But I cannot let the ssh path shown on the webpage in this way.

So I suggest to add a config key to set the URL format SSH path, and this could solve the specific ssh port problem.

**Comment by bonki** [comment]
Isn't that exactly what `SSH_PORT` does? For me it seems to work as expected and SSH clone URLs in the web interface correctly display the configured port.

    ; Port number to be exposed in SSH clone URL
    SSH_PORT =
