### ISSUE TITLE
How do I use npm install to install components from gogs?

### ISSUE THREAD

**Issue by chavyleung** [gogits/gogs#4771]
- Gogs version (or commit ref): 
- Git version:  0.11.29.0727
- Operating system: win10
- Database (use `[x]`):
  - [x] SQLite

## Description
```bash
yarn add --dev https://try.gogs.io/netnr/Netnr.CodeBuilder.git
yarn add v1.0.1
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by miguel456** [comment]
Simply download the binary from gogs.io and run it.

**Comment by Fastidious** [comment]
Not related to `gogs`. You need to install `git`.
