### ISSUE TITLE
Basic functionality needs JavaScript

### ISSUE THREAD

**Issue by rambo-wears-a-pinky-thong** [gogits/gogs#4778]
- Gogs version (or commit ref):  dev
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

Gogs works more or less well without javascript, but there are some features that are not accessible because the top menu requires javascript. These are 

- create new organization
- create new mirror
- change user settings
- logout

could the menus on the top bar please  be replaced with CSS/HTML menus only?

**Comment by jorgesumle** [comment]
There are some dropdowns in the issue page and in the pull request page which don't work when JavaScript is disabled. The branch selectors don't work neither.

**Comment by rambo-wears-a-pinky-thong** [comment]
An easy solution for this is the `button:hover > .dropdown-menu { display: block; }` selector in a `<noscript/>` tag. Or alternatively with a hidden checkbox as shown [here](https://www.freakspot.net/barra-de-navegacion-de-bootstrap-sin-javascript-en.html).

**Comment by rambo-wears-a-pinky-thong** [comment]
If dropdown menus can be made to work with only CSS/HTML, it would be great. In general, removing as much javascript as possible is usually a good idea.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4780, please help test on `develop` branch or https://try.gogs.io.
