### ISSUE TITLE
JBOSS Developer Studio (Eclipse) can noy push GOGS repo 401 unathorized issue

### ISSUE THREAD

**Issue by emre141** [gogits/gogs#4783]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

GOGS Version:0.11.29 
Git Version:  2.14.1 windows
OS:Docker Container
Database:SQLite
JBOSS Dev Studio son versiın 11.0 
JGİT son version 4.8.0
EGİT 4.8.0

**Comment by mckaygerhard** [comment]
i tested same but in linux and works.. also this issue are bad made.. the template are not fill correctly

**Comment by emre141** [comment]
İ have test in it Windows 10 desktop and JBOSS Developer Studio 11.0 GA but failed every time clone is works fine.And when i change my repository to hidden and retry push again on JBOSS Developer Studio it works fine but when i rechange again it to public it did not work fine to pushing although i have already filled correct credential.

**Comment by emre141** [comment]
Hi,

Could you test in windows 10 on JBOSS Developer Studion or any other Eclipse base IDE ?

**Comment by Unknwon** [comment]
I think this is same as https://github.com/gogits/gogs/issues/4531 which both use JGit.
