### ISSUE TITLE
以docker方式安装，服务器重启后gogs界面打开不了

### ISSUE THREAD

**Issue by wjkang** [gogits/gogs#4784]
`134ffa22be80        gogs/gogs           "/app/gogs/docker/..."   7 hours ago         Up 3 minutes        0.0.0.0:3000->3000/tcp, 0.0.0.0:28367->22/tcp               gogs`
安装后是正常的，服务器重启后，容器也可以正常启动，但是界面就打不开了。
端口也是开放了的
`tcp6       0      0 :::3000                 :::*                    LISTEN      14114/docker-proxy`

**Comment by Fastidious** [comment]
好。 如果需要，请阅读说明并使用Google翻译（http://translate.google.com/）。 我已经做了！

**Comment by abmn614** [comment]
怎么解决的？

**Comment by wjkang** [comment]
@abmn614  重新安装，设置界面注意每个要填IP的地方，就是因为IP的问题

**Comment by abmn614** [comment]
谢谢，这个问题解决了。是我http端口配置的问题，应用端口应该填3000，我填了宿主机的端口导致的


Original Message
Sender:若邪notifications@github.com
Recipient:gogits/gogsgogs@noreply.github.com
Cc:abmn614dlming@foxmail.com; Mentionmention@noreply.github.com
Date:Tuesday, Jan 2, 2018 09:38
Subject:Re: [gogits/gogs] 以docker方式安装，服务器重启后gogs界面打开不了 (#4784)


@abmn614 重新安装，设置界面注意每个要填IP的地方，就是因为IP的问题
