### ISSUE TITLE
如何取消仓库地址前面的ssh前缀?

### ISSUE THREAD

**Issue by ccjeaty** [gogits/gogs#4787]
gogs安装好后, 创建的仓库地址是类似: `ssh://git@domain.com:3001/user1/test.git`

请问下像try.gogs.io 那种不以`ssh://`开始的址址是如何配置的呢? (直接以`git@domain:port`开始)

**Comment by Fastidious** [comment]
@ccjeaty 对不起，请按照模板上的说明进行操作，然后重试。 请问英文。^_^

**Comment by Unknwon** [comment]
ssh port 22.

**Comment by ccjeaty** [comment]
thanks.
