### ISSUE TITLE
wrong SSH Clone Link

### ISSUE THREAD

**Issue by vc12345679** [gogits/gogs#4788]
- Gogs version (or commit ref): 0.11.29.0727
- Git version: 2.11.0
- Operating system: Linux raspberrypi 4.9.41-v7+ #1023
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (SSH Clone Link on [TestRepo](https://try.gogs.io/MaxBosse/TestRepo))
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): Not necessary

## Description

1. For repositories which have __upper case__ letters in their names, the repo names in their SSH Clone Links should be in __lower case__, since the real directories have lower case names.
2. Using absolute path in SSH Clone Link will avoid the clone failure under following conditions:
    * using system ssh service
    * `setting.RepoRootPath` != home directory of `setting.RunUser`

e.g.
* `setting.RunUser = git`, its home directory is `/home/git`
* `setting.RepoRootPath = /home/git/gogs-repositories`
* a repo is in __`/home/git/gogs-repositories/username/reponame.git`__
* __Current__ SSH Clone Link is `git@AAA.com:username/reponame.git`, it actually aims at a __WRONG__ position of __`/home/git/username/reponame.git`__
* __Correct__ SSH Clone Link should be `git@AAA.com:/home/git/gogs-repositories/username/reponame.git`

**Comment by yorrd** [comment]
@vc12345679 has this not been included? I'm on a git dev branch installation and the repos are still upper case with a relative path

**Comment by Unknwon** [comment]
Please refer to https://discuss.gogs.io/t/how-to-config-ssh-settings/34.

**Comment by vc12345679** [comment]
@Unknwon Hi, I've read the reference you mentioned very carefully. It gives a very detailed instruction in ssh key settings. But it has nothing to do with this issue.
In order to use standalone ssh server, now I have to set the git user's home directory as the repository directory OR use the modifications as in this PR(https://github.com/gogits/gogs/pull/4789/files).
BTW, I closed this PR because I hadn't tested it with built-in ssh server configurations.

**Comment by Unknwon** [comment]
For whatever reason, use absolute path works, simply means it's wrong. Regardless of anything follows that.

**Comment by vc12345679** [comment]
* `setting.RunUser = git`, its home directory is `/home/git`
* `setting.RepoRootPath = /home/git/gogs-repositories`
* a repo is in __`/home/git/gogs-repositories/username/reponame.git`__

When the home directory differs with the `RepoRootPath`,

* __Current__ SSH Clone Link generated by Gogs is `git@AAA.com:username/reponame.git`, it works well with __built-in ssh server__
* But for __standalone ssh server__, the Link needs an extra relative path (e.g. `gogs-repositories`) as the prefix. It needs to be modified as `git@AAA.com:gogs-repositories/username/reponame.git`

What's worse, if the `RepoRootPath` were not even under the home directory, the SSH Clone Link with an absolute path is inevitable.

---
Just a suggestion
* for built-in ssh server, just keep the current SSH Link style
* for standalone server, use absolute path with lower case

@Unknwon

**Comment by Unknwon** [comment]
>But for standalone ssh server, the Link needs an extra relative path (e.g. gogs-repositories) as the prefix. It needs to be modified as git@AAA.com:gogs-repositories/username/reponame.git

No, since **Gogs delegates all incoming SSH** (by changing `authorized_keys` file), it know where to point for only given username and reponame.

I think you didn't understand the link I posted. SSH clone link shown on the web UI has NOTHING to do with home directory.

**Comment by vc12345679** [comment]
Ah! gotcha
