### ISSUE TITLE
push失败问题，如何解决

### ISSUE THREAD

**Issue by Acctina** [gogits/gogs#4790]
项目用着好好的，突然出现下面问题，可以pull无法push，push就报下面错误。
remote:Gogs: Internal error
![remote rejected] pre-receive hook declined

**Comment by bobdog1986** [comment]
我今天也遇到了这个问题。。。解决方案就是把gogs上面库删了，然后新建一个空的，再推上去。。。

**Comment by TELstatic** [comment]
> 项目用着好好的，突然出现下面问题，可以pull无法push，push就报下面错误。
> remote:Gogs: Internal error
> ![remote rejected] pre-receive hook declined

建议检查下数据库配置
我出现了同样的问题。
因为改了密码，Gogs 配置没修改。
