### ISSUE TITLE
Allow "Rebase and merge" in pull requests

### ISSUE THREAD

**Issue by InExtremaRes** [gogits/gogs#4798]
## Description

At least at version `0.11.29.0727` a pull request can only be merged as a `git merge --no-ff` command. GitHub, for instance, allows _Squash and merge_ and _Rebase and merge_. Rebase and merge are very useful when project teams seek a clean, linear history.

With this feature a _topic branch_ should be rebased on top of the _default branch_ and then merged using the fast forward option.

[More info about GitHub rebase and merge](https://github.com/blog/2243-rebase-and-merge-pull-requests)

**Comment by Unknwon** [comment]
It is now possible on `develop` branch, you can also test on https://try.gogs.io.

Settings:
![image](https://user-images.githubusercontent.com/2946214/32874713-f538dabe-ca61-11e7-980c-e91542ff4764.png)

Merge options:
![image](https://user-images.githubusercontent.com/2946214/32874732-0ec299f2-ca62-11e7-9853-773709518579.png)

**Comment by LukeSchoen** [comment]
Is there any way to enable setting this as the default behavior ? (as our team ALWAYS prefers rebase)
