### ISSUE TITLE
局域网搭建了Gogs共享文件,一直clone 失败！

### ISSUE THREAD

**Issue by oahzuw** [gogits/gogs#4800]
局域网搭建了Gogs共享文件，用户70 ,文件在几十M时clone没有问题，当文件超过100M时速度很慢，文件超过1G时，同时只能一个用户clone 或pull，超过一个其他的用户就clone失败，跟踪内存使用量，消耗完时，就是失败时，服务器配置： 16G内存，i5-7400，硬盘西数1T

**Comment by CuBiC3D** [comment]
Please use English language, my Browser can't even show the symbols you used.

**Comment by oahzuw** [comment]
@CuBiC3D 

LAN set up a Gogs shared files, the user 70, the file in the dozens of M clone no problem, when the file is more than 100M when the speed is very slow, the file more than 1G, while only one user clone or pull, more than one other users clone Failure, tracking memory usage, consumption is complete, it failed, the server configuration: 16G memory, i5-7400, hard disk Western Digital 1T

sorry for my bad english, use google translate!
