### ISSUE TITLE
docker 重新安装gogs 原数据如何解决？

### ISSUE THREAD

**Issue by libra1010** [gogits/gogs#4804]
如果使用docker方式安装gogs
在docker rm 以后，重新run 一个gogs,映射数据目录在原始数据目录
这个时候，就启动不成功 ，一直出现
![image](https://user-images.githubusercontent.com/9667153/30999506-27223086-a508-11e7-8591-f117faca1de4.png)

**Comment by raphaelsoul** [comment]
map host directory to container directory, just like offical mysql docker images. 
alternatively you can use database in host via `docker-compose`

**Comment by Unknwon** [comment]
Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
