### ISSUE TITLE
All RAM and CPU are consumed when commit to gogs server

### ISSUE THREAD

**Issue by wildtang** [gogits/gogs#4806]
- Gogs version (or commit ref): 0.11.29.0727
- Git version: 
- Operating system: CentOS 7.4 with Docker Version: 17.09.0-ce, Storage Driver: overlay
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Last year, We begun running a Gogs server(0.9.x) with docker,  recently we plan to upgrade the Gogs the newest version and begin use HTTPS,

We first modify the app.ini as below:
```
APP_NAME = Gogs: Go Git Service
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = sqlite3
NAME     = gogs
USER     = root
PASSWD   = 
SSL_MODE = disable
PATH     = /data/gogs/data/gogs.db

[repository]
ROOT = /data/git/gogs-repositories

[server]
PROTOCOL = https
DOMAIN       = mydomain.com
HTTP_PORT    = 3000
ROOT_URL     = %(PROTOCOL)s://%(DOMAIN)s:3000/
CERT_FILE = /data/cert/cert.pem
KEY_FILE  = /data/cert/key.pem
TLS_MIN_VERSION = TLS10
DISABLE_SSH  = false
SSH_PORT     = 22
OFFLINE_MODE = false
ENABLE_GZIP = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = true
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = true

[picture]
DISABLE_GRAVATAR = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /app/gogs/log

[log.file]
; leave empty to inherit
LEVEL =
; This enables automated log rotate (switch of following options)
LOG_ROTATE = true
; Segment log daily
DAILY_ROTATE = true
; Max size shift of single file, default is 28 means 1 << 28, 256MB
MAX_SIZE_SHIFT = 28
; Max line number of single file
MAX_LINES = 100000
; Expired days of log file (delete after max days)
MAX_DAYS = 21

[security]
INSTALL_LOCK = true
SECRET_KEY   = Ooeffo7i8w66646

[i18n]
LANGS = en-US,zh-CN
NAMES = English,简体中文

; Used for datetimepicker
[i18n.datelang]
en-US = en
zh-CN = zh

```

Then we run the new gogs docker with command below:
    docker run -d --name gogs \
    -h c-gogs \
    -p 30001:22 \
    -p 3000:3000 \
    -v /mnt/datadisk/gogs:/data \
    -v /etc/timezone:/etc/timezone \
    -v /etc/localtime:/etc/localtime \
    gogs/gogs:0.11.29

Almost everything was fine, we can login with the existing gogs user, we can pull the git repo, we can create new git repo, but when we modify some files of a git repo then commit/push them, git client has no response for a long time, and we found the gogs server became very very slow, use top command we can see the RAM and CPU are all almost consumed, and there were a lot of gogs processes launched.

And, And If we modify the PROTOCOL from https to http in app.ini, we can commit/push the modified files to gogs server successfully. Can anyone tell us where is the problem? Thanks.

P.S. Our https cert is generated by the command below:
/app/gogs/gogs cert -ca=true -duration=87600h0m0s -host=myhost.example.com

**Comment by wildtang** [comment]
After we modified the protocol to http and ran for some hours with about 20 users access, the gogs container also consumed all ram and cpu...

**Comment by Unknwon** [comment]
Please show stats given by admin dashboard. Other sources are not believed ATM.
