### ISSUE TITLE
Gogs bug tracker uploading images does not work

### ISSUE THREAD

**Issue by cloverbox** [gogits/gogs#4809]
- Gogs version (or commit ref): 
I apologize for not following the format but this issue has arrisen through a one click install of gogs into sandstorm
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

I apologize for not following the format but this issue has arrisen through a one click install of gogs into sandstorm.

I am not sure where these sandstorm bugs should be filled. I think this is a big reason that there are so many small problems with the sandstorm platform ( not your fault of course ).

Is there a place to file bugs to your team that is better if it is a sandstorm platform?

Well here is the issue. It does seem more like their problem then yours. 

![screenshot 2017-10-03 at 8 39 52 am](https://user-images.githubusercontent.com/12082628/31125662-094caf48-a817-11e7-9085-b49254221e57.png)

...

**Comment by Unknwon** [comment]
Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by cloverbox** [comment]
How do I even submit this issue?
