### ISSUE TITLE
Chinese translation error in issues page

### ISSUE THREAD

**Issue by ckj996** [gogits/gogs#4811]
- Gogs version (0.11.29.0727): 
- Git version: Not relevant
- Operating system: Not relevant
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/ZeroNet/ZeroNet-brokenmirror/issues/1)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Sign in to join this conversation. 

![Screenshot from 2017-10-04 18-40-21.png](https://ooo.0o0.ooo/2017/10/04/59d4bab02c46b.png)

登**陆** 并参与到对话中。 

should be 

登**录** 并参与到对话中。 

like at the top right

![Screenshot from 2017-10-04 18-42-30.png](https://ooo.0o0.ooo/2017/10/04/59d4bb21d42e3.png)

**Comment by chliang** [comment]
哈哈
