### ISSUE TITLE
PUSH Problem! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by MIngPAPA** [gogits/gogs#4814]
- Gogs version (or commit ref): 0.11.29
- Git version:  1.8.3.1
- Operating system: Centos 7.2
- Database :
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ x] Not relevant      Everything runs Perfectly

## Description
There are some similar questions in the Issues, but there is no clear solution to the question!
I just built the gogs service in the LAN and wanted to push my code to the gogs server.

```
$ git push
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 264 bytes | 264.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Gogs: Internal error
To http://192.168.3.77:3000/XXX/test-push.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://192.168.3.77:3000/XXX/test-push.git'
```
I have also tried `git push -u orign master`. It didn't work as well.

However, when it goes to the web page, the upload push works very well!

Here is the pre-recieve.log in ~/gogs/log/hooks/
---
```
2017/10/07 14:56:40 [FATAL] [...its/gogs/cmd/hook.go:100 runHookPreReceive()] GetProtectBranchOfRepoByName [repo_id: 6, branch: master]: no such table: protect_branch
```
I  did nothing to the option of protect branch on the web page!

Here is my app.ini 
---
[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = root
PASSWD   =
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[server]
DOMAIN           = 192.168.3.77
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.3.77:3000/
DISABLE_SSH      = true
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = true

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = false

**Comment by MIngPAPA** [comment]
I found the problem finally!
It is similar with this [problem](https://discuss.gogs.io/t/gogs-ignores-app-data-path-from-custom-conf-app-ini/982)
---
It blames to the Database Path! As to me, I use the SQlite. The default database path is  **data/gogs.db** , which is a sub-dir of gogs installation path. The genuine path is /home/git/data(The user git as default).

Just change the PATH=/Your database path/  in the [database] block in gogs/custum/conf/app.ini

**Comment by curiousmuch** [comment]
Thank you!

**Comment by DieZahnfee** [comment]
Thank you very much! This problem made me almost go crazy.

**Comment by jarrodquan** [comment]
Thanks.
