### ISSUE TITLE
Windows Client - Empty Reply From Server, but all works with Ubuntu Client

### ISSUE THREAD

**Issue by julien95h** [gogits/gogs#4815]
- Gogs version (or commit ref): 0.11.29.0727
- Git version: 2.1.4
- Operating system: Raspbian (Raspberry Pi 3)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`): Not logged

## Description

I use Gogs on my Raspbbery Pi 3 with a Nginx server and a reverse-proxy.
My git URL is as follow : https://git.myserver.com/
The reverse-proxy use HTTPS and Gogs configured as HTTP, as recommended in the documentation.
Gog configuration  : https://pastebin.com/kwvbMdYx
Nginx configuration : https://pastebin.com/Y0Ny6hyA

All works (commit, push, pull...) with my computer with Ubuntu 17.4.
But not with my computer with Windows 7 (git 2.14.2), I have the following error :
fatal: unable to access 'https://git.myserver.com/user/repo.git/' : Empty reply from server.

I think it's not a configuration problem but really a bug.

**Comment by rimkov** [comment]
hello
same thing here but with a Debian git client (command line) and the first Raspberry pi with gogs 0.9
i updated gogs to 0.11 but it's the same i can not push something or even get origin information (git remote show origin) : "Empty reply from server"

Gogs configured as HTTP
