### ISSUE TITLE
500 error on Repo home

### ISSUE THREAD

**Issue by Rahulsharma0810** [gogits/gogs#4816]
- Gogs version (or commit ref):  **0.11.29.0727**
- Git version: 1.8.3.1
- Operating system:  Centos 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):

```
2017/10/09 10:52:34 [TRACE] Session ID: 70f5c3a73f84816f
2017/10/09 10:52:34 [TRACE] CSRF Token: Q-ffB7kiDH9u2ngi37bTlgaaGzE6MTUwNzUyNjEwOTAzNjc0OTg2NA==
2017/10/09 10:52:34 [ERROR] [...g/context/context.go:171 ServerError()] GetBranches: exit status 1
2017/10/09 10:52:34 [TRACE] Template: status/500
```

## Description

I created a repo yesterday and it was working fine, but today after restarting machine, I am getting 500 Error on Repo home page **http://myadomain:3000/user/myrepo**

![screen shot 2017-10-09 at 10 57 43 am](https://user-images.githubusercontent.com/9934859/31325996-d9d3feb4-ace0-11e7-93e8-6639be89ba12.png)

I created another repo with same user and it is working fine

**Comment by variablenix** [comment]
I would check the repo files on the filesystem. It sounds like they are gone or not located in the expected place. Check the shell history and if you can reproduce the problem with a different user after restarting.

**Comment by Unknwon** [comment]
Try upgrade then test again.
