### ISSUE TITLE
Permission based on Roles

### ISSUE THREAD

**Issue by hubyhuby** [gogits/gogs#4818]
It would make more sens to set the permission as in Gitlab based on roles : 
Guest/ reporter/ Developper / Master.

The read/ write thing in gogits makes sens on a developper perspective (when you are in the code) 
But for a user, we are talking about it s role in the organisation (which is not to read x) )
And having read write at the same level as admin...doesn t make sens either. Since read is a granular permission (read what???) and admin a role x)

**Comment by Unknwon** [comment]
I think this is basically same as https://github.com/gogits/gogs/issues/1743.
