### ISSUE TITLE
Fail to initialize ORM engine: migrate: do migrate - write hook file on Windows 10

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [gogits/gogs#4826]
- Gogs version (or commit ref): `0.11.29` (https://github.com/gogits/gogs/commit/b1100b5e345a8a6f5e3f3dfd19e18c9cc8b499e8)
- Git version: `git version 2.14.2.windows.3`
- Operating system: `Windows 10`
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2017/10/14 15:43:38 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: 
write hook file 'H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive': 
open H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive: 
Das System kann den angegebenen Pfad nicht finden.
```

----

## Description
> Further discussion from https://github.com/gogits/gogs/issues/4677#issuecomment-336646319.

@Unknwon After I upgraded to **`git version 2.14.2.windows.3`** I get this error:

```
2017/10/14 15:43:38 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: 
write hook file 'H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive': 
open H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive: 
Das System kann den angegebenen Pfad nicht finden.
```

*(PS: The German sentence `Das System kann den angegebenen Pfad nicht finden.` means `The system cannot find the indicated path.`)*

**Comment by Unknwon** [comment]
Hi,

do you actually have this file on your disk?

>H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive

**Comment by SuriyaaKudoIsc** [comment]
No. I created a mirror of `dart-lang/sdk.git` but the folder `sdk.git` doesn't exist.

**Comment by Unknwon** [comment]
So... I think you need to delete this repository record from your database table “repository”.

You’ll need to first use “dart-lang” to find user ID and combine with this user ID and name “sdk” to find and delete the record.

Then restart Gogs.

**Comment by SuriyaaKudoIsc** [comment]
> ✅ Fixed.

@Unknwon Thank you! It works now. 😄

**Comment by z2z** [comment]
2019/01/21 12:44:37 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: write hook file '/data/git/gogs-repositories/my_projects/docscanner.git/hooks/pre-receive': open /data/git/gogs-repositories/my_projects/proj.git/hooks/pre-receive: no such file or directory
