### ISSUE TITLE
Unable to use email as username for ldap authenrication

### ISSUE THREAD

**Issue by cyberb** [gogits/gogs#4827]
Unable to use email as username, failed to authenticate with the following error:

Failed to login 'gogs_user@syncloud.it' via 'syncloud': Invalid pattern for attribute 'username' [gogs_user@syncloud.it]: must be valid alpha or numeric or dash(-_) or dot characters

- Gogs version: 0.11.29

**Comment by Fastidious** [comment]
Yes, that is as per design.

**Comment by cyberb** [comment]
Are you saying that username should never be an email in ldap?

**Comment by Fastidious** [comment]
@cyberb no, I am saying usernames on `gogs` can't be emails. Not sure about LDAP.

**Comment by cyberb** [comment]
Any reasons behind this restriction?

**Comment by Fastidious** [comment]
@cyberb that will have to answered by @Unknwon. :-(

**Comment by Unknwon** [comment]
The restriction was added in favor of https://github.com/gogits/gogs/issues/2709. But I think we can verify for either username or email address, if LDAP doesn't care.

**Comment by san-** [comment]
It's important to allow login with e-mail as LDAP username.

**Comment by variablenix** [comment]
LDAP authentication with a username or email address works fine. I think the original question was phrased incorrectly.

**Comment by cyberb** [comment]
I am using email as username and gogs fails with this error which clearly says you are not supposed to use symbols like @ in username.
Does this check not fail when you do the same?
Are you using special ldap filed mapping rules?

**Comment by chrisipa** [comment]
+1

**Comment by variablenix** [comment]
> Are you using special ldap filed mapping rules?

No. I meant logging in with the mail address defined by the `mail` attribute allows login. I see what you're saying now - with the actual `uid` being in an email format.

**Comment by cyberb** [comment]
I am sorry it is still unclear to me.
Are you saying that if I map gogs username to ldap mail field gogs will not trigger this check?
And if map username to cn (which contains email) it will fail the check?
Here is the mapping I use: http://artifact.syncloud.org/gogs/ci/103-sam-amd64/screenshot/ldap-auth.png
Here is the code which does that:
https://github.com/syncloud/gogs/blob/master/hooks/gogs_hooks.py#L237

**Comment by variablenix** [comment]
I'm saying that a `uid` should be in the form `cyberb`. A `cn` should not contain an email address. This is what the `mail` attribute is for. From your settings page have you tried making the `username` attribute `uid` rather than `cn`? If your name is John Doe, the Common Name or `cn` should just be the first name, like `cn=John`. 

For the username filter why not match both `inetOrgPerson` *and* `uid`? 

`(&(objectClass=inetOrgPerson)(uid=%s))`

**Comment by ThirtySomething** [comment]
I'm using German as UI language. In the field "Username Attribute" a hint is displayed: "Leave blank to use the value from the login form as a user name." In your screenshot I can see that there is "cn" used. Maybe you try with an empty username attribute?

**Comment by cyberb** [comment]
@variablenix 
Maybe our LDAP setup is not correct but currently we save username in few ldap fields like (uid, cn) and we do not really know what form of username users will use. So sometimes it is simple username sometimes it is email. Probably we should fix that.
https://github.com/syncloud/platform/blob/master/config/ldap/init.ldif

Also I have fixed the matching and it is 'and' now, thanks.

@ThirtySomething 
Tried removing username attribute, but still getting login error.
https://github.com/syncloud/gogs/blob/master/hooks/gogs_hooks.py#L237

````
017/10/27 18:14:45 [TRACE] Search for LDAP user: gogs_user@syncloud.it
2017/10/27 18:14:45 [TRACE] LDAP: Bound as BindDN: dc=syncloud,dc=org
2017/10/27 18:14:45 [TRACE] LDAP: Searching for DN using filter '(&(objectclass=inetOrgPerson)(uid=gogs_user@syncloud.it))' and base 'ou=users,dc=syncloud,dc=org'
2017/10/27 18:14:45 [TRACE] Binding with userDN: cn=gogs_user@syncloud.it,ou=users,dc=syncloud,dc=org
2017/10/27 18:14:45 [TRACE] Bound successfully with userDN: cn=gogs_user@syncloud.it,ou=users,dc=syncloud,dc=org
2017/10/27 18:14:45 [TRACE] Fetching attributes '', '', '', 'mail', '' with filter '(&(objectclass=inetOrgPerson)(uid=gogs_user@syncloud.it))' and base 'cn=gogs_user@syncloud.it,ou=users,dc=syncloud,dc=org'
2017/10/27 18:14:45 [TRACE] Checking admin with filter '(objectClass=inetOrgPerson)' and base 'cn=gogs_user@syncloud.it,ou=users,dc=syncloud,dc=org'
2017/10/27 18:14:45 [ WARN] Failed to login 'gogs_user@syncloud.it' via 'syncloud': Invalid pattern for attribute 'username' [gogs_user@syncloud.it]: must be valid alpha or numeric or dash(-_) or dot characters
````

**Comment by cyberb** [comment]
I made few changes to our ldap and replaced cn with uid and made sure cn never contains email. Looks like uid is better container for "usernames" no matter what they contain.
That fixed the problem.
Thank you for the advices.
