### ISSUE TITLE
[ldap] unable to create initialized repo

### ISSUE THREAD

**Issue by cyberb** [gogits/gogs#4829]
I am trying to use ldap integration but creating an initialized repo fails with the following error message:

[…/routes/repo/repo.go:102 handleCreateError()] CreatePost: initRepository: initRepoCommit: git commit: fatal: --author '‘gogs_user’ is not 'Name ’ and matches no existing author 2017/10/17 14:24:48 [TRACE]

I have set attribute_mail and I have valid email coming from ldap and I can see it on users page.

Gogs version: 0.11.29

http://artifact.syncloud.org/gogs/ci/100-sam-amd64/screenshot/users.png

**Comment by ThirtySomething** [comment]
I've done a successfully LDAP configuration to an Active Directory Server allthough I'm not an expert for LDAP. I've used [Apache Directory Studio](http://directory.apache.org/studio/) to fiddle out the correct LDAP settings. This might help you, too.

**Comment by cyberb** [comment]
After changing a little bit our ldap structure now I have these ldap fields:
cn: gogs_user (mapped to username)
email: gogs_user@syncloid.it (mapped to email)

Still cannot create initial commit (probably any commit from web UI) with this error:

 2017/11/03 23:00:45 [ERROR] [.../routes/repo/repo.go:102 handleCreateError()] CreatePost: initRepository: initRepoCommit: git commit: fatal: --author ''gogs_user' is not 'Name <email>' and matches no existing author 2

Looks like gogs is not properly creating author for git.
Here is the user page:
http://artifact.syncloud.org/gogs/ci/111-sam-amd64/screenshot/user.png

**Comment by cyberb** [comment]
Sorry that was my git wrapper problem:
https://github.com/syncloud/3rdparty/commit/d94a12719d77e7bcf5246439a621d60c04189a66

**Comment by elico** [comment]
@ThirtySomething Can you share some of your configuration?
I managed to configure LDAP against Active directory but I am yet to be able to search a user as a memeber of a specific group.

**Comment by cyberb** [comment]
Here is gogs client ldap conf: https://github.com/syncloud/gogs/blob/0cdd03799d02b2b521c81e20f923f9e9c53a730d/hooks/gogs_hooks.py#L224
Here is openldap server conf: https://github.com/syncloud/platform/blob/master/config/ldap/init.ldif
