### ISSUE TITLE
Meta tag go-import does not response correct value

### ISSUE THREAD

**Issue by giter** [gogits/gogs#4832]
go get golang.org/x/image/bmp

=>

![tim 20171020175112](https://user-images.githubusercontent.com/1682298/31815464-5351d09a-b5bf-11e7-89cb-21d56a94430d.png)

=>

![tim 20171020175214](https://user-images.githubusercontent.com/1682298/31815596-b924eee8-b5bf-11e7-8877-19211c10ac1b.png)

**Comment by giter** [comment]
@Unknwon

**Comment by Fastidious** [comment]
I wish I could help you, but with what you have provided, not even wearing my tin foil hat I can figure it out! ☺️

**Comment by giter** [comment]
@Fastidious  thanks ,  I've explained this issue to @Unknwon

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by giter** [comment]
Do you have RELEASE date for v0.12? @Unknwon

**Comment by Unknwon** [comment]
@giter 0.12 would take a long way to carry out, but I think I can release another 0.11.x over the weekday.
