### ISSUE TITLE
try.gogs.io -- All repositories gone, dashboard empty

### ISSUE THREAD

**Issue by Avispa** [gogits/gogs#4837]
Not sure if this post is correct here but it is where the 404 page directed me to. (Had a quick look through other issues.)

Had (at least) one repository on **try.gogs.io** but it is simply vanished. As topic says not only the dashboard is empty *also* the repo itself is gone. Simple deduction by `git ls-remote` -> `fatal: repository 'https://try.gogs.io/myname/xxx.git/' not found`. As I can see from `git log` at least last push was 2017-05-25 17:07:40 +0200. Maybe it is related to #4830.

**Comment by alexanderadam** [comment]
It's [written in the readme in #2 that data will be reset](https://github.com/gogits/gogs#important-notes) every now and then.

**Comment by Fastidious** [comment]
@alexanderadam that is not the case, all my repos on `try` are fine. Care to explain more, @Avispa? Why did you deleted the template, instead of following the instructions it asked for? What is your `gogs` URL on `try`?

**Comment by Avispa** [comment]
@Fastidious: Sorry, was in holidays. For privacy reasons I would prefer not to post my gogs identity. Is there any other way I can help to figure that out?
To be honest it looks a bit deleted to me. Is there any possible reason it could be deleted on purpose? Is there any expiration date I've missed maybe?

**Comment by Fastidious** [comment]
@Avispa I can't provide much help;. The repos at `try`, and `try` itself are to show `gogs`, but it is bound to break here and there, as development progresses. That might be the case. If you do not see the repo on the web, then it might really be gone.

Cheers!

**Comment by Unknwon** [comment]
Periodically, repository exceeds 50-100mb will be deleted to save server disk usage. I think that's the case. Sorry about any confusion caused.
