### ISSUE TITLE
REQUIRE_SIGNIN_VIEW isn't being enforced

### ISSUE THREAD

**Issue by cdfuller** [gogits/gogs#4841]
- Gogs version (or commit ref): 0.11.30.1014
- Git version: 2.11.3
- Operating system: Docker image 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant / Need admin access
- Log gist (usually found in `log/gogs.log`): N/A

## Description
I checked REQUIRE_SIGNIN_VIEW when first installing but it doesn't seem to be having any effect. The setting is enabled in /data/gogs/conf/app.ini and in the admin configuration panel on the site. 

When I browse the site from an incognito browser I'm still able to view users and repositories. I expected to be redirected to the sign in page. Please let me know if my understanding of this feature's behavior is flawed.

**Comment by Unknwon** [comment]
Hi, hmm. Right, you would have to restart in order to make this specific option work.

Duplicated to https://github.com/gogits/gogs/issues/2365.
