### ISSUE TITLE
crash when merging

### ISSUE THREAD

**Issue by xcstream** [gogits/gogs#4844]
- Gogs version (or commit ref): 0.10.18.0313
- Git version:  2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb557b6]

goroutine 6734 [running]:
github.com/gogits/gogs/models.(*Repository).getOwner(0x0, 0x16f0600, 0xc420283d60, 0xc4216969c0, 0x36)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:273 +0x26
github.com/gogits/gogs/models.(*Repository).mustOwner(0x0, 0x16f0600, 0xc420283d60, 0xc4212703a8)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:286 +0x43
github.com/gogits/gogs/models.(*Repository).repoPath(0x0, 0x16f0600, 0xc420283d60, 0x2, 0x2)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:415 +0x43
github.com/gogits/gogs/models.(*Repository).RepoPath(0x0, 0x44, 0xc421689d08)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/repo.go:419 +0x43
github.com/gogits/gogs/models.(*PullRequest).PushToBaseRepo(0xc421270380, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/pull.go:572 +0x152
github.com/gogits/gogs/models.addHeadRepoTasks(0xc4222ffeb0, 0x1, 0x2)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/pull.go:652 +0x165
github.com/gogits/gogs/models.AddTestPullRequestTask(0xc420178600, 0xc, 0xc421945570, 0x7, 0xc42183e500)
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/pull.go:698 +0x709
created by github.com/gogits/gogs/models.(*PullRequest).Merge.func1
	/home/vagrant/gopath/src/github.com/gogits/gogs/models/pull.go:190 +0xc3

**Comment by pgleghorn** [comment]
This was reported to me also, with same stack trace (ending in getOwner), though I didn't witness the exact replication steps. Do you know what steps caused it in your case?

**Comment by Unknwon** [comment]
@pgleghorn can you give more info with a formal issue report?

**Comment by pgleghorn** [comment]
Have raised https://github.com/gogits/gogs/issues/4883 for my report, thx.
