### ISSUE TITLE
how to add cdn services?

### ISSUE THREAD

**Issue by kybom** [gogits/gogs#4848]
**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 0.11.29.0727
- Git version: 2.7.4
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

...Since open  my gogs homepage slowly, I wan to use cdn to storage the static files(like css,js,png). How to configure?

**Comment by Unknwon** [comment]
You can use offline mode.
