### ISSUE TITLE
Gogs markdown table preview issue

### ISSUE THREAD

**Issue by bobdog1986** [gogits/gogs#4849]
I've write a README.md which has a table and it works in visual code preview! But in gogs doesnot work well!
Follows are gogs preview, markdown file content, vs code preview screenshots:
![gogs_table_error_display](https://user-images.githubusercontent.com/9330555/32163397-22b17bc2-bd97-11e7-86e7-d9c22c6f18eb.jpg)
![gogs_table_md](https://user-images.githubusercontent.com/9330555/32163400-24550034-bd97-11e7-9fed-970889acaed8.jpg)
![gogs_table_preview_vscode](https://user-images.githubusercontent.com/9330555/32163402-2522c6b8-bd97-11e7-9467-dd1ffb471401.jpg)

**Comment by Fastidious** [comment]
Use:

```
| Header 1 | Header 2  |  Header 3  |
| -------- | --------- | ---------- |
| row1     | content1  | content2   |
| row2     | content3  | content4   |
```

**Comment by bobdog1986** [comment]
Solve this issue afte align column width by add numbers of  '-' !

**Comment by olets** [comment]
Fyi three `-` is the minimum, the start and end `|` are optional, and whitespace isn't counted. Use @Fastidious's solution if you care about legible Markdown. If you only care about rendered HTML you can do

```markdown
Header 1 | Header 2 | Header 3
--- | --- | ---
row1 | content1 | content2
row2 | content3 | content4
```

**Comment by bobdog1986** [comment]
Thankyou! @olets  I had already found that three is the minimum yet.
