### ISSUE TITLE
Different domain settings for SSH and HTTP

### ISSUE THREAD

**Issue by Kamairo** [gogits/gogs#4852]
Hi,

I would like to know if it is possible to support different domains for SSH and HTTPS.
My problem is the following:
I have gogs running on a raspberry pi at home, that only gets an IPv6 address with a DS lite tunnel from my provider.
So, I need to run a portmapper to reach this IPv6 address from the outside from an IPv4 address.
So far so good, the problem now is, that I get an URL and a port from the portmapper provider for each port I open.
I.e.:
Port 443 on my gogs server is now mapped to: ``somegivenhost:1234``
Port 22 on my gogs server is now mapped to: ``somegivenhost:5678``

I now configured Apache to reverse proxy ``127.0.0.1:3000`` to ``/git`` with SSL (that works fine).
And I am also able to reach gogs from the outside using ``https://somegivenhost:1234/git``.

The problem I am now having is that I have to configure the server DOMAIN as ``https://somegivenhost:1234``, i.e. including the port. Now if I click on a repository the https clone address will be correct. However if I edit the SSH port to be 5678, the SSH clone address still includes the port that maps to 443, i.e. 
``ssh://git@somegivenhost:1234:5678/User/Repository.git``
but
``ssh://git@somegivenhost:5678/User/Repository.git``
would be correct and it works.

So, can you add a config parameter to configure the domain name for http(s) and ssh seperately?

**Comment by Kamairo** [comment]
Acutally, this feature is already implemented. I looked a bit through the code and there is an undocumented config parameter called ``SSH_DOMAIN``, which does exactly what I need. 

So, the request changes to: "Please add this to the documentation, e.g. the config cheat sheet".

**Comment by Manouchehri** [comment]
Thanks, was trying to figure out how to do this well. I'll add it to the documentation if no one else does soon.
