### ISSUE TITLE
show the history of issue label change 

### ISSUE THREAD

**Issue by xu4wang** [gogits/gogs#4854]
- Gogs version (or commit ref):  0.11.29.0727 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Is it possible to record/show the event when the issue was added a new label?
At the moment, we can see the labels of each issue, but are not able to see who/when the label was added.

**Comment by xu4wang** [comment]
Checking the implementation, looks like the label change history is not recorded in the data base. 

Suggest to add a comment automatically whenever a label is added/deleted.
By doing so, we will be able to track the label change history by checking the comments.

**Comment by Unknwon** [comment]
Hi, duplicated to https://github.com/gogits/gogs/issues/2520.
