### ISSUE TITLE
GOGs fails with 504 while accessing /admin[Admin Panel]

### ISSUE THREAD

**Issue by sukhada369** [gogits/gogs#4868]
- Gogs version (or commit ref): 0.9.113
- Git version: 1.8.3.1
- Operating system: CentOS 7.3
- Database
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

Workaround: 
I have nginx running in front of GOGs server. I increased the timeout period.
Output of nginx access log:
```
x.x.x.x - - [14/Nov/2017:07:20:19 +0000] "GET /admin HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
```

**Comment by sukhada369** [comment]
Is there any update on this issue?

**Comment by Unknwon** [comment]
Upgrade Gogs... surely..
