### ISSUE TITLE
Wrong branch url in branches view

### ISSUE THREAD

**Issue by DarkAtra** [gogits/gogs#4874]
- Gogs version (or commit ref): 0.11.30.1014
- Git version: 2.1.4
- Operating system: Raspbian GNU/Linux 8 (jessie)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/DarkAtra/test/branches
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): not relevant

## Description
If the branch name contains a # (hashtag) the url in the branch view is wrong.
Open [https://try.gogs.io/DarkAtra/test/branches](https://try.gogs.io/DarkAtra/test/branches) and click on the #test branch (Active Branches). I think this issue does apply to other special chars as well but i did not test it yet.
This also applies to the "New Pull Request" Button url.

## Solution
Encode the url just like you already did for the branch <select> at [https://try.gogs.io/DarkAtra/test](https://try.gogs.io/DarkAtra/test).

**Comment by kaajavi** [comment]
## Solution

Encode the url just like you already did for the branch at ~~https://try.gogs.io/DarkAtra/test~~ **https://try.gogs.io/DarkAtra/test/src/%23test**.

**Comment by DarkAtra** [comment]
The same is happening in settings: https://try.gogs.io/DarkAtra/test/settings/branches.
If you try to select a branch with special chars in the select (Protected Branches ) it breaks the functionality.

You should check that every single link or dropdown encodes the special chars correctly.

**Comment by danowar2k** [comment]
Probably same issue: #4601 #4685

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/DarkAtra/test/branches.

**Comment by DarkAtra** [comment]
Still not working on https://try.gogs.io/DarkAtra/test/settings/branches/#test when selecting #test as branch for Protected Branches. All other cases seem to be fixed.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by DarkAtra** [comment]
looks good
