### ISSUE TITLE
Error "This pull request can't be merged automatically because there are conflicts" on a pull request that should not have any conflicts

### ISSUE THREAD

**Issue by pgleghorn** [gogits/gogs#4875]
- Gogs version (or commit ref): 0.11.29.0727 
- Git version:  2.8.3.windows.1
- Operating system: Gogs on Windows 2012, 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): 
Here is an extract
[gogs_log_extract.txt](https://github.com/gogits/gogs/files/1478933/gogs_log_extract.txt)

## Description

I'm getting the error "This pull request can't be merged automatically because there are conflicts. "
on a pull request. However the fork is brand new, the commit is very simple (one line change) and no other users are working.

1. Created a fork of otheruser/otherrepo
2. In my fork, created a one line change to a file, created branch "feature-test" and a pull request from this (all done in the gogs UI). 
3. Newly created pull request shows the error above

I've searched for this, but other hits suggest another user snuck a change between the fork creation and the pull request creation, which isn't the case here. N.B. I am logged in as admin.

...

**Comment by pgleghorn** [comment]
This seems to be the underlying error from the gogs.log, when the pull request is created:

```
2017/11/16 12:45:53 [TRACE] PullRequest[0].testPatch (patchPath): C:\Users\devsvcvsu\gogs-repositories\james\sparse-6.1.git\pulls\3.patch
2017/11/16 12:45:56 [TRACE] PullRequest[0].testPatch (apply): has conflit
error: patch failed: client/src/lbgtk/StringUtils/case_conv.cpp:1
error: client/src/lbgtk/StringUtils/case_conv.cpp: patch does not apply
2017/11/16 12:45:56 [TRACE] PushToBaseRepo[12]: pushing commits to base repo 'refs/pull/3/head'
2017/11/16 12:45:57 [TRACE] Pull request created: 12/7
```

**Comment by Unknwon** [comment]
Hi, recently another user reported a similar issue that was caused by EOL CLRF, are you developing on Windows?

**Comment by pgleghorn** [comment]
Yep indeed, files are originating on windows. I had suspected this was a factor and tested files with / without CRLF but the result was the same.

However I had a mini-breakthrough, this seems not to be a gogs issue after all. I found that some source files contain spurious invisible binary chars at the start of the file. It shows up in "vim -b" as 

<feff>

I confirmed by testing that removing the binary chars on a file allowed a pull request change on that file to go through, whereas previously it had failed with the "conflict" error. It seems that conflict error is thrown by the git-apply command in gogs, which is running patch command, and that is just struggling to cope with the binary chars. Various post/googles on that error from the patch command affirm that ignoring whitespace in patch command tends to bypass the issue.

I suppose Gogs could also use a similar workaround with ignoring whitespace in git-apply, but I suppose that is not ideal. In our case we will need to find & fix all these files, and understand what caused the binary chars to appear.

**Comment by pgleghorn** [comment]
Aha, its the BOM Byte order mark!
the hex chars are EF BB BF

https://msdn.microsoft.com/en-us/library/cc295463.aspx
Thanks Microsoft for introducing this wonderful weirdness.

Maybe gogs does need a convenient switch to safely deal with these, since it seems that they may be unavoidable for windows developers..

**Comment by Unknwon** [comment]
>I suppose Gogs could also use a similar workaround with ignoring whitespace in git-apply

In the latest `master`, it is an option in repository setting. :D

**Comment by pgleghorn** [comment]
Great timing! I'll give it a go and see what happens.

**Comment by pgleghorn** [comment]
I tested with 0.11.33 and it worked, the "Ignore changes in whitespace" flag let my pull request go through, on a file containing a byte-order-mark.
Many thanks
