### ISSUE TITLE
Add ssh key failed. An error has occurred : addKey: fail to parse public key: exit status 255 - ssh-keygen: /tmp/223525213/id_rsa.pub: Permission denied

### ISSUE THREAD

**Issue by cupen** [gogits/gogs#4881]
- Gogs version:  0.11.33.1119
- Git version:  git-1.8.3.1-12.el7_4.x86_64
- Operating system:  centos7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2017/12/23 03:41:35 [TRACE] Doing: MirrorUpdate
2017/12/23 03:45:24 [TRACE] Session ID: be4078733ffbcff0
2017/12/23 03:45:24 [TRACE] CSRF Token: XoFgjl0-9ubikUT5T4RvRJ0zXLU6MTUxMzk2ODg5MDM3MzMyOTkwNQ==
2017/12/23 03:45:24 [TRACE] Template: user/settings/profile
2017/12/23 03:45:27 [TRACE] Session ID: be4078733ffbcff0
2017/12/23 03:45:27 [TRACE] CSRF Token: XoFgjl0-9ubikUT5T4RvRJ0zXLU6MTUxMzk2ODg5MDM3MzMyOTkwNQ==
2017/12/23 03:45:27 [TRACE] Template: user/settings/sshkeys
2017/12/23 03:45:52 [TRACE] Session ID: be4078733ffbcff0
2017/12/23 03:45:52 [TRACE] CSRF Token: XoFgjl0-9ubikUT5T4RvRJ0zXLU6MTUxMzk2ODg5MDM3MzMyOTkwNQ==
2017/12/23 03:45:52 [TRACE] ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkUB9xaVmy/d+5TuoyFYvPe81EDVZrzCHJFA8n8LE+/Sue1fwq3Gj+XK1cr69Yi9CJs/kEwlROd502aVqA42eAppK4KYrJlGOnVrB2jzZSkMBm82v0GyodGU3FrKI0geaQPR27DyS3sAZ2bOaPustXqG2nHcYZY710GY1mIs4rmUdbL36LSjzXWp7kp9ttDoVqW9nZ1ORdcf4cISRUSJPUfaLySQwi7PbIJ43E6bz3l5IYmecSLvJa8J0P4n4QomoBeexDaU15Ncdp9krMwmEsLZBLrfDDq+arDWNf+S8TZD2mDBsioC5+zRZWwkCZwzhkVIhpj1SejpP2YstRcxF1 cupen@workbench-xdl
2017/12/23 03:45:52 [ERROR] [...g/context/context.go:171 ServerError()] AddPublicKey: addKey: fail to parse public key: exit status 255 - ssh-keygen: /tmp/800513350/id_rsa.pub: Permission denied^M
2017/12/23 03:45:52 [TRACE] Template: status/500
```

## Description
I just add a ssh public key,  the page show me a big `500` with a picture and a error infomation`
An error has occurred : addKey: fail to parse public key: exit status 255 - ssh-keygen: /tmp/223525213/id_rsa.pub: Permission denied`.

I try to look out something, but nothing special.
```bash
$ ls -hl /tmp/223525213
total 4.0K
-rw-r--r--. 1 git git 400 Dec 23 03:18 id_rsa.pub

$ ls -ld /tmp/
drwxrwxrwt. 20 root root 20480 Dec 23 03:18 /tmp/

$ ps aux | grep gogs
git      11329  0.0  0.4 193044 37444 ?        Sl   02:14   0:00 /usr/local/opt/gogs/gogs web --port 10086

$ openssl version
OpenSSL 1.0.2l  25 May 2017

```
ps:  I run my gogs as user `git`

**Comment by Unknwon** [comment]
Hi, what if you:

1. Login as root
2. Switch to user git
3. Try `touch /tmp/800513350/id_rsa.pub`

What would you get?

**Comment by cupen** [comment]
The user git is added by `useradd git -g git -s /usr/sbin/nologin`, so...
```
$ su git
This account is currently not available.
```
But no problem, I change the login shell to `/usr/bin/shell`, now.
```
$ su git
[git@localhost root]$ touch /tmp/800513350/id_rsa.pub
[git@localhost root]$ ls -hl /tmp/223525213
total 4.0K
-rw-r--r--. 1 git git 400 Dec 23 03:18 id_rsa.pub
```
It seem nothing happen.

**Comment by Unknwon** [comment]
I think maybe the `ssh-keygen` does not have permission to write on `/tmp/` directory?

**Comment by cupen** [comment]
Em……  Let me see see.
What's the full command for `ssh-keygen` typed by gogs?  I can type it manually.

**Comment by cupen** [comment]
@Unknwon  Oh, yes.  You are right.
[git@localhost root]$ ssh-keygen -b 2048 -t rsa -f /tmp/test/well
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Saving key "/tmp/test/well" failed: Permission denied

**Comment by cupen** [comment]
@Unknwon  Sorry,  I  `mkdir /tmp/test`  by user root.  Could I get the command for ssh-keygen typed by gogs ? How ?

**Comment by cupen** [comment]
Well, it seems like something wrong with my supervisor. I don't know why, but it works fine with systemd.
Now, I posted my config file of supervisor and systemd here. Maybe a hero would know why and will tell me.
supervisor:
`$ cat /usr/local/opt/gogs/scripts/supervisor/gogs`
```ini
[program:gogs]
directory=/usr/local/opt/gogs
command=/usr/local/opt/gogs/gogs web --port 10086  # --config /usr/local/opt/gogs/custom/conf/app.ini
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/gogs/stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/gogs/stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
user = git
environment = HOME="/usr/local/opt/gogs", USER="git"
```

systemd:
`$ cat /usr/local/opt/gogs/scripts/systemd/gogs.service`
```ini
[Unit]
Description=Gogs
After=syslog.target
After=network.target
After=mariadb.service mysqld.service postgresql.service memcached.service redis.service

[Service]
# Modify these two values and uncomment them if you have
# repos with lots of files and get an HTTP error 500 because
# of that
###
#LimitMEMLOCK=infinity
#LimitNOFILE=65535
Type=simple
User=git
Group=git
WorkingDirectory=/usr/local/opt/gogs
ExecStart=/usr/local/opt/gogs/gogs web --port 10086
Restart=always
Environment=USER=git HOME=/usr/local/opt/gogs


[Install]
WantedBy=multi-user.target

```
