### ISSUE TITLE
 [FATAL] Fail to dump database: fail to dump table 'TwoFactor': Error 1146: Table 'gogs.two_factor' doesn't exist

### ISSUE THREAD

**Issue by VictorHVS** [gogits/gogs#4882]
- Gogs version (or commit ref): 0.11.33.1119
- Git version: 1.9.1
- Operating system: Debian 4.9.2-10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2017/11/21 14:31:34 [W] Fail to health check repository (/home/git/gogs-repositories/128bits/captei-scripts-old.git): chdir /home/git/gogs-repositories/128bits/captei-scripts-old.git: no such file or directory
2017/11/21 16:45:49 [TRACE] Log Mode: File (Trace)
2017/11/21 16:45:49 [ INFO] Gogs 0.11.33.1119
2017/11/21 16:45:49 [ INFO] Cache Service Enabled
2017/11/21 16:45:49 [ INFO] Session Service Enabled
2017/11/21 16:45:49 [ INFO] Mail Service Enabled
2017/11/21 16:45:49 [ INFO] Register Mail Service Enabled
2017/11/21 16:45:49 [ INFO] Notify Mail Service Enabled
2017/11/21 16:45:49 [ INFO] Migration: generate and migrate Git hooks
2017/11/21 16:45:49 [TRACE] [0000]: /home/git/gogs-repositories/128bits/questoes_e_concursos.git
2017/11/21 16:45:49 [TRACE] [0001]: /home/git/gogs-repositories/128bits/captei_app.git
2017/11/21 16:45:49 [TRACE] [0002]: /home/git/gogs-repositories/128bits/institucional-appm.git
2017/11/21 16:45:49 [TRACE] [0003]: /home/git/gogs-repositories/128bits/transparencia.git
2017/11/21 16:45:49 [TRACE] [0004]: /home/git/gogs-repositories/128bits/floriano.git
2017/11/21 16:45:49 [TRACE] [0005]: /home/git/gogs-repositories/128bits/captei-scripts-old.git
2017/11/21 16:45:49 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: write hook file '/home/git/gogs-repositories/128bits/captei-scripts-old.git/hooks/pre-receive': open /home/git/gogs-repositories/128bits/captei-scripts-old.git/hooks/pre-receive: no such file or directory
```
## Description

I upgrade my gogs from 0.9.97.0901 to 0.11.33.1119 and try to create a backup using **./gogs backup** and I got this error:

`2017/11/21 17:07:26 [FATAL] Fail to dump database: fail to dump table 'TwoFactor': Error 1146: Table 'gogs.two_factor' doesn't exist`

...

**Comment by Unknwon** [comment]
Hi,

Migration failed that's why you can't backup because for some reasons, one important element was missing on your previous installation. The `update` hook file under `xxx.git/hooks` directory for every repository managed by Gogs. In this case, the `/home/git/gogs-repositories/128bits/captei-scripts-old.git/hooks`.

You can create this directory manually then start Gogs again, if same error appears for other repositories, repeat same procedure.

**Comment by Unknwon** [comment]
I saw the root cause:

```
2017/11/21 14:31:34 [W] Fail to health check repository (/home/git/gogs-repositories/128bits/captei-scripts-old.git): chdir /home/git/gogs-repositories/128bits/captei-scripts-old.git: no such file or directory
```

You don't have actual file but have record in Gogs database, you probably want to find it back...

**Comment by VictorHVS** [comment]
Ty, I'm curious because in the previous version of gogs I made a dump without problems and use the gogs too... Now, after the updates the gogs works fine, but when I do a gogs backup I'm take this error:

```
2017/11/21 18:34:21 [FATAL] Fail to dump database: fail to dump table 'TwoFactor': Error 1146: Table 'gogs.two_factor' doesn't exist
```

**Comment by Unknwon** [comment]
You will have this table only if you **successfully started** Gogs web server in same version once. Otherwise this table is not created.

**Comment by VictorHVS** [comment]
Thank you @Unknwon ! You are awesome, ty for your service ;D This work for me:

```
find . -name custom_hooks -type d -print -delete
```
