### ISSUE TITLE
Chrome on the mac can not exit the user

### ISSUE THREAD

**Issue by mybolide** [gogits/gogs#4889]
hello
I am not able to quit the Mac Chrome, but safari can exit normally. Is this a bug? How can I change it?

**Comment by Fastidious** [comment]
This doesn't make sense to me. Using Chrome `62.0.3202.94 (Official Build) (64-bit)` I can:

* Login on a `gogs` install.
* Logout.
* Quit the browser.
* Any combination of the above.
