### ISSUE TITLE
Can't upload attachment to issue

### ISSUE THREAD

**Issue by webus** [gogits/gogs#489]
Hello! I'm using Gogs: Go Git Service 0.5.2.0917 Beta
Then i try to upload pdf file to issue i get error: Could not parse JSON

I'm added in app.ini support for pdf and zip files:

[attachment]
; Whether attachments are enabled. Defaults to `true`
ENABLE = true
; Path for attachments. Defaults to `data/attachments`
PATH = data/attachments
; One or more allowed types, e.g. image/jpeg|image/png
ALLOWED_TYPES = image/jpeg|image/png|application/pdf|application/zip
; Max size of each file. Defaults to 32MB
MAX_SIZE = 32
; Max number of files per upload. Defaults to 10
MAX_FILES = 10

Also path data/attachment exists

**Comment by james2doyle** [comment]
I fixed this by creating `/home/gogsuser/go/src/github.com/gogits/gogs/data/attachments` and then changing the permissions of that new folder using `chown -R gogsuser:root data/`.

**Comment by timmyArch** [comment]
@james2doyle i could confirm this, your workaround works fine

**Comment by Unknwon** [comment]
How could I miss this one, it is fixed in `v0.6.5` release. :flushed:
