### ISSUE TITLE
Database setting is not correct: Error 1709: Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by jeremy-gao** [gogits/gogs#4891]
on install web, click install button,  error:  
Database setting is not correct: Error 1709: Index column size too large. The maximum column size is 767 bytes.

[root@controller scripts]# mysql --version
mysql  Ver 15.1 Distrib 10.1.20-MariaDB, for Linux (x86_64) using  EditLine wrapper

**Comment by Primeyang** [comment]
on install web, click install button, error:
Database setting is not correct: Error 1709: Index column size too large. The maximum column size is 767 bytes.
[git@localhost gogs]$ mysql --version
mysql  Ver 14.14 Distrib 5.6.38, for Linux (x86_64) using  EditLine wrapper

**Comment by jeremy-gao** [comment]
hi,  I used the last version, problem solving.

**Comment by rffanlab** [comment]
MySQL 5.5 出现了这个问题，无论使用什么版本。我说大佬，如果没有必要不要非设置255作为一个unique key的长度吧？

**Comment by americodias** [comment]
I have the same problem... I had mysql 5.6. I then tried to migrate to MariaDB 10.0.32 but I have the same issue.

I guess I will give up and use sqlite instead.

**Comment by zenny** [comment]
Same here with mariadb-10 in ubuntu 16.04 even after appending /etc/mysql/my.cnf with:

```
[mysqld]
innodb-file-format=barracuda
innodb-file-per-table=1
innodb-large-prefix=1
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4
```

Any inputs?

**Comment by m2nlight** [comment]
try this:
1. Restart mysql service. 
2. Export data to sql file. (Backup)
3. Run this [sql script:](https://github.com/m2nlight/gogs/blob/7a3c766d4cf625f12227ecaca67a013804768dc1/scripts/mysql.sql)
```sql
SET GLOBAL innodb_file_per_table = ON,
           innodb_file_format = Barracuda,
           innodb_large_prefix = ON;
DROP DATABASE IF EXISTS gogs;
CREATE DATABASE IF NOT EXISTS gogs CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```
4. Restore data from sql file(Restore)

**Comment by m2nlight** [comment]
- or -

Upgrade mariadb version to 10.2 or higher.
Upgrade mysql version to 5.7 or higher.

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogits/gogs/issues/4894.

**Comment by SabuShakya** [comment]
> try this:
> 
> 1. Restart mysql service.
> 2. Export data to sql file. (Backup)
> 3. Run this [sql script:](https://github.com/m2nlight/gogs/blob/7a3c766d4cf625f12227ecaca67a013804768dc1/scripts/mysql.sql)
> 
> ```sql
> SET GLOBAL innodb_file_per_table = ON,
>            innodb_file_format = Barracuda,
>            innodb_large_prefix = ON;
> DROP DATABASE IF EXISTS gogs;
> CREATE DATABASE IF NOT EXISTS gogs CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
> ```
> 
> 1. Restore data from sql file(Restore)

It didn't work. The above steps results 'Broken Pipe' error
