### ISSUE TITLE
关于用户权限设置

### ISSUE THREAD

**Issue by keep-running** [gogits/gogs#4892]
使用的版本：0.11.34
我们有个**使用场景**：
每个普通用户只能在其分配过权限的仓库中读写，普通用户不要有创建仓库项目的权限。

**目前处理**：
因为当前最新的 0.11.34 版本还没有提供"创建仓库权限"的限制功能，我们通过设置普通用户能创建的仓库数量为0，来限制其创建新的仓库。

**问题**：
普通用户虽然创建不了仓库，但是，可以创建组织，在创建的组织下，又能创建仓库，变相导致普通用户也能创建仓库；

**建议**：
限制普通用户创建仓库、创建组织、迁移仓库的权限；

**Comment by blueskit** [comment]
![image](https://user-images.githubusercontent.com/5501633/33526131-42091c50-d877-11e7-8f36-719539ec079c.png)
