### ISSUE TITLE
MySql /Mariadb error: max key length is 767 byte

### ISSUE THREAD

**Issue by ulorentz** [gogits/gogs#4894]
- Gogs version (or commit ref): 0.11.34
- Git version:  2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I tried to install from binary, I created the database on MariaDB, I launched ./gogs web and opened the installing page on browser. I inserted all needed but I received the error "Database setting is not correct: Error 1709: Index column size too large. The maximum column size is 767 bytes."
I think it's a problem related to MariaDB char set size, but I wasn't able to solve it.
...

**Comment by playmyskay** [comment]
I have the same error.
It seems to be a similar problem which is also described here:
https://discuss.gogs.io/t/solved-mysql-error-1064-while-running-first-install/1604/3

I tried these options in mysql (mariadb):
    SET GLOBAL innodb_file_format=Barracuda;
    SET GLOBAL innodb_file_per_table=ON;
    innodb_large_prefix=1

But the create statements of the tables should have (which is not the case):
ROW_FORMAT=DYNAMIC;

**Comment by ulorentz** [comment]
For me, it doesn't work. Do you confirm those commands don't solve the issue?

**Comment by ImAnOwl** [comment]
have the same problem, but I have already read, upgrading mysql to 5.7 should solve the problem. I'll write later again, when i solved it

**Comment by ulorentz** [comment]
Debian 9 uses MariaDB 10.1, that should be mySQL compatible, but it's not mySQL.

**Comment by ImAnOwl** [comment]
I upgraded to MariaDB 10.2 and now it works. :)

**Comment by playmyskay** [comment]
Here a short description how i get it working.. it is very laborious but it works for me:

1. Create your gogs database as usual
2. Visit the install page
3. Type in your data (database, user, etc.)
4. Click on Button "Install"
-> It will fail with: 'Error 1709: Index column size too large. The maximum column size is 767 bytes.'
BUT the tables were partially created.

5. Now connect to your mariadb, use your gogs database and alter the tables with the following command:
ALTER TABLE `_tablename_`  ROW_FORMAT=DYNAMIC;

6. Now go back to step 2 and repeat it. Always alter all "new" tables which were created.

After 4 or 5 rounds you get every needed table and it's done. 

Good luck.

**Comment by ulorentz** [comment]
It works! Thank you very much. 
It would be nice to have this process automatic (what should change in gogs code?).

**Comment by intersel** [comment]
@playmyskay Thanks a lot for the solution that worked for me too  on
mysql  Ver 15.1 Distrib 10.0.32-MariaDB, for debian-linux-gnu (i686) using readline 5.2
on debian 8

**Comment by m2nlight** [comment]
Because of mysql 5.6 (includes prior versions) InnoDB max index length is **767** bytes, mysql 5.7.7 is up to **3072** bytes.
If some varchar column's length is 255, when the character format is utf-8 needs 255\*3=**765** bytes for index length, It's OK. 
But, an utf8mb needs 255\*4=**1020** bytes for index length.

Solutions:
- UPGRADE the mysql to 5.7.7(Mariadb 10.2.2)
- Change the utf8mb column length to 191 (191\*4=764)
- Change the utf8mb to utf8
- set  `innodb_large_prefix=on` and create table using ROW_FORMAT=`DYNAMIC` or `COMPRESSED`

**Comment by laurivosandi** [comment]
Hi, on Debian 9 with MariaDB this sill seems to be much of an hassle. Just to save someone else a bit time, dump this repeatedly to the SQL prompt until Gogs install finishes:

```
ALTER TABLE `access` ROW_FORMAT=DYNAMIC;
ALTER TABLE `access_token` ROW_FORMAT=DYNAMIC;
ALTER TABLE `action` ROW_FORMAT=DYNAMIC;
ALTER TABLE `attachment` ROW_FORMAT=DYNAMIC;
ALTER TABLE `collaboration` ROW_FORMAT=DYNAMIC;
ALTER TABLE `comment` ROW_FORMAT=DYNAMIC;
ALTER TABLE `deploy_key` ROW_FORMAT=DYNAMIC;
ALTER TABLE `follow` ROW_FORMAT=DYNAMIC;
ALTER TABLE `hook_task` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue_label` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue_user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `label` ROW_FORMAT=DYNAMIC;
ALTER TABLE `login_source` ROW_FORMAT=DYNAMIC;
ALTER TABLE `milestone` ROW_FORMAT=DYNAMIC;
ALTER TABLE `mirror` ROW_FORMAT=DYNAMIC;
ALTER TABLE `protect_branch` ROW_FORMAT=DYNAMIC;
ALTER TABLE `protect_branch_whitelist` ROW_FORMAT=DYNAMIC;
ALTER TABLE `public_key` ROW_FORMAT=DYNAMIC;
ALTER TABLE `pull_request` ROW_FORMAT=DYNAMIC;
ALTER TABLE `release` ROW_FORMAT=DYNAMIC;
ALTER TABLE `repository` ROW_FORMAT=DYNAMIC;
ALTER TABLE `star` ROW_FORMAT=DYNAMIC;
ALTER TABLE `two_factor` ROW_FORMAT=DYNAMIC;
ALTER TABLE `two_factor_recovery_code` ROW_FORMAT=DYNAMIC;
ALTER TABLE `upload` ROW_FORMAT=DYNAMIC;
ALTER TABLE `user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `watch` ROW_FORMAT=DYNAMIC;
ALTER TABLE `webhook` ROW_FORMAT=DYNAMIC;
```

**Comment by Sunseille** [comment]
worked for me

ALTER TABLE `access` ROW_FORMAT=DYNAMIC;
ALTER TABLE `access_token` ROW_FORMAT=DYNAMIC;
ALTER TABLE `action` ROW_FORMAT=DYNAMIC;
ALTER TABLE `attachment` ROW_FORMAT=DYNAMIC;
ALTER TABLE `collaboration` ROW_FORMAT=DYNAMIC;
ALTER TABLE `comment` ROW_FORMAT=DYNAMIC;
ALTER TABLE `deploy_key` ROW_FORMAT=DYNAMIC;
ALTER TABLE `email_address` ROW_FORMAT=DYNAMIC;
ALTER TABLE `follow` ROW_FORMAT=DYNAMIC;
ALTER TABLE `hook_task` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue_label` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue_user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `label` ROW_FORMAT=DYNAMIC;
ALTER TABLE `login_source` ROW_FORMAT=DYNAMIC;
ALTER TABLE `milestone` ROW_FORMAT=DYNAMIC;
ALTER TABLE `mirror` ROW_FORMAT=DYNAMIC;
ALTER TABLE `notice` ROW_FORMAT=DYNAMIC;
ALTER TABLE `org_user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `protect_branch` ROW_FORMAT=DYNAMIC;
ALTER TABLE `protect_branch_whitelist` ROW_FORMAT=DYNAMIC;
ALTER TABLE `public_key` ROW_FORMAT=DYNAMIC;
ALTER TABLE `pull_request` ROW_FORMAT=DYNAMIC;
ALTER TABLE `release` ROW_FORMAT=DYNAMIC;
ALTER TABLE `repository` ROW_FORMAT=DYNAMIC;
ALTER TABLE `star` ROW_FORMAT=DYNAMIC;
ALTER TABLE `team` ROW_FORMAT=DYNAMIC;
ALTER TABLE `team_repo` ROW_FORMAT=DYNAMIC;
ALTER TABLE `team_user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `two_factor` ROW_FORMAT=DYNAMIC;
ALTER TABLE `two_factor_recovery_code` ROW_FORMAT=DYNAMIC;
ALTER TABLE `upload` ROW_FORMAT=DYNAMIC;
ALTER TABLE `user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `watch` ROW_FORMAT=DYNAMIC;
ALTER TABLE `webhook` ROW_FORMAT=DYNAMIC;

**Comment by sxl5513** [comment]
I use mysql5.6 , this error exist, your mysql version is 5.7??

**Comment by gabriellima** [comment]
Just to add that, for me, I had to also alter database and table's character set.

The full list of commands was:

```
ALTER TABLE `access` ROW_FORMAT=DYNAMIC;
ALTER TABLE `access_token` ROW_FORMAT=DYNAMIC;
ALTER TABLE `action` ROW_FORMAT=DYNAMIC;
ALTER TABLE `attachment` ROW_FORMAT=DYNAMIC;
ALTER TABLE `collaboration` ROW_FORMAT=DYNAMIC;
ALTER TABLE `comment` ROW_FORMAT=DYNAMIC;
ALTER TABLE `deploy_key` ROW_FORMAT=DYNAMIC;
ALTER TABLE `follow` ROW_FORMAT=DYNAMIC;
ALTER TABLE `hook_task` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue_label` ROW_FORMAT=DYNAMIC;
ALTER TABLE `issue_user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `label` ROW_FORMAT=DYNAMIC;
ALTER TABLE `login_source` ROW_FORMAT=DYNAMIC;
ALTER TABLE `milestone` ROW_FORMAT=DYNAMIC;
ALTER TABLE `mirror` ROW_FORMAT=DYNAMIC;
ALTER TABLE `protect_branch` ROW_FORMAT=DYNAMIC;
ALTER TABLE `protect_branch_whitelist` ROW_FORMAT=DYNAMIC;
ALTER TABLE `public_key` ROW_FORMAT=DYNAMIC;
ALTER TABLE `pull_request` ROW_FORMAT=DYNAMIC;
ALTER TABLE `release` ROW_FORMAT=DYNAMIC;
ALTER TABLE `repository` ROW_FORMAT=DYNAMIC;
ALTER TABLE `star` ROW_FORMAT=DYNAMIC;
ALTER TABLE `two_factor` ROW_FORMAT=DYNAMIC;
ALTER TABLE `two_factor_recovery_code` ROW_FORMAT=DYNAMIC;
ALTER TABLE `upload` ROW_FORMAT=DYNAMIC;
ALTER TABLE `user` ROW_FORMAT=DYNAMIC;
ALTER TABLE `watch` ROW_FORMAT=DYNAMIC;
ALTER TABLE `webhook` ROW_FORMAT=DYNAMIC;
```

```ALTER DATABASE `gogs` CHARACTER SET utf8 COLLATE utf8_general_ci;```

```
ALTER TABLE `access` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `access_token` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `action` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `attachment` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `collaboration` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `comment` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `deploy_key` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_address` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `follow` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `hook_task` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `issue` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `issue_label` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `issue_user` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `label` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `login_source` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `milestone` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `mirror` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `notice` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `org_user` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `protect_branch` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `protect_branch_whitelist` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `public_key` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `pull_request` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `release` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `repository` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `star` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `team` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `team_repo` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `team_user` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `two_factor` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `two_factor_recovery_code` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `upload` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `user` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `watch` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `webhook` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
```

**Comment by zenny** [comment]
Didn't work! :-(

```
MariaDB [gogs]> show table status;
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation          | Checksum | Create_options | Comment |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+
| user | InnoDB |      10 | Compact    |    0 |              0 |       16384 |               0 |            0 |         0 |              1 | 2018-02-03 23:57:08 | NULL        | NULL       | utf8mb4_general_ci |     NULL |                |         |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+--------------------+----------+----------------+---------+
1 row in set (0.00 sec)

MariaDB [gogs]> ALTER TABLE _user_ ROW_FORMAT=DYNAMIC;
ERROR 1146 (42S02): Table 'gogs._user_' doesn't exist

```

**Comment by m2nlight** [comment]
The easiest way:
Upgrade mariadb version to 10.2 or higher.
Upgrade mysql version to 5.7 or higher.

**Comment by DJManas** [comment]
I would love to upgrade to 10.2, but since it is not arm ready yet, I have a problem :-(

**Comment by YakovL** [comment]
I've passed through this issue, so let me summarize:

1. the method by [playmyskay](https://github.com/gogits/gogs/issues/4894#issuecomment-347169012) worked for me
   * I set both encoding and row_format; to speed up the process, I used the list [shared by gabriellima](https://github.com/gogits/gogs/issues/4894#issuecomment-362208350) and used its 2 parts (except for the `alter database` line) each time (after each run of `.gogs web`) instead of putting specific lines (for specific tables)
   * I've also used `ALTER DATABASE `gogs` CHARACTER SET utf8 COLLATE utf8_general_ci;` (suggested by gabriellima) in the beginning of the process
2. I'm on MariaDB 10.1 (strange, I've installed it a couple of days ago and it's not latest 10.2.x), I haven't tried [m2nlight's suggestion](https://github.com/gogits/gogs/issues/4894#issuecomment-362868594) but I'd recomment those who just started to deal with this issue to **try this first**
3. there's also [a patch by m2nlight](https://github.com/m2nlight/gogs/releases/tag/v0.11.34_patch) which I haven't tried and which is probably another straightforward solution
   * fixing this in production is discussed [here](https://github.com/gogits/gogs/pull/4913)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4913, please help test on `develop` branch.

**Comment by MyS5Droid** [comment]
Problem still exists, nothing above fixes it or works, please re-open and raise importance level thank you

**Comment by Unknwon** [comment]
@MyS5Droid upgrade MySQL to 5.7 as per request of https://gogs.io/docs/installation.

**Comment by MyS5Droid** [comment]
@m2nlight Do you know how to restore it from the directory though? I did not know there was CLI command for backup/restore with an archive file :-/

If that directory is where the entire project is contained you would think that either projects in the directory would be added again, or you would be able to import from that directory...

Doesn't matter now, trying to reinstall gogs in the same location has not only cleared the database, but that directory as well... Sadly I have lost a shitty project I was working on. Not that I would have completed it but may have needed the code for other project.

@Unknwon I use virtualmin, when I select the server and go to "PHP Version" it says "Your system only has PHP version 7.0.27 installed, so selecting a different version for each directory is not possible." - According to that I have PHP >= 5.7

**Comment by Unknwon** [comment]
I don’t know what you saying, PHP is not MySQL.

**Comment by MyS5Droid** [comment]
@Unknwon Whoops thanks for pointing out I am a stoner without providing steps to locate the correct version number but I am a knowledgeable person so I digress.

I click "Webmin" and then "Servers" and then "MySQL Database Server" and at the top it says "MySQL version 10.1.26"

**Comment by m2nlight** [comment]
I think you need the gogs-repositories directory and gogs database. If gogs database is empty, the gogs web UI does not show any repos and others. Because the info is gone. Maybe it's a conf.ini configured a error database.

**Comment by m2nlight** [comment]
10.1.26 is MariaDB version. Please update to MariaDB 10.2

**Comment by MyS5Droid** [comment]
WTF is MariaDB I have PHP and MySQL installed on my server. It is
Virtualmin server. I use PHPMyAdmin to access my MySQL database.

I have never installed MariaDB ever. In fact I specifically followed
instructions to remove it and use MySQL.

Virtualmin may have kept it installed in case it wants to use it for a
virtual server but I assure you my SQL databases are MySQL otherwise I
would have issues lol... I've never upgraded any of the databases I've
designed to MariaDB nor any of the PHP code. It simply would not work the
way it is...

**Comment by MyS5Droid** [comment]
I forgot to mention a second or third time, *the point is moot* as I found
the proper working fix (the code in one of my posts above)

Not allowing restoration of everything from the directory is a big mistake.
The files should contain everything needed to do a basic restore...

The dir is named "gogs-repository" for f's sake, you would think all the
files and data are right there to copy zip and backup in emergency...

**Comment by m2nlight** [comment]
@MyS5Droid I am sorry you lost your repos. Restore repos from `gogs-repository` is a good idea. If you can do that, let's work together to prefect gogs.
