### ISSUE TITLE
when  I  commit and git push

### ISSUE THREAD

**Issue by gowufang** [gogits/gogs#4914]
When use a another user account(Which is not ADMIN) to push,there is an error:
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by vrms** [comment]
I see the same error today (2021.09.17) on a local Gogs instance, even if the user is an administrator
