### ISSUE TITLE
控制面板－用户提交记录出现 用户错乱的BUG

### ISSUE THREAD

**Issue by zlkbdotnet** [gogits/gogs#4916]
应用版本：0.11.19.0609
使用时间大概：4个月左右

出现的问题：
控制面板处显示的提交记录，对应的用户是错乱的，明明是A提交的，却显示是B提交；
通过GIT日志去查询，显示该次提交属于B

请问该如何处理呢

谢谢

**Comment by Unknwon** [comment]
Check your committer's email.
