### ISSUE TITLE
Error 1071: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by peasead** [gogits/gogs#4917]
- Gogs version (or commit ref): 0.11.34 (6f2347fc71f17b5703a9b1f383a2d3451f88b741)
- Git version: 1.8.3.1
- Operating system: CentOS 7.4 (1708) 
- Database:
  - [ ] PostgreSQL
  - [x] MySQL `5.5.56-MariaDB`
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): Not created

## Description
I know that this has been raised before and addressed in the [troubleshooting section](https://gogs.io/docs/intro/troubleshooting.html#incorrect-mysql-storage-engine), however since `0.11.34`, I have experienced this issue with no resolution with troubleshooting steps.

While my error says `767 bytes` vs the `1000 bytes` from this image, the rest is the same:
![error](https://cloud.githubusercontent.com/assets/4661855/3787356/852a638a-1a12-11e4-925c-ee3e20ac3d82.jpg)

## Troubleshooting
* Updated MariaDB to version 10 (not running 10 at the moment, but was getting desperate)
* Read [this GoGS discussion post](https://discuss.gogs.io/t/solved-mysql-error-1064-while-running-first-install/1604)
* Imported the `scripts/mysql.sql` using `mysql -u root -p gogs < mysql.sql`
* Run `use gogs;` and `set global storage_engine=INNODB;`
* Attempted multiple suggestions from Google
* In running some checks from [these troubleshooting steps](https://stackoverflow.com/questions/35847015/mysql-change-innodb-large-prefix), I discovered
```
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_large%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | OFF  |
+---------------------+-------+
```
and 
```
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_file%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Antelope |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Antelope |
| innodb_file_per_table    | OFF        |
+--------------------------+-----------+
```
I performed the recommended changes:
```
set global innodb_file_format = `BARRACUDA`;
set global innodb_file_format_max = `BARRACUDA`;
set global innodb_large_prefix = `ON`;
SET GLOBAL innodb_file_per_table=ON;
```
resulting in 
```
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_large%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON  |
+---------------------+-------+
```
and 
```
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_file%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Barracuda |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+
```
However, nothing  I can figure out is getting me past this error.

I'm not a DBA by any stretch, so I apologize if my troubleshooting was wrong; any help is appreciated.

**Comment by m2nlight** [comment]
`ALTER TABLE _tablename_ ROW_FORMAT=DYNAMIC;`
goto https://github.com/gogits/gogs/issues/4894

**Comment by peasead** [comment]
Thanks @m2nlight

**Comment by stigerr** [comment]
I'm using following script:

`#!/bin/bash

echo "show tables;" | mysql gogs | while read LINE;
 do
  if [ "$LINE" != "Tables_in_gogs" ]; then echo "ALTER TABLE \`$LINE\`  ROW_FORMAT=DYNAMIC;" | mysql gogs
 fi
done
`

**Comment by djon2003** [comment]
Here is a script for installation on Windows. I wanted to bypass the creation of a file, but I was not able to due to the pipe symbol even using a caret. Ensure to modify the variables SET at the beginning.

@ECHO OFF

SET mysql_user=root
SET mysql_password=PASSWORD_TO_PUT
SET mysql_location=c:\progs\xampp\mysql
mkdir C:\Temp

echo use gogs;show tables; | %mysql_location%\bin\mysql -u %mysql_user% -p%mysql_password% > c:\temp\gogs-table.txt
for /F "tokens=*" %%A in (c:\temp\gogs-table.txt) do (
IF NOT "%%A" == "Tables_in_gogs" (
echo Altering %%A
echo ALTER TABLE `%%A` ROW_FORMAT=DYNAMIC; | %mysql_location%\bin\mysql -u %mysql_user% -p%mysql_password% gogs
)
)

del c:\temp\gogs-table.txt

**Comment by MyS5Droid** [comment]
Same problem, patch makes it worse and makes error:

> [FATAL] [...gits/gogs/cmd/web.go:70 checkVersion()] Binary version is lower than template file version, did you forget to recompile Gogs?

Please advise
