### ISSUE TITLE
Validate authorized_keys config path

### ISSUE THREAD

**Issue by mqudsi** [gogits/gogs#4920]
After re-installing gogs to a different location, I wound up with a situation where everything was working and configured correctly, yet the dashboard was not updating when I pushed to certain repositories. I attempted to reinstall all git hooks and even went in and manually checked the git hooks for the repositories, but everything checkout out.

Long story short, it turned out that ~/.ssh/authorized_keys for the gogs user was pointing to the old config file and not the new path. 

gogs should, either at startup or at least when attempting to re-install hooks, validate that the app.ini path in authorized_keys matches that of the running gogs instance, and generate a system notice if it doesn't.

**Comment by Unknwon** [comment]
Hi, `authorized_keys` can be put anywhere based on your SSHD configuration, so Gogs has no "right" answer to it. Otherwise, there is no need to have this config option at all.
