### ISSUE TITLE
Broken support for godoc.org

### ISSUE THREAD

**Issue by Drahoslav7** [gogits/gogs#4926]
- Gogs version: 0.11.34.1122 
- Git version: 1.9.2
- Operating system: linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Support for godoc.org service is broken.

eg.: http://godoc.org/try.gogs.io/gogs/gogs - does not work, even thou
https://try.gogs.io/gogs/gogs?go-get=1 seems to return correct meta tags.

I think there might be problem with bad mime/type or missing doctype tag in the response.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4938, please help test on `develop` branch.

**Comment by Drahoslav7** [comment]
Have to wait until tomorrow due to godocs.org's cache.
