### ISSUE TITLE
Admin should be able to edit settings of all repositories

### ISSUE THREAD

**Issue by rojaro** [gogits/gogs#493]
Global administrators should be able to modify repository and user settings directly through the administration interface i.e. make a public repository private, transfer ownership, edit ssh keys etc.

**Comment by xPaw** [comment]
:+1:

By the looks of it, admins can't delete repositories of other users.

**Comment by rojaro** [comment]
I think an Administrator should be able to create, read, update and delete everything including creating repositories for users, renaming repositories, editing description, organizations, teams and memberships.

**Comment by Unknwon** [comment]
@rojaro thanks for the details.

**Comment by linquize** [comment]
+1

**Comment by da-kid** [comment]
+1

**Comment by dentmaged** [comment]
+1

**Comment by Unknwon** [comment]
You can now test this on `develop` branch.

**Comment by stonerl** [comment]
@Unknwon have tested it and it works great.

**Comment by Unknwon** [comment]
@stonerl thanks your confirmation!
