### ISSUE TITLE
Custom pre-receive hook fails with "Internal error" on windows

### ISSUE THREAD

**Issue by pgleghorn** [gogits/gogs#4930]
- Gogs version (or commit ref): 0.11.33.1119
- Git version: 2.8.3.windows.1
- Operating system: Gogs on Windows 2012
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): See below

## Description

I have created a test pre-receive hook in the UI which is just this

```
#!/bin/sh
echo "hello from pre-recieve hook"
```

But this fails with Internal error:

```
C:\Users\pgleghorn\Desktop\local-repos\hooktest>git push -u origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 307 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
Username for 'http://localhost:3000': phil
Password for 'http://phil@localhost:3000':
remote: Gogs: Internal error
To http://localhost:3000/phil/hooktest.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://localhost:3000/phil/hooktest.git'
```

Note, I am running Gogs on windows (in the cmd shell), I have windows git installed

**Comment by pgleghorn** [comment]
Didn't see any errors in gogs.log as such

```
2017/12/11 08:12:59 [TRACE] HTTPGit - Authenticated user: phil
2017/12/11 08:13:07 [TRACE] Session ID: 9ab0d22a2727c64e
2017/12/11 08:13:07 [TRACE] CSRF Token: VjMbTmQXhQysB1fn6kvLPfGPHek6MTUxMjk3OTk4NzE1ODcwMDMwMA==
2017/12/11 08:13:07 [TRACE] TriggerTask 'hooktest/master' by 'phil'
2017/12/11 08:13:07 [TRACE] DeliverHooks [repo_id: 3]
2017/12/11 08:13:07 [TRACE] AddTestPullRequestTask [head_repo_id: 3, head_branch: master]: finding pull requests
2017/12/11 08:13:07 [TRACE] AddTestPullRequestTask [base_repo_id: 3, base_branch: master]: finding pull requests

**Comment by pgleghorn** [comment]
Found this in the hooks log (C:\zzz\gogs\log\hooks\pre-receive.log:

2017/12/11 15:10:38 [FATAL] [...its/gogs/cmd/hook.go:150 runHookPreReceive()] Fail to execute custom pre-receive hook: exec: "c:\\zzz\\gogs\\gogs-repositories\\phil\\hooktest.git\\custom_hooks\\pre-receive": file does not exist

but the file does exist:

```
C:\zzz\gogs\gogs-repositories\phil\hooktest.git\custom_hooks>type pre-receive
#!/bin/sh
echo "hello from pre-recieve hook"
```

Seems to be the same error as #4255

**Comment by pgleghorn** [comment]
We found the cause and solution for this. What had happened was that the gogs installation and the gogs-repositories directory had been moved from its original location. As a result, the default hooks found under gogs-repositories/<reponame>/hooks (like pre-receive, pre-receive, and update) still had embedded within them the old location of the gogs config file.

e.g a repo's default pre-receive looks like this, with the gogs directory baked in:

#!/usr/bin/env bash
"C:/zzz/gogs/gogs.exe" hook --config='C:/zzz/gogs/custom/conf/app.ini' pre-receive

these paths needed to be updated for the new correct location of gogs.

**Comment by Unknwon** [comment]
@pgleghorn you can actually done update via one click on admin panel (`/admin`).

**Comment by jbrodriguez** [comment]
I faced the same issue, thanks @Unknwon for pointing to /admin, it was all it took

**Comment by mikeperalta1** [comment]
+1 editing the hooks path to gogs source dir fixed it for me :)
