### ISSUE TITLE
Add topics/categorization

### ISSUE THREAD

**Issue by sarandafl** [gogits/gogs#4931]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 1.8.3.1
- Operating system: CentOS 7
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Github supports topics which can bee seen at the top of a repo:
![image](https://user-images.githubusercontent.com/17392375/33827288-3000aaae-de68-11e7-872a-5aa3f08f2b03.png)

It would be nice if gogs would support something like this, as it aids in categorization. 
It does not specifically need to be done this way, but any sort of categorization would be appreciated.
For example script which have to do with copying files could be "tagged" as `copy`. When one clicks on `copy`, all repos containing this "tag" will be listed.

**Comment by Unknwon** [comment]
Hmm, I think this is same to https://github.com/gogits/gogs/issues/1253
