### ISSUE TITLE
version 0.11.34 Linux amd64 have ’Specified key was too long; max key length is 767 bytes’ problem

### ISSUE THREAD

**Issue by wggd** [gogits/gogs#4937]
create new mysql tables ,the character is utf8mb4

**Comment by mgckid** [comment]
i think the problem  is your mysql version too low, i have same problem like you ,now i have to choice sqlite3 database,it is work; my mysql version is 5.5x and gogs is not work with this version. i don`t want to update my mysql version.

**Comment by wggd** [comment]
@mgckid thanks, afterwards i choice version 0.11.29, no this problem.

**Comment by levinit** [comment]
use the patch or mariadb 10.12 (or mysql 5.6)

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/4894.
