### ISSUE TITLE
Disable cron jobs

### ISSUE THREAD

**Issue by soundstorm** [gogits/gogs#4947]
I'd like to disable the `git fsck` run (`[cron.repo_health_check]`), but the documentation does not tell, which values are valid for `SCHEDULE` (and which disables a schedule completely).

**Comment by ax1036** [comment]
from https://gogs.io/docs/advanced/configuration_cheat_sheet#cron-(cron)

`[cron.repo_health_check]
ENABLE=false`

(enabled option is available for sub-cron too)
