### ISSUE TITLE
Cannot push to mirror repo

### ISSUE THREAD

**Issue by jooola** [gogits/gogs#4949]
- Gogs version (or commit ref): 0.11.29.0727 
- Git version: git version 2.11.0
- Operating system: Debian 9
- Database:
  - [ ] PostgreSQL
  - [x] MySQL (mariadb)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

Nothing is logged : 
``` 
2017/12/19 11:21:56 [TRACE] HTTPGit - Authenticated user: jonas
2017/12/19 11:21:56 [TRACE] Session ID: 433e6a7775ff45b1
2017/12/19 11:21:56 [TRACE] CSRF Token: OlscpFrGq_kGi8xDdwue-CkhVts6MTUxMzY3ODkxNjgyMzk4NTY0NA==
2017/12/19 11:21:56 [TRACE] HTTPGit - Authenticated user: jonas
2017/12/19 11:21:58 [TRACE] Session ID: f2bcdd6dd149f1f1
2017/12/19 11:21:58 [TRACE] CSRF Token: uSO1O8AYHlganKeeBYoLp9ZXf-A6MTUxMzY3ODkxODM4MDE0ODU3NA==
```
#### Local git log
```
Décompte des objets: 25, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (25/25), fait.
Écriture des objets: 100% (25/25), 4.49 KiB | 0 bytes/s, fait.
Total 25 (delta 13), reused 0 (delta 0)
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403 Forbidden
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```
## Description

After creating a fresh mirror repo. It pulled , committed and while trying to push I get the above git log.
Gogs is behind HAproxy.
After transforming the mirror to a standard repo everything works fine and push works as expected !

Thanks for this app !

**Comment by alexanderadam** [comment]
I'm pretty sure this is intended. If you have write access to a mirror you could mess with the git history which could lead in updating the mirroring functionality.
Besides from that people would expect the exact repository from the mirror anyway.

Fork it if you want to change data from a mirrored repository.
