### ISSUE TITLE
Discord Login

### ISSUE THREAD

**Issue by JustMaffie** [gogits/gogs#4951]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: Not Relevant
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): Not Relevant

## Description

It would be great to be able to allow my users to link their Discord account to their Gogs account.

**Comment by Unknwon** [comment]
Thanks for the suggestion, you can follow up OAuth2 support in https://github.com/gogits/gogs/issues/4602.
