### ISSUE TITLE
 New Migration fails: "You are not allowed to import local repositories" using github git URL

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#4958]
- Gogs version (or commit ref): 0.11.34_1
- Git version: 2.15.1
- Operating system: FreeBSD 11.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

---

## Description

Got this error on git@github.com:RainerKuemmerle/g2o.git as URL.
```git clone``` works fine on it.

...

**Comment by Unknwon** [comment]
Hi, SSH migration is not supported.
