### ISSUE TITLE
gogs 0.11.29.0727 sqlite3 update to gogs 0.11.34.1122 posgresql .user dashboard page is 500 error after login,but other web page is no problem. 

### ISSUE THREAD

**Issue by xufanghui** [gogits/gogs#4959]
exception log:
[Macaron] PANIC: reflect: indirection through nil pointer to embedded struct
/usr/local/go/src/runtime/panic.go:491 (0x434f12)
/usr/local/go/src/text/template/exec.go:146 (0x51c6a4)
/usr/local/go/src/runtime/asm_amd64.s:509 (0x46387a)
/usr/local/go/src/runtime/panic.go:491 (0x434f12)
/usr/local/go/src/reflect/value.go:804 (0x4c4c7e)
/usr/local/go/src/text/template/exec.go:571 (0x520ece)
/usr/local/go/src/text/template/exec.go:528 (0x520189)
/usr/local/go/src/text/template/exec.go:492 (0x51f8d7)
/usr/local/go/src/text/template/exec.go:430 (0x51f285)
/usr/local/go/src/text/template/exec.go:408 (0x51e774)
/usr/local/go/src/text/template/exec.go:234 (0x51d47e)
/usr/local/go/src/text/template/exec.go:242 (0x51d0ec)
/usr/local/go/src/text/template/exec.go:329 (0x52db7e)
/usr/local/go/src/text/template/exec.go:338 (0x51dda6)
/usr/local/go/src/text/template/exec.go:245 (0x51d420)
/usr/local/go/src/text/template/exec.go:242 (0x51d0ec)
/usr/local/go/src/text/template/exec.go:197 (0x51cb28)
/usr/local/go/src/text/template/exec.go:180 (0x51c902)
/usr/local/go/src/html/template/template.go:137 (0x8669b5)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:520 (0x8a5003)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:555 (0x8a547a)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:566 (0x8a57ca)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:586 (0x8a5b1a)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:157 (0x89cd1b)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:167 (0x89cdd1)
/home/vagrant/gopath/src/github.com/gogits/gogs/pkg/context/context.go:120 (0xbd9509)
**/home/vagrant/gopath/src/github.com/gogits/gogs/routes/user/home.go:164 (0xc78aac)
/home/vagrant/gopath/src/github.com/gogits/gogs/routes/home.go:29 (0xc8d479)**
/usr/local/go/src/runtime/asm_amd64.s:509 (0x46387a)
/usr/local/go/src/reflect/value.go:434 (0x4c3124)
/usr/local/go/src/reflect/value.go:302 (0x4c2703)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:177 (0x86fce8)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:137 (0x86f5e9)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x89c7fd)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x89c735)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/session/session.go:186 (0x8f4296)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:79 (0x89c5e0)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x86f9a3)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x86f6da)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x89c7fd)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x89c735)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x8af9fa)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:40 (0x89fa5b)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x86f9a3)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x86f6da)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x89c7fd)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:112 (0x89c735)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:52 (0x8aec8b)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/logger.go:40 (0x89fa5b)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:157 (0x86f9a3)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/go-macaron/inject/inject.go:135 (0x86f6da)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/context.go:121 (0x89c7fd)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:187 (0x8b0ce2)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/router.go:296 (0x8a8f3b)
/home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x8a0fc7)
/usr/local/go/src/net/http/server.go:2619 (0x6dd833)
/usr/local/go/src/net/http/server.go:1801 (0x6d9a8c)
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x4660e0)
[Macaron] 2017-12-24 12:20:26: Completed GET / 500 Internal Server Error in 596.184372ms

my data table at 
access
action
collaboration
comment
follow
issue
issue_label
label
user
watch.

other table is default data.
May be is data error,how to config other table in postgresql database?

**Comment by Unknwon** [comment]
... Please provide every step you did.
