### ISSUE TITLE
ssh url format does not play nice with cargo (rust build tool)

### ISSUE THREAD

**Issue by jonathanstrong** [gogits/gogs#4971]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Cargo, the Rust build tool, rejects the gogs ssh repo url format for "invalid port":

```
error: failed to parse manifest at `[...]/Cargo.toml`

Caused by:
  invalid url `ssh://git@git.domain.com:username/project.git`: invalid port number
```
The proposed workaround on their end is to change the url to `ssh://git@git.domain.com/username/project.git`, which I guess works on gitlab (but does not with gogs). Is there any similar simple hack available on the gogs side? Have already spent too much time on this and would like to move on! haha. I'm happy to spend a few minutes hacking the url parser but would appreciate some guidance first. Thought this would be a helpful issue for anyone else encountering the same problem.

**Comment by Unknwon** [comment]
To me, the URL `ssh://git@git.domain.com:username/project.git` is not correct / not complete. Gogs gives you SSH URL starts with `ssh://` only if you set the SSH port to non-22, which should include port number in the URL. Please check your configuration and report back.

**Comment by jonathanstrong** [comment]
This seems obviously wrong to me so I must be misunderstanding something. 

My install of gogs provides ssh urls in the format `ssh://git@git.domain.com:username/project.git`. So does the demo install: https://try.gogs.io/mirrors/ant-design. If that format is wrong / not complete, it's the one gogs is currently using. Can you please elaborate?

**Comment by Unknwon** [comment]
Nope, what I got is `git@try.gogs.io:mirrors/ant-design.git`, not `ssh://` prefix.

**Comment by jonathanstrong** [comment]
ah - ok, but is a url without a scheme a url? 

```
# in Cargo.toml (udp is just an example package)...
# [dependencies]
# udp = { git = "git@git.mmcxi.com:mm/udp.git" }
$ cargo update
error: failed to parse manifest at `~/src/deps/Cargo.toml`

Caused by:
  invalid url `git@git.domain.com:username/udp.git`: relative URL without a base
```

**Comment by Unknwon** [comment]
This is how Git works with URl, I'm not sure the detail inside.

**Comment by liangzi10101** [comment]
> This seems obviously wrong to me so I must be misunderstanding something.
> 
> My install of gogs provides ssh urls in the format `ssh://git@git.domain.com:username/project.git`. So does the demo install: https://try.gogs.io/mirrors/ant-design. If that format is wrong / not complete, it's the one gogs is currently using. Can you please elaborate?

I have the same problem with you, are you resolve this issue now?
