### ISSUE TITLE
Wrong translation "update profile"

### ISSUE THREAD

**Issue by FlyinDutchMen** [gogits/gogs#4977]
- Gogs version (or commit ref): 0.11.34.112
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/user/settings
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
Not relevant

## Description
The button "update profile" in the user settings has the wrong dutch translation.
it states "profile bijwerken" but it had the be "profiel bijwerken"

**Comment by Unknwon** [comment]
Refer solution to https://github.com/gogits/gogs/issues/4978.
