### ISSUE TITLE
Wrong dutch translation organizations

### ISSUE THREAD

**Issue by FlyinDutchMen** [gogits/gogs#4978]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: Not relevant
- Operating system: Not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) https://try.gogs.io/admin/orgs
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
The button "organizations" in the admin panel has the wrong dutch translation.
it states "orgranisaties" but it had the be "organisaties"

**Comment by knedlsepp** [comment]
Please provide the translation at https://crowdin.com/project/gogs as suggested here: https://gogs.io/docs/features/i18n
