### ISSUE TITLE
Deleting SSH key removes custom changes to authorized_keys file

### ISSUE THREAD

**Issue by jgrocho** [gogits/gogs#4980]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.11.3
- Operating system: Debian 8
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): not relevant

## Description

I am running gogs in a docker container and am sharing port 22 between the host and container as described at http://www.ateijelo.com/blog/2016/07/09/share-port-22-between-docker-gogs-ssh-and-local-system. Importantly, I've manually added to `~git/.ssh/authorized_keys`, inside the container, the line:

    no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa ... git@hostmachine

That works as expected. The problem occurs when a user deletes an SSH key from their account. As we can see from https://github.com/gogits/gogs/blob/v0.11.34/models/ssh_key.go#L515 this triggers a complete rebuild of `~git/.ssh/authorized_keys`, which eliminates the line above, preventing any pushes, etc.

I know the admin task to rebuild the file warns about losing non-Gogs keys, but deleting a user's key does not, nor should not.

**Comment by glw119** [comment]
I got the same problem....

- Gogs version (or commit ref): 0.11.34.1122 [Docker Image gogits/gogs:0.11.34]
- Git version: 2.11.3
- Operating system: CentOS 7 / Docker version 17.12.0-ce, build c97c6d6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

**Comment by petehalverson** [comment]
Confirmed. I have the same issue.

- Gogs version: 0.11.34.1122
- Git version: 2.11.3
- Operating system: Debian 9 / Docker 17.12.0-ce, build c97c6d6
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): n/a

**Comment by petehalverson** [comment]
Here's the workaround I'm using for now:

Since [sshd_config](https://www.freebsd.org/cgi/man.cgi?query=sshd_config&sektion=5&apropos=0&manpath=Debian+8.1.0) supports multiple files for `AuthorizedKeysFile`, using a secondary file that doesn't get overwritten by Gogs seems like a good temporary option.

Store the real key in the shared `~/.ssh` folder as `authorized_real_keys`, this is the key which should have the options prepended:

```
no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa
AAAAjjsdfSFHWER.................i30lijIJzx git@myserver
```

By appending `.ssh/authorized_real_keys` to the [existing sshd config the container uses](https://github.com/gogits/gogs/blob/4ea75dfcbe279dd5b59775a343ac930ca5bf01f4/docker/sshd_config), the shared real key will be read in on start.


```Dockerfile
# Dockerfile
FROM gogs/gogs
RUN sed -i '/AuthorizedKeysFile/ s/$/ .ssh\/authorized_real_keys/' /app/gogs/docker/sshd_config
```

**Comment by Unknwon** [comment]
That's the way it works, thus why do not run Gogs under user `root`...

**Comment by marioosh-net** [comment]
I had the same problem. My workaround for now is modified gogs (https://github.com/marioosh-net/gogs/commit/d2b92d0999bdffa2abf8c4ce04e8d0ce46778465) to store ssh keys in ~/.ssh/authorized_keys2 instead of. This file is by default used together with ~/.ssh/authorized_keys by ssh server.
