### ISSUE TITLE
SMTP Authentication with own server/Gmail not working

### ISSUE THREAD

**Issue by zkvvoob** [gogits/gogs#4988]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 1.9.1
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant - can't access Admin panel in the demo
- Log gist (usually found in `log/gogs.log`):
`2018/01/10 19:42:03 [ WARN] Failed to login 'me@myowndomain.com' via 'S13': EOF`
`2018/01/10 19:50:03 [ WARN] Failed to login 'zkvvoob@gmail.com' via 'Google': EOF`

## Description
Hello,
I've just finished installing Gogs on my server, I created a new admin user and tried to configure Authentication in the Admin panel to enable SMTP Auth.

I tried both my own SMTP server (Postfix/Dovecot), running on the same machine, and Gmail and both result in an error message on the login page:

> Username or password is not correct.

Can you help me figure out what's wrong?

Thank you!

**Comment by fr0der1c** [comment]
I've encountered the same problem. Do you have any solution?
