### ISSUE TITLE
nginx  proxy  gogs  https  

### ISSUE THREAD

**Issue by xingxing9688** [gogits/gogs#4994]
1. 使用nginx 直接proxy_paas 到https 的话  正确的配置是怎么样，如果我在nginx 中配置https 的话改怎么配置
DOMAIN       = abc.com 
HTTP_PORT    = 3000
ROOT_URL     =http://abc.com
DISABLE_SSH  = false
SSH_PORT     = 22
OFFLINE_MODE = false

如果我在这里指定协议为https 就启动报错，这个是什么原因导致的

**Comment by xingxing9688** [comment]
有没有nginx  proxy_paas 详细配置参考文件

**Comment by changsijay** [comment]
可以參考 https://blog.mynook.info/post/host-your-own-git-server-using-gogs/
