### ISSUE TITLE
Fork/pull request public repostories

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#5]
- [x] Fork repostories
- [x] Pull request repostories

**Comment by izolate** [comment]
Eagerly waiting PRs. Thanks @Unknwon

**Comment by kageurufu** [comment]
:+1: for sure

**Comment by Xe** [comment]
Is there any update on this feature?

**Comment by Unknwon** [comment]
@Xe it's WIP, but recently we've received big PRs, so currently work on PRs, will get back when finish reviewing.

**Comment by Xe** [comment]
Can you post the code as is in a feature branch? I'd be happy to help test and fix it.

**Comment by Unknwon** [comment]
@Xe We appreciate that! :facepunch: But we would like to fully on our own for the initial version :smile:

**Comment by xaionaro** [comment]
+1

**Comment by hasufell** [comment]
Yeah, very important feature. Pretty much the last thing missing before I remove gitlab from my server in favor of gogs.

+1 and keep up the good work

**Comment by dubcanada** [comment]
+1

**Comment by aPeer** [comment]
I upvote for Pull Requests as well!

**Comment by bartvankleef** [comment]
Can't wait to enjoy this feature!

**Comment by hermanbergwerf** [comment]
+1

**Comment by matrixik** [comment]
One question:
It is planed more like GitHub pull requests or do you plan to create something better? For example why Go team go with Gerrit (source: http://www.infoq.com/news/2014/11/golang-goes-git-github ):
> As mentioned, a Google-hosted instance of Gerrit will be used for code reviews. In a separate discussion about the use of Gerrit, Andrew Gerrand, Google Go engineer, explained that Gerrit has several advantages over GitHub's code review tool:
* In GitHub, merging pull requests causes pollution in the change history. "Gerrit will automatically rebase the changes atop the master branch head, leaving a nice linear history."
* GitHub forces contributors to create a public fork of the repository, if they do not have write access to it.
* Gerrit allows to collect many comments on a single pull requests, then just sending a single email.
* Gerrit supports multiple 'patch sets' for a particular change, which are particularly useful when reviewing large changes.

Personally I would love to see rebasing instead of merge commit (some background http://blog.spreedly.com/author/ntalbott/#.VGVhz5PF_Zs ).

Some more sites worth checking for improvements ideas (they exists on top of GitHub PR to fix it annoyances):
https://reviewable.io/
http://www.review.ninja/

**Comment by matrixik** [comment]
Phabricator.org and it code review part compared to Gerrit:
https://www.quora.com/Has-anyone-done-a-Gerrit-and-Phabricator-review

**Comment by hasufell** [comment]
> Personally I would love to see rebasing instead of merge commit

The important part about pull requests (IMO) is not that you can merge them via the web UI, but that you can do review/comments and get automatic mail notification etc. I would never do tasks like merging, rebasing or even committing in a web interface.

Also, if gogs would be more like gerrit, I would probably not use it, because gerrit is not simple and enforces a particular workflow on you.

**Comment by Unknwon** [comment]
Hi @matrixik , @hasufell , thanks for discussion!

For the initial purpose, Gogs would the pretty much the way GitHub does, but will open APIs/Webhooks to all of its actions as well. So that would be easier for people to integrate with any other services, and let Gerrit keep doing their good job.

**Comment by hickscorp** [comment]
+1, really waiting for PRs!

**Comment by mmikulicic** [comment]
+1

**Comment by nubbel** [comment]
+1

**Comment by bastiao** [comment]
I tested already the branch that says feature/pull-request but I did not see any button in the UI yet. Can you give us a status?

Thanks!

**Comment by thomasfedb** [comment]
:sparkles:

**Comment by Unknwon** [comment]
@bastiao Thanks for asking.

True reason is we don't want to be harry on such a important feature, but we're working on it. And feature itself isn't standalone, there are related things we need to work on at the same time. So, hmm, thanks for the patient.

**Comment by geshan** [comment]
+1 probably the only thing blocking people from adopting gogs

**Comment by StrangeWill** [comment]
+1, though work around is to just do it the old-school way.

**Comment by jbrodriguez** [comment]
+1, thanks for your efforts @Unknwon.

This was the feature most asked for in an [article](http://jbrodriguez.io/gogs-an-alternative-to-gitlab/) that was reposted on [HackerNews](https://news.ycombinator.com/item?id=9210978) and [Reddit](http://redd.it/2z836f)

**Comment by Techcable** [comment]
Github should add an upvote feature, my inbox is being spammed.

**Comment by tubia** [comment]
I totally agree with you @Techcable :)

**Comment by liminspace** [comment]
+1 for Pull Requests

**Comment by Knorkebrot** [comment]
Can we help somehow to make this happen faster? Don't forget, we're probably 95% devs here, too :)

**Comment by bastiao** [comment]
@Knorkebrot one of the problem is that @Unknwon is not accepting most part of the PR. There are quite a lot pending.

**Comment by xaionaro** [comment]
@bastiao, disagree. There's almost none PRs for such popular project. And most of them are quite fresh (the latest is "Mar 21").

**Comment by bastiao** [comment]
@xaionaro maybe I'm wrong then. If I can contribute some how, I'll be glad to help on that.

**Comment by matt-h** [comment]
@Unknwon is away from gogs right now. He hasn't said why or for how long, but I'm guessing it is either Family, School, or Work taking all of his time at the moment. I'm sure when he gets back he'll review the existing pull requests so keep making them if you have something to fix/add.

**Comment by csu** [comment]
+1

Would also be great to get forking/pull requests on private repositories.

**Comment by theAdmiral777** [comment]
+1

Having pull requests and being able to review team members' code would be really helpful.

**Comment by galoppa** [comment]
If only anybody were working on this feature... :/
I like gogs better than gitlab, but I think I'll switch to gitlab because this project looks dead and no longer maintained

**Comment by bartvankleef** [comment]
@Unknwon could you give us a short update on this?

**Comment by galoppa** [comment]
@bartvankleef  Somebody has finally forked it and I think they are working on both pull requests and wikis https://github.com/go-gitea/gitea

**Comment by liuyang1** [comment]
+1, It's really good of gogs's easy deployment feature. But I need "Pull Request" feature. Without that, cannot use gogs in a large team.

**Comment by bastiao** [comment]
any news? :)

**Comment by Unknwon** [comment]
@bastiao almost :)

**Comment by Unknwon** [comment]
OK, well. Hi all!

It's now able to test Pull Request on https://try.gogs.io/ . To keep your data safe and clean for future releases, please blow up it and post feedback here now! :wink:

**Comment by bastiao** [comment]
@Unknwon you're doing great!

**Comment by xaionaro** [comment]
A huge thanks!

**Comment by xaionaro** [comment]
P.S.: IMHO, PR's should be in separate tab (Pull Requests, not Issues). However this's anyway great :)

**Comment by Unknwon** [comment]
Thank you for following up! @bastiao @xaionaro 

@all: It's in very early stage, so... be nice... :eyes:

> P.S.: IMHO, PR's should be in separate tab (Pull Requests, not Issues). However this's anyway great :)

Yes, it will be added soon. I'm working on it.

**Comment by bastiao** [comment]
I'm updating my own installation and will test it properly. I will happy to return feedback too.

PS and offtopic: you should talk with people that fork gogs. It is not good to community to have disperse forks around. They was working on PR/forks too.

**Comment by bastiao** [comment]
```
# github.com/gogits/gogs/routers/api/v1
routers/api/v1/repo.go:105: opt.Gitignore undefined (type gogs.CreateRepoOption has no field or method Gitignore)
routers/api/v1/repo_hooks.go:29: unknown gogs.Hook field 'Id' in struct literal
routers/api/v1/repo_hooks.go:105: unknown gogs.Hook field 'Id' in struct literal
routers/api/v1/user.go:21: unknown gogs.User field 'Id' in struct literal
```

any idea why?

**Comment by Unknwon** [comment]
@bastiao 

```
go get -u github.com/gogits/go-gogs-client
```

and then rebuild

**Comment by bastiao** [comment]
@Unknwon great, thanks!

**Comment by mexthemax** [comment]
When opening a pull request the original repo gets a new open issue that is closed after merging.
This works for the issue view but in the overview for the original repo there is still one issue too much shown to be open. I think after mergin (which closes the "PR issue") the number of open issues should be decreased by one again.

e.g.:
When you had 10 open issues before the PR, you have 11 open after the PR, 10 open after merge but the overview still shows 11

(This was tested on try.gogs.io)

BTW: Thanks a lot for this feature.

**Comment by bastiao** [comment]
@Unknwon the PR does not work inside the same repository. Only in forks?

**Comment by Unknwon** [comment]
@bastiao right now, yes, only between forks(in same repo in the design though)

>  I think after mergin (which closes the "PR issue") the number of open issues should be decreased by one again.

@mexthemax good catch! Forgot that...

**Comment by Depado** [comment]
A friend of mine juste told me "Too bad it doesn't handle PRs". Went here. Saw the comment one hour ago saying it's now in test. Epic timing ! :dancer:

**Comment by ALenfant** [comment]
I am the friend in question. I've wanted to switch to Gogs for so long but I needed PR support. I'm so happy, thanks guys! :D

**Comment by Unknwon** [comment]
@ALenfant hah, :stuck_out_tongue_closed_eyes: 

Note it's still early stage and may not as perfect as you expected. But I'm here to fix problems. :eyes:

**Comment by zarezadeh** [comment]
A bug here: https://try.gogs.io/swordwinter/prtest/pulls there is two pull requests, one open and one closed. But when you click on open PR, it will show the close one. It seems both of them got same id

**Comment by Unknwon** [comment]
Thanks @zarezadeh ! I've pushed fix to try.gogs.io , and have fixed the index for your PR :)

**Comment by zarezadeh** [comment]
Very weird it's fixed now. Maybe gogs needs some time :)

**Comment by zarezadeh** [comment]
Wow, that was fast, thanks.

**Comment by vijairaj** [comment]
This looks great! Waiting for this to get in to master.

**Comment by bastiao** [comment]
If you can allow support of pull requests in the same project, between branches, it will be great!

**Comment by Unknwon** [comment]
OK, close right now.

Will open new issues for other specific needs.

**Comment by Unknwon** [comment]
**Important update** 

I've pushed code to `develop` branch and https://try.gogs.io that check if pull request has conflict with upstream every time fork repository or upstream repository is pushed, so conflict will be detected correspondingly right now.

Leave feedback here so I can help with further problems you may encounter! :beers:
