### ISSUE TITLE
Fail to save configuration: rename 

### ISSUE THREAD

**Issue by soulawaker** [gogits/gogs#5005]
- Gogs version (or commit ref):    0.11.34.1122
- Git version:  Gogs docker image version 
- Operating system: Docker 17.12.0-ce on Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
  Nothing useful.
## Description
First start in docker, Gogs shows the "Install Steps For First-time Run" page.
I've filled and tried to save. Then the following error occurred.
`Fail to save configuration: rename /data/gogs/conf/app.ini.735222149.tmp /data/gogs/conf/app.ini: device or resource busy`
I placed a custom `app.ini` to `/data/gogs/conf` by docker volume settings. But it's not read only.
User `git` has rw permissions on `app.ini`.
...

**Comment by soulawaker** [comment]
Ah, it's my fault. Never mind.

**Comment by sp1d3rino** [comment]
I have the same issue what's the problem? How did you solve it?

**Comment by soulawaker** [comment]
Oh, it's so late. I've remebered obscurely it was a permission related
thing on app.ini. I hope you had already solved it.

2018년 8월 3일 (금) 오전 5:49, sp1d3rino <notifications@github.com>님이 작성:
