### ISSUE TITLE
remote: Gogs: Internal errorTo http://... [remote rejected] master -> master (pre-receive hook declined)error: failed to push some refs to http://....

### ISSUE THREAD

**Issue by Sparkle24** [gogits/gogs#5012]
- Gogs version (or commit ref): 0.9.141_windows_amd64_mws
- Git version: 2.13.0.windows.1
- Operating system: Windows 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Hello!
There is few days ago, I can not do push to the master branch as a user with "Master" privileges. I was push without any problem before. 
I have the following message:
$ git push
Counting objects: 31, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (27/27), done.
Writing objects: 100% (31/31), 9.64 KiB | 0 bytes/s, done.
Total 31 (delta 22), reused 0 (delta 0)
remote: Gogs: Internal error
To http://172.*.*.*:3000/username/project_name.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://172.*.*.*:3000/username/project_name.git'

I also have this error when I launch Gogs as Windows service: Windows could not start the gogs service on Local Computer. Error 1067: The process terminated unexpectedly.

Thank you in advance for your help.

**Comment by Sparkle24** [comment]
Hello!
Any issue?

**Comment by aninfeel** [comment]
+1

**Comment by Sparkle24** [comment]
up

**Comment by Unknwon** [comment]
Hi, this version is way too old... consider upgrade first.
