### ISSUE TITLE
500 docker 

### ISSUE THREAD

**Issue by seven-tan** [gogits/gogs#5013]
2018/01/23 09:30:08 [xorm] [warn]  2018/01/23 09:30:08.604759 Table repository Column enable_wiki db default is 1, struct default is true
2018/01/23 09:30:08 [xorm] [warn]  2018/01/23 09:30:08.604841 Table repository Column enable_issues db default is 1, struct default is true
2018/01/23 09:30:08 [xorm] [warn]  2018/01/23 09:30:08.604870 Table repository Column enable_pulls db default is 1, struct default is true
2018/01/23 09:30:09 [xorm] [warn]  2018/01/23 09:30:09.536675 Table repository Column enable_wiki db default is 1, struct default is true
2018/01/23 09:30:09 [xorm] [warn]  2018/01/23 09:30:09.536732 Table repository Column enable_issues db default is 1, struct default is true
2018/01/23 09:30:09 [xorm] [warn]  2018/01/23 09:30:09.536756 Table repository Column enable_pulls db default is 1, struct default is true
2018/01/23 09:30:10 [xorm] [warn]  2018/01/23 09:30:10.744720 Table repository Column enable_wiki db default is 1, struct default is true
2018/01/23 09:30:10 [xorm] [warn]  2018/01/23 09:30:10.744797 Table repository Column enable_issues db default is 1, struct default is true
2018/01/23 09:30:10 [xorm] [warn]  2018/01/23 09:30:10.744821 Table repository Column enable_pulls db default is 1, struct default is true
2018/01/23 09:30:11 [xorm] [warn]  2018/01/23 09:30:11.636644 Table repository Column enable_wiki db default is 1, struct default is true
2018/01/23 09:30:11 [xorm] [warn]  2018/01/23 09:30:11.651619 Table repository Column enable_issues db default is 1, struct default is true

**Comment by windyugit** [comment]
I know this problem.   
SSH server started on 0.0.0.0:22221
2018/12/15 11:46:56 [FATAL] Fail to start SSH server: listen tcp 0.0.0.0:22221: bind: address already in use
So, Use the correct port when configuring
