### ISSUE TITLE
Migration Timeout and Subsequent HTTP 500

### ISSUE THREAD

**Issue by turbo** [gogits/gogs#5020]
- Gogs version (or commit ref):  0.11.34.1122
- Git version: 
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/turbo/SQLitePCL.raw
  - [ ] No
  - [ ] Not relevant

## Description

Trying to create a mirror of `https://github.com/ericsink/SQLitePCL.raw` with exactly that as the Git URL will timeout. Subsequently, the created repo URL throws a 500.

**Comment by Unknwon** [comment]
Just wait... as long as less than 10minutes, it will finish.

**Comment by theWayToAI** [comment]
I have encounted the same issue, and I have waited for more than 10 minutes, but it's still 500 error.What can i do to fix it?And now i even can't delete this repo...

- Gogs Version: 0.11.91.0811

**Comment by theWayToAI** [comment]
by the way , i deployed gogs by docker, and i cant wget thie repo so the network should be fine, maybe the repo is too large.What should i do to fix this problem in this case?

**Comment by unknwon** [comment]
@theWayToAI Technically Gogs would clean it up when failed, other cases, you could go to admin (`/admin/repos`) and remove it directly.
