### ISSUE TITLE
Long GC pause

### ISSUE THREAD

**Issue by montyz** [gogits/gogs#5021]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.11.3
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
Oh, sorry, rebooted before I got that.

## Description

40 sec GC pauses, see attached pdf for my admin page with more statistics. I'm using the docker image tagged 0.11.34 (currently latest) from https://hub.docker.com/r/gogs/gogs/. It had been running for 32 days.

[gogs-gc.pdf](https://github.com/gogits/gogs/files/1680065/gogs-gc.pdf)

Let me know if there are any other diagnostics to run if this happens again.

**Comment by Unknwon** [comment]
Hi, that is sum of all GC pauses, which harms nothing just some information from runtime. :D
