### ISSUE TITLE
Some page can't open

### ISSUE THREAD

**Issue by ivories** [gogits/gogs#5029]
- Gogs version (or commit ref): develop / lastes
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

I use docker start gogs. I use gogs for a long time ,about three month.
When i reboot the server, and start the gogs. some page can visit,but some can not .

can visit page:
/user/login
/issues
/pulls
/explore/repos
/user/settings

can't visit page:
html/template: "home" is undefined
html/template: "repo/create" is undefined
html/template:repo/diff/page:6:14: no such template "repo/commits_table"
html/template:repo/issue/view:3:12: no such template "repo/header"

**Comment by ivories** [comment]
I found the solution, use https://about.gitlab.com/ to replace gogs, oh yeah,done.

**Comment by Unknwon** [comment]
Technology does save people :D

**Comment by ivories** [comment]
Please do not use gogs under docker, i try backup and restore in ubuntu, run gogs very good. 

But  i restore gogs under docker,it is broken again. 

So, i really suggested @Unknwon to support docker.

**Comment by marshallford** [comment]
I am running into the same issue. I was hoping to run Gogs in K8s!
