### ISSUE TITLE
Disable some locale

### ISSUE THREAD

**Issue by lexesv** [gogits/gogs#5039]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ *] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ *] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
How to disable some locale without removing files at conf/locale?
Thanks.

**Comment by farshmak** [comment]
override settings **custom/conf:**
```
[i18n]
LANGS = en-US
NAMES = English
```
