### ISSUE TITLE
Please guys continue gogs project.

### ISSUE THREAD

**Issue by gurussia** [gogits/gogs#5049]
HI guys please continue gogs project. I try gitlab and it is very bad comment how to install, include it don't support latest ubuntu 17.10 server version, you has to make hack to make it work but maybe it will not work. gogs is wonderfull program too.

**Comment by Pofilo** [comment]
Gitea is a good fork, unfortunately, there is no way to migrate with latest version of gogs (you would loose your issues for example ..)

**Comment by variablenix** [comment]
Is the Gogs project dead? Should people be migrating away from Gogs?

**Comment by bclermont** [comment]
this project is dead, stop wasting your time.
go to https://github.com/go-gitea/gitea/

**Comment by stumpner** [comment]
This should be written in the readme.md that the project is dead and to use gitea.

**Comment by bclermont** [comment]
don't bother, it's abandonware.
there is unreviewed 37 pull requests.
If you create a pull request to add this to `README.md` it will never be looked at by @Unknwon and never merged

**Comment by appleboy** [comment]
@stumpner you can try gitea on line. See https://try.gitea.io/ and we will release `v1.4.0` asap. See the change log: https://github.com/thehowl/blog-1/blob/release-1.4.0/content/post/release-of-1.4.0.md

**Comment by 4nd3r** [comment]
> this project is dead, stop wasting your time.

[citation needed]

**Comment by bclermont** [comment]
@4nd3r look at the activity of this repository.
Unknown don't accept collaborator and no commits in 4 months.

**Comment by 4nd3r** [comment]
> no commits in 4 months

and that's it? maybe gogs is finished "product"? some people prefer stability over constant "betterment".

or maybe @Unknwon is working privately and will push when time is right.

going around and spamming "dead project" is just spreading FUD. please don't do it.

**Comment by imilo** [comment]
It would be great if someone of main developers at least notify a community about their plans. It's Ok if you continue after a month, 2 or 6, etc, but at least we will have some info

**Comment by joubertredrat** [comment]
This story is so old, @Unknwon disappearing and appearing months later. Gogs is good project in wrong hands. Because this exists Gitea.

**Comment by Unknwon** [comment]
Haven't had chance to install Ubuntu 17.10 yet, not sure what is different from 16.10...

**Comment by Unknwon** [comment]
One last statement for such topic:

Thanks for everyone who likes the project, and everyone who doesn't like it. Go ahead and fork, 100% good. I never said fork is evil, don't speak like I'm someone's enemy. Don't be aggressive, I won't get it. 

Because you have your faith, I have my life. And 

YOUR FAITH CAN'T SAVE MY LIFE.

Until then, keep hands dirty and quiet, please.
