### ISSUE TITLE
Commits not merged after accepting pull request using rebase

### ISSUE THREAD

**Issue by luismbo** [gogits/gogs#5051]
I just tried to use Gogs for the first time over at https://try.gogs.io/ and found the following issue:

1. Created a new repo at https://try.gogs.io/luismbo/foo/ with an initial commit generated using templates.
2. Pulled it via HTTS.
3. Created a new branch with two new commits and pushed it to Gogs.
4. Created a pull request: https://try.gogs.io/luismbo/foo/pulls/2
5. Enabled "Allow use rebase to merge commits" and accepted the pull request using that method.

At this point I expected the new commits to be in the master branch but I can't find them.

**Comment by oneWayOut** [comment]
I had a similar issue:
I tried to do a pull request at https://try.gogs.io,
But there is no "rebase and  merge" option, only "Create a merge commit" is displayed.
Is the Gogs team disable this useful feature??

**Comment by jpleau** [comment]
@oneWayOut You have to enable it per repo it seems, in the settings

@luismbo can confirm, I have enabled the rebase feature, and after merging the pull request nothing happened.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by luismbo** [comment]
@Unknwon works for me. Thanks!

**Comment by vision-ken** [comment]
Rebase can't be used while using pull request now？
