### ISSUE TITLE
Once branch was protected "Lock" icon will never be removed

### ISSUE THREAD

**Issue by MrTypename** [gogits/gogs#5053]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.16.1
- Operating system: Windows
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

Once a branch is protected by "Settings/Branches/Protect this branch" and later option is disabled again, the "Lock" icon within the branch overview list will never be removed again:

![clipboard01](https://user-images.githubusercontent.com/36326219/36342826-44ca362c-1404-11e8-9433-d1cddebd526f.jpg)

**Comment by MrTypename** [comment]
Thx. That was really fast 👍

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5054, please help test on `develop` branch.
