### ISSUE TITLE
how could I config the crontab to make gogs run after it crash ?

### ISSUE THREAD

**Issue by msongz** [gogits/gogs#5055]
crontab:
```
* * * * * sh gogs.sh
```
gogs.sh:
```
#!/bin/bash
pidof gogs > /dev/null
if [ $? -ne 0 ] ; then
   /home/pi/gogs/gogs web &
fi
```

and it always say:
when pi user:
```
[FATAL] [...g/setting/setting.go:571 NewContext()] Expect user 'pi' but current user is:
```
when root user:
```
[FATAL] [...g/setting/setting.go:571 NewContext()] Expect user 'root' but current user is:
```

**Comment by bclermont** [comment]
this project is dead, stop wasting your time.
go to https://github.com/go-gitea/gitea/

**Comment by Unknwon** [comment]
>Expect user 'root' but current user is:

To fix such error, you need to set `$USER` environment variable in the script that runs Gogs.
