### ISSUE TITLE
Disabling attachments breaks issues and comments ajax submit

### ISSUE THREAD

**Issue by 4d47** [gogits/gogs#506]
- Update config to `ENABLE = false` [attachment]
- Try to create a new issue or comment
Issue/comment is created correctly but clicking submit loads a JSON document {ok: true, status: 200} in browser instead of changing the button to "Submiting..." and redirecting.

After investigation I found a click handler on the submit button (button.btn-success.btn) was missing compared to try.gogs.io. It looks like something missing in js/app.js makes the page do the default `<form submit`.

**Comment by Unknwon** [comment]
This is somewhat fixed...
