### ISSUE TITLE
数据库设置不正确：Error 1709: Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by eippbx** [gogits/gogs#5066]
Install Gogs init page (:3000/install) error

**Comment by eippbx** [comment]
Mysql 5.6  innodb_page_size=16k，https://help.aliyun.com/knowledge_detail/41707.html

**Comment by levinit** [comment]
升级mysql或maridb
或者
打这个补丁https://github.com/m2nlight/gogs/releases/tag/v0.11.34_patch

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/4894.
