### ISSUE TITLE
An idea for the git

### ISSUE THREAD

**Issue by Xeblo** [gogits/gogs#5067]
Hello,
I am not particular bug, but I come to give an idea for the git.
A **"Project"** part should be added with different columns (to do, in progress, done). Add, another tab at the level of commits, contributor ... to add the name of the license, and that when we click on it it redirects us to the license in our directory, with what we have the right to do and not to do, as on GitHub, it will be easier.

It should also be possible to change the homepage when we are not logging into our account.

Sincerely, Mael

**Comment by Unknwon** [comment]
Sorry, sounds good, but you're asking too many in very little words.
