### ISSUE TITLE
Add incremental backup?

### ISSUE THREAD

**Issue by antonchen** [gogits/gogs#5070]
Hi @Unknwon,

I need to backup from gogs to other disks (a networked storage, it's a directory on Linux).

Now gogs backup is a complete compressed document, which requires a lot of storage space, longer backup time.

Can consider adding an incremental backup option and does not compress the backup?

**Comment by Unknwon** [comment]
Hi... though this is a reasonable feature request, but I know very little (almost nothing) about how to do incremental backup. I would love to have such feature as well. 

In fact, if you don't backup Git repositories (just database and other files), the archive size should be reduced in significant amount. Is that what you're looking for?

**Comment by antonchen** [comment]
I need to back up all the data.

I have an idea, please consider whether it is reasonable:

Use `git mirror` backup or realize master slave (Create a hook for all git repository, call the slave `git remote update`).

**Comment by antonchen** [comment]
Sorry, my English is not good.

The main reason for using English is that other people are expected to participate in the discussion, but it seems that no one else is interested in the issue right now.

If you are interested in my ideas, we can communicate by email.

My email: ` echo 'YW50b25jaGVuQGhvdG1haWwuY29tCg=='|base64 -d`

**Comment by Unknwon** [comment]
@antonchen You can join Gogs Discord and PM me.
