### ISSUE TITLE
IPython notebook: SVG support

### ISSUE THREAD

**Issue by rubenv** [gogits/gogs#5077]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 
- Operating system: Docker image
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes: https://try.gogs.io/rubenv/ipython-notebook-svg/src/master/prob-01.ipynb
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): none

## Description

Hi! I'm **super** pleasantly surprised to see that IPython notebooks are rendered. That's totally awesome and unexpected.

It seems that rendering SVG files is currently missing:

![screenshot from 2018-03-06 10-40-26](https://user-images.githubusercontent.com/42904/37024997-cc83af48-212a-11e8-95d8-0dc5351bde0e.png)

This should be rather trivial to add, as the SVG file is embedded in the notebook file.

Sample file attached.

[prob-01.zip](https://github.com/gogits/gogs/files/1784369/prob-01.zip)

**Comment by rubenv** [comment]
Looks like a bug in notebookjs: https://github.com/jsvine/notebookjs/pull/14

Sent a PR that should fix things.

**Comment by rubenv** [comment]
@Unknwon Patch to notebookjs has landed, now we just need to update the bundled copy in gogs to `0.3.0`.

**Comment by rubenv** [comment]
PR #5084 submitted

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/rubenv/ipython-notebook-svg/src/master/prob-01.ipynb.

**Comment by rubenv** [comment]
Looks exactly what it should look like, thanks for merging!
