### ISSUE TITLE
Docker: Delete public key does not update '.ssh/authorized_keys' file

### ISSUE THREAD

**Issue by MegaphoneJon** [gogits/gogs#5088]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.11.3
- Operating system: alpine (docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x]  Not relevant
- Log gist (usually found in `log/gogs.log`):
Not relevant

## Description
This is a regression of #2447/#2540.  Deleting a key doesn't remove it from `authorized_keys`, which often leads to trouble when you re-add the key without running the "Rewrite '.ssh/authorized_keys' file" job. A couple people are indicating this same issue on #2447.

**Comment by sinlov** [comment]
authorized

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogits/gogs/issues/5087.
