### ISSUE TITLE
error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401 (ONLY ON HTTP)

### ISSUE THREAD

**Issue by PVineeth** [gogits/gogs#5089]
@Unknwon Hi!

I am trying to push repos to my Gogs server.

I am able to successfully push using SSH but pushing with HTTP fails. I even tried pushing it directly using http://example.com:3000 as remote URL. But it fails.

I get an error like this:

`error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401
fatal: The remote end hung up unexpectedly
Writing objects: 100% (3446965/3446965), 650.43 MiB | 50.34 MiB/s, done.
Total 3446965 (delta 2881846), reused 3446937 (delta 2881827)
fatal: The remote end hung up unexpectedly
Everything up-to-date
`

I checked with my username & password too. I had no problem.

**Comment by Unknwon** [comment]
Hi, you can find this issue is duplicated to https://github.com/gogits/gogs/issues/4718. If Gogs says it's wrong (i.e. 401)... then I would believe it's wrong password.

**Comment by raandree** [comment]
I have the same issue with TFS and Git 2.21.0. It seems to be an issue with Git and the size of the the repo / of some change. The password is correct for sure. At least it works with a small test repo so it cannot be the password.
