### ISSUE TITLE
docker : Failed to run built-in ssh server, 

### ISSUE THREAD

**Issue by vmonteco** [gogits/gogs#5092]
- Gogs version (or commit ref): Latest docker image (sha256:f23a2efe3e3fa1eb76a6a525e6167dcd79ba14b5a33d6b8668c3a1e4a8be4b65)
- Git version: 2.11.3
- Operating system: ArchLinux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When trying to run a gogs container it fails to start the built-in ssh server :

```
2018/03/12 00:52:29 [TRACE] Custom path: /data/gogs
2018/03/12 00:52:29 [TRACE] Log path: /app/gogs/log
2018/03/12 00:52:29 [TRACE] Build Time: 2018-03-06 11:05:39 UTC
2018/03/12 00:52:29 [TRACE] Build Git Hash: 
2018/03/12 00:52:29 [TRACE] Log Mode: Console (Trace)
2018/03/12 00:52:29 [TRACE] Log Mode: File (Trace)
2018/03/12 00:52:29 [ INFO] Gogs 0.11.36.0306
2018/03/12 00:52:29 [ INFO] Cache Service Enabled
2018/03/12 00:52:29 [ INFO] Session Service Enabled
2018/03/12 00:52:29 [ INFO] Mail Service Enabled
2018/03/12 00:52:29 [ INFO] Register Mail Service Enabled
2018/03/12 00:52:29 [ INFO] Notify Mail Service Enabled
2018/03/12 00:52:29 [ INFO] Git Version: 2.11.3
2018/03/12 00:52:29 [ INFO] SQLite3 Supported
2018/03/12 00:52:29 [ INFO] Run Mode: Production
2018/03/12 00:52:29 [TRACE] Doing: CheckRepoStats
2018/03/12 00:52:29 [ INFO] SSH server started on 0.0.0.0:22
2018/03/12 00:52:29 [FATAL] Fail to start SSH server: listen tcp 0.0.0.0:22: bind: permission denied
```

Here is my `docker-compose.yml` :

```
---
version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gogs_password
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=gogs_password
    volumes:
      - db:/var/lib/mysql
  gogs:
    image: gogs/gogs
    environment:
      - VIRTUAL_HOST=mygogs.com
      - VIRTUAL_PORT=3000
    ports:
      - "22:22"
    depends_on:
      - db
    links:
      - db
    volumes:
      - data:/data

volumes:
  data:
  db:

networks:
  default:
    external:
      name: nginx-proxy
```

I've seen in this issue : 
#4961  

That I should `sudo setcap CAP_NET_BIND_SERVICE=+eip /path/to/gogs`.
But the `gogs/gogs` image is based on alpine and doesn't provide setcap (nor sudo) (unless you update and install it), plus having to rebuild a gogs image makes the `gogs/gogs` image a bit useless.

Anyway, adding `sh -c "apk update && apk add sudo libcap && setcap CAP_NET_BIND_SERVICE=+eip /app/gogs/docker/s6/gogs && /bin/s6-svscan /app/gogs/docker/s6/" as a command for the gogs container in `docker-compose up -d` results in an usage error with the `setcap` call :

```
gogs_1  | Failed to set capabilities on file `/app/gogs/docker/s6/gogs' (Invalid argument)
gogs_1  | usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
gogs_1  |
gogs_1  |  Note <filename> must be a regular (non-symlink) file.
```

How could I set up the ssh builtin server without having to make my own image?

I use a custom network because I use this container with `nginx-proxy`+`letsencrypt-nginx-proxy-companion`.
...

**Comment by Unknwon** [comment]
I think it is Linux basic to know special ports (<1024) requires root permission. You can set Gogs builtin SSH server to listen on 2222 which should work (except ugly SSH clone URL). Otherwise, use sshd which comes with Gogs Docker image.
