### ISSUE TITLE
git clone with ssh prompt for gogs password

### ISSUE THREAD

**Issue by qxing3** [gogits/gogs#5103]
$ git clone ssh://gogs@gogs.domain:9022/qi.xing/dockerfile-sample.git
Cloning into 'dockerfile-sample'...
gogs@gogs.21vtech.com's password:
Permission denied, please try again.
gogs@gogs.21vtech.com's password:

> Gogs Version: 0.11.34.1122

/home/gogs/gogs/custom/conf/app.ini
```
APP_NAME = Gogs: Go Git Service
RUN_USER = gogs
RUN_MODE = prod

[database]
DB_TYPE  = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = root
PASSWD   =
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = /home/gogs/gogs-repositories

[server]
DOMAIN       = gogs.21vtech.com
HTTP_PORT    = 3000
ROOT_URL     = https://gogs.21vtech.com/
DISABLE_SSH  = false
SSH_PORT     = 9022
OFFLINE_MODE = false
......
```

**Comment by chaoMaster** [comment]
and the git version 
> git version 2.14.2

**Comment by jszsj** [comment]
@qxing3 Did u fixed the issue?

**Comment by Unknwon** [comment]
@hasufell https://discuss.gogs.io/t/how-to-config-ssh-settings/34
