### ISSUE TITLE
docker gogs mysterious port mapping 1342

### ISSUE THREAD

**Issue by razaborg** [gogits/gogs#5106]
I noticed a strange behavior from my gogs container : 
```
a6edf8301633 gogs/gogs ... Up About a minute 22/tcp, 3000/tcp, 0.0.0.0:32787->1342/tcp gogs
```

And more precisely this : `0.0.0.0:32787->1342/tcp` ?! What exactly is this port binding for ? 

I didn't get to manually map `127.0.0.1:32787->1342/tcp` because the host port always change.
This is very embarassing from a security point of view, firstly because I don't know what it is, second because I don't want it, and third because it's exposed to all the host interfaces.

So... could anyone give me some informations about this mysterious 1342 port mapping ?  And how to bind it only locally ?

**Comment by mikesnoerenschool** [comment]
q

**Comment by Unknwon** [comment]
Hi, by searching this number (1342) over the repository: https://sourcegraph.com/search?q=1342&sq=repo%3A%5Egithub%5C.com%2Fgogits%2Fgogs%24

Not found this is used anywhere from Gogs main repository or vendor, so I suspect it related your Docker setup or some tools automated mapping.
