### ISSUE TITLE
WEB端文件上传大小限制问题排查，已修改配置文件

### ISSUE THREAD

**Issue by blue20080** [gogits/gogs#5109]
如题所示，
已修改配置文件，增加如下配置：
[repository.upload]
ENABLED = true
ALLOWED_TYPES =
FILE_MAX_SIZ = 50M
MAX_FILES = 100

修改后重启服务，进行文件上传，但页面仍提示超过3M限制。
请问该如何跟踪排查？感谢！

版本：0.11.34  二进制安装
操作系统：centos7.2

**Comment by zoeDylan** [comment]
如果你服务器用的nginx，在nginx.conf里面修改上传大小

```
 server {
                listen 80;
                server_name ***.com;
                # 主要是这一句
                client_max_body_size 1024m;
               location **
}
```

**Comment by yedajiang44** [comment]
@zoeDylan 然而并没有用。。。我是多域名反向代理80端口的
