### ISSUE TITLE
Push fails for LFS-enabled repositories

### ISSUE THREAD

**Issue by b0ssi** [gogits/gogs#5110]
- Gogs version (or commit ref): 0.11.34.1122
- Git version:
  - server: 2.11.0
  - client: 2.16.2
- Git LFS version:
  - server: n/a
  - client: git-lfs/2.3.4 (GitHub; linux amd64; go 1.9.2; git 7f83b43)
- Operating system:
  - server: Debian 9.4
  - client: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) - Can only provide empty git repository as the issue prevents me from pushing (see further details[1] below)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

[1]: Steps to repro: Initialize new repo on a client that has LFS enabled; add an arbitrary binary file and track it with LFS. Commit and push to this repo. It will fail with (the try.gogs.io server should probably have a `FATAL` log entry in its `serv.log` (see below)):

> Git LFS: (0 of 1 files) 0 B / 512 B                                                                          
> batch response: Repository or object not found: https://try.gogs.io/bossi/foo.git/info/lfs/objects/batch
> Check that it exists and that you have proper access to it
> error: failed to push some refs to 'https://try.gogs.io/bossi/foo.git'

## Description

Pushing to a *Gogs* repository seems to cause the server to fail with the following message getting logged in `<installRoot>/log/serv.log`:

> [FATAL] [...its/gogs/cmd/serv.go:166 runServ()] Repository does not exist: <user>/<repo>.git upload

This is most likely specific to the following configuration:
* repository has more than one remote configured, with the "primary" (tracking) having LFS support and gogs being one of the secondary (precedence irrelevant though)
* `git lfs url` is not explicitly specified in the repository's `.git/conf`

This causes git lfs to try and push to the gogs repository as well on push and cause the above failure.

## Temporary Solution
Setting `git config --add lfs.url <httpLfsUrl.git/info/lfs>` explicitly solves the problem, getting git to  always push LFS objects to that (non-gogs) LFS endpoint, even when pushing to gogs.

**Comment by Unknwon** [comment]
Hi, Git LFS is not currently supported, please see https://github.com/gogits/gogs/issues/1322.

**Comment by b0ssi** [comment]
Thanks @Unknwon - I was aware of the lack of *active* support but thought this edgecase might still be worth mentioning as it comes across a tad like buggy behavior still, even knowing there is no *active* LTS support on Gogs at the moment - seems to sit somewhere in between :thinking:
