### ISSUE TITLE
建议对于未登录的用户关闭“发现” 功能

### ISSUE THREAD

**Issue by bigbenz8** [gogits/gogs#5116]
目前太暴露了 ，没有登录的用户直接能看到已注册的用户和组织， 这不科学 不够保密。

我目前只能用服务器屏蔽这两个地址，希望改进。。

**Comment by yangbinnnn** [comment]
配置 `REQUIRE_SIGNIN_VIEW = true` 要求用户必须登录才能浏览任何页面
