### ISSUE TITLE
how to change the default language "zh" to "en" ？

### ISSUE THREAD

**Issue by vaptu** [gogits/gogs#5119]
- Gogs version (or commit ref): 0.11.31.1022
- Git version: 2.11.3
- Operating system: Alpine Linux 3.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

how to change the default language "zh" to "en" ？

**Comment by zoeDylan** [comment]
![image](https://user-images.githubusercontent.com/7030260/37945754-5197a1e6-31b4-11e8-99bc-a0fb810ac221.png)

## at footer
