### ISSUE TITLE
Support for internal visibility like gitlab?

### ISSUE THREAD

**Issue by fduxiao** [gogits/gogs#5121]
(Followings are from docker image f23a2efe3e3f)
- Gogs version (or commit ref):  0.11.36.0306
- Git version: 2.11.3
- Operating system: 
  ```shell
   $ uname -a
   > Linux 2fa12c5c7d12 4.15.7-1.el7.elrepo.x86_64 #1 SMP Wed Feb 28 14:38:13 EST 2018 x86_64 Linux
  ```
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

## Description
Internal visibility like [gitlab](https://docs.gitlab.com/ce/public_access/public_access.html) ：
![example](https://docs.gitlab.com/ce/public_access/img/restrict_visibility_levels.png)
I'd like to demonstrate some of my projects to the public while others are restricted to my organization members only. So one doesn't have to suffer from selecting all users as a team.

**Comment by Unknwon** [comment]
I think it's same as https://github.com/gogits/gogs/issues/2308.
