### ISSUE TITLE
Database Backup/Restore when Upgrading

### ISSUE THREAD

**Issue by netlander** [gogits/gogs#5130]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

After looking at the [Docker Page](https://github.com/gogits/gogs/tree/master/docker), upgrade section, it's not clear how and when to point the new Docker container to the existing database.

The [Upgrade from Binary](https://gogs.io/docs/upgrade/upgrade_from_binary) explains how the volumed data should be copied over from the old install but nothing is said about how to restore the database (MySQL in this particular case).
...

**Comment by Unknwon** [comment]
https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991.

PS: Gogs does not delete anything during upgrade, you just replace files and run.
