### ISSUE TITLE
centos 6.5 无法自动启动

### ISSUE THREAD

**Issue by kokorodo** [gogits/gogs#5131]
请问在centos 6.5 中，那个服务启动一直没有成功，看了log提示说了mysql无法连接。但是我用service gogs start 的时候，就可以成功启动gogs，所以推测是自动启动gogs的时候，mysql服务还没有启动，查了一下chkconfig的启动顺序，gogs 是在 mysql 之后启动的，所以这个问题一直想不明白，官方的文档中的service 脚本是针对centos7的，所以在6.5中没有办法使用，请问还有其他的方法来解决这个依赖的问题吗？

**Comment by kokorodo** [comment]
请问，被close掉，是因为我说明不清楚吗？

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by kokorodo** [comment]
ok，sorry。
