### ISSUE TITLE
Unable to Change Settings in Config Page

### ISSUE THREAD

**Issue by netlander** [gogits/gogs#5134]
- Gogs version (or commit ref): 0.11.43.0330
- Git version: 
- Operating system: Docker (Alpine Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Just finished installing a fresh docker image, added database details and admin user at the install page. The Gogs install starts well.

When I access http://blah.com/admin/config, I am able to see the settings but totally unable to change any of the settings or tick any boxes to make changes to the settings.

Is this a feature of the software? If so where is the best place to change settings after installation?
...

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1072.
