### ISSUE TITLE
500 when merge branch to master when it's not the default branch

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#5138]
- Gogs version (or commit ref): 0.11.43
- Git version: 1.8
- Operating system: CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/tacyuuhon/demo/pulls/1)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

```
An error has occurred : git checkout 'master': error: pathspec 'master' did not match any file(s) known to git.
```

## Description

Reference: https://discuss.gogs.io/t/pr-500/1801

**Comment by 502647092** [comment]
@Unknwon

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
