### ISSUE TITLE
Board system based on project organization

### ISSUE THREAD

**Issue by kuchaguangjie** [gogits/gogs#5140]
After using gogs for a while, wondering whether gogs could provide another version of issue / task management.

**The problem:**  
 - Seems gogs's `issue` and `milestone` only belong to a single project, the issue number is not unique among multiple projects, even though 2 projects belong to the same organization.
 - This seems not best suit for a micro service system using scrum based agile development. Since there are always multiple sub projects within the top project, it's difficult to have an overview of tasks in the top project or a scrum.

**Suggestion:**
 - Create a kind of issue/task management functionality, that could create a `scrum` belongs to an organization or a group of projects, (_similar as what `JIRA` provides_).
 - Thus, the scrum could contain multiple projects.
 - And, could create task that belongs to the organization or scrum, so that the task number could be unique among tasks within the organization.

There might be existing tools that provide similar functionality described above, and able to integrate with gogs, but I am not sure, didn't investigate yet.

Anyhow, it would be nice, if gogs could have such a built-in task management service.

Thanks.

**Comment by Unknwon** [comment]
Though good suggestion, it could be asking too much for Gogs, especially involves a lot of FE work. Use professional tools to do the professional work.

**Comment by Unknwon** [comment]
Just realize this is duplicated to https://github.com/gogits/gogs/issues/3716.

**Comment by kuchaguangjie** [comment]
The issue & board feature that `gitlab` provides is also a bit different from what JIRA's scrum provides, I think.

Gitlab has a board which is similar as kanban, and it's milestone could be based on group, not just a single project, that's great.

But, there is still a big **difference**:  
  The issue of gitlab must belong to a single project, and each project has its own issue number. This is quite different from what JIRA's sprint feature provides, in JIRA the task id could be unique among a group of projects, that's easier to track when there are many sub projects in a group, in scrum development.

**Comment by Unknwon** [comment]
@kuchaguangjie you can comment on the thread about organizational level broad. And keep in mind it is definitely not going to happen that a heavyweight broad system will exist in Gogs main repository because as I stated: use professional tools to do the professional work.

**Comment by kuchaguangjie** [comment]
@Unknwon I agree in some degree, maybe could add scrum tool in plugin mode to keep the gogs core focused. Anyhow, I am looking for some replacement for JIRA now due to its license issue.

**Comment by Unknwon** [comment]
>maybe could add scrum tool in plugin mode to keep the gogs core focused

That's really depends on if someone has deep understanding of how JIRA works and has the effort to implement one. :rofl:

**Comment by kuchaguangjie** [comment]
@Unknwon Yep, both golang & gogs are interesting, so maybe I would take a look when have spare time :)

**Comment by Unknwon** [comment]
But the plugin system needs some time to figure out how to do it... no experience about such topic before, very hard for me.

**Comment by kuchaguangjie** [comment]
@Unknwon Yeah, right.
