### ISSUE TITLE
Gogs in docker can't listen 3000 port

### ISSUE THREAD

**Issue by chinakevinguo** [gogits/gogs#5145]
- Gogs version: gogs/gogs:latest 
- Git version: 
- Operating system:  CentOS7 64bit
- Database (use `[x]`):
  - `[x]` SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - `[x]` No
- Log gist (usually found in `log/gogs.log`): just display listen port on 22

## Description

Hi:
    My gogs is started in the docker with docker-compose. But, recently, when I accidentally restarted docker, and found that gogs didn't listen port on 3000, just listen port on 22, and when I modified the conf in the directory, it found it didn't work.May be the conf store in SQLite ,and my sql file was broken ???

**Comment by Unknwon** [comment]
Please provide error log in `log/gogs.log`, not what you see from Docker logs.

**Comment by chinakevinguo** [comment]
This is not a issue ,because my data is so big ,and gogs will take long time to load(about 30min),so ,just wait ...it will be ok by itself .

**Comment by Unknwon** [comment]
...
