### ISSUE TITLE
配置Cache的问题

### ISSUE THREAD

**Issue by MiderWong** [gogits/gogs#5154]
Cache使用Redis，配置失败
1、按照官方文档配置cache时出现问题：
官方文档：<a href="https://gogs.io/docs/advanced/configuration_cheat_sheet#%E7%BC%93%E5%AD%98-(cache)" target="_blank">Gogs-configuration_cheat_sheet-cache</a>
本地配置如下：
```
[cache]
; Either "memory", "redis", or "memcache", default is "memory"
ADAPTER = redis
; For "memory" only, GC interval in seconds, default is 60
INTERVAL = 60
; For "redis" and "memcache", connection host address
; redis: network=tcp,addr=:6379,password=macaron,db=0,pool_size=100,idle_timeout=180
; memcache: `127.0.0.1:11211`
HOST = network=tcp,addr=:6379,password=redisserver#$%123aa,db=15,pool_size=100,idle_timeout=180
```
提示错误如下：
```
panic: ERR invalid password

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-macaron/cache.Cacher(0xc420a8ee00, 0x1, 0x1, 0xce6e00, 0xc42074e580)
```
遂找到框架`Macaron`中关于Redis的配置说明：
说明地址：<a href="https://go-macaron.com/docs/middlewares/cache#redis" target="_blank">Macaron缓存管理之Redis</a>，按照官方的说明地址修改为如下内容：
```
[cache]
; Either "memory", "redis", or "memcache", default is "memory"
ADAPTER = redis
; For "memory" only, GC interval in seconds, default is 60
INTERVAL = 60
; For "redis" and "memcache", connection host address
; redis: network=tcp,addr=:6379,password=macaron,db=0,pool_size=100,idle_timeout=180
; memcache: `127.0.0.1:11211`
AdapterConfig = network=tcp,addr=:6379,password=redisserver#$%123aa,db=15,pool_size=100,idle_timeout=180,hset_name=GogsCache,prefix=cache:
```
启动时又出现如下错误：
```
panic: key-value delimiter not found: data/caches

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-macaron/cache.Cacher(0xc420a3ae00, 0x1, 0x1, 0xce6e00, 0xc42070a9a0)
```
请问有人配置成功了么？

**Comment by MiderWong** [comment]
使用HOST配置没有问题，错误原因在于我的Redis密码中含有需要转义的字符
使用框架Macaron官方AdapterConfig配置时还是会提示`panic: key-value delimiter not found: data/caches
`错误，看来Gogs在使用Macaron框架的Cache时对配置文件做了本地化处理

**Comment by MiderWong** [comment]
想请教一下，使用`go-ini/ini`解析ini配置文件时，`value`中含有特殊字符，如 `#$%^&*@!`等时，应该如何写？举个例子，`gogs`中的`[cache]`配置：
```
HOST = network=tcp,addr=:6379,password=redisserver#$%123aa,db=15,pool_size=100,idle_timeout=180
```
配置中`password`的`value`含有特殊字符，应该如何写？
`go-ini/ini`文档中写到，可以使用`"""code"""`或`来处理，我试了一下，似乎不对？

```
HOST = network=tcp,addr=:6379,password=`redisserver#$%123aa`
```
或者
```
HOST = network=tcp,addr=:6379,password="""redisserver#$%123aa"""
```
本来想在`go-ini/ini`项目中新开一个issue，看到项目作者是 @Unknwon ，就开在这里了

求解答，不胜感激！

**Comment by Unknwon** [comment]
Sorry, according to policy, I have to close this and please report to corresponding package issue tracker.

**Comment by Unknwon** [comment]
Quick answer is use back quotes surrounding value, not inside value. Read carefully.
