### ISSUE TITLE
Gravatar URLs are bad generated

### ISSUE THREAD

**Issue by ogarcia** [gogits/gogs#5157]
- Gogs version (or commit ref): latest
- Git version: n/a
- Operating system: n/a
- Database: n/a
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: any user profile, for example [this](https://try.gogs.io/xuan)
  - [ ] No
  - [ ] Not relevant

## Description
The gravatar URLs are wrong, for example for [this profile](https://try.gogs.io/xuan) Gogs generate `https://secure.gravatar.com/avatar/8afa4ade638e6debbc4725c4a7fc16cd?d=identicon?s=290` that have two `?` instead of `&`:

```diff
- https://secure.gravatar.com/avatar/8afa4ade638e6debbc4725c4a7fc16cd?d=identicon?s=290
+ https://secure.gravatar.com/avatar/8afa4ade638e6debbc4725c4a7fc16cd?d=identicon&s=290
```

The first URL opens a web page with message _Sorry, the parameters you provided were not valid_, and the second one works well.

**Comment by Unknwon** [comment]
Oh... good catch!

**Comment by Unknwon** [comment]
Hmm.. I found `?d=identicon` is not always there, this is a problem.

**Comment by ogarcia** [comment]
The order of the factor doesn't alter the product. You can ask for Gravatar using the form `https://secure.gravatar.com/avatar/8afa4ade638e6debbc4725c4a7fc16cd?s=290&d=identicon`, and in this case, the option `d=identicon` can be always with `&`.

**Comment by Unknwon** [comment]
The problem is both query parameters are conditional. I already have some clues to fix this.

**Comment by twocow** [comment]
And yet I was ignored. #5132. Btw my fix was disabling the gravatar service at the install page. Don't know how it worked

**Comment by Unknwon** [comment]
@twocow when you take a look at what you posted and what @ogarcia posted, you should know why.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by ogarcia** [comment]
It works! Thanks! :smile:
