### ISSUE TITLE
How to change "Author" when pushed via CLI

### ISSUE THREAD

**Issue by veganexe** [gogits/gogs#5161]
When I commit using Git on the CLI, the author of the commit, is shown as "Gogs" in the commit history. How do I change that to the user of the repo?

**Comment by Unknwon** [comment]
https://help.github.com/articles/setting-your-username-in-git/

**Comment by veganexe** [comment]
Oh. Didn't know that. But still, How do I change the default username "Gogs" to something else when a user commits without setting his username?

**Comment by Unknwon** [comment]
He has to set a username.

**Comment by Unknwon** [comment]
Locking this thread according to policy.
