### ISSUE TITLE
gogs功能疑问

### ISSUE THREAD

**Issue by lolipop99** [gogits/gogs#5166]
## 注册
注册功能能否做可配置，比如设置符合接收邮箱后缀或ip限制，才给注册并发送邮件激活

## markdown
目前markdown不支持toc功能，且渲染的时候，表格格式必须`|---|---|---|`才能生成table标签，而`|-|-|-|`不支持。
因为不是很懂go，能否请教下，如果可以自行定制的话，请问在哪里操作。不胜感激。

**Comment by slobber** [comment]
1. 注册的问题，修改：https://github.com/gogits/gogs/blob/9b4054f1fc3a92c7c582770a2c9997213434a792/routes/user/auth.go#L331，增加 && strings.HasSuffix(u.Email, "@your_domain_name")
1. markdown 的 table 基本上无解，gogs 无论是前端js，还是后端使用的 https://github.com/russross/blackfriday 都不支持你的写法。因为一般 `-` 的数量会根据单元格文字来确定，我想一般情况都不会少于3个字符。另外最前和最后的 `|` 可以省略。

**Comment by lolipop99** [comment]
@slobber 感谢大神回答。
但是markdown的table问题，github反而支持，vscode也支持。是不是做了一层兼容

**Comment by slobber** [comment]
你在 @Unknwon 的地盘乱喊大神，这不是折我寿嘛。
table 是一个 markdown 的扩展，各家没有统一的标准，你可以去 https://github.com/russross/blackfriday 提 issue，看看那边怎么个支持。

你也可以 继续 hack 下 blackfriday，
https://github.com/gogits/gogs/blob/6cbaa4787b444babda0ca6b6dd5d2d43d3a2cf99/vendor/github.com/russross/blackfriday/block.go#L812

把这个 case 删掉，应该就可以用了。

**Comment by lolipop99** [comment]
@slobber 教无前后 达者为先 大神大神
我看了一下，只有在编译安装前才可以 hack 这个 blackfriday
我现在gogs服务已经跑着了。

**Comment by slobber** [comment]
是的，需要你自己编译

**Comment by Unknwon** [comment]
Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
