### ISSUE TITLE
checkVersion() function failing

### ISSUE THREAD

**Issue by rokuu** [gogits/gogs#5174]
I'm trying to change the gogs app version to something other than the actual version. Like "1.0". I set the version in the template folder to "1.0" too. Built gogs using the makefile.

But when I run the binary, I get this : 

`2018/04/17 08:53:41 [FATAL] [...gits/gogs/cmd/web.go:72 checkVersion()] Binary version is higher than template file version, did you forget to update template files?`

These were my edits in the gogs.go and .version file

gogs.go
`const APP_VER = "1.0"`

.VERSION
`1.0`

**Comment by rokuu** [comment]
I built gogs using `make build TAGS="sqlite cert"` if that helps

**Comment by rokuu** [comment]
I'm going crazy over this. What am I doing wrong? Don't want to remove the checkversion function over this, lol

**Comment by Unknwon** [comment]
It is possible you thought you modified the "correct" template `.VERSION` but you're really not. I have one user changed to `1.0` as well and succeed.

**Comment by prologic** [comment]
I'm getting this on a recently restarted instnace on the Docker image :/ I didn't touch anything

**Comment by prologic** [comment]
Downgrading from `:latest` to `gogs/gogs:0.11.91` image from the [Docker Hub: gogs/gogs](https://hub.docker.com/r/gogs/gogs/tags) solved this for me. Looks like something is backwards incompatible with the latest tag.

**Comment by unknwon** [comment]
@prologic Thanks for the report. I just pushed a fix to `master` branch, sorry about that! Docker image is building.

![](https://media1.giphy.com/media/HyCxJErg9jTCU/giphy.gif?cid=5a38a5a211202273c2b4a974a5b164e24eb76ee5d68df5e1&rid=giphy.gif)

**Comment by prologic** [comment]
That's okay shit happens :) Glad to help!
