### ISSUE TITLE
generate site for apache2

### ISSUE THREAD

**Issue by ashtonhogan** [gogits/gogs#5184]
Is it possible to generate the site and host it using apache2?

It would be really simple if I could just add MySQL, SSL Certificate, etc configurations in one file like `app.ini` and then copy the entire "ready to go folder" into my `www` directory and immediately have a finished product without any additional steps.

There are a number of reasons why this approach is debatably the simplest. Personally, I've found redirects from ports and IP's particularly confusing so far and do not necessarily want to use a reverse proxy. Also, I would prefer to install and configure 3rd party applications like MySQL myself and just want gogs to **use** them, not **manage** them.

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/1314.
