### ISSUE TITLE
在 sql server2008r2 上面安装不成功

### ISSUE THREAD

**Issue by 284247028** [gogits/gogs#5186]
如题，公司服务器安装提示（环境:windows 2008 R2 数据库 sql server2008r2 )

数据库设置不正确：Login error: read tcp 127.0.0.1:51954->127.0.0.1:1433: wsarecv: An existing connection was forcibly closed by the remote host.

但是我自己的电脑是sql server2017 安装正常

**Comment by Unknwon** [comment]
Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
