### ISSUE TITLE
Deleting a branch

### ISSUE THREAD

**Issue by Guard13007** [gogits/gogs#5192]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.7.4
- Operating system: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/Guard13007/test/branches)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

A branch cannot be deleted through Gogs interface.

**Comment by Guard13007** [comment]
Issue submitted to replace #4700 as it was censored after I mistakenly did not follow the issue reporting template.

Solved by replacing Gogs with [Gitea](https://gitea.io/).

**Comment by rokuu** [comment]
@Guard13007 as unknwon pointed out in #4700 https://www.git-tower.com/learn/git/faq/delete-remote-branch is the way to go. 

Yes. A "delete branch" button can be added in the branches page. But "solving" an issue by just switching between projects is pretty dumb.

**Comment by Guard13007** [comment]
I missed that in my frustration that a useful conversation was deleted for no reason.

> But "solving" an issue by just switching between projects is pretty dumb.

Not when it has more features and is more actively updated. But thank you for pointing out my missing that part of the reply.
