### ISSUE TITLE
Contributing guidelines does not link to template expected for submitting issues

### ISSUE THREAD

**Issue by Guard13007** [gogits/gogs#5193]
- Gogs version (or commit ref): N/A
- Git version: N/A
- Operating system: N/A
- Database (use `[x]`): N/A
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io: N/A
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

The [contribution guide](https://github.com/gogits/gogs/blob/master/.github/CONTRIBUTING.md) does not specify the required issue template.

**Comment by Unknwon** [comment]
Thanks, updated.
