### ISSUE TITLE
Hooks was ignored because it’s not set as executable

### ISSUE THREAD

**Issue by alexandre1985** [gogits/gogs#5195]
- Gogs version (or commit ref): 0.11.43-1
- Git version: 2.17.0
- Operating system: Archlinux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
nothing relevant
## Description
My gogs version is 0.11.43-1
My system is ArchLinux.

I have just changed my `/etc/gogs/app.ini` the part of the repository root to be a path to my external disk.

Since then, everytime that I make a push it gives me the following output:
> hint: The 'hooks/pre-receive' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The 'hooks/update' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The 'hooks/post-receive' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.

1. When before it didn't gave me this output. What show I do to fix this?

**UPDATE:**
Also after creating a new repo and following the initial page commands of the repo creation; after the first push from local, my repo page doesn't change from this:
![deepinscreenshot_20180423180533](https://user-images.githubusercontent.com/5586308/39147233-038e55fc-4731-11e8-920c-ae5b5cda3382.png)

it is stuck

Gogs is writing to the new repo path though

**Comment by Unknwon** [comment]
Hi, it is definitely did, see my reply in the forum. 

https://github.com/gogits/gogs/blob/9387b79b981c268df4bbc97811b9d844d0799dec/models/repo.go#L785-L795

**Comment by alexandre1985** [comment]
I will continue this discussion on https://discuss.gogs.io/t/hooks-was-ignored-because-its-not-set-as-executable/1866
