### ISSUE TITLE
Error with 2FA

### ISSUE THREAD

**Issue by QuickGlare** [gogits/gogs#5197]
- Gogs version (or commit ref): 0.11.43.0330
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): https://hastebin.com/ixisudixux.sql

## Description
I can't confirm the 2FA because everytime i get this error(i use authy or google authenticator to generate the code) http://prntscr.com/j9namy

**Comment by Unknwon** [comment]
It is possible that your server `SECRET_KEY` has been modified, in that case... you would have to disable all current 2FA and reenable them.
