### ISSUE TITLE
CAS authentication support

### ISSUE THREAD

**Issue by cynddl** [gogits/gogs#520]
[CAS](http://en.wikipedia.org/wiki/Central_Authentication_Service) (Central Authentication Service) is a single sign-on protocol providing authentication with tickets. It is used by a lot of universities.

It would be nice to add support for CAS in gogs. I haven't found any complete client library in Go, just [golang-cas-client](https://github.com/lucasuyezu/golang-cas-client), which started just one week ago. Fortunately, the basic functionality of CAS can be resumed in two parts:

- if the user is not logged, redirect him to the CAS server, which redirect back to gogs with one ID;
- send a request for a ticket with the ID to ensure that the user is logged.

I might make a simple working pull request if you find it interesting enough!

**Comment by Unknwon** [comment]
Close as no further feedback.
