### ISSUE TITLE
connect mysql.password not support special characters ‘#’

### ISSUE THREAD

**Issue by asqsummer** [gogits/gogs#5203]
- Gogs version (or commit ref): gogs_v0.9.97
- Git version: 1.8.3.1
- Operating system: linux_amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

if mysql password include special characters '#',gogs startup fail.

error log.

../routers/install.go:72 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: Error 1045: Access denied for user 'root'@'....' (using password: YES)

**Comment by asqsummer** [comment]
Mysql Version:5.7.10
Other Client tools connect database where password include '#' is normal.

**Comment by Unknwon** [comment]
Try

```
PASSWORD = `pass!@#@%$&^*word`
```
