### ISSUE TITLE
Font Awesome Icon fa-star-o not loaded/shown

### ISSUE THREAD

**Issue by HanKooR** [gogits/gogs#5208]
- Gogs version (or commit ref): 0.11.48.0425

## Description
FontAwesome Icon fa-star-o not correctly shown.  
Can even be observed on Your own [try-out-server](https://try.gogs.io/jwmtp2/Test).

**Comment by sergey-dryabzhinsky** [comment]
@Unknwon Here PR: #5218

**Comment by sergey-dryabzhinsky** [comment]
@HanKooR  Please reopen

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5218, please help test on `develop` branch or https://try.gogs.io.

**Comment by HanKooR** [comment]
Sorry,
too fast ;)

**Comment by sergey-dryabzhinsky** [comment]
https://try.gogs.io/
![_2018-05-10_12-17-16](https://user-images.githubusercontent.com/717597/39862367-44e757a6-544c-11e8-94d5-4bc35c86ba96.png)
Looks like it working now.
