### ISSUE TITLE
Split the filename input field in the web editor if a slash character is inserted

### ISSUE THREAD

**Issue by Radiergummi** [gogits/gogs#5210]
- Gogs version (or commit ref): `0.11.29.0727 `
- Operating system: not relevant
- Git version: not relevant
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
 --

## Description

On Github, if you add a new file to the repository, you can create a new directory by inserting a slash in the file name. As soon as you type the slash, anything before it will be appended to the directory breadcrumb left to the input, leaving anything after the slash in the file name field:

![github file breadcrumbs](https://user-images.githubusercontent.com/6115429/39566928-86dc78b0-4ebd-11e8-9a84-baec4d7a3d3d.gif)

This will create the directories recursively and the file inside it, just as you'd expect. This is the same for Gogs - slashes in the file name will result creating it in the path given, however the user experience is not as smooth:

![gogs file breadcrumbs](https://user-images.githubusercontent.com/6115429/39567034-e56a0d66-4ebd-11e8-88dd-9c18ae9fb451.gif)

This is not mission critical, I'd just appreciate if this would be included in Gogs.

**Comment by Unknwon** [comment]
![image](https://user-images.githubusercontent.com/2946214/39775807-f64c96f4-52cc-11e8-8812-0d17c13f4a33.png)

I can do the same thing as GitHub on demo site.
