### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by jeffsui** [gogits/gogs#5212]
- Gogs version (or commit ref): [0.11.43](https://github.com/gogits/gogs/releases/tag/v0.11.43)
- Git version:  git version 2.17.0.windows.1
- Operating system: windows 10 professional 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

remote: Gogs: Internal error
remote: GetProtectBranchOfRepoByName [repo_id: 4, branch: master]: Error 1045: Access denied for user 'root'@'localhost' (using password: NO)

## Description
my colleague init a repo ,push the repo to remote repo got this error from server.
...

**Comment by Unknwon** [comment]
Check you DB password.

**Comment by jeffsui** [comment]
DB password is correct  . gogs  still not work.

**Comment by Unknwon** [comment]
>using password: NO

My bad, not even applied...
