### ISSUE TITLE
git push:!	refs/heads/master:refs/heads/master	[remote rejected] (unable to migrate objects to permanent storage

### ISSUE THREAD

**Issue by bryant24** [gogits/gogs#5213]
- Gogs version (or commit ref):  0.11.19.0609
- Git version: 2.17.0
- Operating system: centos7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):nothing log

## Description

when use git push,always show:
!refs/heads/master:refs/heads/master	[remote rejected] (unable to migrate objects to permanent storage
and push failed, Is anyone kown what happend?thx

**Comment by bryant24** [comment]
I try to update the permission of repository,chmod o+w project.git -R,then push success,but post-receive hook not run because no permission,very confused,I use git user  for running gogs,no question before.

**Comment by Unknwon** [comment]
Maybe helpful: https://discuss.gogs.io/t/hooks-was-ignored-because-its-not-set-as-executable/1866
