### ISSUE TITLE
two factor auth broken

### ISSUE THREAD

**Issue by prudnitskiy** [gogits/gogs#5222]
- Gogs version (or commit ref): 0.11.34-1525806056.7ecf5f71.stretch
- Git version: 2.11.0
- Operating system: Debian 9 Stable (9.4) amd64
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Hello!

As I can see, the 2FA was broken not a long time ago. When I trying to login to server, I see this error:

`[ERROR] [...g/context/context.go:171 ServerError()] ValidateTOTP: AESGCMDecrypt: cipher: message authentication failed`

So I can't login to server or make any changes in my account. GIT itself working properly. This problem is worked both on 0.11.34 and 0.11.33. The packages was from https://packager.io/, it's a last package avalible there

**Comment by Unknwon** [comment]
This is caused by [secret key](https://github.com/gogits/gogs/blob/master/conf/app.ini#L184) changed by the update, since this repository has no control over what packager.io does, we have no solutions. You would have to disable 2FA by deleting database table records.
