### ISSUE TITLE
Docker Deploy + Custom Homepage Theme?

### ISSUE THREAD

**Issue by foxeduser** [gogits/gogs#5240]
- Gogs version (or commit ref): Latest from Docker image
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 Server LTS
- Database
  - [x] SQLite

## Description

I recently setup Gogs on my Docker server. I want to customize the homepage.

This is my docker-compose.yml file:

> gogs:
>   restart: unless-stopped
>   image: gogs/gogs
>   volumes:
>     - /var/gogs:/data
>   ports:
>     - "10022:22"
>     - "3000:3000"

My data is in /var/gogs/gogs, I made this directory /var/gogs/gogs/data/custom/templates and tried inserting head.tmpl files as in documentation and restarting the docker process but it wouldn't update the homepage. Has anybody succeeded in a custom homepage with docker? Thanks.

**Comment by Unknwon** [comment]
Please refer to https://github.com/gogits/gogs/tree/master/docker#custom-directory.
