### ISSUE TITLE
HTTP Security Headers

### ISSUE THREAD

**Issue by sts** [gogits/gogs#552]
Enable various security extensions to prevent common attacks such as - list taken from [OWASP.org](https://www.owasp.org/index.php/List_of_useful_HTTP_headers)
- Strict-Transport-Security:max-age=31536000; includeSubdomains; preload - enforces secure connections to the server.
- X-Frame-Options:deny - provides clickjacking protection.
- X-XSS-Protection:1; mode=block - enables the Cross-site scripting (XSS) filter built into most recent web browsers.
- Content-Security-Policy

There might be configuration options needed. Also the session cookie should be set to [HttpOnly](https://www.owasp.org/index.php/HttpOnly).

Also including maxcdn resources into the codebase, would reduce the possibility that external parties are able to track users from using the application.

**Comment by Unknwon** [comment]
Anyone knows better can review this?

**Comment by Jonny007-MKD** [comment]
Where would you set these headers? In `modules/httplib/httplib.go`?
I would set those headers:

 -  `Strict-Transport-Security: max-age=31536000`

    active: only when CERT_FILE and KEY_FILE are set (so HTTPS is used), otherwise it's an option for the proxy
    Maybe we should an option for the max-age value; I (personally) never change it.

    https://scotthelme.co.uk/hsts-the-missing-link-in-tls/

 - `Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' *.gravatar.com; style-src 'self' 'unsafe-inline'; font-src 'self'; frame-src 'none'; object-src 'none'"

    Here I disabled `<frames>` and `<objects>`. Are there more external sources (like Fonts, CDNs) we have to add? Should the user be able to set own sources? Is JS `eval()` used?

    https://scotthelme.co.uk/content-security-policy-an-introduction/

 - `Public-Key-Pins 'pin-sha256="xxx"'`

    Could be used when HTTPS is used, but it may render a domain useless and should not be activated by default. We could let the user decide to enable this after a throrough warning

    https://scotthelme.co.uk/hpkp-http-public-key-pinning/

 - `X-Frame-Options "SAMEORIGIN" always;`

    The user should be able to disable it in case he wants to use gogs in a `<frame>`.

    https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options

 - `X-Content-Type-Options "nosniff" always;`

    As long as gogs is sending correct mime-types this should be no problem and always active.

    https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options

 - `X-Xss-Protection "1; mode=block" always;`

    As long as gogs isn't doing something weird JS stuff, this should always be active.

    https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection

**Comment by Unknwon** [comment]
> Where would you set these headers?

This is the part I don't know.... where should these headers be used..?

**Comment by Jonny007-MKD** [comment]
I am absolutely not into macaron, here is what they do:

`
func (ctx *Context) setRawContentHeader() {
	ctx.Resp.Header().Set("Content-Description", "Raw content")
	ctx.Resp.Header().Set("Content-Type", "text/plain")
	ctx.Resp.Header().Set("Expires", "0")
	ctx.Resp.Header().Set("Cache-Control", "must-revalidate")
	ctx.Resp.Header().Set("Pragma", "public")
}
`

So maybe we could register a Middleware and set the headers there for all routes. It could be the first handler as the headers are valid for all, results (404, 403,... too) 

`
m.Use(func(ctx *macaron.Context) {
    ctx.Resp.Header().Set(...)
})
`

So where should we place this function? Inline? `modules/middleware/headers.go` sounds good :)

**Comment by Unknwon** [comment]
@Jonny007-MKD thanks for the comments.

But I still don't get what does the code you provide to do with security?

**Comment by Jonny007-MKD** [comment]
That's example code from macaron how to set http headers. 

We take the headers from my first comment, discuss and test their values and set them in a Middleware for every response.

How each of these headers improves security can be read at the linked sites (see above)

**Comment by Unknwon** [comment]
I see.

But how these **security headers** make any differences?

**Comment by Jonny007-MKD** [comment]
The links I posted below each header describe their effect quite well.

**Comment by Unknwon** [comment]
....sorry, I never used any of them, so I have no idea what is the matter if I don't use those headers?

**Comment by Jonny007-MKD** [comment]
The purpose of these headers is to enhance the security of http(s) connections.

 - HSTS (Strict transport security): forces the browser to always use HTTPS in future for this domain. This prevents attackers to e.g. show a false login form during the second visit when the user simply enters the domain in the address bar without https://.
 - CSP (content security policy) defines approved sources of content that the browser may load. It can be an effective countermeasure to Cross Site Scripting (XSS) attacks. With this header forbidding Javascript an attacker cannot insert a `<script>` to execute his code.
 - X-Frame-Options protects the visitor against clickjacking attacks where the attacker can show a harmless site and when the user clicks somewhere he indeed clicks on a link/button of Gogs which is invisibly loaded in an iframe in the background.
 -  X-Content-Type-Options turns off a "feature" of browsers that often opens attack vectors for executing code.
 - X-Xss-Protection enables a good feature in Safari and Chrome protecting against XSS

**Comment by Unknwon** [comment]
@Jonny007-MKD thanks, though not sounds like a easy thing to implemented for me...

**Comment by Jonny007-MKD** [comment]
I did a small test and is really easy! As I [suggested 10 days ago](https://github.com/gogits/gogs/issues/552#issuecomment-187941965)) we can add a middleware that sets these headers. We create a new middleware (e.g. `modules/middleware/secureheaders.go`) with a method like

    func SecureHeaders(ctx *Context) {
        ctx.Resp.Header().Set("Test", "Hallo")
        // here we read the configuration, check for SSL and set the headers as discussed
    }

In `cmd/web.go` we add this method as middleware in `newMacaron`:

    m.Use(middleware.Contexter())
    m.Use(middleware.SecureHeaders)     // new!
    return m

That's it! Now my HTTP response has those headers:

    Content-Type		 text/html; charset=UTF-8
    Date				 Fri, 04 Mar 2016 10:39:55 GMT
    Set-Cookie			_csrf=ieOdfjeT_gNxrfoOX01Kn0gM4WU6MTQ1NzA4Nzk5NDk2MzQzNTcyN%3D%3D; Path=/
    Test				Hallo
    Transfer-Encoding	chunked

What I cannot provide is the code for reading the configuration and detecting HTTPS (over proxy?). If you/someone creates a new branch I will sure contribute :)

**Comment by Unknwon** [comment]
@Jonny007-MKD I know where to set, but when and what to set, need a deep understanding and provide appropriate config options.

**Comment by Jonny007-MKD** [comment]
Ok. I created a new branch at my place and gave you permissions. I will commit some code for each header and add comments what values I need from the config and what their default should be :) I'll tell you when I'm ready!

**Comment by Unknwon** [comment]
@Jonny007-MKD Thanks, I'll review after that.

**Comment by Jonny007-MKD** [comment]
@Unknwon: commits are ready [over here](https://github.com/Jonny007-MKD/gogs/tree/secureheaders).

We need two new settings:

  - frame options (as the user may want to `<iframe>` gogs somewhere)
  - HSTS max age (as the user may want to change this setting)

**Comment by Unknwon** [comment]
@Jonny007-MKD please send an PR so I can put in reivew queue.

**Comment by zacheryph** [comment]
Maybe this should be something that can just be put into the configuration file to enable?  Possibly even make the values definable (hello HSTS).  Granted most users should want these settings for https though you never know, someone might not want them for environmental specific reasons.

**Comment by barracks510** [comment]
> ---SNIP---
> someone might not want them for environmental specific reasons.
That would be pretty much anyone running Gogs behind a reverse proxy on a suburl, including myself. All of these settings are domain specific, and that defeats the purpose of running Gogs on a suburl. For example, the browser will complain if one page has HSTS headers, but all the others do not.

**Comment by bkcsoft** [comment]
@barracks510 I'm guessing anyone (everyone even) running Gogs behind a reverse proxy would have these Headers (if any) be set by said proxy as well :smiley:

**Comment by ccatlett2000** [comment]
If this is implemented, please allow disabling these headers being set. I set options for most of these headers via an apache2 reverse proxy, and would prefer to not have to try to strip them out of every response.

**Comment by Unknwon** [comment]
I agree this should be handled by reverse proxy software.

**Comment by kainecy** [comment]
I really need `X-Frame-Options` settings. 
There is no Nginx in front of my gogs.
It is WARNING by `北京市朝阳分局网络安全保卫大队`  which my gogs running on Cloud Server. 
Reported as `漏洞/事件：X-Frame-Options头未设置`. and if  not fixed ,the gogs service will be closed.

> 我司将配合分局网安部门实施“一键关停”措施，即关闭相关IP资源

**Comment by ccatlett2000** [comment]
@kainecy I'd recommend adding a reverse proxy in front of your gogs install. Without a reverse proxy to supply HTTPS `X-Frame-Options` is useless anyways. If NGINX is too heavy there are good lightweight options. If you absolutely cannot add a reverse proxy, you can look at the above pull request on how to change the gogs code to add headers (although I recommend heavily against this).

**Comment by kainecy** [comment]
I have add HAProxy in front of gogs, and it works.
`http-response set-header X-Frame-Options: DENY`
And now it is 100% safe for web scan(http://webscan.360.cn/)

But many HAProxy Cloud version does not support header config. 
It is good to support this by gogs.
