### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by andyleap** [gogits/gogs#613]
Something is making the application return 404's randomly when refreshing too fast.  The errors happen all over the place, even at the home url "/".  The issue seems to be that something can't handle concurrent access, as when I wrap the macaron http handler in a func like 

    var mutex sync.Mutex

    handler := func (w http.ResponseWriter, req *http.Request) {
            mutex.Lock()
            m.ServeHTTP(w, req)
            mutex.Unlock()
    }

and pass that like `http.ListenAndServe(listenAddr, http.HandlerFunc(handler))`, everything works fine.

Rather serious issue if the system can't handle multiple requests at once.....

**Comment by andyleap** [comment]
With roughly 99,950 or so lines of stack traces and an error of too many open files.

    This is limited by your ulimit -n.

Simple load test shouldn't kill the server due to open file limits, that's insane.  



    Is this maybe the reason why sometimes the avatar won't load?
    
    -> I have avatar caching activated
    -> on a site where a lot of avatars are being loaded (logged in -> dashboard)
    -> avatar cache is being refreshed
    
    Result:
    -> some avatars (or all) do not load.

Yeah, I was having this issue to, tracked it down to the server randomly throwing 404's on the avatar urls.  Disabling concurrency fixed it right away.

**Comment by Unknwon** [comment]
@andyleap thanks for the update!

**Comment by Unknwon** [comment]
The primary race problem should have been fixed by Macaron itself. So close this now.
