### ISSUE TITLE
how to install gogs as windows service?

### ISSUE THREAD

**Issue by jpuncle** [gogits/gogs#630]

**Comment by kardianos** [comment]
One option is to integrate gogs into github.com/kardianos/service .

**Comment by Unknwon** [comment]
See https://gogs.io/docs/installation/install_gogs_on_windows

**Comment by Unknwon** [comment]
@kardianos thank your info!

**Comment by kardianos** [comment]
@Unknwon 
If gogs add the following import to one of the files
```
import _ "github.com/kardianos/minwinsvc"
```
It won't affect non-windows at all, but on windows allow installing directly as a windows service.

**Comment by Unknwon** [comment]
@kardianos sure!

Can you explain or give some references about how does this package actually work?

**Comment by kardianos** [comment]
Windows requires services to maintain callbacks and respond to query messages and stop messages. The package `minwinsvc` works by:
 1) only doing anything at compile time on windows
 2) detecting if the program is running as a service, if not, it does nothing
 3) if running as a service it starts a go routine to setup, monitor, and service the windows required callbacks.
 4) when the stop message is called, it calls os.Exit(0)

Under the covers on windows it uses `golang.org/x/sys/windows/svc` which works on go1.3+. 

You would still need a wiki for installing, but you could install directly as a windows service. If you use a windows command like "sc" to install, you would need to make sure the binPath included the "web" and --config arguments as the working dir on windows is always set to "C:\windows\system32".

**Comment by Unknwon** [comment]
@kardianos sounds great!

Would you mind to PR a section to https://github.com/gogits/docs/blob/master/en-US/installation/install_gogs_on_windows.md for

> You would still need a wiki for installing, but you could install directly as a windows service. If you use a windows command like "sc" to install, you would need to make sure the binPath included the "web" and --config arguments as the working dir on windows is always set to "C:\windows\system32".

**Comment by kardianos** [comment]
Will do.

**Comment by Unknwon** [comment]
Thanks!

**Comment by kardianos** [comment]
There are minimal changes needed to natively support windows services. To log to the windows event log, or enable a command like `gogs.exe web -service install` you would probably want to make slighly more invasive changes by using something like `github.com/kardianos/service (though not by much). But not sure if that is worth it.

**Comment by mpindado** [comment]
Hi, thank you so much for this project.

as of 0.9.13, when installing as a builtin windows service with gogs-ssh builtin option, the directories _ssh_ and _sessions_ are created under c:\windows\system32\data, regardles of --config argument of gogs.
To have everything under c:\GOGS-INSTALL-DIR\data, we created a link like this:
`mklink /d c:\windows\system32\data c:\GOGS-INSTALL-DIR\data`

Thanks
