### ISSUE TITLE
Add Emoji support

### ISSUE THREAD

**Issue by hauleth** [gogits/gogs#633]
It will be nice to have Emoji support in Gogs. It could be done by [EmojiOne](http://git.emojione.com/demos/jstoimage.html) `toImage` function on client side.

**Comment by acusti** [comment]
I found a golang library ([chnlr/emoji](https://github.com/chnlr/emoji)) that supports emoji conversion. Specifically, the [`EmojiTagToTwemoji`](http://godoc.org/github.com/chnlr/emoji#EmojiTagToTwemoji) function takes a source string, a size, and a boolean to specify XHTML output or not (whether to close the `<img>` tag with `/>` or just `>`), and replaces all of the emoji tags, of form `:+1:`, with img elements pointing to the emoji as an SVG served by MaxCDN, like so: <img src="http://twemoji.maxcdn.com/svg/1f44d.svg" width="18" height="18"> (`<img src="//twemoji.maxcdn.com/svg/1f44d.svg" width="18" height="18">`).

Another function, `EmojiTagToHTMLEntities`, will convert the emoji code to the HTML entity for that emoji, like &#x1F44D; (`&#x1F44D;`), but that will only work for users who are using a browser/OS that supports emoji.

**Comment by lunny** [comment]
A nice alternative. @acusti

**Comment by Unknwon** [comment]
OK, everyone... it's now supported on `develop`, and see https://try.gogs.io/gogs/gogs/issues/20 in action.

**Comment by mexthemax** [comment]
Path to emojis seems to be hardcoded in gogs.js. When running in subpath (e.g. www.mydomain.com/gogs) emojis are not shown (because they don't exist in mydomain.com/img/emoji)

**Comment by Unknwon** [comment]
Hi @mexthemax , thanks your feedback!

I've pushed fix to `develop` branch.

**Comment by mexthemax** [comment]
@Unknwon it works like a charm, thanks for the fix :smile:

**Comment by Unknwon** [comment]
@mexthemax no problem!

**Comment by Unknwon** [comment]
Close as implemented. :tada:

**Comment by acusti** [comment]
:bow: :clap:

**Comment by zijam** [comment]
:+1: :smile:
