### ISSUE TITLE
Inline code markdown with leading hash

### ISSUE THREAD

**Issue by drwlrsn** [gogits/gogs#637]
Starting an inline code snippet like \`#00ff00\` results in an attempt to create a link to an issue. It should actually result in monospace formatted text like `#00ff00`.

I am running Gogs 0.5.8.1116 Beta.

**Comment by Unknwon** [comment]
It is working properly now: https://try.gogs.io/unknwon/1111/issues/4

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
