### ISSUE TITLE
Attachment uploading issue.

### ISSUE THREAD

**Issue by Hell0wor1d** [gogits/gogs#641]
Hi there, If select attachments too much, the page will show the error `Could not parse JSON`.  You can get more details in the below figure.  I think you guys can make the error tips much more friendly. Thanks. 
![20141120143448](https://cloud.githubusercontent.com/assets/2695788/5120741/91e34f22-70c2-11e4-9d7a-e2eec400083e.jpg)

**Comment by deringer** [comment]
I don't think it's necessarily attachment related.

I'll get the Could not parse JSON error message from time to time when entering only text. I thought maybe it was a token mismatch error, but it seems to happen at random. I'll try and catch the error next time I see it and provide more info.

**Comment by Unknwon** [comment]
This is somewhat no longer exists as the issue has new implementation.
