### ISSUE TITLE
"git remote show ..." doesn't work

### ISSUE THREAD

**Issue by ghost** [gogits/gogs#645]
The command to get information on a remote does not seem to work.

When I perform any other command (so far) with Gogs, it works fine as long as my SSH-key is installed correctly.

When I perform this command, it retorts with a message similar to that which is shown when the SSH-key is not installed.

See:
```
Gogs: given repository does not exist
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Unknwon** [comment]
Ok, well. Close for now.
