### ISSUE TITLE
Graphic design templates inconsistency

### ISSUE THREAD

**Issue by a-x-** [gogits/gogs#650]
// Excuse my beginner's English
Hi!

- **Bug Description**: Graphic design templates inconsistency. Compare: dashboard and issue edit page, for example.
![image](https://cloud.githubusercontent.com/assets/6201068/5148005/fd5c3138-71cb-11e4-87a0-5b0111d29b06.png)

- **Gogs Version**: 0.5.8.1118 Beta
- **Git Version**: 1.3.3
- **System Type**: debian 7 x32
- **Error Log**: n/a
- **Other information**: n/a

**Comment by JokerQyou** [comment]
This is with the user account page too, just to let you know.
![image](https://cloud.githubusercontent.com/assets/1465267/9829708/1783f032-5943-11e5-910d-06dba2e036d4.png)
![image](https://cloud.githubusercontent.com/assets/1465267/9829710/23dc7386-5943-11e5-8537-4638451a2b3e.png)

**Comment by Unknwon** [comment]
@JokerQyou I definitely which page are using which theme :joy: and your example has finished transforming to new theme in `master` branch.

**Comment by JokerQyou** [comment]
So which is the new theme for future releases? The one with blue header or the one with white header?

**Comment by Unknwon** [comment]
@JokerQyou the white header one.

**Comment by stonerl** [comment]
- [ ] Admin-Panel -> Configuration
- [ ] Organization -> Main Page
- [ ] Organization -> Member Page
- [ ] Organization -> Member Page -> Invitations
- [ ] Organization -> Teams Page
- [ ] Organization -> Teams Page -> Create Team
- [ ] Organization -> Teams Page -> Team Overview
- [ ] Organization -> Teams Page -> Teams Settings

**Comment by tkisme** [comment]
@JokerQyou https://try.gogs.io/ is the master branch

**Comment by stonerl** [comment]
@tkisme according to the README, https://try.gogs.io/ is running the ```develop```branch

**Comment by Unknwon** [comment]
All pages are now uses new theme. 

Finally unified.

**Comment by Unknwon** [comment]
Help test possible UI bugs on https://try.gogs.io

**Comment by melote** [comment]
I found something that may help
1. The dashboard display the issue content completely，so that if we have many contents, all page view will full of it.
2. The dashboard issue seems not to support markdown, so it's full of mess when we have many contents contents .
3. The organization main page view seems not the new UI on v0.7.19.

**Comment by Unknwon** [comment]
@melote  Thanks your feedback!

> The dashboard displays the issue content completely，so that if we have many contents, all page view will full of it.

This should go with a new issue.

> The dashboard issue seems not to support markdown, so it's full of mess when we have many contents .

Same as above.

> 3. The organization main page view seems not support the new UI on v0.7.19.

Please compare the commits time.

**Comment by melote** [comment]
@Unknwon OK, new issue is [here](https://github.com/gogits/gogs/issues/2029)

**Comment by rogerrogeranchor** [comment]
Is there any option to change themes?

**Comment by Unknwon** [comment]
@rogerrogeranchor there is only one theme, may allow custom theme in the future.

**Comment by rogerrogeranchor** [comment]
Thanks @Unknwon. It will be a great feature.

**Comment by Unknwon** [comment]
@rogerrogeranchor you can follow on https://github.com/gogits/gogs/issues/1126
