### ISSUE TITLE
Cannot parse releases' non-digital date

### ISSUE THREAD

**Issue by lifeofguenter** [gogits/gogs#663]
https://gitar.io/gg/valid-hostname/releases (500 err)

Logs:

```
2014/11/24 12:47:53 [release.go:104 Releases()] [E] GetCommitOfTag2: strconv.ParseInt: parsing "Mon": invalid syntax
2014/11/24 12:43:40 [command.go:101 Run()] [F] runUpdate.GetTag: strconv.ParseInt: parsing "Mon": invalid syntax
```

**Comment by Rickou412** [comment]
this appear after a migration. gogs see my tags, and so my releases, but don't let me access to them.

the problem seems to be linked to a date parsing: the error is always ParseInt on value like Fri, Mon,...

**Comment by Unknwon** [comment]
@Rickou412 thanks your tip!

I'm on it.

**Comment by Unknwon** [comment]
![po6_ q6c lf 6l0t db1](https://cloud.githubusercontent.com/assets/2946214/6093649/030f0c8a-aed6-11e4-9e9b-7fa5e67592b1.png)

**Comment by Unknwon** [comment]
Hi all, I've pushed a fix on `dev` branch please help test again! Thanks for the patient! :beer:

**Comment by Rickou412** [comment]
Hi,

the migration of my repositories is now working for releases. Fix is good for me.

**Comment by Rickou412** [comment]
No more working on master :( New log message:

2015/03/06 11:15:11 ^[[1;31m[release.go:84 Releases()] [E] GetCommitOfTag2: parsing time "Fri Dec 6 15:40:55 2013 +0100" as "Mon, 02 Jan 2006 15:04:05 -0700": cannot parse " Dec 6 15:40:55 2013 +0100" as ", "^[[0m

**Comment by Unknwon** [comment]
Hi @Rickou412 , thanks your report!

I've pushed new code to `master` branch, please help test again!

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
