### ISSUE TITLE
Gobuid.io fails to build master branch binaries

### ISSUE THREAD

**Issue by 9uuso** [gogits/gogs#667]
- **Bug Description**: In [gogs's gobuild.io page](http://gobuild.io/github.com/gogits/gogs?tag=branch:master), no binaries are listed
- **Gogs Version**: the latest master, 0.5.8 seemingly
- **Git Version**:
- **System Type**: linux/amd64
- **Error Log**: [see build log in gobuild.io](http://gobuild.io/task/17058)
- **Other information**: I have this same problem with my own application, but so far gobuild has been unable to fix the bug, which seemingly is in their platform. As with you, all my CI builds are green. I was thinking that maybe raising awareness trough your project might speed up fixing the bug, because you are the most downloaded project in their service. I've filed an issue on their repo in [here](https://github.com/gobuild/gobuild3/issues/9). As you can see from my logs as well, there shouldn't be anything which would cause a build failure.

**Comment by Unknwon** [comment]
Close this since gobuild.io is down.
