### ISSUE TITLE
 Could you set up links to closed tasks in commit ?

### ISSUE THREAD

**Issue by adwmicro** [gogits/gogs#668]
Could you set up links to closed tasks in commit ?

**Comment by Unknwon** [comment]
Hi @adwmicro , this should work right now on `dev` branch, you can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:
