### ISSUE TITLE
PHP syntax highlighting

### ISSUE THREAD

**Issue by zilionis** [gogits/gogs#670]
Need to add PHP syntax highlighting

**Comment by nd2s** [comment]
+1
No proper Haskell and SQL highlighting yet.

**Comment by RyenNelsen** [comment]
+1 for so many languages that I use.

**Comment by lazywei** [comment]
+1 for even python

**Comment by explorigin** [comment]
Here's something to think about.  You can integrate Highlight.js (like Github seems to) and then when you want to add web-based editing, you can integrate Ace (again like Github).

Or you can integrate [Codemirror](http://codemirror.net/) and use the readOnly mode for highlighting and get the editing component almost for free when that feature comes a long.  Codemirror has almost as many languages as Highlight.js

**Comment by Unknwon** [comment]
Please check out new UI here: https://try.gogs.io/gogs/gogs

**Comment by xPaw** [comment]
It's not very responsive.

![2015-11-14_13-19-18](https://cloud.githubusercontent.com/assets/613331/11163306/589ac17a-8ad2-11e5-9307-b5c09b71d658.png)

**Comment by Unknwon** [comment]
@xPaw I think statements are made very clear here: https://github.com/gogits/gogs#browser-support

**Comment by Unknwon** [comment]
And please make relevant comments here.

**Comment by xPaw** [comment]
Oh I see. The point about navigation still remains though.

**Comment by Unknwon** [comment]
> Oh I see. The point about navigation still remains though.

You are right, I'm thinking the same thing.

**Comment by nd2s** [comment]
Syntax looks good from what I saw. But could someone please mirror https://github.com/xmonad/xmonad so I can check Haskell highlighting? I tried signing up but activation link doesn't work...

**Comment by Unknwon** [comment]
@nd2s here you go:https://try.gogs.io/unknwon/xmonad/src/master/src/XMonad.hs

**Comment by nd2s** [comment]
Thank you, looks good as well!

**Comment by Unknwon** [comment]
Close as fixed.
