### ISSUE TITLE
Pull email address from LDAP entry when auto-registering users

### ISSUE THREAD

**Issue by jcracknell** [gogits/gogs#672]
It would be nice if you could configure an LDAP field containing an email address to be used when auto-registering accounts.

**Comment by Lafriks** [comment]
#915

**Comment by Prajithp** [comment]
@Unknwon Could you please merge the request #915 to dev or access branch?

**Comment by Unknwon** [comment]
@Prajithp #915 has been merged. cc @Lafriks

**Comment by Unknwon** [comment]
Hi there, by mering PR #1476 into develop, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by lbeltrame** [comment]
> Hi there, by mering PR #1476 into develop, this problem is claimed to be
> fixed, would you mind to test again and give us feedback? Thanks! :beer:

Unfortunately I cannot test it anymore, as I no longer run Gogs for my git 
repositories.

**Comment by Unknwon** [comment]
Close as implemented. :tada:

**Comment by fungos** [comment]
Remove FIXME? :)

https://github.com/gogits/gogs/blob/c60d8bc069491295300969b185a47587dfdd03a6/models/login.go#L231

**Comment by Unknwon** [comment]
@fungos good catch!
