### ISSUE TITLE
Error on adding new member to owners team

### ISSUE THREAD

**Issue by krazyjakee** [gogits/gogs#681]
{
"err": "fail to insert access: UNIQUE constraint failed: access.user_name, access.repo_name, access.mode",
"ok": false
}

Getting this when I try to add a member to the owners list of an organisation

I have found this is when the user is an ordinary member and already exists. So you need to remove the member and then add them again as an owner to fix this bug.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
