### ISSUE TITLE
Poor scalability for huge "flat" repositories

### ISSUE THREAD

**Issue by borman** [gogits/gogs#684]
- **Gogs Version**: master (0.5.8.1125 Beta)
- **Bug Description**: 
  1. Create a new repository
  2. Push from a gargantuan repository with ~10k top-level directories and ~100k commits
  3. Navigate to your newly-populated repository
  4. See gogs turn your cpu into a frying pan

Turns out, gogs issues a bunch of subprocess calls like `git log -1 --pretty=format:%H 713f036503b783df70c81e7174387af214ddcbd1 -- subdir-703` for each (top-level) directory item, which means at least 10k subprocess invocations per request. Good thing, it does not bring your system down with a fork bomb, nor it DoSes the whole gogs instance.

- **How to reproduce**:
The following script may be used to create a model repository:
```bash
#!/bin/bash

ndirs=1000
nrounds=13

git init .

for i in $(seq 1 $ndirs); do
    mkdir subdir-$i
done

for round in $(seq 1 $nrounds); do
    for i in $(seq 1 $ndirs); do
        head -c 50 /dev/urandom | base64 > subdir-$i/data
        git add subdir-$i/data
        git commit -m"modify $i at round $round"
    done
done
```

On my laptop, it was enough to experience unacceptable request processing time:
```
[Macaron] Started GET /borman/bigrepo for 127.0.0.1
[Macaron] Completed /borman/bigrepo 200 OK in 45.588725781s
[Macaron] Started GET /borman/bigrepo for 127.0.0.1
[Macaron] Completed /borman/bigrepo 200 OK in 46.089607608s
[Macaron] Started GET /css/github.min.css for 127.0.0.1
```

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/1505
