### ISSUE TITLE
packager.io is not built with 'cert' support

### ISSUE THREAD

**Issue by willglynn** [gogits/gogs#685]
I installed `gogs` via the packager.io binaries. This created a `/etc/gogs/conf/app.ini`, reading in part:

    ; Generate steps:
    ; $ cd path/to/gogs/custom/https
    ; $ ./gogs cert -ca=true -duration=8760h0m0s -host=myhost.example.com
    CERT_FILE = custom/https/cert.pem
    KEY_FILE = custom/https/key.pem

However, actually running this yields:

    $ /opt/gogs/gogs cert -ca=true -duration=8760h0m0s -host=myhost.example.com
    Command cert not available, please use build tags 'cert' to rebuild.

I think the packager.io builds should include 'cert' support. If that's impractical (#524?), I think the default configuration file should reflect the shipped binary's capabilities.

**Comment by Unknwon** [comment]
Hi @crohr , what is the status of this issue?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
