### ISSUE TITLE
WorkDir() uses the path of the gogs executable instead of the current working directory

### ISSUE THREAD

**Issue by minusinf** [gogits/gogs#689]
- **Bug Description**: WorkDir() uses the path of the gogs executable instead of the current working directory. 

    This poses problems when installing gogs in a custom location such as /usr/local/go/ and then wanting to run it from /home/git/gogs as working directory. The idea being that only root should be able to update gogs and its dependencies and gogs can be run in a 'jailed' environment. 

    Offending line: 

          // WorkDir returns absolute path of work directory.
          func WorkDir() (string, error) {
              execPath, err := ExecPath()
              return path.Dir(strings.Replace(execPath, "\\", "/", -1)), err
          }

    I think it would also make sense to be able to specify a config file location that avoid this problem altogether. 

- **Gogs Version**: 82da024a4df2a626633a49f70dd3a2889b525d15 (I think: `git log | head`)
- **Git Version**: git version 1.9.1
- **System Type**: Debian Wheezy
- **Error Log**: 

           $ gogs web
           2014/11/30 22:22:13 [setting.go:162 NewConfigContext()] [E] Fail to parse 'conf/app.ini': open /usr/local/go/bin/conf/app.ini: no such file or directory

    It works with a bit of creative linking (see below):

           ~/gogs$ /home/git/gogs/gogs web
           2014/11/30 22:04:23 [W] No custom 'conf/app.ini' found, please go to '/install'
           2014/11/30 22:04:23 [T] Custom path: /home/git/gogs/custom
           2014/11/30 22:04:23 [T] Log path: /home/git/gogs/log
           2014/11/30 22:04:23 [I] Gogs: Go Git Service 0.5.8.1130 Beta
           2014/11/30 22:04:23 [I] Log Mode: Console(Trace)
           2014/11/30 22:04:23 [I] Cache Service Enabled
           2014/11/30 22:04:23 [I] Session Service Enabled
           2014/11/30 22:04:23 [I] Run Mode: Development
           2014/11/30 22:04:23 [I] Listen: http://0.0.0.0:3000

    Disclaimer: I haven't pointed a browser to this location yet. I wanted to publish this bug report first.

- **Other information**:
    Here's my current configuration and setup:
  
          PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin
          GOPATH=/usr/local/go

    The gogs source is located in:
 
          /usr/local/go/src/github.com/gogits/gogs/

    Setup:
 
        mkdir -p /home/git/gogs/conf
        ln -s /usr/local/go/src/github.com/gogits/gogs/conf/content /home/git/gogs/conf/content
        ln -s /usr/local/go/src/github.com/gogits/gogs/conf/gitignore /home/git/gogs/conf/gitignore
        ln -s /usr/local/go/src/github.com/gogits/gogs/conf/license /home/git/gogs/conf/license
        cp /usr/local/go/src/github.com/gogits/gogs/conf/app.ini /home/git/gogs/conf/app.ini # that's the only file that I want to copy.
        ln -s /usr/local/go/src/github.com/gogits/gogs/templates /home/git/gogs/templates
 
    "Fix" for those who are (currently) not fluent in go. 

          mkdir -p /home/git/gogs/bin
          ln -s /usr/local/go/bin/gogs /home/git/gogs/bin/gogs
          /home/git/gogs/gogs web

**Comment by weberc2** [comment]
Unless I'm missing something, setting GOGS_CUSTOM doesn't change the situation:

```
$ gogs --version
Gogs version 0.5.11.0103 Beta

$ ls conf/
app.ini  content  gitignore  license  locale

$ GOGS_CUSTOM=$PWD gogs web
2015/01/25 18:52:14 [setting.go:167 NewConfigContext()] [E] Fail to parse 'conf/app.ini': open {$GOPATH}/bin/conf/app.ini: no such file or directory
```

**Comment by Unknwon** [comment]
Since Gogs has updated a lot, any updates on this?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.

**Comment by bekker** [comment]
gogs package on Archlinux AUR installs its binary into `/usr/bin`.

When I tried to restore backup files, the following error arises due to this issue:

```
Fail to import 'custom': rename /tmp/gogs-backup/custom /usr/bin/custom: permission denied
```

I think the restore functionality should be independent of gogs binary path.

Any way, quick fix is to copy /usr/bin/gogs to your desired working directory.
