### ISSUE TITLE
Install page should be able to config log path

### ISSUE THREAD

**Issue by pspoerri** [gogits/gogs#691]
- **Bug Description**: Gogs crashes after the installation when the log path is not writeable. Make the log path available on the install page.
- **Gogs Version**: Go Git Service 0.5.8.1130 Beta
- **Git Version**: 1.9.1
- **System Type**: Debian Wheezy
- **Error Log**:

        $ /usr/local/go/src/github.com/gogits/gogs/gogs web
        2014/12/01 08:40:59 [W] No custom 'conf/app.ini' found, please go to '/install'
        2014/12/01 08:40:59 [T] Custom path: /home/git/gogs
        2014/12/01 08:40:59 [T] Log path: /usr/local/go/src/github.com/gogits/gogs/log
        2014/12/01 08:40:59 [I] Gogs: Go Git Service 0.5.8.1130 Beta
        2014/12/01 08:40:59 [I] Log Mode: Console(Trace)
        2014/12/01 08:40:59 [I] Cache Service Enabled
        2014/12/01 08:40:59 [I] Session Service Enabled
        2014/12/01 08:40:59 [I] Run Mode: Development
        2014/12/01 08:40:59 [I] Listen: http://0.0.0.0:3000
        [Macaron] Started GET / for 127.0.0.1
        [Macaron] Completed / 302 Found in 4.565938ms
        [Macaron] Started GET /install for 127.0.0.1
        [Macaron] Completed /install 200 OK in 103.229657ms
        [Macaron] Started GET /ng/js/lib/jquery-1.11.1.min.js for 127.0.0.1
        [Macaron] Started GET /css/font-awesome.min.css for 127.0.0.1
        [Macaron] Started GET /ng/css/magnific-popup.css for 127.0.0.1
        [Macaron] Completed /ng/css/magnific-popup.css 304 Not Modified in 160.732us
        [Macaron] Started GET /ng/css/tipsy.css for 127.0.0.1
        [Macaron] Completed /ng/css/tipsy.css 304 Not Modified in 120.566us
        [Macaron] Started GET /ng/css/gogs.css for 127.0.0.1
        [Macaron] Completed /ng/css/gogs.css 304 Not Modified in 129.135us
        [Macaron] Started GET /ng/css/ui.css for 127.0.0.1
        [Macaron] Completed /ng/css/ui.css 304 Not Modified in 141.805us
        [Macaron] Completed /css/font-awesome.min.css 200 OK in 2.131768ms
        [Macaron] Completed /ng/js/lib/jquery-1.11.1.min.js 200 OK in 7.815828ms
        [Macaron] Started GET /ng/fonts/octicons.css for 127.0.0.1
        [Macaron] Completed /ng/fonts/octicons.css 304 Not Modified in 103.228us
        [Macaron] Started GET /css/github.min.css for 127.0.0.1
        [Macaron] Completed /css/github.min.css 304 Not Modified in 177.201us
        [Macaron] Started GET /ng/js/lib/lib.js for 127.0.0.1
        [Macaron] Completed /ng/js/lib/lib.js 304 Not Modified in 185.337us
        [Macaron] Started GET /ng/js/lib/jquery.magnific-popup.min.js for 127.0.0.1
        [Macaron] Completed /ng/js/lib/jquery.magnific-popup.min.js 304 Not Modified in 168.215us
        [Macaron] Started GET /ng/js/lib/jquery.tipsy.js for 127.0.0.1
        [Macaron] Completed /ng/js/lib/jquery.tipsy.js 304 Not Modified in 100.367us
        [Macaron] Started GET /ng/js/utils/tabs.js for 127.0.0.1
        [Macaron] Completed /ng/js/utils/tabs.js 304 Not Modified in 666.033us
        [Macaron] Started GET /ng/js/gogs.js for 127.0.0.1
        [Macaron] Completed /ng/js/gogs.js 304 Not Modified in 602.961us
        [Macaron] Started GET /ng/js/utils/preview.js for 127.0.0.1
        [Macaron] Completed /ng/js/utils/preview.js 304 Not Modified in 986.334us
        [Macaron] Started GET /fonts/fontawesome-webfont.woff for 127.0.0.1
        [Macaron] Completed /fonts/fontawesome-webfont.woff 200 OK in 4.907086ms
        [Macaron] Started POST /install for 127.0.0.1
        [Macaron] Completed /install 200 OK in 167.44596ms
        [Macaron] Started GET /ng/fonts/octicons.woff for 127.0.0.1
        [Macaron] Completed /ng/fonts/octicons.woff 304 Not Modified in 610.311us
        [Macaron] Started POST /install for 127.0.0.1
        2014/12/01 08:52:21 [T] Custom path: /home/git/gogs
        2014/12/01 08:52:21 [T] Log path: /usr/local/go/src/github.com/gogits/gogs/log
        2014/12/01 08:52:21 [I] Gogs: Go Git Service 0.5.8.1130 Beta
        2014/12/01 08:52:21 [log.go:294 Error()] [E] Fail to set logger(file): open /usr/local/go/src/github.com/gogits/gogs/log/gogs.log: no such file or directory

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging 2609

**Comment by joshfng** [comment]
Preview of new setting:

<img width="633" alt="screen shot 2016-02-13 at 12 18 11 am" src="https://cloud.githubusercontent.com/assets/302764/13026038/4f64e372-d1e7-11e5-8e05-d6971b7e2dbe.png">

**Comment by Unknwon** [comment]
Close as implemented.
