### ISSUE TITLE
Add binary in release

### ISSUE THREAD

**Issue by shingosama** [gogits/gogs#698]
Hello, I discovered Gogs and I wonder if it is possible to deploy a release in an archive containing only a binary and libraries? When I want to propose a repo on my release, Gogs only shows a link to download the source. I think this is normal, but there is no option to upload my compiled program?

thank you

**Comment by m42e** [comment]
Maybe a way to upload files that are associated with a repository and that can be linked to in the readme or the description is a simple and straight forward solution, isn't it?

**Comment by melote** [comment]
Good feature, it's import to store the distribution release version that includes the everything such as deps package, runtime env that git ignored.

**Comment by Unknwon** [comment]
Sorry I'm starting getting confused about this thread.... is is a feature request for adding attachments for repository release feature, or something else?

**Comment by melote** [comment]
yes, just attachments that could be anything else, such as released binary files, or whole repo excluded .git folder. Sometimes we want to store the files and folders that git ignored, so that we can recover it for these attachments when bad things happened.

**Comment by Unknwon** [comment]
@melote thanks your explanation!

**Comment by MitchTalmadge** [comment]
I'd love to see the ability to attach files to releases! :+1:

**Comment by SkyzohKey** [comment]
Bump. First thanks for the awesome app you built. 
I think that being able to attach a binaries to a release (+ maybe a hook that we could trigger from a CI service (travis, gitlab ci, jenkins, etc) to auto-attach the binary when a new release is available).

I :+1: this feature request. :)

**Comment by fnkr** [comment]
:+1:

**Comment by mc-crafty** [comment]
For anyone else, I know it's not a great, but a quick workaround I've been using is creating a new branch in your repo called 'bin' or something similar and creating the release for your repo from that

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/1614
