### ISSUE TITLE
Get error on raspberrypi

### ISSUE THREAD

**Issue by leecade** [gogits/gogs#705]
Tried to `go build` & `go get`, got:

```
# gopm
/usr/local/go/pkg/tool/linux_arm/5l: readsym out of sync
```

go version:

```
go version go1.3.3 linux/arm
```

**Comment by Unknwon** [comment]
Any updates on this? @leecade

**Comment by vielmetti** [comment]
The @hypriot folks built a Dockerfile that loads gogs

https://registry.hub.docker.com/u/hypriot/rpi-gogs-raspbian/

and they did a nice writeup here of loading gogs

http://blog.hypriot.com/post/run-your-own-github-like-service-with-docker/
