### ISSUE TITLE
500 error: GetTreeEntryByPath

### ISSUE THREAD

**Issue by rojaro** [gogits/gogs#714]
I just created a fresh git repo for a new project. The project consists of javascript stuff only, has no submodules and was pushed to a fresh empty repository via ssh. When i am accessing the repository through the webbrowser i get a 500 error and the following error message in the logs:
```
[Macaron] Started GET /foo/bar for 10.50.1.130
2014/12/05 17:24:09 [view.go:142 Home()] [E] GetSubModule: GetTreeEntryByPath: error not exist
[Macaron] Completed /foo/bar 500 Internal Server Error in 22.237619ms
```

**Comment by rfdrake** [comment]
@Unknwon

I'm having the same issue on a repo that's reasonably safe to publish (it's a vimrc repo)

Here is the error on my system:
```
[Macaron] Started GET /rdrake/vimrc for 10.6.2.149
2015/01/08 20:04:27 [view.go:142 Home()] [E] GetSubModule: GetTreeEntryByPath: error not exist
[Macaron] Completed /rdrake/vimrc 500 Internal Server Error in 144.236261ms
```


I've uploaded it if you have a chance to take a look:
https://try.gogs.io/rfdrake/vimrc

**Comment by Unknwon** [comment]
Hi @rojaro , any updates on this since Gogs has some changes about submodule?

**Comment by gbonvehi** [comment]
I could reproduce it when cloning a repository from Bitbucket (not mirror).
I could access the repository settings directlry using <repo url>/settings (<repo url>/ threw error 500 with the error reported here) and delete it and push it from my machine and it worked correctly.
Unfortunately it's not a public repository so I cannot help to reproduce it.

**Comment by Caerostris** [comment]
Hi @Unknwon ,
I ran into the same error today.
It turned out I had another git repository in a subfolder of the newly created repository.
As soon as you push a subfolder that contains a git repository, gogs will throw a 500 when trying to display the repo.
Gogs Version 0.6.1.0325 Beta

**Comment by magicmark** [comment]
@Caerostris Yup, having exactly the same issue. Hoping this gets fixed soon!

**Comment by leecade** [comment]
:+1:  got the same error

**Comment by msimpson** [comment]
I'm having the same issue when importing an existing GitHub private repository. Strange.

**Comment by Unknwon** [comment]
Hi all, I think the real problem is what @msimpson said.

Please follow on https://github.com/gogits/gogs/issues/1061 for updates.

Also, if you guys have any idea how to solve this, please help and comment.

Best regards, :beer:
