### ISSUE TITLE
Invalid csrf token.

### ISSUE THREAD

**Issue by freder** [gogits/gogs#715]
hi,

I just installed gogs (0.5.8.1130 Beta) and tried to create a new repository, but when I submit the form all I get is this message:
```
Invalid csrf token.
```

any idea what's going wrong here?

**Comment by ahoehne** [comment]
just faced the problem, but there was no restart of gogs server since i opened chrome. so it might be a caching problem that is probably not coming from the create repo page (reload there didnt helped). reload of start page and after that reload of create repo page solved the problem.

**Comment by Unknwon** [comment]
@ahoehne thanks for the tip!

Did you made sure all dependencies are up-to-date?

**Comment by ahoehne** [comment]
yep, sure - system was up2date and gogs/needed resources where installed just before.
but this issue seems to be very uncommon, didn't saw it again (wasn't able to reproduce it also)
btw i reloaded the page via strg+f5, so i forced my browser to reload cached resources.
maybe thats the reason why it didn't worked for @freder (new tab should "force" the browser also to load some scripts/ resources again)

**Comment by Unknwon** [comment]
@ahoehne I see, thanks again!

**Comment by Unknwon** [comment]
Close discussion for now.

**Comment by JokerQyou** [comment]
I've seen this issue like 2 or 3 times a day. I know how to solve it, but I don't know why it's happening. 
For one time I noticed that there's two `csrf` related cookies there, one is for `/` and the other for `/projects` (my Gogs server is behind nginx, and rewrited to `/projects/` path). I'll report if I find any other clues.

**Comment by Unknwon** [comment]
@JokerQyou Thanks!

From what I found, if I switch between two Gogs instances, this error can occur, but haven't had an idea about why this happens.

**Comment by buzz** [comment]
Happens several time a day while creating repositories or updating issues.
The work around is to close and re-open the page. I didn't restart the server in between.

I'm on Version: 0.6.15.0926 Beta

**Comment by ChangePlaces** [comment]
I think these are the exact steps to reproduce: 

1. Open an issues queue in a tab. 
2. Leave it for a certain number of hours (I'm not sure if it's, say 2, or lots more like 8). 
3. Afterwards, go back to that tab, and click the 'create new' issue or open an issue
4. Either create a new issue, or add a new comment
5. Invalid csrf

**Comment by SR-G** [comment]
I just had the same error message ("Invalid csrf token.") while uploading an avatar (valid .jpg) for a new organization.

Reopening gogs in a private session solved the problem (but no luck by just refreshing the page).
(under Opera 35.0.2066.68 / Windows 8.1)

**Comment by ChangePlaces** [comment]
isn't this a dupe of #1891 ?

**Comment by neolit123** [comment]
i had this issue today, creating a test organisation @ try.gogs.io.
after changing the name to something random (zzz) it worked:

some ideas about CSRF security:
http://stackoverflow.com/questions/23455780/the-csrf-token-is-invalid-please-try-to-resubmit-the-form

**Comment by Unknwon** [comment]
@neolit123 thanks for the tip but this is an old issue, please comment on the latest one #1891
