### ISSUE TITLE
Crashes during migration when password is required.

### ISSUE THREAD

**Issue by tudisco** [gogits/gogs#717]
Gogs crashes if a password is required to access the source repository and you forget to input the username and password. Expected behavior would be a notification that a password is required. Currently if I forget to enter the username and password I have to restart gogs.

Gogs version 0.5.8.1130.
git version 1.7.10.4

I looked in the log and didn't see any entries for the last few times it happened. I looked further back into the past and found this:

[repo.go:213 MigratePost()] [E] MigratePost: git clone: fatal: could not read Username for 'http://xxxx.xxx': No such device or address

Not sure if that is related to this bug.

**Comment by Unknwon** [comment]
This auth error can be detected now.
