### ISSUE TITLE
Mysql broken pipe

### ISSUE THREAD

**Issue by zilionis** [gogits/gogs#721]
I see errors from gogits

[MySQL] 2014/11/26 20:41:58 packets.go:32: unexpected EOF
[MySQL] 2014/11/26 20:41:58 packets.go:118: write tcp 127.0.0.1:3306: broken pipe

Not sure what's happening, but maybe is possible make config for mysql connect via socket?

**Comment by Unknwon** [comment]
It is possible to connect mysql via `unix(xxx)`.
