### ISSUE TITLE
Email only allows PLAIN auth

### ISSUE THREAD

**Issue by andyjeffries** [gogits/gogs#724]
It would be really nice if you could configure the email service a little better.  For example, my server uses CRAM-MD5 rather than PLAIN as it's a [little more secure](http://www.samlogic.net/articles/smtp-commands-reference-auth.htm), but I can't configure GOGS to use this.

I also have a plain SMTP daemon running on the server, listening on port 25 but firewalled off from the outside world, but GOGS can't use this because it tries to authenticate.

So it would be nice if we could configure the mail service to use either different authentication mechanisms or turn them off completely.

I'm currently locked out of my GOGS server (my password management system didn't remember the randomly generated password) so I'm a bit stuck until this is fixed/changed.

P.S. to try and get past the login screen I also tried copying the passwd, rands, and salt fields from a user record on my local machine to the server, but that didn't work either...  It's an aside from the email issue above, but just to let you know that it would be nice if there was another mechanism other than email for getting past a locked account.

**Comment by iSDP** [comment]
2015/03/19 13:49:54 [asm_amd64.s:2232 goexit()] [E] Async sent email 0 succeed, not send emails: xxxx@gmail.com, info: UID: 1, send activate email to xxxx@gmail.com err: 535 5.7.8 Error: authentication failed: PDc5MTUwOTE3OTg4NjM0MzYuMTQyNjc2OTM5MkBhcGkxPg==

When trying to log into my mailserver with TLS and CRAM-MD5

**Comment by phsmit** [comment]
Actually, this issue was already resolved a long time. Are you certain you have the password correct?

**Comment by phsmit** [comment]
https://github.com/gogits/gogs/pull/762#issuecomment-67599790

**Comment by iSDP** [comment]
Yeah, 100% sure.

**Comment by phsmit** [comment]
Could you make a new issue? Also can you get more verbose logs of postfix?

**Comment by phsmit** [comment]
@Unknwon could you close this issue as it was already resolved?

**Comment by iSDP** [comment]
Seems after reloading all three servers (postfix,dovecot,gogs) it now works. :|

**Comment by phsmit** [comment]
Glad it works now!

**Comment by Unknwon** [comment]
@phsmit sure.
