### ISSUE TITLE
Method to import bare git folder

### ISSUE THREAD

**Issue by CootCraig** [gogits/gogs#729]
I just did an install on a clean Debian 7 system and it was easy (Thank you).  I have a large number of shared bare git repositories sitting on a Windows network share.  In order to use Gogs, I will have to
import them some how.  Perhaps I can use an account at bitbucket to stage the repos.  I have a personal Github account, but have no commercial / private account for now.

**Comment by l3iggs** [comment]
So at this point, is it possible for me to migrate an existing directory full of bare git repos into gogs?

**Comment by Unknwon** [comment]
@l3iggs hmm... not yet :mask:

**Comment by Unknwon** [comment]
Hi all, just pushed code to `dev` branch that supports migrate repository by local path: https://github.com/gogits/gogs/commit/059338139ca4a70cb1138dc09039abb5dac0d0f2

**Comment by l3iggs** [comment]
ohh! very cool! I'll try to test this out today.

**Comment by hickscorp** [comment]
I wasn't aware of this being in the pipes... A Gogs anouncement mailing list would be so cool :dancer:

**Comment by Unknwon** [comment]
@hickscorp good idea, will open subscription on the website.

**Comment by robince** [comment]
This is working for me. I have imported several pre-existing bare repos by putting the local path into Migration clone address.

**Comment by lambdaupb** [comment]
Is this not a security issue when any user can import readable git repositories on the server ?
They could try the default paths for repositories of other users of gogs for example. Or worse some system/admin git repo.

**Comment by Unknwon** [comment]
@robince thanks for the feedback!

@lambdaupb right, how about admin gain this ability by default, and other people need to get permission by admin?

**Comment by lambdaupb** [comment]
@Unknwon sounds reasonable :), but maybe be even stricter, make it not allowed in "production" mode? 

Also now only "http" is checked, not "http://" it should be checked that `url.Parse(form.CloneAddr)` errors on paths like "http/xy/z" which are local paths. (they probably are parsable in url, just missing the protocol part)

**Comment by Unknwon** [comment]
@lambdaupb 

> sounds reasonable :), but maybe be even stricter, make it not allowed in "production" mode?

Right, this is a good one, and easier to manage than my proposal.

**Comment by Spy-Seth** [comment]
Nice Issue. I've right know the same need.

**Comment by Unknwon** [comment]
This is implemented.

**Comment by CarlosLopezES** [comment]
Hi!

I am very embarrassed to make an update on such an old subject, but I can't find any other place on the Internet where reference is made.

Is it still possible to import a .git folder by local path? I can't find it in all the documentation.

Thank you very much!
