### ISSUE TITLE
Reference to commits in issues

### ISSUE THREAD

**Issue by Mageti** [gogits/gogs#732]
Hello !
The more I use Gogs, the more I like it.
I just found a missing feature (as of Version ```0.5.8.1210 Beta```) : seeing a commit in an issue.

Let me explain : I open an issue, that have the number '#num'.
Then I mention the issue number in a git commit message, like "this commit corrects issue #num".
When I go to the "commits" view, I see the commit message and the issue number is a link to the correct issue page :
![issue-reference](https://cloud.githubusercontent.com/assets/4189017/5394844/8f75a7a4-8142-11e4-8992-c4f786449cfa.png)

But on that issue page, there is no reference to the commit.
Like in github :
![commit-reference-in-issue](https://cloud.githubusercontent.com/assets/4189017/5394817/3b77135e-8142-11e4-8580-f4f59dd73640.png)

Subsidiary question : is it possible to close an issue with the presence of certain keywords in the commit message ? like "this commit closes #num", with the word "closes" set in configuration to close an issue if used in commit message followed by #num

Thanks in advance.

**Comment by Unknwon** [comment]
It is somehow implemented a while ago...
