### ISSUE TITLE
Syntax highlighted diffs

### ISSUE THREAD

**Issue by andyjeffries** [gogits/gogs#733]
It would be really nice if gogs implemented this new github feature:

https://github.com/blog/1932-syntax-highlighted-diffs

Given there's already syntax highlighting in the code view, I'd imagine this wouldn't be too hard to hack in.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging #2528

**Comment by joshfng** [comment]
I can confirm this works.

<img width="560" alt="screen shot 2016-02-12 at 9 28 46 am" src="https://cloud.githubusercontent.com/assets/302764/13009562/0bd33f9a-d16b-11e5-80eb-95288678892d.png">

**Comment by Unknwon** [comment]
@joshfng thanks, though the screenshot you have only shows diff highlight, not the **syntax** highlight, [this is the example](https://try.gogs.io/gogs/gogs/commit/ce3708b3ea1e2c5dcfeb4cf852651cbda2dfd88c) that shows the highlight of syntax :laughing:

**Comment by joshfng** [comment]
Ah ok. I misunderstood.
