### ISSUE TITLE
Run as daemon

### ISSUE THREAD

**Issue by CootCraig** [gogits/gogs#734]
I installed on a fresh Debian 7.7 virtualbox guest.  /install config worked fine.  Connect from another host worked fine.  After a reboot I get

502 Bad Gateway
nginx/1.2.1

Please advise.  Also is there an IRC channel that gogs folks use.  I can use some help.

**Comment by voxxit** [comment]
Why not run it in a Docker container and let Docker handle the restarts?

**Comment by Unknwon** [comment]
@xj9 thanks your info! 

@voxxit right, an official Docker image of Gogs would be necessary.

**Comment by voxxit** [comment]
@Unknwon I'll work on that in the next couple of days and let you know when I have something up for you to see.

**Comment by Unknwon** [comment]
@voxxit sure thing! 

I think it's better to workout a dockerfile that I can test it(maybe some modifications) and then adopt it as the official image :)

**Comment by jmaks** [comment]
Also trying to init *gogs* on startup via script in https://github.com/gogits/gogs/tree/master/scripts/init/debian

Commands like next one doesn't work properly after *update-rc.d*
``` bash
> sudo service start
```
Then I fix script head in **next order** of requiries and then all starts to works well
``` bash
> head /etc/init.d/gogs               
#! /bin/sh
### BEGIN INIT INFO
# Provides:          gogs
# Required-Start:    $local_fs $network $syslog mysql nginx
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A self-hosted Git service written in Go.
# Description:       A self-hosted Git service written in Go.
### END INIT INFO
```

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
