### ISSUE TITLE
Email addresses treated as at-mentions

### ISSUE THREAD

**Issue by jcracknell** [gogits/gogs#737]
Probably needs some lookbehind for whitespace or string start, e.g. `(?<=^|\s)@[a-z0-9_.-]+`.

**Comment by Unknwon** [comment]
Hi @jcracknell , thanks for your patient! This issue should be fixed by the PR you are referenced. You can also test on https://try.gogs.io/ .

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:
