### ISSUE TITLE
At-mentions processed inside of indented code blocks

### ISSUE THREAD

**Issue by jcracknell** [gogits/gogs#738]
Issue #178 brought this up, but looking at the code it was only fixed for fenced (```` ``` ````) code blocks, and not the indented-by-four-spaces variety, which is the most widely supported code block syntax.

A thought is it might be easier to process these as HTML, for example an at mention cannot be inside of `<[^>]+>`, `<pre[^>]*>((?!<\/pre>).)*<\/pre>` or `<code[^>]*>((?!<\/code>).)*<\/code>`.

Edit: or `<a>`.

**Comment by Unknwon** [comment]
Closed by https://github.com/gogits/gogs/pull/1020
