### ISSUE TITLE
SSH server on Ubuntu no longer reachable

### ISSUE THREAD

**Issue by depl0y** [gogits/gogs#740]
I installed Gogs on an Ubuntu machine, which has an OpenSSH server installed. Because I wanted to still be able to use SSH access on that machine, I updated my sshd_config file, so my SSH server uses a different port.

After that I installed Gogs, but now Gogs seems to use my sshd_config file to configure it's own SSH access? The port I defined for SSH access to the system is now used by Gogs and I am no longer able to access the machine over SSH.

I am not sure how to solve this problem, what I would like to achieve is the following:

SSH access to Gogs/Git over port 22 (default)
SSH access to the system itself over another port

Is there anyone who can help me out, configuring so I still have access to both?

**Comment by Unknwon** [comment]
Any updates on this?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
