### ISSUE TITLE
Default CloneURL of repository in Drone

### ISSUE THREAD

**Issue by rabits** [gogits/gogs#742]
Hello,

- **Gogs Version**: `0.5.8.1210 Beta`
- **Git Version**: `1.9.1`
- **System Type**: `Ubuntu 14.04`
- **Bug Description**:

  I trying to connect Gogs service with Drone and have an issue: Drone can't clone repo, if REQUIRE_SIGNIN_VIEW = true.
  Default CloneURL is pointing to https repository address, but for automation it should use ssh repo address. After I change repo_clone_url in Drone database - it works fine. Also I found strange repo_ssh_url value in Drone's database:
  ```
sqlite> SELECT repo_ssh_url FROM repos WHERE repo_name = "test_priv";
ssh://git@localhost:%!d(string=user)/test_repo/%!s(MISSING).git
  ```

Thanks

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
