### ISSUE TITLE
Add mysql as a required service in default init.d script

### ISSUE THREAD

**Issue by FezzFest** [gogits/gogs#746]
Gogs expects the mysql service to be running when starting. This isn't declared in the default init.d script for debian systems, causing the script to fail in some cases.

Changing `# Required-Start:    $syslog $network` to `# Required-Start:    $syslog $network mysql` solves the issue.

**Comment by Unknwon** [comment]
Close for now, feel free to reopen if you want to continue discussing. :wink:
