### ISSUE TITLE
Unable to assign any issue myself

### ISSUE THREAD

**Issue by steelbrain** [gogits/gogs#747]
I am running the latest binary for linux_amd64 available on the GitHub releases page. I was able to successfully assign the first 12 issues to myself, from then on.
If I create a new issue and assign it to myself, I get a JSON parse issue.
On current issues, clicking my username in assign list doesn't work.

Looking at the network console, It's giving me 500 Internal Server Error on this url

     http://localhost:3500/steelbrain/MyRepo/issues/15/assignee

Here's something from gogs.log that might be useful

     [issue.go:634 UpdateAssignee()] [E] UpdateIssueUserPairByAssignee: %v: no such column: true

This is something from xorm.log that I think is related to it

    [xorm] [info]  2014/12/15 03:16:23.197098 [sql] UPDATE `issue_user` SET is_assigned = true WHERE uid = ? AND issue_id = ? [args] [1 15]
    [xorm] [debug] 2014/12/15 03:16:23.197258 [time] UPDATE `issue_user` SET is_assigned = true WHERE uid = ? AND issue_id = ? - args [1 15] - execution took: 135588ns

**Comment by bastiao** [comment]
I'm in develop branch and I still have the issue. Any ideas?

**Comment by Unknwon** [comment]
@bastiao thanks for the report, I reproduced this also.

**Comment by da-kid** [comment]
+1

**Comment by Unknwon** [comment]
Right now in `develop` branch you can assign yourself. 

You can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Closed as implemented. :star:

**Comment by steelbrain** [comment]
Great :clap:
