### ISSUE TITLE
Enable login type conversion after account creation

### ISSUE THREAD

**Issue by shaform** [gogits/gogs#748]
As mentioned in #8, even though the UI seems to suggest that we can change an account to use LDAP authentication, it's actually not supported. It might be a good idea to actually support switching login type or just change the UI.

**Comment by uolter** [comment]
I have the same issue running the version 0.5.11 Beta.
Moreover when I configure the ldap authentication the form has a couple of fields: **Search Attributes** and **Search Filter** which are supposed to be mandatory, but they are not.

It would be nice to have the possibility to validate the ldap configuration.

**Comment by Unknwon** [comment]
This should have been implemented in latest Gogs.

**Comment by Unknwon** [comment]
Close as implemented. :tada:
