### ISSUE TITLE
Post-Install am met with a blank page for /users/login/

### ISSUE THREAD

**Issue by wayneeseguin** [gogits/gogs#756]
I want to try out gogs however I am met with an error, I've tried on two systems so I know it's not the system. I downloaded the binary zip, extracted, configured (using redis & postgres) and started gogs web. I filled out the /install page and hit save, the logs show everything was successful. 

It is at this point that I am met with a completely blank page at /user/login/. If I go to /explore I am met with the outer page but when I click sign in it is empty again.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
