### ISSUE TITLE
Synchronize .ssh/authorized_keys on request 

### ISSUE THREAD

**Issue by fzerorubigd** [gogits/gogs#763]
There is no way to synchronize authorized key in web and the .ssh/authorized_key. 
I want to make sure there is no other key in the authorized_key except the keys from gogs. the problem was I reinstall gogs in my machine and I get this error : 
```
 Gogs: you are not the owner of SSH key
```

Another thing is if this file is out of sync, then the ssh add/delete dose not work correctly. but I'm not sure about this.

**Comment by Unknwon** [comment]
fixed by #818
