### ISSUE TITLE
Email address can be changed without activation

### ISSUE THREAD

**Issue by phsmit** [gogits/gogs#768]
If REGISTER_EMAIL_CONFIRM = true, a link in an email needs to be clicked to activate the account. However, changing the email address on the profile page is done without questions asked (or any new email confirmation for that matter).

With the new multiple_emails feature, we could do the following:
 - Make the email address on the user/settings page uneditable, with a note that you can change the email on the user/settings/email page.
 - Make the procedure to edit the email addres: 1. add a new email, 2. confirm it, 3. remove the old email address

Does this make sense? Shall I make a PR that does exactly this?

**Comment by Unknwon** [comment]
Somewhat is has been fixed?
