### ISSUE TITLE
initial url request after login gone

### ISSUE THREAD

**Issue by Dennis-Smurf** [gogits/gogs#777]
- **Bug Description**:  In my browser I have a bookmark like http://localhost:3000/ProjectX/repositoryX/issues. 
When I goto this url, I have to sign in ('Require Sign In View' is marked). 
After signing in, the page redirects me to the homepage (http://localhost:3000) instead of the initial url. 
Is it possible that the page gets redirected to the initial request url?

- **Gogs Version**: 0.5.9.1216 Beta
- **System Type**: Windows

**Comment by torkelo** [comment]
I think this is cause by AppSubUrl being an empty string, 

from auth middleware 
```go
ctx.SetCookie("redirect_to", "/"+url.QueryEscape(setting.AppSubUrl+ctx.Req.RequestURI), 0, setting.AppSubUrl)
```

When AppSubUrl is emtpy the cookie path will not be set and the browser will set it to the full requested path.

**Comment by Unknwon** [comment]
Hi @torkelo , I think the auth middleware is functioning, and the problem we have here is **only must login pages are set cookie for redirecting back after login**, like create repository, issue, etc.

So issue here is Gogs doesn't set cookie for redirecting back when every page becomes **must login**.

Hope helps you understand!

**Comment by Unknwon** [comment]
Hi @Dennis-Smurf , build from latest code of `master` branch, I cannot reproduce this issue in both Mac and Windows system, can you check again?

**Comment by Unknwon** [comment]
Ping @Dennis-Smurf :dizzy:

**Comment by Unknwon** [comment]
Close as no further feedback.
