### ISSUE TITLE
 RPC failed; result=22, HTTP code = 501

### ISSUE THREAD

**Issue by WanliTian** [gogits/gogs#783]
Completed /test/test/info/refs?service=git-receive-pack 401 Unauthorized

**Comment by Unknwon** [comment]
Thanks your feedback!

- What is your Gogs version?
- How did you push?(steps)

**Comment by chk1** [comment]
I'm facing a similar issue, not sure if it's the same as the original one.

My Gogs details:
```
2015/03/13 11:54:07 [I] Gogs: Go Git Service 0.5.16.0301 Beta
2015/03/13 11:54:07 [I] Log Mode: File(Trace)
2015/03/13 11:54:07 [I] Cache Service Enabled
2015/03/13 11:54:07 [I] Session Service Enabled
2015/03/13 11:54:07 [I] Run Mode: Production
2015/03/13 11:54:08 [I] Listen: http://0.0.0.0:3000
```

I think the issue appeared after I upgraded from a ~4 month old version. I am using LDAP authentication. Login to web interface has worked and still works fine.

I'm commiting and pushing my changes as usual, but authentication fails every time:
```shell
$ git push
Username for 'http://my-gogs-server:3000': me
Password for 'http://me@my-gogs-server:3000':
fatal: Authentication failed
```
Log from Gogs:
```
[Macaron] Started GET /me/myproject.git/info/refs?service=git-receive-pack for 128.0.0.1
[Macaron] Completed /me/myproject.git/info/refs?service=git-receive-pack 401 Unauthorized in 11.158027ms
[Macaron] Started GET /me/myproject.git/info/refs?service=git-receive-pack for 128.0.0.1
[Macaron] Completed /me/myproject.git/info/refs?service=git-receive-pack 401 Unauthorized in 4.857657ms
[Macaron] Started GET /me/myproject.git/info/refs?service=git-receive-pack for 128.0.0.1
2015/03/13 11:54:16 [D] LDAP Authen OK: me
2015/03/13 11:54:16 [D] LDAP Authen OK: me
[Macaron] Completed /me/myproject.git/info/refs?service=git-receive-pack 401 Unauthorized in 61.290118ms
```

I tried two different git projects, same result on both. I can push commits with my local admin account.

**Comment by Unknwon** [comment]
@chk1 thanks for the details!

Would you mind to try the latest version on `master` so that's easier to debug and make fix.

BTW, there are some other relevant information I want to provide:

- in your version there was a bug on HTTP/HTTPS push for **not updating feeds after push successfully**
- ..., also LDAP auth for pushing code has been changed to **talk to your LDAP server every time** in order to make sure your username and password are correct in your LDAP server, which should be done but just fixed recently. In other words, your LDAP-type account's password isn't the one you set in Gogs web UI, but the LDAP server that you set Gogs to connect to.

**Comment by chk1** [comment]
>...your LDAP-type account's password isn't the one you set in Gogs web UI, but the LDAP server that you set Gogs to connect to.

I am using my LDAP credentials for the LDAP user (it says `LDAP Authen OK` during push), I will try your suggestions the next time I have the chance. Thanks for the support!

**Comment by Unknwon** [comment]
@chk1 no problem!

**Comment by chk1** [comment]
I just upgraded to the newest version:
`2015/03/16 14:25:28 [I] Gogs: Go Git Service 0.5.16.0316 Beta`

The bug is still present, I might set up Gogs from scratch though to test this more in depth.

**Comment by Unknwon** [comment]
@chk1 do you think it is related to LDAP?

**Comment by chk1** [comment]
I think it is definitely LDAP related. I have set up Gogs new from scratch today, the only thing I configured was LDAP authentication.

Same procedure as above,
- Create repository with a README
- Clone to local computer
- Change something
- Commit & push

These are the logs:

```
2015/03/18 16:02:44 [I] Gogs: Go Git Service 0.6.0.0318 Beta

[...]

[Macaron] Completed /my_username/mein-test-2.git/info/refs?service=git-receive-pack 401 Unauthorized in 4.679978ms
[Macaron] Started GET /my_username/mein-test-2.git/info/refs?service=git-receive-pack for 128.0.0.1
2015/03/18 16:04:22 [D] LDAP Authen OK: my_username
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x850ac45]

goroutine 189 [running]:
runtime.panic(0x8647f00, 0x8b1df93)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xe9
github.com/gogits/gogs/modules/asn1-ber.readBytes(0x0, 0x0, 0x193d7a10, 0x2, 0x2, 0x0, 0x0)
	/home/git/go/src/github.com/gogits/gogs/modules/asn1-ber/ber.go:181 +0x85
github.com/gogits/gogs/modules/asn1-ber.ReadPacket(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/git/go/src/github.com/gogits/gogs/modules/asn1-ber/ber.go:194 +0xb5
github.com/gogits/gogs/modules/ldap.(*Conn).reader(0x194ecd20)
	/home/git/go/src/github.com/gogits/gogs/modules/ldap/conn.go:259 +0x80
created by github.com/gogits/gogs/modules/ldap.(*Conn).start
	/home/git/go/src/github.com/gogits/gogs/modules/ldap/conn.go:83 +0x35
```
I put the rest of the error message here: https://gist.github.com/chk1/1e7ac93491c71ba86b40

**Comment by Unknwon** [comment]
@chk1 thanks for the info!

I need to dig into go-ldap package see if anything helps.

**Comment by Unknwon** [comment]
What is the status of this issue?

**Comment by chk1** [comment]
I don't have access to a Windows Domain anymore, maybe someone else can confirm it?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
