### ISSUE TITLE
renaming repositories breaks access permissions

### ISSUE THREAD

**Issue by nicolai86** [gogits/gogs#784]
**Bug Description**: 

renaming repository inserts wrong permissions into access table. This manifests in the renamed repo not being listed in the org overview, because the permission check fails.

**Gogs Version**:

0.5.9.1213 Beta

**Git Version**:

git version 2.1.0

**System Type**:

Ubuntu 14.10 

**Error Log**:

None, determine by hand

**Other information**:

Given an Org named "FooBar", renaming a repository inserts an access of "FooBar/baz", where it should be "foobar/baz", as can be infered from just creating the repository with the correct name in the first place.

Changing the access table to contain "foobar/baz" resolves the issue.

**Comment by Unknwon** [comment]
Thanks your report!

Looks like Gogs didn't convert org name to lower cases.

**Comment by Unknwon** [comment]
Hi @nicolai86 , I've pushed a fix on `dev` branch, you can also test on https://try.gogs.io

**Comment by nicolai86** [comment]
Thanks!

**Comment by Unknwon** [comment]
@nicolai86 happy new year!

**Comment by nicolai86** [comment]
To you too :)

**Comment by nicolai86** [comment]
works like a charm! I'll close it now. thanks a bunch again =)
