### ISSUE TITLE
Avatars support should include federated servers

### ISSUE THREAD

**Issue by k0lter** [gogits/gogs#786]
AFAIK, gogs dot not support federated servers while using avatars: see section "Federated servers" in http://wiki.libravatar.org/api/
It could be nice to get it implemented.

Thanks and keep up the good work.

**Comment by Unknwon** [comment]
Hi @k0lter , I think this PR(https://github.com/gogits/gogs/pull/1457) solved your problem in some degree.

It is possible now to set a URL e.g. http://cdn.libravatar.org/avatar/ as the source, any URL.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by k0lter** [comment]
Hi @Unknwon,

I'm sorry but this PR doesn't fixes this bug.

My fe

**Comment by Unknwon** [comment]
Then I don't understand the problem here. 

I saw the `Federated servers` and it just says need a DNS query, but query what URL?

**Comment by k0lter** [comment]
It's explained in my second comment (Dec 28, 2014).

**Comment by Unknwon** [comment]
Thanks, but I'm not very familiar with DNS thing, how do you know it is `_avatars._tcp.gogs.io` with `_tcp.gogs.io` suffix?

**Comment by k0lter** [comment]
You can take a look at http://wiki.libravatar.org/running_your_own/

About *._tcp.* DNS records, there are a lot of decentralized services which works like this. For exemple Jabber/XMPP, see http://wiki.xmpp.org/web/SRV_Records

**Comment by Unknwon** [comment]
So the `*.gogs.io` thing you would have to config it so when do the DNS lookup Gogs can use `_avatars._tcp.gogs.io`, correct me if I understand it wrong.
