### ISSUE TITLE
Commit message not truncated in repository overview

### ISSUE THREAD

**Issue by klausenbusk** [gogits/gogs#788]
- **Bug Description**: 
The commit message in the repository overview, is not truncated.. It seems like there is missing a "max-width"..
https://try.gogs.io/klausenbusk/test
Tested in Firefox, Chromuim and Safari.
- **Gogs Version**: `v0.5.9.1216 Beta`
- **Git Version**: `2.2.1`
- **System Type**: `Arch Linux`
- **Error Log**: Nothing
- **Other information**: Truncate work in commit overview..

**Comment by Unknwon** [comment]
Sorry for late, should be fixed in a PR and come with `v0.5.11` release!
