### ISSUE TITLE
Old repository not updating news feed and "Updated x ago"

### ISSUE THREAD

**Issue by klausenbusk** [gogits/gogs#789]
- **Bug Description**: 
Today I pushed commits to 3 of my "old" repositories.
Later today, I created a new repository and discovered it added some entry to my "News Feed", every time I did a commit, the "Updated x ago" also got updated under my profile every time.
That got my wondering, why I did that for my 3 commits to my "old" repositories, and why the "Updated x ago" stuck at 3 months..

- I read the serve.go and update.go, trying to understand how it work, I then checked the log files, and there was no errors at all. For my new repository there was some "Repository updated:", but nothing for my "old" repository..
- **Gogs Version**: `v0.5.9.1216 Beta`
- **Git Version**: `2.2.1`
- **System Type**: `Arch Linux`
- **Error Log**: Nothing
- **Other information**: `gogs fix` didn't change anything..

**Comment by deringer** [comment]
Hi @Unknwon, I'm experiencing this issue also. It seems to have stopped updating about a day ago.

For a new repo I have, it adds to activity feed fine.

I had one created in an organisation, that doesn't seem to be updating though.

I just created a new user repo and pushed and it updated the activity feed.

I created a new organisation repo and pushed and it updated the activity feed.

I have updated from master since I created the original repo. I have also switched my origin (the repo was in BitBucket, then I switched it to gogs) in my working copy. I cloned that same repository directly from gogs and the activity doesn't appear in it.

Hope that gives you some direction on where to look to fix this issue!

**Comment by klausenbusk** [comment]
Ho @deringer is the git update hook missing?

**Comment by deringer** [comment]
It's working fine for others, unless the hook is per-repository? Where would I look to check?

**Comment by klausenbusk** [comment]
> It's working fine for other repos, unless the hook is per-repository? Where would I look to check @klausenbusk?

It is per-repository, check <repository-root>/user/repo/hooks . There should be a update file..

**Comment by deringer** [comment]
Looks like it's not there. This is from one of the repos that isn't working:

```
applypatch-msg.sample  commit-msg.sample  post-update.sample  pre-applypatch.sample  pre-commit.sample  prepare-commit-msg.sample  pre-push.sample  pre-rebase.sample  update.sample
```

This is from one that is:

```
applypatch-msg.sample  commit-msg.sample  post-commit.sample  post-receive.sample  post-update.sample  pre-applypatch.sample  pre-commit.sample  prepare-commit-msg.sample  pre-rebase.sample  update  update.sample
```

I wonder what would cause the hook to disappear? It might have something to do with the fact that I migrated the repository and that process didn't create the `update` hook. Looking at the non-working hooks directory, all those files are set with permissions 775, whilst one that was created by gogs they're all 666 AND there's also an `update` and `post-commit` hook present.

That said, perhaps gogs should check if the `update` hook exists for a migration - if not, create it and if so, merge / append it to the existing one?

**Comment by klausenbusk** [comment]
@Unknwon I was able to reproduce this (what @deringer said):
1. New Migration <https://github.com/gogits/gogs>
2. git clone https://try.gogs.io/klausenbusk/gogs
3. touch test && git -a commit -m "test" && git push
4. "activity" feed not updated..
https://try.gogs.io/klausenbusk/gogs
![skaermbillede fra 2015-02-09 18 20 33](https://cloud.githubusercontent.com/assets/1080056/6111333/63f3da68-b088-11e4-905c-7605b289ab64.png)

**Comment by Unknwon** [comment]
@klausenbusk thanks for the tip!

**Comment by Unknwon** [comment]
Hi @klausenbusk , I've pushed fix on `dev` branch and you can test on https://try.gogs.io

BTW, if you want to fix old repos, there is an operation called `Rewrite all update hook of repositories` to do this job right now.

**Comment by klausenbusk** [comment]
> Hi @klausenbusk , I've pushed fix on dev branch and you can test on https://try.gogs.io

I can confirm that it work now, when you do a "Migration"..

**Comment by Unknwon** [comment]
@klausenbusk awesome!

Thanks for your patient!
