### ISSUE TITLE
Automatically convert SSH2 public keys to OpenSSH format

### ISSUE THREAD

**Issue by rojaro** [gogits/gogs#798]
To use a SSH2 public key with gogs one has to convert it to the OpenSSH format first i.e. through ssh-keygen
```
ssh-keygen -i -f ssh2.pub > openssh.pub
```
It would be useful to automatically convert these keys into the OpenSSH format so a windows user doesnt have to do that.

As the conversion is pretty simple (basically just string manipulation), this could be done without using ssh-keygen within gogs. To test this, you can create a SSH2 public key from your existing OpenSSH key using
```
ssh-keygen -e -f openssh.pub > ssh2.pub
```

**Comment by Unknwon** [comment]
Sounds not bad. But how does Gogs know user is giving SSH2 or SSH public key?

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/1877 now :D
