### ISSUE TITLE
TLS Error when using https

### ISSUE THREAD

**Issue by mortik** [gogits/gogs#802]
When i switch to https i'm getting the following TLS Error:

```
2014/12/29 23:57:23 http: TLS handshake error from 127.0.0.1:43480: tls: first record does not look like a TLS handshake
```

The https Part in my app.ini looks like:

```
[server]
PROTOCOL = https
DOMAIN = git.mortik.de
ROOT_URL = https://git.mortik.de
...
CERT_FILE = /home/git/gogs_ssl.crt
KEY_FILE = /home/git/gogs_ssl.key
```

**Comment by Unknwon** [comment]
Thanks your report!

As I did some googling, I haven't got an idea of this error.

Following information maybe helpful:

> 2014/12/29 23:57:23 http: TLS handshake error from 127.0.0.1:43480: tls: first record does not look like a TLS handshake

Where is this error coming from?

- How did you visit your Gogs instance? Directly or via Nginx?

**Comment by mortik** [comment]
via nginx 

i've set gogs protocol settings to http and setup ssl only in nginx. 
The remaining Problem is that Chrome and Firefox are showing warnings about that gogs loads some assets via http and not https

**Comment by Unknwon** [comment]
> The remaining Problem is that Chrome and Firefox are showing warnings about that gogs loads some assets via http and not https

I would say it's true.

So did the original problem solved? Do you have any other questions? :santa:

**Comment by mortik** [comment]
sorry, yes the problem is solved for me ^^

**Comment by Unknwon** [comment]
@mortik cool, happy new year!

**Comment by mortik** [comment]
@Unknwon happy new year! :)

**Comment by Hayaweh** [comment]
Hi, 

I had the issue today too. Exactly the same error message when I noticed... 
In the browser bar address, do not forget to type "https" in the address at the beginning.
This fixed it for me and I have been able to add the security exception (as I am not using "trusted" SSL certificates).

I do write it here in case anybody runs into the issue as, as stupid as it is. It might be the issue. :) 

PS: then it seems that if you're in HTTPS mode, if you type the address as an HTTP one, it will do the TLS handshake error: first record does not look like a TLS handshake. I don't know how hard it would be for you, but it might be interesting if when in HTTPS mode it would automatically redirect the "http://blablabla.bla" to "https://blablabla.bla".

**Comment by Unknwon** [comment]
@Hayaweh 

> but it might be interesting if when in HTTPS mode it would automatically redirect the "http://blablabla.bla" to "https://blablabla.bla".

It is nice but you would end up hacking Go source code somehow... but not 100% sure.

Normally we put NGINX front it and redirect HTTP to HTTPS.

**Comment by Hayaweh** [comment]
@Unknwon 
Well. I have absolutely no idea if this is possible or not. 

As for putting NGINX in front, currently I am running it from a Windows Server 2012 and have no web-server installed aside of IIS. (I guess that we can do it there too but that would allow not to have a web-server behind it). 

As I said, I have no knowledge of Go nor the internal structure of Gogs so.. I don't know. :)

**Comment by Unknwon** [comment]
@Hayaweh no worries, but if you Google `iis redirect http to https`, you should get some helpful info.

**Comment by Hayaweh** [comment]
@Unknwon 
Thanks, I already know how to do it. But I was surprised that Gogs did not handle it. (which explained the error stated above)

**Comment by Unknwon** [comment]
@Hayaweh I see :smile:

**Comment by tboerger** [comment]
This is simply not possible with a single port. You have to bind 2 ports, one for http and one for https. In the case of golang you have to run them in go routines because the serve function only returns on error. Redirecting from http to https is absolutly not possible with a single port binding.
