### ISSUE TITLE
Mirror repository not work with SQLite3

### ISSUE THREAD

**Issue by xudaiqing** [gogits/gogs#805]
I can not get mirror repository working. I only find a error log say [E] repo.MirrorUpdate: database table is locked: mirror.

I install the gogs with sqlite. And have try to install on centos 7 and debian, none of them working.

**Comment by xudaiqing** [comment]
I have try the v0.5.5 v0.5.8 v0.5.9 download from http://gogs.io/docs/installation/install_from_binary all end up with same problem

**Comment by Unknwon** [comment]
Hmm, SQLite is always the troublemaker. 

Thanks your report!

**Comment by Unknwon** [comment]
Hi, I've pushed a fix on `dev` branch.
