### ISSUE TITLE
how to proxy in apache

### ISSUE THREAD

**Issue by qyh214** [gogits/gogs#806]
Please add how to proxy in apache because I failed many times
in http://gogs.io/docs/intro/faqs.html tell us about how to proxy in nginx，but no apache……

**Comment by Unknwon** [comment]
Close for inactive status, feel free to reopen and continue discussion!

**Comment by flotho** [comment]
hy @qyh214 , I've tried this #1202 with success.

regards

**Comment by kryztoval** [comment]
I had an issue with the releases as my proxy settings were incomplete, Adding the ProxyPreserveHost  and ProxyRequests fixed this, thank you!
