### ISSUE TITLE
error when migrating git repository

### ISSUE THREAD

**Issue by Raboo** [gogits/gogs#807]
When I try to migrate a git repository into gogs it tries to resolv the username as the host.

gogs.log
```2014/12/30 13:48:37 [T] action.NewRepoAction: administrator/chef-repo
2014/12/30 13:48:37 [repo.go:213 MigratePost()] [E] MigratePost: git clone: error: Couldn't resolve host 'admin' while accessing http://admin:somepasswd@somehost/chef-repo.git/info/refs
fatal: HTTP request failed```

**Comment by Raboo** [comment]
No need for screenshot, it Displays the big 500.png

**Comment by phsmit** [comment]
@Raboo Below the png there is the printed error. Anyway, I made #822 which fixes this issue. Could you checkout the PR I made and test if it solves your problem (you need to compile with Go 1.4 though for it to be fixed!)
