### ISSUE TITLE
Wrong image address when rendering markdown files

### ISSUE THREAD

**Issue by hefanbo** [gogits/gogs#808]
If a image is included using relative path (e.g., `![altxt](images/image.png)`) in a markdown file, it cannot be displayed in the file's page `.../src/master/somefile.md` because of wrong image address, although images in README.md can be correctly displayed in the project's page `.../src/master`.

Possible solution:
```
--- a/routers/repo/view.go
+++ b/routers/repo/view.go
@@ -98,7 +98,7 @@ func Home(ctx *middleware.Context) {
 				readmeExist := base.IsMarkdownFile(blob.Name()) || base.IsReadmeFile(blob.Name())
 				ctx.Data["ReadmeExist"] = readmeExist
 				if readmeExist {
-					ctx.Data["FileContent"] = string(base.RenderMarkdown(buf, ""))
+					ctx.Data["FileContent"] = string(base.RenderMarkdown(buf, branchLink))
 				} else {
 					if err, content := base.ToUtf8WithErr(buf); err != nil {
 						if err != nil {
```

Not sure if this patch has any side effects.

**Comment by Unknwon** [comment]
Thanks patch! I've pushed fix on `dev` branch.
