### ISSUE TITLE
Error while downloading gogs with SQLite3

### ISSUE THREAD

**Issue by bhanuV** [gogits/gogs#810]
go get -u -tags "sqlite redis memcache" github.com/gogits/gogs
# github.com/gogits/gogs/cmd
go/src/github.com/gogits/gogs/cmd/web.go:131: unknown "github.com/macaron-contrib/cache".Options field 'Conn' in struct literal

**Comment by Unknwon** [comment]
Happy new year!

**Comment by bhanuV** [comment]
Happy New year to you too!
