### ISSUE TITLE
CI status with hook

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#813]
This feature request might not be one of the most easy, and is related to https://github.com/gogits/gogs/issues/5

The idea would be for Gogs to expose a simple API for continuous integration / deliveries system to be able to report back about specific commits / PR quality.

An example of how you set up Github to talk with Travis is explained here: http://stackoverflow.com/questions/19810386/showing-travis-build-status-in-github-repo

Basically, i have right now Gogs talk with my CI server in one way, to trigger builds within the CI system. What i would like to do is being able to configure the other way-communication, to allow Gogs to have visibility wether a specific commit / PR passes or fails the tests.

The exposed API should be template-based, or simple enough to be hook-able to any other web-hook based system, this way anyone could configure gogs with his favorite CI / CD system.

Tell me if i'm clear enough, i don't have the exact word for this process.

**Comment by kageurufu** [comment]
:+1: for this

**Comment by bhchew** [comment]
+1

**Comment by cusspvz** [comment]
+1

**Comment by ekozan** [comment]
+1

**Comment by thecanadianbaker** [comment]
Has anyone started doing any work on this or is it still available?

**Comment by Unknwon** [comment]
@thecanadianbaker I don't think anyone one is working on it, but it is also not a easy thing to implemented.

**Comment by thecanadianbaker** [comment]
I agree that the proposed is not easily implemented, but I think we might
be looking at it the wrong way. I think that a much simpler implementation
would be to leave the responsibility of recording and storing the
information regarding builds with the build engine, and instead have Gog's
request that information using a standard internal interface at the time of
display. That means that we can implement a common interface within Gogs to
make the build status request using some standardized parameters, but it is
up to the implementing package to manage the interaction with the build
server.

Is this feasible and does it sound appropriate?

**Comment by Unknwon** [comment]
@thecanadianbaker This feature should be a part of the entire new system like GitHub's pull request merge checks.

Just the hook is easy, but that's not very extendable.

**Comment by naggie** [comment]
Very glad to see this has been added to a milestone. Great, thanks!

**Comment by migibert** [comment]
+1

**Comment by renewsorensen** [comment]
+1

**Comment by farooq-khan-nxt** [comment]
+1
Something like when you raise a Pull request CircleCI automatically builds and lets us know if pull request will pass build or fail.

**Comment by hz** [comment]
+n, n > 好多好多。 gogs后面的团队好给力。

**Comment by neithere** [comment]
I don't see how Gogs could have any practical value without this feature.

**Comment by strk** [comment]
How github implements this: https://developer.github.com/v3/repos/statuses/

**Comment by tboerger** [comment]
IMHO this feature can be integrated quite easy if you do it like github

**Comment by cblomart** [comment]
Would realy love to see this type of integration! 
This allows a more automated control of what enters a repo. (coding style / tests / build). All automaticaly reported :)
:+1:

**Comment by kmadel** [comment]
Is anyone working on this one yet?

**Comment by strk** [comment]
On September 2, 2016 5:46:06 PM CEST, Kurt Madel <notifications@github.com> wrote:
>Is anyone working on this one yet? 

Not me. Planning to start?
--strk;

Sent from hand-held device, sorry for brevity

**Comment by Unknwon** [comment]
Merge this thread to https://github.com/gogits/gogs/issues/4631.
