### ISSUE TITLE
API Documentation / Exposure

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#814]
How difficult / relevant would it be for Gogs to have an automatically generated summary of what it offers in terms of API right now? What is the status of the current API, what can we do with it? Are there codding guidelines when creating new features in Gogs, to expose them to the API?

I would really love to have a formal / cheat-sheet of the available API commands for any given version of Gogs.

**Comment by Unknwon** [comment]
Hi @hickscorp, currently Gogs has some APIs, but we won't to take this seriously until v0.6.0 is released. 

For APIs we have right now, is because people ask for(mostly for drone integration). 

A bit ahead information, we would basically following design of GitHub APIs to expose Gogs's APIs.

**Comment by jaredly** [comment]
For future, here is the code enumerating the current API, such as it is: https://github.com/gogits/gogs/blob/master/cmd/web.go#L192

Looks like you `POST` to `api/v1/users/:username/tokens` to create a new token (with `Name` and `Uid` as parameters [see code](https://github.com/gogits/gogs/blob/master/routers/api/v1/user_app.go#L35), and then you can use that to make further requests.

**Comment by Unknwon** [comment]
Fixed by https://github.com/gogits/go-gogs-client/wiki
