### ISSUE TITLE
Augmented Administrative Privileges

### ISSUE THREAD

**Issue by hickscorp** [gogits/gogs#815]
When a Gogs administrator is logged-in, it appears that he cannot have visibility over important things on the system.
For instance
- Users real name isn't accessible,
- User public keys isn't accessible,
- Absolutely no way to edit Organisations details if you don't own them.

Sometimes, when someone is in charge of a repository, it is good for him to have access to these parameters, for instance to help other users complete their profile if they don't know how to use the system, or simply to correct mistakes done by other users.

Is this an interesting-enough feature that could be added to the roadmap?

**Comment by Unknwon** [comment]
Thanks your feedback!

> Users real name isn't accessible

Can you given an example?

> User public keys isn't accessible

https://try.gogs.io/unknown.keys , does this help?

> Absolutely no way to edit Organisations details if you don't own them.

Someone requested in another issue, I remember. And yes, it's in the roadmap, definitely!

**Comment by hickscorp** [comment]
>> Users real name isn't accessible
> Can you given an example?
Sure. When you are editing your own `Settings > Profile`, you can set a text field named `Full Name`. But when you are an administrator and go to `Admin > Users > Edit a User`, this field is not there to be edited.

> https://try.gogs.io/unknown.keys , does this help?
Not really. Here is why. As there are no ways to set public keys for organisation (See the feature request

**Comment by Unknwon** [comment]
For 1 and 2, I see!

**Comment by hickscorp** [comment]
Im closing this issue, as I’m very happy to see that i can edit most of the important information about users when I’m an admin now! And since there are deployment SSH keys support, this issue is pretty much solved.

Good work! :100:

**Comment by Unknwon** [comment]
:trollface:
