### ISSUE TITLE
go-getable for private repository

### ISSUE THREAD

**Issue by fzerorubigd** [gogits/gogs#816]
I have private repository and I need to make it go-getable, all user has access to this repository (via their ssh keys) but the problem is the first request by go (with the ?go-get=1) failed.
output is : 

```<a href="/user/login">Found</a>.``` 

gogs redirect this to login page, but I need this particular request to work. Is there anyway to handle this problem?

**Comment by phsmit** [comment]
It would be quite a leak if you can see if someone has a private repository, so it does not sound like a good idea.

However, go has a functionality for this. If you add .git to the import path, it will not need to do a https request with that meta tag.

For example, I just made the private repository try.gogs.io/petersmit/mymodule and then I tried:

    go get try.gogs.io/petersmit/mymodule.git

which works perfectly (with https). If you want to use git+ssh, you can set this in the git config: http://michaelheap.com/golang-how-to-go-get-private-repos/

**Comment by Unknwon** [comment]
go-getable is meant for public repositories, `quite a leak`, I would say too.

**Comment by fzerorubigd** [comment]
1- What if it is in setting dialog so the owner could decide what to do? 
the meta just contain the path to clone the repo, and the repo itself is protected, It could be leak, but not `quite a leak`.
2- the .git is not good since it is inside import in some go file, mostly I do not get the repo directly.

**Comment by phsmit** [comment]
2. You can do this also in import statements inside go! E.g. import "try.gogs.io/petersmit/mymodule.git" or import "try.gogs.io/petersmit/mymodule.git/submodule"

**Comment by Unknwon** [comment]
The solution I can think if is what I called `partial public` which allows Git works as if it is public but normal access would remain the repository as private. This way, go get would work(through HTTP/HTTPS).

How does this sound?

**Comment by Unknwon** [comment]
Won't be fixed...
