### ISSUE TITLE
Web UI Shows Incorrect Path with Nginx Reverse Proxy

### ISSUE THREAD

**Issue by jnakatsui** [gogits/gogs#817]
Using the following nginx config.

server {

   listen 80;
   server_name example.com/gogs www.example.com/gogs;
   location /gogs/ {
       proxy_pass http://127.0.0.1:3000/;
       include proxy_params;

   }

}

The /gogs will show in the web ui for connecting to the git repo over ssh

Example:
git remote add origin git@example.com/gogs:atlas/ansible-atlas.git

However, the the correct path should be:
git remote add origin git@example.com:atlas/ansible-atlas.git

Without the /gogs.

I describe issue that arises in more detail at the bottom of this issue:
https://github.com/gogits/gogs/issues/458#issuecomment-68127871

**Comment by phsmit** [comment]
I dived into the code, and everything seems to be correct already!

Probably you have a mistake in the configuration. DOMAIN should not contain the subpath, ROOT_URL should. E.g.:

DOMAIN = myserver.com
ROOT_URL=http://myserver.com:3000/gogs/

**Comment by Unknwon** [comment]
Hi @jnakatsui , I think @phsmit gives the same answer as I will, do you have any progress on the issue?

**Comment by jnakatsui** [comment]
That was it sorry for the mistaken configuration.

**Comment by Unknwon** [comment]
@jnakatsui great! So I close this issue right now unless you want to continue discuss on it. :smile:
