### ISSUE TITLE
教育网下Jquery、font-awesome.min.css和Gravatar不能访问？

### ISSUE THREAD

**Issue by mervin0502** [gogits/gogs#824]
针对Jquery、font-awesome.min.css，我修改了templates/ng/base/head.tmpl文件中的href，但是网页没有修改？
Gravatar头像，可以停用或者有默认头像吗？

**Comment by Unknwon** [comment]
- You can change site to offline mode: https://github.com/gogits/gogs/blob/master/conf/app.ini#L20
- ...and use Duoshuo mirror for Gravatar: https://github.com/gogits/gogs/blob/master/conf/app.ini#L180

**Comment by mervin0502** [comment]
@Unknwon 谢谢。

**Comment by Unknwon** [comment]
Happy new year!

Don't forget to close this issue if problem solved!

**Comment by Unknwon** [comment]
Feel free to reopen this issue if you have further concerns!
