### ISSUE TITLE
500 when add repository to non-empty teams

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#831]
From https://github.com/gogits/gogs/issues/533#issuecomment-68720931

**Comment by Nickoladze** [comment]
Currently hitting this problem on v0.5.13 binary with sqlite3 when trying to add a repository to a team.

Log file:
2015/03/17 13:24:38 [teams.go:141 TeamsRepoAction()] [E] Action(add): 'Programmers' UNIQUE constraint failed: watch.user_id, watch.repo_id
2015/03/17 13:24:38 [teams.go:142 TeamsRepoAction()] [E] TeamsRepoAction: UNIQUE constraint failed: watch.user_id, watch.repo_id

'Programmers' is the name of the team to which I am trying to add the repository.

**Comment by Unknwon** [comment]
@Nickoladze thanks for the detail!

**Comment by Unknwon** [comment]
Hi @Nickoladze , I just tested on latest code of `master` with SQLite3 and didn't reproduce this problem.

Would you mind to test it again on latest code? Or you can wait binary until next release.

**Comment by Nickoladze** [comment]
I would prefer to wait for the next binary.

**Comment by Unknwon** [comment]
@Nickoladze  0.6 is released.

**Comment by Nickoladze** [comment]
#1100 is preventing me from testing

**Comment by Unknwon** [comment]
@Nickoladze any updates on this?

**Comment by Nickoladze** [comment]
Updated to latest binary, haven't hit any issues yet. Might be fixed, but I can't say for certain.

**Comment by Unknwon** [comment]
Thanks for confirmation! Let's wait until 0.6.2 release.

**Comment by Unknwon** [comment]
Closed as implemented. :octocat:
