### ISSUE TITLE
user auto-completion fails

### ISSUE THREAD

**Issue by dromer** [gogits/gogs#832]
When adding a user to a team, the auto-complete suggests usernames including the real-name.
Example: 'test (Test User)' instead of just 'test'.

**Comment by Unknwon** [comment]
Hi @dromer , I think this is been fixed in latest code and release `v0.5.11`.

Try F5 to reload JS files.

**Comment by deringer** [comment]
I came across this issue myself today @Unknwon - using version 0.5.11.0103 Beta.

The error presented was "Given user does not exist."

**Comment by dromer** [comment]
Nope, running v0.5.11 now I still get the same behaviour.

**Comment by hickscorp** [comment]
+1, i still get it as well with 0.5.11.0103 Beta.

**Comment by Unknwon** [comment]
Hi all, I've pushed fix to `dev` branch, and you're also free to test on https://try.gogs.io/ .

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:
