### ISSUE TITLE
Gogs v0.5.11 Linux binary broken

### ISSUE THREAD

**Issue by rhd** [gogits/gogs#833]
Hi, it seems that version 0.5.9.1213 is included in the linux_amd64.zip for the 0.5.11 release.

2015/01/05 12:43:05 [T] Custom path: /home/git/gogs/custom
2015/01/05 12:43:05 [T] Log path: /home/git/gogs/log
2015/01/05 12:43:05 [I] Gogs: Go Git Service 0.5.9.1213 Beta
2015/01/05 12:43:05 [I] Log Mode: File(Trace)
2015/01/05 12:43:05 [I] Redis Enabled
2015/01/05 12:43:05 [I] Memcache Enabled
2015/01/05 12:43:05 [I] Cache Service Enabled
2015/01/05 12:43:05 [I] Session Service Enabled
2015/01/05 12:43:05 [I] Mail Service Enabled
2015/01/05 12:43:05 [I] Register Mail Service Enabled
2015/01/05 12:43:05 [I] Notify Mail Service Enabled
2015/01/05 12:43:05 [I] SQLite3 Enabled
2015/01/05 12:43:05 [I] Run Mode: Production
2015/01/05 12:43:05 [web.go:66 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?
2015/01/05 12:43:05 [web.go:66 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?

**Comment by Unknwon** [comment]
Thanks your report!

I've re-uploaded linux binary, please help test again!

**Comment by rhd** [comment]
Working now... thanks!

**Comment by kisst** [comment]
Same? issue again with  0.6.1.0325 Beta
```
2015/06/23 21:22:06 [T] Custom path: /data/gogs
2015/06/23 21:22:06 [T] Log path: /gopath/src/github.com/gogits/gogs/log
2015/06/23 21:22:06 [I] Gogs: Go Git Service 0.6.1.0325 Beta
2015/06/23 21:22:06 [I] Log Mode: File(Trace)
2015/06/23 21:22:06 [I] Redis Enabled
2015/06/23 21:22:06 [I] Cache Service Enabled
2015/06/23 21:22:06 [I] Session Service Enabled
2015/06/23 21:22:07 [I] SQLite3 Enabled
2015/06/23 21:22:07 [I] Run Mode: Production
2015/06/23 21:22:07 [web.go:77 checkVersion()] [E] Binary and template file version does not match, did you forget to recompile?
```
