### ISSUE TITLE
git.fsck should have a option to set when it will run

### ISSUE THREAD

**Issue by xudaiqing** [gogits/gogs#834]
I haven't hit the problem yet. But i believe if it will cause problem and have to run it daily, then it should have a option to set when it will run. There may be other daily tasks in the future, so some thing like  a maintenance time and set cron tasks with interval longer than a day align to it should be a better option.

**Comment by Unknwon** [comment]
Hi @xudaiqing, thanks your feedback! 

With latest code and release `v0.5.11`, you can disable or config it via: https://github.com/gogits/gogs/blob/master/conf/app.ini#L270

**Comment by xudaiqing** [comment]
I see the update before i write the feedback. I think just config the interval doesn't get the point. The goal of config it is to make sure it will only run when we are not using it, probably at night or at weekend. I haven't try the new config yet, but i believe it will run according to when we start it. So if gogs start at 8:00am it will run at that time everyday. Make it run at 12:00pm everyday no matter when gogs starts makes a lot of sense.

**Comment by xudaiqing** [comment]
After revisit the origin issue #820 it seems that the main course is not the git-fsck. Also i haven't have issue with git-fsck. So it may not worth to do it now.

**Comment by Unknwon** [comment]
@xudaiqing I guess you need an option to config with cron-type job.

Make Gogs allows cron syntax to manage how git.fsck should run, would solve your problem(no matter you want to run as interval, or run in certain time point)。

What's your thought?

**Comment by xudaiqing** [comment]
It definitely solve the problem. But i haven't notice any performance issue on my server which have total repository of about 12GB. So i suggest to keep it in backlog unless you have found a real impact on performance.

**Comment by Unknwon** [comment]
I think `git fask` is already configurable? https://gogs.io/docs/advanced/configuration_cheat_sheet#cron---repository-health-check-(cron.repo_health_check)

**Comment by ajstadlin** [comment]
Link is broken (404)  https://gogs.io/docs/advanced/configuration_cheat_sheet#cron---repository-health-check-(cron.repo_health_check)

**Comment by ajstadlin** [comment]
Current Link in Master: [https://github.com/gogs/docs/blob/master/en-US/advanced/configuration_cheat_sheet.md#cron---repository-health-check-cronrepo_health_check](https://github.com/gogs/docs/blob/master/en-US/advanced/configuration_cheat_sheet.md#cron---repository-health-check-cronrepo_health_check)
