### ISSUE TITLE
Realtime webhooks

### ISSUE THREAD

**Issue by scritch007** [gogits/gogs#835]
Today, we have to wait for the "cron" in **gogs web** to run, before webhooks are notified.
It would be great to be able to have some realtime webhooks.

With the current behavior, **gogs serv** and **gogs update** are the one that knows about the commits. One of those two programms should notify the main **gogs web** process that a new commit has been done.

Either an http request from one of those two processes to the main **gogs web**, or a signal could be used.

**Comment by gittex** [comment]
Signals seem to be fragile and less portable to me.

Either an external queue (like in redis) or some HTTP request to gogs web.

**Comment by kageurufu** [comment]
This would be huge for me, its one of the things keeping me from being able to use this as my main GIT server. I currently have to manually trigger jobs on my CI server, and realtime webhooks would fix that 

:+1:

**Comment by vtolstov** [comment]
@Unknwon do you have any progress? I'm really nead realtime web hooks for my ci sever, because waiting 1 minute slowdown testing.
Maybe create additional process spawned and getting jobs via some rpc for webhooks notify?

**Comment by Unknwon** [comment]
@vtolstov Find a way to do it, will try it ASAP. :grinning:

**Comment by Unknwon** [comment]
Hi @vtolstov , I've push code to `develop` and updated https://try.gogs.io for realtime webhooks, please help test, thanks!

**Comment by vtolstov** [comment]
Thanks! Very good.

**Comment by Unknwon** [comment]
Closed as implemented. :octocat:
