### ISSUE TITLE
removing user from team: database table is locked

### ISSUE THREAD

**Issue by dromer** [gogits/gogs#836]
When I try to remove a user from a team I get:
{"err":"database table is locked","ok":false}

It is possible to remove the entire team.

This with v0.5.9 (will try v0.5.11 in a bit)

**Comment by dromer** [comment]
Same behaviour when removing user from organization.

Using 0.5.11.0103 Beta

**Comment by Unknwon** [comment]
Hi @dromer , I think this issue should no longer exist in the latest version of `master`, would you like to update and test again?

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
