### ISSUE TITLE
Connect multiple gogs instances

### ISSUE THREAD

**Issue by matmo** [gogits/gogs#837]
It would be great if multiple gogs instances could be connected to each other: 

If A and B both have their individual (as in self-hosted) gogs servers and they want to collaborate they have basically two options:
* A registers on B's server or vice versa, but will not see the project on her own gogs instance, and needs to keep track of multiple accounts to e.g. create issues
* A and B both keep seperate copies of the project in their respective gogs instances and add the other server as an additional remote/mirror. Both users see the project in their "main" account, but still can not interact (issues)

A more elegant solution would be if B hosts a project on her server (gogs.b.com) and A (A@gogs.a.com) could be added as a collaborator, without the need to re-register at gogs.b.com. An additional benefit of this would be, that A would have an overview over all her projects, without the need to log in different gogs instances, or keep multiple remotes in sync.

This is similar to "pods" in [Diaspora](https://wiki.diasporafoundation.org/Choosing_a_pod).

(This is just an idea, I am not sure whether it is feasible at all)

**Comment by gittex** [comment]
This would be nice for HA as well, but I see a few challenges with that. Synchornization, Replication, Latency ...

But it would be a nice feature :)

**Comment by Unknwon** [comment]
This feature is far beyond the `1.0.0` release... we are only focusing single instance right now, only would consider when single instance is stable.

Thanks your feedback, though! :smile:

**Comment by cirocosta** [comment]
Hey, since jan 2015, did gogs go to any direction in terms of multiple instances when it comes to high availability? Sorry if that's an easy answer; couldn't find something related to this.

Thanks!

**Comment by Unknwon** [comment]
@cirocosta hi, will not be considered until 1.0.

**Comment by anshulOpscale** [comment]
@unknwon hi, is this feature not added yet?

**Comment by unknwon** [comment]
@anshulOpscale Please see my comment: https://github.com/gogs/gogs/issues/837#issuecomment-289522232

**Comment by anshulOpscale** [comment]
@unknwon thanks for replying, is there any hope soon?

**Comment by unknwon** [comment]
No :)
