### ISSUE TITLE
Issue assignee doesn't show organisation members

### ISSUE THREAD

**Issue by deringer** [gogits/gogs#839]
Furthermore, as the user is part of the organisation that owns the repository, they cannot be added as a collaborator (no problem). This means, however, that issues can't be assigned to users within the organisation.

**Comment by da-kid** [comment]
Is the same as #747

**Comment by Unknwon** [comment]
Right now in `develop` branch you can assign yourself.

You can also test on https://try.gogs.io/

**Comment by Unknwon** [comment]
Closed as implemented. :star:
