### ISSUE TITLE
ldap filter group membership

### ISSUE THREAD

**Issue by Raboo** [gogits/gogs#840]
Hi,

I'm trying to allow only ldap users that are member of a certain group to be able to sign in..

I have this search filter
`(&(objectClass=user)(sAMAccountName=%s)(memberOf=CN=acl_git,OU=Groups,DC=domain,DC=com))`

But it still allows users that are not member of acl_git to sign in(create accounts).

Is my filter wrong or is gogs wrong? When using the tool ldapsearch my filter appears to be correct.

**Comment by Unknwon** [comment]
I think it has large possibilities that Gogs is wrong. Not sure if Gogs supports this, kind of related to https://github.com/gogits/gogs/issues/672 . cc @lunny

**Comment by flotho** [comment]
Hy @Raboo,

Take care of the fact that memberOf is a special function that must be enable in openldap : http://www.openldap.org/doc/admin24/overlays.html
Just try jour command with ldapsearch first and then try it in gogs

**Comment by msimpson** [comment]
The problem isn't the filter or the usage of "memberOf", it is an issue with the way Gogs is using LDAP to authenticate and users during auto registration.

See: https://github.com/gogits/gogs/issues/1257

**Comment by Unknwon** [comment]
Hi there, by mering PR #1476 into develop, this problem is claimed to be fixed, would you mind to test again and give us feedback? Thanks! :beer:

**Comment by Unknwon** [comment]
Close as implemented. :tada:
