### ISSUE TITLE
Users in team cannot clone repo

### ISSUE THREAD

**Issue by dromer** [gogits/gogs#841]
I have created a team with read-access to the organization.
However when a member of the team tries to clone a repo they get:

    You have no right to access this repository
    fatal: The remote end hung up unexpectedly
    
    Please make sure you have the correct access rights
    and the repository exists.

This with 0.5.11.0103 Beta

**Comment by deringer** [comment]
I have similar issues. I have an organisation, and within this organisation, three teams - the default owners, one for developers and one for reporters.

The owners has no permission, whenever I create a new organisation repo (using the api), any users in the owners repo can access the new repo, it appears in the dashboard under 'collaborative repositories' etc.

I have to manually add the repository to the developers and reporters teams, however, this does not update the collaborative repositories in the dashboard, nor visible from the organisation page. The user can visit the repository page directly, though and are then able to work with the repository ok. If I add the user to the owners repository, it then appears on the dashboard and organisation page.

Also of note, if I then remove the user from the owners team, they can still see the repository and there is still a record in the access table.

It's a tedious extra step, given that I would expect the teams to inherit all repositories from the organisation they belong to and for the collaborative repositories to be updated.

Seems there's also some concern around security, given that removing a user from a team doesn't remove their access to the organisation's repositories.

Ideally, when creating an organisation repository, it would be made available to all teams within that organisation, with the appropriate (read / write / admin) level of access.

**Comment by Unknwon** [comment]
Hi @dromer @deringer , I think this issue should no longer exist(we redesigned the DB table) in the latest version of master, would you like to update and test again?

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
