### ISSUE TITLE
Ubuntu 13.10 get from source error

### ISSUE THREAD

**Issue by bug** [gogits/gogs#846]
On our internal Ubuntu 13.10 server trying to get gogs from sources leads to an error:

git:~# go get -u -tags "sqlite redis memcache" github.com/gogits/gogs gogs
package github.com/gogits/gogs
        imports github.com/gogits/gogs
        imports github.com/gogits/gogs: no Go source files in /local/gopath/src/github.com/gogits/gogs

git:~# go version
go version go1.1.2 linux/amd64

Any idea?

**Comment by bug** [comment]
Sorry for the noise, I just realize the version of go is 1.1.2...

**Comment by Unknwon** [comment]
@bug I know it's late, but glad you solved it!
