### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by DraugDev** [gogits/gogs#850]
Where to find all translations, want to translate it into russian.

**Comment by loicsaintroch** [comment]
The community uses Crowdin to translate Gogs: https://crowdin.com/project/gogs/invite

**Comment by DraugDev** [comment]
Thank you!

**Comment by Unknwon** [comment]
@loicsaintroch thanks for your answer!

@DraugDev here are some help info: http://gogs.io/docs/features/i18n.html

**Comment by alexandre-mbm** [comment]
How to translate the website?

**Comment by dentmaged** [comment]
@alexandre-mbm The documentation is at gogits/docs

**Comment by alexandre-mbm** [comment]
![gogs-website-translate](https://cloud.githubusercontent.com/assets/957501/7434799/322c269a-f014-11e4-97ff-68ed307720f7.png)

**Comment by dentmaged** [comment]
@alexandre-mbm I see! Sorry! That is not translatable at the moment, as you can see [here](https://github.com/gogits/gogs/blob/6f81c05dde2def51c30a97f65f901ae45c971e05/templates/home.tmpl#L98)

**Comment by Unknwon** [comment]
Hi @alexandre-mbm , for the part you circled, you have to translate in `home.tmpl`  where @dentmaged pointed. :dizzy:

**Comment by alexandre-mbm** [comment]
There will be i18n for the `home.tmpl`?

**Comment by Unknwon** [comment]
Here is the example of how to add Chinese version: https://github.com/gogits/gogs/blob/6f81c05dde2def51c30a97f65f901ae45c971e05/templates/home.tmpl#L54-L90 

You can copy and paste and translate to your language :satisfied:
