### ISSUE TITLE
Edit Account does not take into consideration password rules

### ISSUE THREAD

**Issue by guycalledseven** [gogits/gogs#851]
Admin panel / Edit Account does not take into consideration password rules. So eg. it's possible to update user with password less than 6 characters long, which rules on Sign In screen will deny with error message: "Password must contain at least 6 characters.".

**Comment by Unknwon** [comment]
Hi @guycalledseven , I've pushed code fix on `master` branch.

You will have to `go get -u github.com/macaron-contrib/binding` to update dependency as well.

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
