### ISSUE TITLE
gogs as service on ubuntu via upstart

### ISSUE THREAD

**Issue by guycalledseven** [gogits/gogs#852]
Hi,
I was trying to make gogs play nice with upstart on ubuntu 14.04 LTS and got stuck with KILL SIGNAL. I understand gogs doesn't have zero downtime functionality (grecafull shutdown) implemented so maybe I am jumping too much ahead here. I didn't find it anywhere on road map as well, so your thoughts would be appreciated.
I am running gogs as separate user and use setgid and setuid appropriately in upstart.
I tried issuing:
kill signal INT
kill signal SIGINT
kill signal SIGTERM
kill signal SIGHUP
...and they all kill gogs but leave following error in /var/syslog:
Jan 11 12:56:58 ubuntu kernel: [34278.257592] init: go-gogs main process (16561) terminated with status 2

I see no errors in gogs logs beside syslog entry, and I am not sure if this is syslog complaining about unhanded exit or something else. For eg. when I try to use  kill signal with SIGQUIT i get go error dump (nothing in syslog), what is expected from SIGQUIT (Ctrl+\).

**Comment by loxK** [comment]
did u install from https://packager.io/gh/pkgr/gogs ? If so it uses upstart ...

**Comment by guycalledseven** [comment]
@loxK no i did not, I build it, but have you read my issue closely? do you have errors in /var/syslog/ when you stop it under ubuntu 14.04lts? 

i have no issue with upstart script, but the gogs side of handling shutdown which is not clean. I highly doubt that gogs from packager.io differs from current github so I am guessing it has the same issue.

**Comment by graetzer** [comment]
I added a `git` user and start gogs with upstart as this user. I had no problems so far.
I used the following upstart script:
```
author "simon"
description "gogs upstart script"

setuid git
setgid git 

start on (local-filesystems and net-device-up)
stop on shutdown
 
console output
 
env USER=git
respawn 
respawn limit 10 5

script
   set -x
   HOME=/home/$USER
   PATH=/sbin:/usr/sbin:/bin:/usr/bin
   export USER HOME PATH
   exec /opt/gogs/scripts/start.sh
end script```

**Comment by Unknwon** [comment]
@graetzer thanks! 

I've tried upstart myself, but finally choose supervisor. :flushed:

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
