### ISSUE TITLE
Development documentation for plugins

### ISSUE THREAD

**Issue by xaionaro** [gogits/gogs#854]
Hello.

Is there any documentation or at least "Hello world" example of how to write plugins for the Gogs?

**Comment by Unknwon** [comment]
Hi, thanks for asking!

I'm not sure what do you mean by `plugins`?

**Comment by xaionaro** [comment]
I need to add functionality to Gogs without modifing it source code (to do not add work of merging it with upstream code). For example ITS "Redmine" has support of plugins to do that. I'm writting new plugins and modifing Redmine behaviour, functionality and interface without modifing it source code.

Sorry for my English.

**Comment by Unknwon** [comment]
> Sorry for my English.

Don't worry, I'm not native speaker, too. :smile: 

For plugins, I think Go program is statically linked so if you want to modify/add/remove functionality, you have to change the source code. It's not impossible, but it's not a easy thing and would have many limitations.

**Comment by xaionaro** [comment]
> For plugins, I think Go program is statically linked so if you want to modify/add/remove functionality, you have to change the source code. It's not impossible, but it's not a easy thing and would have many limitations.

There's no support of dlload() or something like that? I don't know golang, yet, but I'm pretty sure that the problem is solvable :).

**Comment by xaionaro** [comment]
But for now I just will try to modify the source code of Gogs itself to adapt it for our purposes.

**Comment by Unknwon** [comment]
> But for now I just will try to modify the source code of Gogs itself to adapt it for our purposes.

I guess it's the only way right now...

**Comment by Unknwon** [comment]
BTW, there could be a way that developers need to add source directory to the project with special needs but don't have to bother with upstream.

Gogs could defines protocols/interfaces for needed inject parts, and your "plugin" code only need to implement parts you want to enhance. But obviously, it's not going to be a easy thing todo.

**Comment by Unknwon** [comment]
What is the status of this issue?

**Comment by oouyang** [comment]
Base on this(https://www.goinggo.net/2013/08/using-c-dynamic-libraries-in-go-programs.html), it should be possible.
