### ISSUE TITLE
git clone over HTTP not working with 0.5.11 binary

### ISSUE THREAD

**Issue by chris007de** [gogits/gogs#855]
Hi,
I set up a gogs environment, and it seems to work fine, except that it is not possible for me to clone repositories from a remote system over HTTP.

When I try to clone, it fails with:

    [x@localhost ~]$ git clone http://192.168.1.2:3000/y/mytestrepo.git
    Initialized empty Git repository in /home/x/mytestrepo/.git/
    error: Couldn't get http://192.168.1.2:3000/y/mytestrepo.git/HEAD for HEAD
    The requested URL returned error: 404
    got 06b7777d3f92f04d05e79e48b5dbc245e8898de3
    walk 06b7777d3f92f04d05e79e48b5dbc245e8898de3
    got 6d88c8119bb9f76a08f1169321a30ea9b87b0c75
    got e7a909e4c625940a91980fc5a215d236f59cd68a
    got d65264474abda67c9ee04a435cbe10150a49cb8d
    warning: remote HEAD refers to nonexistent ref, unable to checkout.

Anyway, the folder /mytestrepo gets created and contains a .git folder, which tells me there is a origin/master branch.
After a git checkout origin/master && git checkout -b master (like proposed in https://stackoverflow.com/questions/11893678/warning-remote-head-refers-to-nonexistent-ref-unable-to-checkout) everything looks fine, but git push to origin fails with:

    [x@localhost mytestrepo]$ git push
    error: Cannot access URL http://y:pw@192.168.1.2:3000/y/mytestrepo.git/,    return code 22
    error: failed to push some refs to ' http://y:pw@192.168.1.2:3000/y/mytestrepo.git'

I am using the v0.5.11 binary from http://gogs.io/docs/installation/install_from_binary.html on an Ubuntu 14.04 system.

**Comment by Unknwon** [comment]
Thanks your report!

Sorry for late :scream::scream:

Looks like a problem caused by nested git repositories?

**Comment by chris007de** [comment]
No, there are not nested repos involved :-/

**Comment by cybernet** [comment]
where is the fix ?

**Comment by cybernet** [comment]
if you want to reproduce
follow this tutorial
https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04

**Comment by Unknwon** [comment]
Hi @cybernet , I wrote that article and do copy&paste on fresh Ubuntu instance cannot reproduce the issue :flushed:

**Comment by Unknwon** [comment]
However, someone do mention about permission issue and solution here: https://github.com/gogits/gogs/issues/1160#issuecomment-87074899

**Comment by Unknwon** [comment]
What is the status of this issue?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
