### ISSUE TITLE
error: RPC failed; result=7, HTTP code = 0

### ISSUE THREAD

**Issue by voilet** [gogits/gogs#856]
### gogs push tags error
* git tag -m "merge info" -a "xxxxxx"
* git push --tags
<pre>
Counting objects: 1, done.
Writing objects: 100% (1/1), 156 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
</pre>

* git cat-file tag xxx
<pre>
object 4f41efc0643b69cd02ec5a58de66c146e5e4b94f
type commit
tag 201501151201
tagger voilet <voilet@xxx.tv> 1421220903 +0800
merge info
</pre>

**Comment by fuhu** [comment]
Use git:// or git+ssh://, not https

**Comment by Unknwon** [comment]
Hi... Can you reproduce this error with latest Gogs?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.

**Comment by voghDev** [comment]
Curious. I was having this issue in a remote with `https` and fixed it as follows:

   git remote set-url origin git+ssh://my_remote_url
   git remote -v

Verified that the remote has changed. Then back to https

    git remote set-url origin https://my_remote_url

Now it works. My git version is `1.9.1`

Hope it helps somebody :-)
