### ISSUE TITLE
Add organisation as collaborator to repository does not give access to org's team members

### ISSUE THREAD

**Issue by phsmit** [gogits/gogs#857]
On a personal, private repository I added organization 'org1' as a collaborator. 'usera' is member of 'org1'.

After this, 'usera' did not have access to my repository.

What is expected:
- Organization can not be collaborators, or
- Adding a organization as collaborator should give access to all organization members

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/13198922/f9886066-d7e3-11e5-9700-1648d069c025.png)

You can test on `develop` branch or https://try.gogs.io.
