### ISSUE TITLE
团队添加库问题

### ISSUE THREAD

**Issue by CaiCQ** [gogits/gogs#859]
1、新建一个组织
2、新建一个库
3、新建一个团队
4、在团队中添加一名成员
5、添加成员后再添加库，提示：{"err":"Team does not exist","ok":false}
6、删除所以成员，在添加库：OK
上述问题在使用 sqlite3 情况下发生

**Comment by Unknwon** [comment]
What is your Gogs version?

**Comment by CaiCQ** [comment]
最新的5.11版本，该问题之前的版本一直存在

**Comment by phsmit** [comment]
This seems to be the same issue as #739

**Comment by CaiCQ** [comment]
是的，是同一个问题，都是我提出的，之前没解决不了了之，现在发现有规律，只要我把团队成员全部删除再添加库就可以成功，有诚意就无法添加，所以上来再看看是否能解决

**Comment by Unknwon** [comment]
Please continue following on https://github.com/gogits/gogs/issues/739 , that one is put into TODO list, and thanks your patient!
