### ISSUE TITLE
难道项目烂尾了，这么久没动静了！

### ISSUE THREAD

**Issue by CaiCQ** [gogits/gogs#862]
难道项目烂尾了，这么久没动静了！

**Comment by lunny** [comment]
没有。

**Comment by CaiCQ** [comment]
那是什么情况了，这么久没动静，也没看到更新东西，吓着我了

**Comment by lunny** [comment]
没有情况，今天还创建了chardet工程。

**Comment by fuxiaohei** [comment]
过年了，大家都忙别的事情

**Comment by Unknwon** [comment]
You only focus on the surface of things, and ignored the underlying working.

Don't worry, God will always be with you and us.

Hah, :smile: I'm justing joking!
