### ISSUE TITLE
Cannot add user with name as collaborator

### ISSUE THREAD

**Issue by marcuspoehls** [gogits/gogs#867]
- **Bug Description**: an error occurs when trying to add a collaborator to a repository who has a name defined
- **Gogs Version**: 0.5.11.0103 Beta (german)
- **Git Version**: 1.9.1
- **System Type**: Ubuntu 14.04
- **Error Log**:
- **Other information**: Please the screenshots below to get an idea of the problem. Within the screen with the error message the user has a name defined.

![bildschirmfoto 2015-01-20 um 10 31 45](https://cloud.githubusercontent.com/assets/837771/5814873/54240624-a090-11e4-806f-5681b1f4ea16.png)

![bildschirmfoto 2015-01-20 um 10 32 03](https://cloud.githubusercontent.com/assets/837771/5814875/5897d1d6-a090-11e4-87ae-e1650d683cb5.png)

**Comment by uolter** [comment]
One possible fix:
1) Open the file public/ng/js/gogs.js
2) Go to the line 511 and change this code: 
      $('#repo-collaborator').val($(this).text());

**Comment by Unknwon** [comment]
Thanks your report! Working on it.

**Comment by Unknwon** [comment]
@uolter thanks your info!

**Comment by Unknwon** [comment]
This is been fixed by commit: https://github.com/gogits/gogs/commit/7140f50637219cbaffcf21d5082cf6b5c9f1994c#diff-f7a171e6725597de87d4092607c5765dR588 , you're also free to try on https://try.gogs.io/

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:
