### ISSUE TITLE
Failed to update mirror repository

### ISSUE THREAD

**Issue by basilfx** [gogits/gogs#869]
If I create an organization, add a mirror, then change the organization's name, the update mirror task is not updated, resulting in errors such as these:

```
359	Repository	Fail to update mirror repository(/opt/git/external/xxx): chdir /opt/git/external/xxx: no such file or directory	2015-01-21 13:59:57 +0100 CET
```

If I look into the mirror table in the database, it seems that it isn't updated.

- **Bug Description**: Failed to update mirror repository
- **Gogs Version**: 0.5.11.0103 Beta (latest binary release)
- **Git Version**: 1.9.1
- **System Type**: Ubuntu 14.10 x64
- **Error Log**: See title
- **Other information**: Using MySQL as backend

**Comment by basilfx** [comment]
I can confirm that changing the mirror in the database resolved the issue. The notices did not appear anymore, even without restarting Gogs.

**Comment by Unknwon** [comment]
Sorry for late!

This should be fixed by `master` code, to keep simple, please follow on https://github.com/gogits/gogs/issues/1120 .
