### ISSUE TITLE
Allow mysql socket connection instead of tcp

### ISSUE THREAD

**Issue by themidnightfox** [gogits/gogs#872]
Currently it is not possible to configure a mysql-connection with a unix socket. Is there a reason for this?

**Comment by EtienneBruines** [comment]
Looking at the documentation of the MySQL Driver (https://github.com/go-sql-driver/mysql#examples) - it could be done.

**Comment by Unknwon** [comment]
Updates on https://github.com/gogits/gogs/pull/1045

**Comment by Unknwon** [comment]
cc @themidnightfox @EtienneBruines

**Comment by EtienneBruines** [comment]
This should do the trick. Thanks @tomcatzh !

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
