### ISSUE TITLE
https://try.gogs.io/ not working

### ISSUE THREAD

**Issue by superalex** [gogits/gogs#875]
The error:

502 Bad Gateway: nginx/1.6.2 (Ubuntu)

**Comment by Unknwon** [comment]
Thanks for report, but it's duplicated to https://github.com/gogits/gogs/issues/874 , and I've commented the reason.

Have a nice day!

**Comment by superalex** [comment]
Ok, thanks! :+1:

**Comment by Unknwon** [comment]
@superalex no problem!
