### ISSUE TITLE
Update hooks is missing for forked repository

### ISSUE THREAD

**Issue by Dumbris** [gogits/gogs#876]
I have installed 0.5.11 version. And encountered with bug in update logic on forked repos. The webhooks does not fire after git push to forked repo. This is broke drone CI integration in my case. Webhooks in not forker repo works ok.
Also activity stream (explore) does not show "Updated" label correctly. 

My environment:
host Centos 6.6
go1.4.1 linux/amd64
mysql version 5.5.40 with innodb.
update.log is empty

**Comment by Unknwon** [comment]
Thanks for your report and patient, it's been backlog here: https://trello.com/c/0Csbq8BX/391-update-hooks-is-missing-for-forked-repository :eyes:

**Comment by Unknwon** [comment]
Hi @Dumbris , I've pushed fix on `master`, you can also test on https://try.gogs.io !

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
