### ISSUE TITLE
REST endpoint for keys

### ISSUE THREAD

**Issue by bradrydzewski** [gogits/gogs#878]
Would it be possible to expose endpoints for managing SSH keys at the repository level? The equivalent endpoints on GitHub are the following:
https://developer.github.com/v3/repos/keys/

The primary use case is for continuous integration (specifically [Drone](https://github.com/drone/drone)). In order for the continuous integration server to clone private repositories we (ideally) would upload a key.

Let me know your thoughts and if there is anything I can do to help

**Comment by Dumbris** [comment]
I have added REST API endpoints for SSH keys management on gogs. Also I have updated drone/plugin/remote/gogs/gogs.go
I am going to prepare pull requests to drone and gogs after testing on next week.

**Comment by Unknwon** [comment]
It's related/relied on https://github.com/gogits/gogs/issues/334 , then we can have API endpoints for this issue. :stuck_out_tongue_closed_eyes:

**Comment by simonoff** [comment]
@Dumbris any progress?

**Comment by vtolstov** [comment]
ping...

**Comment by Unknwon** [comment]
Will be added in 0.7

**Comment by Unknwon** [comment]
Key end points are added, and document is here: https://github.com/gogits/go-gogs-client/wiki/Repositories---Deploy-Keys

**Comment by aviddiviner** [comment]
That link should be https://github.com/gogs/go-gogs-client/wiki/Repositories-Deploy-Keys
