### ISSUE TITLE
support cznic/ql backend

### ISSUE THREAD

**Issue by kortschak** [gogits/gogs#880]
Repeat of #46 - closed without resolution.

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

But it's really depends on how far `cznic/ql` goes and when would `xorm` supports it.

cc @lunny

**Comment by kortschak** [comment]
It looks to me from what I can see that the issue raised against ql were addressed. It would probably be helpful if the blocking issues that are outstanding actually be listed.

**Comment by Unknwon** [comment]
I created a label `standby` so that people know we're waiting for third-party providers.

**Comment by Unknwon** [comment]
Just talked to the author of xorm(@lunny), and `ql` is almost ready for testing with Gogs, I'm not sure how far it would go(maybe stuck on some wried points), but will start working on it!

just a note of example use ql and xorm: https://github.com/go-xorm/admin

**Comment by lunny** [comment]
Sorry, I have renamed https://github.com/go-xorm/admin to https://github.com/go-xorm/dbweb. And use github.com/lunny/nodb instead ql to store meta data.

**Comment by Unknwon** [comment]
> Sorry, I have renamed https://github.com/go-xorm/admin to https://github.com/go-xorm/dbweb. And use http://github.com/lunny/nodb instead http://github.com/cznic/ql to store meta data.

Such a bad guy!

**Comment by Unknwon** [comment]
This will not be supported as another better option is coming up. https://github.com/pingcap/tidb

**Comment by kortschak** [comment]
Not good.

That's much younger, less well tested and I can see whole sections of code from other people's work used without attribution (@cznic, take a look at the btree package in kv).

**Comment by tboerger** [comment]
Without attribution? They explecitly say thank you to @cznic and reference to him Oo

And it sounds much better from my point of view, especially the roadmap...

**Comment by kortschak** [comment]
I'm sorry, but a trite sentence doesn't make up for removing the copyright notice on the file. How many other files have been similarly taken.

Roadmap is not implementation. I trust cznic's code because he has an excellent track record of quallity - ql is extensively tested, looking at tidb so far, I don't see that. Further, for a single machine install - why I filed the issue - a distributed db is overkill.

**Comment by Unknwon** [comment]
For me, waiting for ql or tidb is same. Both of them are not usable.

**Comment by kortschak** [comment]
If they are the same, don't close the issue.

**Comment by Unknwon** [comment]
But we've waited too long for ql and no sign I can see xorm is going to support it fully. :sob:

**Comment by kortschak** [comment]
>But we've waited too long for ql and no sign I can see xorm is going to support it fully.

OK, that's a different issue. xorm is the problem.

Question for you, what is a the lowest golang/go issue number? How long has that been waiting?

**Comment by Unknwon** [comment]
> OK, that's a different issue. xorm is the problem.

It is same in the Gogs's point of view, if xorm is not going to support it, Gogs is not going to, even if ql has all features that Gogs needs.

> Question for you, what is a the lowest golang/go issue number? How long has that been waiting?

I don't know and don't need to know. There is no necessity of how long to stop waiting between two projects?

**Comment by kortschak** [comment]
Issues are your memory. If you intentionally forget things because they haven't been done in time, they won't be done.

**Comment by Unknwon** [comment]
> If you intentionally forget things because they haven't been done in time, they won't be done.

Yes, but decision has to be made.

**Comment by kortschak** [comment]
Yup, I've made a decision.

**Comment by vtolstov** [comment]
I'm think sometimes ago for writing cznic/ql support. I don't like xorm and
prefer writing interface for getting and setting needed things. But I'm
switch to gitea, and prepare pr to gitea...
07 сент. 2015 г. 0:04 пользователь "Dan Kortschak" <notifications@github.com>
написал:

**Comment by cznic** [comment]
@kortschak 

> (@cznic, take a look at the btree package in kv).

Thanks: https://github.com/pingcap/tidb/issues/45
