### ISSUE TITLE
Unable to select different owner in dropdown due to margin

### ISSUE THREAD

**Issue by JoeHazzers** [gogits/gogs#882]
- **Gogs Version**: 0.5.11.0103 Beta 
- **System Type**:
  - Server: Arch Linux
  - Browser: Firefox 35.0.1 on Arch Linux

Due to a small gap between the dropdown items and the dropdown selector itself on the "New Migration" page, it's not possible to move the mouse down and select another owner.

The effect can be seen here in my browser:

![2015-01-30-160821_1892x1036_scrot](https://cloud.githubusercontent.com/assets/214649/5978846/cf73be34-a89a-11e4-8ec6-e4c4ef78bba7.png)

I found that setting a 2px padding on the `drop` fixed the issue, but I'm not sure if that's the proper way to fix it.

**Comment by Unknwon** [comment]
Thanks your report! I think you're right, it's not possible to keep dropdown showing if mouse doesn't move fast enough.

**Comment by Unknwon** [comment]
This has been fixed with new UI.
