### ISSUE TITLE
Able to disable SSH feature

### ISSUE THREAD

**Issue by NewbieOrange** [gogits/gogs#883]
应该加入关闭SSH的设定喔~ 在关闭的时候 不会显示和SSH有关的内容 免得在没开SSH的服务器误导用户

**Comment by Unknwon** [comment]
You're right, marked!

**Comment by Unknwon** [comment]
Hi @NewbieOrange , I've pushed code to `dev` branch.

You are now able to disable SSH by config option `[server] DISABLE_SSH = true`

**Comment by NewbieOrange** [comment]
Seems good, but I am using Windows server... waiting for someone to test it :)

**Comment by Unknwon** [comment]
@NewbieOrange , I would say Windows is the type of system need this feature. 

You can disable it and web UI should no longer show the SSH-related information.

**Comment by NewbieOrange** [comment]
I mean I can't run without a bin file..

**Comment by Unknwon** [comment]
@NewbieOrange I see, new mirror release should be very soon!

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:

**Comment by NewbieOrange** [comment]
最好能让HTTP的地址栏更长一点 或者放在中间 这样看起来正常一点

**Comment by Unknwon** [comment]
We want to, but got UI issues, and need to compatible with low resolution screens.
