### ISSUE TITLE
Add option for hiding "Sign Up" when register is disabled

### ISSUE THREAD

**Issue by NewbieOrange** [gogits/gogs#884]

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

But don't two buttons are showing at the same time? If changed "sign up" to "sign in", will we have two sign in buttons?

**Comment by NewbieOrange** [comment]
Well, if there will be two buttons, remove one. Like there will be only "sign in" in the top right corner.

**Comment by Unknwon** [comment]
It's easy to remove one, but would that confuse users without a notice page like current approve?

**Comment by NewbieOrange** [comment]
No I think, maybe add a option?

**Comment by Unknwon** [comment]
Cool, no problem.

**Comment by wanghm** [comment]
We need this feature, too.

**Comment by JoeHazzers** [comment]
I thought it seemed strange to have the "Sign Up" button around when registration is disabled, too

+1

**Comment by Unknwon** [comment]
Hi all, I've pushed a fix related to https://github.com/gogits/gogs/pull/908 to `dev` branch, to hide `Sign Up` button by default when registration is disable.

**Comment by wanghm** [comment]
Is it possible to hide "Need an account? Sign up now."?

**Comment by Unknwon** [comment]
@wanghm good catch! Fixed pushed to `dev`.

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:

**Comment by NewbieOrange** [comment]
Everything works fine, resolved. :smile:

**Comment by Unknwon** [comment]
@NewbieOrange awesome! :beer:
