### ISSUE TITLE
Autocomplete in adding Team Member

### ISSUE THREAD

**Issue by EtienneBruines** [gogits/gogs#886]
So, I'm at the "Team" page for an organization, wanting to add a team member. (I'm using the `0.5.11.0103 Beta` version, but I don't believe this has been fixed yet in newer versions)

# Reproduction
* I start typing: `etie...` - ah great, auto-complete! `*click*`.
* The box now contains `etiennebruines (Etienne Bruines)`. 
* I click `*Add Team Member*`
* Error message: `Given user does not exist.`

# Possible fixes:
* autocomplete shouldn't include the Name in the input form field
* server-side should filter the information out, before checking if the user exists.

**Comment by Unknwon** [comment]
Thanks your feedback!

But I'm closing it for its duplication of https://github.com/gogits/gogs/issues/832 . Please follow on that on, thanks!
