### ISSUE TITLE
When SSL terminates at proxy (apache, nginx) Gogs serves pages as 404

### ISSUE THREAD

**Issue by andmarios** [gogits/gogs#887]
If one uses apache or nginx for SSL termination, then Gogs returns the correct page but with a status of `HTTP/1.1 404 Not Found`.

For example although the page below obviously works, it is served as a 404 page:
```
$ curl -I https://try.gogs.io
HTTP/1.1 404 Not Found
Server: nginx/1.6.2 (Ubuntu)
Date: Sun, 01 Feb 2015 16:01:28 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
...
```

I think that due to this, `go get` can't reach public repos behind apache/nginx terminated SSL:
```
$ go get try.gogs.io/test/Test
package try.gogs.io/test/Test: unrecognized import path "try.gogs.io/test/Test"
```

On my Gogs' logs I see:
```
$ ./gogs web
2015/02/01 15:54:06 [T] Custom path: /home/git/gogs/custom
2015/02/01 15:54:06 [T] Log path: /home/git/gogs/log
2015/02/01 15:54:06 [I] Gogs 0.5.11.0103 Beta
2015/02/01 15:54:06 [I] Log Mode: Console(Trace)
2015/02/01 15:54:06 [I] Cache Service Enabled
2015/02/01 15:54:06 [I] Session Service Enabled
2015/02/01 15:54:06 [I] Mail Service Enabled
2015/02/01 15:54:06 [I] Register Mail Service Enabled
2015/02/01 15:54:06 [I] Notify Mail Service Enabled
2015/02/01 15:54:06 [I] SQLite3 Enabled
2015/02/01 15:54:06 [I] Run Mode: Production
2015/02/01 15:54:06 [I] Listen: http://127.0.0.1:3000
[Macaron] Started GET / for 79.131.60.133, 127.0.0.1
[Macaron] Completed / 200 OK in 3.148545ms
[Macaron] Started HEAD / for 79.131.60.133
[Macaron] Completed / 404 Not Found in 2.224472ms
```

**Comment by Unknwon** [comment]
Thanks your report!

> I think that due to this, go get can't reach public repos behind apache/nginx terminated SSL:

`go get meta` should be enabled manually in repository settings page, so I guess you didn't do that as I lookup in the page source code of try.gogs.io/test/Test.

> On my Gogs' logs I see:

Based on your log, GET returns 200 because it is been registered as route.

HEAD didn't, which means HEAD is not allowed in `/` path, so it returns 404, as my understanding, should never exists.

**Comment by andmarios** [comment]
Ah, thank you! After some more tries I made it work, I'm not sure what I did wrong in the past times. Maybe some caching layer in my stack prevented my repos from getting immediately “go getable” after changing the setting.

Sorry for the false alarm. I love gogs!

**Comment by Unknwon** [comment]
@andmarios no problem, thank you!
