### ISSUE TITLE
Support for external issue tracker

### ISSUE THREAD

**Issue by fzerorubigd** [gogits/gogs#890]
The problem is, we use gogs as git repository management, and redmine as issue tracker. every thing works fine, except the link in commit messages (something like `fixes #ISSUEID`) is always go to the gogs issue tracker. 
Its a good option to have, an issue tracker pattern as a part of repository setting (like `http://redmine.example.com//issues/:issue_id` ) and if its empty, then simply use the gogs internal issue tracker

**Comment by rojaro** [comment]
It would be nice if one could configure multiple custom ticket systems via regex match i.e.

* something like `#\w+-\d` to match Jira tickets and point this to https://jira.domain.tld/browse/:ticket_id
* something like `#\d` to Gogs built in or alternative as proposed by @fzerorubigd .

**Comment by Unknwon** [comment]
@fzerorubigd @rojaro thanks your feedback!

Looks like a great feature!

**Comment by fzerorubigd** [comment]
@Unknwon I think the @rojaro 's idea is better, and I can help for implement this. any idea?

**Comment by Unknwon** [comment]
@fzerorubigd right. 

Sure it's great if you can help, but we need to discuss little more about this.

How do we store those regular expressions? Database(require web UI) or in some config file(need another file)?

**Comment by rojaro** [comment]
It would be nice if the settings could be edited through a webinterface, but i think these settings should be configurable through the application configuration.

**Comment by fzerorubigd** [comment]
This could be inside configuration, and can overwrite it in repository
setting.

On Mon, Feb 2, 2015 at 5:07 PM, rojaro <notifications@github.com> wrote:

> It would be nice if the settings could be edited through a webinterface,
> but i think these settings should be configurable through the application
> configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gogits/gogs/issues/890#issuecomment-72458664>.
>



-- 
-----------------------------
http://fzero.rubi.gd

**Comment by Unknwon** [comment]
I think it should be repository level settings? So may need a web Ui to config it, and save info in database.

**Comment by rojaro** [comment]
Keep it simple.

A basic application configuration based implementation without webinterface and database storage is needed anyways. So before thinking about webinterface and database storage, i'd be happy with a simple application configuration based implementation.

**Comment by fzerorubigd** [comment]
Personally I use gogs for internal usage and there is only one issue
tracker for all project, but what if someone need this for multiple issue
tracker for multiple project?

**Comment by Unknwon** [comment]
I guess it's just a very simple UI with a list of regular expressions and corresponding settings(basically external URL for another issue tracker)

**Comment by jhit** [comment]
@Unknwon  I strongly agree this to be a repository setting. We use activeCollab and activeCollab has a dedicated issue counter per project. We need the the project name and issue number to be part of the URL to have working external URLs. A setting on application level would make it very hard to configure this for activeCollab.

**Comment by Unknwon** [comment]
@jhit yes, that's obvious :wink:

**Comment by Unknwon** [comment]
OK, now possible on `develop`, test here: https://try.gogs.io/gogs/gogs , if click any issue links `#xx`, it leads you to GitHub issues of Gogs project.

**Comment by MoBe80** [comment]
@Unknwon thanks for the implementation, but in our case it runs too short. In our issue tracker (JIRA) we've got several project for different teams (Quality, Support, Development). These project have different "issue id formats" like QM-55, SUP-879 or DEV-357 they should redirect to _https://url/browse/DEV-357_. So it would be great to take up the idea of @rojaro again and if necessary to support a different formats and not only #nnn.

**Comment by Unknwon** [comment]
@MoBe80 thanks for the info!

I suggest you open another issue for this feature request.

**Comment by cFINNY** [comment]
+! Would love to see this as well, a simple regex matching pattern type of system to link (for example) JIRA Issues from the commit messages

**Comment by Unknwon** [comment]
@cFINNY thank your feedback.

But this is an closed issue, please open another issue for the regexp match specificity.
