### ISSUE TITLE
Better readme detection

### ISSUE THREAD

**Issue by jcracknell** [gogits/gogs#894]
https://github.com/gogits/gogs/blob/master/modules/base/markdown.go#L66

I made a test case in a project called `ReadmeTest.php` which is getting displayed as a readme file instead of code. This should probably use a regex: `^readme(\.|$)`.

**Comment by Unknwon** [comment]
Thanks your report!

But it's duplicated to https://github.com/gogits/gogs/issues/877 , so I'm closing this and please follow on that one.
