### ISSUE TITLE
Document SSH 'gogs serv' functionality

### ISSUE THREAD

**Issue by pnegahdar** [gogits/gogs#902]
I can't find any documentation for what command to use as part of the `gogs serv` in the `.ssh`.

**Comment by Unknwon** [comment]
It's not meant to call `gogs serv` by users, do you just want to know what it does?

**Comment by pnegahdar** [comment]
I assumed it was the SSH git receive command hook?

**Comment by pnegahdar** [comment]
I assumed it was the SSH git receive command hook required for ssh pushes?

**Comment by Unknwon** [comment]
@pnegahdar  you got it.

**Comment by pnegahdar** [comment]
@Unknwon don't you think that should be in the install docs? Bonus link: https://github.com/progrium/gitreceive

**Comment by Unknwon** [comment]
Yeah, need a line to say do not run it...

**Comment by Unknwon** [comment]
Here we go, I added in FAQ: http://gogs.io/docs/intro/faqs.html#what-is-gogs-serv-command-for%3F

Will move to more appropriate position when we have a single page just for introducing Gogs commands.

**Comment by phsmit** [comment]
Ideally, cli would have an option to create "hidden" commands. Commands that are not shown in the help.

**Comment by Unknwon** [comment]
@phsmit we need to start hacking that package then :panda_face:

**Comment by phsmit** [comment]
@Unknwon Yes, exactly what I did :) https://github.com/codegangsta/cli/pull/180

**Comment by Unknwon** [comment]
@phsmit cool!

**Comment by pnegahdar** [comment]
So to clarify my question: the default installation doesn't include SSH push/pull because there no instructions on setting up that gogs-serv command right?

**Comment by Unknwon** [comment]
@pnegahdar which `default installation` you are pointing to? SSH server?

**Comment by pnegahdar** [comment]
The installations described here: http://gogs.io/docs/installation, there is no mention of setting up the ssh hook. Are they created automatically at some point? I manually built a dockerfile for this.

**Comment by Unknwon** [comment]
You need to add SSH key in settings page like GitHub.

**Comment by pnegahdar** [comment]
Sorry I'm not being clear. I will try to fix my issue and report back later today.

**Comment by Unknwon** [comment]
@pnegahdar sure, no problem.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
