### ISSUE TITLE
Current version (0.5.12.0202 Beta) of gogs appears to chomp database.PASSWD value

### ISSUE THREAD

**Issue by deringer** [gogits/gogs#903]
My MySQL password has a `#` character in it. When parsing the config, everything including and after the `#` appears to be dropped, so database connection fails.

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

Can you try add ` in both sides of your password and see if it solves your problem?

**Comment by deringer** [comment]
Hi, looks l like putting the password in backticks did the trick.

Thanks!

On Thu, Feb 5, 2015 at 11:39 AM, 无闻 <notifications@github.com> wrote:

> Hi, thanks your feedback!
>
> Can you try add ` in both sides of your password and see if it solves your
> problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gogits/gogs/issues/903#issuecomment-72975644>.
>



-- 
Michael Dyrynda

P: (08) 7129 6369
M: 0439 883 971

Blog: http://deringer.tumblr.com

**Comment by Unknwon** [comment]
Great! 

PS: please close this issue if no further discussion needed.
