### ISSUE TITLE
Enable edit issue comment for user who posted an comment

### ISSUE THREAD

**Issue by guycalledseven** [gogits/gogs#906]
Posted Issues and replies to the issue should be editable (ideally for a period of time). 

When writing commenting an issue, If you forgot to mention something, only way to add something is to create new comment to the issue. That is not easily readable nor convenient. Also due to multiple errors in parsing of markdown present at the moment in gogs, IMHO this is important feature.

Thanks :)

**Comment by Unknwon** [comment]
You're right, thanks your feedback!

**Comment by ivan** [comment]
+1, hard to use gogs for issue tracking without being able to edit the issue and comments

**Comment by Unknwon** [comment]
It is now possible to edit issue and comments! https://try.gogs.io/unknwon/gogs/issues

**Comment by Unknwon** [comment]
Closed as implemented. :tada:
