### ISSUE TITLE
bad encoding of email subject

### ISSUE THREAD

**Issue by guycalledseven** [gogits/gogs#913]
When comment to the issue is posted, automated email that is being sent doesn't have UTF8 encoded subject, which causes ?? instead of specific language characters + as added bonus this triggers AMaViS (A Mail Virus Scanner).

header:
```
X-Quarantine-ID: <eEz8+C2c0aFZ>
X-Amavis-Alert: BAD HEADER SECTION, Non-encoded 8-bit data (char C5 hex):
	Subject: [videq] Gre\305\241ka File read e[...]
Subject: [videq] Greka File read error(#5)
Content-Type: text/html; charset=UTF-8
```

outlook displays: 
```[videq] Gre??ka File read error(#5)```

should display:
```[videq] Greška File read error(#5)```

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by phsmit** [comment]
I tried to fix this, but anything I would do at this stage would be just fighting symptoms. 

At this moment the message headers are just pasted together. Proper q encoding and line breaking is not easy, so preferably we would find a good email (mime message) construction package. 

Problem is, there are a lot of packages around that do that, not all of them good. A list in no particular order:

- https://github.com/go-gomail/gomail
- https://github.com/jpoehls/gophermail
- https://github.com/sloonz/go-mime-message
- https://github.com/scorredoira/email
- https://github.com/tike/MIMEMail

**Comment by phsmit** [comment]
Of the ones mentioned above only the first one seems to be mature. I'm willing to implement it, but we need to bump the minimum go version to 1.3....

**Comment by phsmit** [comment]
If we want this implementation, but not raise the minimum Go requirement, we can consider putting the mail functionality behind a "mail" build tag

**Comment by guycalledseven** [comment]
if I may add one more to the list - github.com/jordan-wright/email
I've had a lot of issues with go email encodings (both when reading imap & sending emails), and this package helped me tremendously for sending.

**Comment by Unknwon** [comment]
@guycalledseven this only requires Go 1.1 which is even lower than Gogs, looks great! cc @phsmit

**Comment by phsmit** [comment]
Unfortunately this lib does not do proper header encoding/wrapping. I created a gist to demonstrate it: https://gist.github.com/phsmit/172973767a8b487e6728 

If this lib would work correct, it would show only ascii characters in the header, and wrap all lines to the maximum header length.

**Comment by phsmit** [comment]
I tried gomail as well and they do a much better job: https://gist.github.com/phsmit/110708e68b7792f2905f

result: 

    Subject =?UTF-8?Q?=E8=BD=96=E8=BD=95_=E6=82=8A=E6=83=80=E6=A1=B7_=E9=A7=93?=
     =?UTF-8?Q?=E9=A7=97=E9=B4=80_=E5=B9=93_=E8=B6=9B=E8=B8=A0_=E8=BC=97_?=
     =?UTF-8?Q?=E8=BC=B2=E8=BC=B9=E8=BC=B4_=E7=9E=97=E7=A9=87=E7=B8=8D_?=
     =?UTF-8?Q?=E5=A5=AB=E5=AB=AE_=E9=A4=A4=E9=A7=B0=E9=AC=B3_=E6=AE=BD?=
     =?UTF-8?Q?=E6=AF=B0=E6=AF=B2_=E7=8C=92=E7=8C=B5=E7=9D=86_=E6=85=96,_?=
     =?UTF-8?Q?=E7=A4=9D=E7=A4=9B_=E9=BC=A5=E5=84=B4=E5=A3=9B_=E8=87=A1?=
     =?UTF-8?Q?=E8=99=88=E8=A7=BF_=E6=A5=8B_=E6=95=B3=E6=A6=B6_=E7=A3=8F_?=
     =?UTF-8?Q?=E6=BA=BF=E7=85=94=E7=85=83_=E6=93=99=E6=A8=B2=E6=A9=9A_?=
     =?UTF-8?Q?=E9=A9=A8=E8=A8=91=E7=B4=B1_=E8=82=B5=E8=8B=82=E8=8B=83_?=
     =?UTF-8?Q?=E7=A4=82=E7=B0=85=E7=B8=AD_=E7=BE=AD=E8=81=A7=E8=94=A9_?=
     =?UTF-8?Q?=E8=B7=BE_=E7=80=8A=E7=92=B8,_=E6=AF=BC=E6=AF=B9_=E5=8C=A2?=
     =?UTF-8?Q?=E5=A5=BE=E7=81=B1_=E7=A6=92=E7=AE=88=E7=AE=91_=E9=8A=88?=
    Mime-Version 1.0
    Date 10 Feb 15 10:01 +0200
    Content-Type text/plain; charset=UTF-8
    Content-Transfer-Encoding quoted-printable
    From =?UTF-8?Q?=E6=97=A0=E9=97=BB?= <my@email.com>

**Comment by phsmit** [comment]
The reason that gomail is Go 1.3 is that it uses the package alexcesaro/quotedprintable/ and that one has a very strange usage of sync.pool https://github.com/alexcesaro/quotedprintable/blob/v1/header.go#L75-L97

Good news, in a small while the go standard library will contain a quoted printable encoder : https://github.com/golang/go/tree/master/src/mime/internal/quotedprintable , bad news: I'm not sure what to do for now, I'm almost thinking of rolling out yet another email library for go

**Comment by guycalledseven** [comment]
@phsmit good find. dealing with encodings in go (quoted printable as well) leaves a lot to be desired. 
imho writing yet another lib is fastest road. but when you get to handling multipart, attachments, html,  email certificates, priority, etc things get nasty. :) there is no such comprehensive mail package yet. I went down different road with parsing of emails in go, ended up doing lots of client specific debugging (eg. apple mail/ms outlook don't obey 100% correct RFC's 5322 & 2047 etc), and would be interested in contributing.

**Comment by Unknwon** [comment]
Do we have any chance hack on `quotedprintable` and to avoid `sync.Pool`, maybe just copy out that part of code from Go 1.3?

**Comment by phsmit** [comment]
Sound appealing, but I think we end up forking both gomail and quotedprintable and making it a nice mess. I am liking the idea of @guycalledseven and I am going to start a mail lib at https://github.com/wedogo/email . If we can wait here a couple weeks I'll try to have a good lib ready

**Comment by guycalledseven** [comment]
@phsmit you are quick! :) just one question - why only creation of emails, and not creation and smtp facility?

**Comment by phsmit** [comment]
@guycalledseven Because sending an email is a separate process from creating one. Smtp is one way of sending, but SES/MailGun/AppEngine api are just as valid. Anyway, better do one thing right, then two things half.

**Comment by Unknwon** [comment]
> If we can wait here a couple weeks I'll try to have a good lib ready

No problem with me, up to @guycalledseven

**Comment by guycalledseven** [comment]
@phsmit I get your point, however I have some doubts. Let's continue on gitter. :) 

@Unknwon I love gogs and I'll help how much I can, only I have less experience in go than you guys. :)

**Comment by Unknwon** [comment]
@guycalledseven it's OK :smile: you're better than me elsewhere

**Comment by Unknwon** [comment]
Hi @guycalledseven !

New implementation of mailer module in Gogs has been pushed to `develop`, please help test and see if problem has been solved. Thanks!

**Comment by Unknwon** [comment]
Close as fixed.

**Comment by guycalledseven** [comment]
@Unknwon sorry for late reply. I tested it and email subject and body are shown correctly having utf8 character that were previously garbled.

Keep up the good work1 :+1:

**Comment by Unknwon** [comment]
:tada:
