### ISSUE TITLE
Gogs painfully slow when browsing repos

### ISSUE THREAD

**Issue by Stefan-Code** [gogits/gogs#914]
I am facing the problem that browsing repositories is dead-slow. Other stuff like browsing the dashboard, Users, Config etc. works fine but accessing the repo Overview or viewing files is painfully slow. Console output here:
<pre><code>
    C:\Go\stuff\src\github.com\gogits\gogs>gogs.exe web
    2015/02/07 05:29:00 [T] Custom path: C:/Go/stuff/src/github.com/gogits/gogs/custom
    2015/02/07 05:29:00 [T] Log path: C:/Go/stuff/src/github.com/gogits/gogs/log
    2015/02/07 05:29:00 [I] Gogs: Go Git Service 0.5.12.0202 Beta
    2015/02/07 05:29:00 [I] Log Mode: File(Trace)
    2015/02/07 05:29:00 [I] Redis Enabled
    2015/02/07 05:29:00 [I] Memcache Enabled
    2015/02/07 05:29:00 [I] Cache Service Enabled
    2015/02/07 05:29:00 [I] Session Service Enabled
    2015/02/07 05:29:08 [I] Run Mode: Production
    2015/02/07 05:29:08 [I] Listen: http://0.0.0.0:3000
    [Macaron] Started GET /Stefan/test/src/master/README.md for 127.0.0.1
    [Macaron] Completed /Stefan/test/src/master/README.md 200 OK in 19.7081272s
</code></pre>
As you can see the request to view the readme took 20 seconds! I also activated caching using redis, however nothing changed. I am using Windows 7 64bit, Go 1.4.1 and built the latest Gogs from source. 
I also had a look at the MySQL log files, and no slow queries show up there.

**Comment by Unknwon** [comment]
Thanks your feedback!

What's your repository looks like? Maybe upload to https://try.gogs.io ? 

Because right now your description is like black box to us.

Thanks.

**Comment by Stefan-Code** [comment]
Hi, thanks for the quick response, the repo is an empty one created with gogs and contains 3 files: README, LICENSE and .gitignore with python preset, nothing else

**Comment by Unknwon** [comment]
What's time consumption at the bottom of page?

**Comment by Stefan-Code** [comment]
Same as console, right now: 19583ms

**Comment by Unknwon** [comment]
I see, I would still recommend you upload the repository to https://try.gogs.io

**Comment by Stefan-Code** [comment]
I;m on it right now

**Comment by Stefan-Code** [comment]
Here it is: https://try.gogs.io/Stefan/test

**Comment by Unknwon** [comment]
I see it, seems like it doesn't behavior the same way that your system does...

**Comment by Stefan-Code** [comment]
Yeah... Any ideas what could be wrong? Can I somehow enable more verbose logging, etc.?

**Comment by Unknwon** [comment]
The only possible reason I can think for now is due to Git execution. 

Gogs currently calls git from command line to process the repository data, so do you have trouble with using Git? Like it's slow, or some virus checker to slow down every execution of any command?

**Comment by Stefan-Code** [comment]
After disabling F-Secure antivirus, loading times are down to:
Page: 1408ms · Template: 1ms
I think you can close it. I really have to get a Linux box...

**Comment by Unknwon** [comment]
@Stefan-Code very sorry about this... :sob:  maybe a check host on digital ocean would help.

**Comment by Unknwon** [comment]
:sunny:

**Comment by Stefan-Code** [comment]
No need to be sorry, thanks for your help. Good to know it's my computers fault :smile:

**Comment by AysadKozanoglu** [comment]
i have also the problem that gogs web und git push are very slow (waiting of something)

on fresh debian 8.8 jessie i started ./gogs from the extracted .tar.gz than i open the regular link http://:3000

gogs needs Page: 40071ms Template: 30031ms
Gogs Version: 0.11.19.0609 Page: 40071ms Template: 30031ms

i can not solve the issue with the performance. debian and gogs are fresh installed (nothing else) all settings are by default.

**Comment by AysadKozanoglu** [comment]
i solved my issue by looking logs.  gogs try to solve the avatar against (@gmail or what else you type)  and hangs :-)  

on first gogs installation  i disabled the avatar. now it is very quickly ;-)

thanks a lot for  alle gogs developers that i can use so nice open source solution.
