### ISSUE TITLE
Problem in LDAP UTF-8 string decoding

### ISSUE THREAD

**Issue by Lafriks** [gogits/gogs#916]
In file /modules/asn1-ber/ber.go function DecodeString code

```go
	for _, c := range data {
		ret += fmt.Sprintf("%c", c)
	}
```
should be replaced with
```go
	ret = string(data)
````
and then UTF-8 strings work correctly when coming from LDAP server.

**Comment by Unknwon** [comment]
Hi @Lafriks , thanks your info!

Would you like to take this chance to make a PR, or I'll just make quick changes locally and push to GitHub?

**Comment by Lafriks** [comment]
just make changes yourself

**Comment by Unknwon** [comment]
Hi, I've pushed fix to `dev` branch.

**Comment by Lafriks** [comment]
Cool, thanks

**Comment by Unknwon** [comment]
@Lafriks no problem, thanks again for your help!
