### ISSUE TITLE
Link to Closed Issue in Commit Description is escaped

### ISSUE THREAD

**Issue by Stefan-Code** [gogits/gogs#918]
When having a commit description like "this fixes #6", then it displays correctly when directly looking at the commit like so:
![gogs1](https://cloud.githubusercontent.com/assets/9949033/6097257/365d516e-afb7-11e4-9d30-90718e872251.png)
but in the repo overview it somehow displays the escaped version of the link html, so it becomes:
![gogs2](https://cloud.githubusercontent.com/assets/9949033/6097261/6928a184-afb7-11e4-9666-2741d1953e5f.png)
rendered HTML for it is:
<pre><code>
&lt;span class=&quot;text-truncate&quot;&gt;made downloader asynchronus (this fixes&amp;lt;a href=&amp;#34;/Stefan/downloader/issues/#6&amp;#34;&amp;gt;&lt;a href=&quot;/Stefan/downloader/issues/#6&quot;&gt; #6&lt;/a&gt;&amp;lt;/a&amp;gt; ) and some other stuff&lt;/span&gt;
</code></pre>
In view_list.tmpl this is line number 17 I think.
Thank you for an awesome piece of Open Source Software by the way, very nice and useful!

Edit:
I suspect the problem to be in markdown.go in line 177 in RenderIssueIndexPattern, but unfortunately I don't know go...

**Comment by Unknwon** [comment]
Thanks your report!

I've found this issue myself one or two days ago, so what's your Gogs version? Update to the latest `master` code should be fine, otherwise, you found a bug :smile:

**Comment by Stefan-Code** [comment]
I've used "go get -u -tags "redis memcache" github.com/gogits/gogs" yesterday, but I'll try to manually clone from github.

**Comment by Unknwon** [comment]
@Stefan-Code OK

**Comment by Stefan-Code** [comment]
Well, git says I'm up to day with master:
<pre><code>
    root@Synology:/opt/share/go/stuff/src/github.com/gogits/gogs# git log
    commit <b>f989805050</b>e36cf2c1532625e1643de795148c7f
    Author: Unknwon <joe2010xtmf@163.com>
    Date:   Sat Feb 7 11:12:13 2015 -0500

        conf/locale: update locales
</code></pre>

**Comment by Unknwon** [comment]
Maybe I messed up my memorize, but, yeah, https://try.gogs.io/unknwon/highlighting it's working, if we're talking the same page of UI...

**Comment by Stefan-Code** [comment]
yes, we do. Weird...

**Comment by Unknwon** [comment]
@Stefan-Code , if you can wait, we should have a mirror release soon.

**Comment by Stefan-Code** [comment]
Switched to the dev branch, now it's working :smile:

**Comment by Unknwon** [comment]
@Stefan-Code great! I thought I pushed, my bad :joy:
