### ISSUE TITLE
Info in activity stream is incomplete

### ISSUE THREAD

**Issue by deringer** [gogits/gogs#920]
Hi there,

For some reason when an issue is commented on, there is a string `%!(EXTRA string=##)` alongside the issue name in the activity stream.

![activity stream](https://www.dropbox.com/s/dag4o98pdfi4ugb/Screenshot%202015-02-09%2014.34.25.png?dl=1)

This only started happening recently and appears to be affecting all issues displayed in the activity stream.

**Comment by Unknwon** [comment]
Hi, I've just found and fixes this issue in `dev` branch.

**Comment by Unknwon** [comment]
PS: you can test on https://try.gogs.io

**Comment by deringer** [comment]
Great - working just fine on try.gogs.io. Thanks!

On Mon, Feb 9, 2015 at 2:49 PM, 无闻 <notifications@github.com> wrote:

> PS: you can test on https://try.gogs.io
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gogits/gogs/issues/920#issuecomment-73455700>.
>



-- 
Michael Dyrynda

P: (08) 7129 6369
M: 0439 883 971

Blog: http://deringer.tumblr.com

**Comment by Unknwon** [comment]
@deringer no problem!
