### ISSUE TITLE
"Gogs: auth file format error" when cloning via ssh

### ISSUE THREAD

**Issue by kaibookblue** [gogits/gogs#922]
Hi.  Fresh install from source on a Debian 7 (32 bit) with go version go1.4.1 linux/386 here.

I added an SSH key but kept getting "Gogs: auth file format error" whenever I tried to clone a repo via ssh.  In the serv.log runServ() was complaining "[F] Invalid auth file format".  Looking serve.go in runServ() that error comes up if it can't split os.Args[2] on a hypen.

I manually edited my .ssh/authorized_keys and moved the "key-1" to before the "--config" parameter and it worked.  (So now it says command="/home/git/go/src/github.com/gogits/gogs/gogs serv key-1 --config=.....").  Looks like the parameter order that is created when an ssh key is uploaded is different to the one expected?

Cheers,
Darren

**Comment by phsmit** [comment]
I can confirm this. This seems to have slipped in when I created the custom config option. I'll create a pull request in a short while

**Comment by phsmit** [comment]
Are you able to test my PR #923 ? You can click "Rewrite '.ssh/autorized_key' file" in the admin panel to fix the authorized keys file automatically

**Comment by kaibookblue** [comment]
Seems to work for me.  Steps followed:

1) Grab https://github.com/gogits/gogs/pull/923.patch
2) patch -p1 < 923.patch
3) go build
4) restart gogs

I deleted the existing key and uploaded again.  The "key-n" is now before the "--config" and a clone over ssh works with no manual tweaking.

Hope that helps.  Please let me know if you need me to do something else for a better test.
Darren

**Comment by phsmit** [comment]
Thanks! I can't merge, but I'm sure @Unknwon will as soon as daylight starts in the States

**Comment by Unknwon** [comment]
Merged, thank you all!
