### ISSUE TITLE
Update Year

### ISSUE THREAD

**Issue by tstorch** [gogits/gogs#928]
It 2015 over a month now. There are 2014s all over the place. This should probably be fixed.

**Comment by Unknwon** [comment]
> There are 2014s all over the place

I don't exactly understand what you mean?

**Comment by matt-h** [comment]
For example, he means the "© 2014 GoGits" in the footer of https://try.gogs.io/

**Comment by Unknwon** [comment]
@matt-h thanks for the tip! I've fixed this locally, will push soon.

**Comment by tstorch** [comment]
That's what I meant. Sorry, was in a hurry.

**Comment by Unknwon** [comment]
@tstorch no problem, how's it look right now? https://try.gogs.io/

**Comment by tstorch** [comment]
Better :)
