### ISSUE TITLE
Internal Server Error - trying to watch

### ISSUE THREAD

**Issue by robmoggach** [gogits/gogs#929]
I received the following error when trying to 'watch' a repo with an unregistered user. Probably an exception that needs catching. Works as expected when logged in. Watch/Unwatch/etc.

	[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
	/home/git/lib/go/src/runtime/panic.go:387 (0x413f48)
		gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
	/home/git/lib/go/src/runtime/panic.go:42 (0x41326e)
		panicmem: panic(memoryError)
	/home/git/lib/go/src/runtime/sigpanic_unix.go:26 (0x419a04)
		sigpanic: panicmem()
	/home/git/var/go/src/github.com/gogits/gogs/routers/repo/repo.go:338 (0x6b700c)
		Action: err = models.WatchRepo(ctx.User.Id, ctx.Repo.Repository.Id, true)
	/home/git/lib/go/src/runtime/asm_amd64.s:401 (0x43ce35)
		call16: CALLFN(·call16, 16)
	/home/git/lib/go/src/reflect/value.go:419 (0x6edc45)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/home/git/lib/go/src/reflect/value.go:296 (0x6eca3c)
		Value.Call: return v.call("Call", in)
	/home/git/var/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x91b427)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:112 (0x5e7c35)
		(*Context).run: vals, err := c.Invoke(c.handler())
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:103 (0x5e7b33)
		(*Context).Next: c.run()
	/home/git/var/go/src/github.com/macaron-contrib/session/session.go:188 (0x62bf98)
		func.004: ctx.Next()
	/home/git/lib/go/src/runtime/asm_amd64.s:401 (0x43ce35)
		call16: CALLFN(·call16, 16)
	/home/git/lib/go/src/reflect/value.go:419 (0x6edc45)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/home/git/lib/go/src/reflect/value.go:296 (0x6eca3c)
		Value.Call: return v.call("Call", in)
	/home/git/var/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x91b427)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:112 (0x5e7c35)
		(*Context).run: vals, err := c.Invoke(c.handler())
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:103 (0x5e7b33)
		(*Context).Next: c.run()
	/home/git/var/go/src/github.com/Unknwon/macaron/recovery.go:161 (0x5fb8e3)
		func.008: c.Next()
	/home/git/lib/go/src/runtime/asm_amd64.s:401 (0x43ce35)
		call16: CALLFN(·call16, 16)
	/home/git/lib/go/src/reflect/value.go:419 (0x6edc45)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/home/git/lib/go/src/reflect/value.go:296 (0x6eca3c)
		Value.Call: return v.call("Call", in)
	/home/git/var/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x91b427)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:112 (0x5e7c35)
		(*Context).run: vals, err := c.Invoke(c.handler())
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:103 (0x5e7b33)
		(*Context).Next: c.run()
	/home/git/var/go/src/github.com/Unknwon/macaron/logger.go:40 (0x5fa620)
		func.004: ctx.Next()
	/home/git/lib/go/src/runtime/asm_amd64.s:401 (0x43ce35)
		call16: CALLFN(·call16, 16)
	/home/git/lib/go/src/reflect/value.go:419 (0x6edc45)
		Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
	/home/git/lib/go/src/reflect/value.go:296 (0x6eca3c)
		Value.Call: return v.call("Call", in)
	/home/git/var/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x91b427)
		(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
	/home/git/var/go/src/github.com/Unknwon/macaron/context.go:112 (0x5e7c35)
		(*Context).run: vals, err := c.Invoke(c.handler())
	/home/git/var/go/src/github.com/Unknwon/macaron/router.go:158 (0x5fcdfc)
		func.015: c.run()
	/home/git/var/go/src/github.com/Unknwon/macaron/router.go:245 (0x5f35f8)
		(*Router).ServeHTTP: h(rw, req, p)
	/home/git/var/go/src/github.com/Unknwon/macaron/macaron.go:171 (0x5ec2bc)
		(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
	/home/git/lib/go/src/net/http/server.go:1703 (0x5c898a)
		serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
	/home/git/lib/go/src/net/http/server.go:1204 (0x5c63f7)
		(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
	/home/git/lib/go/src/runtime/asm_amd64.s:2232 (0x43ef51)
		goexit:
	[Macaron] Completed /robmoggach/moggach-first/action/watch 500 Internal Server Error in 13.506576ms

**Comment by Unknwon** [comment]
What is your version of Gogs?

**Comment by robmoggach** [comment]
Version: 0.5.13.0209 Beta

--
Robert Moggach
Sr. VFX Supervisor / Flame Artist
Los Angeles / New York / London / Toronto
http://moggach.com
https://www.linkedin.com/profile/view?id=1664843
Mobile (310) 773-1793

**Comment by Unknwon** [comment]
Thanks, bug is confirmed!

**Comment by robmoggach** [comment]
to be honest - if you're not registered, then you shouldn't see the fork,
star, etc. buttons or they should be disabled with a tooltip

--
Robert Moggach
Sr. VFX Supervisor / Flame Artist
Los Angeles / New York / London / Toronto
http://moggach.com
https://www.linkedin.com/profile/view?id=1664843
Mobile (310) 773-1793

**Comment by Unknwon** [comment]
Hi @robmoggach , thanks your advice!

For this particular issue, I've pushed fix on `dev` branch and you're free to test on https://try.gogs.io/unknwon/gogs

**Comment by robmoggach** [comment]
Looks good. I'd say you've shut that one down cleanly.

--
Robert Moggach
Sr. VFX Supervisor / Flame Artist
Los Angeles / New York / London / Toronto
http://moggach.com
https://www.linkedin.com/profile/view?id=1664843
Mobile (310) 773-1793

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:
