### ISSUE TITLE
Issue Daemon debian

### ISSUE THREAD

**Issue by preovaleo** [gogits/gogs#930]
there is an error when i use the daemon on ubuntu
Can't use `||`
file : [./scripts/init/debian/gogs](https://github.com/gogits/gogs/blob/master/scripts/init/debian/gogs)

```
$> service gogs start
* Starting Go Git Service gogs
sh: line 2: return: can only `return' from a function or sourced script
```

it comes from line 51-57

**Comment by Unknwon** [comment]
Hi, thanks your report.

But all scripts are come from third-party, you can contribute a PR to fix it.
