### ISSUE TITLE
Issue labels: order of labels

### ISSUE THREAD

**Issue by EtienneBruines** [gogits/gogs#931]
Hi,

It would be nice to change the order in which the labels are applied to the issues. 

At the moment (dev branch of a week ago) - it looks like this:
![Screenshot of Issues with labels](https://vps2.huperwebs.nl/screenshot-2015-02-10_22-32-08.jpg)

It would be nice if the order in which the labels are displayed, was the same. Right now, it is the order in which I added the labels, which is shown. 

Possible awesome features/fixes:
- alphabetically ordered;
- user defined order (globally).

**Comment by Unknwon** [comment]
Thanks for the feature request!

**Comment by Unknwon** [comment]
Currently, labels is ordered by ASC label ID.
