### ISSUE TITLE
Issue labels: amount not updated on issue removal

### ISSUE THREAD

**Issue by EtienneBruines** [gogits/gogs#933]
Whenever a label is removed from an issue, the global amount (of that specific label) is unaffected. 

![Image of a label with 1 element, but none shown](https://vps2.huperwebs.nl/public/screenshot-2015-02-10_23:15:42.jpg)

Here we see `1 Issue` at label `fatal`, but there is no issue listed.

**Comment by Unknwon** [comment]
Thanks for the report!

**Comment by nicolai86** [comment]
:+1: anyone working on this?

**Comment by Unknwon** [comment]
@nicolai86 it's on the todo list.

**Comment by nicolai86** [comment]
@Unknwon I didn't find it on the trello :( don't want to make a PR for something that's already half way through

**Comment by Unknwon** [comment]
Hi @EtienneBruines , @nicolai86 had PRed to `dev` branch and now able to test on https://try.gogs.io .

**Comment by EtienneBruines** [comment]
Reproduced with:
- create label
- check counter for that specific label (now 0)
- create issue
- add label to issue
- check counter for that specific label (now 1)
- close issue
- check counter for that specific label (now 1; expected 0). 

Does not seem to work just yet. 

# More info
When clicking `closed` to list the closed issues, the label counter switches to value `0`. When clicking `open` to list the open issues, the label counter switches to value `1`. 

This should be the other way around: 0 open issues, 1 closed issue with that label.

**Comment by nicolai86** [comment]
I will try again later today :)

**Comment by Unknwon** [comment]
@EtienneBruines thanks for more info!

@nicolai86 thanks your work!

**Comment by nicolai86** [comment]
turns out I fixed a related issue but not quite the one which was reported: when removing a label the label count also did not go down. anyway, that's fixed in dev and I'll open a PR for this one soon, too.

**Comment by Unknwon** [comment]
@nicolai86 ha! :scream:

**Comment by nicolai86** [comment]
I've just pushed another fix… (:

**Comment by nicolai86** [comment]
Small sidenote: I *guess* the issue also appears when closing an issue via git commit message. I'm currently trying to pin down where that happens to check If my guess is right. Might need to update the PR if my guess is right.

**Comment by Unknwon** [comment]
> Small sidenote: I guess the issue also appears when closing an issue via git commit message. I'm currently trying to pin down where that happens to check If my guess is right. Might need to update the PR if my guess is right.

I think your guess is right, and please consider my comments in the PR.

**Comment by nicolai86** [comment]
@Unknwon I'll change it to do post increment/ decrement again, and also update the other parts.

**Comment by Unknwon** [comment]
@nicolai86 thanks! Your solution is more robust but it takes significant longer time than  increment/ decrement, especially when user number get large. But, it's a good way to admin panel to correct wrong number though!

**Comment by nicolai86** [comment]
@Unknwon at least we should think about how to correct the wrong numbers out there. PR is done again.

Now it also works when pushing via git comments.

**Comment by Unknwon** [comment]
@nicolai86 made another comment.

PS: having class now, will come back ASAP.

**Comment by nicolai86** [comment]
no need to hurry I'm off for the night (:

**Comment by Unknwon** [comment]
@nicolai86 :facepunch:
