### ISSUE TITLE
一个关于安装很奇怪的问题！

### ISSUE THREAD

**Issue by elvis-bi** [gogits/gogs#934]
首先，为这样一个无法表达问题的标题向大家道歉！因为我确实不知道如何用一句话描述清楚我目前遇到的问题。:(

问题是这样，我之前有一台使用gitosis架设的git服务器。然后我在这台服务器上尝试架设过gogs，最终没有成功。于是就在另外一台服务器上使用gogs架设了一个新的git服务器。而在我的本地origin关联的是原来使用gitosis架设的服务器，有一个叫gogs的remote关联的是新的使用gogs架设的服务器。刚开始的时候工作正常，不过最近突然无法访问到origin了。返回的错误信息显示
```
Gogs: unavailable repository 'xxx.git'
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
甚至连我新clone原来gitosis上的仓库也是这样的提示。更奇怪的是只有我这台电脑无法访问gitosis上的仓库，其它电脑都可以正常访问。我访问远端仓库都是直接使用的IP地址，也应该不是我在hosts里添加了指向造成的问题。

另外，还有个背景我使用的是osx系统，前几天在清理系统的时候好像误删过xcode的什么东西。然后有提示过我git需要xcode的命令行工具让我安装，不知道是否与这个问题有关？

感觉这个问题很奇怪，不知道有没有那位高人知道可能是什么原因造成的呢？

**Comment by Unknwon** [comment]
What is your Gogs version?

**Comment by Unknwon** [comment]
Looks like you didn't config your origin right, can you dump your `.git/config` file?

**Comment by elvis-bi** [comment]
在.git/config中origin指向的无端IP地址是正确的gitosis git服务器地址，而且我使用git clone gitoisip/xxx.git也是同样的提示。

**Comment by Unknwon** [comment]
Whatever happens, your gitosis isn't taking control now. 

So the question is, are you running gitosis in "gitosis" server, or you're running Gogs?

**Comment by elvis-bi** [comment]
在gitosis服务器上没有运行gogs server。我使用netstat -lntp也没有看到有gogs。这个问题我觉得应该是我本地有什么问题，因为在别的电脑上是可以正常访问到gitosis server上的仓库！

**Comment by Unknwon** [comment]
OK, I guess your problem is:

There is a SSH pubic key of your computer in the `.ssh/authorized_keys` file, which was created by Gogs, somehow your SSH connection calls on that one, and then Gogs tells you the repository path is not right. 

If I'm right, just delete that SSH key created by Gogs; otherwise, we need to investigate more. :satisfied:

**Comment by elvis-bi** [comment]
哈哈，就是这个问题。我删除掉gitosis server上.ssh/authorized_keys里的公钥后就正常了。谢谢！非常感谢！:)

**Comment by Unknwon** [comment]
@elvis-bi no problem, my pleasure!
