### ISSUE TITLE
Markdown Parsing Error on '@' (At sign)

### ISSUE THREAD

**Issue by johnroyer** [gogits/gogs#935]
Markdown parser has strange behavior on '@' (at sign). I found three condition that make this error happened.

An SSH account without any markdown syntax, like:

    SSH login: git@test.domain

After push to GoGits, the web page show like this:

![at sign parse error](https://cloud.githubusercontent.com/assets/114491/6141451/aab40456-b1e0-11e4-96a4-34784439e3ed.png)

----

If the '@' is in an inline code block:

    SSH login with code block inline: `git@test.domain`

GoGits show as:

![at sign parse error in inline code block](https://cloud.githubusercontent.com/assets/114491/6141445/9fd7fbe6-b1e0-11e4-9969-f2255e3c3426.png)

----

And if there is an '@' in code block:

    some instruction:
    
        run this
        git clone git@test.domain

GoGoits shows:

![at sign parse error in code block](https://cloud.githubusercontent.com/assets/114491/6141442/8b8e8970-b1e0-11e4-8d6e-cc14b3da49a4.png)

Problems happens in `GoGits 0.5.11.0103 Beta` in `Production Mode`.

**Comment by Unknwon** [comment]
Hi @johnroyer , thanks your detailed report!

I cannot recall which one this is duplicated to, but this is been fixed as you can see here: https://try.gogs.io/unknwon/issue935

Fix also will come with new mirror release soon!

**Comment by johnroyer** [comment]
Thanks a lot. I'll try again in next release.

**Comment by Unknwon** [comment]
no problem!

**Comment by johnroyer** [comment]
I find some related issues: #178 , #738

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:

**Comment by johnroyer** [comment]
I tests again on `Gogs 0.5.13.0212 Beta`. Problems above has been absolutely resolved.

**Comment by Unknwon** [comment]
@johnroyer thanks for your response!
