### ISSUE TITLE
Issue search

### ISSUE THREAD

**Issue by EtienneBruines** [gogits/gogs#938]
It would be nice to do a text-based search on issues. (Feature request)

Does not have to be on description / comments - title would be a good start. 

It can be like the "filters" at GitHub (more customization), but can be a lot simpler than that - at least for the start.

**Comment by Unknwon** [comment]
That's the way we are heading to, thanks!

**Comment by mexthemax** [comment]
I +1 this request.
I would also like the search box to show applied filters. Much like the filter box in GitHub (meaning to prefill the box with something like "tag:tagname milestone:milestonename" if those filters are applied)

**Comment by rogeriolino** [comment]
I believe that this project could be helpful: https://github.com/etsy/hound

**Comment by ChangePlaces** [comment]
A thousand times yes!

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/13
