### ISSUE TITLE
Able to restrict access only to domain and not IP

### ISSUE THREAD

**Issue by kcloze** [gogits/gogs#939]
is there a config for disable ip address access? we need to keep gogs only used in local area network,it   will be safe for source code.

**Comment by Unknwon** [comment]
Thanks!

**Comment by stonerl** [comment]
@kcloze 

If you set ```"HTTP_ADDR = 127.0.0.1"``` and use a reverse-proxy, wouldn't that solve your problem?

**Comment by Unknwon** [comment]
I think @stonerl gave the solution. :trollface:
