### ISSUE TITLE
about repository url when gogs running behind apache

### ISSUE THREAD

**Issue by wanghm** [gogits/gogs#944]
I setup a gogs server in aws:

    ELB(https:443)->Apache(http:80)->gogs(http:3000)
    URL: https://mydomain.xyz

Seems everthing works fine except the repository url showing in the browser.
(in "copy to clipboard" )

I think it should be:

    https://mydomain.xyz/xxx/xxxxx.git
but it is showing as :

    http://127.0.0.1:3000/xxxx/xxxxx.git

Please tell me how to config in this case.

Note, here is my setting:
##### Apache Config

    ProxyPass / http://localhost:3000/
    ProxyPassreverse / http://localhost:3000/

##### Gogs config(custom/conf/app.ini)

    [server]
    PROTOCOL = http
    DOMAIN = mydomain.xxx
    ROOT_URL = http://127.0.0.1:3000/

**Comment by matt-h** [comment]
Update ROOT_URL to https://mydomain.xyz/ should do the trick.

**Comment by wanghm** [comment]
thanks, it worked.

**Comment by Unknwon** [comment]
@matt-h thanks for the help!

@wanghm glad you solve the problem!

**Comment by return42** [comment]
When running behind WEB server, the Gogs server should not listen to the WEB.  Thats why I recommend to set `HTTP_ADDR` to `127.0.0.1` to prevent bypass access from the WWW, direct to the Gogs port (3000). Here is my app.ini's ``[server]`` config:

```ini
[server]
DOMAIN = 127.0.0.1
HTTP_ADDR = 127.0.0.1
HTTP_PORT = 3000
ROOT_URL=https://hostname.mydomain.xyz
```

And here is my Apache site:
```apache
<Location ${GOGS_APACHE_URL}>

    <IfModule mod_security2.c>
        SecRuleEngine Off
    </IfModule>

    Require all granted
    Options +FollowSymLinks

    ProxyPreserveHost On

    # Allow forwarding to gogs
    ProxyPass http://127.0.0.1:3000
    ProxyPassReverse http://127.0.0.1:3000

    RequestHeader add X-Forwarded-Proto https
    RequestHeader set X-Forwarded-Ssl on

</Location> ```
