### ISSUE TITLE
Add support for two factor authentication

### ISSUE THREAD

**Issue by nicolai86** [gogits/gogs#945]
Hey,

I'd like gogs to have support for opt-in 2FA, with TOTP, just like github has.

The implementation is pretty straight forward as there are numerous golang libraries implementing TOTP (like pquerna/otp), we'd just have to store the per user secret.

In a first draft I'd leave out the recovery codes as the admin can always remove the 2FA/ reset via db.

What do you think - might a 2FA PR get in?

**Comment by Unknwon** [comment]
Hi, it would very awesome to have this feature, I personally like it, too.

But it's far beyond the plan, plus, at the current stage, 2FA will be only used for login to web UI( other things are stilling changing, not a good time to plugin 2FA).

**Comment by Kruemmelmonster** [comment]
:+1:

**Comment by bnikola** [comment]
Is there any work on this feature by any chance? 2FA for web UI would be great. Plain username / password can be breached by a determined attacker, given the fact that many people use easy to remember passwords.

**Comment by Unknwon** [comment]
@bnikola 

> Is there any work on this feature by any chance?

No.

> given the fact that many people use easy to remember passwords.

Just want to say lazy people does not even care to use 2FA :joy:

**Comment by bnikola** [comment]
I feel I should give a little bit of a context here - I'm using gogs for my company's public git, we're evaluating solutions that provide a web UI. You most likely know that there's only GitLab and Github that expose similar functionality as gogs. Given the fact that Github is pretty much useless in the context I want to use it (severe lack of control, costs money etc.) and GitLab is slower than a snail, with more "tools" and dependencies than anything I've seen - gogs seemes like an obvious choice. I'm currently building a PAM that enforces 2FA when cloning or updating a git repo via SSH. I would love it if there was a 2FA for web UI because we're working with people that require stronger authentication methods due to regulations (financial market). I know where you're coming from, I know people are lazy, but it would be great if we had this feature on per-user basis. Anyway, any chances for a pull request that enables this feature on a per-user basis? I could code it, but would you add it to the master branch?

**Comment by nicolai86** [comment]
@bnikola if you like we can collaborate on this feature - I'd like to have it as well, but have not yet started working on it. If 2FA is fine for the UI only it would be worth the effort I think

**Comment by Unknwon** [comment]
@bnikola thanks for your detail!

I want to point out my opinion, I personally like to have this feature very much.

But there is one problem I haven't got an idea on it.

When you enable 2FA, you can push/pull with SSH obviously, but how about HTTP/HTTPS?

I see GitHub desktop and Hub warper have solved this problem, just don't know how.

**Comment by nicolai86** [comment]
@Unknwon afaict they use your username, password & 2FA to generate a token which they store inside your `~/.gitconfig`

**Comment by bnikola** [comment]
@nicolai86 it's doable, I'd like this feature for web UI as well, I've done an integration of 2FA for a recent project so I've got the know-how, I'll have free time shortly so I'd really like to take a stab at 2FA for Gogs. 

@Unknwon  - I'm not sure how Github desktop client really works because I didn't use it so far, but I know that guys at kernel.org use gitolite as their access layer and they implemented 2FA over that. Additional option is creating the Personal Authentication Module (PAM) for SSH connections, which is really troublesome so I'd say that 2FA on web UI would be an awesome first step and then we can take a look for ssh later on (or even create a desktop client at some point, using [nw.js](http://nwjs.io) would make such a thing easily doable)

**Comment by Unknwon** [comment]
@nicolai86 

> afaict they use your username, password & 2FA to generate a token which they store inside your ~/.gitconfig

I've checked that but nothing related to 2FA, only `git-lfs` thing....

**Comment by Unknwon** [comment]
FIDO U2F: https://github.com/gogits/gogs/issues/1787#issue-111559634

**Comment by ZacharyDuBois** [comment]
+1

**Comment by PierreKircher** [comment]
+1 much desired

**Comment by bkleef** [comment]
+1

**Comment by jmMeessen** [comment]
+1

**Comment by scuba323** [comment]
+1

**Comment by ghuntley** [comment]
Yes please.

**Comment by EliasGabrielsson** [comment]
+1 for FIDO U2F Scheme
https://fidoalliance.org/specifications/overview/

**Comment by mmoya** [comment]
+1

**Comment by minecrafter** [comment]
I am interested in working on adding two-factor authentication support to Gogs.

Gogs is nice, but lack of two-factor authentication really sours the deal for me. I know some Go so I am happy to try implementing it.

**Comment by Unknwon** [comment]
@minecrafter this requires you understand Gogs auth workflow very well... good luck!

**Comment by minecrafter** [comment]
@Unknwon I realized it was going to be difficult. Let's give it a go though :)

**Comment by minecrafter** [comment]
I think I have a decent grip on how authentication works. It wouldn't be difficult to add a second-stage page for two-factor authentication.

For now I'm going to focus on allowing the user to add two-factor access to their account.

**Comment by minecrafter** [comment]
I'm going to take a break now, but I managed to insert an authentication page in the process of logging in, but I don't yet have 2FA working.

**Comment by minecrafter** [comment]
Turns out I was generating the wrong secret. Now I have it working :smiley: 

Now we turn to adding support to enable and disable 2FA.

**Comment by minecrafter** [comment]
I am going to wrap up for today, but I have made some headway.

**Comment by minecrafter** [comment]
Update on my headway: Two-factor authentication can be enabled, disabled, and you will be prompted for a code when logging in.

What's missing: A nice interface for managing two-factor authentication settings, rate limiting, cancelling tokens when they are used, backup codes, and email notifications for when two-factor settings are changed or a backup code is used.

I anticipate being able to get much of this done by the weekend.

**Comment by arkraft** [comment]
To handle the problem with HTTP/HTTPS authentication with 2FA you could use App-Specific-Passwords. Google and Apple are using these for clients which do not support 2FA. You could then generate a new password when enabling 2FA and the user would have to use this password for his git clients.

**Comment by Unknwon** [comment]
@arkraft good point!

**Comment by xor-gate** [comment]
@Unknwon is there anybody who already did some work on this? I tried to integrate with a existing golang implementation of Google Authenticator style 2FA into gogs and it started to work. Should I create a initial draft as a pull request and reference this issue to it ?

**Comment by Unknwon** [comment]
@xor-gate cc @minecrafter

**Comment by minecrafter** [comment]
@xor-gate that's actually precisely what I did, and I also added enrollment support. Mine still lacks quite a few features but it is getting there.

**Comment by xor-gate** [comment]
@minecrafter i tried to look at your gogs fork for the implementation of this but did you push it public yet?

**Comment by minecrafter** [comment]
@xor-gate It's not currently public, do you want me to push?

**Comment by xor-gate** [comment]
@minecrafter, then I can have a look and when time permits I can give some feedback and maybe enhance and test it a little.

**Comment by minecrafter** [comment]
Pushed: minecrafter@5cd299

**Comment by xor-gate** [comment]
@minecrafter after a quick look i'm pretty impressed by the work you already created. I only took 30 minutes to understand the Gogs auth flow and it is a little tricky but understandable. I think it would be nice to also have some scratchpad tokens and per-app passwords as google/facebook do. But that is a extension when this works correctly.

**Comment by xor-gate** [comment]
@minecrafter any offline progress on integration, or had no time yet?

**Comment by minecrafter** [comment]
I've run out of time to work on this.

**Comment by xor-gate** [comment]
Yeah I understand, it would be a shame if your work gets lost and delved in the moving develop branch. @Unknwon are there other people who have some time left to assist in integration ?

**Comment by colundrum** [comment]
Waiting the integraton of this security feature…
Thanks a lot about the actual version.

**Comment by rugk** [comment]
Please integrate this. The same way as GitHub does access tokens could be used for git locally.

**Comment by david-oswald** [comment]
+1 from me for integration

**Comment by Amarandus** [comment]
+1 from me, too

**Comment by strugee** [comment]
@Amarandus @david-oswald @colundrum @rugk please don't add +1s; they aren't helpful. They just generate more noise for the project maintainers and for those of us who are subscribed to this issue. You might consider adding a thumbs up reaction to this issue. Thanks!

Or, even better, pick up where @minecrafter left off and finish up the integration yourselves :)

**Comment by xor-gate** [comment]
@strugee totaly agree, there needs some contribution to stand up to have this baselined with latest develop.

**Comment by nmaas87** [comment]
+1

**Comment by ModdyLP** [comment]
When is this feature coming? I am really waiting for it.

**Comment by xor-gate** [comment]
Just migrate to gitea, the 2FA feature is integrated and much more goodies.

**Comment by jhasse** [comment]
> Just migrate to gitea, the 2FA feature is integrated and much more goodies.

Gitea still doesn't provide deb/rpm packages. Also migrating is only supported up to Gogs version 0.9.115 and I guess many people already upgraded beyond that :/

**Comment by Unknwon** [comment]
TODO:

- [ ] Enable/disable 2FA in user settings
- [ ] Recovery code
- [ ] Personal access token for HTTPS access
- [ ] Login with OTP/Recovery code

Reference: https://github.com/pquerna/otp

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
