### ISSUE TITLE
Do not distribute MacOS and other meta data

### ISSUE THREAD

**Issue by matze** [gogits/gogs#957]
For most releases you (accidentally) include

* a `__MACOSX` folder in the root,
* various `.DS_Store` files in each subdirectory and 
* an `.idea` folder in `public`.

Although it's not a real issue, it does not look very professional.

**Comment by Unknwon** [comment]
Thanks your reminder, I keep forgetting this... next time I'll use program to do this. :beer:

**Comment by matze** [comment]
Wow quick answer :beers:

You could make this part of a release shell script, starting with `find . -name ".DS_store" -print0 | xargs -0 rm`.

**Comment by Unknwon** [comment]
> find . -name ".DS_store" -print0 | xargs -0 rm

Thanks for the useful tip!

**Comment by Unknwon** [comment]
Close for now, feel free to reopen if you want to continue discussing. :wink:
