### ISSUE TITLE
sync to external repo

### ISSUE THREAD

**Issue by vtolstov** [gogits/gogs#96]
Is that possible to create ability to do external sync from gogits for example to giithub and bitbucker and other services?
I thinks that no need much work...

**Comment by vtolstov** [comment]
ping, as i see gogs have email notify system, so we can use it to notify user about errors..

**Comment by vtolstov** [comment]
this related to #1623

**Comment by JokerQyou** [comment]
After reading some blog posts of mirroring external git repos to github, I think this is possible. Sadly, I did not get it to work.

[About GitHub mirrors][1] told us that we can use `post-receive` hook to push commits to github, after these commits were received by gogs; And [Duplicating a repository][2] told us how to manually push to a mirror, as well as [Setting up backup (mirror) repositories on GitHub][3].

However, what blocked me from achieving this is that gogs seem not to store its repos as ordinary git repos. Now, when I say 'ordinary git repos', I mean we can see its status via `git status` inside that folder. Gogs seems to store all these git information as structured folders. So doing something like `git push --mirror github` does not work in `post-receive` scripts.

I wonder how gogs manipulates git operations without storing the repo in the ordinary form. @Unknwon do you have any example of how to write a `post-receive` ( or any other git hooks ) script that works in gogs?

  [1]: https://help.github.com/articles/about-github-mirrors/
  [2]: https://help.github.com/articles/duplicating-a-repository/
  [3]: https://wincent.com/wiki/Setting_up_backup_(mirror)_repositories_on_GitHub

**Comment by Unknwon** [comment]
@JokerQyou see http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/

**Comment by JokerQyou** [comment]
Wow. Thanks for sharing this post. So after reading that post I've managed to solve this via the `post-receive` hook.
* First set a `post-receive` hook in the project settings in gogs with the content of `exec git push --mirror {EXTERNAL_REPO_URL}`;
* then, instead of directly pushing to this gogs project, use `sudo git` to enter shell as user `git` (or other user which your gogs is running as);
* thirdly, enter the folder where all your gogs repos are stored, and locate the target project;
* enter the `hooks` directory, and execute the `post-receive` hook using `./post-receive`;
* when prompted with host key verification, enter `yes`. This only needs to be done once;
* exit `git` user.

From now on, all gogs repo on the same server should be able to be mirrored to external git services like github, by using the `post-receive` hook.
The key here is that you have to confirm the host key of external git server during the first push.

**Comment by Unknwon** [comment]
> The key here is that you have to confirm the host key of external git server during the first push.

You can achieve that by manually push once..

**Comment by JokerQyou** [comment]
Yes, but not much people would do it as `git` user. :laughing: 
Or you can just add the host key to `~/.ssh/known_hosts` of `git` user.

**Comment by Unknwon** [comment]
:trollface:

**Comment by vtolstov** [comment]
Any news?

**Comment by joepie91** [comment]
> The key here is that you have to confirm the host key of external git server during the first push.

This can be sidestepped by [changing StrictHostKeyChecking](http://askubuntu.com/a/123080). While that answer is for using SSH manually, you can also [set SSH options for Git](http://stackoverflow.com/a/7772571/1332715).

I'd also be very happy to see this implemented :)

**Comment by z2z** [comment]
+1 for this feature

**Comment by binaryben** [comment]
+1 for this feature please! Would be good to have my own Git repo available on GitHub when needed.

**Comment by reinos** [comment]
+1

**Comment by ericfont** [comment]
+1 for this feature.  Also I want to sync to gitlab.com

**Comment by danierukun** [comment]
+1

**Comment by zfbp** [comment]
+1

**Comment by zfbp** [comment]
two way mirror

**Comment by dalareo** [comment]
Anybody working on this?

**Comment by adpande** [comment]
+1

**Comment by JokerQyou** [comment]
Guys, if you just want to vote for this feature, you might want to add your reaction to the first comment of this issue. You can react with 👍 and many other emojis.
But please stop commenting with meaningless content like "+1". Commenting with those content would not contribute to the implementation, and they're really annoying for those who want to keep an eye on this issue. Every time you add a comment like "+1", all the commented and subscribed users receive an email.

**Comment by Unknwon** [comment]
Hmm, why isn't `post-receive` enough?

**Comment by z2z** [comment]
https://stackoverflow.com/questions/3284415/how-to-organize-and-setup-mirrored-backup-servers-for-git-repositories

**Comment by dalu** [comment]
I don't know I can't get it to work

- I have a gogs repo https://git.icod.de/dalu/forum
- I have a github repo https://github.com/dalu/forum
- I have added a post-receive hook `exec git push --mirror git@github.com:dalu/forum.git`
- I have github.com in my .ssh/known_hosts as the gogs user
- I have `ssh-keygen -b 4096` and added the pubkey to github

I push, nothing happens

**Comment by dalareo** [comment]
Are you using Gogs as Git user?

**Comment by dalu** [comment]
see "update:" aok

I push to gogs and gogs pushes to github. all good.

**Comment by GwynethLlewelyn** [comment]
I just wanted to mention that the checklist provided by @dalu works so flawlessly that it ought to be part of the official gogs documentation! Is there any way we can alert the documentation maintainers?

**Comment by thejmazz** [comment]
You can also use a personal access token with repo access, and then your post-receive hook like so:

```bash
#!/bin/bash
git push --mirror https://<token>@github.com/<user>/<repo>.git
```

**Comment by dalareo** [comment]
Thats's just my strategy to have repos synced, but it does no work from the browser, only with client ```git push```

**Comment by thejmazz** [comment]
Hmm yeah, but it is known issue in https://github.com/gogits/gogs/issues/4338, so we just need to wait patiently :)

**Comment by LeOSW42** [comment]
Here is a simple how-to for stupid people:

On your Gogs server:

    root@server# sudo -i -u gogs
    gogs@server$ ssh-keygen -b 4096 # Do not enter any password
    gogs@server$ cat /home/gogs/.ssh.id_rsa.pub # Copy following line

On your Github account:

 * Add a new SSH key by pasting clipboard content
 * Create a new empty repository and copy the ssh clone URL

On your Gogs project page:

 * In settings > hooks > post-receive: (replace URL by the previously pasted one)

```
#!/bin/bash
git push --mirror git@github.com:dalu/forum.git
```

On any computer containing a clone, run:

```
$ git commit --allow-empty -m "test git hook"
$ git push
...
remote: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
remote: To git@github.com:dalu/forum.git
remote:    ebe061f..5d43139  master -> master
...
```

*A stupid guy.*

**Comment by dalu** [comment]
Well, don't just push to my dalu/forum.git repo ;)
If you @LeOSW42 could replace `dalu/forum` with `user/reponame`?

**Comment by xiayhub** [comment]
@Unknwon Just want to point out that all 3 hooks currently exposed through front-end are server side hooks.  None of them are invoked when a merge happens through pull request.

**Comment by Unknwon** [comment]
@xiayhub hmm... ? The known problem is custom hooks are not called when use web editor, not default ones. You may need to file a formal issue report with more details.

**Comment by stealthybox** [comment]
@Unknwon ,
What @xiayhub is saying is that `post-receive` doesn't run when you merge a pull request.
If you're using `post-receive` to sync to GitHub, it won't sync when you merge PR's.

I tried getting around this by manually installing `post-commit` and `post-merge` into the repo, but that didn't seem to work either.

I'll open an issue.

**Comment by DanTulovsky** [comment]
Fyi, you can also use https and a token.  On github, generate a token:

https://github.com/settings/tokens

Then the git hook becomes:

#!/bin/bash
git push --mirror https://TOKEN@github.com/USER/REPO.git

This way you don't need to mess with ssh keys. Of course, anyone who can see the git hooks in gogs, can see the token.. so be careful.

**Comment by DanTulovsky** [comment]
Err, although that works from the command line, gogs give me:

remote: fatal: unable to access 'https://TOKEN@github.com/DanTulovsky/playground.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
remote: Gogs: Internal error
