### ISSUE TITLE
file names with double quotation mark make the repo inaccessible

### ISSUE THREAD

**Issue by spamwax** [gogits/gogs#966]
Steps to reproduce:
```bash
touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin gogs@example.com:you/repo.git
git push -u origin master
```
At this point I can access the repo.

```bash
touch "\"fn with quotes\""
git add .
git commit -m "second commit"
git push origin master
```
Now when visiting the repo on `git.example.com/you/repo` produces a 500 error!

**Comment by Unknwon** [comment]
Thanks your feedback! Looks like rare situation we haven't thought about, we'll get on this ASAP.

**Comment by Unknwon** [comment]
Hi @spamwax , hope you're still there. This is been fix in `develop` and you can test it on https://try.gogs.io/unknwon/issue-966
