### ISSUE TITLE
panic: template: repo/commits_table:35: function "RenderCommitMessage" not defined

### ISSUE THREAD

**Issue by spx** [gogits/gogs#967]
latest version go 1.4.1

**Comment by Unknwon** [comment]
How did you install Gogs?

**Comment by spx** [comment]
git pull fetched new version and i got this error. 
git fetch
go build gogs.go

**Comment by Unknwon** [comment]
`master` branch?

**Comment by spx** [comment]
yep

**Comment by spx** [comment]
$ git branch
* master
$ git log -n 3
commit d85366930c94145c8f1119ff0b6bb95d77c5200e
Author: Unknwon <u@gogs.io>
Date:   Mon Feb 16 02:51:39 2015 -0500

    update travis.yml

commit f625665d8d72fdc4d2ce28a88aaaf01eaf5c2370
Author: Unknwon <joe2010xtmf@163.com>
Date:   Sat Feb 14 17:49:33 2015 -0500

    modules/setting: add abs path check before add workdir prefix

commit d047811c1a34640c5de751b638f1cb477fd595bc
Merge: 685ed1f 8c19861
Author: 无闻 <u@gogs.io>
Date:   Sat Feb 14 17:07:38 2015 -0500

    Merge pull request #956 from bpollack/docfix
    
    Fix a bunch of small typos and formatting quirks
$ go build gogs.go
$ ./gogs web
2015/02/18 11:55:48 [T] Custom path: /Users/mindaugas/tmp/go/gogs/custom
2015/02/18 11:55:48 [T] Log path: /Users/mindaugas/tmp/go/gogs/log
2015/02/18 11:55:48 [I] Gogs: Go Git Service 0.5.13.0214 Beta
2015/02/18 11:55:48 [I] Log Mode: File(Trace)
2015/02/18 11:55:48 [I] Cache Service Enabled
2015/02/18 11:55:48 [I] Session Service Enabled
2015/02/18 11:55:48 [I] Mail Service Enabled
2015/02/18 11:55:48 [I] Register Mail Service Enabled
2015/02/18 11:55:48 [I] Notify Mail Service Enabled
2015/02/18 11:55:48 [I] Run Mode: Production
panic: template: repo/commits_table:35: function "RenderCommitMessage" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0xe19400, 0xc20836b570, 0x0)
	/usr/local/go/src/html/template/template.go:304 +0x50
github.com/Unknwon/macaron.compile(0xc208256e10, 0x26, 0x0, 0x0, 0xc208243420, 0x2, 0x2, 0xc2081cb9d0, 0x1, 0x1, ...)
	/Users/mindaugas/gocode/src/github.com/Unknwon/macaron/render.go:245 +0x400
github.com/Unknwon/macaron.(*templateSet).Set(0xc208256ea0, 0x83fdd0, 0x7, 0xc208262000, 0x0)
	/Users/mindaugas/gocode/src/github.com/Unknwon/macaron/render.go:270 +0x51
github.com/Unknwon/macaron.renderHandler(0xc208256e10, 0x26, 0x0, 0x0, 0xc208243420, 0x2, 0x2, 0xc2081cb9d0, 0x1, 0x1, ...)
	/Users/mindaugas/gocode/src/github.com/Unknwon/macaron/render.go:337 +0x248
github.com/Unknwon/macaron.Renderer(0xc2081e5370, 0x1, 0x1, 0x0, 0x0)
	/Users/mindaugas/gocode/src/github.com/Unknwon/macaron/render.go:374 +0xea
github.com/gogits/gogs/cmd.newMacaron(0xdfbb0)
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/cmd/web.go:122 +0x6a2
github.com/gogits/gogs/cmd.runWeb(0xc2080ea180)
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/cmd/web.go:169 +0x34
github.com/codegangsta/cli.Command.Run(0x869630, 0x3, 0x0, 0x0, 0x8c6170, 0x15, 0x992510, 0x64, 0x0, 0x0, ...)
	/Users/mindaugas/gocode/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc20801fd40, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/Users/mindaugas/gocode/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
	/Users/mindaugas/tmp/go/gogs/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2080675c0)
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/mailer/mailer.go:52 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/mailer/mailer.go:46 +0xea

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208174740)
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 52 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208056140)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 53 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc2080ee840)
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/cron/cron.go:162 +0xa65
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/cron/cron.go:137 +0x3d

goroutine 54 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2082547c0)
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/Users/mindaugas/gocode/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 89 [chan send]:
text/template/parse.lexSpace(0xc208360b80, 0x9f15b8)
	/usr/local/go/src/text/template/parse/lex.go:339 +0xdd
text/template/parse.(*lexer).run(0xc208360b80)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

**Comment by Unknwon** [comment]
Thanks your feedback, I would suggest you completely delete source code and re-pull form GitHub see if problem remains.

**Comment by spx** [comment]
same problem

**Comment by Unknwon** [comment]
Can you try `go get -u -v` under Gogs source code root directory and recompile?

**Comment by spx** [comment]
ok. fixed problem :)

**Comment by Unknwon** [comment]
cool. :scream::scream:
