### ISSUE TITLE
Inconsistent Display of repositories in Organization

### ISSUE THREAD

**Issue by Sauermann** [gogits/gogs#969]
I have the following setup:
- Organization "O"
- User "U" who is not a member of organization "O"
- Organization "O" has a non-private repository "R"
- Organization "O" has a private repository "P" with user "U" as a collaborator

When user "U" looks at the organization site of organization "O" ("gogs.example.com/org/O") that usually shows the repositories of this organization, both repositories "R" and "P" are not listed there.

I would expect that either
- the repositories "R" and "P" are displayed on the organization "O" site for user "U" or
- user "U" can not access the overview site of organization "O".

If I could set a priority to this issue, it would be very low.

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
