### ISSUE TITLE
API support for adding SSH keys

### ISSUE THREAD

**Issue by Xe** [gogits/gogs#976]
I'd like to have a program automatically add SSH keys to a gogs instance. Would it be possible to do this via the API?

**Comment by Unknwon** [comment]
Sure, we can make an API for this.

**Comment by kernel164** [comment]
+1

**Comment by kernel164** [comment]
gogs is cool! This is the only api which blocks me from using gogs. The api exposed in gogs is very limited and for now I was able to use phantomjs to script most of functionalities but not this one.
gogs supports only logged-in user to add the ssh key manually.

I desperately need this OR (at least a way to add ssh key by admin for any user - I could use phantomjs to script). I would like to contribute if this is not in your priority list.

**Comment by Unknwon** [comment]
@kernel164 APIs for deploy keys have been implemented, this one should be very similar. I'll do it ASAP.

**Comment by kernel164** [comment]
cool cool cool! --- Thank you.

**Comment by kernel164** [comment]
Thanks in advance. Any timeline for this fix? Will this be in next release. When will be the next release.

**Comment by Unknwon** [comment]
No guaranteed timeline, but after wiki is finished.

**Comment by Unknwon** [comment]
@kernel164 it's now possible on `develop` branch and https://try.gogs.io 

Documentation: https://github.com/gogits/go-gogs-client/wiki/Users-Public-Keys

**Comment by kernel164** [comment]
@Unknwon Thank you very much.

As per the doc - https://github.com/gogits/go-gogs-client/wiki/Users-Public-Keys 
It looks like admin user can't set ssh for other users. for example 
- POST /users/:username/keys  (add ssh key for an user - by admin)
- GET /users/:username/keys/:id (get ssh key for an user - by admin)
- DELETE /users/:username/keys/:id (delete a ssh key for an user - by admin)
I may be wrong. Please let me know if this is also possible.

This api is available I guess - 
- GET /users/:username/keys (list all ssh keys of an user - by admin)

**Comment by Unknwon** [comment]
@kernel164 Yes, you're right. The APIs should be called by user.

I'll add some APIs for admin.

**Comment by Unknwon** [comment]
I think all you need is:

> POST /users/:username/keys (add ssh key for an user - by admin)

Others can be operate by unique key `id`.

**Comment by Unknwon** [comment]
See https://github.com/gogits/go-gogs-client/wiki/Users-Public-Keys#create-a-public-key-for-user

**Comment by kernel164** [comment]
Oh thank you! cool! 
its hard to build for RHEL 6.6 with restricted proxy.
would there be any quick release for this.

**Comment by Unknwon** [comment]
@kernel164 Planned a release around Dec 18th... two weeks..hmm...

**Comment by kernel164** [comment]
@Unknwon hmm OK. Will that include other HTTP Rest apis - https://github.com/gogits/gogs/issues/1692#issuecomment-159720250
If these are included that would toooo cool.

- create user under the auth source -- by admin
- create org -- by admin
- create team under the org -- by admin
- add user to team -- by admin
- add repo to team -- by admin

**Comment by Unknwon** [comment]
#1692 contains quite a lot APIs, I will priority your needs first.

**Comment by kernel164** [comment]
Thank you.
