### ISSUE TITLE
Very slow responses.

### ISSUE THREAD

**Issue by nd2s** [gogits/gogs#980]
Response time is very bad here. I have to wait from multiple seconds to multiple minutes on nearly every request (a few requests return almost instantly though). System seems to be fully functional, though. Everything was slow from the very beginning ( = /install).

I don't know what part is causing the problem. I can't see anything in logs. There are no errors reported. I have the feeling it has something to do with db access, but that's pretty much a shot in the dark.

Running version with latest commit from master (d85366930c94145c8f1119ff0b6bb95d77c5200e) on FreeBSD with PostgreSQL, serving with nginx.

Any ideas what could cause that or how I can debug?

**Comment by Unknwon** [comment]
Thanks for your feedback!

- is it slow when you execute git command in terminal?
- do you have virus check app or something similar?
- what's your system hardware?

**Comment by nd2s** [comment]
It's running on a production server: i7-4770 haswell quad-core, 32gb ddr3 ram, 1gb/s connection. There is certainly no antivirus or virus on a FreeBSD server :).

All systems are running well, it has to be an issue with this daemon.

**Comment by Unknwon** [comment]
Hmm... looks like there is no reason to be slow on this machine. :joy:

- What is the time show in the bottom of the page?
- Do you say it is slow even for the installation page?

**Comment by nd2s** [comment]
Page and template times are normal. 0-35ms mostly. It takes some (long) time before I can see the request in the (stdout) logs, after that the page immediately gets processed and returned.

Yes, it was slow on installation page. When saving settings. That's why I was suggesting it could have been related to the db connection.

But nevermind, I just solved it: I checked nginx logs again after I got some gateway timeouts and saw the the localhost ipv6 address being used. Seems nginx randomly tried using ipv6 for connecting to the daemon listening on ipv4 because I used "localhost" as a hostname. I changed it to 127.0.0.1 and it's working now.

Sry for the trouble and thanks for the quick response.

**Comment by Unknwon** [comment]
Wow, great! I should add this to troubleshooting, thanks you!

**Comment by AysadKozanoglu** [comment]
i have also the problem that gogs web und git push are very slow (waiting of something)

on fresh debian 8.8 jessie i started ./gogs from the extracted .tar.gz than i open the regular link http://:3000

gogs needs Page: 40071ms Template: 30031ms
Gogs Version: 0.11.19.0609 Page: 40071ms Template: 30031ms

i can not solve the issue with the performance. debian and gogs are fresh installed (nothing else) all settings are by default.

**Comment by AysadKozanoglu** [comment]
i solved my issue by looking logs.  gogs try to solve the avatar against (@gmail or what else you type)  and hangs :-)  

on first gogs installation  i disabled the avatar. now it is very quickly ;-)

thanks a lot for  alle gogs developers that i can use so nice open source solution.

**Comment by mrcancer91** [comment]
Thank you @AysadKozanoglu ,your tip really saved me. I've been having the headache for weeks because the system suddenly got really slow when entering the commits page. 
Just curious, how do you find that solution?
