### ISSUE TITLE
Organisations: cannot change name to upper case.

### ISSUE THREAD

**Issue by nd2s** [gogits/gogs#981]
I cannot directly change name or organisation "test" to "Test". It's complaining about resource name already being used. That doesn't seem right.

**Comment by Unknwon** [comment]
Thanks for the report! We'll get on this ASAP.

**Comment by Unknwon** [comment]
Hi @nd2s , I've pushed fix on `dev` branch and you can also test on https://try.gogs.io/

**Comment by nd2s** [comment]
That was quick. Thank you!

**Comment by Unknwon** [comment]
@nd2s no problem!
