### ISSUE TITLE
Gogs: you are not the owner of SSH key

### ISSUE THREAD

**Issue by iMac0de** [gogits/gogs#983]
Hi guys !

I need your help because I don't understand this error...

I have my admin user IMACODE with this an SSH Key (I check in the database).

But when I want git clone a project, I get this error "Gogs: you are not the owner of SSH key". My project is in organization, and my admin user is the owner of the organization.

Thanks for your help :-)

**Comment by Unknwon** [comment]
Hi there, thanks your feedback!

Did you add SSH key through Gogs web UI?

**Comment by iMac0de** [comment]
Hi,

Yes, only by that way.

**Comment by Unknwon** [comment]
This error happens when user ID recorded in SSH key file is not match your user ID in Gogs database.

**Comment by iMac0de** [comment]
Ok, I removed keys in database and /home/gogs/.ssh/authorized_keys and add ssh key to my account again. It's seems works!

But now, git clone ask me the password for gogs user. What is this password ?

**Comment by Unknwon** [comment]
> But now, git clone ask me the password for gogs user. What is this password ?

What is the command you used for git clone? Complete string please.

**Comment by iMac0de** [comment]
git clone ssh://gogs@git.imacode.net:1453/potternetwork/potternetwork-web.git

**Comment by Unknwon** [comment]
Would you mind to dump your  /home/gogs/.ssh/authorized_keys file?

**Comment by iMac0de** [comment]
command="/opt/gogs/gogs serv key-9 --config='/opt/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvFUqy3j5jgn04E+aE1vRv7qM3RHcohlii0kpx/8eW6th2W6MaE18oM3lrAvGLxtcVkIw9hunvRoje4UrKgSO/NshNan22IXQl0JyiAUrTXhQrLIpFsIh2YvxUQ/96Y8DYAqN9pa1FC+/S+TS8asxXG71ElxToGZxzG6qik7jM9V8rFuTEIgPc+W09BriZ7xyo79Wxh0GJ0wrupMCW2YWyqEE39LGjRv1hpkh4K+lQCpnjmS7OWSChpDzfz/ruO2ikiz01OMmqp/H4n41KBeyiDo9LBKgOQRD7WjfqehCFmFADwXhzbvZXoE/0DQ0fDX8oh+lA02XhBxtQll2DFHQ1 jeremy.peltier@epitech.eu

**Comment by Unknwon** [comment]
Thanks!

If SSH asks for password means SSH server doesn't find match, your request hasn't even been passed to Gogs.

**Comment by iMac0de** [comment]
So, when the request will have been passed to Gogs ?

**Comment by Unknwon** [comment]
I don't know, I think it's local config problem with your SSH server.

**Comment by Unknwon** [comment]
Somehow your SSH server doesn't read/recognize the key in  /home/gogs/.ssh/authorized_keys file.

**Comment by iMac0de** [comment]
I uncomment this line AuthorizedKeysFile %h/.ssh/authorized_keys in /etc/ssh/sshd_config and restart ssh but it still does not work, have you any idea ?

**Comment by fzerorubigd** [comment]
If the permission is anything except 0600 , ssh refuse to read the .~/ssh directory. 
Verify that the ~/.ssh and all content inside that are 0600

**Comment by iMac0de** [comment]
My ~/.ssh permissions are drw------- and my ~/.ssh/authorized_keys permissions are -rw-------

**Comment by Unknwon** [comment]
Can you add SSH key normally to `gogs` user and try SSH login?

**Comment by iMac0de** [comment]
What do you mean by "normally" ?

**Comment by Unknwon** [comment]
Add a SSH key like you want to login your server with it.

**Comment by iMac0de** [comment]
What is the Gogs user password ?

**Comment by Unknwon** [comment]
I don't know what's the user password you create on your machine. :)

**Comment by uchti** [comment]
I have the same problem. Gogs change ownership on file authorized_keys. 
I use init.d script for debian and git user for start gogs but after start gogs i see in process list 

root     29946  0.0  0.1  64528  1772 ?        S    11:52   0:00 /bin/su - git -c cd "/opt/gogs" && /opt/gogs/gogs -- web
git      29947  0.0  0.1  20860  1628 ?        Ss   11:52   0:00 -su -c cd "/opt/gogs" && /opt/gogs/gogs -- web
root     29948  4.0  1.8 141736 18520 ?        Sl   11:52   0:00 /opt/gogs/gogs -- web

gogs run as root user and when i add new key from web interface, gogs changes owner on   /home/git/.ssh/authorized_keys

**Comment by uchti** [comment]
DeletePublicKey  changes owner  when user remove public key in web interface because  DeletePublicKey create new file and call rename

**Comment by Unknwon** [comment]
@uchti run Gogs on root is not a wise choice, and you may never able to log in with SSH to access your machine again...

**Comment by uchti** [comment]
@Unknwon  I know but how explain this situation on my vds server 

```
root@git ~ # su - git
git@git:~$ cd /opt/gogs/
git@git:/opt/gogs$ /opt/gogs/gogs web &
[1] 32140
git@git:/opt/gogs$ 2015/03/03 21:54:29 [T] Custom path: /opt/gogs/custom
2015/03/03 21:54:29 [T] Log path: /opt/gogs/log
2015/03/03 21:54:29 [I] git.etnix.net 0.5.13.0214 Beta
2015/03/03 21:54:29 [I] Log Mode: File(Trace)
2015/03/03 21:54:29 [I] Redis Enabled
2015/03/03 21:54:29 [I] Memcache Enabled
2015/03/03 21:54:29 [I] Cache Service Enabled
2015/03/03 21:54:29 [I] Session Service Enabled
2015/03/03 21:54:29 [I] Mail Service Enabled
2015/03/03 21:54:29 [I] Register Mail Service Enabled
2015/03/03 21:54:29 [I] Notify Mail Service Enabled
2015/03/03 21:54:29 [I] SQLite3 Enabled
2015/03/03 21:54:29 [I] Run Mode: Production
2015/03/03 21:54:29 [I] Listen: http://127.0.0.1:8080

git@git:/opt/gogs$ ps aux | grep gogs
root     32140  0.8  1.8 141736 18496 pts/0    Sl   21:54   0:00 /opt/gogs/gogs web
git      32151  0.0  0.0  11740   932 pts/0    S+   21:54   0:00 grep --color=auto gogs
```

**Comment by Unknwon** [comment]
> I know but how explain this situation on my vds server

Sorry, to explain what for the dump of `ps`?

**Comment by uchti** [comment]
/opt/gogs/gogs web running from root, but gogs was started from git user. 
how gogs can fork porcess from git to root user ?

**Comment by Unknwon** [comment]
> git@git:/opt/gogs$ /opt/gogs/gogs web &

Didn't you start in `git` user? So `/home/git/.ssh/` is the directory Gogs is modifying.

**Comment by uchti** [comment]
that's it, I start process as git and get the process from root. I can not understand how this is possible.

**Comment by Unknwon** [comment]
I would say this is a system-matter thing, I have not enough knowledge to answer you that.

**Comment by matt-h** [comment]
@uchti that is really odd. Gogs doesn't escalate permissions on it's own. I tested the same thing on mine and gogs always runs as the user it is started with.

In your config file, what do you have RUN_USER set to?
Is /opt/gogs/gogs the actual gogs binary or a script pointing to it?

**Comment by uchti** [comment]
Now i test on my dedicated server , no problem with permissions. maybe something is wrong with VDS

**Comment by uchti** [comment]
I found the answer
```
ls -all  /opt/gogs/gogs
-rwsr-sr-x 1 root git 23729252 Feb 20 08:06 /opt/gogs/gogs
```
Gogs owner was root user, but group git. 
And git can start gogs but process have root permissions. 
I fix it.
```  
chown git:git -R /opt/gogs
```

**Comment by Unknwon** [comment]
@uchti cool!

So the problem is:

because Gogs runs under root, then it tries to match wrong SSH key file for you.

Do my observation correct?

**Comment by uchti** [comment]
In my case, gogs run under git user but process have permissions root and when any web user delete any public key, gogs change owner from git user on /home/git/.ssh/authorized_keys to root user.

**Comment by Unknwon** [comment]
@uchti I see, is your problem solved?

**Comment by uchti** [comment]
Because func DeletePublicKey  in models/publickey.go overwrites the file instead of to remove the line.

Yes, my problem solved. Thanks

**Comment by Unknwon** [comment]
> Because func DeletePublicKey in models/publickey.go overwrites the file instead of to remove the line.

It was used to remove a line, but turns out that's not robust(once wrong, always wrong). So overwrite entire file based on database is more robust.

**Comment by uchti** [comment]
agree that the current version is more reliable

**Comment by Unknwon** [comment]
@iMac0de  Is this problem solved  in current version or still occurs?

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion. :dizzy:

**Comment by ByteM3** [comment]
I'm testing Gogs on Debian Jessie x64 minimal. It seems that I'm having the same issue.
Here my case:
 - Gogs is installed to /home/git/gogs/
 - Current Gogs user has 2 pub-keys (actually there is just 1 organization and 2 users)
 - Repositories are located under /home/git/gogs/repos/
 - ~/.ssh/authorized_keys seems normal, (4 drw-------  2 git  git  4096 Oct 27 01:31 .ssh)
- To change  the permission(s) of ~/.ssh/authorized_keys didn't helped
 - On the client computer for example: $ git push -u origin master
       -->  Will ask for git@server password in terminal
 - Adding a new user with new keys did't help.

**Comment by Unknwon** [comment]
@ByteM3 try admin dashboard, click `regenerate ~/.ssh/authorized_keys file`.

**Comment by vignolet** [comment]
I'm testing Gogs on Docker hypriot/rpi-gogs-raspbian. It seems that I'm having the same issue.
On the client computer : $ git push -u origin master --> Will ask for git@server password in terminal.
regenerate ~/.ssh/authorized_keys file  don't help.

**Comment by Unknwon** [comment]
> regenerate ~/.ssh/authorized_keys file

How did you regenerate?

**Comment by vignolet** [comment]
In admin > click on button regenerate ~/.ssh/authorized_keys

**Comment by Unknwon** [comment]
OK, check if file permission is 600

**Comment by vignolet** [comment]
ls -la /home/git/.ssh/
-rw------- 1 git git 1609 Nov 19 18:10 authorized_keys

**Comment by Unknwon** [comment]
Please check your SSH auth.log

**Comment by vignolet** [comment]
I think the problem is with the ssh port redirection docker container. I will ask creator hypriot / rpi-gogs-Raspbian. Thank you

**Comment by Unknwon** [comment]
@vignolet OK.. I did a quick search seem like last updated was 5 months ago..

**Comment by vignolet** [comment]
I found 
http://stackoverflow.com/questions/1558719/using-a-remote-repository-with-non-standard-port
and 
http://serverfault.com/questions/218256/specify-ssh-port-for-git

**Comment by Unknwon** [comment]
@vignolet thanks your info! Does that solve your problem?

**Comment by vignolet** [comment]
@Unknwon Yes, thx

**Comment by Unknwon** [comment]
@vignolet that's cool!
