### ISSUE TITLE
Installation gogs problem suburl This page contains redirect loop

### ISSUE THREAD

**Issue by mukaiu** [gogits/gogs#984]
gogs Version: 0.5.13
go 1.4

Today gogs want to install suburl.chrome prompted 'This page contains a redirect loop.'
root_url 192.168.1.3:3000/gogs, the page redirects to stop http://192.168.1.3:3000/gogs/install.
Root path no problem. Are there friends have the same problem?

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

Suburl tends to work with Nginx/Apache reverse proxy, if you literally add a Suburl, that's not gonna work.

**Comment by mukaiu** [comment]
Thank you, using nginx reverse proxy installed properly.

**Comment by Unknwon** [comment]
No problem!
