### ISSUE TITLE
Filename cut off in DIFF when containing spaces

### ISSUE THREAD

**Issue by jpxd** [gogits/gogs#985]
Hi!

In the file diff for a commit, the filename is cut off if the path contains spaces...

![screenshot 2015-02-24 09 10 38](https://cloud.githubusercontent.com/assets/10384363/6345320/2d1ae418-bc05-11e4-8783-bbac12c8e62a.png)

E.g. here the filename should be "OSG App/Api.swift" but only "OSG" is displayed.

Please fix this :) 
The gogs diff is practically unusable for this project right now...

**Comment by Unknwon** [comment]
Thanks for the report, we'll get on this ASAP!

**Comment by jpxd** [comment]
I'm not familiar with GO, so I can't submit a pull request, but I believe the problem is here with the Split statement:

https://github.com/gogits/gogs/blob/767bf82eabed0fede7bbdb5f5b1c75898c6ff00d/models/git_diff.go#L170-174

**Comment by Unknwon** [comment]
@jpxd thanks for the tip, looks right!

**Comment by Unknwon** [comment]
Should be fixed by https://github.com/gogits/gogs/pull/1404 and can be now tested on https://try.gogs.io

**Comment by Unknwon** [comment]
Close with new release but open for continuing discussion. :dizzy:
