### ISSUE TITLE
Add Operation to check & correct label counts

### ISSUE THREAD

**Issue by nicolai86** [gogits/gogs#986]
#933 showed that there were some ways to reach an inconsistent state, where the label isssue counts were not in sync with reality.

The fix only applies for the uncorrupted situations so we might want to add an operation in the administrative area where admins can fix existing corruption.

@Unknwon would a PR which adds this Operation in the administrative area get in? We could also increase the scope to also check milestone status, etc. like a general "check system health" operation.

**Comment by Unknwon** [comment]
Hi @nicolai86 , I've pushed some changes on `develop` which make label count check in a cron task: https://github.com/gogits/gogs/blob/6235bd1fe9ed15c9a889f72e4fe2880189963306/models/repo.go#L1257-L1271

If you want, you can use it as a template to make more functions like you said, milestone check.

**Comment by nicolai86** [comment]
Thanks @Unknwon for keeping me in the loop. I'll try to take a look at this in the following days.

**Comment by Unknwon** [comment]
@nicolai86 thanks for following up after long pause of this ticket :stuck_out_tongue_closed_eyes:

**Comment by nicolai86** [comment]
Sure. Keep up the good work & thanks for continuing on gogs!

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close now but open for continuing discussion.
