### ISSUE TITLE
GetRepoLink already contains AppSubUrl.

### ISSUE THREAD

**Issue by mukaiu** [gogits/gogs#988]
GetRepoLink already contains AppSubUrl,
gogs/templates/user/dashboard/feeds.tmpl
Multiple lines
{{$ .i18n.Tr "action.create_repo" AppSubUrl .GetRepoLink .GetRepoLink | Str2html}}

AppSubUrl splicing leads twice

To generate the url /gogs//gogs/mukaiu/test
gogs for suburl

**Comment by Unknwon** [comment]
Thanks your report!

**Comment by Unknwon** [comment]
Hi @mukaiu , I've pushed code to `master` to fix this issue, please help test!

**Comment by robince** [comment]
This is has fixed the issue for me in the dashboard view for username, branch, repository and "view comparison of these commits".
But the link for the actual commit still has the problem (host.com/gogs//gogs/user/repo/...).

It was only in dashboard news feed I saw the problem... once navigating within a repository everything seems to work.

I am running on host.com/gogs via Apache with RewriteRule (I couldn't get it to work with ProxyPass):

    RewriteEngine On
    RewriteRule ^/gogs/(.*) http://127.0.0.1:6000/$1 [P]
    ProxyPassReverse /gogs http://127.0.0.1:6000/

**Comment by Unknwon** [comment]
@robince thanks for the feedback!

I've repushed fix on `master` for the problem you described. Please help test again, thanks!

**Comment by robince** [comment]
That's fixed it - all links seem to be working correctly in dashboard and with the rest of the site. Thanks very much!

**Comment by Unknwon** [comment]
@robince awesome, thanks for quick feedback!

**Comment by Unknwon** [comment]
cc @mukaiu

**Comment by mukaiu** [comment]
now test

**Comment by Unknwon** [comment]
Watching...

**Comment by mukaiu** [comment]
@Unknwon test pass!
