### ISSUE TITLE
Web view not updated if repo is created empty

### ISSUE THREAD

**Issue by captbrogers** [gogits/gogs#989]
If I create a repository without a readme, license, or gitignore file, any updates I make do not show up in the web view though I am able to use the repository between machines as I normally would.

I run Gogs on it's normal port using ./gogs web, then proxy to it with Nginx. In the logs that are printed to stdout for Gogs, there are no errors.

Server: Fedora 21 x86_64
Go: 1.3.3
Gogs: 0.5.13.0212 Beta

**Comment by Unknwon** [comment]
Hi @captbrogers , thanks your report!

But I have some questions first:

- Which way did you use to push your code? HTTP or SSH?
- Did you move the Gogs binary after you create the repository?
- Does activity timeline is updating?
- What's the binary path of Gogs?
- What's the content of `path/to/<repo_root_path>/<username>/<reponame>.git/hooks/update` ?

**Comment by captbrogers** [comment]
- Which way did you use to push your code? HTTP or SSH?
SSH. I am using a custom port, and I do have to use the full path, it doesn't seem to start in git's home directory. The origin URL is:
ssh://git@mygitserver.com:<port>/home/git/gogs-repositories/<username>/<reponame>.git

- Did you move the Gogs binary after you create the repository?
No, it was not moved at all.

- Does activity timeline is updating?
No, the activity timeline does not reflect any updates to that repository.

- What's the binary path of Gogs?
/home/git/gogs/gogs

- What's the content of path/to/<repo_root_path>/<username>/<reponame>.git/hooks/update ?
``#!/usr/bin/env bash
"/home/git/gogs/gogs" update $1 $2 $3 --config='/home/git/gogs/custom/conf/app.ini'``

**Comment by phsmit** [comment]
It seems you have added your ssh key by hand to the gogs user, or are using ssh with a password. If the ssh connection would be through gogs it would never need (or actually can't use) the full path.

Could you remove your plain ssh-key from .ssh/authorized_keys and add it through the gogs web interface?

**Comment by Unknwon** [comment]
@phsmit made the point.

@captbrogers , you should push your code like `ssh://git@mygitserver.com:<username>/<reponame>.git`

**Comment by captbrogers** [comment]
That did seem to be the problem, conflicting data in /home/git/.ssh/authorized_keys

I removed the the line that was not added by Gogs, and without changing anything else or restarting the application, it began working as expect. Thanks guys!
