### ISSUE TITLE
Local git repos

### ISSUE THREAD

**Issue by outrunthewolf** [gogits/gogs#99]
We have a git server running already. Is it possible to migrate existing local repositories into gogits?
#question

**Comment by Unknwon** [comment]
Hi all, just pushed code to `dev` branch that supports migrate repository by local path: https://github.com/gogits/gogs/commit/059338139ca4a70cb1138dc09039abb5dac0d0f2

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Comment by boarpig** [comment]
Is this feature implemented in gogs 0.6 and how do I use it? I upgraded my server but I found no clue how to do this, except for single repo migration

**Comment by Unknwon** [comment]
@boarpig type server absolute path where you type HTTP/HTTPS address, web UI is one repo migration at a time. see http://gogs.io/docs/features/migrate.html

**Comment by boarpig** [comment]
hmm, I think I'll write a migration script and migrate all my repos that way. I'm guessing the server will return an error if a repo with that name already exists, right?

**Comment by Unknwon** [comment]
@boarpig right, same behave as web UI, except returns JSON.

**Comment by matt-h** [comment]
@boarpig there are a couple migration scripts out there that might be useful as a starting point:
https://github.com/valeriangalliat/gogs-migrate
https://github.com/girvo/bitbucket-to-gogs-migrator

**Comment by Unknwon** [comment]
@matt-h very helpful tips! I should add them to docs.

**Comment by boarpig** [comment]
@matt-h thank you for your answer. I did look into those, the first one does migration from github and other one from bitbucket. I'm going to do about 40 repository migration from my local server so I'm going to write a short script to do that. Thank you for your effort though, I appreciate it!

**Comment by cb88** [comment]
http://gogs.io/docs/features/migrate.html

Doesn't seem to exist? How does one migrate a repo now? I have a couple local repos created manually.... and I'd like to import them.

**Comment by Unknwon** [comment]
@cb88 see https://github.com/gogits/go-gogs-client/wiki/Repositories#migrate

**Comment by cb88** [comment]
Thanks, actually I was just looking for the migrate page... I hadn't noticed it in the months I've been using gogs :/ ... it worked great though!
