### ISSUE TITLE
建议：创建Repo时默认为Private 

### ISSUE THREAD

**Issue by Tomasen** [gogits/gogs#993]
特别是企业应用中，目前默认是public的，误操作的话很受伤。

或者至少conf里面可以有个选项

**Comment by wanghm** [comment]
+1

**Comment by Unknwon** [comment]
Thanks your feedback!

I think it's the same as the https://github.com/gogits/gogs/issues/965 

You can `+1` on that one :stuck_out_tongue_closed_eyes:
