### ISSUE TITLE
BUG: LDAP通过GOGS修改邮箱和密码后账号混乱

### ISSUE THREAD

**Issue by tomasen** [gogits/gogs#994]
GOGS配置为LDAP登录。用LDAP登录后，把邮箱用户名换掉，再用LDAP登录，又给注册了一个新号。

同时用LDAP登录后，密码修改后，是不承认新的密码的。

建议：账号使用LDAP登录时禁止修改邮箱和密码

**Comment by Unknwon** [comment]
Thanks your feedback, this is a critical issue I believe!

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/1938
