### ISSUE TITLE
How to install it in openshift?(a free PAAS)

### ISSUE THREAD

**Issue by tvvocold** [gogits/gogs#996]

**Comment by tvvocold** [comment]
according this [cart](https://github.com/smarterclayton/openshift-go-cart),i 
```
$rhc create-app mygogs https://cartreflect-claytondev.rhcloud.com/reflect?github=smarterclayton/openshift-go-cart
$vi .godir 
>github.com/gogits/gogs

then what should i do?

**Comment by Unknwon** [comment]
Hmm, hi @tvvocold , thanks for asking, but we really have zero knowledge with OpenShift.

May take a long time to figure out how to install Gogs on it.

**Comment by dsimansk** [comment]
Well, I think you can start with forking Clayton's go-cart and adding gogs code to template dir. @Unknwon is it possible to inject env variables to app.ini file, it would very useful because OpenShift provides everything needed in $OPENSHIFT_* vars. I've managed to get setup web page running, but failed on dir write permission as OpenShift is a bit strict about where and what :) I'll give it a try later.
BTW, the gogs project looks awesome.

**Comment by dsimansk** [comment]
Nevermind the env var part, I can solve this by creating app.ini.erb where OpenShift will parse on and translave env vars on startup.

**Comment by Unknwon** [comment]
@dsimansk cool! Ping me if I can help anything!

**Comment by dsimansk** [comment]
OK, I've managed to get go cartridge running with gogs out of the box. However, I'm stuck on install page, where I'll always get error msg "Run user isn't the current user:...". Any ideas, I've set uid by the OpenShift user, which is runnig the process. 

If someone is willing to try it:
```
 rhc app create gogs https://raw.githubusercontent.com/dsimansk/openshift-go-cart/master/metadata/manifest.yml
```

**Comment by Unknwon** [comment]
@dsimansk 

> "Run user isn't the current user:..."

Try set an env var `USER`.

**Comment by tvvocold** [comment]
@Unknwon 
I had check in openshift by run `$rhc ssh gogs && env | grep USER` and i believe the default var in @dsimansk cart is right.
and reset is not allowed in openshift.
```
$ rhc set-env USER=whatever -a gogs 
Setting environment variable(s) ... USER cannot be overridden
```
Anyidea?

**Comment by Unknwon** [comment]
@tvvocold thanks for the tip, wasn't aware of it.

So can you at least get whatever the user name is?

**Comment by dsimansk** [comment]
Yep, the USER var is set by OpenShift and it identifies also belonging gear, so it can't be changes. It looks like this:
````
[gogs-dsimansk.rhcloud.com 550aa38fe0b8cd445b00018d]\> echo $USER
550aa38fe0b8cd445b00018d
````

**Comment by Unknwon** [comment]
@dsimansk so the user you set is `550aa38fe0b8cd445b00018d` on the `/install` page?

**Comment by tvvocold** [comment]
@Unknwon I think so, in my is 550aae7b5973ca4a5d00007f.

**Comment by dsimansk** [comment]
@Unknwon it's generated by OpenShift under the hood. Can't be modifies on user side.

**Comment by Unknwon** [comment]
@dsimansk Hmm... I mean you set `Run User` in `/install` page to this value `550aa38fe0b8cd445b00018d `? And it complains about run user not match?

**Comment by tvvocold** [comment]
@Unknwon Or u can test it by 
1.  Create an account on [OpenShift](https://www.openshift.com/app/account/new) for free then install [the OpenShift Client Tools](https://developers.openshift.com/en/managing-client-tools.html).
2.  ` $rhc app create gogs https://raw.githubusercontent.com/dsimansk/openshift-go-cart/master/metadata/manifest.yml `
3. Open `/install` page

**Comment by dsimansk** [comment]
@Unknwon yes, exactly, I've used value from $USER var and the /install page complains.

**Comment by Unknwon** [comment]
@tvvocold @dsimansk thank you both, let try it first.

**Comment by Unknwon** [comment]
Hmm.. what is the default MySQL connection address..?

**Comment by Unknwon** [comment]
Never mind, figure that out.

So how does this thing work, why I have a local copy of Gogs? Does anything I do affect on the server?

**Comment by dsimansk** [comment]
You need to get it from env var OPENSHIFT_MYSQL_DB_HOST, port is 3306. There is some hook needed to inject those into app.ini, because mysql cartridge is added after creation and build of go-cartridge, so those env vars aren't available in the meantime.

**Comment by tvvocold** [comment]
@Unknwon Yeah, that's when u could change the local data then `$git push`.(The git push command sends the local application data to the remote repository and automatically deploys the application.)
Here is the [doc](https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/User_Guide/chap-Build_and_Deployment.html) that might be helpful.

**Comment by Unknwon** [comment]
@tvvocold thanks a lot!

**Comment by tvvocold** [comment]
@dsimansk @Unknwon 
I think maybe the reason is the files' permission, On which file should i chmod + x?

**Comment by Unknwon** [comment]
@tvvocold thanks for the tip, @dsimansk and I get over the issue about `run user`, but now `git` doesn't recognize home directory correctly.

**Comment by tvvocold** [comment]
Nice! How do u guys get over that user issue? 
and what's does that mean? (git doesn't recognize home directory correctly.)

**Comment by dsimansk** [comment]
@tvvocold for some reason, when `USER` var was read by gogs as empty string. So I've set `USERNAME` var from the cartridge, because it's also check for the Win case. But that home directory might be a problem, I need to chat with @Unknwon about that.

**Comment by tvvocold** [comment]
@dsimansk @Unknwon 
Plz let me know if u got it run.
Thx!

**Comment by jstrachan** [comment]
BTW we've a kubernetes app for running gogs on OpenShift V3 / RHEL Atomic / GKE if you're interested.

Here's the kubernetes json to apply via the kubernetes CLI: http://central.maven.org/maven2/io/fabric8/jube/images/fabric8/gogs/

e.g. at the time of writing version 2.0.34 is the latest: http://central.maven.org/maven2/io/fabric8/jube/images/fabric8/gogs/2.0.34/gogs-2.0.34-kubernetes.json

**Comment by tvvocold** [comment]
@jstrachan 
That's cool! 
And i noticed that V3 hasn't been released, which means i need to docker run OpenShift V3 in my laptop?
If so, i would rather install gogs directly without OSv3 :smile: 
BTW, When will OSV3 will be released in the [cloud](http://www.openshift.com)?

**Comment by jstrachan** [comment]
@tvvocold not sure when OSV3 is going to be released online; there's a beta for on-premise out now.

Until OSV3 online is out you could try Google's GKE which implements Kubernetes?

**Comment by tvvocold** [comment]
@jstrachan 
Thx for your information.Maybe i'd like to try Google cloud someday.
BTW,when OSV3 goes online, what will happen to V2' gear? (delete?)

**Comment by jstrachan** [comment]
In OSV3 then each 'cartridge' is just a docker container - which is awesome; you can then use any docker image as a 'cartridge' OOTB. 

For V2 cartridges/gears then there's hopefully gonna be a migration script; certainly its not too hard to dockerize a V2 cartridge/gear really; the main differences stem around environment variables really & maybe long term migrating to maybe use a Dockerfile.

**Comment by tvvocold** [comment]
That's cool!
But i think container' security & performance both need to be beefed up before it in production.

**Comment by tkisme** [comment]
@tvvocold 
```
rhc app create gogs https://raw.githubusercontent.com/dsimansk/openshift-go-cart/master/metadata/manifest.yml
```

```
The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 55eef7d20c1e66c8230001cc -c "exec
/usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c4,c419' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log
2>&1\""' returned an error. rc=255

       First download, may take several minutes
-----> Installing Go 1.4.1... done
       Installing Virtualenv... done
       Installing Mercurial... done
       Installing Bazaar... done
-----> Running: go get -tags openshift ./...
# github.com/dsimansk/gogs/models
models/login.go:240: invalid argument mail (type bool) for len
models/login.go:241: cannot use uuid.NewV4().String() + "@localhost" (type string) as type bool in assignment
models/login.go:251: cannot use mail (type bool) as type string in field value
models/repo.go:1044: setting.Git.Fsck undefined (type struct { MaxGitDiffLines int; GcArgs []string "delim:\" \"" } has no
field or method Fsck)
# github.com/dsimansk/gogs/modules/cron
modules/cron/manager.go:18: setting.Webhook.TaskInterval undefined (type struct { QueueLength int; DeliverTimeout int;
SkipTLSVerify bool; Types []string; PagingNum int } has no field or method TaskInterval)
modules/cron/manager.go:19: setting.Git.Fsck undefined (type struct { MaxGitDiffLines int; GcArgs []string "delim:\" \"" } has
no field or method Fsck)
modules/cron/manager.go:20: setting.Git.Fsck undefined (type struct { MaxGitDiffLines int; GcArgs []string "delim:\" \"" } has
no field or method Fsck)
# github.com/dsimansk/gogs/modules/auth
modules/auth/auth.go:36: undefined: models.GetAccessTokenBySha
modules/auth/auth.go:38: type models.ErrAccessTokenNotExist is not an expression
modules/auth/auth.go:53: undefined: models.GetUserById
modules/auth/auth.go:54: type models.ErrUserNotExist is not an expression
modules/auth/auth.go:126: undefined: models.GetUserById
# github.com/dsimansk/gogs/modules/mailer
modules/mailer/mail.go:159: repo.Id undefined (type *models.Repository has no field or method Id)
modules/mailer/mail.go:170: undefined: models.GetUserById
# github.com/dsimansk/gogs/modules/middleware
modules/middleware/context.go:193: cannot use ctx.Context.Req.Request (type *http.Request) as type *macaron.Context in argument
to auth.SignedInUser
modules/middleware/org.go:37: type models.ErrUserNotExist is not an expression
modules/middleware/repo.go:253: repo.Id undefined (type *models.Repository has no field or method Id)
modules/middleware/repo.go:288: repo.GetForkRepo undefined (type *models.Repository has no field or method GetForkRepo)
modules/middleware/repo.go:323: repo.Id undefined (type *models.Repository has no field or method Id)
modules/middleware/repo.go:324: repo.Id undefined (type *models.Repository has no field or method Id)
# github.com/dsimansk/gogs/routers/admin
routers/admin/admin.go:232: undefined: cron.ListEntries
routers/admin/auths.go:69: unknown "github.com/gogits/gogs/modules/auth/ldap".Ldapsource field 'BaseDN' in struct literal
routers/admin/auths.go:70: unknown "github.com/gogits/gogs/modules/auth/ldap".Ldapsource field 'AttributeUsername' in struct
literal
routers/admin/auths.go:75: unknown "github.com/gogits/gogs/modules/auth/ldap".Ldapsource field 'MsAdSAFormat' in struct literal
routers/admin/auths.go:77: form.AuthName undefined (type auth.AuthenticationForm has no field or method AuthName)
routers/admin/auths.go:82: form.SmtpAuth undefined (type auth.AuthenticationForm has no field or method SmtpAuth)
routers/admin/auths.go:83: form.SmtpHost undefined (type auth.AuthenticationForm has no field or method SmtpHost)
routers/admin/auths.go:84: form.SmtpPort undefined (type auth.AuthenticationForm has no field or method SmtpPort)
routers/admin/auths.go:85: form.Tls undefined (type auth.AuthenticationForm has no field or method Tls)
routers/admin/auths.go:94: form.AuthName undefined (type auth.AuthenticationForm has no field or method AuthName)
routers/admin/auths.go:94: too many errors
# github.com/dsimansk/gogs/routers/org
routers/org/members.go:103: type models.ErrUserNotExist is not an expression
routers/org/org.go:62: form.Email undefined (type auth.CreateOrgForm has no field or method Email)
routers/org/org.go:68: assignment count mismatch: 2 = 1
routers/org/org.go:70: type models.ErrUserAlreadyExist is not an expression
routers/org/org.go:73: type models.ErrEmailAlreadyUsed is not an expression
routers/org/setting.go:41: form.OrgUserName undefined (type auth.UpdateOrgSettingForm has no field or method OrgUserName)
routers/org/setting.go:42: form.OrgUserName undefined (type auth.UpdateOrgSettingForm has no field or method OrgUserName)
routers/org/setting.go:50: form.OrgUserName undefined (type auth.UpdateOrgSettingForm has no field or method OrgUserName)
routers/org/setting.go:59: form.OrgUserName undefined (type auth.UpdateOrgSettingForm has no field or method OrgUserName)
routers/org/setting.go:60: form.OrgUserName undefined (type auth.UpdateOrgSettingForm has no field or method OrgUserName)
routers/org/setting.go:60: too many errors
# github.com/dsimansk/gogs/routers
routers/home.go:60: repo.Id undefined (type *models.Repository has no field or method Id)
routers/install.go:69: undefined: cron.NewCronContext
routers/install.go:218: cannot convert "on" to type bool
routers/install.go:218: invalid operation: form.RegisterConfirm == "on" (mismatched types bool and string)
routers/install.go:219: cannot convert "on" to type bool
routers/install.go:219: invalid operation: form.MailNotify == "on" (mismatched types bool and string)
routers/install.go:243: type models.ErrUserAlreadyExist is not an expression
# github.com/dsimansk/gogs/routers/repo
routers/repo/commit.go:206: ctx.Repo.CommitId undefined (type middleware.RepoContext has no field or method CommitId)
routers/repo/http.go:58: type models.ErrUserNotExist is not an expression
routers/repo/http.go:116: undefined: models.GetAccessTokenBySha
routers/repo/http.go:118: type models.ErrAccessTokenNotExist is not an expression
routers/repo/http.go:125: undefined: models.GetUserById
routers/repo/issue.go:78: undefined: models.GetMilestoneByIndex
routers/repo/issue.go:78: ctx.Repo.Repository.Id undefined (type *models.Repository has no field or method Id)
routers/repo/issue.go:87: undefined: models.GetLabels
routers/repo/issue.go:87: ctx.Repo.Repository.Id undefined (type *models.Repository has no field or method Id)
routers/repo/issue.go:100: undefined: models.GetIssues
routers/repo/issue.go:100: too many errors
# github.com/dsimansk/gogs/routers/user
routers/user/auth.go:63: type models.ErrUserNotExist is not an expression
routers/user/auth.go:253: type models.ErrUserAlreadyExist is not an expression
routers/user/auth.go:256: type models.ErrEmailAlreadyUsed is not an expression
routers/user/home.go:107: unknown models.Repository field 'Id' in struct literal
routers/user/home.go:219: unknown models.Repository field 'Id' in struct literal
routers/user/home.go:284: not enough arguments in call to models.GetUserIssueStats
routers/user/home.go:300: repo.Id undefined (type *models.Repository has no field or method Id)
routers/user/home.go:307: repo.Id undefined (type *models.Repository has no field or method Id)
routers/user/home.go:314: repo.Id undefined (type *models.Repository has no field or method Id)
routers/user/home.go:344: undefined: models.GetIssueById
routers/user/home.go:344: too many errors
# github.com/dsimansk/gogs/routers/api/v1
routers/api/v1/repo.go:31: repo.Id undefined (type *models.Repository has no field or method Id)
routers/api/v1/repo.go:58: undefined: models.GetUserById
routers/api/v1/repo.go:92: repos[i].Id undefined (type *models.Repository has no field or method Id)
routers/api/v1/repo.go:105: opt.Gitignore undefined (type gogs.CreateRepoOption has no field or method Gitignore)
routers/api/v1/repo.go:105: too many arguments in call to models.CreateRepository
routers/api/v1/repo.go:107: type models.ErrRepoAlreadyExist is not an expression
routers/api/v1/repo.go:108: undefined: models.ErrRepoNameIllegal
routers/api/v1/repo.go:113: repo.Id undefined (type *models.Repository has no field or method Id)
routers/api/v1/repo.go:113: too many arguments in call to models.DeleteRepository
routers/api/v1/repo.go:141: type models.ErrUserNotExist is not an expression
routers/api/v1/repo.go:141: too many errors
# github.com/dsimansk/gogs/cmd
cmd/serve.go:123: type models.ErrUserNotExist is not an expression
cmd/serve.go:197: undefined: models.GetPublicKeyById
cmd/web.go:202: undefined: "github.com/gogits/gogs/routers/user".Pulls
cmd/web.go:331: undefined: middleware.RequireAdmin
cmd/web.go:360: undefined: org.SettingsHooks
cmd/web.go:361: undefined: repo.WebHooksNew
cmd/web.go:391: undefined: repo.SettingsCollaboration
cmd/web.go:393: undefined: repo.WebHooksNew
cmd/web.go:412: undefined: repo.CreateIssue
cmd/web.go:413: undefined: repo.CreateIssuePost
cmd/web.go:413: too many errors
```

**Comment by tkisme** [comment]
I use diy
https://github.com/tkisme/gogs-openshift

**Comment by tvvocold** [comment]
@tkisme 
Cool

**Comment by manfer** [comment]
@tkisme
It works fine.

Anyone thinks it would be possible to use SSH authenticaion on openshift? I can see there is no access to .ssh folder but there is a .openshift_ssh folder. So anyone knows of a way to make gogs SSH access to git repositories work on openshift? Maybe there is nothing we can do?

**Comment by tkisme** [comment]
@manfer 
Not possible,only https
@tvvocold 
Maybe you can try it and feedback
@Unknwon 
Problem solved,please update doc ^_^

**Comment by jstrachan** [comment]
@manfer BTW we're working on this for using gogs with OpenShift 3.x (docker/kubernetes) using the built in OAuth in OpenShift.... https://github.com/fabric8io/openshift-auth-proxy

**Comment by Unknwon** [comment]
@tkisme :smile: thanks your effort!

So OpenShift is supported now?

**Comment by tkisme** [comment]
If anyone have any questions about it,submit issue on [this](https://github.com/tkisme/gogs-openshift)

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
