### ISSUE TITLE
Add possibility to restrict google oauth to a specific apps domain.

### ISSUE THREAD

**Issue by nleclerc** [gogits/gogs#998]
My company would like to use gogs for internal project ([our open source contribs are hosted on github](https://github.com/coqsenpate)) so it would be cool to be able to restrict google oauth to a specific google apps domain and disable self registration.

**Comment by Unknwon** [comment]
Hi, thanks your feedback! I'm not sure about what you mean by `specific google apps domain`, like Gmail business domain?

**Comment by matt-h** [comment]
Yeah, I would assume that is what @nleclerc means.

You can restrict oAuth to a specific domain name which should serve the purpose for this feature. http://stackoverflow.com/questions/10858813/restrict-login-email-with-google-oauth2-0-to-specific-domain-name

**Comment by Unknwon** [comment]
@matt-h thanks for the tip!

**Comment by nleclerc** [comment]
Yes, that's exactly what I meant. Thank you both :-)

**Comment by Unknwon** [comment]
This issue should be reconsidered as OAuth feature has been dropped in 0.6.13.
