### ISSUE TITLE
HTTPS URL is not a valid URL when creating a migraion repo without a top level domain

### ISSUE THREAD

**Issue by joedborg** [gogits/gogs#999]
When trying to add a new migration repo URL, you must have a TLD.
```
https://server/
```
"HTTPS URL is not a valid URL."

Works okay with
```
https://server.local/
```

**Comment by Unknwon** [comment]
Thanks your report, we'll get on this ASAP!

PS: it's backlog here: https://trello.com/c/ihzlOzbP/409-https-url-is-not-a-valid-url-when-creating-a-migraion-repo-without-a-top-level-domain

**Comment by Unknwon** [comment]
Hi @joedborg , I don't know which Gogs version are you using, because I can't rerpoduce this issue in t he latest version. Would you like to try on https://try.gogs.io and see how things are going?

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
